### ISSUE TITLE
Arara becomes non-responsive on LaTeX error

### ISSUE THREAD

**Issue by zoqaeski** [lervag/vimtex#1000]
### Explain the issue

Arara waits for input indefinitely if the tex file contains an error. As there's no way to send input to the arara process from vimtex (is there?), the process effectively becomes detached and the only way to stop it is to kill it from the command line.

1. Steps to reproduce: Create a document with an error, and compile with arara
```
% arara: lualatex

\documentclass{article}
\begin{document}

\commandnotdefined will make arara wait for input.

\end{document}
```
2. Expected behaviour: Compiler will stop on error
3. Observed behaviour: Arara waits for input which never comes, but `:VimtexStatus` says compiler is not running, and `:VimtexStop`/`:VimtexStopAll` do not kill the processes.

A way to fix this is to change the default `g:vimtex_compiler_arara` options from using `-v` to `--log`. The arara manual states that `-v` will wait on error for user input:

> The `--verbose` flag enables all streams to be flushed to the terminal – exactly the opposite of the silent mode. This flag also allows user input if the current command requires so.

Using logging allows the process to exit on error:

> The `--log` flag enables the logging feature of arara. All streams from all commands will
be logged and, at the end of the execution, an `arara.log` file will be generated.

**Comment by lervag** [comment]
I've updated as suggested. Does this solve your issue?

**Comment by zoqaeski** [comment]
Yes, all fixed.

**Comment by lervag** [comment]
Great! Thanks for reporting and suggesting the fix.
