### ISSUE TITLE
varioref Vref command highlighting wrong

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#1001]
### Explain the issue

The `\Vref` command from `varioref` is not correctly highlighted. The contained label is treated as normal text, including warnings for underscores, which are fine as labels.

### Minimal working example

```tex
\documentclass{article}

\usepackage{varioref}

\begin{document}

\section{Section 1}
\label{sec_one}

\section{Section 2}

\Vref{sec_one} does what you need. Still \vref{sec_one} works.

\end{document}
```

![2017-11-17t11 56 09 01 00](https://user-images.githubusercontent.com/1336287/32944104-96937fae-cb8e-11e7-950d-698921c6fdf0.png)

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
```

**Comment by lervag** [comment]
I think this should be fixed now, please test.

**Comment by languitar** [comment]
yes, works! thank you!

**Comment by lervag** [comment]
No problem :)
