### ISSUE TITLE
g:vimtex_view_general_callback doesn't seem to work

### ISSUE THREAD

**Issue by fsavje** [lervag/vimtex#1002]
I'm trying to set up Vimtex to do a forward search on successful (single shot) compilation. From what I understand from the documentation, `g:vimtex_view_general_callback` is the setting to do this. The following test code does, however, not work:

```vim
let g:vimtex_view_general_callback = 'MyViewCallback'
function! MyViewCallback() dict
  echom 123
endfunction
```

The callback works when using the `g:vimtex_compiler_callback_hooks`. E.g.:
```vim
let g:vimtex_compiler_callback_hooks = ['MyCallbackHook']
function! MyCallbackHook(status)
	echom 123
endfunction
```

I have no experience in plug-in development for Vim, but after a quick look at the source code, I suspect that [this line is the issue](https://github.com/lervag/vimtex/blob/64b541aba170d0164bb6e0c0b9584654982b955a/autoload/vimtex/view.vim#L45). In particular, that line seems to check whether something is saved to the variable `l:v.compiler_callback`, but the callback function [appears to be saved](https://github.com/lervag/vimtex/blob/64b541aba170d0164bb6e0c0b9584654982b955a/autoload/vimtex/view/general.vim#L22) to the variable `l:viewer.compiler_callback`.

Thanks for an excellent plug-in!

**Comment by lervag** [comment]
You are very close! The problem is that the callback function takes an argument, the compiler status. I.e., your example should work if you do this:

```vim
function! MyViewCallback(status) dict
  echom 'status' a:status
endfunction
```

If you need more help to write the actual callback function, let me know.

And thanks for the kind words! :)

**Comment by fsavje** [comment]
@lervag Thank you for the quick response!

I probably misunderstood something, but I followed [the documentation](https://github.com/lervag/vimtex/blob/64b541aba170d0164bb6e0c0b9584654982b955a/doc/vimtex.txt#L1808) where it reads:
```
*g:vimtex_view_general_callback*
  Sets the name of a function that is called within |vimtex#compiler#callback|
  after compilation has finished. The function does not take any arguments, [...]
```

The following _does not_ work for me unfortunately:
```vim
let g:vimtex_view_general_callback = 'MyViewCallback'
function! MyViewCallback(status) dict
  echom 'status' a:status
endfunction
```

`g:vimtex_compiler_callback_hooks` still works, however.

**Comment by lervag** [comment]
This works for me. See the test files I've just added in `test/issues/1002`. In that directory, you can do `vim -u minivimrc`. That will open vim (you can also use neovim) with a minimal configuration. Then you can do `\ll` to start compilation, and it will output "status 1" after compilation is finished. (I've disabled the viewer from automatically opening in the minimal test.)

However, you are right that the docs is wrong, so I'm fixing that now.

**Comment by fsavje** [comment]
Thanks again! Your minimal example works for me. However, as soon as I add `let g:vimtex_view_method = 'skim'`, it stops working (even if I keep `let g:vimtex_view_automatic = 0`). Is it the case that `vimtex_view_general_callback` isn't called if one picks Skim as viewer? And if so, how does one get a callback function with that viewer?

**Comment by lervag** [comment]
Yes, that is the case. `g:vimtex_view_general_callback` is only applicable when you use the `general` viewer and has no effect on the `skim` viewer. However, if you use the skim viewer, you can add a hook like this:

```vim
let g:vimtex_view_skim_hook_callback = 'MyCallbackHook'
function! MyCallbackHook(status)
  echom 123
endfunction
```

**Comment by fsavje** [comment]
Ok, I thought that it might be something along those lines. However, the documentation doesn't say anything about it. In fact, searching the source code, there is no mentioning of `vimtex_view_skim_hook_callback` at all. (It didn't work either.)

I'm sorry to bother with all this. The `vimtex_compiler_callback_hooks` route works excellent for my purposes, so need to add/change anything for my sake.

**Comment by lervag** [comment]
No both, and sorry: I've forgotten to add this for the skim viewer. It should be fixed now. Also, I was wrong, the callback hook is only called on successful compilations, and thus needs no argument:

```vim
let g:vimtex_view_skim_hook_callback = 'MyCallbackHook'
function! MyCallbackHook()
  echom 123
endfunction
```

**Comment by lervag** [comment]
FYI: I just pushed a commit that fixes it, but forgot to refer to this issue.
