### ISSUE TITLE
Some default mappings delay custom bindings

### ISSUE THREAD

**Issue by frebib** [lervag/vimtex#1004]
The two mappings in question are these:

Mapping | Command | Mode
-- | -- | --
dse | <plug>(vimtex-env-delete) | n
dsc | <plug>(vimtex-cmd-delete) | n
ds$ | <plug>(vimtex-env-delete-math) | n
tse | <plug>(vimtex-env-toggle-star) | n
tsd | <plug>(vimtex-delim-toggle-modifier) | nx

As I use the dvorak keyboard layout, I have remapped some of the default bindings to make using Vim more intuitive, see here: https://github.com/frebib/dotfiles/blob/85373cf577f4790f30840792d47af00c2657a384/.vimrc#L114-L117

The mapping of `t`/`d` followed by other characters causes my upward keypresses to be delayed until the timeout or until I press them 4 times is annoying enough to cause me frustration when trying to navigate around tex files.

Is there a way to disable just these bindings without disabling every default or without redefining the entire default configuration?

**Comment by lervag** [comment]
You can add custom mappings, e.g.

```vim
nmap <silent><buffer> lhs <plug>(vimtex-delim-toggle-modifier)
xmap <silent><buffer> lhs <plug>(vimtex-delim-toggle-modifier)
```

Here `lhs` is the new keys. Note that you should add this to your personal `ftplugin/tex.vim` file, or in a `BufRead` autocommand. That is, it is important that the maps are applied before vimtex is initialized. The main point is that the mappings are not created if the right-hand sides are already mapped to.

**Comment by frebib** [comment]
Is there any way to map these commands to nothing? `<Nop>` doesn't seem to work.
Ideally I'd just like them unbound as I'll probably never use them anyway

**Comment by lervag** [comment]
I've added an option that you can use to get the desired behaviour:

```vim
    let g:vimtex_mappings_disable = {
        \ 'n': ['tse', 'tsd'],
        \ 'x': ['tsd'],
        \}
```

Let me know if the feature is unclear.

**Comment by frebib** [comment]
Looks exactly what I need! I'll check it out and let you know, thanks :)

**Comment by frebib** [comment]
Yes! This was exactly what I needed, thank you for that:)

https://github.com/frebib/dotfiles/commit/3042e747e5e22f2d0e022b69737731c9e97ff2ee

**Comment by lervag** [comment]
No problem, I'm happy it works as desired :)
