### ISSUE TITLE
Syntax highlighting not working with vim-plug and Neovim

### ISSUE THREAD

**Issue by jonas-schievink** [lervag/vimtex#1005]
### Explain the issue

Syntax highlighting seems to not work at all when loading vimtex through vim-plug.

### Minimal working example

(doesn't matter - syntax highlighting does not work at all)

### Minimal vimrc file

The provided minimal vimrc from the issue template does not have this issue (as loading `vimtex` manually works fine).

This one reproduces the issue for me:

```vim
set nocompatible

" I've installed vim-plug in ~/.config/vim/autoload/plug.vim
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME

call plug#begin('~/.local/share/vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

filetype plugin indent on
syntax enable
```

Maybe I've broken something - It seems that vimtex' `after` folder is not respected. The rest of vimtex' features work fine, and `after` is only used for syntax highlighting. It should be noted that I've modified the runtimepath, but vim-plug *should* work with that (it only prepends directories).

### Version info

NVIM v0.2.2
up-to-date vim-plug and vimtex

**Comment by lervag** [comment]
The problem is your `runtimepath` string. The `$VIMRUNTIME` entry should come before the `vim/after` entry. I.e.

```vim
set runtimepath=$XDG_CONFIG_HOME/vim,$VIM,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after
```

**Comment by jonas-schievink** [comment]
Yep, that worked. Thanks!

**Comment by lervag** [comment]
No problem :)
