### ISSUE TITLE
Adjust text object `ip` for latex

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1006]
Built-in text object`ip` does not detect latex paragraphs properly; make `ip` cleverer to consider not only blank lines for paragraph boundaries. See following example
Current:
![screen shot 2017-11-27 at 10 45 54](https://user-images.githubusercontent.com/371756/33260467-3b615eb0-d360-11e7-9af9-9dbd6c2f1148.png)
Supposed:
![screen shot 2017-11-27 at 10 46 06](https://user-images.githubusercontent.com/371756/33260476-434051ae-d360-11e7-8bf9-132a2ab89976.png)

**Comment by kiryph** [comment]
Since this might be more complicated and I am not sure whether this is incredibly useful, feel free to close it for now and wait if a second person is interested in this.

**Comment by lervag** [comment]
I've tried this before and ended up walking away. There are so many edge cases here with all sorts of environments and stuff that one might want to keep part of a paragraph or not. So, unless you insist or unless there are more people who think this is an essential and useful feature, I will walk away also now.

**Comment by kiryph** [comment]
I do not insist 👑 . Just some notes how complicated this is:

Paragraphs end with

- blank line
- `\par`
- section commands (`\subparagraph, \paragraph, \subsubsection, \subsection, \section, \chapter, \part`}
- `\noindent, \indent`, e.g.
```tex
This is the text in first paragraph. This is the text in first 
paragraph. This is the text in first paragraph. \par
\noindent %The next paragraph is not indented
This is the text in second paragraph. This is the text in second 
paragraph. This is the text in second paragraph.
```
- \begin{flushleft,flushright,center}
- \end{flushleft,flushright,center}
- floating environments
- ...

Part of a paragraph can be
- math environments
- quotations
- ...

**Comment by lervag** [comment]
Yes, exactly. And thanks. From a pragmatic point of view, I think the efforts required to properly handle this is not "payed for" by the benefits.

However, one could probably add something that works "quite well" given that people write "sensible" LaTeX code with not too much effort. Still, I think it will take quite some time to make this work well, and I would rather spend time on other things (e.g. #1009).
