### ISSUE TITLE
RFC vimtex text object `iP` should not select trailing blank lines 

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1007]
I noticed that `viP` selects trailing blank lines. IMHO it shouldn't do this only `vaP`.

![screen shot 2017-11-27 at 10 54 00](https://user-images.githubusercontent.com/371756/33260798-4a05ec5a-d361-11e7-9080-89635c7c4d2b.png)

**Comment by kiryph** [comment]
And I also checked this quickly. Very good!!!

**Comment by lervag** [comment]
:)
