### ISSUE TITLE
Make [[, ]], [],][ exclusive as defined under :h exclusive

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1008]
😇  I think the `exclusive` behavior of the builtin `}` could be resembled for ]], [[, ][, [], i.e. the documented exceptions should be taken into account.   Just for clarification: `exclusive` and `inclusive` affect the behavior when using **operators**; see the help again:

> When **inclusive**, the start and end position of the motion are included in the operation.
> When **exclusive**, the last character towards the end of the buffer is not included [in the operation].
> Linewise motions always include the start and end position [when used after an operator].
> 
> There are however, two general exceptions:
> 1. If the motion is exclusive and the end of the motion is in column 1, **the
>    end of the motion is moved to the end of the previous line** and the motion
>    becomes inclusive.  Example: "}" moves to the first line after a paragraph,
>    but "d}" will not include that line.
> 						*exclusive-linewise*
> 2. If the motion is exclusive, the end of the motion is in column 1 and the
>    start of the motion was at or before the first non-blank in the line, the
>    motion becomes linewise.  Example: If a paragraph begins with some blanks
>    and you do "d}" while standing on the first non-blank, all the lines of
>    the paragraph are deleted, including the blanks.  If you do a put now, the
>    deleted lines will be inserted below the cursor position.

This would mean for `][`. Starting with following situation:
![screen shot 2017-11-27 at 11 16 59](https://user-images.githubusercontent.com/371756/33261848-87406bce-d364-11e7-9afb-1d18ebd572d2.png)

Yellow block is the cursor. `d][` should do the same as `d2}` (switch to linewise (exception 2) and should delete before the last blank line of the current section(exception 1)). However right now you get

![screen shot 2017-11-27 at 11 20 49](https://user-images.githubusercontent.com/371756/33261996-0aa82a10-d365-11e7-9790-71e8b985c37a.png)

but I would expect (`d2}`):

![screen shot 2017-11-27 at 11 24 33](https://user-images.githubusercontent.com/371756/33262137-8fcc9f64-d365-11e7-8a29-44d7be6e4437.png)

For more illustration of inclusive vs exclusive see also:
https://github.com/andymass/vim-matchup#inclusive-and-exclusive-motions

**Comment by lervag** [comment]
Agreed, and I think this should work after the recent commit.

**Comment by lervag** [comment]
However, I might have misunderstood. Let me know if there are more to it than what I've just implemented.

**Comment by kiryph** [comment]
Thanks for the update.

1. Operating towards the end of the buffer either with `]]` or `][` work as I expect it. ✔️ 

2. However, operating towards the begin of the buffer with either builtin `{` or `[]`, `[[` do not work as I would expect it. This seems to be an issue of vim itself:
`d2{` deletes including the line you would move to with `2{` and works characterwise even though the cursor is on the first non-blank. Both exceptions mentioned under `:h exclusive` seem to be ignored:
- exception 1: end of the motion is moved to the end of the previous line and the motion becomes inclusive
- exception 2: start of the motion was at or before the first non-blank in the line, the motion becomes linewise.

Consider following example:
![screen shot 2017-11-27 at 22 30 57](https://user-images.githubusercontent.com/371756/33290410-e1c6751c-d3c2-11e7-97b5-6ad2bc8c1ede.png)

Now pressing `d2{` and you get:
![screen shot 2017-11-27 at 22 31 08](https://user-images.githubusercontent.com/371756/33290417-e7e3ae38-d3c2-11e7-9671-b7c3fdf6caba.png)

Expected (1 additional blank line; and leading blanks are retained) (not entirely sure):
![screen shot 2017-11-27 at 22 33 31](https://user-images.githubusercontent.com/371756/33290453-0471c29c-d3c3-11e7-9537-897394337732.png)

What do you think? Did I miss something in the documentation and this is intended?

Just to make sure: I am talking about `{`, not about vimtex `[[` and `[]`; they are consistent to `{`.

**Comment by kiryph** [comment]
BTW, the `|exclusive|` tag could be re-added to the documentation.

**Comment by lervag** [comment]
I find the docs on this matter a little bit confusing. It is not clear to me exactly what is the expected behaviour. Perhaps @andymass has an idea, considering that he has written about the inclusive/exclusive motions when working with vim-matchup?

**Comment by andymass** [comment]
What I didn't make completely clear in match-up's readme is that for exclusive motions, the "exclusive" part is always with respect to the position furthest in the buffer, not, for example, the target of the motion.

For instance in `{123█567}`, `d[{` gives `█567}` while `d]}` gives `{123}`.

Apologies for any confusion I've caused.  Although my documentation doesn't seem to explain this precisely, as far as I know match-up works correctly according to `:help exclusive` and empirical behavior.

So, regarding @kiryph's question: the confusing passage is 

> If the motion is exclusive and **the end of the motion is in column 1**

The key misunderstanding is the definition of "end of the motion," by which vim apparently means the position closest to the end of the buffer.  In your example, @kiryph, with `d2{`, this position is clearly not at column 1.  Personally, I think the vim documentation should be improved, because I am a native English speaker and I read it wrong the first time too.

The following operator can be helpful to see what's going on:
```vim
function! VOp(type)
  echo a:type
  if a:type == 'line'
    normal! '[V']
  else
    normal! `[v`]
  endif
endfunction
set operatorfunc=VOp
nnoremap <space> g@
set noshowmode
```

By the way, things get even more confusing when you start getting into "forced" operators like `dv]}`, `dV]}` etc.  I had to deduce a number of edge cases using trial and error and even by reading vim's code.

**Comment by kiryph** [comment]
@andymass thank you for your insight:

> The key misunderstanding is the definition of "end of the motion," by which vim apparently means the position closest to the end of the buffer.

This was very helpful to understand it better.

> For instance in {123█567}, d[{ gives █567} while d]} gives {123}.

This is a very good example to show how vim handles this and makes me wonder whether I would appreciate a change in vim itself.

I think

- the word `exclusive` is misleading here and IMHO does not apply when operating towards the beginning of the buffer,
- feels inconsistent between both directions
- and I am not sure if this difference is very useful and if the operation works as a general user would expect/intend it (see myself). 

What is your opinion? Does the behavior of vim work as you would expect it?

**Comment by kiryph** [comment]
Following situation works as I would expect from `d[[` and `d]]`
![screen shot 2017-11-28 at 08 43 22](https://user-images.githubusercontent.com/371756/33307805-3a4a1a5e-d418-11e7-9ac7-4b8720d60fb6.png)

With `d[[` you can delete the previous section and with `d]]` the middle section.

Deleting till the beginning of a section excluding the section command when the cursor is located within a section, I will use `d[iP` from vim-ninja-feet and the vimtex text-object `iP`.

I haven't found yet a good example for `d[]` and `d][`.

However, I consider this myself as settled.

**Comment by lervag** [comment]
Thanks @andymass!

I have to admit that I rarely use these motions myself. I will be happy to change things if you have good suggestions for improving them. Good examples of expected behaviour makes it easy to create new tests and thus to develop the new behaviours.

Let's consider this settled for now, but (as always) feel free to reopen or open new issues if you have some ideas.

**Comment by andymass** [comment]
> What is your opinion? Does the behavior of vim work as you would expect it?

I have been using vim so long that it's completely expected by me.  It's only confusing when I think about it too much (and try to write a plugin that handles all the corner cases).  But, yes, and the alternative is worse- consider;

- You probably already rely on the behavior if you use `dl`, `dh`, or `dw` and `db`.

- Counts make sense, `d3l` and `d3h` will each delete 3 characters, non-overlapping.  Imagine the cursor is actually zero width and located where it is in insert mode (cursor really on the 5).

            123|567   +  d3l  =>  123
            123|567   +  d3h  =>  567 

- Arguably, `[[` is better if it excludes the cursor.  `d[[` feels pretty natural here.

```tex
\section{Details}

█orem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy
```

- What I agree is a bit confusing/asymmetric is `d[{` vs `d]}` including or not including the `{`/`}` in `{123█567}`.  But, you can always use `dv]}`, `vd]}`, or `d]}x`.
 
Anyway, it sounds like vimtex handles `[[` etc. correctly now, with the minor exception that it doesn't go to the top or bottom of buffer like the normal `[[`/`]]` do.

**Comment by kiryph** [comment]
@andymass Again, thanks for sharing your vim knowledge 👨‍🏫 .

> What I agree is a bit confusing/asymmetric is d[{ vs d]} including or not including the {/} in {123█567}. But, you can always use dv]}, vd]}, or d]}x.

I am actually not missing `dv]}` but a possibility for `d[{` to keep the opening curly brace.

Is there also another variant that I have missed?

@lervag do you mind adding

> with the minor exception that it doesn't go to the top or bottom of buffer like the normal `[[`/`]]` do.

 (I am getting too greedy)

**Comment by lervag** [comment]
Done! :)

**Comment by kiryph** [comment]
Thanks. However, I've noticed that `][` and `[]` should also move to the top and bottom of a buffer.

A second issue is: there shouldn't be a section end before the first section (in the picture below between `\begion{document}` and `\section{First section}`).

Compare following two pictures. The first shows a `cpp` file and the second shows a `tex` file.
The background color `light green` and `light orange` indicate those lines which you reach with `][` and `[]`:

![screen shot 2017-11-29 at 12 11 33- -and- -ft c](https://user-images.githubusercontent.com/371756/33374547-ea68da62-d506-11e7-88f1-9194d7f67d45.png)

and the tex file
![screen shot 2017-11-29 at 11 23 48- -and- -ft tex](https://user-images.githubusercontent.com/371756/33374571-0ab02cf8-d507-11e7-86a4-8f06897f5c3a.png)

*(personal note: coloring has been done with https://github.com/chrisbra/BackgroundColor.vim)*

**Comment by lervag** [comment]
Hm... I'm sorry, but I'm a little bit confused. If I understand correctly, you are saying three things:

1. `[]` should also go to top of file.
2. `][` should also go to bottom of file.
3. `[]` and `][` should never stop above the top section/chapter command except at top of file.

Did I get that right?

**Comment by kiryph** [comment]
Yes, you got it right.

This is probably not the most important feature request. Most user will press `gg` or `G` to go to top and to bottom.
On the other side since the motions `[[`, `]]`, `[]`, `][` are more advanced keeping them aligned as much as possible between filetypes can help that they are more predictable. However, not all $VIMRUNTIME/ftplugins behave this way: e.g. $VIMRUNTIME/ftplugin/vim.vim, $VIMRUNTIME/ftplugin/python.vim, $VIMRUNTIME/ftplugin/ruby.vim.

Since you already changed it for `[[` and `]]`, I would appreciate it if you would change it for `[]` and `][` as well.

**Comment by lervag** [comment]
I agree that it makes sense to make things as consistent between filetypes as possible, and so I appreciate your effort in investigating this issue.

I think you will find that the latest update fixes this. Let me know if I missed something.

**Comment by kiryph** [comment]
Thanks. They work as expected within my test file.

**Comment by lervag** [comment]
Great! :)
