### ISSUE TITLE
g:vimtex_quickfix_blgparser option is a string, not a dictionary

### ISSUE THREAD

**Issue by brianbuccola** [lervag/vimtex#1011]
The `g:vimtex_quickfix_blgparser` option seems to have changed from being a dictionary to a string. This no longer works:

```vim
let g:vimtex_quickfix_blgparser = {'disable': 1}
```

But this does:

```vim
let g:vimtex_quickfix_blgparser = 'disable'
```

Assuming that it should be kept as a string, the documentation should be updated. Right now, it says:

```
The option is a dictionary with the following keys:

    disable
        Disable the parsing of *blg* entries.
```

However, I'm curious why this option is a string (and why it was a dictionary) in the first place. If it's an enable/disable kind of option, then why not encode it like every other such option? Namely, as an integer/boolean: `1` for enable, `0` for disable.

**Comment by brianbuccola** [comment]
Actually, it looks like setting `let g:vimtex_quickfix_blgparser='disable'` disables *everything*. I'm not even getting normal errors anymore.

**Comment by lervag** [comment]
No, the option should be a dictionary. When you set it to a string value, it will disable everything because it is an error.

I am not able to reproduce your problem, though. Could you provide a minimal example?

**Comment by brianbuccola** [comment]
Hmm... I can't reproduce it myself anymore. I'm not sure what I was doing wrong the other day.

In any case, I'm still curious why this option is encoded as a dictionary, rather than as `0`/`1`, given that it's a binary option. What is the rationale?

**Comment by lervag** [comment]
The reason is simple: I partly anticipate that this feature (i.e. the blg parser) might evolve in the future, and I would prefer to avoid defining many more options. Thus I decided to let the option `g:vimtex_quickfix_blgparser` define a dictionary to allow future configuration. However, at the moment, the option only allows to disable the feature alltogether.

**Comment by brianbuccola** [comment]
Makes sense -- thanks!

**Comment by lervag** [comment]
No problem :)
