### ISSUE TITLE
Compiling with Latexmk Does Nothing

### ISSUE THREAD

**Issue by abangfarhan** [lervag/vimtex#1012]
I am using Gvim 8.0 on Windows 10. I already have Latexmk installed and have successfully compiled
Latex documents with it before. When I try to compile a minimal Latex document (using `\ll` or `:VimtexCompile`), it said

```
vimtex: Compiler started in continuous mode
```

But in the working directory, no documents were created, and when I try to stop the compiling process (using `\lk` or `:VimtexStop`), it said

```
vimtex: There is not process to stop
```

And when I execute `:VimtexCompileOutput`, the following message was shown in a temporary file on ~\AppData\Local\Temp\VIA6741.tmp

```
Latexmk: Stopping because executing following code from command line
    $success_cmd = '"D:Program
gave an error:
    Can't find string terminator "'" anywhere before EOF at (eval 9) line 1.
```

Following the instruction, I use the minimal configuration below (I modified it a bit so the plugin can be run using Vundle).

```vim
source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
let $VIMFILES = $VIM . "\\vimfiles\\"
behave mswin

set nocompatible

set rtp+=$VIMFILES/bundle/Vundle.vim
call vundle#begin('$VIMFILES/bundle/')
Plugin 'lervag/vimtex'
call vundle#end()

filetype plugin indent on
syntax enable

set guifont=Consolas:h10

let g:tex_flavor = 'tex'
let g:vimtex_compiler_method = 'latexmk'
```

The Latexmk on my computer is version 4.52c.

**Comment by lervag** [comment]
I'll look into this more later, but I was thinking that `:h vimtex-faq-windows` might be helpful here, i.e. to set `g:vimtex_compiler_progname` as specified there.

**Comment by abangfarhan** [comment]
Thanks for the feedback. I can confirm now that the plugin compiles the latex file continuously after including this on vimrc

```
let g:vimtex_compiler_progname = v:progname
```

**Comment by lervag** [comment]
Great! In that case, I'm closing this. I've previously worked quite hard getting things to work on Windows. I am no windows expert, and so if things work, I won't touch anything.
