### ISSUE TITLE
Highlighting of \end{subequations}

### ISSUE THREAD

**Issue by urbainvaes** [lervag/vimtex#1019]
Sorry, I wanted to cancel the issue but opened it instead, and there doesn't seem to be a way to delete it.

Initially, I wanted to report the strange highlighting of \end{subequations}, but the issue does not seem to be related to vimtex because it happens with an empty .vimrc.

Thank you.

**Comment by clason** [comment]
That doesn't mean that vimtex can't improve on the vanilla syntax highlighting (it does come with its on `syntax/tex.vim`)! I've noticed the wrong highlighting myself, and although it hasn't interfered with indentation or folding so far, it'd be nice to fix this. 

@lervag Would this be complicated?

**Comment by lervag** [comment]
It might not be complicated. I don't know yet. But it would help to get an example of the issue.

**Comment by clason** [comment]
Sure: a MWE is
```
\documentclass{article}
\begin{document}
\begin{subequations}
\end{subequations}
\end{document}
```
(the `documentclass` and `document` is only needed to make sure the filetype is set to LaTeX).

Screenshot:

<img width="259" alt="screen shot 2017-12-16 at 13 35 22" src="https://user-images.githubusercontent.com/2361214/34070422-07ed10aa-e266-11e7-9356-75d655c51aec.png">

The syntax region for `\end{subequations}` is `texBadMath` (the one for `\begin{subequations}` is `texBeginEndName`).

**Comment by lervag** [comment]
Ok, this should work now. However, I would be very happy if one of you guys could send an email to Charles Campbell and ask him to remove `subequations` from the `texBadMath` group, or at least have him explain why he thinks it should be there. I think that this issue should rather be fixed by Charles, not patched by me like this...

**Comment by clason** [comment]
@lervag Thanks! 

Actually, that may have already been fixed upstream yesterday (as part of the rather scattershot https://github.com/vim/vim/commit/f0b03c4e98f8a7184d8b4a5d702cbcd602426923, so should be in  vim 8.0.1401 and later). When neovim next pulls in runtime updates, I'll make a note here so the patch can be reverted.

**Comment by clason** [comment]
@lervag Just a heads-up: It seems that Charles Campbell also removed some standard Math Zones in that update (see the link above), and now has moved all package (including amsmath) related information into several add-on files: http://www.drchip.org/astronaut/vim/index.html#LATEXPKGS

How do you feel about bundling them? At least the amsmath one seems crucial to me.

**Comment by lervag** [comment]
Seems fine by me.
