### ISSUE TITLE
Selecting between \left( and \right) 

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#1022]
This is probably me that is missing some basic text-object or similar, but...  

When writing equations, you can select a subformula in brackets with the appropriate `va(` (or `vi(` or `va[` or the variations thereof). 

But if the subformula is surrounded with `\left( ... \right)` it is not so easy.  If your cursor is on the `\left(` or `\right)` part the matching command is highlighted correctly, but  I could not find a text-object encompassing everything, including the delimiters. If I go into the subformula, `va(` collects the final +`\right)` but not the starting `\left`: 

![selection_028](https://user-images.githubusercontent.com/6414907/34082335-637859ba-e35c-11e7-896f-3557feac917d.png)

Is there any text-object usable here? I was hoping in `t` (tag) but it seems not working. What would be really handy is something that selects between highlighted delimiters (`i` and `a` variants), no matter which they are... 

 ```
    \begin{equation}
        v_{o1} = V_g \left(1 + \frac{R_A}{R_p(P)}\right)  - V_{cc}\frac{R_A}{R_p(P)} = 
        \frac{V_{cc}}{2}\left(1 - \frac{R_A}{R_p(P)}\right)
    \end{equation}
```

Thank for your time and Merry this-period-of-the-year to you all!

**Comment by andymass** [comment]
Do `vad` and `vid` work for you?

**Comment by Rmano** [comment]
As I supposed. Operator (`/me`) error. Thanks, and closing.

**Comment by lervag** [comment]
Thanks for pitching in, @andymass! :)
