### ISSUE TITLE
Feature request: `ysiwc` with vim-surround

### ISSUE THREAD

**Issue by KireinaHoro** [lervag/vimtex#1024]
A pre-defined way to surround a text object with a command (say `\emph{}`) is useful. The following works neatly:

```vim
let g:surround_{char2nr('c')} = "\\\1command\1{\r}"
```

The above comes from https://github.com/tpope/vim-surround/issues/47 .

**Comment by lervag** [comment]
I do not understand what you want here. Do you want me to add a feature similar to what is already provided by vim-surround?

**Comment by KireinaHoro** [comment]
Vim-surround provides the ability to wrap a text onject in _something_. I
mean that vimtex should provide a LaTeX command as one of that _something_.
This can be achieved by the conf I pasted above.

2017年12月21日(木) 5:22 Karl Yngve Lervåg <notifications@github.com>:

**Comment by lervag** [comment]
I don't agree with this. As you say, it is a single line of configuration from vim-surround, and I think people who want this should be aware that this is a vim-surround feature, not a vimtex feature. So I want people to manually add that to their vimrc file if they want it.
