### ISSUE TITLE
Error on startup: file not found: asy.vim

### ISSUE THREAD

**Issue by schoettl** [lervag/vimtex#1025]
When I start vim with a latex file, the following error shows up (until I confirm by pressing enter):

File not found: syntax/asy.vim

This file is included in `after/syntax/tex.vim`, line 357.

I created an empty file `asy.vim` in vimtex's `after/syntax/` directory to fix the issue.

From where does this file come? Is it a dependency?

**Comment by lervag** [comment]
Could you provide an example where this is reproduced?

**Comment by schoettl** [comment]
Not anymore. Weired. I had this startup error for months.

Today I created the missing file with `touch asy.vim`. Then it worked.

Now I just deleted it again (there is no such file anymore in `~/.cache`).

I also fixed another bug in my vimrc, a vimtex setting was set to `0` instead to `[]`. But this seems unrelated for me...

**Comment by lervag** [comment]
No, not quite: I've seen this myself, but never looked into it properly. I've used `try/catch` to ignore this error if the `asy.vim` file is missing, but for some reason, the error is not ignored if other errors are displayed.

I'll look into it now. I've managed to reproduce by ensuring that vimtex throws an error during initialization.

**Comment by schoettl** [comment]
Interesting, that's an explanation.

Great plugin by the way, thank you! As a occasional LaTeX user I unfortunately only use very few of all the cool mappings and functionality.

**Comment by schoettl** [comment]
Nice, thank you!

**Comment by lervag** [comment]
Thanks! I think it's OK to just use the features one find the most useful and interesting, even if that is only compilation and similar. I think the documentation mapping `K`, as well as the text objects (see the last part of  `:h vimtex-mappings`) are useful to know about.

**Comment by lervag** [comment]
I think the problem is fixed now.
