### ISSUE TITLE
Confusing configuration variable

### ISSUE THREAD

**Issue by manasb** [lervag/vimtex#1026]
1. Set `let g:vimtex_imaps_enabled = 0` in `~/.vimrc`
2. Expected insert mode mappings to be disabled
3. Insert mode mappings not disabled, have to set `let g:vimtex_imaps_enabled = 1` for insert mode mappings to be disabled. I personally found this confusing, I don't know if anyone else feels the same. Based on the variable name, setting it to `1` should enable this feature and `0` disable?

Relevant line in `vimtex.vim`:
https://github.com/lervag/vimtex/blob/master/autoload/vimtex.vim#L477

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

let g:vimtex_imaps_enabled = 0
```

**Comment by lervag** [comment]
No. With `let g:vimtex_imaps_enabled = 0`, the imaps are disabled, and the `\lm` map to show the imaps is not enabled.

I think you might be confused about what is an insert mode map. Did you read `:h vimtex-imaps`?.

Or perhaps I misunderstand you. If so, could you please be more specific? E.g., what is the mapping that you think should be disabled that is not disabled?
