### ISSUE TITLE
auto complete \let

### ISSUE THREAD

**Issue by joaocortes** [lervag/vimtex#1027]
Is it possible to enable auto completion of `\let` statements? Consider the following example:

```tex
% main.tex
\documentclass[10pt]{report}
\usepackage{subfiles}

\let \da=\leftrightarrow

\begin{document}
\subfile{./subfile.tex}
\end{document}

% subfile.tex
\documentclass[./main.tex]{subfiles}
\begin{document}

$\da$
    
\end{document}
```

In the main.tex file I define an alias `\da` for `\leftrightarrow`. When typing in `subfile.tex` I would like to be able to autocomplete that alias.

----

Edit: @lervag took the liberty of updating this post to make it more clear.

**Comment by lervag** [comment]
I'm not 100% sure what you mean. Do you want to be able to autocomplete `\da`? I.e., write `\d<c-x><c-o>`  to get `\da`?

**Comment by joaocortes** [comment]
Yes, that's it. Actually, I am navigating trough the possible completions via the pop up menu.
It would be a simple way to check if the alias really exists.

**Comment by lervag** [comment]
Should work now.

**Comment by joaocortes** [comment]
Thanks, I updated and it is working as I was expecting
