### ISSUE TITLE
Support LaTeX3 indentation style guidelines

### ISSUE THREAD

**Issue by zoqaeski** [lervag/vimtex#1028]
The [LaTeX3 style guidelines](http://mirrors.ctan.org/macros/latex/contrib/l3kernel/l3styleguide.pdf) specify a certain indentation style which Vim's indentation doesn't seem to handle very well.

> ### 3 Format of the code itself
> The requirement for fewer than 80 characters per line applies to the code itself as well as the surrounding documentation. A number of the general style principles for LaTeX3 code apply: these are described in the following paragraph and an example is then given.
>
>With the exception of simple runs of parameter (`{#1}`, `#1#2`, etc.), everything should be divided up using spaces to make the code more readable. In general, these will be single spaces, but in some places it makes more sense to align parts of the code to emphasise similarity. (Tabs should not be used for introducing white space.)
>
>Each conceptually-separate step in a function should be on a separate line, to make the meaning clearer. Hence the false branch in the example uses two lines for the two auxiliary function uses.
>
>Within the definition, a two-space indent should be used to show each “level” of code. Thus in the example `\tl_if_empty:nTF` is indented by two spaces, but the two branches are indented by four spaces. Within the false branch, the need for multiple lines means that an additional two-space indent should be used to show that these lines are all part of the brace group.
>
>The result of these lay-out conventions is code which in general looks like the example:
>```
>\cs_new:Npn␣\module_foo:nn␣#1#2
>␣␣{
>␣␣␣␣\tl_if_empty:nTF␣{#1}
>␣␣␣␣␣␣{␣\module_foo_aux:n␣{␣X␣#2␣}␣}
>␣␣␣␣␣␣{
>␣␣␣␣␣␣␣␣\module_foo_aux:nn␣{#1}␣{#2}
>␣␣␣␣␣␣␣␣\module_foo_aux:n␣{␣#1␣#2␣}
>␣␣␣␣␣␣}
>␣␣}
>```

The problem is that the opening and closing brackets don't get indented at the appropriate level, and are indent at the same level as the previous line. The example quoted from the documentation would be automatically indented as follows:
```
\cs_new:Npn␣\module_foo:nn␣#1#2
{
␣␣\tl_if_empty:nTF␣{#1}
␣␣{␣\module_foo_aux:n␣{␣X␣#2␣}␣}
␣␣{
␣␣␣␣\module_foo_aux:nn␣{#1}␣{#2}
␣␣␣␣\module_foo_aux:n␣{␣#1␣#2␣}
␣␣}
}
```
Do you think it is possible to set up the auto-indentation so that it behaves according to the guidelines?

**Comment by lervag** [comment]
Sorry for taking so long to reply. I've been (and still am) uncertain on how to deal with this. Indenting is quite hard (at least I think so). In the current implementation, I've solved it quite consistently and with a simple formula. But to support what you ask I think we need many more edge cases. E.g.:

```tex
% You want this:
\command{
  % start indent here
  }
% stop indent here

% and this
\command
  {% start indent here
  }
% stop indent here
```

The above example shows that the indent level of the current line is not simply a count of opening and closing braces. It also depends on the location of the braces. With the current code, the indent would be as in the examples, except the closing brace will be unindented, and the opening brace will be unindented. That is, the current rule is that closing braces affect the current line, and opening braces affect the following line (to put it simply).

In a way, I think the current implementation is close to ideal. If I were to somehow know that `\cs_new:Npn␣\module_foo:nn␣#1#2` should start an indent, and simultaneously know how to recognize that the block is ended, then I could keep the current indentation rule for the braces and add a new rule based on the command itself. To be more specific, assume that the command is `\somecommand`, we could add a rule that is as follows:

1. If `\somecommand` does not end in an opening brace, then add one indent and go to 2.
2. Remove one indent when the block is finished (we could use a heuristic such as assume that the block is ended by an empty line).
