### ISSUE TITLE
Q: Is <plug>(vimtex-cmd-create) supposed to be repeatable?

### ISSUE THREAD

**Issue by doronbehar** [lervag/vimtex#1030]
According to the discussion conducted in #103, mappings like:
```vim
<plug>(vimtex-env-delete)
<plug>(vimtex-env-delete-math)
<plug>(vimtex-env-change)
<plug>(vimtex-env-change-math)
<plug>(vimtex-cmd-delete)
<plug>(vimtex-cmd-delete-math)
<plug>(vimtex-cmd-change)
<plug>(vimtex-delim-delete)
<plug>(vimtex-delim-change-math)
```
Are supposed to be repeatable using [Tim Pope](http://tpo.pe/)'s [`vim-repeat` plugin](https://github.com/tpope/vim-repeat)'s function `repeat#set`.

The mapped vimtex command I use the most often is
```vim
<plug>(vimtex-cmd-create)
```
And I can't repeat it using `.` while editing. I tried to find out whether this feature should work with `git grep repeat#set\|vimtex-cmd-create` and I saw that many of the commands above are repeatable but I guess `<plug>(vimtex-cmd-create)`.

I tried to add this to my `.vimrc` but it did not help:
```vim
silent! call repeat#set('<plug>(vim-cmd-create)',v:count)
```

Thanks for making this wonderful plugin and thank you for your time.

**Comment by lervag** [comment]
> Thanks for making this wonderful plugin and thank you for your time.

Thanks! :)

The normal mode version of the map should support repeats, but I found a bug that I'm fixing as we speak. The insert mode version and the visual mode version does not support repeat. The visual mode could perhaps support it if there is a logical way to do it (but I don't think there is).

**Comment by doronbehar** [comment]
You are wonderful! :-]
