### ISSUE TITLE
<plug>(vimtex-cmd-create) behaves weird in visual mode with non english letters e.g Hebrew

### ISSUE THREAD

**Issue by doronbehar** [lervag/vimtex#1031]
### Explanation

When editing latex documents with a language other than English (tested with Greek as well) and using `<plug>(vimtex-cmd-create)` after selecting text in visual mode, it inserts more letters to the command other than what was visually selected. Here is the **Observed behaviour**:

For example, let's select the first two words and press <kbd>F7</kbd>:

```tex
This is English text with some Hebrew letters:

מסוק הוא כלי טיס
```

It inserts the 1st letter of the 3rd word (`כ`) as well into the command.

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}

מסוק הוא כלי טיס היוצר עילוי באמצעות סיבוב מדחף בעל להבים (רוֹטוֹר). בעגה המקצועית מוגדר המסוק כ"כלי טיס בעל כנף סובבת" (בניגוד למטוס, שהוא "כלי טיס בעל כנף קבועה").

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable
```

**Comment by lervag** [comment]
Thanks, it seems I did not quite think about multibyte characters when implementing this. Should work now.
