### ISSUE TITLE
disable the map jk as esc in math mode

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#1035]
I am gladly found that vimtex has mapped `` `a`` to `\alpha` only in math-mode (surrounded by `$` or `\[`), personally, I have also defined the following map for escape:
```vimrc
imap jk <esc>
```
This cause some problems when I type math subscript, such as `$\Gamma_{jk}^i$`.  Which will map `jk` to `<esc>` also, which means, I must wait for a short time after typing `j` so that the imap not recognize the map key. It is quite annoying and did there any solution such that 
1. outside math-mode, `jk` maps to `<esc>`
2. and in math-mode, `jk` maps to `jk`?

**Comment by lervag** [comment]
No, there is nothing from vimtex directly that can do this, but it is quite simple to make a custom mapping that you can add to your personal `ftplugin/tex.vim` file or in an autocommand:

```vim
inoremap <expr> jk ITexEscape()

function! ITexEscape()
  let l:is_math = match(map(synstack(line('.'), max([col('.') - 1, 1])),
        \ 'synIDattr(v:val, ''name'')'), '^texMathZone[A-Z]S\?$') >= 0
  return l:is_math ? 'jk' : "\<esc>"
endfunction
```

**Comment by vanabel** [comment]
That's it, thanks a lot. Although I don't under stand the code exactly...

I put your code in my `vimrc` and it works as expected. Thanks again!

**Comment by lervag** [comment]
No problem!

Note, if you put this in your `vimrc` file, you should put the `inoremap` in an autocommand, e.g.:

```vim
augroup my_vimrc_autocommands
  autocmd!
  autocmd FileType tex inoremap <expr> jk ITexEscape()
augroup END
```

Of course, the `augroup` can be whatever you want it to be.
