### ISSUE TITLE
Create environment with shortcut

### ISSUE THREAD

**Issue by dbacc** [lervag/vimtex#1036]
As far as I can see there seems to be no equivalent of

`*<plug>(vimtex-cmd-create)*`

for environments. 
Is this on purpose?
Wouldn't it be benificial to write the name of some environment name like
`equation`
and after pressing, say `<F5>` this would produce
`\begin{equation}

\end{equation}`
with the cursor positioned in the middle of the environment.

**Comment by j-jith** [comment]
You should ideally use a snippets plugin like [UltiSnips](https://github.com/SirVer/ultisnips) or [SnipMate](https://github.com/garbas/vim-snipmate) for this purpose. Your suggestion has already been implemented in the [tex.snippets](https://github.com/honza/vim-snippets/blob/master/snippets/tex.snippets) file found at [honza/snippets](https://github.com/honza/vim-snippets).

**Comment by lervag** [comment]
Yes, @j-jith is spot on. I don't want to implement features that are better handled by other plugins, and this is one such feature. I agree it seems somewhat inconsistent in that we already have `<plug>(vimtex-cmd-create)`, but the complexity of these features are not really comparable.

So, please see the section on snippets and templates in `:h vimtex-non-features`.

**Comment by dbacc** [comment]
Okay, that makes sense.
However, I have troubles using the snippets feature.

I currently added the following line to my `.vimrc` (according to the snippet in honza/snippets)

```        inoremap <silent> <F5> <F5><c-r>=UltiSnips#Anon('\\begin{${1:env}}{0:${VISUAL}}\end{$1}', '<F5>', '', 'i')<cr> ```

This doesn't create any linebreaks, but adding `<cr>`s inside the command leads to a syntacx error 

```
inoremap <silent> <F5> <F5><c-r>=UltiSnips#Anon('\\begin{${1:env}}<cr>{0:${VISUAL}}<cr>\end{$1}', '<F5>', '', 'i')<cr>
```
```
E115: Missing quote: '\\begin{${1:env}}
E116: Invalid arguments for function UltiSnips#Anon('\\begin{${1:env}}```

**Comment by lervag** [comment]
I don't think you can use these anonymous snippets like that. The example from the docs is this:

> `inoremap <silent> $$ $$<C-R>=UltiSnips#Anon(':latex:\`$1\`', '$$')<cr>`

The docs explain how this works, but I'll admit it is not so easy to understand. In any case, the main problem with your version is that the snippet does not know the preceding word.

I think you should instead use the standard setup of writing the trigger word, e.g. `begin` for environments, and then type the trigger mapping. I recommend that you actually _read_ the README file for UltiSnips and the documentation. That way you should learn how this works. I think it should be worth your time, as it will be useful when you work in many other filetypes as well.

**Comment by dbacc** [comment]
Thanks a lot. I think I got it much clearer now.

**Comment by lervag** [comment]
No problem, I'm happy to help :)
