### ISSUE TITLE
vim-latex like placeholders

### ISSUE THREAD

**Issue by sudarshansudarshan** [lervag/vimtex#1038]
http://vim-latex.sourceforge.net/index.php?subject=faq&title=FAQ#faq-placeholders

Is this possible in vimtex? I like vimtex more than vim-latex except for the placeholder functionality. Typing EFI puts 4 lines of code and we can toggle through the placeholders with ctrl+j. I wish we had it in vimtex. Is there an equivalent in vimtex?

**Comment by lervag** [comment]
No, this is not possible with vimtex. But this is by choice: the feature you seek is more general, and is more commonly called snippet expansion. There are several plugins for this, e.g.:

- [UltiSnips](https://github.com/SirVer/ultisnips)
- [neosnippet](https://github.com/Shougo/neosnippet.vim)

There are also others, but I think these two are the most popular ones. I suggest that you look into these, and make a choice. You can also get a bunch of predefined snippets for a lot of languages with [vim-snippets](https://github.com/honza/vim-snippets).

I am aware that this puts a slightly higher burden on users to learn more Vim-stuff, but the gain is definately worth it. If you use Vim for more things than LaTeX, then you will not regret getting a general snippet plugin.

**Comment by sudarshansudarshan** [comment]
Great advice. Thanks. Will look into these.

**Comment by lervag** [comment]
No problem :)
