### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by sudarshansudarshan** [lervag/vimtex#1039]
```vim
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'lervag/vimtex'
call vundle#end()
```

Above is my .vimrc file. Not sure why, but I am not able to compile. `:VimtexCompile` returns `"E492: Not an editor command: VimtexCompile"` error. `\ll` isn't working.

I am working on Mac OS.

**Comment by lervag** [comment]
I have not used Vundle myself, so I won't be able to help you directly. But the problem is that you have not properly installed the plugin.

I suggest that you read up on Vundle or try another plugin manager such as vim-plug.

**Comment by sudarshansudarshan** [comment]
Oh Great. Fixed it in no time. Thanks for the input.

It would be great if we had an exhaustive FAQ in the Wiki section of this repository. It would save many of us from spending time on things that are otherwise straight forward.

**Comment by lervag** [comment]
I don't mind if people write entries in the Wiki, but IMHO, your question is not really related to vimtex. Instead, it is about installing plugins. This is on a more general level, and if we were to include content at this level in a vimtex wiki or similar, it would be way too much. Also, I think the documentation is really quite verbose as it stands, and you should be able to learn a lot by reading it.

**Comment by lacava** [comment]
@sudarshansudarshan can you share what you changed here?

**Comment by sudarshansudarshan** [comment]
I just stopped using vundle and moved to vim-plug

**Comment by CthulhuMythos** [comment]
@lervag 
I also encounter this problem. I am using vim-plug to manage the plugs and the settings in vimrc is as follows.
call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'lervag/vimtex'
call plug#end()
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'

However, I cannot compile the .tex file using '\ll' or ':VimtexCompile'. I have installed latexml and zathura.

**Comment by lervag** [comment]
Please, @CthulhuMythos, open a new issue with a full description of your problem. This particular issue is 1) resolved, and 2) over one year old. This means that your issue is at best related, and so it may make sense to link to it. But it is much better if you open a new issue and describe your issue in detail.
