### ISSUE TITLE
How does vimtex command complete work?

### ISSUE THREAD

**Issue by sudarshansudarshan** [lervag/vimtex#1041]
The help file reads the following: 

Complete commands~
                                                     *vimtex-complete-commands*

Command completion is available after `\` and should provide completion
candidates for relevant LaTeX commands.  The document's preamble is analysed,
and commands will be completed for the loaded packages. A lot of packages are
supported, see the path `VIMTEX/autoload/vimtex/complete` for a relevant file
listing.

But I do not see completion happening after we type the \ command. In fact nothing appears everytime I type \ 

What am I missing here?

**Comment by lervag** [comment]
It is explained in the beginning of the section:

> If |g:vimtex_complete_enabled| is 1 (default), then |vimtex| sets the
'omnifunc' to provide omni completion, see |compl-omni|.  Omni completion is
then accessible with |i_CTRL-X_CTRL-O|.

I've even included the links to more relevant documentation, such as `:h compl-omni` and `i_CTRL-X_CTRL-O`.

So: After typing `\` you can type `<c-x><c-o>` to start the completion.

If you want _auto_completion, then you should look into `:h vimtex-complete-auto` for some relevant information. Note that this requires that you use an additional plugin, as explained in the docs.
