### ISSUE TITLE
Specialized definition of paragraphs

### ISSUE THREAD

**Issue by tschijnmo** [lervag/vimtex#1043]
### Explain the issue

Inside vimtex source, there appears to be some code for specialized definition of paragraphs, for example, [here](https://github.com/lervag/vimtex/blob/7d16f66c04a412762ecd54c37969f88be05a5e69/autoload/vimtex/motion.vim#L63-L98) and [here](https://github.com/lervag/vimtex/blob/7d16f66c04a412762ecd54c37969f88be05a5e69/autoload/vimtex/motion.vim#L161-L173).

However, after some very preliminary searching, these code does not appear to be used by any user-visible commands.  Could any core developers help me if it is a work in progress or for some other purposes?  If redefinition of paragraph according to that specialized list of delimiters for motions `{`, `}`, and paragraph text objects are desired, I would love to attempt to make it work and submit a pull request.  Any help or pointers are appreciated.

**Comment by tschijnmo** [comment]
Sorry, my bad.  Just found that they are intentionally removed in commit decf0f8.

**Comment by lervag** [comment]
I'm curious: considering this was removed two years ago, how did you initially stumble across this? Were you using a two year old version of the plugin?
