### ISSUE TITLE
Open 'broken' Environment/delimiter in insert mode

### ISSUE THREAD

**Issue by dbacc** [lervag/vimtex#1046]
Hi.

I just noticed that while there is a mapping for closing the current environment in insert mode, there's nothing similar for actually opening a 'broken' environment in insert mode.

Suppose you have something like 

```
\begin{gather*}
  eq1\\
  eq2
\end{gather*}
```
and you'd like to split up the equations in two separate parts like this
```
\begin{gather*}
  eq1
\end{gather*}
Some text
\begin{gather*}
  eq2
\end{gather*}
```

Right now, I'm just closing the environment at the end of `eq1` with `]]`. It would be really nice, if could use some mapping like `[[` to avoid having to type `\begin{gather*}`

**Comment by lervag** [comment]
I don't really see this as being a natural or very useful feature, sorry. I think you can make a simple mapping to do what you want, though, something like:

```vim
inoremap <expr> [[ OpenEnv()

function! OpenEnv() abort
  let l:lnum = search('^\s*\\end', 'nW')
  return l:lnum > 0
        \ ? substitute(getline(l:lnum), '\\\zsend', 'begin', '') . "\n"
        \ : ''
endfunction
```

**Comment by lervag** [comment]
You could put the above in your vimrc file, but I'd rather put it in an appropriate `ftplugin`, e.g. `~/.vim/ftplugin/tex.vim` or `~/.vim/after/ftplugin/tex.vim`. This way, the mapping is only defined for LaTeX files. You could also use an autocommand for the mapping.
