### ISSUE TITLE
Glossaries autocomplete fail when file in texmf tree

### ISSUE THREAD

**Issue by skulumani** [lervag/vimtex#1047]
### Glossary autocomplete inconsistent

When a glossary file is located in the working directory, the omni-completion will correctly find glossary entries.

This will fail when the glossary file is located on the texmf tree, but the glossary will be compiled correctly.

A suggestion is to use a similar methodology that allows for citation autocompletions for bib items from the texmf tree.

Thank you for your great plugin!

### Steps to reproduce the issue

1. Move the glossary file to the texmf tree : ` $HOME/texmf/tex/latex/local/glossary_test.text`
2. Compile the document and try to use autocomplete `\gls{CTRL-X CTRL-O}` and notice that there are no completions shown
3. Move glossary file to working directory and repeat step 2 to see the completion

### Attached files

1. `main.tex` - main file to compile
2. `minivimrc` - minimal vimrc - copy of that provided in tests directory
3. `glossary_test.tex` - example glossary file
4. `.latexmkrc` - latexmk file for compiling the glossary

[glossary_minimum.zip](https://github.com/lervag/vimtex/files/1712133/glossary_minimum.zip)

### minimal vimrc
```
" minivimrc
set nocompatible
let &rtp = '~/.vim/plug.vim/vimtex,' . &rtp
let &rtp .= ',~/.vim/plug.vim/vimtex/after'
filetype plugin indent on
syntax enable
```
### main tex document
```
\documentclass[]{article}
\usepackage[automake]{glossaries}
\loadglsentries{glossary_test.tex}
\makeglossaries
\begin{document}

Hello World

Autocompletion will work

Glossary file in current directory

Full path in loadglsentries command

Autocompletion fails when glossary file is in texmf tree

Here is a glossary citation: \gls{linux}

And another one: \gls{matrix}
\glsaddall
\printglossary
\end{document}
```
### glossary test
```
% ---------------------- GLOSSARY TERMS --------------------------------

\newglossaryentry{linux}{
    name=Linux,
    description={is a generic term referring to the family of Unix-like computer operating systems that use the Linux kernel},
    plural=Linuces
}

\newglossaryentry{matrix}{
    name={matrix},
    plural={matrices},
    description={rectangular array of quanttities}
}


\newglossaryentry{polygon}{
    name={polygon},
    plural={polygons},
    description={The area of a plane bounded by straight segments, called edges, which intersect only at their endpoints, called vertices.
    Each vertex belongs to exactly two edges and similarly each edge has exactly two vertices.}
}

\newglossaryentry{MAT}{
    name={medial axis transform},
    description={The medial axis is the set of all point shaving more than one closest point on the objects boundary.
    The medial axis along with the associated radius function of the maximally inscribed discs is called the medial axis transform.}
}

\newglossaryentry{CAD}{
    name={computer aided design},
    description={The use of computer software to create mechanical design drawings}
}

```

### latexmk file
```
add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');
add_cus_dep('acn', 'acr', 0, 'run_makeglossaries');

sub run_makeglossaries {
  if ( $silent ) {
    system "makeglossaries -q '$_[0]'";
  }
  else {
    system "makeglossaries '$_[0]'";
  };
}

push @generated_exts, 'glo', 'gls', 'glg';
push @generated_exts, 'acn', 'acr', 'alg';

$clean_ext .= '%R.ist %R.xdy';

$pdf_mode = 1;
$pdf_latex = 'pdflatex -interaction=nonstopmode -halt-on-error';
```

**Comment by skulumani** [comment]
I found this solution after some more searching, one can use the absolute/relative path and it should work as expected

```
\loadglsentries{\string~/texmf/tex/latex/local/glossaries.tex}
```

**Comment by lervag** [comment]
Thanks, @skulumani. This is a good feature request, but I am not very sure if I want to add it. For bibtex, the reason it works is because I "cheat". That is, we use a hack that was implemented in LaTeX-Box, where we simply import all the bibliography code into a temporary aux file, add a command to include all entries, then compile the document and parse the output for completion candidates.

Doing the same for glossaries seems too much work for me for no apparent gain. Especially considering that I think in general, glossaries should almost always be part of the document itself, and so they should follow the documents. Also, as you say, in the cases where you want to use a "global" glossary file, you can add it with a full path and it will work as expected.

I hope you can relate and understand this decision, even though it might be somewhat dissapointing.

**Comment by skulumani** [comment]
No problem. That's a very reasonable justification and you are correct that it probably makes much more sense to keep my glossary files with the document.

I appreciate the great plugin and all your work.

**Comment by lervag** [comment]
Thanks! :)
