### ISSUE TITLE
<leader> lv not opening pdf document

### ISSUE THREAD

**Issue by adamnewtonwright** [lervag/vimtex#1048]
I am running Mac 10.13, and I have had vimtex working for the past couple of months (so happy with it!). However, recently (possibly coincident with the new mac OS update) <leader>lv no longer opens my pdf document. The compiler still works, and will update the pdf if it is already opening, but will not open the document to begin with.

Currently have this in my .vimrc
`let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'`

`let g:vimtex_view_general_options = '-r @line @pdf @tex'`

**Comment by clason** [comment]
Have you tried just putting `let g:vimtex_view_method = 'skim'` instead of your lines? This works for me on macOS 10.13.4.

**Comment by lervag** [comment]
Yes, please try what @clason suggests.

**Comment by adamnewtonwright** [comment]
I get error
`vimtex: Skim is not installed!
`
when I open my tex document, and <leader>lv still does not work.

**Comment by clason** [comment]
Where did you install Skim? What is the output of running 
```
osascript -e 'tell application "Finder" to POSIX path of (get application file id (id of application "Skim") as alias)'
```
in the terminal?

**Comment by adamnewtonwright** [comment]
I believe it is installed in:
`/Applications/Skim.app/Contents/MacOS/Skim`

But running 
`osascript -e 'tell application "Finder" to POSIX path of (get application file id (id of application "Skim") as alias)'`

gives
`execution error: Finder got an error: Can’t get alias "/Applications/Skim.app". (-1728)`

**Comment by clason** [comment]
OK, then the problem seems to be with your installation, not `vimtex`. Is Skim available as an `Open with` option? Are you by any chance using FileVault?

**Comment by adamnewtonwright** [comment]
Yes, I can open a pdf in the command line with

`open file.pdf -a skim`

**Comment by clason** [comment]
Does it also work with a context click? What does
```
osascript -e 'tell application "Finder" to id of application "Skim"'
```
do?

**Comment by adamnewtonwright** [comment]
`net.sourceforge.skim-app.skim`

**Comment by clason** [comment]
and `osascript -e 'tell application "Finder" to POSIX path of "/Applications/Skim.app/"'`?

**Comment by adamnewtonwright** [comment]
`/Applications/Skim.app/`

**Comment by clason** [comment]
and `osascript -e 'tell application "Finder" to get application file id "net.sourceforge.skim-app.skim"'`?

**Comment by adamnewtonwright** [comment]
`application file Skim.app of folder Applications of startup disk`

**Comment by adamnewtonwright** [comment]
Hm, weird...

Just deleted and reinstalled, and still no luck...

**Comment by lervag** [comment]
Just want to pitch in a thank you to @clason for getting involved and helping out! I'm no good here, as I have no experience with Macs and OSX. I hope you manage to work this out somehow...

Note, I'm leaving this issue closed, because I think this is an issue with your system, not with vimtex.

**Comment by clason** [comment]
Yeah, that was just channeling Roy from IT Crowd... I'm really out of ideas here; this code (which I lifted from the `displayline` script) is working for me on three different Macs running macOS 10.3 (one of which is using FileVault; this being the main offender when googling the `-1728` error.).

Grasping at straws: What happens when you swap `'`  and `"` in the full `osascript` call?

**Comment by lervag** [comment]
Des the `displayline` tool even exist? I.e., what's the output of `ls '/Applications/Skim.app/Contents/SharedSupport/displayline'` in a terminal?

**Comment by clason** [comment]
Good point: Are you using the current version of `vimtex` (which no longer relies on the `displayline` script)?

@lervag I checked the most recent version of Skim; the `osascript` code in `displayline` hasn't changed since I extracted it.

**Comment by adamnewtonwright** [comment]
Switching ' and " gives a syntax error:

`syntax error: Expected expression, property or key form, etc. but found unknown token. (-2741)`

Displayline does exist. Running 

`ls '/Applications/Skim.app/Contents/SharedSupport/displayline'`

gives

`/Applications/Skim.app/Contents/SharedSupport/displayline`

I should have the current version of vimtex. I am using vundle as package manager, and I just ran a Vundle install, and still not working. Are you saying I should not be using `displayline`?

**Comment by lervag** [comment]
@clason Great, good to hear. I'm happy you're still able to help with these things.

One thing: It seems based on the initial description that the `s:skim.view()` does not work, but that `s:skim.compiler_callback()` does work. This is strange, but it might have some clues that @clason could follow up..?

@adamnewtonwright I was just thinking that if that file was missing, it could lead to the `Skim not installed` error, but I realize I was mistaken, since everything depends on the osascripts. Are you able to test one thing by editing the vimtex code? That is, could you edit `VIMTEX/autoload/vimtex/view/skim.vim` lines 9 to 18 and comment these out? Does everything then work as expected?

**Comment by clason** [comment]
If you are using the latest version of `vimtex` (i.e., `HEAD`; I'm using `vim-plug`, not `Vundle`, so not sure how you keep up-to-date) you are not -- `vimtex` is directly calling the `osascript` from  `displayline` to treat callbacks and `<leader>lv` differently (the latter highlights the current line, the former not, which was not possible with `displayline`).

**Comment by adamnewtonwright** [comment]
I don't think that I have a `VIMTEX/autoload/vimtex/view/skim.vim `, and if I do, then I don't know where it is living...

**Comment by clason** [comment]
I don't know where Vundle installs plugins, but it's probably something like `~/.vim/plugins/vimtex/...`

**Comment by adamnewtonwright** [comment]
Ah I see!

**Comment by adamnewtonwright** [comment]
Commenting out lines 9-18 solves the `skim not installed` error! But still no pdf being pulled up

**Comment by clason** [comment]
Not surprising, since a similar osascript is used (by `displayline` as well as `vimtex`) to display the pdf. Honestly, I'm out of ideas at the moment. It's *really* weird that the full line isn't working for you while the constituent steps are.

**Comment by lervag** [comment]
Ok, thanks. Commenting out those lines solves that issue because they implement that test. So, I'm sorry to again say that I can't be of much more help here, as I have no idea about osascript.

If it helps, I could recommend thats you look into Zathura as an alternative viewer. I think it should be possible to make it run and work on OSX. But again, I'm not very qualified at helping out with OSX specific issues... :\

I guess it doesn't hurt asking for one more clue. When you open a LaTeX file, what is the output of `\li`?

**Comment by lervag** [comment]
I'm curious, based on the above testing of the various osascript things:

    osascript -e 'tell application "Finder" to POSIX path of (get application file id (id of application "Skim") as alias)'

To me it seems the problem is this part:

    ... get application file id X as alias

Is it possible to simply test this part directly? Something like this:

    osascript -e 'tell application "Finder" to get application file id "net.sourceforge.skim-app.skim" as alias'

That is, with the `as alias` part added...?

**Comment by lervag** [comment]
(You previously did this without the `as alias`, which seemed to give the correct output. To me it seems the problem is related to the alias stuff...)

**Comment by clason** [comment]
Good point! I missed that. The `alias` bit is actually where the `-1728` error seems relevant. (For reference, my output is `alias Macintosh HD:Applications:Skim.app:`.)

**Comment by adamnewtonwright** [comment]
`\li` gives

![image](https://user-images.githubusercontent.com/26912656/36067418-c68735fe-0e71-11e8-8c3b-a6d0e2e4e5a3.png)

![image](https://user-images.githubusercontent.com/26912656/36067422-ce061e4e-0e71-11e8-9ef1-e5c421eca4eb.png)

And the alias guy gives
`alias /Applications/Skim.app`

**Comment by lervag** [comment]
Ok, thanks. It seems you have a different alias than @clason. I hope that might be helpful for figuring it out...

**Comment by clason** [comment]
Ok, so we finally found a difference. One possibility is that when upgrading to macOS 10.3, your file system did not get converted from HFS+ to APFS. If you run `Disk Utility`, what do you see for the root volume under `Type`?

**Comment by adamnewtonwright** [comment]
It shows APFS.

**Comment by adamnewtonwright** [comment]
It does!

**Comment by clason** [comment]
So it seems that for you, the alias returned is already a POSIX path (with slashes), while it should be an AppleScript path (with colons). I still can't see why the line in my second comment errors out, while the same command with the (same) alias hardcoded doesn't.

What happens if you call the `displayline` script from the  terminal?

**Comment by adamnewtonwright** [comment]
I get:
`Usage: displayline [-r] [-b] [-g] LINE PDFFILE [TEXSOURCEFILE]
Options:
-r, -revert      Revert the file from disk if it was open
-b, -readingbar  Indicate the line using the reading bar
-g, -background  Do not bring Skim to the foreground`

**Comment by lervag** [comment]
I don't think it is relevant for this specifically, but I notice you are running Vim without clientserver. This means that vimtex is not able to refresh the pdf viewer automatically for you. FYI.

Also, I think it could be relevant to make a minimal example. Perhaps by some obscure chance there is something in your vimrc that is doing this..?

I.e., create a minimal vimrc file and a minimal working example with which you can reproduce the problem. This is described in the issue template, [here](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md).

**Comment by clason** [comment]
@adamnewtonwright Sorry, I meant with a pdf file, of course -- something like `displayline 1 your_pdf`.

Also, could you check whether "Check for file changes" and "Reload automatically" are selected in the Skim Preferences (on the Sync tab)? If so, can you uncheck them and see if the PDF still updates automatically after a compilation?

**Comment by clason** [comment]
That's the same problem as with my osascript (hardly surprising, since I copied it from there) and confirms that the problem is definitely with your macOS install and not with vimtex. Since I'm at the limit of my knowledge here, I'd suggest filing an issue with the Skim developers at https://sourceforge.net/p/skim-app/bugs/. (Focus on the error with `displayline`, not with `vimtex`, since they're more likely to take that seriously.) Sorry!

**Comment by lervag** [comment]
In the meantime, I propose that you use vimtex with the default view settings, which as you say works OK. I still think the overall experience should be better with the Skim viewer when everything works, especially if you enable the clientserver (either with the `--servername` option with terminal Vim or with some gui version like mvim).

**Comment by adamnewtonwright** [comment]
Okay, great! Thank you all so much for your help! I really appreciate, and love the community around this! Vimtex is awesome and your up-keep is great.

**Comment by adamnewtonwright** [comment]
Just a note, in case this happens to anyone else, you can just set the default pdf viewer in Mac OS to skim (or whatever you want), and then don't specify a pdf viewer in your vimrc. For me, this opens up skim and everything works well.

Of course, if you don't want this as your default pdf viewer, then your still out of luck since we didn't find our problem.

**Comment by lervag** [comment]
Thanks for the kind words, @adamnewtonwright! I'm sorry that I could not be of more direct help. If you were to open an issue with the Skim devs, I would be happy if you could add a link to it here.

**Comment by jsteen** [comment]
Sorry for reviving this old thread, but I ran into similar issues as @adamnewtonwright.  To be precise, I got the `vimtex: Skim is not installed!` error on MacVim startup.  Commenting out the aforementioned lines in `VIMTEX/autoload/vimtex/view/skim.vim` **did** help in my case, and Skim opened as expected, diverging from @adamnewtonwright's experience.

Not being happy with commenting out the check in `skim.vim`, I found that allowing MacVim and my terminal of choice (for whenever I open MacVim from the command line) to "control Finder" solved the problem.  Specifically, one does this in
`System preferences > Security & Privacy > Privacy > Automation`.

**Comment by gloryVine** [comment]
To chime in, I was running into the same problem.
However, even though I got the above error message, I could still proceed to vim, and just trying to compile with `\ll` worked without errors.
Doing what @jsteen suggested removed the error message.

**Comment by aviloff** [comment]
As @jsteen mentioned, commenting out the lines helped with getting rid of the "not installed" message, but then skim was "not executable". Simply running batchmod with all privilege fields ticked on Skim.app and all enclosing files solved the problem eventually.
