### ISSUE TITLE
select only body text

### ISSUE THREAD

**Issue by joaocortes** [lervag/vimtex#1049]
Hi

I was wondering if is possible to create a command that would select all body text, that is, all the text inside the document environment but outside any math environment. (Sometimes its useful to search and replace patterns only on the main text).

For instance, I want to be sure that every "." on the body text has at least a white space after. I would use the hypothetical command and then use vim search and replace, changing my before.tex (before.txt) to after.tex (after.txt)

Thanks
[after.txt](https://github.com/lervag/vimtex/files/1714939/after.txt)
[before.txt](https://github.com/lervag/vimtex/files/1714940/before.txt)

**Comment by clason** [comment]
I don't think vim supports noncontiguous selection, but you can use regular expressions to restrict the scope of found search terms. For example, the following will only replace `searchterm` inside inline math:
```
s/\$/|;,/\$/s/searchterm/replaceterm/g
```
(Also excluding `equation[*]`, `align[*]` etc. environments is much more complex, though. I suggest you ask at https://vi.stackexchange.com for help if you want to follow this route.)

**Comment by lervag** [comment]
I can see your interest in the feature, but I am not so sure this will be worth the effort. That is, the benefit of such a command is not very great compared to simply using `:%s/.../.../gc`, where `c` let's you confirm every update. But I believe that implementing such a command will be some work. Also, I don't know how much it would be used, and I don't know how good it is to make a very filetype specific search (and replace) command...

**Comment by lervag** [comment]
Oh, and as @clason says, Vim does not support noncontiguous selections.

**Comment by Rmano** [comment]
Hmm... spaces are ignored in math formulas, anyway. I understand it's visually better :-), and that's this is just an example, but just to nitpicking a bit... 

I am with @lervag  that going to `\begin{document}`, select all with `vie`, and then using  a `gc` search on the block (`:'<,'>` is pre-printed in the search space) is the way to go.

**Comment by lervag** [comment]
You can also do something like this:

1. `/\.\S`

2. If the match is not in math mode: `a<space><esc>`

3. Go to next match: `n`

4. If the match is not in math mode: `.` (repeat last edit)

5. Repeat from 3.

I find routines like this, which typically boils down to repeated presses of `n` and `.`, are typically so effective that there is no reason for such a feature that you are asking for.

**Comment by andymass** [comment]
Just to add one advanced option, vimtex already has a handy helper function which returns 1 if the cursor is in math mode and 0 otherwise.  You can use it with `:g` in the standard vim way.  Tab-complete even works in this context, so typing the following would take only a minute:

```vim
:'<,'>g/^/if !vimtex#util#in_mathzone() | s/\.\ze\S/. /g  | endif
```

However, for beginners the ways @lervag mentioned are probably better.

**Comment by clason** [comment]
@andymass Nice! I'll have to remember that. This only works in inline math, right? Is there a version that works in all (inline *and* display) math environments?

**Comment by andymass** [comment]
@clason excellent point, which I completely overlooked.  The way you would do this is with `:s` and `\=` which works match-wise instead of line-wise.  However, it's harder to type.

```vim
:'<,'>s/\.\zs\ze\S/\=vimtex#util#in_mathzone()?'':' '/g
```

Unfortunately, I don't know of a simple way to "run an ex command over the cursor positions of each search match" (besides using a macro of course).

**Comment by joaocortes** [comment]
thanks all. @clason I didnt know i could use an expression on the substitute string. Thats handy.

In this case, the search finds every '\.\S' but the substitution is done in such a way as to leave the matches inside a math environment unaltered.

  Out of curiosity, is it possible to change the search pattern in such a way that only matches the cases inside a math environment? that is, is it in general possible to "modulate" the match state by some conditional?
