### ISSUE TITLE
cgwin and win7 path messed up if using cygwin GIT

### ISSUE THREAD

**Issue by rjiang9** [lervag/vimtex#1052]
I have this issue when I install timtex through vbundle on my Win7 64bit  + vim8 by using +cygwin GIT.

My cygwin home path: /cygdrive/c/Users/littledanniel/

When I install in Vim - PluginInstall, I got 

[2018-02-13 15:04:09] Plugin lervag/vimtex
[2018-02-13 15:04:09] $ git clone --recursive "https://github.com/lervag/vimtex.git" "C:\Users\littledanniel\vimfiles\bundle\vimtex"
[2018-02-13 15:04:09] > Cloning into 'C:\Users\littledanniel\vimfiles\bundle\vimtex'...
[2018-02-13 15:04:09] > fatal: Invalid path '/cygdrive/c/Users/littledanniel/C:\Users\littledanniel\vimfiles\bundle\vimtex': No such file or directory
[2018-02-13 15:04:09] > 

What caused the path messed up?

Thanks,
Little

**Comment by j-jith** [comment]
This is an issue with vundle and not vimtex. I myself do not use vundle, but I don't think cygwin is officially supported by the vundle dev. I did come across a similar issue at VundleVim/Vundle.vim#472. The suggested solution was to call `vundle#begin` in your vimrc with a specific path like `call vundle#begin('~/vimfiles/bundle')`. You could try this approach and see if it helps.

**Comment by rjiang9** [comment]
Thank you very much, J-jith for pointing out the cause of the problem. 
I tried out to change the 2 instances to call vundle#begin('~/vimfiles/bundle', it still does not work. 
c:/Users/littledanniel/vimfiles/bundle not work either. 

So the working around is: uninstall cygwin GIT and install GIT for Windows. 

Thank you for forwarding this issue to vbundle.

**Comment by lervag** [comment]
Thanks for pitching in, @j-jith! Sorry, @rjiang9, for not replying sooner. As this seems sorted out, I'll take the liberty of closing the issue.

**Comment by rjiang9** [comment]
Thank you, Karl!

**Comment by lervag** [comment]
No problem :)
