### ISSUE TITLE
Completion of environments collects ALL THE BRACES

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1053]
I think there's an issue with the recent work on autocompleting environments (cc @andymass) and  `vimtex_complete_close_braces`: If this option is set, accepting a completion adds a closing brace *for every environment completed so far*. (This resets after closing and reopening the file.)

Steps to reproduce:

In a minimal document, type, e.g.,
```
\begin{eq<CTRL-X-O>}
```
and select `equation}`. Then type again
```
\begin{eq<CTRL-X-O>}
```
The list of completions will now be
```
eqnarray}}
equation}}
```
and the extra brace will also appear in the buffer. Lather, rinse, repeat to collect ALL THE BRACES.

Interestingly, if you only type `{e<CTRL-X-O>`, you will see in addition `enumerate}` (single brace), so the accumulating braces are separate for each package (I assume).

### Minimal LaTeX file

```tex
\documentclass{minimal}
\begin{document}

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_complete_close_braces = 1    
```

**Comment by andymass** [comment]
I noticed the same happens for `\usepackage{`.  Do you know if this is a regression I introduced or it was always like that?

Anyway, the following would fix it (for environments only),
https://github.com/andymass/vimtex/commit/880a6bbb209c1eb079fe3d6f675aa3b540911b2e

but maybe @lervag has a different solution in mind.

**Comment by andymass** [comment]
Also, in the case of `\end{` completion, vimtex should somehow trigger a re-indent because the inside of environments are indented by default.  This is done with `CTRL-F` in insert mode, but it seems not enough to append a `}^F` to the completion string.  Possibly the only way is with `CompleteDone`/`feedkeys`.  Any other ideas?  I can write a PR eventually if you would like.

**Comment by clason** [comment]
Good point, I never noticed it for `\usepackage`. I can confirm that this behavior predates your pull request, so you're off the hook :)
I'll see if I can find a commit where this still works.

**Comment by lervag** [comment]
Sorry, the bug was my fault. This should work properly now, I think.

**Comment by clason** [comment]
Works like a charm, thank you! No more hoarding of braces :)
