### ISSUE TITLE
Error when opening a tex file

### ISSUE THREAD

**Issue by emfiedler** [lervag/vimtex#1056]
When opening a tex file there is an error report for a file found in vimtex\after\syntax\tex.vim

1. Error upon opening
2. Expected run as usual
3. Get the following message: 
E475: Invalid arguement: texMathDelim '\\[bB]igg\=\\lVert' contained conceal cchar=(right here there is an â and two boxes)

I'm no vim expert so just want to know if skipping this will have no effect on the primary functions of vimtex and the use of LaTeX.

**Comment by lervag** [comment]
Can you please provide a full minimal example as suggested in the issue template?

Which version of Vim do you use? What's the output of `\li` after you open a LaTeX file?

**Comment by emfiedler** [comment]
I use Vim 8.0 on Windows 10, compiling pdf files seem unaffected.

Here is the error message I get when opening a tex file:
`Error deteced while processing C:\Users\me\vimfiles\plugged\vimtex\after\syntax\tex.vim:
line 305:
E475: Invalid arguement: texMathDelim '\[bB]igg=\lVert' contained conceal cchar=`

When I do `\li` into a document

```System info
  OS: Microsoft Windows 10 Home (10.0.16299 N/A Build 16299)
  Vim version: VIM 8.0 (1-586)
  Has clientserver: true
  Servername: GVIM

vimtex project: test
  base: test.tex
  root: C:\LaTeX\test
  tex: C:\LaTeX\test\test.tex
  out: C:\LaTeX\test/test.pdf
  log: C:\LaTeX\test/test.log
  aux: C:\LaTeX\test/test.aux
  fls: C:\LaTeX\test/test.fls
  document class: article
  compiler: latexmk
    backend: jobs
    output: C:\Users\me\AppData\Local\Temp\VIAB189.tmp
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
    job: process 10064 run
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF -reuse-instance'" -e "$success_cmd = '""""""C:\Program Files\Vim\vim80\gvim.exe"""""" --servername "GVIM" --remote-expr "vimtex#compiler#callback(1)"'" -e "$failure_cmd = '""""""C:\Program Files\Vim\vim80\gvim.exe"""""" --servername "GVIM" --remote-expr "vimtex#compiler#callback(0)"'" "test.tex"
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1`

**Comment by lervag** [comment]
And a minimal example? That is, a minimal vimrc file and a minimal tex file so that "vim -u vimrc mwe.tex" reproduces the issue...

**Comment by AmericanEnglish** [comment]
I'm actually have this same issue. Here is a minimum ".tex" file that causes this to happen. 
```latex
\documentclass{article}
\usepackage[margin=1in]{geometry}
\usepackage{amsfonts}
\usepackage{amsmath}
\usepackage{listings}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}
\usepackage{verbatim}
\title{A Generic Title}
\author{First Last}
\date{\today}



\begin{document}
\maketitle

\end{document}
```
I'm currently using GVim on windows so I can't copy and paste the image so I'm attach the screenshot of the error.
![vimerror](https://user-images.githubusercontent.com/9370077/37230407-6925e046-23b5-11e8-8e6a-87fe3da97914.png)

**Comment by lervag** [comment]
There's been a lot of windows users lately with similar type of errors. I'm guessing that it might be a font or encoding problem, but I don't understand it.

Could you check if it helps to update Vim to a more recent version?

If not, could you please open a new issue for this, and specify a full minimal example, including a minimal vimrc file?

**Comment by AmericanEnglish** [comment]
I will open a new issue after looking into the things you have mentioned. I should also state that this error does not happen if I open a new file. However if I save and exit the new file, the file I just created still causes the error to appear again.

I've checked vim.org and it seems that the last change published for the windows installer on there is 2013 so I most definitely have the newest version that's been published for my OS unless I compile it from source. I'll open a new issues with a minimal example and minimal vimrc file later today.

**Comment by lervag** [comment]
From [this page](https://www.vim.org/download.php) you should be able to download version 8.586 from one of the first links. I don't understand what you mean about 2013, I think this version should not be more than a couple of months old.

In any case, thanks!

**Comment by AmericanEnglish** [comment]
My apologies. I misread something with regards to the license. The _license_ agreement hasn't been changed since then. Installing the newest version did not fix it. Will open an issue later.

**Comment by lervag** [comment]
No problem!

**Comment by andymass** [comment]
@lervag  I think you can reproduce this by doing `set encoding=latin1`.. then opening a tex file.  If this is the same problem others are having, the fix (WFM at least) is to put

```vim
scriptencoding utf-8
``` 
in `after/syntax/tex.vim`.

**Comment by lervag** [comment]
I think you are on to something, @andymass. I'm pushing this as an update now, then @AmericanEnglish can report if it fixes the issue. [Pushing in 5 minutes.]

**Comment by AmericanEnglish** [comment]
The issue is now fixed. I no longer receive the error.

**Comment by lervag** [comment]
Great :)
