### ISSUE TITLE
reverse search and focus

### ISSUE THREAD

**Issue by joaocortes** [lervag/vimtex#1060]
Hi
I am using vimx and okular on a Fedora 26 installation, with Gnome as the desktop manager.

The reverse and backward searches are working.

For the reverse search, I configured okular with the command

    vimx --remote +%l %f

I configured the behaviour of vimtex like this:

```vim
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique --noraise file:@pdf\#src:@line@tex'
```

My problem Is that the reverse search does not raise the vim window. That is, when i Shift+Click on the pdf, the cursor is repositioned on the vim window, but the focus remains on okular.

I am assuming this is related to how Gnome handles apps trying to change the focus of windows, so it is not directly related to vimtex. Still, I thought someone might have solved this and could give me some hint.

Thanks.

**Comment by joaocortes** [comment]
Thanks. Sorry for the formatting. I will keep it in mind. Should 

- vimx is a flavour of vim. I am just using it because there is no fedora package with vim compiled with the server option enabled. I assumed it was irrelevant, but then, I should just have just typed vim to minimize confusion.

- I tried your solution and it works. Thanks.
There is a bit of a lag between the click and the activation of the window, but its usable

**Comment by lervag** [comment]
> Do you think its twekable through the xdootool windowactivate call ?

I don't think so, no. But if you were to find otherwise I would be happy to adjust the code. I don't see any clear points in the code that might give the lag. I use Zathura with the same function for reverse search, and I also have the same (short) lag. :\
