### ISSUE TITLE
Latex-Suite like jumps

### ISSUE THREAD

**Issue by nakamin** [lervag/vimtex#1061]
Does vimtex have something similar to the placeholders described [here](http://vim-latex.sourceforge.net/documentation/latex-suite/latex-macros.html)? If not, is this something that can be added to vimtex?

**Comment by lervag** [comment]
No. This feature is often called snippets, and I strongly recommend that you use a general purpose snippet plugin for this. Please read `:h vimtex-non-features` and `:h vimtex-UltiSnips`.

Let me know if you need more info on this, or if the info in the help files suffices.
