### ISSUE TITLE
Win7 - Latexmk: Stopping because executing following code from command line     $success_cmd = '"C:Program

### ISSUE THREAD

**Issue by rjiang9** [lervag/vimtex#1062]
When I install vimtex (through vbundle) on a Win7 machine today, I got this error (output of \lo, nothing happens for \ll):

```
Latexmk: Stopping because executing following code from command line
    $success_cmd = '"C:Program
gave an error:
    Can't find string terminator "'" anywhere before EOF at (eval 11) line 1.
```

1. A minimal `vimrc` file, for instance:

```vim
set nocompatible

let &rtp = $HOME. '\\vimfiles\\bundle\\vimtex,' . &rtp
let &rtp .= ','. $HOME . '\\vimfiles\\bundle\\vimtex\after'

filetype plugin indent on
syntax enable

let g:tex_flavor='latex'
let g:vimtex_view_general_viewer = $HOME . '\\VIM\\pdfviewer\\SumatraPDF.exe'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
let g:vimtex_compiler_progname = v:progname
```

2. A minimal `.tex` file:
    
```tex
\documentclass{minimal}
\begin{document}
hello you!
\end{document}
```

3. Since this is Win7 machine, when I do `vim --servername VIM -u vimrc mwe.tex`, I got error:

```
  VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb  9 2018 13:11:23)
Unknown option argument: "--servername"
More info with: "vim -h"
```

4. A `.latexmkrc` file 

```perl
$pdflatex = 'xelatex --shell-escape %O %S';
```

![image 092](https://user-images.githubusercontent.com/7293118/36578461-9b195df4-181a-11e8-98b2-1d73cdbc577f.jpg)

**Comment by rjiang9** [comment]
Any suggestion would be highly appreciated. 
Thanks.

**Comment by lervag** [comment]
I think this is related to the recent update by #1059, see also #1054. Can you try to revert vimtex to a commit before the one provided by #1059?

**Comment by lervag** [comment]
On windows, instead of `vim --servername ...`, you can do `gvim -u vimrc mwe.tex`.

**Comment by rjiang9** [comment]
@lervag I checkout a old copy of process.vim (the one you committed 2 month ago for removing modeline) and replaced the current one. and it seems I got the same results:
```

Latexmk: Stopping because executing following code from command line
    $success_cmd = '"C:Program
gave an error:
    Can't find string terminator "'" anywhere before EOF at (eval 11) line 1.
```
If I add in 
`
let g:vimtex_compiler_progname = 'latexmk'`

I got 

Latexmk: applying rule 'pdflatex'...
This is XeTeX, Version 3.14159265-2.6-0.99999 (MiKTeX 2.9.6600 64-bit)

entering extended mode

(mwe.tex

LaTeX2e <2017-04-15>

Babel <3.18> and hyphenation patterns for 75 language(s) loaded.

("C:\Users\bobsmith\AppData\Local\Programs\MiKTeX 2.9\tex\latex\base\minimal.cls"

Document Class: minimal 2001/05/25 Standard LaTeX minimal class

) (mwe.aux) [1] (mwe.aux) )

Output written on aa.pdf (1 pageLatexmk: Log file says output to 'aa.pdf'
Rule 'pdflatex': File change=== TeX engine is 'XeTeX'
Latexmk: applying rule 'pdflatex'...
This is XeTeX, Version 3.14159265-2.6-0.99999 (MiKTeX 2.9.6600 64-bit)

entering extended mode

(mwe.tex

LaTeX2e <2017-04-15>

Babel <3.18> and hyphenation patterns for 75 language(s) loaded.

("C:\Users\bobsLatexmk: Log file says output to 'mwe.pdf'
Latexmk: I have not found a previewer that is already running. 
   So I will start it for 'mwe.pdf'
------------
------------
Running 'start C:\Users\bobsmith\VIM\pdfviewer\SumatraPDF.exe --unique  "aa.pdf"'
------------
------------
Running '"latexmk" --servername GVIM10 --remote-expr vimtex#compiler#callback(1)'
------------
sh: C:UsersbobsmithVIMpdfviewerSumatraPDF.exe: command not found
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `"latexmk" --servername GVIM10 --remote-expr vimtex#compiler#callback(1)'

**Comment by lervag** [comment]
Ok, as I wrote in #1063, setting `g:vimtex_compiler_progname` like that simply does not make sense. Please don't do that.

I think this problem may be related to an earlier issue. I'll try to find it and make a reference. In that issue I never figured out what was the problem... :(

**Comment by lervag** [comment]
Old and relevant threads: #736, #789 and #882. Also #966, but it mostly refers back to these older threads. However, #966 seems very similar to this problem in the original description.

**Comment by lervag** [comment]
By the way, it is also relevant to read `:h vimtex-faq-windows`.

**Comment by lervag** [comment]
```vim
let g:vimtex_compiler_progname = v:progname
```

might work if you ensure that the gvim executable is in your PATH environment variable. I don't know how to do that, though, but I guess you can find out by googling. :)

**Comment by rjiang9** [comment]
thank you @lervag . I put this line in vimrc,

`let g:vimtex_compiler_progname = v:progname`

I got```

Latexmk: All targets (mwe.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
have not found a previewer that is already running. 
   So I will start it for 'mwe.pdf'
------------
------------
Running 'start C:\Users\rjiang\VIM\pdfviewer\SumatraPDF.exe --unique  "mwe.pdf"'
------------
------------
Running '"gvim.exe" --servername GVIM2 --remote-expr vimtex#compiler#callback(1)'
------------
sh: C:UsersrjiangVIMpdfviewerSumatraPDF.exe: command not found
sh: -c: line 0: syntax error near unexpected token `('
sh: -c: line 0: `"gvim.exe" --servername GVIM2 --remote-expr vimtex#compiler#callback(1)'

```

my gvim is in my win7 PATH. I can execute it from both cygwin and cmp windows.

**Comment by lervag** [comment]
Ok, just to be sure, you are now doing `gvim -u vimrc mwe.tex` with the following vimrc file:

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
```

I don't believe you are doing this, because on windows, you typically don't use `~/.vim`, but rather something like `~/vimfiles` or something like that. And if I'm right, this means that your initial post/issue description is misleading.

**Comment by rjiang9** [comment]
minimal vimrc:

```
set nocompatible
let &rtp = $HOME. '\vimfiles\bundle\vimtex,' . &rtp
let &rtp .= ','. $HOME . '\vimfiles\bundle\vimtex\after'
filetype plugin indent on
syntax enable
" Plus possibly vimtex options
let g:tex_flavor='xelatex'
let g:vimtex_view_general_viewer = $HOME . '\\VIM\\pdfviewer\\SumatraPDF.exe'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
let g:vimtex_latemk_progname='gvim'

let g:vimtex_compiler_progname = v:progname

```

**Comment by rjiang9** [comment]
I got:
![image 093](https://user-images.githubusercontent.com/7293118/36617948-912db650-18a6-11e8-857d-3ae2af534206.jpg)

**Comment by rjiang9** [comment]
sorry @lervag for the origianl post info - the browser went away when I wrote the post. I have just updated. Thanks.

**Comment by lervag** [comment]
Ok, a couple of more comments:

- I've updated your minimal vimrc files. First, `xelatex` is not a valid choice for `g:tex_flavor`, please see `:h g:tex_flavor`. I've changed it to `latex`, which I think is more suitable.
- Second, the `g:vimtex_latexk_progname` is not a valid vimtex option, so I removed it.
- Your screenshot indicates that things are still not quite clear. The vimrc file you are editing is named `_vimrc`, and when you do `gvim -u vimrc mwe.tex` you get an error that indicates that the file `vimrc` does not exist. You should either rename the vimrc file or do `gvim -u _vimrc mwe.tex`.
- **Note**: When I am asking you to use a minimal vimrc file, I am not talking about changing your main vimrc file and vim configuration, I am asking you to make a temporary, minimal configuration file that is used only to reproduce the present issue. On windows, `_vimrc` is the typical name of the *main* configuration file, which is why I got the feeling you might have this part confused.

I would also recommend that you read `:h vimtex_viewer_sumatrapdf`. In particular, I think it might be better to use:

```vim
let g:vimtex_view_general_viewer = 'SumatraPDF'
```

Although you should make sure that it is in your `PATH` environment variable.

**Comment by rjiang9** [comment]
sorry for not clear about what minimal vimrc was. I put it in the same folder as mwe.tex and gave me this message:

![image 094](https://user-images.githubusercontent.com/7293118/36620684-7c900fd0-18b1-11e8-9394-7e81c94d6601.jpg)

my pdf viewer is in Win7 Path now and reopened the cmd window.

**Comment by rjiang9** [comment]
Updates: I did a plugin reinstall through vbundle and I could see @lervag did some updates (for tests?) and now it looks working now:

Again: minimal vimrc:
```
set nocompatible
let &rtp = $HOME. '\\vimfiles\\bundle\\vimtex,' . &rtp
let &rtp .= ','. $HOME . '\\vimfiles\\bundle\\vimtex\after'
filetype plugin indent on
syntax enable

let g:tex_flavor='latex'
let g:vimtex_view_general_viewer = 'SumatraPDF.exe'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
let g:vimtex_compiler_progname = v:progname
```
`I also put my pdfviewer in c:\windows`


I could say any words to express my thankfulness 
for your help, @lervag 

By the way, CJK characters support without any issue now.

**Comment by lervag** [comment]
I am happy it works, @rjiang9! I do not know exactly what fixed it for you, but the important thing is that it works.

One more comment: When you say vbundle, I think you mean vundle. In any case, I recommend vim-plug, which I think "just works" more often than other plugin managers.

**Comment by rjiang9** [comment]
@lervag yes, i mean 'vundle'. I will try out vim-plug. 

Issue is wierd and fix is misterious. But all credits to you. Thanks again. Have a good weekend!
