### ISSUE TITLE
ToC: consider options bibintoc and subbibintoc of biblatex for vimtex-toc

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1064]
Consider following LaTeX file:

```tex
\documentclass{book}
\usepackage{biblatex}

\begin{document}

\chapter {Introduction}
\ldots

\printbibheading[heading=bibintoc]
\printbibliography[heading=subbibliography,type=article,title={Articles}]
\printbibliography[heading=subbibliography,type=book,title={Monographs \& Textbooks}]
\end{document}
```

The table of contents generated by vimtex looks like:
```
          Preamble                                                                                                                                    0
1         Introduction                                                                                                                                0
          Bibliography                                                                                                                                0
          Bibliography                                                                                                                                0
          Bibliography                                                                                                                                0
```

In this circumstance, I would prefer to get only 
```
          Preamble                                                                                                                                    0
1         Introduction                                                                                                                                0
          Bibliography                                                                                                                                0
```

Instead of adding always the entry `Bibliography`, check if the commands`\printbibheading` and `\printbibliography` have the option `heading` and if the value is `bibintoc`, `subbibintoc`,  `bibnumbered`, or `subbibnumbered`. If `heading` does not exist or the value is `bibliography`, `subbibliography`, or `none`, do not add it. If people want to have a different behavior between latex-toc and vimtex-toc, we would need an option.

Furthermore, if the option `title` is used, take its value for the vimtex-toc as well. Maybe you could use a generic converter function which converts `\&` to `&`, understands `\texorpdfstring` command and other.

Note following descriptions in the official documentation of biblatex

> 3.7.7 Bibliography Headings and Environments
>
> ...
>
> The following headings, which are intended for use with `\printbibliography`
> and `\printbibheading,` are predefined:
>
> `bibliography`
> This is is the default heading used by `\printbibliography` if the heading op-
> tion is not given. Its default definition depends on the document class. If the
> class provides a `\chapter` command, the heading is similar to the bibliography
> heading of the standard LaTeX book class, i. e., it uses `\chapter*` to create
> an unnumbered chapter heading which is not included in the table of
> contents. If there is no `\chapter` command, it is similar to the bibliography
> heading of the standard LaTeX article class, i. e., it uses `\section*` to
> create an unnumbered section heading which is not included in the table of
> contents.  e string used in the heading also depends on the document class.
> With book-like classes the localisation string bibliography is used, with
> other classes it is references (see § 4.9.2). See also §§ 3.14.1 and 3.14.2
> for class-specific hints.
> 
>  `subbibliography`
> Similar to bibliography but one sectioning level lower.  This heading
> definition uses `\section*` instead of `\chapter*` with a book-like class and
> `\subsection*` instead of `\section*` otherwise.
> 
> `bibintoc`
> Similar to bibliography above but adds an entry to the table of contents.
> 
> `subbibintoc`
> Similar to subbibliography above but adds an entry to the table of contents.
>
> `bibnumbered`
> Similar to bibliography above but uses `\chapter` or `\section` to create a
> numbered heading which is also added to the table of contents.
> 
> `subbibnumbered`
> Similar to subbibliography above but uses `\section` or `\subsection` to create a
> numbered heading which is also added to the table of contents.
> 
> `none`
>  A blank heading definition. Use this to suppress the heading.

**Comment by lervag** [comment]
Ok, so to implement this I need to parse the `\printbibliography` and `\printbibheading` commands for two keys: `heading` and `title`.

It is unclear exactly which combinations of the commands and the heading options that should actually give a TOC entry here.

**Comment by kiryph** [comment]
Combinations which should give a TOC entry:
```tex
\print<bibliography|bibheading>[heading=bibintoc]
\print<bibliography|bibheading>[heading=subbibintoc]
\print<bibliography|bibheading>[heading=bibnumbered]
\print<bibliography|bibheading>[heading=subbibnumbered]

\print<bibliography|bibheading>[heading=bibintoc,title={My Bibliography}]
\print<bibliography|bibheading>[heading=subbibintoc,title={My Subbibliography}]
\print<bibliography|bibheading>[heading=bibnumbered,title={My Numbered Bibliography}]
\print<bibliography|bibheading>[heading=subbibnumbered,title={My Numbered Subbibliography}]
```
where `<a|b>` stands for `a` or `b`.

Combination which should **NOT** give a TOC entry:
```tex
\print<bibliography|bibheading>
\print<bibliography|bibheading>[heading=bibliography]
\print<bibliography|bibheading>[heading=subbibliography]
\print<bibliography|bibheading>[heading=none]

\print<bibliography|bibheading>[title={My Bibliography}]
\print<bibliography|bibheading>[heading=bibliography,title={My Bibliography}]
\print<bibliography|bibheading>[heading=subbibliography,title={My Subbibliography}]
\print<bibliography|bibheading>[heading=none,title={This will be ignored by biblatex}]
```
---

There is another minor aspect:
The localisation string depends on the documentclass:
```
book, scrbook for bibliography: Bibliography
book, scrbook for subbibliography: References
```
```
other for bibliography: References
other for subbibliography: References
```
I am not sure if this is really necessary to adapt. I don't mind to have here a difference between latex-toc and vimtex-toc.

See again biblatex documentation:
> With book-like classes the localisation string bibliography is used, with other
> classes it is references (see § 4.9.2). See also §§ 3.14.1 and 3.14.2 for
> class-specific hints.

---
And now an example file
```tex
\documentclass{book}
% \documentclass{article} localisation string for bibheading becomes 'References'

\begin{filecontents}{\jobname.bib}
@Book{Saussure:1995,
    Author    = {Ferdinand de Saussure},
    Origyear  = {1916},
    Publisher = {Payot},
    Title     = {Cours de Linguistique G{\'e}n{\'e}rale},
    Year      = {1995},
}
@Article{Thomson:1856,
  Author      = {Thomson, W.},
  Title       = {{Elements of a Mathematical Theory of Elasticity}},
  Journal     = {Philosophical Transactions of the Royal Society of London},
  Pages       = {481--498},
  Volume      = {146},
  Year        = {1856},
}
\end{filecontents}

\usepackage{biblatex}

\addbibresource{\jobname.bib}

\begin{document}
\tableofcontents
\chapter {Introduction}
\cite{Saussure:1995}, \cite{Thomson:1856}, \ldots

\printbibliography[heading=bibintoc]
\printbibliography[heading=subbibintoc]
\printbibliography[heading=bibnumbered]
\printbibliography[heading=subbibnumbered]
\printbibliography[heading=bibintoc,title={My Bibliography}]
\printbibliography[heading=subbibintoc,title={My Subbibliography}]
\printbibliography[heading=bibnumbered,title={My Numbered Bibliography}]
\printbibliography[heading=subbibnumbered,title={My Numbered Subbibliography}]
\end{document}
```
latex-toc looks as follows:
![screen shot 2018-03-02 at 11 27 18](https://user-images.githubusercontent.com/371756/36894765-bf4dba4c-1e0c-11e8-939e-ef940a73fa31.png)


The vimtex-toc should look similar
```
          Preamble
1         Introduction
          Bibliography
          References
2         Bibliography
2.1       References
          My Bibliography
          My Subbibliography
3         My Numbered Bibliography
3.1       My Numbered Subbibliography
```
This contains actually another feature request: adding a number for bibliographies when using `bibnumbered` and `subbibnumbered`.

I hope I have now clarified my feature request.

**Comment by lervag** [comment]
Thanks, this is definately clear. I am not sure how straightforward it is, but I will look into it when I get the time.

**Comment by lervag** [comment]
I'm thinking about this now. Would it seem plausible to make this kind of parsing dependent on whether or not the `biblatex` package is found in the package list? I.e., I could make two matchers for the ToC entries, one for `biblatex` and "fallback" (which can be similar to the one that is used now).

The `biblatex` matcher would be more advanced and adhere to options as per your request. In the first version, I am going to ignore the localisation, but I'll adhere to the example you've provided as best as possible.

One question regarding the variants that should not give an entry: I often simply use `\printbibliography`, and although it does not as you say give an entry in the LaTeX ToC, I think it is still convenient to show it in the Vimtex ToC. Could we use a heuristic like "if there is only one instance of `\printbibliography`, then keep it in the vimtex toc even if it does not have the _right_ options"?

**Comment by lervag** [comment]
This issue has not been updated since last april. I think it seems still relevant as a feature request. Do you agree, @kiryph?

**Comment by kiryph** [comment]
Yes, I agree. IMHO it is still a relevant feature request.

IMHO more authors using vimtex should be interested in this.
I have many books on my shelf which actually use a more granular bibliography, in particular chapter bibliographies.

**Comment by lervag** [comment]
Ok, I finally got around to it. I think the latest commits should mostly solve this. One question, though: Is it correct to ignore the optionless versions? I've included them now. The reason: I think many people probably do not use the options at all, and they might be surprised if the toc entry dissappears. The question is then how to improve/fix this.

**Comment by kiryph** [comment]
Hi Lervag,

thanks for your time to work on this.

I agree when people write an article they usually do not have a latex-toc and would not add an option like `heading=bibintoc` to `\printbibliography`. But I suspect they still would appreciate to see it in the vimtex toc.

> The question is then how to improve/fix this.

I am not entirely sure how to do this.

Maybe vimtex could detect that there is a `\tableofcontents` entry for vimtex toc. This means the user has a latex-toc and is aware of what is added or not. In this case I would go with my suggestion (adjusted behavior), otherwise add them without considering options (old behavior).

I guess this must be documented, maybe with an option.

What do you think?

**Comment by lervag** [comment]
I think you have an interesting proposal. I have a counter proposal:

1. When collecting TOC entries, include all versions of `\printbibliography` including the ones without options.

2. Before applying the entries, filter the candidates based on this rule: If any entry include a `heading` option, then filter out all entries that does not have this option. Else keep all entries.

I am thinking this might work OK in all/most cases and that one might not need any options. What do you think? (I'm thinking in the spirit of "Don't let perfect be the enemy of good".)

**Comment by kiryph** [comment]
I think this strategy is good but the rule should be:

> If any entry include a heading option, then filter out all entries that does not have the option `heading` or one of the values `none`,`bibliography`, `subbibliography`. Else keep all entries.

Otherwise my original example
```
\printbibheading[heading=bibintoc]
\printbibliography[heading=subbibliography,type=article,title={Articles}]
\printbibliography[heading=subbibliography,type=book,title={Monographs \& Textbooks}]
```
would give you again three entries what I do not want.

**Comment by lervag** [comment]
Ok, I think this latest commit should finalize the work. Let me know what you think.

**Comment by kiryph** [comment]
Thanks.

I think it works as planned: authors with only \printbibliography` (no option) see it in the vimtex-toc. Authors who modify what comes into the latex-toc with the option heading get an vimtex-toc accordingly.

**Comment by lervag** [comment]
Great, happy to hear that you also did this to work as expected. And thanks
for raising the issue!
