### ISSUE TITLE
Add support for syntax highlighting of nested python code (package pythontex)

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1066]
The package [`pythontex`](https://ctan.org/pkg/pythontex) allows to insert python code inside of LaTeX documents.

Could we add nested syntax highlighting support for python code?

List of commands:
- `\py[⟨session⟩]⟨opening delim⟩⟨code⟩⟨closing delim⟩`
- `\pyc[⟨session⟩]⟨opening delim⟩⟨code⟩⟨closing delim⟩`
- `\pys[⟨session⟩]⟨opening delim⟩⟨code⟩⟨closing delim⟩`
- `\pyv[⟨session⟩]⟨opening delim⟩⟨code⟩⟨closing delim⟩`
- `\pyb[⟨session⟩]⟨opening delim⟩⟨code⟩⟨closing delim⟩`
- `\pycon[⟨session⟩]⟨opening delim⟩⟨code⟩⟨closing delim⟩`

List of environments:
- `pycode [⟨session⟩][⟨fancyvrb settings⟩]`
- `pysub [⟨session⟩][⟨fancyvrb settings⟩]`
- `pyverbatim [⟨session⟩][⟨fancyvrb settings⟩]`
- `pyblock [⟨session⟩][⟨fancyvrb settings⟩]`
- `pyconsole [⟨session⟩][⟨fancyvrb settings⟩]`

There exist by default two variations of the commands and environments where certain python packages are already imported:
- `pylab` (matplotlib)
- `sympy` (SymPy)

(replace in the list above `py` with `pylab` or `sympy`)

The package supports actually more languages:
- ruby
- julia
- octave
- bash
- rust

**Comment by lervag** [comment]
Sounds like a reasonable feature. It would be nice with a more complete LaTeX example file. Only one example is necessary for commands/environments that have the same syntax. To include support for the other languages, please make it clear how to detect which language should be matched.

**Comment by lervag** [comment]
After looking more into it, I would love to add more support for this. It would still be very nice with a good LaTeX sample that can be used to test the syntax, but I can see myself use this package quite a lot in the future. Thanks for making me aware of it!

**Comment by kiryph** [comment]
The package itself provides a LaTeX sample file:

http://mirrors.ctan.org/macros/latex/contrib/pythontex/pythontex_gallery.tex

Maybe this can already be helpful to test. I guess you meant a more condensed file just for testing without any explanation and an almost complete list of possible constructs.
This will be a larger file. Consider for example following command constructs which pythontex accepts:

```tex
\py{1+1}
\py#1+1
\py@1+1
```

**Comment by lervag** [comment]
Yes, I meant a more condensed file for testing. This would also define the (possibly restricted sub)set of supported commands.

I think it would help a great deal to deal with a single example first, and then expand. This way I would learn how things should work before attacking the full set of commands. In this case, it would be helpful if you could suggest a minimal example of one command or one environment. Perhaps this would work as a start?

```tex
\pyb{print('Python says hi!')}

\begin{pyblock}
mytext = '$1 + 1 = {0}$'.format(1 + 1)
\end{pyblock}
```

**Comment by bmccary** [comment]
I'm also interested. I'm not sure I have much to add in the way of writing vim plugins, but I'd be happy to contribute some MWEs of pythontex.

**Comment by krishnakumarg1984** [comment]
Is this feature fully working now?

**Comment by lervag** [comment]
Only partly. I've added support for some of the commands and environments, and I've asked for a more complete example in order to have good tests when adding full support. That's where this is at currently.

**Comment by rubdos** [comment]
There's an interesting possible extension of this request: the `minted` package.

```tex
\begin{minted}{python}
def f():
    pass
\end{minted}
\begin{minted}{rust}
let x = 0u8;
\end{minted}
```

Minted supports many more languages through `pygmentize`, but I'm not sure whether it'd be possible to read the language from the TeX source and thusly highlight it?

**Comment by lervag** [comment]
@rubdos Minted is already supported. :)

**Comment by rubdos** [comment]
> @rubdos Minted is already supported. :)

Sorry for the noise, then. Upon restarting vim,
I indeed have syntax highlighting for my embedded Rust code.
Strange that it wasn't there before!

**Comment by lervag** [comment]
> Sorry for the noise, then. Upon restarting vim,
> I indeed have syntax highlighting for my embedded Rust code.
> Strange that it wasn't there before!

It might not be so strange: the syntax highlighting is loaded on startup, and the nested syntaxes are parsed during initialization. Thus, if you add a new language, it will not be properly highlighted until you restart.

**Comment by yzlnew** [comment]
Is tree-sitter going to make this a reality?

**Comment by lervag** [comment]
Nah, I don't think I will work with tree-sitter. I'm sorry for letting this issue stagnate. There's a little bit too much to do, so I've prioritized bugs and "simple" things. I still want to work on this one, though, which is why it is still open. I you want to help then my previous comment still applies:

> ... and I've asked for a more complete example in order to have good tests when adding full support.

**Comment by lervag** [comment]
I'm closing this issue now. If anyone wants better support for pythontex syntax highlighting, feel free to open a new issue with a clear description.
