### ISSUE TITLE
No compiler output using neovim and plugged

### ISSUE THREAD

**Issue by tamul** [lervag/vimtex#1067]
When using nvim and plugged for loading plugins, there is no output from `VimtexCompileOutput`. Testing in vim has the expected behaviour. It seems the output is not being redirected to the temporary file.

Minimal `vimrc` file:

```vim
set nocompatible
let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

Minimal `.tex` file:

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Description

Start neovim with `nvim -u minimal.vim minimal.tex`. Start compilation and call the command `VimtexCompileOutput` or use <leader>lo shortcut. Also tried with an empty .latexmkrc

Expected Behaviour: The opened split shows the output of the latexmk command.

Actual Behaviour: Empty buffer.

**Comment by lervag** [comment]
Thanks! I've noticed this myself, but I never found the time to look into it. Now I will, though. I took the liberty of simplifying your description somewhat and to remove the vim-plug dependency of the minimal vimrc file.

**Comment by tamul** [comment]
Thanks for looking into/closing it! And hmm, that's odd, I found I only had the issue when using vim-plug. If I used a `vimrc` like listed it actually worked, at least when I tested.

**Comment by lervag** [comment]
Strange. The problem was replicated for me with the minimal vimrc file without vim-plug. The fix should not be dependent on vim-plug either. Anyway, doesn't matter, as it is fixed :)

**Comment by dajuno** [comment]
The problem seems to have reappeared, running the MWE above gives me the same behaviour. :VimtexCompile compiles the file, but :VimtexCompileOutput is empty.

neovim v0.2.2, vimtex master

**Comment by lervag** [comment]
Thanks. I think it should be fixed now.

**Comment by dajuno** [comment]
Yes, it works now! Thanks to too for your good work.

**Comment by lervag** [comment]
Great, and no problem :)
