### ISSUE TITLE
No compiler output using arara, gvim on win32

### ISSUE THREAD

**Issue by lucasreddinger** [lervag/vimtex#1068]
Hi,

I'm trying to get vimtex to compile using arara on Windows 7 (sorry!) running gvim.

arara works nicely on the command line (cmd, powershell, and git bash). However, when I try to compile with vimtex, a window appears and immediately disappears on the taskbar, too quickly to discern anything. No compiler output is stored in the temp file referenced by `:VimtexCompileOutput`, and no `arara.log` is saved. I don't know how to debug this, or I would! I spent some time reading the arara-specific compiler code, but I think someone may be able to answer my question quickly.

Is there a way that I can echo the exact command that vimtex is trying to execute for compilation? Maybe then I could see what's wrong. Thanks much!!

-----

1. Minimal `~/_vimrc` file:

```vim
set nocompatible
let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'

let g:vimtex_compiler_method='arara'
let g:vimtex_view_method='mupdf'
let g:vimtex_view_forward_search_on_start=0
```

2. Minimal `main.tex` file:

```tex
% arara: pdflatex
\documentclass{minimal}
\begin{document}
Hello World!
\end{document}
```

3. Steps to reproduce:

    - Run `gvim E:\demo\main.tex`.
    - Run `:VimtexCompile`. A window opens and closes almost instantaneously. Meanwhile, in gVim, a new status is reported:

        > vimtex: Compiler started in background

    - Run `:VimtexCompileOutput`. An empty file is opened, with a path like `~/AppData/Local/Temp/ABCD123.tmp`.

-----

I'm assuming this is unrelated, but xdotool doesn't support windows. Accordingly, on startup, I get a notice:

    > vimtex: MuPDF requires xdotool!

I was hoping that vimtex would let me use MuPDF without xdotool by setting

```vim
let g:vimtex_view_forward_search_on_start=0
```

However, it seems to have disabled `:VimtexView`.

**Comment by lucasreddinger** [comment]
I'm assuming this is unrelated, but xdotool doesn't support windows. Accordingly, on startup, I get a notice:

>vimtex: MuPDF requires xdotool!

I was hoping that vimtex would let me use MuPDF without xdotool by setting
>let g:vimtex_view_forward_search_on_start=0

However, it seems to have disabled `:VimtexView`.

**Comment by lervag** [comment]
First, I took the liberty of freshing up your issue post with some more formatting and a more minimal vimrc file.

Let's start with MuPDF.  I've pushed an update that I think should make it work. Please test.

About the main issue. Which version of Vim are you on? Could you give me the output of `\li` after opening the `main.tex` file?

**Comment by lucasreddinger** [comment]
First, I really appreciate your response and help!

re: MuPDF--Yes, the error message about xdotool is no longer displayed. Thanks!

-----

Regarding the main issue, my version is:

> VIM - Vi Improved 7.4 (2013 Aug 10), MS-Windows 32-bit GUI version with OLE support.

I'd check for a newer version of Vim, but vim.org is not responding--I think all SourceForge websites are offline.

[Here is an unrelated error message I get upon starting Vim, since pulling the updates.](https://user-images.githubusercontent.com/2672779/36888685-703ca9ba-1dab-11e8-85b9-c9f5cb316166.png)

[Here is the output from \li, following \ll.](https://user-images.githubusercontent.com/2672779/36888686-70569c08-1dab-11e8-965a-f29f9c3be35d.png)

(Sorry about using image captures, but I couldn't manage to copy either texts, and I didn't want to make an error.)

BTW, I tried the `~/.vimrc` you posted, but it didn't work to load vimtex, so I'm using this `~/.vimrc`:

```
set nocompatible
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_compiler_method='arara'
let g:vimtex_view_method='mupdf'
let g:vimtex_view_forward_search_on_start=0
```

**Comment by lervag** [comment]
Ok. I believe this issue might be resolved directly if you use Vim 8, which should be [available for Windows here](https://www.vim.org/download.php). Can you update and report back?

**Comment by lucasreddinger** [comment]
Updated to Vim 8. Compilation with arara now works! Thanks!

![capture_2018-03-05_0006](https://user-images.githubusercontent.com/2672779/36994095-e31f3e5a-2064-11e8-861b-499a0ab4c232.png)


`\lv` is not opening the pdf in mupdf, as expected. I can run `mupdf` from the command line successfully, so $PATH includes the mupdf.exe location.

If I'm understanding the limitation of not having xdotool, even if vimtex can open the pdf in mupdf, it can't send mupdf an `r` keystroke to reload the file, correct? (I realize it can't search through the file, as explained elsewhere, without xdotool.)

Beyond that, this addresses the scope of the original issue. And I think this gives Windows users a pretty decent workflow. One can compile and re-compile from Vim. To view output, however, one must Alt-Tab to mupdf and press `r` to reload the file (or open it, if mupdf isn't already open).

If I'm missing anything that could make the Windows vimtex experience better, I'd love to hear.

Thanks again!

-----

Side notes: Still getting a couple quirky error messages with Vim 8. I can't tell what the effect of these are; maybe they don't matter at all.

* [An error on start-up.](https://user-images.githubusercontent.com/2672779/36994117-f27236aa-2064-11e8-9c8f-ab059c5c284a.png)
* [Post-compile callback error message.](https://user-images.githubusercontent.com/2672779/36994122-f5bc2b22-2064-11e8-87a8-5cef33c5c0f9.png)

**Comment by lervag** [comment]
- I'm very happy to hear that Arara works! :)
- I don't quite understand why `mupdf` suddenly stopped working. Perhaps the `$PATH` is not properly set (even though it seems like it from the command line)? Check `:echo $PATH` inside Vim. If you still can't get it to work, please open a new issue for this.
- And yes, you need `xdotool` to make MuPDF update after compilation and to synchronize the views (only on page level). I am not interested in finding other alternatives to xdotool on Windows, but if you should find any you are welcome to submit a PR.
- As for suggestions: How about using SumatraPDF? I have the impression this is more standard on Windows and that it works quite well. See `:h vimtex_viewer_sumatrapdf`.
- I've seen the startup-error a couple of times now from different people, and I would be very happy to solve this once and for all. Again, could you open a new issue for it? Please provide a minimal description of how to replicate.
- The last error was due to a minor bug in the mupdf viewer, and I think it is fixed now.

**Comment by lervag** [comment]
I'm closing this, as it seems the remaining issues should be opened as new issues.
