### ISSUE TITLE
Recognize \begin{frame}\end{frame} (beamer) as "sections"

### ISSUE THREAD

**Issue by anntzer** [lervag/vimtex#1072]
While beamer files can include `\section{}`s, most often the "sectioning" element there is \begin{frame} ... \end{frame}.  I would thus suggest, if possible, to recognize these too in the iP/aP text elements.
While there already exists ie/ae for environments, these will recognize any "inner" element, e.g. in
```
\begin{frame}
\begin{center}
\end{center}
\end{frame}
```
if the cursor is in the "center" environment, then ae will recognize that environment, whereas I'd like aP to recognize the entire frame.

**Comment by lervag** [comment]
I don't really think this is that useful as a general feature, but you can implement it with something like this:

```vim
xnoremap <silent><buffer> iB :<c-u>call GetFrame(1, 1)<cr>
xnoremap <silent><buffer> aB :<c-u>call GetFrame(0, 1)<cr>
onoremap <silent><buffer> iB :<c-u>call GetFrame(1, 0)<cr>
onoremap <silent><buffer> aB :<c-u>call GetFrame(0, 0)<cr>

function! GetFrame(is_inner, mode) abort
  if a:mode
    call vimtex#pos#set_cursor(getpos("'>"))
  endif

  let [l:l1, l:c1] = searchpairpos('\\begin{frame}', '', '\\end{frame}', 'bnW')
  if l:l1 == 0 | return | endif

  let [l:l2, l:c2] = searchpairpos('\\begin{frame}', '', '\\end{frame}', 'nW')
  if l:l2 == 0 | return | endif

  if a:is_inner
    let l:l1 += 1
    let l:l2 -= 1
  endif

  normal! V
  call vimtex#pos#set_cursor(l:l1, l:c1)
  normal! o
  call vimtex#pos#set_cursor(l:l2, l:c2)
endfunction
```

Add that to your own ftplugin, e.g. in `~/.vim/after/ftplugin/tex.vim`. Note, this is not at all perfect, but it is a simple and working implementation.
