### ISSUE TITLE
question: how to debug some errors

### ISSUE THREAD

**Issue by teto** [lervag/vimtex#1073]
# Explain the issue

I had VimtexCompile starting without anything happening (with master). When running VimStatus, it would show not running. VimtexLog gives:

```
13:55:52: warning
  from: vimtex#complete#init_buffer
  from: s:init_buffer
  from: vimtex#init
  bibtex is not executable!
  bibtex completion is not available!

13:56:21: info
  from: vimtex#compiler#compile
  Compiler started in continuous mode

13:57:26: warning
  from: vimtex#compiler#status
  Compiler is not running!
```

I ended up running latexmk myself

```
Unquoted string "bin" may clash with future reserved word at (eval 9) line 1, <GEN0> chunk 1.
Unquoted string "bibtex" may clash with future reserved word at (eval 9) line 2, <GEN0> chunk 1.
Latexmk: Initialization file '/home/teto/.latexmkrc' gave an error:
     Unknown regexp modifier "/t" at (eval 9) line 1, at end of line
     Unknown regexp modifier "/r" at (eval 9) line 1, at end of line
     Unknown regexp modifier "/e" at (eval 9) line 1, at end of line
```

thus I fixed the .latexmkrc (an unquoted string) and it fixed the issue. Now I wonder if vimtex couldn't have logged the latexmk error or at least throw a warning.

**Comment by lervag** [comment]
Interesting request. What happens if you revert the `.latexmkrc` file so that it is wrong, then try to start compilation from Vim, then do `\lo` (`:VimtexCompileOutput`)? I think it should show the same output as you saw when you run `latexmk` yourself.

**Comment by lervag** [comment]
Also, it would help if you could provide a minimal example of this problem. That is, if I were to try to add some feature that shows a warning or error if the latexmk process does not start properly, then it would help to have a minimal example where the latexmk process fails to start.

**Comment by teto** [comment]
Just create a wrong .latexmkrc, for instance `$bibtex=/nix/store/2rxl0lhrki16p0b1h6bgjhc2psajj0f3-texlive-combined-2017/bin/bibdadad` (unquoted => error)

Then open your main.tex, run `:VimtexCompile`. There is no error, `VimtexCompileOutput` is empty. I have to do VImtexInfo, copy/paste/run the latexmk command to see the error about the .latexmkrc.

**Comment by lervag** [comment]
Ok, I've tried to improve this. It will only work on neovim and Vim 8, i.e. it requires the `timer_start` function. The update makes vimtex check if the process for some reason does not start, and if it does not, then we try to open the latexmk output to make it clear what the error might be. Please see if this makes things better for you.

**Comment by lervag** [comment]
Feel free to reopen if you have further comments.
