### ISSUE TITLE
question: custom delimiter for indentation

### ISSUE THREAD

**Issue by mrajner** [lervag/vimtex#1074]
I would like to increase indent inside square brackets (same as it is enabled fro curly braces).
I tried to change variables for delimiters adding pair of `[` and `]` but I had troubles to make it work.
Is it possible by playing with `g:` variables instead of touching `indentexpr`?

**Comment by lervag** [comment]
No, this is not possible right now. Indentation is hard, and I think the current version is pretty good. There is a balance between what is possible to implement and what is desired. I am the first to acknowledge that the current version is not perfect, e.g. there should be more context-aware indentation such as indenting simple parantheses inside math environments. However, improving in this direction is highly nontrivial.

So, to the specific request: Some years ago I did add indents for `[` and `]`, but I changed after some discussions. I can't remember exactly when and which issue, but to give some perspective on how hard it is, please see: #342, #605 (this is an example of how adding this kind of support might break things for other people), #592 (more on unbalanced pairs of delimiters), #396 (possible the issue that led to removing `[]` from indented delimiters.

My suggestions is that you either live with the limitation, or learn some vimscript and suggest a change that does not break things for other users while giving the desired functionality.

**Comment by mrajner** [comment]
Thank you for detailed reply with references.
I though that some clever setting of `g:vimtex_delim_list` would work. And I couldn't figure it out. Now I know that it is much harder.
I will use some private and nasty trick then.

**Comment by lervag** [comment]
No problem. Don't hesitate to share you "nasty trick". If it is smart, it could inspire an update from my side. :)

**Comment by mrajner** [comment]
Do not expect nothing smart from me. I will live with simple solution:
https://github.com/mrajner/vimtex/commit/54b22adcf3b04f36b1d36e3d2fbf09a95e6b2d80
If I encounter serious sideeffects I will let you know. I will keep an eye if one day you would add an option for custom pair of delimiters for indentation to set by user.

**Comment by lervag** [comment]
This should not have any side effects.However, I could add an option, something like this:

```vim
let g:vimtex_indent_delims = {
      \ 'open' : ['{', '\\\@<!\\\['],
      \ 'close' : ['}', '\\\]'],
      \}
```

with updated code like this in `indent/tex.vim`:

```vim
let s:re_open = g:vimtex#delim#re.delim_mod_math.open
      \ . join(g:vimtex_indent_delims.open, '\|')
let s:re_close = g:vimtex#delim#re.delim_mod_math.close,
      \ . join(g:vimtex_indent_delims.close, '\|')
```

This should allow you to customize which delimiters that add indents. What do
you think?

**Comment by mrajner** [comment]
Yes, that would be nice, it will not brake backward compatibility giving flexible choice for  user. I thought about similar solutions when I saw in the code that for `s:re_` you already joining predefined `g:vimtex#delim#re`.(I do not know however why in open `[` you check if it is not part of `\[` and in close you indicate math delimiter `\]` , is that typo?.)

There is still however problem with unpaired custom delimiters. Few years ago I used to fix the `beamer` fragile frame indentation to force the ending frame statement start without any whitespace. So I used indentation changing curly braces after comment sign. It worked. With your syntax aware plugin (and also without it with new vim version) it doesn't work.
Here is example
````tex
    ...
    % for some reason new frame does not start from begining of line
    \begin{frame}[fragile]
        Hello world 
    % the \end{frame}  would end with leading whitespaces
    % so I head to change it manually, and line below used to do that trick
    %}
% the number of commented unimpared curly braces depends on how much `&sw` I have to change
% now we do not have whitepace for the closing frame environment statement.
\end{frame}

% now I need to restore my indent
%{
    % and I am again with increased indent
    \begin{frame}
````
This unpaired curly braces do not work anymore. Maybe you could add some syntax to manually change indention. `%{{{` would increase indention  3 times `&sw` . Something like manual folding in vim.

**Comment by lervag** [comment]
If I copy your example into vim and indent it with vimtex indentexpr, it indents exactly as expected. I don't understand your problem here.

There is no typo in `\\\@<!\\\[`. `\\\@<!` says "no \", then `\\\[` matches `\[`. That is, this will match any `\[`, but not `\\[`. The point is to match display math environments like `\[ ... \]`.

**Comment by lervag** [comment]
Besides, using commented `%{` and `%}` to control indents is not good. If I worked on a paper with a collaborator who did that, I would ask him to stop.

**Comment by mrajner** [comment]
ah, ok. Your example was for `\[` and `\]`. It is ok. I was thought of simple `[` and `]`.
You are right that supporting of manual indentation would be problematic with file shared with other collaborators. Good point.

Anyway for future reference and other insubordinate users, here is how you can cheat indention
````tex
\iffalse {{{\fi
`````
but it breaks syntax higlighting.

Returning to main topic. Supporting of user defined indention delimiter pairs would be nice feature. And as you provided example already, it won't be hard to implement.

**Comment by lervag** [comment]
Ok, I've implemented this. Could you please see if it suits your needs? I've documented the new option and also allowed to not include the default math modifier delimiters. This allows one to customize it as desired at a full level.

**Comment by lervag** [comment]
Yes, `\else` would be more difficult because it will both add and reduce indents. As such, I would rather implement `\if ... \else ... \fi` in a different manner. If you open an issue for this it would help me remember to look at it. (I would think that indenting this makes sense as a default behaviour.)

**Comment by mrajner** [comment]
I would not recommend of making it default behaviour because the proper regular expressions could become overcomplicated (I saw some threads that the performance is also concern for you). But it should be definitely consider as the optional parameter.
This is continued in new issue #1078.

**Comment by lervag** [comment]
Thanks!
