### ISSUE TITLE
No error tab in nvim v0.2.2

### ISSUE THREAD

**Issue by Lezcano** [lervag/vimtex#1079]
This issue is similar to https://github.com/lervag/vimtex/issues/767, but the solution proposed in that one did not fix it in my case.

When a document compiles with errors, if the pdf compiler cannot recover from the error, no error tab is shown. Interestingly enough, if the pdf compiler can recover, it does show the error tab.

My vimtex configuration is as follows:

```vim
let g:vimtex_compiler_latexmk = {
    \ 'continuous' : 1,
    \ 'background' : 1,
    \ 'build_dir' : 'build',
    \}

if has('nvim')
    let g:vimtex_compiler_progname = 'nvr'
endif
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique @pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
let g:vimtex_quickfix_method = 'pplatex'
```

These are two example outputs of `lo` and `li` after a non-recoverable error happened.
```
Latexmk: This is Latexmk, John Collins, 17 Jan. 2018, version: 4.55.
Viewing pdf
Rule 'pdflatex': File changes, etc:
   Non-existent destination files:
      'build/robust.pdf'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -synctex=1 -interaction=nonstopmode -recorder -output-directory="build"  "robust.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
[... compilation info ...]
 [1
{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map
}
]
)
Runaway argument?
{X, \theta \] \par \subsection {Discussion of Section 4 in the origin\ETC.
! File ended while scanning use of \\MT_delim_pa_nostar:.
<inserted text> 
                \par 
<*> robust.tex
              
! Emergency stop.
<*> robust.tex
              
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on build/robust.log.
Latexmk: Failure to make the files correctly
    ==> You will need to change a source file before I do another run <==
------------
Running '/bin/nvr --servername /tmp/nvimzrASfj/0 --remote-expr "vimtex#compiler#callback(0)"'
------------
=== TeX engine is 'pdfTeX'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 1
      Refer to 'build/robust.log' for details
```
```
System info
  OS: Arch Linux
  Vim version: NVIM v0.2.2
  Has clientserver: true
  Servername: /tmp/nvimzrASfj/0

vimtex project: robust
  base: robust.tex
  root: /home/lezkus/gdrive/Documentos/1DPhil/notes
  tex: /home/lezkus/gdrive/Documentos/1DPhil/notes/robust.tex
  out: 
  log: /home/lezkus/gdrive/Documentos/1DPhil/notes/build/robust.log
  aux: /home/lezkus/gdrive/Documentos/1DPhil/notes/build/robust.aux
  fls: /home/lezkus/gdrive/Documentos/1DPhil/notes/build/robust.fls
  document class: scrartcl
  packages:
[...packages...]
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimzrASfj/1
    configuration: 
      continuous: 1
      callback: 1
      build_dir: build
      latexmk options:
        -verbose
        -pdf
        -synctex=1
        -interaction=nonstopmode
    pid: 5138
    cmd: max_print_line=2000 latexmk -verbose -pdf -synctex=1 -interaction=nonstopmode -outdir=build -pvc -e '$pdf_previewer = "okular --unique"' -e '$success_cmd = "'""'/bin/nvr'""' --servername '/tmp/nvimzrASfj/0' --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'""'/bin/nvr'""' --servername '/tmp/nvimzrASfj/0' --remote-expr \"vimtex\#compiler\#callback(0)\""' 'robust.tex'
  viewer: General
  qf: LaTeX logfile using pplatex
    setqflist: 152
```
I'm using vimtex 6b96500ce49ee51336390a43534e9f426130bac7

**Comment by lervag** [comment]
First: When you say "error tab", I think you mean Quickfix Window. See `:h quickfix`.

So, to the issue at hand. Could you provide a minimal LaTeX sample and a minimal vimrc file? For the issue you describe, I would suspect that the following should suffice:

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_compiler_latexmk = {'build_dir': 'build'}
if has('nvim')
  let g:vimtex_compiler_progname = 'nvr'
endif
let g:vimtex_quickfix_method = 'pplatex'
```

I'm also curious if you have the same problem without pplatex.

> When a document compiles with errors, if the pdf compiler cannot recover from the error, no error tab is shown. Interestingly enough, if the pdf compiler can recover, it does show the error tab.

I don't understand what you mean with "pdf compiler can/cannot recover". After
a non-recoverable error, what happens when you do `\le` to open the Quickfix
window?

**Comment by Lezcano** [comment]
When I use that minimal `.vimrc` and I have a non-recoverable error (like a missing `}`), I get:
```
robust.tex|470 warning|  Citation `maurer2009empirical' on page 5 undefined
|| ** Error  :
||    File ended while scanning use of \frac  <inserted text>  \par  <*> robust.tex
||    I suspect you have forgotten a `}', causing me
||    to read past where you wanted me to stop.
||    I'll try to recover; but if the error is serious,
||    you'd better type `E' or `X' now and fix your file.
```
So the error is indeed displayed in the quickfix window.
By non-recoverable error, I mean one in which the compiler does not manage to just omit it. An example could be writing `$\frac{2}{1$`, while a recoverable error would be writing `$\alhpa$` (an unrecognised keyword.

While writing this post and changing my `.vimrc` for your minimal `.vimrc` and then changing it back to the original `.vimrc` the error has disappeared. I truly do not know what happened there. I'll close this for now, and I'll reopen it if I can reproduce this error.
Thank you for your quick and helpful response!!

**Comment by Lezcano** [comment]
It happened to work the first time. Then I corrected the missing `}`, and after deleting it again and recompiling it the error's back.
When a non-recoverable error happens and I press `\le` nothing happens.

If I don't use `pplatex` I do get the error (a different one):
```
  1 X.tex|| File ended while scanning use of \frac .
  2 X.tex|| Emergency stop.
  3 X.tex|| ==> Fatal error occurred, no output PDF file produced!
```
so I believe this is related to the use of pplatex

**Comment by lervag** [comment]
This is strange. The minimal example works for me. I use the vimrc file as above and this minimal LaTeX file:

```vim
\documentclass{minimal}
\begin{document}

Hello World! $\frac{2}{1$

\end{document}
```

I'm using pplatex version 1.0-rc2.

**Comment by Lezcano** [comment]
You are right, your example does work. I provide here a minimal example where I found this behaviour.
```
\documentclass{minimal}

\usepackage{mathtools}

\DeclarePairedDelimiter\pa{\lparen}{\rparen}

\begin{document}

Hello World! $\pa{asdf$

\end{document}
```
It did compile well the first time that I executed `\ll`, but when I corrected the error, saved, and then I deleted the ending `}` and saved again I got the bug.

Please confirm me if you can replicate this behaviour.

I am using the same pplatex version as you.

**Comment by lervag** [comment]
Ok, I've reproduced and tried to improve things. It is not perfect, but it is difficult to improve it much further, sorry. But it is better than before, I hope you agree!
