### ISSUE TITLE
change surrounding delimiter unexpected behavior

### ISSUE THREAD

**Issue by pierreganty** [lervag/vimtex#1080]
insert 
`[bla]`
place the cursor between the brackets
in normal mode press `csd`
in the prompt press `{`
result is 
`{bla{`

**Comment by clason** [comment]
I can confirm this; entering `}` results in `}bla}`. (The other delimiters work fine.)

**Comment by lervag** [comment]
Yes. When I implemented this, it was meant to be used in math mode, where `{}` is not really a delimiter. That is, it is not a math delimiter. So what is happening here is that the `{` or `}` is not recognized as a delimiter and so it is replaced as is.

So, we should decide what is the expected result here. I think perhaps the current behaviour is correct, even though it might be a little bit surprising. If you want to change e.g. `[...]` to `{...}`, you can do `csbB` as @clason suggests (if you have vim-surround, that is). I did not  want to reimplement vim-surround, I only implemented consistent feature for LaTeX specific math modified delimiters. The prompt has completion, so if you do `<tab>` in the prompt, it will show you the possible candidates.

**Comment by clason** [comment]
While I see the argument that `}` is not a proper delimiter in math mode, I do think the behavior is somewhat unexpected -- consistency (where feasible) would be good to strive for. On that note: How does https://github.com/andymass/vim-matchup behave?

**Comment by pierreganty** [comment]
I agree with @clason on this one.

**Comment by andymass** [comment]
@clason, vim-matchup does not have a "change surrounding" feature, i.e., there is no `cs%` map.  I'm open to it eventually I suppose, but implementation would be difficult.  The replacements essentially have to be handled as a series of special cases, and vimtex/surround/sandwich already do a pretty good job with a reduced scope.  vim-matchup doesn't interfere with vimtex's `csd`, `cse`, etc., at all.

**Comment by clason** [comment]
@andymass True, the matching in `vim-matchup` is not based on the concept of delimiters but on more basic (less semantic) parentheses. So sorry to drag you into this! This wasn't a feature request but more of a poll to see what is out there to be consistent with.

(But the matchup README does mention the grand master plan of integrating with `vim-surround` :smile: )

**Comment by lervag** [comment]
I've updated now. I've reconsidered and I think you might be right that fixing this will never hurt, but that not fixing it will lead to unexpected results as the one you raise. Let me know if there should be any unexpected side effects... :)
