### ISSUE TITLE
Does not compile in newly created folders

### ISSUE THREAD

**Issue by ernestorenanche** [lervag/vimtex#1081]
When I create a new folder and edit a tex file in it, the plugin compiles it only once and then stops working properly.

### Normal behaviour
```
cd old_folder
vim new_file.tex
```

Insert
```latex
\documentclass{minimal}
\begin{document}
Hello
\end{document}
```

`:w` and `<leader>ll` produces a document with written hello.
If I udpate the file to
```latex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```
`:w` updates the document with written Hello world!

### Abnormal behaviour

```
mkdir new_folder
cd new_folder
vim new_file.tex
```

Insert
```latex
\documentclass{minimal}
\begin{document}
Hello
\end{document}
```

`:w` and `<leader>ll` produces a document with written hello.
If I udpate the file to
```latex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```
`:w` and nothing happens.

### My vimrc
```vim
set nocompatible
set runtimepath+=/home/ronan/.vim/bundle/neobundle.vim/
call neobundle#begin(expand('/home/ronan/.vim/bundle'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/vimproc.vim', {
      \ 'build' : {
      \     'windows' : 'tools\\update-dll-mingw',
      \     'cygwin' : 'make -f make_cygwin.mak',
      \     'mac' : 'make',
      \     'linux' : 'make',
      \     'unix' : 'gmake',
      \    },
      \ }
NeoBundle 'lervag/vimtex'
call neobundle#end()
NeoBundleCheck
filetype plugin indent on
```

### Other informations
I am running Ubuntu 17.10 with Vim 8.0.

**Comment by lervag** [comment]
I can't reproduce this. Also, I don't understand the difference between the two scenarios. It seems you are saying the if you do `cd old_dir`, then create new file and compile, things work. But if you do `mkdir new_dir` then `cd new_dir`, then the same thing as before, now things don't work. But this does not make any sense to me.

Your minimal vimrc file is bloated. It should be

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
```

No reason to include neobundle.

**Comment by ernestorenanche** [comment]
Yes it doesn't make much sense to me neither. However I observed this bug by creating new folders at various locations on my computer.

**Comment by lervag** [comment]
Still, it is up to you to describe a way to reproduce the issue. And as I said, I can't reproduce this.
