### ISSUE TITLE
Forward sync not working with Skim

### ISSUE THREAD

**Issue by alecshaw** [lervag/vimtex#1084]
I am attempting to get forward sync to work with Skim. It hasn't worked for me for some time, but today I've decided to tackle the issue, and I could use some help.

My minimal `vimrc`:

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

let g:vimtex_view_method = 'skim'
```

My minimal `.tex` file:

```tex
\documentclass{minimal}

\usepackage{lipsum}

\begin{document}
\lipsum[1]
\newpage
\lipsum[2]
\newpage
\lipsum[3]
\end{document}
```

3. Steps to reproduce:
a. Load the file with `mvim -u vimrc synctex-fix.tex`.
b. Start the compilation process with `\ll`.
c. Skim loads, showing the first page of the PDF.
d. The PDF updates normally as text is added (here, additional `\lipsum` commands), but there is no forward search. Additionally, the red dot drawn for a second on the PDF to find your place does not appear.

`\lv` works as expected, triggering a forward search to the correct place, with the appropriate red dot drawn on the PDF as a visual marker of location (it does also highlight the line where the red dot draws, which is an issue, but that is for another issue).

The expected behaviour which is for forward search to work. It had previously, and I can't recall what may have changed with my setup.

This is possibly a related past issue? https://github.com/lervag/vimtex/issues/1002

**Comment by clason** [comment]
This is by design: There was a request to *not* skip around the PDF when updating using the callback after successful compilation, which was implemented in https://github.com/lervag/vimtex/pull/997. Only the explicit `\lv` triggers the forward search with highlighting.

**Comment by lervag** [comment]
Yes, as @clason says, this is by design. I don't use OSX and don't have very many opinions about this myself. But I think the current design desitions are pretty well thought out.

**Comment by alecshaw** [comment]
Alright, good to know. Thanks to both of you!

**Comment by lervag** [comment]
No problem :)
