### ISSUE TITLE
vimtex-toc: fold todos & add option to remove todos completely

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1085]
In a larger manuscript you might end up having a longer list of todo markers in your document.

They will take up a large percentage of the vimtex-toc which I do not like.

### Dedicated List of Todos
Personally, I would remove them from the toc and would provide a dedicated list of todos (similar to labels).

### Dedicated Plugins for Todo Markers

BTW, there are dedicated vim plugins to list todo markers:
- https://github.com/vim-scripts/GrepTasks
- https://github.com/gilsondev/searchtasks.vim
- https://github.com/vim-scripts/TaskList.vim
- https://github.com/neoclide/todoapp.vim (requires sqlite)

However, ft-specific support which understands packages and simple comments

- `% TODO`
- `\todo[inline]{...}`

could be a reason to have vimtex to do this.

### Add a Fold for Todos in vimtex-toc
Since other people like to have this in the toc, I would suggest to add at least a fold for them.

### Add Separate Denite Source for vimtex-todos

Another request regarding the todo markers would be to have separate denite source.

### Location List

I have another thought about these kinds of lists. Why do you not use vim's location list?

I would parse the document, store in a vim dictionary the lists, and just print them on request to the location list.

### List of Figures & Tables

Actually, one could also provide 
- List of Figures
- List of Tables

similar to LaTeX. But this would be separate issues.

**Comment by lervag** [comment]
Sorry for not responding sooner. This is a large request, and so it has not been prioritized in between smaller issues and a pretty full general schedule.

First: I've implemented folds for (sorted) TODOs now, and it seems to work well. Let me know if it works for you.

----

Do any of the dedicated Todo Marker plugins allow customization of how to recognize a TODO on a ft specific level? If so, that could perhaps be used to provide what you want.

----

If I understand correctly, these are the main elements of your suggested updates:

- To allow the use of the location list for displaying the various lists.
- A separated list of TODOs similar to the table of contents/labels (including a denite source). I've opened #1101 for further discussions on this.
- Lists of figures/tables: I would kindly ask that you propose this in a separate issue when this issue. I'll solve this issue first. It will make it easier for me to keep focus.

# Location lists

This needs some clarification on how it should work with regard to options. E.g.: Should it be possible to let the default action of `:VimtexToc` be to simply fill (and open) the location list? Should there be separate options for each type of list? What should the options be?

**Comment by kiryph** [comment]
Thanks for considering this request and I want to apologize for this too broad issue. If I could go back in time, I would only have asked if it would be possible to define a fold.

I think my intention was that I wanted to point out that there might be different approaches to handle todo lists.

First of all folding works. However, I haven't figured out how I could fold the todos by default without folding other at the same level. This might be not possible.

---

Regarding using todo marker plugins. I haven't used them I just checked the docs. As far as I see it, they simply scan for keywords (todo, fixme, ...), stripping of options from `\todo[inline]{actual todo text}` would not be possible.

---

Regarding location list:

On https://www.vi-improved.org/recommendations/ you can read:

> Plugins that have persistent UI elements (sidebars, mock-tabs, etc) are generally frowned apon as they don't scale.

I do not agree in general, but I certainly appreciate vim's builtin features and I would use them as long as they can do what I want. A simple list of todos (no folding, indentation, or other feature needed) feels like the location list could be enough.

On the other side you could use vimtex-index functionality and be consistent with labels and toc.

---

Since I already bugged you with three open issues I will not open requests for Lists of figures/tables. No new feature issues from me in the next time.

---

And sorry that I do not answer all of your questions you have raised, but right now this issue is not as important as it looked like. I was just annoyed that my todo markers filled up the vimtex-toc which I tend to use for navigation.

**Comment by clason** [comment]
> Since I already bugged you with three open issues I will not open requests for Lists of figures/tables. No new feature issues from me in the next time.

Then let me step in: having a Table of Figures and a Table of Tables as well *would* be useful! :) (But low priority; first things first.)

**Comment by lervag** [comment]
Thanks, @clason. I've opened a new issue for that, see #1106.

Also: Reopening this. Will close when location list feature is completed.

**Comment by lervag** [comment]
Adding index content to the location list should now work. See `:h vimtex_index_mode`.

Next step is separating the ToC and the table of TODOs.
