### ISSUE TITLE
setting up backward search

### ISSUE THREAD

**Issue by esquires** [lervag/vimtex#1086]
I am trying to setup backward search with vimtex and neovim with okular (or zathura). Following the documentation, I have set the custom editor to "nvr --remote-silent %f -c %l" in okular.

The minimal vimrc I am using is

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_compiler_progname="nvr"
"let g:vimtex_view_method = 'zathura'
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
```

The minimal tex file I am using is

```tex
\documentclass{minimal}
\begin{document}

Hello World (page 1)
\newpage
Hello World (page 2)

\end{document}
```

I start nvim with ``nvim -u vimrc main.tex``. After hitting "\ll" I see the document opened in okular. I can scroll down to the line "Hello World (page 2)" and hit "\lv" to see okular move to page 2.

When I go to okular and double click on "Hello World (page 1)" I was expecting it to cause neovim to move the cursor in the terminal to line 4 (where the text "Hello World (page 1)" is) but nothing happens. Can you help me understand where I am going wrong?

These are the versions I am using:
* neovim: v0.2.2
* okular: 4.14.16 (from ubuntu 16.04 repos)
* neovim-remote: 1.9.4 (from pip)

I have also tried with zathura where the "zathura" line in the vimrc is uncommented and the lines following are commented.

**Comment by lervag** [comment]
# Okular

With Okular, you need to set the reverse search inside Okular settings. [This thread](https://tex.stackexchange.com/questions/419/how-to-set-up-inverse-search-with-okular-and-kile) shows how to edit the correct Okular settings. I do see you have tried this already, so here are some additional hints:

- Be sure that you have `neovim-remote` installed and that `nvr` is executable.

- In order for `nvr` to work, it needs to have the servername available. By default, `nvim` will use a temporary and random servername, e.g. `/tmp/nvim8XEKUS/0`. If you instead use `nvr` to start neovim, it should use a more accessible default servername, which should make it easier to get things to work. The bottom line is: you need to make the servername available to `nvr`.

- After you have opened a LaTeX file, you can check that `nvr` can communicate from the terminal with e.g.

    ```sh
    nvr -c "echo 'Hello world!'"
    ```

- If the previous test works, then you should be able to get reverse search with the setting that you mentioned. You can also try to use the following:

    ```
    nvr --remote-expr "vimtex#view#reverse_goto(%l, '%f')"
    ```

    Note that you might need to escape the `#`s with backslashes.

# Zathura

If you use Zathura, vimtex will automatically add `--servername ...`, which
means it should work in most cases directly. If it does not work for you, then
there might be something wrong on your end. Do you have `xdotool` installed?

**Comment by esquires** [comment]
Thank you for the feedback. I have confirmed the following:

* `nvr` is executable 
* when neovim is opened I can open in another terminal `nvr  -c "echo 'Hello world!'` and see the message show up in the neovim buffer
* I can execute `nvr --remote-expr "vimtex#view#reverse_goto(4, 'main.tex')` in another terminal and see the neovim buffer move the cursor to line 4
* `xdotool` is installed

It looks like I can now hold ctrl and left click on zathura and see neovim update. okular, however, still isn't working. That said, I wrote the following script

```[bash]
#!/bin/bash
echo "args are $@" > ~/okular.txt
```

set it to executable in my $PATH, set okular's custom editor command to `my_prog %l %f`, and didn't see anything show up in `~/okular.txt`. Apparently there is something wrong with how my okular is calling the external editor.

The zathura solution will work fine for me though. Thanks for your suggestions.

**Comment by lervag** [comment]
I'm happy to hear things are working with Zathura. And I'm sorry that I can't help more with Okular, but since you are fine with Zathura all is well. :)

**Comment by felixwoolford** [comment]
I know this is an old issue, but I just wanted to say that after having had exactly the same issue with Okular not working I have found a possible solution which may help someone in the future: In order for shift+left click to trigger the external command, Okular must have the "browse" tool activated, rather than "text selection" which in my case at least tends to be what is usually activated!

**Comment by vmichals** [comment]
@felixwoolford Thank you for posting this tip!

**Comment by lervag** [comment]
> Try adding `-synctex=1` to your g:vimtex_compiler_latexmk's options. …

`-synctex=1` is already included in the [default option list](https://github.com/lervag/vimtex/blob/7f2633027c8f496a85284de0c11aa32f1e07e049/doc/vimtex.txt#L1023-L1039). Your suggested would actually _break_ things, because it will remove the other default options.
