### ISSUE TITLE
VimtexView with SumatraPDF is broken on Windows

### ISSUE THREAD

**Issue by JackeJR** [lervag/vimtex#1088]
Minimal `vimrc` from `"vimfiles\plugged\vimtex\test\examples\minimal\minivimrc"`.
Minimal `tex` file:

    \documentclass{minimal}
    \begin{document}
    Hello World!
    \end{document}

Suggested SumatraPDF configuration:

```
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
            \ = '-reuse-instance -forward-search @tex @line @pdf'
            \ . ' -inverse-search "gvim --servername ' . v:servername
            \ . ' --remote-send \"^<C-\^>^<C-n^>'
            \ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
            \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
            \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
            \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'

```

On pressing `\lv`, a terminal window opens and close briefly without opening SumatraPDF.
I am not sure when this error was introduced as it worked fine a few commits back. Not sure what the proper troubleshooting procedure is but I tried the following:

- Open up process monitor and start capturing
- Capture the command triggered by `vimrun`
- Test out the command in a command prompt

The command throws a `system cannot find file` error and breaking it down, I think it boils down to errors in escaping the resulting command. Where should I begin to investigate this further?

On further testing, this was introduced in commit 6c172bdf3bc89d0f5154e7c875b66d48baa60aee

I just saw that this was already reported at https://github.com/lervag/vimtex/issues/1054.

**Comment by lervag** [comment]
Thanks! I've reverted 6c172bd.
