### ISSUE TITLE
Something went wrong when parsing log files

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1092]
I am using neovim 0.2.2 with latest neovim remote
I have set the compiler progname option to 'nvr' which is in my path.

The quickfix window does not open automatically upon errors/warnings. Manual :copen works fine. When \le is issued, vimtex issues an error "something went wrong in parsing the log file"

**Comment by lervag** [comment]
Please read the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md). It is very difficult to understand your problem when you don't provide relevant details.

**Comment by krishnakumarg1984** [comment]
Thank you. The problem was caused due to incompatibility with the vim-qf plugin https://github.com/romainl/vim-qf

I have disabled this plugin for now.

**Comment by lervag** [comment]
See [vim-qf#45](https://github.com/romainl/vim-qf/issues/45), which I think is very relevant for you here.

See also #754.

**Comment by krishnakumarg1984** [comment]
Thank you. Do you want to mention this conflict in your documentation, and a possible workaround being?

```let g:qf_auto_open_quickfix = 0```

**Comment by lervag** [comment]
Not sure. I would be glad to consider a pull request :)
