### ISSUE TITLE
Echancement request: Include ability to integrate 'pulp' in latexmk workflow

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1095]
The tool ```pulp``` https://github.com/dmwit/pulp is a smarter way to process latex log files.

It's integration into latexmk is officially supported by John Collins as seen from the readme file from the project's homepage.

Please consider supporting this for ```\lo``` vimtex interface, through a user-dictionary (similar to the config options provided for error parsing, ```pplatex``` vs ```internal```)

**Comment by lervag** [comment]
I've added an initial version of support for pulp. No need to change any latexmk settings, I simply use `pulp` directly to generate the pulp output, which I parse for quickfix info. To test it, make sure you have pulp installed and set

```vim
let g:vimtex_quickfix_method = 'pulp'
```

**Comment by lervag** [comment]
Note: I have to explicitly add errorformat parse strings. The pulp messages are relatively straightforward, but I am sure I am missing stuff (e.g. info messages). Note further that I explicitly ignore _everything_ that I don't parse, which means that the quickfix window will not include things like info messages at the moment.

For me to improve this, I need explicit examples either of LaTeX code that generates the messages that should be parsed, or alternatively a log file (or pulp message).

**Comment by krishnakumarg1984** [comment]
@lervag , thank you for accepting this suggestion. I am working on my thesis, and I shall hopefully be able to provide example of the different messages from the 3 parsers (pplatex, pulp and internal). Is this issue the right forum to provide the examples?

Once again, thank you for the wonderful vimtex plugin and also for the receptive outlook to these type of suggestions from end-users.

**Comment by krishnakumarg1984** [comment]
Hmm, After a quick try things seem to be disappointing with ```pulp```.
The ```pplatex``` project gives me the following
>thesis.tex|| No file thesis.syi.
1_introduction/introduction.tex|78 warning|  Float too large for page by 34.37805pt

Howecer, pulp gives me nothing. In fact,  vimtex just says "compilation completed" and does not open the quickfix window. Manually doing ```:copen``` brings in an empty quickfix window with no entries

**Comment by lervag** [comment]
> Is this issue the right forum to provide the examples?

Yes, for now it is.

> Howecer, pulp gives me a very verbose 308 line output

So, this is where I have to ask you to be specific. Please create a short/minimal example where the pulp output is not as expected.
