### ISSUE TITLE
Question/discussion: Why isn't vimtex's surrounding's related feature are part of other surroundings related plugins?

### ISSUE THREAD

**Issue by doronbehar** [lervag/vimtex#1096]
Hello @lervag,

First of all I wanted just to make sure you know (and if you don't than allow me to tell you :]) that your plugin is the best piece of art I've encountered in among the vim-plugins I know, so thanks for sharing it with us!

After a long time I wasn't sure why isn't there any `ys<text-object>*` normal mode mappings for creating an environment/command in `vimtex`, I've encountered what was written under the tag [`vimtex-faq-surround`](https://github.com/lervag/vimtex/blob/33d096af3e2fd14763f7bbea6219197dff749cbe/doc/vimtex.txt#L3127) in `vimtex`'s help file and it was great news for me to find out the `ys*` commands can be created so easily through ['vim-surround`](https://github.com/tpope/vim-surround).

I was just wondering, shouldn't these commands (**along with `{d,c,t}s{e,c,$,d}`**) be integrated in [`vim-surround`](https://github.com/tpope/vim-surround)? Have you tried to contact @tpope about it or make a PR? I couldn't find any sign of it when I searched his repo for anything related to `tex`. Is the reason you haven't done so is to allow you to keep it under your full control?

The main reason I'm asking this is that from what I understand, the native commands (`{d,c,t}s{e,c,$,d}`) are just different implementations of what most of `vim-sorround`'s default mappings do, just with Tex specific regular expressions.

Oh and BTW, in this sense, isn't `<plug>(vimtex-cmd-create)` (mapped to `<F7>`) unnecessary if one is using [`vim-surround`](https://github.com/tpope/vim-surround) with the suggested `b:surround_*` variables:
```vim
let b:surround_{char2nr('e')}
    \ = "\\begin{\1environment: \1}\n\t\r\n\\end{\1\1}"
let b:surround_{char2nr('c')} = "\\\1command: \1{\r}"
```
?

My opinion in this subject is that all of the commands related to Tex delimiters and Tex environments/commands (including `{d,c,t}s{e,c,$,d}`) should be provided by [`vim-surround`](https://github.com/tpope/vim-surround) exclusivly and even putting the `b:surround_` variables part of the official `vimtex` won't heart anyone even if he doesn't use [`vim-surround`](https://github.com/tpope/vim-surround). IMO, all related surrounding's features should be part of [`vimtex`'s non-features](https://github.com/lervag/vimtex/blob/33d096af3e2fd14763f7bbea6219197dff749cbe/doc/vimtex.txt#L158).

In regard to this subject, I've read as well what you wrote about [integration with `vim-sandwich`](https://github.com/lervag/vimtex/blob/33d096af3e2fd14763f7bbea6219197dff749cbe/doc/vimtex.txt#L216) and I guess his approach is much more generalized and interesting but I haven't dived in to this yet. Besides, it doesn't matter for the discussion whether you choose ([`vim-surround`](https://github.com/tpope/vim-surround) or [`vim-sandwich`](https://github.com/machakann/vim-sandwich))

**Comment by lervag** [comment]
> First of all I wanted just to make sure you know (and if you don't than allow me to tell you :]) that your plugin is the best piece of art I've encountered in among the vim-plugins I know, so thanks for sharing it with us!

Thanks! <3

----

> IMO, all related surrounding's features should be part of vimtex's non-features.

You are raising an interesting topic in which I have made some inconsistent choices. However, I find the choices to be pragmatic in the sense that it provides the features I need and use myself that I was not able to get from other plugins. I do think vim-sandwich is pretty much complete and could be referred to as the go-to plugin. However, I think it would be unwise to change this in vimtex now, as I expect a lot of people rely on these mappings and will be dissappointed if I were to remove the mappings and force people to use vim-sandwich.

If someone were to suggest a simple and short description of how to use vim-sandwich to fully replace the corresponding mappings in vimtex, then I might reconsider, but for me this is more hazzle than it is worth the effort.

Note that vim-surround can not provide all the surround-like features from vimtex. In particular, it can't detect inline math properly, and it can't detect the various math delimiter structures.

----

> Oh and BTW, in this sense, isn't <plug>(vimtex-cmd-create) (mapped to <F7>) unnecessary if one is using vim-surround with the suggested b:surround_* variables:

Yes. I think the same

**Comment by tpope** [comment]
For the record, I think it is entirely appropriate that vimtex maintain it's own surround.vim like maps. I do something similar in [my vim-sexp extension](https://github.com/tpope/vim-sexp-mappings-for-regular-people). It would also be reasonable to assign `b:surround_` variables, as I've done in [ragtag.vim](https://github.com/tpope/vim-ragtag) among other plugins.

**Comment by lervag** [comment]
Thanks for pitching in, @tpope. I've chosen to not add the `b:surround_` variables because I want users to know what they are doing. Also, I don't want vimtex to in any way add mappings without having an option to not add the map. This is handled pretty well now, but it would be difficult to prevent the vim-surround maps if I added the `b:surround` vars without adding an option for it.

See also #936 for a relevant discussion.

**Comment by doronbehar** [comment]
Thinking about the discussions here and in #936, I'm trying to imagine an ideal relationship between the different plugins. I think the approach made by [`vim-airline`](https://github.com/vim-airline/vim-airline) to this matter of collaboration is the most pragmatic and useful one I've seen taken by a Vim plugin. I think [`vim-surround`](https://github.com/tpope/vim-surround) and [`vim-sandwich`](https://github.com/machakann/vim-sandwich) should consider adopt such an approach, allow me to explain:

[`vim-airline`](https://github.com/vim-airline/vim-airline) has extensions which are configured under his tree under [`autoload/airline/extensions`](https://github.com/vim-airline/vim-airline/tree/master/autoload/airline/extensions). [`vim-airline`](https://github.com/vim-airline/vim-airline) has many built-in extensions, for example: [`fugitiveline.vim`](https://github.com/vim-airline/vim-airline/tree/master/autoload/airline/extensions), [`vimtex.vim`](https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/extensions/vimtex.vim) and [`ale.vim`](https://github.com/vim-airline/vim-airline/blob/master/autoload/airline/extensions/ale.vim) (to name just a few..).

[`vim-airline`](https://github.com/vim-airline/vim-airline)'s various extensions are fully explained in it's [help file](https://github.com/vim-airline/vim-airline/blob/2ba64a88fd20c35f65a3c85882fe40444208d858/doc/airline.txt#L328).

When someone doesn't want to merge his own extensions to upstream [`vim-airline`](https://github.com/vim-airline/vim-airline), he can put under his plugin tree (under `<myplugin-root-repo>/autoload/airline/extensions/myextension.vim`) an extension he'll maintain by himself. These extensions are loaded by default by [`vim-airline`](https://github.com/vim-airline/vim-airline) (unless [`let g:airline#extensions#disable_rtp_load = 1`](https://github.com/vim-airline/vim-airline/blob/2ba64a88fd20c35f65a3c85882fe40444208d858/doc/airline.txt#L333) is set).

My claim is that our discussed surroundings plugins could divide their built-in functionality into extensions as well such as (for [`vim-surround`](https://github.com/tpope/vim-surround)):

- `autoload/surround/extensions/xml.vim` (should be useful for HTML editing as well)
- `autoload/surround/extensions/brackets.vim` (should be useful for any filetype)
- `autoload/surround/extensions/quotes.vim` (should be useful for any filetype)

Or for [`vim-sandwich`](https://github.com/machakann/vim-sandwich):

- `autoload/sandwich/extensions/xml.vim` (should be useful for HTML editing as well)
- `autoload/sandwich/extensions/brackets.vim` (should be useful for any filetype)
- `autoload/sandwich/extensions/quotes.vim` (should be useful for any filetype)
- `autoload/sandwich/extensions/tex.vim` (could replace [`vim-sandwich`](https://github.com/machakann/vim-sandwich)'s existing [tex `macro`](https://github.com/machakann/vim-sandwich/tree/master/macros/sandwich/ftplugin))

Besides completely changing the code structure, the extensions could be enabled and configured with theses kind of variables:

```vim
let g:surround#extensions#<ext>#enabled = 1
let g:surround#extensions#<ext>#other_opts = " ..
" or for sandwich:
let g:sandwich#extensions#<ext>#enabled = 1
let g:sandwich#extensions#<ext>#other_opts = " ..
```

This way, whether users are using [`vim-surround`](https://github.com/tpope/vim-surround) or [`vim-sandwich`](https://github.com/machakann/vim-sandwich), they will be able to choose between using `vimtex`'s 'third party' surroundings extensions for [`vim-surround`](https://github.com/tpope/vim-surround) or [`vim-sandwich`](https://github.com/machakann/vim-sandwich).

The point of having such a relationship between the plugins is that no functionality is implemented twice and everybody use functions which already exist in other functions populated in `autoload/` files.

**Comment by lervag** [comment]
I agree this sounds like a reasonable and smart way to manage extensions. I propose that you open issues with vim-surround and vim-sandwich and propose it there. It seems off topic here.

If there were to be such features for extensions, then I could agree to add extension code to the vimtex repo.
