### ISSUE TITLE
support for \mint{lang}|...| and \mintinline{lang}|...| ?

### ISSUE THREAD

**Issue by douglasgscofield** [lervag/vimtex#1098]
Thanks for language-specific syntax highlighting within minted and custom minted blocks!  Perhaps I've missed something, but I couldn't find support for the single-line environments surrounded by custom delimiters, like \verb with || // {} etc.

```latex
    \mint[showspaces]{perl}|say "this is line $."|   % a single line on its own

    In Perl, \mintinline[showspaces]{perl}|foreach my $a| begins % inline formatting
```

These also have custom environments like the *code ones with \begin and \end:

```latex
    \newmint{perl}{showspaces}
    \newmintinline{perl}{showspaces}
```

provides

```latex
    \perl|say "this is line $."|   % a single line on its own

    In Perl, \perlinline|foreach my $a| begins % inline formatting
```

Is this available?  At the least, it would be nice to switch out of tex mode within these environments, the liberal use of `$` in Perl, bash etc kind of messes things up.

**Comment by douglasgscofield** [comment]
Following the minted documentation (<http://tug.ctan.org/macros/latex/contrib/minted/minted.pdf>, §3.3, pp 7-8 for \mint and \mintinline, and §6, pp 30 for \newmint and \newmintinline.

Yes, they are both a single line.  \mint formats a single line of non-inlined code, and \mintinline formats inline code.  The second delimiter is the same as the first, similar to \verb, except one can also use matched curly braces so long as the fragment does not contain curly braces itself, *but only with \mint and \mintinline*.  I learned putting together the example document that curly braces do not work with the custom macros.

```latex
\documentclass[12pt]{article}
\usepackage[a4paper]{geometry}
\setlength{\parindent}{0pt}

\usepackage{minted}

\newmint{perl}{}   % by default, defines the macro to be the language name: \perl|...|
\newmint[perlwithspaces]{perl}{showspaces}  % defines the macro to be perlwithspaces: \perlwithspaces|...|
\newmintinline{perl}{} % by default, defines the macro to be the language name + inline
\newmintinline[perlinlinewithspaces]{perl}{showspaces}

\begin{document}

A single line using curly braces as delimiters: \mint{perl}{my $var = 1;}

A single line showing spaces, using an option and vertical bars as delimiters: \mint[showspaces]{perl}|my @arr = qw/a b c/;|

This perl fragment uses mintinline and curly-brace deliminters to show \mintinline{perl}{my $var = 1;}.

This fragment also uses mintinline plus an option and vertical-bar delimiters to show spaces: \mintinline[showspaces]{perl}|my @arr = qw/a b c/;|.

Now, defining a custom newmint macro.  The line rendered using \verb|\perl| is \perl|my $var = 1;| and the line rendered using \verb|\perlwithspaces| is \perlwithspaces|my $var = 1;|

And finally, defining custom inline macros.

This one is the custom \verb|\perlinline|: \perlinline/my $var = 1;/

And this one is the custom \verb|\perlinlinewithspaces|: \perlinlinewithspaces|my @arr = qw/a b c/;|.

\end{document}
```

It would make sense to be required to specify these custom macros in the dictionary alongside the environments, something like:

```
...
    \ {
    \   'lang' : 'perl',
    \   'singleline' : ['perl', 'perlwithspaces'],
    \   'inline' : ['perlinline','perlinlinewithspaces'],
    \   'environments' : ['perlcode'],
    \ }

...
```

**Comment by lervag** [comment]
Sorry for taking so long! I've implemented an initial support for this. You can test it with these settings:

```vim
let g:vimtex_syntax_minted = [
    \ {
    \   'lang' : 'perl',
    \   'commands' : ['perl', 'perlwithspaces', 'perlinline', 'perlinlinewithspaces'],
    \   'environments' : ['perlcode'],
    \ }]
```

**Comment by lervag** [comment]
I'll update the docs after this has been tested by more than myself.

**Comment by douglasgscofield** [comment]
This seems to work very well, thank you!

However I now have another issue that may not be related.  I use subfiles, and have broken up one of the chapter subfiles into separate files for sections and loading each section using `\include{}` within the `\documentclass[main.tex]{subfiles}`-wrapped chapter.  This will not be my final configuration for the chapter but it works for now.

VimTex now (and not before `:PluginUpdate`) gives an error that appears to occur while looking for latexmain. There is a `main.tex.latexmain` in the same directory.  Loads of other `.tex` files seem to work fine.

The same error occurs if I load the `subfiles`-d chapter (with no error), then load the `\include`-d file in a separate tab.  The same error occurs if I load any of the `\include`-d files, but not if I load any of the other `.tex` or `.bib` files in the project.

Should I open another issue for this?

~~~~
Error detected while processing function vimtex#init[4]..<SNR>61_init_state[1]..vimtex#state#init[1]..<SNR>72_get_main[39]..<SNR>72_get_main_latexmain[3]..<SNR>72_file_reaches_current:
line    4:
E341: Internal error: lalloc(0, )
~~~~

My MacVim is `Custom Version 8.1.72 (149)`.

**Comment by lervag** [comment]
Yes, please open a new issue for this. I recently made some changes that might probably have resulted in this issue, but it is not clear from your description what the problem is.

If you are able to parse a minimal example for how to reproduce the problem, that would be very helpful!

**Comment by naibaf0** [comment]
Works great for me as well, thank you!

**Comment by lervag** [comment]
No problem :)
