### ISSUE TITLE
FAQ for yse/ysc mappings for sandwich.vim

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1100]
From what I understand from the documentation as well as your dotvim files, it looks like sandwich.vim is preferred to surround.vim (or atleast an equally preferable alternative).

The FAQ provides info for yse/ysc mappings for surround.vim 
>Q: |vimtex| provides `dse`, `dsc`, `cse`, and `csc`.  These seem to be inspired by
   |surround.vim|.  Does |vimtex| also provide the corresponding `yse` and `ysc`?
A: The mentioned mappings are indeed inspired by |surround.vim|.  However,
   |vimtex| does not provide `ys<text-object>e` and `ys<text-object>c`.  If you use
   |surround.vim|, then the asked for mappings may be easily added if one adds
   the following lines to `~/.vim/after/ftplugin/tex.vim` or any other
   `ftplugin/tex.vim` in your |runtimepath|: >
>
> let b:surround_{char2nr('e')}
      \ = "\\begin{\1environment: \1}\n\t\r\n\\end{\1\1}"
  let b:surround_{char2nr('c')} = "\\\1command: \1{\r}"

Can you consider provide similar documentation for sandwich.vim ?

**Comment by lervag** [comment]
Yes, that sounds fair. The only thing is that vim-sandwich is more "cumbersome" to configure manually, and if you allow/enable the LaTeX mappings that ship with it, it already provides the said mappings.

Do you have a suggestion for what to write?

**Comment by lervag** [comment]
Ok, I've added a comment that I think should suffice.

Note: I think it is worth the effort to learn sandwich; it has more powerful surroundings such as functions, interactive surroundings and similar. At least, I find this to be well worth the inconvenient amount of configuration.

**Comment by krishnakumarg1984** [comment]
Thank you Lervag.  Being a non-computer programmer in the sciences, I am already finding vim hard. I think I shall slowly get there.

**Comment by lervag** [comment]
No problem, happy to be of any help. I think the best strategy for learning Vim is to take it slow. :)
