### ISSUE TITLE
VimtexClean fails

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#1102]
# Explain the issue
Trying to run `:VimtexClean` fails on my Windows 10 installation, currently. I've tested using a minimal vimrc and LaTeX file. The error output resembles the screenshot below.

![error](https://user-images.githubusercontent.com/6321578/38589065-ff1a2abc-3cf6-11e8-87a4-977ecd9a1eb1.jpg)

Using the stacktrace in the above screenshot I've traced the source of the error to a [line in `process.vim`](https://github.com/lervag/vimtex/blob/a07cd40cecd339d5a89376d055e96e148a3e0ef2/autoload/vimtex/process.vim#L103). I played around with the `self.prepared_cmd` string and managed to get it to work after a while. The key was to remove the [`start /b`](https://github.com/lervag/vimtex/blob/a07cd40cecd339d5a89376d055e96e148a3e0ef2/autoload/vimtex/process.vim#L159) line from process.vim. This is a poor solution given that this very line is what is supposed to implement background execution. There is almost definitely a better solution, but there is seemingly no proper placement of quotes and spaces which allows this to work.

I've submitted PR #1103 for this.

**Comment by lervag** [comment]
We'll continue this discussion in #1103.
