### ISSUE TITLE
No quickfix feedback with neovim

### ISSUE THREAD

**Issue by rbnvrw** [lervag/vimtex#1105]
# No quickfix feedback with neovim

I am using Neovim, and I'm unable to get build messages in the quickfix window.

1. A minimal `vimrc` file:

    ```vim
    set nocompatible
    let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
    let &rtp .= ',~/.vim/bundle/vimtex/after'

    let g:vimtex_compiler_latexmk = {
    \ 'backend' : 'nvim',
    \ 'background' : 1,
    \ 'build_dir' : '',
    \ 'callback' : 1,
    \ 'continuous' : 1,
    \ 'executable' : 'latexmk',
    \ 'options' : [
    \   '-pdf',
    \   '-pdflatex="xelatex -synctex=1 \%S \%O"',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}
    ```

2. A minimal `.tex` file:

    ```tex
    \documentclass{minimal}
    \begin{document}

    Hello World!

    \end{document}
    ```

3. Description of the problem:

In the documentation of vimtex, it says that I have to pass a `--servername` to vim so it latexmk knows where to post the callback. However, neovim does not have this option, and therefore I'm not sure how to make this work. This issue might be of interest: https://github.com/tpope/vim-dispatch/issues/163

**Comment by clason** [comment]
Neovim doesn't have the `--servername` option yet, you have to use the `nvr` wrapper from https://github.com/mhinz/neovim-remote. With this, using 

    let g:vimtex_compiler_progname = 'nvr' 

in your `init.vim` should suffice in place of your options (which are deprecated in any case, if I recall correctly -- always make sure you use the current version of the plugin).

**Comment by lervag** [comment]
Hi @rbnvrw,

First, you can simplify your options to

```vim
let g:vimtex_compiler_latexmk = {
\ 'options' : [
\   '-pdf',
\   '-pdflatex="xelatex -synctex=1 \%S \%O"',
\   '-verbose',
\   '-file-line-error',
\   '-synctex=1',
\   '-interaction=nonstopmode',
\ ],
\}
```

And even remove that option alltogether if you specify the `pdflatex` option in your `.latexmkrc` file, in which case the defaults should work for you.

However, as @clason says, to use neovim, you need to `let g:vimtex_compiler_progname = 'nvr'` and install `neovim-remote`. This can be done either with `pip install neovim-remote` or through your package manager (depending on which OS/distribution you are on).

You can read about this in the first paragraph of `:h vimtex-requirements`, which links further to `:h vimtex-faq-neovim`.

**Comment by clason** [comment]
No problem! I think it can be useful since it is (slightly) more visible than the `h: vimtex` (which apparently too few people look at). Would it make sense to add a brief link to the FAQ entry in the README.md (e.g., either to Installation or Quickstart the sentence `Vimtex supports Neovim; see the [FAQ entry](link) for the configuration).`)?

**Comment by lervag** [comment]
Yes, that would be useful. I'll add that now.

**Comment by rbnvrw** [comment]
@lervag and @clason Thank you for the help. I did read the `:h vimtex-requirements` but apparently skipped right to the last part and missed the neovim wiki. My apologies and thank you for the hard work! :+1:

**Comment by lervag** [comment]
I can relate to the "information overload" for new users, and so no problem. No reason to apologize. And thanks! :)
