### ISSUE TITLE
Add Table of Figures/Tables

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#1106]
Cf. #1085.

Note: The direction is now going to "Table of Contents/TODOs/Labels/Figures/Tables", i.e. 5 different things. I'm thinking we should change the default mappings to make all of these lists more available. Perhaps something like a choice menu? I would be happy to get some ideas/suggestions/comments on this.

**Comment by clason** [comment]
Would a three-letter mapping be possible: `<leader>lt[cdlft]`?

**Comment by lervag** [comment]
Yes, I think it could. I also think it could be nice with a mini-menu for assisting with the final letter. That is, mapping `<localleader>lt` to a function that displays a menu and asks for the final letter. Perhaps, if possible, only showing the menu if there is a short delay.

Note: It goes without saying that I will add `<plug>` mappings for all the various commands for those who want that, which would allow to keep the old behaviour if desired.

**Comment by lervag** [comment]
I've opened a pull request that should address this issue, and as such, I am closing this now.
