### ISSUE TITLE
Cannot compile xelatex + minted

### ISSUE THREAD

**Issue by diwww** [lervag/vimtex#1108]
There is a problem with compiling tex files which contain minted code snippets since minted requires `--shell-escape` flag.

I know that `g:vimtex_latexmk_options` is now deprecated and that `g:vimtex_compiler_latexmk` has a priority over `.latexmkrc` settings. Therefore I decided to set this flag in my vimrc.

My minimal `vimrc` file:
```vim
let g:vimtex_view_method='mupdf'
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-pdf',
    \   '-pdflatex="xelatex --shell-escape \%O \%S"',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ]
    \}
```

Output from VimtexCompileSS:
```
HSE-theme/beamerthemeHSE.sty|14 error| Package minted Error: You must invoke LaTeX with the -shell-escape flag.
example-beamer-HSE.tex|| LaTeX Warning: You have requested package `HSE-theme/beamerthemeHSE',
example-beamer-HSE.tex|31 warning| Package hyperref Warning: Token not allowed in a PDF string (Unicode):
example-beamer-HSE.tex|31 warning| Package hyperref Warning: Token not allowed in a PDF string (Unicode):
example-beamer-HSE.tex|31 warning| Package hyperref Warning: Token not allowed in a PDF string (Unicode):
example-beamer-HSE.tex|31 warning| Package hyperref Warning: Token not allowed in a PDF string (Unicode):
example-beamer-HSE.tex|35 error| Package minted Error: You must have `pygmentize' installed to use this package.
example-beamer-HSE.tex|77 warning| Overfull \hbox (30.73085pt too wide) in paragraph at lines 77--77
example-beamer-HSE.vrb|31 error| Package minted Error: Missing Pygments output; \inputminted was
example-beamer-HSE.vrb|31 error| Package minted Error: Missing Pygments output; \inputminted was
example-beamer-HSE.vrb|31 error| Package minted Error: Missing Pygments output; \inputminted was
```

Also `latexmk -pdf -pdflatex="xelatex --shell-escape %O %S" mytexfile.tex` runs without any error.

What is a correct way to pass `--shell-escape` option to latexmk options?

**Comment by lervag** [comment]
I think a better solution is to set `-pdflatex` in your `.latexmkrc` file. Then you don't need to change any vimtex setting. E.g.:

```perl
$pdflatex = 'xelatex --shell-escape %O %S'
```

I also think that it should not be necessary to escape the `%`s in the option. Does it work from vimtex if you change to the following?

```vim
    \   '-pdflatex="xelatex --shell-escape %O %S"',
```

**Comment by diwww** [comment]
Both options don't work.

If I create local .latexmkrc file with the following content and run `latexmk mytexfile.tex` everything works ok, but VimtexCompileSS produces the same error.
```
$pdf_mode=1;
$pdflatex="xelatex --shell-escape %O %S";
```

I think this is because:
```
  options~
    This is a list of options that are passed to `latexmk`. The default
    options should work well for most people.

    Note: Options may also be specified indirectly to `latexmk` through both
          a global and a project specific `.latexmkrc` file. One should know,
          though, that options specified on the command line has priority, and
          so if one wants to override one of the above default options, then
          one has to set this key to a list that contains the desired options.
```

"options specified on the command line has priority" -- does this mean that the only way to pass options to latexmk is to write them to `" g:vimtex_compiler_latexmk` in my vimrc?

```
\   '-pdflatex="xelatex --shell-escape %O %S"',
```
has no effect too.

**Comment by pRot0ta1p** [comment]
you need install python and install pygmentize using pip. If you are using anaconda, make sure you add anaconda to the PATH vatiable.

**Comment by lervag** [comment]
Thanks @pRot0ta1p, based on the initial info given by @diwww, it seems you might be right that this is the problem.

**Comment by xyzsam** [comment]
What is the recommended way to solve this problem with latexrun? Currently, I have a local .`lvimrc` file at the root of my project directory, where I've set g:vimtex_compiler_latexrun like so:

```vim
let g:vimtex_compiler_latexrun = { 
        \ 'background' : 1,
        \ 'build_dir' : 'latex.out',
        \ 'options' : [ 
        \   '--verbose-cmds',
        \   '--latex-cmd="xelatex"',
        \   '--latex-args="-shell-escape"',
        \ ],
        \}
```

If I start vim from the top of my project directory and compile with vimtex, it works fine, but only if I start vim from the top. But I use [vim-localrc](https://github.com/embear/vim-localvimrc) to ensure that it gets loaded no matter where I start vim, and I can verify this behavior by adding `echo "Hello World"` to the local vimrc and seeing that it does get printed when I open a file from a non-root directory. 

Here's what the log file says when I do this from the non-root directory:

```bash
thesis.tex:51: error: [minted] You must invoke LaTeX with the -shell-escape flag
      at \usepackage{siunitx}
thesis.tex:93: error: [minted] You must have `pygmentize' installed to use this package
      at \begin{document}
```

minimal global .vimrc:

```vim
execute pathogen#infect()
Helptags
filetype plugin indent on

let maplocalleader = "\\"
let g:tex_flavor = 'latex'
let g:vimtex_compiler_method="latexrun"
set exrc
let g:localvimrc_name = ".lvimrc"
let g:localvimrc_whitelist = "thesis/.lvimrc"
```
Apart from this issue, vimtex works great for me.

**Comment by lervag** [comment]
@xyzsam You are describing an issue that is clearly related to another plugin, but you are not describing the essential steps I should do to reproduce.

I would kindly ask that you open a new issue for this where you describe the exact steps I should do to reproduce your problem. This includes a minimal vimrc file, a minimal "local" vimrc file, and a minimal LaTeX example.

I also take the liberty of closing this issue, as there has been no other relevant activity for some time.

**Comment by nadya-p** [comment]
> you need install python and install pygmentize using pip. If you are using anaconda, make sure you add anaconda to the PATH vatiable.

    conda install pygments

Otherwise
```
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-pdf',
    \   '-pdflatex="xelatex --shell-escape %O %S"',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ]
    \}
```
works fine for me as well.
