### ISSUE TITLE
No file autocompletions for \subfile

### ISSUE THREAD

**Issue by fedeDev** [lervag/vimtex#1109]
First off, let me say that I use this plugin a lot and I think it is an great example of a vim plugin done right. Thanks a lot for your amazing work! 

I am currently autocompleting using deoplete. Everything seems to work as expected, however when I try to add a ```subfile``` using the ```\subfile{|}``` command, I do not get autocompletions automatically populated with the ```[input/include]``` suggestions (as it happens on ```\include{|}```, for example). Is this the intended behavior?

I can fix this by adding ```|subfile``` to 
https://github.com/lervag/vimtex/blob/a7fc6f62e8234fc0696cfe4325153e922e2fddd5/autoload/vimtex/re.vim#L45
such that it triggers  ```[input/include]``` on ```\subfile{|}```.

I think this is a simple fix so I didn't fill in the complete issue template, if need be I can give the complete details.

**Comment by lervag** [comment]
Thanks for noticing! I've updated and fixed.

Also, thanks for kind words!

**Comment by fedeDev** [comment]
Thanks! That was some impressive reaction time, less than 8 minutes and I can confirm the fix is working on my end.

**Comment by lervag** [comment]
Yeah, I was in the right place at the right time, and the issue was well described and simple to fix. :)
