### ISSUE TITLE
Completion after recent deoplete changes in omni options

### ISSUE THREAD

**Issue by petobens** [lervag/vimtex#1110]
Recently @Shougo changed deoplete's omni settings ([see here](https://github.com/Shougo/deoplete.nvim/issues/682)). After that change I cannot get deoplte to play nicely/work with vimtex's omni function:
i) my minimal nvim `init.vim` file is:
```vim
set nocompatible

let $DOTVIM = expand('$HOME/.vim')

set runtimepath+=$DOTVIM/bundle/repos/github.com/Shougo/deoplete.nvim
set runtimepath+=$DOTVIM/bundle/repos/github.com/lervag/vimtex
filetype plugin indent on

let g:deoplete#enable_at_startup = 1
call deoplete#custom#option('sources', {
\ 'tex' : ['buffer', 'dictionary', 'file', 'omni']
\})
call deoplete#custom#source('omni', 'input_patterns', {
            \ 'tex' : '\\(?:'
                \ .  '\w*cite\w*(?:\s*\[[^]]*\]){0,2}\s*{[^}]*'
                \ . '|includegraphics\*?(?:\s*\[[^]]*\]){0,2}\s*\{[^}]*'
                \ . '|(?:include(?:only)?|input)\s*\{[^}]*'
                \ . '|usepackage(\s*\[[^]]*\])?\s*\{[^}]*'
                \ . '|documentclass(\s*\[[^]]*\])?\s*\{[^}]*'
                \ . '|\w*'
                \ .')',
                \}
                \)
```
ii) I have a `foo.tex` like
```tex
\documentclass{article}
\usepackage{|

\begin{document}

Foo bar baz

\end{document}
```
If I place the cursor at `|` (i.e after the usepackage braces there is no completion (whereas if i press `C-x C-o` i do get omnicompletion. Any ideas?
Thanks in advance

**Comment by petobens** [comment]
Btw (and beyond this plugin scope) I use to have dictionary completion with
```
let tex_buffer_patterns = {'tex' : '[a-zA-Z_]\w{2,}:\S+'}
let tex_dict_patterns = {'tex' : '\\?[a-zA-Z_]\w*'}
    call deoplete#custom#source('buffer', 'keyword_patterns',
            \ tex_buffer_patterns)
    call deoplete#custom#source('dictionary', 'keyword_patterns',
            \ tex_dict_patterns)
```
however this is also not longer working.

**Comment by Shougo** [comment]
@petobens Please use `call deoplete#custom#var()` instead.

```vim
call deoplete#custom#var('omni', 'input_patterns', {
            \ 'tex' : '\\(?:'
                \ .  '\w*cite\w*(?:\s*\[[^]]*\]){0,2}\s*{[^}]*'
                \ . '|includegraphics\*?(?:\s*\[[^]]*\]){0,2}\s*\{[^}]*'
                \ . '|(?:include(?:only)?|input)\s*\{[^}]*'
                \ . '|usepackage(\s*\[[^]]*\])?\s*\{[^}]*'
                \ . '|documentclass(\s*\[[^]]*\])?\s*\{[^}]*'
                \ . '|\w*'
                \ .')',
                \}
                \)
```

**Comment by lervag** [comment]
Thanks for helping out, @Shougo! A couple of questions:

- Should we use `deoplete#custom#var` also for similar things? For instance,

    ```vim
    call deoplete#custom#var('buffer', 'keyword_patterns',
            \ tex_buffer_patterns)
    call deoplete#custom#var('dictionary', 'keyword_patterns',
            \ tex_dict_patterns)
    ```
- When adding a complex input pattern (like this one for `tex` files), where
  there are several branches: Do you have an idea if it is better to split the
  branches and supply a list for deoplete, or is it OK to provide it as a long
  string as here?

**Comment by Shougo** [comment]
> Should we use deoplete#custom#var also for similar things? For instance,

`deoplete#custom#var()` is for source specific options.
buffer and dictionary source don't have the options.

> When adding a complex input pattern (like this one for tex files), where
there are several branches: Do you have an idea if it is better to split the
branches and supply a list for deoplete, or is it OK to provide it as a long
string as here?

I think it is better.

```vim
let s:patterns = {}
let s:patterns.tex = 'some pattern'
call deoplete#custom#var('omni', 'input_patterns', s:patterns)
```

**Comment by lervag** [comment]
> I think it is better.

Ok, perhaps my question was unclear. Do you have an opinion on which of these are better?

```
let s:patterns = {}
" Either this:
let s:patterns.tex = '\(pattern1\|pattern2\)'

" Or this:
let s:patterns.tex = ['pattern1', 'pattern2']

call deoplete#custom#var('omni', 'input_patterns', s:patterns)
```

**Comment by Shougo** [comment]
Yes.

**Comment by lervag** [comment]
Ok, so: `deoplete#custom#var` sets variables in a source, such as `input_patterns` for the `omni` source, while `deoplete#custom#source` sets source specific options, such as `rank` or `mark`?

**Comment by Shougo** [comment]
Yes.

`deoplete#custom#source()` options are in `deoplete-source-attributes`.

Note: It is same with denite.

**Comment by lervag** [comment]
Great! It makes sense. Thank you!

**Comment by lervag** [comment]
@petobens I can only assume that this thread solves your issue. Btw, you can also use the `g:vimtex#re#deoplete` variable for the input pattern, which I try to keep updated for the various kinds of omni completion in vimtex:

```vim
call deoplete#custom#var('omni', 'input_patterns', {
      \ 'tex' : g:vimtex#re#deoplete,
      \})
```

**Comment by petobens** [comment]
@Shougo changing to `var` worked. Note that the docs seem to be wrong: https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L553

Sorry @lervag for polluting this issue tracker and thanks for pointing towards the regex variable.

I have one more question (probably stil directed to Shougo)
> buffer and dictionary source don't have keyword_patterns options.
@Shougo I want to set specific patterns for dictionary and buffer source.  How can I achieve this? I tried the following which doesn't work.
```
let tex_buffer_patterns = {'tex' : '[a-zA-Z_]\w{2,}:\S+'}
let tex_dict_patterns = {'tex' : '\\?[a-zA-Z_]\w*'}
call deoplete#custom#source('buffer', 'keyword_patterns', tex_buffer_patterns)
call deoplete#custom#source('dictionary', 'keyword_patterns', tex_dict_patterns)
```

**Comment by petobens** [comment]
@lervag do you see some flickering when completing citations?

![apr-19-2018 10-04-57](https://user-images.githubusercontent.com/2583971/38993132-24692a5c-43b9-11e8-86f1-84252b07760b.gif)

**Comment by lervag** [comment]
No, I don't see such flickering. Is it Vim or neovim?

**Comment by lervag** [comment]
Sorry, I see you specified that initially. But as I said, I don't have this issue...

**Comment by petobens** [comment]
Ok thanks!!
