### ISSUE TITLE
Automatically compile Asymptote

### ISSUE THREAD

**Issue by skitimoon** [lervag/vimtex#1113]
I make a figure in Asymptote and I have to compile it myself by:
`asy myfile-*.asy`
so the main file can include the image properly.

Is there a way to check the `\usepackage{asymptote}` and compile it automatically?

**Comment by lervag** [comment]
Hi!

See [here](http://asymptote.sourceforge.net/doc/LaTeX-usage.html), and in particular note:


> An even better method for processing a LaTeX file with embedded Asymptote code is to use the latexmk utility from
>
>     http://mirror.ctan.org/support/latexmk/
>
> after putting the contents of [this file](http://sourceforge.net/p/asymptote/code/HEAD/tree/trunk/asymptote/doc/latexmkrc) in a file latexmkrc in the same directory. The command
>
>     latexmk -pdf latexusage
>
> will then call Asymptote automatically, recompiling only the figures that have changed.

Vimtex uses `latexmk` in the background (by default), so if you follow this guide you should get the desired behaviour.

Note, it seems the referred `latexmkrc` file is not available. Instead, I found it [here](https://github.com/vectorgraphics/asymptote/blob/master/doc/latexmkrc).

See also [here](https://tex.stackexchange.com/questions/258103/latexmk-and-the-location-of-asymptotes-generated-files) for a related SO question.
