### ISSUE TITLE
TOC position

### ISSUE THREAD

**Issue by petobens** [lervag/vimtex#1116]
Hi @lervag . Two small questions that I couldn't answer by reading the docs. 

i) How do I place the TOC always as the very left window? If I have to split windows (with a tex file on the right) and I run that opens the toc then the window is opened immediately to the left of that tex file (I want for it to be always fixed at the furthermost left):
<img width="2880" alt="screen shot 2018-05-07 at 13 58 56" src="https://user-images.githubusercontent.com/2583971/39716473-db5ab3ec-5206-11e8-9d68-f642906a1341.png">

ii) Now imagine that I have the same tex file opened in a vertical split (I.e 2 windows with the same file). If I open the toc from the right tex file and press enter on one of the entries then the cursor jumps to the corresponding section on the left tex file window. I expect it to jump in the same file shown on the window where the toc command was actually called (the right one in this case):
![may-07-2018 14-59-37](https://user-images.githubusercontent.com/2583971/39716675-59589f52-5207-11e8-8434-31f4cb88243b.gif)

Please let me know if you can reproduce these issues. Thanks!

**Comment by lervag** [comment]
1. The TOC is opened as a split window. The position is determined by the `splitbelow` and `splitright` options. You can also use the `g:vimtex_index_split_pos` setting.

2. Yes, I can reproduce this. But is it really an issue? Could you perhaps explain when this scenario would actually be necessary?

**Comment by petobens** [comment]
>The TOC is opened as a split window. The position is determined by the splitbelow and splitright options. You can also use the g:vimtex_index_split_pos setting.

I tried using 
```vim
let g:vimtex_index_split_pos = 'topleft vsplit'
let g:vimtex_index_split_width = 20
```
but despite i get the correct position (always to the far left) I don't get the proper resize

> Yes, I can reproduce this. But is it really an issue? Could you perhaps explain when this scenario would actually be necessary?

Sometimes I have the document opened at two different places (in each split) and I want to jump in one of those split to a specific section. I find it strange that vimtex hijacks my cursor position.

Thanks for the quick reply.

**Comment by lervag** [comment]
I've made a minimal test for this, see `test/issues/1116`.

Note, with this, I can only reproduce that the wrong window is opened. The TOC split is correctly positioned on the leftmost window.

I'm looking into why the wrong window is used.

**Comment by lervag** [comment]
Ok, I think I've fixed at least part of this: When activating a TOC entry you should be returned to the correct window.

As mentioned, I was not able to reproduce the part about where the TOC window is opened. For me, the settings suggested by you ensures that the TOC is opened at the left always.

**Comment by petobens** [comment]
Thanks for the fix!

Regarding the second issue, using:
```
let g:vimtex_index_split_pos = 'topleft vsplit'
let g:vimtex_index_split_width = 10
```
correctly opens the TOC always to the left but without the proper resize. Can you reproduce that part?

**Comment by lervag** [comment]
It works if you use `vert topleft`. It seems one should use `:vert` before the position commands. I'll add a note in the docs.

**Comment by petobens** [comment]
Awesome. Thank you! Feel free to close :)

**Comment by lervag** [comment]
Great :)
