### ISSUE TITLE
How to configure texcount to show wordcount of complete project in status line?

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1118]
I am unsure where to post this support request. tex.StackExchange seems too broad and there not many users of vimtex in vi.stackexchange

I came across [this exchange](https://www.reddit.com/r/neovim/comments/8a6gy6/texcount_word_count_in_statusline_with_lightline/) between @lervag and another user 'lxndrcx' about using vimtex's texcount wrapper to update the statusline with the wordcount.

I have shamelessly stolen  [lxndrcx's configuration for this](https://github.com/lxndrcx/neovim-init.vim/blob/master/init.vim) and it works well.  Thank you!

But, this configuration only shows the current buffer's count in the status line. This is of limited use. In a large project such as a thesis (or even journal papers), the user typically wishes to split the work into multiple files. And in many universities, there is an overall word limit (same for journal papers).  Is there a way to use ```% TEX-root``` directive to dynamically detect the word count of the full project and update the status line accordingly (using either lightline or airline)?

**Comment by lervag** [comment]
I think the problem is that you need to pass some more options to `texcount`. See [here](http://app.uio.no/ifi/texcount/download.php?doc=QuickReference_3_1.pdf) for a quick reference. I think perhaps the missing option is `-inc`.
