### ISSUE TITLE
Custom TOC matcher doesn't work with the refactored parser

### ISSUE THREAD

**Issue by edwardtulane** [lervag/vimtex#1119]
I want to have the introduction of my document inserted without numbering and therefore I am using the `\addchap` command (that is specific to the KOMA classes, I think). To make it appear in the vimtex TOC,
I defined a custom TOC matcher, which was working fine, so far.

After refactoring of the parser code, I get an error that seems to be related to the `l:context` dictionary, but I am not quite sure what to do about that. Maybe you can hardwire parsing of the `\add(part|chap|sec)` commands? I would very much appreciate that! If not, can you give me a hint how I can fix the matcher definition?

This is the error:
```
Error detected while processing function 209[7]..197[5]..vimtex#parser#toc[2]..vimtex#parser#toc#parse:
line   71:
E716: Key not present in Dictionary: get_entry(l:context)
E15: Invalid expression: l:matcher.get_entry(l:context)
Error detected while processing function 209[7]..197[5]..vimtex#parser#toc:
line    5:
E712: Argument of filter() must be a List or Dictionary
Error detected while processing function 209[7]..197:
line   12:
E712: Argument of filter() must be a List or Dictionary
```
Which I get using this minimal `vimrc`
```vim
set nocompatible

filetype plugin indent on

let mapleader=','
let maplocalleader=','

let g:vimtex_toc_custom_matchers = [
            \ { 'title' : 'Introduction',
            \   're' : '\v^\s*\\addchap\{' }
            \]

call plug#begin()
Plug 'lervag/vimtex' ", {'commit': '11ca64c035e4858d79b67f5f696ad223a859941e'}
call plug#end()
```
(the commented commit is the last one that is working for me)
together with this tex file

```tex
\documentclass{scrreprt}

\begin{document}
   \addchap{test}
\end{document}
```
Steps to reproduce: run `vim -u vimrc mwe.tex` and type `,lt`.

Thank you so much!

**Comment by lervag** [comment]
Please try with this code:

```vim
let g:vimtex_toc_custom_matchers = [
        \ { 'title' : 'Introduction',
        \   're' : '\v^\s*\\addchap\{',
        \   'get_entry' : function('vimtex#parser#toc#get_entry_general'),
        \}]
```

In the old code, I allowed an implicit `get_entry` function. This is no longer
allowed. But the general function was private, so I've now made it public, and
I think the above code should work as before.

**Comment by edwardtulane** [comment]
Yes, that does the trick! Thank you!

**Comment by lervag** [comment]
No problem, and sorry for the inconvenience :)
