### ISSUE TITLE
latest commit broke synctex functionality

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#1120]
Please check if commit 548763b93e6180edf9f32be388002620e7e23de3 broke something in `:VimTexview`. Over here, the command worked before the commit (jump to corresponding position in `pdf`), but not afterwards.

**Comment by Konfekt** [comment]
This might have to do with
```
ldd =zathura|grep libsynctex
```
yielding no output, but `zathura` supporting `synctex`. It is version 0.3.6. 

Perhaps better check
```
zathura --help | grep synctex
```
or something alike.

**Comment by Konfekt** [comment]
The output of `ldd =zathura` is (on OpenSUSE 42.3): 
```
	not a dynamic executable
```

**Comment by lervag** [comment]
Yes, sorry. I guessed this wouldn't work perfectly. But I can check the help either, see #1117. I've updated to check for error codes now, and if I can't properly decide I fall back to fate. :)

**Comment by Konfekt** [comment]
Ok, that resolves it for me.
