### ISSUE TITLE
How to check duplicated label/citation key?

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#1123]
Some times, we make a mistake that label two equations or theorem/lemma with the same name, in which case,  `tex` only use the later number as reference. I am just wondering how to check this by setting `g:vimtex_quickfix_latexlog`. Put it in another way, which kind of error of this duplicated labeling belongs to? I know the default value of `g:vimtex_quickfix_latexlog` is given by
```vim
    let g:vimtex_quickfix_latexlog = {
          \ 'default' : 1,
          \ 'general' : 1,
          \ 'references' : 1,
          \ 'overfull' : 1,
          \ 'underfull' : 1,
          \ 'font' : 1,
          \ 'packages' : {
          \   'default' : 1,
          \   'natbib' : 1,
          \   'biblatex' : 1,
          \   'babel' : 1,
          \   'hyperref' : 1,
          \   'scrreprt' : 1,
          \   'fixltx2e' : 1,
          \   'titlesec' : 1,
          \ },
          \}
```
I know that the duplicated citation key can be detected by turn on `biblatex` switch. I hope there are some explanation of `references/default/general` error.

**Comment by lervag** [comment]
I don't understand your problem. I've made a simple example of duplicated label, and the error is displayed when you do `\le`.

**Comment by vanabel** [comment]
I almost get there, I tested that if we set `default:1` and `references:0` then the duplicated labeling warning will popup, if we want to know the undefined label, then we should set `references:1`, the strange thing is that we must set `default:1` also, or the undefined label will not popup.

**Comment by vanabel** [comment]
It is not a big problem, how about let forget it?

**Comment by lervag** [comment]
That's ok by me. But if you want to find a solution, feel free to reopen and provide details necessary for me to understand the issue. :)
