### ISSUE TITLE
Use zathura --synctex-forward instead of xdotool for synctex

### ISSUE THREAD

**Issue by aenda** [lervag/vimtex#1128]
Hello! Thanks for all your hard work on this plugin, I use it all the time. I'm currently using qpdfview as my pdf viewer because of the good synctex support, but I would like to switch to zathura. I currently cannot, however, because I am using a wayland based WM and the xdotool method for forward search does not work. I would like to ask if the synctex-forward option specified by zathura could achieve the same functionality as what is currently done with xdotool. The switch says that it will automatically open a new instance if there is none running for the current file, so it seems like it would meet vimtex's needs, but there may be something I am overlooking. Thank you!

**Comment by lervag** [comment]
> because I am using a wayland based WM

I'm sorry, but Wayland is not fully supported. `xdotool` is used to avoid creating multiple Zathura windows. I think things should work quite well if you set `let g:vimtex_view_forward_search_on_start = 1` in your vimrc file.

I am not using Wayland, and so I will not be working on supporting it myself. Pull requests are welcome, of course.
