### ISSUE TITLE
Question: Compile only subfile

### ISSUE THREAD

**Issue by volkerkarle** [lervag/vimtex#1129]
Hi there,

The subfile package works as expected. Now I would like to compile *only* the Chapter I am working right on (to increase the speed and readability). If I compile externally, it works out, but I would like to use the compilation of vimtex. A typical chapter looks like

```tex
\documentclass[../main.tex]{subfiles}
\begin{document}
\section{Introduction}
text (...)
\end{document}
```

Thanks in advance,
V.

**Comment by lervag** [comment]
See `:h vimtex-subfile`:

> Subfiles package~
>   |vimtex| also supports the `import` and the `subfiles` packages that can be used to
>   make it easier to work with multi-file projects. If one uses the `subfiles`
>   package, the |VimtexToggleMain| command is particularly useful.
>
>     - https://www.ctan.org/pkg/import
>     - https://www.ctan.org/pkg/subfiles
