### ISSUE TITLE
inverse search with vim gui

### ISSUE THREAD

**Issue by meijieru** [lervag/vimtex#1130]
Thanks for your fantastic work first.

It seems to be a reasonable workflow that we have our editor and the pdf viewer on the left/right window respectively. So it's commonly to benefit from a modern gui like [oni](https://github.com/onivim/oni). Everything works well except inverse search. Anyway to solve it or should it be gui's work?

**Comment by lervag** [comment]
Thanks for the kind words :)

I'm not quite sure I understand what you mean. Could you give some more details on the setup you are thinking about, perhaps some screenshots, and a more clear explanation of what is not working and why?

My understanding is that you have a setup with oni/neovim that mostly works well, but where inverse search does not work. It is not clear what you use for pdf viewer. Also, if you could provide a full minimal configuration for your setup so that I could reproduce, that would help much.

**Comment by meijieru** [comment]
Thanks.

When I use neovim, inverse search works well with okular by `nvr`. Now, what I want to do is using oni with okular, where the inverse search broken.

**Comment by lervag** [comment]
The inverse search relies on the `vim --remote` family of commands. These were removed from neovim, which is why we use [`nvr`](https://github.com/mhinz/neovim-remote).

Doing a quick search, I found a relevant thread at the oni repo:
- https://github.com/onivim/oni/issues/247

That is, the main question that must be answered is how to use e.g. `nvr` to communicate with the neovim instance in oni.

**Comment by lervag** [comment]
Actually, I think `oni` should work well with `nvr` out of the box. Could you please give the output from `:VimtexInfo` (or `\li`) here after you've opened a LaTeX file in oni?

Note, when you run `nvr --remote....`, it is often useful or necessary to set the servername somehow. That is, Okular should somehow know the servername of the oni instance.

**Comment by meijieru** [comment]
Here are the output of `\li`

```
System info
  OS: Manjaro Linux
  Vim version: NVIM v0.2.2
  Has clientserver: true
  Servername: /tmp/nvim3vcgBK/0

vimtex project: example
  base: example.tex
  root: /home/jrmei/workspace/other/HUSTPaperTemp/Example
  tex: /home/jrmei/workspace/other/HUSTPaperTemp/Example/example.tex
  out: /home/jrmei/workspace/other/HUSTPaperTemp/Example/build/example.pdf
  log: /home/jrmei/workspace/other/HUSTPaperTemp/Example/build/example.log
  aux: /home/jrmei/workspace/other/HUSTPaperTemp/Example/build/example.aux
  fls: /home/jrmei/workspace/other/HUSTPaperTemp/Example/build/example.fls
  compiler: latexmk
    backend: nvim
    output: /tmp/nvim3vcgBK/4
    configuration: 
      continuous: 1
      callback: 1
      build_dir: build
      latexmk options:
        -xelatex
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
  document class: HustGraduPaper
  packages:
    CJKfntef
    algorithm
    algorithmicx
    algpseudocode
    amsbsy
    amsfonts
    amsgen
    amsmath
    amsopn
    amssymb
    amstext
    appendix
    array
    auxhook
    bm
    booktabs
    caption
    caption3
    ctex
    ctexhook
    ctexpatch
    enumitem
    environ
    everysel
    expl3
    fancyhdr
    fix-cm
    float
    fontenc
    fontspec
    fontspec-xetex
    geometry
    gettitlestring
    graphics
    graphicx
    hobsub-generic
    hobsub-hyperref
    hyperref
    ifpdf
    ifthen
    ifvtex
    ifxetex
    keyval
    kvoptions
    l3keys2e
    makecell
    metalogo
    multirow
    nameref
    natbib
    realscripts
    rerunfilecheck
    stringenc
    subfig
    tabularx
    titlesec
    tocloft
    trig
    trimspaces
    ulem
    url
    wrapfig
    xeCJK
    xeCJKfntef
    xltxtra
    xparse
    xstring
    xtemplate
    xunicode
    xunicode-addon
    zhnumber
```

**Comment by lervag** [comment]
To me, it seems you should be able to make things work based on the other stuff I wrote in my previous comments.

**Comment by meijieru** [comment]
I found it works now, thanks!

**Comment by lervag** [comment]
Great! Feel free to give some details, especially if there is something I should write in the docs, either about how to work with Okular, or how to work with oni. Although, I think the latter is equiavalent to neovim.

**Comment by meijieru** [comment]
One thing took me a lot of time is that okular use "shift + click" to do inverse search. I think that may be in the doc.

**Comment by lervag** [comment]
Thanks, I've updated.
