### ISSUE TITLE
Support for draftmode runs for first few latexmk runs from within vimtex

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1131]
I have a really complicated document using LuaTeX (PhD thesis with lots of figures etc.)

My compilation times have really become a lot of bottleneck, so much that even a minor spelling change in a word takes a few minutes to compile and for the PDF to refresh.

I have externalised graphics with tikz, pre-compiled preamble, avoided loading unnecessary packages, but it is still too slow.

I read that draftmode for the first few runs can really save the day here. I am able to get this done from the terminal following the answers here: https://tex.stackexchange.com/questions/212657/compile-a-document-as-draft-for-the-first-few-times-and-then-non-draft-in-the?  and here: https://gist.github.com/yig/ba124dfbc8f63762f222

But how do I get ```vimtex``` to use this? Notice that there needs to be 2 distinct calls to latexmk.  I am also of the opinion that maybe this should be the default action sequence vimtex should aim for? I do not see any harm in running draftmode for the very first run. Surely, you can't get references right with the very first run, so draftmode can fly through this blazing fast.

**Comment by lervag** [comment]
This could work pretty well when you compile manually, but it will not work well for continuous compilation.

IMHO, the complexity of implementing this in a robust manner does not outweight the convenience in general. I understand that this will be very useful to you when working on book-sized documents (with figures, equations, tikz figures, etc), but it is not really that important for most use cases.

I would be much more positive if there was a way to do this through ones `.latexmkrc` file, somehow. Then I would definately want to write about it in the docs as a suggested setup. But searching the webs for more information on this topic did not make me much wiser.

If you prefer manual compilation, then I think perhaps [arara](https://www.ctan.org/pkg/arara) might be of interest to you. I think you could get the desired behaviour with arara, and it should also work with vimtex (see `:h vimtex-arara`).

**Comment by lervag** [comment]
Note, one tip for speeding things up is to use the [subfiles package](http://texdoc.net/texmf-dist/doc/latex/subfiles/subfiles.pdf). It makes it easy to split your project into multiple files, and then to only compile the file that you are working on. E.g., if you split up into your various chapters and are working on `chapters/chap1.tex`, then in vimtex you can do `\ls` to start working on the "local" version. If you compile now, only chapter 1 will be compiled. This might make things considerably faster.

**Comment by krishnakumarg1984** [comment]
@lervag  thank you. I thought what you propose is  what ```\include``` with ```\includeonly``` does, right?

**Comment by lervag** [comment]
No, `subfiles` does more than `\include` and similar. With `subfiles`, you can compile the subfile chapter directly, and it will use the main file preamble. Vimtex supports this and provides the `\ls` to toggle between the main/full project and the subfile/local file. This makes it pretty easy to work on a part of your book and only compile that part, and at the same time compile the full document whenever you want. I propose that you read (or skim) the subfile manual to learn more.
