### ISSUE TITLE
Zathura reverse search with neovim does not work (installed from Ubuntu repos)

### ISSUE THREAD

**Issue by AlxBartel** [lervag/vimtex#1133]
I am trying to set up neovim with vimtex and zathura. I installed zathura on Ubuntu 18.04 from the repository. Forward search works as it should, but Ctrl-Left click in Zathura does nothing.

Minimal ~/.config/nvim/init.vim:
```
" vim-plug configuration
call plug#begin('~/.local/share/nvim/plugged')

" Latex plugin
Plug 'lervag/vimtex'

" Initialize plugin system
call plug#end()

let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_progname = 'nvr'
let g:tex_flavor = 'latex'

```

My ~/.config/zathura/zathurarc (I also tried it without it):
```
set synctex true
set synctex-editor-command "nvr --remote-silent %f -c %l"

```

My ~/.latexmkrc:

`$pdflatex = 'pdflatex --shell-escape -synctex=1 %O %S';`

Since I installed Zathura from the repositories (after having installed libsynctex), I was not sure if it had been compiled with synctex enabled. Presumably, since forward search works, synctex must be working, in principle? Just in case,

zathura -h gives
```
Usage:
  zathura [OPTION…]  [file1] [file2] [...]

Help Options:
  -h, --help                           Show help options

Application Options:
  -e, --reparent=xid                   Reparents to window specified by xid (X11)
  -c, --config-dir=path                Path to the config directory
  -d, --data-dir=path                  Path to the data directory
  --cache-dir=path                     Path to the cache directory
  -p, --plugins-dir=path               Path to the directories containing plugins
  --fork                               Fork into the background
  -w, --password=password              Document password
  -P, --page=number                    Page number to go to
  -l, --log-level=level                Log level (debug, info, warning, error)
  -v, --version                        Print version information
  -x, --synctex-editor-command=cmd     Synctex editor (forwarded to the synctex command)
  --synctex-forward=position           Move to given synctex position
  --synctex-pid=pid                    Highlight given position in the given process
  --mode=mode                          Start in a non-default mode
```

**Comment by AlxBartel** [comment]
Please ignore, it works perfectly. My suspicion is that I must have tested this on a file that I had not changed, and so latexmk was not recompiling, and therefore not creating a synctex file. This issue can be closed.

**Comment by lervag** [comment]
Sorry for the late reply, but I'm glad it sorted out by itself. :)

**Comment by RolfMa** [comment]
> Please ignore, it works perfectly. My suspicion is that I must have tested this on a file that I had not changed, and so latexmk was not recompiling, and therefore not creating a synctex file. This issue can be closed.

Hi, could you give me a favor? I copied you settings, but I don't no how to active reverse search function in Zathura, I mean, which key should I press? Thank you!

**Comment by imLew** [comment]
@RolfMa The default seems to be 'Ctrl + <Left Click>'

**Comment by levduc** [comment]
It used to work, but backward search functionality on zathura no longer works for me. I cannot figure out how to fix it even after looking at other issues.
My configuration:
```
Arch Linux
Zathura 0.4.8
neovim v0.5.0

```
