### ISSUE TITLE
Is it possible to do forward search and not have vim instance lose focus?

### ISSUE THREAD

**Issue by Epaenetus** [lervag/vimtex#1134]
# Explain the issue
Is there a way to do a forward search and not leave the vim instance? Every time I use vimtex-view, my focus leaves the VIM instance and transfers to the pdf viewer itself.

**Comment by lervag** [comment]
Yes and no. It depends on the system (OS) and the pdf viewer. Please provide some more details:

1. Your relevant vimtex configuration, and
2. Your OS system and Vim (or neovim) version.

**Comment by Epaenetus** [comment]
`let g:vimtex_view_general_viewer = 'SumatraPdf'`
`let g:vimtex_view_general_options = '-reuse-instance -shell-escape -forward-search @tex @line @pdf'`
`let g:vimtex_view_general_options_latexmk = '-reuse-instance'`
  
I am using Windows and running Vim 8.1 in ConEmu. Let me know if there is any further info you need. Thank you!

**Comment by lervag** [comment]
Thanks!

I do not know any way to do what you ask on windows, but I would not be surprised if it is possible. See #865 for a similar question with a solution that works on Linux. You could possibly find something like `xdotool` that works on windows that you could use to change the focus after the `vimtex-view` command has been run. Something like this:

```vim
let g:vimtex_view_general_hook_view = 'MyHook'

function! MyHook()
  silent call system(...)
endfunction
```

where `...` is a command that is run in the shell on Windows that somehow puts the focus back to Vim.

As I do not know anything more specific than this, I am closing the thread.
Please let me know if you should be able to solve it, I would be happy to know
and perhaps write about it in the docs.
