### ISSUE TITLE
Automatically call :VimtexView on successful compilation with neovim

### ISSUE THREAD

**Issue by steveeJ** [lervag/vimtex#1135]
I'm trying to port a workflow that I had working a while ago in vim to neovim.
When I run `:VimtexView` manually or use the keyboard shortcut the current block is highlighted in the PDF in zathura, so in general the synctex mechanism seems to work.
However my old config doesn't trigger this on successful compilation anymore. 

## The setup
The setup is based on direnv + Nix so it might look unfamiliar. Other than that I trust it being reproducible, in fact easier to reproduce than a mere minimal vimrc example, as the setup also includes system dependencies as seen in the default.nix. Please don't hesitate to state any questions about the setup and I will answer in detail.

* [default.nix shell containing the neovim configuraiton](https://gist.github.com/steveeJ/1392f68b7f5221c1b06ecd7818be85a7#file-default-nix)
* [generated vimrc](https://gist.github.com/steveeJ/1392f68b7f5221c1b06ecd7818be85a7#file-bnc97wyyvids042v688nw6cbil3s6l8l-vimrc)
* [tex file used](https://gist.github.com/steveeJ/1392f68b7f5221c1b06ecd7818be85a7#file-minimal-tex)

Here's the important part from the vimrc:

```vim
            let g:vimtex_view_method = 'zathura'
            let g:vimtex_latexmk_options = '-verbose -pdf -shell-escape -file-line-error -synctex=1 -interaction=nonstopmode'
            function! ViewerCallback() dict
              call self.forward_search(self.out)
            endfunction
            let g:vimtex_view_zathura_hook_callback = 'ViewerCallback'
```

## Reproducing the issue

This assumes having the above configuration in place.

### Steps

1. Run `nvim minimal.tex`
2. Execute :VimtexCompile and watch how zathura is opened
3. Edit the file and save it, and watch it reload.

### Result
The preview is reloaded but the forward search is not triggered, as there is no green background behind the text.

### Expected
Automatic triggering of the forward search and seeing a green background behind the (only) paragraph in this small example.

**Comment by lervag** [comment]
Hi, and thanks for the issue report. First, `g:vimtex_latexmk_options` has been deprecated for quite some time. Please see `:h g:vimtex_compiler_latexmk`. Further, `self.out` is a function, not a variable, so you must do `self.out()`. So, I can reproduce your problem, and with `self.out()` it seems to work as expected.

**Comment by steveeJ** [comment]
Thanks for taking a look at my config. I've incorporated your changes but I still can't produce the expected result. I saw that in your referenced example you added `et g:vimtex_compiler_progname = 'nvr'`. Is that necessary for this functionality? I'm wondering because the manual call to :VimtexView works just fine.
