### ISSUE TITLE
loading custom latexmk options for lualatex

### ISSUE THREAD

**Issue by pitkling** [lervag/vimtex#1136]
When using latexmk, vimtex by default uses the `-pdf` flag. In particular, this allows me to have a line of the form

    $pdflatex = "pdflatex %O -shell-escape %S"

in my `~/.latexmkrc` which activates some custom options (like `-shell-escape`, in this case).

Now suppose I have one specific latex project that should use lualatex. I can make vimtex use lualatex in this project by starting the tex source with the tex-directive

    % !TEX program = lualatex

Now this makes vimtex add the command line option `-lualatex` to latexmk. Unfortunately, this way I cannot define custom lualatex options in my `~/.latexmkrc`. If instead the tex-directive would cause vimtex not to add `-lualatex` but to use `-pdflua` instead of `-pdf`, a line like

    $lualatex = "lualatex %O -shell-escape %S"

in my `~/.latexmkrc` would be picked up correctly by latexmk.

(I'm not sure since when the `-pdflua` switch is supported by latexmk, it might be a comparatively new feature. My latexmk is version 4.56.)

**Comment by lervag** [comment]
This is an interesting issue. First, are you sure there is no way to add lualatex options with `-lualatex`? According to [the manual](http://ctan.math.washington.edu/tex-archive/support/latexmk/latexmk.pdf):

```
$lualatex ["lualatex %O %S"]

    The LaTeX processing program that is to be used when the lualatex program
    is called for (e.g., by the option -lualatex).
```
Further, it reads:

```
-lualatex

    Use lualatex. That is, use lualatex to process the source file(s) to pdf.
    The generation of dvi and postscript files is turned off.

    This option is equivalent to using the following set of options

      -pdflua -dvi- -ps-

    (Note: Note that the method of implementation of this option, but not its
    intended effect, differ from some earlier versions of latexmk.)
```

This seems to indicate that you should be able to use the `$lualatex` variable. Perhaps the problem is that the `-lualatex` option comes before `-pdf`?

**Comment by lervag** [comment]
I'm thinking perhaps the `-pdf` flag to latexmk should not come from the default option list, but from the default engine list. What do you think?

**Comment by lervag** [comment]
That is: If you remove the `-pdf` flag from the `g:vimtex_compiler_latexmk.options` list, and then use the `lualatex` directive, do things work as expected?

**Comment by lervag** [comment]
That's strange. I don't quite understand how you could affect that order. But regardless, I'm happy it works now!

I'll think about changing the default options and putting `-pdf` into the engine list. The drawback is that it makes it (currently) impossible to remove the `-pdf` option. Still, this could raise a feature request that could improve the configuration. Thus I am tempted to do the change, and then instead fix the possible drawback if anyone should ever want to remove the `-pdf` flag.

**Comment by lervag** [comment]
I've changed things again, sorry. Please see my comment at  #1142 for more details.

**Comment by lervag** [comment]
Note, I think the change is ultimately good, as it adds more flexibility and robustness. However, you might need to change some settings (not sure).

**Comment by pitkling** [comment]
That's actually a great solution, thanks! :)
(Also, no problems, everything works as expected.)

**Comment by lervag** [comment]
No problem, I'm also happy as I think this is a better implementation now. It ensures that the TeX program directive may be parsed correctly regardless of the compiler (e.g. latexrun vs latexmk).
