### ISSUE TITLE
Have to do vimtex-clean

### ISSUE THREAD

**Issue by Majdoddin** [lervag/vimtex#1139]
You open a Latex source in continuous mode, but it does not compile because a required Latex package is missing. You install the missing package (for example via tlmgr). But now you have to run vimtex-clean first to have your Latex source recompiled.
This is inconvenient, specially if the Latex source is from someone else and you have to install many packages to get it compiled.

**Comment by lervag** [comment]
Your issue post is of very low quality. It is unclear what you want.

It seems that you want there to be some sort of automatic cleaning of source files if you install a missing package. However, this is a very complex feature that has a very limited usage (IMHO). So I am not going to implement it.

Instead, I suggest that you install something like `texlive-full` or `texlive-huge` or whatever is available on your system. This will install a lot of stuff (~1-2 GB), but it should also make it very rare that packages are missing.
