### ISSUE TITLE
Lualatex option is not applied

### ISSUE THREAD

**Issue by ashtez** [lervag/vimtex#1141]
Sorry to bother you, but I can't wrap my head around this one : 

1. My `vimrc` file:

    ```vim
      let mapleader = ","

      let g:vimtex_compiler_latexmk = {
          \ 'options' : [
          \   '-lualatex',
          \   '-interaction=nonstopmode',
          \ ],
          \ 'build_dir' : 'livepreview',
      \}

     noremap <leader>ll :VimtexCompile<cr>
    ```

2. A minimal `.tex` file, looking like my *way bigger* real one:

    ```tex
    \documentclass[french,12pt,a4paper]{article}
    \usepackage{fontspec} % gère les polices
    \begin{document}
          ...
    \end{document}
    ```

3. So, when I open my `main.tex` file in vim, I try to compile it with `,ll`, which indeed launches the compilation. The problem is that it doesn't use lualatex, as I have the following log file (`main.log`) : 
```
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Arch Linux) (preloaded format=pdflatex 2018.6.14)  14 JUN 2018 21:50

...

Package: fontspec 2017/11/09 v2.6g Font selection for XeLaTeX and LuaLaTeX


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! Fatal fontspec error: "cannot-use-pdftex"
! 
! The fontspec package requires either XeTeX or LuaTeX.
! 
! You must change your typesetting engine to, e.g., "xelatex" or
! "lualatex"instead of "latex" or "pdflatex".
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.44 \msg_fatal:nn {fontspec} {cannot-use-pdftex}
                                                 
|'''''''''''''''''''''''''''''''''''''''''''''''
| This is a fatal error: LaTeX will abort.
|...............................................

 ) ) 
```

**Comment by lervag** [comment]
Ah, yes. This is because the TeX engine is now not part of the option set. It is instead set by the TeX directive. By default, the `-pdf` option (which implies `pdflatex`) is used. You can use directives in your TeX file, see `:h vimtex-tex-program`.

So, the current way to fix this is to remove your `'option'` change and to add `%! TeX program = lualatex` in a comment in one of the first lines of the main TeX file.

In addition, I've added the option `g:vimtex_compiler_engine` that you can use to change the default engine.

**Comment by rezahousseini** [comment]
Still having the same problem despite using 

    let g:vimtex_compiler_engine = 'lualatex'

in my vimrc and writing

    %! TeX program = lualatex

At the top of my `main.tex` file

**Comment by lervag** [comment]
Please open a new issue and describe your problem fresh. There is no indication that this issue was not resolved for the original poster. Follow the issue template and include a minimal example.

**Comment by Rmano** [comment]
> and writing
> 
> ```
> %! TeX program = lualatex
> ```
> 
> At the top of my `main.tex` file

I can't check now (in a hurry for the frigging online classes) but I thought I had the same problem once because I failed to notice that you have to re-open the file after changing the `%! TeX program` directive --- and that's quite logical. Save and re-open the file and it should work.
