### ISSUE TITLE
Optional and required external dependencies

### ISSUE THREAD

**Issue by eirnym** [lervag/vimtex#1145]
I went through your github page and haven't found any notes about external optional and required dependencies. By reading actual plugin code I've found that your plugin uses some third-party applications and somehow uses python 3. 

Could you explain in readme or installation/usage file following things:
* Which third-party applications and libraries should be installed beforehand?
* How to configure paths to each package/library?
* If any of this is optional, explain what I'll gain when have these applications and libraries

Reasoning why path configuration is important. On macOS I use MacPorts, someone uses Homebrew, someone else don't want or can't install even in this way (only inside home directory)

**Comment by lervag** [comment]
Actually, I've described dependencies quite well. The plugin code does not use python at all. Third-party applications depend on a couple of things, but are described where necessary, I think.

I don't use macOS, never did and probably never will. So there is not really any motivation for me to do investigate this issue. However, I will accept relevant pull requests or suggestions for updates to the documentation.

By default, the only requirement is `latexmk`, which should be suppplied through your LaTeX installation.
