### ISSUE TITLE
quickfix window does not open automatically

### ISSUE THREAD

**Issue by dbacc** [lervag/vimtex#1146]
Hey,

I just read, that the `quickfix` window is actually supposed to open automatically. Well, that never happened so far...

I'm using `neovim` with a minimalistic `.vimrc` just loading the plugin and the following modifications:

```vim
let g:python3_host_prog='/usr/bin/python3'
let g:python_host_prog='/usr/bin/python2'
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique @pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
let g:vimtex_latexmk_progname = 'nvr'
let g:vimtex_compiler_latexmk = {
    \ 'backend' : 'nvim',
    \ 'background' : 1,
    \ 'build_dir' : '../build',
    \ 'callback' : 1,
    \ 'continuous' : 1,
    \ 'executable' : 'latexmk',
    \ 'options' : [
    \   '-pdf',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}
```

After starting the compiler I can see that the following command is running:

```
perl /net/TeXLive/bin/x86_64-linux/latexmk -pdf -verbose -file-line-error -synctex=1 -interaction=nonstopmode -outdir=../build -pvc -e $pdf_previewer = "okular --unique" -e $success_cmd = "/usr/bin/nvim --servername /tmp/nvimgimSqb/0 --remote-expr \"vimtex\#compiler\#callback(1)\"" -e $failure_cmd = "/usr/bin/nvim --servername /tmp/nvimgimSqb/0 --remote-expr \"vimtex\#compiler\#callback(0)\"" main.tex
```

However, the `quickfix` window doesn't open automatically, nor does it update after changing something.

**Comment by lervag** [comment]
I can understand that reading the entire docs is baffling, but the answer to your questions are there.

The thing that is lacking is a coupling with the serverclient. For neovim, I think the docs explain it well here: `:help vimtex-faq-neovim`. 

Finally, note that the `python` options are not relevant for vimtex at all. Ah, sorry, I just now see that you set `g:vimtex_latexmk_progname`. This option is deprecated. Instead, you should use `g:vimtex_compiler_progname`. I think that should solve your problem.

Note also, you don't have to set the compiler options that are already default. I.e., you can simplify your config to:

```vim
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique @pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : '../build',
    \}
```

**Comment by dbacc** [comment]
Thanks again for the quick reply! That indeed solved the problem. I've probably just taken the depecrated option from somewhere in the internet.

**Comment by lervag** [comment]
No problem. Happy it works. :)
