### ISSUE TITLE
RFC: Add motions [m, ]m, [M, ]M to jump to begin or end of environment

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1147]
This is a feature request about adapting the builtin motions `[m,]m,[M,]M` for LaTeX files to jump to the beginning or ending of an environment. I think the default behaviour does not match the intention of these motions in LaTeX files.

```
						*]m*
]m			Go to [count] next start of a method (for Java or
			similar structured language).  When not before the
			start of a method, jump to the start or end of the
			class.  When no '{' is found after the cursor, this is
			an error.  |exclusive| motion. {not in Vi}
						*]M*
]M			Go to [count] next end of a method (for Java or
			similar structured language).  When not before the end
			of a method, jump to the start or end of the class.
			When no '}' is found after the cursor, this is an
			error. |exclusive| motion. {not in Vi}
						*[m*
[m			Go to [count] previous start of a method (for Java or
			similar structured language).  When not after the
			start of a method, jump to the start or end of the
			class.  When no '{' is found before the cursor this is
			an error. |exclusive| motion. {not in Vi}
						*[M*
[M			Go to [count] previous end of a method (for Java or
			similar structured language).  When not after the
			end of a method, jump to the start or end of the
			class.  When no '}' is found before the cursor this is
			an error. |exclusive| motion. {not in Vi}
```

From my point of view they should jump to the noted lines in following example file.

```tex
\documentclass[]{article}

\begin{document}                                % [m[m[m[m or 4[m

\begin{figure}                                  % [m[m[m or 3[m
  \centering
  \includegraphics[width=\linewidth]{file}
  \caption{figure}
  \label{fig:illustration}
\end{figure}                                    % [M

\begin{table}                                   % [m[m or 2[m
  \centering
  \begin{tabular}{c}                            % [m
                                                % CURSOR
  \end{tabular}                                 % ]M
  \caption{table}
  \label{tab:listing}
\end{table}                                     % ]M]M or 2]M

\begin{figure}                                  % ]m
  \centering
  \includegraphics[width=\linewidth]{file}
  \caption{figure}
  \label{fig:illustration}
\end{figure}                                    % ]M]M]M or 3]M

\end{document}                                  % ]M]M]M]M or 4]M
```

Feedback what other people would expect from these motions in LaTeX files would be very welcome.

For convenience one can use https://github.com/Houl/repmo-vim to use `;` and `,` to repeat these motions.

Another issue would be to adapt the motions which move to start of comments `[*` or `[/` and to end of comments `]*` or `]/`. However, other ftplugins have used for them their commentstring, e.g. `$VIMRUNTIME/ftplugin/vim.vim`:
```
  " Move around comments
  nnoremap <silent><buffer> ]" :call search('^\(\s*".*\n\)\@<!\(\s*"\)', "W")<CR>
  vnoremap <silent><buffer> ]" :<C-U>exe "normal! gv"<Bar>call search('^\(\s*".*\n\)\@<!\(\s*"\)', "W")<CR>
  nnoremap <silent><buffer> [" :call search('\%(^\s*".*\n\)\%(^\s*"\)\@!', "bW")<CR>
  vnoremap <silent><buffer> [" :<C-U>exe "normal! gv"<Bar>call search('\%(^\s*".*\n\)\%(^\s*"\)\@!', "bW")<CR>
```
 However, this is not possible for latex: `[%` is already used by matchit/match-up.

**Comment by lervag** [comment]
I agree this makes much more sense, thanks.

**Comment by lervag** [comment]
I'm curious if we really need this for comments...?

**Comment by kiryph** [comment]
Thank you for adding the `[m`, `]m`, `[M`, `]M` motions. I start to use them more and more often in other filetypes and had this idea for LaTeX files for a while.
IMHO the square bracket motions rely to much on my right pinky finger and I still have to improve my typing skills to type them quickly without making a typo.

I mentioned`[*` or `[/` more or less for the sake of completeness. There are not many default ft-specific motions left which can be adapted for filetypes.

**Comment by lervag** [comment]
For the sake of completeness, I've now implemented the comment motions. I've also updated the docs to more reflect how they are written for e.g. `]m` and `]*` in the Vim documentation.

I think it should work as expected, but let me know if I've missed something.

**Comment by kiryph** [comment]
Thanks for adding these as well.
Just for the record

- `$VIMRUNTIME/ftplugin/vim.vim` uses `["` and `]"`
- `$VIMRUNTIME/ftplugin/eiffel.vim` uses `[-` and `]-`
- `$VIMRUNTIME/ftplugin/hamster.vim` uses `[#` and `]#`
- `$VIMRUNTIME/ftplugin/sql.vim` uses `["` and `]"` (comments can be `/*...*/`, `//` or `--`)

Therefore, they do not actually overwrite `[*` or `[/`. However, I certainly do not mind to overwrite them. The only reason I could imagine to save them for motions where they have better mnemonics.

However, following is in my opinion more important: there seem to be different expectations what these motions do:

```c
// ft=c

/* // [*[* moves here
 * FIRST COMMENT
 */

/*  // [* moves here
 * CURSOR
 */ // ]* moves here


/*
 * THIRD COMMENT
 */ // ]*]* moves here
```

The implementation in $VIMRUNTIME/vim.vim (author: Bram Moolenaar)
```vim
" ft=vim

"
" FIRST COMMENT
" [" moves here

"
" CURSOR
"

" ]" moves here
" THIRD COMMENT
"
```
It is surprising that Bram implemented them differently. You obviously followed vim.vim:

```tex
% ft=tex
\documentclass{article}

\begin{document}

% Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
% tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
% vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
% no sea takimata sanctus est Lorem ipsum dolor sit amet. 
% [* moves here


% Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
% tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
% >>> CURSOR
% vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
% no sea takimata sanctus est Lorem ipsum dolor sit amet. 

% ]* moves here
% Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
% tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
% vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
% no sea takimata sanctus est Lorem ipsum dolor sit amet. 

\end{document} 
```
In sql.vim, they do something different again:
```vim
" Move to the start and end of comments
exec 'nnoremap <silent><buffer> ]" :call search('."'".b:comment_start."'".', "W" )<CR>'
exec 'nnoremap <silent><buffer> [" :call search('."'".b:comment_end."'".', "W" )<CR>'
exec 'xnoremap <silent><buffer> ]" :<C-U>exec "normal! gv"<Bar>call search('."'".b:comment_start."'".', "W" )<CR>'
exec 'xnoremap <silent><buffer> [" :<C-U>exec "normal! gv"<Bar>call search('."'".b:comment_end."'".', "W" )<CR>'

" Comments can be of the form:
"   /*
"    *
"    */
" or
"   --
" or
"   //
```

```sql
-- ft=sql

--
-- FIRST COMMENT
--

--
-- CURSOR
-- [" moves here

-- ]" moves here
-- THIRD COMMENT
--
```

For sql.vim a vim user has six mappings `[* ]*`, `[/ ]/` and `[- ]-`. The last two consider all comments but behave differently than the others which only consider `/* ... */` and `// `.
Since I do not write sql files, I do not care.

But I am also unsure for the tex case. I could imagine to use four mappings:

- `[/` start of current or previous comment
- `[*` end of previous comment
- `]*` end of current or next comment
- `]/` start of next comment

I guess I would slightly favour my proposal of four mappings:

I imagine that jumping through a file by comments could be a useful motion which could be done using `repmo.vim` together with my proposal of `[/` and `]/` jumping always to the start of a comment.

BTW, I have encountered a few people who actually use the package https://ctan.org/pkg/comment:
which adds `\be­gin{com­ment} ... \end{com­ment}`. I do not use this package, since commentary and textobjects do the trick for me. First of all the syntax highlighting could change for the content of this environment and of course this environment could be taken into account for the motions under discussion.
I see one advantage of this environment: the line length does not change compared to using a comment character in all lines.

**Comment by lervag** [comment]
Yes, I based the motions on `:h ]star`. However, I agree that there seems to be no reason not to improve this as you suggest. I think, in that case, that 

Regarding `\begin{comment}...\end{comment}`, I don't want to add that complexity at this time. As you say, you've "eoncountered a few people". None of these have opened any issue here, and so it seems to not really be a big issue at all. However, if I were to work on this, then I think it should be opened as a separate issue.

**Comment by lervag** [comment]
Let me know what you think about this. It is not perfect and I there are probably edge cases that are missed, but I think it should _mostly_ work as expected. :)

**Comment by kiryph** [comment]
Thanks once again. They work as expected for me (until I find an edge case :-)).

I think the symmetry between

- `[[`, `[m`, `[/` for previous beginning of section, environment, comment
- `][`, `]m`, `]/` for next beginning of section, environment, comment

and

- `[]`, `[M`, `[*` for previous end of section, environment, comment
- `]]`, `]M`, `]*` for next of end of section, environment, comment

helps to memorize them, or even to guess and maybe one uses them more often than I anticipate.

**Comment by lervag** [comment]
I agree, and I actually think I might use them myself. Thanks for raising the issue!
