### ISSUE TITLE
Improve 'include-search' for subfiles

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1148]
Add `%TEX root = main.tex` to `include`?

Vimtex sets `'define'` so `[d` family of commands could work
(https://github.com/lervag/vimtex/blob/master/autoload/vimtex.vim#L336-L344).

However, consider following simple MWE:

`main.tex`:
```tex
\documentclass{article}

\renewcommand{\vec}[1]{\mathbf{#1}}

\begin{document}

$\vec{a}\cdot\vec{b}$ % [Ctrl-d works on \vec
\include{chapter1}

\end{document} 
```

`chapter1.tex`:
```tex
%  TEX root = main.tex
\chapter{First}

$\vec{a}\cdot\vec{b}$ % [Ctrl-d DOES not work on \vec
```

I get the error message

`E388: Couldn't find definition`

Cyclic includes should obviously be avoided.

Also having a large project with many included files the search gets quite slow and actually blocks vim8.

---

If you don't mind, have also a look at the recent plugin by tpope: https://github.com/tpope/vim-apathy

I hope that vimtex could set everything up so that the features mentioned in the readme work appropriately for latex files:

> * `gf`, `<C-W>f`, `<C-W>gf`: jump to the included file under the cursor.
> * `:find`, `:sfind`, `:tabfind`: jump to the specified included file.
> * `[i`: display the first line in the current file or an included file
>   containing the keyword under the cursor.
> * `]i`: like above, but start searching after the cursor.
> * `:isearch`: like above, but give your own line range and search pattern.
> * `[I`, `]I`, `:ilist`: like above, but display all matches.
> * `[<C-I>`, `]<C-I>`, `<C-W>i`, `:ijump`, `:isplit`: like above, but jump to
>   the match.
> * `<C-X><C-I>`: complete keywords from included files.
> * `[d`, `]d`, `:dsearch`, `[D`, `]D`, `:dlist`, `[<C-D>`, `]<C-D>`, `<C-W>d`,
>   `:djump`, `:dsplit`, `<C-X><C-D>`: like their `i` equivalents, but for macro
>   definitions.
> * `:checkpath`: list missing included files.

1. `gf`-family already works thanks to `suffixesadd` and `includeexpr`
2. `'path'` is completely neglected by vimtex. I am actually not sure myself how to set it up.
The texmf tree is too complex and it does not make sense adding every subfolder.
This affects the commands `:find`, `:sfind`, `:tabfind`.
3.  I am not sure for what to use the `[i` family.  Currently, I use ctags which allows me to navigate to labels and bibtex sources. Also keyword completion from included files is nothing I missed yet.
4. `[d` family is something new what I haven't thought about using in Latex files which apathy.vim inspired me to use. Vimtex already sets `'define'` properly so this should in principle work as well. 
5. `:checkpath` could be used if you have specified a package, documentclass, include file which cannot be found.

**Comment by lervag** [comment]
I'll address the main concern raised here, i.e. that `]d` does not work in `chapter1.tex`. You give some extra context and ideas, which is interesting, but in some sense irrelevant.

You suggest to add the `TeX root` as an include directive. I was worried that cyclic includes would be a problem, but it appears to work well. Please test and let me know what you think.

**Comment by kiryph** [comment]
The extra context was meant to be as background information. I should have been more explicit about this. I think tpope has such a good understanding of *the vim way*, that is always good to see how he approaches features under consideration.
 If I will miss something from 'the list', I will raise a new issue.

The minimal example works. So thanks for the update.

But it is really slow. I am not sure how to profile a builtin mapping (`[d`). If you know this, any help would be appreciated.

**Comment by lervag** [comment]
I agree, and I found the information interesting. Thanks.

I've also noticed that the mapping is slow. Unfortunately, I have no idea why and how to debug that. Perhaps it is a result of the "cyclic" include? If you should find any information on this that could help, let me know!

**Comment by andymass** [comment]
One thing I noticed is when pressing `[d` on `\vec` in `chapter1.tex` in @kiryph's example, vimtex tries `main.tex.tex`, `main.tex.sty`, `main.tex.cls`, then finally `main.tex`, which it finds.  This may be intentional but it seems wasteful to call `kpsewhich` four times in this case.

There is another problem; pressing `[d` on `\cdot` also tries `\include{.tex`, `\include{main.sty`, `\include{.cls`, and `\include{`, which are nonsensical filenames.

**Comment by lervag** [comment]
How did you notice this, @andymass? It is not intentional from my side.

**Comment by andymass** [comment]
I just put an `echo a:file` before the `system(` in `vimtex#kpsewhich#find` figuring the `kpsewhich` was the slow part.  I assume it's reproducible, but if not I can try to investigate a MWE (which is simply `main.tex` and `chapter1.tex` with a minimal vimrc).

**Comment by lervag** [comment]
Thanks! I'll push a fix soon that makes things faster.

**Comment by lervag** [comment]
The latest commit fixes the issue with slow `[<c-d>`, and also fixes another issue where definitions in `\include{something}` were not found.

**Comment by kiryph** [comment]
It works now without an annoying delay which would have been a reason not to use it.

Also thanks to @andymass to have a quick look into this.

**Comment by kiryph** [comment]
The `README.md` and `doc/vimtex.txt` could highlight/document that vimtex sets following settings

- `'include'`
- `'includeexpr'` (already documented)
- `'suffixesadd'`
- `'define'`

which allows to use `:h include-search` and `:h definition-search`.

However, LaTeX path searching ([kpathsea](http://tug.org/texinfohtml/kpathsea.html)) is not mirrored to vim's path searching mechanism.

IMHO vim could have an option like `'findexpr'` for `:find` which could point to `kpsewhich` or use the cached results in `ls-R` files.

If I find the time, I would ask about this on the vim_dev mailing list.

**Comment by lervag** [comment]
Thanks, agreed. And I would be happy if such a `findexpr` existed. In the meantime: Would it be possible/make sense to use `kpsewhich` during init to set `path` properly?

E.g. something like `kpsewhich -var-value TEXINPUTS`?

**Comment by lervag** [comment]
That is,

```sh
kpsewhich -var-value TEXINPUTS

# Outputs
# .:{/home/lervag/.texlive/texmf-config,/home/lervag/.texlive/texmf-var,/home/lervag/.texmf,!!/etc/texmf,!!/var/lib/texmf,!!/usr/local/share/texmf:/usr/share/texmf,!!/usr/share/texmf-dist}/tex/{kpsewhich,generic,}//
```

The output string could then be parsed to the set of search paths and this could be used to set `'path'`.

**Comment by kiryph** [comment]
I am not sure if this is sufficient and we would need actually more something like:

``
prefix/      installation root (/usr/local by default)
 bin/         executables
 man/         man pages
 include/     C header files
 info/        GNU info files
 lib/         libraries (libkpathsea.*)
 share/       architecture-independent files
  texmf/      TDS root
   bibtex/     BibTeX input files
    bib/        BibTeX databases
     base/       base distribution (e.g., ‘xampl.bib’)
     misc/       single-file databases
     pkg/       name of a package
    bst/        BibTeX style files
     base/       base distribution (e.g., ‘plain.bst’, ‘acm.bst’)
     misc/       single-file styles
     pkg/       name of a package
   doc/         additional documentation
   dvips/       ‘.pro’, ‘.ps’, ‘psfonts.map’
   fonts/       font-related files
    type/         file type (e.g., ‘tfm’, ‘pk’)
     mode/          type of output device (types ‘pk’ and ‘gf’ only)
      supplier/       name of a font supplier (e.g., ‘public’)
       typeface/        name of a typeface (e.g., ‘cm’)
        dpinnn/           font resolution (types ‘pk’ and ‘gf’ only)
   metafont/    Metafont (non-font) input files
    base/        base distribution (e.g., ‘plain.mf’)
    misc/        single-file packages (e.g., ‘modes.mf’)
    pkg/           name of a package (e.g., ‘mfpic’)
   metapost/    MetaPost input files
    base/        base distribution (e.g., ‘plain.mp’)
    misc/        single-file packages
    pkg/           name of a package
    support/     support files for MetaPost-related utilities (e.g., ‘trfonts.map’)
   mft/         ‘MFT’ inputs (e.g., ‘plain.mft’)
   tex/         TeX input files
    format/         name of a format (e.g., ‘plain’)
     base/        base distribution for format (e.g., ‘plain.tex’)
     misc/        single-file packages (e.g., ‘webmac.tex’)
     local/       local additions to or local configuration files for format
     pkg/           name of a package (e.g., ‘graphics’, ‘mfnfss’)
    generic/     format-independent packages
     hyphen/      hyphenation patterns (e.g., ‘hyphen.tex’)
     images/      image input files (e.g., Encapsulated PostScript)
     misc/        single-file format-independent packages (e.g., ‘null.tex’).
     pkg/           name of a package (e.g., ‘babel’)
   web2c/        implementation-dependent files (.pool, .fmt, texmf.cnf, etc.)
```
for each of the folders listed by kpsewhich.

**Comment by kiryph** [comment]
### `[I` lists matches of current file twice if included via the main file

When I press `[I` on `\vec` in `chapter1.tex` of my given example, I get following result:
```
main.tex
  1:    3 \renewcommand{\vec}[1]{\mathbf{#1}}
  2:    7 $\vec{a}\cdot\vec{b}$
main.tex (includes previously listed match)
chapter1.tex
  3:    4 $\vec{a}\cdot\vec{b}$
chapter1.tex
  4:    4 $\vec{a}\cdot\vec{b}$
```
Result 4 is the same as result 3. Is this a vim bug or something we could improve?

Running `:checkpath!` in `chapter1.tex` returns
```
--- Included files in path ---
main.tex
main.tex -->
  chapter1.tex
  chapter1.tex -->
    main.tex  (Already listed)    
```

I think `chapter1.tex` should be marked as the current file and should not be evaluated another time.
 
In my opinion this is related to cyclic includes. Vim does not do this infinitely but recognizes this iusse one iteration too late for the current file.

**Comment by kiryph** [comment]
Just for the record: another issue someone might come cross is https://github.com/romainl/vim-qf/issues/69 when one uses the plugins [vim-qf](https://github.com/romainl/vim-qf) and [vim-qlist](https://github.com/romainl/vim-qlist) from romainl.

**Comment by kiryph** [comment]
### Slow `:checkpath!`

Running `:checkpath!` in a larger project takes minutes to finish for me:
```
--- Included files in path ---
/Users/kiryph/Manuscripts/thesis/subfiles/../main.tex
~/Manuscripts/thesis/subfiles/../main.tex -->
  /Users/kiryph/Manuscripts/thesis/subfiles/main_KOMAoptions.tex
  /Users/kiryph/Manuscripts/thesis/subfiles/main_shared_preamble_part.tex
  /Users/kiryph/Manuscripts/thesis/subfiles/setuptitle.tex
  ~/Manuscripts/thesis/subfiles/setuptitle.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/main_preamble_symbols.tex
  /Users/kiryph/Manuscripts/thesis/subfiles/coverpage.tex
  /Users/kiryph/Manuscripts/thesis/subfiles/plan.tex
  ~/Manuscripts/thesis/subfiles/plan.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/bastardtitle.tex
  ~/Manuscripts/thesis/subfiles/bastardtitle.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/officialtitle.tex
  ~/Manuscripts/thesis/subfiles/officialtitle.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/abstract_de.tex
  ~/Manuscripts/thesis/subfiles/abstract_de.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/abstract_en.tex
  ~/Manuscripts/thesis/subfiles/abstract_en.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/tableofcontents.tex
  ~/Manuscripts/thesis/subfiles/tableofcontents.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/preface.tex
  ~/Manuscripts/thesis/subfiles/preface.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/listofpublications.tex
  ~/Manuscripts/thesis/subfiles/listofpublications.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/chapt_1.tex
  ~/Manuscripts/thesis/subfiles/chapt_1.tex -->
    ../main.tex  (Already listed)
    special_topic  NOT FOUND
  /Users/kiryph/Manuscripts/thesis/subfiles/chapt_2.tex
  ~/Manuscripts/thesis/subfiles/chapt_2.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/chapt_3.tex
  ~/Manuscripts/thesis/subfiles/chapt_3.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/chapt_4.tex
  ~/Manuscripts/thesis/subfiles/chapt_4.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/chapt_5.tex
  ~/Manuscripts/thesis/subfiles/chapt_5.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/chapt_6.tex
  ~/Manuscripts/thesis/subfiles/chapt_6.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/chapt_outlook.tex
  ~/Manuscripts/thesis/subfiles/chapt_outlook.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/chapt_introduction.tex
  ~/Manuscripts/thesis/subfiles/chapt_introduction.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/chapt_results.tex
  ~/Manuscripts/thesis/subfiles/chapt_results.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/appendix.tex
  ~/Manuscripts/thesis/subfiles/appendix.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/bibliography.tex
  ~/Manuscripts/thesis/subfiles/bibliography.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/publications.tex
  ~/Manuscripts/thesis/subfiles/publications.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/acknowledgements.tex
  ~/Manuscripts/thesis/subfiles/acknowledgements.tex -->
    ../main.tex  (Already listed)
  /Users/kiryph/Manuscripts/thesis/subfiles/backcover.tex
  ~/Manuscripts/thesis/subfiles/backcover.tex -->
    ../main.tex  (Already listed)
```

**Comment by lervag** [comment]
Ok, there are two issues now:

1. Cyclic includes lead to (I hypothesize) lags for large projects and double parsing of current file. I'll addres this here.

2. Better setting of the `path` variable. I'll ignore this for now. Please open a new issue if you're interested in continuing this discussion.

----

So, how to solve the cyclic includes. The problem is that we are considering includes from two directions. That is, in most programming languages, a "sub module" or similar will be the one to include the parent project. However, now we are turning this upside down.

A possible solution:

1. We use a general `&include` regexp that also parses `\documentclass[...]{subfile}` and `TeX root` and similar.

2. We add a "hack" to the `&includexpr` that keeps track of included files. E.g.: Add a stack that is emptied if ~1 second has passed when invoking the `&includeexpr`. I think we could use an algorithm like this:

    ```
    if now() - stack.time > 1 second
      stack.clear()
    endif

    if % is in stack
      return ''
    else
      stack.add(%)
    endif
    ```

What do you think about this? Do you see a reason why this would not work?

**Comment by kiryph** [comment]
I agree that the discussion for the `'path'` setting should be done in a separate issue.

Regarding cyclic includes: First of all I think that c header files are also included more often (include guards) and it is also possible to get cyclic includes. Right now I do not have a nice minimal example for this.
I want to say this might be a problem not specific to vimtex/latex and could also be discussed on the vim_dev mailing list.

Just to say it again, I think `:checkpath!` should treat the current file as `already listed/included` (-> vim_dev mailing list).

I am not sure about your hack and also a regex to parse the project.

If one uses https://github.com/romainl/vim-qlist which offers an alternative behaviour for `[I`, the implementation of <Plug>QlistIncludefromtop could clean up the quickfixlist as well.

**Comment by kiryph** [comment]
Thanks for your efforts. But it did not improve the time for `:checkpath` for my large project:

1. open file and exit: **3.051sec**
```
~/Manuscripts/thesis master*
❯ time vim -c ":quit" main.tex
mvim -v -c ":quit" main.tex  2.50s user 0.78s system 107% cpu 3.051 total
```

1. open file, run `:checkpath`, and exit: **1:25.86** (85.86sec)
```
~/Manuscripts/thesis master*
❯ time vim -c ":checkpath | quit" main.tex
mvim -v -c ":checkpath | quit" main.tex  53.58s user 25.41s system 91% cpu 1:25.86 total
```

**Comment by lervag** [comment]
That's strange. For me, the latest commits give a very clear performance improvement because the old implementation seemed to result in a call to `kpsewhich` for every included file, regardless. But perhaps I've missed something. Could you provide a minimal example that is similar to your large project with regard to the structure of main file vs included files?

---

Btw., do you still get cyclic includes? The latest version should have solved that, and I'm curious how this works for other people.
