### ISSUE TITLE
Engine selection not re-read on compiler stop & restart?

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#1149]
# Engine selection not re-read on compiler stop & restart?

Probably a non-issue, but I report it anyway... it seems that the comment line selecting the engine are read only at the start of the vim session, and further changes are not taken into account. 

I was doing some compatibility check across engines --- and got quite confused until I tested this file: 
```tex
\documentclass{article}
\usepackage{ifluatex, ifpdf}
\begin{document}
\Huge
\ifluatex
   Running LuaLaTeX
\else
    \ifpdf
         Running pdfLaTeX  
     \else
        Running plain LaTeX
     \fi  
\fi
\par
\end{document}
```

with `gvim -u minivimrc detectengine.tex`, where  rhe `minivimrc` is:  

```vim
    set nocompatible
    let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
    let &rtp .= ',~/.vim/plugged/vimtex/after'
    filetype plugin indent on
    syntax enable
```

Adding a line 

```tex
%! TeX program = lualatex
```

and the stopping, cleaning (`<leader>ll` `<leader>lc`) and restarting will still use `pdflatex`. Exiting and re-editing the file, being careful about making some changes before restarting the compiler with `<leader>ll` will work as expected.

Is this by design (i.e., is it difficult to recheck the engine directive on compiler restart?)?

**Comment by lervag** [comment]
Yes, you are correct: The comment line is read when you open the buffer. However, you can do `\lx` or `:VimtexReload`. This will reload vimtex and thus also reparse the program directive.

I don't think it is very difficult to reparse the engine directive, but I am curious if that is really necessary. How often do you expect to change it?

**Comment by Rmano** [comment]
Perfect, I didn't know about `\lx`. 

I normally do not change engine mid-way; I discovered this just when try to create a file compilable on both `lualatex` and `pdflatex`, and trying to look at differences.

`\lc\lx` solves the problem fully. Thanks.
