### ISSUE TITLE
Request for example documentation on  project's wordcount from texcount on statusline

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1152]
Hi,

I am loving vimtex, three months into my PhD thesis writing.

My university has a word limit for theses and I would like to keep an eye on the word count as I write more chapters, and make continuous adjustments to writing by factoring this information into my brain.

In the help section of vimtex, it is claimed that you support word count through ```texcount.pl```. However, in an otherwise excellent documentation, the word count feature is rather sparse. The issue list discussing this is tiny too.  In the help documentation, I found only two commands, ```:vimtexcountwords``` and ```:vimtexcountletters```. However, it is a bit wearisome to remember to manually invoke the command. When the command is executed, the output shows up in the console buffer and disappears. 

This is rather inconvenient. I have to remember the number from the last run. Errr.....was it __20352__ words or __20852__ words? This adds mental effort to already strained minds trying to write technical content. In this case, I think it would be brilliant if the project's word-count alone is integrated into the status-line (updated on every save maybe), so that users can simply glance at it whenever required for any tex project.  

My vimscript skills are virtually non-existent since I have not attempted writing something like this before. Therefore, may I ask your help in  providing some minimal example in the documentation on how to integrate this to a) standard status-line and b) vim-airline.  Much appreciate it if you could consider this request.

**Comment by lervag** [comment]
I'm happy that you enjoy using vimtex!

The `:VimtexCount*` family of commands should all open a new window where the information should be presented, see screenshot below:

![screen](https://user-images.githubusercontent.com/998898/41959717-11d42a7a-79ee-11e8-8852-a15b66efbae4.png)

As such, it should not disappear unless you close the window. If this is not the behaviour that you see, then please make sure you use the latest version of vimtex; if it persists, then describe minimal vimrc and LaTeX file to reproduce.

I can see that having a more available function that could be used e.g. in statuslines could be useful. This does not exist as of now. Let's discuss that after we have resolved the first part mentioned above.

**Comment by krishnakumarg1984** [comment]
@lervag  thank you for your response. 

Sorry, I wasn't clear because of my poor choice of words earlier. yes, indeed the behavior you describe is what I get.  What I meant was, this window is 'ephemeral', i.e. it disappears upon pressing ```q```, unlike traditional buffers, which requires a more calculated two-stroke key press or a colon command. 

The point I was raising is more of an inconvenience during a typical usage scenario.  Let's say I wrote a fair bit of a chapter for my thesis, and I wish to have a sense of the word count. I need to invoke the command ```:VimtexCountWords```. I take a peek at the words, quickly hit ```q``` to close it because I don't want a window to take real-estate on my screen distracting me from writing.  So, I think in my mind "okay, so we are now upto __3265__ words. great." And then, over the next two days, I write a few more sections, but I can't remember how much were I "Was it __3600__ something or __3800__ something?  Plus, I have to remember to invoke the command. 

The information presented by ```:VimtexCount```, albeit quite informative and provides a nice summary, is a bit too much for vast majority of cases.  Let me substantiate this claim. Having written a couple of journal articles in the past, I am going to hazard a guess that most journals (particularly, Elsevier and IEEE) have a word-limit. Similarly, for theses, most universities specify a word limit.  So, it would provide a better orientation for the author to continuously adjust their writing pattern, if a constant feedback on the word count is available in the status line.  I can't praise enough of how much ```vim-airline```'s ```vimtex``` integration has helped me through the ```mvc``` status-flags.

To provide the project's word count, I propose something along the following lines

```texcount -sum -merge -nosub -q -1  main.tex```

and concatenate the resulting positive integer with the string ```words``` to show somewhere in the status line for example,

```3097 words```

I am able to successfully run the above command at the shell prompt. What we need help with is to intelligently pass the ```main.tex``` correctly to ```texcount``` to obtain the project-wide word-count irrespective of being any buffer (in a typical multi-file project).  The tricky bit being correct determination of the ```root``` file. Simply one does need to hook into ```vimtex``` sophisticated root-file detection sequence to address this. The second tricky thing would be to address user-plugins for status-lines.  Maybe the right answer would be to provide example documentation for vanilla status line and for vim-airline, and invite documenation pull-requests from knowledgeable members to help with other status-line plugins like ```lightline``` etc.  

What do you think?

**Comment by lervag** [comment]
I'm going to leave the statusline integration to someone else, but I've now updated the code to make it easier to get the desired information. I.e., to get the wordcount, you can now simply call `echo vimtex#misc#wordcount()`

Note, for integration with e.g. airline or lightline or similar, you should cache the count and update only at a certain interval. Else the calls to `texcount` will lead to a noticable lag. But as I said, I have to leave the integration to someone else, because I don't use or have much knowledge of these plugins.

As a simple example, one may use this in a statusline like this:

```vim
let &statusline = 'count is %{vimtex#misc#wordcount()}'
```

But of course, one should never do this, since the function only makes sense in `tex` files with the vimtex plugin active. As such, this should only be used by relatively experienced users.
