### ISSUE TITLE
Load configuration in /after/ftplugin/

### ISSUE THREAD

**Issue by mathsaey** [lervag/vimtex#1155]
In order to keep my `.vimrc` clean, all of my language specific configuration is stored inside various `.vim/after/ftplugin/lang.vim` files, as described [in vim wikia](http://vim.wikia.com/wiki/Keep_your_vimrc_file_clean).

Vimtex options which are initialized with [`vimtex#init_options()`](https://github.com/lervag/vimtex/blob/master/autoload/vimtex.vim#L26) seem to be initialized before the `after/ftplugin/tex.vim` file gets read, which means that options set in this file are only seen by vimtex after `VimtexReloadState` is called. Since not all options are initialized by `init_options`, it can be tricky to figure out how to solve this issue; figuring out that `VimtexReloadState` is enough to fix the issue is not trivial either.

It would be nice if it was possible to only initialize the vimtex options after the `after/ftplugin/tex.vim` is loaded. If this is not feasible, I would at least document this behavior and a workaround (calling `VimtexReloadState` in `after/ftplugin/tex.vim`)  somewhere.

I didn't provide a `.vimrc` to reproduce this issue, since this is more of a feature request. If I'm wrong and if this is actually unintended behavior, let me know and I'll try to produce a minimal configuration for you.

**Comment by lervag** [comment]
No, sorry, this does not make sense. `after/ftplugin` files are sourced _after_ the normal `ftplugin` files, and vimtex is exactly that. Which means that a lot of the important options that should be defined before vimtex is initialized will not be set.

If you want to separate your configuration, then instead put it in `.vim/ftplugin/lang.vim`, because this file should be sourced _before_ the various filetype plugins.

**Comment by mathsaey** [comment]
> If you want to separate your configuration, then instead put it in .vim/ftplugin/lang.vim, because this file should be sourced before the various filetype plugins.

Okay, this seems to be a case of me being stupid. I symlinked my language specific configuration to `/after/ftplugin` a long time ago, and never considered `ftplugin`. Sorry for wasting your time and thanks for the quick reply 🙂 .

**Comment by lervag** [comment]
No problem! :)
