### ISSUE TITLE
dse mapping does not delete arguments (optional or mandatory)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1156]
Vimtex's ```dse``` mapping does not delete any mandatory or optional arguments used in the start of any environment.

1. minimal vimrc is given below.

    ```vim
    set nocompatible
    let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
    let &rtp .= ',~/.vim/bundle/vimtex/after'

    filetype plugin indent on
    syntax enable
    ```

2. Minimal ```mwe.tex``` file to replicate the issue is given below:
    ```
    \documentclass{article}
    \usepackage[inline]{enumitem}
    \begin{document}

    Text before list.
    \begin{itemize}[itemsep=0pt]
         \item My first in list.
         \item My second in list.
    \end{enumerate}
    \end{document}
    ```

3. Invoke vimtex on this example with with ```vim --servername VIM -u vimrc mwe.tex``` . Now, with the cursor in normal mode on any of the lines within the ```itemize``` environment, if we press ```dse```, it leaves the source code in the following state
   ```
    Text before list.
    [itemsep=0pt]   <--- this is an artifact and should have been removed by dse
         \item My first in list.
         \item My second in list.
   
    ```

The expected behavior is to completely get rid of all tex-related text including options in square-brackets, additional arguments for custom environments in braces and trailing comments in the line containing ``` \begin{itemize}[itemsep=0pt]``` (in this case itemize, but generically for any environment).

**Comment by lervag** [comment]
Thanks, I think this should work more as expected now. Note, though: It is not so easy to parse LaTeX comands: There is no way of knowing how many arguments will be "eaten" by a command. E.g:

```tex
\begin{env}[opts1][opts2]{arg1}{arg2}
...
\end{env}
```

Here `env` could consume everything, or it could consume perhaps only `opts1`, or until and including `arg1`. There is no way to know without knowing something about `env`.

This update makes `dse` consume everything
