### ISSUE TITLE
Improvement of text objects for nested environments?

### ISSUE THREAD

**Issue by vneiger** [lervag/vimtex#1159]
Hello,

First, let me thank you for the excellent plugin and the constant effort of improving it and answering people requests or comments.

I find the text objects defined by vim extremely helpful, and I am wondering about a possible small improvement. I prefer to describe the issue by an example; say I have the following piece of tex:
```
\begin{minipage}{0.5\textwidth}
   \begin{itemize}
       \item blo blo
   \end{itemize}
   \begin{itemize}
       \item bla bla
   \end{itemize}
\end{minipage}
```
My cursor is on the first "blo". Then, for some reason I want to select the inner minipage environment: I would expect that pressing "vieie" would do it, but it does not, it stays in the itemize. However, "vaeae" does work and select the outer environment.

Why would one expect "vieie" to do this? Because this is how it usually works with more basic vim text objects, such as in:
``` (this is a (bracket) inside a parenthesis)```
then, if your cursor is on the word bracket, pressing either "vi)i)" or "va)i)" will both "go up one level" and select the inside of the outer parenthesis.

Do you think having "vieie" and "vaeie" (and maybe similar behavior for commands and delimiters) behave like this is feasible?
Thank you again.

PS : I refer to https://github.com/lervag/vimtex/issues/687 for earlier discussion about making "vaeae", "vadad", and "vacac" work. I agree these work well. I am wondering about the similar "vieie", "vieae", "vicic", etc...

**Comment by lervag** [comment]
I agree this is a nice addition. I think my update should work, but please let me know if you notice something that's not working as it should. I'm not very surprised if I've missed a corner case or two.

**Comment by vneiger** [comment]
A few attempts (probably missing some corner cases as well) show the right behavior. Thank you very much for the quick update!

**Comment by lervag** [comment]
No problem; thanks for suggesting the change :)
