### ISSUE TITLE
Tag navigation needs to use upper-case Word instead of lower-case word

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1161]
### Background
Throughout the text, there are labels to equations, tables etc. for which an accepted convention among TeX writers is the following

```\label{eq:massenergy}``` , ```\label{tbl:exptresults}``` etc.  

These can be cross-referenced later in text, eg ```referring to equation~\ref{eq:massenergy}, we can see that ..... blah ...blah ...```

Sometimes, I want to change the equation being referenced, say I want to replace ```{eq:massenergy}``` with ```{eq:workenergyequivalence}```. If my cursor is already somewhere in the word  ```massenergy```, I can do ```ciw``` and start typing the desired label. But in this case, it deletes the entire content within braces, i.e. becomes equivalent to ```ci}```.

So I have set ```:``` as a word separator using `iskeyword-=:`.

However, this broke tag navigation, i.e. ```C-]``` does not work anymore. When I am anywhere in the text within the braces ```{}``` of the ```ref``` command,  I get a ```E426: tag not found: eq:``` or ```E425: tag not found: massenergy```.  Before setting the  `iskeyword-=:`.option, tag navigation worked flawlessly. 

### Possible Cause
I suspect that the tag regular expression parser looks for `word` rather than `Word`.  The only legal tag separator in `latex` syntax (for `ref`,`cref` and friends) is comma `,` . Hence, incorporating this change should not hopefully break anything for existing documents. 

### Steps to reproduce

1.  `minivimrc` file

    ```vim
    set nocompatible
    let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
    let &rtp .= ',~/.vim/bundle/vimtex/after'

    filetype plugin indent on
    syntax enable

    set iskeyword-=:

    ```

2. A minimal `.tex` file, such as:

    ```tex
    \documentclass{minimal}
    \begin{document}

    Equation~\ref{eq:massenergy} is the famous mass-energy relationship. Blah.... 
   \begin{equation}{eq:massenergy}
         e = mc^2
   \end{equation}

    \end{document}
    ```
3. `~/.ctags` file

```
--langdef=bib
--langmap=bib:.bib
--regex-bib=/^@[A-Za-z]+\{([^,]*)/\1/b,bib/

--langdef=bibtex
--langmap=bibtex:.bib
--regex-bibtex=/@string\{([^ "#%')(,=}{]+)/\1/s,BibTeX-Strings/i
--regex-bibtex=/@(article|book|booklet|inbook|incollection|inproceedings|manual|masterthesis|misc|phdthesis|proceedings|techreport|unpublished)\{([^,]+),/\2/e,BibTeX-Entries/i
--regex-bibtex=/[[:space:]]*author[[:space:]]*=[[:space:]]*("([^"]+)"|\{([^\}]+)\})[[:space:]]*,?[[:space:]]*$/\2\3/a,BibTeX-Authors/i

--langdef=tex2
--langmap=tex2:.tex
--regex-tex2=/\\label[ \t]*\*?\{[ \t]*([^}]*)\}/\1/l,label/
```

4. Start min with  `vim --servername VIM -u minivimrc mwe.tex` 
__Expected Behaviour__ : When pressing `C-]` in any character within braces of ```\ref{eq:massenergy}```, vimtex causes cursor to jump to the corresponding label in the project
__Observed Behaviour__ : When pressing `C-]` in any character within braces of ```\ref{eq:massenergy}```, I get a ```E426: tag not found: eq:``` error and cursor does not jump to the tag in braces.

I suspect the problem is due to a combination of the regex in the ```~/.ctags``` file (along with possibly vim or vimtex's tag parser). However, the complicated regex syntax makes my head spin. Also, using `:` is just a convention and not a universally required standard. Maybe the user prefers semicolon `;` or some other digraph/accented character in their language or any other unicode symbol.  Tag navigation should not break on this.  Hence, the regex should be written as the ```boolean inverse``` of current regex, i.e. any set of character within braces to the ```ref``` family of commands, separated the comma ```,``` should be considered a valid tag.

How can we widen the net so that this can be implemented? Perhaps this can be clarified in the documentation for the benefit of other users too?

**Comment by lervag** [comment]
This is not really a vimtex specific question. It is a Vim general question. Notice that `ctags` is mentioned in `:h vimtex-non-features` under the sub section "Tag navigation". However, one could improve that particular note if there is something sensible to add.

**Comment by krishnakumarg1984** [comment]
Do you have a clue of what an appropriate regex in this case may be? Or if you think this is out of scope, would you encourage me to ask vi.stackexchange?

**Comment by andymass** [comment]
Ctrl-] uses the iskeyword to determine what the current word under the cursor is.  In this case since you have excluded `:`, vim searches for either `eq` or `massenergy`.  There's not much you can do besides remapping Ctrl-], which is a totally valid approach.  Note that `vi{<c-]>` works as you expecct.

**Comment by lervag** [comment]
Yes, I think @andymass is pretty much right. I don't think the problem is the regex in the `.ctags` file. You could change the regex to exclude the initial `fig:`, `eq:`, etc, but that just feels wrong.

Instead, I think you should have `:` as part of the `iskeyword`. You say you remove it in order to do `ciw` to change only the "later" part of the label, i.e. to ignore the `eq:` part (and similar). In this case, I would rather change how you do this. Instead of `ciw` when cursor is on `example` in `eq:example`, you could do `evF:c` (or any number of similar things). I know itVim experience.

A different approach would be to make a simple mapping to toggle the `iskeyword` to remove/add `:`.

In any case, I feel like we should keep things as they are right now, unless you have a specific idea of how I should update the docs.

**Comment by krishnakumarg1984** [comment]
No issues. Thanks you @lervag and @andymass for the valuable suggestions. I shall try and adopt one of these methods

**Comment by lervag** [comment]
No problem :)
