### ISSUE TITLE
vimtex not using specified leader

### ISSUE THREAD

**Issue by fonnesbeck** [lervag/vimtex#1167]
I have a comma specified as my leader character in my neovim configuration file, but when I try passing vimtex commands with it, they do not execute. However when I use a backslash, the command works. This seems to suggest that vimtex is somehow not using my global configuration. 

Using vimtex as installed from vim-plug.

**Comment by lervag** [comment]
vimtex uses `maplocalleader`, not `mapleader`. See `:h maplocalleader`.
