### ISSUE TITLE
Mupdf wont refresh on filechanges.

### ISSUE THREAD

**Issue by yuri0r** [lervag/vimtex#1171]
# Expected

Starting to compile while working on a `.tex` document (`\ll`) will open default Pdfviewer and refresh on saved changes (when in bottom left says "Compilation completed") .

# Observed

It  works perfectly fine for Evince and Zathura but not for MuPDF (sadly my favorite).

# Replicating

Minimal vimrc file used:

````vim
set nocompatible

call plug#begin('~/.vim/plugged')
    Plug 'lervag/vimtex'
call plug#end()

filetype plugin indent on
syntax enable
````

Minimal tex file used:

````tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}

````

File has been opened with:

```sh
vim --servername $USER -u .minrc min.tex
```

Tex file changed "World" to "Change" and saved. Then I close vim between each run while changing my default pdf viewer via nautilus (so that xdg-open would return different pdfviewer) as mentioned Evince and Zathura showed the changes immediately, MuPDF did not only on manual refresh (pressing r in mupdf).

Running on Ubuntu 18.04 using i3wm.

I compiled vim from source with the `-with-features=huge` flag. Also sorry if its hard-ish to read English is not my native language.

**Comment by lervag** [comment]
No problem, easy to read. Good issue report.

So, the reason that MuPDF does not work as expected for you is that MuPDF does not automatically update on its own. We need some more magic for that, in particular, we need to use `xdotool` as an external dependency to force refresh. This should work automatically if you install `xdotool` and then set MuPDF as your pdf viewer with `let g:vimtex_view_method = 'mupdf'` in your vimrc file. See also `:help vimtex-view` and related help sections.

**Comment by xarthurx** [comment]
@lervag 
For windows user, is there other ways to do auto-updates?
For instance, use autoHotKey instead of xdotool?

Really like mupdf but cannot auto refreshing the pdf is really annoying.

**Comment by lervag** [comment]
@xarthurx Please open new issues instead of commenting on old and resolved issues with unrelated (or semi-related) questions.
