### ISSUE TITLE
How to autofocus on skim after \lv

### ISSUE THREAD

**Issue by znculee** [lervag/vimtex#1177]
Thanks for your great plugin. I'm using OSX10.13 with skim and macvim. Everything works fine, but I want the skim be focused after pressing \lv. Is there any configuration can make that?

**Comment by lervag** [comment]
I'm sorry, but I don't really know. Perhaps @clason is able to help here?

**Comment by lervag** [comment]
Thanks, we'll continue this discussion in #1178.
