### ISSUE TITLE
vimtex-toc open/toggle works only once

### ISSUE THREAD

**Issue by mirzachi** [lervag/vimtex#1181]
I receive the following error after I try to open/toggle toc multiple times. In other words, it works only when I open/toggle it for the first time, afterwards it produces the error shown below. I use the standard mappings from the vimtex doc to open/toggle toc: ` <localleader> lt and <localleader> lT`. Exiting and entering VIM enables again one time toc opening/toggling.

```
Error detected while processing function 73[7]..61[5]..vimtex#parser#toc[2]..vimtex#parser#toc#parse[47]..201:
line    6:
E734: Wrong variable type for .=
Error detected while processing function 73[7]..61[5]..vimtex#parser#toc:
line    5:
E712: Argument of filter() must be a List or Dictionary
Error detected while processing function 73[7]..61:
line   12:
E712: Argument of filter() must be a List or Dictionary
Press ENTER or type command to continue
```
The project that I am currently working on consists of multiple files, so I do not know exactly what to post here. If you require that kind of input as well, please be more specific what might be an issue so that I can provide the necessary parts for the .tex files as well.

This is an excerpt from the .vimrc file that I am using concerning vimtex only:

```
" close braces at the end                       
let g:vimtex_complete_close_braces = 1
" should allow recognizing tex files without preamble
let g:tex_flavor = 'latex'
" set localleader map key as a shortcut for some vimtex stuff
let maplocalleader="\<space>"
```

**Comment by lervag** [comment]
I can't reproduce this, sorry. I can see where the error comes. It seems to be due to section titles that spans multiple lines. But I have a test for this that works for me.

Could you perhaps make a copy of a document where you are experiencing this and reduce it (if desired) and send it to me? I don't care about the contents, so please just rewrite or remove whatever content is there that is not necessary for you to reproduce the problem.

**Comment by mirzachi** [comment]
Since the project consists of multiple files, it is pretty inconvenient to post all of them here. Therefore, I sent a zipped project directly to your email via some additional explanations.

**Comment by lervag** [comment]
As I wrote on email, I confirm that I've reproduced the problem with your example. The problem is with sections without titles, i.e.:

```tex
\section{}
Some text here
```

I'll look into it now or later when I get the time.

**Comment by mirzachi** [comment]
Thanks for pointing that out. Indeed, there was an empty chapter `\chapter{}` statement.

When I put some content into it, toc toggling/starting has started working perfectly fine again.

**Comment by lervag** [comment]
No problem. I think I've solved the original problem as well, now. :)
