### ISSUE TITLE
Disabling inline math

### ISSUE THREAD

**Issue by nwoeanhinnogaehr** [lervag/vimtex#1182]
I find that the inline math mode (while definitely cool) is often a hassle. The biggest issue that I have is it's hard to tell where the cursor is because special characters are folded. Also, when typing inside of a math block, my cursor will sometimes appear to be multiple characters to the right of where it should be (I think this is equal to the number of characters that have been hidden). Finally, some formulas seem to break it, for example:
```
Y(k)=\sum_{n=1}^My(n)e^{-2\pi ikn/M}
```
Bugs aside, since the typeset math is already visible in the preview window, I would like to disable any special formatting within the code window. It seems that the only way to disable it is by turning off syntax highlighting entirely, which is less than ideal.

My apologies if this is already possible. I read through the docs but was unable to find anything.

P.S. Thanks for a great plugin. Everything else it does is fantastic.

**Comment by lervag** [comment]
This is not due to vimtex, but due to the internal LaTeX syntax plugin that ships with Vim (and neovim). You can control this feature with `g:tex_conceal`, see `:h g:tex_conceal` for help. See also `:h conceal`, `:h conceallevel` and `:h concealcursor` for related Vim settings.

> P.S. Thanks for a great plugin. Everything else it does is fantastic.

Thanks! :)
