### ISSUE TITLE
Plug (plugin manager) errors

### ISSUE THREAD

**Issue by theova** [lervag/vimtex#1187]
Hello!

__Observed behaviour:__
When using nvim with vimtex and [Plug](https://github.com/junegunn/vim-plug), I get an error right when starting 
```bash
nvim -u config.vim test.tex
```

Error:
```vim
Error detected while processing function vimtex#init[5]..<SNR>11_init_buffer:
line   30:
E121: Undefined variable: g:vimtex#re#tex_include
E15: Invalid expression: g:vimtex#re#tex_include
```
Otherwise, vimtex runs fine.

__Expected behaviour:__ 
No errors are produced.

### minimal `config.vim` file
The following `config.vim` is working:
```vim
  " set runtimepath
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
```
Whereas this `config.vim` file which is using `Plug` produces the error:
```vim
  " set runtimepath
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath

" set up Plug (plugin manager)
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source ~/.vimrc
endif

call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

set nocompatible

filetype plugin indent on
syntax enable
```

### Minimal `test.tex` file:

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Versions/ OS
I'm using the latest versions of `vimtex`, `Plug` and `nvim` (available for ArchLinux).

Thank you very much for the development of vimtex, it's amazing!

**Comment by lervag** [comment]
Hi! I'm sorry, but I can't reproduce this. I've pushed my test code based on your post; please update vimtex and confirm if you can reproduce with the same files.

Note: The `if empty... endif` code should not be important. Also, `vim-plug` will do `filetype...` and `syntax enable` for you, so those lines are not necessary. Further, `set nocompatible` is not necessary with neovim.

Note that I'm also on Arch, so it should be possible to find the solution to this.

**Comment by theova** [comment]
I can reproduce it in the following way:
1) `nvim -u ~/.vim/bundle/vimtex/test/issues/1187/minivimrc`
2) `:PlugInstall` (since my pluggins are in `~/.vim/plugged/`, I have to install vimtex to this location)
3) `cp ~/.vim/bundle/vimtex/test/issues/1187/minimal.tex ~/.`
4)  `nvim -u ~/.vim/bundle/vimtex/test/issues/1187/minivimrc`

**Comment by lervag** [comment]
Strange. I can not reproduce.

Can you provide the output of the following actions?

1. Inside vim and vimtex (on minimal example): `:VimtexInfo`
2. In terminal:

    ```sh
    nvim -v

    # With normal configuration (not minimal)
    nvim +"checkhealth vimtex"
    ```

Finally, could you test if things work as expected with normal Vim?

**Comment by theova** [comment]
Of course:
### `:VimTexInfo`
```vim
System info
  OS: Linux 4.17.12-arch1-1-ARCH
  Vim version: NVIM v0.3.1
  Has clientserver: true
  Servername: /tmp/nvimQu56EN/0

vimtex project: minimal
  base: minimal.tex
  root: /home/theo
  tex: /home/theo/minimal.tex
  out: 
  log: 
  aux: 
  fls: 
  document class: minimal
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimQu56EN/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -pdf
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
```

### `nvim -v`
```bash
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Übersetzt von builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

          System-vimrc-Datei: "$VIM/sysinit.vim"
     Voreinstellung für $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```
### `nvim +"checkhealth vimtex"`
```vim

health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - OK: Zathura should work properly!
  - OK: Compiler should work!

```

### `vim -u minivimrc`
I get the same error again.

**Comment by lervag** [comment]
Huh. This is very strange. I can not reproduce with neither of Vim or neovim.

Are we on different packages, perhaps? You are using translated versions. Is this merely a side effect from your locale, perhaps?

**Comment by theova** [comment]
In deed, it is...
I set my locale to english, but it still remains the same (english error message updated in the first post).

Probably, I can locate the error a bit better. I manually downgraded vimtex and found out,
that the error appears since  90dd813c34548bfd6c4fd975e32a374f40536cd0, where as the version before runs without an error.

**Comment by theova** [comment]
Finally, I found the problem!

I had once copied some files to `~/.vim/autoload/vimtex/`. So the solution was to simply delete this folder.

I'm very sorry for this! I apologize for wasting your time.

Thanks a lot!

**Comment by lervag** [comment]
No problem, I'm happy you found the solution.

**Comment by lervag** [comment]
If I'd been a little bit more clever, I would have suggested that you copy the output of `:scriptnames` for the minimal example here. I think I would have recognized the problem then.
