### ISSUE TITLE
Change math surroundings

### ISSUE THREAD

**Issue by zhuosongz** [lervag/vimtex#1188]
# Explain the issue

Hello! I have a question on the math delimiters. When using `csd` command, I want to change the delimiter to the `\lvert` and `\rvert`.  Which key I need to use when Change surrounding delimiter to `\bigl\lvert ... \bigr\rvert`. Thanks!

**Comment by lervag** [comment]
Given this:

```tex
$( [x] )$
```

where `[]` indicates the cursor position, `csd` will ask for input with the text `Change surrounding delimiter: ( ... )` and a prompt `> `. If you write `\lvert`, you will change to:

```tex
$\lvert [x] \rvert$
```

To add the modifiers, `\bigl ... \bigr`, you can use the `tsd` mapping. You are probably also interested in changing the `g:vimtex_delim_toggle_mod_list`, e.g.

```vim
let g:vimtex_delim_toggle_mod_list = [
  \ ['\left', '\right'],
  \ ['\bigl', '\bigr'],
  \ ['\Bigl', '\Bigr'],
  \ ['\biggl', '\biggr'],
  \ ['\Biggl', '\Biggr'],
  \]
```

For more info, please read `:h g:vimtex_delim_toggle_mod_list`, as well as `:h <plug>(vimtex-delim-toggle`.
