### ISSUE TITLE
problem with viewer method 'skim'

### ISSUE THREAD

**Issue by hrouault** [lervag/vimtex#1190]
# 'skim' viewer option

I tested with a minimal vimrc and a minimal tex file:

1. `vimrc` file:

    ```vim
    set nocompatible
    let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
    let &rtp .= ',~/.vim/bundle/vimtex/after'

    " Load other plugins, if necessary
    " let &rtp = '~/path/to/other/plugin,' . &rtp

    filetype plugin indent on
    syntax enable

    " Vimtex options go here
    let g:vimtex_view_method='skim'
    ```

2. A minimal `.tex` file:

    ```tex
    \documentclass{minimal}
    \begin{document}

    Hello World!

    \end{document}
    ```

3. I am using the last version of neovim `nvim -u vimrc mwe.tex`

 Then neovim hangs forever. If I remove the `let g:vimtex_view_method='skim'` line in the config file, neovim starts smoothly.
It used to work until very recently. I am not sure the problem came with an update of Skim or with an update of neovim, or vimtex?

If I hit `ctrl-C`, it stops hanging. `:VimtexInfo` does not seem to show anything meaningful about the problem.

**Comment by hrouault** [comment]
After I restarted my computer, I couldn't reproduce the problem. Sorry for opening the issue...

**Comment by lervag** [comment]
No problem :)

**Comment by daturkel** [comment]
I have this exact same issue, for what it's worth. I'm going to try a restart now, but using the latest neovim, latest skim, latest vimtex, the only thing I can do to make Vim stop slowing to a crawl at startup is disabling "let g:vimtex_view_method='skim'"

**Comment by lervag** [comment]
Strange! I suspect the reason is linked to the initialization code:

```vim
function! vimtex#view#skim#new() abort " {{{1
  " Check if Skim is installed
  let l:cmd = join([
        \ 'osascript -e ',
        \ '''tell application "Finder" to POSIX path of ',
        \ '(get application file id (id of application "Skim") as alias)''',
        \])

  if system(l:cmd)
    call vimtex#log#error('Skim is not installed!')
    return {}
  endif
  ...
```

I personally do not work with OSX and don't know osascript. Perhaps @clason would be able to help?

**Comment by clason** [comment]
This just gets the full path of `Skim.app`. Neovim can be slow to start on tex files, but that's usually related to syntax highlighting and getting the project structure. I've never had that specific problem.

What does `checkhealth` say? What's your OS (version)?

**Comment by daturkel** [comment]
> Is it still faster if you comment out let g:vimtex_view_method = 'skim'?

Actually, they now seem to be about the same. It's quite a bit faster than it was prior to the restart, admittedly. 

> What does checkhealth say? 

Interestingly, it says   `- WARNING: |g:vimtex_compiler_progname| (`nvr`) is not executable!`. I have `nvr` set to my compiler progname since I'm running neovim, but I see now that I didn't have the neovim-remote plugin installed. I installed it now, but checkhealth is still returning that error.

OS version is MacOS 10.15 Beta (19A558d).

The `osascript` line works. And the slowness is only really evident on opening an existing tex file.

**Comment by clason** [comment]
> Interestingly, it says - WARNING: |g:vimtex_compiler_progname| (nvr) is not executable!. I have nvr set to my compiler progname since I'm running neovim, but I see now that I didn't have the neovim-remote plugin installed. I installed it now, but checkhealth is still returning that error.

I assume that means `let g:vimtex_compiler_progname = 'nvr'` in `init.vim`. Is it in fact executable (from the terminal)?

> OS version is MacOS 10.15 Beta (19A558d).

That is relevant; Catalina introduces new sandboxing features.

**Comment by lervag** [comment]
To me it seems there is no real issue here. @daturkel If you think there still is a real issue, then please open a new issue and describe it. Please adhere to the issue template and provide a minimal example and explicit steps to reproduce, including both observed and expected behaviours.
