### ISSUE TITLE
Default keyword completion is slow with pdf_tex files

### ISSUE THREAD

**Issue by mgunyho** [lervag/vimtex#1192]
Hello,

If I have `pdf_tex` files generated by Inkscape as part of my document, I've found that keyword completion (the default that ships with Vim) becomes quite slow. In [this simple example](https://github.com/lervag/vimtex/files/2288058/autocomplete-mwe.zip), pressing `<C-n>` shows `scanning included file: ....pdf_tex` for around half a second for each of the files, or around twice as long when using `gvim`. On larger documents with more complicated diagrams, this becomes too slow for keyword completion to be usable.

I guess it could have something to do with these generated files having a lot of braces, although I haven't looked much into the search algorithm.

I tried to search the documentation for some way to exclude files with a specific extension from the search, but couldn't find an option for that. If such an option exists, it would be an easy solution to this problem.

I'm using Ubuntu 17.10 with Vim 8.0.

**Comment by lervag** [comment]
Thanks. I've fixed it now, I think.

**Comment by mgunyho** [comment]
Looks like it's fixed, thanks! I guess not searching commented-out files is a good idea anyways.

**Comment by lervag** [comment]
Exactly. My only worry is that the lookbehind regexp may be expensive, but I don't think it should be a problem; I think it is not called very often.
