### ISSUE TITLE
Automatically close environments

### ISSUE THREAD

**Issue by avonmoll** [lervag/vimtex#1193]
vimtex provides `vimtex-delim-close` and the handy `]]` mapping for Insert mode. Is it possible to have an environment close automatically after hitting <kbd>Enter</kbd>?

## (My + vimtex's) Current Behavior

I type `\begin{env}`<kbd>Enter</kbd><kbd>Enter</kbd>`]]` which yields:

```
\begin{env}

\end{env}%CURSOR%
```

but then I have to move my cursor back to be inside the environment.

## Desired Behavior

I type `\begin{env}`<kbd>Enter</kbd> and get:

```
\begin{env}
    %CURSOR%
\end{env}
```

## Existing Tools?

1. [This Atom package](https://github.com/Evpok/latex-autocomplete) has the type of behavior I'm requesting
2. [tex_autoclose.vim](https://www.vim.org/scripts/script.php?script_id=920) is similar to `vimtex-delim-close` in that it requires additional keypresses to close the environment
3. Ultisnips seems like it can do this, but I don't know enough about it to say whether it can handle any/all (even custom) environments

**Comment by lervag** [comment]
Yes! What you want is called snippets. Please read `:help vimtex-non-features`, in particular note the snippet part, and also read `:help vimtex-UltiSnips`.

With a snippet plugin, you should be able to easily create snippets where you type e.g.:

```
begin<expand-key>
```

to get

```
\begin{%CURSOR%}

\end{X}
```

when you type something, `X` will be expanded to the same thing automatically. And there is a key to go to the next position. The point is, this feature is a much more general feature that works equally well for almost any type of file, and as such, you should learn to use one of the dedicated plugins like UltiSnips or  neosnippet.

**Comment by avonmoll** [comment]
Using UltiSnips along with [honza/vim-snippets](https://github.com/honza/vim-snippets) I came up with the following, which produces the desired behavior.

```
priority -10

extends tex

snippet "\\begin\{(\w+)\}" "multiline begin{} / end{}" rbA
\begin{`!p snip.rv = match.group(1)`}
	$0
\end{`!p snip.rv = match.group(1)`}
endsnippet

snippet "(?<!^)\\begin\{(\w+)\}" "inline begin{} / end{}" riA
\begin{`!p snip.rv = match.group(1)`}$0\end{`!p snip.rv = match.group(1)`}
endsnippet
```

It turns out honza/vim-snippets comes with a very similar snippet which requires triggering, e.g.
`b`<kbd>Tab</kbd>`env`<kbd>Ctrl</kbd><kbd>j</kbd>. The inline snippet I wrote is slightly novel, in comparison, as it would expands things like `\begin{bmatrix}` inside of a long equation. 

Thanks for the advice!

**Comment by lervag** [comment]
I'm happy you find it useful! And thanks for the suggested snippet, I will try it out myself.
