### ISSUE TITLE
request to add llpp as a viewer

### ISSUE THREAD

**Issue by sharethewisdom** [lervag/vimtex#1199]
*background:* There's an open issue for my window manager (sway using wlroots) which somehow prevents mupdf to receive the keys send to it.

This caused me to look for a temporary alternative. I found [llpp](https://github.com/moosotc/llpp), which is able to receive keystrokes. I also really like its features and its scrolling behavior, which is why I think it may be a useful addition for vimtex anyway, if you're interested.

**Comment by lervag** [comment]
Thanks! Before I add a separate viewer implementation: How far do you get with the general viewer?

Also, if I add a separate viewer, it would be helpful if you could provide details on:

1. How do you run llpp?
2. How do you do forward search?
3. Does it support backward search, and if so, how does it work?

Have you tried Zathura, and if so, how would you compare llpp with it?

**Comment by lervag** [comment]
So, if you set:

```vim
let g:vimtex_view_general_viewer = 'llpp'
```

Then the viewer should work pretty well. Which other features do you want? Please explain them, and please explain how to achieve them with `llpp`.

**Comment by sharethewisdom** [comment]
Thank you for your response. I'll try to answer your questions in detail next week. Indeed I tried the general viewer before, but I've had problems having to recover my system, and I'm too busy to test the features properly. The viewer does save the view in the xml config file, which I don't really like, but it is why I at first glance chose llpp in favor of zathura, as I need to get things done now... I may have been too quick with this request.

**Comment by lervag** [comment]
That's OK, I'll close the issue in the mean time. Feel free to reopen with more details when you have the time.
