### ISSUE TITLE
RFC: Support external tools for formatting code e.g. latexindent.pl

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1200]
There are several suggestions for formatting latex source code or more generally 

> plaintext [...] which exports to some non-plaintext system. 

**Update**  I mainly have in mind a manuscript written in latex, not the source code of a latex package, also not specifically tikz or pstricks pictures.

The formatting style should make collaborative writing easier,  being VCS-friendly (ideally commits should be limited to actual changes, not unnecessary re-flows of paragraphs), diff friendly (cli with limited line lengths) and of course should be easy to read.

## Suggestions for formatting

- [Wikibook: LaTeX/Collaborative Writing of LaTeX Documents](https://en.wikibooks.org/wiki/LaTeX/Collaborative_Writing_of_LaTeX_Documents)
  > ### Directives for using LaTeX with version control systems
  > 
  > Avoid 'ineffective' modifications.
  > Do not change line breaks without good reason.
  > Turn off automatic line wrapping of your LaTeX editor.
  > Start each new sentence in a new line.
  > Split long sentences into several lines so that each line has at most about 80 characters.
  > [...]

- Article: [VCS friendly, patchable, document line wrapping by Cristopher Lemmer](http://dustycloud.org/blog/vcs-friendly-patchable-document-line-wrapping/) (add additional indentation for split sentences)
  > ```
  > If you do enough work in any sort of free software environment, you get used
  >   to doing lots of writing of documentation or all sorts of other things in
  >   some plaintext system which exports to some non-plaintext system.
  > One way or another you have to decide: are you going to wrap your lines with
  >   newlines?
  > And of course the answer should be "yes" because lines that trail all the way
  >   off the edge of your terminal is a sin against the plaintext gods, who are
  >   deceptively mighty, and whose wrath is to be feared (and blessings to be
  >   embraced).
  > So okay, of course one line per paragraph is off the table.
  > So what do you do?
  > ```

- Article: [Semantic linefeeds by Brandon Rhodes](http://rhodesmill.org/brandon/2012/one-sentence-per-line/) with quote from [1974 by Brian Kernighan](https://en.wikipedia.org/wiki/Brian_Kernighan) 

  > ### Hints for Preparing Documents
  > 
  > Most documents go through several versions (always more than you expected) before they are finally finished. Accordingly, you should do whatever possible to make the job of changing them easy.
  > 
  > First, when you do the purely mechanical operations of typing, type so subsequent editing will be easy.
  > - Start each sentence on a new line. 
  > - Make lines short, and
  > - **break lines at natural places, such as after commas and semicolons, rather than randomly.**  
  >   
  > Since most people change documents by rewriting phrases and adding, deleting and rearranging sentences, these precautions simplify any editing you have to do later.

As always, personal taste differs. However, tools can help to fix formatting and make it easier to follow a common style.

## External Tools 

- [latexindent.pl](https://github.com/cmhughes/latexindent.pl) (with recent additions in 3.5 for indented split sentences)
- machine learning toolkits for processing of natural language text for advanced sentence detection (OpenNLP, NLTK, ...)
- [BibTool](https://github.com/ge-ne/bibtool) (pretty printing incl. cleaning, sorting and aligning fields in bib files)

Note this issue started here as a [comment](https://github.com/lervag/vimtex/issues/544#issuecomment-245959879) with subsequent comments about machine learning toolkits for processing of natural language text and latexindent.pl release 3.5. The comments give also instructions how to use these tools.

### Generic vim plugins for formatting source code based on external tools

- [vim-autoformat](https://github.com/Chiel92/vim-autoformat) (1.3k stars)
- [neoformat](https://github.com/sbdchd/neoformat) (530 stars) (already configured for latexindent: [tex.vim](https://github.com/sbdchd/neoformat/blob/master/autoload/neoformat/formatters/tex.vim))
- [vim-codefmt](https://github.com/google/vim-codefmt) (500 stars)

Afaik, vimtex prefers to delegate features, if possible, to other plugins (which I would do so as well), e.g. snippets, linting, tag file generation.

We could still add documentation describing practices of formatting and how to achieve it conveniently in vim.

What is your opinion?

Do you know advantages which vimtex could provide compared to more generic formatting plugins such as vim-autoformat and neoformat?

(BTW: 5/8 open issues are from me: I hope I do not spam you; in total 69 of 996 issues are from me)

**Comment by kiryph** [comment]
My *current* personal style preference is in agreement with Christoper Lemmer described on dustycloud. Re-flowing one sentence should not introduce much commit noise because sentences should be short anyway.

IMHO two arguments againts the suggestions of what B. Rhodes and B. Kernighan said:

1. Inserting always a linebreak after semantic units, commas, colons and semi-colons makes the text lines very short and uneven. IMHO, this reduces the readability.
2. Tools cannot support you to detect semantic units or commas which can be used for a list or to separate a subordinate clause. You have to manage it manually.


### Dustycloud example formatted according to Lemmer + Kernighan

(linebreak after commas for subordinate clause, not lists)

```
If you do enough work in any sort of free software environment,
  you get used to doing lots of writing of documentation or all sorts of
  other things in some plaintext system which exports to some non-plaintext
  system.
One way or another you have to decide:
  are you going to wrap your lines with newlines?
And of course the answer should be "yes" because lines that trail all the way
  off the edge of your terminal is a sin against the plaintext gods,
  who are deceptively mighty,
  and whose wrath is to be feared (and blessings to be embraced).
So okay,
  of course one line per paragraph is off the table.
So what do you do?
```

### Dustycloud example formatted according to Lemmer + Rhodes

(Semantic linefeeds)
```
If you do enough work
  in any sort of free software environment,
  you get used to doing lots of writing of
  documentation or all sorts of other things
  in some plaintext system
  which exports to some non-plaintext system.
One way or another you have to decide:
  are you going to wrap your lines with newlines?
And of course the answer should be "yes"
  because lines
  that trail all the way off the edge of your terminal
  is a sin against the plaintext gods,
  who are deceptively mighty,
  and whose wrath is to be feared
  (and blessings to be embraced).
So okay,
  of course one line per paragraph is off the table.
So what do you do?
```

I am also not confident about where to put the semantic linefeeds. I would put much more thought into formatting than I should do. This would be a third argument against it.

**Comment by dbmrq** [comment]
I have also been trying to figure out a good way to do this in Vim. I was using latexindent, but besides other shortcomings, it's really slow.

So I decided to write a Vim plugin specifically for this. It's still very experimental, there aren't any customization options and the code is a huge mess… but it's working pretty well so far.

@kiryph Since you also seem very interested in this, I thought you might like to test it: https://github.com/dbmrq/vim-bucky

I wasn't going to publish it until I could polish it more, but some feedback/help would be nice, so there you go. If you do decide to try it, you can open issues there to discuss anything relevant. :)

**Comment by kiryph** [comment]
@dbmrq Wow. There is almost always someone with the same wish, has already implemented something and is willing to share it. This happened to me before in issue #650: poppyschmo had written a deoplete source based on cwl files.

I will raise the first issue with a few first (obvious) comments (nothing fancy).

However, I want to thank you here as well for publishing your work!

**Comment by krishnakumarg1984** [comment]
@kiryph poppyschmo's sources based on texstudio's completion candidates was a big mess and interfered with snippet manager as well the completion candidates offered by `vimtex`. 

And, yes. I would like to +1 for `latexindent.pl`. It is the best latex-aware indent tool out there.

git-diffing has been a problem for me forever. I really don't know how to format prose while still keeping an 80 character width. One line per sentence seems too tough to follow in practice.

**Comment by lervag** [comment]
Hi! So, it's about time I look at this. First, for my own sake, I'll try to summarize the initial comments.

First, we all agree there are a lot of different ways and philosophies for formatting text, including LaTeX manuscripts (and code). @kiryph lists some good sources that describe some approaches.

List of external tools:
- latexindent.pl
- BibTool
- vim-bucky (@dbmrq's plugin)
- Machine learning toolkits (not sure about specific tools here?)

Relevant generic Vim plugins:
- ale
- neoformat
- vim-codefmt
- vim-autoformat

In addition, there is the Vim internal text formatting, see `:help formatting`, as well as the vimtex formatexpr (`:help g:vimtex_format_enabled`). The vimtex formatexpr relies on hardwrapping text at a specific textwidth, while adherring to natural LaTeX boundaries and indentation.

----

I do not see any advantage of implementing more methods within vimtex. Instead, I see a lot of pitfalls. It seems to me a much better approach is to instead rely on external, generic Vim plugins. However, we should document this in a good way to make it easy to discover and easy to setup.

----

@krishnakumarg1984 I actively use one sentence per line for collaborative documents, and I actually think it works very well. Obviously, you need to `set tw=0` and `set wrap`, but then I find it easy to work with without external tools.

**Comment by lervag** [comment]
So, it seems the action related to this issue is:

- Update the documentation with how to setup an external format tool with a generic Vim plugin.
- Add a list of alternatives (external tools and generic vim plugins)
- Ensure that the updated docs make sense and is "discoverable"

**Comment by lervag** [comment]
So, do you all agree with this? :)

**Comment by dbmrq** [comment]
Sounds fine by me. :)

(My plugin is still a long way from being ready for general use, though. It may be better not to mention it or to state that it's a beta or maybe an alpha version.)

**Comment by kiryph** [comment]
Yes, I also agree. As usual I have some thoughts 😃:


### KISS: keep things short and focused
I agree we should not mention everything:

- from my perspective using machine learning toolkits is too much.
- I know that `vim-bucky` is still not a finished tool to use. This could be a reason not to mention it. On the other side, I appreciate the speed compared to latexindent.pl and that it works seamlessly within vim. Also having possibly more user to report issues could help you @dbmrq to develop it. However, I do not know what your plans are: developing and maintaining a plugin, in particular a latex formatting plugin, needs time.

From my point of view mature, worthwhile tools are `latexindent.pl`, `BibTool`.
Calling them from one of the generic format plugins (`autoformat`, `neoformat`, `codefmt`) should be ok.

### Require Minimal User Setup

However, I would like to have them working out of the box, ie. the user should not have to go through lengthy installation steps and has not to figure out how to customize them so it works. E.g. right now there is no configuration for `bibtool` to sort and format bib files.  Btw Bibtool is not distributed with mactex or texlive in general. However, the installation is from my point of view easy enough:

$ sudo apt install bibtool # https://packages.debian.org/stretch/bibtool, ...
$ brew install bib-tool # macOS

Also mactex on macos needs additional perl modules so that the pre-installed `latexindent.pl` works. IMHO these are more steps than I would like to have. I guess we cannot do anything about this.

**Comment by lervag** [comment]
I've finally written something about this now. I would appreciate feedback and suggestions for improving. Right now, there is very little detail. I'm thinking that it could be improved somewhat, perhaps some more details, and then also perhaps add one example of a "common" setup with vim-plug, latexindent and either neoformat or one of the other vim plugins. This could be added to the FAQ section, for instance, and we could add a link from the non-feature section.

**Comment by Astrantia** [comment]
@lervag https://github.com/James-Yu/LaTeX-Workshop/ allows formatting with latexindent directly. Can something similar be achieved with vimtex too?

**Comment by lervag** [comment]
As you have probably noticed, I have not been able to follow up on vimtex development as much as I would like to of late. A combination of family life, work and spare time that does not quite balance the way I want it. In any case, I will be more than happy to consider pull requests for improved documentation, or better, suggestions (preferably in PR format) for how to add support for `latexindent.pl`  to vimtex. In the mean time, I'll take the liberty of closing this issue as resolved.

**Comment by lervag** [comment]
@Astrantia Anything is possible, but I am afraid I don't have the time to solve this myself right now. To me, this is not an important feature. But as mentioned, I would be happy to consider PR's or concrete suggestions on how to implement such a feature. Simultaneously, I think that autoformatting with external tools should be done by projects such as [ale.vim](https://github.com/w0rp/ale).
