### ISSUE TITLE
A question for a new function for csd

### ISSUE THREAD

**Issue by zhuosongz** [lervag/vimtex#1202]
# A question for a new function for csd

When I want to change the surrounding delimiter, for example, (* is my cursor) I want to change

```
\bigl( *My equation \bigr)
```
to 
```
\bigl[ *My equation \bigr]
```

When I want to change the delimiter, I use `csd` and then press `]`, then the result would be 

```
[ *My equation ]
```
How can I change to `\bigl[` and `\bigr]` surroundings? Thanks!

**Comment by clason** [comment]
`csb]` should work!

**Comment by clason** [comment]
How about `vad:s/vert/Vert/g`? But if you need a lot of operations on custom delimiters, you should take a look at https://github.com/machakann/vim-sandwich.

**Comment by andymass** [comment]
you should be able to add lvert/lVert to `g:vimtex_delim_list` and it will act like a delimiter.

**Comment by zhuosongz** [comment]
Many thanks for your kind help! I will take a look.

**Comment by zhuosongz** [comment]
If I add the `lvert/lVert` to the delimiter list, and if I use the command `csd`, it will also delete the `\bigl \bigr`.

**Comment by lervag** [comment]
This is because `\bigl` and `\bigr` are modifiers, not delimiters. I think perhaps I'll look into changing this, because I agree it seems strange to remove the modifiers when doing the `csd` mapping.

Notice that the same occurs with e.g. `\left( ... \right)`.

**Comment by lervag** [comment]
@andymass `\lvert` and `\lVert` are already counted as delimiters by default. The problem here is that the `csd` command includes the modifiers when deleting and before replacing. I think this is a bug, but I am surprised it has not been reported before. Perhaps it was difficult to implement?

I'm looking at it now, I'll see if I can fix this.

**Comment by andymass** [comment]
Indeed, you're right about lvert/lVert, my mistake.  But I remember `csd` working as intended, I guess it may have been broken in 681e2e0.

**Comment by zhuosongz** [comment]
Hi Lervag, 

Thanks for your reply. I myself wrote a stupid way to do it. I modified the function `vimtex#delim$change`, and add by hand some new choices. By doing this, if I wand to change 

`\bigl( … \bigr)` to `\Bigl\{ … \Bigr\}`

I simply use csd and then input `B{`. I hope there will be more simple and convenient way to do this! Thank you very much for your consideration of this issue. 

Best regards, 
Zhuosong 


PS: please find the changes of the function below. 



function! vimtex#delim#change(open, close, new) " {{{1
  "
  " Set target environment
  "
  if a:new ==# ''
    let [l:beg, l:end] = ['', ‘']
“ #################################################################
“ 		This is the main change
“ #################################################################
  elseif a:new ==# 'lr('
    let [l:beg, l:end] = ['\left(', '\right)']
  elseif a:new ==# 'b('
    let [l:beg, l:end] = ['\bigl(', '\bigr)']
  elseif a:new ==# 'B('
    let [l:beg, l:end] = ['\Bigl(', '\Bigr)']
  elseif a:new ==# 'bb('
    let [l:beg, l:end] = ['\biggl(', '\biggr)']
  elseif a:new ==# 'BB('
    let [l:beg, l:end] = ['\Biggl(', '\Biggr)']
  elseif a:new ==# 'lr['
    let [l:beg, l:end] = ['\left[', '\right]']
  elseif a:new ==# 'b['
    let [l:beg, l:end] = ['\bigl[', '\bigr]']
  elseif a:new ==# 'B['
    let [l:beg, l:end] = ['\Bigl[', '\Bigr]']
  elseif a:new ==# 'bb['
    let [l:beg, l:end] = ['\biggl[', '\biggr]']
  elseif a:new ==# 'BB['
    let [l:beg, l:end] = ['\Biggl[', '\Biggr]']
  elseif a:new ==# 'lr{'
    let [l:beg, l:end] = ['\left\{', '\right\}']
  elseif a:new ==# 'b{'
    let [l:beg, l:end] = ['\bigl\{', '\bigr\}']
  elseif a:new ==# 'B{'
    let [l:beg, l:end] = ['\Bigl\{', '\Bigr\}']
  elseif a:new ==# 'bb{'
    let [l:beg, l:end] = ['\biggl\{', '\biggr\}']
  elseif a:new ==# 'BB{'
    let [l:beg, l:end] = ['\Biggl\{', '\Biggr\}']
  elseif a:new ==# 'lr|'
    let [l:beg, l:end] = ['\left\lvert', '\right\rvert']
  elseif a:new ==# 'b|'
    let [l:beg, l:end] = ['\bigl\lvert', '\bigr\rvert']
  elseif a:new ==# 'B|'
    let [l:beg, l:end] = ['\Bigl\lvert', '\Bigr\rvert']
  elseif a:new ==# 'bb|'
    let [l:beg, l:end] = ['\biggl\lvert', '\biggr\rvert']
  elseif a:new ==# 'BB|'
    let [l:beg, l:end] = ['\Biggl\lvert', '\Biggr\rvert']
  elseif a:new ==# 'lr||'
    let [l:beg, l:end] = ['\left\lVert', '\right\rVert']
  elseif a:new ==# 'b||'
    let [l:beg, l:end] = ['\bigl\lVert', '\bigr\rVert']
  elseif a:new ==# 'B||'
    let [l:beg, l:end] = ['\Bigl\lVert', '\Bigr\rVert']
  elseif a:new ==# 'bb||'
    let [l:beg, l:end] = ['\biggl\lVert', '\biggr\rVert']
  elseif a:new ==# 'BB||'
    let [l:beg, l:end] = ['\Biggl\lVert', '\Biggr\rVert']
  elseif a:new ==# 'lr<'
    let [l:beg, l:end] = ['\left\langle', '\right\rangle']
  elseif a:new ==# 'b<'
    let [l:beg, l:end] = ['\bigl\langle', '\bigr\rangle']
  elseif a:new ==# 'B<'
    let [l:beg, l:end] = ['\Bigl\langle', '\Bigr\rangle']
  elseif a:new ==# 'bb<'
    let [l:beg, l:end] = ['\biggl\langle', '\biggr\rangle']
  elseif a:new ==# 'BB<'
    let [l:beg, l:end] = ['\Biggl\langle', '\Biggr\rangle']
  “ ############################################################
  “ 			End of the change
  “ ############################################################
  "   let [l:beg, l:end] = ['\bigl(', '\bigr)']
  else
    let l:side = a:new =~# g:vimtex#delim#re.delim_all.close
    let l:index = index(map(copy(g:vimtex#delim#lists.delim_all.name),
          \   'v:val[' . l:side . ']'),
          \ a:new)
    if l:index >= 0
      let [l:beg, l:end] = g:vimtex#delim#lists.delim_all.name[l:index]
    else
      let [l:beg, l:end] = [a:new, a:new]
    endif
  endif

  let l:line = getline(a:open.lnum)
  call setline(a:open.lnum,
        \   strpart(l:line, 0, a:open.cnum-1)
        \ . l:beg
        \ . strpart(l:line, a:open.cnum + len(a:open.match) - 1))

  let l:c1 = a:close.cnum
  let l:c2 = a:close.cnum + len(a:close.match) - 1
  if a:open.lnum == a:close.lnum
    let n = len(l:beg) - len(a:open.match)
    let l:c1 += n
    let l:c2 += n
    let pos = vimtex#pos#get_cursor()
    if pos[2] > a:open.cnum + len(a:open.match) - 1
      let pos[2] += n
      call vimtex#pos#set_cursor(pos)
    endif
  endif

  let l:line = getline(a:close.lnum)
  call setline(a:close.lnum,
        \ strpart(l:line, 0, l:c1-1) . l:end . strpart(l:line, l:c2))

  if a:new ==# ''
    silent! call repeat#set("\<plug>(vimtex-delim-delete)", v:count)
  else
    silent! call repeat#set(
          \ "\<plug>(vimtex-delim-change-math)" . a:new . '
', v:count)
  endif
endfunction

**Comment by lervag** [comment]
Yes, you are right, @andymass. I'm fixing now.

**Comment by zhuosongz** [comment]
Hi Lervag, 

Thank you very much for your update. However, after I upgrade the vimtex plugin, there is a new problem for me. When I open a tex file, it is not open automatically, and in the command line, it shows: 

> Filename.tex
> []
> Press ENTER or type command to continue

I don’t know it is a general question or only for me. I tried to uninstall the plugin, and the problem is gone. Could you please help me with this? Thanks!

Best regards, 
Zhuosong

**Comment by lervag** [comment]
Sorry, my mistake, fixed now. I forgot to remove an "echo" line that I used while fixing/implementing something.

**Comment by zhuosongz** [comment]
Many thanks!

Best regards, 
Zhuosong
