### ISSUE TITLE
[feature request] Offer completion candidates for packages when using PassOptionsToPackage

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1205]
The construct `PassOptionsToPackage` is sometimes a good way to avoid latex package clashes. 

The syntax is as follows

`PassOptionsToPackage{options list}{package name}`

It would be great if `vimtex` can offer completion candidates for the `package name` similar to how it does this for `usepackage` and `RequirePackage`.

**Comment by lervag** [comment]
No problem. :)

Just curious, when (and how) would you use `PassOptionsToPackage` in a real world example?

**Comment by krishnakumarg1984** [comment]
Package clashes are not uncommon with latex. Please see this FAQ by the UK-TUG https://texfaq.org/FAQ-optionclash 

To quote a few relevant sentences from this, "The command \PassOptionsToPackage tells LaTeX to behave as if its options were passed, when it finally loads a package. As you would expect from its name, \PassOptionsToPackage can deal with a list of options, just as you would have in the the options brackets of \usepackage. "

As a real-world example, many universities require PhD theses to be submitted in the PDF/A format (for complying to long-term archival requirements). The `pdfx` package facilitates this, but this package also loads a few packages with a pre-decided set of options. Now, I think options to latex packages can only be set once (at the time of first loading of the package).  Most packages (except `hyperref` (through `hypersetup` and the graphics bundle using `Gin` keys) do not have a mechanism of providing options to a package after it has been loaded.

 `PassOptionsToPackage` provides a wonderful mechanism to pass extra user-defined options to packages which are loaded as dependencies by other packages. The best part is, it will never hurt you if you use it.

**Comment by lervag** [comment]
Thank you for the introduction to `\PassOptionsToPackage`, I can see how it is useful!

**Comment by lervag** [comment]
While improving my tests for completion I've noticed that it seems this issue was not solved correctly. The package is completed in the first argument, instead of in the the second where it should be completed. Am I right?
