### ISSUE TITLE
Command line errors when open a tex file

### ISSUE THREAD

**Issue by zhuosongz** [lervag/vimtex#1209]
Hi, after I update the vimtex plugin, I got a problem when opening a new tex file. In the command line, it says 

![image](https://user-images.githubusercontent.com/31466564/45063513-b4b27000-b0f1-11e8-93bc-0fc7a828b302.png)

and then I have to press some key to open this file. Since there is no error information, and I don't know where is this error from. Could you please help me with this? Many thanks!

**Comment by lervag** [comment]
This is fixed now.
