### ISSUE TITLE
DSE problem using vimtex under Windows

### ISSUE THREAD

**Issue by unoqualsiasi60** [lervag/vimtex#1211]
# DSE using Vimtex under Windows

The `dse` combination used under Windows leaves two curly brackets before and after the text.

Here is a small example:

### Before `dse` command

```
\begin{center}
TEST DSE
\end{center}
 ```

### After `dse` command

```
}
TEST DSE
}
```
The same problem was not present in a previous version of the plugin (I tried to reinstall an old version of 2016 and the behavior is correct)l.

Thanks for your patience

**Comment by lervag** [comment]
Hi. Can you please provide a full minimal example as specified in the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md). For me, `dse` works as expected, and so I have no way of knowing why this fails for you unless you provide (alot) more details.

Which Vim version are you on?
