### ISSUE TITLE
Detection of main file with curly braces around input

### ISSUE THREAD

**Issue by pitkling** [lervag/vimtex#1214]
Consider the following two files:

main_file.tex:
```
\documentclass{article}
\begin{document}
{\input{input_file}}
\end{document}
```

input_file.tex:
```
included successfully
```

Note that the input macro in `main_file.tex` is surrounded by curly braces (I use this when writing documents to ensure that macros defined in an included file cannot be used outside of that file).

I would expect that opening input_file.tex would recognize main_file.tex as the project's main file, but it does not. When removing the curly braces around the input macro, it works as expected. Also, I **think** this worked as expected until recently.

**Comment by lervag** [comment]
The reason _not_ to update vimtex to support your use case is that it makes the regexp quite a lot faster if I  anchor it as I've done now. If it was not anchored, then I would need to add an expensive regexp part to ensure that the input command is not in a comment.

**Comment by lervag** [comment]
Oh, and sorry about not writing everything in a single response: This is probably quite new, yes. I've updated the Table of contents feature, which use the various regexes quite a lot. This is where I found that adding this anchor would improve load times for complex LaTeX documents. I figured that the benefits would clearly outweigh the possible inconvenience to users...

**Comment by pitkling** [comment]
Ahh, I see. Thanks for the (as always) quick response and explanation. I will just use something like

```
{
    \input{…}
}
```

in the main file, which seems to work (I prefer having the "visual clutter" of the extra braces in the main document, which is not touched that often).

**Comment by lervag** [comment]
No problem! Again, I am sorry for the inconvenience! Note, you could also redefine the `\input` command if you _always_ follow that pattern, e.g.

```tex
\let\oldinput\input
\renewcommand{\input}[1]{{\input{#1}}}
```

This should (I have not tested it) give you the desired behaviour and let you write the `\input` without the surrounding braces.

**Comment by pitkling** [comment]
Good suggestion, but I guess that might drive my coauthors crazy if they miss the redefinition ;). Anyway, I assume there is no option that allows me to tell vimtex which macros include new files? Then I could write my own `\guardedinput{…}` macro similar to your suggestion.

**Comment by lervag** [comment]
No, sorry, there is no such option as of now. But I could consider adding one... It should be very easy, and there might be more people who would want it.

I would need a good name for it, though...

**Comment by pitkling** [comment]
Hm, `g:vimtex_include_indicators` or something along that line seems fitting, but then I'm not aware of your general naming scheme. Anyway, thanks for considering it :).

**Comment by lervag** [comment]
Seems like a good name. I've added it now, and it should allow to add more names. Please test. Note, each name is applied as a regex, so you could e.g. just change the default to something like:

```vim
let g:vimtex_include_indicators = ['\w*input', 'include', 'subfile']
```

**Comment by pitkling** [comment]
Works perfectly, thanks!

One thing though: I get the following error if I **do not** define `g:vimtex_include_indicators` in my `input.vim` file.

```
error detected while processing /Users/peter/.local/share/nvim/plugged/vimtex/autoload/vimtex/re.vim:
line   14:
E121: Undefined variable: g:vimtex_include_indicators
E116: Invalid arguments for function join
E15: Invalid expression: '\v\\%(' . join(g:vimtex_include_indicators, '|') . ')\s*\{'
line   21:
E121: Undefined variable: g:vimtex#re#tex_input_latex
E116: Invalid arguments for function join
E15: Invalid expression: '\v^\s*%(' . join([   g:vimtex#re#tex_input_latex,   g:vimtex#re#tex_input_import, ], '|') . ')'
line   24:
E121: Undefined variable: g:vimtex#re#tex_input
E15: Invalid expression: g:vimtex#re#tex_input_root . '|' . g:vimtex#re#tex_input . '\zs[^\}]*\ze\}?'
```

I assume the default value is not properly set?

**Comment by lervag** [comment]
Sorry, I think it is fixed now.

**Comment by pitkling** [comment]
Looks good, thanks again! :)

**Comment by lervag** [comment]
No problem :)

**Comment by pitkling** [comment]
Just a minor remark, something I stumbled upon when cleaning up my vim configuration: It seems setting this option in 'after/ftplugin/tex.vim' does not work. Having it in 'init.vim', however, works just fine. Maybe it's obvious that it cannot be set in the former, but it was not clear to me (I tend to use the former to configure tex specific settings).

**Comment by lervag** [comment]
Ah, yes, the option is read during initialization of vimtex, and so it must be set early. I can understand that this is not necessarily intuitive, and so I'll add a comment to the docs.
