### ISSUE TITLE
Error in TOC jump when changing outline level

### ISSUE THREAD

**Issue by drinkwell** [lervag/vimtex#1223]
When using the table of contents (default mapping `<localleader>lt`), jumping to a location in the file (using `<Enter>` or `<Space>`) works correctly if the document outline is fully expanded.  If, however, `-` is first used to filter the lower subsections,  the location in the document jumped to will be incorrect.    

This can be reproduced using the following example document:
```tex
\documentclass{minimal}

\begin{document}

\section{Section 1}
\subsection{Section 1.1}
\subsubsection{Section 1.1.1}
\section{Section 2}
\subsection{Section 2.1}
\subsubsection{Section 2.1.1}
\section{Section 3}
\subsection{Section 3.1}
\subsubsection{Section 3.1.1}

\end{document}
```

**Comment by drinkwell** [comment]
Wow, that was quick! Thanks

**Comment by lervag** [comment]
No problem :)

Den ons. 19. sep. 2018, 18:48 skrev drinkwell <notifications@github.com>:
