### ISSUE TITLE
Omnicomplete candidate filtering of adjacent eqref and ref interacts 

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1225]
*(This is really a very minor issue, but I thought that I'd report it anyway.)*

If I understand correctly, vimtex filters the candidates for `\eqref{` omnicompletion based on the label prefix `eq:`, while the candidates for `\ref{` and `\cref{` are not filtered. (Although I'm not perfectly clear how and when; if I have `sec:1` and `eq:1`, the candidates are filtered, but for `sec:1` and `eq1` they are not.)

The issue is that if a `\ref{` follows immediately after an `\eqref{...}` *without spaces*, the filtering is also applied to the candidates for `\ref{`:
![screenshot_20180921_183050](https://user-images.githubusercontent.com/2361214/45894133-cff9cc80-bdcd-11e8-8369-21f5882fc508.png)
If I add a space before `\ref{`, the list is unfiltered as expected. 

(This is using an autocomplete plugin for the sake of the screenshot, but the issue also shows up with the standard minimal `.vimrc`.)

**Comment by lervag** [comment]
Fixed, I think. Please test and report if it should have some bad side effects.
