### ISSUE TITLE
Forward search not working with vim-polygon plugin (using Neovim with Skim on macOS)

### ISSUE THREAD

**Issue by Zeta611** [lervag/vimtex#1227]
1. `.minimalvimrc`:

    ```vim
    let &rtp = '~/.local/share/nvim/plugged/vim-polyglot,' . &rtp
    let &rtp .= ',~/.local/share/nvim/plugged/vimtex,' . &rtp
    let &rtp .= ',~/.local/share/nvim/plugged/vimtex/after'

    syntax on

    let g:vimtex_view_method = 'skim'
    let g:vimtex_compiler_progname = 'nvr'
    ```

2. `main.tex`:

    ```tex
    \documentclass{minimal}
    \begin{document}

    Hello World!

    \end{document}
    ```

3. Steps to reproduce:

With `NVIM_LISTEN_ADDRESS=/tmp/nvimsocket nvim -u .minimalvimrc main.tex`, open `main.tex` and typeset. Although inverse search works with Skim and Neovim, **forward search** doesn't work.

Without [vim-polygot](https://github.com/sheerun/vim-polyglot) plugin, both forward and inverse search works. Is this a problem from vim-polygot plugin, or vimtex?

**Comment by lervag** [comment]
Your minimal vimrc can't work without `filetype plugin indent on`.

And yes, vimtex does not work properly with vim-polyglot. You need `let g:polyglot_disabled = ['latex']` (or perhaps `'tex'`).

**Comment by Zeta611** [comment]
Sorry, I should have read the `README` more carefully.
Thanks for clarification!
