### ISSUE TITLE
Error with `vimtexcountwords` and `vimtexcountletters` - "unescaped left brace in regex ..."

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1229]
I get the following error message when using the commands `vimtexcountwords`  and `vimtexcountletters`

>
>vimtex: Counted words: Unescaped left brace in regex is deprecated here (and will be fatal in Perl 5.32), passed through in regex; marked by <-- HERE in m/\\\w+({
><-- HERE })?/ at /usr/local/bin/texcount line 2934.1936

This is on Arch Linux with `perl 5.28`.  

Any idea what might be the issue?

**Comment by lervag** [comment]
It seems `texcount` does not work properly. Can you try it outside Vim/vimtex?

**Comment by krishnakumarg1984** [comment]
I just ran `texcount` on the command-line and looks like it is a problem with `texcount` rather than `vimtex`. Nevertheless, when run from the command-line, `texcount` works fine producing a warning (but still returning the counts). However, `vimtex` simply errors out.

**Comment by krishnakumarg1984** [comment]
Ah. An update. The returned count from `texcount` is simply wrong!

**Comment by lervag** [comment]
Good! So, it seems this is not an issue with vimtex, right?

**Comment by krishnakumarg1984** [comment]
Yes. I agree.  Should vimtex disable this feature until upstream fixes?

**Comment by lervag** [comment]
No, because there will be a lot of people with earlier versions that still
works.

Den man. 24. sep. 2018, 19:43 skrev Krishnakumar <notifications@github.com>:

**Comment by krishnakumarg1984** [comment]
The author of `texcount`, Einar Andreas Rødland emailed me an updated version of `texcount` for trial. This updated version solved the issue with unmatched paren and fixed all counting issues.  He said he shall update the public release after a few more tests.

**Comment by lervag** [comment]
Great, thanks! I can't see how this could have ended any better. :)
