### ISSUE TITLE
Problems with `zathura` viewer

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1230]
Following a recent `vimtex` upgrade, I get the following error when using `zathura` as the viewer.

>vimtex: Viewer cannot find Zathura window ID!

Any idea what might be wrong?

**Comment by lervag** [comment]
Could you provide some more information and context? I'm on Arch Linux and
use zathura with no issue.

Den man. 24. sep. 2018, 19:45 skrev Krishnakumar <notifications@github.com>:

**Comment by krishnakumarg1984** [comment]
huh. I don't know. The problem magically disappeared. Sorry for the noise.

**Comment by lervag** [comment]
No problem.
