### ISSUE TITLE
Inverse search from Okular does not work

### ISSUE THREAD

**Issue by copyme** [lervag/vimtex#1233]
Hey guys!

I am not sure if this is vimtex problem but I have noticed that the inverse search from okular has stopped to work.

1. Open a latex file in neovim
2. Do `\lv`
3. shift + click
4. No effect

Okular editor: `nvr --remote-silent %f -c %l` (nvr 2.0.10)

My init.vim file has:

```vim
" Forward search
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
```

and `latexmkrc` has:

```perl
$pdflatex = 'lualatex --enable-write18 -synctex=1 %O %S';
```

I have not updated too much here but today I wanted to work on an article and I noticed the problem.

Note that, it works fine if I open okular in a terminal and then do a shift + click, which will open an instance of nvim in between which I can search i.e., forward and backward search works. 

Is the nameserver set properly? I guess vimtex was doing that before, no?

**Comment by lervag** [comment]
Inverse search from Okular is not something you set from vimtex, but something you set configure in Okular. If `nvr --remote-silent %f -c %l` does not work from Okular, then try the same in a terminal, with `%f -> tex filename` and `%l -> some line number`.

**Comment by lervag** [comment]
I would not be surprised if the problem is related to the servername. Do things work in regular Vim?

**Comment by copyme** [comment]
Interesting, it works when nvim is open from bash but it does not when I work with fish (my default shell).

**Comment by copyme** [comment]
But it was working well for so long. I have switched to fish a year ago. Let's keep this thread open, please. Maybe we will find a cure for this ;-)

**Comment by copyme** [comment]
I made a progression. Everything works with the same terminal profile in yakuake and xterm but it does not in Konsole. So I guess it is somehow related to a bug in Konsole but I cannot say more so far.

**Comment by copyme** [comment]
It works in Konsole when: 1. open Konsole; 2. call nvim in the konsole

Does not work when: click on a latex file -> open with -> Neovim - this will open the file in neovim under the default terminal (konsole here) but you will not be able to run inverse search. Note that the nvim address variable is properly set but it still does not work. Apparently, even by switching to bash this will not work.
So, I guess this is a bug in Plasma 5 that appeared after the last update in openSUSE.

Sorry for a bit of confusion but it was not easy to nail this down.

**Comment by Rmano** [comment]
Hmmm... I have seen something similar with regular vim sometime. I never reported because I can't find a pattern. What happens is that sometimes the file name returned by `okular` has an extra, literal "\\" (backslash) at the end, so vim tries to open another file. 
But it's intermittent, and I do not really know how to trigger it.

**Comment by copyme** [comment]
thanks for your feedback @Rmano. I will check whether the "\" problem is occurring in my case or not.

**Comment by lervag** [comment]
Thanks for updating the issue with more details. I'm sorry I have no extra input, as I have little to no experience with KDE. I hope you got things working the way you want.

**Comment by Rmano** [comment]
I found what was my problem. I was calling from `okular`: 
```
tvim-send-back +%l "%f"
```
where `tvim-send-back` is a script of mine (so that I have a different vim server for each desktop). In that script, I was using `"$2"` (with the quotes), and that resulted in double quotation at the end (there was really a newline there). So probably this is a completely different problem from yours.

**Comment by copyme** [comment]
@Rmano I do think so that this is another problem. Anyway, I am glad that you have solved the problem on your side ;-)

**Comment by msiniscalchi** [comment]
@lervag just FYI, the following works for me using gvim v8.0 (the version that ships with Ubuntu 18.10): `gvim --remote-silent +%l "%f"`

Indeed the command-line docs for vim say that `-c` is to send commands; `+` s used to jump to line n; and finally all options must be provided *before* file names.

**Comment by lervag** [comment]
Thanks, @msiniscalchi, was not aware that the docs were not quite right here. Updated now.

**Comment by ZhiyuanLck** [comment]
@Rmano The same problem with me. But when I remove the quotes, which changes the command to:
```shell
vim --remote-silent +%l %f
```
inverse research worked.

**Comment by DystopianLphant** [comment]
I feel like it's worth it writing here that I got reverse search working on okular and neovim by using 
`nvr --remote-silent +%l %f`
as mentioned above, keeping all the rest of the configuration the same, as mentioned in the wiki.
It should be corrected imo

**Comment by lervag** [comment]
Do I understand correctly that thing do not work with `"%f"`, and that they work with simply `%f`? I don't mind updating the docs. Note, though: The quotes are meant to avoid problems if you should have spaces in your file paths. You could try to use `'%f'` instead? Or perhaps the quotes are already passed within the `%f` keyword implicitly, if necessary?

**Comment by DystopianLphant** [comment]
apparently now it works no matter what I put into okular, even in files or paths containing spaces

**Comment by lervag** [comment]
Ok, then I will update the docs!

**Comment by DystopianLphant** [comment]
nevermind, it doesn't work anymore for no reason, I'm trying to figure it out

**Comment by sandersantema** [comment]
Someone else seems to have found the culprit: https://stackoverflow.com/a/30530128

Okular's backward search only works in browse mode, which at least on my opensuse system is enabled with the ctrl-l shortcut, after which shift click should work. Besides that it's working for me with `nvr --servername /tmp/nvimsocket --remote-silent %f -c %l` in okular.

**Comment by piperfw** [comment]
I know this is an old issue, but does anyone have inverse search fully working in Okular (with just vim)?

With `vim --remote-silent +%l %f`, if I open a document in a new Okular instance and `Shift+Click` vim opens the file at the specified line, as expected. But that instance is 'detached' in the sense that if I then open the viewer with ` <localleader>lv` a new Okular instance opens in which the reverse search does _not work_.

**Comment by lervag** [comment]
Did you notice `:help vimtex_viewer_okular`?

**Comment by piperfw** [comment]
Yes, I am using the recommended settings there (but have also tried without them). Forward search works as expected.

**Comment by lervag** [comment]
For me, it works as expected with Vim. With neovim and nvr, it is more difficult, because you need a way to specify the servername.

Note, you also need to ensure that the servername is specified with Vim. I.e., you must start with e.g. `vim --servername VIM`.

**Comment by piperfw** [comment]
Excellent, that is what I was missing, thank you. Could we possibly put 

`Note: Those starting vim from a terminal need to ensure a server is running in order to use backwards search; see Clientserver`

under `vimtex_viewer_general`? I may not be the only one to miss the note on servers in the docs.

**Comment by lervag** [comment]
Well, it _is_ up there in the top of the documentation under `:help vimtex-requirements`. But I guess it does not hurt to add a comment here as well.

**Comment by piperfw** [comment]
Well I mean, that _should_ be sufficient, but don't underestimate the user's incompetency when it comes to properly reading documentation :laughing:.

**Comment by lervag** [comment]
I know, you're quite right. I do try to add links to make things discoverable, and your suggestion was in that regard good.
