### ISSUE TITLE
$pdf_mode=3 in .latexmkrc is ignored

### ISSUE THREAD

**Issue by tasusu** [lervag/vimtex#1234]
Thank you for developing a wonderful plugin! I have been a big fan of vimtex for years.

Recently I found an issue for identification of `$pdf_mode` in latexmkrc. In my `.latexmkrc` file, I set `$pdf_mode=3` (dvipdf) to compile a japanese document, which is incompatible to pdftex. However, running vimtex produces an error:
```
error| LaTeX Error: This file needs format `pLaTeX2e`
```

If I run latexmk manually from the shell, latexmk successfully compiles my file with dvipdf mode.

The variable `$pdf_mode` in `.latexmkrc` seems ignored if it is other than 1, 4, or 5 in [compiler/latexmk.vim](https://github.com/lervag/vimtex/blob/196a8aa7e9f9d04c69adfa7643b0e6ae6b0d3b3b/autoload/vimtex/compiler/latexmk.vim#L99) . Therefore, even if `$pdf_mode=3` is specified in `.latexmk`, vimtex runs latexmk with `-pdf` option. `:VimtexInfo` also shows it indeed complies with `-pdf` option:

```
cmd: max_print_line=2000 latexmk -verbose -file-line-error -shell-escape -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$success_cmd = "'""'nvr'""' --servername '/tmp/nvimMx88fj/0' --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'""'nvr'""' --servername '/tmp/nvimMx88fj/0' --remote-expr \"vimtex\#compiler\#callback(0)\""' 'main.tex'
```

Below, I provide a minimal example:

`init.vim`:

```vim
set nocompatible
let &rtp  = '~/.cache/dein/repos/github.com/lervag/vimtex,' . &rtp
let &rtp .= ',~/.cache/dein/repos/github.com/lervag/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-verbose',
    \   '-file-line-error',
    \   '-shell-escape',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}
 ```

`main.tex` file:

```tex
\documentclass{jsarticle}
\begin{document}
Hello World!
\end{document}
 ```

`.latexmkrc` file.

```perl
$pdf_mode = 3;
$latex = 'platex';
$bibtex = 'pbibtex';
$dvipdf = 'dvipdfmx %O -o %D %S';
```

Thank you in advance.

**Comment by lervag** [comment]
Hmm. I can't compile your minimal example. From terminal, with your `.latexmkrc` file, I get the following error:

```
This is e-pTeX, Version 3.14159265-p3.8.0-180226-2.6 (utf8.euc) (TeX Live 2018/Arch Linux) (preloaded format=platex)
 restricted \write18 enabled.

kpathsea: Running mktexfmt platex.fmt
mktexfmt: mktexfmt is using the following fmtutil.cnf files (in precedence order):
mktexfmt:   /etc/texmf/web2c/fmtutil.cnf
mktexfmt: mktexfmt is using the following fmtutil.cnf file for writing changes:
mktexfmt:   /home/lervag/.texlive/texmf-config/web2c/fmtutil.cnf
mktexfmt [INFO]: writing formats under /home/lervag/.texlive/texmf-var/web2c
mktexfmt [INFO]: did not find entry for byfmt=platex, skipped
mktexfmt [INFO]: Disabled formats: 6
mktexfmt [INFO]: Not selected formats: 36
mktexfmt [INFO]: Total formats: 42
mktexfmt [INFO]: exiting with status 0
I can't find the format file `platex.fmt'!
```

Do you know what might be wrong?

**Comment by lervag** [comment]
> Thank you for developing a wonderful plugin! I have been a big fan of vimtex for years.

Oh, and btw: Thanks! :)

**Comment by lervag** [comment]
I think the latest commit fixes the issue. For reference, it would still be nice to know how to make the example compile, though.

**Comment by tasusu** [comment]
Thanks for your quick reply and update! Now I can successfully compile my file. 

Regarding on your error, I have no idea (sorry!). I am using the same version of texlive (network installer with full option) on Ubuntu 18.04 and can compile with no error. Maybe your texlive lacks texlive-lang-japanese? Or something got broken in texlive environment... 

A little surveying lead me this page, but no easy fix: 
https://tex.stackexchange.com/questions/23164/i-cant-find-the-format-file-xelatex-fmt

Thank you anyway!

**Comment by lervag** [comment]
No problem! Happy to hear it works :)
