### ISSUE TITLE
Unexpected repetition of `csc` with the dot command after an undo

### ISSUE THREAD

**Issue by lacygoill** [lervag/vimtex#1238]
Consider this minimal vimrc:

    set rtp^=~/.vim/plugged/vim-repeat/
    set rtp^=~/.vim/plugged/vimtex
    set rtp+=~/.vim/plugged/vimtex/after/
    filetype plugin indent on

And the following tex file:

    \usepackage[utf8]{inputenc}

Position the cursor at the end of `usepackage` (i.e. its last `e` character).
Press `dd` to delete the line, then `u` to undo.
Press `csc` to change the command name.
Provide the name `foo` and press Enter to validate.
Press `u` to undo, then `.` to repeat the command.

I would expect the substitution of the command to be repeated, and get:

    \foo[utf8]{inputenc}

But what actually happens is that the line is deleted:

![gif_broken](https://user-images.githubusercontent.com/8505073/46631347-699fd880-cb47-11e8-9ba0-2fb4f8ca5709.gif)

I think this is due to the fact that the `vimtex#cmd#change()` function in `autoload/vimtex/cmd.vim` calls the `repeat#set()` function at its end.  
`repeat#set()` doesn't seem reliable after an undo. [An issue](https://github.com/tpope/vim-repeat/issues/63#issuecomment-390281441) has been opened on `vim-repeat`'s bug tracker, where its author says that they prefer to avoid it in the future, in favor of an operator function:

> The direction I am moving is avoid repeat.vim wherever I can in favor of an operator func, even if I have to shoehorn it in.

`repeat#set()` can lead to other similar issues. I remember using `repeat#set()` to repeat a custom function, for which `.` could sometimes repeat the last but one edit, instead of the last edit, even without any undo.

Anyway, I agree with tpope, and I've removed all occurrences of `repeat#set()` in my configuration files, in favor of operator functions, as they don't suffer from these issues. Besides, it removes a dependency.

I've looked at my plugins:

    :vim /repeat#set(/gj ~/.vim/**/*.vim ~/.vim/**/*.snippets ~/.vim/vimrc | cw

And noticed that `vimtex` calls `repeat#set()` in 12 different locations.
The current issue is for one of them.

To eliminate `repeat#set()`, you could use a “pseudo” operator function.
pseudo because the user would never be able to provide an arbitrary text-object, like they can for the other operator functions.
Instead, you would always pass it the motion `l`.
I think that's what tpope meant when he used the word “shoehorn”.
It's a hack, like `repeat#set()`, but more reliable.

Before calling the operator function, you would need to call another function which would save the replacement text input by the user in a script-local variable, so that the operator function can inspect it when you repeat the edition with `.`.

Here's a [diff file](https://gist.github.com/lacygoill/ce29b61a8f802249710bef29ac603d1d) which I produced using the `diff` command, your original `cmd.vim` file, and a modified version, implementing the idea mentioned just above.

I think you can apply it with this command:

    $ patch -b autoload/vimtex/cmd.vim </path/to/diff

Note however that I wasn't able to completely paste the contents of the diff in my web browser. The original code of your plugin contains a literal carriage return, which is interpreted as a newline by firefox.
So, I edited the gist to join back the 2 last lines, and inserted the 2 characters `^M`. If you try the patch, you'll have to replace them with a literal carriage return.

As you can see, it seems to fix the issue:

![gif](https://user-images.githubusercontent.com/8505073/46631375-7de3d580-cb47-11e8-89e6-63a7255c2036.gif)

If you agree with the idea of replacing `repeat#set()` with operator functions, I could try to do something similar for the other 11 locations, and submit a PR, but I'm not sure I would succeed, as I'm not familiar with the code of your plugin (nor with LaTeX).

**Comment by lervag** [comment]
If I understand correctly, you are raising an issue on a relatively obscure bug with vim-repeat, and also suggesting a method of fixing it. I.e., first calling a function to set the desired new name, store value sin script local variables, then calling the change function as an operator function that operatores on the left motion (although it still works the same as before, so the left motion is just a dummy). Am I understanding correctly?

**Comment by lacygoill** [comment]
Yes, you understood correctly, but if you think the issue is not important, feel free to close it. It's just a bug which I encountered frequently in the past.

**Comment by lervag** [comment]
I don't mind fixing things, and I do like the idea of cutting a dependency. So please, if you want, feel free to open a PR for this!

Note, though, for your particular example: I would instead use a custom function for the normal map, i.e. change `vimtex#cmd#change` to `<sid>normal_mode_change`, with

```vim
function! s:normal_mode_change(_) " {{{1
  call vimtex#cmd#change(s:new_name_cmd_change)
endfunction
```

This would reduce the impact a great deal, I think. That is, we only need a minor change to the mapping itself, as well as two help functions and to remove the `repeat#set` call.

**Comment by lacygoill** [comment]
Ok, I'll work on the 12 locations and do what I can to remove `repeat#set()`, as well as follow your recommendation.
I'll try to submit a PR in the next few days/weeks.

Thank you very much for your plugin.

**Comment by lervag** [comment]
Great, thanks!
