### ISSUE TITLE
Skim not opening or updating

### ISSUE THREAD

**Issue by lobachevzky** [lervag/vimtex#1239]
#### minimal .vimrc
```vim
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_view_method = 'skim'
let g:vimtex_compiler_latexmk = { 'build_dir' : 'build' }
call plug#begin('~/.vim/bundle')
Plug 'lervag/vimtex'
call plug#end()
```

#### minimal tex file

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

#### Steps to reproduce
1. `nvim  -u ~/.config/nvim/init.vim simple.tex`
2. type `:VimtexCompile<CR>`.

#### Expected Behavior
Vim echoes 'vimtex: Compiler started in continuous mode.'
Skim pops up displaying rendered tex file.

#### Actual Behavior
Vim echoes 'vimtex: Compiler started in continuous mode.'
Skim does not open.

Even if I manually open Skim, the displayed document does not update when I save in Vim.

**Comment by lervag** [comment]
Please update your issue report. Use the template, don't _include_ the template.

**Comment by lervag** [comment]
Sorry, it seems you might have updated the issue (you should have made a comment, because I don't get notified when something is edited).

**Comment by lervag** [comment]
Further, I'm also sorry to say that I can't really be of much help here. I don't really know much about OSX. I've been lucky that there's been some friendly people in the community that have helped before, perhaps they are able to help now as well?

@clason @vanabel @andymass

**Comment by clason** [comment]
All I can say is that
```vim
let g:tex_flavor='latex'
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_view_method = 'skim'
```
works for me. (Maybe the issue is that you need to set them *after* loading the plugin?  Does it work if you omit the line about the build dir? Also make sure you have the latest version of `neovim` and `neovim-remote` installed.)

**Comment by lobachevzky** [comment]
Solved this one. Basically I had updated to `python3.7` and did not have `neovim-remote` installed for that version of python.

The way I found it was by looking in `:VimtexInfo` and then running the following on the command line:
```
max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$success_cmd = "'""'nvr'""' --servername '/var/folders/bd/8nh4kyg933zcxm7n90n2m98r0000gn/T/nvim0s9ADo/0' --remote-expr \"vimtex\#compiler\#callback(1)\""' -e '$failure_cmd = "'""'nvr'""' --servername '/var/folders/bd/8nh4kyg933zcxm7n90n2m98r0000gn/T/nvim0s9ADo/0' --remote-expr \"vimtex\#compiler\#callback(0)\""' 'minimal.tex'     
```
This threw an error that indicated that `nvr` was looking in the wrong place for `python`.
Two suggestions:
- Maybe include some error handling in case `nvr` is not working.
- Have users posting issues run the output of the `:VimtexInfo > vimtex project > compiler > cmd` command on the command line as it can reveal useful debugging info.
