### ISSUE TITLE
Wrong indent for \item when using Ultisnips

### ISSUE THREAD

**Issue by goduck777** [lervag/vimtex#1245]
Vimtex can handle the indent of \item very will in most cases.

In Ultisnips (or other snippet plugins), there is a very convenient way to input \item. Like, I can just type it\<tab\> to get a \item. However, in this case vimtex gives the wrong indent. The tab before \item is not eliminated. The result is like
```
\item a
    \item b
        \item c
```
 Is there a fix for this problem? or is there a better way for inputting \item?

**Comment by lervag** [comment]
The reason for this is that the current line is reindented on certain specified keys, which are not typed when you do `it<tab>`. Thus the tab before the `\item` will not be removed.

Personally, I've solved this particular issue by defining a mapping for inserting the items, i.e. I have the following in my personal `ftplugin/tex.vim` (can also be put in `ftplugin/after/tex.vim`).

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : '<m-i>',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment',
      \ 'context' : [
      \   'itemize',
      \   'enumerate',
      \   {'envs' : ['description'], 'rhs' : '\item['},
      \ ],
      \})
```

However, Ultisnips is powerful, and I'm sure you can solve this with it as well. I'm no expert, but it seems [this](https://github.com/SirVer/ultisnips/blob/master/doc/UltiSnips.txt#L1580) might be close to what you want to do.

**Comment by lervag** [comment]
I'm closing the issue, but feel free to continue the discussion.

**Comment by goduck777** [comment]
Thank you for your answer. This is not exactly what I want. I am looking for auto-indenting the line after the snippet expand. The ultisnips trick you suggests gives a fixed indent, but not a smart indent according to the context.

I will submit an issue to ultisnips for this problem.

**Comment by lervag** [comment]
Ok, thanks. Feel free to make a reference to the Ultisnips issue when/if you create it.

**Comment by andymass** [comment]
@goduck777 there is already this possibly related issue https://github.com/SirVer/ultisnips/issues/913

**Comment by goduck777** [comment]
@andymass Thank you, this is what I want.

**Comment by cuppajoeman** [comment]
@lervag Why does vimtex autoindent after a line containing \item? Is there a way to disable that.

**Comment by lervag** [comment]
@cuppajoeman Please don't ask new questions in old threads. It is much better to open a new issue.

The why: Because I've found it convenient to "descramble" the `\item` lines from the remaining lines in itemize environments. That is, because I like it this way. But of course, it is configurable. The details are explained in `:help g:vimtex_fold_types`. For your convenience:

```vim
let g:vimtex_fold_types = {'item' : {'enabled' : 0}}
```

**Comment by fxmarty** [comment]
@lervag Thanks a lot

**Comment by awa5114** [comment]
It would be nice to be able to disable this. Is it still not possible?

**Comment by lervag** [comment]
@awa5114 This was never opened as a feature request. If you want it, please open a feature request and describe what you want.
