### ISSUE TITLE
Forward search for zathura not working

### ISSUE THREAD

**Issue by akshit-sharma** [lervag/vimtex#1246]
Forward search for zathura is not working. It works when I substitute zathura with okular.

1. A minimal `vimrc` file, for instance:

 ```vim
  set nocompatible
  let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
  filetype plugin indent on
  syntax enable

  let g:vimtex_compiler_latexmk = { 'build_dir'  : 'build' }
  let g:vimtex_view_general_viewer = 'zathura'
  " let g:vimtex_view_general_viewer = 'okular'
  let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
 ```

2. A minimal `.tex` file, such as:

```tex 
  \documentclass[12pt]{article}
  \usepackage[utf8]{inputenc}

  \begin{document}

  This is a sample text.

  \newpage

  This is second page.

  \end{document}
 ```

3. ```vim --servername vim -u vimrc minimal.tex``` to open the file. Then pressed ```\ll``` to compile followed by ```\lv``` on lines containing "sample text" and "second page".
If my general_viewer is set to zathura, I am not able to do forward search but if it is okular then it works just fine. While using zathura (pressing ```\lv```), the vim just refreshes and I am not able to see any output in vim status bar.
If I run the following command from terminal then forward searching on zathura works ```zathura --synctex-forward 6:1:minimal.tex build/minimal.pdf```.

4. my ```.latexmkrc``` is empty.

Do you have an idea as to why it is failing to do forward search on zathura with vimtex.

**Comment by lervag** [comment]
Can you instead try to use 

```vim
let g:vimtex_view_method = 'zathura'

" Instead of
"let g:vimtex_view_general_viewer = 'zathura'
"let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
```

**Comment by akshit-sharma** [comment]
Thanks, that fixed it.

**Comment by lervag** [comment]
Great :)
