### ISSUE TITLE
Mis-indentation of some circuitikz environment after last update

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#1248]
After the last update, I noticed mis-indentation of environments --- I managed to reduce the case to some optional argument for example in `circuitikz`.  It seems **not** related to trailing spaces (there are none here, I think...) 

This is my `minivimrc`:

    ```vim
    set nocompatible
    let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
    let &rtp .= ',~/.vim/plugged/vimtex/after'
    filetype plugin indent on
    syntax enable
    ```

This is the example LaTeX file

```tex
\documentclass{article}
\usepackage{circuitikz}
\begin{document}
Text here
\begin{center}
    \begin{circuitikz}[american] 
        \draw (0,0) node[npn]{};
    \end{circuitikz}
\end{center}
\begin{center}
    \begin{circuitikz}[american, baseline=(VCC)]
        \draw (0,0) node[npn]{};
\end{circuitikz}
\end{center}
\end{document}
```

As you can see, the `circuitikz` environment is doubly de-indented *only* when the optional parameter `baseline=(VCC)` is added. 

![image](https://user-images.githubusercontent.com/6414907/47101119-7dc79200-d239-11e8-9204-2d59d03a9097.png)

**Comment by Rmano** [comment]
I checked some more; it's the comma `,` the problem.

**Comment by lervag** [comment]
Can you test after the most recent commit? I think this might be related to #1244.

**Comment by Rmano** [comment]
Yes, it's fixed. Thank you!

**Comment by lervag** [comment]
No problem :)
