### ISSUE TITLE
ds$ doesn't work

### ISSUE THREAD

**Issue by sim590** [lervag/vimtex#1249]
1. A minimal `vimrc` file:
    ```sh
    vim -u <(<<< "set nocompatible
        let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
        let &rtp .= ',~/.vim/plugged/vimtex/after'
        let &rtp = '~/.vim/plugged/vim-surround,' . &rtp

        filetype plugin indent on
        syntax enable")
    ```

2. Writing the following:

    ```tex
    \documentclass{minimal}
    \begin{document}

    $ 2+2 = 4 $

    \end{document}
    ```

3. Trying `ds$` inside the dollar signs doesn't work.

    >- Delete the surrounding command, environment or delimiter with
    >`dsc`/`dse`/`ds$`/`dsd`

    According to the help page, this should work.

### More info

- **Vim version**: VIM - Vi IMproved 8.0320 (2018 May 18, compiled Aug 22 2018 23:46:39)
- **vimtex revision**: b21c1c6

**Comment by lervag** [comment]
Sorry, that was a regression error that I strangely never noticed. I'm also adding a test now. Thanks for reporting!
