### ISSUE TITLE
`\lv` broken since d9b30f9: `\lv` opens new instance of zathura, synctex forward search not working

### ISSUE THREAD

**Issue by nasenatmer** [lervag/vimtex#125]
Heya, great to see these massive code cleanups! Thanks a lot for your work on `vim-latex`!

However, it seems that d9b30f9 broke `\lv`: With `view_method` set to `zathura`, it opens a second instance of it although one has been started by `\ll` already.

Also, forward search isn't working anymore for those windows opened by `\lv`. This is the output of `\li`

```vim
b:latex.id         0
b:latex.fold_parts
  1  ^\s*\(\\\|% Fake\)subsection\>

g:latex#data[0]
  pid   8022
  name  01.weltbevölkerung-und-china
  base  01.weltbevölkerung-und-china.tex
  root  /home/jakob/doc/schule/sozialkunde/migration_und_demographie/06-bevölkerungslage-deutschland
  tex   /home/jakob...gration_und_demographie/06-bevölkerungslage-deutschland/01.weltbevölkerung-und-china.tex
  aux   /home/jakob...gration_und_demographie/06-bevölkerungslage-deutschland/01.weltbevölkerung-und-china.aux
  out   /home/jakob...gration_und_demographie/06-bevölkerungslage-deutschland/01.weltbevölkerung-und-china.pdf
  log   /home/jakob...gration_und_demographie/06-bevölkerungslage-deutschland/01.weltbevölkerung-und-china.log
  command: compile
    cd '/home/jakob/doc/schule/sozialkunde/migration_und_demographie/06-bevölkerungslage-deutschland' && max_prin
t_line=2000 latexmk -pdf -e '$pdflatex =~ s/ / -file-line-error /' -outdir=. -pvc -e '$success_cmd = "vim --serve
rname VIM --remote-expr \"latex\#latexmk\#callback(1)\""' -e '$failure_cmd = "vim --servername VIM --remote-expr
\"latex\#latexmk\#callback(0)\""' -e '$new_viewer_always = "0"' -e '$pdf_previewer = "start zathura  -x \"/usr/bi
n/vim --servername VIM --remote +\%{line} \%{input}\" \%S"' '01.weltbevölkerung-und-china.tex' &>/tmp/jakob/vQsad
al/1
  command: view
    zathura  -x "/usr/bin/vim --servername VIM --remote +\%{line} \%{input}" '/home/jakob/doc/schule/sozialkunde/
migration_und_demographie/06-bevölkerungslage-deutschland/01.weltbevölkerung-und-china.pdf'
```

Note: This also happens if the filename doesn't contain umlauts :)

**Comment by lervag** [comment]
I'm not sure if the bug fix is enough, but could you please try?

**Comment by nasenatmer** [comment]
Partly: No additional windows opening anymore.

But: forward search still not working with `\lv`

`gb` foreward search still works, however:
```vim
nnoremap <expr><buffer><silent> gb  ':!zathura --synctex-forward '.line(".").':'.col('.').':% ' . shellescape(g:latex#data[b:latex.id].out()) . ' >/dev/null<CR> <C-L>'
```

**Comment by lervag** [comment]
Please test now. I've made some finishing touches to the new implementation. I think it should work now.

**Comment by nasenatmer** [comment]
Indeed, no additional windows spawning anymore and both `\ll` and `\lv` atomatically enable forward search.

However, this commit introduced another new bug: 
1. open tex file (e.g. mwe from #117)
2. press `\ll`
3. `zathura` opens
4. vim window is blank (can be re-drawn by pressing `<ctrl-l>`)

Am I the only one with these frequently happening blanking outs? Also tried this with minimal vimrc and without tmux, so I'm without a clue as to why this only happens to me…

**Comment by nasenatmer** [comment]
Actually, the `vim` buffer goes blank everytime I write the file and the pdf gets updated. Like this:

1. open tex file
2. press `\ll`
3. `zathura` opens, `vim` goes blank
4. `<ctrl-l>` to redraw vim buffer
5. edit tex file
6. save file `:write`
7. `zathura` is updated on current synctex position
8. `vim` buffer is blank

**Comment by lervag** [comment]
This is strange. I am not able to reproduce this issue. :(

Can you provide the minimal working example in full detail? I'll assume the tex file from #117, so I need:
1. vimrc (preferably minimal version with vim-latex settings)
2. vim version
3. steps to reproduce in full detail

Does it happen for gvim or only vim in terminal? If I understood correctly, it happens also for vim in terminal outside of tmux (so tmux is irrelevant), right?

**Comment by nasenatmer** [comment]
Alright, sorry for the delay, Berlin nightlife brought my days out of order. Also, I sanitized my vim setup, so here's the package:

1. minimal [`vimrc`](https://github.com/nasenatmer/dotfiles-bone2/blob/testing/vimrc-minimal)
2. vim version: 7.4.617-1

MWE:
```tex
\documentclass{scrartcl}
\begin{document}
Word
\newpage
Word2
\end{document}
```

Steps to reproduce:
1. open mwe
2. `\ll`
3. `zathura` opens, `vim` goes blank
4. `<C-L>` redraws vim buffer, all is fine.
5. change anything in tex file
6. `:write` prompts recompilation, `zathura` updates accordingly, `vim` goes blank again

Here's the output of `\li`
```vim
b:latex
  id : 0
  fold_parts :

g:latex#data[0] : mwe
  root : '/home/jakob/tmp/latex/mwe'
  aux : '/home/jakob/tmp/latex/mwe/mwe.aux'
  log : '/home/jakob/tmp/latex/mwe/mwe.log'
  out : '/home/jakob/tmp/latex/mwe/mwe.pdf'
  tex : '/home/jakob/tmp/latex/mwe/mwe.tex'
  tmp : '/tmp/jakob/v6jpkW3/1'
  pid : '6325'
  cmd_latexmk_compile : 'cd ''/home/jakob/tmp/latex/mwe'' && max_print_line=2000 latexmk -pdf -e ''$pdflatex =~ s/
/ -file-line-error /'' -outdir=. -pvc -e ''$success_cmd = "vim --servername VIM --remote-expr \"latex\#latexmk\#cal
lback(1)\""'' -e ''$failure_cmd = "vim --servername VIM --remote-expr \"latex\#latexmk\#callback(0)\""'' -e ''$new_
viewer_always = "0"'' -e ''$pdf_previewer = "start zathura  -x \"/usr/bin/vim --servername VIM --remote +\%{line} \
%{input}\" \%S"'' ''mwe.tex'' &>/tmp/jakob/v6jpkW3/1'
  base : 'mwe.tex'
  labels : function('<SNR>35_gather_labels')
  viewer :
    xwin_id : '37748739'
    class : 'Zathura'
    cmd_start : 'zathura  -x "/usr/bin/vim --servername VIM --remote +\%{line} \%{input}" ''/home/jakob/tmp/latex/m
we/mwe.pdf'''
    cmd_forward_search : 'zathura --synctex-forward 3:5:''/home/jakob/tmp/latex/mwe/mwe.tex'' ''/home/jakob/tmp/lat
ex/mwe/mwe.pdf'''
    init : function('21')
    view : function('22')
    start : function('23')
    forward_search : function('24')
    latexmk_callback : function('25')
    latexmk_append_argument : function('26')
    focus_vim : function('<SNR>33_focus_vim')
    xwin_exists : function('<SNR>33_xwin_exists')
    xwin_get_id : function('<SNR>33_xwin_get_id')
```

I wonder whether it's possible to add a `<C-L>` in vim after the execution of the `:write` function or so to prompt redrawing the screen?

**Comment by lervag** [comment]
First, I am sure this is happening after each call of `latex#latexmk#callback()`, which you can find in `autoload/latex/latexmk.vim`. Thus you could experiment a little bit yourself and see if you can find exactly what code makes a redraw necessary.

It seems, as you've said yourself, that this is the exact same issue as the one you have mentioned in #117 for MuPDF, so when this is solved then I think we solve it also for MuPDF.

Unfortunately, I am not able to reproduce this. Everything seems to be working well here. I think the easiest way to debug this is if you could do some testing yourself. I would propose you first try to comment out lines 91 to 93 ([here](https://github.com/lervag/vim-latex/blob/master/autoload/latex/latexmk.vim#L91)). That will remove the zathura callback, see [here](https://github.com/lervag/vim-latex/blob/master/autoload/latex/view.vim#L391). If it works, then the next step is to test which of the calls in `zathura.callback..` is creating the problem. And so forth...

**Comment by nasenatmer** [comment]
After deactivating [prezto](https://github.com/sorin-ionescu/prezto), my zsh configuration, I went back to try `bash` and there seems to be no redrawing problem with it. So maybe `zsh` is the bad boy here.

Your suggestion to look at the various calls in `zathura.latexmk_callback` was the right track. When I comment out `call self.focus_vim()`, I get normal behaviour and everything is fine, there's just no re-focusing of vim after the callback (which I would be ok with).

But delving deeper into `view.vim`, I found that [L468](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/view.vim#L468) seems to be the problem. It blanks out my vim buffer. Adding a new line below with a simple `redraw!` solves the whole issue.

So with this as the only change, all of the problems reported in this issue are solved. How nice!

**Comment by lervag** [comment]
Great, thanks for looking into this!

Could you remove `silent` from L468 and see what output it gives?

In any case, now I know what causes the need for `redraw!`. I'll try to look into which cases should require a `redraw!`, just to understand if this `redraw` is natural, or if it might be due to a bug or something.

**Comment by lervag** [comment]
Ah, could you also try to change `silent` to `silent!`?

**Comment by lervag** [comment]
It seems the `redraw!` is necessary here, so I've added it. I found this in the docs for `:h :silent`:

> ":silent" will also avoid the hit-enter prompt.  When
> using this for an external command, this may cause the
> screen to be messed up.  Use |CTRL-L| to clean it up
> then.

**Comment by lervag** [comment]
Oh, and btw (sorry for the spam): The reason I was not able to reproduce at once was because I didn't realize this was a terminal only issue. I was trying to reproduce from `gVim`, but the issue never occured there.

**Comment by nasenatmer** [comment]
Works like a charm now! I also like the new highlighted messages from dda6f1fc859615c18d2f2efca60107967cb2da38.

Thanks so much for your help in debugging here!

**Comment by lervag** [comment]
Great! And thanks, I'm working on making all the messages highlighted. There are a couple of messages left, but it's getting there.
