### ISSUE TITLE
%!TEX program parsing feature gives confusing error message 

### ISSUE THREAD

**Issue by CareF** [lervag/vimtex#1251]
# Explain the issue

I found some projects giving `% !TEX TS-program = luatex` heading (e.g. https://github.com/darwiin/yaac-another-awesome-cv) and I didn't realize at first it's the reason when the error message says latexmk get 2 filename: 

    Latexmk: Need to specify exactly one filename for preview-continuous mode     
          4     but 2 were specified 

I realize it's a feature to parse these kinds of heading for configuration, but I still hope suggest better handling for this case. Plus the url (https://tex.stackexchange.com/questions/78101/when-and-why-should-i-use-tex-ts-program-and-tex-encoding) mentioned in docs also listed TS-program keywords. 

Thank you again for this excellent plugin! 

--------

1. A minimal `vimrc` file, for instance:
N/A

2. A minimal `.tex` file, such as:

    ```tex
    % !TEX TS-program = luatex
    \documentclass{article}
    \begin{document}
    a
    \end{document}

    ```

**Comment by lervag** [comment]
I do not quite understand what is the expected reaction to the `% !TEX TS-program` directive. Are you asking that I ensure that it is ignored?

**Comment by CareF** [comment]
Thank you for the reply! 
My assumption would be making `#!TEX TS-program` equivalent with `#!TEX program`, and ignore any unspecified directive.

**Comment by andymass** [comment]
I assume the problem is `luatex` is not listed as an engine in `g:vimtex_compiler_latexmk_engines`.  But the error message does not make much sense.

**Comment by lervag** [comment]
Yes, @andymass may be correct. There was no option `-luatex` for `latexmk`. I've mapped `luatex` to `lualatex`, which I assume should work. Let me know if this fixes your issue.

**Comment by CareF** [comment]
Sorry but I just got a chance to test. 
For the case I gave, it still gives `vimtex: Compilation failed!`, without any error message.
Change the heading to `#!TEX program=luatex` or `lualatex` doesn't help. 
But anyway, it's better than before.

**Comment by lervag** [comment]
> Change the heading to #!TEX program=luatex or lualatex doesn't help.

That should neither help nor be necessary.

> But anyway, it's better than before.

Why is it better than before? What works now that did not work before?

So, to continue, it is important to get a full example that I can use to reproduce this problem. Please provide:

1. A minimal vimrc file.
2. A minimal TeX file (unless you can still reproduce this with the example provided initially).
3. Possibly any `.latexmkrc` that you may be using (a minimal version; please first check if the problem goes away by removing it).

It could also be useful to get output from the following:

1. `:VimtexInfo` after you have opened a relevant TeX file.

2. `:VimtexOutput` after you have tried to start compilation, i.e., after the `vimtex: Compilation failed!` message appears.

**Comment by lervag** [comment]
What happens if you run `lualatex  -file-line-error -synctex=1 -interaction=nonstopmode -recorder  "a.tex"` in a terminal?

**Comment by CareF** [comment]
```
This is LuaTeX, Version 1.07.0 (TeX Live 2018) 
 restricted system commands enabled.
(./a.tex
LaTeX2e <2018-04-01> patch level 5
```

**Comment by lervag** [comment]
Where exactly do you see this `Latexmk: Need to specify exactly one filename for preview-continuous mode` message?

**Comment by lervag** [comment]
This is the output for me:

```
> lualatex -file-line-error -synctex=1 -interaction=nonstopmode -recorder "a.tex"
This is LuaTeX, Version 1.07.0 (TeX Live 2018/Arch Linux) 
 restricted system commands enabled.
(./a.tex
LaTeX2e <2018-04-01> patch level 5
(using write cache: /home/lervag/.texlive/texmf-var/luatex-cache/generic)(using
 read cache: /var/lib/texmf/luatex-cache/generic /home/lervag/.texlive/texmf-va
r/luatex-cache/generic)
luaotfload | main : initialization completed in 0.080 seconds (/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo(load luc: /home/lervag/.texliv
e/texmf-var/luatex-cache/generic/fonts/otl/lmroman10-regular.luc)))
No file a.aux.
[1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./a.aux))
 355 words of node memory still in use:
   2 hlist, 1 vlist, 1 rule, 2 glue, 3 attribute, 45 glue_spec, 3 attribute_lis
t, 1 write nodes
   avail lists: 2:15,3:3,4:1,5:21,6:1,7:14,8:1,9:6
</usr/share/texmf-dist/fonts/opentype/public/lm/lmroman10-regular.otf>
Output written on a.pdf (1 page, 2533 bytes).
SyncTeX written on a.synctex.gz.
Transcript written on a.log.
```

**Comment by CareF** [comment]
Sorry I didn't make it clear. 
When I say it's better than before, I mean this confusing message no longer shows.

**Comment by CareF** [comment]
OK... It's a bug for lualatex now. Thank you for your help! 

It's weird.. I can get an output with sudo, otherwise but lualatex stops like I posted before..

**Comment by CareF** [comment]
Just for future reference if anyone encountered this lualatex stops at the beginning position: 
I found a `.texlive2018` directory under `~/`, but owned by root. Not sure why but it's possible I accidentally ran lualatex as sudo (I have `Defaults env_keep += "HOME"` for my sudo config). After I removed this directory everything goes fine.

**Comment by lervag** [comment]
Great, I'm happy to see that you've figured things out! And happy to help! Oh, and thanks for the donation; I'll be thinking of you when I buy my next beer/coffee :)

**Comment by ebarojas** [comment]
@lervag I get this error when using

```%!TEX program = latex```

on my main.tex with neovim

I'm also using the ```%!TEX root``` directive

The only way I've managed to made it work is removing that first line, which provides some compatibility issues with my other environments.

_I've tried to change some config, but unsure if this is an ```nvr```problem or is easily configurable._
