### ISSUE TITLE
Completion of bibtex items (and possibly others) broke

### ISSUE THREAD

**Issue by kmarius** [lervag/vimtex#1257]
Commit https://github.com/lervag/vimtex/commit/d21cb52106345ade2ec266b505694bc0076031ee broke omni completion for bibtex entries. Completion candidates used to be filtered in https://github.com/lervag/vimtex/blob/3716a8ab1ea256ab4f98c3c1ce0cd44c82473138/autoload/vimtex/complete.vim#L175 against the regex `a:regex`, however in the function `s:filter_with_options` the regex is changed to `'^' . a:regex`:
https://github.com/lervag/vimtex/blob/3716a8ab1ea256ab4f98c3c1ce0cd44c82473138/autoload/vimtex/complete.vim#L794
 This is the way lines used to be filtered when completing commands (which is what this commit addressed). Calling `s:filter_with_options` as `s:filter_with_options(lines, '.*' . a:regex`) fixes the problem, the better solution would probably be not changing the regex in `s:filter_with_options` and calling it with `'^' . a:regex` where necessary. I don't know what the expected behaviour for completion of the different items is.

**Comment by clason** [comment]
Funny, it's still working with `ncm2` autocompletion on current master (but indeed not with omnicompletion if `ncm2` is disabled).

**Comment by lervag** [comment]
Sorry, my mistake. I think this is fixed now.
