### ISSUE TITLE
$out_dir of latexmk can be absolute path

### ISSUE THREAD

**Issue by itouen** [lervag/vimtex#1263]
When I set `$out_dir` to an absolute path in `.latexmkrc`, vimtex creates unnecessary directories.

E.g.  `$out_dir='/Users/aaa/Documents/latexmk_out';` and latex root directory (self.root in vimtex) is `/Users/aaa/tex`, directories are created in `/Users/aaa/tex`. Directories should be created in `$out_dir`.

I think the following code in `autoload/vimtex/compiler/latexmk.vim` creates directories.

``` vim
  "
  " Create build dir if it does not exist
  "
  if !empty(self.build_dir)
    let l:dirs = split(glob(self.root . '/**/*.tex'), '\n')
    call map(l:dirs, 'fnamemodify(v:val, '':h'')')
    call map(l:dirs, 'strpart(v:val, strlen(self.root) + 1)')
    call vimtex#util#uniq(sort(filter(l:dirs, "v:val !=# ''")))
    call map(l:dirs, "self.root . '/' . self.build_dir . '/' . v:val")
    call filter(l:dirs, '!isdirectory(v:val)')

    " Create the non-existing directories
    for l:dir in l:dirs
      call mkdir(l:dir, 'p')
      echomsg 'created: ' . l:dir
    endfor
  endif
```

I think the concatenation of `"self.root . '/' . self.build_dir . '/' . v:val"` is the problem.
OTOH, should vimtex create the directories? I think latexmk will create directories as necessary.

**Comment by lervag** [comment]
Yes, you're right, there's a bug there. Fixing asap. Note, this code is needed, because `latexmk` does not create subdirectories in the out dir.

**Comment by itouen** [comment]
@lervag Thanks! I confirmed the problem is fixed on my environment (macOS).

By the way, checking if `self.build_dir[0] !=# '/'` also works on Windows? (no need to consider drive letter)? I'm sorry I don't know well about drive letters on Windows.

**Comment by itouen** [comment]
@lervag Thank you for the response. But I found some new problem.

I noticed that the existence of the trailing slash affects the result of `fnamemodiry`.

**Case 1:** `self.build_dir` is `/foo/bar` (no trailing slash)
`fnamemodify(self.build_dir, ':p')` returns `/foo/bar/`
and `(self.build_dir !=# fnamemodify(self.build_dir, ':p')` is false.

**Case 2:** `self.build_dir` is `/foo/bar/` (with trailing slash)
`fnamemodify(self.build_dir, ':p')` returns `/foo/bar/`
and `(self.build_dir !=# fnamemodify(self.build_dir, ':p')` is true.


In addition, the issue of https://github.com/vim-jp/issues/issues/1202 (sorry in Japanese) says that `fnamemodify('foo/bar', ':p')` returns different result on Windows and UNIX if the directory `foo/bar` does not exist.
In Windows, it returns absolute-path. In UNIX, it returns `foo/bar`.

Detecting absolute-path on Windows seems to be a little complicated...

**Comment by lervag** [comment]
Hmm, I see. In that case, I'll revert my last commit and instead leave the issue unresolved for Windows for now. If it should be that someone raises the issue from Windows, I'll rather solve it then. :)
