### ISSUE TITLE
Unicode support in TOC

### ISSUE THREAD

**Issue by AmiZya** [lervag/vimtex#1264]
Hello Dr Lervag,

I have a problem when writing a latex file in french, in the TOC it doesn't look like expected.

I attached a screenshot to have an idea.

<img width="570" alt="screen shot 2018-12-01 at 6 50 44 pm" src="https://user-images.githubusercontent.com/407471/49331383-c2ae4a80-f593-11e8-8505-0fd07580a62d.png">

**Comment by lervag** [comment]
I have not seen that before. However, I can't say what's wrong. Can you provide more info?

Please, read the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md).

**Comment by AmiZya** [comment]
Sorry for the bloated issue report.

The problem is that certain french words with accents are not shown as expected.

In the third line of the screenshot you can see "D<e9>didaces" instead of "Dédicaces". 

I hope I was clear this time

**Comment by lervag** [comment]
No, sorry, I understood your problem. But I can't help you if I can't reproduce the problem. Please, again: **Read the issue template**. In particular, please provide a minimal example (LaTeX) and a minimal vimrc file.

It will also help to get more info:
- Which OS (windows, Linux, etc)?
- Which version of Vim/neovim?

**Comment by Konfekt** [comment]
Perhaps `set encoding=utf-8` already helps. A minimal `vimrc` would be helpful.
