### ISSUE TITLE
save .bib file "Undefined variable: b:vimtex"

### ISSUE THREAD

**Issue by dylnmc** [lervag/vimtex#1266]
will make issue better later. no time now. I keep getting tens of errors that flood the screen when I ues this plugin with bibtex and I am in the .bib file and save it:

![screenshot from 2018-12-04 10 51 04](https://user-images.githubusercontent.com/7635158/49454283-d7b4f480-f7b2-11e8-8e20-aa7c0092877f.png)

please fix

**Comment by lervag** [comment]
I think it is fixed now.
