### ISSUE TITLE
Forward and backward search does not work in multi-file project (with zathura)

### ISSUE THREAD

**Issue by tidues** [lervag/vimtex#1269]
I use neovim with zathura, and have xdotool installed. The forward and backward search work perfectly in a single file project, but in the multi-file case neither works.  I use subfiles package, and the project can be correctly compiled. I don't know if this multi-file forward/backward feature has not been supported yet, or something is wrong at my end. Thanks!

**Comment by lervag** [comment]
Try to set "let g:tex_flavor = 'latex'" in your vimrc file.

Den ons. 5. des. 2018, 18:47 skrev tidues <notifications@github.com>:

**Comment by tidues** [comment]
I had that in my vimrc setting. My current setting is:

let g:Tex_DefaultTargetFormat='pdf'
let g:vimtex_view_enabled=1
let g:vimtex_view_automatic=1
let g:vimtex_view_general_viewer = 'zathura'
let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_progname = 'nvr'
let g:tex_flavor = "latex"

**Comment by lervag** [comment]
Well, first: you don't need to set the `general_viewer` option when you set the view method to `zathura`. Next, you don't need to set `view_enabled` and `view_automatic`, because these are already enabled by default.

Finally, and much more importantly, the first option, `g:Tex_DefaultTargetFormat` is an option for LaTeX-Suite or LaTeX-Box, not for vimtex. This hints that you may be trying to run multiple LaTeX plugins for Vim at the same time. This won't work. A common mistake is to use vim-polyglot (a mistake in itself, if you ask me) and forget to disable LaTeX-Box.

**Comment by tidues** [comment]
Thank you for these info. I think I found the reason why it didn't work. I worked inside  the pcloud virtual drive, where actually some of the files were not really exist locally. Now, I tried things locally, the forward and backward search worked almost perfectly. 

Except one thing, every time after a backward search (ctrl+right click in zathura), I cannot perform forward search in the same tex file (say section1.tex) by \lv, until I move to a different one (say section2.tex). Do you know any way to fix this? I appreciate a lot!

**Comment by lervag** [comment]
Again, this should just work, and I have no idea why it does not work. Please, adhere to the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md), in particular the part about the minimal example.

**Comment by rubenvereecken** [comment]
@lervag I had the same issue. Removing the `general_viewer` option of course fixed it, I'm not sure why it was there in the first place. Beautiful!

**Comment by tidues** [comment]
I checked one more time this morning, it seems everything is good now. Thank you for your help!

I still have a different problem encountered on my laptop, I have almost the same environment there, but the weird thing is that the backward search works perfectly in both single file or multi-file cases, but neither can perform the forward search. Another thing I noticed is that, usually after compiling the project, the pdf showing in zathura will have green block at the first line indicating the selected area. But this green block wasn't showing there. I think this might be caused by the same problem. I have xdotool and nvr installed there, also changed the vimrc setting as you suggested.

Please let me know if you want me change the thread to talk about this, and any further information you needed. Thanks!

**Comment by lervag** [comment]
Good to hear things are working on 1/2 computers. So, to your laptop. Let's continue here, no need for a new issue.

Can you try to create a minimal example of your issue in the lines of:

1. Minimal vimrc file that you start with `vim -n minivimrc test.tex`.
2. Minimal `test.tex` file.
3. Explain the steps to reproduce the problem, e.g.: "I open the file with the minimal vimrc file, then do `\lv`. I expect it to perform forward search, but XXX happens."

For examples of minimal files, see the issue template that I linked earlier.

**Comment by tidues** [comment]
So this is what I did:
First, I created a minimal vimrc file
```
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_progname = 'nvr'
let g:tex_flavor = "latex"
```
Then, I created a minimal test.tex file:
```
\documentclass{article}
\begin{document}

\section{Section 1}
Hello world 1.

\section{Section 2}
Hello world 2.

\section{Section 3}
Hello world 3.

\end{document}
```
After, I open the file with the command
```
nvim -u minivimrc test.tex
```
nothing strange so far.

In the next step, I compile the .tex file by \ll. The pdf showed up in the Zathura pdf viewer. As I mentioned before, there is **no** green block at the first row where it should be showing.

Next step, I moved the cursor in neovim to the line of "Hello world 1.", then entered the command \lv, but nothing happened.

Then, I clicked "Hello world 3." in the pdf file, the cursor in neovim jumped to the correct position.

Then again, I moved the cursor in neovim to the line of "Hello world 2.", and entered the command \lv, still nothing happened.

So, the forward search is no working there.

Some extra information maybe helpful:
my system is Ubuntu 18.04
neovim version is 0.3.1
zathura version is 0.4.1 with girara 0.3.0 and pdf-poppler 0.2.9
xdotool version is 3.20160805.1
nvr version is 2.1.0

Please let know if you need anything more.

Thanks!

**Comment by lervag** [comment]
Thanks! This is good information!

When you open the tex file with the minimal vimrc file, then do `\lv` to open the pdf (skip the `\ll`): do things work now? Can you post the output of `\li` as well?

It would also be interesting to see the compile command, which you find with `\li` after doing `\ll`.

Further, what's the output of `zathura --help|grep synctex`?

**Comment by tidues** [comment]
I opened the test.tex with minimal vimrc, then did `\lv`, one error showed up:
```
vimtex: Viewer cannot find Zathura window ID!
```
so I tried first open a blank zathura, then did the exact steps as above, that error didn't show up this time, but also nothing happened in the zathura, it was still blank. The `\li` info I got was
```
System info
  OS: Ubuntu 18.04.1 LTS
  Vim version: NVIM v0.3.1
  Has clientserver: true
  Servername: /tmp/nvimxymOyJ/0

vimtex project: test
  base: test.tex
  root: /home/tidues/tmp/vimtexminitest
  tex: /home/tidues/tmp/vimtexminitest/test.tex
  out: /home/tidues/tmp/vimtexminitest/test.pdf
  log: /home/tidues/tmp/vimtexminitest/test.log
  aux: /home/tidues/tmp/vimtexminitest/test.aux
  fls: /home/tidues/tmp/vimtexminitest/test.fls
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimxymOyJ/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Zathura
    xwin id: 48234499
    process: 
      pid: -
      cmd: zathura -x "nvr --servername /tmp/nvimxymOyJ/0 --remote-expr \"vimtex#view#reverse_goto(%{line}, '%{input}')\"" --synctex-forward 1:1:'/home/tidues/tmp/vimtexminitest/test.tex'  '/home/tidues/tmp/vimtexminitest/test.pdf' >/dev/null 2>&1 &
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
  document class: article
```

I reopened the file, and got `\li` info after compiling with `\ll`:
```
System info
  OS: Ubuntu 18.04.1 LTS
  Vim version: NVIM v0.3.1
  Has clientserver: true
  Servername: /tmp/nvimgCCFMq/0

vimtex project: test
  base: test.tex
  root: /home/tidues/tmp/vimtexminitest
  tex: /home/tidues/tmp/vimtexminitest/test.tex
  out: /home/tidues/tmp/vimtexminitest/test.pdf
  log: /home/tidues/tmp/vimtexminitest/test.log
  aux: /home/tidues/tmp/vimtexminitest/test.aux
  fls: /home/tidues/tmp/vimtexminitest/test.fls
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimgCCFMq/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    pid: 7793
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"nvr --servername /tmp/nvimgCCFMq/0 --remote +\%{line} \%{input}\" \%S"' -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'test.tex'
  viewer: Zathura
    xwin id: 50331651
    process: 
      pid: -
      cmd: zathura -x "nvr --servername /tmp/nvimgCCFMq/0 --remote-expr \"vimtex#view#reverse_goto(%{line}, '%{input}')\"" --synctex-forward 1:1:'/home/tidues/tmp/vimtexminitest/test.tex'  '/home/tidues/tmp/vimtexminitest/test.pdf' >/dev/null 2>&1 &
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
  document class: article
```
And the output of `zathura --help|grep synctex` was
```
  -x, --synctex-editor-command=cmd     Synctex editor (forwarded to the synctex command)
  --synctex-forward=position           Move to given synctex position
  --synctex-pid=pid                    Highlight given position in the given process
```

**Comment by lervag** [comment]
Strange. Opening zathura with `\lv` should work, so let's focus on that part first. So, given: `test.tex` that is compiled to `test.pdf`. If you open `test.tex` and do `\lv`, you are saying that Zathura does not open and there is an error message. Do I understand correctly?

The next step is to try to start Zathura from the command line with the same arguments. So, first, open `test.tex` in neovim in one terminal. Take note of the servername (`:echo v:servername`). Then, from a different terminal, do:

    zathura -x "nvr --servername <name> --remote-expr \"vimtex#view#reverse_goto(%{line}, '%{input}')\"" --synctex-forward 1:1:test.tex test.pdf

Obviously, you must use correct paths here. If you are opening from the same
directory, then I think it is OK to use relative paths (as suggested here). If
this works, then try again, now use the same full paths as used from vimtex.

**Comment by tidues** [comment]
That is very helpful. By running that command, I found out I didn't install the dbus-x11 package. After installed that, the forward search works as expected.

I really appreciate your help! I enjoy writing thing with your package very much!

**Comment by lervag** [comment]
Great, I'm happy to help and to hear that you benefit from vimtex! :)
