### ISSUE TITLE
Doesn't run bibtex and latex compilers enough times?

### ISSUE THREAD

**Issue by Ploppz** [lervag/vimtex#1271]
I use neovim, on Arch Linux.

Relevant part of vimrc:
```
let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_progname = 'nvr'
let g:tex_flavor = 'latex'
```

Latex file:
```
\documentclass[12pt]{article}%
\usepackage[a4paper, margin=2cm]{geometry}
\begin{document}

\title{T}
\author{E}
\date{\today}
\maketitle

Hey \cite{test}

\bibliography{../bibfile}
\bibliographystyle{plain}
\end{document}
```

Bib file:
```
@BOOK{test,
    AUTHOR = "author",
    TITLE = "book title",
    PUBLISHER = {publishing company},
    ADDRESS = {where published},
    YEAR = 2000}

```

Errors when typin `\ll` in vim:

```
  1 thesis.tex|10 warning| LaTeX Warning: Citation `test' on page 1 undefined on input line 10.                                                                                    
  2 thesis.tex|| LaTeX Warning: There were undefined references.      
```

According to [this](https://latex.org/forum/viewtopic.php?t=9280), it might have to do with the order of runs of latex and bibtex compilers.

**Comment by lervag** [comment]
I'm running a similar system (Arch Linux and neovim), and your example works perfectly with me. Was there a reason you place the bibfile in the parent directory? (Things work regardless for me, though.)

I've pushed the test files. Can you go to the test directory and try yourself with `nvim -u minivimrc`, then `\ll` to compile?

**Comment by Ploppz** [comment]
Thanks. I just had to change this in the vimrc, for nvim users:
```
let &rtp = '~/.local/share/nvim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.local/share/nvim/plugged/vimtex/after'
```

Indeed it works fine! So probably not an issue with vimtex. Thanks for constructing the test case.

**Comment by Ploppz** [comment]
I just tested it again and now it works fine... weird. Sorry for wasting your time.

**Comment by lervag** [comment]
No problem. Happy it works :)
