### ISSUE TITLE
Remapping vimtex-view does not work 

### ISSUE THREAD

**Issue by soerenwolfers** [lervag/vimtex#1273]
If I remap vimtex-view to F5 (or anything else), and then press F5, nothing happens (after pressing `\ll` first)
I am using vim 8.1 with all features enabled.

1. A minimal `vimrc` file:

    
```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
let g:vimtex_view_method = 'zathura'
nnoremap <F5> <Plug>(vimtex-view)  
```                            

2. A minimal `.tex` file:

```
\documentclass{minimal}
\begin{document}
test
\clearpage
test
\end{document}
```

**Comment by lervag** [comment]
You need to use a recursive mapping: `map <f5> ...`, not `nnoremap ...`.
