### ISSUE TITLE
Navigating stops compiler?

### ISSUE THREAD

**Issue by Astrantia** [lervag/vimtex#1275]
Using \lt to navigate between different files in the same project sometimes stops the active compiler and doesn't stop other times. Why is there this incosistent behavior?

**Comment by lervag** [comment]
I have not experienced this problem, and so it is not easy to answer. It is near impossible to answer if you can't provide a reproducible example.

**Comment by Astrantia** [comment]
```
Plug '907th/vim-auto-save'
autocmd FileType tex let g:auto_save = 1
autocmd FileType tex let g:auto_save_silent = 1
augroup vimtex_event_1
  au!
  au User VimtexEventQuit     call vimtex#compiler#clean(0)
  au User VimtexEventInitPost call vimtex#compiler#compile()
augroup END
function! CloseViewers()
  if executable('xdotool') && exists('b:vimtex')
     \ && exists('b:vimtex.viewer') && b:vimtex.viewer.xwin_id > 0
    call system('xdotool windowclose '. b:vimtex.viewer.xwin_id)
  endif
endfunction
augroup vimtex_event_2
  au!
  au User VimtexEventQuit call CloseViewers()
augroup END
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
```
This is my vimrc. What else can I provide to debug this?

**Comment by Astrantia** [comment]
@lervag Thanks for your responses. Unfortunately, I forgot to include tex flavor in my my virmc
```vim
Plug '907th/vim-auto-save'
autocmd FileType tex let g:auto_save = 1
autocmd FileType tex let g:auto_save_silent = 1
augroup vimtex_event_1
  au!
  au User VimtexEventQuit     call vimtex#compiler#clean(0)
  au User VimtexEventInitPost call vimtex#compiler#compile()
augroup END
function! CloseViewers()
  if executable('xdotool') && exists('b:vimtex')
     \ && exists('b:vimtex.viewer') && b:vimtex.viewer.xwin_id > 0
    call system('xdotool windowclose '. b:vimtex.viewer.xwin_id)
  endif
endfunction
augroup vimtex_event_2
  au!
  au User VimtexEventQuit call CloseViewers()
augroup END
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
let g:tex_flavor = 'latex'
```

This is the minimal vimrc. Now the files are the following:
1. Create directory reproduce/
2. Create root.tex in reproduce/
3. Create first.tex in reproduce/sections
4. Create second.tex in reproduce/sections
5. Create third.tex in reproduce/sections
6. Create fourth.tex in reproduce/sections
7. Create fifth.tex in reproduce/sections
8. Put this in root:
```vim
\documentclass[a4paper]{article}

\usepackage[utf8]{inputenc}
\usepackage[T1]{fontenc}
\usepackage{textcomp}
\usepackage[dutch]{babel}
\usepackage{amsmath, amssymb}

\begin{document}
\input{sections/first.tex}
\input{sections/root.tex}
\input{sections/third.tex}
\input{sections/fourth.tex}
\input{sections/fifth.tex}
\end{document}
```
9. Fill sections with random tex
10. Start \ll auto compiling
11. Navigate between files with \lt 5-6 times. It should be enough to hit a case when compiler stops

**Comment by lervag** [comment]
> This is the minimal vimrc. Now the files are the following:

This is not minimal. If I use this and do `vim -u minivimrc`, it does not work. Thus, it is not minimal. Please read my previous post again.

**Comment by lervag** [comment]
Just FYI, I do not intend to be dismissive or difficult here. The problem is, without a good and reproducible example, I can't really help you. And your description so far is incomplete. Perhaps the problem is on my end in explaining what I need, but I believe that my [previous comment](https://github.com/lervag/vimtex/issues/1275#issuecomment-445304336) really do explain how to create such a minimal example.

Note, the only thing I'm missing now is a good minimal vimrc file that I can use with `vim -u minivimrc`. Feel free to read the help text on the `-u` option, `:help -u`.

**Comment by Astrantia** [comment]
@lervag Thanks. I'll reopen this when I'm able to properly set up a minimum reproduction.

**Comment by lervag** [comment]
Great, thanks. If you have questions, let me know.
