### ISSUE TITLE
Allow creation of map to open viewer without highlighting forward search

### ISSUE THREAD

**Issue by soerenwolfers** [lervag/vimtex#1277]
I would like the ability to (sometimes, not always) use \lv or VimtexView and perform a forward search (go to the correct page) but not highlight the result of the forward search. The highlighting (green bars in zathura) can be distracting when creating graphical content (mostly using beamer, in my case).  

The ideal thing would be to expose variant mappings/commands such as \lV, VimtexView! and vimtex-view-no-forward-search (just hypothetical examples).

**Comment by Konfekt** [comment]
Maybe best to change the highlighting color in `zathurarc`?

**Comment by Konfekt** [comment]
By the way, `mupdf`, in lieu of `zathura`, will jump to the corresponding page, but not highlight anything.
