### ISSUE TITLE
Installing with vim-plug

### ISSUE THREAD

**Issue by dumuzidsafi** [lervag/vimtex#1278]
I am getting an error about accessing a remote repository when using :PlugInstall in gvim.

```
call plug#begin('~/.vim/plugged')
Plug 'PotatoesMaster/i3-vim-syntax'
Plug 'jreybert/vimagit'
Plug 'lervag/vimtex'
call plug#end()
```

Please reassure me that I'm not insane and have not made a typo.

I saw a comment elsewhere about linking git accounts to the PC, so I'll go and read on that in the meantime to see if that is the root cause. The other packages install and work fine.

**Comment by lervag** [comment]
I can't see anything wrong here. Can you provide more exact what the error message is?

**Comment by lervag** [comment]
I don't understand what this has to do with AUR packages and `yay`. In any case, it seems there must be something wrong on your end. Let me know if there is anything else I can help with.
