### ISSUE TITLE
E716: Key not present in Dictionary: view

### ISSUE THREAD

**Issue by Mueslii** [lervag/vimtex#1281]
Hello,

I'm using Windows 8.1 x64 and gVim 8.0. I've installed vimtex recently and the command ```\lv``` doesn't seem to work and yields the error (I've also tried to remap it to F8 but nothing changes): 
```
E716: Key not present in Dictionary: view
```
I didn't realize it before but when I open latex files it appears the following message:
```
Selected viewer is not executable
- Selection: SumatraPDF
- Please see :h g:vimtex_view_general_viewer
```

My minimal vimrc setup is:
 ```
    call plug#begin('~/vimfiles/plugged')
    Plug 'lervag/vimtex'
    call plug#end()
	
    filetype plugin on
    syntax on

    let g:vimtex_compiler_method='arara'
    let g:vimtex_view_general_viewer = 'SumatraPDF'
```

And the minimal latex file is:
```
    % arara: pdflatex
    \documentclass[a4paper]{article}
    \begin{document}
    A thing here and something there.
    \end{document}
```

**Comment by Konfekt** [comment]
Have you typed `:h g:vimtex_view_general_viewer` into Vim and read it through? Do you have `SumatraPDF` installed?

**Comment by Mueslii** [comment]
Yes, I extracted the ```let g:vimtex_view_general_viewer = 'SumatraPDF'``` option from there. I also have Sumatra installed.

**Comment by Konfekt** [comment]
Perhaps an issue of a wrong path, or one which is not escaped for the shell. Have you tried adding the folder that contains the executable of `sumatra` to the %PATH (for example, by http://www.rapidee.com/)? 

Does the path to the executable contain a space?

**Comment by Mueslii** [comment]
Adding the location of the executable to %PATH solved the problem. Thanks!

**Comment by lervag** [comment]
Thanks, @Konfekt, for helping to solve the issue!
