### ISSUE TITLE
Certain documents: No latex errors, but \ll does not open PDF window

### ISSUE THREAD

**Issue by Ploppz** [lervag/vimtex#1284]
OS: Arch Linux
neovim: NVIM v0.3.1
 (I have installed `nvr`)

Relevant part of `init.vim`:
```
let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_progname = 'nvr'
let g:tex_flavor = 'latex'
```

Latex document:

```
\documentclass[12pt]{article}%
\usepackage[a4paper, margin=2cm]{geometry}

\usepackage[colorinlistoftodos]{todonotes}

\begin{document}

\title{Title}
\author{Author}
\date{\today}
\maketitle

\section{Introduction}
Hello (\todo{something})

\end{document}
```

My problem is that when typing `\ll` in certain documents (for example the above), no zathura window opens to view the PDF.  I get no errors in neovim: nothing in `:messages` and nothing in `:lopen` or `:copen`, so it's hard to tell what's wrong.

However, if I don't include the `todonotes` packages and don't use `\todo`, it works just fine.

**Comment by Ploppz** [comment]
I have this problem on my laptop, but I cannot reproduce on my desktop, with the exact same `init.vim`. I'm now updating the system and nvim plugins on both computers.

**Comment by lervag** [comment]
I can't reproduce this either. Let me know after you've tried to update everything.

**Comment by Ploppz** [comment]
I haven't had the problem since.

**Comment by lervag** [comment]
Great, good to hear it.
