### ISSUE TITLE
cse takes effect even when cancelled with <Esc>

### ISSUE THREAD

**Issue by soerenwolfers** [lervag/vimtex#1286]
When `cse` is cancelled it still takes effect, using the argument that was previously used with `cse`.

1. A minimal `vimrc` file:

    ```vim
    set nocompatible
    call plug#begin('~/.vim/plugged')
    Plug 'lervag/vimtex'
    call plug#end()
    filetype plugin indent on
    ```

2. A minimal `.tex` file:

    ```tex
    \documentclass{minimal}
    \begin{document}

    \begin{itemize}
        \item test
    \end{itemize}

    \end{document}
    ```

3. A concise description of the issue and **the steps to reproduce** it: 
First press `cse` with the cursor at "test" and then type `enumerate<CR>`.
Then move the cursor on the empty line after `\begin{document}` and press `cse`. Cancel with `<Esc>`.

**The `document` environment is changed to an `enumerate` environment. I expected it stay the same.**

**Comment by lervag** [comment]
Should be fixed now.
