### ISSUE TITLE
Change name of plugin

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#129]
I'm considering to change the name of the plugin. The name was chosen without much thought to it, and I didnt notice immediately that the well known plugin LaTeX-Suite was also known as Vim-LaTeX (http://vim-latex.sourceforge.net/).

My initial idea for a change of name is: `vimtex`. Other ideas are `vlatex` or `vatex`, or perhaps `latex.vim`. Note that a short name is very conventient, as it makes all options and commands shorter to type.

I'd very much like some input to this issue, as a change of names is not something done lightly.
@Konfekt @nasenatmer

**Comment by Rmano** [comment]
I think that a good name should be short, avoid clashes now and in the future... and point to what the plugin is. What about `kyl-vimtex`?

**Comment by lervag** [comment]
Agreed. Though why not just `vimtex`?

**Comment by Rmano** [comment]
I like it, but the problem for `vimtex` is that it will be difficult to search for; lot of hits already. I was suggesting to personalize it a bit more ;-).... in the end is your brainchild! (Really, whatever will work.)

**Comment by lervag** [comment]
Hmm, I didn't find any other plugin named `vimtex` during my first try. Now I noticed [this one](https://github.com/Disuke/vimtex), but that is only a clone of LaTeX-Suite/Vim-LaTeX.

I don't really want to have a personal name for it, just a simple, short, and good name, that is not used by anyone else. I don't want to change the name more than once, since this is going to affect everyone who uses the plugin (they need to change their github origin, as well as all of their options).

So far, I think `vimtex` is a good candidate. But I'll definately consider other names if anyone has any good ideas.

**Comment by Konfekt** [comment]
From a pragmatic standpoint vimtex is close to perfect as the name should tell people that this is something related to vim and tex and be concise. 

On the flipside, perhaps it's not unique enough. Try vitex, or TeXiV. The last one is not so telling, but more distinguishable and looks good. 

I hope to come up with more original ideas, but those are already fine for me.

**Comment by lervag** [comment]
I like the sound of `vitex`. Thanks!

Do you have any examples of `vimtex` already being used by someone/-thing else?

**Comment by Konfekt** [comment]
Nope, I don't know any. It's just a general suspicion that vimtex will not be easily googleable.

**Comment by ldong** [comment]
Since I suspect the purpose of the plugin is to be **light(lite)**.

I have a name suggestion, lite tex.

litex -> LiteX, liTex

**Comment by nasenatmer** [comment]
Heya, I was thinking about the unfortunate name of `vim-latex` recently, too and think it's a good move to change the name to something unique.

I agree that vimtex is quite short and might not be perfect, but it's also quite concise and so far there don't seem to be bigger conflicts (although there's a textile company from India), so this is definitely my favourite so far.

Vitex also sounds nice. Incorporating @ldong's ideas, I could imagine  `vim-litex` although that would remove `latex` from the name which is good to have…

**Comment by lervag** [comment]
I also like @ldong's idea. My current favorites are `litex` and `vitex`. If it is `litex`, then I think the official name should be `vim-litex`, although all options, commands and similar will be named something like `LitexCommand`, `g:litex_option`, `<plug>(litex_mapping)`.

**Comment by lervag** [comment]
Oh, and btw: `vitex` and `vimtex` will also remove `latex` from the name. In some sense, I don't really think that is too bad. There is no reason the plugin should not work for other `tex` flavours in general (even though it might not do so right now).

**Comment by lervag** [comment]
I guess I just have to make a choice. So here it goes: I'll change the name to `vim-litex`. Thanks to @ldong for the suggestion!

So, the idea of the name is to combine `light` and `tex` into `lite tex` and then `litex`. I prepend `vim-` as the official name, but I intend to use simple `litex` for internal naming.

**Comment by lervag** [comment]
Hah! After I made all necessary changes for `litex`/`vim-litex`, I got a bad feeling. Somehow I just didn't feel quite happy with the name. So in the end I ended up using `vimtex`, which for some reason feels better to me. Sorry for the inconvenience (if any).

Please let me know if there are any problems after performing the name change!

**Comment by nasenatmer** [comment]
Haha nice story! Going to re-install immediately :)

**Comment by lahwaacz** [comment]
I just realized that the command I use for reverse search contained the keyword __vimtex__ all along ;)
```
gvim --servername VIMTEX --remote-silent +%2 "%1"
```

**Comment by lervag** [comment]
Hehe, nice! :)
