### ISSUE TITLE
Folds incorrectly highlight the following text

### ISSUE THREAD

**Issue by Coleej** [lervag/vimtex#1290]
I'm having a difficult time reproducing the bug. When editing text or open/closing folded section or subsections, text further down the document is highlighted as math mode. This highlighting encompasses all text and continues to end of the document.

Opening/closing folds or editing above the incorrectly highlighted text will fix the highlighting. Usually multiple fold traversals or edits are required.
 
Once I can reproduce the bug, I'll setup a minimal tex file and update the post.

**Comment by lervag** [comment]
I'm aware of this problem myself. It has to do with syntax syncing, but I've also not been able to create a reproducible example. If you should be able to do that, then that would be very helpful in finding how to fix the problem.

In the meantime, I've found that opening and closing all folds often helps, e.g. with `zRzMzv`.
