### ISSUE TITLE
Is there a way to make text objects with i and a not timeout, so to make di$ easier

### ISSUE THREAD

**Issue by soerenwolfers** [lervag/vimtex#1294]
I find it very hard to trigger, for example, the command `di$` to delete the contents of inline math. 

The reason for this, I realized, is that `i` times out, so if I take too long to press Shift+4 to get the dollar sign, I can only complete the `i` in `di` to bulitin objects (like `iw`, for example). 

I don't see any functional argument for why this timeout would be desired behavior. I understand that vim may make it difficult to fix this, however. Indeed, it seems to me that vim treats `i` as a builtin-command in itself, instead of treating `iw` `ip` `i(` etc each as their own builtin-commands. If that is the case, I understand if vimtex cannot (with reasonable effort) fix this issue.

**Comment by lervag** [comment]
Vim has a specified timeout controlled with the `:help timeout` and `:help timeoutlen` options. If you think the timeout is too short, then you can increase the timeoutlen.

**Comment by soerenwolfers** [comment]
I know about these options. The point is: there is no reason for the timeout in this case. There is no logical (there may well be a technical hurdle) reason why the text object `iw` should behave differently than `i$`. I can wait a second between `i` and `w`, I should also be able to wait a second between `i` and `$`. 

My time out is rather short (300ms) and I like it like that because I have quite some conflicting maps that depend on a timeout.

**Comment by lervag** [comment]
I don't quite understand. This is not something that is controlled by vimtex. It is pure Vim, and the timeout settings are the ones relevant here. Or am I misunderstanding your question?

**Comment by lervag** [comment]
That is, there should not be anything different between `iw` and `i$`, they should have the same timeout.

**Comment by soerenwolfers** [comment]
Sorry, I should have started with the default issue layout in the first place:

```
\documentclass{article}
\begin{document}
Test
\end{document}
```

``
set nocompatible
let &rtp = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
```

0. `vim -u vimrc mwe.tex`
1. Put cursor on T in `Test`.
2. Press `di`
3. Wait 2 seconds
4a. Press `P`: Nothing happens
4b. Press `w`: `Test` is deleted

I would expect that steps 4a and 4b have the same effect (up to whitespace) in this example. However, `P` has no effect at all. It does have the desired effect if I reduce the waiting time in step 3 to half a second. 

As verified by `set timeoutlen?`, the timeout time is 1000 which is shorted than the waited 2 seconds. However, as in step 4b, this shouldn't matter. Timeout's only make sense if `i` were a text object in itself, without any following letter. That's not the case.

**Comment by lervag** [comment]
Well, first, it is clear that this is controlled by `timeoutlen` (easily verified). I am not sure why this option is relevant for the text objects defined by vimtex and not for the ones defined by Vim itself. I've also tested the text objects defined by [targets.vim](https://github.com/wellle/targets.vim), which seems to work as you expect (not really sure what I expect, yet). Not sure what the difference is.

@kiryph @Konfekt @wellle Do any of you guys understand this?
