### ISSUE TITLE
[Info] enabling backward search for neovim

### ISSUE THREAD

**Issue by GohioAC** [lervag/vimtex#1296]
The current documentation in ` :h vimtex-faq-neovim ` can be misleading. It should be made clear that in
 [neovim-remote](https://github.com/mhinz/neovim-remote) needs to be installed for backward-sync to work in neovim (until ` --remote ` functionality is added back by neovim-PR #8326).

It would be nice if ` :h vimtex-synctex ` adds a line about setting ` g:vimtex_compiler_progname = 'nvr' `.

Currently, nvim servername can be set through ` --listen ` option similar to the vim ` --servername ` option. Setting up `alias nvim=nvim --listen VIM` is suggested.

Note, that the default servername for ` nvr ` is ` '/tmp/nvimsocket' ` so for enabling synctex in ` okular `  the following options are recommended:

` nvr --servername VIM--remote-silent +%l "%f" `
or ` nvr --servername VIM --remote-expr "vimtex#view#reverse_goto(%l, '%f')" `
#s should not be escaped.

(possibly pdf viewers other than ` zathura ` need to explicitly declare the servername as well)

Environment
===========
- Ubuntu 18.04.1 LTS
- nvim v0.3.1
- okular 1.3.3
- nvr 2.1.3
- guake 3.4.1

**Comment by lervag** [comment]
Thanks!

Note that `nvim --listen VIM` will also create the file socket VIM in the current directory, so I suggest instead using `nvim --listen /tmp/nvimserver` or similar.

**Comment by bitsandscraps** [comment]
@lervag It seems that the `--listen` option was added in v0.3.0 ([link](https://github.com/neovim/neovim/releases?after=v0.3.4)). I think it's worth mentioning it in the docs.

**Comment by lervag** [comment]
@bitsandscraps I'm not sure if it is worth mentioning. Neovim has already reached v0.4.0, and I think those who choose to use neovim should make sure to use a relatively up to date version. Else I would claim one should rather use Vim itself. So, why would anyone not be on version 0.3.0 by now?

**Comment by bitsandscraps** [comment]
@lervag The neovim version on the Ubuntu repository tuns out to be 0.2.2 ([link](https://packages.ubuntu.com/bionic/neovim)). I was unaware of it until I tried to use the `--listen` command, which did not work. I thought there would be other users like me, but I guess you do have a solid point.

**Comment by lervag** [comment]
Yes, you are right. Also see [here](https://packages.ubuntu.com/search?keywords=neovim). Still, I think my point is relevant, that it makes little sense to stay on these old neovim versions. Perhaps from version 0.3.1 it starts to make more sense, but before 0.3 I would rather suggest you install a newer version as expained [here](https://github.com/neovim/neovim/wiki/Installing-Neovim#ubuntu).
