### ISSUE TITLE
Can't configure folding for environments like enumerate

### ISSUE THREAD

**Issue by SuperPrower** [lervag/vimtex#1298]
I can't configure vimtex to enable folding for environments like enumerate and itemize.

Like suggested in help, I have installed a FastFold plugin. Also, as suggested in many other issues here, I have disabled `tex_fold_enabled` and only enabled `vimtex_fold_enabled`. I also have added this to my `init.vim` (I use neovim):

```vim
let g:vimtex_fold_types = {
	\ 'envs' : {
	\	'whitelist': ['enumerate','itemize','math'],
	\ },
\ }
```

Here is my .tex file:
```tex
\documentclass[11pt]{report}

\usepackage[utf8]{inputenc}
\usepackage{graphicx}

\begin{document}

\begin{enumerate}
	\item Element 1
	\begin{itemize}
		\item Another Element
		\item And one more
	\end{itemize}
\end{enumerate}

\begin{figure}
	\centering
	\includegraphics[width=0.8\linewidth]{test.png}
	\caption{Name}
	\label{Figure}
\end{figure}

\end{document}
```

`figure` environment folds just fine, but I can't apply folding to any other environment.

**Comment by lervag** [comment]
I can't reproduce. Can you post a full minimal example?

**Comment by SuperPrower** [comment]
```vim
set nocompatible

set foldenable
set foldmethod=marker

call plug#begin("~/.local/share/nvim/plugged")
	Plug 'Konfekt/FastFold'
	Plug 'lervag/vimtex', { 'for': 'tex' }
	Plug 'matze/vim-tex-fold', { 'for': 'tex' }
call plug#end()

let g:fastfold_savehook = 1
let g:fastfold_fold_command_suffixes =  ['x','X','a','A','o','O','c','C']
let g:fastfold_fold_movement_commands = [']z', '[z', 'zj', 'zk']

let g:tex_fold_enabled = 0

let g:tex_flavor = "latex"
let g:tex_conceal = ''

let g:vimtex_fold_enabled = 1
let g:vimtex_fold_types = {
	\ 'envs' : {
	\	'whitelist': ['enumerate','itemize','math'],
	\ },
\ }
```

When I open `.tex` file with (almost) same contents as above, I have `figure` environment folded, but `math`, `enumerate` and `itemize` environments are open. I can't fold them with zc, zx, or za. Folding sections also work just fine.

Here is updated `.tex` example just in case:
```tex
\documentclass[11pt]{report}

\usepackage[utf8]{inputenc}
\usepackage{graphicx}

\begin{document}

\begin{enumerate}
    \item Element 1
\end{enumerate}

\begin{itemize}
    \item Another Element
    \item And one more
\end{itemize}

\begin{math}
    1 + 2 = 3
\end{math}

\begin{figure}
    \centering
    \includegraphics[width=0.8\linewidth]{test.png}
    \caption{Name}
    \label{Figure}
\end{figure}

% \bibliography{references}
% \bibliographystyle{ieeetr}
\end{document}
```

My neovim version, if it'll help:
```
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.1/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"
```

**Comment by lervag** [comment]
I'll look more closely at this when I get the time. I've question, though: why do you load vim-tex-fold? Can you reproduce without it?

**Comment by SuperPrower** [comment]
Darn. I thought I removed it a long time ago. Yes, problems was with it. I was following some guide on neovim and vimtex at first and it listed this plugin, but I never really understood what it does, so I thought I removed it. Yes, all the problems was because of it.

But now I can't close `figure` environment, though, probably because it is not listed in my whitelist. Is there a way to add ALL environments to whitelist? Help says `whitelist` is a list of strings, so I suspect it won't accept wildcard, but if there is something like that, please tell me.

**Comment by lervag** [comment]
Great, good to hear it works. If the whitelist is not empty, then the idea is that only whitelisted environments are folded. So to fold every environment you should not change that option. I propose you remove the option from your vimrc file.

**Comment by SuperPrower** [comment]
Got it, thank you!

**Comment by lervag** [comment]
No problem :)
