### ISSUE TITLE
Duplicte tag in doc

### ISSUE THREAD

**Issue by petobens** [lervag/vimtex#130]
Hi @lervag  after the commit that changes the name to `vimtex` when I try to update the plugin with neobundle I get the following message:

    Vim(helptags):E154: Duplicate tag "vimtex" in file C:/OD/Users/Pedro/vimfiles/bundle/.neobundle/doc/vimtex.txt                                     

Maybe it's something wrong with my neobundle settings. If that's the case please close this issue. Thanks!

**Comment by lervag** [comment]
Could you try to remove the tags file? I don't remember how this works with neobundle (that is, if neobundle keeps the tags files for documentations somewhere else than inside the plugins `doc` directory). One simple way is to remove the plugin completely: First comment out the `Neobundle 'lervag/vimtex'` line, then start vim again and do `:NeoBundleClean` (or something similar) to remove the plugin. Then reinstall.

**Comment by petobens** [comment]
Mmm I tried removing the plugin and reinstalling it but I still get the message. I''ll try to investigate further and report back.

**Comment by lervag** [comment]
Sorry, the error message was so clear I should have understood the problem right away... I think it should work now.

**Comment by petobens** [comment]
No need to be sorry. Thank you!!

**Comment by lervag** [comment]
:)
