### ISSUE TITLE
Outdated import from amsmath.vba.gz by DrChip (do not overwrite texMathZones)

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1301]
Currently, the file `after/syntax/tex.vim` contains an outdated import from 
http://www.drchip.org/astronaut/vim/vbafiles/amsmath.vba.gz

The new version is from 

```
"   Author: Charles E. Campbell
"   Date:   Jun 29, 2018
"   Version: 1c	ASTRO-ONLY
```

The corresponding part in vimtex has the date 2017-10-12:

https://github.com/lervag/vimtex/blob/6934291dcbde6fbe9e590241940112eed5a19dfb/after/syntax/tex.vim#L358-L390

In particular, some `texMathZones` defined in `$VIMRUNTIME/syntax/tex.vim` which can be seen here:

https://github.com/vim/vim/blob/f62fc316a212160d1c58be88f30efd11eb595493/runtime/syntax/tex.vim#L438-L458

are overwritten by vimtex. 

The new version has changed the letters to
```
call TexNewMathZone("E","align",1)
call TexNewMathZone("F","alignat",1)
call TexNewMathZone("G","equation",1)
call TexNewMathZone("H","flalign",1)
call TexNewMathZone("I","gather",1)
call TexNewMathZone("J","multline",1)
call TexNewMathZone("K","xalignat",1)
call TexNewMathZone("L","xxalignat",0)
```

Could we use the same letters as well?

**Comment by kiryph** [comment]
I figured out that the zones are actually not overwritten but the region definition extended by a secodn start/end definition:

```
:syntax list texMathZoneX
--- Syntax items ---
texMathZoneX   xxx matchgroup=Delimiter start=/\$/ skip=/\\\\\|\\\$/ end=/%stopzone\>/ end=/\$/  concealends contains=@texMathZoneGroup 
                   start=/\\begin\s*{\s*equation\s*}/ end=/\\end\s*{\s*equation\s*}/  keepend contains=@texMathZoneGroup 
                   links to texMath
```

I am not sure anymore if a change to vimtex is necessary.
You can close the corresponding PR #1303 if you like. 
On the other side it might still be reasonable to update accordingly to amsmath.vba.gz.

**Comment by lervag** [comment]
Thanks, and yes, I agree it should be in sync with amsmath.vba.gz. I'll accept your PR.
