### ISSUE TITLE
vimtex#debug#stacktrace errors

### ISSUE THREAD

**Issue by michaelschaub** [lervag/vimtex#1304]
1. Minimal `vimrc` file:

    ```vim
    set nocompatible
    let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
    let &rtp .= ',~/.vim/bundle/vimtex/after'

    filetype plugin indent on
    syntax enable
    ```

2. Minimal `mwe.tex` file:

    ```tex
    \documentclass{minimal}
    \begin{document}

    Hello World!

    \end{document}
    ```

3. Using the above files with `vim --servername VIM -u vimrc mwe.tex` and running `\ll` should normally compile without errors. The pdf is indeed compiled correctly, but the 'debug stacktrace' functionality (in debug.vim) of vimtex produces the following error as the variable `l:text` is not set and thus cannot be used in the `add()` function.

```
Error detected while processing function <SNR>33_callback_continuous_output[6]..vimtex#compiler#callback[14]..vimtex#log#info[1]..158[13]..vimtex#debug#stacktrace:
line   72:
E121: Undefined variable: l:text
E116: Invalid arguments for function add
```

It seems this might be due to changes introduced in commit fab5435a3499bda710546a0988a434adfb990080.

Vim version used:
VIM - Vi IMproved 8.1 (2018 May 18)
macOS version. Included patches: 1-577

Latexmk version: 4.61, 25 October 2018.

**Comment by lervag** [comment]
Strange. I can't reproduce this. I'm on Arch Linux with Vim 8.1.570.

**Comment by lervag** [comment]
However, I found a minor bug that is probably related. Still, if I could reproduce the problem I could perhaps also improve this further.

What's the output when you follow your minimal example with the updated code, then finally do `\lq` to open the vimtex (debug) log?

**Comment by michaelschaub** [comment]
After this fix things work again as expected, i.e., no error message.

Here is the debug log output via `lq`

```
17:54:55: info
  #1 _
  In vimtex#log#info
  #2 _
  In 38
  #3 _
  In vimtex#compiler#compile
  Compiler started in continuous mode

17:54:55: info
  #1 _
  In vimtex#log#info
  #2 _
  In vimtex#compiler#callback
  #3 _
  In s:callback_continuous_output
  Compilation completed
```

**Comment by lervag** [comment]
Ok, thanks. For me, the output text also contains the text of the corresponding lines. For some reason, on your end, the feature does not pick up the line numbers. Can you edit the `debug.vim` file and add a line above line number 33 like this:

```
unsilent echom string(l:stack)
```

Then run the example again and copy the echoed text here? (You might need to do `:messages` to get the text, since other parts may do `redraw` after this line is executed.)

**Comment by michaelschaub** [comment]
Sure. Just to confirm the debug.vim now looks something like
```
[ ... ]
  "
  " Build the quickfix entries
  "
  let l:qflist = []
  let l:files = {}
  unsilent echom string(l:stack)
  for l:func in l:stack
[ ... ]
```

The resulting output I get ('resurrected' via `:messages`) is the following:

```
"minimal.tex" 6L, 71C
['158[13]', 'vimtex#log#info[1]', '38[29]', 'function vimtex#compiler#compile[5]']
['158[13]', 'vimtex#log#info[1]', '38[29]', 'function vimtex#compiler#compile[5]']
['158[13]', 'vimtex#log#info[1]', '38[29]', 'function vimtex#compiler#compile[5]']
['158[13]', 'vimtex#log#info[1]', '38[29]', 'function vimtex#compiler#compile[5]']
['158[13]', 'vimtex#log#info[1]', 'vimtex#compiler#callback[14]', 'function <SNR>33_callback_continuo
us_output[6]']
['158[13]', 'vimtex#log#info[1]', 'vimtex#compiler#callback[14]', 'function <SNR>33_callback_continuo
us_output[6]']
['158[13]', 'vimtex#log#info[1]', 'vimtex#compiler#callback[14]', 'function <SNR>33_callback_continuo
us_output[6]']
['158[13]', 'vimtex#log#info[1]', 'vimtex#compiler#callback[14]', 'function <SNR>33_callback_continuo
us_output[6]']
```

**Comment by lervag** [comment]
Ok, that looks good. Now remove the previous line and instead add this:

```diff
            \ vimtex#util#command('verbose function ' . l:func_name)[1],
            \ '\f\+\.vim')
    endif

    let l:filename = fnamemodify(l:filename, ':p')
+   unsilent echom l:name
+   unsilent echom l:filename filereadable(l:filename)
+   unsilent echom '--'
    if filereadable(l:filename)
      if !has_key(l:files, l:filename)
        let l:files[l:filename] = reverse(readfile(l:filename))
      endif
```

The lines are to be added below line 56. Can you again copy the output here?

For me, the output looks similar to this:

```
158
/home/lervag/.vim/bundle/vimtex/autoload/vimtex/log.vim 1
--
vimtex#log#info
/home/lervag/.vim/bundle/vimtex/autoload/vimtex/log.vim 1
--
vimtex#qf#open
/home/lervag/.vim/bundle/vimtex/autoload/vimtex/qf.vim 1
--
vimtex#qf#toggle
/home/lervag/.vim/bundle/vimtex/autoload/vimtex/qf.vim 1
```

**Comment by michaelschaub** [comment]
Done. I get the following:

```
"minimal.tex" 6L, 71C
158
/VIM/bundle/vimtex/autoload/vimtex/log.vim 0
--
vimtex#log#info
/VIM/bundle/vimtex/autoload/vimtex/log.vim 0
--
38
/VIM/bundle/vimtex/autoload/vimtex/compiler/latexmk.vim 0
--
vimtex#compiler#compile
/VIM/bundle/vimtex/autoload/vimtex/compiler.vim 0
--
158
/VIM/bundle/vimtex/autoload/vimtex/log.vim 0
--
vimtex#log#info
/VIM/bundle/vimtex/autoload/vimtex/log.vim 0
--
vimtex#compiler#callback
/VIM/bundle/vimtex/autoload/vimtex/compiler.vim 0
--
s:callback_continuous_output
/Users/mschaub/Dropbox/ 0
--
```

Just guessing, what could be a problem here, but note that the files "/VIM/bundle/vimtex/autoload/vimtex/log.vim" etc do not exist in fact, but the path is actually a symlink (i.e., my .vimrc and .vim folder are symlinks)..

**Comment by lervag** [comment]
Hm. Strange. Can you explain how you've symlinked this?

Also, can you show the output after changing to

```diff
            \ vimtex#util#command('verbose function ' . l:func_name)[1],
            \ '\f\+\.vim')
    endif

+   unsilent echom 1 l:filename
+   unsilent echom 2 resolve(l:filename)
    let l:filename = fnamemodify(l:filename, ':p')
+   unsilent echom 3 l:filename
+   unsilent echom 4 resolve(l:filename)
    if filereadable(l:filename)
      if !has_key(l:files, l:filename)
        let l:files[l:filename] = reverse(readfile(l:filename))
      endif
```

Here `resolve()` is a function that resolves symlinks. I think perhaps I could use it to fix this problem.

**Comment by michaelschaub** [comment]
The output is:
```
1 /VIM/bundle/vimtex/autoload/vimtex/log.vim
2 /VIM/bundle/vimtex/autoload/vimtex/log.vim
3 /VIM/bundle/vimtex/autoload/vimtex/log.vim
4 /VIM/bundle/vimtex/autoload/vimtex/log.vim
1 /VIM/bundle/vimtex/autoload/vimtex/log.vim
2 /VIM/bundle/vimtex/autoload/vimtex/log.vim
3 /VIM/bundle/vimtex/autoload/vimtex/log.vim
4 /VIM/bundle/vimtex/autoload/vimtex/log.vim
1 /VIM/bundle/vimtex/autoload/vimtex/compiler/latexmk.vim
2 /VIM/bundle/vimtex/autoload/vimtex/compiler/latexmk.vim
3 /VIM/bundle/vimtex/autoload/vimtex/compiler/latexmk.vim
4 /VIM/bundle/vimtex/autoload/vimtex/compiler/latexmk.vim
1 /VIM/bundle/vimtex/autoload/vimtex/compiler.vim
2 /VIM/bundle/vimtex/autoload/vimtex/compiler.vim
3 /VIM/bundle/vimtex/autoload/vimtex/compiler.vim
4 /VIM/bundle/vimtex/autoload/vimtex/compiler.vim
1 /VIM/bundle/vimtex/autoload/vimtex/log.vim
2 /VIM/bundle/vimtex/autoload/vimtex/log.vim
3 /VIM/bundle/vimtex/autoload/vimtex/log.vim
4 /VIM/bundle/vimtex/autoload/vimtex/log.vim
1 /VIM/bundle/vimtex/autoload/vimtex/log.vim
2 /VIM/bundle/vimtex/autoload/vimtex/log.vim
3 /VIM/bundle/vimtex/autoload/vimtex/log.vim
4 /VIM/bundle/vimtex/autoload/vimtex/log.vim
1 /VIM/bundle/vimtex/autoload/vimtex/compiler.vim
2 /VIM/bundle/vimtex/autoload/vimtex/compiler.vim
3 /VIM/bundle/vimtex/autoload/vimtex/compiler.vim
4 /VIM/bundle/vimtex/autoload/vimtex/compiler.vim
1 ~/Dropbox
2 ~/Dropbox
3 /Users/mschaub/Dropbox/
4 /Users/mschaub/Dropbox (Personal)/
```

The symlinks are to Dropbox as follows (having a personal and a work dropbox account on the same computer unfortunately automatically creates a folder with a space in the filename "Dropbox (Personal)", which causes problems in some setups (this may also be the culprit). I have fixed this in most instances by defining the third symlink as a workaround..

```
.vimrc -> Dropbox/VIM/.vimrc
.vim -> Dropbox/VIM
Dropbox -> 'Dropbox (Personal)/'
```

**Comment by lervag** [comment]
Thanks, I think this should be fixed now, at least if you use english locale. The problem is with parsing file names with spaces from a localized string from the output of `:verbose function ...`. For english, which I assume most people use, I've fixed the problem. For other languages, I don't know a good fix except hardcoding every special case. I won't do that. :)

**Comment by lervag** [comment]
Thanks for providing the info for debugging this. I know this wasn't really important to you, but it was nice for me to fix this bug. The feature is useful in debugging, and so it is nice to make it work more reliably.
