### ISSUE TITLE
Autofocus on Zathura after \lv

### ISSUE THREAD

**Issue by Millani** [lervag/vimtex#1305]
First things first, thanks for this rather amazing plug in!

So, what I came to ask is just whether would it be possible for me to have `vimtex` activate (i.e. bring to front) the Zathura PDF viewing window when `\lv` is pressed. I think this is analogous to what was implemented a few months ago for Skim due to https://github.com/lervag/vimtex/pull/1178.

I like to work with Vim maximized to fullscreen, so when I hit `\lv` the PDF in Zathura gets updated but every single time I have also to alternate windows to navigate to Zathura. If I only have Vim and Zathura opened, that is not an issue; but if many applications are open it can become problematic.

If there's any way I can accomplish this with Zathura by either customizing config settings or tweaking the source code, please let me know!

**Comment by lervag** [comment]
> First things first, thanks for this rather amazing plug in!

Thanks! :)

> If there's any way I can accomplish this with Zathura by either customizing config settings or tweaking the source code, please let me know!

Yes, this is possible by utilizing the (undocumented) option `g:vimtex_view_zathura_hook_view`. An example configuration:

```vim
function! VimtexHookZathura() abort
  let xwin_id = get(b:vimtex.viewer, 'xwin_id')
  if xwin_id > 0
    silent call system('xdotool windowactivate ' . xwin_id . ' --sync')
    silent call system('xdotool windowraise ' . xwin_id)
  endif
endfunction

let g:vimtex_view_method = 'zathura'
let g:vimtex_view_zathura_hook_view = 'VimtexHookZathura'
```

**Comment by lervag** [comment]
I notice you added a comment to issue 180 that you later deleted. Thanks for that, I much prefer that you create a new issue instead of "bumping" and old one. The latter often requires me to read possibly long threads, and I currently don't have that much time to vimtex. (Hope to get more time soon.)
