### ISSUE TITLE
Label completion does not work when page number disabled

### ISSUE THREAD

**Issue by codetrick** [lervag/vimtex#1306]
When page number output is disabled through latex command `\pagenumbering{gobble}`, the label omnicompletion does not work properly. 

Minimal example:
```latex
\documentclass{article}

\pagenumbering{gobble}

\begin{document}

    Hello World!
    \begin{figure}
        \caption{This is a test}
        \label{fig:test}
    \end{figure}

\end{document}
```

Compiling this document generates the following aux file:
```
\relax 
\newlabel{fig:test}{{}{}}
```
upon which `function! s:completer_ref.parse_labels(file, prefix) dict` throws an error at line https://github.com/lervag/vimtex/blob/237639af93b036af9c8817fc650bcd1f051b0ec1/autoload/vimtex/complete.vim#L386

Suggested fix:
```vim
      if type(l:context[1]) == type([]) && len(l:context[1]) > 0
        let l:page = l:context[1][0]
      else
        let l:page = 0
      endif
```

**Comment by lervag** [comment]
Thanks! Should be fixed now.
