### ISSUE TITLE
Unexpected behavior of `dsd`

### ISSUE THREAD

**Issue by zhuosongz** [lervag/vimtex#1307]
`dsd` and `csd` provide a very convenient way to change the surroundings. However, I found an unexpected behavior of `dsd`. 

For example: If I want to remove the delimiter (including `\bigl` and `\bigr`): 
```
\bigl( cursor \bigr) --> cursor
```
but a `dsd` gives: 
```
\bigl cursor \bigr
```
 Could you please help me for this? Thank you very much!

**Comment by lervag** [comment]
Strange. This works as expected for me. Can you please provide more information, such as a minimal example? I've updated the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md), which should provide a guide to giving the necessary information.

**Comment by zhuosongz** [comment]
@lervag 
Thank you for your reply. I just tried with my personal Mac, and it works well. Maybe there was something wrong with the computer at my university. I will try again. Sorry for the issue and thank you for your time!

**Comment by lervag** [comment]
No problem! Common problems may be that there are conflicting plugins and similar. You should check th eoutput of `:VimtexInfo`, as well as `:map dsd` (which should show that `dsd` is mapped to `<plug>(vimtex-delim-delete)`).
