### ISSUE TITLE
Text objects as a 'plugin' for targets.vim if installed

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1308]
This issue started in #1299. Since the issue 1299 is actual about new motions and the discussion has become a bit lengthy I repeat a few things:

https://github.com/wellle/targets.vim/blob/master/plugins.md says

> It's possible to extend targets.vim by adding new sources. Text objects implemented as targets.vim plugin will automatically gain all the functionality of the built in ones. Most notably you can
> - use `n` and `l` to select next and last one,
> - provide counts to pick a specific one,
> - use seeking (`vix` pick current, next or last),
> - growing (`vixix` is the same as `v2ix` etc.) and
> - skipping (`vinxinx` is the same as v2inx).

Furthermore, it is possible to define `I` and `A` variants to exclude inner surrounding whitespace or include trailing/leading whitespace.

I have created a small snippet reusing vimtex definition for the text object `ie` to get `ane/ale/ine/ile` and `Ie` and `Ae`, ...:

`~/.vim/ftplugin/tex.vim`:
```viml
autocmd User targets#sources call targets#sources#register('tex_env', function('vimtextargets#envnew'))
autocmd User targets#mappings#plugin call targets#mappings#extend({'e': {'tex_env': [{'c': 1}]}})
```
`~/.vim/autoload/vimtextargets.vim`:
```viml
function! vimtextargets#envnew(args)
    return {
                \ 'args': {
                \     'count': get(a:args, 'c', 1),
                \ },
                \ 'genFuncs': {
                \     'c': function('vimtextargets#envcurrent'),
                \     'n': function('vimtextargets#envnext'),
                \     'l': function('vimtextargets#envlast'),
                \ },
                \ 'modFuncs': {
                \     'i': function('targets#modify#keep'),
                \     'a': function('vimtextargets#modifyouterenv'),
                \     'I': function('targets#modify#shrink'),
                \     'A': [function('vimtextargets#modifyouterenv'), function('targets#modify#expand')],
                \ }}
endfunction

function! vimtextargets#envcurrent(args, opts, state)
    execute "normal \<Plug>(vimtex-ie)"
endfunction

function! vimtextargets#envnext(args, opts, state)
    execute "normal \<Plug>(vimtex-]m)v\<Plug>(vimtex-ie)"
endfunction

function! vimtextargets#envlast(args, opts, state)
    execute "normal \<Plug>(vimtex-[M)v\<Plug>(vimtex-ie)"
endfunction

function! vimtextargets#modifyouterenv(target, args)
    call a:target.cursorS()
    call a:target.searchposS('\\begin{.*}', 'bW')
    call a:target.cursorE()
    call a:target.searchposE('\\end{.*}', 'We')
endfunction
```

Following works now

- `vane` if you are before the env you want to select
- `vine`  if you are before the env you want to select
- `vIe` (capital i) to not select inner surrounding whitespace. The following picture tries to illustrate this:

![screenshot 2019-01-15 at 11 45 10](https://user-images.githubusercontent.com/371756/51175599-0eeee900-18bb-11e9-8d85-b5a1ae9d2ed9.png)

This shows in principle how targets.vim is used but a proper realization needs more than this to work flawlessly. However, it should be possible to reuse functionality of vimtex's implementation for the text objects.

The plugin mechanism of targets.vim is documented under

- https://github.com/wellle/targets.vim/blob/master/plugins.md
- https://github.com/wellle/line-targets.vim/blob/master/README.md
- https://github.com/wellle/line-targets.vim/blob/master/plugin/linetargets.vim (in source docs)
- https://github.com/wellle/line-targets.vim/blob/master/autoload/linetargets.vim (in source docs)

The builtin text objects of targets.vim are also implemented as plugins and their source code is helpful to better understand the mechanism:
- [autoload/targets/sources/tag.vim](https://github.com/wellle/targets.vim/blob/master/autoload/targets/sources/tag.vim)
- [autload/targets/sources/pair.vim](https://github.com/wellle/targets.vim/blob/master/autoload/targets/sources/pair.vim)

Modifier functions which can also be reused:
- [autoload/targets/modify.vim](https://github.com/wellle/targets.vim/blob/d6466f6f281f920e178637882a2e6e4f40c3acc2/autoload/targets/modify.vim) 
  I used in the the snippet above to
remove whitespace `targets#modify#shrink` for `Ie`, to add whitespace `targets#modify#expand` for `Ae`.

**Comment by lervag** [comment]
Thanks! It is very helpful that you have separated the topics of #1299 and summarized (in much detail) the threads here and in #1315. I'll definately look into this. I'm looking into the "advanced" features of targets.vim now, e.g. the `n` and `l` modifiers. If I end up using them it might make for a stronger motivation as well.

**Comment by kiryph** [comment]
> I'm looking into the "advanced" features of targets.vim now, e.g. the `n` and `l` modifiers. If I end up using them, it might make for a stronger motivation as well.

I was aware of `targets.vim` for quite a while before I actually started to be interested in using myself.

Vim and its plugins can sometimes be very granular, maybe sometimes too granular which can actually mean an additional burden in learning new aspects. In particular, if it is not well-documented:

I did not know following for a long period of vim usage. The builtin text object `aw` includes trailing white space **except at the end of line where it includes leading whitespace**. 
In this case I blame the reference manual of vim:

`:h aw` (reference manual)

> ```
> aw			"a word", select [count] words (see |word|).
> 			Leading or trailing white space is included, but not
> 			counted.
> ```

`Leading or trailing white space` is not self-explanatory. The user manual actually explains it in the last sentence of following paragraph:

`:h 4.8`

> ```
> The "d" of "daw" is the delete operator.  "aw" is a text object.  Hint: "aw"
> stands for "A Word".  Thus "daw" is "Delete A Word".  To be precise, the white
> space after the word is also deleted (the white space before the word at the
> end of the line).
> ```

Of course, this does not resolve the problem of deleting the last word including leading whitespace in a sentence ending with a period at the end of the line.

As another example of granularities: vim-surround provides

- `ys` variants:
  - `yss`: operates on the current line but ignores leading whitespace in contrast to `VS` (line-wise visual mode)
  - `yS` and `ySS`: indent the surrounded text and place it on a line of its own.
  - `ySs`: unclear
- if an opening mark (, {, [, and < is used as a target, contained whitespace is also trimmed.
- similar behavior can be found with (, {, and [ (but not <) as replacements, which append an additional space to the inside. 
- replacement `<C-}>` instead of `}` (which is really `<C-]>`) adds braces on lines separate from the content.
- if the replacement `<C-T>` instead of `t` is used, the tags will appear on lines by themselves.

Probably not everyone wants to learn and needs all these details. It depends on what you are doing and where shortcuts will pay off.

My point is:
However, I think the situation for targets.vim is less demanding. IMHO the learning effort is less than for all features of vim-surround: the applicability to all text objects of the modfieres `n`/`l` and `I`/`A` makes them predictable & consistent. Therfore the amount of things to learn is quite small.

**Comment by lervag** [comment]
Ok, I'm "back". Please confirm if I understand things right, I don't have so much, and there's a lot of text concerning this issue now: I should pdated `text_obj.vim` as follows:

- [ ] Implement `targets.vim` specific wrapper functions for all of vimtex's text objects.
- [ ] Use the `targets.vim` autocommands and `targets#sources#register` and `targets#mappings#extend` to define the actual mappings, if the user has `targets.vim` installed.

**Comment by kiryph** [comment]
I have deleted my last comment to reduce the length and number of comments of this issue. I hope this helps. (*The comment was trying to motivate this issue and explain that the learning curve vanishes after having grasped how targets.vim works for one set of text objects.*)

I agree that the two fundamental tasks to support targets.vim are those which you mentioned
1. write wrapper functions
2. detect if targets.vim is installed and then define autocommands which register the actual mappings

I think the first task is most likely the more difficult one. Task 2 should be easier, mostly writing boilerplate code.

I hope my first incomplete snippet helps you to see what wrapper functions are needed. Nevertheless, I list them again:

1. Following three basic functions are needed
    ```
    function('vimtextargets#envcurrent') " this is 'ie' and should already exist
    " For seeking we need additional ones:
    function('vimtextargets#envnext')" NEW
    function('vimtextargets#envlast')" NEW
    ```

2. targets.vim uses modifier functions to create more text objects by applying the modifier functions after the above have been applied (mainly adding, removing whitespace or the "delimiters")

    The first modifier function changes `ie` to `ae`:
    ```
    function('vimtextargets#modifyouterenv')
    " outer version by modifying the inner version by adding \begin{} and \end{}
    ```

    I tried to use following modifier functions of targets.vim:
    `function('targets#modify#expand')` for `Ae` and `function('targets#modify#shrink')` for `Ie` which should add surrounding whitespace or remove inner whitespace. However, it did not work for the environments.

    I think we need new versions:
    ```
    function('vimtextargets#modifyshrinkenv) " NEW ignore inner whitespace
    function('vimtextargets#modifyexpandenv) " NEW add outer whitespace
   ```

**Comment by wellle** [comment]
Hey, this is very exciting, thanks for considering/using targets.vim for this 👍 

If you find any rough edges in the extensibility mechanisms, please feel free to ping me or open an issue!

**Comment by lervag** [comment]
Thanks, @wellle! I've been very busy lately, so progress is slow. But I'll work on it when I get the time. And I'll make sure to ping you if I have any questions!

**Comment by wellle** [comment]
> 2\. detect if targets.vim is installed and then define autocommands which register the actual mappings

Hey, I'm just re-reading this issue again and noticed how you said here that you'd have to detect if targets.vim is installed. Just wanted to point out that this shouldn't be needed. You can just always add autocommands like this:
```vim
autocmd User targets#sources call targets#sources#register('tex_env', function('vimtextargets#envnew'))
autocmd User targets#mappings#plugin call targets#mappings#extend({'e': {'tex_env': [{'c': 1}]}})
```
If targets.vim is not installed, then those will just never be fired.
