### ISSUE TITLE
Toggling visibility of Quickfix List

### ISSUE THREAD

**Issue by lahwaacz** [lervag/vimtex#131]
On smaller displays it may not be a good idea to keep the Quickfix window all the time. It can be easily opened manually with `\le`, but there is no default way to close it as easily. Would it be suitable to make the underlying function toggling, so that `\le` can be used for both of these actions?

**Comment by lervag** [comment]
Yes, this is a good idea. I've updated so that the command `VimtexErrors` and the mapping `\le` now work as a toggle.

Note that the mappings are NOT valid inside the quickfix window! Thus you can not use `\le` to quit the quickfix window from inside the window itself.

**Comment by lahwaacz** [comment]
Great, thank you!
