### ISSUE TITLE
[feature request] Support `mleft` and `mright` in `tsd` by auto-detection of `mleftright` package

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1313]
The latex package [`mleftright`](https://ctan.org/pkg/mleftright) is an extremely useful one providing the `\mleft(` and `\mright)` variants of the standard `\left(` and `\right)` for stretchy brackets, but without the unwanted spacing introduced by it.

Is there a chance you could consider supporting `mleft` and `mright` through the `tsd` (toggle surrounding delimiter) operator, only if the `mleftright` package is detected. Since `vimtex` already scans the preamble at-least once, this should be a straight-forward extension.

in this case, the `tsd` is a simple boolean case. if `mleftright` is not loaded, use the standard `left(` and `right)` , if the package is loaded, `tsd` should toggle only `mleft(` and `mright)` since there is no instance of a user preferring the standard left over mleft, especially when consciously loading `mleftright`. That is to say, `mleft` is always desirable over just `left(` , and same for the `\right` equivalents.

**Comment by lervag** [comment]
It is possible to implement what you are asking, @krishnakumarg1984. However, I've not heard about this package until now, and I'm not sure that the best solution is to add support for the package directly to vimtex. Instead, I think @kiryph provides two suggestions that should solve your issue quite well.

**Comment by lervag** [comment]
Ok, sorry, I have heard of the package.

I'm curious, if vimtex were to automatically apply example 1 from the documentation for `g:vimtex_delim_toggle_list_mod` if the `mleftright` package is detected, would anyone find it annoying? Or would it feel natural? I think it is easy to add this, so I might consider to do it...

**Comment by kiryph** [comment]
As I said some people might want to mix them or prefer the switch (e.g. saves a few letters in lengthy equations) and therefore would want to stick to the current situation.

Therefore, I would argue that it should not be enforced on all user. At least provide an option to opt-out.

**Comment by lervag** [comment]
Great, then we'll leave things as they are.
