### ISSUE TITLE
Support counts for text objects iP and aP

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1315]
This issue started in #1299 and is intended to keep track on the remaining text objects without support for counts, ie. `iP` and `aP`:

- [x] `ie/ae` LaTeX environments (237639af93b036af9c8817fc650bcd1f051b0ec1)
- [x] `ic/ac` Commands (03840a26ce31b644cc8c5a47c3162180a31e3eb7)
- [x] `id/ad` Delimiters (added support probably in the same commit as for environments)
- [x] `i$/a$` Inline math structures (added support probably in the same commit as for environments)
- [ ] `iP/aP` Sections

### Examples

- **Environments**

  ```
  \begin{document}
    \begin{center}
        \begin{align}
          a = b |
        \end{align}
    \end{center}
  \end{document}
  ```
  Press `d2ae` on | to get
  ```
  \begin{document}
    
  \end{document}
  ```

- **Commands**
  
  ```
  a + \bar{\mathit{c + d|}} =
  ```
  Press `d2ac` on `|` to get
  ```
  a + | =
  ```

- **Delimiters**

  ```
  a + \left(b + \left[c + d | \right] + e\right) + f
  ```
  Press `d2ad` on | to get
  ```
  a + | + f
  ```

**Comment by lervag** [comment]
I think this is solved now. Let me know if I'm wrong. :)

**Comment by kiryph** [comment]
Thanks! I've tested it a little bit and it works so far :-).

**Comment by lervag** [comment]
Great, happy to hear it!
