### ISSUE TITLE
Forward search doesn't work if path to .tex file contains spaces

### ISSUE THREAD

**Issue by nadya-p** [lervag/vimtex#1316]
If you compile a file, path to which contains spaces (such as `C:\test dir\minimal.tex`), the forward search fails with "Viewer cannot read PDF file!" message. This used to work in a vimtex version a month or two ago. I'm using neovim on Windows.

Backslash path separator might be another root cause for that.

<details>
  <summary>minimal.tex</summary>

  ```tex
  \documentclass{article}
  \begin{document}
  Test
  \end{document}
  ```

</details>

<details>
  <summary>.vimrc</summary>

  ```vim
  execute pathogen#infect()

  " vimtex
  let g:tex_flavor = 'latex'
  let g:vimtex_view_general_viewer = 'SumatraPDF'
  let g:vimtex_view_general_options
      \ = '-reuse-instance -forward-search @tex @line @pdf'
  let g:vimtex_view_general_options_latexmk = '-reuse-instance'
  let g:vimtex_compiler_latexmk = {
      \ 'options' : [
      \   '-pdf',
      \   '-pdflatex="xelatex %O %S"',
      \   '-verbose',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \ ]
      \}

  augroup vimtex_config
    autocmd User VimtexEventInitPost VimtexCompile
  augroup END
  nmap <space>lv <plug>(vimtex-view)
  ```

</details>

<details>
  <summary>:VimtexInfo</summary>

  ```
  System info
    OS: Microsoft Windows 7 Professional  (6.1.7601 Service Pack 1 Build 7601)
    Vim version: NVIM v0.3.4
    Has clientserver: true
    Servername: \\.\pipe\nvim-12788-0

  vimtex project: minimal
    base: minimal.tex
    root: C:\test dir
    tex: C:\test dir\minimal.tex
    out: C:\test dir/minimal.pdf
    log: C:\test dir/minimal.log
    aux: C:\test dir/minimal.aux
    fls: C:\test dir/minimal.fls
    compiler: latexmk
      backend: nvim
      output: C:\Windows\TEMP\nvimeoAZfE\0
      configuration:
        continuous: 1
        callback: 1
        latexmk options:
          -pdf
          -pdflatex="xelatex %O %S"
          -verbose
          -file-line-error
          -synctex=1
          -interaction=nonstopmode
        latexmk engine: -pdf
      pid: 17304
      cmd: set max_print_line=2000 & latexmk -pdf -pdflatex="xelatex %O %S" -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e "$pdf_previewer = 'SumatraPDF -reuse-instance'" -e "$success_cmd = 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = 'echo vimtex_compiler_callback_failure'" "minimal.tex"
    viewer: General
    qf: LaTeX logfile
      config:
        fix_paths: 1
        packages:
          default: 1
        default: 1
    document class: article
  ```

</details>

<details>
  <summary>:VimtexCompileOutput</summary>

  ```
  Latexmk: This is Latexmk, John Collins, 25 October 2018, version: 4.61.
  Viewing pdf
  Latexmk: I have not found a previewer that is already running.
     So I will start it for 'minimal.pdf'
  ------------
  ------------
  Running 'start SumatraPDF -reuse-instance  "minimal.pdf"'
  ------------
  Latexmk: All targets (minimal.pdf) are up-to-date
  For rule 'view', running '&if_source(  )' ...
  ------------
  Running 'echo vimtex_compiler_callback_success'
  ------------
  vimtex_compiler_callback_success
  ```

</details>

**Comment by lervag** [comment]
Thanks, @pdf. I also much agree with your comment and I took the liberty of updating accordingly.

**Comment by lervag** [comment]
@nadya-p Are you able to do a git bisect to find which commit breaks things?

**Comment by nadya-p** [comment]
The regression was introduced in the changeset
`1b3a70d64914bc7ba854d2ef84fd15497997623a` Fixed #1285: Handle cygwin paths

**Comment by lervag** [comment]
I see.  That commit comes from a pull request by @pirofti. I personally do not use Windows, and so I can't test or develop vimtex on Windows. As such, I rely on external contributions. In this particular case, it would be very helpful if @pirofti could comment here and try to help out.

Else we could also do some "pair-debugging". That is, I ask you to test things, you report back the resuts.

The first action would be to investigate what the "bad" commit actually does in your case: Apply the following diff, perform your "test case" and report the output of the "echom" commands.

```diff
--- a/autoload/vimtex/view/general.vim
+++ b/autoload/vimtex/view/general.vim
@@ -45,9 +45,11 @@ function! s:general.view(file) dict abort " {{{1
   endif

   " Update the path for Windows on cygwin
+  unsilent echom 'before' outfile
   if executable('cygpath')
     let outfile = substitute(system('cygpath -aw '.outfile), '\n', '', 'g')
   endif
+  unsilent echom 'after ' outfile

   if vimtex#view#common#not_readable(outfile) | return | endif
```

**Comment by dussek** [comment]
I have the same problem and did the investigation you suggested. It was @pirofti's update [1b3a70d](https://github.com/lervag/vimtex/commit/1b3a70d64914bc7ba854d2ef84fd15497997623a) which causes the problem. I was able to fix the issue by quoting the filename:

```diff
diff --git a/autoload/vimtex/view/general.vim b/autoload/vimtex/view/general.vim
index d9f31b4..8044175 100644
--- a/autoload/vimtex/view/general.vim
+++ b/autoload/vimtex/view/general.vim
@@ -46,7 +46,7 @@ function! s:general.view(file) dict abort " {{{1

   " Update the path for Windows on cygwin
   if executable('cygpath')
-    let outfile = substitute(system('cygpath -aw '.outfile), '\n', '', 'g')
+    let outfile = substitute(system('cygpath -aw "'.outfile.'"'), '\n', '', 'g')
   endif

   if vimtex#view#common#not_readable(outfile) | return | endif
```

**Comment by pirofti** [comment]
Hello everyone,

Sorry for getting back to you so late and, @dussek, @nadya-p , sorry about breaking your workflow. I have been very busy and never got around to testing since the issue was opened.

I cannot reproduce your issue. I tried with spaces in the directory names, in the file name and in both cases and all work fine for me.

On the good side, I tried your diff also and it doesn't break anything for me. So if @lervag wants to apply it, then I have no objections.

Have a good day,
Paul Irofti

**Comment by dussek** [comment]
@pirofti: the problem manifests when working outside of Cygwin (which I don't even have installed -- my `cygpath` comes from an MSYS installation). The Windows command processor will convert a path with unescaped spaces into multiple parameters, e.g.,
```
cygpath -aw C:\directory name\file name
```
gets interpreted as
```
['cygpath', '-aw', 'C:\directory', 'name\file', 'name']
```
with resulting output
```
C:\directory
C:\current_location\name\file
C:\current_location\name

```

**Comment by lervag** [comment]
Sorry for taking so long!

Based on the input from @dussek and @pirofti, this issue should now be resolved. Thanks!

**Comment by nadya-p** [comment]
Thank you very much.
Indeed I have cygwin installed on my machine.
I confirm that the fix is working for me as well.

**Comment by lervag** [comment]
Happy to hear it!
