### ISSUE TITLE
Visual mode is interrupted while a "VimtexCompileOutput" window is open

### ISSUE THREAD

**Issue by ishitaku5522** [lervag/vimtex#1318]
## Issue
Visual mode is interrupted on CursorMoved while a "VimtexCompileOutput" window is open.

## How to reproduce
1. Open a .tex file
1. Press \\lo to open VimtexCompileOutput window
1. Move cusor to the window of .tex file
1. Press v to enter visual mode
1. Press l to move cusor

## Expected behavior
Keeping visual mode active even while a "VimtexCompileOutput" window is open.

## Cause of this issue
Changing window focus in s:output.update() interrupts visual mode:
https://github.com/lervag/vimtex/blob/master/autoload/vimtex/compiler.vim#L203

## Solution
Not update ouput window while visual mode is active. I think interruption of visual mode is not natural behavior for users and  comfortable text editing is more important than updating output.

See: https://github.com/lervag/vimtex/pull/1319

**Comment by lervag** [comment]
Thanks for posting and for submitting a fix! We'll continue the discussion in #1319.
