### ISSUE TITLE
vim re-appropriating focus after successful compilation

### ISSUE THREAD

**Issue by nasenatmer** [lervag/vimtex#132]
Hey, just started working with `vimtex` and I noticed tha vim is re-appropriating window focus after each successful compilation and it doesn't feel right to me. But maybe this is meant to be like this?

How to reproduce: once I've got a session up and running (i.e. tex file opened, starteded compilation, zathura is open as well), if I then do the following:

1. edit the text file
2. save the changes
3. and focus zathura (with `Alt-Tab`) to wait for the changes to become visible
4. once compilation has finished, vim is re-appropriating the focus (i.e., zathura loses focus and vim is in focus instead)

Obviously, the `latexmk_callback` function is run every time compilation is successful and `xdotool` focuses `vim`.

Is this meant to be like this? I'm not such a fan of windows auto-focusing themselves and so on, but I agree that there are some cases where this is useful behaviour. So if you plan to keep this: No worries, I will deactivate the callback function in my local clone and won't be bothered by this any longer.

**Comment by lervag** [comment]
Actually, the intention is only to re-appropriate focus to vim after the pdf viewer was opened by `latexmk`, so this is a bug. I'll look into it.

**Comment by lervag** [comment]
I think this should fix the problem.

**Comment by nasenatmer** [comment]
It doesn't. And if I understand the code correctly, it can't because if `self.xwin_exists` is positive, `call self.forward_search()` and `call self.focus_vim()` are executed, hence vim is focused again.

```vim
function! s:zathura.latexmk_callback() dict " {{{2
  " Try to get xwin ID
  if !self.xwin_exists()
    call self.xwin_get_id()
  endif

  " Some additional callbacks if possible
  if self.xwin_exists()
    call self.forward_search()
    call self.focus_vim()
  endif
endfunction
```

**Comment by lervag** [comment]
Haha, sorry. My bad! The logic is almost correct, but the lower conditional should ofcourse be INSIDE the upper conditional.

**Comment by nasenatmer** [comment]
Alright! This is also wrong in `function! s:mupdf.latexmk_callback()`

**Comment by lervag** [comment]
Yes, that's right. Thanks!

**Comment by nasenatmer** [comment]
Great! Problem solved! Additionally, this update also stops forward search from being executed at every successful compilation. I planned to ask for making this changeable as I was a bit distressed by zathura always jumping to the current cursor position in vim and highlighting it. But it works like a charm as it is now!

**Comment by lervag** [comment]
Yes, I never wanted the viewer callback to do more than to start the pdf viewer (with forward search) and ensure that vim focus is not lost. Now it works here as well. :)
