### ISSUE TITLE
Inner text objects select incorrect region when text object is empty

### ISSUE THREAD

**Issue by olmokramer** [lervag/vimtex#1320]
When an "inner" text object (<kbd>id</kbd>, <kbd>ie</kbd>, etc.) is empty, it selects one character before and one character after the text object.

In the .tex file, put the cursor on the first `\begin{equation}`, then press `cie`. The `}\` is removed. Now put the cursor between the `[]` and press `cid`. The `[]` is removed. I would expect this to behave similarly to vanilla Vim's `ci[`.

Minimal .tex
```tex
\documentclass{article}
\begin{document}
\begin{equation}\end{equation}
\begin{equation}
    []
\end{equation}
```

Minimal .vimrc
```vim
set nocompatible

let &runtimepath = '~/.vim/pack/plugins/start/vimtex,' . &runtimepath . ',~/.vim/pack/plugins/start/vimtex/after'
filetype plugin indent on
syntax enable
```

**Comment by lervag** [comment]
Thanks! Confirmed, I'll try to fix it later this week.

**Comment by olmokramer** [comment]
That was quick :P

**Comment by andymass** [comment]
@lervag, If you happen to have any trouble implementing this feel free to check out my take;
https://github.com/andymass/vim-matchup/blob/53c9101f65cea0d51dd3a1254946254a13e8f96d/autoload/matchup/text_obj.vim#L85

Conversely, if you know of a better implementation, I'm interested to see it here.

**Comment by lervag** [comment]
Thanks @andymass! I've tried to implement something similar, see the commit. My hypothesis (which might be wrong) is that it is enough to add temporary text for the `d` and `c` operators. For other operators, I simply fix the selection range.

**Comment by lervag** [comment]
@andymass Could you explain this part?

https://github.com/andymass/vim-matchup/blob/53c9101f65cea0d51dd3a1254946254a13e8f96d/autoload/matchup/text_obj.vim#L98:#L101

**Comment by olmokramer** [comment]
@lervag I tried your commit, and it seems to work for `c` and `d` but for other operators it still selects the character right after the text object. For example, in the empty equation env, `yie` yanks the `\`. Not much of a problem for `y` I think, because why would one yank an empty text object... but I have some custom operators where this can be a problem.

**Comment by andymass** [comment]
@lervag the intent was to place the cursor in the same place `ci[` does, although looking at it now it's clearly wrong (since `|` is virtual pos not byte pos).  Thanks for bringing my attention to it.  For some reason it didn't work with `#pos#set_cursor`

**Comment by lervag** [comment]
I'm not quite sure how to solve this in general. It is easy to fix special cases, though. So if you (or anyone) can provide me with examples that still does not work as expected, then I can fix them. If I get multiple different examples, that could help in finding a more general solution as well.

**Comment by olmokramer** [comment]
It happens with [vim-sandwich](https://github.com/machakann/vim-sandwich), for example. And also with my custom operator:

```vim
" ~/.vim/autoload/operator/replace.vim

function! s:visualmode(type) abort
	let types = {
		\ 'char': 'v',
		\ 'line': 'V',
		\ 'block': "\<C-v>",
	\ }

	return has_key(types, a:type) ? types[a:type] : a:type
endfunction

function! s:select(type) abort
	if "v\<C-v>" =~? a:type
		normal! gv
	elseif a:type == 'char'
		normal! `[v`]
	elseif a:type == 'line'
		normal! '[V']
	elseif a:type == 'block
		normal! '[<C-v>']
	else
		throw 'Unknown selection target'
	endif
endfunction

function! operator#replace#operatorfunc(type) abort
	if a:type ==# "\<C-v>" || a:type == 'block'
		echoerr 'Block mode replace not supported'
		return
	endif

	call s:select(a:type)
	normal! "_d

	let linewise = s:visualmode(a:type) == 'V'

	if (linewise && line('.') < line("'[")) || (!linewise && col('.') < col("'["))
		let p = 'p'
	else
		let p = 'P'
	endif

	execute printf('normal "%s%s', s:register, p)
endfunction

function! operator#replace#nmap() abort
	let s:register = v:register

	let c = nr2char(getchar())

	set operatorfunc=operator#replace#operatorfunc

	if c == 'r'
		call feedkeys('0g@g_')
	else
		call feedkeys('g@' . c)
	endif
endfunction

function! operator#replace#xmap() abort
	let s:register = v:register
	call operator#replace#operatorfunc(visualmode())
endfunction
```

```vim
" ~/.vim/vimrc

nnoremap ,r :<C-u>call operator#replace#nmap()<CR>
xnoremap ,r :<C-u>call operator#replace#xmap()<CR>
```

**Comment by olmokramer** [comment]
Now that I look at it, my operator uses `` `[v`] `` to select the text to delete, but that of course selects one character at the position of the operated text. So this is actually a bug in my operator, as it should not delete anything if the operated text is empty.

**Comment by olmokramer** [comment]
Yes that was the cause. Ignoring empty selections in my operators resolves the issue. I don't know if there's anything else you can do, as the text objects do set the position of `'[` equal to the position of `']`, i.e. `getpos("'[") == getpos("']")`.

**Comment by lervag** [comment]
Thanks for more info. But, similar to you, I don't really see how to improve this further. Let me know if you (or anyone) should think of something!

**Comment by olmokramer** [comment]
You're welcome, and thank you for the quick follow-ups!

**Comment by lervag** [comment]
No problem, happy to help :)
