### ISSUE TITLE
compilation slow

### ISSUE THREAD

**Issue by henrllb** [lervag/vimtex#1321]
Hi,

first, thank you for your work and your excellent plugin, that I use every day since 5 years! 

Just a remark: I update yesterday the plugin (with vundle). My last update was 2 years old (ok, that's not good!). The actual version looks very nice (for example, I like the new `:VimtexTocToggle`).

But, I am noting that the compilation on the new version is slower than the 2017 version. I have to wait 2/3 seconds before the `vimtex: Compilation completed message` appears, when it was almost instantaneous with the old version.

I don't use any `.latexmkrc`. The `:VimtexInfo` information output looks similar in the two versions. I use vim version 8.1.837 under Ubuntu 18.04 and python3 (version 3.6.7).

The git log of the old vimtex version (ref 327873e49a891a5e16cc5e5c624eb7eb4ebd407d) says:

```
commit 327873e49a891a5e16cc5e5c624eb7eb4ebd407d (HEAD -> master, origin/master, origin/HEAD)
Author: Karl Yngve Lervåg <karl.yngve+git@gmail.com>
Date:   Mon Oct 30 22:02:28 2017 +0100
```

Is it normal?

Best

**Comment by lervag** [comment]
> first, thank you for your work and your excellent plugin, that I use every day **since 5 years** !

Wow, that's cool. I'm happy to hear you like it!

Vimtex does not do any compilation, this is passed to `latexmk`. As such, compilation should not be slower. 

You claim that compilation is faster in 327873e than at the current master HEAD. Are you able to create an example that reproduces your issue? I.e., if I run the two different versions on the same example, it should be faster in the old version.

**Comment by henrllb** [comment]
Hi, 

you are right, the compilation by latexmk is the same. But, in vim, the return of vimtex is slower in the new version.

To reproduce : 

.vimrc :  
set nocompatible
let mapleader = ","
let maplocalleader = ","
set rtp+=~/.vim/vundle/vundle/
filetype plugin on
call vundle#begin()
Plugin 'lervag/vimtex'
call vundle#end()

I link then ~/.vim/bundle/vimtex on the old or the new version.

Latex file : 

\documentclass{article}
\begin{document}
This is a test
\end{document}

Now, you runs vimtex (this is the same effect in the two version). Then remove 'i" in "This" and :w

In the old version I immediatly see "vimtex: Compilation completed". In the new version, the message comes after some times.

Best

**Comment by lervag** [comment]
Ok, I've tested. For me, the latest version feels much snappier than the one you referred to. Thus, I can't really reproduce this. :\

**Comment by henrllb** [comment]
Ok! Thank you very much for testing so quickly. 

So, this means it is not a vimtex problem, but more likely a conflict with a package of my distribution.

Thanks again for your excellent work !

**Comment by lervag** [comment]
No problem. And thanks!
