### ISSUE TITLE
Motion through boundaries with `][` and `[]`

### ISSUE THREAD

**Issue by unoqualsiasi60** [lervag/vimtex#1322]
I tried to move through section boundaries. I noticed that invoking `[[` or `]]` through the boundaries, typically `\section` and `\subsection` commands (as in the example below), the cursor moves regularly to the previous or next section as expected. Instead, by pressing `][` od `[]`, the cursor moves only to the upper or the lower row or in other places, but not to the same level section as it should.

I've tried using Linux Fedora, Debian (updated to the most recent versions) and Windows with the same results.

The minimal LaTeX code used for the tests is shown below:

```tex
\documentclass{article}
\begin{document}
\section{One level}
Text
\subsection{One sublevel}
Text
\section{Another level}
Text
\subsection{Another sublevel}
\end{document}
```

Thanks for your patience
Best Regards
Franco Pasut

**Comment by lervag** [comment]
> I've tried using Linux Fedora, Debian (updated to the most recent versions) and Windows with the same results.

There should not be different behaviour on different OS/systems, so this is expected.

> I tried to move through section boundaries. I noticed that invoking `[[` or `]]` through the boundaries, typically `\section` and `\subsection` commands (as in the example below), the cursor moves regularly to the previous or next section as expected. Instead, by pressing `][` od `[]`, the cursor moves only to the upper or the lower row or in other places, but not to the same level section as it should.

I am not quite sure I understand exactly. Could you be more explicit on what you are doing and what you expect? E.g.:

1. I put my cursor in line 3 (`\section{One level}`).
2. Do `][`, expect that cursor moves to ...
3. Observe that cursor moves to ...

And similar. This will help me recognize whether you are describing a bug or if the motion just behaves unexpected.

If you add an empty line before each `\section` or `\subsection` and the `\end{document}`, do things work as expected then?

**Comment by unoqualsiasi60** [comment]
In fact, I expected the `[]` and `][` movement to be different from the one it really is. 
That is, as it happens in other languages (Markdown for example) the jump was between sections of equal level.
Instead, the jump points to space beyond the boundary of the level.
In this way an empty line after the level marker really works. 
Thank you for your answer.

**Comment by lervag** [comment]
No problem. If I understand correctly, we may close this issue now.
