### ISSUE TITLE
Main file detection fails when compiling from a buffer containing a separate preamble file (resulting in compiler errors)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1323]
For a large project like a PhD thesis, the preamble can get very long with lots of custom commands and packages. It is often convenient to separate this into a file of its own, say `preamble.tex`, and using the directive `TEX root` in the comments at top of the file to provide the path to `main.tex`.

In this scenario, when compiling the project from within the `preamble.tex` buffer, vimtex's main file detection mechanism fails, resulting in it trying to compile `preamble.tex`, not only inconveniently producing a bunch of auxiliary files, but also erroring out with the message equivalent to `\begin{document} not found`.

### Steps to Reproduce

1. Make the following 'main' file `main.tex` 

```
\input{preamble.tex}

\begin{document}
  Hello world
\end{document}
```

2. Make the following `preamble.tex` file

```
%! TEX root = main.tex

\documentclass[a4paper]{article}
\usepackage{amsmath}
```

3. Now compile the project with vimtex from `preamble.tex`.  A fatal error will be reported, and compilation stops straightaway, and the directory will be littered with `preamble.aux`, `preamble.fdb_latexmk` etc.

**Comment by krishnakumarg1984** [comment]
@lervag thank you for the fix.

**Comment by lervag** [comment]
No problem! Sorry for taking so long, I've been very busy lately with work, family time, and similar.
