### ISSUE TITLE
[feature request] Enhanced gf command for addbibresource

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1326]
Pressing `gf` anywhere on a line containing `\addbibresource{references.bib}`, should open the bib file in the buffer.  Presently, this is not the case. It is quite helpful to have this feature akin to `\include` and `\input`.

**Comment by lervag** [comment]
I agree. I think it should work now.

**Comment by krishnakumarg1984** [comment]
@lervag thank you. I forgot to mention this originally, but `addbibresource` is a `biblatex` command. For `natbib` and other traditional bibliography packages, we need this feature for the `\bibliography{<mybibfile>}` command.

**Comment by lervag** [comment]
I know, and so I added support for both commands already. Let me know if it does not work as expected.

**Comment by krishnakumarg1984** [comment]
Works like a charm! Thank you.

**Comment by lervag** [comment]
No problem :)
