### ISSUE TITLE
vimtex_compiler_progname does not recognize full path to nvr installation in conda environment

### ISSUE THREAD

**Issue by astier** [lervag/vimtex#1327]
neovim 0.3.4

I have a conda-environment just for vim where I install neovim specific things like pynvim, black (a python-code-formatter). Then I set in my vimrc the full paths to those tools. Vim recognizes this tools which I mentioned. However this doesn't work for neovim-remote. I set the full path with the vimtex_compiler_progname but when I run :checkhealth vimtex complains.

> WARNING: Compiler callbacks will not work!

However, vimtex recognizes nvr if I do not set the full path but replace it with *nvr*, activate the respective conda-environment and then start vim. This sucks because then I would need either to install neovim-remote globally or to activate the respective conda-env each time I want to use vimtex.

**Comment by lervag** [comment]
Hi. I'm not really accustomed to Anaconda, so this might be difficult to help with.

The first and important step that might help me help you is for you to describe very explicitly what you do, preferably in a minimal manner. That is, create a minimal vimrc file that sets the relevant configuration, and describe how to reproduce your problem. When I say minimal, I mean minimal. It should be something similar to this:

```vim
set nocompatible
let &rtp = '/path/to/vimtex,' . &rtp
let &rtp .= ',/path/to/vimtex/after'
filetype plugin indent on
syntax enable

" Set relevant Vim and neovim settings
set vimoptions=setting

" Set relevant vimtex configuration
let g:vimtex_options = 'setting'
```

**Comment by astier** [comment]
I assume you have a linux system. Here are the steps to reproduce:

1. Create vimrc for nvim
```vim
call plug#begin('~/.local/share/nvim/plugins')
Plug 'lervag/vimtex'
call plug#end()
let g:vimtex_compiler_progname = 'nvr'
" let g:vimtex_compiler_progname = $HOME.'/miniconda3/envs/nvim/bin/nvr'
```
2. Install miniconda
```sh
curl -O https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
sh Miniconda3-latest-Linux-x86_64.sh
```
3. Create conda environment for nvim and install neovim-remote (pynvim is also automatically installed as a dependency)
```sh
conda create -n nvim psutil
source activate nvim
pip install neovim-remote
```

4. Verify that vimtex detects nvr with activated conda environment
```sh
source activate nvim
nvim
:checkhealth
```
![2019-03-01-094132_365x138_scrot](https://user-images.githubusercontent.com/36510152/53626546-48c74500-3c06-11e9-834e-762783690f5a.png)

5. Verify that vimtex doesn't detect nvr with deactivated conda environment
```sh
conda deactivate
nvim
:checkhealth
```
![2019-03-01-094504_536x139_scrot](https://user-images.githubusercontent.com/36510152/53626684-b5424400-3c06-11e9-8221-98e9f095aa43.png)

6. Set absolute path to nvr in vimrc
```vim
" let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_compiler_progname = $HOME.'/miniconda3/envs/nvim/bin/nvr'
```

7. Test if vimtex detects nvr with deactivated/activated conda environment and full path to nvr (it should but it doesn't in both cases)
```sh
conda deactivate / source activate nvim
nvim
:checkhealth
```
![2019-03-01-095113_624x207_scrot](https://user-images.githubusercontent.com/36510152/53627017-8f696f00-3c07-11e9-8256-2884f89fc4bc.png)

This however is probably not an issue of nvim because nvim is able to detect pynvim if the absolute path is given.

1. Verify that nvim can't detect pynvim without full path
```sh
conda deactivate
nvim
:checkhealth
```
![2019-03-01-101041_691x240_scrot](https://user-images.githubusercontent.com/36510152/53628042-4830ad80-3c0a-11e9-9710-45b6bb2e22b2.png)

2. Set full path to python in vimrc
```vim
let g:python3_host_prog = $HOME.'/miniconda3/envs/nvim/bin/python'
```

3. Verify that nvim can detect pynvim with full path
```sh
conda deactivate
nvim
:checkhealth
```
![2019-03-01-101201_677x106_scrot](https://user-images.githubusercontent.com/36510152/53628129-77dfb580-3c0a-11e9-8e4b-20d5f8a7ffe6.png)

I would expect such an behavior also from vimtex.

**Comment by lervag** [comment]
Ah, thanks. I think I figured it out, please test.

**Comment by astier** [comment]
Works. Thank you.

**Comment by lervag** [comment]
Great!
