### ISSUE TITLE
Omni-complete command patterns

### ISSUE THREAD

**Issue by wwywong** [lervag/vimtex#1328]
Is there a way to easily add additional triggers for \ref or \cite omni-completion? 

I have some private macros for extended referencing, which uses for exame \descref and \descthref for cross referencing. It would be good if I can add those commands to the pattern to allow omni completion to treat those also like \ref's.

**Comment by lervag** [comment]
I've added the feature. Please check the documentation for `g:vimtex_complete_bib` and `..._ref` and the `custom_patterns` key. Let me know if anything is unclear.

**Comment by wwywong** [comment]
Awesome!
I just tested it out and it works great (I just modified the patterns that were in complete.vim and put in into the custom_patterns key). 
Minor comment: in the documentation for ..._ref, I think you just copied and pasted from the one for ..._bib, and it reads "bibliography" instead of "reference". 

Thanks so much for the quick update!

**Comment by lervag** [comment]
Thanks for noticing the typo. Should be fixed now. :)
