### ISSUE TITLE
Folding the frame environment with option

### ISSUE THREAD

**Issue by gipert** [lervag/vimtex#1329]
I noticed that the following `frame` environment:
```tex
\begin{frame}{Frame title}
...
\end{frame}
```
gets correctly folded as
```
\begin{frame}        Frame title
```
(even if I don't understand why there are so many spaces in between the two things) but if an option is specified to the environment:
```tex
\begin{frame}[c]{Frame title}
...
\end{frame}
```
Then the frame title isn't displayed anymore. Some failing regex, I guess? Can you reproduce it? If yes can this behaviour be easily fixed?

**Comment by lervag** [comment]
The latest update should fix this. It won't handle every edge case, though, but in most cases it should work.
