### ISSUE TITLE
latexmk process not stopping after I exit Neovim

### ISSUE THREAD

**Issue by chuckmasterson** [lervag/vimtex#1332]
This looks a lot like #1032, but I was requested to open a new issue for it. Title basically says it. Here's what I tried:

``` sh
$ killall perl        # to kill any existing latexmk processes
$ nvim -u ~/.config/nvim/bundle/vimtex/test/examples/minimal/minivimrc
```

(Neovim doesn't seem to understand this `--servername` business: `Unknown option argument: "--servername"`

``` vim
:e mwe-latexmk-doesnt-stop.tex
" which is a file that just says...
\documentclass{article}

\begin{document}
  Testing
\end{document}
```

And then I press `\ll`, and of course the compilation is completed almost instantly. I open up another terminal...

```sh
$ pgrep perl
9450
```

So I've got perl running latexmk at PID 9450. Then in Neovim I do a simple `:q`. Run `$ pgrep perl` again... and process 9450 is still running.

This seems to happen consistently whenever I shut down Neovim after running latexmk through vimtex. I just tried, and it doesn't seem to happen after just running `$ latexmk mwe-latexmk-doesnt-stop.tex`.

My system information:
- MX Linux 18.1
- Neovim v0.2.3-775-gba87a2cde
- Last commit on vimtex before I cloned from Github was Feb. 26, 2019
- As far as I know I don't have a `.latexmkrc`
- When I run `:VimtexInfo` it just says "Not an editor command"; not sure how I'm supposed to fix this (I ran `:Helptags` to get `:h vimtex` working, but that doesn't seem to make this command work)

Anything else you need to know, or tests I should run?

**Comment by lervag** [comment]
If  `:VimtexInfo` is not a command, then you are not using `vimtex`. My initial guess is that you are using polyglot, which enables LaTeX-Box by default for tex files. 

Note: This is exactly why the issue template (and thus, I) also asks you to provide a minimal vimrc file. Since you are now not providing any info on your vim configuration, I will not be able to give more than speculative advice.

Regarding `--servername`, please read `:help vimtex-faq-neovim` for some more info.

Finally, please note that you are quite a lot behind recent versions of neovim.

**Comment by chuckmasterson** [comment]
The vimrc file I used was the one that came with vimtex; I was trying to show that by providing the full path to it. I checked, and none of the keybindings in my actual .vimrc work, so it's not loading both.

Is it possible for `:h vimtex` to work even if I'm not running Vimtex? Because I get the Vimtex documentation, complete with `(c) 2019 Karl Yngve Lervåg`, when I use that command, but I get nothing from `:VimtexInfo`. I don't have Polyglot installed; I just have the following (`$ cd ~/.config/nvim/bundle` `$ ls`):

```
bufexplorer   scrollfix             vim-easyclip       vim-session
clever-f.vim  vim-airline           vim-fugitive       vim-surround
ctrlp.vim     vim-auto-save         vim-jekyll         vimtex
desert.vim    vim-bracketed-paste   vim-misc           vim-textobj-quote
falcon        vim-colors-pencil     vim-pandoc-syntax  vim-textobj-sentence
goyo.vim      vim-colors-solarized  vim-pencil         vim-textobj-user
move          vim-commentary        vim-repeat         vim-vinegar
```

**Comment by chuckmasterson** [comment]
Aha! Your final note was the trick. I upgraded Neovim and the problem is solved. (Must make a note to do that more often; I build it from source since AppImages annoy me.) Sorry the solution was so trivial... but then again I guess that's a good thing as far as debugging goes.

Side note, I was definitely using vimtex the whole time, because when I compile it tells me, `vimtex: Compilation completed`, but even after upgrading I don't get anything from `:VimtexInfo`. If this is an issue it's a separate issue, though, I suppose. It doesn't really affect me so I'll leave it to your discretion whether it's something to spend time on.

**Comment by lervag** [comment]
> The vimrc file I used was the one that came with vimtex; I was trying to show that by providing the full path to it.

Ah, sorry, I didn't notice that, and it should have worked. (I was also once on neovim 0.2.3, and it used to work back then as well.)

In any case, I'm happy to hear it works after upgrading!
