### ISSUE TITLE
Omni completion problem when label is empty

### ISSUE THREAD

**Issue by MiguelGodinhoMatos** [lervag/vimtex#1334]
If a latex file has a label that was left empty the vimtex plugin autocomplete feature stops working. Had this problem while writing a paper recently and I was ready to go back to latexbox before i figured out what the problem was. 

Here is a reproducible example: 

```
\documentclass{article}
\begin{document}
\section{first section}
\label{}
\section{second section}
\label{works}
\ref{
\end{document}

```
And here is the error i get: 

<img width="515" alt="error" src="https://user-images.githubusercontent.com/695753/53946800-655af580-40bc-11e9-8c81-6b5689938a39.png">

As soon as the first section label is fixed everything starts working again.

**Comment by lervag** [comment]
Thanks, this should be fixed now.
