### ISSUE TITLE
How do I disable Latex-box, from polyglot

### ISSUE THREAD

**Issue by matbc92** [lervag/vimtex#1335]
I am a bit of a newbie to the vim(actually I'm using neovim to be a bit more specific) world, and latex too for that matter. Being so I got a pre-set plugin package from http://nvim.fisadev.com/ (this place) and It comes with polyglot, the package works wonders with python files(my intent all the way) but it seems it comes with latex-box from the polyglot, and I have no clue how to use that plugin, had no luck searching for any newbie approachable guide of how to set things up, and since vimtex seems to provide more information, and to update more frequently I decided to try to set that up, but then I have to disable the latex-box plugin, and I have no clue of how to do so.

**Comment by lervag** [comment]
I strongly discorouge the use of polyglot (and pre-sets in general), as you should strive to know what you are doing.

However, if you insist on using pre-sets, you can use

```vim
let g:polyglot_disabled = ['latex']
```

in your vimrc file to disable LaTeX-Box.
