### ISSUE TITLE
spelllang switch triggers

### ISSUE THREAD

**Issue by rubdos** [lervag/vimtex#1338]
I hope you're okay with a feature request! I'm not even sure `vim` can support it, but here goes. I often write Dutch (`spelllang=nl_be`) documents these days for teaching, with some English terminology. Using XeLaTeX, I can do:

```latex
% vi: spelllang=nl_be
\documentclass{beamer}
\usepackage{polyglossia}
\setdefaultlanguage{dutch}
\setotherlanguage[variant=british]{english}
\title{Dit is een Titel}
\begin{document}
\maketitle

\begin{frame}{\textenglish{What's next?}}
  Vorige lessen:
\end{frame}

\end{document}
```

Vim sets the `spelllang` to nl_be, and sees "What's next?" as Dutch. It would be terrific if it were somehow possible to set the spelllang from the language package used in LaTeX, and specifically in those small "zones".

My knowledge of vim and vimscript is too limited to know whether this would be possible, but I would be okay with writing most of it myself, if I can get some pointers.

**Comment by lervag** [comment]
Thanks for the request. But I don't think this is possible, unfortunately. Vim only operates with a single language or a list of languages per buffer (see `:help spelllang`). It is not possible (to the best of my knowledge) to specify different zones for different languages.
