### ISSUE TITLE
set path

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#1340]
Inspired by https://vimways.org/2018/death-by-a-thousand-files/ the paths of the LaTeX packages  by the user and the LaTeX distribution could by added to &path to permit jumping to their definitions. This addition to `&path` should probably, at least for paths to the packages by the LaTeX distributions, be made optional: For example, TeXlive installs all available packages, of which there are around 6000, causing a considerable slowdown when looking up keywords and definitions.

Here is a roughly how these paths to all packages to `&path` could be added in, say, `~/.vim/after/ftplugin/tex.vim` :

```vim
let &l:include = &include . '\v' . (empty(&include) ? '' : '\|') . '\s*\\%(usepackage|RequirePackage)%(\s*\[[^]]*\])?s*\{\zs[^\}]*\ze\}'

if !executable('latex')
  echoerr 'Executable latex not found! Please install a LaTeX distribution such as TeXlive.'
  finish
endif

if executable('kpsewhich')
  let pathes = split(system('kpsewhich -var-value=TEXMFHOME'), '\n')
  for path in pathes
    exe 'setlocal path+=' . path . '/tex/latex/*'
  endfor
  unlet pathes
elseif isdirectory('~/texmf/tex/latex')
  setlocal path+=~/texmf/tex/latex/*
endif

if has('unix')
  let latex_path = system('command -v latex')
  if match(latex_path, '/texlive/') == -1
    setlocal path+=/usr/share/texmf/tex/latex/*
    setlocal path+=/usr/share/texmf-texlive/tex/latex/*
  else
    let root = substitute(latex_path, '/bin/.*$', '', '')
    let path_pack = root . '/texmf/tex/latex/*'
    let path_dist = root . '/texmf-dist/tex/latex/*'
    let path_local = substitute(root, '\v/\d+$', '', '') . '/texmf-local/tex/latex/*'
    exe 'setlocal path+=' . path_pack
    exe 'setlocal path+=' . path_dist
    exe 'setlocal path+=' . path_local
  endif
endif
```

With these settings, for example in a TeX document containing
```tex
\RequirePackage{mathtools}
\DeclarePairedDelimiter{\hull}{\langle}{\rangle}
```
hitting `[<c-d>` on the second line jumps, on my manual  TeX-live installation (= not by the Linux distribution's package manager) from last year, to line `707` of `/usr/local/texlive/2018/texmf-dist/tex/latex/mathtools/mathtools.sty` where one reads
```tex
\newcommand*\DeclarePairedDelimiter[3]{%
  \@ifdefinable{#1}{
    \MT_delim_default_inner_wrappers:n{#1} % define the wrappers
...
```

**Comment by Konfekt** [comment]
Setting  `path`, so it seems to me, should after all be unnecessary because `&includeexpr` uses `kpsewhich`. However, only setting
```vim
let &l:include = &include . '\v' . (empty(&include) ? '' : '\|') . '\s*\\%(usepackage|RequirePackage)%(\s*\[[^]]*\])?s*\{\zs[^\}]*\ze\}'
```
does not permit to look up the definition's in the packages of the distribution, no results are found.

**Comment by lervag** [comment]
Sorry, but I am not quite sure what you are asking. You are right that vimtex does not set the `path` option. And so, it could be relevant to set it to something useful in the spirit of "death by a thousand files". However, if we consider it from a pragmatic angle, I am curious which issue we are really adressing. I don't think that most people really wants to go to the package definitions.

Also, I was not able to make your suggested path setting work for me for your example.

In any case, I think it would be better to turn this on its head: You are describing how to solve the issue, but you are not clearly describing which feature is lacking. Provide a concrete example of it (i.e. observed vs expected behaviour). I think that would make it easier to address.

**Comment by Konfekt** [comment]
>   you are not clearly describing which feature is lacking
>  I don't think that most people really wants to go to the package definitions.

But that is it, being able to jump to the definitions of commands not defined in the current working directory. Making the TeX source code explorable. 

I agree that most people are happy to stay away from reading TeX source code, but for the few that could care, maybe by mere curiousity, not  set it to a good guess that achieves that, instead of leaving it empty?

>  I was not able to make your suggested path setting work for me for your example.

Did the path as set up above point  on your installation to the packages folder?

**Comment by lervag** [comment]
Ok, I've added test files that _should_ work, but it returns errors for me.

With the pushed test files, I get the following output after `nvim -u minivimrc`:

```
dlist /test/

minimal.tex
  1:    2 \newcommand{\test}{test}
dlist /Declare/
Vim(dlist):E388: Couldn't find definition
```

**Comment by Konfekt** [comment]
Was the first line
```vim
let &l:include = &include . '\v' . (empty(&include) ? '' : '\|') . '\s*\\%(usepackage|RequirePackage)%(\s*\[[^]]*\])?s*\{\zs[^\}]*\ze\}'
```
included elsewhere? As noted in https://github.com/lervag/vimtex/issues/1340#issuecomment-473823676 I wonder why it was not sufficient on my system, because `&includeexpr` should already get the path of the package by calling `kpsewhich mathtools.sty`.

**Comment by lervag** [comment]
Ok, I've managed to make it work as expected (and I've pushed the updated test files).

I have a single worry: Will the updates lead to things taking longer to load/execute? I notice that the `dlist` command (and siblings) are slow.

I propose:

- To update the `include` to support `usepackage` and `RequirePackage`. I don't think this will have any bad consequences.
- To further discuss that `path` setting. Should it be optional and opt-in? Or am I just to worried?

**Comment by Konfekt** [comment]
>  To update the include to support usepackage and RequirePackage. I don't think this will have any bad consequences.
> To further discuss that path setting. Should it be optional and opt-in? Or am I just to worried?

:+1: 

As noted https://github.com/lervag/vimtex/issues/1340#issuecomment-473823676 the idea of amplifying path came first, then the discovery that `&includeexpr` should already do better than a vast `&path` by looking at `ls-R` via `kpsewhich`, but somehow it does not work. That could go into a new issue.

**Comment by lervag** [comment]
Ok, it seems you are right in that we do not need to set the `&path` for things to work. My test now works as expected. That is, at least partly. For some reason, when I run the automated test, it sometimes does _not_ find the keyword. But when I try it "manually", it seems to work consistently.

**Comment by Konfekt** [comment]
On my system, despite
```
➜ ~ kpsewhich mathtools.sty
/usr/local/texlive/2018/texmf-dist/tex/latex/mathtools/mathtools.sty
```
hitting `[<c-d>` on `DeclarePairedDelimiter` inside
```tex
\usepackage{mathtools}
\DeclarePairedDelimiter{\hull}{\langle}{\rangle}
```
immediately returns `E388: could not find definition`.

**Comment by Konfekt** [comment]
Ah, the `&includeexpr` was not correct. Works fine now!

**Comment by lervag** [comment]
Great, happy to hear it :)
