### ISSUE TITLE
Having problems with compiling

### ISSUE THREAD

**Issue by SimZor** [lervag/vimtex#1343]
Having problems compiling latex.

Info of install: https://i.imgur.com/qTuNolf.png
This is my neovimrc https://github.com/SimZor/dotfiles/blob/master/nvim/init.vim

Getting the following error when compiling (some Swedish):

```
Fel upptäcktes vid bearbetning av function vimtex#compiler#compile:
rad    1:
E716: Nyckeln finns inte i Dictionary: compiler, 'continuous')
E116: Ogiltiga argument till funktion: get
E15: Ogiltigt uttryck: get(b:vimtex.compiler, 'continuous')
Tryck RETUR eller skriv kommando för att fortsätta
```

I have skim installed and setup in vimrc if that makes any difference. I have installed MacTex, however, I'm not sure whether I need to or not.

**Comment by lervag** [comment]
Can you be somewhat more specific: I.e., "when compiling" - which mappings or commands are you using?

Are you able to create a minimal example as suggested in the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md)?

**Comment by SimZor** [comment]
It seems to be fine now. I don't know what I did.

MacTex is required for compiling right?

**Comment by lervag** [comment]
> MacTex is required for compiling right?

Yes and no: You need a valid and working LaTeX installation. MacTex is a convenient installation of Texlive for MacOS. I assume there are other options as well.

As you say things are fine, I'll take the liberty of closing the issue.
