### ISSUE TITLE
Viewer is not executable

### ISSUE THREAD

**Issue by LoneKrug** [lervag/vimtex#1345]
I am on Windows and I'd like to use mupdf as my viewer so I set it in my vimrc:

```
let g:vimtex_view_general_viewer = 'mupdf'
let g:vimtex_view_method = 'general'
```

I expected a working pdf viewer, but instead it says:
```
vimtex: Selected viewer is not executable!
        - Selection: mupdf
        - Please see :h g:vimtex_view_general_viewer
```

I've read the vimtex docs, but it is not clear for me if I have to add additional options to make mupdf work.
I also tried this with SumatraPDF. Same response.

I saw issue  #1093 and wondered if this is the same problem for Windows too.
Also, could it be that #416 was a related issue?

**Comment by lervag** [comment]
I assume this is because `mupdf` is not available as a command. If you open a cmd prompt (windows+r  ->  cmd  ->  enter), then type "mupdf", what happens? I expect it won't work. The reason is that programs by default are not available in the PATH environment variable. You either have to write the full path to the MuPDF-executable in the vimtex option, or you need to update your windows PATH variable so that the MuPDF binary is available.

**Comment by LoneKrug** [comment]
I had the programs available in the PATH variable. After some hours I installed another version of sumatrapdf and found the solution to this problem.

I had a 32-bit vim version and 64-bit versions of the viewers. Now I use 32-bit viewer versions and it is working flawlessly. If I use the 64-bit version of SumatraPDF it doesn't work again. This surprised me, actually.

May I suggest this will be added to the Windows troubleshoot section #412? Is good to open an open Github Issue just for people to comment their fix for something? I don't know if this is the right way to gather some troubleshooting tips, but maybe it could help.

Big thanks for responding to minor issues like these. You rock.

**Comment by lervag** [comment]
> Big thanks for responding to minor issues like these. You rock.

Thanks! :)

> I had a 32-bit vim version and 64-bit versions of the viewers. Now I use 32-bit viewer versions and it is working flawlessly. If I use the 64-bit version of SumatraPDF it doesn't work again. This surprised me, actually.

Interesting. I'm also a little bit surprised, but I also guess it makes some sense. In any case, I'm happy that you found the cause!

> May I suggest this will be added to the Windows troubleshoot section #412?

This section is found in `:help vimtex-troubleshooting`. The section is not really very well maintained, I admit. I would be happy to consider PRs for improving it. Reg. if this current issue should result in an update here: Well, this is the very first time I've heard of anyone having this problem. I think it would be better to add things that are more "common". If anyone else have a similar issue as you, they might either find this thread, or I might remember this. Besides, I am quite sure that most people don't really read all of the docs... :p

**Comment by andalou** [comment]
I have also the same problem. It's very common for people using windows
64 bit, and using vim 32 bit, like me.

**Comment by lervag** [comment]
This issue was closed almost a year ago. If you have a similar issue, you should still post it as a new issue and refer to this old issue if it gives relevant context. However, please provide a full description as suggested in the issue template.
