### ISSUE TITLE
`cse` sometimes behaves oddly

### ISSUE THREAD

**Issue by b-mehta** [lervag/vimtex#1347]
I have a large (~3000 line) tex file, and if I try `cse` inside any environment, it gives the error
```E117: Unknown function: vimtex#env#change_prompt```
However, if I make a copy of the file, `cse` works as expected.

Any ideas how I can get to the bottom of this problem? I can provide my vimrc or the tex file, but I'm not sure how helpful they would be, since the issue disappears for me using the same setup, and the file copied. This issue appears for more than one file, and seemed to begin when I updated plugins.

**Comment by lervag** [comment]
This is very strange. But if the problem dissapears when you create a copy of the file, then why don't you just copy the file, delete the original, and then work from the copy? Does the problem have anything to do with how you name the files?

For me to help, I need more specific information, and preferably a reproducible setup.

**Comment by b-mehta** [comment]
I don't think the problem is to do with file naming: changing from `analytic_number_theory.tex` to `analytic_number_theory2.tex` seems like a minor enough change that it shouldn't have an impact.
My suspicion is that this is to do with vim's swp/tmp files, but I don't know enough about how they work to debug this myself.

Is there any specific information I can provide that would help? If I try `:call vimtex#env#change_prompt`, the same error appears (in both the original and copied versions).

I can appreciate this is hard for others to help with, especially since I can barely reproduce the problem: so if the only possible fix you can determine is to just rename all my files, then I'm happy to close this issue.

**Comment by lervag** [comment]
Ah. `vimtex#env#change_prompt` no longer exists. I assume you have made a personal mapping. I will probably be able to help if you can provide the relevant part of your vimrc file.

**Comment by b-mehta** [comment]
I had considered this, but it doesn't explain why `cse` works in a copy of the file (with the same vimrc). Even then, I don't seem to have used `vimtex#env#change_prompt` in my vimrc, except perhaps here:

```
augroup latexsurround
   autocmd!
   autocmd filetype tex call s:latexsurround()
augroup end

function! s:latexsurround()
   let b:surround_{char2nr("e")}
     \ = "\\begin{\1environment: \1}\n\t\r\n\\end{\1\1}"
   let b:surround_{char2nr("c")} = "\\\1command: \1{\r}"
   let b:surround_{char2nr("h")} = "\\hyperlink{\1hyperlink: \1}{\r}"
   let b:surround_{char2nr("d")} = "\\hyperlink{def:\1definition: \1}{\r}"
endfunction
```

**Comment by lervag** [comment]
No, this is not it. There is most likely something wrong with your vimrc/vim configuration. It is impossible for me to help without knowing more about your system/case. Possible causes:

- Custom mappings in your vimrc file
- Custom mappings in personal `ftplugin/tex.vim` files
- Custom mappings in `after/ftplugin/tex.vim` files

**Comment by b-mehta** [comment]
I don't have any `ftplugin` files, but I found 
```
function! vimtex#env#init_buffer() " {{{1
  nnoremap <silent><buffer> <plug>(vimtex-env-delete)
        \ :call vimtex#env#delete('env_tex')<cr>

  nnoremap <silent><buffer> <plug>(vimtex-env-change)
        \ :call vimtex#env#change_prompt('env_tex')<cr>

  nnoremap <silent><buffer> <plug>(vimtex-env-delete-math)
        \ :call vimtex#env#delete('env_math')<cr>

  nnoremap <silent><buffer> <plug>(vimtex-env-change-math)
        \ :call vimtex#env#change_prompt('env_math')<cr>

  nnoremap <silent><buffer> <plug>(vimtex-env-toggle-star)
        \ :call vimtex#env#toggle_star()<cr>
endfunction
```
in `~/.vim/plugged/vimtex/autoload/vimtex/env.vim` (I'm using vim-plug on macOS).

It seems that something went wrong when my plugin manager updated `vimtex`...

**Comment by lervag** [comment]
Yes, I agree. You can probably do something like:

```sh
cd ~/.vim/plugged/vimtex/
git fetch
git checkout master
git reset --hard origin/master
```

**Comment by b-mehta** [comment]
This doesn't seem to fix it, but I'm fairly sure the problem is with my plugin installation rather than with this specific plugin, so feel free to close this issue.

Thanks for your help!

**Comment by lervag** [comment]
No problem. Another option is of course to simply delete the vimtex folder and install the plugin fresh.

**Comment by b-mehta** [comment]
I tried that too, but the problem is still there...

**Comment by lervag** [comment]
Huh. What? Does the `env.vim` file still have the same lines as you posted above?

**Comment by b-mehta** [comment]
It doesn't, but I think perhaps that's not where the plugins are being loaded from.

**Comment by lervag** [comment]
You can see which plugins are loaded with `:scriptnames`. It might have a lot of output, though, but still, it should give you a clear idea where the plugins are located.

**Comment by b-mehta** [comment]
Ah, part of my vimrc attempted to save folds using `mkview`, but this seemingly made a copy of the vimrc for each file, before I'd updated vimtex. In particular, it held onto the old mapping for `cse`, but with a newly named file, there was no old mapping.

**Comment by lervag** [comment]
Ah, that seems to make some sense, yes. I don't use this feature myself, so I didn't think of it. In any case, I'm glad it is resolved!
