### ISSUE TITLE
[Feature Request] Add coc.nvim support

### ISSUE THREAD

**Issue by voldikss** [lervag/vimtex#1349]
[coc.nvim](https://github.com/neoclide/coc.nvim) is a modern completion framework plugin for Vim/NeoVim. It's very fast and easy to use.

Currently I am using snippets with coc to compelte Tex code. Notice that vimtex have support for Deoplete, ncm2, YCM,  it will be fantastic if vimtex also support coc.nvim.

How do you think about this?

P.S. this might be helpful: [Create custom source
](https://github.com/neoclide/coc.nvim/wiki/Create-custom-source#start-by-a-simple-example)

**Comment by clason** [comment]
Did you see https://github.com/neoclide/coc-vimtex?

**Comment by voldikss** [comment]
I'm so sorry 😥 for that

**Comment by lervag** [comment]
No reason to be sorry! I think `coc-vimtex` should be documented in vimtex as well, which is currently missing.

**Comment by voldikss** [comment]
@clason @lervag I just forked vimtex project, the coc.nvim will be documented soon

**Comment by voldikss** [comment]
Just made a PR for coc.nvim & coc-vimtex introduction.

**Comment by lervag** [comment]
Thanks, @voldikss! I think #1351 resolves this issue. What do you think, @clason?

**Comment by clason** [comment]
Looks good! I'm not sure whether the installation instructions should be more explicit (installing CoC is _not_ as simple as `Plug 'neoclide/coc.nvim'`, since you also need to install the binary, which could be tricky depending on how much of the dependencies you've already installed)?

**Comment by voldikss** [comment]
Hmmmm It does need some pre-requirements...
I forgot it, and it should be introduced in detail.

But notice that it will be much stuff to about coc's installation, how about just providing the link of coc's README? https://github.com/neoclide/coc.nvim/blob/master/Readme.md

**Comment by clason** [comment]
Yes, that should be sufficient: make clear that it's not just `Plug` and play, and give a link to the installation instructions (although https://github.com/neoclide/coc.nvim/wiki/Install-coc.nvim is probably a better target than a deep link to the source code).

**Comment by voldikss** [comment]
Yes, I agree.

Since that's is a pretty little modification, a PR might be troublesome. So could please you modify and commit it?

It's midnight here, I am in the bed now :smile:

**Comment by lervag** [comment]
I think my update should resolve this.

**Comment by lervag** [comment]
By the way: Do you have any experience with `ncm2` and/or `deoplete`, and if so, how would you compare `coc.nvim` to these? I've used `neocomplete`, then `ncm2`, then `deoplete`, and for now I'm relatively satisfied with `deoplete`.

**Comment by voldikss** [comment]
Thank you @lervag 

I've being using Deoplete before CoC, it is quite convenient and out of box. However it seems to be pretty show, so I switched to CoC.

Besides, I haven't used ncm2 and neocomplete, I've used YCM 3 years ago when I came into Vim. But YCM is bulky.

**Comment by lervag** [comment]
Ok, thanks. I've not really had an issue with deoplete being slow. I looked into CoC yesterday, but it seems very inconvenient to configure.

**Comment by voldikss** [comment]
It's not that inconvenient actually. I won't persuade you to use coc, but if you did suffered a lot from Deoplete's slow performance you should have a try with coc. 

For people who haven't used coc before, it might be convoluted when they first looked at coc. But it has a quite detailed doc as well as it's [wiki](https://github.com/neoclide/coc.nvim/wiki). Furthermore, only the basic configuration can get coc to work.

Since you are a Vim developer, it will be fine for you to configure it.

Both deoplete and coc are excellent, just pick which are suitable for you.

**Comment by voldikss** [comment]
Ho! I just hear from vim-cn telegram group that coc is on the github trending today!
See https://github.com/trending :astonished:

**Comment by voldikss** [comment]
Sorry, just confusion:

I read vim-airline's document today, why not add that documentation in the doc/vimtex.txt?
see: https://github.com/vim-airline/vim-airline/blob/master/doc/airline.txt#L1061

**Comment by lervag** [comment]
Reg. vim-airline: Do you have a suggestion to where in the vimtex docs it should be mentioned? I don't think it makes sense to write much, but I agree it might be good to mention that the plugins work well together.

**Comment by voldikss** [comment]
I have no idea about this:(. Maybe that makes no sense, it's just a little integration which is hard to insert into the vimtex.txt

**Comment by lervag** [comment]
Ok, thanks. I think I'll leave it as it is, because the information is already clear at vim-airline's side, where it matters. If you (or anyone else) have a clear idea where and how it could be documented in vimtex, then I'm all ears.

**Comment by patricknraanes** [comment]
It might be worth documenting as well some map conflicts with coc's, whose README suggests a ton of mappings. For example, `nmap K` is used by both vimtex and coc to show documentation.

**Comment by lervag** [comment]
Yes, feel free to suggest something specific :)

**Comment by patricknraanes** [comment]
You mean a PR? I can do that. But there may be several other conflicts that I'm not aware of yet.

**Comment by lervag** [comment]
Either a PR or just a concrete suggestion is also fine. I'm not sure if it is worth commenting on all conflicts, though; these may change in time and keeping things updated will be too much work.
