### ISSUE TITLE
No module named 'colorama'

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1350]
```
:call vimtex#fzf#run('c')
```
raises on my machine following error

```
|| Messages maintainer: Bram Moolenaar <Bram@vim.org>
|| "document.tex" 767L, 21644C
|| Error detected while processing function
|| vimtex#fzf#run[11]
|| <SNR>93_parse_toc[48]
|| Traceback (most recent call last):
||   File "<string>", line 3, in <module>
|| ModuleNotFoundError: No module named 'colorama'
|| Error detected while processing function
|| vimtex#fzf#run[11]
|| fzf#run[36]
|| E605: Exception not caught: Invalid source type
```

New fzf.vim source requires non-standard python module colorama.

The description of colorama says

> Makes ANSI escape character sequences (for producing colored terminal text and cursor positioning) work under MS Windows.

I am on macOS. Do I need this @T-Rex96 ?

I would prefer if we do not need this by default.

By the way this should be documented, e.g. in

```
FZF INTEGRATION                                                   *vimtex-fzf*

                                           https://github.com/junegunn/fzf.vim
                                               https://github.com/junegunn/fzf
|fzf.vim| integrates the general-purpose command-line fuzzy finder |fzf| into vim
and neovim. Similar to the |denite.vim| and |unite.vim| source it may be used to
quickly navigate |vimtex|'s built-in ToC feature. To use it, just define a
mapping to `vimtex#fzf#run()` in your .vimrc, e.g.: >

  nnoremap <localleader>lt :call vimtex#fzf#run()<cr>

You can also choose to only show certain entry "layers", according to this
table (see |vimtex-toc| for detailed explanation of the "layers"):

  `c`:  content
  `t`:  todo
  `l`:  label
  `i`:  include

The default behavior is to show all layers, i.e. 'ctli'. To only show
`content` and `label`s use: >

  :call vimtex#fzf#run('ct')
```

**Comment by lervag** [comment]
I've pushed an update on this. What do you think, @kiryph? Does it work as expected? I.e.: Colorama is not necessary, but without it there are no colors.

**Comment by T-Rex96** [comment]
Oh I thought Colorama was a default python package, my bad. We could also just switch to plain ansi escape sequences for the colors in that case.

**Comment by kiryph** [comment]
@lervag: no, your recent commit does not avoid an error message if one does NOT have colorama.
The full messge is slightly different:

```
|| Error detected while processing function
|| vimtex#fzf#run[11]
|| <SNR>106_parse_toc[47]
|| Traceback (most recent call last):
||   File "<string>", line 22, in colorize
|| ModuleNotFoundError: No module named 'colorama'
|| During handling of the above exception, another exception occurred:
|| Traceback (most recent call last):
||   File "<string>", line 39, in <module>
||   File "<string>", line 39, in <listcomp>
||   File "<string>", line 33, in create_candidate
||   File "<string>", line 29, in colorize
|| NameError: name 'entry' is not defined
|| Error detected while processing function
|| vimtex#fzf#run[11]
|| fzf#run[36]
|| E605: Exception not caught: Invalid source type
```

**Comment by lervag** [comment]
Sorry, my mistake. Try again.

**Comment by kiryph** [comment]
Yes, this time the commit fixed it.

Is there a possibility to be colorful on platforms which understand Ansi Codes without colorama?
IMHO only windows users should be required to install colorama if colors are desired.

**Comment by lervag** [comment]
The obvious possibility is to install Colorama. Perhaps @T-Rex96 knows an OK an reliable way to add color codes with no extra dependencies that should work on Linux/MacOS?

**Comment by T-Rex96** [comment]
Yeah, I'll have a go tonight

**Comment by lervag** [comment]
Thanks for pushing an update that should solve this, @T-Rex96. It was merged now.

**Comment by lervag** [comment]
Ref. #1352.
