### ISSUE TITLE
pdf and bib file outside build_dir

### ISSUE THREAD

**Issue by xarthurx** [lervag/vimtex#1355]
I've set the `build_dir` as suggested in the help folder, but have a question relating to separate pdf/bib file from all the other files.

Once I set the `build_dir`, all compiled files except for the original `*.tex` file will be generated in that folder, and I also have to put reference files in that folder too.

My question is, is it possible to get another variables so that all the compile-related file is put into the `build_dir` folder, while make `*.pdf` and `*.bib` or whatever I need to the same location of the `*.tex` file?

In this way, I can make the project really clean for large projects.

**Comment by lervag** [comment]
> and I also have to put reference files in that folder too.

No, you don't. Move this file to the same folder as the `.tex` file.

> My question is, is it possible to get another variables so that all the compile-related file is put into the build_dir folder, while make *.pdf and *.bib or whatever I need to the same location of the *.tex file?

Yes, partly. You can use `g:vimtex_view_use_temp_files`, which will make a copy of the generated PDF file on successful compiles.

IMHO: Although I understand that you like to get the PDF file in the same location as the `.tex` file, you should remember that this file is also purely a generated file. As such, it makes sense to keep it in the same build directory, so as to keep the source files separated from the built files.

**Comment by xarthurx** [comment]
@lervag  Hi, thank you for your quick respond and thorough explanation.
Yes, the `bib` part works, as I don't need to put it in the `build_dir` folder.
And I agree that `*.pdf` is also generated from compilation and should be put into the `build_dir` folder.

One last question: I tried to set the `g:vimtex_view_use_temp_files` to either `1` or `2`, but nothing seems happened...

**Comment by xarthurx** [comment]
@lervag 
Hi, After rebooting neovim, now it seems everything works fine.
Thx.

**Comment by lervag** [comment]
Great, happy to hear things work for you now!

**Comment by xarthurx** [comment]
The only issue left is:
vimtex will not automatically open the pdf after compilation. And when conducting `vimtexview` command, it will then report cannot find the pdf file, but the sumatraPDF do open the `xxx_vimtex.pdf` file in the main folder.

I'm not sure if this is a vimtex bug.

I feel it make more sense to open the pdf in the build folder as it will help with automatic updates.

**Comment by lervag** [comment]
I can confirm that with these settings, vimtex does not automatically open the pdf after compilation with the general viewer. However, it should work when you do `\lv` or `:VimtexView`. What do you mean with the following?

> And when conducting vimtexview command, it will then report cannot find the pdf file, but the sumatraPDF do open the xxx_vimtex.pdf file in the main folder.

If you turn off the `g:vimtex_view_use_temp_files` option (it is off by default, so simply remove from your config), then I would assume that things work as expected. Right?

Note: When you update vimtex settings, please restart Vim/neovim.

**Comment by xarthurx** [comment]
I mean:
![image](https://user-images.githubusercontent.com/1921878/55756215-4354ea00-5a51-11e9-88e6-622bdd215d70.png)

So on my computer, after successful compilation, no file is copied out of the `build_dir`.
But when using `:VimtexView`, vim report the above command, and it seems will automatically copy the `pdf` and `synctex.gz` two files out into the project folder, and open the pdf accordingly.

**Comment by lervag** [comment]
I've tried to fix this, can you test latest version?

**Comment by xarthurx** [comment]
Thank you for this instant respond.

Got this during the compilation process:
![image](https://user-images.githubusercontent.com/1921878/55757592-a1cf9780-5a54-11e9-8e4a-26466e3d5b84.png)

The `:VimtexView` command works the same as my last comment.

**Comment by lervag** [comment]
Sorry, my mistake. Try again?

**Comment by xarthurx** [comment]
Yes, now it works.
1. pdf is open automatically.
2. The `file.pdf` inside `build_dir` got updated every time new changes are made.
3. The `file_vimtex.pdf` inside project folder cannot get updated.

Are `3` normal?
How about the pdf viewer open the pdf inside `build_dir` rather than the copied one?

Besides, may I ask why `file_vimtex.synctex.gz` also got copied out?

Sorry for so many questions.

**Comment by lervag** [comment]
No, 3 is not normal, `file_vimtex.pdf` is supposed to be updated according to the `g:vimtex_view_use_temp_files` setting (see help).

If you want to open the pdf inside the `build_dir`, then disable `g:vimtex_view_use_temp_files` (i.e., remove the option).

> Besides, may I ask why file_vimtex.synctex.gz also got copied out?

Of course. It is copied in order for backward and forward search to work, because this relies on synctex, and the synctex file must be present.

> Sorry for so many questions.

No problem! :)

**Comment by xarthurx** [comment]
Well, then I guess it is a bug?
When changing the text and `vimtex` auto compile and refresh the pdf, the pdf viewer **DO** pop-up and highlights the line I changed, but the text is not modified and remained the same.

The pdf in the `build_dir` is changed though.

I guess there's something wrong either with vimtex or sumatraPDF...

**Comment by lervag** [comment]
If so, please open a new issue to describe the problem in a reproducible manner, and please adhere to the issue template.
