### ISSUE TITLE
Parsing error with biblatex duplicate entries and unknown keys

### ISSUE THREAD

**Issue by dbacc** [lervag/vimtex#1357]
Okay, that's a very strange thing happening here. Consider the minvimrc

```vim
set nocompatible
call plug#begin('~/.local/share/nvim/plugged')
Plug 'lervag/vimtex'
call plug#end()
filetype plugin indent on
syntax enable

nnoremap q :qall!<cr>

let g:vimtex_view_automatic = 0

let g:matchup_override_vimtex = 1

let g:vimtex_view_general_viewer = 'zathura'
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_compiler_latexmk = {
			\ 'build_dir' : '../build',
			\}
let g:vimtex_quickfix_latexlog = {
			\ 'default' : 1,
			\ 'general' : 1,
			\ 'references' : 1,
			\ 'overfull' : 0,
			\ 'underfull' : 0,
			\ 'font' : 1,
			\ 'packages' : {
			\   'default' : 1,
			\   'general' : 1,
			\   'babel' : 1,
			\   'biblatex' : 1,
			\   'fixltx2e' : 1,
			\   'hyperref' : 1,
			\   'natbib' : 1,
			\   'scrreprt' : 1,
			\   'titlesec' : 1,
			\ },
			\}

let g:vimtex_toc_config = {'resize' : 1}
if has('nvim')
  let g:vimtex_compiler_progname = 'nvr'
endif
```

and following tex file

```tex
\documentclass[12pt]{article}
\usepackage[utf8]{inputenc}
\usepackage{biblatex}
\addbibresource{test2.bib}
\addbibresource{test.bib}
\begin{document}
This is a sample text. \cite{test}
\printbibliography

\end{document}
```

with identical `test.bib` and `test2.bib` given by

```bib
@misc{Nobody06,
  author = "Nobody Jr",
  title = "My Article",
  year = "2006"
}
```

Then, if starting nvim from outside the basepath  of the files with `nvim -u basepath/minivimrc basepath/minimal.tex`. I get the `vimtex: Something went wrong when parsing log files!` error.

The error disappears if inside the basepath or if I use an existing cite key, i.e. if I replace `\cite{text}` by `\cite{Nobody06}`.

**Comment by lervag** [comment]
First, some comments to your configuration:

```
" This is not necessary for the minimal example:
let g:matchup_override_vimtex = 1

" Why not rather set g:vimtex_view_method?
let g:vimtex_view_general_viewer = 'zathura'

" At the bottom, you set this with has('nvim'). That is safer if you also use
" regular Vim
let g:vimtex_compiler_progname = 'nvr'

" Just curious: Why go to parent dir here?
let g:vimtex_compiler_latexmk = {
      \ 'build_dir' : '../build',
      \}

let g:vimtex_quickfix_latexlog = {
      \ 'default' : 1,
      \ 'general' : 1,
      \ 'references' : 1,
      \ 'overfull' : 0,
      \ 'underfull' : 0,
      \ 'font' : 1,
      \ 'packages' : {
        \   'default' : 1,
        \   'general' : 1,
        \   'babel' : 1,
        \   'biblatex' : 1,
        \   'fixltx2e' : 1,
        \   'hyperref' : 1,
        \   'natbib' : 1,
        \   'scrreprt' : 1,
        \   'titlesec' : 1,
        \ },
      \}

let g:vimtex_toc_config = {'resize' : 1}

" Se earlier comment
if has('nvim')
  let g:vimtex_compiler_progname = 'nvr'
endif
```

**Comment by lervag** [comment]
I'll respond in more detail later.

**Comment by lervag** [comment]
I've fixed the error. Note, though, that when you start vimtex in this way, it becomes difficult to parse the log files properly, and the paths might be off. Perhaps I could fix it, but it seems difficult and I'd rather not, since it seems trivial to just open the tex file in the right directory.

**Comment by dbacc** [comment]
Sorry for my late reply.


> ```viml
> 
> " Why not rather set g:vimtex_view_method?
> let g:vimtex_view_general_viewer = 'zathura'
> ```
I do not really remember, I had some troubles getting backward search to work, maybe that's why.
> ```viml
> " Just curious: Why go to parent dir here?
> let g:vimtex_compiler_latexmk = {
>       \ 'build_dir' : '../build',
>       \}
> ```
Some of my projects not only contain tex files, for example I could have some code, that generates the figures. Then, my folder structure looks like
```
project/
           tex
           code
          figures
          build
```
and it feels more clean to have the build folder on the 'main' level.

>I've fixed the error. Note, though, that when you start vimtex in this way, it becomes difficult to parse the >log files properly, and the paths might be off. Perhaps I could fix it, but it seems difficult and I'd rather> >not, since it seems trivial to just open the tex file in the right directory.

Thanks a lot. Of course, that's trivial, but that's something one has to know.
Also, for me personally, that would be a bit cumbersome. I'm regularly using `fasd` (https://github.com/clvv/fasd) which allows me to open up my files with a simple `v partoftexfilename` no matter the current path.

**Comment by lervag** [comment]
Ok, I've tried to fix it. Please test newest version.
