### ISSUE TITLE
Remapping keys c and t with langmap introduces delays

### ISSUE THREAD

**Issue by OlivierNicole** [lervag/vimtex#1359]
## How to reproduce

Include the following in the `.vimrc`:
```vim
set langnoremap
set langmap=ctsrCTSRhjklHJKL;hjklHJKLctsrCTSR
```

Ensure Vimtex is installed and open a new `.tex` file.

## Expected behaviour

Keys C, T, S and R should behave like the movement keys H, J, K and L (respectively), and vice versa.

## Observed behaviour

Hitting key `t` will move down one line, but only after a delay. During this delay, `t` is printed in the status bar, as if waiting for the rest of a command. Same thing with key `c`. This makes it impractical to use C, T, S and R as movement keys.

This only happens when Vimtex is activated.

**Comment by lervag** [comment]
I can not reproduce this with the following minimal vimrc file:

```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

set langnoremap
set langmap=ctsrCTSRhjklHJKL;hjklHJKLctsrCTSR
```

This most likely means the problem is not with vimtex. Whats the output of `:map t` for you?

**Comment by OlivierNicole** [comment]
Oh, you're right, I get the same result with your minimal vimrc.

`:map t` gives:
```vim
x  tsD          @<Plug>(vimtex-delim-toggle-modifier-reverse)
n  tsD          @<Plug>(vimtex-delim-toggle-modifier-reverse)
x  tsd          @<Plug>(vimtex-delim-toggle-modifier)
n  tsd          @<Plug>(vimtex-delim-toggle-modifier)
n  tsc          @<Plug>(vimtex-cmd-toggle-star)
n  tse          @<Plug>(vimtex-env-toggle-star)
```

**Comment by lervag** [comment]
Are you able to create a minimal vimrc that introduces the lag as well?

Note: The lag is most likely due to mappings. That is, when you press `t`, if there is a map like `tsd`, then Vim waits for more input according to your `timeout` setting. See `:help timeout` for more info.

**Comment by OlivierNicole** [comment]
It seems that the problem comes from an interaction between vimtex and neomake. Here is the minimal vimrc to trigger this behaviour, assuming you have current-version neomake files installed in the given directory:
```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
let &runtimepath  = '~/.vim/bundle/neomake,' . &runtimepath
filetype plugin indent on
syntax enable

set langnoremap
set langmap=ctsrCTSRhjklHJKL;hjklHJKLctsrCTSR
```

**Comment by lervag** [comment]
When `neomake` is installed and included, what's the output of `:map t` then?

**Comment by OlivierNicole** [comment]
Same as before, nothing else than vimtex's mappings:
```vim
x  tsD          @<Plug>(vimtex-delim-toggle-modifier-reverse)
n  tsD          @<Plug>(vimtex-delim-toggle-modifier-reverse)
x  tsd          @<Plug>(vimtex-delim-toggle-modifier)
n  tsd          @<Plug>(vimtex-delim-toggle-modifier)
n  tsc          @<Plug>(vimtex-cmd-toggle-star)
n  tse          @<Plug>(vimtex-env-toggle-star) 
```

**Comment by lervag** [comment]
Ok. For me, it still works. I did this:

0. Created `~/test` with minimal files `test.tex` and `test.vim`
1. `git clone https://github.com/neomake/neomake ~/test/neomake`
2. Include `let &runtimepath  = '~/test/neomake,' . &runtimepath` in `test.vim` similar to your updated minimal vimrc file
3. Run `nvim -u test.vim test.tex`

This still works as expected. After the langmap, `jkd` will do what was originally `tsd`, i.e. toggle delimiteres like `$(...)$` -> `$\left(...\right)$.

**Comment by OlivierNicole** [comment]
I did everything you did, except I use Vim and not Neovim. I still get my bug. Also, I'm using whichever version of vimtex is installed by vim-plug (the one on master, I assume).
I'll install Neovim a bit later to see if it is indeed free of this bug.

**Comment by lervag** [comment]
Ah, that's it. With Vim I also reproduce this issue. And I can reproduce the issue without vimtex, so it is not an issue with vimtex. Please open an issue at neomake.

Minimal vimrc file:

```vim
set nocompatible
let &runtimepath  = '/path/to/neomake,' . &runtimepath
filetype plugin indent on
syntax enable

nnoremap tsd :echo 'test'<cr>

set langnoremap
set langmap=ctsrCTSRhjklHJKL;hjklHJKLctsrCTSR
```
