### ISSUE TITLE
Main file detection fails when compiling from a file in a directory containing a separate preamble file

### ISSUE THREAD

**Issue by TheDelus** [lervag/vimtex#1360]
As the title suggests, this issue is quite similar to #1323. I have a scenario where I want to put all my custom commands and packages into an own file, called `preamble.tex`, located in a sub-directory under the root, called `header`.
When I put  the `TEX root` directive in the `preamble.tex` file I can compile from this file just fine (thanks to the fix e7b0f2f). But when I put another file in the directory `header`, say `meta.tex`, and I try to compile from this file it will fail just as described in #1323. 

### Steps to Reproduce

1. Create the following project structure:

```
path/main.tex
path/header/preamble.tex
path/header/meta.tex
```

with 

#### main.tex
```
\input{preamble.tex}

\begin{document}
  Hello world this is \me!
\end{document}
```

#### preamble.tex
```
%! TEX root = ../main.tex

\documentclass[a4paper]{article}
\usepackage{amsmath}

\input{meta}
```

#### meta.tex
```
%! TEX root = ../main.tex

\newcommand{\me}{John}
```

2. Compile the project from file `meta.tex`. An error will be reported which indicates, that the compiler uses `header.tex` as main file.

**Comment by lervag** [comment]
I think your `\input`s are wrong. They need to be relative to the main file, i.e., `\input{header/preamble}` and `\input{header/meta}`. When I update accordingly, everything works as expected for me.

Note: `\input`s are always relative to the path of the main document.

**Comment by TheDelus** [comment]
I´m sorry you are completely right. My bad.

**Comment by lervag** [comment]
No problem :)
