### ISSUE TITLE
Buffer modified by :VimtexCompile and :VimtexCompileSS

### ISSUE THREAD

**Issue by msuperdock** [lervag/vimtex#1363]
## Summary

- When I run `:VimtexCompile`, all works correctly, except that the character under the cursor is replaced with a lowercase `r` after compilation is completed (as though `rr` was typed).
- When I run `:VimtexCompileSS`, all works correctly, except that vim enters single-character replace mode after compilation is completed (as though `r` was typed).

Relevant details are:
- Using nvim v. 0.3.1.
- Using current version of vimtex. (Installed through vim-plug since last master update.)

The minimal configuration that seems to cause the issue is:

```
let g:vimtex_view_automatic = 0
let g:vimtex_view_method = 'mupdf'
```

Neither configuration option on its own causes the issue, but together I get the behavior described above consistently.

## Minimal example

(Note: I am also setting `g:vimtex_syntax_enabled = 0`, because otherwise I get an error `Unknown function: TexNewMathZone`, which I suspect is because I use my own custom syntax file for LaTeX. I do not think this setting has anything to do with the error I'm describing.)

```
" minivimrc
set nocompatible
let &runtimepath  = '~/.config/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.config/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable

nnoremap q :qall!<cr>

let g:vimtex_syntax_enabled = 0
let g:vimtex_view_automatic = 0
let g:vimtex_view_method = 'mupdf'

silent edit main.tex
```

```
% main.tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

Start nvim with: `nvim -u minivimrc main.tex`.

Then type: `:VimtexCompile<cr>` or `:VimtexCompileSS<cr>`.

### Actual behavior

The document compiles, but in each case, the buffer is modified strangely:

- For `:VimtexCompile`, the character under the cursor is replaced with `r`.
- For `:VimtexCompileSS`, vim enters single-character replace mode.

## Output from VimtexInfo

Running `:VimtexInfo` upon opening `main.tex` gives:

```
System info
  OS: Linux 4.14.110
  Vim version: NVIM v0.3.1
  Has clientserver: true
  Servername: /tmp/nvimjxZAjq/0

vimtex project: main
  base: main.tex
  root: /home/matt/Downloads
  tex: /home/matt/Downloads/main.tex
  out: /home/matt/Downloads/main.pdf
  log: /home/matt/Downloads/main.log
  aux: /home/matt/Downloads/main.aux
  fls: /home/matt/Downloads/main.fls
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimjxZAjq/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: MuPDF
    xwin id: 0
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
  document class: minimal
```

After running `:VimtexCompile` and getting the error described above, running `:VimtexInfo` again gives the following error:

```
Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..181
line 4:
E37: No write since last change (add ! to override)
```

## Output from VimtexCompileOutput

After compiling with `:VimtexCompile`, running `:VimtexCompileOutput` gives the following:

```
Latexmk: This is Latexmk, John Collins, 7 August 2018, version: 4.59.
Not using a previewer
------------
Running 'echo vimtex_compiler_callback_success'
------------
Latexmk: All targets (main.pdf) are up-to-date
vimtex_compiler_callback_success
```

## Progress toward a solution

Tracing through some of the code, I found a call to `b:vimtex.compiler.exec()`. Calling this function directly with `call b:vimtex.compiler.exec()` produced the same result as `:VimtexCompileSS`. My guess is that `b:vimtex.compiler.exec()` is producing a normal-mode `r` keypress, and this happens once within `:VimtexCompileSS` and twice within `:VimtexCompile`.

**Comment by lervag** [comment]
I believe it has to do with the callback for MuPDF. Are you proficient enough with vimscript to assist with the debugging? If so, then you should start to look in `autoload/vimtex/view/common.vim` in the function `s:xwin_template.xwin_send_keys`. E.g., add the line `unsilent echom cmd` before the `silent call` line and inspect the output.

My initial thought is that there is a problem with `xdotool` on your system.

Can you check the output of `:checkhealth vimtex`?

**Comment by msuperdock** [comment]
Yes, happy to help! I added `unsilent echom cmd` exactly where you said, and got the following output:

```
xdotool key --window 0 r
xdotool key --window 0 r
```

Adding more `echom` statements reveal that `self.xwin_id` is 0 and `a:keys` is 'r'. I assume this is not the expected behavior, but am not sure, and I don't see immediately how to debug further.

I ran `:checkhealth vimtex` and got two warnings, one about `pstree` and the other about changing my compiler setting to `nvr`. (It had previously been set by default to the path to `nvim`.) I did change my compiler setting to `nvr`, which got rid of that warning, but did not fix the error I'm having. Here's my new `minivimrc`. (The only change is the compiler setting.)

```
" minivimrc
set nocompatible
let &runtimepath  = '~/.config/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.config/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable

nnoremap q :qall!<cr>

let g:vimtex_syntax_enabled = 0
let g:vimtex_view_automatic = 0
let g:vimtex_view_method = 'mupdf'
let g:vimtex_compiler_progname = 'nvr'

silent edit main.tex
```

Here's the output of `:checkhealth vimtex` after changing the compiler setting to `nvr`:

```
health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - OK: MuPDF should work properly!
  - WARNING: pstree is not available
    - ADVICE:
      - vimtex#view#reverse_goto is better if pstree is available.
  - OK: Compiler should work!
```

**Comment by lervag** [comment]
Ok, so, it seems we are not able to detect the proper xwin ID. This explains your issue.

Can you give some more details on your system? Which Linux distribution, which window manager, etc. Are you on Wayland?

Can you open a pdf with mupdf from a terminal, then do `xdotool search --class MuPDF`, report the output?

**Comment by msuperdock** [comment]
With this I was able to fix the issue!

You were right, `xdotool search --class MuPDF` gave no output. Running `xprop WM_CLASS` and clicking on a MuPDF window showed that the attribute does not exist. My distribution is NixOS, my window manager is xmonad, and I am not using wayland.

The issue has to do with NixOS; the `mupdf` package on NixOS provides two binaries, `mupdf-gl` and `mupdf-x11`, but no binary called `mupdf`. Initially this caused vimtex's viewing functionality not to work with mupdf, since it looks for a `mupdf` binary and doesn't find it, but after reading other issues I fixed that problem by creating a `mupdf` symlink to `mupdf-gl`. This was not the right choice, because as is documented elsewhere, `mupdf-gl` does not set WM_CLASS, which led to the issue I reported here. So I changed the symlink to `mupdf-x11`, and now the issue I originally reported is not happening anymore.

This isn't mainly vimtex's problem, but if you wanted to help others avoid this sort of issue, perhaps a solution would be to catch situations where `xdotool search --class MuPDF` gives no output, i.e. situations where `self.xwin_id` is 0, and output an error instead of calling xdotool.

If anyone using NixOS stumbles upon this and wants to know how to fix the issue locally, here is part of my `configuration.nix`:

```
  nixpkgs.config = {
    packageOverrides = pkgs: {
      # Make mupdf accessible via `mupdf` rather than `mupdf-x11`.
      mupdf = pkgs.mupdf.overrideDerivation (old: {
        postInstall = old.postInstall + ''
          ln -s $bin/bin/mupdf-x11 $bin/bin/mupdf
        '';
      });
    };
  };
```

**Comment by lervag** [comment]
Great, happy to hear you've solved the issue. I think this warrants a minor change in vimtex in that we should not try to pass keys when the xwin_id is not properly set.
