### ISSUE TITLE
Two okular instances on first :VimtexCompile (despite --unique)

### ISSUE THREAD

**Issue by stloewen** [lervag/vimtex#1364]
I'm not sure whether this counts as a bug in vimtex or in okular or whether it counts as a bug at all, but it could certainly be worked around in vimtex.

## Observed behavior:

With arbitrary *.tex files the first call of `:VimtexCompile` causes okular to be lauched twice.
The second instance has a popup saying "There is already a unique Okular instance running. This instance won't be the unique one."

`.vimrc` contains:
```vim
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--noraise --unique @pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
```

I don't know how the `--unique` tries to ensure uniqueness but the issue seems to be that two okular instances are called too fast for `--unique` to work.
Same behavior can be seen with:

```bash
#!/bin/bash
okular --unique build/test.pdf &
okular --unique build/test.pdf &
```

Introducing a slight delay between both okular launches gets rid of the problem.

## Workaround:
My current workaround is:

Put `okular-delayed` onto PATH:
```bash
#!/bin/bash
ARGS=$@
if [ "$1" == "--delayed" ]
then
    sleep 0.5
    # Filter out the --delayed
    ARGS=${@:2}
fi
okular $ARGS
```

Change `.vimrc` to use it:
```vim
let g:vimtex_view_general_viewer = 'okular-delayed'
let g:vimtex_view_general_options = '--noraise --unique @pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--delayed --unique'
```

## Further information
Okular Version 1.6.3

**Comment by lervag** [comment]
Can you specify a full minimal example to reproduce it?

**Comment by stloewen** [comment]
Sure.

```vim
" .vimrc
call plug#begin('~/.vim/plugged') # using vim-plug
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--noraise --unique @pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
```
```latex
% test.tex
\documentclass{minimal}
\begin{document}
test
\end{document}
```
No `.latexmkrc`
Then run `vim test.tex` and `:VimtexCompile`.

**Comment by lervag** [comment]
I think this was caused by a recent change that was probably not quite correct, cf. #1355 and #1362. I've fixed it, I think, without causing regression problems for the mentioned issues.
