### ISSUE TITLE
Error detected while processing function vimtex#init..<SNR>28_init_highlights..vimtex#log#warning..1:

### ISSUE THREAD

**Issue by fgq1992** [lervag/vimtex#1365]
The tex file is: 
![tex](https://user-images.githubusercontent.com/17982375/56339995-fd331f80-61e2-11e9-9d49-12c775648741.png)

And my vimrc is: 
![tex_config](https://user-images.githubusercontent.com/17982375/56340778-86e3ec80-61e5-11e9-814e-655f9b8e0dbe.png)

Every time when I open the tex file, the error will occur: 
![error log](https://user-images.githubusercontent.com/17982375/56340512-b21a0c00-61e4-11e9-941a-d70f05e102b3.png)
Does any one know how to solve this problem? Thank you

**Comment by lervag** [comment]
I think this problem might already be solved. Can you make sure you are on the latest version of vimtex?

**Comment by lervag** [comment]
I found a minor bug that might have been your problem.

**Comment by itsShnik** [comment]
Thanks for the quick response and the fix. I would like to know what was the bug and how did you fix it?
