### ISSUE TITLE
Is it possible to use vimtex in ubuntu subsystem (in windows 10) with some pdf reader ?

### ISSUE THREAD

**Issue by ViOrise** [lervag/vimtex#1367]
Hi, I use vim in windows 10 (vim in subsystem ubuntu). Can I use vimtex to compile my tex file and see it in some pdf reader?

Edit (by @lervag): The attached image is not relevant; removed to make the question more concise.
```
![изображение](https://user-images.githubusercontent.com/41738895/56679858-b061b400-66ce-11e9-9f3a-d296ba1ffb1c.png)
```

**Comment by lervag** [comment]
Hi @ViOrise. Your attached screenshot is not relevant, so I "commented" it out.

> Can I use vimtex to compile my tex file and see it in some pdf reader?

Yes, in principle. I don't use Windows myself, and so I am not able to help. There are some sections in the documentations that might be relevant. See `:help vimtex-faq-windows` for some general tips and `:help vimtex_viewer_sumatrapdf` for info on SumatraPDF, a popular PDF viewer on Windows that should work well with vimtex.
