### ISSUE TITLE
reflowing a paragraph that ends with equation

### ISSUE THREAD

**Issue by nchopin** [lervag/vimtex#1370]
Hi, 

Have been using (and loving) vimtex for some time, however there is one thing I can't figure out.

Consider this piece of tex:

> We have some math below:                                                                         
> \begin{equation}                                                                                 
>      2 + 3                                                                                        
> \end{equation} 

If I press gqip on the first line, I get this: 

> We have some math below: \begin{equation} 2 + 3  \end{equation}

If I understand correctly closed issue #436, gq should **not** reflow the equation. On the other hand, the current documentation does not seem to say anything about "protecting" environments when pressing gq; the only thing I could find in the doc is the bit about variable `vimtex_format_enabled`, and how it may be used to deal with "comments at end of lines". 

So which one is right? Is is possible already to "protect" environments from reformatting? then how? 

I'm using the current version of vimtex (updated today), on neovim 0.2.2 and Ubuntu 18.04 LTS. 

Many thanks for your help in advance (and generally for developing vimtex). 
Nicolas

**Comment by lervag** [comment]
Ah, yes. Sorry. The documentation should be improved on this point. I recommend that you read the section on formatting in `:help vimtex-non-features`. Vimtex does support what you ask, but only as a slightly improved version of the standard Vim formatting. To enable it, you must add

```vim
let g:vimtex_format_enabled = 1
```

in your `.vimrc` file. I'll update the docs asap.

**Comment by nchopin** [comment]
Thanks for your prompt reply, now that I added this to my dotfile, things work as expected. 

The section on formatting in `:h vimtex-non-features` is precisely the part of the doc I was referring to. :-) Yes, it'd be great if more details could be added. 

Speaking of which, it would be great if this documentation would also be available as a html file on-line (especially for newcomers who want to know what the package does before installing).

**Comment by lervag** [comment]
> The section on formatting in :h vimtex-non-features is precisely the part of the doc I was referring to. :-) Yes, it'd be great if more details could be added.

I've already updated the docs. Feel free to suggest further changes.

> Speaking of which, it would be great if this documentation would also be available as a html file on-line (especially for newcomers who want to know what the package does before installing).

I don't know how to do that. I will gladly accept help for this, though, if someone knows how and can help me to get something like that up and running. I would need to convert from Vim doc to HTML and then to somehow present it at some location on the web. This is not my field of expertise, so, as said, I would need some help.
