### ISSUE TITLE
Citation Completion not working with BibLaTeX

### ISSUE THREAD

**Issue by AnthonyWharton** [lervag/vimtex#1373]
I am currently writing a document that makes use of my own class file. Initially I was not using any extra package for citations - which to the best of my knowledge means it was running with just basic BibTex. In this setup, everything wass fine; completion and auto-completion both work absolutely fine with the `ycm_semantic_trigger` set up as described the documentation. I've been loving completion this far!

However now I have added BibLaTeX and citation completion has stopped working to my disappointment, however I should add that other completions such as referencing labels _still works_, leading me to believe there must be some configuration setting missing, or something is incompatible.

With the debugging I have done so far, below are the minimum things I can change for it to stop working - in essence it's the minimum I can do to change from the default BibTex setup to BibLaTeX as far as I'm aware: 

Added to `.cls`:
```tex
\RequirePackage{biblatex}
\addbibresource{book.bib}
```

Removed from `.cls`:
```tex
\bibliographystyle{plain}
```

Added to main `.tex`:
```tex
\printbibliography
```

Removed from main `.tex`:
```tex
\bibliography{book}
```
---

So far I have tried the following to no avail:

 - Tried to see if it was the fact BibLaTeX was using the `biber` backend vs the `bibtex` backend
 - Tried to see if was the an issue with new citations I had added since my last working configuration
 - I also saw #142 and tried some of the suggestions there such as recursive bib options (although in the new configuration syntax), and also tried the simple bib mode

I'm not super knowledgeable in this area so I will admit these were some blind stabs in the dark, so excuse me if any of the above trains of thought make absolutely no sense!

---

Unfortunately I need to dash off somewhere so I will have to follow up with a minimal example for you to reproduce, but I though I should quickly throw an issue together in case I am missing something simple, and so I don't forge to later!

For now here is my `.vimrc` configuration:

```
let g:tex_flavor = 'latex'
let g:vimtex_compiler_latexmk = {
    \ 'backend' : 'process',
    \ 'background' : 1,
    \ 'build_dir' : 'latexmk-files',
    \ 'callback' : 1,
    \ 'continuous' : 1,
    \ 'executable' : 'latexmk',
    \ 'options' : [
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}
let g:vimtex_view_general_viewer = 'zathura'
let g:vimtex_view_method = 'zathura'
let g:vimtex_view_general_options =
	\ ' -x "vim --servername=vim --remote +%{line} %{input}"'
```

And relevant lines from my `.cls` file:

```tex
\LoadClass[10pt,a4paper,twoside]{book}
\RequirePackage{biblatex}
\addbibresource{book.bib}
```

With a call to `\printbibliography` at the end of my document. Other details that may be of note is that my document is comprised of multiple tex files, and all the build files are set to be put in a `build_dir` called `latexmk-files` as per the `.vimrc` config above.

I'll try get a minimal example added here in the next day or two, but hopefully that is enough to get started with - thanks in advance!

**Comment by lervag** [comment]
I can't help until I have a fully reproducible example. I'll try and help based on your input. Can you check if the following minimal LaTeX sample still reproduces the problem?

```tex
% File: mwe.tex
\documentclass[10pt,a4paper,twoside]{book}
\usepackage{biblatex}
\addbibresource{book.bib}

\begin{document}

\chapter{1}
Lorem ipsum ...
\autocite{...}

\chapter{2}
Lorem ipsum ...

\printbibliography

\end{document}
```

And the following minimal vimrc file:

```vim
" File: minivimrc.vim
set nocompatible

" This loads vimtex
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Add path to youcompleteme here, and possibly more if necessary to load it
let &rtp = YOUCOMPLETEME

filetype plugin indent on
syntax enable

let g:tex_flavor = 'latex'

" You only need to specify changes from default value
" Note: Why do you insist on the process backend?
let g:vimtex_compiler_latexmk = {
    \ 'backend' : 'process',
    \ 'build_dir' : 'latexmk-files',
    \}

" If you set this, then you don't need to set the general viewer
let g:vimtex_view_method = 'zathura'

" Add settings for youcompleteme here!

" Only for convenience when testing
nnoremap q :qall!<cr>
```

With this, and your `book.bib` file in the same folder, you should be able to test with `vim --servername VIM -u minivimrc mwe.tex`.

**Comment by AnthonyWharton** [comment]
Hi, thanks for the quick response - you got here before I managed to get a working example up and running!  I did say I'd have one made for you in a few days when I got some time, and as promised I have managed to get this sorted now - please find it below.

A quick note beforehand. Now that I've tested it a bit, it seems like having `\addbibresource{test.bib}` in the `cls` file as opposed to the main `tex` file is what causes the issue. Presumably you're not parsing it from a `cls` file, or something to that extent? (I am not familiar with the codebase for this plugin so I can't really offer any more than that, sorry!)

----

### minivimrc
```vim
set nocompatible

let &rtp  = '~/.vim/vim-plug-plugins/vimtex,' . &rtp
let &rtp .= ',~/.vim/vim-plug-plugins/vimtex/after'
let &rtp .= ',~/.vim/vim-plug-plugins/YouCompleteMe/'

filetype plugin indent on
syntax enable

"" Add YCM VimTex integration
if !exists('g:ycm_semantic_triggers')
  let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers.tex = g:vimtex#re#youcompleteme

"" Vimtex Configuration
let g:tex_flavor = 'latex'
let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : 'latexmk-files',
    \}

let g:vimtex_view_method = 'zathura'

" Only for convenience when testing
nnoremap q :qall!<cr>
```

### test.tex
```tex
\documentclass{test}

\begin{document}
\chapter{The Beginning}

Hello world \cite{Nobody06}

\printbibliography[heading=none]
\end{document}
```
**When moving `\addbibresource{test.bib}` to just before `\begin{document}` in `test.tex`, it all works properly.**

### test.cls
```tex
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{test}[2019/04/30, Anthony Wharton <a.wharton.2015@bristol.ac.uk]

\LoadClass[10pt,a4paper,twoside]{book}

\RequirePackage[backend=biber,defernumbers=true]{biblatex}

\addbibresource{test.bib}
```

### test.bib
```
@misc{Nobody89,
      author = "Nobody Sr",
      title = "Good Show!",
      year = "1989"
}

@misc{Nobody06,
      author = "Nobody Jr",
      title = "Show: What we've learnt over 17 years",
      year = "2006"
}

@misc{Somebody08,
      author = "Somebody",
      title = "Mysterious Work",
      year = "2008"
}
```

----

Finally, in response to your note. I only had `'backend' : 'process'` as this was a boilerplate copy-paste from a colleague of mine, I'm still in the process of exploring all the options in Vimtex and streamlining my configuration!

**Comment by AnthonyWharton** [comment]
I couldn't help myself and did a bit of digging. Although I'm not that well versed in vimscript it looks like the issue might be [here](https://github.com/lervag/vimtex/blob/2e1687bd66c58fc37d47447c411f89895d8db4cd//autoload/vimtex/complete.vim#L255)!

Afraid I am probably not qualified enough to add a fix (or at least one that is programmed nicely), so for now I will move where my `bib` file is included and either leave you to fix this or add an explicit note to the documentation to say that bib includes must be in `.tex` files.

**Comment by lervag** [comment]
> A quick note beforehand. Now that I've tested it a bit, it seems like having `\addbibresource{test.bib}` in the cls file as opposed to the main tex file is what causes the issue. Presumably you're not parsing it from a cls file, or something to that extent? (I am not familiar with the codebase for this plugin so I can't really offer any more than that, sorry!)

Ah, yes. That would explain it. And in this particular case, I am very skeptical of "fixing" this. It does not quite feel right that the `\addbibresource` should be part of your custom class, as the point of a class is to specify your document template, not it's main content. Further, you also seem to be inconsistent in that you included the bibliography file from the `.tex` file with `\bibliography`, but when changing to BibLaTeX you move the corresponding `\addbibresource` into your `.cls` file. As such, I can guess that you will not feel to bad to move it back into your `.tex` file?

> Finally, in response to your note. I only had 'backend' : 'process' as this was a boilerplate copy-paste from a colleague of mine, I'm still in the process of exploring all the options in Vimtex and streamlining my configuration!

No problem. There's a lot to learn. I can only recommend that you spend some time reading the documentation, although I also easily see that the size of the docs has become quite daunting for reading in full.

> I couldn't help myself and did a bit of digging...

That's the best way to learn. Good work. And you are quite right, this is where the bibliography files are collected, and your observation is correct in that only `.tex` files are parsed. If I were to parse the `.cls` and `.sty` (package) files as well I am afraid it would start to become (more) inefficient.

**Comment by AnthonyWharton** [comment]
> Further, you also seem to be inconsistent in that you included the bibliography file from the .tex file with \bibliography, but when changing to BibLaTeX you move the corresponding \addbibresource into your .cls file. 

So for some context; the original style file is a University provided thesis template (I'm working on my Masters Thesis!). I've been slowly customising it to my needs and generally been putting package options in the `cls` file, as most of the other options were there. In this case, I set up the BibLaTeX settings in the `cls` file whilst going through the BibLaTeX docs, and then returned to the `tex` file and merely switched out the `\bibliography` line with `\printbibliography` and left it at that. Now the inconsistency seems a bit obvious, but I thought nothing of it at the time!

>As such, I can guess that you will not feel to bad to move it back into your .tex file?

Yes that's absolutely fine, I've moved it now and it's all good!

> I can only recommend that you spend some time reading the documentation, although I also easily see that the size of the docs has become quite daunting for reading in full.

I've spent a bit of time reading through it over the last few days (and before posting this issue!) and have started optimising some of the configs as of making the mini `vimrc` above. As you say though, there's a lot of content there and unfortunately I am focussing on the writing at the moment, but I'll get some more time to look into things properly in the future.

Not wanting to add to the problem but perhaps some sort of note mentioning that bibliographies are only parsed from tex files in the docs FAQ/around the citation completion section might be useful? However I understand if you think this is unecessary, as there was a strange course of events to lead to me in this state!

> That's the best way to learn. Good work. And you are quite right, this is where the bibliography files are collected, and your observation is correct in that only .tex files are parsed. If I were to parse the .cls and .sty (package) files as well I am afraid it would start to become (more) inefficient.

Thanks! Makes sense to keep it as it is.

Cheers for all the help, Anthony.

**Comment by lervag** [comment]
> Not wanting to add to the problem but perhaps some sort of note mentioning that bibliographies are only parsed from tex files in the docs FAQ/around the citation completion section might be useful? However I understand if you think this is unecessary, as there was a strange course of events to lead to me in this state!

Nah, as mentioned, the docs are already very full. I don't mind adding things when it feels necessary, but I think this is a litle bit too uncommon.

In any case, I'm happy to help. Feel free to open new issues/feature requests :)
