### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by juliankrieger** [lervag/vimtex#1376]
Latex commands are defined like this

`\newcommand{\newcommandname}[Number of Arguments]`

Is it possible to add a variable number of braces when completing a command, for example make
\begin complete to `\begin{}`?

I would be willing to look into it, but I'd love a suggestion on where to start.

**Comment by lervag** [comment]
Sorry, no. Please read `:help vimtex-non-features`, and in particular the section on snippets, then `:help vimtex-UltiSnips` and `:help vimtex-neosnippet`. These are general purpose snippet tools that works for multiple languages and that solves your requested feature on a more general level.
