### ISSUE TITLE
Some characters have background in concealed lines

### ISSUE THREAD

**Issue by JohnEdChristensen** [lervag/vimtex#1377]
Terminal Emulator: Termite

Special characters in concealed lines have a background as shown here: 
![Screenshot_2019-05-01_16-52-01](https://user-images.githubusercontent.com/29576860/57048511-7b56e380-6c31-11e9-8c2f-fb0105ba7994.png)
This behavior does go away with some vim themes, but is showing up with the default vim color scheme.
The text in the picture:
```
\documentclass[12pt]{article} 
\begin{document} 
\[ 
a \in A 
a = \bigcap_{i \in I} A_i 
.\] 
\end{document} 
```
my .vimrc
```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'
call plug#end()
```

Is this a bug or am I missing something?

**Comment by lervag** [comment]
I think this must be a bug, or at least something that is not directly related to vimtex. I am sorry to say that I do not immediately recognize the issue.

Did you read `:help conceallevel`? It says:

```
	Value		Effect ~
	0		Text is shown normally
	1		Each block of concealed text is replaced with one
			character.  If the syntax item does not have a custom
			replacement character defined (see |:syn-cchar|) the
			character defined in 'listchars' is used.
			It is highlighted with the "Conceal" highlight group.
```

I think you might alleviate the issue by setting the `Conceal` highlight group, e.g. something like this:

```vim
high Conceal guibg=none ctermbg=none
```

Note, though, that customizing your colorscheme should be done correctly. See e.g. http://andrewradev.com/2011/08/06/making-vim-pretty-with-custom-colors/.
