### ISSUE TITLE
Enable continuous compilation on background

### ISSUE THREAD

**Issue by hwangdylan** [lervag/vimtex#1379]
I have been using Skim as the PDF viewer and when I am in continuous compilation mode, after each change and save, Vimtex will compile the file and when it is done, it will bring Skim to the front. How do I prevent that from happening? When I just use the normal "latexmk -pdf -pvc main.tex" it will compile the file and then it will update the pdf file but it will not bring the pdf to the front of the screen.

I have tried setting ` let g:vimtex_view_enabled=1` which will prevent the viewer from constantly popping back up, but then I am unable to use `forwardsearch` which i rely on pretty heavily. I have also tried setting `let g:vimtex_view_automatic=0` which has not worked. 

VimtexInfo file output:
```
System info
  OS: Mac OS X 10.14.3 (1234)
  Vim version: VIM 8.1 (1-1100)
  Has clientserver: false

vimtex project: main
  base: main.tex
  root: /Users/path
  tex: /Users/path
  out: /Users/path
  log: /Users/path
  aux: /Users/path
  fls: /Users/path
  compiler: latexmk
    backend: jobs
    output: /var/folders/8d/sbkcmqkd64343pf67yw0000gn/T/vXVaLYp/2
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: process 443483 run
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'main.tex'
  viewer: Skim
    process: 
      pid: -
      cmd: osascript -e 'set theFile to POSIX file "path/main.pdf"' -e 'set thePath to POSIX path of (theFile as alias)' -e 'tell application "Skim"' -e 'try' -e 'set theDocs to get documents whose path is thePath' -e 'if (count of theDocs) > 0 then revert theDocs' -e 'end try' -e 'open theFile' -e 'end tell' >/dev/null 2>&1 &
  qf: LaTeX logfile
    config: 
      overfull: 0
      fix_paths: 1
      packages: 
        default: 0
      underfull: 0
      default: 1
  document class: extarticle
  packages:

```

**Comment by lervag** [comment]
In general, it should suffice to set `g:vimtex_view_method = 'Skim'`. If you add `g:vimtex_view_automatic = 0`, then the viewer should not be started automatically, but instead opened after your first invocation of `\lv` / `:VimtexView`.

The issue that the viewer is brought to focus after each compilation is unknown to me. Unfortunately, I don't use Skim or OSX. As such, I hope perhaps @clason, @msiniscalchi (cf. #1260), or someone else might be able to help here?

**Comment by lervag** [comment]
See also #1177 and #1178. Perhaps @znculee might also be able to help.

**Comment by znculee** [comment]
Here is my minimum config for vimtex related to your issue, and this should solve your problem.
```
let g:tex_flavor='latex'
let g:vimtex_compiler_method='latexmk'
let g:vimtex_view_method='skim'
let g:vimtex_view_skim_activate=1
```
And this is the full version.
```
let g:tex_flavor='latex'
let g:vimtex_compiler_method='latexmk'
let g:vimtex_compiler_latexmk={'build_dir': 'build'}
au VimEnter * let g:ycm_semantic_triggers.tex=g:vimtex#re#youcompleteme
let g:vimtex_quickfix_open_on_warning=0
let g:vimtex_quickfix_latexlog={
  \ 'overfull': 0,
  \ 'underfull': 0,
  \ 'packages': {'default': 0}
  \ }
let g:vimtex_toc_config={
  \ 'split_pos': 'full',
  \ 'layer_status': {'content': 1,'label': 0,'todo': 0,'include': 0},
  \ 'show_help': 0
  \ }
let g:vimtex_view_method='skim'
let g:vimtex_view_skim_activate=1
let g:vimtex_view_skim_reading_bar=0
```
For my up-to-date .vimrc, please refer to [this link](https://raw.githubusercontent.com/znculee/dotfiles/master/vim/.vimrc).

**Comment by clason** [comment]
I think this is actually a bug (or intended change) in Skim: The compilation callback (as opposed to the `\lv` function) should _not_ bring the window to the foreground. You can test this yourself with the `displayline` script distributed with Skim: in the current version, the document is brought to the foreground regardless whether the option `-b` for background is provided. So I don't think this is a vimtex issue and should be raised at the [Skim bug tracker](https://sourceforge.net/p/skim-app/bugs/).

**Comment by lervag** [comment]
Thanks, @znculee and @clason, for pitching in! @hwangdylan I hope this helps! In particular, it seems @clason may be right that this is due to a bug in Skim, and so I'll take the liberty of closing here. Feel free to reopen, and of course, continue the discussion. I'll also keep my eyes on this and help if possible!
