### ISSUE TITLE
exclude main file preamble inputs from TOC

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#138]
`\input{file.tex}` before `\begin{document}` neither adds labels nor entries to the TOC and therefore `VimtexTOC/Labels` should skip `file.tex`; the more so since `file.tex` could be in the local TexMF tree (by default in `~/texmf` on TeXLive under Linux).

**Comment by lervag** [comment]
Agreed, and thanks for noticing.

**Comment by Konfekt** [comment]
:+1:  :+1: !
