### ISSUE TITLE
Errors while editing file to be used in \input{}

### ISSUE THREAD

**Issue by tribly** [lervag/vimtex#1383]
I have a main document `script.tex` and a file to be input into that document `a.tex`.

```tex
\begin{document}
\input{a.tex}
\end{document}
```
When editing the `a.tex` and saving it the quickfix windows shows me (with active compilation)
```
Undefined control sequence. \section
Undefined control sequence. \subsection
LaTeX Error: Missing \begin{document}.
```

Is there a way to fix this?

**Comment by ryleelyman** [comment]
To me this sounds like it's working as expected? `a.tex` itself doesn't need to be compiled, the `script.tex` file does, so just disable compiling while editing `a.tex`?

**Comment by lervag** [comment]
The reason is simply that vimtex can not find a suitable main file for `a.tex`, and it falls back to setting `a.tex` to the main file.

If you try to compile `script.tex` you should see it will also fail, because it is not a proper LaTeX file. You should add `\documentclass` to the top.

**Comment by lervag** [comment]
If you change `script.tex` to something like this, then things should work:

```tex
\documentclass{article}
\begin{document}
\input{a.tex}
\end{document}
```

**Comment by tribly** [comment]
Sorry, my example was missing the documentclass. My actual code has it of course.

Is there any way to tell vimtex what the main file is? Always switching to the main file and compiling or having the quickfix window is not really the way I want to go. Nor is disabling the compilation.

**Comment by lervag** [comment]
> Sorry, my example was missing the documentclass. My actual code has it of course.

Well, if I am to help, you must show me your actual code (but please, simplify it to create a minimal example similar to the one you posted originally).

E.g., given these files:
```tex
% script.tex
\documentclass{minimal}
\begin{document}

\input{a.tex}

\end{document}

% a.tex
Hello World.
```

If I now open `a.tex` and start compilation with `\ll`, it will compile correctly. Thus I believe your example must differ from this somehow.

**Comment by lervag** [comment]
> Is there any way to tell vimtex what the main file is?

Yes, but you should not really need it in most cases. That is, it should autodetect the main file. You can see `:help vimtex-multi-file` for how vimtex works with multi file projects.

**Comment by tribly** [comment]
Ah, I found the culprit. I set the  `build_dir` for `vimtex_compiler_latexmk` to `/tmp/latex` and somehow the files got tangled. When I have separate build-dirs it works without complaining.

Thanks for this awesome plugin!

**Comment by lervag** [comment]
> Ah, I found the culprit.

Great! :)

> Thanks for this awesome plugin!

You're welcome, and I'm happy you like it!
