### ISSUE TITLE
indentation of long command arguments

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#1389]
i am quite happy with vimtex's formatting functionality. a nitpick i still have is this:

typing this figure float:
```
\begin{figure}[htpb]
	\includegraphics[width=0.8\linewidth]{name.ext}%
	\centering%
	\caption{alksdjf alksdj alkjsjd alksj dklfjalkjs dklfj alkj s.alksdjf alksdj alkjsjd alksj dklfjalkjs dklfj alkj s. alksdjf alksdj alkjsjd alksj dklfjalkjs dklfj alkj s.alksdjf alksdj alkjsjd alksj dklfjalkjs dklfj alkj s. alksdjf alksdj alkjsjd alksj dklfjalkjs dklfj alkj s.}
\end{figure}
```
and then `gqip` gives this:
```
\begin{figure}[htpb]
	\includegraphics[width=0.8\linewidth]{name.ext}%
	\centering%
	\caption{alksdjf alksdj alkjsjd alksj dklfjalkjs dklfj alkj s.alksdjf alksdj
		alkjsjd alksj dklfjalkjs dklfj alkj s. alksdjf alksdj alkjsjd alksj
		dklfjalkjs dklfj alkj s.alksdjf alksdj alkjsjd alksj dklfjalkjs dklfj alkj
	s. alksdjf alksdj alkjsjd alksj dklfjalkjs dklfj alkj s.}
\end{figure}
```
the same result can be obtained by changing indentation and then doing `=ip`. the indentation of the last line of the `\caption` to align with the `\caption` command seems odd to me. i could agree if the last line had only the closing brace, but with text it is distracting. 

i would propose to align the last line of the `caption` argument with the previous lines of the `caption` argument.

**Comment by kiryph** [comment]
If this is bothering you right now and lervag does not change it soon, you could invest time into using https://github.com/cmhughes/latexindent.pl as `formatprg`/`equalprg`.

**Comment by lervag** [comment]
> lervag does not change it soon

Sorry guys, life's been very busy lately, and so I'm not able to stay quite on top of the issues. I'll try my best to fix and address things (including this issue) in the following couple of weeks.

**Comment by lervag** [comment]
Thanks for raising this issue. It's been a few years since I last considered this. The last time, I settled on the current behaviour, because I was able to make it work reliably. The issue with the feature you are asking for is that it is harder to keep track of the delimiter counts.

Before I begin to try and implement something, I want to get a clearer picture of what would be the most sensible indentation rules. The current rule counts the number of opening and closing delimiters in the current and previous line and applies some basic math to decide the correct indentation of the current line. Indentation requires an important assumption that the previous line has the correct indentation.

My initial suggestion would be to keep things simple: Instead of reducing indentation on the line of a closing delimiter, we reduce it on the following line. Examples:

```tex
% Current behaviour:
\newcommand{\blah}{command definition
  goes here
and here}

% Change to this:
\newcommand{\blah}{command definition
  goes here
  and here}

\begin{equation}
  % Current behaviour:
  f(x) = \left(... some long expression here ...
    + more stuff here
  + more stuff here \right)

  % Change to this:
  f(x) = \left(... some long expression here ...
    + more stuff here
    + more stuff here \right)
\end{equation}

% Current behaviour:
Lorem ipsum {\color{red} dolor sit amet, consetetur sadipscing elitr, sed diam
  nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed
diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.} Stet
clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

% Change to this:
Lorem ipsum {\color{red} dolor sit amet, consetetur sadipscing elitr, sed diam
  nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed
  diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum.} Stet
clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
```

I think this should be doable with some modification of the math used to calculate the new indentation.

**Comment by lervag** [comment]
I think the behaviour I mention is obtained by changing
https://github.com/lervag/vimtex/blob/fc6b9bf750467ac25fb7b7b394d255ba32729686/indent/tex.vim#L205-L210

into

```vim
function! s:indent_delims(line, lnum, prev_line, prev_lnum) abort " {{{1
  return s:sw*(s:count(a:prev_line, s:re_open) - s:count(a:prev_line, s:re_close))
endfunction
```

So, the question is how to proceed, and I would be very happy to get some feedback. I think this may warrant a new option as well.

Note: In the current implementation, `\[ ... \]` is treated as delimiters, which I think is wrong. It should be treated as an environment specification. If we decide to change things, then I'll fix this as a side effect.

**Comment by nilsbecker** [comment]
this sounds nice! is this already deployed for testing?

**Comment by lervag** [comment]
I've pushed a PR for this now, please see #1405.

**Comment by lervag** [comment]
I'll close this, as we can let the discussion continue in #1405.
