### ISSUE TITLE
Some buggy behavior

### ISSUE THREAD

**Issue by vsilv** [lervag/vimtex#139]
I have a very strange and buggy behavior here.  Everytime I type in {}{} the result is \left\{ } \right\}<++>}<++> with these strange <++> signs. Then I tried to remove vimtex in order to see where the behavior comes from, but removing is not possible! I use vundle, and then PluginClean after decommenting, but as I look into :map the mappings of vimtex are still there! Do you have any explanation?

**Comment by lervag** [comment]
This is not vimtex behaviour, but it does look a lot like the IMAPs from [LaTeX-Suite](http://vim-latex.sourceforge.net/). I suspect you have LaTeX-Suite installed and activated, which should be easy to confirm with `:h latex-suite`.

I do not recommend to use vimtex along other LaTeX-plugins.

**Comment by vsilv** [comment]
You are totally right, I was not aware of having installed Latex-Suite. I will remove it right now, sorry for the interruption and thank you for the fast answer!

**Comment by lervag** [comment]
No problem.
