### ISSUE TITLE
Bug: Quick fix window is not updated after compilation when saving a bibliography file

### ISSUE THREAD

**Issue by dylan-chong** [lervag/vimtex#1391]
1. Open a latex document that has errors
2. Start compilation with `VimtexCompile`
3. Go to the bibliography file (or a child tex file)
4. Edit it by adding some problematic code
5. Save the file
6. Wait for it to say compilation failed. You will see that the quickfix window is not updated with the latest list of errors. However, if after saving the file you quickly switch back to the main tex file, the quickfix window is updated with a list of errors.

`:VimtexInfo`:

```
System info
  OS: Mac OS X 10.14.5 (18F132)
  Vim version: NVIM v0.3.4
  Has clientserver: true
  Servername: /var/folders/kx/wsz1xqjj5cncxlwzwh1rh_4c0000gp/T/nvimaIjwUW/0

vimtex project: assignment2
  base: assignment2.tex
  root: /Users/Dylan/Dropbox/School/engr401/assignment2
  tex: /Users/Dylan/Dropbox/School/engr401/assignment2/assignment2.tex
  out: /Users/Dylan/Dropbox/School/engr401/assignment2/assignment2.pdf
  log: /Users/Dylan/Dropbox/School/engr401/assignment2/assignment2.log
  aux: /Users/Dylan/Dropbox/School/engr401/assignment2/assignment2.aux
  fls: /Users/Dylan/Dropbox/School/engr401/assignment2/assignment2.fls
  compiler: latexmk
    backend: nvim
    output: /var/folders/kx/wsz1xqjj5cncxlwzwh1rh_4c0000gp/T/nvimaIjwUW/2
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    pid: 87669
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$pdf_previewer = "open"' -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'assignment2.tex'
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
  document class: IEEEtran
  packages:
    auxhook
    gettitlestring
    hobsub-generic
    hobsub-hyperref
    hyperref
    ifxetex
    keyval
    kvoptions
    nameref
    rerunfilecheck
    url
```

**Comment by lervag** [comment]
Hi. First: The point of the issue template is to instruct you on what you should include to write a good issue description. There is *no* need to include the issue template text in your issue (I've edited your post to delete the template text).

Except for that, I find your description clear and I understand the problem. I'll look into it when I get the time, as I agree that it would be an improvement for this to work seamlessly.

**Comment by lervag** [comment]
I think this has been solved now, please test.

**Comment by dylan-chong** [comment]
I've just tested this with a child text file and a BIB file and it works perfectly! Thanks so much for fixing this!

**Comment by lervag** [comment]
No problem, thanks for reporting. I think it was a good thing to fix! :)

**Comment by dylan-chong** [comment]
It seems your fix no longer works as of today

**Comment by lervag** [comment]
I can't reproduce that, sorry. For me, this still work as expected.

**Comment by dylan-chong** [comment]
Okay i might have a go at reproducing this in a couple weeks

**Comment by dylan-chong** [comment]
okay I just tried to replicate this again and your plug-in seems to be working perfectly. Not sure what was going on

**Comment by lervag** [comment]
Ok, happy to hear that things are working!
