### ISSUE TITLE
Can you official add the omni complete support of figref fref Eqref.....

### ISSUE THREAD

**Issue by hanqing0521** [lervag/vimtex#1396]
Many journals provide some custom command such as `\figref`, `\Eqref`..... or other ref command
Can you add some support for the ref, so that vimtex can complete any command which has the form `\<anyword>ref{}`.
Thank you.

**Comment by lervag** [comment]
Could you provide a small example LaTeX document that I can work with? It must

1. Compile correctly.
2. Be short (but long enough to be a proper example for what you ask).

Further: Can you explain what you mean with "the form `\anyworkdref{}`"? Is it just a typo, i.e., you mean `\<anyword>ref` (if so, please be more careful when you write issues, because confusion like this is actually quite time consuming!). I'll assume it is a typo, in which case: I have avoided matching `<anyword>` before because I'm afraid it will activate completion on irrelevant commands. Perhaps my worry is misguided. What do you think about this, @kiryph?

**Comment by kiryph** [comment]
@hanqing0521 could you mention the journals and their LaTeX documentclass which define custom commands of the form `\<anyword>ref`?

Just fyi
- `\eqref` (lowercase) is provided by amsmath; I do not know who has defined the uppercase variant

I personally know following  documentclasses of journals

- `elsarticle` by Elsevier journals
- `reftex4-2` http://mirrors.ctan.org/macros/latex/contrib/revtex/doc/auguide/summary4-2.pdf 

Both do not define any new ref commands.

Right now vimtex already matches quite a few variants, i.e. supports already many common packages (e.g. cleveref) and documentclasses:

https://github.com/lervag/vimtex/blob/457fa214ff2b53f24032488823260d5a23b6977e/autoload/vimtex/complete.vim#L284-L294



5min-googling for`\ figref` shows that many people define this on their own. I could not find a documentclass of a journal. However, I have found the package `commath` which defines following additional ones including `\figref`
```
thmref exref   defnref secref
lemref propref remref  figref
colref appref  assref
```
However, IMHO `commath` is not a *standard* package as `amsmath` or the documentclass `revtex4-2` by the American Physical society.

> What do you think about this, @kiryph?

I would add those of important packages (`amsmath`) and documentclasses (i.e. `elsarticle`, `revtex4-2`) which are missing explicitly. Not sure if this is the case here without an explicit example.
Additionally, I would provide a possibility for user who define their own commands or use less common packages to add them manually in their vimrc.

**Comment by hanqing0521** [comment]
> @hanqing0521 could you mention the journals and their LaTeX documentclasses which define custom commands of the form `\<anyword>ref`?
> 
> Just fyi
> 
> * `\eqref` (lowercase) is provided by amsmath; I do not know who has defined the uppercase variant
> 
> I personally know following documentclasses of journals
> 
> * `elsarticle` by Elsevier journals
> * `reftex4-2` http://mirrors.ctan.org/macros/latex/contrib/revtex/doc/auguide/summary4-2.pdf
> 
> Both do not define any new ref commands.
> 
> Right now vimtex already matches quite a few variants, i.e. supports already many common packages (e.g. cleveref) and documentclasses:
> 
> https://github.com/lervag/vimtex/blob/457fa214ff2b53f24032488823260d5a23b6977e/autoload/vimtex/complete.vim#L284-L294
> 
> 5min-googling for`\ figref` shows that many people define this on their own. I could not find a documentclass of a journal. However, I have found the package `commath` which defines following additional ones including `\figref`
> 
> ```
> thmref exref   defnref secref
> lemref propref remref  figref
> colref appref  assref
> ```
> 
> IMHO `commath` is not a _standard_ package as `amsmath` or the documentclass `revtex4-2` by the American Physical society.
> 
> @lervag :
> 
> > What do you think about this, @kiryph?
> 
> I would add those of important packages (`amsmath`) and documentclasses (i.e. `elsarticle`, `revtex4-2`) which are missing explicitly. Not sure if this is the case here without an explicit example.
> Additionally, I would provide a possibility for user who define their own commands or use less common packages to add them manually in their vimrc.

Yes, I have modified the file `vimtex/autoload/vimtex/complete.vim` before I make the issue.
But you know, it is not wise to modify the file by myself when i use the vim plugin managers.
## Example of Journal
The IOP (insitutiute of Physics) recommand the \Fref, \fref , and  others in iopart.cls

```tex
\newcommand{\eref}[1]{(\ref{#1})}
\newcommand{\sref}[1]{section~\ref{#1}}
\newcommand{\fref}[1]{figure~\ref{#1}}
\newcommand{\tref}[1]{table~\ref{#1}}
\newcommand{\Eref}[1]{Equation (\ref{#1})}
\newcommand{\Sref}[1]{Section~\ref{#1}}
\newcommand{\Fref}[1]{Figure~\ref{#1}}
\newcommand{\Tref}[1]{Table~\ref{#1}}
```
Many journals rely on this file.

## My suggestion
I understand your worry.  The vimtex  should not abuse the complete. 
As far as i know, an command (from texlive-package, downloads cls, or custum cls) with the form \<anyword>ref{}, should be a hyperref command, did you aggree.
Complete automatically it is better than input by oneself.
##  modify vimtex/autoload/vimtex 286
If it can be acceptable, the code can be changed to
```vim
let s:completer_ref = {
      \ 'patterns' : [
      \   '\v\\v?%(\w*)?ref%(\s*\{[^}]*|range\s*\{[^,{}]*%(\}\{)?)$',
      \   '\\hyperref\s*\[[^]]*$',
      \   '\\subref\*\?{[^}]*$',
      \ ],
      \ 're_context' : '\\\w*{[^}]*$',
      \ 'cache' : {},
      \ 'labels' : [],
      \ 'initialized' : 0,
      \}
```

**Comment by kiryph** [comment]
Is see it is `iopart` (`art` for article).

The best source for the class I could find is https://publishingsupport.iopscience.iop.org/questions/latex-template/
with the download link
http://publishingsupport.iopscience.iop.org/wp-content/uploads/2017/10/ioplatexguidelines.tar.gz

It is not part of TeXLive/MikTeX or on ctan and has to be installed manually.

As you said it defines following variants:

![Screenshot 2019-05-29 at 11 44 09](https://user-images.githubusercontent.com/371756/58547126-1f1eb980-8207-11e9-8920-58a26429e711.png)

Despite that it has to be installed manually, IMHO this is a common documentclass and would vote to support it out-of-the box.

I am not sure whether it is sensible to use the detection of the documentclass to enable completion for the `\[esftESFT]ref` commands only if `iopart` is used.

I would update the syntax file as well. I think right now the syntax file uses the detection of documentclasses and packages to enable highlighting of the non-standard commands. For example this allows to spot more easily typos when writing (no linter or compilation to be made aware of the typo).

However, I still would add the possibility to adjust the `patterns` of `completer_ref` in the vimrc so everyone can add personal `\newcommands` (e.g. `\figref`) and other classes which have not yet come up.

**Comment by hanqing0521** [comment]
Thank you.
And I find that when I input \<anyword>cite{}, the bib is auto-completed. 
It is the example which I want the ref can be.
If you determine to add the completer_ref to global settings, please do not forget the complete_bib.

I don't think it is important to detect whether the documentclass is iopart or not.
Many nonstandard documentclass may exist, at least so many people write some custom documentclass.

**Comment by lervag** [comment]
Thanks, again, @kiryph, your help is much appreciated! And yes, I also overlooked the existing option!

Reg. syntax highlighting, I am still thinking that it could work to simply match `\\\w*ref` as a reference command. I've searched the list of commands for very many popular packages, and I can't find a single one that ends with `ref` that is not a `ref` type command. Please let me know if you think this is a bad idea!

**Comment by lervag** [comment]
Btw, this issue is resolved the option `g:vimtex_complete_ref`, which was added to the documentation by @kiryph in #1399.

**Comment by kiryph** [comment]
> Please let me know if you think this is a bad idea!

I am not totally opposed of the idea of adding `\\\w*ref`. But I can see also the chance that not all of them refer to defined labels in the document.

I did a search for commands of the form `\\\w*ref` in my TeXLive 2019 installation:

```
/usr/local/texlive/2019 15s
❯ rg -o -N --no-filename '\\\w*ref' | sort | uniq > matches.txt
```

Well, the number of unique matches is actually higher than I anticipated: **2247**

This search result makes me wary about adding them all to the family of `\ref` commands.

I cannot post all matches here. Just the head and the tail. If you have installed [`ripgrep`](https://github.com/BurntSushi/ripgrep) yourself, you can repeat the above command (on my machine 15sec runtime).

```
❯ head -100 matches.txt | column
\7eqref				\Aref				\CodelinePref			\Direttoref
\7pageref			\Autoref			\Coderef			\DisableCrossref
\7ref				\Autref				\CommonCSPref			\DispPref
\AAOwikiref			\BSKtheref			\CommonIfPref			\DispsPref
\ABXtheref			\Backref			\CompilePref			\DubiousFiguref
\AMSautoref			\Betref				\ConfigPref			\EQ_hyperref
\AMSeqref			\BiblatexManualHyperref		\Cpageref			\EnableCrossref
\APACref			\Bref				\Cpref				\EntryPref
\ASYPICcomparef			\CDref				\Cref				\Eqrangeref
\ASYpref			\CNlabelnoref			\Crossref			\Eqref
\AccFancyVerbLineautoref	\CNlabelsubnoref		\CurrentPref			\Equationref
\Accfootnoteautoref		\CNref				\DJsprechref			\Equationsref
\Acctheoremautoref		\CPpref				\DOIexternalref			\Equref
\AcromakePageref		\CSXstructref			\DOIpref			\Exref
\AddHyperref			\CTANfileref			\DTLformatarticlecrossref	\FDSYMdowntheref
\AddPref			\CTANhref			\DTLformatbookcrossref		\FDSYMlefttheref
\AlgoLineautoref		\CTANref			\DTLformatcrossref		\FDSYMrighttheref
\Algorithmref			\CWEBref			\DTLformatincollproccrossref	\FDSYMtheref
\Algorithmsref			\CallHyperref			\DTLisPref			\FDSYMuptheref
\Apageref			\ChapterPref			\DVIobjectref			\FLOWbufferpref
\Appendicesref			\Chapterref			\DeclareBinaryPref		\FNref
\Appendixautoref		\Chaptersref			\DeclarePref			\FOmasterref
\Appendixref			\ChemCleveref			\DeclareSIPref			\FOpnref
\Apxref				\ChemFancyref			\DeclareSubref			\FOref
\ArXivpref			\CitationPref			\DescribePref			\FancyVerbLineautoref

❯ tail -100 matches.txt | column
\verb1chetref		\wantedfigurepref	\wikilangref		\wwwctanpkggenref	\xmlref
\verbpdfref		\waref			\wikiquotelangref	\wwwctanpkgref		\xpageref
\verseref		\warnedxref		\wikiref		\wwwctanpkgsearchref	\xpstartref
\vertref		\wasytheref		\wikitipref		\wwwctanpkgstyref	\xref
\vervolgref		\weakref		\wiktderef		\wwwctanpkgtopicref	\xrsectionref
\verysimplebibnumref	\webdefmref		\wiktenref		\wwwctanref		\xsublineref
\vfigureref		\webdesignref		\wiktionarylangref	\xPDFobjectref		\xtableref
\vnameref		\webdesignurlref	\wiktref		\xabslineref		\xxref
\vnref			\wetterwpref		\winref			\xacceptref		\xygetpolypref
\volref			\wikidebookref		\withhyperref		\xannotationref		\xymatrixpref
\volyearpageref		\wikideenbookref	\wordref		\xassoccnt_standardref	\xymref
\vpagelineref		\wikideenflagref	\wormsmusref		\xbibref		\xypolypref
\vpageref		\wikideflagref		\wrapindpageref		\xdopresetsometextpref	\yacceptref
\vref			\wikideref		\wrappageref		\xdosetupsometextpref	\yourref
\vrnpref		\wikidisambref		\wref			\xfigureref		\yref
\vsecref		\wikienbookref		\writeitemxref		\xflagref		\zeitref
\vxref			\wikienflagref		\writeref		\xindyhyperref		\zifref
\wacceptref		\wikienref		\writetoref		\xintbaref		\zpageref
\wantedconversionpref	\wikilangbooksref	\wwwctanorgbaseref	\xintthebaref		\zref
\wantedfiguref		\wikilangflagref	\wwwctanpkgauref	\xlineref		\ztitleref
```

**Comment by kiryph** [comment]
>  I've searched the list of commands for very many popular packages, and I can't find a single one that ends with ref that is not a ref type command.

BTW is not `\href{http://google.com}` by `hyperref` already a counter-example?

**Comment by lervag** [comment]
> BTW is not \href{http://google.com} by hyperref already a counter-example?

It is, thanks!

In that case, I don't mind adding support for more `\...ref` commands for highlighting, but it would help to get specific requests on which commands to add combined with proper examples.

One possibility would be to let the syntax file also respect the `g:vimtex_complete_ref` option, even though the option name is not intuitive. This would require an update to the docs to make it clear how this option affects syntax highlighting.
