### ISSUE TITLE
TOC split width

### ISSUE THREAD

**Issue by petobens** [lervag/vimtex#140]
Changing the value of `g:vimtex_index_split_width` doesn't seem to work. For instance when I try

```vim
let g:vimtex_index_split_width = 20
```

the TOC width is still `30`. On the other hand doing :
```vim
let g:vimtex_index_split_pos = 'vert leftabove 20'
```

does work.

**Comment by lervag** [comment]
Are you sure you are using the latest version? I think I solved this problem already.

**Comment by petobens** [comment]
I'm using latest. With the following minimal vimrc:

```vim
set nocompatible

let $ONEDRIVE_HOME = expand('C:/OD/Users/Pedro')
let $DOTVIM = expand('$ONEDRIVE_HOME/vimfiles')

set runtimepath+=$DOTVIM/bundle/vimtex/
filetype plugin indent on
let g:tex_flavor = 'latex'

let g:vimtex_view_enabled = 0
let g:vimtex_latexmk_enabled = 0
let g:vimtex_index_split_width = 20
````

The TOC window is not properly resized as seen in the GIF below. On the other hand if I set 
```vim
let g:vimtex_index_split_pos = 'vert leftabove 20'
```
then it works. 

![blah](https://cloud.githubusercontent.com/assets/2583971/6828248/5919fd22-d2eb-11e4-8bc3-806e22858a88.gif)

**Comment by petobens** [comment]
BTW, why is that in the minimal example of my previous comment I need to call `vimtex#init()` for the plugin to work?

**Comment by lervag** [comment]
The reason is that `set runtimepath+=...` appends to the runtimepath. What you what is to prepend, which makes the plugin prioritized over the internal tex plugin. You can use: `let &rtp = '~/.vim/bundle/vimtex,' . &rtp` (or similar).

**Comment by lervag** [comment]
Typical silly bug. Sorry, it should be fixed now.

**Comment by petobens** [comment]
Thank you!! And thanks for the explanation too.
