### ISSUE TITLE
Compile pdf to loaction of cursor on vim

### ISSUE THREAD

**Issue by thereisnospooon** [lervag/vimtex#1400]
**Describe the solution you'd like**
I'm using neovim with vimtex on Ubuntu to write tex files. 
My .vimrc file is here -

https://pastebin.com/0Hs5EaEg

When I'm saving my .tex file vimtex automatically compiles the tex to pdf (on default evince). After compilation, I would like the pdf to open in a position close to where I am with the cursor on vim. Is it possible?

Thanks,

**Comment by lervag** [comment]
What you are asking for is called forward search with synctex, see `:help vimtex-synctex` and `:help g:vimtex_view_method`. Let me know if you have problems after reading the relevant documentation.

**Comment by lervag** [comment]
See #179 for a related discussion. Note also the recommendation to look into other viewers.
