### ISSUE TITLE
Unable to invoke Latex with shell escape

### ISSUE THREAD

**Issue by Rayzgz** [lervag/vimtex#1403]
Hi, I have a small issue with trying to use minted package, I have configured the vimrc to have the latexmk option to compile with -shell -escape, but was in the error told that I must invoke with shell escape flag.
I am using vim 8.0 on ubuntu 18.04
vimtex already up to date.
minted is installed with package texlive-latex-extra
python-pygment is installed as well.
I don't know what other steps I'm missing, sorry for the bother(still new to github and programming) and thank you very much!

here is my latex file
![Screenshot from 2019-06-05 20-00-43 (1)](https://user-images.githubusercontent.com/39783603/58998294-13666080-87ce-11e9-9516-c86c5dd6f1c5.jpg)

here is the error
![Screenshot from 2019-06-05 20-00-43 (2)](https://user-images.githubusercontent.com/39783603/58998314-224d1300-87ce-11e9-9f8c-fdf4a603649b.jpg)

and here is my vimrc file
![Screenshot from 2019-06-05 20-10-16](https://user-images.githubusercontent.com/39783603/58998320-2842f400-87ce-11e9-8cd3-5b121cb401b1.jpg)

**Comment by lervag** [comment]
Happy to hear it works.
