### ISSUE TITLE
VimtexCompile doesn't work in continuous mode because of locale error

### ISSUE THREAD

**Issue by PascalZh** [lervag/vimtex#1404]
**Describe the issue**
VimtexCountWords doesn't work too, but VimtexCompileSS still work.

**Steps to reproduce**
- This is my .vimrc file:
```vim
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'
let g:vimtex_compiler_progname='nvr'

```
- I think it's nothing about the LaTex file, but I still give one:

  ```tex
  \documentclass{minimal}
  \begin{document}
  Hello world!
  \end{document}
  ```
- When I run `VimtexCompile` and `VimtexCountWords` the following error occured:
```
*** locale::facet::_S_create_c_locale name not valid
```
- I accidentally fix this problem:
When I run :!locale in the neovim:
![1](https://user-images.githubusercontent.com/32212800/59025634-343ebc80-8887-11e9-88a3-a04c4579acb1.PNG)

By the way, I'm using zsh. When I add `export LANG=en_US.UTF-8` to `/etc/zsh/.zshenv`, VimtexCountWords works, but VimtexCompile still not works.

Then I read the source code `vimtex/autoload/vimtex/compiler/latexmk.vim`, and change every `sh` in the file to `zsh`, it works!

What's the hell about it? Maybe it is not the problem of vimtex, but I am desperate about it.

**Comment by lervag** [comment]
You did not read the issue template. Please read it again, in particular note the part about defining a minimal example and on describing the issue in a clear and concise matter.
