### ISSUE TITLE
Capture python errors when using pythontex

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1406]
**Is your feature request related to a problem? Please describe it.**
When using pythontex and your python code contains an error, the only feedback you get, when using vimtex for compiling, is no pdf output. But you do not know what the reason is.

**Describe the solution you'd like**
I would find it useful if the quickfix list could list the python errors as well.

**Describe alternatives you've considered**
1. Open manually the log file `<leader>lo` and search for errors.
2. Compiling on the command line without using vim and its quickfix list.

**Additional context**
Example file with a simple indentation error (lines should not be indented).
```tex
\documentclass{article}
\usepackage{pythontex}

\begin{document}

\begin{pycode}
    print(r'\begin{center}')
    print(r'\textit{A message from Python!}')
    print(r'\end{center}')
\end{pycode}

\end{document}
```
(use latexmkrc from `<YOURTEXLIVEPATH>/texmf-dist/doc/support/latexmk/example_rcfiles/pythontex-latexmkrc`. my texlive path is `/usr/local/texlive/2019`. There have been updates in October 2018 to latexmk and the file `pythontex-latexmkrc`. Please use a latexmk version after Oct 2018.)

Part of output:
```
------------
Running 'pythontex  "demo-pythontex.pytxcode"'
------------
This is PythonTeX 0.16

----  Messages for py:default:default  ----
* PythonTeX stderr - error on line 7:
    File "<outputdir>/py_default_default.py", line 53
      print(r'\begin{center}')
      ^
  IndentationError: unexpected indent

--------------------------------------------------
PythonTeX:  demo-pythontex - 1 error(s), 0 warning(s)

Latexmk: Errors, so I did not complete making targets
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
```

**Comment by lervag** [comment]
Hi @kiryph. I'm so sorry for responding to this so very late. At least I managed to respond within the year... :p 

Are you still interested in this?

I've been thinking about this, and I'm not quite sure how to properly implement it. Do you know if `pythontex` supports loggin python errors to a separate file? That would make it relatively simple. But if the only way is to parse the already quite "messy" LaTeX log file, then I'm not sure if it is worth the effort.

**Comment by lervag** [comment]
I did not have the `latexmkrc` file on my system, but I [found this one](https://ctan.uib.no/support/latexmk/example_rcfiles/pythontex-latexmkrc). I assume this should work?

**Comment by lervag** [comment]
Ok, I can reproduce your error message now. However, it seems difficult to implement support for this, because the error output does not seem to be available except in the latexmk output stream. So, to add support, I would also have to change some of the underlying code so as to make the most recent compile output available. I see a lot of "pain" and difficulties in this, and I'm not sure I want to try.

However, if it would be possible to divert the python error output to a file, then that should make things "easy" (at least, I think so).

**Comment by kiryph** [comment]
Hi @lervag, thanks for taking a look into this.

> However, if it would be possible to divert the python error output to a file, then that should make things "easy" (at least, I think so).

There is the package option `makestderr`:

```tex
\documentclass{article}
\usepackage[makestderr]{pythontex}

\begin{document}

\begin{pycode}
    print(r'\begin{center}')
    print(r'\textit{A message from Python!}')
    print(r'\end{center}')
\end{pycode}

\end{document}
```

This will generate error output files for each `\py` command and pyenv. Here `pythontex-files-demo/py_default_default_0.stderr`.
```
❯ tree
.
├── demo.aux
├── demo.fdb_latexmk
├── demo.fls
├── demo.log
├── demo.pytxcode
├── demo.pytxlog
├── demo.tex
├── latexmkrc
├── latexmkrc-new
└── pythontex-files-demo
    ├── demo.pytxmcr
    ├── demo.pytxpyg
    ├── **py_default_default_0.stderr**
    └── pythontex_data.pkl

1 directory, 13 files
```

However, filename and line numbers do not match the original LaTeX file:

```
❯ cat pythontex-files-demo/py_default_default_0.stderr
  File "py_default_default.py", line 1
    print(r'\begin{center}')
    ^
IndentationError: unexpected indent
```

Interestingly, the documentation of pythontex mentions this very issue [on page 6](http://mirrors.ctan.org/macros/latex/contrib/pythontex/pythontex.pdf#page=6):

> **Error messages**
> Whenever code is saved from a LaTeX document to an external file and then executed, the line numbers for any error messages will not correspond to the line numbering of the original LaTeX document. At one extreme, python.sty doesn’t attempt to deal with this issue, while at the other extreme, SageTeX uses an ingenous system of Try/Except statements on every chunk of code. We need a system that translates all error messages so that they correspond to the line numbering of the original LaTeX document, with minimal overhead when there are no errors.

However, I could not figure out if pythontex actually offers a solution for this.

In a first step, I would not mind when the cursor is not automatically placed on the correct line, even though this would be desirable. Getting feedback about an error and what the error is would already be an improvement.

So, I would suggest that users who want to see errors need to add the option `makestderr` and vimtex lists the errors without line numbers.

If someone knows whether the filename and line numbers can be modified to match the LaTeX file, let us know here.

Of course, vimtex could do this, but I feel like this could/should be part of pythontex.

**Comment by lervag** [comment]
Thanks for the update on details such as the `makestderr` option!

> In a first step, I would not mind when the cursor is not automatically placed on the correct line, even though this would be desirable. Getting feedback about an error and what the error is would already be an improvement.

I'm thinking about a possible way to address this:

1. When parsing errors, check if we have the `pythontex` package with the `makestderr` option. If not, do nothing else.

2. Add a new qf parser that adds to the quickfix list from `pythontex-files*/*.stderr`. We can use standard python errorformats and let the file names point to the `stderr` files, which should provide the context.

**Comment by lervag** [comment]
Ok, I've tried to look at it some more, and I have to admit I don't quite "get it". It seems, for some reason, that pyhtontex "screws up" the callbacks. If I compile the original example in this thread, I first get the "compilation failed" message. But after changing things, I no longer get the callbacks. I don't understand what is happening.

I'm sorry to say that I'm tempted to let this one go...

**Comment by krishnakumarg1984** [comment]
Whoa! This is incredible stuff. If this fix happens, this will probably help to fix 'sagetex' compilation errors too (since sage is essentially python).

**Comment by lervag** [comment]
@krishnakumarg1984 Did you read my last post? I'm still thinking to let this one pass, as I've not been able to figure out a "smooth" way to implement it. That is, it seems to very quickly turn into an ugly hack, and I don't really want that.

**Comment by krishnakumarg1984** [comment]
Ah. I hadn't read that. I read the issue description by the OP, and thought this will be really cool.

Anyway, no worries.

**Comment by lervag** [comment]
I'm letting this go to make it easier to focus on other things.
