### ISSUE TITLE
Indentation for "tex" delimiters

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1412]
**Is your feature request related to a problem? Please describe it.**
/right/rbrace is not changing indentation back, and i expect this to be the same for 'texed' delimiters

**Describe the solution you'd like**
add them to the autoindentation,

If they should just be added to the indentation/tex.vim file, i will gladly help

**Comment by lervag** [comment]
Can you provide a proper example of the delimiter? `/right/rbrace` is not a proper LaTeX macro, if you mean `\right\rbrace`, then `\right` is not itself a delimiter, but a delimiter modifier. The delimiter is `\lbrace ... \rbrace`, and these are not standard, I believe.

See https://tex.stackexchange.com/questions/109220/vs-lbrace-rbrace, which seems to claim that you should use `\{ ... \}` instead. Is there a reason why you think it is better to use `\lbrace .. \rbrace`?

**Comment by 927589452** [comment]
yes the / instead of the \ was a typo

I just did always use it, but if it should be dropped i think we could also remove it from the autocompletion ( where I added them earlier ).

(also I am only using them in mathmode)

**Comment by lervag** [comment]
I am sorry for being blunt, but please try to be more specific. Remember that what is obvious/clear to you is not necessarily so for me. I don't understand what you mean with

> I just did always use it, but if it should be dropped i think we could also remove it from the autocompletion ( where I added them earlier ).

What's "it", and what do you mean "remove it from the autocompletion (where I added them earlier)"?

**Comment by 927589452** [comment]
no problem;
was talking about \rbrace 
i made the PR adding \rbrace to the autocompletion on ``]]``
 #1336

if it is not encouraged to use, it should probably be dropped, or it should be included in 
https://github.com/lervag/vimtex/blob/master/indent/tex.vim line 22 
for completeness(es?) sake

and sorry for me beeing not detailed enough

**Comment by 927589452** [comment]
Though thinking about it:
could /should the delims from here 
autoload/vimtex/delim.vim
be included in the indentation 
aka the first element of the list signalizing indentation
and the second removing a level of indentation ?
not sure if this is possible anyway

**Comment by lervag** [comment]
Thanks, things make more sense now. The `indentkeys` option does not define indentation, it only gives a list of identifiers that, when typed, causes reindentation of a line with respect to the indent expression. That is, in vimtex case, it causes the `VimtexIndentExpr()` function to be called.

Although I think I might understand what you want now, could you be more specific in the sense of providing a clear example of what you want to do, then what you expect to happen as well as your observation of what happens now?

**Comment by 927589452** [comment]
On 19-06-28 03:02:58, Karl Yngve Lervåg wrote:
> Thanks, things make more sense now. The `indentkeys` option does not define indentation, it only gives a list of identifiers that, when typed, causes reindentation of a line with respect to the indent expression. That is, in vimtex case, it causes the `VimtexIndentExpr()` function to be called.

Thanks for clarifying
>
> Although I think I might understand what you want now, could you be more specific in the sense of providing a clear example of what you want to do, then what you expect to happen as well as your observation of what happens now?
>

Just made a test

Currently
```
\begin{math}
% this is all just typed down and closes with `` ]]``

	(
	A
	)
	\left(
		B
	\right)
	\left\lbrace
		C
		\right\rbrace
```
Expected behaviour
```
\begin{math}
% this is all just typed down and closes with `` ]]``

	(
	A
	)
	\left(
		B
	\right)
	\left\lbrace
		C
	\right\rbrace
```

Alternatively
```
\begin{math}
% this is all just typed down and closes with `` ]]``

	(
	A
	)
	\left(
		B
	\right)
	\left\lbrace
	C
	\right\rbrace
```




Dream unicorn fluff perfect
```
\begin{math}
% this is all just typed down and closes with `` ]]``

	(
		A
	)
	\left(
		B
	\right)
	\left\lbrace
		C
	\right\rbrace

```

**Comment by lervag** [comment]
> Dream unicorn fluff perfect

Currently, only modified delimiters, i.e. `\left...\right...` (and similar) variants, are indented. Indenting delimiters without modifiers is possible, but I think we had a good reason to avoid it. Can't remember now, but I think it makes at least partial sense. In any case, it is a different issue, and we could consider it if more people agree.

In any case, I now fully understand the issue and will look into it.

**Comment by lervag** [comment]
In case you had not noticed, please also read `:help vimtex_indent_delims`.

**Comment by lervag** [comment]
Ok, I think I've solved your original issue. Please test and confirm.

Back to your fluffy perfect desire, you may add indentation for parantheses through the `g:vimtex_indent_delims`, but note that there is no support for differentiation between math mode and text mode. I.e., if you want parantheses to add indents, they will also add indents in the text.

Quite some time ago, I actually did handle math mode and text mode differently, but I never managed to iron it out and after some discussion, we settled on the current version which is of course much simpler, but it should work more consistently.

**Comment by 927589452** [comment]
thank you very much, the fix is working 

will look into the the vimtex_indent_delims (and gladly don't need to treat text special
