### ISSUE TITLE
Autocompletion triggers after line break (\\)

### ISSUE THREAD

**Issue by Krasjet** [lervag/vimtex#1414]
**Describe the issue**

Hi, I'm currently using the [coc.nvim](https://github.com/neoclide/coc.nvim) (with [coc-vimtex](https://github.com/neoclide/coc-vimtex) extension ) for auto-completions. Since coc.nvim is using the [regexes](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/re.vim) from [deoplete.nvim](https://github.com/Shougo/deoplete.nvim), this issue should affect deoplete users as well.

This is a very minor issue but it is kind of annoying. Every time I type the line break sequence `\\` (for example, inside a `align*` environment), the completion regexes will try to match a single `\` and show a list of all the available commands. To reproduce it, first install `coc.nvim` with `coc-vimtex` or `deoplete`, and

```latex
\documentclass{minimal}
\usepackage{amsmath}
\begin{document}
\begin{align*}
  x &= 1 \
  %       ^ type '\' here
\end{align*}
\end{document}
```

I am using the `Enter` key to confirm a completion, so whenever I need to open a new line after the line break (which is something I always do), I have to manually type a space character to cancel the completion, or go back to normal mode and press `o` to open a new line, which can be quite cumbersome after a while.

Is it possible to modify the completion regexes so that it ignores the line break sequence (`\\`)?

Thank you.

**Comment by lervag** [comment]
I'm using `coc.nvim` myself, and I can reproduce this. That is, I assume what you want is this:

1. When the first `\` is typed, `coc.nvim` may apply its magic and activate completion.
2. When the second `\` is typed, the regex should be applied and indicate that no completion is allowed.

**Comment by Krasjet** [comment]
Exactly, the first `\` is the prefix of a command, so no problem. But `\\` should be interpreted as a line break and should not trigger auto-completion.

**Comment by lervag** [comment]
Should be fixed now.
