### ISSUE TITLE
Completion of citations does not work

### ISSUE THREAD

**Issue by lahwaacz** [lervag/vimtex#142]
I'm working on setting up automatic completion with YCM (will make a pull request soon to update the docs), but I can't make it work for citations. I suspect that this is a general issue of vimtex not related to YCM itself.

I've tested the completion in an old document using bibtex and in current document using biber, it worked fine in the old but not in the new. Looking at the code, I assume the information is obtained by parsing `.bbl` files produced by manually running bibtex on custom `.aux` file including the recognized `.bib` files (please correct me if I'm wrong), so it seems that my `.bib` file is not recognized. It is added using `\addbibresource` in `header.tex` (file which contains just the preamble) which is then `\input` from `main.tex` which is the main file being compiled.

**Comment by lervag** [comment]
I'll be very happy to receive a pull request for YCM!

You're assumptions are pretty solid: The completion code generates a custom aux-file that inserts all citations from the set of bib files that are included. This is then parsed by bibtex to generate a bbl-file.

The bibligraphies are parsed with the regexp:
```vimL
let s:re_bibs  = '''' . s:nocomment
let s:re_bibs .= '\\(bibliography|add(bibresource|globalbib|sectionbib))'
let s:re_bibs .= '\m\s*{\zs[^}]\+\ze}'''
```
This should match `\addbibresource`, which I have previously verified myself.

Could you try to set `g:vimtex_complete_recursive_bib = 1`? The problem might be due to the use of `\input` in the preamble. For large documents with a lot of inputted files, I found that recursively parsing all inputted files for added bibliographies was a little bit slow, so I turned it off by default.

**Comment by lahwaacz** [comment]
Indeed, `g:vimtex_complete_recursive_bib = 1` solves the issue.

There is one more thing of an aesthetic nature: When the omnifunc for citation completion is invoked, the entire terminal window flashes for a moment. This happens only for citation completions, e.g. after `\cite{`, but not when completing regular labels with e.g. after `\eqref{`. YCM uses the same function for these, so I suspect it's on vimtex' side. Perhaps because executing external program is involved?

**Comment by lervag** [comment]
Strange, this does not happen for me with neocomplete. I could look into this, but it would help to get a minimal working example and a minimal vimrc file.

**Comment by lahwaacz** [comment]
I see, I'll investigate more thoroughly tonight...

**Comment by lahwaacz** [comment]
Here is the minimal example:
``` vim
\documentclass{book}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}

\usepackage{biblatex}
\addbibresource{references.bib}

\begin{document}

\begin{thebibliography}{1}
    \bibitem{item1}
    \bibitem{item2}
    \bibitem{item3}
\end{thebibliography}

\end{document}
```
As it is, writing `\cite{` and invoking the completion results in the terminal flashing. Interestingly commenting out `\addbibresource` avoids flashing, i.e. the in-document bibliography entries are then completed without flashing. The `references.bib` contains only five entries, so it is not so big to cause any trouble.

**Comment by lervag** [comment]
Thanks. Could you also provide `reference.bib` and a minimal `vimrc` file? See [here](https://github.com/lervag/dotvim/blob/master/minivimrc) for an example of a minimal `vimrc` file that should  be easy to use as a template. Note that you can use a custom `virmc` file with `vim -u /path/to/minivimrc`.

**Comment by lahwaacz** [comment]
Sure, the minimized `references.bib` contains just
```
@book{label,
    title={title},
    author={author},
    year={2000},
    publisher={publisher},
}
```
and the minimal `vimrc` to work with YCM is
``` vim
set nocompatible

" runtimepath to load just vimtex and system plugins, including YCM
set runtimepath=$XDG_CONFIG_HOME/vim/bundle/vimtex,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$XDG_CONFIG_HOME/vim/bundle/vimtex/after

" load file type plugins
filetype plugin on

" latex completion
let g:vimtex_complete_recursive_bib = 1     " needed to search .bib files recursively, even in files included with \input
let g:ycm_filetype_whitelist = { 'tex': 1 }
let g:ycm_semantic_triggers = { 'tex': ['\v\\\a*(ref|cite)\a*([^]]*\])?\{([^}]*,)*[^}]*'] }
```

**Comment by lahwaacz** [comment]
Also note that YCM currently does not automatically trigger omnifunc completions due to [this issue](https://github.com/Valloric/YouCompleteMe/issues/438#issuecomment-68581749), so you just need to press `<C-space>` to invoke it manually.

**Comment by lervag** [comment]
Yes, I've now reproduced the issue, thanks. I found it is reproducible without YCM by using common omnicomplete `<c-x><c-o>`. Looking into it now.

**Comment by lahwaacz** [comment]
Confirmed, thanks!

**Comment by srsudar** [comment]
It looks like the YCM issue above is closed. However I still have to hit `<C-space>` to trigger citation completion from my bib file as opposed to just tokens in my file. I've added these lines as suggested above to my vimrc:

```
let g:ycm_filetype_whitelist = { 'tex': 1 }
let g:ycm_semantic_triggers = { 'tex': ['\v\\\a*(ref|cite)\a*([^]]*\])?\{([^}]*,)*[^}]*'] }
```

Are you currently seeing citations suggested automatically without needing the extra `<C-space>`?

**Comment by lervag** [comment]
Hi! See `:h vimtex-complete-youcompleteme` for the current suggestion for `g:ycm_semantic_triggers`. This thread is one year old, and there have been a lot of updates.

If the suggestion in the docs does not work for you, please open a new issue. We can resolve it together.

**Comment by srsudar** [comment]
Ah fantastic, thank you! That does it. My apologies if I missed this in the doc.

**Comment by lervag** [comment]
No problem!
