### ISSUE TITLE
Parsing of bibtex keys fails when identical bibtex keys pop up in different files

### ISSUE THREAD

**Issue by dbankmann** [lervag/vimtex#1423]
**The issue**
Some bib tex are not found for omni completion. This seems to happen, when there are multiply defined keys in different bib files (In my project I got 5 different files).
If the repeated keys appear in the same bib file, vimtex seems not to have any problems.

**Steps to reproduce**

I'm using vim plug so my vimrc looks like 

  ```vim
  set nocompatible
  let &runtimepath  = '~/.local/share/nvim/plugged/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.local/share/nvim/plugged/vimtex/after'
  filetype plugin indent on
  syntax enable

  let g:vimtex_complete_bib = {
			  \'simple': 1,
			  \'recursive': 1
			  \}

  ```
The `simple` option is just set for making things easier to explain and `recursive` just for curiosity (it is not strictly necessary).

- a minimal tex file:

```tex minimal.tex
\documentclass{scrbook}
 \usepackage{biblatex}

\addbibresource{minibib.bib}
\addbibresource{minibib.bib}
\addbibresource{minibib2.bib}
\begin{document}
\cite{M|}               (Cursor |  after M)   
\end{document}
 ```
- some example bib files
```tex minibib.bib
@misc{Nobody06,
  author = "Nobody Jr",
  title = "My Article",
  year = "2006"
}

```
```tex minibib2.bib

@misc{Myself13,
  author = "Myself Jr",
  title = "Your Article",
  year = "2013"
}

```

```tex minibib3.bib
@misc{Nobody06,
  author = "Nobody Jr",
  title = "My Article",
  year = "2006"
}
@misc{Nobody06,
  author = "Nobody Jr",
  title = "My Article",
  year = "2006"
}
```

In the described state, try to use omni completion with `M<c-x><c-o>`; it will not work, while 
`N<c-x><c-o>` does work. 

Also, removing one of the `\addbibresource{minibib.bib}` lines or, additionally, adding the line `\addbibresource{minibib3.bib}` will make `M<c-x><c-o>`  succeed again.

**Comment by lervag** [comment]
Thanks for reporting, this should be fixed now!
