### ISSUE TITLE
completion (closing) of quotes

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1425]
**Is your feature request related to a problem? Please describe it.**
It would be nice to use ]]-completion for \grqq 

**Describe the solution you'd like**
\glq with \grq
\glqq with \grqq
\flq with \frq
\flqq with \flqq
included in the  ]]-completion dictionary

**Describe alternatives you've considered**
Usage of cs quotes

**Additional context**
taken from [here](https://de.wikibooks.org/wiki/LaTeX-W%C3%B6rterbuch:_Anf%C3%BChrungszeichen#Deutsche_Anf%C3%BChrungszeichen)

**Comment by kiryph** [comment]
Did you already try one of the "autoclosing" plugins:

- **Autopairs** https://github.com/jiangmiao/auto-pairs#multibyte-pairs
- **Lexima** https://github.com/cohama/lexima.vim#customization
  (https://github.com/deathlyfrantic/lexima-template-rules)

Also [**UltiSnips**](https://github.com/SirVer/ultisnips) can help (if you like with auto-expansion otherwise remove the `A` at the end of the snippets below):

```
snippet glq "\glq \grq" wA
\glq$1\grq$0
endsnippet

snippet glQ "\glqq \grqq" wA
\glqq$1\grqq$0
endsnippet

snippet flq "\flq \frq" wA
\flq$1\frq$0
endsnippet

snippet flQ "\flqq \frqq" wA
\flqq$1\frqq$0
endsnippet
```

**Comment by 927589452** [comment]
I would prefer for it to be the same way as for other delims,
so I would add it to 
function! s:init_delim_lists() 
as an subdictionary if @lervag doesn't object

I try to get away from this quotation as BibLaTeX prefers usage of cs quotes too,
but I would implement it at this position, if there are no problems with this

thanks @kiryph for your suggestions, but the first one directly "conflicts" with ( ) closing of vimtex for example

**Comment by kiryph** [comment]
> thanks @kiryph for your suggestions, but the first one directly "conflicts" with ( ) closing of vimtex for example

This should be [configurable](https://github.com/jiangmiao/auto-pairs/blob/3c290d9308c1b651c588865c3741a12654ae640e/doc/AutoPairs.txt#L206-L217): `au Filetype tex let b:AutoPairs = {"\glq": "\grq"}`

> so I would add it to `function! s:init_delim_lists()`

Did you already try 

```viml
g:vimtex_delim_list = {
        \ 'delim_tex' : {
        \   'name' : [
        \     ['\glq', '\grq'],
        \   ]
        \ }
\}
```
You should not change the source code of vimtex itself but use variables considered by vimtex to adjust those lists.

Related plugin: [vim-sandwich](https://github.com/machakann/vim-sandwich) (similar to vim-surround) allows you to wrap existing text with custom surroundings. The defaults do not cover those explicitly, but the existing ones can be adjusted or extended for them:

https://github.com/machakann/vim-sandwich/blob/master/macros/sandwich/ftplugin/tex.vim#L4-L11

**Comment by 927589452** [comment]
> > thanks @kiryph for your suggestions, but the first one directly "conflicts" with ( ) closing of vimtex for example
> 
> This should be [configurable](https://github.com/jiangmiao/auto-pairs/blob/3c290d9308c1b651c588865c3741a12654ae640e/doc/AutoPairs.txt#L206-L217): `au Filetype tex let b:AutoPairs = {"\glq": "\grq"}`
this was only from reading the description

> 
> > so I would add it to `function! s:init_delim_lists()`
> 
> Did you already try
> 
> ```viml
> g:vimtex_delim_list = {
>         \ 'delim_tex' : {
>         \   'name' : [
>         \     ['\glq', '\grq'],
>         \   ]
>         \ }
> \}
> ```
that works rather nicely.

I suggested an addition to the doc in #1431 .

**Comment by lervag** [comment]
Yes, I agree with @kiryph on not changing vimtex here. I realize that the relevant option is somewhat obscure, so I've updated the docs according to your example in #1431 and the above discussion. I hope this will feel adequate.
