### ISSUE TITLE
[docs-update request] Provide a more direct link to `latexrefman` in the documentation

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1426]
In the documentation page for `vimtex`, I notice that the link to `latexreman` is given as 
`https://puszcza.gnu.org.ua/projects/latexrefman/` 

This is in-fact the GNU project-tracker page, which includes a lot more "meta-info" than the actual Latex-help contents of `latexrefman`.

It would be more helpful to readers if the link was updated to directly point to the actual documentation, i.e. [`https://latexref.xyz/`](https://latexref.xyz/) which is what most users are looking for.

**Comment by lervag** [comment]
Thanks! This is resolved by #1432 and my recent commit.

**Comment by krishnakumarg1984** [comment]
You are awesome! Thanks @lervag

**Comment by lervag** [comment]
Thanks! :)
