### ISSUE TITLE
Dealing with Packages

### ISSUE THREAD

**Issue by Degiorgio** [lervag/vimtex#1427]
I have vimtex setup, I also have latexmk installed.  This works fine, unless I am using packages for example (filecontents). When I try to compile,  it  gives an error like 'filecontents.sty' not found. How does one go about installing packages? 

Thanks!

**Comment by 927589452** [comment]
This highly depends on your OS;
you could have a look at http://tug.ctan.org/ and you can probably install it with your systems package manager and the tex-all package

**Comment by lervag** [comment]
Yes, this is not an issue with vimtex. You should learn to use LaTeX in general and on your OS/distribution. There are countless guides and books on this.
