### ISSUE TITLE
Vimtex fails to initialize

### ISSUE THREAD

**Issue by xu-cheng** [lervag/vimtex#143]
After recent update, `vimtex` stop to initialize when opening `.tex` files. A minimal example is shown in below:
* Install [vim-plug](https://github.com/junegunn/vim-plug)
* Set `$HOME/.nvim/nvimrc`(I use neovim) as:
```vim
call plug#begin($HOME . '/.nvim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```
* Run `:PlugInstall` and restart neovim.
* Open any `.tex` file and run `:verbose map`. You won't found any vimtex key mapping.
* Run `:call vimtex#init()` and `:verbose map` again. Everything works normal.

**Comment by lervag** [comment]
I am not able to reproduce. I did as follows:

1. Create `mininvimrc` with the specified content
```vimL
call plug#begin('~/.nvim/bundle')
Plug 'lervag/vimtex'
call plug#end()
```
2. Run `nvim -u mininvimrc`
3. Do `:set ft=tex`

Now when I do `:verbose map`, the mappings are listed as expected. Was there some step here I've missed?

I use neovim on commit [119a3f2485](https://github.com/neovim/neovim/commit/119a3f2485e057b05ca46fc40e59f1434913d488), installed on Arch Linux with the `neovim-git` [aur package](https://aur.archlinux.org/packages/neovim-git/).

**Comment by xu-cheng** [comment]
If I run `:set ft=tex`, everything works fine as well. But should it auto detect file type rather than set it manually?

FYI, my neovim is on commit https://github.com/neovim/neovim/commit/4b585c52f3e4627b746c9e371e307210680baa0a which is almost same as yours (Only a document is different between the two commits). I work on OS X installed by [`homebrew-neovim`](https://github.com/neovim/homebrew-neovim).

**Comment by lervag** [comment]
Ok. Instead of my previous 3., I now do: `:e test.tex`, where `test.tex` does not exist. This reproduces your problem. However, this is the "desired" behaviour. The reason is that the `tex` file is recognized as a `plaintex` file, which you see if you do `:set filetype`. If you always want to use LaTeX file types, you can add `let g:tex_flavor = 'tex'` to your `vimrc` or `nvimrc` file.

**Comment by xu-cheng** [comment]
My `test.tex` exists and has valid content.

**Comment by lervag** [comment]
When you open your `test.tex`, what is the output of `:echo &filetype` (or `set filetype`)?

**Comment by xu-cheng** [comment]
Strange. It shows `filetype=vim`.

**Comment by lervag** [comment]
That's strange. Try `:verbose set filetype`. Do you use a modeline in the `tex` file?

**Comment by xu-cheng** [comment]
`verbose set filetype` shows:

```
filetype=vim
        Last set from /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/filetype.vim
```

TeX file is:
```latex
\documentclass{article}

\begin{document}
test
\end{document}
```

**Comment by lervag** [comment]
Does this also occur if you add `let g:tex_flavor = 'latex'` to your `nvimrc` file?

**Comment by lervag** [comment]
Though, I get the correct behaviour without that variable defined when I do `nvim -u mininvimrc test.tex` with your minimal `nvimrc`. Here `test.tex` is the same file as you just supplied.

**Comment by xu-cheng** [comment]
Oh my bad. I accidentally name the file to `test.vim`. Everything works fine in the minimal test. 

However, in my vim config, vimtex still fails to initialize even after running `:set ft=tex`. Close this issue now until I can work out a workable mini example.

**Comment by lervag** [comment]
Yes, that would explain the problem. I find it strange that vimtex fails to initialize, but of course there might be a bug somewhere.

**Comment by xu-cheng** [comment]
Finally, I find the bug is caused the vim plugin written by my own(in fact it's my first and only vim plugin so far). If you are interesting, this is the [cause](https://github.com/xu-cheng/brew.vim/commit/7dcc577407d88aee5d67d0b2dee28dbc2df6cbfd)

Sorry for any inconvenience.

**Comment by lervag** [comment]
No inconvenience and no problem. :)
