### ISSUE TITLE
Only load syntax highlighting if package present

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1433]
**Describe the solution you'd like**
Only load the syntax highlighting for packages, if the package is loaded.

**Describe alternatives you've considered**

**Additional context**
The idea is from [here](https://github.com/lervag/vimtex/issues/1428#issuecomment-514511813) by @kiryph  and I would like to try to at least provide a few of the cases tomorrow

**Comment by lervag** [comment]
Thanks, this is done now.
