### ISSUE TITLE
Vimtex compilation with \ll doesn't work after update

### ISSUE THREAD

**Issue by mfwre** [lervag/vimtex#1434]
Hi, I'm really sorry if you might need to ask me extra question. I'm completely new at Linux, Vim, ecc..

However, I managed to set Vim, with vimtex working together with Zathura and compiling with latexmk up on a Linux Mint installation.

My plugin manager is Vundle.

Everything worked great until I updated vim via source to version 8.1.1773. 
Now, whenever I open a .tex file vim spits me out these errors
```raw
Error detected while processing function vimtex#init[4]..<SNR>35_init_state[1]..vimtex#state#init[9]..3[33]..vimtex#compiler#init_state[10]..vimtex#compiler#latexmk#init:
line    3:
E712: Argument of extend() must be a List or Dictionary
Error detected while processing function vimtex#init[4]..<SNR>35_init_state[1]..vimtex#state#init:
line    9:
E171: Missing :endif
```

and it doesn't recognice the '\' leader anymore. So no more continuous compilation.
I haven't found a single solution googling around and browsing through the issues here.

Here a minimal LaTeX file
```latex
  \documentclass{article}
  \begin{document}
  \maketitle
  \tableofcontents
  \newpage
  
  \section{Dummy}
Some text
  \end{document}
```
assume it worked without issues until after the update.
Every other plugin works without problems.

And here a minimal .vimrc with my settings
  ```vim
  set nocompatible       
  filetype off             
 
  set rtp+=~/.vim/bundle/Vundle.vim
  call vundle#begin()
 Plugin 'lervag/vimtex'
call vundle#end()  
          
  syntax off
  filetype plugin indent on 
  syntax enable

  let g:tex_flavor='latex'
  let g:vimtex_view_method='zathura'
  let g:vimtex_quickfix_mode=0
  set conceallevel=1
  let g:tex_conceal='abdmg'
  let g:vimtex_compiler_latexmk=1
  ```

:VimtexInfo gives me
`E492: Not an editor command: VimtexInfo`

I'm here for whatever additional info you'll require. Sorry if my issue isn't complete.

**Comment by lervag** [comment]
Strange. I'll look at it, but can you update your original post and add the preamble to your minimal LaTeX file (I don't know what `testata.tex` or  `sezioni/termodinamica.tex` are)?

FYI: Vim has not reached patch 1773 on Arch Linux yet. I might install it from source to test, but not right now.

**Comment by mfwre** [comment]
I’ve updated my original post.
I just keep my preamble (since it’s huge) and the sections on separate files.

I strongly fear that I made some mistake whilst updating.

I tried reinstalling vimtex and vim but the error remains.

**Comment by lervag** [comment]
I think your problem is in your configuration. What do you want to achieve with this setting?

```vim
let g:vimtex_compiler_latexmk=1
```

Please see `:help g:vimtex_compiler_latexmk`. The value should be a dictionary to configure the latexmk backend.

**Comment by mfwre** [comment]
Yes, that solved it. Thank you and sorry for the pointless issue.

My reasoning behind is was it to set latexmk as a compiler. I thought that configuration was like a "switch".

Today I learned that I can :help things. Thank you again

**Comment by lervag** [comment]
No problem! :)

`latexmk` is already the default compiler backend. To set a different backend, you use `:help g:vimtex_compiler_method`.
