### ISSUE TITLE
better support for manual folds

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1438]
**Is your feature request related to a problem? Please describe it.**
`vimtex`'s `foldtext` replacement "eats" lines:

```MWE.tex
\begin{document}
\somerandomcomman{% {{{
options,
some more text
}% }}}
```

gets folded loosing the information
```MWE.tex folded
\begin{document}
---------------
```

**Describe the solution you'd like**
```MWE.tex
\begin{document}
\somerandomcomman{---------------
```

If no title is given for a fold by using ```% {{{ title```,  eg matches `foldmarker$` , it would be nice to set `foldtext` to the match `\1` of `^(.*)foldmarker`.  This would be rather useful when setting manual folds ( and saves having to add a title)

**Comment by lervag** [comment]
Fixed. I made some minor improvements to the marker fold text, let me know what you think.

**Comment by lervag** [comment]
(Sorry, having trouble pushing to github atm, the fix will be pushed as soon as possible.)

**Comment by 927589452** [comment]
its already much better, but the search string could be refined to ignore numbers (for foldlevels) directly following the foldmarker as in `{{{2`; currently we get
```
\newglossaryentry{abelian} {% {{{2
	name={Abelsch},
	description={},
}% }}}2
```
to
```
 % {{{ 2─────────────────────────────────
```
I thinks this can be fixed by my PR
