### ISSUE TITLE
error on CTRL-N

### ISSUE THREAD

**Issue by cridemichel** [lervag/vimtex#1441]
**Describe the issue**
A clear and concise description of the issue.

**Steps to reproduce**

1) create a directory VIMTEX_BUG
2) unzip and copy the attached file (maintext_v1.tex) in the directory just created
3) unzip and copy the minimalist '.vimrc' (which is attached) into your home dir
4) open macvim (from /Applications)
5) from macvim command line: 
     :cd VIMTEX_BUG
6) then: 
     :e maintext_v1.tex
7) switch to insert mode
8) type CTRL-N

I systematically get the following error:
https://docs.google.com/document/d/11aHqNS2NLRVZVpqyN4BlcjaAMS6xcG3x4Ba_QFxyFY0/edit?pli=1

Error detected while processing function vimtex#include#expr[1]...164:
line 1:
E806: using Float as a String

[maintext_v1.tex.gz](https://github.com/lervag/vimtex/files/3470738/maintext_v1.tex.gz)

[minivimrc.gz](https://github.com/lervag/vimtex/files/3471025/minivimrc.gz)

**Output from VimtexInfo**
```
System info
  OS: Mac OS X 10.14.6 (18G84)
  Vim version: VIM 8.1 (1-1722)
  Has clientserver: true
  Servername: VIM

vimtex project: prova.tex
  base: prova.tex
  root: /Users/demichel
  tex: /Users/demichel/prova.tex
  out:
  log:
  aux:
  fls:
  compiler: latexmk
    backend: jobs
    output: /var/folders/26/9q3nft3x4xg2zbj45nzm__100000gn/T/vYh6Vun/4
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Skim
  qf: LaTeX logfile
    config:
      packages:
        default: 1
      default: 1
  document class:
```

**Comment by lervag** [comment]
I am sorry, but I think you misunderstand the concept of a minimal vimrc file. I've provided an example of it. Your vimrc file is 256 lines long when I remove the comments, and I am not going to try and reproduce your issue with it.

Please provide an actual minimal example.

**Comment by cridemichel** [comment]
> I am sorry, but I think you misunderstand the concept of a minimal vimrc file. I've provided an example of it. Your vimrc file is 256 lines long when I remove the comments, and I am not going to try and reproduce your issue with it.
> 
> Please provide an actual minimal example.

Dear Lervag,
I prepared a detailed list of steps with minimalist .vimrc and .tex files by which 
I am able to systematically reproduce the issue
I hope you will be able to fix it this way,
best regards
Cristiano

**Comment by lervag** [comment]
Dear Cristiano. Your vimrc is still not really minimal. In particular, it still loads several plugins through the plugin manager Vundle. Can you reduce it even further, and in particular, can you remove the Vundle dependency?

Something like this should suffice:

```vim
set nocompatible

" Load plugins
let &rtp = '~/.vim/bundle/vim-fugitive,' . &rtp
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp = '~/.vim/bundle/command-t,' . &rtp
let &rtp = '~/.vim/bundle/YouCompleteMe,' . &rtp

" If necessary:
let &rtp .= ',~/.vim/bundle/vimtex/after'
let &rtp .= ',~/.vim/bundle/PLUGIN/after'

filetype plugin indent on
syntax enable

" Add further settings and configuration here as needed to reproduce the issue
```

Save the vimrc file to something like `minivimrc`, then replace your step 4 with `mvim -u minivimrc` to start your Vim with the minimal vimrc file. Let me know if you need more help with doing this.

Note: I use Linux, and as such, I don't have access to Macvim. I don't think this matters here.

**Comment by cridemichel** [comment]
> Dear Cristiano. Your vimrc is still not really minimal. In particular, it still loads several plugins through the plugin manager Vundle. Can you reduce it even further, and in particular, can you remove the Vundle dependency?
> 
> Something like this should suffice:
> 
> ```viml
> set nocompatible
> 
> " Load plugins
> let &rtp = '~/.vim/bundle/vim-fugitive,' . &rtp
> let &rtp = '~/.vim/bundle/vimtex,' . &rtp
> let &rtp = '~/.vim/bundle/command-t,' . &rtp
> let &rtp = '~/.vim/bundle/YouCompleteMe,' . &rtp
> 
> " If necessary:
> let &rtp .= ',~/.vim/bundle/vimtex/after'
> let &rtp .= ',~/.vim/bundle/PLUGIN/after'
> 
> filetype plugin indent on
> syntax enable
> 
> " Add further settings and configuration here as needed to reproduce the issue
> ```
> 
> Save the vimrc file to something like `minivimrc`, then replace your step 4 with `mvim -u minivimrc` to start your Vim with the minimal vimrc file. Let me know if you need more help with doing this.
> 
> Note: I use Linux, and as such, I don't have access to Macvim. I don't think this matters here.

I uploaded a minimal vimrc but strangely if I use 'mvim -u minivimrc' 
the issue is not triggered, the only way is to follow steps in my first post (i.e. open macvim and 
then the tex file)

**Comment by lervag** [comment]
Thanks for the update. First, reg. minimal vimrc file: The point is that _you_ need to create a viable minimal vimrc file that is usable by me. The one you've attached so far is more complicated than necessary, and I am certain that it can be further reduced as indicated in my earlier posts. I do aknowledge that it require some experience to do this, though, but I am more than happy to help if required.

In any case, your debugging is interesting. The `self.time` should be defined, and it does not make sense that it is not defined. It should be defined in the code just before the `s:visited.timeout()` function definition.

I don't want to update vimtex with your fix until I can reproduce the problem, since I don't understand why your fix is necessary.

**Comment by lervag** [comment]
> I uploaded a minimal vimrc but strangely if I use mvim -u minivimrc the issue is not triggered. The only way is to follow steps in my first post (i.e. open macvim and then the tex file).

What do you mean by this? Are you now using the minimal vimrc file I suggested, i.e.:

```vim
set nocompatible

" Load plugins
let &rtp = '~/.vim/bundle/vim-fugitive,' . &rtp
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp = '~/.vim/bundle/command-t,' . &rtp
let &rtp = '~/.vim/bundle/YouCompleteMe,' . &rtp

filetype plugin indent on
syntax enable
```

**Comment by cridemichel** [comment]
> Thanks for the update. First, reg. minimal vimrc file: The point is that _you_ need to create a viable minimal vimrc file that is usable by me. The one you've attached so far is more complicated than necessary, and I am certain that it can be further reduced as indicated in my earlier posts. I do aknowledge that it require some experience to do this, though, but I am more than happy to help if required.
> 
> In any case, your debugging is interesting. The `self.time` should be defined, and it does not make sense that it is not defined. It should be defined in the code just before the `s:visited.timeout()` function definition.
> 
> I don't want to update vimtex with your fix until I can reproduce the problem, since I don't understand why your fix is necessary.

the vimrc which I am using is the one which you sent me, please check

**Comment by cridemichel** [comment]
> Thanks for the update. First, reg. minimal vimrc file: The point is that _you_ need to create a viable minimal vimrc file that is usable by me. The one you've attached so far is more complicated than necessary, and I am certain that it can be further reduced as indicated in my earlier posts. I do aknowledge that it require some experience to do this, though, but I am more than happy to help if required.
> 
> In any case, your debugging is interesting. The `self.time` should be defined, and it does not make sense that it is not defined. It should be defined in the code just before the `s:visited.timeout()` function definition.
> 
> I don't want to update vimtex with your fix until I can reproduce the problem, since I don't understand why your fix is necessary.

the previous fix was meaningless I agree, indeed the realy culprit was
the use of a floating point number in the following if condition:

if localtime() - self.time > 1.0

inside the function s:visited.timeout()
If one replaces 1.0 with 1 the issue is gone!

In other word the new s:visited.timeout() function should read

function! s:visited.timeout() abort dict " {{{1
  if localtime() - self.time > 1
    let self.time = localtime()
    let self.list = [expand('%:p')]
  endif
endfunction

I think you can safely commit this fix
best Cristiano

**Comment by lervag** [comment]
I already did that, actually. So if you update vimtex it should be resolved. Can you verify this?

**Comment by lervag** [comment]
Also, please note that it is much easier to read your posts if you use proper formatting. You can read the github markdown formatting guide here:
https://guides.github.com/features/mastering-markdown/

**Comment by cridemichel** [comment]
I apologize for not being used to markdown, I will do it

best C.

**Comment by cridemichel** [comment]
yes thank you!

**Comment by lervag** [comment]
> I apologize for not being used to markdown, I will do it

Great! And I'm happy to hear that the issue is resolved :)
