### ISSUE TITLE
Point minivimrc to own root

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1442]
**Is your feature request related to a problem? Please describe it.**
Just wanted to do a clean test of the behaviour from #1440 and wanted to use the files in `test/issue/1440` for it (including the `minivimrc` so  my own doesn't change the test), but as I am using `vimplug` and not `bundle`(?) it won't work

**Describe the solution you'd like**
point to repository root, eg `../../../` if this is possible

**Comment by lervag** [comment]
Ah. The `test/issues/NUMBER` directories are actually mostly for myself during testing. I know that the paths like `~/.vim/bundle/...` are not the right paths for everyone else. But if that is the case, then it should really be very simple for you to just change those paths.

However, I think your suggested solution is good. I could perhaps do a hefty search and replace throughout the `test/issues` files...

**Comment by lervag** [comment]
Done. Thanks, even though this is not so important for me, I understand that it is convenient for you and others who might want to run tests on your own systems.
