### ISSUE TITLE
issue template: request english log

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1444]
**Is your feature request related to a problem? Please describe it.**
It would be very useful, to provide all logs in english when reporting issues

**Describe the solution you'd like**
Tell users to `export LANGUAGE=en_US.UTF-8`, when generating logs

**Additional context**
This allows override of any other language setting as described in the [GNU gettext manual](https://www.gnu.org/software/gettext/manual/html_node/Locale-Environment-Variables.html)

**Comment by lervag** [comment]
Thanks, this is closed by #1445.
