### ISSUE TITLE
Multi-line options throw off syntax highlighting

### ISSUE THREAD

**Issue by maaattes** [lervag/vimtex#1446]
**Describe the issue**
If a command has a lot of options, I often split those options across multiple lines like [so](https://tex.stackexchange.com/a/155670/133359). This often throws off syntax highlighting. Usually that does not bother me much. But when using common environment variables like `$HOME`, syntax highlighting is broken till the next command. See screenshot below. I'm wondering if there's any way to fix this?

![syntax highlighting thrown off](https://user-images.githubusercontent.com/52661914/62714292-92f6f280-b9fe-11e9-8403-c8321cb704f3.png)

Minimal .vimrc:
  ```vim
  " ~/.vimrc
  set nocompatible
  let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/bundle/vimtex/after'
  filetype plugin indent on
  syntax enable
  ```

MWE:
```tex
\documentclass[
    a4paper,
    fontsize=11pt,
]{scrartcl}

\usepackage{pdfpages}

\begin{document}
\include{$HOME/Text_A}
Text Text Text Text
\includepdf[%
    pages=-,
    nup=2x2
]{$HOME/test/folder/Attachment_B}
Text Text Text Text
\end{document}
```

**Comment by lervag** [comment]
Thanks, should be fixed now.

**Comment by maaattes** [comment]
Seems to be broken again after the last update :(

**Comment by lervag** [comment]
It is not broken for me, so please provide a reproducible example.

**Comment by maaattes** [comment]
Hm, after changing language to `en_US.utf8` in my vimrc (and back to my language `de_DE.utf8`) it suddenly worked Oo I apologize for the inconvenience.

**Comment by lervag** [comment]
Strange. If you should happen to find a way to reproduce the problem e.g. by changing locale, let me know. In the meantime, I'll assume this works.
