### ISSUE TITLE
wrong unicode characters in completion preview window

### ISSUE THREAD

**Issue by cridemichel** [lervag/vimtex#1447]
**Describe the issue**
A clear and concise description of the issue.

**Steps to reproduce**

- Create a minimal vimrc file, e.g.:

  ```vim
  set nocompatible
  let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/bundle/vimtex/after'
  filetype plugin indent on
  syntax enable
  ```

- Create a minimal LaTeX file, e.g.:

  ```tex
  \documentclass{minimal}
  \begin{document}
  Hello world!
  \end{document}
  ```

- Start vim with `vim --servername VIM -u minivimrc minimal.tex`

- Start neovim with `nvim -u minivimrc minimal.tex`

- Provide set og keys or command to reproduce the issue

- Describe both the expected and the observed behaviour

- *Note*: if relevant, include the content of your `.latexmkrc` file

**Output from VimtexInfo**

**Comment by lervag** [comment]
If you update the original post with a description that adhers to the template, then feel free to reopen.

**Comment by cridemichel** [comment]
yes gimme time to complete it :-)
