### ISSUE TITLE
vimtex opens two windows with zathura

### ISSUE THREAD

**Issue by wasaCheney** [lervag/vimtex#1460]
**Issue**

When I set zathura as default pdfviewer, open a tex file from vim, and run `\ll`, then two zathura windows are opened. Something like [issue #1017](https://github.com/lervag/vimtex/issues/1017).

But if I close these two windows and run `\ll` again, it becomes normal: one zathura window is opened.

All of my test are attached here:
![Screenshot from 2019-08-27 10-54-05](https://user-images.githubusercontent.com/18375090/63737489-2ebaa680-c8b9-11e9-9797-1d0cbab53737.png)

**minimal.vim**
The only thing I add to vimrc file:
`let g:vimtex_view_method = 'zathura'`

**minimal.tex**
```tex
\documentclass{article}
\begin{document}
Hello world!
\end{document}
```

**Commands/Input**
Open the tex file from vim, then execute `\ll`

**Observed Behaviour**
Two zathura windows are opened! the first one is without highlight, and the second one with highlight

**Expected Behaviour**
Only one zathura window should be opened.

**Output from VimtexInfo**
```
System info
  OS: Fedora release 28 (Twenty Eight)
  Vim version: VIM 8.1 (1-119)
  Has clientserver: false

vimtex project: minimal_test
  base: minimal_test.tex
  root: /mnt/article/vimtex_bugReport
  tex: /mnt/article/vimtex_bugReport/minimal_test.tex
  out: /mnt/article/vimtex_bugReport/minimal_test.pdf
  log: /mnt/article/vimtex_bugReport/minimal_test.log
  aux: /mnt/article/vimtex_bugReport/minimal_test.aux
  fls: /mnt/article/vimtex_bugReport/minimal_test.fls
  compiler: latexmk
    backend: jobs
    output: /tmp/v5qCWqK/4
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: process 22801 run
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"/usr/bin/vim --servername  --remote +\%{line} \%{input}\" \%S"' -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'minimal_test.tex'
  viewer: Zathura
    xwin id: 0
    process: 
      pid: -
      cmd: zathura -x "/usr/bin/vim --servername  --remote-expr \"vimtex#view#reverse_goto(%{line}, '%{input}')\"" --synctex-forward 2:1:'/mnt/article/vimtex_bugReport/minimal_test.tex'  '/mnt/article/vimtex_bugReport/minimal_test.pdf' >/dev/null 2>&1 &
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
  document class: article
```

**Comment by lervag** [comment]
Does it work if you use `vim --servername VIM ...` when you start Vim?

**Comment by wasaCheney** [comment]
Thanks for your reply @lervag I tried as you said, but failed:
1. Command failed: vim --servername VIM ... because my vim do not support clientserver
1. Try to install vim from source (with clientserver support), but error:
  ```
  no terminal library found
  checking for tgetent()... configure: error: NOT FOUND!
  ...
  You need to install a terminal library; for example ncurses.
  Or specify the name of the library with --with-tlib
  ```
1. Try to install ncruses, but I got
  ```
  Package ncurses-6.1-4.20180224.fc28.x86_64 is already installed, skipping
  ```
  and I could find some related file in `/usr/lib64`, such as: libncurses.so.6.1, libncursesw.so.6.1
1. Try to set `--with-tlib ncurses`, but error: 
  ```
  checking for linking with ncurses library... configure: error: FAILED
  ```
1. I get puzzled @_@; Maybe I should first go to vim for help.

**Comment by lervag** [comment]
I can't say directly how to properly install Vim on your system, but perhaps [this post](https://michaelheap.com/installing-vim-with-clientserver/) is relevant?

Often, it might suffice to install `gvim` instead of `vim`, since it typically
includes terminal Vim with clientserver alongside the gui version.

**Comment by wasaCheney** [comment]
Oh, yes! gvim + vimtex + zathura works just as epxected! 
It is enough for me at present, though I am still curious about the issue. The world becomes fun again.
Thank you very much! @lervag

**Comment by qqlovekerry** [comment]
Hi,
I also encountered the same problem on Ubuntu 18.04LTS. I have installed GVim in the software and if I type `vim --version` in the terminal, `+clientserver` can be found. But if I use `vim --servername vim` to open a tex file. The zathura still have two windows opened. The first one is without highlight, and the second one with highlight. Did I miss something? Could you please tell me how to fix this problem?
@lervag Any help would be much appreciated!

**Comment by lervag** [comment]
My first thought is that you do not have `xdotool`. Or that you are running on Wayland. If first, then install `xdotool` and things should work. If second, then things will not work, sorry. The `zathura` features rely on `xdotool` to work smoothly, and this is not available on Wayland now.

If this did not help, please take the time to open a new issue with a full description.

**Comment by qqlovekerry** [comment]
Hi @lervag , thanks very much for the reply! 
I have installed `xdotool` before and I have re-checked that it is installed by `apt install xdotool`.
I log in my Ubuntu 18.04 by the default option rather than `Ubuntu on Wayland`, so maybe I am running on Xorg. But I am sorry I did not know much about Wayland and the X servers. Could you please tell me how check whether I am running on Wayland?

**Comment by lervag** [comment]
See [here](https://unix.stackexchange.com/questions/202891/how-to-know-whether-wayland-or-x11-is-being-used).

**Comment by qqlovekerry** [comment]
Hi @lervag , 
Thanks! The problem should be caused by Wayland. I have tested on two PCs with Ubuntu 18.04LTS.
On one machine, I can find two users, the user of my name shows the type x11, but the user `gdm` shows type wayland. On another machine, I only find the user of my name, which uses the type x11, on this machine, it is OK to use vimtex with zathura, only one window pops up.
I do know why the first Ubuntu has two users logged in. But I think the reason which caused by the problem has been found.
Thanks very much again for your help!
