### ISSUE TITLE
A general question about autocompletion with coc.nvim

### ISSUE THREAD

**Issue by alucardkoten** [lervag/vimtex#1469]
How to configure coc.nvim or vimtex so that it only autocompletes for Latex commands but not for words. I have already installed coc-vimtex plugin.

**Comment by lervag** [comment]
This is not a vimtex related question, but a coc related question. So you are asking in the wrong forum.

I think what you need to do is to set something like:

```json
  "coc.source.around.enable": false,
  "coc.source.buffer.enable": false,
```

In your `coc-settings.json` file. This will disable these sources completely, so it might not be exactly what you want. I don't know the specific syntax to only disable for a given filetype. @chemzqm would know, and if you ask at the coc.nvim issue board, you would probably get an answer sooner.

**Comment by alucardkoten** [comment]
Thank you for your reply!

**Comment by lervag** [comment]
No problem, I hope it helped.
