### ISSUE TITLE
Treating \paragraph and \subparagraph as sections in ToC and ]]/[[ movement?

### ISSUE THREAD

**Issue by hwagyesa** [lervag/vimtex#1476]
The current version of the plugin doesn't seem to treat \paragraph and \subparagraph labels as sections in their own right, in that they don't seem to be processed to appear in the ToC window, even if they are in the .aux file, and they are skipped when using ]]/[[ to navigate between sections. I wonder if this is an intentional behavior, or whether the behavior could be amended to include these two environments as sections.

I have looked through the help documentation and it seems that this behavior could be added in part within the existing framework via a `vimtex_toc_custom_matcher`; I apologize but after a quick look at the source code I myself wasn't able to determine how to extend the current behavior using this interface.

**Comment by lervag** [comment]
> I wonder if this is an intentional behavior, ...

Well, yes, sort of. `\paragraph`s are not included in the rendered ToCs either. I personally tend to think of `\paragraph` as a paragraph heading macro, not as a sectioning macro.

> ... or whether the behavior could be amended to include these two environments as sections.

Yes, it would be possible to add this feature, but I'm not really sure it is necessary/worth it. You propose the following changes:

1. Add `\(sub)paragraph` to vimtex ToC, and

2. Let `[[` and `]]` motions also move to `\(sub)paragraph`s.

Personally, I think point 2 makes more sense than point 1.

**Comment by hwagyesa** [comment]
> \paragraphs are not included in the rendered ToCs either.

That's correct, but it is only a default behavior; using `\setcounter{tocdepth}{ ... }` with argument 4 or 5 will cause the rendered ToC to include paragraphs and subparagraphs (resp.). Here is a MWE:
```
\documentclass[11pt]{article}
\setcounter{tocdepth}{5}
\begin{document}

\tableofcontents 
\section{A section}
\subsection{A subsection}
\subsubsection{A subsubsection}
\paragraph{A paragraph}
\subparagraph{A subparagraph}

\end{document}
```
My understanding based on some documentation I have read (e.g. [on Overleaf](https://www.overleaf.com/learn/latex/Sections_and_chapters)) is that most standard classes indeed use `\(sub)paragraph` for sectioning. I myself am using it for organizing distinct elements of a proof; having vimtex support navigation through these sections would be helpful in paralleling the rendered ToC structure. Thanks for your consideration.

**Comment by lervag** [comment]
Ok. I can include this. There is already a support for the `tocdepth` counter, in part, and I think the default setting would ignore paragraphs in the ToCs. I'll work on it when I get the time. In the meantime, I'm pushing some example files to work with.

I've updated the `]]` motions to include the `\paragraph` commands, please test and see if it works as expected.

**Comment by lervag** [comment]
Ok, I think this should work for ToC as well now. You need a high tocdepth, though. Try to increase it with `+` and `-`, or set the `tocdepth` key in the config.

**Comment by hwagyesa** [comment]
Thanks, it works great.

**Comment by lervag** [comment]
No problem! There might be reactions to this change, if so, I hope it is OK if I notify you in future discussions.

**Comment by hwagyesa** [comment]
Thanks, please do.
