### ISSUE TITLE
Zathura synctex is buggy with multiple-files projects

### ISSUE THREAD

**Issue by emanuelealiverti** [lervag/vimtex#1478]
Thanks for your amazing work with vimtex. I'm using it for a while and I'm very happy with it. 
Recently I have observed a some bugs with zathura, vimtex and multi-file documents.
It could also be an `nvr` issue, but at this point I'm not able to distinguish.

**Issue**
Zathura synctex is buggy with multiple-files projects
**minimal.vim**

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'lervag/vimtex'
call plug#end()

" Vimtex options go here
let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_progname = 'nvr'
```

**minimal.tex**

```latex
\documentclass{article}
\usepackage{lipsum}
\begin{document}
\input{test1.tex}
\end{document}
```

**test1.tex**

```latex
This is some test text.
\begin{equation}
	2+2 = 4
\end{equation}


\section{Part1}
\lipsum[1-2]
\section{Part2}
\lipsum[3-4]
```

**Commands/Input**
`nvim -u minimal.vim minimal.tex`. Compile with `\ll`. `CTRL+click` on the pdf document at Part1, *twice*.

**Observed Behaviour**
On the first click, goes to the right location of the document.
On the second (and following ones), goes at the bottom of `part1.tex`.
If the document is closed and then reopend with `\lv`, everything works as expected.

**Expected Behaviour**
Go to line 8 of `part1.tex` on any click.

**Output from VimtexInfo**
```
System info
  OS: Ubuntu 16.04.6 LTS
  Vim version: NVIM v0.3.8
  Has clientserver: true
  Servername: /tmp/nvimJwfRsY/0

vimtex project: main
  base: main.tex
  root: /home/meme/GIT/issue
  tex: /home/meme/GIT/issue/main.tex
  out: /home/meme/GIT/issue/main.pdf
  log: /home/meme/GIT/issue/main.log
  aux: /home/meme/GIT/issue/main.aux
  fls: /home/meme/GIT/issue/main.fls
  source files:
    main.tex
    test1.tex
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimJwfRsY/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    pid: 9444
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"nvr --servername /tmp/nvimJwfRsY/0 --remote +\%{line} \%{input}\" \%S"' -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'main.tex'
  viewer: Zathura
    xwin id: 60817411
    process: 
      pid: -
      cmd: zathura -x "nvr --servername /tmp/nvimJwfRsY/0 --remote-expr \"vimtex#view#reverse_goto(%{line}, '%{input}')\"" --synctex-forward 1:1:'/home/meme/GIT/issue/main.tex'  '/home/meme/GIT/issue/main.pdf' >/dev/null 2>&1 &
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: article
  packages:
    expl3
    lipsum
    xparse
```

**Comment by lervag** [comment]
Confirmed, but I am sorry to say I don't find a solution. I think the problem is with `nvr`, because this works as expected in Vim.

Note, as a workaround, you could use

```vim
let g:vimtex_view_automatic = 0
```

and always open the viewer manually. I like that myself, and it allows a little bit better control over the remote commands (use `--remote-expr` instead of `--remote`.

I'm closing, since I think this has to be solved on the neovim-remote side of things.

**Comment by emanuelealiverti** [comment]
Thanks a lot for your time. Opening the viewer manually is indeed a great workaround.
I will open the issue for `nvr`

**Comment by lervag** [comment]
No problem, happy to hear you like the workaround. It would be nice to follow the (possible) progress on the nvr issue, so I would be happy if you could link it here.

**Comment by emanuelealiverti** [comment]
Sure. I have opened an issue [here](https://github.com/mhinz/neovim-remote/issues/116)
