### ISSUE TITLE
Delimiter matching called on floating buffer

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1481]
*(I apologize for this vague issue; I'm hoping for general feedback to be able to refine it iteratively. The reproducing example is also far from minimal at the moment.)*

I have an issue where neovim opening a floating buffer from inside a TeX file is extremely slow; looking at the profile, it looks like vimtex's `get_matching_delimiters` is called everytime a new floating buffer is opened (using `nvim_open_win`) or changed (using `win_gotoid`). The new buffer  (showing documentation for completions returned by a language server) does _not_ have the filetype `tex`; the buffer contents are only a few characters of plaintext.

(Using vim 8.1 or disabling vimtex does not show this behavior.)

The reason seems to be that (only!) in this setting, the (rather expensive) function `s:get_matching_delim()` is fired (twice) on every `<down>` key with an open popupmenu completion on `\ref{`, but not on `<c-n>`. (With vim 8.1, this function is not fired on either key.)

Do you have any idea what could be causing this, or how I could trace why this function is called?

**Comment by clason** [comment]
This turned out to be an issue with the plugin that calls `nvim_open_win`; sorry for the noise!

**Comment by lervag** [comment]
No problem!
