### ISSUE TITLE
add completion for glskeys

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1489]
**Is your feature request related to a problem? Please describe it.**

I would like to have completion for selfdefined glossarykeys

**Describe the solution you'd like**

keys added by
```tex
\glsaddkey
 {maccusative}% key
 {}% default value
 {\glsentrymaccusative}% no link cs
 {\Glsentrymaccusative}% no link ucfirst cs
 {\glsmacc}% link cs
 {\Glsmacc}% link ucfirst cs
 {\GLSmacc}% link all caps cs
```

example from [here](https://tex.stackexchange.com/questions/178725/how-to-use-glossaries-for-different-grammatical-acronym-forms)

**Additional context**

the first entry would be the best to be shown in the autocompletion for the commands argument  with a failover to the second one, but the first step would probably be an regex spanning lines ignoring comments which seems to be not that easy to me

**Comment by lervag** [comment]
It would be very helpful if you could provide a minimal example for this. That is:

1. A full minimal LaTeX source.
2. Preferably: A minimal vimrc file to go along with what you think would be natural settings.
3. As for a regular issue: provide steps to "reproduce".

I'm aware it feels strange with number 3, but the point is for me to understand the full context. This makes it much easier for me to create a working set of test files and as such, to properly implement the desired feature.

**Comment by 927589452** [comment]
> It would be very helpful if you could provide a minimal example for this. That is:
> 
>     1. A full minimal LaTeX source.
I would just enhance the bib2gls example with this, would that be ok?
> 
>     2. Preferably: A minimal vimrc file to go along with what you think would be natural settings.
Will have to think about that
>     3. As for a regular issue: provide steps to "reproduce".

The "flow" I would expect would be:

go to insert mode
start typing `\gls<c-x><c-o>`
get `glsentrymaccusative` and `glsmacc` as additional completion suggestions
upon completing to `glsmacc{` for example
enter `<c-x><c-o>`
start `bib2gls` completion and suggest all gls entries and fill the preview of the popup with the entry with the key `maccusative`, fallback to the key defined in the default value, if there is one, empty preview or warning if none is defined

**Comment by lervag** [comment]
> I would just enhance the bib2gls example with this, would that be ok?

Instead of pushing a minor PR, I think it would be better to do: Given test files for #1474, with the following addition, and then give a listing with  ```` ```tex ... ``` ```` where you specify the changes.

> go to insert mode
> start typing \gls<c-x><c-o>
> get glsentrymaccusative and glsmacc as additional completion suggestions
> upon completing to glsmacc{ for example
> enter <c-x><c-o>
> start bib2gls completion and suggest all gls entries and fill the preview of the popup with the entry with the key maccusative, fallback to the key defined in the default value, if there is one, empty preview or warning if none is defined

I'm sorry, but I don't understand what you write here. Can you please clean up, add proper punctuation, capital letters, etc? Perhaps you want a list, if so, use proper markdown formatting (e.g. [see here](https://guides.github.com/features/mastering-markdown/)). I'm not trying to be a pedant, I seriously just don't understand the proposed flow.

**Comment by 927589452** [comment]
updated the flow @lervag

**Comment by lervag** [comment]
Thanks! Much clearer now.

I think a good way to proceed now is to separate the test files into `tests/feature/completion/gls/...` and to create a full set of tests here for all of the `gls` completion stuff.

**Comment by 927589452** [comment]
maybe the "full set" should be described before

**Comment by 927589452** [comment]
and I would suggest to derive the parsing for standard `gls` completions from this one as for example the `\glspl` like commands can be defined as
```
\glsaddkey
 {plural}% key
 {}% default value
 {\glsentryplural}% no link cs
 {\Glsentryplural}% no link ucfirst cs
 {\glspl}% link cs
 {\Glspl}% link ucfirst cs
 {\GLSpl}% link all caps cs
```
AFAIK

**Comment by lervag** [comment]
Hmm. I've looked into this some more now. Basically you want two things:

1. `\glsaddkey` should corresponding new commands for command completion.
2. The added commands should improve the `\gls...{` completion to show relevant context.

The relevant documentation for this is section 4.3.1 in [the glossaries manual](http://texdoc.net/texmf-dist/doc/latex/glossaries/glossaries-user.pdf).

So, this feature request is quite complex. I'm curious if a simpler version is OK, where:

1. I add commands for command completion from `\glsaddkey` commands, and
2. Allow all variants of `\gls` commands, e.g. by changing the completion pattern to `\v\\(gls|Gls|GLS)\w*`. Thus allowing completion of glossary entries everywhere, but it would lack the smart context feature.

The question is: how "important" or "convenient" would this smart context feature be? I would guess it is not really that important, and that the important part is to allows glossary completion in all glossary commands and perhaps to complete all glossary commands.

**Comment by lervag** [comment]
Bump. It would be useful to get an answer here. Else I might close this issue due to lack of activity/interest.

**Comment by 927589452** [comment]
I think the easier version seems more sensible; if the need arises of the smart context this could be implemented later.

**Comment by lervag** [comment]
Thanks! I'll see if I'll get some time to work on this in not too long, then. :)

**Comment by lervag** [comment]
I've implemented a first version now. Could you please test if it works OK?
