### ISSUE TITLE
Autocomplete xparse-style definitons

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1490]
**Is your feature request related to a problem? Please describe it.**

Commands defined by `\providecommand` or `\DeclareExpandableDocumentCommand` are currently not available in the autocompletion

**Describe the solution you'd like**

expand the collection regexp to include those

**Additional context**

See #1488

**Comment by lervag** [comment]
Thanks! Lets continue the discussion and progress in #1488. I'll close this.
