### ISSUE TITLE
Extend the gf navigation funcationality for files in TEXINPUTS, BSTINPUTS, BIBINPUTS environment variables as well as \graphicspath

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1493]
**Is your feature request related to a problem? Please describe it.**
This feature request is to enhance the `gf` navigation for files without a full relative path in the latex source document.  The present `gf` functionality works great to quickly navigate to the `input`ted or 
`include`d files. 

However, there exist situations where I need to move sections of text around.  Imagine that in `main.tex`, we have the following input lines `\input{method_materials/concept.tex}`   `\input{method_materials/implementation.tex}`. For reinforcing the realistic nature of this feature request, also consider that  we have `\input{backmatter/references.tex}` and `\input{backmatter/acronyms.tex}`.  From `main.tex`, the `gf` command works great in editing these files.  However, after a draft-manuscript review with my supervisor & co-authors, if it is decided that the `concept.tex ` belongs to the introduction section, then I need to move the file to the folder titled introduction. Not only that, I need to also change the input line to `\input{introduction/concept.tex}`. Similarly, after rejection by one journal, if we decide to resubmit the manuscript to a different one requiring acronyms in the front section, to keep the logical structure of the document while preparing the new draft, I need to move the `acronyms.tex` to the `frontmatter` folder. Not only that, I need to edit the input line to be `\input{frontmatter/acronyms.tex}`. 

This procedure is tedious and error-prone, for a long document whose structure changes as the draft evolves. 

The `TEXINPUTS`, `BSTINPUTS`, `BIBINPUTS` environment variables and the `\graphicspath` command all come together to save the day. To give an example that mitigates the above situation, I simply include an additional line in my latexmkrc.

`ensure_path( 'TEXINPUTS', './preamble//', './frontmatter//', './introduction//, './method_materials//', './backmatter//' );`

The above line provides a platform independent solution and sets the `TEXINPUTS` environment variable for both MikTeX and TexLive (have tested it on Linux, Mac & Windows).  Now, I can keep my folder structure logically clean and separate.  I now simply have the following lines in the appropriate places in my `main.tex`

```
\input{concept.tex}
\input{implementation.tex}
\input{references.tex}
\input{acronyms.tex}
```
The TeX engine shall find the right files from the correct path during document compilation. If I need to move the acronyms file to the frontmatter folder, I simply do so and rearrange the `\input` sequence. Everything just works as expected without renaming the absolute/relative path to the input file. If tomorrow, we decide to rename the underlying folders to something else, the `main.tex` does not change, which is great.

>
The problem now is that vimtex's `gf` command does not work anywhere on the line now, which is quite frustrating.

**Describe the solution you'd like**
For the new `gf` algorithm, perhaps use one of the following:
a. Query the shell for `TEXINPUTS` and friends 
b. Parse `latexmkrc`/`.latexmkrc` in the project root (might need to hook into vimtex's root-searching logic)
c. Consider a magic comment like % TEXINPUTS near the modelines
d. Maybe something else!

**Comment by lervag** [comment]
I could query the `$TEXINPUTS` variable, but that would be more of a global solution, since one would (probably) not change this variable between projects. Parsing `latexmkrc` would be possible, but cumbersome. As such, I think your option c) is the best alternative.

>  d. Maybe something else!

Except, I'm curious, could a solution be to simple glob for the file from the root and upwards? E.g., consider:

```
.
├── input-one
│   └── input-a.tex
├── input-two
│   └── input-b.tex
└── main.tex
```

In this setup, `\input{input-a.tex}` in `main.tex` could lead to `glob(b:vimtex.root . '/**/' . a:fname)`, which will result in `input-one/input-a.tex`.

This is _not_ perfect, e.g. if you have multiple files with same names in different directories. But it could be better than nothing, and probably solve most of your issues?

**Comment by lervag** [comment]
I've pushed my suggested globbing solution. Please test it and let me know what you think.

**Comment by krishnakumarg1984** [comment]
@lervag I am sorry to report back that the fix did not work. I get the following error message that I report verbatim here.

> E447: Cannot find file "input" in path

**Comment by lervag** [comment]
Could you provide an example where it doesn't work? For me, it works well on the given test files (see `test/issues/1493` in the repo).

Note, at the moment, the globbing looks for the filename exactly. But `\input{input}` could also lead to `input.tex`, right?

**Comment by lervag** [comment]
I've made a minor update, could you see if it solves your issue?

**Comment by krishnakumarg1984** [comment]
@lervag No. It doesn't work yet. I think the missing aspect is that `ensure_path( 'TEXINPUTS', './preamble//');` within `latexmkrc` shall get the `preamble` directory and all its subdirectories within. This is my directory structure.

```
preamble/
├── custom_cmds_for_packages
│   ├── custom_cmds_pkg_amsmath.tex
│   ├── custom_cmds_pkg_biblatex.tex
│   ├── custom_cmds_pkg_caption.tex
│   ├── custom_cmds_pkg_catchfile.tex
│   ├── custom_cmds_pkg_cleveref.tex
│   ├── custom_cmds_pkg_datetime2.tex
│   ├── custom_cmds_pkg_diffcoeff.tex
│   ├── custom_cmds_pkg_draftwatermark.tex
│   ├── custom_cmds_pkg_expl3.tex
│   ├── custom_cmds_pkg_gitinfo2.tex
│   ├── custom_cmds_pkg_glossaries.tex
│   ├── custom_cmds_pkg_graphicx.tex
│   ├── custom_cmds_pkg_hyperref_hypersetup.tex
│   ├── custom_cmds_pkg_ieeetrantools.tex
│   ├── custom_cmds_pkg_ltxcmds.tex
│   ├── custom_cmds_pkg_microtype.tex
│   ├── custom_cmds_pkg_mleftright.tex
│   ├── custom_cmds_pkg_paralist.tex
│   ├── custom_cmds_pkg_showkeys.tex
│   ├── custom_cmds_pkg_siunitx.tex
│   ├── custom_cmds_pkg_todonotes.tex
│   ├── custom_cmds_pkg_totpages.tex
│   ├── custom_cmds_pkg_trimspaces.tex
│   ├── custom_cmds_pkg_ulem.tex
│   └── custom_cmds_pkg_xcolor.tex
├── custom_latex_cmds
│   ├── custom_battery_specific_cmds.tex
│   ├── custom_cmds_tabularmaterial.tex
│   ├── custom_genpurpose_cmds.tex
│   ├── custom_journal_specific_definitions.tex
│   └── custom_latex_settings.tex
├── glossary_definitions
│   ├── acronyms.bib
│   ├── acronyms.tex
│   ├── generic_symbols.bib
│   ├── greek_symbols.bib
│   ├── latin_symbols.bib
│   ├── thesis_acronyms.bib
│   ├── thesis_greek_symbols.bib
│   └── thesis_latin_symbols.bib
├── glyph_to_unicode_conversion
│   ├── convert_glyphs_to_unicode.tex
│   ├── glyphtounicode-cmr.tex
│   ├── glyphtounicode-ntx.tex
│   └── glyphtounicode.tex
├── load_pkgs_and_passoptions
│   ├── force_load_required_packages.tex
│   ├── load_conditional_gitver_related_pkgs_and_settings.tex
│   ├── load_font_and_math_pkgs_and_settings.tex
│   ├── load_hyperref_related_pkgs_and_settings.tex
│   ├── load_packages_and_settings.tex
│   ├── load_pkgs_and_settings_for_ieee_orcid.tex
│   ├── load_std_pkgs_and_settings.tex
│   ├── passoptions_to_packages.tex
│   └── unused_pkgs_and_settings.tex
└── preamble.tex
```



```
  source files:
    main.tex
    ./author_inputs_for_manuscript.tex
    preamble/glyph_to_unicode_conversion/glyphtounicode.tex
    preamble/glyph_to_unicode_conversion/glyphtounicode-cmr.tex
    preamble/glyph_to_unicode_conversion/glyphtounicode-ntx.tex
    preamble/glyph_to_unicode_conversion/convert_glyphs_to_unicode.tex
    preamble/load_pkgs_and_passoptions/force_load_required_packages.tex
    preamble/load_pkgs_and_passoptions/passoptions_to_packages.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_ltxcmds.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_amsmath.tex
    preamble/load_pkgs_and_passoptions/load_font_and_math_pkgs_and_settings.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_biblatex.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_diffcoeff.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_graphicx.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_ieeetrantools.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_microtype.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_mleftright.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_paralist.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_siunitx.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_xcolor.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_todonotes.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_ulem.tex
    preamble/load_pkgs_and_passoptions/load_std_pkgs_and_settings.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_expl3.tex
    preamble/load_pkgs_and_passoptions/load_conditional_gitver_related_pkgs_and_settings.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_totpages.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_catchfile.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_trimspaces.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_hyperref_hypersetup.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_glossaries.tex
    preamble/custom_cmds_for_packages/custom_cmds_pkg_cleveref.tex
    preamble/load_pkgs_and_passoptions/load_hyperref_related_pkgs_and_settings.tex
    preamble/load_pkgs_and_passoptions/load_packages_and_settings.tex
    preamble/custom_latex_cmds/custom_cmds_tabularmaterial.tex
    preamble/custom_latex_cmds/custom_battery_specific_cmds.tex
    preamble/custom_latex_cmds/custom_genpurpose_cmds.tex
    preamble/custom_latex_cmds/custom_latex_settings.tex
    preamble/preamble.tex
```

**Comment by lervag** [comment]
Could you create a new _minimal_ example where this does not work? It's not immediately clear to me from you preamble structure. Something like:

```
.
├── input-1.tex
├── latexmkrc
├── main.tex
└── subdir
    └── subsub
        └── input-2.tex
```

Please include the minimal content as well. This makes it much easier for me to understand the full context of your issue, and also to create a relevant test. With that, it will also be much easier to implement and fix this.

**Comment by krishnakumarg1984** [comment]
@lervag  Thanks a lot. Sorry for being a slouch on this. I have been trying to finish a paper (overdue by 1 year now :)) 
I shall do this at the earliest if you can leave this open for a couple of more weeks.

**Comment by lervag** [comment]
No problem, I'll leave it open until you add the example. Good luck on your paper (and I can easily relate on being late with papers, no worries!).

**Comment by lervag** [comment]
It helps me sleep at night if I can keep the issue count low, so I'll take the liberty of closing this issue. Feel free to reopen and update if you find the time to provide the asked for details. :)
