### ISSUE TITLE
Full support for biblatex: \autocite, \autocites and etc

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#1494]
The `\cite` command is handled properly, for example its content excluded from spellchecking process (as it should be).

Whereas biblatex provided `\autocite` command (and `\autocites`, [help on wikibooks](https://en.wikibooks.org/wiki/LaTeX/Bibliographies_with_biblatex_and_biber#Reference_Styles)) isn't excluded from spellchecking process and marked as BadWord.

Quotation from [biblatex manual](http://mirrors.mi.ras.ru/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf):

> **\autocite[\<prenote\>][\<postnote\>]{\<key\>}**
> In contrast to other citation commands, the `\autocite` command does not only
> scan ahead for punctuation marks following its last argument to avoid double
> punctuation marks, it actually moves them around if required. For example, with
> `autocite = footnote`, a trailing punctuation mark will be moved such that
> the footnote mark is printed after the punctuation. `\Autocite` is similar to
> `\autocite` but capitalizes the name prefix of the first name in the citation if
> the useprefix option is enabled, provided that there is a name prefix and the
> citation style prints any name at all.

**Comment by petRUShka** [comment]
I've just noticed that same problem holds for `\align` command which is supposed to yield non-text output and hence shouldn't be considered as region for spellchecking.

**Comment by lervag** [comment]
Could you provide a simple example for me to work on?

**Comment by petRUShka** [comment]
@lervag, I'm sorry that is probably my fault.

Because on minimal examples it works very well. I couldn't reproduce issue even with deep input and several main files.

I have quite complex text multi-file project with a lot of subfiles and etc. I have several main files in one project with common files. After I've marked all main files with with `.latexmain` it started to work as expected.

P.S.
**minimal.tex**
```tex
\documentclass{minimal}
\usepackage{biblatex}
\usepackage{amsmath}
\bibliography{minimal}

\begin{document}
Hello world!
\input{input}

\end{document}
```

**input.tex**
```
\cite{foo1999}
\autocite{foo1999}

\begin{align}
  f_{20} &= 1;\\
\end{align}

\begin{eqnarray}
  f_{20} &= 1;\\
\end{eqnarray}

\input{deep_input}
```

**deep_input.tex**
```
\cite{foo1999}
\autocite{foo1999}

\begin{align}
  f_{20} &= 1;\\
\end{align}

\begin{eqnarray}
  f_{20} &= 1;\\
\end{eqnarray}
```
```

**Comment by lervag** [comment]
You posted example files, which seems not to reproduce the problem. I believe the problem is related to which syntax packages are loaded. That is, I hypothesise that if you experience this, then check `:echo b:vimtex_syntax`, it will not contain an entry for `biblatex`.

As an example: If you consider the example you post and comment out the line with `\usepackage{biblatex}`, then reload vimtex/restart vim, the problem is reproduced.

In general, the detection of packages should work well. If you should have an example where it is not working as expected, then I'd be happy to work on it and improve.
