### ISSUE TITLE
Bug in path handling

### ISSUE THREAD

**Issue by concatime** [lervag/vimtex#1499]
This is a simple bug to describe.
To reproduce, create a folder named `#1` and create a tex file inside.
When I call `:VimtexView`, vimtex will replace `#1` by the name of the tex file!
```vim
" .local/bin/bintest
" #!/bin/sh
" echo "$@" > ~/logs
let g:vimtex_view_general_viewer = 'bintest'
```
```
cat ~/logs
# /home/issam/sample.tex/sample.pdf
```

**Comment by lervag** [comment]
Thanks, this should be fixed now.
