### ISSUE TITLE
[Fish shell] Editor freezes when compilation error happens

### ISSUE THREAD

**Issue by bel3atar** [lervag/vimtex#150]
When using the Fish shell, compilation errors nerver show up in VIM, the editor just hangs and I have to force close it.
Just try something like `\usepackage{foobar}` (assuming that foobar doesn't exist) to reproduce this issue.

**Comment by lervag** [comment]
I'm sorry, but I don't use the Fish shell, and so I will not be able to debug this particular issue. Unless anyone (you, @lahwaacz, @Rmano, ...?) are able to give enough hints to understand what needs to change to get this to work, I won't be able to fix it. If I can't fix it, I will close the issue as "won't fix".

**Comment by lahwaacz** [comment]
Given that the fish shell [is not POSIX compliant](https://en.wikipedia.org/wiki/Fish_(shell)#Syntax), I think that any attempt to support fish alongside bash is futile. As a personal rant towards fish, I'm unable to comprehend how could software one of whose main mottos is [Configurability is the root of all evil](http://fishshell.com/docs/current/design.html#conf) ever become so popular.

**Comment by lervag** [comment]
I wouldn't say that any attempt to support fish is futile, but it seems there might be a need for specialized code several places. If it is straightforward such as the last changes (see #148), then I think it is OK to implement. But I don't want the code to suffer much just to support the Fish shell.

Even though I agree that such a motto is incomprehensible, I will respect that people are different and that some people may enjoy a shell such as Fish. However, I don't, and as I mentioned in my first reply I don't know what it takes to fix this current issue. I am not going to install the Fish shell just to find out, either.. @bel3atar Thus to fix such issues as this one, I rely on contributions from users of the Fish shell.

Based on this, I've decided I'll close this issue now. The discussion may continue, but I think it is more appropriate that @bel3atar or others who want to use the Fish shell create a pull request. I will of course do my best to help and to answer to questions on how the code works, but the code should be relatively simple to understand (IMHO).
