### ISSUE TITLE
Callback errors when editing bib file

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1500]
Since very recently (I can try bisecting), I get errors when editing a bib file while continuous compilation is running.

Here are the steps to reproduce (files below):

1. `nvim -u minimal.vim test.tex`
2. `:VimtexCompile`
3. `<c-w c-n>`
4. `:e test.bib`
5.  make any change
6. `:w`

Results in
``` 
Error detected while processing function <SNR>36_callback_nvim_output[9]..vimtex#compiler#callback:
line    1:
E716: Key not present in Dictionary: compiler, 'silence_next_callback')
Error detected while processing function <SNR>36_callback_nvim_output[9]..vimtex#compiler#callback:
line    1:
E116: Invalid arguments for function get
Error detected while processing function <SNR>36_callback_nvim_output[9]..vimtex#compiler#callback:
line    1:
E15: Invalid expression: exists('b:vimtex') && get(b:vimtex.compiler, 'silence_next_callback')
Error detected while processing function <SNR>36_callback_nvim_output[9]..vimtex#compiler#callback:
line    1:
E716: Key not present in Dictionary: compiler, 'silence_next_callback')
Error detected while processing function <SNR>36_callback_nvim_output[9]..vimtex#compiler#callback:
line    1:
E116: Invalid arguments for function get
Error detected while processing function <SNR>36_callback_nvim_output[9]..vimtex#compiler#callback:
line    1:
E15: Invalid expression: exists('b:vimtex') && get(b:vimtex.compiler, 'silence_next_callback')
```

(This is with neovim master; I get different errors with vim 8.1.)

`minimal.vim`
  ```vim
  set nocompatible
  let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/bundle/vimtex/after'
  filetype plugin indent on
  syntax enable
  ```

`test.tex`

  ```tex
\documentclass{article}
\begin{document}
\nocite{*}                                                                                 
\bibliographystyle{siam}                                                                   
\bibliography{test}                                                                        
\end{document}                   
 ```

`test.bib`
```bibtex
@article{article,
  author  = {Peter Adams}, 
  title   = {The title of the work},
  journal = {The name of the journal},
  year    = 1993,
  number  = 2,
  pages   = {201--213},
  month   = 7,
  note    = {An optional note}, 
  volume  = 4
}
```

**Comment by lervag** [comment]
Hmm, I don' think this is a new bug, actually. In any case, I think it is fixed now.

**Comment by clason** [comment]
Yes, looks fixed indeed. Thank you very much for the quick fix!

(Weird that I only noticed it now, then; the steps are not so uncommon. Might have been exposed _in this situation_ by a recent change.)

**Comment by lervag** [comment]
No problem!

If you'd open a bib file from inside a tex file, things would have worked well before. But your report used the `<c-w><c-e>` mapping to open a new empty split first, and then open a bib file. This exposed a minor bug where the `b:vimtex` variable was set to an empty dictionary, and this lead to the present issue. I assume the reason you might not have seen it before may be because you typically open the bib file from within a tex file?

**Comment by clason** [comment]
Hmm, I don't think I did anything differently than usual... I might have been using tabs more often, but I've definitely been using splits before. Anyway, it's fixed now :)
