### ISSUE TITLE
How to change fold markers in g:vimtex_fold_types ?

### ISSUE THREAD

**Issue by slonik-az** [lervag/vimtex#1502]
I find default choice of fold markers `{{{` ... `}}}` quite bad for TeX/LaTeX.  Oftentimes nested commands end in `}}}` like `\emph{\textbf{\textsc{EXAMPLE }}}`. I routinely comment out such lines causing incorrect matching of fold markers.

I found `<<:` ... `:>>` to be a better choice of a fold marker pair for LaTeX. But I do not know how to set it in vimtex. Documentation does not provide any examples for `g:vimtex_fold_types` marker setting.

Any help is greatly appreciated.
Thanks,
--Leo

**Comment by lervag** [comment]
This should be possible now. Please see updated docs for explaining how to configure, if you still need to ask then I must do a better job of documenting...

**Comment by slonik-az** [comment]
Thank you a lot for quickly fixing the issue and updating documentation! I followed the instructions and It works perfectly.

**Comment by lervag** [comment]
No problem, happy to help.
