### ISSUE TITLE
Checkhealth needs to be updated after updating "vimtex_complete_bib" dictionary

### ISSUE THREAD

**Issue by timlag1305** [lervag/vimtex#1503]
**Issue**
:checkhealth in neovim errors out. This is due to a recent commit removing the `recursive` key from the `g:vimtex_complete_bib` dictionary.

`autoload/health/vimtext.vim` needs to either be updated to remove the check at line 23 or update it to remove the access of the `g:vimtex_complete_bib.recursive`

**minimal.vim**
N/A

**minimal.tex**
N/A
**Commands/Input**
`:checkhealth`

**Observed Behaviour**
```
  1                                                                                                                             
  2 health#vimtex#check                                                                                                         
  3 ========================================================================                                                    
  4   - ERROR: Failed to run healthcheck for "vimtex" plugin. Exception:                                                        
  5     function health#check[21]..health#vimtex#check[5]..<SNR>138_check_general, line 11                                      
  6     Vim(if):E716: Key not present in Dictionary: recursive && !executable('kpsewhich') 
```

**Expected Behaviour**
`:checkhealth` should not error out like that.

**Output from VimtexInfo**
N/A

**Comment by lervag** [comment]
Thanks for reporting!

**Comment by timlag1305** [comment]
No problem, thanks for the quick fix!
