### ISSUE TITLE
Disable spellcheck for the minted, lstlisting, etc

### ISSUE THREAD

**Issue by XVilka** [lervag/vimtex#1504]
Currently if spellchecking enabled vimtex doesn't isolate these environments from the spellchecking. Would be nice (if possible) to avoid the spellcheck for these.

**Comment by lervag** [comment]
Could you provide some clear examples? I've tried to reproduce, but for me, things seem to work quite well.

**Comment by XVilka** [comment]
@lervag see for example red highlighted words (and the extract from my vimrc on the right):
![image](https://user-images.githubusercontent.com/203261/66627654-000d4b00-ec2f-11e9-8fa8-20ec569760d2.png)

**Comment by lervag** [comment]
Ah, but this is not a bug. Comments in code are typically set to be highlighted. If you saved the content in the listing as a file and opened it, I suspect you get the same highlighting of bad spelled words.
