### ISSUE TITLE
Bug in s:find_closing in vimtex#parser#toc?

### ISSUE THREAD

**Issue by hwagyesa** [lervag/vimtex#1506]
**Issue:**

I found that `texorpdfstring` commands from hyperref are not stripped properly in the Vimtex TOC. Here is a MWE to see the behavior:

```
\documentclass{article}
\usepackage{hyperref}

\begin{document}

\tableofcontents

\section{abc $cx + d$}
aaa

\section{abc \texorpdfstring{$cx + d$}{cx + d}}
bbb

\end{document}
```

**Fix?**

After poking around in the source I was surprised to find that there is already a function `s:clear_texorpdfstring` included for seemingly this purpose. It seems to be not currently working, though. I found that if I change [one line here](https://github.com/lervag/vimtex/blob/e323c55e9669c1adb205295b06ec4463bae5b637/autoload/vimtex/parser/toc.vim#L660) from
```
let l:i2 = a:start - 1
```
to
```
let l:i2 = a:start
```
everything seems to work fine. Thus I am wondering if this fix could be quickly committed, or whether there is another functionality that I am breaking when I make this change to line 660 in `vimtex/parser/toc`. Thanks for your help.

**Comment by lervag** [comment]
Thanks! Both for reporting and proposing a fix. I could not find anything that breaks, so I think you probably found a good fix.
