### ISSUE TITLE
SumatraPDF and Windows Powershell: forward search not working, inverse search only with gVim

### ISSUE THREAD

**Issue by norbert-op** [lervag/vimtex#1508]
After repeated testing with the issue cited in #1495, I found that setting PowerShell as the terminal is causing forward searching to break.

**minimal.vim**

```vim
set shell=C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
set shellcmdflag=-command
set nocompatible
filetype plugin indent on
syntax on
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
let g:vimtex_view_general_options
	\ = '-reuse-instance -forward-search @tex @line @pdf'
	\ . ' -inverse-search "gvim --servername ' . v:servername
	\ . ' --remote-send \"^<C-\^>^<C-n^>'
	\ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
	\ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
	\ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
	\ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
```

**minimal.tex**
```tex
\documentclass{article}

\begin{document}
	This is my minimal .tex example.
\newpage
    Here's a second page of text.
\end{document}
```
**Steps to reproduce**

0. Disable plugins besides vimtex (I did this by moving them out of `~\vimfiles\pack\*\start`)
1. Run PowerShell and change directory to the location of minimal.vim and minimal.txt.
2. Run `vim --servername vim -u minimal.vim minimal.tex`
3. Type "\ll" to compile.
4. Alt-tab back to Vim, move down to second line, and type "\lv" for forward search. Nothing happens.
5. Scroll back to first page in SumatraPDF and double-click for inverse search. Error message about GVIM server.

2b. Run `vim --servername gvim -u minimal.vim minimal.tex`. This gets inverse search working.

2c. Run `gvim -u minimal.vim -U NONE minimal.tex`. Inverse search works, forward search still does nothing.

I'm hopeful that you can find a way to support PowerShell without breaking forward search for Command Prompt use. Automatic detection would of course be better than setting an option. Thanks for looking into it, and let me know if you need any further testing.

**Comment by lervag** [comment]
Thanks for following up on my suggestion for splitting the issues. First, I'm curious: Why are you changing the shell option? If there is no reason, then I think the simplest solution is for you to change back to default settings.

**Comment by leonorbert** [comment]
When I first started with Vim I was having problems passing commands to the shell. Those went away when I switched to PowerShell, though I don't remember exactly what they were. I've also been learning PowerShell and am starting to appreciate it's capabilities, so I may use it more in the future from Vim. But for now I can live without it if need be, at least for using Vimtex.

**Comment by lervag** [comment]
I've followed this up in #1507 for now. As long as we're on the "meta" level (choosing whether to fix it or "ignore" it), lets keep the discussion there. If I choose to implement fixes, then I'll come back to this particular issue as well.

**Comment by Konfekt** [comment]
Well, my bad, this only solves backward search which already works but only needed the replacement of `gvim` by `vim` if Vim is used in the terminal. 

Regarding forward-search, does anything change if only 
```vim
let g:vimtex_view_general_options
	\ = '-reuse-instance -forward-search @tex @line @pdf'
```
is used? 

To find out if it is due to wrong escaping of the path of the pdf file, is it a path that does not contain spaces or special symbols (not a hyphen, underline, digit or letter)? If it contains, then could you test for such a path?

**Comment by norbert-op** [comment]
This appears to be working fine under Windows 10 for @Konfekt, and is only a problem for me under Windows 8.1.

**Comment by lervag** [comment]
Ok, thanks. Does that mean you'll simply upgrade to Win 10?

**Comment by norbert-op** [comment]
No, I'll just use Win 8.1. My laptop hardware has problems with Win 10--I tried it and had to downgrade again.

**Comment by Konfekt** [comment]
Strange it is. You can [install](https://chocolatey.org/packages/powershell-core) the new powershell-core (version 6) independent of the Windows Version.

**Comment by norbert-op** [comment]
Yes, I do have PowerShell 6 also, so I don't think the problem lies there. I tried using it on some iterations without a change.

**Comment by Konfekt** [comment]
Oh well, I am out of luck, I hoped it was due to the missing slashes before `%f` and `%l`.

**Comment by Konfekt** [comment]
Check also the settings of sumatraPDF. Perhaps for some reason they are not updated to
```
      \ = '-reuse-instance -forward-search @tex @line @pdf'
      \ . ' -inverse-search "' . exepath(v:progpath) . ' --servername ' . v:servername
      \ . ' --remote-send \"^<C-\^>^<C-n^>'
      \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
      \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
```

**Comment by norbert-op** [comment]
Yes, I did check and update the settings after your last commit. The problem can't be with that or with my PowerShell settings, but must be some other hidden setting in Vim. As I've said, if I start Vim with `&shell=cmd.exe` then use `ShellToggle()` forward search responds normally. But if I start with `call ShellToggle()` in the `vimrc` then it doesn't respond. I'll leave it as a mystery.

(btw, I replaced ==# with ==? to ignore case in my `ShellToggle()` function)

**Comment by Konfekt** [comment]
The SumatraPDF viewer itself has an advanced settings entry in its menu bar (as in https://www.ghacks.net/2013/05/22/sumatra-2-3-introduces-advanced-settings/), where one can check whether the options from Vim have been passed correctly; perhaps they suffer alterations. This corresponds to the entry 
```
pattern used to launch the LaTeX editor when doing inverse search
InverseSearchCmdLine =
```
in https://www.sumatrapdfreader.org/settings.html

Speaking of an hidden setting, that should be impossible by using a minimal vimrc. On Linux there is `/etc/vimrc`, but on Windows I am not aware of it. Updating Vim could be worth a try. 

There is https://www.top-password.com/blog/windows-10-command-prompt-new-console-vs-legacy-console/ about the changes in `cmd` between Windows 8 and 10, but surely they do not touch the syntax.

**Comment by Konfekt** [comment]
For future reference: Shell escaping in Powershell requires extra work, but it seems that the following code from [vim-plug](https://github.com/junegunn/vim-plug)  has it done:

```vim
let s:TYPE = {
\   'string':  type(''),
\   'list':    type([]),
\   'dict':    type({}),
\   'funcref': type(function('call'))
\ }

let s:is_win = has('win32')

function! s:is_powershell(shell)
  return a:shell =~# 'powershell\(\.exe\)\?$' || a:shell =~# 'pwsh\(\.exe\)\?$'
endfunction

function! s:shellesc_cmd(arg, script)
  let escaped = substitute('"'.a:arg.'"', '[&|<>()@^!"]', '^&', 'g')
  return substitute(escaped, '%', (a:script ? '%' : '^') . '&', 'g')
endfunction

function! s:shellesc_ps1(arg)
  return "'".substitute(escape(a:arg, '\"'), "'", "''", 'g')."'"
endfunction

function! s:shellesc_sh(arg)
  return "'".substitute(a:arg, "'", "'\\\\''", 'g')."'"
endfunction

" Escape the shell argument based on the shell.
" Vim and Neovim's shellescape() are insufficient.
" 1. shellslash determines whether to use single/double quotes.
"    Double-quote escaping is fragile for cmd.exe.
" 2. It does not work for powershell.
" 3. It does not work for *sh shells if the command is executed
"    via cmd.exe (ie. cmd.exe /c sh -c command command_args)
" 4. It does not support batchfile syntax.
"
" Accepts an optional dictionary with the following keys:
" - shell: same as Vim/Neovim 'shell' option.
"          If unset, fallback to 'cmd.exe' on Windows or 'sh'.
" - script: If truthy and shell is cmd.exe, escape for batchfile syntax.
function! Shellescape(arg, ...)
  if a:arg =~# '^[A-Za-z0-9_/:.-]\+$'
    return a:arg
  endif
  let opts = a:0 > 0 && type(a:1) == s:TYPE.dict ? a:1 : {}
  let shell = get(opts, 'shell', s:is_win ? 'cmd.exe' : 'sh')
  let script = get(opts, 'script', 1)
  if shell =~# 'cmd\(\.exe\)\?$'
    return s:shellesc_cmd(a:arg, script)
  elseif s:is_powershell(shell)
    return s:shellesc_ps1(a:arg)
  endif
  return s:shellesc_sh(a:arg)
endfunction
```

**Comment by lervag** [comment]
Thanks for the info. I believe I've more or less successfully avoided this issue by instisting on using the _default_ shell on any given system (i.e. `sh` on Linux and MacOS and `cmd` on Windows). More or less everything (if not everything) that needs an external call in VimTeX now relies on the jobs APIs:

https://github.com/lervag/vimtex/tree/master/autoload/vimtex/jobs

with main interface here:

https://github.com/lervag/vimtex/blob/master/autoload/vimtex/jobs.vim
