### ISSUE TITLE
How to remap 'change in command' mappings?

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1509]
Thank you for the excellent plugin. Here's a small issue/request.

For commenting source code lines, I am using the [`tcomment`](https://github.com/tomtom/tcomment_vim) plugin. However, the mapping `cic` of vimtex with the `inline comment` mapping of `tcomment`.

Can you please provide some documentation to remap `vimtex's` `cic` functionality?

**Comment by lervag** [comment]
Is the problem that  `tcomment` maps `cic`, and so Vimtex does not map it? Or is it the other way around?

If it is the first, then you can fix it with the following addition in your vimrc file:

```vim
augroup vimrc
  autocmd!
  autocmd FileType tex xmap <buffer> ic <plug>(vimtex-ic)
  autocmd FileType tex omap <buffer> ic <plug>(vimtex-ic)
augroup END
```

**Comment by krishnakumarg1984** [comment]
@lervag Thank you. Perfect, the autocmd mappings work like a charm.

**Comment by lervag** [comment]
Great, happy to hear it.

**Comment by fbouchez** [comment]
Another work-around is to modify `tcomment` 'ic' into something else, so you can keep having both mappings.
Personnally, I added the following in my `.vimrc` (I chose 'i/' because '/' is the first letter in C-style inline comments /*  */)
```
" change the default 'ic' as it conflicts with vimtex's 'ic'
let g:tcomment_textobject_inlinecomment='i/'
```
