### ISSUE TITLE
Include PDF files in (YouCompleteMe) file name completion triggered by '\includegraphics{'

### ISSUE THREAD

**Issue by Quappas** [lervag/vimtex#1510]
**Is your feature request related to a problem? Please describe it.**
The command `\includegraphics{}` provided by the package `graphicx` allows figures saved in the PDF file format to be included. Using PDF figures is desirable due to their lossless scalability [1, 2].

I use vimtex together with YouCompleteMe (YCM). When i type '\includegraphics{' the YCM completion menu pops up. It contains suggestions for image files in formats like JPEG or PNG, but not for figures i saved in the PDF format.

[1] https://tex.stackexchange.com/questions/8532/is-eps-or-pdf-the-preferred-figure-format-when-typesetting-in-latex
[2] https://stackoverflow.com/questions/2889286/quality-for-images-in-latex-documents

**Describe the solution you'd like**
Include PDF files in the completion suggestions triggered by '\includegraphics{' (and displayed by YCM).

**Describe alternatives you've considered**
PNG etc. do not scale as well. SVG messes up figures I create in pyplot. `C-X C-F` is not as convenient and lists non-image files.

**Comment by lervag** [comment]
The `\includegraphics` command should already complete `pdf` files. So I think the problem is something else. Could you provide a minimal example as asked for in the issue template?

**Comment by Quappas** [comment]
Thanks for the answer. My bad, I had `set wildignore=...,*.pdf` in my vimrc to filter CtrlP search results, which apparently affects more plugins than I thought.

**Comment by lervag** [comment]
No problem! Good to hear it works now.
