### ISSUE TITLE
Error opening tex-file with vimtex added to neovim

### ISSUE THREAD

**Issue by thomas-haslwanter** [lervag/vimtex#1513]
**Issue**
When starting the file `minimal.tex` below, I get the following error message:
```
Error detected while processing function  vimtex#init[4]..SNR>62_init_state[1]..vimtex#state#init[9]..273[32]..vimtex#view#init_state[5]..vimtex#view#general#new":  
Line    3:
E684: list index out of range: 0
E15: invalid expression: split(g:vimtex_view_general_viewer)[0]
Error detected while processing function vimtex#init[4]..<SNR>62_init_state[1]..vimtex#state#init":                   
Line    9:
E171: Missing: endif
```  

**minimal init.vim**
```
set nocompatible
let &runtimepath  = '~/.config/nvim/pack/minpac/start/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/.config/nvim/pack/minpac/start/vimtex/after'
filetype plugin indent on
syntax enable

packadd minpac
call minpac#init()
call minpac#add('lervag/vimtex')
packloadall
```
The same error comes up if the first paragraph (which was taken from the instructions) is left away.

**minimal.tex**

  ```tex
  \documentclass{minimal}
  \begin{document}
  Hello world!
  \end{document}
  ```

The same error message appears when I start neovim with `nvim -u init.vim minimal.tex`

**Output from VimtexInfo**
E492: Kein Editorbefehl: VimtexInfo

(Translation: No Editor command: VimtexInfo)

**Environment**
Win64

- `checkhealth` reports no problems
- `VimtexCompileOutput` is not known by the system
- The command `nvim -v` results in

```
NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO
<img width="900" alt="vimtex_error" src="https://user-images.githubusercontent.com/1530437/66699816-1fb57980-ecea-11e9-866f-ed691f66d302.png">
_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
?bersetzt von appveyor@APPVYR-WIN

Features: -acl +iconv +tui
```

**Comment by lervag** [comment]
Don't use `minpack` in the minimal example. I.e., remove these lines:

```vim
packadd minpac
call minpac#init()
call minpac#add('lervag/vimtex')
packloadall
```

Is the problem still present?

**Comment by thomas-haslwanter** [comment]
Yes, it is there with tex-files (not otherwise)

**Comment by lervag** [comment]
I think the problem is that `g:vimtex_view_general_viewer` is not set. I agree this should not lead to a problem in itself, or at least give an understandable warning. Can you please test if your issue is resolved now? (I've pushed an update.)

Note, though, that you should set the `g:vimtex_view_general_viewer` on Windows, because I don't know a good default setting for this and have therefore not defined one.

**Comment by thomas-haslwanter** [comment]
Yes, that solved the problem.
I also wanted to thank you, for that incredibly quick and helpful response!!!
Thanks, Thomas

**Comment by lervag** [comment]
Great, happy to hear it works now and that you found my response helpful. Thanks for opening the issue!
