### ISSUE TITLE
lualatex option ignored - warning coming from tikz-feynman

### ISSUE THREAD

**Issue by tamasgal** [lervag/vimtex#1514]
**Issue**
Somehow the lualatex option seems to be ignored, which is indicated by a warning from the tikz-feynman package. I am not sure however if the warning is "real", in the sense that maybe tikz-feynman fails to recognise the lualatex option or whatever.

I have the following settings in my neovim.init, which usually works fine:

```
" vimtex
if uname == 'Linux'
    let g:vimtex_view_method = 'zathura'
elseif uname == 'Darwin'
    let g:vimtex_view_method = 'skim'
endif
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-pdf',
    \   '-lualatex',
    \   '-shell-escape',
    \   '-verbose',
    \   '-bibtex',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}
```

and here is an MWE:

```tex
%! TeX program = lualatex
\documentclass[tikz]{standalone}
\usepackage{tikz}
\usepackage{tikz-feynman}
\begin{document}
\thispagestyle{empty}

\begin{tikzpicture}
\draw [thick, ->] (0, 0) -- (3, 4);
\end{tikzpicture}

\end{document}
```

with the warnings:

```
1   test.tex|5 warning| Package tikz-feynman Warning: LuaTeX is required if you wish to have vertices automatically placed. You     can disable this warning by setting /tikzfeynman/warn luatex=false on input line 5.
  1 test.tex|5 warning| Package tikz-feynman Warning: Consider loading TikZ-Feynman with \usepackage[compat=1.1.0]{tikz-feynman}     so that you can be warned if TikZ-Feynman changes. on input line 5.
```

**Observed Behaviour**
A warning is shown, indicating that the document was not compiled with lualatex.

**Expected Behaviour**
No warning

**Output from VimtexInfo**

```
System info
  OS: Mac OS X 10.14.6 (18G103)
  Vim version: NVIM v0.4.2
  Has clientserver: true
  Servername: /var/folders/hf/bpq_1svj47j_c6gvvlxp0jg80000gn/T/nvimmwLXos/0

vimtex project: test
  base: test.tex
  root: /Users/tamasgal/tmp/lualatex
  tex: /Users/tamasgal/tmp/lualatex/test.tex
  out: /Users/tamasgal/tmp/lualatex/test.pdf
  log: /Users/tamasgal/tmp/lualatex/test.log
  aux: /Users/tamasgal/tmp/lualatex/test.aux
  fls: /Users/tamasgal/tmp/lualatex/test.fls
  tex program: lualatex
  compiler: latexmk
    backend: nvim
    output: /var/folders/hf/bpq_1svj47j_c6gvvlxp0jg80000gn/T/nvimmwLXos/1
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -pdf
        -lualatex
        -shell-escape
        -verbose
        -bibtex
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -lualatex
  viewer: Skim
  qf: LaTeX logfile
    config:
      packages:
        default: 1
      default: 1
  document class: standalone
  packages:
    epstopdf-base
    etexcmds
    everyshi
    graphics
    graphicx
    grfext
    ifluatex
    ifpdf
    ifxetex
    infwarerr
    kvdefinekeys
    kvoptions
    kvsetkeys
    ltxcmds
    pdftexcmds
    pgf
    pgfcomp-version-0-65
    pgfcomp-version-1-18
    pgfcore
    pgffor
    pgfkeys
    pgfmath
    pgfopts
    pgfrcs
    pgfsys
    shellesc
    tikz
    tikz-feynman
    trig
    xcolor
    xkeyval
```

**Comment by lervag** [comment]
Your files worked fine for me. I suspect there is something else wrong.

You only provided the "relevant" part of your vimrc here. Instead, could you try to create a minimal vimrc file as suggested in the [issue template](https://raw.githubusercontent.com/lervag/vimtex/master/.github/ISSUE_TEMPLATE/issue_report.md)? Note the suggested content in the comments.

In addition, after you open the `minimal.tex` file, then start compilation e.g. with `\ll`: you can inspect the actual compiler output with `\lo`. This might give some more relevant context for understanding the issue.

Finally, you set a lot of unnecessary options for latexmk. Try to use this instead:

```
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-shell-escape',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}
```

Here I've removed `-bibtex`, which should already be set by default. Further, `-pdf` and `-lualatex` are parsed from the TeX Directive. If you want to change the default engine, use `g:vimtex_compiler_latexmk_engines`. See the docs for an explanation to change the default.

**Comment by tamasgal** [comment]
Thanks @lervag I already tried the minimal setup but got the same error. Today I tested it on my Linux machine (latest ArchLinux roll-out) and it worked; then I updated the whole TeXLive distribution on my Mac (which included an update of the tikz-feynman package) and now it works.

Sorry for the noise!

**Comment by lervag** [comment]
No problem, I'm happy to hear it works now.
