### ISSUE TITLE
vimtex folding marker problem

### ISSUE THREAD

**Issue by slonik-az** [lervag/vimtex#1515]
I am using the latest vimtex commit on master (1db32d3) and it seems that vimtex does not recognize marker folds with text on the same line as the opening fold marker.

## Here is the MWE:
I am using custom markers. Here is the relevant `.vimrc` lines:

```
let g:vimtex_fold_enabled = 1
let g:vimtex_fold_types = {
      \ 'markers': {
      \  'open': '<<:',
      \  'close': ':>>',
      \ },
      \}
```

Below is the `foo.tex` file that has two folding regions -- one that works and one which is broken

```
\documentclass{article}
\begin{document}

Broken fold  %<<:
this fold is NOT recognize
by vimtex
%:>>

%<<:
this fold is recognized OK
by vimtex
%:>>

\end{document}
```

When an opening fold marker is on the line by itself preceded only by a comment character `%`  vimtex recognizes fold OK. But fold is broken if other text precedes the opening marker.

**Comment by slonik-az** [comment]
I forgot to mention that I am using vim-8.1 on macosx (MacVim).

**Comment by lervag** [comment]
Thanks. This should work now.

**Comment by slonik-az** [comment]
Thanks for a prompt fix. Works now as expected.
