### ISSUE TITLE
Make (at least a subset of) vimtex functionality available from within bib files

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1517]
I understand that vimtex's documentation states that it is not a `ftplugin` for `bib` files. 

It is so common a workflow to edit `bib` files when working on a latex project. Can at least a subset of functionality be made available from within `bib` files? The following should be harmless

- make the text objects available (particularly useful in 'symbols' bib file for `bib2gls`)
- syntax highlighting
- interface to the compiler (maybe all main file detection routines except the magic comments)
- indentation

I'd leave the sort-by-key, validation, linting etc  to specialised bib tools, but clearly one could argue that a latex plugin isn't complete with some bib support. (especially since vimtex has gone so far to support `listings, minted, subfiles` and other external packages)

**Comment by lervag** [comment]
Ok, first, sorry for responding to this so late!

> Can at least a subset of functionality be made available from within bib files? The following should be harmless

I'll respond to each separately.

> * make the text objects available (particularly useful in 'symbols' bib file for bib2gls)

This could be possible.

> * syntax highlighting

No, I don't want that. There is already a syntax plugin by Bernd Feige (see `:e $VIMRUNTIME/syntax/bib.vim`) that IMHO works quite well.

> * interface to the compiler (maybe all main file detection routines except the magic comments)

This could be possible.

> * indentation

There is already an indent expression for bibfiles (see `:help vimtex_indent_bib_enabled`). It is not very smart, but at least IMHO it works well enough.

> I'd leave the sort-by-key, validation, linting etc to specialised bib tools, but clearly one could argue that a latex plugin isn't complete with some bib support. (especially since vimtex has gone so far to support listings, minted, subfiles and other external packages)

I partly agree. But first, I think LaTeX packages are a very different thing than bib files, and I don't think it is fair to compare these two. Second, there is already some support inherent in Vim (i.e., syntax and also an extremely minimal indent file that only specifies `set cindent`). There is also a minor filetype plugin with vimtex that tries to keep the interface to the vimtex state. There is also, as mentioned, an indent file with vimtex that provides a slighty better indent behaviour.

----

The current support for bib files is as mentioned above limited. I don't mind improving it a bit, but I think I want to limit this to allowing text objects and the interface to the "compiler" as you say (I would rather say an interface to a "proper" vimtex state or project).

For both of these, I want to start by creating some tests. To understand what is currently possible, you can note that if you have a file, e.g. `main.tex`, open, then open a related `bib` file, then the vimtex state is available. If you started compilation, then you will still see e.g. `vimtex: compile successful` messages. But the mappings are not available. I agree it makes sense to allow the mappings as long as the state is properly kept.

Ok, now there's already a lot of words. As you might have noticed, I don't have that much time for working with vimtex. So, to keep thing focussed, I like to have each issue thread address one specific thing. I therefore take the liberty of restricting the current thread to the below feature. It would make it easier for me if the other parts of your feature request are addressed in separate threads. Feel free to open them now or later.

**Opening a bib file should attempt to properly define a vimtex state and related, relevant mappings**

Case 1: Opening `main.tex` then `references.bib` should allow `\ll` to toggle compilation. This is currently not possible, but should be quite easy to implement as the state is already copied.

Case 2: Open `references.bib`, vimtex should try to find a proper main file. If found, then it should provide the relevant mappings. This is harder, but not impossible.

**Comment by lervag** [comment]
I've finally gotten around to addressing this. Vimtex now initializes the state in bib files. We try similar methods for recognizing the main tex file, and if we can't find it, we fallback to 1) the alternate tex buffer (if it exists), or 2) a "minimal" vimtex state that is not connected to a real latex file.

I think a lot of things now work more "as expected". E.g. mappings such as `\le` and `\ll` should work inside bib files, as long as the states are appropriately defined (which should happen in most cases, I think). TOC should be available, as well as some of the text objects.

Please test and give some feedback on this. Did I miss something important? Did I break something? I've tried to be careful while implementing this, but you never know...

I'll take the liberty of closing the issue, but feel free to continue the discussion or to open new related issues with further enhancement ideas.
