### ISSUE TITLE
vimtex: Selected viewer is not executable. -Selection: SumatraPDF- Executable: PDF- 

### ISSUE THREAD

**Issue by RaghuNaik** [lervag/vimtex#1523]
I get the above error with the following relevant _vimrc option:

```vim 
let g:vimtex_view_general_viewer = 'SumatraPDF'
```
SumatraPDF path is defined in the environment. 

Thank you. 

Raghu

**Comment by lervag** [comment]
I assume you are aware of the docs, e.g. `:help vimtex_viewer_sumatrapdf`.

If SumatraPDF is defined in your environments, then I assume that this should work:

1. Open a CMD window (the basic windows terminal).
2. Write "SumatraPDF".

Does this open SumatraPDF? If not, what is the error message?

**Comment by RaghuNaik** [comment]
Point well taken @lervag.  Despite the path setup, I could not execute sumatrapdf from the dos prompt. Reinstalled it through **chocolatey** and now vimtex does not complain about it. 

Thank you. 

Raghu

**Comment by lervag** [comment]
No problem, happy to hear you got it sorted out!
