### ISSUE TITLE
"build_dir" does not take any effect on latexmk command

### ISSUE THREAD

**Issue by dailylama** [lervag/vimtex#1524]
ftplugin/tex.vim is ignored? Sorry if I missed answer in 4500 lines long help file

**Comment by lervag** [comment]
Wtf? Just drop vimtex if you don't want to use it.

> ftplugin/tex.vim is ignored?

Of course not. Learn to use Vim.

> Sorry if I missed answer in 4500 lines long help file

I'm sorry if my 1000s of hours in developing this stuff is useless to you. Yes, there's a lot of features and so the docs are long, but it is meant as a reference. Read the introduction as a start. If you're new to Vim, then spend time learning Vim first.

If you want help from me, then start by being nice and respectful.
