### ISSUE TITLE
Zeroth column highlighted

### ISSUE THREAD

**Issue by danieleavitabile** [lervag/vimtex#1525]
**Issue**

Whenever I open and save a .tex file my 0th column becomes highlighted and I see the ">>" symbols, as in the picture. It is quite hard to understand what causes this, as I haven't really switched on that behaviour voluntarily. I am not including a minimal .vimrc file, as I would just want to be put on the right track to understand what the cause of the problem is, and I hope someone will recognise that behaviour. 

Thanks.

![Screenshot 2019-10-24 at 14 17 20](https://user-images.githubusercontent.com/20712295/67485445-57b5a880-f66a-11e9-871e-05c9890c3644.png)

**Comment by lervag** [comment]
I suspect you have installed something like ALE or coc.nvim. It is the sign column and is used to indicate warnings and errors. It is not related to vimtex. I personally don't like this and disable it with `let g:ale_set_signs = 0` (I use ALE).

**Comment by danieleavitabile** [comment]
Thank you, this is exactly what I needed. In my case it was syntastic.

**Comment by lervag** [comment]
Yes, that makes sense. And no problem :)
