### ISSUE TITLE
Parsing input|include-Files from TEXINPUTS

### ISSUE THREAD

**Issue by sv-dl** [lervag/vimtex#1531]
Hello,

for the completion-feature it would be nice to parse even included files which reside within TEXINPUTS-directories.

Assume the following file layout

```
${HOME}
   +  texinclude
   |   +  inp.tex
   +  texwork
       +  example.tex
```

The shell environment `TEXINPUTS` is set to `${HOME}/texinclude:`

content of `${HOME}/texinclude/inp.tex`

```
 \section{bar}\label{sec:bar}

\newglossaryentry{g:foo}{%
  name={foo},
  plural={foos},
  description={%
    very fooish
  }%  
}
```

content of `${HOME}/texwork/example.tex`

```
\documentclass{article}
\usepackage{glossaries}

\makeglossary
\begin{document}

  \input{inp.tex} % gf on 'inp.tex' works fine

  \ref{sec:bar}   % completion after type '\ref{' works if aux-file exists
  \gls{g:foo}     % completion after type \gls{' didn't work
                  % but completion works if used '\input{../texinclude/inp.tex}

\printglossaries

\end{document}
```

The completion for the glossary entries did not work as the parser seems to try to include `${HOME}/texwork/inp.tex` but not looking for the TEXINPUTS or kpsewhich.

Additionally I use sometimes some custom .cls-files from which I source glossary definitions. The definitions are not shown for the completion since documentclass files are not parsed. Maybe a white list of of class-files and/or package-files for parsing could help in this situation.

Thanks for your great work.

**Comment by lervag** [comment]
I think this should work now, please test.

**Comment by sv-dl** [comment]
Works fine, many thanks!

In a test environment I've seen, that with relative pathes in `$TEXINPUTS` like `TEXINPUTS=../inputdir/:` vimtex fails with:

```
"exmpl.tex" 21L, 392C
Error detected while processing function vimtex#init[4]..<SNR>35_init_state[1]..vimtex#state#init[9]..1[30]..7[3]..vimtex#parser#tex[1]..vimtex#parser#general#parse[2]..15[27]..16[19]..<SNR>40_input_to_filename[21]..vimtex#kpsewhich#find:
line    7:  
E121: Undefined variable: b:vimtex
E116: Invalid arguments for function simplify(b:vimtex.root . '/' . l:filename)
E15: Invalid expression: vimtex#paths#is_abs(l:filename) ? l:filename : simplify(b:vimtex.root . '/' . l:filename)
Error detected while processing function vimtex#init[4]..<SNR>35_init_state[1]..vimtex#state#init[9]..1[30]..7:
line    3:  
E712: Argument of map() must be a List or Dictionary
Error detected while processing function vimtex#syntax#init[6]..vimtex#syntax#load:
line    4:  
E715: Dictionary required
```

While I don't think that this would be a useful setup in real life maybe vimtex should never the less not fail.

**Comment by lervag** [comment]
I was not able to reproduce, but I think I was able to fix the issue. Can you please test?

**Comment by sv-dl** [comment]
Wow - this was quick

and it fixes the issue.

Thanks again

**Comment by lervag** [comment]
> Wow - this was quick

:)

> and it fixes the issue.

> Thanks again

Great, and no problem. Thanks for the suggestion and bug report!
