### ISSUE TITLE
Close current delimiter environment bug for mismatching left/right delimiters

### ISSUE THREAD

**Issue by tbrazel** [lervag/vimtex#1534]
Opened as per request [here](https://github.com/lervag/vimtex/issues/1532#issuecomment-552009753).

When typing mismatching delimiters, e.g. `\left. f \right|_X`, the user would expect that `]]` would not close any delimiters, since `\left` and `\right` are matching, despite the delimiters being different. However, when typing `]]` after this phrase will produce `\right.`

If possible, vimtex should recognize left/right pairs of mismatching delimiters. Thanks!

**Comment by lervag** [comment]
I think this is fixed now. If you still find examples that does not work as expected, please let me know.
