### ISSUE TITLE
How can I tell vimtex an environment is a math environment to make math symbol conceal? 

### ISSUE THREAD

**Issue by Freed-Wu** [lervag/vimtex#1535]
Excuse me, how can I tell vimtex an environment is a math environment to make math symbol conceal? `\begin{equation}...\end{equation}`, `$...$`, have conceal, but `\begin{align}...\end{align}`, `\begin{numcases}...\end{numcases}` don't have it.
![Image 6](https://user-images.githubusercontent.com/32936898/68581065-a78dcf80-04b2-11ea-89cb-2b680caa4b79.png)

I guess it maybe exists a dictionary to tell vimtex which is a math environment but I has not find it in its manual.
nd the environment numcases is special... you can `!texdoc cases` to find its manual, it looks like 
```
\begin{numcases}{left_side}
case_1 & explanation_1 \\
case_2 & explanation_2 \\
...
case_n & explanation_n
\end{numcases}
```
the case_1 and left_side is math content but the explanation_1 is text content.
Thank you!

**Comment by lervag** [comment]
Environments like `align` are detected as math environments when vimtex recognizes that the `amsmath` package is loaded. If this is loaded implicitly (e.g. by other packages or the documentclass), then you need to compile the document for vimtex to recognize the package (by parsing the `.fls` file). So, please check if this issue is fixed by compiling your document and then restarting vimtex.

**Comment by Freed-Wu** [comment]
I use `newtxmath` package and it implictly load amsmath. Because my vimrc always clean `*.fls` when it finish complie so I cannot see the conceal of `align`. You are right!
And the other math environment how can I tell vimtex they are math environment? This method cannot work for other math environment....
Thank you very much!
![Image 7](https://user-images.githubusercontent.com/32936898/68585490-5f27df00-04bd-11ea-8e6e-b70116bf665f.png)
![Image 9](https://user-images.githubusercontent.com/32936898/68585508-67801a00-04bd-11ea-949e-f93c84250bb1.png)

**Comment by lervag** [comment]
> You are right!

Good to hear!

> This method cannot work for other math environment....

Probably this is because it is not implemented. So, let's fix that. I will need the following:

- List the missing math environments with the expicit packages that defines them.
- Give at least one good example for each environment you want me to add support for. I would prefer to get these examples in text, not as a screenshot.

**Comment by Freed-Wu** [comment]
Please use this mini.tex! Thank you a lot!
```
\documentclass{article}
\usepackage{newtxmath}
\usepackage{cases}
\begin{document}

\begin{subnumcases}{y_1 = }
f_1(x) & $x > 0$\\
f_2(x) & $x \leqslant 0$
\end{subnumcases}

\begin{numcases}{y_2 = }
f_1(x) & $x > 0$\\
f_2(x) & $x \leqslant 0$
\end{numcases}

\end{document}
```
![Image 10](https://user-images.githubusercontent.com/32936898/68589789-d9f5f780-04c7-11ea-921d-0d3e2129f348.png)

**Comment by lervag** [comment]
Ok, this should work now.

**Comment by Freed-Wu** [comment]
Excuse me, the `\si` and `\SI` can be support about math conceal? As the following `test.tex`:
```
\documentclass{report}
\usepackage{siunitx}
\begin{document}

\SI{10x10}{\mu m}

\si{\m^2}

\end{document}

```

Thank you very much!

![Image 14](https://user-images.githubusercontent.com/32936898/69473080-396bd580-0ded-11ea-836b-724dad2328bd.png)
![Image 15](https://user-images.githubusercontent.com/32936898/69473082-3cff5c80-0ded-11ea-9b8a-a77a697dc994.png)

**Comment by lervag** [comment]
No, I think it is too difficult to add conceal for this, sorry. Vim only supports concealing multiple characters with a single character, see `:help conceal`.

**Comment by albertfgu** [comment]
I'm having the problem @Freed-Wu mentioned where the environments are not properly detected when
1. The amsmath package is loaded through an import
2. The `.fls` is cleaned up after closing the file, via
```
augroup vimtex_event_1 autocmd!
  autocmd User VimtexEventQuit     call vimtex#compiler#clean(0)
augroup END
```

I just want to confirm that with the normal workflow (open document without `.fls`, start continuous compilation) this is expected to *not* detect environments such as `align`.
Rather, it seems that the file must be opened with the `.fls` already existing; the alternate workflow I found that works is to reload the file with `:so %` after continuous compilation is already started.

**Comment by clason** [comment]
@albertfgu see #1546, which touches on the same problem -- feel free to add your view on this there. Could you check that `<leader>lx` (which reloads the plugin) reparses the `fls` file and gives the correct environments?

**Comment by Alexandre867** [comment]
What about custom math environment? It's causing me issues when using context-dependant snippets.
```
\documentclass{article}
\usepackage[paperheight=2in,paperwidth=3in,margin=.25in]{geometry}
\usepackage{mathtools}
\newenvironment{nsflalign}{\setlength{\abovedisplayskip}{0pt}\setlength{\belowdisplayskip}{0pt}\csname flalign\endcsname}{\csname endflalign\endcsname\ignorespacesafterend}

\begin{document}

\begin{nsflalign}
	1+2 &= 3 &\\
	\mu^2+\tau^2 &= \theta^2+4
\end{nsflalign}\hspace{0pt}

$\mu^2+\tau^2 = \theta^2+4$

\end{document}
```
![Screenshot of the code](https://user-images.githubusercontent.com/97113885/192300879-78ab579f-7a49-4463-8a10-0653be8edba0.png)
![Screenshot of the result](https://user-images.githubusercontent.com/97113885/192300947-71e5fb7b-9bee-4fa8-ac04-fa0a80722acc.png)
