### ISSUE TITLE
vimtex#fold: commented code with three closing }}} ends environment fold unexpectedly

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1536]
**Issue**
Consider the folds of this minimal.tex
  ```tex
\documentclass{article}
\usepackage{tikz}

\begin{document}

\begin{tikzpicture}[x=1.75cm,y=1.75cm]

    \path foreach \a in {0,...,3} {foreach \b in {0,...,3} {(-120:\a) +(\b,0) pic {p6mm}}};

    \path (-120:2) +(2,0)    pic {p2={$(-120:1)-(1,0)$}{$(-120:1)+(1,0)$}{8pt}};
    \node at ($(-120:2.5)+(0.1,0)$) {$\stackunder{p2}{\mathclap{\stackunder{\vec{a}-\vec{b},}{\vec{a}+\vec{b}}}}$};
    \path (-120:2.5) +(2,0)  pic {p2={$(-120:1)-(1,0)$}{$(-120:1)+(1,0)$}{8pt}};

\end{tikzpicture}

\end{document}
  ```
as shown in this screenshot
![Screenshot 2019-11-15 at 09 11 04](https://user-images.githubusercontent.com/371756/68927514-39822a80-0788-11ea-83d4-0692eff74542.png)

When I comment the line `\node...`, the fold for the environment `tikzpicture` changes what I do not expect
![Screenshot 2019-11-15 at 09 10 33](https://user-images.githubusercontent.com/371756/68927574-5b7bad00-0788-11ea-9454-aba84c249f1f.png)

**minimal.vim**

  ```vim
  set nocompatible
  let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/bundle/vimtex/after'
  filetype plugin indent on
  syntax enable
let g:vimtex_fold_enabled = 1

  ```

**Comment by lervag** [comment]
Hmm. I'm not sure how to properly solve this. But I had a related issue not too long ago, see #1515 and #1502. In particular, I think the best solution is to change the foldmarker or disable it:

```vim
" Either:
let g:vimtex_fold_types = {'markers': {'enabled': 0}}

" Or alternatively, something like this:
let g:vimtex_fold_types = {
      \ 'markers': {
      \  'open': '<<:',
      \  'close': ':>>',
      \ },
      \}
```

**Comment by kiryph** [comment]
Sorry for not checking the issue tracker properly.

However, I still think there is an issue. IMHO a `% }}}` should not close a different type of fold, here the fold of the environment `\begin{tikzpicture}`.

What do you think?

**Comment by lervag** [comment]
> What do you think?

I'm not sure if this is a bug worth fixing. As was pointed out in #1502, the `{{{ ... }}}` markers are actually not very good defaults in Vim. If I were to fix this issue, I would have to introduce a state variable. Unless, perhaps it is enough to let the marker fold type always be the last method to try?

**Comment by lervag** [comment]
To give more detail: The fold markers simple increase or add fold levels. That is, `% {{{` add one to the foldlevel, and `% }}}` reduce one. There is not state, and `% }}}` does not know about state or anything else.

Changing the order of how fold types are handled does not help. And I don't really see any good/robust way of "fixing" this. So, sorry. Unless you have a good idea, I think I will leave this as an unresolved bug.

**Comment by kiryph** [comment]
I see. Then I think I go with disabling fold markers:

```viml
let g:vimtex_fold_types = {'markers': {'enabled': 0}}
```

Do all fold types described under `:h g:vimtex_fold_type` close each other by changing fold level?

**Comment by lervag** [comment]
No, they don't. Some are "smarter". E.g., section folds determine fold level by section depth. But for instance environments work the same way as markers in this context.

The "problem" is that folding is computed by iterating over the lines. For proper "statefull" folding that would prevent a fold type from closing a fold it should not, one would need quite a lot of reverse lookups. I think the current implementation is quite smart and works well, but I'll gladly admit it is far from perfect. If you omit the `\begin{env}`, you would easily be able to break the folding. However, I don't think there are a lot of examples where you can do this and not also produce erroneous LaTeX code.

**Comment by lervag** [comment]
> However, I don't think there are a lot of examples where you can do this and not also produce erroneous LaTeX code.

And if there are examples, then I'll be glad to consider them for improving the folding feature, of course.

**Comment by kiryph** [comment]
I have one idea: Could we allow to modify the regex for `%.* }}}` in

https://github.com/lervag/vimtex/blob/15deb77a7c9cd7409796c8e9b02d199a1ba738f3/autoload/vimtex/fold/markers.vim#L23

I want to adjust the regex to exclude very likely candidates of commented commands as following:

I am considering following two situations

```tex
% \cmd{\cmd{\cmd{abc}}} % should not decrese fold level
% \cmd{\cmd{\cmd{abc}}} % }}} decreases fold level
```

Since I know that there should be three unmatched curly braces for the default fold markers,
I think followng regex should help me out in most situations:

1. find matching curly braces with `\({[^{]*}\)*`
2. then search for three consecutive curly braces which are only preceeded by up to two braces `[^{]*{\=[^{]*{\=[^{]*}}}`

```viml
  let self.re.end = '%\({[^{]*}\)*[^{]*{\=[^{]*{\=[^{]*}}}'
```

**Comment by 927589452** [comment]
I would suggest going a slightly different route:
```vim
let self.re.end = '%[^\\\%]*' . self.close
```

This just suppresses commented commands (and only the last comment is matched).
Did some quick tests with this [here](https://regex101.com/r/vaCegz/1).

**Comment by lervag** [comment]
Discussion moved to #1540. I'm closing this issue to avoid duplicate threads.
