### ISSUE TITLE
Can only search part of included files

### ISSUE THREAD

**Issue by sillybun** [lervag/vimtex#1539]
**Is your feature request related to a problem? Please describe it.**
When I write `\alp` in math environment and want a completion `\alpha`, I press `<tab>` and vimtex will `Scanning included files` and it will cause a big delay. I have found that in your document:

```
*g:vimtex_include_search_enabled*
  Vimtex sets 'includeexpr' to recognize included files. If a file isn't found
  in the current directory, Vimtex uses `kpsewhich` to search for it in the
  system TeX distribution. If the 'complete' option includes "i", invoking
  keyword completion with |i_CTRL-N| will search included files for completion
  possibilities. In this case, there may be a lot of calls to `kpsewhich`
  while scanning for included files during the first invocation of keyword
  completion, and this may introduce a significant delay. Subsequent keyword
  completions should be faster, as the calls to `kpsewhich` are cached.

  This option allows to disable searching for included files with `kpsewhich`,
  and with that prevent the above explained delay.

  Default value: 1
```

But if I set `let g:vimtex_include_search_enabled=0`, it will display pattern not found. But what I want is just completion of basic math environment keyword like `\alpha`, `\rightarrow`, '\mathrm' ...

**Describe the solution you'd like**

Is there any possibility that vimtex only search certain package like `amsmath.sty`. It may reduce delay but provides enough completion.

**Comment by lervag** [comment]
> When I write \alp in math environment and want a completion \alpha, I press <tab> and vimtex will Scanning included files and it will cause a big delay.

This is _not_ a regular vimtex feature. Please, provide a complete minimal example.

To be specific: There is inherently no `<tab>` completion in Vim. This is provided by a plugin or custom mapping on your side. I can't help you without knowing exactly what you are doing.

So, in order for me to be able to help, please read the [issue template](https://raw.githubusercontent.com/lervag/vimtex/master/.github/ISSUE_TEMPLATE/issue_report.md) and create a minimal example that consist of a simple `minimal.tex` file and a simple `minimal.vim` file.

**Comment by sillybun** [comment]
Thank you for your reply! I finally solve this problem by using YouCompleMe. It's now on the fly~
