### ISSUE TITLE
More actions for cite keys (open PDF, open bibentry, ...)

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#1541]
It would be nice if e.g. typing `<cr>` on top of a cite key would open a context menu from which one could choose to open the corresponding PDF, edit the bibentry, etc, depending on what is available. E.g., if the pdf is available through a `file` key of the bibentry, then one could open it. If an url or doi key is available, then one could open this. Else just edit the bibentry.

**Comment by lervag** [comment]
This is mostly ready and solved by #1802, and so I'll close the issue. Further discussions go in #1802.

**Comment by andymass** [comment]
It's been a while since I've updated and used plugin so apologies for this comment.  It seems like a useful feature, but in my opinion the `<cr>` is an unfortunate choice.   I use `<cr>` to go down (it's like j but goes to the start of the next line).  Sure, I could disable this by mapping something else to <plug>(vimtex-context-menu) but since it's a (common) built-in vim command, I wonder if others will be impacted.

My confusion was furthered when I pressed `<cr>` and it did nothing, so I wasn't even sure what this was supposed to be used for.  It seems only for citations currently.  Perhaps at the very least it should do the normal thing `<cr>` does in vim unless you're actually on a cite key?

**Comment by lervag** [comment]
> It seems like a useful feature, but in my opinion the `<cr>` is an unfortunate choice. I use `<cr>` to go down (it's like j but goes to the start of the next line). Sure, I could disable this by mapping something else to (vimtex-context-menu) but since it's a (common) built-in vim command, I wonder if others will be impacted.
>
> My confusion was furthered when I pressed `<cr>` and it did nothing, so I wasn't even sure what this was supposed to be used for. It seems only for citations currently.

Yes, I can see your point. Perhaps a better default is something like `<localleader>la` (this is not taken, and "a" for "action" seems quite easy to remember).

And yes, for now this is only used for citation contexts. But the code is general and can be used for other things in the future.

> Perhaps at the very least it should do the normal thing `<cr>` does in vim unless you're actually on a cite key?

Agreed, but this seems hard to implement since the mapping should then "know" what the LHS is. It might be possible, but it is not trivial. So I think it is better to change the default here.

So, would you find a change from `<cr>` to `<localleader>la` to be a good choice here?

**Comment by andymass** [comment]
> So, would you find a change from <cr> to <localleader>la to be a good choice here?

That would definitely suit me, although judging by the likes you have other users of this feature, and to be fair, I could remap it myself.

Very interested to see where this actions concept goes!

**Comment by lervag** [comment]
> That would definitely suit me, although judging by the likes you have other users of this feature, and to be fair, I could remap it myself.

Great. I'll make the change, because I agree with you that we should not make mappings that break expected normal Vim behaviour (unless there is a very good reason, and there is none here).

I'll bump the version with this change and make a comment in the release notes.

> Very interested to see where this actions concept goes!

Thanks, me too. I think the implementation is quite good, so there are some possibilities here. If you (or anyone) have ideas, please feel free to open issues to suggest them.
