### ISSUE TITLE
amsmath environments are not recognized if loading mathtools

### ISSUE THREAD

**Issue by juw** [lervag/vimtex#1545]
Hi,
I only load `mathtools` via `\usepackage` but do not load `amsmath` explicitely, since `mathtools` requires it. Unfortunately `amsmath` environments such as `gather` are then not recognized and `_` and `^` are highlighted red but they are actually used inside a math environment and hence correct syntax. Would it be possible, to detect if only `mathtools` is loaded and also enable the `amsmath` syntax highlighting?
Best regards.

**Comment by lervag** [comment]
`They are recognized when you compile the document. In this case, there will be a `.fls` file which lists all packages, and when this file is available, the syntax should load as expected.

If you start a new project, or if you start to edit a file that is not compiled yet, then you can compile it, then do `:edit!` to reload the file inside Vim. This should also restart Vimtex and load all syntax rules.

**Comment by juw** [comment]
For me, no such file is created, I just compile the documents via `lualatex` and `biber` I do not have anything fancy like `latexmk` available.

**Comment by juw** [comment]
Never mind `lualatex -recorder`, `pdflatex -recorder`, etc. does the trick.

**Comment by lervag** [comment]
> For me, no such file is created, I just compile the documents via lualatex and biber I do not have anything fancy like latexmk available, since I do not manage the machines I use. Do you know of a way how to generate this file without latexmk?

Sorry, I was not aware of this option. On page 13 of the [latexmk manual](http://ctan.uib.no/support/latexmk/latexmk.pdf) I see it states that this option is provided by default. I'll add a comment in the docs!
