### ISSUE TITLE
g:vimtex_toc_custom_matchers not works

### ISSUE THREAD

**Issue by mrajner** [lervag/vimtex#1547]
Hej Lervag,

I wanted to put my frames into `toc` but I get an error. So I tried also example from documentation:

````vim
let g:vimtex_toc_custom_matchers = [
  \ { 'title' : 'My Custom Environment',
  \   're' : '\v^\s*\\begin\{mycustomenv\}' }
  \]
````

and again I got a lot of errors (see below):

````
Error detected while processing function <SNR>136_sort_by_priority:
line    1:
E716: Key not present in Dictionary: priority ? a:d1.priority > a:d2.priority : -1
E716: Key not present in Dictionary: priority ? a:d1.priority > a:d2.priority : -1
E716: Key not present in Dictionary: priority ? a:d1.priority > a:d2.priority : -1
Error detected while processing /home/mrajner/.vim/plug/vimtex/autoload/vimtex/parser/toc.vim:
line  626:
E716: Key not present in Dictionary: in_preamble
line  627:
E716: Key not present in Dictionary: in_content
````

Am I missing something, isn't it as simple as set `g:vimtex_toc_custom_matechers` variable?

**Comment by lervag** [comment]
Sorry. I've fixed this now. Please also read the updated docs, this stuff should be better and more precisely described now.

**Comment by mrajner** [comment]
Hej, thank you for quick solution. Now it is working.

I am currently struggling to have a numbers close to frames and titles of this frames in toc.
Documentation says it is not trivial, and I had not succeed yet. Wouldn't you mind to share idea how to use `get_entry` to get the frame title (`\\begin{frame}{\zs.*\ze}`), and frame number if possible?

So far I get this setting below allows to have frames in toc (useful in beamer package).
````
let g:vimtex_toc_custom_matchers = [
\ { 'title' : 'frame:',
\   're' : '\v^\s*\\begin\{frame\}',
\ }]
````

PS
You also refer in documentation to function:
  `s:toc.parse(...)` in `autoload/vimtex/toc.vim`.
which is not already part of that file (removed in `e79d040`).
You may want to fix this part in doc, but I am not sending separate pull request on that.

**Comment by lervag** [comment]
I could show you, but I reckon this makes sense to implement for everyone. So I did: I made an easy version similar to your suggested regex. It does not support the `\frametitle` command or multiline titles, but I think it is good enough for now.

Feel free to improve it if you feel like it: I think you should be able to understand how it is done by looking at the latest commit, [here](https://github.com/lervag/vimtex/commit/c397decfc0b9a906cf8e2fb00a998c099bb0f263#diff-e7dcc764f0d4ea9cd41000c5d900a941R590-R606).
