### ISSUE TITLE
latex_view_general_viewer not fully deprecated

### ISSUE THREAD

**Issue by rieser** [lervag/vimtex#1549]
Although stated in issue #656 that `latex_view_general_viewer` is ignored, it is still described in the documentation, and the line

```vim
let g:latex_view_general_viewer = 'your favorite viewer'
```

WILL change the viewer as indicated in the documentation. If you change the viewer in this way, however, forward and reverse searching will not work, even if you also use

```vim
let g:latex_view_method = 'your favorite viewer'
```

somewhere else in your `.vimrc`. If, on the other hand, you ONLY use

```vim
let g:latex_view_method = 'your favorite viewer'
```

with a viewer which supports forward and backward searching, then everything works fine.

This appears to be the true origin of the problem in issue #656.

**Comment by lervag** [comment]
There is no such thing as `latex_view_general_viewer` or `latex_view_method`. So I assume you mean `vimtex_view_...` in both cases.

The statement in #656 is that `g:latex_view_general_viewer` is ignored. `g:vimtex_view_general_viewer` is _not_ ignored, and becomes relevant if `g:vimtex_view_method = 'general'`. If `g:vimtex_view_method` is e.g. `zathura`, then the option `g:vimtex_view_general_viewer` becomes irrelevant.

Let's assume you are right that there is a bug: Please provide a concrete example of this with a minimal vimrc file.
