### ISSUE TITLE
PDF refreshed many times after compilation.

### ISSUE THREAD

**Issue by franzbertani** [lervag/vimtex#1552]
With compilation started in continuous mode, Skim refreshes the PDF several times (more than 4 times) after every file save, even if I don't add any new references and latexmk executes just one run.

The same doesn't happen when compiling from command line.

These are my vimtex settings

```vim
Plug 'lervag/vimtex'

let g:tex_flavor="latex"
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_compiler_latexmk = {
      \ 'build_dir' : 'build',
      \}
let g:vimtex_view_method = 'skim'
let g:vimtex_quickfix_latexlog = {
      \ 'overfull' : 0,
      \ 'underfull' : 0,
      \ 'packages' : {
      \   'default' : 0,
      \ },
      \}
```

**Comment by lervag** [comment]
Thanks for the issue. Unfortunately, I don't own a Mac and I can't help directly with this. As far as I understand from previous issues, things should work well on OSX with Skim. I've tagged the issue in the hope that someone might contribute here.

On your side: It would be very helpful if you could design a full minimal example of this with clear and explicit steps to reproduce. The issue template was supposed to give some indications on how to do this; let me know if you need help with it.

**Comment by clason** [comment]
@franzbertani Also make sure to include the Skim options -- it sounds like you might have "check for file changes" activated, which interferes with vimtex's scripted refresh.

**Comment by franzbertani** [comment]
Thanks for your super quick feedback!

vim config
```
call plug#begin('~/.config/nvim/plugged')
    Plug 'lervag/vimtex'
        let g:vimtex_compiler_progname = 'nvr'
        let g:vimtex_compiler_latexmk = {
                    \ 'build_dir' : 'build',
                    \}
        let g:vimtex_view_method = 'skim'
        let g:tex_flavor="latex"
        let g:vimtex_quickfix_latexlog = {
                    \ 'overfull' : 0,
                    \ 'underfull' : 0,
                    \ 'packages' : {
                    \   'default' : 0,
                    \ },
                    \}
call plug#end()
set nocompatible
filetype plugin indent on
syntax enable
```

test file
```
\documentclass{article}
\begin{document}
  Hello world!
  Ciao!
  \clearpage
  \section{Section 1}\label{sec1}
  \subsection{sub}\label{sec2}
  \clearpage
  Ref \ref{sec1}
  Pageref \pageref{sec1}
  Pageref \pageref{sec2}

\end{document}
```

The document refreshes four time every time I add a word and save.

@clason "check for file changes" was indeed activated, but the multiple refresh persist after deactivation. The only non standard Skim option is to support backward search with vimr.

Again, thank you both for your support.

**Comment by clason** [comment]
Then it must be the `build_dir` option (or anything in a `.latexmkrc` that might be lying around) -- can you try without it?

**Comment by franzbertani** [comment]
I don't have any `.latexmkrc` and the issue persist without the build_dir option.
The same happens with standard neovim, so VimR shouldn't play a role indeed.

I'll try to investigate deeper into this issue and hopefully be back with a solution (even if it seems that I'm the only one affected :) ).

**Comment by clason** [comment]
Well, besides the usual suggestion (update all the things), I can only think of the possibility that multiple pdflatex were spawned in parallel so you get a race condition (checked by `ps -ax |grep latex` from the terminal; sometimes a judicious `killall perl` and starting from scratch helps).

**Comment by lervag** [comment]
> I'll try to investigate deeper into this issue and hopefully be back with a solution (even if it seems that I'm the only one affected :) ).

Thanks. I'm sorry to say I really don't have any idea here. I hope you (possibly with help from @clason; thanks!) will be able to figure it out!

**Comment by franzbertani** [comment]
It seems to be related to fish shell. 
Setting zsh as shell in vimrc solves the problem.
Still I really don't know why :)

**Comment by lervag** [comment]
I guess vimtex assumes a bash/zsh style shell, and so some of the system calls may fail/behave unexpectedly under Fish shell. Sorry about that. But I'm glad to hear that things now work.
