### ISSUE TITLE
Where to throw money

### ISSUE THREAD

**Issue by 927589452** [lervag/vimtex#1553]
**Issue**
I wanted to throw some money at this project (or a project of your liking) and there is no such thing mentioned in the help yet @lervag.

**Comment by lervag** [comment]
That's very kind of you!

I accept donations on paypal and have put a donation sign on the README file. Note that I don't have any expenses on this project (except my time). Any donation money is therefore spent on coffee or beer (both make me happy).

But, if you want, you should also feel free to instead donate to a charity. I have a good life, and so the money could have a greater impact if it reaches someone in need for aid. For instance, you could donate to the [ICCF](https://iccf-holland.org/), or you could donate to [Medicins sans Frontiers](https://www.msf.org/), or any charity that you like.
