### ISSUE TITLE
Vim stuck on folder creation when using build_dir

### ISSUE THREAD

**Issue by Sk4r12** [lervag/vimtex#1555]
I ran into a problem trying to use build_dir.

To test it I included

`let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : 'latexbuild',
    \}`

in my vimrc and tried some minimal tex example, but whenever I tried to compile vim got stuck (ran up to 15mins without completing).

After some tinkering I found that the problematic line was in the `latexmk.vim` in the function  `s:compiler_start`:

`let l:dirs = split(glob(self.root . '/**/*.tex'), '\n')`

I had put my minimal example in my home directory, so this call took too long. 

When I moved my file to a different folder everything worked great.
Changing the ** in glob to just look a few levels deep also worked

**Comment by lervag** [comment]
> I had put my minimal example in my home directory, so this call took too long.

> When I moved my file to a different folder everything worked great.

Just so it's clear: The issue you raise here is only an issue when the directory tree upwards is very large. The home directory is a good example.

Although I think this is a slightly absurd edge case, I agree it is unexpected and that things should work well regardless.

**Comment by lervag** [comment]
The problem here is that it is difficult to "guess" the number of levels. Say we set it to maximum two levels, then it will break for people who use three levels. I would think there are a lot more people who do that than who makes the latex files directly in their home dir.

Also, for me, the `glob()` call is very fast also from the home dir.

I think it would be nice to define a full minimal example for this problem so that I could possibly reproduce it. Right now it is very difficult to change anything because 1) things work well for almost everyone, and 2) a change to limit the depth as you propose would probably break things for someone.

**Comment by Sk4r12** [comment]
> Just so it's clear: The issue you raise here is only an issue when the directory tree upwards is very large. The home directory is a good example.
 
Yes, that's correct. 

I agree that this is a rather absurd edge case that will rather pop up when trying things, than in a "real life situation" and that a fix here can easily break things for other people. 
 

I mainly opened this issue, so anybody encountering such a problem can find it on the internet. 

>I think it would be nice to define a full minimal example for this problem so that I could possibly reproduce it.

I'm not sure how to define the minimal example here since this issue might be specific to my folder structure.

> Right now it is very difficult to change anything because 1) things work well for almost everyone, and 2) a change to limit the depth as you propose would probably break things for someone.

I don't even know if it really needs a fix. Maybe adding a sentence to the documentation for `build_dir`might be enough.

I had one idea on how to fix it, but I don't know whether this is easy to implement in vimscript:
The `glob()` call could be wrapped in some sort of timer (maybe 60s) - if that time is up and the function call has not returned yet, the user gets a warning about this issue. And either the command is aborted there or the user can decide whether to continue.

**Comment by lervag** [comment]
>  The `glob()` call could be wrapped in some sort of timer (maybe 60s) - if that time is up and the function call has not returned yet, the user gets a warning about this issue. And either the command is aborted there or the user can decide whether to continue.

I am not aware of such a builtin feature in Vim, sorry. I don't think it is possible.

> I don't even know if it really needs a fix. Maybe adding a sentence to the documentation for `build_dir` might be enough.

Ok, thanks. I agree that might suffice, but I'm not quite sure what to add. The following is the current text:

```
  build_dir~
    This option sets the compilation build directory.  It corresponds to the
    `-output-directory` option in `latexmk`.  If the path is a relative path,
    then it will be considered relative to the main project file.

    Note 1: This option only works with `latexmk` version 4.27 and later.
    Note 2: If `$out_dir` is added to `.latexmkrc`, then the `.latexmkrc` setting
            will have priority.
```

I could add something like this:

```
    Note 3: Vimtex automatically creates necessary subdirectories. This
            requires a search for all relevant `.tex` files, which is done by
            a `glob('main-root/**/.tex')` type call. This may "blow up" if you
            try to use this feature in a deep node in your file hierarchy, e.g.
            in `$HOME`.
```

Feel free to suggest a better wording!

**Comment by Sk4r12** [comment]
I think the wording is fine like that and should be enough if anybody runs into that same problem.
