### ISSUE TITLE
Document server name forwarding for reverse search with zathura+neovim+nvr

### ISSUE THREAD

**Issue by mcorah** [lervag/vimtex#1556]
This is a minor issue, but I don't see any point in the documentation that indicates that vimtex fowards the server-name to zathura [(see here)](https://github.com/lervag/vimtex/blob/7c08bf73aa15bc794c79b1e8750df3c18066c6fb/autoload/vimtex/view/zathura.vim#L46).

The discussion of `nvr` under `vimtex-synctex`, `vimtex-faq-neovim` does not mention whether vim/neovim has to be configured to use a specific server name (such as the default for nvr).

A lot of the discussion of client-server functionality for vim and neovim here and elsewhere seems to me to imply a single server with a fixed name. It would be good to know when this model isn't necessary.

**Comment by lervag** [comment]
Could you please be more specific on which problem you are trying to solve? Everything you need to know about the clientserver feature in Vim/neovim can be found in `:help clientserver`. When you start Zathura (or other supported viewers) from Vimtex, then it passes the current clientserver, which is the sensible thing to do.

**Comment by mcorah** [comment]
Sorry, I was coming out of a long day when I wrote that.

For context, this relates to backwards/reverse search which I had been aware of for some time but hadn't used in part because I didn't want to deal with the overhead of running vim as a server, especially with a fixed name as my workflow often involves multiple latex files and vim instances.

My understanding is that starting uniquely named server functionality for each session is a quirk of neovim (unless Vim 8 is able to do so too). That's great for me as it's compatible with my workflow without any extra effort.

However, the mechanics that make this work (unique naming and name forwarding) don't come across in the documentation. Moreover, nvr provides a default server name which suggests an alternative and less sensible implementation.

So, (*TLDR*) my suggestion is to explicitly clarify that fixed server names or useful but not necessary due to forwarding. I can provide edits and a merge request if you like.

**Comment by lervag** [comment]
> So, (TLDR) my suggestion is to explicitly clarify that fixed server names or useful but not necessary due to forwarding. I can provide edits and a merge request if you like.

I must admit I still do not quite understand what you mean, but if you could propose a merge request then it might be easier to understand.

What do you mean by "fixed server names"?

With Vim in a terminal, you have to do `vim --servername NAME` to set a servername. In gui vim it is set by default. With neovim, the servername is set by default and is unique for each new instance. `nvr` is _not_ relevant to setting a servername. `nvr` is a tool for neovim to bring back the `vim --remote*` class of arguments. These lack from neovim and has been implemented in `nvr`. Thus, if you start neovim with some servername, say `/tmp/nvimASDasd`, then you can use `nvr --servername /tmp/nvimASDasd` --remote file1` to open `file1` in the neovim instance.

**Comment by mcorah** [comment]
> What do you mean by "fixed server names"?

I was referring scenarios where where the `vim`/`neovim` server name is specified in the command line as you describe.

I am concerned with specifying `vimtex`'s behavior for `neovim` running with a default/unique server name.

I'll try to have a merge request to you later today or this week.

**Comment by lervag** [comment]
Thanks, the suggested improvements in #1562 make sense.
