### ISSUE TITLE
Default to tex_flavor=latex?

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1557]
Once in a while, someone wonders why their vim doesn't recognize their `.tex` files as `filetype=tex` because the automated keyword search doesn't trigger for some reason. So I put the following suggestion up for discussion: Is it time to make `latex` the default flavor and have plaintex afficionados (who know what they are doing) override this with `tex_flavor=plaintex`? (Possibly adding known overrides like `$$` -- which nobody should be doing in LaTeX anyway?)

**Comment by clason** [comment]
Sorry, not a vimtex issue! (Wish you were the ft maintainer... :grin: )

**Comment by lervag** [comment]
> Sorry, not a vimtex issue! (Wish you were the ft maintainer... grin )

Haha, no problem. :)

I do partly agree, though. And it is somewhat annoying to address issues related to "basic" things like this, even though it is understandable that people get surprised. I think having LaTeX be the default would be less surprising for most people.

**Comment by clason** [comment]
Would it be feasible to just set `g:tex_flavor=latex` when loading vimtex? (Vimtex also registers as `plaintex` ftplugin, right?) And then note this in `:h vimtex-comment-internal` and that it can be overriden by `g:tex_flavor=plaintex`. Or would this be too intrusive (and break autodetection)?

**Comment by lervag** [comment]
I think it is feasible, but I'm not sure if it is "correct". I would love to get some more opinions before I perform the change, though.

The proposal, in short: If `g:tex_flavor` is undefined, then set it to `latex`. Add a comment on this in the docs under `vimtex-coment-internal`

**Comment by clason** [comment]
I'm not sure it's the right thing to do, either; the autodetect heuristic seems good (`\documentclass`, `\usepackage`, `\begin`/`\end` in the first 1000 uncommented lines). I'm a bit surprised that there are examples where a) this doesn't trigger and b) this leads to vimtex problems -- specifically, 
> But, when I open a new .tex file, I get a notification saying "vimtex not loaded"
(which was fixed by setting `g:tex_flavor=latex`).

**Comment by lervag** [comment]
> I'm a bit surprised that there are examples where a) this doesn't trigger and b) this leads to vimtex problems -- specifically,

I sort of agree, but I think sometimes people might only use `\section` and text, and in this case, the filetype is not detected "properly".

> > But, when I open a new .tex file, I get a notification saying "vimtex not loaded"
>
> (which was fixed by setting g:tex_flavor=latex).

I am not sure where your quote is from, and I don't quite see where the notification comes from. I don't think it is issued by vimtex itself...

**Comment by clason** [comment]
> I sort of agree, but I think sometimes people might only use \section and text, and in this case, the filetype is not detected "properly".

I guess I have a hard time imagining LaTeX without any `\begin{equation}`, but that's obviously just my limited imagination ;)

> I am not sure where your quote is from, and I don't quite see where the notification comes from. I don't think it is issued by vimtex itself...

Sorry, I should have sourced that -- it's from the neovim gitter, where someone mentioned this problem. Sounds like a strange error alright (if vimtex isn't loaded, who would know to notify? thinking about it, I have a sneaking suspicion of spacevim...) I'll see if the person is still around on gitter and can provide more details.

**Comment by clason** [comment]
Ah, no, he wasn't bridged from freenode/IRC, so can't ping him. But he mentioned 
>  I am using coc.nvim with vimtex

(but possibly not `coc-vimtex`, just `vimtex`).

**Comment by lervag** [comment]
Ok, let's just try it. If anyone should later object to it, then I'll probably be quick to revert the change. But since it might reduce the number of times I have to help people with related issues, then I also think it might be worth the update.

**Comment by lervag** [comment]
Ah, no, sorry. This variable needs to be set _before_ a filetype plugin is loaded. Thus, to set it, I would need to add a plugin script, which I think is a little bit too hacky. Thus, I think we'll let things stay the way they are. :\
