### ISSUE TITLE
Word text objects too greedy

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1558]
Some recent change (couldn't bisect it yet, but still trying) changed the way that vimtex handles word objects (as in `dw`). For example, `dw` in the following situation deletes _everything_ from the cursor until the white space:
```tex
[l|em:foo] bar
```
(Previously -- and without vimtex -- it would only delete up to the colon. This also breaks autocomplete, where triggering on `eq:some` will insert `eq:eq:something`.)

Specifically, it seems that `:` and `]` are no longer considered word boundaries (while `}` still is).

I realize this is little to go on and would be happy to help pinpoint the problem.

**Comment by lervag** [comment]
It's not really that recent. See #853, which resulted in `set iskeyword+=:`. However, `]` should still be considered a word boundary and does so for me.

Autocompletion also works as expected for me, so I think we would need to pinpoint to figure out what's happening here.

**Comment by clason** [comment]
No, this was definitely a change in the last few weeks/months. (Possibly around the time of the big text-object PR?) So to be clear: doing `dw` in my example does stop at `]` for you?

**Comment by lervag** [comment]
Yes, it stops at `]`. `dw` behaves exactly like I expect it to behave. Autocompletion as well.

**Comment by clason** [comment]
Interesting. Then it's not a vimtex problem (although I cannot reproduce it with `nvim -u NONE`). I'll try to bisect further.

You're using deoplete, right? Maybe the autocomplete is unrelated and an ncm2 problem.

**Comment by lervag** [comment]
I'm using `coc.nvim` actually. I think for the completion issue it is good to first verify that it is not an issue with the omnifunction by testing `<c-x><c-o>`. If the problem is only with the autocomplete plugin, then that makes it easier to debug.

It could be a problem with vimtex, of course. I'm just saying that I don't see the problem myself. :)

**Comment by clason** [comment]
Oh, you went to the _real_ dark side ;)

Yes, vimtex's omnicompletion works fine. I just tested `asyncomplete`, where I don't have the issue. (It doesn't do fuzzy matching, but I can live without that for now.) So it really looks like there are two separate issues, which I'm no longer sure are vimtex-related. So I'll close for now and reopen when (or if) I have a stronger indication that there's a vimtex problem with the `dw` issue.

Sorry for the noise, and as always, thanks for your patient help!

**Comment by clason** [comment]
OK, I think I could reproduce this -- it only happens inside tikz pictures (so something like `\node[color=r|ed]{...}` will delete everything from `|` to the next whitespace).

**Comment by lervag** [comment]
> Oh, you went to the real dark side ;)

Haha, yeah. For now. Not sure if I'll stay, but it does work quite well.

> OK, I think I could reproduce this -- it only happens inside tikz pictures (so something like \node[color=r|ed]{...} will delete everything from | to the next whitespace).

With the following example, `dw` still does not delete the `]` (or anything beyond this point).

```tex
\documentclass{standalone}
\usepackage{tikz}
\usetikzlibrary{arrows}
\usetikzlibrary{positioning}
\usetikzlibrary{calc}
\begin{document}

\begin{tikzpicture}
  [
    thick
  ]
  \node[color=red]{asdf}
\end{tikzpicture}

\end{document}
```

**Comment by clason** [comment]
> Haha, yeah. For now. Not sure if I'll stay, but it does work quite well.

That's all that matters :)

I cannot reproduce it with your example either, so back to the drawing board, I guess... (It might be OS specific; I'm away from my Linux box for the holidays and using Macs at home.)

**Comment by clason** [comment]
Oh, how about this:
```tex
$[F(u_{\min|})](x)$
```
(cursor on the `}` in normal mode). Does that delete up to or including the `]` for you? (It actually deletes everything until the `x` for me.)

**Comment by lervag** [comment]
Yes, in this case I delete the same text as you. But I do that regardless of the filetype. That is, if you save that file as `test.txt` and open it, then it behave the same way. Vimtex is still not relevant here.

**Comment by clason** [comment]
Hmm, I could have sworn that was new behavior, at least in some situations. Chalk it up to end-of-year fatigue...

Sorry for wasting your time! (Seriously, you're doing enough supporting vimtex in your spare time!)

**Comment by lervag** [comment]
> Sorry for wasting your time! (Seriously, you're doing enough supporting vimtex in your spare time!)

No problem, not much time wasted. And thanks for the kind words! :)
