### ISSUE TITLE
Autocompletion add option to make eqref ignore page numbers

### ISSUE THREAD

**Issue by a-torgovitsky** [lervag/vimtex#1559]
Equation completion prioritizes pages over equation numbers.
For example, if I have an equation on page 2 labelled (1), and an equation on page 2 labelled (3), then
`\eqref{2 <CTRL+X><CTRL+O>`
gives equation (1) as the first choice for autocompletion.

This seems contrary to what most users would expect, especially given that the autocompletion was triggered from `\eqref` as opposed to a general `\ref`.
I am assuming it was intended, so I put this as an enhancement to allow for an option to turn it off and only search based on equation numbers.

Here's an example .tex file where this occurs:
```tex
\documentclass{article}

\begin{document}

Here's some text on the first page
\newpage

Here's my first numbered equation on page 2
\begin{equation}
    a = b
    \label{eq:one}
\end{equation}

\newpage

Here's my second numbered equation on page 3
\begin{equation}
    c = d
    \label{eq:two}
\end{equation}

Now \eqref{2 <CTRL+X><CTRL+O} completes to eq:one as the first choice.

\end{document}
```

This is using YouCompleteMe as the autocompletion engine.

**Comment by lervag** [comment]
I can see that in some cases this could be convenient. However, IMHO, the gain is not enough to warrant a new option. That is, I think this seems a rather small inconvenience that in some cases would be a convenience. In large documents, you could match both the number and the page for a more precise regexp.

Personally, I actually very seldom use this feature. And if I do, I typically begin with matching the label (e.g. `eq:...`), then when I see my desired match pops up far below in the menu, I might continue with something like `.*p.*18` to refine the match to something on page 18.

Sorry if you disagree with my decision. But for me, adding new options is really not something I want to do unless very necessary.
