### ISSUE TITLE
Forward search with okular

### ISSUE THREAD

**Issue by adhalanay** [lervag/vimtex#156]
I am using (g)vim with vimtex and okular as pdf viewer. Everything works fine except for forward-search. Each time I press <Localleader>lv a new instance of okular appears instead of jumping in the already opened file. Should I use another viewer?

If its relevant my system is Debian Sid amd64 with kde 4.14.

**Comment by lahwaacz** [comment]
I don't use okular myself, but it uses the `--unique` option to set the one-instance-only mode. Perhaps the current instance was not started with `--unique`? Does okular print any message when it is started with `--unique` from the terminal?

**Comment by adhalanay** [comment]
Sorry! It was some old function in my .vimrc which messed things. Got rid of it and everything is fine now. So I am closing it.

**Comment by lervag** [comment]
Great, happy to hear that things are working!

**Comment by nasenatmer** [comment]
@adhalanay wrote:
> Should I use another viewer?

Yes, if you like minimal interface and keyboard-driven usage, try zathura :)
