### ISSUE TITLE
Missing completion of new commands and environments in custom classes & packages

### ISSUE THREAD

**Issue by GergelyKalmar** [lervag/vimtex#1561]
**Issue**
I often use custom classes in my tex files, however, it seems that packages loaded in these class files are not picked up by vimtex. 

Let's have in ``custom.cls`` for example:

```
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{custom}[2020/01/01 v1.0 Custom class]
...
\RequirePackage{amssymb, amsmath, amsthm}
...
```

Then while using it in ``test.tex`` (being in the same folder):

```
\documentclass{custom}
\begin{
```

... ``align`` does not show up in the YCM autocompletion list. If I explicitly load amsmath with ``\usepackage{amsmath}`` in ``text.tex`` it works as expected. I see similar problems with everything defined in class files (e.g. new commands, new environments and so on) being ignored.

Is this a known limitation or am I doing something wrong?

I'm using vim 8.1.1401 and vimtex from around October.

**Comment by lervag** [comment]
Does it work if you open `test.tex` when it has been compiled? I think it does. Vimtex does not itself parse every documentclass and package to create the list of packages. It only searches the preamble for all packages, and then uses the `.fls` file if it is available. This file is created during compilation and gives a list of all packages that are loaded for the given project. Thus, if you do this on your project, I think it should work:

1. Open `test.tex` with Vimtex
2. Compile it
3. Close Vim and reopen `test.tex`
4. Now the completion (and other things) will work as expected

Finally, note that you can simplify step 3: You can either do `:edit!` to completely reload the file, which should 1) stop any running compilers, and 2) reload vimtex. You can also use `:VimtexReload`, which does mostly the same (except it only reloades vimtex specific stuff).

**Comment by lervag** [comment]
> I'm using vim 8.1.1401 and vimtex from around October.

You should update Vimtex before you post an issue. I don't think it would be very relevant in this case, but in general, it is good practise. Else you might complain about a bug that is already fixed.

**Comment by GergelyKalmar** [comment]
Thanks for the reply! No, it does not work after compilation - it might be because I'm using latexmk with ``output-directory=.aux``, which causes the ``.fls`` files to end up in that directory. Is there a potential workaround for such cases?

I have not seen any similar bugs reported since I've pinned the repository and I thought reproducing the issue won't be a problem given the slight version discrepancy. Of course I can also look into the Ansible deployment files for my machine and change the commit hash I'm pinning vimtex to, but as you said I didn't expect that would make a difference in this case... Otherwise I agree!

**Comment by lervag** [comment]
Ok; could you provide a full minimal example, including whatever latexmk settings you use? Preferably also a minimal vimrc file, at the very minimum, your vimtex related settings? I can try to reproduce your issue. If I can reproduce it, then I hope I might fix it.

Reg. pinning: I still (relatively) actively develop vimtex, and so in 6 months time there will be a lot of bug fixes and perhaps feature improvements. You will miss these if you do not update at least once in a while. But perhaps you already do, in which case ignore this paragraph...

**Comment by GergelyKalmar** [comment]
Sure! You would need these files:

``custom.cls``
```
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{custom}[2020/01/01 v1.0 Custom class]
\RequirePackage{amsmath}
\LoadClass[12pt, a4paper]{report}
```

``test.tex``
```
\documentclass{custom}

\begin{document}
Example.
\end{document}
```

``vimrc``
```
set nocompatible
filetype plugin indent on

let g:ycm_min_num_of_chars_for_completion = 1
let g:ycm_max_num_candidates = 25

let g:tex_flavor = 'latex'
let g:vimtex_compiler_enabled = 0
let g:vimtex_matchparen_enabled = 0
let g:vimtex_view_enabled = 0
if !exists('g:ycm_semantic_triggers') | let g:ycm_semantic_triggers = {} | endif
autocmd VimEnter * let g:ycm_semantic_triggers.tex = g:vimtex#re#youcompleteme
```

Now open ``test.tex`` with ``vim -u vimrc test.tex`` and type ``\begin{`` somewhere, then a list like this shall pop up:
```
abstract [env: default]
alltt [env: default]
bmatrix [env: default]
...
```

Exit vim and execute ``latexmk test.tex``. Now if you open ``test.tex`` and type ``\begin{`` you shall see a list like this:
```
abstract [env: default]
align [env: amsmath]
align* [env: amsmath]
...
```

Note that the ``amsmath`` environments are properly shown. Exit again and delete all auxiliary files (except ``custom.cls`` and ``test.tex``). Execute ``latexmk test.tex -output-directory=aux`` and open ``test.tex`` again. If you start to type ``\begin{`` you shall not see the amsmath environments now, which is the issue I face. This is with the latest vimtex version now.

**Comment by lervag** [comment]
Ah, yes. But now you are not giving vimtex enough information. It seems you don't want vimtex to control compilation. That's fine, of course. But if you still insist on using a separate output directory, then you should not deactivate the compiler feature. Instead, you should properly configure it for the defined output directory, e.g.:

```vim
let g:vimtex_compiler_latexmk = {'build_dir' : 'aux'}
```

This way, vimtex will know to look inside the `aux` folder for the auxilliary files. As long as the compiler feature is enabled, it will also parse any `latexmkrc` files and see if the `out_dir` setting is configured. This way, you can use project specific output directories that are respected by vimtex.

**Comment by GergelyKalmar** [comment]
I see, that makes a lot of sense! Thanks for the hint. Am I right that by overriding the default compiler dictionary it remains sort of in 'sleep mode' otherwise (i.e. it doesn't do continuous compiling and such)?

So it generally seems to work now mostly fine if I add this to the vimrc file, however, I've noticed that new commands are still not picked up properly. That is, if you add ``\newcommand{\test}{test}`` to ``custom.cls``, I do not see ``\test`` being suggested while editing ``test.tex``. It works though when adding to the file directly. Am I doing something silly (again)?

**Comment by lervag** [comment]
> Am I right that by overriding the default compiler dictionary it remains sort of in 'sleep mode' otherwise (i.e. it doesn't do continuous compiling and such)?

I'm not quite sure what you mean. By overriding the default compiler dictionary, you mean this?

```vim
let g:vimtex_compiler_latexmk = {'build_dir' : 'aux'}
```

If so, then no. The compiler dictionary specifies the configuration of the latexmk compiler, which is used by default (see `:help vimtex-compiler`). The settings that you do not specify/change will remain at their default values, so the above will only change the `build_dir` setting.

> That is, if you add \newcommand{\test}{test} to custom.cls, I do not see \test being suggested while editing test.tex.

Ah, yes. Vimtex does not actually parse the classes (i.e. `.cls` files). Instead, it relies on predefined lists of commands for various packages and documentclasses, see [here](https://github.com/lervag/vimtex/tree/master/autoload/vimtex/complete). Thus, what you ask is currently not possible.

However, I could try to implement it. Something like: When completing commands, it will look for commands in the known packages, and for each package that is not already available, we could add a parser for the `.cls` file (and perhaps also `.sty` files, but we'll leave that for later).

**Comment by GergelyKalmar** [comment]
> However, I could try to implement it. Something like: When completing commands, it will look for commands in the known packages, and for each package that is not already available, we could add a parser for the .cls file (and perhaps also .sty files, but we'll leave that for later).

That would be awesome! I would also love if .sty file support would be available as I often separate new commands and environments out into .sty files to keep the .cls files focused more on document styling. I'll change the title of the issue accordingly.

In any case, this plugin works really well for me and improves my efficiency a lot already, thanks for all your effort!

**Comment by lervag** [comment]
> In any case, this plugin works really well for me and improves my efficiency a lot already, thanks for all your effort!

Great, I'm happy to hear it! :)

As you might have noticed, I'm not able to spend as much time on this as I would have liked, and so it takes some time just to follow up discussions and comments. So, to help myself, I'll specify the required actions here so that it is easy to pick it up when I get the time to implement. This also makes it easy for you to let me know if I missed something and/or missunderstood something.

----

> In any case, this plugin works really well for me and improves my efficiency a lot already, thanks for all your effort!

Great, I'm happy to hear it! :)

As you might have noticed, I'm not able to spend as much time on this as I would have liked, and so it takes some time just to follow up discussions and comments. So, to help myself, I'll specify the required actions here so that it is easy to pick it up when I get the time to implement. This also makes it easy for you to let me know if I missed something and/or missunderstood something.

----

**Required actions**
- [ ] Improve completion by parsing custom classes and packages, that is, any `.cls` and `.sty` files that are not already available as precompiled lists.
- [ ] Collect every macro defined by `\newcommand`s for command completion.
- [ ] Collect every environment defined by `\newenvironment`s for env completion.

**Comment by GergelyKalmar** [comment]
No worries, I'm not in much of a rush. I think the actions look good, looking forward to having them one day!

**Comment by lervag** [comment]
I'm closing the issue, let's follow up this discussion at #1591.
