### ISSUE TITLE
Syntax highlighting of pycode within tikzpicture

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1563]
**Issue**
Syntax highlighting of python code within environment `pycode` works outside of a `tikzpicture` environment but not within.

Consider this example

```tex
\documentclass{article}

\usepackage{pythontex}
\usepackage{tikz}

\begin{document}

\begin{pycode}
print(r'This is python.') 
\end{pycode}

\begin{tikzpicture}

\begin{pycode}
print(r'\node {This is python};') 
\end{pycode}

\end{tikzpicture}

\end{document}
```

which renders as following:

![Screenshot 2020-01-06 at 16 51 34](https://user-images.githubusercontent.com/371756/71829500-15b2d500-30a5-11ea-9d7d-fc7fb5de02f3.png)

As you can see the first `pycode` environment has adjusted syntax highlighting (colorful print function), but the second not.

Can we adjust this?

**Comment by kiryph** [comment]
A quick fix is
```diff
❯ g diff
diff --git a/autoload/vimtex/syntax/p/tikz.vim b/autoload/vimtex/syntax/p/tikz.vim
index 36974370..2b02ba49 100644
--- a/autoload/vimtex/syntax/p/tikz.vim
+++ b/autoload/vimtex/syntax/p/tikz.vim
@@ -28,7 +28,7 @@ function! vimtex#syntax#p#tikz#load() abort " {{{1
         \ end='\\end{tikzpicture}'re=e
         \ keepend
         \ transparent
-        \ contains=@texTikz
+        \ contains=@texTikz,texZonePythontex
   syntax match texTikzEnv /\v\\begin\{tikzpicture\}/
         \ contains=texBeginEnd nextgroup=texTikzOpts skipwhite
```

However, this fix might not be the general solution.

**Comment by lervag** [comment]
I think that solution is fine. Not perfect, and there could potentially be a better solution, but it's pragmatic and solves the issue. Thanks!

**Comment by kiryph** [comment]
Thanks for including it. I was thinking there might be other embedded languages which could be accepted e.g. luacode.

**Comment by lervag** [comment]
Yes, you are probably right. Perhaps all the embedded/nested language commands, e.g. minted and so on, should be available?

**Comment by lervag** [comment]
Ok, so; a lot of the syntax groups added by vimtex should in principle be allowed "everywhere", and so I need to add them to a lot of the tex syntax clusters like `texChapterGroup` and similar. I could solve this issue much better by simultaneously creating a vimtex specific cluster of groups that should be available "everywhere", and then adding this syntax cluster to the tikz group. It seems to work well.

**Comment by kiryph** [comment]
This issue is back for me. My fix is:

```diff
❯ git diff a.txt b.txt
diff --git a/autoload/vimtex/syntax/p/tikz.vim b/autoload/vimtex/syntax/p/tikz.vim
index 3510be65..23678e19 100644
--- a/autoload/vimtex/syntax/p/tikz.vim
+++ b/autoload/vimtex/syntax/p/tikz.vim
@@ -5,7 +5,7 @@
 "

 function! vimtex#syntax#p#tikz#load(cfg) abort " {{{1
-  syntax cluster texClusterTikz    contains=texCmdTikz,texTikzEnvBgn,texTikzSemicolon,texTikzDraw,texTikzCycle,texCmd,texGroup,texComment
+  syntax cluster texClusterTikz    contains=texCmdTikz,texTikzEnvBgn,texTikzSemicolon,texTikzDraw,texTikzCycle,texCmd,texGroup,texComment,texPythontexZone
   syntax cluster texClusterTikzset contains=texTikzsetArg,texMathZoneLI,texMathZoneTI,texTypeSize,@texClusterOpt

   syntax match texCmdTikzset "\\tikzset\>"
```

**Comment by lervag** [comment]
Thanks, fixed now.
