### ISSUE TITLE
Autocompletion very slow

### ISSUE THREAD

**Issue by khpoelstra** [lervag/vimtex#1565]
When entering any command, neovim lags on every keystroke.

The relevant lines from my `:profile` output are:
```FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   98  17.581066   0.030302  vimtex#complete#omnifunc()
```
```FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   48             17.032275  vimtex#util#uniq_unsorted()
```
```
FUNCTION  409()
    Defined: ~/.local/share/nvim/plugged/vimtex/autoload/vimtex/complete.vim line 413
Called 48 times
Total time:  17.260269
 Self time:   0.044592

count  total (s)   self (s)
   48   0.047780   0.000455   call self.gather_candidates_from_packages()
   48   0.001951   0.000574   call self.gather_candidates_from_newcommands()
   48   0.134951   0.000460   call self.gather_candidates_from_lets()
   48   0.000682   0.000473   call self.gather_candidates_from_glossary_keys()
                            
   48  17.074824   0.042550   return vimtex#util#uniq_unsorted(   copy(self.candidates_from_newcommands) + copy(self.candidates_from_lets) + copy(self.candidates_from_packages) + copy(self.candidates_from_glossary_keys))
```
```
FUNCTION  vimtex#util#uniq_unsorted()
    Defined: ~/.local/share/nvim/plugged/vimtex/autoload/vimtex/util.vim line 221
Called 48 times
Total time:  17.032275
 Self time:  17.032275

count  total (s)   self (s)
   48              0.000247   if len(a:list) <= 1 | return a:list | endif
                            
   48              0.000147   let l:visited = [a:list[0]]
152160              0.110453   for l:index in reverse(range(1, len(a:list)-1))
152112             16.243155     if index(l:visited, a:list[l:index]) >= 0
   96              0.000234       call remove(a:list, l:index)
152016              0.051712     else
152016              0.263616       call add(l:visited, a:list[l:index])
152112              0.055994     endif
152160              0.056432   endfor
   48              0.000128   return a:list
```

When trying to compose a minimal example, I could not reproduce the issue.
The high counts in the last code block look alarming. However, I do not know where they come from.

**Comment by lervag** [comment]
I'm sorry, but I can't help unless you give more details. If you are not able to reproduce with a minimal example, then at the very least, give me the details of your configuration and some more information about the particular case in which this is happening.

**Comment by khpoelstra** [comment]
I finally managed to reproduce the behaviour in a minimal setting:

My init.vim for neovim:
```vim
set nocompatible
if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall | source $MYVIMRC
endif
call plug#begin('~/.local/share/nvim/plugged')

Plug 'lervag/vimtex'
Plug 'neoclide/coc.nvim', {'branch': 'release'}

call plug#end()

filetype plugin indent on

let g:coc_global_extensions = [ 'coc-vimtex' ]
```

LaTeX-file:
```latex
\documentclass{minimal}
\begin{document}
  Hello world!
\end{document}
```
After compiling once, I just hold the backslash key in insert mode anywhere in the document:
```latex
\documentclass{minimal}
\begin{document}
  Hello world!
  \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\
\end{document}
```
There the time lag already occurs. It gets considerably worse in larger documents.

I just realized that there is already an issue filed concerning this for coc-vimtex:
https://github.com/neoclide/coc-vimtex/issues/7

**Comment by khpoelstra** [comment]
I just did a little more testing:
```latex
\documentclass{minimal}

% include some packages that define a lot of stuff
\usepackage{mathtools}
\usepackage{amssymb}

\begin{document}

\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\

\end{document}
```
While typing these `\`-characters, vimtex spent 4.86s in vimtex#util#uniq_unsorted and the fan of my notebook started to blow...

At the moment, writing anything in math mode is really annoying.

Maybe there is a way to do things in a more asynchronous way?

**Comment by lervag** [comment]
I've just tried your example, and I can't reproduce. That is, for me, the lag is not really annoying. It is noticable, and with profiling I also notice that the `uniq_unsorted` function is slow.

I will take a look now and see if I can improve it. Perhaps the main difference is that I'm on a pretty high-end laptop?

**Comment by khpoelstra** [comment]
Thank you so much for looking into this!

With me it is really that when I write in math mode, the text appears only in chunks of several characters. I normally still get things right without instant visual feedback, but it just does not feel right. This is on an Intel i7-7500U.

**Comment by lervag** [comment]
Could you please test now? I've made some improvements to the uniq function, and it should work better now. I hope.

**Comment by khpoelstra** [comment]
Yes! That seems to be a massive improvement. I will test it tomorrow more thoroughly. Thank you for your incredible work!

**Comment by lervag** [comment]
Great, I'm happy to hear it! Let me know if you think we need more effort in this direction or if you have other suggestions!
