### ISSUE TITLE
A litttle configuration trouble

### ISSUE THREAD

**Issue by GideonWolfe** [lervag/vimtex#1566]
**Issue**

When I attempt to compile a `tex` file using `:VimtexCompile`, I get errors complaining about `fontspec` and my typesetting engine.

**minimal.vim**

```
let g:latex_view_general_viewer = "zathura"
let g:vimtex_view_method = "zathura"
let g:tex_flavor = "latex"
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_quickfix_mode = 2
let g:vimtex_compiler_method = "latexmk"
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_compiler_latexmk = {
    \ 'background' : 1,
    \ 'build_dir' : '',
    \ 'callback' : 1,
    \ 'continuous' : 1,
    \ 'executable' : 'latexmk',
    \ 'options' : [
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}

```

**Commands/Input**

`:VimtexCompile`

**Observed Behaviour**

When I execute `:VimtexCompile`, I get the following errors.

```
/usr/share/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| Fatal Package fontspec Error: The fontspec package requires either XeTeX or LuaTeX. You must change your typesetting engine to, e.g., "xelatex" or "lualatex"instead of "latex" or "pdflatex".
/usr/share/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| Emergency stop.
/usr/share/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| ==> Fatal error occurred, no output PDF file produced!

```

**Expected Behaviour**

The expected behavior is my newly compiled PDF opening in Zathura. I *can* get all the errors to go away after adding the following line to the top of my document:

`%!TEX TS-program = xelatex`

This will produce the expected behavior.

How do I configure this option globally? I am really just unsure about the dozen different names for tex programs and which ones I should actually be using.

**Comment by GideonWolfe** [comment]
I believed this is fixed by creating a `.latexmkrc` file and adding the line `$pdf_mode = 5;`.

**Comment by lervag** [comment]
This is _not_ an issue, but the expected behaviour. When you use XeTeX or lualatex features, then you must use these compilers. This must be controlled either with the `TeX Program` directive (see `:help vimtex-tex-directives`), with a `.latexmkrc` file (which may be either "global" by putting it at `$HOME/.latexmkrc` or project local by putting it at your LaTeX project root), or finally, you can use `:help g:vimtex_compiler_latexmk_engines` to set a default in vimtex.
