### ISSUE TITLE
Backwards search with Zathura

### ISSUE THREAD

**Issue by alexwms** [lervag/vimtex#1568]
**Issue**
I cannot get backwards search to work with zathura. According to other issues I have read, backwards search should work out of the box.

**minimal.vim**

  ```vim
  set nocompatible
  let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/bundle/vimtex/after'
  filetype plugin indent on
  syntax enable
  ```

**minimal.tex**

  ```
  \documentclass{minimal}
  \begin{document}
  Hello world!
  \end{document}
  ```

I used `gvim --servername VIM -u minimal.vim minimal.tex` to start gvim. The same exact behavior occurred with regular vim. 
**Commands/Input**
I compiled the document with the command ```\ll```. The file compiled and Zathura automatically opened the pdf. I then held control and left clicked on the text in the pdf. 

**Observed Behaviour**
Nothing at all happened when I clicked on the text in the pdf.

**Expected Behaviour**
A shift of focus back to vim and a movement of the cursor to the line containing the text.

**Output from VimtexInfo**

```
System info
  OS: Ubuntu 18.04 LTS (beaver-three-eyed-raven X92)
  Vim version: VIM 8.0 (1-1453)
  Has clientserver: true
  Servername: VIM1

vimtex project: minimal
  base: minimal.tex
  root: /home/alex
  tex: /home/alex/minimal.tex
  out: /home/alex/minimal.pdf
  log: /home/alex/minimal.log
  aux: /home/alex/minimal.aux
  fls: /home/alex/minimal.fls
  compiler: latexmk
    backend: jobs
    output: /tmp/vp1QTth/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
  document class: minimal
```
**Output from VimtexCompileOutput**
```
Latexmk: This is Latexmk, John Collins, 18 June 2019, version: 4.65.
Viewing pdf
======= Need to update make_preview_continuous for target files
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -file-line-error -synctex=1 -interaction=nonstopmode -recorder  "minimal.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./minimal.tex
LaTeX2e <2017-04-15>
Babel <3.18> and hyphenation patterns for 3 language(s) loaded.
(/usr/share/texlive/texmf-dist/tex/latex/base/minimal.cls
Document Class: minimal 2001/05/25 Standard LaTeX minimal class
) (./minimal.aux) [1{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./minimal.aux) )</usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on minimal.pdf (1 page, 12686 bytes).
SyncTeX written on minimal.synctex.gz.
Transcript written on minimal.log.
Latexmk: Log file says output to 'minimal.pdf'
Latexmk: I have not found a previewer that is already running. 
   So I will start it for 'minimal.pdf'
------------
=== TeX engine is 'pdfTeX'
Latexmk: All targets () are up-to-date
For rule 'view', running '&if_source(  )' ...
vimtex_compiler_callback_success
------------
Running 'start xdg-open  "minimal.pdf"'
------------
------------
Running 'echo vimtex_compiler_callback_success'
------------
```
**Software Versions**
OS: Ubuntu 18.04 LTS
Zathura: 0.3.8
(plugin) pdf-poppler (0.2.8)
vim: 8.0 
vimtex: I cleaned and installed a fresh copy with vim-plug.

**Comment by lervag** [comment]
Please read the docs, `:help vimtex-view` and `:help vimtex_view_method`. The solution lies therein.

**Comment by alexwms** [comment]
Thank you for pointing me there. Setting ```vimtex_view_method='zathura'``` in minimal.vim enabled backwards search. In my own `.vimrc` I had already included the line ```let g:vimtex_view_method='zathura'```. I also had the line ```let g:vimtex_compiler_progname = 'latexmk'```. Commenting this line out enabled backwards search.

**Comment by lervag** [comment]
> In my own `.vimrc` I had already included the line let `g:vimtex_view_method='zathura'`. I also had the line let `g:vimtex_compiler_progname = 'latexmk'`. Commenting this line out enabled backwards search.

Ah, yes. It seems you did not read the docs for `g:vimtex_compiler_progname`:

```
*g:vimtex_compiler_progname*
  Path to vim executable.  This is used for the callback functionality, and it
  must be set correctly ... [more text follows]
```

Thus, it should not be set to the path of a latexmk executable, but to Vim. The default should work in most cases.
