### ISSUE TITLE
Support a target pdf file for `VimtexView` command

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#157]
Cloned from #155 discussion.

It would be good to have a possibility to view any pdf file with `synctex` support, but not only the main project file. This ability is in particular needed  for the multi-file projects based on `subfile` package, where each file can be compiled independently.

I propose to add an optional command argument for `VimtexView` to set the desired pdf file.

**Comment by lervag** [comment]
This should do the trick. Please test and verify.

**Comment by maxfl** [comment]
I've updated the code, but it always opens the main file. The reason is strange. I have put the following code to the `zathura.view` function:
```vim
  echom a:file
  echom a:file ? 'true' : 'false'
```
Variable `a:file` is correct, but ternary operator always evaluates to 'false'. After changing the condition to `a:file!=''` it now works as a charm.

Thanks you!

**Comment by lervag** [comment]
Ah, sorry! My mistake, I thought only empty string was False. Updating immediately.

**Comment by maxfl** [comment]
now it works. 

By the way, it's amazing that vimtex also supports mupdf.

**Comment by lervag** [comment]
Great! And thanks, I've been using `mupdf` alot myself, and so I've implemented some hacks to make it work relatively well with `vimtex`.
