### ISSUE TITLE
`$` command in blockwise Visual mode doesn't select the right ends of the lines

### ISSUE THREAD

**Issue by matsuhav** [lervag/vimtex#1573]
**Issue**
`$` command in blockwise Visual mode doesn't select the right ends of the lines. This is different behaviour from help `:h v_$`.

**minimal.vim**
```vim
set nocompatible
filetype plugin indent on
syntax enable

let g:tex_flavor = 'latex'
```

Vimtex is installed in pack dir (implicitly installed).

**minimal.tex**
```tex
foobar
foo
```

**Commands/Input**
`gg<C-V>j$`

**Observed Behaviour**
Only line 2 is selected to the end.

**Expected Behaviour**
Both line 1 and line 2 should be selected to the end, but only line 2 is selected to the end. If filetype is other than latex, it works as expected. And when I `let g:vimtex_matchparen_enabled = 0`, it works as expected too.

I think `v_$` special selecting mode which select the right ends of the lines, is inactivated when autoload/vimtex/delim.vim:481 sets cursor pos.

I don't know why but when I enter `$` twice, selected area becomes correct. So `xnoremap $ $$` can be a workaround?

**Output from VimtexInfo**
```
System info
  OS: Mac OS X 10.15.2 (19C57)
  Vim version: VIM 8.2 (1-100)
  Has clientserver: false

vimtex project: a
  base: a.tex
  root: /Users/matsuhav
  tex: /Users/matsuhav/a.tex
  out:
  log:
  aux:
  fls:
  compiler: latexmk
    backend: jobs
    output: /var/folders/1x/tssj451s2ws255_qmnc7dlfm0000gn/T/vDMYR36/2
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdfdvi
  viewer: General
  qf: LaTeX logfile
    config:
      packages:
        default: 1
      default: 1
  document class:
```

**Comment by lervag** [comment]
Ok, I found a hacky way to solve this that seems to work well. Let me know if you should fint it somehow breaks anything!

**Comment by matsuhav** [comment]
Thank you very match!
It's working nicely!

**Comment by lervag** [comment]
Great, happy to hear it!
