### ISSUE TITLE
vimtex doesn't think skim is installed when it is

### ISSUE THREAD

**Issue by RRethy** [lervag/vimtex#1574]
**Issue**

`vimtex` doesn't think skim is installed, so it defaults to open pdfs in preview instead of skim when using `:VimtexCompile`.

`:checkhealth` prints

```
## vimtex
  - OK: Vim version should have full support!
  - ERROR: Skim is not installed!
  - WARNING: Compiler callbacks will not work!
    - ADVICE:
      - `neovim-remote` / `nvr` is required for callbacks to work with neovim
      - Please also set |g:vimtex_compiler_progname| = 'nvr'
      - For more info, see :help |vimtex-faq-neovim|
```

Also worth noting, I have skim installed (newest version) and can open it. Last time I used latex was in August 2019 and the behaviour worked back then.

**minimal.vim**

  ```vim
let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'skim'
let g:vimtex_quickfix_mode = 0
  ```

**Comment by lervag** [comment]
I'm sorry, but I'm not much of a Mac expert. But this seems to be a problem with your setup, not with vimtex. How do you start Skim when you say you can open it? Does it work when starting it from a terminal?

Perhaps @clason would be willing to help out?

**Comment by clason** [comment]
And, most importantly, where is the Skim.app installed -- `/Applications` or `~/Applications`?

**Comment by RRethy** [comment]
I can open skim from Spotlight or from the command-line with `open /Applications/skim.app`. The output of that apple script is `/Applications/Skim.app/`. My Neovim version is `NVIM v0.5.0-nightly`, my skim is `Version 1.5.6 (122)`, my kitty (terminal) is `Version 1.5.6 (122)`, and my mac is `10.14.6`.

The issue has been resolved however when getting that apple script to run. In system preferences > Security & Privacy > Privacy > Automation, after checking the `Finder` checkbox under `kitty`, I was only then able to run the apple script without getting a `98:103: execution error: Not authorized to send Apple events to Finder. (-1743)`. After this, vimtex correctly opens skim. I think after updating my mac to mojave, certain security preferences were changed, and as a result vimtex was likely getting an error when trying to access skim from my terminal because it (kitty) didn't have the right access.

Thanks for the help! I'll close the issue.

**Comment by lervag** [comment]
Great, happy to hear it works!
