### ISSUE TITLE
SyntaxHL pythontex: all square brackets are considered as texBeginEndModifier

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#1575]
```
\documentclass{article}
\usepackage{pythontex}

\begin{document}

\begin{pycode}
# A list: 
mylist= ['a', 'b'] # texBeginEndModifier
# listcomp as filter
my_filtered_lst = [n for n in mylist if n == 'a']
# Filter a dict comprehension
my_filtered_dct = {n: 'a' for n in mylist if n == 'a'}
\end{pycode}

\end{document}
```

which looks like

![Screenshot 2020-01-22 at 16 41 04](https://user-images.githubusercontent.com/371756/72908608-0767e880-3d36-11ea-863b-25e4116d07db.png)

The `'a'` and `'b'` should be highlighted as strings, `for` in the list comprehension should be highlighted as a keyword in red similar to the dict comprehension.

All characters within the square brackets are highlighted as `texBeginEndModifier`. I think this should not happen here.

**Comment by lervag** [comment]
I'm pushing a quick fix for this where I remove `texBeginEndModifier` from the contains list for the pythontex environment. I think it should work, but let me know if it has any unwanted side effects!
