### ISSUE TITLE
Allow longer environments

### ISSUE THREAD

**Issue by gustaphe** [lervag/vimtex#1579]
When looking at whether a line is in a specific environment, `vimtex#env#is_inside` only looks 50 lines back. I commonly use `tikzpicture` environments longer than that. I'd suggest a `g:vimtex_env_maxlength` parameter so one can set that in a vimrc (changing line 108 of autoload/vimtex/env.vim to `let l:stopline = max([line('.') - g:vimtex_env_maxlength, 1])`). I'd make a pull request, but I don't know where default values of global parameters are normally defined.

**Comment by lervag** [comment]
I actually prefer to not use options unless necessary. But if we can not find a better way, then I agree an option might be preferable.

Could you provide a good LaTeX example that fails? Before I do anything, I want to add a test to properly specify what we are going to do.

**Comment by gustaphe** [comment]
This is as brief as I can make it. Notice how vimtex indents the last two lines one step too far because they don't recognize the semicolon as a tikz-end, since it's after the 49th row of the `tikzpicture`.
[errorexample.txt](https://github.com/lervag/vimtex/files/4118626/errorexample.txt)

**Comment by lervag** [comment]
Thanks, I've tried to fix this without an option now. I still rely on hard coded boundaries. Now with a timer as the main boundary (100 ms timeout should work well in most cases, I think), and I've increased the lookaround limit to 500 lines in Vim versions that does not have the timeout feature.

**Comment by lervag** [comment]
Let me know what you think. I don't think there is a reason to allow a custom preference here, but I may be persuaded otherwise if you can convince me I'm wrong. :)

**Comment by gustaphe** [comment]
A respectable preference. Not one I share, but it's not my code. I don't think I'll need it to be larger than that anyway.

**Comment by lervag** [comment]
IMHO, the vimtex documentation is already very long, and the list of options is also very long. I try to be pragmatic, as it seems to make things easier both for me maintaining and for users if I don't allow customization of everything. However, I do think I could have done some things differently to allow more customization (e.g. if I used more hooks/user autocommands).

In any case, thanks again for noticing and raising the issue!
