### ISSUE TITLE
Vimtex breaks python if/else highlighting

### ISSUE THREAD

**Issue by nkakouros** [lervag/vimtex#1586]
**Issue**

I run neovim with only vimtex installed, using vim-plug. When editing a python file, if/else highlighting is broken. I think typing `else` and then `:` is the moment it breaks.

**minimal.vim**

**Commands/Input**

run vim and then:

```
:set ft=python<CR>
i
if aaa:
  fff
else:
  ggg
```

**Observed Behaviour**

`else:` is not highlighted as expected.

**Expected Behaviour**

`else:` should have a color different to normal text.

**Comment by clason** [comment]
I can't reproduce this. Could you try again with a minimal init.vim (and report your version of neovim)?

**Comment by lervag** [comment]
I'm sorry, but this is nonsense. Vimtex does not do anything for python filetypes. Feel free to convince me otherwise, but if so, please provide a full minimal example (as kindly suggested in the issue template and by @clason). Include also full steps to reproduce.

**Comment by nkakouros** [comment]
It was `set iskeyword+=:` to fix reference completion that I was setting in the same file as `Plug 'lervag/vimtex'`. I don't remember where I found that advice. Sorry for the disturbance.

**Comment by lervag** [comment]
No problem. I think setting `iskeyword` makes sense, but you should only do it for LaTeX files, either with autocommands or in a filetype plugin.
