### ISSUE TITLE
b:vimtex_main not respected when initially set

### ISSUE THREAD

**Issue by latricewilgus** [lervag/vimtex#1588]
The b:vimtex_main variable seems not to be respected when initially set.
Install vimtex as a pack in e.g. `~/.local/share/nvim/site/pack/tex/start/vimtex`.

Example:

```tex
% main.tex
\documentclass[a4paper]{article}
\begin{document}
\newcommand{\ddd}{1} % obfuscate filename a little
Hello
\input{sub\ddd}
\end{document}
```

```tex
%sub1.tex
World
% vim: set ft=tex :
```

`g:tex_flavor` is set to `'latex'` in the vimrc, option `'hidden'` is disabled.

Now:
1. `nvim sub1.tex`
2. `b:vimtex_main` is not defined at this point.
3. `:let b:vimtex_main = 'main.tex'`
4. `<LocalLeader>ll`

As a single command:

```sh
nvim -u NORC sub1.tex -c ':let b:vimtex_main = "main.tex"' -c ':VimtexCompile'
```

The last statements errors out as it tries to compile sub1.tex directly instead of 'main.tex'

Workaround:
5. Open another buffer/file (it seems it does not matter which one, e.g. `blub.txt`)
6. Change buffer back to `sub1.tex`
7. `<LocalLeader>ll` now succeeds and compiles `main.tex` as expected.

As a single command:

```sh
nvim -u NORC sub1.tex -c ':let b:vimtex_main = "main.tex"' -c ':edit blub.txt' -c ':bprevious'  -c ':VimtexCompile'
```

Remarks:
* If `'hidden'` is set to true, then the workaround does not work
* Blind guess: Something gets reinit when the buffer is reloaded (not only hidden)
* When fixing keep also the scenario in mind that there are two main files `main1.tex` and `main2.tex` which both include `sub1.tex`. Then setting `:let b:vimtex_main = 'main1.tex'` compiling should compile `main1.tex` and after changing  `:let b:vimtex_main = 'main2.tex'` the file `main2.tex` should be compiled. Currently, this stays at `main1.tex`.
* After setting `b:vimtex_main` to `main.tex` `:VimtexInfo` still shows `sub1.tex` as tex file and `sub1.pdf` as output file. No mentioning of `main.tex`.

Tested version:
* 45dc935ed5f5ca6d22b7bedb8190dcc9ad10fef8 (HEAD as of writing)

**Comment by lervag** [comment]
No, sorry, you are using `b:vimtex_main` wrong. I can see that the docs are confusing on this. But: The variable must be specified before you open the tex file. That's why the docs use the `BufReadPre` event in the autocmd.

I actually don't think this feature is very useful, as it is probably easier to just use the `:help vimtex-tex-root` specifier or the `.latexmain` specifier.

**Comment by lervag** [comment]
So, to be clear: There is no real bug here.

**Comment by latricewilgus** [comment]
Thanks for the quick response and the clarification. I can see that this is not a bug in the implementation. Nevertheless, as you mentioned yourself, the docs are unclear/misleading and should be expanded. I took a shot and updated the docs (see pull request https://github.com/lervag/vimtex/pull/1589).

I also noted that after doing a `:let b:vimtex_main='main.tex'` a `:VimtexReloadState` (by default bound to `<LocalLeader>lX`) is another workaround for the issue described above. Do you know whether this has any other side effects (forgetting/resetting some settings, should not be run while continuous compilation is running, ...) or is different in comparison to switching the buffer back and forth?

@lervag wrote:
> I actually don't think this feature is very useful, as it is probably easier to just use the :help vimtex-tex-root specifier or the .latexmain specifier.

I disagree, from the description the feature is what I want. Let me explain why: I have a file content.tex which gets included by two different main files slides.tex and handout.tex, i.e. I produce two different output formats from a single input file. The two suggestions you mentioned don't fit my bill as both support only a single main file.
Using the buffer variable allows me to switch the main easily without either
a) [tex-root] changing the file and thus creating disturbance in the git history, or
b) [latexmain] switching to the console, removing a file and creating another one.

**Comment by lervag** [comment]
> I took a shot and updated the docs (see pull request #1589).

Thanks for that!

> Do you know whether this has any other side effects (forgetting/resetting some settings, should not be run while continuous compilation is running, ...) or is different in comparison to switching the buffer back and forth?

It should not really have any bad side effects (if it does, it could be considered a bug). Reloading should stop background processes such as compilers, but that is a wanted side effect.

> I disagree, from the description the feature is what I want. Let me explain why: I have a file content.tex which gets included by two different main files slides.tex and handout.tex, i.e. I produce two different output formats from a single input file. The two suggestions you mentioned don't fit my bill as both support only a single main file.

Good point, and thanks for making it. Let me know if you have suggestions for how to improve this, then (and feel free to suggest PRs if you want to try doing some vimscript).
