### ISSUE TITLE
The mapping <localleader>ll doesn't continuous compile as it should.

### ISSUE THREAD

**Issue by paniash** [lervag/vimtex#1590]
**Issue**
Pardon me if this is a redundant question, as I'm quite new to Linux, vim, github, etc. The default mapping for continuous compilation is `<localleader>ll`, which if successful shows the message  `vimtex: Compilation completed`, whereas after an update, it shows `Compiling to pdf ... success!` which just continuous compile but rather compiles as a single shot and doesn't open the pdf viewer too, which I have to do manually for some reason.

**minimal.vim**

```vim
set nocompatible
" These are necessary unless vimtex is installed with the Vim package feature
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:tex_flavor = "latex"
let g:vimtex_view_method = "zathura"
let g:vimtex_quickfix_open_on_warning = 0
```

**minimal.tex**

```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

**Observed Behaviour**
On executing `<localleader>ll`, a single-shot compilation is done and the pdf viewer has to be opened manually.

**Expected Behaviour**
Executing `<localleader>ll` should yield a continuous compilation message along with opening the default pdf viewer.

**Comment by Bancini** [comment]
I can't reproduce this issue here with the configuration provided: zathura is opened for me after compilation (also qpdfview, with its own configuration).

But also, this configuration doesn't seem very "standard" (from the documentation). 
- g:latex_view_general_viewer: where does this variable come from?
- g:vimtex_latexmk_continuous: is deprecated, I think you should now configure latexmk compiler through g:vimtex_compiler_latexmk dictionary.

**Comment by lervag** [comment]
@Bancini Thanks for pitching in!

@paniash I've updated your post by removing the old, deprecated/nonexisting options. Can you please test if you can repeat your issue if you do `vim --servername VIM -u test.vim test.tex`, where `test.vim` is the minimal vimrc file and `test.tex` is the minimal LaTeX file (as given in your original post).

**Comment by lervag** [comment]
@paniash Please also note that the minimal vimrc/settings must load vimtex, either by using the `rtp` option (as I've updated in your original post) or by using the Vim package feature.

**Comment by paniash** [comment]
>  Can you please test if you can repeat your issue if you do `vim --servername VIM -u test.vim test.tex`, where `test.vim` is the minimal vimrc file and `test.tex` is the minimal LaTeX file (as given in your original post).

I use neovim, so these commands don't work. I'll be glad if you could let me know the suitable commands.

**Comment by lervag** [comment]
With neovim, use `nvim -u test.vim test.tex`. I assume you have `nvr` available and have read `:help vimtex-faq-neovim`?

By the way: The version of Vim you are using is very relevant and should have been a part of your original post. The [issue template] asks for the output of `:VimtexInfo`, which includes this info. I'm just saying this to make you aware that this is stuff you should provide initially when you report bugs/issues. :)

**Comment by paniash** [comment]
Here's the output of `:VimtexInfo`
```
System info
     OS: Linux 4.19.99-1-lts
     Vim version: NVIM v0.4.3
     Has clientserver: true
     Servername: /tmp/nvimGxj64P/0
  
   vimtex project: hello
     base: hello.tex
     root: /home/ashish
     tex: /home/ashish/hello.tex
    out: /home/ashish/hello.pdf
    log: /home/ashish/hello.log
    aux: /home/ashish/hello.aux
    fls: /home/ashish/hello.fls
    compiler: latexmk
      backend: nvim
      output: /tmp/nvimGxj64P/1
      configuration:
        continuous: 1
        callback: 1
        latexmk options:
          -verbose
          -file-line-error
          -synctex=1
          -interaction=nonstopmode
        latexmk engine: -pdf
    viewer: Zathura
      xwin id: 0
    qf: LaTeX logfile
      config:
        packages:
          default: 1
        default: 1
    document class: minimal
```

**Comment by lervag** [comment]
Thanks. And now for:

> Can you please test if you can repeat your issue if you do `nvim -u test.vim test.tex`, where `test.vim` is the minimal vimrc file and `test.tex` is the minimal LaTeX file (as given in your original post).

**Comment by paniash** [comment]
Now, it doesn't even compile as pdf. The cursor just moves to the right (vim key l to move to the right).

**Comment by lervag** [comment]
What is your local leader key? See `:help maplocalleader`. I think it is `\` by default, and so the mapping is `\ll` by default. Within the minimal example, you can use `:map` to see what mappings are recognized.

**Comment by paniash** [comment]
My local leader key is `,`

**Comment by lervag** [comment]
Can you give the details of what you are doing?

**Comment by lervag** [comment]
@paniash Thanks for the details provided to me by email. The screencast and your `init.vim` show me two things:

1.  You did not understand what I meant by my earlier comment:

    > @paniash Please also note that the minimal vimrc/settings must load vimtex, either by using the rtp option (as I've updated in your original post) or by using the Vim package feature.

    The point here is that you need to ensure that vimtex is loaded. In your `init.vim` you have the following line:

    ```vim
    call plug#begin('~/.config/nvim/plugged')
    ```

    Thus, your minimal `test.vim` file should start like this:

    ```vim
    set nocompatible
    let &rtp = '~/.config/nvim/plugged/vimtex,' . &rtp
    let &rtp .= ',~/.config/nvim/plugged/vimtex/after'
    ...
    ```

    That is, `&rtp` needs to include the correct path to vimtex! When this is set correctly, I believe that you should be able to perform the minimal test and observe that everything works as expected.

2.  Your `init.vim` also shows that you use `vim-polyglot`. See `:help vimtex-troubleshooting`, where I explain why this is generally bad (IMHO), and also shows how to ensure that vimtex is still loaded instead of LaTeX-Box which is provided by `vim-polyglot`.

**Comment by paniash** [comment]
>    Thus, your minimal `test.vim` file should start like this:
>    ```viml
>    set nocompatible
>    let &rtp = '~/.config/nvim/plugged/vimtex,' . &rtp
>    let &rtp .= ',~/.config/nvim/plugged/vimtex/after'
>    ...
>    ```
>    
>    
>    That is, `&rtp` needs to include the correct path to vimtex! When this is set correctly, I believe that you should be able to perform the minimal test and observe that everything works as expected.

Yes, I tried it and it worked!

> 2. Your `init.vim` also shows that you use `vim-polyglot`. See `:help vimtex-troubleshooting`, where I explain why this is generally bad (IMHO), and also shows how to ensure that vimtex is still loaded instead of LaTeX-Box which is provided by `vim-polyglot`.

I apologise for not reading the help page. I never expected `vim-polyglot` to be the cause. After removing it, `vimtex` works perfectly.

I apologise for the delay, and thank you @lervag for helping me out. Thank you very much!

**Comment by paniash** [comment]
kk

**Comment by lervag** [comment]
> P.S. Sorry for the trouble.

No problem. Happy to hear your issue is resolved.
