### ISSUE TITLE
Automatic lookup of cite entries which do not match on mathscinet

### ISSUE THREAD

**Issue by p135246** [lervag/vimtex#1592]
**Tip for enhancement:**

It would be cool if the following workflow could be implemented:

**Workflow**

The user types `\cite{string` and the completion menu with (smartly) matched items from the current bib file is shown (I am using `coc`). There is always an item "lookup at mathscinet" which, when selected, looks up `string` at [mathscinet](http://www.ams.org/mrlookup). After a succesful lookup, the user is asked to choose from the matches (it should display author, title, year for each entry). Picking something opens the current bib file in a new split window with the chosen item added as a bibtex citation filled with the data from mathscinet. After this, the cursor should point to the position to type a bibkey. The user enters the bibkey, makes changes, saves the bib file and quits. The completion gets updated.

**Notes:**

* There is a similar function for mathscinet lookup implement it jabref; see [here](https://github.com/JabRef/jabref/blob/master/src/main/java/org/jabref/logic/importer/fetcher/MathSciNet.java). However, I find its integration in the GUI quite cumbersome and would prefer the above very much.

* I do not know any editor implementing the workflow.

* I am using `coc`; hence it would be cool if the completions and menus appeared in the coc menu.

* Btw. in which variable is the path to the bib file name stored?

**Comment by lervag** [comment]
Hmm. I agree such a workflow could be interesting, but it seems way to complicated for me to aim for currently. A couple of comments:

* If we consider the feature to look up a string for search at mathscinet (or a similar place) separately and not connected to the completion, then I think this could be done. It is still complicated, I think, and I don't know exactly how to perform the lookup.

* I don't think it is possible to couple the lookup with the omnicompletion. But I think it could be possible to couple this with coc.nvim. However, I don't know how.

There is already an issue related to cite keys, see #1541. I want to address that first. I suggest you follow that thread and give me some comments when I start to implement things there. It could be a starting point towards features that are related to your suggestion. However, for now, I will not address this feature request in any near future. If you are capable and willing to work on it yourself, then I will be happy to keep the issue open, if not, then I prefer to keep it closed to help me focus on resolving the other open issues.

**Comment by lervag** [comment]
By the way, I think you might be interested in [scholarref](https://adamsgaard.dk/scholarref.html). It is a small collection of CLI utilities that may be helpful: `getdoi` will get a doi to a paper based on a search string (it uses the crossref API). `getref` takes a doi as argument and returns the bibtex entry. `shdl` downloads the pdf for a given `doi` (this may be illegal in some countries).

**Comment by p135246** [comment]
Thank you very much for your prompt answer and the reference to scholarref! I will try to incorporate it in my workflow now and will think about tweaking the software later. You are of course free to close this issue and continue developing your very cool project in other ways :-)

P.S. I would like to create a bundle of vim plugins and configurations which is easy to use even for non-vim people (e.g., that TeXMaker's key bindings work in the insert and select mode of vim and use the system clipboard) and which I can share with my friends and collaborators. I also want to type `:WriteMath` and `:CorrectMath` to switch between different work modes (e.g., turn on line numbers, conceal level, current soft line highlighting, etc...).

**Comment by lervag** [comment]
> Thank you very much for your prompt answer and the reference to scholarref! I will try to incorporate it in my workflow now and will think about tweaking the software later. You are of course free to close this issue and continue developing your very cool project in other ways :-)

No problem, and thank you for the kind words. I also appreciate the effort in raising you suggestion, and I hope you'll feel free to do so again if you have other ideas.
