### ISSUE TITLE
Autocompletion of some glossaries commands fails to match regex

### ISSUE THREAD

**Issue by vyasr** [lervag/vimtex#1594]
**Issue**

As described in #1582, any glossaries command that involves characters after the main command (`gls*`, `\acr*`, etc) will fail to autocomplete available options when the curly brace is open. Switching the regexes in autoload/vimtex/re.vim to use `[a-zA-Z]` instead of `\a` resolves this problem, but it's not clear why.

**minimal.vim**
```
call plug#begin('~/.vim/plugged')
Plug 'https://github.com/lervag/vimtex'
Plug 'https://github.com/Valloric/YouCompleteMe.git'
call plug#end()

if !exists('g:ycm_semantic_triggers')
let g:ycm_semantic_triggers = {}
endif
au VimEnter * let g:ycm_semantic_triggers.tex=g:vimtex#re#youcompleteme
```

**minimal.tex**

  ```tex
 \documentclass[aps,prl,preprint,superscriptaddress]{revtex4-2}

% Define acronyms
\usepackage[acronym,shortcuts]{glossaries}
\newacronym{test}{TEST}{Test acronym}

\begin{document}

% This will autocomplete
\gls{

% This will not autocomplete
\glsname{

\end{document}
  ```
-->

**Output from VimtexInfo**

I tested this on two separate operating systems:

```
System info
  OS: Mac OS X 10.14.6 (18G3020)
  Vim version: VIM 8.1 (1-2234)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

vimtex project: tmp
  base: tmp.tex
  root: 
  tex: 
  out:
  log:
  aux:
  fls:
  compiler: latexmk
    backend: jobs
    output: /var/folders/9g/sx2bbqmn2zb2vv876g9g4vqh2yv8rd/T/v6s5bUM/0
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config:
      packages:
        default: 1
      default: 1
  document class:
  packages:
    amsmath
    cleveref
    fontenc
    glossaries
    graphicx
    lipsum
    natbib
```

and 

```
System info
  OS: Linux 4.19.88-1-lts
  Vim version: VIM 8.2 (1-148)
  Has clientserver: false

vimtex project: tmp
  base: tmp.tex
  root: 
  tex: 
  out:
  log:
  aux:
  fls:
  compiler: latexmk
    backend: jobs
    output: /tmp/vEbQYk8/1
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config:
      packages:
        default: 1
      default: 1
  document class
```

**Comment by lervag** [comment]
I assume this is only related to the youcompleteme regex, right? That is, with `\a*` in the regex for the completor in `completion.vim`, things still work as expected?

**Comment by vyasr** [comment]
Assuming you mean `complete.vim`, yes I think that's true. At least, I haven't noticed this issue anywhere else.

**Comment by lervag** [comment]
So, first things first: the issue is currently coupled vimtex + YCM. Let's see if we can isolate: Can you start omnicompletion manually and see if it works as expected? That is, in the case where it is not autocompleting, i.e. `\glsname{`, can you do `<c-x><c-o>` to check if it shows the expected completion candidates?

**Comment by vyasr** [comment]
Yes, that does work. The pop-up menu shows with the correct list of candidates.

**Comment by lervag** [comment]
Ok. Strange. I don't really have any clue to what the problem is, and since you have suggested a solution I decided to be pragmatic and just implement that.

**Comment by vyasr** [comment]
I tried to narrow this down a bit further, but I never had any luck. I take it you were not able to replicate the problem? I think the solution I suggested should be equivalent in all cases, so as long as it works and bypasses whatever this problem is I think we're probably OK.

**Comment by lervag** [comment]
Yes, I also think the solution is safe. I never really tried to replicate with YouCompleteMe, but I tried to find reproduce without YCM with no luck. That's where my pragmatism entered. :)

**Comment by vyasr** [comment]
Makes sense. Thanks!

**Comment by lervag** [comment]
No problem! :)
