### ISSUE TITLE
Prevent spell checking in environment, etc.

### ISSUE THREAD

**Issue by NeilGirdhar** [lervag/vimtex#1596]
Code like:

```
    \begin{threeparttable}
      \begin{tabularx}{0.75\textwidth}{@{}rX@{}} \toprule
```
shows spelling errors: threeparttable, tabularx, rX

How do I disable spell-checking within environments?

**Comment by lervag** [comment]
Vimtex is not really responsible for syntax highlighting, which is the Vim mechanism for specifying regions that should/should not be spell checked. However, Vimtex does add some rules on top of the internal Vim syntax plugin for LaTex. So, spell-checking should work mostly as expected in general, but will fail for (probably a lot of) custom environments defined in various packages or by yourself.

The `tabularx` environment is a good example of something that is not supported. I could probably add support for it, but please note there might be a lot more examples that are not supported. To do that, it would be helpful with a specification of the `\begin{tabularx} ...` macro.

**Comment by NeilGirdhar** [comment]
Thanks for the detailed reply.  I just want to disable spell checking in *all* environments so that the main document text is checked, and maybe figure captions too.   I want to block it in tabular, align, etc.

**Comment by Rmano** [comment]
> I just want to disable spell checking in _all_ environments so that the main document text is checked

well --- I think it depends a lot on the environment. For example, I do not want it disabled on an `itemize`, `enumerate` or similar thing, or in a `quote`, or... a lot more. It's so specific that it's almost impossible to write a rule. 

Maybe (wild idea) some kind of magic comment (stop spell check/restart spell check) would be nice, but I do not know if it's possible --- it would be great for multilingual documents too.

**Comment by NeilGirdhar** [comment]
Okay, you're right, this is way more complicated than I thought.

**Comment by lervag** [comment]
> Okay, you're right, this is way more complicated than I thought.

Yes, that was my point. Also, that vimtex is not really dedicated to specify the syntax rules, only to provide some modifications that give 1) support to some package specific stuff, and 2) some slightly better defaults.

As I also proposed: You may give good descriptions of environments and macros defined by packages that I could consider to improve the syntax rules for.

I also want to mention that one should aim to be pragmatic. I tend to not keep spell checking enabled at all times. I have a mapping to quickly toggle it on and off, and I make sure to spell check things once in a while. When I spell check, I don't really care that there are some edge cases where there are highlighted spelling errors that don't matter (such as `rX` in your tabularx example).

**Comment by NeilGirdhar** [comment]
Ah got it.  Your work flow makes sense.  I have been leaving spell-checking until the last minute and then trying to go over a huge document with "]s", which is not fun.

**Comment by lervag** [comment]
Great. I'll close this issue, then. As mentioned, feel free to open issues concerning both syntax specific or spell specific stuff. If you do, please be specific and provide a specification of the macros/environments to help me know exactly what to implement.
