### ISSUE TITLE
`aux` directory cannot be created in Windows

### ISSUE THREAD

**Issue by statiolake** [lervag/vimtex#1601]
**Issue**

https://github.com/lervag/vimtex/commit/bfae0e82f53a4d2eb638a1dcb01046166edc02e6 introduces a directory named `aux`, which is reserved name and it cannot be created in a normal way on Windows.  This causes `git clone` or `git pull` to fail.

**minimal.vim**

No need to run Vim.

**minimal.tex**

Also no need to give a tex file.

**Commands/Input**

```console
> git clone https://github.com/lervag/vimtex
```

**Observed Behaviour**

```console
> git clone https://github.com/lervag/vimtex
Cloning into 'vimtex'...
remote: Enumerating objects: 249, done.
remote: Counting objects: 100% (249/249), done.
remote: Compressing objects: 100% (156/156), done.

Receiving objects: 100% (18553/18553), 7.85 MiB | 2.07 MiB/s, done.
Resolving deltas: 100% (10716/10716), done.
fatal: cannot create directory at 'test/tests/test-completion-labels/aux': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Expected Behaviour**

Successfully cloned / pulled.

**Output from VimtexInfo**

This is not related to actual vimtex behavior.

**Comment by lervag** [comment]
Thanks. Very strange, silly even, but I guess it should be easily fixed...
