### ISSUE TITLE
Completion on multiline citation

### ISSUE THREAD

**Issue by weber-s** [lervag/vimtex#1602]
Hi! Thanks for this amazing vim plugin!

**Is your feature request related to a problem? Please describe it.**

When adding lots of references (or with long name for references), it's usual to break lines like

```tex
\citep{veryLongNameNumber1,veryLongNameNumber2,veryLongNameNumber3,
veryLongNameNumber4,veryLongNameNumber5
}
```
but in such situation, the completion works only in the first line (where `\citep` lives).

**Describe the solution you'd like**

It would be really nice to autocomplete as long as we are in the `\citep` command.

**Describe alternatives you've considered**

Write everything in one line... But we lose clarity, and most of the time `gw` will break it.

**Additional context**

Minimal example:

```tex
\documentclass{article}
\usepackage{natbib}

\begin{document}
    
\cite{foo, //completion works
jo //completion doesn't work
}

\bibliographystyle{apalike}
\bibliography{./bibtex.bib}

\end{document}                
```

bibtex.bib file:
```bibtex
@article{john,
  title = {Title John},
  author = {John Doe and Foo Bar},
  year = {2019},
  month = may,
  volume = {54},
  journal = {Journal of Applied Meteorology and Climatology},
  language = {en},
  number = {5}
}

@article{foo,
  title = {Title foo},
  author = {Foo Bar and John Doe},
  year = {2020},
  month = oct,
  volume = {125},
  issn = {0091-6765, 1552-9924},
  journal = {Environmental Health Perspectives},
  language = {en},
  number = {10}
}

```

**Comment by lervag** [comment]
> Hi! Thanks for this amazing vim plugin!

Thanks for liking it and for providing a clear and full issue description/feature request!

> When adding lots of references (or with long name for references), it's usual to break lines like
>
> ```tex
> \citep{veryLongNameNumber1,veryLongNameNumber2,veryLongNameNumber3,
> veryLongNameNumber4,veryLongNameNumber5
> }
> ```
> but in such situation, the completion works only in the first line (where `\citep` lives).

Yes, sorry. I don't think this is easy to solve, because the regexes would become much more expensive if I were to allow them to cross line boundaries. That is, I don't think it is possible to support this, because it would lead to big lags while completing.

I'll look into it though to check if I'm right.

**Comment by lervag** [comment]
Ok, so: Currently, while completing, there are two main steps:

1. Check context to determine the start of the text to be completed. This is where the various "sub completers" are detected, such as bibtex completion. The current implementation only looks at the current line.

2. The context is used for the "sub completer" to gather candidates.

It _could_ be possible to adjust the first step to look for more context. However, I think it becomes complicted and am afraid it will make things much less robust. So I've decided not to implement this.

I'm sorry about the inconvenience, but I would propose that you try and avoid line separations while completing citations. You could add new lines afterwards, instead. I would also propose that you read the `Formatting` section in `:help vimtex-non-features`, in particular the parts about styles like "one sentence per line". I personally prefer that myself for the reasons stated in the docs, and it has the benefit of avoiding your issue.
