### ISSUE TITLE
Use main file from latemkrc

### ISSUE THREAD

**Issue by oponkork** [lervag/vimtex#1603]
`vimtex` already uses the compiler info from the `.latexmkrc` file present in the project root. It would be nice if it can read the main file/files from the same. Would be useful for the following:

- When you have a rather long latex preamble (stuff before `\begin{document}`) which you can then keep in a separate file.
- Chapters are subdivided into various files, and you are editing a chapter and want to compile.
- To invoke the viewer with the proper pdf, while editing chapters.

Minimal `.latexmkrc`
```
$pdf_mode          = 1;     
@default_files     = ('main.tex');    
$pdflatex          = "xelatex -synctex=1 -halt-on-error %O %S";    
$pdf_update_method = 2;    
$view              = "none";   
```
`preamble.tex`
```latex 
\documentclass{book} 
\usepackage{lipsum}  

```
`main.tex`
```latex
\input{preamble.tex}    
\author{lervag}    
\title{Vimtex}    
\begin{document}    
\maketitle    
\lipsum[1-1]    
\end{document}   
```

**Comment by lervag** [comment]
It should not be too difficult to parse the `@default_files` variable. It would be nice though to get a full specification for it. E.g., how would we interpret multiple files in the list?

**Comment by oponkork** [comment]
> How would we interpret multiple files in the list?

Right now all I could think of is either we pick only the first file in the list or compile all files in the list one by one, as `latexmk` does.

**Comment by lervag** [comment]
Ok, I've added this now. It works on my examples, but let me know if you find kinks.

**Comment by oponkork** [comment]
@lervag , Thanks a lot. I kind of forgot that I have opened this issue. Just realized that
compilation proceeds correctly even if I start the compiler from a different file. Also I checked it with a project where `@default_files` contains multiple files, and see that you have opted to compile only the
first file in the list. Am I right?

**Comment by lervag** [comment]
> @lervag , Thanks a lot. I kind of forgot that I have opened this issue. Just realized that compilation proceeds correctly even if I start the compiler from a different file. Also I checked it with a project where `@default_files` contains multiple files, and see that you have opted to compile only the first file in the list. Am I right?

Yes, you're right. :)
