### ISSUE TITLE
vimtex loading unreliably with latex `input`

### ISSUE THREAD

**Issue by nielsaka** [lervag/vimtex#1606]
## Issue

I am encountering inconsistent loading behaviour of vimtex across vim versions 7.4 and 8.2 and across different .tex files (main vs input). 

## Details 

The issue arises whenever I work on latex files that are `input` for a main latex file. With vim version 8.2, vimtex will only load if the main latex file is edited. With vim version 7.4, vimtex will load if either the main latex file or an input file with a latex command at the top is being edited.

If vimtex fails to load, I can force it as in #586 with `:call vimtex#init()`.

`set filetype?` shows that vim v8.2 and vim v7.4 will regard a .tex input file without (la?)tex commands as `plaintex`, whereas vim v7.4 will regard a .tex input file with a latex command as `tex`, but vim v8.2 will keep `plaintex`.

## Reproduce

**minimal.vim**
  ```vim
set nocompatible
call plug#begin('~/.vim/plug')
Plug 'lervag/vimtex'
call plug#end()
  ```

**minimal.tex**

  ```tex
  \documentclass{article}
  \begin{document}
  Hello world!
  \input{chap1}
  \input{chap2}
  \end{document}
  ```
**chap1.tex**
```tex
% !TEX root = minimal.tex
\section{Intro}
here is some text
```

**chap2.tex**
```tex
% !TEX root = minimal.tex
here is some text
```

**Observed Behaviour**
Below I have `alias`ed the respective vim versions to `vim8.2` and `vim7.4`.

Works: 

```bash
vim8.2 -u minimal.vim +VimtexCompile minimal.tex
vim7.4 -u minimal.vim +VimtexCompile minimal.tex
vim7.4 -u minimal.vim +VimtexCompile chap1.tex
```

Fails:

```bash
vim8.2 -u minimal.vim +VimtexCompile chap1.tex
vim8.2 -u minimal.vim +VimtexCompile chap2.tex
vim7.4 -u minimal.vim +VimtexCompile chap2.tex
```
with error message 

> Error detected while processing command line:
> E492: Not an editor command: VimtexCompile

**Expected Behaviour**
All commands should compile the document.

Seems like a simple problem, but it has driven me quite mad until I found out what was going on.

**Comment by nielsaka** [comment]
P.S. in practice I don't run vim on one of the input files as done above. The issue is that I open some latex input file while working on a project with many other non-latex files. I expect vimtex to load, even if the main.tex file hasn't been opened yet.

**Comment by lervag** [comment]
I believe this is not really an issue, please see `:help vimtex-comment-internal`; I think you have missed the `g:tex_flavor` option. See also `:help g:tex_flavor`.

**Comment by nielsaka** [comment]
Thanks! Setting `let g:tex_flavor = 'latex'` in my vimrc solved it. 
I'm hoping this issue will already serve a documentary purpose for people facing the same issue.

**Comment by lervag** [comment]
Yes. I am aware that the docs are already large. There's a lot of information! I try to keep things well structured and consise, but still, it's easy to miss things like this.
