### ISSUE TITLE
Cache: table of contents

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1608]
Title says all: the new cache infrastructure could be leveraged for the table of contents functionality.

**Comment by lervag** [comment]
Yes, this is probably a good idea. I don't see immediately how, though. Will have to think about it.

**Comment by lervag** [comment]
However, is the ToC really that slow? Before looking into the caching I want to have a timing example. With that, one could time before/after caching.

**Comment by clason** [comment]
It can be (~seconds) if there are a lot of labels. Again, not a critical issue, but nice to have. How would I time that? Just a simple profile?
[prof.log](https://github.com/lervag/vimtex/files/4264397/prof.log)

**Comment by lervag** [comment]
The profile is proof, thanks. But, I think, to better work on this I should have a good sample for profiling the speed and making a test similar to `test/tests/test-completion-bibtex-speed`. Would you by any chance have such a sample or be willing to make one?

**Comment by clason** [comment]
Hmm, the reason the sample is slow is that it involves a massive number of labels, so I'm not sure how to create a meaningful sample that has the same properties.

Maybe it suffices to `y3j99P` something like
```tex
\section{1}\label{sec:1}
\begin{equation}\label{eq:1}
1
\end{equation}
```
?

... Nope, but copy&pasting the equation 99 times, and then copy&pasting the section (with the 100 equations!) 99 times is definitely slow.

**Comment by lervag** [comment]
Thanks, I've made an example now and I'm pushing an update where the toc entries are cached. 

However, persistent caching seems more difficult, since toc entries are currently implemented in a more complex manner with functions and similar. This means I can simply save the toc entries to a json file.

Still, caching should at least help make the toc appear much faster when it is reopened between file saves.

**Comment by clason** [comment]
Every little bit helps ;) Thanks!

**Comment by lervag** [comment]
Great, happy to hear it!
