### ISSUE TITLE
Cache: project-specific caching

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1609]
Currently, there is only a single cache for the last recently used project. It could be useful to extend this to multiple projects by making the cache files project specific, e.g., by adding the project root filename (sans extension) to the cache file, plus possibly a hash of the containing directory path (`paper.tex`, anyone?)

This would probably require some sort of cache pruning mechanism (called by VimtexClean and possibly after 30 days or so?)

**Comment by lervag** [comment]
Yes, good point. The completion caches should be specific to each project.

Is there a simple way to "hash" a path in Vim? Or just generally make a hash from anything? If not, then I think a simple workaround would be to just remove the `/`s (or turn them into `%`s) and prepend this string to the cache name, e.g. "refcomplete_<path-string>.json".

**Comment by clason** [comment]
Good question. You could shell out to `md5sum`, but I'm not sure how portable this is (*cough*Windows). But unhashed works, too, and is more human readable. (It's not like they'll clutter up the home directory or anything.)

**Comment by lervag** [comment]
Yes, I'd prefer to keep things portable. So I guess unhashed it is. An example, the cache file for `bibcomplete` for this file:

`/home/user/path/to/project/chapters/chapter1.tex`

would be

`/home/user/.cache/vimtex/bibcomplete%home%user%path%to%project%main.tex`

Agreed? Or do you have any better ideas or thoughts on how this could go wrong?

**Comment by clason** [comment]
Sounds good to me (although the second is probably meant as a placeholder, right? ;))!

People may have strange file names (spaces, slashes, other weird stuff) -- maybe there's a canonical asciification function for paths?

**Comment by andymass** [comment]
Sorry to butt in, but re hashing strings there is sha256().

**Comment by lervag** [comment]
Ah, yes! Thanks, @andymass! It was available from versions Vim 7.4 and neovim 0.1.0, so it is safe to use as well. That's very useful to know!

**Comment by lervag** [comment]
Ok, this should be solved now. I avoided `sha256` here for now, because I thought it was better to allow recognizable cache filenames. Let me know how this works for you.
