### ISSUE TITLE
Does not work with latexmk V. 4.24 

### ISSUE THREAD

**Issue by Kebay** [lervag/vimtex#161]
On Ubuntu 12.04 there is only the latexmk version 4.24 available, but --output-directory was introduced in 4.27, see the changelog: http://users.phys.psu.edu/~collins/software/latexmk-jcc/versions.html

At the *very* least, this should be noted in the docs, but *maybe* it is enough to just omit the option.

**Comment by lervag** [comment]
Thanks for the update. I've updated the code so that the option is only added if the build directory `g:latex_latexmk_build_dir` is set to something different than the default value.

Thanks!
