### ISSUE TITLE
Cache: formatted bibtex menu 

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1610]
Currently, the bibtex cache includes the bibtex entries (title, author, etc.) used to generate the formatted label shown in the menu for omnicomplete. It seems (and I might be wrong here) that generating the formatted labels takes non-negligible time, so it might be useful to (also) cache the formatted label for reuse.

**Comment by lervag** [comment]
> It seems (and I might be wrong here) that generating the formatted labels takes non-negligible time

Not wrong. But not much time, though. Still, I think it is slightly noticable when there are a lot of references.

> so it might be useful to (also) cache the formatted label for reuse.

Agreed! The formatting should be done before the caching, it makes much more sense and should speed things up quite abit, I think.

**Comment by clason** [comment]
> Not wrong. But not much time, though. Still, I think it is slightly noticable when there are a lot of references.

Agreed; it's not a lot, but noticeable (compared to the cached labels), at least for big files. (Some people _love_ their centralized bib libraries...)

**Comment by lervag** [comment]
It seems this update makes bibcompletion an order of magnitude faster. That's fun!

**Comment by lervag** [comment]
The results are visible in the CI log as well:
- [new](https://github.com/lervag/vimtex/runs/477878680?check_suite_focus=true#step:5:86)
- [old](https://github.com/lervag/vimtex/runs/476687900?check_suite_focus=true#step:5:84)

**Comment by clason** [comment]
🚀 

(not for me, sad to say -- but that's ok; it's a huge list of candidates, and there's bound to be a limit to how fast things can be...)

As an aside, I got an error message when trying this first since there was a pre-patch cache file around. Some sort of cache invalidation mechanism would be good -- even something manual like `:VimtexCacheClear` or tied to `VimtexClean` might suffice?

**Comment by lervag** [comment]
Huh, that's strange. Are you sure? Could you show me timings before after the most recent commits?

**Comment by lervag** [comment]
Also, yes: there is a hidden mechanism now: `call vimtex#cache#clear(NAME, LOCALFLAG)`. But I agree there should be a command to clear all caches. And of course, you can just delete the files manually.

**Comment by clason** [comment]
I tried to get a clean "before cache"/"after cache" log with the new commit:

before:
```
   58   1.846998   1.825672  41()
```

after:
```
   29   0.916112   0.906003  41()
```
So a definite improvement, but as expected, there's not much room for improvement.

Interestingly, the _old_ timings are the same as the latter both before and after caching...

**Comment by lervag** [comment]
Is this measuring the completion the first time you complete in a file? Because the main improvement comes from subsequent completions. That is:

1. Open `file.tex`
2. Somewhere, write `\cite{<c-x><c-o>`
  * Before today, this would take some time X
  * After today, this should take some time slightly less than X
  * Note: X is obviously smaller when the cache exists
3. Repeat step 2
  * Before today, this would take some time X
  * After today, this should take some time much less than X

At least, this is how it appears in my measurements.

**Comment by clason** [comment]
Interesting; I see a massive speed difference in your test, but not in mine.

(in my above comment, "before" corresponds to 2., "after" to 3.)

So I'll have to investigate what is special in my files. Possibly using `strings`?

**Comment by lervag** [comment]
> So I'll have to investigate what is special in my files. Possibly using strings?

Please do, and let me know if you find something! I don't think strings should matter much, because they should not really be parsed.

> How should I modify the the bibtex-speed test to get more significant digits?

What do you mean? There should already be plenty significant digits?

**Comment by clason** [comment]
No, I'm only getting `1.0`, `0.0`, and `0.0`...

**Comment by clason** [comment]
Oh, and I should have said: This is function `41()`:
```
FUNCTION  41()
    Defined: ~/.cache/nvim/plugins/vimtex/autoload/vimtex/parser/general.vim:41
Called 58 times
Total time:   1.844613
 Self time:   1.824221

count  total (s)   self (s)
   58              0.000975   if !filereadable(a:file) || index(self.prev_parsed, a:file) >= 0
                                return []
   58              0.000022   endif
   58              0.000094   call add(self.prev_parsed, a:file)

   58              0.000070   let l:parsed = []
   58              0.000041   let l:lnum = 0
42866              0.048253   for l:line in readfile(a:file)
42808              0.029345     let l:lnum += 1

42808              0.020127     if self.finished
                                  break
42808              0.009975     endif

42808              0.053951     if has_key(self, 're_stop') && l:line =~# self.re_stop
                                  let self.finished = 1
                                  if !get(self, 're_stop_inclusive', 0) | break | endif
42808              0.009648     endif

42808              0.019114     if self.detailed
                                  call add(l:parsed, [a:file, l:lnum, l:line])
42808              0.013574     else
42808              0.051152       call add(l:parsed, l:line)
42808              0.012979     endif

42808              0.298091     if l:line =~# self.input_re
   56   0.007021   0.000391       let l:file = self.input_parser(l:line, a:file, self.input_re)
   56              0.000198       call extend(l:parsed, self.parse(l:file))
   56              0.000036       continue
42752              0.012584     endif
42810              0.017432   endfor

   58              0.000055   return l:parsed
```
This does not look like the "expensive" function in your test, so something else must be going on in my example (~20 included files? use of asymptote?) If I use my bibfile (and biblatex) in your example, it's fast...

**Comment by lervag** [comment]
Huh, ok. You're talking about `test-completion-bibtex-speed`, right? The timing is done manually with vimscript and shell with:

```vim
silent let s:time = str2float(system('date +"%s.%N"'))
```

I guess the problem is that you have a `date` that is different from mine:

```
date (GNU coreutils) 8.31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

**Comment by lervag** [comment]
Perhaps the problem is related to the parsing of `thebibliography`? You could test that by commenting out the relevant part in `complete.vim`: https://github.com/lervag/vimtex/blob/18405a6ba5800dbf819df65a6522c8905223a3e5/autoload/vimtex/complete.vim#L154-L184

**Comment by clason** [comment]
Could be, it's macOS.

Commenting that out made no difference. Hmm.

**Comment by lervag** [comment]
Strange, I don't think bibcompletion should call the general parser except for in that particular code. Consider me confused...

**Comment by lervag** [comment]
> Could be, it's macOS. --- Yep, openSUSE behaves differently.

Is there a way to use `date` on macOS to get more digits? If so, you could try to change the relevant code to use that.

**Comment by clason** [comment]
Not sure; it should behave the same (it takes the same format string). 

The general parser is also called for finding bibfiles (`find_bibs`).

Yep, that's it -- if I remove all `\include` commands from the main file, autocomplete is nearly instant (and moreso after caching).

**Comment by clason** [comment]
`\addbibresource` can only be used in the preamble; I assume the same is true(?) for `\bibliography`. Maybe the parser can bail out once it finds the `\begin{document}`? (But that would require a custom parser...)

**Comment by lervag** [comment]
> Yep, that's it -- if I remove all \include commands from the main file, autocomplete is nearly instant (and moreso after caching).

Ah, thanks, that's it.

> `\addbibresource` can only be used in the preamble; I assume the same is true(?) for `\bibliography`. Maybe the parser can bail out once it finds the `\begin{document}`? (But that would require a custom parser...)

No, `\bibliography` may be used wherever.

I'll look into this and see if it is possible to avoid parsing everything always. Caching might be key here as well.

**Comment by clason** [comment]
> No, \bibliography may be used wherever.

Ah, that kills that idea, then...

> Caching might be key here as well.

Hmm, maybe. Sounds non-trivial, though. (Requires hashing each file -- for each purpose -- to see whether it has to be parsed again?) Don't worry on my account; I'm fine with the current state.

**Comment by lervag** [comment]
> Hmm, maybe. Sounds non-trivial, though. (Requires hashing each file -- for each purpose -- to see whether it has to be parsed again?) Don't worry on my account; I'm fine with the current state.

I'm already doing something similar at some other places. I'm thinking to add a temporal delay, that is, don't update cache more often than every 5 minutes, for instance. Typically, we don't change the `\bibliography` lines very often, so I'm thinking this makes for an OK compromise. What do you think?

**Comment by clason** [comment]
Hmm, no matter what the preset for this, it's bound to trip someone up. (What if you just added the bibliography file because you noticed you forgot, and then immediately tried to autocomplete?)

**Comment by clason** [comment]
I think a general "don't reparse files whose hash hasn't changed since the last such parse" mechanism would be sufficient (and make vimtex in general snappier for larger projects such as lecture notes, theses, and books with many included chapter-files).

**Comment by lervag** [comment]
I've added simple caching similar to your suggestion. Could you check if it helps with your examples?

**Comment by clason** [comment]
Like night and day! (0.9s uncached, 0.3s cached)  🚀

**Comment by lervag** [comment]
Great, I'm happy to hear it!
