### ISSUE TITLE
Label autocomplete not working with latexmk -output-directory flag

### ISSUE THREAD

**Issue by Anthirian** [lervag/vimtex#1614]
**Issue**

I am using `latexmk`to compile my .tex file to a PDF. In order not to clutter my working folder I make latexmk write to a subfolder using the `-output-directory` flag. This unfortunately means that the *.aux files that vimtex relies upon for label completion are not properly parsed. I was hoping that vimtex would recursively attempt to search for them, but that doesn't seem to be happening. I'm not sure if I missed this in the manual, but I hope there is an option for this.

**minimal.vim**

  ```vim
  set nocompatible
  let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/bundle/vimtex/after'
  filetype plugin indent on
  syntax enable
  ```

**minimal.tex**

```tex
\documentclass{book}

\begin{document}

\chapter{First chapter}%
\label{cha:First chapter}

Hoofdstuk~\vref{cha:First chapter}.

\section{First section}%
\label{sec:First section}

Section~\ref{sec:First section}.

\end{document}
```

**Commands/Input**

After creating the mimimal files above, run the following command.

```sh
$ latexmk -pdf -output-directory=build minimal.tex
```

**Observed Behaviour**

Vim shows the following:
-- Omni completion (^O^N^P) Pattern not found

**Expected Behaviour**

I would like to complete labels as if the *.aux file was in the same directory as the *.tex file.

**Output from VimtexInfo**

```
System info
  OS: Ubuntu 18.04.4 LTS
  Vim version: VIM 8.0 (1-1453)
  Has clientserver: true
  Servername: VIM

vimtex project: report
  base: report.tex
  root: /tmp/vimtex-test
  tex: /tmp/vimtex-test/report.tex
  out: 
  log: 
  aux: 
  fls: 
  compiler: latexmk
    backend: jobs
    output: /tmp/vm8X8DK/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: book
```

**Comment by lervag** [comment]
Vimtex is (unfortunately) not omniscient, so it does not know which arguments you pass to latexmk if you run that manually. Thus, if you want to specify an output directory and have it respected by vimtex, then you need to provide this info to vimtex. See `:help vimtex_compiler_latexmk`; you need to specify the `build_dir` key, something like this:

```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_compiler_latexmk = {'build_dir' : 'build'}
```

With this, you can run latexmk manually like you showed in your example, or you can start compilation in Vim(tex) with `\ll`. Files will be put inside `build`, and completion will work as expected.
