### ISSUE TITLE
\newminted is not always correctly recognized

### ISSUE THREAD

**Issue by Nnidyu** [lervag/vimtex#1616]
**Issue**
It seems that handling of syntax highlighting with `\newminted` for text and shell-session does not fully work.

**minimal.vim**

```vim
set nocompatible
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
let g:tex_flavor='latex'
```

**minimal.tex**
```tex
\documentclass{minimal}
\usepackage{minted}
\newminted[logdump]{text}{breaklines}
\newminted[longss]{shell-session}{breaklines}

\begin{document}
\begin{logdump}
destination d_local { file("/var/log/syslog-ng/messages_${HOST}"); };
\end{logdump}

\begin{longss}
$ ls -l
$ ls -l
\end{longss}
\end{document}
```

**Observed Behaviour**

After opening the minimal file I get the following highlighting:
![screenshot](https://user-images.githubusercontent.com/293573/75852497-68caaf00-5dec-11ea-9664-9a9ac10e084b.png)
As you can notice, "logdump" and "longss" aren't correctly recognized as minted environments. Replacing the `\newminted` declaration with normal `minted` environments fixes the situation.

After some debugging I think there are at least two issues:
- shell-session is not recognized as correct name of the pygments lexer due to the hyphen, (this is not really important as I can just use "console" alias)
- "text" in `\newminted` is not correctly handled – if I replace "text" with e.g. "python" it is correctly highlighted.

**Comment by lervag** [comment]
Thanks, I think this is fixed now.

**Comment by Nnidyu** [comment]
Thanks, it seems to work now :)
