### ISSUE TITLE
Vimtex_compiler_engine

### ISSUE THREAD

**Issue by mnisicles** [lervag/vimtex#1617]
Dear Sir,

As you suggested, I removed ‘xelatex’ from my options and added the line:

```vim
let g:vimtex_compiler_engine=‘xelatex’
```

but I’m getting an issue with `\le` telling me to change me typesetting engine for fontspec.

Am I missing something?

Many thanks in advance

**Comment by lervag** [comment]
> but I’m getting an issue with \le telling me to change me typesetting engine for fontspec.

I do not understand what you mean. Please be more specific, e.g. copy output from the quickfix buffer or something like that.

**Comment by mnisicles** [comment]
Hello Lervag,

Sorry for the delay.

here's a minvimrc :


call plug#begin('~/.vim/plugged') 



Plug 'lervag/vimtex'
    let g:tex_flavor='latex'
    let g:vimtex_view_method='general'
    let g:vimtex_compiler_engine='xelatex'
    let g:vimtex_quickfix_mode=0
    set conceallevel=1
    let g:tex_conceal='abdmg'


call plug#end()


let g:vimtex_compiler_latexmk = { 
        \ 'executable' : 'latexmk',
        \ 'options' : [ 
        \   '-shell-escape',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \ ],
        \}

here's my mwe : 

\documentclass{article}
\usepackage{fontspec}

\setmainfont{Menlo}

 \begin{document}

Hello Welt !

\end{document}

and here's the quickfix result : 

/usr/local/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| Fatal Package fontspec Error: The fontspec package requires either XeTeX or LuaTeX. You must change your typesetting engine to, e.g., "xelatex" or "lualatex"instead of "latex" or "pdflatex".


Expected result would be to get rid of this error !

Many thanks for your help in advance !

**Comment by lervag** [comment]
Hi again. First: There is no such option as `g:vimtex_compiler_engine`. You are probably looking for `g:vimtex_compiler_latexmk_engines`. Please read docs for how to set it.

Next, you can simplify your setting of `g:vimtex_compiler_latexmk` to:

```vim
let g:vimtex_compiler_latexmk = {
        \ 'options' : [
        \   '-shell-escape',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \ ],
        \}
```

To fix your problem, you need to specify for vimtex that you want to use `xelatex`. You can either do it with directives, see `:help vimtex-tex-program` or by changing the default engine with `g:vimtex_compiler_latexmk_engines`.
