### ISSUE TITLE
Please add math syntax support for `breqn` package.

### ISSUE THREAD

**Issue by kevin77797** [lervag/vimtex#1618]
**Is your feature request related to a problem? Please describe it.**
The syntax  for math enviroment `dmath` provided by `breqn` package cannot be handled well.
![syntax-error](https://user-images.githubusercontent.com/15872396/75877694-3902c200-5e53-11ea-87fd-99bb705386ce.png)

**Describe the solution you'd like**
I hope you could add syntax support for the `breqn` package.

**Describe alternatives you've considered**
Math environments in `breqn`: `dmath`, `dmath*`, `dseries`, `dseries*`, `dgroup`, `dgroup*`, `darray`, `darray*`.
Text environment: `dsuspend`.

**Additional context**
Minimal working example:
```latex
\documentclass[preview]{standalone}
\usepackage{amsmath} 
\usepackage{physics} 
\usepackage{flexisym}
\usepackage{breqn}

\begin{document}
    
\begin{dmath}
[a,f(a,a^\dagger)] 
= \sum_{n_1=0}^{\infty} \sum_{n_2=0}^{\infty} \frac{1}{n_1! n_2!}
\frac{\partial^{n_1+n_2}f(0,0)}{\partial X^{n_1} \partial Y^{n_2}}
[a,a^{n_1} {a^\dagger}^{n_2}] 
= \sum_{n_1=0}^{\infty} \sum_{n_2=0}^{\infty} \frac{1}{n_1! n_2!}
\frac{\partial^{n_1+n_2}f(0,0)}{\partial X^{n_1} \partial Y^{n_2}} n_2 a^{n_1} {a^\dagger}^{n_2-1}
= \sum_{n_1=0}^{\infty} \sum_{n_2=1}^{\infty} \frac{1}{n_1! (n_2-1)!}
\frac{\partial^{n_1+n_2}f(0,0)}{\partial X^{n_1} \partial Y^{n_2}} a^{n_1} {a^\dagger}^{n_2-1} 
= \pdv{f}{a^\dagger}.
\end{dmath}

\end{document}
```

**Comment by lervag** [comment]
This should work now, please test.

**Comment by kevin77797** [comment]
It works! Thanks a lot.

**Comment by kevin77797** [comment]
It does work, but for syntax highlighting only, linting not involed. It seemed that the text inside the`dmath` env is regarded as text, not math. Comparing between the same formula in `dmath` and `equation`:
![linting-error](https://user-images.githubusercontent.com/15872396/76055506-d0305c80-5fae-11ea-817b-b0599c9c5696.png)



MWE:
```latex
\documentclass[preview]{standalone}
\usepackage{amsmath} 
\usepackage{physics} 
\usepackage{flexisym}
\usepackage{breqn}

\begin{document}
    
\begin{dmath}
[a,f(a,a^\dagger)] 
\end{dmath}

\begin{equation}
[a,f(a,a^\dagger)] 
\end{equation}

\end{document}
```
---
By the way, I found that by running cmd `call TexNewMathZone("C","dmath",1)`, vim will treat `dmath` as `equation`, as in `tex.vim`:
![tex-vim](https://user-images.githubusercontent.com/15872396/76055421-90697500-5fae-11ea-96f3-6bd1bfcc46dd.png)

One more question, could you tell me what the `suffix` argument in `TexNewMathZone` function being use to?

**Comment by lervag** [comment]
> By the way, I found that by running cmd call TexNewMathZone("C","dmath",1), vim will treat dmath as equation, as in tex.vim:

Yes, this is basically what I am doing, except I'm naming the math zones something else. See here: https://github.com/lervag/vimtex/blob/master/autoload/vimtex/syntax/p/breqn.vim

Do I understand correctly that the linting problem you have is "fixed" if you run `call TexNewMathZone("C","dmath",1)`? If so, then I would make the people responsible for the linter aware that they should not test for `texMathZoneC` specifically, but for `texMathZone.*`.

> One more question, could you tell me what the suffix argument in TexNewMathZone function being use to?

Yes, see the above link. I use `Breqn[ABCD]` as suffixes.

**Comment by kevin77797** [comment]
> Do I understand correctly that the linting problem you have is "fixed" if you run `call TexNewMathZone("C","dmath",1)`? If so, then I would make the people responsible for the linter aware that they should not test for `texMathZoneC` specifically, but for `texMathZone.*`.

To your problem, the answer is *yes*.
