### ISSUE TITLE
LaTeX math delimiters dont get toggled properly

### ISSUE THREAD

**Issue by zacmar** [lervag/vimtex#1620]
**Issue**
When using the LaTeX inline (`\( ... \)`) or display math delimiters (`\[ ... \]`), toggling the surrounding delimiter with `tsd` produces unexpedted behavior, as it tries to switch the delimiters to \left( or \left[ respectively.

**minimal.vim**
```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

**minimal.tex**
```tex
\documentclass{article}

\begin{document}
\( a^2 + b^2 = c^2 \)
\end{document}
```

**Commands/Input**
Put cursor between `\(` and `\)`, and press `tsd`.

**Observed Behaviour**
`\( a^2 + b^2 = c^2 \)` becomes `\\left( a^2 + b^2 = c^2 \\right)`

**Expected Behaviour**
`\( a^2 + b^2 = c^2 \)` becomes `\[ a^2 + b^2 = c^2 \]`

**Output from VimtexInfo**
```
System info
  OS: Arch Linux
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /tmp/nvimw0UWrr/0

vimtex project: test
  base: test.tex
  root: /home/martin/Dokumente/test
  tex: /home/martin/Dokumente/test/test.tex
  out: /home/martin/Dokumente/test/test.pdf
  log: /home/martin/Dokumente/test/test.log
  aux: /home/martin/Dokumente/test/test.aux
  fls: /home/martin/Dokumente/test/test.fls
  main parser: current file verified
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimw0UWrr/2
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -pdf
        -shell-escape
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: article
  packages:
    ifluatex
    ifpdf
    ifxetex
    shellesc
    xkeyval
```

**Comment by lervag** [comment]
I think it's a bug, but not the bug you expect. That is, the expected behaviour is for nothing to change, because `tsd` is not supposed to change the inline/display math environment limits `\( ... \)` and `\[ ... \]`, because these are not delimiters. To change these, you should use `cs$`.

I'll look into it later.

**Comment by lervag** [comment]
Thanks, I've fixed the bug. Now, as mentioned, to change between `\( ... \)` and `\[ ... \]`, you can use `cs$`. It should be intuitive and work as expected. It also allows to change into a full equation environment (or any environment, for that matter).
