### ISSUE TITLE
Previously functional "isMath()" now broken for latex documents

### ISSUE THREAD

**Issue by andresnmejiaa** [lervag/vimtex#1624]
**Issue**
Previously workign "isMath()" function written worked for several latex environments. I have switched to neovim, although I am not sure if this is relevant. Now, the function will not register the  `align` environment at all, nor does it register double dollar signs, but still works for single dollar signs.

The isMath Function is as follows:

> def isMath():
>     synstackids = vim.eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")
>     if not set(texIgnoreMathZoneIds).isdisjoint(synstackids):
>         return False
>     return not set(texMathZoneIds).isdisjoint(synstackids)
> def prose():
> 	return not isMath()

One (simple) example to try out is the following snippet:

> context "isMath()"
> snippet ,, "ldots" iA
> , \\ldots, $0
> endsnippet

And trying this in a .tex file

> \begin{align*} \end{align*}

 vs. in 

> $ $
produces the snippet in the latter, but not the former.

**Comment by lervag** [comment]
Ehm. Ok. This is not a vimtex feature. You are seemingly not relying on a vimtex feature either. So not sure why this issue is raised here.

If you want my help, then please provide a full minimal example.

**Comment by andresnmejiaa** [comment]
Well, this is shameful. I meant to raise this issue with ultisnips. My apologies!

**Comment by lervag** [comment]
No problem :)
