### ISSUE TITLE
Cache files fail to be created on Windows

### ISSUE THREAD

**Issue by rsekman** [lervag/vimtex#1626]
In 64e361ad0babb6b268234fd40d2daf688d59c89b cache file names were changed to based on the filename of the file being edited. However, only whitespace and forward slashes are escaped, but on Windows paths can also contain backslashes and colons. Thus,  `\cite{<c-x><c-o>` on Windows gives a nasty error message saying the cache file couldn't be created.

The fix is simple, #1627

**Comment by lervag** [comment]
Thank you! I've not tested the cache feature on windows, so I'm very happy if you can confirm that it now works there as well!

**Comment by rsekman** [comment]
The tests in `test/tests/test-cache`  pass on Windows. I also edited for a few hours after applying the fix without noticing any issues.

**Comment by lervag** [comment]
Thanks, good to hear.
