### ISSUE TITLE
vim-latex like .latexmain

### ISSUE THREAD

**Issue by Kebay** [lervag/vimtex#163]
vimtex searches recursively for a \begin{document}, which may be somewhat slow. I started using vimtex on a larger project now and get huge (~ 1 second) lags while editing. After I added a  `%! TEX root = foo.tex` line, the lag has gone. I experienced the lag offer a long time and tried some other things, so I doubt this is a coincidence. (It should be noted that I am using a few years old laptop (and no SSD), so other may not notice the lag at all.)

vim-latex however let you specify the main file by just appending `.latexmain` to your main file and then searching recursively for that file – which is much faster than opening all files ans searching for `\begin{document}`. This is a better solution than adding %! TEX root = foo.tex` to each file, since it only requires *one* edit per project, not per file.

The function can be found here: https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/main.vim#L401-453

**Comment by lervag** [comment]
Hi. I'm aware of the `.latexmain` functionality in vim-latex. Since I've never had any problems with lag, I've not found any need for such a solution. However, I understand your need and I could implement this.

First, I'm curious if I should first try a minor change of the recursive detection scheme I'm using. As you've noticed, I'm searching for `\begin{document}`. However, it could be much faster to search for `\documentclass`, since this is usually at the top of the file. One could then limit the search to the first few lines, which should be much quicker.

Another idea is to first do a fast grep for files that contains `\begin{document}`, and then search through only these files for files that `\input` or `\include` the current file.

**Comment by Kebay** [comment]
Of course I also welcome a speed up of the current "no special lines/files needed"-method, if that is possible.

A very fast option would be to do grep only for "\documentclass" or "\begin{document}" recursively and take the first file that appears. That can run into problems of course but on my setup it would work just fine.

**Comment by Kebay** [comment]
Oh, I have to apologize: I just noticed my test cases were all wrong. It somehow appears that editing a file on the first lines is faster than on the last lines. Also I believe you search for the main latex fail only once per file? Then the lag should vanish directly, shouldn‘t it?

This only happens for `ft=tex`, so it *might* be a fault of vimtex, but I doubt that. At the very least the problem remains after setting `let g:vimtex_enabled = 0` in vimrc.

Therefore I close here. Feel free to implement a faster search or a .latexmain functionality If you want to, but presumably I will not need that anymore.

**Comment by lervag** [comment]
If there is no problem, then there is no need to fix it. :)

But I'd like to understand why it fails. Perhaps there is something I should write in the docs? I suspect it might be the syntax plugin included with vim. Vimtex does not supply a custom syntax plugin, instead it just make some minor updates to the existing one. You could try to have `syntax off` (or remove `syntax on`) in your vimrc file to see if this helps..?

**Comment by Kebay** [comment]
It *seems* to be the `after/ftplugin/tex.vim` file of https://github.com/matze/vim-tex-fold. I have installed that package a few days ago, but today was the first time I edited a ~1000 line latex file. Removing that file helped.

**Comment by lervag** [comment]
Ah, I see. Have you tried the folding in vimtex? It should be pretty good, and by default it is not automatic (folds are updated through the `zx` mapping), which also means that the folding is very fast.

**Comment by Kebay** [comment]
Your doc says "|vimtex| can fold documents according to the LaTeX structure (part, chapter,
section and subsection)". I‘d like to have folds for mathematical environments such as `proof` or `theorem`. Is that possible as well in vimtex?

**Comment by nasenatmer** [comment]
Do you mean things like this?

```tex
\begin{theorem}
    some text
\end{theorem}
```

These are folded automatically, too. I think this applies to any environment that is invoked by `\begin{}` and `\end{}`

**Comment by lervag** [comment]
@Kebay Yes, `vimtex` also folds all environments (by default). Please see `:h vimtex-folding`, which should give an overview of the capabilities and relevant settings.

**Comment by Kebay** [comment]
Ah I see, thanks. :)
