### ISSUE TITLE
Default PDF viewer in Windows

### ISSUE THREAD

**Issue by jagjordi** [lervag/vimtex#1630]
**Is your feature request related to a problem? Please describe it.**
In windows there is no default viewer.

**Describe the solution you'd like**
In #151 you mention that Windows doesn't have a default "opener" like `xdg-open` in Ubuntu, but in fact it does. If you "call" a file name from terminal it will be opened by the default application. For example 
```
Jordi@Surface $~\Documents .\main.pdf
```
will open `main.pdf` with the default viewer.
Not sure how hard it would be to implement that but it would be nice :)

**Describe alternatives you've considered**
As of now I have `let g:vimtex_view_general_viewer = SumatraPDF` and it works fine but it would be nice having the default option.

**Comment by lervag** [comment]
> If you "call" a file name from terminal it will be opened by the default application.

It feels "sketchy" to rely on this. Is it clearly documented? Perhaps [this SO answer](https://superuser.com/questions/550138/open-file-with-default-application-from-command-line) is a possibility?

**Comment by lervag** [comment]
Could you test these?

```cmd
start "" "pdf-file-path"
explorer.exe "pdf-file-path"
```

If both work, then perhaps we could use `explorer.exe` as the default? Note, though: This would probably open pdf files in a blocking viewer, which will prevent compilation from working. E.g., if Adobe Reader opens a PDF file, then the file is locked and you can't write to it. Then `pdflatex` (and friends) will not work, and errors are abound. So, on Windows, you would need a proper viewer anyway. As such, forcing people to configure one does not feel so wrong?

Perhaps a better alternative is to let `SumatraPDF` be set by default if it is available? That is, on vimtex init we can check if SumatraPDF exists, and if it does, then we apply the suggested configuration by default (unless options are already defined).

**Comment by jagjordi** [comment]
> `start "" "pdf-file-path"`
does not seem to work, I get this as error
```
Start-Process: Cannot validate argument on parameter 'FilePath'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.```

> `explorer.exe "pdf-file-path"`
on the other hand seems to work in a non-blocking manner (at least in PowerShell v7) not sure if it would behave the same way when called from vim though.

I do agree that checking for SumatraPDF and marking it as default seems a better option, I think that most people doing LaTeX with vim in windows will be using that anyways...

Another option can be using `Start-Process` command from PowerShell https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Start-Process?view=powershell-7

**Comment by lervag** [comment]
Thanks for testing!

> on the other hand seems to work in a non-blocking manner (at least in PowerShell v7) not sure if it would behave the same way when called from vim though.

Blocking depends on the pdf viewer. But in any case, I think I'll go with checking for SumatraPDF and setting it automatically.

> Another option can be using Start-Process command from PowerShell https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Management/Start-Process?view=powershell-7

Not sure if this is good, because the default shell from Vim is cmd. Thus we would need to recommend people to change their shell setting. Or, I would need to change these settings within vimtex. Since I don't really use Windows, implementing this becomes difficult. Thus, I will rather go for the above solution which is much simpler (at least from my perspective).

----

So: I'll be glad to add this, but I would be happy if you could commit to testing things. I'll let you know when I push an update on this. Is this OK?

**Comment by jagjordi** [comment]
I'll be glad to test it (y)

**Comment by lervag** [comment]
Ok, I've added this now. Please test. It should set the defaults according to `:help vimtex_viewer_sumatrapdf` when SumatraPDF is available, else use `explorer.exe`. It would be extra good if you could test that the latter works. To do that, you would either need to ensure that `SumatraPDF` is not executable, or temporarily alter the following code:

https://github.com/lervag/vimtex/blob/37d7d725caa183a9adcef080d27df9e7a2a96b02/autoload/vimtex.vim#L298

E.g. change `executable('SumatraPDF')` to `executable('SumatraPDFXXXX')`.

**Comment by jagjordi** [comment]
What is the expected outcome when using `explorer.exe` ? The default seems to work fine but the other option doesnt seem to work. I am unsure how to get the logs, `VimtexLog` shows an empty screen,

**Comment by lervag** [comment]
> What is the expected outcome when using explorer.exe?

The idea was to make a viewer possible by default on Windows even without SumatraPDF. @Konfekt suggested to use `cmd /s start` (cf. https://github.com/lervag/vimtex/commit/37d7d725caa183a9adcef080d27df9e7a2a96b02#commitcomment-37973216), so I'll change to make that the default.

> the other option doesnt seem to work.

Not sure what is the "other option".

> I am unsure how to get the logs, `VimtexLog` shows an empty screen,

Not sure which log you want. But with `:VimtexInfo` you can see which command was run when you try to open the viewer.

**Comment by lervag** [comment]
@Konfekt I've changed the default to `start`. I think Vim (or vimtex) will automatically use `cmd /s` to run it. However, since I don't use Windows it would be very helpful for input here to check that this does what I want.

**Comment by Konfekt** [comment]
@lervag Exactly, I also think that `!` in Vim implies `cmd /c`  (*not* `/s` by the way) by `:help 'shellcmdflag' .

**Comment by lervag** [comment]
Great, then I think the current version should work. Let me know if I'm wrong :)

**Comment by jagjordi** [comment]
I have made SumatraPDF unaccessible by changing its executable name but `:VimtexInfo` still marks is as the default pdf viewer. Not sure what is happening...
```
  viewer: General
    process: 
      pid: -
      cmd: start /b cmd /s /c "SumatraPDF "C:\Users\Jordi\Documents\GitHub\master_thesis\slides/main.pdf" >nul"
```

**Comment by lervag** [comment]
Does it work, i.e., does it still open the PDF in SumatraPDF? If so, then your change did not really do what you wanted, I think.

**Comment by jagjordi** [comment]
No, it does not open the viewer.

**Comment by lervag** [comment]
Did you restart Vim/neovim? Did you update your vimrc?

**Comment by jagjordi** [comment]
Yes, I restarted Vim. My vimrc hasn't changed (just to claridy I do **not** have `g:vimtex_view_general_viewer` set.

**Comment by lervag** [comment]
Could we chat on Gitter?
https://gitter.im/vimtex-chat/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

**Comment by jagjordi** [comment]
I can confirm that everything works fine now 👍

**Comment by lervag** [comment]
Great, happy to hear it!
