### ISSUE TITLE
return the cursor back when closing an environment with ]]

### ISSUE THREAD

**Issue by mbsariyildiz** [lervag/vimtex#1631]
Hello!

Thanks for developing this plugin.

I find the mapping `]]` quite useful to quickly create environments. I think it would be better if after the environment is closed the curser returns to the closing curly brace of the environment opening.

For instance, if `]]` typed after `\begin{enumerate}` the cursor goes to the end of the line: 
```latex
\begin{enumerate}\end{enumerate}(cursor is here)
```
in what I request:
```latex
\begin{enumerate}(cursor is here)\end{enumerate}
```

I am not a vim expert. If this is something that can be fulfilled very cheaply please tell me.

Many thanks

**Comment by lervag** [comment]
Sorry, but no. `]]` is intended for a workflow where you write linearly. I think what you want is something different: snippets. It is more convenient than `]]`. See `:help vimtex-nf-snippets` for more information.

**Comment by mbsariyildiz** [comment]
Thanks for your return. I will check the snippets to see something useful my me.
