### ISSUE TITLE
On Windows, VimtexInfo fails because variable systeminfo not defined

### ISSUE THREAD

**Issue by vando026** [lervag/vimtex#1632]
**Issue**

On my Windows machine, VimtexInfo fails. 

**minimal.tex**

This issue is observed also when using the minimal example. 

**Commands/Input**

:VimtexInfo

**Observed Behaviour**

[
![Capture](https://user-images.githubusercontent.com/36604253/77226872-d5c79e00-6b7b-11ea-83d6-608460733c6f.PNG)
](url)

**Expected Behaviour**

Output from VimtexInfo

**Output from VimtexInfo**

VimtexInfo does not produce output because it fails with the above error message. 

I found the variable `systeminfo` called in the `get_os_info()` function in the info.vim file, but I dont see the `systeminfo` variable defined anywhere. If I comment out the line

 `let s:win_info = vimtex#process#capture(systeminfo)` 
and replace it with 
`let s:win_info = "MyTest"` 

then VimtexInfo works. 

Please can you take a look at this. It should be an easy fix, as VimtexInfo seems to be a useful command.

**Comment by lervag** [comment]
Thanks, should be fixed now. `VimtexInfo` is indeed useful, in particular for providing me with useful details on systems for issue reports. :)
