### ISSUE TITLE
Please provide github releases

### ISSUE THREAD

**Issue by Segaja** [lervag/vimtex#1636]
Hello,

as I would like to package vimtex to be usable for archlinux users by installing an AUR package it would be really helpful if you could provide github releases whenever you feel ready that the latest changes are stable for usage.
That way people could be sure that the release they are using is working (apart from known bugs maybe) and don't have to hope that the master doesn't break with latest changes (which is not uncommon in software development).

While I still can build a package for this without the releases by just pinning to an arbitrary commit I choose it would still be nicer to have a versioning defined from you (upstream) which I can build on.

Best regards

**Comment by lervag** [comment]
Thanks for the suggestion. There are mainly two reasons why I don't use releases and versioning:

1. I've spent my energy on working with issues and improvements, and
2. I don't really know "how" to properly work with releases.

I guess these are not very good reasons, and I can be persuaded to change. However, it would be very helpful to get some guidence on how to do it properly. Both with respect to the Git workflow, github workflow, and on how to decide the version numbers.

That said, I don't really support the idea of installing Vim plugins via system package managers. Could you give some good reasons why anyone would want to do that instead of installing them on a per user basis with e.g. plugin managers like Vundle, vim-plug, pathogen, etc? IMHO, installing plugins at the system level adds a level of confusion in the sense that a user may not really know which plugins are active.

Still, I won't object or interfere with anyone who wants to do this, and I understand why you in this particular case would prefer more formal releases/versioning.

**Comment by Segaja** [comment]
Well I'm not sure how much explanations to versioning. I like the idea of doing version numbers with major.minor.bugfix:
- major: the major version number which only changes if you introduce breaking changes into the software
- minor: this number changes when you introduce new features which people can you but don't break anything
- bugfix: this version is used if you fix bugs in the existing features but don't add anything new or break any existing functionality.

In general this is done by tagging the repository at the given time. So for example you could now define that the current code is version "1.0.0" and add a git tag to it. then after a while when a certain amount of changes was introduced in the code you could update the number according to the top rules.
In general I think it doesn't take too much time to do this if you do it regularly and maybe have a changelog that tracks what kind of changes were added. That way it would be easy to determine what kind of version increase is needed.

In regards to vim plugins and how to handle them:
I guess there are a lot of ways and vim plugin managers are one of them. Since I use my PC alone at home I don't have to worry about other people not knowing which plugins are active. But I do understand this very valid point.
Furthermore the one thing I like about linux in general is that as a base rule you have one source where the programs you use come from. If I can I try to void mixing this with other "local / manual" sources.

But this is just my current opinion and I'm open to arguments. If there are good arguments for vim plugin managers in general and one in particular then I wouldn't mind trying it out and maybe change my opinion.
Should that happen would the packaging idea be obsolete.

**Comment by lervag** [comment]
> In regards to vim plugins and how to handle them:
> I guess there are a lot of ways and vim plugin managers are one of them. Since I use my PC alone at home I don't have to worry about other people not knowing which plugins are active. But I do understand this very valid point.
> Furthermore the one thing I like about linux in general is that as a base rule you have one source where the programs you use come from. If I can I try to void mixing this with other "local / manual" sources.

Yes, I agree, except for certain cases such as Vim plugins.

> But this is just my current opinion and I'm open to arguments. If there are good arguments for vim plugin managers in general and one in particular then I wouldn't mind trying it out and maybe change my opinion.
> Should that happen would the packaging idea be obsolete.

Your Vim configuration should be localized to your vimrc file and/or your `~/.vim` folder. My configuration is [here](https://github.com/lervag/dotvim). I mostly keep everything in my `vimrc` file, but I also have some custom, personal plugins and similar all bundled together.

By keeping this all in a git repo, it is very easy to set up my Vim configuration on any computer or server. I don't need sudo access to install things on a system level. I can just clone my vim files and perform an initial installation of plugins, then everything works.

Personally, I think this is a much better way than to install your plugins at the system level.

----

Regarding versioning: I guess what you suggest is called [semantic versioning](https://semver.org/)? I'll consider it, but I'm not sure I see the benefits. Perhaps other users have some opinions on this? @kiryph @clason @Konfekt

**Comment by clason** [comment]
For what it's worth, I agree: vim plugins are fundamentally different from system packages (more akin to configuration files than libraries). There's too much pain in dealing with obsolete or less than well maintained packages, and you will have to deal with people having (often unknowingly) installed old versions from different sources. (I can see the same with TeX: my first recommendation is always "ignore packages, just install texlive somewhere and put its path first.)

Regarding versioning: I see only two motivations for this.
1. You have other software that depends on yours and needs to be sure of the correct API. (maybe coc-vimtex?)
2. You want to have an easy way of knowing if people have the latest fixes. (what's your version? that's too old, please upgrade.)
Point 2 might be relevant (especially if hooking into checkhealth), but in general I don't see any reason to support multiple versions, and vim-plug (and equivalent) provide a too convenient way of staying up-to-date. I don't see many vim plugins that have a consistent release strategy.

Actually, there's a third point that _might_ be relevant for you: documenting progress (elevating the changelog from `:h vimtex` to the github releases page). In this case I'd not worry about semver (that is only important regarding point 1) and just bump major or minor version whenever you've implemented a feature that you are particularly proud of. However, if you start, you probably need to keep doing it -- having a single four-year old release is worse than no release at all...

**Comment by Segaja** [comment]
Hm, I can see some pros in the idea of using a vim plugin manager.

To be honest I'm a bit irritated that vim plugins don't come in proper versioning as this sounds very error prone to me.

Does vim-plug always update the repositories when you start it? Or warn you on startup if you have old versions?
Otherwise it is also prone to running old versions of plugins.

**Comment by clason** [comment]
@Segaja What errors precisely would you be worried about here? (Asking honestly.) Vim-plug doesn't update automatically, but provides a command `PlugUpdate` to `git pull` all plugins (assuming you specified a repo, which is the usual way of using it). Of course, you can also specify branches or tags rather than master, or specify a local directory if you don't want to follow someone else's development at all. This way you have complete control over what and when to update.

I think it's worth keeping in mind that the way of using vim plugins is rather different from usual, system-level, software. The mind-model here is a very deep configuration of vim, piggybacking on other people's work -- it's much more usual to fork and adapt other people's plugins to your taste. Also, many vim plugins are _old_ and pretty much in bugfix-only maintenance mode, so versioning is much less of an issue. (You either never upgrade, or always want to be on the latest.)

**Comment by Segaja** [comment]
Hm maybe I'm just too deep in software development and overthink the process in case of vim plugins. 

What could happen is that some plugin author changes how a function or keybindings works and this breaks a feature of the plugin (by intention). In this case in other software the author would make a new major version out of it to make the users aware that something big changes in this update.
That way nothing breaks for the users on update that they don't know about.
I'm mainly working with PHP and there you have semver and composer where you can say as version constraint "1.*" and you get any minor or bugfix version upgrade but not a major one unless you actively choose to by update the constraint.

I understand that the philosophy is different for vim plugins and I will think about how to deal with that. It might turn out that then it makes sense to use the plugin manager as there is no feasible way to define versions for a plugin like this.

I will also have a look into vim-plug and see how it feels and performs for me. I would definitely want some form of auto-update in order to not forget it.

**Comment by clason** [comment]
> Hm maybe I'm just too deep in software development and overthink the process in case of vim plugins.

That was the point I was politely trying to make ;)

> I will also have a look into vim-plug and see how it feels and performs for me. I would definitely want some form of auto-update in order to not forget it.

I whole-heartedly recommend vim-plug; it's a really nice work and seems to be the most used plugin manager (others are dein -- probably the second most used one -- and vundle). I'm not sure I'd want to update on every start (it works in parallel but not async); I've put a simple mapping in my vimrc
```viml
nnoremap <silent> <leader>pu :PlugUpgrade \| PlugUpdate<cr>
```
that I'm muscle-trained to spam whenever I start a work-session. (`PlugUpgrade` updates vim-plug itself; doesn't happen often, but why not?)

**Comment by lervag** [comment]
Thanks for pitching in, @clason! I'll close this then. Might consider releases at one time, but for now, I'll rather focus on just continuously improving things.
