### ISSUE TITLE
The file name aux.vim is incompatible in Windows

### ISSUE THREAD

**Issue by Joe-C-Ding** [lervag/vimtex#1639]
`Aux` is a reserved keyword in Windows, and cannot be used as a file/dir's name. Adding suffixes doesn't help it, so `aux.vim` is still a invalid name.

in 3a3095e3, the `general.vim` was split into 3 files, one of them was `aux.vim`.  For Windows users, checking out this commit (or later commits) will result in errors.

I understand that `aux.vim` is a good and intuitive name for that file, but I hope you don't mind changing its name.

**Comment by lervag** [comment]
Wtf, Windows is so weird! Thanks, I'll find a different name later this evening.

**Comment by Joe-C-Ding** [comment]
Thanks for your quick response.

**Comment by lervag** [comment]
Thanks for reporting! :)
