### ISSUE TITLE
mupdf VimtexRsearch error

### ISSUE THREAD

**Issue by rafaqz** [lervag/vimtex#164]
I'm not sure if this meant to work out of the box. Its compiling fine and selecting the mupdf window but actually neither direction sync is working, at least this one gives me an error.

Here's the full vim error output:

```
Calling shell to execute: "(xdotool search --class MuPDF) >/tmp/vWA413u/10 2>&1"
Calling shell to execute: "(synctex view -i 132:2:'/home/my/latex/dir/essay_2.tex' -o '/home/my/latex/dir/essay_2.pdf' | grep -m1 'Page:' | sed 's/Page://' | tr -d '^@') >/tmp/vWA413u/11 2>&1"
Calling shell to execute: "(xdotool search --class MuPDF) >/tmp/vWA413u/12 2>&1"
:!xdotool windowfocus 73400403

Calling shell to execute: "xdotool windowfocus 73400403"

Calling shell to execute: "(xdotool search --class MuPDF) >/tmp/vWA413u/13 2>&1"
Calling shell to execute: "(xdotool getwindowname 73400403 | sed 's:.* - \([0-9]*\)/.*:\1:' | tr -d '^@') >/tmp/vWA413u/14 2>&1"
Calling shell to execute: "(synctex edit -o "3:288:108:/home/my/latex/dir/essay_2.pdf"| grep 'Input:' | sed 's/Input://' | head -n1 | tr -d '^@' 2>/dev/null) >/tmp/vWA413u/15 2>&1"
Calling shell to execute: "(synctex edit -o "3:288:108:/home/my/latex/dir/essay_2.pdf"| grep -m1 'Line:' | sed 's/Line://' | head -n1 | tr -d '^@') >/tmp/vWA413u/16 2>&1"
                                                                                                                                                                           Error detected while processing function 10:
line   35:
E172: Only one file name allowed: edit SyncTeX ERROR: No SyncTeX available for /home/my/latex/dir/essay_2.pdf
E492: Not an editor command: usage: ...
```

I'm on arch linux, and its happening with all other vim plugins uninstaled.

**Comment by lervag** [comment]
Which shell are you using? Do you have `xdotool` installed` What happens if you try the commands directly in the shell? For example `xdotool search --class MuPDF`.

**Comment by rafaqz** [comment]
bash, with xdotool. It reurns 75497555 so I guess that part is working, and 
`xdotool getwindowname 75497555` returns `essay_2.pdf - 3/3 (96 dpi)` 

All those commands work manually until the last one, which gives the `No synctex available for  for /home/my/latex/dir/essay_2.pdf` response. Is there meant to be a synctex file in the directory?

**Comment by rafaqz** [comment]
Ok solved, just needed to delete all the temp files in the directory with the tex file and start again. I hadn't set up synctex yet when I first compiled it.

**Comment by nasenatmer** [comment]
Yep, a file named `projectname.synctex.gz` is essential for synctex to work :)

**Comment by lervag** [comment]
Ah, yes. It is mentioned in the docs, but it could perhaps be clarified. In any way, good to hear there is no problem.
