### ISSUE TITLE
Support for blacktex

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1640]
[Blacktex](https://github.com/nschloe/blacktex) is an awesome linter-like tool that fixes tex antipatterns. It would be great if `vimtex` provides support for this, so that we can run this from inside `vim` rather than at the command-line.

**Comment by krishnakumarg1984** [comment]
One idea is that, the user could have a mapping (and/or a vimtex command) to run the tool from within `vim` and update the current buffer with the fixes.

**Comment by lervag** [comment]
I'm not so sure. Ale has support for fixers as well as linters. I also notice that it is very lacking wrt. documentation. It only provides a single example of what it does and then refers to l2tabu documentation of antipatterns.

It should already be quite "trivial" to make a custom command. First, Vim already supports filters, see `:help filter` or `:help :range!`. A command to filter the entire file looks like this:

```vim
command BlackTex %!blacktex
```

So, I'm not saying I won't add something for this, but I want to understand it better before I decide.

**Comment by krishnakumarg1984** [comment]
Agree. I am happy with manually piping this as a filter. Unless anyone else has a better idea, we can close this issue in a few days?

**Comment by lervag** [comment]
Sounds good! I just tested it, and using it with the filter feature of Vim works just as expected.

**Comment by krishnakumarg1984** [comment]
Great! Do you want to just close it off?

**Comment by lervag** [comment]
Yes. I'll mention blacktex in the docs.

**Comment by krishnakumarg1984** [comment]
@lervag  For some reason, the piping to `blacktex` does not work for me in either vim or neovim.
I get an error message stating `blacktex: error: the following arguments are required: infiles`. After executing the command, my tex buffer is just completely wiped off! Here is a minimal non-working example.

``` tex
\documentclass{article}
\begin{document}
Hello world!

Because   of $$a+b=c$$ ({\it Pythogoras}),
% @johnny remember to insert name
and $y=2^ng$ with $n=1,...,10$, we have ${\Gamma \over 2}=8.$
\end{document}

```

**Comment by lervag** [comment]
It's because `blacktex` does not read from stdin. Instead, you can use it like this: `:%!blacktex %`; the last `%` is replaced with the name of the current file. It seems to work well for me.

**Comment by krishnakumarg1984** [comment]
@lervag That worked! thank you!

**Comment by lervag** [comment]
No problem, happy to hear it!

**Comment by krishnakumarg1984** [comment]
It's probably worth mentioning the `--keep-comments` flag of `blacktex` since it aggressively gets rid of every single comment in the source file - every single comment!

**Comment by krishnakumarg1984** [comment]
How can I run `blacktex` automatically on save?

**Comment by lervag** [comment]
You can use an autocommand, something like this:

```vim
augroup vimrc_vimtex
  autocmd!
  autocmd FileWritePost *.tex %!blacktex --keep-comments %
augroup END
```

You could play around with it, e.g. using an `echo "blacktex ..."` instead of the actual blacktex command to verify that it runs at the expected times.

**Comment by krishnakumarg1984** [comment]
Thanks
