### ISSUE TITLE
the vimtex didn't load in some types of tex files

### ISSUE THREAD

**Issue by Unknown-Chinese-User** [lervag/vimtex#1642]
**Issue**
The vimtex doesn't load when I open a new file or the type of tex files that don't contain `\begin{}`and`\end{}`

**minimal.vim**
```
call plug#begin('~/.config/nvim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'lervag/vimtex'
call plug#end()
```

**minimal.tex**
when my file has `\begin{}`and`\end{}`, the vimtex and coc-vimtex works.
```
\begin{}
\end{}
```
But when it is a blank file or some file don't contain  `\begin{}`and`\end{}`, coc.nvim will rise a error `[coc.nvim]vimtex not loaded`

**Output from VimtexInfo**
__vimtex is not accessable in the error file , this is the output of my main.tex__
```
System info
  OS: Mac OS X 10.15.3 (19D76)
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /var/folders/nw/lvt9p60n3hgdl98kwm5hp1pc0000gn/T/nvim1e8Sf3/0

vimtex project: main
  base: main.tex
  root: /Users/mio/homework
  tex: /Users/mio/homework/main.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  tex program: xelatex
  source files:
    main.tex
    physics/5.tex
  compiler: latexmk
    backend: nvim
    output: /var/folders/nw/lvt9p60n3hgdl98kwm5hp1pc0000gn/T/nvim1e8Sf3/2
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -xelatex
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: elegantnote
  packages:
    bm
    cases
```
this is information in vimtexinfo. When I go to file physics/5.tex or open it directly, the vimtex is not loaded. The same problem happens when I open a new file.

**Comment by lervag** [comment]
Please read the docs, `:help vimtex-introduction`. The answer is given in the first 230 words.

**Comment by Unknown-Chinese-User** [comment]
In fact I have skimmed the introduction and used regular search to find '\\begin' and 'coc', but I still can't find why. I see one of my friends who can use vimtex when creating a new file, so I wonder if I had made something wrong.

**Comment by Unknown-Chinese-User** [comment]
I copied my friends' vimrc,and it now works.
Thank you!

**Comment by lervag** [comment]
> In fact I have skimmed the introduction and used regular search to find '\begin' and 'coc', but I still can't find why.

It does not have anything to do with `\begin` or `coc`. From `:help vimtex-comment-internal` (which is at the very beginning of the introduction):

```
Vim will generally autodetect filetypes automatically. In most cases this
works as expected, however, in some cases it will detect a file with the `tex`
suffix as a |plaintex|. To prevent this, one may set the option
|g:tex_flavor| in ones `vimrc` file, that is: >

  let g:tex_flavor = 'latex'
```

So, the answer to your question is to add that last line to your vimrc.

> I copied my friends' vimrc,and it now works.

Great. But beware, if you are a Vim beginner, then I suggest that you learn Vim progressively and try to avoid copying to much stuff that you don't really understand.
