### ISSUE TITLE
How to automatically toggle the conceallevel variable between 0 & 2 for vertically split tex buffers?

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1645]
Apologies. This is more of a question configuring `vim` for `latex` to work well with `vimtex` rather than a core `vimtex`-specific bug/issue. In `:h ft-tex-syntax`, we have the following sentence about `tex-conceal` (see `:h tex-conceal`)

>One way to use this is to have vertically split windows (see |CTRL-W_v|); one
with `conceallevel` at 0 and the other at 2; and both using `scrollbind`.

How can I configure this (using autocommands?). By default, I have set `conceallevel=2` to see the nice math characters rendered in `utf-8`. However, to edit a line containing math, I need to set it to `conceallevel=0`. After editing, I have to manually set the conceal level back to 2. This becomes tiring and repetitive soon.

When I vertically split my `tex` buffers (and only `tex` buffers), I'd like to automatically have the exact configuration mentioned in the documentation (i.e. conceal level set to 0 and scrollbind applied to all the buffers). When I close all the splits, I'd like to have the conceal-level restored to 2.

**Comment by lervag** [comment]
First: Did you know about the `:help concealcursor` option? It allows to specify that the cursor line is concealed or not and in which mode it is concealed.

If that is not sufficient, then I would propose an autocommand to toggle between conceallevels when you enter/exit insertmode. Something like this:

```vim
augroup vimrc
  autocmd!
  autocmd InsertEnter *.tex set conceallevel=0
  autocmd InsertLeave *.tex set conceallevel=2
augroup END
```

This should change things so nothing is concealed when you are in insert mode, and everything is concealed in other modes.

If you insist on the split window behaviour, then I would propose to instead make a mapping that sets the windows up as you want them, and perhaps another one to restore single window mode. That would make it easy. Something like this should work:

```vim
nnoremap <f1> :call SetupSplits()<cr>
nnoremap <f2> :call Restore()<cr>

function! SetupSplits() abort
  split
  set conceallevel=2
  set scrollbind
  wincmd w
  set conceallevel=0
  set scrollbind
  syncbind
endfunction

function! Restore() abort " {{{1
  close
  set conceallevel=0
  set noscrollbind
endfunction
```
