### ISSUE TITLE
Backward and folds

### ISSUE THREAD

**Issue by mivbvim** [lervag/vimtex#1647]
Hi,

I use vimtex with forward and backward search with zathura. It's work perfectly. 

My question is about the backward process. When I come back from zathura to vim, vimtex automatically refreshes the folds. 
Is there a way to disable this option ? 

Thank you very much for your work. Your plugin is incredible good.

Best

**Comment by lervag** [comment]
> I use vimtex with forward and backward search with zathura. It's work perfectly.

> Thank you very much for your work. Your plugin is incredible good.

Thanks for the kind words, I appreciate it!

> My question is about the backward process. When I come back from zathura to vim, vimtex automatically refreshes the folds.
Is there a way to disable this option ?

You can try to add `let g:vimtex_fold_manual = 1` to your vimrc file. I also recommend the FastFold plugin.

**Comment by mivbvim** [comment]
Thank you very much for your quick and precise answer. It works !

Another question (should I open a new tread ?) : is there a way with vimtex to define a latex item block (in itemize or enumerate environment) as a text-object ? 

Best

**Comment by lervag** [comment]
No problem! :)

You can use `ie` and `ae` as text objects for the current surrounding environment. It should work with any environment. There is no way to define a text object for a specific text object at the moment, and I don't really see the need for it.

**Comment by mivbvim** [comment]
I use ie and ae all the time. Very helpful ! In fact, I use text object as soon I can. 

If you have a big itemize and want to work with an item part, it could be usefull to say to vim : yank this item (take the "\item" with the 'around' option and don't take it with the "inner"). At the moment, I write my item as "paragraph", so that I can use ip or ap to deal with them. 
But when  I am working on a latex text written by a colleague, it cold be interesting to have that to change/ryank/eformat the text.

In any case, it is clear that it is more a detail and not really important.

Thank again for your work !

**Comment by lervag** [comment]
> If you have a big itemize and want to work with an item part, it could be usefull to say to vim : yank this item (take the "\item" with the 'around' option and don't take it with the "inner"). At the moment, I write my item as "paragraph", so that I can use ip or ap to deal with them.

Sorry, then I misunderstood. I can see that this is interesting. Could you open a new issue with this suggestion? I think it could be useful and would therefore consider to add it. It would then also be useful to have some more and less complex examples that should work; I like to write tests before I work on a real implementation.
