### ISSUE TITLE
vimtex-imaps are not working anymore in align environment afrer updataing vimtex

### ISSUE THREAD

**Issue by ritajitk** [lervag/vimtex#1648]
vimtex-imaps are not working in align environment. I am seeing this behavior after updating the vimtex. I am able to use those imaps in math mode i.e, $...$, $$...$$ , in equation environment not not in align anymore.

**Comment by lervag** [comment]
Does it work if you quit vim and reopen the file? Can you provide a minimal LaTeX file where this problem occurs?

**Comment by ritajitk** [comment]
This problem persisted even if I reopened files. In which files it worked before is not working in them also. Here is a minimal LaTeX file. 

\documentclass{article}
\usepackage{amsmath}

\begin{document}
\begin{align}
        a_a &= \sin(\alpha) \\
        \beta_a &= a
\end{align}
$\alpha \beta \gamma \nu$
\begin{equation}
        \alpha = \beta \gamma
\end{equation}
\end{document}


I am using vim-plug as my plugin manager, with these plugins
- delimitMate
- supertab
- vim-snippets
- vimwiki
- nerdcommenter
- lightline.vim
- goyo.vim
- vimtex
- vim-unimpaired
- ctrlp.vim
- ultisnips

this is my tex.vim

setlocal spell
set foldmethod=expr
set foldexpr=vimtex#fold#level(v:lnum)
set foldtext=vimtex#fold#text()
let g:vimtex_view_general_viewer="zathura"
let g:vimtex_view_method = "zathura"
noremap <buffer> <silent> yot :VimtexTocToggle<CR>
set conceallevel=2
let g:tex_conceal='abdmg'
"let g:vimtex_quickfix_mode=0
let g:vimtex_quickfix_open_on_warning=0
set complete-=i
nnoremap <leader>lp :VimtexCompileSS<CR>
nnoremap <C-LeftMouse> :VimtexView<CR>
let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : 'latexbuild',
    \}

let g:vimtex_compiler_latexrun_engines = {
        \ '_'                : 'pdflatex',
        \ 'pdflatex'         : 'pdflatex',
        \ 'lualatex'         : 'lualatex',
        \ 'xelatex'          : 'xelatex',
        \}
let g:vimtex_imaps_enabled=1

**Comment by ritajitk** [comment]
I tried to check out some old commits,

`git checkout 66fad64bb95`

this one is around January 9, 202. This expands `a to \alpha, and all imaps work in align environment.

**Comment by lervag** [comment]
> this is my `tex.vim`

I've cleaned it up for you. The following should do exactly the same:

```vim
setlocal spell
set conceallevel=2
set complete-=i

let g:tex_conceal = 'abdmg'

let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : 'latexbuild',
    \}
let g:vimtex_fold_enabled = 1
let g:vimtex_imaps_enabled = 1
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_view_method = 'zathura'

noremap <buffer> <silent> yot :VimtexTocToggle<CR>
nnoremap <leader>lp :VimtexCompileSS<CR>
nnoremap <C-LeftMouse> :VimtexView<CR>
```

Currently looking into the issue; I can reproduce it.

**Comment by lervag** [comment]
Thansk for reporting. There was a regression bug that was not catched by the test suite. I've added a test for it and fixed the issue.
