### ISSUE TITLE
item as a text-object

### ISSUE THREAD

**Issue by mivbvim** [lervag/vimtex#1650]
Hi,

as discussed in another thread, I open a new issue concerning a text-object implementation for (latex) `\item` from `itemize` and `enumerate` environments.

Example:

```tex
\item blablabla (..) end-of-item-zone
```

Expected: if the cursor is between `\` and `e` (of zone), the text-object (for example, mapped to `m` as ite`m`, and especially because I don't know about another vim text-object that uses `m`, but it can be any other symbol):

- `am` acts on `\item blablabla (..) end-of-item-zone`
- `im` acts on `blablabla (...) end-of-item-zone`

Possible difficulties: to detect what is exactly an "item zone", and what is its end. For example

```tex
\begin{itemize}
\item blablabla
\item \begin{enumerate}
         \item (...)
         \item (...)
         \end{enumerate}
\end{itemize}
```

When we are in the second item of the itemize environment, the text-object have to take the items of higher levels.

I do not know if it is reasonable and feasible. I imagine it could be a useful tool for writing latex in vim.

Best

**Comment by lervag** [comment]
Thanks! I'll probably work on this and implement a solution, but it might take some time before I do it. I think `m` is fine as a text object "name". An alternative could be `i`?

**Comment by mivbvim** [comment]
"i" is perfect !

**Comment by kiryph** [comment]
I use additional text objects and I consider the indentation-based custom text object which uses `ii/`ai` very useful. This choice has been taken by most plugins which implement this:

- https://github.com/michaeljsmith/vim-indent-object
- https://github.com/kana/vim-textobj-indent/blob/master/doc/textobj-indent.txt#L186-L189
- https://github.com/hgiesel/vim-motion-sickness#indent-text-objects

@lervag you have defined this yourself here: https://github.com/lervag/dotvim/blob/master/personal/plugin/text-object-indent.vim

I would vote against using `ii`/`ai` and vote for `im`/`am`. The only text objects I know which use `im`/`am` are filetype specific:

- $VIMRUNTIME/ftplugin/ruby.vim
- https://github.com/python-mode/python-mode

**Comment by mivbvim** [comment]
Hi, 

maybe the name of the text-object is not so relevant. 

For example, if you want "the item-latex" tex-object is mapped on im/am, it is sufficient to add in your .vimrc 

autocmd filetype tex 
			\ xmap im <plug>(vimtex-ii) |
			\ xmap am <plug>(vimtex-ai) |
			\ omap im <plug>(vimtex-ii) |
			\ omap am <plug>(vimtex-ai)

(I assume here the vimtex text-object is mapped on ii/ai, and the vimtex corresponding function names are vimtex-ai and vimtex-ii.)

**Comment by kiryph** [comment]
@mivbvim 
My comment was about how to choose default mappings not about if it is possible to configure them in `$MYVIMRC`. I think being sensible about the defaults helps everyone to not go mad on finding non clashing mappings, in particular newbies. I know that the perfect choice is impossible. However, I would follow a few guidelines:

**Popularity of text object indentation**  
If you search on https://vimawesome.com/?q=text+object for text object, the text object based on indentation is the highest ranked (excluding vim-textobj-user which does not provide any text objects on its own). The ranking is based on vimrc's uploaded to github.

**Higher priority of more universal text objects than specific ones**  
The item-latex text object is a very specific one. The indentation text object is more universally applicable and therefore should get higher priority.

**Respect existing established plugins**
I would also respect claims of plugins which exist for a longer period of time (here at least 10 years) except there is a good reason to overwrite them e.g. not useful for TeX documents.

**Minimize necessary configuration**
I would prefer defaults which work for most people without configuration taking into account relevant popular plugins. One does not step on anyone toes by choosing `im`/`am` instead of `ii`/`ai`. Expecting from existing user to add configuration lines to their vimrc is not very polite.

I know all points can be argued about. However, I think in this case it is easy to choose `im`/`am` because there is no history for this new text object.

**Comment by mivbvim** [comment]
@kiryph 

I understand your point. (I also use the plugin vim-indent-object, kana's version which is also mapped on ii/ia. I don't know the one of Michael Smith. I agree on the fact it is very useful).

**Comment by lervag** [comment]
Thanks for the discussion, I agree that we should avoid clashing with the popular indent text object and instead use `im` and `am`.

I will create a minimal working version now, but it will still be work in progress to fix edge cases.

**Comment by lervag** [comment]
There, it's pushed now. Let me know how it works for you. It's still in alpha mode, but it's a start.

For further improvements, it would be very useful to get concrete examples that does not work right now in the following format (see below). This will make it easy for me to add the examples as tests, which is useful for keeping things robust.

```tex
% context (assume cursor is on first "\" below)
\begin{enumerate}
  \item first
  \item second
\end{enumerate}

% input: jjdam

% expected result
\begin{enumerate}
  \item first
\end{enumerate}
```

**Comment by mivbvim** [comment]
Hi,

thank you very much. It's nice ! 

I am detecting the following "bug" 

\begin{enumerate}
  \item ** \begin{enumerate}
              \item
              \item
            \end{enumerate}
    \item
  \end{enumerate}

When I am on ** and use vam (for example), it selects only the first line of the second enumerate.

**Comment by lervag** [comment]
Thanks! I was aware of this limitation and was just waiting for someone to comment on it... I'll find a way to support nested itemize like environments! I think the following heuristic should work: When we look for the end of the `\item`, we will ensure to loop through all environments. Thus, if there is a `\begin{xxx}`, then we'll search forward to the corresponding `\end{xxx}` before we look for an actual end (i.e. next `\item` or `\end{itemize|enumerate}`.

**Comment by lervag** [comment]
I've finally updated to support this now. Please test and report edge cases, as before :)

**Comment by mivbvim** [comment]
Hi,

thank you very much for your work ! The new update is nice and works for most of the cases !
I am still detecting a (small) bug :

\begin{itemize}
\item \begin{enumerate}
      \item (...)
      \end{enumerate}   <--- here
\end{itemize}

When the cursor is on "\end{enumerate", then "im" has no effect !

**Comment by lervag** [comment]
It would be nice to know what you expect to happen. I propose the following:

1. With

    ```tex
    \begin{itemize}
      \item (...)
    \end{itemize}
    ```

  `dim` from `\end{itemize}` deletes the inner last item.

2. With

    ```tex
    \begin{itemize}
      \item \begin{enumerate}
        \item (...)
      \end{enumerate}
    \end{itemize}
    ```

  `dim` from `\end{enumerate}` deletes the inner last item of `enumerate`.

3. With

    ```tex
    \begin{itemize}
      \item \begin{enumerate}
        \item (...)
      \end{enumerate}
    \end{itemize}
    ```

  `dim` from `\end{itemize}` deletes the inner last item of `itemize`.

How does this sound?

PS, and btw: In English (I think most languages), there should not be white space in front of punctuation characters such as "!" and ":".

**Comment by mivbvim** [comment]
In fact, I was not clear, sorry. 

I really like the current behavior that you proposed. I think it does what is expected. To summary:

\begin{itemize}
\item Text A
\item Text B
\item Text C
\end{itemize} 

When the cursor is on \begin{itemize} or \end{itemize}, im has no effect (because we don't are on an item block).
When the cursor is on "Text B", then dim deletes Text B, And dam deletes \item Text B.

This is what is happening in the current version, and this is perfect!

I come back to my previous message:

When the cursor is on \begin{enumerate}. We are on the first item on the itemize environment. 
* dim deletes 
\begin{enumerate}
\item (...)
\end{enumerate}.
* dam deletes 
\item \begin{enumerate}
         \item (...)
         \end{enumerate}.
Perfect!!

When the cursor is on \end{enumerate}, or after on the line, dim and dam have no effect. For me, since we are in the first item block of the itemize environment, it has to delete the corresponding item block, exactly like what's happen when we are on \begin{enumerate}. 

In fact, I detect at the moment the following

\begin{itemize}
\item \begin{enumerate}
         \item (...)
         \end{enumerate}
         foo
\item
\end{itemize}

When the cursor is on foo, dim or dam have also no effect. For me, since again, we are in the first item block of the itemize environment, it should delete it.

**Comment by lervag** [comment]
Ok, I think this should do. Let me know what you think!

I'll take the liberty of closing the issue now, since I think the feature has started to become robust and useful. Feel free to still post new edge cases either here or in new issues.
