### ISSUE TITLE
Active biblex completion with custom bibliography command

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#1653]
**Is your feature request related to a problem? Please describe it.**
For some reason, I have to redefine the bibliography command, see the example in the following MME.

However, it seems that this definition destroys the scheme for activating the  bibtex completion. The MWE for test:

```tex
\documentclass{amsart}
\newcommand{mybibliography}[1]{
  \phantomsection\addcontentsline{toc}{subsubsection}{Reference}
  \bibliography{#1}
}
\begin{document}
\cite{<C-X><C-O>
\mybibliography{ref}
\end{document}
```

This does not work for bibtex completion, but it works with the original command

```tex
\bibliography{ref}
```

The `ref.bib` looks like

```bib
@article{test,
    AUTHOR = {AUTHOR},
     TITLE = {TITLE},
   JOURNAL = {JOURNAL},
}
```

**Describe the solution you'd like**
I hope the bibtex completion work also for the custom defined command.

**Describe alternatives you've considered**
I try to include the `ref.bib` manually in TOC by

```
% vimtex-include: ref.bib
```

however, this seems not work also. Maybe this could become a solution, i.e., when we include bibtex data file manually, then active bibtex completion. Thanks for your time!

**Comment by lervag** [comment]
>  For some reason, I have to redefine the bibliography command, see the example in the following MME.

I understand that one will not always be in full control of ones manuscripts. In this case, I'm a little bit curious how little/much control one has. That is, I see a possibility in adding an option for specifying the regex for matching the bibfile lines. Currently, it is hard coded as follows:

```vim
      \ 'bibs' : '''\v%(%(\\@<!%(\\\\)*)@<=\%.*)@<!'
      \          . '\\(%(no)?bibliography|add(bibresource|globalbib|sectionbib))'
      \          . '\m\s*{\zs[^}]\+\ze}''',
```

There is already a mechanism for the options with `g:vimtex_complete_bib`.

**Comment by lervag** [comment]
@vanabel Are you interested in this? You never replied or followed up on the discussion...?

**Comment by vanabel** [comment]
Yeah, of course, I am interested in this. As you had said, I'd like to have an option for specifying the regex for matching the bible lines. Thanks!

**Comment by lervag** [comment]
Ok, I'll look into it.

By the way, quite recently I've updated the mechanism for finding `.bib` files so that it first relies on parsing the `.blg` file (or similar for biblatex). Thus, completion should work in the original case in this issue as long as the document is compiled. Can you confirm that?

**Comment by lervag** [comment]
I think this should work now. See `:help vimtex_complete_bib` for info on how to configure, let me know if you find any further related issues.

**Comment by vanabel** [comment]
> Ok, I'll look into it.
> 
> By the way, quite recently I've updated the mechanism for finding `.bib` files so that it first relies on parsing the `.blg` file (or similar for biblatex). Thus, completion should work in the original case in this issue as long as the document is compiled. Can you confirm that?

I can confirm that the auto-completion works via the new scheme that depend on `.blg`, thanks.

**Comment by lervag** [comment]
Happy to hear it. And you should now also be able to configure the regexes as raised/suggested in this issue.
