### ISSUE TITLE
Question regarding default mappings

### ISSUE THREAD

**Issue by JohnMalliotakis** [lervag/vimtex#1654]
Sorry if this sounds like a dumb question, but on the vimtex-default-mappings manual, which vim modes do x and o refer to? I have had no problem with the normal and insert mode mappings, but I have been struggling with the `a` (`ac` etc) and `i` (`ic` etc) mappings.

Thanks

EDIT: Sorry for the bug label

**Comment by lervag** [comment]
> Sorry if this sounds like a dumb question, but on the vimtex-default-mappings manual, which vim modes do x and o refer to? I have had no problem with the normal and insert mode mappings, but I have been struggling with the `a` (`ac` etc) and `i` (`ic` etc) mappings.

The modes referred to are the "prefixes" of the `map` command. This should explain it:

- `n` is normal mode (the "default" mode)
- `x` is visual mode
- `o` is operator-pending mode

You can read about these modes in the docs. See e.g. `:help :map-modes`. You might expect `v` to denote visual mode, but `vmap` is used to map both visual and select mode, which are different modes. `xmap` is used to map only visual mode.

Mappings like `ac` and `ic` are text objects, which mean they are the targets of operators. See `:help text-objects`. This is one of the very useful features of Vim, so I strongly recommend you learn about them!

I'll also update the docs, as I understand these things are not clear to newbies.

> EDIT: Sorry for the bug label

Nothing to be sorry about, that's my fault for specifying it as a defualt label. :)

**Comment by JohnMalliotakis** [comment]
Ok thanks, I will read more on the modes.
