### ISSUE TITLE
VimtexInfo closes after vim movement command + trouble with minimal vimrc

### ISSUE THREAD

**Issue by horror-vacui** [lervag/vimtex#1657]
**Issue**
`\li` or `\lI`, i.e. `:VimtexInfo` command switches to something which looks like a system information log file. Though it does not create a vim buffer. This means that `:ls` command will return only the already opened files, and it has no entry for `:VimtexInfo`.
The issue is that this information "screen" closes, and reverts back to the previously open file after any movement command, that I would use to see the end of `:VimtexInfo`.

I've got trouble using the minimal `.vimrc` file. It looks like that vimtex is not loaded, though vimtex is listed in `:scriptnames`'s output, and `set runtimepath?` and `:h local-additions` also list the vimtex directory. Starting with `vim --servername VIM -u minimal.vim minimal.tex` did not make the the `\li` command work, and I've got E492 errors for vimtex commands.

All other plugins (e.g. ariline, vimwiki, commentary) are working with the minimal vimrc. It indicates some issue specific to vimtex.

I've cloned vimtex via git.
```
zoltan@aprosag ~/.vim/pack/plugins/start/vimtex $ git status
HEAD detached from c146852a
nothing to commit, working tree clean
```

**Expected Behaviour**
The information of vimtex-info opens in a new buffer.

**Output from VimtexInfo**

`E492: Not an editor command: VimtexInfo` 
`E492: Not an editor command: VimtexCompile`

**Vim version**
```
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 26 2018 23:54:33)
Included patches: 1-328
Compiled by zoltan@aprosag
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl               +extra_search      +mouse_netterm     +tag_old_static
+arabic            +farsi             +mouse_sgr         -tag_any_white
+autocmd           +file_in_path      -mouse_sysmouse    -tcl
+autochdir         +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
+balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
+browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          +toolbar
+cindent           +insert_expand     +path_extra        +user_commands
+clientserver      +job               -perl              +vartabs
+clipboard         +jumplist          +persistent_undo   +vertsplit
+cmdline_compl     +keymap            +postscript        +virtualedit
+cmdline_hist      +lambda            +printer           +visual
+cmdline_info      +langmap           +profile           +visualextra
+comments          +libcall           -python            +viminfo
+conceal           +linebreak         +python3           +vreplace
+cryptv            +lispindent        +quickfix          +wildignore
+cscope            +listcmds          +reltime           +wildmenu
+cursorbind        +localmap          +rightleft         +windows
+cursorshape       +lua               +ruby              +writebackup
+dialog_con_gui    +menu              +scrollbind        +X11
+diff              +mksession         +signs             -xfontset
+digraphs          +modify_fname      +smartindent       +xim
+dnd               +mouse             +startuptime       +xpm
-ebcdic            +mouseshape        +statusline        +xsmp_interact
+emacs_tags        +mouse_dec         -sun_workshop      +xterm_clipboard
+eval              -mouse_gpm         +syntax            -xterm_save
+ex_extra          -mouse_jsbterm     +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16   -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector -rdynamic -Wl,-export-dynamic  -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -ldl  -L/usr/lib -llua5.1   -L/usr/lib/python3.6/config-3.6m-x86_64-linux-gnu -lpython3.6m -lpthread -ldl -lutil -lm  -lruby-2.5 -lpthread -lgmp -ldl -lcrypt -lm 
```

**Comment by lervag** [comment]
> `\li` or `\lI`, i.e. `:VimtexInfo` command switches to something which looks like a system information log file. Though it does not create a vim buffer. This means that `:ls` command will return only the already opened files, and it has no entry for `:VimtexInfo`.
> The issue is that this information "screen" closes, and reverts back to the previously open file after any movement command, that I would use to see the end of `:VimtexInfo`.

`:VimtexInfo` opens a scratch buffer. The buffer is not displayed in `:ls` because it is a scratch buffer. It should not close on any movement command. However, I've mapped the following keys to close the buffer: `q`, `<c-e>`, `<c-6>`, `<c-^>`, and `<esc>`. If other keys closes the window, then that should be due to something on your side, I think.

> I've got trouble using the minimal `.vimrc` file. It looks like that vimtex is not loaded, though vimtex is listed in `:scriptnames`'s output, and `set runtimepath?` and `:h local-additions` also list the vimtex directory. Starting with `vim --servername VIM -u minimal.vim minimal.tex` did not make the the `\li` command work, and I've got E492 errors for vimtex commands.

You need to use the correct paths to vimtex. Note, if you are using Vim's package feature, then you should first disable it/ensure that no plugins are loaded from the package paths. I don't use this feature and don't know exactly how, except you could of course just move all of the plugin folders manually.

So, the runtimepaths need to be set correctly, and they should **not** be paths under Vim's package structure.
