### ISSUE TITLE
\cite completion and .bib file globbing

### ISSUE THREAD

**Issue by gipert** [lervag/vimtex#1658]
**Is your feature request related to a problem? Please describe it.**

The `\cite` completion list is empty for me with the following MWE:
```tex
\documentclass{article}
\usepackage{biblatex}
\addbibresource{*.bib}
\begin{document}
Test
\end{document}
```
`ref.bib`
```bibtex
@article{Agostini2019b,
    author        = "Agostini, M. and others",
    archivePrefix = "arXiv",
    collaboration = "Gerda",
    doi           = "10.1007/JHEP03(2020)139",
    eprint        = "1909.02522",
    journal       = "JHEP",
    pages         = "139",
    primaryClass  = "nucl-ex",
    title         = "{Modeling of GERDA Phase II data}",
    volume        = "03",
    year          = "2020"
}
```
And it works as expected if I `\addbibresource{ref.bib}`. Can you reproduce?

**Describe the solution you'd like**

Would it be possible to add support for wildcards in the `\addbibresource` command? Or is there already some trick I can use to make this work?

**Comment by lervag** [comment]
Hi. I was not aware that one could use wildcards in the `\addbibresource` command. Should work now, I think. Let me know if you find edge cases that do not work as expected.

**Comment by kiryph** [comment]
For the record this requires `biber` and seems to behave slightly differently on Windows:

Excerpt form the manual of biblatex v3.14 Dec 2019

> ## 3.7 Bibliography Commands
> ### 3.7.1 Resources
> `\addbibresource[<options>]{<resource>}`
> Adds a `<resource>`, such as a .bib file, to the default resource list. This command is
> only available in the preamble. It replaces the `\bibliography` legacy command.
> Note that files must be specified with their full name, including the extension. **With
> biber, the resource name can be a BSD-style glob pattern.** This only makes sense
> when resources refer to files with an absolute or relative path and does not work when
> looking for data resources in biber s input/output directories or with resources
> located by `<kpsewhich>` etc. When running **on Windows**, biber will switch to a
> **Windows compatible globbing mode where backslashes are also useable as path
> separators and case does not matter**.

**Comment by lervag** [comment]
> For the record this requires biber and seems to behave slightly differently on Windows:

Bah, why is everything so complicated. Perhaps a better solution is to _not_ allow globbing, and instead add a different mechanism for this? Also related to #1653, I guess?

**Comment by kiryph** [comment]
IMHO if people collaborate on the same tex document, they should only use a simple glob pattern, nothing platform dependent.

However, if you work on your on document on Windows, you might expect that you can use backslashes as path separator. This is something I suspect someone will eventually raise an issue. You could fix it then.

**Comment by lervag** [comment]
Ok, so leave things as they are now and address future issues if they arise. Seems OK to me.

**Comment by gipert** [comment]
Works perfectly, as always! Thank you.

**Comment by lervag** [comment]
Great, happy to hear it! )
