### ISSUE TITLE
How to set option `--shell-escape` for xelatex?

### ISSUE THREAD

**Issue by ZhiyuanLck** [lervag/vimtex#1662]
I want add `--shell-escape` option in `.vimrc`, and I have tried two ways neither of which worked (by keymap `\li` and `\lo` to check the compile information):
this way
```vim
    let g:vimtex_compiler_latexmk = {
        \ 'backend' : 'jobs',
        \ 'background' : 1,
        \ 'build_dir' : '../output',
        \ 'callback' : 1,
        \ 'continuous' : 1,
        \ 'executable' : 'latexmk',
        \ 'optons': [
        \   '-pdfxe',
        \   "-xelatex=\"xelatex --shell-escape %O %S\"",
        \   '-verbose',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \   '-cd', ],
        \}
```
and this way
```vim
    let g:vimtex_compiler_latexmk = {
        \ 'backend' : 'jobs',
        \ 'background' : 1,
        \ 'build_dir' : '../output',
        \ 'callback' : 1,
        \ 'continuous' : 1,
        \ 'executable' : 'latexmk',
        \ 'optons': [
        \   '-pdfxe',
        \   "-xelatex",
        \   "-e '$xelatex=\"xelatex --shell-escape %O %S\"'",
        \   '-verbose',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \   '-cd', ],
        \}
```
So I have to set this option in `.latexmkrc`which just works fine
```perl
$xelate="xelatex --shell-escape %O %S"
```
Is this a **bug** or I don't get the correct way?

**Comment by lervag** [comment]
You should not put the engine option in this list. That is, don't use `-pdfxe` and `-xelatex` here. They won't be recognized. Instead, you should specify it with a directive (see `:help vimtex-tex-program`) or by changing the default engine with `:help g:vimtex_compiler_latexmk_engines`.

That should be the reason things don't work. Let me know if it fixes your problem.

Note, though: I actually think this kind of configuration (i.e. the `$xelatex=...shellescape`) is better to put in your `.latexmkrc` file, because sometimes you might want to run `latexmk` in your terminal. By putting the configuration in `.latexmkrc`, you will get the same behaviour in vimtex as in the terminal.

**Comment by ZhiyuanLck** [comment]
Yeah, it works. Thanks for help!

Another question, I find additional sytax files in `/autoload/vimtex/syntax/p`, how can I enable them? I have checked that `g:vimtex_syntax_enabled=1`,  but when I check the highlight group of `minted` environment, I get `texBeginEndName` rather than `texZoneMinted`.

And there is an inconvenience I have met:
texMathZone settings for `amsmath` are not written in help document, when I set them I have to check `/autoload/vimtex/syntax/p/amsmath.vim` although it need setted only once.

**Comment by lervag** [comment]
> Yeah, it works. Thanks for help!

Great, happy to hear it!

> Another question, I find additional sytax files in `/autoload/vimtex/syntax/p`, how can I enable them? I have checked that `g:vimtex_syntax_enabled=1`, but when I check the highlight group of `minted` environment, I get `texBeginEndName` rather than `texZoneMinted`.

The syntax files are loaded automatically as long as the `minted` package is recognized. You can check with `:VimtexInfo` that it is listed, or with `:echo b:vimtex_syntax` to see which syntax packages are loaded. Note, this is initialized when you open your document. In some cases, the package list is not complete until after you compile the document. You can try to reopen the file or do `:edit!` (save first) to reload everything.

> And there is an inconvenience I have met:
> texMathZone settings for `amsmath` are not written in help document, when I set them I have to check `/autoload/vimtex/syntax/p/amsmath.vim` although it need setted only once.

I don't understand what you mean?
