### ISSUE TITLE
Add vim-surround mappings in documentation

### ISSUE THREAD

**Issue by urbainvaes** [lervag/vimtex#1665]
Tim Pope's vim-surround defines mapping `ys{motion}l` in normal mode and `Sl` in visual mode to surround a motion with an LaTeX environment. It might be nice to mention this somewhere in the documentation?

Thanks for this great plugin! :)

**Comment by lervag** [comment]
vim-surround is mentioned, although the mappings are not explained. See `:help vimtex-nf-surround`. Do you still think we should add to the docs? If so, please suggest a first version :)

> Thanks for this great plugin! :)

You're welcome; I'm happy you like it!

**Comment by lervag** [comment]
Closed due to inactivity.

**Comment by urbainvaes** [comment]
When reading the documentation today, I found out you could do `cs$` and `cse\[` to go from
```
\[
...
\]
```
to
```
\begin{align}
...
\end{align}
```
and back. This is super convenient, thank you again for this great plugin!

**Comment by lervag** [comment]
Thanks, and thanks for the PR!
