### ISSUE TITLE
A bug about `tsf`

### ISSUE THREAD

**Issue by zhuosongz** [lervag/vimtex#1668]
Hello, 

`tsf` is amazing to deal with `a/b` and `\frac{a}{b}`. However, on my MacOS system, an unexpected bug happens: 

With `tsf`, `e^{a/b}` is expected to become `e^{\frac{a}{b}}`, but it gives me `\frac{e^{a}{b}}`. Also, `n^{1/2}` turns out to become `\frac{n^{1}{2}}`, which is expected to be `n^{\frac{1}{2}}`.

I also tried with `e^{ a/b }`, and it gives me `e^{ \frac{a}{b} }`, as expected. 

Thank you for your attention!

**Comment by lervag** [comment]
Thanks! I'm quite sure it is not related to your OS, instead, it is a shortcoming with the current implementation. I'll look into it.

Note, in the meantime, from inline fracs like `e^{a/b}` you can use the visual mode version. Select `a/b` and do `tsf`, and it should work as expected.

**Comment by zhuosongz** [comment]
Thank you a lot for your reply. 

I would like to report some more unexpected behaviors: 

```
n^{-1/2}  --tsf--> \frac{n^{-1}{2}}, 
```
which is expected to be `n^{-\frac{1}{2}}`.

Using visual mode version, I selected `1/2` and it gave me `n^{-\frac{1}{2}}`, as expected. However, when I did `tsf` to `n^{-\frac{1}{2}}`, some error appeared: 
```
Error detected while processing function <SNR>85_operator_function[3]..vimtex#cmd#toggle_frac:
line    8:
E716: Key not present in Dictionary: col_start) . l:frac.text_toggled . strpart(l:line, l:frac.col_end+1))
E116: Invalid arguments for function strpart(l:line, 0, l:frac.col_start) . l:frac.text_toggled . strpart(l:li
ne, l:frac.col_end+1))
E116: Invalid arguments for function setline
```

**Comment by lervag** [comment]
Thanks, I think I've fixed all of these now. Please let me know if it works as expected for you!
