### ISSUE TITLE
TextObj Compatible Issue with Surrounding and Multi Cursor

### ISSUE THREAD

**Issue by y1rah** [lervag/vimtex#1669]
I've covered the config with (found in doc):

```viml
  let b:surround_{char2nr('e')}
      \ = "\\begin{\1environment: \1}\n\t\r\n\\end{\1\1}"
  let b:surround_{char2nr('c')} = "\\\1command: \1{\r}"
```

to reach support resembling:

```viml
" Configured at ~/.vim/after/ftplugin/tex.vim:
"
" ys{text-obj}e: yield surrounding environment
" ys{text-obj}c: yield surrounding command
```

Here is a problem, when I try `ys{text-obj}c` with multi cursor, I have to repeat the command value as many times as the cursors exist.

The gif below illustrates some of above:

![演示动图](https://user-images.githubusercontent.com/30183249/79633458-4ae8bc00-8198-11ea-888b-b55042270b4e.gif)

Is there any solution towards this?

Thanks a lot. ^_^

**Comment by lervag** [comment]
I really don't know. This is not part of vimtex, it is a feature from [surround.vim](http://grammatikk.com/). Please open the issue there instead.
