### ISSUE TITLE
Nested syntax highlighting for minted

### ISSUE THREAD

**Issue by lahwaacz** [lervag/vimtex#167]
Would it be possible to implement nested syntax highlighting for the [minted](https://github.com/gpoore/minted) package? It allows to define custom environments for different languages with different options (see the "Defining shortucts" chapter in the [documentation](https://github.com/gpoore/minted/blob/master/source/minted.pdf)), but the default name of the environment is `<lang>code` (e.g. `cppcode` or `pythoncode`). This could be used to automatically detect the language, or alternatively a mapping/dictionary could be exposed for configuration.

I see there is already some support for the [listings](https://github.com/lervag/vimtex/blob/master/after/syntax/tex.vim#L41) package, though I did not try it and have no idea how the language detection works.

**Comment by lervag** [comment]
This seems like a nice challenge and a useful feature. I will not promise to do it at once, though, as I have a lot of stuff going on at the moment. So feel free to post a pull request if you manage to find a nice solution.

Note that I've previously added nested syntax highlighting for dot, as you can see in `after/syntax/tex.vim`.

**Comment by lahwaacz** [comment]
OK, there seems to be an issue. If I highlight the C++ code in the `cppcode` environment with
``` viml
unlet b:current_syntax
syntax include @CPP syntax/cpp.vim
syntax region texZone
      \ matchgroup=texRefZone
      \ start="\\begin{cppcode\*\=}"
      \ matchgroup=texRefZone
      \ end="\\end{cppcode\*\=}"
      \ keepend
      \ transparent
      \ contains=@CPP
let b:current_syntax = 'tex'
```
which is a naive adjustment of the nested dot highlighting, everything works as expected, except that when a keyword is part of different symbol (e.g. variable name) delimited by underscore, they are highlighted as keywords. For example, if there is a variable named `foo_for_bar`, `foo_if_bar` etc., then `for` and `if` are highlighted. Is it possible that TeX lexing rules are still applied in the region?

**Comment by lervag** [comment]
I'm guessing that this might be due to the `iskeyword` setting. The internal syntax plugin for tex that ships with vim sets `iskeyword` and the `_` character is not included. You could try to set it yourself with something like:
```vimL
let g:tex_isk='48-57,a-z,A-Z,192-255,:,_'
```

**Comment by lahwaacz** [comment]
Thanks, I think this setting works quite well. Now only to recognize `<lang>code` environments generally...

**Comment by lervag** [comment]
I don't think there is a general or dynamic way of recognizing `<lang>code` environments. However, one could make a list of supported languages and load the syntax rules for each language. Something like this:
```vimL
let g:vimtex_minted_languages = [
  \ 'cpp',
  \ 'python',
  \ ]
for lang in g:vimtex_minted_languages
  unlet b:current_syntax
  execute 'syntax include @' . toupper(lang) 'syntax/' . lang . '.vim'
  execute 'syntax region texZone'
        \ 'matchgroup=texRefZone'
        \ 'start="\\begin{' . lang . 'code\*\=}"'
        \ 'matchgroup=texRefZone'
        \ 'end="\\end{' . lang . 'code\*\=}"'
        \ 'keepend'
        \ 'transparent'
        \ 'contains=@' . toupper(lang)
endfor
let b:current_syntax = 'tex'
```

If you want, I could try to implement this. However, then it would be very helpful with a small example LaTeX document for testing.

**Comment by lervag** [comment]
I've pushed an update that adds support for minted. The initial code supports `c`, `csharp` and `python`, but it is easy to add more languages. See `:h g:vimtex_syntax_minted`.

**Comment by lahwaacz** [comment]
Hi, thank you very much for implementing this feature, and sorry for the late reply -- the deadline for my project was coming closer and closer, so I needed to freeze my working environment and concentrate on the work.

It works quite nicely, but only for the basic `minted` environment (e.g. section 4.2 in [the docs](http://mirrors.nic.cz/tex-archive/macros/latex/contrib/minted/minted.pdf)). In chapter 7 they show how to define "shortcuts" environments for easier specification of options, as has been discussed in this issue above. Would it be possible to support the default style of naming the environments, e.g. `cppcode` and `cppcode*`? To grant even more flexibility, the `g:vimtex_syntax_minted` option could recognize another field in the dictionaries, e.g.
``` viml
let g:vimtex_syntax_minted = [
    \ {
    \   'lang' : 'cpp',
    \   'environments' : ['cppcode', 'cppcode*', 'cppcode_something'],
    \ }
    \ ]
```

**Comment by lervag** [comment]
Yes, this should be relatively easy. The only problem is to decide the correct approach. That is, is there a general regexp that would match all such environment namings? At first sight, it seems `lang . 'code\*\?'` should do it. I've pushed an update that does this.

But perhaps the environemnt names should be more flexible? In that case, your suggestion might be better.

**Comment by lahwaacz** [comment]
It is possible to configure completely custom environment names via the optional parameter of `\newminted`, i.e. `\newminted[environment_name]{lang}{options}`, so these would have to be configured manually for vimtex to recognize them.

Also, there is a problem that the starred versions of every such environment accepts parameters in another pair of braces, e.g. `\begin{cppcode*}{gobble=4}`. With the current approach (`cppcode*` is treated the same way as `cppcode`), the highlighting works fine, but the `{gobble=4}` part is parsed as C++ code, not tex.

**Comment by lervag** [comment]
Ah, I didn't notice that (custom environment names). I also mistakenly assumed the starred versions accepted parameters inside square braces, not curly braces. I'll fix it and push an update soon.
