### ISSUE TITLE
Folds jump open and closed in rnoweb files

### ISSUE THREAD

**Issue by mattjbourque** [lervag/vimtex#1670]
I'm really enjoying the vimtex plugin, thanks so much for your great work. I'm having an issue with folding rnoweb files, and and am not sure whether the fix should come from vimtex or from the maintainers of rnoweb.vim. Here is my description:

**Issue**
When using folding with manual folding enabled, folds in rnoweb files jump open as soon as the cursor enters the folded line, and then jump closed again when the cursor leaves. The effect is disorienting.

**minimal.vim**

  ```vim
  set nocompatible
  let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
  let &rtp .= '~/,.vim/bundle/vimtex/after'
  filetype plugin indent on
  syntax enable

  let g:vimtex_fold_enabled=1
  let g:vimtex_fold_manual=1
  ```

**minimal.Rnw**

  ```tex
  \documentclass{minimal}

  % This is a preamble comment
  % to get a few lines to fold

  \begin{document}

  \section{The first section}

  It has a couple of lines.
  It has a couple of lines.


  \section{The second section}

  This one does, too.
  This one does, too.

  \end{document}
  ```

**Commands/Input**
`vim -u minimal.vim minimal.Rnw`
Open the file and move vertically through it.

**Observed Behaviour**
The preamble and section folds jump open and closed.

**Expected Behaviour**
The folds stay closed until user presses `zo` or something else to open the fold.

**A temporary fix**
It appears that `vimtex#fold#init#buffer` in `autoload/vimtex/fold.vim` gets called twice when opening a rnoweb file, and the autocommand which calls the `fold_manual_refresh` function gets created twice but only deleted once. To be honest, my vimscript powers are not up to figuring out exactly what's going on in this function, but I did find that a check to only call `vimtex#fold#init#buffer` once seems to fix the problem for me:

```patch
diff --git a/autoload/vimtex/fold.vim b/autoload/vimtex/fold.vim
index 09e5290a..1903b15f 100644
--- a/autoload/vimtex/fold.vim
+++ b/autoload/vimtex/fold.vim
@@ -6,7 +6,9 @@
 
 function! vimtex#fold#init_buffer() abort " {{{1
   if !g:vimtex_fold_enabled
-        \ || s:foldmethod_in_modeline() | return | endif
+        \ || s:foldmethod_in_modeline() 
+        \ || exists('b:did_fold_init_buffer') | return | endif
+  let b:did_fold_init_buffer=1
 
   " Set fold options
   setlocal foldmethod=expr
 
```

Please let me know if this is an issue that should be taken up with the maintainers of rnoweb.vim, or if there's something else I can help to do to resolve it here.

**Output from VimtexInfo**
```
System info
  OS: Debian GNU/Linux 9.11 (stretch)
  Vim version: VIM 8.2 (1-96)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

vimtex project: file
  base: file.Rnw
  root: /home/matt/vimtest
  tex: /home/matt/vimtest/file.Rnw
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    backend: jobs
    output: /tmp/vzeLv4g/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: minimal
  packages:
    amsmath
    fullpage
```

**Comment by lervag** [comment]
> I'm really enjoying the vimtex plugin, thanks so much for your great work.

Thanks for the kind words!

> I'm having an issue with folding rnoweb files, and and am not sure whether the fix should come from vimtex or from the maintainers of rnoweb.vim. Here is my description:

I've tested your minimal example, and I can't reproduce it. Things work as expected on my end. I've tested with both Vim (v8.2.510) and neovim (v0.5.0).

However, the issue seems related to the `:help 'foldopen'` and `:help 'foldclose'` options. Could you check that these are at their default values?

----

Your patch really should not be necessary, because `vimtex#fold#init_buffer` is called by `s:init_buffer` in `autoload/vimtex.vim`, which is called by `vimtex#init`, which is called by `ftplugin/tex.vim` from vimtex. The latter has a guard already that should prevent `vimtex#init` from being called twice in the same buffer.

Are you sure that the `fold#init_buffer` is called twice when you start with the minimal Vim file? You could test with something like this:

```diff
diff --git a/autoload/vimtex/fold.vim b/autoload/vimtex/fold.vim
index 097313cc..15fecb58 100644
--- a/autoload/vimtex/fold.vim
+++ b/autoload/vimtex/fold.vim
@@ -4,9 +4,12 @@
 " Email:      karl.yngve@gmail.com
 "
 
+let s:count = 0
 function! vimtex#fold#init_buffer() abort " {{{1
   if !g:vimtex_fold_enabled
         \ || s:foldmethod_in_modeline() | return | endif
+  let s:count += 1
+  unsilent echom 'init_buffer call #' . s:count
 
   " Set fold options
   setlocal foldmethod=expr
```

Note: I've made some minor simplifications of the code, but I don't think it should matter to your issue.

**Comment by mattjbourque** [comment]
Thanks for your speedy reply.

> However, the issue seems related to the `:help 'foldopen'` and `:help 'foldclose'` options. Could you check that these are at their default values?

`:set foldopen` returns `foldopen=block,hor,mark,percent,quickfix,search,tag,undo` and `:set foldclose` gives `  foldclose=`. I think these are the defaults; neither option is listed with a plain `:set`.

> Are you sure that the `fold#init_buffer` is called twice when you start with the minimal Vim file? You could test with something like this ...
>

With your patch `vim -u minimal.vim minimal.Rnw` gives the following `:messages`
```
"file.Rnw" 19L, 271C
init_buffer call #1
init_buffer call #2
```

> Note: I've made some minor simplifications of the code, but I don't think it should matter to your issue.

I think I see these on Github, but I have not updated my plugin code to get them. I can do that if you like.

**Comment by lervag** [comment]
Ok; this is strange. Can you move the test code into the `ftplugin/tex.vim` file and check if my suspicion is correct that the issue is related to the loading of the filetype plugin? Let me know if you need help with it.

Reg. recent updates: they should not solve the issue, but I suggest that you generally try to keep up with updates as I continuosly maintain, update, and improve vimtex.

**Comment by mattjbourque** [comment]
When I delete the contents of `autoload/vimtex/fold.vim` and append them to `ftplugin/tex.vim` and then run `vim -u minimal.vim minimal.Rnw` I get the same messages.

**Comment by mattjbourque** [comment]
Wait, no! Sorry, I do **not** get the same messages, I get
```
"file.Rnw" 19L, 271C
init_buffer call #1
init_buffer call #1
```

**Comment by lervag** [comment]
So, this means that for you, with `.Rnw` files, vimtex is loaded twice. If you look at the code in `ftplugin/tex.vim`, it should be quite simple. In particular, there's a guard:

```vim
if exists('b:did_ftplugin')
  finish
endif
let b:did_ftplugin = 1
```

This _should_ prevent vimtex from being loaded twice. My next debug step would be to check the value of `b:did_ftplugin`. Something like this:

```vim
unsilent echo 'test' &filetype
unsilent echo 'test' exists('b:did_ftplugin')
if exists('b:did_ftplugin')
  finish
endif
let b:did_ftplugin = 1
```

**Comment by lervag** [comment]
> Wait, no! Sorry, I do not get the same messages, I get

It still seems to give two messages, though? The counter code may be wrong here? (I.e. if you reset the counter when the file is sourced the second time, then the counter should be the same both times.)

**Comment by mattjbourque** [comment]
Yes, still two messages, so it does look like the code is getting called twice. Here are the messages when opening the file with the `b:did_ftplugin` test code you give:
```
"file.Rnw" 19L, 271C
test rnoweb
test 0
init_buffer call #1
test rnoweb
test 0
init_buffer call #1
```

**Comment by lervag** [comment]
And this happens when you use the minimal vimrc file, i.e. `vim -u minimal.vim minimal.Rnw`?

What's the output of `:scriptnames` after you open with the minimal.vim file?

**Comment by mattjbourque** [comment]
Yes, all of this is with `vim -u minimal.vim minimal.Rnw`. Here's the output of `:scriptnames` after that invocation of vim:
```
  1: ~/vimtest/minimal.vim
  2: /usr/local/share/vim/vim82/filetype.vim
  3: ~/.vim/ftdetect/nope_Rnw.vim
  4: /usr/local/share/vim/vim82/ftplugin.vim
  5: /usr/local/share/vim/vim82/indent.vim
  6: /usr/local/share/vim/vim82/syntax/syntax.vim
  7: /usr/local/share/vim/vim82/syntax/synload.vim
  8: /usr/local/share/vim/vim82/syntax/syncolor.vim
  9: /usr/local/share/vim/vim82/plugin/getscriptPlugin.vim
 10: /usr/local/share/vim/vim82/plugin/gzip.vim
 11: /usr/local/share/vim/vim82/plugin/logiPat.vim
 12: /usr/local/share/vim/vim82/plugin/manpager.vim
 13: /usr/local/share/vim/vim82/plugin/matchparen.vim
 14: /usr/local/share/vim/vim82/plugin/netrwPlugin.vim
 15: /usr/local/share/vim/vim82/plugin/rrhelper.vim
 16: /usr/local/share/vim/vim82/plugin/spellfile.vim
 17: /usr/local/share/vim/vim82/plugin/tarPlugin.vim
 18: /usr/local/share/vim/vim82/plugin/tohtml.vim
 19: /usr/local/share/vim/vim82/plugin/vimballPlugin.vim
 20: /usr/local/share/vim/vim82/plugin/zipPlugin.vim
 21: /usr/local/share/vim/vim82/ftplugin/rnoweb.vim
 22: ~/.vim/bundle/vimtex/ftplugin/tex.vim
 23: ~/.vim/bundle/vimtex/autoload/vimtex.vim
 24: ~/.vim/bundle/vimtex/autoload/vimtex/util.vim
 25: ~/.vim/bundle/vimtex/autoload/vimtex/state.vim
 26: ~/.vim/bundle/vimtex/autoload/vimtex/re.vim
 27: ~/.vim/bundle/vimtex/autoload/vimtex/parser.vim
 28: ~/.vim/bundle/vimtex/autoload/vimtex/parser/tex.vim
 29: ~/.vim/bundle/vimtex/autoload/vimtex/cache.vim
 30: ~/.vim/bundle/vimtex/autoload/vimtex/paths.vim
 31: ~/.vim/bundle/vimtex/autoload/vimtex/view.vim
 32: ~/.vim/bundle/vimtex/autoload/vimtex/view/general.vim
 33: ~/.vim/bundle/vimtex/autoload/vimtex/view/common.vim
 34: ~/.vim/bundle/vimtex/autoload/vimtex/compiler.vim
 35: ~/.vim/bundle/vimtex/autoload/vimtex/compiler/latexmk.vim
 36: ~/.vim/bundle/vimtex/autoload/vimtex/qf.vim
 37: ~/.vim/bundle/vimtex/autoload/vimtex/qf/latexlog.vim
 38: ~/.vim/bundle/vimtex/autoload/vimtex/toc.vim
 39: ~/.vim/bundle/vimtex/autoload/vimtex/fold.vim
 40: ~/.vim/bundle/vimtex/autoload/vimtex/fold/envs.vim
 41: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_single_opt.vim
 42: ~/.vim/bundle/vimtex/autoload/vimtex/fold/markers.vim
 43: ~/.vim/bundle/vimtex/autoload/vimtex/fold/preamble.vim
 44: ~/.vim/bundle/vimtex/autoload/vimtex/fold/sections.vim
 45: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_addplot.vim
 46: ~/.vim/bundle/vimtex/autoload/vimtex/fold/env_options.vim
 47: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_multi.vim
 48: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_single.vim
 49: ~/.vim/bundle/vimtex/autoload/vimtex/parser/fls.vim
 50: ~/.vim/bundle/vimtex/autoload/vimtex/cmd.vim
 51: ~/.vim/bundle/vimtex/autoload/vimtex/complete.vim
 52: ~/.vim/bundle/vimtex/autoload/vimtex/debug.vim
 53: ~/.vim/bundle/vimtex/autoload/vimtex/delim.vim
 54: ~/.vim/bundle/vimtex/autoload/vimtex/doc.vim
 55: ~/.vim/bundle/vimtex/autoload/vimtex/echo.vim
 56: ~/.vim/bundle/vimtex/autoload/vimtex/env.vim
 57: ~/.vim/bundle/vimtex/autoload/vimtex/pos.vim
 58: ~/.vim/bundle/vimtex/autoload/vimtex/format.vim
 59: ~/.vim/bundle/vimtex/autoload/vimtex/fzf.vim
 60: ~/.vim/bundle/vimtex/autoload/vimtex/imaps.vim
 61: ~/.vim/bundle/vimtex/autoload/vimtex/include.vim
 62: ~/.vim/bundle/vimtex/autoload/vimtex/info.vim
 63: ~/.vim/bundle/vimtex/autoload/vimtex/kpsewhich.vim
 64: ~/.vim/bundle/vimtex/autoload/vimtex/log.vim
 65: ~/.vim/bundle/vimtex/autoload/vimtex/matchparen.vim
 66: ~/.vim/bundle/vimtex/autoload/vimtex/misc.vim
 67: ~/.vim/bundle/vimtex/autoload/vimtex/motion.vim
 68: ~/.vim/bundle/vimtex/autoload/vimtex/process.vim
 69: ~/.vim/bundle/vimtex/autoload/vimtex/profile.vim
 70: ~/.vim/bundle/vimtex/autoload/vimtex/scratch.vim
 71: ~/.vim/bundle/vimtex/autoload/vimtex/syntax.vim
 72: ~/.vim/bundle/vimtex/autoload/vimtex/test.vim
 73: ~/.vim/bundle/vimtex/autoload/vimtex/text_obj.vim
 74: ~/.vim/bundle/vimtex/autoload/vimtex/text_obj/targets.vim
 75: ~/.vim/ftplugin/tex.vim
 76: /usr/local/share/vim/vim82/ftplugin/tex.vim
 77: /usr/local/share/vim/vim82/indent/rnoweb.vim
 78: ~/.vim/bundle/vimtex/indent/tex.vim
 79: /usr/local/share/vim/vim82/indent/r.vim
 80: /usr/local/share/vim/vim82/syntax/rnoweb.vim
 81: /usr/local/share/vim/vim82/syntax/tex.vim
 82: /usr/local/share/vim/vim82/syntax/r.vim
```

**Comment by lervag** [comment]
Two scripts stand out:

```
  3: ~/.vim/ftdetect/nope_Rnw.vim
 75: ~/.vim/ftplugin/tex.vim
```

What are these?

**Comment by mattjbourque** [comment]
I was just noticing `nope_Rnw.vim` myself after i posted that. The `nope_` was meant to disable it but as I now realize, that doesn't work. The file contains:

```vim
" Vim filetype detection plugin
" " Language:    rnoweb
"
autocmd BufRead,BufNewFile *.Rnw set filetype=rnoweb
```

I must have put that there ages ago, I don't remember why. If I remove it, it looks like vimtex is only loaded once when started with `minimal.vim`, and folding on the test file works as expected.

I am sorry for dragging you into what turns out to be a lousy configuration of my own!

**Comment by lervag** [comment]
> I am sorry for dragging you into what turns out to be a lousy configuration of my own!

No problem! I like debugging in general (it's just like solving a mystery), and I'm happy that I could be of help :)
