### ISSUE TITLE
Incorrect highlighting of syntax errors in custom command

### ISSUE THREAD

**Issue by danjenson** [lervag/vimtex#1671]
I have the following custom command in a `common.tex` file: `\newcommand{\eq}[1]{\begin{align*}#1\end{align*}}`. I use this as shorthand for doing this `\eq{...math stuff...}`. Unfortunately, it incorrectly highlights mathematical annotations like '_' and '^', etc. How can I make vimtex aware of command aliases or inform it that this is a math environment?

**Comment by lervag** [comment]
I'm sorry, but this is something I don't want to support directly. I don't see any good way to do it in a simple manner. My best suggestion is for you to stop using that custom command. IMHO, it is an anti pattern. Of course, for you personal projects it doesn't matter and you can do as you want, but if you were to collaborate with people, then such custom commands make it harder for your collaborators.

If you insist, then you can see in the default syntax plugin how the inline math groups are created. Do `:e $VIMRUNTIME/syntax/tex.vim` and search for "Inline Math Zones". The following is the version in my install:

```vim
 " Inline Math Zones: {{{2
 if s:tex_fast =~# 'M'
  if has("conceal") && &enc == 'utf-8' && s:tex_conceal =~# 'd'
   syn region texMathZoneV	matchgroup=Delimiter start="\\("			matchgroup=Delimiter	end="\\)\|%stopzone\>"			keepend concealends contains=@texMathZoneGroup
   syn region texMathZoneW	matchgroup=Delimiter start="\\\["			matchgroup=Delimiter	end="\\]\|%stopzone\>"			keepend concealends contains=@texMathZoneGroup
   syn region texMathZoneX	matchgroup=Delimiter start="\$" skip="\\\\\|\\\$"	matchgroup=Delimiter	end="\$"	end="%stopzone\>"		concealends contains=@texMathZoneGroup
   syn region texMathZoneY	matchgroup=Delimiter start="\$\$" 			matchgroup=Delimiter	end="\$\$"	end="%stopzone\>"	keepend concealends contains=@texMathZoneGroup
  else
   syn region texMathZoneV	matchgroup=Delimiter start="\\("			matchgroup=Delimiter	end="\\)\|%stopzone\>"			keepend contains=@texMathZoneGroup
   syn region texMathZoneW	matchgroup=Delimiter start="\\\["			matchgroup=Delimiter	end="\\]\|%stopzone\>"			keepend contains=@texMathZoneGroup
   syn region texMathZoneX	matchgroup=Delimiter start="\$" skip="\%(\\\\\)*\\\$"	matchgroup=Delimiter	end="\$"	end="%stopzone\>"		contains=@texMathZoneGroup
   syn region texMathZoneY	matchgroup=Delimiter start="\$\$" 			matchgroup=Delimiter	end="\$\$"	end="%stopzone\>"	keepend	contains=@texMathZoneGroup
  endif
  syn region texMathZoneZ	matchgroup=texStatement start="\\ensuremath\s*{"	matchgroup=texStatement	end="}"		end="%stopzone\>"	contains=@texMathZoneGroup
 endif

 syn match texMathOper		"[_^=]" contained
```

Of course, if you don't know vimscript this might be confusing. But the point is that you can use a similar command to define a `texMathZoneCustom` region for your custom commands.
