### ISSUE TITLE
Remap existing key mapping

### ISSUE THREAD

**Issue by horror-vacui** [lervag/vimtex#1673]
I've got a problem, which might relate to my limited knowledge of vim, and not to vimtex. I would like to use `VimtexCompileSS` in a mapping. I've not found any existing mapping to it, so I tried to create one by myself, but it failed. I wanted to map \ls to it, but vimtex has already one mapping to that key combination.
I've tried with `nmap <Leader>ls :VimtexCompileSS<CR>` after `packloadall` in my .vimrc. 

Could you help me with a suggestion how to do that?

**Comment by lervag** [comment]
Yes, `:VimtexCompileSS` is not mapped by default.

You can create a custom map for it with e.g.

```vim
augroup vimrc_tex
  autocmd!
  autocmd FileType tex nnoremap <buffer> <leader>ls :VimtexCompileSS<cr>
augroup END
```

The `augroup` and `autocmd` is used to ensure the mapping is only created in `.tex` files, and the `<buffer>` expression ensures the mapping is only valid in the buffer.

You can also create a file like `~/.vim/after/ftplugin/tex.vim` and put the map there (i.e. the `nnoremap ...` part above). This avoids the use of the `autocmd`. I personally like this better.

**Comment by horror-vacui** [comment]
Unfortunately this does not work. The `tex.vim` is loaded (I defined another mapping there, which does work), but `\ls` is still mapped to default 'tex file changing' command. I am clueless why the mapping has not been overridden.

**Comment by lervag** [comment]
Ah, I think the issue here is that you want to use `<localleader>` instead of `<leader>`. Have you specified the leader key to e.g. `<space>`?

**Comment by horror-vacui** [comment]
Awesome! I specified a localleader and then everything worked. Thanks for your help!

**Comment by lervag** [comment]
No problem, happy to hear it works :)
