### ISSUE TITLE
Option to move section to the top after jumping to it from ToC

### ISSUE THREAD

**Issue by horror-vacui** [lervag/vimtex#1674]
**Describe the solution you'd like**
I would like an option which allows changing the behaviour of jumping to a section, label, etc. from the table of contents. By default, the selected label is in the middle of the screen, just as would be the case after the `zz` key combination. I would like to see the selected section on the top of the screen, equivalently to issuing the `zt` key combination.

**Describe alternatives you've considered**
Manually typing `zt` after every jump.

**Additional context**
It is not a vital feature, just something I find nice to have.

**Comment by lervag** [comment]
This should be possible now with something like the following:

```vim
augroup vimtex_events
  au!
  au User VimtexEventTocActivated normal! zt
augroup END
```

Note, there is no `zz` performed by default, but `zv` is called to ensure folds are open on the cursor position. I think this may be the reason for why the screen is position with cursor in the middle, but not sure.

**Comment by horror-vacui** [comment]
Worked like a charm! Thanks!

**Comment by lervag** [comment]
No problem, and thanks for the suggestion. I think this allows useful customizations.
