### ISSUE TITLE
E121: Undefined variable: b:vimtex_syntax on compiler callback when vimtex syntax is disabled

### ISSUE THREAD

**Issue by yongrenjie** [lervag/vimtex#1675]
**Issue**
When `g:vimtex_syntax_enabled` is `0`, compiling a beamer file gives the following error message:

```
Error detected while processing function <SNR>53_callback_continuous_output[6]..vimtex#compiler#callback[21]..vimtex#syntax#load#pac
kages[2]..vimtex#syntax#p#beamer#load:                                                                                              
line    1:                                                                                                                          
E121: Undefined variable: b:vimtex_syntax                                                                                           
E116: Invalid arguments for function has_key(b:vimtex_syntax, 'beamer') | return | endif                                            
Error detected while processing function <SNR>53_callback_continuous_output[6]..vimtex#compiler#callback:                           
line   21:                                                                                                                          
E171: Missing :endif                                                                                                                
Error detected while processing function <SNR>53_callback_continuous_output:                                                        
line    6:                                                                                                                          
E171: Missing :endif
```

The compilation itself works perfectly OK and the error disappears very quickly once the compilation is done so there is no actual issue with the functionality, just a minor annoyance to have the error pop up.

**minimal.vimrc** (I didn't set `rtp` because I install packages to ~/.vim/pack/plugins/start):
```
filetype plugin indent on
syntax on
let g:vimtex_syntax_enabled=0
```

It seems that with when vimtex syntax is disabled, the dictionary `b:vimtex_syntax` is never initialised, so all the checks `if has_key(b:vimtex_syntax, '<key>')` throw `E121`. If I re-enable `g:vimtex_syntax_enabled` then the error goes away.

This issue was introduced with commit 2ee514fc and (I think) occurs with all of the files inside `autoload/vimtex/syntax/p` since I get it with `biblatex` as well. I personally patched it out very crudely by using `catch /E117:\|E121:/` on lines 67 and 73 of `autoload/vimtex/syntax/load.vim` but I am sure you will know of a more proper way to fix it :-)

As for a minimal tex file, the following beamer works:

**minimal.tex**
  ```tex
\documentclass{beamer}
\begin{document}
\begin{frame}
    \frametitle{Hello}
    \maketitle
\end{frame}
\end{document}
  ```

**Comment by lervag** [comment]
I've fixed this now, I think. :)

**Comment by yongrenjie** [comment]
Thank you for the quick fix & for your work on the plugin 😀

**Comment by lervag** [comment]
No problem, and thank you for reporting :)
