### ISSUE TITLE
Ctrl-n completion takes a long time for “scanning included file”

### ISSUE THREAD

**Issue by xiankunxu** [lervag/vimtex#1677]
When put `Plugin 'lervag/vimtex'` in my `.vimrc` file. Every time when I use `Ctrl-n` to do auto completion, it takes several seconds to search patterns in files located in `/usr/share/texlive/texmf-dist/tex/`.

If I remove vimtex, it will not search inside these files.

I found a similar issue from here:  https://vi.stackexchange.com/questions/11349/ctrl-n-completion-takes-a-long-time-for-scanning-included-file.  But the solution does not work for me. I tried to: `setglobal complete=.`  in my `.vimrc` file, does not help.

Any help is appreciated.

Thanks,
Xiankun

**Comment by lervag** [comment]
> When put Plugin 'lervag/vimtex' in my .vimrc file. Every time when I use Ctrl-n to do auto completion, it takes several seconds to search patterns in files located in /usr/share/texlive/texmf-dist/tex/.

First, I would like to point out that this is not **auto** completion, but manual completion. Auto completion implies that the completion occurs automatically.

`CTRL-n` will invoke generic keyword completion (see `:help i_CTRL-N` for more info). The keywords will be searched from places as specified with the `complete` option:

```
						*'complete'* *'cpt'* *E535*
'complete' 'cpt'	string	(default: ".,w,b,u,t")
			local to buffer
	This option specifies how keyword completion |ins-completion| works
	when CTRL-P or CTRL-N are used.  It is also used for whole-line
	completion |i_CTRL-X_CTRL-L|.  It indicates the type of completion
	and the places to scan.  It is a comma separated list of flags:
	.	scan the current buffer ('wrapscan' is ignored)
	w	scan buffers from other windows
	b	scan other loaded buffers that are in the buffer list
	u	scan the unloaded buffers that are in the buffer list
	U	scan the buffers that are not in the buffer list
	k	scan the files given with the 'dictionary' option
	kspell  use the currently active spell checking |spell|
	k{dict}	scan the file {dict}.  Several "k" flags can be given,
		patterns are valid too.  For example: >
			:set cpt=k/usr/dict/*,k~/spanish
<	s	scan the files given with the 'thesaurus' option
	s{tsr}	scan the file {tsr}.  Several "s" flags can be given, patterns
		are valid too.
	i	scan current and included files
	d	scan current and included files for defined name or macro
		|i_CTRL-X_CTRL-D|
	]	tag completion
	t	same as "]"

	Unloaded buffers are not loaded, thus their autocmds |:autocmd| are
	not executed, this may lead to unexpected completions from some files
	(gzipped files for example).  Unloaded buffers are not scanned for
	whole-line completion.

	As you can see, CTRL-N and CTRL-P can be used to do any 'iskeyword'-
	based expansion (e.g., dictionary |i_CTRL-X_CTRL-K|, included patterns
	|i_CTRL-X_CTRL-I|, tags |i_CTRL-X_CTRL-]| and normal expansions).
```

Note, in particular, that the default value does _not_ include `i` and `d`. This means that you are experiencing a result of your own personal configuration.

The solution is to change your vimrc file. My guess is that you have copied some configuration from others, e.g. something like this:

```vim
set complete+=U,s,k,kspell,d,]
```

I propose that you remove the `,d` part.

**Comment by xiankunxu** [comment]
Hi Lervag,

Thanks for the solution. I tried " set complete=." instead of "setglobal complete=.", now the problem solved.

Thanks,
Xiankun

**Comment by lervag** [comment]
Hi,

Yes, that should work. See the `:help` text for the complete option if you want to use more advanced settings.

Happy to hear that the problem is solved.

**Comment by Rmano** [comment]
@lervag  notice that in my `vim` I have:

```                                               *'complete'* *'cpt'* *E535*
'complete' 'cpt'        string  (default: ".,w,b,u,t,i") 
                        local to buffer
                        {not in Vi}
```

so that `i` **is** included in the default set. (version `version 8.0.1453`)

Just to add my 0.2¢...

**Comment by lervag** [comment]
Thanks, @Rmano; I was not aware this was default in Vim. Good to know! I think it is sensible to keep it out, because parsing included files can take some time in many kinds of projects.

**Comment by Rmano** [comment]
> Thanks, @Rmano; I was not aware this was default in Vim. Good to know! I think it is sensible to keep it out, because parsing included files can take some time in many kinds of projects.

Yes. In LaTeX could be a real black hole (especially if you use tikz...)

**Comment by Rmano** [comment]
> Yes. In LaTeX could be a real black hole (especially if you use tikz...)

Now, if it were possible to limit the recursion to just one...

**Comment by lervag** [comment]
Hmm. That could be possible. It could have "unintended" side effects, though. Like, for instance, if you work on "deep" projects with files for each section and for each chapter. Or similar. :\

Feel free to open a new issue with a feature request regarding this; we could have a discussion on whether or not it makes sense to make the `inclexpr` even smarter.

**Comment by Rmano** [comment]
Done, see #1681

**Comment by lervag** [comment]
Great, thanks!

**Comment by llinfeng** [comment]
Thank you guys for walking through the setting for `set complete`. `<c-n>` has been bothering me for quite a number of years :) 

I am currently settled with specifying `setlocal complete=.,w,b,u,t` in `~/vimfiles/ftplugin/tex.vim`.

**Comment by lervag** [comment]
No problem, happy to hear this helps. Let's continue the relevant discussion at #1681; I think we can find ways to improve things without fully disabling the `i` flag for the `complete` option.

**Comment by lervag** [comment]
The option `g:vimtex_include_search_enabled` was added in #1358 to alleviate this particular issue. I forgot about that. See also my [comment in #1681](https://github.com/lervag/vimtex/issues/1681#issuecomment-624868852) for more info.
