### ISSUE TITLE
Limit the depth of `set complete+= i` option.

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#1681]
In several LaTeX projects, especially when using heavy packages like `tikz`, you have to avoid having `i` in your `set complete` options, because the inclusion of packages can go *really* deep (and the delay is quite noticeable). On the other hand, if you are using a local package or including local files, it would be handy to have the completion of commands defined there.

One possible solution (I think) could be to optionally limit the level of recursion of searched files to, say, 1 or 2 levels. That way you can have a mid-ground between speed and commodity.

This issue has been prompted by issue #1677 

(This is obviously a low-priority-as-possible issue ;-))

**Comment by lervag** [comment]
Thanks! A good way forward is to create a relevant and good test case, preferably one that involves a multi file project with more than two levels of depth. This would help very much in working on possible solutions.

One idea could be to limit recursion only for files within a texmf tree. That seems "sensible" to me, at least.

**Comment by Rmano** [comment]
What about this? 

File 1: `main.tex`:
```latex
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{xcolor}
\input{level1.tex}% my macros
\begin{document}
    Text here
    
\end{document}
```

and file `level1.tex`:
```latex
\usepackage{tikz}
\def\mymacro{Alfa}
```
with  a `minivimrc`:

```vim
set nocompatible
let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
set complete+=i
```

The idea is that with the new option, a completion must find commands in `xcolor` (for example, `\color`) and `\mymacro` in `level1.tex`, but not the zillions things in `tikz`. 

I have done a GIF (it's fast here, but the first time was slower --- now my file cache was primed so ...)
 
![Peek 2020-04-29 12-58](https://user-images.githubusercontent.com/6414907/80589237-17205880-8a1a-11ea-9393-08e9c9aee777.gif)

**Comment by lervag** [comment]
> The idea is that with the new option, a completion must find commands in `xcolor` (for example, `\color`) and `\mymacro` in `level1.tex`, but not the zillions things in `tikz`.

I've looked into things now. I don't think we can avoid recursion, because I can't find any way of recognizing the recursion. That is, when completing with `<c-n>`, the `includeexpr` function (`vimtex#include#expr`) is called for each detected include statement (according to the `include` option). I can't detect which file is currently parsed, and so it seems very difficult to implement a good solution here.

One possible solution is to ignore all "global" package files, e.g. files under a texmf tree. It might not be what most people want, though.

**Comment by llinfeng** [comment]
Is it possible to _fine tune_ what is counted as "included files"? Say, ignore files included through `\usepackage` and keep only files included through `\input` and `\bibliography` command?

For now, I think the long searching time is introduced mainly by the `\usepackage{}` commands in the preamble of the TeX file. On the contrary, for files that are helpful to be sourced for manual completion, like `\input{chapter.tex}` and `\bibliography{BibFile}`, they won't take that long to source anyways.

---- 

An alternative is to keep both `chapter.tex` and `BibFile.bib` opened in a buffer at the background. Then, a simple `set complete=.,w,b,u,t` setting shall source these "desired sources" and avoid the large majority of other included files in the preamble.

**Comment by lervag** [comment]
@llinfeng Yes, this is partly what I mean with

> One possible solution is to ignore all "global" package files, e.g. files under a texmf tree. It might not be what most people want, though.

However, I just noticed that I've already at least partially worked on this stuff before. See `:help g:vimtex_include_search_enabled`:

```
*g:vimtex_include_search_enabled*
  Vimtex sets 'includeexpr' to recognize included files. If a file isn't found
  in the current directory, Vimtex uses `kpsewhich` to search for it in the
  system TeX distribution. If the 'complete' option includes "i", invoking
  keyword completion with |i_CTRL-N| will search included files for completion
  possibilities. In this case, there may be a lot of calls to `kpsewhich`
  while scanning for included files during the first invocation of keyword
  completion, and this may introduce a significant delay. Subsequent keyword
  completions should be faster, as the calls to `kpsewhich` are cached.

  This option allows to disable searching for included files with `kpsewhich`,
  and with that prevent the above explained delay.

  Default value: 1
```

So, I think the completion should be fast when one uses:

```vim
let g:vimtex_include_search_enabled = 0
```

In one of my papers, I see an improvement from 10.1 seconds to 0.37 seconds when I disable that option. I'm sorry for having forgotten about it!

Note, though: If you __do__ disable it, then you will not be able to do `gf` on a usepackage and open the corresponding `.sty` file. This is probably OK for most people, though.

**Comment by lervag** [comment]
For reference: The option was added in #1358. I didn't implement it myself, which is probably why I didn't remember it.

**Comment by llinfeng** [comment]
Great catch! Setting `g:vimtex_include_search_enabled` to `0` works directly out of the box. Many thanks!

**Comment by lervag** [comment]
@Rmano What do you think; is it an OK "solution", or should we discuss other solutions?

**Comment by Rmano** [comment]
@lervag yes - given the restrictions I think it's the best possible solution. It's a bit of a pity that the recursion level is not kept anywhere...

**Comment by lervag** [comment]
> @lervag yes - given the restrictions I think it's the best possible solution. It's a bit of a pity that the recursion level is not kept anywhere...

Agreed, I would like it better if we could implement a smarter way to handle this. But as mentioned above, I don't see how to do it. I tried using `expand('%:h')` inside the `includeexpr` function, but (not so unexpectedly) this does not work and always returns the file we're working on, not the current file in the `<c-n>` include search recursion. Note, one can also use `:checkpath!` to see how the `includeexpr` searches and finds included pages.

I'll close this issue, then. But if anyone should happen to come up with a way to improve these things, then I'll be happy to hear it!
