### ISSUE TITLE
zathura synctex check is broken for non-zsh shells

### ISSUE THREAD

**Issue by phijor** [lervag/vimtex#1682]
# Issue
The code here

https://github.com/lervag/vimtex/blob/32d72e57cf31440752158a8a16bc5efa4d684a3a/autoload/vimtex/view/zathura.vim#L15

uses [`zsh`-specific syntax](http://zsh.sourceforge.net/Doc/Release/Expansion.html#g_t_0060_003d_0027-expansion) and won't work with other shells.

# minimal.vim

Independent of configuration.

# minimal.tex
 Independent of any `*.tex` files.

# Commands/Input

Run

```sh
SHELL=/usr/bin/bash nvim -u NONE '+echo(system("ldd =zathura"))'
```

# Observed Behaviour

`nvim` outputs

```
ldd: ./=zathura: No such file or directory
Press ENTER or type command to continue
```

# Expected Behaviour

`nvim` outputs whatever `ldd $(which zathura)` would output:

```
        linux-vdso.so.1 (0x00007ffd88cc1000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f9246bac000)
        libm.so.6 => /usr/lib/libm.so.6 (0x00007f9246a66000)
        libgirara-gtk3.so.3 => /usr/lib/libgirara-gtk3.so.3 (0x00007f9246a46000)
        libgtk-3.so.0 => /usr/lib/libgtk-3.so.0 (0x00007f92462c7000)
        <... snip>
```

**Comment by lervag** [comment]
I think my latest update fixes this. Sorry about the inconvenience!

**Comment by lervag** [comment]
As pointed out in [this reddit thread](https://www.reddit.com/r/archlinux/comments/ga8l0p/vimtex_zathura_is_not_linked_to_libsynctex/), the first fix does not work in e.g. the fish shell. The second fix should work more generally.

**Comment by meesvermeulen** [comment]
Is there an option to disable this check? I use zathura with firejail, which means that `which zathura` returns the location of a symlink to firejail, so the check will fail.

**Comment by lervag** [comment]
No, not currently. Could you explain a little bit more how this works? I don't know firejail. Is it possible to improve the `$(which zathura)` command to more reliable return the zathura path? If there is not good way to handle this, then I'll agree to add an option to disable the check.

**Comment by meesvermeulen** [comment]
Firejail is used to sandbox the execution of zathura. To launch zathura with firejail by default a symbolic link named zathura is added in `/usr/local/bin` pointing to firejail. I don't think there's any easy way to detect the real zathura without running it. I wonder if the `zathura -h` will also print the synctex options if synctex is not available...

In the meantime I have started using qpdfview, as I had some other issue with zathura as well (it hangs when I start compilation for multiple seconds, should I create a new issue for this, or is this known/expected behavior?)

**Comment by lervag** [comment]
Thanks for the info on firejail.

> I wonder if zathura -h will also print the synctex options if synctex is not available...

I don't remember exactly why, but I vaguely remember that grepping `zathura -h` did not always work as expected. I might remember falsely and I agree it certainly looks like this is a valid option.

In any case, I've added the option `g:vimtex_view_zathura_check_libsynctex`. If you set it to 0 or `v:false`, the `ldd` check will be disabled.

> In the meantime I have started using qpdfview, as I had some other issue with zathura as well (it hangs when I start compilation for multiple seconds, should I create a new issue for this, or is this known/expected behavior?)

Feel free to open a new issue. If it is related to Zathura, then I probably can't help you, but perhaps I can help guide you in the right direction.

**Comment by BachoSeven** [comment]
If it can be any useful to you, I experimented a bit and, independently of grepping `zathura -h`, the output of 
```
zathura -x ''
```
yields `error: Built without synctex support, but synctex specific option was specified.`

Otherwise, it opens zathura, of course.

**Comment by lervag** [comment]
Thanks, it's interesting, but I'm not sure it's useful. We don't want to test for synctex support in a way that actually opens Zathura.
