### ISSUE TITLE
TODO ToC w/o prefix

### ISSUE THREAD

**Issue by horror-vacui** [lervag/vimtex#1683]
**Describe the solution you'd like**
Would it be possible to create an option which removes the "TODO:" prefix --- or any prefix in general --- from the todo ToC in order to use the side panel space more efficiently?
I use `% TODO: buy milk` format for my TODOs, instead of the latex command.

**Describe alternatives you've considered**
In a layer='todo' ToC, I would like to see only `buy milk` instead of `TODO: buy milk`

**Comment by lervag** [comment]
I've updated now so that you can use the `g:vimtex_toc_todo_labels` option. See docs for how to set it, or let me know if it is unclear.
