### ISSUE TITLE
'align' contents not highlighted as math

### ISSUE THREAD

**Issue by ddrake** [lervag/vimtex#1685]
**Issue**
Regression: Prior to commit 62dc919 on 7/30/19, math expressions inside
```tex
\begin{align*}
\end{align*}
```
or
```tex
\begin{align*}
\end{align*}
```
were correctly highlighted as math, but since that commit, the syntax highlighting is not correct in that context.

**Observed Behaviour**
contents of
```tex
\begin{align*}
	math stuff...
\end{align*}
```
is highlighted as text (not math)

**Expected Behaviour**
contents of
```tex
\begin{align*}
	math stuff...
\end{align*}
```
highlighted as math

**Minimal tex file demonstrating the issue**
```tex
\documentclass{minimal}
  \begin{document}
    \begin{align*}
      iamnothighlightedbutshouldbe
    \end{align*}
    some text
    \begin{align}
      iamnothighlighedbutshouldbe
    \end{align}
    some text
    \[ iamhiglightedok \]
    some text
    $iamhiglightedok$
\end{document}
```

**Output from VimtexInfo**
```
System info
  OS: Ubuntu 20.04 LTS
  Vim version: VIM 8.1 (1-2269)
  Has clientserver: true
  Servername: VIM

vimtex project: tmp
  base: tmp.tex
  root: /home/dow/tmp
  tex: /home/dow/tmp/tmp.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    backend: jobs
    output: /tmp/vRbbXma/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: minimal
```

**Comment by lervag** [comment]
Sorry, but this is not a bug. It is a change in which package specific syntax rules are only loaded when the package is detected. In some cases, the package is not immediately detected; e.g., the package `amsmath` which defines the `align` environments is often loaded implicitly through other packages and classes, and so the package is not immediately recognized. However, the package should be recognized when your document is compiled and the `.fls` file is present. Can you confirm this behaviour?

The reason for this change is that syntax matching can be expensive, and it makes sense to avoid loading extra rules unless specifically necessary. However, if it is too inconvenient, we can discuss ways to override this. Note, in previous discussions and previous work, I have concluded that it is very difficult to perform a (manual) recursive search for the package list. There are two ways that are used now: i) parse the `.fls` file if it is present, and ii) manual search by `\usepackage` in preamble. The first should work very well, I think, but only works when your document is successfully compiled. The second works quite well, but may miss implicitly loaded packages.

**Comment by ddrake** [comment]
Thanks for your reply,

I didn't notice it before, but I can confirm that the syntax highlighting is correct after compiling, and I understand your design choice.  I am still having issues, however using the current version of Vimtex

The syntax highlighting is not a big concern visually, but I'm using many Ultisnips snippets which rely on some python/vimscript code from
here https://castel.dev/post/lecture-notes-1
(pasted below) to allow or suppress snippet expansion depending on whether we're in a math context.  I imagine you are aware of this approach.

After updating Vimtex, I found that the normal snippet expansion no longer works in the align environment (even after compilation).  I've struggled to debug this issue without success.  Perhaps there is a better way determine the context than inferring from the syntax highlighting, or perhaps some texMathZone information has since changed.

I appreciate any suggestions you may offer that might allow me to continue using context-dependent snippets with the current version of Vimtex.

Best,
Dow

global !p

texMathZones = ['texMathZone'+x for x in
['A', 'AS', 'B', 'BS', 'C', 'CS', 'D', 'DS', 'E',
'ES', 'F', 'FS', 'G', 'GS', 'H', 'HS', 'I', 'IS',
'J', 'JS', 'K', 'KS', 'L', 'LS', 'DS', 'V', 'W',
'X', 'Y', 'Z']]

texIgnoreMathZones = ['texMathText']
texMathZoneIds = vim.eval('map('+str(texMathZones)+", 'hlID(v:val)')")
texIgnoreMathZoneIds = vim.eval('map('+str(texIgnoreMathZones)+ \
", 'hlID(v:val)')")
ignore = texIgnoreMathZoneIds[0]

def math():
"""
Check whether we are in a math context; return a boolean.
"""
synstackids = vim.eval("synstack(line('.'), col('.')" + \
  " - (col('.')>=2 ? 1 : 0))")
try:
first = next(i for i in reversed(synstackids)
if i in texIgnoreMathZoneIds or
i in texMathZoneIds)
return first != ignore
except StopIteration:
return False
endglobal


________________________________

**Comment by ddrake** [comment]
The syntax highlighting in Vimtex is working fine for me, including for amsmath align, etc...  
I worked out how to fix the math context detection issue I was having with the current Vimtex.
It just amounted to adding the highlight groups to my detection script: AmsA through AmsG and BreqnA through BreqnD, where each of these has a starred version except AmsF (xxalignat).  I found these by grepping the Vimtex source code.  I also removed the groups that were replaced by these groups, namely those with suffixes E through L.

To see the mathzone ids that were active in my tex file, I used
```
:echo synstack(line('.'), col('.'))
```
and to see if a zone was defined, I used e.g.
```
:echo hlID('texMathZoneA') 
```
My updated math() function and related code is like this

```
# Definitions of texMathZone highlight group suffixes,
# which are currently defined by tex/vimtex (if known)
# A: ?, B: ?, C: equation, D: ?, V: ?, W: \[ \], X: $ $, Y: ?, Z: ?
# AmsA: align, AmsB: alignat, AmsC: gather, AmsD flalign
# AmsE; xalignat, AmsF: xxalignat (no star), AmsG: mathpar
# BreqnA: dmath, BreqnB: dseries, BreqnC: dgroup, BreqnD: darray
# Previously-defined suffixes: E, F, G, H, I, J, K, L no longer seem to 
# be defined.

sfx = """A B C D E V W X Y Z
             AmsA AmsB AmsC AmsD AmsE AmsF AmsG
	     BreqnA BreqnB BreqnC BreqnD""".split()
nostarsfx = 'AmsF V W X Y Z'.split()
nostarZones = ['texMathZone'+x for x in sfx]
starZones = ['texMathZone'+x+'S' for x in sfx if x not in nostarsfx]
texMathZones = nostarZones + starZones
texIgnoreMathZones = ['texMathText']
texMathZoneIds = vim.eval('map('+str(texMathZones)+", 'hlID(v:val)')")
texIgnoreMathZoneIds = vim.eval('map('+str(texIgnoreMathZones), 'hlID(v:val)'))
ignore = texIgnoreMathZoneIds[0]

def math():
	"""
	Check whether we are in a math context; return a boolean.
	"""
        # get a list of zone ids for the cursor location based on syntax highlighting   
	synstackids = vim.eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")
        # filter out the non-mathzone ids
	ids = [i for i in synstackids
		       if i in texMathZoneIds
		       or i in texIgnoreMathZoneIds]
	return (ids[-1] != ignore) if len(ids) > 0 else False
endglobal
```
After making my own fixes, I came across updated code in [this repository](https://github.com/gillescastel/latex-snippets/blob/master/tex.snippets) which I assume should also work.

**Comment by lervag** [comment]
Sorry for the late reply! I'm happy to hear you've figured things out yourself, and I also appreciate that you've supplied the updates you've used to make things work as you expect.

During refactoring the syntax packages, I found it made sense to use more recognizable names for the different math zones. I didn't actually consider that this could affect users like you with ultisnippet code that relied on the old zone names. Thanks for making me aware of it, and again thanks for supplying a relevant fix for it. Also, thanks for the links to Gilles Castel's updated files (@gillescastel).
