### ISSUE TITLE
Preserve existing indentation when not indenting on braces.

### ISSUE THREAD

**Issue by macleginn** [lervag/vimtex#1686]
**Issue**

I have a list with a couple of quotes in it. With default settings, it gets indented like this:

```tex
\begin{enumerate} 
\item blah blah blah blah blah blah blah blah blah blah blah blah blah blah 
      blah blah blah blah blah blah blah blah blah blah \enquote{blah blah
		blah blah blah blah blah blah blah blah blah blah blah blah
      blah blah}.
\end{enumerate}
```

And if I disable indentation on braces, it gets indented like this:

```tex
\begin{enumerate} 
\item blah blah blah blah blah blah blah blah blah blah blah blah blah blah    
      blah blah blah blah blah blah blah blah blah blah \enquote{blah blah
blah blah blah blah blah blah blah blah blah blah blah blah
blah blah}.
\end{enumerate}
```

Supposedly, disabled indentation should not actively de-indent things. It would be even better to support enquote, textit, etc., as environments.

**Comment by lervag** [comment]
Could you provide as a minimum the vimtex config you use?

**Comment by macleginn** [comment]
Here it is, with indentation-on-brace disabled:

```vim
let g:vimtex_view_method = 'skim'
let g:vimtex_quickfix_latexlog = {
          \ 'overfull' : 0,
          \ 'underfull' : 0,
          \ 'packages' : {
          \   'default' : 0,
          \ },
          \}
let g:vimtex_indent_delims = {
          \ 'open' : [],
          \ 'close' : [],
          \ 'close_indented' : 0,
          \ 'include_modified_math' : 1,
          \}
```

When it is enabled, only the first two `let`s are active.

**Comment by macleginn** [comment]
I shoudn't have removed the closing brace as well, should I?

**Comment by lervag** [comment]
Yes, this should work. In fact, it works for me.

Note, indentation assumes that the lines above are correctly indented. In your example, it is not. If I copy your example:

```tex
\begin{enumerate}
\item blah blah blah blah blah blah blah blah blah blah blah blah blah blah
      blah blah blah blah blah blah blah blah blah blah \enquote{blah blah
e       blah blah blah blah blah blah blah blah blah blah blah blah
      blah blah}.
\end{enumerate}
```

Now do `gg=G`, then I get

```tex
\begin{enumerate}
  \item blah blah blah blah blah blah blah blah blah blah blah blah blah blah
    blah blah blah blah blah blah blah blah blah blah \enquote{blah blah
e   blah blah blah blah blah blah blah blah blah blah blah blah
    blah blah}.
\end{enumerate}
```

I use the following minimal vimrc file:

```vim
set nocompatible
let &rtp = 'path-to-vimtex,' . &rtp
filetype plugin indent on

set nomore
set shiftwidth=2
set expandtab

let g:tex_flavor = 'latex'

let g:vimtex_indent_delims = {
      \ 'open' : [],
      \ 'close' : [],
      \}
```

Note, btw: you don't need to include the keys that you don't change, so you can safely remove `close_indented` and `include_modified_math` if you don't change them.

**Comment by macleginn** [comment]
They were correctly indented in the file, I messed things up a bit when posting. Anyway, it works fine with the settings you provided, thanks!

**Comment by lervag** [comment]
Great, happy to hear it. If you should find it does not work with some other settings, let me know.
