### ISSUE TITLE
Can't use mathmode mappings on subsequent buffers

### ISSUE THREAD

**Issue by PROgram52bc** [lervag/vimtex#1688]
**Issue**

When I open multiple `.tex` files for editing, I noticed that the mathmode mappings apply only to the first buffer, but not the rest of them. For example, when I do
```
vim 1.tex 2.tex
```
under the buffer corresponding to `1.tex`, I can type the following in insert mode
```latex
$`l$
```
which would be turned into
```latex
$\lambda$
```
But this does not work in the buffer corresponding to `2.tex`

I think the same thing happens when I open new files with `:tabnew 2.tex`, or `:badd 2.tex`.

When I do
```
:imap
```
for `1.tex`, the output contains many mappings like the following
```
...
i  `vr         *@vimtex#imaps#wrap_math("`vr", '\varrho')
i  `vq         *@vimtex#imaps#wrap_math("`vq", '\vartheta')
i  `vk         *@vimtex#imaps#wrap_math("`vk", '\varkappa')
i  `vf         *@vimtex#imaps#wrap_math("`vf", '\varphi')
i  `ve         *@vimtex#imaps#wrap_math("`ve", '\varepsilon')
i  `Y          *@vimtex#imaps#wrap_math("`Y", '\Psi')
i  `X          *@vimtex#imaps#wrap_math("`X", '\Xi')
i  `W          *@vimtex#imaps#wrap_math("`W", '\Omega')
i  `U          *@vimtex#imaps#wrap_math("`U", '\Upsilon')
i  `S          *@vimtex#imaps#wrap_math("`S", '\Sigma')
i  `Q          *@vimtex#imaps#wrap_math("`Q", '\Theta')
...
```
But none of them appear when I run it under the file `2.tex`

**minimal .vimrc**

  ```vim
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'lervag/vimtex'
call vundle#end()
filetype plugin indent on
  ```

**Comment by lervag** [comment]
What's the output of `:set filetype` in the various files? If it is plaintex, then see `:help vimtex-comment-internal`.

**Comment by PROgram52bc** [comment]
I got `filetype=tex` in all of them, just that it seems the math mode mappings are not available in buffers opened subsequently. Are you able to reproduce it?

**Comment by lervag** [comment]
Yes, I can reproduce it. Fixing it asap.
