### ISSUE TITLE
`VimtexReload` destroy the `vimtex#imaps#add_map`

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#1690]
**Issue**

I find that if I reload the plugin by `VimtexReload`, then the `` `a`` Cann't expand to $\alpha$ correctly.

**minimal.vim**

**minimal.tex**

I start vim with `vim -u minimal.vim minimal.tex`
**Commands/Input**

`` `a``
**Observed Behaviour**

If try to input `\alpha` by `` `a``, then it work as expected, however if I reload vimtex via `:VimtexReload`, then the same command expand to `'\alpha'`.
**Expected Behaviour**

I hope that even after reload the vimtex, the `` `a`` expand to `\alpha` correctly. 

**Output from VimtexInfo**

```bash
System info
  OS: Mac OS X 10.14.6 (18G4032)
  Vim version: VIM 8.2 (1-539)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

vimtex project: test
  base: test.tex
  root: /Users/vanabel/devlopment
  tex: /Users/vanabel/devlopment/test.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    backend: jobs
    output: /var/folders/bn/hvv2h3k972x_wdfd68frqnvw0000gn/T/vbvgnZy/2
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: amsart
```

**Comment by lervag** [comment]
Could you update to the most recent version and check if the problem persists? I recently updated imaps code to fix #1688, and I think the recent changes also fixes this issue.

**Comment by vanabel** [comment]
@lervag Thanks, it is fixed after I update to the newest version. Sorry for the false-alarm.

**Comment by lervag** [comment]
No problem! :)
