### ISSUE TITLE
Instructions for starting vim with server does not work (vim 8.2.539)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1691]
I have `vim 8.2.539` compiled with both `+clientserver` and `+autoservername`. 

Using the `vimtex`-provided documentation for starting with a server (both methods) causes `vim` to crash immediately upon opening.

**Comment by lervag** [comment]
Can you provide a minimal example? Are you sure this is related to vimtex?

**Comment by krishnakumarg1984** [comment]
**minimal.vim**

  ```vim
  set nocompatible
  let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/plugged/vimtex/after'
  filetype plugin indent on
  syntax enable
  if empty(v:servername) && exists('*remote_startserver')
      call remote_startserver('VIM')
  endif
  ```

**minimal.tex**
  ```tex
  \documentclass{minimal}
  \begin{document}
  Hello world!
  \end{document}
  ```

**Execution steps to reproduce**
  ```bash
  $ vim -u minimal.vim minimal.tex
  ```


Within vim, `echo serverlist()` results in empty result on my local `macOS` and crashes `vim` on a remote ssh session. The `vim` version is `8.2.0539`.

**Comment by lervag** [comment]
Ok, I've tested. I'm on Arch Linux with Vim version 8.2.510 and I have the `remote_startserver` function. With your minimal vimrc, things seem to work well. `:echo serverlist()` outputs `VIM`.

As far as I can tell, this is not an issue related to vimtex, but instead an issue related to Vim on MacOS.
