### ISSUE TITLE
Parallel processing for Vim and Latexmk (or other compiler)

### ISSUE THREAD

**Issue by norbert-op** [lervag/vimtex#1693]
I get quite a bit of lag during document compilation, so as an alternative I've been running `latexmk` from a terminal window. This uses a separate processor core and I can keep editing smoothly during compilation.

Is there a way to have Vimtex do this automatically? I know Latex has to run on a single core, but I'm not sure if the way Vimtex is written makes it necessary to run the compiler on the same core as Vim.

The feature I miss most with my workaround is forward search to the PDF viewer.

I'm using Windows 8.1, so this may function differently on Linux.

**Comment by lervag** [comment]
Vim version 8 should already support this, even on Windows. If you have a real issue, could you please describe it in more detail?

Note: Vim version 8 provides the `job` feature, which allows running jobs in the background. This is done by default in vimtex if possible.

**Comment by Konfekt** [comment]
Perhaps a red hering, but if the system lags during compilation, perhaps the job can be scheduled by the system, say by appending `s:scheduler` set to

```
  if has('unix') && executable('chrt') && executable('ionice')
      let s:scheduler = 'chrt --idle 0 ionice -c2 -n7 '
  elseif has('win32')
      let s:scheduler = (&shell =~? '\v(^|\\)cmd\.exe$' ? '' : 'cmd.exe ')
                  \ . 'start /B /LOW'
  else
      let s:scheduler = ''
  endif
```

**Comment by lervag** [comment]
Not so sure; are we solving any real issues with this? Feel free to submit a PR. :)

I'm closing this, as I don't quite see how this is a real issue. Feel free to reopen with more details.

**Comment by norbert-op** [comment]
It's good news that this is already a feature of Vim and Vimtex uses it. I don't have time for looking into my problem on Windows any further right now, but if I do in the future I'll open a separate issue.

Would you mind giving me an idea of how I would start troubleshooting it, though? I'm not sure what I would look for or how to detect it.

**Comment by lervag** [comment]
> Would you mind giving me an idea of how I would start troubleshooting it, though? I'm not sure what I would look for or how to detect it.

I assume you are referring to the first part of your original post:

> **I get quite a bit of lag during document compilation**, so as an alternative I've been running latexmk from a terminal window. This uses a separate processor core and I can keep editing smoothly during compilation.

It is still very vague, though. I think the basic approach of creating a minimal example is the best approach. This involves: i) create a minimal vimrc file, ii) create a minimal LaTeX file, iii) start Vim with the minimal vimrc file (e.g. `vim -u minimal.vim minimal.tex`). On Windows, things might be somewhat different. E.g.; do you use any command lines?

**Comment by norbert-op** [comment]
I'll definitely create a MWE and follow those steps if I open an issue. For now, I was thinking you could just give me some pointers on how to detect whether the `+job` feature is working as you designed it to be handled by `Vimtex`. I have Vim 8.2 compiled with `+job`, but beyond that I wouldn't know what to look for in the log file, etc.

**Comment by lervag** [comment]
If you do `:VimtexInfo` in a LaTeX project you will get some information on vimtex settings. You should find something like this there:

```
vimtex project: 
  name: 
  base: 
  root: .
  tex: 
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file
  compiler: latexmk
    backend: nvim
```

The backend should be `jobs` or something on Vim 8.2.

**Comment by norbert-op** [comment]
Ok, thanks. It's there as the backend, so it's not clear what the source of the problem is. This is only a minor inconvenience for me, since I have my workaround. I'll do some troubleshooting in the future if I have time for it, though. If it seems like Vimtex is the problem, I'll open an issue.

**Comment by lervag** [comment]
Great, that sounds good!

One thing you could test is whether you have the same problems with neovim. Neovim should also work well on Windows, if I understand correctly, and it has its own implementation of the jobs feature.
