### ISSUE TITLE
Using vim-polyglot and vimtex breaks vimtex on loading

### ISSUE THREAD

**Issue by Nagefire** [lervag/vimtex#1695]
When both vimtex and polyglot are loaded, vimtex refuses to start with the error message 
```
Error detected while processing /home/nagefire/.config/nvim/plugged/vimtex/after/syntax/tex.vim:
line    7:
E117: Unknown function: vimtex#syntax#init
Error detected while processing /home/nagefire/.config/nvim/plugged/vimtex/ftplugin/tex.vim:
line   25:
E117: Unknown function: vimtex#init
Error detected while processing /home/nagefire/.config/nvim/plugged/vimtex/after/ftplugin/tex.vim:
line   16:
E117: Unknown function: vimtex#check_plugin_clash
Error detected while processing /home/nagefire/.config/nvim/plugged/vimtex/indent/tex.vim:
line   98:
E121: Undefined variable: g:vimtex#re#not_bslash
E15: Invalid expression: g:vimtex#re#not_bslash . '\&'
line   99:
E716: Key not present in Dictionary: re_amp
E15: Invalid expression: '^[ \t\\]*' . s:indent_amps.re_amp
line  235:
E121: Undefined variable: g:vimtex#delim#re
E15: Invalid expression: (empty(s:re_open) ? '' : '\|') . g:vimtex#delim#re.delim_mod_math.open
```
The plugin never even loads, so its impossible to use `:checkhealth`. I know that vimtex and polyglot are incompatible, and the line `let g:polyglot_disabled=['latex', 'tex']` is included in my config. My plugin manager is vim-plug and minimal config to reproduce the error is
```vim
let g:polyglot_disabled=['latex', 'tex']

call plug#begin()
Plug 'sheerun/vim-polyglot'
Plug 'lervag/vimtex'
call plug#end()
```

**Comment by lervag** [comment]
> When both vimtex and polyglot are loaded, vimtex refuses to start with the error message

Do I understand correctly that the problem goes away when you remove polyglot?

**Comment by lervag** [comment]
Ok, I've tested and reproduced. However, this is __not__ a vimtex issue, this is definately a polyglot issue. I STRONGLY recommend not using vim-polyglot, but if you insist on using it, then please open an issue with that project instead.

(Btw: Try changing the order of the `Plug` statements.)

**Comment by lervag** [comment]
It seems vim-polyglot now bundles vimtex, which may explain your issue. If this is correct, then, if you insist on using vim-polyglot, you should be able to use vimtex with simply loading polyglot and not disabling anything latex related. I'm updating the docs.

**Comment by jansendotsh** [comment]
Sorry to bump an older thread but you can also explicitly disable vim-polyglot in a LaTeX file by putting the following in your vimrc with:
```
let g:polyglot_disabled = ['latex']
```
