### ISSUE TITLE
Add support for git-latexdiff

### ISSUE THREAD

**Issue by oponkork** [lervag/vimtex#1696]
As the repo description says [git-latexdiff](https://gitlab.com/git-latexdiff/git-latexdiff) is a simple, but very convenient wrapper around git and latexdiff. I have been using it to get diffed pdf output for my drafts which are version controlled. So far I have been using it simply in combination with `vimtex` with the following setup
```vim
command! -nargs=0 TexDiff call jobstart("texDiff ".b:vimtex['base']." > diff.log")
nmap <localleader>ld :TexDiff<CR>
```
where texDiff is a tiny little script which essentially runs the following command
```bash
git-latexdiff --ignore-makefile --latexmk --view --pdf-viewer zathura --cleanup keeppdf --quiet -p diffPreamble.tex --main draft.tex -o draft_diff.pdf HEAD --
```
The output is a pdf generated by latexdiff between the HEAD and last commit, and is immediately
opened for viewing. The barebone solution works, but I would love to get messages once the compilation is finished, to be able to view the diffed pdf using `<localleader>lv` and use vimtex's convenient quickfix workflow to fix issues.

Would it be possible to add `git-latexdiff` support in vimtex?

**Comment by lervag** [comment]
First, I'm curious: I've been using `latexdiff-vc --git` for the same effect. It seems `git-latexdiff` is a wrapper that makes this more convenient, if I understand correctly. It was difficult to find a more detailed description of why I would use `git-latexdiff` instead of `latexdiff-vc`. Do you have some input on this?

Now, adding support for this seems complicated. To be honest, I don't quite see that the effort is worth the gains. Except perhaps for one thing: Does `git-latexdiff` give output that is easy to parse for to quickfix? If so, then that would be interesting. I think this could warrant adding a compiler backend for it.

- Command for running `git-latexdiff`: You've already suggested something that seems close to "perfect". What's lacking is feedback. 
- Command for viewing: It would be "easy" to add some simple custom command/mapping, but a more complete integration is not viable. It seems to require a lot

**Comment by oponkork** [comment]
> First, I'm curious: I've been using `latexdiff-vc --git` for the same effect. It seems `git-latexdiff` is a wrapper that makes this more convenient, if I understand correctly. It was difficult to find a more detailed description of why I would use `git-latexdiff` instead of `latexdiff-vc`. Do you have some input on this?

I am not aware of `latexdiff-vc`, so unfortunately I can't compare it with `git-latexdiff`.

> Now, adding support for this seems complicated. To be honest, I don't quite see that the effort is worth the gains. Except perhaps for one thing: Does `git-latexdiff` give output that is easy to parse for to quickfix? If so, then that would be interesting. I think this could warrant adding a compiler backend for it.

`git-latexdiff` first creates a diffed source in a temporary folder, located in `/tmp` which is then compiled to generate the pdf. As I mentioned in the issue detail, one can set it use `latexmk` to compile the diffed source. To add feedback, I think it should be enough to get the location of temporary folder, and then use vimtex's latexmk backend to compile.

About fixing errors, I think there's no need to add support for it. If the compilation from `git-latexdiff` fails, a simple message to fix the original text should suffice.

**Comment by lervag** [comment]
Ok, thanks for the update. Unfortunately, I think this is too complicated to support in the manner you suggest. I could consider adding a command for `git-latexdiff` similar to what you suggest in your original post. The command would do something like this:

1. Run `git-latexdiff` (or `latexdiff-vc --git`) against a specified/inputted revision/tag. Utilize the `jobs` backend in Vim/neovim, and add a callback to notify the user when the diff is ready.
2. On error, open a scratch buffer to show the error output. (I'm talking about errors from running the `git-latexdiff` tool itself.)
3. If there is no error, then the command could have an option to automatically open the resulting pdf when it is finished. The predefined viewer backend would be used to open the pdf.

This would add a command `:VimtexVCDiff` with possibly a mapping `\ld`, as well as an option with the default arguments.

I'm not sure when I'll get the time to do this, but if this sounds like a solution you would find adequate, then I would leave this issue open until I've gotten around to it.

**Comment by oponkork** [comment]
> I'm not sure when I'll get the time to do this, but if this sounds like a solution you would find adequate, then I would leave this issue open until I've gotten around to it.

Sounds good to me. You can take your time, there's no hurry. I can live with the current setup,
but will try to see if I can manage callbacks and notification on my own.

Thanks a lot for your efforts in creating `vimtex`.

**Comment by lervag** [comment]
I've been thinking about this, and I can't see a way to do this that is going to be robust and "simple". Thus, I think if I try to add this, it may/will be the cause of many issues, and it will lead to more docs (already huge), more options (already too many), and so on. So, I've concluded I don't want to add this feature.

I think essentially that this is something best left for simple terminal sessions/bash scripts, Makefiles, or similar.

Sorry! But I hope some of my thoughts may be of help if you were/are to make an attempt yourself. And if you do implement this in a satisfactory manner, feel free to open a PR. I'll be glad to reconsider.

**Comment by oponkork** [comment]
@lervag Thanks for the update. As I said, the current setup works as it is, it just lacks feedback. I will try to implement the feedback part once I have some free time and let you know if it turns out to be any good. :)

**Comment by lervag** [comment]
Great, sounds good!
