### ISSUE TITLE
How can I get completion of .sty and .cls files?

### ISSUE THREAD

**Issue by krisfans** [lervag/vimtex#1699]
**Issue**
I'd like to get a completion of the `.sty` and `.cls` file , which is  a supported feature ,as  described in the picture , but I failed . 
![YoLWF0.png](https://s1.ax1x.com/2020/05/20/YoLWF0.png)

**minimal.vim**
 I use `deoplete` to get the completion ,  below is my `minimal.vim`

  ```vim
"------plug------------------------"
call plug#begin('$HOME/.vim/plugged') 
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/neoinclude.vim'
Plug 'Shougo/neosnippet.vim'
Plug 'Shougo/neosnippet-snippets'
Plug 'lervag/vimtex',{'for':'tex'}
Plug 'honza/vim-snippets'
call plug#end()
let g:plugged#enable_at_startup = 1 

"---------------deoplete-------------"
if has('nvim')
    let g:python3_host_prog = "D:/Software/Python/Python38-32/python.exe"
endif

let g:deoplete#enable_at_startup = 1
call deoplete#custom#option({
\ 'auto_complete_delay': 200,
\ 'smart_case': v:true,
\ })
call deoplete#custom#source('LanguageClient',
            \ 'min_pattern_length',
            \ 2)
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
call deoplete#custom#option('sources', {
            \ '_':[] , 
            \ 'c': ['LanguageClient','buffer','file'],
            \ 'python':['jedi','buffer','file'],
            \ 'tex': []
            \})
" This is new style
call deoplete#custom#var('omni', 'input_patterns', {
      \ 'tex': g:vimtex#re#deoplete
      \})

"---------------vimtex---------------"
let g:tex_flavor  = 'latex'    
if has('nvim')
    let g:vimtex_compiler_progname = 'nvr'
endif

  ```

**minimal.tex**

  ```tex
\documentclass{article}
\usepackage {amsmath}
\begin{document}
$x^2+y^2=1$
\end{document}
  ```

**Commands/Input**

**Observed Behaviour**
![2020-05-20-13-41-56](https://user-images.githubusercontent.com/57793534/82409547-9eed0600-9aa0-11ea-94f6-167f3d0d7b57.gif)

**Expected Behaviour**
![YTSHg0.png](https://s1.ax1x.com/2020/05/20/YTSHg0.png)

**Output from VimtexInfo**

![Snipaste_2020-05-20_14-09-40](https://user-images.githubusercontent.com/57793534/82411092-aeba1980-9aa3-11ea-99fb-9ab5c9b5848b.png)

**Comment by lervag** [comment]
A couple of comments to your config:

```vim
"------plug------------------------"
# Change this:
Plug 'lervag/vimtex',{'for':'tex'}

# To this:
Plug 'lervag/vimtex'

# This is no longer necessary, as it is set automatically/by default
if has('nvim')
  let g:vimtex_compiler_progname = 'nvr'
endif
```

Note, this does work as expected for me. Let us first focus on making it work without deoplete, i.e. with omnicompletion. So, reduce your config by removing everything not vimtex related. Now, does it work if you use `<c-x><c-o>` inside `\documentclass{...`?

**Comment by krisfans** [comment]
It seems that there is also a error whitout `deoplete` . When I  use `<c-x><c-o>` inside `\documentclass{...`  I get this 

![Snipaste_2020-05-20_17-28-08](https://user-images.githubusercontent.com/57793534/82431570-614ca500-9ac1-11ea-8f12-296c987e8678.png)

This is `minimal.vim`

```vim
"------plug------------------------"
call plug#begin('$HOME/.vim/plugged') 
 Plug 'lervag/vimtex'
 Plug 'honza/vim-snippets'
call plug#end()
let g:plugged#enable_at_startup = 1 

"---------------vimtex---------------"
let g:tex_flavor  = 'latex'    

```

**Comment by lervag** [comment]
Strange. Can you check the file `d:\Software\texlive\texmf-local\ls-R` if it exists and if so, which permissions are set on it?

**Comment by lervag** [comment]
I've made a minor update that I think should prevent the error. Does things work better after an update now?

**Comment by krisfans** [comment]
I update my `vimtex` plugin but this error still exist . 
In addition I need get administrator privileges to operate this file .  But I donot know the usage of the file `d:\Software\texlive\texmf-local\ls-R` .

**Comment by lervag** [comment]
Ok, then the problem is that we are trying to read a file that you do not have access to. I don't really know much windows stuff, but I would expect your LaTeX installation to be readable by vimtex.

Can you try to change the permissions of the file so that you get access to it?

**Comment by krisfans** [comment]
After getting access to this file , `vimtex`  works well with `deoplete` . Thanks a lot . 

![Snipaste_2020-05-20_19-49-36](https://user-images.githubusercontent.com/57793534/82442873-10de4300-9ad3-11ea-96f1-cb8a8f8aa343.png)

**Comment by lervag** [comment]
Great, and no problem. :)
