### ISSUE TITLE
Suppress auto folding behavior.

### ISSUE THREAD

**Issue by neizod** [lervag/vimtex#170]
It's very annoying and interfere my setting in `.vimrc`:

    set nofoldenable

I know this is a nice feature, but could you please at lease not make it auto run?

**Comment by lervag** [comment]
I am not sure what you mean. You can disable folding with `let g:vimtex_fold_enabled = 0`.

**Comment by neizod** [comment]
I mean that. I just surprise it's default is true. Also before your answer I don't know how to set it.

**Comment by lervag** [comment]
I suggest you read the documentation. Things like this are clearly described there.
