### ISSUE TITLE
Add syntax support for autoref

### ISSUE THREAD

**Issue by zacmar** [lervag/vimtex#1700]
**Is your feature request related to a problem? Please describe it.**
When using `\autoref` from `\usepackage{hyperref}`, and using `:set spell`, spellchecking is enabled within the `autoref` command. This is unwanted behavior in my opinion, since labels are not expected to be written in proper english.

**Describe the solution you'd like**
I would like `\autoref` to behave just like what is already implemented for `\cref` and `\varioref`.

**Describe alternatives you've considered**
I tried to add `syn match texAutoref "\\autoref{[^}]\{-}}"hs=s+8,he=e-1 containedin=texStatement contains=@NoSpell` to `$runtimepath/syntax/tex.vim`. This has the unwanted side effect of not highlighting the curly brackets anymore. Since proper functionality is already implemented for `\cref` and `\varioref` I assume that the framework for this is already set up in `vimtex` and doing the same for `\autoref` can be done in much better ways.

**Additional context**
Nothing, really.

**Comment by lervag** [comment]
Thanks, this seems reasonable. Could you provide an example or two of how you would use `\autoref` (I've not used this macro before myself).

**Comment by zacmar** [comment]
Sure:
```tex
\documentclass{article}
\usepackage{hyperref}

\begin{document}
\begin{equation}
	e = mc^2%
	\label{einstein}
\end{equation}
Here, I'm referring to \autoref{einstein}.
\end{document}
```
Usage is equivalent to, e.g. `cref`. The `einstein` inside of the curly braces is considered to be improperly spelled, and it is not assigned to the same highlight group as if `vref`, `cref` (and maybe others) were used.

**Comment by lervag** [comment]
`\autoref` was actually already implemented, except that it was part of cleveref. I've fixed it now so that it is properly activated with hyperref. Thanks for raising the issue!
