### ISSUE TITLE
Table of contents do not include sections from recursively included subfiles

### ISSUE THREAD

**Issue by thor** [lervag/vimtex#1702]
_(A short background introduction: the support for `subfiles` and synctex is the combinational killer feature for me personally with vimtex. A big thank-you to you and all the other contributors.)_

Looking at #155 and [maxfl's comment](https://github.com/lervag/vimtex/issues/155#issuecomment-98073693) I've used subfiles with an absolute path for each subfile pointing to `main.tex` based on the working directory.

Now I'm trying to add another level of subfiles, specifically a structure like this:

```
─ $(pwd)
  ├── main.tex
  └── parts/
      ├── chapter.tex
      └── sections/
          ├── first.tex
          └── second.tex
```

While compilation proceeds without any issues whether I compile `main.tex` or any one of `chapter.tex`, `first.tex` or `second.tex` by switching the current compilation target with `<localleader>ls`, I can see that the vimtex table of contents does not include the sections from `parts/sections/*.tex`.I presume this is because it tries to read the contents of `$(pwd)/sections/first.tex`, as opposed to `$(pwd)/parts/sections/first.tex`.

### Mucking about

*If* I change the inclusion in `chapter.tex` to `parts/sections/*.tex` it will include the files in the list of detected source files. However, compilation will fail.

The closest I've come is by changing the parameter to the `subfiles` document class for `chapter.tex`, but this seems like inviting trouble as it suddenly inconsistent with absolute or relative paths.

```latex
\documentclass[../main.tex]{subfiles}
% ...
```
Upside:
* If I open `parts/chapter.tex` from `$(pwd)` the table of contents include the sections.

Downside:
* If I open `main.tex` or any of the `sections/*.tex` the table of contents _do not_ include the sections.

_Another_ way to kind of muck about that sort of works around it, if you _only_ compile via vimtex: change `$(pwd)` to `parts/`, then open `chapter.tex`. vimtex correctly finds the `main.tex` above, despite `$(pwd)` being incorrect, and compilation works from within nvim. I note that the path for the `parts/sections/*.tex` files end up with a full path in the table of contents.

**Expected Behaviour**

The table of contents includes all the sections included by subfiles that are included by subfiles (that are included by ...).

Perhaps while using absolute paths for `\documentclass[abs/path/file.tex]{subfiles}` the files included by the `subfiles` package should be relative to the current file the `subfiles` are used in?

I've noted that `subfiles` post-v1.3 use the `import` package, which handles relative includes/inputs, and as such it *seems* reasonable on first look that reading the contents of the argument to `\subfile{}` should take into account that it should be relative to the current file, not the working directory, whereas the `\documentclass[]{subfiles}` should do the opposite?

### Reproduction

<details>
  <summary>Expand <code>vimrc</code></summary>

```vim
set nocompatible
let &runtimepath  = '~/.config/nvim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.config/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

</details>
<details>
  <summary>Expand <code>*.tex</code> files</summary>

```latex
% main.tex
\documentclass[a4paper]{report}
\usepackage{subfiles}

\begin{document}
\tableofcontents

\subfile{parts/chapter.tex}

\end{document}
```
```latex
% parts/chapter.tex
\documentclass[main.tex]{subfiles}
\begin{document}
\chapter{Chapter with subsections}
Here we introduce the bug as it currently is experienced by a user.
\subfile{sections/first.tex}
\subfile{sections/second.tex}
\end{document}
```
```latex
% parts/sections/first.tex
\documentclass[main.tex]{subfiles}
\begin{document}
\section{The first section}
Titling notwithstanding, could this issue be a case of PEBCAC?
\end{document}
```
```latex
% parts/sections/second.tex
\documentclass[main.tex]{subfiles}
\begin{document}
\section{The second section}
You don't always think it be like this, but it do.
\end{document}
```

</details>

### Output from VimtexInfo
<details>
  <summary>Expand <code>VimtexInfo</code></summary>

```
System info
  OS: Arch Linux
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /tmp/thor/nvimFyxNe8/0

vimtex project: main
  base: main.tex
  root: /home/thor/dev/thor/testing-stuff
  tex: /home/thor/dev/thor/testing-stuff/main.tex
  out: /home/thor/dev/thor/testing-stuff/main.pdf
  log: /home/thor/dev/thor/testing-stuff/main.log
  aux: /home/thor/dev/thor/testing-stuff/main.aux
  fls: /home/thor/dev/thor/testing-stuff/main.fls
  main parser: current file verified
  source files:
    main.tex
    parts/chapter.tex
  compiler: latexmk
    backend: nvim
    output: /tmp/thor/nvimFyxNe8/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    pid: 1138989
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"/usr/bin/nvr --servername /tmp/thor/nvimFyxNe8/0 --remote +\%{line} \%{input}\" \%S"' -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'main.tex'
  viewer: Zathura
    xwin id: 119537667
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: report
  packages:
    import
    subfiles
```
</details>

**Comment by lervag** [comment]
> _(A short background introduction: the support for `subfiles` and synctex is the combinational killer feature for me personally with vimtex. A big thank-you to you and all the other contributors.)_

Thanks! :)

> While compilation proceeds without any issues whether I compile `main.tex` or any one of `chapter.tex`, `first.tex` or `second.tex` by switching the current compilation target with `<localleader>ls`, I can see that the vimtex table of contents does not include the sections from `parts/sections/*.tex`.I presume this is because it tries to read the contents of `$(pwd)/sections/first.tex`, as opposed to `$(pwd)/parts/sections/first.tex`.

Ok, so, in short: Table of contents is not correct when we're in "subfile mode" in this case of nested subfile usage?

> **Expected Behaviour**
> 
> The table of contents includes all the sections included by subfiles that are included by subfiles (that are included by ...).

It may be I'm not reading this right, but let me phrase this in my way and you can decide: The expected behaviour is this:

1. In "full project mode", the ToC should contain the entire project structure.

2. In "subfile mode", the ToC should contain the entries from the current part of the project.

> Perhaps while using absolute paths for `\documentclass[abs/path/file.tex]{subfiles}` the files included by the `subfiles` package should be relative to the current file the `subfiles` are used in?
> 
> I've noted that `subfiles` post-v1.3 use the `import` package, which handles relative includes/inputs, and as such it _seems_ reasonable on first look that reading the contents of the argument to `\subfile{}` should take into account that it should be relative to the current file, not the working directory, whereas the `\documentclass[]{subfiles}` should do the opposite?

You are raising an interesting issue, in that we are looking at "nested" subfiles. Still, all the subfiles should refer to the same `main.tex` file, and I think this part is "correct". The question is how to interpret the root when we parse the `\subfile` commands.

I'll look into your supplied example later, I just wanted to throw out my first thoughts. :)

**Comment by thor** [comment]
> > While compilation proceeds without any issues whether I compile `main.tex` or any one of `chapter.tex`, `first.tex` or `second.tex` by switching the current compilation target with `<localleader>ls`, I can see that the vimtex table of contents does not include the sections from `parts/sections/*.tex`.I presume this is because it tries to read the contents of `$(pwd)/sections/first.tex`, as opposed to `$(pwd)/parts/sections/first.tex`.
> 
> Ok, so, in short: Table of contents is not correct when we're in "subfile mode" in this case of nested subfile usage?

In short, yup. In "full project mode" the table of contents does not include the sections from `parts/sections/*.tex` included with `\subfile{sections/first}` and `\subfile{sections/second}` in `parts/chapter.tex`.

Here's me opening up `parts/chapter.tex` (or `parts/sections/*.tex`) with the main parser being subfiles and the base being `main.tex` (as reported by `VimtexInfo`), with the table of contents open.
![image](https://user-images.githubusercontent.com/234489/82729482-38622500-9cf8-11ea-98f8-a72f29b75c11.png)


> > **Expected Behaviour**
> > The table of contents includes all the sections included by subfiles that are included by subfiles (that are included by ...).
> 
> It may be I'm not reading this right, but let me phrase this in my way and you can decide: The expected behaviour is this:
> 
>    1. In "full project mode", the ToC should contain the entire project structure.
> 
>    2. In "subfile mode", the ToC should contain the entries from the current part of the project.
I'm sorry; I struggled with phrasing that properly, but I think you've hit the nail on the head. As far as I can tell that expected behaviour _is_ indeed how it otherwise works, except for this specific issue where the sections are not included due to the relative path used by the `\subfile{}` inclusions.


> > Perhaps while using absolute paths for `\documentclass[abs/path/file.tex]{subfiles}` the files included by the `subfiles` package should be relative to the current file the `subfiles` are used in?
> > I've noted that `subfiles` post-v1.3 use the `import` package, which handles relative includes/inputs, and as such it _seems_ reasonable on first look that reading the contents of the argument to `\subfile{}` should take into account that it should be relative to the current file, not the working directory, whereas the `\documentclass[]{subfiles}` should do the opposite?
> 
> You are raising an interesting issue, in that we are looking at "nested" subfiles. Still, all the subfiles should refer to the same `main.tex` file, and I think this part is "correct". The question is how to interpret the root when we parse the `\subfile` commands.

Indeed, it seems to work very well both in terms of consistency and ease of use that all the subfiles use the same fixed and unique name of `main.tex` (or other project equivalent, such as `thesis.tex`).

> I'll look into your supplied example later, I just wanted to throw out my first thoughts. :)

Please let me know if I can assist in any way. :+1:

**Comment by lervag** [comment]
I think you're detecting two separate issues. I've pushed a PR for this with wip fixes. It would be great if you could test if this covers all of your issues.

**Comment by lervag** [comment]
I've now improved the code in the PR and think it should now be ready for merge. I'll wait for feedback, and I'll also make sure to add tests before I merge.

I'll take the liberty of closing the issue; let's continue discussions in #1703.
