### ISSUE TITLE
Installation instruction should specify the latexmk dependency

### ISSUE THREAD

**Issue by paulrougieux** [lervag/vimtex#1707]
The installation instructions on the readme should specify the latexmk dependency. 
Other wise we run into this error at vim startup: `vimtex: latexmk is not executable`, reported as [issue 1420](https://github.com/lervag/vimtex/issues/1420) 
For example on my system this is easily fixed by installing it:
```
sudo apt install latexmk
```
I could suggest this as a modification to the readme but I guess it needs to be made more generic for all operating systems.

**Comment by lervag** [comment]
No, I disagree. The installation instructions explain how to install vimtex. In the Quick Start guide just after, it is __strongly__ encouraged to read the main docs and the user is referred to `:help vimtex`. These docs are large, so I can understand pretty much noone reads all of it. But the third section in the introduction is titled "Requirements", and the second entry here is the compiler backends such as `latexmk`. Thus, I think the docs are clear. Note that `latexmk` is one of four possible backends (I'll admit I believe 98% of users rely on latexmk, though).

In any case, IMHO, the docs are clear on this point and no action is needed.

**Comment by paulrougieux** [comment]
Thank you, I usually generated my latex with other editors such as Lyx and Texstudio. latexmk was not needed then (maybe it's embedded or another process is used). Moving to vim to edit a new article, now I realise how important latexmk is.

**Comment by lervag** [comment]
> Thank you, I usually generated my latex with other editors such as Lyx and Texstudio. latexmk was not needed then (maybe it's embedded or another process is used).

No, I think most editors also implement a custom compile engine. This was also the strategy of the old LaTeX-Suite for Vim.

> Moving to vim to edit a new article, now I realise how important latexmk is.

Exactly. I think one can get a relatively nice experience with only bare Vim (no plugins) and latexmk in a terminal. Of course, vimtex exists because I think this can be tightened and improved way beyond that, but still. :)
