### ISSUE TITLE
Item text objects not working as expected

### ISSUE THREAD

**Issue by MahbubAlam231** [lervag/vimtex#1708]
**Issue**
Vim's `p` command pastes text after the cursor or below the `cursorline`. When I deleted an item (in enumerate environment) by `vimtex`'s `am` (i.e., `dam`) and proceeded to paste it somewhere else using `p`, it pasted above `cursorline`. It also introduced a one character space before `\item` and deletes one character space before the next `\item` in the environment. This seems to be an unexpected behaviour.

**minimal.vim**
```vim
set nocompatible
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'lervag/vimtex'

call vundle#end()

filetype plugin indent on
syntax enable
```

**minimal.tex**
```tex
\documentclass{amsart}
\usepackage{amsmath}
\usepackage{enumerate}
\usepackage{enumitem}

\begin{document}
    \begin{enumerate}
      \item First one. [[CURSOR HERE, NORMAL MODE]]
      \item Second one.
    \end{enumerate}
\end{document}
```

**Commands/Input**
`dam`. After this command cursor moves to the line  "\item Second one." in normal mode. I then press the second command `p`.

**Observed Behaviour**
Enumerate environment changes to --
```tex
    \begin{enumerate}
       \item First one.
     \item Second one.
    \end{enumerate}
```

`p` pastes the deleted item before `cursorline`. Also, note the introduced space before the first `\item` and deleted space beforet the second `\item`.

**Expected Behaviour**
Expected enumerate environment --
```tex
    \begin{enumerate}
      \item Second one.
      \item First one.
    \end{enumerate}
```

**Output from VimtexInfo**
```
System info
  OS: Linux Mint 18.3 Sylvia
  Vim version: VIM 8.2 (1-676)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

vimtex project: item
  base: item.tex
  root: /home/mahbub/Desktop/Untitled Folder
  tex: /home/mahbub/Desktop/Untitled Folder/item.tex
  out: /home/mahbub/Desktop/Untitled Folder/item.pdf
  log: /home/mahbub/Desktop/Untitled Folder/item.log
  aux: /home/mahbub/Desktop/Untitled Folder/item.aux
  fls: /home/mahbub/Desktop/Untitled Folder/item.fls
  main parser: current file verified
  compiler: latexmk
    backend: jobs
    output: /tmp/vOl9Qb3/2
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: amsart
  packages:
    amsmath
    enumerate
    enumitem
```

**Comment by lervag** [comment]
Interesting. The problem is due to the lack of `am` being linewise. I think it does make sense to make it linewise.

**Comment by lervag** [comment]
I think the issue should be solved now.

**Comment by MahbubAlam231** [comment]
> Interesting. The problem is due to the lack of `am` being linewise. I think it does make sense to make it linewise.

Does it make sense to make `ae` linewise as well? It's probably not that important, but just asking.
