### ISSUE TITLE
Every `\lv` run new instance of Zathura

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#171]
When I use mapping `\lv` for the first time it just run Zathura without any highlighting lines.
When I press `\lv` second time it run another instance of Zathura with green highlighting (synctex based) lines.
Any following press of '\lv' run new instance of Zathura.

It looks like unwanted behavior.

![2015-05-20-163338_1920x1200_scrot](https://cloud.githubusercontent.com/assets/146893/7726911/135f2786-ff0e-11e4-81ac-fd71b53aa0fc.png)

P.S. My configuration:

~/.vim/vundles.vim

    Bundle 'lervag/vimtex'

~/.vimrc

    let g:tex_flavor = "latex"
    set iskeyword+=:
    set grepprg=grep\ -nH\ $*
    let g:vimtex_view_method = 'zathura'

~/.latexmkrc

    $pdflatex = 'pdflatex -synctex=1 %O %S';

**Comment by petRUShka** [comment]
May be following will help.

I leave here my working Latex Suite configuration with support of Zathura with forward and backward search. And also with force of compile on save.

    "latex
    let g:Tex_CompileRule_pdf = 'latexmk -pdflatex="pdflatex -file-line-error -synctex=1" -pdf -f $*'
    let g:Tex_DefaultTargetFormat = 'pdf'

    " Get the correct servername, which should be the filename of the tex file,
    " without the extension.
    " Using the filename, without the extension, not in uppercase though, but
    " that's okay for a servername, it automatically get uppercased
    let theuniqueserv = expand("%:r")"

    " Working!!!, when we run vim appropriately
    let g:Tex_ViewRuleComplete_pdf = 'zathura -x "vim --servername '.theuniqueserv.' --remote +\%{line} \%{input}" $*.pdf 2>/dev/null &'

    au BufWritePost *.tex silent! call Tex_WriteAndSearch()

    " Forward search
    " syntax for zathura: zathura --synctex-forward 193:1:paper.tex paper.pdf
    function! SyncTexForward()
      let execstr = 'silent! !zathura --synctex-forward '.line('.').':1:"'.expand('%').'" "'.expand("%:p:r").'".pdf'
      execute execstr
    endfunction

    function! Tex_WriteAndSearch()
      silent! call Tex_RunLaTeX()
      silent! call SyncTexForward()
    endfunction

**Comment by lervag** [comment]
Strange. I do not have the same problem with Zathura. Could you please test again with a minimal working example, e.g.
```tex
\documentclass{minimal}
\begin{document}
Hello world.
\end{document}
```
and a minimal vimrc file, e.g.
```vimL
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
filetype plugin indent on
syntax enable
set iskeyword+=:
let g:tex_flavor = "latex"
let g:vimtex_view_method = 'zathura'
```
Note that the path `'~/.vim/bundle/vimtex,'` must be correct. If you save the minimal vimrc to a file `minivimrc` and the minimal working example to `mwe.tex`, then you can test with `vim -u minivimrc mwe.tex` (or gvim/mvim if you prefer).

**Comment by nasenatmer** [comment]
@petRUShka: What do you get if you press `\li`? Does it show the correct pid of zathura?

Also, I usually do `\ll` first before pressing `\lv`. Have you tried this, too?

**Comment by lervag** [comment]
Thanks @nasenatmer, good questions.

@petRUShka Could you please show the output of `\li` after you have opened zathura with `\lv`?

**Comment by petRUShka** [comment]
Thats what returned in my vimrc

    b:vimtex
      id : 0
      fold_parts
        ['^\s*\(\\\|% Fake\)subsection:\?\>', 3]
        ['^\s*\(\\\|% Fake\)section:\?\>', 2]
        ['^\s*\(\\\|% Fake\)chapter:\?\>', 1]
    Error detected while processing function vimtex#info:
    line   18:
    E716: Key not present in Dictionary: words()
    E15: Invalid expression: data.words()

    g:vimtex#data[0] : know-results
      pid : 0
      root : '/home/petrushka/Dropbox/НИИСИ/articles/gleb/s-unity'
      aux : '/home/petrushka/Dropbox/НИИСИ/articles/gleb/s-unity/know-results.aux'
      log : '/home/petrushka/Dropbox/НИИСИ/articles/gleb/s-unity/know-results.log'
      out : '/home/petrushka/Dropbox/НИИСИ/articles/gleb/s-unity/know-results.pdf'
      tex : '/home/petrushka/Dropbox/НИИСИ/articles/gleb/s-unity/know-results.tex'
      base : 'know-results.tex'
      viewer
        xwin_id : 0
        cmd_start : 'zathura  -x "/usr/bin/gvim --servername VIM --remote +\%{line} \%{input}" ''/home/petrushka/Dropbox/НИИСИ/articles/gleb/s-unity/know-results.pdf'''
        cmd_forward_search : 'zathura --synctex-forward 690:30:''/home/petrushka/Dropbox/НИИСИ/articles/gleb/s-unity/know-results.tex'' ''/home/petrushka/Dropbox/НИИСИ/articles/gleb/s-unity/know-results.pdf'''
        class : 'Zathura'
        init : function('397')
        view : function('398')
        start : function('399')
        forward_search : function('400')
        latexmk_callback : function('401')
        latexmk_append_argument : function('402')
        focus_vim : function('<SNR>135_focus_vim')
        xwin_exists : function('<SNR>135_xwin_exists')
        xwin_get_id : function('<SNR>135_xwin_get_id')

Then I created minimal `.tex` file and `minivimrc` and run gvim:

    $ gvim -u ~/minivimrc minimal.tex
    vimtex viewer Zathura requires xdotool!

GVIM pointed that `xdotool` should be installed. Without installed `xdotool` there was absolutely same behaviour.

But after installation of `xdotool` everything became working properly even in my config. Thanks.

I think dependency on `xdotool` should be pointed more explicitly.

**Comment by lervag** [comment]
Ah, yes, it was one of my suspicions. As you see, there is already a warning for this. It should have been displayed in your own config as well, but you have probably something in your config that disrupts the warning message.

I see I've missed pointing out that zathura also requires `xdotool` in the documentation. I'm adding it now.

**Comment by petRUShka** [comment]
Great!

**Comment by lervag** [comment]
Also, I've fixed the silly issue that lead to an error on `:VimtexInfo` (`\li`).

**Comment by gkapfham** [comment]
Although I know that this issue is now close, I thought that it might be appropriate for me to make a quick observation. I have tried to use vimtex and Zathura together in a way that it very similar to what was mentioned in the very first post on this issue. However, I have never seen Zathura create the green highlight line when I try to use it correctly? While I acknowledge that this may be due to the concerns that I have described in issue #177, I would love to learn more about how to obtain the green highlighting.

**Comment by nasenatmer** [comment]
Basically, `zathura` should start if you press `\ll` for the first time and compilation has finished successively. 

Every time after this, if you want to get synctex highlighting (i.e. the green and yellow lines) you have to press `\lv` which works fine here.

Are you sure you're using a vim version that has `+clientserver` compiled? Check via `vim --version | grep clientserver`. Are you starting a vim server by using `vim --servername <$anyname> <file>`? See `:h vimtex-requirements` for that.

**Comment by gkapfham** [comment]
Hello again @nasenatmer! Thanks again for your feedback. I have followed your suggestions exactly and found that I cannot get Zathura forward searching in the way that you have described. In addition, please note that I did this for a minimal working example that has all of the files for a multi-file project in a single directory. Finally, I was running most of these tests in gvim. However, I can also confirm exactly the same behavior that I reported in the issue when I use vim with server running (i.e., using `vim --servername VIMTEXTEST minimal.tex`). Here is the output of running `:version`:

```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled May 31 2015 17:09:42)
Included patches: 1-729
Compiled by gkapfham@kallistos
Huge version with GTK2-GNOME GUI.  Features included (+) or not (-):
+acl             +conceal         +farsi           +libcall         +mouse_netterm   +profile         +syntax          +visualextra
+arabic          +cryptv          +file_in_path    +linebreak       +mouse_sgr       +python          +tag_binary      +viminfo
+autocmd         +cscope          +find_in_path    +lispindent      -mouse_sysmouse  -python3         +tag_old_static  +vreplace
+balloon_eval    +cursorbind      +float           +listcmds        +mouse_urxvt     +quickfix        -tag_any_white   +wildignore
+browse          +cursorshape     +folding         +localmap        +mouse_xterm     +reltime         -tcl             +wildmenu
++builtin_terms  +dialog_con_gui  -footer          +lua             +multi_byte      +rightleft       +terminfo        +windows
+byte_offset     +diff            +fork()          +menu            +multi_lang      +ruby            +termresponse    +writebackup
+cindent         +digraphs        +gettext         +mksession       -mzscheme        +scrollbind      +textobjects     +X11
+clientserver    +dnd             -hangul_input    +modify_fname    +netbeans_intg   +signs           +title           -xfontset
+clipboard       -ebcdic          +iconv           +mouse           +path_extra      +smartindent     +toolbar         +xim
+cmdline_compl   +emacs_tags      +insert_expand   +mouseshape      +perl            -sniff           +user_commands   +xsmp_interact
+cmdline_hist    +eval            +jumplist        +mouse_dec       +persistent_undo +startuptime     +vertsplit       +xterm_clipboard
+cmdline_info    +ex_extra        +keymap          -mouse_gpm       +postscript      +statusline      +virtualedit     -xterm_save
+comments        +extra_search    +langmap         -mouse_jsbterm   +printer         -sun_workshop    +visual          +xpm
```

**Comment by nasenatmer** [comment]
Alright, so we can exclude `(g)vim` as being the reason for this error. It was just the first thought I had when I read your post.

**Comment by lervag** [comment]
@gkapfham I think I'll comment more on this in the issue you opened. In any case, I suspect you might either be lacking `xdotools` on your system, or you have not set up `latexmk` to compile with `synctex`.
