### ISSUE TITLE
Problems to configure COC

### ISSUE THREAD

**Issue by Marco-Israel** [lervag/vimtex#1716]
Hello

congratulation, very good plugin which is really easy to setup in basics. It does a lot of magic for me :)

Also you documentation is pretty good!

But I have some trouble to configure coc + vimtex:

You write in your documentation:

```
Additionally, you can configure code completion for TeX by setting these
options in |coc-nvim|'s configuration file `coc-settings.json` >

  coc.source.vimtex.disableSyntaxes // disabled syntax names
  coc.source.vimtex.enable          // set to false to disable this source
  coc.source.vimtex.priority        // priority of source, default 99
  coc.source.vimtex.shortcut        // shortcut used in menu of completion item
```

So after simple copy paste this to my "~/.vim/coc-settings.json" this does not work and throws me the error when opening vim:

```
[coc.nvim] settings file parse error, run ':CocList diagnostics'
```

Can you pleace provide a working example in your documentation? Best by setting the defaut vaules and give alternatice values in comments behind?

Also its not realy clear to me what this setting do. Are they needed or not? What is the default

```
  coc.source.vimtex.disableSyntaxes // disabled syntax names
```

What are syntax names?

```
  coc.source.vimtex.enable          // set to false to disable this source
```

What are "sources" in the mean of vimtex. What is "this" source?

```
  coc.source.vimtex.priority        // priority of source, default 99
```

What effect does changing this pro have to me / vim / vimtex / else? Is 99 the highest or the lowest prio?

```
  coc.source.vimtex.shortcut        // shortcut used in menu of completion item
```

What is the default shorcut? Is there some or does I need to define one to let vimtex work with coc?

Btw.: which autocompleation do you prefer?

My best to you all! :)

**Comment by lervag** [comment]
> So after simple copy paste this to my "~/.vim/coc-settings.json" this does not work and throws me the error when opening vim:

Ah, sorry. I can see the docs are somewhat confusing here. But first, please
note that a lot of your following questions are related to coc.nvim, not
vimtex.

So, first: vimtex should work with coc.nvim _without_ any options. Simply do `:CocInstall coc-vimtex`, and things should work. The configuration options are for changing the default options.

> ```
> [coc.nvim] settings file parse error, run ':CocList diagnostics'
> ```

Yes, the options I've listed is not the syntax you use to specify the options. You should learn to use and configure coc.nvim first.

> Can you pleace provide a working example in your documentation? Best by setting the defaut vaules and give alternatice values in comments behind?

I'll update the docs to make it less confusing.

> ```
>   coc.source.vimtex.disableSyntaxes // disabled syntax names
> ```
>
> What are syntax names?

I have to admit I don't really know what this is. Feel free to ask at the coc-vimtex repo and link here.

> ```
>   coc.source.vimtex.enable          // set to false to disable this source
> ```
> 
> What are "sources" in the mean of vimtex. What is "this" source?

sources are the term for completion sources in coc.nvim.

> ```
>   coc.source.vimtex.priority        // priority of source, default 99
> ```
> 
> What effect does changing this pro have to me / vim / vimtex / else? Is 99 the highest or the lowest prio?

I think 99 is typically very high priority. I don't think there is a highest/lowest. The default should work fine, don't need to change it.

> ```
>   coc.source.vimtex.shortcut        // shortcut used in menu of completion item
> ```
> 
> What is the default shorcut? Is there some or does I need to define one to let vimtex work with coc?

This is just a label used in the completion menu to distinguish vimtex completion candidates from other sources. Default should work fine.

> Btw.: which autocompleation do you prefer?

I use coc.nvim without any of these options changed.
