### ISSUE TITLE
Error processing function vimtex#syntax#init

### ISSUE THREAD

**Issue by DaitiDay** [lervag/vimtex#1722]
When I open a .tex file with vimtex installed (using vim-plug) I get the following error:
```
Error detected while processing function vimtex#syntax#init[6]..vimtex#syntax#load[22]..vimtex#syntax#load#packag
es:
line   10:
E884: Function name cannot contain a colon: vimtex#syntax#p#{l:pkg}#load()
Error detected while processing function vimtex#syntax#init:
line    6:
E171: Missing :endif
Error detected while processing function <SNR>11_SynSet:
line   24:
E170: Missing :endfor
Error detected while processing function dist#ft#FTtex:
line   47:
E171: Missing :endif
```
My init.vim
```
call plug#begin(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/nvim/plugged"'))
Plug 'lervag/vimtex'
call plug#end()

" Basic settings
let mapleader =" "
set nocompatible
set clipboard+=unnamedplus
filetype plugin indent on
syntax on
set encoding=UTF-8
set number relativenumber
setlocal spell
set spelllang=en_us
set noshowmode
set hls is
set hidden
set backspace=indent,eol,start
```

Other plugin functionality seems to work just fine (for what I tested).

Can't find a solution looking at the documentation or searching on internet.
Thanks for the help

**Comment by lervag** [comment]
Which version of Vim are you on?

**Comment by DaitiDay** [comment]
I'm on the latest version of NeoVim (v0.4.3)

**Comment by lervag** [comment]
Can you provide a minimal example where this error occurs?

**Comment by DaitiDay** [comment]
I'm re-writing in LaTex my university notes and this error pops up when I open the main file or any other subfile. It seems to be packages-related because on a "fresh" tex file, just like
```
\documentclass{article}                                                                                      

\begin{document}

\section{Test}

Test \textit{prova} test

\begin{equation} \label{eq:1}
        a+b=c
\end{equation}

test

\end{document}
```
I do not get any error, but it looks like the syntax highlighting is not propertly working, i.e. I get the same highlighting with or without the plugin installed (there is no colouring such as in the gif on the README of this plugin).

**Comment by lervag** [comment]
> I'm re-writing in LaTex my university notes and this error pops up when I open the main file or any other subfile. It seems to be packages-related because on a "fresh" tex file, just like ...

Yes, that's the reason I ask for the minimal example. I expect the error might be related to something in your TeX file that I don't handle properly.

> I do not get any error, but it looks like the syntax highlighting is not propertly working, i.e. I get the same highlighting with or without the plugin installed (there is no colouring such as in the gif on the README of this plugin).

Vimtex does not provide a syntax plugin directly, instead it adds improved syntax rules on top of the plugin that ships with Vim/neovim. See `:help vimtex-syntax`.

So, again: please provide a minimal example that I can use to reproduce your issue.

**Comment by DaitiDay** [comment]
As I'm trying to reproduce the error on a "minimal" tex file I realize that just deleting part of the text of the document allows me to open the file without any error.
More in depth, in the main file, I've left all the packages untouched and just deleted every line of the "real" document except the call to the first subfile. In the subfile I've done the same thing.
For this reaason it is kinda hard to provide a "minimal" file that you can use to reproduce the error. The only way I can think of is if I send you the "complete" main and a subfile. Any suggestion?

**Comment by lervag** [comment]
Feel free to send me your complete files, if that's OK for you. Then I'll see if I can reproduce your issue on my end.

**Comment by DaitiDay** [comment]
I've sent you an email with the two files. Feel free to give them a look.

**Comment by lervag** [comment]
Thanks! Let's take the discussion related to your full example on email, and the possible discussion related to bugs/vimtex changes here.

**Comment by DaitiDay** [comment]
I'm fine with that. Thanks for the help

**Comment by lervag** [comment]
Ok, by email it seems the issue is gone after cleaning aux files. Do you see the problem again if you recompile?

**Comment by DaitiDay** [comment]
Sorry for the late replay. Now the error is gone and everything is working fine

**Comment by lervag** [comment]
Glad to hear it.
