### ISSUE TITLE
Forward search not working when using multi-directory projects

### ISSUE THREAD

**Issue by Mattieu314** [lervag/vimtex#1724]
**Issue**
I am not sure if this is an issue, or a non-feature.

When compiling multi-file projects with the subfiles package, forward search doesn't work when compiling the main file. To use forward search within the document currently being edited, one must use ```:VimtexToggleMain ```

**Directory structure**
-- main -- main.tex
-- sub -- sub.tex

**minimal.vim**
  ```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

filetype plugin indent on
syntax enable

let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_progname = 'nvr'
let g:tex_flavor = "latex"
  ```

**main.tex**
  ```tex
\documentclass{article}
\usepackage{subfiles}

\begin{document}
\section{Section 1}
Hello world 1.

\section{Section 2}
Hello world 2.

\section{Section 4}
\subfile{sub}
\end{document}

  ```
**sub.tex**
```tex
\documentclass[test.tex]{subfiles}
\begin{document}
Hello world 4
\end{document}
```

**Commands/Input**
Compile sub.tex with ```\ll``` then use ```\lv```. 

**Observed Behaviour**
Just goes to beginning of the document.

**Expected Behaviour**
Expect current position of cursor to be highlighted.

**Comment by lervag** [comment]
Strange. I've copied your example, as follows:

```
.
├── sub.tex
├── test.tex
└── test.vim
```

The files are as you suggest. I do `nvim -u test.vim sub.tex`, then do `\ll` to compile, and finally, I go to "Hello world 4" and do `\lv`. Result: "Hello world 4" is highlighted in the PDF.

Note, in your post it seems you have a couple of minor errors:

- You write `main.tex`, I expect you mean `test.tex`.
- You include both `let &rtp = ...` and `call plug#begin`. You should not need the vim-plug lines here, thus, the following should suffice:

    ```vim
    set nocompatible
  let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
  let &rtp .= ',~/.vim/bundle/vimtex/after'
  filetype plugin indent on
  syntax enable

  let g:vimtex_view_method = 'zathura'
  let g:tex_flavor = "latex"
  ```

Let me know if I've misunderstood anything...

**Comment by Mattieu314** [comment]
Apologies for the mistake, that should be test.tex. This is my first time writing an issue on GitHub so I am learning.

I may not have presented the directory structure clearly enough:
```
.
+-- tex
|    +-- test
|        +-- test.tex
|    +-- sub
|        +-- sub.tex
```
The subfile is in a different directory to the main (test.tex) file.

**Comment by lervag** [comment]
Ah, but this won't work and should not compile correctly. If you use this structure, then the files should be:

```tex
% main.tex
\documentclass{article}
\usepackage{subfiles}

\begin{document}
\section{Section 1}
Hello world 1.

\section{Section 2}
Hello world 2.

\section{Section 4}
\subfile{../sub/sub}
\end{document}


% sub.tex
\documentclass[../test/test.tex]{subfiles}
\begin{document}
Hello world 4
\end{document}
```

This is documented both in the documentation of the `subfiles` package and partly in the vimtex docs in `:help vimtex-subfiles`.

With my version, I can reproduce your problem. However, I think this problem is with synctex itself, not with vimtex. If I move the `sub` folder inside the `test` folder and update the paths in the examples, then things work as expected. Is this an option for you?

**Comment by Mattieu314** [comment]
Ah yes. By putting the ```sub``` folder into the ```test``` folder it works as expected. This is an option for me. Thank you.

**Comment by lervag** [comment]
Great, happy to hear it!
