### ISSUE TITLE
Vimtex lag, located around delimiter functions

### ISSUE THREAD

**Issue by ykonstant1** [lervag/vimtex#1727]
**Observed Behaviour**
When typing on a tex file, the cursor sometimes lags both in insert and normal mode.  Long lines make the problem worse, but even very short lines have a very noticeable lag.  

Here is the output of a profiler on the minimal tex with minimal vimrc provided in the issue template:
```
 512   6.674296   0.084943  180()
  580   5.414321   5.116813  <SNR>54_get_delim()
  512   5.313593   0.029766  vimtex#delim#get_current()
  512   1.007821   0.022215  vimtex#util#in_comment()
  519   0.987129             vimtex#util#in_syntax()
  910   0.925844             <SNR>14_Highlight_Matching_Pair()
   90   0.280184   0.019977  vimtex#delim#get_matching()
  227   0.185040   0.032400  <SNR>36_callback_continuous_output()
   22   0.170769   0.006600  <SNR>51_get_cmd()
   17   0.167791   0.001536  vimtex#cmd#get_at()
   17   0.162449   0.002621  vimtex#cmd#get_current()
   68   0.160280   0.158782  <SNR>54_get_matching_delim()
   64   0.160175   0.008925  <SNR>51_get_cmd_part()
    5   0.152640   0.015401  vimtex#compiler#callback()
  112   0.118299   0.068509  <SNR>54_parser_delim()
   64   0.107628   0.002010  vimtex#delim#get_next()
  951   0.095063   0.025245  vimtex#pos#set_cursor()
   17   0.093242   0.003957  <SNR>54_parser_env()
    5   0.084476   0.009843  vimtex#qf#open()
 1013   0.073876   0.072747  <SNR>66_parse_args()
```
The lag is not very noticeable with such a small text, but with a bigger text and my normal vimrc, I get something like this:
``` 
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
 1298  15.206509   0.146818  196()
 1783  13.881655  12.099743  <SNR>95_get_delim()
 1298  12.553013   0.052531  vimtex#delim#get_current()
 1779   4.997794   4.997791  UltiSnips#TrackChange()
    2   2.487325   0.000018  operator#sandwich#add()
    2   2.487307   0.000223  <SNR>130_do()
    2   2.485821   0.000108  231()
    2   2.479128   0.000273  235()
    2   2.405539   2.323754  243()
 1403   1.936653             vimtex#util#in_syntax()
 1298   1.833539   0.033853  vimtex#util#in_comment()
...
```
I do use several plugins in parallel with vimtex, mainly UltiSnips, fastfold and sandwich, but as I understand it the delimiter functions from vimtex cause the bulk of the lag.  Also, in my vimrc I included 
```
let g:vimtex_motion_matchparen = 0
let g:vimtex_indent_enabled = 0
let g:vimtex_matchparen_enable = 0
```
but that made no difference to the statistics at all!
 
Remark: I have had this problem for very long, and have tried to bisect my vimrc countless times, always breaking down due to the tediousness and bizarre combinations increasing / decreasing lag.  Today I think I found a source of lag even with a minimal set up.

**Expected Behaviour**
Smooth typing.

**Output from VimtexInfo**
System info
  OS: Linux 5.7.5-arch1-1
  Vim version: VIM 8.2 (1-814)
  Has clientserver: true
  Servername: VIM

vimtex project: minimal
  base: minimal.tex
  root: /home/admin
  tex: /home/admin/minimal.tex
  out: /home/admin/minimal.pdf
  log: /home/admin/minimal.log
  aux: /home/admin/minimal.aux
  fls: /home/admin/minimal.fls
  main parser: current file verified
  compiler: latexmk
    backend: jobs
    output: /tmp/vNj4fGX/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -lualatex
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: minimal

**Comment by lervag** [comment]
I think this is closely related to #1721, but perhaps not quite, since you are claiming you see the lag even with `g:vimtex_matchparen_enabled = 0`.

Could you provide a full minimal example and steps to reproduce the lag?

**Comment by ykonstant1** [comment]
Will do; in the meantime I have a question: with the option ```g:vimtex_matchparen_enabled = 0``` in my vimrc, my profiler shows the following: 

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
  509   4.669468   0.094836  180()
  604   4.028635   3.535482  <SNR>54_get_delim()
  508   3.753160   0.035821  vimtex#delim#get_current()
  527   0.704465             vimtex#util#in_syntax()
  509   0.693463   0.027383  vimtex#util#in_comment()
  974   0.539432             <SNR>14_Highlight_Matching_Pair()
   31   0.301368   0.011832  <SNR>51_get_cmd()
   91   0.282913   0.015877  <SNR>51_get_cmd_part()
   28   0.259788   0.003482  vimtex#cmd#get_at()
   28   0.250139   0.003461  vimtex#cmd#get_current()
   28   0.233806   0.006171  <SNR>54_parser_env()
   44   0.233534   0.099596  GetTeXIndent()
   91   0.179877   0.003203  vimtex#delim#get_next()
   92   0.144410   0.022839  vimtex#delim#get_matching()
    3   0.138600   0.002441  vimtex#delim#close()
    5   0.135137   0.000515  vimtex#delim#get_prev()
 1062   0.123574   0.033903  vimtex#pos#set_cursor()
  109   0.119729   0.065575  <SNR>54_parser_delim()
  154   0.108199   0.031501  <SNR>36_callback_continuous_output()
   26   0.107388             <SNR>79_CheckPairedIsLastCharacter()
```
I recognize some functions that still match parentheses, is this normal behavior?

**Comment by ykonstant1** [comment]
OK, I am not sure if this is what you need, if you need more info let me know:

**Step 1**: minimal vimrc
```
  set nocompatible
  let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/bundle/vimtex/after'
  filetype plugin indent on
let g:vimtex_motion_matchparen = 0
let g:vimtex_indent_enabled = 0
let g:vimtex_matchparen_enable = 0
let g:fastfold_minlines = 0
  syntax enable
```
**Step 2**: run Vim ```vim --servername VIM -u .vimrc.minimal /home/data/share/research/projects/quant_mixing/test.tex```
(test.tex is the tex file for a 31 page paper; I would like not to make it public in its current form)

**Step 3**: start profiling via

```
:profile start profile-big.log
:profile func *
:profile file *
```

**Step 4**: Type random text in the middle of sentences in the tex file, observe intermittent lag; when holding a key down, the character occasionally stops/jerks. The problem seems worse within big equations, but this may be just my impression. 

[Note, this lag is lower with the minimal example than with my full vimrc, which includes UltiSnips, sandwich, has enabled folds and relative numbers.  But even in that case, the functions dominating the profile log run time are delimiter functions such as the ones listed below.]

**Step 5**: pause the profiler and exit, check log:
profile_big.log
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
 1221  14.865172   0.143799  180()
 1159  12.643111  12.307564  <SNR>54_get_delim()
  999  12.515864   0.052385  vimtex#delim#get_current()
 1309   1.654573             vimtex#util#in_syntax()
 1221   1.641549   0.042431  vimtex#util#in_comment()
 2222   0.888137             <SNR>14_Highlight_Matching_Pair()
  136   0.585419   0.045516  vimtex#delim#get_matching()
   21   0.460167   0.106187  GetTeXIndent()
   65   0.381022   0.380461  <SNR>54_get_matching_delim()
   70   0.340797             <SNR>79_CheckPairedIsLastCharacter()
   34   0.206614   0.001309  vimtex#cmd#get_at()
   34   0.202235   0.002271  vimtex#cmd#get_current()
   37   0.198561   0.004828  <SNR>51_get_cmd()
  109   0.190785   0.006857  <SNR>51_get_cmd_part()
  245   0.183715   0.044972  <SNR>36_callback_continuous_output()
    2   0.138743   0.000499  vimtex#compiler#callback()
 1825   0.132195   0.034721  vimtex#pos#set_cursor()
    2   0.104903   0.020471  vimtex#qf#open()
 2066   0.101956   0.100745  <SNR>66_parse_args()
    1   0.101629   0.001970  vimtex#delim#close()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
 1159  12.643111  12.307564  <SNR>54_get_delim()
 1309              1.654573  vimtex#util#in_syntax()
 2222              0.888137  <SNR>14_Highlight_Matching_Pair()
   65   0.381022   0.380461  <SNR>54_get_matching_delim()
   70              0.340797  <SNR>79_CheckPairedIsLastCharacter()
 1221  14.865172   0.143799  180()
   21   0.460167   0.106187  GetTeXIndent()
 2066   0.101956   0.100745  <SNR>66_parse_args()
 1221              0.084503  179()
    2   0.065853   0.059714  62()
  999  12.515864   0.052385  vimtex#delim#get_current()
  136   0.585419   0.045516  vimtex#delim#get_matching()
  245   0.183715   0.044972  <SNR>36_callback_continuous_output()
 1221   1.641549   0.042431  vimtex#util#in_comment()
 1825   0.132195   0.034721  vimtex#pos#set_cursor()
   34   0.033101   0.032734  <SNR>54_get_matching_env()
  139   0.062888   0.032598  <SNR>54_parser_delim()
 1493              0.022121  vimtex#pos#get_cursor()
    2   0.104903   0.020471  vimtex#qf#open()
  140              0.016843  <SNR>54_parser_delim_get_corr()
```

**Comment by ykonstant1** [comment]
As an extra bit of information (perhaps this can show that vimtex is not the source of the lag?), here is the result of profiling the same file as above, doing the same kind of actions (just typing text), with the full vimrc; here the lag is extreme.

profile-full-2.log
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
  793   6.721074             UltiSnips#CursorMoved()
 1728   6.386420   6.386418  UltiSnips#TrackChange()
  947   5.750005   0.089143  196()
  947   4.887497   0.036637  vimtex#delim#get_current()
  956   4.855281   4.733953  <SNR>95_get_delim()
    6   1.661252   0.059228  <SNR>28_WinDo()
 5548   1.600393   1.000188  vimtex#fold#level()
  997   1.329551   0.040159  airline#extensions#wordcount#get()
  894   1.282121   0.027250  <SNR>52_update_wordcount()
  903   1.243895             <SNR>52_get_wordcount()
    2   1.142887   0.000201  <SNR>28_UpdateBuf()
 1116   0.777619   0.384999  vimtex#fold#text()
  997   0.618205   0.183235  airline#check_mode()
  947   0.558460   0.024075  vimtex#util#in_comment()
    7   0.537436   0.536917  UltiSnips#ExpandSnippet()
  960   0.536856             vimtex#util#in_syntax()
    1   0.518781   0.000215  <SNR>28_UpdateWin()
 1839   0.474009             <SNR>34_Highlight_Matching_Pair()
   32   0.430493   0.076461  airline#highlighter#highlight()
  532   0.367958   0.177732  113()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
  793              6.721074  UltiSnips#CursorMoved()
 1728   6.386420   6.386418  UltiSnips#TrackChange()
  956   4.855281   4.733953  <SNR>95_get_delim()
  903              1.243895  <SNR>52_get_wordcount()
 5548   1.600393   1.000188  vimtex#fold#level()
    7   0.537436   0.536917  UltiSnips#ExpandSnippet()
  960              0.536856  vimtex#util#in_syntax()
 1839              0.474009  <SNR>34_Highlight_Matching_Pair()
 1116   0.777619   0.384999  vimtex#fold#text()
  997   0.618205   0.183235  airline#check_mode()
  532   0.367958   0.177732  113()
   26   0.157317   0.157116  <SNR>95_get_matching_delim()
 1638              0.120244  132()
 6979              0.112258  airline#util#append()
  532              0.099222  115()
    2   0.097612   0.097250  UltiSnips#JumpForwards()
  997   0.098709   0.090650  airline#extensions#vimtex#get_scope()
  947   5.750005   0.089143  196()
 1593   0.091579   0.089068  112()
 1638              0.088730  141()
```

**Comment by lervag** [comment]
> Step 2: run Vim vim --servername VIM -u .vimrc.minimal /home/data/share/research/projects/quant_mixing/test.tex

The entire point of the example is for _me_ to be able to reproduce _your_ problem. I quite understand that you won't share your papers under work with me, but you need to share _something_ that reproduces your problem.

> Step 4: Type random text in the middle of sentences in the tex file, observe intermittent lag; when holding a key down, the character occasionally stops/jerks. The problem seems worse within big equations, but this may be just my impression.

This is _not_ specific ("random text", "holding a key down"). Please be _specific_, say exactly what I should do to observe your problem.

So, please, again: Provide a minimal example (now I'm thinking LaTeX file) and instructions for how to reproduce the lag you are seeing. Please ignore everything that is not vimtex, because I can't help with that. So, use the minimal vimrc file and keep Ultisnips++ out of it.

----

That said:

```vim
" This option does not exist, so you can safely remove it
let g:vimtex_motion_matchparen = 0

" This option should not really be expensive, so no need to disable it (unless
" you don't want the indentation feature)
let g:vimtex_indent_enabled = 0

" This option is explained in the docs: it disables the highlighting of
" matching parantheses/delimiters. Keeping it off should make things faster,
" both in normal and insert mode. Personally, I keep it enabled, and things are
" not so slow for me.
let g:vimtex_matchparen_enable = 0

" This option is irrelevant to vimtex
let g:fastfold_minlines = 0
```

I'll also admit that I know that the functions for parsing the delimiters can get somewhat slow. For me, it is not a big problem, but as was shown in e.g. issue #1721, it can be noticable when one uses the matchparen feature and also has very long lines.
