### ISSUE TITLE
block when :VimTexCompile

### ISSUE THREAD

**Issue by zdmgmail** [lervag/vimtex#1731]
```
System info
  OS: Linux 5.7.6-arch1-1
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /tmp/nvimMKPB07/0

vimtex project: a
  base: a.tex
  root: /home/zdm/Code/tex/f
  tex: /home/zdm/Code/tex/f/a.tex
  out: /home/zdm/Code/tex/f/a.pdf
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    backend: nvim
    output: /tmp/nvimMKPB07/3
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -xelatex
  viewer: Zathura
    xwin id: 0
  qf: LaTeX logfile
    config: 
      overfull: 0
      packages: 
        default: 0
      underfull: 0
      default: 1
  document class: article
  packages:
    ctex
    forest
    geometry
    graphicx

```

 when I  use  `VimtexCompile` , 

After  may be one seconds , nvim will block  until compile end,(cursor blink and can't move),  the compile time not long

 Is this a normal thing?  or it should never block when compile?
 
also have this problem:  hangs starting continuous compile #1467   

but I don't use wayland

**Comment by lervag** [comment]
This is not normal, but it is way too little detail for me to help solve the issue.

Please provide the details asked in the issue template: minimal vimrc, minimal latex example, clear and concise steps to reproduce.

**Comment by zdmgmail** [comment]
> This is not normal, but it is way too little detail for me to help solve the issue.
> 
> Please provide the details asked in the issue template: minimal vimrc, minimal latex example, clear and concise steps to reproduce.

init.vim
```
call plug#begin('~/.config/nvim/plugged')

Plug 'SirVer/ultisnips'
Plug 'lervag/vimtex'

call  plug#end()


autocmd Filetype tex nnoremap S  :call Latex()<cr>




autocmd BufRead *.tex  :set ft=tex
autocmd User VimtexEventQuit :VimtexClean

func! Latex()
	exec "w"
	silent! exec "VimtexStop"
	silent! exec "VimtexCompile"
endfunc


let g:vimtex_quickfix_open_on_warning=0
let g:latex_view_general_viewer = 'zathura'
let g:vimtex_view_method='zathura'
let g:vimtex_compiler_method='latexmk'
let g:tex_flavor='latex'
let g:vimtex_quickfix_mode=0


" Disable overfull/underfull \hbox and all package warnings
let g:vimtex_quickfix_latexlog = {
			\ 'overfull' : 0,
			\ 'underfull' : 0,
			\ 'packages' : {
			\   'default' : 0,
			\ },
			\}


let g:vimtex_compiler_latexmk_engines = {
			\ '_'                : '-xelatex',
			\ 'xelatex'          : '-xelatex',
			\ 'lualatex'         : '-lualatex',
			\ 'pdflatex'         : '-pdf',
			\ 'dvipdfex'         : '-pdfdvi',
			\ 'context (xetex)'  : '-pdf -pdflatex=''texexec --xtx''',
			\ 'context (luatex)' : '-pdf -pdflatex=context',
			\ 'context (pdftex)' : '-pdf -pdflatex=texexec',
			\}


```

min.tex

```
\documentclass{article}

\title{}
\author{}
% \date{$4}

\begin{document}

\maketitle

helloworld

\end{document}
```

in normal mode , use S to compile

**Comment by lervag** [comment]
Ok, first, let's clean up your config. It is _way_ bloated. Your config should be reduced to this:

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'lervag/vimtex'
call  plug#end()

" This is not really necessary, but may be OK to keep
autocmd User VimtexEventQuit :VimtexClean

let g:tex_flavor = 'latex'
let g:vimtex_compiler_latexmk_engines = {'_': '-xelatex'}
let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_quickfix_mode = 0
let g:vimtex_quickfix_latexlog = {
  \ 'overfull' : 0,
  \ 'underfull' : 0,
  \ 'packages' : {
    \   'default' : 0,
    \ },
  \}
```

Here I've removed some useless options, as well as your custom `S` mapping. Instead, use the default `\ll` mapping to start compilation, and use `\ll` again to stop it if you want. When it is started, it will automatically compile when you write your document.

Can you now confirm that, with the updated minimal vimrc file, you can still reproduce your problem? If so, can you again describe in detail how to reproduce it?

**Comment by zdmgmail** [comment]
> Ok, first, let's clean up your config. It is _way_ bloated. Your config should be reduced to this:
> 
> ```viml
> call plug#begin('~/.config/nvim/plugged')
> Plug 'lervag/vimtex'
> call  plug#end()
> 
> " This is not really necessary, but may be OK to keep
> autocmd User VimtexEventQuit :VimtexClean
> 
> let g:tex_flavor = 'latex'
> let g:vimtex_compiler_latexmk_engines = {'_': '-xelatex'}
> let g:vimtex_view_method = 'zathura'
> let g:vimtex_quickfix_open_on_warning = 0
> let g:vimtex_quickfix_mode = 0
> let g:vimtex_quickfix_latexlog = {
>   \ 'overfull' : 0,
>   \ 'underfull' : 0,
>   \ 'packages' : {
>     \   'default' : 0,
>     \ },
>   \}
> ```
> 
> Here I've removed some useless options, as well as your custom `S` mapping. Instead, use the default `\ll` mapping to start compilation, and use `\ll` again to stop it if you want. When it is started, it will automatically compile when you write your document.
> 
> Can you now confirm that, with the updated minimal vimrc file, you can still reproduce your problem? If so, can you again describe in detail how to reproduce it?

I tried the config and if  I use `\ll` to stop first , use \ll again , the block time seems shorter but still exist, 
I just compile then use j/k move cursor ,  when compiling, the cursor where blink and stop move . 
if compile complete , the cursor will suddenly move long distance like it never stop

Double confirm: It should never block or block a little time?

If never block , seems I want auto compile when textchange...

```
autocmd TextChanged,TextChangedI *.tex :call Latex()
func! Latex()
	exec "w"
	silent! exec "VimtexStop"
	silent! exec "VimtexCompile"
endfunc
```

**Comment by zdmgmail** [comment]
> Ok, first, let's clean up your config. It is _way_ bloated. Your config should be reduced to this:
> 
> ```viml
> call plug#begin('~/.config/nvim/plugged')
> Plug 'lervag/vimtex'
> call  plug#end()
> 
> " This is not really necessary, but may be OK to keep
> autocmd User VimtexEventQuit :VimtexClean
> 
> let g:tex_flavor = 'latex'
> let g:vimtex_compiler_latexmk_engines = {'_': '-xelatex'}
> let g:vimtex_view_method = 'zathura'
> let g:vimtex_quickfix_open_on_warning = 0
> let g:vimtex_quickfix_mode = 0
> let g:vimtex_quickfix_latexlog = {
>   \ 'overfull' : 0,
>   \ 'underfull' : 0,
>   \ 'packages' : {
>     \   'default' : 0,
>     \ },
>   \}
> ```
> 
> Here I've removed some useless options, as well as your custom `S` mapping. Instead, use the default `\ll` mapping to start compilation, and use `\ll` again to stop it if you want. When it is started, it will automatically compile when you write your document.
> 
> Can you now confirm that, with the updated minimal vimrc file, you can still reproduce your problem? If so, can you again describe in detail how to reproduce it?

also tried vim-latex-live-preview not block or blink cursor, I don't know the difference...

**Comment by lervag** [comment]
> I tried the config and if I use `\ll` to stop first , use \ll again , the block time seems shorter but still exist,
> I just compile then use j/k move cursor , when compiling, the cursor where blink and stop move .
> if compile complete , the cursor will suddenly move long distance like it never stop
> 
> Double confirm: It should never block or block a little time?

No, I don't have these experiences at all.

> If never block , seems I want auto compile when textchange...
>
> ```
> autocmd TextChanged,TextChangedI *.tex :call Latex()
> func! Latex()
> 	exec "w"
> 	silent! exec "VimtexStop"
> 	silent! exec "VimtexCompile"
> endfunc
> ```

NO! You **don't** need to do `VimtexStop` and `VimtexCompile`. Vimtex uses latexmk to _automatically_ compile your document when you save it. This is all very well documented (IMHO). If you insist that you want to perform a single, manual compilation, then look at `:help vimtex_compiler_latexmk` and the `continuous` key (set it to 0), or use the `:VimtexCompileSS` command instead of the normal `:VimtexCompile` command.

But, again: I don't see any blocking behaviour. Perhaps you could make a small video of your screen to show what you mean? Are you running the minimal vimrc correctly, i.e. with `nvim -u minimal.vim minimal.tex` where `minimal.vim` is similar to the vimrc content pasted before?

**Comment by zdmgmail** [comment]
> > I tried the config and if I use `\ll` to stop first , use \ll again , the block time seems shorter but still exist,
> > I just compile then use j/k move cursor , when compiling, the cursor where blink and stop move .
> > if compile complete , the cursor will suddenly move long distance like it never stop
> > Double confirm: It should never block or block a little time?
> 
> No, I don't have these experiences at all.
> 
> > If never block , seems I want auto compile when textchange...
> > ```
> > autocmd TextChanged,TextChangedI *.tex :call Latex()
> > func! Latex()
> > 	exec "w"
> > 	silent! exec "VimtexStop"
> > 	silent! exec "VimtexCompile"
> > endfunc
> > ```
> 
> NO! You **don't** need to do `VimtexStop` and `VimtexCompile`. Vimtex uses latexmk to _automatically_ compile your document when you save it. This is all very well documented (IMHO). If you insist that you want to perform a single, manual compilation, then look at `:help vimtex_compiler_latexmk` and the `continuous` key (set it to 0), or use the `:VimtexCompileSS` command instead of the normal `:VimtexCompile` command.
> 
> But, again: I don't see any blocking behaviour. Perhaps you could make a small video of your screen to show what you mean? Are you running the minimal vimrc correctly, i.e. with `nvim -u minimal.vim minimal.tex` where `minimal.vim` is similar to the vimrc content pasted before?


I tried no config in vimtex then not block ,  tried each line ,

finally  find if I  comment `let g:vimtex_view_method = 'zathura'`  then not block

but if I don't have this line, still defualt open pdf in zathura , just not block and blink cursor 



>  You don't need to do `VimtexStop` and `VimtexCompile`. Vimtex uses latexmk to _automatically_ compile your document when you save it.

what's this mean ...  it never auto compile when I save .tex file so I run VimtexCompile manully...

**Comment by lervag** [comment]
What is in your `.latexmkrc` file?

**Comment by zdmgmail** [comment]
> What is in your `.latexmkrc` file?

don't have .latexkrc ,   just use these in vim

```
let g:vimtex_compiler_method='latexmk'


let g:vimtex_compiler_latexmk_engines = {
			\ '_'                : '-xelatex',
			\ 'xelatex'          : '-xelatex',
			\ 'lualatex'         : '-lualatex',
			\ 'pdflatex'         : '-pdf',
			\ 'dvipdfex'         : '-pdfdvi',
			\ 'context (xetex)'  : '-pdf -pdflatex=''texexec --xtx''',
			\ 'context (luatex)' : '-pdf -pdflatex=context',
			\ 'context (pdftex)' : '-pdf -pdflatex=texexec',
			\}

```

**Comment by lervag** [comment]
You can simplify those two lines to simply:

```vim
let g:vimtex_compiler_latexmk_engines = {'_': '-xelatex'}
```

If I understand correctly, pdf files on your system are opened with Zathura by default (e.g. `xdg-open file.pdf`  opens the PDF in zathura).

Further, you say that the delays you are seeing comes from `let g:vimtex_view_method = 'zathura'`. Do you have `xdotool` installed and available? And `pgrep`?

**Comment by zdmgmail** [comment]
> You can simplify those two lines to simply:
> 
> ```viml
> let g:vimtex_compiler_latexmk_engines = {'_': '-xelatex'}
> ```
> 
> If I understand correctly, pdf files on your system are opened with Zathura by default (e.g. `xdg-open file.pdf` opens the PDF in zathura).
> 
> Further, you say that the delays you are seeing comes from `let g:vimtex_view_method = 'zathura'`. Do you have `xdotool` installed and available? And `pgrep`?

I change to this line 

```
let g:vimtex_compiler_latexmk_engines = {'_': '-xelatex'}
```

and have these but still problem

```
xdotool --version                                                               
xdotool version 3.20160805.1 
----------------------------------------------------------------------------------------------------------
 pgrep --version                                                                    
pgrep from procps-ng 3.3.16 
----------------------------------------------------------------------------------------------------------
```

**Comment by lervag** [comment]
Well, OK. I've tried to help, but I'm out of ideas. I hope you'll figure it out, and sorry for not being able to help more!

**Comment by fcomoreira1** [comment]
Is there any update on this kind of issue? I've seen multiple unresolved, but closed issues regarding a block on the window with just a cursor blinking for a few seconds when I run \ll. 

I noticed that when I disabled latexmk callbacks this does not happen, so it can be related to those, but I am not sure.

**Comment by lervag** [comment]
What do you mean? What kind of update do you want? If you read this thread, you will see that I never was able to reproduce the problem.

Feel free to open a new issue, but please, if you do, describe the problem in detail and provide a fully minimal example.
