### ISSUE TITLE
environment highlighting knowledge sharing for fortran ft

### ISSUE THREAD

**Issue by rudrab** [lervag/vimtex#1733]
Dear lervag,
One of the standout feature of vimtex is environment highlighting, i.e.
```
\begin{section}
  ...
\end{section}
```
is highlighted when cursor is either in `begin` or `end`.

I am trying to do the same for `fortran` filetype, which has syntax like
```
do i = 1,1n
  ...
end do
```

One file that I need is `autoload/vimtex/matchparen.vim`, i guess. What other files I should look at? May you kindly help?

**Comment by lervag** [comment]
I think you may be interested in the plugin [vim-matchup](https://github.com/andymass/vim-matchup), which should work also for Fortran files, according to the README file.

Note, vim-matchup works well with Vimtex and should give an even better matching experience. See `:help vimtex-nf-enhanced-matchparen`.
