### ISSUE TITLE
Changing vimtex engine to lualatex

### ISSUE THREAD

**Issue by zorgick** [lervag/vimtex#1734]
Hi again) I've got a problem with changing vimtex engine from pdflatex to lualatex on mac.

**Issue**
The background of the problem: I need to use plantuml inside latex, but it works only with lualatex compiler.
Running directly `lualatex --shell-escape index.tex` makes a pdf file with a uml diagram, 

**but** compiling `index.tex` file using `<localleader>ll` makes a pdf file without a uml diagram, leaving only error on its place
```pdf
Restricted shell escape. PlantUML cannot be called. 

Start pdflatex/lualatex with -shell-escape. @startuml Alice -> Bob: Hello Alice <- Bob: Hi! @enduml
```

**minimal.vim**

  ```vim
  set nocompatible
  filetype plugin indent on
  syntax enable
Plug 'lervag/vimtex'
let g:vimtex_compiler_progname = 'nvr'
let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'skim'
let g:vimtex_quickfix_mode = 0
let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : 'dist',
    \}

  ```

**minimal.tex**

  ```tex
% !TeX program = lualatex

  \documentclass{minimal}
\usepackage{plantuml}

  \begin{document}
  \begin{plantuml}
  @startuml
  Alice -> Bob: Hello
  Alice <- Bob: Hi!
  @enduml
\end{plantuml}

  \end{document}
  ```

**.latexmkrc**
```
$pdflatex = 'lualatex --shell-escape --interaction=nonstopmode --synctex=1 %O %S;';

```

**Comment by lervag** [comment]
> Hi again) I've got a problem with changing vimtex engine from pdflatex to lualatex on mac.

It seems to me that the problem is related to the `--shell-escape` option, and that you've partly solved it. `--shell-escape` is not added automatically by vimtex, and I have not found a very convenient way of doing it. However, you can specify it in your `.latexmkrc` file similar to how you've tried. But: if you use the `lualatex` option for latexmk, then setting `$pdflatex` does nothing. Instead, you can use something like what I use to set some common options for _all_ compilers:

```perl
set_tex_cmds('-synctex=1 -interaction=nonstopmode --shell-escape %O %S');
```

This would add the options `-synctex=1`, `-interaction=nonstopmode`, and `--shell-escape` to both `latex`, `pdflatex`, `lualatex`, and so on. Let me know if this solves your problem.

**Comment by zorgick** [comment]
I've cleared latexmkrc file and added this line, but it didn't solve the problem. The error is still the same. 

I'm currently searching for a way to set a `makeprg` directive for vimtex like for a c++ compiler `set makeprg=g++\ -std=c++11\ -o\ bin_index\ *.cpp`. Is there any option to do it?

**Comment by lervag** [comment]
> I've cleared latexmkrc file and added this line, but it didn't solve the problem. The error is still the same.

Strange. If you do `:VimtexCompileOutput` (or `\lo`) you can see the latexmk output, it might be helpful.

> I'm currently searching for a way to set a `makeprg` directive for vimtex like for a c++ compiler `set makeprg=g++\ -std=c++11\ -o\ bin_index\ *.cpp`. Is there any option to do it?

Not sure why, and how is this related? The compiler backend for latex compilation in vimtex does not rely on the makeprg feature. However, there are a couple of grammar and syntax checkers that are available through the compiler feature, see `:help vimtex-grammar` and `:help vimtex-lint` for more details.

**Comment by zorgick** [comment]
I've opted to xetex, in the end. I've found out that your plugin does everything right (through `\lo` output), except, it wasn't able to find `index-plantuml.latex` file. I did everything necessary as described in [this package](https://ctan.org/pkg/plantuml), but the result was the same, vimtex couldn't compile my tex file. So I swapped plantuml with tikz-uml package, as it is more robust, [in my opinion](https://texample.net/tikz/examples/tag/diagrams/), it is recommended by overleaf online text editor, it has a great amount of documented use cases, as well. And it works great with xetex engine (needs LC variables defined in bash_profile).

```sh
#   Fix: perl: warning: Setting locale failed.
#   ------------------------------------------------------------
export LC_CTYPE=en_US.UTF-8
export LC_TELEPHONE=en_US.UTF-8
export LC_ALL=en_US.UTF-8

```

I've created public gist describing, [how one would install](https://gist.github.com/zorgick/4f37f9b06340981af453ee9da65d774c) tikz package for latex.

**Comment by lervag** [comment]
Great, thanks for the update and info.

**Comment by PeterlitsZo** [comment]
Does the `vimtex` call `latexmk` instead of `pdflatex`? So if I want to change its behavior, I should edit the `.latexmkrc` in the home dir right?

**Comment by lervag** [comment]
@PeterlitsZo It is better to open a new issue with new questions, than to add your question to an old thread. To answer your question: Yes. You can change the behaviour with `.latexmkrc` (both in `$HOME` and in a project directory). But VimTeX starts latexmk with some options as defined in the `g:vimtex_compiler_latexmk` variable, and the `g:vimtex_compiler_latexmk_engines` variable can be used to specify the desired TeX program. You really should open and read the docs; at least the introduction `:help vimtex`.

**Comment by PeterlitsZo** [comment]
> @PeterlitsZo It is better to open a new issue with new questions, than to add your question to an old thread. To answer your question: Yes. You can change the behaviour with `.latexmkrc` (both in `$HOME` and in a project directory). But VimTeX starts latexmk with some options as defined in the `g:vimtex_compiler_latexmk` variable, and the `g:vimtex_compiler_latexmk_engines` variable can be used to specify the desired TeX program. You really should open and read the docs; at least the introduction `:help vimtex`.

Thanks for your kindly answer very much! I think I get it!
