### ISSUE TITLE
vimtex doesn't work with biber, bibtex, biblatex or cite when using .bib file

### ISSUE THREAD

**Issue by dsevero** [lervag/vimtex#1736]
Vimtex doesn't work with biber, bibtex, biblatex, nor cite when using .bib file

I keep getting errors such as 

```
cv.tex|65 warning| LaTeX Warning: Citation 'severo2019ward2icu' on page 2 undefined on input line 65.
cv.tex|66 warning| LaTeX Warning: Empty bibliography on input line 66.
cv.tex|| LaTeX Warning: There were undefined references.
cv.tex|| Package biblatex Warning: Please (re)run Biber on the file: cv
```

on this [project](https://github.com/dsevero/dsevero.com/tree/master/tex/cv-ta), more specifically, [this tex](https://github.com/dsevero/dsevero.com/blob/master/tex/cv-ta/cv.tex) and [bib](https://github.com/dsevero/dsevero.com/blob/master/tex/cv-ta/cv.bib) files.

my `init.vim` is

```
call plug#begin()
Plug 'vim-pandoc/vim-pandoc'
Plug 'lervag/vimtex'
Plug 'Konfekt/FastFold'
Plug 'matze/vim-tex-fold'
call plug#end()

tnoremap <Esc> <C-\><C-n>
tnoremap <C-A> pwd\|xclip -selection clipboard<CR><C-\><C-n>:cd <C-r>+<CR>i
vnoremap <C-c> "+y
set number

let g:python_host_prog = '/home/dsevero/miniconda3/envs/nvim-py2718/bin/python'
let g:python3_host_prog = '/home/dsevero/miniconda3/envs/nvim-py373/bin/python'
set shell=/usr/bin/zsh

let g:tex_flavor  = 'latex'
let g:tex_conceal = ''
let g:vimtex_fold_manual = 1
let g:vimtex_latexmk_continuous = 1
let g:vimtex_compiler_progname = 'nvr'

terminal

```

**Comment by clason** [comment]
Yes, it does (at least for me). Can you add a minimal TeX file, too?

**Comment by lervag** [comment]
> Vimtex doesn't work with biber, bibtex, biblatex, nor cite when using .bib file

It does work.

> I keep getting errors such as ...

I suspect you get the same errors if you compile your document from the terminal.

> on this [project](https://github.com/dsevero/dsevero.com/tree/master/tex/cv-ta), more specifically, [this tex](https://github.com/dsevero/dsevero.com/blob/master/tex/cv-ta/cv.tex) and [bib](https://github.com/dsevero/dsevero.com/blob/master/tex/cv-ta/cv.bib) files.

I've cloned your files and I have no problem compiling them.

> my `init.vim` is ...

Some comments:

```vim
" I think this plugin will interfere with vimtex folding. Perhaps you want to
" disable vimtex folding with "let g:vimtex_fold_enable = 0"?
Plug 'matze/vim-tex-fold'

" This option does not exist. Check vimtex docs for more info.
let g:vimtex_latexmk_continuous = 1

" This is not necessary, as it is set automatically
let g:vimtex_compiler_progname = 'nvr'
```

----

As suggested by @clason: Please provide minimal latex files and a minmal vimrc file necessary to reproduce your problem. Note also that the `.latexmkrc` file may be relevant.

**Comment by dsevero** [comment]
Sorry, I made a mistake. It looks like [`\nofiles` in `res.cls`](https://github.com/dsevero/dsevero.com/blob/master/tex/cv-ta/res.cls#L203) was blocking the creation of `cv.aux` (which, as far as I know, is needed by bibtex and biber backends).

@clason @lervag I'm not sure why, but when I ran `latexmk` directly in my terminal the `cv.aux` file was created.

I'm sorry to bother you!

**Comment by lervag** [comment]
No problem, happy to hear it works now! :)

Note, when something doesn't work, I often tend to first clean all aux files, then recompile. This may sometimes be necessary for the compilation to work correctly.

**Comment by hejops** [comment]
Would it be possible to call the pdf/bib/pdf chain from vimtex only for documents with a bibliography (and just normally compile otherwise)? I tried setting the `let g:Tex_MultipleCompileFormats = 'pdf,bib,pdf'` option, but that didn't seem to be able to call biber. I don't have any options set in vimtex.

As a workaround, I currently have `:! pdflatex % ; biber %:r ; pdflatex %` set to a keybind, but I presume that would be a waste of compilation time for documents without bibliography.
