### ISSUE TITLE
Error whe I'm trying to use <TAB> in `cse`

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#174]
When I try to change enviroment via `cse` shortcut and to use <TAB> to complete environment name I catch an error:

E117: Unknown function: input_complete

**Comment by lervag** [comment]
I don't quite understand. Could you provide a full example?

**Comment by nasenatmer** [comment]
I get the same error. But is there completion expected?

**Comment by lervag** [comment]
I've fixed it. In the current version one can not define the completion candidates. I could implement an option for this, but I think the current list of candidates should suffice for almost all cases.

**Comment by petRUShka** [comment]
I'm sorry for delay in answer! It seems that option is a good idea, because everybody use his own set of environments.

**Comment by lervag** [comment]
I'm pushing an update pretty soon that adds a new option `g:vimtex_change_complete_envs`. That should complete this issue, I think.
