### ISSUE TITLE
Erroneous indenting with nested environments

### ISSUE THREAD

**Issue by smartspot2** [lervag/vimtex#1740]
**Issue**
With nested environments (specifically here, a bmatrix within an align environment), outer environment end tags are erroneously indented.

**minimal.vim**

  ```vim
  set nocompatible
  let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
  let &runtimepath .= ',~/.vim/bundle/vimtex/after'
  filetype plugin indent on
  syntax enable
  ```

**minimal.tex**

```tex
\documentclass{minimal}
\usepackage{amsmath}
\begin{document}
\begin{align}
    x &= \begin{bmatrix} 1 \\ 3 \end{bmatrix}
\end{align}
\end{document}
```

**Commands/Input**
Running `gg=G` to format the entire document.

**Observed Behaviour**
The `\end{document}` line becomes indented one level:
```tex
\documentclass{minimal}
\usepackage{amsmath}
\begin{document}
\begin{align}
    x &= \begin{bmatrix} 1 \\ 3 \end{bmatrix}
\end{align}
    \end{document}
```

**Expected Behaviour**
When I autoindent the document, I expect to have no changes, but instead, the `\end{document}` line is erroneously indented. Surrounding the `align` environment with more environments causes all other end tags afterward to also get erroneously indented.

I suspect that it has something to do with the indenter being confused with the extra `\\` within the `bmatrix` environment.

**Comment by lervag** [comment]
Thanks! I think this is fixed now.
