### ISSUE TITLE
vimtex_quickfix_latexlog is ignored when using pplatex

### ISSUE THREAD

**Issue by hejops** [lervag/vimtex#1741]
**Issue**
I am using neingeist's [fork](https://github.com/neingeist/pplatex)  of pplatex. I don't know if it happens for the main branch.

**minimal.vim**

```
let g:vimtex_quickfix_method = 'pplatex'
let g:vimtex_quickfix_latexlog = { 'overfull' : 0, 'underfull' : 0 }
```

**Observed Behaviour**
On its own, `let g:vimtex_quickfix_latexlog = { 'overfull' : 0, 'underfull' : 0 }` works as expected; the relevant log messages from the default log parser are not shown.

**Expected Behaviour**
```let g:vimtex_quickfix_method = 'pplatex'``` causes the abovementioned setting to be ignored, and the log messages are shown.

**Output from VimtexInfo**

```System info
  OS: Manjaro Linux
  Vim version: VIM 8.2 (1-1151)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

vimtex project: assignment
  base: assignment.tex
  root: <path>
  tex: <path>/assignment.tex
  out: <path>/assignment.pdf
  log: <path>/assignment.log
  aux: <path>/assignment.aux
  fls: <path>/assignment.fls
  compiler: latexmk
    backend: jobs
    output: /tmp/vqabNtj/3
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Zathura
    xwin id: 0
  qf: LaTeX logfile using pplatex
    setqflist: 59
    set_errorformat: 58
  document class: article
  packages:
    amsbsy
    amsfonts
    amsgen
    amsmath
    amsopn
    amssymb
    amstext
    atbegshi
    atveryend
    auxhook
    biblatex
    bigintcalc
    bitset
    calc
    chemgreek
    epstopdf-base
    etexcmds
    etoolbox
    expl3
    geometry
    gettitlestring
    graphics
    graphicx
    hycolor
    hyperref
    iftex
    ifthen
    ifvtex
    infwarerr
    inputenc
    intcalc
    keyval
    kvdefinekeys
    kvoptions
    kvsetkeys
    l3keys2e
    letltxmacro
    lmodern
    logreq
    ltxcmds
    mhchem
    nameref
    pdfescape
    pdftexcmds
    refcount
    rerunfilecheck
    trig
    uniquecounter
    url
    xparse

**Comment by lervag** [comment]
The `pplatex` method does not have any configuration. That is, `g:vimtex_quickfix_latexlog` only affects the quickfix list when you use the `latexlog` method with `g:vimtex_quickfix_method`. Sorry.

**Comment by lervag** [comment]
Oh, you might be interested in the option `g:vimtex_quickfix_ignore_filters`, which allows to ignore errors/warnings regardless of which "backend" you use. It is a list of regexes that are used to filter the messages. See also #1569 for reference (and #1408).

**Comment by hejops** [comment]
Ah, that's a neat solution; I was wondering why there were two options that served a similar purpose. Thanks!

**Comment by lervag** [comment]
> I assume the syntax would be along the lines of let g:vimtex_quickfix_ignore_filters = [ '(ov|und)erfull' [, 'more regexes...'] ]? Thanks!

Yes, but you must use vim's regex syntax, see `:help regex`. Specifically, note that the default mode is called "magic mode", in which you must escape things like `(`, `|`, and `)`, thus:

```vim
let g:vimtex_quickfix_ignore_filters = [
      \ '\(ov\|und\)erfull',
      \ ...
      \]
```

**Comment by lervag** [comment]
Note also that you should try to keep the regexes relatively specifically to avoid too many "false positives". There might be errors/warnings with the word overfull that you want to see (I don't know if that is true in this case, but the point is still important).

**Comment by hejops** [comment]
> Specifically, note that the default mode is called "magic mode", in which you must escape things like `(`, `|`, and `)`

Got it, thanks again! Vim's regexes still catch me off guard...

**Comment by lervag** [comment]
Yes, the different variants of regexes between languages and tools can be confusing and catches most of uss off guard sometimes. I learned regexes from Vim, so for me, it is other variants that catch me off guard. :)
