### ISSUE TITLE
template for vimtex-compile-selected temporary file

### ISSUE THREAD

**Issue by slonik-az** [lervag/vimtex#1742]
`vimtex` has a very useful feature of compiling selected portion of a LaTeX document. It is achieved by placing the selected text into a temporary file that contains the same preamble as the file with the original selection.

Unfortunately, in many of my use cases the temporary file fails to compile. For example, I have to place some definitions and settings after `\begin{document}`. Not being part of the preamble they are missing from the temporary file, thus causing LaTeX compilation errors.

These problems can be solved by means of a `vimtex-selected-template.tex` placed in the same directory. This is a LaTeX file with a specially formatted comment line
``` %%% vimtex-selection-goes-here %%% ```
that will be replaced by the actual selected text when temporary file is created. The template gives a user flexibility to custom add LaTeX code beyond what is found in the preamble.

Thanks,
--Leo

**Comment by lervag** [comment]
> Unfortunately, in many of my use cases the temporary file fails to compile. For example, I have to place some definitions and settings after \begin{document}. Not being part of the preamble they are missing from the temporary file, thus causing LaTeX compilation errors.

It would be very useful with a minimal example. Note, I'm not sure I understand/agree that you "**have** to place some definitions and settings after \begin{document}". That is, why do you have to do that? And when?

Regarding the feature request: It would again be very useful if you could provide an explicit (minimal) example with a description of the expected workflow and results.

**Comment by slonik-az** [comment]
The Minimal Example is included towards the end of this message. But first I wanted to revise my proposal without templates.

## Revised proposal
(without any templates) Vimtex will recognize two optional marker-lines placed in the latex file
```%%% latex-header-end```
and
```%%% latex-trailer-start```
that, if found, will denote the header part (from the beginning of the file up to the header end comment) and the trailer part (from the trailer start comment to the end of file). Otherwise, the behavior is the same as it is now.

## Minimum Example
The following example fails to compile selected formula. But it will work OK under the revised proposal.

```
\documentclass[12pt]{article}

\newenvironment{LRmath}{
  \def\E{}
  \renewcommand{\E}[2][]{\ensuremath\mathrm{E}_{##1}\!\left[##2\right]}
  \def\PP{\ensuremath\mathrm{P}}
}{}

\begin{document}
\begin{LRmath}

%%% latex-header-end
Text, Text, Text

\begin{equation}
    \PP[x\le y] = \E[x]{\max(y-x,0)/(y-x)}
\end{equation}

Text, Text, Text

%%% latex-trailer-start
\end{LRmath}
\end{document}
```

If one selects just the equation and tries to compile the selection by pressing `<leader>lL`, compilation fails due to undefined `\PP` and `\E`. This is happening because the temporary file is missing `\begin{LRmath}...\end{LRmath}` environment that activates the definitions.

**Comment by lervag** [comment]
Your revised proposal is even less tempting to me; sorry!

Why do you need the `LRmath` environment, why not simply but those definitions in the preamble directly? And, if you need it, why not simply surround the equation with the `LRmath`, why surround so much other stuff as well?

In any case, I think your original proposal is better. A minimal example might then be:

**Original tex file**

```tex
\documentclass[12pt]{article}

\newenvironment{LRmath}{
  \def\E{}
  \renewcommand{\E}[2][]{\ensuremath\mathrm{E}_{##1}\!\left[##2\right]}
  \def\PP{\ensuremath\mathrm{P}}
}{}

\begin{document}
\begin{LRmath}

Text, Text, Text

\begin{equation}
    \PP[x\le y] = \E[x]{\max(y-x,0)/(y-x)}
\end{equation}

Text, Text, Text

\end{LRmath}
\end{document}
```

**Template file**

```tex
\documentclass[14pt]{article}

\def\E{}
\renewcommand{\E}[2][]{\ensuremath\mathrm{E}_{##1}\!\left[##2\right]}
\def\PP{\ensuremath\mathrm{P}}

\begin{document}

%%% vimtex-selection %%%

\end{document}
```

**Comment by slonik-az** [comment]
> Why do you need the `LRmath` environment, why not simply but those definitions in the preamble directly? And, if you need it, why not simply surround the equation with the `LRmath`, why surround so much other stuff as well?

I knew you would ask this question :-)    
I am writing lots of math equations and keep my LaTeX math shortcuts defined across multiple environments. `\begin{LRstat}...\end{LRstat}` for probability/statistics shortcut definitions, `\begin{LRqm}...\end{LRqm}` for Quantum Mechanics, `\begin{LRalgebra}...\end{LRalgebra}` for algebra definitions and so on. Each section is placed in a separate file and the complete document is stitched  together with `subfiles` machinery. I cannot put my math shortcuts definitions into a global preamble, for I need them scoped at a section (sometimes subsection) level. LaTeX environments give me lots of scope control and fit my use case perfectly.  I can even selectively combine my shortcuts by nesting the environments like this: `\begin{LRqm}\begin{LRstat}...\end{LRstat}\end{LRqm}` .

Your second question was -- why not surround each equation with the LRmath environment. The answer is -- too much boiler plate. A section in my doc can easily have 20+ equations. It would be tiresome to repeat the same `\begin{LRmath}...\end{LRmath}` every single time I am writing a new display equation or around each paragraph that has any inline math in it. I typically activate an environment at the largest possible scope. Of course, in some cases I use a narrow scope down to a single equation.

**Comment by lervag** [comment]
> I knew you would ask this question :-)

:)

> I am writing lots of math equations and keep my LaTeX math shortcuts defined across multiple environments. `\begin{LRstat}...\end{LRstat}` for probability/statistics shortcut definitions, `\begin{LRqm}...\end{LRqm}` for Quantum Mechanics, `\begin{LRalgebra}...\end{LRalgebra}` for algebra definitions and so on. Each section is placed in a separate file and the complete document is stitched together with `subfiles` machinery. I cannot put my math shortcuts definitions into a global preamble, for I need them scoped at a section (sometimes subsection) level. LaTeX environments give me lots of scope control and fit my use case perfectly. I can even selectively combine my shortcuts by nesting the environments like this: `\begin{LRqm}\begin{LRstat}...\end{LRstat}\end{LRqm}` .

Ok! Is the point that you have conflicting macros/shortcuts? If not, then I still don't understand why you can not have them in the global preamble.

> Your second question was -- why not surround each equation with the LRmath environment. The answer is -- too much boiler plate. A section in my doc can easily have 20+ equations. It would be tiresome to repeat the same `\begin{LRmath}...\end{LRmath}` every single time I am writing a new display equation or around each paragraph that has any inline math in it. I typically activate an environment at the largest possible scope. Of course, in some cases I use a narrow scope down to a single equation.

Makes sense, but again: Why not use global macros?

**Comment by slonik-az** [comment]
> Ok! Is the point that you have conflicting macros/shortcuts?

Yes, this is indeed the case. Macros conflicts were the main reason for me to move shortcut definitions from the global scope to a local one. The problem is much worse if you are collaborating with your co-authors in writing a review article or report with each one of them responsible for their own section or chapter. Every co-author has their own habits and preferences resulting in using the same (short) names for very different macros. Flexible scoping with environments really helps here.
That's why all my shortcut environments have my initials as part of the name as in `\begin{LRmath}...\end{LRmath}`. It helps separating my stuff from someone else's  `\begin{XYmath}...\end{XYmath}`

**Comment by lervag** [comment]
I think this update should give you the desired capability. Please test. Please see `:help VimtexCompileSelected` for a specification of the feature, and let me know if you have thoughts on the docs or the feature itself.

**Comment by slonik-az** [comment]
Thanks for taking care of this enhancement so promptly. Much appreciated!  

It works OK but needs some improvements. In my workflow I keep each section in a separate file like `foo.tex`, `bar.tex`, etc. They use different and oftentimes conflicting shortcut macros environments. A single common template such as `vimtex-template.tex` would not cut it. To compile a selection from `foo.tex` I would need `foo-vimtex-template.tex` while a selection from `bar.tex` will use `bar-vimtex-template.tex`.

Here is the logical flow I have in mind:
* To compile a selection from `foo.tex` first try to locate `foo-vimtex-template.tex` in the same directory. If successful -- use this template to generate the temporary file.
* **Else If** common  `vimtex-template.tex` exists in the same directory -- use it to generate temporary file
* **Else** (no templates found) fall back to old logic of generating temporary file.

**Comment by lervag** [comment]
I've updated as suggested. Does it now work as expected?

If this should be developed any further, then I would take some more time to improve the code quality. I think it is OK now, but there's room for improvement :)

**Comment by slonik-az** [comment]
Your latest changes seem to work fine! I noticed couple of errors in some *.tex files `test/tests/test-compiler-selected/` and corrected them in a PR above. CI tests seem to pass OK.

**Comment by lervag** [comment]
Thanks! Happy to hear it works :)
