### ISSUE TITLE
Triggering autocomplete in second or third pair of braces of multicite commands

### ISSUE THREAD

**Issue by flimofly** [lervag/vimtex#1744]
It does look like vimtex supports biblatex cite commands such as `\autocite`, but there does not seem to be a way to trigger the popup menu for autocompletion of bibliographic references when using multicite commands, such as `\autocite{}{}.` 

To be concrete, it would be nice if completion could be triggered (even if manually) when one jumps to the second (or third,...) pair of curly braces. 

Using the typical colon between different citekeys is not an option here. The multicite command allows one to specify a prenote and postnote (eg page number) for each individual citeky, like so: `\autocites[See also][46--48]{Jones:2000df}[Moreover, there are two old papers, namely][2--5]{Jackson:2005aa}[3--4]{Jackson:2002di}` or even like `\autocites(This is shown by several sources.)(More information can be found in the library.)[See, first of all,][12--14]{Jones:2000ab}[Moreover, see also][34]{Jackson:1969a}`

**Comment by lervag** [comment]
Can you show me the reference of the `\autocites` command and explain the full syntax?

**Comment by flimofly** [comment]
The command is explained in the [biblatex manual](https://mirror.koddos.net/CTAN/macros/latex/contrib/biblatex/doc/biblatex.pdf) on p. 108-109. 

Here's the syntax:

<img width="1219" alt="Screenshot 2020-07-13 at 20 09 51" src="https://user-images.githubusercontent.com/20085376/87338095-dcbc5700-c544-11ea-90f1-b4b93a2bf36b.png">

Syntax is identical to that of \autocite but with several {bibkeys} in a row, each with own [prenote] and [postnote] and the possibility of a global (prenote) and global (postnote).

- When only one bibkey is added, autocites is treated as autocite.
- The global prenote and postnote are optional. When only one pair is present, it is treated as a global postnote.
- The prenote and postnote linked to the bibkey are optional.
- Importantly, the syntax allows you to leave out one of both pairs of []. In that case, the remaining pair is treated as the [postnote]. 

So, all of these -- a non-exhaustive list -- are valid:
`\autocites[]{}[]{}`
`\autocites{}{}`
`\autocites(){}`
`\autocites(){}{}`
`\autocites()[]{}[]{}`
`\autocites()(){}{}`

**Comment by j1-lee** [comment]
I guess I can do this but this might involve a lengthy regex. If I am to make a pull request regarding this, @lervag, which one would you prefer between the next two styles (to be added in complete.vim)?

1.
```vim
      \   '\v\\\a*cites%(\s*\([^)]*\)){0,2}%(%(\s*\[[^]]*\]){0,2}\s*\{[^}]*\})*'
      \ . '%(\s*\[[^]]*\]){0,2}\s*\{[^}]*$',
```

2.
```vim
      \   '\v\\\a*cites%(\s*\([^)]*\)){0,2}%(%(\s*\[[^]]*\]){0,2}\s*\{[^}]*\})*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*$',
```

The first one avoids using more than 80 characters per line, but is potentially confusing for future maintenance. The second one goes over 80 columns.

Another possibility is to reduce the regex so that it does not check the syntax properly, i.e., something like:
```vim
      \   '\v\\\a*cites\s*%(\([^)]*\)|\[[^]]*\]|\{[^}]*\})*\s*\{[^}]*$'
```
which will allow an incorrect expression `\autocites[something][like][this](example){ «cursor» }`. Personally I don't like this option 3.

**Comment by lervag** [comment]
> I guess I can do this but this might involve a lengthy regex.

@j1-lee Thanks for pitching in, I appreciate the help!

> If I am to make a pull request regarding this, @lervag, which one would you prefer between the next two styles (to be added in complete.vim)?

I would prefer the first one that avoids long lines. But perhaps break the regex at more "logical" places? Something like this:

```vim
      \   '\v\\\a*cites%(\s*\([^)]*\)){0,2}'
      \ . '%(%(\s*\[[^]]*\]){0,2}\s*\{[^}]*\})*'
      \ . '%(\s*\[[^]]*\]){0,2}\s*\{[^}]*$',
```

Not _important_, but I think it is slightly easier to read.

If you do open a PR, then I would appreciate if you could try to add one or more tests, see `test/tests/test-completion-bibtex`.

**Comment by j1-lee** [comment]
Great, nice suggestion. I'll then work on this, apply it to deoplete, ycm, etc, and try add tests.

**Comment by lervag** [comment]
> Great, nice suggestion. I'll then work on this, apply it to deoplete, ycm, etc, and try add tests.

Cool. Feel free to open a PR early and let me know if you want any help/input!

**Comment by lervag** [comment]
#1752 should resolve this issue. @flimofly can you test?

**Comment by flimofly** [comment]
Works perfectly. Many thanks for the quick implementation @j1-lee and @lervag !

**Comment by lervag** [comment]
Great, happy to hear it! Credits to @j1-lee for the effort and work! :)
