### ISSUE TITLE
Question on closing the quickfix list upon resuming editing of the source file

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1746]
Apologies, I had to raise this 'pseudo' issue here because there is no asynchronous communication with the project (like _gitter_ for example) listed on the `README.md`, and instead of sending an email to the author, I thought it is perhaps best to have this question here for others to potentially benefit from an answer.

I find `vimtex's` feature of automatically closing the quick fix list after 2-3 keystrokes of resuming editing the main file to be incredibly useful. Not just latex, but a whole host of compiler plugins use the quickfix tool for the build status, right. 

Sometimes, we may want to get back to the editing (either to fix the current warning(s), or not to lose the train of thought), and therefore this feature is very useful outside of `vimtex`.

Can you please explain how I can achieve this effect in other filetypes i.e. autoclose the quickfix window after a configurable number of keypresses when resuming editing the main file?

**Comment by lervag** [comment]
> Apologies, I had to raise this 'pseudo' issue here because there is no asynchronous communication with the project (like _gitter_ for example) listed on the `README.md`, and instead of sending an email to the author, I thought it is perhaps best to have this question here for others to potentially benefit from an answer.

There [_is_ a gitter channel](https://gitter.im/vimtex-chat/community?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)! There's even a badge for it on the top of the README file, and you've even posted there once :)

But I don't mind issues raised for discussions, so no problem!

> I find `vimtex's` feature of automatically closing the quick fix list after 2-3 keystrokes of resuming editing the main file to be incredibly useful. Not just latex, but a whole host of compiler plugins use the quickfix tool for the build status, right.

Yes, I agree it is a nice feature, and I guess it could be something that one could potentially decouple from vimtex and submit as a separate repo.

> Can you please explain how I can achieve this effect in other filetypes i.e. autoclose the quickfix window after a configurable number of keypresses when resuming editing the main file?

The feature is quite simple, actually. The following code is the essential part and may be found in `autoload/vimtex/qf.vim`:

```vim
augroup vimtex_qf_autoclose
  autocmd!
  autocmd CursorMoved,CursorMovedI * call s:qf_autoclose_check()
augroup END

function! s:qf_autoclose_check() abort
  if get(s:, 'keystroke_counter') == 0
    let s:keystroke_counter = g:vimtex_quickfix_autoclose_after_keystrokes
  endif

  redir => l:bufstring
  silent! ls!
  redir END

  if empty(filter(split(l:bufstring, '\n'), 'v:val =~# ''%a- .*Quickfix'''))
    let s:keystroke_counter -= 1
  else
    let s:keystroke_counter = g:vimtex_quickfix_autoclose_after_keystrokes + 1
  endif

  if s:keystroke_counter == 0
    cclose
    autocmd! vimtex_qf_autoclose
    augroup! vimtex_qf_autoclose
  endif
endfunction
```

So, how does this work?

1. The `augroup` code must be called after the quickfix window is opened. This may be possible to do more generally by wrapping it inside a function, and then calling that function in a new autocommand hook for e.g. with the `QuickFixCmdPost` event (see `:help QuickFixCmdPost`). In vimtex, it is called as part of the function that opens the quicfix window, i.e. the function mapped to by `\le`.

2. The function `s:qf_autoclose_check` is called on every CursorMoved event, and it uses a counter stored in the `s:keystroke_counter` variable. The counter is initialized to the value of the option `g:vimtex_quickfix_autoclose_after_keystrokes`. There's a check that subtracts 1 from the counter unless the current buffer is the quickfix buffer itself. When the counter reaches 0, the quickfix window is closed and the autocommands are wiped.

I hope this helps!

**Comment by krishnakumarg1984** [comment]
@lervag 
Thanks for this very useful snippet. I copied the contents on to `~/.vim/ftplugin/cpp` . The auto-close idea worked for the 1st instance, but subsequently whenever the quickfix window was opened, it didn't have any effect.

How can I fix this?

**Comment by lervag** [comment]
I already gave a suggestion on this:

> The augroup code must be called after the quickfix window is opened. This may be possible to do more generally by wrapping it inside a function, and then calling that function in a new autocommand hook for e.g. with the QuickFixCmdPost event (see :help QuickFixCmdPost). In vimtex, it is called as part of the function that opens the quicfix window, i.e. the function mapped to by \le.

Still, I can understand that this is relatively advanced. The part you need to change is the code that defines the `vimtex_qf_autoclose` augroup. Here's an updated example that I think should work, but I'll leave the testing to you.

```vim
augroup qf_autoclose
  autocmd!
  " Please read the docs on this event (:help QuickFixCmdPost). Here you may
  " specify commands that should activate the feature (e.g. cwindow, copen,
  " etc). If " you also want it for location lists, then you could use simply
  " `*` instead of " `c*`. And so on.
  autocmd QuickFixCmdPost c* call s:qf_autoclose_start()
augroup END

function! s:qf_autoclose_start() abort
  " This function does the same as the original example. The point is that this
  " needs to run everytime the quickfix window is opened.
  augroup qf_autoclose_tmp
    autocmd!
    autocmd CursorMoved,CursorMovedI * call s:qf_autoclose_check()
  augroup END
endfunction

function! s:qf_autoclose_check() abort
  if get(s:, 'keystroke_counter') == 0
    let s:keystroke_counter = g:quickfix_autoclose_after_keystrokes
  endif

  redir => l:bufstring
  silent! ls!
  redir END

  if empty(filter(split(l:bufstring, '\n'), 'v:val =~# ''%a- .*Quickfix'''))
    let s:keystroke_counter -= 1
  else
    let s:keystroke_counter = g:quickfix_autoclose_after_keystrokes + 1
  endif

  if s:keystroke_counter == 0
    cclose
    autocmd! qf_autoclose_tmp
    augroup! qf_autoclose_tmp
  endif
endfunction
```

**Comment by krishnakumarg1984** [comment]
@lervag Apologies for being on the slower side here.  I tried the new code, but that also didn't work. Perhaps the problem is is that the number of keystrokes after which the autoclose is to be activated is not defined?

**Comment by lervag** [comment]
Yes, you need to define `g:quickfix_autoclose_after_keystrokes`, e.g. in your vimrc file or in the  same file.

**Comment by krishnakumarg1984** [comment]
@lervag Thanks for being so nice, and helping out though this is not strictly a vimtex question. 

I still didn't get it to work. My `~/.vim/ftplugin/cpp/qf_autoclose.vim` file is now the following:

```vim

let g:quickfix_autoclose_after_keystrokes=3

augroup qf_autoclose
  autocmd!
  " Please read the docs on this event (:help QuickFixCmdPost). Here you may
  " specify commands that should activate the feature (e.g. cwindow, copen,
  " etc). If " you also want it for location lists, then you could use simply
  " `*` instead of " `c*`. And so on.
  autocmd QuickFixCmdPost * call s:qf_autoclose_start()
augroup END

function! s:qf_autoclose_start() abort
  " This function does the same as the original example. The point is that this
  " needs to run everytime the quickfix window is opened.
  augroup qf_autoclose_tmp
    autocmd!
    autocmd CursorMoved,CursorMovedI * call s:qf_autoclose_check()
  augroup END
endfunction

function! s:qf_autoclose_check() abort
  if get(s:, 'keystroke_counter') == 0
    let s:keystroke_counter = g:quickfix_autoclose_after_keystrokes
  endif

  redir => l:bufstring
  silent! ls!
  redir END

  if empty(filter(split(l:bufstring, '\n'), 'v:val =~# ''%a- .*Quickfix'''))
    let s:keystroke_counter -= 1
  else
    let s:keystroke_counter = g:quickfix_autoclose_after_keystrokes + 1
  endif

  if s:keystroke_counter == 0
    cclose
    autocmd! qf_autoclose_tmp
    augroup! qf_autoclose_tmp
  endif
endfunction
```

What am I doing incorrectly?

**Comment by lervag** [comment]
Could you also explain the steps you use to fill and open the quickfix window?

**Comment by lervag** [comment]
Some debugging can be useful here, to try and understand where things are not working as expected. So, you could add `unsilent echo "test"` or similar at various places to see if the specific code is running. Or `unsilent echo "xxx" s:keystroke_counter` to see the value of the counter.

**Comment by krishnakumarg1984** [comment]
>Could you also explain the steps you use to fill and open the quickfix window?

Yes. I use the [`asynctasks`](https://github.com/skywind3000/asynctasks.vim) and [`asyncrun`](https://github.com/skywind3000/asyncrun.vim) plugins to quickly compile a single-file `cpp` source file in the current  buffer. These plugins automatically open the `quickfix` window during compilations (even if there are no warnings). If there are warnings or errors, they are also shown in the quickfix window.

I don't understand why the autoclose script you provided does not co-operate well with this (since it is nothing more than just an open quickfix window, I think).  Anyhow, with these plugins, one way to close the quickfix window is through  hooking up to the `:call asyncrun#quickfix_toggle(8)<cr>` facility provided by them.  Can your script be somehow modified to simply call this instead?

>Some debugging can be useful here, to try and understand where things are not working as expected. So, you could add unsilent echo "test" or similar at various places to see if the specific code is running. Or unsilent echo "xxx" s:keystroke_counter to see the value of the counter.

Okay, I don't have much experience here, but I am going to try.

**Comment by lervag** [comment]
> Yes. I use the [`asynctasks`](https://github.com/skywind3000/asynctasks.vim) and [`asyncrun`](https://github.com/skywind3000/asyncrun.vim) plugins to quickly compile a single-file `cpp` source file in the current buffer. These plugins automatically open the `quickfix` window during compilations (even if there are no warnings). If there are warnings or errors, they are also shown in the quickfix window.

Ok, I see.

> I don't understand why the autoclose script you provided does not co-operate well with this (since it is nothing more than just an open quickfix window, I think). Anyhow, with these plugins, one way to close the quickfix window is through hooking up to the `:call asyncrun#quickfix_toggle(8)<cr>` facility provided by them. Can your script be somehow modified to simply call this instead?

Yes, probably. But I don't know how exactly, because I don't use these scripts myself currently.

> > Some debugging can be useful here, to try and understand where things are not working as expected. So, you could add unsilent echo "test" or similar at various places to see if the specific code is running. Or unsilent echo "xxx" s:keystroke_counter to see the value of the counter.
> 
> Okay, I followed your suggested and inserted `unsilent echo "debugging qf autoclose ..."` one at a time at each and every line in the file `~/.vim/ftplugin/cpp/qf_autoclose.vim` . That echo statement doesn't get called at all, when used anywhere within any of the functions!

> But I can confirm that it is in the right location, because when I place the `unsilent echo "debugging qf autoclose ..."` statement right at the top of the `ftplugin` file and open say `demo.cpp` the debugging message echoes at the bottom of vim's command-line (status message area) during the opening of the buffer. When opening `demo.txt`, that doesn't happen. So, at least we are working with the right file to load this functionality.

> But why doesn't any of these lines get executed?

I think the problem is that the autocmd at the top does not work as expected. Instead of `QuickFixCmdPost`, we need something else that works with asynctasks or asyncrun. I am sorry to say I don't know exactly what. :\

So, you need to play with the `augroup qf_autoclose` and related lines. Perhaps asynctasks/-run has an event that you can hook into? You could also try to do something like `autocmd QuickFixCmdPost copen call s:qf_autoclose_start()` and similar, i.e. change the `*` to various quickfix commands. Other possibilities are `make`, `cwindow`, etc.

**Comment by krishnakumarg1984** [comment]
@lervag There could be a very easy solution to this (but I could use your help).

In my `vimrc`, I have currently set 

`nnoremap <leader>q :call asyncrun#quickfix_toggle(8)<cr>`

which does the job for me manually.  So, can you help to slightly modify your original solution to just evaluate the RHS suitably i.e. `:call asyncrun#quickfix_toggle(8)<cr>`

**Comment by lervag** [comment]
Hi! Sorry for late reply, been busy.

So, what we have so far is this, which does not work:

```vim
augroup qf_autoclose
  autocmd!
  autocmd QuickFixCmdPost * call s:qf_autoclose_start()
augroup END
```

Based on your previous post, I would think perhaps the following could work:

```vim
augroup qf_autoclose
  autocmd!
  autocmd User AsyncRunStart call s:qf_autoclose_start()
augroup END
```

If you do use the AsyncRun features, then I would think this should work. As an alternative, it is of course also possible to rely on a mapping. I would do that like this (still in the `ftplugin/cpp.vim` file):

```vim
nnoremap <leader>q :<c-u>call s:qf_toggle()<cr>

function! s:qf_autoclose_start() abort
  augroup qf_autoclose_tmp
    autocmd!
    autocmd CursorMoved,CursorMovedI * call s:qf_autoclose_check()
  augroup END

  call asyncrun#quickfix_toggle(8, 1)
endfunction
```

I would try the autocmd solution first, as it is more "automatic". If it does not work, then I can't see why the latter solution would not work.
