### ISSUE TITLE
RFC: Bumping Vim/neovim version requirement?

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#1748]
A lot of years ago I determined to keep vimtex compatible with Vim version 7.4. This means I'm prevented from using a lot of more recent updates to vimscript which is sometimes quite annoying. I'm now considering to bump the requirements to Vim version 8.0 or 8.1 (and simillarly for neovim). I'm curious if the community has any thoughts on the matter.

Such a change would imply that I check the version and present a relevant warning. I would also ensure to tag the last version that works with Vim 7.4. This could possibly also be a starting point for versioning vimtex properly (I've never bothered with that before).

**Comment by slonik-az** [comment]
I think this is a great idea! To the best of my knowledge vim-8.x installers  are readily available to all new Linux, MacOS, Windows systems. Legacy vim-7.x installations are mostly confined to legacy servers and are used for sysadmin purposes rather than writing LaTeX docs.

**Comment by clason** [comment]
I would wholeheartedly support this. Since you mention neovim, I'd suggest targeting the latest release here (0.4.3) -- neovim users tend to be early adopters, and distros that do not package this are usually so far behind (0.2.x) as to be almost unusable... (And neovim provides easy-to-use app images for these situations.)

I'm very much looking forward to what vimtex 2.0 will bring 😁

**Comment by Rmano** [comment]
I mostly agree with this, if the requirement is vim-8.0 (and not 8.1). Vim-8.0 is the version shipped with Ubuntu 18.04 LTS, and it will have a quite long future yet, on a practical point of view.

**Comment by lervag** [comment]
Great, happy to hear it. I think it sounds good to restrict the version to the patch-level used by Ubuntu 18.04 LTS, i.e. patch level 1453. This will be very nice, because I can clean up a lot of unnecessary code used to preserve compatibility.

Before I start making these changes, I will tag the current version as version 1.0 and provide a release which also gives a clear statement of the requirement changes.

**Comment by lervag** [comment]
Thanks, this is settled then. I'll tag a release 1.0 which is compatible with Vim 7.4, then update requirements to Vim 8.0 and neovim 0.4.3 and make this clear in both the README file and in the docs. Then I'll start to update vimtex to use more modern features. I'll probably start to make more releases to make it more clear how things develop.
