### ISSUE TITLE
Change PDF Viewer 

### ISSUE THREAD

**Issue by pluskid** [lervag/vimtex#175]
Hi, I changed the default PDF viewer to Skim.app via
```
let g:vimtex_view_general_viewer = 'open'
let g:vimtex_view_general_options = '-a Skim'
```
it works fine when I use `<leader>lv` to open the viewer. But when I use `<leader>ll` to start building mode, it will open the system default PDF viewer (instead of Skim.app) after it finish building. Is this a bug?

**Comment by lahwaacz** [comment]
latexmk has some default PDF viewer, you could try to disable it with
``` perl
$pdf_previewer = '';
$pdf_update_method = 0;
```
in `~/.latexmkrc`.

**Comment by pluskid** [comment]
Thanks!

**Comment by lervag** [comment]
It was not really a bug, but I've added some code that should fix the problem without you having to add the mentioned settings to your `.latexmkrc` file. Could you test the latest version? That is, remove the lines that @lahwaacz mentioned and test the latest version. It should now pass the general viewer settings to latexmk, which should then open.

**Comment by pluskid** [comment]
@lervag No, it doesn't work. Although I guess it might be because of a typo in the latest commit:
```
g:vimtex_view_mupdf_options
```
maybe should be `general_options`?

**Comment by lervag** [comment]
Yes, you're right. It's updated now.

**Comment by pluskid** [comment]
Thanks! It works now.

**Comment by lervag** [comment]
Great!
