### ISSUE TITLE
Selected word count (g ctrl-g) becomes useless

### ISSUE THREAD

**Issue by HuidaeCho** [lervag/vimtex#1753]
**Issue**

Selecting lines and `g`, `ctrl-g` shows selected word counts in Vim. With vimtex, I can see it kind of working, but only a fraction of a second. Vimtex doesn't give the user enough time to be able to see this information and almost immediately switches to `-- VISUAL LINE --`.

**minimal.vim**
```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```
Nothing else in `~/.vimrc`

**minimal.tex**
```tex
line 1
line 2
```

**Commands/Input**
1. Select the first line using `shift-v`
2. Press `g` then `ctrl-g`

**Observed Behaviour**

Selected word counts flashes and `-- VISUAL LINE --` overwrites it immediately.

**Expected Behaviour**

Selected word counts stay there until another key press or action is taken.

**Output from VimtexInfo**

```vim
System info
  OS: Linux 4.14.39
  Vim version: VIM 7.4 (1-1938)
  Has clientserver: true
  Servername: VIM2

vimtex project: main
  base: main.tex
  root: /home/user/paper
  tex: /home/user/paper/main.tex
  out: /home/user/paper/main.pdf
  log: /home/user/paper/main.log
  aux: /home/user/paper/main.aux
  fls: /home/user/paper/main.fls
  main parser: recursive search
  source files:
    main.tex
    macros.tex
    title.tex
    abstract.tex
    software-availability.tex
    1-introduction.tex
    2-methods.tex
    3-case-study.tex
    4-results-discussion.tex
    5-conclusions.tex
    acknowledgements.tex
  compiler: latexmk
    backend: process
    output: /var/tmp/v9Pa2UK/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: 
  packages:
    algorithm
    algorithmicx
    algpseudocode
    amsbsy
    amsfonts
    amsgen
    amsmath
    amsopn
    amssymb
    amstext
    array
    atbegshi
    atveryend
    auxhook
    bigintcalc
    bitset
    booktabs
    caption
    caption3
    cas-common
    color
    colortbl
    comment
    dcolumn
    epstopdf-base
    etexcmds
    etoolbox
    expl3
    float
    fontenc
    footmisc
    geometry
    gettitlestring
    graphics
    graphicx
    hycolor
    hyperref
    iftex
    ifthen
    ifvtex
    infwarerr
    intcalc
    keyval
    kvdefinekeys
    kvoptions
    kvsetkeys
    l3keys2e
    letltxmacro
    ltxcmds
    makecell
    moreverb
    multirow
    nameref
    natbib
    pdfescape
    pdftexcmds
    refcount
    rerunfilecheck
    setspace
    siunitx
    stfloats
    subfig
    tabularx
    trig
    uniquecounter
    url
    verbatim
    wrapfig
    xcolor
    xparse
    xspace
    xstring
```

**Comment by j1-lee** [comment]
Hi, have you tried the same with no vimrc loaded, i.e., `vim -u NONE minimal.tex`? The same happens even without loading vimtex plugin, at least on my machine with nvim (seems like vim 7 is no longer supported by vimtex). Option `set noshowmode` (if you're using airline or lightline) might keep the message from disappearing.

**Comment by lervag** [comment]
Thanks @j1-lee! I was sure I added a reply here similar to what you typed! Don't know what happened!

So, more clearly from me: This issue does not really seem like a vimtex issue. I can actually not reproduce it with either of Vim or neovim.

And yes: I've recently updated the requirements for vimtex. If you are stuck on old Vim (older than Vim 8), then you should not update vimtex beyond v1.0.

**Comment by HuidaeCho** [comment]
> Hi, have you tried the same with no vimrc loaded, i.e., `vim -u NONE minimal.tex`? With vim 8 or nvim, the same happens (but with 3 seconds of delay rather than a fraction of a second), even without loading vimtex plugin when `set showmode` is set.

I have tried that to no avail. Without vimtex or vimrc, it works with a delay of 3 seconds. That's an expected behavior with vimtex, I guess?

> 
> Seems like vim 7 you are currently using is no longer supported by vimtex... But perhaps option `set noshowmode` (if you're using airline or lightline) might keep the message from disappearing, I guess.

`set noshowmode` is a workaround. Thanks for the hint.

**Comment by HuidaeCho** [comment]
> Thanks @j1-lee! I was sure I added a reply here similar to what you typed! Don't know what happened!
> 
> So, more clearly from me: This issue does not really seem like a vimtex issue. I can actually not reproduce it with either of Vim or neovim.
> 
> And yes: I've recently updated the requirements for vimtex. If you are stuck on old Vim (older than Vim 8), then you should not update vimtex beyond v1.0.

Interesting. Neovim works fine. Maybe, it's the Vim version. Mine is 7.4.1938.

**Comment by lervag** [comment]
As before, I can't reproduce this. I don't have any idea what could cause this delay. Vimtex does set som Vim settings for tex buffers, but I can't think of any that should cause such a delay. You could try to disable different parts of vimtex with the following settings. First disable everything with `g:vimtex_enabled`, then selectively by feature with the other options. It would be helpful if you would be able to pinpoint which part of vimtex introduces the problem.

```vim
let g:vimtex_enabled = 0
let g:vimtex_compiler_enabled = 0
let g:vimtex_complete_enabled = 0
let g:vimtex_fold_enabled = 0
let g:vimtex_format_enabled = 0
let g:vimtex_imaps_enabled = 0
let g:vimtex_include_search_enabled = 0
let g:vimtex_indent_enabled = 0
let g:vimtex_indent_bib_enabled = 0
let g:vimtex_mappings_enabled = 0
let g:vimtex_matchparen_enabled = 0
let g:vimtex_motion_enabled = 0
let g:vimtex_quickfix_enabled = 0
let g:vimtex_syntax_enabled = 0
let g:vimtex_text_obj_enabled = 0
let g:vimtex_toc_enabled = 0
let g:vimtex_view_enabled = 0
```

**Comment by HuidaeCho** [comment]
```vim
let g:vimtex_matchparen_enabled = 0
```
works!

**Comment by lervag** [comment]
Great. After vimtex version 1.0, I've updated the code so that you should use Vim 8.0 with patch level 1452 or more (the Vim version from Ubuntu 18.04, LTS). This may have been relevant. So, you could try to checkout the tag `v1.0`, i.e. `git checkout v1.0` inside the vimtex repo. Still, I'm not sure.

In any case, I won't spend more time on this unless you can show that your problem somehow exists on a supported version of Vim.
