### ISSUE TITLE
Switching Color Schemes Removes Style Syntax Highlighting

### ISSUE THREAD

**Issue by Neightro** [lervag/vimtex#1754]
**Issue**
When setting a color scheme, the syntax highlighting for bold and italic text within Vim disappears. Running `:source /usr/share/vim/vim82/syntax/hitest.vim` and searching for texBoldStyle confirms that the highlighting groups are cleared; if the same script is sourced again, then they no longer appear. As a temporary workaround, executing `:set ft=tex` restores the highlighting groups.

Before changing color scheme:
![image](https://user-images.githubusercontent.com/23202923/87900371-083db680-ca09-11ea-9dd2-f02497b2a7dc.png)

After `:set bg=dark`:
![image](https://user-images.githubusercontent.com/23202923/87900488-5783e700-ca09-11ea-8193-d3df0b8704fd.png)

**minimal.vim**
  ```vim
set nocp
set encoding=utf-8
set conceallevel=1
let g:tex_conceal = 'abdmg'
set rtp+=~/.vim/bundle/vimtex rtp+=~/.vim/bundle/vimtex/after
filetype plugin indent on
syntax on
  ```

**minimal.tex**

  ```tex
  \documentclass{minimal}
  \begin{document}

  \textit{Hello}, \textbf{world}!

  \end{document}
  ```

**Commands/Input**
`source $VIMRUNTIME/syntax/hitest.vim` for debugging highlighting
`colorscheme` with any color scheme, though changing the value of `background` will do as well.

**Observed Behaviour**
texBoldStyle and related highlighting groups remain cleared upon switching color scheme

**Expected Behaviour**
texBoldStyle and related highlighting groups are automatically re-applied when switching color schemes

**Output from VimtexInfo**
With my minimal.vim: `E492: Not an editor command: VimtexInfo`

With my full config (using Vundle):
```
System info
  OS: Manjaro Linux
  Vim version: VIM 8.2 (1-1185)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

vimtex project: minimal
  base: minimal.latex
  root: /home/nathan/.vim/bundle/vimtex
  tex: /home/nathan/.vim/bundle/vimtex/minimal.latex
  out:
  log:
  aux:
  fls:
  main parser: current file verified
  compiler: latexmk
    backend: jobs
    output: /tmp/v336FXw/1
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    config:
      packages:
        default: 1
      default: 1
  document class: minimal
```

**Comment by lervag** [comment]
This is not unexpected. Changing the colorscheme is generally a relatively _strong_ change, which often (always?) does things like `highlight clear`. Also, the problem is not related to vimtex, but to the built in syntax plugin (see `:help vimtex-syntax`).

I suggest that you generally don't change colorschemes _while_ editing. If you do change colorschemes, simply quit and reload the file you are working on.

**Comment by Neightro** [comment]
My apologies; I had assumed that vimtex used its own highlighting for some reason—and thank you regardless for the info.

My experience would  uggest that the problem is due to `hi! link`s being reset. I find it odd that none of the code syntax files seem to have this problem; only markup languages. Luckily you can fix these yourself with autocmd, which has become my solution with markdown.vim.

**Comment by lervag** [comment]
> My apologies; I had assumed that vimtex used its own highlighting for some reason—and thank you regardless for the info.

No problem, and sorry about the inconvenience.
