### ISSUE TITLE
can the ]] shortcut to close the current environment be disabled or changed?

### ISSUE THREAD

**Issue by jonorthwash** [lervag/vimtex#1756]
This is another "vimtex is great but it breaks my workflow in some minor but annoying way" ask for help.

I'm coming up short for how to disable the default behaviour of `]]` while in insert mode (closing the current environment).  I type `[` and `]` often for phonetic transcriptions in my LaTeX documents, and because of this behaviour of vimtex, typing a single `]` is really annoying.

I've checked the manual and looked around online some, and my lack of ability to find anything suggests to me that I don't even know what to call what I'm looking for.

**Comment by lervag** [comment]
I think you want the `:help g:vimtex_mappings_disable` option. With it, you can disable specifically the `]]` mapping. You can use the table in the `:help vimtex-default-mappings` section to see what to disable. In this case:

```vim
let g:vimtex_mappings_disable = {
      \ 'i': [']]'],
      \}
```
