### ISSUE TITLE
Open in new tab instead of buffer when backward searching

### ISSUE THREAD

**Issue by goingtosleep** [lervag/vimtex#1761]
I'm working with some tex files using `subfiles`.
When I `Ctrl+click` on some region of the pdf file, vim opens the corresponding tex file in a new buffer. 
I don't know if I can change the config somewhere to make vim open the tex file in a new tab? This behavior is similar to TexStudio.

I use `neovim 0.4.3` and `zathura 0.4.5` on `Ubuntu`.
Thank you for the great experience I have with `vimtex`.

Edit: Have no idea why the issue automatically labeled `bug`. I can't change that label.

**Comment by lervag** [comment]
> I'm working with some tex files using `subfiles`.
> When I `Ctrl+click` on some region of the pdf file, vim opens the corresponding tex file in a new buffer.
> I don't know if I can change the config somewhere to make vim open the tex file in a new tab? This behavior is similar to TexStudio.

No, sorry, this is not supported. Essentially, I think you should learn to use buffers. Tabs may have their uses, but (IMHO) tabs should not be considered "the way to display different buffers". I strongly recommend that you read `:help buffers`.

> I use `neovim 0.4.3` and `zathura 0.4.5` on `Ubuntu`.
> Thank you for the great experience I have with `vimtex`.

I'm happy you like it! :)

> Edit: Have no idea why the issue automatically labeled `bug`. I can't change that label.

Sorry about that, it's my fault. I should probably add a third kind of more general questions.
