### ISSUE TITLE
Error on startup (not the intended warning) when `g:tex_flavor` is not set

### ISSUE THREAD

**Issue by danielwe** [lervag/vimtex#1764]
**Issue**

Since f78a0bd, vimtex throws the following error when vim starts and 'g:tex_flavor' is not set:
```
Error detected while processing /home/username/.vim/plugged/vimtex/plugin/vimtex.vim[12]..function vimtex#log#warning[1]..10[13]..vimtex#debug#stacktrace:
line   44:
E684: list index out of range: 1
E116: Invalid arguments for function matchstr( vimtex#util#command('verbose function ' . l:func_name)[1], v:lang[0:1] ==# 'en'   ? 'Last set from \zs.*\.vim' : '\f\+\.vim')
```
The problem arises when `vimtex#log#warning` is called in `plugin/vimtex.vim`. Eventually a manual stacktrace is created, but the top-level item in `v:throwpoint` is just the filename `/home/username/.vim/plugged/vimtex/plugin/vimtex.vim`, which is not properly handled by the logic in `vimtex#debug#stacktrace`: The call to `vimtex#util#command` on line 52 in `autoload/vimtex/debug.vim` returns an empty list, and the error is thrown when trying to access its second element.

To reproduce, just run `vim -u minimal.vim`. No tex file or server needed.

**minimal.vim**

```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

**Output from VimtexInfo**

```
System info
  OS: Ubuntu 18.04.4 LTS
  Vim version: VIM 8.2 (1-1303)
  Has clientserver: true
  Servername: VIM
```

**Comment by lervag** [comment]
Huh, I'm sorry to say that I can't reproduce this (tried with Vim and neovim). Still, I've tried to fix the line where the error originated. Can you test?

**Comment by danielwe** [comment]
Thanks, that fixed it. Your inability to reproduce might be a vim version issue perhaps?

**Comment by lervag** [comment]
Perhaps. I'm on Vim 8.2.814.
