### ISSUE TITLE
Set different textwidths for math mode and non-math mode.

### ISSUE THREAD

**Issue by gaoqiangks** [lervag/vimtex#1767]
How to set different textwidths for math mode and non-math mode ?  I'm customered to set textwidth=80.  However, I find it's better to set unlimited textwidth for math mode.  Is there any way to do this ? I think it should be easy and just something like

```vim
autocmd CursorMoved,CursorMovedI *.tex let &l:textwidth = LineWidthForTex()
```

However, I don't know whether I'm in math mode.  Can you give me some help ?

**Comment by lervag** [comment]
Personally, I prefer to keep each sentence on a single line, so I have `textwidth = 0`. I don't want to add any code for this feature to vimtex, but I think you could rely on the api to get it. Something like this:

```vim
autocmd CursorMoved,CursorMovedI *.tex
      \ let &l:textwidth = vimtex#syntax#in_mathzone() ? 0 : 80
```

**Comment by lervag** [comment]
Note, though: I think this could cause some lag, since you are asking for code to be called on every keystroke. Perhaps you can be more specific with regard to which events to attach to? E.g., remove `CursorMovedI` and use `InsertEnter`, `InsertLeave`. I guess you could just experiment.

**Comment by gaoqiangks** [comment]
> Note, though: I think this could cause some lag, since you are asking for code to be called on every keystroke. Perhaps you can be more specific with regard to which events to attach to? E.g., remove `CursorMovedI` and use `InsertEnter`, `InsertLeave`. I guess you could just experiment.

Thank you very much!   That's what I want. Thanks again!

**Comment by lervag** [comment]
Happy to help! :)
