### ISSUE TITLE
deoplete settings does not work after updates.

### ISSUE THREAD

**Issue by xarthurx** [lervag/vimtex#1769]
**Issue**

I update the plugin and now settings worked before gives me error:
![image](https://user-images.githubusercontent.com/1921878/89790196-df00d980-db21-11ea-873b-b285f975c709.png)

**minimal.vim**

  ```vim
" Specify a directory for plugins
if has("win32") || has("win64")
  let g:plugged_home = $LOCALAPPDATA.'/nvim/plugged'
else
    let g:plugged_home = '~/.vim/plugged'
endif

call plug#begin(g:plugged_home)

" register plug-in itself as plugin
Plug 'junegunn/vim-plug'

" auto-completion
if has('nvim')
    Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
    Plug 'Shougo/deoplete.nvim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
endif

" LaTeX support
Plug 'lervag/vimtex', { 'for' : ['tex', 'latex', 'plaintex']}
autocmd! User vimtex echom 'vimtex is now loaded!'

call plug#end()

" " Auto completion at startup
let g:deoplete#enable_at_startup = 1
" " Use smartcase.
call deoplete#custom#option('smart_case', v:true)
"
" " -- TeX
" " global settings
let g:tex_flavor='latex'

" -- VimTex
" auto completion with deoplete
call deoplete#custom#var('omni', 'input_patterns', {
      \ 'tex': g:vimtex#re#deoplete
      \})

  ```

**minimal.tex**

no need for the tex file.

**Commands/Input**

**Observed Behaviour**

**Expected Behaviour**

**Output from VimtexInfo**

**Comment by xarthurx** [comment]
Additional note:
It seems the vimtex is not loading "re.vim" package?

![image](https://user-images.githubusercontent.com/1921878/89801738-dd8add80-db30-11ea-8f21-5025b7409cb4.png)


I got another error when editing tex file.

**Comment by Shougo** [comment]
This is not bug.  It is your configuration fault.

```vim
Plug 'lervag/vimtex', { 'for' : ['tex', 'latex', 'plaintex']}
```

Do you understand the configuration??
It means `vimtex` is loaded when tex file editing.

```vim
" -- VimTex
" auto completion with deoplete
call deoplete#custom#var('omni', 'input_patterns', {
    \ 'tex': g:vimtex#re#deoplete
    \})
```

It means it is executed when Vim is loaded.  But vimtex cannot be loaded until tex file editing.
So the error messages are displayed.

You need to configure vimtex configuration in `autocmd User vimtex`.
Please read it.

```vim
autocmd! User vimtex echom 'vimtex is now loaded!'
```

**Comment by xarthurx** [comment]
@Shougo  
I have your last line in the minimal vimrc file above. Please read?

And when I fallback the vimtex package to version `af9d5e8`, which is the version before update, I don't have the problem in this issue.

So I guess `vimtex` must have changed something between my version and the current `master` version.

**Comment by Shougo** [comment]
> @Shougo
> I have your last line in the minimal vimrc file above. Please read?

Please read this??

> You need to configure vimtex configuration in autocmd User vimtex.

This is *not* vimtex configuration.

> autocmd! User vimtex echom 'vimtex is now loaded!'

**Comment by Shougo** [comment]
> So I guess vimtex must have changed something between my version and the current master version.

I don't know previous behavior.  I think you have added lazy loading for vimtex.

```vim
autocmd! User vimtex call deoplete#custom#var('omni', 'input_patterns', {
    \ 'tex': g:vimtex#re#deoplete
    \})
```

**Comment by xarthurx** [comment]
I see. 
Sorry that I don't know `autocmd` very well.
Your suggestion works. 

Thank you.

**Comment by Shougo** [comment]
I have tested and this is works.

```vim
set rtp+=~/src/vim-plug
call plug#begin('~/work/test/plugged')

" register plug-in itself as plugin
Plug 'junegunn/vim-plug'

" auto-completion
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif

" LaTeX support
Plug 'lervag/vimtex', { 'for' : ['tex', 'latex', 'plaintex']}
autocmd User vimtex echomsg 'loaded'
autocmd User vimtex call deoplete#custom#var('omni', 'input_patterns', {
    \ 'tex': g:vimtex#re#deoplete
    \})

call plug#end()

" " Auto completion at startup
let g:deoplete#enable_at_startup = 1
" " Use smartcase.
call deoplete#custom#option('smart_case', v:true)
"
" " -- TeX
" " global settings
let g:tex_flavor='latex'
```

Please close the issue.

**Comment by lervag** [comment]
I see @Shougo already assisted: thanks!

Some general remarks from me:

1. vimtex is already a properly written filetype plugin which is by definition only loaded for tex files. Thus, you can make the following change:

    ```vim
    " Change this:
    Plug 'lervag/vimtex', { 'for' : ['tex', 'latex', 'plaintex']}

    " To this:
    Plug 'lervag/vimtex'
    ```

2. What is the point of this?

    ```vim
    autocmd! User vimtex echom 'vimtex is now loaded!'
    ```

    Vimtex does not define any event named `vimtex`. For the available events, see `:help vimtex-events`. Is this event defined by vim-plug, perhaps? Well, in that case, you don't need it! Read my point #1 above.

3. There is no change to vimtex that caused this problem (as far as I can remember). I would suggest that the issue instead came as a result of you changing your config, e.g. adding the `{ 'for': ...}` clause.

----

I see @Shougo suggests this:

```vim
Plug 'lervag/vimtex', { 'for' : ['tex', 'latex', 'plaintex']}
autocmd User vimtex echomsg 'loaded'
autocmd User vimtex call deoplete#custom#var('omni', 'input_patterns', {
    \ 'tex': g:vimtex#re#deoplete
    \})
```

As explained in my point #1, you should instead do this:

```vim
Plug 'lervag/vimtex'

" (remember, plug#end must come before calls to deoplete api)
call plug#end()
call deoplete#custom#var('omni', 'input_patterns', {
    \ 'tex': g:vimtex#re#deoplete
    \})
```
