### ISSUE TITLE
Include _fixme_ commands and environments in the TOC

### ISSUE THREAD

**Issue by donbex** [lervag/vimtex#1770]
**Is your feature request related to a problem? Please describe it.**
Fixme notes created with the [fixme](http://mirror.ox.ac.uk/sites/ctan.org/macros/latex/contrib/fixme/fixme.pdf) package do not appear in the TOC.

**Describe the solution you'd like**
Include the _fixme_ commands and environments in the TOC.

**Describe alternatives you've considered**
I looked into writing my own parser following the _toc_matcher_specification_, but I am not familiar with vimscript and I am having trouble wrapping my head around it.

**Additional context**
_fixme_ provides a series of commands and environments, with different signatures:
- Commands `\fxnote`, `\fxwarning`, `\fxerror`, `\fxfatal`, with signature _[\<options\>]{\<note\>}_;
- Starred versions of the same commands, with signature _[\<options\>]{\<note\>}{\<text\>}_;
- Environments `anfxnote`, `anfxwarning`, `anfxerror`, `anfxfatal`, with signature _[\<options\>]{\<summary\>}_;
- Starred versions of the same environments, with signature _[\<options\>]{\<summary\>}{\<text\>}_.

The entry text for the TOC item should be the content of _\<note\>_ for the commands, and _\<summary\>_ for the environments.

**Comment by lervag** [comment]
Thanks for the consise and clear description. I'm not familiar with the fixme package. Could you provide some samples for me so I can add some tests while adding this? A simple and short LaTeX file that shows a few variants of the commands/environments should suffice.

**Comment by donbex** [comment]
Here's a sample file. I tried to include an example of each command and environment. Note that _fixme_ also supports a `\fixme` command and a `afixme` environment, but I haven't included them since they are deprecated.

https://gist.github.com/donbex/04c83564cb8b622a1454922b99173a7f

**Comment by lervag** [comment]
Thanks! Sorry for taking so long. I found I had to rebase the ToC matcher code to make it easier to understand and work with. I've added initial support now, it's a little bit rough, but should be a good start. Can you test and give some feedback?

**Comment by donbex** [comment]
I tested this on the fixme notes in older revisions of my papers and so far it seems to work well. Thank you!
Is there anything in particular you need me to test?

**Comment by lervag** [comment]
Great, happy to hear it works. No, I don't need anything in particular tested. But let me know if you think things should "look" or behave differently.
