### ISSUE TITLE
Don't raise zathura after forward search

### ISSUE THREAD

**Issue by gaoqiangks** [lervag/vimtex#1773]
For most time, I don't want to raise zathura after a forward search.  So I refocus my terminal using the following code

```vim
function Focus_window(pid)
   "sleep 100m
   let search_cmd='xdotool search --pid '.a:pid
   let win_str=system(search_cmd)
   let win_list=split(win_str)
   for i in win_list
   let focus_cmd='xdotool windowfocus '.i
       call system(focus_cmd)
   endfor
endfunction
au User VimtexEventView call Focus_window(curr_window_pid)
"curr_window_pid is the process id of my current terminal and I use tilda.
```

However, this doesn't work unless I add the command `sleep 100m`  just at the beginning at the definition of the function `Focus_window`.  It seems like   forward search  is executed asynchronously.  I think `sleep 100m` is a bit awkward.  Is there any other way to realize this?

**Comment by lervag** [comment]
I would try something like this:

```vim
function! FocusWindow()
  if b:vimtex.viewer.xwin_exists()
    call system('xdotool windowfocus ' . b:vimtex.viewer.xwin_id)
  endif
endfunction

" Or simply
function! FocusWindow()
  call system('xdotool windowfocus ' . b:vimtex.viewer.xwin_id)
endfunction

" You should keep your autocmd's in augroup's
augroup vimrc
  " The first time you use the group, clear it:
  autocmd!

  " Now define your autocmd
  autocmd User VimtexEventView call FocusWindow()
augroup END
```

I  would expect this to work without `sleep`. Could you test it?

**Comment by gaoqiangks** [comment]
> I would try something like this:
> 
> ```viml
> function! FocusWindow()
>   if b:vimtex.viewer.xwin_exists()
>     call system('xdotool windowfocus ' . b:vimtex.viewer.xwin_id)
>   endif
> endfunction
> 
> " Or simply
> function! FocusWindow()
>   call system('xdotool windowfocus ' . b:vimtex.viewer.xwin_id)
> endfunction
> 
> " You should keep your autocmd's in augroup's
> augroup vimrc
>   " The first time you use the group, clear it:
>   autocmd!
> 
>   " Now define your autocmd
>   autocmd User VimtexEventView call FocusWindow()
> augroup END
> ```
> 
> I would expect this to work without `sleep`. Could you test it?

Thank you for your reply. But...sorry for my poor english. It seems that I didn't express myself clearly.  Actually, I want to keep my focus on the terminal.  I mean   I don't want to raise zathura after a forward search.  Since zathura doesn't supply this function as okular does, I have to refocus my terminal after a forward search.

**Comment by lervag** [comment]
Ah, sorry, I see. With Vim, you could perhaps use `v:windowid` for the xwindow ID. With neovim, this does not seem to work as well.

However, regarding your question: You need the `sleep` because vimtex uses background calls for the viewer. I.e., does something like this: `zathura ...opts &`. Thus, the event `VimtexEventView` may be activated before `zathura` actually opens the viewer or before your window manager properly displays it. However, I would think that you could decrease the sleep time. 100m sounds large.

**Comment by gaoqiangks** [comment]
I see.   Thank you very much~
By the way,  The windowid in vim seems to be a number to distinguish different tabs and windows in vim only, not the x-window ID.

**Comment by lervag** [comment]
No problem.

And no:

```
:help v:windowid
					*v:windowid* *windowid-variable*
v:windowid	When any X11 based GUI is running or when running in a
		terminal and Vim connects to the X server (|-X|) this will be
		set to the window ID.
		When an MS-Windows GUI is running this will be set to the
		window handle.
		Otherwise the value is zero.
		Note: for windows inside Vim use |winnr()| or |win_getid()|,
		see |window-ID|.
```
