### ISSUE TITLE
How to actually use VLTY?

### ISSUE THREAD

**Issue by rionda** [lervag/vimtex#1774]
**Issue**

The docs explain how to *configure* vimtex to use YaLafi and LanguageTool for grammar checking and so on, but not how to actually perform the grammar checking. I added set `show_suggestions` to `1` in `g:vimtex_grammar_vlty` but when I activate continuous compilation I don't see any suggestion in my quickfix or any sign anywhere suggesting that any grammar checking is being performed. `compiler vlty` gives no errors. 

So how is grammar checking actually performed?

**Comment by lervag** [comment]
Actually, the docs _do_ explain it. You need to read the start of the section, i.e. `:help vimtex-grammar`. :)

**Comment by rionda** [comment]
lol, don't know how I missed it. Sorry for the noise...

**Comment by lervag** [comment]
No problem, honest mistake. Feel free to reopen if you should have any further issues with this.
