### ISSUE TITLE
Add options to customize sections formatting in ToC window

### ISSUE THREAD

**Issue by n0ibe** [lervag/vimtex#1776]
**Is your feature request related to a problem? Please describe it.**

This is how I configured my ToC window
```
let g:vimtex_toc_show_preamble = 0
let g:vimtex_toc_config = {
  \ 'show_help': 0,
  \ 'tocdepth': 6,
  \ }
```
and this is an example of how it usually looks like

![2020-08-16@18:49:11](https://user-images.githubusercontent.com/59321248/90339471-3fe05400-dff1-11ea-8b4e-94c0b0b3a0e3.png)

As you can see there doesn't seem to be any visual distinction between chapters and sections, while subsections are barely visible because of my colorscheme and my terminal background color.

Also the title, `Table of contents`, looks the same as the title of the part.

**Describe the solution you'd like**

A possible solution would be to create highlight groups for parts, chapters, sections, subsections, subsubsections etc.., this way one could set colors and attributes like *italics*, **bold** or ***bold-italic***.

**Additional context**

As a sidenote, I'd be nice to have the `Table of contents` title flush left instead of being aligned with all the other ToC entries, maybe with a blank line between it and the first Toc entry. Imho that would give a bit more visual distinction.

**Comment by lervag** [comment]
Highlight groups are already available, just not well documented. All groups are defined here:

https://github.com/lervag/vimtex/blob/master/autoload/vimtex/toc.vim#L332

The sections are defined as `VimtexTocSec0` to `...4`. With this, you should be able to customize your colors as desired.

Regarding "Table of contents", it is _not_ a title, it is an entry to the line where you have `\tableofcontents` in your document.

**Comment by lervag** [comment]
And this is where the highlight groups are specified to default values:

https://github.com/lervag/vimtex/blob/ebb422c3c87c9f2cb333fac2b42b8e45ecc7f441/autoload/vimtex/options.vim#L434-L472

**Comment by n0ibe** [comment]
> Highlight groups are already available, just not well documented

Oh I see, I didn't bother checking the code itself, my bad.

On an unrelated note, is it possible to close the ToC window automatically once I close the buffer with the .tex file?

**Comment by lervag** [comment]
> On an unrelated note, is it possible to close the ToC window automatically once I close the buffer with the .tex file?

Yes, this should be possible. Something like this should suffice:

```vim
augroup vimtex_events
  au!
  au User VimtexEventQuit call b:vimtex.toc.close()
augroup END
```

I'll look into the indent idea. I agree it could make sense to allow this as an option.

**Comment by lervag** [comment]
Ok, I'm pushing an update that should allow you to set `g:vimtex_toc_config = {'indent_levels': 1}` to get indented ToC entries. Let me know what you think.

**Comment by n0ibe** [comment]
@lervag I think it looks great! Definitely a lot more useful than using different colors.

You're gonna hate me, but I have another idea for a possible improvement.

Now personally I don't like using `conceal` features when editing, I think they add an unnecessary level of abstraction and I'd rather see my file as what it is: plain text. However, I'd have no problems with concealing code in the ToC window.

Consider the following example:

```
\documentclass{article}
\usepackage{hyperref}

\begin{document}

\tableofcontents

\section{\texorpdfstring{$L^p$}{L\^{}p} spaces}

$L^p spaces$

\end{document}
```

The ToC looks like this

![2020-08-21@00:22:00](https://user-images.githubusercontent.com/59321248/90831594-603b4600-e344-11ea-8c2f-cb774e65707b.png)

yeah, not that great to look at. A possible option could be to only conceal text in the toc window, leaving concealing of the tex file managed by the `g:tex_conceal` variable. That toc entry could then look like this

![2020-08-21@00:26:13](https://user-images.githubusercontent.com/59321248/90831892-f5d6d580-e344-11ea-9037-864e122065aa.png)

which imho is a lot cleaner.

**Comment by lervag** [comment]
> You're gonna hate me, but I have another idea for a possible improvement.

Nope, no hate. But I'd be happy if you could raise this as a new issue/feature request, as I think it is off topic in this thread.

**Comment by n0ibe** [comment]
> But I'd be happy if you could raise this as a new issue/feature request, as I think it is off topic in this thread.

Done.

**Comment by n0ibe** [comment]
@lervag Is there a not too complicated way to reuse your code for assigning numbers in the ToC window for my own `foldtext` function?

I skimmed through the code in `autoload/vimtex/toc.vim` to see if I could just copy a couple of functions to do that, but every function seems to call five others.

**Comment by lervag** [comment]
Sort of, yes. I think the function `vimtex#toc#new` can be used relatively freely, and it will provide a lot of the necessary metadata. You can use it similar to how I use it [here](https://github.com/lervag/vimtex/blob/ec219646136de3040356b00d0dc74520950bd761/autoload/vimtex/fold/sections.vim#L80). I can understand that this is not trivial to read, but let me know if this helps already.

**Comment by n0ibe** [comment]
@lervag I guess I have to do something like

```
let toc = vimtex#toc#new()
let sec_num = toc.print_number(???)
```
but what arguments do I need to pass to `toc.print_number`? In the `foldtext` function all I have is the line number of the line where the fold starts, not much more.

**Comment by lervag** [comment]
v

**Comment by lervag** [comment]
The code is pretty much what I linked to. Simplified:

```vim
let toc = vimtex#toc#new({
    \ 'name' : 'Fold text ToC',
    \ 'layers' : ['content'],
    \ 'refresh_always' : 0,
    \})

call toc.get_entries(1)
let entries = filter(toc.get_visible_entries(), '!empty(v:val.number)')
call filter(entries, {_, x -> x.line == a:lnum && x.file ==# expand('%:p')})

return empty(entries) ? '' : toc.print_number(entries[0].number)
```

Note, here we removed the caching that is in the vimtex code I linked to. I think caching might be very useful here, but you could test if it works well enough already.

**Comment by n0ibe** [comment]
Works great!

![2020-09-06@12:24:20](https://user-images.githubusercontent.com/59321248/92323843-281e4d80-f03c-11ea-8224-0af48ed64906.png)

although the cursor now lags quite a bit when I'm scrolling between folded lines.

Also, as soon as I add or delete a line, all the fold numbers of the sections below that disappear, but they reappear once I save the document. I guess this is expected since we're using the line number in `call filter(...)`, correct?

**Comment by lervag** [comment]
> although the cursor now lags quite a bit when I'm scrolling between folded lines.

Yes, I think it is because the foldtext function is evaluated often. Thus, as I mentioned, you should probably cache the numbering as I've done in vimtex (see the function I linked to earlier).

> Also, as soon as I add or delete a line, all the fold numbers of the sections below that disappear, but they reappear once I save the document. I guess this is expected since we're using the line number in `call filter(...)`, correct?

Yes, exactly.

**Comment by n0ibe** [comment]
I don't think I'm caching the files in the right way. I first tried this

``` vim
if !exists('toc')
  let toc = vimtex#toc#new({
      \ 'name' : 'Fold text ToC',
      \ 'layers' : ['content'],
      \ 'refresh_always' : 0,
      \ })
  let file_updated = {}
  let toc_updated = 0
endif

let l:file = expand('%')
let l:ftime = getftime(l:file)

if l:ftime > get(file_updated, l:file) || localtime() > toc_updated + 300
  call toc.get_entries(1)
  let toc_entries = filter(toc.get_visible_entries(), '!empty(v:val.number)')
  let file_updated[l:file] = l:ftime
  let toc_updated = localtime()
endif
```
but I saw no improvements, I think because `toc`, `file_updated` and `toc_updated` are scoped within the function, so `!exists('toc')` is always true and I'm always executing the whole code.

I then tried to copy your code by appending a `dict` to the `foldtext` function definition, and modifying the above to

```vim
if !has_key(self, 'toc')
  let self.toc = vimtex#toc#new({
      \ 'name' : 'Fold text ToC',
      \ 'layers' : ['content'],
      \ 'refresh_always' : 0,
      \ })
  let self.file_updated = {}
  let self.toc_updated = 0
endif

let l:file = expand('%')
let l:ftime = getftime(l:file)

if l:ftime > get(self.file_updated, l:file) || localtime() > self.toc_updated + 300
  call self.toc.get_entries(1)
  let toc_entries = filter(self.toc.get_visible_entries(), '!empty(v:val.number)')
  let self.file_updated[l:file] = l:ftime
  let self.toc_updated = localtime()
endif
```

but that messes up the fold text completely.

**Comment by lervag** [comment]
Try this:

```vim
let s:cache = {
      \ 'toc_updated': 0,
      \ 'file_updated': {},
      \}

function! ParseLevel(lnum) abort " {{{1
  if !has_key(s:cache, 'toc')
    let s:cache.toc = vimtex#toc#new({
        \ 'name' : 'Fold text ToC',
        \ 'layers' : ['content'],
        \ 'refresh_always' : 0,
        \})
  endif

  let l:file = expand('%')
  let l:ftime = getftime(l:file)

  if l:ftime > get(s:cache.file_updated, l:file)
        \ || localtime() > s:cache.toc_updated + 300
    call s:cache.toc.get_entries(1)
    let s:cache.toc_entries = filter(
          \ s:cache.toc.get_visible_entries(),
          \ '!empty(v:val.number)')
    let s:cache.file_updated[l:file] = l:ftime
    let s:cache.toc_updated = localtime()
  endif

  let l:entries = filter(deepcopy(s:cache.toc_entries), 'v:val.line == a:lnum')
  if len(l:entries) > 1
    call filter(l:entries, "v:val.file ==# expand('%:p')")
  endif

  return empty(l:entries) ? '' : s:cache.toc.print_number(l:entries[0].number)
endfunction
```

The point here is to create a script local cache variable, `s:cache`. Add the TOC stuff inside it and use filedates for checking the cache.

I think this should work, but again, I can't promise.

----

By the way, why don't you just use vimtex foldtext?

**Comment by n0ibe** [comment]
> I think this should work, but again, I can't promise.

It does! The cursor doesn't lag anymore except when I scroll over `\begin{document}` and `\end{document}`, but I think that's caused by vimtex itself and not by the folding function.

> By the way, why don't you just use vimtex foldtext?

Mainly to improve my vim-fu. I'm learning a lot by bulding my own `foldexpr` and `foldtext` functions, plus I get to have a lot more control over every aspect of the the folding process.

**Comment by lervag** [comment]
> It does! The cursor doesn't lag anymore except when I scroll over `\begin{document}` and `\end{document}`, but I think that's caused by vimtex itself and not by the folding function.

Great, happy to hear it!

> Mainly to improve my vim-fu. I'm learning a lot by bulding my own `foldexpr` and `foldtext` functions, plus I get to have a lot more control over every aspect of the the folding process.

That's a good reason! :)

If you should have any suggestions for how to improve vimtex in this regards, feel free to open an issue/PR.

By the way, we've now discussed things that are clearly OT wrt. original post. Let's stop that here, but feel free to open a new issue if you want more similar discussions.
