### ISSUE TITLE
Disabling conceal also removes bold-italic syntax highlighting

### ISSUE THREAD

**Issue by n0ibe** [lervag/vimtex#1777]
**Issue**
I don't know if this is the intended behaviour, but disabling all concealment features with `let g:tex_conceal=''` also removes syntax highlighting for bold-italic blocks. This is what I see with conceal respectively on and off

![2020-08-18@16:48:29](https://user-images.githubusercontent.com/59321248/90528224-ad67be00-e172-11ea-8bdb-bec8fe39221c.png)

![2020-08-18@00:16:08](https://user-images.githubusercontent.com/59321248/90528237-b0fb4500-e172-11ea-9232-cdb82f8d8091.png)

**minimal.vim**

  ```vim
  let g:tex_conceal = ''
  ```

**minimal.tex**

  ```tex
\documentclass{article}
\begin{document}
\textit{This is italic} \textbf{This is bold} \textit{\textbf{This is bold-italic, but it looks italic}}.
\end{document}
  ```

**Observed Behaviour**

The text inside `\textit{\textbf{..}}` is highlighted in italic.

**Expected Behaviour**

The text inside `\textit{\textbf{..}}` is highlighted in bold-italic.

**Comment by lervag** [comment]
Thanks. I found there were some more inconsistensies, and I think I've fixed them all now. Please test.

**Comment by n0ibe** [comment]
Yes, ebc800e fixed it.

Just for my curiosity, why are some commands highlighted differently than others? For example in math mode

![2020-08-20@13:51:11](https://user-images.githubusercontent.com/59321248/90766711-466e1480-e2ec-11ea-9e08-9e4b016825e3.png)

**Comment by lervag** [comment]
Good question. However, this is not really a vimtex related question. The reason is that some of the commands are specifically matched as math commands, whereas the other are matched as the more general `texStatement` group. Or something similar. You can see the file with `:e $VIMRUNTIME/syntax/tex.vim`.

**Comment by n0ibe** [comment]
Thanks, I'll look into that.
