### ISSUE TITLE
Issue Compiling and E492

### ISSUE THREAD

**Issue by penguiny123** [lervag/vimtex#1784]
**Issue**
Hello, I'm very new to Linux, and I'm trying to set-up Vimtex, however, whenever I attempt to compile or even use :VimtexInfo, an E492: Not an editor command appears. 

**minimal.vim**
```vim
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'junegunn/seoul256.vim'
Plug 'lervag/vimtex'
call plug#end()

set conceallevel=1
let g:tex_conceal = 'abdmg'
let g:tex_flavor = 'latex'

let g:vimtex_compiler_latexmk=1
let g:vimtex_quickfix_mode=0
let g:vimtex_view_method='zathura'
```

```tex
\documentclass{article}
\begin{document}
\maketitle
\tableofcontents
\newpage

\section{Dummy}
Some text
\end{document}
```

**Commands/Input**
`:VimtexInfo`, `:VimtexCompile`

**Observed Behaviour**
```
E492: Not an editor command: VimtexInfo
```

**Output from VimtexInfo**
Vim Version:
```
> vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Apr 15 2020 06:40:31)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version without GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       -tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
-balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
-browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     -perl              -toolbar
+cindent           +job               +persistent_undo   +user_commands
-clientserver      +jumplist          +postscript        +vartabs
-clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        -lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con        +mksession         +smartindent       -X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             -xim
-dnd               -mouseshape        +startuptime       -xpm
-ebcdic            +mouse_dec         +statusline        -xsmp
+emacs_tags        +mouse_gpm         -sun_workshop      -xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: &quot;$VIM/vimrc&quot;
     user vimrc file: &quot;$HOME/.vimrc&quot;
 2nd user vimrc file: &quot;~/.vim/vimrc&quot;
      user exrc file: &quot;$HOME/.exrc&quot;
       defaults file: &quot;$VIMRUNTIME/defaults.vim&quot;
  fall-back for $VIM: &quot;/usr/share/vim&quot;
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H   -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-iU6mZD/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl     -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm
```

**Comment by lervag** [comment]
> Hello, I'm very new to Linux, and I'm trying to set-up Vimtex, ...

Welcome! Hope you will find a good experience!

Note, I took the liberty of "cleaning up" your original post with proper formatting. Feel free to inspect it to learn how to format comments, or read [the guide](https://guides.github.com/features/mastering-markdown/).

Note also that I cleaned up your vimrc and removed unnecessary comments (at least for this issue) and the unnecessary `let g:vimtex_view_general_viewer = 'zathura'`. Since you have `let g:vimtex_view_method = 'zathura'` the former option becomes irrelevant.

> ... however, whenever I attempt to compile or even use :VimtexInfo, an E492: Not an editor command appears.

Yes, I think it is because of an error in your vimrc file. I'm curious, why do you have this line?

```vim
let g:vimtex_compiler_latexmk=1
```

If you remove it, I think things will work. I'm curious, though, if the docs somehow give the impression that this is valid configuration?

**Comment by penguiny123** [comment]
Hello,
Thank you very much for the quick reply and formatting tips, I'll be sure to read up on them! I tried your suggestions and input the minimal vimrc, however, I still get the same E492 error when I attempt to compile. When I try to re-install Vimtex in vim-plug, it tells me it's already installed.
> I'm curious, why do you have this line?

I've been searching for my problem and I've been trying others' vimrc configurations and I believe I saw someone with this. The documentation upon further reflection does not give this impression as you've noted, thank you again.

**Comment by lervag** [comment]
> Thank you very much for the quick reply and formatting tips, I'll be sure to read up on them!

My pleasure :)

> I tried your suggestions and input the minimal vimrc, however, I still get the same E492 error when I attempt to compile.

The error implies that vimtex is not loaded. This means that 1) vimtex is not properly installed or 2) the filetype is not properly set.

Given the minimal vimrc and LaTeX file from your original post, can you do the following and show the various outputs?

1. `vim -u minimal.vim mwe.tex`
2. `:VimtexInfo`
2. `:echo &filetype`
3. `:scriptnames`

> > I'm curious, why do you have this line?
> 
> I've been searching for my problem and I've been trying others' vimrc configurations and I believe I saw someone with this. The documentation upon further reflection does not give this impression as you've noted, thank you again.

Good to hear. And yes, one should be catious when copying other peoples configuration, as you probably understand now. I try to always ensure I understand things that I copy before I actually do the copying.
