### ISSUE TITLE
VimtexRSearch not an editor command

### ISSUE THREAD

**Issue by Tyrn** [lervag/vimtex#1787]
Hi,

I've been using vimtex with Okular. After some idle time and updates, `<localleader>lr` command is working no longer. 
```
:VimtexRSearch
```
is `Not an editor command`. Autocomplete with `VimtexR` shows only `VimtexReload` and `VimtexReloadState`. 

Search is vimtex sources shows this:
`doc/vimtex.txt`:
```
2649::VimtexRSearch            Do reverse search (only available for MuPDF viewer).
```
`autoload/vimtex/view.vim`:
```
13:    command! -buffer -nargs=* VimtexRSearch
```
Is there a way to get the reverse search back?

**Comment by lervag** [comment]
> I've been using vimtex with Okular. After some idle time and updates, `<localleader>lr` command is working no longer.

`:VimtexRSearch` has never worked with Okular. As stated in the documentation:

```
                                             *VimtexRSearch*
                                             *<plug>(vimtex-reverse-search)*
:VimtexRSearch            Do reverse search (only available for MuPDF viewer).
```

Specifically: "Only available for MuPDF viewer".

For configuration of Okular, see `:help vimtex_viewer_okular`.
