### ISSUE TITLE
Add Evince Forward and Reverse Searching Support to Vimtex?

### ISSUE THREAD

**Issue by gkapfham** [lervag/vimtex#179]
Once again, thanks for all of your efforts in implementing vimtex!

 I regularly use this vim plugin to edit large LaTeX documents. I have noticed that vimtex supports forward searching with Zathura and MuPDF --- for those of us who use Linux --- and other viewers for other operating systems. Yet, I regret that I have never been able to get forward or reverse searching to work correctly with these tools. 

Would you consider adding forward and reverse searching with `evince`? This feature works correctly in the Tex-9 plugin. In fact, I have been using both vimtex (for all of the great features that it provides) and Tex-9 (for forward and reverse searching) along with Evince when I have been recently editing LaTeX documents.

With that said, this feature request is not a pressing one! I would much prefer your feedback on and the successful resolution of issues #176, #177, and #178.

Thanks in advance for any insights or new features that you can provide.

**Comment by lervag** [comment]
I would love to add support for evince. However, it seems evince does not support this from the command line, which makes the implementation much less straightforward. And considering I do not have that much time lately, I think I will leave this for now.

If anyone would be able to provide a very specific recipe for how this can be done, then I might do it. Else I will be happy to consider and accept pull requests.

**Comment by archdria** [comment]
TeX-9 supports evince through the d-bus interface.
It's the only think preventing me from using this plug-in instead...
https://github.com/vim-scripts/TeX-9/blob/master/ftplugin/tex_nine/tex_nine_synctex.py
Hope it helps. Thank you!

**Comment by lervag** [comment]
Thanks, I've already seen TeX-9's approach. However, it is not clear how to extract the minimal amount of code to achieve the evince sync. I've found a couple of things that could help, but I'm not sure how to do it in a vimtex-ish manner.

In the meantime I suggest you try `zathura`. I much prefer it over evince!

**Comment by lervag** [comment]
Ok, so I've investigated this some more. I see there are several plugins for both vim and other editors that implement support for Evince. However, I find all of the solutions to involve ALOT of code, and it seems like the complexity is high for this simple problem. As I can't find a relatively simple way to implement this, I am sorry to say that I choose to not implement support for evince at this time.

I will consider pull requests, as mentioned. And if anyone will provide a very simple and barebones solution that will be straightforward to implement, then I might consider to implement it myself. In the meantime, I will close this issue with the won't fix-label.

Personally, I think both mupdf, zathura, okular, and qpdfview are good alternatives to evince.

**Comment by coxackie** [comment]
@lervag Sorry for "necromancing" here; I opened yesterday an issue with evince about better synctex support [here](https://gitlab.gnome.org/GNOME/evince/-/issues/1535#note_989594). It would be good if you could give your 5 cents there; the devs may be inclined to make some changes and get the situation better, not only for this plugin, but in general.

**Comment by lervag** [comment]
I'm not sure if I want to register at the Gnome gitlab org to leave a comment. I'm not personally interested in either Gnome nor Evince. But I won't mind collaborating to make Vimtex work better with Evince. If there is an "easy" way to work through dbus from Vim then that might work, else I also think that it would be convenient with command line options as you've suggested (i.e., similar to Zathura).

**Comment by lervag** [comment]
Ok, sure; I noticed I did not need to create a new account. I can use my Github account. So I've added an initial comment now and I'll be following the thread.

**Comment by davidlowryduda** [comment]
In case someone comes across this later, I'll note that I use https://github.com/peterbjorgensen/sved (which adds forward and backward search through dbus) side by side with vimtex. It works well for me.

**Comment by lervag** [comment]
Feel free to consider if it would be interesting to add some tips to the relevant parts of the docs (e.g. `:help vimtex_viewer_evince`) - and if so, feel free to suggest changes by PR! :)

**Comment by aloispichler** [comment]
Thank you! Works perfect for me!

**Comment by 14mRh4X0r** [comment]
I took some time to hack together an [evince view implementation](https://gist.github.com/14mRh4X0r/5819f10a45013280f3c7abd27b8ae1cd). It doesn't support NeoVIM, and as such I don't think it makes sense to open a PR for it, but it could be used as a basis.
