### ISSUE TITLE
Remove vim-polyglot notice from help page. Vim-polyglot removed all of its latex-related files

### ISSUE THREAD

**Issue by AlxHnr** [lervag/vimtex#1790]
**Issue**

[Vim-polyglot](https://github.com/sheerun/vim-polyglot) does not ship LaTeX related syntax files anymore (see [a9cc6f](https://github.com/sheerun/vim-polyglot/commit/a9cc6fd2188ddc37257c834b6f5a5fa86d0eebd5)). The note in the help page is confusing and implies there is some conflict between these two plugins. This _may_ lead people to spend time fiddling with `let g:polyglot_disabled = [ 'latex' ]` and the like, which is not necessary anymore.

**Comment by lervag** [comment]
Thanks for the notice! However, 

> I've removed latex from vim-polyglot, it causes to many issues. **We need some simple plugin with basic syntax and indent instead.**

@sheerun indicates he wants to add some simple plugin for LaTeX. If I remove the polyglot guards and notices in vimtex, then they may suddenly become relevant again in the future. I still strongly recommend that people explicitly installs the plugins they want and need, instead of installing them in bulk through vim-polyglot.

**Comment by lervag** [comment]
But OK, I'll remove the notices and guards for now, and instead add them again in the future if I find it necessary.

**Comment by sheerun** [comment]
vimtext is not meant to be in vim-polyglot, even if only because you needed to put `g:polyglot_disabled = ["latex"]` here :) vim-polyglot should not interfere with extra language packs and clearly it did in this case

**Comment by krishnakumarg1984** [comment]
I think now polyglot uses vimtex as its Latex language plugin?

**Comment by sheerun** [comment]
We don't include one because no plugin I've found supports just highlighting and indentation. There are always some advanced featres

**Comment by lervag** [comment]
> I think now polyglot uses vimtex as its Latex language plugin?

No, as implied by @sheerun, polyglot no longer ships with a LaTeX filetype plugin.
