### ISSUE TITLE
Customize conceal for additional commands, like \textsubscript and \textsuperscript

### ISSUE THREAD

**Issue by TonyWu20** [lervag/vimtex#1792]
**Is your feature request related to a problem? Please describe it.**

No.

**Describe the solution you'd like**

I'd like to be able to add customized conceal for own purpose. Ex., I'm writing with a huge load of usage of \textsubscript and \textsuperscript in consideration of my future pandoc conversion to docx, which does not handles the font in math mode well automatically. So the \textsubscript or my alias \tsub is flooding over my vim interface.

**Comment by lervag** [comment]
> I'd like to be able to add customized conceal for own purpose.

Sorry, I can't help you with this. I don't think Vim's conceal feature is powerful enough. The subscript and superscript conceals are defined in `:e $VIMRUNTIME/syntax/tex.vim` in a section near line 1000. However, adapting this to support something like `\cmd{content}` seems very difficult (or impossible).

**Comment by krishnakumarg1984** [comment]
This never works for me. The conceal feature is not powerful at all.
