### ISSUE TITLE
Support light latex make build tool presented first at TUG 2020

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1797]
A shiny new compiler backend has been released on CTAN i.e. yet another compiler automation solution akin to the likes of `latexmk`,`arara`, and `latexrun`.  This one is called `llmk` which stands for **Light Latex Make**, and was well received at the recently concluded TUG2020 (a conference always attended by stalwarts of the TeX world).

- [Link to CTAN project](https://ctan.org/pkg/light-latex-make)
 - [Youtube demo video from TUG 2020](https://www.youtube.com/watch?reload=9&v=kzqlNHKmzBo)

The package documentation specifically describes the differences from `latexmk` and `arara`. This GitHub issue is therefore a placeholder for the main contributors here to evaluate whether `vimtex` can callback to this automation tool, and if it is indeed required or not.  Since `vimtex` is modular by design, I assume this is not a huge technical challenge to include another compiler backend. 

Here's the CTAN summary describing the program.

> This program is yet another build tool specific for LaTeX documents. Its aim is to provide a simple way to specify a workflow of processing LaTeX documents and encourage people to always explicitly show the right workflow for each document.
>
>The main features of the executable llmk are all about the above purpose. First, you can describe the workflows either in an external file llmk.toml or in a LaTeX document source in the form of magic comments. Further, multiple magic comment formats can be used. Second, it is fully cross-platform. The only requirement of the program is the texlua command; llmk provides a uniform way to describe the workflows available for nearly all TeX environments. Third, it behaves exactly the same in any environment. At this point, llmk intentionally does not provide any method for user configuration. Therefore one can guarantee that for a LaTeX document with an llmk setup, the process of typesetting the document will be reproduced in any TeX environment with the program.

**Comment by lervag** [comment]
Thanks for the notification and info. I'll "ignore" this for now, but keep it open. If it gets more traffic and interest I'll consider to work with adding support, and of course, I'll be happy to consider and assist on related pull requests.

**Comment by lervag** [comment]
Notice that the new generic compiler backend _can_ probably be used with light latex make, see `:help vimtex-generic-compiler` and #1898. This is still a WIP, but I think it is relevant.

**Comment by krishnakumarg1984** [comment]
Great to know about the generic compiler backend.

I notice that vimtex supports specific compilation tools such as `arara` in addition to `latexmk`.  A simplied version of `arara` known as [`spix`](https://ctan.org/pkg/spix) has been released. Can the `arara` backend be reused for `spix`?

**Comment by lervag** [comment]
> I notice that vimtex supports specific compilation tools such as `arara` in addition to `latexmk`. A simplied version of `arara` known as [`spix`](https://ctan.org/pkg/spix) has been released. Can the `arara` backend be reused for `spix`?

I mean, everything is possible, but I do not have any specific goal of supporting everything. There is a clear limit to my time, and adding support for compiler backends is a little bit complicated. So, unless there is a very specific interest I will not spend time on adding support for spix. I would rather spend time on making the generic backend better, as that seems more worth the effort. That is, I imagine it should be possible to specify a generic compiler backend that allows customization through hooks and callbacks.

As such, I would imagine that the generic backend should be usable also for this light latex tool. By improving the generic backend, it would have a wider range of benefits, I think.

**Comment by krishnakumarg1984** [comment]
Agree. Can you perhaps just mention some of these backends in the documentation for the generic backend?

**Comment by lervag** [comment]
Yeah, that sounds good. I'll do that.

**Comment by krishnakumarg1984** [comment]
Thanks a lot. Do you think we can close this issue now?

**Comment by lervag** [comment]
Yes, I think that's OK. There's still an open issue for the generic compiler: #1898. I'll not close that one until things are more mature.

**Comment by lervag** [comment]
See also #2021 that I just opened to summarize current tasks for my future self.

**Comment by krishnakumarg1984** [comment]
Cool. Thanks a lot Karl.
