### ISSUE TITLE
Tex-specific color schemes

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#1800]
*(This may be less of a feature request than a request for comments and suggestions. I'm also bringing this up now because it might inform the syntax file re-write in #1799.)*

**TL;DR** I'm fed up with looking for color schemes that both look appealing (to me) and highlight TeX code (which I spent about 90% of my time in vim looking at) correctly, so I want to write one that is specifically tuned to TeX.

As far as I understand it, the situation regarding color schemes is roughly the following:

1. The builtin syntax file defines a number of (very) TeX-specific syntax groups via regular expressions.
2. It then links these to a (smaller) number of TeX-specific highlight groups.
3. It *then* links these to an (even smaller) number of more-or-less standard generic highlight groups.
4. (On top of that, vimtex defines even more TeX-specific syntax groups and links them to either specific or generic highlight groups.)
5. Color schemes assign colors to (some) of these generic highlight groups and link other groups to these.

This often leads to inconsistent (and inefficient, but that's less of a concern) highlighting, say, for braces or labels. I am therefore looking to short-circuit this by assigning colors directly to a set of generic *but TeX-specific* highlight groups (which need to be defined first), in particular bypassing the lossy steps 3 and 5.

Roughly, I'd like to distinguish at a glance

* comments,
* math mode contents,
* text mode contents,
* TeX commands and environments,
* labels and references,
* delimiters (braces and backslashes)

Ideally, commands and environments in math and text mode would be colored differently (so that I could have, e.g., dark green commands in math mode that is otherwise colored light green, while commands in text mode would be light blue to only slightly stand out from white on dark text).

What I'd like to ask for here is

a) a bit of explanation and/or documentation of the different syntax/highlight groups vimtex uses (esp. in step 4, which is not so easy to fully understand from the code),
b) some advice which groups would be good to use or define for this purpose (or even adding the latter in vimtex, if this whole thing seems useful for others as well),
c) suggestions for good color schemes (or other advice) from others.

(For the record, the only color schemes I've liked so far for TeX were https://github.com/mhartington/oceanic-next and https://cocopon.github.io/iceberg.vim/ (with some tweaks).)

**Comment by krishnakumarg1984** [comment]
Like clason, I haven't had great success with finding the best readable TeX specific colorscheme for vim.

**Comment by clason** [comment]
For the record, here are all the syntax groups in `autoload/syntax` I found that are linked directly to generic highlight groups instead of tex-specific ones (i.e., of the form `texXXX`):
```
p/hyperref.vim
29:  highlight link texUrl          Function

p/tikz.vim
38:  highlight def link texTikzEqual Operator
39:  highlight def link texTikzSemicolon Delimiter

p/tabularx.vim
66:  highlight def link texTabularCol        Directory
67:  highlight def link texTabularAtSep      Type
68:  highlight def link texTabularVertline   Type
69:  highlight def link texTabularPostPre    Type
70:  highlight def link texMathDelimSingle   Delimiter

p/beamer.vim
24:  highlight link texBeamerOpt Identifier
25:  highlight link texBeamerDelimiter Delimiter

load.vim
77:  highlight def link texDefParmNested Identifier
87:  highlight def link texCommentURL Comment
88:  highlight def link texCommentAcronym Comment
```

**Comment by clason** [comment]
I'm currently going through some TeX files and using the following code (which everyone else probably knows already) to check which highlight groups are actually used:
```vim
function! SynGroup()
    let l:s = synID(line('.'), col('.'), 1)
    echo synIDattr(l:s, 'name') . ' -> ' . synIDattr(synIDtrans(l:s), 'name')
endfun
```
One thing I noticed is that the `begin` in `\begin{equation}` is a `texStatement`, while the `begin` in `\begin{lemma}` is a `texBeginEnd` (both are linked to `Statement`, so one wouldn't see the difference at first, but it shows up of course when you want to relink them). Is this intentional or necessary due to the way these are set up?

**Comment by lervag** [comment]
> As far as I understand it, the situation regarding color schemes is roughly the following:
> 
>     1. The builtin syntax file defines a number of (very) TeX-specific syntax groups via regular expressions.
> 
>     2. It then links these to a (smaller) number of TeX-specific highlight groups.
> 
>     3. It _then_ links these to an (even smaller) number of more-or-less standard generic highlight groups.
> 
>     4. (On top of that, vimtex defines even more TeX-specific syntax groups and links them to either specific or generic highlight groups.)
> 
>     5. Color schemes assign colors to (some) of these generic highlight groups and link other groups to these.

Sounds about right. :)

> Roughly, I'd like to distinguish at a glance
> 
>     * comments,
> 
>     * math mode contents,
> 
>     * text mode contents,
> 
>     * TeX commands and environments,
> 
>     * labels and references,
> 
>     * delimiters (braces and backslashes)

I think essentially, what you are asking, is for the syntax script to be more consistent. This is something I'm also looking into now, as you know, in #1799. I've come a long way in making the code more consistent, and I still have some more tasks before I start to make "the big changes". But when I do, I think a part of it will be to redefine the syntax groups. This is actually a huge change, because it means that TeX syntax will end up looking different. It requires that we think things out carefully, and I would appreciate some help with that.

In a sense, I think this issue is strongly connected with what I consider to be _phase 2_ in #1799.

I won't answer your more specific questions, since it should be partly answered as a result of #1799. That is, that the syntax groups should be more consistent, better named, and easier to understand.

I'm not going to have a strong opinion on the actual colors/color schemes. I personally use Solarized and I'm happy with it. I agree that LaTeX is not optimally colored, though, but I want to fix this "upstream" first, and then allow color-scheme authors to continue to build on top of it after.

**Comment by lervag** [comment]
> I'll just list some things I noticed which might be improved:

Very god list, I'll have it in mind in my current work. I'll also appreciate similar types of input when #1799 is progressing.

**Comment by krishnakumarg1984** [comment]
@lervag I have a question.

Did any of the latest syntax-related commits break functionality?

Right now, when I open a tex file, I am facing huge delays of upto 10 seconds before the monochrome text of the buffer colours up!

**Comment by lervag** [comment]
> Did any of the latest syntax-related commits break functionality?

Probably! But it should not affect you unless you have defined `g:vimtex_syntax_alpha`. And this is of course only meant to be used if you want to be bold. :)

Feel free to be more specific and open a new issue, though.

**Comment by clason** [comment]
> I won't answer your more specific questions, since it should be partly answered as a result of #1799. That is, that the syntax groups should be more consistent, better named, and easier to understand.

I completely agree (even going so far as writing "fully answered"). 

>  I agree that LaTeX is not optimally colored, though, but I want to fix this "upstream" first, and then allow color-scheme authors to continue to build on top of it after.

Color-scheme authors, or users re-linking the tex-specific groups directly to the defined colors.

Just as a teaser, here's a before and after short with the current syntax file (which doesn't break for me, btw) and hand-tweaked tex highlight groups:
<img width="892" alt="Screenshot 2020-10-05 at 23 25 59" src="https://user-images.githubusercontent.com/2361214/95133790-2393a480-0762-11eb-8766-016237667442.png">
<img width="892" alt="Screenshot 2020-10-05 at 23 25 22" src="https://user-images.githubusercontent.com/2361214/95133721-0bbc2080-0762-11eb-9262-6f76326f7cbc.png">

**Comment by lervag** [comment]
@krishnakumarg1984 It has not broken for me. Please, as I already suggested, open a new issue and describe your problem in full and provide e.g. a minimal vimrc and latex example. Also, it would be useful to know which commit you've found by bisection introduces the problem.

**Comment by lervag** [comment]
@clason As I've opened #1834 and started to work on the full merge of syntax support, I'd like to ask you to move some of your main concerns from this issue into suggestions for #1834. We are now "free" to do whatever we want, as there are no longer any links to the old syntax scripts.

I'd like the focus currently to be on the syntax groups, not on highlighting. Then we can have a new discussion later on how to link the tex syntax groups to defaults later.

Note, I think the code should now be (or at least I aim for it to be) quite easy to read:

* The main rules are applied [here](https://github.com/lervag/vimtex/blob/feat/syntax/autoload/vimtex/syntax/core.vim#L7).

* The highlight rules are [in this function](https://github.com/lervag/vimtex/blob/feat/syntax/autoload/vimtex/syntax/core.vim#L442).

I hope you don't mind that I close this issue, as I think it is intrinsic to #1834.

**Comment by clason** [comment]
@lervag I can do that, but

> I'd like the focus currently to be on the syntax groups, not on highlighting. Then we can have a new discussion later on how to link the tex syntax groups to defaults later.

Doesn't that mean that this issue is also separate? I agree that it is predicated on the work in #1834, but that PR in itself will not address this (fully). Or do you want me to reopen this issue when #1834 is merged?

**Comment by lervag** [comment]
> Doesn't that mean that this issue is also separate? I agree that it is predicated on the work in #1834, but that PR in itself will not address this (fully). Or do you want me to reopen this issue when #1834 is merged?

What I was thinking was that we should first mold the syntax stuff and make it more concise/efficient, consistent, and better. When it is becoming "stable", then it makes sense to specify some default colors based on the "main" highlight groups (e.g. `Type`, `Error`, etc). It might not fully address your thoughts in this issue, and I think it could be better to open a new issue after in that case. Does that sound OK?

**Comment by clason** [comment]
Makes sense 👍 

The main issue for me is consistent syntax and highlight groups. I don't think it's possible to find default colors for highlight groups that work well with every color scheme, so that step (e.g., `texRefZone` -> `Constant`) is probably best left for color schemes or personal configs.

If you plan to tackle -- as I now think you intend to -- _highlight_ groups as well as syntax groups in #1834, then that's fine,  I just misunderstood.

**Comment by lervag** [comment]
No problem; and I agree, color schemes will probably want to fine tune things no matter how we define things. But we should have some simple, sensible defaults that should look "good enough" in most color schemes, or at least try to.

**Comment by lervag** [comment]
For fun, my current color scheme (a slightly modified solarized theme) with some customizations.

![2020-12-05_18:23_screenshot](https://user-images.githubusercontent.com/998898/101259232-ea5abf00-3727-11eb-8cf3-8946dcbe3014.png)

**Comment by ronakmsoni** [comment]
Just stumbled into this. Are there any good colorschemes now that use all these syntax groups? Most I've found seem to have the problems @clason mentioned in the OP; weirdly, the morning and evening colorschemes packaged with vim seem to be the only ones that have distinctive colours for the latex groups.

**Comment by lervag** [comment]
To be honest, I don't really know. I use my own custom colorscheme. 🤷🏻

**Comment by ronakmsoni** [comment]
Recording my solution here for anyone stumbling onto this, and who is (like me) bad at picking specific colours and/or doesn't want to make an entire custom colorscheme.

I'm using [navarasu/onedark.nvim](https://github.com/navarasu/onedark.nvim), but I tried a few others and this solution made all of them better.

```VimL
augroup texcolors
	au!
	au ColorScheme * highlight! link Conceal       Special 
	au ColorScheme * highlight! link texCmdGreek   Special
	au ColorScheme * highlight! link texMathOper   texDelim
	au ColorScheme * highlight! link texMathDelim  texDelim
	au ColorScheme * highlight texDelim gui=bold guifg=#8ebd6b "See below
augroup end
```
For the last line:
- Choose a nice color from the palette of your colorscheme here. I used [telescope](https://github.com/nvim-telescope/telescope.nvim), specifically the command `:Telescope highlights` to explore the palette. For vanilla vim, you can use the commands [here](https://jordanelver.co.uk/blog/2015/05/27/working-with-vim-colorschemes/). 
- If you delete this line, texDelim in linked to (has the same highlighting as) Delim; I personally dislike this, since many colourscheme give delimiters less prominent colours and being able to see brackets clearly in math equations is helpful.
- I have `set termguicolors` in my config. If you don't, or if you use a terminal without truecolor support, you want to use `ctermfg` instead of `guifg`.

---

For me these customisations change it from
<img width="887" alt="image" src="https://github.com/lervag/vimtex/assets/38462423/029233e2-dccd-400d-ac98-e5c142071458">
to
<img width="865" alt="image" src="https://github.com/lervag/vimtex/assets/38462423/a4a97654-2c4a-43b1-a6ac-15a1782a73ba">
(I also turned off background colors in the same augroup)

**Comment by lervag** [comment]
Thanks, that seems like good advice for others who want to customize. I also want to stress that there are several useful resources and tips to anyone who wants to customize their colors in the docs, see `:help vimtex-syntax-core`.

**Comment by ronakmsoni** [comment]
Oh wow, I wish I had run into that two weeks ago lol. Should have known you would have put together a good explainer already. Thanks again for everything! (:

**Comment by lervag** [comment]
Yes, sorry; the docs are very long and I know that makes it hard for people to discover things. I believe one of the most useful tricks to learn, in general, is to learn how to skim and read documentation. It is fascinating how many tools and programs that have very good documentation!

In any case; thanks for the kind words!
