### ISSUE TITLE
Textidote: option to provide all command line arguments

### ISSUE THREAD

**Issue by bratekarate** [lervag/vimtex#1801]
First of all thank you so much for this great plugin. I came from Latex-Suite and always felt like somethign was amiss. Turns out it was vimtex. With `coc-vimtex`, `coc-snippets` and `UltiSnips` it is a lot of fun to use. However, there is one thing that is not quite solved very well in my view with coc or ALE. And that is grammar and spellchecks.

**Is your feature request related to a problem? Please describe it.**
I use a heavily customized textidote command with many options, which also  -- most importantly -- reads a dictionary file for ignore words. Without this option, a lot of noise appears in the log. The second most unfortunate thing is that I can not use the n-gram language model files I use normally. They provide much better spelling and grammar checks.

**Describe the solution you'd like**
I would go for the easiest solution that still allows to customize the execute command. I don't want anything fancy integrated, just the possiblity to provide options. Others may disagree, but I don't even need it foolproof. I am happy to provide the entire command myself, without multiple options in one variable. 

If it should be a little safer to use for newer users that don't know the quirks, there could be some mandatory options (like `--output singleline` and `--no-color`) that are simply complemented by the user variable, something like `g:vimtex_textidote_command_options`.

**Describe alternatives you've considered**
I am currently using ALE, which was a pain to integrate and kind of works now. But my configuration is very bloated due to ALE trying to enable many functions by default that don't work well for me. I would rather get rid of ALE entirely, as I normally use `coc-vimtex` for the completion.

I also have configured a textidote linter for `coc-diagnostic-languageserver`. Yes, I have configured this now in coc, ALE and vimtex, and I am still not completely happy. 

I feel like coc and vimtex are the best solution together, but not for textidote or LanguageTool! This is a special usecase, because languagetool is so CPU and memory heavy, it does not make sense to use it like the other diagnostics of coc. 

It is impossible to disable the `coc-diagnostic-languageserver`'s auto-linting, at least according to the main dev of coc. I can link the issue if I find the time. 

I would be happy to contribute as I think by now I got accquainted to quite some of the inner workings of languagetool, textidote and vim plugins. I already fixed and adapted an ALE PR for textidote for my personal use. Right now I am short on time because I'm writing my thesis (with vimtex), but after that I could also issue a PR. Just want to know first if a PR is wanted, i.e. worth the time to invest.

**Comment by Konfekt** [comment]
> Describe the solution you'd like
I would go for the easiest solution that still allows to customize the execute command. I don't want anything fancy integrated, just the possibility to provide options.

This should already be possible simply by appending the command arguments to `g:vimtex_textidote_jar`. If this works out fine for you, one could mention this in the documentation (and possibly rename the variable).

**Comment by Konfekt** [comment]
For reference:

```vim
" compiler/textidote.vim (lines 22-24)
let &l:makeprg = s:textidote_cmd
      \ . ' --no-color --output singleline --check '
      \ . matchstr(&spelllang, '^\a\a') . ' %:S'
```

**Comment by bratekarate** [comment]
Thanks for checking on this issue. I tried to do it this way, but it does not work. Maybe I am doing it wrong?

I used `let g:vimtex_textidote_jar = <PATH_TO_JAR --remove-macros todo`.

When running `compiler textidote | make`, I get the following error:

```
Error detected while processing /.../vim/plugged/vimtex/compiler/textidot
e.vim:                                                                            
line   12:
To use the textidote compiler, please set g:vimtex_textidote_jar to the path of textidote.ja
r!
```
And this makes sense, because of
```
" compiler/textidote.vim (lines 7-8)
if exists('g:vimtex_textidote_jar')
      \ && filereadable(fnamemodify(g:vimtex_textidote_jar, ':p'))
...
```
So it seems as though `g:vimtex_textidote_jar` must be a file path, otherwise the check fails.

Maybe I misunderstood you and you mean I should modify `compiler/textidote` myself?

Also, not sure if it matters, but the line numbers of your excerpts are different in my version. For me, they are at lines 9-10 and 17-18.

Finally, the `.textidote` config file I use in the project directory kind of circumvents the issue, by putting all CLI arguments in there. But this is only useful for project specific CLI settings, and they cannot be changed programatically. Sometimes I need to append or remove the `--read-all` flag at runtime. 

Also, I use `~` paths in that file, which somehow does not work with the vimtex compiler, but works with CLI.

**Comment by Konfekt** [comment]
Indeed, I overlooked that the check makes it fail; well observed, my bad. Appending the arguments to the jar path is a bad idea anyway due to possible spaces in the file path. 

So an appended string `g:vimtex_textidote_args` would be the easiest way to solve this issue; how about it, @lervag ?

**Comment by lervag** [comment]
Thanks for the discussion to both, and to @Konfekt for the suggestions! I've updated the textidote interface somewhat, including a change of the option name - it is now called `g:vimtex_grammar_textidote` to be more consise with the `vlty` checker. This should resolve this issue. Let me know what you think.

**Comment by bratekarate** [comment]
First thank you for fast reaction! Unfortunately the `args` key is not respected. This is because `exists(dictionary.key)` will always return 0. I changed it to `has_key` and it works. I submitted a PR. #1804 

A persisting issue for me is that the language is not configurable. I am using British English, and it is not possible to configure it with the current API. `en` will be mapped to `en-US` by textidote behind the scenes. I submitted a PR as a suggestion for this issue, where `&spelllang` is mapped to a format textidote understands. I checked the source code of textidote, the only outlier is `en_gb` -> `en_UK` (as of now...). So the solution handles all known cases so far.  #1805

If the language solution seems not stable enough, I would also be happy to provide a language variable that overrides `&spelllang`.

**Comment by lervag** [comment]
> First thank you for fast reaction! Unfortunately the `args` key is not respected. This is because `exists(dictionary.key)` will always return 0. I changed it to `has_key` and it works. I submitted a PR. #1804

Good catch, thanks!

> A persisting issue for me is that the language is not configurable. I am using British English, and it is not possible to configure it with the current API. `en` will be mapped to `en-US` by textidote behind the scenes. I submitted a PR as a suggestion for this issue, where `&spelllang` is mapped to a format textidote understands. I checked the source code of textidote, the only outlier is `en_gb` -> `en_UK` (as of now...). So the solution handles all known cases so far. #1805

> If the language solution seems not stable enough, I would also be happy to provide a language variable that overrides `&spelllang`.

Thanks! I'll look into it. Let's continue the discussion in #1805.
