### ISSUE TITLE
Save custom .sty file cause vim error when compiler is running

### ISSUE THREAD

**Issue by ZhiyuanLck** [lervag/vimtex#1808]
**Issue**
I'm writting my own package. And I need to test the package in `test.tex`, so I include my package in the same folder and start compiling in continuous mode.

Then when I do some change in `mypackage.sty` and save it, vim complains that
```txt
Error detected while processing function <SNR>130_callback_continuous_output:
E716: Key not present in Dictionary: compiler.output
E116: Invalid arguments for function filewritable (b:vimtex.compiler.output)
```
**test.tex**

```tex
\documentclass{minimal}
\usepackage{mypackage}

\begin{document}
  Hello world!
\end{document}
```

**mypackage.sty**
```tex
\RequirePackage{expl3}
\ProvidesExplPackage
  {mypackage}
  {2020/09/27}
  {v1}
  {test}

\file_input_stop:
```

**Comment by lervag** [comment]
> Then when I do some change in `mypackage.sty` and save it, vim complains that ...

I'm sorry, but I need more details:

1. Please provide the output of `:VimtexInfo`.
2. Please explain the steps you do to reproduce the issue. E.g. i) start Vim with `vim -u minimal.vim test.tex`, ii) start compiltion with `\ll`, iii) open `mypackage.sty` and make a change.

I've also implied that I'd like a minimal vimrc file `minimal.vim`. This could
be e.g.

```vim
set nocompatible
" Update path here
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:tex_flavor = 'latex'
let g:vimtex_options = values
```

**Comment by ZhiyuanLck** [comment]
## Files
**test.tex**
```tex
\documentclass{minimal}
\usepackage{mypackage}

\begin{document}
  Hello world!
\end{document}
```

**mypackage.sty**
```tex
\RequirePackage{expl3}
\ProvidesExplPackage
  {mypackage}
  {2020/09/27}
  {v1}
  {test}

\file_input_stop:
```

**minimal.vim**
```vim
set nocompatible
" Update path here
let &rtp = '~/.vim/bundles/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundles/vimtex/after'
filetype plugin indent on
syntax enable

let g:tex_flavor='latex'
let g:vimtex_compiler_latexmk_engines = {
  \ '_'        : '-xelatex --shell-escape',
  \ 'pdflatex'     : '-pdf',
  \ 'dvipdfex'     : '-pdfdvi',
  \ 'lualatex'     : '-lualatex',
  \ 'xelatex'      : '-xelatex --shell-escape',
  \ 'context (pdftex)' : '-pdf -pdflatex=texexec',
  \ 'context (luatex)' : '-pdf -pdflatex=context',
  \ 'context (xetex)'  : '-pdf -pdflatex=''texexec --xtx''',
  \}
let g:vimtex_compiler_latexmk = {
  \ 'backend' : 'jobs',
  \ 'background' : 1,
  \ 'callback' : 1,
  \ 'continuous' : 1,
  \ 'executable' : 'latexmk',
  \ 'options': [
  \   '-pdfxe',
  \   '-gg',
  \   '-verbose',
  \   '-file-line-error',
  \   '-synctex=1',
  \   '-interaction=nonstopmode',
  \   '-cd', ],
  \}
```

## Step to produce
1. `vim -u minimal.vim test.tex` and star compiling by `\ll`
2.  Edit `mypackage.sty` by adding one line `\tl_new:N \l_test_tl` before `\file_input_stop:`
3. Save changes of `mypackage.sty` by `:w`

## vim error information
```txt
Error detected while processing function <SNR>130_callback_continuous_output:
E716: Key not present in Dictionary: compiler.output
E116: Invalid arguments for function filewritable (b:vimtex.compiler.output)
```

## output of `:VimtexInfo`
```
Rc files read:
  NONE
Latexmk: This is Latexmk, John Collins, 17 Apr. 2020, version: 4.69a.
======= Need to update make_preview_continuous for target files
Latexmk: applying rule 'xelatex'...
Latexmk: Changing directory to './'
This is XeTeX, Version 3.14159265-2.6-0.999992 (TeX Live 2020) (preloaded format=xelatex)
 \write18 enabled.
Latexmk: Removing all generated files
entering extended mode
(./test.tex
LaTeX2e <2020-02-02> patch level 5
Viewing pdf
L3 programming layer <2020-06-03> (/usr/local/texlive/2020/texmf-dist/tex/latex/base/minimal.cls
Document Class: minimal 2001/05/25 Standard LaTeX minimal class
) (./mypackage.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/l3kernel/expl3.sty (/usr/local/texlive/2020/texmf-dist/tex/latex/l3backend/l3backend-xdvipdfmx.def))) (./test.aux) (/usr/local/texlive/2020/texmf-dist/tex/latex/base/ts1cmr.fd) [1] (./test.aux) )
Rule 'xelatex': The following rules & subrules became out-of-date:
Output written on test.xdv (1 page, 500 bytes).
SyncTeX written on test.synctex.gz.
Transcript written on test.log.
      'xelatex'
=== TeX engine is 'XeTeX'
Latexmk: applying rule 'xdvipdfmx'...
For rule 'xdvipdfmx', running '&do_viewfile(  )' ...
------------
Latexmk: All targets (test.xdv test.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
vimtex_compiler_callback_success
Run number 1 of rule 'xelatex'
------------
------------
Running 'xelatex -no-pdf -file-line-error -synctex=1 -interaction=nonstopmode --shell-escape -recorder  "test.tex"'
------------
Latexmk: Log file says output to 'test.xdv'
Rule 'xdvipdfmx': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'test.xdv'
   Rule(s) that have been run and require run of dependent rule:
      'xelatex' which requires run of 'xdvipdfmx'
------------
Run number 1 of rule 'xdvipdfmx'
------------
Latexmk: Making 'test.pdf' via temporary '/tmp/test_tmp1.pdf'...
------------
Running 'xdvipdfmx -E -o "/tmp/test_tmp1.pdf"  "test.xdv"'
------------
test.xdv -> test.pdf
[1]
2920 bytes written
Latexmk: I have not found a previewer that is already running. 
   So I will start it for 'test.pdf'
------------
------------
Running 'start xdg-open  "test.pdf"'
------------
------------
Running 'echo vimtex_compiler_callback_success'
------------
```

Everything about latex is normal, but vim complains a lot and I have to press `<Enter>` several times to skip these vim errors.

**Comment by lervag** [comment]
You did not show the output of `:VimtexInfo`, you showed `:VimtexCompileOutput` (which is also useful).

**Comment by ZhiyuanLck** [comment]
I'm sorry. Here is it.
```
System info
  OS: Ubuntu 18.04.5 LTS
  Vim version: VIM 8.2 (1-1539)
  Has clientserver: true
  Servername: VIM5

vimtex project: test
  base: test.tex
  root: /home/zhiyuan/tex/temp
  tex: /home/zhiyuan/tex/temp/test.tex
  out: /home/zhiyuan/tex/temp/test.pdf
  log: /home/zhiyuan/tex/temp/test.log
  aux: /home/zhiyuan/tex/temp/test.aux
  fls: /home/zhiyuan/tex/temp/test.fls
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -pdfxe
        -gg
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
        -cd
      latexmk engine: -xelatex --shell-escape
    job: process 32451 run
    pid: 32451
    cmd: max_print_line=2000 latexmk -pdfxe -gg -verbose -file-line-error -synctex=1 -interaction=nonstopmode -cd -xelatex --shell-escape -pvc -e '$pdf_previewer = "xdg-open"' -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'test.tex'
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: minimal
  packages:
    expl3
    mypackage
```

**Comment by lervag** [comment]
Thanks. First, you can simplify your configuration by removing the defaults, i.e.:

```vim
let g:vimtex_compiler_latexmk_engines = {
      \ '_'        : '-xelatex --shell-escape',
      \ 'xelatex'      : '-xelatex --shell-escape',
      \}
let g:vimtex_compiler_latexmk = {
      \ 'options': [
      \   '-pdfxe',
      \   '-gg',
      \   '-verbose',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \   '-cd', ],
      \}
```

I've tried to reproduce this, but everything works as expected on my end.

After you've performed step 1, and then opened `mypackage.sty`: What happens if you do `\li` within the `.sty` file? What is the output of `:echo b:vimtex`?

**Comment by ZhiyuanLck** [comment]
Output of `\li` within the `.sty` file is
```
System info
  OS: Ubuntu 18.04.5 LTS
  Vim version: VIM 8.2 (1-1539)
  Has clientserver: true
  Servername: VIM5

vimtex project: mypackage
  base: mypackage.sty
  root: /home/zhiyuan/tex/temp
  tex: 
  out: 
  log: 
  aux: 
  fls: 
  main parser: cls/sty file
  document class: 
```

**Comment by lervag** [comment]
Ok. I'm sorry, but from my point of view, everything works as expected. I can't reproduce your problem with your specificied configuration. Are you sure you are not forgetting about something that may be important in reproducing this?

**Comment by ZhiyuanLck** [comment]
Output of `\li` within the `.sty` file is
```
System info
  OS: Ubuntu 18.04.5 LTS
  Vim version: VIM 8.2 (1-1539)
  Has clientserver: true
  Servername: VIM5

vimtex project: mypackage
  base: mypackage.sty
  root: /home/zhiyuan/tex/temp
  tex: 
  out: 
  log: 
  aux: 
  fls: 
  main parser: cls/sty file
  document class: 
```

**Comment by ZhiyuanLck** [comment]
Well I did forget an important information: I open `test.tex` and `mypackage.sty` in two tabs and then error occured. If they are in the same buffer, everything goes normal.

But I mainly use tab to organize my files and hardly use buffers, can this be fixed?

**Comment by lervag** [comment]
> Well I did forget an important information: I open `test.tex` and `mypackage.sty` in two tabs and then error occured. If they are in the same buffer, everything goes normal.

Yes, that's important. This is why the issue template _specifically_ asks you to detail every step. The current list:

> 1. `vim -u minimal.vim test.tex` and start compiling by `\ll`
> 2. Edit `mypackage.sty` by adding one line `\tl_new:N \l_test_tl` before `\file_input_stop:`
> 3. Save changes of mypackage.sty by `:w`

Does _not_ specify _how_ you "Edit `mypackage.sty`", so I did `:edit mypackage.sty`. You are probably doing `:tabedit ...`, which is essential. So please, learn from this that you should specify exactly what you are doing.

> But I mainly use tab to organize my files and hardly use buffers, can this be fixed?

Can _what_ be fixed?

**Comment by lervag** [comment]
Note, I still can't reproduce this. So, if you want me to fix anything, please try and provide a reproducible example. Give the precise steps you do to get the error.

**Comment by ZhiyuanLck** [comment]
Thank much for your patient. Below is the detailed steps:
1. `vim -u minimal.vim test.tex`
2. `\ll`
3. `:tabnew`
4. `:e mypackage.sty`
5.  add/change some content
6. `:w`

**Comment by lervag** [comment]
Ah, this explains it. I can fix the message. Note, it is better if you do `:tabedit mypackage.sty`, because vimtex can then keep the "previous" state and assume that `mypackage.sty` should be considered a part of the `test.tex` "project". If you first do `:tabnew` (or `:new`), then vimtex can not "connect" the `mypackage.sty` file to a project, which means the state does not have the properties assumed by the callback function.

So:

1. I'll fix it.

2. If you do `:tabedit mypackage.sty` instead of `:tabnew` then `:e`, the problem you've reported is no longer a real issue.

**Comment by ZhiyuanLck** [comment]
Thanks very much for your effort. After I update the plugin with the same step, instead of a lot of duplicated errors, there is still one piece of error:
```
Error detected while processing function <SNR>36_callback_continuous_output[7]..vimtex#compiler@callback
E716: Key not present in Dictionary: compiler, 'silence_next_callback`
E116: Invalid arguments for function get(b:vimtex.compiler, 'silence_next_callback')
```
Cauze I open a newtab first and then use `dirvish` choose the file to open, which is more conveniant than `tabedit` for me, so the popup error messages is always there when I open the file by this way and perform the above steps.

**Comment by lervag** [comment]
Sorry; fixed now.
