### ISSUE TITLE
Problem with g:vimtex_syntax_alpha

### ISSUE THREAD

**Issue by jubnzv** [lervag/vimtex#1809]
Hi,

I found a small issue when updating vimtex to the latest version from git master.
It seems that f72642c0828196475fdaf7764fd63cfb1f74c04a leads to errors at startup.

Here are the error messages that appears when starting vim:

```
Error detected while processing /home/jubnzv/.local/share/nvim/plugged/vimtex/syntax/tex.vim:             
line   23:                                                                                                
E121: Undefined variable: g:vimtex_syntax_alpha                                                           
E15: Invalid expression: exists('b:current_syntax') || !g:vimtex_syntax_alpha                             
Error detected while processing /home/jubnzv/.local/share/nvim/plugged/vimtex/after/syntax/tex.vim:       
line    7:                                                                                                
E121: Undefined variable: g:vimtex_syntax_alpha                                                           
E15: Invalid expression: !g:vimtex_syntax_alpha   
```

It seems that the problem in the global variable `g:vimtex_syntax_alpha`.

If we replace `g:vimtex_syntax_alpha` to `get(g:, 'vimtex_syntax_alpha')` [here](https://github.com/lervag/vimtex/blob/f72642c0828196475fdaf7764fd63cfb1f74c04a/after/syntax/tex.vim#L7) and [here](https://github.com/lervag/vimtex/blob/f72642c0828196475fdaf7764fd63cfb1f74c04a/syntax/tex.vim#L23), the plugin works as expected.

**Comment by lervag** [comment]
That's strange. This should'nt happen, because `g:vimtex_syntax_alpha` should be initialized before the `syntax` scripts. Can you give me a minimal vimrc for this?

**Comment by lervag** [comment]
It seems it is due to the order of `syntax on` vs. `filetype plugin on`. You should put `filetype plugin on` _before_ `syntax on`.

**Comment by lervag** [comment]
I can't find a good source for this, but IMHO it is a standard _best practise_, and I think _all_ of the plugin managers (like vim-plug) that automatically applies `filetype plugin on` and `syntax on` apply the operations in this order. Still, I think you raise an important issue, and before I "insist" that people put things in a given order I will accept your suggested change.

In the future, I might want to specify a correct order so that the syntax scripts may rely on the filetype plugin state. This is actually already assumed for certain syntax elements, so if you want things to work correctly, you should already now update your vimrc as I've mentioned.

**Comment by jubnzv** [comment]
@lervag thank you for looking this.

It seems that the vim-plug doesn't set this option. They only set `filetype plugin indent on` [here](https://github.com/junegunn/vim-plug/blob/d16273e07231260e02412625f98651bc6ceebb56/plug.vim#L419-L423).

**Comment by lervag** [comment]
> @lervag thank you for looking this.

No problem.

> It seems that the vim-plug doesn't set this option. They only set `filetype plugin indent on` [here](https://github.com/junegunn/vim-plug/blob/d16273e07231260e02412625f98651bc6ceebb56/plug.vim#L419-L423).

But, I'm sorry, but you're wrong. And you're staring right at it. The code does exactly what I was talking about. See also [this excerpt from the docs of vim-plug](https://github.com/junegunn/vim-plug/blob/d16273e07231260e02412625f98651bc6ceebb56/doc/plug.txt#L137-L140):

```
 3. `call plug#end()` to update 'runtimepath' and initialize plugin system
   - Automatically executes `filetype plugin indent on` and `syntax enable`.
     You can revert the settings after the call. e.g. `filetype indent off`,
     `syntax off`, etc.
```

Note: `filetype plugin on` and `filetype plugin indent on` is "the same", except `filetype plugin indent on` also enables the `indent` scripts. `syntax enable` is similar to `syntax on`. For more info, read the docs, e.g. `:help :filetype` and `:help :syn-enable`.

**Comment by jubnzv** [comment]
Oh, got it. Thank you for the clarification.

**Comment by lervag** [comment]
> Oh, got it. Thank you for the clarification.

No problem!

> The behavior of `filetype` functions is more clearly visible in the source code: [ex_filetype](https://github.com/neovim/neovim/tree/f34eeba2d85b4382d7504e1f3e12a7afb0788c1d/src/nvim/ex_docmd.c#L9100). The `plugin` and `indent` options are treated as arguments for the `filetype` command [here](https://github.com/neovim/neovim/tree/f34eeba2d85b4382d7504e1f3e12a7afb0788c1d/src/nvim/ex_docmd.c#L9115).

I've not really looked much at the Vim source code, and I've not very much experience with C. But yes, that was not so hard to read. :)
