### ISSUE TITLE
Citation completion does not work lately

### ISSUE THREAD

**Issue by bratekarate** [lervag/vimtex#1815]
The citation completion does not work for me anymore. I'm sure this is somehow a local issue for me, but I fail to wrap my head around it.

After I installed vimtex a month or so ago, the citation completion worked right out of the box. I used it with `coc-vimtex`. Today I tried it and it did not work anymore. No errors appeared, there were just no suggestions. I tried to disable coc completely and use the omnicompletion. There it yielded "Pattern not found".

I tried some more things:
- reverted back to a vimtex commit from about a month ago
- deleted the cache at `~/.cache/vimtex` as described in another issues
- deleted all compilates from my latex directory.
- reverted back to an older version of my latex document
- disabled all plugins except vimtex
- used vim instead of neovim

I checked the `main.blg` file, as described in #1751. I am also missing the lines:
```
[135] Utils.pm:75> INFO - Globbing data source ...
```
Maybe this shows something is wrong?

Output from `tree`:
```
.                                                                                
├── 01_input.tex
├── 02_input.tex
├── 03_input.tex
├── acronyms.tex
├── defines.tex
├── dict.txt
├── geometry.sty
├── images
├── main.bib
├── main.tex
├── main.tex.latexmain
├── noindent.sty
├── Readme_LaTeX.txt
├── README.md
└── style.tex
```

```tex
./style.tex:
---------------
\usepackage[style=alphabetic-verb,backend=biber]{biblatex}
...
\bibliography{main}
...
```
```sh
$ latex --version
pdfTeX 3.14159265-2.6-1.40.21 (TeX Live 2020/Arch Linux)
kpathsea version 6.3.2
Copyright 2020 Han The Thanh (pdfTeX) et al.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the pdfTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the pdfTeX source.
Primary author of pdfTeX: Han The Thanh (pdfTeX) et al.
Compiled with libpng 1.6.37; using libpng 1.6.37
Compiled with zlib 1.2.11; using zlib 1.2.11
Compiled with poppler version 20.08.0
```

Any thing else I could try? 

**Edit:** I also tried with the example project "book-multifile" -- same result.
**Edit2:** Must be something with my project...I tried `test/issues/1454/minimal.tex` with my own `.bib` file and it works. Wish I knew what is going on.

**Comment by bratekarate** [comment]
Ok, kind of solved. The issue was that
```tex
\bibliography{main}
```
had to be changed to

```tex
\bibliography{./main}
```
or 
```tex
\bibliography{./main.bib}
```
Which is odd, because according to my git history, it was always like this but used to work. Reverting back to an older version of vimtex did not help though.

I will leave this issue open for now, since I am not sure if it is a bug or expected behaviour. At least it compiles, so I feels like it should work or be documented.

**Comment by lervag** [comment]
Strange! Are you able to make a minimal LaTeX example for this that I could look at? (Or share your current working document, e.g. by email)?

**Comment by bratekarate** [comment]
@lervag `test/issues/1454/minimal.tex` is almost enough to test it. Only the bib file must go in the same directory as the `.tex` file and referenced without the prefix `./` as posted above. This should be enough to break it.

**Comment by lervag** [comment]
> @lervag `test/issues/1454/minimal.tex` is almost enough to test it. Only the bib file must go in the same directory as the `.tex` file and referenced without the prefix `./` as posted above. This should be enough to break it.

It does not work for me. Or, that is, it does work exactly as expected. Can you make a proper minimal example and minimal vimrc file?

**Comment by bratekarate** [comment]
Wow, something strange going on with my setup I suspect. I will try to setup an example soon.

**Comment by lervag** [comment]
Great :)
