### ISSUE TITLE
Citation context menu: pdf file not recognized

### ISSUE THREAD

**Issue by bratekarate** [lervag/vimtex#1816]
If I specify the `file` property in my `.bib` file, it is not recognized by the context menu. 

I tried to debug a little, but could not follow everything that happens. The result of `vimtex#parser#bib` has no key `file`. In `parse_with_vim`, the key is still there in the variable `l:entries`, but after `s:parse_entry_body`, it is gone. I am not sure how the parser in general works, but these are the observations I made so far.

**Comment by bratekarate** [comment]
...and also found a workaround for this one. `file` must be at the top of the bib entry. Is this expected behaviour? At least I did not expect it :)

**Comment by lervag** [comment]
I suspect there may be an error in your bib file (or, obv., a bug in vimtex). Can you work down a minimal example?

**Comment by bratekarate** [comment]
@lervag Yes, I suspect it is because I use `bibclean`. It formats the file in a quite unusual way, but it should not be an error. I formatted it with `bibclean` (Ale) and linted/compiled it with `biber --tool` (vimtex). Should be valid. Here an except that should be enough to reproduce the error:

 ```bib
@InProceedings{Laput_2016,
  file         = "../research/file.pdf",
  doi          = "https://doi.org/10.1145/2984511.2984582",
  year         = "2016",
  publisher    = "{ACM} Press",
  author       = "Gierad Laput and Robert Xiao and Chris Harrison",
  title        = "{ViBand}",
  booktitle    = "Proceedings of the 29th Annual Symposium on User
                 Interface Software and Technology - {UIST}
                 {\textquotesingle}16",
}
```
Do you need anything else?

**Comment by lervag** [comment]
> Do you need anything else?

I still can't reproduce. It would be much easier if you could create a minimal LaTeX example (and preferably also a minimal vimrc file).

> The context menu is great by the way! Now that I have the `file` properties at the top, it works perfectly for me. Only one future suggestion, but I open another issue for that.

Thanks! I also find it very useful :)

**Comment by bratekarate** [comment]
@lervag ok, I will try to setup a simple example soon. Weird that it was not reproducible, I was so sure the bib file format was the issue.

**Comment by lervag** [comment]
Things have a tendency of being surprising... :p
