### ISSUE TITLE
Choose independent viewer for context menu

### ISSUE THREAD

**Issue by bratekarate** [lervag/vimtex#1817]
The context menu is a great tool that simplified my workflow a lot! However, I think it would be a useful addition to be able to choose another pdf viewer just for the citation context.

Use case: I use zathura as the default for almost all cases, especially in conjunction with the vimtex compiler feature. But when going through research papers, I use a pdf viewer that can handle annotations, like Okular or Evince. I think highlighting and scribbeling on the pdf can be very helpful when the pdf is opened again after a couple of days without seeing it.

A solution could be to tap into `netrw-gx` when opening the pdf through the context menu, although I don't know how easy it is. Then the user could configure `netrw-gx` with a different viewer context menu. If `g:netrw_browsex_viewer` is not specified, then `g:vimtex_view_method` could be used.

One downside of this solution would be that the heavyweight viewer was to be used everytime `netrw-gx` is called. This would be an argument for configuring a special viewer only for the context menu. On the other hand, the user could configure `g:vimtex_view_method` with a heavy pdf viewer specifically for the tex filetype. The user could then still not use a lightweight pdf viewer like zathura for tex filetypes anymore with `netrw-gx`, but maybe this is acceptable. Lightweight enthusiast could then decide not to use a heavy pdf viewer all together.

**Comment by lervag** [comment]
> Use case: I use zathura as the default for almost all cases, especially in conjunction with the vimtex compiler feature. But when going through research papers, I use a pdf viewer that can handle annotations, like Okular or Evince. I think highlighting and scribbeling on the pdf can be very helpful when the pdf is opened again after a couple of days without seeing it.

Good point!

> A solution could be to tap into `netrw-gx` when opening the pdf through the context menu, although I don't know how easy it is. Then the user could configure `netrw-gx` with a different viewer context menu. If `g:netrw_browsex_viewer` is not specified, then `g:vimtex_view_method` could be used.

Or, perhaps we should define a new option for this? Something like `g:vimtex_contex_viewer`. I think it could make sense. The default could be similar to the current `g:vimtex_view_general_viewer` (e.g. `xdg-open` on Linux).

**Comment by bratekarate** [comment]
Yes, the use case is probably very different to that of netrw-gx. Just wanted to through in some ideas how existing functionality could be reused. I think you are right that a configuration property is the best solution.

**Comment by lervag** [comment]
I've added a new option now: `g:vimtex_context_pdf_viewer`. It seems to work as expected for me. I've made the default slightly complex, let me know what you think.

**Comment by bratekarate** [comment]
@lervag Looks good to me. Replaced my local fix with the new master and it still works as expected :)
