### ISSUE TITLE
Errors when completing labels

### ISSUE THREAD

**Issue by DiogoDoreto** [lervag/vimtex#182]
Hello! I think I'm having a issue very related to #169 . The first time I try to autocomplete inside `\ref` or `\autoref` it shows the errors below. But then it works like nothing happened.

```
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E684: list index out of range: 2
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E116: Invalid arguments for function type(tree[2][0]) == type([]) && !empty(tree[2][0])
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E15: Invalid expression: type(tree[2][0]) == type([]) && !empty(tree[2][0])
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E684: list index out of range: 2
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E116: Invalid arguments for function type(tree[2][0]) == type([]) && !empty(tree[2][0])
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E15: Invalid expression: type(tree[2][0]) == type([]) && !empty(tree[2][0])
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E684: list index out of range: 2
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E116: Invalid arguments for function type(tree[2][0]) == type([]) && !empty(tree[2][0])
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E15: Invalid expression: type(tree[2][0]) == type([]) && !empty(tree[2][0])
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E684: list index out of range: 2
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E116: Invalid arguments for function type(tree[2][0]) == type([]) && !empty(tree[2][0])
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E15: Invalid expression: type(tree[2][0]) == type([]) && !empty(tree[2][0])
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E684: list index out of range: 2
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E116: Invalid arguments for function type(tree[2][0]) == type([]) && !empty(tree[2][0])
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>48_labels_get..<SNR>48_labels_extract:
line   15:
E15: Invalid expression: type(tree[2][0]) == type([]) && !empty(tree[2][0])
```

**Comment by lervag** [comment]
Interesting. Could you please provide a minimal working example and explain the exact steps required to reproduce the issue?

**Comment by DiogoDoreto** [comment]
Oops... I can't reproduce this in a new document. I don't know what could be conflicting and I don't have much time right now to test every possibility. Just to add some more info, it is showing `\M@TitleReference` on every suggestion. I don't know if this can give you some insight on what could be happening. When I get some spare time I'll reconstruct my current document from ground up to find out what is happening.

![vimtex](https://cloud.githubusercontent.com/assets/259302/8043584/775eff60-0dfd-11e5-8d67-e16c5ca82ac8.PNG)

**Comment by lervag** [comment]
I'm sorry, but I really need to be able to reproduce this to solve the issue. I understand that it's a little bit bothersome, but the information you've provided so far is not enough. From it, I know where the error occurs, and I have an idea of what is wrong.

One thing that might help is the generated `aux` file. Based on the error, I would think you are using some package that provides a new reference type. The code uses a relatively silly assumption when parsing the labels that they are all of the form
```
\newlabel{name}{{number}{page}.*}.*
```
I already know this is not always true, and I have therefore added some extra code to handle some edge cases. However, it seems you are experiencing a new edge case that I have not seen so far.

The minimum requirement to solve the issue is to get an aux-file for a document where this error occurs.

**Comment by DiogoDoreto** [comment]
This is how my label looks like in the .aux file:

    \newlabel{cha:programacao_concorrente}{{\M@TitleReference {2}{Programa\IeC {\c c}\IeC {\~a}o Concorrente}}{27}{Programação Concorrente}{chapter.2}{}}

If you prefer to see the whole file I can post it here or somewhere. Or we can wait until next week when I'll have some time to get a minimum working example.

**Comment by lervag** [comment]
Thanks, I can now reproduce. I'm still very interested in a complete minimal working example. That is, provide a minimal preamble and document that would create such a label in the aux file.

**Comment by DiogoDoreto** [comment]
What changes the label is the `abntex2` document class, like this:

```
\documentclass{abntex2}
\begin{document}
\section{Programação Concorrente}
\label{sec:programacao_concorrente}
\end{document}
```

**Comment by DiogoDoreto** [comment]
Thanks, but I'm still getting some errors:

```
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..
<SNR>48_labels_get..<SNR>48_labels_extract:
line   21:
E684: list index out of range: 0
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..
<SNR>48_labels_get..<SNR>48_labels_extract:
line   21:
E15: Invalid expression: len(tree[0][0]) > 1 ? tree[0][0][1][0] : tree[0][0][0]
```

At least they are a lot less than before and the `\M@TitleReference` is not showing anymore

**Comment by lervag** [comment]
Could you again provide an example of a file that will give an error?

tor. 18. jun. 2015, 23.37 skrev Diogo Doreto <notifications@github.com>:

**Comment by DiogoDoreto** [comment]
Now I think I got to the root of the problem:

```
\documentclass{abntex2}
\usepackage[utf8]{inputenc}

\begin{document}

\section{Introdução}
\label{sec:introducao}

My text

\end{document}
```

So, given this example, when I go to the end of "My text" and write `\ref{` and then press `<c-Space>` to give me the labels suggestions the following sequence of errors shows up:

```
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>57_labels_get..<SNR>57_labels_extract:
line   15:
E684: list index out of range: 2
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>57_labels_get..<SNR>57_labels_extract:
line   15:
E116: Invalid arguments for function type(tree[2][0]) == type([]) && !empty(tree[2][0])
Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>57_labels_get..<SNR>57_labels_extract:
line   15:
E15: Invalid expression: type(tree[2][0]) == type([]) && !empty(tree[2][0])
```

These errors only occur when I have `\usepackage[utf8]{inputenc}` in the preamble.

**Comment by lervag** [comment]
Ah, perfect! I'm happy it is working!

**Comment by mattjj** [comment]
I'm getting the same set of errors in a particular document. I don't yet have a minimal example (I'll try to make one when I get a chance) but here's an offending aux file: https://gist.github.com/mattjj/f16d4add4d60799cb0ec.

**Comment by lervag** [comment]
I think you are using either a documentclass or a package that I've never used. In any case, based on the aux file I think I've implemented a fix for your problem.

**Comment by mattjj** [comment]
Your fix worked!

Sorry for not being more helpful in debugging. The documentclass is just article but there are a lot of packages being used; I had meant to do a binary search to figure out which one was causing the problem but I haven't had a chance.

Thanks for that fix and for the brilliant plugin!

**Comment by lervag** [comment]
Great! Glad to hear it works, and no problem! The aux file was sufficient
:-)

fre. 26. jun. 2015, 23.35 skrev Matthew Johnson <notifications@github.com>:
