### ISSUE TITLE
Advanced matchparen highlight is not local to tex buffer

### ISSUE THREAD

**Issue by adigitoleo** [lervag/vimtex#1820]
**Issue**

With vimtex advanced matchparen enabled, the MatchParen highlight group bleeds into other buffers. Highlights are still visible after e.g. `:bn`. This also affects single-bracket highlights, e.g. for `{}`. I am on neovim, not sure if it affects vim or not.

**minimal init.vim**

Just needs to load vimtex and enable advanced matchparen (default).

```vim
filetype plugin indent on
set number

let g:PLUGIN_HOME = expand(stdpath('data') . '/plugged')
call plug#begin(g:PLUGIN_HOME)
    Plug 'lervag/vimtex',
call plug#end()

let g:vimtex_matchparen_enabled = 1
```

**minimal.tex**

Any tex file that defines at least one environment will do.

  ```tex
  \documentclass{minimal}
  \begin{document}
  Hello world!
  \end{document}
  ```
**Observed Behaviour**

Open the tex file and move the cursor to either the `\begin`ning or `\end` of the environment. The entire command should be highlighted. Note the Line numbers (`B,E`). Open any other buffer that has text on lines `B` and `E` in the same window, e.g. via `:e <filename>`. The highlights are still visible and are drawn over the new buffer's contents. 

Switch back to the tex file and move the cursor to the bracket `{` after `\documentclass`. The closing bracket of the command is also highlighted. Switch to the other buffer again, making sure that it has text at the matching position. The characters that match the former bracket positions are still highlighted.

**Expected Behaviour**

Matchparen highlights are local to the tex buffer and are cleared when leaving it.

<details>
<summary>Output from VimtexInfo</summary>

```
System info
  OS: Linux 5.8.13-arch1-1
  Vim version: NVIM v0.4.4
  Has clientserver: true
  Servername: /tmp/nvimsocket

vimtex project: cv-gov
  base: cv-gov.tex
  root: /home/leon/Documents/work/cv-gov
  tex: /home/leon/Documents/work/cv-gov/cv-gov.tex
  out: /home/leon/Documents/work/cv-gov/cv-gov.pdf
  log: /home/leon/Documents/work/cv-gov/cv-gov.log
  aux: /home/leon/Documents/work/cv-gov/cv-gov.aux
  fls: /home/leon/Documents/work/cv-gov/cv-gov.fls
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 56
    fix_paths: 57
    set_errorformat: 55
  document class: komacv
  packages:
    array
    atbegshi
    atveryend
    auxhook
    babel
    bigintcalc
    bitset
    bookmark
    calc
    enumitem
    epstopdf-base
    etexcmds
    etoolbox
    everysel
    fontawesome
    fontaxes
    fontenc
    gettitlestring
    graphics
    graphicx
    hycolor
    hyperref
    ifluatex
    ifpdf
    iftex
    ifthen
    ifxetex
    infwarerr
    inputenc
    intcalc
    keyval
    komacv-classic
    kvdefinekeys
    kvoptions
    kvsetkeys
    lastpage
    letltxmacro
    libertine
    ltxcmds
    marvosym
    microtype
    nameref
    pdfescape
    pdftexcmds
    ragged2e
    refcount
    rerunfilecheck
    scrbase
    scrkbase
    scrlayer
    scrlayer-scrpage
    scrlfile
    textcomp
    tocbasic
    trig
    typearea
    uniquecounter
    url
    xcolor
    xkeyval
```

</details>

---

I mentioned this observation briefly in #1781 and thought that it was not vimtex-specific, but I have since failed to reproduce it without vimtex matchparen, so I think it could be a vimtex thing. This should be considered a low-priority annoyance and doesn't seem to affect any functionality.

Edits: fix minimal init.vim and spelling

**Comment by lervag** [comment]
> With vimtex advanced matchparen enabled, the MatchParen highlight group bleeds into other buffers. ...

Reproduced! Thanks for reporting this, I was not aware of it. I'll look into it and fix it.

**Comment by lervag** [comment]
I think this should be fixed now.

**Comment by adigitoleo** [comment]
Can confirm, spurious highlights are gone!

**Comment by lervag** [comment]
Great, happy to hear it!

**Comment by adigitoleo** [comment]
Actually there are some weird edge cases where it's still misbehaving:

1. Floating windows like those created by [fzf](https://github.com/junegunn/fzf) "steal" the highlight until closed
2. Moving to another buffer now clears the highlight, and it's restored when moving back *unless* the cursor is on the same line number

The second one is very insignificant (jumping with `%` works and restored the highlight). The first one is strange, I tested the autocommand events a bit and opening the popup *does* fire a WinLeave from the tex buffer, so it should work... I'll play around a bit more to see if I can track this down so you can focus on more important stuff.

**Comment by lervag** [comment]
> Actually there are some weird edge cases where it's still misbehaving: ...
> 
> The second one is very insignificant (jumping with `%` works and restored the highlight).

Yes, agreed - I don't see any easy fixes either.

> The first one is strange, I tested the autocommand events a bit and opening the popup _does_ fire a WinLeave from the tex buffer, so it should work... I'll play around a bit more to see if I can track this down so you can focus on more important stuff.
> 
> EDIT: Nevermind, (1) isn't vimtex specific and happens even with the default matchparen highlights. Probably nothing to be done here.

Ok. If you would be able to make a simple, reproducible example, then I could potentially look into it. If so, feel free to open a new issue (it is easier for me to keep threads separated).

**Comment by adigitoleo** [comment]
Sorry, I was barking up the wrong tree :) This only happens with fzf popups so I have [reported it](https://github.com/junegunn/fzf/issues/2406) as an issue with their popup implementation.

**Comment by lervag** [comment]
I see; no problem :)
