### ISSUE TITLE
Gvim-Cannot view file with okular

### ISSUE THREAD

**Issue by adhalanay** [lervag/vimtex#1823]
**Issue**
Trying to open the pdf file with '\lv' does nothing.  I noticed a few things:

- when using vim started from the command-line the viewer works
- the culprit seems to be the call
    ```
    okular --unique file:'/home/andrei/minimal.pdf'\\#src:1'/home/andrei/minimal.tex' >/dev/null 2>&1 &
    ```
    when running it with `:!` also nothing happens. If one removes `>/dev/null 2> & 1 &1` the call works as expected.

**minimal.vim**

```vim
set nocompatible
call vimrc#init()
call plug#begin('~/.vim/bundle')
call plug#begin(g:vimrc#path_bundles)
Plug 'lervag/vimtex'
call plug#end()
let mapleader=","
let maplocalleader=","
let g:tex_flavor='latex'
let g:vimtex_view_general_viewer='okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
```

**minimal.tex**
```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

**Commands/Input**
`<Localleader>lv`

**Observed Behaviour**
Nothing happens.

**Expected Behaviour**
The Okular viewer should start loaded with the pdf file.

**Output from VimtexInfo**
```
System info
OS: Debian GNU/Linux bullseye/sid
Vim version: VIM 8.2 (1-716)
Has clientserver: true
Servername: GVIM

vimtex project: minimal
base: minimal.tex
root: /home/andrei
tex: /home/andrei/minimal.tex
out: /home/andrei/minimal.pdf
log: /home/andrei/minimal.log
aux: /home/andrei/minimal.aux
fls: /home/andrei/minimal.fls
main parser: current file verified
compiler: latexmk
  configuration: 
    continuous: 1
    callback: 1
    latexmk options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    latexmk engine: -pdf
  job: process 16220 run
  pid: 16220
  cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$pdf_previewer = "okular --unique"' -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'minimal.tex'
viewer: General
  process: 
    pid: -
    cmd: okular --unique file:'/home/andrei/minimal.pdf'\\#src:1'/home/andrei/minimal.tex' >/dev/null 2>&1 &
qf: LaTeX logfile
  root: /home/andrei
  addqflist: 56
  errorformat_saved: 
  fix_paths: 57
  main: /home/andrei/minimal.tex
  set_errorformat: 55
document class: minimal
```

**Comment by lervag** [comment]
First, some comments to a couple of parts in your minimal `vimrc` file:

```vim
" This is not necessary
set nocompatible

" Why two paths here?!
call plug#begin('~/.vim/bundle')
call plug#begin(g:vimrc#path_bundles)

" Mapleader is not relevant
let mapleader=","
```

Regarding your issue: What is the value of the `shell` option? Is it different in GVim and Vim? Also, when starting with the minimal vimrc, can you give the output of `:scriptnames` both from Vim in terminal and GVim?

**Comment by adhalanay** [comment]
Outpuf of :scriptnames for gvim

 ~/.vimrc-minim
  2: ~/.vim/autoload/vimrc.vim
  3: ~/.vim/autoload/plug.vim
  4: /usr/share/vim/vim82/filetype.vim
  5: ~/.vim/personal/ftdetect/dagbok.vim
  6: ~/.vim/personal/ftdetect/julia.vim
  7: ~/.vim/personal/ftdetect/text.vim
  8: /usr/share/vim/vim82/menu.vim
  9: /usr/share/vim/vim82/autoload/paste.vim
 10: /usr/share/vim/vim82/ftplugin.vim
 11: /usr/share/vim/vim82/indent.vim
 12: /usr/share/vim/vim82/syntax/syntax.vim
 13: /usr/share/vim/vim82/syntax/synload.vim
 14: /usr/share/vim/vim82/syntax/syncolor.vim
 15: ~/.vim/personal/plugin/log-autocmds.vim
 16: ~/.vim/personal/plugin/merge-mode.vim
 17: ~/.vim/personal/plugin/open-in-browser.vim
 18: ~/.vim/personal/plugin/text-object-indent.vim
 19: ~/.vim/personal/plugin/toggle-verbose.vim
 20: ~/.vim/personal/plugin/windows.vim
 21: ~/.vim/personal/plugin/zeal.vim
 22: ~/.vim/bundle/vimtex/plugin/vimtex.vim
 23: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
 24: /usr/share/vim/vim82/plugin/gzip.vim
 25: /usr/share/vim/vim82/plugin/logiPat.vim
 26: /usr/share/vim/vim82/plugin/manpager.vim
 27: /usr/share/vim/vim82/plugin/matchparen.vim
 28: /usr/share/vim/vim82/plugin/netrwPlugin.vim
 29: /usr/share/vim/vim82/plugin/rrhelper.vim
 30: /usr/share/vim/vim82/plugin/spellfile.vim
 31: /usr/share/vim/vim82/plugin/tarPlugin.vim
 32: /usr/share/vim/vim82/plugin/tohtml.vim
 33: /usr/share/vim/vim82/plugin/vimballPlugin.vim
 34: /usr/share/vim/vim82/plugin/zipPlugin.vim
 35: ~/.vim/personal/after/plugin/speeddating.vim
 36: /usr/share/vim/gvimrc
 37: ~/.gvimrc
 38: /usr/share/vim/vim82/autoload/dist/ft.vim
 39: ~/.vim/personal/ftplugin/tex.vim
 40: ~/.vim/bundle/vimtex/autoload/vimtex/imaps.vim
 41: ~/.vim/bundle/vimtex/ftplugin/tex.vim
 42: ~/.vim/bundle/vimtex/autoload/vimtex.vim
 43: ~/.vim/bundle/vimtex/autoload/vimtex/options.vim
 44: ~/.vim/bundle/vimtex/autoload/vimtex/util.vim
 45: ~/.vim/bundle/vimtex/autoload/vimtex/state.vim
 46: ~/.vim/bundle/vimtex/autoload/vimtex/re.vim
 47: ~/.vim/bundle/vimtex/autoload/vimtex/parser.vim
 48: ~/.vim/bundle/vimtex/autoload/vimtex/parser/tex.vim
 49: ~/.vim/bundle/vimtex/autoload/vimtex/cache.vim
 50: ~/.vim/bundle/vimtex/autoload/vimtex/paths.vim
 51: ~/.vim/bundle/vimtex/autoload/vimtex/view.vim
 52: ~/.vim/bundle/vimtex/autoload/vimtex/view/general.vim
 53: ~/.vim/bundle/vimtex/autoload/vimtex/view/common.vim
 54: ~/.vim/bundle/vimtex/autoload/vimtex/compiler.vim
 55: ~/.vim/bundle/vimtex/autoload/vimtex/compiler/latexmk.vim
 56: ~/.vim/bundle/vimtex/autoload/vimtex/qf.vim
 57: ~/.vim/bundle/vimtex/autoload/vimtex/qf/latexlog.vim
 58: ~/.vim/bundle/vimtex/autoload/vimtex/toc.vim
 59: ~/.vim/bundle/vimtex/autoload/vimtex/fold.vim
 60: ~/.vim/bundle/vimtex/autoload/vimtex/fold/envs.vim
 61: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_single_opt.vim
 62: ~/.vim/bundle/vimtex/autoload/vimtex/fold/markers.vim
 63: ~/.vim/bundle/vimtex/autoload/vimtex/fold/preamble.vim
 64: ~/.vim/bundle/vimtex/autoload/vimtex/fold/sections.vim
 65: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_addplot.vim
 66: ~/.vim/bundle/vimtex/autoload/vimtex/fold/env_options.vim
 67: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_multi.vim
 68: ~/.vim/bundle/vimtex/autoload/vimtex/fold/items.vim
 69: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_single.vim
 70: ~/.vim/bundle/vimtex/autoload/vimtex/context.vim
 71: ~/.vim/bundle/vimtex/autoload/vimtex/context/cite.vim
 72: ~/.vim/bundle/vimtex/autoload/vimtex/parser/fls.vim
 73: ~/.vim/bundle/vimtex/autoload/vimtex/bib.vim
 74: ~/.vim/bundle/vimtex/autoload/vimtex/cmd.vim
 75: ~/.vim/bundle/vimtex/autoload/vimtex/complete.vim
 76: ~/.vim/bundle/vimtex/autoload/vimtex/debug.vim
 77: ~/.vim/bundle/vimtex/autoload/vimtex/delim.vim
 78: ~/.vim/bundle/vimtex/autoload/vimtex/doc.vim
 79: ~/.vim/bundle/vimtex/autoload/vimtex/echo.vim
 80: ~/.vim/bundle/vimtex/autoload/vimtex/env.vim
 81: ~/.vim/bundle/vimtex/autoload/vimtex/format.vim
 82: ~/.vim/bundle/vimtex/autoload/vimtex/fzf.vim
 83: ~/.vim/bundle/vimtex/autoload/vimtex/include.vim
 84: ~/.vim/bundle/vimtex/autoload/vimtex/info.vim
 85: ~/.vim/bundle/vimtex/autoload/vimtex/kpsewhich.vim
 86: ~/.vim/bundle/vimtex/autoload/vimtex/log.vim
 87: ~/.vim/bundle/vimtex/autoload/vimtex/matchparen.vim
 88: ~/.vim/bundle/vimtex/autoload/vimtex/syntax.vim
 89: ~/.vim/bundle/vimtex/autoload/vimtex/pos.vim
 90: ~/.vim/bundle/vimtex/autoload/vimtex/misc.vim
 91: ~/.vim/bundle/vimtex/autoload/vimtex/motion.vim
 92: ~/.vim/bundle/vimtex/autoload/vimtex/process.vim
 93: ~/.vim/bundle/vimtex/autoload/vimtex/profile.vim
 94: ~/.vim/bundle/vimtex/autoload/vimtex/scratch.vim
 95: ~/.vim/bundle/vimtex/autoload/vimtex/text_obj.vim
 96: ~/.vim/bundle/vimtex/autoload/vimtex/ui.vim
 97: ~/.vim/bundle/vimtex/autoload/vimtex/text_obj/targets.vim
 98: /usr/share/vim/vim82/ftplugin/tex.vim 
  99: ~/.vim/bundle/vimtex/after/ftplugin/tex.vim
 100: ~/.vim/bundle/vimtex/indent/tex.vim
 101: /usr/share/vim/vim82/indent/tex.vim
 102: ~/.vim/bundle/vimtex/syntax/tex.vim
 103: /usr/share/vim/vim82/syntax/tex.vim
 104: ~/.vim/bundle/vimtex/after/syntax/tex.vim
 105: ~/.vim/bundle/vimtex/autoload/vimtex/syntax/after.vim
 106: ~/.vim/bundle/vimtex/autoload/vimtex/syntax/misc.vim
 107: ~/.vim/bundle/vimtex/autoload/vimtex/syntax/packages.vim
 108: ~/.vim/bundle/vimtex/autoload/vimtex/syntax/p/amsmath.vim
 109: ~/.vim/bundle/vimtex/autoload/vimtex/syntax/core.vim
 110: ~/.vim/personal/after/syntax/tex.vim

Output of :scriptnames for vim:
 1: ~/.vimrc-minim
 2: ~/.vim/autoload/vimrc.vim
  3: ~/.vim/autoload/plug.vim
  4: /usr/share/vim/vim82/filetype.vim
  5: ~/.vim/personal/ftdetect/dagbok.vim
  6: ~/.vim/personal/ftdetect/julia.vim
  7: ~/.vim/personal/ftdetect/text.vim
  8: /usr/share/vim/vim82/ftplugin.vim
  9: /usr/share/vim/vim82/indent.vim
 10: /usr/share/vim/vim82/syntax/syntax.vim
 11: /usr/share/vim/vim82/syntax/synload.vim
 12: /usr/share/vim/vim82/syntax/syncolor.vim
 13: ~/.vim/personal/plugin/log-autocmds.vim
 14: ~/.vim/personal/plugin/merge-mode.vim
 15: ~/.vim/personal/plugin/open-in-browser.vim
 16: ~/.vim/personal/plugin/text-object-indent.vim
 17: ~/.vim/personal/plugin/toggle-verbose.vim
 18: ~/.vim/personal/plugin/windows.vim
 19: ~/.vim/personal/plugin/zeal.vim
 20: ~/.vim/bundle/vimtex/plugin/vimtex.vim
 21: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
 22: /usr/share/vim/vim82/plugin/gzip.vim
 23: /usr/share/vim/vim82/plugin/logiPat.vim
 24: /usr/share/vim/vim82/plugin/manpager.vim
 25: /usr/share/vim/vim82/plugin/matchparen.vim
 26: /usr/share/vim/vim82/plugin/netrwPlugin.vim
 27: /usr/share/vim/vim82/plugin/rrhelper.vim
 28: /usr/share/vim/vim82/plugin/spellfile.vim
 29: /usr/share/vim/vim82/plugin/tarPlugin.vim
 30: /usr/share/vim/vim82/plugin/tohtml.vim
 31: /usr/share/vim/vim82/plugin/vimballPlugin.vim
 32: /usr/share/vim/vim82/plugin/zipPlugin.vim
 33: ~/.vim/personal/after/plugin/speeddating.vim
 34: /usr/share/vim/vim82/autoload/dist/ft.vim
 35: ~/.vim/personal/ftplugin/tex.vim
 36: ~/.vim/bundle/vimtex/autoload/vimtex/imaps.vim
 37: ~/.vim/bundle/vimtex/ftplugin/tex.vim
 38: ~/.vim/bundle/vimtex/autoload/vimtex.vim
 39: ~/.vim/bundle/vimtex/autoload/vimtex/options.vim
 40: ~/.vim/bundle/vimtex/autoload/vimtex/util.vim
 41: ~/.vim/bundle/vimtex/autoload/vimtex/state.vim
 42: ~/.vim/bundle/vimtex/autoload/vimtex/re.vim
 43: ~/.vim/bundle/vimtex/autoload/vimtex/parser.vim
 44: ~/.vim/bundle/vimtex/autoload/vimtex/parser/tex.vim
 45: ~/.vim/bundle/vimtex/autoload/vimtex/cache.vim
 46: ~/.vim/bundle/vimtex/autoload/vimtex/paths.vim
 47: ~/.vim/bundle/vimtex/autoload/vimtex/view.vim
 48: ~/.vim/bundle/vimtex/autoload/vimtex/view/general.vim
 49: ~/.vim/bundle/vimtex/autoload/vimtex/view/common.vim
 50: ~/.vim/bundle/vimtex/autoload/vimtex/compiler.vim
 51: ~/.vim/bundle/vimtex/autoload/vimtex/compiler/latexmk.vim
 52: ~/.vim/bundle/vimtex/autoload/vimtex/qf.vim
 53: ~/.vim/bundle/vimtex/autoload/vimtex/qf/latexlog.vim
 54: ~/.vim/bundle/vimtex/autoload/vimtex/toc.vim
 55: ~/.vim/bundle/vimtex/autoload/vimtex/fold.vim
 56: ~/.vim/bundle/vimtex/autoload/vimtex/fold/envs.vim
 57: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_single_opt.vim
 58: ~/.vim/bundle/vimtex/autoload/vimtex/fold/markers.vim
 59: ~/.vim/bundle/vimtex/autoload/vimtex/fold/preamble.vim
 60: ~/.vim/bundle/vimtex/autoload/vimtex/fold/sections.vim
 61: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_addplot.vim
 62: ~/.vim/bundle/vimtex/autoload/vimtex/fold/env_options.vim
 63: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_multi.vim
 64: ~/.vim/bundle/vimtex/autoload/vimtex/fold/items.vim
 65: ~/.vim/bundle/vimtex/autoload/vimtex/fold/cmd_single.vim
 66: ~/.vim/bundle/vimtex/autoload/vimtex/context.vim
 67: ~/.vim/bundle/vimtex/autoload/vimtex/context/cite.vim
 68: ~/.vim/bundle/vimtex/autoload/vimtex/parser/fls.vim
 69: ~/.vim/bundle/vimtex/autoload/vimtex/bib.vim
 70: ~/.vim/bundle/vimtex/autoload/vimtex/cmd.vim
 71: ~/.vim/bundle/vimtex/autoload/vimtex/complete.vim
 72: ~/.vim/bundle/vimtex/autoload/vimtex/debug.vim
 73: ~/.vim/bundle/vimtex/autoload/vimtex/delim.vim
 74: ~/.vim/bundle/vimtex/autoload/vimtex/doc.vim
 75: ~/.vim/bundle/vimtex/autoload/vimtex/echo.vim
 76: ~/.vim/bundle/vimtex/autoload/vimtex/env.vim
 77: ~/.vim/bundle/vimtex/autoload/vimtex/format.vim
 78: ~/.vim/bundle/vimtex/autoload/vimtex/fzf.vim
 79: ~/.vim/bundle/vimtex/autoload/vimtex/include.vim
 80: ~/.vim/bundle/vimtex/autoload/vimtex/info.vim
 81: ~/.vim/bundle/vimtex/autoload/vimtex/kpsewhich.vim
 82: ~/.vim/bundle/vimtex/autoload/vimtex/log.vim
 83: ~/.vim/bundle/vimtex/autoload/vimtex/matchparen.vim
 84: ~/.vim/bundle/vimtex/autoload/vimtex/syntax.vim
 85: ~/.vim/bundle/vimtex/autoload/vimtex/pos.vim
 86: ~/.vim/bundle/vimtex/autoload/vimtex/misc.vim
 87: ~/.vim/bundle/vimtex/autoload/vimtex/motion.vim
 88: ~/.vim/bundle/vimtex/autoload/vimtex/process.vim
 89: ~/.vim/bundle/vimtex/autoload/vimtex/profile.vim
 90: ~/.vim/bundle/vimtex/autoload/vimtex/scratch.vim
 91: ~/.vim/bundle/vimtex/autoload/vimtex/text_obj.vim
 92: ~/.vim/bundle/vimtex/autoload/vimtex/ui.vim
 93: ~/.vim/bundle/vimtex/autoload/vimtex/text_obj/targets.vim
 94: /usr/share/vim/vim82/ftplugin/tex.vim
 95: ~/.vim/bundle/vimtex/after/ftplugin/tex.vim
 96: ~/.vim/bundle/vimtex/indent/tex.vim
 97: /usr/share/vim/vim82/indent/tex.vim
 98: ~/.vim/bundle/vimtex/syntax/tex.vim
 99: /usr/share/vim/vim82/syntax/tex.vim
100: ~/.vim/bundle/vimtex/after/syntax/tex.vim
101: ~/.vim/bundle/vimtex/autoload/vimtex/syntax/after.vim
102: ~/.vim/bundle/vimtex/autoload/vimtex/syntax/misc.vim
103: ~/.vim/bundle/vimtex/autoload/vimtex/syntax/packages.vim
104: ~/.vim/bundle/vimtex/autoload/vimtex/syntax/p/amsmath.vim
105: ~/.vim/bundle/vimtex/autoload/vimtex/syntax/core.vim
106: ~/.vim/personal/after/syntax/tex.vim

The shell option appears to be undefined but when I run :shell it starts the default shell (zsh). I noticed that there seem to be a problem with zsh on gvim as there appear some garbadge characters
like this
```
[01;34m[ [31m11:43PM [01;34m] [01;34m [ [31mandrei@debian:~[33m[01;34m ][00m
 $ [?2004h
```

**Comment by lervag** [comment]
Thanks. So, essentially, with GVim you load these additional scripts:

* `~/.gvimrc`
* `/usr/share/vim/gvimrc`
* `/usr/share/vim/vim82/autoload/paste.vim`
* `/usr/share/vim/vim82/menu.vim`

I suspect the three last ones should not do anything relevant here. What's the content of the first of these, that is, `~/.gvimrc`?

I think the problem is related to the environment in which your GVim instance is running. It is not the same as the one you Vim is running in. That is, the output of `:env` is probably different with Vim and GVim.

**Comment by adhalanay** [comment]
I think I found the problem : looking in the global `gvimrc` i.e. `/usr/share/vim/gvimrc` the option `set noguipty` was commented out. After puting `set noguipty` in `~/.gvimrc` I get the desired result, i.e. `|lv` opens okular at the right spot.

**Comment by lervag** [comment]
> I think I found the problem : looking in the global `gvimrc` i.e. `/usr/share/vim/gvimrc` the option `set noguipty` was commented out. After puting `set noguipty` in `~/.gvimrc` I get the desired result, i.e. `|lv` opens okular at the right spot.

I assume that, given `|lv`, you use `|` as your localleader? In any case, I'm glad to hear you've figured it out. I was not aware of the `guipty` option, but then, I've not used GVim for ~10 years. In any case, you should probably read `:help gui-pty` to learn more what this option does and the drawbacks of doing `:set noguipty`.
