### ISSUE TITLE
Cursor disappearing in neovim (vimr), error refers to vimtex

### ISSUE THREAD

**Issue by krissen** [lervag/vimtex#1825]
**Issue**
I'm not sure if vimtex is to blame here, or if so in what manner. But I'm occasionally seeing the following error:

```
Error detected while processing function vimtex#context#menu[5]..138:
line 1:
E716: Key not present in Dictionary: name[1:] !~# self.re
E15: Invalid expression: a.cmd.name[1:] !~# self.re
```

It seems to ensue when I've been doing a search using `/`. What actually happens after the search --- and, really, what is mainly the annoyance --- is that the cursor disappears after the search. It is "invisible" while in normal mode and when entering `: text`. The cursor looks fine when in insert mode. Have yet to find a way except restarting vim to fix the cursor. The aforementioned error message appears when I press `enter`.

I'm primarily editing on macOS (10.15.7), using the latest snapshot ([357](https://github.com/qvacua/vimr/releases/tag/snapshot%2F357)) of vimr (a neovim GUI). I _feel_ that the issue is not happening on gvim but I'm not 100% sure. I haven't encountered the issue using nvim on the terminal, but not sure if it's because I'm not editing as extensively in the terminal as I am on the GUI. If I could reproduce the issue at will, I'd try, but...

**Comment by krissen** [comment]
Nevermind. I seem to get the same error-message even when vimtex is not loaded. (Not sure about the symptom though; haven't had the cursor disappear since I started vim without vimtex in order to troubleshoot.)

**Comment by lervag** [comment]
I think there was a minor bug that I've just fixed.

**Comment by lervag** [comment]
Happy to hear it :)

**Comment by krissen** [comment]
I encountered the issue a couple of times again, and now actually found a way to reproduce it reliably.

Using the following `vimrc`:
```
if &compatible
  set nocompatible
endif
" Add the dein installation directory into runtimepath
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  " my plugins
  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')
  call dein#add('lervag/vimtex')
  call dein#add('machakann/vim-sandwich')
  call dein#end()
  call dein#save_state()
endif

if dein#check_install()
  call dein#install()
endif

filetype plugin on
filetype indent on
syntax on

augroup filetypedetect
  au! BufRead,BufNewFile *.cls setfiletype tex
augroup END

let g:tex_flavor='latex'
```

And editing a text containing, for instance, the following: `this will, no doubt, work`.

Now, if I'm in normal mode and selecting the text `, no doubt,` and then press `sd` (i.e. vim-sandwich command `surround-delete`, the commas are indeed deleted --- but the cursor is also rendered invisible.

However, I can only reproduce it in vimr! (I've tried vim, nvim, gvim, and vimr.) So the bug is probably there rather than in vimtex.

**Comment by lervag** [comment]
Hmm. I don't know vimr. The mapping `sd` is not a vimtex mapping, so I think this is rather an issue with `vim-sandwich`. Are you saying that it is not reproducible without loading vimtex?

Can you reproduce with the following more minimal vimrc? (Of course, adapt the path to the bundles as appropriate on your system.)

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp = '~/.vim/bundle/vim-sandwich,' . &rtp
let &rtp .= ',~/.vim/bundle/vim-sandwich/after'
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

nnoremap q :qall!<cr>

let g:tex_flavor='latex'

silent edit test.tex
```

where `test.tex` contains the mentioned sentence? I.e., do `vimr -u test.vim` (I'm assuming vimr has the same options as regular Vim) to open the buffer.

**Comment by krissen** [comment]
I haven't tried it with your minimal vimrc, but I _have_ tried it with only `vim-sandwich`, and can confirm it has nothing to do with vimtex. It's a pure `vimr` + `vim-sandwich` issue.

**Comment by lervag** [comment]
Ok, thanks. Then I propose you open an issue with vim-sandwich. I suggest you also try my minimal vimrc (without vimtex and the `let g:tex_flavor ...` line), as it is much more minimal than yours.

Good luck!
