### ISSUE TITLE
Long strings in completion window truncated

### ISSUE THREAD

**Issue by flimofly** [lervag/vimtex#1826]
Apologies if this is not a vimtex problem, but this is something that is really bothering me and I can't seem to fix it. 

I have noticed that, in NeoVim (0.4.4) the completion window gets truncated when it runs wider than the window edge. So, when one adds a `\cite{}` near the right hand border the long title strings quickly run off screen and cannot be read.

I have tried to remedy this with `:let pumwidth=200` but haven't noticed any change.

Ideally, the completion window would show the menu with citation details (title, author, year) on the left side of the cursor when the completion window does not fit, or even wrap lines within the pop-up.

**Comment by lervag** [comment]
Yes, sorry, this is not a vimtex issue. It seems this is a bug that was reported already in 2007 and was fixed in Vim in 2018. The patch should be available also in neovim according [to this issue](https://github.com/neovim/neovim/issues/13085).

**Comment by lervag** [comment]
However, I'm not sure if this actually solves your issue. Setting `pumwidth` does not seem to work for me, at least. :\

**Comment by lervag** [comment]
And now I noticed you are the same person who opened the issue I just linked to...

**Comment by flimofly** [comment]
Thanks for the quick response here and over at the neovim issue, @lervag . 

I was looking into setting a very high minimum width for the popup window because that's what [someone suggested worked in vim](https://vi.stackexchange.com/questions/20525/float-ycm-completion-candidate-list-to-make-more-of-entry-previews-visible/20527#20527). 

Somehow it seems strange that this would not have been fixed yet -- seems like a bug that would annoy many.

**Comment by lervag** [comment]
I don't really know. For me, setting `pumwidth` really high seems to have an effect in Vim, but it looks buggy. Sometimes it is ignored, and the value doesn't really look very relevant. Not sure what is happening. In neovim, it seems way more buggy. :\
