### ISSUE TITLE
Something broke rnoweb syntax highlighting

### ISSUE THREAD

**Issue by emanuelealiverti** [lervag/vimtex#1827]
**Issue**
Rnoweb syntax (`.Rnw` files) does not work as expected.
Everything worked smoothly some time back, and indeed this issue is  **not** present, for example, in the `v1.4` checkout.
I thought it could be related with `vimtex-tex-flavor`, but setting it to different values (e.g. `"latex"` or `"plain"`) did not help.
Observed both with neovim 0.4.4 and with the most recent version v0.5.0-751-gd198aa511

**minimal.vim**

  ```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'lervag/vimtex'
call plug#end()
  ```

**minimal.Rnw**

  ```tex
\documentclass{article}
\usepackage[T1]{fontenc}

\begin{document}

Here is a code chunk.

<<foo, fig.height=4>>=
1 + 1
par(mar = c(4, 4, .2, .2))
plot(rnorm(100))
@

You can also write inline expressions, e.g. $\pi=\Sexpr{pi}$,
and \Sexpr{1.9910214e28} is a big number.

\end{document}
  ```
**Commands/Input**
```
vim -u minimal.vim minimal.Rnw
```

**Observed Behaviour**
Only the R syntax is correctly detected. 

**Expected Behaviour**
Both R and Tex syntax should be detected. 

```
cd path/to/vimtex
git checkout v1.4
vim -u minimal.vim minimal.Rnw
```
works as expected

**Output from VimtexInfo**
```
System info
  OS: Ubuntu 20.04.1 LTS
  Vim version: NVIM v0.5.0-751-gd198aa511
  Has clientserver: true
  Servername: /tmp/nvimrBoHTj/0

vimtex project: minimal
  base: minimal.Rnw
  root: /home/meme/GIT/issue
  tex: 
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 56
    fix_paths: 57
    set_errorformat: 55
  document class: 
```

**Comment by dennisjmoritz** [comment]
I am experiencing the same behavior.

**Comment by lervag** [comment]
Sorry, this is a "side effect" of a WIP, see #1799. I think I've found a simple way to circumvent and thus fix the issue. Let me know if I'm wrong. :)

**Comment by emanuelealiverti** [comment]
You were indeed right (as usual !) 
thanks a lot for the fix

**Comment by lervag** [comment]
No problem :)
