### ISSUE TITLE
How to change begin/end highlight colors?

### ISSUE THREAD

**Issue by rogershijin** [lervag/vimtex#1831]
Just got `vimtex` and the syntax highlighting alone is lifechanging.  However, begin/end marker syntax highlighting looks like this for me:

![image](https://user-images.githubusercontent.com/27650355/96204008-14f27d80-0f18-11eb-9a0e-e54e1bbdc591.png)

I find this a bit too loud, how can I go about changing this?  Thanks!

**Comment by lervag** [comment]
The highlight group is called `MatchParen`, you can see the highlight info with `:highlight MatchParen` and if you use `:verbose highlight MatchParen` you should also learn where it is defined.

So, to customize the colors, add a line similar to this:

**Comment by rogershijin** [comment]
Thank you! 
`autocmd filetype tex highlight MatchParen ctermbg=8` did the trick!

**Comment by lervag** [comment]
Great, happy to hear it :)
