### ISSUE TITLE
cannot invoke -shell-escape flag with \ll

### ISSUE THREAD

**Issue by leannejdong** [lervag/vimtex#1835]
I am using vimtex and compile with \ll. I tested with a single tex file and it works great. However I am working on a large latex project include multiple source file. It requires invoking LaTex with the -shell-escape flag as I am using the minted package. Could you suggest how we could fix the .vimrc or equivalence?

Instead I use my makefile and it seems compiling fine.

```make
filename=report
all:
	latexmk --shell-escape -pdf 
clean:
	rm -f *.ps *.pdf *.log *.aux *.out *.dvi *.bbl *.blg *.fls
open:
	evince ${filename}.pdf &
```

However I wish to use `\ll` in vim so that I can get the pdf quicker :)

**Comment by lervag** [comment]
There are two options:

1. Use a `.latexmkrc` file to specify the options. E.g. something like this:

    ```perl
    set_tex_cmds('-synctex=1 -interaction=nonstopmode --shell-escape %O %S');
    ```

2. Specify the option from your vimrc file with `g:vimtex_compiler_latexmk`:

    ```vim
    let g:vimtex_compiler_latexmk = {
        \ 'options' : [
        \   '--shell-escape',
        \   '-verbose',
        \   '-file-line-error',
        \   '-synctex=1',
        \   '-interaction=nonstopmode',
        \ ],
        \}
    ```

I personally go with option 1, since I sometimes use `latexmk` from a terminal. But both options should work.

**Comment by leannejdong** [comment]
thanks. I took your second suggestion.
I also use latexmk over the terminal with `latexmk --shell-escape -pdf
main.tex`
But I really prefer the `\ll` command as it bounds me back a pdf straight
away. With the terminal, I still have to manually invoke a pdf reader. It
was why I wrote a Makefile...

**Comment by lervag** [comment]
> With the terminal, I still have to manually invoke a pdf reader. It was why I wrote a Makefile...

Well, this only means you never learned how to use `latexmk`. The entire point of `latexmk` is to _avoid_ a Makefile. E.g., you can use `latexmk -pvc file.tex` to start "continuous" compilation that opens a previewer. You use `.latexmkrc` to specify the desired viewer and similar. I do recommend learning more about `latexmk`, but of course, if you're happy with the vimtex setup, then that's fine as well :)

**Comment by leannejdong** [comment]
that -pvc leads to a dvi file only. I add -pdf but it directed to xpdf which doesn't literally exist in my machine.
I do not see any issue of using makefile with latexmk. It does automatically clean up. I do not see any faster way than that...
Creating an extra .latexmkrc is extra amount effort, which is more time consuming using a single makefile. Make is powerful and multipurpose. I prefer to keep apps/plugins/tools minimum in my personal machines. The only two build tools I use is Make and CMake :)

**Comment by lervag** [comment]
> that -pvc leads to a dvi file only. I add -pdf but it directed to xpdf which doesn't literally exist in my machine.

You can specify the viewer in your `.latexmkrc` file.

> I do not see any issue of using makefile with latexmk. It does automatically clean up. I do not see any faster way than that...

You can clean up with `latexmk -c` (or `latexmk -C` to also clean the pdf file).

> Creating an extra .latexmkrc is extra amount effort, which is more time consuming using a single makefile. Make is powerful and multipurpose. I prefer to keep apps/plugins/tools minimum in my personal machines. The only two build tools I use is Make and CMake :)

You are already using `latexmk`, which is a build tool for latex. Adding some simple content to your `.latexmkrc` is not much effort, and it has benefits immediately. You no longer need to copy/write the Makefile, for instance.

A simple latexmkrc file that should "replicate" your Makefile:

```perl
# Specify to use PDF mode as default
$pdf_mode = 1;
$bibtex_use = 1.5;

# Specify a viewer
$pdf_previewer = "start evince";

# Show how much time was used to compile
$show_time = 1;

# Specify options used both for pdflatex, lualatex, etc
set_tex_cmds('-synctex=1 -interaction=nonstopmode --shell-escape %O %S');

# This ensures buffer flushing, which makes output better in vimtex
STDOUT->autoflush;
STDERR->autoflush;

# Add more extensions that should be removed with latexmk -c
push @generated_exts, "cb";
push @generated_exts, "cb2";
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "brf";
push @generated_exts, "nlg";
push @generated_exts, "nlo";
push @generated_exts, "nls";
push @generated_exts, "auxlock";
push @generated_exts, "synctex.gz";
push @generated_exts, "synctex(busy)";
push @generated_exts, "pgf-plot.*";
push @generated_exts, "run.xml";

# vim: ft=perl
```

See also [this Overleaf article](https://www.overleaf.com/learn/latex/Articles/How_to_use_latexmkrc_with_Overleaf:_examples_and_techniques) for more info. [This blog post](https://mg.readthedocs.io/latexmk.html) also looks good.
