### ISSUE TITLE
vimtex#init() never called when using vim-polyglot

### ISSUE THREAD

**Issue by rleathart** [lervag/vimtex#1837]
**Issue**
Recently, Vimtex has not been initialised when opening `.tex` files on both macOS and Linux when used in conjunction with [vim-polyglot](https://github.com/sheerun/vim-polyglot). Calling `vimtex#init()` manually solves this problem, but is obviously non-ideal.

**minimal.vim**
```vim
fun! PathJoin(...)
  return join(a:000, has('win32') ? '\' : '/')
endf

set nocompatible
let &rtp = PathJoin(stdpath('data'), 'plugged', 'vimtex') . ',' . &rtp
let &rtp .= PathJoin(stdpath('data'), 'plugged', 'vimtex', 'after')
let &rtp = PathJoin(stdpath('data'), 'plugged', 'vim-polyglot') . ',' . &rtp
let &rtp .= PathJoin(stdpath('data'), 'plugged', 'vim-polyglot', 'after')

filetype plugin indent on
syntax enable

let g:tex_flavor = 'latex'
```

**minimal.tex**
```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

**Commands/Input**
Just open `minimal.tex` using `minimal.vim` as an init file and then try to use Vimtex commands like `:VimtexInfo` etc.
```
nvim -u minimal.vim minimal.tex
```

**Observed Behaviour**
Vimtex is not initialised when entering the buffer. All autoload functions can be called manually, but commands like `:VimtexInfo`, `:VimtexCompile`, etc. are not available until after calling `vimtex#init()` manually.

**Expected Behaviour**
Vimtex commands should be available upon entering a `tex` buffer.

**Nvim `version`**
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include
Compiled by brew@Catalina

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.4/share/nvim"

Run :checkhealth for more info

```

**Nvim `checkhealth`**
```
health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - OK: General viewer should work properly!
  - OK: Compiler should work!

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date
```

**Comment by Char-Aznable** [comment]
I have the same problem and the zathura window is not open upon invoking forward search

**Comment by rleathart** [comment]
There's a similar issue [here](https://github.com/sheerun/vim-polyglot/issues/580) on the vim-polyglot repo. Seems a temporary solution is to ensure Vimtex appears before vim-polyglot in `runtimepath`. Is there a better fix for this?

**Comment by lervag** [comment]
No. And there will not be one, sorry. See the recent discussion on #1822. I think another solution can be to use the `g:polyglot_disabled` option?

However, I don't think this is a vimtex issue. Vimtex does the right things and respects the built in filetype and syntax plugins in the correct way.

**Comment by lervag** [comment]
@Char-Aznable Feel free to open a new issue about Zathura if you don't figure it out.

**Comment by sheerun** [comment]
Newest vim-polyglot should fix this - it tries to load other plugins first

**Comment by lervag** [comment]
Ah, that's nice! Thanks, both for addressing this issue and for giving the update here!
