### ISSUE TITLE
Open quickfix window only for tex files

### ISSUE THREAD

**Issue by lahwaacz** [lervag/vimtex#184]
When I edit for example a Gnuplot script in the same vim instance (on different tab), make a change and re-generate the files included in a tex document, latexmk properly detects the changes, re-compiles the pdf and runs the callback command. If there are errors/warnings, vimtex opens a quickfix window with the messages, but ignores the fact that the current buffer does not contain a tex document. Personally I find this a little annoying because the `\le` shortcut works only in tex files and the warnings are mostly irrelevant to the file being edited. Perhaps vimtex could check the filetype of the current buffer and open the quickfix window only if it is `tex`?

**Comment by lervag** [comment]
Strange. Could you provide a small example for me to test, and describe how to reproduce?

**Comment by lahwaacz** [comment]
We need a `minimal.tex` file which will issue a warning or error, the compilation of the following should fail with `Package babel Error: You haven't specified a language option.` (the error or content does not really matter, perhaps an empty file would be enough):
``` tex
\documentclass{book}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{babel}

\begin{document}
\end{document}
```
Then, with the following `minimal.vimrc` (adjust runtimepath as needed):
``` viml
set nocompatible

" runtimepath to load just vimtex and system plugins, including YCM
set runtimepath=$XDG_CONFIG_HOME/vim/bundle/vimtex,$VIM/vimfiles,$VIMRUNTIME,$VIM/vimfiles/after,$XDG_CONFIG_HOME/vim/bundle/vimtex/after

" load file type plugins
filetype plugin on

function Testing()
    :VimtexCompile
    :VimtexErrors
    :VimtexStop
    :VimtexCompile
    :tabnext
endfunction
```
run the following command, which will open the `minimal.tex` file and (supposedly) empty `foo.txt`, one file per tab:
```
vim --servername minimal -u minimal.vimrc -p minimal.tex foo.txt
```
And finally call the testing function:
``` viml
:call Testing()
```
Now I've been able to reproduce the issue only when the quickfix window is opened on the tex file, which happens often in the real world when the error/warning message is not related to the non-tex file being edited at the moment. The testing function is there because the compilation of the minimal example is really fast, but my current project takes ~20s to compile. There should be a quickfix window opened in both tabs after running the function.

**Comment by lervag** [comment]
Hi, I've reproduced the problem. I'm using the following minivimrc:
```vimL
nocompatible

" runtimepath to load just vimtex and system plugins
let &rtp = '~/.vim/bundle/vimtex,' . &rtp

" load file type plugins
filetype plugin on

function Testing()
  VimtexCompile
  VimtexErrors
  next
endfunction
```
Here I've stopped using tags and I set the `rtp` in a different way (so that vim starts faster). Now I run the test with
```sh
gvim --servername minimal -u minimal.vimrc minimal.tex foo.txt +'call Testing()'
```
Everything runs very fast, so I only see the file `foo.txt` open with the quickfix window also opened. I'll investigate what is happening when I get the time.

**Comment by lervag** [comment]
This was a relatively subtle bug, but I think I've solved it now. Could you please test?

**Comment by lahwaacz** [comment]
Yes, I think it's fixed. Sorry for the late reply again...

**Comment by lervag** [comment]
Great, and no problem!
