### ISSUE TITLE
Some vim-latex imap bindings don't work after installing vimtex

### ISSUE THREAD

**Issue by rogershijin** [lervag/vimtex#1842]
vim-latex imap bindings that start with ``` ` ``` aren't working (e.g. ``` `s ``` for `\sigma`) after installing vimtex.  Is there a way to turn vimtex imaps off?

**Comment by lervag** [comment]
I don't know what vim-latex is.

Yes, you can turn off vimtex imaps with `g:vimtex_imaps_enabled`, i.e. set it to 0 or `v:false`.

**Comment by rogershijin** [comment]
Thanks! That worked. And sorry I was talking about http://vim-latex.sourceforge.net/.

**Comment by lervag** [comment]
Ah, of course, sorry. I should have remembered that. I think vim-latex is better known as LaTeX-Suite (but I might be wrong).
