### ISSUE TITLE
Cannot open PDF through context menu on windows (issue with vimtex#process#run)

### ISSUE THREAD

**Issue by bratekarate** [lervag/vimtex#1843]
On Windows, I experienced issues with opening PDF files through the context menu on windows. I found out that this issue is not related to the context menu itself, but rather for the windows specific code run by `vimtex#process#run`.

I don't understand all of the code, but this is the culprit:

```vim
    if self.silent && self.output ==# 'null'
      let self.prepared_cmd = '"' . l:cmd . '"'
    else
      let self.prepared_cmd = l:cmd
    endif
```
The command is wrapped in quotes under certain conditions. This produces the following invalid command:

```
"start /b cmd /s /c "okular "FILE.pdf" >nul""
```
Commenting out the if statement and just use `l:cmd` solves the issue. I am wondering, why is this version necessary? What is wrapping with quotes supposed to achieve?

**Comment by lervag** [comment]
> I don't understand all of the code, but this is the culprit:
> 
> ```viml
>     if self.silent && self.output ==# 'null'
>       let self.prepared_cmd = '"' . l:cmd . '"'
>     else
>       let self.prepared_cmd = l:cmd
>     endif
> ```

I don't understand this myself, even. I never use Windows, and most of the windows related code has been implemented with help of others. However, I worry that changing this would break something else.

I'm not sure how to solve this. But perhaps one idea is for you to make a PR on this? I would be happy to merge it if it works for you and if you could also do some more testing and check if it breaks anything else. I can help with specifying what you should test.

**Comment by bratekarate** [comment]
I may be able to find time at some point in the future. The windows version is not my top priority either, and for now I just deleted the lines in `process.vim` to make it work. I am not sure how motivated I am myself to spend time on a windows only issue, but it might as well happen.

There are also more issues: the cmd command has issues with whitespaces in filenames. Not sure how complex this topic would get yet. I will report back if I had the time to look it through more thoroughly.

**Comment by lervag** [comment]
> I may be able to find time at some point in the future. The windows version is not my top priority either, and for now I just deleted the lines in `process.vim` to make it work. I am not sure how motivated I am myself to spend time on a windows only issue, but it might as well happen.

Great. I'll leave the issue open, then.

> There are also more issues: the cmd command has issues with whitespaces in filenames. Not sure how complex this topic would get yet. I will report back if I had the time to look it through more thoroughly.

I really thought this worked as expected. Strange. But again, I will need to rely on user contributions on this part as well.

**Comment by lervag** [comment]
I'm closing some old issues with no progress; please feel free to continue the discussion/reopen if you have more input.
