### ISSUE TITLE
Enhanced gf is broken again

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#1845]
A regression of #1646.

One of the recent commits has again broken the enhanced `gf` functionality, which was fixed earlier (on Apr 1, 2020).

**Comment by lervag** [comment]
Strange. As part of #1646 I've added tests, and these do not fail. Can you please provide a minimal example?

**Comment by krishnakumarg1984** [comment]
I think something was wrong in my setup. I think everything is working correctly. Apologies for the false alarm. I shall now close this issue.

**Comment by lervag** [comment]
No problem :)
