### ISSUE TITLE
search/replace in math environments only using in_mathzone or wrap_math?

### ISSUE THREAD

**Issue by bellecp** [lervag/vimtex#1846]
Thanks again for this great plugin.

**Is your feature request related to a problem? Please describe it.**

Feature request. It is sometimes very handy to search+replace in math mode only. For instance, I now would like to boldface all vectors x in mathmode with \mathbf{x}. However ``:%s/x/\\mathbf{x}/g`` obviously matches all the ``x`` in the text outside of math environments.

**Describe the solution you'd like**

Possibility to search/replace, if possible using vim's built-in replacement, but only in the math (both inline, display equations, align environment etc).

As vimtex already has syntax#in_mathzone and wrap_math, I an wondering if it would be easy to re-use these wrappers and achieve replacement in math mode only without too much work.

**Describe alternatives you've considered**
I usually achieve this by using vim's built-in replacement, say ``:%s/A/\\mathbf{A}/gc`` and skipping by hand and skipping all instances not in math zone by hand. Maybe it's possible to use in_mathzone to skip automatically the matches that are not in math environments.

**Comment by bellecp** [comment]
The closest working solution that I have so far is
```
:%s/beta/\=vimtex#syntax#in_mathzone() ? 'alpha' : submatch(0)/g
```
which somewhat does the job. However, with the ``c`` flag as in
```
:%s/x/\=vimtex#syntax#in_mathzone() ? '\mathbf{x}' : submatch(0)/gc
```
all the matches outside of the mathzone are not skipped (although the replacement would not affect them). It would be preferable to skip those matches and I am not sure how to achieve this.

**Comment by lervag** [comment]
> Thanks again for this great plugin.

Your welcome :D

> **Describe the solution you'd like**
> 
> Possibility to search/replace, if possible using vim's built-in replacement, but only in the math (both inline, display equations, align environment etc).

Thanks. I agree this could be useful.

> The closest working solution that I have so far is
> 
> ```
> :%s/beta/\=vimtex#syntax#in_mathzone() ? 'alpha' : submatch(0)/g
> ```

This was the first thing I thought of as well.

> which somewhat does the job. However, with the `c` flag as in
> 
> ```
> :%s/x/\=vimtex#syntax#in_mathzone() ? '\mathbf{x}' : submatch(0)/gc
> ```
> 
> all the matches outside of the mathzone are not skipped (although the replacement would not affect them). It would be preferable to skip those matches and I am not sure how to achieve this.

Interesting. I can't think of a simple/consistent way to do this with the same "syntax" as the built in `:s`. I think it should be possible to make a function like `vimtex#...#search_replace(pattern, replacement, ...)` that could do what you want, and then it should be possible to make a command that relies on this. I will have to think about it. Suggestions or ideas on how to achieve this could be useful. Both on making the command interface to a function and for how to achieve the search and replace loop similar to `:s/../../c`.

I'm currently working on #1834, which is a time consuming task. So I won't promise anything very soon.

**Comment by bellecp** [comment]
I have used ``:%s/beta/\=vimtex#syntax#in_mathzone() ? 'alpha' : submatch(0)/g``  a few times today and it is actually simpler to use that I thought. A nice outcome is that ``in_mathzone()`` already does the robust detection of math zones.

Vimtex clearly has more pressing issues than this! It sounds good to me to close this and we might reopen when someone thinks of a good implementation idea.

Related for search (not replace): since vim 8.2.0915, the ``search`` function takes a fifth argument ``skip`` that can be an expression evaluated to skip some results (source: https://vi.stackexchange.com/a/27008).

The same idea using ``\=`` posted on tex.stackexchange: https://tex.stackexchange.com/a/568696/207532 -- the question has alternatives for emacs.

**Comment by lervag** [comment]
> I have used `:%s/beta/\=vimtex#syntax#in_mathzone() ? 'alpha' : submatch(0)/g` a few times today and it is actually simpler to use that I thought. A nice outcome is that `in_mathzone()` already does the robust detection of math zones.

Yes, the `in_mathzone()` is quite useful :)

> Vimtex clearly has more pressing issues than this! It sounds good to me to close this and we might reopen when someone thinks of a good implementation idea.

Sounds good to me! Feel free to reopen (or open a fresh ticket) if you still want me to consider this.

> Related for search (not replace): since vim 8.2.0915, the `search` function takes a fifth argument `skip` that can be an expression evaluated to skip some results (source: https://vi.stackexchange.com/a/27008).

Yes, I use this feature in some parts of vimtex. In my initial ideas I was thinking of using `search` with a manual interface to mimic the `:s//c` functionality.

> The same idea using `\=` posted on tex.stackexchange: https://tex.stackexchange.com/a/568696/207532 -- the question has alternatives for emacs.

Nice!
