### ISSUE TITLE
Issue with Forward/Backward search on zathura and neovim.

### ISSUE THREAD

**Issue by bibek22** [lervag/vimtex#1847]
**Issue**
When I run `:VimtexCompile`, it's able to compile and open the pdf in zathura window. It also does update on save. However, when I do `:VimtexView`, it creates a new zathura window and doesn't open in the right position/page.

I've looked at the manual and I do have `xdotool` installed; version `3.20160805.1` and zathura is version `0.4.7`

I find the line `cmd: xdg-open '/home/bibek/minimal.pdf' >/dev/null 2>&1 &` on `VimtexInfo` to be suspect, but I don't know what to do about it.

**Steps to reproduce**
* neovim: `nvim -u minimal.vim minimal.tex`

**minimal.vim**
```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_viewer_method='zathura'
let g:tex_flavor='latex'
```

**minimal.tex**
```tex
\documentclass[]{article}

\begin{document}
\section{Introduction}
Intro here

\newpage
\section{Results}
Results here
\end{document}
```

**Commands/Input**
`\ll` and scroll down to the *Results* section of source and `\lv`

**Observed Behaviour**
Two instance of zathura is created, both document being opened at the same scroll location.

**Expected Behaviour**
Forward-search behaviour

**Output from VimtexInfo**
```
System info
  OS: Linux 5.9.1-arch1-1
  Vim version: NVIM v0.4.4
  Has clientserver: true
  Servername: /tmp/nvimkA0a3m/0

vimtex project: minimal
  base: minimal.tex
  root: /home/bibek
  tex: /home/bibek/minimal.tex
  out: /home/bibek/minimal.pdf
  log: /home/bibek/minimal.log
  aux: /home/bibek/minimal.aux
  fls: /home/bibek/minimal.fls
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: 3
    pid: 1106288
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$pdf_previewer = "xdg-open"' -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'minimal.tex'
  viewer: General
    process: 
      pid: -
      cmd: xdg-open '/home/bibek/minimal.pdf' >/dev/null 2>&1 &
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: article
```

**Comment by lervag** [comment]
Are you on Wayland or Xorg?

**Comment by bibek22** [comment]
I'm on Xorg with running dwm, if that matters.

**Comment by lervag** [comment]
Do things work if you close the first viewer; then do `\lv` and repeat `\lv`? I.e., if the viewer is opened with `\lv` and not `\ll`, do forward search work as expected?

**Comment by bibek22** [comment]
> Do things work if you close the first viewer; then do `\lv` and repeat `\lv`? I.e., if the viewer is opened with `\lv` and not `\ll`, do forward search work as expected?

Unfortunately, it doesn't. I just tried.

**Comment by lervag** [comment]
Ah, your option is wrong: The correct name is `g:vimtex_view_method`.
