### ISSUE TITLE
vimtex does not start and prints "g:tex_flavor not specified" error

### ISSUE THREAD

**Issue by horror-vacui** [lervag/vimtex#1848]
**Issue**
I got a warning about g:tex_flavor and vimtex is not loaded. My .vimrc is loaded and other plugins are working. I've got some problems before that vim my vimtex setup and I've recompiled vim and updated vimtex. After that I've got the error below. It seems to be a different issue than #1764. #1806 mentions this error, but I do not use wayland.

**Commands/Input**
`vim`. By starting vim, I got some warnings:
```
[>4;m[>4;2mvimtex: g:tex_flavor not specified
        Please read :help vimtex-tex-flavor!
Press ENTER or type command to continue
```
I am not sure why the strange characters got there. 
I've got the same response even with minimal.vim, except the strange characters are not there.

**Observed Behaviour**
Describe the observed behaviour.

**Expected Behaviour**
Vimtex works. 

**Output from VimtexInfo**
VimtexInfo does not start. E492: Not an editor command.

My [vimrc](https://github.com/horror-vacui/vimconfig/blob/master/.vimrc) contains the let g:tex_flavor command, and therefore I do not understand the issue, and I do not have enough knowledge to debug it further. 
```
$ git submodule status vimtex
 982185bb454942a5c04d41b647ab58fceb4e7683 vimtex (v1.5-10-g982185bb)
$ vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Nov  4 2020 12:56:24)
```
I am using currently Xubuntu 18.04.4 LTS.

BTW, what is "NB!" at the beginning? Does it stand for the latin "nota bene"? :)

**Comment by lervag** [comment]
The problem is that you are doing `packloadall` before you have defined `g:tex_flavor`. This will load all package scripts, including `plugin/vimtex.vim` from vimtex.

I suggest you either _don't_ do `packloadall` in your vimrc file (instead put the scripts you want to load on start in `/start`), or move the vimtex configuration before the `packloadall` command.
