### ISSUE TITLE
skim forward search (mac)

### ISSUE THREAD

**Issue by verga** [lervag/vimtex#185]
Before the latest commits, the code (in .vimrc)

    " forward search                                                               
        map <silent> <Leader>ls :silent                                               
        \ !/Applications/Skim.app/Contents/SharedSupport/displayline              
        \ <C-R>=line('.')<CR>                                                     
        \ "<C-R>=g:vimtex#data[b:vimtex.id].out()<CR>" "%:p"<CR>  

worked seamlessly with Skim.app in mac os. Now I get an error 
E121: Undefined variable: g:vimtex#data
E15: Invalid expression: g:vimtex#data[b:vimtex.id].out()

I noted the new vimtex#util#fnameescape, but I did not manage to find the correct syntax...

**Comment by lervag** [comment]
I am sorry for taking so long to reply! I've been very busy lately.

Luckily, this problem is easy to fix. You should change `g:vimtex#data[b:vimtex.id]` to `b:vimtex`, then everything should work as before.

**Comment by lervag** [comment]
I've just pushed a new update where I've tried to add support for Skim directly. Could you please test? Use `g:vimtex_view_method = 'skim'`. The mapping should be `\lv`.

I've used the forward search command as the main/default command. I do not use MacOS, so I can not test myself. I was wondering if one has to open Skim before using the `displayline` tool. If so, then I must update the implementation.

**Comment by verga** [comment]
I tried skim with the new version and \lv (viewer) is working. Backward and forward search also work, without need to open skim before. Everything seems OK! 

(I risk to be not so responsive this time: I have an intermittent internet connexion--I am abroad for 20 days).

**Comment by lervag** [comment]
Great. Thanks for testing. Let me know if there are problems or if you have suggestions for improvement.

**Comment by AlekseiSmirnov** [comment]
For me `g:vimtex_view_method = 'skim' ` doesn't work.
I'm getting an error:
```
vimtex warning: viewer skim does not exist!
- Please see :h g:vimtex_view_method
Press any key to continue ...,
Error detected while processing function vimtex#init[39]..<SNR>68_init_mappings:
line   94:

E716: Key not present in Dictionary: viewer, 'reverse_search')
E116: Invalid arguments for function has_key(b:vimtex.viewer, 'reverse_search')
E15: Invalid expression: has_key(b:vimtex.viewer, 'reverse_search')   
```

But it seems to work fine if I use code snippet for skim from documentation

**Comment by lervag** [comment]
`skim` is _not_ a valid `g:vimtex_view_method` option. As specified in the docs, the possible values are `general`, `mupdf` and `zathura`. Skim may be used through the `general` method with the options as specified in `:h vimtex_viewer_skim`.
