### ISSUE TITLE
Either vimtex or coc complains about "Pattern not found"

### ISSUE THREAD

**Issue by noib3** [lervag/vimtex#1850]
I'm not sure wheter this is vimtex's or coc's fault (feel free to close this issue if it's the latter), but if I `set noshowmode`, an error is shown every time I trigger a snippet. A minimal `init.vim` (or `.vimrc`) to test this is:

```vim
call plug#begin('~/.config/nvim/plugged')
  Plug 'neoclide/coc.nvim'
  Plug 'lervag/vimtex'
call plug#end()

set noshowmode

let g:tex_flavor = "latex"

let g:coc_global_extensions = [
\   "coc-snippets",
\   "coc-vimtex",
\ ]

" coc-snippets
imap <Tab> <Plug>(coc-snippets-expand-jump)
let g:coc_snippet_prev = "<S-Tab>"
```

with the snippet

```vim-snippet
snippet md "Make dollar" A
$$1$
endsnippet
```

which on my machine behaves like this

![2020-Nov-08@18:39:32](https://user-images.githubusercontent.com/59321248/98472322-91643d80-21f2-11eb-952f-490a93ad9cf3.gif)

**Comment by lervag** [comment]
I am quite sure this is not a vimtex issue; it looks more like a coc.nvim issue or config related issue. That is, it looks like something related to automatic completion that for some reason is triggering here.
