### ISSUE TITLE
Vimtex-info not working and understanding continuous compiling

### ISSUE THREAD

**Issue by Princeofthebow** [lervag/vimtex#1855]
**EDIT please disregard the submitted issue a restart has solved the issue.**

--------------

Hi I have ran in a problem using vimtex and as I'm rather new to using vim and vimtex I'm positing my issue as I mightbe doing somethings wrong.

Here is the problem I encounter:

when running `\li` or `:VimtexInfo` (I run Vim 8.1 in Debian) I get:

```
Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..191:
line    4:
E37: No write since last change (add ! to override)
```
However, compiling works well(I enable continuous compiling via `\ll`) for the following vimrc configuration:
```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

let g:tex_flavor = 'latex'
```

Here my tex file:

```
\documentclass{article}
\begin{document}
  Hello World! 
\end{document}
```

As a side note: is there a way to have mupdf to update the file once i give a `:w` and hence the compiling runs again?

Thanks for the great work!

**Comment by lervag** [comment]
> **EDIT please disregard the submitted issue a restart has solved the issue.**

No problem! Happy to hear you figured it out!

> Hi I have ran in a problem using vimtex and as I'm rather new to using vim and vimtex I'm positing my issue as I mightbe doing somethings wrong.

I hope you find learning vim (and vimtex) to be fun and useful :)

> As a side note: is there a way to have mupdf to update the file once i give a `:w` and hence the compiling runs again?

I think this should be automatic if you have `xdotool` installed. Are you using Wayland or Xorg?

> Thanks for the great work!

Happy you enjoy it!

**Comment by Princeofthebow** [comment]
I'm using Xorg and it immediately started working after I specified to us mupdf i the settings! 
I'm still familiarising with vim and vimtex but making progress!

May Lyapunov protect your stability!

**Comment by lervag** [comment]
Thanks :) (I'm guessing [this Lyapunov](https://en.wikipedia.org/wiki/Aleksandr_Lyapunov)? Seems like an interesting guy!)
