### ISSUE TITLE
Quickfix window not automatically showing up on OS X

### ISSUE THREAD

**Issue by lifepillar** [lervag/vimtex#186]
I am trying Vimtex, and I have an issue with the quickfix window. According to the manual, using the default settings the quickfix window is supposed to automatically open when there are errors. That is not the case for me: I have to open it manually with `\le`. Besides, when the document is compiled and the quickfix window is already opened, it is not updated: I have to close an re-open it. I have tried to install `pgrep`, too, but it does not make a difference.

This is not a problem with clientserver, because LaTeX-Box works as expected.

I am using the latest MacVim, and I have checked that both `g:vimtex_latexmk_callback` and `g:vimtex_latexmk_continuous` are set to 1.

**Comment by lervag** [comment]
Hi! First, sorry for taking so long!

Could you please report your related `vimrc` settings/options for vimtex and the version of vim you are using (output of `:version`).

I would also be very happy if you could reproduce your problem with a minimal working example and a minimal vimrc file. The following is an example of a minimal vimrc file:
```vimL
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
filetype plugin indent on
syntax enable
```
And this is an example of a minimal tex file:
```tex
\documentclass{minimal}
\begin{document}
Hello world! \adderrorcommand
\end{document}
```
Here `\adderrorcommand` will not compile, and so this should open the quickfix window after `\ll`.

**Comment by lifepillar** [comment]
I am not using any custom settings, just the defaults. The same problem exists with your minimal setup, too.

I have tried to debug the problem. The function `vimtex#latexmk#callback()` is not called. The command `:echo  b:vimtex.cmd_latexmk_compile` shows this:

```
cd '/Users/me/Documents/Outbox' && max_print_line=2000 latexmk -pdf -e '$pdflatex =~ s/ / -file-line -error /' -pvc -e '$success_cmd = "Vim --servername VIM --remote-expr \"vimtex\#latexmk\#callback(1)\""' -e '$failure_cmd = "Vim --servername VIM --remote-expr \"vimtex\#latexmk\#callback(0)\""' -e '$new_viewer_always = "0"' -e '$pdf_update_method = "0"' -e '$pdf_previewer = "start open "' 'test.tex' >/var/folders/hb/ptth9qcs0951rm0r990kw_pm0000gn/T/vY2o110/2 2>&1   
```

`Vim` is not the correct command here, because that invokes terminal Vim (I am using MacVim): `gvim` or `mvim` should be used. Is there a way to change this through some settings?

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jun  5 2015 17:21:34)
MacOS X (unix) version
Included patches: 1-712
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl             +diff            +jumplist        +mouse_urxvt     +signs           +visual
+arabic          +digraphs        +keymap          +mouse_xterm     +smartindent     +visualextra
+autocmd         +dnd             +langmap         +multi_byte      -sniff           +viminfo
+balloon_eval    -ebcdic          +libcall         +multi_lang      +startuptime     +vreplace
+browse          +emacs_tags      +linebreak       -mzscheme        +statusline      +wildignore
++builtin_terms  +eval            +lispindent      +netbeans_intg   -sun_workshop    +wildmenu
+byte_offset     +ex_extra        +listcmds        +odbeditor       +syntax          +windows
+cindent         +extra_search    +localmap        +path_extra      +tag_binary      +writebackup
+clientserver    +farsi           +lua             +perl            +tag_old_static  -X11
+clipboard       +file_in_path    +menu            +persistent_undo -tag_any_white   -xfontset
+cmdline_compl   +find_in_path    +mksession       +postscript      +tcl             +xim
+cmdline_hist    +float           +modify_fname    +printer         +terminfo        -xsmp
+cmdline_info    +folding         +mouse           +profile         +termresponse    -xterm_clipboard
+comments        -footer          +mouseshape      -python          +textobjects     -xterm_save
+conceal         +fork()          +mouse_dec       +python3         +title           -xpm
+cryptv          +fullscreen      -mouse_gpm       +quickfix        +toolbar
+cscope          -gettext         -mouse_jsbterm   +reltime         +transparency
+cursorbind      -hangul_input    +mouse_netterm   +rightleft       +user_commands
+cursorshape     +iconv           +mouse_sgr       +ruby            +vertsplit
+dialog_con_gui  +insert_expand   -mouse_sysmouse  +scrollbind      +virtualedit
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -D
MACOS_X_UNIX  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1     -I/System/Library/Frameworks/Tcl.framewor
k/Headers  -D_REENTRANT=1  -D_THREAD_SAFE=1  -D_DARWIN_C_SOURCE=1
Linking: clang   -L. -L/usr/local/lib -L. -L/usr/local/lib  -L/usr/local/lib -o Vim -framework Cocoa -fr
amework Carbon       -lm  -lncurses -liconv -framework Cocoa  -pagezero_size 10000 -image_base 100000000
 -L/usr/local/lib -lluajit-5.1 -fstack-protector  -L/System/Library/Perl/5.18/darwin-thread-multi-2level
/CORE -lperl  -L/usr/local/Cellar/python3/3.4.3/Frameworks/Python.framework/Versions/3.4/lib/python3.4/c
onfig-3.4m -lpython3.4m -framework CoreFoundation -F/System/Library/Frameworks -framework Tcl -framework
 CoreFoundation -framework Ruby
```

**Comment by lervag** [comment]
Ah, I see. In MacVim, what does `:echo v:progname` return?

**Comment by lervag** [comment]
In an earlier version I added support for MacVim, see #83. Due to some tips about `v:progpath` and `v:progname`, I updated the code through #101. I've not heard about any problems since then.

I think the essential part here is that MacVim does not have the correct `v:progname`. This should be verified when you show the output of `:echo v:progname`. Please also provide the output of `:echo v:progpath`.

My initial idea is to allow an option to set the correct executable and use this option if it is set.

**Comment by lifepillar** [comment]
Ah, I see, `v:progrname` is `Vim` and `v:progpath` is `/usr/local/Cellar/macvim/7.4-76/MacVim.app/Contents/MacOS/Vim`. But Homebrew MacVim does not create symbolic links to `Vim` in PATH.

**Comment by lervag** [comment]
I've pushed an update that brings two changes:

1. We use `v:progpath` as default value if it is available.
2. Added option `g:vimtex_latexmk_progname`, which may be used to set the callback vim executable manually to for instance `mvim` or `gvim`.

I think the new option should solve the problem.

**Comment by lifepillar** [comment]
Great, thanks! I haven't tried the new option, the update now works out of the box with MacVim.

**Comment by lervag** [comment]
Great! I'm glad to hear. I think it would require a manual touch for older versions of vim where `v:progpath` is not available.
