### ISSUE TITLE
Syntax highlighting problem with array package

### ISSUE THREAD

**Issue by krypt-n** [lervag/vimtex#1866]
In the following minimal example, `\end{array}` is in the syntax group `texMathError` and thus highlighted in red. I think this is not correct since pdflatex compiles it without any errors or warnings and two slight modifications yield the expected highlighting. The syntax highlighting in the array is also slightly different and features like `conceal` don't work, but I suspect this is just a side effect.

```tex
\documentclass{minimal}
\usepackage{array}

\begin{document}
$$
\begin{array}{c}
\end{array}
$$
\end{document}
```
The two slightly different versions that are highlighted as expected are:

```tex
\documentclass{minimal}

\begin{document}
$$
\begin{array}{c}
\end{array}
$$
\end{document}
```
and
```tex
\documentclass{minimal}
\usepackage{array}

\begin{document}
\[
\begin{array}{c}
\end{array}
\]
\end{document}
```

This can also be observed with a minimal vimrc. My version of the `array` package is `array 2019/08/31 v2.4l Tabular extension package (FMi)`. I have not yet tested if the newest version of the package fixes the problem.

**Observed Behaviour**
`\end{array}` has the syntax group `texMathError`

**Expected Behaviour**
`\end{array}` has the syntax group `['texMathRegion', 'texMathCmdEnv', 'texCmdMathEnv']` (this is taken from the second example that is highlighted as expected)  or something functionally equivalent.

**Output from VimtexInfo**
```
System info
  OS: Linux 5.9.8-arch1-1
  Vim version: VIM 8.2 (1-1989)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

vimtex project: test
  base: test.tex
  root: /home/mfunk
  tex: /home/mfunk/test.tex
  out: /home/mfunk/test.pdf
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: MuPDF
    xwin id: 0
  qf: LaTeX logfile
    addqflist: 62
    fix_paths: 63
    set_errorformat: 61
  document class: minimal
  packages:
    array
```

**Comment**
I am no expert in either latex or vim syntax highlighting, so please don't hesitate to close this issue if a misunderstanding on my part causes it. Also, I do realise that providing consistent and useful syntax highlighting of latex, especially in the presence of `$$` and redefinition of environments, is very complicated if not impossible. In the larger picture this is just something that I discovered while experimenting with the new vimtex features and I may be able to convince my coauthors to use `\[` instead of `$$` :sweat_smile:.
And finally I want to mention that vimtex is a very important part of my workflow and has been for years. Thank you for creating this very useful piece of software!

**Comment by Rmano** [comment]
Hi!, let me just chime in: `$$` is *not* LaTeX, and you shouldn't use it. This: https://tex.stackexchange.com/a/69854/38080 is a comment by David Carlisle himself --- he is one of the LaTeX2ε authors. Things like `fleqn` and `amsmath` and most of the modern format for journals will be royally confused by it ;-) 

So I do not think if this is classifiable as a LaTeX highlighting problem...

**Comment by krypt-n** [comment]
I am aware of that and I don't use `$$` in documents I write myself. However when collaborating on documents, I find it difficult to argue that my colleagues should change their habits if the only thing that is impacted is my syntax highlighting. As I said, I can live with this being out of scope for vimtex, but if there is an easy fix, it would be nice to fix.

**Comment by Rmano** [comment]
Yes ;-), I agree with you. Using `$$` is a minor problem (I have one PhD student that insists on using `\\` to end every paragraph).

**Comment by Rmano** [comment]
Btw, I have also you second example mis-highlighted: 

![image](https://user-images.githubusercontent.com/6414907/100247470-ad7a1580-2f3a-11eb-9564-a9e61e99a3f3.png)

**Comment by krypt-n** [comment]
Have you made sure that vimtex doesn't think that the `array` package is included? I had to delete my temporary files and restart vim in order for vimtex to notice that I removed `\usepackage{array}`. (I think `array` appears in `:VimtexInfo` if this is the case)

**Comment by Rmano** [comment]
Ah, ok, you're right. Removing temporary files and restarting vim gives the same result you have. Sorry for the noise.

![image](https://user-images.githubusercontent.com/6414907/100258089-eb7d3680-2f46-11eb-8370-31ec45e836f8.png)

**Comment by lervag** [comment]
I'm sorry, but I can't reproduce this. Can you explain how to reproduce it properly?

**Comment by krypt-n** [comment]
I am not sure I can.
If I run `vim -u minimal.vim test.tex`, where `test.tex` is the first snippet mentioned above and `minimal.vim` is the minimal vimrc from your issue template (which should load vimtex `1f5ec9c753ff4d1e2567ee233c337fcf2af8ad8b`), the line `\end{array}` appears in red.

For figuring out that `texMathError` is the cause of the red color, I used the following snippet found via google:
```vim
function! SynStack()
  if !exists("*synstack")
    return
  endif
  echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")')
endfunc
```
I am not sure if the snippet is correct.

If our vim and vimtex versions are the same, I have no idea why you can't reproduce this and could only speculate.

**Comment by krypt-n** [comment]
I can reproduce the problem using the vimtex-test docker container

**Comment by krypt-n** [comment]
Sorry for the spam, but I think I found the reason for the behaviour I am observing.

`core.vim` contains the definition of the syntax region for `$$`. Note how the syntax region for `$` is defined before the one for `$$`.

https://github.com/lervag/vimtex/blob/1f5ec9c753ff4d1e2567ee233c337fcf2af8ad8b/autoload/vimtex/syntax/core.vim#L349

`array.vim` is loaded when vimtex thinks that the `array` package is used and contains a rule that redefines the syntax region for `$`.

https://github.com/lervag/vimtex/blob/1f5ec9c753ff4d1e2567ee233c337fcf2af8ad8b/autoload/vimtex/syntax/p/array.vim#L15

In the snippet
```tex
$$
\begin{array}{c}
\end{array}
$$
```

`$$` is interpreted as a pair of `$` if array.vim is loaded (`texMathRegionX`) and not as the start of `texMathRegionXX`. This causes the syntax problems that lead me to open this issue.
If I
* either remove the redefinition of the `texMathRegionX` syntax group from array.vim
* or add a the same definition of `textMathRegionXX` to the end of array.vim,
this issue disappears.

`:help syn-priority` furthermore says:
```
When several syntax items may match, these rules are used:

1. When multiple Match or Region items start in the same position, the item
   defined last has priority.
```
thus I propose the following patch for array.vim:
```diff
diff --git a/autoload/vimtex/syntax/p/array.vim b/autoload/vimtex/syntax/p/array.vim
index 42a90dea..4c446476 100644
--- a/autoload/vimtex/syntax/p/array.vim
+++ b/autoload/vimtex/syntax/p/array.vim
@@ -18,6 +18,17 @@ function! vimtex#syntax#p#array#load(cfg) abort " {{{1
         \ (&encoding ==# 'utf-8'
         \     && g:vimtex_syntax_conceal.math_delimiters
         \   ? 'concealends' : '')
+
+  " Redefine syntax region for $$, since the above would have higher priority
+  "
+  " See issue https://github.com/lervag/vimtex/issues/1866
+  "
+  if g:vimtex_syntax_conceal.math_bounds
+    syntax region texMathRegionXX matchgroup=texMathDelimRegion concealends contains=@texClusterMath keepend start="\$\$" end="\$\$"
+  else
+    syntax region texMathRegionXX matchgroup=texMathDelimRegion contains=@texClusterMath keepend start="\$\$" end="\$\$"
+  endif
+
 endfunction
 
 " }}}1
```
However, there might be a more elegant approach to solve this problem. And sadly this doesn't explain why you cannot reproduce it.

**Comment by lervag** [comment]
Thanks for looking more into it. I've tried to understand why I've added the special `texMathRegionX` match in `array.vim`, but I failed to find a good reason for it. I've therefore simply removed it. I believe this should both solve the issue and not really remove any important syntax features.

**Comment by krypt-n** [comment]
Thanks a lot. Works perfectly now

**Comment by lervag** [comment]
Great, happy to hear it!

**Comment by lervag** [comment]
Just a friendly heads up: I've changed `texMathRegion` back to `texMathZone` (and similar for all related `*Region` groups).
