### ISSUE TITLE
Compatibility issue with Vim 8.1 and older in Vimtex 2.0

### ISSUE THREAD

**Issue by danchieta** [lervag/vimtex#1867]
When using Vimtex 2.0 with Vim 8.1.1401, I got the following error message right after opening a file:

    "tomate.tex" [New File]                                                              
    Error detected while processing User Autocommands for "VimtexEventInitPost":         
    E492: Not an editor command: ++once call vimtex#syntax#packages#init() 

Which is a command in /syntax/tex.vim.
Apparently, the ++once option was introduced in Vim 8.2 and causes this error in previous versions.

**Comment by lervag** [comment]
Thanks, I've removed the `++once`; I think this should work as expected now.
