### ISSUE TITLE
Issue with syntax

### ISSUE THREAD

**Issue by metaMockery** [lervag/vimtex#1868]
**Issue**
Error upon opening any .tex file. Tried with minimal.tex/.vim, all the same.
I'm using vim-plug and vim-8.2

Screenshot (I tried to translate to the best of my abilities)
![Снимок экрана (114)](https://user-images.githubusercontent.com/20060969/100269574-cea52b00-2f67-11eb-8282-821f145f726c.png)

I'm not using any commands.
Problem lies with syntax. If I make `vimtex_syntax_enabled=0`, everything is okay. It compiles, works, etc.

**Comment by lervag** [comment]
As a temporary solution, you can set

```vim
let g:vimtex_syntax_conceal = {'math_super_sub': 0}
```

You say you tried with minimal files, but, for sake of completeness, can you post the minimal files you use and the exact steps to reproduce?

**Comment by metaMockery** [comment]
Here, minimal.tex and minimal.vim nice and clear.
![Снимок экрана (115)](https://user-images.githubusercontent.com/20060969/100279520-c3f29200-2f77-11eb-9f6c-8f39e77a55ff.png)

Also you can see error after I made `let g:vimtex_syntax_conceal = {'math_super_sub': 0}`

**Comment by lervag** [comment]
I think this may come from encodings, but I'm not sure. I can't reproduce it, sorry.

You still don't really provide the steps you use to create the error. That is, how do you run Vim with the minimal configuration? If you think a video is the best way to show it, that's OK. But I do prefer text that is written in a clear and concise manner.

Another option for preventing the issue is `let g:vimtex_syntax_conceal_default = 0`.

**Comment by lervag** [comment]
To give an example of what I want:

1. Change `_vimrc` file to:

    ```vim
    set nocompatible
    let &rtp = '~/.vim/plugged/vimtex,' . &rtp
    filetype plugin indent on
    syntax enable
    ```

    With this, Vim will start with the minimal configuration when I open it.

2. Now open the `minimal.tex` file via the File open menu.

3. Observe the described error.

Alternative:

1. Given `minimal.vim` file (as above) and `minimal.tex` file, start Vim from a Windows terminal with `vim -u minimal.vim minimal.tex`.

2. Observe the described error.

----

Also, something that will be useful. In the case when you start with a minimal vimrc file and observe the error. Can you, after Vim has opened, do `:scriptnames` and copy the content here (or screenshot)?

It is also useful to see the output of `:VimtexInfo`.

**Comment by metaMockery** [comment]
Well okay, that worked `let g:vimtex_syntax_conceal_default = 0`. 
I tried to open .tex with pretty simple _vimrc on video. Just vimtex and colorscheme. 

Also video (https://drive.google.com/file/d/1b7DU3EnDyh2ChYKUidZ2YY93VGOepQXH/view?usp=sharing)

**Comment by metaMockery** [comment]
Actually I think that was encoding error. I tried 'set enc=utf8' and it works fine.
Sorry to bother!

**Comment by lervag** [comment]
Yes, I expected this was an encoding issue, but I still would like to understand how to ensure people don't unexpectedly get them.

**Comment by lervag** [comment]
> Well okay, that worked `let g:vimtex_syntax_conceal_default = 0`.
> I tried to open .tex with pretty simple _vimrc on video. Just vimtex and colorscheme.
> 
> Also video (https://drive.google.com/file/d/1b7DU3EnDyh2ChYKUidZ2YY93VGOepQXH/view?usp=sharing)

Thank you, the video makes things quite clear.

Perhaps it should be documented that users need to set `encoding`?

**Comment by metaMockery** [comment]
Yes, apparently it's a common problem for plugins on vim. It's easily solved by setting encoding to utf8 `set enc=utf8` in your vimrc.

This problem originates from default encoding for your Vim. (For example in ru-version of Vim, default enc is cp1251, if you try to set it on utf8 it will mess up your menu -- there will be nonsensical symbols, but it will solve issue with plugin)


![Снимок экрана (128)](https://user-images.githubusercontent.com/20060969/100384390-1cd23100-3031-11eb-84e0-2ac091e558ea.png)

**Comment by lervag** [comment]
I have to admit I don't really know how to address this problem. Is it possible for you to use the english version of Vim, for instance?

**Comment by lervag** [comment]
Does it help to use `:menutranslate`?
