### ISSUE TITLE
file name changes

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#187]
Hello,

May vimtex be agnostic to a name change of the main tex file? Would a `BufFilePre` autocmd come to the remedy?

For example, a `VimtexCompileToggle` followed by a rename of the TeX file `old.tex` to `new.tex`, and twice `VimtexCompileToggle` seems to continue compiling `old.tex`.

**Comment by lervag** [comment]
Sorry for taking so long to reply. I've been quite busy with my life lately, and I've been trying to keep up with other issues as well.

I've pushed an update that should implement the desired feature. I'm also pushing some minor improvements in a few minutes. Please test and see if this works as you would expect.

**Comment by Konfekt** [comment]
Thanks a lot! No need for hurry nor excuses, rarely anywhere else issues without pull requests are closed as fast as over here.

**Comment by lervag** [comment]
:D
