### ISSUE TITLE
Spell checker complains about some env names

### ISSUE THREAD

**Issue by j1-lee** [lervag/vimtex#1871]
Thank you for the huge update!

**Issue**
After v2.0, spell checker marks some environment names (such as displaymath, pmatrix, and bmatrix as shown below) as wrong.

I am using Neovim 0.4.3 on mate-terminal.

**minimal.vim**
```vim
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()

let g:tex_flavor = 'latex'
set spell
```
(Here I added `let g:tex_flavor = 'latex'` to compare the result with v1.6.)

**minimal.tex**
```tex
\documentclass{article}
\usepackage{amsmath}

\begin{document}
\begin{displaymath}
	a^n + b^n = c^n.
\end{displaymath}

\begin{align*}
	1 + 1 \neq 0.
\end{align*}

\begin{gather*}
	\begin{matrix}
		1 & 2\\
		3 & 4
	\end{matrix}
	\quad
	\begin{pmatrix}
		1 & 2\\
		3 & 4
	\end{pmatrix}
	\quad
	\begin{bmatrix}
		1 & 2\\
		3 & 4
	\end{bmatrix}
\end{gather*}
\end{document}
```

**Observed Behaviour**
The following is what I see after updating vimtex to v2.0. As we can see, the env names (displaymath, pmatrix, and bmatrix) are marked in red by the spell checker, whereas others (such as gather, align, and matrix) are not.
![v2 0](https://user-images.githubusercontent.com/47399860/100527145-88d1a800-319d-11eb-8630-38cbc1beee34.png)

In comparison, in v1.6, those were not marked, as follows.
![v1 6](https://user-images.githubusercontent.com/47399860/100527148-8b340200-319d-11eb-8735-a1e9b8a478bc.png)

**Expected Behaviour**
The env names displaymath, pmatrix, and bmatrix are expected to be not checked by the spell checker. I guess there are more env names like this...

**Comment by lervag** [comment]
> Thank you for the huge update!

I'm glad you like it!

> **Issue**
> After v2.0, spell checker marks some environment names (such as displaymath, pmatrix, and bmatrix as shown below) as wrong.

Thanks, you are right. I've fixed it now. Note, there may definately be more places where spell checking should be deactivated. I would be happy to fix if you find and report them.

**Comment by clason** [comment]
This one may be controversial, but I feel that `texComments` would be better not spell checked.

I've also noticed spell checking in `[sub]figure` options.

Also, the contents of `asy` environments are spell checked but shouldn't; these don't have any syntax group that I can see, though?

**Comment by lervag** [comment]
> This one may be controversial, but I feel that `texComments` would be better not spell checked.

At the very least, opinionated. Does it warrant an option?

> I've also noticed spell checking in `[sub]figure` options.

It would be nice with an example. :)

> Also, the contents of `asy` environments are spell checked but shouldn't; these don't have any syntax group that I can see, though?

I think this was fixed now.

> Finally, `bibKey`, `bibEntryKw`, and `bibVariable` are spell checked but shouldn't.

I don't think these are defined in Vimtex? Perhaps a project for a later time?

**Comment by clason** [comment]
> > I've also noticed spell checking in `[sub]figure` options.
> 
> It would be nice with an example. :)

Fair :) I'm talking about the `t` in 

```tex
\begin{subfigure}[t]{.45\textwidth}
```

> > Also, the contents of `asy` environments are spell checked but shouldn't; these don't have any syntax group that I can see, though?
> 
> I think this was fixed now.

Not that I can see? (Even after updating right now.)

> > Finally, `bibKey`, `bibEntryKw`, and `bibVariable` are spell checked but shouldn't.
> 
> I don't think these are defined in Vimtex? Perhaps a project for a later time?

Oh, sorry, I thought they were! Somehow I assumed that you "tex syntax plugin" also included "bib syntax plugin", but that's of course an unwarranted assumption :)

Yes, if you're _really_ bored and miss working on the tex syntax, that could be a new project ;)

**Comment by lervag** [comment]
> Fair :) I'm talking about the `t` in
> 
> ```
> \begin{subfigure}[t]{.45\textwidth}
> ```

I've fixed an error with the `texEnvOpt` group; how does this look now?

> > I think this was fixed now.
> 
> Not that I can see? (Even after updating right now.)

Strange. In that case, it would help if (again) you could give an example. :)

> > > Finally, `bibKey`, `bibEntryKw`, and `bibVariable` are spell checked but shouldn't.
> > 
> > 
> > I don't think these are defined in Vimtex? Perhaps a project for a later time?
> 
> Oh, sorry, I thought they were! Somehow I assumed that a "tex syntax plugin" also included "bib syntax plugin", but that's of course an unwarranted assumption :)
> 
> Yes, if you're _really_ bored and miss working on the tex syntax, that could be a new project ;)

Feel free to open an issue on this. I won't address it right now, but if (when?) I get time, I think this is relevant as a further improvement of Vimtex.

**Comment by clason** [comment]
> I've fixed an error with the texEnvOpt group; how does this look now?

Yep, looks good, thanks!

> Strange. In that case, it would help if (again) you could give an example. :)

Here's a minimal example: `set spell`  marks `unitsize` and `d`. I'd have expected for the `asy` environment not to be spell checked at all?

```tex
\usepackage{asymptote}

\begin{document}
\begin{asy}
    unitsize (1,1);
    real d = 1;
\end{asy}
\end{document}
```

> Feel free to open an issue on this. I won't address it right now, but if (when?) I get time, I think this is relevant as a further improvement of Vimtex.

Maybe at some point, if I can come up with an actual improvement to make. Bibtex syntax is so simple, I don't see much room for it at the moment; the basic syntax script works well.

**Comment by lervag** [comment]
> > I've fixed an error with the texEnvOpt group; how does this look now?
> 
> Yep, looks good, thanks!

Great, happy to hear it!

> > Strange. In that case, it would help if (again) you could give an example. :)
> 
> Here's a minimal example: `set spell` marks `unitsize` and `d`. I'd have expected for the `asy` environment not to be spell checked at all?

This examples works well for me. Can you open a new issue and explain in more depth what I need to reproduce it?

Here's a screenshot to show what I mean:

![2020-12-02_18:25_screenshot](https://user-images.githubusercontent.com/998898/100908346-b3886d00-34cb-11eb-9fdd-a774822792f8.png)

**Comment by clason** [comment]
OK, must be my config then. I'll see if I can narrow it down, but since I don't use spell checking in vimtex myself, I'm probably not going to spend a lot of time on it -- if you say that this is already working, that's good enough for me!
