### ISSUE TITLE
Compiler did not start successfully after swich from MiKTex 2.9 to MiKTex 20.11

### ISSUE THREAD

**Issue by chasorleo** [lervag/vimtex#1872]
Thanks for creating such a good plugin, I've been using it for drafting paper and my thesis with real time update, the experience was superb! However, issue occured last week. The plugin was somehow stop working, though it mange to compile my tex file with latexmk in command line.

**Issue**
`Compiler did not start successfully` after swiching from MiKTex 2.9 to MiKTex 20.11.
The issue occured with the listed `vimrc` and `minimal.tex`
1. Error occur after opening the `*.tex` file without any vimtex command.
2. Error `Compiler did not start successfully`, after `\ll` or `:VimtexCompile` with the above `:VimtexCompileOutput`

* Output of `:VimtexCompileOutput`:

```
z:\Downloads\vimtexIssue>perl -S latexmk.pl -verbose -file-line-error -synctex 1 -interaction nonstopmode -pdf -pvc -e 
Latexmk: -synctex bad option
Latexmk: -interaction bad option

Latexmk: No code to execute specified after -e switch
Use
   latexmk -help
to get usage information
```

**vimrc**
```vim
set nocompatible
filetype plugin indent on
syntax enable

call plug#begin('$VIM\plugins\')
Plug 'https://github.com/lervag/vimtex.git'
call plug#end()
```

**minimal.tex**
```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

**Commands/Input**
`:VimtexCompile`

**Observed Behaviour**
Compiler was not working and not pdf file was generated

**Expected Behaviour**
tex file should compile successfully with `*.pdf` file generated in the pwd

**Output from VimtexInfo**
```
System info
  OS: Microsoft Windows 10 Pro for Workstations (10.0.19041 N/A Build 19041)
  Vim version: VIM 8.2 (1-1911)
  Has clientserver: true
  Servername: GVIM

vimtex project: mini
  base: mini.tex
  root: z:\Downloads\vimtexIssue
  tex: z:\Downloads\vimtexIssue\mini.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: process 10420 dead
    pid: 10420
    cmd: set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e "$pdf_previewer = 'SumatraPDF -reuse-instance'" -e "$success_cmd = 'echo vimtex_compiler_callback_success'" -e "$failure_cmd = 'echo vimtex_compiler_callback_failure'" "mini.tex"
  viewer: General
  qf: LaTeX logfile
    addqflist: 56
    fix_paths: 57
    set_errorformat: 55
  document class: article
```

Thank you.

**Comment by lervag** [comment]
> Thanks for creating such a good plugin, I've been using it for drafting paper and my thesis with real time update, the experience was superb!

Glad to hear it :D

> However, issue occured last week. The plugin was somehow stop working, though it mange to compile my tex file with latexmk in command line.
> 
> **Issue**
> `Compiler did not start successfully` after swiching from MiKTex 2.9 to MiKTex 20.11.

This is strange. Can you try to switch back to MiKTeX 2.9; does it work?

My feeling is that the problem may be related to the environment or something; i.e. how `latexmk` is being run.

Note, in your `vimrc`, you can simplify. First, if you use `vim-plug`, you don't need the first three lines. Next, you can simplify the `Plug` lines. A reduced, equivalent `vimrc`:

```viml
call plug#begin('$VIM\plugins\')
Plug 'lervag/vimtex'
call plug#end()
```

Further, note that this is not really minimal, because it relies on `vim-plug`. A truly minimal `vimrc` looks like this:

```vim
set nocompatible
let &rtp = '/path/to/vimtex,' . &rtp
let &rtp .= ',/path/to/vimtex/after'
filetype plugin indent on
syntax enable
```

**Comment by chasorleo** [comment]
Hi, Thanks for the reply.
I retested based on your vimrc, with MiKTex 2.9 and the problem is still there.
Specificly.
1 **NO ERROR** after open tex file.
2 The same error of compiler did not start successfully happend.
Output of VimtexCompileOutput:

> z:\Downloads\vimtexIssue>perl -S latexmk.pl -verbose -file-line-error -synctex 1 -interaction nonstopmode -pdf -pvc -e 
> Latexmk: -synctex bad option
> Latexmk: -interaction bad option
> 
> Latexmk: No code to execute specified after -e switch
> Use
>    latexmk -help
> to get usage information
> 

Not quite sure how to test your comment of 
"how latexmk is being run."
But I can get the file compiled with latexmk in CMD.

**Comment by lervag** [comment]
> Hi, Thanks for the reply.
> I retested based on your vimrc, with MiKTex 2.9 and the problem is still there.

Ok, so, the problem is not related to the MiKTeX version. This was actually as
expected.

Note: I do not think this is really a vimtex issue, but instead an issue with your installation of MiKTeX/LaTeX. I don't use Windows and don't know so much about it, so it is difficult to help. But my initial guess is that it has to do with the selected perl flavor. Perhaps #378 may give some useful hints? See also the troubleshoot section of the docs (`:help vimtex-troubleshooting`, search for "perl").

I don't know if it can help, but you might want to read `:help vimtex-faq-windows`.

> Not quite sure how to test your comment of
> "how latexmk is being run."
> But I can get the file compiled with latexmk in CMD.

This is basically what I wanted to know, thanks.

**Comment by chasorleo** [comment]
@lervag Thanks for you reply. You are right, the issue is NOT about vimtex but about the Latex&Latexmk  loop instead.
I manage to get my pre-upgrade smooth work flow back by:
1. Uninstall my old activeperl installation and switch to Strawberry Perl 38.
2. Uninstall my old MiKTex platform and install Texlive.
3. Delete my own instalation of latexmk, and using the Texlive latexmk default (without any setup).

After these three steps the problem is gone.
I hope this could help anyone who encountered this issue after upgarding from the MiKTex 2.x to MikTex 20.11.

Frankly speaking, I am not sure which of the 3 steps are critical, but my tex file can be compile on the fly soomthly now.
Thank you very much for your time and patience during the process and I wish you all the best.

**Comment by lervag** [comment]
I'm glad to hear you figured it out! Thanks for writing how you solved this, it may be useful to others!
