### ISSUE TITLE
Highlight group texNewcmdArgName

### ISSUE THREAD

**Issue by j1-lee** [lervag/vimtex#1873]
**Is your feature request related to a problem? Please describe it.**
Suppose one wants to highlight the LHS (a macro to be defined, e.g., `\norm`) in `\newcommand` command, as follows:
```tex
\newcommand{\norm}[1]{\lVert #1 \rVert}
```
One might try, for example,
```vim
highlight link texNewcmdArgName Yellow
```
and sees no difference. It seems that `\norm` is matched to texCmd. As the LHS almost always is in this form, it means that texNewcmdArgName is almost never accessible; one cannot highlight the LHS separately from a regular texCmd.

In contrast, for `\def`, one can separately highlight LHS in by
```vim
highlight link texDefArgName Yellow
```

**Describe the solution you'd like**
One solution might be adding `'contains': ''` pair in the definition of texNewcmdArgName to force vim _not_ to match texCmd (well, anything) in the highlight region:

autoload/vimtex/syntax/core.vim
```vim
call vimtex#syntax#core#new_arg('texNewcmdArgName', {'next': 'texNewcmdOpt,texNewcmdArgBody', 'contains': ''})
```

If you consider this a relevant feature request and find this solution acceptable, then I can modify the code and issue a PR.

**Additional feature**
It might be good to have similar syntax feature for similar commands such as `\let` and `\DeclareMathOperator`; the former is a TeX-native command, and the latter is an amsmath command (so that it is natural to be defined in .../p/amsmath.vim?). I understand we need to draw the line somewhere, but I believe these two are the most frequently used commands that have similar purposes as `\def` and `\newcommand`.

If you find this additional feature plausible, I'll try working on this.

**Comment by lervag** [comment]
> If you consider this a relevant feature request and find this solution acceptable, then I can modify the code and issue a PR.

Yes, absolutely. I agree with your description. Note, if you issue a PR, then
please also add a default link for `texNewcmdArgName` to `texCmd`.

> **Additional feature**
> It might be good to have similar syntax feature for similar commands such as `\let` and `\DeclareMathOperator`; the former is a TeX-native command, and the latter is an amsmath command (so that it is natural to be defined in .../p/amsmath.vim?). I understand we need to draw the line somewhere, but I believe these two are the most frequently used commands that have similar purposes as `\def` and `\newcommand`.
> 
> If you find this additional feature plausible, I'll try working on this.

Yes, I don't mind adding this at all. Especially the `\let`, which I fully agree is an important native command. The `\DeclareMathOperator` should be defined in the `/p/amsmath.vim` file, as you ask.
