### ISSUE TITLE
"g:vimtex_quickfix_ignore_filters" not Filtering Some Errors

### ISSUE THREAD

**Issue by Uver999** [lervag/vimtex#1875]
**Issue**
I am trying to rid the "Quickfix" error log of a few false positive errors and but have only been able to get rid of 2 of the 4 I'm trying to hide. The first two in my .vimrc (my OS is MacOS Catalina) are not working while second pair are.

I'm pretty sure there isn't anything strange going on with the forward slashes in the regex because obviously `\headheight` worked in the last entry. The only thing I can think of is that there are two spaces between the `\underbar` & "has" and `\underline` & "has" in the ones that aren't working.

I have tried many different ways of getting around that such as
```
 \ 'Command \underbar  has changed.',
```
(Without the generic LaTeX warning text.)
```
 \ 'underbar  has changed.',
```
(Without the backslash.)
```
 \ 'underbar has changed.',
```
(Without the extra space.)
```
 \ 'underbar  has changed',
```
(Without the period.) and as many combinations of these as I could think of to no avail. (I believe these errors are caused by the `sectsty` package but I don't think that's important to this issue because I just want to hide the "errors" regardless of why they're there.) This could certainly be user error as I have only really started using Vim a few months ago, LaTeX a couple weeks ago, and this plugin days ago.

**minimal.vim**
```vim
" LaTeX settings
let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'skim'
let g:vimtex_quickfix_ignore_filters = [
    \ 'LaTeX Warning: Command \underbar  has changed.',
    \ 'LaTeX Warning: Command \underline  has changed.',
    \ 'Over-specification in `v',
    \ '\headheight is too small'
\]
```

**minimal.tex**
```tex
\documentclass[letterpaper, 12pt]{book}

\usepackage{sectsty}

% I'm not sure how much of a .tex file to show here but this I'm including this function because it uses sectsty.

% Header(s)
\fancypagestyle{firstpage}
{
\pagestyle{fancy}
\renewcommand{\headrulewidth}{0pt}
\fancyhead[R]{%
  \begin{tabular}[t]{@{}r@{}}
  Name\\Subject\\Week Due
  \end{tabular}}
}

\begin{document}
\thispagestyle{firstpage}

Hello world!
\end{document}

```

I don't have anything in a `.latexmkrc` file.

**Commands/Input**
* Open the `.tex` file.
* Press `\ll` to start compiling the PDF. 
* See the errors in the Quickfix console.

**Observed Behaviour**
These two `sectsty` "errors" show in the Quickfix console when I'm trying to disregard them from my `.vimrc` using `g:vimtex_quickfix_ignore_filters`.

**Expected Behaviour**
These "errors" should be ignored and not pop open the Quickfix console. 

**Output from VimtexInfo**
```
System info
  OS: Mac OS X 10.15.6 (19G2021)
  Vim version: VIM 8.2 (1-2000)
  Has clientserver: false

vimtex project: Minimal Tex Example
  base: Minimal Tex Example.tex
  root: /Users/username/Minimal Tex
  tex: /Users/username/Minimal Tex/Minimal Tex Example.tex
  out: /Users/username/Minimal Tex/Minimal Tex Example.pdf
  log: /Users/username/Minimal Tex/Minimal Tex Example.log
  aux: /Users/username/Minimal Tex/Minimal Tex Example.aux
  fls: /Users/username/Minimal Tex/Minimal Tex Example.fls
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Skim
  qf: LaTeX logfile
    root: /Users/username/Minimal Tex
    addqflist: 56
    errorformat_saved: 
    fix_paths: 57
    main: /Users/username/Minimal Tex/Minimal Tex Example.tex
    set_errorformat: 55
  document class: book
  packages:
    dirtytalk
    fancyhdr
    geometry
    iftex
    ifthen
    ifvtex
    keyval
    kvoptions
    kvsetkeys
    ltxcmds
    mathptmx
    nth
    sectsty
    setspace
```

**Comment by lervag** [comment]
> I'm pretty sure there isn't anything strange going on with the forward slashes in the regex because obviously `\headheight` worked in the last entry. The only thing I can think of is that there are two spaces between the `\underbar` & "has" and `\underline` & "has" in the ones that aren't working.

Well, I'm pretty sure that the forward slashes are causing your problems here. The filters are used as regular expressions, where `\u` has a special meaning, see `:help \u`. So, to match literal "\underbar" you need `\\underbar`. See also `:help \h` if you want to understand why the last filter still works.

I believe the following should work:

```viml
let g:vimtex_quickfix_ignore_filters = [
      \ 'LaTeX Warning: Command \\under\(bar\|line\)  has changed.',
      \ 'Over-specification in `v',
      \ '\\headheight is too small'
      \]
```

Btw., note that you no longer need to specify `g:tex_flavor` in your vimrc file (it doesn't hurt, of course).

**Comment by Uver999** [comment]
Thank you so much! I read through most of the documentation but didn't put two and two together with those special character meanings. Works perfectly now!

**Comment by lervag** [comment]
Happy to hear it :)
