### ISSUE TITLE
Correct syntax not recognized as such

### ISSUE THREAD

**Issue by rionda** [lervag/vimtex#1877]
The LaTeX `foo \emph{bar $\frac{4}{5}$ baz} baw` is valid, but the new (?) syntax does not seem to like it, giving very weird colors.

Update: even `foo \emph{bar $\sqrt{4}$ baz} baw` appears wrong.

**Comment by lervag** [comment]
Can you explain _what_ is wrong? For me, it seems correct. I'm now looking at a document with the following content:

```tex
``foo \emph{bar $\sqrt{4}$ baz} baw''
  foo \emph{bar $\frac{4}{5}$ baz} baw
```

**Comment by lervag** [comment]
![2020-12-02_18:22_screenshot](https://user-images.githubusercontent.com/998898/100908079-5c829800-34cb-11eb-895b-72cff469719b.png)

**Comment by rionda** [comment]
![image](https://user-images.githubusercontent.com/1178354/100908301-440e7f80-34c3-11eb-8c7e-4dc985f2d699.png)

**Comment by lervag** [comment]
Can you try this with a minimal example? And provide the configuration that you use?

**Comment by rionda** [comment]
yeah, sorry. I hoped it was an easy fix and I wouldn't need to do that. Coming up soon.

**Comment by rionda** [comment]
The following screenshot is obtained by running vim with `vim -u minimal.vim test.tex`, with `minimal.vim` being

```
set nocompatible
let &runtimepath  = '~/.vim/pack/matteo/start/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/pack/matteo/start/vimtex/after'
filetype plugin indent on
syntax enable
```
 and `test.tex` being exactly what you see in the screenshot.

![image](https://user-images.githubusercontent.com/1178354/100909080-2db4f380-34c4-11eb-9dc7-ada4ec70b549.png)

**Comment by rionda** [comment]
Despite the minimal runtime, other plugins were loaded. I removed all other plugins except vimtex, and the issue is gone, so it is probably caused by another plugin (which also seems to have other side effects, e.g., text inside `\emph{ }` not appearing in italic in vim). I think the issue can be closed, but I want to check first.

**Comment by rionda** [comment]
Ok, so it seems the conflict is with [tex-conceal](https://github.com/KeitaNakamura/tex-conceal.vim.git), which I believe used to be suggested in the docs, but I don't see it anymore, probably because now vimtex has its own concealing code?

**Comment by lervag** [comment]
Ah, yes; Vimtex no longer really works with `tex-conceal`, because `tex-conceal` builds on top of the internal syntax plugin.

Let me know if you think there are some major things from `tex-conceal` you miss.
