### ISSUE TITLE
\symbols not concealed if appended by `_`

### ISSUE THREAD

**Issue by BertrandSim** [lervag/vimtex#1878]
Hi, I noticed that a symbols are not concealed if an underscore follows immediately after the symbol.
For example, I observed `\sigma_2` --> `\sigma₂`, while I would expect it to behave as `\sigma_2` --> `σ₂`.

**minimal.vim**
```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
set conceallevel=2
```

**minimal.tex**
```tex
\documentclass{minimal}
\begin{document}
$\sigma$ %ok
$\sigma^2$ %ok
$\sigma_2$ %not ok
\end{document}
```

**Comment by BertrandSim** [comment]
I've investigated the issue further. It turns out that this behavior is due to `'iskeyword'`, which includes `_` by default. 
A possible fix would be to set the value of `'iskeyword'` (or better, `:syn iskeyword`)

**Comment by lervag** [comment]
Yes, my immediate thought is that this is because of the `\>` that is used in the regexes. I think your suggestion seems like a good solution for solving it.

**Comment by lervag** [comment]
Thanks for investigating and proposing something that looks like a good solution. It saves me time, and I appreciate it!

**Comment by BertrandSim** [comment]
You're welcome, glad I could help in a small way :)
