### ISSUE TITLE
The tex-conceal.vim problem

### ISSUE THREAD

**Issue by oblitum** [lervag/vimtex#1881]
**Is your feature request related to a problem? Please describe it.**

[tex-conceal.vim](https://github.com/KeitaNakamura/tex-conceal.vim) is a nice plugin that offers a good set of concealed elements which makes for much improved LaTeX preview. It seems [it used to work fine together with vimtex](https://github.com/lervag/vimtex/issues/557#issuecomment-391106228), but today [vimtex blocks most of it from working](https://github.com/lervag/vimtex/issues/557#issuecomment-738555582).

**Describe the solution you'd like**

I wished they were compatible or that vimtex merged such feature.

**Describe alternatives you've considered**

I didn't yet analyze it well, but I'm checking whether disabling parts of vimtex through its flags may allow the two work together, even though missing some vimtex feature, which actually I didn't want to, but such concealing is such a killer feature for me...

**Comment by AnglyPascal** [comment]
I have modified the code.vim file to add the conceal support from that plugin, i can upload it if you'd like. I am new to git so i am not very confident about making commits or pull requests

**Comment by oblitum** [comment]
@AnglyPascal you can share it in a [gist](https://gist.github.com/) for the moment. A diff/patch, or the whole file as-is.

**Comment by AnglyPascal** [comment]
https://gist.github.com/AnglyPascal/fe8a92f37c2abd1a08ebdc9eb4b4bdd3 Here you go

**Comment by lervag** [comment]
I've added most of the conceals from @AnglyPascal now. Thanks for sharing!

**Comment by oblitum** [comment]
I'm sorry @lervag, but was added didn't help much for me, see [tex-conceal.vim test](https://github.com/KeitaNakamura/tex-conceal.vim/tree/master/test).

This is what I get with vimtex only:

![img-2020-12-04-163605](https://user-images.githubusercontent.com/1269815/101207239-1a825f00-364f-11eb-85e4-0a34c93565ca.png)

This is what I get with tex-conceal only (sole conf is `let g:tex_conceal = 'abdmg'):

![img-2020-12-04-163316](https://user-images.githubusercontent.com/1269815/101207276-279f4e00-364f-11eb-9089-f1b2188f05e6.png)

**Comment by oblitum** [comment]
I didn't enable `let g:tex_conceal_frac=1`, by doing so:

![img-2020-12-04-164313](https://user-images.githubusercontent.com/1269815/101207763-da6fac00-364f-11eb-87c6-02ac15c949bd.png)

**Comment by lervag** [comment]
Ok. This is a feature I really don't care that much about (sorry), but I don't mind adding things. However, it would be a great help to get a list of what is missing. E.g. something like this:

1. `\bm{x}` -> `x`
2. `\mathrm{x}` -> `x`

and so on. This would make it much easier for me to work on it when I get time. Also, anyone who finds this important should feel free to submit a PR.

**Comment by oblitum** [comment]
I rather preferred that vimtex wasn't taking the route LaTeX-Suite, to do one thing and do it well and be easy to mix and match with other plugins without a lot of overlapping that I see happening. I have this criticism, please don't take offense, as I think a project should be open either to praising as well as valid criticism. I think it's time for me to stop using vimtex because:

* I already have coc-texlab that does a great job at linting through LSP, it has synctex support for document synchronization with live preview.
* I already have coc-diagnostic configured with textidote for grammar checking both latex and markdown. I just learned another day that vimtex also had an option for this.
* I already have tex-conceal that does better conceal than vimtex, and tex-conceal has recent activity in the area, and there's outstanding PR to add more conceal. The fact that it's a separate plugin focused on that feature alone makes it developed that feature faster, making it easier for interested people to find that feature and contribute to it.

**Comment by lervag** [comment]
> I rather preferred that vimtex wasn't taking the route of LaTeX-Suite, reverse of to do one thing and do it well and be easy to mix and match with other plugins without a lot of overlapping that I see happening.

IMHO, Vimtex is _not_ taking the route of LaTeX-Suite. I understand the comment, though, seeing that Vimtex is expanding its features. When I say I disagree, my point is that Vimtex is expanding while ensuring that the inherent "simplicity" is not broken. What I mean by that, is that the code base is still maintainable and modular. There is not (much) bloated code that adds features no one wants and that adds inefficiencys. It is possible to disable features you don't want. And Vimtex attempts to behave "as expected" as a general rule.

> I have this criticism, please don't take offense, as I think a project should be open either to praising as well as valid criticism.

No offense taken. And I mean no offense when I say that I could not care less about your preferences in this matter. I don't mind there being good alternatives to Vimtex and that there is a community that is working on alternative solutions.

> I think it's time for me to stop using vimtex because:
> 
>     * I already have coc-texlab that does a great job at linting/completion through LSP, it has SyncTeX support for document synchronization with live preview.

I'm glad to hear that `coc-texlab` is working well for you.

>     * I already have coc-diagnostic configured with textidote for grammar checking both latex and markdown. I just learned another day that vimtex also had an option for this.

Yes, there are compiler backends for textidote in Vimtex. But I can see that the coupling with coc can be nice here.

>     * I already have tex-conceal that does better conceal than vimtex, and tex-conceal has recent activity in the area, and there's outstanding PR to add more conceal. The fact that it's a separate plugin focused on that feature alone makes it evolve that feature faster, making it easier for interested people to find that feature and contribute to it.

IMHO, the internal syntax plugin for TeX was not so good. The syntax groups were not consistent, there was unnecessary features and unnecessary complications. I find the version that ships with Vimtex v2 to be a significant improvement which makes it _much_ easier to further improve syntax support for e.g. custom packages and similar. It will also be quite easy to improve the conceal support, either within Vimtex or by adapting e.g. `tex-conceal` into something like `vimtex-conceal`.

**Comment by AnglyPascal** [comment]
I think a possible approach could be adding a separate syntax file storing all the conceal related stuff that will be turned off by default but if someone wants to add that they can toggle it with a command.

**Comment by Konfekt** [comment]
> However, with version 2, Vimtex bundles its own, new syntax plugin. It has different syntax group names.

Could `texMathRegionX` (and its likes) be renamed to `texMathZoneX` (and similar,say `texMathRegionEnvStarred` to `texMathZoneES`) to restore some compatibility?

**Comment by Konfekt** [comment]
An ulterior motive being the preservation of a plug-in independent check for a Math syntax group in TeX files, see https://github.com/lervag/vimtex/issues/1880#issuecomment-738737996 )

**Comment by lervag** [comment]
> > However, with version 2, Vimtex bundles its own, new syntax plugin. It has different syntax group names.
> 
> Could `texMathRegionX` (and its likes) be renamed to `texMathZoneX` (and similar,say `texMathRegionEnvStarred` to `texMathZoneES`) to restore some compatibility?

I'd rather not. I decided to not remain compatible with the internal plugin. If I changed this, then people might ask: "could Vimtex change e.g. `texCmd` back to `texStatement` to restore some compatibility?".

I do understand that this is all opinionated, but I personally think the changes are for the better. And of course, if people are generally happy with Vimtex v1.6, then it is of course an option to stay with that version.

**Comment by lervag** [comment]
Btw., another option that people might find better is to simply disable the syntax support in Vimtex with `g:vimtex_syntax_enabled`.

**Comment by lervag** [comment]
So, to summarize this last discussion, users of Vimtex now has three options:

1. Use Vimtex 2.0 "all the way", get all the features and live with somewhat reduced conceal support (until it possibly is added in future improvements).

2. Use Vimtex 2.0 without the syntax (`let g:vimtex_syntax_enabled = 0`). Stay up-to-date with bugfixes and non-syntax improvements, but use Dr. Chips syntax plugin and the conceal support with `tex-conceal`. Note that this also means the Vimtex package specific improvements will also go away, but Dr. Chip do have some additional packages available as optional downlods.

3. Remain with Vimtex 1.6. You get the old style syntax and conceal, but no more new features and bug fixes.

I do understand that some people don't agree with these changes. Vimtex is released under the MIT license, and one may of course simply fork the project and use a customized version.

**Comment by clason** [comment]
> > However, with version 2, Vimtex bundles its own, new syntax plugin. It has different syntax group names.
> 
> Could `texMathRegionX` (and its likes) be renamed to `texMathZoneX` (and similar,say `texMathRegionEnvStarred` to `texMathZoneES`) to restore some compatibility?

Also, you can always just `hi link texMathZoneX texMathRegionX` etc. in your own config to restore compatibility.

**Comment by Konfekt** [comment]
Oh, thank you, @clason, that's good to know. Do you perhaps know which syntax groups should be linked for maximal compatibility?

**Comment by Konfekt** [comment]
Then this linkage could be made a toggle option; perhaps enabled by default.

**Comment by clason** [comment]
No, because I don't use `tex-conceal` (or any conceal, really) and switched to vimtex 2.0 for its vastly improved syntax groups for my highlighting. I could help with the new groups, though.

Maybe you could open a new issue about a "compatibility table" (that could go into the Wiki) with your precise needs?

> Then this linkage could be made a toggle option; perhaps enabled by default.

I think that would go against the spirit of the whole refactor; it would make sense to maintain this as an independent compatibility shim plugin, if this is really required.

**Comment by Konfekt** [comment]
This incompatibility has as one of its effects the incompatibility of concealing; but there are other functions that depend on the existence of TeX syntax groups. 

To supplement:

```vim
hi link texMathRegion texMathZoneW
hi link texMathRegionX texMathZoneX
hi link texMathRegionXX texMathZoneY
hi link texMathRegionEnv texMathZoneG
hi link texMathRegionEnvStarred texMathZoneGS
```

Yet missing is the regions `Ensured`.

**Comment by clason** [comment]
> But there are other functions that depend on the existence of TeX syntax groups.

Can you be more specific? (Honestly asking here.)

**Comment by lervag** [comment]
```vim
hi link texMathZoneZ texMathRegionEnsured
```

I am fully aware that the incompatibility breaks certain dependencies, which is exactly why I released this as a major update.

I do think, though, that a section in the Wiki about how to link (some of) the new groups to the old ones to patch (possibly only some of) the incompatibilities may be a good strategy. Perhaps this should be continued in a new thread?

**Comment by Konfekt** [comment]
> Can you be more specific? (Honestly asking here.)

That claim was a bit bold, but at least I thought of https://github.com/lervag/vimtex/issues/1880 . This is useful, say, for the [vim-pandoc plug-in](https://github.com/vim-pandoc/vim-pandoc) that uses the TeX highlight groups for math. Then abbreviations and imaps can be triggered only inside a math zone.

**Comment by lervag** [comment]
This discussion is now moved to #1883.
