### ISSUE TITLE
restore some compatibility to Vim's built-in syntax groups

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#1882]
As discussed at https://github.com/lervag/vimtex/issues/1881 linking the new to the old syntax groups, say by

```vim
hi link texMathZoneW texMathRegion
hi link texMathZoneX texMathRegionX
hi link texMathZoneY texMathRegionXX
hi link texMathZoneG texMathRegionEnv
hi link texMathZoneGS texMathRegionEnvStarred
hi link texMathZoneZ texMathRegionEnsured
```

restores some compatibility to Vim's built-in syntax groups, useful to restore existent functionality, for example, of additional concealing [tex-conceal](https://github.com/KeitaNakamura/tex-conceal.vim/) and syntax group detection https://github.com/lervag/vimtex/issues/1880

**Comment by lervag** [comment]
Do you agree that this is the same as #1883, and would you mind if we keep the discussion in a single thread?

**Comment by clason** [comment]
sorry, your issue came first, but mine has more text ;)

**Comment by Konfekt** [comment]
Yes, it is indeed the same.
