### ISSUE TITLE
`Selected viewer is not executable!` on Win10 with 'start' option

### ISSUE THREAD

**Issue by fbanning** [lervag/vimtex#1886]
On startup of a simple test.tex file:

```tex
\documentclass{minimal}
\begin{document}

Hallo hallo

\end{document}
```

I get the following message:

```
vimtex: Selected viewer is not executable!
        - Selection: start
        - Executable: start
        - Please see :h g:vimtex_view_general_viewer
```

Compilation via `\ll` works just fine and opens the generated pdf via the `start` system handler (i.e. Adobe Reader).

This is the output of `:VimtexInfo` :

```
System info
  OS: Microsoft Windows 10 Pro (10.0.18363 Nicht zutreffend Build 18363)
  Vim version: VIM 8.2 ()
  Has clientserver: true
  Servername: VIM

vimtex project: test
  base: test.tex
  root: C:\Users\Frederik Banning
  tex: C:\Users\Frederik Banning\test.tex
  out: C:\Users\Frederik Banning/test.pdf
  log: C:\Users\Frederik Banning/test.log
  aux: C:\Users\Frederik Banning/test.aux
  fls: C:\Users\Frederik Banning/test.fls
  main parser: current file verified
  compiler: latexmk
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  qf: LaTeX logfile
    addqflist: 316
    fix_paths: 317
    set_errorformat: 315
  document class: minimal
```

I'm wondering why things work just fine when compiling from vim and then viewing the pdf but vimtex still seems to complain about something at startup? Thanks in advance for any ideas what to try out. :)

**Comment by lervag** [comment]
Can you share your related configuration?

**Comment by fbanning** [comment]
Sure, what exactly would you like to know? Just trying to set vimtex up. I get the same message no matter if I don't configure any vimtex variables in `_vimrc` or if I try to explicitly force it to use `let g:vimtex_view_general_viewer = 'start'`.

**Comment by lervag** [comment]
It's always useful to know what config you are using. For instance, are you changing the `shell` option?

See [this wiki post](https://vim.fandom.com/wiki/Execute_external_programs_asynchronously_under_Windows) for some relevant information.

Note, I strongly suggest that you use `SumatraPDF` as a viewer on Windows. Adobe doesn't work, because it locks the PDF file. At least it did in the past, perhaps this has changed now?

**Comment by fbanning** [comment]
>  Adobe doesn't work, because it locks the PDF file.

Just tested this by adding some words to the `test.tex` file and trying to `:w`. Throws the following:

```
test.tex|8 error| I can't write on file `test.pdf'.
test.tex|8 error| Emergency stop. ...shipout:D \box_use:N \l_shipout_box
test.tex|8 error| ==> Fatal error occurred, no output PDF file produced!
```

Therefore you are right and Adobe still locks the PDF. This is really unfortunate because I hate to have two pieces of software installed that do 99% the same.

I will try out another PDF viewer and see if the message still occurs on startup.

**Comment by fbanning** [comment]
With `Okular` the continuous updating of the PDF file works just fine. So I'll just use it for `vimtex`, no problem.

However, the startup message is still there if I just let the system choose the PDF viewer via `start` (i.e. without specifying the PDF viewer in my `_vimrc` file and using the system default instead). Is this approach not recommended for vimtex? Should I always specify explicitly which PDF viewer should be used instead of using system defaults?

> For instance, are you changing the `shell` option?

No.

**Comment by lervag** [comment]
> > Adobe doesn't work, because it locks the PDF file.
> 
> Just tested this ...

Thanks, that verifies my suspicion.

> This is really unfortunate because I hate to have two pieces of software installed that do 99% the same.

I can partly relate to that, but I would claim that in this regard, viewers like SumatraPDF is (IMHO) much better than Adobe Reader for viewing pdf files on Windows. SumatraPDF is much faster and simpler, and it works very well with Vim and Vimtex.

> With `Okular` the continuous updating of the PDF file works just fine. So I'll just use it for `vimtex`, no problem.

I've not tried Okular on Windows. If it works, then that's great, but you might also be interested in testing SumatraPDF as I've previously suggested.

> However, the startup message is still there if I just let the system choose the PDF viewer via `start` (i.e. without specifying the PDF viewer in my `_vimrc` file and using the system default instead).

Thanks, it's useful to know this. I would have expected this to work as expected, and I'm sorry to see it is not. However, as I just wrote in a different thread: I don't work with Windows machines, and so it is very difficult to help solve issues related to it. This doesn't mean I don't want it to work on Windows, just that it is difficult for me to fix and improve things. I would very much appreciate help understanding why this doesn't work.

> Is this approach not recommended for vimtex?

The approach _should_ work, but I would claim it should not be recommended. Of course, I aim for things to "just work", but to work well, people should read the docs and configure things to their liking. Not all pdf viewers support forward and/or backward searching, for instance; and the default ones rarely do. Besides, this has to be properly configured to work.

----

So, back to the issue at hand: If you start Vim, what is the output when you do `:!start calc`? Does it open a calculator?

**Comment by fbanning** [comment]
Thanks for taking your time, it's much appreciated. I use Linux on my personal PC as well but for work I am stuck with Win10 at the moment.

> what is the output when you do `:!start calc`? Does it open a calculator?

Yes, perfectly fine. It also works if I do `:!start test.pdf`.

I'm here to help with the bug hunting. :)

**Comment by fbanning** [comment]
Just a sidenote: I've fixed the error on startup by putting Okular on my `PATH` and `let g:vimtex_view_general_viewer = 'okular' in my `_vimrc`. This is not really helping with the more general issue described above but it certainly is a feasible workaround.

**Comment by lervag** [comment]
> Thanks for taking your time, it's much appreciated. I use Linux on my personal PC as well but for work I am stuck with Win10 at the moment.

No problem, happy to help :)

> > what is the output when you do `:!start calc`? Does it open a calculator?
> 
> Yes, perfectly fine. It also works if I do `:!start test.pdf`.
> 
> I'm here to help with the bug hunting. :)

Great, then at least we know it is not the `!start` itself that is the problem. Now, what happens if you do `:echo executable('start')`? It seems this is where the current behaviour fails, and it might be that `start` is special and not recognized as an executable?

> Just a sidenote: I've fixed the error on startup by putting Okular on my `PATH` and `let g:vimtex_view_general_viewer = 'okular' in my `_vimrc`. This is not really helping with the more general issue described above but it certainly is a feasible workaround.

Yes, I wouldn't call this "fixed the error". It's more like specifying a viewer explicitly, which I think most users should do anyway :)

**Comment by fbanning** [comment]
> Yes, I wouldn't call this "fixed the error".

Me neither, it was just because I was lacking a better word. Let's say "I avoided the error on startup". ;-)

> what happens if you do `:echo executable('start')`?

Returns 0

**Comment by lervag** [comment]
Are you comfortable with changing the code yourself to test? If so, could you comment out the following code and see if it makes things work for you?

https://github.com/lervag/vimtex/blob/eb4c21f969f39f4c68cff6a42a45024427e633ac/autoload/vimtex/view/general.vim#L11-L18

**Comment by fbanning** [comment]
Yep, that removed the error message on startup as expected when commenting out the check for an executable viewer in the first place. :D

**Comment by lervag** [comment]
Yes, but does the viewer work? If you do not specify `g:vimtex_view_general_viewer`, does the default `start` now open a pdf with e.g. Adobe Acrobat?

**Comment by fbanning** [comment]
Yes

**Comment by lervag** [comment]
So, if we remove this test, then everything works as expected, yes? So it would solve your issue? If so, then I can add an exception here for Windows and the `start` executable specifically.

**Comment by fbanning** [comment]
Yes, it seems as if that's the case. I can open a `.tex` file, edit it, compile via `\ll`, stop compilation via `\lk` - all without any problems. I think adding an exception for `start` would make sense. I wonder why nobody metioned this before me but it might just be that people either use a specific viewer via their vimrc or that there just aren't many Vimdows users using vimtex in the first place.

**Comment by lervag** [comment]
Great, thanks for reporting and helping with figuring things out! I'll make a patch and submit later when I get the time.

**Comment by fbanning** [comment]
No problem and thanks for making and maintaining this package. :)

**Comment by lervag** [comment]
> No problem and thanks for making and maintaining this package. :)

Happy you like it!
