### ISSUE TITLE
\DeclareTCBListing not recognized as minted environment.

### ISSUE THREAD

**Issue by obreitwi** [lervag/vimtex#1889]
**Issue**
When declaring a custom `tcolorbox`-listing environment to use with `minted`-highlighting via `\DeclareTCBListing`, `vimtex` does not recognize it as a `minted` environment. This causes syntax-highlighting to mess up, for example if the environment contains an odd number of dollar signs (see example below). I do recognize that not all `tcolorbox`-listing environments are actually used as `minted`, only if `minted`-related options are present and `\tcbuselibrary{minted}` is specified.

However, the workaround might be useful for someone else encountering the problem.

**Workaround**
Manually declaring the environment as `minted` solves the issue.
```vim
call vimtex#syntax#core#new_region_env('texMintedZone', 'mintedbox', {'contains': 'texCmdEnv,texMintedEnvBgn'})
```

**minimal.vim**
(`vimtex` loaded via `vim-plugged`. Full config [here](https://github.com/obreitwi/dot_vim), most certainly unneeded.)

**minimal.tex**
```tex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}

\usepackage{tcolorbox}
\tcbuselibrary{minted}
\tcbuselibrary{xparse}
\DeclareTCBListing{mintedbox}{ m !O{} }{%
  listing only,
  minted language=#1, #2}

\begin{document}
This part of the document is in regular syntax highlighting.
\begin{mintedbox}{text}
$ This is a minted box that contains a single dollar sign.
\end{mintedbox}
Now this part of the document has math-mode syntax highlighting.
\end{document}
```
[Output](https://breitwieser.eu/tmpodrom/khRSNmBGaYpbUqDQ/issue.pdf)

Thank you for `vimtex`! :upside_down_face:

**Comment by lervag** [comment]
Is the `\DeclareTCBListing` command from the `minted` package? Or is it from the `tcolorbox` package? It would be nice to see the corresponding references here. It seems to me it is from the `tcolorbox`, in which case I don't think we should add this into the `minted` syntax package directly. Perhaps it would suffice to let the `\DeclareTCBListing` command declare a generic listing environment instead of a minted specific environment?

**Comment by obreitwi** [comment]
> Is the `\DeclareTCBListing` command from the `minted` package? Or is it from the `tcolorbox` package?

Yes, `\DeclareTCBListing` is a command from `tcolorbox` that allows for the [definition of custom](http://texdoc.net/texmf-dist/doc/latex/tcolorbox/tcolorbox.pdf#page=452&zoom=100,94,56) [`tcblisting`](http://texdoc.net/texmf-dist/doc/latex/tcolorbox/tcolorbox.pdf#page=309&zoom=100,94,56)-based environments using [`xparse`](https://mirror.dogado.de/tex-archive/macros/latex/contrib/l3packages/xparse.pdf). Sorry for not clarifying!

`tcblisting` environments on their own only use `minted`-related machinery if the corresponding [options](http://texdoc.net/texmf-dist/doc/latex/tcolorbox/tcolorbox.pdf#page=319&zoom=100,94,56) are specified.

> Perhaps it would suffice to let the `\DeclareTCBListing` command declare a generic listing environment instead of a minted specific environment?

Yes, I think that would suffice. My main concern was the use singular `$` in dummy shell prompts "bleeding" into the surrounding TeXt.

**Comment by lervag** [comment]
I think it should work now, please test.

**Comment by obreitwi** [comment]
Wow, that was quick. Works perfectly, thank you!

**Comment by lervag** [comment]
Great, happy to hear it :)
