### ISSUE TITLE
latexmk gets stopped when I open another tex file

### ISSUE THREAD

**Issue by ff2000** [lervag/vimtex#189]
This makes working with multi-file-documents tedious. I am currently proofreading a book with about 40 included files. Everytime I open an included file latexmk stops and I have to (re)start it. Continious mode works if I stay in one file and :write it.
Closing the buffer containing the included file keeps latexmk alive, changes to the main file recompile the document. Until I open the next included file ;)
I am running vim-7.4.738, latest vimtex-master (updated right now), latexmk-443a
```
alias vimtex
vimtex='vim --servername vimtex'
```

**Comment by lervag** [comment]
I suspect this is because you do not have `set hidden` in your `vimrc`. The `latexmk` process is stopped when a buffer that started it is closed (and if the buffer is the only "relevant" buffer).

**Comment by ff2000** [comment]
Thx, set hidden works. Would be great if this gets mentioned in the docs (I actually searched it first but couldn't find a hint).
I still wonder why it stays alive after :bdelete the buffer containing the included file. Shouldn't latexmk be killed, too?

**Comment by lervag** [comment]
Hmm, yes: I should add this to the docs. Will do it later. I think a Troubleshooting section might be appropriate.

I didn't quite understand your last question. Could you explain what you are doing and what the expected behavour is? If you could create a small example that I could test myself, that would be optimal. The `latexmk` process should stay alive as long as there are buffers open for the current LaTeX-project. You can use `\li` to see information about what is currently stored (for the buffer), and `:VimtexInfo!` to see all the information available for all open projects.

**Comment by ff2000** [comment]
* vim main.tex
  \ll to start latexmk
* go to a line that includes another tex file ("included.tex")
* 'gf' to open the file under the cursor
  -> latexmk is killed (as expected with hidden=off)
* \ll to restart latexmk
* :bd to delete current buffer with included.tex file
  -> latexmk is still running

With your first comment I would have expected that deleting the buffer containing included.tex would also kill latexmk, as it was started for that file. Your last comment might indicate that as long as the main.tex file is open latexmk stays alive - which would explain the behaviour I see.

**Comment by lervag** [comment]
I found a different way of handling the case when a buffer is switched/closed. In my tests, the latest version should now work properly both for `hidden` and `nohidden`. I would be happy if you could test and confirm that things now work as you would expect.

**Comment by ff2000** [comment]
Yay! Thx alot! Working perfectly (as expected) with nohidden.

**Comment by lervag** [comment]
Great, happy to help :)
