### ISSUE TITLE
Little help for implementing auto - adding "\item" in itemize and enumerate

### ISSUE THREAD

**Issue by TornaxO7** [lervag/vimtex#1895]
Well as we already started in this issue: https://github.com/lervag/vimtex/issues/1863#issuecomment-743761892
I'm trying to implement a way to add `\item` automatically if I'm in an `itemize` environment. So currently I have this:
```vim
if vimtex#env#is_inside('itemize')
    imap <CR> i\item
else
    unmap <CR>
endif
```

But I'm getting this error message:
```vim
E745: Using a List as a Number
```
Do you have an idea how I can fix this?

**Comment by j1-lee** [comment]
I am not a vim expert, but how about the following?
```vim
inoremap <expr> <CR> (vimtex#env#is_inside('itemize') != [0, 0] ? "\<CR>\\item " : "\<CR>")
```

In your case, the error message seems to arise because `vimtex#env#is_inside('itemize')` returns a list, not a number (that can be interpreted as true/false).

**Comment by lervag** [comment]
@j1-lee proposes a relevant solution. I would add that such a map should be created either in a `autocmd Filetype tex ...` context or in a personal filetype plugin for tex, e.g. in `~/.vim/after/ftplugin/tex.vim`. The latter is IMHO to be preferred. Further, I would suggest that you use the `imaps` feature (it is enabled by default), in which case you can add the mapping like this:

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : '<cr>',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment',
      \ 'context' : [
      \   'itemize',
      \   'enumerate',
      \ ],
      \})
```

**Comment by TornaxO7** [comment]
@j1-lee somehow your mapping doesn't work:
![GIF](https://user-images.githubusercontent.com/50843046/102282832-84451780-3f31-11eb-9188-0a8f5b9816ad.gif)

@lervag Your imap adds the `\item` macro, but it doesn't add it in the new line:
![GIF](https://user-images.githubusercontent.com/50843046/102283097-ffa6c900-3f31-11eb-9942-ec9d036794c1.gif)

Do you have an idea how I can fix this?

**Comment by j1-lee** [comment]
For the `inoremap` command, I am not sure why that does not work. One reason might be the map is overwritten later somehow, e.g., by another plugin. Try putting that in `nvim/after/ftplugin/tex`, not `nvim/ftplugin/tex`, although I am not sure whether this would work.

Also, when you do so, insert `<buffer>` argument as follows:
```vim
inoremap <buffer> <expr> <CR> (vimtex#env#is_inside('itemize') != [0, 0] ? "\<CR>\\item " : "\<CR>")
```

**Comment by TornaxO7** [comment]
@j1-lee Yeah! It's working now! Adding the `nvim/after/ftplugin/tex` directory helped! that's coooooooool :D Thank you!
How do you know of this directory? Where can I read more about it?

**Comment by j1-lee** [comment]
Glad it worked! I heard of this directory when I was reading some stackexchange thread regarding `setlocal formatoptions-=o`. I don't remember the situation quite well, but the issue was something like putting that in `nvim/ftplugin/` is overridden by some other plugins. The remedy was to put that in `nvim/after/ftplugin/` instead. I am sorry I can't remember where exactly that came from, so I cannot provide a relevant reference...

**Comment by TornaxO7** [comment]
@j1-lee new issue xD I want to have this feature as well if I'm in an `enumerate` environment. Currently I have this in my `nvim/after/ftplugin/tex`:
```vim
inoremap <buffer> <expr> <CR> (vimtex#env#is_inside('itemize') != [0, 0] ? "\<CR>\\item " : "\<CR>")
imap <buffer> <expr> <CR> (vimtex#env#is_inside('enumerate') != [0, 0] ? "\<CR>\\item " : "\<CR>")
```
But now it doesn't add the `\item` automatically in an `itemize` environment. Do you have an idea how I can fix that?

**Comment by j1-lee** [comment]
I guess it is because the second line overrides the first line. In this case, we could think of something like the following:
```vim
function! ImapAutoItem()
  let s:in_itemize = vimtex#env#is_inside('itemize') != [0, 0]
  let s:in_enumerate = vimtex#env#is_inside('enumerate') != [0, 0]
  let s:return_imap = "\<CR>"
  if s:in_itemize || s:in_enumerate
    let s:return_imap .= '\item '
  endif
  return s:return_imap
endfunction

inoremap <expr> <buffer> <CR> ImapAutoItem()
```

But in this case I think the solution by @lervag:
```vim
call vimtex#imaps#add_map({
      \ 'lhs' : '<cr>',
      \ 'rhs' : "\r\\item ",
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment',
      \ 'context' : [
      \   'itemize',
      \   'enumerate',
      \ ],
      \})
```
would be much better.

**Comment by TornaxO7** [comment]
@j1-lee woohoooo! The imap is working!!! Thank you!!!

**Comment by lervag** [comment]
> @lervag Your imap adds the \item macro, but it doesn't add it in the new line: ...

Sorry, I forgot that you also wanted the newline. I see @j1-lee corrected my snippet. Thanks for pitching in, @j1-lee! For the custom function, I would rewrite it as follows:

```vim
function! ImapAutoItem()
  for l:env in ['itemize', 'enumerate']
    if vimtex#env#is_inside(l:env) != [0, 0]
      return "\<cr>\\item"
    endif
  endfor

  return "\<cr>"
endfunction
```
