### ISSUE TITLE
Glitch (maybe) in syntax for tabulars...

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#1896]
**Issue**
Sometimes the tabular extended arguments (by `array` package) got confused. 

I am opening this file:
```latex
\documentclass{memoir}
\begin{document}
\begin{center}
    \begin{tabular}{>{\ttfamily}l>{\ttfamily}ll}
	\toprule
	parameter &  default & description  \\
	\midrule
	relative thickness & 1.0 & multiply the class thickness \\
	color & none & the color of the circle: \texttt{none} means default \\
	\bottomrule
    \end{tabular}
\end{center}
\end{document}
```

with `gvim -u ./minivimrc arrays.tex` where `minivmrc` is:

```vim
set nocompatible
let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

and I obtain: 

![image](https://user-images.githubusercontent.com/6414907/102328752-c731da00-3f87-11eb-8b5c-f38a0739194a.png)

The puzzling thing is that there are cases in which it works correctly, so I am at a loss --- probably some local problem, but I can't find it. 

**Output from VimtexInfo**
```
System info
  OS: Ubuntu 20.04.1 LTS
  Vim version: VIM 8.1 (1-2269)
  Has clientserver: true
  Servername: GVIM

vimtex project: arrays
  base: arrays.tex
  root: /home/romano/software/bugs/vimtex
  tex: /home/romano/software/bugs/vimtex/arrays.tex
  out: /home/romano/software/bugs/vimtex/arrays.pdf
  log: /home/romano/software/bugs/vimtex/arrays.log
  aux: /home/romano/software/bugs/vimtex/arrays.aux
  fls: 
  main parser: current file
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 56
    fix_paths: 57
    set_errorformat: 55
  document class: 
```

**Comment by lervag** [comment]
Ah, yes: this works correctly if your document is compiled. In this case, there is a file `test.fls` that lists the package `tabularx` and so vimtex recognizes it and loads the appropriate package instructions. This should be easy to confirm.

There is one simple solution available: Specify to always load the tabularx syntax package. You can do it with this:

```vim
let g:vimtex_syntax_packages = {
      \ 'tabularx': {'load': 2},
      \}
```
