### ISSUE TITLE
texMathOper in sub-/super-scripts concealed with blank

### ISSUE THREAD

**Issue by BertrandSim** [lervag/vimtex#1897]
Hi, I use the conceal feature when editing tex files. I notice that while most math sub-/super-scripts are concealed with the appropriate cchars, a few (+-/=) show as a blank char. After investigating for a while, I notice that these happen to be `texMathOper`s.

**minimal.vim**
```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

vsplit
set conceallevel=2
```

**minimal.tex**
```tex
\documentclass{minimal}
\begin{document}
$a_+$
$a_-$
$a_/$

$a^+$
$a^-$
$a^/$
$a^=$
\end{document}
```

**Observed Behaviour**
concealed chars are not displayed for texMathOpers in sub-/super-scripts. Here is a screenshot
![image](https://user-images.githubusercontent.com/46756885/102461336-33453880-4083-11eb-804c-6600a8a03f41.png)

Running `syn clear texMathOper` results in concealed characters displayed, but creates a new problem, as the syntax highlighting is removed.

![image](https://user-images.githubusercontent.com/46756885/102461377-40622780-4083-11eb-8fcb-47b6771274a1.png)

**Expected Behaviour**
concealed chars for texMathOpers in sub-/super-scripts should be displayed correctly, as in s:map_sub and s:map_super in 
.vim/bundle/vimtex/autoload/vimtex/syntax/core.vim

**Further Comments**
Lines 679-691 of .vim/bundle/vimtex/autoload/vimtex/syntax/core.vim seem to be the relevant parts of code. I couldn't figure out a fix however.

**Comment by lervag** [comment]
Thanks: I there were some inconsistency in the super/sub vs mathoperator matching. It should be fixed now.
