### ISSUE TITLE
Allow running arbitrary commands in lieu of choosing a compiler backend

### ISSUE THREAD

**Issue by ashpil** [lervag/vimtex#1898]
**Is your feature request related to a problem? Please describe it.**
I would like to use tectonic as my backend, but it does not natively support a continuous mode, so it would be nice if I could instruct vimtex to use a manual workaround. 

**Describe the solution you'd like**
Using a wrapper like `watchexec`, one can have tectonic recompile a file every time it is changed, as described [here](https://github.com/tectonic-typesetting/tectonic/issues/82): `watchexec --exts tex tectonic file.tex`.
If instead of explicitly instructing vimtex to use a given backend (`vimtex_compiler_x`) one could specify an arbitrary command to be run at the compile/livereload phase (`vimtex_compiler_custom:  tectonic [file]` or `vimtex_compiler_custom_live: watchexec --exts tex tectonic [file]`), this would open vimtex up to a lot more customization at a very low cost, and allow users to use more backends without extra work for the maintainers.

**Describe alternatives you've considered**
I suppose you could just build some sort of `watchexec` feature into vimtex itself, but that doesn't seem nearly as appealing.

**Comment by lervag** [comment]
I've added a first version of a generic compiler. Can you test it and give some feedback? This is still very much WIP, but I hope it might be in the direction you want.

**Comment by KarlWithK** [comment]
Hello, I was trying to use this feature. Am I doing this correct? I tried adding flags to tectonic but I'm unsure how.
```vim
let g:vimtex_compiler_method="generic"
let g:vimtex_compiler_generic = {
    \ 'cmd' : 'watchexec --exts tex tectonic',
    \ 'build_dir' : '',
    \}
```

**Comment by lervag** [comment]
> Hello, I was trying to use this feature. Am I doing this correct? I tried passing flags to tectonic but I'm unsure how. I tried ``--`
> 
> ```viml
> let g:vimtex_compiler_method="generic"
> let g:vimtex_compiler_generic = {
>     \ 'cmd' : 'watchexec --exts tex tectonic',
>     \ 'build_dir' : '',
>     \}
> ```

Yes, this should work, I think. You don't need to specify the build dir if you don't actually specify it.

I don't use `watchexec` much, but I do use `entr`. I just tested this:

```viml
let g:vimtex_compiler_method = 'generic'
let g:vimtex_compiler_generic = {
    \ 'cmd' : 'ls *.tex|entr -c latexmk',
    \}
```

It works as expected. However, it should be noted that there are no callbacks (how would I implement a generic callback function anyhows?). But you can look at the output with `\lo` or `:VimtexCompileOutput`. This should also show you error messages if your command does not work.

By the way: why would you use the generic method when `let g:vimtex_compiler_method = 'tectonic'` already exists (see `:help vimtex-tectonic`)?

**Comment by BachoSeven** [comment]
@lervag As for your last question, I think that the original reason for OP to ask for a generic method was to enable combining `tectonic` with `watchexec` (or `entr`, I guess) to add "continuous" compilation functionality for `tectonic`, which does not support that yet.

**Comment by lervag** [comment]
> @lervag As for your last question, I think that the original reason for OP to ask for a generic method was to enable combining `tectonic` with `watchexec` (or `entr`, I guess) to add "continuous" compilation functionality for `tectonic`, which does not support that yet.

Ah, that makes some sense, I guess. :) But, as I said, for me it seems to work as expected, so I would appreciate more details about what exactly is not working.

**Comment by BachoSeven** [comment]
I had not looked into it properly, now I tried again and it works, using `entr` to place the arguments in the right place for `tectonic`(not sure how to do the same argument substitution trick with `watchexec`):
```
	let g:vimtex_compiler_method='generic'
	let g:vimtex_compiler_generic = {
		\	'cmd': 'ls *.tex | entr -c tectonic /_ --synctex --keep-logs',
		\}
```

Since this is very useful as long as `tectonic` does not support continous compilation, so perhaps there could be another `tectonic-continous` backend which supports callback?
I understand this is a bit of a niche use, but since this is really what OP wanted from this "generic" compiler, perhaps it would be easier to make a wrapper around tectonic, using your favourite `entr/watchexec` program for detecting changes but with the same callback as the `tectonic` backend.

Sorry if the above doesn't make sense, I don't really know how the callback function works

**Comment by lervag** [comment]
> I had not looked into it properly, now I tried again and it works,

Great, glad to hear it.

> Since this is very useful as long as `tectonic` does not support continous compilation, so perhaps there could be another `tectonic-continous` backend which supports callback?

Nah, I don't like that. Instead, I think it could be possible to allow some custom callback functions. That is, I could implement the generic compilers output similar to how it is done with latexmk and allow hooks like what is possible for `:help g:vimtex_compiler_latexmk` (see the `hooks` key in the help text). That would allow something like this:

```vim
function! MyCustomCallback(msg) abort
  if condition(a:msg)
    call vimtex#compiler#callback(!vimtex#qf#inquire(b:vimtex.tex))
  endif
endfunction
let g:vimtex_compiler_generic = {
      \ 'cmd': 'ls *.tex | entr -c tectonic /_ --synctex --keep-logs',
      \ 'hooks': [function('MyCustomCallback')],
      \}
```

**Comment by lervag** [comment]
I've opened a new issue with a description of remaining tasks for the generic compiler. Feel free to comment. I'm closing this issue as it is preceded by the new issue.
