### ISSUE TITLE
`\lr` is not mapped

### ISSUE THREAD

**Issue by cedb12** [lervag/vimtex#190]
The `\lr` sequence should be mapped if reverse search is available. However, `autoload/vimtex/mappings.vim` checks that the following way:
```vim
if has_key(b:vimtex, 'rsearch')
```
whereas the rest of the code seems to look for the key `reverse_search`.

**Comment by lervag** [comment]
Thanks. Should be fixed now.

**Comment by cedb12** [comment]
Thanks! And thank you for your great work. I switched from latex-suite to vimtex last week and I quite like it!

**Comment by lervag** [comment]
Thanks, I'm glad to hear it! Let me know if you find problems or have ideas for improvements.
