### ISSUE TITLE
nvr is required for backwards-search in neovim

### ISSUE THREAD

**Issue by aabacchus** [lervag/vimtex#1900]
In vim, it seems to be necessary to use the syntax `vim --servername vim` to open your file and have backwards-search working, but there is no such option with neovim. I have come across [neovim-remote](https://github.com/mhinz/neovim-remote) and I think this is the necessary solution when using neovim. Is this correct?

**Comment by clason** [comment]
Yes, this is correct.

**Comment by lervag** [comment]
I've added a note in `:help vimtex-requirements` to guide readers into the faq section. I hope that might help new users discover this more easily.
