### ISSUE TITLE
tex file and skim on the same window 

### ISSUE THREAD

**Issue by Tongzhoutz** [lervag/vimtex#1902]
Hello, I am not sure if it is appropriate to ask this question here.

Whenever I execute  ```\lv```, a skim pdf will pop up as an independent page. However, I see a guy's working example is showed below, where the tex file and skim seem on the same window, so that executing  ```\lv``` or ```ctrl+skim``` will not steal focus from the other.

I was wondering how this can be achieved? on ```.vimrc``` or other settings? Thanks.

![v2-c26dc2319b8735e12fb6025ac4089000_b webp](https://user-images.githubusercontent.com/61123232/102813672-35670a00-4397-11eb-8f0c-bfe60b17ecaa.gif)

**Comment by lervag** [comment]
I think the default for the Skim viewer is for `\lv` not to focus Skim, see `:help g:vimtex_view_skim_activate`. Does this not work as expected for you?

**Comment by Tongzhoutz** [comment]
> I think the default for the Skim viewer is for `\lv` not to focus Skim, see `:help g:vimtex_view_skim_activate`. Does this not work as expected for you?

```\lv``` works well on my neovim, but the reverse does not. ```ctrl + skim``` fails to respond.

**Comment by lervag** [comment]
Did you read `:help vimtex-faq-skimviewer`?

**Comment by Tongzhoutz** [comment]
Yes. I do read it and set them in ```.vimrc``` and updated the ```sync``` option on Skim. So I suspect the only reason why it does not work is that when executing ```ctrl + skim``` steals the focus of tex file.

**Comment by lervag** [comment]
I'm sorry, but I really don't understand what you are saying.  What is stealing the focus? What do you mean by `ctrl + skim`?
