### ISSUE TITLE
vimtex break some subscript

### ISSUE THREAD

**Issue by ChasingZenith** [lervag/vimtex#1903]
**Issue**

Using Neovim here. No other latex relevent plugin used here.

1. subscript in `_{}` cannot work with vimtex, but only subscripts like `_i`.

with vimtex
![Untitled](https://user-images.githubusercontent.com/22112456/102915058-2168f880-44bc-11eb-8df9-b445d13ad0f5.png)
without vimtex
![Untitled](https://user-images.githubusercontent.com/22112456/102915198-583f0e80-44bc-11eb-94c8-f2dfd838997f.png)

**minimal.tex**
```tex
\documentclass{minimal}
\begin{document}
$x_i(t+1)=\sum_{j} w_{ij} x_j(t)$
\end{document}
```

**Comment by lervag** [comment]
Yes, that's true. It is impossible to make the subscripts work _in general_, so I chose to simplify things and remove support for the `_{}` variant. However, I guess it could be possible to allow `_{}` subscripts as long as the `{}` group only includes subscriptable characters.

Btw, you **obviously** didn't read the issue template...

> Finally, please remove any boilerplate template content that is not relevant!

**Comment by ChasingZenith** [comment]
Thank you for your respond. But really hope that we can add this feature.
It seems that `vimtex` now cover the conceal provided by built-in vim. Even if I disable syntax by setting
```vim
let g:vimtex_syntax_enable=0
let g:vimtex_syntax_conceal_default=0
```
All syntax conceal disappears, I mean, the built-in conceal does not show up.

Sorry for not obeying the issue rule, have edited.

**Comment by lervag** [comment]
> Even if I disable syntax by setting ...
> All syntax conceal disappears, I mean, the built-in conceal does not show up.

Strange. I'll look into it. Do you have any related configuration, e.g. `let g:tex_conceal`?

> Sorry for mentioning that I want to disable vimtex-syntax which is a milestone for version 2.0 and 2.1. `vimtex` is a great latex plugin in `VIM` and adding syntax feature make it even better. I ask this just because this behave differently and I want to know why.

Don't worry, I wouldn't mind if someone preferred the old syntax scripts either, and it should be possible to disable the vimtex syntax scripts.

> Sorry for not obeying the issue rule, have edited.

No problem, I emphasized it because it was a little bit funny that you left only the part that explicitly asked you to remove it :)

**Comment by lervag** [comment]
Notice that the option is called `g:vimtex_syntax_enabled`.

**Comment by lervag** [comment]
Ok, I've added initial support for super/sub TeX groups. Let me know what you think.

**Comment by ChasingZenith** [comment]
Sorry for making this silly mistake. 

haven't find any different after using `master` now.

I'm not very familiar with writing vim script, so I don't no what you have done, I need some time to learn something about it. I'm busy in these two days, I will take some time on this in this weekend.

**Comment by lervag** [comment]
This is how your example looks like on my end with the most recent version of Vimtex:
![2020-12-24_09:49_screenshot](https://user-images.githubusercontent.com/998898/103076121-5153f100-45cd-11eb-9456-692cf69b1bb8.png)

Please note that the subscript or superscript groups (i.e. `{...}`) that contain unsupported elements will not be changed. For instance with `\sum_{\Delta j}`:
![2020-12-24_09:50_screenshot](https://user-images.githubusercontent.com/998898/103076255-9841e680-45cd-11eb-9827-5bd8f967e161.png)

**Comment by ChasingZenith** [comment]
All I would like to say is "Wow"!!!!!    I couldn't expect more!

> note that the subscript or superscript groups (i.e. `{...}`) that contain unsupported elements will not be changed. 

Leaving (sub-) superscript unchanged if it contains unsupported elements is the dream feature that I was always looking for!

Since some symbols do not have a good conceal in subscript, so some of them in subscript or superscript group (i.e. `{...}`) may show as conceal but some will just broken and show as latex code, which gives a sense of incompleteness. However most of the time they are well behaved conceal if it is not a (sub-) superscipt. (Just like the `\Delta` in the subscript in your example)

Your improvement solve this case and make it much much better.

Since we have this attractive feature now. I think that we can change the gif in `README.md` in the repo main page. Not just showing compiling and quickfix, but also show how elegent it is to type LaTeX with `vimtex`

**Comment by lervag** [comment]
> All I would like to say is "Wow"!!!!! I couldn't expect more!

Great, I'm glad you like it!

> Since we have this attractive feature now. I think that we can change the gif in `README.md` in the repo main page. Not just showing compiling and quickfix, but also show how elegent it is to type LaTeX with `vimtex`

The gif is really old, so I guess it does make sense to update it to show off more of the new features. I'll leave this issue open until I get around to it.

**Comment by j1-lee** [comment]
This is cool. I have been wondering, although I don't use conceal, if there is a way to conceal the inverse sign `^{-1}`. Now vimtex can handle this!

**Comment by lervag** [comment]
Sorry, but it seems I am not really mastering screencasting. I've made a minor update, but I never get satisfied with the result when I try to create a simple, but more advanced example. I would be very happy to consider contributions in this sphere. I've opened #1946, so let's continue the discussion there.

**Comment by lervag** [comment]
FYI: I got help and there is a new quick start video and the README has been updated. Feedback is appreciated.
