### ISSUE TITLE
'g:tex_comment_nospell' option vs vimtex-grammar

### ISSUE THREAD

**Issue by g6ai** [lervag/vimtex#1904]
**Observed Behaviour**
`g:tex_comment_nospell` option was removed in https://github.com/lervag/vimtex/pull/1834 , as discussed in https://github.com/lervag/vimtex/issues/1799#issuecomment-699683162.

I like the new feature as described in the doc, vimtex-grammar section. I have tried **textidote** and **vlty**, they can skip comment spell checking, but I only managed to show the spell check result in the quickfix window rather than Vim's native in-line display (*e.g.* curly underline in gVim).

**Expected Behaviour**
Being able to to ignore comment in Vim's native spell checking, *i.e.* reenable `g:tex_comment_nospell` option; or is there a way to use compilers **textidote** or **vlty** in a manner of output-to-html, so we could see the grammar/spell check inline?

**Comment by lervag** [comment]
Thanks. I've added an option `g:vimtex_syntax_nospell_comments` - if you set it to 1 it will disable spell checking in comments.

Regarding textidote and vlty: these are _not_ linked to the internal spell checker in Vim (e.g. curly underlines). They operate as external tools that rely on the quickfix or location lists to show the list of errors.

> is there a way to use compilers **textidote** or **vlty** in a manner of output-to-html, so we could see the grammar/spell check inline?

I don't understand what this means. What do you mean by `output-to-html`?

**Comment by g6ai** [comment]
Thanks, that helps a lot! By saying `output-to-html`, I mean function like https://github.com/sylvainhalle/textidote#html-report and https://github.com/matze-dd/YaLafi#example-application. On second thought, I think these function can be defined in `.vimrc` by writing a Vim script.

**Comment by lervag** [comment]
Ah, I see. I also think you should add this type of functionality in your `.vimrc`. :)
