### ISSUE TITLE
compile can't start on windows10 if vim use different shell other than cmd

### ISSUE THREAD

**Issue by xubury** [lervag/vimtex#1905]
The compile process can't not start normally if vim was set to use different shell.
For example, I use bash shell as default rather than cmd.
```
if has('win32')|| has('win32unix')
    let $MSYSTEM = 'MINGW64'
    set shell=bash
    set shellcmdflag=--login\ -c
    set shellquote="
    set shellslash
    set shellquote=\"
    set shellxquote=
endif
```
There's message say `vimtex: Compiler started in continuous mode` . But it will never complete.
And `:VimtexCompileOutput` prompt cmd but has no ouput.
However, the behavior is normal using cmd (comment out above vim settings)

**Comment by xubury** [comment]
Somehow I got the error message now, how to fix this?
```
bash: cmd /s /c "set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -xelatex -
outdir=latex.out -pvc -e "$pdf_previewer = 'SumatraPDF.exe -reuse-instance'" -e "$success_cmd = 'echo 
vimtex_compiler_callback_success'" -e "$failure_cmd = 'echo vimtex_compiler_callback_failure'" "fmicw-stagger-algorithm.tex"": 
File name too long
```

**Comment by lervag** [comment]
> The compile process can't not start normally if vim was set to use different shell.
> For example, I use bash shell as default rather than cmd.
> 
> ```
> if has('win32')|| has('win32unix')
>     let $MSYSTEM = 'MINGW64'
>     set shell=bash
>     set shellcmdflag=--login\ -c
>     set shellquote="
>     set shellslash
>     set shellquote=\"
>     set shellxquote=
> endif
> ```
> 
> There's message say `vimtex: Compiler started in continuous mode` . But it will never complete.
> And `:VimtexCompileOutput` prompt cmd but has no ouput.
> However, the behavior is normal using cmd (comment out above vim settings)

> Somehow I got the error message now, how to fix this?
> 
> ```
> bash: cmd /s /c "set max_print_line=2000 & latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -xelatex -
> outdir=latex.out -pvc -e "$pdf_previewer = 'SumatraPDF.exe -reuse-instance'" -e "$success_cmd = 'echo 
> vimtex_compiler_callback_success'" -e "$failure_cmd = 'echo vimtex_compiler_callback_failure'" "fmicw-stagger-algorithm.tex"": 
> File name too long
> ```

Vimtex does not support that you change your shell. On Windows, it assumes that you use `cmd`. If not, it won't work.

I would be happy to consider any PRs to improve this, but I don't want to spend my time improving anything on Windows as I don't use it myself. It is very hard to properly maintain it when I can't really test it.
