### ISSUE TITLE
Is it possible to add a symbol to the neovim built-in statusline when the tex compiler is active in continuous mode?

### ISSUE THREAD

**Issue by danielfalbo** [lervag/vimtex#1906]
I sometimes forget whether I did or did not start the compiler 🤪

**Comment by lervag** [comment]
Yes, this is possible. I've added a convenience function `vimtex#compiler#is_running()` that you can use in your statusline. See the docs for info on the return values.

**Comment by clason** [comment]
Just out of curiosity, is this better than something like
```
let l:status = ''
  if exists('b:vimtex')
    let l:compiler = get(b:vimtex, 'compiler', {})
    if !empty(l:compiler) && has_key(l:compiler, 'is_running') && b:vimtex.compiler.is_running()
      let l:status = '{C}'
    endif
  endif
```
and using this in the status line?

**Comment by lervag** [comment]
Nah, not better, but perhaps slightly simpler? I.e., you can write this instead:

```vim
let l:running = vimtex#compiler#is_running()
let l:status = l:running < 0 ? ''
      \ : (l:running > 0 ? 'Running' : 'Stopped')
```
