### ISSUE TITLE
conceal `\operatorname`

### ISSUE THREAD

**Issue by ces42** [lervag/vimtex#1909]
**Is your feature request related to a problem? Please describe it.**
lots of `\operatorname`s can clutter source code

**Describe the solution you'd like**
This is probably a good candidate for conceal, i.e. concealing the pair `\operatorname{` and `}`

**Additional context**
This would probably even more useful for operators defined with `\DeclareMathOperator` but this sounds much harder.

**Comment by lervag** [comment]
I don't use the conceal feature myself, as I find LaTeX to be quite readable directly, as long as it is written in a consistent manner with indents.

I'm not sure if I understand this request. With `operatorname`, do you mean lots of different operators, or specifically "operatorname"?

**Comment by lervag** [comment]
Examples are always useful!

**Comment by ces42** [comment]
So I'm thinking that since something like
```
\operatorname{Hom}(A, B)
```
is rendered as "Hom(A, B)" it would make sense to display this as 
```
Hom(A, B)
```
when using conceal (it seems to me that the philosophy of vimtex conceal is to display text similiarly to how it is rendered by LaTeX).

**Comment by lervag** [comment]
Yes, the idea behind the conceal feature is to render things more similar to how it looks when rendered by LaTeX, so sorry for pitching my personal opinion (it is really not that relevant).

Do you know which package provides the `\operatorname` command?

**Comment by ces42** [comment]
I think it's amsmath?

**Comment by ces42** [comment]
Concerning what I said about `\DeclareMathOperator`: Usually my documents will end up having several lines like
```
\DeclareMathOperator{\Hom}{Hom}
\DeclareMathOperator{\Aut}{Aut}
\DeclareMathOperator{\End}{End}
```
I was thinking that in theory it should be possible in theory to scan these and define corresponding conceals. However I just realized that vim only allows conceals with a single character, so this would be way too complicated...

**Comment by lervag** [comment]
> Concerning what I said about \DeclareMathOperator: Usually my documents will end up having several lines like ...

Thanks, I forgot to comment that: I also think this may be too complicated. It also seems relatively unnecessary (in your examples, we "save" one character for each command).

But I think it should be possible and relevant to add conceal for the `\operatorname` macro. I'll do it when I get the time.
