### ISSUE TITLE
Changing menu_fmt in g:vimtex_complete_bib requires removing relevant cached file in .cache/vimtex 

### ISSUE THREAD

**Issue by oponkork** [lervag/vimtex#1910]
I just found out that the change in `menu_fmt`  will not work unless the relevant `.json` file in `.cache/vimtex` is removed.
Either we should rebuild the files once `menu_fmt` is changed or document the behavior at the appropriate place.

**Comment by lervag** [comment]
Thanks, I've added a comment in the docs.
