### ISSUE TITLE
Error upon opening any .tex file.

### ISSUE THREAD

**Issue by wee-woo-wee-woo** [lervag/vimtex#1914]
**Issue**
I get an error whenever i open a `.tex` file. The content of the file does not matter, only the extension. I am running vimtex in vim (not neo) on a completely fresh arch linux installation. I have another almost identical system where vimtex works normally.

Vimtex itself seems to work normally, i can compile files with the `.tex` extension etc. Interestingly though, i tried running `:VimtexCompileOutput`, which just opened an empty window. Unsure if this is because i lack configurations.

I doubt this is reproducable, as i can't figure out what difference in my setup the error stems from.
**Commands/Input**
Run `:e test.tex`

**Observed Behaviour**
Following error pops up:
```
Error detected while processing BufRead Autocommands for "*.tex"..function dist#ft#FTtex[47]..FileType Autocommands for "*"..Syntax Autocommands for "*"..function <SNR>11_SynSet[25]..script /home/teis/.vim/plugged/vimtex/syntax/tex.vim[23]..function vimtex#syntax#core#init[402]..<SNR>114_match_math_sub_super:
line   10:
E475: Invalid argument: texMathSuper "(" contained conceal cchar=<E2>~A<BD>
Press ENTER or type command to continue
```
Vim then goes on to actually open the file, and vimtex seems to work in it.
**Expected Behaviour**
Vim should open the file instantly; no error should be displayed (and ideally produced) first.
**Output from VimtexInfo**
```
System info
  OS: Linux 5.10.3-arch1-1
  Vim version: VIM 8.2 (1-1989)
  Has clientserver: false

vimtex project: test
  base: test.tex
  root: /home/rudolf
  tex: /home/rudolf/test.tex
  out:     
  log:     
  aux:     
  fls:    
  main parser: current file
  compiler: latexmk
    configuration:     
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  qf: LaTeX logfile
    addqflist: 316
    fix_paths: 317
    set_errorformat: 315
 document class:
```

**Comment by lervag** [comment]
I assume it has to do with encodings. What's the output of `locale` in your terminal?

**Comment by lervag** [comment]
I've perhaps been sloppy in that I assume everyone has `encoding=utf8`. After opening any file, what's the output of `:set encoding`?

**Comment by wee-woo-wee-woo** [comment]
The output of `locale` is
```
LANG=C
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
```

The output of `:set encoding` is `latin1`

Setting the encoding to `utf-8` fixed my problem. Im not sure why it wasn't that way by default.

**Comment by lervag** [comment]
The value of `encoding` depends on your locale. If you update your locale (see e.g. [here](https://wiki.archlinux.org/index.php/Locale)), you won't need to specify the option.

**Comment by wee-woo-wee-woo** [comment]
Thanks a lot, will do so.
