### ISSUE TITLE
Missing fragile frame titles in ToC

### ISSUE THREAD

**Issue by akononovicius** [lervag/vimtex#1916]
**Issue**

I am missing frame titles in ToC, if those frames are set to be fragile.

**Reproduction**

Minimal *.tex document:
```tex
\documentclass{beamer}

\begin{document}

\begin{frame}[fragile]{I won't be seen}
Test frame.
\end{frame}

\end{document}
```
After running `:VimtexTocOpen` in the ToC I can see just "Frame" without the title "I won't be seen". Removing `[fragile]` fixes the issue. Still I have to use `[fragile]`, because of the nature of my slides.

**Suggested solution**

On my machine I have modified `vimtex/autoload/vimtex/parser/toc/beamer_frame.vim` by replacing line 20 with:
```vim
\ matchstr(a:context.line, self.re . '[^{]*{\zs.*\ze}\s*$'))
```
I have simply replaced "\s*" with "[^{]*", which should match both spaces and allow me to use `[fragile]` without loosing ToC functionality.

Could this (or similar) solution be included into the base plugin code?

**Comment by lervag** [comment]
> Could this (or similar) solution be included into the base plugin code?

Definately. I use a slightly more robust regex, but I think it should work as long as the content is on a single line.
