### ISSUE TITLE
VimtexCountLetters and VimtexCountWords not working for selection

### ISSUE THREAD

**Issue by andryandrew** [lervag/vimtex#1918]
The two commands `VimtexCountLetters` and `VimtexCountWords` do not work anymore when called on a selection (e.g. in visual mode), giving the error:
```
!!! File not found or not readable: main_vimtex_selected !!!
(errors:1)
```

I bisected the issue to commit 659e36d1e43182df6ed73041b9b4480ca1c6c0ab (which makes sense). Other commands which make use of selection ranges (such as `VimtexCompileSelected`) seem to work as intended.

I am using `nvim` but the issue is present in `vim` too.

**Comment by lervag** [comment]
Sorry about that, I think it should work now.
