### ISSUE TITLE
Switch to "xelatex" engine

### ISSUE THREAD

**Issue by Tongzhoutz** [lervag/vimtex#1924]
I am trying to use the package ```xeCJK``` to input Chinese characters, but it seems that I fail to let the ```xelatex``` engine  work, though I have read up some previous posts on this issue.

Here is my ```.vimrc```

```vim
let g:vimtex_view_method = 'skim' 
let g:vimtex_view_general_viewer
    \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
let g:tex_flavor='latex'
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_quickfix_mode=2
let g:vimtex_compiler_progname = 'nvr'
let g:python3_host_prog = '/usr/local/bin/python3'
let g:vimtex_compiler_latexmk_engines={
    \ 'dvipdfex'         : '-pdfdvi',
    \ 'lualatex'         : '-lualatex',
    \ 'xelatex'          : '-xelatex',
    \ 'context (pdftex)' : '-pdf -pdflatex=texexec',
    \ 'context (luatex)' : '-pdf -pdflatex=context',
    \ 'context (xetex)'  : '-pdf -pdflatex=''texexec --xtx''',
    \}
set conceallevel=2
let g:tex_conceal="abdgm"
```

The error message is:

```
/usr/local/texlive/2019/texmf-dist/tex/latex/fontspec/fontspec.sty|45 error| Fatal Package fontspec Error: The fontspec package requires either XeTeX or LuaTeX. You must change your typesetting engine to, e.g., "xelatex" or "lualatex"instead of "latex" or "pdflatex".
```

Here is the minimal tex file:

```tex
%! TEX = xelatex
\documentclass[a4paper]{article}
\usepackage{fontspec}
\usepackage{xeCJK}
\begin{document}
Input Chinese characters. 
\end{document}
```

Here is what the ```VimtexInfo``` reports: 
```
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Skim
  qf: LaTeX logfile
    addqflist: 354
    fix_paths: 355
    set_errorformat: 353
  document class: article
  packages:
    expl3
    fontspec
    xeCJK
    xparse
```

**Comment by lervag** [comment]
Some comments to your config (see comments inline):

```vim
let g:vimtex_view_method = 'skim'

" g:vimtex_view_general_viewer is not relevant when g:vimtex_view_method is set
" to 'skim', you can safely remove the following two options.
let g:vimtex_view_general_viewer
    \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'

" g:tex_flavor is not necessary after version 2.0
let g:tex_flavor='latex'

let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_quickfix_mode=2

" This should be automatically set if `nvr` is available
let g:vimtex_compiler_progname = 'nvr'
let g:python3_host_prog = '/usr/local/bin/python3'

" I don't think you need to set the following option, the default should
" suffice
let g:vimtex_compiler_latexmk_engines={
    \ 'dvipdfex'         : '-pdfdvi',
    \ 'lualatex'         : '-lualatex',
    \ 'xelatex'          : '-xelatex',
    \ 'context (pdftex)' : '-pdf -pdflatex=texexec',
    \ 'context (luatex)' : '-pdf -pdflatex=context',
    \ 'context (xetex)'  : '-pdf -pdflatex=''texexec --xtx''',
    \}
set conceallevel=2

" g:tex_conceal is not relevant for Vimtex after version 2.0, see instead
" :help g:vimtex_syntax_conceal
let g:tex_conceal="abdgm"
```

So, I propose you use the following config instead:

```vim
set conceallevel=2

let g:python3_host_prog = '/usr/local/bin/python3'

let g:vimtex_view_method = 'skim'
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_quickfix_mode=2
```

> Here is the minimal tex file:
> ```
> %! TEX = xelatex
> ```

It seems you did not really read the docs properly, specifically `:help vimtex-tex-program`. Try to change the first line in your minimal tex file to:

> ```
> %! TEX program = xelatex
> ```

**Comment by Tongzhoutz** [comment]
Thanks a lot! I added it to the first line in the correct way. However, the issue still persists on the minimal tex file. The latexmk engine still shows ```-pdf```

**Comment by lervag** [comment]
That's strange. Please provide an updated minimal example, preferably also with a minimal vimrc file. I'll look into it; I believe the problem is in your configuration or in the TeX file.

**Comment by Tongzhoutz** [comment]
Hello @lervag , I have fixed the issue. I truly appreciate your help with that!

**Comment by lervag** [comment]
Great, happy to hear it. What did you need to do to fix it?

**Comment by Tongzhoutz** [comment]
It was a dumb syntax error in tex, irrelevant to vimtex. Thanks!

**Comment by lervag** [comment]
Ah, ok. Well, I'm glad to hear it works now.

**Comment by knsamsdesk** [comment]
Hello @lervag! Enjoying the plug-in so far but I have a couple of questions! 

(1) Is there a way to make the default engine `xelatex` instead of having this be the first line in every `.tex` file I write? 

(2) How do I get forward search to work? For eg., I am not even sure if I am executing right keystrokes to get forward search. So if you could tell me what the command is, I could try again! (I swear I searched all over; I got "option+s" but that does not take me to the correct line in the pdf. 

(3) Re backward search, I read the documentation for skim and followed it but I still could not get it to work. 

Thank you for all your help!
