### ISSUE TITLE
Good font to see the concealed characters? Which font are you currently using?

### ISSUE THREAD

**Issue by danielfalbo** [lervag/vimtex#1926]
https://user-images.githubusercontent.com/39460524/104851549-dfce4080-58f5-11eb-8657-1e51b0affb16.mov

I'm currently using `JetBrainsMono Nerd Font`, but the `ₙ` character is not "defined" in this font. I also tried `FiraCode Nerd Font`, `Hack Nerd Font` and `Menlo` but looks like none of them supports the `ₙ` character.

The perfect font, imo,
* would be a [Nerd Font](https://github.com/ryanoasis/nerd-fonts) (for the icons),
* would have [ligatures](https://github.com/tonsky/FiraCode#whats-in-the-box),
* would support the `ₙ` character and all other characters that this vim plugin uses to conceal mathematical expressions.

Does anyone know such font? Which font are you currently using?

**Comment by lervag** [comment]
Ah, yes, fonts can be challenging. I've been very happy with inconsolata-g for a long time, but I've had to add fallback fonts to add more glyphs/symbols. For this reason I decided to change quite recently, and I now use [Iosevka](https://typeof.net/Iosevka/), which I think looks very good. It has support for a lot of symbols. Not all, but enough for it to work very well for me.

I use urxvt as terminal, and my config is [here](https://github.com/lervag/dotfiles). The relevant config here is under `X/.Xresources`.

**Comment by lervag** [comment]
Note, though: I don't really use the conceal feature of Vimtex myself.

**Comment by clason** [comment]
You might be interested in https://github.com/cormullion/juliamono -- it seems based on JetBrains Mono, visually, and claims wide Unicode coverage at least on par with Iosevka. (No italics, though, which look nice for comments.)

I also don't use conceal, because it can never be more than a Frankenstein monster, typographically :)

**Comment by lervag** [comment]
> You might be interested in https://github.com/cormullion/juliamono -- it seems based on JetBrains Mono, visually, and claims wide Unicode coverage at least on par with Iosevka.

I was not aware of this. I've installed it and my first impression is actually very good. It is a little bit wide, but I'm also now working on a very wide screen. I'll probably try it for some days/weeks to see if I like it better than Iosevka.

> (No italics, though, which look nice for comments.)

Are you saying that the lack of italics makes comments loo nice or that italics, which is lacking, makes comments look nice? There is clearly some support for "curved" characters, but they don't look quite right. So I assume it is the latter.

**Comment by clason** [comment]
> It is a little bit wide, but I'm also now working on a very wide screen.

I can see why you might think so, coming from Iosevka :) (Which is a particularly "thin" font -- it's one of its design goals, even calling itself a "slender typeface" in the "about" ;))

> > (No italics, though, which look nice for comments.)
> 
> Are you saying that the lack of italics makes comments loo nice or that italics, which is lacking, makes comments look nice? There is clearly some support for "curved" characters, but they don't look quite right. So I assume it is the latter.

Sorry, that was ambiguous. I do think italics look nice for comments, so their lack is a drawback for me. (Which is why I'm sticking with SF Mono.)

**Comment by danielfalbo** [comment]
> (By the way, I just checked, and Fira Code definitely supports the subscript-n glyph.)

Ooooh, thank you, I just discovered that the problem is not my font, is my terminal emulator (Alacritty)

**Comment by danielfalbo** [comment]
Should I close this issue now?

**Comment by lervag** [comment]
I guess you can close it, yes. There's no other actions here except possibly to continue the discussion and get more opinions/thoughts on the topic.
