### ISSUE TITLE
New syntax plugin for 'listings' breaks on \lstinline

### ISSUE THREAD

**Issue by bratekarate** [lervag/vimtex#1929]
Since the 2.0 update, I experience some issues with the syntax plugin, more specifically with the "listings" package and `\lstinline`. The end of the macro is not detected, which applies funny colors to the rest of the document.

Example: 
```latex
This is an example using an inline snippet: \lstinline{pacman -R texstudio && pacman -S vim}.
Now follows regular text that should not be highlighted.
```

Old behaviour:
Only the the macro argument in curly braces is highlighted.

Behaviour since 2.0:
All text until the next `{` is highlighted. The following input would render correctly:
```latex
This is an example using an inline snippet: \lstinline{pacman -R texstudio && pacman -S vim{}.
This text will not be highlighted anymore.
```

Workaround: Disable the syntax plugin for the "listings" package by specifying a custom `g:vimtex_syntax_packages` dictionary.

Right now I don't have the time to include a minimal test project, but it should be very easy to reproduce.

Edit: Apperently it's the regex in the `matcher` causing it: https://github.com/lervag/vimtex/blob/5d3d96dcdf0f87273978c482e9c1b39201f4516f/autoload/vimtex/syntax/core.vim#L319-L324

I'm not an expert with listings, in fact I only use the inline listings to reference variable names and one liner commands. I don't really understand the matcher. I will just disable the plugin for now.

**Comment by lervag** [comment]
Thanks, I think it should be fixed now. Note, `\lstinline{...}` is actually experimental, see the listings docs for details.

**Comment by lervag** [comment]
That is, the "proper" syntax is `lstinline<char>...<char>`, where `<char>` is some character. Similar to `\verb`.

**Comment by bratekarate** [comment]
Alright, thanks for the reply and fix. Good to know about the proper `lstinline` syntax, somehow I missed it in my quick google search, although it's fairly obvious. Probably lack of sleep was to blame. Would have tried to fix the regex myself, but I imagined the listings syntax to be more complex than it actually is.
