### ISSUE TITLE
Errors when completing \ref

### ISSUE THREAD

**Issue by yagebu** [lervag/vimtex#193]
When trying to use completion for a reference using YCM in a lengthy maths paper, I get the following error. Disabling all plugins and using `\ref{<C-x><X-o>` had the same effect. After throwing these errors the completion worked however from then on and the errors would not appear again unless I restarted vim.

    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract..<SNR>47_labels_parse_number:
    line    4:
    E730: using List as a String
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract..<SNR>47_labels_parse_number:
    line    4:
    E730: using List as a String
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract..<SNR>47_labels_parse_number:
    line    4:
    E730: using List as a String
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract..<SNR>47_labels_parse_number:
    line    4:
    E730: using List as a String
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract..<SNR>47_labels_parse_number:
    line    4:
    E730: using List as a String
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract..<SNR>47_labels_parse_number:
    line    4:
    E730: using List as a String
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract:
    line   23:
    E684: list index out of range: 1
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract:
    line   23:
    E15: Invalid expression: tree[0][1][0]
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract:
    line   23:
    E684: list index out of range: 1
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract:
    line   23:
    E15: Invalid expression: tree[0][1][0]
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract:
    line   23:
    E684: list index out of range: 1
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract:
    line   23:
    E15: Invalid expression: tree[0][1][0]
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract:
    line   23:
    E684: list index out of range: 1
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract:
    line   23:
    E15: Invalid expression: tree[0][1][0]
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract:
    line   23:
    E684: list index out of range: 1
    Press ENTER or type command to continue
    Error detected while processing function vimtex#complete#omnifunc..vimtex#complete#labels..<SNR>47_labels_get..<SNR>47_labels_extract:
    line   23:
    E15: Invalid expression: tree[0][1][0]

If it's hard to reproduce or you need more information I will try to find a minimal example to reproduce later.

I'm running a current neovim on OS X, but the exact same thing happens in Vim (7.4.712).

**Comment by yagebu** [comment]
I'm able to reproduce most of the errors with the following document. Notice the `documentclass` is `amsart`. That seems to make all the difference, as the errors don't occur with `article`.

    \documentclass{amsart}
    \begin{document}
    \section{Section}
    \label{section}
    \end{document}

**Comment by lervag** [comment]
Haha, I compiled the document, which gives the following `aux` file:
```tex
\relax 
\newlabel{tocindent-1}{0pt}
\newlabel{tocindent0}{0pt}
\newlabel{tocindent1}{17.77782pt}
\newlabel{tocindent2}{0pt}
\newlabel{tocindent3}{0pt}
\@writefile{toc}{\contentsline {section}{\tocsection {}{1}{Section}}{1}}
\newlabel{section}{{1}{1}}
```
Notice `\newlabel{tocindentX}{Ypt}`. I would love to see the reason this is defined through the `\newlabel` command!

The fix should on vimtexs end is easy enough, although it seems stupid to support such a broken documentclass.

**Comment by yagebu** [comment]
Thanks for the quick fix! There are some broken LaTeX packages out there... Even with your fix, I'm still getting errors with my main file. I've narrowed it down to the following:

    \documentclass{article}
    \usepackage{enumitem}
    \begin{document}
    \begin{enumerate}[label=(TEST\arabic*)]
    \item\label{label1} test
    \end{enumerate}
    \end{document}

this will produce the following `.aux` file

    \relax 
    \newlabel{label1}{{{{(TEST1)}}}{1}}

And because the `tex2tree` function parses all the curly brackets, that will throw a `using List as a String` error.

**Comment by lervag** [comment]
Should be fixed now. Thanks for providing the good minimal example!

**Comment by yagebu** [comment]
Now it works beautifully. Thank you!

**Comment by lervag** [comment]
No problem! I'm happy to hear that it works :)

**Comment by davidlowryduda** [comment]
I know I'm late to the party --- I wanted to say that I also had this problem and I'm happy that you fixed it. It works great.

**Comment by lervag** [comment]
:+1:
