### ISSUE TITLE
Add progress information 

### ISSUE THREAD

**Issue by reportaman** [lervag/vimtex#1931]
Am running vimtex/latexmk in continuous mode. For large documents, after I save the file to the time when vimtex opens quick fix list, I don't even know that a compilation is running or my system has frozen... as there is no information (like in airline) that shows that compilation is going on. 

Multiple possible solutions:
[simple] Add a symbol to airline status bar that says document is being compiled.
[full blown] Add a symbol to airline status bar that says document is being compiled, and number of pages generated/processed while tex engine is running. So if tex has already generated 153 (pdf) pages, it would show [153], and the count will keep progressing till compile completes.

The [simple] solution would require adding another symbol, perhaps displayed to left/right of current information on airline. This would be simple I guess as vimtex already reports the event that compilation has completed, and would require some code like this:

```vim
" Compilation is running and continuous compilation is off
call s:SetDefault( 'g:airline#extensions#vimtex#compiled',   "c₁")

" Compilation is running and continuous compilation is on
call s:SetDefault( 'g:airline#extensions#vimtex#continuous', "c")
```
Source: https://github.com/vim-airline/vim-airline/blob/c7a633ce8f4547e680377efe8ea70493fcce1349/autoload/airline/extensions/vimtex.vim#L30-L34

Ideally there would be a way to configure the progress symbol/character, so one can get something more like:

<img width="424" alt="Screen Shot 2021-01-25 at 8 49 36 PM" src="https://user-images.githubusercontent.com/71736629/105801867-ee98a100-5f4e-11eb-8a59-62e0565183f8.png">

**Comment by reportaman** [comment]
Hit enter too soon, am writing the description :)

**Comment by lervag** [comment]
> Am running vimtex/latexmk in continuous mode. For large documents, after I save the file to the time when vimtex opens quick fix list, I don't even know that a compilation is running or my system has frozen... as there is no information (like in airline) that shows that compilation is going on.

Well, `latexmk` is either running or not. Vimtex does not provide any statusline solutions itself, except some relevant APIs that e.g. airline can hook into (e.g. see `:help vimtex-code-api`.

> Multiple possible solutions:
> [simple] Add a symbol to airline status bar that says document is being compiled.
> [full blown] Add a symbol to airline status bar that says document is being compiled, and number of pages generated/processed while tex engine is running. So if tex has already generated 153 (pdf) pages, it would show [153], and the count will keep progressing till compile completes.
> The [simple] solution would require adding another symbol, perhaps displayed to left/right of current information on airline. This would be simple I guess as vimtex already reports the event that compilation has completed, and would require some code like this: ...

These are all solutions that should be considered for airline, not for Vimtex. I propose that you instead open an issue there.

I'm not sure how easy it is to get a more detailed status. Vimtex does add callback events `VimtexEventCompileStarted`, `VimtexEventCompileStopped`, `VimtexEventCompileSuccess`, and `VimtexEventCompileFailed`, that may be used in some statusline feature in e.g. airline. Perhaps combined with `vimtex#compiler#is_running()` (which should be more robust for checking if the compiler backend, e.g. `latexmk`, is running).

**Comment by clason** [comment]
If you absolutely need progress information, you could use https://github.com/latex-lsp/texlab for building, which provides that via the LSP spec. (You can use this in parallel to vimtex.) You also need a client that can show this, of course.
