### ISSUE TITLE
py3 error

### ISSUE THREAD

**Issue by Tongzhoutz** [lervag/vimtex#1932]
Hello,  my old computer is died, so I switched to a new one. However, after I installed everything I need, the vim still does not allow me to write latex files and I have been struggling with this for two days. I think this issue is not related to vimtex plugin, but I think this platform is quite helpful to me to get quick and accurate solutions.

There are several issues that persist, but the urgent one for me is the error related to python3 I guess.  
Whenever I tried to type something in a tex file,  two error messages always pop up (see below):

I have tried to uninstall python3 and re-install them many times. Since I think it is not related to vimtex, I am not providing the minimal tex and .vimrc.

<img width="805" alt="Screen Shot 2021-01-26 at 8 50 18 AM" src="https://user-images.githubusercontent.com/61123232/105853682-f0488000-5fb3-11eb-9a54-1e51dce15abb.png">

<img width="807" alt="Screen Shot 2021-01-26 at 8 49 35 AM" src="https://user-images.githubusercontent.com/61123232/105853693-f2124380-5fb3-11eb-9bba-95b2ca354968.png">

**Comment by Rmano** [comment]
Hmmm, at first glance it seems an UltiSnip error --- do you have a python3-enabled vim? Try

```bash
θ61° [romano:~/research/Covid] % vim --version | grep py
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
[...]
```

**Comment by Tongzhoutz** [comment]
Thanks! That's perhaps the problem. My ```python3``` is not enabled, but I have installed using ```brew install```.

**Comment by Rmano** [comment]
Notice that not only you need to have `python3` installed, also the `vim` program must be compiled with the option to use it.
I do not know how the `brew` system works (no idea about Mac system, really), maybe it will take care of it.

**Comment by Tongzhoutz** [comment]
Problem solved. Sorry for bothering!
