### ISSUE TITLE
vimtex#ui#choose_from does not display on Neovim

### ISSUE THREAD

**Issue by j-hui** [lervag/vimtex#1933]
**Issue**
When I open up a `.bib` file using Neovim, the editor appears to freeze, and I seem to only be able to regain control by hitting <C-c>.

I did some tracing and narrowed it down to the `vimtex#ui#choose_from` function before realizing that this was a UI bug and it was waiting for my input. It turns out this works fine on Vim, and the issue only appears on Neovim. (In Vim, it asks me "Please select an appropriate main file", and offers some numeric choies.)

The issue appears to only be related to printing the prompt to screen. If I fly blind and press a number, it proceeds as normal.

**minimal.vim**

```vim
set nocompatible
filetype plugin indent on
syntax enable

call plug#begin('~/.vimplugins/plugged')
Plug 'lervag/vimtex'
call plug#end()
```

I don't bother showing a `.bib` file here because it's not really specific to any particular thing in there, at least to my knowledge.

**Commands/Input**

Open a `.bib` file in a directory with multiple possible main tex files.

**Observed Behaviour**

Editor appears to hang. It's actually waiting for my input but no prompt is printed to the status line.

**Expected Behaviour**

Prints out a prompt, like it does in Vim.

**Output from VimtexInfo**

Not sure how helpful this is aside from Neovim version, but here:

```
System info
  OS: Linux 5.4.89  Vim version: NVIM v0.4.4
  Has clientserver: true
  Servername: /tmp/nvimQIQnc5/0

vimtex project: main
  base: main.tex <NOTE: this is only this because I picked it from the invisible menu>
  root: .
  tex: main.tex
  out: /home/j-hui/Documents/paper/main.pdf  log: /home/j-hui/Documents/paper/main.log
  aux: /home/j-hui/Documents/paper/main.aux
  fls: /home/j-hui/Documents/paper/main.fls
  main parser: recursive search (bib)
  source files:
    <irrelevant...>
  compiler: latexmk
    configuration:      continuous: 1      callback: 1      latexmk options:        -verbose        -file-line-error        -synctex=1        -interaction=nonstopmode      latexmk engine: -pdf  viewer: General  qf: LaTeX logfile
    addqflist: 57
    fix_paths: 58
    set_errorformat: 56
  document class: article
  packages:
    <irrelevant...>
```

**Comment by j-hui** [comment]
Turns out it's because Neovim sets `F` for `shortmess` by default, which supresses autocommand output: https://github.com/neovim/neovim/issues/12288

Not sure there's a workaround here for Vimtex. But perhaps the prompt should at least try to catch `<C-c>` and terminate gracefully/default to some option instead of crashing and leaving the buffer in a strange state?

**Comment by j-hui** [comment]
Actually, adding `unsilent` in from of every `echo` and `echon` in `autoload/vimtex/echo.vim` seems to work.

**Comment by lervag** [comment]
To summarize: the problem is reproduced if you have two files, e.g. `test1.tex` and `test2.tex`, both of which include some other file `test.bib`. If you open `test.bib`, Vimtex will ask for which file should be selected as the main file. With default Neovim settings with `F` in `shortmess`, the menu text from `vimtex#ui#choose_from` is not displayed. I can confirm this on Neovim nightly.

**Comment by lervag** [comment]
And with that, I think the issue is solved. Please test.

**Comment by j-hui** [comment]
Yeah, works for me! Thanks for the fix.

**Comment by lervag** [comment]
No problem,  and thanks for noticing and reporting!
