### ISSUE TITLE
How this maps work

### ISSUE THREAD

**Issue by rudrab** [lervag/vimtex#1935]
Hi, I am very new to Vimtex and still trying to come out of vim-Latex's muscle memory. 
I have managed to get greek letters, by defining let `g:vimtex_mappings_leader`, but I cant get `...` or `^^`.  This is very old thread, but is those mapping still there or moved to sinppets completey or I am missing something?

``` vimL
let g:vimtex_imaps_default = [
        \ { 'map' : ['...',   '\dots'],               'leader' : '' },
        \ { 'map' : ['<m-i>', '\item '],              'leader' : '' },
        \ { 'map' : ['__',    '_\{$1\}'],             'leader' : '',   'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['^^',    '^\{$1\}'],             'leader' : '',   'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['((',    '\left($1\right)'],     'leader' : '',   'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['[[',    '\left[$1\right]'],     'leader' : '',   'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['{{',    '\left\\{$1\right\\}'], 'leader' : '',   'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['i',     '\int_{$1}^{$2}'],      'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['qK',    '\Uparrow'],            'wrapper' : 's:wrap_math_ultisnips'},
        \ { 'map' : ['a',     '\alpha'],              'wrapper' : 's:wrap_math'},
        \ { 'map' : ['Y',     '\Psi'],                'wrapper' : 's:wrap_math'},
        \]
```

_Originally posted by @lervag in https://github.com/lervag/vimtex/issues/251#issuecomment-149310708_

**Comment by rudrab** [comment]
Hi, I have found, with `h vimtex-imaps`, that these are not inbuilt, and I have to define them

**Comment by lervag** [comment]
> I have managed to get greek letters, by defining let `g:vimtex_mappings_leader`, but I cant get `...` or `^^`. This is very old thread, but is those mapping still there or moved to sinppets completey or I am missing something?

No, that issue is as you say very old, and the snippet is no longer valid.

> Hi, I have found, with `h vimtex-imaps`, that these are not inbuilt, and I have to define them as:
> 
> ```
>  " Using UltiSnips#Anon
>     inoremap <silent> __ __<c-r>=UltiSnips#Anon('_{$1}$0', '__', '', 'i')<cr>
>     inoremap <silent> ^^ ^^<c-r>=UltiSnips#Anon('^{$1}$0', '^^', '', 'i')<cr>
> 
> A drawback with the anonymous UltiSnips snippets is that they do not nest.
> That is, if you did `__` twice in a row, only the second one could be escaped.
> In recent versions of |UltiSnips|, one may set normal snippets to trigger
> automatically, see |UltiSnips-autotrigger|. This allows nesting, and is
> therefore a better approach than using the anonymous snippet function.
> ```
> 
> So, while anno is working,

What do you mean with "anno"?

> what is the suggested method? Write a full snippet with
> `snippet ^^ "Superscript" A` ?

I think this is explained in the docs (`:help vimtex-UltiSnips`):

```
Note: that this feature is not the same as the snippet feature of |UltiSnips|
or |neosnippet|. The imaps feature of Vimtex previously supported `automatic`
snippets, but these have been removed after careful considerations and input
from Vimtex users, please see vimtex issue #295: ...
```

So, the suggested solution is to rely on a more full blown snippet solution, e.g. UltiSnips. This is another plugin, so you must install it. When you do, then the snippets sugested should "just work".
