### ISSUE TITLE
Easiest way to port csc/dsc to other languages?

### ISSUE THREAD

**Issue by noib3** [lervag/vimtex#1936]
I really enjoy the ability to change/delete the surrounding commands with the `csc`/`dsc` bindings that vimtex provides, and I miss it a lot when I'm writing in other programming languages.

Is there a way to port those commands to other languages? For example, having `dsc` in python would allow to easily turn `print(type("Vimtex is great!"))` into `print("Vimtex is great)`, and so on.

I imagine the logic would be the same, except there's no need for backslashes and curly braces turn into round braces.

**Comment by lervag** [comment]
> I really enjoy the ability to change/delete the surrounding commands with the `csc`/`dsc` bindings that vimtex provides, and I miss it a lot when I'm writing in other programming languages.

Thanks; I agree this is a useful feature! It is inspired by [vim-surround](https://github.com/tpope/vim-surround).

> Is there a way to port those commands to other languages? For example, having `dsc` in python would allow to easily turn `print(type("Vimtex is great!"))` into `print("Vimtex is great)`, and so on.

Yes, definitely. vim-surround of course works quite well, but I prefer [vim-sandwich](https://github.com/machakann/vim-sandwich). My personal configuration vim-sandwich is [here](https://github.com/lervag/dotvim/blob/a7ff88e142d3f16ec1bd1b8880d423484984c68f/vimrc#L810-L888) (but you should read the docs and find something that works for you!).

In case you're not already aware, you should also learn about text objects and look into [targets.vim](https://github.com/wellle/targets.vim).
