### ISSUE TITLE
Does vimtex expose the current project root?

### ISSUE THREAD

**Issue by yrammos** [lervag/vimtex#1938]
Dear @lervag ,

Thank you for this extraordinary plugin, which is gradually becoming a staple of my daily work.

I'm beginning to experiment with texlab in an effort to adopt LSP as broadly as possible, as early as possible, even at the  shorter-term expense of features.

ALE is my current LSP client and, unfortunately, texlab requires that the current project root be set to a global parameter, as follows:

`let g:ale_lsp_root = {'texlab': <Project_Root_Path>}`

But of course I'm not prepared to yield primary control of my tex workflow to texlab, which should have an auxiliary role for completion purposes only.

My probably naive question, then, is whether vimtex exposes the current project root through an API call or global variable. One crude solution would be to just set the texlab parameter to the current buffer path in an `autocmd`:

`g:ale_lsp_root = {'texlab': expand('%:p:h')}` 

But this would be a rather fragile solution.

Many thanks.

**Comment by clason** [comment]
The LSP client/server should handle project root detection by itself; no need for vimtex to get involved. I'm using texlab in parallel with vimtex, and never had a problem (using first `vim-lsp` and now the neovim builtin LSP client), so this seems to be an issue with ALE. I'd suggest (at least to try) switching clients.

**Comment by yrammos** [comment]
@clason thank you for this advice. I've edited my question to clarify, as you correctly inferred, that ALE is my current LSP client. I'm tempted to use `vim-lsp` as you say, but even more tempted to switch to the nightly builds of neovim 0.5, if its stability inspires confidence for real work (academic deadlines etc.). May I ask for your impressions so far?

**Comment by clason** [comment]
I've been using it as a daily driver for more than a year now. There have been a few times where master had some breaking bugs that impacted work, but it's easy to revert to a last good commit. Do be aware that this requires investing a bit of time to follow development and sometimes to adapt configurations to changes in neovim since development is still ongoing. (The main API should be relatively stable now, though.) If you want to set it up and forget about it, I'd definitely recommend `vim-lsp`. (There's also `coc-texlab` if you are already invested in that ecosystem, e.g., via `coc-vimtex`.)

**Comment by yrammos** [comment]
@clason this is perfectly clear. I'll opt for the the `vim-lsp` avenue then and slowly prepare for 0.5 by avoiding non-LSP sources in my deoplete. I'm reluctant towards the powerful `coc` ecosystem because of its design principles.

Not to turn this thread into a freeform discussion, nonetheless may I ask, finally, whether you use ALE for linting? It is an extraordinarily stable and clean plugin, and I've grown somewhat attached, but now begin to doubt whether I should be running two LSP clients at once.

**Comment by clason** [comment]
I think `vim-lsp` is a very solid choice, as is `asyncomplete` for autocompletion (pure vim). 

I do not use ALE for linting because I find this too intrusive and opinionated (especially style suggestions). In future, texlab may support basic static LaTeX code checking by exposing parser errors, though, and I'd consider enabling that.

**Comment by lervag** [comment]
> Thank you for this extraordinary plugin, which is gradually becoming a staple of my daily work.

Thanks for the kind words!

> My probably naive question, then, is whether vimtex exposes the current project root through an API call or global variable.

Yes: You can rely on the variable `b:vimtex.root` to be correct in any given LaTeX buffer (if it is not, then please report it!).

Regarding LSPs, I've also started to use them (with coc as a backend), but I've not yet delved into texlab. I probably will, at some time. So for now, I think people like @clason are better at suggesting how to make Vimtex work well with texlab.

I also use ALE for linting, and I'm quite happy with that. I do, though, disable linting for most file types and only activate certain things like `pylint` for Python. I don't have any linters for LaTeX. I do not use ALE as an LSP client, and I don't think it is a problem to keep it alongside alternative LSP clients.

I'm closing this, but feel free to continue the discussion. I really don't mind free form discussions and exchanges of experiences and ideas!

**Comment by yrammos** [comment]
Thanks @lervag. I'm grappling with this issue as we speak on this fair Sunday. So far I'm disappointed by the lagginess of Texlab. The alternative LSP server, digestif, is supposed to be faster, but unfortunately building from source is failing on my Mac.

The beauty of ALE is that its stability and friendless—qualities not to be taken for granted in this ecosystem.

Thank you for the `b:vimtex.root` tip!

**Comment by lervag** [comment]
> Thanks @lervag. I'm grappling with this issue as we speak on this fair Sunday. So far I'm disappointed by the lagginess of Texlab. The alternative LSP server, digestif, is supposed to be faster, but unfortunately building from source is failing on my Mac.

Feel free to share your experiences when you've worked with it more.

> The beauty of ALE is owed to its stability and friendless—qualities not to be taken for granted in this ecosystem.

Yes, agreed. I find ALE is quite good at what it does, although I didn't really like that it became an LSP client. Still, as a linting backend it is very good.

> Thank you for the `b:vimtex.root` tip!

No problem! :)
