### ISSUE TITLE
Syntax highlighting for some cleveref macros missing

### ISSUE THREAD

**Issue by pitkling** [lervag/vimtex#1939]
For quite some time I had some code in my `after/syntax/tex.vim` to support syntax highlighting in some additional cleveref macros, in particular `\lcnamecref`, `\lcnamecrefs`, `\namecref`, and `\namecrefs`. That code stopped working recently, I'm assuming due to the recent changes in the syntax highlighting of vimtex.

Trying to fix that, I stumbled upon your code in `vimtex/autoload/vimtex/syntax/p/cleveref.vim` and began to wonder whether these macros were just forgotten to include there. Or is there any reason not to add them there?

(FYI: The macros' purpose is basically to refer to the "type-name" of an element. For example, referring to the label of a lemma via `\namecref{let:lemma1}` would return "Lemma".)

**Comment by lervag** [comment]
> Trying to fix that, I stumbled upon your code in `vimtex/autoload/vimtex/syntax/p/cleveref.vim` and began to wonder whether these macros were just forgotten to include there. Or is there any reason not to add them there?

No reason, except I've never used these myself and noone has previously requested them. I'll add them, but could you give me some concrete examples for each variant so I know how they should work (i.e., how the syntax should work, specifically)? For instance, are the usage for all of these similar? Do they take the same kind of optional argument(s)? And so on.

**Comment by pitkling** [comment]
The full set of macros related to this is
*   `\namecref`
*   `\nameCref`
*   `\lcnamecref`
*   `\namecrefs`
*   `\nameCrefs`
*   `\lcnamecrefs`

They all take only a single mandatory argument, which is a label. I don't think it matters here, but in contrast to `\cref` you cannot pass multiple labels separated by commas. (Information taken from current cleveref documentation, Section 4.)

As a specific example, given code like
```
\begin{lemma}\label{lem:fancy}
…
\end{lemma}
```
you can use code like `…the above \lcnamecref{lem:fancy} highlights…` to get "…the above lemma highlights…".

**Comment by lervag** [comment]
Let me know what you think of the latest version. I think it should suffice, but if you find anything wrong with it, let me know.

**Comment by pitkling** [comment]
Perfect, works like a charm! Thanks! :)

**Comment by lervag** [comment]
Great, and no problem; thanks for opening the issue :)
