### ISSUE TITLE
Fatal error occurred when compiled

### ISSUE THREAD

**Issue by Tongzhoutz** [lervag/vimtex#1943]
I ran into a bizarre error when a tex file is compiled. The compilation fails with an error message showing that some usual package cannot be found, such as ```amsthm.sty```. 

Here is a minimal tex file:

```
\documentclass[12pt]{article} 
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsfonts}
\usepackage{amsthm}
\begin{document}

$\mathbb{E}[x | y]$

 \end{document}
```

The compilation fails show that 
```
File `amsthm.sty' not found .
```

Here is the `VimtexInfo` output:
```
  main parser: current file
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: 5
    pid: 22265
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'hwww.tex'
  viewer: Skim
  qf: LaTeX logfile
    root: /Users/tongzhou/Dropbox/2021_Spring/Econometrics/hw1
    addqflist: 354
    errorformat_saved: %-G%.%#Underfull%.%#,%-W%.%#Overfull%.%#,%-G%.%#specifier changed to%.%#,%-G%.%#You have requested%.%#,%-G%.%#Missing number%\, treated as zero.%.%#,%-G%.%#There were undefined references%.%#,%-G%.%#Citation %.%# undefined%.%#,%E! LaTeX %trror: %m,%E! %m,%E%f:%l: %m,%+WLaTeX %.%#Warning: %.%#line %l%.%#,%+W%.%# at lines %l--%*\d,%+WLaTeX %.%#Warning: %m,%+WPackage %.%#Warning: %m,%-Z [],%-Z,%-C(%.%#) %#%m on input line %l.,%-C(%.%#) %#%m,%-Cl.%l %m,%-Cl.%l ,%-C  %m,%-C%.%#-%.%#,%-C%.%#[]%.%#,%-C[]%.%#,%-C%.%#%[{}\]%.%#,%-C<%.%#>%m,%-GSee the LaTeX%m,%-GType  H <return>%m,%-G ...%.%#,%-G%.%# (C) %.%#,%-G(see the transcript%.%#),%-G\s%#,%-C%.%#,%-O[%*\d]%r,%-Q %#)%r,%-Q %#[%\d%*[^()])%r,%-Q %#])%r,%-O(%f)%r,%-P(%f%r,%-P%*[^()](%f%r,%-P(%f%*[^()],%-P[%\d%[^()]%#(%f%r,%-P(%f%r,%-Q)%r,%-O(%f)%r,%-O[%*\d]%r,%-P(%f%r,%-Q)%r,%-O(%f)%r,%-O[%*\d]%r,%-P(%f%r,%-Q)%r,%-O(%f)%r,%-O[%*\d]%r,%-P(%f%r,%-Q)%r,%-O(%f)%r,%-O[%*\d]%r,%-O[%*\d,%-O,%-G%.%#,%-O%.%#
    fix_paths: 355
    main: /Users/tongzhou/Dropbox/2021_Spring/Econometrics/hw1/hwww.tex
    set_errorformat: 353
  document class: article
```

**Comment by lervag** [comment]
Strange, but how come you think this is related to Vimtex?

I can not reproduce this on my end. Can you reproduce this without Vimtex in a terminal with simply `latexmk hwww.tex`?

**Comment by Tongzhoutz** [comment]
> Strange, but how come you think this is related to Vimtex?
> 
> I can not reproduce this on my end. Can you reproduce this without Vimtex in a terminal with simply `latexmk hwww.tex`?

Thanks for your suggestion!  I tried ```latexmk hwww.tex``` and the issue persists. I seems that the error is related to many paths related to ```TinyTex```, because I installed it on my Rstudio out of curiosity yesterday. I have uninstalled it from Rstudio, but the issue is still unresovled. Could you shed lights on how to diffuse it? Thanks

**Comment by Tongzhoutz** [comment]
Sorry to bother. The problem has been sovled! I re-install and then uninstall Tinytex immediately! The trick seems working.

**Comment by lervag** [comment]
No problem, and good to hear that you've figured it out :)

**Comment by TornaxO7** [comment]
If I see it right, this issue has been solved. Shouldn't it be closed than?

**Comment by lervag** [comment]
Yes, thanks!
