### ISSUE TITLE
Wrong expl3 syntax highlighting with optional arguments and with \use:x

### ISSUE THREAD

**Issue by dcpurton** [lervag/vimtex#1945]
**Issue**

I've noticed two errors with `expl3` syntax highlighting (which is a *really* nice feature BTW).

1. In optional arguments, underscore (`_`) and colon (`:`) characters are not treated as part of the variable or function name.
2. Functions without an underscore do not treat colon (`:`) characters as part of the function (e.g., `\use:x`).

I'm running VIM 8.2.2434 under Debian bullseye/sid.

**minimal.vim**
```vim
set nocompatible
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

**minimal.tex**

This function (from `pdfoverlay.sty`) demonstrates both problems:

```tex
\ExplSyntaxOn
\cs_new:Nn \__pdfoverlay_format_pdf_page:
  {
    \hcoffin_gset:Nn \g__pdfoverlay_pdf_page_coffin
      {
        \use:x
          {
            \exp_not:N \includegraphics
              [ \clist_use:Nn \g__pdfoverlay_graphics_options_clist { , } ]
              { \g__pdfoverlay_pdf_file_name_str }
          }
      }
  }
\ExplSyntaxOff
```

**Comment by lervag** [comment]
> I've noticed two errors with `expl3` syntax highlighting (which is a _really_ nice feature BTW).

Happy you like it! And opening issues to report errors are a good way to help me improve it :)

I've tried to address both of your concerns. Let me know if this regresses something or if I missed anything.

**Comment by dcpurton** [comment]
Thanks! That seems to work well!
