### ISSUE TITLE
Unmatched “}” on tabular cell format options for paragraph

### ISSUE THREAD

**Issue by joaoandreporto** [lervag/vimtex#1947]
**Issue**
Closing curly-bracket undetected on tabular cell format options for paragraph, with output "<- unmatched “}”" (see image below);

<img width="843" alt="issue screenshot" src="https://user-images.githubusercontent.com/78543243/107065665-8d819080-67cc-11eb-9cc2-9a1354fcc5c2.png">

isolated issue code: https://pastebin.com/5A6gMfhP

**Context**
The code is following a tutorial on latex and it compiles correctly outside vim (i.e. with texmaker), so my hypothesis is that it may be related to vimtex;

**:VimtexCompileOutput**
https://pastebin.com/8rGn9fQn

**.vimrc (content relevant to the issue only)**
https://pastebin.com/w746K5dw

I would like to know if I am missing something and/or if you could provide me with a solution for this problem.
Thank you.

**Comment by lervag** [comment]
Hmm. I've thought the `p{..}` was only available when you used the `tabularx` package. Notice that the syntax works if you add this package.

I'll update and add this as part of the core syntax.

**Comment by lervag** [comment]
Essentially, the following is allowed:

```tex
\documentclass{minimal}

\begin{document}

\begin{tabular}{|l|p{2cm}|}
  \hline
  Lorem ipsum & Lorem ipsum dolor  \\ \hline
\end{tabular}

\end{document}
```

**Comment by joaoandreporto** [comment]
I updated vimtex and now the tabular `p{..}` format option works as intended (i.e. the .tex file compiles correctly). Using the `tabularx` package, as you suggested, corrects the highlighting. 

The syntax error message for `unmatched “}”` still remains though, along with others that are raised as a consequence from the `unmatched “}”`, thus hindering the whole syntax checking process.

I installed neomake and used it instead of syntastic, the output is the same and i’m in doubt if this has to do with the syntax checkers (or even any other component) and not vimtex itself.

vim screenshot:
<img width="842" alt="vim_neomake_screenshot" src="https://user-images.githubusercontent.com/78543243/107099897-69d93d00-6802-11eb-82f1-c993caaa714b.png">

compiled file screenshot:
<img width="829" alt="compiled_tex_file_excerpt" src="https://user-images.githubusercontent.com/78543243/107099927-7b224980-6802-11eb-8fb2-a59cfba7a485.png">

It would be neat if the syntax checkers did not call on this error, since it is not valid. Wondering if this is this possible?

**Comment by lervag** [comment]
> The syntax error message for `unmatched “}”` still remains though, along with others that are raised as a consequence from the `unmatched “}”`, thus hindering the whole syntax checking process.

Ah, but that is not Vimtex. I suspect you use ALE or something similar with lacheck as a linter. At least, the message implies lacheck here, and Vimtex does not have any auto linting features (you can run lacheck with `compiler lacheck` then `make`, see `:help vimtex-lint`).

**Comment by joaoandreporto** [comment]
That is correct, I was using syntastic, switched to neomake (both of them using lacheck) and the problem still persisted.

I disabled all linting plugins, ran `:compiler lacheck|lmake`, as you've suggested and still got the same result:

<img width="838" alt="vim_lwindow" src="https://user-images.githubusercontent.com/78543243/107119455-2f5db780-6877-11eb-9b5a-94b14994b1fb.png">

**Comment by lervag** [comment]
> I disabled all linting plugins, ran :compiler lacheck|lmake, as you've suggested and still got the same result:

Yes, exactly as expected. `lacheck` is _not_ Vimtex. So if you think this is wrong by lacheck, then you should contact lacheck's maintainer, not me. :)

**Comment by joaoandreporto** [comment]
That’s all. Thank you for answering and developing Vimtex.

**Comment by lervag** [comment]
Btw, as noticed earlier, the tabular environment was not supported correctly. I have made some corrections that at the very least should make Vimtex more consistent with a plain LaTeX file and with the `array` and `tabularx` packages.

**Comment by lervag** [comment]
> That’s all. Thank you for answering and developing Vimtex.

Great, and my pleasure. I'm happy you find it useful.

**Comment by joaoandreporto** [comment]
> Btw, as noticed earlier, the tabular environment was not supported correctly. I have made some corrections that at the very least should make Vimtex more consistent with a plain LaTeX file and with the `array` and `tabularx` packages.

I’ve updated Vimtex and can confirm that. Now, without importing `tabularx`, the highlighting is correct and it does not present an issue.

I am new to TeX and hadn’t covered the checkers yet, that was what I was missing. Meanwhile, I’ve switched from `lacheck` to `chktex`, which does not display any warning or error for `unmatched “}”` and although I have just started using it, personally find `chktex` output more fitting.

> Great, and my pleasure. I'm happy you find it useful.

Bridging Vim and TeX is extremely useful. Thank you.

**Comment by lervag** [comment]
> > Btw, as noticed earlier, the tabular environment was not supported correctly. I have made some corrections that at the very least should make Vimtex more consistent with a plain LaTeX file and with the `array` and `tabularx` packages.
> 
> I’ve updated Vimtex and can confirm that. Now, without importing `tabularx`, the highlighting is correct and it does not present an issue.

Thanks, I appreciate that you also tested and confirmed this.

> I am new to TeX and hadn’t covered the checkers yet, that was what I was missing. Meanwhile, I’ve switched from `lacheck` to `chktex`, which does not display any warning or error for `unmatched “}”` and although I have just started using it, personally find `chktex` output more fitting.

Thanks for the info. I don't really use these checkers myself, but it is useful to know of you experience.

> > Great, and my pleasure. I'm happy you find it useful.
> 
> Bridging Vim and TeX is extremely useful. Thank you.

Agreed; your welcome!
