### ISSUE TITLE
Add auto-completion feature for font names

### ISSUE THREAD

**Issue by reportaman** [lervag/vimtex#1948]
One of the noticeable slowdowns for designing & writing quick and short documents using LaTeX is that one has to find and enter the postscript name of the fonts. This can be especially painful while iterating through system fonts, building pdf from tex and seeing how the output would look like.

I would like a solution where after typing `fn:` (followed by some keys like `<C-p>`) it should bring up a auto completion list with all font names in the system. Users will be asked for a pointer to a text file that has postscript names of all fonts: one font per line. Users will be responsible to keep that file updated as they install new fonts on their system, which I guess anyway varies by system. The line could be just a postscript font name or full path, the completion should just replace `fn:` with whatever user selects.

Am new to TeX, so don't know how it will blend in well with other plugins like YouCompleteMe, etc.

**Comment by lervag** [comment]
> I would like a solution where after typing `fn:` (followed by some keys like `<C-p>`) it should bring up a auto completion list with all font names in the system.

What does this have to do with LaTeX? Can you instead try and explain where in your TeX workflow you want the actual completion?

**Comment by reportaman** [comment]
@lervag Yes it doesn’t have to do something exclusively with LaTeX. Ideally I would want this same feature to work with files with other extensions (like .css, .vimrc, or any other plain text file actually). The way it does relate to Tex is this: it’s going to enhance user experience of producing documents with Tex/Vimtex duo. Also, I tried some dictionary based solution from online, and it turned out to be quite slow. As I mention, am new to Vim... I have heard of some plug-in called YouCompleteMe, though the documentation seems pretty daunting & there are no simple examples that I can find. And I also don’t know if it’s going to be the right approach, and if it will interfere with Vimtex...

**Comment by lervag** [comment]
> @lervag Yes it doesn’t have to do something exclusively with LaTeX. Ideally I would want this same feature to work with files with other extensions (like .css, .vimrc, or any other plain text file actually). The way it does relate to Tex is this: it’s going to enhance user experience of producing documents with Tex/Vimtex duo. Also, I tried some dictionary based solution from online, and it turned out to be quite slow. As I mention, am new to Vim... I have heard of some plug-in called YouCompleteMe, though the documentation seems pretty daunting & there are no simple examples that I can find. And I also don’t know if it’s going to be the right approach, and if it will interfere with Vimtex...

My point is: I won't implement something in Vimtex that is not really directly useful for writing LaTeX. That is, what you are asking is much more general, and as such, it could be a separate plugin. Thus, I don't see why it should be part of Vimtex.

I think you can implement something like what you want with dictonary completion where you populate your dictionary manually.

I.e., assume you create a file like `~/.vim/my_fonts` where each line is the name or path of a font. Perhaps you can create this with e.g. `fc-list`. Then you add to your vimrc something like `set dictionary=~/.vim/my_fonts`. Now you should be able to complete with `<c-x><c-k>`. For more info, see `:help 'dictionary'` and `:help 'complete'`.
