### ISSUE TITLE
Make \tag plaintext while in align environment

### ISSUE THREAD

**Issue by agentfire170** [lervag/vimtex#1949]
**Is your feature request related to a problem? Please describe it.**
I use UltiSnips to generate predefined LaTeX macros, and categorize them by if I want them to run in math mode or not. The `\tag{}` command (used in align environments to give commentary on the side) converts everything inside it to text mode, and out of math mode. The syntax highlighting for `\tag{}` is still math mode though.

**Describe the solution you'd like**
The text in `\tag{}` should be treated as plain text, just like the text inside `\intertext{}`.

**Contextual Screenshots**
![code](https://user-images.githubusercontent.com/48545987/107126023-40252200-68a5-11eb-9aa3-66ffa6c05120.png)
![text](https://user-images.githubusercontent.com/48545987/107126024-40bdb880-68a5-11eb-8815-c78522241f23.png)

**Comment by lervag** [comment]
Thanks, I've added support for `\tag` and `\tag*` now.
