### ISSUE TITLE
Inconsistent spell checking of different natbib commands

### ISSUE THREAD

**Issue by johangustafsson** [lervag/vimtex#1951]
In

> \cite{notaword}

"notaword" is not flagged as misspelled, which is expected behavior. But in each of

> \citealt{notaword}
> \citeyear{notaword}
> \citeyearpar{notaword}

"notaword" is flagged as misspelled, which is not expected behavior. I would like the spell check to ignore the arguments of \citealt, \citeyear, and \citeyearpar just like it avoids the argument of \cite.

**Comment by lervag** [comment]
That should be easy, but could you provide a full minimal example of this? I.e. a small LaTeX document with a bib file that compiles, and where the spell checking fails as explained.

**Comment by johangustafsson** [comment]
\documentclass[12pt]{article}
\usepackage{natbib}
\begin{document}
Works (no spelling flag on `notaword'):
\cite{notaword}
Does not work (spelling flag on `notaword'):
\citealt{notaword}
\citeyear{notaword}
\citeyearpar{notaword}
\end{document}

**Comment by lervag** [comment]
Thanks, but notice that this document does not compile...

**Comment by johangustafsson** [comment]
Ok, I now think I get what is going on. The above example does not actually cause the problem. The problem only occurs when I comment out "\usepackage{natbib}". In my normal latex documents, I do not have a "\usepackage{natbib}" line; I use load another package that loads natbib. So I guess vimtex assumes that I am not using natbib.

I can get the syntax and spell check to work running:
call vimtex#syntax#packages#load('biblatex')

**Comment by lervag** [comment]
Ah, no: Vimtex does not assume you are using natbib, and if we can't parse it from the preamble it becomes difficult. However, if you compile your document, then there should be an `.fls` file that Vimtex parses that recognizes natbib. So, can you check if this works as long as your document is compiled?

**Comment by johangustafsson** [comment]
If I compile with the `--recorder` option so that a `.fls` file is created, then syntax and spell checking works. I rather not have a `.fls` file. But, since I can fix this now on my own with the call I mentioned earlier, I think this might be an edge case that isn’t worth fixing.

**Comment by lervag** [comment]
> If I compile with the `--recorder` option so that a `.fls` file is created, then syntax and spell checking works. I rather not have a `.fls` file.

I'm curious, why?

> But, since I can fix this now on my own with the call I mentioned earlier, I think this might be an edge case that isn’t worth fixing. Thanks for the help!

You can also do this with an option, see `:help vimtex_syntax_packages`. E.g.:

```vim
let g:vimtex_syntax_packages = {
      \ 'natbib': {'load': 2},
      \}
```

**Comment by johangustafsson** [comment]
Great, the `g:vimtex_syntax_packages` solution works. I will use that.

I try to keep as few help files as possible (after a finished LaTeX-compilation cycle) to avoid clutter. So I only keep `.pdf`, `.tex`, `.bib`, and `synctex.gz` files, once compiling is complete.
