### ISSUE TITLE
Make command "cse" also work if the environment name doesn't match between begin/end

### ISSUE THREAD

**Issue by reportaman** [lervag/vimtex#1952]
I tend to change name of environment in either begin{<envname>} or end{<envname>} command more often if there is a typo than for other cases. And 'cse' doesn't allow a <envname> change if there is a mismatch in value of <envname> in begin & end commands.

Make 'cse' change <envname> even if begin/end values mismatch. Thanks!

**Comment by lervag** [comment]
Huh, this is interesting. I think I've made this too complicated. I.e., the current behaviour is to search for the **corresponding** correctly named `begin|end` pair. But the names are not really important. So, I could simplify and always just match corresponding `\begin` to `\end` commands at the right "level".

That is: in the following example, every type of surround environment feature breaks down. I think the core idea was that this example is not valid. But who cares? If it doesn't compile, then the compiler will complain. VimTeX could still just do what seems sensible.

```tex
\begin{a}
  \begin{b}
  \end{c}
\end{d}
```

I'm pushing a very small update that should fix this, and I don't think it should break anything. At least, the tests still pass. Let me know if anything breaks, and we can look at it in more detail.

**Comment by reportaman** [comment]
@lervag Everything works well after your update, thanks!

**Comment by lervag** [comment]
Great, happy to hear it :)
