### ISSUE TITLE
Expand macros in \subfile, \include

### ISSUE THREAD

**Issue by zacmar** [lervag/vimtex#1953]
Problem description:

```
$ tree
.
├── doc.tex
├── body
│   └── intro.tex
├── build
└── minimal.vim
```
doc.tex
```
\documentclass{article}

\begin{document}
\def\bodyprefix{body}
\include{\bodyprefix/intro}
\end{document}
```
minimal.vim
```
packadd! vimtex
```

`vim -u minimal.vim doc.tex` and put cursor here
```
\include{\bodyprefix/intro}
                      ^
```
and press `gf`. Response is: `E447: Can't find file "bodyprefix/intro" in path.`

**Describe the solution you'd like**
The `\bodyprefix` macro should be expanded instead of used verbatim in the go to file command. I think this is feasible, as this expansion has to be done only in `\include`, `\subfile` etc.

**Describe alternatives you've considered**
None.

**Additional context**
Specifying a path prefix using \def "on the fly" is my preferred solution for not duplicating any code. This is often useful, especially in multi-file projects.

**Comment by zacmar** [comment]
This is actually more far-reaching than i initially thought, in fact the whole multi-file support of VimTeX seemingly breaks down when having a macro in the include path.

**Comment by lervag** [comment]
> **Describe the solution you'd like**
> The `\bodyprefix` macro should be expanded instead of used verbatim in the go to file command. I think this is feasible, as this expansion has to be done only in `\include`, `\subfile` etc.

Well, I agree this would be nice. But the complexity is not to be ignored. What you are asking is for Vimtex to parse the TeX code. IMHO, this is asking quite a lot. It could be possible to allow "simple" forms, but to solve this in a general way is near impossible without implementing a full TeX engine.

> **Additional context**
> Specifying a path prefix using \def "on the fly" is my preferred solution for not duplicating any code. This is often useful, especially in multi-file projects.

Could you show by (a small) example why this is actually useful? My intuition is that you are, at best, making a very small simplification to avoid some kind of redundancy. But I'll be glad to be convinced otherwise.

> This is actually more far-reaching than i initially thought, in fact the whole multi-file support of VimTeX seemingly breaks down when having a macro in the include path.

Yes; this is not supported now.

**Comment by zacmar** [comment]
> Well, I agree this would be nice. But the complexity is not to be ignored. What you are asking is for Vimtex to parse the TeX code. IMHO, this is asking quite a lot. It could be possible to allow "simple" forms, but to solve this in a general way is near impossible without implementing a full TeX engine.
That is what I was afraid of. Although I though it _could_  still be feasible when limiting it to special occurrences, e.g. parse `\include{}` or `\subfile{}` for a backslash, and look for a `\def` or `\newcommand` in the same file.

> Could you show by (a small) example why this is actually useful? My intuition is that you are, at best, making a very small simplification to avoid some kind of redundancy. But I'll be glad to be convinced otherwise.
The use case is mostly exactly as I described. Although surely there are others: For instance, when including multiple figures (i.e. images) from some path with a common "trunk". I have a file opener implemented in my vimrc (just using `xdg-open`), and it would be kind of neat if I could just `gf` and the image is opened in my favorite image viewer.

> Yes; this is not supported now.
Thanks for the clarification.

**Comment by andymass** [comment]
Seems like one very simple way to solve this is to allow the user to give a custom hook in vimtex#include#expr for custom preprocessing (e.g., `substitute(..., '\bodyprefix', 'body', 'g')`).

**Comment by lervag** [comment]
> That is what I was afraid of. Although I though it _could_ still be feasible when limiting it to special occurrences, e.g. parse `\include{}` or `\subfile{}` for a backslash, and look for a `\def` or `\newcommand` in the same file.

I'll not claim this is impossible. In fact, implemented in a good way it could probably allow for other related and nice features. But I don't have that much time, and this doesn't really strike me as very important.

> The use case is mostly exactly as I described. Although surely there are others: For instance, when including multiple figures (i.e. images) from some path with a common "trunk". I have a file opener implemented in my vimrc (just using `xdg-open`), and it would be kind of neat if I could just `gf` and the image is opened in my favorite image viewer.

Ok, so, instead of writing

```tex
\includegraphics{/path/to/my/fancy/picture/file/a.jpg}
\includegraphics{/path/to/my/fancy/picture/file/b.jpg}
\includegraphics{/path/to/my/fancy/picture/file/c.jpg}
\includegraphics{/path/to/my/fancy/picture/file/d.jpg}
\includegraphics{/path/to/my/fancy/picture/file/e.jpg}
\includegraphics{/path/to/my/fancy/picture/file/f.jpg}
```

you write this?

```tex
\def\common{/path/to/my/fancy/picture/file}
\includegraphics{\common/a.jpg}
\includegraphics{\common/b.jpg}
\includegraphics{\common/c.jpg}
\includegraphics{\common/d.jpg}
\includegraphics{\common/e.jpg}
\includegraphics{\common/f.jpg}
```

I still don't quite see why this is useful (except for saving a few keystrokes). I really don't mean to be difficult, just to make that clear. I just want to understand what particular problem you are really solving with the added macro.

> Seems like one very simple way to solve this is to allow the user to give a custom hook in vimtex#include#expr for custom preprocessing (e.g., `substitute(..., '\bodyprefix', 'body', 'g')`).

Yes, I agree; however, I would expect this would also very quickly not fully suffice. If I were to use such a feature, it would be because I specifically want to parametrize something. In this case, it would be quite probable that two different project had a similar structure but with different values for the macro/command. And in this case, the custom hook would not work.

**Comment by zacmar** [comment]
> I'll not claim this is impossible. In fact, implemented in a good way it could probably allow for other related and nice features. But I don't have that much time, and this doesn't really strike me as very important.
Ok, I understand that this is not exactly high priority. In general, if you feel like this is not worth the hassle, feel free to close the issue.
 
> Ok, so, instead of writing
> 
> ```
> \includegraphics{/path/to/my/fancy/picture/file/a.jpg}
> \includegraphics{/path/to/my/fancy/picture/file/b.jpg}
> \includegraphics{/path/to/my/fancy/picture/file/c.jpg}
> \includegraphics{/path/to/my/fancy/picture/file/d.jpg}
> \includegraphics{/path/to/my/fancy/picture/file/e.jpg}
> \includegraphics{/path/to/my/fancy/picture/file/f.jpg}
> ```
> 
> you write this?
> 
> ```
> \def\common{/path/to/my/fancy/picture/file}
> \includegraphics{\common/a.jpg}
> \includegraphics{\common/b.jpg}
> \includegraphics{\common/c.jpg}
> \includegraphics{\common/d.jpg}
> \includegraphics{\common/e.jpg}
> \includegraphics{\common/f.jpg}
> ```
> 
> I still don't quite see why this is useful (except for saving a few keystrokes). I really don't mean to be difficult, just to make that clear. I just want to understand what particular problem you are really solving with the added macro.
Exactly, yes. I would argue that it is simply best practice to do so, as if you moved the images anywhere, you only have to change `\common`. This may be clearer like this:
```
\begin{figure}
\def\common{/path/to/my/fancy/picture/file}
\def\param{25}
\includegraphics{\common/param_\param/a.jpg}
\includegraphics{\common/param_\param/b.jpg}
\includegraphics{\common/param_\param/c.jpg}
\caption{Results for \( param = \param \).}
\end{figure}
```
Where, if I change my mind on which parameter choice i want to show, I only need to edit the `\def`. Although I understand that this example may be a bit contrived (as it also caters to my exact use case of being able to quickly glance at the .jpg when pressing `gf`). The point still stand for subfiles and the likes.

**Comment by clason** [comment]
But in this exact use case, isn't that exactly what `\graphicspath` is for?

**Comment by lervag** [comment]
> But in this exact use case, isn't that exactly what `\graphicspath` is for?

> Exactly, yes. I would argue that it is simply best practice to do so, as if you moved the images anywhere, you only have to change `\common`. This may be clearer like this: ...
>
> Where, if I change my mind on which parameter choice i want to show, I only need to edit the `\def`. Although I understand that this example may be a bit contrived (as it also caters to my exact use case of being able to quickly glance at the .jpg when pressing `gf`). The point still stand for subfiles and the likes.

As @clason says: this example seems to be a bad example as this is the point of `\graphicspath`.

I still feel that there is no good example of why/where this is useful currently on the table. This does not mean that it is not useful, of course, but it will be much more motivating to me to see an actual example of where this particular feature actually makes much sense.
