### ISSUE TITLE
How to switch between multiple engines?

### ISSUE THREAD

**Issue by SK-silver** [lervag/vimtex#1955]
I'm a beginner in vim and also not familiar with the latex environment settings either. I usually use different engines, including pLatex, upLatex and XeLaTeX. I would like to ask if vimtex supports an efficient way to switch engines. If so, I hope you can teach me! Thank you very much!

**Comment by lervag** [comment]
You'll want to read the part in the docs about TeX directives, see `:help vimtex-tex-directives`. I think that should be the key to allow switching between different compilers. Note that I think of an _engine_ as something like latexmk, arara, and textonic. XeLaTeX and pdflatex and similar are (AFAIK) better called compilers. (I've not heard about pLatex and upLatex.)
