### ISSUE TITLE
Wrong syntax highlighting for lstinline if options in brackets are used

### ISSUE THREAD

**Issue by Toromtomtom** [lervag/vimtex#1956]
When setting options for `\lstinline` with brackets, the syntax highlighting assumes that the opening bracket `[` is the delimiter for the listing code. In the following example file, the syntax highlighting is correct for the first usage of `\lstinline`. The second usage, however, sets the language for the listing with brackets, and all characters until the next `[` are highlighted as if they were part of the listing.

```latex
\documentclass{article}
\usepackage{listings}
\begin{document}

The declaration \lstinline|int x;| creates a new variable.

The declaration \lstinline[language=C]|int x;| creates a new variable.

\end{document}
```

(The Markdown highlighting here seems to have the same problem).

**Comment by lervag** [comment]
Thanks, I think this is fixed now. I tried to also add nested syntax support to these elements. Let me know what you think.

**Comment by Toromtomtom** [comment]
Excellent, thanks!
