### ISSUE TITLE
Automatically close viewers when buffers closed (mac)

### ISSUE THREAD

**Issue by ktkimit** [lervag/vimtex#1959]
Is there a way to close a viewer when the corresponding buffer is closed?

I can see in vimtex.doc there is an example to do this, but this looks like only for Linux using `xdotool`.

My OS is mac and I am using Skim for the viewer.

**Comment by lervag** [comment]
Yes, on Linux (and perhaps also BSD) with Xorg and xdotool, this is possible. At least with the MuPDF and Zathura viewers. I don't know if this is possible with Skim on macOS, though; sorry!

@clason Do you know a way to make this work on macOS?

**Comment by clason** [comment]
It's possible with AppleScript: `osascript -e 'tell app "Skim" to quit'` (similar to how it's opened in `skim.vim`).

It'd be a bit more difficult to only close the window (and the app if this is the only window).

**Comment by lervag** [comment]
So, a working example should be something like this:

So, a working example should be something like this:

```vim
augroup vimtex_events
  au!
  au User VimtexEventQuit call CloseViewers()
augroup END

" Close Skim viewer when VimTeX buffers are closed
function! CloseViewers()
  if exists('b:vimtex.viewer')
    call system('osascript -e ''tell app "Skim" to quit''')
  endif
endfunction
```

**Comment by ktkimit** [comment]
It work, thank you, @lervag and @clason !

**Comment by lervag** [comment]
Happy to hear it :)
