### ISSUE TITLE
vimtex-compiler-ss does not open quickfix

### ISSUE THREAD

**Issue by rudrab** [lervag/vimtex#1962]
Hi,

Due to my muscle memory (aquired from vim-latex and other code compilation, so `<F10>` is universal compiler for me), I prefer singleshot calculation. I do have given a shot to `\ll` and then just save to compile, but unfortunate my muscle memory rejects that.

So, I have created this map:

```vim
autocmd Filetype tex imap <buffer> <f10> <Esc>:w<CR> <plug>(vimtex-compile-ss)<CR><Esc>
```

Unfortunately, this does not open quickfix as `\ll` does.

Is it possible to open quickfix when there is some error using this map?

I have also tried

```vim
autocmd Filetype tex imap <buffer> <f10> <Esc>:w<CR> :VimtexCompileSS<CR><Esc>
```

**Comment by lervag** [comment]
> So, I have created this map:
>
> ```viml
> autocmd Filetype tex imap <buffer> <f10> <Esc>:w<CR> <plug>(vimtex-compile-ss)<CR><Esc>
> ```

This seems to work for me:

```viml
autocmd Filetype tex imap <buffer> <f10> <esc>:w<cr><plug>(vimtex-compile-ss)
```

> I have also tried
>
> ```viml
> autocmd Filetype tex imap <buffer> <f10> <Esc>:w<CR> :VimtexCompileSS<CR><Esc>
> ```

That mapping works as expected on my end. Note that you should remove the
space, i.e.:

```viml
autocmd Filetype tex imap <buffer> <f10> <esc>:w<cr>:VimtexCompileSS<cr><esc>
```

> Unfortunately, this does not open quickfix as `\ll` does.
>
> Is it possible to open quickfix when there is some error using this map?

The quickfix opens as expected on my end. Can you give some more details? What's your VimTeX config? Are you on Vim or neovim; which version?

**Comment by rudrab** [comment]
Dear @lervag, 
Thanks for your comment. Please allow me to put my complete `.vimrc` for you to have a look. Kindly have a check if you find some time.  The `vimtex` syntax is around the bottom of the `vimrc`.
https://drive.google.com/file/d/160ItwbFdTdr8az7O9NGu6gebEnYauwcl/view?usp=sharing

**Comment by j1-lee** [comment]
How about removing the following (line 440 in your vimrc): `\   '-pvc',`?

**Comment by lervag** [comment]
Yes, @j1-lee is quite right: you should __not__ use `-pvc` in the latexmk options. This is added automatically if you need it.

Btw, note that you don't need `, {'for': 'tex'}` when you load VimTeX, because VimTeX is properly implemented as a filetype plugin.

I also strongly suggest that you use a linter to help make your vimrc more readable. I find [vint](https://github.com/Vimjas/vint) works well.

**Comment by lervag** [comment]
> Yes, @j1-lee is quite right: you should **not** use `-pvc` in the latexmk options. This is added automatically if you need it.

To be more clear: VimTeX has the option `g:vimtex_compiler_latexmk.continuous` which is used to toggle the `-pvc` option. If you add `-pvc` to the `.options` list, then you will force VimTeX to always start latexmk in continuous mode, which breaks the single shot feature.

**Comment by rudrab** [comment]
oops...`pvc` was there by mistake. changes and its working.

**Comment by lervag** [comment]
Great, I'll close this issue then :)
