### ISSUE TITLE
Issue with forward search using Zathura

### ISSUE THREAD

**Issue by niloysh** [lervag/vimtex#1963]
**Issue**
I can't seem to get forward search working with Zathura. Concretely, `\lv` from the `.tex` file does not move to the corresponding line in the pdf. I have tried `:VimtexView` in case there was an issue with the keybindings.

Vimtex compiles fine. I can see the generated pdf in Zathura (0.3.8). Backward search works fine. If I do `ctrl+left click` on the pdf, the cursor moves to the corresponding line in the .tex file. I have xdotool installed (version 3.20160805.1).

**~/.vimrc**
```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_view_method = 'zathura'
let g:tex_flavor = "latex"
filetype plugin indent on

if empty(v:servername) && exists('*remote_startserver')
call remote_startserver('VIM')
endif

"Compile with latexmk with shell escape
"to use the minted package
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-pdf',
    \   '-shell-escape',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}
```

**minimal.tex**
```tex
\documentclass{article}
\begin{document}
\section{First}
This is the first section. It contains some dummy text.
\section{Second}
This section contains some more text.
\end{document}
```

**.latexmkrc**
```
$pdf_mode = 1;
$pdflatex = 'pdflatex --shell-escape -synctex=1 -interaction=nonstopmode %O %S';
```

**Commands/Input**
`\lv` or `:VimtexView` 

**Observed Behaviour**
Zathura does not move to the corresponding line in the pdf.

However, if I copy the command `zathura --synctex-forward 6:1:'minimal.tex' 'minimal.pdf'` from `:VimtexInfo` and paste it in the terminal, a new instance of Zathura is launched, with the corresponding line highlighted.

On the other hand, if I change the pdf viewer to mupdf, then forward search works but not backward search. I would like Zathura to work, because it highlights the line.

**Output from VimtexInfo**
```
System info
  OS: Ubuntu 18.04.5 LTS
  Vim version: VIM 8.2 (1-2311)
  Has clientserver: true
  Servername: VIM

VimTeX project: minimal
  base: minimal.tex
  root: /mnt/c/Users/Niloy/Documents/workspace/test
  tex: /mnt/c/Users/Niloy/Documents/workspace/test/minimal.tex
  out: /mnt/c/Users/Niloy/Documents/workspace/test/minimal.pdf
  log: /mnt/c/Users/Niloy/Documents/workspace/test/minimal.log
  aux: /mnt/c/Users/Niloy/Documents/workspace/test/minimal.aux
  fls: /mnt/c/Users/Niloy/Documents/workspace/test/minimal.fls
  main parser: current file verified
  compiler: latexmk
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -pdf
        -shell-escape
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: process 1957 run
    pid: 1957
    cmd: max_print_line=2000 latexmk -pdf -shell-escape -verbose -file-line-error -synctex=1 -interaction=nonstopmode
  viewer: Zathura
    xwin id: 2621443
    cmd_forward_search: zathura --synctex-forward 6:1:'minimal.tex' 'minimal.pdf'
  qf: LaTeX logfile
    root: /mnt/c/Users/Niloy/Documents/workspace/test
    addqflist: 59
    errorformat_saved:
    fix_paths: 60
    main: /mnt/c/Users/Niloy/Documents/workspace/test/minimal.tex
    set_errorformat: 58
  document class: article
```
**Output of VimtexCompileOutput**
```
Latexmk: This is Latexmk, John Collins, 1 January 2015, version: 4.41.
Viewing pdf
Latexmk: I have not found a previewer that is already running.
   So I will start it for 'minimal.pdf'
------------
Latexmk: All targets (minimal.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
vimtex_compiler_callback_success
------------
Running 'start zathura  -x "/usr/bin/vim.gtk3 --servername VIM --remote +%{line} %{input}" "minimal.pdf"'
------------
------------
Running 'echo vimtex_compiler_callback_success'
------------
```

**Other Info**
I am using Ubuntu on Windows Subsystem for Linux (WSL), but I have x11 forwarding enabled.

Thanks for the amazing work on this plugin, any help regarding this issue is appreciated.

**Comment by lervag** [comment]
First, a couple of minor comments:

* You should not add `-pdf` to the latexmk options. The backend (pdflatex, lualatex, etc) is chosen based on other things, e.g. `g:vimtex_compiler_latexmk_engines`.
* You don't need to specify `g:tex_flavor` in VimTeX v2.0 and later.

Now, you say backward search works well. But when does it work? I mean: How did you open Zathura in the first place?

Does `\lv` open Zathura at all? If it opens Zathura, does backward search work directly now?

> Thanks for the amazing work on this plugin

Thanks for the kind words :)

**Comment by niloysh** [comment]
> * You should not add `-pdf` to the latexmk options. The backend (pdflatex, lualatex, etc) is chosen based on other things, e.g. `g:vimtex_compiler_latexmk_engines`.
> * You don't need to specify `g:tex_flavor` in VimTeX v2.0 and later.

Removing these worked!

> Does `\lv` open Zathura at all? If it opens Zathura, does backward search work directly now?

Yes, it works perfectly now. Both forward and backward search.
Thanks for a lot for your help!

**Comment by lervag** [comment]
> > * You should not add `-pdf` to the latexmk options. The backend (pdflatex, lualatex, etc) is chosen based on other things, e.g. `g:vimtex_compiler_latexmk_engines`.
> > * You don't need to specify `g:tex_flavor` in VimTeX v2.0 and later.
> 
> Removing these worked!

Ah, great. Then it was the `-pdf` option that made the difference.

> Yes, it works perfectly now. Both forward and backward search.
> Thanks for a lot for your help!

Happy to hear it!

**Comment by horror-vacui** [comment]
I think this info (-pdf is not needed) should be referenced somehow in the vimtex help. The forward/backward search part is concise, and I've just spent some good amount of time to hunt for any information, which could tell me, why the searches does not work any more.

Vimtex is still amazing! Keep up the nice work!

**Comment by lervag** [comment]
> I think this info (-pdf is not needed) should be referenced somehow in the vimtex help.

Ok, I'll push an update. Let me know what you think and please feel free to suggest improvements!

> The forward/backward search part is concise, and I've just spent some good amount of time to hunt for any information, which could tell me, why the searches does not work any more.

But I understand this means you also were able to figure it out?

> Vimtex is still amazing! Keep up the nice work!

Thanks! :)
