### ISSUE TITLE
[suggestion] Setting up nvr for neovim on Windows

### ISSUE THREAD

**Issue by jdhao** [lervag/vimtex#1964]
Documentation [here](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L4852) on setting up inverse search for Neovim is a bit ambiguous.

> 2. Configure your viewer to use `nvr --remote +"%line" "%file"` for backward sync.

The way to specify currently-clicked line in PDF document and correspond LaTeX source varies for different PDF viewers. The above config is only valid for Skim on macOS.  For Sumatra PDF on Windows, we need to use command of the form: `nvr --servername server_address +"%l" "%f"`, where `%l` is the current line and `%f` represents the LaTeX source file.

Ref:

+ https://www.sumatrapdfreader.org/docs/Use-Sumatra-as-a-pre-viewer-for-LaTeX-editors.html
+ https://tex.stackexchange.com/questions/52170/sumatrapdf-inverse-search
+ https://tex.stackexchange.com/questions/194645/jump-to-the-last-line-of-pdf-when-compiling-text-in-sublime-text

**Comment by jdhao** [comment]
Below I will write how I set up inverse search for Sumatra PDF on Windows.

1. Install [neovim-remote](https://github.com/mhinz/neovim-remote): `pip install neovim-remote`
2. Add the following config to neovim config:

    ```vim
    function! SetServerName()
        if has('win32')
            let nvim_server_file = $TEMP . "/curnvimserver.txt"
            let cmd = "echo " . v:servername . " >" . nvim_server_file
        else
            let cmd = 'echo ' . v:servername . ' > /tmp/curnvimserver'
        endif
        call system(cmd)
    endfunction
    augroup vimtex_common
        autocmd!
        autocmd FileType tex call SetServerName()
    augroup END
    ```
3. Set up Sumatra PDF. Open Sumatra PDF, go to Settings --> Options, in the bottom part, there is a section Set inverse search command-line, put the following command there:

    ```
    cmd /c for /F %i in ('type C:\Users\ADMINI~1\AppData\Local\Temp\curnvimserver.txt') do nvr --servername %i -c "normal! zzzv" +"%l" "%f"
    ```
    Note that you may need to change the exact file path for your Windows system, you can use command `:echo $TEMP` to check the temp folder on your Windows.

The above settings work well for me on Windows with Sumatra PDF viewer. Once it is set up, no manual labor is needed.

**Comment by lervag** [comment]
Thanks! I'll update the docs accordingly. I assume [this blogpost](https://jdhao.github.io/2021/02/20/inverse_search_setup_neovim_vimtex/) is also directly relevant? Perhaps I could add a reference to it? Also, I think it could be convenient with a backlink from your blogpost to this issue?

**Comment by jdhao** [comment]
yes, that post is the up to date version for inverse search, it also involves less manual labor.
I will update the post with a link to this issue in the hope that future reader can find it easily.

**Comment by lervag** [comment]
I've updated the docs; please let me know if you think I missed something or if you think I should write something different.

**Comment by jdhao** [comment]
The help doc looks fine to me 👍

**Comment by Th3Tr00p3r** [comment]
I just tried it today and for some reason this doesn't work for me. I believe I did everything as you described.

The curnvimserver.txt file is generated just fine, and when I double click in SumatraPDF (after compiling a newly opened .tex file in neovim-qt, opened from administrator powershell on windows) I see some program (which I assume is the cmd) quickly open and close in the windows task bar, but nothing else happens.

Anything I can obviously check?

Thanks!

**Comment by lervag** [comment]
I'm sorry, but I can't help here. Perhaps, hopefully, @jdhao may be able to assist?

**Comment by Th3Tr00p3r** [comment]
I just solved it. Basically I tried to satisfy the vimtex section in :healthcheck and that led me to solving the issue:

1) Added these to my vimtex augroup:
:au FileType tex let g:vimtex_view_general_viewer = 'SumatraPDF'
:au FileType tex let g:vimtex_compiler_progname = 'nvr'

2) Added SumatraPDF folder to system path

3) Using a fresh powershell window, I activated python virtualenv containing 'nvr', and then launched nvim-qt.

Hope this helps someone!

**Comment by lervag** [comment]
Thanks! One minor comment: You don't need to put the options under autocmds; i.e., in your config (`init.vim` for neovim or `vimrc` for vim) use simply:

```
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_compiler_progname = 'nvr'
```
