### ISSUE TITLE
backward search on mac osx

### ISSUE THREAD

**Issue by knsamsdesk** [lervag/vimtex#1967]
I thought I should create a new issue at least as it relates to backward search using skim.

Here is where I am:
1. Using the default setting for macvim does make the inverse search work.
2. My `vim --version` tells me client-server functionality is available. So it's a bit of a mystery why the same commands on skim as for macvim but with vim instead does not work.

I'd be happy to provide more information that you might need to help me with this! Looking forward to hearing from you!

Thank you in advance!

=========

Hello @lervag! Enjoying the plug-in so far but I have a couple of questions!

(1) Is there a way to make the default engine `xelatex` instead of having this be the first line in every `.tex` file I write?

(2) How do I get forward search to work? For eg., I am not even sure if I am executing right keystrokes to get forward search. So if you could tell me what the command is, I could try again! (I swear I searched all over; I got "option+s" but that does not take me to the correct line in the pdf.

(3) Re backward search, I read the documentation for skim and followed it but I still could not get it to work.

Thank you for all your help!

**Comment by lervag** [comment]
> I thought I should create a new issue

Yes, that is easier for me to relate to :) (I took the liberty of removing your comment in the other issue, as I think things are self contained here.)

> Here is where I am: ...

Ok, so: Inverse search with VimTeX+Skim are working for you in MacVim, but not with Vim on macOS with the same vimrc file? Or did I misunderstand?

> I'd be happy to provide more information that you might need to help me with this!

It would be very useful to see a vimrc file. Or, even much better, a minimal example as explained in the [issue template](https://github.com/lervag/vimtex/blob/master/.github/ISSUE_TEMPLATE/issue_report.md).

> (1) Is there a way to make the default engine `xelatex` instead of having this be the first line in every `.tex` file I write?

Yes:

```vim
let g:vimtex_compiler_latexmk_engines = {
    \ '_'                : '-xelatex',
    \}
```

See `:help g:vimtex_compiler_latexmk_engines` (note the last line in the following excerpt):

```
*g:vimtex_compiler_latexmk_engines*
  Defines a map between TeX program directive (|vimtex-tex-program|) and
  compiler engine. This is used by |vimtex-latexmk| to define the LaTeX
  program. The `_` key defines the default engine.

  ...
```

> (2) How do I get forward search to work? For eg., I am not even sure if I am executing right keystrokes to get forward search. So if you could tell me what the command is, I could try again! (I swear I searched all over; I got "option+s" but that does not take me to the correct line in the pdf.

I'm not quite sure what you are asking here. The default keymap is `<localleader>lv` (which both opens the viewer and does forward search). If you did not change your localleader, then this means `\lv`. You can also use the ex command `:VimtexView`.

> (3) Re backward search, I read the documentation for skim and followed it but I still could not get it to work.

Based on the first things you write it seems you get it to work with MacVim, but not with Vim?

Please note, @jdhao just made me aware of some useful blog posts that may be of help:

* https://jdhao.github.io/2021/02/20/inverse_search_setup_neovim_vimtex/
* https://jdhao.github.io/2019/03/26/nvim_latex_write_preview/#inverse-search-for-sumatra-pdf-on-windows

The latter is not directly relevant, but it might be interesting if you are new to Vim and/or VimTeX.

> Thank you for all your help!

I hope it helps!

**Comment by knsamsdesk** [comment]
> > I thought I should create a new issue
> 
> Yes, that is easier for me to relate to :) (I took the liberty of removing your comment in the other issue, as I think things are self contained here.)
> 
> > Here is where I am: ...
> 
> Ok, so: Inverse search with VimTeX+Skim are working for you in MacVim, but not with Vim on macOS with the same vimrc file? Or did I misunderstand?

I think that is right; though, it's not the Vim that ships with macOS --- it is the one installed by HomeBrew when I install macvim and is available from the terminal by simply "vim." 

```
myusername@LocalMac ~ % vim --version 
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 28 2020 07:15:57)
macOS version
Included patches: 1-2164
Compiled by Homebrew
Huge version with MacVim GUI.  Features included (+) or not (-):
+acl               +file_in_path      -mouse_sysmouse    -tag_old_static
+arabic            +find_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +float             +mouse_xterm       +tcl
+autochdir         +folding           +multi_byte        +termguicolors
-autoservername    -footer            +multi_lang        +terminal
+balloon_eval      +fork()            -mzscheme          +terminfo
+balloon_eval_term +fullscreen        +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +odbeditor         +textprop
+byte_offset       +iconv             +packages          +timers
+channel           +insert_expand     +path_extra        +title
+cindent           +ipv6              +perl              +toolbar
+clientserver      +job               +persistent_undo   +transparency
+clipboard         +jumplist          +popupwin          +user_commands
+cmdline_compl     +keymap            +postscript        +vartabs
+cmdline_hist      +lambda            +printer           +vertsplit
+cmdline_info      +langmap           +profile           +virtualedit
+comments          +libcall           -python            +visual
+conceal           +linebreak         +python3           +visualextra
+cryptv            +lispindent        +quickfix          +viminfo
+cscope            +listcmds          +reltime           +vreplace
+cursorbind        +localmap          +rightleft         +wildignore
+cursorshape       +lua               +ruby              +wildmenu
+dialog_con_gui    +menu              +scrollbind        +windows
+diff              +mksession         +signs             +writebackup
+digraphs          +modify_fname      +smartindent       -X11
+dnd               +mouse             -sound             -xfontset
-ebcdic            +mouseshape        +spell             +xim
+emacs_tags        +mouse_dec         +startuptime       -xpm
+eval              -mouse_gpm         +statusline        -xsmp
+ex_extra          -mouse_jsbterm     -sun_workshop      -xterm_clipboard
+extra_search      +mouse_netterm     +syntax            -xterm_save
-farsi             +mouse_sgr         +tag_binary        
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/Applications/MacVim.app/Contents/Resources/vim"
Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_MACVIM -Wall -Wno-unknown-pragmas -pipe  -DMACOS_X -DMACOS_X_DARWIN  -fdeclspec -arch arm64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: clang   -L. -fstack-protector-strong -L/opt/homebrew/lib -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/opt/readline/lib -L. -fstack-protector-strong -L/opt/homebrew/lib -L/opt/homebrew/opt/libyaml/lib -L/opt/homebrew/opt/openssl@1.1/lib -L/opt/homebrew/opt/readline/lib  -arch arm64 -L/opt/homebrew/lib -o Vim        -lm  -lncurses -liconv /opt/homebrew/lib/libintl.a -framework AppKit  -L/opt/homebrew/opt/lua/lib -llua5.4 -fstack-protector-strong  -L/System/Library/Perl/5.28/darwin-thread-multi-2level/CORE -lperl  -L/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -framework CoreFoundation -F/System/Library/Frameworks -framework Tcl -framework CoreFoundation -lruby.3.0  -L/opt/homebrew/Cellar/ruby/3.0.0/lib    
```

> > I'd be happy to provide more information that you might need to help me with this!
> 
> It would be very useful to see a vimrc file. Or, even much better, a minimal example as explained in the [issue template](https://github.com/lervag/vimtex/blob/master/.github/ISSUE_TEMPLATE/issue_report.md).

Let me make a separate response as this is getting a bit long! 
> > (1) Is there a way to make the default engine `xelatex` instead of having this be the first line in every `.tex` file I write?
> 
> Yes:
> 
> ```viml
> let g:vimtex_compiler_latexmk_engines = {
>     \ '_'                : '-xelatex',
>     \}
> ```
> 
> See `:help g:vimtex_compiler_latexmk_engines` (note the last line in the following excerpt):
>
> ```
> *g:vimtex_compiler_latexmk_engines*
>   Defines a map between TeX program directive (|vimtex-tex-program|) and
>   compiler engine. This is used by |vimtex-latexmk| to define the LaTeX
>   program. The `_` key defines the default engine.
> 
>   ...
> ```

Thank you! This works, I tried the following and it didn't work: 

```
let g:vimtex_compiler_latexmk = { 
         \ 'executable' : 'latexmk',
         \ 'options' : [ 
         \   '-xelatex',
         \   '-file-line-error',
         \   '-synctex=1',
         \   '-interaction=nonstopmode',
         \ ],
         \}
```

> > (2) How do I get forward search to work? For eg., I am not even sure if I am executing right keystrokes to get forward search. So if you could tell me what the command is, I could try again! (I swear I searched all over; I got "option+s" but that does not take me to the correct line in the pdf.
> 
> I'm not quite sure what you are asking here. The default keymap is `<localleader>lv` (which both opens the viewer and does forward search). If you did not change your localleader, then this means `\lv`. You can also use the ex command `:VimtexView`.
> 

Hah, thanks, I don't know but I must have been confused about something. 

> > (3) Re backward search, I read the documentation for skim and followed it but I still could not get it to work.
> 
> Based on the first things you write it seems you get it to work with MacVim, but not with Vim?
> 
> Please note, @jdhao just made me aware of some useful blog posts that may be of help:
> 
>     * https://jdhao.github.io/2021/02/20/inverse_search_setup_neovim_vimtex/
> 
>     * https://jdhao.github.io/2019/03/26/nvim_latex_write_preview/#inverse-search-for-sumatra-pdf-on-windows
> 
> 
> The latter is not directly relevant, but it might be interesting if you are new to Vim and/or VimTeX.
> 

Both the links seem to help when --remote is not an option in your vim install. But my vim has the option --remote and notice that clientserver is enabled in my compilation. 

> > Thank you for all your help!
> 
> I hope it helps!

**Comment by lervag** [comment]
> > > I'd be happy to provide more information that you might need to help me with this!
> > 
> > 
> > It would be very useful to see a vimrc file. Or, even much better, a minimal example as explained in the [issue template](https://github.com/lervag/vimtex/blob/master/.github/ISSUE_TEMPLATE/issue_report.md).
> 
> Let me make a separate response as this is getting a bit long!

Ok. Not quite sure what you mean - a new issue?

> Thank you! This works, I tried the following and it didn't work:
> 
> ```
> let g:vimtex_compiler_latexmk = { 
>          \ 'executable' : 'latexmk',
>          \ 'options' : [ 
>          \   '-xelatex',
>          \   '-file-line-error',
>          \   '-synctex=1',
>          \   '-interaction=nonstopmode',
>          \ ],
>          \}
> ```

No, that won't work. Don't set the `executable` option, there should be no need for that. Also, the `options` is intended for more "general" options. I propose to leave it at the defaults, unless you need something specific.

> Both the links seem to help when --remote is not an option in your vim install. But my vim has the option --remote and notice that clientserver is enabled in my compilation.

Ok. I'm a little bit confused now as to what specifically is not working for you. Can we try to keep each issue focussed on a single thing? It is better to open multiple issues if you have different problems.

**Comment by knsamsdesk** [comment]
At the moment, the only outstanding issue is getting inverse search to work with skim. I wanted to post my .vimrc but my response was getting long especially as I was responding inline. 

Finally, to the links you suggested, I was writing to say that the links did not quite help because they're trying to solve an altogether different problem. They are assuming I think that `--remote` is not a flag that vim installation accepts.

**Comment by lervag** [comment]
> At the moment, the only outstanding issue is getting inverse search to work with skim. I wanted to post my .vimrc but my response was getting long especially as I was responding inline. I think it might be better to close this so I can start a new issue that is devoted to this problem.

Sounds good.

> Finally, to the links you suggested, I was writing to say that the links did not quite help because they're trying to solve an altogether different problem. They are assuming I think that `--remote` is not a flag that vim installation accepts.

Ah, ok, I see.
