### ISSUE TITLE
Vimtex changes movement commands

### ISSUE THREAD

**Issue by Christopher-Bradshaw** [lervag/vimtex#1969]
Intermittently when working in tex files, I find that movement commands (`w`, `e`, `b`, etc) are acting like their capitalized versions (`W`, `E`, `B`, etc). I have no idea what causes this (on opening a new file things behave as expected), but it is fixed by `:VimtexReload`. This + the fact that it only happens in tex files, even if I have other file types open in other tabs makes me think it is caused by this plugin. 

I hope this is a known feature that I am just triggering accidentally, but I can't find any info in the documentation.
If this is not known, I can provide more debug info.

Thanks for the plugin!

**Comment by lervag** [comment]
No, this must be some kind of bug. I remember seeing a similar issue before, and then it was found to be a bug with neovim. See #1595. Can you check if this issue is related?

**Comment by Christopher-Bradshaw** [comment]
Hey lervag, thanks for the response.

Reading through that bug it sounds like exactly the same thing (I am using neovim v0.4.4). Feel free to close this, I'll follow up in the other issue if I have more info, but it sounds like the bug is deep in the weeds of neovim/vim compatibility so I'll probably just `:VimtexReload` when the issue crops up.

**Comment by lervag** [comment]
Good; I think the issue was solved on newer neovim versions - perhaps you could update?
