### ISSUE TITLE
Minor glitch with the quickfix windows

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#197]
Using latest `vimtex` (commit 892ad491326519092d97f6426fe67a1b0b45dfd2) with gvim, in a gnome-shell environment, with focus-follow-mouse mode (yep, I'm so old...). Using `latexmk` in continuous mode.

If there is an error, the quickfix windows appears. Then if I correct the error, and do an ":update" , the project is recompiled, I have a "success" in the status line, but the quickfix window does not disappear until something (anything) happens: the gvim window lose or gain focus, I move the cursor, or type something. 

It's not a problem at all, but I though to comment it here; the first time (until you notice that simply unfocus and refocus the windows) it's a bit strange. 

Thanks!

**Comment by lervag** [comment]
Interesting. This does not occur with me. Does this always happen, even on a minimal example such as:
```tex
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

That is, if you start `latexmk`, then insert an error, e.g. append `\ttteeesssttt` after `Hello world!` and do `:update` -> the quickfix window appears. Now remove the bad command and repeat the update: Does the quickfix window disappear immediately now?

If not: Could you try again with a minimal vimrc file, e.g.
```vimL
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
filetype plugin indent on
syntax enable
```
Note that `~/.vim/bundle/vimtex,` should of course be modified to the path to `vimtex` on your setup. You can run `vim` with the minimal rc file with `gvim -u minivimrc path/to/mwe.tex`.

**Comment by Rmano** [comment]
I tested it .... with the minimal rc and I still have the glitch. 
Look at the pause after the second `:update`: the quickfix windows stays put and I have a "success" in the bottom line. As soon as I move the cursor (or unfocus the window) the quickfix window disappears. 

![recorded](https://cloud.githubusercontent.com/assets/6414907/8566354/cd0a0e2e-255d-11e5-9d13-d0ca5480336e.gif)

**Comment by lervag** [comment]
Yes, I see. As I said, this does not happen with me. I do have one possible solution, though. It would be interesting to see if it works on your end first:

1. Make sure you are using the latest version of vimtex (this ensures that my code references will be correct).
2. Edit `bundles/vimtex/autoload/vimtex/latexmk.vim`.
3. Go to line 88, which should be the first line in `vimtex#latexmk#callback`.
4. Add a new line below the first line: "redraw!"

This should ensure that vim is refreshed and the quickfix window should now disappear. Could you test it? If it works, then I will test it on my end and ensure that it does not break anything else, and then push an update.

**Comment by Rmano** [comment]
OK --- So I made this change:

```
diff --git a/autoload/vimtex/latexmk.vim b/autoload/vimtex/latexmk.vim
index ed04f30..05a113a 100644
--- a/autoload/vimtex/latexmk.vim
+++ b/autoload/vimtex/latexmk.vim
@@ -86,6 +86,7 @@ endfunction
 
 function! vimtex#latexmk#callback(status) " {{{1
   call vimtex#latexmk#errors_open(0)
+  redraw!
 
   if g:vimtex_view_enabled
         \ && has_key(b:vimtex.viewer, 'latexmk_callback')
```

and it works, the glitch is gone. Thanks!

**Comment by lervag** [comment]
Great! I've pushed an update that should fix the problem. I ended up moving a `redraw!` inside the quickfix function (see the commit for the details). It should have the same effect.

**Comment by Rmano** [comment]
Updated and tested: unfortunately, it seems it does not work. Still the old behavior.... can't understand why. Will check more tomorrow when I have a bit of time.

**Comment by lervag** [comment]
Sorry, my mistake. I've used my first idea for the fix, which I think might make sense anyway. That is, I think the redraw might be necessary because the function is called through a callback.

**Comment by Rmano** [comment]
Now it's ok! Thanks a lot!

**Comment by lervag** [comment]
No problem! :)
