### ISSUE TITLE
Conceal support for custom commands/macros

### ISSUE THREAD

**Issue by patricknraanes** [lervag/vimtex#1972]
**Is your feature request related to a problem? Please describe it.**
#1968 discusses conceal support

**Describe the solution you'd like**
I would like to be able to extend the conceal support to custom commands/macros that I define. As mentioned in the other issue, suppose I have these macros

```tex
\newcommand{\mat}[1]{{\mathbf{{#1}}}}
\newcommand{\vect}[1]{{\bm{#1}}}
```

Then in the text I might write
```tex
$ \mat{A} \vect{x} = \vect{b}$
```
The advantage of this system is that I can easily change the text styles for vectors and matrices. It'd be cool if conceal could work for the `\mat` and `\vect` commands, somehow, so that they conceal as **A x** = **b**

**Describe alternatives you've considered**
@lervag suggested allowing for options like

```vim
let g:vimtex_syntax_custom_cmds = {
      \ 'bold': ['mat', 'vect'],
      \ 'italic': ['todo'],
      \ 'hide': ['footnote'],
      \}
```

That would be great. I do not think something more dynamic (that automatically picks up the macro definitions) is needed.

**Comment by lervag** [comment]
Just to be clear: I assume you want `\mat{x}` to look exactly the same as `\vect{x}`, right (simply bold fonted)?

**Comment by patricknraanes** [comment]
Here's what text-conceal yields:
<img width="284" alt="conceal2" src="https://user-images.githubusercontent.com/7222967/109548575-1ab6bd00-7acd-11eb-8090-a69806910f69.png">

Regardless, I would say, yes, I would chose to set both `mat` and `vect` to bold. Assuming I could chose to do so, I would also use italics for plain. Maybe coloring could be considered as well among the options, but that is less necessary.

**Comment by lervag** [comment]
> Here's what text-conceal yields:

I don't know what "text-conceal" is, sorry...

> Assuming I could chose to do so, I would also use italics for plain.

What do you mean?

> Maybe coloring could be considered as well among the options, but that is less necessary.

I'm sorry, but that's too hard; in this case, it would be much easier for you to simply learn how to write these syntax rules yourself.

As you might have seen, the amount of issues has been stacking up lately. I'm trying to keep it down, but I don't have so much time. So, I can't promise this is delivered very soon, but I'll get to it probably within the month. Perhaps. :)

**Comment by patricknraanes** [comment]
Sorry, it seams I was a bit too tired last night. My bad. I mean
- `KeitaNakamura/tex-conceal.vim`
- When there is no (custom or standard [e.g. `mathbf`]) macro surrounding my math symbols, I'd prefer that they be italicized. However, I realise now that is off-topic, since this is about custom commands.
- Yeah, I really don't know if the color highlighting would be a good idea, so nevermind. I was just throwing it out there, since I noticed it with tex-conceal.

Anything you can do is much appreciated, but I totally understand that you have limited time!

**Comment by lervag** [comment]
> Sorry, it seams I was a bit too tired last night. My bad. I mean
>
> * `KeitaNakamura/tex-conceal.vim`

Ah, ok. From your example, it looks like `\mathsf{A}` can look like two different things (one blue, one gray)? That's strange?

> * When there is no (custom or standard [e.g. `mathbf`]) macro surrounding my math symbols, I'd prefer that they be italicized. However, I realise now that is off-topic, since this is about custom commands.

Ok! :)

> * Yeah, I really don't know if the color highlighting would be a good idea, so nevermind. I was just throwing it out there, since I noticed it with tex-conceal.

Yes, no problem. The different colors are due to the items having different highlight groups. I understand it may be hard to understand the syntax engine, but let's just say my previous comment holds :)

But ok, the conclusion is to add an option similar to what I proposed earlier that allows to add custom conceals to simple commands (i.e. `\mycommand{single argument}`). I think I'll allow to differentiate between math mode and text mode as well, so I'll have to think some more on what would be a proper implementation. Perhaps this is better:

```vim
let g:vimtex_syntax_conceal_custom = {
      \ 'mat': {'style': 'bold', 'mode': 'math'},
      \ 'vect': {'style': 'italbold', 'mode': 'math'},
      \ 'footnote': {'style': 'ital', 'mode': 'text'},
      \ 'mathtext': {'style': 'none', 'mode': 'mathtext'},
      \}
```

I.e., we can specify both the style and the mode with a dictionary.

**Comment by patricknraanes** [comment]
> From your example, it looks like `\mathsf{A}` can look like two different things (one blue, one gray)

My bad again. The second one was `%pmb`

Yes, the suggested configuration methods and options would be very nice.

**Comment by lervag** [comment]
I've added an initial version of this. See the docs `:help g:vimtex_syntax_custom_cmds` and test it. I'll be glad to get some feedback.

**Comment by elu00** [comment]
Thanks so much for this feature!
Would it be possible to add something similar for macros -> unicode symbols, e.g. `\R -> ℝ, \E -> 𝔼, \P -> ℙ`, etc?

**Comment by lervag** [comment]
Your wish is hereby granted. See the docs for an example configuration.

**Comment by patricknraanes** [comment]
I haven't had much time to test yet, but it seems to be pretty great! Many thanks!

I don't suppose `underline` could be added as one of the `argstyle` options?

If any body is looking for configuration examples, here's what I have so far. REMEMBER: these are adapted for my custom latex commands, and won't have any effect unless you have similar `\newcommand`s in your docs:

```vim
let g:vimtex_syntax_custom_cmds = [
      \ {'name': 'vect', 'mathmode': 1, 'argstyle': 'bold', 'conceal': 1},
      \ {'name': 'mat' , 'mathmode': 1, 'argstyle': 'bold', 'conceal': 1},
      \ {'name': 'bm'  , 'mathmode': 1, 'argstyle': 'bold', 'conceal': 1},
      \ {'name': 'pmb' , 'mathmode': 1, 'argstyle': 'bold', 'conceal': 1},
      "\ Unicode:,
      \ {'name': 'Prob'    , 'mathmode': 1, 'concealchar': 'ℙ'},
      \ {'name': 'Expect'  , 'mathmode': 1, 'concealchar': '𝔼'},
      \ {'name': 'Var'     , 'mathmode': 1, 'concealchar': '𝕍'},
      \ {'name': 'pdf'     , 'mathmode': 1, 'concealchar': '𝕡'},
      \ {'name': 'qdf'     , 'mathmode': 1, 'concealchar': '𝕢'},
      \ {'name': 'NormDist', 'mathmode': 1, 'concealchar': '𝒩'},
      \ {'name': 'Reals'   , 'mathmode': 1, 'concealchar': 'ℝ'},
      \ {'name': 'Imags'   , 'mathmode': 1, 'concealchar': '𝕀'},
      \ {'name': 'Naturals', 'mathmode': 1, 'concealchar': 'ℕ'},
      \ {'name': 'Integers', 'mathmode': 1, 'concealchar': 'ℤ'},
      \ {'name': 'ones'    , 'mathmode': 1, 'concealchar': '𝟙'},
      \ {'name': 'bigO'    , 'mathmode': 1, 'concealchar': '𝒪'},
      \]
```

**Comment by patricknraanes** [comment]
Btw, @lervag , is there any way to link commands to your unicode character sets? Such that `\mathds` displays/conceals like `\mathbb`, for example.

Another minor remark: shouldn't `\;` and `\,` conceal like `quad`? For ex: I have this configured:
```vim
autocmd BufEnter *.tex syntax match texMathSymbol "\\," contained conceal cchar= 
autocmd BufEnter *.tex syntax match texMathSymbol "\\;" contained conceal cchar= 
``` 
(note: there's a space the line endings)

**Comment by lervag** [comment]
> I haven't had much time to test yet, but it seems to be pretty great! Many thanks!

Happy you like it!

> I don't suppose `underline` could be added as one of the `argstyle` options?

Everything is possible. Do you think it should be possible to combine? I.e.: `bold, underline`, `bold, ital, underline`, etc?

> Btw, @lervag , is there any way to link commands to your unicode character sets? Such that `\mathds` displays/conceals like `\mathbb`, for example.

No, I think we need to define that specifically. If you can argue that `\mathds` should be displayed similar to `\mathbb`, then I could just add that, though.

> Another minor remark: shouldn't `\;` and `\,` conceal like `quad`? For ex: I have this configured:

Yes, perhaps. But `\;` and `\,` are both much smaller spaces, so replacing them with a full space may also be misleading?

Please note, for your info: I don't use conceals myself (I don't even like them). So in a way, I would always say "no" to questions like "shouldn't blah be concealed like blurgh". But I do understand that a lot of people find this feature useful and preferable, and since it is in many cases easy to include, I don't mind having it and improving it. :)

**Comment by patricknraanes** [comment]
> Everything is possible. Do you think it should be possible to combine? I.e.: bold, underline, bold, ital, underline, etc?

Cool! For sure, unless it requires much code complexity, I think being able to combine makes sense! In any case, underline is also common vector notation, so I definitely it should be available.

> If you can argue that `\mathds` should be displayed similar to `\mathbb`, then I could just add that, though.

I use `\mathds` to produce the double-struck `1`, as suggested [here](https://tex.stackexchange.com/a/26640/15175), and therefore I also prefer `\mathds` for other symbols. Seeing as this is a fairly common use case, I would say adding it to vimtex is reasonable. On the other hand, I don't know why other other vim/tex plugins have not done it. Moreover, once we start down this road, there's no telling [where it will end](https://tex.stackexchange.com/a/58124)... I therefore find it hard to give a strong recommendation here :see_no_evil: 

> Yes, perhaps. But \; and \, are both much smaller spaces, so replacing them with a full space may also be misleading?

Hmm... yes, that's true. My primary use case is to introduce spacing ahead of the punctuation in displayed equations, and I would favor concealing them, but again I have a hard time arguing with generality here.

**Comment by lervag** [comment]
> Cool! For sure, unless it requires much code complexity, I think being able to combine makes sense! In any case, underline is also common vector notation, so I definitely it should be available.

See #2033. Can't promise when, but at least there's an issue for it :)

> > If you can argue that `\mathds` should be displayed similar to `\mathbb`, then I could just add that, though.
> 
> I use `\mathds` to produce the double-struck `1`, as suggested [here](https://tex.stackexchange.com/a/26640/15175), and therefore I also prefer `\mathds` for other symbols. Seeing as this is a fairly common use case, I would say adding it to vimtex is reasonable. On the other hand, I don't know why other other vim/tex plugins have not done it. Moreover, once we start down this road, there's no telling [where it will end](https://tex.stackexchange.com/a/58124)... I therefore find it hard to give a strong recommendation here see_no_evil

It seems a simple solution is to add this specifically when the package `dsfont` is available?

> > Yes, perhaps. But ; and , are both much smaller spaces, so replacing them with a full space may also be misleading?
> 
> Hmm... yes, that's true. My primary use case is to introduce spacing ahead of the punctuation in displayed equations, and I would favor concealing them, but again I have a hard time arguing with generality here.

Could you show an example of this? I don't want to add a dedicated option for something like this, so I think the behavour should be "undisputed", which is why I am hesitating.

**Comment by patricknraanes** [comment]
>It seems a simple solution is to add this specifically when the package dsfont is available?

Sure. I was just worried about where it would end for you (the implementer).

Without
![Screenshot from 2021-04-13 11-18-33](https://user-images.githubusercontent.com/7222967/114529264-10e6b480-9c4a-11eb-89ed-29ffc866f300.png)
With
![Screenshot from 2021-04-13 11-18-53](https://user-images.githubusercontent.com/7222967/114529274-12b07800-9c4a-11eb-9f28-bc99a801aa76.png)

**Comment by lervag** [comment]
> > It seems a simple solution is to add this specifically when the package dsfont is available?
> 
> Sure. I was just worried about where it would end for you (the implementer).

Thanks :)

So, reg. `\mathds`, could you open a new issue for that with a simple, but clear description of what you want and a link here? That'll make it easier for me when I get around to it :)

----

I'm pushing a minor update that adds conceal to `\;`, `\:`, `\,`, and `\!` in math mode. After some thought, I think this makes some sense.

**Comment by patricknraanes** [comment]
Thanks for `boldital` btw!

**Comment by One-In-Dark** [comment]
A quick comment: just found that custom concealing setting of `\R` will wrongly takeover concealing of `\Re` :cry:

![image](https://github.com/user-attachments/assets/f48d9b55-95a6-4041-83c0-01967f06555e)

![image](https://github.com/user-attachments/assets/adab0733-924e-4faa-8e60-2c68a896d898)

**Comment by lervag** [comment]
You should show your custom definition - I believe we can avoid this issue quite easily.

**Comment by One-In-Dark** [comment]
> You should show your custom definition - I believe we can avoid this issue quite easily.

In neovim I have the Lua configuration as such:
```lua
vim.g.vimtex_syntax_custom_cmds = {
   {
      name = 'Reals', cmdre = 'R',
      mathmode = 1, concealchar = 'ℝ'
   }
}
```

Vimscript translation:
```vim
let g:vimtex_syntax_custom_cmds = [
            \ {'name': 'Reals', 'cmdre': 'R', 'mathmode': 1, 'concealchar': 'ℝ' },
            \ ]
```

If this was the expected behaviour, a workaround was to change `cmdre` from `R` to `R\>` (not escaped) relying on Vim's regex pattern.

**Comment by lervag** [comment]
> > You should show your custom definition - I believe we can avoid this issue quite easily.
> 
> In neovim I have the Lua configuration as such: …

Yes, you need to use `cmdre = 'R>'` here. You were on to it, but you missed the fine print in the docs; notice the last sentence here in `:help vimtex_syntax_custom_cmds`:

```vimhelp
*g:vimtex_syntax_custom_cmds*
    …
    cmdre ~
      Default: Undefined
      If this is defined, then it is used instead of `name` for matching the
      `cmdname` part. It is interpreted as a regular expression with "very
      magic" mode activated (see |/\v|).
```

It's not so surprising that you miss this. 🤷

**Comment by One-In-Dark** [comment]
> Yes, you need to use cmdre = 'R>' here.

Thanks! This solves the problem. Sorry for my carelessness.

Somehow I don't think it is the expected behaviour to match the prefix of the command name. Or could you kindly add this to the docs?

**Comment by lervag** [comment]
> > Yes, you need to use cmdre = 'R>' here.
> 
> Thanks! This solves the problem. Sorry for my carelessness.

No problem, and glad to help.

> Somehow I don't think it is the expected behaviour to match the prefix of the command name. Or could you kindly add this to the docs?

Well, yes, but I'm not quite sure _what_ to add. Can you please suggest an improvement?

**Comment by One-In-Dark** [comment]
> Can you please suggest an improvement?

IMHO, in the `cmdre` description, it can be added that:
```vimhelp
You may need to use `>` to avoid matching a prefix (see |/\>|).
```

And in the example, this usage can be made clear:
```vimhelp
The second example shows how to conceal `\R` with `ℝ`, avoiding `\Re` to be matched incorrectly.
```

```vim
    let g:vimtex_syntax_custom_cmds = [
          \ {'name': 'vct', 'mathmode': 1, 'argstyle': 'bold'},
          \ {'name': 'Reals', 'cmdre': 'R>', 'mathmode': 1, 'concealchar': 'ℝ'}, …]
```

**Comment by lervag** [comment]
Thanks!

**Comment by flin16** [comment]
Is it possible to set up the right conceal for \vct F, the font is plain, compared with \vct{F}.

**Comment by lervag** [comment]
Yes; I pushed an update that should make that work as expected. Please update and test.
