### ISSUE TITLE
g:tex_conceal not limiting the conceal behaviour, having to use conceallevel

### ISSUE THREAD

**Issue by sawsuh** [lervag/vimtex#1973]
I am using the most recent version of vimtex with vim-plug on neovim. My neovimrc is: 
```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'Valloric/YouCompleteMe'
Plug 'dense-analysis/ale'
Plug 'Yggdroot/indentLine'
Plug 'bfredl/nvim-miniyank'
Plug 'mcchrish/nnn.vim'
call plug#end()
filetype plugin on
filetype indent on
syntax on
set breakindent
set breakindentopt=shift:2
set encoding=utf-8
set incsearch
set tabstop=4
set shiftwidth=4
set expandtab
let maplocalleader=","
let g:vimtex_view_general_viewer = 'zathura'
let g:vimtex_view_general_options = ''
let g:tex_conceal=""
let g:UltiSnipsExpandTrigger="<c-j>"
let g:UltiSnipsJumpForwardTrigger="<c-b>"
let g:UltiSnipsJumpBackwardTrigger="<c-y>"
let g:goyo_width = 100
let g:ale_fixers = { 'python' : ['black', 'autopep8']}
let g:indentLine_color_term = 7
let g:indentLine_char = '>'
let g:limelight_conceal_ctermfg = 7

autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!

autocmd VimEnter * ALEDisable

inoremap jj <Esc>

autocmd FileType python nnoremap ,t :!python % 
autocmd FileType haskell nnoremap ,t :!runhaskell % 
autocmd FileType sh nnoremap ,t :!bash % 

au VimEnter * hi NonText ctermfg=8
au VimEnter * hi search ctermbg=8 ctermfg=15
au VimEnter * hi EndOfBuffer ctermfg=0
au VimEnter * hi CursorLineNr ctermfg=8
au VimEnter * hi LineNr ctermfg=8
set laststatus=0 ruler
set list lcs=tab:>\ 
set number
set relativenumber

map p <Plug>(miniyank-autoput)
map P <Plug>(miniyank-autoPut)
map ,n <Plug>(miniyank-cycle)
map ,N <Plug>(miniyank-cycleback)
```
I am finding that I still have concealed characters when editing a .tex file. doing 'set conceallevel=0' fixes the problem but I would prefer to simply have it fixed for tex files specifically using the tex_conceal option. Any ideas why setting g:tex_conceal='' is not working here?

**Comment by sawsuh** [comment]
Sorry, this was my bad. It turns out that [indentLine](https://github.com/Yggdroot/indentLine) was putting in an 'after' hook to set conceallevel, so even if I set conceallevel in my vimrc it wouldn't work (I'd have to set conceallevel manually within the editor). I removed `plug 'Yggdroot/indentLine'` from my `.vimrc` and all is fine.

**Comment by lervag** [comment]
> I am using the most recent version of vimtex with vim-plug on neovim. My neovimrc is:
> 
> ```viml
> let g:vimtex_view_general_viewer = 'zathura'
> let g:vimtex_view_general_options = ''
> let g:tex_conceal=""
> ```

You should read `:help vimtex_viewer_zathura`; I think you probably want to replace the `_view_` options with simply `let g:vimtex_view_method = 'zathura'`.

> I am finding that I still have concealed characters when editing a .tex file. doing 'set conceallevel=0' fixes the problem but I would prefer to simply have it fixed for tex files specifically using the tex_conceal option. Any ideas why setting g:tex_conceal='' is not working here?

VimTeX does not care about `g:tex_conceal` (see release notes for VimTeX v2.0). Instead, see docs for `:h g:vimtex_syntax_conceal`.

> Sorry, this was my bad. It turns out that [Yggdroot/indentLine](https://github.com/Yggdroot/indentLine) was putting in an 'after' hook to set conceallevel, so even if I set conceallevel in my vimrc it wouldn't work (I'd have to set conceallevel manually within the editor). I removed `plug 'Yggdroot/indentLine'` from my `.vimrc` and all is fine.

Ok, but my above replies may still be useful :)
