### ISSUE TITLE
make `tsf` work on `\dfrac`

### ISSUE THREAD

**Issue by ces42** [lervag/vimtex#1984]
It would be useful if `tsf` could convert `\dfrac`s into inline fractions (I often end up using `\dfrac` for fractions in inline math, which are the kinds of fractions I might want to use `tsf` on later one).

A possible drawback of this would be that `tsf` stops being involutive: Once you apply it to a `\dfrac` you can only get back a `\frac` (at least not without 'manual work').

**Comment by lervag** [comment]
Is `\dfrac` a custom command or is it provided by a package?

**Comment by ces42** [comment]
Oh right, I forgot to mention it's from amsmath (so fairly standard I would say).

**Comment by lervag** [comment]
Sorry about taking so damn long here! No real excuse, except "life" and new issues getting priority for no good reason.
