### ISSUE TITLE
vimtex compile issue

### ISSUE THREAD

**Issue by snochi** [lervag/vimtex#1985]
I suddenly faced a compile issue today. When I try to compile my LaTeX document, it fails, and when I try to look at the log file via `\le`, it says "No log file found".

Here's my .vimrc:

```vim
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'morhetz/gruvbox'
Plugin 'lervag/vimtex'
call vundle#end()
filetype plugin on

set nocompatible

set autoindent
set cindent
set expandtab
set shiftwidth=4
set spelllang=en_ca spell

set nu

let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=2
let g:tex_conceal='abdmg'
let g:latex_view_general_viewer = 'zathura'
let g:latex_view_general_options = shellescape('--synctex-forward "' . v:progname . ' --servername ' . v:servername . ' +{%line} {%file}"')

nnoremap <expr><buffer><silent> gb  ':!zathura --synctex-forward '.line(".").':'.col('.').':% ' . shellescape(g:latex#data[b:latex.id].out()) . ' >/dev/null<CR>'
```

And here's the `.tex` document that I tried to compile:

```tex
\documentclass{article}
\usepackage{amsmath}

\begin{document}
asdfasdf
\end{document}
```

+) I was having no issues with vimtex until today, and i've used it for about two years.

**Comment by lervag** [comment]
After you do `\ll`, what is the output in `\lo`?

**Comment by lervag** [comment]
> Here's my .vimrc:

Here is your vimrc cleaned up by me:

```viml
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'morhetz/gruvbox'
Plugin 'lervag/vimtex'
call vundle#end()
filetype plugin on

set autoindent
set cindent
set expandtab
set shiftwidth=4
set spelllang=en_ca spell
set number
set conceallevel = 2

let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_mode = 0
```

Some comments:

* The `g:tex_` options do not affect VimTeX.
* The `g:latex_view` options are not relevant to VimTeX.
* Your `gb` mapping should not be necessary, as `\lv` should suffice.

I assume you've updated VimTeX?

What is the details of your system? OS? Vim version?

**Comment by lervag** [comment]
> (1) This is the output of `\lo`:
> 
> ```
> Latexmk: This is Latexmk, John Collins, 22 April 2016, version: 4.45.
> Viewing pdf
> Latexmk: applying rule 'pdflatex'...
> Latexmk: Errors, so I did not complete making targets
> vimtex_compiler_callback_failure
> Rule 'pdflatex': File changes, etc:
>    Non-existent destination files:
>       'buggy.pdf'
> ------------
> Run number 1 of rule 'pdflatex'
> ------------
> ------------
> Running 'xelatex  -file-line-error -synctex=1 -interaction=nonstopmode -recorder  "buggy.tex"'
> ------------
> sh: 1: xelatex: not found

>   pdflatex: (Pdf)LaTeX failed to generate the expected log file 'buggy.log'
> ```

And there's your problem...

**Comment by snochi** [comment]
So how can I fix this problem?

Also, the main problem isn't that I am not getting the `.log` file. It's that I cannot compile my document.

**Comment by lervag** [comment]
I'm sorry for not being more clear; I was on my phone. In any case, I'm glad to hear you figured things out. My point in my last post was that your problem was related to this part in the output of `\lo`:

```
Running 'xelatex  -file-line-error -synctex=1 -interaction=nonstopmode -recorder  "buggy.tex"'
------------
sh: 1: xelatex: not found
```

I.e., the executable `xelatex` used to compile the document was not found.

By the way: From your post so far, there is no reason to know that you needed xelatex. That is, with your vimrc file and the tex file supplied, VimTeX and latexmk would _not_ use `xelatex`. Either you have supplied wrong information, or you have a `.latexmkrc` file that specifies to use `xelatex` for compilation - the issue template specifically mentions that you should also disclose any `.latexmkrc` file.
