### ISSUE TITLE
Highlight \iffalse … \fi as a comment

### ISSUE THREAD

**Issue by psvenk** [lervag/vimtex#1988]
Similarly to how `c.vim` shipped with Vim [highlights anything between `#if 0` and `#endif` as a comment][1], it would be nice if VimTeX highlighted anything between `\iffalse` and `\fi` as a comment, given that these play a similar role in TeX and are a useful way to comment out large swaths of TeX source.

In a similar vein, it may be useful to highlight the interior of a `comment` environment ([from the `comment` package][2]) as a comment.

[1]: https://github.com/vim/vim/blob/e3ffcd9902efc756178900d9bd972c74a09c3fcd/runtime/syntax/c.vim#L381-L401
[2]: https://tex.stackexchange.com/a/17818

**Comment by lervag** [comment]
It's not a such a bad idea, I think. I'd like a second opinion, though (perhaps @clason?).

If we did this, then I think `\iffalse` and `\fi` should still be highlighted to help distinguish this region.

**Comment by clason** [comment]
Highlighting contents of the `comment` environment as a comment sounds good to me. 

I'm not sure about `\iffalse...\fi`, as this is assuming that this construct is (ab)used for something specific (that is different from the general intended use as a programming language construct). (Also, this is TeX, not LaTeX, so it should depend on the flavor?)

**Comment by j1-lee** [comment]
I agree with @clason. Although I don't fully understand the nature of `\iffalse`, according to the Stack Exchange [article](https://tex.stackexchange.com/questions/46377/what-is-iffalse-for) @psvenk provided, there seem to be other usages of `\iffalse` (in the answers by egreg and yo').

For example, in [`latex.ltx`](https://www.tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/base/latex.ltx?view=co), we can find the following part:

```tex
\let\if@tempswa\iffalse
\def\loop#1\repeat{\def\iterate{#1\relax\expandafter\iterate\fi}%
  \iterate \let\iterate\relax}
```

I guess that highlighting the characters between `\iffalse` and `\fi` would not be correct.

**Comment by psvenk** [comment]
@j1-lee This is a good point. What if we only highlighted the contents of `\iffalse` … `\fi` if each one is the first (or only) token on its line?

I now realize that `geometry.dtx` has an `\iffalse` block that spans multiple documentation blocks (that is, there is also package code interspersed between, and we don't want that to be highlighted as a comment). I imagine that highlighting that would be quite complex.

Given the above, I'm not sure whether or not this is too specialized to be included in VimTeX, given that it would entail handling various edge cases. I had just thought that it would be a convenient quality of life addition, but it seems that this might open up a can of worms; however, I would still be happy to implement it if it is deemed beneficial as a feature to include. Another possibility is to use the approach I detailed previously and just exclude `dtx` files.

**Comment by lervag** [comment]
> Highlighting contents of the `comment` environment as a comment sounds good to me.

I'll look into that!

@clason
> I'm not sure about `\iffalse...\fi`, as this is assuming that this construct is (ab)used for something specific ...

@j1-lee
> I agree with @clason. ...

Thanks for pitching in! I really do appreciate it; it is sometimes hard to decide what is a good idea and what is not - often things may seem like both, and we just have to make a choice.

> @j1-lee This is a good point. What if we only highlighted the contents of `\iffalse` … `\fi` if each one is the first (or only) token on its line?
> ...

Perhaps we could add it as an optional highlight? Something like `g:vimtex_syntax_comment_iffalse`, which would be set to `0` or `v:false` by default (to avoid surprising long time users).

**Comment by lervag** [comment]
Note, the following should suffice for adding `\iffalse ... \endif` as comments:

```vim
syntax region texComment matchgroup=texCmd start="\\iffalse" end="\\endif"
```

**Comment by lervag** [comment]
> * I think you made a typo (I made the same typo earlier and just now retroactively fixed it); `\endif` should be `\fi`.

Thanks, fixed :)

> * It may be a good idea to enable folding, both for `comment` environments ([3809599](https://github.com/lervag/vimtex/commit/3809599d9fb6f9cc2589f2f3c62a8e5f4d6394b4)) and for `\iffalse ... \endif`, in line with how many other environments are folded and how multi-line comments are folded for other languages (including `#if 0 ... #endif` in C).

I think this is a completely new and separate thread. And I'm not fully sure what you mean: folding is enabled, especially for the `comment` environment (as environments are folded in general). Conditionals are also folded, but `\iffalse` is not in the default regex. See `:help vimtex_indent_conditionals`. If you think `\iffalse` should be folded by default, please raise a new issue - I might agree, but I have not thought about it yet.

> * I think it may still be a good idea to put restrictions in place on the `\iffalse` code. I tested your proposed code (substituting `\\fi` for `\\endif`), and the results are (arguably) tolerable but suboptimal on [`geometry.dtx`](http://mirrors.ctan.org/macros/latex/contrib/geometry/geometry.dtx):

Ah, yes - in this particular case, there is also the problem of nested conditionals: `\iffalse -> \ifcase -> \ifx -> \fi ...`; my initial proposal fails because it ends on the first `\fi`. This can be fixed by use of nested syntax groups. Something simple will probably suffice, e.g. a `texCommentContainedConds` groups that is only matched inside `texComment` and that contains transparent regions between `\if\w\+ -> \fi`.

If I add an optional `\iffalse` as comment-feature, I will definitely apply my above suggested improvement.

So: to do or not to do add this feature? It seems you are already interested in this, and I would guess it could be of interest to more people. So I'll raise a "why not"?

> * On a slightly unrelated note, I noticed that the `^^M` detection for `dtx` files currently does not work, presumably because [`texSpecialChar`](https://github.com/lervag/vimtex/blob/4a21851550877f8c1dee848ff41283b8e2b70fb0/autoload/vimtex/syntax/core.vim#L96) is defined after [`texComment`](https://github.com/lervag/vimtex/blob/4a21851550877f8c1dee848ff41283b8e2b70fb0/autoload/vimtex/syntax/core.vim#L56-L69) in `syntax/core.vim`, so `^^M` is highlighted as a `texSpecialChar` and the remainder of the line is not highlighted as a comment but as normal LaTeX.

Ah, good point; I never tested and so never noticed that. My fault.

**Comment by psvenk** [comment]
> And I'm not fully sure what you mean: folding is enabled, especially for the `comment` environment (as environments are folded in general).

I realized that I had not even enabled folding in VimTeX! I had grown used to folding in other languages and just assumed that it was already enabled in VimTeX when I had actually been living without folds. I enabled folding and the `comment` environment is folded as expected, in addition to VimTeX's superb folding in general.

> Ah, yes - in this particular case, there is also the problem of nested conditionals: `\iffalse -> \ifcase -> \ifx -> \fi ...`; my initial proposal fails because it ends on the first `\fi`. This can be fixed by use of nested syntax groups. Something simple will probably suffice, e.g. a `texCommentContainedConds` groups that is only matched inside `texComment` and that contains transparent regions between `\if\w\+ -> \fi`.

This sounds like a good way to do it. Do you have any idea how to mitigate the additional problem of intervening code in `dtx` files? (For example, in `geometry.dtx`, the corresponding `\fi` for the `\iffalse` is on line 123, but there is some package code before that line which should be highlighted normally.)

> > * On a slightly unrelated note, I noticed that the `^^M` detection for `dtx` files currently does not work […]
> 
> Ah, good point; I never tested and so never noticed that. My fault.

Thanks!

**Comment by lervag** [comment]
Sorry for the delay here! It's been very busy the last month.

I just pushed a change that I think might work well in almost every case, so that the option is not necessary. Let me know what you think, and if I'm wrong, I'll be happy to add a switch for this (with default set to off).

**Comment by psvenk** [comment]
Yes, this fix works well for me. Thank you @lervag!

**Comment by lervag** [comment]
Great :)
