### ISSUE TITLE
Compiling on Mac Terminal

### ISSUE THREAD

**Issue by cmarshak** [lervag/vimtex#199]
I am fairly new to vim.  I badly want to use it for latex.  I am using Vundle to manage the plugins, but can't seem to get vim to work correctly after `:BundleInstall'.

As the docs suggest, I have `+clientserve` available.  However when I type `:ll`, I get the error `E776: No location list`.  When I intialize vim with 'vim --servername test_servername' and then open up the latex file in a new tab, still get the same error.  I am not really sure what's going on with clientserve (obviously), but would appreciate any help in resolving this issue.

I have used TexShop for a long time, but really excited about transitioning.

**Comment by micbou** [comment]
You are using the wrong command: use `\ll` (a backslash instead of a colon). Backslash is the default key for `<leader>`.

**Comment by cmarshak** [comment]
I can't use `\' in the terminal.  I am trying to google my way to the answer, but no luck.  If you could suggest a fix that would be appreciated.

**Comment by cmarshak** [comment]
http://stackoverflow.com/questions/11122866/vim-default-leader-key-on-a-macbook

**Comment by lervag** [comment]
Hi @cmarshak! I'm glad you trying out Vim for LaTeX. I personally think it works very well!

As @micbou says, `:ll` is not the correct command. And as you've already seen from the SO-question, you can remap the leader key to for instance `,`, which means you should be able to begin compiling with `,ll`.

Note that the commands are also available with the ex commands, i.e. typing `:VimtexCompile<cr>` (here `<cr>` means the Enter/Return-key). If you type `:Vimtex<c-d>`, where `<c-d>` is CTRL-d, you will get a list of available Vimtex commands.

**Comment by pclucas14** [comment]
Hi, 

I'm running into a similar issue. I am new to vimtex and also using a Mac. I have remapped the leader key to `,`, yet no vimtex commands seem to work (e.g `,ll` or `,lc`)

Minimal `.vimrc` file
```
call plug#begin('~/.vim/plug.vim')
Plug 'lervag/vimtex'
call plug#end() " start all the plugins above
let g:vimtex_view_method = 'skim'
let mapleader = ","
```
vimtex is loaded as `:help vimtex` loads the documentation. 


Any thoughts ?

**Comment by lervag** [comment]
Hi @pclucas14. First, I would recommend that you in the future open a new issue instead of "bumping" an old issue. You can refer to an old issue with the syntax `#issue-number`, e.g. #199.

Regarding your issue: vimtex does not use `mapleader`, instead, it uses `maplocalleader`, which is by default `\`. So, you can try `\ll` and `\lc`. See `:help maplocalleader` for more info.

**Comment by pclucas14** [comment]
Everything works now! Thanks
