### ISSUE TITLE
How to add `xelatex` cli arguments while compiling?

### ISSUE THREAD

**Issue by nations-Xiong** [lervag/vimtex#1993]
I am using the latex package *markdown*, and the *xelatex* compiler. It needs to be compiled by using `xelatex --shell-escape file.tex`. How can I add this argument while compiling with `<leader>ll`?

**Comment by lervag** [comment]
```vim
let g:vimtex_compiler_latexmk = {
      \ 'options' : [
      \   '-shell-escape',
      \   '-verbose',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \ ],
      \}
```

See `:help vimtex_compiler_latexmk` for more details.

Also: Please don't use `** ... **` in the title (what was the purpose of that, anyway?).

**Comment by nations-Xiong** [comment]
Thanks!
