### ISSUE TITLE
fix main file by *.latexmain file

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#200]
As arisen in https://github.com/lervag/vimtex/issues/198#issuecomment-119478302 :

A `*.latexmain` file to mark the main file is useful in a collaborate project where there's
- the common main file, and 
- the author's main file (ignored by git). 

Then the only solution to ensure that Vimtex choses author's main file is, currently, decorating all collaborate TeX files by %! TEX root = ....

For inspiration, this function has already been implemented in LaTeX Box : https://github.com/LaTeX-Box-Team/LaTeX-Box/issues/182

**Comment by lervag** [comment]
I've pushed an update that brings support for `.latexmain` specifiers. It works on the simple test that I've used.

I also updated the docs on multi-file projects. I've indicated the method priority. I think the priority makes sense, but I am not sure: Perhaps `.latexmain` should have higher priority than `TeX root specifier` and `subfiles`?

**Comment by Konfekt** [comment]
Thanks a lot ! The priority also makes sense to me, by the local before global principle. 

So everything fine in my eyes.

**Comment by lervag** [comment]
Great!
