### ISSUE TITLE
Section motions don't work with KOMA-script's \addsec 

### ISSUE THREAD

**Issue by bongbang** [lervag/vimtex#2003]
Is there a way for me to make it work? I know it's possible to add custom matchers for TOC and folding, but I don't see how to do it for motions (e.g. `[[`, `]]`). Thank you.

**Comment by lervag** [comment]
No, sorry, there is no mechanism for this as of now. Since 2013, your the first who has asked for this, so I would claim your use case is quite uncommon. Can you show an example of what you want to achieve?

**Comment by bongbang** [comment]
Thank you for your reply. `\addsec` is the same as the standard `\section*`, except the unnumbered section will appear in the table of contents, which is much handier than appending `\addcontentsline` to every unnumbered section. 

It may not be worthwhile for you to provide a custom sectioning option, but if this is a matter of adding a line or two to the code, could you point me in the right direction, please? (Being completely ignorant of VimScript, I don't even know which file or even directory to look to monkey with the code.)

**Comment by lervag** [comment]
Thanks, it is getting clearer now. I'd like to know a little bit more, though:

1. Where is `\addsec` defined? Can you show me a manual/reference?
2. You want `\addsec` to be supported by the sectioning motions `[[` and `]]`.
3. Where else do you want `\addsec` to be recognized?

**Comment by bongbang** [comment]
1. It's defined in the [KOMA-Script package](https://www.ctan.org/pkg/koma-script). The manuals are available on the linked page, with the German one supposedly being much more complete.
2. Yes, please.
3. The VimTex's TOC is the only must-have that I can think of, but ideally `\addsec` should be treated as synonynous with `\section*` (and `\addchap` and `\addpart` with `\chapter*` and `\part*` respectively).

**Comment by lervag** [comment]
Ok, thanks. Then I think the following actions are more or less sufficient:

* [ ] Add `syntax/p/scrbook.vim` to add syntax support for KOMA-script files.
* [ ] Add the `\add(sec|chap|part)` variants to the section regexes:
  * [ ] `motion.vim`
  * [ ] `toc.vim`
  * [ ] ...

For my own sake, I'll also look for a way to "generalize" the section regexes so that it is not necessary to keep tabs of so many locations.

**Comment by lervag** [comment]
I've now added some initial support (motions and ToC), please test. Is this going in the right direction?

**Comment by bongbang** [comment]
It's working. Thank you very much.  The only issue I notice is that the argument of `\addsec` (i.e. the heading inside the bracket) has the color of normal text instead of being highlighted the same way as that of `\section*`.  I'm not sure if syntax-highlighting is a responsibility of VimTex or something else. (If it is, I have a separate bug to report.)

Thank you again for your responsiveness on top of crafting this already exceptional plug-in.

**Comment by lervag** [comment]
> It's working. Thank you very much. The only issue I notice is that the argument of `\addsec` (i.e. the heading inside the bracket) has the color of normal text instead of being highlighted the same way as that of `\section*`. I'm not sure if syntax-highlighting is a responsibility of VimTex or something else. (If it is, I have a separate bug to report.)

Yes, I had not added syntax support, but it should be good now. Please test.

> Thank you again for your responsiveness on top of crafting this already exceptional plug-in.

Thanks for the kind words :)
