### ISSUE TITLE
preserve location in citation

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#2008]
As a follow up to https://github.com/lervag/vimtex/commit/428906647a22fdb30409554935eacdd9932726cb , the current concealment of `cite[...]{...}` loses the whole information`[...]` matched by `\%(\[[^]]*\]\)` that usually contains the place where the citation is found in the cited document. Say, `\cite[Statement 3]{RMS}`.

If there is a place, that is, square brackets, how about concealing `\cite[Statement 3]{RMS}` by `[Statement 3 in RMS]` instead of `[RMS]`? 

Instead of

```vim
 syntax match texCmdRefConcealed
        \ "\\cite[tp]\?\>\*\?"
        \ conceal skipwhite nextgroup=texRefConcealedOpt,texRefConcealedPre
  syntax match texRefConcealedPre contained "{"
        \ conceal cchar=[
        \ skipwhite nextgroup=texRefConcealedArg
  syntax match texRefConcealedArg contained "[^}]*"
        \ skipwhite nextgroup=texRefConcealedPost
  syntax match texRefConcealedPost contained "}"
        \ conceal cchar=]
```

something like

```vim
 syntax match texCmdRefConcealed
        \ "\\cite[tp]\?\>\*\?"
        \ conceal skipwhite nextgroup=texRefConcealedOpt,texRefConcealedPre
 syntax match texRefConcealedPre contained "["
        \ conceal cchar=
        \ skipwhite nextgroup=texRefConcealedArg
  syntax match texRefConcealedArg contained "}["
        \ conceal cchar=@[
        \ skipwhite nextgroup=texRefConcealedPost
  syntax match texRefConcealedPost contained "}"
        \ conceal cchar=]
```

A difficulty is that `\cite` accepts optional parameters other than the location of the citation, and the existing syntax matching for `\cite{...}` without `[..]` is to be treated differently (by keeping it as is).

**Comment by lervag** [comment]
> If there is a place, that is, square brackets, how about concealing `\cite[Statement 3]{RMS}` by `[Statement 3 in RMS]` instead of `[RMS]`?

I agree this would be nice! Btw., RMS? I guess you're reading the latest FSF news? :)

The main problem is that `cchar` does not allow more than a single substitute character. So, the part `]{` can not be concealed with ` in `. However, some options may work:

* `\cite[Statement 3]{RMS}` -> `[Statement 3][RMS]` (this should be simple!)
* `\cite[Statement 3][more opts]{RMS}` -> `[Statement 3][RMS]` (this should also be possible/simple)
* `\cite[Statement 3]{RMS}` -> `[Statement 3; RMS]` (this may be possible, but I think it will be harder!)

**Comment by Konfekt** [comment]
Yes, making people curious about the latest news. The second item looks great, the last one more natural; though not worth much effort.

**Comment by lervag** [comment]
Ok, I've implemented an initial version. Let me know what you think.

**Comment by Konfekt** [comment]
Great! Solves this issue for me. 

While at it, would the same concealment for  `\ref`, `\cref{...}`, ... be reasonable?

**Comment by lervag** [comment]
Happy to hear it!

> While at it, would the same concealment for \ref, \cref{...}, ... be reasonable?

Good question. As I don't really use this feature myself, I'm not sure what to say. I propose that you, if interested, open a new issue and suggest the feature. If people want it, I'll add it.
