### ISSUE TITLE
ToC frame matcher with title and subtitle

### ISSUE THREAD

**Issue by Saavestro** [lervag/vimtex#2010]
I like defining frames in beamer as

```
\begin{frame}{title}{subtitle}
```

But the [current toc frame matcher](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/parser/toc/beamer_frame.vim) is compatible only with frames defined as

```
\begin{frame}{title}
```

So in the toc window I get an entry like

* Frame: title}{subtitle

This is badly formatted.

It would be nice to extend the default frame matcher to be compatible with both frame definitions described above.

**Comment by lervag** [comment]
This should be supported now. Let me know what you think.

**Comment by Saavestro** [comment]
Thank you. It works as it should.

**Comment by lervag** [comment]
Great!
