### ISSUE TITLE
Disable specific ToC matchers

### ISSUE THREAD

**Issue by Saavestro** [lervag/vimtex#2011]
Disabling toc matchers can be useful sometimes.

For example, in a beamer frame defined as

```
\section{Some section}
\subsection{Some subsection}
\begin{frame}{\insertsection}{\insertsubsection}
```

the toc window show entries like

* Some section 1
* Some subsection 1.1
* Frame: Some section}{Some subsection

In this case the third entry is useless (and badly formatted). Then here it would be useful to disable the [default frame matcher](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/parser/toc/beamer_frame.vim).

**Comment by lervag** [comment]
This is added now, see `:help g:vimtex_toc_config_matchers`. Let me know what you think, and feel free to suggest improvements e.g. to the docs.

**Comment by Saavestro** [comment]
Thank you! It works well. The documentation seems good to me.

**Comment by lervag** [comment]
Great, happy to hear it!
