### ISSUE TITLE
Multiple citations not highlighted

### ISSUE THREAD

**Issue by bongbang** [lervag/vimtex#2013]
Arguments of the `\cites` command are not highlighted the way that of `\cite` is. This is also the case for `\autocites` and presumably other variants as well.

**Comment by lervag** [comment]
Can you provide a full example?

**Comment by lervag** [comment]
Specifically: `\cites` and similar are only available with `biblatex`, and if you load `biblatex` then these should be properly highlighted.

**Comment by bongbang** [comment]
I'm not sure what you mean by "load biblatex". The package is in my preamble and it does give me citations when I compile the .tex document, if that's what you mean. I get correct highlighting and a context menu with `\autocite{citation}` but neither with `\autocites{citation_1}{citation_2}`. (Is that enough example for you or do you want a whole .tex document?)

**Comment by lervag** [comment]
When you first started a new issue, you were presented with an issue template. Please [read it again](https://github.com/lervag/vimtex/blob/master/.github/ISSUE_TEMPLATE/issue_report.md). IMHO, I do not understand why "full example" is hard to understand. So, again:

> (Is that enough example for you or do you want a whole .tex document?)

Yes, I want a whole `.tex` docuiment. But I want a _minimal_ document, i.e., it should compile, but only contain whatever is necessary for me to reproduce your problem.

**Comment by bongbang** [comment]
Yes, I understand the use of a minimal example, but I thought highlighting was such a simple issue that you could try it in any .tex document you already have.  

Here's my example.

```
\documentclass{article}

\usepackage[style=verbose-ibid,
		]{biblatex}
\addbibresource{highlight.bib}

\begin{document}

\begin{enumerate}

	\item The following citation command is properly highlighted and the
		citation key is equipped with a context
		menu.\autocite[10]{Hemingway:For_Whom_the}

	\item Neither citation key in the following is highlighted or equipped
		with a context
		menu.\autocites{Hemingway:For_Whom_the}{JiM::Organized_Crime_2020}

	\item In the following, the first citation key is highlighted and
		equipped with a context menu, but not the second; neither postnote
		is
		highlighted.\autocites[10]{Hemingway:For_Whom_the}[20]{JiM::Organized_Crime_2020}

	\item The following produces the same effect as the
		previous.\autocites[10]{Hemingway:For_Whom_the}{JiM::Organized_Crime_2020}

	\item In the following, the first citation key is not highlighted, but
		the second is; neither is equipped with a context menu and postnote
		is not highlighted.
		is.\autocites{Hemingway:For_Whom_the}[20]{JiM::Organized_Crime_2020}

\end{enumerate}

\end{document}
```

`highlight.bib`

```
@book{Hemingway:For_Whom_the,
	author   = {Earnest Hemingway},
	title    = {For Whom the Bell Tolls},
	date     = {1940},
	publisher  = {Simon \& Schuster},
}

@book{JiM::Organized_Crime_2020,
	author   = {Justice in Mexico},
	title    = {Organized Crime and Violence in Mexico: 2020 Special Report},
	date     = {2019-07},
	publisher = {Justice in Mexico},
}
```

**Comment by lervag** [comment]
Thanks; I've reproduced the issue and submitted a patch now. Let me know how it works.

Notice that for multiline `\usepackage` commands, the package might not load properly until you've compiled your document (that is, the package should load if there's an `.fls` file present).

**Comment by bongbang** [comment]
The highlighting now works, but still not the context menu. Should I open another issue?

**Comment by lervag** [comment]
Ah, yes, sorry: please open a new issue for that. And linking here or adding the example will help - I don't have so much time, so everything that lowers the time for me to get the full context helps me to fix things fast.
