### ISSUE TITLE
Errors & warnings shown in another tab

### ISSUE THREAD

**Issue by carlosala** [lervag/vimtex#2015]
Hi!
I love vimtex, but I think that there is one interesting thing to add. Compiling with `latexmk`, it appears the quickfix list in the same tab, just splitting the window. I think that would be great to have the possibility with some global variable, for instance:
`let g:vimtex_compiler_latexmk_newtab = 1` 
to open this quickfix list in another tab. This would be very comfortable when you are working on a small laptop to still see all your code and have the possibility to see your warnings with just typing `gt`.
Thanks!

**Comment by lervag** [comment]
> I love vimtex,

<3

> but I think that there is one interesting thing to add. ...

I'm sorry, but I don't agree. VimTeX should not interfere with the quickfix window any more than necessary. See e.g. [here](https://github.com/romainl/vim-qf/issues/69), and note @romainl's last comment to which I fully agree (except for very special cases; I've bolded the important part):

> Closing this as there is no resolution in sight. I stand by my position: **filetype-specific plugins have no business handling the quickfix window**.
