### ISSUE TITLE
How do these insert mode imappings work?

### ISSUE THREAD

**Issue by Foro38** [lervag/vimtex#2018]
I am tryingto use the insert mode imappings but they don't seem to work

when I type `j in insert mode and press enter, nothing happens

**Comment by j1-lee** [comment]
`j is not mapped to anything in the default setting.

**Comment by Foro38** [comment]
I meant `jj , sorry

**Comment by lervag** [comment]
> I am tryingto use the insert mode imappings but they don't seem to work

Well, they work for me. So far, what you say is simply: "X does not work for me". Please provide a full minimal example and specific steps to reproduce your problem, as described in the [issue template](https://github.com/lervag/vimtex/blob/master/.github/ISSUE_TEMPLATE/issue_report.md).

Note that all new issues are filled with this template, so you deliberately deleted this text. It could be helpful to me (seriously!) if you explain why you did that and why you think your short description is enough for me to help you?
