### ISSUE TITLE
The TexMathZoneX and TexmathZoneXX in vimtex_syntax may not work well with Ultisnips

### ISSUE THREAD

**Issue by hanqing0521** [lervag/vimtex#2019]
I am sorry for no `minimal.vim` or `minimal.tex`.  The issue connects with Ultisnips. Are there someone meeting the same issue with me? **When enabling vimtex_syntax, the Ultisnips with `context "math()"`  can not work, while other mathzones work well.** I used many kinds of  `math()` function such as

1. The function provide by the vimtex.
    ```
    def math():
        return vim.eval('vimtex#syntax#in_mathzone()') == '1'
    ```
2. The one in #1863
    ```python
    global !p
    texMathZones = ['texMathZone' + x for x in ['', 'X', 'XX', 'Env', 'EnvStarred', 'Ensured']]

    texIgnoreMathZones = ['texMathText']

    texMathZoneIds = vim.eval('map('+str(texMathZones)+", 'hlID(v:val)')")

    texIgnoreMathZoneIds = vim.eval('map('+str(texIgnoreMathZones)+", 'hlID(v:val)')")

    ignore = texIgnoreMathZoneIds[0]

    def math():
            synstackids = vim.eval("synstack(line('.'), col('.') - (col('.')>=2 ? 1 : 0))")
            try:
                    first = next(i for i in reversed(synstackids) if i in texIgnoreMathZoneIds or i in texMathZoneIds)
                    return first != ignore
            except StopIteration:
                    return False
    endglobal
    ```

3. if disabling the vim_syntax through `let g:syntax_enable=0`, and using traditional `math()` function and modified tex.vim (syntax file), the inline math snips work well.

current commit is commit 860f6364b954cc710d3773c5299479e6099cbb9f (HEAD -> master, origin/master, origin/HEAD)

If someone read the issue, please try to test the inline math. I am not sure that I am the only unlucky guy. If it is a bug of the vimtex_syntax, the developer may help to fix it. Thank you very much

**Comment by lervag** [comment]
> I am sorry for no `minimal.vim` or `minimal.tex`.

I use Ultisnips with the first of your listed options, [see here](https://github.com/lervag/dotvim/blob/master/UltiSnips/tex.snippets). For me, everything works as expected. And this is precisely why I ask for the minimal examples: You claim that you have tried various options, but I already know that options 1 and 2 both work if you do it correctly. So, you need to show me what you are doing. Providing a minimal example is the very best way, but if you are unable to do that, then it is still better to show me your real configuration. I am quite sure you have some misconfiguration that explains your problem.

> 3. if disabling the vim_syntax through `let g:syntax_enable=0`, and using traditional `math()` function and modified tex.vim (syntax file), the inline math snips work well.

There is nothing named "vim_syntax" or `g:syntax_enable`. I am guessing that what you meant here is `g:vimtex_syntax_enabled`. Please note that using the correct names for things is quite important to avoid confusion or misunderstandings. I understand that it can be hard to know what everything is called, of course, but my point is still important. If you don't know the proper names, then it can be good to mention that as well.

**Comment by hanqing0521** [comment]
Yes, is the `let g:vimtex_syntax_enabled=0`.  Under this situation, I must use the minimal.vim and minimal.tex.  I will do it as soon as possible.

**Comment by lervag** [comment]
Sounds good. Let me know if you need help to create a minimal example.

**Comment by hanqing0521** [comment]
Shocking, I use the files in the example-minimal, it works well!
```vim
set nocompatible
"let &rtp = '../..,' . &rtp
"let &rtp .= ',../../after'
let &rtp = "/home/lixun/.vim/plugged/vimtex," . &rtp
let &rtp .= ',/home/lixun/.vim/plugged/ultisnips'
let &rtp .= ',/home/lixun/.vim/plugged/vimtex/after'
let &rtp .= ',/home/lixun/.vim/plugged/vim-snippets'
let &rtp .= ',/home/lixun/.vim/plugged/ultisnips/after'
let &rtp .= ',/home/lixun/.vim/after'
let &rtp .= ',/home/lixun/.vim/plugged/coc.nvim'
let &rtp .= ',/home/lixun/.vim/plugged/vim-which-key'
filetype plugin indent on
syntax enable
nnoremap q :qall!<cr>

let g:vimtex_view_automatic = 0

let g:maplocalleader=" "
let g:mapleader=','

let g:vimtex_syntax_enabled=1
silent edit main.tex
```
An interesting thing is that when I `let g:vimtex_syntax_enabled=0` in my old vimrc,  it works well though I use the function 
```def math():
    return vim.eval('vimtex#syntax#in_mathzone()') == '1'
```

It is puzzling!

My own vimrc file is too  long,  I upload in an  obsolete git repo if you want to see it [vimrc](https://github.com/hanqing0521/MyVim/blob/master/vimrc)

I am the unlucky guy!

**Comment by lervag** [comment]
> Shocking, I use the files in the example-minimal, it works well!

Hehe, not so shocking for me :)

> An interesting thing is that when I add `let g:vimtex_syntax_enabled = 0` in my old vimrc, it works well even though I use the function
> 
> ```python
> def math():
>     return vim.eval('vimtex#syntax#in_mathzone()') == '1'
> ```

This is also not so strange, because this function should actually work well with the original Vim LaTeX syntax scripts. :)

> It is puzzling!

I agree; but I think the puzzle is related to your configuration. Are you sure you are using the latest version of VimTeX? Do you have any conflicting plugins? Have you installed plugins at system level (e.g. `sudo apt install ...` or similar)?

One useful thing you can test: When you use your configuration without the `let g:vimtex_syntax_enabled = 0`, that is, in the case where things _do **not** work_: can you copy the output of `:scriptnames` after you have loaded a LaTeX file?

> My own vimrc file is too long, I upload in an obsolete git repo if you want to see it [vimrc](https://github.com/hanqing0521/MyVim/blob/master/vimrc)
> 
> I am the unlucky guy!

Not so unlucky: I'll take a look at your vimrc files and see if I can spot a problem.

**Comment by lervag** [comment]
> > My own vimrc file is too long, I upload in an obsolete git repo if you want to see it [vimrc](https://github.com/hanqing0521/MyVim/blob/master/vimrc)
> > I am the unlucky guy!
> 
> Not so unlucky: I'll take a look at your vimrc files and see if I can spot a problem.

Some general comments:
* Your repo contains both a `.vimrc` and a `vimrc` file; they are out of sync. You've linked to the `vimrc` file, so I am assuming the `.vimrc` file is not relevant.
* Your repo includes a lot of empty directories under `.vim/bundle/...`.
* You should not mix `Plug 'path'` lines with plugin configuration. Some plugins relies on function calls for configuration, but this is only possible after `call plug#end()`. I recommend to have a separate plugin "preamble" that simple does `call plug#begin` + `Plug ...` + `call plug#end`. Then add plugin configuration after this.

LaTeX and VimTeX specific comments:
* You can remove the `g:tex_conceal` option, as it is not relevant if you use VimTeX (with VimTeX syntax).
* You should not set values that are already default. Your "begin vimtex" section can be reduced to the following equivalent code:

  ```vim
  Plug 'lervag/vimtex'
  let g:vimtex_view_method = 'zathura'
  let g:vimtex_quickfix_ignore_filters = [
        \ 'Marginpar on page',
        \ 'Package',
        \]
  let g:vimtex_grammar_textidote = {
        \ 'jar': '/home/lixun/.local/bin/textidote.jar',
        \ 'args': '',
        \}
  autocmd BufEnter *.cls,*.tex nmap K :VimtexDocPackage<cr>
  ```

Except for this, I can't see anything specific that should explain your problem. My suggestion about `:scriptnames` may be the easiest way to discover what is happening.

**Comment by hanqing0521** [comment]
> > Shocking, I use the files in the example-minimal, it works well!
> 
> Hehe, not so shocking for me :)
> 
> > An interesting thing is that when I add `let g:vimtex_syntax_enabled = 0` in my old vimrc, it works well even though I use the function
> > ```python
> > def math():
> >     return vim.eval('vimtex#syntax#in_mathzone()') == '1'
> > ```
> 
> This is also not so strange, because this function should actually work well with the original Vim LaTeX syntax scripts. :)
> 
> > It is puzzling!
> 
> I agree; but I think the puzzle is related to your configuration. Are you sure you are using the latest version of VimTeX? Do you have any conflicting plugins? Have you installed plugins at system level (e.g. `sudo apt install ...` or similar)?
> 
> One useful thing you can test: When you use your configuration without the `let g:vimtex_syntax_enabled = 0`, that is, in the case where things _do **not** work_: can you copy the output of `:scriptnames` after you have loaded a LaTeX file?
> 
> > My own vimrc file is too long, I upload in an obsolete git repo if you want to see it [vimrc](https://github.com/hanqing0521/MyVim/blob/master/vimrc)
> > I am the unlucky guy!
> 
> Not so unlucky: I'll take a look at your vimrc files and see if I can spot a problem.

1. No other vim plugins install by system package managers like pacman or yay.
2.  When without `let g:vimtex_synatx_enabled=0`, the vimtex_syntax will be enabled by the default setting. The "math()" funciton does not work in inline math.
3. The output of scriptnames without `let g:vimtex_synatx_enabled=0` ,
 ```vim
  1: /etc/vimrc
  2: /usr/share/vim/vimfiles/archlinux.vim
  3: ~/.vimrc
  4: ~/.vim/autoload/plug.vim
  5: /usr/share/vim/vim82/filetype.vim
  6: ~/.vim/plugged/ultisnips/ftdetect/snippets.vim
  7: ~/.vim/plugged/vimtex/ftdetect/tex.vim
  8: /usr/share/vim/vimfiles/ftdetect/PKGBUILD.vim
  9: /usr/share/vim/vimfiles/ftdetect/conkyrc.vim
 10: /usr/share/vim/vim82/ftplugin.vim
 11: /usr/share/vim/vim82/indent.vim
 12: /usr/share/vim/vim82/syntax/syntax.vim
 13: /usr/share/vim/vim82/syntax/synload.vim
 14: /usr/share/vim/vim82/syntax/syncolor.vim
 15: ~/.vim/plugged/awesome-vim-colorschemes/colors/OceanicNext.vim
 16: ~/.vim/plugged/vim-easy-align/plugin/easy_align.vim
 17: ~/.vim/plugged/coc.nvim/plugin/coc.vim
 18: ~/.vim/plugged/coc.nvim/autoload/coc/rpc.vim
 19: ~/.vim/plugged/coc.nvim/autoload/coc/util.vim
 20: ~/.vim/plugged/coc.nvim/autoload/coc/client.vim
 21: ~/.vim/plugged/ultisnips/plugin/UltiSnips.vim
 22: ~/.vim/plugged/ultisnips/autoload/UltiSnips/map_keys.vim
 23: ~/.vim/plugged/vim-snippets/plugin/vimsnippets.vim
 24: ~/.vim/plugged/vim-airline/plugin/airline.vim
 25: ~/.vim/plugged/vim-airline/autoload/airline/init.vim
 26: ~/.vim/plugged/vim-airline/autoload/airline/parts.vim
 27: ~/.vim/plugged/vim-airline/autoload/airline/formatter/short_path.vim
 28: ~/.vim/plugged/vim-airline/autoload/airline/util.vim
 29: ~/.vim/plugged/vim-airline-themes/plugin/airline-themes.vim
 30: ~/.vim/plugged/fcitx.vim/plugin/fcitx.vim
 31: ~/.vim/plugged/vim-easymotion/plugin/EasyMotion.vim
 32: ~/.vim/plugged/vim-easymotion-chs/plugin/setup.vim
 33: ~/.vim/plugged/vim-which-key/plugin/which_key.vim
 34: ~/.vim/plugged/vim-choosewin/plugin/choosewin.vim
 35: ~/.vim/plugged/Undotree/plugin/undotree.vim
 36: ~/.vim/plugged/vim-surround/plugin/surround.vim
 37: ~/.vim/plugged/vim-boxdraw/plugin/boxdraw.vim
 38: ~/.vim/plugged/vim-table-mode/plugin/table-mode.vim
 39: ~/.vim/plugged/LeaderF/plugin/leaderf.vim
 40: ~/.vim/plugged/vim-gutentags/plugin/gutentags.vim
 41: ~/.vim/plugged/jupyter-vim/plugin/jupyter.vim
 42: ~/.vim/plugged/nerdtree/plugin/NERD_tree.vim
 43: ~/.vim/plugged/nerdtree/autoload/nerdtree.vim
 44: ~/.vim/plugged/nerdtree/lib/nerdtree/path.vim
 45: ~/.vim/plugged/nerdtree/lib/nerdtree/menu_controller.vim
 46: ~/.vim/plugged/nerdtree/lib/nerdtree/menu_item.vim
 47: ~/.vim/plugged/nerdtree/lib/nerdtree/key_map.vim
 48: ~/.vim/plugged/nerdtree/lib/nerdtree/bookmark.vim
 49: ~/.vim/plugged/nerdtree/lib/nerdtree/tree_file_node.vim
 50: ~/.vim/plugged/nerdtree/lib/nerdtree/tree_dir_node.vim
 51: ~/.vim/plugged/nerdtree/lib/nerdtree/opener.vim
 52: ~/.vim/plugged/nerdtree/lib/nerdtree/creator.vim
 53: ~/.vim/plugged/nerdtree/lib/nerdtree/flag_set.vim
 54: ~/.vim/plugged/nerdtree/lib/nerdtree/nerdtree.vim
 55: ~/.vim/plugged/nerdtree/lib/nerdtree/ui.vim
 56: ~/.vim/plugged/nerdtree/lib/nerdtree/event.vim
 57: ~/.vim/plugged/nerdtree/lib/nerdtree/notifier.vim
 58: ~/.vim/plugged/nerdtree/autoload/nerdtree/ui_glue.vim
 59: ~/.vim/plugged/nerdtree/nerdtree_plugin/exec_menuitem.vim
 60: ~/.vim/plugged/nerdtree/nerdtree_plugin/fs_menu.vim
 61: ~/.vim/plugged/nerdtree/nerdtree_plugin/vcs.vim
 62: ~/.vim/plugged/vim-devicons/nerdtree_plugin/webdevicons.vim
 63: ~/.vim/plugged/nerdcommenter/plugin/NERD_commenter.vim
 64: ~/.vim/plugged/vim-rainbow/plugin/rainbow.vim
 65: ~/.vim/plugged/vim-fencview/plugin/fencview.vim
 66: ~/.vim/plugged/vim-hexokinase/plugin/hexokinase.vim
 67: ~/.vim/plugged/vim-hexokinase/autoload/hexokinase/v2.vim
 68: ~/.vim/plugged/vim-devicons/plugin/webdevicons.vim
 69: ~/.vim/plugged/vim-airline/autoload/airline.vim
 70: ~/.vim/plugged/markdown-preview.nvim/plugin/mkdp.vim
 71: /usr/share/vim/vimfiles/plugin/gtags-cscope.vim
 72: /usr/share/vim/vimfiles/plugin/gtags.vim
 73: /usr/share/vim/vim82/plugin/getscriptPlugin.vim
 74: /usr/share/vim/vim82/plugin/gzip.vim
 75: /usr/share/vim/vim82/plugin/logiPat.vim
 76: /usr/share/vim/vim82/plugin/manpager.vim
 77: /usr/share/vim/vim82/plugin/matchparen.vim
 78: /usr/share/vim/vim82/plugin/netrwPlugin.vim
 79: /usr/share/vim/vim82/plugin/rrhelper.vim
 80: /usr/share/vim/vim82/plugin/spellfile.vim
 81: /usr/share/vim/vim82/plugin/tarPlugin.vim
 82: /usr/share/vim/vim82/plugin/tohtml.vim
 83: /usr/share/vim/vim82/plugin/vimballPlugin.vim
 84: /usr/share/vim/vim82/plugin/zipPlugin.vim
 85: ~/.vim/plugged/ultisnips/after/plugin/UltiSnips_after.vim
 86: ~/.vim/plugged/indentLine/after/plugin/indentLine.vim
 87: ~/.vim/plugged/vim-easymotion-chs/autoload/EasyMotion/migemo/utf8.vim
 88: /usr/share/vim/vim82/autoload/dist/ft.vim
 89: ~/.vim/plugged/vimtex/ftplugin/tex.vim
 90: ~/.vim/plugged/vimtex/autoload/vimtex.vim
 91: ~/.vim/plugged/vimtex/autoload/vimtex/options.vim
 92: ~/.vim/plugged/vimtex/autoload/vimtex/util.vim
 93: ~/.vim/plugged/vimtex/autoload/vimtex/state.vim
 94: ~/.vim/plugged/vimtex/autoload/vimtex/re.vim
 95: ~/.vim/plugged/vimtex/autoload/vimtex/parser.vim
 96: ~/.vim/plugged/vimtex/autoload/vimtex/parser/tex.vim
 97: ~/.vim/plugged/vimtex/autoload/vimtex/cache.vim
 98: ~/.vim/plugged/vimtex/autoload/vimtex/paths.vim
 99: ~/.vim/plugged/vimtex/autoload/vimtex/view.vim
100: ~/.vim/plugged/vimtex/autoload/vimtex/view/zathura.vim
101: ~/.vim/plugged/vimtex/autoload/vimtex/view/common.vim
102: ~/.vim/plugged/vimtex/autoload/vimtex/compiler.vim
103: ~/.vim/plugged/vimtex/autoload/vimtex/compiler/latexmk.vim
104: ~/.vim/plugged/vimtex/autoload/vimtex/qf.vim
105: ~/.vim/plugged/vimtex/autoload/vimtex/qf/latexlog.vim
106: ~/.vim/plugged/vimtex/autoload/vimtex/toc.vim
107: ~/.vim/plugged/vimtex/autoload/vimtex/fold.vim
108: ~/.vim/plugged/vimtex/autoload/vimtex/fold/envs.vim
109: ~/.vim/plugged/vimtex/autoload/vimtex/fold/cmd_single_opt.vim
110: ~/.vim/plugged/vimtex/autoload/vimtex/fold/markers.vim
111: ~/.vim/plugged/vimtex/autoload/vimtex/fold/preamble.vim
112: ~/.vim/plugged/vimtex/autoload/vimtex/fold/sections.vim
113: ~/.vim/plugged/vimtex/autoload/vimtex/fold/cmd_addplot.vim
114: ~/.vim/plugged/vimtex/autoload/vimtex/fold/env_options.vim
115: ~/.vim/plugged/vimtex/autoload/vimtex/fold/cmd_multi.vim
116: ~/.vim/plugged/vimtex/autoload/vimtex/fold/items.vim
117: ~/.vim/plugged/vimtex/autoload/vimtex/fold/cmd_single.vim
118: ~/.vim/plugged/vimtex/autoload/vimtex/context.vim
119: ~/.vim/plugged/vimtex/autoload/vimtex/context/cite.vim
120: ~/.vim/plugged/vimtex/autoload/vimtex/parser/fls.vim
121: ~/.vim/plugged/vimtex/autoload/vimtex/bib.vim
122: ~/.vim/plugged/vimtex/autoload/vimtex/cmd.vim
123: ~/.vim/plugged/vimtex/autoload/vimtex/complete.vim
124: ~/.vim/plugged/vimtex/autoload/vimtex/debug.vim
125: ~/.vim/plugged/vimtex/autoload/vimtex/delim.vim
126: ~/.vim/plugged/vimtex/autoload/vimtex/doc.vim
127: ~/.vim/plugged/vimtex/autoload/vimtex/echo.vim
128: ~/.vim/plugged/vimtex/autoload/vimtex/env.vim
129: ~/.vim/plugged/vimtex/autoload/vimtex/format.vim
130: ~/.vim/plugged/vimtex/autoload/vimtex/fzf.vim
131: ~/.vim/plugged/vimtex/autoload/vimtex/imaps.vim
132: ~/.vim/plugged/vimtex/autoload/vimtex/include.vim
133: ~/.vim/plugged/vimtex/autoload/vimtex/info.vim
134: ~/.vim/plugged/vimtex/autoload/vimtex/kpsewhich.vim
135: ~/.vim/plugged/vimtex/autoload/vimtex/log.vim
136: ~/.vim/plugged/vimtex/autoload/vimtex/matchparen.vim
137: ~/.vim/plugged/vimtex/autoload/vimtex/syntax.vim
138: ~/.vim/plugged/vimtex/autoload/vimtex/pos.vim
139: ~/.vim/plugged/vimtex/autoload/vimtex/misc.vim
140: ~/.vim/plugged/vimtex/autoload/vimtex/motion.vim
141: ~/.vim/plugged/vimtex/autoload/vimtex/process.vim
142: ~/.vim/plugged/vimtex/autoload/vimtex/profile.vim
143: ~/.vim/plugged/vimtex/autoload/vimtex/scratch.vim
144: ~/.vim/plugged/vimtex/autoload/vimtex/text_obj.vim
145: ~/.vim/plugged/vimtex/autoload/vimtex/ui.vim
146: ~/.vim/plugged/vimtex/autoload/vimtex/text_obj/targets.vim
147: /usr/share/vim/vim82/ftplugin/tex.vim
148: ~/.vim/plugged/vimtex/after/ftplugin/tex.vim
149: ~/.vim/plugged/vimtex/indent/tex.vim
150: /usr/share/vim/vim82/indent/tex.vim
151: ~/.vim/plugged/vimtex/syntax/tex.vim
152: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/core.vim
153: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/nested.vim
154: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/packages.vim
155: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/p/url.vim
156: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/p/hyperref.vim
157: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/p/amsmath.vim
158: /usr/share/vim/vim82/syntax/tex.vim
159: ~/.vim/plugged/vim-airline/autoload/airline/extensions.vim
160: ~/.vim/plugged/vim-airline/autoload/airline/extensions/quickfix.vim
161: ~/.vim/plugged/vim-airline/autoload/airline/extensions/netrw.vim
162: ~/.vim/plugged/vim-airline/autoload/airline/extensions/term.vim
163: ~/.vim/plugged/vim-airline/autoload/airline/section.vim
164: ~/.vim/plugged/vim-airline/autoload/airline/highlighter.vim
165: ~/.vim/plugged/vim-airline/autoload/airline/extensions/undotree.vim
166: ~/.vim/plugged/vim-airline/autoload/airline/extensions/hunks.vim
167: ~/.vim/plugged/vim-airline/autoload/airline/extensions/csv.vim
168: ~/.vim/plugged/vim-airline/autoload/airline/extensions/coc.vim
169: ~/.vim/plugged/vim-airline/autoload/airline/extensions/whitespace.vim
170: ~/.vim/plugged/vim-airline/autoload/airline/extensions/po.vim
171: ~/.vim/plugged/vim-airline/autoload/airline/extensions/wordcount.vim
172: ~/.vim/plugged/vim-airline/autoload/airline/extensions/tabline.vim
173: ~/.vim/plugged/vim-airline/autoload/airline/extensions/tabline/autoshow.vim
174: ~/.vim/plugged/vim-airline/autoload/airline/extensions/tabline/tabs.vim
175: ~/.vim/plugged/vim-airline/autoload/airline/extensions/tabline/buffers.vim
176: ~/.vim/plugged/vim-airline/autoload/airline/extensions/gutentags.vim
177: ~/.vim/plugged/vim-airline/autoload/airline/extensions/keymap.vim
178: ~/.vim/plugged/vim-airline/autoload/airline/extensions/vimtex.vim
179: ~/.vim/plugged/vim-airline/autoload/airline/extensions/searchcount.vim
180: ~/.vim/plugged/awesome-vim-colorschemes/autoload/airline/themes/oceanicnext.vim
181: ~/.vim/plugged/vim-airline/autoload/airline/themes.vim
182: ~/.vim/plugged/vim-airline/autoload/airline/builder.vim
183: ~/.vim/plugged/vim-airline/autoload/airline/extensions/wordcount/formatters/default.vim
184: ~/.vim/plugged/vim-airline/autoload/airline/extensions/default.vim
185: ~/.vim/plugged/vim-gutentags/autoload/gutentags.vim
186: ~/.vim/plugged/vim-hexokinase/autoload/hexokinase/v2/scraper.vim
187: ~/.vim/plugged/vim-hexokinase/autoload/hexokinase/utils.vim
188: ~/.vim/plugged/LeaderF/autoload/lfMru.vim
189: ~/.vim/plugged/vim-which-key/autoload/which_key.vim
190: ~/.vim/plugged/vim-airline/autoload/airline/extensions/tabline/ctrlspace.vim
191: ~/.vim/plugged/vim-airline/autoload/airline/extensions/tabline/tabws.vim
192: ~/.vim/plugged/vim-airline/autoload/airline/extensions/tabline/builder.vim
193: ~/.vim/plugged/vim-airline/autoload/airline/extensions/tabline/buflist.vim
194: ~/.vim/plugged/vim-devicons/autoload/airline/extensions/tabline/formatters/webdevicons.vim
195: ~/.vim/plugged/vim-airline/autoload/airline/extensions/tabline/formatters/default.vim
196: ~/.vim/plugged/vim-hexokinase/autoload/hexokinase/highlighters/backgroundfull.vim
197: ~/.vim/plugged/coc.nvim/autoload/coc/api.vim
198: ~/.vim/plugged/coc.nvim/autoload/coc.vim
199: /tmp/vtmf3Rx/coc.nvim-8259/coc-8259.vim
200: ~/.vim/plugged/coc.nvim/autoload/coc/float.vim
```
I also record the output when with `let g:vimtex_synatx_enable=0`, the main difference is lacking of  
```vim 
152: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/core.vim
153: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/nested.vim
154: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/packages.vim
155: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/p/url.vim
156: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/p/hyperref.vim
157: ~/.vim/plugged/vimtex/autoload/vimtex/syntax/p/amsmath.vim
```
I seems normal.
3. The repo is old, only the vimrc file is new.  All the .vim folder is too large over then 150M, sad

**Comment by lervag** [comment]
Ok. I'm sorry, but I can't see what is wrong. Some thoughts:

* The problem you are describing is not a problem for me.
* You confirm that you can not reproduce the problem with a minimal vimrc.
* Thus: I am not able to reproduce the issue, which makes it close to impossible for me to find a solution.
* My only idea was to figure out what was wrong in your original vim config by i) inspecting your vimrc file, and ii) inspecting the output of `:scriptnames`. Neither of these actions have worked - I am still clueless to what is wrong.

So, my suggestion is that you do this; and regularly check if the snippet problem is present:

1. Start your vim configuration from a clean and empty vimrc file.
2. Add vim-plug and VimTeX with VimTeX configuration.
3. Add UltiSnips and snippets. This is the first time you can test for the problem; we are basically at a "minimal vimrc".
4. Now add your general vim configuration; i.e. options and mappings. Nothing related to more plugins yet, just regular Vim config. Test again.
5. Now add your remaining plugins; regularly test after adding a few plugins.

This procedure should allow you to figure out what is wrong.

**Comment by hanqing0521** [comment]
Ok, It is very hard to find the problem. There are so many plugins!  Now at least I can use the vimtex with vimtex_syntax_disable.

**Comment by lervag** [comment]
My suggested algorithm does not need to take so much time. But of course, you're free to do what you want :)

**Comment by L1szt** [comment]
@hanqing0521  have you found a solution?

**Comment by hanqing0521** [comment]
> @hanqing0521 have you found a solution?

Yes, it is a plugin conflict. The plugin rainbow ( a plugin for colorizing parenthesis) conflicts with vimtex mathzone

**Comment by lervag** [comment]
> Yes, it is a plugin conflict. The plugin rainbow ( a plugin for colorizing parenthesis) conflicts with vimtex mathzone

Let me know if you think there is something I can do to help make this work from the VimTeX side.

**Comment by hanqing0521** [comment]
> > Yes, it is a plugin conflict. The plugin rainbow ( a plugin for colorizing parenthesis) conflicts with vimtex mathzone
> 
> Let me know if you think there is something I can do to help make this work from the VimTeX side.

This plugin https://github.com/frazrepo/vim-rainbow . maybe is not important. There are many alternative rainbow plugins. I use https://github.com/luochen1990/rainbow, it works well with vimtex

**Comment by lervag** [comment]
Ok, thanks. At least useful to know for which plugin this does not work as intended.
