### ISSUE TITLE
Incorrect indentation of math blocks containing \iff

### ISSUE THREAD

**Issue by jordan-arenstein** [lervag/vimtex#2023]
**Issue**
When using a math block containing `\iff`, indenting the block using the `=` motion results in an increase of the indentation level for the rest of the document.

**minimal.tex**
```tex
\documentclass{minimal}
\begin{document}
\begin{equation}
ab = 0 \iff a = 0 \text{ or } b = 0
\end{equation}
\end{document}
```

**Commands/Input**
From the minimal.tex, select the entire file, and indent using `=`, and the final two lines are incorrectly indented.

**Observed Behaviour**
```tex
\documentclass{minimal}
\begin{document}
\begin{equation}
	ab = 0 \iff a = 0 \text{ or } b = 0
	\end{equation}
	\end{document}
```

**Expected Behaviour**
```tex
\documentclass{minimal}
\begin{document}
\begin{equation}
	ab = 0 \iff a = 0 \text{ or } b = 0
\end{equation}
\end{document}
```

**Output from VimtexInfo**
Run `:VimtexInfo` and paste the content here.
```
System info
  OS: macOS 11.3 (20E5172i)
  Vim version: NVIM v0.5.0-dev+370469be2
  Has clientserver: true
  Servername: /var/folders/_8/094zv34n46169ry2ym4xrh5m0000gn/T/nvimabGDN8/0

VimTeX project: test
  base: test.tex
  root: /Users/jordan/Desktop
  tex: /Users/jordan/Desktop/test.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file
  compiler: latexmk
    configuration: 
      continuous: v:true
      callback: v:true
      latexmk options:
        -verbose
        -file-line-error
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 69
    fix_paths: 70
    set_errorformat: 68
  document class: 
```

**Comment by jordan-arenstein** [comment]
I found a fix from https://github.com/lervag/vimtex/issues/1078. My bad!

**Comment by lervag** [comment]
Ah, you're the second that has made the same comment, so I think perhaps my suggested fix should be part of what I termed "sane defaults". I'm pushing that now. Thus, you and @clason no longer have to change the configs for this particular issue.

**Comment by jordan-arenstein** [comment]
Incredible! Thanks for pushing that out so quick!
