### ISSUE TITLE
vimtex_quickfix_ignore_filters

### ISSUE THREAD

**Issue by mivbvim** [lervag/vimtex#2024]
Hello,

I am a long time vimtex user and I love your plugin that I use all the time.

Today, I am making some update. Until now (I used an old version of the plugin), the quickfix list filter used the option `g:vimtex_quickfix_latexlog` .

Now, it changes to `g:vimtex_quickfix_ignore_filters`. I put the following into my `.vimrc`:

```vim
let g:vimtex_quickfix_ignore_filters = [
      \ 'Underfull',
      \ 'Overfull',
      \]
```

Unfortunately, it has no effect to the compilation. For example, I obtain in Quickfix list:

```
|597 warning| Overfull \hbox (9.86964pt too wide) in paragraph at lines 597--602
|24 warning| Underfull \hbox (badness 1308) in paragraph at lines 24--28
```

In fact, my previous settings were:

```vim
let g:vimtex_quickfix_ignore_all_warnings = 0
let g:vimtex_quickfix_latexlog = {
      \ 'default' : 1,
      \ 'general' : 1,
      \ 'references' : 1,
      \ 'overfull' : 0,
      \ 'underfull' : 0,
      \ 'font' : 1,
      \ 'packages' : {
      \   'default' : 0,
      \   'general' : 0,
      \   'babel' : 1,
      \   'biblatex' : 1,
      \   'fixltx2e' : 1,
      \   'hyperref' : 1,
      \   'natbib' : 1,
      \   'scrreprt' : 1,
      \   'titlesec' : 0,
      \ },
      \}
```

Maybe do you have an idea how to configure `g:vimtex_quickfix_ignore_filters` to have the same behavior as the previous one?

Thank a lot for your help!

**Comment by lervag** [comment]
> I am a long time vimtex user and I love your plugin that I use all the time.

Happy to hear it!

> Today, I am making some update. Until now (I used an old version of the plugin), the quickfix list filter used the option `g:vimtex_quickfix_latexlog` .

Could you provide some more details:

* OS
* Vim or neovim version
* VimTeX Git hash (`cd /path/to/vimtex; git show`)

> Now, it changes to `g:vimtex_quickfix_ignore_filters`. I put the following into my `.vimrc`:
> 
> ```viml
> let g:vimtex_quickfix_ignore_filters = [
>       \ 'Underfull',
>       \ 'Overfull',
>       \]
> ```

That's strange. This configuration works as expected on my end. Can you please provide a minimal example, or, at least the details of your current config?

**Comment by mivbvim** [comment]
Thank you for your answer !

OS: ubuntu 20.04
vim: version 8.2.1897
vimtex: commit 5f94ff53c166095968c4ba4a48e84d506aeb06a3 (grafted, HEAD -> master, origin/master, origin/HEAD

Following what you say, I tried with a minimal vimrc, and it works. After study more precisely my .vimrc, the problem seems coming from a conflict with the plugin

Plug 'romainl/vim-qf'

( https://github.com/romainl/vim-qf )

This is strange. Probably this plugin modifies the quickfix list properties... Anyway, even I like vim-qf, to make latex in good condition is more important for me. Then I probably will remove this plugin.

Best, and thank again for your work.

**Comment by lervag** [comment]
Ah, yes, that probably explains it. There's a related issue:

https://github.com/romainl/vim-qf/issues/69

**Comment by lervag** [comment]
Note that you can use vim-qf with VimTeX today if you have `let g:qf_auto_open_quickfix = 0` in your vimrc.

**Comment by L1szt** [comment]
@lervag Could you explain me how I can disable all vimtex warnings? They become really annoying when working on a smaller display. Thanks in advance!

**Comment by lervag** [comment]
You could use `let g:vimtex_quickfix_open_on_warning = 0`; perhaps that's sufficient? Or you could add regexes to the `g:vimtex_quickfix_ignore_filters` list.

**Comment by L1szt** [comment]
@lervag I have already tried out the first option but there are still warnings. Is there some other way than adding all warning separately via regex, like some option that disables all warnings?

**Comment by lervag** [comment]
Yes, the first option only specifies whether the quickfix list should open if there are only warnings, it does not filter the warnings. The `...ignore_filters` option can be used to ignore warnings _and_ errors, and so it does not really allow a simple way to ignore all warnings.

Could you open a new issue/feature request for this, so that we can avoid disturbing this thread any further?
