### ISSUE TITLE
Alignment tab removal when switching environments

### ISSUE THREAD

**Issue by antimike** [lervag/vimtex#2028]
## Suggested improvement ("what")
Provide support for automatically removing alignment characters ('&') when switching from aligned math environments to non-aligned ones (e.g., `\begin{align*} ... \end{align*}` to `\begin{gather*} ... \end{gather*}`).

## Background ("why")
I use Vimtex for taking notes, and as such it's often the case that I don't anticipate which math environment is most suited to an equation when I start typing it.  When this is the case, I use Vimtex's "environment" textobject to change the environment (e.g., `cse`).  Of course, this causes problems when switching from an aligned environment to a non-aligned one like `equation` or `gather`, and when live-TeXing, the resulting compilation issues cause annoying lags and the appearance of a scratch-buffer of sadness.  

I'm thinking it should be relatively easy to add either an option or a keybinding for automatic alignment character removal, and if so then it would probably be worthwhile.

**Comment by lervag** [comment]
Thanks; I can see how what you want can be convenient in your workflow. However, I don't see how this can be implemented as an elegant solution within VimTeX.

To remove ampersands, you could do something like this:

1. `vie`
2. `:s/&//`

This can be combined into a single mapping, e.g.

```vim
nmap <localleader>lda vie:s/&//<cr>

" also remove preceding spaces
nmap <localleader>lda vie:s/\s*&//<cr>
```

I would put such a mapping in a personal `ftplugin/tex.vim`, e.g. under `.vim/ftplugin/tex.vim`, as this ensures the mapping is only defined for LaTeX files.

**Comment by lervag** [comment]
However, one idea that comes to mind: I could add an event after `cse` that you could hook into. I'm not sure how useful this is, but it could allow something like this:

```vim
augroup vimtex_events
  au!
  au User VimtexEventEnvChange call RemoveAmps()
augroup END

function! RemoveAmps()
  if b:_envs.old ==# 'align' && b:_envs.new ==# 'gather'
    normal vie:s/&//
  endif
endfunction
```

I.e.: this could allow users to configure extra behaviour when changing between different environments. However, as said, I'm not sure how useful this really is. I would think not many people will use it.
