### ISSUE TITLE
Use tex2unicode for Bibtex completion suggestions

### ISSUE THREAD

**Issue by yagebu** [lervag/vimtex#203]
Bibtex can contain TeX code, for example to write some special characters. So it would be nice if those were converted to Unicode where possible for the completion suggestions. There is already the `tex2unicode` function in `complete.vim` so it shouldn't be hard to implement (but I couldn't get it to work...)

**Comment by lervag** [comment]
Thanks for the suggestion. It would help very much if you could give me an example case to work on. That is, a small bibtex file and a small tex file where the current implementation does not complete as you suggest.

I would also appreciate a somewhat more detailed explanation of what you are after. I think I understand, but I am not sure. For instance, I assume you don't want vimtex to actually change the bibtex file..?

**Comment by yagebu** [comment]
Sorry for being so short, I thought it would be easier to understand. It's only a small aesthetic issue, the completion works as expected.

With the following TeX file

    \bibliography{test}

and `test.bib`:

    @ARTICLE{ref,
      author = {N{\"o}me, Test},
      title = {Some title},
    }

the completion suggestion, by which I mean the text that is displayed to choose between different possible completions (I'm using YCM, so it's displayed as a popup under the cursor), reads `[a] N\"ome   Some title`. So I thought it would be nice to replace the `\"o` by `ö` in this text that is displayed. So you assume correctly, I don't intend for vimtex to actually change any bibtex files at all.

**Comment by lervag** [comment]
Try now. This required just a simple addition of the `s:tex2unicode` function, and it seems to give an improved bibtex completion experience.

Note that some people, e.g. myself, use unicode characters in bibtex files. This works nicely when you have `\usepackage[utf8]{inputenc}`.

**Comment by yagebu** [comment]
Perfect, thanks :smile:

Thanks for the tip, I actually try to use `utf-8` whenever possible, but when working together with other people, that's sadly not an option sometimes.

**Comment by lervag** [comment]
Great! And yes, good point; sometimes one can not choose freely.
