### ISSUE TITLE
Conceal support for more math text style commands

### ISSUE THREAD

**Issue by patricknraanes** [lervag/vimtex#2034]
As mentioned after resolution of #1972 I use `\mathds` to produce (e.g.) the double-struck 1, and would like to see it concealed. Seeing as this is a fairly common use case, I would say adding it to vimtex is reasonable. @lervag agrees that concealment for some more font style commands may be added. However, which ones to add? It's beyond me to firmly judge which ones are pertinent or frivolous, but the following lists those not already in vimtex that appear at the top of this popular stackexchange [answer](https://tex.stackexchange.com/questions/58098).

To be rendered in bold:
  - pmb
  - bm

To be rendered as double-struck
  - mathds
  - mathbbb
  - mathbbm
  - mathbbmss
  - mathbbmtt
  - varmathbb

To be rendered as Goth/Frak:
  - textfrak
  - textswab
  - textgoth

@lervag also mentioned that this might be activated upon availability of the corresponding package.

**Comment by lervag** [comment]
I've pushed an update that should solve at least your issue here. I did not consider `pmb`, `bm`, and the `text*` variants as of now, since I'm not sure if these are really of interest. Perhaps `bm` is; I can remember using it myself. But the other seems to be fringe commands?

**Comment by patricknraanes** [comment]
Sorry for the latency. I certainly never used the `text*` variants, but `bm` I use a lot. However, you probably have a better overview than I do on what's relevant.

**Comment by lervag** [comment]
Ah, yes, I've only added the double struck for alphabetic characters. I could add this also for the numbers - it is a trivial change. Will do it later  today.

**Comment by lervag** [comment]
Double struck should work with all letters (a-zA-Z) and numbers (0-9) now.
