### ISSUE TITLE
Add option to ignore regions

### ISSUE THREAD

**Issue by dalcde** [lervag/vimtex#2038]
**Is your feature request related to a problem? Please describe it.**
If catcodes of characters are modified, then the syntax highlighter gets confused and can potentially mis-highlight the rest of the document. For example, the snippet
```tex
\catcode`\$=11
$
\catcode`\$=3
```
will cause the rest of the document to be treated as being in math mode.

**Describe the solution you'd like**
A simple way to tell `vimtex` to ignore a region for the purposes of syntax highlighting. This can be triggered via comments and implemented in the same way as verbatim environments.

**Describe alternatives you've considered**
Correctly parsing the snippet will likely require reimplementing a good part of a TeX engine.

**Comment by lervag** [comment]
I've added a simple mechanism for this, see the docs under `:help vimtex-syntax`. Let me know what you think.

```tex
% VimTeX: SynIgnore on
\catcode`\$=11
$
\catcode`\$=3
% VimTeX: SynIgnore off
```
