### ISSUE TITLE
citation (bib(la)tex) suggestion/completion disappears

### ISSUE THREAD

**Issue by atticus-sullivan** [lervag/vimtex#2039]
**Issue**
When inserting `\cite{`, the available keys from the `.bib` are suggested. But when starting to type to narrow the keys, the completion menu vanishes.

This is a follow-up from [https://vi.stackexchange.com/questions/31129/coc-vimtex-bib-completion-strange-suggstions/31130#31130](https://vi.stackexchange.com/questions/31129/coc-vimtex-bib-completion-strange-suggstions/31130#31130), but I've messed up with the initial post (sorry @ lervag again).

**minimal.nvim**
```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'lervag/vimtex'
call plug#end()
```

**minimal.tex**
```tex
\documentclass{article}

\usepackage[backend=biber]{biblatex}
\addbibresource{testing.bib}

\begin{document}
\cite{k

\printbibliography
\end{document}
```

**Observed Behaviour**
Already described above. And see the demonstration:
![Peek 2021-04-29 22-27](https://user-images.githubusercontent.com/60581958/116614465-7e246600-a929-11eb-8a03-b447e6771596.gif)

**Expected Behaviour**
I'd expect that the menu stays visible and filters the entries by the text inserted.

**Output from VimtexInfo**
Note: shortened the paths
```
System info
  OS: Linux 5.10.32-1-lts
  Vim version: NVIM v0.4.4
  Has clientserver: true
  Servername: /tmp/nvimARV5QS/0

VimTeX project: testing
  base: testing.tex
  root: testing_biblatex/mfe
  tex: mfe/testing.tex
  out: mfe/testing.pdf
  log: testing_biblatex/mfe/testing.log
  aux: testing_biblatex/mfe/testing.aux
  fls: testing_biblatex/mfe/testing.fls
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 51
    fix_paths: 52
    set_errorformat: 50
  document class: article
  packages:
    biblatex
    etoolbox
    expl3
    iftex
    ifthen
    infwarerr
    keyval
    kvoptions
    kvsetkeys
    logreq
    ltxcmds
    pdftexcmds
    url
    xparse
```

**Comment by lervag** [comment]
Thanks for the issue report.

Before I try to reproduce this, I have a couple of minor comments:

* I've simplified your minimal vimrc file (note that you don't need `g:tex_flavor`). Can you test again with the simplified file?
* There is no VimTeX option named `g:vimtex_complete_bib_simple`. I've updated your minimal vimrc to fix that - but I wonder if you want and/or need that option?

**Comment by lervag** [comment]
Also, as you probably understand, `coc.nvim` is implicitly loading a bunch of extensions. Can you list the extensions you have installed and perhaps remove every extension that is not relevant? I propose that you uninstall all extensions first, then reinstall coc-vimtex and test again. Let me know if you can still reproduce the issue.

**Comment by atticus-sullivan** [comment]
> Note that the option g:vimtex_complete_bib.simple is 0 by default, in case that was the option you wanted to disable.
Yes I thought maybe this defaulted to the wrong value and this would be part of the issue I'm having (but anyway yes this was a typo in the option name)

The extensions I had installed were `coc-calc`, `coc-clangd`, 'coc-marketplace', `coc-pyright`, `coc-ultisnips` and of course `coc-vimtex`.
Now I had all coc extensions removed and using the really minimal `.vimrc`, but sadly the issue remains.

**Comment by lervag** [comment]
Ah, yes, sorry, I was also confused myself.

**Comment by lervag** [comment]
Sorry, I posted the reply before I was finished writing. So, the point is, as the docs say: When you want to use an autocomplete engine such as coc.nvim, it is better to use the simple option, so:

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_complete_bib = {'simple' : 1}
```

This should work better and more as expected, I think. Please test.

**Comment by atticus-sullivan** [comment]
Yes now searching in the keys works. Thanks
