### ISSUE TITLE
Support for texfot tool

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2041]
It would be really nice to have native/automatic support for the [`texfot`](https://ctan.org/pkg/texfot) filtering tool within vimtex. 

texfot describes itself as:
>The package provides a small Perl script to filter the online output from a TeX run, attempting to show only those messages which probably deserve some change in the source. The TeX invocation itself need not change. 

and its PDF documentation is quite short at just 3 pages. 

The tool is cross-platform since it requires only perl as its only dependency. Windows users already use perl with a standard tex installation anyway to run various tools such as texcount, latexmk, latexfmt etc.

This tool is written by none other than Karl Berry himself, a famous TeXian with a myriad of contributions to the LaTeX kernel and with a high reputation in TUG circles.

**Comment by clason** [comment]
If it's just filtering, wouldn't it be enough to simply add it to your `.latexmkrc`?

**Comment by krishnakumarg1984** [comment]
Yes. But texfot can do a lot more! Plus no need to customise latexmkrc for every project. Also, what if you are running arara instead?

 Have a look at the texfot tool. The doc is just 3 pages long.

**Comment by lervag** [comment]
@krishnakumarg1984 Thanks, it looks like an interesting tool. Could you explain _how_ you think a native/automatic support for texfot in VimTeX should look like? I.e., what needs to change? Which new options do we need? How would you want this to work, specifically?

**Comment by krishnakumarg1984** [comment]
I would like vimtex to automatically call texfot if it is installed and available. This way the latex log file to be parsed by pplatex is much cleaner!

**Comment by clason** [comment]
texfot doesn't filter the log file, only the console output!

**Comment by krishnakumarg1984** [comment]
Sorry my bad. I meant console output, since vimtex, specifically with pplatex, reads in the console output to populate the quickfixlist.

**Comment by lervag** [comment]
Yes, @clason is right. Both `pplatex` and the current system for parsing errors warnings are based on the log file, not on the console output. Thus, filtering to improve the console output would not immediately work. So, to use `texfot` in this context, it seems we need to use it to filter the log file. Is that possible?

**Comment by lervag** [comment]
By the way, VimTeX uses `pplatex` directly on the log file, not on the console output, so VimTeX does not use pplatex to parse errors from console output.

**Comment by krishnakumarg1984** [comment]
From reading the [pplatex ](https://github.com/stefanhepp/pplatex) documentation, it looks like it reads the log file of a tex run to produce human readable errors to the stdout.  Is that incorrect?

**Comment by lervag** [comment]
No, but how does texfot fit into that? texfot is used to filter the output of `pdflatex` (and similar). Note: I'm asking because I don't know myself, I've never used texfot. Perhaps you could show some examples of how this works in a console session?

**Comment by krishnakumarg1984** [comment]
Hmm, I see. Karl Berry writes in the package's documentation specifically about this difference of parsing console output vs log file:

>I found some other programs of a similar nature, the LaTeX package silence, and plenty of other (La)TeX wrappers, but it seemed none of them did what I wanted.  Either they read the log file (I wanted the online output only), or they output more or less than I wanted, or they required invoking TeX differently (I wanted to keep my build process exactly the same, most critically theTeX invocation, which can get complicated).  Hence I wrote this.

**Comment by clason** [comment]
Exactly:

* `pplatex` filters _after_ a run (to produce concise, readable console output from the log file; used by running `pplatex foo` instead of `pdflatex foo`);
* `texfot` filters _during_ a run (to remove "unneeded" console output; used by running, e.g., `texfot pdflatex foo`).

Since vimtex never shows console output during a run, it's not clear how it would profit from the latter.

**Comment by clason** [comment]
Here's a sample output from `texfot pdflatex foo`:
```
/usr/local/texlive/2021/bin/universal-darwin/texfot: invoking: pdflatex foo
This is pdfTeX, Version 3.141592653-2.6-1.40.22 (TeX Live 2021) (preloaded format=pdflatex)
Package hyperref Warning: Unexpected value for option `hidelinks'
Underfull \hbox (badness 1052) in paragraph at lines 167--167
Underfull \hbox (badness 2269) in paragraph at lines 167--167
Underfull \vbox (badness 2426) has occurred while \output is active [2296]
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `math shift' on input line 607.
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `math shift' on input line 607.
Overfull \hbox (0.79645pt too wide) in paragraph at lines 914--926
Overfull \hbox (0.77428pt too wide) in paragraph at lines 1089--1092
Overfull \hbox (9.1222pt too wide) in paragraph at lines 1187--1188
Overfull \hbox (0.29013pt too wide) detected at line 1306
Overfull \hbox (3.78539pt too wide) in paragraph at lines 1513--1517
Underfull \vbox (badness 2626) has occurred while \output is active [2319]
Underfull \vbox (badness 4621) has occurred while \output is active [2321 <./Fi
Underfull \vbox (badness 10000) has occurred while \output is active [2322 <./F
Underfull \vbox (badness 10000) has occurred while \output is active [2327]
Underfull \hbox (badness 1087) in paragraph at lines 2210--2212
Output written on foo.pdf (34 pages, 987017 bytes).
```

**Comment by lervag** [comment]
I don't see how to fit this into VimTeX in a natural manner. For me, it seems it is more appropriate to configure your latexmk (or other backend) to use texfot; this would probably allow a cleaner output (that you can inspect with `:VimtexCompileOutput` or `\lo`) - but I don't see other benefits.

Feel free to suggest explain how it can fit. Perhaps I'm missing something?

**Comment by krishnakumarg1984** [comment]
Would VimTeX be able to: support a "meta" engine to the compiler backends like `latexmk` or `arara`? 

Option 1 is ideal for me. Here is the reason.  I am working on an ultra large tome, co-written with 21 others!  The publisher provides us with a private git repo, and tightly control the contents within key control files that can be committed (to be consistent with their internal production flow). They explicitly forbid updates to key files like `latexmkrc` and others, and have asked the authors to update only technical content, and that too only in plain text.  In fact, the authors need to run past their staff to even commit image files (which introduces 3 days of delay) for them to provide us with a (non) lossy compressed equivalent. Any other binary blobs are expressly forbidden.

Now, I'd like to typeset the whole book occasionally, but keep my log file clean and with minimum noise. With the `nag` and the `banned 2e` packages, the log file is getting filled up with ton of noise (like from raw/deprecated tex macros like `\it`, `\def` etc used by my co-authors from the pre-latex2e era). I know that the `silence` package can be used to help here, but the technical staff at the publisher told me that it is helpful for them to actually see the usage of old macros so that they can fix it during the final stages. They asked me to refrain from committing a preamble with the `silence` package in. 

At least for my local compiles, `texfot` shall be a Godsend if only I can get VimTex to play nicely with it. Yes, I can use `texfot` at the command-line, but then I lose the goodness of `latexmk` with the continuous compilation. Additionally, our `latexmkrc` also deals with perl functions to call indexing programs, glossary generators, generating figures by `asy` etc etc.  The convenience of having `vimtex` is unparalleled, with the quickfix support etc.

Even if it doesn't make it into official VimTeX, what's the best way to integrate `texfot` into my `latexmk` run without actually committing it to `latexmkrc`? Maybe local vimrc? But how?

**Comment by krishnakumarg1984** [comment]
Closing this since `texfot` only looks at the console output and VimTeX works only with log files for populating the `qf` list.

**Comment by lervag** [comment]
Thanks!
