### ISSUE TITLE
Conceal - mhequ

### ISSUE THREAD

**Issue by atropos112** [lervag/vimtex#2042]
**Is your feature request related to a problem? Please describe it.**
I am currently using a package from https://ctan.org/pkg/mhequ, well known by people within my research area. When I use $ $ to enter math-mode conceal works, the same is true with \begin{align} \end{align}. The mhequ package gives yet another environment namely \begin{equs} \end{equs} and within this environment conceal does not work at all.

**Describe the solution you'd like**
I'd like \begin{equs} \enq{equs} to conceal the same as if it was say \begin{align} \end{align}. Apart from the equation labeling equs and align are very similar.

**Describe alternatives you've considered**
I could use align but all my current collaborators are using equs and so most likely I would have to give up on the concealer. 

**Additional context**
I am guessing concealer doesn't know equs environment is a math-mode type of an environment.

**Comment by lervag** [comment]
The problem is not conceals, but that the environment is not recognized as a math environment.

**Comment by atropos112** [comment]
Thank you for you swift response ! Is there a way to add it as a math environment ?

**Comment by lervag** [comment]
Yes. I just did it :)

**Comment by lervag** [comment]
(I forgot to tag the commit, but if you update, it should work.)

**Comment by atropos112** [comment]
Legend, thank you !

**Comment by lervag** [comment]
No problem: glad to add support for more useful packages. :)
