### ISSUE TITLE
Syntax highlighting for \parbox

### ISSUE THREAD

**Issue by ji-cerny** [lervag/vimtex#2044]
It seems that the current syntax highlighting does not support \parbox command (which is very similar to \text). In the tex code below, "footext" is highlighted as a normal text but "fooparbox" as a formula.    

```tex
\documentclass{minimal}
\begin{document}
Hello world!
\begin{equation}
  \parbox{10cm}{fooparbox $bar$}
  \text{footext $bar$}
\end{equation}
\end{document}
```

**Comment by lervag** [comment]
It would be useful to get some more details on the `\parbox` command. Where does it come from? Documentation?

**Comment by ji-cerny** [comment]
It is a standard latex command, one does not need any package to use it. 
For documentation, see e.g. http://latexref.xyz/_005cparbox.html or https://en.wikibooks.org/wiki/LaTeX/Boxes#parbox,_minipage,_and_pbox

**Comment by lervag** [comment]
I've made a first attempt at support for this now, please test.

**Comment by ji-cerny** [comment]
It works very well. Thanks a lot for your fast help and for the great package.

**Comment by lervag** [comment]
Happy to hear it! :)
