### ISSUE TITLE
Bug in vimtex#parser#toc with \todo{...} commands with odd contents

### ISSUE THREAD

**Issue by hwagyesa** [lervag/vimtex#2045]
Hi, I encountered a bug with vimtex's toc parser which I think I managed to trace to some 'oddly'-formatted `\todo{...}` entries in my document. Since the code compiles fine on the LaTeX side, I guess this is an issue with the parser.

## Issue
I created some complicated `\todo{...}` commands that contained an enumerate environment -- this compiles and displays fine in the LaTeX document, although it is obviously not very useful for display in the vimtex toc. A MWE of the setup is below.

```tex
\documentclass{article}

\usepackage{lipsum}
\usepackage{xcolor}

\newcommand{\todo}[1]{{\color{red}{\bf TODO: #1}}}

\begin{document}

\todo{Fix these things:
\begin{enumerate}
  \item abc
  \item def
\end{enumerate}
}

\lipsum

\end{document}
```

With this `\todo{...}` command in the document, the toc will not generate correctly -- I will observe an error `E734: Wrong variable type for .=` when e.g. pressing r to refresh in the vimtex toc window. A consequence in more complicated documents is that as soon as vimtex hits the offending `\todo{...}` command, it will be unable to continue generating the toc for the rest of the document, so the toc will display incomplete in the vimtex toc window.

## Fix?
Sorry, I didn't dig into the vimtex#parser#toc code to see what might have caused the error, but I guess there is an assumption being made about the kinds of inputs that will be received that is violated by `\todo{...}` commands of the type in my MWE above.

**Comment by lervag** [comment]
> Hi, I encountered a bug with vimtex's toc parser which I think I managed to trace to some 'oddly'-formatted \todo{...} entries in my document. Since the code compiles fine on the LaTeX side, I guess this is an issue with the parser.

There's always bugs abound :p

> # Issue
> ...
> With this \todo{...} command in the document, the toc will not generate correctly -- I will observe an error `E734: Wrong variable type for .=` when e.g. pressing r to refresh in the vimtex toc window.

I'm sorry, but I can't reproduce this on my end. Can you provide a minimal vimrc file as well?

**Comment by hwagyesa** [comment]
Sorry to waste your time -- after I updated vimtex to the latest version, the issue went away! I guess this issue was fixed at some time in the past. Thanks!

**Comment by lervag** [comment]
No problem, I'm happy it's sorted out :)
