### ISSUE TITLE
Text Objects always ending one character

### ISSUE THREAD

**Issue by huweiATgithub** [lervag/vimtex#2047]
**Issue**
Tried commands, environments, delimiters, math, item objects

all work but missing the final character. For example, va$ for the following text:
$a+b=c$
the final '$' is not selected. 

BTW, vam works as expected.

Vimtex is installed via Vim-Plug on Windows 10 with VIM 8.2 

Is this a feature or there is some setting to be tuned?

**Comment by lervag** [comment]
Not a feature, just Vim on Windows that misbehaves. See `:help vimtex-troubleshooting` and the section about text objects on Windows.
