### ISSUE TITLE
Buggy custom conceal due to inner command

### ISSUE THREAD

**Issue by patricknraanes** [lervag/vimtex#2048]
I take advantage of [this feature](https://github.com/lervag/vimtex/issues/1972) by using:

```vim
" ~/.vim/syntax/tex.vim:
setlocal conceallevel=2
let g:vimtex_syntax_custom_cmds = [{'name': 'keyw', 'mathmode': 0, 'argstyle': 'boldital' , 'conceal': 1}]
```

This should conceal `\keyw` in the following:
```tex
% test.tex
\documentclass[a4paper]{article}
\begin{document}
\keyw{Piecewise \textbf{test} splines}
\end{document}
```

Unfortunately, the presence of ` \textbf{test}` messes up the concealment, as seen in the screenshot
![Screenshot from 2021-05-12 15-33-44](https://user-images.githubusercontent.com/7222967/117983665-74dac680-b337-11eb-91bd-980ff786243b.png)

I have used the standard `minimal.vim` for testing.

**Comment by lervag** [comment]
I think it's fixed now, please test. I believe the fix should not have any side effects. Let me know if I'm wrong... :)
