### ISSUE TITLE
How to customize the compilation order？

### ISSUE THREAD

**Issue by Beau-Yang** [lervag/vimtex#2049]
When it comes to citing documents, tex documents need to be compiled in a certain order using different engines. For example, I want to cite the documents recorded in the `.bib` file and I need to compile the tex file in the order `XeLaTex->BibTex->XeLaTex->XeLaTex` otherwise the reference number will not be displayed normally. How should I edit the `.vimrc` file to achieve that given that I fail to find relevant instructions in the documentation? Thanks in advance.

Here's my current `.vimrc` file:
```
Plug 'lervag/vimtex'
       let g:tex_flavor='latex'
       let g:vimtex_quickfix_mode=0
       let g:vimtex_view_general_viewer = 'okular'
       let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
       let g:vimtex_view_general_options_latexmk = '--unique' 
```

**Comment by lervag** [comment]
> How should I edit the `.vimrc` file to achieve that given that I fail to find relevant instructions in the documentation? Thanks in advance.

VimTeX relies on a build tool like latexmk (default), which should do exactly this. It works very well, in my experience. However, if you use XeLaTeX, then you must make sure that VimTeX/latexmk is aware of it. There are several ways to do this:

1. Use a directive comment, see `:help vimtex-tex-program`.
2. Change the default TeX program with e.g. `g:vimtex_compiler_latexmk_engines`:
   ```vim
   let g:vimtex_compiler_latexmk_engines = {'_': '-xelatex'}
   ```
3. Use `.latexmkrc` or `~/.latexmkrc` (see the latexmk manual for details).

> Here's my current `.vimrc` file: ...

You can safely remove the `g:tex_flavor`.
