### ISSUE TITLE
synctex not working on OS X with zathura viewer

### ISSUE THREAD

**Issue by thewilli** [lervag/vimtex#205]
I'm using zathura 0.3.3 (with pdf-mupdf), vimtex 1823ee60b6, Vim 7.4 and OS X Yosemite. 

my ~/.latexmkrc:
> $pdf_mode = 1;
> $pdflatex = 'pdflatex --shell-escape -synctex=1 -interaction=nonstopmode %O %S';

and I added
> let g:vimtex_view_method = "zathura"

to my ~/.vimrc

After executing `VimtexCompileToggle` the TeX file is compiled correctly and opened in zathura. Whenever I change something, the document is recompiled, and zathura refreshes itself. Unfortunately neither forward nor inverse search work, and after changing some content, zathura does not go to the current position. 

When I run `VimtexView` a new zathura instance is opened, but it still does not point to the current cursor location.

Do you have any idea what the problem might be?

**Comment by lahwaacz** [comment]
The docs [say](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L712), that `xdotool` is required for forward search. Do you have it installed?

**Comment by thewilli** [comment]
> The docs say, that xdotool is required for forward search. Do you have it installed?

yes, sorry, I forgot to mention this

**Comment by lervag** [comment]
I think this issue may be the same as #205. I'll therefore continue the issue there. If I'm mistaken, then please reopen.
