### ISSUE TITLE
Sumatra not detected

### ISSUE THREAD

**Issue by bongbang** [lervag/vimtex#2050]
SumatraPDF is installed on my computer for all users and Vimtex had no problem working with it until an issue with Windows update forced me to start a new user account and migrate. Now Vimtex doesn't seem to detect Sumatra. When I do `<leader>lv`, a command prompt opens in the directory. If I force the issue with the following line:

`let g:vimtex_view_general_viewer = 'SumatraPDF'`

then I get the error message: "Selected viewer is not executable". Is there a simple way I can get Vimtex (up-to-date as of this writing) to find Sumatra? I wanted to try what I can before reinstalling, because I had to do a bit of work to get reverse search to work last time around.

**Comment by bongbang** [comment]
It works now after adding Sumatra's directory to the path. It was likely in the old user profile's path instead of the system's, which wouldn't work with a new profile.

**Comment by lervag** [comment]
Yes, that makes sense. I was going to ask you to test if SumatraPDF was available in your PATH. :)
