### ISSUE TITLE
Beamer: no folding for notes

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#2051]
**Issue**
Whereas `\frame` environment folds perfectly accompanying `\note` environment doesn't fold at all.

See example:
![2021-05-17-194607_550x253_scrot](https://user-images.githubusercontent.com/146893/118526087-8ca3b780-b748-11eb-8b7a-c8bda1950081.png)

About [Beamer](https://en.wikipedia.org/wiki/Beamer_(LaTeX))

> Beamer is a LATEX class for creating presentations that are held using a projector, but it can also be used to create transparency slides. 
 
From [Beamer docs](http://tug.ctan.org/macros/latex/contrib/beamer/doc/beameruserguide.pdf):

> A `note` is text that is intended as a reminder to yourself of what you should say or should keep in mind when presenting a  slide. Notes are usually printed out on paper, but with two-screen support they can also be shown on your laptop screen while the main presentation is shown on the projector.

* Regular Vim: `vim --servername VIM -u minimal.vim minimal.tex`
* neovim: `nvim -u minimal.vim minimal.tex`

**minimal.vim**
```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
let g:vimtex_fold_enabled = 1
syntax enable
```

**minimal.tex**
```tex
\documentclass[notes=hide]{beamer}
\begin{document}
\begin{frame}
    Frame content
\end{frame}
\note{
    Note content
}
\end{document}
```

NB: If relevant, include the content of your `.latexmkrc` file!

**Commands/Input**
Provide set of keys or command to reproduce the issue.

**Observed Behaviour**
`\note` doesn't fold

**Expected Behaviour**
`\note` folds

**Output from VimtexInfo**
Run `:VimtexInfo` and paste the content here.

```
System info
  OS: Arch Linux
  Vim version: VIM 8.2 (1-2859)
  Has clientserver: true
  Servername: VIM2

VimTeX project: minimal
  base: minimal.tex
  root: /home/user/minimal
  tex: /home/user/minimal/minimal.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      build_dir: build/
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 51
    fix_paths: 52
    set_errorformat: 50
  document class: beamer
```

**Comment by lervag** [comment]
> **Expected Behaviour**
> `\note` folds

There is nothing "special" about the `\note` command, and so I believe it does not deserve a special treatment. But it seems like the `\note` command is generally very simple and takes a single command, and there is already a fold type for this. See `:help g:vimtex_fold_types` and take not of the `cmd_single` fold type. The docs may be overly complicated on this point; I'm sorry about that. The following minimal vimrc file should solve your problem while keeping the default folded (simple) command set.

```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_fold_enabled = 1
let g:vimtex_fold_types = {
       \ 'cmd_single' : {
       \   'cmds' : [
       \     'hypersetup',
       \     'tikzset',
       \     'pgfplotstableread',
       \     'lstset',
       \     'note',
       \   ],
       \ },
       \}
```
