### ISSUE TITLE
let `texMathZones` ignore the zone before `\begin{document}`

### ISSUE THREAD

**Issue by Edenharder** [lervag/vimtex#2052]
**Describe the bug**
It seems that some function like `texMathZones` in `vimtex` takes the zone before `\begin{document}` also into consideration. This is unnecessary and causes problem sometimes.
**To Reproduce**
For example,  
```
\documentclass{article}
\usepackage{array}
\newcolumntype{C}{>{$}c<{$}} %1
\begin{document}
$This part is detected as not texMathZones$ %2
This part is detected as texMathZones %3
\end{document}
```
With `vimtex` on, the line `%1` contains `$`, and it is before the beginning of the document. Then the part between the two `$` in place `%2`has not been detected as `texMathZones`. Instead, the part in place `%3`, which should not be a `texMathZones`, is detected as `texMathZones`.

With `vimtex` off, everything is correct.

**Expected behavior**
The function like `texMathZones` in `vimtex` should ignore the zone before the beginning of the document.

**Environment (please complete the following information):**
 - Vim version 8.2

Related issue: [let `texMathZones` ignore the zone before `\begin{document}`](https://github.com/vim/vim/issues/8228)

**Comment by lervag** [comment]
Thank you; this does reveal a bug. I think it is fixed now, please test.

**Comment by Edenharder** [comment]
Thank you! It works.

**Comment by lervag** [comment]
Happy to hear it :)
