### ISSUE TITLE
Question: Is there an option to make the quickfix list toggle only on demand?

### ISSUE THREAD

**Issue by brymer-meneses** [lervag/vimtex#2053]
I get slightly bugged whenever the quickfix list toggles each time I save and compile my tex file. Is there an option to make it so that I can only toggle it on demand perhaps using my own keybinding?

**Comment by lervag** [comment]
Yes, see `:help g:vimtex_quickfix_mode` (you probably want to set it to 0).

**Comment by lervag** [comment]
Yes, see `:help g:vimtex_quickfix_mode` (you probably want to set it to 0).

**Comment by brymer-meneses** [comment]
@lervag what command do I have to execute to open the quickfix list?

**Comment by lervag** [comment]
`:VimtexErrors` (see `:help :VimtexErrors` for more info). By default, it is mapped to `\le`.

**Comment by brymer-meneses** [comment]
Thank you!

**Comment by lervag** [comment]
Glad to hear it helps. Sorry for the short answers, I replied while not having the time to fill out the details. I suggest you read the docs on the various quickfix options, see `:help vimtex_quickfix_enabled` and the following parts.
