### ISSUE TITLE
Typing a grave accent '`' requires two key presses

### ISSUE THREAD

**Issue by johngodlee** [lervag/vimtex#2054]
In insert mode, typing \` (grave accent) results in a short delay before the cursor moves to the right side of the grave accent to allow typing a second grave accent. Typing two grave accents as the markup for double opening quotes therefore requires three keypresses, two to insert the first grave accent and one to insert the second.

Is it possible to disable this behaviour so a grave accent is treated as a normal character? 

What is the benefit of the intended functionality?

**Comment by clason** [comment]
Are you sure this is related to vimtex (try `vim -u NORC` or `nvim -u NONE`)? This is normal behaviour on most international keyboard layouts (google "dead keys") to allow inputting accented characters (e.g., grave + `e` becomes `è`).

**Comment by lervag** [comment]
It is because of the imaps feature, see `:help vimtex-imaps`. To disable it, use `g:vimtex_imaps_enabled`.

**Comment by johngodlee** [comment]
Many thanks @lervag, that's solved my problem

**Comment by clason** [comment]
Or set a different imaps leader, e.g., `let g:vimtex_imaps_leader = ';'`.

**Comment by lervag** [comment]
Happy to hear it. I think the imaps feature can be quite convenient, so remapping the leader may be a good alternative to disabling it.
