### ISSUE TITLE
Spell checking inside bm

### ISSUE THREAD

**Issue by ngmoviedo** [lervag/vimtex#2055]
I've noticed that characters inside `\bm{}`, from the bm package, get highlighted by the built-in spell checker. I suppose this is not intended, as I can't see the use of checking spell there. Generating the `.fls` file or reloading don't solve the issue. I think this package is usual enough to consider, as it is also included on vimtex's concealment rules.

**Comment by lervag** [comment]
I think this should fix it, please test.

**Comment by ngmoviedo** [comment]
It works! That was fast!
Thanks for the fix and for this great plugin. I can't imagine editing LaTeX without it anymore.

**Comment by lervag** [comment]
Glad you like it :)

**Comment by Joellidin** [comment]
May I ask if it is intended for the built-in spell checker to highlight text inside `\acrshort,` `\acrlong,` `\acrfull`. It does not highlight it for glossaries, so I suppose it should not do it for acronyms either.

**Comment by lervag** [comment]
Yes, of course; but please note that your question is only partly on topic, and that there is no good reason not to open a new issue (and instead link to this one if you think the context is necessary). It makes it easier for me to follow up in case there are any necessary actions.

**Comment by lervag** [comment]
Sorry, forgot to actually answer: It's as simple as this - no one has made this comment before, and I've never really reacted to the issue myself. So there is no intent neither to enable or disable the spell checking inside those commands. If you want me to change something, please open a new issue with a simple description (similar to your question) and a reference to the documentation for those commands and/or some concrete examples of how to use them.

**Comment by Joellidin** [comment]
@lervag Of course, sorry about that. I will open a new issue. Thank you!

**Comment by lervag** [comment]
No problem :)
