### ISSUE TITLE
Where should scripts that target the pdf-viewer windows be called?

### ISSUE THREAD

**Issue by maxfer1221** [lervag/vimtex#2059]
Hello!

First and foremost, I'm not facing any issues, I do have some questions, however.

I am currently using zathura to view compiled tex files, and, in addition to zathura, I am utilizing a C script to manipulate the window decorations for the pdf viewer.

I've skimmed most of the vimtex manual and documentation, as well as read through view.vim, view/zathura.vim and a few other files, but I can't quite seem to figure out where to execute my script.

The script works by manipulating any open zathura windows, and thus needs to be called after the zathura window is opened. From reading through the .vim files, I tried to `call system('my-script')` as follows:
```vim
" autoload/vimtex/view.vim
function! vimtex#view#view(...) abort " {{{1
  if exists('*b:vimtex.viewer.view')
    call b:vimtex.viewer.view(a:0 > 0 ? a:1 : '')
    call system('my-script')
  endif
endfunction
" }}}1
```
I'm sure to you all it is obvious that this didn't work, but as a complete vim beginner, this was my best guess as to the correct location to call the script. Any help would be appriciated on this matter, and I can always provide more information if necessary.

Thank you!

P.S. `my-script` executes `/path/to/script $(wmctrl -lx | grep -E "zathura" | grep -oE "[0-9a-z]{10}")'`, which targets my zathura window

**Comment by lervag** [comment]
I believe you can rely on the `VimtexEventView` event. Something like this should work (add the following to your vimrc file):

```vim
augroup vimrc_vimtex
  autocmd!
  au User VimtexEventView call MyViewHook()
augroup END

function! MyViewHook() abort
  " Ensure this hook only executes within a VimTeX buffer
  if !exists('b:vimtex') | return | endif

  call system('/path/to/script')
endfunction
```

For more info, see `:help vimtex-events`.
