### ISSUE TITLE
Synctex with Zathura (linux, easy)

### ISSUE THREAD

**Issue by vsilv** [lervag/vimtex#206]
Dear Lervag,

You were writing somewhere that this certainly works, so let me raise the question after hours of trying and with some colleagues having the same issue, you can probably answer it within a blink of an eye:
How can I make use of synctex, using vim in terminal and zathura?

Up to now I have in my `.latexmkrc`

```
$pdflatex = 'pdflatex -shell-escape -synctex=1 %O %S';
```

and in my .vimrc

```vimL
let g:latex_view_general_viewer = 'zathura'
let g:vimtex_view_method = "zathura"
```

I am sure this is certainly not enough, but I was not able to find out what is the right configuration for, lets say, backward and forward search.

Thanks in advance a lot!

**Comment by lahwaacz** [comment]
The documentation [says](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L712), that `xdotool` is required for forward search (synctex). Do you have it installed?

**Comment by vsilv** [comment]
Yes, of course I have installed xdotools, but it does not say in which it is used, so I can not react to it.

**Comment by lervag** [comment]
Could you please specify a couple of things:

1. Which version of `xdotools` are you using?
2. Which version of `zathura` are you using?
3. Which version of Vim are you using?
4. Which OS are you using?

Next, could you from the terminal

1. open vim
2. open a LaTeX file
3. start compiling with `<leader>ll`
4. do command `<leader>lv` to open viewer/perform forward search
5. give me the output after `<leader>li` (this should give some information about e.g. which commands have been used to start `latexmk` and `zathura`)
6. give me the output after `<leader>lo` (this will show the output from the `latexmk` process)

Btw: I believe this issue may be related to #205.

**Comment by lervag** [comment]
Note that I [previously](https://github.com/lervag/vimtex/issues/181#issuecomment-110092265) learned that synctex support was added to zathura in version 0.2.7, see #181.

**Comment by vsilv** [comment]
Thank you for the response, I recompiled everything and noticed that <leader>lv is now working. But for the sake of backwards search, I will give you a detailed answer of the questions.
\li gives (shortened, I only pasted the important parts)
cmd_latexmk_compile : 'cd ''.../bachelor/report'' && max_print_line=2000 latexmk -pdf -e ''$pdflatex =
~ s/ / -file-line-error /'' -outdir=. -pvc -e ''$success_cmd = "vim --servername  --remote-expr \"vimtex\#latexmk\#callback(1)\""'' -e '
'$failure_cmd = "vim --servername  --remote-expr \"vimtex\#latexmk\#callback(0)\""'' -e ''$new_viewer_always = "0"'' -e ''$pdf_previewer
 = "start zathura  -x \"/usr/bin/vim --servername  --remote +\%{line} \%{input}\" \%S"'' ''report.tex'' &>/tmp/vg6IH5C/11' 
...
cmd_start : 'zathura  -x "/usr/bin/vim --servername  --remote +\%{line} \%{input}" ''.../repor/report.pdf'''
...
cmd_forward_search : 'zathura --synctex-forward 278:1:'.../theory.tex'' '.../report.pdf'''
class : 'Zathura' 
...
\lo gives
Latexmk: This is Latexmk, John Collins, 5 February 2015, version: 4.43a.
Viewing pdf
Latexmk: I have not found a previewer that is already running. 
   So I will start it for './report.pdf'
------------
------------
Running 'start start zathura  -x "/usr/bin/vim --servername  --remote +%{line} %{input}" "./report.pdf"'
------------
Latexmk: All targets (./report.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
------------
Running 'vim --servername  --remote-expr "vimtex#latexmk#callback(1)"'
------------
Vim: Warning: Output is not to a terminal
Vim: Warning: Input is not from a terminal

If you need any certain details, please tell me. Since forward search is working now, is there something special I need to do for backwards search?

with best regards and thank you for your fast answer!

**Comment by nasenatmer** [comment]
For backwards search, you don't have to configure anything in particular. But in order to do backward search, you need to do <ctrl>+<left mouse click> on the word you want to do backward search for.

**Comment by lervag** [comment]
@vsilv I believe I understand the problem now. You are working in a terminal vim, correct? What is the output of `:echo v:servername`? I suspect the output is empty. As you might see from the output you provided, there are several places where the option `--servername` is provided, but no servername is actually added.

I can reprocuce this issue with terminal vim myself. Everything works as expected with gvim.

**Comment by lervag** [comment]
One simple solution might be to follow [this](http://www.rohanjain.in/yet-another-vim-productivity-post-server-client/) example.

That is, you can specify the servername on the command line. If you start vim with `vim --servername foo`, then I suspect that everything should work.

**Comment by lervag** [comment]
[vim wikia](http://vim.wikia.com/wiki/Enable_servername_capability_in_vim/xterm) also has some tips. The simplest one might be suitable: Create an alias for vim that sets the servername:

```bash
alias vim='vim --servername vim'
```

**Comment by vsilv** [comment]
The last comment solved my problem. Thanks a lot!

**Comment by lervag** [comment]
Great! Happy to hear it! :)

**Comment by sierxue** [comment]
Dear Lervag,

First, I would say that this plugin is terrific!

Xubuntu 16.04, vim 8.0, vimtex (cloned from git), zathura 0.36:

I can do [ctrl]+[left mouse click] on the word to do backward search. If I want map to <C-Enter>, how can I do it?

Thanks in advance!

**Comment by lervag** [comment]
I am not sure if this is possible. According to `man zathurarc`, one may map key bindings to shortcut fuctions, but none of the shortcut functions seem to be the one we want for doing backrward search.

I recommend that you pass this on to the zathura devs, see [here](https://pwmt.org/contact/) for contact information.

**Comment by sierxue** [comment]
Thanks! Will do it.

**Comment by adrienooms** [comment]
Hi Karl, Hi all,
First of all, thank you Karl for this plugin and the great support and feedback you give on the forums. Thanks for this thread which allowed me to set forward and backward search with vim on my system. It amazes me even more since I am working with WSL (w/ ubuntu) and a Windows X server.
My question is, would it be technically possible to, in addition to repositioning the cursor, have the selected window switching from zathura back to the vim window when you do [ctrl]+[left click] ? Or this controlled by another entity?

Thank you

**Comment by lervag** [comment]
@adrienooms Thank you for the kind words! To answer your question: Yes, in principle. If you use `let g:vimtex_view_method = 'zathura'` and if you have `xdotool` installed (and working), then this should work. However, I have to admit that I try to keep out of Windows specific issues. I don't have (nor want) a Windows computer for testing, and so it is very difficult to develop/fix bugs related to windows specific issues. In any case, what you are asking for is typically called backward search or reverse search, and to enable it, you need to specify the `-x` option for Zathura. This is only available if Zathura is compiled with `libsynctex` enabled, and if it is available, you will see the option when you do `zathura -h`. For testing, I would try to make this work without vimtex first. It may also help to view the exact commands used by vimtex, which you may find with `\li` after you've issued the commands. E.g., open a document, view with `\lv`, then see the view command with `\li` (search for "viewer" and "cmd").

If you want to follow up on this, please open a new issue. I don't like it so much when we "disturb" old threads.
