### ISSUE TITLE
Highlight \begin{comment}/\end{comment} environment

### ISSUE THREAD

**Issue by dajuno** [lervag/vimtex#2061]
Hi,
the package [comment](https://ctan.org/tex-archive/macros/latex/contrib/comment?lang=en) enables block comments, like so:
```tex
\documentclass{article}
\usepackage{comment}

\begin{document}
\section{Intro}
Some text.

\begin{comment}
    \section{commented section}
    some more text ...

    \section{etc}
    etc
\end{comment}
\end{document}
```

It would be nice if `vimtex` could apply the syntax rules for comments to `\begin{comment}/\end{comment}` blocks, too.

Best wishes

**Comment by lervag** [comment]
Thanks! But VimTeX already does support this.

![2021-06-01_12:54_screenshot](https://user-images.githubusercontent.com/998898/120312077-8f6de300-c2d8-11eb-8283-df71f2e62f8a.png)
