### ISSUE TITLE
forward/backward search with evince

### ISSUE THREAD

**Issue by rudrab** [lervag/vimtex#2064]
Hi,
my vimtex setting is:

```
let g:vimtex_mappings_leader='`'
let g:vimtex_compiler_latexmk = {
      \ 'continuous' : 0,
      \ 'options' : [
      \   '-verbose',
      \   '-pv',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-shell-escape',
      \   '-interaction=nonstopmode',
      \ ],
      \}
let g:vimtex_compiler_latexmk_engines = {
      \ '_' : '-lualatex',
      \}
```
As a viewer I use evince. 

Is there any way to enable forward/backward search?

I have also added  'gauteh/vim-evince-synctex'  but still I am not getting the searches,.

**Comment by lervag** [comment]
> my vimtex setting is: ...
> 
> ...
>
> As a viewer I use evince.

You did not specify the viewer option in your settings. Have you read `:help vimtex-view`? If not, please do.

> Is there any way to enable forward/backward search?

See `:help vimtex_viewer_evince`; short answer is "it is not easy", and "I don't really know how".

> I have also added 'gauteh/vim-evince-synctex' but still I am not getting the searches,.

That's not VimTeX, so it is not relevant here. Instead ask on that repo for more info. I don't know anything about that plugin. Sorry.

**Comment by Konfekt** [comment]
https://github.com/gauteh/vim-evince-synctex/blob/ca7a1381bd0badbd22c243f3f1540bda5e6b68ad/after/ftplugin/tex.vim#L11

enables for/backward search with evince in Vimtex by

```vim
    " VimTex
    let g:vimtex_view_general_viewer  = resolve(s:path . '/../../bin/evince_backward.sh')
    let g:vimtex_view_general_options = '@pdf ' . v:servername

    function! Evince_ForwardSearch()
      VimtexView
      let cmd = s:path . '/../../bin/evince_dbus.py ' . b:vimtex.out() . ' ' . line(".") . ' ' . expand("%:p")
      let output = system(cmd)
    endfunction

    command! -buffer VimtexForwardSearch  call Evince_ForwardSearch()
```

Perhaps the vimtex API used is out of date?

**Comment by lervag** [comment]
> Perhaps the vimtex API used is out of date?

Are you asking me? Well, one thing I'm noticing is that it seems possible to simplify by use of `VimtexEventView`. Something like this:

```vim
augroup vimrc_vimtex
  autocmd!
  autocmd User VimtexEventView call EvinceForwardSearch()
augroup END

function! EvinceForwardSearch()
  call system('/path/to/evince_dbus.py '
        \ . b:vimtex.out() . ' '
        \ . line(".") . ' '
        \ . expand("%:p"))
endfunction
```

I'm closing this issue as I don't have the time or interest to investigate these things directly myself. But if anyone uses this and has some spare time, I would be happy to consider a PR for improving the documentation.

**Comment by Konfekt** [comment]
@rudrab submit the issue at https://github.com/gauteh/vim-evince-synctex/issues and propose to add a pull request to merge what vim-evince-synctex achieves into vimtex.

**Comment by lervag** [comment]
@rudrab Just a comment to the config your posted: `g:vimtex_mappings_leader` is not a valid option, perhaps you meant `g:vimtex_imaps_leader`?

**Comment by rudrab** [comment]
> 
> ```viml
> augroup vimrc_vimtex
>   autocmd!
>   autocmd User VimtexEventView call EvinceForwardSearch()
> augroup END
> 
> function! EvinceForwardSearch()
>   call system('/path/to/evince_dbus.py '
>         \ . b:vimtex.out() . ' '
>         \ . line(".") . ' '
>         \ . expand("%:p"))
> endfunction
> ```
>

If @lervag  kindly allows to continue the discussion here, the code is working perfectly for forward search, but backward search is not working yet.

**Comment by lervag** [comment]
> If @lervag kindly allows to continue the discussion here, ...

My point of closing the issue was simply that I don't see a concrete thing to do on my side. I don't mind that you continue the discussion, so feel free! :)

**Comment by rudrab** [comment]
Just one thing: the code
```viml
augroup vimrc_vimtex
  autocmd!
  autocmd User VimtexEventView call EvinceForwardSearch()
augroup END

function! EvinceForwardSearch()
  call system('~/home/bin/evince_dbus.py '
        \ . b:vimtex.out() . ' '
        \ . line(".") . ' '
        \ . expand("%:p"))
endfunction

nnoremap <leader>lf :EvinceForwardSearch<CR>

```
is not working if I remove vim-evince-synctex plugin. I don't see why, but without the vim-evince-synctex plugin it is giving error: `not an editor command  EvinceForwardSearch()`

**Comment by lervag** [comment]
> ```viml
> "...
> nnoremap <leader>lf :EvinceForwardSearch<CR>
> ```
> 
> is not working if I remove vim-evince-synctex plugin. I don't see why, but without the vim-evince-synctex plugin it is giving error: `not an editor command EvinceForwardSearch()`

Yes, because the command `:EvinceForwardSearch` is not provided by VimTeX or by the supplied code. There is a distinction between `:command` and `:call function()`, see e.g. `:help :ex-cmd-index`.

You could instead do this:

```vim
nnoremap <leader>lf :call EvinceForwardSearch()<cr>
```

However, the point of my suggested code was that the `EvinceForwardSearch` function should be called whenever you do `\lv`, so I'm not sure if you even need the `\lf` mapping at all?
