### ISSUE TITLE
Mathzone doesn't get recognized properly

### ISSUE THREAD

**Issue by L1szt** [lervag/vimtex#2070]
I'm using UltiSnips and hence want to make use of the mathzone recognising feature. 
This is my code in the UltiSnips file (all snippets are working apart from those depending on the mathzone recognition feature):
```
global !p
def math():
	return vim.eval('vimtex#syntax#in_mathzone()') == '1'
```
What could cause this problem?

**Comment by L1szt** [comment]
https://github.com/nvim-treesitter/nvim-treesitter/issues/1184

**Comment by lervag** [comment]
Ah, yes, I believe you figured it out.
