### ISSUE TITLE
Table of Contents removes alternate file 

### ISSUE THREAD

**Issue by bongbang** [lervag/vimtex#2073]
Opening Vimtex's Table of Contents removes Vim's alternate file.

1. Edit the file below.
2. Compile to create `highlight.bib`.
2. `e highlight.bib` to open an alternate file.
3. `ctrl-^` three times to switch back to the `.tex` file and forth and back again.
4. `<local-leader>lt` to open the TOC.
5. `ctrl-^` to switch to the alternate file.

    `"E23: No alternate file"`

This behavior doesn't occur with Vundle's `PlugInList`, which similarly opens a new buffer in a split. The alternate file is retained after closing the split.

```tex
\documentclass{article}
\usepackage[style=verbose-ibid]{biblatex}
\addbibresource{highlight.bib}

\begin{filecontents}{highlight.bib}

@book{Hemingway:For_Whom_the,
	author   = {Earnest Hemingway},
	title    = {For Whom the Bell Tolls},
	date     = {1940},
	publisher  = {Simon \& Schuster},
}

\end{filecontents}

\begin{document}

\section{Introduction}

Some text here.\autocite[10]{Hemingway:For_Whom_the}

\end{document}
```

**Comment by lervag** [comment]
Thanks, I think this should be fixed now.

**Comment by bongbang** [comment]
Fixed indeed. You maintain this free plug-in better than most corporations do their paid software. Much appreciated.

**Comment by lervag** [comment]
Glad to hear it! I wish I had more time to address the backlog as well, but at least I am able to keep it more or less "at bay" :)
