### ISSUE TITLE
Compose imaps

### ISSUE THREAD

**Issue by albertfgu** [lervag/vimtex#2074]
It would be nice if imaps were composed in a stack-like reduction if the arguments to them are other imaps.

Example config:

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : 'b',
      \ 'rhs' : 'vimtex#imaps#style_math("bm")',
      \ 'expr' : 1,
      \ 'leader': '``'
      \})
```

Current Functionality: ``` ``b`a ``` -> `` \bm{`}a ``

Desired Functionality: ``` ``b`a ``` -> ` \bm{\alpha} `

(Incidentally, I have that line in my config which was probably copied from an old Github issue, but I can't find the documentation for this feature. Is it in the docs and is that config line up to date?)

**Comment by lervag** [comment]
> It would be nice if imaps were composed in a stack-like reduction if the arguments to them are other imaps.

I can see that this could be convenient, but I have to admit I have no clear idea how to achieve it. The current `#style_math()` function works by use of the `getchar()` function, and I don't immediately see how it could be properly stacked.

This type of functionality _might_ work with the more potent snippet engines, though, e.g. UltiSnips. E.g., you could make a snippet for the `\bm` command that autoexpands and immediately "frees" the typehead so it would work as expected with the VimTeX imaps.

Sorry for the inconvenience!

> (Incidentally, I have that line in my config which was probably copied from an old Github issue, but I can't find the documentation for this feature. Is it in the docs ...

At least in part: See `:help vimtex-imaps`. There is an example for `#rX -> \mathrm{X}`.

> ... and is that config line up to date?)

Yes, it seems so. You could consider to also add the `wrap_math` wrapper as shown in the examples in the docs.
