### ISSUE TITLE
Toggle surrounding delimiters does not work with absolute value

### ISSUE THREAD

**Issue by urbainvaes** [lervag/vimtex#2077]
Hi @lervag,

Again, thank you very much for this great plugin!

It seems that `tsd` does not work with absolute values, for example with `\bigl| text between delimiters \bigr|`.

**Comment by lervag** [comment]
I'm not quite sure what you mean with "absolute values". `tsd` does not work with `|`, because it is not really a delimiter. Instead, you should use `\lvert` and `\rvert`. To also toggle with e.g. `\bigl ... \bigr` pairs, see `:help g:vimtex_delim_toggle_mod_list`.

**Comment by urbainvaes** [comment]
TIL about `\lvert` and `\rvert`, thank you very much!

**Comment by lervag** [comment]
No problem :)
