### ISSUE TITLE
Request: Configurability of vimtex#fold#text() via vimtex_fold_types_defaults

### ISSUE THREAD

**Issue by gjgress** [lervag/vimtex#2083]
**Is your feature request related to a problem? Please describe it.**
When folding a LaTeX document with lots of titled environments and little text in-between, you get something that looks like:
```
       Preamble
\begin{document}

\begin{defn}-------------------------

\begin{anki}-------------------------

\begin{defn}-------------------------

\begin{anki}-------------------------

\begin{defn}-------------------------

\begin{defn}-------------------------

\begin{anki}-------------------------

\begin{thm}-------------------------

\begin{cor}-------------------------

\begin{anki}-------------------------

\end{document}
```
Depending on the level of plaintext in-between, this is difficult to pore through.

**Describe the solution you'd like**
Increased configurability of the vimtex function vimtex#fold#text() , i.e. a setting that allows folding to instead look like:

```
       Preamble
\begin{document}

\begin{defn}[Open Disc]-------------------------

\begin{anki}[Open Disc]-------------------------

\begin{defn}[Interior, Exterior, and Boundary Points]-------------------------

\begin{anki}[Interior, Exterior, and Boundary Points]-------------------------

\begin{defn}[Closure]-------------------------

\begin{defn}[Open and Closed Sets]-------------------------

\begin{anki}[Open and Closed Sets]-------------------------

\begin{thm}[Fundamental Theorem 1]-------------------------

\begin{anki}[Fundamental Theorem 1]-------------------------

\begin{cor}[Consequence of Fundamental Theorem]-------------------------

\end{document}
```

**Describe alternatives you've considered**
Adding comments before the environment with the title of the environment is a temporary workaround, but clutters the document unnecessarily, and obviously won't work for pre-written documents.

**Additional context**
There is some talk within the documentation about various levels of concealment of certain environments via cmd, but I can't seem to figure out how to use this for my case! In particular, it seems that it is often used to conceal further, but I'd like to show -more- instead.

In general, stuff like the foldtext() is very useful to modify for various reasons, and increased configurability of the function would be nice.

**Comment by lervag** [comment]
> Increased configurability of the vimtex function vimtex#fold#text() , i.e. a setting that allows folding to instead look like: ...

So, you want to have the first option group to be visible in the fold text, i.e. `\begin{env}[opt]`. Am I right?

> There is some talk within the documentation about various levels of concealment of certain environments via cmd, but I can't seem to figure out how to use this for my case! In particular, it seems that it is often used to conceal further, but I'd like to show -more- instead.

This is a very different feature. Conceals are a syntax feature and is in no way related to folding. See `:help syn-conceal` for more info.

----

Can you provide a full example file that I can work with? Preferably something that compiles as expected. Also, provide the relevant VimTeX config (if any).

**Comment by gjgress** [comment]
> > Increased configurability of the vimtex function vimtex#fold#text() , i.e. a setting that allows folding to instead look like: ...
> 
> So, you want to have the first option group to be visible in the fold text, i.e. `\begin{env}[opt]`. Am I right?

Yes, that is correct. More generally, it might be a good thing to include as options under `env_options` in `g:vimtex_fold_types_default` (?) I guess I'm not sure the best way to configure individual environments beyond the special ones (like 'sections', 'items') but it would be nice if I could fine-tune them.

> > There is some talk within the documentation about various levels of concealment of certain environments via cmd, but I can't seem to figure out how to use this for my case! In particular, it seems that it is often used to conceal further, but I'd like to show -more- instead.
> 
> This is a very different feature. Conceals are a syntax feature and is in no way related to folding. See `:help syn-conceal` for more info.

My bad, I mixed up terminology. Upon further review, what I was referring to is-- `cmd_*` which allows for automatic folding of options in _unfolded_ content. What I am requesting would be the reverse: keep the optional arguments unfolded (read: in the foldtext() ) along with the environment, while still folding the rest of the content.

> Can you provide a full example file that I can work with? Preferably something that compiles as expected. Also, provide the relevant VimTeX config (if any).

Sure thing, although to be honest I'm not sure how useful it will be. I can't upload .tex files directly, but [here](https://pastebin.com/U7S9iPn9)'s the source code.

As for the relevant VimTex config, I don't think its particularly relevant, but this is my current config:
```
let g:tex_flavor='latex'
let g:vimtex_view_method = 'zathura' 
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmgs'
let g:vimtex_disable_recursive_main_file_detection=1
let g:vimtex_quickfix_autoclose_after_keystrokes=0
let g:vimtex_fold_enabled=1
let g:vimtex_fold_types = {'items' : {'enabled' : 0},
			\'envs' : {'blacklist' : ['itemize', 'enumerate', 'align', 'align*']}
			\}
"set foldtext=vimtex#fold#text()

set fillchars=fold:\ 
```
You can see that I already tried playing with `foldtext` to get a solution, but ran into a wall once I dug into the vimtex#fold#text() function :)

**Comment by lervag** [comment]
> Yes, that is correct. More generally, it might be a good thing to include as options under `env_options` in `g:vimtex_fold_types_default` (?) I guess I'm not sure the best way to configure individual environments beyond the special ones (like 'sections', 'items') but it would be nice if I could fine-tune them.

The `env_options` type is not really for folding an environment; instead, if the environment is _not_ folded, then you can have this type to fold only the options part. It can be useful if you blacklist e.g. the `axis` environment (part of pgfplots) from the `envs` type. This env typically requires a lot of options, so some people wanted to have those folded.

In your case, it seems we instead want to implement an improved fold text. My proposal is to simply change the current default to also include the option group, or as much as possible from it. I think this should be always interesting/useful, so I think we don't even need an option for it.

> > Can you provide a full example file that I can work with? Preferably something that compiles as expected. Also, provide the relevant VimTeX config (if any).
>
> Sure thing, although to be honest I'm not sure how useful it will be.

It is very useful, because it makes it immediately possible for me to see which kinds of things you are talking about. I'll use it while developing and might also use some of it for making tests.

> As for the relevant VimTex config, I don't think its particularly relevant, but this is my current config: ...

You can simplify this. First, `g:tex_flavor` and `g:tex_conceal` is not longer relevant and can be removed, and the `g:vimtex_quickfix_autoclose_after_keystrokes` was not changed from its default value. So, I would reduce to the following - please note the comments.

```vim
set fillchars=fold:\ 

" Note that conceallevel is local to window! Thus, you should apply it with an
" autocommand or similar to make sure it is set for tex buffers. I also believe
" you probably want to use the value 2.
set conceallevel=1

let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_mode = 0
let g:vimtex_fold_enabled = 1
let g:vimtex_fold_types = {
      \ 'items': {'enabled' : 0},
      \ 'envs': {'blacklist' : ['itemize', 'enumerate', 'align', 'align*']}
      \}

" Are you sure about this?!
let g:vimtex_disable_recursive_main_file_detection = 1
```

**Comment by lervag** [comment]
So, to be clear, it seems this issue is resolved if I change the environment folds so that the fold text includes the option group, if it is available. Can you confirm?

**Comment by gjgress** [comment]
Yes, I agree. Your plan seems like a good resolution.

Thanks for the swift reply, and for the configuration tips!

**Comment by gjgress** [comment]
Not sure where this is on the to-do list, but I could spend some time rewriting the vimtex#fold#text() function and submit a pull request, if you haven't rewrote it already. Let me know if that would be helpful.

**Comment by lervag** [comment]
> Not sure where this is on the to-do list, but I could spend some time rewriting the vimtex#fold#text() function and submit a pull request, if you haven't rewrote it already. Let me know if that would be helpful.

It's "there", but there's been a rush of new issues of late. I barely have time to reply to the different requests, so there's not that much time for implementing/improving. But with time, I will work on this. If you want it sooner, then of course I would be happy to see a PR! If you want to look at it, then the following is probably where you should start:

https://github.com/lervag/vimtex/blob/a064c48ade2a4df3d010e02b2d528fc2534a62eb/autoload/vimtex/fold/envs.vim#L76-L78

**Comment by lervag** [comment]
PR #2107 addresses this issue and the issue will be resolved when the PR is merged. I'll therefore take the liberty of closing this issue.
