### ISSUE TITLE
Citation completion issues with international characters

### ISSUE THREAD

**Issue by xileF1337** [lervag/vimtex#2091]
Hi, thanks for your useful LaTeX plugin. I just installed it and got the most features working as desired, but I'm having trouble with the completion of citation keys. 

## Config
I'm using neovim-qt and installed vimtex via vim plug. I am also using UltraSnip, but no other completion plugin.

## Issue

Consider the following bib entry, which has a first author with a German umlaut 'ü'. For reasons of compatibility, it is often written using the LaTeX command `\"u` instead:

```bibtex
@article{mueller-2019-csra,
  title     = {A new role for CsrA: promotion of complex formation between an
               sRNA and its mRNA target in Bacillus subtilis},
  author    = {M{\"u}ller, Peter and Gimpel, Matthias and Wildenhain, Theresa
               and Brantl, Sabine},
  journal   = {RNA biology},
  volume    = {16},
  number    = {7},
  pages     = {972--987},
  year      = {2019},
  publisher = {Taylor \& Francis}
}
```
Now, in a tex file including this bibliography, I try to complete the key, invoking the omni-completion using `<c-x><c-o>`. 

## Observed Behaviour
The following commands *are* correctly completed:
```latex
\cite[]{m}
\cite[]{mü}
\cite[]{M}
\cite[]{MÜ}
```
When there is more than one match in the bib file, the list of matching entries opens, where I can see the above entry formatted like so:
```
mueller-2019-csra [a] MÜller et al. (2019), "A new role [...]"
```
Note how "M*Ü*ller" is spelled with a capital Ü, despite it iss a small letter in the bib entry.

The following commands are *not* completed ("Pattern not found"):
```latex
\cite[]{mu}
\cite[]{Mü}
\cite[]{peter}
\cite[]{Peter}
\cite[]{gimpel}
\cite[]{Gimpel}
```

## Expected Behaviour
All the above keys should be completed to the given bibtex entry.

## Discussion
So if understand correctly, the completion is performed case-insensitive for the ASCII chars, but is case-sensitive for the unicode chars, and additionally the substitution of `{\"u} ` and other symbols is not working correctly. Additionally, it seems that I cannot search for any author but the first one, and only by his given name. Also, it seems like vimtex cannot complete the key of the entry (`mueller-2019-csra`), otherwise `\cite{mu}` would work. I have read about the `simple` option to search *only* for the keys, but shouldn't the "smart" mode allow to search for author names, title, *and* keys? Or am I missing something?

## VimtexInfo
```
System info
  OS: KDE neon User Edition 5.21
  Vim version: NVIM v0.4.3
  Has clientserver: true
  Servername: /tmp/nvimXrhFxp/0

VimTeX project: thesis
  base: thesis.tex
  root: /home/usrname/scr/Research/Thesis/TeX
  tex: /home/usrname/scr/Research/Thesis/TeX/thesis.tex
  out: /home/usrname/scr/Research/Thesis/TeX/thesis.pdf
  log: /home/usrname/scr/Research/Thesis/TeX/thesis.log
  aux: /home/usrname/scr/Research/Thesis/TeX/thesis.aux
  fls: /home/usrname/scr/Research/Thesis/TeX/thesis.fls
  main parser: latexmain specifier
  source files:
    thesis.tex
    misc/custom_commands.tex
    chapters/introduction.tex
    chapters/background.tex
    chapters/a_chapter.tex
    chapters/another_chapter.tex
    chapters/yet_another_chapter.tex
    appendices/appendix_dummy.tex
  compiler: latexmk
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
    process:
      pid: -
      cmd: okular --unique file:'/home/usrname/scr/Research/Thesis/TeX/thesis.pdf'\\#src:26'/home/usrname/scr/Research/Thesis/TeX/chapters/a_chapter.tex' >/dev/null 2>&1 &
  qf: LaTeX logfile
    addqflist: 157
    fix_paths: 158
    set_errorformat: 156
  document class:
  packages:
    algorithmic
    amsbsy
    amsfonts
    amsgen
    amsmath
    amsopn
    amssymb
    amstext
    amsthm
    array
    atbegshi
    atveryend
    auxhook
    biblatex
    bigintcalc
    bitset
    calc
    caption
    caption3
    catchfile
    csquotes
    datatool-base
    datatool-fp
    dcolumn
    defpattern
    delarray
    epstopdf-base
    etexcmds
    etoolbox
    everysel
    everyshi
    expl3
    fancyvrb
    float
    fontenc
    fp
    fp-addons
    fp-basic
    fp-eqn
    fp-eval
    fp-exp
    fp-pas
    fp-random
    fp-snap
    fp-trigo
    fp-upn
    framed
    fvextra
    gettitlestring
    glossaries
    glossaries-compatible-307
    glossary-hypernav
    glossary-list
    glossary-long
    glossary-super
    glossary-tree
    graphics
    graphicx
    hycolor
    hyperref
    ifluatex
    ifplatform
    iftex
    ifthen
    infwarerr
    inputenc
    intcalc
    keyval
    kvdefinekeys
    kvoptions
    kvsetkeys
    l3keys2e
    letltxmacro
    lineno
    listofitems
    lmodern
    logreq
    longtable
    ltcaption
    ltxcmds
    marginnote
    mathtools
    memhfixc
    mfirstuc
    mhsetup
    microtype
    minitoc
    minted
    mtcmess
    mtcpatchmem
    multirow
    nameref
    nomencl
    pdfescape
    pdftexcmds
    pgf
    pgfcomp-version-0-65
    pgfcomp-version-1-18
    pgfcore
    pgffor
    pgfkeys
    pgfmath
    pgfrcs
    pgfsys
    ragged2e
    refcount
    rerunfilecheck
    scrbase
    scrlfile
    shellesc
    sidecap
    silence
    soul
    substr
    supertabular
    tabularx
    textcase
    textcomp
    tikz
    tocbasic
    todonotes
    trig
    uniquecounter
    upquote
    url
    xassoccnt
    xcolor
    xfor
    xkeyval
    xparse
    xspace
    xstring
...
```

**Comment by lervag** [comment]
Thanks for the detailed issue description.

First: I can't reproduce that the umlaut is not properly translated. On my end, it looks like this:

![image](https://user-images.githubusercontent.com/998898/124768894-54934680-df39-11eb-92ab-5863b5be8255.png)

Next, when you use the "advanced" matching on author names, then you should not that the search is performed on the menu string, not on the content in the bib entry. In this case, the menu string is "[a] Müller et al. (2019)", so you can't match on the other names. Further, the matching is case sensitive by default; if you write `\cite{\cmü`, then you should get a match because `\c` specified that the regex should match case insensitive.

On my end, it seems the matching works well for `\cite{m`, `\cite{mue` (these match on the bib key), `\cite{M`, `\cite{Mü`, `\cite{\cmü` (these three match on the menu string).

So, I believe the main problem here is that the documention may be somewhat inaccurate. If you read `:help vimtex-complete-cites`, it has the following paragraph at the end:

```
In particular, note that regular expressions (or vim patterns) can be used
after '\cite{' to search for candidates. By default, the regex is applied to
the completion menu, which is defined by |g:vimtex_complete_bib.menu_fmt|.
```

So, one solution is to change the format string, e.g.

```vim
let g:vimtex_complete_bib = {'menu_fmt':  '[@type] @author_all (@year), "@title"'}
```

When I do that, I can match on Gimpel and Wild. The first names are not included. It looks like this:

![image](https://user-images.githubusercontent.com/998898/124770363-8fe24500-df3a-11eb-8d7e-32717c8e68b5.png)

**Comment by clason** [comment]
First,
> So, one solution is to change the format string, e.g.
> `let g:vimtex_complete_bib = {'menu_fmt':  '[@type] @author_all (@year), "@title"'}`

*yoink!* (although there seems to be a hard cut-off in the author list at some point?)

Second, I can somewhat reproduce that, although I have not tried in as much detail -- I, too, see `Ü` in names like `M{\"u}ller`. If I change the entry to `ü`, the first name prints correctly. I see similar issues with, e.g., `é `.

I suspect it might be something to do with locales? (I'm using the very latest Neovim commit on macOS, by the way, with `lan en_US.UTF-8` set in my `init.vim`.)

**Comment by lervag** [comment]
> _yoink!_ (although there seems to be a hard cut-off in the author list at some point?)

Hmm... yes, you're right, it cuts off at 20 characters:

https://github.com/lervag/vimtex/blob/26315034fca39e53e1051166d352e9e3f4e36e20/autoload/vimtex/complete.vim#L186

> Second, I can somewhat reproduce that, although I have not tried in as much detail -- I, too, see `Ü` in names like `M{\"u}ller`. If I change the entry to `ü`, the first name prints correctly. I see similar issues with, e.g., `é `.

Strange. For me, it works as expected with both neovim and Vim.

> I suspect it might be something to do with locales? (I'm using the very latest Neovim commit on macOS, by the way, with `lan en_US.UTF-8` set in my `init.vim`.)

Yes, that might explain things. But my locale is also `en_US.UTF-8`. So, perhaps it has to do with the OS? I'm on Arch Linux.

The function that translates these commands is here:

https://github.com/lervag/vimtex/blob/26315034fca39e53e1051166d352e9e3f4e36e20/autoload/vimtex/util.vim#L83

Notice in particular the list `s:tex2unicode_list` defined just below it, and the letter in question:

https://github.com/lervag/vimtex/blob/26315034fca39e53e1051166d352e9e3f4e36e20/autoload/vimtex/util.vim#L150

**Comment by clason** [comment]
> Hmm... yes, you're right, it cuts off at 20 characters:

Does it make sense to make it configurable? ;)

> Strange. For me, it works as expected with both neovim and Vim.
> Yes, that might explain things. But my locale is also `en_US.UTF-8`. So, perhaps it has to do with the OS? I'm on Arch Linux.

It's weird alright. But I don't think it's the locale at all; with your hint, I just removed the `\\"U` entry, and now I get the correct substitution on `\\"u`. The same happens if I switch the order of upper-case and lower-case letters -- but then I get `ü` for `M\"U`ller!

So there is some sort of issue with "greedy" substitution, where it picks the first matching one (case-insensitive). If your neovim and vim behave differently, it might be a version issue -- maybe a vim patch changed something, and we have but you don't? (But @xileF1337 is on neovim v0.4.3, so that doesn't make sense, either.)

**Comment by clason** [comment]
Right, and here's the culprit: I have `set ignorecase` in my `init.vim`; without that, it behaves as you describe.

**Comment by lervag** [comment]
> > Hmm... yes, you're right, it cuts off at 20 characters:
> 
> Does it make sense to make it configurable? ;)

I guess.

> Right, and here's the culprit: I have `set ignorecase` in my `init.vim`; without that, it behaves as you describe.

Yes, I was starting to suspect something like this. I'm pushing a fix now.

> by adding `I` to the option (i.e., `gI` instead of `g`). That fixes things for me.

No, that doesn't work. See `:help substitute()` - it does not accept the same flags as `:substitute`. We need to alter the patterns to contain `\C`.

**Comment by lervag** [comment]
@xileF1337 Me and @clason have "polluted" the discussion now. Can you fetch the latest updates and let me know if you find the explanations and adjustments here satisfactory?

**Comment by xileF1337** [comment]
@lervag The explanation sounds reasonable in so far as I have set `ignorecase` as well (or was it `smartcase`?). I hope I get to test the changes during the course of the evening. It would be cool to have the matching of the completion actually respect the setting of `ignorecase` or  `smartcase`.  If I set such an option as a user, then this is likely the behaviour I desire. My understanding of your discussion was that you want to force case sensitivity, didn't you? 

What I still don't understand then is why `\cite{mu}` does not match anything if the key of the entry is also matched against. But I will try the fix and see what happens.

**Comment by clason** [comment]
The matching here is not between what you type and menu entry, it's between the escaped Unicode character and its replacement. Case-insensitive (or, more generally, fuzzy) matching is a different thing entirely.

And it's not matching on `mu` since the literal string it matches against is `Mü` (and `u!=ü`). 

There are two issues here: matching what you type against the (rendered!) string that is shown in the menu (and not against the full bib entry as you initially thought), and how that string is rendered from the bib entry. The former is working as intended; the latter had a bug that is now fixed (at least for me).

**Comment by clason** [comment]
Yes, that seems to be a different issue that I can reproduce even without `ignorecase`.

**Comment by xileF1337** [comment]
I think the documentation is a bit unclear because it sais: "regular expressions *can* be used" to search for candidates and that *these* are "applied to the menu". (1) I would state that the search pattern *is* (always) interpreted as a regular expression (a regex need not contain metachars) and then (2) matched against the rendered bibtex entry as defined by `g:vimtex_complete_bib.menu_fmt`. Also, note that the menu *does* contain the key before the rendered entry, so according to the *current* documentation the key *should* be matched against. I think that many people give keys to their bibtex entries that they can easily remember and search for them later on. Having to choose via an option whether I want to match against either the key or the rendered entry does not seem that user-friendly to me. So maybe you want to change this as well? ;-)

**Comment by clason** [comment]
> Also, note that the menu does contain the key before the rendered entry,

Careful -- I (and the documentation) wasn't talking about the popup menu but the `menu`, see `:h complete-items`.

**Comment by xileF1337** [comment]
> > Also, note that the menu does contain the key before the rendered entry,
> 
> Careful -- I (and the documentation) wasn't talking about the popup menu but the `menu` part of the entry, see `:h complete-items`.

Ok, I was not aware of that special meaning of the term "menu" here. Still, in my opinion, it would be nice to match against key + "menu", i.e. the full pop-up menu entry. It would be quite useful. And is there any reason for not doing so? 

@lervag Beside that, I just tested commit https://github.com/lervag/vimtex/commit/2866508b5cb4d1e0759ee152d90c521a12d80b65 and unfortunately it does not change the matching behaviour. I still get the exact same result as in my original post. Sorry!

**Comment by xileF1337** [comment]
Ok, now I am totally puzzled. I had to rename the folder containing the LaTeX document, now the umlauts are rendered with the correct case is the menu entry. The completion works as expected and `smartcase` is also respected by the search, perfect. Thanks a lot! 

Is there any internal cache of vimtex? If so, how can I clean it? When changing the name of the containing dir back to its original name, I still get capital umlauts.

And what was your opinion what I wrote before?
> [...] it would be nice to match against key + "menu", i.e. the full pop-up menu entry. It would be quite useful. And is there any reason for not doing so?

**Comment by clason** [comment]
vimtex has a cache; maybe that didn't get cleared? `g:vimtex_cache_root`

**Comment by xileF1337** [comment]
> vimtex has a cache; maybe that didn't get cleared? `g:vimtex_cache_root`

Perfect, cleaning the `bibcomplete*` files in `'$XDG_CACHE_HOME/vimtex'` did the trick, thanks alot!

**Comment by xileF1337** [comment]
@lervag I also tested your commit allowing to specify the 'auth_len', and specified a custom format:
```vim
    let g:vimtex_complete_bib = {
                    \ 'auth_len': 0,
                    \ 'menu_fmt': '[@type] (@year) @author_all, "@title"',
                \}
```
Then, searching all authors works as expected. Cool! 

Caveats: (1) I had to manually clean the cache again to make the setting work. (2) I (obviously) can no longer see the title when there are many authors in the pop-up menu. It may be worth considering to separate the settings for what is displayed in the menu and what is matched against. But that is probably not part of this issue here. Thanks for your help again!

**Comment by lervag** [comment]
Sorry about the late reply :)

> @lervag The explanation sounds reasonable in so far as I have set `ignorecase` as well (or was it `smartcase`?). I hope I get to test the changes during the course of the evening. It would be cool to have the matching of the completion actually respect the setting of `ignorecase` or `smartcase`. If I set such an option as a user, then this is likely the behaviour I desire. My understanding of your discussion was that you want to force case sensitivity, didn't you?

See `:help g:vimtex_complete_ignore_case` and `:help g:vimtex_complete_smart_case`. By default, your settings should be respected.

> What I still don't understand then is why `\cite{mu}` does not match anything if the key of the entry is also matched against. But I will try the fix and see what happens.

I believe this is more or less settled now: With the "smart" mode, the key is not matched on by default. You can add the key to the completion menu, though.

> I think the documentation is a bit unclear

I tried to improve it now, do you find it clearer?

> Having to choose via an option whether I want to match against either the key or the rendered entry does not seem that user-friendly to me. So maybe you want to change this as well? ;-)

Good point. I see two alternatives: Either defining a custom "smart" string for the matching, or simply prepending the key regardless of any options. I partly prefer the latter, as it would not need an extra option.

> Is there any internal cache of vimtex? If so, how can I clean it? When changing the name of the containing dir back to its original name, I still get capital umlauts.

This is also documented; see the note for `:help g:vimtex_complete_bib.menu_fmt`. How to clear the cache depends on the system. On Linux, it is typically located in `~/.cache/vimtex/bibcomplete*.json`.

> Caveats: (1) I had to manually clean the cache again to make the setting work.

Yes, sorry; I don't see any simple way of improving this.

> (2) I (obviously) can no longer see the title when there are many authors in the pop-up menu. It may be worth considering to separate the settings for what is displayed in the menu and what is matched against. But that is probably not part of this issue here. Thanks for your help again!

As mentioned above: perhaps it makes sense to allow a separate setting for the "matching string", as this allows more user control and perhaps more flexibility wrt. the matching.

What do you think, @xileF1337 and @clason?

**Comment by clason** [comment]
Docs are now indeed better, in my eyes.

Personally, I don't mind matching against `word`/`abbrv` _and_ `menu` by default, if that is simple enough to implement. Having a customizable `complete_bib_match_str` would give more freedom, of course; you could make it default to `'@key [@type] @author_all (@year), "@title"'` (without cutoff). I think that would match (ha!) most users' expectations?

But of course it depends how much overhead that adds (probably not much) and how much work it is (probably not little ;))

**Comment by lervag** [comment]
I've added a new issue to describe what we're discussing now. I believe it should resolve the current discussion; please let me know if I missed something that should be addressed as well; and please comment on the suggested specification.

**Comment by xileF1337** [comment]
This covers all my needs and is a much more intuitive behaviour, thank you so much!
