### ISSUE TITLE
Parsing class name fails with multiline declarations

### ISSUE THREAD

**Issue by manu-mannattil** [lervag/vimtex#2092]
I found this problem while investigating #2090.  The fix in 5681b4f0851534ee7785ce7f54a588a12a3ea7a8 correctly parses class names with hyphens, but fails to find the correct class name with multiline declarations, e.g.,

```tex
\documentclass[
  12pt,       % 12 pt font
  a4paper,    % A4 paper
  twoside,    % two-side layout
]{article}

\begin{document}

Hello, world!

\end{document}
```

After opening the above MWE, the class name is not properly resolved and the variable `b:vimtex.documentclass` is empty.

**Comment by manu-mannattil** [comment]
Perhaps the fix is to parse the .fls file before trying a regex match.

**Comment by lervag** [comment]
Thanks! Should be fixed now :)
