### ISSUE TITLE
Changing the surrounding curly brace delimiter does not work.

### ISSUE THREAD

**Issue by xileF1337** [lervag/vimtex#2093]
Hi guys,

I've got another issue with vimtex when changing the surrounding delimiter.

## Issue

 I cannot get the "change surrounding delimiter" (`csd`) functionality get to work with curly braces (`{ }`). For other types of braces, everything works as expected. 

## Example
Here is a minimal example:
```latex
\documentclass{scrartcl}                                                       
                                                                               
\usepackage[T1]{fontenc}                                                       
\usepackage[utf8]{inputenc}                                                    
                                                                               
\begin{document}                                                               
                                                                               
    % csd works.                                                               
    % I can enter a new delimiter, which is substituted for the old one.       
    \{Delimited group\}                                                        
    (Delimited group)                                                          
    [Delimited group]                                                          
    $\left(a^2+b^2=c^2\right)$                                                 
    $\{a^2+b^2=c^2\}$                                                          
                                                                               
    % Doesn't work / 'csd' does not trigger anything.                          
    {Delimited group}                                                          
    ${a^2+b^2=c^2}$                                                            
                                                                               
\end{document}      
```
As you can see, even `\{` is working properly, but not raw `{`.

## Observed Behaviour
For the "working" examples, `csd` triggers a prompt where I can enter a new surrounding delimiter, which is then substituted for the old one. For the examples surrounded by `{`, typing `csd` does nothing.

## Expected Behaviour
`csd` should work for `{` as well.

## Output from VimtexInfo
```
System info                                                                    
  OS: Ubuntu 20.04.2 LTS                                                       
  Vim version: NVIM v0.4.3                                                     
  Has clientserver: true                                                       
  Servername: /tmp/nvimHNQ3Cf/0                                                
                                                                               
VimTeX project: main                                                           
  base: main.tex                                                               
  root: /media/scr/Research/vimtex_tst                                         
  tex: /media/scr/Research/vimtex_tst/main.tex                                 
  out: /media/scr/Research/vimtex_tst/main.pdf                                 
  log: /media/scr/Research/vimtex_tst/main.log                                 
  aux: /media/scr/Research/vimtex_tst/main.aux                                 
  fls: /media/scr/Research/vimtex_tst/main.fls                                 
  main parser: current file verified                                           
  compiler: latexmk                                                            
    configuration:                                                             
      continuous: 1                                                            
      callback: 1                                                              
      latexmk options:                                                         
        -verbose                                                               
        -file-line-error                                                       
        -synctex=1                                                             
        -interaction=nonstopmode                                               
      latexmk engine: -pdf                                                     
  viewer: General                                                              
  qf: LaTeX logfile                                                            
    addqflist: 157                                                             
    fix_paths: 158                                                             
    set_errorformat: 156                                                       
  document class: scrartcl                                                     
  packages:                                                                    
    fontenc                                                                    
    inputenc                                                                   
    keyval                                                                     
    scrbase                                                                    
    scrkbase                                                                   
    scrlfile                                                                   
    tocbasic                                                                   
    typearea                                                                   
```

Thanks for your help!

**Comment by clason** [comment]
What would you expect to happen for `{` (which is not a TeX delimiter in that sense but part of the TeX syntax)?

**Comment by xileF1337** [comment]
I would expect that `csd` behaves the same way as it does for other delimiters, i.e. open a prompt and ask me for the delimiter which I want to replace `{ }`. 

The fact that `{ }` is not printed as a character is not so relevant, right? I may want to edit a `\customcmd{arg1}{arg2}` and make `arg1` an optional argument, thus replacing `{ }` by `[ ]`. I may accidentally have written `{ }` in math mode, but actually wanted visible braces and thus replace by `\{ \}`, etc. Other braces may, depending on the context, also be part of the syntax of some command, still I can replace them. Why not for curly braces?

**Comment by clason** [comment]
But it's _not_ a delimiter, so vimtex's `csd` won't act on it. You can still do vim's internal `csB`, of course (or install one of the more full-featured surround/matchup plugins).

**Comment by xileF1337** [comment]
I can't really see why it is not a delimiter. It obviously delimits the arguments of LaTeX commands, or groups math expressions (i.e. it delimits the groups). It just feels inconsistent to me as a user to have a command to change all types of braces except for the presumably most-often used `{ }`. But ok, if that was your last word, I will just use `vim-surround` (`csB` is not working?).

**Comment by clason** [comment]
Well, the last word is @lervag's, of course. I'm just explaining why your (not completely unreasonable, mind you!) expectation doesn't match what VimTeX does. As the docs explain, the full command that `csd` maps to is `<plug>(vimtex-delim-change-math)`, which is supposed to
> Delete/Change surrounding (math) delimiter.

Note the qualification of "math delimiter", since the word "delimiter" is indeed ambiguous in the context. This indicates that VimTeX is only handling _semantic_ (literal) delimiters, while _syntactic_ delimiters are left to more general-purpose (builtin) plugins. I assume that choice was made to avoid collisions (which can be tedious to handle, as the similar collision with vim-matchup shows).

(You may be right, `csB` is probably from vim-surround, which I have installed and cannot recommend highly enough.)

**Comment by lervag** [comment]
@clason is quite right, and I could not explain the reasoning better myself. `csd` is not meant to change the LaTeX synctactic delimiters, but math delimiters.

@xileF1337 If you are not already using [vim-surround](https://github.com/tpope/vim-surround) or [vim-sandwich](https://github.com/machakann/vim-sandwich), then you are missing out and you should learn one of these immediately. I personally prefer the latter (vim-sandwich), although I know the former is probably more popular. These plugins implement the "change surrounding" command at a general level.
