### ISSUE TITLE
Alone `[` in command with    `@` confuses highlight

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#2094]
In (very rare) cases you have a command using `\@ifnextchar` (from the LaTeX kernel routines). When the checked char is `[`, the syntax highlighter got confused:

```latex
\documentclass{article}
\makeatletter
\def\something{\@ifnextchar[{\addtunablearrow@full}{\addtunablearrow@simple}}%
\makeatother

\begin{document}

Normal text here

\end{document}
```

![image](https://user-images.githubusercontent.com/6414907/125075241-9ef20000-e0be-11eb-9b67-72c235f16e48.png)

Using this minimal vimrc:
```vim
set nocompatible
let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

Now --- this is a very special case, I know, so it's not high-priority at all. Is there a way to "reset" it? (adding a comment with %] does not suffice...)

**Output from VimtexInfo**

```VimTeX project: open-square
  base: open-square.tex
  root: /home/romano/software/bugs/vimtex
  tex: /home/romano/software/bugs/vimtex/open-square.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 51
    fix_paths: 52
    set_errorformat: 50
  document class: article
```

**Comment by lervag** [comment]
I added support for `\@ifnextchar`. Seems cheap and simple, so why not. :)

**Comment by Rmano** [comment]
I hope I haven't  been  guilty of not specifying enough, but there is a series of "ifnextchar" --- the other one I use quite a lot is `\pgfutil@ifnextchar`. Maybe checking for "\\<whatever>@ifnextchar" would be better...

(Sorry, should have been clearer)

**Comment by lervag** [comment]
> ... there is a series of "ifnextchar" --- the other one I use quite a lot is \pgfutil@ifnextchar. Maybe checking for "\ whatever @ifnextchar" would be better...

Ok; perhaps you could provide some reference to the command or family of commands? It is trivial to support `\*@ifnextchar`, of course, so I'll push that asap. But it would be good to understand the source a little bit better.

**Comment by Rmano** [comment]
Yes --- these are commands to "generate" the optional argument in LaTeX (pre-latex3), you can see it there: https://www.texdev.net/2020/08/20/newdocumentcommand-versus-newcommand-versus.

When using packages that are multi-format (ie, that should work in LaTeX, TeX and ConTeXt) normally the package provides a wrapper, like for example `\pgfutil@ifnextchar` that I use in `circuitikz`. I know only about these two version, though, for now.

**Comment by lervag** [comment]
Ok, thanks for the explanation. IIUC, my last commit then resolves the issue for you?
