### ISSUE TITLE
Separate cite completion menu from "smart mode" match string

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#2095]
Cite completion by default matches on the string displayed in the "menu part" of the completion menu which is defined by `g:vimtex_complete_bib.menu_fmt`. As was discussed in #2091, it seems useful to have an alternative option such as `g:vimtex_complete_bib.match_str_fmt` to separate the string displayed in the menu with the string used for cite completion filtering.

Suggested specification: Add new key to `g:vimtex_complete_bib` option with the following documentation (similar to the current `:help g:vimtex_complete_bib.menu_fmt`):

```
                                          *g:vimtex_complete_bib.match_str_fmt*
  match_str_fmt
    Default value: '@key [@type] @author_all (@year), "@title"'
    The format used for the match string for bib completion candidates. That
    is, the string that the smart mode candidate matching is matched against.
    See |vimtex-complete-cites| for more info. See the description of
    `menu_fmt` for the allowed keys.

    Note: If you change this option, you should also clear the related cache
          files (i.e. `~/.cache/vimtex/bibcomplete*.json` on Linux systems).
```

**Comment by xileF1337** [comment]
Sounds great. One thing I wondered about: there is an (internal?) function to clear the vimtex cache, right? If I remember correctly, my tab-completion found something like that at some point. Can the user call it, too? It would be more convenient to have vimtex handle this than manually deleting files in the file manager, and it would also make the documentation platform-independent.

**Comment by lervag** [comment]
> It would be more convenient to have vimtex handle this than manually deleting files in the file manager, and it would also make the documentation platform-independent.

I've implemented `:VimtexClearCache` now. I agree it makes things easier!

**Comment by xileF1337** [comment]
That's awesome @lervag. However, `VimtexClearCache` does not seem to work for me? Neither in vim nor in neovim,  one of the following calls:
```vim
VimtexClearCache bibcomplete
VimtexClearCache bibcomplete.*
VimtexClearCache 'bibcomplete.*'
VimtexClearCache ALL
VimtexClearCache
```
deleted my cache file `bibcomplete%media%scr%Research%Thesis%TeX%thesis.json` residing in `/home/usrname/.cache/vimtex`. 

The file was created only minutes before, so it is definitely the right cache directory. I didn't have the TeX file open when I called the clearing function.

**Comment by lervag** [comment]
Thanks! I think this is fixed now.

**Comment by lervag** [comment]
I've implemented this feature now. Please test it and let me know if you notice any issues. In particular, please check the completion speed, e.g. if you have large bib files.

**Comment by clason** [comment]
I _did_ notice an issue:
```
Error detected while processing function vimtex#complete#omnifunc[30]..136[6]..<SNR>95_filter_with_options:
line   20:
E716: Key not present in Dictionary: "mstr =~? a:regex"
```

(I haven't configured a matching string.)

**Comment by clason** [comment]
Never mind, forgot to clean the cache; after manually removing everything it works fine :)

**Comment by lervag** [comment]
Ah, yes; this is probably gonna raise issues... it _would_ be nice if I implemented some kind of automatic cache cleaning mechanism... I guess I'll just have to answer those issues. :\

**Comment by clason** [comment]
Just make a FAQ on the website: "if in doubt, clean and shout!"

**Comment by xileF1337** [comment]
Couldn't you just add the matching string template and maybe the current version/commit hash to the cache files? Then you compare them when loading the cache data and clean / refresh it if anything has changed.

**Comment by lervag** [comment]
> Just make a FAQ on the website: "if in doubt, clean and shout!"

I instead made a new release which I'll post on reddit. :)

> Couldn't you just add the matching string template and maybe the current version/commit hash to the cache files? Then you compare them when loading the cache data and clean / refresh it if anything has changed.

Yes, this is not a bad idea. Would you mind posting it as a feature suggestion?

**Comment by xileF1337** [comment]
@lervag I'm still struggling with `VimtexClearCache bibcomplete`. While it deleted another bibcomplete cache file, it failed to delete the following:
```
bibcomplete%scr%machinename%usrname%tmp%vimtex_cite_compl%main.json
```
located in `/tmp/vimtex/`, which equals `$XDG_CACHE_HOME/vimtex`.

**Comment by xileF1337** [comment]
> I've implemented this feature now. Please test it and let me know if you notice any issues. In particular, please check the completion speed, e.g. if you have large bib files.

Performance is decent for a bib with about 120 refs!

**Comment by lervag** [comment]
> > I've implemented this feature now. Please test it and let me know if you notice any issues. In particular, please check the completion speed, e.g. if you have large bib files.
> 
> Performance is decent for a bib with about 120 refs!

Good to hear!

**Comment by lervag** [comment]
> @lervag I'm still struggling with `VimtexClearCache bibcomplete`. While it deleted another bibcomplete cache file, it failed to delete the following:
> 
> ```
> bibcomplete%scr%machinename%usrname%tmp%vimtex_cite_compl%main.json
> ```
> 
> located in `/tmp/vimtex/`, which equals `$XDG_CACHE_HOME/vimtex`.

This is strange. Are you able to more precisely describe how I could try to reproduce this? (preferably in a new issue)
