### ISSUE TITLE
Provide support for the runcode package (akin to pythontex)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2096]
The [`runcode`](https://www.ctan.org/pkg/runcode) package is pretty awesome. As per the package description,

> runcodeis a LATEXpackage that executes programming source codes (in-cluding all command line tools) from LATEX, and embeds the results in theresulting pdf file.  Many programming languages can be easily used and anycommand-line executable can be invoked when preparing the pdf file from atex file.

VimteX supports pythontex and sagetex (to a lesser extent). It would be nice to bring support to `runcode` as well and provide a unified interface to all external code runners which return the results as LaTeX markup to stdout.

**Comment by lervag** [comment]
Seems interesting! Can you provide some preferably small, but good examples? And what is meant by "support" - are we talking about more than syntax highlighitng?
