### ISSUE TITLE
Regarding project-specific vimrc files: buffer variable (clarification in documentation)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2099]
For the main file detection, I now find myself in a situation being forced to use the buffer-variable method. This is because my collaborators _a)_ do not want a vim modeline on all files, and _b)_ use arara and not latexmk for building (thus `@default_files` option in latexmkrc is not viable). Finally, I can't use the `.latexmain` file because the main filename changes nearly every fortnight and I need to write on multiple machines, and the collaborators do not like extraneous files. Finally, the recursive method of mainfile detection is very slow due to the huge size of the book (I am writing 3 chapters).

I am thinking of a local `vimrc` file which will also help to obey a few other requirements of the collaborators (and our publisher), namely turn off auto-formatting etc.

`vimtex's` documentation says:

> If one uses project specific |vimrc| files, one may then use an |autocmd| to
> specify the main file through this buffer variable with
>
>   `autocmd BufReadPre *.tex let b:vimtex_main = 'main.tex'`

However, it is unclear how one would go about actually doing this. An example configuration will be helpful.  This is in spirit of numerous other examples given throughout (like configuring zathura and other viewers, contents of ~/.ctags file etc.).  I have only used a global `vimrc` so far, and I am not clear how to set up local `vimrc` that will help to override some settings from my global vimrc. 

Shall much appreciate a documentation update demonstrating the setting of the buffer variable along with necessary hyperlinks to any relevant plugin/blog posts etc.

**Comment by lervag** [comment]
> For the main file detection, I now find myself in a situation being forced to use the buffer-variable method. This is because my collaborators _a)_ do not want a vim modeline on all files,

Note that the TeX root directive is _not_ a Vim modeline thing. It is recognized by a lot of different editors. Are you sure your collaborators will not accept using this mechanism?

> Finally, the recursive method of mainfile detection is very slow due to the huge size of the book (I am writing 3 chapters).

Interesting! I would be quite happy to look into how to improve this. I do not really expect this to be slow. If you would ever be able to create a simple (probably not small; of course) example that demonstrates this slowness, then please let me know.

> I am thinking of a local `vimrc` file which will also help to obey a few other requirements of the collaborators (and our publisher), namely turn off auto-formatting etc.
> 
> `vimtex's` documentation says:
> 
> > If one uses project specific |vimrc| files, one may then use an |autocmd| to
> > specify the main file through this buffer variable with
> > `autocmd BufReadPre *.tex let b:vimtex_main = 'main.tex'`

You are addressing an interesting point. Vim does not really have a concept of a local vimrc file (built in). There are several plugins for handling this, though, e.g. [vim-projectionist](https://github.com/tpope/vim-projectionist). I also found a possibly relevant [blog post](https://andrew.stwrt.ca/posts/project-specific-vimrc/). I believe I may have been thinking about one of these when I wrote that paragraph. I'm not sure if the `set exrc` thing works on neovim, though.

However, note that you can easily add the autocommand to your global vimrc. For instance, you can do something like this:

```vim
" You always want to use a group
augroup vimrc
  autocmd!
  autocmd BufReadPre /path/to/your/book/*.tex
        \ let b:vimtex_main = '/path/to/your/book/main.tex'
augroup END
```

(See `:help file-pattern` for more info on the autocmd file pattern syntax.)

> However, it is unclear how one would go about actually doing this. An example configuration will be helpful. This is in spirit of numerous other examples given throughout (like configuring zathura and other viewers, contents of ~/.ctags file etc.). I have only used a global `vimrc` so far, and I am not clear how to set up local `vimrc` that will help to override some settings from my global vimrc.

I'll change the docs accordingly and remove the mention about local vimrcs.

**Comment by clason** [comment]
> I'm not sure if the `set exrc` thing works on neovim, though.

It does, but is heavily recommended against (same as for vim) due to security concerns.

**Comment by lervag** [comment]
Huh; I tried it and could not get it to work. I tried to add `set exrc`, then create a `.vimrc` file with `echom "test"` in some directory. It did not echo the text.

**Comment by clason** [comment]
I think it has to be called `.exrc`.

**Comment by lervag** [comment]
Ah, ok. Well, in any case, I still think it is best not to delve into the local vimrc settings. Those who want that can learn about it on their own :)

**Comment by krishnakumarg1984** [comment]
Apparently, the concept of a per-directory set-up local vimrc has been discussed here in `vimtex`.

See this issue: [https://github.com/lervag/vimtex/issues/710](https://github.com/lervag/vimtex/issues/710). Karl also mentions the [vim-localvimrc](https://github.com/embear/vim-localvimrc) plugin.

I think using an autocommand in a `global vimrc` has 3 disadvantages:

1. If I decide to move my latex project repo to another path, then I will have to update my global vimrc. Not so good for maintenance. 
2. Won't work across different machines since paths are likely to be different. On Windows machines in my campus library, I use `H:\` drive, a shared network drive that mounts in every machine. On my personal laptop, my projects are in `/home/users/krishna`, whereas on my workstation the path will be `/home/users/krishxxxyyy` which is my employee id number. The path string for the same latex project will be different across machines
3. Committing my .vimrc to a public dotfiles repo will be a privacy issue since my path can contain my username, employee id number etc. 
4. As the number of such projects grow, the number of such paths that needed to be added to the autocommand also grows

I believe that `local vimrc` is the best solution for this issue.

**Comment by lervag** [comment]
> Apparently, the concept of a per-directory set-up local vimrc has been discussed before, here in `vimtex`. See this issue: #710 in which Karl mentions the [vim-localvimrc](https://github.com/embear/vim-localvimrc) plugin (in addition to `.exrc`).

You _are_ going deep, aren't you! :)

> I think using an autocommand in a `global vimrc` has 3 disadvantages:

Of course, I agree with this. But I think that going for project specific vim configuration should be something the user learns about on their own. Still, I'll add an extra comment suggesting this as an alterantive to the global autocmds.
