### ISSUE TITLE
Wrong commentstring in nested LaTeX file

### ISSUE THREAD

**Issue by NicolaiRuckel** [lervag/vimtex#2100]
**Issue**
When using a dockerfile in a LaTeX llisting, `commentstring` gets set to `# %s` while Vim still detects the filetype as being tex.

**minimal.tex**

Create the following document as `main.tex`:
```latex
\documentclass{article}

\usepackage{listings}
\usepackage{minted}

\usemintedstyle{borland}

\setminted{%
  autogobble,
  xleftmargin=20pt,
  linenos
}

\begin{document}

\begin{listing}[ht]
  \begin{minted}{dockerfile}
  FROM java:8
  ADD example-app-1.0.jar app.jar
  EXPOSE 8761
  ENTRYPOINT ["java", "-jar", "/app.jar"]
  \end{minted}
  \caption{Simple \texttt{Dockerfile} example.}
  \label{lst:example-docker}
\end{listing}
\end{document}
```

Running `:verbose set commentstring` gives the following output:
```
commentstring=# %s
      Last set from /usr/share/nvim/runtime/syntax/dockerfile.vim line 38
```

**Output from VimtexInfo**
Run `:VimtexInfo` and paste the content here.

```
System info
  OS: Arch Linux
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /tmp/nvimMERncM/0

VimTeX project: text
  base: text.tex
  root: /home/nicolai/tmp
  tex: /home/nicolai/tmp/text.tex
  out: 
  log: 
  aux: 
  fls: 
  main parser: current file verified
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: General
  qf: LaTeX logfile
    addqflist: 52
    fix_paths: 53
    set_errorformat: 51
  document class: article
  packages:
    listings
    minted
```

**Comment by lervag** [comment]
This is not really a bug in VimTeX; instead, the dockerfile syntax script is bad. It should _not_ set options like this - that's the job of the filetype plugin!

Still, I've added a simple solution for handling this that I think should work well.

**Comment by NicolaiRuckel** [comment]
That means I should probably open an issue in the main nvim repository? Thanks a lot for your fix!

**Comment by lervag** [comment]
Yes, probably. But of course, whoever is responsible for the dockerfile syntax script may disagree with me. :p
