### ISSUE TITLE
Missing '-recorder' option for default run of latexmk (fresh install of vimtex,  revealed by :VimTexInfo output)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2101]
### Issue
In the __Package Detection__ section of `vimtex`'s documentation, it states that:

>If a `.fls` file exists having the name of the main file, it is scanned. This file is created by `latex` (or `pdflatex`, `xelatex`, ...) if it is    run with the __`-recorder`__ option. This is enabled by default with `latexmk`. Parsing the `.fls` file is done both at VimTeX initialization and after each successful compilation, if possible.

However, upon compiling a minimal example using a default install of vimtex without any other plugins, and without any other settings, the `vimtexinfo` command does not indicate that this option has been set. 

### Reproduction

neovim: `nvim -u minimal.vim minimal.tex`

**minimal.vim**
```vim
set nocompatible
let &runtimepath  = '~/.vim/bundle/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

**minimal.tex**
```tex
\documentclass{article}
\begin{document}
Hello world!

Because of
\[
a+b = c
\]
(\textit{Pythogoras}),
and \(y = 2^n g\) with \(n = 1,\dots,10\), we have \(\frac{\Gamma}{2} = 8\).
\end{document}

```
### Commands/Input 
`:VimTeXInfo` or `\li`.
`:VimTeXInfoFull` or `\lI`.

### Observed Behaviour
```
System info
  OS: Ubuntu 21.04
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /tmp/nvim4ckRp2/0

VimTeX project: minimal
  base: minimal.tex
  root: /home/
  tex:  /home/minimal.tex
  out:  /home/minimal.pdf
  log:  /home/minimal.log
  aux:  /home/minimal.aux
  fls:  /home/minimal.fls
  minimal parser: current file verified
  compiler: latexmk
    configuration:
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: 11
    pid: 747137
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -e '$pdf_previewer = "xdg-open"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'minimal.tex'
  viewer: General
  qf: LaTeX logfile
    root: /home/
    addqflist: 57
    fix_paths: 58
    minimal: /home/minimal.tex
    set_errorformat: 56
  document class: article
```

In particular, note the `cmd` option nested under `compiler`. It seems to suggest that the `-recorder` option is not passed to `latexmk`. The `latexmk` options dictionary in the above output also do not contain `-recorder`.

### Expected Behaviour
The `:VimTeXInfo` output shall clearly show that the `-recorder` option is passed to `latexmk`. The options dictionary shall also reflect this.

Otherwise, if it was decided sometime in the past that the `-recorder` option shall not be passed to latexmk, the relevant documentation shall be updated suitably.

**Comment by clason** [comment]
I think you misunderstand the documentation here: this is a default option of `latexmk`, so it is not an extra option that vimtex needs to pass. From `man latexmk`:

>   --recorder
            Give the -recorder option with *latex.  In (most) modern versions of  these  programs,  this
            results  in a file of extension .fls containing a list of the files that these programs have
            read and written.  Latexmk will then use this file to improve its detection of source  files
            and  generated  files after a run of *latex.  **This is the default setting of latexmk, unless
            overridden in an initialization file.**

**Comment by krishnakumarg1984** [comment]
Ah. That's perfect. That explains it. The documentation line which slightly mislead me was `This is enabled by default with latexmk`. As a VimTeX user familiar with its multiple compiler backends, I interpreted it as _This is enabled by VimTeX when using the latexmk compilation backend_.  

Sorry, my mistake.
