### ISSUE TITLE
Documentation clarification: Unclear wording/connection/semantics between vlty, languagetool and YaLafi

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2104]
I have been reading the VimTeX documentation linearly, and reached the section where options are set. In particular, `g:vimtex_grammar_vlty` to configure the `vlty` grammer checker.  I know that there is a detailed section afterwards which discusses the grammer checker in detail, but the following wording (emphasis mine) takes me by surprise:

>    shell_options~
      Pass additional options to __`YaLafi`__, e.g., `--equation-punctuation displ`;
      for more info, see: 
      https://github.com/matze-dd/YaLafi

The problem is that, all options so far between the `g:vimtex_grammar_vlty` and this aforesaid option have the substring `lt` embedded in their names, which is good enough to suggest that somehow the `languagetool` grammar checker is being employed. However, suddenly the name `YaLafi` pops up (for the very first time in the documentation) without any prior reference or mention whatsoever. This is ever so slightly jarring. I looked up [`YaLafi`](https://github.com/matze-dd/YaLafi) and the length of the README.md file slightly intimidates me. 

Furthermore, in the interfaces to `vim` section of the README, the string uses `.` notation for setting the options e.g. `let g:vimtex_grammar_vlty.shell_options` whereas in VimTeX's documentation, it is like a single long dictionary with key-value pairs. For users (who just want to use vim for writing latex) who don't understand vimscript, this is slightly confusing. It would be nice if the alternative syntax is mentioned in VimTex's documentation.

I acknowledge that I can use tag navigation to navigate to the detailed description mentioned later on and come back to continue my reading to make better sense of the option,  but I still think that a bit more context around this array of new words i.e. YaLafi/vlty/LanguageTool shall help someone who is reading linearly.

**Comment by lervag** [comment]
> Furthermore, in the interfaces to `vim` section of the README, the string uses `.` notation for setting the options e.g. `let g:vimtex_grammar_vlty.shell_options` whereas in VimTeX's documentation, it is like a single long dictionary with key-value pairs. For users (who just want to use vim for writing latex) who don't understand vimscript, this is slightly confusing. It would be nice if the alternative syntax is mentioned in VimTex's documentation.

I don't agree; I don't think we should change the VimTeX docs because a separate project uses a syntax that a user may not be familiar with. In this case, you should rather open an issue with YaLafi and make the comment there.

The dot notation quite straightforward and well documented, see `:help dict` and `:help 41.8`.

> I acknowledge that I can use tag navigation to navigate to the detailed description mentioned later on and come back to continue my reading to make better sense of the option, but I still think that a bit more context around this array of new words i.e. YaLafi/vlty/LanguageTool shall help someone who is reading linearly.

I agree, and I've made a minor modification to make this more clear.
