### ISSUE TITLE
Documentation clarification request: version/date of Dr Chip's syntax plugin used as the base for vimtex's syntax highlighter

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2109]
In the documentation, it states that:

> The VimTeX syntax plugin is loosely based on Dr Chip's syntax plugin for LaTeX which is shipped by default with Vim and neovim (|ft-tex-syntax|) [0]. 
> [0]: http://www.drchip.org/astronaut/vim/index.html#SYNTAX_TEX

Can you please clarify in the docs what version of Dr Chip's syntax file was used as the base? Furthermore, Dr Chip has updated their syntax file a few times, the most recent being [version 120, December 2020](https://www.drchip.org/astronaut/vim/syntax/tex.vim.gz). Does VimTeX attempt to stay somewhat in sync with Dr Chip's releases?  It might be relevant since changes in the TeX world are __perceived__ to be slow-moving, whereas in reality, a significant delta can accumulate over the years (esp with LuaTeX release. L3 kernel changes etc). 

It would be nice if info on this base-version info and or syncing frequency is mentioned on the docs.

**Comment by clason** [comment]
You _really_ don't want to start working on that tome, do you 😆  (And I thought _I_ was a master procrastinator...)

The key word here is _loosely_. VimTeX in version 2.0 has completely rewritten the syntax files and should be considered as an independent filetype plugin. This statemement should be considered more as scholarly attribution of influences than a strict dependence. So I don't think "staying in sync" is a meaningful concept, and any errors in VimTeX's syntax highlighting should be reported as issues irrespective of whether they occur with the stock syntax file.

(And I am not aware that either vim's or the upstream `tex.vim` covers LuaLaTeX or LaTeX3 at all.)

**Comment by krishnakumarg1984** [comment]
Hehe. That's actually true. Trying to get to the weekend without writing :). The excuse I tell myself is __"It's been a few months since I've read the vimtex manual. So, need to do it now before writing"__.

On the topic of the new syntax groups etc, I know there was a significant rewrite/upgrade for the 2.0 release wherein a ton of new groups are added. For the lay user without familiarity with `vimscript`, all that they want to know is, how to make their editing experience better, and work with their colorscheme.  This info is not obvious from the documentation. 

Is the user expected to add any lines to their `vimrc` to take advantage of the new syntax groups in VimTeX 2,0+? If so, what are they? And how does it interfere with their colorscheme? Are there any recommended colorschemes that go well with VimTeX 2.0+?

**Comment by clason** [comment]
I don't think it's reasonable to expect that VimTeX replicates basic vim documentation. Someone using VimTeX should be assumed to be familiar with basic vim usage (at least to the extent to know where to look or how to Google for more information). But the documentation actually already goes far beyond the call of duty in explaining things in `:h vimtex-syntax-core` which also gives links to descriptions of how to add additional user highlighting rules to color schemes. The new groups themselves (at least for core syntax if not all packages) is _extensively_ documented in `:h vimtex-syntax-reference`.

I am not aware of any colorscheme that supports these out of the box, but you could take a look at my own [personal color scheme](https://gist.github.com/clason/f62c9849c2e634f314c546f2e8b0585b) as a basis for yours. (After all, the whole point of adding these new groups is for people to be able to customize their color scheme exactly how _they_ like it -- In case they need another excuse not to start with the _actual_ work...)

Also, may I mention the vimtex chatroom at https://gitter.im/vimtex-chat/community ? Asking questions there before having "discussions" in Github issues would reduce the noise on the issue tracker.

**Comment by lervag** [comment]
I think @clason mostly covers what I want to say, but just to make it more official:

> Can you please clarify in the docs what version of Dr Chip's syntax file was used as the base?

I think it might have been version 119, but I don't fully remember.

> Does VimTeX attempt to stay somewhat in sync with Dr Chip's releases?

No. The syntax scripts in VimTeX are really written from scratch and I don't quite see a single reason to stay in sync. I don't think there is much to synchronize anyway.

> For the lay user without familiarity with `vimscript`, all that they want to know is, how to make their editing experience better, and work with their colorscheme. This info is not obvious from the documentation.

Mostly, it should be _automatic_ as long as one uses a modern colorscheme. However, as @clason already writes quite well, VimTeX allows a much higher degree of customizability. This can be utilized by users or by writers of colorschemes. I have tried to make it more or less clear how to take advantage of the new syntax groups in `:help vimtex-syntax`, and in particular `:help vimtex-syntax-core` and the following subsections. Note the introduction of the core specification, which guides users to read a list of resources to learn about writing colorschemes and overriding colorschemes, and so on.

> Is the user expected to add any lines to their `vimrc` to take advantage of the new syntax groups in VimTeX 2,0+?

No, not expected, but allowed.

> If so, what are they?

Read `:help vimtex-syntax-core` and the suggested resources.

> And how does it interfere with their colorscheme?

It clearly depends on the colorscheme.

> Are there any recommended colorschemes that go well with VimTeX 2.0+?

I think most colorschemes should work well, in general, but I don't really know. I've also personally, similar to @clason, made a lot of adjustments. I run [my own colorscheme](https://github.com/lervag/dotnvim/blob/main/personal/colors/my_solarized.vim) (Solarized light, but with some customizations).

----

But, of course: It is always possible to improve the docs, and feel free to either suggest improvements as you spend more time with it, or to point out specific shortcomings.
