### ISSUE TITLE
VimtexCompileSingleShot for current tex file

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#211]
How about VimtexCompileSingleShot accepting as optional Parameter a TeX file name, that, if given, would be compiled instead of the Main file?

**Comment by Konfekt** [comment]
I am thinking in particular about :VimtexCompileSingleShot %.

**Comment by lervag** [comment]
Agreed, this is a good feature that I think should be implemented. I will do it when I get the time.

**Comment by Eisfreak7** [comment]
As suggested in #280:
It'd be great if it would also be possible to set the file to be compiled by the continuous mode. That would be handy when working on a subfile, because it can speed up the compilation enormously and give faster feedback.

**Comment by lervag** [comment]
So, I've implemented a toggle that allows one to consider the subfile as a dedicated project. It is mapped by default to `<localleader>ls`. This should be a nice solution for people who use subfile.

I know this is not what was asked in the OP, and so the issue remains open. But I'm wondering if it might solve the "original" problem @Konfekt?

**Comment by Konfekt** [comment]
Thanks! That's a fine solution, though it would be intuitive to allow this for SingleShot compiles as well

**Comment by Eisfreak7** [comment]
It solves my problem, thanks!

**Comment by lervag** [comment]
@Konfekt You're right. There is no real reason to restrict this to subfiles. I think I could make a very simple update where I allow the toggle to work for any file. Obviously, if a user toggles this for a file with no preamble, it won't compile. But then again, users should know what they are doing... in any case, I'll push the update in a few minutes.

I think the update should also include a change of names for the command and mapping. Any proposals or ideas? The first that comes to my mind is: `VimtexToggleLocal`. Or perhaps `VimtexFocus`? In the meantime, I keep the current names (although the toggle will now work on any file).

**Comment by Konfekt** [comment]
Thanks again, the idea was that sometimes you need two versions of an article say, so not restricting to subfiles goes along with that. Call it perhaps VimtexCompileMainToggle

**Comment by lervag** [comment]
Hm, no, VimtexCompileMainToggle implies that the command has something to do with compilation. It really doesn't, it only changes the file that is considered the main file, which is relevant for very many other commands.

Perhaps VimtexToggleMain or VimtexMainToggle?

**Comment by Konfekt** [comment]
yep, perhaps VimtexMainfileToggle would be more speaking.

**Comment by lervag** [comment]
Let me know if you have any problems with this new feature!

**Comment by ludovicschwartz** [comment]
7 Years later, this is still very useful ! In my case, most of the time working with subfiles I will like the current file to be compiled. While this can be achieved by the VimtexMainfileToggle command, it would be nice to have a parameter in the config to make it the default behaviour for subfile(Something like SubfileMainDefault set to True or False). If you think that's an interesting thing to do, I could look into it in more details and try to make a PR. Let me know !

**Comment by lervag** [comment]
> 7 Years later, this is still very useful ! In my case, most of the time working with subfiles I will like the current file to be compiled. While this can be achieved by the VimtexMainfileToggle command, it would be nice to have a parameter in the config to make it the default behaviour for subfile(Something like SubfileMainDefault set to True or False). If you think that's an interesting thing to do, I could look into it in more details and try to make a PR. Let me know !

First, just a friendly comment: I really prefer that you open a new issue even for simple questions, instead of "bumping" old threads.

I'm curious if `:help g:vimtex_subfile_start_local` may be what you are looking for? If not, then please open a new issue and I'll be glad to consider it as a feature request!

**Comment by ludovicschwartz** [comment]
Hi, your comment is noted for future question. Indeed the vintex_subfile_start_local is exactly what I was looking for, I just couldn't find it in the doc. Thanks a lot again !

**Comment by lervag** [comment]
Great, and I'm glad to help! :-)
