### ISSUE TITLE
Optional folding when backward searching

### ISSUE THREAD

**Issue by Eryx5502** [lervag/vimtex#2110]
Hi!

When using backward search (at least with zathura as viewer), the function `vimtex#view#reverse_goto` is used to jump to the correct location in the .tex. Right now this function perfoms a folding (with `normal! zMzvzz`), which folds some things out if folding is enabled.

It would be useful (at least to me) to be able to have folding enabled but not getting the fold status of the buffer changed when using backward search. I haven't found an option to modify this behaviour through the docs, so right now I have commented out the line doing the folding as a workaround.

**Comment by lervag** [comment]
> Hi!

Hi! :)

> When using backward search (at least with zathura as viewer), the function `vimtex#view#reverse_goto` is used to jump to the correct location in the .tex. Right now this function perfoms a folding (with `normal! zMzvzz`), which folds some things out if folding is enabled.

I can see how this is opinionated! Perhaps it would be better to remove the `normal!` command and add an event that allows the user to customize this action?

E.g., to get the current behaviour, my suggestion implies that users would have to add something like this to their vimrc file:

```vim
augroup VimTeX
  autocmd!
  autocmd User VimtexReverseGoto normal! zvzz
augroup
```

**Comment by Eryx5502** [comment]
That sounds like a nice solution, and the posibility of further customization could be useful for some users.

Thanks for the awesome work!

**Comment by lervag** [comment]
Great, I've implemented this now. Let me know what you think. Notice the new example under `:help VimtexEventViewReverse` in the docs.
