### ISSUE TITLE
Explore the possibility of a <plug>vimtex_open_beamer_viewer command and g:vimtex_beamer_viewer mapping

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2115]
There exist some specialised PDF presenter tools (with presentation view, dual-screen support etc). The aspect ratio/page size of beamer presentations (4:3 or 16:9) are obviously quite different to a standard A4/letter paper PDF. 

For each rehearsal iteration in the PDF presentation tool, there is a typical ongoing need to enhance/edit/polish/fine-tune content from a selected subset of frames being viewed at the current presenter view without having to reload the presentation. This is especially convenient when using tiled window managers like `i3` where the editor is on a particular workspace, and the presentation PDF is arranged as per desire (speaker notes on bottom, next slide preview,  speaker view slide-timer) in another workspace window. 

All that the author wants to do is make a quick tweak of a bullet point, or image, and just resume the slide rehearsal. With standard viewers like `zathura`, while it can do a live reload seamlessly (just like for any document), we don't get the benefits of continuing the speaker view from where we left off.  Let's say we were practising the presentation until slide 5, and had to make a quick edit. It is a bit inconvenient to reload the presentation manually with mouse and GUI clicks etc.

It would be pretty seamless if VimTeX can provide an interface to a few of these presentation-centric PDF tools. See a nice compilation of such tools [here on TeX.SX](https://tex.stackexchange.com/questions/84622/is-there-a-specialized-pdf-viewer-for-latex-beamer-presentations-on-linux). Among these, for presentations, it is vital to have a cross-platform tool which runs on Windows, mac and Linux with the same UI and keybindings. Though `pdfpc` is the top-ranked answer and generally superior, it does not work on Windows (or Wayland). In 2019, I struggled with this issue at a conference because the auditorium's presentation system had a fancy cabling through the furniture/walls etc to a dedicated desktop running Windows. The organisers said both PDF and PPT shall be fine, but I had practised my talk with `pdfpc`! They were even happy to let me install any software to help me present, but obviously, I had to make do with Acrobat viewer's presenter mode (without dual screen support, speaker notes etc). The other tool mentioned there is `impressive`, which is Windows-only (and is a no-go for developing on my personal machines). The only actively developed cross-platform PDF presenter is `pympress`, and I am satisifed on all 3 OSes I have tried.

Can VimTeX provide an option like `g:vimtex_beamer_viewer` which interfaces with some of these tools. This will default to whatever document viewer the user has configured in their `.vimrc` (zathura, okular, mupdf, skim, sumatrapdf or whatever)? In summary, the user needs to have independently controllable settings for general PDF document viewing and beamer presentation PDF viewing, taking into cognisance the fact that beamer PDFs have fundamentally different use-cases (although the same editor is used for creating both: a `one-to-many` mapping!). Users can open the general PDF viewer with `\lv` as usual, and beamer PDFs with `\lb` (or `\lp`) and therefore will need a plug command/mapping to be defined as well. This might perhaps not be such an unusual request as well given that a context-specific PDF viewer has been added in recent times to VimTeX.

**Comment by clason** [comment]
It's (again) not quite clear what you actually want here:

1. Some (standard) PDF viewers do not reset the view when reloading a file, so you could just use one of them.
2. If they do, you could just add a call to forward search to the hook after building successfully.
3. There is already support for adding your own viewer that is not supported out of the box, see `g:vimtex_view_general_viewer`.

Also, I would challenge your claim that working on a beamer presentation is so radically different from working on any other TeX file that it needs a new, completely separate viewer setting. The workflow you describe sounds exactly the same as when proof-reading a paper/book/lecture notes/whatever.

(And the "context-specific PDF viewer" is the viewer opened via the context menu, not for ConTeXt files...)

**Comment by krishnakumarg1984** [comment]
>Some (standard) PDF viewers do not reset the view when reloading a file, so you could just use one of them.

Yes. I already mention that `zathura` does this (skim and sumatrapdf too). No that won't work because, they don't provide options such as presenter view. 

> If they do, you could just add a call to forward search to the hook after building successfully.

How do I do this only for Beamer PDFs? I want to use a standard PDF viewer for all my other documents. This morning I worked on a paper, and in the afternoon I am preparing slides.Obv, I don't want to change  my viewer options in `.vimrc` every hour!

> There is already support for adding your own viewer that is not supported out of the box, see g:vimtex_view_general_viewer.

Yes. I am aware of it. I need `zathura` for my documents, and need to view Beamer PDFs in a specialised viewer. 

>Also, I would challenge your claim that working on a beamer presentation is so radically different from working on any other TeX file that it needs a new, completely separate viewer setting.

I hereby provide a factual rebuttal for this by presenting the fact that most standard PDF viewers do not support dual-screen monitors or slide timers.  In specialised PDF viewers, I get a slide timer denoting how much time is spent per slide, and total time spent in a talk. As we know, conferences are strict about timings, and I find it convenient to have a powerpoint-like "presenter view" with a timer and preview of next screen etc. 

So, yes. _Viewing a Beamer presentation in presenter mode is indeed a __radically different__ use-case than viewing a journal article_. Presumably, the user doesn't need a countdown timer or a preview of the next page or dual-screen support :) 

> (And the "context-specific PDF viewer" is the viewer opened via the context menu, not for ConTeXt files...)

Yes. And, I meant context-menu as well. My point was that, there is already a precedent in that VimTeX has already incorporated the possibility of setting a different viewer for a specific use-case.  I am just requesting another valid use case for a different viewer to be called. That's all.

**Comment by lervag** [comment]
If I understand correctly, what you want can be boiled down to this:

* A command to view the current project in a beamer specific PDF viewer.
* Configuration option for specifying the desired viewer (`g:vimtex_beamer_viewer`).

I understand the motivation for this request, and I agree that the act of viewing PDFs for presentation mode is _different_ than for reading/viewing regular PDFs. I can see that what you are proposing might help during a workflow where you're incrementally improving a presentation _while_ you are timing it.

And thanks for the amusing screenshot example!

However: I am not quite convinced that it makes sense to add this to VimTeX. My thoughts are in ways similar to @clason's, but perhaps in a more pragmatic way. In particular, there are three reasons I hesitate:

1. Vim users should learn to configure their editors. What you ask can be implemented on the user side with a single mapping where the user has full control. One line if you use a personal `ftplugin/tex.vim`, or a couple more if you use an autocmd in your vimrc file:

    ```vim
    augroup vimrc_vimtex
      autocmd!
      autocmd FileType tex nnoremap <localleader>lb :call system('pdfpc ' . b:vimtex.out() . '&')<cr>
    augroup END
    ```

  Of course, this can be further customized, e.g. to handle the case where the output file is not present:

    ```vim
    function! MyBeamerViewer()
      try
        let l:out = b:vimtex.out()
      catch /.*/
        let l:out = ''
      endtry

      if empty(l:out) | return | endif

      call system('pdfpc ' . l:out . '&')
    endfunction

    augroup vimrc_vimtex
      autocmd!
      autocmd FileType tex nnoremap <localleader>lb :call MyBeamerViewer()<cr>
    augroup END
    ```

2. The specific workflow in which this feature seems useful also seems to me like a quite specific edge case. That is, in most cases, you could use Zathura (or whatever) for developing your presentation.

3. Adding this as a feature requires more work, because it must be thought through. We need consistency, documentation which includes discoverability of the new feature, and more. Considering the "simplicity" of personal custom mappings (of course, assuming the user knows how), I don't quite find this work worth the effort.

I might consider it if someone else takes the bulk workload and suggests it with a PR, but even then I would have to be convinced that the maintenance burden is worth the effort.

**Comment by krishnakumarg1984** [comment]
Alright. I rest my case. Will work with the mappings you helped me with. 

>Vim users should learn to configure their editors. 

That mapping is some next-level `vimscript-fu`. Using `vim` for writing text, and grokking an esoteric configuration language are two different things, innit? :)

Thanks again for providing the custom mapping!

**Comment by lervag** [comment]
Heh, perhaps I'm "too strict" with my "should" statement. I can understand that not everyone will learn (or be interested in learning) advanced Vim configuration (and vimscript). Feel free to PM me if you need more help in making a suitable personal mapping for this.

**Comment by krishnakumarg1984** [comment]
No issues at all. I am reasonably happy with the outcome. If more people require such mappings, then they can refer to this issue for posterity, and put together a concrete PR if necessary.
