### ISSUE TITLE
Labels and captions of subfolds incorrectly displayed in top-level folds

### ISSUE THREAD

**Issue by gjgress** [lervag/vimtex#2117]
**Issue**
As discovered in PR #2107 in the comment [here](https://github.com/lervag/vimtex/pull/2107#issuecomment-886125204), the labels and captions of environments within another environment are incorrectly displayed in the top-level fold, even if the top-level fold has its own labels and captions.

**Observed Behaviour**

```tex
\begin{thm}[Theorem 1]
\label{thm:theorem_1}
\caption{theorem 1 caption}
...
\begin{figure}
\label{fig:figure_1}
...
\caption{figure 1 caption}
\end{figure}
...
\end{thm}
```

is currently folded as:

```
\begin{thm}[Theorem 1]     figure 1 caption                                             (fig:figure_1)
```

**Expected Behaviour**

instead of the proper folding:

```
\begin{thm}[Theorem 1]     theorem 1 caption                                         (thm:theorem_1)
```

This is caused by the `fold_parse_label` and `fold_parse_caption` functions here:

https://github.com/lervag/vimtex/blob/a064c48ade2a4df3d010e02b2d528fc2534a62eb/autoload/vimtex/fold/envs.vim#L118-L142

Fixing this will involve rewriting the function to not search subfolds.

**Output from VimtexInfo**

Should be irrelevant in this case, but for the sake of consistency:

```
System info
  OS: Manjaro Linux
  Vim version: VIM 8.2 (1-3171)
  Has clientserver: true
  Servername: undefined (vim started without --servername)
```

**Comment by lervag** [comment]
Thanks for the clear issue description! Let's consider this after #2107 has been merged. I'm out of time now, but perhaps I'll have time to look at it tomorrow.

**Comment by lervag** [comment]
I believe I've fixed this now. Please test! :)
