### ISSUE TITLE
Latexmk `internal` keyword (sh: 1: internal not found)

### ISSUE THREAD

**Issue by camilstaps** [lervag/vimtex#212]
I have the following in my `.latexmkrc`:

    pdflatex = 'internal musixlatex %R %O %S';
    push @generated_exts,"mx2";
    push @generated_exts,"mx1";
 
    sub musixlatex {
       my $root = shift;
       # Define root filename for the mx1 and mx2 files
       # Note that $aux_dir1 includes directory separator
       #      and it equals $out_dir1 if only the out_dir is set.
       my $mx = "$aux_dir1$root";
       my @args = @_; 
       if ( $pass{$rule} <= 1 ) { 
          print "======= FIRST PASS: Deleting '$mx.mx2' =======\n";
          unlink "$mx.mx2"; 
          print "====   Generating '$mx.mx1' then '$mx.mx2' ===\n";
          my $ret = system( "pdflatex @args" );
          if ($ret) { return $ret; }
          $ret = system( "musixflx $mx" );
          if ($ret) { return $ret; }
       }
       return system( "pdflatex @args" );
    }

Running `latexmk -pdf ...` from the command line works perfectly. However, `VimtexCompile` gives me the following error:

    Latexmk: Need to remake files.
      File changes, etc:
       Changed files, or newly in use since previous run(s):
          'songbook.tex'
    Rule 'pdflatex': File changes, etc:
       Changed files, or newly in use since previous run(s):
          'songbook.tex'
    ------------
    Run number 1 of rule 'pdflatex'
    ------------
    ------------
    Running 'internal -file-line-error musixlatex "songbook"  -recorder  "songbook.tex"'
    ------------
    Latexmk: All targets (songbook.pdf) are up-to-date

    === Watching for updated files. Use ctrl/C to stop ... 
    Latexmk: applying rule 'pdflatex'...
    sh: 1: internal: not found
    Latexmk: fls file doesn't appear to have been made
    Latexmk: Log file says output to 'songbook.pdf'
    Latexmk: Failure to make the files correctly
        ==> You will need to change a source file before I do another run <== 
    Collected error summary (may duplicate other messages):
      pdflatex: Command for 'pdflatex' gave return code 32512

I didn't change any of VimTeX's default options. What could be causing Latexmk to fail when run by VimTeX?

**Comment by lervag** [comment]
That's an interesting issue. I think we should be able to get this to work.

I'm curiuos: When you open the tex file and then do `:VimtexCompile`, and if you use pure default settings, then you should not immediately get the above error. Did you already use `:VimtexCompileOutput` to see the error?

In any case, after you have issued the `:VimtexCompile` command, could you then do `:VimtexInfo` and past the result here? In particular, I am interested in the content of the `cmd_latexmk_compile` string, which is the command issued by vimtex to start the compilation.

**Comment by camilstaps** [comment]
Indeed, I also ran `:VimtexCompileOutput`. Here is the output of `:VimtexInfo`:

    b:vimtex : songbook
      root : '/.../songbook'
      aux : '/.../songbook/songbook.aux'
      log : '/.../songbook/songbook.log'
      out : '/.../songbook/songbook.pdf'
      tex : '/.../songbook/songbook.tex'
      tmp : '/tmp/vBtnOMe/1'
      pid : '18578'
      cmd_latexmk_compile : 'cd ''/.../songbook'' && max_print_line=2000 latexmk -pdf -e ''$pdflatex =~ s/ / -file-line-error /'' -pvc -e ''$new_viewer_always = "0"'' -e ''$pdf_update_method = "0
    "'' -e ''$pdf_previewer = "start xdg-open "'' ''songbook.tex'' >/tmp/vBtnOMe/1 2>&1'
      base : 'songbook.tex'
      viewer
        init : function('6')
        view : function('7')
        latexmk_append_argument : function('8')
 
Thank you for looking into this!

**Comment by lervag** [comment]
I notice from this output that you are not on the latest version. Please update (`git pull` or similar).

I've also briefly looked at the [latexmk manual](http://ctan.uib.no/support/latexmk/latexmk.txt), where I see that the `internal` method makes the entire command line passed to an internal procedure. Thus all the options vimtex is adding will be ignored.

Perhaps is there a way to do what you want without the `internal`?

**Comment by camilstaps** [comment]
Sorry for the mess, I thought I didn't create the pull requests yet. 

Anyway... I changed the regex substitution a little bit to not perform any if the `internal` keyword is at the beginning of the string. Could you have a look at the pull request?

This `internal` routine is needed for MusiXTeX. The workflow you need is:

1. Remove old *.mx2
2. Run pdflatex
3. Run musixflx
4. Run pdflatex

That's a little difficult without `internal`, that's why.

**Comment by lervag** [comment]
Sorry for taking so long! Life has been ... busy...

And thanks for explaining; I can see that the `internal` routine is necessary for some cases, including yours. I will consider your pull request. If it is OK by you, I will close this issue and we can continue the discussion in the pull request thread #213.
