### ISSUE TITLE
Vimtex error with vim-pandoc-syntax

### ISSUE THREAD

**Issue by listout** [lervag/vimtex#2120]
When trying to open a pandoc flavored markdown file [pandoc.markdown] an `Error detected while processing function` is shown.

![pandoc_error](https://user-images.githubusercontent.com/66715002/127110688-6a64d993-ce18-497b-848c-7fc0d4ee58aa.png)

Minimal vimrc

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'lervag/vimtex'
Plug 'vim-pandoc/vim-pandoc-syntax'
call plug#end()

augroup pandoc_syntax
	au! BufNewFile,BufFilePre,BufRead *.md set filetype=markdown.pandoc
augroup END
```
Reproduce the issue

```
vim -u init.vim test.md
```

Even tried with vim-plugs lazy loading feature, same issue.

---

Reversing back to commit `b292c2a` seems to fix the issue. I have tried reverting back to some commits in vim-pandoc-syntax, while keeping vimtex at current head (`b4fc8ae`), but the problem still remained.

**Comment by lervag** [comment]
I believe this is fixed now. I'll figure out another way of doing what I wanted to do. Thanks for the detailed issue report, it will be helpful for testing!

**Comment by listout** [comment]
Thank you
