### ISSUE TITLE
Support for autocompletion of commands defined through `\DeclarePairedDelimiter` and other "command-defining" commands like `\NewDocumentCommand`

### ISSUE THREAD

**Issue by rionda** [lervag/vimtex#2123]
The commands that are locally defined through `\newcommand` show up in the autocomplete tab from, e.g., YouCompleteMe, I assume through some magic in vimtex =).

It would be nice to also have the commands that are defined through `\DeclarePairedDelimiter` (I believe it is from `mathtools`) and `\DeclareDocumentCommand` and `\NewDocumentCommand` (from `xparse`) added to the list for autocompletion.

Thanks!
Matteo

**Comment by lervag** [comment]
That might be possible, but it would be very helpful with more info. Especially, some good examples and reference to the relevant commands would be in order.

**Comment by rionda** [comment]
For example, I almost always declare the following for absolute values or set cardinalities:

```latex
\DeclarePairedDelimiter\abs{\lvert}{\rvert}
```

and use it as `\abs{S}` to get `|S|`. It is described in section 3.6 of the [`mathtools` guide](https://texdoc.org/serve/mathtools.pdf/0). Essentially, I would like the autocomplete to suggest `\abs` when I start typing `\ab` or similar.

`\NewDocumentCommand` and `\DeclareDocumentCommand` are a little more convoluted because they are extremely flexible, but all we care about is the name of the command that is declared. 
Here is an example
```latex
\DeclareDocumentCommand\domain{mo}{% {method}[graph]
  \symcal{D}_{#1%
    \IfNoValueTF{#2}{}{,#2}%
  }%
}
```
which I can use as `\domain{B}` or `\domain{B}[A]`. They are described in the [`xparse` documentation](http://mirrors.ctan.org/macros/latex/contrib/l3packages/xparse.pdf). 

Hope this helps, and thanks for considering it.

Matteo

**Comment by lervag** [comment]
Please test now. The xparse command was already supported, actually, but only with `\DelcareDocumentCommand{...}` syntax. I think it should work more generally now.

**Comment by rionda** [comment]
Seem to work! Thank you!

**Comment by lervag** [comment]
Glad to hear it! :)
