### ISSUE TITLE
VimtexTocOpen sometimes adds a spurious extension to filenames

### ISSUE THREAD

**Issue by alexandreroberts** [lervag/vimtex#2126]
I am experiencing an issue similar to [this one](https://github.com/lervag/vimtex/issues/1543): sometimes (not always) `:VimtexTocOpen` adds a spurious `.tex` to the end of filenames; for example, the line `\import{FILEPATH}{general.header.tex}` results in a TOC entry `tex incl: general.header.tex.tex`.

Relatedly, sometimes it ignores `FILEPATH` in the command `\import{FILEPATH}{FILENAME}`, printing only `FILENAME` rather than `FILEPATH/FILENAME`.

So the issue seems to be how `vimtex` parses `\import` commands. Curiously, it sometimes works and sometimes does not work. I haven't been able to discern what is different about those cases (they all involve the same `FILEPATH`, which reads, in my case `/Users/alexandre/Dropbox/TeX-Alex-custom-files/`).

The reason I noticed this problem is that it makes `vimtex` sometimes unaware of the `.bib` files I load, thus making citation completion not work.

**Output from VimtexInfo**

```
System info
  OS: Mac OS X 10.15.6 (19G2021)
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /var/folders/92/6c80fs_55hnf_1s2ybgbv5c40000gn/T/nvim5VO5rw/0

vimtex project: _souda-chemeia
  base: _souda-chemeia.tex
  root: /Users/robe941/Dropbox/Projects/1c-ABOUT-TO-SUBMIT/souda-chemeia-AlchByzVol
  tex: /Users/robe941/Dropbox/Projects/1c-ABOUT-TO-SUBMIT/souda-chemeia-AlchByzVol/_souda-chemeia.tex
  out: /Users/robe941/Dropbox/Projects/1c-ABOUT-TO-SUBMIT/souda-chemeia-AlchByzVol/_souda-chemeia.pdf
  log: /Users/robe941/Dropbox/Projects/1c-ABOUT-TO-SUBMIT/souda-chemeia-AlchByzVol/_souda-chemeia.log
  aux: /Users/robe941/Dropbox/Projects/1c-ABOUT-TO-SUBMIT/souda-chemeia-AlchByzVol/_souda-chemeia.aux
  fls: 
  tex program: xelatex
  source files:
    _souda-chemeia.tex
    sections/0-to-add.tex
    sections/1-intro.tex
    sections/2-body.tex
    sections-compiled-by-Makefile.tex
    sections/3-conclusion.tex
    _outline.tex
  compiler: latexmk
    backend: nvim
    output: /var/folders/92/6c80fs_55hnf_1s2ybgbv5c40000gn/T/nvim5VO5rw/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -xelatex
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: memoir
  packages:
    chemformula
    geometry
    import
```

**Comment by lervag** [comment]
> So the issue seems to be how `vimtex` parses `\import` commands. Curiously, it sometimes works and sometimes does not work. I haven't been able to discern what is different about those cases (they all involve the same `FILEPATH`, which reads, in my case `/Users/alexandre/Dropbox/TeX-Alex-custom-files/`).

It is very difficult to debug a problem if I can't reproduce it. Could you try to find a reliable manner in which you can reproduce the problem you are experiencing and provide a minimal example?

**Comment by alexandreroberts** [comment]
I've tried to make a minimal example, but when I do, it doesn't have the problem. It's very odd. In fact, two different projects with nearly identical main files have divergent results: one has the problem, the other doesn't.

Here is what the beginning of my main project file looks like:
<img width="820" alt="Screen Shot 2021-08-06 at 9 49 55 PM" src="https://user-images.githubusercontent.com/6886906/128588321-35a1ade8-00ec-484a-b321-48869855ad89.png">

and here is the relevant part of the Vimtex TOC:
<img width="707" alt="Screen Shot 2021-08-06 at 9 49 35 PM" src="https://user-images.githubusercontent.com/6886906/128588342-0f83cfe8-8d36-4a18-a0f9-8ee07f1b8fe6.png">

Note the double `.tex.tex` in the TOC on *some* but not all of the included tex files.

Most puzzlingly, my main file calls `specific.ByzAlchVol.tex`, which in turn calls `biblio.ByzAlchVol.tex`; somehow the TOC knows about `biblio.ByzAlchVol.tex`, but when I select `specific.ByzAlchVol.tex.tex` and go to the file, it brings me to a blank. It's as if it's reading the correct file but then losing track of it.

The `biblio.ByzAlchVol.tex` then refers to the `.bib` file, which is *not* mentioned in Vimtex's TOC. 

I know this isn't what you asked for, but I am hoping at least that these further details may help in making sense of what is going on.

**Comment by alexandreroberts** [comment]
Also, why does the TOC include the whole long filepath (`/Users/alexandre/`etc.) for some of the files (namely the ones called by `general.header.tex`) but not the earlier ones, which are in fact in the same directory as them?

Curiously, when I select those files with the long filepath, they *do* still link to the correct file. Could this have something to do with the problem? That somehow it is clipping the filepath from the earlier ones and thus losing track of them?

**Comment by alexandreroberts** [comment]
In fact, now I see that those files with the long filepath are referenced in `general.header.tex` using `\input`, not `\import`, so maybe the problem is that sometimes (and I still don't understand why it doesn't always happen) `vimtex` forgets the filepath for files referenced using the `\import` command.

**Comment by alexandreroberts** [comment]
For reference, here is the main file of the project where this problem does *not* occur.
<img width="827" alt="Screen Shot 2021-08-06 at 10 04 17 PM" src="https://user-images.githubusercontent.com/6886906/128588646-48057b36-9126-4ef5-a010-b242ae4e7df2.png">

I really can't see what's different about it other than the specific file it loads `specific.JLAIBS.tex` instead of `specific.ByzAlchVol.tex`.

And here is what the TOC generated from it looks like:

<img width="695" alt="Screen Shot 2021-08-06 at 10 04 48 PM" src="https://user-images.githubusercontent.com/6886906/128588663-0a72e1a0-379d-46ff-88a4-53022048eb68.png">

**Comment by alexandreroberts** [comment]
Ah! Here is something: `specific.JLAIBS.tex` loads `biblio.JLAIBS.tex` using an `\input` command with the whole filepath, whereas `specific.ByzAlchVol.tex` relies on `import` to load `biblio.JLAIBS.tex` with a simple `\input{biblio.JLAIBS.tex}` command, without the filepath. Perhaps that is where Vimtex is getting tripped up?

This still wouldn't explain the double `.tex.tex` and the links to files that don't work, but maybe it helps?

Sorry to keep thinking aloud.

**Comment by alexandreroberts** [comment]
After all that, I have fiddled with my minimal example and *was* in fact able to reproduce the error. Here it is, as a ZIP file: 
[vimtex-import.zip](https://github.com/lervag/vimtex/files/6948622/vimtex-import.zip). If you open `main.tex` and run `VimtexTocOpen` on it, you will see the issue (or at least I do on my computer).

**Comment by alexandreroberts** [comment]
Output from VimtexInfo in this case was:

```
System info
  OS: Mac OS X 10.15.6 (19G2021)
  Vim version: NVIM v0.5.0
  Has clientserver: true
  Servername: /var/folders/92/6c80fs_55hnf_1s2ybgbv5c40000gn/T/nvimsKig4A/0

vimtex project: main
  base: main.tex
  root: /Users/robe941/Dropbox/tex-issues-and-MWEs/vimtex-import
  tex: /Users/robe941/Dropbox/tex-issues-and-MWEs/vimtex-import/main.tex
  out: 
  log: 
  aux: 
  fls: 
  tex program: xelatex
  source files:
    main.tex
    file-that-calls-bib-file.tex
  compiler: latexmk
    backend: nvim
    output: /var/folders/92/6c80fs_55hnf_1s2ybgbv5c40000gn/T/nvimsKig4A/1
    configuration: 
      continuous: 1
      callback: 1
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -xelatex
  viewer: General
  qf: LaTeX logfile
    config: 
      packages: 
        default: 1
      default: 1
  document class: memoir
  packages:
    biblatex-chicago
    import
```

**Comment by lervag** [comment]
First: I took the liberty of cleaning up your comments by inlining the example and deleting the unnecessary content. This helps me quickly refresh the context when I again consider the issue.

Thank you for providing a minimal example! However, I still can't reproduce any issues. Can you

1. Check that I did not misunderstand anything by reading the updated minimal example in your comment.

2. Provide your relevant VimTeX configuration. (Or, better - provide a fully minimal vimrc file so that the reproduction step becomes `vim -u test.vim main.tex`.)

3. You write:

    > If you open main.tex and run VimtexTocOpen on it, you will see the issue (or at least I do on my computer).

    Can you be specific here: What does "you will see the issue" mean?

**Comment by alexandreroberts** [comment]
Thank you, I wasn't sure what information might be useful, but it is certainly clearer without every step in my thought-process.

Here is a minimal vimrc file:

# test.vim

```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex' 
call plug#end()
```

# The issue

The issue is that when I open `main.tex` by running `nvim -u test.vim main.tex` (note that I am using NeoVim -- not sure if that makes a difference) and then run `:VimtexTocOpen`, I get the following output:

<img width="1127" alt="Screen Shot 2021-08-08 at 3 14 04 PM" src="https://user-images.githubusercontent.com/6886906/128647306-b14f6b60-4075-4135-b38d-8676254ff53c.png">

There are actually two problems with the output.

The first is that the list of **Included** files in the TOC has only one entry, for `file-that-calls-bib-file.tex`. But based on the files, the TOC ought to include `test.bib` as well, since `other-dir/file-that-calls-bib-file.tex` calls `test.bib`.

If you widen the TOC, you see the second problem: the single entry in the TOC reads `file-that-calls-bib-file.tex.tex`, with an extra `.tex` extension.

Maybe these two issues are related?

**Comment by lervag** [comment]
Thanks for the update! I've tested with the test files provided by you. I have used the following structure:

```sh
pwd
# /home/lervag/.local/plugged/vimtex/test/issues/2126

tree
# .
# ├── main.tex
# ├── sub
# │   └── imported.tex
# ├── test.bib
# └── test.vim
```

Where the contents of the files are as specified by you, except with the paths changed according to the above file names and locations.

I now open with `nvim -u test.vim main.tex`, then do `\lt` to open the ToC. It looks like this:

![image](https://user-images.githubusercontent.com/998898/129267095-c4658024-1489-478e-be4d-9ccbc7e3d3d8.png)

As you can see, everything looks right. Can you test with a similar structure as the one I've used here (change the file names accordingly, and so on)? Perhaps I'm missing a minor detail?

**Comment by j1-lee** [comment]
At the line `\import{/some/path/other-dir/}{file-that-calls-bib-file.tex}` in `main.tex`, omitting `/` at the end of `/some/path/other-dir/` seems to exclude `test.bib`.

**Comment by lervag** [comment]
Ah, yes: From 2020, the import package allows to remove the trailing `/`. So, in this case, there's no reason not to allow it in VimTeX.

I've fixed this now.

**Comment by alexandreroberts** [comment]
That fixed it -- thank you!
