### ISSUE TITLE
SumatraPDF error despite having variables added to PATH, vimtex_compiler_progname not executable

### ISSUE THREAD

**Issue by randomrevised** [lervag/vimtex#2134]
### Description

SumatraPDF is installed on the computer and I also added the directory to the path (tried both the executable and the folder that contains said executable), but it keeps throwing this error:

![image](https://user-images.githubusercontent.com/82856360/129547333-4ab2e25b-63d3-4020-9e4a-996894c03bbc.png)

Additionally, does anyone know why the second error `g:vimtex_compiler_progname` is not executable? 

Thanks!

### Steps to reproduce

Vim: `vim`
neovim: `nvim`

Then just check using `:checkhealth` to see that it doesn't work.

### Expected behavior

SumatraPDF and compiler progname should not show up as errors.

### Actual behavior

They instead show up as not executable as detailed in this image:
![image](https://user-images.githubusercontent.com/82856360/129547740-96e8f00b-00e7-48e0-aebb-b07eb7e01679.png)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
Haven't used a Latex file because I've been a bit worried about the setup.
```

**Comment by lervag** [comment]
> SumatraPDF is installed on the computer and I also added the directory to the path (tried both the executable and the folder that contains said executable), but it keeps throwing this error:

According to the output you show, SumatraPDF is still not available to your Vim or neovim instance. Perhaps vim/neovim do not have the same path as your system?

You have not supplied any information about your configuration and similar. Please do. (Do you expect me to understand implicitly which options you use?)

The only thing I am quite sure of is that you use Windows. I do not understand if you use Vim or neovim, I do not know which options you have used for VimTeX, I do not know which versions of OS and software you use, etc.

> Additionally, does anyone know why the second error `g:vimtex_compiler_progname` is not executable?

Yes: The warning shows up because you do not have `nvr` executable. I would propose that you ignore this for now. It's only a warning.

> ### VimtexInfo
>
> Haven't used a Latex file because I've been a bit worried about the setup.

It would be helpful if you could open a LaTeX file and run `:VimtexInfo`, then copy the content here. The point is it shows a lot of useful info about your system.

**Comment by randomrevised** [comment]
Hey, sorry it's been a while and didn't get back to it till now.

About the first part, right now I got that to work - the system needs to be restarted. Didn't think of that!

`:VimtexInfo` yields the following; seems to have multiple issues right now.
```
Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..449[31]..451[4]..428[1]..429[1]..<SNR>119_get_os_info:
line   18:
E684: list index out of range: 1
E116: Invalid arguments for function matchstr
E15: Invalid expression: matchstr(s:win_info[1], ':\s*\zs.*')
Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..449[31]..451[4]..428:
line    1:
E714: List required
Press ENTER or type command to continue
```

**Comment by lervag** [comment]
Huh, strange. Can you:

1. Make sure you have installed the latest version of VimTeX.
2. After loading a `.tex` file, do `:VimtexInfo`

I believe it should work now after a minor update from my side.

Which version of Windows do you use? If you open a cmd prompt (windows key, type "cmd"). It should open a terminal. In the terminal, type "systeminfo" + enter; what's the output?

**Comment by lervag** [comment]
Well, you never really gave any information about your configuration. I believe you have changed e.g. the `shell` setting? In any case, I have to admit I'm quite bad at Windows related issues. So I might not be able to help properly.

The issue template explains how to setup a minimal example. Can you try to setup a minimal vimrc and minimal tex file and see if it works then?

**Comment by randomrevised** [comment]
I have been able to fix the windows not recognizing the terminal issue, but now it cannot find cmd.exe. 

The original issue has been fixed; I believe the rest is just bugs to work out with Windows setup and not on the side of Vimtex itself.  (I noticed other plugins and vim-plug itself also have troubles)

Thanks so much for helping in the previous posts.

**Comment by lervag** [comment]
Glad to hear it!

**Comment by lervag** [comment]
I assume [this vi.stackexchange.com](https://vi.stackexchange.com/questions/34549/vim-usr-bin-bash-s-no-such-file-or-directory) question was by you? Since it seems you may have resolved your issue, could you give some clue to what the problem was and how you solved it?
