### ISSUE TITLE
dynamic build_dir

### ISSUE THREAD

**Issue by habamax** [lervag/vimtex#2137]
**Is your feature request related to a problem? Please describe it.**

I would like to have only `tex` and `pdf` files to be in the end in the filesystem.
Unfortnunately `VimtexClean` does nothing for me.
I was thinking if I can at least hide all generated files into some sub folder - it would kind of solve my issue.
Now there is a `build_dir` I can try to use but it is static and I couldn't find a way to make it "per file"

```
let g:vimtex_compiler_latexmk = {
            \ 'build_dir': './current_tex_basename_folder',  <--------- here I would like to have either `%:t:r` or ` {-> expand("%:t:r")}`
            \ 'options' : [
                \   '-shell-escape',
                \   '-verbose',
                \   '-file-line-error',
                \   '-synctex=1',
                \   '-interaction=nonstopmode',
                \ ],
                \}
```

**Describe the solution you'd like**
It would be nice to be able to provide tex file base name as a `build-dir` for example as a lambda:
```
let g:vimtex_compiler_latexmk = {
            \ 'build_dir': {-> expand("%:t:r")}
            \ 'options' : [
                \   '-shell-escape',
                \   '-verbose',
                \   '-file-line-error',
                \   '-synctex=1',
                \   '-interaction=nonstopmode',
                \ ],
                \}
```

Then when I compile tex file `test.tex`, all aux files are next to it in the `test` folder.

**Comment by lervag** [comment]
It should not be hard to implement, but I'm curious, why is not using a static name sufficient? Do you keep a lot of documents in the same folder?

**Comment by habamax** [comment]
> Do you keep a lot of documents in the same folder?

Yep, that is the case. They are all related, but should be in a separate docs, so I keep them in the same dir.

**Comment by lervag** [comment]
Ok, this should work now. I'll push an update to the docs as well.

**Comment by habamax** [comment]
Thanks. Works if there is no minted package.

Otherwise it errors:
![image](https://user-images.githubusercontent.com/234774/130119902-9c997beb-9913-4d52-8715-b47da7541274.png)

and the output pdf has no code that is in minted environments:
![image](https://user-images.githubusercontent.com/234774/130120004-af77a8a2-8248-4308-8301-78e28425efb8.png)

Minted helper dir is outside of `build_dir` if that matters:
![image](https://user-images.githubusercontent.com/234774/130120095-355cf1df-f79f-494d-b97f-fb985d0b5199.png)

**Comment by habamax** [comment]
with default build_dir minted is ok as before:
![image](https://user-images.githubusercontent.com/234774/130120324-d071be4b-f23a-4c7e-b6d3-db741751f0d0.png)

**Comment by lervag** [comment]
> Thanks. Works if there is no minted package.

Can you give a minimal LaTeX file? It might be a limitation posed by minted itself.

**Comment by habamax** [comment]
yes, probably minted and how it processes their own generated files.

![image](https://user-images.githubusercontent.com/234774/130124600-47b23049-f5fc-4b29-a189-7c80d4000c40.png)

```
\documentclass{article}
\usepackage{minted}

\title{Test Minted}
\author{habamax}

\begin{document}

\begin{minted}{python}
def hello(world):
    pass
\end{minted}

\end{document}
```

**Comment by habamax** [comment]
And vimtex settings I have:

```
let g:vimtex_compiler_latexrun_engines = {'_': 'lualatex'}
let g:vimtex_compiler_latexmk_engines = {'_': '-lualatex'}
let g:vimtex_compiler_latexmk = {
            \ 'build_dir': {-> expand("%:t:r")},
            \ 'options' : [
                \   '-shell-escape',
                \   '-verbose',
                \   '-file-line-error',
                \   '-synctex=1',
                \   '-interaction=nonstopmode',
                \ ],
                \}
```

**Comment by habamax** [comment]
```
(./_minted-test_minted/default-pyg-prefix.pygstyle)
(./_minted-test_minted/default.pygstyle)Error: cannot read infile: [Errno 2] No such file or directory: 'test_minted.pyg'
system returned with code 1


! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need
the outputdir package option, or may be using an incompatible build tool,
or may be using frozencache with a missing file.
```

Looks like I have to specify it in a package settings?

**Comment by habamax** [comment]
https://tex.stackexchange.com/questions/339931/latex-minted-package-using-custom-output-directory-build

**Comment by habamax** [comment]
So, yes this is minted related and has nothing to do with vimtex.

**Comment by habamax** [comment]
For future curious ones, this works:

```
\documentclass{article}

\usepackage{ifthen}
\usepackage{currfile-abspath}
\getabspath{\jobname.log}
\ifthenelse{\equal{\theabsdir}{\thepwd}}% using ifthen package
%\ifdefstrequal{\theabsdir}{\thepwd}% using etoolbox package
    {}{\PassOptionsToPackage{outputdir=\theabsdir}{minted}}
\usepackage{minted}

\title{Test Minted}
\author{habamax}

\begin{document}

\begin{minted}{python}
def hello(world):
    pass
\end{minted}

\end{document}
```

**Comment by lervag** [comment]
Great, I'm glad to see you found a workaround!
