### ISSUE TITLE
Error in opening table of contents 

### ISSUE THREAD

**Issue by vsbuffalo** [lervag/vimtex#214]
In trying to open the table of contents, I get the error:

    Error detected while processing function vimtex#toc#open..<SNR>79_parse_toc..<SNR>79_parse_limits..<SNR>79_parse_limits:
    line    2:
    Error in vimtex#toc s:parse_limits
    line    3:
    File not readable:

It does work (I see the table of contents) but just thought I'd let you know I see this.

Thanks for vimtex, it's great so far!

**Comment by lervag** [comment]
That shouldn't happen... could you try to open the test file in `VIMTEX/test/test-advanced-toc/main.tex` and see if you have the same error there?

If not, could you provide a minimal example so that I can attempt to reproduce the error?

**Comment by vsbuffalo** [comment]
Sure — I've narrowed it down to the figure block below causing the issue. The actual embedded tikz file doesn't seem to matter, but if you need it I can send it along too.

    \documentclass[11pt]{article}
    \usepackage{fullpage}
    \usepackage{amsmath,amssymb,amsthm}
    \usepackage{graphicx}
    \usepackage{bm}
    \usepackage{bbm}
    \usepackage{mathrsfs}
    \usepackage[authoryear,round,longnamesfirst]{natbib}
    \usepackage[x11names, rgb]{xcolor}
    \usepackage[utf8]{inputenc}
    \usepackage{tikz}
    \usetikzlibrary{snakes,arrows,shapes}
    \usepackage{hyperref}
    \hypersetup{
      colorlinks=true
    }
    \renewcommand{\P}{\mathbb{P}}
    \newcommand{\E}{\mathbb{E}}
    \DeclareMathOperator{\var}{var}
    \DeclareMathOperator{\cov}{cov}
    
    \title{a test example}
    
    \begin{document}
    \maketitle
    
    
    \section{some section}
    
    
    \begin{figure}
      \centering
      \begingroup
      \tikzset{every picture/.style={scale=1}}%
      % dot -Txdot graphmodel.dot | dot2tex -tmath --figpreamble=''\Large'' --figonly > graphmodel.tex
      \input{x-graph-01.tex}
      \endgroup
    
      \caption{a caption}
    
      \label{fig:x-graph-01}
    
    \end{figure}
    
    \subsection{a subsection}
    
    \end{document}

**Comment by lervag** [comment]
If I create the `x-graph-01.tex` file and put it in the same folder as the main file, then I do not get any errors.

What is the project structure? That is, where is the file `x-graph-01.tex` located relative to the main file?

**Comment by vsbuffalo** [comment]
`x-graph-01.tex` is located in the project root — I think the issue may lie in this LaTeX file. It's generated with dot2tex and had duplicate labels and I think this was the issue. I'll close the issue because it seems project-specific, but I can reopen if you want to dig into what's going on with this specific file.

Thanks for your help!

**Comment by lervag** [comment]
I don't mind trying to find the cause of the problem, but then I would need the file (or parts of it) so that I can reproduce the issue. It's up to you. But if you want me to look at it, then it would help if you could create a minimal working example from the graph tex file.
