### ISSUE TITLE
syntax highlighting for footnote command

### ISSUE THREAD

**Issue by alexandreroberts** [lervag/vimtex#2140]
**Describe the solution you'd like**

I would like to be able to control the highlighting of text withing `\footnote{}` commands. I would like this to be robust enough to allow for differential syntax highlighting within a footnote, and to allow for footnote text that includes `newline`s.

So for example:
```
Text.\footnote{This is my footnote.
In continues on this line where I cite \cite[12]{citekey}.
% It contains a comment.
And here is where it ends.}
More text.
```

It would be great, for example, if everything falling between the braces of the `\footnote` command could then have a slightly different background (e.g., a different tint from the main text) so as not to be glaring but still easily distinguished visually from the main text. Then a command like `\cite` could be highlighted as usual on top of that background, and the comment could appear in gray and still be easily distinguished from the rest of the footnote.

**Describe alternatives you've considered**

I've searched online but haven't found a good solution. [This one](https://tex.stackexchange.com/questions/219772/syntax-highlight-for-footnotes-in-vim) doesn't capture footnotes that include a `newline` character, and by linking the highlighting to comments, it simply makes everything within a one-line footnote gray, so that it is indistinguishable from a comment and fails to register syntax highlighting within it.

**Comment by clason** [comment]
I think the `texFootnoteArg` highlight group is exactly what you want. I use that to make footnotes italic:
<img width="508" alt="Screenshot 2021-08-19 at 18 51 26" src="https://user-images.githubusercontent.com/2361214/130110465-62191d8d-9055-4540-8897-008d46e5ee77.png">

**Comment by alexandreroberts** [comment]
Ah! I didn't realize that existed, thank you! Might I ask you for the code that you put in your `.vimrc`? I am still new to the syntax for setting highlighting (and to `vim` in general).

**Comment by clason** [comment]
I define that (and many others) in my own colorscheme. To add them to your own color scheme, you need to use an autocommand:
```vim
au ColorScheme * hi texFootnoteArg ...
```
where the `...` are the colors and attributes (see `:h highlight-args`, or adapt from the color scheme you use).

**Comment by lervag** [comment]
I believe @clason more or less explained things satisfactory here. I just want to add a good reference on how to customize on top of a given colorscheme: [The right way to override any highlighting if you don't want to edit the colorscheme file directly](https://gist.github.com/romainl/379904f91fa40533175dfaec4c833f2f).

Also, for more info on VimTeX specific things, read the section `:help vimtex-syntax`.

**Comment by alexandreroberts** [comment]
Thank you, @clason -- and thanks, @lervag, for the link.
