### ISSUE TITLE
Simple example to get synctex working with zathura and nvim

### ISSUE THREAD

**Issue by danjenson** [lervag/vimtex#2143]
### Description

Is there a simple example to get synctex working with zathura and nvim? I feel like it worked recently and stopped. I'm using zathura 0.4.8 (girara 0.3.6), latexmk version 4.70b, and nvim 0.5.0. I've read posts dating back to 2014 but can't seem to find anything that works.

`.latexmkrc`
```perl
$out_dir = 'build';
$pdf_mode = 1;
$pdf_previewer = 'zathura';
$pdflatex = 'pdflatex -shell-escape -verbose -file-line-error -synctex=1 -interaction=nonstopmode'
```

relevant portion of `init.vim`

```vim
let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_method = 'latexmk'
autocmd FileType tex nnoremap <leader>p :VimtexCompile<CR>
```

### Expected behavior

Forward/backward search would work.

### Actual behavior

No clicks work in either direction.

### Do you use a latexmkrc file?

Yes

### VimtexInfo

```yaml
System info
  OS: Arch Linux
  Vim version: NVIM v0.5.0-dev+1166-g070e084a6
  Has clientserver: true
  Servername: /tmp/nvimpYeJVh/0

VimTeX project: exam_3_notes
  base: exam_3_notes.tex
  root: /data/repos/math-104
  tex: /data/repos/math-104/exam_3_notes.tex
  out: /data/repos/math-104/build/exam_3_notes.pdf
  log: /data/repos/math-104/build/exam_3_notes.log
  aux: /data/repos/math-104/build/exam_3_notes.aux
  fls: /data/repos/math-104/build/exam_3_notes.fls
  main parser: current file
  source files:
    exam_3_notes.tex
    math.tex
    math-104.tex
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      build_dir: build
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Zathura
    xwin id: 0
  qf: LaTeX logfile
    addqflist: 59
    fix_paths: 60
    set_errorformat: 58
  document class: article
  packages:
    amsbsy
    amsfonts
    amsgen
    amsmath
    amsopn
    amssymb
    amstext
    amsthm
    atbegshi
    atbegshi-ltx
    atveryend
    atveryend-ltx
    auxhook
    babel
    bigintcalc
    bitset
    calc
    catchfile
    enumitem
    environ
    epstopdf-base
    etexcmds
    etoolbox
    expl3
    fancyhdr
    fancyvrb
    float
    framed
    fvextra
    geometry
    gettitlestring
    graphics
    graphicx
    hycolor
    hyperref
    ifluatex
    ifplatform
    iftex
    ifthen
    ifvtex
    infwarerr
    inputenc
    intcalc
    keyval
    kvdefinekeys
    kvoptions
    kvsetkeys
    letltxmacro
    lineno
    ltxcmds
    mathtools
    mhsetup
    minted
    multirow
    nameref
    pdfescape
    pdftexcmds
    pgf
    pgfcomp-version-0-65
    pgfcomp-version-1-18
    pgfcore
    pgfrcs
    pgfsys
    physics
    refcount
    rerunfilecheck
    shellesc
    tcolorbox
    trig
    trimspaces
    uniquecounter
    upquote
    url
    verbatim
    xcolor
    xparse
    xparse-2020-10-01
    xstring
```

**Comment by lervag** [comment]
> Is there a simple example to get synctex working with zathura and nvim? I feel like it worked recently and stopped. I'm using zathura 0.4.8 (girara 0.3.6), latexmk version 4.70b, and nvim 0.5.0. I've read posts dating back to 2014 but can't seem to find anything that works.

It's supposed to just work, and on my end, it does. Can you try without the `.latexmkrc`? (Notice that VimTeX passes most of the options you add directly.)

Also, I think it is slighly better to add additional options in `.latexmkrc` with this line, as it also passes options to other flavors like xelatex and lualatex.

```perl
set_tex_cmds('-synctex=1 -interaction=nonstopmode --shell-escape %O %S');
```

> relevant portion of `init.vim`

Let me comment this:

```viml
" Not necessary
let g:tex_flavor = 'latex'

let g:vimtex_view_method = 'zathura'

" Not necessary - it is already the default value
let g:vimtex_compiler_method = 'latexmk'

" Why don't you just use the default mapping "\ll"?
autocmd FileType tex nnoremap <leader>p :VimtexCompile<CR>
```

**Comment by danjenson** [comment]
Still not working. My latexmkrc (I kept this because I want the 'build' directory, and occasionally call this from cli instead of vim):

`.latexmkrc`
```
$out_dir = 'build';
$pdf_mode = 1;
$pdf_previewer = 'zathura';
set_tex_cmds('-synctex=1 -interaction=nonstopmode --shell-escape %O %S');
```

`init.vim` relevant portion:
``` 
let g:vimtex_view_method = 'zathura'
" my leader is semi-colon, so ;p is a touch faster than \ll
autocmd FileType tex nnoremap <leader>p :VimtexCompile<CR>
```

I can't seem to fully remove the latexmkrc because I need --shell-escape -- I get a compilation error without it (maybe this is also what is throwing it off). Either way, even removing all the lines int he latexmkrc except the `set_tex_cmds`, zathura blinks constantly with the text 'loading'; it doesn't jump anywhere when I click inside it and sometimes it crashes and has to restart.

**Comment by danjenson** [comment]
In addition, if I add `$out_dir = 'build';` to my latexmkrc, the pdf isn't updated with shell escaped code, and I get warnings like this 
![image](https://user-images.githubusercontent.com/4793438/130333652-c9422dd9-0bad-4375-8588-1747ed6c6ab0.png)
from code like this
```tex
\digraph{sir}{
  rankdir=LR;
  S -> S [label=0.9]
  S -> I [label=0.1]
  I -> I [label=0.75]
  I -> R [label=0.25]
  R -> R [label=1]
}
```
Adding the output directory seems to stop the 'flashing'/loading, but still doesn't allow any sort of search.

**Comment by danjenson** [comment]
Updated VimtexInfo from within the running process:
```
System info
  OS: Arch Linux
  Vim version: NVIM v0.5.0-dev+1166-g070e084a6
  Has clientserver: true
  Servername: /tmp/nvimJIOlHY/0

VimTeX project: exam_3_notes
  base: exam_3_notes.tex
  root: /data/repos/math-104
  tex: /data/repos/math-104/exam_3_notes.tex
  out: /data/repos/math-104/build/exam_3_notes.pdf
  log: /data/repos/math-104/build/exam_3_notes.log
  aux: /data/repos/math-104/build/exam_3_notes.aux
  fls: /data/repos/math-104/build/exam_3_notes.fls
  main parser: current file
  source files:
    exam_3_notes.tex
    math.tex
    math-104.tex
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      build_dir: build
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
    job: 5
    pid: 160440
    cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -outdir=build -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"/usr/bin/nvim --servername /tmp/nvimJIOlHY/0 --remote +\%{line} \%{input}\" \%S"' -e '$success_cmd = "echo vimtex_compiler_callback_success"' -e '$failure_cmd = "echo vimtex_compiler_callback_failure"' 'exam_3_notes.tex'
  viewer: Zathura
    xwin id: 71303171
  qf: LaTeX logfile
    root: /data/repos/math-104
    addqflist: 59
    errorformat_saved: 
    fix_paths: 60
    main: /data/repos/math-104/exam_3_notes.tex
    set_errorformat: 58
  document class: amsbook
  packages: ...
```

**Comment by lervag** [comment]
> Still not working.

Ok;

> I can't seem to fully remove the latexmkrc because I need --shell-escape

But then, please, let's first simplify! Instead of working with a complex document and example, let's consider a simple one. You say the issue is with Zathura and synctex, so, please temporarily remove your latexmkrc file, then define these files:

```vim
" test.vim
set nocompatible
" Please use your path here instead of .local/plugged!
let &rtp = '~/.local/plugged/vimtex,' . &rtp
let &rtp .= ',~/.local/plugged/vimtex/after'
filetype plugin indent on
syntax enable

let g:vimtex_view_method = 'zathura'
```

```tex
% test.tex
\documentclass{minimal}
\begin{document}

Hello World!
\newpage
Hello Moon!

\end{document}
```

Now do `vim -u test.vim test.tex` - this will open `test.tex` with a minimal vimrc file. Compile with `\ll` and use `\lv` for forward search and ctrl+left click in Zathura for backward search. Does it work?

**Comment by danjenson** [comment]
So, with 
```
set nocompatible
let &rtp = '~/.local/share/nvim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.local/share/nvim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
let g:vimtex_view_method = 'zathura'
```
Forward search works, but backward search does not. I also got forward search to work in my original configuration. So backward search is the only thing not working. Could it be that I include two header latex files? or that I use a lot of newcommand/rewewcommands?

**Comment by lervag** [comment]
> So, with
> 
> ...
> 
> Forward search works, but backward search does not. I also got forward search to work in my original configuration. So backward search is the only thing not working. Could it be that I include two header latex files? or that I use a lot of newcommand/rewewcommands?

Did you test this with the minimal LaTeX example as well, as I explained? There is a very good reason why I ask for the minimal examples, here!

**Comment by danjenson** [comment]
Yes, I did.

**Comment by lervag** [comment]
Ok! The reason I ask is because of this:

> Forward search works, but backward search does not. I also got forward search to work in my original configuration. So backward search is the only thing not working. **Could it be that I include two header latex files? or that I use a lot of newcommand/rewewcommands?**

The minimal example specifically does _not_ have two header latex files. It does _not_ use any newcommands. It is 8 lines of LaTeX code. So, if you used the minimal example and it still fails, then the answer to your questions is clearly no. But since you _are asking_, I get the impression that you did not use the minimal example.

So, to be clear, with the minimal example, I mean _both_ the minimal `test.vim` _and_ the minimal `test.tex`. If you do `vim -u test.vim test.tex`, as suggested, it should be possible to test both forward and backward search on a fully minimal example. Did you do this, and what was the result?

**Comment by danjenson** [comment]
Yes, I used both the test.tex and test.vim. It does not backward search on control click or double click or anything I could try.

**Comment by lervag** [comment]
Well, then, this is strange. On my end, on what seems to be an identical system, everything works as expected. With the same minimal example, everything works here. So, something is obviously different.

Did I understand that things used to work on your end?

Let's try some more debugging:

1. Use the previously explained minimal example files: `test.vim` and `test.tex`
2. Do `nvim -u test.vim test.tex`
3. Do `\ll` to start compilation
4. Confirm that Zathura opens automatically and shows the first page "Hello world".
5. Show the output of `:VimtexInfo`
6. Now go to the line `Hello Moon` and do `\lv` to do the forward search
7. Confirm that this opens the next page in Zathura
8. Now, inside Zathura, go back to page one. then while holding the ctrl key press the left mouse button
9. Confirm that this focuses neovim and moves the cursor to `Hello world`

If I understand correctly, everything except step 8-9 should work. Can you confirm this?

One possibility that may explain the problem: Do you have neovim-remote installed, aka `nvr`?

**Comment by danjenson** [comment]
I did not have `neovim-remote` installed...thank you!!!!

**Comment by lervag** [comment]
Great, I'm glad we figured it out! :)
