### ISSUE TITLE
dse/cse not working

### ISSUE THREAD

**Issue by friolz** [lervag/vimtex#215]
I have the latest version of vimtex installed.
However the before mentioned commands won't work at all.

Do I have to enable something in the .vimrc for it to run?

**Comment by thirtythreeforty** [comment]
Do you also have [surround.vim](https://github.com/tpope/vim-surround) installed?

**Comment by lervag** [comment]
@friolz No, I do not think you need anything else installed for this to work.

Could you please test with a minimal vimrc file? I suspect there might be a plugin conflict.

**Comment by HerrmannM** [comment]
Hi

I have similar issue with dsc/csc.
For example, with : 

"Dans le chapitre \ref{chap_conadj}, nous avons"
If I put the cursor on "chap_conadj" and do a 'dsc', nothing change.
If I put the cursor on "ref" and do a 'dsc' : 
"Dans le chapitre chap_conadj} nous avons "
Notice that the comma disappear after the closing brace. It seems to delete one char after the '}'

The csc command works fine if the cursor is on 'ref'; nothing happens with the cursor on "chap_conadj".

The same happen with a minimal vimrc : 
" --- --- --- --- GENERAL --- --- --- --- "
set nocompatible              " Must be first !
set encoding=utf-8            " UTF-8 FTW
set mouse=a                   " Enable the mouse

"--- --- --- --- PLUGINS with Vundle --- --- --- --- "
" Management with Vundle:
filetype off                  " required

" --- --- --- --- --- Vundle itself --- --- --- --- ---
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins call vundle#begin('~/some/path/here')
Plugin 'gmarik/Vundle.vim'  " let Vundle manage Vundle, required

"" --- LaTeX
Plugin 'lervag/vim-latex'
let g:tex_flavor = "latex"
let g:vimtex_imaps_disabled = ['<m-i>']
"" --- --- Needs the surround plugin
Plugin 'tpope/vim-surround'

"--- --- --- --- PLUGINS with Vundle --- --- --- --- "
" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on

**Comment by lervag** [comment]
@HerrmannM You do not need the surround plugin. I've verified the problem. There are two problems: First, there was a specific problem with the `\ref` command in that it was not detected when inside the braces. Second, the deletion of the surrounding braces was wrong.

**Comment by lervag** [comment]
I now believe this issue is solved. There are some remaining tasks, see #245.

**Comment by HerrmannM** [comment]
Ok, works for me now.
Thank you ! I owe you a beer =)

**Comment by lervag** [comment]
No problem! Happy to hear it works. :)
