### ISSUE TITLE
Emphasis in syntax highlighting is lost when colorscheme is reconfigured 

### ISSUE THREAD

**Issue by bongbang** [lervag/vimtex#2152]
To replicate:

1. Load the minimal example below.
2. `:set background=dark` (it doesn't matter if the background is already dark)
3. Notice that the content of `\emph` is no longer italicized.
4. `<local-leader>lx` to get the italics back.

The problem also occurs when the color scheme is switched by the `:colo` command.

```tex
\documentclass{article}
\begin{document}
Watch this \emph{emphasis}.
\end{document}
```

**Comment by lervag** [comment]
I believe this is fixed now.
