### ISSUE TITLE
[question] g:vimtex_doc_handlers cannot use autoload function

### ISSUE THREAD

**Issue by Freed-Wu** [lervag/vimtex#2153]
In <https://github.com/lervag/vimtex/blob/master/autoload/vimtex/doc.vim#L26>

```vim
  for l:handler in g:vimtex_doc_handlers
    if exists('*' . l:handler)
      if call(l:handler, [l:context]) | return | endif
    endif
  endfor
```

`exists` will return 0 for autoload function. Is there any method to use autoload function?

Thanks!

**Comment by lervag** [comment]
Yes and no. The problem with an autoload function in this context is that it may or may not be sourced. An immediate way to make it work is to ensure it is sourced, i.e. something like this:

```vim
let g:vimtex_doc_handlers = ['my#cool#function']
runtime autoload/my/cool.vim
```

However, perhaps it could be solved from VimTeX by a minor change. Could you test to change the mentioned code into this:

```vim
for l:handler in g:vimtex_doc_handlers
  try
    if call(l:handler, [l:context]) | return | endif
  catch /E117/
    " E117: Unknown function
  endtry
endfor
```

**Comment by Freed-Wu** [comment]
I have tested. It can work!

**Comment by lervag** [comment]
Ok; I've pushed the code. Please update and verify that it now works as expected.
