### ISSUE TITLE
Fuzzy finder on bibtex files allowing for fast citations

### ISSUE THREAD

**Issue by ThSGM** [lervag/vimtex#2154]
This is not a serious enhancement request for vimtex, but I wanted to document this possibility since some people (like myself) have been interested in how we can fuzzy find through more extensive bibtex files in order to retrieve citations. It may be the case that it inspires similar development ideas for vimtex. 

As it turns out @noahares has created a nice plugin called [telescope-bibtex](https://github.com/nvim-telescope/telescope-bibtex.nvim). This uses the [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) plugin to fuzzy find through bib files. I made a video on this.

Make sure you inspect the bottom for the `:Telescope bibtex` command (it may be hidden by the video controls). 

https://user-images.githubusercontent.com/3396578/131756465-7a1784f7-3fa3-449f-b61e-68bb7b3206b3.mp4

One of the nice features of this plugin is that it will not only search the current .tex file directory for the .bib file, but it can also add additional .bib files. For example, you can add a master .bib file [generated by Zotero](https://retorque.re/zotero-better-bibtex/), and cite from both this document and local bib files. 

This issue can be closed, of course.

**Comment by noahares** [comment]
Thank you for mentioning this plugin here :) I would apprechiate any input from people using it. I do not use bibtex extensively and only have simple .bib files, so I mostly rely on other users to find bugs (recently someone pointed out `@Comment` exists and wasn't handled correctly).

**Comment by lervag** [comment]
> As it turns out @noahares has created a nice plugin called [telescope-bibtex](https://github.com/nvim-telescope/telescope-bibtex.nvim).

Nice! It looks cool; although I don't think I quite see myself using it as I already find the cite completion combined with a good autocomplete engine (I use coc.nvim) to be more than sufficient.

> One of the nice features of this plugin is that it will not only search the current .tex file directory for the .bib file, but it can also add additional .bib files.

So it is sort of more general than a project specific feature? Does it then add the `\bibliography{...}` lines if a new `.bib.` file is added?

> It may be the case that it inspires similar development ideas for vimtex.

I assume you're already aware of VimTeX's cite completion? Do you have any other specific ideas that you think we should address?

> For example, you can add a master .bib file [generated by Zotero](https://retorque.re/zotero-better-bibtex/), and cite from both this document and local bib files.

I also use Zotero, and I often add a synchronized bib file in addition to a document specific one while I'm writing. I find the context action to be quite useful in this regard (see `:help vimtex-context-citation`).

> This issue can be closed, of course.

Sure; feel free to suggest an update to the docs if you think this plugin should be mentioned. (@noahares you can also do that, of course, if you want to.)
