### ISSUE TITLE
Improved conceal for natbib's commands

### ISSUE THREAD

**Issue by rionda** [lervag/vimtex#2155]
Conceal works correctly for many (not all, see below) of [natbib](https://www.ctan.org/pkg/natbib)'s commands such as `\citep`, `\citet`, ..., that start with a *lowercase* `c`, but it does not work for any those that starts with an *uppercase* `C`, such as `\Citep`, ... . These commands starting with an uppercase `C` are used to enforce uppercase names at the beginning of a sentence (see [natbib reference](http://mirrors.ctan.org/macros/latex/contrib/natbib/natnotes.pdf), section "Forcing upper case names").

Conceal also does not seem to work for some of natbib's commands, such as `\citeauthor`, `\citeyear`, or those starting with `\citeal`, and possibly others. See the reference linked above for a complete list of natbib's commands.

Thanks for all the work!

**Comment by lervag** [comment]
> Conceal works correctly ..., but it does not work for any ...
> 
> Conceal also does not seem to work for some of ...

It would be very helpful if you could provide a sample LaTeX snippet that includes all of the commands you find is lacking. Then I could use it for testing while adding them.

> Thanks for all the work!

My pleasure :)

**Comment by rionda** [comment]
Here you are:

```latex

% "Standard" commands

\citeauthor{jon90} 

\citeauthor*{jon90} 

\citeyear{jon90} 

\citeyearpar{jon90}

% Capital `C` commands

\Citep{jon90}

\Citet{jon90}

\Citealt{jon90}

\Citealp{jon90}

\Citeauthor{jon90}

% Suppressed parentheses commands (i.e., "`\citeal*`" commands)

\citealt{jon90}

\citealt*{jon90}

\citealp{jon90}

\citealp*{jon90}

\citenum{jon90}

\citetext{priv.\ comm.}

```

**Comment by lervag** [comment]
This should work now, please test.

**Comment by rionda** [comment]
I did a couple of tests. Seems to work. Thanks!

**Comment by lervag** [comment]
Good to hear!

**Comment by lervag** [comment]
Oh, they should work. Perhaps the natbib package is not loaded? Can you give a proper minimal example?
