### ISSUE TITLE
Add .tikz file completion for \input

### ISSUE THREAD

**Issue by jhossbach** [lervag/vimtex#2162]
As of now, if I am reading https://github.com/lervag/vimtex/blob/5623fb4c44b2975dd89b0925ba3b952ffa33dfc6/doc/vimtex.txt#L3657 correctly, vimtex only searches for `.tex` files when `\input` is written. However, I would love to see it searching for `.tikz` files as well. I believe this is the normal way to include tikz files, e.g.

```tex
\begin{figure}
  \centering
  \input{filename.tikz}
  \caption{}
  \label{}
\end{figure}
```

I would love to see completion for this as well.
Please correct me if this is not the right way to do / there **is** completion for tikz files, just not for `\input`.

Regards
Julian Hossbach

**Comment by jhossbach** [comment]
Also, compilation errors that happen inside this .tikz file seem to not trigger the quickfix window. This might be related, but I don't know for sure

**Comment by lervag** [comment]
> As of now, if I am reading [the docs] correctly, vimtex only searches for `.tex` files when `\input` is written.

So, simply put: you want completion for `\input` (and friends) to also complete `*.tikz` files in addition to `*.tex` files, right?

> Please correct me if this is not the right way to do ...

This is OK, but I would be glad if you could provide a minimal example of this. That is, a `main.tex` file and a minimal `.tikz` file.

> Also, compilation errors that happen inside this .tikz file seem to not trigger the quickfix window. This might be related, but I don't know for sure

No, this is not related. But I could consider looking into this if you open a new issue for it with a description of how to reproduce it.

**Comment by jhossbach** [comment]
> So, simply put: you want completion for `\input` (and friends) to also complete `*.tikz` files in addition to `*.tex` files, right?
>
Exactly.

> This is OK, but I would be glad if you could provide a minimal example of this. That is, a `main.tex` file and a minimal `.tikz` file.
> 
I tested this with the following files:
My `minimal.vim` file: (I use vim-plug)
```vim
set nocompatible
let &runtimepath  = '~/.vim/plugged/vimtex,' . &runtimepath
let &runtimepath .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
```

My `minimal.tex` file:
```tex
\documentclass{minimal}
\usepackage{tikz}
\begin{document}
\input{minimal.tikz}
\end{document}
```
My `minimal.tikz` file:
```tex
\begin{tikzpicture}
\node at (0,0) {This is a test node};
\end{tikzpicture}
```
I want `\input{` (and friends) to offer `minimal.tikz` for file completion, but it only offers `.tex` files.

**Comment by lervag** [comment]
I think this should work now, please test.

**Comment by jhossbach** [comment]
It does not provide minimal.tikz for omnicomplete if I use `minimal.vim` file, but my normal vim now displays .tikz files for omnicomplete, I'll take that. Thanks a lot!

**Comment by lervag** [comment]
It will only work if VimTeX recognizes that you use the `tikz` package. This restriction could be relaxed, but I am quite confident that it should work well (and it thus avoids a filesystem search for files unless necessary).

**Comment by clason** [comment]
I have the following in my config:
```
au BufNewFile,BufRead *.tikz setlocal ft=tex nowrap
```
(Maybe VimTeX could recognize `.tikz` files out of the box?)

**Comment by lervag** [comment]
Yes, but I believe it may require some more work. I.e., we need to consider how the VimTeX state should be initialized when loading VimTeX for tikz files.

Could you open a new issue about this?

**Comment by clason** [comment]
Ah, VimTeX doesn't provide any `ftdetect` on its own -- `.sty` and `.cls` files are also not recognized as `ft=tex`. Would you be open to adding detection logic?

**Comment by lervag** [comment]
Yes, at least open to discuss it. I think this could also be part of the same issue.
