### ISSUE TITLE
Detect more TeX-related filetypes

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#2163]
Now that VimTeX is a full-featured filetype plugin, it would be nice if it triggered for (more) TeX-related filetypes.

Off the top of my head:

1. `*.cls`: that is recognized by `ftplugin.vim`, but only if the first line starts with a `%` (otherwise the filetype is set to `st`); if you have VimTeX installed, chances are good that your `.cls` files are LaTeX class files...
2. `*.tikz` (see #2162)

**Comment by lervag** [comment]
I believe this may suffice. Please test.

I'm not 100% sure if it is a good idea to override the builtin conditional for cls filetype detection. I don't know and use smalltalk, and so I don't know how likely it is for this change to lead to unexpected behaviour...

**Comment by clason** [comment]
> I believe this may suffice. Please test.

Looks good!

>  I don't know and use smalltalk, and so I don't know how likely it is for this change to lead to unexpected behaviour...

I don't, either; I guess we'll find out whether the intersection of TeX writers and smalltalk programmers is nonempty...

**Comment by lervag** [comment]
> I don't, either; I guess we'll find out whether the intersection of TeX writers and smalltalk programmers is nonempty...

Hehe, yes; let's take the risk. If there are objections, then I'll probably revert this change. In the meantime, I'll close this issue. :)
