### ISSUE TITLE
Plugin should reparse directive on compiler start

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2168]
**Is your feature request related to a problem? Please describe it.**

When I create a new TeX file, add the first line:

```
%! TEX program = xelatex
```

then type the rest of the document, then use `\ll`, it compiles with `pdflatex` until Vim is restarted.

**Describe the solution you'd like**

It would be best if the plugin re-parse the program directive whenever the compiler is started, instead of (currently) only once when the file is loaded into Vim.

Or better, even if the compiler is in continuous mode, determine if the program directive changes and restart the compiler automatically. (rarely used feature)

**Describe alternatives you've considered**
Restart Vim is a workaround, but it's quite unintuitive (the user may spend some time thinking why the compiler isn't correct even with the directive line)

**Comment by lervag** [comment]
Agreed; I've pushed an updated that more or less solves this.

> Or better, even if the compiler is in continuous mode, determine if the program directive changes and restart the compiler automatically. (rarely used feature)

That would be nice, but I think the benefit does not outweight the implementation cost. Now you can simply restart the compilation to reparse the directive.
