### ISSUE TITLE
gvim 7.4 / Win7 / MikTeX : mappings don't work

### ISSUE THREAD

**Issue by awisse** [lervag/vimtex#217]
I can't get any of the mappings from dse, dsc, ... , ae, ie, ...,  [[ to work. Jumping between sections and folding work, the commands wo. When I type "ie" for instance, vim goes into insert mode and inserts "e", dse deletes to the end of the word, just like expected without a plugin.

Compiling :VimtexCompile starts but never stops until :VimtexStop and doesn't compile anything.

It's probably just me not understanding something obvious to seasoned vim users.

I am using pathogen, this is my .vimrc file contents:

    set tabstop=4
    set expandtab
    set shiftwidth=4
    set softtabstop=4
    set textwidth=79
    set autoindent
    set encoding=utf-8
    set laststatus=2
    set incsearch
    set hls
    set ruler
    cd $HOME
    filetype off
    
    execute pathogen#infect()
    execute pathogen#helptags()
    
    filetype indent plugin on
    syntax enable
    
    " vimtex options
    let g:vimtex_view_general_viewer='C:/Program Files (x86)/SumatraPDF/SumatraPDF.exe'
    let g:vimtex_view_general_options='-forward-search @tex @line @pdf'
    let g:vimtex_view_general_options_latexmx='-reuse-instance'
    let g:vimtex_flavor='latex'

**Comment by lervag** [comment]
Hi! First, som minor things: You want `let g:tex_flavor`, because this is not a vimtex option, but an option for the syntax file included with vim. Vimtex only expands on this included syntax file, so I approve of this option.

So, to the issue: That is, there are two issues. The first regarding the mappings: Does any of the leader mappings work, e.g. `<leader>ll` for `VimtexCompile`, `<leader>lv` for `VimtexView`, or `<leader>li` for `VimtexInfo`?

The second, regarding the compilation not stopping: This is really the intended behaviour. `:VimtexCompile` will (by default) start a continuous compilation in the background through use of `latexmk` (a standalone an separate program). Although, of course, the compilation should generate files. When you have started the compilation, what is the output of `VimtexCompileOutput` and `VimtexInfo`?

**Comment by awisse** [comment]
I added  `let maplocalleader = '<backtick>'` to my .vimrc and tried in normal mode:

    :let maplocalleader='`'
    :let mapleader='`'

The commands 

    `li
    `ll

behave as if the (local)leader weren't defined. Also tried maplocalleader=','.

`VimtexCompileOutput` is empty, `VimtexInfo` gives:

    b:vimtex : methodologie
      pid : 6788
      tmp : 'C:\Users\peter\AppData\Local\Temp\VIA95.tmp'
      root : 'c:\Users\peter\Dropbox\apps\TeX Writer\Methodologie_VF8'
      aux : 'c:\Users\peter\Dropbox\apps\TeX Writer\Methodologie_VF8/methodologie.aux'
      log : 'c:\Users\peter\Dropbox\apps\TeX Writer\Methodologie_VF8/methodologie.log'
      out : 'c:\Users\peter\Dropbox\apps\TeX Writer\Methodologie_VF8/methodologie.pdf'
      tex : 'c:\Users\peter\Dropbox\apps\TeX Writer\Methodologie_VF8\methodologie.tex'
      cmd_latexmk_compile : 'cmd /s /c "cd /D "c:\Users\peter\Dropbox\apps\TeX Writer\Methodologie_VF8" && set max_print_line=2000 & latexmk -pdf -e "$pdflatex =~ s
    / / -file-line-error /" -pvc -e "$success_cmd = ''\"C:\Program Files\Vim\vim74\gvim.exe\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e
     "$failure_cmd = ''\"C:\Program Files\Vim\vim74\gvim.exe\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previewer = ''C:/Program Files (x86)/SumatraPDF/SumatraPDF.exe ''" "methodologie.tex" >C:\Users\peter\AppData\Local\Temp\VIA95.tmp"'
      base : 'methodologie.tex'
      viewer
        init : function('4')
        view : function('5')
        latexmk_append_argument : function('6')

**Comment by lervag** [comment]
Strange. Does the default leader key work? What is the output of `:map <buffer>`?

**Comment by awisse** [comment]
The `:map <buffer>` command was enlightening. Thank to this, I learned that `maplocalleader` has to be assigned _before_ vimtex is loaded.

The `<localleader>`, the mappings, everything works now as it should. Just a matter of me learning how to use vim and the vimtex mappings with different modes (nxoi). So this is a non issue and can be closed. Thanks for your support.

**Comment by lervag** [comment]
No problem! I'm happy things work :)
