### ISSUE TITLE
Create an "opaque" comment macro to hide part of the code to the syntax checker. (low priority!)

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#2171]
There are, in the wild, "funny" templates that do very strange things; sometimes it would be useful to mark part of your text/code as invisible for the syntax highlighter parser. I will male just an example here... 

For example, the MDPI journal templates issues a `\begin{paracol}{2}` which is **hidden** into the `\begin{document}` command. At a later stage in the document, you are required to issue a `\end{paracol}` (just before wide figures, for example, and before bibliography); see https://tex.stackexchange.com/questions/606008/wide-table-using-mdpi-template/606032#606032. I am unable to produce a small example, but this thing for example disrupts the backward search from PDF in my `vimtex`.

But in general, my point is that this is often a smash-a-mole thing, similar things can appear everywhere and it is impossible to take into account all the times some package makes an utterly ugly thing like that. 

Overleaf has a [nice mechanism](https://www.overleaf.com/learn/how-to/Code_Check#Disabling_Code_Check_for_part_of_a_file) for this: everything between the two magic comments
```
%%begin novalidate
...
%%end novalidate
```
is completely ignored by code check, syntax highlight, etc. 

Wouldn't that be a nice "last-resort" thing to have?

**Comment by lervag** [comment]
VimTeX has a similar feature for syntax highlighting, see `:help vimtex-syntax`:

```
There will probably always be situations where the parser will fail, and in
some cases it may be hard to "recover". It is therefore possible to manually
activate a severely reduced syntax zone to handle such situations. The zone is
activated with the directive `% VimTeX: SynIgnore on` and disabled with the
similar directive `% VimTeX: SynIgnore off`, e.g.: >

  % VimTeX: SynIgnore on
  \catcode`\$=11
  $
  \catcode`\$=3
  % VimTeX: SynIgnore off

The above LaTeX code will look plain, but OK with VimTeX. Note: The directive
is matched case insensitive, and the synonyms `enable` and `disable` may be
used instead of `on` and `off`.
```

It could be relevant to also support the same magic comment as Overleaf uses. Do you thank that is necessary?

Also: do you find a need for something in addition to this from VimTeX side?

**Comment by Rmano** [comment]
Ah, I did not know of that feature! Sorry for the noise.

**Comment by lervag** [comment]
No problem! The overleaf mechanism still looks nice to support from VimTeX as well? Afterall, it is quite easy to work locally towards Overleaf through the git integration...

**Comment by Rmano** [comment]
Yes --- that could be nice!

I work a lot locally with the overleaf-github link (so I can edit with `vimtex` locally, and still have online collaboration with my co-authors). Now I have the comments duplicated, but it would be nice if the overleaf comment would be understood by `vimtex`, too.

**Comment by lervag** [comment]
Done!

**Comment by Rmano** [comment]
Thanks!
