### ISSUE TITLE
Using vimtex features when editing (R)Markdown documents

### ISSUE THREAD

**Issue by noib3** [lervag/vimtex#2173]
I recently started writing documents in RMarkdown instead of LaTeX due to the simpler, less cumbersome syntax, the flexibility to compile one source file into both HTML and PDF, etc.

I was wondering if it was possible to continue using some of the really vimtex nice features that I got used to when editing LaTeX files, like the ability to change/toggle commands and environments, the autocompletion of reference labels, the syntax for display math mode, and countless others.

Just to give an example, this is a comparison between [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc-syntax) math's syntax (above) and vimtex's math syntax (below) using the gruvbox colorscheme. Vimtex's output is much nicer and it also highlights matching `\begin` `\end` delimiters.

![2021-09-15@19:02:59](https://user-images.githubusercontent.com/59321248/133477773-4bacaf34-2b0c-43f2-a511-8a3c8605f065.png)
![2021-09-15@19:03:09](https://user-images.githubusercontent.com/59321248/133477775-3b5c449f-b4bc-4eaa-b25d-c43c902cc63b.png)

**Comment by lervag** [comment]
> I was wondering if it was possible to continue using some of the really vimtex nice features that I got used to when editing LaTeX files, like the ability to change/toggle commands and environments, the autocompletion of reference labels, the syntax for display math mode, and countless others.

There are some related issues:
* #1937: This is an open, related issue. I believe it may hold some relevant tips for how you can do things right now, and with time I plan to make it easier to load parts of VimTeX "on demand" (e.g. for LaTeX in Markdown). But it is not high priority; sorry.
* #1706 and #1729: Discussions on VimTeX and R-markdown. There's quite a few words here, and it may be too much to read everything. But it may be of interest and there may be some good tips.
* #1623: Here I suggest one way to load VimTeX stuff in pandoc or Markdown filetypes.

> Just to give an example, this is a comparison between [vim-pandoc](https://github.com/vim-pandoc/vim-pandoc-syntax) math's syntax (above) and vimtex's math syntax (below) using the gruvbox colorscheme. Vimtex's output is much nicer and it also highlights matching `\begin` `\end` delimiters.

I do not use `vim-pandoc-syntax` personally, and so I don't know exactly how that works. Perhaps you could try other Markdown plugins? I believe some plugins loads the `.tex` filetype syntax for LaTeX snippets, which should mean they load VimTeX if that is installed.

----

Feel free to continue the discussion, but I'll close the issue as I think it is more or less covered by #1937.

**Comment by noib3** [comment]
Thanks for the detailed answer as always :). After adding `call vimtex#init()` to `after/ftplugin/rmarkdown.vim` the syntax is a lot better although not exactly equal to what I get in `.tex` files, for example

![2021-09-16@00:14:44](https://user-images.githubusercontent.com/59321248/133517048-1800c635-dea5-4f40-84ae-ec15b1a57d9c.png)
![2021-09-16@00:14:54](https://user-images.githubusercontent.com/59321248/133517050-748e2a97-9cb8-4a6c-b39a-f65314895623.png)

but that's not a big deal. However I seem to be missing all the following mappings:

![2021-09-16@00:02:46](https://user-images.githubusercontent.com/59321248/133517137-e6bba5d4-9435-44e5-b327-1cee359cffea.png)

Skimming through the codebase I see that those mappings are defined inside the function `s:init_default_mappings()` (in `autoload/vimtex.vim`), which is already called by `vimtex#init()` so I'm not really sure why those mappings aren't added (`:echo g:vimtex_mappings_enabled` returns a 1 in `foo.Rmd`).

**Comment by lervag** [comment]
> Thanks for the detailed answer as always :).

My pleasure :)

> After adding `call vimtex#init()` to `after/ftplugin/rmarkdown.vim` the syntax is a lot better although not exactly equal to what I get in `.tex` files, for example ...

It would be easier to comment on this if I had a concrete example in which I could test things myself. But I would not expect it to be exactly the same, because nested syntax will always be somewhat "degraded" compared to the full version.

> However I seem to be missing all the following mappings: ...
> 
> Skimming through the codebase I see that those mappings are defined inside the function `s:init_default_mappings()` (in `autoload/vimtex.vim`), which is already called by `vimtex#init()` so I'm not really sure why those mappings aren't added (`:echo g:vimtex_mappings_enabled` returns a 1 in `foo.Rmd`).

Again, it would be easier to comment by having a concrete (minimal) example. That may also help in continuing the work to make things easier to load "on demand", e.g. #1937.
