### ISSUE TITLE
[bug] conlict with dein.vim

### ISSUE THREAD

**Issue by Freed-Wu** [lervag/vimtex#2175]
See <https://github.com/Shougo/dein.vim/issues/429>
Thanks!

**Comment by Shougo** [comment]
https://github.com/lervag/vimtex/commit/00ed2f1612599c07de8d77cc85b4c1becfd1ae0f#diff-6ae020aafd02c787f996ea9a031f8dae45ab2db601e996a717f70a85fac1ebc2R44

is broken.  The line must be:

```vim
autocmd ColorScheme <buffer> call vimtex#syntax#core#init_highlights()
```

**Comment by lervag** [comment]
Sorry about that, I'm pushing the fix immediately!

And thanks, @Shougo, for recognizing the problem and suggesting a fix!

**Comment by Shougo** [comment]
I am Vim plugins debugger.

**Comment by lervag** [comment]
And you are appreciated! :)
