### ISSUE TITLE
Slow opening of all .tex files when using vimtex with vim and neovim

### ISSUE THREAD

**Issue by kaprests** [lervag/vimtex#2176]
### Description

Vimtex causes vim and neovim to be pretty slow when opening any .tex file on my machine. Normal vim takes about three seconds, while neovim takes more than five seconds consistently. I have tested both with totally blank configuration files, except for vimtex, but the issue arises even with vimtex as the only plugin and otherwise stock configuration. 

Any suggestions to how I can go about to debug this or to what might cause the issue?

I am using Endeavor OS is that is of relevance. 

### Steps to reproduce

`vim anytexfile.tex`

or

`nvim anytexfile.tex`

### Expected behavior

When following the above steps I expect vim/nvim to open the file almost instantly

### Actual behavior

Vim takes around three seconds to open, nvim above five seconds.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
Neovim: 
 1 System info
  2   OS: EndeavourOS Linux
  3   Vim version: NVIM v0.5.0
  4   Has clientserver: true
  5   Servername: /tmp/nvim0rMSGs/0
  6 
  7 VimTeX project: new
  8   base: new.tex
  9   root: /home/kaprests
 10   tex: /home/kaprests/new.tex
 11   main parser: current file
 12   document class: 
 13   compiler: latexmk
 14     engine: -pdf
 15     options:
 16       -verbose
 17       -file-line-error
 18       -synctex=1
 19       -interaction=nonstopmode
 20     engine: -pdf
 21     callback: 1
 22     continuous: 1
 23     executable: latexmk
 24   viewer: Zathura
 25     xwin id: 0
 26   qf method: LaTeX logfile


Vim:
  1 System info
  2   OS: EndeavourOS Linux
  3   Vim version: VIM 8.2 (1-3441)
  4   Has clientserver: false
  5 
  6 VimTeX project: new
  7   base: new.tex
  8   root: /home/kaprests
  9   tex: /home/kaprests/new.tex
 10   main parser: current file
 11   document class: 
 12   compiler: latexmk
 13     engine: -pdf
 14     options:
 15       -verbose
 16       -file-line-error
 17       -synctex=1
 18       -interaction=nonstopmode
 19     engine: -pdf
 20     callback: 1
 21     continuous: 1
 22     executable: latexmk
 23   viewer: General
 24   qf method: LaTeX logfile
```

**Comment by clason** [comment]
You can get a trace of your startup with `nvim --startuptime profile.log anytexfile.tex`.

**Comment by lervag** [comment]
@clason's suggestion is very relevant.

Another thing which may be revealing is if you do `:scriptnames` after opening any tex file. It could be interesting to see the output here.

**Comment by kaprests** [comment]
Thank you for blazing fast replies! Attached the outputs as files, from the profile log it seems that stuff related to vimtex indeed takes up a good chunck of the startup tim
[nvim_profile.log](https://github.com/lervag/vimt
[nvim_scriptnames.txt](https://github.com/lervag/vimtex/files/7202114/nvim_scriptnames.txt)
ex/files/7202112/nvim_profile.log)
e.

**Comment by clason** [comment]
It seems that some runtime files just take an exceptionally long time loading -- this might be due to your hard disk/SSD having bad sectors, on which these files happen to land?

**Comment by kaprests** [comment]
Hmm, I don't know much about disk health, so I guess that could be the case although I don't notice any problems with the disk otherwise.

**Comment by kaprests** [comment]
> > Also I see now that nvim any.tex with a bare init.vim except for vimtex also takes around 3 sec., so enabling vimtex seems to give me about 3 seconds extra startup for both vim and neovim.

> I did not understand what you meant here...

I just tried to correct myself from the original comment where I wrote that the slowdown was greater for nvim, but it is the same with similar configuration.

It certainly looks like calling `uname` is a culprit, `echo system('uname')` after 'nvim --clean' does take a couple of seconds.

**Comment by lervag** [comment]
> It certainly looks like calling `uname` is a culprit, `echo system('uname')` after `nvim --clean` does take (what feels like) a couple of seconds.

What is the output of `:echo system('uname')`? What is the output of `uname` when you run it in a terminal?

**Comment by kaprests** [comment]
The output is "Linux" in both cases

**Comment by lervag** [comment]
Strange. And you have the same experience in both Vim and neovim? I.e., that doing `:echo system('uname')` is slow with `vim -u NONE` and `nvim --clean` (or `nvim -u NONE`)?

Please note, though, that this does not seem to be an issue with VimTeX, but rather an issue with your setup, somehow. I have no experience with or knowledge of Endeavor OS, and I'm not really sure what more you can try here.

Does `:!uname` run fast?

What is the output of `:echo &shell`?

**Comment by kaprests** [comment]
> Strange. And you have the same experience in both Vim and neovim? I.e., that doing :echo system('uname') is slow with vim -u NONE and nvim --clean (or nvim -u NONE)?

Yep.

> Does :!uname run fast?

This also takes a little while. Seems like !anycommand is a little slow. 

> What is the output of :echo &shell?

That gives "/usr/bin/fish". I just tried changing to bash also, but the results were the same. 

> Please note, though, that this does not seem to be an issue with VimTeX, but rather an issue with your setup, somehow. I have no experience with or knowledge of Endeavor OS, and I'm not really sure what more you can try here.

Yes, I guess it probably is. Maybe I'll have to consider a clean install of the OS sometime soon.

**Comment by lervag** [comment]
Perhaps you could open an issue on neovims repo? Explain the slowness of `!uname` or `:call system('uname')` even with `nvim --clean`; I would not be surprised if someone there could faster identify the cause of this issue. I'm sorry to say I don't have any further idea on how to debug this. :\

**Comment by kaprests** [comment]
Good idea! I'll have a look in the neovim community or maybe even Endeavor. 
Thanks for all the help! Closing the issue :)

**Comment by lervag** [comment]
Glad to help, and good luck!
