### ISSUE TITLE
[advice] Change conceal regular expression

### ISSUE THREAD

**Issue by Freed-Wu** [lervag/vimtex#2178]
In <https://hub.fastgit.org/lervag/vimtex/blob/master/autoload/vimtex/syntax/core.vim#L1376>

```vim
syntax match texMathSymbol "\\sum\>"               contained conceal cchar=∑
```

`"\\sum\>"` is too strict, it cannot match `\sum_{i = 1}^n` or `\sum^n_{i = 1}`

How about change it to `"\\sum\ze\(\>\|_\|\^\)"`?

Other operators are similar.

Thanks!

**Comment by lervag** [comment]
> Other operators are similar.

You're right. But I'm not sure it makes sense to change all operators. Would you mind proposing a set of the relevant operators? Or do you think it would be better to simply change all related regexes?

**Comment by Freed-Wu** [comment]
In my opinion, I believe it should not have any side effect. However, if it results in any bug for some operators, we can treat these operators specially.

**Comment by lervag** [comment]
I've updated this now. I think it should work as expected in most or all cases now, but please test and report any errors.
