### ISSUE TITLE
Turn off conceal for a block of lines

### ISSUE THREAD

**Issue by oponkork** [lervag/vimtex#2181]
Conceal is a great feature which helps reduce the visual clutter, but it is also a constant source of jitter while editing. The text on concealed lines is not where you think it is, which messes up vertical navigation. The situation becomes worse while editing heavily concealed blocks of text, for example equations.

Currently, vim/vimtex reveal/expand the concealed text only for the row which cursor is on. I propose to reveal a block of lines around the current line, which should ease up some of the navigational issues. For example,`g:vimtex_conceal_offset=2`  should reveal text for current line and two lines above and below, a total of five lines.

- Does this makes sense?
- Would it be useful for the vimtex userbase?
- How hard/easy it will be to implement this feature? I can give it a shot with some help.

**Comment by clason** [comment]
I'm afraid that is something that needs to be dealt with by Vim itself, not a plugin...

(Basically, you need to extend conceallevel.)

**Comment by lervag** [comment]
Yes, I think @clason is right here. I think your idea is good, but it should be proposed upstream either at Vim or neovim.

**Comment by oponkork** [comment]
I thought since vimtex has it's own syntax engine, it could be done with vimtex itself. I will open the issue on upstream.

**Comment by clason** [comment]
Vimtex has its own syntax _rules_; the _engine_ is still very much vim's builtin regex-based one.
