### ISSUE TITLE
A vimtex tag on vi.sx

### ISSUE THREAD

**Issue by gdetrez** [lervag/vimtex#219]
I don't have enough points, so I'm putting the idea here in case someone does.

**Comment by lervag** [comment]
I might have enough points, but I don't have a particular question where I know it is relevant. If you could provide a link to one, then I could try to add it?

**Comment by gdetrez** [comment]
Well, I will then shamelessly point you to my own question :-)
http://vi.stackexchange.com/questions/4523/how-to-configure-spell-to-ignore-some-environments-in-latex

**Comment by lervag** [comment]
Consider the tag added.

For your question: I think the answer provided by jjaderberg is good. A different question is whether I should update vimtex somehow.

For starters: Could you provide a small example and explain the desired behaviour? Perhaps I should update the `after/syntax/tex.vim` script provided by vimtex...

**Comment by gdetrez** [comment]
Here is an example of the minted environment:
```latex
\documentclass{article}
\usepackage{minted}
\begin{document}
\begin{minted}{java}
import foobar
\end{minted}
\end{document}
```
in this case, vim spell highlights both `java` (the minted argument that specify which lexer to use) and foobar (in the code snippet).

Note that there seems to be quite a few verbatim-like environments ([minted](http://ftp.acc.umu.se/mirror/CTAN/macros/latex/contrib/minted/minted.pdf), [verbments](http://ftp.acc.umu.se/mirror/CTAN/macros/latex/contrib/verbments/verbments.pdf), [texments](http://ftp.acc.umu.se/mirror/CTAN/macros/latex/contrib/texments/texments.pdf), [listings](http://ftp.acc.umu.se/mirror/CTAN/macros/latex/contrib/listings/listings.pdf)...) so maybe there could be a setting in vimtex for the user to specify his favorite verbatim environments. An cool fallback, although probably not the simplest feature, would be to check if the user has a [chktex](http://baruch.ev-en.org/proj/chktex/) config (`~/.chktexrc`) with a `VerbEnvir` section like:

```
VerbEnvir {
  verbatim comment listing verbatimtab rawhtml errexam picture texdraw
  filecontents pgfpicture tikzpicture minted
}
```

--- 

One other case where I thing the spell checker should be disabled is with the `hyperref` package:
```latex
\documentclass{article}
\usepackage{hyperref}
\begin{document}
\url{http://foobar}
\href{http://foobar}{my link}
\end{document}
```

Again, the spell checker highlights foobar, in both `\url` and `\href` (the second argument of `\href` is the "link text" which should probably be spell-checked).

**Comment by lervag** [comment]
Thanks! I'll look into this. It should be possible to solve. Though, due to me not having that much time for vimtex lately, it might take some time until I work in this issue. I hope you can live with the current state in the mean time.

**Comment by lervag** [comment]
One thing: Did you notice the option `g:vimtex_syntax_minted`? If you set this option appropriately, then you can get proper syntax highlighting within the minted environment. E.g. use

```vimL
let g:vimtex_syntax_minted = [
      \ {
      \   'lang' : 'java',
      \ }]
```

for Java. This also disables spell checking inside the minted envionment as desired with no further actions from my side.

I'll look into the `\url` and `\href` commands.

**Comment by lervag** [comment]
I've added support for the `\url` and `\href` commands (5d5c71044880443035e07009497962feacb56b20). Please check if it works as expected.

**Comment by gdetrez** [comment]
It works as expected with `\url` and `=href`, thanks!

I did not notice `g:vimtex_syntax_minted` and it seems to solve my problem (with the added bonus of syntax highlighting!) so I guess you can close this issue and maybe add this as an answer to vi.sx so I can accept it.

I was thinking I could just populate this settings with the full list of languages supported by pygments but since it's not done by default maybe it's because it's not such a good idea?

**Comment by gdetrez** [comment]
One more detail: the `\url` command also accepts a verb-like separated argument, i.e. you can write `\url+foobar+` where `+` can be replaced by any character that doesn't appear in the URL.

**Comment by gdetrez** [comment]
Oh, and there is also an `\urldef` command which is used like this:
```latex
\urldef{\mysite}\url{http://example.com}
```
There is no problem with spell checking there but the command is not highlighted entirely:

![selection_008](https://cloud.githubusercontent.com/assets/38019/9600293/993830ea-509a-11e5-9c18-3891dc3d5666.png)

**Comment by lervag** [comment]
Thanks, I've updated to address the remaining issues. Please test!

**Comment by gdetrez** [comment]
It works perfectly now, thank you!

**Comment by lervag** [comment]
Great! :)
