### ISSUE TITLE
Error when opening `.tex` files

### ISSUE THREAD

**Issue by L1szt** [lervag/vimtex#2192]
### Description

I have just installed vimtex but whenever I open a `.tex` file I'm getting the following error:

```
Error detected while processing BufRead Autocommands for "*.tex"..function dist#ft#FTtex[47]..FileType Autocommands for "*"..function <SNR>16_LoadFTPlugin[17]..script /Users/me/.vim/plugged/vimtex/ftplugin/tex.vim[25]..function vimtex#init[7]..<SNR>42_init_state[1]..vimtex#state#init[1]..<SNR>43_get_main[25]..<SNR>43_file_is_main[16]..vimtex#parser#preamble[1]..vimtex#parser#tex#parse_preamble[6]..<SNR>46_parse_preamble[16]..vimtex#parser#tex#input_parser[10]..<SNR>46_input_to_filename[21]..vimtex#kpsewhich#find:
line   27:
E897: List or Blob required
Error detected while processing BufRead Autocommands for "*.tex"..function dist#ft#FTtex[47]..FileType Autocommands for "*"..function <SNR>16_LoadFTPlugin[17]..script /Users/me/.vim/plugged/vimtex/ftplugin/tex.vim[25]..function vimtex#init[7]..<SNR>42_init_state[1]..vimtex#state#init:
line    1:
E714: List required
```

### Steps to reproduce

Here is my `.vimrc` file
```vim
call plug#begin('~/.vim/plugged')

if executable('rg')
    let g:rg_derive_root='true'
endif

let loaded_matchparen = 1
let mapleader = " "

" all plugins
Plug 'mbbill/undotree'
Plug 'sirver/ultisnips'
Plug 'lervag/vimtex'
Plug 'folke/tokyonight.nvim', { 'branch': 'main' }
call plug#end()
```

### Do you use a latexmkrc file?

Yes (but also without using them it doesn't work)
### VimtexInfo

I'm getting: `not an editor command`, so after opening the file and getting the above error message the extension doesn't work.

**Comment by lervag** [comment]
Can you update VimTeX and try again?

**Comment by L1szt** [comment]
@lervag I deleted  and   reinstalled it but it still throws the same error message.

**Comment by lervag** [comment]
Strange. It should give another error message. I believe you can fix this by opening Vim/neovim and running `:VimtexClearCache kpsewhich`.

**Comment by lervag** [comment]
There should be an error message that explains this, I don't understand why it

**Comment by L1szt** [comment]
@lervag  I'm getting `E492: Not an editor command: VimtexClearCache kpsewhich` even though everything is installed (I checked again)

**Comment by lervag** [comment]
Ah, yes; the command is only available when you open a tex file. Ok. Are you on Linux? If so, then you can do `rm ~/.cache/vimtex/kpsewhich.json` - it will do the same thing.

**Comment by L1szt** [comment]
@lervag  I'm on MacOS but it worked, thanks a lot!

**Comment by lervag** [comment]
Glad to hear it!
