### ISSUE TITLE
Plugin scan through whole current directory when build_dir is nonempty

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2198]
In function `s:compiler.create_build_dir()`, if `build_dir` is not empty, the plugin scans through the whole directory that contains the TeX file.

(from my reading of the code, it's to create separate build dir for each folder that contain file or something similar)

This is very slow in some cases.

I think this can be safely disabled when `g:vimtex_disable_recursive_main_file_detection` is set, because the main file is always the current file.

**Comment by lervag** [comment]
> I think this can be safely disabled when `g:vimtex_disable_recursive_main_file_detection` is set, because the main file is always the current file.

Perhaps, but it feels much more as a hack, because the option is really not related to this code.

**Comment by lervag** [comment]
Please test now.
