### ISSUE TITLE
Compiling a latex file with PDF preview on breaks terminal in WSL

### ISSUE THREAD

**Issue by saippua** [lervag/vimtex#2199]
### Description

Continued on from this issue here: https://github.com/neovim/neovim/issues/15734#issuecomment-938550953

When compiling a PDF in nvim vimtex in WSL, vimtex opens a preview of the compiled PDF using xdg-open. For some reason this breaks the terminal and causes issues like this:
![image](https://user-images.githubusercontent.com/30152369/136551419-1e6a4d2c-708c-4372-af2f-e9df335e74a4.png)

I've narrowed the issue to `:! xdg-open file.pdf` breaking, but `:term xdg-open file.pdf` not breaking.

Currently using `let g:vimtex_view_general_viewer = ''` as a workaround which prevents vimtex from opening the preview.

Suggested fix of `let g:vimtex_view_auto = 0` does not seem to work. Preview still opens.

I also have a .latexmkrc which I made just to be certain that latexmk isnt opening the preview itself..
```
$pdf_previewer = '';
$preview_mode = 0;
```

### Do you use a latexmkrc file?

yes

### VimtexInfo

```yaml
1 System info
  2   OS: Ubuntu 20.04.3 LTS
  3   Vim version: NVIM v0.4.4
  4   Has clientserver: true
  5   Servername: /tmp/nvimirAcvj/0
  6
  7 VimTeX project: ex3
  8   base: ex3.tex
  9   root: .../Ex3
 10   tex: .../Ex3/ex3.tex
 11   main parser: current file verified
 12   document class: article
 13   packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstext appendix atbegshi atveryend auxhook bigintcalc bitset enumerate epstopdf-base etexcmds gettitlestring graphics graphicx hycolor hyperref if 14   source files:
 15     ex3.tex
 16     regex/frank.txt
 17   compiler: latexmk
 18     engine: -pdf
 19     options:
 20       -verbose
 21       -file-line-error
 22       -synctex=1
 23       -interaction=nonstopmode
 24     callback: 1
 25     continuous: 1
 26     executable: latexmk
 27   qf method: LaTeX logfile
```

**Comment by lervag** [comment]
I've updated your post to include the content verbatim, instead of through the zip file.

The example is minimal, so just to be clear: you are observing the problem with that particular minimal example? Can you also clearly describe the steps you use?

**Comment by lervag** [comment]
> The issue can be reproduced by simply running `:! xdg-open file.pdf` in neovim.

Can you also reproduce this with `:call jobstart('xdg-open file.pdf')`? VimTeX now never uses `:! ...` to start any processes, so `:!` is irrelevant wrt. VimTeX.

> It seems obvious to me that vimtex isn't causing this bug, but rather vimtex is using some other functionality that is bugged.

I agree, or, at least in that VimTeX should not introduce any bug here. If there is really a bug in neovim is harder to say. You really _should_ update to a newer version (v0.4.4 is quite old).

> `g:vimtex_view_automatic = 0` seems to work. It's a viable workaround for me.

Great, glad to hear it. I'll take the liberty of closing the issue, then, but of course, feel free to continue the discussion.
