### ISSUE TITLE
Add option to specify auxdir

### ISSUE THREAD

**Issue by degill** [lervag/vimtex#220]
Hey there,

vimtex has the ability to specifiy the -outdir flag for latexmk by setting the variable g:vimtex_latexmk_build_dir

This essentially puts all generated files (*.aux and the like) but also the *.pdf files into the specified directoy.

Latexmk has the option to specifiy -auxdir where all generated files but the pdf will be put into.

Is there a way to achieve that behaviour through vimtex with a relative path provided?

**Comment by lahwaacz** [comment]
Unfortunately `latexmk --help` says:
```
   -aux-directory=dir or -auxdir=dir 
                 - set name of directory for auxiliary files (aux, log)
                 - Currently this only works with MiKTeX
```
The de-facto standard tex distribution on Linux is TexLive, so without some hacks like manually moving/copying some files there is no way to do this.

**Comment by degill** [comment]
Oh I see. I should have read the man page more thoroughly.

Thanks for the reply :)

**Comment by lervag** [comment]
Thanks @lahwaacz for investigating and responding. I think your conclusion is good. And sorry, @degill, I agree that `-auxdir` is nice, but since it is not supported by TexLive I won't support it in vimtex. :(
