### ISSUE TITLE
VimTeX silently stop when document contain `\errorstopmode` command

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2202]
(to the user, the issue could be obvious, but I just tried adding the command to test out some command-line compilation, then get back to VimTeX and was confused how it doesn't work. Still, it may be better if it raises some error `\errorstopmode is not supported`.)

To reproduce the issue:

Example document:

```latex
%! TEX program = xelatex
\documentclass{article}

\errorstopmode

\begin{document}

\undefinedcontrolsequence

text

\end{document}
```

Result: when compilation is started, there's a message "compilation started in continuous mode", then no more message.

**Comment by lervag** [comment]
Well, I'm not entirely sure how VimTeX should react to this. I could perhaps search for the `\errorstopmode` command (and perhaps there are similar commands) and give a warning when starting to compile, but then, it seems entirely unnecessary to ever use that command?

**Comment by lervag** [comment]
Note that adding the search for this command will add to the init processing and reduce performance. So I'm not convinced that it is worth the effort to do anything about it.

**Comment by lervag** [comment]
> It's possible to change like this ...

Yes, that seems safe. I'm pushing this (and similar for neovim) asap. Thanks for noticing this possibility and suggesting it!
