### ISSUE TITLE
More specific functions for vimtex API

### ISSUE THREAD

**Issue by L1szt** [lervag/vimtex#2212]
The vimtex api is great so far but I would like to have the possibility to find out whether my cursor is currently in a `x` section where `x` is just a placeholder for any possible section, e.g. 
```latex
\begin{x}
...
\end{x}
```
and I would like to be able to call some API function to tell me whether my cursor currently is in an `x`-block.

**Comment by lervag** [comment]
E.g. something like `vimtex#syntax#in`?

**Comment by lervag** [comment]
I.e., if you have the following source

```tex
\begin{x}
  cursor here
\end{x}
```

with the cursor where indicated, then `vimtex#syntax#in('x')` should return a true value.

**Comment by lervag** [comment]
Sorry, I was wrong. `...#in(...)` does not check specifically for environment `x`. It checks for syntax item x, which is generally not the same.

> Wouldn't it be easier to have `in()` return `'x'` and let the caller do the checking?

No, not quite - it would have to return the syntax stack.

----

However, we have `vimtex#env#is_inside(env)`, which I think should work as expected. And your question is the same - it could be relevant to add a function like `vimtex#env#get_current` which returns the current outermost environment. Or perhaps the full stack of surrounding environments?

**Comment by clason** [comment]
I don't see how anybody could complain about that :)
