### ISSUE TITLE
Put a curser back after autocomplete using ]]

### ISSUE THREAD

**Issue by zoome0215** [lervag/vimtex#2237]
For example, pressing `]]` after typing `\begin{align}` yields
```
\begin{align}\end{align}
```
with the curser at the last `}`. However, most of the times when the autocomplete of this kind is triggered, we want to put something between begin and end environment. Is it possible to do something to put he curser back to the closing braces of `\begin{align}` ?

**Comment by zoome0215** [comment]
Nevermind, sorry the correct way is 
```
\begin{align}
   write equation
   line 2
  etc ]]
```
gives
```
\begin{align}
   write equation
   line 2
\end{align}
```

**Comment by lervag** [comment]
Yes, precisely. However, please note that you probably also want to install a snippet plugin. I recommend that you read `:help vimtex-af-snippets` for more info and suggested plugins.
