### ISSUE TITLE
Continuous mode doesn't seem to work for me

### ISSUE THREAD

**Issue by svenstaro** [lervag/vimtex#224]
So `let g:vimtex_latexmk_enabled` reports 1 and so does `let g:vimtex_latexmk_continuous`. However, upon changing the document, it does not automatically get recompiled and I get no obvious errors. Running `latexmk -pvc -pdf` from the command line on the very same document works just fine.

Also, pressing <localeader>lv works fine in that it opens the generated pdf if there is one but it won't generate one by itself if there isn't. I'm using neovim.

How can I debug this further? latexmk is in my PATH.

**Comment by svenstaro** [comment]
Nevermind that, I'm an idiot and didn't issue VimtexCompile.

**Comment by lervag** [comment]
No problem! :)
