### ISSUE TITLE
Turning off syntax makes *vimtex#syntax#in_mathzone(...)* fail

### ISSUE THREAD

**Issue by cuppajoeman** [lervag/vimtex#2241]
### Description

Turning off syntax makes it so that snippets which use `vimtex#syntax#in_mathzone(...)` fail.
![output](https://user-images.githubusercontent.com/19198104/140994302-c4d72a3f-ba27-4048-8bac-f5bc3548199e.gif)

### Steps to reproduce

`$HOME/.config/nvim/pythonx/math_snippet_helpers.py`
```py
import vim
def math():
    return vim.eval('vimtex#syntax#in_mathzone()') == '1'

def comment(): 
    return vim.eval('vimtex#syntax#in_comment()') == '1'

def env(name):
    [x,y] = vim.eval("vimtex#env#is_inside('" + name + "')") 
    return x != '0' and x != '0'
```

`$HOME/.config/nvim/math-snippets/sets.snippets`
```py
global !p
from math_snippet_helpers import *
endglobal

...

context "math()"
snippet set "set" A
\\left\\{ $1 \\right\\} $0
endsnippet
```

Then having this line in the config: `let g:UltiSnipsSnippetDirectories=["math-snippets"]`

### Expected behavior

I expected them to expand even without syntax on. 

### Actual behavior

They don't expand

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info
  OS: Manjaro Linux
  Vim version: NVIM v0.6.0-dev+116-g35041432b
  Has clientserver: true
  Servername: /tmp/nvimSFuJaf/0

VimTeX project: book
  base: book.tex
  root: /home/ccn/knowledge-book
  tex: /home/ccn/knowledge-book/book.tex
  out: /home/ccn/knowledge-book/build/book.pdf
  log: /home/ccn/knowledge-book/build/book.log
  aux: /home/ccn/knowledge-book/build/book.aux
  fls: /home/ccn/knowledge-book/build/book.fls
  main parser: current file verified
  source files:
    book.tex
  compiler: latexmk
    configuration: 
      continuous: 1
      callback: 1
      build_dir: build
      latexmk options:
        -verbose
        -file-line-error
        -synctex=1
        -interaction=nonstopmode
      latexmk engine: -pdf
  viewer: Zathura
    xwin id: 0
  qf: LaTeX logfile
    addqflist: 62
    fix_paths: 63
    set_errorformat: 61
  document class: book
  packages:
    adjcalc
    adjustbox
    amsbsy
    amsfonts
    amsgen
    amsmath
    amsopn
    amssymb
    amstext
    amsthm
    atbegshi
    atbegshi-ltx
    atveryend
    atveryend-ltx
    auxhook
    babel
    bigintcalc
    bitset
    calc
    collectbox
    color
    currfile
    environ
    epstopdf-base
    etexcmds
    etoolbox
    expl3
    filehook
    filehook-2020
    filemod-expmin
    fontenc
    footmisc
    geometry
    gettitlestring
    gincltex
    graphics
    graphicx
    hycolor
    hyperref
    ifoddpage
    iftex
    ifvtex
    infwarerr
    inputenc
    intcalc
    keyval
    knowledge
    kvdefinekeys
    kvoptions
    kvsetkeys
    letltxmacro
    listings
    listingsutf8
    lstlang1
    lstlang2
    lstlang3
    lstmisc
    ltxcmds
    mathtools
    mhsetup
    nameref
    pdfcol
    pdfescape
    pdftexcmds
    pgf
    pgfcomp-version-0-65
    pgfcomp-version-1-18
    pgfcore
    pgffor
    pgfkeys
    pgfmath
    pgfrcs
    pgfsys
    refcount
    rerunfilecheck
    shellesc
    standalone
    stringenc
    svn-prov
    tcolorbox
    tikz
    titlesec
    trig
    trimclip
    trimspaces
    uniquecounter
    url
    varwidth
    verbatim
    xcolor
    xhfill
    xkeyval
    xparse
    xparse-2020-10-01
    xspace
```

**Comment by clason** [comment]
That's not a bug, surely: `vimtex#syntax#in_mathzone` works by checking the syntax region -- turning it off disables all features built on it.

**Comment by lervag** [comment]
Precisely what @clason states. If you want to use Tree-sitter for syntax highlighting, then you need a different mechanism instead of `vimtex#syntax#in_mathzone`, and I don't know how myself. Sorry.

**Comment by cuppajoeman** [comment]
All I was trying to do was to use vimtex *without* any highlighting enabled. It seems like the only way to do this is to redefine highlight groups since this command seems directly connected to whether syntax is on or off.

**Comment by clason** [comment]
Yes, `syntax` controls syntax _parsing_, not highlighting -- that is the responsibility of the highlight groups. Look at one of the many monochrome colorschemes on the internet.

**Comment by lervag** [comment]
> All I was trying to do was to use vimtex _without_ any highlighting enabled. It seems like the only way to do this is to redefine highlight groups since this command seems directly connected to whether syntax is on or off.

Yes, sorry. Parsing LaTeX is hard, and since we already do the parsing with the syntax matching it becomes natural to rely on this for certain things. This particular feature would be quite cumbersome to implement without the syntax parsing.
