### ISSUE TITLE
Error in opening TOC with separated-preamble-file project.

### ISSUE THREAD

**Issue by inakacalm** [lervag/vimtex#225]
I'm facing the same error as #214 when I try to open table of contents.
In my case, I noticed that this happen when I use separated preamble .tex file. 
Here is my project structure and MWE which have the error.
I've tried latexmain and TeX root specifiers but both have the same error.
Please excuse me if this behavior is natural which mentioned in vimtex.txt.

path/main.tex.latexmain
path/main.tex
path/chapters/preamble.tex
path/chapters/chapter1.tex

Contents of each files are,

main.tex
```
\input{./chapters/preamble.tex}

\begin{document}
	\include{./chapters/chapter1.tex}
\end{document}
```

preamble.tex
```
\documentclass{scrbook}
```
chapter1.tex
```
\chapter{chapter1}
	This is a chapter 1.
```

**Comment by lervag** [comment]
Can you try a similar example with the only difference that you put the `\documentclass` line in `main.tex`? I.e. include preamble content except the `\documentclass` in `preamble.tex`.

**Comment by inakacalm** [comment]
I tried your advise and it works fine. But after that, curiously opening the TOC works fine on my MWE in the initial post.
Whereas in my actual tex structure, the preamble file contains the latter "pdftex" in its file name.
To eliminate this latter, I notice that opening of TOC will be working correctly. I also try with
"tex.tex" preamble file and it also cause error in TOC opening.

**Comment by lervag** [comment]
I am sorry, but I don't quite understand what you mean with `the preamble file contains the latter "pdftex" in its file name`. I thus don't understand your last problem. Could you please explain again?

**Comment by inakacalm** [comment]
I'm sorry for my poor ability of English.
The error occurs on a following project structure, for example.

path/main.tex.latexmain
path/main.tex
path/chapters/preamble_pdftex.tex
path/chapters/chapter1.tex

**Comment by lervag** [comment]
Ok, so I tried to reproduce your initial problem. That is, I have the following files:
```
.
├── chapters
│   ├── chapter.tex
│   └── preamble.tex
├── main.tex
└── main.tex.latexmain
```

With the following contents:
```tex
% file: chapters/chapter.tex
\chapter{Chapter 1}
This is chapter 1.

% file: chapters/preamble.tex
\documentclass{scrbook}

% file: main.tex
\input{chapters/preamble.tex}
\begin{document}
  \include{chapters/chapter.tex}
\end{document}
```

Now I open `main.tex` and type `:VimtexTOC`. This opens the TOC window as expected with no errors. The only (minor) problem is that the `preamble` entry is missing, but that is not a major issue. If I move the `\documentclass` to `main.tex`, then everything works as expected.

I've also tried with the `preamble_tex.tex` and `preamble_tex_.tex`, and both work as expected.

Which options for vimtex do you use? Can you reproduce the problem with a minimal vimrc file?

**Comment by inakacalm** [comment]
Thank you for your reply but I am sorry that have mistaken in my descriptions again....
The error occurs when I include file "without" extension. Could you please try the following contents ?
```tex
% file: chapters/chapter.tex
\chapter{Chapter 1}
This is chapter 1.

% file: chapters/preamble_tex.tex
\documentclass{scrbook}

% file: main.tex
\input{chapters/preamble_tex}
\begin{document}
  \include{chapters/chapter}
\end{document}
```
I also try with following minimal vimrc file and it reproduces the error.

```vim
""
"" NeoBundle
""
" Note: Skip initialization for vim-tiny or vim-small.
if 0 | endif

if has('vim_starting')
   if &compatible
     set nocompatible               " Be iMproved
   endif

   " Required:
   set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
 call neobundle#begin(expand('~/.vim/bundle/'))
 
 " Let NeoBundle manage NeoBundle
 " Required:
 NeoBundleFetch 'Shougo/neobundle.vim'


"TeX
NeoBundle 'lervag/vimtex'

call neobundle#end()

filetype plugin indent on

NeoBundleCheck

""
"" Enable syntax
""
syntax on
"===========================================================================
"EOF
```

**Comment by lervag** [comment]
I think I found the problem, could you please test?

**Comment by inakacalm** [comment]
I tested your latest commit and now ```:VimtexTocOpen``` command is working fine on my situation.
Thank you so much!

**Comment by lervag** [comment]
Happy it works! :)
