### ISSUE TITLE
Math mappings don't work on some math delimiters

### ISSUE THREAD

**Issue by luiz00martins** [lervag/vimtex#2251]
_Note: This may be a bug. I'm assuming it's a missing feature or indended behavior. I may be wrong however._

**Is your feature request related to a problem? Please describe it.**

Currently, `ds$` deletes `\[ ... \]` math surrounds, but not `$ ... $` or `$$ ... $$`. This is also the case for other mappings, such as `di$`, `ca$`, etc...

![Peek 2021-11-18 08-57](https://user-images.githubusercontent.com/43142209/142416104-f50ae8b6-627e-4038-bbff-1e52eed3933a.gif)

**Describe the solution you'd like**
I'd be nice if these math mappings would also work on `$ ... $` or `$$ ... $$` delimiters.

**Describe alternatives you've considered**
I'm using `vim-sandwitch` right now, so it's possible to just remap the math commands to something like `dsm`, `cim`, `csm`, etc... However, I feel like it'd be nice if these math commands detected all types of math delimiters.

**Comment by clason** [comment]
Works for me with vim-surround, so that may be a conflict in your setup (or due to the way VimTeX integrates with vim-sandwich that you are not taking into account).

**Comment by lervag** [comment]
What's the output of `:map i$` inside a LaTeX file?

**Comment by lervag** [comment]
(Just FYI: This works as expected for me.)

**Comment by luiz00martins** [comment]
Must be a bug then, or some wrong config on my setup :\\

I'm a bit busy rn, but I'll try to pinpoint later what the issue is.

---

> What's the output of `:map i$` inside a LaTeX file?

```
o  i$           @<Plug>(vimtex-i$)                                 
x  i$           @<Plug>(vimtex-i$)
```

**Comment by lervag** [comment]
Well, it's strange, but without seeing a minimal example I really can't help much. In the video, you are only showing the `ds$` variant. Can you show the output of `:map ds`?

**Comment by luiz00martins** [comment]
Hi again, sorry for leaving you waiting. End of semester at college.

Anyway, after some (endless) bifurcations of my configs, I found the culprit: The latex treesitter. After removing `latex` from my `ensure_installed`, the mapping worked fine. As a bonus, my `.tex` files look much better. Your highlighting/conceal was being hidden by treesitter, and it's a shame, cuz it looks marvelous :)

I still find it weird though, since nothing was overridden. This is my `:map ds`:
```
n  dsm          @<Plug>(vimtex-cmd-delete-math)                                                                                                 
n  dsd          @<Plug>(vimtex-delim-delete)                                                                                                    
n  dsc          @<Plug>(vimtex-cmd-delete)                                                                                                      
n  dse          @<Plug>(vimtex-env-delete)
n  ds$          @<Plug>(vimtex-env-delete-math)
```

Which looks normal.

I also don't have the jurisdiction to decide if this is a *treesitter* or a *vimtex* problem, so I'll leave the decision to close this one up to you.

**Comment by clason** [comment]
> I also don't have the jurisdiction to decide if this is a treesitter or a vimtex problem, so I'll leave the decision to close this one up to you.

It's neither: Enabling tree-sitter syntax highlighting disables the builtin syntax highlighting -- on which many "smart" features of VimTeX (in particular, the environment detection) rely. So this is perfectly expected, and in fact even documented, I believe.

**Comment by lervag** [comment]
Yes, @clason is on point here. Please read `:help vimtex-requirements`, where this is documented under "Vim configuration".
