### ISSUE TITLE
Add ]d text object

### ISSUE THREAD

**Issue by urbainvaes** [lervag/vimtex#2257]
... for "from here to the next unmatched delimiter". I use `])` all the time (for example in `d])` or `c])`), and I think it would be very useful to have an `]d` operator map as well. Has this been considered before?

**Comment by lervag** [comment]
I can't remember that this has been suggested before, no. There are similar maps for environments (`]m` and similar) and math delimiters like `$..$` (`]n` and similar), but none for the delimiters.

E.g.:

```
  ]d [d   next/prev delimiter (exclusive)
  ]D [D   next/prev delimiter (inclusive)
```

It seems like a reasonable and good suggestion, so I'll add it when I get the time.

**Comment by andymass** [comment]
I do not mean to suggest in any way that vimtex can't add this for its users, but I wanted to mention that the plugin match-up supports this via `]%` and `[%`: https://github.com/andymass/vim-matchup/.  It very similar to vimtex's built-in matching but a bit more general, in the sense that all delimiter, environments, math, etc are considered to be "delimiters."

Also, wanted to note that while there is some nice properties of the lower/upper : inclusive/exclusive maps proposed (as opposed to `%` ones), `]d`, `[d`, `]D`, `[D` are all built-in maps in vanilla vim.  Although, that is admittedly very easy for the user to re-configure in vimtex and is not the only example of overriding a built-in map.

**Comment by lervag** [comment]
Thanks for the useful info, @andymass. You are right about the conflict with built-in maps, I forgot about that. And considering this is already available in vim-matchup, I feel it may be unnecessary to add to vimtex. It would most likely be a worse implementation, anyway.

So, @urbainvaes, perhaps a solution for you would be to install vim-matchup?

**Comment by urbainvaes** [comment]
Hi both,

Many thanks for your answers and for pointing out the existence of `vim-matchup`. I just gave it a try, but unfortunately it does not seem to cover my use case. For example, consider this situation (`|` denotes the cursor position):
```tex
\left(| \left[ hello world \right] \right)
```
It'd be great if `c]%` would change this to
```tex
\left(|\right)
```
but instead I get
```tex
    \left(|)
```
so I would say that `vim-matchup` is not a good solution at the moment.

@lervag My suggestion was to define *operator mappings* (which I don't think are built-in) to the next *unclosed* delimiter, so it's a bit different from what you wrote I think.

**Comment by lervag** [comment]
@andymass Do you have a comment about this? I do agree that the reported result of `d]%` is unexpected here, what's the rationale behind it?

@urbainvaes I know you suggested an operator-pending mapping, but I think what you are asking for is really much better to describe as a motion. Vim's motions are usually defined both as normal mode maps, visual mode maps, and operator mode maps, and I don't think you will find any motions in the standard docs that are not also available as an operator map. You will find more on how Vim describes this under `:help operator`.

**Comment by andymass** [comment]
I cannot reproduce that problem.   It's possible that match-up was not
actually enabled for latex, cf.
https://github.com/andymass/vim-matchup#vimtex-for-latex-documents

For me, c]% is fully exclusive of the ending \right)

Regardless of this I'm not completely clear what is meant by "next
*unclosed* delimiter" in this issue and whether the motions provided by
match-up suits OPs needs.

**Comment by lervag** [comment]
Ah, yes; for me, `d]%` also works as expected. I believe you need to use the following config:

```vim
let g:matchup_override_vimtex = 1
```

**Comment by urbainvaes** [comment]
@lervag : Yes, you are right, it would be much better to describe it as a motion, with `]d` just going to the right delimiter. And indeed, it'd be strange to have something defined as an operator map but a visual map, for example. Many thanks for the explanation !

@andymass : My mistake, I should have read the documentation better. With the line @lervag wrote, the plugin works very smoothly and does exactly what I was looking for. Thank you very much! :)

**Comment by lervag** [comment]
Great, happy to hear that you find vim-matchup to work as a resolution here. Note that this is also documented at `:help vimtex-af-enhanced-matchparen` - I'll admit it may be hard to notice this, but on the other hand, one would expect users to read the introduction of the documentation? Still, if you have a suggestion for how to improve the docs I'll be glad to hear it!

**Comment by urbainvaes** [comment]
The `vimtex` documentation is very good, and usually I always learn something when I read it. I must have missed the part of the introduction where `vim-matchup` is discussed.

You might be interested to know that `vim-ninja-feet` can also be employed to achieve the actions I initially described, with `c]id` or `d]id`, for example. The plugin only defines operator maps, unfortunately, so things like `]id` does not work in normal mode.

**Comment by lervag** [comment]
Thanks! I was partly aware of vim-ninja-feet. I could never quite fit it into my own workflow, but I appreciate the idea behind it!
