### ISSUE TITLE
Allow configuring the nvim path used inside s:inverse_search_cmd

### ISSUE THREAD

**Issue by poscat0x04** [lervag/vimtex#2261]
On NixOS, if one chooses to configure neovim declaratively, then the neovim binary gets wrapped inside a wrapper.
What the wrapper does is it calls the neovim binary with suitable arguments and environment variables. One of the arguments passed is `-u /nix/store/h97rm0ckx2p9vqcc5hsdkskykw882j87-init.vim` which is how the plugins such as vimtex get loaded.
This usually works fine, but when vimtex uses zathura for viewing pdf, and since [`get(v:, 'progpath')`](https://github.com/lervag/vimtex/blob/d9e05f5e8010ce43670d19655058a6dc8cad300e/autoload/vimtex/view/zathura.vim#L113) returns the path to the unwrapped binary, the unwrapped binary gets passed to zathura as part of the synctex command. This immediately causes a problem: since the unwrapped binary can't possibly load vimtex, the command will always fail.

One way to solve this is issue to allow configuring the nvim path used inside s:inverse_search_cmd so people using NixOS (and possibly GuixSD) can manually set the nvim path to the wrapper. Unfortunately, I'm don't know much vimscript so I cannot implement this.
See also: https://github.com/NixOS/nixpkgs/issues/78033

**Comment by lervag** [comment]
This issue is discussed further in #2262.
