### ISSUE TITLE
Disable conceal inside specific commands/environments

### ISSUE THREAD

**Issue by poscat0x04** [lervag/vimtex#2266]
**Is your feature request related to a problem? Please describe it.**
Currently, conceal is enabled in `\newcommand` and `\renewcommand` (and `\providecommand` and so on...), which means
this command:
```tex
\renewcommand\emph{\textbf}
```
will be displayed as:
```tex
\renewcommand
```
which is very confusing.

**Describe the solution you'd like**
I've noticed that conceal is disabled inside verbatim environments. I'm not sure how it's done but maybe we could
use the same method to implement an interface for users to disable conceal inside specific commands/environments.

**Comment by lervag** [comment]
First, I believe this is not an issue if you use `\renewcommand{\emph}...` - can you confirm?

Still, I agree this is not expected, so I'll look into it!

**Comment by lervag** [comment]
This should work as expected now.
