### ISSUE TITLE
Enable combining `vimtex_syntax_nospell_commands` and `vimtex_syntax_custom_cmds`

### ISSUE THREAD

**Issue by patricknraanes** [lervag/vimtex#2269]
Hi!

Sometimes I might want to ignore some "WeirdWord" in my spell check, without adding it to global spell-file (word not general enough), or a local one (messy).

I figured I could do

```tex
\documentclass{article}
\newcommand{\nospell}[1]{#1}
\begin{document}
Here's a \nospell{WeirdWord} for which I don't want spell checking.
\end{document}
```

with this in my `syntax/tex.vim`:
```vim
let g:vimtex_syntax_nospell_commands = ["nospell"]
```

This works great! Now I want to conceal `nospell` by adding
```vim
let g:vimtex_syntax_custom_cmds = [
      \ {'name': 'nospell'   , 'mathmode': 0, 'conceal': 1}
      \]
```
That works (conceals), except that it re-activates the spell-check! Is it possible to have enable their working in combination?

**Comment by lervag** [comment]
The `g:vimtex_syntax_nospell_commands` is deprecated. Please update VimTeX and read `:help g:vimtex_syntax_custom_cmds` for how to specify the nospell option.

**Comment by lervag** [comment]
(That is, your use case is covered even with an example.)

**Comment by patricknraanes** [comment]
Dang, `vimtex` development moves fast! My bad, and thanks!

**Comment by lervag** [comment]
No problem :)
