### ISSUE TITLE
VimtexCompile doesn't keep compiling automatically while I change my .tex file. 

### ISSUE THREAD

**Issue by Adrian-Cuvi** [lervag/vimtex#2274]
### Description

Recently, I started to use Vimtex and it was working fine **(real time update as I write my .tex file)** until I upgraded my machine to the macOS Monterey. _Now, I have to keep doing `:w` every time I make some change to my `.tex` file_ in order to see the compiled version. Basically, I like it more when I can see a real time update as I write my `.tex` file.

- I would greatly appreciate if anyone knows how to **_make vimtex give me a real time update_** like [for this guy](https://yufanlu.net/2018/09/03/neovim-latex/). _Scroll all the way to the end to see the **demo**_
- Also, when I do **VimtexInfo** I get the following:  _xwin id: Failed creating new xdo instance_. I would also like to know any possible solutions to fix this.
- Finally, When I do **VimtexCompileOutput** I get the following: _Need to update make_preview_continuous for target files_. How can I fix this?

As far as I know, Vimtex should already do it because it was giving me a real time update before I did the upgrade.

By the way, I am using _**zathura**_ as my pdf reader.

### **My vimrc are as follows:**

```vim
call plug#begin('~/.vim/plugged')
  Plug 'lervag/vimtex'
   Plug 'ckunte/latex-snippets-vim', { 'tag': '*' }
call plug#end()
```

### **General**

```vim
"              LaTex
" Setting for LaTex indentation
let g:tex_flavor='latex'
let g:vimtex_quickfix_open_on_warning = 1
let g:vimtex_quickfix_mode = 1
let g:tex_conceal = ''
let g:vimtex_view_method="zathura"
let g:vimtex_compiler_latexmk={'build_dir': 'ac'}
let g:vimtex_latexmk_preview_continuosly=1
let g:vimtex_compiler_latexmk = {
 \ 'continuous' : 1,
 \}
```

### **Minimal working example**

```tex
%!TeX ts-program = xelatex
%!TeX encoding = utf-8 Unicode
\documentclass[11pt,a4paper]{article}

\title{None title}
\author{None author}

\begin{document}

\maketitle
This is just a random text.
\end{document}
```

### **VimtexInfo**
```perl
System info
OS: macOS 12.0.1 (21A559)
 Vim version: NVIM v0.5.0
 Has clientserver: true
 Servername: /var/folders/tl/6gbjg0y95cz8zp1ryc4wbzdc0000gn/T/nvimDdDnTz/0
VimTeX project: paper
  base: paper.tex
  root: /Users/Alfred/Desktop/tuesday
  tex: /Users/Alfred/Desktop/tuesday/paper.tex
  main parser: current file verified
 document class: article
 compiler: latexmk
   engine: -xelatex
   options:
     -verbose
     -file-line-error
     -synctex=1
     -interaction=nonstopmode
   callback: 1
   continuous: 1
   executable: latexmk
   job: 
     jobid: 8
     output: /var/folders/tl/6gbjg0y95cz8zp1ryc4wbzdc0000gn/T/nvimDdDnTz/2
           cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -xelatex -pvc -e '$new_viewer_always = "0"' -e '$pdf_previewer = "zathura  -x \"/usr/local/Cellar/neovim/0.5.0/bin/nvim --headless -c \"\\\"\"VimtexInverseSearch \%{line} '"'"'\%{input}'"'"'\"\\\"\"\" \%S"' -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'paper.tex'
     pid: 3569
 viewer: Zathura
   xwin id: Failed creating new xdo instance.
   cmd_start: zathura -x "/usr/local/Cellar/neovim/0.5.0/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 12:14:'/Users/Alfred/Desktop/tuesday/paper.tex'  '/Users/Alfred/Desktop/tuesday/paper.pdf'&
 qf method: LaTeX logfile
```

### **VimtexCompileOutput**

```
**Rc files read:**
 NONE
**Latexmk:** This is Latexmk, John Collins, 21 September 2021, version: 4.75.
Viewing pdf
======= Need to update make_preview_continuous for target files
------------
Running 'echo vimtex_compiler_callback_compiling'
------------
vimtex_compiler_callback_compiling
**Latexmk:** I have not found a previewer that is already running. 
 So I will start it for 'paper.pdf'
------------
**Latexmk:** All targets (paper.xdv paper.pdf) are up-to-date
------------
Running 'start zathura  -x "/usr/local/Cellar/neovim/0.5.0/bin/nvim --headless -c "\""VimtexInverseSearch %{line} '%{input}'"\""" "paper.pdf"'
------------
Running 'echo vimtex_compiler_callback_success'
------------
vimtex_compiler_callback_success
```

### Expected behavior

Like I said, **I would like to get a live preview for my .tex files (real time update as I write the file)**

### Actual behavior

When I do **VimtexCompile** only compiles once and it does not give me a real time update as I write my `.tex` file. _If I want to see the changes that I made  I have to be always changing to normal mode and `:w`_,  and honestly, this is annoying and time consuming.

**Comment by Adrian-Cuvi** [comment]
Thank you for your reply. I thought I could perform a real time update with Vimtex. However, I will still keep using Vimtex because is a great tool. Lastly, Thank you for your recommendation in using  ``` for whenever  I have a code.

**Comment by lervag** [comment]
Thanks for the kind words, and feel free to open new issues in the future :)
