### ISSUE TITLE
Rename warnings as warnings, make them optional

### ISSUE THREAD

**Issue by asmunder** [lervag/vimtex#228]
So I just started using vimtex, which looks to be very nice! So I opened a document I've been working on for half a year, which compiles without warnings or errors. I was thus a bit surprised when vimtex said my document has 27 errors. Going through the list, none of them are errors, and they should be called warnings. What I mean is stuff like
```
1-article.tex|161 error| possible unwanted space at "{"
1-article.tex|894 error| Whitespace before punctation mark in " ."
```

Furthermore, I'm not sure it makes sense to warn about some of these. The "possible unwanted space" thing is triggered when I write stuff like
```
\includegraphics[width=\linewidth]{
  my-really-really-really-really-really-long-figure-name.png
}
```
and I don't see how there is anything wrong with that.

**Comment by lervag** [comment]
Have you seen `g:vimtex_quickfix_ignore_all_warnings` and `g:vimtex_quickfix_ignored_warnings`. You are probably also interested in `g:vimtex_quickfix_mode` and `g:vimtex_quickfix_open_on_warning`.

Let me know if none of those options are what you are after.

**Comment by asmunder** [comment]
Ah, sorry about the noise, the buffer I'm talking about came from syntastic rather than vimtex. Closing.

**Comment by lervag** [comment]
Ah, no problem! :)
