### ISSUE TITLE
Tectonic continous compilation

### ISSUE THREAD

**Issue by LU15W1R7H** [lervag/vimtex#2280]
`:help vimtex-compiler` states the following:

```
It does not support continuous
compilation like |vimtex-compiler-latexmk|, so the only relevant commands are
|:VimtexCompile| to start (single shot) compilation, and
|:VimtexCompileOutput| to see the compilation output. 
```

But that's not quite true (anymore).
The tectonic V2 CLI supports continuous compilation:

Starting continuous compilation
`tectonic -X watch`

Starting CC and open file (like `latexmk -pvc`)
`tectonic -X watch --exec "build --open"`

I would like for vimtex to have support for this.

Here is a reference page from tectonic for this: [V2CLI Watch](https://tectonic-typesetting.github.io/book/latest/v2cli/watch.html)

**Comment by lervag** [comment]
Just to be more clear; the reason the latexmk implementation works well with VimTeX is because we can utilize the `$success_cmd` and `$failure_cmd` and related settings to make latexmk signal a callback to VimTeX when a compilation was completed successfully or failed. Without these, the compilation will of course still work, but the user will not really know what is going on.

**Comment by SichangHe** [comment]
Well, referring to this old issue in my workaround setup.

**Comment by SichangHe** [comment]
Well, I don't know how to supply the current file in the arguments…

**Comment by lervag** [comment]
I'm sorry, but it's hard for me to know exactly what you mean and how I can be of help here.

> Well, referring to this old issue in my workaround setup.

I'm not sure who this comment was intended for..?

> Well, I don't know how to supply the current file in the arguments…

Do you want help? Can you be more explicit here, e.g. "supply the current file"; what do you mean by current file? Perhaps `expand('%')` is what you want? See `:help expand()` for more info. And "in the arguments" - arguments for what?

**Comment by SichangHe** [comment]
Hi @lervag, thank you for getting back to my random comments!

I linked to this issue in a configuration commit, so it shows in the browser UI. I was hoping this may serve as a reference for people who want Tectonic continuous compilation.

> > Well, I don't know how to supply the current file in the arguments…
> 
> Do you want help? Can you be more explicit here, e.g. "supply the current file"; what do you mean by current file? Perhaps `expand('%')` is what you want? See `:help expand()` for more info. And "in the arguments" - arguments for what?

Thank you! My current configuration hardcodes the TeX file path `main.tex` because I could not figure out how to pass the current file path into the command (if I could, it would be perfectly fine to use Tectonic). I checked VimTeX source code and it seems `vimtex_compiler_generic` runs the provided command as-is; is that correct?

**Comment by BachoSeven** [comment]
@lervag  I would also like to be able to pass the file in the command, but ran into the same issue where I cannot use vimscript because the command doesn't get expanded that way before being passed to the generic compiler. At the moment I simply have:

```vim
let g:vimtex_compiler_generic = {
	\	'command': 'ls *.tex | entr -n -c tectonic /_ --synctex --keep-logs',
	\}
```

**Comment by lervag** [comment]
> I linked to this issue in a configuration commit, so it shows in the browser UI. I was hoping this may serve as a reference for people who want Tectonic continuous compilation.

Ok!

> > > Well, I don't know how to supply the current file in the arguments…
> > 
> > 
> > Do you want help? Can you be more explicit here, e.g. "supply the current file"; what do you mean by current file? Perhaps `expand('%')` is what you want? See `:help expand()` for more info. And "in the arguments" - arguments for what?
> 
> Thank you! My current configuration hardcodes the TeX file path `main.tex` because I could not figure out how to pass the current file path into the command (if I could, it would be perfectly fine to use Tectonic).

Are you writing Lua or Vimscript? With Vimscript, you can get the file path to the current _main_ file with `b:vimtex.tex`. In Lua, you can use `vim.b.vimtex.tex`.

Depending on the context, you may need to have some guards ala `if exists('b:vimtex') ... endif`.

> I checked VimTeX source code and it seems `vimtex_compiler_generic` runs the provided command as-is; is that correct?

Yes, that is correct.

**Comment by lervag** [comment]
> @lervag I would also like to be able to pass the file in the command, but ran into the same issue where I cannot use vimscript because the command doesn't get expanded that way before being passed to the generic compiler.

With the generic compiler, there is currently no way to dynamically pass the current main file.

> At the moment I simply have:
> 
> ```viml
> let g:vimtex_compiler_generic = {
> 	\	'command': 'ls *.tex | entr -n -c tectonic /_ --synctex --keep-logs',
> 	\}
> ```

This seems like a reasonable approach that should work quite well.

But I'm curious, why do you not use the builtin `tectonic` compiler? Is it because it is not "continuous"?

**Comment by BachoSeven** [comment]
> > @lervag I would also like to be able to pass the file in the command, but ran into the same issue where I cannot use vimscript because the command doesn't get expanded that way before being passed to the generic compiler.
> 
> With the generic compiler, there is currently no way to dynamically pass the current main file.

Ok, that's good to know. Do you think there is some technical limitation, or would that be implementable?

> 
> > At the moment I simply have:
> > ```viml
> > let g:vimtex_compiler_generic = {
> > 	\	'command': 'ls *.tex | entr -n -c tectonic /_ --synctex --keep-logs',
> > 	\}
> > ```
> 
> This seems like a reasonable approach that should work quite well.
> 
> But I'm curious, why do you not use the builtin `tectonic` compiler? Is it because it is not "continuous"?

Indeed, I want to be able to compile on file save.

**Comment by lervag** [comment]
First, I'm sorry for the long wait for a reply here!

> > With the generic compiler, there is currently no way to dynamically pass the current main file.
> 
> Ok, that's good to know. Do you think there is some technical limitation, or would that be implementable?

Yes, it should be implementable. I think a good solution would be to allow some interpolation here. I propose something like this:

```vimhelp
*g:vimtex_compiler_generic*

  …

  command ~
    This is the command to run to start compilation. This can be any command,
    and the command is run from the project root. The command string will
    substitute `@tex` with the path to the current project's main tex file.
```

With it, you could use

```vim
let g:vimtex_compiler_generic = {
  \ 'command': 'ls @tex | entr -n -c tectonic /_ --synctex --keep-logs',
  \}
```

Or something like it.

Does this sound OK?

**Comment by lervag** [comment]
I've added it now, so you can test if that is what you want. I'd be happy to get some feedback on this.

**Comment by luiswirth** [comment]
Since the advent of typst I'm not really using latex anymore and therefore also not using tectonic. Neither am I using (neo)vim anymore. I'm unable to test this.

**Comment by lervag** [comment]
Ok, no problem. Thanks for letting me know. Have heard lots of good things about typst. :)
