### ISSUE TITLE
Just bringing into attention ltex - a new language server that automatically uses installed LanguageTool 

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2285]
I have used `vlty` that is supported in VimTeX. I think it  uses languagetool as the backend.

There is a brand-new __language server__ called `LTeX` [https://valentjn.github.io/ltex/index.html](https://valentjn.github.io/ltex/index.html)  that beautifully integrates with my existing Neovim LSP setup (i.e. with diagnostics in either floating window or in a separate buffer with the awesome `trouble.nvim`).

> LTEX provides offline grammar checking of various markup languages using LanguageTool (LT). LTEX can be used standalone as a command-line tool, as a language server using the Language Server Protocol (LSP), or directly in various editors using extensions.
>
> LTEX currently supports BibTEX, ConTEXt, LATEX, Markdown, Org, reStructuredText, R Sweave, and XHTML documents.

While `vlty` is a Vim-specific backend created by its original author, `LTeX` works in any editor that can work as a language client. This will provide a seamless collaboration experience with other co-authors who don't use `vim`.  i.e. both VimTeX users and non-VimTeX users will have similar experience using a common tool. 

I am hesitant to make a specific feature request to ask for "support" within VimTex, without having an idea about exactly what kind of support or integration within VimTeX is possible. But having used `vlty`, I think this can provide equivalent (if not better) grammar checking experience within vim for LateX documents. Perhaps other interested members of this community can evaluate [LTeX](https://valentjn.github.io/ltex/index.html) and discuss its potential use from within VimTeX?

PS1: There is also a separate Grammarly language that can be used within `vim` (I think using `coc-vim`). See an example here: [https://github.com/znck/grammarly/issues/138](https://github.com/znck/grammarly/issues/138).  I thought Grammarly was proprietary (with maybe a few free rate-limited requests/day to their API).  Hence, not much interested in it personally, but nevertheless mentioning here anyway.

**Comment by lervag** [comment]
LTeX is hardly brand new, but I agree it is worth noticing.

I don't think there is any kind of integration to be had between VimTeX and ltex, except perhaps an honorary mention in the docs in the same manner as texlab - I've added this now.
