### ISSUE TITLE
A typo in the _template.vim

### ISSUE THREAD

**Issue by wgmzbl** [lervag/vimtex#2287]
### Description

I suppose there is a typo in the line 254 in file autoload/vimtex/view/_template.vim.
The code "self.start" should be "self._start", I guess. Otherwise, there will be a
strange error like Key not present in Dictionary: "start".

If that is indeed a typo, would you like to fix it?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
typo report
```

**Comment by lervag** [comment]
You are right and it was a silly but also slightly severe issue. Thanks!
