### ISSUE TITLE
`VimtexEventCompileRunning` event for continuous compilation

### ISSUE THREAD

**Issue by Neelfrost** [lervag/vimtex#2290]
**Is your feature request related to a problem? Please describe it.**
I would like to display the compile status on my statusline. Currently, vimtex provides 3 events that trigger when:
1. Compile is first started,
2. Compile is successful, 
3. Compile has failed.

The above works great for single-shot compilation, but not when using continuous compilation, since compile runs every time the document is saved. 

**Describe the solution you'd like**
I would like another event that is triggered when a cycle of continuous compilation runs.
![image](https://user-images.githubusercontent.com/64243795/147768097-ad9b6b7b-1b1c-4007-b807-2485fa114866.png)

**Comment by lervag** [comment]
This already exists, but I forgot to document it. You want the `VimtexEventCompiling` event. I've updated the docs now.

**Comment by lervag** [comment]
Note, if you want this for a statusline feature, then you don't need to rely on the events. I use a custom statusline, but I believe my code should be not so hard to read, see here:

https://github.com/lervag/dotnvim/blob/c07302353b0544c4c6923b06ef0281ebb5077c18/autoload/personal/statusline.vim#L148-L157

```vim
  let l:status = getbufvar(a:bufnr, 'vimtex').compiler.status + 1

  let [l:symbol, l:color] = get([
        \ ['[⏻] ', ''],
        \ ['[⏻] ', ''],
        \ ['[⟳] ', ''],
        \ ['[✔︎] ', 'SLInfo'],
        \ ['[✖] ', 'SLAlert']
        \], l:status)
```

The idea here is that the statusline can check the `b:vimtex.compiler.status` attribute, which is the current compiler status. The status values are the same as those documented at `:help vimtex#compiler#callback`, although the values -1 and 0 may appear. -1 indicates that the compiler was never started, and value 0 means it is not running.

**Comment by Neelfrost** [comment]
This is even better! Thank you! :)

**Comment by lervag** [comment]
No problem :)
