### ISSUE TITLE
Adding pdfannots to the context menu

### ISSUE THREAD

**Issue by benbrastmckie** [lervag/vimtex#2294]
Given a citation which the cursor is hovering over, it would be great to be able to run [pdfannots](https://github.com/0xabu/pdfannots) on the associated pdf, where the resulting markdown file is saved in a "References" directory in the project directory where the .tex file lives. One natural thought would be to add this functionality to the context menu, where the result gives one a choice between associated pdfs if there is more than one, or spits out an error if there is no pdf, and otherwise creates the desired markdown file which includes all of one's annotations. 

Alternatively, if there is a way to access the path to the files associated with the citation that the cursor is hovering over, a keybinding in which-key could also be made to suffice. What I am imagining is that one could create a which-keybinding that runs pdfannots on the pdf associated with the citation that the cursor is hovering over, opening the resulting markdown file in a new buffer. This would be great, because then when citing a given paper, one could easily generate a markdown file with all of the annotations included in the pdf, where these might include highlighted text that one intends to quote.

I am unfortunately still inexperienced using vimscript/lua, and so would be very grateful for any pointers.

**Comment by lervag** [comment]
First, for reference, the question was also asked [on Reddit](https://www.reddit.com/r/neovim/comments/oif6zq/vimtex_v26/hst84yj/?context=3).

> One natural thought would be to add this functionality to the context menu, where the result gives one a choice between associated pdfs if there is more than one, or spits out an error if there is no pdf, and otherwise creates the desired markdown file which includes all of one's annotations.

I don't think this is a natural feature to add to VimTeX specifically. But it should not be too hard to make a custom feature on your end.

Alternatively, if there is a way to access the path to the files associated with the citation that the cursor is hovering over, a keybinding in which-key could also be made to suffice.

The following should probably do more or less what you ask:

```vim
nnoremap <c-f> <cmd>call PdfAnnots()<cr>

function PdfAnnots() abort
  try
    let infile = vimtex#context#get().handler.get_actions().entry.file
  catch /E121/
    echo "No file found"
    return
  endtry

  let outfile = fnamemodify(infile, ':t:r') . '.md'
  call system(printf('pdfannots -o "%s" "%s"', outfile, infile))
endfunction
```

Put the above inside `ftplugin/tex.vim` in your vim or neovim config folder (e.g. `~/.vim/...` or `~/.config/nvim/...`), and update it according to your preference. I.e., you will likely want to use a different key(!). I don't use which-key, so you will need to "fill out the blanks" in that regard. This also does not handle the "References" folder. But you can easily automate that as well by use of the following Vimscript features:

```vim
" b:vimtex.root is the root directory of the current project - it is available
" for all VimTeX projects as long as you are in a LaTeX buffer.
echo b:vimtex.root

" mkdir allows to create directories, e.g.
call mkdir('References', 'p')

" delete allows to delete a file (perhaps you don't need that)
call delete(...)

" you could also want to open the created annotation file by adding
execute 'split' fnameescape(outfile)
```

**Comment by benbrastmckie** [comment]
Amazing, I'm delighted! It works beautifully. I wish I had your powers of Vim wizardry. It's definitely inspiring to keep learning more (I am an academic without any background in programming, though I am considering diving into lua given the direction NeoVim is going).

With regards to making a 'References' directory, would the function have to be modified to go something like this:

```
function PdfAnnots() abort
  try
    let infile = vimtex#context#get().handler.get_actions().entry.file
  catch /E121/
    echo "No file found"
    return
  endtry

  let outfile = fnamemodify(infile, ':t:r') . '.md'
  if [THE References DIRECTORY DOES NOT EXITS IN THE ROOT DIRECTORY] " Not sure how to say this
    call mkdir('References', 'p')
  else 
    [RUN pdfannots AS BELOW, BUT INSIDE THE References DIRECTORY] " Equally unsure
    call system(printf('pdfannots -o "%s" "%s"', outfile, infile))
    execute 'split' fnameescape(outfile)
endfunction
```

I appreciate your help, and so I'm happy to pursue this inquiry elsewhere if you are short on time.

Thanks again!

**Comment by benbrastmckie** [comment]
Ok, got it sorted [here](https://www.reddit.com/r/vim/comments/s78qeg/comment/ht8kwvo/?utm_source=share&utm_medium=web2x&context=3). Thanks again!

**Comment by lervag** [comment]
Glad to hear it works and that you got the rest settled in a sufficient manner. I'm not "always on" and so did not have the time to reply until now, but I don't mind helping with this sort of thing. For reference, perhaps you could post your final version in this thread for potentially interested peers?

**Comment by benbrastmckie** [comment]
Of course, thanks for all of your help. I will definitely post here once I'm happy with it. I will also log it away in the [resources](https://www.youtube.com/channel/UCOi2wszcfvs0j9Pcom3z9VA) that I've been tinkering on for academics like myself that are trying to catch up. I'm sure there are more qualified people out there, but so far the intersection between LaTeX and Vim seems to be small, at least for beginners first trying to get going. Anyhow, I've been trying to reduce the slope of the learning curve to make the power of combining Vim and LaTeX more accessible.

**Comment by lervag** [comment]
> Of course, thanks for all of your help. I will definitely post here once I'm happy with it.

Happy to help - and great :)

> I will also log it away in the [resources](https://www.youtube.com/channel/UCOi2wszcfvs0j9Pcom3z9VA) that I've been tinkering on for academics like myself that are trying to catch up.

Nice! There's definitely room for this type of content! I agree on the observation that LaTeX + Vim is a small niche, and since there's quite the learning slope for both techs, everything that can make things easier for new people is very welcome!

**Comment by lervag** [comment]
I "skimmed" a couple of your videos now, and I like the content. As a general comment, it may be "confusing" to people that you use which-key and custom bindings for things where VimTeX provides commonly used defaults like `\ll` (for build), `\lv` for view, and so on. But this is not a problem, I think, and you get to show of which-key as well. I don't like that myself, but it is probably very useful, especially for new users.

In any case, well done. Good videos, good content, nice and calm voice - I would be very happy to have similar videos as a reference when I was starting out almost 20 years ago :)

**Comment by benbrastmckie** [comment]
Thanks! The truth is, I made those videos when I was pretty new to Vim, so hope to remake them once I port my config to as much Lua as possible. I'm also a bit more comfortable in my config now, and mostly done changing it, so can better organise the structure of the video series. Hopefully I'll get to this soon, but it's hard to find time for big projects right now.

**Comment by lervag** [comment]
Great! Make sure to announce your updated videos when you push them, e.g. on Reddit. Perhaps we could also link to them from the Readme as a combination of a demo and suggestion for configuration?

**Comment by benbrastmckie** [comment]
Will definitely announce on Reddit, and would love to be linked from the Readme. As for the PdfAnnots function, here is what I have:
```
function PdfAnnots() abort
  try
    let infile = vimtex#context#get().handler.get_actions().entry.file
  catch /E121/
    echo "No file found"
    return
  endtry

  let cwd = getcwd()
  try
    call chdir( Annotations )
  catch
    call mkdir('Annotations', 'p')
  finally
    call chdir( cwd )
  endtry

  let outfile = fnamemodify(infile, ':t:r') . '.md'
    call system(printf('pdfannots -o "Annotations/%s" "%s"', outfile, infile))
      " execute 'split' fnameescape(outfile)
      " could change 'split' to 'tabnew'
endfunction
```
I couldn't get it to open the file after it generates (I think that I don't have the full path to the file as it exists in the Annotations directory). If you can ease fix for that, or any other changes that make sense, I would love to know. But at least the above does almost everything that I want.

Thanks again for the pointers!

**Comment by lervag** [comment]
I believe this version should work:

```vim
function PdfAnnots() abort
  try
    let infile = vimtex#context#get().handler.get_actions().entry.file
  catch /E121/
    echo "No file found"
    return
  endtry

  let cwd = getcwd()
  try
    call chdir(b:vimtex.root)

    if !isdirectory('Annotations')
      call mkdir('Annotations')
    endif

    let outfile = "Annotations/" . fnamemodify(infile, ':t:r') . '.md'
    call system(printf('pdfannots -o "%s" "%s"', outfile, infile))

    execute 'split' fnameescape(outfile)
  finally
    call chdir(cwd)
  endtry
endfunction
```

**Comment by benbrastmckie** [comment]
Beautiful, works great!
