### ISSUE TITLE
Option to disable visual bold and italics

### ISSUE THREAD

**Issue by paniash** [lervag/vimtex#2295]
Hi!

Currently VimTeX doesn't support the option of disabling visual bold and italics in latex files. This is enabled by default with no straightforward way of disabling.

**Describe the solution you'd like**
Provide an option for the user to disable visual italics and bold.

**Describe alternatives you've considered**
[This](https://tex.stackexchange.com/questions/173445/disable-visually-italicizing-characters-in-textit-when-using-latex-suite#179472) stackexchange post describes disabling it but it does not work in my use case. (I'm not sure why).

**Additional context**
I'm using treesitter for highlighting. I've tested it on default regex-based syntax highlighting but the issue persists (following the stackexchange post).

**Comment by clason** [comment]
If you're using tree-sitter for LaTeX highlighting, the syntax files in this repository are disabled, so there's nothing to be done here.

In general, bold and italics are set by your color scheme, not the syntax files themselves. (Note that VimTeX uses different highlight groups than the upstream syntax file, see `:h vimtex-syntax-reference`.)

**Comment by lervag** [comment]
What @clason says is right. If you use Tree-sitter, then VimTeX syntax highlighting is not relevant.
