### ISSUE TITLE
Option to ignore double dollar sign when highlighting

### ISSUE THREAD

**Issue by xsrvmy** [lervag/vimtex#2296]
Is it possible to add an option for treating `$$` as two separate dollar signs when highlighting, given that `\[\]` is supposed to be used for display math is latex? The reasoning for this is to avoid the screen flashing when using a snippet to insert `$$` and put the cursor in between.

PS. Yes I know `\(\)` exists but the readability of that is debatable.

**Comment by lervag** [comment]
I'm sorry, but I don't quite understand. Can you explain this a bit further?

**Comment by xsrvmy** [comment]
Basically I'm wondering if you could add some configuration option to disable the `$$` syntax for display math for syntax highlighting and conceal.

The reasoning for this is that if typing the closing bracket is setup (I use snippets for this), then typing `\(\)`, `\[\]` and `$$$$` will not change whether the rest of the document is math mode. However, typing `$$` intending to open and close inline math will momentarily flip math and non-math in the rest of the document, which recolors everything, and causes a even bigger mess if conceal is used.

**Comment by lervag** [comment]
Ok, so, you want to disable the syntax highlighting of e.g. `$$ display math f(x) = 1$$`?

I'm not sure - it feels "wrong" to me to add this as an option. The `$$ ... $$` is really a part of the language, and to remove it to allow a "random" user workflow, even with an option, does not sound quite right to me. It feels like we're adressing the wrong end of the problem.

However, it should be easy for you to remove the syntax group from your end.
Create the file `~/.vim/after/syntax/tex.vim` (Vim) or `~/.config/nvim/after/syntax/tex.vim` (neovim) and add

```vim
syntax clear texMathZoneXX
```
