### ISSUE TITLE
[Feature] Conceal \emph{text} and set text in italic

### ISSUE THREAD

**Issue by Hotschke** [lervag/vimtex#230]
Are you considering extending  conceal functionality distributed by vim?

I have encountered the conceal feature of vim in markdown plugins, such as

https://github.com/prurigro/vim-markdown-concealed
https://github.com/vim-pandoc/vim-pandoc-syntax  

Using one of these plugins enables following behaviour of vim:
Enter following
\*italic\*
Move the cursor to a different line. Then the appearance of the other line changes to:
 *italic*

The surruonding stars are hidden and the text is in italics, resembling the html output at a very basic level.

Vim has builtin support of concealment for latex. For example, you can conceal \alpha by its unicode letter (file stays untouched).

I miss the markdown capability for \emph{} in latex. So I would be happy to see this added to vim itself or your plugin.

**Comment by lervag** [comment]
I see no reason not to add this, as I agree that it should be added for completeness. However, I propose that you also send a message to Charles Campbell, the maintainer of the Vim syntax file, see [here](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_TEX).

**Comment by Hotschke** [comment]
Thank you very much for adding this. I quite like it. I will add textbf, textit, mathbf on my own. When I find the time I will send an email to Charles Campbell.

**Comment by lervag** [comment]
No problem. I'd be happy if you could let me know if you get a response from Charles Campbell, especially if he adds support.
