### ISSUE TITLE
@page option in g:vimtex_view_general_options

### ISSUE THREAD

**Issue by AmeerTaweel** [lervag/vimtex#2302]
I'm using `termpdf.py` as a pdf viewer. There is no option for it to go to a specific line/character, but it can go to a specific page in the document. Please add a `@page` option to `g:vimtex_view_general_options` so that I can achieve this.

**Comment by AmeerTaweel** [comment]
This is my current setup. It uses `termpdf.py` inside `kitty`. It's very hacky but it works. If I have the `@page` option it will be perfect (at least for my needs):

```lua			
local script = '[ "$(kitty @ ls | grep -c \'"title": "vimtex-live-output"\')" -ne 0 ]; '
script = script .. 'if [ "$?" -eq 0 ]; '
script = script .. 'then kitty @ --to "$KITTY_LISTEN_ON" send-text --match title:"vimtex-live-output" "\\x12"; '
script = script .. 'else kitty @ --to "$KITTY_LISTEN_ON" new-window --keep-focus --title "vimtex-live-output" "$SHELL"; '
script = script .. 'kitty @ --to "$KITTY_LISTEN_ON" send-text --match title:"vimtex-live-output" "termpdf.py '
vim.g.vimtex_view_general_viewer = script
vim.g.vimtex_view_general_options  = '@pdf \\n"; fi'
```

Many pdf viewers have the option of going to a certain page, but not to a certain character or line, so I think this option can be useful for many people who use unsupported pdf viewers using the general interface.

**Comment by AmeerTaweel** [comment]
If `@page` is available, I can make an `autocommand` that runs `VimtexView` on `VimtexEventCompileSuccess`, and I will get my pdf viewer to position correctly automatically.

**Comment by lervag** [comment]
The feature you are talking about is usually called forward search and is provided by synctex. VimTeX does not currently interface with synctex directly, and instead assumes that the pdf viewer does this work. However, I did implement [some basic synctex stuff for the MuPDF viewer interface](https://github.com/lervag/vimtex/blob/700c40d018b25cc367c26ba348127fe4c6d87638/autoload/vimtex/view/mupdf.vim#L117-L123), and I can possibly generalize that code to allow something like this. Or at least make it easier to hack on it for "power users". In the meantime, you may find the existing snippet useful.

**Comment by AmeerTaweel** [comment]
I'm new to Latex, and I guess that was obvious to you from my question. Thank you for explaining the relevant terms to me and pointing me in the right direction.

I read the snippet you implemented for `MuPDF` and played a little bit with `synctex`, and now I understand how I should implement forward-searching with `termpdf.py`.

**Comment by lervag** [comment]
No problem, I'm glad my answer was of help. Feel free to open new issues if you have other questions or suggestions or problems.
