### ISSUE TITLE
separate syntax zone for the argument of mathrm?

### ISSUE THREAD

**Issue by ces42** [lervag/vimtex#2307]
**Is your feature request related to a problem? Please describe it.**
I use snippets (UltiSnips) a lot for latex editing. Most of them are for math mode so I add a condition that only triggers them when `vimtex#syntax#in_mathzone()` is true. Now I would like to define snippets that convert e.g. `dim` or `sin` to `\dim` or `\sin` automatically in math. I can do this but one problem remains: If I have some variable with a "textual subscript", the singular locus of a space X which is denoted by a "sing" subscript, I typeset this as `$X_\mathrm{sing}$`. But `mathrm` is math and so the `sing` turns into `\sin` and `g`...
This might be my fault for using `\mathrm` instead of `\textrm`, but to my understanding `\mathrm` is considered the right solution and I do like using different (upright) fonts for text and math.

**Describe the solution you'd like**
Would it be possible to add a new syntax group say `texMathRm` for the contents of a `\mathrm` command (unlike with `\text` I **do** think that the contents of `\mathrm` should still be considered a math zone)? I admit this is very ad-hoc but it would allow me to easily solve this problem by doing an extra `synstack()` check.

**Describe alternatives you've considered**
Using `\textrm`, as explained above.

**Comment by lervag** [comment]
> This might be my fault for using `\mathrm` instead of `\textrm`, but to my understanding `\mathrm` is considered the right solution and I do like using different (upright) fonts for text and math.

I actually think that `\text` or  `\textrm` is OK in this case, because the subscript is essentially text. I would use `\mathrm` for e.g. specifying dimensionless numbers or similar.

But ok, this may all be opinionated, so let's assume `\mathrm{...}` really is appropriate here.

> Would it be possible to add a new syntax group say `texMathRm` for the contents of a `\mathrm` command (unlike with `\text` I **do** think that the contents of `\mathrm` should still be considered a math zone)?

Well, everything is possible. But it is not fully trivial. Are we sure there is no simple way to somehow solve this within Ultisnips? I know one may control when a snippet is expanded. Perhaps you could avoid expanding it just after `{`? You could probably also check this manually with `getline()` and `col()` in a similar fashion as the `vimtex#syntax#in_syntax()` is used with UltiSnips.

**Comment by ces42** [comment]
You are right, this is probably best left to UltiSnips

**Comment by lervag** [comment]
Great - feek free to share if you find a good solution :)

**Comment by ces42** [comment]
Current solution: I've added this to my snippets file
```python
global !p
def math(before):
	if not vim.api.eval('vimtex#syntax#in_mathzone()'): return False
	pos = before.find(r'\mathrm{')
	if pos == -1: return True
	level = 1
	for c in before[pos + 8:]:
		level += (c == '{')
		level -= (c == '}')
		if level == 0: return True
	return False
endglobal
```
adding `context "math(snip.buffer[snip.line][:snip.column+1])"` (or `context "math(snip.before)" if [this PR](https://github.com/SirVer/ultisnips/pull/1432) is merged) on top of your snippet definition now should make it trigger only if you are in math but outside `\mathrm`

This will not work correctly if you have multiline `\mathrm` or if your snippet trigger contains unmatched curly braces.
