### ISSUE TITLE
Vimtex + neocomplete: \cite{ does not show completion menu but \cite{, does

### ISSUE THREAD

**Issue by Hotschke** [lervag/vimtex#232]
I have encountered following inconsistent behaviour when using neocomplete and vimtex as documented in :h vimtex-complete-neocomplete

I have added following to `~/.vim/after/ftplugin/tex.vim`:
```
if !exists('g:neocomplete#sources#omni#input_patterns')
        let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.tex =
                        "\ '\v\\\a*(ref|cite)\a*([^]]*\])?\{([^}]*,)*[^}]*'
```

Enter follwoing in insert mode:
```
\cite{
\cite[chapt]{
```
No completion menu is shown.
However,  enter these and I get the menu:
```
\cite{<Backspace>{
\cite<ESCAPE>a{
\cite{,
\cite{,<ESCAPE>a

```

Some details about my setup: compiled with linuxbrew `$ brew install --with-gtk+ --with-client-server --with-lua --with-luajit vim` on Debian 7
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Sep 22 2015 15:47:31)
Included patches: 1-873
Compiled by Homebrew
Huge version with GTK2 GUI.
```
neocomplete and vimtex installed via vim-plug using master branches from the github repositories.

`vimrc`:
```viml
set nocompatible

filetype plugin indent on
set encoding=utf-8
set hidden
set backspace=2

syntax enable

call plug#begin('~/.vim/plugged') " {{{
Plug 'lervag/vimtex'
Plug 'Shougo/vimproc.vim', { 'do': 'make' }
Plug 'Shougo/neocomplete'
Plug 'Shougo/neosnippet'
Plug 'Shougo/neosnippet-snippets'
call plug#end() "}}}

" 'Shougo/neocomplete' options.
" let g:acp_enableAtStartup = 0
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#auto_completion_start_length = 3
" let g:neocomplete#sources#syntax#min_keyword_length = 4
" let g:neocomplete#enable_auto_select = 1
" let g:neocomplete#enable_fuzzy_completion = 0

inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><C-y>  neocomplete#close_popup()
inoremap <expr><C-e>  neocomplete#cancel_popup()

" <CR>: expand neosnippet and close popup
imap <expr><CR>
	\ pumvisible() ?
	\ (neosnippet#expandable() ?
	\ "\<Plug>(neosnippet_expand)" :
	\ neocomplete#close_popup()) : "\<CR>"

" <TAB>:
"inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<S-TAB>"
 
" Suggested by neosnippet:
imap <expr><TAB>
 \ pumvisible() ? "\<C-n>" :
 \ neosnippet#expandable_or_jumpable() ?
 \ "\<Plug>(neosnippet_expand_or_jump)" :
 \ "\<TAB>" 
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
 \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

" For conceal markers.
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
```

**Comment by lervag** [comment]
Confirmed. This seems like new behaviour, I am sure this used to work earlier. I'll investigate when I get the time.

**Comment by kiryph** [comment]
On my macbook it looks fine. 
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 15 2015 08:55:12)
MacOS X (unix) version
Included patches: 1-769
Compiled by Homebrew
Huge version with MacVim GUI.
```
If you happen to have a vim version with patch level between we could easily narrow it.

**Comment by lervag** [comment]
Interesting. I'll test with different patches to see when it stopped working.

**Comment by lervag** [comment]
I've just tested with a minimal vimrc file, where the problem does not occur. This implies it might be due to a plugin conflict.

**Comment by lervag** [comment]
@Hotschke (and @kiryph) Could you please test whether the problem also occurs in the master branch of vimtex with the vimrc file located in `/path/to/vimtex/test/issue-232/vimrc`. You can test simply with:

```sh
vim -u /path/to/vimtex/test/issue-232/vimrc
```
This should automatically open a test file in insert mode, where you can immediately type `\cite{` to check whether things work as expected. On my end, it does work as expected with this vimrc file.

**Comment by Hotschke** [comment]
@lervag No change on linuxbrewed vim-7.4.873 Huge on Debian 7 (as given above) using your minimal setup.

**Comment by lervag** [comment]
Meaning it still does not autocomplete? That is strange.

I see now that I am on Vim 7.4.854, so perhaps this is due to a newer patch?

**Comment by Hotschke** [comment]
Yes, no change. The compilation on my current system is sometimes strangely not reproducible, so I currently stick to my vim version. Hopefully someone else can see whether a newer can fix it.

However, you mentioned in your first comment that you can confirm the reported behaviour. Did you change anything else except to use a more minimal vimrc.

**Comment by lervag** [comment]
In my first comment, I think the problem was due to a mapping conflict where the completion was not started until after the timeout. When I try to reproduce again now, I see that the completion starts after about 1 second.

**Comment by Hotschke** [comment]
After typing `\cite{` waiting for a longer time does not bring the popup menu.

Also using the preinstalled (debian wheezy) vim 7.3.547 with lua also does not autocomplete on `\cite{`

`\usr/bin/vim --version`
```
VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Feb 10 2013 02:27:59)
Included patches: 1-547
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by jamessan@debian.org
Huge version with GTK2 GUI.
```

**Comment by petobens** [comment]
HI @Hotschke and @lervag, I think I encountered a similar problem which I reported [here](https://github.com/Shougo/neocomplete.vim/issues/390#issuecomment-130433146).
I believe it is a mapping conflict. I personally use UltiSnips but I think that I'm pretty much doing the same thing you do. The following mapping:

```vim
    imap <silent><expr><CR> pumvisible() ?
        \ (len(keys(UltiSnips#SnippetsInCurrentScope())) > 0 ?
        \"\<C-y>\<C-s>" : "\<C-y>") : "\<CR>"
```
doesn't trigger `cite{` completion when used with this snippet:

```
snippet tc "Cite" w
\cite{$0
endsnippet
```
If instead of pressing `<CR>` after writing `tc` I press `<C-y>` followed by `<C-s>` I do get cite completion (`<C-s>` is my mapping to expand/trigger snippets).  Unfortunately I have no idea how to fix it (maybe @Shougo can help).

![blahh](https://cloud.githubusercontent.com/assets/2583971/10222120/a8728394-6828-11e5-8ad0-1175cc404f46.gif)

**Comment by Hotschke** [comment]
@petobens thank you for providing your experience.

I have also switched to ultisnips. A minimal config is posted here:
https://github.com/SirVer/ultisnips/issues/519#issuecomment-143450416
But nothing has changed. Still no autocompletion after `\cite{`.
The snippet repository of honza provides `cite` snippets
https://github.com/honza/vim-snippets/blob/master/snippets/tex.snippets
However, removing them does not eliminate my problem.

**Comment by petobens** [comment]
@Hotschke I see. Sorry for not being able to provide any further help.

**Comment by lervag** [comment]
@petobens Thanks for the comment. In my suggested minimal vimrc I didn't load any snippet plugins or related mappings, so on my end this at least does not have anything to do with it.

@Hotschke I've just updated to Vim 7.4.884, and still it works as expected. Although, I did notice a strange behaviour where it only starts autocomplete if I type "quickly". That is, if write at one character per second, the completion does not start automatically. I do not understand why.

**Comment by Shougo** [comment]
Hm....
It seems neocomplete problem.
I will check it later.

**Comment by lervag** [comment]
@Shougo Thanks! In case you didn't notice, I've created a [minimal vimrc](https://github.com/lervag/vimtex/blob/master/test/issue-232/vimrc) that loads vimtex and neocomplete and sets the recommended neocomplete options. It also automatically loads an example file, goes to a specific line and starts insert mode. This makes it easy to quickly test whether `\cite{` triggers omni completion.

**Comment by Hotschke** [comment]
Since neocomplete uses lua, I add a little bit more details about lua:
`:lua print(_VERSION)` returns `Lua 5.1`
Vim's  says it is compiled with `-lluajit-5.1`.

I have noticed following line in neocomplete `" Escape string for lua regexp.` Lua does not have a true regex engine but its own pattern matching facility. Hence, I have checked if there were recent changes to this. As far as I can see nothing important has changed here: 
http://www.lua.org/manual/5.2/readme.html#changes
http://www.lua.org/manual/5.3/readme.html#changes
(Assuming everyone else already switched to lua-5.2 or lua-5.3 released 16 Dec 2011)

**Comment by lervag** [comment]
Just mentioning: I'm on `Lua 5.3`.

**Comment by lervag** [comment]
@Hotschke As I am not able to reproduce, and since I have really no idea what may be wrong on the vimtex side, I think I may not be able to help. I hope it might be a problem on the neocomplete side and that Shougo might be able to fix it. If not, then this might stay unresolved.

I'll leave it open for now, but I am not going to spend more time on it until more is known.

**Comment by Hotschke** [comment]
Actually, I could get it work in a virtual machine running debian 8 which has lua 5.2. Also on my macbook it works where I use MacVim with lua5.2.
If it is actually due to lua 5.1, it would be a neocomplete dependency issue. So you can't do anything.

Anyhow, thank you for your time.

**Comment by Shougo** [comment]
Sorry, it is neocomplete bug.
I have fixed.  Please update neocomplete.

**Comment by Hotschke** [comment]
@Shougo yes it works. Thank you very much.

Can you give a short explanation of your fix. Are all of the three commits  you've pushed related to this: https://github.com/Shougo/neocomplete.vim/commit/710a25385a9ff86927ae78d24cfd5b3e229de877, https://github.com/Shougo/neocomplete.vim/commit/b3205b57340f0d88c0a1a5b97bdcb9c019d9b264, https://github.com/Shougo/neocomplete.vim/commit/d2a78075207b97c105041927a125e2cf0b2b0ca5. Just out of curiousity.

**Comment by Shougo** [comment]
> Can you give a short explanation of your fix. Are all of the three commits you've pushed related to this: 

The completion is skipped after CompleteDone event.
So, I have changed completion skip implementation.
