### ISSUE TITLE
Improve ts$ when changing to display math

### ISSUE THREAD

**Issue by ji-cerny** [lervag/vimtex#2321]
To start, I really like the new "ts$" feature, thanks for it! 

I believe that it could be improved slightly: I never use `$$`, `\[` and `\]` for displayed mathematics. So I put
```
let g:vimtex_env_toggle_math_map = {
          \ '$': 'equation',
          \ '\[': 'equation',
          \ '$$': 'equation',
          \ '\(': '$',
          \}
```
into my .vimrc file. This does not work as expected (at least for me) since it does not put `\begin{equation}` and `\end{equation}` on new lines (as it does with `\[`, `\]` when `g:vimtex_env_toggle_math_map` contains `'$': '\['`). A workaround is to keep `'$': '\['` there and to do `ts$` twice, but it would be nicer not to have to.

**Comment by lervag** [comment]
I've improve the code and believe I've fixed this at the same time. Can you update and test?

**Comment by ji-cerny** [comment]
It works, thanks. 

There is only one little issue: When one does `ts$` on an inline formula that starts at the beginning of a line (or after an indentation), like
```
$ foo $ bar
```
then one gets
```
\begin{equation}
\end{equation}
foo
bar
```

**Comment by lervag** [comment]
Thanks! I believe it is fixed now.

**Comment by ji-cerny** [comment]
> Thanks! I believe it is fixed now.

Works for me now. Thanks!

**Comment by lervag** [comment]
Glad to hear it!
