### ISSUE TITLE
Double click for inverse search in vimtex+skim

### ISSUE THREAD

**Issue by uthpalaherath** [lervag/vimtex#2325]
Hello, 

Sorry for writing this as an "issue" when it is actually just a question. 

I have vimtex working with skim and everything is great!
I just wanted to ask if there was a way to do the inverse search (skim->vim) by just double-clicking on the PDF and not cmd+shift+click. I tried to look for a syntax to edit, but could not find one. 

Thank you, 

Cheers!
Uthpala

**Comment by clason** [comment]
No, that is something VimTeX has no control over. You'd have to make a feature request to Skim.

**Comment by uthpalaherath** [comment]
Thanks for the swift response @clason !

**Comment by uthpalaherath** [comment]
I do have a related question though.

When using a project with multiple tex documents (a thesis with multiple tex files for each chapter for instance), vim-> skim search works fine but skim->vim does not show the PDF location on the vim tex document. It doesn't even open the relevant tex file in the editor. Is this behavior expected? 

This isn't an issue for single tex files. 

Thanks again, 
Uthpala
