### ISSUE TITLE
[FEATURE] Add to toc `Bibliographic information file` and mapping <plug>(vimtex-open-bibfile)

### ISSUE THREAD

**Issue by Hotschke** [lervag/vimtex#233]
My typical latex manuscript consists of a tex file and a bib file.

I use ctags with `<Ctrl-]>` to jump from my tex file to entries of the bibfile, based on following setup 
- http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
- http://stackoverflow.com/questions/8119405/create-tags-file-for-latex-for-labels-and-bib-items
- https://caffeinatedcode.wordpress.com/2009/11/16/simple-latex-ctags-and-taglist/

However, when I want to add a new bibentry, I would like to jump to the bibfile directly without having to put the cursor on another \cite command.

As a vim user I have plenty of other options to get to this file.
I can navigate to `\bibliography{name_of_bibfile}` to open it with `gf`, use netrw/vinegar to get a directory listing. If it was already opened, it's in the buffer list. I could add it to the arglist , can use tpope/projectionist. And probably millions of other ways (fswitch, a.vim, ...).

As vimtex already extracts the bibfilename for its completion mechanism, I could imagine that vimtex can offer an out-of-the-box super convenient possibility without relying on other plugins.

1) An extension of the toc by an entry `Bibliographic information file` would be one way.
2) or simply add another mapping `<localleader>lb` `<plug>(vimtex-open-bibfile)`

**Comment by lervag** [comment]
Good idea! I'm working on it.

**Comment by lervag** [comment]
I've made a first attempt at solving this. I think it works pretty well. Thanks for the suggestion!

**Comment by Hotschke** [comment]
Great to see this addition. I've noticed following behavior:

When I open `gvim` and use `CtrlP` to find the tex file I want to work on, the current working directory (cwd) is not automatically set to the one of the tex file. So the call of `kpsewhich` to find the bibfile, when `cwd` is for example still my home directory, is not succesful. Obviously bib and tex file are not in the home directory.
kpsewhich simply does not find the bibtex file in the same directory of the tex file.
I can fix it by changing the pwd of vim to the one of the tex file.

I think invoking kpsewhich from the directory where the main tex or current tex file is located, would solve it.

I have tried to change the directory temporarily with `( cd .. && kpsewhich bibfile)` which has issues. Do you see what? (currently still using cwd, just for test purpose)
```diff
diff --git a/autoload/vimtex/util.vim b/autoload/vimtex/util.vim
index e7fab23..508743d 100644
--- a/autoload/vimtex/util.vim
+++ b/autoload/vimtex/util.vim
@@ -289,10 +289,12 @@ endfunction
 
 " }}}1
 function! vimtex#util#kpsewhich(file, ...) " {{{1
-  let cmd  = 'kpsewhich '
+  let pwdir = getcwd()
+  let cmd  = '(cd "' . pwdir . '" && '
+  let cmd .='kpsewhich '
   let cmd .= a:0 > 0 ? a:1 : ''
-  let cmd .= ' "' . a:file . '"'
-  let out = system(cmd)
+  let cmd .= ' "' . a:file . '")'
+  let out = system(shellescape(cmd))
 
   " If kpsewhich has found something, it returns a non-empty string with a
   " newline at the end; otherwise the string is empty

**Comment by lervag** [comment]
Sorry for being so slow. So, I've tried to reproduce, but I don't seem to have this problem. Could you please test again and explain how to reproduce?
