### ISSUE TITLE
standalone convert not called

### ISSUE THREAD

**Issue by ccaprani** [lervag/vimtex#2335]
### Description

@lervag more of an FYI than an issue; took me a while to track this down. Just leaving it here in case it helps someone else - please close, edit for accuracy, or remove of course, if you prefer!

**Problem**
vimtex doesn't pass on the call to `convert` when used in the `standalone` class. 

**Solution**
`-shell-escape` isn't enabled by default. Enable it (per [here](https://github.com/lervag/vimtex/issues/467#issuecomment-395840260)) by adding this to your vimrc: 
```vim
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-pdf',
    \   '-shell-escape',
    \   '-verbose',
    \   '-file-line-error',
    \   '-synctex=1',
    \   '-interaction=nonstopmode',
    \ ],
    \}
```

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
N/A
```

**Comment by lervag** [comment]
> **Problem** vimtex doesn't pass on the call to `convert` when used in the `standalone` class.

I do not immediately "recognize" this problem. I looked through the [standalone docs](https://texdoc.org/serve/standalone/0) and I believe I find the relevant documentation in Section 5.6.2. So, `-shell-escape` is required if the standalone package requires an external call to the tool `convert` - this is the case if you want to convert a standalone file into an image.

> **Solution** `-shell-escape` isn't enabled by default. Enable it (per [here](https://github.com/lervag/vimtex/issues/467#issuecomment-395840260)) by adding this to your vimrc:

Correct. I don't think we should add `-shell-escape` as a default option, as it may be harmful. The users should know what they are doing when they add this option.

Regardless, thanks for bringing awareness to this particular use case! I'll leave it open for a few days before I close it.
