### ISSUE TITLE
Add option for setting window size of compiler output

### ISSUE THREAD

**Issue by oestby** [lervag/vimtex#2337]
**Is your feature request related to a problem? Please describe it.**

When I run the compiler in continuous mode any compiler output will be presented in a window.
If there is a lot of output this window can get a bit disturbing and it pops up each time a buffer is saved.

**Describe the solution you'd like**
I wish that there would be an option to define the max or fixed size of the compiler output window.
A way to permanently close it as well would perhaps be a nice edition.

**Describe alternatives you've considered**
I have considered not running in continuous mode and just compiling one-shots, but I don't like the workflow

**Additional context**
I don't think there is any additional context, but I will gladly add it if needed.

**Comment by lervag** [comment]
You are (probably) not seeing the compiler output, you are seeing the Vim quickfix window. It opens when your document has errors/warnings. You will want to look into `:help g:vimtex_quickfix_mode` and probably `:help g:vimtex_quickfix_open_on_warning`.

Btw., this is _not_ a feature request. There are already sufficient options to do what you want, you just did not properly read the docs. Note, I do understand that it's quite a lot of text and so it is hardly realistic that new users read everything. But before suggesting a feature, you might instead open a regular issue. That would have asked you some other questions that would have been interesting to see the responses to, e.g. the output of `:VimtexInfo` and the relevant VimTeX configuration.
