### ISSUE TITLE
qpdfview forward search

### ISSUE THREAD

**Issue by xyegithub** [lervag/vimtex#2340]
I configured as the doc of vimtex 

```vim
let g:vimtex_view_general_viewer = 'qpdfview'
let g:vimtex_view_general_options
      \ = '--unique @pdf\#src:@tex:@line:@col'
```

However, It do not open the qpdfview after compile the tex using `\ll`. And when I remove the `--unique`, it opened.

```vim
let g:vimtex_view_general_viewer = 'qpdfview'
let g:vimtex_view_general_options
      \ = '@pdf\#src:@tex:@line:@col'
```

When i run `qpdfview --unique` in the shell command line, I recieve a message "Not connected to D-Bus server". And the qpdfview does not open. I wander what`s wrong with my configuration. Can anybody help?

**Comment by lervag** [comment]
> I recieve a message "Not connected to D-Bus server".

qpdfview requires a dbus connection for the `--unique` option to work. I believe a lot of synctex stuff also requires dbus, in case you want to have forward (and possibly backward) search.

You did not adhere to the issue template. It asks for a lot of information - I know that may be intimidating, but there is a reason I ask for it. It is hard to help when I know almost nothing about your system.

**Comment by lervag** [comment]
Based on #2339, ut seems you are running Ubuntu. How did you install qpdfview?
