### ISSUE TITLE
$ ... $ is not detected as mathzone

### ISSUE THREAD

**Issue by andyseve** [lervag/vimtex#2345]
Hi!

This is mainly a question, I did not find a better place to ask this. I apologize if this is not the right place for the post.

For whatever reason, vimtex#syntax#in_mathzone() returns 0 inside $ ... $ for me. This is stopping me from using all the imaps inside $ .. $, and syntax highlighting for $ .. $ and $$ .. $$ tend to be different.

Is this intended and is there any way to change this?

Here are my vimtex settings:
```
" # Vimtex configuration
let g:vimtex_enabled = 1
let g:vimtex_view_automatic = 1
let g:vimtex_toc_enabled = 1
let g:vimtex_toc_show_included_files = 1

let g:vimtex_cache_root = '/tmp/vimtex'

let g:tex_flavor = "latex"
```

and a minimal example:
```
\begin{document}
	\maketitle
	\[ this is mathzone \]
	$ this is not mathzone $ 
\end{document}

```

Thanks!`

**Comment by clason** [comment]
*sigh*  are you using Neovim with tree-sitter?

**Comment by andyseve** [comment]
yes I am using neovim with tree-sitter. Let me test with minimal settings. Thanks!

**Comment by clason** [comment]
Then this won't work: enabling tree-sitter highlighting disables _all_ built-in regex-based syntax features. I believe this is documented. I'm afraid you'll have to choose between tree-sitter and VimTeX (for the `latex` filetype) -- and I personally would choose the latter.

**Comment by lervag** [comment]
Yes, this is documented in the introduction under "Requirements".

**Comment by andyseve** [comment]
Thanks for quick replies! Sorry I was traveling and could only get to this now.

Just wanted to add this: Turns out that problem was also with the theme (ishan9299/nvim-solarized-lua) I was using. Disabling both fixed the problem.

**Comment by lervag** [comment]
Glad to hear it!
