### ISSUE TITLE
Compilation failed

### ISSUE THREAD

**Issue by thedawnboy** [lervag/vimtex#2349]
## Configurations related to vimtex

```lua
vim.g.tex_flavor = 'latex'
vim.g.vimtex_quickfix_mode = 0
vim.g.tex_conceal = 'abdmg'
vim.o.conceallevel = 2
vim.g.tex_clean_on_exit = 1
vim.g.vimtex_view_general_viewer = 'zathura'
vim.g.vimtex_view_method = 'zathura'
vim.g.vimtex_compiler_progname = 'nvr'
vim.g.vimtex_toc_config = {
  name = 'TOC',
  layers = {'content', 'todo', 'include'},
  split_width = 25,
  todo_sorted = 0,
  show_help = 1,
  show_numbers = 1,
}

vim.g.vimtex_compiler_latexmk = {
           executable = 'latexmk',
           options = {
             '-xelatex',
             '-file-line-error',
             '-synctex=1',
             '-interaction=nonstopmode',
           },
          }
```

## Question

Hello, Today I follow the guidance to install and use vimtex,and the configuration is above. But When I compile a file, it failed. The file is below.

![vimtex-2](https://user-images.githubusercontent.com/81896522/157005015-312ced6f-085f-46c6-ade4-118cb1c7d58b.png)

So I want to know what is wrong with the configuration?

Appreciate !

**Comment by lervag** [comment]
> Hello, Today I follow the guidance to install and use vimtex,and the configuration is above. But When I compile a file, it failed.

I believe the problem is in your configuration. See below.

> ```lua
> vim.g.tex_flavor = 'latex'
> ...
> ```

You can safely simplify your configuration to this:

```lua
-- NOTE: This is a Vim option and not only related to VimTeX!
vim.o.conceallevel = 2

-- NOTE: This is unknown to me and has nothing to do with VimTeX!
vim.g.tex_clean_on_exit = 1

vim.g.vimtex_quickfix_mode = 0
vim.g.vimtex_view_method = 'zathura'
vim.g.vimtex_toc_config = {
  name = 'TOC',
  layers = {'content', 'todo', 'include'},
  split_width = 25,
  todo_sorted = 0,
  show_help = 1,
  show_numbers = 1,
}

-- NOTE: Do not use vimtex_compiler_latexmk to change the default build
--       backend, instead use this:
vim.g.vimtex_compiler_latexmk_engines = { _ = '-xelatex' }
```

I strongly suggest that you read the relevant docs, e.g. `:help vimtex_compiler_latexmk_engines`. You should also take note to understand the difference between a global option and window/buffer local option. `'conceallevel'` is a window local option. See `:help local-options`.
