### ISSUE TITLE
Use DVI instead of PDF

### ISSUE THREAD

**Issue by mosco** [lervag/vimtex#2353]
Can vimtex be configured to produce a DVI file and automatically update the Skim viewer?

This has the potential to speed-up compilation times.

**Comment by lervag** [comment]
It's a decent question. I have never tried this myself, and so the simple answer is no. However, it could be possible with possibly small changes. However, I don't work with MacOS and so it's hard to develop in this direction for me. If you are capable of trying it yourself, then I'll be glad to assist with and review a PR!

**Comment by clason** [comment]
Skim can view DVI, so it should be possible to simply feed it the DVI file the same way as the PDF file currently.

**Comment by mosco** [comment]
@lervag If there is a simple way to configure vimtex to do this, I would be happy to test it on Mac.

**Comment by lervag** [comment]
v

**Comment by lervag** [comment]
Sorry, I believe something wrong happened when I responded here. I did not mean to only respond "v". I deleted that reply and I'll try again:

No, I don't think there is an easy way. You have to change the code, and I guess I never considered that people would want other than PDF output. It may not require big changes to the code, but they may be somewhat complicated as they will touch many parts of the code.

Notice, though, that you can use latexmk in a terminal and it is really not a bad experience. Run something like:

```sh
latexmk --dvi -pvc main.tex
```

Be sure to configure your `.latexmkrc` and define your viewer settings. Read (or skim) the manual to learn the various configuration options.

Sorry for the inconvenience, but I don't think I'll prioritize working on this. I will consider PRs, of course, if anyone should be tempted to work on it.
