### ISSUE TITLE
Consider adding the d/c/ts(i)m for inline math using \( and \) constructs (semantic/modern inline math repesentation)

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2355]
I notice in recent updates that VimTeX now has more support for `ts$` which surrounds the relevant buffer content with `$` ... `$`.  While this does represent inline math in the underlying TeX primitive, in the LaTeX macro package, this is discouraged.

The semantically correct way of representing inline math in LaTeX is `\[` ... `\]`. See this [top-voted tex.stackexchange question](https://tex.stackexchange.com/questions/510/are-and-preferable-to-dollar-signs-for-math-mode/513#513) that convincingly explains the rationale. I quote the extract of the first couple of paragraphs of the answer here:

>\( ... \) is LaTeX syntax. $ ... $ is TeX syntax.
>
> plainTeX only allows $. In LaTeX you can use both, but \( ... \) will give less obscure error messages when there is a mistake inside it.

In this spirit, I propose the inclusion of `sm` or `sim` (surrounding math/inline math), for the delete, change and toggle operations, i.e. `dsm`, `csm`, `tsm`  (or `dsim`, `csim`, `tsim`).  And to encourage new users with best practices, perhaps we could mark the `$` use as deprecated (but maybe still support it for legacy texts written?), and additionally link that top-rated stackexchange answer in VimTeX's documentation.

**Comment by clason** [comment]
And I strongly disagree that it's VimTeX's role to enforce (or even encourage) code standards.

**Comment by krishnakumarg1984** [comment]
Yes. I realised it as soon as I submitted the original issue report. I have modified the issue to request support for semantic inline math. 

I am convinced that the `\( ..\)` construct is superior and worth including with a text-object mapping in VimTeX, rather than promoting `$`.

**Comment by clason** [comment]
`:h g:vimtex_env_toggle_math_map`

**Comment by krishnakumarg1984** [comment]
>And I strongly disagree that it's VimTeX's role to enforce (or even encourage) code standards. 

Yes. I agree with you. I am happy to drop the request for the gentle nudge to use semantic standards in documentation wording. 

VimTex already supports the `ds$`, cs$`, `ts$` mapping. So, let's refocus this issue as a request to support **another correct inline math** surrounding construct.

**Comment by krishnakumarg1984** [comment]
>:h g:vimtex_env_toggle_math_map

Nice. Wasn't following all the latest VimTeX updates/features carefully.

Couple of last pending questions/suggestions:
- Can we mix and match them in the same VimTeX project? My collaborator is a professor who will write only with `$...$`, while I write with `\[ ..\]`. Would be nice to change that boolean toggle option to a priority-ordered list of supported math modes, and then just use `dsim/csim/tsim` (im = inline math) to be agnostic to whatever convention a document author is currently using? 
- I notice the above option is toggle only. So, how do I get the `change` and `delete` text-objects with the `\[..\]` inline math?

**Comment by lervag** [comment]
So, first:

* Inline: We have the modern `\( ... \)` that replaces `$ ... $`. There are good reasons to choose the former, but for some reason, I think most people still use the old variant.
* Display: Correspondingly, we have `\[ ... \]` that replaced `$$ ... $$`. In this case, there are even more and better reasons to choose the former, and in my experience, _no one_ uses the latter.

In the discussion, it is crucial to talk about either inline variants or display variants. You are mixing them up and e.g. comparing `$ ... $` to `\[ ... \]` - this just doesn't make any sense. E.g.:

> My collaborator is a professor who will write only with `$...$`, while I write with `\[ ..\]`.

These are _different_! Perhaps your professor uses inline `$ ... $` where he _should_ use display math, but that's a whole different topic.

You are asking for a separation between inline and display math commands, and also for it to be sensitive to the style of the author. Of course, this could be done, but I really can't see how it will improve any workflows. The current commands are `cs$`, `ds$`, and `ts$`.

* `cs$`: This allows to change to the desired type/environment. I can't see why it makes sense to make two commands for this one.
* `ds$`: Same - no reason to change this!
* `ts$`: You can specify the toggle list with `g:vimtex_env_toggle_math`, which I believe more or less addresses your issue spot on?

> I notice the above option is toggle only. So, how do I get the `change` and `delete` text-objects with the `\[..\]` inline math?

First: There is no such thing as `\[ ... \]` inline math!

Now: I don't understand what you mean. If your cursor is inside `\[ ... \]`, then `cs$` can be used to change it to what you want. E.g., type `cs$$` to change it to `$ ... $`.
