### ISSUE TITLE
Conceal

### ISSUE THREAD

**Issue by aloispichler** [lervag/vimtex#2356]
In love with vimtex and conceal:

1. Suggestion: It would be nice to conceal `\eqref{eq:17}` to `(eq:17)` and the same with `\label{…}` and other `\ref{…}`s. Similarly, as `\cite{Lervag}` nicely conceals to `[Lervag]`.

2. Suggestion: I have the following in my `init.vim`, possibly interesting for others as well:
    ```vim
    autocmd FileType tex syntax match texMathSymbol "\\nobreakdash-" conceal cchar=-
    autocmd FileType tex syntax match Character     "\~"             conceal cchar= 
    autocmd FileType tex syntax match texMathSymbol "&"              conceal cchar= 
    autocmd FileType tex syntax match texMathSymbol "\\ "            conceal cchar= 
    autocmd FileType tex syntax match texMathSymbol "\\;"            conceal cchar= 
    autocmd FileType tex syntax match texMathSymbol "\\not\\in"      conceal cchar=∉
    autocmd FileType tex syntax match texMathSymbol "\\{"            conceal cchar={
    autocmd FileType tex syntax match texMathSymbol "\\}"            conceal cchar=}
    autocmd FileType tex syntax match texMathSymbol "\^\\prime"      conceal cchar='
    autocmd FileType tex syntax match texMathSymbol "\\iint"         conceal cchar=∬
    autocmd FileType tex syntax match texMathSymbol "\\iiint"        conceal cchar=∭
    autocmd FileType tex syntax match texMathSymbol "\\tilde n"      conceal cchar=ñ
    ```

3. Suggestion: Would be nice to conceal
    ```tex
    \begin{theorem}
         a²+b²=c².
    \end{theorem}
    ```
    to
    ```tex
    Theorem.
        a²+b²=c².

    ```
    and other environments in the same way. (I did not manage to do this on my own.)

Thanks!

**Comment by lervag** [comment]
> In love with vimtex and conceal:

:D

> 1. Suggestion: It would be nice to conceal `\eqref{eq:17}` to `(eq:17)` and the same with `\label{…}` and other `\ref{…}`s. Similarly, as `\cite{Lervag}` nicely conceals to `[Lervag]`.

I would not mind to look at the `\eqref` specifically, as I think it is somewhat intuitive and could be interesting to people who like conceals. But I'm more skeptical of the other parts of this suggestions. For instance, are you sure that you want `\label{eq:17}` to look like `(eq:17)`? `\label` is sort of the _opposite_ of a reference, so would this not be confusing? And I am similarly skeptical of e.g. `\cref{fig:foobar} → (fig:foobar)`.

> 2. Suggestion: I have the following in my `init.vim`, possibly interesting for others as well: ...

Thanks! I'll look through this and possibly add some or all!

> 3. Suggestion: Would be nice to conceal `\begin{theorem}...\end{theorem}` and other environments ...

I'm sorry, but I believe this is more or less impossible to do in a general and good manner. Conceals can only fully conceal matched text or replace with a single character. We can do the specific conceal asked for here with a relatively simple approach: the core idea would be to first match the begin and end parts, then conceal the `\begin{t` with `T` and the `}` with `.` with contained elements. But, as may be apparent now, this will need to be fully specified for each similar environment, and we can not do more than capitalize the first letter and add a dot. I'm not fully convinced it is worth the effort.

Also: Which other environments?

**Comment by lervag** [comment]
Reg. suggestion 2:

* I've never seen `\nobreakdash-`. It feels very specific; is it from a package? Then it could potentially be better to add as support for that package?
* The space commands: `\~`, `&`, `\ `, and `\;` - I'm not sure if I agree that we should conceal them. When you use a specific spacing command, is it not better to actually see it?
* `\not\in`: Why don't you just write `\notin`? I can't really find much info about `\not\in`.
* `\{` and `\}`: I disagree; it can potentially make it hard to notice the difference between if `{` is a TeX brace or a math brace. I believe this should be a user configuration, as I don't want to add this potential confusion from VimTeX side.
* `^\prime` - Interesting. Is there a chance this could lead to unexpected results?
* `\iint`, `\iiint`, `\tilde n`: Thanks!

**Comment by aloispichler** [comment]
Hello again!

Thanks again for conceal. I use it, if I do not want to see the TeX code :-)

* I look fwd to seeing `\eqref(eq:17)` concealed to  `(eq:17)`. And yes, you are probably right with `\label{…}`.
* this `{` is a tex brace, but this `\{` is a math brace. I have not encountered any problems with that. I use conceal because I do not want to see the code, but what I mean. (However, I can conceal `\{` on my side here as well.)
* Please note that there is slight issue with phi, there are 3 of them and at the moment they are mixed up: Phi= Φ, varphi= φ, phi= ϕ,
* same with varepsilon=ϵ, epsilon= ε,
* same with Theta=Θ, theta= θ, vartheta= ϑ,
* and finally Pi= Π, pi=π, varpi= ϖ.
* Today I have added these lines:
```
autocmd FileType tex syntax match texMathSymbol "''"             conceal cchar="
autocmd FileType tex syntax match texMathSymbol "\^\*"           conceal cchar=*
\ {'name': 'll',      'mathmode': 1, 'concealchar': '«'}            " simply looks better
```
I did not manage to correctly conceal `\begin{theorem}` to `theorem`. I tried something all combinations with `syntax match` and `syntax region`, but I could not fix the issue. Just in case you know that - help appreciated.

Thank you!

**Comment by lervag** [comment]
> * I look fwd to seeing `\eqref(eq:17)` concealed to  `(eq:17)`. And yes, you are probably right with `\label{…}`.

I'll look into it and let you know when you can update to test!

> * Please note that there is slight issue with phi, there are 3 of them and at the moment they are mixed up: Phi= Φ, varphi= φ, phi= ϕ,
> * same with varepsilon=ϵ, epsilon= ε,
> * same with Theta=Θ, theta= θ, vartheta= ϑ,
> * and finally Pi= Π, pi=π, varpi= ϖ.

No, I believe VimTeX implements this correctly. I've tested by creating the following document and compiling it. The conceals correspond to the compiled output. At least on my end.

```tex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}
\begin{document}

\noindent
varepsilon: $\varepsilon$ \\ % Conceals to → ε
epsilon: $\epsilon$ \\ % Conceals to -> ϵ
Phi: $\Phi$ \\ % Conceals to -> Φ
varphi: $\varphi$ \\ % Conceals to -> φ
phi: $\phi$ \\ % Conceals to -> ϕ
Theta: $\Theta$ \\ % Conceals to -> Θ
theta: $\theta$ \\ % Conceals to -> θ
vartheta: $\vartheta$ \\ % Conceals to -> ϑ
Pi: $\Pi$ \\ % Conceals to -> Π
pi: $\pi$ \\ % Conceals to -> π
varpi: $\varpi$ % Conceals to -> ϖ

\end{document}
```

Notice, though, that in your claim you got varepsilon and epsilon mixed. The above sample is correct. The rendered output is this:

![image](https://user-images.githubusercontent.com/998898/160285234-dcb469de-50b0-4e41-97fa-ad5c4b5b4a90.png)


> * Today I have added these lines:
> 
> ```
> autocmd FileType tex syntax match texMathSymbol "''"             conceal cchar="
> autocmd FileType tex syntax match texMathSymbol "\^\*"           conceal cchar=*
> \ {'name': 'll',      'mathmode': 1, 'concealchar': '«'}            " simply looks better
> ```

It seems you missed something while copying, because the third line does not make sense here?

> I did not manage to correctly conceal `\begin{theorem}` to `theorem`. I tried all combinations with `syntax match` and `syntax region`, but I could not fix the issue. Just in case you know that - help appreciated.

You can do something like this: Create your own custom syntax script, e.g. `~/.vim/after/syntax/tex.vim`, add these lines:

```vim
syntax match texCmdThmConcealedBeg "\\begin{theorem}"
      \ contains=texThmConcealStart,texThmConcealEnd
syntax match texThmConcealStart "\\begin{t" contained conceal cchar=T
syntax match texThmConcealEnd "}" contained conceal
syntax match texCmdThmConcealedEnd "\\end{theorem}" conceal
```

**Comment by lervag** [comment]
I've added the `\eqref` rule now, please test.

**Comment by michaelfortunato** [comment]
Is there still interest in concealing `\tilde`? I can try to make a pull request. Thanks!

**Comment by lervag** [comment]
You mean like `\tilde n` for `ñ`? That's already supported, I think?

**Comment by michaelfortunato** [comment]
Yes, exactly. I must have misconfigured it. I apologize. I will confirm on my end.

**Comment by lervag** [comment]
I've added that now, please update and test. I believe this is correct behaviour in this case.

**Comment by michaelfortunato** [comment]
Yes thanks. I pulled the update, and got the following. Also, I confirmed that `:echo vimtex_syntax_conceal.accents` printed "1" before testing.

## Screenshot - Concealed

<img width="943" alt="image" src="https://github.com/user-attachments/assets/14081dd7-3ce3-4cfd-86fc-82d9c1e39ce5">
As you can see, accents are concealed only for certain letters.  New to vimtex (and only have a basic understanding of latex in general) so this may be the intended behavior. 

## Screenshot - Unconcealed
<img width="951" alt="image" src="https://github.com/user-attachments/assets/6c0845cb-a81c-4852-821d-9297e62fb587">

Thank you for the wonderful plugin! Followed https://ejmastnak.com/tutorials/vim-latex/luasnip/ and got into it. The text objects, for example, are particularly helpful.

**Comment by lervag** [comment]
I'm very glad you find the plugin useful! :)

Now, regarding the missing conceals here, the reason they are missing is because, as far as I know, they are not part of the common unicode characterset. I've added all the tilde variants I know how to write.

Now, we are discussing things in an old issue thread. Could I kindly ask that you open a new issue if you want to continue the discussion; e.g. if you find out how to add more tilde variants?
