### ISSUE TITLE
Add a way to disable default mappings.

### ISSUE THREAD

**Issue by AdrienDML** [lervag/vimtex#2361]
I use the workman layout and my movement keys are "htkl" the simplest and comfortable thing i found. But some of the vimtex mappings uses t as their first key. Which is very very annoying. 

I would like to have away to disable all the default mappings and add back the one i would like by myself.

**Comment by lervag** [comment]
No problem, glad to see you figured it out. Let me know if you think there's a good way to improve the docs to make it easier to figure out!
