### ISSUE TITLE
Delimited textobj when `set selection=exclusive`

### ISSUE THREAD

**Issue by patnr** [lervag/vimtex#2368]
Like always, thanks for the great work. I recently discovered the option

```vim
set selection=exclusive
```

which doesn't include the last char in a selection, useful to avoid selecting the end-of-line character. But now when I use vimtex's delimited textobj's (e.g. `da$`) the trailing `$` is not deleted. This also applies for `d` delimiters but not `e`. I believe this is a bug. [Related issue/fix from vim-textobj-user](https://github.com/kana/vim-textobj-user/blob/41a675ddbeefd6a93664a4dc52f302fe3086a933/autoload/textobj/user.vim#L327)

**Comment by lervag** [comment]
Thanks for the kind words and for the interesting issue. Could you please provide a couple of detailed examples, e.g. something along the lines of this:

```
text $inline| math$ other text
% dap from |
Expect:  text other text
Observe: text $ other text
```

This will help me understand what you see and what you expect and will greatly help in fixing the issue.

**Comment by lervag** [comment]
For my personal reference (so I don't have to look it up), the referred to solution from `vim-textobj-user` is to add this:

```vim
if &selection ==# 'exclusive'
  normal! l
endif
```

**Comment by patnr** [comment]
You provide one example there, except I'm referring to `da$`, not `dap`. Also `di$` leaves `$h$ rather than `$$`

Similarly, doing `dad` inside the brackets leaves the trailing `]` below. Same happens for parentheses.

`text $[abc def]$ other text`

**Comment by lervag** [comment]
I've pushed a fix now. Please let me know if you have more similar examples.
