### ISSUE TITLE
"E16: Invalid range" appears when opening files in paths containing the pattern `[text-number]`

### ISSUE THREAD

**Issue by sxmichaels** [lervag/vimtex#237]
I do homework in LaTeX and have my course folders organized by the format `[CODE COLLEGE-SECTION] TITLE`, e.g. `[PSYCH101 COL-2] Psychology 101`. When I use vim to open TeX files in such a path, Vimtex throws the following error and requires me to hit Enter to continue.

    Error detected while processing function vimtex#init..<SNR>90_init_buffer..<SNR>90_get_main..<SNR>90_main_latexmain:
    E16: Invalid range
    ...(several of these)...
    E16: Invalid range

This error seems to be thrown from line `368` in `autoload/vimtex.vim`, function `get_main_latexmain()`.

    let l:candidates = split(globpath(l:dirs, '*.latexmain'), '\n')

As best as I can tell, it's triggered by a pattern of the form `[TEXT-NUM]` in a folder name anywhere in the path, where TEXT is any string and NUM is any string of characters 0-9. I don't know enough Vimscript to try to fix this myself, but I suspect Vim is interpreting this part of the path as some other command rather than as a raw string.

**Comment by lervag** [comment]
Thanks for noticing and reporting the issue! I added a minimal test case for testing that reproduced your problem, see test folder, i.e. `/path/to/vimtex/test/issue-237`. The test case now works as expected, and so I think the problem is solved.
