### ISSUE TITLE
vimtex-faq-neovim relevant any more?

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2379]
### Description

VimTeX's documentation says: 
>Windows users should also read |vimtex-faq-windows|, and neovim users should read |vimtex-faq-neovim|.

However, `vimtex-faq-neovim` has no significant information (except a good-natured jovial remark). 

Throughout the documentation, there are references to `neovim` (e.g. applicability of various completion engines, server functionality etc.). In this instance, is there a need to direct users to a specific neovim-faq at the start of the help doc?

I remember that there was a need of `neovim-remote` (nvr) to facilitate inverse search from viewers. Has this been deprecated? Although the changelog says `g:vimtex_compiler_prognam` has been deprecated, I couldn't find the deprecation for the need of `nvr`. 

This is just really a clarification question (and if necessary, this issue may be taken as a gentle request to update the relevant parts of the documentation to reflect any significant requirements). 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
N/A
```

**Comment by lervag** [comment]
> VimTeX's documentation says:
> 
> > Windows users should also read |vimtex-faq-windows|, and neovim users should read |vimtex-faq-neovim|.
> 
> However, `vimtex-faq-neovim` has no significant information (except a good-natured jovial remark).

Agreed, I've removed this. I'm leaving the good-natured joke, though, but no reason to refer to it. :)

> I remember that there was a need of `neovim-remote` (nvr) to facilitate inverse search from viewers. Has this been deprecated? Although the changelog says `g:vimtex_compiler_prognam` has been deprecated, I couldn't find the deprecation for the need of `nvr`.

Yes, nvr is no longer necessary.

> This is just really a clarification question (and if necessary, this issue may be taken as a gentle request to update the relevant parts of the documentation to reflect any significant requirements).

Thanks, it's useful to get suggestions for improving the docs!

**Comment by krishnakumarg1984** [comment]
Would it be okay to ask a short explanation on why the `nvr` requirement was abolished? I looked at the changelog, but didn't see the deprecation notice for neovim users.

**Comment by lervag** [comment]
Yes, of course. The reason is that we don't need it anymore. We don't use the `--remote` flags for communication with neovim, instead, we use the built-in server api directly. It is documented under `:help vimtex-synctex-inverse-search`. To be more clear: Before, the pdf viewers called something like `nvr --remote FILE:LINE`, and `nvr` was responsible for communicating with the correct neovim instance. Now, viewers do `nvim --headless -c "VimtexInverseSearch %l '%f'"`, where `:VimtexInverseSearch` is a global command from VimTeX that essentially runs this code:

https://github.com/lervag/vimtex/blob/db71bcf4f1fa7e8c305ac8977717a7421654fb34/autoload/vimtex/view.vim#L148-L163

**Comment by krishnakumarg1984** [comment]
Thank you for the explanation. I understand it well now.

Interestingly, the recently released 0.7 version of nvim reintroduced the client-server functionality.


Finally, a related question. The docs mention that the minimum neovim version supported by VimTeX is 0.4.3. Elsewhere in the docs, there are multiple references to more recently introduced neovim features, such as treesitter and mentions plugins which leverage the lua API (e.g. cmp) which requires at least 0.5+. Is it best to update the minimum neovim version in the docs? Worthwhile to open a separate issue on this?

**Comment by lervag** [comment]
The minimum version requirement is indeed 0.4.3, and I believe it is more or less correct. VimTeX does not rely on treesitter and does not use any more recent features. I may be wrong, in which case I would be happy to be corrected and to update the docs. But I don't think there is a reason to update the requirement unless it reflects an actual requirement?
