### ISSUE TITLE
line joining over %, \\ and the like.

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#238]
when auto-formatting a paragraph with `gqap`, vimtex now respects environment boundaries and commented lines. however, some problems remain.

  - lines following a line with a mid- or end-line comment sign `%` are joined, producing wrong output
example:

before

    lala kdjf aksj % sjdkfja ks
    skdjf kdjf lskdjf 

after 

    lala kdjf aksj % sjdkfja ks skdjf kdjf lskdjf 

  - tex line breaks are joined.

before

    lakdfj askdfj alaskjd f \\ 
    ksj djfk

after

    lakdfj askdfj alaskjd f \\ ksj djfk

this does not produce wrong output but most likely is not intended as it obfuscates the input. arguably, some of the other line breaking commands should also not be joined over:

    \\ start a new paragraph.
    \\* start a new line but not a new paragraph.
    \cleardoublepage flush all material and start a new page, start new odd numbered page.
    \clearpage plush all material and start a new page.
    \linebreak allow to break the line here.
    \newline request a new line.
    \newpage request a new page.
    \pagebreak encourage page break.

**Comment by lervag** [comment]
Thanks, I will look into this when I get the time!

**Comment by lervag** [comment]
I've pushed a first version of a formatexpr that does some of what you want. In the initial version, I only treat the `%`, as this is the only thing that produces wrong output.

I am actually not sure if I think it should affect anything else. As you say, the other commands produce the same output, regardless of the line break.

Let me know what you think.

Note, though, the feature is off by default. Enable it with `g:vimtex_change_set_formatexpr`.

**Comment by lervag** [comment]
I'll consider this resolved for now. Feel free to reopen or open follow up issues.

**Comment by nilsbecker** [comment]
hi, thanks for the implementation. however, it does not seem to work for me currently. i `let g:vimtex_change_set_formatexpr=1` but then lines are still joined over `%` at the end??

**Comment by nilsbecker** [comment]
aside from the potential bug above, here is another idea, maybe too radical: 

no line joining if the last word on any line is a latex command. this would allow paragraphs like

```
\begin{document}
\title{Laba daba}
\date{\today}
\author{B.\,Bunny}
```
to remain untouched. or even
```
\begin{figure}[htpb]
	\includegraphics[width=\linewidth]{fig/mdsscc-erika.pdf}
	\centering
	\caption{\label{fig:mdsscc-erika}%
		Scatter plots of  bla bla bla}
\end{figure}
```
could be formatted as a whole without joining all the commands. essentially, `gq` would then work basically everywhere (unless i'm mistaken).

of course there will be false positives where a command like `\emph{aldskf}` occurs at the end of a line. the question is then if this is a reasonable price to pay...

**Comment by lervag** [comment]
That's strange. It works here. Before I consider the (radical) idea, I want to understand why the current version don't work with you. I therefore suggest that you open a new issue for the radical idea with a reference here. That way it will be easier to track, since I don't know when I get the time to work on things.

Could you report the output of `echo &formatexpr`? It should say `vimtex#change#format()`.

**Comment by nilsbecker** [comment]
ok, opened a new issue.

**Comment by nilsbecker** [comment]
hmm, now it works! sorry for the fuss, but i did restart vim and download the latest version of the plugin, or at least so i thought at least. anyway, it works as described for me now :)

**Comment by lervag** [comment]
Great, happy to hear it works!
