### ISSUE TITLE
Add option to disable second indent in list environments

### ISSUE THREAD

**Issue by mcorah** [lervag/vimtex#239]
I was surprised when I first encountered the behavior where list environments are indented twice. I would like a method to disable or modify this behavior that does not involve disabling indentation or modifying the source.

As this feature is implemented now, adding an extra indent in certain environments, there is no way of modifying this behavior without affecting other aspects of indentation behavior.

**Comment by lervag** [comment]
Hi. Could you please provide a simple example, just to make sure I understand your request correctly?

**Comment by mcorah** [comment]
Typically I would expect consistent tabbing (two spaces as I have it configured): 
```
\begin{align}
  2+2=4
\end{align}

\begin{itemize}
  \item first item in the list
\end{itemize}
```

However, what I get with automatic indenting in vimtex (and closing with ]]) is:
```
\begin{align}
  2+2=4
\end{align}

\begin{itemize}
    \item item is indented twice
      and the next line is indented to match
  \end{itemize}
  % something went wrong here

\begin{itemize}
    \item another
  \end{itemize} % and the same behavior occurs here
```

Commenting out the if conditions that add the extra indent in indent/tex.vim produced my expected behavior. This is what the diff looks like (not something I would commit but works for me):
```
@@ -71,21 +71,11 @@ function! VimtexIndent() " {{{1
   " Add indent on begin environment
   if pline =~# '\\begin{.*}' && pline !~ s:envs_noindent
     let ind = ind + &sw
-
-    " Add extra indent for list environments
-    if pline =~ s:envs_lists
-      let ind = ind + &sw
-    endif
   endif
 
   " Subtract indent on end environment
   if cline =~# '\\end{.*}' && cline !~ s:envs_noindent
     let ind = ind - &sw
-
-    " Subtract extra indent for list environments
-    if cline =~ s:envs_lists
-      let ind = ind - &sw
-    endif
   endif
 
   " Indent opening and closing delimiters
@@ -105,14 +95,6 @@ function! VimtexIndent() " {{{1
     let ind += &sw*(max([popen - pclose, 0]) - max([cclose - copen, 0]))
   endif
 
-  " Indent list items
-  if pline =~# '^\s*\\\(bib\)\?item'
-    let ind += &sw
-  endif
-  if cline =~# '^\s*\\\(bib\)\?item'
-    let ind -= &sw
-  endif
-
   " Indent tikz elements
   if pline =~ s:tikz_commands
     let ind += &sw
```

Also, exploring this further, what I am experiencing may be a conflation of a few issues. The intended behavior is, I believe, to produce something like this:
```
\begin{itemize}
  \item an item
    second line
\end{itemize}
```
as described in the default indent file maintained by YiChao Zhou.

**Comment by lervag** [comment]
Actually, this works (almost) as expected with me. If I copy you example into a minimal tex file, and then do: `gg=G`, then the indentation is correct.

Also, if I type out your example directly in insert mode, the autoindent seems to work correctly. Further, it also seems to work correctly with the `]]` mapping.

Could you please post a minimval vimrc file that reproduces this?

**Comment by mcorah** [comment]
This is an issue off automatic indenting while typing out the latex. Half
the issue is that I have to do that to fix the indent after.

**Comment by lervag** [comment]
And as I said, I could not reproduce the issue. In my test, the automatic indentation works as expected. Thus the problem is probably due to vimrc settings. So, if you could provide me with a minimal vimrc file where the problem should be reproducible, I could investigate further and perhaps fix the problem.

You could use [my minivimrc](https://github.com/lervag/dotvim/blob/master/minivimrc) file as an example/template. Add the necessary vimtex options and vim settings that are required to reproduce, and I will verify that I can reproduce.

**Comment by mcorah** [comment]
I appear to have a conflict of some sort with YouCompleteMe. When YouCompleteMe is disabled a line in an `enumerate` will initially be double indented initially but updated to a single indent once I finish typing in `\item`. That update does not happen if I enable YouCompleteMe (using only the recommended configuration options in the vimtex documentation). Since YouCompleteMe seems quite popular among vim-latex users this may be a peculiarity of my configuration and I will continue looking in to the issue on my own.

**Comment by mcorah** [comment]
Ok. So I was encountering Valloric/YouCompleteMe#1244. Apparently YCM does not play well with autoindent. I don't see this issue coming up anywhere here so I am not sure whether you are aware. 

Adding fix in the last comment:
```
if exists("g:loaded_fix_indentkeys")
    finish
endif

let g:loaded_fix_indentkeys = 1

" Set indentkeys option again on changed filetype option.
" This fixes TeX \item indentation in combination with YouCompleteMe.
" See https://github.com/Valloric/YouCompleteMe/issues/1244
" You may add more filetypes if necessary.
autocmd FileType tex,plaintex execute "setlocal indentkeys=" . &indentkeys
```
to the end of my vimrc fixed the issue. There are no plans to fix this issue as it is apparently a general issue with vim and other auto-completion engines. Since the vim-latex documentation already provides some instructions for working with YCM some form of this fix should probably be added so that new users don't continue to run into this problem.

**Comment by lervag** [comment]
Ok, I did a more thorough test, and it seems this really happens also with neocomplete a Shougo says. I then looked into the fix. After inspecting the difference in the `indentkeys` option with and without the fix, I made a simple change that seems to fix the issue on my end. Please check if it works for you.

**Comment by mcorah** [comment]
It works! Thanks for the help!

**Comment by lervag** [comment]
Great! And no problem! Let me know if you find this breaks something. I don't think it should, but I didn't test it very thoroughly.

**Comment by llinfeng** [comment]
I unfortunately had the sample problem, but was not able to solve it by pasting the readily available solution. However, there appears to be an even simpler alternative (if not sloppy and rigid), that solved my problem: to put the following line in `~/.vim/ftplugin/tex.vim` (or, wherever you find `ftplugin` folder on one's Windows system).

  ````
   " there are four spaces in enclosed by the double quotes.
  setlocal indentkeys="    "
  ````

As I am sticking with a very simple indentation rule: `4 spaces` for every possible levels of indentation, this simple, if not ugly fix does the job.

Hope this alternative approach may help some Windows users out.
