### ISSUE TITLE
Include \begin{align, equation, etc...} in math_bounds concealment setting

### ISSUE THREAD

**Issue by johnbcoughlin** [lervag/vimtex#2390]
For formatting equations in display mode, I use the `equation[*]` and `align[*]` environments almost exclusively -- because I want equation numbers and alignment. I would like the `\begin` and `\end` delimiters to be concealable in the same way as `$$` and `\[ \]` are, using the `math_bounds` entry in the `vimtex_syntax_conceal` dictionary.

Is that possible? Alternatively, it would be just as good (even better) to be able to set the font of these and all math delimiters to some faint color.

Thank you!

**Comment by lervag** [comment]
> Alternatively, it would be just as good (even better) to be able to set the font of these and all math delimiters to some faint color.

This is already (more or less) possible, although not with distinction of starred or not. You need to specify some highlight groups. You probably already have a colorscheme, so you should do something like this:

```vim
function! MyHighlights() abort
  highlight texCmdMathEnv     guifg=#abcdef
  highlight texMathEnvArgName guifg=#abcdef
endfunction

augroup MyColors
  autocmd!
  autocmd ColorScheme * call MyHighlights()
augroup END

colorscheme foobar
```

The point of the autocommand is explained in [this great Gist](https://gist.github.com/romainl/379904f91fa40533175dfaec4c833f2f). See `:h vimtex-syntax-reference` for more info on the various available syntax groups, and see the code (i.e. `autoload/vimtex/syntax/core.vim`) for all the details.

----

> I would like the \begin and \end delimiters to be concealable in the
same way as $$ and \[ \] are, using the math_bounds entry in the
vimtex_syntax_conceal dictionary.

I'm not quite sure if this is a good idea. Several math environments allow some extra options inside braces. It would also be a breaking change for a lot of people. However, you _can_ do this quite easily yourself: Add an `after/syntax/tex.vim` in your `.vim/` or `.config/nvim` folder and add these lines:

```vim
syntax match texMathEnvBgnEndConcealed "\\\%(begin\|end\)\>{align\*\?}"
      \ contained containedin=texMathZoneEnv conceal
syntax match texMathEnvBgnEndConcealed "\\\%(begin\|end\)\>{equation\*\?}"
      \ contained containedin=texMathZoneEnv conceal
```

I believe it should be relatively straightforward to add support for other similar environments.

I hope this helps!

**Comment by johnbcoughlin** [comment]
This is exactly what I was looking for, thank you!

**Comment by lervag** [comment]
Great, glad to hear it! :)
