### ISSUE TITLE
Bug in documentation in the example for custom_patterns for *g:vimtex_complete_ref*

### ISSUE THREAD

**Issue by 6601618158** [lervag/vimtex#2393]
### Description

In the documentation at https://github.com/lervag/vimtex/blob/dfaca59bbbf0079ab1b4f159337ae7f17d1b5289/doc/vimtex.txt#L1298, there seem to be two typos (?). 

```
let g:vimtex_complete_ref = {
        \ 'custom_patterns' = ['\\figref\*\?{[^}]*$']
        \ }
```
should probably be 

```
let g:vimtex_complete_ref = {
        \ 'custom_patterns' : ['\\figref\*\{-}{[^}]*$']
        \ }
```
instead. At least with these changes, things seem to work as expected. 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
Not relevant (I think).
```

**Comment by lervag** [comment]
Thanks! I'm quite sure that the `\?` is ok, but the `:` is a typo. Can you test `'custom_patterns': ['\\figref\*\?{[^}]*$']`?

**Comment by 6601618158** [comment]
> Thanks! I'm quite sure that the `\?` is ok, but the `:` is a typo. Can you test `'custom_patterns': ['\\figref\*\?{[^}]*$']`?

I guess I thought the `\?` was supposed to be the ‘non-greedy marker’ but escaped (‽), or something, which is `\{-}` in vim regex (which you probably are very aware of), but that doesn't really make sense there… I think I just don't understand what the `\?` is there for, and when testing, my version _seemed_ to have worked, but that was probably just a testing error on my side, because it definitely doesn't work _now_. :sweat_smile: 

`'custom_patterns': ['\\figref\*\?{[^}]*$']` seems to do what it's supposed to do though (although I was trying to use it for `{zref,zcref,zcpageref}`), so thanks!

**Comment by lervag** [comment]
> I guess I thought the `\?` was supposed to be the ‘non-greedy marker’ but escaped (‽), or something, which is `\{-}` in vim regex (which you probably are very aware of), but that doesn't really make sense there…

See `:help \?`: It matches 0 or 1 of the preceding atom.

> `'custom_patterns': ['\\figref\*\?{[^}]*$']` seems to do what it's supposed to do though (although I was trying to use it for `{zref,zcref,zcpageref}`), so thanks!

My pleasure; thanks for reporting the typo!
