### ISSUE TITLE
Add support for `\zlabel`s from `zref` 

### ISSUE THREAD

**Issue by 6601618158** [lervag/vimtex#2394]
Would you consider adding support for `\zlabel`s from [`zref`](https://ctan.org/pkg/zref)? 

AFAIK, the possible completion candidates for `labels` that `vimtex` provides are grabbed from the `*.aux` files, correct? `zlabel`s are also written to the `*.aux` files using `\zref@newlabel` instead of `\newlabel`, with the same first argument (the label itself), but a different second argument, providing more information. 

I'm guessing that `\zref@newlabel`s might even be easier to parse than `\newlabel`s, because all infos are enclosed inside of commands, e.g. `\page{1}` instead of just `{1}`. Other packages can also add new properties that are then added to this second argument with their own command. The `abspage` module, for example, adds an `abspage` property (corresponding to the ‘absolute’ page number) to this list in the form of `\abspage{1}`. 

Would you be willing to have a look at this, maybe if I provide some kind of meaningful minimal test file? I guess you would want to have a look at section 2.4 of the [`zref` documentation](http://mirrors.ctan.org/macros/latex/contrib/zref/zref.pdf) if that's the case. 

Here is something *I* think might work as a testfile (I stole your `sub3 with spaces.tex` and added some stuff; the compiler was `pdfTeX`):

```tex
% minimal.tex
\documentclass{scrartcl}
\usepackage{amsmath}
\usepackage{hyperref}
\usepackage{zref-user}
\usepackage{zref-clever}

\begin{document}

\section{sub3 with spaces}\zlabel{sec:sub3 with spaces}

\begin{equation}
  f(x) = 42
  \label{eq:sub3 with spaces}
\end{equation}

This is \zcref{sec:sub3 with spaces}, and \zcref{eq:sub3 with spaces} is up top.  
The same here, but without anything clever done to it: \zref{eq:sub3 with spaces}.

\end{document}
```

and

```aux
% minimal.aux
\relax 
\providecommand\hyper@newdestlabel[2]{}
\providecommand\zref@newlabel[2]{}
\providecommand*\new@tpo@label[2]{}
\providecommand\HyperFirstAtBeginDocument{\AtBeginDocument}
\HyperFirstAtBeginDocument{\ifx\hyper@anchor\@undefined
\global\let\oldcontentsline\contentsline
\gdef\contentsline#1#2#3#4{\oldcontentsline{#1}{#2}{#3}}
\global\let\oldnewlabel\newlabel
\gdef\newlabel#1#2{\newlabelxx{#1}#2}
\gdef\newlabelxx#1#2#3#4#5#6{\oldnewlabel{#1}{{#2}{#3}}}
\AtEndDocument{\ifx\hyper@anchor\@undefined
\let\contentsline\oldcontentsline
\let\newlabel\oldnewlabel
\fi}
\fi}
\global\let\hyper@last\relax 
\gdef\HyperFirstAtBeginDocument#1{#1}
\providecommand\HyField@AuxAddToFields[1]{}
\providecommand\HyField@AuxAddToCoFields[2]{}
\providecommand\BKM@entry[2]{}
\BKM@entry{id=1,dest={73656374696F6E2E31},srcline={9}}{5C3337365C3337375C303030735C303030755C303030625C303030335C3030305C3034305C303030775C303030695C303030745C303030685C3030305C3034305C303030735C303030705C303030615C303030635C303030655C30303073}
\@writefile{toc}{\contentsline {section}{\numberline {1}sub3 with spaces}{1}{section.1}\protected@file@percent }
\zref@newlabel{sec:sub3 with spaces}{\default{1}\page{1}\abspage{1}\zc@counter{section}\thecounter{1}\zc@type{section}\zc@cntval{1}\zc@pgval{1}\zc@enclval{}\zc@pgfmt{1}\anchor{section.1}}
\newlabel{eq:sub3 with spaces}{{1}{1}{sub3 with spaces}{equation.1.1}{}}
\zref@newlabel{eq:sub3 with spaces}{\default{1}\page{1}\abspage{1}\zc@counter{equation}\thecounter{1}\zc@type{equation}\zc@cntval{1}\zc@pgval{1}\zc@enclval{}\zc@pgfmt{1}\anchor{equation.1.1}}
\gdef \@abspage@last{1}
```

I've added `zref-clever` and `hyperref` to provide you with examples for new properties, and because `zref-clever` does some special stuff to `\label`s inside `amsmath` environments (`\label` creates both a `\newlabel` *and* a `\zref@newlabel`), because you can't (directly) use `\zlabel`s there. `zref-clever` basically replaces `cleveref`, by the way.

**Comment by lervag** [comment]
> Would you consider adding support for \zlabels from [zref](https://ctan.org/pkg/zref)?

Well, yes, I wouldn't mind considering it. But I'm curious: does completion not already work without parsing the `\zref@newlabel`? That is, it seems there are duplicate `\newlabel` entries for each `\zref@newlabel`. If I'm right, what do we gain from also parsing the `\zref@newlabel`s; i.e., why do we want to parse this as well?

By the way: it seems silly to support `zref` only for completions and not for e.g. syntax highlighting. The latter would be an easier task, I think, and more or less straightforward. If you think this is also relevant, please open a new feature request for that with some clear examples of code and descriptions of how it should be highlighted (unless it is clear from the context).

**Comment by lervag** [comment]
It would be useful if you could also provide a simple, minimal example and specify current behaviour vs expected behaviour. The provided example may work as the minimal example, but the current vs. expected is also useful to make it perfectly clear what is currently missing.

**Comment by 6601618158** [comment]
Sorry for not reacting for so long. I'll try to provide you with a less shitty example next time (I guess I tried to show too many things at once), and collect all the different commands with expected behaviour, etc. 

I already started with the last part a couple of days ago, but there seem to be more things to consider than I anticipated (and I'm guessing you wouldn't want to implement this piecemeal). 😅 I hope I can get this done over the weekend.

**Comment by lervag** [comment]
> Sorry for not reacting for so long. I'll try to provide you with a less shitty example next time (I guess I tried to show too many things at once), and collect all the different commands with expected behaviour, etc.

Great, and no problem.

> I already started with the last part a couple of days ago, but there seem to be more things to consider than I anticipated (and I'm guessing you wouldn't want to implement this piecemeal). I hope I can get this done over the weekend.

No rush; take whatever time you need. :)

**Comment by lervag** [comment]
Feel free to reopen if you get back to this.

**Comment by clason** [comment]
@lervag I think this issue has received some urgency, since `cleveref` has been unmaintained for years now and is increasingly broken on current LaTeX releases -- with 2025-06-01 to the point where I have to abandon it and switch to `zref-clever`, which is pretty much the official recommendation. And missing out on VimTeX syntax highlighting and completion hurts a lot ;)

**Comment by lervag** [comment]
> I think this issue has received some urgency, since `cleveref` has been unmaintained for years now and is increasingly broken on current LaTeX releases -- with 2025-06-01 to the point where I have to abandon it and switch to `zref-clever`, which is pretty much the official recommendation. And missing out on VimTeX syntax highlighting and completion hurts a lot ;)
> 
> (It's mostly about recognizing `\zcref` -- which takes options, as in `\zcref[S]{foo}` for `\Cref` -- not necessarily for `\zlabel', which most people won't need to use.)

Ok. So, the original issue seems to provide a lot of the necessary context for building the completion feature. I could also start looking at the highlighting from that example.

> Or is there a trick to make VimTeX believe `cleveref` is loaded without actually loading it so I can just redefine the `zref` commands and pretend I'm still using `cleveref`?
> 
> Ah, found it: `g:vimtex_syntax_packages`. Can I extend that, or do I have to copy the defaults?

If you define it in your config it will be combined with the defaults with `extends()`. Thus, no need to copy the defaults.

**Comment by lervag** [comment]
Do I understand correctly that you suggest reopening this in order to implement the completion based on the current input?

**Comment by lervag** [comment]
I've pushed an attempt at this - if I understood correctly it should be what you want.

**Comment by clason** [comment]
Yes, that's exactly what I'm saying :)

**Comment by lervag** [comment]
Great. I like it when things are simpler than first expected :)
