### ISSUE TITLE
vimtex#syntax#in_mathzone() not work correctly in markdown file

### ISSUE THREAD

**Issue by DehanLUO** [lervag/vimtex#2395]
### Description

Thanks for your [suggestion of the minimisation](https://github.com/lervag/vimtex/issues/2346#issuecomment-1127721712).

> Ah, no: the custom files should be `~/.vim/after/ftplugin/markdown.vim` or
> `~/.vim/after/syntax/markdown.vim`. Don't create this under the VimTeX repo.

I moved my markdown.vim to `~/.vim/after/syntax/markdown.vim`. But `vimtex#syntax#in_mathzone()` still returned 0. My current setup after your suggestions looks like this:

```vim
" ~/.vim/vimrc
" Install vim-plug if not found
if empty(glob('~/.vim/autoload/plug.vim'))
  sil !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
en

" Run PlugInstall if there are missing plugins
au VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
        \| PlugInstall --sync | so $MYVIMRC
        \| en

" Plugins package manager
cal plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
Plug 'preservim/vim-markdown'
cal plug#end()

let g:vimtex_view_method='zathura'

ino <expr> <Tab> "\<C-r>=vimtex#syntax#in_mathzone()<cr>"
```

```vim
" ~/.vim/after/syntax/markdown.vim
call vimtex#options#init()
```

### Steps to reproduce

1. Create markdown file with content as below.
2. Move cursor between `$` and press `<tab>` (custom mapping as indicated above).

### Expected behavior

```markdown
$press <Tab> and return 1$

$$
press <Tab> and return 1
$$
```

### Actual behavior

```markdown
$press <Tab> and return 0$

$$
press <Tab> and return 0
$$
```

**Comment by lervag** [comment]
First, thanks for moving this to a new issue. It makes it easier for everyone to, even if it was related to the previous issue.

I've taken the liberty of updating your description based on your comment in #2346. Please review it and update/change it if I am wrong. Also, please confirm that it is OK before we continue.

**Comment by DehanLUO** [comment]
Yes, those are right.

And I just tried some envs. I just replaced `$VIMRUNTIME/syntax/markdown.vim` with `$VIMRUNTIME/syntax/tex.vim`. My <Tab> still returned 0. And, I disabled `Plug 'preservim/vim-markdown'` in vimrc and reopened a markdown file. <Tab> returned 1.

Then, I kept `preservim/vim-markdown` being disabled, restored `$VIMRUNTIME/syntax/markdown.vim`, replaced my `~/.vim/after/syntax/markdown.vim` with `$VIMRUNTIME/syntax/tex.vim`, and appended `call vimtex#options#init()` to `~/.vim/after/syntax/markdown.vim`. My <Tab> returned 0.

**Comment by lervag** [comment]
> Yes, those are right.

Great. Then I understand your setup. Please note that the things you are trying are mostly not so relevant/interesting. Instead, let me try to help.

* First: From your input, it seems you are using Vim and not neovim. Is that right? In particular, I want to be certain that you do not have any Tree-sitter stuff enabled for Markdown and/or LaTeX.
* Next, given the `vimrc` in your original post, I believe the error is simply that you need to _enable_ the math stuff for `vim-markdown`. I.e., add `let g:vim_markdown_math = 1` to your vimrc.

To be clear, if I do this, things work as expected for me:

```sh
cd

# Remove old vim settings
mv .vim .vimold
mv .vimrc .vimrc.old

vim .vimrc # ADD SETTINGS SPECIFIED BELOW AND QUIT
vim        # ALLOW vim-plug TO INSTALL PLUGINS AND QUIT
vim test.md
```

with

```vim
" .vimrc
if empty(glob('~/.vim/autoload/plug.vim'))
  sil !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
en

" Run PlugInstall if there are missing plugins
au VimEnter * if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
        \| PlugInstall --sync | so $MYVIMRC
        \| en

" Plugins package manager
cal plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
Plug 'preservim/vim-markdown'
cal plug#end()

let g:vim_markdown_math = 1
let g:vimtex_view_method='zathura'

nno        <Tab> :echo vimtex#syntax#in_mathzone()<cr>
ino <expr> <Tab> "\<C-r>=vimtex#syntax#in_mathzone()<cr>"
```

**Comment by lervag** [comment]
And, again, to be clear: In this case, you don't need any `after/syntax/markdown.vim` or similar. You can remove that file.

**Comment by lervag** [comment]
Notice that this is also documented [here](https://github.com/preservim/vim-markdown/blob/master/README.md#latex-math).

**Comment by lervag** [comment]
No problem! And thanks for the suggested configuration that removes the dependency for the 3rd party markdown plugin. It may come in handy!
