### ISSUE TITLE
Special context support request

### ISSUE THREAD

**Issue by pilgrimlyieu** [lervag/vimtex#2397]
Is there any way to distinguish inline_math `$...$`, display_math `$$...$$` and chemical_environment `\ce{...}`?

**Comment by lervag** [comment]
Can you explain in more detail what you want to achieve?

The answer is "not entirely". You can use the syntax regions. E.g.

```vim
" Matches in $ inline math $
echo vimtex#syntax#in('texMathZoneX$')

" Matches in $$ display math $$
echo vimtex#syntax#in('texMathZoneXX')
```

There is no good highlighting of the `mhchem` package, so in this case you would need to use something else, like:

```vim
echo get(vimtex#cmd#get_current(), 'name', 'N/A') ==# 'ce'
```

**Comment by pilgrimlyieu** [comment]
Works Wonderfully! Extremely appreciate your effort!

> ```viml
> echo get(vimtex#cmd#get_current(), 'name', 'N/A') ==# 'ce'
> ```

But this I think may be

```viml
echo get(vimtex#cmd#get_current(), 'name', 'N/A') ==# '\ce'
```

**Comment by lervag** [comment]
Great, glad to hear it - and the kind words! :)

**Comment by pilgrimlyieu** [comment]
A further question. How to distinguish `\(...\)` and `\[...\]`? The doc shows that `texMathZone` can't do that.

```txt
  texMathZone              Special        \( HERE \); \[ HERE \]
```

**Comment by pilgrimlyieu** [comment]
> A further question. How to distinguish `\(...\)` and `\[...\]`? The doc shows that `texMathZone` can't do that.
> 
> ```
>   texMathZone              Special        \( HERE \); \[ HERE \]
> ```

Maybe is this? I find it through `vimtex#syntax#stack()`. However the doc doesn't mention it.

```vim
" Matches in $ inline math $
echo vimtex#syntax#in('texMathZoneX')

" Matches in $$ display math $$
echo vimtex#syntax#in('texMathZoneY')

" Matches in \( inline math \(
echo vimtex#syntax#in('texMathZoneV')

" Matches in \] display math \]
echo vimtex#syntax#in('texMathZoneW')
```

**Comment by lervag** [comment]
VimTeX does not provide the groups `texMathZone(Y|V|W)`, sorry. Right now, you can only distunguish like this:

```vim
" Matches in $ inline math $
echo vimtex#syntax#in('texMathZoneX$')

" Matches in $$ display math $$
echo vimtex#syntax#in('texMathZoneXX')

" Matches in \( inline math \)
"        and \[ display math \]
echo vimtex#syntax#in('texMathZone$')
```

**Comment by lervag** [comment]
I think it may actually be worth a discussion if we should rename these groups to allow to distinguish them. If you think so, then feel free to open a new issue about it.

**Comment by pilgrimlyieu** [comment]
> VimTeX does not provide the groups `texMathZone(Y|V|W)`

But why can `vimtex#syntax#in('texMathZone(V|W|Y)')` can work normally? And `vimtex#syntax#stack()` command can show these groups though I don't know the function of this command.

**Comment by lervag** [comment]
If you use the built-in syntax scripts, then these syntax regions will exist. So, if they exist, it seems you may not use VimTeX's syntax script. If you want to go more in depth on this, please open a new issue and provide the standard details.
