### ISSUE TITLE
Configure ts$ to not remove newlines when going from \[...\] to $...$?

### ISSUE THREAD

**Issue by jpreiss** [lervag/vimtex#2409]
Thank you for making this plugin, it is an essential part of my workflow ✨

I often put inline math on a newline so it stands out in the code and is more easily manipulated using line-centric Vim commands. E.g. I often have code like

```tex
let
$\mathbb{N} = 1, 2, \dots$
denote the set of natural numbers.
```

Now suppose my code looks like this:
```tex
let
\[
    \mathbb{N} = 1, 2, \dots
\]
denote the set of natural numbers.
```

If I execute the wonderful new `ts$` command twice inside the `\[ ... \]` delimiters, I will get

```tex
let $\mathbb{N} = 1, 2, \dots$ denote the set of natural numbers.
```

Is there any way to configure `ts$` so it will yield the result from my first code block instead?

Apologies if this has already been covered; I couldn't find it in other issues or docs.

**Comment by lervag** [comment]
> Thank you for making this plugin, it is an essential part of my workflow

Glad to hear it!

> Now suppose my code looks like this:
> 
> ```
> let
> \[
>     \mathbb{N} = 1, 2, \dots
> \]
> denote the set of natural numbers.
> ```
> 
> If I execute the wonderful new `ts$` command twice inside the `\[ ... \]` delimiters, I will get
> 
> ```
> let $\mathbb{N} = 1, 2, \dots$ denote the set of natural numbers.
> ```
> 
> Is there any way to configure `ts$` so it will yield the result from my first code block instead?

Sorry, no. I guess we _could_ consider to add an option. If so, it would be useful to understand how it should work. Let's say we add an option `g:vimtex_toggle_math_inline_separate` (we probably want a better name!). If it is undefined or false, we keep the current behaviour. If it is true, then your request is the following behaviour:

```tex
let
\[
    \mathbb{N} = 1, 2, \dots
\]
denote the set of natural numbers.

% toggle

let
\begin{equation}
    \mathbb{N} = 1, 2, \dots
\end{equation}
denote the set of natural numbers.

% toggle

let
$\mathbb{N} = 1, 2, \dots$
denote the set of natural numbers.

% toggle

let
\[
    \mathbb{N} = 1, 2, \dots
\]
denote the set of natural numbers.
```

I guess we also want the current behaviour in this case:

```tex
let $\mathbb{N} = 1, 2, \dots$ denote the set of natural numbers.

% toggle

let
\[
    \mathbb{N} = 1, 2, \dots
\]
denote the set of natural numbers.
```

So, essentially, the option implies that we do not remove the newlines just before and/or just after the `\[ ... \]` or `\begin{equation} ... \end{equation}` when we go to the inline variant `$ ... $`.

I would be happy if you could try and think of a better name for the option. We also need a good description of this behaviour for the docs.
