### ISSUE TITLE
Issue after remove vimtex

### ISSUE THREAD

**Issue by ywpkwon** [lervag/vimtex#2413]
### Description

I was using `texlab` and I tried to use `vimtex` by
````
     Plug 'lervag/vimtex'
````
After removing this (also after `:PlugClean`), whenever I open `.tex` files, I face a message
````
Plugin vimtex not loaded, make sure it's loaded loaded on filetype: latex                                                                                                                    
(1)Exclude latex in user configuration:
````
the files' filetype has been always `tex`. (before trying and after removing `vimtex`)

I'm guessing somehow `vimtex` initiate to care `latex` filetype and after removal, vim lost how to handle the filetype. How can I properly revert this and remove the message?

Please help!

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
This issue happened after the removal of `vimtex` so there is no `:VimtexInfo` command.
```

**Comment by lervag** [comment]
VimTeX does not do anything strange here, so this problem is most likely a problem with your configuration. The error message is not given by VimTeX.

**Comment by lervag** [comment]
No problem. :)
