### ISSUE TITLE
Cannot use `:help vimtex`

### ISSUE THREAD

**Issue by corei8** [lervag/vimtex#2416]
### Description

When trying to us the `:help` command in neovim, I get the error `E149: Sorry, no help for vimtex`.

What is odd, is that I am able use use pdflatex via vimtex, and configure the plugin to use Skim. However, I need to use lualatex, and cannot get the plugin to use it and, as the title states, I cannot bring up the help pages. If I remember correctly, I was able to bring up the pages at one point -- maybe there was an update that has broken this functionality? I am able to use `:help` for other plugins.

Here is my configuration for vimtex:

```lua
-- VimTeX configuration
vim.g.vimtex_view_method = "skim" -- working
-- end of configuration
```

If it makes a difference, I am on MacOS Monterey 12.4.

### Steps to reproduce

1. Install vimtex via Packer:

```lua
use({
    "lervag/vimtex",
    ft = "tex",
})
```
2. Enter the command `:help vimtex`

### Expected behavior

I expect to get to the help page for vimtex.

### Actual behavior

Instead, I get the error: `E149: Sorry, no help for vimtex`.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
`E492: Not an editor command: VimtexInfo`
```

**Comment by lervag** [comment]
> Install vimtex via Packer:
> 
> ```lua
> use({
>     "lervag/vimtex",
>     ft = "tex",
> })
> ```

Don't use lazy loading. Install with simply this:

```lua
use({ "lervag/vimtex" })
```

**Comment by ejmastnak** [comment]
Haha, @lervag  beat me to it. 

In case it is useful, @corei8, VimTeX is a well-written filetype plugin and will, by design, exit immediately for non-LaTeX files. I'm guessing (correct me if I'm wrong) that you are trying to make VimTeX only load for files with the `tex` filetype.
When I just started using Vim I remember trying to do the same thing, thinking I was "bloatedly" loading VimTeX for every file type. But it turns out that's not the case.

**Comment by lervag** [comment]
> Haha, @lervag beat me to it.

:)

> In case it is useful, @corei8, VimTeX is a well-written filetype plugin

<3

> and will, by design, exit immediately for non-LaTeX files.

Yes, but not exactly. VimTeX uses the autoload feature for lazy loading. A few things, such as help files and a few special commands are loaded globally (because this makes sense!). Everything else is avoided unless necessary. See also `:help autoload`.
