### ISSUE TITLE
Set filetype for TOC window

### ISSUE THREAD

**Issue by lambtho12** [lervag/vimtex#2418]
**Is your feature request related to a problem? Please describe it.**
The current TOC window has no filetype. Defining a filetype for would allow other plugins to detect it and act accordingly.
In specific, the [akinsho/bufferline plugin](https://github.com/akinsho/bufferline.nvim#sidebar-offset-1) can offset the bufferline (tagline) for vertical windows such as a treeview, etc. This offset works by detecting the filetype of the opened window.

**Describe the solution you'd like**
Set `filetype=vimtex-toc` or something like that for this window by default. I don't think this would cause any issue, especially considering that no filetype is currently set.

**Comment by lambtho12** [comment]
Awesome! It works as expected.
Thank you very much for your quick response and for this amazing plugin!

**Comment by lervag** [comment]
Great! Thanks for the kind words :)
