### ISSUE TITLE
i$, a$, ae, ie, id, ad not working?

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#242]
I have been testing all of the vimtex default commands and it seems that ``i*`` and ``a*`` are not working (the asterisk is a wild card). For example, pressing ``i$`` places me in insert mode and then inserts a dollar sign. This makes sense. Similarly, pressing ``ad`` place me in append mode and then appends a ``d``. I looked through ``:help vimtex`` to see if I was using the command improperly. It doesn't seem so. Maybe these commands are intended to do exactly what I have experienced them to do. But, this doesn't seem right.

I am running on Windows 8.1 with Vim in command prompt. My ``_vimrc`` file is given below:
```
set nocompatible
let &rtp = 'C:\Users\John Rinehart\.vim\bundle\vimtex,' . &rtp
filetype plugin indent on
syntax enable

let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options ='-forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk='reuse-instance'
```

**Comment by lervag** [comment]
`i$`, `a$`, and all the similar `ix` and `ax` commands are actually not commands, but text objects. They are used as targets for other commands. An example is `ci$` to delete everything inside two matching `$` and then go to insert mode. Similarly, `dae` can be used to delete an environment (`\begin|\end` pair).

**Comment by lervag** [comment]
You should read `:h text-objects`.

**Comment by fuzzybear3965** [comment]
I had read a good portion of the Vim documentation ~1 year ago and had learned about "text objects". I forgot that they were called that and I do see that you describe ``<plug>(vimtex-i$)`` and the like as text objects. It's clear. Thank you.

**Comment by lervag** [comment]
No problem! Text objects are essential to a good vim experience, IMHO. You should make sure to learn how to use them :)

**Comment by fuzzybear3965** [comment]
Oh, I do use them! ci(, ci{, cw and ci" are incredibly useful.

**Comment by lervag** [comment]
Ah, great!

**Comment by aureooms** [comment]
It is not clear at all that those are not commands but text objects. At least for newbies like myself. Should be put in the wiki?

**Comment by lervag** [comment]
I've never actually edited or updated the wiki myself (as I can recall). I notice the someone actually has added some info to the wiki, which seems neat. However, everything should be documented in the docs. See `:h vimtex-i$`, for instance, which says:  "Text object for inline math (exclusive)." If that is not clear, then ...

**Comment by aureooms** [comment]
Yes the docs are complete :).
