### ISSUE TITLE
[documentation] exrc is deprecated in neovim

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2422]
### Description

Regarding project-local config files, the documentation currently says:
>This is supported in Vim and neovim already, see 'exrc'  and 'secure'. 

neovim had [deprecated `:exrc`](https://neovim.io/doc/user/deprecated.html) a while ago.

Can you also add  the following project-local config plugins to the list in the documentation?

- https://klen/nvim-config-local
- https://github.com/jenterkin/vim-autosource 
- https://github.com/ii14/exrc.vim 

The first one is neovim only (written in lua), while the other two work in both vim & neovim (written in vimscript).

### Do you use a latexmkrc file?

Not relevant

### VimtexInfo

```yaml
Not relevant for every documentation-related issue?
```

**Comment by lervag** [comment]
Thanks!

**Comment by krishnakumarg1984** [comment]
@lervag After months of experimenting, we finally have a decent project local plugin: https://github.com/MunifTanjim/exrc.nvim 

This has solved all other buggy implementations e.g. [this one](https://github.com/klen/nvim-config-local/issues/6#issuecomment-1226109426).

**Comment by lervag** [comment]
Cool; would you like to propose an update to the docs?

**Comment by krishnakumarg1984** [comment]
@lervag After months of experimenting, we finally have a decent project local plugin: https://github.com/MunifTanjim/exrc.nvim 

This has solved all other buggy implementations e.g. [this one](https://github.com/klen/nvim-config-local/issues/6#issuecomment-1226109426).

**Comment by lervag** [comment]
@krishnakumarg1984 You posted a duplicate comment; I deleted it. Perhaps you intended to write something else?
