### ISSUE TITLE
vimtex not loading quickfix window

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#243]
I have noticed that vimtex does not not open the quickfix window for documents that fail to compile when manually executing ``mklatex`` from the command line. Both warnings and errors fail to deliver the quickfix window to my Vim instance. I have checked the following:

``:echo g:vimtex_latexmk_continuous`` and ``:echo g:vimtex_latexmk_callback`` both return 1.

I am running on Windows 8.1 with Vim running in the command line. My ``_vimrc`` file is as follows:
```
set nocompatible
let &rtp = 'C:\Users\John Rinehart\.vim\bundle\vimtex,' . &rtp
filetype plugin indent on
syntax enable

let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options ='-forward-search @tex @line @pdf'
```

**Comment by lervag** [comment]
I don't quite understand: If you manually evoke `latexmk` from the command line, then it does not know about vimtex, and so it could not know how to open the quickfix window. The vimrc file have no effect in this case.

What does have an effect, though, is the `.latexmkrc` (or `_latexmkrc`, perhaps, on windows?). You can add settings similar to the below:

```perl
$success_cmd = "gvim --remote-expr 'latex#latexmk#callback(1)'";
$failure_cmd = "gvim --remote-expr 'latex#latexmk#callback(0)'";
```

Note, though, that this will assume a servername equal to `GVIM` or `GVIM1` or something like that, which means it might fail if you have multiple gvim instances running. Further, the above might need some tuning to work on windows.

**Comment by fuzzybear3965** [comment]
I wasn't being clear enough. I was trying to compile the documents first in vimtex. I intentionally inserted LaTeX mistakes into the .tex file (I didn't terminate an align environment and I used subscripts outside of math mode, etc. ). vimtex never failed to compile.The text would always compile in vimtex. So, I went to the command line to see if errors/warnings were being generated by mklatex. They were. In my original post, I only included my ``_vimrc`` file for completeness so that you could know the testing conditions.

I have ran ``latexmk -r .latexmkrc test.tex`` and have started a single instance of vim using the following ``vim --servername gvim``. Although I see the warnings that latexmk generates on the command line I don't see any quickfix window being opened in the separate Vim instance when I go back to check on it.

The following is the ``.latexmkrc`` I'm using:

```
$success_cmd = "gvim --remote-expr 'latex#latexmk#callback(1)'";
$failure_cmd = "gvim --remote-expr 'latex#latexmk#callback(0)'";
```

Note that latexmk didn't seem to have a problem with the escaping of the quotation marks (it didn't complain about them). But, it didn't seem to execute these commands either.

I also tried the following command on the command line (I had to play with the quotes for a bit). It didn't do anything in Vim.

```
latexmk -e "$success_cmd = 'gvim --remote-expr \"latex#latexmk#callback(1)\"'" -e "$failure_cmd = 'gvim --remote-expr \"latex#latexmk#callback(0)\"'" test.tex
```
The following is the reported output after compilation (using both ``-r`` and ``-e`` methods):

```
Latexmk: This is Latexmk, John Collins, 5 February 2015, version: 4.43a.
Latexmk: applying rule 'latex'...
Rule 'latex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'test.aux'
------------
Run number 1 of rule 'latex'
------------
------------
Running 'latex  -recorder  "test.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9)
entering extended mode
(test.tex
LaTeX2e <2015/01/01> patch level 2
Babel <3.9m> and hyphenation patterns for 69 languages loaded.
(C:\Miktex\tex\latex\base\article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(C:\Miktex\tex\latex\base\size10.clo)) (test.aux)
! Missing $ inserted.
<inserted text>
                $
l.3 ABC CDEF e^
               {i\theta} = 1
?

! LaTeX Error: Environment align undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.6 \begin{align}

?
! Missing $ inserted.
<inserted text>
                $
l.8 \end{document}

?
! Missing \endgroup inserted.
<inserted text>
                \endgroup
l.8 \end{document}

?
[1] (test.aux) )
Output written on test.dvi (1 page, 368 bytes).
Transcript written on test.log.
Latexmk: Log file says output to 'test.dvi'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  latex: Command for 'latex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
```
The following is the LaTeX files I'm trying to compile:
```
\documentclass{article}
\begin{document}
ABC CDEF e^{i\theta} = 1 
\log(\theta) = 1 test
abc
\begin{align}
	abc
\end{document}
```

**Comment by lervag** [comment]
Ok, thanks for the explanation.

First, could you try again on the command line, but add these lines to `.latexmkrc`:

    $print_type = 'pdf';
    $pdf_mode = 1;
    $pdflatex = 'pdflatex -interaction=nonstopmode --shell-escape %O %S';

This should ensure you are compiling with `pdflatex` to `pdf` format.

Next, could you from the command line start `vim --servername gvim` (as you already did). Then again from the command line do: `gvim --remote-send ":echom 'tested'<cr>"`. I think this should work, and it should simply echo "tested" in the first vim instance.

Finally, you can try again the `latexmk` command on the command line that failed. But I want you to ensure that you have loaded vimtex in the remote vim instance. I also want you to ensure that a remote command as used above works as expected. Please let me know what you find out.

**Comment by fuzzybear3965** [comment]
The echo worked just fine. The remote instance seems to have loaded vimtex in that ``:help vimtex`` loads the documentation. However, none of the vimtex commands are available (``VimtexCompile``,``VimtexStatus``, etc.). I assume that's because there is no LaTeX file being edited in the remote instance - it's blank (Vim uses the filetype to load the proper plugins??).

I have added those lines to my ``.latexmkrc`` file. It now looks like
```
$success_cmd = "gvim --remote-expr 'latex#latexmk#callback(1)'";
$failure_cmd = "gvim --remote-expr 'latex#latexmk#callback(0)'";
$print_type = 'pdf';
$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode --shell-escape %O %S';
```

I have executed the following command on the command line to the same LaTeX file I supplied in the earlier post: ``latexmk -r ../.latexmkrc test.tex``. I obtain the following output (a .PDF is generated in the working directory):

```
Latexmk: This is Latexmk, John Collins, 5 February 2015, version: 4.43a.
Latexmk: applying rule 'pdflatex'...
Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex
Rule 'pdflatex': The following rules & subrules became out-of-date:
      'pdflatex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex -interaction=nonstopmode --shell-escape  -recorder  "test.tex"'
------------
This is pdfTeX, Version 3.14159265-2.6-1.40.16 (MiKTeX 2.9)
entering extended mode
(test.tex
LaTeX2e <2015/01/01> patch level 2
Babel <3.9m> and hyphenation patterns for 69 languages loaded.
(C:\Miktex\tex\latex\base\article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(C:\Miktex\tex\latex\base\size10.clo)) (test.aux)
! Missing $ inserted.
<inserted text>
                $
l.3 ABC CDEF e^
               {i\theta} = 1

! LaTeX Error: Environment align undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.6 \begin{align}

! Missing $ inserted.
<inserted text>
                $
l.8 \end{document}

! Missing \endgroup inserted.
<inserted text>
                \endgroup
l.8 \end{document}

[1{C:/Users/John Rinehart/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}]
(test.aux) )
(see the transcript file for additional information)<C:/Miktex/fonts/type1/publ
ic/amsfonts/cm/cmmi10.pfb><C:/Miktex/fonts/type1/public/amsfonts/cm/cmmi7.pfb><
C:/Miktex/fonts/type1/public/amsfonts/cm/cmr10.pfb>
Output written on test.pdf (1 page, 30084 bytes).
Transcript written on test.log.
Latexmk: Log file says output to 'test.pdf'
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs of latex/pdflatex.
```

There are no messages/anything in the remote vim instance.

**Comment by fuzzybear3965** [comment]
Okay, Karl, I've changed things. I was using the Cream release of Vim. Now, I'm using the version released officially on ``vim.org``. The quickfix window now loads properly!

I don't know what the problem was and I hate fixing it in this way. But, it's a good solution in that I should be using the official version of Vim and vimtex works just fine with the official release.

**Comment by fuzzybear3965** [comment]
I also want to note that I'm using Strawberry Perl (I noticed that the Perl distributed with Git Bash, which was all I had originally, wasn't working).

**Comment by lervag** [comment]
First, I'm glad to hear things are working!

I do not immediately remember if there are parts of the relevant code that requires a specific version of Vim. If I remember correctly, you are a Windows user. I am personally not a very advanced Windows user myself, and I have never tried anything but the official Vim build on Windows. I have never installed Perl, I've just installed latexmk through the MikTeX package manager. So, I do not know what might have been wrong. :\
