### ISSUE TITLE
package detection does not find fls find if in out_dir

### ISSUE THREAD

**Issue by belamu** [lervag/vimtex#2435]
I use the option `$out_dir` in my `.latexmkrc` file to avoid cluttering of my tex-file directory with temporary files.
This means that the `mainfile.fls` file is in this `$out_dir`, not next to `mainfile.tex`. Hence `vimtex` does not find it and the package support (in my case spellchecking disabling in `autocite` via `biblatex`) is not enabled.

My current workaround (working) is to create a symlink in my tex directory to the fls file in the `out_dir`. Conceptually this symlink is misplaced there and therefore I would prefer it if vimtex is also finding the fls file in the `out_dir`.

I am not sure what would happen if I didn't use `out_dir` but a `jobname` that is different from `mainfile`.

**Comment by belamu** [comment]
Yes, it does work. Thank you for the quick solution! Since parsing a `.latexmkrc` file sounds a lot more work than a setting for vimtex, I close the issue and hope that other people with the same problem will find the solution.

Since that's a project-wide setting, not global, I use the [vim-local](https://github.com/flatcap/vim-local) plug-in that allows to have a project-wide vim settings file in the top-level project directory. Since also other settings files are there, I prefer this place for the setting.

**Comment by lervag** [comment]
Good to hear the option works. But I did expect the `.latexmkrc` approach to work as well. And, on my end, it does. I've tested with this minimal example:

Test directory contains these files:

```
.
├── .latexmkrc
├── test.tex
└── test.vim
```

```tex
% test.tex
\documentclass{minimal}
\usepackage{mathtools}
\begin{document}

Hello World!

\end{document}
```

```perl
# .latexmkrc
$out_dir = "out";
```

```vim
" test.vim
set nocompatible
set runtimepath^=~/.local/plugged/vimtex
set runtimepath+=~/.local/plugged/vimtex/after
filetype plugin indent on
syntax enable

silent edit test.tex
```

I do:

1. `nvim --clean -u test.vim`
2. `\li` - confirm that the packages line only contains `mathtools`
3. `\ll` - compile document
4. `\li` again - now notice that the packages line is filled with content parsed from the `.fls` file in the out directory.

So, could you explain how your original setup differs from the above example?

**Comment by belamu** [comment]
On first sight based on some experimenting with the given option, my guess is that I didn't compile with `\ll` but had compiled with `latexmk -pvc` outside of vim and expected vimtex to pick up the fls file. After compiling with `\ll` I believe the biblatex package was found.
I will later today try it out again with a/your minimal example and report back.

Sidenote:
> Using `latexmk` in a different terminal window is a practise of mine for a while now. I think, one motivation was to avoid the warning/error window. And after choosing some error I was jumping to a different file without knowing how to come back to the file I was just editing except for closing and opening vim.

**Comment by belamu** [comment]
> You can use <c-o> to jump back. You may also be interested in :help g:vimtex_quickfix_autojump.
That's very helpful. (For vim-Newbies like me: <c-o> means Ctrl + o.)
I don't use this autojump option now since I use continous compilation but 
`let g:vimtex_quickfix_autoclose_after_keystrokes = 5`
(Then it's not in my way if I don't care about errors right now and I just have to continue working without any special action.) and
`let g:vimtex_quickfix_open_on_warning = 0`

**Comment by belamu** [comment]
Your minimal example works the same way for me.
