### ISSUE TITLE
how to turn off the shadow around the concealled charaters

### ISSUE THREAD

**Issue by thudjx** [lervag/vimtex#2438]
### Description

I have `set conceallevel=2`, but the concealled charaters have shadow aroud them which makes them bare to see.

### Steps to reproduce

I use [darkplus](https://github.com/martinsione/darkplus.nvim) colortheme and default highlighting of `VimTeX`. The effects on characters before and after concealing is:
![image](https://user-images.githubusercontent.com/32637321/178995584-2c25b0c7-fbee-4888-8f1a-0e5c3e9e7c74.png)
![image](https://user-images.githubusercontent.com/32637321/178995662-13ef92e6-b818-4348-939b-2e278d359c4d.png)
I think it would be great to turn the shadow off or reset the transparency of it.

**Comment by lervag** [comment]
This is due to the highlight rules you have. See `:help conceallevel`:

```
						*'conceallevel'* *'cole'*
'conceallevel' 'cole'	number (default 0)
			local to window
	Determine how text with the "conceal" syntax attribute |:syn-conceal|
	is shown:

	Value		Effect ~
	0		Text is shown normally
	1		Each block of concealed text is replaced with one
			character.  If the syntax item does not have a custom
			replacement character defined (see |:syn-cchar|) the
			character defined in 'listchars' is used.
			It is highlighted with the "Conceal" highlight group.
	2		Concealed text is completely hidden unless it has a
			custom replacement character defined (see
			|:syn-cchar|).
	3		Concealed text is completely hidden.

	Note: in the cursor line concealed text is not hidden, so that you can
	edit and copy the text.  This can be changed with the 'concealcursor'
	option.
```

Notice: "It is highlighted with the "Conceal" highlight group. Concealed text is completely hidden unless it has a custom replacement character defined (see |:syn-cchar|)."

So, clearly, the darkplus colorscheme does not have a properly defined `Conceal` highlight group.

**Comment by thudjx** [comment]
So how to define this `Conceal` highlight group? Or maybe you have some recommended colorthemes? It would be great if they are dark style.

**Comment by lervag** [comment]
You can define it yourself. See [this Gist](https://gist.github.com/romainl/379904f91fa40533175dfaec4c833f2f) for a nice explanation of how to customize colorschemes.

**Comment by thudjx** [comment]
Thank you so much! It is indeed better to set my own colorshemes. And the link is just helpful.

**Comment by lervag** [comment]
Glad to hear it helps :)
