### ISSUE TITLE
Have `vimtex.root` be the `master.tex` that's found in the root directory in a git folder

### ISSUE THREAD

**Issue by SingularisArt** [lervag/vimtex#2442]
Here's my current folder setup:

```
.
├── 2022
│   ├── 07
│   │   ├── 01
│   │   │   └── note.tex
│   │   ├── ...
│   │   │   └── ...
│   │   └── goals.tex
│   └── goals.tex
├── master.pdf
├── .git
├── .gitignore
└── master.tex
```

But when I'm in `2022/07/01/note.tex` and I echo the `vimtex.root`, the output is `2022/07/20`.
Is it possible if you can make vimtex keep going back until it finds a `.git` folder, and if it doesn't find one, it can use the current folder that you're in?

**Comment by lervag** [comment]
Sorry, but I think you've gotten some things backwards. The `.git` root should never be relevant for a LaTeX projects root directory. Multifile LaTeX projects will need some type of structure that VimTeX will often parse automatically. In some cases, parsing this structure is hard, and so there are a few options to manually specify the master file. Please read `:help vimtex-multi-file`.

If you still have issues after reading this, then please, open a new issue with a (SMALL) concrete example that does not work as expected for you. Be specific about which your VimTeX configuration and system as well. Essentially, please adhere to the issue template.
