### ISSUE TITLE
how to customize the citation completion terms

### ISSUE THREAD

**Issue by thudjx** [lervag/vimtex#2444]
The citation completion of `vimtex` is just amazing!
But I am wondering is it possible to show the authors and titles before the citation keys, so that the title can be shown more in the screen:
![image](https://user-images.githubusercontent.com/32637321/180914104-a0839a64-1a3b-4a3d-a105-6265271e68b3.png)

**Comment by lervag** [comment]
> The citation completion of `vimtex` is just amazing!

Glad you like it! :)

> But I am wondering is it possible to show the authors and titles before the citation keys, so that the title can be shown more in the screen:

Not quite sure exactly what you ask for, but you can change the formatting with
the option `:help g:vimtex_complete_bib` with the `menu_fmt` key and/or
`abbr_fmt` key. An example where the author and year is removed:

```vim
let g:vimtex_complete_bib = {
      \ 'menu_fmt': '[@type] @title',
      \}
```

**Comment by thudjx** [comment]
Well, I want to turn off the keys in the menu, which I think are not so informative and shorten the titles shown in the menu, which you can see from the picture above.
I have read the part of the documentation you mensioned(sorry I didn't RTFM), but didn't find the option I want. So is it possible to achieve what I want? If not, is it possible to show terms in the menu in multi-lines so that the titles are shown completely?

**Comment by lervag** [comment]
> Well, I want to turn off the keys in the menu, which I think are not so informative and shorten the titles shown in the menu, which you can see from the picture above.

Sorry, but you are not really specifying what you want accurately enough for me to fully understand. But, I think I am close. Perhaps something like this will be closer to what you want:

```vim
let g:vimtex_complete_bib = {
      \ 'menu_fmt': '[@type] @title',
      \ 'abbr_fmt': '@author_short (@year)',
      \}
```

Notice that you may have to clear cache after changing this option. So, if you don't see the changes after changing the option, run `:VimtexClearCache ALL` and restart.

> If not, is it possible to show terms in the menu in multi-lines so that the titles are shown completely?

No, this is not possible, sorry.

Feel free to show by explicit example what you want; i.e. write out 3-4 rows of the completion menu how you would want it to appear.

**Comment by thudjx** [comment]
Sorry for my vague description, but I think the picture below might make me clear:
![example](https://user-images.githubusercontent.com/32637321/181228901-4084043b-9ecd-4a0b-a1aa-d9b8cd7f91fa.png)
which is what is shown after I type `\cite{Bistritzer<C-x><C-o>` to trigger the citation completion menu. What the `menu_fmt` controls is the second part which I labeled as "menu keys", but what I want to do is to remove the "citation keys" which is not informative but occupying the valueable place to show the menu.

**Comment by lervag** [comment]
Ok. I think you can get what you want with something like this:

```vim
let g:vimtex_complete_bib = {
      \ 'menu_fmt': '',
      \ 'abbr_fmt': '[@type] @title',
      \}
```

You can experiment with these settings yourself. While you experiment, it may be useful to also add `let g:vimtex_cache_persistent = 0` to disable the cache files. Then you don't need to clean the cache after changing the options. When you are satisfied, you should remove this option and do `:VimtexClearCache ALL` to ensure that you have cleaned the cache files.

**Comment by lervag** [comment]
Notice that you can use the `menu_fmt` and `abbr_fmt` to add some alignement, e.g.:

```vim
let g:vimtex_complete_bib = {
      \ 'menu_fmt': '@title',
      \ 'abbr_fmt': '@author_short (@year)',
      \}
```

**Comment by thudjx** [comment]
Wow, thanks so much! The menu format is just satisfying for me now!

**Comment by lervag** [comment]
Glad to hear it!
