### ISSUE TITLE
Is there any way to use `tsd` to toggle delimiters in insert mode?

### ISSUE THREAD

**Issue by pilgrimlyieu** [lervag/vimtex#2445]
**Is your feature request related to a problem? Please describe it.**

`<plug>(vimtex-delim-toggle-modifier)` is useful. However, it will be better if I can toggle it as soon as I insert delimiters in insert mode.

**Describe the solution you'd like**

Support using `<plug>(vimtex-delim-toggle-modifier)` or any other way to enable a key mapping for insert mode.

Thanks!

**Comment by lervag** [comment]
I've pushed a minor fix just now. With this, you can create that map yourself. The following example should work:

```vim
imap <f7> <esc><plug>(vimtex-delim-toggle-modifier)a
```

I would add this in one of two ways:

1. Add it to your personal `ftplugin/tex.vim`. This is what I recommend.
2. Alternatively, add the mapping in your vimrc or init.vim file under an autocommand, something like this:

    ```vim
    augroup vimrc
      autocmd!
      autocmd FileType tex imap <f7> <esc><plug>(vimtex-delim-toggle-modifier)a
    augroup END
    ```

This way, you only apply the mapping when VimTeX is loaded.

**Comment by pilgrimlyieu** [comment]
That works.

However, it will change the position of the cursor. Here is an example.

```vim
imap <f7> <esc><plug>(vimtex-delim-toggle-modifier)a
```

```tex
$$
(aaa)<cursor>
$$
```

Then press <kbd>F7</kbd>.

```tex
$$
\left(aaa\right)<cursor>
$$
```

Press again.

```tex
$$
(<cursor>aaa)
$$
```

**Comment by lervag** [comment]
Sorry, there was a minor error in the positioning calculation. I've fixed it now, please test again.

**Comment by pilgrimlyieu** [comment]
> Sorry, there was a minor error in the positioning calculation. I've fixed it now, please test again.

That works. But still has a minor issue.

```tex
$$
\{aaa\}<cursor>
$$
```

Then press <kbd>F7</kbd>.

```tex
$$
\left\{aaa\right\<cursor>}
$$
```

Press again.

```tex
$$
\{aaa\<cursor>}
$$
```

**Comment by lervag** [comment]
Thanks; nice edge case. I'll fix it as soon as I get the time!

**Comment by lervag** [comment]
I believe this should be fixed now, please test.

**Comment by pilgrimlyieu** [comment]
> ```viml
> imap <f7> <esc><plug>(vimtex-delim-toggle-modifier)a
> ```

Thanks! Works now.

**Comment by lervag** [comment]
Great, glad to hear it!
