### ISSUE TITLE
change surrounding command confused in footnotes

### ISSUE THREAD

**Issue by thomasahle** [lervag/vimtex#245]
If I place my cursor on `for` in the following:

    \footnote{We use $\oplus$ for concattenation}

And write `csc`, I get the option of changing `oplus` into something else.

I would prefer to get the option of changing `footnote`, as I don't really consider myself being 'inside' the `oplus`.

**Comment by Konfekt** [comment]
Confirmed, that behavior of `csc` is inconsistent with that of of `dsc` that deletes `\footnote{...}`

**Comment by Konfekt** [comment]
The 
```vim
normal! F\lcea
```
command is too simplistic.

**Comment by Konfekt** [comment]
So how about `normal! F{F\lcea`?

**Comment by Konfekt** [comment]
Better `vaB<esc>` instead of F{ as this skips escaped braces, as does dsc.

**Comment by lervag** [comment]
I've pushed a fix to this. I updated both `csc` and `dsc` so they should both be more general.

I think there might be a problem with `dsc` in some cases. It would be nice to get a report whether you agree, or to hear if it works as expected.

**Comment by Konfekt** [comment]
Hello, 


True that the previous commands worked fine but very invasive, as jump list and previous visual selection were overridden.

Here `dsc` halts the computer. Supposedly the culprit is the additional `while getline('.')[l:col-1 :] =~# '^\s*{'` loop at https://github.com/lervag/vimtex/commit/c45f9b4f94a0bba992ba5c8ba7a133f93cf13ff4#diff-69d39002f65b6ef8058c06e787b5a9d7R139  

Why ought `dsc` to delete all surrounding braces? Also `normal! f{` could jump to an escaped brace, which `vaB` prevents. Finally where's the part that deleted the command `\...` itself?

**Comment by lervag** [comment]
Good point about jump list and visual selection. I'll work on it later. I just pushed a minor update to remove the loop, I'll work on the other things when I get the time.

**Comment by Konfekt** [comment]
Ok, now `dsc` does not halt the computer anymore, but forgets deleting the braces `{}`.

Regarding the jump list, the `g`` command is meant to leave it intact though.

**Comment by lervag** [comment]
This is an overview of remaining tasks and issues:

[]: Previous visual selection is overridden
[]: Jump list is overriden
[]: Use `vaB` instead of `f{` for improved robustness
[]: Ensure the command `\...` is deleted
[]: Ensure that (possibly) following braces are deleted

**Comment by lervag** [comment]
I think it should work better now. I am trying to find out how to avoid overriding the visual selection. Input on this is appreciated.

**Comment by Konfekt** [comment]
There's a function in UltiSnips that achieves that, however it is in Python:

https://github.com/SirVer/ultisnips/blob/e1e005a810edc7b1c13b5095fe3ab7ce2600b0cb/pythonx/UltiSnips/vim_state.py#L104

But preserving `line("'<")"""),"col("'<")` and `line("'>")"""), "col("'>")` and then using `cursor()` to reselect this area should work?

Or are you looking for something that does not override the visual selection it in the first place? Not sure if there's such a switch.

**Comment by Konfekt** [comment]
For the moment, neither `dsc` nor `csc` has any effect.

**Comment by lervag** [comment]
@Konfekt I think the commands should now work as expected again. I've fixed a couple of minor bugs.

**Comment by lervag** [comment]
And I now believe that everything should work as expected. Please report if you still have problems or issues.

**Comment by Konfekt** [comment]
Somehow, it handles made up commands such as `\help{...}` well  but on common ones, such as `\begin` or `\emph`, it has no effect. This is under the following TeX settings:
```
" make Vim recognize filenames in TeX surrounded by { and }.
set isfname-={,}
let g:tex_isk = '48-57,a-z,A-Z,192-255'.",`,',-,:"
let g:tex_flavor = "latex"
let g:tex_comment_nospell= 1
let g:tex_verbspell= 0
let g:tex_conceal = 'abdgm'
let g:tex_fold_enabled=1
```

**Comment by Konfekt** [comment]
For example on
```
            {\small{test}}
```
there's a missing endif:
```vim
Error detected while processing function vimtex#change#command_delete[2]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command[16]..vimtex#change#get_command:
line   16:
E132: Function call depth is higher than 'maxfuncdepth'
Error detected while processing function vimtex#change#command_delete:
line    2:
E714: List required
line    3:
E121: Undefined variable: l:old
E15: Invalid expression: l:old ==# '' | return | endif
line   43:
E171: Missing :endif
```

**Comment by lervag** [comment]
Thanks! I've fixed it again, but I see that the idea of matching syntax regions might not bee as good as I've hoped. If there are more problems now, then I'll find a different approach. Please let me know if you find other commands where this doesn't work as expected.

**Comment by Konfekt** [comment]
Still, `dsc` on `\emph{ abc }` has no effect (whereas on `\help{ abc }` it works).

**Comment by lervag** [comment]
Strange. For me, `dsc` works fine with `\emph{ abc }`. Perhaps there is another problem. Could you give a full minimal tex file where this happens?

**Comment by Rmano** [comment]
Hmmm... for me, on `\emph{whatever}`, `dsc` or `csc` is doing nothing, and testing from the argument of  `\ref{fig:sthing}` gives the error: 

```
Error detected while processing function vimtex#change#command..vimtex#change#ge
t_command:
line   17:
E117: Unknown function: getcurpos
E15: Invalid expression: getcurpos()
line   20:
E121: Undefined variable: l:curpos
E116: Invalid arguments for function setpos
```

...then it asks for the replacement, I put "lat", and I have `\relatfig:sens}`...

**Comment by Konfekt** [comment]
With `vim -u $XDG_CONFIG_HOME/.vim/viminrc` and `vimrc` being
```vim
set nocompatible
filetype plugin indent on
syntax enable

call plug#begin('~/.vim/plugged')
  Plug 'https://github.com/lervag/vimtex'
call plug#end()
```
and empty `ftplugin` and `plugin` folders, then on
```tex
\documentclass{article}
\begin{document}
  % a
  \emph{ a }
  % b
\end{document}
```
has no effect on `\emph`.

**Comment by Konfekt** [comment]
However, if the line `%a` is deleted by `dd` and then `u`, now `dsc` works.

**Comment by lervag** [comment]
Hi. I'm sorry, it seems I forgot about this issue. I've looked at it again now. It seems this might be related to #272 as @Konfekt says. I've added some test files to the repo:

```vim
" minivimrc
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
filetype plugin indent on
syntax enable
```

```tex
% Minimal tex file
\documentclass{article}
\begin{document}
  % a
  \emph{ a }
  % b
\end{document}
```

I do `vim -u minivimrc main.tex`, go inside the braces and then do `dsc`, which works as expected. Could you please try this with my minimal vimrc file (of course `&rtp` if you have a different plugin directory)?

**Comment by lervag** [comment]
I've reproduced the issue with Vim version 7.4.52. It seems `getcurpos()` was introduced in a later patch.
