### ISSUE TITLE
Enable completion for custom macro

### ISSUE THREAD

**Issue by NiklasKappel** [lervag/vimtex#2451]
Say I define a macro like this:

```
\newcommand{\mySuperGraphic}[1]{
...
\includegraphics{#1}
...
}
```

Then I type (with `|` being the cursor position):

```
\mySuperGraphic{|
```

vimtex does not trigger image file name completion. Would it be possible to tell vimtex that it should trigger specific completion suggestions for the nth argument of a specifically named command, i.e. through a vim option?

**Comment by lervag** [comment]
Sorry, but no, there is no such feature available and I don't plan to implement it. :\
