### ISSUE TITLE
Add default value of ligatures in help

### ISSUE THREAD

**Issue by TheCoolDinosuar** [lervag/vimtex#2452]
In `:h vimtex_syntax_conceal`, the code that shows the default value doesn't show the value of `g:vimtex_syntax_conceal.ligatures`, which is `1`.
This is what it is currently:
```
    let g:vimtex_syntax_conceal = {
          \ 'accents': 1,
          \ 'cites': 1,
          \ 'fancy': 1,
          \ 'greek': 1,
          \ 'math_bounds': 1,
          \ 'math_delimiters': 1,
          \ 'math_fracs': 1,                                                                                                  
          \ 'math_super_sub': 1,
          \ 'math_symbols': 1,
          \ 'sections': 0,
          \ 'styles': 1,
          \}
```

Solution:
In `doc/vimtex.txt` It should be
```
    let g:vimtex_syntax_conceal = {
          \ 'accents': 1,
          \ 'ligatures': 1,
          \ 'cites': 1,
          \ 'fancy': 1,
          \ 'greek': 1,
          \ 'math_bounds': 1,
          \ 'math_delimiters': 1,
          \ 'math_fracs': 1,                                                                                                  
          \ 'math_super_sub': 1,
          \ 'math_symbols': 1,
          \ 'sections': 0,
          \ 'styles': 1,
          \}
```
I'm not sure if opening an issue is the correct way to report such a small issue, or if I should create a pr instead. Thank you for creating this plugin!

**Comment by lervag** [comment]
> In `:h vimtex_syntax_conceal`, the code that shows the default value doesn't show the value of `g:vimtex_syntax_conceal.ligatures`, which is `1`.

Thanks! Nice catch! I've updated now.

> I'm not sure if opening an issue is the correct way to report such a small issue, or if I should create a pr instead. Thank you for creating this plugin!

This was perfect. PR is of course also great, but not necessary for such simple things.

And glad to hear you like the plugin!
