### ISSUE TITLE
VimtexCompile = Not an editor command

### ISSUE THREAD

**Issue by Gako358** [lervag/vimtex#2458]
### Description

I am running nixos, have setup neovim declerative as seen [here](github.com/gako358/nvimFlakes).

When running `:checkhealth`, it returns OK on vimtex, on all 3 accounts.

my vimtex config:

```lua
-----------------------------------------------------------
-- VimTeX Management
-----------------------------------------------------------
vim.g.vimtex_view_general_viewer = 'evince'
vim.g.vimtex_compiler_method = 'latexrun'
vim.g.tex_flavor = 'latex'
```

I am not sure what is missing and why no commands related to Vimtex is working, everything returns, Not an editor command. However `:h Vimtex` works.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
Does not work
```

**Comment by lervag** [comment]
> my vimtex config:
> 
> ```lua
> -----------------------------------------------------------
> -- VimTeX Management
> -----------------------------------------------------------
> vim.g.vimtex_view_general_viewer = 'evince'
> vim.g.vimtex_compiler_method = 'latexrun'
> vim.g.tex_flavor = 'latex'
> ```

`g:tex_flavor` is irrelevant, so you can remove it.

> I am not sure what is missing and why no commands related to Vimtex is working, everything returns, Not an editor command. However `:h Vimtex` works.

I believe the problem lies in how you've installed VimTeX. Can you explain or show your full neovim config?

**Comment by Gako358** [comment]
Ive installed it using nix flake, decleratived. My config is here [nvimFlakes](https://github.com/Gako358/nvimFlakesl)

**Comment by lervag** [comment]
Ehm, ok; sorry, but I don't know Nix and Flakes. But I _do_ know Vim and neovim. What I'm asking is not how you install things on Nix, but how VimTeX is installed in your Vim/neovim config.

If you open a `.tex` file, what's the output of `:scriptnames`?

**Comment by Gako358** [comment]
``
:scriptnames
  1: /nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master/share/nvim/runt
ime/ftplugin.vim
  2: /nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master/share/nvim/runt
ime/indent.vim
  3: /nix/store/1njcqqhyizjjp0la41jpk27ryxgcqz0g-init.vim
  4: /nix/store/h65z5jwb15082hfyjv4k13isyixwf51m-vimplugin-nvim-treesitter-master/autolo
ad/nvim_treesitter.vim
  5: /nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master/share/nvim/runt
ime/syntax/syntax.vim
  6: /nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master/share/nvim/runt
ime/syntax/synload.vim
  7: /nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master/share/nvim/runt
ime/filetype.lua
  8: /nix/store/6q47n0pxhqb382wjpp50il9hlfrfhh3a-vimplugin-luasnip-master/ftdetect/snipp
ets.vim
  9: /nix/store/2y8d3gpiypnpkywqiinn36ph68flip75-vimplugin-vimtex-master/ftdetect/cls.vi
m
 10: /nix/store/2y8d3gpiypnpkywqiinn36ph68flip75-vimplugin-vimtex-master/ftdetect/tex.vi
m
 11: /nix/store/2y8d3gpiypnpkywqiinn36ph68flip75-vimplugin-vimtex-master/ftdetect/tikz.v
im
 12: /nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master/share/nvim/runt
ime/filetype.vim
 13: /nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master/share/nvim/runt
ime/ftplugin/tex.vim
 14: /nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master/share/nvim/runt
ime/ftplugin/plaintex.vim
 15: /nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master/share/nvim/runt
ime/ftplugin/initex.vim
 16: /nix/store/2y8d3gpiypnpkywqiinn36ph68flip75-vimplugin-vimtex-master/ftplugin/tex.vi
m
 17: /nix/store/2y8d3gpiypnpkywqiinn36ph68flip75-vimplugin-vimtex-master/after/ftplugin/
tex.vim
 18: /nix/store/2y8d3gpiypnpkywqiinn36ph68flip75-vimplugin-vimtex-master/autoload/vimtex
/util.vim
 19: /nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master/share/nvim/runt
``

**Comment by lervag** [comment]
Ok; I've "cleaned it up" to make it easier to read:

> ```
>   3: /init.vim
>   9: /vimplugin-vimtex-master/ftdetect/cls.vim
>  10: /vimplugin-vimtex-master/ftdetect/tex.vim
>  11: /vimplugin-vimtex-master/ftdetect/tikz.vim
>  12: /neovim-unwrapped-master/share/nvim/runtime/filetype.vim
>  13: /neovim-unwrapped-master/share/nvim/runtime/ftplugin/tex.vim
>  14: /neovim-unwrapped-master/share/nvim/runtime/ftplugin/plaintex.vim
>  15: /neovim-unwrapped-master/share/nvim/runtime/ftplugin/initex.vim
>  16: /vimplugin-vimtex-master/ftplugin/tex.vim
>  17: /vimplugin-vimtex-master/after/ftplugin/tex.vim
>  18: /vimplugin-vimtex-master/autoload/vimtex/util.vim
>  19: /neovim-unwrapped-master/share/nvim/runtime/indent/tex.vim
>  20: /vimplugin-vimtex-master/indent/tex.vim
>  21: /neovim-unwrapped-master/share/nvim/runtime/syntax/tex.vim
>  22: /vimplugin-vimtex-master/syntax/tex.vim
>  48: /vimplugin-vimtex-master/plugin/vimtex.vim
> ```

Specifically, notice how the built-in plugin is loaded _before_ VimTeX is loaded. That's you're problem. More specifically, the `initex.vim` (index 15) will set `b:did_filetype`, which causes VimTeX to _not_ load due to the guard:

https://github.com/lervag/vimtex/blob/411a22a6b66aba58252f287829118c5533f16a11/ftplugin/tex.vim#L11-L14

Do I understand correctly that you do _not_ use a plugin manager, but instead use Nix for everything? If so, then where/how do you specify the resulting `runtimepath`?

**Comment by Gako358** [comment]
I need to look into what loads first and how to set it up.
Yes using nix for everything, that is the point, have some config inline lua, but that is it.

**Comment by lervag** [comment]
Ok; well, yes - you need to figure out how the `runtimepath` is defined. It is the variable that defines where neovim will search for script files that are sourced. The `:scriptnames` output indicates that `/nix/store/3l1paq8q2rv949xjvsys0ihpz8ad4ypy-neovim-unwrapped-master` is before `/nix/store/2y8d3gpiypnpkywqiinn36ph68flip75-vimplugin-vimtex-master` in `runtimepath`. Common package managers will ensure the other way around - e.g., vim-plug will put plugin paths in _front_ of the neovim built-ins.

I've looked at your nix config, but I can't see how or where these things are defined. I can only assume that there are some sort of implicits involved. Perhaps someone else has defined a standard neovim "layer" for flakes/nix that you are relying on. If so, I would ask them, if you can't figure out on your own.

I'll close the issue, as I can't see how this is a problem with VimTeX. But feel free to follow up if you have more questions.
