### ISSUE TITLE
Add nested syntax support for pyluatex similar to pythontex

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2460]
I have used [pythontex](https://ctan.org/pkg/pythontex) for quite some time. However, it always requires to have a more complicated compilation setup (see this [latexmkrc](https://mirror.clientvps.com/CTAN/support/latexmk/example_rcfiles/pythontex-latexmkrc), pythontex always requires the python package pygments, but my system python remains clean, so I have to enable via [pyenv](https://github.com/pyenv/pyenv) a python version meeting the requirements, [...](https://xkcd.com/1987/)).

There is a new package pyluatex which only needs the luatex engine instead of pdftex (single compilation run, no need for additional python packages except which I personally use).

However, it has different environment names

```tex
\documentclass{article}
\usepackage{pyluatex} 

\begin{document} 

\begin{python} 
print("I am python but vimtex syntax highlighting does not know me")
\end{python}

\begin{pythonq} 
print("I am python but vimtex syntax highlighting does not know me")
\end{pythonq}

\begin{pythonrepl} 
print("I am python but vimtex syntax highlighting does not know me")
\end{pythonrepl}

\end{document} 
```

Can nested syntax highlighting added for these as well?

This document can be compiled with

```
$ lualatex --shell-escape document.tex
```

**Comment by lervag** [comment]
Pushed an initial support now.

**Comment by kiryph** [comment]
Thanks for the addition. I hope you are doing well.

**Comment by lervag** [comment]
I'm well, thanks! :)
