### ISSUE TITLE
Scroll PDF from within Vim

### ISSUE THREAD

**Issue by annTull** [lervag/vimtex#2462]
I am not sure if this is already possible to achieve, but I could not find mentions to it online so I am posting here as a feature request. If there is any way to already hack a solution to it, please let me know!

Is it possible to scroll up/down through a PDF opened with Zathura, but from within Vim using vimtex? I am not talking about forward/backward searching. I am talking about, for example, creating two shortcuts in Vim such that, when editing a tex file with vimtex, they would do the same as Shift+J and Shift+K keyboard keys do if the focus is on the PDF opened in Zathura, but without losing focus from Vim.

This would be a god-sent feature, because then when one wants to read through the PDF being edited, one would not need to keep Alt-Tabing to switch between Vim and the PDF.

Note: obviously a broader ability to send commands/shortcuts to a PDF viewer like Zathura could be an even more general suggestion - like searching, going to first/last page, etc. But I guess that is a bit too much of a trouble to implement.

**Comment by lervag** [comment]
There is, although it is hidden and undocumented. I believe you can achieve what you want with a custom function and map, something like this:

```vim
function! ZathuraDown() abort
  if exists('*b:vimtex.viewer.xdo_send_keys')
    call b:vimtex.viewer.xdo_send_keys('J')
  endif
endfunction

nnoremap LHS :<c-u>call ZathuraDown()<cr>
```

I'm leaving the other maps as an exercise. :)

I propose you add it in your `ftplugin/tex.vim` so it only sources for the `tex` filetype.

**Comment by lervag** [comment]
You can of course play around with the `xdo_send_keys` function. It should allow to send most key presses to Zathura. Of course, it relies on `xdotool`, and so it will only work on Xorg.

**Comment by annTull** [comment]
Ah, that was my hope; given how your plugin operates I was hoping that there would some hidden and undocumented way to communicate commands to the PDF viewer.

Unfortunately, however, that code snippet does not work on my setup. After pasting it the way it is in my `ftplugin/tex.vim`, I opened a new Vim instance, loaded a tex file, compiled it (which made the PDF open via Zathura). But then, when pressing the keys, nothing happens - nothing is even displayed in the status bar.

If I change the last line of your code to:

`nmap LHS <C-u> :call ZathuraDown()<CR>`

Then, after reopening, reloading and recompiling a tex file, at least pressing the keys displays `:call ZathuraDown()` in the status bar. But still, nothing happens on the PDF. I tried sending other keys for testing, no luck either.

**Comment by lervag** [comment]
Ah, it seems Zathura does not immediately accept key presses. I found a more hacky way:

```vim
function! ZathuraKey(key) abort
  if exists('b:vimtex.viewer.xwin_id')
        \ && b:vimtex.viewer.xwin_id > 0
    call vimtex#jobs#run(
          \ 'xdotool windowfocus --sync '
          \ . b:vimtex.viewer.xwin_id
          \ . ' key --clearmodifiers ' . a:key . ' ' . a:key)
    call b:vimtex.viewer.xdo_focus_vim()
  endif
endfunction

nnoremap <c-j> :<c-u>call ZathuraKey('J')<cr>
nnoremap <c-k> :<c-u>call ZathuraKey('K')<cr>
```

For some reason, I needed to duplicate the key press. I didn't need that in a terminal. Feel free to play around with it, I believe you should be able to build something with that.

**Comment by annTull** [comment]
Thanks, that works! The only caveat is the annoying typical delay that comes with sending keys/text via xdotool, but there seem to be no way around that (although I did find that using `type` instead of `key` has less delay in my computer at least).

I could also not find out why repeating the key/text is needed, but it is indeed. Very odd. Another oddity, out of curiosity, is that I tried dropping the `windowfocus` stuff and just using `key --window` or `type --window` instead. It should work, because the parameter `--window` is precisely for passing the window ID such that keys/text are passed to the target window regardless of it having focus. Nothing that I tried made it work without first issuing `windowsfocus`.

Anyhow, many thanks. I set up multiple special shortcuts that are proving very useful. Now I am just trying to set one that may allow searching within the PDF from Vim. In case I ever make it work, I will come back to post it here for future reference.

**Comment by lervag** [comment]
Great, glad to hear you find this useful!

> Another oddity, out of curiosity, is that I tried dropping the `windowfocus` stuff

Yes, I also noticed this. I believe some applications do not react to the passed events unless they have focus, somehow. There was something about this in the xdotool manual, although it was not very clear.
