### ISSUE TITLE
When forward searching, focus on PDF window first, then go back to Vim/gVim

### ISSUE THREAD

**Issue by annTull** [lervag/vimtex#2463]
I am not sure if this is a bug report or a feature request, to be honest. Also, I am aware of the many questions about making Vim/gVim get back the focus after forward searching. That works perfectly for me, using Zathura.

That is, my Vim/gVim  retains focus when forward searching. However, I would love if Zathura could get the focus first, and then lose it back to Vim/gVim .

This would be great for when the PDF window is behind other windows. Currently forward searching scrolls the PDF to the correct part, but the PDF viewer window does not gain any focus not even temporarily. Thus, if the PDF window is behind another software window (say, the web-browser), I have to alt-tab my way back to the PDF window and then alt-tab again to Vim/gVim .

For reference, my `.vimrc` curently has:

```vim
let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_mode = 2
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_quickfix_autoclose_after_keystrokes = 0

augroup vimrc
  autocmd!
  autocmd InsertEnter *.tex set conceallevel=0
  autocmd InsertLeave *.tex set conceallevel=2
augroup END

nmap \<localleader\>v <plug>(vimtex-view)
```

Is there any way to achieve what I described?

**Comment by lervag** [comment]
> For reference, my `.vimrc` curently has:

FYI, you don't need to set options unless you change them from the defaults, so you could simplify:

```viml
let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_open_on_warning = 0

" ...
```

> That is, my Vim/gVim retains focus when forward searching. However, I would love if Zathura could get the focus first, and then lose it back to Vim/gVim .

> Is there any way to achieve what I described?

I believe so. You can do something similar to the solution proposed in the other thread. Something like this:

```vim
augroup vimrc
  autocmd!
  autocmd InsertEnter *.tex set conceallevel=0
  autocmd InsertLeave *.tex set conceallevel=2
  autocmd User VimtexEventView call ZathuraFocus()
augroup END

function! CloseViewers()
  if exists('b:vimtex.viewer.xwin_id')
        \ && b:vimtex.viewer.xwin_id > 0
    " This may work:
    call vimtex#jobs#run('xdotool windowraise ' . b:vimtex.viewer.xwin_id)

    " If not, try the following:
    call b:vimtex.viewer.xdo_focus_viewer()
    sleep 50m
    call b:vimtex.viewer.xdo_focus_vim()
  endif
endfunction
```

I advice you to first test the simple `xdotool windowraise` line. It may work and if it does, it is much simpler than the focussing stuff below.

**Comment by annTull** [comment]
Hi again. The first and simpler option did not work; the only thing that happens is a top Ubuntu notification saying that the Zathura windows is ready. But it does not regain focus. The second option, however, worked like a charm!

Thanks much for being so responsive and helpful!

**Comment by lervag** [comment]
`xdotool` _is_ a little brittle! But I'm glad to hear it works! :)

**Comment by lervag** [comment]
> @lervag I'm having the same issue here (linux mint, neovim in kitty terminal).

IMHO, it's not necessarily the same issue, since you are on a different system. I generally much prefer that you open a _new_ issue rather than adding a new comment to an old issue. It makes it much easier for me, since it "forces" you to provide more of the relevant details and to explain the issue. Making it easier for me also means it is more likely that I can help you, faster.

But I'll try!

> Could you (or anyone else) please explain how to implement this solution in the context of a .lua config, rather than in vimscript?

Yes. Something like this:

```lua
local group = vim.api.nvim_create_augroup("init_vimtex", {})

vim.api.nvim_create_autocmd("InsertEnter", {
  pattern = "*.tex",
  group = group,
  command = "set conceallevel=0"
})

vim.api.nvim_create_autocmd("InsertLeave", {
  pattern = "*.tex",
  group = group,
  command = "set conceallevel=2"
})

vim.api.nvim_create_autocmd("User", {
  pattern = "VimtexEventView",
  group = group,
  callback = function()
    if
      vim.fn.exists("b:vimtex.viewer.xwin_id") > 0
      and vim.b.vimtex.viewer.xwin_id ~= "0"
    then
      vim.fn["vimtex#jobs#run"]("xdotool windowraise " .. vim.b.vimtex.viewer.xwin_id)

      vim.api.nvim_call_dict_function("b:vimtex.viewer", "xdo_focus_viewer", {})
      vim.cmd "sleep 50m"
      vim.api.nvim_call_dict_function("b:vimtex.viewer", "xdo_focus_vim", {})
    end
  end
})
```

> (sorry for this noob question...)

Properly converting the Vimscript function to Lua is not really trivial, so I wouldn't call it a noob question. You would probably come far with a tool like ChatGPT, but there are a lot of nuances that is easy to get wrong. Such as the type of `xwin_id` and the signature of `nvim_call_dict_function`.

> BTW is this still the recommended solution or has something changes since then?

Yes, I think this should still work and there is no better way to do this that I know of. Notice, though, that it depends on `xdotool` and so will not work on Wayland.

**Comment by lervag** [comment]
Glad to hear it! :)
