### ISSUE TITLE
Reverse search from zathura to gvim --servername broken in current master commit

### ISSUE THREAD

**Issue by jaijeet** [lervag/vimtex#2464]
First of all, many many thanks for writing and maintaining VimTeX.
I have been relying upon it for years - it is an essential part of my latex flow.

An issue with the most recent master commit (hash 5641242ea6d5eb30428f78eaa9591c78be351b66) is that it breaks synctex reverse search between zathura and `gvim --servername ...`.
This version of vimtex seems to call zathura with `synctex-editor-command` set to: 

```
/usr/bin/vim -T dumb --not-a-term -n -c "VimtexInverseSearch %{line} '%{input}'
```

In spite of `gvim` having been called with `--servername BOOK`. Not surprisingly, reverse search using `Ctrl-LeftClick` in zathura, with this setting, does not work with `gvim --servername ...`.

Whereas a previous commit (hash d569ed8c080fbfe2a65d710520afc59ef1618357) works fine. It sets `synctex-editor-command` in zathura to: `/usr/bin/vim --servername BOOK --remote +%{line} %{input}`.

Ideally, there would be some simple way of setting the preferred  `synctex-editor-command` in `~/.vimrc`, specifying, eg, the vim binary name, `v:servername`, etc.. `:help vimtex-synctex-inverse-search` does not, however, provide any insight into how this might be achieved. Note that any setting in `zathurarc` for `synctex-editor-command` is 1) overridden when vimtex starts up zathura, and 2) even if it were respected, it is not clear how the servername used for gvim/vim could be referred to inside `zathurarc`. Hardcoding a servername like VIM would break the multiple simultaneous gvim-zathura setups I have on different virtual workspaces.

My OS is Arch linux. The only relevant vimrc settings are: `let g:vimtex_view_method = 'zathura'` and `let g:vimtex_quickfix_mode = 0`.   My zathurarc contains only `set dbus-service true` and `set synctex true`.

**Comment by lervag** [comment]
> First of all, many many thanks for writing and maintaining VimTeX. I have been relying upon it for years - it is an essential part of my latex flow.

Glad to hear it! :)

> An issue with the most recent master commit (hash [5641242](https://github.com/lervag/vimtex/commit/5641242ea6d5eb30428f78eaa9591c78be351b66)) is that it breaks synctex reverse search between zathura and `gvim --servername ...`. This version of vimtex seems to call zathura with `synctex-editor-command` set to:
> 
> ```
> /usr/bin/vim -T dumb --not-a-term -n -c "VimtexInverseSearch %{line} '%{input}'
> ```

Yes. And that's on purpose and is an improvement on earlier methods. It no longer relies on providing the servername at all, because we do that within Vim itself. So, if this does not work for you, then something _else_ is wrong.

Can you open a simple LaTeX document, compile (`\ll`), then do `\lv`. Finally, do `\li` and show the output here.

**Comment by jaijeet** [comment]
> > An issue with the most recent master commit (hash [5641242](https://github.com/lervag/vimtex/commit/5641242ea6d5eb30428f78eaa9591c78be351b66)) is that it breaks synctex reverse search between zathura and `gvim --servername ...`. This version of vimtex seems to call zathura with `synctex-editor-command` set to:
> > 
> > ```
> > /usr/bin/vim -T dumb --not-a-term -n -c "VimtexInverseSearch %{line} '%{input}'
> > ```
> 
> Yes. And that's on purpose and is an improvement on earlier methods. It no longer relies on providing the servername at all, because we do that within Vim itself. So, if this does not work for you, then something _else_ is wrong.

Got it.

> Can you open a simple LaTeX document, compile (`\ll`), then do `\lv`. Finally, do `\li` and show the output here.


Note that I did not need a `\lv` for the zathura window to pop up after `ll` - one came up automatically.
Hitting `\lv` simply refocussed the same zathura window.

Here is the output of `li` after the above:

-----------------------
System info:
  OS: Linux 5.15.55-2-lts
  Vim version: VIM 9.0 ()
  Has clientserver: true
  Servername: BOOK

VimTeX project: 00-book-draft-top
  base: 00-book-draft-top.tex
  root: /home/jr/git-managed/simulationBook--github/the-book-latex
  tex: /home/jr/git-managed/simulationBook--github/the-book-latex/00-book-draft-top.tex
  main parser: current file verified
  document class: BYUTextbook
  packages: adjmulticol algorithm2e amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm amsxtra appendix array
  source files:
    00-book-draft-top.tex
    EEdeviceModels.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job:
      jobid: process 672852 run
      output: /var/tmp/jr/vHQqpct/0
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=non
      pid: 672852
  viewer: Zathura
    xwin id: 94371843
    cmd_forward_search: zathura --synctex-forward 11:1:'/home/jr/git-managed/simulationBook--github/the-book-latex/00-bo
    cmd_start: zathura  -x "/usr/bin/vim -T dumb --not-a-term -n -c \"VimtexInverseSearch %{line} '%{input}'\"" --syncte
  qf method: LaTeX logfile
-----------------------
~

**Comment by lervag** [comment]
Thanks. Now, what happens if you open `vim` in a terminal and do `:VimtexInverseSearch 100 'test.tex'`?

**Comment by lervag** [comment]
Also, can you show me your vimrc file/configuration?

**Comment by jaijeet** [comment]
VimtexInverseSearch is not found, in spite of `\ll`, `\lv`, etc, working.

This is likely because I am not using a plugin manager to load vimtex.
Instead, I have soft links under ~/.vim/ pointing to files in the vimtex git directory, together with `filetype plugin on` in ~/.vimrc.
(This worked in previous vimtex versions for inverse search.)

Let me try to narrow the cause a bit and get back to you.

**Comment by lervag** [comment]
> This is likely because I am not using a plugin manager to load vimtex. Instead, I have soft links under ~/.vim/ pointing to files in the vimtex git directory, together with `filetype plugin on` in ~/.vimrc.

Yes, that seems likely to be the issue. If you explain exactly what you do, I can help. The issue, in any case, is that you do not source `VIMTEX/plugin/vimtex.vim`.

Notice, though, this way of installing the plugin is not really something I would recommend.

**Comment by jaijeet** [comment]
Indeed this was the case.
I added an explicit line in my `.vimrc` to source `~/.vim/plugin/vimtex.vim` (which is a soft link to `VIMTEX/plugin/vimtex.vim`); and it now works fine.
It does not seem to even require any `--servername` argument to vim/gvim any more; in spite of this, it works correctly with two different gvim/vimtex/zathura setups running simultaneously.

The vimtex-relevant lines in my `.vimrc` now are: 
```
filetype plugin on 
source $HOME/.vim/plugin/vimtex.vim
```

vimtex-relevant soft links under my `~/.vim/` are:
```
$ ls -l ~/.vim/vimtex-git
0 lrwxrwxrwx 1 jr jr 42 Aug 21 08:28 /home/jr/.vim/vimtex-git -> /home/jr/git-managed/vimtex--github-lervag/

$ ls -l ~/.vim/autoload/
0 lrwxrwxrwx 1 jr jr 29 Aug 21 08:34 vimtex -> ../vimtex-git/autoload/vimtex/
0 lrwxrwxrwx 1 jr jr 33 Aug 21 08:50 vimtex.vim -> ../vimtex-git/autoload/vimtex.vim

$ ls -l ~/.vim/ftplugin/
total 0
0 lrwxrwxrwx 1 jr jr 30 Aug 21 19:07 bib.vim -> ../vimtex-git/ftplugin/bib.vim
0 lrwxrwxrwx 1 jr jr 30 Aug 21 19:07 tex.vim -> ../vimtex-git/ftplugin/tex.vim

$ ls -l ~/.vim/plugin/
 0 lrwxrwxrwx 1 jr jr    31 Aug 21 19:01 vimtex.vim -> ../vimtex-git/plugin/vimtex.vim
```

`plugin/vimtex.vim` does not seem to be automatically sourced (hence I now do so explicitly in `.vimrc`, as above); but the rest seem to be.
This seems a minimal set of soft links needed for vimtex to work (except possibly for `ftplugin/bib.vim`).

We could close the issue, though I am going to try cleaning up and modernizing my `.vimrc` and `.vim/` (which have collected things over almost 30 years) and try using a plugin to load vimtex, as recommended.
I do have a preference for setting up vimtex using as few other packages and layers as possible, though.

Thank you again, very much, for everything!

Jaijeet

**Comment by lervag** [comment]
> Indeed this was the case.

Great, glad to hear it works now!

> It does not seem to even require any `--servername` argument to vim/gvim any more;

That's right and as expected. However, notice that you still need to ensure that Vim _has_ a servername (check with `\li`). VimTeX relies on this for callbacks from the compiler.

> The vimtex-relevant lines in my `.vimrc` now are: ...

I would strongly recommend to instead change the `runtimepath` setting. E.g., I believe these lines should work:

```vim
" Somewhere near the top of your vimrc file
set runtimepath^=~/.vim/vimtex-git
set runtimepath+=~/.vim/vimtex-git/after
filetype plugin indent on
syntax enable
```

Then you would no longer need to do all this intricate symlinking.

> though I am going to try cleaning up and modernizing my `.vimrc` and `.vim/` (which have collected things over almost 30 years) and try using a plugin to load vimtex, as recommended. I do have a preference for setting up vimtex using as few other packages and layers as possible, though.

I would recommend vim-plug, as it is quite easy to use. But changing the runtimepath as I suggested above is also easy and should work (this is essentially what plugin managers do for you).

> Thank you again, very much, for everything! Jaijeet

Glad to help!

By the way: notice that, when you use the option to reply to threads by email, the formatting will not work. I don't know why.

**Comment by lervag** [comment]
Regarding the clientserver stuff, in case you did not already do so, I suggest you read `:help vimtex-clientserver`.
