### ISSUE TITLE
Support of \mleft \mright highlighting and concealing

### ISSUE THREAD

**Issue by 9IPOCJIABbI4** [lervag/vimtex#2466]
Current behaviour:
<img width="184" alt="image" src="https://user-images.githubusercontent.com/48085992/185742427-d2e96f24-e8ae-43f2-849f-cbb8a5a34dbb.png">

**Comment by lervag** [comment]
Can you provide a complete example LaTeX file that I can compile on my machine?

**Comment by 9IPOCJIABbI4** [comment]
```
\documentclass{article}
\usepackage{mleftright}
\begin{document}
\[
   \left(  \right) 
   \mleft(  \mright) 
\] 
\end{document}
```

**Comment by lervag** [comment]
I've added support for this now, please test and let me know if I missed something.

**Comment by 9IPOCJIABbI4** [comment]
Thank you very much!

**Comment by lervag** [comment]
Glad to hear it! :)
