### ISSUE TITLE
Support distinguishing different cases of math environment using different group

### ISSUE THREAD

**Issue by pilgrimlyieu** [lervag/vimtex#2467]
Use different groups for `texMathZone`s to make it possible to distinguish them. See also #2397.

Here are currently supported cases (see `:help vimtex-syntax-reference`, table 3):

```txt
  GROUP                    DEFAULT        EXAMPLE
  ----------------------------------------------------------------------------
  texMathZone              Special        \( HERE \); \[ HERE \]
  texMathZoneX             texMathZone    $ HERE $
  texMathZoneXX            texMathZone    $$ HERE $$
```

Notice that we can't distinguish `\( Inline Math \)` and `\[ Display Math \]` through, since they are both `texMathZone`.

**Comment by lervag** [comment]
Perhaps we could use something like this:

GROUP | DEFAULT | EXAMPLE
--- | --- | ---
texMathZoneLI | Special | \( here \)
texMathZoneLD | Special | \[ here \]
texMathZoneTI | texMathZone | $ here $
texMathZoneTD | texMathZone | $$ here $$

@clason do you have any thoughts on this? Ideas for more consistent naming, perhaps?

**Comment by clason** [comment]
Hmm, I'd prefer if the current behaviour wouldn't change (all math zones link to `texMathZone`, which links to `Special`).

Otherwise the naming is sound (and better than `X`, `XX`); I just worry a bit about compatibility with the builtin tex syntax file -- will this lead to a huge regression with common colorschemes? (But are there even any with specific tex highlight groups?)

Will you use special groups for the delimiters themselves then?

**Comment by lervag** [comment]
> Hmm, I'd prefer if the current behaviour wouldn't change (all math zones link to `texMathZone`, which links to `Special`).

Sorry, here's an adjusted suggestion that should make more sense:

GROUP | DEFAULT | EXAMPLE
--- | --- | ---
texMathZone   | Special | N/A
texMathZoneLI | texMathZone | `\( here \)`
texMathZoneLD | texMathZone | `\[ here \]`
texMathZoneTI | texMathZone | `$ here $`
texMathZoneTD | texMathZone | `$$ here $$`

> Will you use special groups for the delimiters themselves then?

The delimiters will still all link to `texMathDelimZone`, of course.

> Otherwise the naming is sound (and better than `X`, `XX`); I just worry a bit about compatibility with the builtin tex syntax file -- will this lead to a huge regression with common colorschemes? (But are there even any with specific tex highlight groups?)

I don't think so, but I have to admit I don't know. But then, this change should make it _really_ easy for colorscheme creators to adjust their rules, right?

**Comment by clason** [comment]
> The delimiters will still all link to texMathDelimZone, of course.

I meant, will you add `texMathDelimZoneTD` and friends? (I assume yes, but just to make it explicit.)

> I don't think so, but I have to admit I don't know. But then, this change should make it really easy for colorscheme creators to adjust their rules, right?

Yes, it's not hard to adapt at all; just trying to come up with possible complaints about this change.

**Comment by lervag** [comment]
> > The delimiters will still all link to texMathDelimZone, of course.
> 
> I meant, will you add `texMathDelimZoneTD` and friends? (I assume yes, but just to make it explicit.)

I don't see why not. If we link them to a common one, things will not change for anyone, except it allows more flexibility for people who might want it.

Updated suggestion:

GROUP | DEFAULT | EXAMPLE
--- | --- | ---
texMathZone   | Special | N/A
texMathZoneLI | texMathZone | `\( here \)`
texMathZoneLD | texMathZone | `\[ here \]`
texMathZoneTI | texMathZone | `$ here $`
texMathZoneTD | texMathZone | `$$ here $$`
texMathDelimZone   | texDelim | N/A
texMathDelimZoneLI | texMathDelimZone | `\(` and `\)`
texMathDelimZoneLD | texMathDelimZone | `\[` and `\]`
texMathDelimZoneTI | texMathDelimZone | `$` and `$`
texMathDelimZoneTD | texMathDelimZone | `$$` and `$$`

**Comment by lervag** [comment]
Notice, with these suggestions, it would be easy to check if one is inside an inline environment with `vimtex#syntax#in('texMathZone[LT]I')`, or inside _any_ of the math zones with `vimtex#syntax#in('texMathZone')`.

**Comment by lervag** [comment]
Done; I've updated the code and the docs, as well as the related wiki entry. Let me know if there is something that is not working as expected!

(I will make sure this gets some attention in the next release notes.)
