### ISSUE TITLE
textidote not working

### ISSUE THREAD

**Issue by chenle02** [lervag/vimtex#2472]
I tried to configure textidote in my system (ubuntu)

Here is the setup in `init.vim` file:
```
let g:vimtex_grammar_textidote = {'jar': '/opt/textidote/textidote.jar'}
```

I can run `$ textidote test.tex` from terminal with output. But when I open a tex file using my
neovim and type `:compiler textidote | lmake`, results are shown and upon pressing enter, they disappear. It would be nice to have them in a quickfix window.

Thanks a lot~!

**Comment by chenle02** [comment]
It works now. I will use the html output and view it from the browser. The colors are way better than the plain text output.

**Comment by lervag** [comment]
I'm sorry for the late reply, I've been busy.

I'm glad to hear you made it work. Does it mean we can close the issue?

**Comment by chenle02** [comment]
Thank you Lervag. After reading more carefully the help document, I figured out how it works and the best way may just use the html output, where one can see the colors.

Yes, please close the issue. Thanks a lot~!

> I'm sorry for the late reply, I've been busy.
> 
> I'm glad to hear you made it work. Does it mean we can close the issue?
