### ISSUE TITLE
Always ignore special characters inside minted blocks

### ISSUE THREAD

**Issue by asmunder** [lervag/vimtex#248]
Currently, one must enable vimtex handling of minted blocks on a per-language basis by specifying a list-of-dicts in `g:vimtex_syntax_minted`. If nothing is specified for a language, vimtex does not perform nested highlighting for blocks using that language. This is done for performance reasons and is fine. 

However, vimtex also does not ignore special characters inside minted blocks that use a language not specified in `g:vimtex_syntax_minted`. This is a problem if one has not specified javascript and writes code blocks with `$` inside, then vimtex thinks it is in math mode after this $, leading to incorrect behaviour. The default should be to always ignore special characters inside minted blocks, for all languages.

**Comment by lervag** [comment]
In the latest update, minted environments should now behave similar to lstlisting environments, unless the language is added to `g:vimtex_syntax_minted`. This should solve your problem.
