### ISSUE TITLE
Cite lervag and vimtex in my acknowledgment thesis section

### ISSUE THREAD

**Issue by awelormro** [lervag/vimtex#2482]
It is not a bug, but don't know where can I ask this, without the ease and adptability of vimtex, I wouldn't been able to finish my thesis and I wanted to ask you if is possible to put you in my thesis acknowledgment section

**Comment by lervag** [comment]
> It is not a bug, but don't know where can I ask this, without the ease and adptability of vimtex, I wouldn't been able to finish my thesis and I wanted to ask you if is possible to put you in my thesis acknowledgment section

Thank you, @awelormro, I would be honored to be mentioned in your thesis acknowledgements! And if you do, please don't hesitate to send me a copy (if _possible_ of course) :)

**Comment by awelormro** [comment]
Thanks! I'm waiting the final revissions but when it will be finished I'll send you a copy :)

**Comment by lervag** [comment]
Cool; and congrats on finishing your thesis! :)
