### ISSUE TITLE
Conceal is wrong on subscript \delta

### ISSUE THREAD

**Issue by griffinwxk** [lervag/vimtex#2485]
### Description

In math mode, if I write `_\delta` or `_{\delta}`, the conceal will render as Unicode subscripts "elta", while `\d` seems to be treated as an macro and is hidden. As far as I know there is a Unicode character for subscript delta. Other greek letters seem fine (for the ones I use).

### Steps to reproduce

Just write `_\delta` or put `\delta` in any part of a subscript enclosed by braces `_{}`, in math mode of course.

### Expected behavior

Either concealed with a Unicode subscript delta, or at least render \delta as plain Unicode delta.

### Actual behavior

It's rendered as subscript "elta" with "\d" part hidden

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
It should be a simple syntax file bug so VimtexInfo shouldn't matter here.
```

**Comment by lervag** [comment]
Sorry, but it seems subscript delta does not exist. At least, I can't find it. I've searched e.g. [here](https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts#Latin,_Greek_and_Cyrillic_tables).

I can confirm the problem, though. I believe the latest patch at least improves slightly.

**Comment by griffinwxk** [comment]
Yes you are right about subscript delta. My bad (I have some font config file that I looked up wrong). I just updated and it works fine now (normal delta works for me)! Thank you!

**Comment by lervag** [comment]
No problem; thanks for noticing and reporting!
