### ISSUE TITLE
bibtex-tidy as a new vimetex friend?

### ISSUE THREAD

**Issue by ccaprani** [lervag/vimtex#2487]
Duplicate keys, bad formatting, and a host of other problems can make working with bib files a pain.

[_bibtex-tidy_](https://flamingtempura.github.io/bibtex-tidy/) is a cool tool that makes this much easier. It has a [CLI](https://github.com/FlamingTempura/bibtex-tidy#sec-cli) through npm and I'm wondering if it would be relatively easy to add it to vimtex as an optional add-on? 

That is, if _bibtex-tidy_ is on your system (`npm install -g bibtex-tidy`), then execute something like `<localleader>lT` to run _bibtex-tidy_ on the current bib file.

I don't have the skills to execute this idea unfortunately.

**Comment by lervag** [comment]
Thanks for mentioning this! I've started by adding a short comment on this plugin in the docs (see `:help vimtex-af-ftplugin-bib`).

Reg. an optional add-on within VimTeX: I'm not sure it is a good idea. Several reasons:

1. Different users will probably want different behaviour. This means we would need one or more extra options. We would also need documentation to guide users on how to install and similar.
1. It is actually quite easy to make a custom mapping that does what you want. This would also allow to customize exactly as you want it.

As a short proof of the latter point: put the below code in e.g. your `~/.vim/ftplugin/bib.vim` or `~/.config/nvim/ftplugin/bib.vim`:

```vim
nnoremap <localleader>lT :!bibtex-tidy %:p<cr>
```

You could also use more advanced options:

```vim
nnoremap <localleader>lT :!bibtex-tidy --omit=id,name --space --sort %:p<cr>
```

**Comment by ccaprani** [comment]
Dear people form the future: this works a treat; though `<leader>lT` clashed with the default contents mapping, so I've used the following, with my own preferences for the CLI args:
```vim
nnoremap <localleader>bt :!bibtex-tidy --align --space=4 --duplicates --merge=combine %:p<cr>
```
As ever @lervag has been super helpful for a not-too-skilled person like me. Nicest guy in the business - thank you!

**Comment by lervag** [comment]
> As ever @lervag has been super helpful for a not-too-skilled person like me. Nicest guy in the business - thank you!

My pleasure! :)

**Comment by nachovizzo** [comment]
For those also looking into bibtex-tidy. I've added a "formatter" to use the tools, just a formatting tool. More info on the Neoformat repo:  https://github.com/sbdchd/neoformat/pull/456
