### ISSUE TITLE
Toggle between equation and align

### ISSUE THREAD

**Issue by cnut1648** [lervag/vimtex#2488]
**Is your feature request related to a problem? Please describe it.**
When typing for math formula in `\[ \]` I find myself often need to switch to `align` due to the formula getting too long and I need to split it into several lines. Currently `ts$` can toggle between inline math mode, display math mode, and `equation` environment. I think it will be useful if we can have even more environments to toggle, in particular, makes `equation` jump to `align`.

**Additional context**
A similar topic is raised in https://github.com/lervag/vimtex/issues/2310, and we have `vimtex_env_toggle_math_map`. But I found it not able to recognize the environment name, I have the following in my config but it seems that it still fallback to default `$` every time when I toggle in equation mode.

```
let g:vimtex_env_toggle_math_map = {
      \ '$': '\[',
      \ '\[': 'equation',
      \ 'equation': 'align',
      \ 'align': 'gather',
      \}
```
Thank you!

**Comment by lervag** [comment]
> When typing for math formula in `\[ \]` I find myself often need to switch to `align` due to the formula getting too long and I need to split it into several lines.

Actually, you should not use `align` in this case. Instead, you should use `\begin{multline*} ... \end{multline*}` or `\[ \begin{split} ... \end{split} \]` or something similar. `align` is more useful for multiple equations.

> I have the following in my config but it seems that it still fallback to default `$` every time when I toggle in equation mode.
> 
> ```
> let g:vimtex_env_toggle_math_map = {
>       \ '$': '\[',
>       \ '\[': 'equation',
>       \ 'equation': 'align',
>       \ 'align': 'gather',
>       \}
> ```

That's definitely a bug. I've pushed a fix now. Thanks for noticing and reporting!

**Comment by cnut1648** [comment]
@lervag Thanks for the suggestion!
