### ISSUE TITLE
Add vimtex-env-create

### ISSUE THREAD

**Issue by cnut1648** [lervag/vimtex#2489]
First of all, I have been using vimtex for a few days and this plugin is absolutely amazing!!!! Thank you so much for this plugin and it makes my note-taking experience better than ever!!

**Is your feature request related to a problem? Please describe it.**
Currently there is a `vimtex-cmd-create` which is mapped to `F7` by default. I personally find it very useful in that I can visually select text and hit one `F7` to wrap the whole selected text in a command. 

I think it will be equally useful if we can have a counterpart for environment so that users can also wrap selected text in an environment.

**Describe the solution you'd like**
Add a `vimtex-env-create` command.

**Describe alternatives you've considered**
My current workaround is to use [Utisnips](https://github.com/SirVer/ultisnips), here is my snip:
```
snippet beg "begin{} / end{}" bA
\\begin{$1}
	${VISUAL}
\\end{$1}
endsnippet
```
To do so I would have to first enter into visual mode, select text, hit `tab` and type `beg` and `tab` again, which is ok but a little annoying. With `vimtex-env-create` command I can map it to, say, `<F5>` and voila.

Thank you for reading.

**Comment by lervag** [comment]
> First of all, I have been using vimtex for a few days and this plugin is absolutely amazing!!!! Thank you so much for this plugin and it makes my note-taking experience better than ever!!

Thanks for the kind words! :)

> I think it will be equally useful if we can have a counterpart for environment so that users can also wrap selected text in an environment.
> 
> **Describe the solution you'd like** Add a `vimtex-env-create` command.

I've previously thought this should be left to a snippet engine. However, I can see that this, although solveable by a snippet engine, could also warrant a feature of its own in VimTeX. We would want this workflow, right:

* **Visual mode**: Select text, press `<f5>`, write the name of an environment, then VimTeX adds `\begin{name}` in a line above and `\end{name}` in a line below the selection. Preferably it should be properly indented, so we might also adjust indents accordingly.
* **Normal mode**: press `<f5>` to surround current line with an environment.

Perhaps we should call it `vimtex-env-create-surrounding` to make it more clear?

**Comment by Alexandre867** [comment]
I'm using [UltiSnips](https://github.com/SirVer/ultisnips) too and I've found a workaround for wrapping around some selected text using some mapping here: [https://vi.stackexchange.com/questions/38597/mapping-snippet-trigger-in-visual-mode](https://vi.stackexchange.com/questions/38597/mapping-snippet-trigger-in-visual-mode). You could adapt it to wrap around as an environment.

In my ~\vimfiles\ftplugin\tex.vim:
```
vnoremap <buffer> <C-S-E> :call UltiSnips#SaveLastVisualSelection()<CR>gvs#<C-R>=UltiSnips#ExpandSnippet()<CR>
inoremap <buffer> <C-S-E> #<C-R>=UltiSnips#ExpandSnippet()
```

In my ~\vimfiles\UltiSnips\tex.snippets:
```
snippet # "Put in brackets" i
\\${1:emph}{${VISUAL}$2}$0
endsnippet
```

**Comment by lervag** [comment]
@cnut1648 Any comments about my suggestion?

**Comment by cnut1648** [comment]
Hi @lervag, this sounds really great! This is exactly what I was looking for. The indentation part is good, as for now I have to manually add the indentation in the snippet engine.

**Comment by cnut1648** [comment]
@Alexandre867 oh interesting. I never knew we can make non-ascii characters the trigger. This certainly gives us more options for this functionality. But I personally still feel a vimtex built-in is easier to manage.

**Comment by lervag** [comment]
I've added an initial version of this. Please test and give some feedback. The relevant docs: `:help vimtex-env-surround-line`. Notice that the default map is `<F6>`.

**Comment by cnut1648** [comment]
Thanks @lervag! I've been using it for a day and it is good!!

**Comment by lervag** [comment]
Glad to hear it!

**Comment by lukasz-r** [comment]
I've been using an older version of VimTeX and got used to pressing <F5> for environment insert. I switched to the newest version and I'm glad to see it's back, though mapped to <F6>, but that's not a problem. A great feature.
