### ISSUE TITLE
Minted-highlighting: add support for different names of language in Vim-syntax and in Pygments

### ISSUE THREAD

**Issue by asmunder** [lervag/vimtex#249]
Example: when I write code in HTML with the Jinja2 templating engine, I want Minted to highlight this properly, and I can do that by specifying the language in the minted block as "html+jinja" which is what Pygments calls it. But then I can't enable vimtex to handle minted blocks in this language (using `g:vimtex_syntax_minted`), since the name of the vim style file is not "html+jinja.vim", it's just "jinja.vim". Of course I can set up a symlink to trick this, but that's a pretty ugly hack. I think the system should be extended to allow specifying e.g.

```vimscript
let g:vimtex_syntax_minted = [
      \ {'lang' : 'html',},
      \ {'lang' : 'html+jinja', 'syntax' : 'jinja.vim',},
      \]
```

**Comment by lervag** [comment]
Your example should already work, try:

```vim
let g:vimtex_syntax_minted = [
      \ {'lang' : 'html',},
      \ {'lang' : 'html+jinja', 'syntax' : 'jinja',},
      \]
```

**Comment by asmunder** [comment]
I need to learn to RTFM. Thanks.

**Comment by lervag** [comment]
No problem :)
