### ISSUE TITLE
got error when compiling 

### ISSUE THREAD

**Issue by ZeyuBa** [lervag/vimtex#2493]
### Description

when i open a `.tex` file and use `\ll` the got the error:

```
Error detected while processing function vimtex#compiler#compile:
line    1:
E716: Key not present in Dictionary: "is_running"
```

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
:VimtexInfo
```

**Comment by lervag** [comment]
Well, how do you expect me to help you with this when you don't provide any of the information I've specifically asked for in the issue template?

**Comment by lervag** [comment]
Still; I expect this has something to do with how you've installed VimTeX. Perhaps you have a conflict with other LaTeX plugins. After you've opened a `.tex` file, can you do `:scriptnames` and copy the output here (or take a screenshot if that's easier - just make sure to show all of the output).

**Comment by lervag** [comment]
Thanks. This is easier to follow. However, I think there must be something wrong in your configuration. Can you show me your VimTeX related config?

**Comment by AbdeltwabMF** [comment]
Yes here it is.
```lua
-- vimtex.lua 


-- Viewer options: One may configure the viewer either by specifying a built-in
-- viewer method:
vim.g.vimtex_view_method = "zathura"

-- Or with a generic interface:
vim.g.vimtex_view_general_viewer = "okular"
vim.g.vimtex_view_general_options = "--unique file:@pdf#src:@line@tex"

-- VimTeX uses latexmk as the default compiler backend. If you use it, which is
-- strongly recommended, you probably don't need to configure anything. If you
-- want another compiler backend, you can change it as follows. The list of
-- supported backends and further explanation is provided in the documentation,
-- see ":help vimtex-compiler".
vim.g.vimtex_compiler_method = "latexrun"

-- Most VimTeX mappings rely on localleader and this can be changed with the
-- following line. The default is usually fine and is the symbol "\".
-- vim.g.maplocalleader = ","

vim.g.vimtex_imaps_enabled = 0
```

```lua
-- init.lua

use({
  "lervag/vimtex",
  config = function()
    require("xxx.plugins.vimtex")
  end,
})
```

**Comment by AbdeltwabMF** [comment]
I've figured it out now by commenting this line

```lua
vim.g.vimtex_compiler_method = "latexrun"
```

I think my machine does not have `latexrun` installed but `latexmk`.

**Comment by lervag** [comment]
> Yes, here it is.
> ...
> I've figured it out now by commenting this line
> 
> ```lua
> vim.g.vimtex_compiler_method = "latexrun"
> ```
>
> I think my machine does not have `latexrun` installed but `latexmk`.

It seems you've copied the configuration listed in the [README.md](https://github.com/lervag/vimtex/blob/71e6e2d27520477975a5c86d568b1ed1b781bba3/README.md#configuration). Specifically, from these lines:

```vim
" ...

" Viewer options: One may configure the viewer either by specifying a built-in
" viewer method:
let g:vimtex_view_method = 'zathura'

" Or with a generic interface:
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'

" VimTeX uses latexmk as the default compiler backend. If you use it, which is
" strongly recommended, you probably don't need to configure anything. If you
" want another compiler backend, you can change it as follows. The list of
" supported backends and further explanation is provided in the documentation,
" see ":help vimtex-compiler".
let g:vimtex_compiler_method = 'latexrun'
```

It seems you did not even read the comments. Or the text above, which says (added emphases):

> After installing VimTeX, you should edit your `.vimrc` file or `init.vim` file to configure VimTeX to your liking. **Users should read the documentation** to learn the various configuration possibilities, but **the below is a simple overview** of some of the main aspects.

It is _not_ meant for copy-paste! And you should definitely read the docs, or at least part of them. I can also recommend the tutorial linked to from the README file.

Notice that VimTeX tries to provide reasonable defaults. You should not change any option unless you know what you are doing. And, to know what you are doing, you should read the docs :)

**Comment by lervag** [comment]
No worries, we are all guilty of things like that. I hope I did not come off annoyed. Perhaps I should somehow change the README, because you are not the only one to do this mistake, I think. That is, I believe there have been multiple issues due to confusion from copying the config from the README before reading (understanding) the surrounding text.
