### ISSUE TITLE
TOC highlighting for fixme package

### ISSUE THREAD

**Issue by lambtho12** [lervag/vimtex#2497]
## Feature
The fixme package creates adds a few commands that can be used as `todo` in the document. These are already parsed and gathered in vimtex's TOC ([see old feature request](https://github.com/lervag/vimtex/issues/1770)), as it would be the case for regular `\todo` commands or `TODO` comments.

While `\todo` and `TODO` are currently highlighted in the TOC, there is currently no highlight for the fixme commands and environments (see [this comment for full list](https://github.com/lervag/vimtex/issues/2494#issuecomment-1257236074)). This makes it difficult to differ the `fixme` items from regular headings in the TOC.

## Proposition
Two possibillities (maybe add an option for the user to decide?)
1. Highlight all fixme commands in the TOC as `TODO` items to make them pop a bit more.
2. Highlight the fixme commands using their level of severity, as it is done with the fixme package.
    - `fxnote` like the `TODO` items (?)
    - `fxwarning` in yellow-orange
    - `fxerror` in dark orange
    - `fxfatal` in red (bold red?)

For reference, the colors used in `fixme` are the following:
```latex
\definecolor{fxnote}{rgb}{0.0000,0.6000,0.0000}
\definecolor{fxwarning}{rgb}{1.0000,0.5490,0.0000}
\definecolor{fxerror}{rgb}{1.0000,0.2706,0.0000}
\definecolor{fxfatal}{rgb}{1.0000,0.0000,0.0000}
```

----
This feature request is linked to an other one asking for proper syntax highlight of the fixme commands in the tex document: https://github.com/lervag/vimtex/issues/2494

**Comment by lervag** [comment]
This should be implemented now. Please test.

Notice, you can customize the colors. See `:help vimtex-syntax-reference` table 1 for the relevant groups (`VimtexTodo` and so on).

**Comment by lambtho12** [comment]
Awesome! This works great. Thank you very much for implementing this.

**Comment by lervag** [comment]
Glad to hear it! :)
