### ISSUE TITLE
vimtex to detect custom math environments

### ISSUE THREAD

**Issue by Alexandre867** [lervag/vimtex#2499]
Is it possible to have vimtex detect custom math environment? It's causing me issues when using context-dependant snippets.

I found out I can fix it by manually adding every custom environment using `call vimtex#syntax#core#new_region_math('nsflalign')` for example in my ftplugin/tex.vim.

Here's a .tex example, with how it looks without and with adding the custom environment manually.

```
\documentclass{article}
\usepackage[paperheight=2in,paperwidth=3in,margin=.25in]{geometry}
\usepackage{mathtools}
\newenvironment{nsflalign}{\setlength{\abovedisplayskip}{0pt}\setlength{\belowdisplayskip}{0pt}\csname flalign\endcsname}{\csname endflalign\endcsname\ignorespacesafterend}

\begin{document}

\begin{nsflalign}
	1+2 &= 3 &\\
	\mu^2+\tau^2 &= \theta^2+4
\end{nsflalign}

\begin{flalign}
	1+2 &= 3 &\\
	\mu^2+\tau^2 &= \theta^2+4
\end{flalign}

\end{document}
```
![Screenshot of the code without fix](https://user-images.githubusercontent.com/97113885/192309363-1e859f41-f7d7-4a36-a1aa-8d5834ac274e.png)
![Screenshot of the document](https://user-images.githubusercontent.com/97113885/192308954-bd680347-edfd-4ef2-b9c1-a4bc0250dca1.png)
![Screenshot of the code with manual fix](https://user-images.githubusercontent.com/97113885/192308876-f71b2f2c-bede-4cb1-95a4-2d8977ee6c8c.png)

**Comment by lervag** [comment]
> I found out I can fix it by manually adding every custom environment using `call vimtex#syntax#core#new_region_math('nsflalign')` for example in my ftplugin/tex.vim.

This is precisely how you should handle this specific case.

> Is it possible to have vimtex detect custom math environment?

No, that's too hard. Sorry!

**Comment by Doltonius** [comment]
Do you have any clue why putting that line in my ftplugin/tex.vim does not work, but typing it in the command line after the file is loaded works?

**Comment by lervag** [comment]
Thanks for that questions - it shows that I was too quick in my previous reply!

You need to execute that line _after_ the VimTeX syntax scripts have executed. Putting the line in your personal `ftplugin/tex.vim` does not ensure this. A more appropriate place to put this (and similar) customizations would be in your `after/syntax/tex.vim`, because this script will be executed after all the main syntax scripts.

**Comment by Doltonius** [comment]
That works! I have another question: is there a way to disable conceal in certain environments?

**Comment by lervag** [comment]
Partly; you can control the conceal options with `:help g:vimtex_syntax_conceal`. It is not very customizable, sorry.

It would be easier to answer a concrete question, though...

**Comment by Doltonius** [comment]
For example, I want math-mode highlighting but not math-mode conceal inside the environment `tikzcd`, since I want to be able to align by `&`(`tikzcd` turns on math mode on the inside and it is fundamentally a `tabular`-like environment); I added it to the list of math env delimiters for the former purpose, but then the math symbols are concealed, making manual alignment useless.

**Comment by Felipe-9** [comment]
Im having some trouble declaring a math environment as well...
how im receiving an error saying the function is not defined
<img width="684" alt="Screenshot 2024-10-04 at 23 31 01" src="https://github.com/user-attachments/assets/4080788a-56eb-4251-84c6-827783e2da3e">

i read that the proper lua bridge would be using `vim.fn` and i want to define the environment `BM`
then i should add to my `vimtex.lua` setup the following line `vim.fn['vimtex#syntax#core#new_region_math']('BM')`

**Comment by lervag** [comment]
@Felipe-9 Can you open a new issue for your question and provide the relevant context in your post?

**Comment by Felipe-9** [comment]
sure, no problem

**Comment by Felipe-9** [comment]
### Update,

i found a solution for this so there is no need to create another issue. i can still create an issue also providing the answer right away if needed.

On the docs i found this function that allows us to declare custom environments and describe their characteristics
<details>
<summary>

### `g:vimtex_syntax_custom_envs` (from the docs)
</summary>

> A list of environments for which to apply custom styling. This allows to
  define custom math environments or to specify custom environments for which
  to load nested syntaxes. The latter is relevant e.g. if you use the
  `\lstnewenvironment` from the `listings` package.
  ...
</details>

```lua
    vim.g.vimtex_syntax_custom_envs = {
      {
        name = "BM",
        math = true
      }
    }
```

**Comment by lervag** [comment]
Great - I should probably have been able to remember that and provided an answer immediately. 😅
