### ISSUE TITLE
neovim servername unknown command

### ISSUE THREAD

**Issue by Lorenzbi** [lervag/vimtex#250]
I recently found out about neovim but it seems the --servername option was removed. How can I use vimtex in continuous mode? 

nvim: Unknown option argument: "--servername"

**Comment by lervag** [comment]
Interesting question. I've not begun to use neovim yet myself. Neovim has implemented a different approach to servers, it seems, and it does not have the argument `--servername`. It should be possible to solve this, but at the moment I just don't have the time.

I do, however, plan to switch to neovim sometime in the future. When I do, I will of course update vimtex to support neovim.

In the meantime, you may turn off the callback functionality with the following setting (in your nvimrc):

```vimL
let g:vimtex_latexmk_callback = 0
```

Note also that the servername is used with the Zathura pdf viewer, and so it won't work on neovim either. You may use the general viewer to get basic Zathura functionality, but it will not provide advanced features (like backward and forward search, as well as the detection of existing viewer to get a unique viewer).
