### ISSUE TITLE
Can't use :VimtexInfo,and it throw a error: String ... contains byte that does not start any utf-8 character.

### ISSUE THREAD

**Issue by tlm12345** [lervag/vimtex#2507]
### Description

I has installed the vimtex plugin, and it's wrong when I run command ":VimtexInfo"。The information is folloing:
![QQ截图20221002201839](https://user-images.githubusercontent.com/74193816/193456722-5295fffe-c796-48dd-a515-177ce4d252e6.png)
I check vim-plug's installed list, it's ok.
![QQ截图20221002201909](https://user-images.githubusercontent.com/74193816/193456787-30d95559-653a-4176-8501-339c640bac06.png)
After I run command ":VimtexInfo", I did it again.The wrong information was changed.
![QQ截图20221002213519](https://user-images.githubusercontent.com/74193816/193456883-afc95684-5da6-4a94-990b-b897870db85e.png)
I read the third-party article Getting startted with the vimtex plugin, only a fraction of that article.And the relative content of configuration in my init.vim(Neovim) is folloing:
![QQ截图20221002214250](https://user-images.githubusercontent.com/74193816/193457234-3cdb3cd3-de5a-4bc5-9181-d3ee0ace5f8f.png)
Then I removed the directory vimtex, and installed it by vim-plug again.It only throws the error message:
**No an editor command :VimtexInfo** 

My machine system is MS Windows 10.The information of Neovim's version I use is:
![QQ截图20221002222543](https://user-images.githubusercontent.com/74193816/193459360-83558202-7c5f-4694-bc71-e6800cf3d0ce.png)
I also run command `:checkhealth`.The important information I think was copied .
```
vimtex: health#vimtex#check
========================================================================
## VimTeX
  - OK: Vim version should have full support!
  - ERROR: Zathura is not executable!
  - WARNING: Zathura requires xdotool for forward search!
  - ERROR: |g:vimtex_compiler_method| (`latexrun`) is not executable!
  ## Perl provider (optional)
  - WARNING: No usable perl executable found

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: C:\Users\12483\AppData\Local\Temp\nvim\lsp.log
  - INFO: Log size: 3 KB
## Perl provider (optional)
  - WARNING: No usable perl executable found
## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

```

### Expected behavior

I want to use vimtex plugin to compile my *.tex file, but now it doesn't work.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
**No an editor command :VimtexInfo**
```

**Comment by lervag** [comment]
The first error seems to do with the encoding on your system. I believe a possible solution to that is to ensure you are using UTF-8.

However, the next issue is that VimTeX is not properly installed.

Please notice that the third-part article and the README.md for VimTeX explains some of the common options. It is not meant as something you should blindly copy. Instead, you should try and understand!

Some of the feedback provided by `:checkhealth` should be self evident. E.g., `Zathura is not executable`: You selected it as a viewer, but it is not available on your system. Why do you want Zathura on Windows? Furthermore, you choose `latexrun` as the compiler backend, but you did not install it.

Now, you have not provided the config you use that does not work. You also did not provide any minimal example (I understand the latter is hard for people who are new to these things). Then it becomes hard to help you.

If you host your vimrc or `init.vim` on github, please link to it. Then it is easier to help.

**Comment by tlm12345** [comment]
Thank you for your help!
According to your first advise,I found an effective solution.

1. Open the "Control Panel"
2. Select "region"
3. Under the "Management",select "change settings of System region..."
4. Tick the "Beta version : ...."
![QQ截图20221003083521](https://user-images.githubusercontent.com/74193816/193500413-6c588a0d-9627-46e4-be77-02a96e181876.png)

Then I read the vimtex.txt,and changed my init.vim.Now it's ok.
![QQ截图20221003121412](https://user-images.githubusercontent.com/74193816/193500734-90bd7cc2-1b32-4012-ba34-5f1b22cc3953.png)

**Comment by lervag** [comment]
First, I'm so glad to hear you figured this out. Next, thanks for sharing the path to use UTF-8 encoding - that will be useful for others, I'm sure!
