### ISSUE TITLE
E492: Not an editor command: VimtexInfo error 

### ISSUE THREAD

**Issue by MysticMaestro** [lervag/vimtex#2511]
### Description

Hi. I am running neovim on my arch setup. I am not able to run `:VimtexInfo` which I believe shows me whether vimtex is properly installed or not on my neovim setup
I have used `vim-plug` to install vimtex.  I have `latexmk` and `pdflatex` packages in my system.
I have `texlive-bin` `texlive-core` `texlive-latexextra` and `texmaker` packages installed on my system from the `aur`.
I am also posting my complete `init.vim` file so that you can verify if any other plugin is interfering somewhere: [init.vim](https://pastebin.com/BMAqN4iR)
![image](https://user-images.githubusercontent.com/55852009/194620190-d2783831-e856-4f74-a103-101cf8f45ecb.png)

---

### Minimal.vim

```
" tabs and spaces handling
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" show line numbers
set nu

" remove ugly vertical lines on window division
set fillchars+=vert:\ 

call plug#begin("~/.config/nvim/plugged")

" vimtex
Plug 'lervag/vimtex'

" ultisnips
Plug 'SirVer/ultisnips'

call plug#end()


"VimTeX ---------------------------------

let g:tex_flavor='latex'
let g:vimtex_view_method='zathura'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmg'


set termguicolors
set encoding=utf-8
let fancy_symbols_enabled = 1

```
---
### minimal.tex

```
\documentclass{minimal}
\begin{document}
Hello world!
\end{document}
```

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
E492: Not an editor command: VimtexInfo
```

**Comment by ejmastnak** [comment]
As a first step, could you open your `minimal.tex` file in Neovim, run the command `:scriptnames`, and paste the output here?

**Comment by MysticMaestro** [comment]
Yes I have run the command `:PlugInstall` this is the output:
![image](https://user-images.githubusercontent.com/55852009/194642898-6f303774-8031-4f49-beb4-f992cccf1432.png)

**Comment by ejmastnak** [comment]
Haha glad you figured it out!

**Comment by lervag** [comment]
Thanks for pitching in, @ejmastnak - and glad to hear you figured things out, @MysticMaestro! :)

**Comment by ejmastnak** [comment]
> Thanks for pitching in, @ejmastnak - and glad to hear you figured things out, @MysticMaestro! :)

Happy to help, I've also steered a good bit of issue traffic your way from the blog posts so helping out now and then is the least I can do haha
