### ISSUE TITLE
Compiler messages are hidden by `cmdheight=0` in neovim 0.8+

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2516]
### Description

Neovim 0.8+ introduces the option `cmdheight=0`. However, this obscures the compiler messages and other "command-line area" messages from VimTeX. 

What is the plan to handle this situation?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
N/A
```

**Comment by clason** [comment]
`cmdheight=0` is an experimental feature in Nvim 0.8 that still comes with a large number of regressions. These will eventually be fixed, so there's nothing special that VimTeX needs to do.

**Comment by lervag** [comment]
Thanks, @cason, that is precisely my understanding as well.

**Comment by krishnakumarg1984** [comment]
ok. So, hopefully all command-line area messages shall be visible when the `cmdheight=0` regressions are fixed. Interesting why shipped a buggy feature in a stable release of neovim.

**Comment by lervag** [comment]
I can't comment on this, as I have no idea. I guess @clason may have some thoughts.

**Comment by clason** [comment]
> Interesting to see they shipped a feature (with a priori known?) bugs in a stable release of neovim.

Such is the way of open source; you don't pay or contribute, you don't get to complain. The feature is marked as experimental and works fine in some situations (although we of course can't test all possible plugin -- in particular statusline -- interactions); if it doesn't for you, you do not need to enable it.

Obviously, in Vim the command line and the message area is shared, so removing one removes the other and you'll have to find another way of displaying these messages. One way is `vim.ui_attach()`, but that is experimental as well.

**Comment by krishnakumarg1984** [comment]
Ah. Thank you for explaining. In the future, once the regressions and other bugs with `cmdheight=0` are fixed, is it expected that whenever something is written to that shared screen area, the message will be be given priority and be shown, right?

I use `cmdheight=0` because it helps to somewhat compromise the line lost due to the `winbar` at the top (again, a nvim 0.8+ feature that I have _opted in to_, to show navigation breadcrumbs). 

Is it worthwhile for VimTeX to keep an eye out for `vim.ui.attach()` for (potentially increasing number of) neovim users who might want to use `cmdheight=0` in the future?

Once again, thank you for chipping in with your comments. Since you are a core neovim contributor, your insights are very valuable.

**Comment by clason** [comment]
>  is it expected that whenever something is written to that shared screen area, the message will be be given priority and be shown, right?

It is expected that users that want to use `cmdheight=0` take care of their needs, or use a UI plugin like https://github.com/folke/noice.nvim.

> Is it worthwhile for VimTeX to keep an eye out for vim.ui.attach() for (potentially increasing number of) neovim users who might want to use cmdheight=0 in the future?

No, this has zero to do with VimTeX specifically, so no need to add to developer burden. This is purely between a user and their Neovim config.
