### ISSUE TITLE
Interaction of TOC with mksession command

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2517]
Hello,

The following is my vimrc:

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
set viminfo=%,<800,'100,/50,:100,f1,n./.vim/.viminfogl
function! MakeSession()
    exe "mksession! .vim/sessiongl.vim"
endfunction
function! LoadSession()
    if (filereadable(".vim/sessiongl.vim"))
      exe 'source .vim/sessiongl.vim'
    else
      echo "No session loaded."
    endif
endfunction
au VimEnter * nested :call LoadSession()
au VimLeave * :call MakeSession()
```

The above settings allow the user to save a load a session the next time the file is opened by vim automatically.

I went through the following sequence.

1. Start with an empty `.vim/` folder (no pre-existing session to be loaded)
2. Open a tex file via `vim latextest.tex`
3. Issue `:VimtexTocOpen` The TOC opens fine on the left hand side.
4. Issue `:qa`
    * After this step, the session's data is saved in `.vim/` folder. The above steps are illustrated in this animated video/gif: https://imgur.com/a/oBGYRt3
5. Now, from the terminal, on issuing `vim latextest.tex` the session file is loaded from `.vim/` folder. But, the TOC is not loaded although the window is open and empty. See that image here: https://imgur.com/a/bsb9LKe
6. Now, when I issue command `:VimtexTocToggle` I obtain the following error: `Key not present in dictionary`. See image here: https://imgur.com/a/aSar4dm
    * From here, when I press enter to continue, as suggested in the image, the window set aside for TOC goes away. Now, issuing `:VimtexTocOpen` leads to TOC opening fine.

Is there a way to have TOC interact without this error with the mksession command that saves and restores the content of a vim session?

Thank you.

**Comment by lervag** [comment]
> Is there a way to have TOC interact without this error with the mksession command that saves and restores the content of a vim session?

Thanks for the detailed issue report. I'm sorry to say I really have _no_ idea how to change VimTeX to allow this type of workflow. The content of the TOC is never saved to a file, it is only parsed from the TeX files and displayed in a buffer. As far as I can tell, this means that `:mksession` will not be able to restore it.

So, I'm sorry, I don't think I'll be able to help you much further here. :\

**Comment by TryerGit** [comment]
No problem @lervag

I have tried to have tagbar plugin provide TOC data and it seems to work. Just fyi and for others who may want to have a workflow where vimming up a .tex file automatically restores the previous session from where it was left off (including tagbar being open), here is how I got it to work with tagbar:

vimrc:

```
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
  Plug 'preservim/tagbar'
call plug#end()
let g:tagbar_type_tex = {'ctagstype' : 'latex', 'kinds': ['s:sections', 'g:graphics:0:0','l:labels', 'r:refs', 'p:pagerefs:1:0' ],'sort'    : 0}
let g:tagbar_position = 'topleft vertical'
set viminfo=%,<800,'100,/50,:100,f1,n./.vim/.viminfogl
function! MakeSession()
  exe "mksession! .vim/sessiongl.vim"
endfunction
function! LoadSession()
  if (filereadable(".vim/sessiongl.vim"))
    exe 'source .vim/sessiongl.vim'
  else
    echo "No session loaded."
  endif
endfunction
" Adding automatons for when entering or leaving Vim
au VimEnter * nested :call LoadSession()
au VimLeave * :call MakeSession()
```

Tagbar needs a `~/.ctags` file the contents of which are:

```
--langdef=latex
--langmap=latex:.tex
--regex-latex=/^\\tableofcontents/TABLE OF CONTENTS/s,toc/
--regex-latex=/^\\frontmatter/FRONTMATTER/s,frontmatter/
--regex-latex=/^\\mainmatter/MAINMATTER/s,mainmatter/
--regex-latex=/^\\backmatter/BACKMATTER/s,backmatter/
--regex-latex=/^\\bibliography\{/BIBLIOGRAPHY/s,bibliography/
--regex-latex=/^\\part[[:space:]]*(\[[^]]*\])?[[:space:]]*\{([^}]+)\}/PART \2/s,part/
--regex-latex=/^\\part[[:space:]]*\*[[:space:]]*\{([^}]+)\}/PART \1/s,part/
--regex-latex=/^\\chapter[[:space:]]*(\[[^]]*\])?[[:space:]]*\{([^}]+)\}/CHAP \2/s,chapter/
--regex-latex=/^\\chapter[[:space:]]*\*[[:space:]]*\{([^}]+)\}/CHAP \1/s,chapter/
--regex-latex=/^\\section[[:space:]]*(\[[^]]*\])?[[:space:]]*\{([^}]+)\}/\. \2/s,section/
--regex-latex=/^\\section[[:space:]]*\*[[:space:]]*\{([^}]+)\}/\. \1/s,section/
--regex-latex=/^\\subsection[[:space:]]*(\[[^]]*\])?[[:space:]]*\{([^}]+)\}/\.\. \2/s,subsection/
--regex-latex=/^\\subsection[[:space:]]*\*[[:space:]]*\{([^}]+)\}/\.\. \1/s,subsection/
--regex-latex=/^\\subsubsection[[:space:]]*(\[[^]]*\])?[[:space:]]*\{([^}]+)\}/\.\.\. \2/s,subsubsection/
--regex-latex=/^\\subsubsection[[:space:]]*\*[[:space:]]*\{([^}]+)\}/\.\.\. \1/s,subsubsection/
--regex-latex=/^\\includegraphics[[:space:]]*(\[[^]]*\])?[[:space:]]*(\[[^]]*\])?[[:space:]]*\{([^}]+)\}/\3/g,graphic+listing/
--regex-latex=/^\\lstinputlisting[[:space:]]*(\[[^]]*\])?[[:space:]]*(\[[^]]*\])?[[:space:]]*\{([^}]+)\}/\3/g,graphic+listing/
--regex-latex=/\\label[[:space:]]*\{([^}]+)\}/\1/l,label/
--regex-latex=/\\ref[[:space:]]*\{([^}]+)\}/\1/r,ref/
--regex-latex=/\\pageref[[:space:]]*\{([^}]+)\}/\1/p,pageref/
--langdef=bib
--langmap=bib:.bib
--regex-bib=/^@[A-Za-z]+\{([^,]*)/\1/b,bib/
```

With this setup, I repeated the same steps as I did in the OP, this time with `:TagbarToggle` which opens up the Tagbar which for my purposes is as good as a ToC. Then, I leave the Tagbar buffer/window open and close the file with `:qa!`. This saves the session information and the state of various buffers. See animaged video/gif of that here: https://imgur.com/a/idoqmtW

Then, on opening up the tex file again, this previous stated is restored with the same Tag information as we left off with when we closed previously. See that image on second opening here: https://imgur.com/a/DcQJgWd

Thank you.

**Comment by TryerGit** [comment]
Furthermore, I saw your edits on my OP. Actually, the session information is opened in a .vim subfolder in my current directory where the .tex file resides. This can be anywhere on my computer and not the ~/.vim directory at the home directory.

**Comment by lervag** [comment]
> No problem @lervag

:thumbs:

> I have tried to have tagbar plugin provide TOC data and it seems to work. Just fyi and for others who may want to have a workflow where vimming up a .tex file automatically restores the previous session from where it was left off (including tagbar being open), here is how I got it to work with tagbar: …

Thanks for sharing!

> Furthermore, I saw your edits on my OP. Actually, given my original vimrc the session information is opened in a .vim subfolder in my current directory where the .tex file resides. …

Yes, sorry about that. I made an initial edit to fixup some minor formatting, but I also made the mistake you mentioned here. However, I realized I was wrong when I tested and reverted it.
