### ISSUE TITLE
Have `\includeonly` in the default setting of `g:vimtex_include_indicators`

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2519]
### Description

Currently, `g:vimtex_include_indicators` contains the default value of `['input', 'include']`. It is perhaps worthwhile to additionally have `\includeonly` as the default. 

https://latexref.xyz/_005cinclude-_0026-_005cincludeonly.html 

When authoring chapters of a large book, maybe we want to see only some related chapters, and `\includeonly` is very handy.

### Do you use a latexmkrc file?

N/A

### VimtexInfo

```yaml
N/A
```

**Comment by AsbjornPreuss** [comment]
This seems to add some problems with the TODO implementation, where all TODOs will be shown, but the TODOs in files, that are \includeonly, will show up twice. Is this the intended functionality? Is there someway to avoid it?
![vimtex_TODO_includeonly](https://github.com/user-attachments/assets/b37e1e28-69a9-4f27-a84f-ce25bd4b976c)

**Comment by lervag** [comment]
Hmm... considering this more closely, I think you may be right that it was wrong to add `\includeonly` to the indicators option. This command does _not_ include anything, it is only used as a "guard" for the `\include` command.

Still, it would be nice with a new issue that references this one and that gives a simple example.
