### ISSUE TITLE
For the Toc, help instructions/legend keys could be moved to the lower half of the toc window and folded away with the folds closed by default 

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2520]
**Is your feature request related to a problem? Please describe it.**
Even for a simple document, when opening the toc, the real toc headings start way down at the bottom. The top half of the toc window (where most eyeballs/brain power is focused; this is supported by pedagogical research) is cluttered with help instructions/legend keys (I know there are options to disable them), and the real TOC starts way at the bottom.

![image](https://user-images.githubusercontent.com/15239509/196186298-64427eda-5828-47f3-808b-5de0d9cb7578.png)
 

**Describe the solution you'd like**
- Move the legend and keymap instructions to the lower half of the toc window (or make their position customisable by providing an option key for users)
- Fold it away by default (and provide options for enabling/disabling these folds). 

This solution will remain compatible with the current vimtex options and behaviour.

This will result in a better UX.

**Comment by lervag** [comment]
Hmm. I'm not sure about this one. For new users, it may be confusing to have the help at the _bottom_. Experienced users can (and probably should) just hide the help text?

I don't like adding new options unless I see a clar value, and right now I am not sure.

Could you explain why you think the ability to hide (and to start hidden) is not sufficient?

**Comment by krishnakumarg1984** [comment]
Here's another idea. If not folding, maybe the pop-up/floating window capabilities of vim/neovim can be considered. Many plugins take advantage of this for help text. Examples include `vimspector` in vim, and `mason` in neovim.

Here's a screenshot for an analogous use-case taken from `mason`. There is a very clear text which says Press `g?` to show help text.
![image](https://user-images.githubusercontent.com/15239509/196280455-5910b512-79cc-4dba-acb8-12e6ebc62cbe.png)

And when we show `g?`, the same space is now occupied by a help menu

![image](https://user-images.githubusercontent.com/15239509/196280903-9bf61d35-b16c-4beb-b9eb-f219a7cf9d83.png)
And the very first entry in the help is on how to toggle the help text i.e. `g?`. Very thoughtful indeed. 

It doesn't have to be floating/pop-up. We can continue with using splits for the ToC menu, but with the above UX paradigm. It is visually less jarring  than text moving up and down to reveal/hide the help menu.

**Comment by lervag** [comment]
Hmm, yes; I think having simply `press h for help` at the top of the TOC is quite clever. So, instead of this (current version):

```
<Esc>/q  Close
<Space>  Jump
<Enter>  Jump and close
      r  Refresh
      h  Toggle help text
      t  Toggle sorted TODOs
    -/+  Decrease/increase ToC depth (for content layer)
    f/F  Apply/clear filter
      s  Hide numbering

Layers:  L  label+
         I  include+
         T  todo+
         C  content+

[ax] 1       Short title
[ay]         eq:test
[az] 2       section 2
[ba] 2.1     \textcolor{red}{Very important title}
[bb]         sec:test2
[bc] 2.2     Test section 1
[bd]         sec:TesSec1
[be]         tex incl: test/example-book-multifile/test.tikz
[bi]         fig:example1
[bl] 2.2.1   sub
[bm] 2.2.1.1 subsub
[bo] 2.2.2   Test sub section 1
[bp] 2.3     $\alpha$
[bu] 2.3.1   Test sub section 1
[bv] 2.3.2   Test sub section 2
...
```

We'll have this:

```
      h  Toggle help text
<Esc>/q  Close
<Space>  Jump
<Enter>  Jump and close
      r  Refresh
      t  Toggle sorted TODOs
    -/+  Decrease/increase ToC depth (for content layer)
    f/F  Apply/clear filter
      s  Hide numbering

Layers:  L  label+
         I  include+
         T  todo+
         C  content+

[ax] 1       Short title
[ay]         eq:test
[az] 2       section 2
[ba] 2.1     \textcolor{red}{Very important title}
[bb]         sec:test2
[bc] 2.2     Test section 1
[bd]         sec:TesSec1
[be]         tex incl: test/example-book-multifile/test.tikz
[bi]         fig:example1
[bl] 2.2.1   sub
[bm] 2.2.1.1 subsub
[bo] 2.2.2   Test sub section 1
[bp] 2.3     $\alpha$
[bu] 2.3.1   Test sub section 1
[bv] 2.3.2   Test sub section 2
...
```

And if the help text is hidden, we have this:

```
Press h to toggle help text.

[ax] 1       Short title
[ay]         eq:test
[az] 2       section 2
[ba] 2.1     \textcolor{red}{Very important title}
[bb]         sec:test2
[bc] 2.2     Test section 1
[bd]         sec:TesSec1
[be]         tex incl: test/example-book-multifile/test.tikz
[bi]         fig:example1
[bl] 2.2.1   sub
[bm] 2.2.1.1 subsub
[bo] 2.2.2   Test sub section 1
[bp] 2.3     $\alpha$
[bu] 2.3.1   Test sub section 1
[bv] 2.3.2   Test sub section 2
 ...
```

The option `g:vimtex_toc_config.show_help` would still determine if the help text is displayed by default, and to avoid a breaking change, I think it is good to still show the text by default. But if you set it to 0, then having the initial helpful line on top should resolve your need here, if I'm not wrong?

Going to floating windows and similar is interesting, but requires more thought and work since I still keep things working in both Vim and neovim. I'll not start work on that kind of things just yet.

**Comment by krishnakumarg1984** [comment]
"Floating" Windows work on both vim and neovim. In vim, they are called popup windows I think.

Yes. It would be an improvement if we go with the option to toggle the help text, keeping it on by default, and providing an option for users to keep it initially hidden. 

Whilst that would be a nice improvement, perhaps can you hide the actual ToC and unhide it based on the help toggle?

**Comment by krishnakumarg1984** [comment]
This is nice. Thank you!

**Comment by lervag** [comment]
No problem; thanks for the suggestions!
