### ISSUE TITLE
vimtex class and package completion should consider `\PassOptionsToClass` and `\PassOptionsToPackage`

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2521]
### Description

The documentation says:
>Package, documentclass, and bibliography style completion are available for
the `\usepackage{`, `\documentclass{`, and `\bibliographystyle` commands,
respectively.

However, it should also be available for `\PassOptionsToClass` and `\PassOptionsToPackage`

### Do you use a latexmkrc file?

N/A

### VimtexInfo

```yaml
N/A
```

**Comment by krishnakumarg1984** [comment]
Thank you!

**Comment by lervag** [comment]
My pleasure :)
