### ISSUE TITLE
"Compile selected lines" works but cannot open a viewer when the build_dir of vimtex_compiler_latexmk is set

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2522]
### Description

With the following configuration,

```vim
  let g:vimtex_compiler_latexmk = {
  \ 'build_dir' : 'build',
  \ 'callback' : 1,
  \ 'continuous' : 1,
  \ 'executable' : 'latexmk',
  \ 'hooks': [function('Callback')],
  \ 'options' : [
  \   '-verbose',
  \   '-recorder',
  \   '-file-line-error',
  \   '-synctex=1',
  \   '-interaction=nonstopmode',
  \ ]
  \}
```

Visually selecting a few lines of latex source code, and performing a `<leader>lL` triggers a successful compilation of the selected lines. However, the view command fails with the error message:
>VimTeX: viewer cannot read the PDF file.

This is with the default settings, wherein the viewer is supposed to automatically open and do a forward search. 

Setting the `'build_dir'` back to `''` ensures a successful compilation of selected lines and immediately opens the PDF viewer

### Steps to reproduce

Please see description above

### Do you use a latexmkrc file?

N/A

### VimtexInfo

```yaml
N/A?
```

**Comment by lervag** [comment]
Interesting. I'll look into this when I get the time!

**Comment by lervag** [comment]
> With the following configuration,
> 
> ```viml
>   let g:vimtex_compiler_latexmk = {
>   \ 'build_dir' : 'build',
>   \ 'callback' : 1,
>   \ 'continuous' : 1,
>   \ 'executable' : 'latexmk',
>   \ 'hooks': [function('Callback')],
>   \ 'options' : [
>   \   '-verbose',
>   \   '-recorder',
>   \   '-file-line-error',
>   \   '-synctex=1',
>   \   '-interaction=nonstopmode',
>   \ ]
>   \}
> ```

1. You don't need to set values to their defaults. Thus, you can simplify the above to this:

    ```viml
      let g:vimtex_compiler_latexmk = {
            \ 'build_dir' : 'build',
            \ 'hooks': [function('Callback')],
            \ 'options' : [
            \   '-verbose',
            \   '-recorder',
            \   '-file-line-error',
            \   '-synctex=1',
            \   '-interaction=nonstopmode',
            \ ]
            \}
    ```

2. What is the `'Callback'` function?
3. I believe the callback function and `-recorder` option is not relevant to this issue anyway, which means you could probably simplify (for this issue) to

    ```viml
      let g:vimtex_compiler_latexmk = { 'build_dir' : 'build' }
    ```

**Comment by lervag** [comment]
I believe this is fixed now, please test.

**Comment by krishnakumarg1984** [comment]
@lervag  Tested, and while it compiles the selected lines, two PDF viewers are opened

**Comment by krishnakumarg1984** [comment]
err.... It also creates a file `main_selected_vimtex.tex` in my project root directory.

**Comment by lervag** [comment]
> @lervag Tested, and while it compiles the selected lines, two PDF viewers are opened

Not on my end. Can you make a minimal example for that?

**Comment by lervag** [comment]
> err.... It also creates a file `main_vimtex_selected.tex` in my project's root.

Ah, yes. I guess you'd expect the temporary file to be created inside the build_dir. Agreed, I'll update accordingly.
