### ISSUE TITLE
Compiler callback lines for latexmk do not work for neovim

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2523]
### Description

VimTex's documenation says:

> A particular set of options are very convenient for a good coupling between
> `latexmk` and Vim: `$compiling_cmd`, `$success_cmd`, and `$failure_cmd`. These
> options can be used to specify commands that are run by `latexmk` before and
> after compilation. This is used by VimTeX to achieve callbacks after
> compilation has finished through |vimtex#compiler#callback| with something
> like this: >
> 
>   $compiling_cmd = "vim --remote-expr 'vimtex#compiler#callback(1)'";
>   $success_cmd = "vim --remote-expr 'vimtex#compiler#callback(2)'";
>   $failure_cmd = "vim --remote-expr 'vimtex#compiler#callback(3)'";

However, neovim (the `nvim` executable) does not have the `---remote-expr` option available. Can the docs be updated to provide something analogous for neovim?

### Do you use a latexmkrc file?

N/A

### VimtexInfo

```yaml
N/A
```

**Comment by krishnakumarg1984** [comment]
@lervag Should we remove those lines from our latexmkrc?

**Comment by lervag** [comment]
Yes, there is no need for these lines unless you use `latexmk` in the terminal (without VimTeX).
