### ISSUE TITLE
How to disable highlighting matching delimiter?

### ISSUE THREAD

**Issue by joshcho** [lervag/vimtex#2524]
If I place cursor on the line starting with \begin below,
```
\begin{align}
aRb
\end{align}
```
I get matching delimiter line starting with \end highlighted. How do I disable this feature? I am doing `hi MatchParen ctermbg=NONE` for now.

**Comment by lervag** [comment]
You can disable with `let g:vimtex_matchparen_enabled = 0`. I recommend that you also read the related docs with `:help vimtex_matchparen_enabled`.
