### ISSUE TITLE
VimTex interaction with MuComplete

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2525]
Hello,

I don't know if this is an issue with VimTex or if it is with MuComplete. FYI...I have raised an issue with MuComplete folks [here](https://github.com/lifepillar/vim-mucomplete/issues/203) as well.

Essentially, `\cite{` automatically triggers a suggested list of bibkeys, while `\ref{` does not trigger a suggested list of `\label{}`s. Copy pasting the issue from there here also as I am unsure which plugin could be the root cause.

----

My `vimrc` is thus:

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
Plug 'lifepillar/vim-mucomplete'
call plug#end()

set completeopt+=menuone
set completeopt+=noselect
let g:mucomplete#enable_auto_at_startup = 1

let g:mucomplete#can_complete = {}
let g:mucomplete#can_complete.tex = { 'omni': { t -> t =~# g:vimtex#re#neocomplete . '$' } }
```

I have taken the suggestion for `can_complete.tex` from https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt with respect to having mucomplete interact with VimTex.

I have the following content in `bibfile.bib`:
```bib
@Article{somekey,
  title     = {A super awesome paper}
}
```

With this configuration, I am able to have mucomplete work fine for triggering automatic completion suggestion when `\cite{` is typed  and the option provided is `somekey` from the bibliography file.

However, on typing `\ref{` in the hope of triggering automatic completion suggestions of equation labels in the `.tex` file, it fails to work.

Please see the animated gif of the .`tex` file : https://imgur.com/a/XOv167i

Is it possible to help me figure out why this could be the case?

----

In case you would like to replicate at your end, here is the content of the .tex file shown in the animated gif:

```tex
\documentclass[11pt]{article}

\usepackage{amsmath}

\begin{document}

\begin{alignat}{2}
	\text{ }& asdfasdf              &&\quad\nonumber\\
	\text{ }&89999\times 45\leq 88	&&\quad \forall\label{eq:1}\\
		&abc	                &&\quad\exists\label{eq:okay}\\
		&\times x	        &&\quad\forall\nonumber\\
		&abcd                   &&\quad\nonumber
\end{alignat}

\bibliographystyle{apalike}
\bibliography{bibfile.bib}

\end{document}

```

Output of `:echo g:vimtex#re#neocomplete` is

`\v\\%(%(\a*cite|Cite)\a*\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|%(\a*cites|Cites)%(\s*\([^)]*\)){0,2}%(%(\s*\[[^]]*\]){0,2}\s*\{[^}]*\})*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|bibentry\s*\{[^}]*|%(text|block)cquote\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|%(for|hy)\w*cquote\*?\{[^}]*}%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|defbibentryset\{[^}]*}\{[^}]*|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)|hyperref\s*\[[^]]*|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*|%(include%(only)?|input|subfile)\s*\{[^}]*|([cpdr]?(gls|Gls|GLS)|acr|Acr|ACR)\a*\s*\{[^}]*|(ac|Ac|AC)\s*\{[^}]*|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*|%(usepackage|RequirePackage|PassOptionsToPackage)%(\s*\[[^]]*\])?\s*\{[^}]*|documentclass%(\s*\[[^]]*\])?\s*\{[^}]*|begin%(\s*\[[^]]*\])?\s*\{[^}]*|end%(\s*\[[^]]*\])?\s*\{[^}]*|\a*)`

Thank you.

**Comment by lervag** [comment]
> I don't know if this is an issue with VimTex or if it is with MuComplete …
> … while `\ref{` does not trigger a suggested list of `\label{}`s.

Thanks for writing thorough issue descriptions! It makes it easy for me to understand your problem and to look into it.

In this case, I believe the problem is not an actual issue, but instead a limitation you may not have been aware of: label completion only works as long as your document is compiled, because it relies on parsing the `.aux` file. With your example, I can 1) reproduce your issue when the document is not compiled, and 2) achieve automatic label completion with `\ref{` after having compiled with `\ll`.

Can you check and see if this in fact resolves the issue for you?

**Comment by lervag** [comment]
Notice that this is also documented. See `:help vimtex-complete-labels`:

```
COMPLETE LABELS                                        *vimtex-complete-labels*

Label completion is triggered by `\ref{` commands.  The completion parses every
relevant aux file to gather the completion candidates.  This is important,
because it means that the completion only works when the LaTeX document has
been compiled.
```

**Comment by TryerGit** [comment]
Yes, indeed with the presence of the `.aux` file, autocompletion works as expected.
