### ISSUE TITLE
Run :VimtexClean on exit

### ISSUE THREAD

**Issue by nsirolli** [lervag/vimtex#253]
Hi,

It would be nice if the plugin could run `:VimtexClean` (or `:VimtexClean!`) automatically when closing the tex file.

Thanks,
Nico.

**Comment by lervag** [comment]
I found this to be harder than I first thought. I will look into it later, in the mean time I hope you can live without the feature.

**Comment by nsirolli** [comment]
Sure! I can do the cleaning myself in the mean time.

**Comment by Eisfreak7** [comment]
Maybe I'm overlooking something, but for me
```
augroup vimtex_config
  autocmd!
  autocmd Filetype tex autocmd BufUnload <buffer> VimtexClean
augroup END
```
Works pretty well.

**Comment by lervag** [comment]
@Eisfreak7 It works well if you are working on single file projects. If you are working on a multi-file project with several buffers open, this does not work that well, since it will call `VimtexClean` when you close one of the buffers of the project. But perhaps it works for @nsirolli?

I plan to add some user events or hooks that will allow custom commands to be run before exiting a vimtex project, for instance. However, it needs some refactoring and updates to much of the code, and so I have not had the time to do it yet.

**Comment by nsirolli** [comment]
It works for me, thank you @Eisfreak7!

**Comment by lervag** [comment]
I've pushed an update that adds a `VimtexQuit` event. This event is triggered when the last file of a LaTeX project is closed. Note, though, that in this scope, the commands are not available. The functions are, though, so the following will work as you want:

```vim
augroup vimtex_config
  autocmd!
  autocmd User VimtexQuit call vimtex#latexmk#clean(0)
augroup END
```

**Comment by nsirolli** [comment]
I'm afraid this update is not working for me. This is the setting here.

OS: Debian 8.2

Vim version: 7.4.576

Vim settings:

```
let g:tex_flavor = 'latex'
let g:vimtex_fold_enabled = '0'
let g:vimtex_fold_automatic = '0'
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique @pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'

augroup vimtex_config
  autocmd!
  autocmd User VimtexQuit call vimtex#latexmk#clean(0)
augroup END
```

Steps performed:
* open vim
* open tex file
* run VimtexComplie
* quit vim

Expected result: auxilary latex compilation files get removed

Actual result: auxilary latex compilation files do not get removed

**Comment by lervag** [comment]
Hi. I've made some minor tweaks. Could you please try again, now with 

```vim
augroup vimtex_config
  autocmd!
  autocmd User VimtexEventQuit call vimtex#latexmk#clean(0)
augroup END
```

**Comment by lervag** [comment]
Ah, I see. I did not really quit my Vim session, I only closed the buffer. I think it should work with the commit I'm pushing now.

**Comment by nsirolli** [comment]
It works now :)

**Comment by lervag** [comment]
Great, glad to hear it!

lør. 7. nov. 2015, 23.47 skrev Nicolás Sirolli <notifications@github.com>:

**Comment by Carslake22** [comment]
This fix doesn't work for me, does it still work after using VimtexStop

**Comment by andymass** [comment]
@Carslake22 the function name changed:
```vim
  augroup vimtex_config
    au!
    au User VimtexEventQuit call vimtex#compiler#clean(0)
  augroup END
```

**Comment by Carslake22** [comment]
awesome thanks

**Comment by lazyzyf** [comment]
does anyone know how to do the same in init.lua file rather than .vimrc file?

**Comment by lervag** [comment]
Yes:

```lua
local augroup = vim.api.nvim_create_augroup("vimtex_config")
vim.api.nvim_create_autocmd("User", {
  pattern = "VimtexEventQuit",
  group = augroup,
  desc = "Clean files on exit.",
  command = [[ call vimtex#compiler#clean(0) ]],
})
```

**Comment by lazyzyf** [comment]
Great, thanks, Lervag, I did a minor change to the first line, now it works.
`local augroup = vim.api.nvim_create_augroup("vimtex_config", { clear = true })`

**Comment by lervag** [comment]
Yes, sorry; you don't need `clear = true` (because it is the default), but you do need an empty table since the function takes two arguments.

**Comment by Jihillestad** [comment]
I tried this, but cleaning is not working when quitting neovim.

```lua
return {
  "lervag/vimtex",
  -- event = "BufEnter *.tex",
  init = function()
    vim.g.vimtex_view_method = "skim"
    vim.g.vimtex_skim_sync = 1
    vim.g.vimtex_skim_activate = 1
  end,

  config = function()
    local au_group = vim.api.nvim_create_augroup("vimtex_events", {})

    vim.api.nvim_create_autocmd("User", {
      pattern = "VimtexEventQuit",
      group = au_group,
      command = "VimtexClean",
    })
  end,
}

```

**Comment by lervag** [comment]
No need to use both `init` and `config` function here. Just put all of it in `init`. Here; I've also fixed a couple of minor bugs in your settings:

```lua
return {
  "lervag/vimtex",
  init = function()
    vim.g.vimtex_view_method = "skim"
    vim.g.vimtex_view_skim_sync = 1
    vim.g.vimtex_view_skim_activate = 1

    local au_group = vim.api.nvim_create_augroup("vimtex_events", {})

    vim.api.nvim_create_autocmd("User", {
      pattern = "VimtexEventQuit",
      group = au_group,
      command = "VimtexClean",
    })
  end,
}
```

Now, if this doesn't work, then please, open a new issue and describe your problem in more detail.

**Comment by lervag** [comment]
Also, if you read `:help VimtexEventQuit`, you may have missed the final note:

```vimdoc
  *VimtexEventQuit*
    This event is triggered when the last buffer for a particular LaTeX project
    is wiped (for example, using `:bwipeout`) and when Vim is quit.  The event
    may be used, for instance, to cleanup up auxiliary build files or close
    open viewers (see Examples below).  With Vim defaults, this event is not
    triggered when using `:quit` or `:bdelete` since these commands merely hide
    the buffer.  In multi-file projects, the event may be triggered multiple
    times.  The `b:vimtex` variable contains context data for the quitting
    file or project.  For example, `b:vimtex.tex` identifies the tex file being
    wiped, or the main tex file of a multi-file project.

    Note: Commands such as |:VimtexClean| does not always work as expected
          with this event. This is because, when quitting vim, the current
          buffer does not necessarily have filetype "tex".
```
