### ISSUE TITLE
Ability to override foldtext function

### ISSUE THREAD

**Issue by petobens** [lervag/vimtex#2532]
Hi! I would like to change the fold text function to resemble the image in my markdown file (i,e show line numbers, use `+---` for levels, etc):
![image](https://user-images.githubusercontent.com/2583971/198501205-0513b3f6-095a-42d3-874f-dfece48517fd.png)

I tried simply setting:
```lua
vim.opt_local.foldtext = foldtext()
```
which of course didn't work. Can I somehow easily override that function to achieve something like the image above? Currently my folding looks like:
![image](https://user-images.githubusercontent.com/2583971/198501333-0bdc917f-24db-424a-b451-23dfd527694f.png)

Thanks in advance!

**Comment by lervag** [comment]
A simple way to achieve this is to set the option in your personal `after/ftplugin/tex.vim` (e.g. `~/config/nvim/after/ftplugin/tex.vim`). This file is sourced _after_ the regular filetype plugins, which means the option would override the setting used by VimTeX.

**Comment by petobens** [comment]
Great. Thanks for the tip... One additional question (bug?).. if I set my vimtex folding config like so:
```lua
vim.g.vimtex_fold_enabled = 1
vim.g.vimtex_fold_manual = 1 -- only compute folds on demand
vim.g.vimtex_fold_types = { -- only fold preamble, parts and sections
    preamble = { enabled = 1 },
    sections = { enabled = 1 },
    parts = { enabled = 1 },
    comments = { enabled = 0 },
    envs = { whitelist = { 'frame' } },
    env_options = { enabled = 0 },
    item = { enabled = 0 },
    markers = { enabled = 0 },
    cmd_single = { enabled = 0 },
    cmd_single_opt = { enabled = 0 },
    cmd_multi = { enabled = 0 },
    cmd_addplot = { enabled = 0 },
}
```
and then have a `foo.tex` sample file
```tex
\documentclass{article}

\begin{document}

\section{Foo}

\begin{enumerate}
  \item Foo bar
  \item asdjaskdla asjd laskd asjd klasd asjdkl asdj askld asjdaslkd asj daskld
    asj lkas
  \item  Blah
\end{enumerate}

\end{document}
```
For some reason enumerate items that span multiple lines get folded (see image below). Is it possible to avoid that?

![fold_tex](https://user-images.githubusercontent.com/2583971/198896688-9f7ad756-03bf-4d41-9c1e-06cefcfbbc58.gif)

**Comment by lervag** [comment]
> Great. Thanks for the tip... One additional question (bug?).. if I set my vimtex folding config like so:
> 
> ```lua
> vim.g.vimtex_fold_enabled = 1
> vim.g.vimtex_fold_manual = 1 -- only compute folds on demand
> vim.g.vimtex_fold_types = { -- only fold preamble, parts and sections
>     preamble = { enabled = 1 },
>     sections = { enabled = 1 },
>     parts = { enabled = 1 },
>     comments = { enabled = 0 },
>     envs = { whitelist = { 'frame' } },
>     env_options = { enabled = 0 },
>     item = { enabled = 0 },
>     markers = { enabled = 0 },
>     cmd_single = { enabled = 0 },
>     cmd_single_opt = { enabled = 0 },
>     cmd_multi = { enabled = 0 },
>     cmd_addplot = { enabled = 0 },
> }
> ```
> 
> and then have a `foo.tex` sample file
> 
> ```
> \documentclass{article}
> 
> \begin{document}
> 
> \section{Foo}
> 
> \begin{enumerate}
>   \item Foo bar
>   \item asdjaskdla asjd laskd asjd klasd asjdkl asdj askld asjdaslkd asj daskld
>     asj lkas
>   \item  Blah
> \end{enumerate}
> 
> \end{document}
> ```

> For some reason enumerate items that span multiple lines get folded (see image below). Is it possible to avoid that?

Yes. You had a type in your config. The following config should work (and is essentially equivalent with what you had). Notice that you don't need to set things unless you change from the default values.

```lua
vim.g.vimtex_fold_enabled = 1
vim.g.vimtex_fold_manual = 1
vim.g.vimtex_fold_types = {
    envs = { whitelist = { 'frame' } },
    env_options = { enabled = 0 },
    items = { enabled = 0 },
    markers = { enabled = 0 },
    cmd_single = { enabled = 0 },
    cmd_single_opt = { enabled = 0 },
    cmd_multi = { enabled = 0 },
    cmd_addplot = { enabled = 0 },
}
```

**Comment by petobens** [comment]
Oops. Thanks!!

**Comment by lervag** [comment]
No problem.
