### ISSUE TITLE
ctags syntax for multiple tex files sourced from main .tex file

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2533]
Hello,

I am not sure if there is a `vimtex` feature addressing this. I was hoping to get some guidance regarding this.

Previously, I had one big `.tex` file containing everything and my `.vimrc` was set to generate `tags` file on save via the following command:

```vim
let g:ctagscall = "ctags ".expand("%")." allreferences.bib"
:autocmd BufWritePost * call system(g:ctagscall)
```

So, if my big `.tex` file containing everything was `fullpaper.tex`, the above call would become `ctags fullpaper.tex allreferences.bib` both in the current folder. Only `allreferences.bib` was hardcoded into the `vimrc`.

Everything worked fine. However, I want to now move to a more streamlined structure where I have a small `main.tex` which contains only the preamble and other stuff and calls individual `.tex` files. So, `main.tex` will have:

```
\input{section1}
\input{section2}
```

and so on, where `section1.tex` and `section2.tex` are separate `.tex` files. Is there a particular way so that I can generate tags for the entire project?

So, essentially, I want to have `ctags` run `ctags main.tex section1.tex section2.tex allreferences.bib` without hardcoding `section1.tex` or `main.tex` or even `allreferences.bib` and so on, into the `.vimrc`. Is this possible directly via an appropriate command in `.vimrc` or is there a `vimtex` feature that achieves the same result for multi-file `.tex` projects?

At present, my `main.tex` looks like so:

```tex
preamble stuff

\begin{document}

\title{Title} \maketitle

\begin{abstract}
Some nice abstract
\end{abstract}

\input{section1}
\input{section2}

\bibliographystyle{apalike}
\bibliography{allreferences.bib}

\end{document}
```

**Comment by lervag** [comment]
> I am not sure if there is a `vimtex` feature addressing this. I was hoping to get some guidance regarding this.

No, there is no VimTeX feature relevant here, but I can try to give some advice.

> Previously, I had one big `.tex` file containing everything and my `.vimrc` was set to generate `tags` file on save via the following command:
>
> ...
>
> and so on, where `section1.tex` and `section2.tex` are separate `.tex` files. Is there a particular way so that I can generate tags for the entire project?

Personally, I've found [Gutentags](https://bolt80.com/gutentags/) to be an excellent solution to project wide ctags. I believe it may solve your issue here as well. There's some relevant info in the VimTeX docs, actually, see `:help vimtex-af-tag-nav`. The related faq entries are probably also of interest. `:help vimtex-faq-tags` suggests some `~/.ctags` configuration that can be useful.

**Comment by TryerGit** [comment]
@lervag  Thanks.

My experience with autocompletion with multiple separate files leaves a lot to be desired. For e.g., a `\label{eq:firstequation}` in `section1.tex` is *invisible* to the `section2.tex` buffer when I type `\ref{eq:|}` even with gutentags. It is not clear to me how to have MUComplete/VimTeX help out here. I may have to go back to the single `.tex` file.

**Comment by lervag** [comment]
> @lervag Thanks.

No problem :)

> My experience with autocompletion with multiple separate files leaves a lot to be desired. For e.g., a `\label{eq:firstequation}` in `section1.tex` is _invisible_ to the `section2.tex` buffer when I type `\ref{eq:|}` even with gutentags.

VimTeX has label completion (see `:help vimtex-complete-labels`). It should work well for multi file projects. I don't know much about MuComplete, but I know it works as expected with normal omnicompletion (triggered by `<c-x><c-o>`). If you have a problem with this, then first check that it works _without_ MuComplete. If it does, then the problem is with MuComplete or with how you've set things up. This is what I expect.

**Comment by TryerGit** [comment]
After redoing things a bit, without gutentags, with how I was handling ctags as before, things seem to be working fine even with a multi file project.

Thanks!

**Comment by lervag** [comment]
Glad to hear it works.

Notice, though; gutentags is very useful for the tags navigation features, so I still recommend it!

**Comment by TryerGit** [comment]
My current ctags setup (let me call this "plain old ctags usage") generates a `tags` file in the project folder and it "scrapes" main.tex, section1.tex .... section10.tex as well as the .bib file. So, I am still able to issue `Ctrl]` to navigate to a location that has been scraped. Furthermore, VimTeX's TOC feature also lists many of these tags as well. If you don't mind, could you indicate a workflow that would benefit from gutentags not already covered by VimTeX's TOC and "plain old ctags usage" described above?

**Comment by lervag** [comment]
No, it seems your "plain old ctags usage" is sufficient here. Gutentags is just a way to simplify the plain old ctags usage. :)
