### ISSUE TITLE
Incorrect help tag location for latexmk in feature overview

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2535]
In the feature overview section, the first line is: "Document compilation with `latexmk`, `latexrun`, `tectonic` or `arara`".

However, navigating to the `latexmk` tag takes us to the wrong location. Line 6316 in the changelog section. Specifically, `*g:latex_latexmk_autojump*`

Similarly, the first line of the `latexrun` description tag takes us to the wrong location. > See LaTeX run. Run latexrun. When following the `LaTeX run` tag, it takes us to `quickfix.txt` under `errorformat-latex` section.

**Comment by lervag** [comment]
There is no latexmk tag in that line. Help tags are created with `|`s, e.g. `|latexmk|`. In that line, I've used `` `latexmk` ``, and it's not meant as a tag.

**Comment by lervag** [comment]
![image](https://user-images.githubusercontent.com/998898/198835978-8a437a99-2291-4160-95c1-bbc1c37c6632.png)

Notice how the tags are colored blue, whereas the words you are talking about are cursive and colored grey.

**Comment by krishnakumarg1984** [comment]
Understood. But it is confusing when some of them jump and go to tags. For example, the `latexrun`, `tectonic` and `arara` all jump to the right section. The viewer bullet points also jump to the right place. For the completion subheading, it doesn't work for the first bullet point, but works for the 2nd buller point. 

Since the documentation admits that it is too long for a single readthrough, and that parts of it can be used as a reference, a good place to quickly navigate to relevant places is the feature overview section using tags.

**Comment by lervag** [comment]
> Understood. But it is confusing when some of them jump and go to tags. For example, the latexrun, tectonic and arara all jump to the right section.

Well, IMHO, this is more a confusion about how Vim's tag system work. Notice that `CTRL-]` for navigating to a tag will work on _any_ word! It does not need to be a well-defined tag enclosed by bars `|like-this|`. This is often useful, but it can be confusing if you are not aware how it works. I suggest you read more about this in the docs: `:help CTRL-]`. Also see `:help 29.1` for more info on tags in the user manual.

> Since the documentation admits that it is too long for a single readthrough, and that parts of it can be used as a reference, a good place to quickly navigate to relevant places is the feature overview section using tags.

Yes, that's a good point. Still, adding proper tags will make this overview much larger (the tags can be quite length in some cases). I would rather trust users to search for more information about features they find of interest, than to make the feature overview more cluttered.
