### ISSUE TITLE
doc: Accuracy of neovim's mechanism stated in the documentation

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2536]
### Description

In the documentation, it says:

>Neovim does not implement the same clientserver feature. Instead, it
  implements the MessagePack-RPC protocol (see |RPC|). VimTeX relies on this
  protocol in the same fashion as the clientserver. Both Vim and neovim have
  the |v:servername| variable that contains the name/location of the server
  with which we need to communicate.

Is this true any more? I thought neovim 0.7+ re-introduced the client-server architecture?

### Do you use a latexmkrc file?

N/A

### VimtexInfo

```yaml
N/A
```

**Comment by clason** [comment]
>  Is this true any more? I thought neovim 0.7+ re-introduced the client-server architecture?

No. Still apples and oranges.

**Comment by lervag** [comment]
> In the documentation, it says:
> 
> > Neovim does not implement the same clientserver feature. Instead, it
> > implements the MessagePack-RPC protocol (see |RPC|). VimTeX relies on this
> > protocol in the same fashion as the clientserver. Both Vim and neovim have
> > the |v:servername| variable that contains the name/location of the server
> > with which we need to communicate.
> 
> Is this true any more? I thought neovim 0.7+ re-introduced the client-server architecture?

Yes, this is still true.
