### ISSUE TITLE
doc: the +clientserver tag does not work in neovim

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2538]
The documentation states:

>Vim requires |+clientserver| in order to allow inverse search from the PDF
  viewer to Vim (see |vimtex-synctex-inverse-search|). 

However, in neovim 0.8, the `<C-]>` mapping to follow the `+clientserver` tag does not seem to work. Perhaps the documentation should somehow(?) account for this?

Similarly, `|remote_startserver()|` does not have tags in neovim

**Comment by clason** [comment]
Vim != Neovim

**Comment by lervag** [comment]
> The documentation states:
> 
> > Vim requires |+clientserver| in order to allow inverse search from the PDF
> > viewer to Vim (see |vimtex-synctex-inverse-search|).
> 
> However, in neovim 0.8, the `<C-]>` mapping to follow the `+clientserver` tag does not seem to work. Perhaps the documentation should somehow(?) account for this?
> 
> Similarly, `|remote_startserver()|` does not have tags in neovim

Nah, I think that's OK. If you are reading that part and you are using Vim, it makes sense to follow the tags to read up on things. If you are using neovim, then that part is not relevant to you anyway.
