### ISSUE TITLE
doc: Incorrect path to vimtex complete-commands documentation

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2539]
### Description

In the section, "COMPLETE COMMANDS AND ENVIRONMENTS", the documentation currently says:

>A lot of packages are supported, see the path `VIMTEX/autoload/vimtex/complete` for a relevant file listing.

However, the above filepath could not be navigated at all, either with `gf` or with `<C-]>`. 

Manually browsing the filesystem in the plugin installation directory, it is seen that command completion is provided for the following packages

```
abntcite
acro
acronym
afterpage
algorithm2e
allrunes
amsbsy
amsfonts
amsmath
amsopn
amssymb
amsthm
appendix
array
attachfile
babel
beamerfoils
beamerprosper
beamerseminar
beamertexpower
beamerthemeFhG
biblatex
bm
booktabs
braket
calc
cancel
caption
cases
chemformula
chemstyle
circuitikz
class-beamer
class-book
class-letter
class-memoir
class-moderncv
class-scrartcl
class-scrartcl,scrreprt,scrbook
class-scrbook
class-scrlttr2
class-scrreprt
cleveref
color
colortbl
commath
comment
coordsys
cquthesis
csquotes
currvita
cyrillic
datatool
datatool-base
default
diagxy
doi
empheq
enumerate
epigraph
epstopdf
etoolbox
eurosym
fancybox
fancyhdr
fancyunits-base
fancyunits-np
fancyunits-per
fancyunits_big-fractions
fancyunits_medium-fractions
fancyunits_small-fractions
fancyvrb
fhgtechdoku_additional
fixme
float
fontspec
geometry
german
glossaries
glosstex
graphicx
harvard
hyperref
ifluatex
ifpdf
iftex
ifthen
ifvtex
ifxetex
import
jurabib
kantlipsum
latex-209
latex-dev
latex-document
latex-l2tabu
latex-mathsymbols
layout
letltxmacro
libertine
lipsum
listings
logsys
longtable
lscape
ltxtable
luatex
luatodonotes
manyfoot
marvosym
mathtools
mdframed
mdwlist
memhfixc
menukeys
metrix
mhchem
microtype
minted
multicol
multido
multimedia
multirow
nameref
natbib
needspace
newclude
ngerman
nicefrac
nomencl
paracol
parskip
pdfpages
pgf
pgfcore
pgfplots
physics
pifont
placeins
psfrag
pst-3d
pst-blur
pst-char
pst-coil
pst-eps
pst-fill
pst-node
pst-plot
pst-text
pst-tree
pstricks
rotating
scraddr
scrdate
scrlfile
scrpage2
scrtime
secsty
setspace
siunitx
siunitx-special
subcaption
subfig
subfigure
subfiles
supertabular
svn-multi
svninfo
tabu
tabularx
tabulary
tex
textcomp
theorem
tikz
tikz-cd
tikz-timing
titlesec
tocbibind
tocloft
todonotes
tools
ulem
units
upgreek
url
varioref
verse
virginialake
wasysym
xcolor
xetex
xifthen
xkeyval
xltxtra
xparse
xspace
xtab
xy
yathesis
yfonts
```

While these 201 packages are probably important, there are many other critical packages that can benefit from command completion (the full texlive distro has about 4k packages).  What are the plans towards supporting more packages for command completion?

**Comment by lervag** [comment]
> In the section, "COMPLETE COMMANDS AND ENVIRONMENTS", the documentation currently says:
> 
> > A lot of packages are supported, see the path `VIMTEX/autoload/vimtex/complete` for a relevant file listing.
> 
> However, the above filepath could not be navigated at all, either with `gf` or with `<C-]>`.

No, that's right. Here `VIMTEX` is meant to imply the path to the VimTeX installation directory. There's no way to look into this other than manually browsing.

**Comment by lervag** [comment]
> While these 201 packages are probably important, there are many other critical packages that can benefit from command completion (the full texlive distro has about 4k packages). What are the plans towards supporting more packages for command completion?

No plans. Feel free to contribute :)

**Comment by krishnakumarg1984** [comment]
Can this be one of the cases where `texlab` can take over the command-completion functionality if installed?

**Comment by krishnakumarg1984** [comment]
>Here VIMTEX is meant to imply the path to the VimTeX installation directory. 

Ah. Then, it might be better to omit the leading `VIMTEX` in `VIMTEX/autoload/vimtex/complete`. This is to maintain consistency with the other 6 usages in the documentation.

e.g. 
> - Default value: See `s:init_delim_lists()` in `autoload/vimtex/delim.vim`.
> - Default value: See source in `/autoload/vimtex/options.vim`
> - Default value: See `autoload/vimtex/options.vim` (it's a long list)
> - Note: The available built-in matchers are defined in separate files under
        `autoload/vimtex/parser/toc/*.vim`.
> - In particular, see the function  `s:toc.parse(...)` in `autoload/vimtex/toc.vim`.
> - See `autoload/vimtex/parser/toc.vim` for examples on how to use this.
> - * Core elements: The `vimtex#syntax#core#init_highlights()` function in the file `autoload/vimtex/syntax/core.vim` specifies the default highlighting of  the core groups.
> * Package specific groups and elements are defined in the package specific
  scripts: `autoload/vimtex/syntax/p/*.vim`.

**Comment by lervag** [comment]
Thanks; I agree it should be consistent. I decided on `/autoload/...`.
