### ISSUE TITLE
Xelatex/ Luatex compatibility

### ISSUE THREAD

**Issue by leakciM** [lervag/vimtex#254]
Hi, 
Is it normal that I'm not able to compile Xelatex or Luatex files? I have some scripts that use the {fontspec} packages and I do not seem to be able to compile my code ...

Is there any solution?

**Comment by lervag** [comment]
Hi. You should be able to use Xelatex or Luatex. However, this should be specified in your `latexmkrc` file, for example:

```perl
$pdflatex = 'xelatex --shell-escape %O %S';
```

I do not plan to or want to add this as an option to vimtex. Even though I've hidden many "complexeties" of latexmk from most users, I still think that people should learn about latexmk and know how to run and use it outside of vimtex.

**Comment by leakciM** [comment]
Sounds great, thank you lervag, I already had a look at pdflatex and yes it is full of nice features!

**Comment by xerron** [comment]
You can have a latexmkrc for each project?

**Comment by tobanw** [comment]
@xerron: yes. From the [manual](http://mirror.jmu.edu/pub/CTAN/support/latexmk/latexmk.txt), `latexmk` will look for a config file in the current directory:

> The RC file in the current working  directory. This  file  can be named  either "latexmkrc" or ".latexmkrc", and the first of these to be found is used, if any.

**Comment by xerron** [comment]
Configuration for Lualatex:

```perl
#$pdflatex = 'xelatex -file-line-error -shell-escape -synctex=1';
$pdflatex = 'lualatex --interaction=nonstopmode --shell-escape --synctex=1';
```

work fine!

**Comment by Aster89** [comment]
Is this (I mean $pdflatex ...) the precise line to add in the latexmkrc in the working dir?

**Comment by tobanw** [comment]
Yes, you can have both a `latexmkrc` in your home dir as well as per-project ones in each working dir. The latter are read after the former, so they can override any general settings for a particular project.

**Comment by hoangdangninh** [comment]
@lervag : thanks, finally got it working with latexmkrc
