### ISSUE TITLE
doc:question on supported values of `$pdf_mode`

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2540]
The documentation says that:

>The supported values of `$pdf_mode` are **0 (pdflatex)**, 4 (lualatex) and 5 (xelatex). 

I thought the value of `1` stands for `pdflatex`? The manpage for latexmk for this variable says that:
> If zero, do NOT generate a pdf version of the document. If equal to 1, generate a pdf version of the document using pdflatex, using the command specified by the $pdflatexv ariable.

**Comment by lervag** [comment]
Good catch, thanks!
