### ISSUE TITLE
Getting quickfix list to match error/warning in sourced file rather than main file in multi-file project

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2543]
Hello,

I have the following files under the same project folder.

`main.tex`:

```tex
\documentclass[11pt]{article}
\usepackage{amsmath}
\usepackage{amsmath}
\usepackage[authoryear,comma]{natbib}

\begin{document}

\title{Title} \maketitle

\begin{abstract}
Some nice abstract
\end{abstract}

\input{section1}
\input{section2}

\end{document}
```

`section1.tex`:

```tex
\section{Section 1}
\label{s:section1}

This is Section 1.

\ref{s:section3} should give error.
```

`section2.tex`:

```tex
\section{Section 2}
\label{s:section2}

This is section 2.

```
My `vimrc` is thus:

```vim
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```

On compilation, the quickfix list shows warnings/errors only in `main.tex`. The complete content of the list are:

```tex
main.tex|| LaTeX Warning: No \author given.
main.tex|6 warning| LaTeX Warning: Reference `s:section3' on page 1 undefined on input line 6.
main.tex|| LaTeX Warning: There were undefined references.
```
Ideally, I would expect the quickfix list to point/take me to `section1.tex` last line where there is a reference made to an undefined section label, `section3`. 

Is there a way to achieve this functionality in multi-file projects where the errors/warnings are not indicated only in `main.tex`?

Please see screen cast of the issue above here: https://imgur.com/a/jsOix11

Thank you.

**Comment by lervag** [comment]
> Is there a way to achieve this functionality in multi-file projects where the errors/warnings are not indicated only in `main.tex`?

No, sorry, this is a hard limitation of the way LaTeX outputs its logs. It _is_ possible to parse, but it is so hard that I've decided not to do it. The reason is slightly complicated, so I'll not go into the details. However, this type of error message is correctly parsed by e.g. `pplatex`, which you can use with VimTeX (see `:help g:vimtex_quickfix_method`).

**Comment by TryerGit** [comment]
On downloading the pplatex excutable from https://github.com/stefanhepp/pplatex/releases (the tar.gz for linux) and placing the prebuilt binary `pplatex` in my project folder, and ensuring that `chmod u+x pplatex` I obtain the following VimTeX error:

```
VimTeX: pplatex is not executable!
VimTeX: Quickfix state not initialized!
Please see :help g:vimtex_quickfix_method
```

This is after setting `let g:vimtex_quickfix_method = 'pplatex'` in my vimrc.

Is there any alternative workaround you are aware of, @lervag

**Comment by lervag** [comment]
Sorry; I've installed `pplatex` in Arch Linux from the AUR (Arch User Repositories). The `PKGBUILD` file may be helpful, but it may also be just confusing - in any case, here it is: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pplatex

You could also just try to `git clone` the repo and compile and install it directly?

**Comment by TryerGit** [comment]
The installation instructions on that website seems to be different from the AUR PKGBUILD file:

`cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON ..`

The above (assuming this is the right command to issue) says something like the two CMakeLists.txt files don't match, etc.

When I tried to build it from source, I obtain a different error for which I have raised a request for help from that owner [here](https://github.com/stefanhepp/pplatex/issues/20)

**Comment by lervag** [comment]
Ok. The package builds just fine on my system, at least. Will be interested to hear if you get any help on the repo.

**Comment by TryerGit** [comment]
Got it to work, finally. VimTeX works fine and the error is caught in section1.tex. So, all good so far :-)

I was screwing up on the right pplatex installation. Updated the other thread with the steps I followed in case someone else faces same issue and also for my own forgetful reference in the future!

https://github.com/stefanhepp/pplatex/issues/20

**Comment by lervag** [comment]
Great, glad to hear you figured it out! :)

**Comment by TryerGit** [comment]
@lervag 

I did some more digging around. 

Suppose I have a windows batch file, say, `openmain.bat` whose contents is:

`wsl.exe vim main.tex`

the rough idea being that one can simultaneously open `wsl` and vim with main.tex showing up, By double clicking in windows on `openmain.bat`, the following error is obtained

```
"main.tex" [dos] 95L, 3045C
VimTeX: pplatex is not executable!
VimTeX: Quickfix state not initialized!
Please see :help g:vimtex_quickfix_method
```
On the other hand, splitting the above two processes (i.e., not running the batch file in Windows) and opening the WSL command prompt first and then typing `vim main.tex`, does not give the error and pplatex seems to load fine.

Just wanted to note that as something interesting for possible future evaluation time permitting and if you have access to a Windows WSL machine.

**Comment by lervag** [comment]
Hmm... I'm sorry to say that I don't really have any access to a Windows machine and don't expect to have in the foreseeable future. I'm therefore depending on user input and help to keep support for Windows.
