### ISSUE TITLE
doc; improve the documentation on/clarify on vimtex's folding feature

### ISSUE THREAD

**Issue by krishnakumarg1984** [lervag/vimtex#2547]
The documentation on foldin currenty says:

> FOLDING                                                        *vimtex-folding*
>                                                            *vimtex-bib-folding*
> 
> VimTeX can fold documents according to the LaTeX structure (part, chapter,
> section and subsection).  Folding in tex files is turned off by default, but
> can be enabled if desired, either through the option |g:vimtex_fold_enabled|,
> or manually with >
> 
>   set foldmethod=expr
>   set foldexpr=vimtex#fold#level(v:lnum)
>   set foldtext=vimtex#fold#text()

What is unclear is that, does the `g:vimtex_fold_enabled` variable automatically influence these three options simultaneously? i.e. setting it causes these 3 variables to be set to the above values?

Also, does setting this single option override these above settings only for `tex` and `bib` files? That means all other buffer types in the currn project foder will retain the settings that I have configured elsewhere in my vimrc, right?

Shall appreciate a bit more clarification around these aspects in the documentation.

**Comment by lervag** [comment]
> What is unclear is that, does the `g:vimtex_fold_enabled` variable automatically influence these three options simultaneously? i.e. setting it causes these 3 variables to be set to the above values?

Yes, precisely:

https://github.com/lervag/vimtex/blob/a234bd8dcb42bfcf2600dc0cb521c3bcfedacff9/autoload/vimtex/fold.vim#L7-L14

> Also, does setting this single option override these above settings only for `tex` and `bib` files? That means all other buffer types in the currn project foder will retain the settings that I have configured elsewhere in my vimrc, right?

Yes, this only overrides fold settings for `.tex` files. Similarly for `g:vimtex_fold_bib_enabled` for `.bib` files.

> Shall appreciate a bit more clarification around these aspects in the documentation.

I'll make an update, let me know what you think.

**Comment by krishnakumarg1984** [comment]
Thank you. That's much clearer now.

**Comment by lervag** [comment]
Great, glad to heart it :)
