### ISSUE TITLE
[FR] Swap default highlight for fxerror and fxfatal (fixme package) 

### ISSUE THREAD

**Issue by lambtho12** [lervag/vimtex#2552]
Even though highlights can be fully customized for the `fixme` package, I think it would make more sense to swap the default highlight for `fxerror` (currently bold, red, underline) and `fxfatal` (currently just red). 

This would match more closely the order of importance defined in Fixme: `Notes < Warning  < Error < Fatal`

Besides that, `fxfatal` are much more important as they will prevent the compilation of a non-draft document by throwing an error (the others will just be hidden in non-draft documents). Therefore it would make more sense to reflect that in the syntax with
- Error in red (or red+bold)
- Fatal in red + bold + underline

and not the opposite.

As the highlights are completely customizable, I would understand perfectly if you reject that. It is just just a small request to have more logical defaults.

**Comment by lervag** [comment]
> Even though highlights can be fully customized for the `fixme` package, I think it would make more sense to swap the default highlight for `fxerror` (currently bold, red, underline) and `fxfatal` (currently just red).

I can  swap, no problem. But please note that the default highlighting seems to be more or less the same for `Error` and `ErrorMsg`. At least on my side with Neovim.
