### ISSUE TITLE
Add word in line to Vimtex InverseSearch

### ISSUE THREAD

**Issue by arastoob** [lervag/vimtex#2555]
I love the `VimtexInverseSearch` that has been added to the new vimtex. Currently, this command accepts two arguments: the line number and the file. I'm wondering if it is possible to also add the word number in a line to the arguments to make the backward search more accurate.

**Comment by lervag** [comment]
Well, it is possible, but it would be useful to understand the full "pipeline" here. I.e., can the viewer actually _pass_ the word number as well?

Could you show an example of how I could test this if I were to implement it?

**Comment by arastoob** [comment]
One scenario that passing the clicked word might be helpful is when you write the text in one line in the `.tex` file and its compiled pdf is a paragraph. In that case, when you Cmd+Shift+click on any words in that paragraph, the pointer goes to the beginning of that line in the `.tex` file.  
Maybe passing the clicked word can help rather than the word number? Sorry I'm not fully aware of the `VimtexInverseSearch` code...

**Comment by arastoob** [comment]
Sorry, I misunderstood your previous question. I just checked for backward search in the [Skim wiki](https://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/#choosing-an-editor-command-for-backward-search), and I couldn't find any other parameters aside from `%line` and `%file`. So, we are limited to what the viewers return.
Thanks for your reply. I think we can close this issue?

**Comment by lervag** [comment]
Thanks for looking into this; I suspected that this feature was not available, but I was not sure. If you should discover that it is, in fact, somehow possible, then feel free to share and reopen this issue (or open a new one).
