### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by pierce-c** [lervag/vimtex#2561]
### Description

when I use vimtex, the syntax conceal feature works to some extent, replacing some latex commands with unicode symbols, but it also highlights the replaced symbols. Any help would be appreciated.
![image](https://user-images.githubusercontent.com/110128489/200195811-0cbaf9a3-033f-4a99-b546-2301aa385a2b.png)

### Steps to reproduce

downlaod the linked file. run `nvim discrete.tex` with vimtex installed

### Expected behavior

to see the syntax be concealed without highlighting

### Actual behavior

syntax concealed and highlights the concealed character

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
ubuntu 22.04.1 lts
nvim v0.6.1
has clientserver true
servername /tmp/nvimWpWHOY/0

vimtex project: discrete
base discrete.tex
root path
tex: root base
main parser fallback curr file
doc class article
packages amsmath, amssymb, geometry, inputenc, parskip
complirer latexmk
engine pdf
potions:
 verbose 
 file-line-error
 spynctex=1
 interaction=nonstopmode
callback 1
contihnuous 1
exec latexmk
viewer general
qf method: latex logile
```

**Comment by pierce-c** [comment]
sorry im dum this is unrelated goodbye goodday

**Comment by pierce-c** [comment]
sorry im still dum this unrelated goodbye goodday

**Comment by lervag** [comment]
So you figured things out? Good. You are right, it is unrelated. The highlighting is controlled by the highlight group `Conceal`.

**Comment by pierce-c** [comment]
yes. nice plugin btw!
