### ISSUE TITLE
Submission to editorialmanager journal sites

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2565]
Hi @lervag 

I pose this question since you may have direct experience with this. 

If you want to submit a paper to journals, is there a preferred method that you use? Specifically, on the `editorialmanager` website, for second round of review onwards, the journal insists that pdf files are not accepted but only .tex files. The journal site provides options for uploading only the following types of file submissions (see image [here](https://imgur.com/a/p63fMD8)) :

(a) Latex Source File (b) Figure

Previously, even in later rounds, a pdf was acceptable and then I had to separately provided .tex files. The folks behind the scenes at the journal would manually typeset accepted papers and send a pdf back for proofreading. Now, with the provided .tex files, the journal itself builds the pdf automatically at submission stage for onward processing. So, any typesetting errors at this stage means that the submission cannot happen.

At present, my project consists of a `main.tex` that calls (via `\input` command) other files such as `section1.tex`, `section8.tex`, etc. The submission only accepts a singular latex source file (so, multiple `.tex` files seem unacceptable)

Is there any vimtex support that will convert `main.tex`, `section1.tex`,...,`section8.tex` into one single big consolidated `.tex` file? Also, (I know this is a question for `editorialmanager` folks, but as I mentioned above, perhaps you have experience and hence my query), are the included graphics figures to be uploaded individually as Figure(s)  and then the `editorialmanager` website will source these graphics files automatically?

Thank you.

PS: The journal's latex submission page does not address any of the above questions, hence this post. The journal (under Elsevier) has the following Latex submission help page: https://www.elsevier.com/authors/policies-and-guidelines/latex-instructions

**Comment by TryerGit** [comment]
I figured it out after some trial and error. Essentially, as the site suggests, create a zip file with all `.tex`, `.bib` and `.jpg` files. Upload this zip file as a "Manuscript File". The system seems to unzip this and loads each individual file. Rename all these files as 'Manuscript File"s. The system builds the pdf for you.

**Comment by lervag** [comment]
Yes, if I had the time to reply sooner, I would claim exactly this, that you should be able to provide your complete manuscript in an archive. Glad to hear you figured it out.

**Comment by lervag** [comment]
VimTeX does not really have this magic, it only relies on what is provided by latexmk.

Also, this does not really seem like a very useful feature, considering how easy it is to zip files in general.

**Comment by JVAQUEROM** [comment]
zipping files is easy, but not automating the selection of the files needed to build the pdf. Anyway, I'll take aa look to latexmk and see if I can automate it from latexmk itself. Thanks!

**Comment by JVAQUEROM** [comment]
Ok, I don't know much about perl but I may give it a shot. I'll post if I get a working solution.

Best!
