### ISSUE TITLE
Feature Request: Open \input or \include file on <control>-]

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#257]
Similar to how links are navigated in Vim help I think it would be nice to be able to have vimtex open files that are \input or \include(d) in the currently-edited LaTeX file.

Example: On line 10 of ``main.tex`` the user encounters the line ``\input{otherfile}``. Placing the user's cursor between ``{`` and ``}`` (somewhere on the text ``otherfile`` and pressing ``<ctrl>-] `` - Vim's stock jump control sequence - opens ``./otherfile.texfile`` in a new pane in normal mode (window split horizontally or vertically depending on .vimrc settings; default horizontal).

i think this new pane should become the active pane after jumping to it.

**Comment by ff2000** [comment]
On Sat, 24 Oct 2015 06:35:10 -0700, John Rinehart <notifications@github.com> wrote:
> Similar to how links are navigated in Vim help I think it would be nice to be able to have vimtex open files that are \input or \include(d) in the currently-edited LaTeX file.
> 
> Example: On line 10 of ``main.tex`` the user encounters the line ``\input{otherfile}``. Placing the user's cursor between ``{`` and ``}`` (somewhere on the text ``otherfile`` and pressing ``<ctrl>-] `` - Vim's stock jump control sequence - opens ``./otherfile.texfile`` in a new pane in normal mode (window split horizontally or vertically depending on .vimrc settings; default horizontal).
> 
> i think this new pane should become the active pane after jumping to it.
You can already use `gf` which opens the file under the cursor. Works
really well :)

**Comment by fuzzybear3965** [comment]
Wow! Thanks! I had no idea this was a feature in Vim. For those who might read this after me ``gf`` actually opens the file referenced under the cursor in the current window. I didn't want that. However, ``<c-w>f`` (``<ctrl>+w+f``) does exactly what I want!

In case you want to use ``gf`` you can return to the previous file by using ``<ctrl>^``.

References: 
   1. http://stackoverflow.com/questions/19971023/how-to-go-back-to-previous-opened-file-in-vim
   1. http://vim.wikia.com/wiki/Open_file_under_cursor

**Comment by lervag** [comment]
@ff2000 Thanks for contributing to the discussions, and thus solving the issue!

@fuzzybear3965 I would also have mentioned the `gf` command. I'm glad this solves your issue.
