### ISSUE TITLE
MRU autosuggestions

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2576]
Hello,

I am not sure if this should properly be a question/request for VimTeX or MuComplete (my current autocompletion engine).

But, is it possible to have, in math mode, an MRU (most recently used) suggestions available on top for default tab/auto/trigger completion? I continue to use LyX for some of my other projects and LyX has this feature and it is quite useful.

I find myself in math mode, having to type `\tilde` a lot or `\ldots` a lot and these are mostly spatially and temporally proximate and clustered.

Is there any suggestion regarding entering greek symbols easily and quickly in math mode in VimTeX in particular and Vim in general? At present I have UltiSnips for commonly used symbols and while typing a snippet `alph` is somewhat easier than typing `\alpha`, perhaps I am missing out on something easier.

Thank you.

**Comment by lervag** [comment]
> But, is it possible to have, in math mode, an MRU (most recently used) suggestions available on top for default tab/auto/trigger completion?

This sounds like something that could _possibly_ be implemented as a source for a completion engine, but I'm not sure. I've never seen anything like it before myself.

> Is there any suggestion regarding entering greek symbols easily and quickly in math mode in VimTeX in particular and Vim in general? At present I have UltiSnips for commonly used symbols and while typing a snippet `alph` is somewhat easier than typing `\alpha`, perhaps I am missing out on something easier.

With UltiSnips you can create automatically expanding snippets with the `A` option. It is convenient to combine this with some type of "leader" key, e.g. `;a` ⇒ `\alpha`, `;~` ⇒ `\tilde`, and so on.

VimTeX also has a similar feature already for trivial or _almost_ trivial snippets. It is documented at `:help vimtex-imaps`. This gives something like the above explained shortcuts. But with UltiSnips, you can also create more advanced automatic snippets, e.g. `__` in math mode expanding to `_{|}` where `|` is the cursor.

Still, if you only really need the most simple versions, then it could be interesting to check the built-in stuff in VimTeX.

**Comment by TryerGit** [comment]
Hi @lervag 

I have been slowly working my way through rationalizing my ultisnips snippets and removing those for which vimtex already provides imaps. In that process, I came across a few useful mappings in vimtex's `options.vim` file:

```
        \ { 'lhs' : '/',  'rhs' : 'vimtex#imaps#style_math("slashed")', 'expr' : 1, 'leader' : '#'},
        \ { 'lhs' : 'b',  'rhs' : 'vimtex#imaps#style_math("mathbf")', 'expr' : 1, 'leader' : '#'},
        \ { 'lhs' : 'f',  'rhs' : 'vimtex#imaps#style_math("mathfrak")', 'expr' : 1, 'leader' : '#'},
        \ { 'lhs' : 'c',  'rhs' : 'vimtex#imaps#style_math("mathcal")', 'expr' : 1, 'leader' : '#'},
        \ { 'lhs' : '-',  'rhs' : 'vimtex#imaps#style_math("overline")', 'expr' : 1, 'leader' : '#'},
        \ { 'lhs' : 'B',  'rhs' : 'vimtex#imaps#style_math("mathbb")', 'expr' : 1, 'leader' : '#'},
```

All of the previous mappings iin this file work with the backtick leader key (by default), while these seem to have very specific leader key `#`. Is there any reason why you have chosen to use different leader keys for these? I needed the `\overline` command quite frequently, with greek symbols, and I noticed that the greek symbols work with the backtick leader key (and this is just one keystroke), while the `#` needs two keystrokes. I also verified that the `-` [for obtaining `\overline`] does not clash with any previous imap and so was curious why you had decided to go this way.

Thank you -- I have had to convert some ancient math notes into TeX and I have been enjoying being quite productive with VimTeX!

**Comment by lervag** [comment]
Perhaps it's not perfectly consistent, but I believe the rationale was that the default main leader is already used for `b`, `f` and `c`, and since these commands were related, it seemed to make sense to group them to the same leader. Not entirely sure, it's been very long since I wrote those things.

There is nothing wrong with just copying the entire defautl configuration into your vimrc and modifying it to your liking though. I don't expect to make many changes to these parts in any near future.

**Comment by lervag** [comment]
And I'm glad to hear you find VimTeX useful! <3
