### ISSUE TITLE
Disabling syntax invalidates text object $

### ISSUE THREAD

**Issue by jimmy-zx** [lervag/vimtex#2583]
### Description

When `let g:vimtex_syntax_enabled = 0` is set, the text object `$` is invalidated.

### Steps to reproduce

minimal.vim:
```vim
set nocp

call plug#begin()
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_syntax_enabled = 0

syntax on
```

minimal.tex:
```tex
\begin{document}
$a + b = c$
\end{document}
```

1. `vim -u minimal.vim minimal.tex`
2. Perform `da$` on `$a + b = c$`

### Expected behavior

`$a + b = c$` deleted

### Actual behavior

Nothing happens

(Other text objects described in the documentation still works)

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
None
```

**Comment by lervag** [comment]
You need syntax highlighting enabled for some of the text objects to work. This is because these text objects rely on the syntax information in their implementation.

I realize this is not properly documented, so I'll make an update to the docs to point it out.
