### ISSUE TITLE
Completion support

### ISSUE THREAD

**Issue by ShiAnPoQing** [lervag/vimtex#2584]
### Description

How to add custom tex commands to omnicompletion?

![2022-11-27-16-35-11](https://user-images.githubusercontent.com/112422825/204126143-b1809605-1066-4277-9f76-d692da7f6b5f.png)
I don't know where to add the custom command, adding in these files has no effect.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
N/A
```

**Comment by lervag** [comment]
> How to add custom tex commands to omnicompletion?
> ..
> I don't know where to add the custom command, adding in these files has no effect.

Can you please take a step back and explain your original problem? I guess you are working in some document where you want some commands either from a package or similar to be autocompleted? Please explain, and provide the relevant details, e.g. an example document.
