### ISSUE TITLE
Add conceal symbols

### ISSUE THREAD

**Issue by awelormro** [lervag/vimtex#2585]
Just a general question, the conceal works well with many characters, but un cases like \longrightarrow or similar, it does not have a conceal, Is there a way to add conceal characters for vimtex conceal?

**Comment by lervag** [comment]
Yes, either:

1. open an issue and explain why it should be added in general for everyone, or
2. use `:help g:vimtex_syntax_custom_cmds`.

An example of how to use the latter:

```vim
let g:vimtex_syntax_custom_cmds = [
      \ {'name': 'longrightarrow', 'mathmode': 1, 'concealchar': '→'},
      \]
```

Of course, you can put (more or less) any unicode character in the `'concealchar'` value.

If you think `\longrightarrow` should be concealed for everyone, then please give an example of how to use it and give a link to the documentation of the relevant package. I might add it.

**Comment by awelormro** [comment]
Maybe not for everyone, but it's something I really wanted to make, because I use this symbol a lot, just I didn't found the part to expand the conceal characters for vimtex conceal in the documentation for the custom ones, Thanks a lot for the response!

**Comment by lervag** [comment]
Glad to help :)
