### ISSUE TITLE
Influencing name of pdf file created on compilation

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2588]
Hello,

Given `main.tex`, is it possible to create different pdf files (a) `a.pdf` or (b) `b.pdf` via vimtex depending on a variable defined in the source code `main.tex` itself, say like so:

```tex
\usepackage{ifthen} 
\newif\ifVersionA 
\VersionAtrue % output should be a.pdf
%\VersionAfalse % output should be b.pdf
```

Relevant (albeit dated) stackexchange discussion [here](https://tex.stackexchange.com/questions/19182/how-to-influence-the-name-of-the-pdf-file-created-with-pdflatex-from-within-the).

Although the accepted answer there answers the question in the negative, subsequent answers seem to suggest some workarounds that influence the compiler command issued. See for instance [this](https://tex.stackexchange.com/a/471024/254015)

Thank you.

**Comment by lervag** [comment]
No, sorry. This is not possible with VimTeX. If you did make this work with regular TeX/LaTeX, you should also note that it would not work well with VimTeX, because VimTeX assumes that the outpiut file name (and aux files) share the same basename as the main file.

Did you try the solutions posted in the subsequent answers on SE?

**Comment by TryerGit** [comment]
> Did you try the solutions posted in the subsequent answers on SE?

Not the ones on the page listed. Currently, I have a workaround which is similar to [this](https://tex.stackexchange.com/a/513876) method -- essentially have different outer `.tex` files which define variables which are then used appropriately within the same common inner `tex` file. There is no need to ever touch the outer tex files once they are setup. Only the inner one needs to be updated periodically.

**Comment by lervag** [comment]
Ok, cool. That seems to be a nice workaround. I don't really see any better ways to do this...

**Comment by lervag** [comment]
> If someone ends up calling `vim main.tex`, it could lead to an issue for VimTeX in terms of figuring out which is the right file to compile -- `student.tex` or `professor.tex` -- when from within `main.tex` `\ll` is issued. Do you think this could be a problem?

I believe, in this case, that VimTeX should ask _which_ of `student.tex` or `professor.tex` to use as the main file. Seems to work as expected for me, at least:

![image](https://user-images.githubusercontent.com/998898/204534293-48697405-74d8-4a39-9e2e-9d9c29f0d41c.png)

```tex
% main.tex
\begin{document}
Hello World! \person
\end{document}

% professor.tex
\documentclass{minimal}
\newcommand{\person}{from professor}
\input{main.tex}

% student.tex
\documentclass{minimal}
\newcommand{\person}{from student}
\input{main.tex}
```

**Comment by TryerGit** [comment]
Ah perfect. I hadn't tested that out. I was thus far compiling from student.tex or professor.tex only. VimTeX actually solves the problem rather well, I must say. This is even better than all other proposed solutions on SE!
