### ISSUE TITLE
Unwanted backslash is inserted with neosnippet

### ISSUE THREAD

**Issue by inakacalm** [lervag/vimtex#259]
Unwanted backslash is inserted in the following procedure, with neosnippet bundle.
1. Close TeX document with cursor at just before (insert mode) or on (normal mode) the backslash.
2. Reopen the document, the another backslash is inserted next to the backslash in step1.

I explain this issue with picture.
When I close document with following cursol position and quit MacVim.
<img width="400" alt="before_quit" src="https://cloud.githubusercontent.com/assets/9824898/10715806/e645b9d8-7b66-11e5-818d-a7f0ff0cf2ed.png">

Unwanted backslash is inserted when I reopen the same document.
This issue also appears on the CUI version of Vim.
<img width="400" alt="after_reopen" src="https://cloud.githubusercontent.com/assets/9824898/10715820/4a94fffc-7b67-11e5-9931-6191c22edeb1.png">

I attached the minimal working .vimrc file. I loaded vimtex plugin and neosnippet with neobundle.
```vim
""
"" NeoBundle
""
" Note: Skip initialization for vim-tiny or vim-small.
if 0 | endif

if has('vim_starting')
   if &compatible
     set nocompatible               " Be iMproved
   endif

   " Required:
   set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

" Required:
 call neobundle#begin(expand('~/.vim/bundle/'))
 
 " Let NeoBundle manage NeoBundle
 " Required:
 NeoBundleFetch 'Shougo/neobundle.vim'

"Neosnippet
NeoBundle 'Shougo/neosnippet'
NeoBundleLazy 'lervag/vimtex', {
            \ 'autoload' : {'filetypes' : 'tex'}
            \ }

"" End of Bundles

call neobundle#end()

filetype plugin indent on

NeoBundleCheck

""
"" vimtex
""
let g:vimtex_imaps_snippet_engine = 'neosnippet'

""
"" Enable syntax
""
syntax on
"===========================================================================
"EOF
```

**Comment by lervag** [comment]
Sorry, should be fixed now.

**Comment by inakacalm** [comment]
Thank you!!

**Comment by lervag** [comment]
No problem! :)
