### ISSUE TITLE
Default VimTex errors window size

### ISSUE THREAD

**Issue by SiddidMandi** [lervag/vimtex#2590]
Not really an important issue and I think it can be fixed with 
`set lines=35`
But how do you set the default size of the `Vimtex errors {Latex logfile}` window that pops up when you compile?
What is the .vimrc or init.vim command?

**Comment by lervag** [comment]
The error window is what is called a quickfix window, see `:help quickfix-window`. You can use an autocommand to specify the size, e.g.

```vim
augroup quickfix_autocmds
  autocmd!
  autocmd BufReadPost quickfix 35wincmd _
augroup END
```

I have some more advanced settings for the quickfix window that you may find interesting:

https://github.com/lervag/dotnvim/blob/main/ftplugin/qf.vim

As you see, I put the configuration under `/ftplugin/qf.vim` in my neovim configuration directory (`~/.config/nvim`). It would be `~/.vim` if you are using Vim. Some functions I use are defined in a separate file, `/autoload/personal/qf.vim`.

**Comment by SiddidMandi** [comment]
Yeah, it works, the height alters. Thanks for the quick reply and this plugin in general. Just swapped to vim from awful vscode and your extension was a deal-breaking feature.

**Comment by lervag** [comment]
Thanks for the kind works :)
