### ISSUE TITLE
Autocomplete with \nameref{} & \pageref{}

### ISSUE THREAD

**Issue by mafsi** [lervag/vimtex#2593]
According to [documentation,](https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L3820) autocomplete labels is triggered by `\ref` command. It would be nice to have the same trigger for `nameref` package also for `cleverref`.
Thanks!

**Comment by lervag** [comment]
I can consider that. Could you first provide a small example on which I can test things?

**Comment by mafsi** [comment]
#### MWE

```tex
\documentclass{article}
\usepackage{nameref}
\usepackage{hyperref}

\begin{document}

\section{Introduction}
\label{sec:intro}

We would like to propose that \texttt{vimtex} autotrigger for
\texttt{nameref} package and also for the \texttt{cleverref}.

\section{Methodology}
\label{sec:meth}

As we stated on section §\nameref{sec:intro} on page
\pageref{sec:intro} we want to propose that to cover all types of
crossreferences.

\end{document}
```

**Comment by lervag** [comment]
I believe this should work as expected now, please test.

Notice, though: VimTeX does _not_ do autocompletion. It only provides an omnicomplete function. However, VimTeX should work well with most common autocomplete plugins (see `:help vimtex-complete-auto` for more info).
