### ISSUE TITLE
syntax conceal for spacing commands

### ISSUE THREAD

**Issue by pierce-c** [lervag/vimtex#2594]
request to apply the syntax conceal feature to LaTeX spacing commands such as `\quad`, `\qquad`, `\,`, `\thinspace`, `\:`, `medspace`, `;`, `\thickspace`, `\!`, `\bigskip`, `\vskip`, `\vspace`, `\hspace`, `\vfill`, `\hfill`

**Comment by lervag** [comment]
This is more or less already supported. There are probably some exceptions, but at least `\quad` and `\,` and similar should already work. The following are not implemented now:

* `\thinspace`
* `\medspace`
* `\thickspace`
* `\bigskip`
* `\vskip`
* `\vspace`
* `\hspace`
* `\vfill`
* `\hfill`

I could add these, but before I properly consider it, please help me by categorizing the commands:

1. Do they work in math or normal mode?
2. Are they part of the "core", or do they come from a specific package?

**Comment by pierce-c** [comment]
u mean like do they come from a latex package?
`\\:` , `\\medspace`, `\\;`, `\\thickspace`, `\!` all come from `amsmath`

**Comment by pierce-c** [comment]
the reset r not from a package

**Comment by pierce-c** [comment]
i haven't noticed \, working or \quad, and i just fetched

**Comment by lervag** [comment]
I'm sorry, but could you please write in full sentences? I do not understand what you write in the last comment.

Proof that the conceals work as expected for some of these:

![image](https://user-images.githubusercontent.com/998898/206028211-ca0ca5ce-0da9-4339-ba33-13b76273bc71.png)

Here you see that `\quad` and many of the other symbols are concealed (on the right-hand side). The left-hand side has `set conceallevel=0`. However, `\medspace`, `\thickspace` and similar are not concealed yet.

In any case, I've investigated and reached the following conclusion:

1. I will not add conceals for the vertical variants. These are more _important_ in a context and should not be concealed (IMHO).
2. I will implement support for the other variants. It is true that `amsmath` does provide some of these, but only in the sense that it improves them. The following minimal example compiles and works as expected without loading `amsmath`:

```tex
\documentclass{minimal}
\begin{document}

Hello
\thinspace
\medspace
\thickspace
\bigskip
\hspace{1em}
\hfill
\vspace{1em}
\vfill
Moon

1 \, \: \; \! \quad \qquad 2

$ 1 \, \: \; \! \quad \qquad 2 $

$
Hello
\thinspace
\medspace
\thickspace
\bigskip
\hspace{1em}
\hfill
\vspace{1em}
Moon
$

\end{document}
```

Some of this, as mentioned before, already works. But I'll implement the missing parts as well.

**Comment by pierce-c** [comment]
after fetching, it still didn't conceal \, or \quad , it just highlighted them.

**Comment by lervag** [comment]
Then that's because you have some issue with your configuration.

**Comment by lervag** [comment]
To be clear: Please provide details on your system. There's a template for posting issues and it's there for a reason :)
