### ISSUE TITLE
Disable \item indenting on next line

### ISSUE THREAD

**Issue by BigDru** [lervag/vimtex#2599]
There is a closed issue (lervag/vimtex#1245) which has a discussion following closing about indentation after `\item` elements.
Specifically, in the discussion following the closure there is an example: 

> 
> (i.e., when pressing ENTER in an itemize environment, I get an additional indent like
> 
> ```
> \item blabla (ENTER pressed)
>      | <--- now here :-(
> ```

It was mentioned that if we want to have an option to disable this kind of indentation we should make a new feature request. So here we are :)

For now I am using the following:
```
let g:vimtex_indent_enabled = 0
let g:tex_indent_items = 0
```
or in neovim: 
```
vim.g.vimtex_indent_enable = 0
vim.g.tex_indent_items = 0
```

I imagine the end result would be an option similar to the base tex option. Something like `g:vimtex_indent_items` which can be set to 0 or 1 (default value). 

If the option is cleared (off / 0), the behaviour in the above example would be: 
> ```
> \item blabla (ENTER pressed)
> | <--- now here :D
> ```

I believe implementation would involve adding a conditional to indent/tex.vim but I'll leave those details to the devs. :)

**Comment by ilias777** [comment]
Are you on Vim or Neovim?
With Neovim you can solve the indentation problem with `latexindent` and `Null-ls`.
For more information you can read the documentation here --> [LatexIndent](https://latexindentpl.readthedocs.io/en/latest/sec-indent-config-and-settings.html)

I am on Mac and I use Neovim. I show you my configuration. *(This configuration works only with Neovim)*

These are my steps:
+ Installing `latexindent` binary on your system (in my case I installed it with homebrew).
+ Installing `nvim-lspconfig`, if you don't have this already ([neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig)).
+ Installing `null-ls`, if you don't have this already ([jose-elias-alvarez/null-ls.nvim](https://github.com/jose-elias-alvarez/null-ls.nvim)).
+ Create a folder in your home directory `.latexindent/`.
+ In this folder create a file `mysettings.yaml`.
+ In this `mysettings.yaml` file put this lines:
```yml
noAdditionalIndent:
  textit: 1
  footnote: 1
  item: 1
```
Here will be disabled the indentation for `textit`, `footnote` and `item`. You need only `item: 1`, if you want indentation for the others.
+ Settings in `nvim-lspconfig` file:
```lua
local on_attach = function(client, bufnr)
        -- ...
        vim.keymap.set('n', '<space>f', function()
            vim.lsp.buf.format({ async = true })
        end, bufopts)
        -- ...
end
```
Keymap for formatting the buffer.
+ Settings in `Null-ls` file:
```lua
require('null-ls').setup({
        sources = {
            -- ...
            require('null-ls').builtins.formatting.latexindent.with({
                extra_args = {
                    '-l',
                    '/<your-homedirectory-path>/.indentconfig.yaml',
                },
            }),
            -- ...
        }
})
```

From now every time you press `<Space>f` your `*.tex` file will be formatted without indentation in the `\item` section.

And it looks like this:

https://user-images.githubusercontent.com/39212564/208322847-c4e55fb0-f48c-4269-b7ed-faa7d2940c7a.mov


I hope this is helpful for you.

**Comment by lervag** [comment]
> With Neovim you can solve the indentation problem with `latexindent` and `Null-ls`.

Thanks for this info. As a side note, on Vim, you can use a similar approach with other plugins, e.g. the well know [Ale](https://github.com/dense-analysis/ale).

Using external tools for formatting and indenting is not a bad idea. I believe the VimTeX indentation function is quite good, but I'll also gladly admit it has its restrictions. Also, it is clearly opinionated. It has always been a goal with VimTeX to allow other options for specific features, so if you want to use external tools for indentation, then you can also disable VimTeXs indent feature with the `g:vimtex_indent_enabled` option.

**Comment by lervag** [comment]
I'll close the issue, since I believe my first comment should suffice for resolving the original problem.
