### ISSUE TITLE
Unable to open gVim normally after installation.

### ISSUE THREAD

**Issue by Sklansky** [lervag/vimtex#2602]
### Description

I failed to open gvim after installing with vim plug.
```
Plug 'lervag/vimtex'
let g:tex_flavor='latex'
```
Then
![Screenshot 2022-12-16 170810](https://user-images.githubusercontent.com/104699857/208065539-98aab1d5-3651-4cca-bcad-5f5cac1b20b0.png)

The version used is gVim9.0, windows10. Please help me.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
A.
```

**Comment by lervag** [comment]
> I failed to open gvim after installing with vim plug.

It is impossible to say based on the input you give. Please provide more details.

> 
> ```
> Plug 'lervag/vimtex'
> let g:tex_flavor='latex'
> ```

That is _not_ your entire `vimrc` file. `let g:tex_flavor` is not necessary with VimTeX, so you can remove that anyway.

----

Can you please be more clear and concrete about what you are doing. That is,

1. What is in your `_vimrc` file?
2. What are the exact steps you use to open GVim and reproduce this error?

**Comment by Sklansky** [comment]
Sorry, I'm a green hand.I only added a few plug-ins, and the rest are default.
```
" Vim with all enhancements
source $VIMRUNTIME/vimrc_example.vim

" Use the internal diff if available.
" Otherwise use the special 'diffexpr' for Windows.
if &diffopt !~# 'internal'
  set diffexpr=MyDiff()
endif
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg1 = substitute(arg1, '!', '\!', 'g')
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg2 = substitute(arg2, '!', '\!', 'g')
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let arg3 = substitute(arg3, '!', '\!', 'g')
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      if empty(&shellxquote)
        let l:shxq_sav = ''
        set shellxquote&
      endif
      let cmd = '"' . $VIMRUNTIME . '\diff"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  let cmd = substitute(cmd, '!', '\!', 'g')
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3
  if exists('l:shxq_sav')
    let &shellxquote=l:shxq_sav
  endif
endfunction
set nu
set guifont=Lucida\ Console:h15
colorscheme evening

call plug#begin('D:/VIM/vimfiles/plugin')
Plug 'preservim/nerdtree'
Plug 'luochen1990/rainbow'
Plug 'lervag/vimtex'
call plug#end()
let g:rainbow_active = 1
let g:tex_flavor='latex'
```

**Comment by lervag** [comment]
Ok. Can you also explain the steps to get the error? I mean, how do you start GVim? What's the "path" (list of steps) to get to the error message?

**Comment by Sklansky** [comment]
I double-click the shortcut on the desktop and wait a few seconds to get the error window.

![error](https://user-images.githubusercontent.com/104699857/208108687-68fee913-a32f-49c2-b300-5456dc5bc7d9.png)

**Comment by lervag** [comment]
First, and again: you don't need `let g:tex_flavor ... ` - just remove that line.

Now, what happens if you simply comment out everything in your `_vimrc` file? I would expect GVim to open without any issues and just display the standard intro screen.

If so, then the next step would be to uncomment the plugin loading so that you basically have this config:

```viml
call plug#begin('D:/VIM/vimfiles/plugin')
Plug 'preservim/nerdtree'
Plug 'luochen1990/rainbow'
Plug 'lervag/vimtex'
call plug#end()
```

Does it still work, or do you have the same error as before? If you have the same error, is the error gone if you comment out `Plug 'lervag/vimtex'`?

**Comment by Sklansky** [comment]
I cleared _vimrc file, but vim is not okay.Gvim can only be opened after all plug-ins(files) are cleared.IF not, other plug-ins hava similar problems.
![Screenshot 2022-12-16 224655](https://user-images.githubusercontent.com/104699857/208123706-b2915b60-f77f-4cee-bbf0-4eceffe483ae.png)
I think the following code must exist without deleting the plug-in file.So I only add that in the _vimrc.
```
call plug#begin('D:/VIM/vimfiles/plugin')
Plug 'preservim/nerdtree'
Plug 'luochen1990/rainbow'
Plug 'lervag/vimtex'
call plug#end()
```
But it still can't work.
![casacs](https://user-images.githubusercontent.com/104699857/208124704-80ae1010-eea0-41f3-8fe0-8b2f23dcbed1.png)
I delete vimtex files in the D:/VIM/vimfiles/plugin, It ran successfully.

**Comment by lervag** [comment]
So, first, your problem is not really a VimTeX issue - it is rather a configuration issue caused by you doing something wrong with configuration. I'll try and help.

I believe the issue may be that you are trying to use a path for your plugins that is already automatically sourced. Can you try and change `call plug#begin('D:/VIM/vimfiles/plugin')` to `call plug#begin('~\.vim\bundles')` or similar?

By the way: where did you first install vim-plug itself? To install it, you have most likely downloaded the `vim-plug.vim` file and put it in some `autoload/` directory - which one?

**Comment by Sklansky** [comment]
Thanks for your help.I changed 'D:/VIM/vimfiles/plugin' to '~/vimfiles/pludded'.GVim is back to normal.But plug-ins went to my drive, How can I let these to D Drive？

**Comment by lervag** [comment]
> But plug-ins went to my drive, How can I let these to D Drive？

I have no idea what you mean, sorry. Can you try to rephrase and explain better? What is "my drive" and what do you mean "let these to ..."?

**Comment by Sklansky** [comment]
![QQ截图20221217085635](https://user-images.githubusercontent.com/104699857/208214657-9310d616-6da8-4bb5-bbe4-0b5725069339.png)

**Comment by Sklansky** [comment]
Thank you very much for your help.

**Comment by lervag** [comment]
It seems you figured things out, then? Glad to hear it!
