### ISSUE TITLE
Developments Re Zathura on Apple Silicon

### ISSUE THREAD

**Issue by ejmastnak** [lervag/vimtex#2604]
Hi @lervag,

Just wanted to bring this to your attention; perhaps it is useful information:

I just got an email from a visitor to the tutorials on my website reporting success with Zathura on an Apple Silicon Mac. The process (a more elaborate version of `:help vimtex-faq-zathura-macos` that I would never have come up with myself) is described in Homebrew Zathura issue [#99](https://github.com/zegervdv/homebrew-zathura/issues/99#issuecomment-1356384136). I've linked this issue on my website; perhaps it is also worth mentioning in `:help vimtex-faq-zathura-macos`? (Happy to submit a PR if it helps, but it's probably just a one-liner addition to the docs).

Disclaimer: Haven't tested it as I don't have an Silicon Mac and am on Linux these days anyway, but I've been in contact with the OP and it is reported to work.

**Comment by lervag** [comment]
> I just got an email from a visitor to the tutorials on my website reporting success with Zathura on an Apple Silicon Mac. The process (a more elaborate version of `:help vimtex-faq-zathura-macos` that I would never have come up with myself) is described in Homebrew Zathura issue [#99](https://github.com/zegervdv/homebrew-zathura/issues/99#issuecomment-1356384136). I've linked this issue on my website; perhaps it is also worth mentioning in `:help vimtex-faq-zathura-macos`? (Happy to submit a PR if it helps, but it's probably just a one-liner addition to the docs).

Thank you, yes, this does seem very relevant. I'd be glad to consider a PR for it!

I agree it should be a short addition with a referance/link to the post on the homebrew-zathura project.

**Comment by lervag** [comment]
Resolved in #2605.
