### ISSUE TITLE
Snippet misfires if typed across multiple lines 

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2607]
Hello,

Consider the following snippet in UltiSnips:

```
snippet mm "Inline Math" wA
\\( $1 \\) $0
endsnippet
```

In insert mode, when `mm` is typed as a new word (`w` option), this snippet automatically (`A` option) gives one an inline math mode.

Consider the following .vimrc:

```vim
"-------------Load Plugins------------------
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')
Plug 'lifepillar/vim-mucomplete'
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'lervag/vimtex'
call plug#end()
"---------------End Plugins added-----------------------
"----------- UltiSnips triggering-------------
let g:UltiSnipsExpandTrigger = '<C-a>'
let g:UltiSnipsJumpForwardTrigger = '<C-a>'
let g:UltiSnipsJumpBackwardTrigger = '<C-d>'
let g:UltiSnipsEditSplit="vertical"
let g:UltiSnipsSnippetDirectories=[$HOME.'/.vim/UltiSnips']
"-----------End ultisnips--------------------
"---------Begin MuComplete Setup-----------
  set completeopt+=menuone
  set completeopt+=noselect
  set belloff+=ctrlg
  let g:mucomplete#enable_auto_at_startup = 1
"---------End MuComplete Setup-------------
set textwidth=79
set colorcolumn=79
```

Now, when `mm` is typed close to column number 79, the cursor's position becomes `\|)` instead of `|\)`

An explanatory gif is below:

![issue](https://user-images.githubusercontent.com/70434658/209467964-79a80cdd-cbbf-459a-93bc-34d04bc6d729.gif)

I do not know if this is a VimTeX issue or if this is an UltiSnips issue. If this is fixable within VimTeX, it would help! The UltiSnips issues tracker has been in coma for a while.

**Comment by lervag** [comment]
I'm sorry, but this is not a VimTeX issue. I believe it is an UltiSnips issue.

One simple way to avoid it is to adopt the one sentence per line idea where you avoid the textwidth restriction. I personally like that better, because it 1) helps me avoid too long sentences, and 2) makes diffing versions easier because it avoids changes only due to formatting to adhere to the `tw=79` rule.

**Comment by lervag** [comment]
See also `:help vimtex-af-formatting` for a related discussion.

**Comment by TryerGit** [comment]
I see. One sentence per line guideline may help in pure prose typesetting. In math docs, even if the typeset document spans less than a line, the tex that produces it could span multiple 79 width rows as a single sentence that gives rise to that line.

In any case, I see that it is a known issue and that it is an UltiSnips issue. Let me open an issue at their site for what it is worth.
Thank you.

**Comment by lervag** [comment]
> I see. One sentence per line guideline may help in pure prose typesetting. In math docs, even if the typeset document spans less than a line, the tex that produces it could span multiple 79 width rows as a single sentence that gives rise to that line.

Not sure what you mean. I would use the same guideline for math texts. It is still text. It having equations does not really matter.

Of course, one sentence per line does not include having math environments on one line! Only the actual text, more or less including inline math.

> In any case, I see that it is a known issue and that it is an UltiSnips issue. Let me open an issue at their site for what it is worth. Thank you.

Yes, sounds good. Feel free to make a link here and to let me know if you get any replies!

**Comment by TryerGit** [comment]
> Not sure what you mean. I would use the same guideline for math texts. It is still text. It having equations does not really matter.
 
> Of course, one sentence per line does not include having math environments on one line! Only the actual text, more or less including inline math.

Hmm...Just so I understand correctly your response here: the one sentence per line guideline would not work if you have a longish inline math text sentence that nonetheless typesets to a single line in the pdf. Am I right? Or perhaps I am not understanding the actual meaning of the guideline.

For e.g, consider the following sentence that spans multiple lines -- it would not be possible unless one plays around with `tw` setting to have this sentence span only 79 columns. So, one is forced with the setting of `tw` to be 79 to break this across multiple lines.

![issue](https://user-images.githubusercontent.com/70434658/209660667-9d124737-65c6-43bf-a69b-7882bb177c1f.jpg)

I suppose the guideline cannot be applied in this case, if I understand correctly.

**Comment by lervag** [comment]
I don't think you quite understand, sorry. The idea is probably easier to understand by considering an example:

```tex
Here we write one sentence per line.
This means that we, even in a sentence with expressions like $f(x) = 1$ or \(e^{x + 1} = g(x) + 2\), will not add a linebreak until the sentence is finished.
This means some lines are short.
And some are long.
And that's ok.
Very long sentences will now be easy to recognize, and since you should avoid long sentences, it is actually a good thing that they are easier to distinguish.
```

When I write in this style, I tend to use `set tw=0` to make sure Vim/neovim does not automatically add linebreaks. Further, I also often use `set wrap` so that long sentences are displayed within the editor window (I generally don't use full screen windows).

I hope this makes it easier to understand!

**Comment by TryerGit** [comment]
Thank you for the example. Let me explore the relationship between `tw` and `set wrap`.
