### ISSUE TITLE
Navigating \if \else \fi blocks

### ISSUE THREAD

**Issue by TryerGit** [lervag/vimtex#2609]
Hello,

I have looked at https://github.com/lervag/vimtex/blob/master/doc/targets-textobj-cheatsheet.md and https://github.com/lervag/vimtex/blob/master/VISUALS.md and this issue does not seem to be covered. Hence, this post.

Consider:

```tex
\documentclass{article}
\usepackage{ifthen}
\newif\ifanswer
\answerfalse
\begin{document}

\ifanswer    [Line x]

Answer is true

\else        [Line y]

Answer is false

\fi          [Line z]

\end{document}
```
 
Is it possible to navigate/jump directly from between lines x and y to either of lines x or y and then once there cyclically around lines x, y and z?

The links above do provide navigational facilities between various other constructs, but I could not find anything related to `if...else` constructs. Currently, pressing `%` from within these lines toggles between `\begin{document}` and `\end{document}`

Thanks.

**Comment by lervag** [comment]
No, maching if statements is currently not supported, and I don't plan to add support. However, this is a good time to install vim-matchup (aka match-up)! :)

Please read `:help vimtex-af-enhanced-matchparen`. The plugin is briefly explained there and you can find a link to it. I believe you will find it very useful!
