### ISSUE TITLE
The <m-i> shortcut to insert "\item" elements conflicts with the "é" letter on french keyboards

### ISSUE THREAD

**Issue by elafarge** [lervag/vimtex#261]
Hi lervag,

First of all, thanks and congratulations for your work on this vim plugin, it's awesome :)

The bug described on [this old issue](https://github.com/lervag/vimtex/issues/36) seems to happen again for me. 

As you did last time, I disabled the key binding and [made a PR against your repo](https://github.com/lervag/vimtex/pull/260) to fix the conflict.

Cheers !

Etienne

**Comment by lervag** [comment]
Hi @elafarge! First, thanks for the kind words!

This particular issues has actually already been discussed. Please see [here (#251)](https://github.com/lervag/vimtex/issues/251#issuecomment-149310708). @HerrmannM had the same issue as you. Considering you are now two users who want this mapping removed, I've chosen to agree and instead add the mapping myself as a custom mapping, same as I chose in #36.

**Comment by elafarge** [comment]
Thanks !
