### ISSUE TITLE
Compiler does not work

### ISSUE THREAD

**Issue by Daniel78890** [lervag/vimtex#2618]
### Description

Hello, I am new to vim/neovim. I am using a MacBook Pro and the neovim version 0.8.2. I just want to compile a simple latex file and see the pdf viewer on the side updating changes. I know it is probably something stupid and can't figure it out on my own cause I just started using neovim. If anyone can help me or give me any tips, I will appreciate it. Thank you!

Init.vim:
<img width="1512" alt="Screenshot 2023-01-12 at 9 12 33 PM" src="https://user-images.githubusercontent.com/119009507/212221226-b67a1285-472c-4dad-bb84-3186a4808b27.png">

VimtexInfo:
<img width="1512" alt="Screenshot 2023-01-12 at 9 07 08 PM" src="https://user-images.githubusercontent.com/119009507/212221295-a638d0e4-fcf9-4c4a-b1b0-7562e38b6da9.png">

Checkhealth:
<img width="1512" alt="Screenshot 2023-01-12 at 9 18 25 PM" src="https://user-images.githubusercontent.com/119009507/212221885-6e646715-1dd4-427b-b74d-08139774e902.png">

### Steps to reproduce

1. Neovim: nvim test.tex
2. once inside the file, use command :Vimtexcompile
<img width="1512" alt="Screenshot 2023-01-12 at 8 41 16 PM" src="https://user-images.githubusercontent.com/119009507/212220217-b4e867d2-2e1e-4b64-a9e3-23a7512f9cd5.png">

### Expected behavior

When I follow the steps I expect the file to compile.

### Actual behavior

When I enter the command :VimtexCompiler, I get an error.
<img width="1512" alt="Screenshot 2023-01-12 at 8 42 09 PM" src="https://user-images.githubusercontent.com/119009507/212220425-f2ecddde-e35c-408f-9e8d-7ec05c80334f.png">
<img width="1512" alt="Screenshot 2023-01-12 at 8 41 34 PM" src="https://user-images.githubusercontent.com/119009507/212220436-0d1939e8-18a0-45e2-b779-2dce882c5c2b.png">

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
uploaded a picture in description.
```

**Comment by lervag** [comment]
The problem you are seeing is due lacking `latexmk`. You need to install a LaTeX distribution. It seems MacTeX is the one you want, see here: https://tug.org/mactex/. With Homebrev, you would do `brew install --cask mactex`.

I'm not sure if it will install latexmk directly, or if that is an addon you would install separately afterwards. I found some info here: https://latextools.readthedocs.io/en/latest/install/#os-x. Perhaps it helps?

I know there are a lot of MacOS users here, perhaps one of them would notice this post and help out. 🤞🏻

**Comment by Daniel78890** [comment]
That was the problem! Everything works perfect now! Thank you so much. I really appreciate it.

**Comment by lervag** [comment]
Glad to hear it works :)
