### ISSUE TITLE
Autocompletion in biblatex based on field

### ISSUE THREAD

**Issue by alexandreroberts** [lervag/vimtex#2620]
Prefatory note: I believe that `vimtex` provides functionality for `.bib` files. If I am wrong about this, then the rest of my feature request is irrelevant (because outside the scope of `vimtex`) and should be closed.

**Is your feature request related to a problem? Please describe it.**
When I use autocompletion (with `C-N`) in a `.bib` file, usually I would like the completion to search only other entries in the same field where the cursor is (e.g., if my cursor `*` is in `author = {*}` then I want the autocompletion to look only at other entries in `author` fields). I also want it to be smart enough to parse such fields (e.g., treat different authors in the `author` field as different possibilities for the autocompletion: `author = {Macron, E. and Scholtz, Olaf}` yields two different possible autocompletions, not one). The "problem" is that currently `C-N` uses a full list of all words appearing in the file, as far as I can tell.

**Describe the solution you'd like**
I would like a solution that does as I described above. I apologize if `vimtex` already implements this (maybe using a different command?), but I wasn't able to find it in the documentation or on StackExchange. I made a similar query (more general, not restricted to `vimtex`) [here on vi.SE](https://vi.stackexchange.com/q/39751/37099).

**Describe alternatives you've considered**
Use BibDesk. That is what I currently do, but for obvious reasons it would be nice to be able to work in `nvim` (all the more so if one is not using an Apple computer).

**Comment by lervag** [comment]
> Prefatory note: I believe that `vimtex` provides functionality for `.bib` files.

Well, that _is_ true, although the support is _very_ limited and is much more about providing LaTeX support even if you open a bib file. Still, there is some support, e.g. for indentation rules and similar.

> When I use autocompletion (with `C-N`) in a `.bib` file,

This is not _auto_completion. `<c-n>` starts what is kalled keyword completion, and it is not really in itself very customizable (see `:help i_CTRL-N`).

VimTeX provides an omni-completion function for LaTeX (see `:help compl-omni`). There are a lot of autocomplete plugins that provide engines for doing real autocompletion. These plugins usually combine many sources, both keywords completion, omni-completion, and others. I've tried to explain very briefly under `:help vimtex-completion` and I suggest you read that and `:help vimtex-complete-auto`.

Now, for completion in `.bib` files: This is not currently a feature. I do think you are proposing a slightly useful feature, but I am unfortunately quite overloaded and I believe there are _better_ ways to work with your bibfiles than to manually write out author names and entries.

For instance, if you use [Zotero](https://www.zotero.org/) to manage your bibliographies, you can easily synchronize collections to a bib file. There are also other similar tools, like [papis](https://github.com/papis/papis). The latter also has a neovim plugin [papis.nvim](https://github.com/jghauser/papis.nvim), however I've never tried that myself.

**Comment by alexandreroberts** [comment]
Thank you for this helpful clarification, and for the reference to papis, which I didn't know about. As far as I can tell those other tools, including Zotero, store bibliographical information in a format other than biblatex, mostly yaml. This is probably fine for most use cases, but because I work in the humanities, many of my references do not conform to the assumptions made by most of those programs (this is definitely true of Zotero, which I have tried; about the others I am not so sure). (I suppose it is not yaml per se that is the problem but rather the assumptions that these programs make.) I use `biblatex-chicago`, which extends the functionality of built-in biblatex tremendously, so I think it makes most sense to store my bibliographies in the `biblatex` format.

That said, of course I understand that incorporating tools to more easily edit `.bib` files into `vimtex` may not be a top priority. So for now I will stick with BibDesk and hope that one day a vim alternative comes along.

**Comment by lervag** [comment]
> Thank you for this helpful clarification, and for the reference to papis, which I didn't know about. As far as I can tell those other tools, including Zotero, store bibliographical information in a format other than biblatex, mostly yaml. This is probably fine for most use cases, but because I work in the humanities, many of my references do not conform to the assumptions made by most of those programs (this is definitely true of Zotero, which I have tried; about the others I am not so sure). (I suppose it is not yaml per se that is the problem but rather the assumptions that these programs make.) I use `biblatex-chicago`, which extends the functionality of built-in biblatex tremendously, so I think it makes most sense to store my bibliographies in the `biblatex` format.

This should not really be a problem. The point is that you can use Zotero to export your collection to a `.bib` file with the better-bibtex extension. It can even keep the file updated automatically when you make changes to your Zotero collections. Thus, Zotero should be compatible with biblatex and probably also the `biblatex-chicago` package. I'm not very familiar with that specific style/package, but I have used biblatex and I don't see how there should be a problem.

Btw: You may be interested in reading the issue thread of a related issue #2596.

**Comment by alexandreroberts** [comment]
Thank you for the link to that other thread, which I looked through with great interest, since it also discusses how to use Zotero with .bib and nvim.

About using Zotero, the main weakness I have come across is how it handles edited volumes, which are common in my field (a book with an editor but with separate authors of each chapter, which is typically a sort of free-standing article of its own). With `biblatex-chicago` one can make a ***@***.***` entry for the whole volume and then simply create ***@***.***` entries for each chapter in the volume (that is, only the chapters one actually wishes to cite), with a `crossref` to the parent `book` entry. The only way I know how to represent such chapters in Zotero is to repeat all of the book's information for each chapter (which Zotero calls a "book section", I believe -- or is that Endnote?).

**Comment by lervag** [comment]
> About using Zotero, the main weakness I have come across is how it handles edited volumes, which are common in my field (a book with an editor but with separate authors of each chapter, which is typically a sort of free-standing article of its own). With `biblatex-chicago` one can make a `***@***.***` entry for the whole volume and then simply create `***@***.***` entries for each chapter in the volume (that is, only the chapters one actually wishes to cite), with a `crossref` to the parent `book` entry.

Good point; I don't know how to do this with Zotero without duplicating content a lot. Still, it may be possible. I would suggest, if you are interested in looking further into this, that you ask at one of the Zotero forums/resources. (And if you do, feel free to share your findings back here!)
