### ISSUE TITLE
Add `g:vimtex_view_sioyek_options` to allow `--reuse-window`

### ISSUE THREAD

**Issue by HakonHarnes** [lervag/vimtex#2621]
Relevant issue: #2468. 

**Problem description**

I use the subfiles latex package to sub-compile latex files (by toggling `VimtexToggleMain`) to reduce compilation time. At the moment, a new sioyek window is opened for each file that is compiled. I'd like to have _one_ sioyek window that automatically opens the compiled files. This is possible using the `--reuse-window` option in sioyek (similar to the now deprecated `--reuse-instance` option). 

As issue #2468 suggests, this is possible by setting `should_launch_new_instance 0` in the sioyek configuration file. However, I don't want to always have this option enabled, since I often do want sioyek to open multiple windows in other situations. Therefore, I need to pass `--reuse-window` as a command line flag when using vimtex. 

**Proposed solution**

As suggested in #2468, add a `g:vimtex_view_sioyek_options`.

**Comment by lervag** [comment]
Done! :)

**Comment by HakonHarnes** [comment]
> Done! :)

Takk! Fantastisk plugin :)

**Comment by lervag** [comment]
Bare hyggelig; glad du liker den :)
