### ISSUE TITLE
Error: Zathura is not executable!

### ISSUE THREAD

**Issue by tim0120** [lervag/vimtex#2624]
### Description

VimTex is not loading properly (i.e., running `:Vimtex` returns the error `E492: Not an editor command: VimtexInfo`). Running `:help vimtex` does looad `vimtex.txt`, though.

Running `:checkhealth vimtex` gives me the title error, i.e., `ERROR: Zathura is not executable!`.

Any suggestions on how to resolve this?
Sorry if this is a lacking description, I am new to (n)vim plugins/customization in general. I can provide any other information if it helps.

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
n/a (explained in description)
```

**Comment by lervag** [comment]
I believe you are having two issues. First, it seems you trying to lazy load VimTeX. Please don't! If that is not the issue: VimTeX only loads for LaTeX buffers, so `:VimtexInfo` is not available unless you open a `.tex` file.

Now, it seems you have `let g:vimtex_view_method = 'zathura'` but Zathura is not found on your system. As a first step, just remove the option. Let's solve your main issue first.

**Comment by lervag** [comment]
> > I believe you are having two issues. First, it seems you trying to lazy load VimTeX. Please don't! If that is not the issue: VimTeX only loads for LaTeX buffers, so `:VimtexInfo` is not available unless you open a `.tex` file.
> 
> Thank you this was exactly correct. Also a quick question about this response: I am pretty new to VimTeX (and vim plugins in general), and I do not know what it means to "lazy load" VimTeX (or other plugins). Could you explain what this means?

Yes: There's a big hype around lazily loading plugins these days. This means using plugin managers like vim-plug, packer or lazy.nvim with options that avoid actually loading a plugin until necessary. The idea is to save some time on neovim/Vim startup time. However, a lot of plugins, like VimTeX, is already implemented lazily in the sense that VimTeX does not load until you need it anyway. And if you were to actively lazy load it as explained above, you also prevent it from loading a few things that is necessary for some features to work (see `:help VimtexInverseSearch`).

> > Now, it seems you have let `g:vimtex_view_method = 'zathura'` but Zathura is not found on your system. As a first step, just remove the option. Let's solve your main issue first.
> 
> Turns out zathura doesn't run well on silicon Macs, so I decided to use Silk instead, as suggested in [this article on setting up a pdf reader for VimTeX](https://www.ejmastnak.com/tutorials/vim-latex/pdf-reader/).

Ah, I see. There's also a little faq on this, see `:help vimtex-faq-zathura-macos`. I strive to have a good documentation for most things, so I would claim it is a good investment to read the full introduction and just skim the table of contents. If you have some trouble, you may often find answers by opening the help file and searching for relevant keywords.
