### ISSUE TITLE
Syntax for package "comment": \begin{env}[options] and \end{env} appear as not being commented

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2626]
Following LaTeX file
```tex
\documentclass{article}
\usepackage{comment} 

\begin{document}

\begin{comment}
  text text text text text text text text text text text text text 
  $a=b$
  text text text text text text text text text text text text text 
\end{comment}


\begin{comment}
  text text text text text text text text text text text text text 
  \begin{equation}
    a=b
  \end{equation}
  text text text text text text text text text text text text text 
  \begin{empheq}[box=\widefbox]{align*}
    c_1 &= a\\
    c_2 &= b\\
    c_3 &= c
  \end{empheq}
  text text text text text text text text text text text text text 
\end{comment}

\end{document}
```
appears in neovim 0.8.2 with vimtex installed as following
![Screenshot 2023-02-02 at 08 05 11](https://user-images.githubusercontent.com/371756/216255142-cc8269fd-d07e-47b5-a0c8-fa5355fe0a00.png)

**Describe the solution you'd like**
Lines 15, 17, 19, and 23 should also be greyed out.

**Comment by kiryph** [comment]
> And it seems very unlikely that anyone would actually do this in real life?

I would not do this. I could imagine that other people are doing it, but I am not one of them.
IMHO the edge case of nested comment environment is not important enough to find a completely new technique.

Thanks as always for the quick fix.

**Comment by lervag** [comment]
Hmm.. I guess it is a good rule to never assume what other people will do or not do ;)

Anyway, I'm happy to get good issues that help me keep improving VimTeX. So thanks to you for reporting!
