### ISSUE TITLE
Adding PdfAnnots in Lua

### ISSUE THREAD

**Issue by benbrastmckie** [lervag/vimtex#2631]
As also posted of [Reddit](https://www.reddit.com/r/neovim/comments/10vlvr6/pdfannots_in_lua/), I am looking to rewrite the vimscript provided in issue #2294 in Lua. The purpose of this function is to runs [PdfAnnots](https://github.com/0xabu/pdfannots) on the pdf associated with the citation under the cursor. I find that this provides a nice complement to the features already provided by the VimTex context menu. The vimscript to run PdfAnnots from before is as follows:
```vim
function PdfAnnots() abort
  try
    let infile = vimtex#context#get().handler.get_actions().entry.file
  catch /E121/
    echo "No file found"
    return
  endtry

  let cwd = getcwd()
  try
    call chdir(b:vimtex.root)

    if !isdirectory('Annotations')
      call mkdir('Annotations')
    endif

    let outfile = "Annotations/" . fnamemodify(infile, ':t:r') . '.md'
    call system(printf('pdfannots -o "%s" "%s"', outfile, infile))

    execute 'split' fnameescape(outfile)
  finally
    call chdir(cwd)
  endtry
endfunction
```
Any help converting this to lua would be much appreciated!

**Comment by lervag** [comment]
I believe the following should work (or at least more or less):

```lua
local function PdfAnnots()
  local ok, pdf = pcall(vim.api.nvim_eval,
    "vimtex#context#get().handler.get_actions().entry.title")
  if not ok then
    vim.notify "No file found"
    return
  end


  local cwd = vim.fn.getcwd()
  vim.fn.chdir(vim.b.vimtex.root)

  if vim.fn.isdirectory('Annotations') == 0 then
    vim.fn.mkdir('Annotations')
  end

  local md = vim.fn.printf("Annotations/%s.md", vim.fn.fnamemodify(pdf, ":t:r"))
  vim.fn.system(vim.fn.printf('pdfannots -o "%s" "%s"', md, pdf))
  vim.cmd.split(vim.fn.fnameescape(md))

  vim.fn.chdir(cwd)
end
```

I did not properly test this, that is, I did not test the `pdfannots` command specifically. Perhaps `vim.fn.system` should be replaced with something else more modern here. If anyone should observe this and knows a better way, I would be glad to be enlightened!

**Comment by benbrastmckie** [comment]
Thanks so much! I put the code above in tex.lua which lives in `nvim/after/ftplugin`. Although I did not get any errors upon reloading my config, it did throw the error, "E5108: Error executing lua [string ":lua"]:1: attempt to call global 'PdfAnnots' (a nil value) stack traceback: [string ":lua"]:1: in main chunk" once I ran the command `lua PdfAnnots()`. I also tried running `call PdfAnnots()`, but that raised the error, "Unknown function: PdfAnnots". If there is some obvious mistake that I'm making, or something I can try to troubleshoot, I'd be curious to know.

Thanks again!

**Comment by lervag** [comment]
I believe this is because of `local`: you probably want to make it a global function (i.e. remove `local` from `local function ...`. Alternatively, you could make a mapping, e.g. add the following lines:

```lua
vim.keymap.set("n", "<localleader>la", PdfAnnots, { buffer = true })
```

**Comment by benbrastmckie** [comment]
Ah that makes sense, and definitely helps. It now runs, creating a 'Annotations' directory and a md file in that directory for the associated pdf. Unfortunately, the md file it creates is empty. I tested PdfAnnots in the terminal and it works great on its own, so PdfAnnots isn't the issue. I wonder if it has to do with the way that the file name is provided since I notice that for certain papers, e.g. "A Theory of Truthmaker Content II", the name of the file it creates includes lots of extra braces, e.g., "A {{Theory}} of {{Truthmaker Content II}}". This doesn't happen for files without spaces, e.g. the file for a paper named "Causation" was named properly without any extra braces. Anyhow, seems like a clue, though I can't quite figure out how to fix the problem, or identify if this is what is causing the md files to be empty.

**Comment by lervag** [comment]
Ah, sorry; while making this I changed `.file` to `.title` in the third line. I think that's the problem here.

**Comment by benbrastmckie** [comment]
I tried changing `.title` back to `.file`, but now it reports 'No file found'. I'm not sure if this is related, but have also noticed that in the VimTex context menu it is no longer possible to launch the pdf directly from Vim the way it used to be. What I see instead is:
```
Context menu for citekey Hall2004a
1: Edit entry
2: Show entry
x: Abort
```
Could it be a more general issue with VimTex locating the file in a lua config? Happy to try anything else that might help identify the problem.

**Comment by lervag** [comment]
Does the entry in your bib file actually _have_ the `file` key? What's the output of "Show entry" for the specified key?

**Comment by benbrastmckie** [comment]
That was the issue! I have been using `bibexport` to generate a small bib file for my papers, but it does not preserve the `file` key. Anyhow, I'll revise my workflow to accommodate this. Thanks so much for your help. I really appreciate it.

**Comment by lervag** [comment]
> Thanks so much for your help. I really appreciate it.

Glad to hear you figured it out, and glad to help! :)
