### ISSUE TITLE
Vimtex stops working after update

### ISSUE THREAD

**Issue by AadiWaghray** [lervag/vimtex#2640]
### Description

First off, apologies if my issue is due to my incompetence and not a bug. Even though I use vimtex to complete literally every assignment in my life, I have next to no clue how the plugin works. After running `:PlugUpdate` and installing the `coc-vimtex` extension, none of the vimtex commands work in my latex files. I think there was a pop-up when I was entering one of my `.tex` files that said something along the lines of ignore user config, but I don't remember and thought nothing of it as my ultisnips config has some issues (that I need to resolve at some point) and often leads to popups. I can run `:h vimtex`. My `init.vim` has `let g:tex_flavor='latex'`. I removed vimtex with `:PlugClean` and reinstalled it. However, when I update it now, it just says OK instead of Already up to date! like the rest of the plugins. When I run any Vimtex command, vim tells me it is not an editor command. Given the nature of the issue, I am not sure what are relevant settings to provide the minimal files or steps to follow to reproduce. Thank you for any help. 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
Says not an editor command.
```

**Comment by lervag** [comment]
Can you share your configuration? Either link to dotfiles repo or verbatim here?

**Comment by AadiWaghray** [comment]
"""""""""""""""""""
""VimTex config  ""
"""""""""""""""""""
let g:tex_flavor='latex'
let g:vimtex_view_method='skim'
let g:vimtex_quickfix_mode=0
set conceallevel=2
let g:tex_conceal='abdmg'

**Comment by lervag** [comment]
Ok, so:

1. Remove both `g:tex_flavor` and `g:tex_conceal` - these options are not relevant for VimTeX.
2. Please notice that the `conceallevel` option is "local to window" (see the docs). I recommend that you read `:help option-summary` and `:help conceallevel` to understand what that means and why it

**Comment by lervag** [comment]
Further: you now provided the VimTeX related configuration, but the problem you describe is more likely with your general configuration and with how you load VimTeX. Can you show me your _full_ configuration?

**Comment by AadiWaghray** [comment]
https://github.com/AadiWaghray/dotfiles

**Comment by lervag** [comment]
Some comments:

```vim
Plug 'KeitaNakamura/tex-conceal.vim', {'for': 'tex'}
Plug 'lervag/vimtex', {'tag': 'v1.6'}
```

Why did you pin VimTeX to `v1.6`? With the latest version, you will probably not want `tex-conceal.vim` either.

```vim
filetype plugin indent on
```

You don't need that; `call plug#end()` applies it for you.

The `g:tex_*` variables are not relevant when you use VimTeX. You can safely remove lines 104 to 106, 112 and 116.

Except for this, I don't see anything specifically wrong here. I would suggest you clean up your `init.vim` somewhat; e.g. remove commented lines (you already have Git history, so no need to keep the garbage), etc.

After applying the changes suggested and doing `:PlugClean` and `:PlugUpdate` - what's the result of doing `:VimtexInfo` (you must open a tex file first, of course)?

**Comment by AadiWaghray** [comment]
Thank you so much for the advice. I wasn't sure why I did the specific settings you critiqued. I sort of just wanted to have a tex editor that worked well so followed random guides without understanding them. Vimtex started working again. Here is the result of the command. Additionally, if there are any general guidelines I should follow when organizing my init.vim file please let me know. 

System info:
  OS: macOS 13.0.1 (22A400)
  Vim version: NVIM v0.8.0-dev-775-g27ce21ac8
  Has clientserver: true
  Servername: /var/folders/pp/r7_p49sx7b94ztpczpwhflmm0000gn/T/nvim.aadiwaghray/r7yGoZ/nvim.52476.0

VimTeX project: Homework_5
  base: Homework_5.tex
  root: /Users/aadiwaghray/Documents/College_Notes/Phys_461/Homework_5
  tex: /Users/aadiwaghray/Documents/College_Notes/Phys_461/Homework_5/Homework_5.tex
  main parser: current file verified
  document class: report
  packages: algorithm2e amsbsy amsfonts amsgen amsmath amsopn amssymb amstext amsthm array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bigintcalc bitset bookmark calc cancel centernot color comment enumitem environ epstopdf-base eso-pic etexcmds etoolbox expl3 geometry gettitlestring graphics graphicx hycolor hyperref ifmtarg ifoddpage iftex ifthen ifvtex import infwarerr inputenc intcalc keyval kvdefinekeys kvoptions kvsetkeys l3keys2e letltxmacro listings listingsutf8 lscape lstlang1 lstmisc ltxcmds mathtools mhsetup multicol nameref newpxmath pdfcol pdfescape pdflscape pdfpages pdftexcmds pgf pgfcomp-version-0-65 pgfcomp-version-1-18 pgfcore pgffor pgfkeys pgfmath pgfrcs pgfsys physics pict2e qtree refcount relsize rerunfilecheck shellesc stringenc tcolorbox textcomp theoremref tikz tikz-cd tikzsymbols titletoc transparent trig trimspaces uniquecounter url varwidth verbatim xcolor xfrac xifthen xkeyval xparse xspace xtemplate
  source files:
    Homework_5.tex
    ../preamble.tex
    ../macros.tex
    ../letterfonts.tex
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
    job: 
      jobid: 6
      output: /var/folders/pp/r7_p49sx7b94ztpczpwhflmm0000gn/T/nvim.aadiwaghray/r7yGoZ/1
      cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode -pdf -pvc -view=none -e '$compiling_cmd = ($compiling_cmd ? $compiling_cmd . " ; " : "") . "echo vimtex_compiler_callback_compiling"' -e '$success_cmd = ($success_cmd ? $success_cmd . " ; " : "") . "echo vimtex_compiler_callback_success"' -e '$failure_cmd = ($failure_cmd ? $failure_cmd . " ; " : "") . "echo vimtex_compiler_callback_failure"' 'Homework_5.tex'
      pid: 52480
  viewer: Skim
  qf method: LaTeX logfile

**Comment by lervag** [comment]
> Thank you so much for the advice. I wasn't sure why I did the specific settings you critiqued. I sort of just wanted to have a tex editor that worked well so followed random guides without understanding them.

I'm glad to help. There are a lot of guides online, some of them are very dated. I strongly advice that you aim to understand the configuration you copy from such guides. If you don't, then you take a high risk of getting in trouble. :)

> Additionally, if there are any general guidelines I should follow when organizing my `init.vim` file please let me know.

I think a couple of good general rules are:

* Try and understand the configuration that you use. Avoid adding too much stuff just because you read somewhere that it is useful.
* Avoid using too many plugins; it is OK to take things slow.
* Here are some guides/links that I can recommend:
  * [Seven habits of effective text editing](http://moolenaar.net/habits.html)
  * [Steps to learn Vim](https://blog.joren.ga/tools/vim-learning-steps)
  * [Your problem with Vim is that you don't grok vi](http://stackoverflow.com/questions/1218390/what-is-your-most-productive-shortcut-with-vim/1220118#1220118)
  * [/r/vim/wiki/vimrctips](https://www.reddit.com/r/vim/wiki/vimrctips)
