### ISSUE TITLE
[Syntax Conceal] \vec{a} as a in bold

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2641]
The documentation gives following two options to customize concealment of commands

- `g:vimtex_syntax_custom_cmds`
- `g:vimtex_syntax_custom_cmds_with_concealed_delims`

An example configuration for the first is given as well:

```viml
    let g:vimtex_syntax_custom_cmds = [
          \ {'name': 'vct', 'mathmode': 1, 'argstyle': 'bold'},
          \ {'name': 'R', 'mathmode': 1, 'concealchar': 'ℝ'},
          \ {'name': 'mathnote', 'mathmode': 1, 'nextgroup': 'texMathTextArg'},
          \ {'name': 'nospell', 'argspell': 0},
          \]
```

However, this does not conceal `\vec{a}` as `a` in bold but sets `a` in bold but does not hide `\vec{` and `}`, as seen in following picture

![Screenshot 2023-02-23 at 10 13 29](https://user-images.githubusercontent.com/371756/220865033-8694c147-5b00-4954-b6a0-9e5f1411c2ca.png)

The second option does not provide an `argstyle` option.

Is it is possible to add an `argstyle` option to `g:vimtex_syntax_custom_cmds_with_concealed_delims`?

```viml
    let g:vimtex_syntax_custom_cmds_with_concealed_delims = [
          \ {'name': 'vec',
          \  'mathmode': 1,
          \  'argstyle': 'bold',
          \  'cchar_open': '',
          \  'cchar_close': ''},
          \]
```

**Comment by lervag** [comment]
> However, this does not conceal `\vec{a}` as `a` in bold but sets `a` in bold but does not hide `\vec{` and `}`, as seen in following picture

The conceal you want can be achieved with this:

```vim
let g:vimtex_syntax_custom_cmds = [
      \ {'name': 'vec', 'mathmode': 1, 'conceal': 1, 'argstyle': 'bold'},
      \}
```

> The second option does not provide an `argstyle` option.

Yes, I can add that.

But notice that the point of the second option is to allow a specific type of command conceals where `\foo{bar}` is matched and concealed as `XbarY` where `X` and `Y` can be passed as options. This is not possible with the former option, which is a much more general type of customization.

**Comment by kiryph** [comment]
Sorry, I missed `'conceal'` in the documentation to `g: vimtex_syntax_custom_cmds`.

Thanks for the quick help.

**Comment by lervag** [comment]
No problem; glad to help! :)
