### ISSUE TITLE
[Syntax Conceal] Conceal completely \hphantom{arg}

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2642]
Is it possible to  conceal `\hphantom{arg}` completely?

**Comment by kiryph** [comment]
I have created for neovim the file `~/.config/nvim/after/syntax/tex.vim` with the content:
```viml
syntax match texCmd "\\hphantom{.\{-}} \?" conceal
syntax match texMathCmd "\\hphantom{.\{-}} \?" contained conceal
```

**Comment by lervag** [comment]
The following code works for me (you could put it in `after/syntax/tex.vim`, for instance):

```vim
syntax match texCmdPhantom "\\hphantom\>"
      \ conceal skipwhite nextgroup=texPhantomArg
syntax match texMathCmdPhantom "\\hphantom\>"
      \ conceal skipwhite nextgroup=texPhantomArg
syntax cluster texClusterMath add=texMathCmdPhantom

call vimtex#syntax#core#new_arg('texPhantomArg', {
      \ 'opts': 'contained conceal',
      \ 'contains': 'texPhantomGroups',
      \})
call vimtex#syntax#core#new_arg('texPhantomGroups', {
      \ 'matchgroup': 'matchgroup=NONE',
      \ 'opts': 'contained conceal',
      \ 'contains': 'texPhantomGroups',
      \})

highlight def link texCmdPhantom       texCmd
highlight def link texPhantomArg       texArg
highlight def link texPhantomGroups    texPhantomArg
```

I could add this to VimTeX as a feature - do you think that would be useful? Should it be enabled by default with a flag in `g:vimtex_syntax_conceal`?

**Comment by lervag** [comment]
By the way: a core idea to make this work is to use `syntax region` to match the brace groups. That way we don't have to use regexps to match nested levels (reg exps are generally _not_ suitable for that type of parsing).

**Comment by kiryph** [comment]
Thanks for all your feedback.

> By the way: a core idea to make this work is to use syntax region to match the brace groups. That way we don't have to use regexps to match nested levels (reg exps are generally not suitable for that type of parsing).

It is great that there is proper solution to this and I totally agree that reg exps are here not the right tool.

> I could add this to VimTeX as a feature - do you think that would be useful? Should it be enabled by default with a flag in g:vimtex_syntax_conceal?

Obviously, I find it useful. 

The popular answer on https://tex.stackexchange.com/questions/74353/what-commands-are-there-for-horizontal-spacing lists quite a few commands to add horizontal spacing. `\hphantom` is listed there on position 13.

VimTeX already conceals a part from this list:

https://github.com/lervag/vimtex/blob/b527d75dca0e2fef64b9d0ef8ccd6d707e1c0d33/autoload/vimtex/syntax/core.vim#L2033-L2061

So one could argue that `\hphantom fits into the group 

https://github.com/lervag/vimtex/blob/b527d75dca0e2fef64b9d0ef8ccd6d707e1c0d33/autoload/vimtex/syntax/core.vim#L645-L648

Actually I have added myself `\>` as well

```

**Comment by kiryph** [comment]
And I actually have added `cchar= ` (space), since it usually introduces additional whitespace.

**Comment by lervag** [comment]
> The popular answer on https://tex.stackexchange.com/questions/74353/what-commands-are-there-for-horizontal-spacing lists quite a few commands to add horizontal spacing. `\hphantom` is listed there on position 13.
> 
> VimTeX already conceals a part from this list:

Ah, yes, I agree. I've pushed an update that adds conceals for `\phantom` and `\hphantom` now. Should we also add the `cchar=`? I guess its subjective if that's desireable, but I don't want to add an option for it... I'll just go with whatever you find best. :)

**Comment by kiryph** [comment]
> Should we also add the cchar=? I guess its subjective if that's desireable, but I don't want to add an option for it... I'll just go with whatever you find best. :)

I see: delegating the blame/pressure 😅 .

I would go with what is done until now, i.e. no space. Do not change existing behaviour except someone comes with a good reason.

I agree that this is subjective. Concealment in general feels this ways since it is only an approximation and it depends on how one writes tex code and formats it. I actually have changed a few places how I format my code due to enabling concealment (e.g. no alignment of `\\` in matrices since they appear at some arbitrary column).

**Comment by lervag** [comment]
> > Should we also add the cchar=? I guess its subjective if that's desireable, but I don't want to add an option for it... I'll just go with whatever you find best. :)
> 
> I see: delegating the blame/pressure sweat_smile .

;)

> I would go with what is done until now, i.e. no space. Do not change existing behaviour except someone comes with a good reason.

Sounds good!

> I agree that this is subjective. Concealment in general feels this ways since it is only an approximation and it depends on how one writes tex code and formats it. I actually have changed a few places how I format my code due to enabling concealment (e.g. no alignment of `\\` in matrices since they appear at some arbitrary column).

Yes. I personally don't like the conceals and don't use them.

**Comment by kiryph** [comment]
> I personally don't like the conceals and don't use them.

I am always impressed about the many features and quality of them you have added which you do not use yourself. Thank you for this.

**Comment by lervag** [comment]
I find pleasure in trying to solve (sometimes hard) problems in a good way. As I'm no longer in academia, I also use LaTeX more seldom personally, but I still find it fun to tinker with VimTeX. :)
