### ISSUE TITLE
[RFC] Further concealments: math matrices & envs, alignment character, conceal first space after left delimiter word e.g. \langle

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2645]
I am evaluating the concealment feature how much I would conceal to increase the readability:

I am trying following:

1. Math matrices
1. Math environments `\begin{equation|...}` and `end{equation|...}`
2. Alignment character `&`
3. First space after left delimiter word e.g. `\langle`

```viml
" Amsmath Matrices
" \begin{Vmatrix|vmatrix|Bmatrix|bmatrix|matrix|pmatrix|smallmatrix} \end{...}
syntax match texCmdEnvM "\\begin{Vmatrix}"     contained conceal cchar=║
syntax match texCmdEnvM "\\end{Vmatrix}"       contained conceal cchar=║
syntax match texCmdEnvM "\\begin{vmatrix}"     contained conceal cchar=|
syntax match texCmdEnvM "\\end{vmatrix}"       contained conceal cchar=|
syntax match texCmdEnvM "\\begin{Bmatrix}"     contained conceal cchar={
syntax match texCmdEnvM "\\end{Bmatrix}"       contained conceal cchar=}
syntax match texCmdEnvM "\\begin{bmatrix}"     contained conceal cchar=[
syntax match texCmdEnvM "\\end{bmatrix}"       contained conceal cchar=]
syntax match texCmdEnvM "\\begin{pmatrix}"     contained conceal cchar=(
syntax match texCmdEnvM "\\end{pmatrix}"       contained conceal cchar=)
syntax match texCmdEnvM "\\begin{smallmatrix}" contained conceal cchar=(
syntax match texCmdEnvM "\\end{smallmatrix}"   contained conceal cchar=)
syntax match texCmdEnvM "\\begin{matrix}"      contained conceal
syntax match texCmdEnvM "\\end{matrix}"        contained conceal

" Hide Array
syntax match texMathCmdEnv "\\begin{array}{.\{-}}" contained conceal
syntax match texMathCmdEnv "\\end{array}"          contained conceal

" Hide math environments similar to \[ \]
syntax match texMathEnvBgnEnd "\\begin{equation\*\?}" contained conceal
syntax match texMathEnvBgnEnd "\\end{equation\*\?}"   contained conceal
syntax match texMathEnvBgnEnd "\\begin{align\*\?}"    contained conceal
syntax match texMathEnvBgnEnd "\\end{align\*\?}"      contained conceal
syntax match texMathEnvBgnEnd "\\begin{gather\*\?}"   contained conceal
syntax match texMathEnvBgnEnd "\\end{gather\*\?}"     contained conceal
syntax match texMathEnvBgnEnd "\\begin{aligned\*\?}"  contained conceal
syntax match texMathEnvBgnEnd "\\end{aligned\*\?}"    contained conceal

syntax match texCmdEnvM "\\begin{alignat\*\?}{.\{-}}" contained conceal
syntax match texCmdEnvM "\\end{alignat\*\?}"          contained conceal

syntax match texCmdEnvM "\\begin{empheq\*\?}\(\[.\{-}\]\)\?{.\{-}}" contained conceal
syntax match texCmdEnvM "\\end{empheq\*\?}"                         contained conceal

" Conceal alignment character
syntax match texTabularChar /&/ conceal
syntax match texTabularChar /&/ contained conceal
```

For the math enviornments and the alignment character I feel like this should be optional and possibly by default turned off.

Currently, only the concealment for sections as markdown/atx formatting is disabled:

https://github.com/lervag/vimtex/blob/b527d75dca0e2fef64b9d0ef8ccd6d707e1c0d33/doc/vimtex.txt#L2410-L2424

I also have refined the concealment of `\langle` as following:

```viml
" Refined concealment: capture optional space " \?"
syntax match texMathDelim "\\langle\> \?" contained conceal cchar=⟨
```
To understand the motivation consider this part of an equation:
```tex
\forall \{i,j;n_k\} \in E(\langle G,n\rangle)
```
is now displayed as
![Screenshot 2023-02-24 at 13 33 27](https://user-images.githubusercontent.com/371756/221180062-3f38bfca-7cc3-4fb6-bf2c-315f6723380a.png)

and without the refinement it looks like following:
![Screenshot 2023-02-24 at 13 34 36](https://user-images.githubusercontent.com/371756/221180237-87bda0b0-ca86-4b03-a2b1-71ab5b488213.png)

Do you see the additional space after `〈` ?

I am not sure about them yet. I guess time will tell. If others consider them also worthwhile, they could express their interest.

**Comment by kiryph** [comment]
And also `\{` and `\}` could be concealed:
```vim
syntax match texMathDelim contained conceal cchar={ "\\{"
syntax match texMathDelim contained conceal cchar=} "\\}"
```

**Comment by lervag** [comment]
Sorry, but I'm a little bit confused as to what you are proposing here. It seems to be several different things (all though all of them related to conceals). I'll start by addressing what I understand:

> I also have refined the concealment of `\langle` as following:

I agree this makes sense. Perhaps one could do symmetrical it like this?

```vim
  syntax match texMathDelim contained conceal cchar=⟨ '\\langle\>\s*'
  syntax match texMathDelim contained conceal cchar=⟩ '\s*\\rangle\>'
```

If we add this, then I think it should be done for all variants similarly.

> And also `\{` and `\}` could be concealed:
> 
> ```viml
> syntax match texMathDelim contained conceal cchar={ "\\{"
> syntax match texMathDelim contained conceal cchar=} "\\}"
> ```

Yes, I agree; I'm adding that now.

----

Now, for the first part, it seems you are suggesting _new_ conceals of math related stuff. I think it would be easier to discuss them if they are raised as separated suggestions. But OK:

> * Math matrices

This seems relevant and I could consider adding that. I think they should be optional, perhaps opt-in?

> * Math environments `\begin{equation|...}` and `end{equation|...}`

I don't really like this; but, as mentioned elsewhere, I don't use conceals, and perhaps people who use them would find this useful..? At least, it should be opt-in.

> * Alignment character `&`

This feels as something that might make things confusing, so I'm again a little bit skeptical.

**Comment by kiryph** [comment]
Sorry for not splitting it into different issues. I didn't want to spam you today. But I guess you would have prefered it in different issues. I will do this the next time. Since you already started answering each point, I will proceed here:

1. **Math matrices:** the safe set should be with visible characters  
    ```viml
    syntax match texCmdEnvM "\\begin{Vmatrix}"     contained conceal cchar=║
    syntax match texCmdEnvM "\\end{Vmatrix}"       contained conceal cchar=║
    syntax match texCmdEnvM "\\begin{vmatrix}"     contained conceal cchar=|
    syntax match texCmdEnvM "\\end{vmatrix}"       contained conceal cchar=|
    syntax match texCmdEnvM "\\begin{Bmatrix}"     contained conceal cchar={
    syntax match texCmdEnvM "\\end{Bmatrix}"       contained conceal cchar=}
    syntax match texCmdEnvM "\\begin{bmatrix}"     contained conceal cchar=[
    syntax match texCmdEnvM "\\end{bmatrix}"       contained conceal cchar=]
    syntax match texCmdEnvM "\\begin{pmatrix}"     contained conceal cchar=(
    syntax match texCmdEnvM "\\end{pmatrix}"       contained conceal cchar=)
    syntax match texCmdEnvM "\\begin{smallmatrix}" contained conceal cchar=(
    syntax match texCmdEnvM "\\end{smallmatrix}"   contained conceal cchar=)
    ```

   I am not sure whether `matrix` and `array` is desired by everyone (since they simply vanish).

2. **Math environments.** I am actually not sure myself. I have a vim-unimpaired style toggle `yoe` to quickly disable concealment. I think one can leave this until someone else is interested (or only by default off). I have it for now in the personal `after/ftplugin/tex.vim` file.

3. **Alignment character &** Again, I agree this can be confusing. This can be done in a personal configuration as well.

4. **I also have refined the concealment of \langle**  
   > Perhaps one could do symmetrical it like this?

   I like this and yes doing it for all similar delimiters would also be the proper way.

6. `\{` `\}` thanks for adding them


Here two screenshots of 
```tex
\paragraph{Modulus of the position vector}
\begin{align*}
  \|\vec{r}\|^2  &= (x, y, z) \mat{G} \begin{pmatrix} x \\ y \\ z \\ \end{pmatrix} \\
    &= x^2 g_{11} + y^2 g_{22} + z^2 g_{33} + 2yz g_{23} + 2xz g_{13} + 2xy g_{12} \qquad\text{(3D)} \\
    &= x^2 g_{11} + y^2 g_{22} + 2xy g_{12} \qquad\text{(2D)}
\end{align*}
```
![Screenshot 2023-02-24 at 16 35 01](https://user-images.githubusercontent.com/371756/221220388-f9acda9b-9ed1-42d3-a90e-3bfa70f085b6.png)
![Screenshot 2023-02-24 at 16 35 30](https://user-images.githubusercontent.com/371756/221220581-d2610cf0-e755-4597-a494-6e3a6ce4c553.png)

which illustrate many concealments including the discusse `pmatrix`, math env `align` and the alignment character `&`.

**Comment by lervag** [comment]
> Sorry for not splitting it into different issues. I didn't want to spam you today. But I guess you would have prefered it in different issues. I will do this the next time.

Thanks; yes, I actually _do_ prefer multiple small issues. It makes it easier to work fast on a single item, as I don't need to work through a lot of unrelated content (or, perhaps not unrelated, but, you know what I mean).

----

> 1. **Math matrices:** the safe set should be with visible characters … I am not sure whether `matrix` and `array` is desired by everyone (since they simply vanish).

Yes, I agree. Are these envs all from `amsmath`; i.e., should this be added to `amsmath.vim`?

----

> 2. **Math environments.** I am actually not sure myself. I have a vim-unimpaired style toggle `yoe` to quickly disable concealment. I think one can leave this until someone else is interested (or only by default off). I have it for now in the personal `after/ftplugin/tex.vim` file.

> 3. **Alignment character &** Again, I agree this can be confusing. This can be done in a personal configuration as well.

I think I'll leave these unless someone else should enter the discussion and express that they want them/one of them.

The alignment character is understandable with your screenshots. I can see how concealing them in `align` environments and similar makes sense. However, I would find it confusing if they were concealed in a tabular environment or similar. Thus, it seems safer to let you add this as a personal adjustment and to err on the cautious side here.

----

> 4. **I also have refined the concealment of \langle**
>        > Perhaps one could do symmetrical it like this?
>        I like this and yes doing it for all similar delimiters would also be the proper way.

Sounds good. I'll get on it when I have the time.

----

> 5. `\{` `\}` thanks for adding them

My pleasure!

> Here two screenshots of …

Thanks! It is nice to see an example of how this looks!

**Comment by lervag** [comment]
I've updated the delimiter conceals (ref. the `\langle`); please update and let me know if I missed something. It looks good to me on the limited testing I did.

**Comment by kiryph** [comment]
> I've updated the delimiter conceals (ref. the \langle); please update and let me know if I missed something. It looks good to me on the limited testing I did.

Thanks. Right now, I do not have a document myself with all types. But at least for \langle it works as expected. I will let you know if I encounter issues.

I have created now separate issues for the remaining concealment questions on my side and close this.

**Comment by lervag** [comment]
Great, and thanks; I'll look into the issues one at a time as soon as I have the time.
