### ISSUE TITLE
Key not present in Dictionary: get_file(‘fls’) when no LaTeX installation

### ISSUE THREAD

**Issue by bwhelm** [lervag/vimtex#2646]
### Description

On a device that does not have a LaTeX installation (like iVim on iPadOS), the following error arises with `set ft=tex` in a blank document:

> Error detected while processing function vimtex#init[7]..<SNR>82_init_state[1]..vimtex#state#init[9]..vimtex#state#class#new[40]..41:
> line    5:
> E716: Key not present in Dictionary: get_file('fls'))
> E116: Invalid arguments for function vimtex#parser#fls(self.compiler.get_file('fls'))

This error was introduced in commit 6e79c4fa42ef0eb5216220afe835be8fe9d2369d

### Steps to reproduce

1. Launch vim with empty document on system without LaTeX installation
2. :set ft=tex

### Do you use a latexmkrc file?

No

### VimtexInfo

The command `:VimtexInfo` is not defined (because of the error). When I revert to an earlier version of vimtex, launch vim, enter `:se ft=tex` and run `:VimtexInfo`, I get an error in iVim on iPadOS. (I’ll report that bug in a separate issue.)

**Comment by lervag** [comment]
Thanks! I've pushed an update that I believe fixes this; please test!

**Comment by bwhelm** [comment]
Yes, that fixes it. Thanks!

**Comment by lervag** [comment]
Glad to hear it!
