### ISSUE TITLE
Conceal \texorpdfstring{tex string}{string for pdf toc} as tex string

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2648]
When using math in chapters, subsection headers, they usually throw a pdf error. A solution is to output a dedicated string for the pdf toc by using `\texorpdfstring` from the package hyperref.

See for details http://mirrors.ctan.org/macros/latex/contrib/hyperref/doc/hyperref-doc.html#x1-250006.1.2

In a LaTeX file this can be concealed and only revealed when edited.

Conceal
```tex
 \texorpdfstring{tex string}{string for pdf toc} 
```
as
```
tex string
```

**Comment by lervag** [comment]
I've added an initial attempt at this, please test and give some feedback. I would also appreciate feedback to the variant when you disable conceals (e.g. with `let g:vimtex_syntax_conceal_disable = 1`).

**Comment by kiryph** [comment]
> I've added an initial attempt at this, please test and give some feedback. 

Thanks. My headings are now shown as expected. A simple example
```tex
\paragraph{\texorpdfstring{Modulus of the position vector $\vec{r}$}{Modulus of the position vector r}}
```
becomes with concealment
![Screenshot 2023-02-27 at 07 28 46](https://user-images.githubusercontent.com/371756/221490700-b911b23f-319b-4285-9de4-df880efbb302.png)
and when the cursor is on the line
![Screenshot 2023-02-27 at 07 29 17](https://user-images.githubusercontent.com/371756/221490796-f18195c4-b440-470a-a43d-3c139267e8f3.png)

> I would also appreciate feedback to the variant when you disable conceals (e.g. with `let g:vimtex_syntax_conceal_disable = 1`)

Actually, I have observed an issue. I have defined (using neovim)
```lua
vim.g.vimtex_syntax_custom_cmds = {
  {name= 'vec', mathmode= true, argstyle= 'bold', opt=false, conceal=true},
}
```
This conceals `\vec{r}` as `r`.

However, when I set `let g:vimtex_syntax_conceal_disable = 1`, it is still concealed. 
Only when I disable concealment in neovim/vim with `:set conceallevel=0`, it is not concealed anymore.

**Comment by lervag** [comment]
> > I've added an initial attempt at this, please test and give some feedback.
> 
> Thanks. My headings are now shown as expected.

Great. In my own testing, I noticed that the conceals are sometimes severely affected by the "bugs" related to softwrapping. This is particularely visible i you look at conceals spread across multiple lines. But I'm not sure what to do about that; if anything.

> > I would also appreciate feedback to the variant when you disable conceals (e.g. with `let g:vimtex_syntax_conceal_disable = 1`)
> 
> Actually, I have observed an issue. I have defined (using neovim)
> 
> ```lua
> vim.g.vimtex_syntax_custom_cmds = {
>   {name= 'vec', mathmode= true, argstyle= 'bold', opt=false, conceal=true},
> }
> ```
> 
> This conceals `\vec{r}` as `r`.
> 
> However, when I set `let g:vimtex_syntax_conceal_disable = 1`, it is still concealed. Only when I disable concealment in neovim/vim with `:set conceallevel=0`, it is not concealed anymore.

Ah, yes. This is clearly a rare edge case, since why would you add custom conceal commands if you disable conceals? Perhaps you even _wanted_ that? E.g., say you _don't_ want the general conceal stuff, but you _do_ want some minor, custom conceals?

But just to be clear, I was looking for feedback on the `\texorpdfstring` implementation without conceals. I assume no feedback is good feedback, though :)

**Comment by kiryph** [comment]
> Great. In my own testing, I noticed that the conceals are sometimes severely affected by the "bugs" related to softwrapping. This is particularely visible i you look at conceals spread across multiple lines.

That is true.

I am now not sure how I want to format my code now. In general I prefer hard wrapping over soft wrapping. But concealed latex can be much shorter where the hard wrapped lines can look unnecessary short.

I had also not yet enabled concealment for sections. When I do this, I see following issue:

```tex
\subsection{\texorpdfstring{Derivative with metric entries $g_{nm}(t)$}
{Derivative with metric entries}}
```
Concealed as
![Screenshot 2023-03-02 at 08 02 44](https://user-images.githubusercontent.com/371756/222355190-d9564e6f-e7b2-41a2-901a-069ff766ad4a.png)
Expectation
![Screenshot 2023-03-02 at 08 03 11](https://user-images.githubusercontent.com/371756/222355215-27c4b5f6-9e47-4e55-97d5-5e6ffec8767b.png)


---

> This is clearly a rare edge case, since why would you add custom conceal commands if you disable conceals?

 I actually do not understand why `g:vimtex_syntax_conceal_disable` exists. Concealment can be enabled by filetype with set conceallevel anyway.
I can only imagine when using nested syntax, e.g. latex in markdown. One could disable concealment for latex in markdown but want concealment for markdown.

**Comment by lervag** [comment]
> I had also not yet enabled concealment for sections. When I do this, I see following issue: …

Strange. On my end, the same code looks like this:

![image](https://user-images.githubusercontent.com/998898/222562728-241a50f6-52fd-48fb-ac25-edbabec6e422.png)

> I actually do not understand why `g:vimtex_syntax_conceal_disable` exists.

Simple: If we don't want conceals enabled, then we actually want the syntax rules to behave slightly different. For example, when we conceal `\mathcal{L}` we do it by matching _all of it_ as a specific target group that is concealed. When we _don't_ use conceal, then we instead want to match the various parts differently.

> Concealment can be enabled by filetype with set conceallevel anyway. I can only imagine when using nested syntax, e.g. latex in markdown. One could disable concealment for latex in markdown but want concealment for markdown.

Yes. And of course, you can just keep conceals enabled at all times and disable with `set conceallevel` - it should mostly work just find. But the quality of syntax highlighting will be slightly reduced compared to using `g:vimtex_syntax_conceal_disable`.

**Comment by kiryph** [comment]
> Strange. On my end, the same code looks like this:

Can you check it with
```lua
-- ~/.config/nvim/after/ftplugin/tex.lua
vim.opt.conceallevel = 2
vim.g.vimtex_syntax_conceal = {
  sections= 1,
}
```

> But the quality of syntax highlighting will be slightly reduced compared to using g:vimtex_syntax_conceal_disable.

I did not know this. To be honest, this should be added the documentation.
If I get it right, even for people who do not use concealment, one should ideally set for tex files
```lua
vim.opt.conceallevel = 2 -- enable concealment
vim.g.vimtex_syntax_conceal_disable = 1 -- but do not actually perform it, but get more granular syntax highlighting
```

I am actually still not sure how the syntax is better. If you happen to have a specific example, I would be glad to see it.

From my point of view the performance of the syntax highlighting can be improved by reducing the matching rules when concealment is not used (e.g. see my issue about fontawesome5 https://github.com/lervag/vimtex/issues/2580).

**Comment by kiryph** [comment]
> Strange. On my end, the same code looks like this:

But with

```lua
vim.g.vimtex_syntax_conceal = {
  sections= 0,
}
```

it looks good.

**Comment by lervag** [comment]
Ah, thanks. I think I fixed that now. Please update and test :)
