### ISSUE TITLE
Conceal wide characters, e.g. \mathcal{L} with an additional space

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2651]
```tex
$\mathcal{L}(i,j;n_k)$
```
is concealed as
![Screenshot 2023-03-01 at 07 56 54](https://user-images.githubusercontent.com/371756/222066404-baa4d4ae-c1e5-404b-9003-dbf5c3d80e5a.png)

The calligraphic L and the open parenthesis overlap. Is there a possibility to add a space to improve readability for the wide characters? Afaik, `cchar` is only a single character.

**Comment by lervag** [comment]
> Is there a possibility to add a space to improve readability for the wide characters? Afaik, `cchar` is only a single character.

Well, yes, I think. But it is a hack. We can do things like this:

```vim
  syntax match Tmp "\\mothcal{L}" transparent contains=TmpCmd
  syntax match TmpCmd "\\mothcal" contained nextgroup=TmpArg conceal cchar=𝓛
  syntax match TmpArg "{L}" contained conceal cchar= 
```

Which ends up looking like this on my end:

![image](https://user-images.githubusercontent.com/998898/222261364-b7365a5a-0b7a-4b57-9a28-576a392fd211.png)

I guess I have a different font in which the calligraphic L is not as wide. But it would be interesting to see how this looks on your end. Simply add the above code to you `after/syntax/tex.vim` to test.

For reference, the relevant code that may need an update if we make changes here:

https://github.com/lervag/vimtex/blob/640ffa4879d7c15fa6c5b8b458669f244ceff81c/autoload/vimtex/syntax/core.vim#L1412-L1414

**Comment by lervag** [comment]
For other unicode symbols that are wide on my end I do see that adding the extra space gives a nicer experience:

![image](https://user-images.githubusercontent.com/998898/222262396-f398f8d9-cde7-4313-b54d-f4096a2d6876.png)

Still, it may be annoying if we add extra space that is not needed for everyone...?

**Comment by kiryph** [comment]
```viml
syntax match texMathCmd "\\mothcal{L}" transparent contains=TmpCmd contained
syntax match TmpCmd "\\mothcal" contained nextgroup=TmpArg conceal cchar=𝓛
syntax match TmpArg "{L}" contained conceal cchar= 
" in the previous line there is a line ending space
```
looks like

![Screenshot 2023-03-02 at 09 56 20](https://user-images.githubusercontent.com/371756/222380021-3677fb53-cf48-4ed4-9c28-0bccc922b0c5.png)

with patched font Meslo Mono from https://www.nerdfonts.com/

> Still, it may be annoying if we add extra space that is not needed for everyone...?

I agree. This feature is actually font-dependent. Very difficult to maintain and probably should be delegated to the user.

**Comment by lervag** [comment]
Yes, that looks better! Seems like a nice looking font!

> > Still, it may be annoying if we add extra space that is not needed for everyone...?

> I agree. This feature is actually font-dependent. Very difficult to maintain and probably should be delegated to the user.

One possibility would be to add an option for this. But then I'm not sure, because I would assume even for your font Meslo Mono, there are several of similar type of symbols/characters that only require single width. These would then look bad.

So, it sort of seems like we need _n_ options, one for each symbol, and that's clearly not viable.

Would you be ok with instead fixing things like this on your end with personal customization?

**Comment by kiryph** [comment]
> Would you be ok with instead fixing things like this on your end with personal customization?

Yes this is fine. I am thankful for your help that I know now how to do this.

Do you think adding a note about this to the VimTeX documentation about concealment would make sense?

**Comment by lervag** [comment]
I'm not sure. The docs are already very long, and the chance of someone noticing it and actually finding it useful would be quite small..? I would put this kind of thing in the "very advanced personal customization" box. :)
