### ISSUE TITLE
Conceal non-line breaking space ~ (tie character) with a regular space

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2654]
The tilde character `~` or in this context called tie character (https://latexref.xyz/_007e.html ) can be concealed with a regular space.

> before~after
> The _tie_ character, `~`, produces a space between before and after at which the line will not be broken. By default the white space has length 3.33333pt plus 1.66666pt minus 1.11111pt (see Lengths).
> 
> Note that the word ‘tie’ has this meaning in the TeX/Texinfo community; this differs from the typographic term “tie”, which is a diacritic in the shape of an arc, called a “tie-after” accent in The TeXbook.
> 
> Here LaTeX will not break the line between the final two words:
> 
> Thanks to Prof.~Lerman.
> In addition, despite the period, LaTeX does not use the end-of-sentence spacing (see \@).
> 
> Ties prevent the end of line separation of things where that could cause confusion. They also still allow hyphenation (of either of the tied words), so they are generally preferable to putting consecutive words in an \mbox (see \mbox & \makebox).

**Comment by lervag** [comment]
Well, yes, this does sound like a no brainer. But it feels "too easy"...

Also, thanks for giving the very relevant reference! I appreciate that, it helps in understanding the core idea - I already know about `~`, but I never actually read this reference before!

**Comment by kiryph** [comment]
I noticed that
```tex
\documentclass{article}
\usepackage{natbib}

\begin{document}
(p.~181)
\citet[Sect.~3]{MyRef:2023}
\end{document}
```
is concealed as
![Screenshot 2023-03-04 at 07 58 18](https://user-images.githubusercontent.com/371756/222881056-dff0c511-e808-455d-ba2e-edb972b4f9bd.png)


I would have expected that the tilde is also hidden in the optional argument of `\citet`.

**Comment by lervag** [comment]
Done. :)
