### ISSUE TITLE
\left\lbrace concealment

### ISSUE THREAD

**Issue by Nnomis** [lervag/vimtex#2657]
### Description

When i write "**\left\lbrace**" in math mode, it's concealed as "**[**". 
But i would like to have instead "**{**".
I've read the part of the documentatin talking about that and tried to change this behaviour.
I managed to get "{" with "\lbrace" but don't know what to do with the whole "\left\lbrace".
Is that possible to override the default behaviour ? 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
None
```

**Comment by lervag** [comment]
Sorry, you're right - should be fixed now.
