### ISSUE TITLE
Concealment of \citet and \citep from natbib

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#2658]
I am wondering whether the concealment of `\citet` and `\citep` from natbib can be improved.

Here a screenshot from the documentation of natbib

![Screenshot 2023-03-04 at 07 53 46](https://user-images.githubusercontent.com/371756/222880952-336e59a3-a6f9-474d-8690-558f0be7aa8d.png)

The corresponding code is
```tex
\documentclass{article}
\usepackage{natbib}

\begin{document}
\citet{jon90}
\citet[chap.~2]{jon90}
\citep{jon90}
\citep[chap.~2]{jon90}
\citep[see][]{jon90}
\citep[see][chap.~2]{jon90}
\citet*{jon90}
\citep*{jon90}
\end{document}
```
Currently concealed as following

![Screenshot 2023-03-04 at 08 11 21](https://user-images.githubusercontent.com/371756/222881598-b9a81a83-cebd-4c2d-a89c-9137b04a48c9.png)

The most obvious change could be:
- [x] show `\citep*?{jon90}` with parentheses instead of square brackets (third and last line).

Prepend optional parameters and replace  inner brackets with spaces
- [ ] Conceal `\citet[chap.~2]{jon90}` as `[chap. 2 jon90]`
- [ ] Conceal `\citep[see][]{jon90}` as `(see jon90)`
- [ ] `\citep[see][chap.~2]{jon90}`. Here the chapter reference becomes completely invisible. I would at least show it. Showing it with less square brackets, e.g. as `(see chap. 2 jon90)`.
- [ ] for `\citet` one could drop the surrounding square brackets. Here I am not so sure.

I am not totally sold on all my suggestions and what is possible to mimic natbib functionality

**Comment by lervag** [comment]
The first one seems simple and I've fixed it already. The other ones will require some more thought.

> * Conceal `\citet[chap.~2]{jon90}` as `[chap. 2 jon90]`

> * Conceal `\citep[see][]{jon90}` as `(see jon90)`

These are quite hard. We are parsing from left to right, and we are parsing group by group. Currently, I'm relying on `nextgroup=` and I'm allowing two optional groups:

https://github.com/lervag/vimtex/blob/6f7e507ed1c397838798e43a8249612864c929ba/autoload/vimtex/syntax/core.vim#L2144-L2155

That is a simple but effective implementation.

To enable what you are asking, we would instead need to somehow match the entire optional groups in one go. It may be possible, but I don't quite see how to do it. Perhaps we can use the pattern offsets here (`:help syn-pattern-offset`) with `end="{"me-1` or something similar. Then we could conceal any `]\_s*[` by a single space character. I would need to experiment a bit with this.

> * `\citep[see][chap.~2]{jon90}`. Here the chapter reference becomes completely invisible. I would at least show it. Showing it with less square brackets, e.g. as `(see chap. 2 jon90)`.

Yes, I agree. I'll find a way to only hide the second option if it is empty.

> * for `\citet` one could drop the surrounding square brackets. Here I am not so sure.

I think having the square brackets makes it easier to recognize that this is a concealed `\citet` command, and as such, is useful.

**Comment by kiryph** [comment]
> It may be possible, but I don't quite see how to do it.

Do not invest too much time in this issue. If there is no obvious way, keep the current way. It works.

> Yes, I agree. I'll find a way to only hide the second option if it is empty.

That would be great and would resolve, from my point of view, the most urgent part of this issue.

> I think having the square brackets makes it easier to recognize that this is a concealed \citet command, and as such, is useful.

Agreed. Leave it as it is.
