### ISSUE TITLE
Clean synctex file

### ISSUE THREAD

**Issue by Eisfreak7** [lervag/vimtex#266]
After running ```:VimtexClean```, there remain 3 files in my folder: the tex file, the pdf file (both intendet) and the synctex.gz file (not intended I guess?)
It would be great, if the synctex file could also be cleaned.

**Comment by lervag** [comment]
This can be fixed by updating your `.latexmkrc` file. My `.latexmkrc` file has these lines:

```perl
push @generated_exts, "cb";
push @generated_exts, "cb2";
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "brf";
push @generated_exts, "nlg";
push @generated_exts, "nlo";
push @generated_exts, "nls";
push @generated_exts, "synctex.gz";
push @generated_exts, "tex.latexmain";
push @generated_exts, "run.xml";
```

**Comment by Eisfreak7** [comment]
Thanks, that solved it

**Comment by lervag** [comment]
No problem :-)

tir. 3. nov. 2015, 17.52 skrev Eisfreak7 <notifications@github.com>:

**Comment by krisfans** [comment]
> 
> 
> After running `:VimtexClean`, there remain 3 files in my folder: the tex file, the pdf file (both intendet) and the synctex.gz file (not intended I guess?)
> It would be great, if the synctex file could also be cleaned.

So how do you solve this problem ? Just using .latexmkrc file?

**Comment by lervag** [comment]
> So how do you solve this problem ? Just using .latexmkrc file?

Yes.
