### ISSUE TITLE
Tabout

### ISSUE THREAD

**Issue by Fireond** [lervag/vimtex#2660]
I found a pugin [tabout](https://github.com/abecodes/tabout.nvim) which can jump out from parentheses, quotes etc., which is quite useful. However, it need treesitter as dependency, hence for latex filetype I cannot use this tool. But for writing LaTex, since there are quite a lot `{}`, and it would be nice to navigate use tab. So I wonder if it is possible to support this feature, or can you give me some advise about how to realize this feature (just as simply as jump out `()`, `[]`, `{}`, if possible, math environment like `\(\)`, `\[\]` etc.) Thanks!

**Comment by lervag** [comment]
> So I wonder if it is possible to support this feature,

Sorry, no, I will not implement this into VimTeX. It is too general a feature that will require a lot of work, and I don't have the time.

> or can you give me some advise about how to realize this feature (just as simply as jump out `()`, `[]`, `{}`, if possible, math environment like `\(\)`, `\[\]` etc.) Thanks!

I believe you may have something close with [vim-matchup](https://github.com/andymass/vim-matchup). It has motions like `]%` that moves to a closing brace. Thus, you could make a mapping that mostly mimics tabout, something like this:

```vim
map <tab> ]%l
```

**Comment by lervag** [comment]
https://github.com/andymass/vim-matchup#a2-jump-to-open-and-close-words

**Comment by Fireond** [comment]
Thanks!

**Comment by lervag** [comment]
No problem. Feel free to ask follow up questions if you should have any.
