### ISSUE TITLE
Conceal Support for 2-Command Arguments

### ISSUE THREAD

**Issue by EmperorEntropy** [lervag/vimtex#2666]
**Is your feature request related to a problem? Please describe it.**
My feature request is related to an interesting [article](https://www.unicode.org/notes/tn28/UTN28-PlainTextMath-v3.1.pdf) I read on Unicode Plain Tex Encoding for math. One of the unicode "simplifications" intrigued me, and it was how `\binom{n}{k}` was simplified into `(n¦k)`. I would like to have a similar functionality with Vimtex's conceal system.

**Describe the solution you'd like**
To be precise, I would like conceal support for 2-command arguments, which are arguments that look like `\cmd{}{}`. Perhaps a command like `g:vimtex_syntax_custom_cmds_with_two_args` would work? For the example I want, it could look like the following
```vim
let g:vimtex_syntax_custom_cmds_with_two_args = [
          \ {'name': 'binom',
          \  'mathmode': 1,
          \  'cchar_open': '(',
          \ 'cchar_mid': '¦',
          \  'cchar_close': ')'},
          \]
```
where `cchar_open` is inserted before the first argument, `cchar_mid` is the char inserted between the two arguments, and `cchar_close` is inserted after the second argument. So, something like `\binom{4}{2}` would appear as `(4¦2)`.

Ideally, `cchar_open` and `cchar_close` would be optional, allowing for cases where we don't need them as part of the concealment. A basic example would be fractions, and possible customization for it might look like:
```vim
let g:vimtex_syntax_custom_cmds_with_two_args = [
          \ {'name': 'frac',
          \  'mathmode': 1,
          \ 'cchar_mid': '/'},
          \]
```
In this case, `\frac{2}{3}` could become `2/3` under concealment.

This seems rather complex to implement, but hopefully something like this would be possible to have. It would make concealment be a lot more useful. Thank you for considering this suggestion!

**Comment by lervag** [comment]
Sorry for the slow response here. First, let's consider how we could write such a rule. This fits very nicely into the "very hacky" type solutions. :)

I came up with this (still in draft mode). It seems to work:

```vim
syntax match texMathCmdCBinom "\v\\binom>"
      \ skipwhite nextgroup=tex1
      \ conceal cchar=(
syntax cluster texClusterMath add=texMathCmdCBinom
syntax region tex1
      \ matchgroup=tex1CD
      \ concealends cchar=|
      \ start="{" skip="\\\\\|\\}" end="}"
      \ skipwhite nextgroup=tex2
      \ contained contains=@texClusterMath
syntax region tex2
      \ matchgroup=tex1CD
      \ concealends cchar=)
      \ start="{" skip="\\\\\|\\}" end="}"
      \ contained contains=@texClusterMath
```

I'm thinking though that perhaps it is better _not_ to make an option for this. Instead, perhaps we can add a VimTeX api function that anyone could use in their `after/syntax/tex.vim` with a proper specification? That might be a better solution for the current `g:vimtex_syntax_custom_cmds_with_concealed_delims` as well. Not sure, though...

**Comment by lervag** [comment]
I'm pushing a function that should work, please test it. You 1) update vimtex, then 2) add the following to your `after/syntax/tex.vim` (or similar):

```vim

  call vimtex#syntax#core#new_cmd_with_concealed_delims_2args({
        \ 'name': 'binom',
        \ 'mathmode': 1,
        \ 'cchar_open': ')',
        \ 'cchar_mid': '|',
        \ 'cchar_close': '(',
        \})
```

**Comment by lervag** [comment]
Scratch that. I updated the existing function instead. See `:help vimtex_syntax_custom_cmds_with_concealed_delims` and let me know if it does not work as expected.
