### ISSUE TITLE
Hardwrap 

### ISSUE THREAD

**Issue by hcf-n** [lervag/vimtex#2667]
I use vimtex with formatoptions=tcqwa1 and tw=72. I guess the expected behavior is that Vim will wrap text at whitespace. This works fine. However, in Latex there are sometimes quite long phrases without whitespace, i.e. \footnote{\url.......} or \footcite[111]{SomeBibtexReference}. This gives a very ragged look when they are top long and vim have to wrap.  

Is there a way to configure vim or vimtex to break at some other characters than whitespace when hardwrapping? (Softwrap has a long list of with breakat-characters, I'm looking for something similar when hard-wrapping).

hcf

**Comment by lervag** [comment]
> Is there a way to configure vim or vimtex to break at some other characters than whitespace when hardwrapping? (Softwrap has a long list of with breakat-characters, I'm looking for something similar when hard-wrapping).

No, sorry, not that I'm aware of.

There's a short write up on formatting in the VimTeX docs that may be of interest to you, see `:help vimtex-af-formatting`.
