### ISSUE TITLE
Make mupdf viewer option auto-update

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2676]
**Is your feature request related to a problem? Please describe it.**
Currently if mupdf is used as a viewer, it will not automatically refresh when the PDF file change.

**Describe the solution you'd like**
Implement it. It can be done by sending HUP signal to the mupdf process https://unix.stackexchange.com/questions/425907/how-to-make-mupdf-automatically-refresh-a-document

At least just spawning `kill -HUP <pid>` work in UNIX environments, not sure about Windows.

----

Edit: we can use `job_stop()` in vim to signal SIGHUP, but still not sure if it works on Windows.

**Comment by lervag** [comment]
Notice that this should work currently if you have `xdotool`:

https://github.com/lervag/vimtex/blob/a4d5e2fdfd6bf2275a1d765a998d5a04d2ad4d1b/autoload/vimtex/view/mupdf.vim#L29

You are asking for an adjustment where we instead signal mupdf directly. It seems much less of a hack, and so I think it could be interesting to consider it.

To implement, we would need:

1. Use `vimtex#jobs#start` to start the viewer, as that will use the modern `jobstart` or `job_start` apis and gives access to PIDs and possibly signalling.
2. Either signal with `kill -HUP PID` or perhaps by use of built-in `job_stop` (there does not seem to be a corresponding version on neovim).

**Comment by user202729** [comment]
Ah, for some reason it didn't work earlier (even though I have xdotool). I changed view method back to mupdf and it works now..

**Comment by lervag** [comment]
I've made the changes now, and it seems to work well. Please test - does it work for you?

**Comment by user202729** [comment]
That's fast. Yes, it works.

**Comment by lervag** [comment]
Great, glad to hear it. And thanks for the idea, I think this should be a general improvement overall for the mupdf layer.
