### ISSUE TITLE
vimtex_view_general_viewer required??

### ISSUE THREAD

**Issue by midpl0x** [lervag/vimtex#2680]
### Description

I'm trying to use WSL to write LaTeX with Vim, following Gilles Castel's (RIP) guides. And everything is working perfectly, however! I also wish to use window snapping which apparently is NOT a feature with WSL. So I want my PDF to launch using SumatraPDF from my C-drive, which is working perfectly as well. However, in my .vimrc, I have to use the option "`let g:vimtex_view_general_viewer = 'SumatraPDF'`. I simply cannot make it work with the non-deprecated option, "`let g:vimtex_view_method = 'SumatraPDF'`". If I attempt that, I'm just greeted with a "invalid viewer" on launch, even though I have confirmed it working with the "old" option. 

Am I doing something wrong? 

### Expected behavior

Expecting launch of SumatraPDF as confirmed working with `let g:vimtex_view_general_viewer`. 

### Actual behavior

Nothing happens. Error message upon opening file with Vim. 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  2   OS: Ubuntu 22.04.2 LTS
  3   Vim version: VIM 8.2 (1-3995, 4563, 4646, 4774, 4895, 4899, 49  4   Has clientserver: false
  5
  6 VimTeX project: test
  7   base: test.tex
  8   root: /home/casper
  9   tex: /home/casper/test.tex
 10   main parser: current file verified
 11   document class: article
 12   packages: amsbsy amsfonts amsgen amsmath amsopn amssymb amstex 13   compiler: latexmk
 14     engine: -pdf
 15     options:
 16       -verbose
 17       -file-line-error
 18       -synctex=1
 19       -interaction=nonstopmode
 20     callback: 1
 21     continuous: 1
 22     executable: latexmk
 23   viewer: General
 24   qf method: LaTeX logfile
~
```

**Comment by lervag** [comment]
> I'm trying to use WSL to write LaTeX with Vim, following Gilles Castel's (RIP) guides.

RIP? I was not aware, and I don't find any information about this online. But this saddens me, he striked me as a very skilled guy who could possibly accomplish a lot of cool stuff! He was also skilled at writing about his ideas and workflows and I believe he already made a large impact on the Vim and LaTeX community with his posts. :(

> I simply cannot make it work with the non-deprecated option, "`let g:vimtex_view_method = 'SumatraPDF'`".

That's not a valid choice. See `:help vimtex_view_method`:

```
*g:vimtex_view_method*
  Set the viewer method. By default, a generic viewer is used through the
  general view method (e.g. `xdg-open` on Linux).

  Possible values:
    * `'general'`
    * `'mupdf'`             |vimtex-view-mupdf|
    * `'skim'`              |vimtex-view-skim|
    * `'zathura'`           |vimtex-view-zathura|
    * `'zathura_simple'`    |vimtex-view-zathura-simple|
```

Notice the "possible values" list.

> Am I doing something wrong?

Yes, see above. Also, please read `:help vimtex-view-sumatrapdf`, which explains how to set things up.

**Comment by lervag** [comment]
Also, notice from `:VimtexInfo` that you don't have the clientserver enabled. Please see `:help vimtex-clientserver` for more info on that.

**Comment by lervag** [comment]
> I'm learning a lot about linux these days.

It's fun, right? :)

> SumatraPDF was ok. I decided I'd try Sioyek, and I'm really liking it this far. I've made it work with it as well, so yeah.

Yes, I've also started to use Sioyek and I find it is very good!

> And apparently so. It seems he passed in June last year. [https://www.kuleuven.be/wieiswie/en/person/00131443](url)

Well, that was bad news. I'm sorry to hear it! :(

As I guess most of the community, I was very impressed by his blog posts and his very streamlined workflow for taking notes!
