### ISSUE TITLE
Tool for gifs

### ISSUE THREAD

**Issue by mkschreder** [lervag/vimtex#2685]
What tool do you use to produce visual gifs found on https://github.com/lervag/vimtex/blob/master/VISUALS.md?

**Comment by lervag** [comment]
I'll let @ejmastnak answer this one :)

**Comment by lervag** [comment]
Perhaps it would be a good idea to add a short paragraph about this in that document?

**Comment by ejmastnak** [comment]
Hi @mkschreder!

The basic infrastructure is [Menyoki](https://github.com/orhun/menyoki) for recording the GIFs and [screenkey](https://gitlab.com/screenkey/screenkey) to display the keys being typed.

On top of this are some aesthetic details to make the GIFs look nicer, including:

- [Goyo](https://github.com/junegunn/goyo.vim) to remove Vim peripherals (status bar, line numbers, etc.) for a cleaner look
- [Limelight](https://github.com/junegunn/limelight.vim) to draw focus to the currently selected paragraph (and gray out the rest of the document)
- Screen recording region (crop, basically) set via Menyoki to exactly capture the terminal window (and not e.g. the rest of my desktop)
- Enlarged terminal font for the duration of the GIF recording for better readability
- Vim and screenkey color schemes and fonts aligned for visual consistency.

The aesthetic details and crops are wrapped in shell scripts for repeatability across multiple GIF recordings.

Feel free to email me (email in profile) if you're interested in the details or recording similar GIFs.

**Comment by ejmastnak** [comment]
> Perhaps it would be a good idea to add a short paragraph about this in that document?

Good idea! Shall I add the gist of the above comment as a PR to VISUALS.md?

**Comment by lervag** [comment]
Yes, thanks, I would appreciate that!

**Comment by lervag** [comment]
Closing this, as I believe the original question was very well answered now by @ejmastnak.

**Comment by ejmastnak** [comment]
> Yes, thanks, I would appreciate that!

Done!

**Comment by mkschreder** [comment]
@ejmastnak supercool. Thanks for your detailed explanation.

**Comment by ejmastnak** [comment]
> @ejmastnak supercool. Thanks for your detailed explanation.

No problem, I appreciate the interest ;)
