### ISSUE TITLE
Setting `keys` with lazy.nvim causes vimtex to not load

### ISSUE THREAD

**Issue by albertfgu** [lervag/vimtex#2699]
### Description

Following on https://github.com/lervag/vimtex/issues/2698, I tried moving my entire config to be managed by `lazy.nvim`. Setting the global variables works great. However when I tried to move my keymap definitions into the `keys` table of lazy's configuration, vimtex no longer loads. In fact, specifying the `keys` key at all seems to cause this issue:
```
  {
    "lervag/vimtex",
    -- Lervag recommends putting configuration here: https://github.com/lervag/vimtex/issues/2698
    keys = {},
    init = function()
      -- set global variables
    end,
  }
```
Is the issue that perhaps lazy.nvim is doing something weird with lazy loading the keymaps? I'm guessing this would work fine if I just moved the keymaps into the `init` with `vim.keymap.set()`. Essentially it seems that the right way to set this up is to move everything that I had in my `ftplugin/tex.vim` and move it into the `init` function - is that right?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
N/A (can update with the info if it's relevant)
```

**Comment by lervag** [comment]
> However when I tried to move my keymap definitions into the `keys` table of lazy's configuration, vimtex no longer loads.

Ah, because you misunderstand what this option of lazy.nvim does. It specifies to lazily load VimTeX and only load it when the specified keys are typed!

**Comment by lervag** [comment]
https://github.com/folke/lazy.nvim/blob/main/doc/lazy.nvim.txt#L192

**Comment by albertfgu** [comment]
You're right, thanks for the clarification 😅 Is setting everything via `vim.keymap.set` inside the `init` function the correct way then?

**Comment by lervag** [comment]
If you want to remap things, then I would suggest you make an `ftplugin/tex.vim` or `.../tex.lua` file in your config where you put your `map`s or `vim.keymap.set`s. VimTeX will not override user mappings, and if you create a mapping for one of the `<plug>(vimtex-...)` mappings, then VimTeX will not create the default map.

**Comment by lervag** [comment]
You can also put it in your `init` function, but then you should put it inside an autocmd for `FileType tex`.

**Comment by albertfgu** [comment]
Makes sense!

> VimTeX will not override user mappings, and if you create a mapping for one of the <plug>(vimtex-...) mappings, then VimTeX will not create the default map.

This sentence confused me slightly though - does this assume that the user mapping is created before Vimtex is initialized? Wouldn't this go back to the issue of putting user stuff inside `ftplugin/` because we're not sure what order it's called (https://github.com/lervag/vimtex/issues/2698#issuecomment-1533487841)?

**Comment by lervag** [comment]
> > VimTeX will not override user mappings, and if you create a mapping for one of the (vimtex-...) mappings, then VimTeX will not create the default map.
> 
> This sentence confused me slightly though - does this assume that the user mapping is created before Vimtex is initialized? Wouldn't this go back to the issue of putting user stuff inside `ftplugin/` because we're not sure what order it's called ([#2698 (comment)](https://github.com/lervag/vimtex/issues/2698#issuecomment-1533487841))?

Hah, good question. Ok, so: I may have been slightly too "strict" in my previous comment. In general, your personal `~/.config/nvim/ftplugin/` files should be sourced first and any external plugins should be sourced afterwards. Thus, adding your VimTeX configuration here _should_ work. However, I have noticed that this does not always work as expected for everyone, but I can't remember the details.

An important thing here is that there is a difference between mappings and options. If, for some reason, the load order is wrong, it becomes a larger problem with options. This is because some of the VimTeX options _need_ to be defined before loading VimTeX to have an effect. But if you were to apply mappings after VimTeX was loaded they would just override existing mappings and things should work as expected.

I hope this clarifies things somewhat!

**Comment by albertfgu** [comment]
This is very helpful as usual! I figured out the problem with putting global variables in the ftplugin: if you open (Neo)vim to a non-tex file and then `:e` a tex file, the configuration is wrong because Vimtex gets initialized on the first file.

I feel like ideally the plugin would also only be loaded on .tex files - it feels a bit strange to me to have lots of `g:vimtex_` variables defined everytime I use vim given that I primarily use it for non-latex editing (even though as you say, it is lightweight to define these variables and I'm fine with this being the working solution). But I don't understand enough about all the loading shenanigans - I know you've discussed this at length in documentation and discussions so I'll read those if I want to dig in more :)

**Comment by lervag** [comment]
> This is very helpful as usual!

<3

> I figured out the problem with putting global variables in the ftplugin: if you open (Neo)vim to a non-tex file and then `:e` a tex file, the configuration is wrong because Vimtex gets initialized on the first file.

What do you mean VimTeX gets initialized on the first file? VimTeX is not initialized until necessary (e.g. for tex files).

But apart from that, I believe you are on to something here.

> I feel like ideally the plugin would also only be loaded on .tex files - it feels a bit strange to me to have lots of `g:vimtex_` variables defined everytime I use vim given that I primarily use it for non-latex editing (even though as you say, it is lightweight to define these variables and I'm fine with this being the working solution).

I can understand that. But I don't quite see any good solutions here. Some options take affect when VimTeX is initialized. If a user wants to change these options from default values, they _must_ be changed them _before_ VimTeX is initialized. I do agree that some other options _could_ be defined later, but it is much easier as a maintainer to just require that options are defined up front.

And the cost _is_ negligible: on my end, running the `init` function which sets a bunch of options on startup costs 0.12 ms on a slow laptop.

**Comment by albertfgu** [comment]
> What do you mean VimTeX gets initialized on the first file? VimTeX is not initialized until necessary (e.g. for tex files).
But apart from that, I believe you are on to something here.

Hmm, I'm not sure then. I did check that this caused an issue when the global variables are put into `ftplugin/tex` though.
