### ISSUE TITLE
indent of displayed equation

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#270]
With `shiftwidth=2`, typing
```tex
\[
()
\]
```
where () is typed last, indents to 

```tex
\[
    ()
\]
```
Expected:
```tex
\[
  ()
\]
```
That is, only indented by one shiftwidth.

**Comment by lervag** [comment]
Thanks, I've found a bug that I think caused this.

**Comment by Konfekt** [comment]
Yep, it's fixed. Thanks!
