### ISSUE TITLE
Switch textwidth automatically in math environments

### ISSUE THREAD

**Issue by chenle02** [lervag/vimtex#2704]
I have textwidth=80 in a normal text but would like to have it be 1000 in math environments. I wrote a function and do that by a key binding. Would it be possible to make it automatical?

Thanks a lot!
Le

**Comment by lervag** [comment]
> I have textwidth=80 in a normal text but would like to have it be 1000 in math environments.

You probably want to set it to 0 in math (which means to disable hardwrapping).

Notice, though, that there are good reasons to consider changing your preference. See `:help vimtex-af-formatting` for more info.

> I wrote a function and do that by a key binding. Would it be possible to make it automatical?

Yes. Most things are possible :)

You would want to use an autocommand for this. There are several relevant events. Something like this may be useful as a starting point (put it in your `ftplugin/tex.vim` or similar):

```vim
autogroup vimrc_vimtex
  autocmd!
  autocmd CursorMoved  <buffer> call Function()
  autocmd CursorMovedI <buffer> call Function()
augroup END
```

See `:help autocmd` and `:help CursorMoved` for more info.

**Comment by chenle02** [comment]
Thank you so much for the prompt help~! I have checked `:help vimtex-af-formatting`, which is very thoughtful. I didn't realize this issue has been carefully considered by Vimtex. I am using hard formatting for 80 characters. It does mass up with my collaborators and with diff. I will try out the options from the help document and also the one your suggested. Thanks a lot~!

**Comment by lervag** [comment]
Glad you find it useful! Feel free to reopen (or just simply continue the discussion with follow up questions)!
