### ISSUE TITLE
Indent after tikz command

### ISSUE THREAD

**Issue by Eisfreak7** [lervag/vimtex#271]
This code
```
\documentclass{report}
\usepackage{tikz}

\begin{document}
\part{Something}
\tikz \fill [green] rectangle (0.5, 0.5); Something
\end{document}
```
Gets auto indented by ```gg=G``` to
```
\documentclass{report}
\usepackage{tikz}

\begin{document}
\part{Something}
\tikz \fill [green] rectangle (0.5, 0.5); Something
    \end{document}
```

Without the ```Something``` after the tikz command this doesn't happen.
I assume this isn't intendet?

**Comment by lervag** [comment]
Yes, I think you are right. I never use standalone `tikz` commands, I always put them in environments. I'll look into this when I get the time.

**Comment by Eisfreak7** [comment]
Thanks, I use them to create colored markers in front of my different therem styles.
It's not a big deal though, I just have to remember to start the auto-indenting at the \begin{document} instead of the top of the file.
Thanks for looking into it
