### ISSUE TITLE
Expand for lsp-zero

### ISSUE THREAD

**Issue by keiwanjamaly** [lervag/vimtex#2716]
I there, 

I'm using [lsp-zero](https://github.com/VonHeikemen/lsp-zero.nvim) and had quite a lot of troubles setting it up, but now I got it. 

lsp basically wraps the `cmp.setup()` function into `lsp.setup_nvim_cmp(...)`. My error was, that I have called `lsp.setup()` before that. So if you want, I can extend the documentation for `lsp-zero` and submit a pull request, it is just a slight modification, but I would have saved 2 hours of my life :)

https://github.com/lervag/vimtex/blob/a6df6c3bed5f3170ab7f5706c57162df1aa0d986/doc/vimtex.txt#L4367

**Comment by lervag** [comment]
Interesting. I'm curious why do you think we need to update the docs for VimTeX for lsp-zero? They are not really related..? Perhaps you could show me a quick draft of how you think we should update the docs? It may make it easier for me to determine if I agree with the idea.

**Comment by keiwanjamaly** [comment]
I'm thinking about something very simple, like:

```
If you are using `lsp-zero` replace `.setup(...)` with `.setup_nvim_cmp(...)` and remember to call `lsp.setup()` afterwards.
```

Maybe adding some imports for `lsp-zero` but nothing too fancy. 

I mean it would have helped me, but your average user might be more intelligent than me and does not need it (could be very likely I'm not that clever xD)

**Comment by lervag** [comment]
> I'm thinking about something very simple, like:
> 
> ```
> If you are using `lsp-zero` replace `.setup(...)` with `.setup_nvim_cmp(...)` and remember to call `lsp.setup()` afterwards.
> ```
> 
> Maybe adding some imports for `lsp-zero` but nothing too fancy.
> 
> I mean it would have helped me, but your average user might be more intelligent than me and does not need it (could be very likely I'm not that clever xD)

You are probably very intelligent :)

The reason I'm skeptical is that users of `lsp-zero` should take their time to
understand how it changes the requirements of dependencies. It sort of feels
wrong to add more text for this specific case.

However, I tried to write something. My current draft looks like this:

```vimhelp
nvim-cmp ~
                                                     *vimtex-complete-nvim-cmp*
|nvim-cmp| [0] is the successor of |nvim-compe|. It provides completion …

  SAME AS BEFORE
  SAME AS BEFORE

Note: If you are using |lsp-zero|, then the above needs to be adjusted to the
      configuration style required by |lsp-zero|. E.g., instead of the first
      snippet: >lua

        local lsp = require('lsp-zero')
        lsp.setup_nvim_cmp {
          sources = cmp.config.sources { { name = 'omni', }, }
        }
        lsp.setup()

[0]: https://github.com/hrsh7th/nvim-cmp
[1]: https://github.com/hrsh7th/cmp-omni
```

I'm not fully confident that I understood correctly and I worry that the suggested code is not really quite right. I've looked at [the docs of lsp-zero](https://github.com/VonHeikemen/lsp-zero.nvim/blob/v2.x/doc/md/configuration-templates.md) which instead suggests something like this:

```lua
local lsp = require('lsp-zero').preset({})

lsp.on_attach(function(client, bufnr)
  lsp.default_keymaps({buffer = bufnr})
end)

-- (Optional) Configure lua language server for neovim
require('lspconfig').lua_ls.setup(lsp.nvim_lua_ls())

lsp.setup()
```

**Comment by keiwanjamaly** [comment]
> In version 2 of lsp-zero people can just customize nvim-cmp after lsp-zero's setup function. There is a section in the readme about adding sources: [Adding extra sources](https://github.com/VonHeikemen/lsp-zero.nvim#adding-extra-sources).
> 
> ```lua
> local lsp = require('lsp-zero').preset({})
> 
> lsp.on_attach(function(client, bufnr)
>   lsp.default_keymaps({buffer = bufnr})
> end)
> 
> lsp.setup()
> 
> local cmp = require('cmp')
> cmp.setup({
>   sources = {
>     {name = 'nvim_lsp'},
>     {name = 'omni'},
>   }
> })
> ```
> 
> People don't need to do anything special. Just know that they can use the `cmp` module after lsp-zero.

Yea this works, sorry I copied my lsp-zero config frome somewhere and haven't read the new ls-zero docs. In that case It is my fault, sorry for the confusion.

@lervag from my side this issue is closed. 

@lervag @VonHeikemen I really appreciate the work you are doing, I would like to show it more financially, but this is difficult atm.

**Comment by lervag** [comment]
@VonHeikemen Thanks for the info!

@keiwanjamaly No problem, and thanks for the kind words! Be well :)
