### ISSUE TITLE
Text objects  'a$' ,'i$' do not recognize single '$' as inline math delimiters in neovim 0.9

### ISSUE THREAD

**Issue by tjavdar** [lervag/vimtex#2718]
In an up-to-date Archlinux, I have a working current vim-vimtex 2.12-1 installed  with yay from aur.

Opening a tex file (ft=tex)  in neovim  0.9.0-2, text objects 'i$' and 'a$' do not recognize single '$' as math delimiters
and commands 'di$', 'ca$', etc, do not work as a result. Still, this does not happen  in plain vim 9.01572-1.

Other surrounding math delimiters work as expected in both vim and neovim. Here's a minimal exmple:  

\documentclass{article}
\begin{document}

% Issuing 'di$','ci$','da$','ca$' in the environments below:

$ e=mc^2 $ % has NO effect in neovim, but work in vim

\\( e=mc^2 \\) % work as expected in BOTH vim and neovim

\\[
  e=mc^2 % work as expected in BOTH vim and neovim
\\]

\begin{equation}
  e=mc^2 % work as expected in BOTH vim and neovim
\end{equation}

\end{document}

**Comment by lervag** [comment]
> In an up-to-date Archlinux, I have a working current vim-vimtex 2.12-1 installed with yay from aur.

PLEASE don't install VimTeX from AUR/package manager!!!!! If I had a say, that package would never exist! You should install all vim plugins from your vim configuration with standard package managers like lazy.nvim, vim-plug, packer, or similar.

> Opening a tex file (ft=tex) in neovim 0.9.0-2, text objects 'i$' and 'a$' do not recognize single '$' as math delimiters and commands 'di$', 'ca$', etc, do not work as a result. Still, this does not happen in plain vim 9.01572-1.

This is most likely because you are using treesitter and did not read `:help vimtex-faq-treesitter`. You need to disable treesitter for LaTeX.

**Comment by tjavdar** [comment]
First off: Thanks for the sound advice!

Removing the AUR package and using Plug ' lervag/vimtex' resolved the issue.  I removed also my AUR/{vim-ultisnips,vim-airline} packages and installed them natively through Plug.

I suppose there might have been some subtle overlap/interference between UltiSnips and VimTeX in the AUR installs which caused trouble. (I do not use Treesitter).

Thanks again for your excellent package!

**Comment by lervag** [comment]
Glad to help! Thanks for the kind words!
