### ISSUE TITLE
math environment not recognized in \emph{ ... }

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#272]
If the cursor is on `a` in
```tex
\emph{$a$}
```
then `ci$` does nothing. Expected: Deletes `$a$` and enters insert mode.

Somehow `$a$` is no longer recognized as math environment.

**Comment by lervag** [comment]
Strange. This works as expected for me. I opened `$VIMTEX/test/test-minimal/main.tex`, added `\emph{$a=1$}`. With cursor on `=` I did `ci$`, and it worked as expected.

**Comment by Konfekt** [comment]
It is the same issue as https://github.com/lervag/vimtex/issues/245 

Works perfect for `\help{...}` instead. But even fails in the minimal example with `\emph{...}`.
 
If @Rmano could test ?

**Comment by Konfekt** [comment]
... and, as in https://github.com/lervag/vimtex/issues/245 with a minimal `.vimrc`

**Comment by Konfekt** [comment]
Perhaps it is about `syntax/tex.vim`. Here it is
```vim
" Last Change:	Jun 11, 2015
" Version:	87
```

**Comment by Rmano** [comment]
It fails for me also. Where can I find a minimal .vimrc example (local --- I had the plugin in ~/.vim/plugged/vimtex`)? (I had one but Iost it....)

**Comment by Konfekt** [comment]
Try
```vim
set nocompatible
filetype plugin indent on
syntax enable

call plug#begin('~/.vim/plugged')
  Plug 'https://github.com/lervag/vimtex'
call plug#end()
```

**Comment by Rmano** [comment]
@Konfekt thanks --- but wouldn't this one reload the whole plugin? I am sure there was one where you just pointed vim to the directory and nothing more...

**Comment by Konfekt** [comment]
Hmm.. perhaps you mean something like
```vim
set rtp+=~/.vim/bundle/vimtex
```
instead of 
```
call plug#begin('~/.vim/plugged')
  Plug 'https://github.com/lervag/vimtex'
call plug#end()
```
if you do not want to copy `vimtex` into the `.vim` dir?

**Comment by Konfekt** [comment]
See https://github.com/lervag/vimtex/issues/232#issuecomment-144701295

**Comment by lervag** [comment]
First, I have the same version of `syntax/tex.vim`. My vim version is 7.4.884, I'm on Arch Linux.

I use the following minimal vimrc file:

```vimL
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
filetype plugin indent on
syntax enable
```

And I use the following tex file:

```tex
\documentclass{minimal}
\begin{document}
\emph{$a+1$}
\end{document}
```

I still can't reproduce your problem.

**Comment by lervag** [comment]
I've now added the MWE and minivimrc that I'm testing with to the repo. I suspect the problem here might be different versions of Vim.

**Comment by Rmano** [comment]
Ok, tried the same (calling with `vim -u ./minivimrc minimal.tex` in the new directory --- thanks). If I put the cursor in your minimal file into the math, and press `ci$`, it beeps and nothing happens.

But the problem must be different --- `ci$` don't work also outside the `\emph` thing. 

```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
Included patches: 1-52
```

**Comment by Rmano** [comment]
With the new `minivimrc` (obviously after adapting it to my plugin directory --- sorry for the noise before) I can confirm that it works ok. So it must be something different. 

Conceal code maybe? It's the only difference I can see between `\emph` and `\blah` ...

My VIM: 
```
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2014 19:39:47)
Included patches: 1-52
```

**Comment by lervag** [comment]
Ok, so I tested Vim 7.4.52, and I still can't reproduce this issue.

**Comment by Konfekt** [comment]
Strangely, everything works with
```vim
set nocompatible
filetype plugin indent on
syntax enable

let &rtp = '~/.vim/plugged/vimtex,' . &rtp
```
but not with
```vim
set nocompatible
filetype plugin indent on
syntax enable

call plug#begin('~/.vim/plugged') 
Plug 'https://github.com/lervag/vimtex'
call plug#end()
```
Can you reproduce it with 
```vim
set nocompatible

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !mkdir -p ~/.vim/autoload
  silent !curl -fLo ~/.vim/autoload/plug.vim
        \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif

filetype plugin indent on
syntax enable

call plug#begin('~/.vim/plugged') 
Plug 'https://github.com/lervag/vimtex'
call plug#end()
```
?

**Comment by lervag** [comment]
Thanks for the update. I think we are getting close, and I think @Rmano might be right that this is regarding conceal. That is, it seems like things work as expected when I comment out the conceal code for `\emph` in `after/syntax/tex.vim`.

I'm pushing an updated minimal vimrc file that reproduces the issue.

**Comment by lervag** [comment]
I can now reproduce with my regular `vimrc` file: I removed `let g:tex_conceal = ''`. I'll try to find a fix asap.

**Comment by lervag** [comment]
Now it works with the updated minimal working example. Can you verify that it works for you?

**Comment by Konfekt** [comment]
Yep, works, thanks!

**Comment by lervag** [comment]
Great!

**Comment by Rmano** [comment]
Works for me too. Thanks! (can you remove the "non-reproducible" label too? ;-))
