### ISSUE TITLE
VimtexInfo not an editor command & VimtexInverseSearch broke the neovim

### ISSUE THREAD

**Issue by chanbengz** [lervag/vimtex#2720]
### Description

I am using NvChad with Lazy.nvim on a M1 Chip Mac. I've done every step of installation and loaded vimtex when neovim starts. But `:help VimtexInfo` works well, and I've tried the solutions of previous issues, such as making `runtime/ftplugin.vim` be run after vimtex. These solutions all failed. I think it might be the problem of NvChad, but those who use NvChad as me don't have this issue. So I really really want you help.

### Steps to reproduce

<img width="2560" alt="Screenshot 2023-05-31 at 02 00 04" src="https://github.com/lervag/vimtex/assets/34162471/ffc1c7bb-54b1-4f7b-ac47-d2156bfeaafb">

### Expected behavior

VimtexInfo, VimtexCompile and all the commands are available.

### Actual behavior

Not an editor command

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
Can't run VimtexInfo
```

**Comment by lervag** [comment]
> ### Description
> 
> I am using NvChad with Lazy.nvim on a M1 Chip Mac. I've done every step of installation and loaded vimtex when neovim starts.

I don't know what "every step of installation" means. But for help with installing and configuring NvChad, you will have to ask the maintainers/users of NvChad. I'm sorry to say I know more or less nothing of it.

> But `:help VimtexInfo` works well,

So, `:help VimtexInfo` works and opens the docs, but `:VimtexInfo` in a TeX file does not work?

> and I've tried the solutions of previous issues, such as making `runtime/ftplugin.vim` be run after vimtex.

You are not showing me what you are actually doing now that is not working. I need much more than this.

> These solutions all failed.

Which solutions? Be explicit and concrete.

> I think it might be the problem of NvChad, but those who use NvChad as me don't have this issue. So I really really want you help.

I'll try and help, but you need to provide more information. What is your configuration? You should explain what you are trying to do in detailed steps.

> ### Steps to reproduce
> …

The screenshot only shows that VimTeX was not loaded at all. No VimTeX source file is present in the list from `:scriptnames`. Thus, it is not unexpected in this case that VimTeX is not available...?

**Comment by chanbengz** [comment]
<img width="2560" alt="Screenshot 2023-05-31 at 10 40 26" src="https://github.com/lervag/vimtex/assets/34162471/1d981554-8034-4d74-a0d7-e92e1706cb3f">

 Thanks for the timely reply! Somehow I woke up and found my `vimtex` works well after recovering the `ftplugin/tex.vim`. But I have no idea why. And the solutions I mentioned include commenting the `let b:did_ftplugin = 1`, trying to load `runtime/ftplugin` after `vimtex` and modifying the load of plugins in NvChad. I don't which of these solutions work. It might be the situation that I misconfigured somewhere and let these solutions fail. And the screenshot I post in `Steps to reproduce` is from the instructions of writing issue, say the result of running `nvim -u minimal.vim minimal.tex`. I thought it was irrelevant to my problem but I still followed the instructions. So that's why I post it and sorry for misleading you. Again, thank you very very very much!

**Comment by lervag** [comment]
> Thanks for the timely reply! Somehow I woke up and found my `vimtex` works well after recovering the `ftplugin/tex.vim`.

The computer works in mysterious ways.

By the way: I would recommend putting your VimTeX configuration either in `plugin/vimtex.vim` or in your regular `init.vim`, `init.lua` or `.vimrc` file. It may not matter, but IMHO, it is cleaner and avoids potential issues due to wrong load order of scripts.

> But I have no idea why. And the solutions I mentioned include commenting the `let b:did_ftplugin = 1`, trying to load `runtime/ftplugin` after `vimtex` and modifying the load of plugins in NvChad. I don't which of these solutions work.

I mean, I can't really help here either, because I have not seen your files and I can only guess what you are actually doing/saying here. :)

> And the screenshot I post in `Steps to reproduce` is from the instructions of writing issue, say the result of running `nvim -u minimal.vim minimal.tex`.

But you did not show the contents of `minimal.vim`. The regular `minimal.vim` that I suggest contains `runtimepath`s; for the file to work you must ensure these paths are correct.

> I thought it was irrelevant to my problem but I still followed the instructions. So that's why I post it and sorry for misleading you. Again, thank you very very very much!

It's OK; we all start somewhere on our journey to learn all the things. It's a long journey and I guess we never finish. Good luck!
