### ISSUE TITLE
Question: compile current file only

### ISSUE THREAD

**Issue by mangkoran** [lervag/vimtex#2723]
First of all, thank you for making such great tools! I am currently learning to write Latex and vimtex made it much easier.

I have a question regarding single file compilation. Currently my Latex document is split (and tied together) using `subfiles` package.

1. How can I compile a single file (current file to be exact) via vimtex?

As it seems vimtex 'detect' root/parent directory for current project, and pick it's 'main' Latex file to be compiled.

I use tectonic as my compiler, and use it's v2 interface. Below is my vimtex config.
```
System info:
  OS: Linux 5.15.90.1-microsoft-standard-WSL2
  Vim version: NVIM v0.9.1
  Has clientserver: true
  Servername: /run/user/1000//nvim.10303.0

VimTeX project: index
  base: index.tex
  root: /home/mangkoran/repo/utmthesis-new/src
  tex: /home/mangkoran/repo/utmthesis-new/src/index.tex
  main parser: subfiles
  document class: report
  packages: algorithm algpseudocode amsfonts amsmath appendix babel blindtext booktabs chngcntr etoolbox geometry graphicx hyperref inputenc mathtools parskip sectsty setspace subcaption subfiles tabularx titlesec titling tocbibind tocloft
  source files:
    index.tex
    utils/if-itb-thesis.sty
    chapters/cover.tex
    chapters/approval-multiple-advisors.tex
    chapters/approval-single-advisor.tex
    chapters/statement.tex
    chapters/abstract-id.tex
    chapters/abstract-en.tex
    chapters/forewords.tex
    chapters/chapter-1.tex
    chapters/chapter-2.tex
    chapters/chapter-3.tex
    chapters/chapter-4.tex
    chapters/chapter-5.tex
    chapters/appendix-1.tex
    chapters/appendix-2.tex
  compiler: tectonic
    options:
      -X
      compile
    job: 
      jobid: 17
      output: /tmp/nvim.mangkoran/VfjqpL/0
      cmd: tectonic -X compile --outdir="/home/mangkoran/repo/utmthesis-new/src" 'index.tex'
  viewer: Zathura
    xwin id: 0
    cmd_start: zathura  -x "/usr/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 23:1:'/home/mangkoran/repo/utmthesis-new/src/chapters/cover.tex' 'src/index.pdf'&
  qf method: LaTeX logfile
```

**Comment by lervag** [comment]
> First of all, thank you for making such great tools! I am currently learning to write Latex and vimtex made it much easier.

Glad you find it useful :)

> I have a question regarding single file compilation. Currently my Latex document is split (and tied together) using `subfiles` package.

I believe your answer is answered in the docs. Can you read `:help vimtex-subfiles` and let me know if that is enough of a nudge?

Note that I've not heard anyone try this with tectonic as the compiler backend, but I believe it should work. Let me know if you have problems.

**Comment by mangkoran** [comment]
Thank you for your reply. The `:VimtexToggleMain` is definitely what I am looking for. I should've read the docs thoroughly.

However, the behavior (or approach) is a bit not what I expected. If I have many subfiles, it seems that I need to `:VimtexToggleMain` on each subfiles that I would like to compile. What I think is that we could have a separate compilation command, one for the whole project (well, the main project file) and the other for only current file.

For example, if I have `a.tex`, `b.tex`, `c.tex`, and `main.tex`, and I would like to work on the child files, I need to go to each files and do `:VimtexToggleMain` in each files. If we have separate compilation command instead, we could either compile current file, or compile the main project file. All of that without changing the project.

Well, it could be that there is some approach that you utilize for this that I might not aware of.

**Comment by ejmastnak** [comment]
@mangkoran  how about defining a custom command (e.g. `ToggleMainAndCompile`) that calls `:VimtexToggleMain` and then `:VimtexCompile` immediately after? Or even simpler—you could create a Vim key mapping that does the same thing, i.e. calls `:VimtexToggleMain` and then `:VimtexCompile` immediately after.
These options would reduce the toggle main and compile workflow to a single command or key combination. 

Happy to help if you are unfamiliar with defining Vim commands or key mappings; it this case let me know if you are using Vimscript or Lua to configure Vim/Neovim.

**Comment by lervag** [comment]
> Thank you for your reply. The `:VimtexToggleMain` is definitely what I am looking for. I should've read the docs thoroughly.

Yes; most of us should, but I understand it is a lot of stuff to read. So don't worry about it.

> However, the behavior (or approach) is a bit not what I expected. If I have many subfiles, it seems that I need to `:VimtexToggleMain` on each subfiles that I would like to compile.

You could try the `g:vimtex_subfile_start_local` option. It will change the behaviour slightly and open the current file/subfile as the default "main" file. It seems this is what you want, and that changing the option might suffice.

> What I think is that we could have a separate compilation command, one for the whole project (well, the main project file) and the other for only current file.

If not, then @ejmastnak is right and it should be quite easy to make a custom mapping that does what you want.

**Comment by mangkoran** [comment]
> You could try the g:vimtex_subfile_start_local option. It will change the behaviour slightly and open the current file/subfile as the default "main" file. It seems this is what you want, and that changing the option might suffice.

Just tried it and well it should suffice my use case. Thank you very much everyone!

With that, I will close this ticket as solved.

**Comment by lervag** [comment]
Great, glad to hear it!
