### ISSUE TITLE
How to remap %?

### ISSUE THREAD

**Issue by gaoqiangks** [lervag/vimtex#2726]
I use vimtex with vscode-neovim plugin. However,  % doesn't work properly.  I want to remap % by myself but failed.  The simple setting `nnoremap % l` takes no effect.  I tried with neovim 0.8.1 with only vimtex loaded.

**Comment by lervag** [comment]
I don't know the vscode-neovim plugin at all.

> However, % doesn't work properly. I want to remap % by myself but failed. The simple setting nnoremap % l takes no effect.

You need to explain this in more detail. Where are you putting this setting?

I'm quriuos, why did you disregard the issue template?

**Comment by gaoqiangks** [comment]
> I don't know the vscode-neovim plugin at all.
> 
> > However, % doesn't work properly. I want to remap % by myself but failed. The simple setting nnoremap % l takes no effect.
> 
> You need to explain this in more detail. Where are you putting this setting?
> 
> I'm quriuos, why did you disregard the issue template?

I didn't disregard the issue template since I think this is not an enhancement request, or not a bug. Maybe I should use the General issue template.

My question actually has nothing to do with vscode-neovim plugin. The issue I encountered is the following:  

I want to remap the symbol %, but the code `map % l` doesn't work.  

To reproduce this is simple, just start neovim0.8 with only vimtex loaded.  I want to know, if I want to remap %, how should I do?
