### ISSUE TITLE
Delete _minted_.. folders when running `:VimtexClean`

### ISSUE THREAD

**Issue by doronbehar** [lervag/vimtex#2728]
**Is your feature request related to a problem? Please describe it.**

When I compile a document that has `\inputminted`, the compilation produces a directory `_minted_$(basename $texFileName)`. `:VimtexClean` doesn't clean this directory.

**Describe the solution you'd like**

I'd like to be able to tell `:Vimtex` that this path is an additional path that it might need to clean when I run `:VimtexClean`.

**Describe alternatives you've considered**

Removing it by hand - or overriding the command on my own `init.vim`.

**Comment by lervag** [comment]
If you use `latexmk` as the backend, then it is `latexmk` that also cleans files and directories. You need to instruct it to remove these files. I believe this SO question with answers and comments may be relevant: https://tex.stackexchange.com/questions/232338/how-to-set-latexmk-to-clean-directory.

**Comment by lervag** [comment]
To be more specific, I believe you can fix this by adding something like the following to your `.latexmkrc` file:

```perl
$clean_ext .= " _minted-%R/* _minted-%R";
```

**Comment by doronbehar** [comment]
> If you use `latexmk` as the backend

But @lervag , this is not generally the case. In my case, I use `tectonic` as the backend. Please reopen :pray: .

**Comment by lervag** [comment]
> > If you use `latexmk` as the backend
> 
> But @lervag, this is not generally the case. In my case, I use `tectonic` as the backend. Please reopen.

The detail about which backend you are using is clearly important. But I should have asked and not assumed, so sorry about that. I'll reopen.

Now, the question would be how to properly implement this. The current implementation is very simple: We simply delete all files named `${basename}.EXT` for a list of relevant extensions `EXT`. The current request will need to "complicate" things. I think we could hardcode this with something like this:

```vim
let l:dir = printf("%s/_minted_%s", self.state.root, self.state.base)
if isdirectory(l:dir)
  call delete(l:dir, 'rf')
endif
```

However, this requires some assertions:

1. Is `_minted_BASENAME` always the correct path name? If not, what are the possibilities and what controls this? According to the previously mentioned post, it seems the path is `_minted-SOMETHING`?
2. Will the directory always be placed in the root? Does it depend on the outdir-option (`g:vimtex_compiler_tectonic.out_dir`)?

**Comment by doronbehar** [comment]
>   1. Is `_minted_BASENAME` always the correct path name? If not, what are the possibilities and what controls this? According to the previously mentioned post, it seems the path is `_minted-SOMETHING`?
>   2. Will the directory always be placed in the root? Does it depend on the outdir-option (`g:vimtex_compiler_tectonic.out_dir`)?

So this topic is covered in [minted's manual](https://tug.ctan.org/macros/latex/contrib/minted/minted.pdf), section: _5.1 Package options_. It's pretty complicated - there's the `cachedir` package option, and there's the path sanitation, and LaTeX can be used to detokenize the string passed to `cachedir` etc.

I think that it'd be too much to ask vimtex to parse these options and figure out correctly the path to delete. What I was hoping for, is simply a way to manually add directories / paths to the list of paths that VimtexClean deletes. Then, we could advise in `vimtex.txt` that adding the glob `_minted*` there permanently, can be used for minted users that don't modify the default `cachedir`.

**Comment by lervag** [comment]
> > 1. Is `_minted_BASENAME` always the correct path name? If not, what are the possibilities and what controls this? According to the previously mentioned post, it seems the path is `_minted-SOMETHING`?
> > 2. Will the directory always be placed in the root? Does it depend on the outdir-option (`g:vimtex_compiler_tectonic.out_dir`)?
> 
> So this topic is covered in [minted's manual](https://tug.ctan.org/macros/latex/contrib/minted/minted.pdf), section: _5.1 Package options_. It's pretty complicated - there's the `cachedir` package option, and there's the path sanitation, and LaTeX can be used to detokenize the string passed to `cachedir` etc.

Thanks for the reference.

> I think that it'd be too much to ask vimtex to parse these options and figure out correctly the path to delete.

Agreed!

> What I was hoping for, is simply a way to manually add directories / paths to the list of paths that VimtexClean deletes.

I would actually prefer _not_ to add any options. But perhaps that's wishful thinking...

Ok, so, let's assume we have some option that does what you want. How would the docs look like? Perhaps something like this?

```vimhelp
*g:vimtex_compiler_clean_paths*
  A list of additional path expressions for generated files that you want to be
  cleaned by `:VimtexClean`. Each expression is a glob expression (see |glob()|
  and |wildcards|) and each path is assumed rooted to the project root.

  For instance, to clean any generated `_minted` paths (including directories),
  you could use something like this: >vim

    let g:vimtex_compiler_clean_paths = ['_minted*']
<
  Warning: Each resolved path will be deleted with |delete()| with the `"rf"`
           flag!

  Note: This option is only relevant for compiler backends that do not provide
        their own clean options:
        * |vimtex-compiler-tectonic|
        * |vimtex-compiler-arara|
        * |vimtex-compiler-generic|

  Default value: `[]`
```

**Comment by whisperity** [comment]
I suggest adding to the documentation the fact that *output directories* exist (for certain compiler toolchains, like latexmk?) and if the project is complex enough, these out-of-tree builds should be preferred (and less dangerous than executing a glob in the source directory). My on-going PhD thesis's `latexmkrc` contains several about 15 file extensions and the appropriate configuration for all the cleaning that `latexmk` would recognise and delete out-of-the-box...

-----

> To be more specific, I believe you can fix this by adding something like the following to your `.latexmkrc` file:
> 
> ```perl
> $clean_ext .= " _minted-%R/* _minted-%R";
> ```

@lervag Wow, it's so nice that this works now. At least can confirm `latexmk` version `4.80` does understand this nicely, even if an output directory is otherwise specified.

-----

> > 2. Will the directory always be placed in the root? Does it depend on the outdir-option (`g:vimtex_compiler_tectonic.out_dir`)?
> 
> So this topic is covered in [minted's manual](https://tug.ctan.org/macros/latex/contrib/minted/minted.pdf), section: _5.1 Package options_. It's pretty complicated - there's the `cachedir` package option, and there's the path sanitation, and LaTeX can be used to detokenize the string passed to `cachedir` etc.

@doronbehar @lervag It does depend on the outdir option, and using output directories with packages that generate external content (I found `epstopdf` when using `pdflatex`, `minted` and `svg` with all compilers to be affected) gets finicky. This post shows a sketch on how to set it up to work in the general case all the time: http://tex.stackexchange.com/questions/339931/latex-minted-package-using-custom-output-directory-build/548869#548869. Same deal with `\epstopdfsetup{outdir=...}` and `inkscapepath=...` for `svg`.

**Comment by doronbehar** [comment]
> How would the docs look like? Perhaps something like this?

This looks great as a starting point. However, @whisperity's comment makes me think that perhaps the docs should mention that latexmk's compiler method doesn't read this vimtex option because it has the `$clean_ext` option, that is recommended as an alternative. Perhaps this should be the documentation:

```vimhelp
*g:vimtex_compiler_clean_paths*
  A list of additional path expressions for generated files that you want to be
  cleaned by `:VimtexClean`. Each expression is a glob expression (see |glob()|
  and |wildcards|) and each path is assumed rooted to the project root.

  For instance, to clean any generated `_minted` paths (including directories),
  you could use something like this: >vim

    let g:vimtex_compiler_clean_paths = ['_minted*']
<
  Warning: Each resolved path will be deleted with |delete()| with the `"rf"`
           flag!

  Note: This option is only relevant for compiler backends that do not provide
        their own clean options (like `$clean_ext` in `latexmk`[1]):
        * |vimtex-compiler-tectonic|
        * |vimtex-compiler-arara|
        * |vimtex-compiler-generic|
    
  Default value: `[]`

  [1]: See `latexmk`'s `$clean_ext` documentation at https://texdoc.org/serve/latexmk/0
```

**Comment by lervag** [comment]
> I suggest adding to the documentation the fact that _output directories_ exist (for certain compiler toolchains, like latexmk?) …

I would be very happy to see a concrete suggestion on what to add and where to add it. A PR or just an inline suggestion. Thanks!

> > To be more specific, I believe you can fix this by adding something like the following to your `.latexmkrc` file:
> > ```perl
> > $clean_ext .= " _minted-%R/* _minted-%R";
> > ```
> 
> @lervag Wow, it's so nice that this works now. At least can confirm `latexmk` version `4.80` does understand this nicely, even if an output directory is otherwise specified.

Yes; I've been amazed at `latexmk` several times myself. It's a good piece of software!

> @doronbehar @lervag It does depend on the outdir option, and using output directories with packages that generate external content (I found `epstopdf` when using `pdflatex`, `minted` and `svg` with all compilers to be affected) gets finicky. This post shows a sketch on how to set it up to work in the general case all the time: http://tex.stackexchange.com/questions/339931/latex-minted-package-using-custom-output-directory-build/548869#548869. Same deal with `\epstopdfsetup{outdir=...}` and `inkscapepath=...` for `svg`.

Thanks for the info!

**Comment by lervag** [comment]
> > How would the docs look like? Perhaps something like this?
> 
> This looks great as a starting point. However, @whisperity's comment makes me think that perhaps the docs should mention that latexmk's compiler method doesn't read this vimtex option because it has the `$clean_ext` option, that is recommended as an alternative. …

Thanks! That seems wise. I think I'll go for something like this:

```vimhelp
*g:vimtex_compiler_clean_paths*
  A list of additional path expressions for generated files that you want to be
  cleaned by `:VimtexClean`. Each expression is a glob expression (see |glob()|
  and |wildcards|) and each path is assumed rooted to the project root.

  For instance, to clean any generated `_minted` paths (including directories),
  you could use something like this: >vim

    let g:vimtex_compiler_clean_paths = ['_minted*']
<
  Warning: Each resolved path will be deleted with |delete()| with the `"rf"`
           flag!

  Note: This option is NOT relevant for the compiler backends
        |vimtex-compiler-latexmk| and |vimtex-compiler-latexrun|, because these
        provide their own clean implementations. For `latexmk`, see the
        documentation for `$clean_ext` at https://texdoc.org/serve/latexmk/0.

  Default value: `[]`
```

**Comment by doronbehar** [comment]
> That seems wise. I think I'll go for something like this:

That's very good!

**Comment by lervag** [comment]
I believe this should work now. Please update and test.

**Comment by doronbehar** [comment]
It works great! Thanks :green_heart:

**Comment by lervag** [comment]
Great, glad to hear it!
