### ISSUE TITLE
Display frametitle of beamer class in toc

### ISSUE THREAD

**Issue by ChenZhongPu** [lervag/vimtex#2731]
When writing presentations using `beamer` class in Latex, `vimtex` only displays the beamer tags themselves in toc:

<img width="537" alt="image" src="https://github.com/lervag/vimtex/assets/2310958/e3cd9f37-f0c8-4b21-97c6-dd0ffc081025">

I would like the similar effect in Latex Workshop  of VSCode, where the*frametitles* are displayed:

<img width="388" alt="image" src="https://github.com/lervag/vimtex/assets/2310958/f80fb7fe-b673-45ac-9edd-2e0c4a969a98">

**Comment by ChenZhongPu** [comment]
I checked [beamer_frame.vim](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/parser/toc/beamer_frame.vim). Currently, it is able to extract titles and subtitles from frame using the following syntax:

```tex
\begin{frame}{title}{subtitle}
\end{frame}
```

But it fails to do so for:

```tex
\begin{frame}
	\frametitle{Sample frame title}
	\framesubtitle{Sample subtitle}
\end{frame}
```

**Comment by lervag** [comment]
Is the latter example the _only_ example you find VimTeX does not work as you expect?

**Comment by ChenZhongPu** [comment]
> Is the latter example the _only_ example you find VimTeX does not work as you expect?

Yes. `Latex Workshop` in VSCode works for both cases, while `vimtex` only works for the first example.

**Comment by ChenZhongPu** [comment]
BTW, if there is a `\section{}` inside `\frame{}`, it would be better to add an **indentation** like what Latex Workshop in VSCode does.

```tex
\begin{frame}
	\section{Conclusion}
\end{frame}
```

**Comment by lervag** [comment]
Why would you put a section _inside_ a frame? In my understanding, you should have section commands outside the frames.

**Comment by lervag** [comment]
According to the documentation, section 3.7 (https://texdoc.net/pkg/beamer):

> The next commands Euclid finds are
>
>   `\section{Motivation}`
>   `\subsection{The Basic Problem That We Studied}`
>
> **These commands are given outside of frames**. So Euclid assumes that at the point of invocation they have no direct effect, they only create entries in the table of contents. Having a “Motivation” section seems reasonable to Euclid, but he changes the \subsection title.

I could not find any example in the docs where the `\section` was included in a frame.

**Comment by lervag** [comment]
I believe the original issue is resolved now; please test.

**Comment by ChenZhongPu** [comment]
> I believe the original issue is resolved now; please test.

Thanks for your efforts. It works now, and I love `vimtex` even more :)

I think it would be better 

- to add a *serial number* after `Frame` (e.g., Frame 1) so that we can navigate/search it easily. 
- not to show the hyphen if the `framesubtitle` is not specified.

**Comment by lervag** [comment]
Thanks for the good suggestions; I've added both of these now. Please test again.
