### ISSUE TITLE
highlight

### ISSUE THREAD

**Issue by aloispichler** [lervag/vimtex#2732]
Hello again,

Thanks for vimtex.
Vimtex does a pretty nice job in highlighting math formulae and parts of these.
Highlight groups include `<texMathSymbol>`, `<texMathCmd>`, `<texCmdGreek>,` etc., for example in the formula `$\int\alpha(x) dx$`. Conceal displays them in even different colors.

XeLaTeX or LuaLaTeX allow inputting these formulae directly, as `$∫α(x) dx$`; however, without highlighting.
Would it be possible to have the same highlighting? An implementation might follow the conceal-dictionary… Thanks!

**Comment by lervag** [comment]
So, you want some specific list of utf8 symbols to be highlighted as the corresponding group for the corresponding command? More or less these:

* https://github.com/lervag/vimtex/blob/2b31261b20e44c4b3c79ca7e42e2f9a5cdbe8cd3/autoload/vimtex/syntax/core.vim#L1448
* https://github.com/lervag/vimtex/blob/2b31261b20e44c4b3c79ca7e42e2f9a5cdbe8cd3/autoload/vimtex/syntax/core.vim#L2142

Do I understand correctly?

**Comment by aloispichler** [comment]
Following your table for conceal,
`ℵ` should share the same color group as `\aleph`,
`∫` as `\int`, etc.

For Greek letters:
`δ` (and its unicode friends `δ𝝳𝛅𝛿𝛅𝞭`): same color group as `\delta`, etc.

I do understand that this is making too great demands, and just for a niche.
Greetings to Trondheim, where I lived 3+ year.

**Comment by lervag** [comment]
I've made an attempt at this that I think comes close (or even hits the spot). Please update and test. Let me know if you find any problems or unexpected behaviour due to this.

Also; greetings back! Trondheim is not the worst place to be these days - welcome back :)

**Comment by aloispichler** [comment]
Very helpful, indeed. So far, behavior as expected. Thank you!

**Comment by lervag** [comment]
Great; let me know if you find any unexpected inconsistencies. :)

**Comment by cionx** [comment]
Would it be possible to make this feature toggleable? I find that it leads to inconsistent highlighting, as can be seen in the following image:

![highlight](https://github.com/lervag/vimtex/assets/7231796/3d9986de-8f3a-4980-802f-5399a12f4af8)

In the first example, all four functions are highlighted in the same way. But in the second line, one of them is highlighted differently for no apparent reason. (Until I found this GitHub issue, I actually assumed that this was a bug.)

One of the advantages of direct Unicode input is that one doesn’t need to rely on TeX commands, which allows for a more consistent look and feel of the code, including consistent code highlighting. Adjusting the highlighting of part of the code to something that it specifically _isn’t_ (namely a TeX command) strikes me personally as more of an anti-feature. So I think it would be good if it could be disabled by the user.

I can also open a new issue, if this is more appropriate.

**Comment by lervag** [comment]
This was implemented in this function:

https://github.com/lervag/vimtex/blob/877de3ba5de5f766e5bfa1c3fb0d2ecfcd18f868/autoload/vimtex/syntax/core.vim#L2050-L2062

Notice that it will match greek unicode letters as `texCmdGreek`, but also a quite large list of unicode symbols defined near line 1528 as `texMathSymbol`. Would you find it OK if all of this is behind an option, or should there be more granularity?

**Comment by aloispichler** [comment]
For me, this is just fine. Thanks!

**Comment by cionx** [comment]
I was personally okay with the behaviour before 7bf2a74d817bcebd4636eaa85f4d2614979af748, so putting all the Unicode highlighting behind an option should be fine for me.

I think the “proper” solution to highlighting Unicode characters would be to highlight them depending on their semantics:

- letters (Greek, Fraktur, …) the same as regular Latin letters,
- operations (`∪`, `⊗`, …) the same as `+`,
- relations (`≤`, `<`, `‖`, …) the same as `=`,
- …

But this is probably far too much work, as not many people use direct Unicode input. (I don’t know how many people use conceal.)

**Comment by lervag** [comment]
> I was personally okay with the behaviour before [7bf2a74](https://github.com/lervag/vimtex/commit/7bf2a74d817bcebd4636eaa85f4d2614979af748), so putting all the Unicode highlighting behind an option should be fine for me.

Cool, I'll add an option for this, then.

> I think the “proper” solution to highlighting Unicode characters would be to highlight them depending on their semantics: …

> But this is probably far too much work, as not many people use direct Unicode input. (I don’t know how many people use conceal.)

Yes, I agree that this is a better solution, but I also agree it is quite a lot of work, and I'm not interested in doing it myself. I wouldn't mind a PR if anyone did the work, though.

**Comment by lervag** [comment]
I need to specify a default value here. I'll choose default true, since that is the defacto current value. Thus, if you want to disable, you need to add

```vim
let g:vimtex_syntax_match_unicode = v:false
```

or, in Lua,

```lua
vim.g.vimtex_syntax_match_unicode = false
```

**Comment by cionx** [comment]
Thanks, that works for me.

**Comment by aloispichler** [comment]
Thank you!
