### ISSUE TITLE
conceal of \emph breaks in ( ... )

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#274]
Whereas in `\emph{abc}` the text `abc` is displayed italic and `\emph{}` hidden, in
```tex
(\emph{abc})
```
it is displayed as is.

**Comment by Rmano** [comment]
I'm starting to think that conceal is evil(TM)... I have ` conceallevel=0` in my `.vimrc`, and  I can see the same ... `abc ` in `(\emph{abc}) is not displayed as slanted. 
A minor glitch, I can live with it. Is there a way to disable conceal _completely_ for latex files? I do not want any wysywig...

**Comment by Konfekt** [comment]
Try
```vim
let g:tex_conceal = ''
```

**Comment by lervag** [comment]
@Rmano I think @Konfekt is right: you can turn off conceal completely with `let g:tex_conceal = ''`.

**Comment by Konfekt** [comment]
Thanks again. Hopefully that's been it.
