### ISSUE TITLE
Please let VimtexDocPackage recognize packages within \RequirePackage commands. 

### ISSUE THREAD

**Issue by grbll** [lervag/vimtex#2753]
Currently `K` opens package info on `\usepackage{amsmath}`, however if used on `\RequirePackage{amsmath}` it asks whether to open on latex2e, or lshort. 

I assume it doesn't recognize \RequirePackage. I would love it, if this feature would be added.

PS: I admire your work. Thank you.

**Comment by lervag** [comment]
> Currently `K` opens package info on `\usepackage{amsmath}`, however if used on `\RequirePackage{amsmath}` it asks whether to open on latex2e, or lshort.
> 
> I assume it doesn't recognize \RequirePackage. I would love it, if this feature would be added.

Thanks for the suggestion! It should work now, I think.

> PS: I admire your work. Thank you.

Thanks for the kind words! <3
