### ISSUE TITLE
Add math environment `DispWithArrows` from package `witharrows`

### ISSUE THREAD

**Issue by Nora-n** [lervag/vimtex#2755]
Currently, the environment `DispWithArrows` loaded from the package `witharrows` (see [ctan](https://www.ctan.org/pkg/witharrows)) is not considered a math environment.
```latex
\usepackage{physics}
\usepackage{witharrows}
\begin{DispWithArrows}
  \dv{i_2}{t} &= - \frac{M}{L_2} \dv{i_1}{t}
  \Arrow{\text{par intégration}} \\
  \Rightarrow
  i_2 &= -\frac{M}{L_2}i_1 + \mathrm{cte}
\end{DispWithArrows}
```

It would be a huge help to have this environment read as a mathzone with `vimtex#syntax#in_mathzone`

**Comment by lervag** [comment]
The witharrows documentation was 100 pages long, so I'm sure there are improvements to be had here. But I'll leave it to you/users to raise issues for that. If you find something missing, feel free to reopen the issue or open a new issue. If so, please provide an example (preferably a minimal one that I can compile) on which I can reproduce the missing feature.

And thanks for contributing to the project by suggesting improvements! :)
