### ISSUE TITLE
Syntax highlighting of C in math zone

### ISSUE THREAD

**Issue by coolbluealan** [lervag/vimtex#2761]
### Description

Any capital C in a math zone is highlighted differently than other letters. I believe it is introduced by [this commit](https://github.com/lervag/vimtex/commit/7bf2a74d817bcebd4636eaa85f4d2614979af748) and [this line](https://github.com/lervag/vimtex/blob/95579267d48a6b4e8e99c4f32456cba992565ea2/autoload/vimtex/syntax/core.vim#L1690). 

The  "C" value in the dictionary is making every C highlighted with `texMathSymbol`. I think a solution is to take that pair out of the dictionary and highlight it separately. If highlighting Cs differently is intended, is there any way I can disable it?

### Steps to reproduce

Type a "C" in a math zone along with some other letters.

### Expected behavior

The letters are highlighted the same.

### Actual behavior

![image](https://github.com/lervag/vimtex/assets/39867758/236e9eb7-f704-4251-8943-6e729457480d)

**Comment by lervag** [comment]
Thanks, you're right. I've fixed this now.
