### ISSUE TITLE
Math enviorment subtype

### ISSUE THREAD

**Issue by VolinM** [lervag/vimtex#2764]
Hey, is there any way to prompt vimtex wether I'm on a matrix or cases environment? Similar to the `vim.fn["vimtex#syntax#in_mathzone"]`?

**Comment by lervag** [comment]
I think `vimtex#env#is_inside("env_name")` can be useful to you. You could use it e.g. like this:

```lua
local pos_match = vim.fn["vimtex#env#is_inside"]("cases")
```

The return value is the same as `:help searchpairpos()` and will be `{0, 0}` if one is not inside the environment.

**Comment by VolinM** [comment]
Thanks! Honestly you're one of the best maintainers I've seen! Cheers man!

**Comment by VolinM** [comment]
Lastly, is there a general way to determine all kind of matrices, or do I have to input one by one?

**Comment by lervag** [comment]
> Thanks! Honestly you're one of the best maintainers I've seen! Cheers man!

Thanks! <3

> Lastly, is there a general way to determine all kind of matrices, or do I have to input one by one?

You can use a regular expression, e.g. something like this:

```lua
local pos_match = vim.fn["vimtex#env#is_inside"]("\wmatrix")
```
