### ISSUE TITLE
More granular toggling of delimiters

### ISSUE THREAD

**Issue by danieleavitabile** [lervag/vimtex#2768]
**Is your feature request related to a problem? Please describe it.**
I always use delimiters of type \big(, \bigg(, \Big(, \Bigg( as opposed to \left(, as I prefer having control over the delimiters' size. Vimtex's shortcuts for delimiters seem to target only the latter use case.

**Describe the solution you'd like**
I would like to toggle between delimiter size (in the list above). I would also want to transform a standard ( delimiter into a \big(, or start toggling \left(, \big(, \bigg(, \Big(, \Bigg( 

**Describe alternatives you've considered**
I am conscious the steps above may be uncommon, so I would be happy to implement this with my own shortcuts, if I am given some help about doing this. I wonder if there is a way to implement this in vimtex without being disruptive to the current setup.

**Comment by lervag** [comment]
If I understand you correctly, what you want is to change `:help g:vimtex_delim_toggle_mod_list`, e.g. something like this:

```vim
let g:vimtex_delim_toggle_mod_list = [
      \ ['\bigl', '\bigr'],
      \ ['\Bigl', '\Bigr'],
      \ ['\biggl', '\biggr'],
      \ ['\Biggl', '\Biggr'],
      \]
```

Notice, though, that you really _should_ use the `\bigl(...\bigr)` variants, and _not_ the `\big(...\big)` variants, and also that this is the only variants supported by VimTeX for this purpose.

**Comment by danieleavitabile** [comment]
This is excellent, and thanks for the tip also on` \bigl(... \bigr)`

**Comment by danieleavitabile** [comment]
This is excellent, and thanks for the tip also on` \bigl(... \bigr)`

**Comment by lervag** [comment]
My pleasure :)
