### ISSUE TITLE
Root file detection: respect %!TEX root magic comment

### ISSUE THREAD

**Issue by wookayin** [lervag/vimtex#2769]
I find prompting users to choose the root tex file quite annoying as it blocks the UI, `"Please select an appropriate main file: ..."` and would like to have it automatically determined in some programmatic ways.

But how to tell tex source files which is an appropriate main file to use? One way is to use the `%!TEX root` root magic comment, e.g.

```
%!TEX root = the_main_file.tex
```

If this matches the candidate root files, we would NOT need to prompt users every single time we open a tex file. Or an alternative way is to use some RC files such as `.latexmkrc`.

Ideally, it would be also great to have some user-configurable hook (vim function or lua function in neovim) to customize the behavior or let users write a logic to determine the root file; when it fails to resolve one we could still fall back to prompting users.

**Comment by wookayin** [comment]
Hmm this feature already seems to be implemented. In `autoload/vimtex/state.vim`, `s:get_main()`:

- Use `b:vimtex_main` buffer local variable (this can be set in user's ftplugin)
- Search for TEX root specifier at the beginning of file. This is used by
  several other plugins and editors.
- Search for .latexmain-specifier
- Search for .latexmkrc @default_files specifier
- and then ask users if still not found.

Indeed the TEX root magic is being parsed correctly,

The reason I find this was not working is that because the specified root file would be find relative to the tex file, not from the CWD.

**Comment by lervag** [comment]
Hi! Sorry for the late reply! I notice that you already closed the issue, so I assume you found this to be already resolved.

> But how to tell tex source files which is an appropriate main file to use?

There are several ways, please read `:help vimtex-multi-file` for a full overview. The `%!TeX root` directive is the second method mentioned there.

> Hmm this feature already seems to be implemented. Sorry for an invalid issue.

No problem!

> In `autoload/vimtex/state.vim`, `s:get_main()`:

I'm always glad when people inspect the code for figuring out how things work :)

> The reason I find this was not working is that because the specified root file would be found relative to the tex file, not from the CWD. This can be a problem when individual `.tex` source files do not exist in the root directory as the main(root) file.

I'm sorry, I don't quite understand this. Are you saying there is a case that is not properly handled here? If so, should we reopen?
