### ISSUE TITLE
Instructions to install using Lazy package manager

### ISSUE THREAD

**Issue by coderpotter** [lervag/vimtex#2770]
### Description

I'm using Astronvim that uses the lazy package manager. I cannot find the instructions to install vimtex using Lazy. I tried just adding `lervag/vimtex` to my plugins.lua file but that did not work. 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
N/A
```

**Comment by lervag** [comment]
> I'm using Astronvim that uses the lazy package manager. I cannot find the instructions to install vimtex using Lazy. I tried just adding `lervag/vimtex` to my plugins.lua file but that did not work.

This sounds like a proposal for updating the README file, but then you closed the issue. Did you figure things out?

**Comment by coderpotter** [comment]
Yes. Lazy loading was the key.

**Comment by RuanBritzke** [comment]
Could you elaborate on how you were able to do it? I'm struggling hard

**Comment by lervag** [comment]
> Could you elaborate on how you were able to do it? I'm struggling hard

Are you struggling with installing VimTeX with lazy.nvim? What did you try?
