### ISSUE TITLE
Error on opening file in neovim

### ISSUE THREAD

**Issue by wohlersgit** [lervag/vimtex#2774]
### Description

every time i open a latex file i get following error message:

```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /usr/share/nvim/runtime/filetype.lua:21: Error executing lua: /usr/share/nvim/runtime/filetype.lua:22: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SNR>1_LoadFTPlugin[19]..script /home/yannik/.config/nvim/plugged/vimtex/ftplugin/tex.vim[25]..function vimtex#init[7]..<SNR>84_init_state[1]..vimtex#state#init[9]..vimtex#state#class#new[36]..vimtex#qf#init_state, line 4: Vim(let):E117: Unknown function: vimtex#qf#0#new
stack traceback:
	[C]: in function 'nvim_cmd'
	/usr/share/nvim/runtime/filetype.lua:22: in function </usr/share/nvim/runtime/filetype.lua:21>
	[C]: in function 'nvim_buf_call'
	/usr/share/nvim/runtime/filetype.lua:21: in function </usr/share/nvim/runtime/filetype.lua:10>
stack traceback:
	[C]: in function 'nvim_buf_call'
	/usr/share/nvim/runtime/filetype.lua:21: in function </usr/share/nvim/runtime/filetype.lua:10>
```

also commands like `:VimtexInfo` are not found. One suggestion was to set `g:tex_flavor = 'latex'` but this doesn't helped.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
E492: Not an editor command: VimtexInfo
```

**Comment by lervag** [comment]
> every time i open a latex file i get following error message: …

How did you install VimTeX? Which version of Vim or neovim are you using? What is your configuration?

> One suggestion was to set `g:tex_flavor = 'latex'` but this doesn't helped.

Where did you see that suggestion? This option is irrelevant to VimTeX and you don't need it.

**Comment by wohlersgit** [comment]
I cloned the repository and installed via VimPlug. I use neovim version 0.9.1 with following configuration:
`
let mapleader =","

if ! filereadable(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/plug.vim"'))
	echo "Downloading junegunn/vim-plug to manage plugins..."
	silent !mkdir -p ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/
	silent !curl "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" > ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/autoload/plug.vim
	autocmd VimEnter * PlugInstall
endif

map ,, :keepp /<++><CR>ca<
imap ,, <esc>:keepp /<++><CR>ca<

call plug#begin(system('echo -n "${XDG_CONFIG_HOME:-$HOME/.config}/nvim/plugged"'))
Plug 'tpope/vim-surround'
Plug 'preservim/nerdtree'
Plug 'junegunn/goyo.vim'
Plug 'jreybert/vimagit'
Plug 'vimwiki/vimwiki'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-commentary'
Plug 'ap/vim-css-color'
Plug 'lervag/vimtex'
Plug 'SirVer/ultisnips'
Plug 'KeitaNakamura/tex-conceal.vim'
Plug 'dylanaraps/wal'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

set title
set bg=light
set go=a
set mouse=a
set nohlsearch
set clipboard+=unnamedplus
set noshowmode
set noruler
set laststatus=0
set noshowcmd

" Some basics:
	nnoremap c "_c
	set nocompatible
	filetype plugin on
	syntax on
	set encoding=utf-8
	set number relativenumber
" Enable autocompletion:
	set wildmode=longest,list,full
" Disables automatic commenting on newline:
	autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
" Perform dot commands over visual blocks:
	vnoremap . :normal .<CR>
" Goyo plugin makes text more readable when writing prose:
	map <leader>f :Goyo \| set bg=light \| set linebreak<CR>
" Spell-check set to <leader>o, 'o' for 'orthography':
	map <leader>o :setlocal spell! spelllang=de,en<CR>
	setlocal spellfile=/home/yannik/.config/nvim/spell/de.utf-8.add,/home/yannik/.config/nvim/spell/en.utf-8.add
" Splits open at the bottom and right, which is non-retarded, unlike vim defaults.
	set splitbelow splitright

" Nerd tree
	map <leader>n :NERDTreeToggle<CR>
	autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
    if has('nvim')
        let NERDTreeBookmarksFile = stdpath('data') . '/NERDTreeBookmarks'
    else
        let NERDTreeBookmarksFile = '~/.vim' . '/NERDTreeBookmarks'
    endif

" vimling:
	nm <leader>d :call ToggleDeadKeys()<CR>
	imap <leader>d <esc>:call ToggleDeadKeys()<CR>a
	nm <leader>i :call ToggleIPA()<CR>
	imap <leader>i <esc>:call ToggleIPA()<CR>a
	nm <leader>q :call ToggleProse()<CR>

" Shortcutting split navigation, saving a keypress:
	map <C-h> <C-w>h
	map <C-j> <C-w>j
	map <C-k> <C-w>k
	map <C-l> <C-w>l

" Replace ex mode with gq
	map Q gq

" Check file in shellcheck:
	map <leader>s :!clear && shellcheck -x %<CR>

" Open my bibliography file in split
	map <leader>b :vsp<space>$BIB<CR>
	map <leader>r :vsp<space>$REFER<CR>

" Replace all is aliased to S.
	nnoremap S :%s//g<Left><Left>

" Compile document, be it groff/LaTeX/markdown/etc.
	map <leader>c :w! \| !compiler "%:p"<CR>

" Open corresponding .pdf/.html or preview
	map <leader>p :silent !opout "%:p"<CR>

" Runs a script that cleans out tex build files whenever I close out of a .tex file.
	autocmd VimLeave *.tex !texclear %

" Ensure files are read as what I want:
	let g:vimwiki_ext2syntax = {'.Rmd': 'markdown', '.rmd': 'markdown','.md': 'markdown', '.markdown': 'markdown', '.mdown': 'markdown'}
	map <leader>v :VimwikiIndex<CR>
	let g:vimwiki_list = [{'path': '~/.local/share/nvim/vimwiki', 'syntax': 'markdown', 'ext': '.md'}]
	autocmd BufRead,BufNewFile /tmp/calcurse*,~/.calcurse/notes/* set filetype=markdown
	autocmd BufRead,BufNewFile *.ms,*.me,*.mom,*.man set filetype=groff
	autocmd BufRead,BufNewFile *.tex set filetype=tex

" Save file as sudo on files that require root permission
	cabbrev w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

" Enable Goyo by default for mutt writing
	autocmd BufRead,BufNewFile /tmp/neomutt* let g:goyo_width=80
	autocmd BufRead,BufNewFile /tmp/neomutt* :Goyo | set bg=light
	autocmd BufRead,BufNewFile /tmp/neomutt* map ZZ :Goyo\|x!<CR>
	autocmd BufRead,BufNewFile /tmp/neomutt* map ZQ :Goyo\|q!<CR>

" Automatically deletes all trailing whitespace and newlines at end of file on save. & reset cursor position
 	autocmd BufWritePre * let currPos = getpos(".")
	autocmd BufWritePre * %s/\s\+$//e
	autocmd BufWritePre * %s/\n\+\%$//e
  autocmd BufWritePre *.[ch] %s/\%$/\r/e " add trailing newline for ANSI C standard
  autocmd BufWritePre *neomutt* %s/^--$/-- /e " dash-dash-space signature delimiter in emails
  	autocmd BufWritePre * cal cursor(currPos[1], currPos[2])

" When shortcut files are updated, renew bash and ranger configs with new material:
	autocmd BufWritePost bm-files,bm-dirs !shortcuts
" Run xrdb whenever Xdefaults or Xresources are updated.
	autocmd BufRead,BufNewFile Xresources,Xdefaults,xresources,xdefaults set filetype=xdefaults
	autocmd BufWritePost Xresources,Xdefaults,xresources,xdefaults !xrdb %
" Recompile dwmblocks on config edit.
	autocmd BufWritePost ~/.local/src/dwmblocks/config.h !cd ~/.local/src/dwmblocks/; sudo make install && { killall -q dwmblocks;setsid -f dwmblocks }

" Turns off highlighting on the bits of code that are changed, so the line that is changed is highlighted but the actual text that has changed stands out on the line and is readable.
if &diff
    highlight! link DiffText MatchParen
endif

" Function for toggling the bottom statusbar:
let s:hidden_all = 0
function! ToggleHiddenAll()
    if s:hidden_all  == 0
        let s:hidden_all = 1
        set noshowmode
        set noruler
        set laststatus=0
        set noshowcmd
    else
        let s:hidden_all = 0
        set showmode
        set ruler
        set laststatus=2
        set showcmd
    endif
endfunction
nnoremap <leader>h :call ToggleHiddenAll()<CR>
" Load command shortcuts generated from bm-dirs and bm-files via shortcuts script.
" Here leader is ";".
" So ":vs ;cfz" will expand into ":vs /home/<user>/.config/zsh/.zshrc"
" if typed fast without the timeout.
silent! source ~/.config/nvim/shortcuts.vim

" This is necessary for VimTeX to load properly. The "indent" is optional.
" Note that most plugin managers will do this automatically.
filetype plugin indent on

" This enables Vim's and neovim's syntax-related features. Without this, some
" VimTeX features will not work (see ":help vimtex-requirements" for more
" info).
syntax enable

" Viewer options: One may configure the viewer either by specifying a built-in
" viewer method:
let g:vimtex_view_method = 'zathura'

" Or with a generic interface:
let g:vimtex_view_general_viewer = 'zathura'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'

" VimTeX uses latexmk as the default compiler backend. If you use it, which is
" strongly recommended, you probably don't need to configure anything. If you
" want another compiler backend, you can change it as follows. The list of
" supported backends and further explanation is provided in the documentation,
" see ":help vimtex-compiler".
let g:vimtex_compiler_method = 'latexmk'

" Most VimTeX mappings rely on localleader and this can be changed with the
" following line. The default is usually fine and is the symbol "\".
let maplocalleader = ","

let g:tex_flavor='latex'
let g:vimtex_quickfix_method=0
set conceallevel=1
let g:tex_conceal='abdmg'
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
hi Conceal ctermbg=none

" setlocal spell
" set spelllang=en_us, de
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u
" colorscheme wal
set background=dark
autocmd BufWritePost *.tex :silent !compiler "%:p"

let g:deoplete#enable_at_startup = 1
call deoplete#custom#option('ignore_sources', {'_': ['around', 'buffer']})

inoremap <C-f> <Esc>: silent exec '.!inkscape-figures create "'.getline('.').'" "'.g:vimtex#root.'/figures/"'<CR><CR>:w<CR>
nnoremap <C-f> : silent exec '!inkscape-figures edit "'.g:vimtex#root.'/figures/" > /dev/null 2>&1 &'<CR><CR>:redraw!<CR>

if has('unix')
	language messages C
else
	language messages en
endif
`

I can compile without problems, the concealment works fine but the commands like :VimtexInfo doesn't work and i don't have access to vimtex variables.

> Where did you see that suggestion? This option is irrelevant to VimTeX and you don't need it.

I saw this suggestion on a closed Issue where an user hat also problems when opening a latex document.

**Comment by wohlersgit** [comment]
To test I also installed vim, linked my init.vim to .vimrc installed the plugins via vim-plug and got the same result all plugins worked (except deoplete which was configured only for neovim) but i get the same error message for vimtex and the only vimtex command that vim and neovim can find is VimtexInverseSearch

**Comment by lervag** [comment]
> I cloned the repository and installed via VimPlug. I use neovim version 0.9.1 with following configuration: …

Thanks. I can't see anything immediately wrong. However, you are doing a lot of unnecessary stuff in your vimrc file. I won't comment on it all, because I don't have the time. But some comments are warranted:
* There is not reason to define autocommands for `.tex` files.
* There is no reason for `filetype plugin on` and `syntax on`, which you for no reason repeat later just before the VimTeX config part. This is already set by `plug#end()`.
* You should keep the `maplocalleader` line together with the `mapleader` line.
* You don't need to set `tex_flavor` and `tex_conceal` (they are not relevant to VimTeX).
* 0 is not a valid option for `g:vimtex_quickfix_method`!
* You have an autocommand to run `!compiler` on BufWritePost for tex files. This is not related to VimTeX and will conflict!
* It is very clear to me that you have more or less blindly copied configuration from different sources. That is a sure way to get into problems. As far as possible, I strongly advice to only copy things you properly understand!

The VimTeX specific stuff can be very much simplified. I would remove everything from "This is necessary for VimTeX to load properly" until the UltiSnips stuff with the following single line:

```vim
let g:vimtex_view_method = 'zathura'
```

The `set conceallevel` should be together with your other general settings, and you should notice that it is a window local option (see `:help options` and for more info - generally, _do_ read the documentation for things).

> I can compile without problems, the concealment works fine but the commands like `:VimtexInfo` doesn't work and i don't have access to vimtex variables.

If `:VimtexInfo` does not work, then you _can't_ compile with VimTeX. If you compile without problems, then that comes from somewhere else.

> > Where did you see that suggestion? This option is irrelevant to VimTeX and you don't need it.
> 
> I saw this suggestion on a closed Issue where an user hat also problems when opening a latex document.

Please refer to that specific closed issue, then. VimTeX is under continuous development, and things that may have been relevant 7 years ago are probably not relevant now.

> To test I also installed vim, linked my init.vim to .vimrc installed the plugins via vim-plug and got the same result all plugins worked (except deoplete which was configured only for neovim) but i get the same error message for vimtex and the only vimtex command that vim and neovim can find is VimtexInverseSearch

I believe your problem is related to VimTeX not being properly loaded. It is impossible, so far, to say exactly why. But I would not be surprised if you have installed another LaTeX plugin for Vim in your system. It is easy to check. Do this:

1. Open some `.tex` file (doesn't matter which one).
2. Run `:scriptnames` and copy the content to a reply to this thread.

**Comment by wohlersgit** [comment]
Yeah the config is very bad it's from an old server, when i didn't hat any experience no i changed distros and something broke with it and now i want to fix everything and clean everything up, hopefully without having to redo everything

> The set conceallevel should be together with your other general settings, and you should notice that it is a window local option (see :help options and for more info - generally, do read the documentation for things)

this setting actually is global it works fine and if i comment this line out the concealment is gone

> If :VimtexInfo does not work, then you can't compile with VimTeX. If you compile without problems, then that comes from somewhere else.

Oh sorry you are right i compile with an autocommand i had the hopes it didn't conflict but maybe there is the error.
But the strange thing is in nvim I don't have access to anything except :VimtexInverseSearch (which crashes nvim) but in ultisnips i can use `vim,eval("vimtex#syntax#in_mathzone()")` just fine.

> Run :scriptnames and copy the content to a reply to this thread.

`
  1: /usr/share/nvim/runtime/ftplugin.vim
  2: /usr/share/nvim/runtime/indent.vim
  3: /etc/xdg/nvim/sysinit.vim
  4: /usr/share/nvim/archlinux.vim
  5: ~/.config/nvim/init.vim
  6: /usr/share/nvim/runtime/filetype.lua
  7: ~/.local/share/nvim/site/pack/packer/start/ultisnips/ftdetect/snippets.vim
  8: ~/.local/share/nvim/site/pack/packer/start/vimtex/ftdetect/cls.vim
  9: ~/.local/share/nvim/site/pack/packer/start/vimtex/ftdetect/tex.vim
 10: ~/.local/share/nvim/site/pack/packer/start/vimtex/ftdetect/tikz.vim
 11: /usr/share/vim/vimfiles/ftdetect/lf.vim
 12: /usr/share/nvim/runtime/syntax/syntax.vim
 13: /usr/share/nvim/runtime/syntax/synload.vim
 14: ~/.config/nvim/shortcuts.vim
 15: /usr/share/nvim/runtime/syntax/nosyntax.vim
 16: ~/.local/share/nvim/site/pack/packer/start/deoplete.nvim/autoload/deoplete/custom.vim
 17: ~/.local/share/nvim/site/pack/packer/start/deoplete.nvim/autoload/deoplete/init.vim
 18: /usr/share/nvim/runtime/plugin/gzip.vim
 19: /usr/share/nvim/runtime/plugin/health.vim
 20: /usr/share/nvim/runtime/plugin/matchit.vim
 21: /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 22: /usr/share/nvim/runtime/plugin/matchparen.vim
 23: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 24: /usr/share/nvim/runtime/plugin/rplugin.vim
 25: ~/.local/share/nvim/rplugin.vim
 26: /usr/share/nvim/runtime/autoload/remote/host.vim
 27: /usr/share/nvim/runtime/autoload/remote/define.vim
 28: /usr/share/nvim/runtime/plugin/shada.vim
 29: /usr/share/nvim/runtime/plugin/spellfile.vim
 30: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 31: /usr/share/nvim/runtime/plugin/tohtml.vim
 32: /usr/share/nvim/runtime/plugin/tutor.vim
 33: /usr/share/nvim/runtime/plugin/zipPlugin.vim
 34: /usr/share/vim/vimfiles/plugin/fzf.vim
 35: /usr/share/vim/vimfiles/plugin/redact_pass.vim
 36: ~/.config/nvim/plugin/packer_compiled.lua
 37: /usr/share/nvim/runtime/plugin/editorconfig.lua
 38: /usr/share/nvim/runtime/plugin/man.lua
 39: /usr/share/nvim/runtime/plugin/nvim.lua
 40: ~/.local/share/nvim/site/pack/packer/start/deoplete.nvim/plugin/deoplete.vim
 41: ~/.local/share/nvim/site/pack/packer/start/deoplete.nvim/autoload/deoplete.vim
 42: ~/.local/share/nvim/site/pack/packer/start/goyo.vim/plugin/goyo.vim
 43: ~/.local/share/nvim/site/pack/packer/start/nerdtree/plugin/NERD_tree.vim
 44: ~/.local/share/nvim/site/pack/packer/start/nerdtree/autoload/nerdtree.vim
 45: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/path.vim
 46: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/menu_controller.vim
 47: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/menu_item.vim
 48: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/key_map.vim
 49: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/bookmark.vim
 50: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/tree_file_node.vim
 51: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/tree_dir_node.vim
 52: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/opener.vim
 53: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/creator.vim
 54: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/flag_set.vim
 55: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/nerdtree.vim
 56: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/ui.vim
 57: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/event.vim
 58: ~/.local/share/nvim/site/pack/packer/start/nerdtree/lib/nerdtree/notifier.vim
 59: ~/.local/share/nvim/site/pack/packer/start/nerdtree/autoload/nerdtree/ui_glue.vim
 60: ~/.local/share/nvim/site/pack/packer/start/nerdtree/nerdtree_plugin/exec_menuitem.vim
 61: ~/.local/share/nvim/site/pack/packer/start/nerdtree/nerdtree_plugin/fs_menu.vim
 62: /usr/share/nvim/runtime/autoload/provider/clipboard.vim
 63: ~/.local/share/nvim/site/pack/packer/start/nerdtree/nerdtree_plugin/vcs.vim
 64: ~/.local/share/nvim/site/pack/packer/start/ultisnips/plugin/UltiSnips.vim
 65: ~/.local/share/nvim/site/pack/packer/start/ultisnips/autoload/UltiSnips/map_keys.vim
 66: ~/.local/share/nvim/site/pack/packer/start/vim-airline/plugin/airline.vim
 67: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/init.vim
 68: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/parts.vim
 69: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/formatter/short_path.vim
 70: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/util.vim
 71: ~/.local/share/nvim/site/pack/packer/start/vim-commentary/plugin/commentary.vim
 72: ~/.local/share/nvim/site/pack/packer/start/vim-surround/plugin/surround.vim
 73: ~/.local/share/nvim/site/pack/packer/start/vimagit/plugin/magit.vim
 74: ~/.local/share/nvim/site/pack/packer/start/vimagit/common/magit_common.vim
 75: ~/.local/share/nvim/site/pack/packer/start/vimtex/plugin/vimtex.vim
 76: ~/.local/share/nvim/site/pack/packer/start/vimwiki/plugin/vimwiki.vim
 77: ~/.local/share/nvim/site/pack/packer/start/vimwiki/autoload/vimwiki/vars.vim
 78: ~/.local/share/nvim/site/pack/packer/start/vimwiki/autoload/vimwiki/u.vim
 79: ~/.local/share/nvim/site/pack/packer/start/vimwiki/autoload/vimwiki/base.vim
 80: ~/.local/share/nvim/site/pack/packer/start/vimwiki/autoload/vimwiki/markdown_base.vim
 81: ~/.local/share/nvim/site/pack/packer/start/vimwiki/autoload/vimwiki/path.vim
 82: ~/.local/share/nvim/site/pack/packer/start/ultisnips/after/plugin/UltiSnips_after.vim
 83: ~/.local/share/nvim/site/pack/packer/start/vimtex/ftplugin/tex.vim
 84: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex.vim
 85: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/options.vim
 86: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/util.vim
 87: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/jobs.vim
 88: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/cache.vim
 89: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/paths.vim
 90: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/state.vim
 91: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/re.vim
 92: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/parser.vim
 93: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/parser/tex.vim
 94: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/kpsewhich.vim
 95: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/state/class.vim
 96: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/view.vim
 97: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/view/zathura.vim
 98: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/view/_template.vim
 99: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/compiler.vim
100: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/compiler/latexmk.vim
101: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/compiler/_template.vim
102: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/qf.vim
103: /usr/share/nvim/runtime/ftplugin/tex.vim
104: ~/.local/share/nvim/site/pack/packer/start/vimtex/after/ftplugin/tex.vim
105: ~/.local/share/nvim/site/pack/packer/start/vimtex/indent/tex.vim
106: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/delim.vim
107: /usr/share/nvim/runtime/indent/tex.vim
108: ~/.local/share/nvim/site/pack/packer/start/vimtex/syntax/tex.vim
109: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/syntax/core.vim
110: ~/.local/share/nvim/site/pack/packer/start/vimtex/autoload/vimtex/syntax/nested.vim
111: /usr/share/nvim/runtime/syntax/tex.vim
112: ~/.local/share/nvim/site/pack/packer/start/tex-conceal.vim/after/syntax/tex.vim
113: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions.vim
114: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/quickfix.vim
115: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline.vim
116: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/netrw.vim
117: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/fzf.vim
118: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/term.vim
119: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/vimagit.vim
120: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/nvimlsp.vim
121: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/whitespace.vim
122: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/po.vim
123: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/wordcount.vim
124: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/keymap.vim
125: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/vimtex.vim
126: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/searchcount.vim
127: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/section.vim
128: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/highlighter.vim
129: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/themes/dark.vim
130: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/themes.vim
131: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/builder.vim
132: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/wordcount/formatters/default.vim
133: ~/.local/share/nvim/site/pack/packer/start/vim-airline/autoload/airline/extensions/default.vim
134: ~/.local/share/nvim/site/pack/packer/start/deoplete.nvim/autoload/deoplete/util.vim
135: /usr/share/nvim/runtime/autoload/provider/pythonx.vim
136: /usr/share/nvim/runtime/autoload/provider/python3.vim
137: /usr/share/nvim/runtime/autoload/provider.vim
138: ~/.local/share/nvim/site/pack/packer/start/deoplete.nvim/autoload/deoplete/mapping.vim
139: ~/.local/share/nvim/site/pack/packer/start/deoplete.nvim/autoload/deoplete/handler.vim`

**Comment by lervag** [comment]
> > The set conceallevel should be together with your other general settings, and you should notice that it is a window local option (see :help options and for more info - generally, do read the documentation for things)
> 
> this setting actually is global it works fine and if i comment this line out the concealment is gone

No, it is not global. But it _does_ probably work fine. But knowing and understanding that it is not local is smart, because it may help understand when things don't work as you expect.

`:help conceallevel`:

```
                                                *'conceallevel'* *'cole'*
'conceallevel' 'cole'   number  (default 0)
                        local to window
```

> > Run :scriptnames and copy the content to a reply to this thread.
> 
> ```
>   1: /usr/share/nvim/runtime/ftplugin.vim
>   2: /usr/share/nvim/runtime/indent.vim
>   3: /etc/xdg/nvim/sysinit.vim
>   4: /usr/share/nvim/archlinux.vim
>   5: ~/.config/nvim/init.vim
>   6: /usr/share/nvim/runtime/filetype.lua
>   7: ~/.local/share/nvim/site/pack/packer/start/ultisnips/ftdetect/snippets.vim
> ```

Let me stop you there: You showed earlier that you used vim-plug, but this is _clearly_ packer!

Thus, you must have shown me the wrong configuration..?

Also, it seems like VimTeX is loaded as expected. One good way to debug this is to "bisect" your vimrc file. Remove all the stuff that is not relevant and check regularly if things start to work. When you are down to the minimum config for VimTeX things really _should_ work, and if not, then you may have a bug report at the end.

**Comment by lervag** [comment]
Well, in my opinion it has good value to create a reasonably clean configuration. And, at least for some of us, it is good fun. :)

I'm sorry I can't pinpoint your problem more directly, but I hope at least you are able to make a configuration that works and that you are happy with. Feel free to ask questions here if you have some.
