### ISSUE TITLE
Is there a way to keep compiler output window open at all times?

### ISSUE THREAD

**Issue by ElectrifyPro** [lervag/vimtex#2777]
Apologies if this is in the documentation and I did not look hard enough. I've run into a minor issue where I type `begin` (to access the begin environment snippet), activate the snippet, then while I think for a moment for what environment name to type, the compiler error window pops up with the error `Environment env not defined.` and kicks me out of the snippet mode, and back to normal mode. I basically need to type the environment name fast enough to beat the error window popping up!

Is it possible to keep the output window open at all times? Or perhaps change how errors should be displayed?

**Comment by lervag** [comment]
> I've run into a minor issue where I type `begin` (to access the begin environment snippet), activate the snippet, then while I think for a moment for what environment name to type, the compiler error window pops up with the error `Environment env not defined.` and kicks me out of the snippet mode, and back to normal mode.

Huh; are you _saving_ your file in insert mode? VimTeX (or, rather, latexmk) does not compile your file except after you write/save it. Thus, I don't see how this error can appear.

Could you outline the steps you use to reproduce the problem? In detail, so that I can repeat it?

> Is it possible to keep the output window open at all times? Or perhaps change how errors should be displayed?

I guess you can use `let g:vimtex_quickfix_mode = 0`, but I personally don't like that.

**Comment by ElectrifyPro** [comment]
> Huh; are you _saving_ your file in insert mode? VimTeX (or, rather, latexmk) does not compile your file except after you write/save it. Thus, I don't see how this error can appear.

Yeah, this seems a lot weirder now that I think about it. It's probably better demonstrated with a GIF:

![Imgur](https://imgur.com/IOp0fac.gif)

Apparently it seems like my snippet plugin (currently using UltiSnips) actually return to normal mode before putting me into select mode, and I just so happen to have a section in my vim config to automatically save when leaving insert mode...

**Comment by lervag** [comment]
Ok, I see. Well, there is nothing I can do here except perhaps suggesting to add `let g:vimtex_quickfix_mode = 0`. But I think it would be better for you to _not_ autosave after insert mode.

**Comment by ElectrifyPro** [comment]
> Ok, I see. Well, there is nothing I can do here except perhaps suggesting to add `let g:vimtex_quickfix_mode = 0`. But I think it would be better for you to _not_ autosave after insert mode.

That's alright, this solution will actually be fine for me. Thanks!
