### ISSUE TITLE
add_map function is bufferwise

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#279]
As stated by @Konfekt in #277, the `add_map` function in `imaps.vim` is bufferwise. This means it has to be called by an autocmd, and it becomes inconvenient to setup one's own imap.

This should be improved to make it easier to add custom mappings.

**Comment by Konfekt** [comment]
Perhaps best to set up the autocmd's on VimEnter so that`add_map` changes `g:vimtex_imaps_list` before these autocmd's are set up.

**Comment by lervag** [comment]
I'm pushing a solution soon where I keep the same API, i.e., the user should still use the `vimtex#imaps#add_map()`. Instead of actually creating the map, the function now just adds the map to a list, and then all maps are created when a tex file is opened. I just want to test that things work before I push.
