### ISSUE TITLE
Distinguish between "interline formula" and "inline formula"

### ISSUE THREAD

**Issue by yang-datong** [lervag/vimtex#2790]
**Is your feature request related to a problem? Please describe it.**

I'm using snippets, and I want to determine whether my current cursor is in an interline formula or an Inline formula by calling VimTex.

**Describe the solution you'd like**

I know that I can now judge whether I am within the formula by "vimtex#syntax#in_mathzone()", but this is not enough. I need to further determine the type of formula.

**Describe alternatives you've considered**

I simulated this function with some simple programming, but my programming ability is so poor that it doesn't work in some complex scenarios.

**Additional context**

tex.snippets 

```python
def math():
    return vim.eval('vimtex#syntax#in_mathzone()') == '1'


def internel_math():
    if math():
        linebuf = vim.eval("getline('.')")
        index = int(vim.eval("col('.')-1"))
        count_before = linebuf[:index].count('$')
        count_after = linebuf[index:].count('$')
        if (count_after == 0 and count_before == 0):# or (count_after % 2 == 0 and count_before % 2 == 0):
            return False
        return True
    else:
        return False

def display_math():
		return math() and (not internel_math())

#-----------------------------------------------------------------------------------------------------------
context "internel_math()"
snippet // "Fraction" i
\dfrac{$1}{$2}$0
endsnippet

context "display_math()"
snippet // "Fraction" i
\frac{$1}{$2}$0
endsnippet
```

**Comment by lervag** [comment]
> I'm using snippets, and I want to determine whether my current cursor is in an interline formula or an Inline formula by calling VimTex.

Can you give a minimal example document that shows what you mean by interline and inline formulas?
