### ISSUE TITLE
Only compile subfile

### ISSUE THREAD

**Issue by niklaas** [lervag/vimtex#280]
I looked into the docs but haven't found any solution yet: Is there an option to disable compiling the entire project i.e., the main file and just compile the subfile that is open in vim?

**Comment by Konfekt** [comment]
See https://github.com/lervag/vimtex/issues/211

**Comment by niklaas** [comment]
Great, thanks for the reference.

**Comment by lervag** [comment]
Thanks, @Konfekt. I was planning on providing the same reference, but I hadn't gotten around to it yet... :\

**Comment by Eisfreak7** [comment]
It'd be great if it wouldn't be just a "single shot" thing as I understand the other issue but rather an option that also affects the continous mode.

**Comment by lervag** [comment]
I suggest you copy that comment into the other issue with a reference here.

**Comment by lervag** [comment]
See #211 for more info.
