### ISSUE TITLE
Way to disable warning about treesitter

### ISSUE THREAD

**Issue by medwatt** [lervag/vimtex#2801]
Using the default syntax file causes a lot of sluggishness inside neovim, especially when scrolling. The issue doesn't exist with `syntax off` or when using treesitter. I am using treesitter now and I don't seem to be missing anything. However, everytime I open a latex buffer, I get a warning message about treesitter. It seems that you didn't provide any option to set it off. I hope you can allow the user to turn it off.

```
if has('nvim-0.5')
      \ && g:vimtex_syntax_enabled
      \ && !g:vimtex_syntax_conceal_disable
  call timer_start(1000, 'vimtex#nvim#check_treesitter')
endif
```

**Comment by lervag** [comment]
If you prefer to use Treesitter, then you can use `let g:vimtex_syntax_enabled = 0` in your config. Or `vim.g.vimtex_syntax_enabled = 0` if you use Lua. You are staring at the code where this specific option is used... :)

Notice, though, that you probably want to read the docs here. Treesitter syntax highlighing for LaTeX is still not as good as VimTeX's, IMHO. See `:help vimtex-syntax`.

**Comment by medwatt** [comment]
Sorry for that. I probably missed it because of my unfamiliarity with viml.

I checked the doc performing making the post here, but I was searching for "treesitter". I saw the warnings. The problem I have is that scrolling is incredibly sluggish with vim regex. Also, there are too many things highlighted to the point that my latex document looks like a Christmas lantern.
