### ISSUE TITLE
Timer instead of 500m sleep

### ISSUE THREAD

**Issue by chakravala** [lervag/vimtex#2805]
At the end of https://github.com/lervag/vimtex/issues/2802#issuecomment-1747597732 you mentioned I should open a new issue for the following:

One issue I had in the past is that I needed a custom `autoload/vimtex/view/my_zathura.vim` file containing
```
  if g:vimtex_view_automatic
    "
    " Search for existing window created by latexmk
    "   It may be necessary to wait some time before it is opened and
    "   recognized. Sometimes it is very quick, other times it may take
    "   a second. This way, we don't block longer than necessary.
    "
    if !has_key(self, 'started_through_callback') && g:vimtex_view_xwin_exists
      for l:dummy in range(30)
        sleep 50m
        if self.xwin_exists() | break | endif
      endfor
    endif
```
Specifically, I changed 500m to 50m, as half a second was too long. Now this same sleep timer is found here:

https://github.com/lervag/vimtex/blob/a59a49b54ae039f1a439c9a16c2ea7b461b8e925/autoload/vimtex/view/_template.vim#L142

Currently, without changing the `500m` it seems to be fine, but for some reasons in the past I had to change it. If I look at some of my previous issues on here, this comment may have been the original cause https://github.com/lervag/vimtex/issues/1063#issuecomment-369929359 ... however, I don't remember at this point why exactly I changed it from 500 to 50, it may be that the changes to VimTex since then have made this unnecessary, as I did not notice any significant problems right now.

This is not necessarily an issue anymore, but I am sharing this based on the history that I previously had the issue which required customizing the sleep timer; I am not completely sure if it still matters or not.

Lervag has suggested using `timer_start` instead of `sleep`, so perhaps there is yet something to be improved.

**Comment by lervag** [comment]
I believe this is fixed now. Please test.

**Comment by chakravala** [comment]
I believe it works, thank you for your continued efforts on general improvement

**Comment by lervag** [comment]
Great, glad to hear it! :)
