### ISSUE TITLE
Insert mappings ignored in align* environment

### ISSUE THREAD

**Issue by jdagilliland** [lervag/vimtex#281]
The insert mappings are appropriate inside of environments like `align`, or `equation` or `$$`, but inside of starred equivalents like `align*`, `equation*`, insert mappings are not honored. This must boil down to the implementation of `is_math` in `autoload/vimtex/imaps.vim`, but I'm not sure what is the most appropriate way to fix it, since it looks like it goes straight to the syntax matching, which is probably where those environments fail to be recognized.

To simply reproduce this error, go inside
```
\begin{align*}
\end{align*}
```
and type `` `m``.

**Comment by lervag** [comment]
Thanks, there was a problem in the syntax checker. Should work now.

**Comment by jdagilliland** [comment]
Awesome, thanks!

**Comment by lervag** [comment]
No problem :-)

ons. 18. nov. 2015, 21.56 skrev Jason Daniel Augustine Gilliland <
notifications@github.com>:
