### ISSUE TITLE
 build directory latexmk is ignored 

### ISSUE THREAD

**Issue by troyzhu** [lervag/vimtex#2810]
### Description

This is my first time requesting an issue, so please bear of me if any of my formatting is not correct, and I will update them accordingly. In summary, my latexmk compiling seems to be ignoring the "build_dir", and compile only to the current directory instead.  

System: Mac Os 13.5.2 (22G91)
Shell: Bash 
Vim: not Neovim
pdfviewr: Zathura 

Based on viminfo, I think it's an interface issue as latexmk has no outputdir, and  I can get the compiler to work appropriately by using: 

let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \   '-outdir=latexbuild',
    \ ]
    \}

instead, but this break my forward-backward search interface wiith Zathura. 

### Steps to reproduce

minimal .vimrc set up: 

call plug#begin('~/.vim/plugged')

Plug 'lervag/vimtex'
    let g:tex_flavor='latex'
    let g:vimtex_compiler_latexmk = {
    \ 'build_dir' : 'latexbuild',
    \}
    let g:vimtex_view_method='zathura'
    let g:vimtex_quickfix_mode=0

call plug#end()

### Expected behavior

The compiler outputs all the compiling file under latexbuild/ directory.

### Actual behavior

The compiler outputs all the compiling file under current directory instead. 

### Do you use a latexmkrc file?

No 

### VimtexInfo

```yaml
compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
```

**Comment by troyzhu** [comment]
Never mind it looks like it's due to in the new update the correct argument is now 'outputdir' per https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#1016. 

For people run into similar issues, the correct configuration is now:

let g:vimtex_compiler_latexmk = {
    \ 'out_dir' : 'latexbuild',
    \}

**Comment by lervag** [comment]
Glad to see you figured it out! :)
