### ISSUE TITLE
Automatically insert item in list contexts

### ISSUE THREAD

**Issue by kflak** [lervag/vimtex#2811]
Hi, and thanks for a _brilliant_ plugin. I was wondering if it's possible to automatically insert a new list item in f.x. an enum list. so that I don't have to type `\item` every time? In `Neorg` this is mapped to `M-CR` by default.

**Comment by lervag** [comment]
> Hi, and thanks for a _brilliant_ plugin.

<3

> I was wondering if it's possible to automatically insert a new list item in f.x. an enum list. so that I don't have to type `\item` every time? In `Neorg` this is mapped to `M-CR` by default.

Yes. There are several ways to do it:

* Use the built-in imap feature, see `:help vimtex-imaps`. E.g., you can do this:

    ```vim
    let g:vimtex_imaps_list = [
          \  {
          \    'lhs': 'ii',
          \    'rhs': '\\item ',
          \    'leader': '',
          \    'wrapper': 'vimtex#imaps#wrap_environment',
          \    'context': ['itemize', 'enumerate', 'description'],
          \  },
          \]
    ```

    Or with Lua:

    ```lua
    vim.g.vimtex_imaps_list = {
      {
        lhs = "ii",
        rhs = "\\item ",
        leader = "",
        wrapper = "vimtex#imaps#wrap_environment",
        context = { "itemize", "enumerate", "description" },
      },
    }
    ```

* Use a regular Snippet engine, such as UltiSnips (see the specific engines documentation for more info).

**Comment by kflak** [comment]
Thanks, the `vimtex-imaps` feature looks very promising. I guess I'll stick with my snippet plugin for now (luasnip). The main point I'm looking for is something that will take whatever kind of item I'm currently in and starting the next line insert with the same kind. But snippets work just fine for my purposes as a casual, occasional latex user.

**Comment by lervag** [comment]
> Thanks, the `vimtex-imaps` feature looks very promising. I guess I'll stick with my snippet plugin for now (luasnip).

Just to be clear: the `vimtex-imaps` feature is really only a "poor man's" snippet implementation. It does work quite well and there are a lot of built-in shortcuts that can be useful. It is also easy to make new/other "imaps".

But for anything that is not trivial, you should turn to a real snippet plugin.

> The main point I'm looking for is something that will take whatever kind of item I'm currently in and starting the next line insert with the same kind. But snippets work just fine for my purposes as a casual, occasional latex user.

Cool. Something like this, then?

```vim
inoremap RHS <cr>\item 
```

where `RHS` is what you want to use as the right-hand side, i.e. the keys you want to type to expand? You can easily add mappings like that in your `~/.config/nvim/ftplugin/tex.vim` - or `~/.vim/ftplugin/tex.vim` if you use Vim. If you are on Windows, then the paths are somewhat different and you can find the relevant locations with `:help VIMRC` or `:help MYVIMRC`.
