### ISSUE TITLE
Equation autocompletion

### ISSUE THREAD

**Issue by ronakmsoni** [lervag/vimtex#2812]
**A clear and short description of what the problem is.**

`CTRL-X-CTRL-P` is an amazingly powerful auto-completion mode in vim; hitting it once completes a single word and hitting it again adds the next word on and on.

For example, if you want to write
```
This is a sentence.

That is a sentence.
```
You can write
```
This is a sentence.

That
```
and hit `CTRL-X X CTRL-P CTRL-P CTRL-P` you get the rest of the sentence word by word.

This is potentially very useful for latex, because you often want to write _almost_  the same equation many times.

However, vim doesn't recognise the characters `\,{,},(,),-,+` --- all of which appear in equation atoms --- as part of a word and so this feature doesn't work for equations out of the box.

**Describe the solution you'd like**

A single line change in autoload/vimtex.vim.

Currently it says
`set iskyword+=:`
Modify it to
`set iskeyword+=:,\\,{,},(,),-,+,[,]`
and we're good to go.

Also maybe a couple of lines in the doc to tell users this is possible.

The above line is in my personal `ftplugin/tex.vim`, but it seemed like this would be a simple enough and universally useful enough change to include in the plugin proper, if others here agree.

**Describe alternatives you've considered**
Close this issue and future users can find the line to put in their personal configs in searches.

**Comment by ronakmsoni** [comment]
Sorry I just realised that the inclusion of `{,}` breaks folding by expr. Is there a way to have both expression folding and the auto-completion from above?

**Comment by ronakmsoni** [comment]
This has a different use-case than snippets. For example, if I'm doing a derivation I'd like to automatically copy all the terms I'm not changing in a given manipulation.
This is not worth writing a snippet for, since I'm going to be carrying forward each term 2-5 times total.

Anyway my current solution is
```
imap <C-S-x> <c-o>:set iskeyword+=\\,(,),[,],{,},^,-,+<CR><C-x>
au CompleteDone * set iskeyword-=\\,(,),[,],{,},^,-,+
```

This is of course a bad idea for large projects, but it seems to work fine for a 50-page pdf.

Another option is to change `iskeyword` when entering and leaving insert mode. Might work better for large files. though I don't have any project more than ~50 pages to test.

**Comment by lervag** [comment]
Your solution looks quite good, I think. I don't think you will get any change in performance if you use autocommand to change when leaving/entering insert mode, though.

**Comment by ronakmsoni** [comment]
Why would there not be a difference in speed, if I may ask? I was worried that vim would freeze up trying to re-index the open files. Is this algorithm fast enough for it not to matter? (I am not very experienced at vimscript, or programming, to be clear.)

**Comment by lervag** [comment]
> Why would there not be a difference in speed, if I may ask? I was worried that vim would freeze up trying to re-index the open files. Is this algorithm fast enough for it not to matter? (I am not very experienced at vimscript, or programming, to be clear.)

If I understood correctly, you are asking if the following alternative 1 would be more performant than alternative 2. Am I right?

1. "current solution"

    ```vim
    imap <C-S-x> <c-o>:set iskeyword+=\\,(,),[,],{,},^,-,+<CR><C-x>
    au CompleteDone * set iskeyword-=\\,(,),[,],{,},^,-,+
    ```

2. changing `iskeyword` when entering/leaving insert mode (something like this):

    ```vim
    autocommand InsertEnter *.tex set iskeyword+=\\,(,),[,],{,},^,-,+
    autocommand InsertLeave *.tex set iskeyword-=\\,(,),[,],{,},^,-,+
    ```

I would think these are more or less equivalent wrt. completion, except the latter will change the keyword completion "generally", whereas your current solution only changes it while running your mapping.

I don't know if changing `iskeyword` will lead to any noticable delays, but I would not really expect it. Perhaps it will for huge documents, but I would advice to not worry until you actually notice the delay directly.

**Comment by ronakmsoni** [comment]
Yeah this is what I was asking, thanks!
