### ISSUE TITLE
Is there an easy way to yank the tag in ToC view?

### ISSUE THREAD

**Issue by ThSGM** [lervag/vimtex#2815]
### Description

I'd like to hover over the relevant entries in the ToC corresponding to labels and then yank the label key. Can this be easily done with a shortcut? 

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
N/A
```

**Comment by lervag** [comment]
> I'd like to hover over the relevant entries in the ToC corresponding to labels and then yank the label key. Can this be easily done with a shortcut?

To be honest, I'm not sure what you mean. First, what is "hover" here? Do you mean with your mouse?

Perhaps you could create a mapping within `vimtex-toc` filetypes? Labeled stuff typically has as its text only the label, right? So, you could just copy that. Something like this:

```vim
autocmd FileType vimtex-toc nnoremap 02Wvt(by
```

You may want to experiment with this. The idea is:

```
0                         go to beginning of line
 2W                       jump two WORDS to get to start of label
   vt(                    enter visual mode and move to the paranthesis
      b                   go back to last character of the label
       y                  yank selected text
```

**Comment by lervag** [comment]
Closing as resolved by the previous comment.
