### ISSUE TITLE
Error when opening any latex file on neovim related to amsmath

### ISSUE THREAD

**Issue by ludovicschwartz** [lervag/vimtex#2821]
### Description

I just installed vimtex for the first time using vimplug and neovim

Minimal tex file(It does the error on any tex file):

Minimal.vim :

```vim
set number relativenumber
set clipboard+=unnamedplus
set nocompatible
call plug#begin()
Plug 'Sirver/ultisnips'
Plug 'https://github.com/lambdalisue/suda.vim'
Plug 'honza/vim-snippets'
Plug 'lervag/vimtex'
call plug#end()

let g:UltiSnipsExpandTrigger='<tab>'
let g:UltiSnipsJumpForwardTrigger='jk'
let g:UltiSnipsJumpBackwardTrigger='<S-Tab>'
let g:UltiSnipsSnippetDirectories=[$HOME.'/.config/nvim/UltiSnips',"UltiSnips"]
```

### Steps to reproduce

1. `nvim -u minimal.vim minimal.tex`

### Expected behavior

The file opening in nvim

### Actual behavior

I get the following error

```
Error detected while processing function vimtex#syntax#core#init_post[12]..vimtex#syntax#packages#init[14]..vimtex#syntax#p#amsmath#load:
line   10:
E121: Undefined variable: #
E116: Invalid arguments for function vimtex#syntax#core#new_env
Press ENTER or type command to continue

```

I couldn't find an issue on this error after a google search with the error.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
  1   OS: Ubuntu 20.04.3 LTS
  2   Vim version: NVIM v0.4.3
  3   Has clientserver: true
  4   Servername: /tmp/nvimixhdIF/0
  5 
  6 VimTeX project: test
  7   base: test.tex
  8   root: /home/user/Test_Vimtex
  9   tex: /home/user/Test_Vimtex/test.tex
 10   main parser: fallback current file
 11   document class: 
 12   compiler: latexmk
 13     engine: -pdf
 14     options:
 15       -verbose
 16       -file-line-error
 17       -synctex=1
 18       -interaction=nonstopmode
 19     callback: 1
 20     continuous: 1
 21     executable: latexmk
 22   viewer: General
 23   qf method: LaTeX logfile
```

**Comment by lervag** [comment]
The problem is that you are using Neovim v 0.4.3. I know it says it is supported, but I'm about to bump the version requirement to version 0.9. You _really_ should update your neovim version. 0.4.3 is _ancient_ and there is no good reason to not update to at least version 0.9.

To be clear: I've ended up using a syntax that is not supported by Neovim 0.4.3, which is why you get this error. But I don't want to fix it. Sorry.

**Comment by lervag** [comment]
Glad to help :)
