### ISSUE TITLE
Boken link in documentation

### ISSUE THREAD

**Issue by GTP95** [lervag/vimtex#2822]
### Description

In the help section about autocompletion, you will find this:
```
VimCompletesMe
                                                          vimtex-complete-vcm
A plugin that maps <tab> to trigger the built-in completion that is most
suitable to the current context.  The plugin is available here:
https://github.com/ajh17/VimCompletesMe.
```
But the given link is broken. I think it has been moved to https://git.sr.ht/~ackyshake/VimCompletesMe.vim.

### Steps to reproduce

1. Open the relevant help section: `:h vimtex-complete-auto`
2. Read the paragraph about VimCompletesMe

### Expected behavior

The link gets me to VimCompletesMe's repository.

### Actual behavior

404 error

### Do you use a latexmkrc file?

Not applicable

### VimtexInfo

```yaml
Not applicable
```

**Comment by lervag** [comment]
Thanks!
