### ISSUE TITLE
Telescope or similar preview window for referencing/fuzzy finding references

### ISSUE THREAD

**Issue by ThSGM** [lervag/vimtex#2826]
Recently there has been a really significant quality-of-life functionality with the help of @micangl which is the development of the [cmp-vimtex](https://github.com/micangl/cmp-vimtex) plugin, which allows for fuzzy finding of latex references like citations and equations. For me, this has been absolutely essential, so I am eager to see how the plugin develops (and also considerations of direct implementation into vimtex evolves). 

I am wondering if it is possible to develop a Telescope-like plugin where you can fuzzy find on labels, but allowing you to preview where the label of such a reference appears. 

For example, suppose that my equation is referenced via \label{eq:bigresult}. I would like to press shortcut, pop up a Telescope window, then type 'big' and immediately get a preview of the text where the relevant label appears. Alternatively I can scroll through possible entries and select whichever one is appropriate. 

- Another Reddit user asked a similar question about a year ago: https://www.reddit.com/r/neovim/comments/14aj2az/telescope_latex_labels/
- A Telescope plugin for parsing your bibtex file is [telescope-bibtex.nvim](https://github.com/nvim-telescope/telescope-bibtex.nvim).

**Comment by lervag** [comment]
ghe closest currently available feature would be the table of contents, which can give functionality close to what you are asking for. You can create custom table of contents, e.g. one that only shows the labels.

E.g., if you add this to your `after/ftplugin/tex.vim` file:

```vim
let g:__vimtex_toc_labels = vimtex#toc#new({
    \ 'name' : 'VimTeX Labels',
    \ 'layers' : ['label'],
    \ 'show_help' : 0,
    \ 'show_numbers' : 0,
    \})
nnoremap <silent> \ly :call g:__vimtex_toc_labels.open()<cr>
```

Now you can use `\ly` to open a dedicated toc with only labels. It does not give the preview feature, though, and it is not quite the same as the Telescope selector (you could say it is far from it).

However, it should be quite easy to write a telescope source by use of the same backend. This is close to what we already do for the fzf picker:
https://github.com/lervag/vimtex/blob/master/autoload/vimtex/fzf.vim

This is about 100 lines of code, much of which is not so relevant (theres a lot of formatting and stuff). Now, I don't really need this feature myself, and I'm not an expert at writing Telescope sources. I would not mind helping, but I would be glad if someone else took lead on writing the Telescope picker. If someone did, I would be glad to consider and help out with a PR.

**Comment by tienlonghungson** [comment]
Hi @lervag , thank you for a wonderful plugin.
I have managed to add the table of content as a source for Snacks.nvim. Here is my config:
In `nvim/after/ftplugin/tex.lua`
```lua
vim.keymap.set("n", "<localleader>lA", function()
  -- Check if vimtex is available
  if vim.fn.exists("*vimtex#parser#toc") == 0 then
    vim.notify("VimTeX TOC parser not available", vim.log.levels.ERROR)
    return
  end

  local function format_number(n)
    local num = {
      n.chapter ~= 0 and n.chapter or nil,
      n.section ~= 0 and n.section or nil,
      n.subsection ~= 0 and n.subsection or nil,
      n.subsubsection ~= 0 and n.subsubsection or nil,
      n.subsubsubsection ~= 0 and n.subsubsubsection or nil,
    }
    num = vim.tbl_filter(function(t)
      return t ~= nil
    end, num)
    if vim.tbl_isempty(num) then
      return ""
    end
    -- Convert appendix items numbers to letters (e.g. 1 -> A, 2 -> B)
    if n.appendix ~= 0 then
      num[1] = string.char(num[1] + 64)
    end
    num = vim.tbl_map(function(t)
      return string.format(t)
    end, num)
    return table.concat(num, ".")
  end

  local entries = vim.fn["vimtex#parser#toc"]()
  local layers = "ctli" -- content, todos, labels, includes

  -- Filter entries by layers
  entries = vim.tbl_filter(function(t)
    return string.find(layers, t.type:sub(1, 1)) ~= nil
  end, entries)

  -- Format entries for snacks.nvim picker
  local items = vim.tbl_map(function(v)
    local section_num = format_number(v.number)
    local display = section_num ~= "" and (section_num .. " " .. v.title) or v.title

    return {
      text = display,
      file = v.file,
      pos = { v.line or 1, 0 },
      type = v.type,
    }
  end, entries)

  Snacks.picker.pick({
    source = "vimtex_toc",
    items = items,
    format = "text",
    layout = {
      preset = "ivy",
    },
-- preset = function()
--       return vim.o.columns >= 120 and "default" or "vertical"
--     end,
    preview = function(ctx)
      if ctx.item.file then
        Snacks.picker.preview.file(ctx)
      else
        ctx.preview:reset()
        ctx.preview:set_title("No preview")
      end
    end,
    confirm = function(picker, item)
      picker:close()
      -- Navigate to the selected TOC entry
      vim.cmd.edit(item.file)
      vim.api.nvim_win_set_cursor(0, item.pos)
      vim.cmd.normal("zz") -- Center the cursor
    end,
  })
end, { desc = "VimTeX Sn(A)ck Table of Contents" , buffer = true })
```
I believe this can be adapted to the source of vimtex

**Comment by tienlonghungson** [comment]
@lervag it works. There is one typo issue in the doc though. If you look at
 ``` markdown
To use it, define a mapping to `require("vimtex.snacks").toc(options)`, e.g. >lua

  vim.keymap.set("n", "<localleader>lt", function()
    return require("vimtex.snacks").run()
  end)
```

It should be
```lua
return require("vimtex.snacks").toc()
```
not `run()`.
