### ISSUE TITLE
Customize SyncTeX inverse search command

### ISSUE THREAD

**Issue by ravibrock** [lervag/vimtex#2827]
Hello - I'm sorry if this is somewhere in the docs, but I was trying to customize the SyncTeX inverse search command to automatically return focus to iTerm after triggering inverse search in Sioyek, but I couldn't figure out any way to modify the command. The method I had figured out, at least, was to run a custom AppleScript command after the inverse search command:

`osascript -e 'activate application "iTerm"' && nvim --headless -c "VimtexInverseSearch %l '%f'"`

It's probably clear from the command, but the `osascript` just runs a line of AppleScript telling MacOS to return focus to iTerm2. This command works, but I was unable to make VimTeX send it to Sioyek. I might be able to find a workaround if there's no other option, but it would be much simpler/more elegant if there is a way to configure this natively. Thank you!

Apologies for not using the issue template by the way - I wasn't sure which category this would fall into since it's not really a bug, but I'm not sure it's an enhancement either if there's already some way to customize it.

**Comment by ravibrock** [comment]
That works perfectly. Thank you!

**Comment by lervag** [comment]
Cool, glad to hear it!
