### ISSUE TITLE
Regarding Vim9 and Lua in vimtex

### ISSUE THREAD

**Issue by ykonstant1** [lervag/vimtex#2828]
This is more a question than a request: vimtex is currently written primarily in vimscript; has Karl thought about moving parts of development to Vim9 or Lua?  I am asking because Lua has first class support in neovim, and I have heard that Vim9 is a much better language than vimscript for vanilla Vim.  I'd like to know the author's thoughts about these languages, problems regarding legacy support etc.

In any case, keep being awesome and blessing us with this amazing plugin :)

**Comment by lervag** [comment]
> This is more a question than a request: vimtex is currently written primarily in vimscript; has Karl thought about moving parts of development to Vim9 or Lua?

Yes, he has. I use neovim, and I don't see any good reason to move anything to Vim 9. I've already started to build some functionality with Lua, and I believe, if anything, I will continue in this direction.

I don't plan to make any huge breaking changes in the near feature. That is, I will continue to maintain VimTeX mostly based on the common Vimscript. In the next release, I will bump version requirements to the latest versions of both Vim and neovim and I plan to make some general improvements and simplifications based on the updates to the common Vimscript language.

In a few years, I do think it is likely that I drop Vim support. But if I do, there will be a final version that should work well with Vim that anyone would be fully free to fork.

> In any case, keep being awesome and blessing us with this amazing plugin :)

Thanks! :)
