### ISSUE TITLE
fatal: Could not read from remote repository.

### ISSUE THREAD

**Issue by loftyyyy** [lervag/vimtex#2829]
### Description

git clone https://github.com/lervag/vimtex.git
Cloning into 'vimtex'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

### Steps to reproduce

git clone https://github.com/lervag/vimtex.git

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
None
```

**Comment by lervag** [comment]
Did you figure it out?

I'm not quite sure what's going on here, but my first guess is that you have some strange ssh config or gitconfig.
