### ISSUE TITLE
untangle fold setup

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#283]
To use vimtex expression folding ideally
```vim
setlocal fdm=expr
setlocal foldexpr=vimtex#fold#level(v:lnum)
```
should suffice. 

However`vimtex#fold#level(v:lnum)` needs `g:vimtex_fold_enabled=1` since only then
```vim
    g:vimtex_fold_preamble, b:vimtex_fold_parts, g:vimtex_fold_envs.
```
are defined. However, `g:vimtex_fold_enabled=1` also overwrites `foldtext` and sets up `autocmd`s.

So how about defining 
```vim
    g:vimtex_fold_preamble, b:vimtex_fold_parts, g:vimtex_fold_envs.
```
always (and documenting the value of `foldexpr`)? 

Then `g:vimtex_fold_enabled` sets up
```vim
  setlocal foldmethod=expr
  setlocal foldexpr=vimtex#fold#level(v:lnum)
  setlocal foldtext=vimtex#fold#text()
```
Also, instead of the many autocmd's, even on `CursorMove` how about simply using https://github.com/Konfekt/FastFold using less frequent autocmd's ?

**Comment by lervag** [comment]
I agree the folding options are a little bit too complex. Personally, I use the default options, which I think is similar to how FastFold functions. With `g:vimtex_fold_automatic`, we keep the `foldmethod=expr`, but toggles it when entering insert mode.

The manual (and default) mode uses a self destructive autocommand in order to update the folds when a file is loaded. Else there are no autocommands involved.

I'm a bit reluctant to make vimtex fully dependent on FastFold. However, I think I could consider to remove the automatic mode, and instead make this a "clean" `expr` mode.

Regarding the other part, I agree: the options should be defined also when the folding is disabled.

**Comment by Konfekt** [comment]
Yeah, that's a fine solution, The automatic mode should do what proposed on top of the inital post; then FastFold can tap into it.

The non-automatic mode can continue working as before. 

Note that defering the fold update to the leave of insert mode caused a pause over here too, but that's probably due to concealing and  not so noticeable otherwise. 

It's fine as it is, but might give it a try with, that is,compare to automatic mode with FastFold.

**Comment by Konfekt** [comment]
To clarify, automatic mode means clean mode.

**Comment by lervag** [comment]
TODOs:

- [ ]: Consider to remove the automatic fold option (or improve the documentation for it) -- a good case against this option is that there are plugins that solve the problem much better than the way done in vimtex... vimtex should keep simple and not reimplement existing solutions.
- [ ]: Allow a fully clean fold option, i.e., an option that does NOTHING more than set `foldexpr`, `foldtext` and `foldmethod`.

Am I missing something here, @Konfekt?

**Comment by Konfekt** [comment]
Yep, :+1: for removing the automatic option and a fully clean fold option, for example FastFold now works fine with the sole `setlocal foldexpr fdm=expr`.

Regarding foldtext, for example https://github.com/Konfekt/FoldText indents according to the fold level, which helps orient oneself. Then refer to the `autocmd User VimtexInit ..` to restore it. Or document the setup as in https://github.com/lervag/vimtex/pull/284 for fine-grained control, to change only `fdm foldexpr` but keeping `foldtext` beforehand.

**Comment by lervag** [comment]
I think the recent updates should satisfy you. Could you please read the updated documentation and check if it works for you?

I might consider to set the manual mode to disabled by default. It is currently enabled by default.

**Comment by Konfekt** [comment]
Ok, looking good. Fine for me. About disabling manual by default and using other plugins, I'm too prejudiced to decide. But yeah, better keep it manual by default because otherwise it is simply to slow, especially with conceallevel > 0.

**Comment by lervag** [comment]
That was my thinking as well. I'll close this, then.

**Comment by Konfekt** [comment]
One afterthought: With automatic folding the slowdown is evident and once fixed  you know that `zx` updates the folds, whereas with manual folding that folds are only updated hitting `zx` is harder to hit on.

**Comment by lervag** [comment]
I have no idea what you just said... could you please explain what you mean?

**Comment by lervag** [comment]
I actually change things slightly: One no longer needs to do `zx` to update the calculated fold levels. Thus the remapping of `zx` is now only relevant for the manual mode, where it is required in order to do the recalculation trick. That is, for manual mode, `zx` now does:

```vimL
setlocal fdm=expr
normal! zx
setlocal fdm=manual
```

**Comment by Konfekt** [comment]
Suppose manual folds are off: As a new Vimtex user, seeing that folds are slow, you read about manual folds and consciously use `zx`, knowing that folds only update by `zx`.
Suppose manual folds are on by default: As a new Vimtex user, sometimes you wonder why folds are off, until learning about refreshing them by `zx`. 

I thought perhaps the latter problem will take more time to observe and formulate, and so look up, for a new user.

**Comment by lervag** [comment]
Thanks for the clarification. I actually think it is a good point. And combined with the KISS philosophy, I actually think I want to make manual mode optional, instead of default.

I appreciate your effort in writing about issues and suggesting improvements to vimtex! Thanks!

**Comment by lervag** [comment]
Btw: I'm currently testing your FastFold plugin. If I like it, I might stick with it. I do like the idea of solving the speed problem for all syntax/expr fold methods, regardless of filetype.

**Comment by Konfekt** [comment]
Oh, thank you very much. It's just that I use vimtex so much and like things to be thought through. And spent too much time taming Vim.

**Comment by lervag** [comment]
> ... spent too much time taming Vim.

Haha, same here. Probably the Stockholm syndrome, but today I actually enjoy programming in VimL. :)

**Comment by Konfekt** [comment]
Stockholm syndrome or Sunk Cost Fallacy would be another charming take on explaining this devotion.

**Comment by nasenatmer** [comment]
Hey guys, this has been a bit too much going to and fro, so I'd rather ask to find out about the optimal set up rather than to die stupid:

I installed **FastFold** now and have the following settings in `~/.vimrc` and would like to know whether this is the optimal setup I can get or I misunderstood something:

```vim
" Enable FastFold for tex files
        let g:tex_fold_enabled=1

" Enable folding in vimtex
        let g:vimtex_fold_enabled = 1
```

If understand the configuration correctly, `fold-expr` is slow while `fold-manual` is cumbersome. But using `fold-expr` in combination with `FastFold` is fast and easy?

**Comment by Konfekt** [comment]
Ah, let g:tex_fold_enabled=1 enables tje standard syntax folding which is overridden by vimtex expression folding. Just the second line, enabling vimtex expression folding, and installing FastFold without further setup is all there is to it.

**Comment by Konfekt** [comment]
...  where standard syntax folding means that built into Vim.

**Comment by nasenatmer** [comment]
Cool, thanks for your reply and for FastFold!

**Comment by lervag** [comment]
@nasenatmer As already clarified, `g:tex_fold_enabled` is not part of vimtex. It is part of the syntax plugin built into Vim, which provides syntax based folding.

The updates to the folding functionality in vimtex is really mostly a simplification. First, it redefines the default folding to simply use `fold-expr` folding with no more complexities. It provides an option to utilize `fold-manual` to speed things up. IMHO, this is not really cumbersome. But I do agree with @Konfekt that this same approach can be generalized, and that is exactly what FastFold does. Thus, it becomes a sensible setting to use the common `fold-expr` setting (i.e. the default fold setting) combined with FastFold.

I hope this clarifies somewhat.

**Comment by nasenatmer** [comment]
Got it, thanks for your explanation and continuous work on `vimtex` :+1:
