### ISSUE TITLE
latexmain specifier does not work unless the mainfile includes the current file?

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2831]
### Description

When I try to use .latexmain file as mentioned in "File .latexmain specifier" section of the documentation, 

* if the corresponding mainfile.tex includes the current file, that file is correctly detected.
* otherwise, it will not be detected.

This is according to the behavior in the source code:

https://github.com/lervag/vimtex/blob/a630f0f75d9468d10c9125f2f1b0049e479c2f54/autoload/vimtex/state.vim#L359

The corresponding documentation:

https://github.com/lervag/vimtex/blob/a630f0f75d9468d10c9125f2f1b0049e479c2f54/doc/vimtex.txt#L431

I think this is mostly a documentation bug (nevertheless, would it be preferable to edit the source code instead to use that file as main regardless?)

**Comment by lervag** [comment]
If the file is not included, then how can we claim that the specified mainfile is really a main file? I find the current behaviour to make a lot of sense, so if anything, I would prefer to update the docs.

**Comment by user202729** [comment]
Also fine by me. (it may also be preferable to send a warning message inform the user that latexmain configuration is ignored.)

**Comment by lervag** [comment]
I believe I answered hastily. The `.latexmain` has a special behaviour in that it is used as a fallback. I.e., consider this:

```sh
touch test.tex
touch main.tex
touch main.tex.latexmain
nvim test.tex
```

Doing the above, then `:VimtexInfo`, yields:

```
VimTeX project: main
  base: main.tex
  root: /home/lervag/test
  tex: /home/lervag/test/main.tex
  main parser: fallback
```

Notice that it finds `main.tex` as the main file even if it does not include `test.tex`, and that the main parser is specified to be "fallback".

**Comment by user202729** [comment]
Yes, but if there are two candidate main files `main1.tex` and `main2.tex`, `main1.tex` exists and include the current file, but `main2.tex.latexmain` exist, then `main1.tex` will be used without any warning that the latexmain file is ignored.

(Actual use case: the [Napkin](https://github.com/vEnhance/napkin) compiles really slowly, so I [use a trick to copy the generated PDF file to a backup after each compilation pass](https://tex.stackexchange.com/a/701422/250119), but I also want the forward/reverse search in vimtex to work and use the "Napkin-backup.pdf" file.)

**Comment by lervag** [comment]
> Yes, but if there are two candidate main files `main1.tex` and `main2.tex`, `main1.tex` exists and include the current file, but `main2.tex.latexmain` exist, then `main1.tex` will be used without any warning that the latexmain file is ignored.

Hmm, ok. Perhaps I'll add a warning in this case, then. I agree it can be considered confusing, although I still think the current actual behaviour is correct.
