### ISSUE TITLE
Is it possible to use multiple characters as concealchar?

### ISSUE THREAD

**Issue by dirichy** [lervag/vimtex#2833]
Sometimes i can’t find suitable character as concealchar, so is there a way to use multiple char or it’s too difficult to do? 
For example, if i want \longrightarrow can be concealed into ‘———>’. 
Thank you!

**Comment by lervag** [comment]
go, sorry; The syntax feature in Vim does not allow that in general.

However, it is possible to "hack" this. It becomes weird and error prone, but might work. E.g.:

```vim
syntax match texCmdArrowConcelead "\\longrighta\zerrow"
      \ conceal
      \ nextgroup=texCmdArrowConceleadA
syntax match texCmdArrowConceleadA "r"
      \ conceal
      \ cchar=-
      \ nextgroup=texCmdArrowConceleadB
syntax match texCmdArrowConceleadB "r"
      \ conceal
      \ cchar=-
      \ nextgroup=texCmdArrowConceleadC
syntax match texCmdArrowConceleadC "o"
      \ conceal
      \ cchar=-
      \ nextgroup=texCmdArrowConceleadD
syntax match texCmdArrowConceleadD "w"
      \ conceal
      \ cchar=>
```

The idea here is to first match the command, but stop before the last characters. Conceal the command in full. Then for each following character you conceal one at a time.

You can put things like this in your personal `~/.config/nvim/after/syntax/tex.vim` file (or `~/.vim/after/...` for Vim).

**Comment by dirichy** [comment]
thank you very much!

**Comment by lervag** [comment]
Glad to help!
