### ISSUE TITLE
Vimtex loading in Neovim but none of the features work

### ISSUE THREAD

**Issue by jwbullard** [lervag/vimtex#2841]
### Description

Using nvim v0.9.4 on Mac OS Sonoma 14.1.1, I have my vimtex.lua file attached.
<img width="966" alt="Screenshot 2023-11-29 at 3 53 08 PM" src="https://github.com/lervag/vimtex/assets/62448796/b8f0e013-b837-4a57-bb39-99860635e218">

Opening up nvim, I run :checkhealth and get this output for vimtex:

<img width="409" alt="Screenshot 2023-11-29 at 3 54 41 PM" src="https://github.com/lervag/vimtex/assets/62448796/01b91430-394a-4124-b0af-6080f441d734">

If I open up a LaTeX file, I can view the vimtex documentation with :h vimtex

Running  :VimtexInfo on an open LaTeX file is successfull.  See output below.

<img width="859" alt="Screenshot 2023-11-29 at 3 57 24 PM" src="https://github.com/lervag/vimtex/assets/62448796/c20a37be-18c1-43a2-bfb6-e4e2e82747e5">

However, none of the expected vimtex features work within that LaTeX file.  This includes:

- none of the default mappings are recognized.
- none of the environment completion features are triggered.

### Expected behavior

Default mappings (or any mappings) should work
Environment completion should work, reference completion should work, etc.

### Actual behavior

None of the default mappings are recognized.  For example, if I type \ll, the cursor just moves two steps to the right.

Environment completion is not happening, reference completion suggestions are not happening ...

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
System info:
    1   OS: macOS 14.1.1 (23B81)
    2   Vim version: NVIM v0.9.4
    3   Has clientserver: true
    4   Servername: /var/folders/bx/n7fymkfd381363ckznhh8fp40000gr/T/nvim.jwbullard/mQ5bcZ/nvim.595.0
    5
    6 VimTeX project: test
    7   base: test.tex
    8   root: /Users/jwbullard/scratch
    9   tex: /Users/jwbullard/scratch/test.tex
   10   main parser: current file verified
   11   document class: article
   12   packages: fontaxes fontenc ifluatex iftex ifxetex libertine mweights textcomp xkeyval
   13   compiler: latexmk
   14     engine: -pdf
   15     options:
   16       -verbose
   17       -file-line-error
   18       -synctex=1
   19       -interaction=nonstopmode
   20     callback: 1
   21     continuous: 1
   22     executable: latexmk
   23   viewer: Skim
   24   qf method: LaTeX logfile
```

**Comment by ejmastnak** [comment]
> Expected behavior
> 
> Default mappings (or any mappings) should work
> Environment completion should work, reference completion should work, etc.
>
> Actual behavior
> None of the default mappings are recognized. For example, if I type \ll, the cursor just moves two steps to the right.

I can't speak for completion, but regarding default mappings, any chance that this is because you have set `vimtex_mappings_enabled = 0` in your `vimtex.lua`? It might be worth checking both:
1. If `:VimtexCompile` works (which is what `\ll` calls under the hood)
2. If default mappings work after removing `vimtex_mappings_enabled = 0` from your `vimtex.lua`

**Comment by lervag** [comment]
@ejmastnak is spot on regarding your first issue. Regarding completion: Are you using any autocomplete plugins? If so, which one? Please see `:help vimtex-complete-auto`, it might be sufficient to help you here.

Here is your configuration, simplified. I've removed unnecessary options and improved the syntax. Feel free to add your comments again. I also removed the `vim.g.vimtex_mappings_enabled` option, as it seems you want the default mappings _enabled_.

```lua
vim.g.vimtex_view_method = 'skim'
vim.g.vimtex_quickfix_mode = 0
vim.g.vimtex_indent_enabled = 0
vim.g.vimtex_log_ignore = {
  'Underfull’,
  'Overfull',
  'specifier changed t',
  'Token not allowed in a PDF string',
}
vim.g.vimtex_complete_close_braces = 1
```

**Comment by jwbullard** [comment]
That was exactly the problem.  I am grateful for people like you who take the time to patiently explain these things to a newbie like me.
