### ISSUE TITLE
Inlay hints for figure/section numbers

### ISSUE THREAD

**Issue by PurpleMyst** [lervag/vimtex#2848]
**Is your feature request related to a problem? Please describe it.**
My problem is having to open the ToC to look at section/figure numbers instead of being able to see them at a glance.

**Describe the solution you'd like**
I'd like to see those numbers as an inlay hint, like the latest Neovim versions support.

**Describe alternatives you've considered**
Just using the ToC.

**Comment by lervag** [comment]
Just curious, why would you want to see these at a glance? This does not really feel like an important feature to me. Section and figure numbers are important when reading the document. When I write, I only need section and figure _labels_.

**Comment by PurpleMyst** [comment]
It just saves me a bit of mental math and/or time when receiving feedback from others. As an example, I got feedback on a recent collaborative document that went something like:
* Figure `A.60`: *bla bla bla*
* Figure `A.62`: *bla bla bla*
If I'm on figure `A.59`, it's nice to immediately see where I have to jump to to get to `A.62`.

**Comment by lervag** [comment]
Ok, I see. In that scenario, I would open my PDF file and use reverse search. That is, I would find the location in the pdf file that corresponds to where I got feedback and press ctrl + left mouse click (with Zathura, other viewers may be different) to open that location in the source files.

**Comment by clason** [comment]
Texlab already has this; I find it of questionable value. (I prefer hover for checking the rendered label.)
<img width="823" alt="Screenshot 2023-12-20 at 18 46 07" src="https://github.com/lervag/vimtex/assets/2361214/e5ad2387-2cb8-41f9-9cc5-244433e425ad">
<img width="823" alt="Screenshot 2023-12-20 at 18 45 23"
 src="https://github.com/lervag/vimtex/assets/2361214/991f93f1-f174-4c24-a879-640472e2bbfd">

If you _do_ end up implementing this, I'd strongly recommend making this a toggle.

**Comment by PurpleMyst** [comment]
I'm not sure how you're getting them from texlab. I use it as well and I have no such thing.

**Comment by clason** [comment]
That's a question for another repo.

**Comment by lervag** [comment]
> Texlab already has this; I find it of questionable value. (I prefer hover for checking the rendered label.)

Thanks for the info. This makes me less inclined to add it, as I don't see any reason to reimplement something anyone can get from texlab. texlab works well with VimTeX already, so one should be able to use both.

Also, I agree that using hover seems better. Your second screenshot is very annoying to me with all the extra unnecessary added text.

> I'm not sure how you're getting them from texlab. I use it as well and I have no such thing.

I looked at your [dotfiles](https://github.com/PurpleMyst/dotfiles), and I couldn't find that you are using texlab there? In any case, for inlay hints you do need the latest neovim version, and possibly even closer to nightly. But, as @clason said, you will have more luck asking for these things at the texlab repo or something similar.

**Comment by clason** [comment]
> Your second screenshot is very annoying to me with all the extra unnecessary added text.

Oh, yeah, that's off by default, and only enabled briefly for a peek.

> possibly even closer to nightly.

Yes, inlay hints are only in nightly (will be released with 0.10), but since the OP wrote

> like the latest Neovim versions support.

I assumed that's what they were using.

**Comment by PurpleMyst** [comment]
I'll have to look into this on the texlab repo. Just for the record, I've got inlay hints working on rust-analyzer and the like, so it's weird texlab does not show them to me.

By the way, I should probably remove those dotfiles as the ones I currently use are managed differently ever since I switched from Linux to Windows.

Thank you all for the help. I believe we can close this issue.

**Comment by lervag** [comment]
> Thank you all for the help. I believe we can close this issue.

Glad to help! :+1:
