### ISSUE TITLE
SEGV when in continuous mode

### ISSUE THREAD

**Issue by hildensia** [lervag/vimtex#285]
Hi,

I get segfaults really often when I'm in continuous mode, which is really annoying. vim simply closes. Happens in both vim and gvim. I'm using some other plugins, which might interact in a badly way. They are: 
  * 'VundleVim/Vundle.vim'
  *  'altercation/vim-colors-solarized'
  * 'scrooloose/nerdcommenter'
  * 'gnupg.vim' 
  * 'Lokaltog/powerline', {'rtp': 'powerline/bindings/vim/'}
  * 'Valloric/YouCompleteMe'
  * 'fugitive.vim'
  * 'FSwitch'
  
I'm not very experienced with vim plugin development, so I do not know, what kind of information you need to track that problem.

Can you link me to an explanation of what information you would need and how I can gather it? (I'm experienced in general programming, though, so it does not need to be overly detailed)

**Comment by lervag** [comment]
Is there any way to reproduce this? With no way to reproduce, it is simply too difficult to debug, and so I will not be able to help.

FWIW: I use continuous mode myself, and it rarely crashes. Although, it has crashed a couple of times, but I think it is not due to vimtex itself. Since I am not able to reliably reproduce such crashes, I have no way of debugging it.

**Comment by hildensia** [comment]
It basically always happens after a a couple of seconds. I assume it tries to rebuild the document and when it runs latexmk the second or third time it crashes. What I do now is I switch to continuous mode lat it run two times and then turn it of.

**Comment by lervag** [comment]
And this only happens with vimtex?

Well, with no clear way to reproduce, this is going to be very difficult.

Let's start with the basics:

- Which OS are you running?
- What version of Vim are you on?
- Are you using the latest version of vimtex?
- Can you reproduce the error with a minimal vimrc file?

**Comment by hildensia** [comment]
I'll try the minimal vimrc asap. So far:

 * OS: Arch Linux 

    $ uname -a
    Linux quirm 4.2.1-1-ARCH #1 SMP PREEMPT Tue Sep 22 06:57:07 CEST 2015 x86_64 GNU/Linux

 * Vim: 7.4 (Details from `vim --version` see http://pastebin.com/PV7Cf9B1)
 * I just updated vimtex with `:VundleUpdate` -- it still crashes

**Comment by lervag** [comment]
Thanks. I'm also on Arch Linux, although I'm on Vim 7.4.884 and on a more recent kernel (4.2.5-1). Let me know if you need input on the minimal vimrc. There are several examples under the `/test` folder in the vimtex repo.

**Comment by hildensia** [comment]
Ok. I first do a `pacman -Syu` and then see what happens.

**Comment by Konfekt** [comment]
Are these all plugin? I had segfaults when using a plugin that updated the `tags` file when saving a TeX file. Disabling resolved the issue.

**Comment by hildensia** [comment]
Yes. that are all plugins. Updating arch (and hence vim and linux and a lot of other stuff) seems to resolve the issue.

**Comment by lervag** [comment]
Glad to hear the problem is resolved!
