### ISSUE TITLE
E716: Key not present in Dictionary: "subsubsubsubsection"

### ISSUE THREAD

**Issue by hrcHarry** [lervag/vimtex#2850]
### Description

I create deeper section levels: sub-sub-sub-section and sub-sub-sub-sub-section.

In the preamble, the declaration is as follows.

```
\usepackage{relsize} % For \relscale{}

\makeatletter
\newcommand{\subsubsubsection}{\@startsection{paragraph}{5}{\z@}{-2.5ex\@plus -1ex \@minus -.25ex}{1.25ex \@plus .25ex}{\noindent\normalfont\relscale{1.2767}}}
\makeatother

\setcounter{secnumdepth}{5}
\setcounter{tocdepth}{5}

\makeatletter
\newcommand{\subsubsubsubsection}{\@startsection{subparagraph}{6}{\z@}{-2.5ex\@plus -1ex \@minus -.25ex}{1.25ex \@plus .25ex}{\noindent\normalfont\relscale{1.123}}}
\makeatother

\setcounter{secnumdepth}{6} 
\setcounter{tocdepth}{6}        
```
sub-sub-sub-section shows in ToC (`vimtex-toc-open` ), functioning normally. However, once there is sub-sub-sub-sub-section in text, ToC gives the following message.
```
Error detected while processing function 90[12]..95[5]..vimtex#parser#toc[13]..vimtex#parser#toc#parse[8]..vimtex#parser#toc#level:
line    1:
E716: Key not present in Dictionary: "subsubsubsubsection"
```

Is there any remedy for this? Thanks.

Additional info:
OS: Win 10

### Steps to reproduce

test.tex
```
\documentclass[10pt,b5paper]{article}

\makeatletter
\newcommand{\subsubsubsection}{\@startsection{paragraph}{5}{\z@}{-2.5ex\@plus -1ex \@minus -.25ex}{1.25ex \@plus .25ex}{\noindent\normalfont}}
\makeatother

\setcounter{secnumdepth}{5}
\setcounter{tocdepth}{5}

\makeatletter
\newcommand{\subsubsubsubsection}{\@startsection{subparagraph}{6}{\z@}{-2.5ex\@plus -1ex \@minus -.25ex}{1.25ex \@plus .25ex}{\noindent\normalfont}}
\makeatother

\setcounter{secnumdepth}{6}
\setcounter{tocdepth}{6}    

\begin{document}

\frontmatter
\tableofcontents
\mainmatter

\section{Section}
123
\subsection{Sub-Section}
123
\subsubsection{Sub-Sub-Section}
123
\subsubsubsection{Sub-Sub-Sub-Section}
123
\subsubsubsubsection{Sub-Sub-Sub-Sub-Section}
123
\end{document}  
```

### Expected behavior

ToC can function normally where
1. sub-sub-sub-sub-section may show in ToC or
2. sub-sub-sub-sub-section may not show.

### Actual behavior

Vimtex gives the following message
```
Error detected while processing function 90[12]..95[5]..vimtex#parser#toc[13]..vimtex#parser#toc#parse[8]..vimtex#parser#toc#level:
line    1:
E716: Key not present in Dictionary: "subsubsubsubsection"
```

### Do you use a latexmkrc file?

No. There is no such file `latexmkrc` in the project directory.

### VimtexInfo

```yaml
Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..222[32]..224[4]..210[1]..211[1]..<SNR>99_get_os_info[18]..vimtex#jobs#cached[4]..8[4]..9:
line    6:
E474: String "<a5>D<be><f7><a6>W<ba><d9>:             HW1120005" contains byte that does not start any UTF-8 character
Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..222[32]..224[4]..210:
line    1:
E1098: String, List or Blob required
```

**Comment by lervag** [comment]
> I create deeper section levels: sub-sub-sub-section and sub-sub-sub-sub-section.

Hah, ok. The simplest solution is to just add support for one more level to the code. My personal opinion is that you should never need that many levels, but I think it won't hurt to just apply this change and it will fix things for you...

> Additional info: OS: Win 10

> ### VimtexInfo
> 
> ```yaml
> Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..222[32]..224[4]..210[1]..211[1]..<SNR>99_get_os_info[18]..vimtex#jobs#cached[4]..8[4]..9:
> line    6:
> E474: String "<a5>D<be><f7><a6>W<ba><d9>:             HW1120005" contains byte that does not start any UTF-8 character
> ```

I'm working on trying to improve this on Windows, see #2849. If you run `systeminfo` in a terminal (PowerShell or cmd), what's the output there?

**Comment by lervag** [comment]
I think the original issue is fixed now; please update and test.

**Comment by hrcHarry** [comment]
> I think the original issue is fixed now; please update and test.

Thank you so much! 🥰 Now it works.

**Comment by hrcHarry** [comment]
> > I create deeper section levels: sub-sub-sub-section and sub-sub-sub-sub-section.
> 
> Hah, ok. The simplest solution is to just add support for one more level to the code. My personal opinion is that you should never need that many levels, but I think it won't hurt to just apply this change and it will fix things for you...
> 
> > Additional info: OS: Win 10
> 
> > ### VimtexInfo
> > ```yaml
> > Error detected while processing function vimtex#info#open[2]..vimtex#scratch#new[2]..222[32]..224[4]..210[1]..211[1]..<SNR>99_get_os_info[18]..vimtex#jobs#cached[4]..8[4]..9:
> > line    6:
> > E474: String "<a5>D<be><f7><a6>W<ba><d9>:             HW1120005" contains byte that does not start any UTF-8 character
> > ```
> 
> I'm working on trying to improve this on Windows, see #2849. If you run `systeminfo` in a terminal (PowerShell or cmd), what's the output there?

There are so many info in `systeminfo`; what fields do you need? What can I help?

**Comment by lervag** [comment]
> ```yaml
> E474: String "<a5>D<be><f7><a6>W<ba><d9>:             HW1120005" contains byte that does not start any UTF-8 character
> ```

> > I'm working on trying to improve this on Windows, see #2849. If you run `systeminfo` in a terminal (PowerShell or cmd), what's the output there?
> 
> There are so many info in `systeminfo`; what fields do you need? What can I help?

Can you find something that ends with `:             HW1120005`? I would be happy to see what the string infront of `:` really is.

**Comment by hrcHarry** [comment]
> > ```yaml
> > E474: String "<a5>D<be><f7><a6>W<ba><d9>:             HW1120005" contains byte that does not start any UTF-8 character
> > ```
> 
> > > I'm working on trying to improve this on Windows, see #2849. If you run `systeminfo` in a terminal (PowerShell or cmd), what's the output there?
> > 
> > 
> > There are so many info in `systeminfo`; what fields do you need? What can I help?
> 
> Can you find something that ends with `: HW1120005`? I would be happy to see what the string infront of `:` really is.

Hi, it's `Host Name`.
````
Host Name:        HW1120005
````

**Comment by lervag** [comment]
That doesn't make sense. Is it "Host Name" except in a different language?

**Comment by hrcHarry** [comment]
> That doesn't make sense. Is it "Host Name" except in a different language?

Hi, that's the result of `systeminfo` on my machine. When language setting is chinese, it shows "主機名稱".

Hope that helps.

https://upload.cc/i1/2023/12/21/pHFPYT.png

**Comment by lervag** [comment]
Ok, thanks. :)
