### ISSUE TITLE
Use `exists()` instead of `silent!` to check `w:vimtex_match_id1` exist?

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2852]
**Is your feature request related to a problem? Please describe it.**

**Describe the solution you'd like**

See title.

https://github.com/lervag/vimtex/blob/e7ce03ea517c5b61ec9703a44019481678d60af3/autoload/vimtex/matchparen.vim#L67

Although it's not clear if the `matchdelete` itself can also raise error, in which case maybe keep the `silent!` in addition just in case.

**Additional context**

Context is in https://github.com/vim/vim/issues/13733 .

>  I'm using vimtex, and it has a line that uses `silent!` to suppress output:
> 
> ```
> function! s:matchparen.clear() abort dict " {{{1
>   silent! call matchdelete(w:vimtex_match_id1)
>   silent! call matchdelete(w:vimtex_match_id2)
>   unlet! w:vimtex_match_id1
>   unlet! w:vimtex_match_id2
> endfunction
> ```
> 
> (the variables `w:vimtex_match_id1` might not be defined)
> 
> Problem is, if I want to open some files remotely, the error messages may print out, even though they're completely nonconsequential:
> 
> ```
> $ vim --servername vim123 --remote-expr "execute('tabe a.tex | tabe b.tex')"
> 
> Error detected while processing BufNewFile Autocommands for "*.tex"..function dist#ft#FTtex[49]..FileType Autocommands for "*"..function <SNR>15_LoadFTPlugin[18]..script /home/user202729/.vim/pack/git-plugins/start/vimtex/ftplugin/tex.vim[25]..function vimtex#init[8]..<SNR>83_init_buffer[21]..vimtex#matchparen#init_buffer[3]..vimtex#matchparen#enable[1]..243[18]..246[1]..245:
> line    1:
> E121: Undefined variable: w:vimtex_match_id1
> Error detected while processing BufNewFile Autocommands for "*.tex"..function dist#ft#FTtex[49]..FileType Autocommands for "*"..function <SNR>15_LoadFTPlugin[18]..script /home/user202729/.vim/pack/git-plugins/start/vimtex/ftplugin/tex.vim[25]..function vimtex#init[8]..<SNR>83_init_buffer[21]..vimtex#matchparen#init_buffer[3]..vimtex#matchparen#enable[1]..243[18]..246[1]..245:
> line    1:
> E116: Invalid arguments for function matchdelete
> Error detected while processing BufNewFile Autocommands for "*.tex"..function dist#ft#FTtex[49]..FileType Autocommands for "*"..function <SNR>15_LoadFTPlugin[18]..script /home/user202729/.vim/pack/git-plugins/start/vimtex/ftplugin/tex.vim[25]..function vimtex#init[8]..<SNR>83_init_buffer[21]..vimtex#matchparen#init_buffer[3]..vimtex#matchparen#enable[1]..243[18]..246[1]..245:
> line    2:
> E121: Undefined variable: w:vimtex_match_id2
> Error detected while processing BufNewFile Autocommands for "*.tex"..function dist#ft#FTtex[49]..FileType Autocommands for "*"..function <SNR>15_LoadFTPlugin[18]..script /home/user202729/.vim/pack/git-plugins/start/vimtex/ftplugin/tex.vim[25]..function vimtex#init[8]..<SNR>83_init_buffer[21]..vimtex#matchparen#init_buffer[3]..vimtex#matchparen#enable[1]..243[18]..246[1]..245:
> line    2:
> E116: Invalid arguments for function matchdelete
> ```

**Comment by lervag** [comment]
Thanks; I see no reason not to use `exists()` here instead of `silent!`.
