### ISSUE TITLE
Inconsistent `vimtex_ui_method` for NeoVim

### ISSUE THREAD

**Issue by jdujava** [lervag/vimtex#2855]
### Description

In NeoVim, `<plug>(vimtex-env-change)` uses different input method (it is probably `legacy` input prompt) compared to `<plug>(vimtex-cmd-change)` (which uses by default `nvim` popup menu).

### Steps to reproduce

1. `nvim -u minimal.vim minimal.tex`
2. Keymap `csc` results in a popup menu (similarly `K`).
3. Keymap `cse` results in a command-line input prompt.

### Expected behavior

All input/select methods are by default consistent, so in NeoVim it is always popup menu.

### Do you use a latexmkrc file?

not relevant

### VimtexInfo

```yaml
not relevant
```

**Comment by lervag** [comment]
> In NeoVim, `<plug>(vimtex-env-change)` uses different input method (it is probably `legacy` input prompt) compared to `<plug>(vimtex-cmd-change)` (which uses by default `nvim` popup menu).

Yes, I know. The reason is that `cse` has completion and I've not been able to add completion to the custom popup input box.
