### ISSUE TITLE
Automatically compile asymptote file?

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2858]
**Is your feature request related to a problem? Please describe it.**
Currently, the feature to automatically compile TeX file with `\ll` is nice. Can we have the same thing for Asymptote? (is this within the scope of this plugin?)

**Additional context**
The main reason for me is that using `asy` or `asypicture` environment in PDFTeX has an overhead of about 0.6 → 1 second, on top of the Asymptote compilation itself which already take ≈ 0.6 second even with PDFLaTeX.

(and also that it doesn't seem to work too nicely with custom `-output-directory`)

**Comment by clason** [comment]
This is handled by your `.latexmkrc`, e.g., by adding
```perl
sub asy {return system("asy -o build/ '$_[0]'");}
add_cus_dep("asy","eps",0,"asy");
add_cus_dep("asy","pdf",0,"asy");
add_cus_dep("asy","tex",0,"asy");
```

**Comment by lervag** [comment]
Yes, I think @clason has a correct suggestion here. But if this is not what you are thinking of; could you provide a simple/minimal example of source files and a suggested minimal configuration for what you want?

**Comment by user202729** [comment]
I mean, if I have `a.tex` contains `\usepackage{asymptote}` → `\begin{asy}...` it would work. But if the whole document has the figure as the sole thing (common when testing I think) that involves invoking the PDFLaTeX engine (twice!) just to invoke asymptote, which is quite a waste of time.

My suggestion is that you can press `\ll` in an `.asy` file and have the compilation work.

**Comment by lervag** [comment]
Ok, I understand what you are asking for now. but again, can you provide a simple/minimal example of source files and a suggested minimal configuration for what you want?

I'm not trying to be rude. But you are asking for a new feature. I don't think it is too much to ask for some more concrete input that I can use while looking into if this is viable - and that will help if I were to implement the feature.

**Comment by user202729** [comment]
Sure, sorry I missed that part of the comment earlier.

```asymptote
settings.outformat="pdf";
size(6cm);
draw((0, 0)--(1, 1), L=Label("Text", EndPoint));
```


Output should look something like this

![image](https://github.com/lervag/vimtex/assets/25191436/33907b5b-6e01-4523-b71e-73da4bb7c219)

There's a little complication while implementing the feature: depends on what there is in global `config.asy`, command-line flag and/or `settings.outformat;` in the file, the output file may have one of several extensions.

**Comment by lervag** [comment]
I'm probably not being very clear, sorry. I want something like this:

1. A set of files, perhaps:

    ```vim
    " test.vim
    set nocompatible
    set runtimepath^=~/.local/plugged/vimtex
    set runtimepath+=~/.local/plugged/vimtex/after
    filetype plugin indent on
    syntax enable
    ```

    ```tex
    % test.tex
    \documentclass{article}
    \usepackage[inline]{asymptote}
    \begin{document}

    \begin{asy}
      \input{foo.asy}
    \end{asy}
    \end{document}
    ```

    ```asy
    # foo.asy
    settings.outformat="pdf";
    size(6cm);
    draw((0, 0)--(1, 1), L=Label("Text", EndPoint));
    ```

2. Steps with expected results:

  a. Start Vim with `nvim --clean -u test.vim test.tex`
  b. Do `gf` on `foo.asy` to open the file.
  c. `\ll` start compilation of `test.tex` (from within `foo.asy`)

However, I'm not sure what would be correct minimal content in the files and I want a clarification on the desired steps with expected results. Having this stuff clarified will ensure that I don't implement the wrong things.

**Comment by clason** [comment]
I think the ask here is to be able to compile asy files _without_ any surrounding TeX files (so call `asy` directly instead of `latexmk`/`pdflatex`).

I.e., the OP wants `VimAsy`.

**Comment by lervag** [comment]
Well, no, I believe he wants to compile embedded asy files. But it is confusing, which I think your comment clearly indicates. Let's hope we can get clarification :)

**Comment by user202729** [comment]
> I think the ask here is to be able to compile asy files _without_ any surrounding TeX files (so call `asy` directly instead of `latexmk`/`pdflatex`).
> 
> I.e., the OP wants `VimAsy`.

Sounds right. (I mean, if it is not too difficult to augment the current plugin, since the parts e.g. invoking the viewer etc. should hopefully be reusable for both?  Asymptote comes with default vim plugin for syntax highlighting)

That having said, I do use Asymptote inside LaTeX, just have to resort to standalone compilation because compile the whole TeX project is too slow. I don't think it's anywhere near easy for an external plugin to handle extracting the Asymptote code out of a TeX file because of e.g. asydef environments.

**Comment by lervag** [comment]
Ah, ok. In this case, it does feel out of scope. I don't have very much time these days, so I'm not really interested in adding this as a new feature. Sorry!
