### ISSUE TITLE
Bibtex parser: key vs label

### ISSUE THREAD

**Issue by micangl** [lervag/vimtex#2859]
### Description

I've fixed the [issue](https://github.com/micangl/cmp-vimtex/issues/13) raised on `cmp-vimtex` concerning an error. Apparently, Bibtex has a special `key` citation key. My parser procuded a result table, for the bibtex file, where the `key` entry was used for the citation label; as a consequence the actual `key` couldn't be inserted.

I've fixed the problem with this [commit](https://github.com/micangl/cmp-vimtex/commit/50da2d9baeca3e9efb9ca9d90f68c7cc01377bc2).

I don't know if you had already solved the problem but, as I don't have enough time to check, I still thought you should know for your parser.

**Comment by lervag** [comment]
I think my code was robust, so it didn't crash. But I was not aware that fields could be named "key". I've handled it slightly differently than you for now.
