### ISSUE TITLE
TOC for sections with optional arguments

### ISSUE THREAD

**Issue by Oloshka** [lervag/vimtex#286]
If I use the latex sectioning commands with optional argument then such sections disappear from toc.

Example:
```latex
\documentclass{article}
\begin{document}
\section{First section}
\section[Short title]{Second section long title}
\section{Third section}
\end{document}
```

TOC:
```
          Preamble
1         First section
2         Third section
```

**Comment by lervag** [comment]
Should be fixed now, thanks for reporting.

Note: I fixed this by ignoring the short title. This might not be the optimal way to handle things, but it was the simple way...

**Comment by Oloshka** [comment]
Thanks!
