### ISSUE TITLE
Zathura fails for symbolic links (physical vs. absolute logical paths)

### ISSUE THREAD

**Issue by mms-neuro** [lervag/vimtex#2865]
### Description

This is an observation I made - I found ways to get around it, but it might be interesting to fix it anyways.

If a tex-document is compiled in a directory with symbolic links in the path (and opened by that absolute path in the command) and should be opened with Zathura, zathura could try to open the file in the wrong directory.

### Steps to reproduce

The issue is probably a problem of how the paths are handled (and how symbolic links work on linux) and therefore mainly dependent on the file-structure. It should work with any minimal configuration, provided that `let g:vimtex_view_method = 'zathura'` (or minimal) is set. 

# Directory setting (bash)
My setting is quite complex, but I think this is the essence of the problem: 
In practice, a device should of course be mounted. 
```bash
cd /home/myusername/
mkdir /mnt/mydrive/
ln -s /mnt/mydrive 
cd mydrive
nvim /home/myusername/mydrive/test.tex
```
Then paste minimal example, write file and compile. 

Call `:VimxtexView`
# Comments on the setting
## Vimtex-Root
If I call (in `/home/myusername/mydrive`)
`nvim test.tex`, then the Vimtex-Root is `/mnt/mydrive/`
If I use `nvim /home/myusername/mydrive/test.tex`, then the Vimtex-Root for the same file is `/home/myusername/mydrive` (using the symbolic link).

Note, that in that case, `:pwd` and `!pwd` return different paths, the first the *physical path* `/mnt/mydrive` (can be called in bash by `pwd -P`) and the second one the 'logical path' `/home/myusername/mydrive` (`pwd -L`).
## Problems in Vimtex:
* I think at that place there have been issues before ( #2573 #2575) - the actual problem starts at https://github.com/lervag/vimtex/blob/f9b19d09ee6f0ba70dad0b5c2e710dd700681000/autoload/vimtex/view/zathura.vim#L55
   * In the second case (`nvim /home/myusername/mydrive/test.tex`), outfile will be `/home/myusername/mydrive/test.pdf`, while getcwd() will be `/mnt/mydrive/`. The result is then something like `../../home/home/myusername/mydrive/test.pdf` (not sure about the exact numers of `..`, but the problem is the double `home`:

### Expected behavior

Zathura window opens and shows `test.pdf` 

### Actual behavior

Zathura document opens and shows no file (tries to open the file in the wrong directory). 

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
Hope the problem is clear like that.
```

**Comment by mms-neuro** [comment]
There are several options to adress this problem:
1) Using absolute paths for zathura
2) Use something like `:resolve` to resolve symbolic links for  `root`/the file-names
3) Adapt `vimtex#paths#relative` so that it returns the right relative path in that situation.
I think the complexity of the possible approaches is increasing with the numbers ;)

**Comment by lervag** [comment]
Thanks, this is a very good bug report. To be honest, this almost feels like a bug with Vim/neovim itself. In the case where we use the absolute path, it seems that `expand('%:p')` resolves differently during vimtex initialization and _after_ vimtex is initialized.

I _could_ add `let l:main = resolve(l:main)` here:

https://github.com/lervag/vimtex/blob/f9b19d09ee6f0ba70dad0b5c2e710dd700681000/autoload/vimtex/state.vim#L17

However, I think it is a bad idea. E.g., if you were to do `ln -s test.tex foo.tex`, then I believe you expect VimTeX to respect it. If I resolve the main file, then we will always ignore that type of link.

But we _could_ resolve only the root part. I believe that makes more sense and may be an easy fix here.

**Comment by lervag** [comment]
I believe it is fixed now.
