### ISSUE TITLE
`which-key.nvim` support

### ISSUE THREAD

**Issue by Dolfost** [lervag/vimtex#2869]
Plugin default keymaps have no `desc` field set I guess. The `which-key` menu for `<leader>l` shows the `<plug>...` instead of command names. 

<img width="1710" alt="Screenshot 2024-01-12 at 5 18 44 PM" src="https://github.com/lervag/vimtex/assets/59747489/cfc554cc-4f04-4a2c-b481-382ffa31c641">

I have fixed this temporarily with 
```
		vim.keymap.set("n", "<localleader>ll", "<Cmd>update<CR><Cmd>VimtexCompile<CR>", {desc = "Vimtex compile"})
		vim.keymap.set({"n", "x"}, "<localleader>lL", "<Cmd>update<CR><Cmd>VimtexCompileSelected<CR>", {desc = "Vimtex compile selected"})
		vim.keymap.set("n", "<localleader>li", "<Cmd>VimtexInfo<CR>", {desc = "Vimtex info"})
		vim.keymap.set("n", "<localleader>lI", "<Cmd>VimtexInfo!<CR>", {desc = "Vimtex info full"})
		vim.keymap.set("n", "<localleader>lt", "<Cmd>VimtexTocOpen<CR>", {desc = "Vimtex TOC"})
		vim.keymap.set("n", "<localleader>lT", "<Cmd>VimtexTocToggle<CR>", {desc = "Vimtex toggle TOC"})
		vim.keymap.set("n", "<localleader>lq", "<Cmd>VimtexLog<CR>", {desc = "Vimtex log"})
		vim.keymap.set("n", "<localleader>lv", "<Cmd>VimtexView<CR>", {desc = "Vimtex view"})
		vim.keymap.set("n", "<localleader>lr", "<plug>(Vimtex-reverse-search)", {desc = "Vimtex reverse search"})
		vim.keymap.set("n", "<localleader>lk", "<Cmd>VimtexStop<CR>", {desc = "Vimtex stop"})
		vim.keymap.set("n", "<localleader>lK", "<Cmd>VimtexStopAll<CR>", {desc = "Vimtex stop all"})
		vim.keymap.set("n", "<localleader>le", "<Cmd>VimtexErrors<CR>", {desc = "Vimtex errors"})
		vim.keymap.set("n", "<localleader>lo", "<Cmd>VimtexCompileOutput<CR>", {desc = "Vimtex compille output"})
		vim.keymap.set("n", "<localleader>lg", "<Cmd>VimtexStatus<CR>", {desc = "Vimtex status"})
		vim.keymap.set("n", "<localleader>lG", "<Cmd>VimtexStatus!<CR>", {desc = "Vimtex full status"})
		vim.keymap.set("n", "<localleader>lc", "<Cmd>VimtexClean<CR>", {desc = "Vimtex clean"})
		vim.keymap.set("n", "<localleader>lC", "<Cmd>VimtexClean!<CR>", {desc = "Vimtex full clean"})
		vim.keymap.set("n", "<localleader>lx", "<Cmd>VimtexReload<CR>", {desc = "Vimtex reload"})
		vim.keymap.set("n", "<localleader>lX", "<Cmd>VimtexReloadState<CR>", {desc = "Vimtex reload state"})
		vim.keymap.set("n", "<localleader>lm", "<Cmd>VimtexImapsList<CR>", {desc = "Vimtex input maps list"})
		vim.keymap.set("n", "<localleader>ls", "<Cmd>VimtexToggleMain<CR>", {desc = "Vimtex toggle main"})
		vim.keymap.set("n", "<localleader>la", "<Cmd>VimtexContextMenu<CR>", {desc = "Vimtex context menu"})
```
 
<img width="1710" alt="Screenshot 2024-01-12 at 5 19 06 PM" src="https://github.com/lervag/vimtex/assets/59747489/651171e8-700c-4618-9444-6aeb4a63917b">

I think this should be defined out of the box. Also, the normal mode edit commands have no description.

A bit of context: 
- I use `lazy.nvim` plugin manager
- nvim is v0.9.5
- OS: macOS Sonoma 14.2.1 ARM
- nvim is installed via homebrew package manager

**Comment by lervag** [comment]
This is because VimTeX is written in Vimscript which does not support the `desc` field for mappings. I'm not planning to rewrite things that generally work well in Lua, thus this is a won't fix from my side. Sorry.

**Comment by Dolfost** [comment]
> This is because VimTeX is written in Vimscript which does not support the `desc` field for mappings. I'm not planning to rewrite things that generally work well in Lua, thus this is a won't fix from my side. Sorry.

Okay. Thank for Your answer.

**Comment by firubat** [comment]
@lervag @Dolfost I think that the "proper" way to approach this is not to change the keymaps themselves or the way they are implemented, but to tell which-key their proper descriptions. Here is an example, using lazy.vim:

```
{
    "folke/which-key.nvim",
    optional = true,
    opts = {
      defaults = {
        ["<localLeader>l"] = {
          name = "+vimtex",
          l = { "Vimtex compile" },
          L = { "Vimtex compile selected" },
          i = { "Vimtex info" },
          I = { "Vimtex info full" },
          t = { "Vimtex TOC" },
          T = { "Vimtex toggle TOC" },
          q = { "Vimtex log" },
          v = { "Vimtex view" },
          r = { "Vimtex reverse search" },
          k = { "Vimtex stop" },
          K = { "Vimtex stop all" },
          e = { "Vimtex errors" },
          o = { "Vimtex compille output" },
          g = { "Vimtex status" },
          G = { "Vimtex full status" },
          c = { "Vimtex clean" },
          C = { "Vimtex full clean" },
          x = { "Vimtex reload" },
          X = { "Vimtex reload state" },
          m = { "Vimtex input maps list" },
          s = { "Vimtex toggle main" },
          a = { "Vimtex context menu" },
        },
      },
    },
}
```

**Comment by lervag** [comment]
Thanks, @firubat!

**Comment by laoumh** [comment]
It seems @firubat's solution doesn't work anymore because `wk.register` was deprecated (view, for instance, https://github.com/folke/which-key.nvim/commit/596bbb89735a6afe9fce1893d0f556acbb8a65e9).

Here's a reworked solution using `wk.add` to add a description to existing mappings:

```lua
local wk = require("which-key")
wk.add({
  { "<leader>l", group = "Vimtex" },
  { "<leader>lv", desc = "view" },
  { "<leader>ll", desc = "compile" },
  { "<leader>lL", desc = "compile selected" },
  { "<leader>li", desc = "info" },
  { "<leader>lI", desc = "info full" },
  { "<leader>lt", desc = "TOC" },
  { "<leader>lT", desc = "toggle TOC" },
  { "<leader>lq", desc = "log" },
  { "<leader>lv", desc = "view" },
  { "<leader>lr", desc = "reverse search" },
  { "<leader>lk", desc = "stop" },
  { "<leader>lK", desc = "stop all" },
  { "<leader>le", desc = "errors" },
  { "<leader>lo", desc = "compille output" },
  { "<leader>lg", desc = "status" },
  { "<leader>lG", desc = "full status" },
  { "<leader>lc", desc = "clean" },
  { "<leader>lC", desc = "full clean" },
  { "<leader>lx", desc = "reload" },
  { "<leader>lX", desc = "reload state" },
  { "<leader>lm", desc = "input maps list" },
  { "<leader>ls", desc = "toggle main" },
  { "<leader>la", desc = "context menu" },
})
```

Note that when the right-hand side argument is omitted, the mapping is preserved and only a description is added (so there is no need to rewrite the associated command, like `{ "<leader>lv", "<plug>(vimtex-view)", desc = "view" }`).

I like to place this type of configuration within the plugin that the key maps correspond to (so, in this case, `lua/plugins/vimtex.tex`), but I guess placing in which-key's `opts.spec` would also work.

**Comment by Dolfost** [comment]
Hello everyone. I got notification of @laoumh post. I also have which-key binds. I made them 4 months ago when which-key updated. [Here they are](https://github.com/Dolfost/dotfiles/blob/main/nvim/lua/plugins/vimtex.lua). 

The icons won't be visible in browser, see the `wk.add` snippet in [nerd font](https://www.nerdfonts.com).

![Screenshot 2024-11-29 at 9 47 12 PM](https://github.com/user-attachments/assets/daed8ea9-4ee7-487b-bd4d-2eab50044f5d)

**Comment by firubat** [comment]
@laoumh Indeed which-key changed its way of defining things, I actually changed according to its suggestion but forgot to update here...
Here I incorporated @Dolfost icons (thanks!) without the map definitions, and there are also some additional descriptions for motions, as well as the way to add it in a lazy.nvim way:
```
 {"folke/which-key.nvim",
    optional = true,
    opts = {
      spec = {
      {   -- Vimtex mappings
          mode = { "n", "v" },
          { "<localLeader>l", group = "Vimtex", icon = { icon = "", color = "green" } },
          { "<localLeader>lc", desc = "Clean", icon = { icon = "󰃢", color = "orange" } },
          { "<localLeader>lC", desc = "Full clean", icon = { icon = "󰃢", color = "red" } },
          { "<localLeader>lx", desc = "Reload", icon = { icon = "󰑓", color = "green" } },
          { "<localLeader>lX", desc = "Reload state", icon = { icon = "󰑓", color = "cyan" } },
          { "<localLeader>la", desc = "Context menu", icon = { icon = "󰮫", color = "purple" } },
          { "<localLeader>le", desc = "Errors", icon = { icon = "", color = "red" } },
          { "<localLeader>lg", desc = "Status", icon = { icon = "󱖫", color = "purple" } },
          { "<localLeader>lG", desc = "Full status", icon = { icon = "󱖫", color = "purple" } },
          { "<localLeader>li", desc = "Info", icon = { icon = "", color = "purple" } },
          { "<localLeader>lI", desc = "Info full", icon = { icon = "󰙎", color = "purple" } },
          { "<localLeader>lk", desc = "Stop", icon = { icon = "", color = "red" } },
          { "<localLeader>lK", desc = "Stop all", icon = { icon = "󰓛", color = "red" } },
          { "<localLeader>lv", desc = "View", icon = { icon = "", color = "green" } },
          { "<localLeader>ll", desc = "Compile", icon = { icon = "", color = "green" } },
          { "<localLeader>lL", desc = "Compile selected", icon = { icon = "", color = "green" } },
          { "<localLeader>lo", desc = "Compile output", icon = { icon = "", color = "purple" } },
          { "<localLeader>lm", desc = "Input maps list", icon = { icon = "", color = "purple" } },
          { "<localLeader>lq", desc = "Log", icon = { icon = "", color = "purple" } },
          { "<localLeader>lr", desc = "Reverse search", icon = { icon = "", color = "purple" } },
          { "<localLeader>ls", desc = "Toggle main", icon = { icon = "󱪚", color = "green" } },
          { "<localLeader>lt", desc = "TOC", icon = { icon = "󰠶", color = "purple" } },
          { "<localLeader>lT", desc = "Toggle TOC", icon = { icon = "󰠶", color = "purple" } },
        },

    { -- Vimtex motions
          mode = { "n", "x", "o" },
          { "]", group = "Goto next" },
          { "[", group = "Goto previous" },
          { "]]", desc = "Next end of a section" },
          { "][", desc = "Next beginning of a section" },
          { "[]", desc = "Previous end of a section" },
          { "[[", desc = "Previous beginning of a section" },
          { "]m", desc = "Next start of an environment `\\begin`" },
          { "]M", desc = "Next end of an environment `\\end`" },
          { "[m", desc = "Previous start of an environment `\\begin`" },
          { "[M", desc = "Previous end of an environment `\\end`" },
          { "]n", desc = "Next start of a math zone" },
          { "]N", desc = "Next end of a math zone" },
          { "[n", desc = "Previous start of a math zone" },
          { "[N", desc = "Previous end of a math zone" },
          { "]r", desc = "Next start of a frame environment" },
          { "]R", desc = "Next end of a frame environment" },
          { "[r", desc = "Previous start of a frame environment" },
          { "[R", desc = "Previous end of a frame environment" },
          { "]/", desc = "Next start of a LaTeX comment" },
          { "]*", desc = "Next end of a LaTeX comment" },
          { "[/", desc = "Previous start of a LaTeX comment" },
          { "[*", desc = "Previous end of a LaTeX comment" },
        },
    },
  },
}

```

**Comment by lervag** [comment]
I'm glad to see people share which-key configurations here. Perhaps it would be a good idea to add a page to the wiki? If so, I could consider to add a link to it from the VimTeX docs as well.

**Comment by Dolfost** [comment]
> I'm glad to see people share which-key configurations here. Perhaps it would be a good idea to add a page to the wiki? If so, I could consider to add a link to it from the VimTeX docs as well.
> 
> I.e., I would propose to add a [new page](https://github.com/lervag/vimtex/wiki/_new) e.g. named "`which-key.nvim` support".

Amazing idea! I just finished refining my bindings with `:h vimtex`!

**Comment by lervag** [comment]
Thanks for making [a first version](https://github.com/lervag/vimtex/wiki/which%E2%80%90key.nvim-support). I've edited it. Notice that I made a few significant changes that you should be aware of:

1. **important** You should _not_ lazy load VimTeX! There is no significant benefit, and it breaks the inverse search feature if you use the one suggested by VimTeX with `:VimtexInverseSearch`.
2. The configuration should be with `init = function...`, not `config = ...`, because a few options does not work as expected unless they are fully defined before VimTeX is loaded. Again, this does not have any significant drawback.
3. I removed some of your configuration that did not seem relevant to the purpose of the wiki page.

**Comment by Dolfost** [comment]
> Thanks for making [a first version](https://github.com/lervag/vimtex/wiki/which%E2%80%90key.nvim-support). I've edited it. Notice that I made a few significant changes that you should be aware of:
> 
> 1. [**important**] You should _not_ lazy load VimTeX! There is no significant benefit, and it breaks the inverse search feature if you use the one suggested by VimTeX with `:VimtexInverseSearch`.
> 2. The configuration should be with `init = function...`, not `config = ...`, because a few options does not work as expected unless they are fully defined before VimTeX is loaded. Again, this does not have any significant drawback.
> 3. I removed some of your configuration that did not seem relevant to the purpose of the wiki page.

Thanks for pointing out! I will update my configuration.

**Comment by Rmano** [comment]
H! Thanks for the wiki page!

A question: suppose that I have a basic vimscript `nvim` configuration; how should I load those options? 

I have just 

    Plug 'folke/which-key.nvim'

in my `init.vim`...

**Comment by lervag** [comment]
I'll update the wiki page with info for vim-plug now; let me know if that doesn't answer your question (should be ready in ~5 minutes).

**Comment by lervag** [comment]
> A question: suppose that I have a basic vimscript `nvim` configuration; how should I load those options?

I've updated the wiki page now; notice, even if you do have vimscript based neovim configuration, you can of course still mix in a lua file as suggested in the updated wiki. Let me know if it doesn't work!

**Comment by Rmano** [comment]
> > A question: suppose that I have a basic vimscript `nvim` configuration; how should I load those options?
> 
> I've updated the wiki page now; notice, even if you do have vimscript based neovim configuration, you can of course still mix in a lua file as suggested in the updated wiki. Let me know if it doesn't work!

It works like a charm. Thanks!

**Comment by lervag** [comment]
Glad to hear it!

**Comment by firubat** [comment]
@lervag @Dolfost Thanks for the great work!

**Comment by Rmano** [comment]
Hi. Sorry to abuse this issue, but I do not know if there is a discussion page for the wiki pages... 

I have a very strange problem with the suggested `ftplugin/tex.lua` solution. It works ok **most** of the time, but it has a very nasty interaction with `--remote-tab`. 

To test it, suppose you have two files in `~/tmp`, `lilla.tex` and `lalla.tex`. Now, edit the first one starting a server pipe: 

    nvim --listen ./here.pipe lilla.tex

and in another shell, `cd` to the same dir, and 

    nvim --server ./here.pipe --remote-tab lalla.tex

Now, when you use in *input mode* `]]`, you have this:

![image](https://github.com/user-attachments/assets/cf5d93ca-bcf5-4477-937d-a3691523966b)

That seems strictly related to `--remote-tab`. In all other cases I tested, there is no problem. I will try to recheck this with a minimal setup (I have to find how I do the `-U minimal.vimrc` in `nvim`, though...).

**Comment by lervag** [comment]
> I have a very strange problem with the suggested `ftplugin/tex.lua` solution. It works ok **most** of the time, but it has a very nasty interaction with `--remote-tab`.

Just out of curiosity, what is the use case of `--remote-tab`? Or, how does it fit in your workflow?

> To test it, suppose you have two files in `~/tmp`, `lilla.tex` and `lalla.tex`. Now, edit the first one starting a server pipe: …

Nothing comes to mind immediately about what is wrong here. It would help to
have a minimal example.

> I have to find how I do the `-U minimal.vimrc` in `nvim`, though....

I would guess you could do something like this:

1. Create a folder `tmp` into which you copy the `ftplugin/tex.lua` file with the entire path.

2. Use a `test.vim` file like this

    ```vim
    set nocompatible
    set runtimepath^=~/.local/plugged/vimtex
    set runtimepath+=~/.local/plugged/vimtex/after
    set runtimepath^=~/tmp
    filetype plugin indent on
    syntax enable

    " ... other options/config
    ```

3. Then `nvim --clean -u test.vim` should have a a minimal config.

**Comment by Rmano** [comment]
> Just out of curiosity, what is the use case of `--remote-tab`? Or, how does it fit in your workflow?

I have a script that creates a `Vim` window for each virtual desktop... if there is already a window open, the script will add the file to a tab of the window. Otherwise, it will create a new one. With  `barbar`, it is quite handy --- I can double-click in the file manager or open the file with the script and have it in the same vim instance. So I have, for example, different projects on different virtual desktops, and every file I edit goes automatically to the right one ;-). 

I will try the minimal thing as soon as I can. Thanks! 

(And if you want to have a look at the script, just ask and I'll send it)

**Comment by lervag** [comment]
> > Just out of curiosity, what is the use case of `--remote-tab`? Or, how does it fit in your workflow?
> 
> I have a script that creates a `Vim` window for each virtual desktop... …

Cool! I like it; although it's clearly very specific to your own workflow. And of course, the config for VimTeX and which-key.nvim should work well with this, so I think we should be able to figure things out here.

> I will try the minimal thing as soon as I can. Thanks!

Great. Feel free to open a new issue for this, though, if you don't figure things out immediately on your own with the minimal example. Or you could consider to start a discussion - I've not used them much, but they should also work.

**Comment by laoumh** [comment]
@lervag @Dolfost thank you very much, the menu looks awesome!

**Comment by Rmano** [comment]
BTW, is it possible to add the mappings from the backside (`` `a → \alpha``) to the `which-keys` mappings? It would be so useful...

**Comment by lervag** [comment]
> I have opened #3057, having managed to have a minimal configuration that reproduces the problem. Fell free to move it to a discussion if you think it's better suited.

👍 Will look at it when I get the time!

> BTW, is it possible to add the mappings from the backside (`` `a → \alpha ``) to the `which-keys` mappings? It would be so useful...

I hope someone else may help answer this one; I don't use which-keys, so it's hard for me to answer without first investigating that plugin...

**Comment by firubat** [comment]
> BTW, is it possible to add the mappings from the backquote (`` `a → \alpha ``) to the `which-keys` mappings? It would be so useful...

Oh I did not know about this functionality, thanks @Rmano ! It is actually there:
![image](https://github.com/user-attachments/assets/a68b2e23-ab5d-420f-bee4-2b64ad6508a5)

If you want to have it look nicer you can add to the example in the wiki
```
 { -- Vimtex ` shortcuts
          mode = { "i" },
          { "`", group = "Vimtex ` " },
          { "`a", desc = "\\alpha" },
-- more here
}
```
But that's quite a long list so I'm not sure it's so helpful, and doing it manually will be a pain. But if I understand correctly,  these mappings are [automatically generated](https://github.com/lervag/vimtex/blob/b8bb79b5fb27e9030ade92e75cd9375416f2c666/autoload/vimtex/imaps.vim#L83C3-L83C6), so there probably should be a way to also automatically generate these additions, i.e. put something like the following line into some function (which I don't know how to define)
```
wk.add({ lhs, desc = rhs, mode = "i" })
```

**Comment by Rmano** [comment]
> Oh I did not know about this functionality, thanks @Rmano ! It is actually there:

Hmm --- my problem is that this is not triggered here. I mean, I press the backquote in math mode, and the `whick-key` menu does not trigger. I have a `.vim` init script, so I rely only on the `tex.lua` of the wiki to set up which-key... and I have not even been able to set up the mode till now. I will have to play with the Vimscript/lua interface a bit more, it seems, because I think I am missing some basic steps. 

Thanks anyway, I will continue the search...

**Comment by firubat** [comment]
I see, maybe you need to configure which-key a bit more thoroughly, I admit I don't know what should be done as I use [LazyVim](https://www.lazyvim.org/)'s configuration. But you can look [there](https://www.lazyvim.org/plugins/editor#which-keynvim) for ideas. Good luck!

**Comment by Rmano** [comment]
Thanks. I have to say that this is a bit frustrating (I'm just moving to `nvim`) --- it seems that using LazyVim seems almost mandatory. I am trying using

```
lua << EOF
require("which-key").setup({
    opts = {
        preset = "helix",
    },
})
EOF
```

...but it seems it does nothing. Well. I'll stop pestering and try to really understand the interactions here...

**Comment by Dolfost** [comment]
> > Oh I did not know about this functionality, thanks @Rmano ! It is actually there:
> 
> Hmm --- my problem is that this is not triggered here. I mean, I press the backquote in math mode, and the `whick-key` menu does not trigger. I have a `.vim` init script, so I rely only on the `tex.lua` of the wiki to set up which-key... and I have not even been able to set up the mode till now. I will have to play with the Vimscript/lua interface a bit more, it seems, because I think I am missing some basic steps.
> 
> Thanks anyway, I will continue the search...

Looks like You haven't set up which-key triggers for insert mode bindings. For details see `:help which-key` especially `:help which-key.nvim-which-key-triggers`.

**Comment by Rmano** [comment]
So, it seems that I have to add 

```
        triggers = {
             { "`", mode = { "i"} },
          },
```

to my `ftplugin/tex.lua`, but I am at a loss on *how* to do this without using `lazy.vim` (and even then, I am not clear what the method is).  The in-line Lua I used two questions above does not work... is there anyway an example on how to set up options for `which-key`  in a vimscript/vimplug environment? Or should I bite the bullet and change all my configuration to Lua? The `:help which-key` says 

  
![image](https://github.com/user-attachments/assets/c3e4ba1f-5632-4bbb-956a-c12ba7762721)

...but I can't find *how* to change the defaults or add something... :-(

**Comment by Rmano** [comment]
Ok, found it. I will post here if some noobie is around and chatGPT does its magic. 

```
lua << EOF
require("which-key").setup({
        preset = "helix",
        triggers = {
             { "<auto>", mode = "nxsoi" },
        }
})
EOF
```
...works
