### ISSUE TITLE
Equation label autocompletion shows incorrect equation numbers

### ISSUE THREAD

**Issue by matthewjohnrussell** [lervag/vimtex#287]
Using omnicomplete (`<C-X><C-O>`) within `\ref{}` or `\eqref{}` etc. shows the list of possible labels, but the equation numbers that are shown are not correct. It is always a single digit number that is shown, and it seems to be correct for equation numbers which actually have one digit. After that, I'm not sure what the pattern is (maybe the last digit of the actual number?)

**Comment by lervag** [comment]
Thanks, I've noticed this myself, but I never took the time to investigate properly. I'm pusing a fix in a couple of minutes.

**Comment by matthewjohnrussell** [comment]
Fantastic! Many thanks.

**Comment by lervag** [comment]
No problem :)
