### ISSUE TITLE
Errors E716 E116 when running :VimtexTocOpen in a file containing a \label

### ISSUE THREAD

**Issue by brechetp** [lervag/vimtex#2883]
Hi :)

First of all, thank you so much for this wonderful vim plugin! I couldn't think of writing `.tex` files without it.

It's my first time opening a ticket on github, I hope the description will be to your liking! Please, tell me otherwise.

### Description

Two errors (**E716**, **E116**) come up when running `:VimtexTocOpen` (or `:VimtexTocToggle`) in a file containing some `\label` commands. The  commands run smoothly in the same file without the `\label`.

Here is the error log:

```
Error detected while processing function 356[12]..361[5]..vimtex#parser#toc[13]..vimtex#parser#toc#parse[65]..509:
line    4:
E716: Key not present in Dictionary: "format, l:key, l:label), 'number' : '', 'file'   : a:context.file, 'line'   : a:context.lnum, 'level'  : a:context.max_level - a:context.level.current, 'rank'   : a:context.lnum_total, 'type'   : 'label', }"
E116: Invalid arguments for function printf(self.format, l:key, l:label), 'number' : '', 'file'   : a:context.file, 'line'   : a:context.lnum, 'level'  : a:context.max_level - a:context.level.current, 'rank'   : a:context.lnum_total, 'type'   : 'label', }
```

I can't seem to find the same set of errors online.

It is relatively recent, and persists even when checking-out older commits. I therefore think it's because of my system, but I can't find the reason why, nor can debug vim scripts :'(

I tried with a minimal `vimrc` file, no other plugins, and with a `minimal.tex` file as well.

Would you have an idea where this could be coming from?

### Steps to reproduce

1. `vim -Nu "vimrc" mimimal.tex`
2.  Run `:VimtexTocOpen` ---> fails

**minimal.tex**:

```tex
\documentclass{article}
\begin{document}

\section{Introduction}
\label{sec:intro}

\end{document}
```

**vimrc** (using `vim-plug`):
```vimrc
call plug#begin()
Plug 'lervag/vimtex'
call plug#end()
```

### Expected behavior

When following the above-mentioned steps, I expect the TOC to open.

### Actual behavior

When following the above steps, I get the following error message

```
Error detected while processing function 356[12]..361[5]..vimtex#parser#toc[13]..vimtex#parser#toc#parse[65]..509:
line    4:
E716: Key not present in Dictionary: "format, l:key, l:label), 'number' : '', 'file'   : a:context.file, 'line'   : a:context.lnum, 'level'  : a:context.max_level - a:context.level.current, 'rank'   : a:context.lnum_total, 'type'   : 'label', }"
E116: Invalid arguments for function printf(self.format, l:key, l:label), 'number' : '', 'file'   : a:context.file, 'line'   : a:context.lnum, 'level'  : a:context.max_level - a:context.level.current, 'rank'   : a:context.lnum_total, 'type'   : 'label', }
```

### Do you use a latexmkrc file?

no

### VimtexInfo

```yaml
System info:
  OS: Debian GNU/Linux 11 (bullseye)
  Vim version: VIM 8.2 (1-2434)
  Has clientserver: true
  Servername: undefined (vim started without --servername)

VimTeX project: minimal
  base: minimal.tex
  root: /home/user/thesis
  tex: /home/user/thesis/minimal.tex
  main parser: current file verified
  document class: article
  compiler: latexmk
    engine: -pdf
    options:
      -verbose
      -file-line-error
      -synctex=1
      -interaction=nonstopmode
    callback: 1
    continuous: 1
    executable: latexmk
  viewer: General
  qf method: LaTeX logfile
```

**Comment by lervag** [comment]
> First of all, thank you so much for this wonderful vim plugin! I couldn't think of writing `.tex` files without it.

Thanks for the kind words!

> It's my first time opening a ticket on github, I hope the description will be to your liking! Please, tell me otherwise.

Yes, this is a good first ticket! Nice to see that you're using proper formatting and everything!

> Two errors (**E716**, **E116**) come up when running `:VimtexTocOpen` (or `:VimtexTocToggle`) in a file containing some `\label` commands. The commands run smoothly in the same file without the `\label`.
> 
> Here is the error log:
> 
> ```
> Error detected while processing function 356[12]..361[5]..vimtex#parser#toc[13]..vimtex#parser#toc#parse[65]..509:
> line    4:
> E716: Key not present in Dictionary: "format, l:key, l:label), 'number' : '', 'file'   : a:context.file, 'line'   : a:context.lnum, 'level'  : a:context.max_level - a:context.level.current, 'rank'   : a:context.lnum_total, 'type'   : 'label', }"
> ```

I can't reproduce this on my end. I've made a minor patch that _might_ fix it. Before you update and test, please read my next reply and see if you can still reproduce with an updated minimal config.

> It is relatively recent, and persists even when checking-out older commits. I therefore think it's because of my system, but I can't find the reason why, nor can debug vim scripts :'(
> 
> I tried with a minimal `vimrc` file, no other plugins, and with a `minimal.tex` file as well.
> 
>     1. `vim -Nu "vimrc" mimimal.tex`
>     2. Run `:VimtexTocOpen` ---> fails

Can you try and reproduce with `vim --clean -u test.vim minimal.tex` instead; where `test.vim` is as given here:

```vim
set nocompatible
set runtimepath^=~/.vim/plugged/vimtex
set runtimepath+=~/.vim/plugged/vimtex/after
filetype plugin indent on
syntax enable
```

Can you still reproduce your problem now?

> ```yaml
> System info:
>   OS: Debian GNU/Linux 11 (bullseye)
>   Vim version: VIM 8.2 (1-2434)
>   Has clientserver: true
>   Servername: undefined (vim started without --servername)
> ```

Just in case you didn't already know of it, you should read `:help vimtex-clientserver`.

**Comment by lervag** [comment]
> Thanks you for your quick reply and your feedback!
> 
> I reproduced the steps you described, and I still got the error, but your patch fixed it! Thank you so much for your assistance, that's really wonderful.
> 
> Thanks again!

Glad to hear it! It is still surprising to me that you could reproduce the problem, but let's not spend more energy on it if it works now :)

> I went ahead and closed the ticket, is this OK?

Yes, perfect. And feel free to open new issues if you have other questions or problems.
