### ISSUE TITLE
fold comments

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#289]
How about an option to fold comments? The standard syntax folding does that. Tho it's not best practice to fold away chunks of your code, in practice it happens a lot.

**Comment by lervag** [comment]
I just made some attempts at this, and I realised it is slightly difficult. It requires more context, and thus it complicates the optimization I currently use to speed up the fold level function.

I would be happy to consider a pull request, but the functionality is IMHO not very important, and thus it should be optional and it should not affect the speed of the fold function to a high degree.

**Comment by Konfekt** [comment]
Ok, didn't expect these complications as the regex checking for a comment is just ^\s*%. Do things lie different for syntax folding?

**Comment by lervag** [comment]
Ok, I managed to find the correct logic. It wasn't as complicated as I first thought, it seems. I hope it works and that you find it useful.

**Comment by Konfekt** [comment]
Thanks!

**Comment by nasenatmer** [comment]
Hey, thanks for this new option which will be immensely helpful!

**Comment by lervag** [comment]
I'm happy you like it :-)

lør. 5. des. 2015, 14.18 skrev Jakob Hetzelein <notifications@github.com>:
