### ISSUE TITLE
Use new synctex interactive mode to speed up synctex

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2892]
**Is your feature request related to a problem? Please describe it.**
For large PDF files, synctex may take 1-2 seconds.

**Describe the solution you'd like**
We can use the new synctex feature (explained in https://github.com/user202729/luatex/commit/0831bb66f6591a1e609bbbac04c6fecb208ee824#commitcomment-139418652 ) (if the feature is available with the installed synctex version that is)

------

Another option is to use the C interface `libsynctex`, but I think this would complicate the distribution process (require the user to compile C and/or distribute platform-dependent executables)

**Comment by lervag** [comment]
> **Describe the solution you'd like** We can use the new synctex feature (explained in [user202729/luatex@0831bb6#commitcomment-139418652](https://github.com/user202729/luatex/commit/0831bb66f6591a1e609bbbac04c6fecb208ee824#commitcomment-139418652) ) (if the feature is available with the installed synctex version that is)

To be honest, I don't quite understand how to use the new synctex feature based on that comment (and the linked threads).

Also, it looks like this stuff is brand new and not really available in any releases yet? That is, the PR https://github.com/jlaurens/synctex/pull/75 is not even merged yet. But perhaps I'm misunderstanding this?

The main question is: How should I update VimTeX to take use this new feature?

> Another option is to use the C interface `libsynctex`, but I think this would complicate the distribution process (require the user to compile C and/or distribute platform-dependent executables)

Yes, this seems too complicated.

**Comment by user202729** [comment]
Basically the feature works like this:

Currently, in vimtex you have a command `<Plug>(vimtex-view)` that invokes `synctex view ...`.

The problem with this approach is that each time you invoke the executable, it has to parse the synctex file (which let's say takes 1-2 second), then the executable exits immediately, so the parsing result is lost and next time it needs to be parsed again.

With the new change, you invoke the synctex executable with `--interactive`, then the executable will remain there in the background, the next time you want to invoke `synctex view …`, you just pass it to the standard input of the executable.

------

Indeed, it's not available in any release yet. This is just a proposal to see if you're interested in implementing it (or at least have it implemented, I can try to pull request in the latter case).

------

On the vimtex side, I think an implementation would need to:

* keep track of the running synctex job as well as the latexmk job
* change the logic as needed to use the synctex job instead of spawning a new process
* other bookkeeping stuff (e.g. on `\lx` plugin reload, terminate the synctex job as well, and on `\ll`... should the synctex job be kept running?)

**Comment by lervag** [comment]
> Currently, in vimtex you have a command `<Plug>(vimtex-view)` that invokes `synctex view ...`.

Well, that's not quite right. VimTeX never really uses `synctex` explicitly, except in a single specific sub case: It is used for the MuPDF viewer, because MuPDF does not have built-in support for synctex.

Instead, the viewers use synctex behind the scenes.

So, IMHO, it would make much more sense to delegate this responsibility to the viewers. Then it would also benefit users who don't use VimTeX.

> With the new change, you invoke the synctex executable with `--interactive`, then the executable will remain there in the background, the next time you want to invoke `synctex view …`, you just pass it to the standard input of the executable.

I'm curious: Does `synctex --interactive` work be creating a daemon process such that subsequent _standard_ `synctex ...` calls will reuse the daemon process?

That is, would it sort of suffice for VimTeX to start this daemon process when someone invokes the viewer, and then just ensure to kill it when the specific LaTeX project is closed?

**Comment by user202729** [comment]
That's interesting, I made a wrong assumption. Looks like it's zathura's fault then.

> I'm curious: Does synctex --interactive work be creating a daemon process such that subsequent standard synctex ... calls will reuse the daemon process?

Unfortunately, no. But that sounds like a nice idea.

**Comment by lervag** [comment]
> That's interesting, I made a wrong assumption. Looks like it's zathura's fault then.

No problem!
