### ISSUE TITLE
Toggle to revert changes made in issue 2401

### ISSUE THREAD

**Issue by jrmd54** [lervag/vimtex#2893]
Hello,

Is there a way to add an option that toggle the change made to solve issue [#2401](https://github.com/lervag/vimtex/issues/2401) on linux?
I use zathura and would like my viewer to close upon exising vim.

(sorry if such option already exist, i searched in the documentation/issues but did not find anything related except issue #2401)

Thank you very much

**Comment by lervag** [comment]
> Is there a way to add an option that toggle the change made to solve issue [#2401](https://github.com/lervag/vimtex/issues/2401) on linux? I use zathura and would like my viewer to close upon exising vim.

That change did not affect Zathura, so this is not related to #2401.

If you are on a Linux system with `xdotool`, then you can try something like this:

```vim
" Close viewers when VimTeX buffers are closed
function! CloseViewers()
  if executable('xdotool')
        \ && exists('b:vimtex.viewer.xwin_id')
        \ && b:vimtex.viewer.xwin_id > 0
    call system('xdotool windowclose '. b:vimtex.viewer.xwin_id)
  endif
endfunction

augroup vimtex_event_2
  au!
  au User VimtexEventQuit call CloseViewers()
augroup END
```

**Comment by jrmd54** [comment]
It works, thank you very much!

**Comment by jrmd54** [comment]
It works, thank you very much!
