### ISSUE TITLE
l:file not defined in function vimtex#compiler#compile_selected(type)

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#2896]
When calling `:VimtexCompileSelected`, the error message

```vim
Trovato errore eseguendo function vimtex#compiler#compile_selected:
riga   33:
E121: Variabile non definita: l:file
E116: Argomenti non validi per la funzione: vimtex#qf#inquire(l:file.tex)
No newer jump position
```

shows up. Indeed, at

https://github.com/lervag/vimtex/blob/a77d14b2e4391c0d3e860708bb1fd56161ab68eb/autoload/vimtex/compiler.vim#L172

it is not evident how `l:file` came to be.

**Comment by Konfekt** [comment]
This is on master. On https://github.com/lervag/vimtex/releases/tag/v2.13 this issue cannot be reproduced

**Comment by lervag** [comment]
Sorry, that was a silly regression bug. It should be fixed now!

**Comment by Konfekt** [comment]
Thank you for everything, that went quick!

**Comment by lervag** [comment]
No problem, thanks for noticing and reporting the bug!
