### ISSUE TITLE
Setup text argument in user-defined command

### ISSUE THREAD

**Issue by Nora-n** [lervag/vimtex#2898]
I have a custom `\beforetext` command that adds text on the left side of an equation. Following #2755, I'd like to know how to setup a local syntax to tell `vimtex` that what's inside is text. I looked up the commit you made for `witharrows` and could easily reproduce it, but my command is not attached to any package. Would you be able to point me in the right direction to do that?

```
  syntax match texMathCmdText "\\beforetext\>"
        \ contained skipwhite nextgroup=texMathTextArg
```

As always, thank you for this fantastic plugin and your maintenance of it :-).

**Comment by lervag** [comment]
Hi!

> I have a custom `\beforetext` command that adds text on the left side of an equation. Following #2755, I'd like to know how to setup a local syntax to tell `vimtex` that what's inside is text. I looked up the commit you made for `witharrows` and could easily reproduce it, but my command is not attached to any package. Would you be able to point me in the right direction to do that?
> 
> ```
>   syntax match texMathCmdText "\\beforetext\>"
>         \ contained skipwhite nextgroup=texMathTextArg
> ```

I believe you can solve this with the `g:vimtex_syntax_custom_cmds` option. Specify it wherever you specify your other VimTeX options. Something like this:

```vim
let g:vimtex_syntax_custom_cmds = [
      \ {'name': 'beforetext', 'mathmode': v:true,
      \  'nextgroup': 'texMathTextArg'},
      \]
```

> As always, thank you for this fantastic plugin and your maintenance of it :-).

Thanks for the kind words! <3

**Comment by Nora-n** [comment]
Thank you! I must've missed it, I just started using the useful concealing tools and changed the highlighting groups, but didn't stumble on that.

Cheers! :-)

**Comment by lervag** [comment]
> Thank you! I must've missed it, I just started using the useful concealing tools and changed the highlighting groups, but didn't stumble on that.

I'll be the first to admit it's easy to miss things when the documentation has reached 7000 lines of text... in any case, no problem!
