### ISSUE TITLE
Can't open .tex files... sort of?

### ISSUE THREAD

**Issue by joakimHertzberg** [lervag/vimtex#2903]
### Description

Hello! I just installed VimTeX in my nvim config, but the first time I try opening a file after launching neovim, I get following error message: 

<img width="883" alt="Screenshot 2024-03-22 145050" src="https://github.com/lervag/vimtex/assets/72621585/e75e1798-38d2-4d5a-bce9-226c352879b2">

The second attempt, the file opens with no error message, but no syntax highlighting.

The third time, however, it opens with no message AND syntax highlighting works all of a sudden.

I don't understand where this stems from.

FYI: Don't know if this is relevant, but my nvim is installed with scoop.

I'm very new to neovim, so this could be something really simple, don't know.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
E492: Not an editor command: VimtexInfo
```

**Comment by lervag** [comment]
> ### Description
> 
> Hello! I just installed VimTeX in my nvim config, but the first time I try opening a file after launching neovim, I get following error message:

Notice the message content: "Cannot create directory H:\/.cache: no such file or directory".

It seems you are running neovim with some strange settings in your system. The relevant setting is `g:vimtex_cache_root`, which by default should be set to `$HOME . "/.cache/vimtex"` where `$HOME` is an environment variable that is usually set on most systems to a user directory. On your system, it is clearly set to `H:\` where you do not have permission to create a new folder.

> The second attempt, the file opens with no error message, but no syntax highlighting.
> 
> The third time, however, it opens with no message AND syntax highlighting works all of a sudden.

I'm not sure exactly why this happens.

> FYI: Don't know if this is relevant, but my nvim is installed with scoop.

I don't _think_ that this should be very relevant.

----

It would be useful to see how you've loaded and configured VimTeX. Which plugin manager are you using?

**Comment by joakimHertzberg** [comment]
Okay! I've configured neovim with VimTeX on my school laptop. I went into my init.lua and added the code below in a `vim.cmd[[]]`

```vim
let g: vimtex_cache_root= 'C:/Users/ah48963/.cache/vimtex'
```

Which has fixed it!

**Comment by lervag** [comment]
Great, glad to hear it works now.
