### ISSUE TITLE
Disabling "latexmk is not executable" message on startup

### ISSUE THREAD

**Issue by DUOLabs333** [lervag/vimtex#2905]
**Is your feature request related to a problem? Please describe it.**
Every time I start up Neovim, I get the message `latexmk is not executable`. I don't use latexmk (or bibtex, or any such program), and I'm using VimTeX only for its syntax highlighting. So, this message is superfluous to me (especially I work fine without it). 

**Describe the solution you'd like**
Allow an option disabling the startup error messages.

**Additional context**
I tried `let g:vimtex_compiler_enabled=0`, but the messages still show up.

**Comment by lervag** [comment]
`let g:vimtex_compiler_enabled = 0` should work now.

**Comment by DUOLabs333** [comment]
This seems to work. Thanks!

**Comment by lervag** [comment]
Great, glad to hear it!
