### ISSUE TITLE
Support for \eqref ompletion

### ISSUE THREAD

**Issue by eolianoe** [lervag/vimtex#291]
Would it be possible to support [`\eqref{}`](https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing#eqref) completion (from the [`amsmath`](http://ctan.org/pkg/amsmath) package)  in the same manner as `\ref{}` completion ?

Thanks by advance

**Comment by lervag** [comment]
This should already be implemented. Does it not work for you?

**Comment by lervag** [comment]
See `/path/to/vimtex/test/feature/completions/main.tex`. This is a simple example file that I use to test the completion feature. When I compile this document and then try omnicompletion with `\eqref{<c-x><c-o>`, it works exactly as expected.

**Comment by eolianoe** [comment]
Sorry for the noise, it works as expected with `\eqref{<c-x><c-o>`. But with `\ref{}` it is automatic, no need of `<c-x><c-o>`, maybe there is a conflict between plugins ?

**Comment by lervag** [comment]
Ah, no. Vimtex does not provide autocompletion. This is provided by neocomplete or YouCompleteMe. Which of these do you use? I personally use neocomplete with the following settings:

```vim
let g:neocomplete#sources#omni#input_patterns.tex =
      \ '\v\\\a*(ref|cite)\a*([^]]*\])?\{([^}]*,)*[^}]*'
```

**Comment by eolianoe** [comment]
Again sorry for disturbance, I'm using YouCompleteMe, which works nicely if I write the right configuration line `let g:ycm_semantic_triggers = {'tex': ['\ref{','\cite{','\eqref{']}`.

**Comment by lervag** [comment]
I've actually suggested a trigger in the docs, please see `:h vimtex-complete-youcompleteme`: 

```vim
  let g:ycm_semantic_triggers.tex = [
        \ 're!\\[A-Za-z]*(ref|cite)[A-Za-z]*([^]]*])?{([^}]*, ?)*'
        \ ]
```

This trigger should work with a lot of different `ref` and `cite` variants, e.g. `\cref`, `\autocite`, ....

**Comment by eolianoe** [comment]
Yes, I saw this one but it was conflicting with an old that I have, I cleaned everything and take the one from the doc. And everything works fine, thanks.

**Comment by lervag** [comment]
Great, and no problem :)
