### ISSUE TITLE
[Feature request] Allow for title of "Fake(sub)sectio" if folded

### ISSUE THREAD

**Issue by nasenatmer** [lervag/vimtex#292]
Hey, 

crazy to see how much happened here while I was working with two group projects in MS Office (horrible!) which are now finally over, *phew*. But now I'm back to vimtex to write my Master's thesis and am still catching up with new features (especially folding) and am quite intrigued at the pace of development which is great to see!

I have one — admittedly low-priority-but-nice-to-have — feature request: Is there any possibility to give "names" to a `Fake(sub)section` when they are folded? Right now, when a `Fakesection` is folded, vim displays only `* Fakesubsection` which can get confusing if you have several Fake(sub)sections in a row like me: 

```vimL
*     Theoretical Framework
*     Fakesection
*     Fakesection
*     Fakesection
*     Fakesection
*     Research design
```

Which is why I wonder whether it would be possible to assign each Fake(sub)section a name by writing e.g. `%Fakesubsection {Empirical studies}` which would then show the fold as

```
*     Fakesubsection Empirical studies
```

Again, this is rather candy than bread and butter and if it's rather hard to implement I fully understand if you reject this, but I thought I'd simply ask to find out.

**Comment by lervag** [comment]
This is actually already supported, but perhaps we should update/modify it. Today, you can get a title if you use `Fakesection: ...` (or similar). That is, you need the colon.

If you are an avid user of fakesections, then perhaps you have a good idea about how the title string should be parsed. I.e., should it include the "Fakesection" string, or should it be similar to other sectioning levels and just include the title itself?

**Comment by nasenatmer** [comment]
Wow, I didn't expect that!

Right now, it doesn't show `Fakesection` if a title is given which is fine in a way. But there's one downside: If you have a `Fakesubsection` next to a real `subsection` you can't discriminate between them if they're both folded.

```tex
\subsection{Concepts}
%Fakesubsection: Concepts, definitions,etc.
```
will conflate to:
```tex
*     Concepts
*     Concepts, definitions, etc.
```

Therefore, it might be a good idea, to keep `Fake(sub)section` in the title string to know which is a real and which is a fake(sub)section…

**Comment by lervag** [comment]
Ok. I've pushed an update where the fold text becomes the entire fake section line, i.e. for your example above:

```
Fakesubsection: Concepts, definitions,etc.
```

I also added documentation about the fake section folding (I noticed there were none).

**Comment by nasenatmer** [comment]
Great, works as it should! Thanks for that!

**Comment by lervag** [comment]
No problem :-)

lør. 5. des. 2015, 13.52 skrev Jakob Hetzelein <notifications@github.com>:
