### ISSUE TITLE
What can we do to improve the output parsing/visuals of pdflatex?

### ISSUE THREAD

**Issue by ThSGM** [lervag/vimtex#2920]
I've long puzzled over why I find the output display of vimtex so difficult to work with, as compared to `normal' LaTeX UIs like SublimeText, TeXShop, etc. I wanted to make a discussion to raise some thoughts. 

To me, there are three things: 

1. Is there a parser that better parses the output? 
2. Is there a parser that can visually colourise the output? 
3. Is there something about the quickfix interface and output display that makes it inferior to other UIs? 

I am not sure what the answer to these questions are. I think it might take some side-to-side comparison. But just two further thoughts.

1. Apparently [pplatex](https://github.com/stefanhepp/pplatex) can be used to 'prettify' output, and this is incorporated into vimtex. However pplatex is not easily obtainable on Mac. I have not tried to build it from source. 
2. [QuieTeX](https://github.com/mje-nz/quietex) looks super promising. @lervag can we incorporate this into vimtex? [Here is the demo of before and after](https://github.com/mje-nz/quietex/blob/master/screen-recordings.md)

**Comment by lervag** [comment]
> I've long puzzled over why I find the output display of vimtex

Just so we're clear, your talking about the output visible in `:VimtexCompileOutput` (`\lo`), right?

> 1. Apparently [pplatex](https://github.com/stefanhepp/pplatex) can be used to 'prettify' output, and this is incorporated into vimtex. However pplatex is not easily obtainable on Mac. I have not tried to build it from source.

`pplatex` is available as an option for parsing the log file and giving input to the quickfix window. But I don't think this is what you are talking about here. Also, I don't really think `pplatex` can be easily used as a "filter" for `latexmk` or similar.

> 2. [QuieTeX](https://github.com/mje-nz/quietex) looks super promising. @lervag can we incorporate this into vimtex? [Here is the demo of before and after](https://github.com/mje-nz/quietex/blob/master/screen-recordings.md)

This is interesting. But notice that you can already use it with `latexmk` by adding a line to your `.latexmkrc` file. This means you can use it with VimTeX without changing anything in VimTeX!

But to me, it does not seem to provide a _very_ big improvement to the output, and the project has been stale for 3 years.
