### ISSUE TITLE
Push some files to vim runtime?

### ISSUE THREAD

**Issue by Freed-Wu** [lervag/vimtex#2923]
Can we push some files to vim runtime, such as compiler/*.vim? Refer https://github.com/vim/vim/pull/14459

TIA!

**Comment by lervag** [comment]
Sorry, but could you explain in a little bit more detail what you are proposing?

**Comment by Freed-Wu** [comment]
For example, push vimtex's complier/bibertool.vim to vim runtime, And set `compiler bibertool` for `bib`.

**Comment by clason** [comment]
@Freed-Wu I know you're on a vim PR rampage (and maybe consider slowing down to give the poor maintainers some breathing space -- this is not a sprint!), but remember what people told you about the drawbacks of upstreaming filetype plugins (especially the added maintenance burden). In particular,
1. VimTeX is a tightly integrated plugin, so carving out random chunks will not work well;
2. Everyone that is seriously working with TeX files will want the "full VimTeX experience", so most people will not profit from the upstreamed files.

(This is different from, e.g., the julia filetype plugin, where Vim had _no_ support and the functionality on top of the basic syntax and indent files was questionable.)

**Comment by Freed-Wu** [comment]
IMO, many compliers `compiler/chktex.vim`, `compiler/bibertool.vim`, ... can work without other code of vimtex, so I think perhaps we can put them to vim runtime to let more people enjoy it.

> give the poor maintainers some breathing space -- this is not a sprint

Sorry, :cry: I'll wait some time.

**Comment by clason** [comment]
Rule of thumb: wait for your PR to be merged before opening a new one. (Batches of two or three are fine, but keeping opening new ones while the maintainers are still busy reviewing the old ones is simply overloading them.)

**Comment by lervag** [comment]
> For example, push vimtex's complier/bibertool.vim to vim runtime, And set `compiler bibertool` for `bib`.

I do think @clason has a good point that most people who work with LaTeX will probably want VimTeX as well, but I don't mind if some things are pushed upstream if the core maintainers are fine with that. I won't do that work myself, but if there is anything I should do as the maintainer of VimTeX, just let me know.

It seems like `bibertool`, `lacheck` and `style-check` could be candidates for upstreaming, since these have no other dependency on anything VimTeX.

The other compilers have dependencies to VimTeX options. This includes `chktex`, because it depends on `g:vimtex_lint_chktex_parameters` and `…_ignore_warnings`. Pushing these upstream would require some more consideration.

**Comment by Freed-Wu** [comment]
> if the core maintainers are fine with that

@clason

>  I won't do that work myself, but if there is anything I should do as the maintainer of VimTeX, just let me know.

Maybe we can add a CI/CD, when the upstream (this repo)'s `compiler/*.vim` is newer than downstream (vim runtime), open a PR by `github action[bot]`.

> chktex, because it depends on g:vimtex_lint_chktex_parameters and …_ignore_warnings

Surprised. `chktex` have `~/.chktexrc` to set its behaviour. Why we still need an extra behaviour to set its behaviour.

**Comment by clason** [comment]
I'm not a (Vim) core maintainer. But, again, you _don't_ want every single change in this repo to be pushed upstream -- those should be _much_ more stable. It's a fallacy to believe that everything that _can_ be part of Vim's runtime _should_ be part of Vim's runtime. I'm frankly wondering what the motivation behind your runtime crusade is.

(And adding _and maintaining_ CI sounds like even more work -- _a lot_ more work...)

**Comment by lervag** [comment]
Regardless of the discussion, I don't think there is currently any direct action to take for VimTeX here. If Vim would adopt anything into its runtime it would be useful to know it. I'm not personally against it, but I also don't think it is very important.

Thus, I'll close this issue now.
