### ISSUE TITLE
Detect "Overfull vbox" warning messages in log file

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2924]
```
%! TEX program = pdflatex
\documentclass{article}
\usepackage{graphicx}
\begin{document}

\includegraphics[width=20cm, height=1cm]{example-image-a}

\includegraphics[height=30cm, width=1cm]{example-image-a}

\end{document}
```

⟹ log file contains

```
Overfull \hbox (239.0729pt too wide) in paragraph at lines 6--7

⋮

Overfull \vbox (303.66812pt too high) has occurred while \output is active []
```

There's no line number in the error message however. Should we still do this?

**Comment by lervag** [comment]
> There's no line number in the error message however. Should we still do this?

You mean, should we still include the error message in the parsed log? Currently, it will only be included if there is some form of line specification:

https://github.com/lervag/vimtex/blob/ac0a41b297a70c101df89bc9c8d43341ba00fd4f/autoload/vimtex/qf/latexlog.vim#L60

I think we could probably add another matcher to include `\vbox` warnings that don't have the line specification. Users are free to ignore the messages with the filter option, so I think it makes  sense to include all relevant warnings. Right?

**Comment by lervag** [comment]
I'm sorry for the delay here! I didn't notice the "thumbs up" - my workflow is based on email notifications on replies, and since I didn't get a reply, this ended up going to `/dev/null`.

I'll add the matcher as I suggested!
