### ISSUE TITLE
SumatraPDF: Forward Search not working properly

### ISSUE THREAD

**Issue by ThelloD** [lervag/vimtex#294]
Fix: In *ftplugin\latex-suite\compiler.vim* on line *371* replace
`let execString .= Tex_Stringformat('start %s "%s" -forward-search "%s" %s', viewer, target_file, mainfnameFull.".tex", linenr)`
with
`let execString .= Tex_Stringformat('start %s "%s" -forward-search "%s" %s', viewer, target_file, sourcefileFull, linenr)`

Explanation:
mainfnameFull always represents the main latex file. However, if you are including additional latex files (e.g. using \input), you have to use the file name of the *current* latex file. Otherwise the PDF viewer will jump to the wrong position.

Furthermore, you might consider to change the if query `elseif (viewer =~? "^sumatrapdf")` on line 368. This won't work, if the user sets `let g:Tex_ViewRule_pdf` to a full path. Using something like `elseif (viewer =~? "sumatrapdf")` allows the usage of full paths for *g:Tex_ViewRule_pdf*, like e.g. `let g:Tex_ViewRule_pdf = 'C:\MyApps\MiKTeX\bin\SumatraPDF.exe'`.
However, it might be a good idea, if the query only matches Strings ending with either "sumatrapdf" or "sumatrapdf.exe".

**Comment by lervag** [comment]
I'm sorry, but I think you must confuse this plugin with [LaTeX-Suite](http://vim-latex.sourceforge.net/).
