### ISSUE TITLE
"Missing character" error message of LuaTeX is not detected

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2943]
```
%! TEX program = lualatex
\documentclass{article}
\begin{document}
\tracinglostchars=3
\symbol{1}
\end{document}
```

Results in "Compilation failed!" without any error message.

Must compile with LuaLaTeX. For PDFLaTeX the character at position 1 does exist (you can replace 1 with 255, but then for PDFLaTeX then the error **is** detected)

**Comment by lervag** [comment]
I think it's fixed now; please update and test. Notice, I was not able to parse the line number of the error.

**Comment by user202729** [comment]
Yes that works 😄 but there's a little quirk:  if it's only set to be a warning instead of an error, the parser will gobble the next line.

Quickfix window:

```
c.tex|| There is no ^^A (U+0001) in font [lmroman10-regular]:+tlig;! {/home/user202729/.texlive/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] (/tmp/.tex-fast-recompile-tmp/301923-01rf2jzi/c.aux)
```

Log file partial:

```
c.tex

(./c.tex [1


Missing character: There is no ^^A (U+0001) in font [lmroman10-regular]:+tlig;!
{/home/user202729/.texlive/texmf-var/fonts/map/pdftex/updmap/pdftex.map}] (/tmp/.tex-fast-recompile-tmp/301923-01rf2jzi/c.aux)
 ***********
LaTeX2e <2023-11-01> patch level 1
L3 programming layer <2024-02-20>
 ***********
```

**Comment by lervag** [comment]
Huh, so `\tracinglostchars=3` specifies that this is an error? I'm not sure if I want to support that feature. Thus, if the default behaviour is to mark it is a warning, then that's what we should do.

So, I propose we "demote" the "Missing character" to a warning, and then I'll also fix the gobble-problem. Does that sound fine by you?

**Comment by user202729** [comment]
I didn't know vimtex handles a warning and an error differently. I don't see any problem either way as long as it's visible to the user.

**Comment by lervag** [comment]
> I didn't know vimtex handles a warning and an error differently.

Ah, well, that's not precisely what I meant. What we do, more precisely is to parse the latex log file line for line with the errorformat spec, see e.g.:

https://github.com/lervag/vimtex/blob/8b668fb0ec1eff810998c810de5374a1635183c0/autoload/vimtex/qf/latexlog.vim#L39-L66

This is definitely an esoteric DSL that takes some getting used to!

So, in this sense, we handle warnings and errors the same. But we do match them slightly differently. The problem with your last example is that this line in the log:

https://github.com/lervag/vimtex/blob/8b668fb0ec1eff810998c810de5374a1635183c0/test/example-quickfix/main.log#L55

was matched as a multi-line continuation in line 40 of `latexlog.vim`. So, I had to add a more specific matcher to ignore it (i.e. line 39).

> Note that the default mode of vimtex is in `\scrollmode` (we forcefully continue through errors) anyway.

Yes, but I don't think that is relevant here.
