### ISSUE TITLE
"VimTeX does not support your version of Vim" on neovim

### ISSUE THREAD

**Issue by Ocisaac** [lervag/vimtex#2944]
### Description

I use neovim 0.9.4 on ubuntu WSL. I installed VimTex via VimPlug.
When I try to edit a tex file, I get the following error: 
```
Error detected while processing BufReadPost Autocommands for "*":
Error executing lua callback: /snap/nvim/2819/usr/share/nvim/runtime/filetype.lua:24: Error executing lua: /snap/nvim/28
19/usr/share/nvim/runtime/filetype.lua:25: BufReadPost Autocommands for "*"..FileType Autocommands for "*"..function <SN
R>1_LoadFTPlugin[19]..script /home/adios/.local/share/nvim/plugged/vimtex/ftplugin/tex.vim, line 19: Vim(echoerr):Error:
 VimTeX does not support your version of Vim
stack traceback:
        [C]: in function 'nvim_cmd'
        /snap/nvim/2819/usr/share/nvim/runtime/filetype.lua:25: in function </snap/nvim/2819/usr/share/nvim/runtime/file
type.lua:24>
        [C]: in function 'nvim_buf_call'
        /snap/nvim/2819/usr/share/nvim/runtime/filetype.lua:24: in function </snap/nvim/2819/usr/share/nvim/runtime/file
type.lua:10>
stack traceback:
        [C]: in function 'nvim_buf_call'
        /snap/nvim/2819/usr/share/nvim/runtime/filetype.lua:24: in function </snap/nvim/2819/usr/share/nvim/runtime/file
type.lua:10>
```

I'd be happy to know how to fix it, or if the bug can be resolved

### Steps to reproduce

`nvim -u minimal.lua minimal.tex`

`minimal.lua`:
```
local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')
Plug('lervag/vimtex')
vim.call('plug#end')
```

`minimal.tex`:
Empty

### Expected behavior

To open an empty file 

### Actual behavior

The error described above.

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
I don't have the command available.
```

**Comment by lervag** [comment]
You have three options:

1. Upgrade to neovim v0.9.5.
2. Degrade VimTeX to v2.15.
3. Set `g:vimtex_version_check` to 0 or false.

See the latest release notes for more info: https://github.com/lervag/vimtex/releases/tag/v2.15

Notice: the third options is not really recommended, although it will probably work fine for you now and will be the simplest solution.

**Comment by Ocisaac** [comment]
I ended up picking #2, which worked.
Thanks!

**Comment by lervag** [comment]
No problem; that's a valid solution! Notice that you may be interested in checking updates in the future when you have Neovim 0.9.5.

**Comment by fiktor** [comment]
Here is how to find the latest version of vimtex supporting the currently installed version of Vim or NeoVim and perform @hoxu's fix above with the up-to-date tag:

* Step 1. In vim / neovim, check the version using the command `:version` (or, e.g., `nvim --version` from command line).
* Step 2. Go to https://github.com/lervag/vimtex/blob/master/ftplugin/tex.vim . Somewhere around line 17 there are the minimal supported versions of VIM and NeoVim.
* Step 3. Choose recent tags in the GitHub UI to go to a previous version of that file and find the tag which supports your current version of NeoVim. E.g. I have NeoVim v0.9.5 and it is supported by VimTeX v2.16 (see screenshot).
![Image](https://github.com/user-attachments/assets/99f0bd8d-430f-4bb0-a87c-0be40b010b6c)

* Step 4. Now use the above fix with the tag you've found. E.g. in my case
```
Plug 'lervag/vimtex', { 'tag': 'v2.16' }
```

**Comment by lervag** [comment]
This may be useful information, so thanks for sharing. But please note that I will not backport fixes, so I strongly recommend that you consider finding a way to upgrade your Vim or Neovim versions.
