### ISSUE TITLE
Is it possible to add `vimtex#compiler#is_running()` again?

### ISSUE THREAD

**Issue by WenLinkis** [lervag/vimtex#2945]
Sometimes I need to check if the compilation is currently running, and I stumbled upon a function `vimtex#compiler#is_running()` that did this before:

- [feat: add vimtex#compiler#is_running · lervag/vimtex@401bea8](https://github.com/lervag/vimtex/commit/401bea84b863f34a04b227fa60d2f498d7c9b7fb#diff-d1b4cedf8b2b99405a642de59c292d881f5299d4bf5386dab618eff676f8f786)
- [Is it possible to add a symbol to the neovim built-in statusline when the tex compiler is active in continuous mode? · Issue #1906 · lervag/vimtex](https://github.com/lervag/vimtex/issues/1906). 

But it seems to have been removed later on, so it's possible to put it back in?

BTW, I'm really enjoying this plugin. Huge thanks for your awesome work on it!

**Comment by lervag** [comment]
> Sometimes I need to check if the compilation is currently running, and I stumbled upon a function `vimtex#compiler#is_running()` that did this before: …

I don't quite remember _why_ I removed it, but I believe I realized that I didn't need it. In VimTeX code, I use this:

```vim
exists('b:vimtex.compiler') && b:vimtex.compiler.is_running()
```

The first `exists()` is necessary if you are calling this from a context where the VimTeX buffer state is not available.

> But it seems to have been removed later on, so it's possible to put it back in?

I _could_ consider adding it back in as a convenience API, but the above snippet should work and is already quite small. I'm not sure if it is necessary?

> BTW, I'm really enjoying this plugin. Huge thanks for your awesome work on it!

Thanks for the kind words!

**Comment by WenLinkis** [comment]
Thanks for your reply.

I test `echo b:vimtex.compiler.is_running()` in command-line, it works. But when I try to use it in neovim and lua:

```lua
vim.b.vimtex.compiler.is_running
```

it returns `vim.NIL`. It confused me a lot

![demo](https://github.com/lervag/vimtex/assets/82384131/251e85d8-0921-4eed-8ca3-ae9bdbba49fd)

**Comment by lervag** [comment]
In Lua, we need to use the `nvim_call_dict_function`. This should work:

```lua
local ok, result = pcall(vim.api.nvim_call_dict_function, "b:vimtex.compiler", "is_running", {})
local is_running = ok and result
```

Here `pcall` is used to handle the error when `b:vimtex.compiler` is not available (e.g. if you are not in a LaTeX file).

**Comment by lervag** [comment]
It is not so strange that you are confused. The main issue here is that the dictionary functions in Vimscript are not readily available in Lua, so we need to use wrappers.

**Comment by WenLinkis** [comment]
It works. Really appreciate that!

**Comment by lervag** [comment]
Glad to help!
