### ISSUE TITLE
[help] Get details of citation under cursor

### ISSUE THREAD

**Issue by anandkumar89** [lervag/vimtex#2946]
I'm trying to write a script that could open pdf linked to citation under cursor. Since vimtex parses bibtex files linked, is it possible to get entire details for the citation key under cursor ?

**Comment by lervag** [comment]
Yes. You can use `vimtex#cite#get_entry()` for that.

**Comment by lervag** [comment]
> Thanks a ton @lervag

No problem; thanks for the request!

Notice, just in case you were not aware, that there is already a context feature that sort of provides what you are looking for here. See `:help vimtex-context-cite`.

> for anyone stumbling here, looking for similar. I use zotero with better-bibtex to export bib files (file entry is automatically included). keymap below allows to open corresponding pdf when cursor is on the citation key. …

I think this is a _slightly_ improved version:

```lua
vim.keymap.set('n', '<leader>zo', function()
  local citation_entry = vim.fn['vimtex#cite#get_entry']()
  job:new({
    command = '/path/to/sioyek',
    args = { citation_entry.file },
    detached = true,
  }):start()
end, {desc='Open pdf related to citations'})
```

**Comment by lervag** [comment]
You can try to change the `g:vimtex_context_pdf_viewer` option.

**Comment by lervag** [comment]
No problem :)

Notice, using the context function means several key presses. If you frequently want to just open the corresponding pdf, then having the direct version you asked for in this issue makes sense. That's why I didn't immediately mention the context feature. ;)
