### ISSUE TITLE
Error detected while processing function callback

### ISSUE THREAD

**Issue by weberam2** [lervag/vimtex#2949]
### Description

Hello,

I'm using the LazyVim config

I keep getting this error when I save/compile:

```
Error detected while processing function <SNR>59_callback_nvim_output[8]..<SNR>59_check_callback[4]..vimtex#compiler#callback[38]..vimtex#qf#open:
line   46:
E5108: Error executing lua .../nvim-lazyvim/lazy/bufferline.nvim/lua/bufferline/ui.lua:119: attempt to call field 'is_list' (a nil value)
stack traceback:
> .../nvim-lazyvim/lazy/bufferline.nvim/lua/bufferline/ui.lua:119: in function 'get_component_size'
```

Any ideas?

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
1 System info:
    1 │ OS: Ubuntu 22.04.3 LTS
    2 │ Vim version: NVIM v0.10.0-dev-777+gc6c21db82
    3 │ Has clientserver: true
    4 │ Servername: /run/user/1000/nvim-lazyvim.23545.0
    5 │
    6 VimTeX project: UBC_CV
    7   base: UBC_CV.tex
    8   root: /home/weberam2/Dropbox/AssistantProf_BCCHRI/CV/LaTeX
    9   tex: /home/weberam2/Dropbox/AssistantProf_BCCHRI/CV/LaTeX/UBC_CV.tex
   10   main parser: current file verified
   11   document class: report
   12   packages: adjcalc adjustbox array atbegshi atbegshi-ltx atveryend atveryend-ltx auxhook bibentry bigintcalc bitset changepage collectbox color colortbl datetime2 enumitem epstop
   13   compiler: latexmk
   14     engine: -pdf
   15     options:
   16       -verbose
   17       -file-line-error
   18       -synctex=1
   19       -interaction=nonstopmode
   20     callback: 1
   21     continuous: 1
   22     executable: latexmk
   23     job:
   24       jobid: 27
   25       output: /tmp/nvim-lazyvim.weberam2/37Z1Ey/0
   26       cmd: max_print_line=2000 latexmk -verbose -file-line-error -synctex=1 -interaction=nonstopmode  -pdf -pvc -pvctimeout- -view=none -e '$compiling_cmd = ($compiling_cmd ? $com
   27       pid: 24007
   28   viewer: Zathura
   29     xwin id: 92274691
   30     cmd_start: zathura  -x "/usr/local/bin/nvim --headless -c \"VimtexInverseSearch %{line} '%{input}'\"" --synctex-forward 302:9:'/home/weberam2/Dropbox/AssistantProf_BCCHRI/CV/L
   31   qf method: LaTeX logfile
```

**Comment by lervag** [comment]
> I'm using the LazyVim config

I know _of_ this config, but I don't know any of the details as I don't use it.

> I keep getting this error when I save/compile:
> 
> ```
> Error detected while processing function <SNR>59_callback_nvim_output[8]..<SNR>59_check_callback[4]..vimtex#compiler#callback[38]..vimtex#qf#open:
> line   46:
> E5108: Error executing lua .../nvim-lazyvim/lazy/bufferline.nvim/lua/bufferline/ui.lua:119: attempt to call field 'is_list' (a nil value)
> stack traceback:
> > .../nvim-lazyvim/lazy/bufferline.nvim/lua/bufferline/ui.lua:119: in function 'get_component_size'
> ```

The error here is not really a VimTeX error, but a bufferline error. I don't use bufferline.nvim either, and so it's really hard to help.

The reason it appears to be a VimTeX error is because the 46th line of `vimtex#qf#open()` calls `:refresh`, which refreshes the statusline.

> Any ideas?

I would open an issue in the bufferline.nvim repo. I would think someone over there could help here.
