### ISSUE TITLE
ClassWarning is not detected

### ISSUE THREAD

**Issue by user202729** [lervag/vimtex#2950]
File:

```tex
%! TEX program = pdflatex
\documentclass{memoir}
\begin{document}
\fixpdflayout
\end{document}
```

In the log there is:

```
Class memoir Warning: As of 2018, \fixpdflayout\ is no longer used on input line 4.
```

But no error is reported.

(This is similar to
```
  setlocal errorformat+=%+WPackage\ %.%#\ Warning:\ %m\ on\ input\ line\ %l.
```
format but it's `Class` instead of `Package`, I think.)

(I have no idea what the command is for, just to demonstrate the issue.)

**Comment by lervag** [comment]
Thanks; I've updated accordingly.
