### ISSUE TITLE
Latexmk not running

### ISSUE THREAD

**Issue by thomasahle** [lervag/vimtex#296]
I'm running

    bash-3.2$ latexmk --version
    latex-mk version 2.1

On OSX, El Capitan.

I have an issue with latexmk not starting. I do `<leader>ll` and it tells me `latexmk compile: started continous mode`, but then I run it again, and it says the same thing. Or I run `<leader>lG` and I get the message `latexmk status: not running`.

The source of the errors appears to be that the command being run (according to `<leader>li`) uses the `-verbose` flag. When I try to run the command directly in bash I get

    bash-3.2$ cd ''/Users/...'' && max_print_line=2000 latexmk -verbose -pdf  -e ''$pdflatex =~ s/ / -file-line-error /'' -pvc -e ''$pdf_previewer = "/Applications/Skim.app/Contents/SharedSupport/displayline "'' ''filename.tex''
    unknown option: -verbose

In fact, most of the options from `man latexmk` don't seem to work. Only the options in `latexmk --help` don't give the `unknown option` error:

    OPTIONS
    -b, --bibtex      :  Force a run of bibtex even if there were no
  		       missing citations.
    --clean           :  Clean up various state files and log files used
		       by /usr/local/bin/latexmk.
    --debug           :  Enable verbose debugging output.
    -h, --help        :  Display this help message.
    --ignore-errors   :  Ignores any error codes from the various programs
		       which are run.
    --pdflatex        :  Use PDFLaTeX instead of LaTeX.
    --testlog logfile :  Log the actions taken by this script to the file
		       "logfile".  This is used as part of the regression
		       test suite and is primarily for developer use.
		       The exact format and contents of the log file are
		       subject to change without notification.
    --tex2page        :  Use TeX2Page instead of LaTeX.
    --version         :  Displays the version and exits.

Is this a well known problem? I haven't been able to find any other mentions of it.

**Comment by lervag** [comment]
Wow, you are running old software! The current version of latexmk is 4.43a. I don't know the date of version 2.1, but from [this](http://users.phys.psu.edu/~collins/software/latexmk-jcc/versions.html) page, it seems ancient!

I think I want to insist that you install a newer version. It should not be too hard. Since I have no experience with OSX, I will not be able to assist.

**Comment by thomasahle** [comment]
Oh, I thought from http://latex-mk.sourceforge.net/ that 2.1 was the latest version. Thank you!

**Comment by lervag** [comment]
Interesting. In any case, CTAN is also a good source for all things LaTeX, also [latexmk](https://www.ctan.org/pkg/latexmk/). I hope this solves your issue!

**Comment by thomasahle** [comment]
Apparently the bad version came from the `brew` package manager. In case anybody else runs into the same problem, the solution is to get MacTex from https://tug.org/mactex/mactex-download.html

**Comment by lervag** [comment]
Thanks for the info!
