### ISSUE TITLE
Vimtex doesnt boot

### ISSUE THREAD

**Issue by Puperger** [lervag/vimtex#2969]
### Description

Vimtex suddenly isnt working anymore, I cannot access any of the commands anymore and the healthcheck returns an error. I havent changed anything in my config files, which were working before

### Expected behavior

Vimtex should boot normally

### Actual behavior

Vimtex didnt start properly

### Do you use a latexmkrc file?

No

### VimtexInfo

```yaml
Cannot be ran, however here is the Checkhealth:


vimtex: health#vimtex#check
========================================================================
  - ERROR: Failed to run healthcheck for "vimtex" plugin. Exception:
    function health#check[20]..health#vimtex#check, line 3
    Vim(call):E5108: Error executing lua [string "v:lua"]:1: attempt to call field 'start' (a nil value)
    stack traceback:
    [string "v:lua"]:1: in main chunk
```

**Comment by lervag** [comment]
> Vimtex suddenly isnt working anymore, I cannot access any of the commands anymore and the healthcheck returns an error. I havent changed anything in my config files, which were working before

Which OS are you on, which version of Vim/Neovim?

**Comment by Puperger** [comment]
Im using Linux (Ubuntu) and running Neovim 0.9.0

**Comment by lervag** [comment]
Ok; next, how do you load VimTeX - what's your config for VimTeX?

**Comment by Puperger** [comment]
I'm using Vimplug to load the plugin and my config looks like this

```
"VimTEX
let g:vimtex_view_method= 'zathura'
let maplocalleader = ","
let g:tex_flavor='biblatex'
set conceallevel=2
let g:tex_conceal='abdmg'

let g:rainbow_active = 1 

let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \    '-shell-escape',
    \    '-verbose',
    \    '-file-line-error',
    \    '-synctex=1',
    \    '-interaction=nonstopmode',
    \ ],
    \}"let g:accordion_mode="h"


```

**Comment by lervag** [comment]
> I'm using Vimplug to load the plugin and my config looks like this …

Ok, well, you can simplify this immediately to this:

```viml
" These are NOT vimtex options - it may affect other plugins as well
let maplocalleader = ","
set conceallevel=2


let g:vimtex_view_method = 'zathura'
let g:vimtex_compiler_latexmk = {
    \ 'options' : [
    \    '-shell-escape',
    \    '-verbose',
    \    '-file-line-error',
    \    '-synctex=1',
    \    '-interaction=nonstopmode',
    \ ],
    \}
```

The `g:tex_...` options are not relevant if you use VimTeX.

But ok, I see nothing wrong with your config. But to be clear - there is no change in VimTeX that can explain your problem. You wrote:

> Vimtex suddenly isnt working anymore, I cannot access any of the commands anymore and the healthcheck returns an error. I havent changed anything in my config files, which were working before

I'm curious - do you remember what you _did_ change? E.g., did you do an update of your plugins?

---

After opening a `.tex` file, can you show the output of `:scriptnames`?

**Comment by Puperger** [comment]
I dont think I did update anything, but Im honestly not quite sure about it...

Heres the output of scriptnames
```


  1: /usr/share/nvim/runtime/ftplugin.vim
  2: /usr/share/nvim/runtime/indent.vim
  3: ~/.config/nvim/init.vim
  4: ~/.local/share/nvim/site/autoload/plug.vim
  5: /usr/share/nvim/runtime/filetype.lua
  6: ~/.vim/plugged/ultisnips/ftdetect/snippets.vim
  7: ~/.vim/plugged/vimtex/ftdetect/cls.vim
  8: ~/.vim/plugged/vimtex/ftdetect/tex.vim
  9: ~/.vim/plugged/vimtex/ftdetect/tikz.vim
 10: /usr/share/nvim/runtime/syntax/syntax.vim
 11: /usr/share/nvim/runtime/syntax/synload.vim
 12: ~/.vim/plugged/vim/colors/dracula.vim
 13: ~/.vim/plugged/vim/autoload/dracula.vim
 14: /usr/share/nvim/runtime/syntax/nosyntax.vim
 15: ~/.vim/plugged/rainbow/plugin/rainbow_main.vim
 16: ~/.vim/plugged/nerdtree/plugin/NERD_tree.vim
 17: ~/.vim/plugged/nerdtree/autoload/nerdtree.vim
 18: ~/.vim/plugged/nerdtree/lib/nerdtree/path.vim
 19: ~/.vim/plugged/nerdtree/lib/nerdtree/menu_controller.vim
 20: ~/.vim/plugged/nerdtree/lib/nerdtree/menu_item.vim
 21: ~/.vim/plugged/nerdtree/lib/nerdtree/key_map.vim
 22: ~/.vim/plugged/nerdtree/lib/nerdtree/bookmark.vim
 23: ~/.vim/plugged/nerdtree/lib/nerdtree/tree_file_node.vim
 24: ~/.vim/plugged/nerdtree/lib/nerdtree/tree_dir_node.vim
 25: ~/.vim/plugged/nerdtree/lib/nerdtree/opener.vim
 26: ~/.vim/plugged/nerdtree/lib/nerdtree/creator.vim
 27: ~/.vim/plugged/nerdtree/lib/nerdtree/flag_set.vim
 28: ~/.vim/plugged/nerdtree/lib/nerdtree/nerdtree.vim
 29: ~/.vim/plugged/nerdtree/lib/nerdtree/ui.vim
 30: ~/.vim/plugged/nerdtree/lib/nerdtree/event.vim
 31: ~/.vim/plugged/nerdtree/lib/nerdtree/notifier.vim
 32: ~/.vim/plugged/nerdtree/autoload/nerdtree/ui_glue.vim
 33: ~/.vim/plugged/nerdtree/nerdtree_plugin/exec_menuitem.vim
 34: ~/.vim/plugged/nerdtree/nerdtree_plugin/fs_menu.vim
 35: /usr/share/nvim/runtime/autoload/provider/clipboard.vim
 36: ~/.vim/plugged/nerdtree/nerdtree_plugin/vcs.vim
 37: ~/.vim/plugged/vim-devicons/nerdtree_plugin/webdevicons.vim
 38: ~/.vim/plugged/vim-devicons/plugin/webdevicons.vim
 39: ~/.vim/plugged/nvim-web-devicons/plugin/nvim-web-devicons.vim
 40: ~/.vim/plugged/coc.nvim/plugin/coc.vim
 41: ~/.vim/plugged/coc.nvim/autoload/coc/rpc.vim
 42: ~/.vim/plugged/coc.nvim/autoload/coc/util.vim
 43: ~/.vim/plugged/coc.nvim/autoload/coc/client.vim
 44: ~/.vim/plugged/ultisnips/plugin/UltiSnips.vim
 45: ~/.vim/plugged/ultisnips/autoload/UltiSnips/map_keys.vim
 46: ~/.vim/plugged/vim-indent-guides/plugin/indent_guides.vim
 47: ~/.vim/plugged/vim-indent-guides/autoload/indent_guides.vim
 48: ~/.vim/plugged/auto-pairs/plugin/auto-pairs.vim
 49: ~/.vim/plugged/vim-gitgutter/plugin/gitgutter.vim
 50: ~/.vim/plugged/vim-gitgutter/autoload/gitgutter/utility.vim
 51: ~/.vim/plugged/vim-gitgutter/autoload/gitgutter/highlight.vim
 52: ~/.vim/plugged/copilot.vim/plugin/copilot.vim
 53: ~/.vim/plugged/vim-accordion/plugin/accordion.vim
 54: ~/.vim/plugged/vim-lastplace/plugin/vim-lastplace.vim
 55: ~/.vim/plugged/vim-startify/plugin/startify.vim
 56: ~/.vim/plugged/nvim-spotify/plugin/nvim-spotify.vim
 57: /usr/share/nvim/runtime/autoload/remote/host.vim
 58: /usr/share/nvim/runtime/autoload/remote/define.vim
 59: ~/.vim/plugged/plenary.nvim/plugin/plenary.vim
 60: ~/.vim/plugged/vimtex/plugin/vimtex.vim
 61: ~/.vim/plugged/vim-latex/plugin/SyntaxFolds.vim
 62: ~/.vim/plugged/vim-latex/plugin/filebrowser.vim
 63: ~/.vim/plugged/vim-latex/plugin/imaps.vim
 64: ~/.vim/plugged/vim-latex/plugin/remoteOpen.vim
 65: ~/.vim/plugged/nvim-colorizer.lua/plugin/colorizer.vim
 66: ~/.vim/plugged/markdown-preview.nvim/plugin/mkdp.vim
 67: ~/.vim/plugged/vim-table-mode/plugin/table-mode.vim
 68: ~/.vim/plugged/hologram.nvim/plugin/hologram.vim
 69: /usr/share/nvim/runtime/plugin/gzip.vim
 70: /usr/share/nvim/runtime/plugin/health.vim
 71: /usr/share/nvim/runtime/plugin/matchit.vim
 72: /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 73: /usr/share/nvim/runtime/plugin/matchparen.vim
 74: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 75: /usr/share/nvim/runtime/plugin/rplugin.vim
 76: /usr/share/nvim/runtime/plugin/shada.vim
 77: /usr/share/nvim/runtime/plugin/spellfile.vim
 78: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 79: /usr/share/nvim/runtime/plugin/tohtml.vim
 80: /usr/share/nvim/runtime/plugin/tutor.vim
 81: /usr/share/nvim/runtime/plugin/zipPlugin.vim
 82: ~/.vim/plugged/telescope.nvim/plugin/telescope.lua
 83: /usr/share/nvim/runtime/plugin/man.lua
 84: ~/.vim/plugged/ultisnips/after/plugin/UltiSnips_after.vim
 85: ~/.vim/plugged/vimtex/ftplugin/tex.vim
 86: ~/.vim/plugged/vim-latex/ftplugin/tex_latexSuite.vim
 87: /usr/share/nvim/runtime/ftplugin/tex.vim
 88: ~/.vim/plugged/vimtex/after/ftplugin/tex.vim
 89: ~/.vim/plugged/vim-gitgutter/autoload/gitgutter.vim
 90: ~/.vim/plugged/copilot.vim/autoload/copilot.vim
 91: ~/.vim/plugged/copilot.vim/autoload/copilot/util.vim
 92: ~/.vim/plugged/coc.nvim/autoload/coc/highlight.vim
 93: ~/.vim/plugged/coc.nvim/autoload/coc/color.vim
 94: ~/.vim/plugged/copilot.vim/autoload/copilot/client.vim
 95: ~/.vim/plugged/copilot.vim/autoload/copilot/version.vim
 96: ~/.vim/plugged/copilot.vim/autoload/copilot/job.vim
 97: ~/.vim/plugged/coc.nvim/autoload/coc/window.vim
 98: ~/.vim/plugged/coc.nvim/autoload/coc/ui.vim
 99: ~/.vim/plugged/rainbow/autoload/rainbow_main.vim
100: ~/.vim/plugged/rainbow/autoload/rainbow.vim
101: ~/.vim/plugged/coc.nvim/autoload/coc/float.vim
102: ~/.vim/plugged/coc.nvim/autoload/coc/notify.vim
103: ~/.vim/plugged/copilot.vim/autoload/copilot/handlers.vim
104: ~/.vim/plugged/copilot.vim/autoload/copilot/logger.vim
105: ~/.vim/plugged/ultisnips/autoload/UltiSnips.vim
106: /usr/share/nvim/runtime/autoload/provider/python3.vim
107: /usr/share/nvim/runtime/autoload/provider/pythonx.vim
108: /usr/share/nvim/runtime/autoload/provider.vim
109: ~/.vim/plugged/coc.nvim/autoload/coc.vim
110: ~/.vim/plugged/vimtex/autoload/vimtex/complete.vim
111: ~/.vim/plugged/vimtex/autoload/vimtex/re.vim
112: ~/.vim/plugged/coc.nvim/autoload/coc/pum.vim
```

**Comment by Puperger** [comment]
Also maybe there is a chance LaTeX has a problem in general I guess, how could I quickly check in my terminal to see wheter or not it is working correctly?

**Comment by lervag** [comment]
> I dont think I did update anything, but Im honestly not quite sure about it...

Notice that _something_ clearly did change. And computers are not really alive, so _someone_ caused that change. Most likely, you did something - but if so, you were clearly not aware of it.

I think we'll figure it out.

> Heres the output of scriptnames …
> 
> ```
>   3: ~/.config/nvim/init.vim
>   4: ~/.local/share/nvim/site/autoload/plug.vim
>   6: ~/.vim/plugged/ultisnips/ftdetect/snippets.vim
>   7: ~/.vim/plugged/vimtex/ftdetect/cls.vim
>   8: ~/.vim/plugged/vimtex/ftdetect/tex.vim
>   9: ~/.vim/plugged/vimtex/ftdetect/tikz.vim
> ```

Ok, so, this shows that VimTeX is properly loaded as a plugin. Notice I removed some of the less interesting lines here - ignore that.

> ```
>  60: ~/.vim/plugged/vimtex/plugin/vimtex.vim
>  61: ~/.vim/plugged/vim-latex/plugin/SyntaxFolds.vim
>  62: ~/.vim/plugged/vim-latex/plugin/filebrowser.vim
>  63: ~/.vim/plugged/vim-latex/plugin/imaps.vim
>  64: ~/.vim/plugged/vim-latex/plugin/remoteOpen.vim
>  85: ~/.vim/plugged/vimtex/ftplugin/tex.vim
>  86: ~/.vim/plugged/vim-latex/ftplugin/tex_latexSuite.vim
> ```

This is a red flag! You seem to have installed LaTeX-Suite (aka vim-latex) as well; VimTeX does not work together with that plugin. Please disable either VimTeX or vim-latex.

> Also maybe there is a chance LaTeX has a problem in general I guess, how could I quickly check in my terminal to see wheter or not it is working correctly?

You can create a temporary directory, add a minimal LaTeX file, then compile it with `latexmk test.tex`.

**Comment by lervag** [comment]
Btw., notice that `:VimtexInfo` will only be available after you've opened a LaTeX file.

Also, regarding `:checkhealth` - you don't need capital C for it in neovim; I noticed that I made an update due to #2838. It may seem like neovim version 0.9 does not have the new `vim.health.start` API. But it shouldn't really be a problem for you, so let's ignore this for now.

**Comment by Puperger** [comment]
Ok, latexmk doesnt seem to be the problem then, it did compile a test file I made

Removing vim-latex also didnt change anything unfortunaely, but thanks for that hint nonetheless

**Comment by lervag** [comment]
Can you precisely explain the steps you use to test?

**Comment by lervag** [comment]
> When I open the same file in neovim with vimtex then I can run :checkhealth vimtex and this causes the message Ive shown earlier.

But I already said that you should not worry about `:checkhealth`:

> Also, regarding `:checkhealth` - you don't need capital C for it in neovim; I noticed that I made an update due to #2838. It may seem like neovim version 0.9 does not have the new `vim.health.start` API. But it shouldn't really be a problem for you, so let's ignore this for now.

After you open a tex file, what happens when you do `:VimtexInfo`?

**Comment by lervag** [comment]
To be more clear: `:checkhealth` may not work for you, but that's not a problem if VimTeX _does_ work. So just ignore it.

**Comment by Puperger** [comment]
Command returns that "command doesnt exist"

**Comment by lervag** [comment]
Ok; can you explain the steps you use? E.g.:

1. STart a terminal
2. `cd dir`
3. `nvim file.tex`
4. `:VimtexInfo`
5. observe "command doesnt exist"

**Comment by Puperger** [comment]
Its exactly that, yes

**Comment by lervag** [comment]
Ok; can you do steps 1 to 3, then `:scriptnames` - show me the output. This should mostly be the same as what you showed earlier.

Further, can you show me your actual configuration? Perhaps you already share it on github?

Next, can you ensure that you are using the latest version of VimTeX. Either use `:PlugUpdate` or

```sh
cd ~/.vim/plugged/vimtex/
git pull
```

**Comment by Puperger** [comment]
1: /usr/share/nvim/runtime/ftplugin.vim
  2: /usr/share/nvim/runtime/indent.vim
  3: ~/.config/nvim/init.vim
  4: ~/.local/share/nvim/site/autoload/plug.vim
  5: /usr/share/nvim/runtime/filetype.lua
  6: ~/.vim/plugged/ultisnips/ftdetect/snippets.vim
  7: ~/.vim/plugged/vimtex/ftdetect/cls.vim
  8: ~/.vim/plugged/vimtex/ftdetect/tex.vim
  9: ~/.vim/plugged/vimtex/ftdetect/tikz.vim
 10: /usr/share/nvim/runtime/syntax/syntax.vim
 11: /usr/share/nvim/runtime/syntax/synload.vim
 12: ~/.vim/plugged/vim/colors/dracula.vim
 13: ~/.vim/plugged/vim/autoload/dracula.vim
 14: /usr/share/nvim/runtime/syntax/nosyntax.vim
 15: ~/.vim/plugged/rainbow/plugin/rainbow_main.vim
 16: ~/.vim/plugged/nerdtree/plugin/NERD_tree.vim
 17: ~/.vim/plugged/nerdtree/autoload/nerdtree.vim
 18: ~/.vim/plugged/nerdtree/lib/nerdtree/path.vim
 19: ~/.vim/plugged/nerdtree/lib/nerdtree/menu_controller.vim
 20: ~/.vim/plugged/nerdtree/lib/nerdtree/menu_item.vim
 21: ~/.vim/plugged/nerdtree/lib/nerdtree/key_map.vim
 22: ~/.vim/plugged/nerdtree/lib/nerdtree/bookmark.vim
 23: ~/.vim/plugged/nerdtree/lib/nerdtree/tree_file_node.vim
 24: ~/.vim/plugged/nerdtree/lib/nerdtree/tree_dir_node.vim
 25: ~/.vim/plugged/nerdtree/lib/nerdtree/opener.vim
 26: ~/.vim/plugged/nerdtree/lib/nerdtree/creator.vim
 27: ~/.vim/plugged/nerdtree/lib/nerdtree/flag_set.vim
 28: ~/.vim/plugged/nerdtree/lib/nerdtree/nerdtree.vim
 29: ~/.vim/plugged/nerdtree/lib/nerdtree/ui.vim
 30: ~/.vim/plugged/nerdtree/lib/nerdtree/event.vim
 31: ~/.vim/plugged/nerdtree/lib/nerdtree/notifier.vim
 32: ~/.vim/plugged/nerdtree/autoload/nerdtree/ui_glue.vim
 33: ~/.vim/plugged/nerdtree/nerdtree_plugin/exec_menuitem.vim
 34: ~/.vim/plugged/nerdtree/nerdtree_plugin/fs_menu.vim
 35: /usr/share/nvim/runtime/autoload/provider/clipboard.vim
 36: ~/.vim/plugged/nerdtree/nerdtree_plugin/vcs.vim
 37: ~/.vim/plugged/vim-devicons/nerdtree_plugin/webdevicons.vim
 38: ~/.vim/plugged/vim-devicons/plugin/webdevicons.vim
 39: ~/.vim/plugged/nvim-web-devicons/plugin/nvim-web-devicons.vim
 40: ~/.vim/plugged/coc.nvim/plugin/coc.vim
 41: ~/.vim/plugged/coc.nvim/autoload/coc/rpc.vim
 42: ~/.vim/plugged/coc.nvim/autoload/coc/util.vim
 43: ~/.vim/plugged/coc.nvim/autoload/coc/client.vim
 44: ~/.vim/plugged/ultisnips/plugin/UltiSnips.vim
 45: ~/.vim/plugged/ultisnips/autoload/UltiSnips/map_keys.vim
 46: ~/.vim/plugged/vim-indent-guides/plugin/indent_guides.vim
 47: ~/.vim/plugged/vim-indent-guides/autoload/indent_guides.vim
 48: ~/.vim/plugged/auto-pairs/plugin/auto-pairs.vim
 49: ~/.vim/plugged/vim-gitgutter/plugin/gitgutter.vim
 50: ~/.vim/plugged/vim-gitgutter/autoload/gitgutter/utility.vim
 51: ~/.vim/plugged/vim-gitgutter/autoload/gitgutter/highlight.vim
 52: ~/.vim/plugged/copilot.vim/plugin/copilot.vim
 53: ~/.vim/plugged/vim-accordion/plugin/accordion.vim
 54: ~/.vim/plugged/vim-lastplace/plugin/vim-lastplace.vim
 55: ~/.vim/plugged/vim-startify/plugin/startify.vim
 56: ~/.vim/plugged/nvim-spotify/plugin/nvim-spotify.vim
 57: /usr/share/nvim/runtime/autoload/remote/host.vim
 58: /usr/share/nvim/runtime/autoload/remote/define.vim
 59: ~/.vim/plugged/plenary.nvim/plugin/plenary.vim
 60: ~/.vim/plugged/vimtex/plugin/vimtex.vim
 61: ~/.vim/plugged/nvim-colorizer.lua/plugin/colorizer.vim
 62: ~/.vim/plugged/markdown-preview.nvim/plugin/mkdp.vim
 63: ~/.vim/plugged/vim-table-mode/plugin/table-mode.vim
 64: ~/.vim/plugged/hologram.nvim/plugin/hologram.vim
 65: /usr/share/nvim/runtime/plugin/gzip.vim
 66: /usr/share/nvim/runtime/plugin/health.vim
 67: /usr/share/nvim/runtime/plugin/matchit.vim
 68: /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 69: /usr/share/nvim/runtime/plugin/matchparen.vim
 70: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 71: /usr/share/nvim/runtime/plugin/rplugin.vim
 72: /usr/share/nvim/runtime/plugin/shada.vim
 73: /usr/share/nvim/runtime/plugin/spellfile.vim
 74: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 75: /usr/share/nvim/runtime/plugin/tohtml.vim
 76: /usr/share/nvim/runtime/plugin/tutor.vim
 77: /usr/share/nvim/runtime/plugin/zipPlugin.vim
 78: ~/.vim/plugged/telescope.nvim/plugin/telescope.lua
 79: /usr/share/nvim/runtime/plugin/man.lua
 80: ~/.vim/plugged/ultisnips/after/plugin/UltiSnips_after.vim
 81: ~/.vim/plugged/vim-gitgutter/autoload/gitgutter.vim
 82: ~/.vim/plugged/copilot.vim/autoload/copilot.vim
 83: ~/.vim/plugged/copilot.vim/autoload/copilot/util.vim
 84: ~/.vim/plugged/coc.nvim/autoload/coc/highlight.vim
 85: ~/.vim/plugged/coc.nvim/autoload/coc/color.vim
 86: ~/.vim/plugged/vim-startify/autoload/startify.vim
 87: ~/.vim/plugged/vim-startify/autoload/startify/fortune.vim
 88: ~/.vim/plugged/vim-startify/syntax/startify.vim
 89: ~/.vim/plugged/rainbow/autoload/rainbow_main.vim
 90: ~/.vim/plugged/rainbow/autoload/rainbow.vim
 91: ~/.vim/plugged/copilot.vim/autoload/copilot/client.vim
 92: ~/.vim/plugged/copilot.vim/autoload/copilot/version.vim
 93: ~/.vim/plugged/copilot.vim/autoload/copilot/job.vim
 94: ~/.vim/plugged/coc.nvim/autoload/coc/window.vim
 95: ~/.vim/plugged/coc.nvim/autoload/coc/ui.vim
 96: ~/.vim/plugged/coc.nvim/autoload/coc/float.vim
 97: ~/.vim/plugged/coc.nvim/autoload/coc/notify.vim
 98: ~/.vim/plugged/copilot.vim/autoload/copilot/handlers.vim
 99: ~/.vim/plugged/copilot.vim/autoload/copilot/logger.vim
100: ~/.vim/plugged/vimtex/ftplugin/tex.vim
101: /usr/share/nvim/runtime/ftplugin/tex.vim
102: ~/.vim/plugged/vimtex/after/ftplugin/tex.vim
103: ~/.vim/plugged/vim-gitgutter/autoload/gitgutter/async.vim
104: ~/.vim/plugged/vim-gitgutter/autoload/gitgutter/debug.vim

Here is the output of scriptnames now..
Let me quickly ensure my github configs is on the latest version, I havent updated in quite some time now

**Comment by lervag** [comment]
Oh, sorry! I'm stupid and forgetful! The problem is simply that you are using a too old version of neovim.

**Comment by Puperger** [comment]
ah, that explains a lot :)

**Comment by lervag** [comment]
However, after you do `nvim test.tex`, you _should_ get an error that explains this.

**Comment by lervag** [comment]
https://github.com/lervag/vimtex/blob/0587a064f675fd85cdfb8a76d6a3ff698af3944b/ftplugin/tex.vim#L16-L23

**Comment by Puperger** [comment]
It works now, I guess I missed it because some plugin makes it dissapear quite quickly. Thanks for the help

**Comment by lervag** [comment]
No problem, and sorry for the confusion!
