### ISSUE TITLE
Continuous Compilation Hang

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#297]
Hey, Karl, I'm back. I'm having a weird issue that I'm hoping you will help me debug. I have compiled Vim myself (on Windows) and I have the following issue. 

----
###### Scenario 1
1) Start GVim (GUI version of Vim) from the command line: ```gvim```
2) Open a LaTeX file and start continuous compilation: ```\ll```
3) Compilation completes successfully and the compiled document is opened in the configured .PDF viewer.

---
###### Scenario 2
1) Start GVim (GUI version of Vim) by double-clicking the executable in the installation directory
2) Open a LaTeX file and start continuous compilation: ```\ll```
3) vimtex reports ```latekmk compile: started continuous mode```. Document never compiles. (```\lC``` also fails to clean any compile-related files that may exist in the working directory).

---

I'm not sure where the issue lies (Vim, Windows, vimtex). But, I was hoping you might be able to help me debug this. I have checked both scenarios for the existence of a ```v:servername``` variable. In both cases ```:echo v:servername``` returns ```GVIM```.

**Comment by lervag** [comment]
Ok, so the difference is how you start `GVim`, right?

I have a couple of suggestions:

1. With scenario 2: After step 3, please report the output of `\lo` (this should show the `latexmk` output in a new buffer).
2. With scenario 2: After step 3, please report whether you can stop the process with `\ll`.
3. With scenario 2: After step 3, please check the process manager in Windows and verify whether or not there is actually a latexmk process running. Also report output from `\li`.

**Comment by fuzzybear3965** [comment]
Yeah, that's exactly the difference.

1. ```\lo``` is an empty buffer. I kept it open while I toggled compilation and nothing was reported there.
2. I can definitely change the status of the continuous compilation using ```\ll```. But, it doesn't seem to change anything except for the words printed at the bottom of vim.
3. I checked the process manager. While a command line window is opened as soon as ```\ll``` starts continuous compilation, it closes quickly thereafter (to quickly for me to see what's happening). There is no ```latexmk``` process started. ```latexmk``` does appear in the process manager when following scenario 1.

**Comment by nasenatmer** [comment]
I don't know about the differences between starting an executable in windows and linux, but here in the Linux corner, some of the variables that might be necessary for certain programmes to work are inherited from the process that spawns the executable. That is: When I start `vim` from the commandline, `vim` inherits the variables from `zsh`. While if I start `vim` from the openbox-menu, it only inherits variables from `openbox-menu`.

But then I have no idea whether any of those variabels (is there such a think as `$PATH` on windows?) are needed for `vimtex` to work on Windows? But this was just a thought I had…

**Comment by lervag** [comment]
@fuzzybear3965 Does a `latexmk` process appear in the process manager when following scenario 2?

@nasenatmer Thanks for pitching in. I have had the same thought. I don't really know that much about Windows, and so I don't know how environment variables work there. But I do know that there are variables such as `PATH`.

@fuzzybear3965 Perhaps you could try to do `:echo $PATH` in both scenarios and see if there is a difference?

**Comment by fuzzybear3965** [comment]
@nasenatmer: That was a great idea. Windows definitely has a $PATH environment variable for the operating system. There may be other environment variables to consider checking but I don't know which ones vimtex considers/needs.

@lervag, I tried to address the issue of the latexmk process earlier but I guess it wasn't clear. So, vimtex "tries" to spawn a latexmk process, I think, because I can see a Windows command line window flash on the bottom of the screen (and I can see the spawned process in the process viewer). However, it disappears too quickly for me to see what's being executed and what error messages may/may not be appearing. It appears that, [in general](http://superuser.com/questions/306167/how-to-prevent-the-command-prompt-from-closing-after-execution) I can not keep the command prompt windows from closing. However, if I knew which command was being executed it may be possible to add a `` && pause `` to keep the command window open so that I could inspect it.

Do you know which line of vimtex would spawn the ``latexmk`` process so that I could add a ``pause`` statement?

**Comment by jbkopecky** [comment]
Hello Karl, I am back as well ! 

I have the same issues mentionned above.

It looks like `echo $PATH` gives the same output in gvim or in cmd vim.

However, I have tried to copy the latexmk command generated and run it myself in a cmd window.

from gvim:
```
cmd /s /c "cd /D "C:\Users\JKY\Dropbox\Administratif\CV" && set max_print_line=2000 & latexmk -verbose -pdf  -e "$pdflatex =~ s/ / -file-line-error /" -pvc -e "$success_cmd = ''\"C:\Program Files (x86)\Vim\vim74\gvim.exe\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e "$failure_cmd = ''\"C:\Program Files (x86)\Vim\vim74\gvim.exe\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previewer = ''SumatraPDF -reuse-instance''" "CVKopeckyEnTex.tex" >C:\Users\JKY\AppData\Local\Temp\VIAF2E6.tmp"
```

It fails to launch a latexmk process. It looks like the issue maybe is in the latexmk command string single quote nesting:

Indeed, when I replace the line 372 in autoload/vimtex/latexmk.vim

    return ' -e "$' . a:name . ' = ''' . a:value . '''"'

by

    return ' -e "$' . a:name . ' = '' . a:value . ''"'

(replacing `'''` by `''`)

the command works and a latexmk process is successfully created (from gvim and cmd vim).

The latexmk command generated by cmd vim is:
```
cmd /s /c "cd /D "C:\Users\JKY\Dropbox\Administratif\CV" && set max_print_line=2000 & latexmk -verbose -pdf  -e "$pdflatex =~ s/ / -file-line-error /" -pvc -e "$success_cmd = ''\"vim\" --servername VIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e "$failure_cmd = ''\"vim\" --servername VIM --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previewer = ''SumatraPDF -reuse-instance''" "CVKopeckyEnTex.tex" >C:\Users\JKY\AppData\Local\Temp\VIADDF0.tmp"
```

You can see that the success_cmd string is not the same than the one made by gvim, especially the way quotes are escaped, maybe this is why it works in cmd vim and not gvim !?

Should I try with a minimal vimrc ? Maybe this is not at all the source of the issue ?

**Comment by fuzzybear3965** [comment]
Hey, @jbkopecky, thanks for pitching in! I edited line 372 exactly as you suggested hoping that it would fix me up. No luck :(. But, the behavior did change. Now, the command window that exits too quickly still starts and exits too quickly. However, in addition to that, now. Each time I cycle vimtex to start continuous compilation an instance of Windows Explorer (Windows file manager) is opened in my home directory (``C:\Users\ John Rinehart``). I can't explain this. This only started occurring after I modified line 372 as you explained above. It seems like we're getting closer.

Howe did you obtain the latexmk command generated by gvim? I think it's in that command window that closes too quickly but, precisely for that reason, I can't tell what's going on.

**Comment by lervag** [comment]
@fuzzybear3965 The code the builds the command is inside `autoload/vimtex/latexmk.vim`. The command is executed from `vimtex#latexmk#compile()`, and the command is built in `s:latexmk_build_cmd()`. You should be able to add the `&& pause` by looking into this latter function.

It is interesting to note that the problem is not due to varying paths. Perhaps there are other environment variables?

@fuzzybear3965 and @jbkopecky: It seems like the actual command that is run is different in the two scenarios. Could you check this specifically, i.e. run both scenarios and copy the command string here (found through `:VimtexInfo` or `\li`.

@jbkopecky The fix you're suggesting "shouldn't" work. I don't know why it does for you. The reason there are three quotes is because the first two represent an escaped quote character.

**Comment by fuzzybear3965** [comment]
Okay, I managed to add the ``&& pause`` to the command. That wasn't too bad. I also added a ``\K`` switch to keep the command window from closing. Both additions/editions had no effect on the compilation. Below is the command string found from the output of ``\li`` for scenario 1 (working case):
```
  cmd_latexmk_compile : 'cmd /s /k "cd /D "C:/Users/John Rinehart" && set max_print_line=2000 & latexm
k -verbose -pdf  -e "$pdflatex =~ s/ / -file-line-error /" -pvc -e "$success_cmd = ''\"gvim\" --server
name GVIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e "$failure_cmd = ''\"gvim\" --servername
 GVIM --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previewer = ''SumatraPDF ''" "test.te
x" >C:/Users/JOHNRI~1/AppData/Local/Temp/VIAFD6F.tmp" && pause'
```
Below is the command string obtained from the output of ``\li`` in the case of scenario 2.
```
  cmd_latexmk_compile : 'cmd /s /k "cd /D "C:/Users/John Rinehart" && set max_print_line=2000 & latexm
k -verbose -pdf  -e "$pdflatex =~ s/ / -file-line-error /" -pvc -e "$success_cmd = ''\"C:\Program File
s (x86)\vim\gvim.exe\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e "$failur
e_cmd = ''\"C:\Program Files (x86)\vim\gvim.exe\" --servername GVIM --remote-expr \"vimtex\#latexmk\#c
allback(0)\"''" -e "$pdf_previewer = ''SumatraPDF ''" "test.tex" >C:/Users/JOHNRI~1/AppData/Local/Temp
/VIAE083.tmp" && pause'  
```

What's strange is the addition of that ``\`` to the path name. It's interesting that in the different cases the path to ``gvim.exe`` is different. In the second case the entire path is used. In the first case it is assumed that ``gvim.exe`` is on the ``$PATH`` (which it is).

**Comment by fuzzybear3965** [comment]
I'm sorry to double-post, but this is more of a "solution" post than it is a "debug" post. I have moved my Vim installation folder to a path with no spaces ``C:\vim\gvim.exe``. When I start this, now, I have the following as the ``cmd_latexmk_compile`` variable: 
```
  cmd_latexmk_compile : 'cmd /s /k "cd /D "C:/Users/John Rinehart" && set max_pr
int_line=2000 & latexmk -verbose -pdf  -e "$pdflatex =~ s/ / -file-line-error /"
 -pvc -e "$success_cmd = ''\"C:\vim\gvim.exe\" --servername GVIM1 --remote-expr
\"vimtex\#latexmk\#callback(1)\"''" -e "$failure_cmd = ''\"C:\vim\gvim.exe\" --s
ervername GVIM1 --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previ
ewer = ''SumatraPDF ''" "test.tex" >C:/Users/JOHNRI~1/AppData/Local/Temp/VIA9931
.tmp" && pause' 
```
Note the lack of spaces in the path name. Now, compilation works great! So, what do I need to do, @lervag?

**Comment by lervag** [comment]
Strange. It seems the problem might be the escaping of spaces in the Vim program path. The relevant code is found in `s:latexmk_build_cmd` close to line [422](https://github.com/lervag/vimtex/blob/master/autoload/vimtex/latexmk.vim#L422). As you see, I've added `\" ... \"` to surround the progname, and I thought this should be enough. Unfortunately, it seems it is not.

Let me know if you find a working solution.

**Comment by jbkopecky** [comment]
@lervag Ok, my bad.

@fuzzybear3965, It indeed works when setting g:vimtex_latexmk_progname to a path without spaces.

It seems that the issue is the space in "Program Files (x86)" names ? 

I have tried to escape these spaces like so: "Program\ Files\ (x86)" and run the command manually in cmd without success...

**Comment by lervag** [comment]
Could you try [this](https://superuser.com/questions/279008/how-do-i-escape-spaces-in-command-line-in-windows-without-using-quotation-marks)? That is, use caret symbols to escape: `^`.

**Comment by jbkopecky** [comment]
No luck Either.

Here is the total command output:
```
C:\Users\JKY>cmd /s /c "cd /D "C:\Users\JKY\Dropbox\Administratif\CV" && set max_print_line=2000 & latexmk -verbose -pdf  -e "$pdflatex =~ s/ / -file-line-error /" -pvc -e "$success_cmd = ''
\"C:\Program^ Files^ (x86)\Vim\vim74\gvim.exe\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e "$failure_cmd = ''\"C:\Program^ Files^ (x86)\Vim\vim74\gvim.exe\" --ser
vername GVIM --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previewer = ''SumatraPDF -reuse-instance''" "CVKopeckyEnTex.tex" >C:\Users\JKY\AppData\Local\Temp\VIAF2E6.tmp"
Bareword found where operator expected at (eval 11) line 1, near "''C"
        (Missing operator before C?)
Latexmk: Stopping because executing following code from command line
    $success_cmd = ''C:\Program
gave an error:
    syntax error at (eval 11) line 1, near "''C"
```

**Comment by lervag** [comment]
Strange... Could you try to remove the `\` signs (I've used them to escape the quotes inside quotes, but perhaps that's not necessary on windows?). And could you try to move the last quote to before the extension, i.e. use `"C:\Program Files (x86)\Vim\vim74\gvim".exe`.

**Comment by jbkopecky** [comment]
Like this ? Doesn't seem to work

```
C:\Users\JKY>cmd /s /c "cd /D "C:\Users\JKY\Dropbox\Administratif\CV" && set max_print_line=2000 & latexmk -verbose -pdf  -e "$pdflatex =~ s/ / -file-line-error /" -pvc -e "$success_cmd = ''
"C:\Program Files (x86)\Vim\vim74\gvim".exe --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e "$failure_cmd = ''"C:\Program Files (x86)\Vim\vim74\gvim".exe --servername
GVIM --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previewer = ''SumatraPDF -reuse-instance''" "CVKopeckyEnTex.tex" >C:\Users\JKY\AppData\Local\Temp\VIAF2E6.tmp"
Bareword found where operator expected at (eval 11) line 1, near "''C"
        (Missing operator before C?)
Latexmk: Stopping because executing following code from command line
    $success_cmd = ''C:\Program
gave an error:
    syntax error at (eval 11) line 1, near "''C"
```

The same command with `^` does not work.

**Comment by jbkopecky** [comment]
I have also tried all sorts of combinations of quotes escape `''\"`, `''"`, `'"`, ...
Without success.

**Comment by lervag** [comment]
Sigh, why is stuff so difficult on windows? :P

Right now I don't have any more ideas, unfortunately. If I understand correctly, everything works as expected if you simply use `gvim.exe`, right? What is the output?

**Comment by jbkopecky** [comment]
I have no idea why this is so cumbersome.

It works when I put a shorcut of gvim.exe in my home folder (no spaces in path).

It might also work if we simply put g:vimtex_latexmk_progname='gvim' with the gvim exe in path ?

**Comment by lervag** [comment]
Can you try that? That is, set `g:vimtex_latexmk_progname = "gvim"` (or `"gvim.exe"`)?

**Comment by jbkopecky** [comment]
Yeah, works like a charm.

```
b:vimtex : CVKopeckyEnTex
  pid : 7356
  tmp : 'C:\Users\JKY\AppData\Local\Temp\VIA4CDA.tmp'
  root : 'C:\Users\JKY\Dropbox\Administratif\CV'
  aux : 'C:\Users\JKY\Dropbox\Administratif\CV/CVKopeckyEnTex.aux'
  log : 'C:\Users\JKY\Dropbox\Administratif\CV/CVKopeckyEnTex.log'
  out : 'C:\Users\JKY\Dropbox\Administratif\CV/CVKopeckyEnTex.pdf'
  tex : 'C:\Users\JKY\Dropbox\Administratif\CV\CVKopeckyEnTex.tex'
  cmd_latexmk_compile : 'cmd /s /c "cd /D "C:\Users\JKY\Dropbox\Administratif\CV" && set max_print_line=2000 & latexmk -verbose -pdf  -e "$pdflatex =~ s/ / -file-line-error /" -pvc -e "$success_cmd = ''\"gvim\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e "$failure_cmd = ''\"gvim\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previewer = ''SumatraPDF -reuse-instance''" "CVKopeckyEnTex.tex" >C:\Users\JKY\AppData\Local\Temp\VIA4CDA.tmp"'
  base : 'CVKopeckyEnTex.tex'

  viewer
    init : function('13')
    view : function('14')
    latexmk_append_argument : function('15')
```

**Comment by lervag** [comment]
Great! Then at least we have a fix. Can you verify that this also works for you, @fuzzybear3965?

**Comment by fuzzybear3965** [comment]
Yep, that works great! I also tried to play around with the escaped quotes and back slashes and caret symbols before all of your guys' back and forth. I failed, too. I think the best option is to include in the installation instructions that ``vim`` or ``gvim`` must be on the user's path and just change the ``g:vimtex_latexmk_progname``variable to be assigned the program name (i.e. ``vim.exe`` or ``gvim.exe``) and not also include the entire path leading up to and including the program name. 

If you could assign ``v:progname`` and assign it to (or replace it with) ``g:vimtex_latexmk_progname`` I think that would be best. Actually, it seems that ``g:vimtex_latexmk_progname`` isn't aptly named in that it is not storing the name of the program, but also the entire path leading up to the program name. Also, it seems to be storing not the name of the ``latexmk`` program but the name of ``vim`` (or ``gvim``, in our case).

I tried changing a bit of this stuff on my own but I don't know the semantics or syntax of VimScript/Viml at all. I'm now thinking that it might be worth my time to learn a little. I want my own pull request!

**Comment by lervag** [comment]
@fuzzybear3965 Actually, as said in the docs, `g:vimtex_latexmk_progname` is by default set to `v:progpath` if this is available, and to `v:progname` if not. The idea was that `v:progpath` is more general than `v:progname`. Further, the idea is that most users should not need to change `g:vimtex_latexmk_progname`. Therefore, perhaps it would be better to let the option by default be set to `v:progname`, not `v:progpath`.

Could you please check what the variables `v:progname` and `v:progpath` are set to both scenarios?

And yes, I would suggest you learn som vimscript. I actually find it quite nice (although it might be due to some form of the Stockholm syndrome... who knows?).

Btw: You can not change `v:progname`, it is an internal variable.

Btw 2: The naming scheme of the options is based on the modules, i.e. `g:vimtex_latexmk_progname` : the first part says that the option lives in `vimtex/latexmk.vim`.

**Comment by jbkopecky** [comment]
Yes, I don't think there is any need to push anything ? g:vimtex_latexmk_progname is a usefull fix in .local.vimrc ...

**Comment by lervag** [comment]
I won't update the default value, since I think it will break things for other people (cf. #186). So I'll consider this issue resolved, unless something else comes up.

**Comment by fuzzybear3965** [comment]
Hey, @lervag and @jbkopecky, sorry for taking so long to respond.

```echo v:progname``` returns ```gvim.exe```
```echo v:progpath``` returns ```C:\Program Files (x86)\vim\gvim.exe```

I agree, I think you should leave the default value as it is, considering issue #186. I have added ```let g:vimtex_latexmk_progname='gvim'``` to my ```vimrc``` file. Everything works smoothly, now.

Yeah, I definitely didn't understand what was happening before. I understand, now, what happened and that no commit/change to the codebase is necessary. Thanks, you guys.

**Comment by lervag** [comment]
No problem, @fuzzybear3965. And I'm happy that you're satisfied with the solution.
