### ISSUE TITLE
Order of environments with `]]`

### ISSUE THREAD

**Issue by eolianoe** [lervag/vimtex#298]
When trying to close the following environment with `]]`:
```latex
\begin{equation}
  \left\{
    \begin{array}
```
vimtex closes the left with a right, then the array and finally the equation environment to get:
```latex
\begin{equation}
  \left\{
    \begin{array}
    \right\}
  \end{array}
\end{equation}
```
whereas the correct order should be, first the array, then the right and finally the equation : 
```latex
\begin{equation}
  \left\{
    \begin{array}
    \end{array}
  \right\}
\end{equation}
```

Is it a normal behaviour?

**Comment by lervag** [comment]
Thanks, should be fixed now.
