### ISSUE TITLE
Feature request: support apastyle prenotes

### ISSUE THREAD

**Issue by engeir** [lervag/vimtex#2981]
**Is your feature request related to a problem? Please describe it.**

[apacite](https://ctan.org/pkg/apacite) uses `\cite` and `\citeA` for parenthesis and in-text citation, and `<>` and `[]` for prenotes and postnotes. The prenotes syntax breaks the suggestion list / completion that normally shows all available references when typing `\cite<prenote>{author...}`.

**Describe the solution you'd like**

It would be great if the `<>` prenotes were supported and worked similarly to the more standard `\cite[prenotes]{author...}` format, which does give completion suggestions on available `author...`s.

**Describe alternatives you've considered**

For the syntax highlighting to work, I added

```vim
syntax match texCmdRef nextgroup=texRefOpt,texRefArg skipwhite skipnl "\\[Ee]dcite[pt]\?\>\*\?"
syntax match texCmdRef nextgroup=texRefOpt,texRefArg skipwhite skipnl "\\[Tt]ranscite[pt]\?\>\*\?"
syntax match texCmdRef nextgroup=texRefOpt,texRefArg skipwhite skipnl "\\citeA[pt]\?\>\*\?"
```

So the highlighting is correct in the tex source files, but completion is missing.

**Comment by lervag** [comment]
Please update and test; I believe I've added support for the main features, but I may have missed something.

**Comment by engeir** [comment]
Thank you. The completion source works just like expected now.

The syntax highlighting of `\citeA[author2024}` and `\cite<prenotes>{author2024}` is not showing up the same as the standard `\cite{author2024}`, but I am not sure how to properly test the syntax highlighting in a correct way, isolated from other plugins I have that might interfere. So im not really sure if it is my setup or vimtex that is causing them to be different.

I used the command `nvim -u mini.lua main.tex` to test, where `mini.lua` contain:

<details>
<summary>mini.lua</summary>
<br>

```lua
-- Bootstrap lazy.nvim
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not (vim.uv or vim.loop).fs_stat(lazypath) then
    local lazyrepo = "https://github.com/folke/lazy.nvim.git"
    local out = vim.fn.system({ "git", "clone", "--filter=blob:none", "--branch=stable", lazyrepo, lazypath })
    if vim.v.shell_error ~= 0 then
        vim.api.nvim_echo({
            { "Failed to clone lazy.nvim:\n", "ErrorMsg" },
            { out, "WarningMsg" },
            { "\nPress any key to exit..." },
        }, true, {})
        vim.fn.getchar()
        os.exit(1)
    end
end
vim.opt.rtp:prepend(lazypath)

-- Make sure to setup `mapleader` and `maplocalleader` before
-- loading lazy.nvim so that mappings are correct.
-- This is also a good place to setup other settings (vim.opt)
vim.g.mapleader = " "
vim.g.maplocalleader = "\\"

-- Setup lazy.nvim
require("lazy").setup({
    spec = {
        -- add your plugins here
        {
            "lervag/vimtex",
            lazy = false, -- we don't want to lazy load VimTeX
            -- tag = "v2.15", -- uncomment to pin to a specific release
            init = function()
                -- VimTeX configuration goes here, e.g.
                vim.g.vimtex_view_method = "zathura"
            end,
        },
    },
    -- automatically check for plugin updates
    checker = { enabled = true },
})
```

</details>

<details>
<summary>Screenshot</summary>
<br>

![mini](https://github.com/user-attachments/assets/1a052312-43f3-4c72-b252-230a851aacc9)

</details>

**Comment by lervag** [comment]
That's strange. Here's how it looks for me:

![image](https://github.com/user-attachments/assets/f0fd128a-93d5-4b0b-8cb3-4ac0636e0cff)

I'm curious, how does your LaTeX file look? Can you create a minimal example? I suspect the problem is that VimTeX does not recognize that you are using the `apacite` package.

**Comment by engeir** [comment]
Okay, I think I see what caused the issue, although I didn't think it would make a difference. 

I was compiling with

```sh
tectonic -X compile ./main.tex --keep-logs --keep-intermediates
```

and not `<localleader>ll`, ie vimtex.

- When using vimtex to compile, highlighting start working if it was not working before compilation (with or without specifying `\usepackage{apacite}`).
- When explicitly setting `\usepackage{apacite}` highlighting works immediately.

What I do not understand is that if I first compile with vimtex, close and re-open nvim, highlighting still works (i.e., no need to compile again after re-open). But maybe this has to do with the other auxiliary files created during compilation?

This tex file recreates the same highlighting issues as above:

```tex
\documentclass[draft]{agujournal2019}

\begin{document}

\cite{lehner2016,bronnimann2019}
\citeA{timmreck2024}
\cite<e.g.~>{guo2004,timmreck2018}

\bibliography{/home/een023/science/ref/ref}

\end{document}
```

where the class file include the apacite package. It is the same as used in [this template](https://www.overleaf.com/latex/templates/agu-jgr-atmospheres-agutex-article/bwqjbhmdyvyg).

**Comment by lervag** [comment]
> I was compiling with
> 
> ```shell
> tectonic -X compile ./main.tex --keep-logs --keep-intermediates
> ```
> 
> and not `<localleader>ll`, ie vimtex.

Ah, yes. Well, that is _part_ of it.

VimTeX loads syntax packages based on the recognized packages from the preamble. However, LaTeX loads packages "recursively", so it is not enough to just parse the preamble. But when you compile a document, latex creates a `.fls` file that lists the packages.

If you use latexmk from VimTeX, then we attach a callback that notifies VimTeX that the `.fls` file is created/updated, which makes it possible to update the package list and load the extra syntax package dynamically. When you instead compile the document "on the side", then there is no such automatic/dynamic loading. However, you _could_ reload VimTeX with `\lx`.

I think the above also explains the behaviour you see. When you open a clean uncompiled document, it may not highlight everything properly. If you open a document that was already compiled, the highlighting will be as expected.

Notice, this is explained in the docs if you read `:help vimtex-syntax`. ;)

**Comment by lervag** [comment]
> I was compiling with
> 
> ```shell
> tectonic -X compile ./main.tex --keep-logs --keep-intermediates
> ```
> 
> and not `<localleader>ll`, ie vimtex.

Ah, yes. Well, that is _part_ of it.

VimTeX loads syntax packages based on the recognized packages from the preamble. However, LaTeX loads packages "recursively", so it is not enough to just parse the preamble. But when you compile a document, latex creates a `.fls` file that lists the packages.

If you use latexmk from VimTeX, then we attach a callback that notifies VimTeX that the `.fls` file is created/updated, which makes it possible to update the package list and load the extra syntax package dynamically. When you instead compile the document "on the side", then there is no such automatic/dynamic loading. However, you _could_ reload VimTeX with `\lx`.

I think the above also explains the behaviour you see. When you open a clean uncompiled document, it may not highlight everything properly. If you open a document that was already compiled, the highlighting will be as expected.

Notice, this is explained in the docs if you read `:help vimtex-syntax`. ;)
