### ISSUE TITLE
Treat semiverbatim as verbatim

### ISSUE THREAD

**Issue by MithicSpirit** [lervag/vimtex#3000]
**Is your feature request related to a problem? Please describe it.**
The semiverbatim environment (similar to verbatim, but \\, {, and } preserve their normal meaning) provided by beamer is treated as regular LaTeX code, which leads to annoying formatting issues and subpar syntax highlighting.

**Describe the solution you'd like**
semiverbatim should just be treated as regular verbatim by vimtex.

**Comment by MithicSpirit** [comment]
woah, this is exactly issue number 3000. I suppose now is a good time to thank you for all your work!

**Comment by lervag** [comment]
> **Is your feature request related to a problem? Please describe it.** The semiverbatim environment (similar to verbatim, but \, {, and } preserve their normal meaning) provided by beamer is treated as regular LaTeX code, which leads to annoying formatting issues and subpar syntax highlighting.

Could you provide an example or two of this that I can use for testing?

> woah, this is exactly issue number 3000.

🎊

> I suppose now is a good time to thank you for all your work!

💝

**Comment by MithicSpirit** [comment]
> Could you provide an example or two of this that I can use for testing?
```tex
\documentclass{beamer}

\begin{document}
\begin{frame}[fragile]
\begin{semiverbatim}
int main() \{
  \uncover<2->{return 0;}
\}
\end{semiverbatim}
\end{frame}
\end{document}
```
Try formatting/indenting the lines inside the semiverbatim environment.

**Comment by lervag** [comment]
There, I think it should work as expected now.
