### ISSUE TITLE
Add unicode-math support for \sym- style command

### ISSUE THREAD

**Issue by One-In-Dark** [lervag/vimtex#3004]
**Is your feature request related to a problem? Please describe it.**
There's no way to add conceal for unicode-math standard commands `\symbb` etc. even by #1972 custom conceal methods.

**Describe the solution you'd like**
For the simplicity of implementation, I would like the corresponding commands (e.g. `\symbb` to `\mathbb`, `\symit` to `\mathit`) to be concealed alike. Maybe in a individual syntax package for `unicode-math`.

**Describe alternatives you've considered**
A more general way is to allow users to add this correspondence manually, as is mentioned in the previous issue.

**Additional Info**
The `unicode-math` package commands:
![image](https://github.com/user-attachments/assets/68cd10f6-3c65-47b8-98f9-1836db1274b4)

**Comment by lervag** [comment]
> For the simplicity of implementation, I would like the corresponding commands (e.g. `\symbb` to `\mathbb`, `\symit` to `\mathit`) to be concealed alike. Maybe in a individual syntax package for `unicode-math`.

Ok, sounds reasonable. It would be a great help if you can create a table of examples, preferably with the first column being the typed commands and the second column showing or explaining how it should look.

The image you posted seems to indicate that this is really just adding synonyms to existing commands according to this table:

Command       | Synonym
---           | ---
`\symnormal`  | `\mathnormal`
`\symliteral` |
`\symbfsf`    | `\mathbfsf`
`\symbfup`    | `\mathbfup`
`\symbfit`    | `\mathbfit`
`\symbb`      | `\mathbb`
`\symbbit`    | `\mathbbit`
`\symcal`     | `\mathcal`
`\symbfcal`   | `\mathbfcal`
`\symsecr`    | `\mathscr`
`\symbfser`   | `\mathbfscr`
`\symfrak`    | `\mathfrak`
`\symbffrak`  | `\mathbffrak`
`\symsfup`    | `\mathsfup`
`\symbfsfup`  | `\mathbfsfup`
`\symsfit` | `\mathsfit`
`\symbfsfit` | `\mathbfsfit`

But it is unclear how `\symliteral` should behave, and I also don't think we currently support all of those `\math…` variants.

> A more general way is to allow users to add this correspondence manually, as is mentioned in the previous issue.

It's hard for me to comment this without fully understanding what you want. If you provide the examples I'm asking for it will be easier to fully understand and then considering the options for solving this.

**Comment by One-In-Dark** [comment]
Thanks for the timely reply!

> The image you posted seems to indicate that this is really just adding synonyms to existing commands according to this table:

Yes indeed, despite 2 typos (I've marked them with `!`). These commands work just as their name suggests.

Five "standard" commands are missed by me. I've added them now.
| Command        | Synonym       | Eg    |
| -------------- | ------------- | ----- |
| `\symnormal`   | `\mathnormal` |       |
| `\symbfsf`     | `\mathbfsf`   | 𝘼     |
| `\symbfup`     | `\mathbfup`   |       |
| `\symbfit`     | `\mathbfit`   | 𝑨     |
| `\symbb`       | `\mathbb`     |       |
| `\symbbit`     | `\mathbbit`   | ⅅⅆⅇⅈⅉ |
| `\symcal`      | `\mathcal`    |       |
| `\symbfcal`    | `\mathbfcal`  | 𝓐     |
| `\symsecr`(!)  | `\mathscr`    |       |
| `\symbfser`(!) | `\mathbfscr`  | 𝓐     |
| `\symfrak`     | `\mathfrak`   |       |
| `\symbffrak`   | `\mathbffrak` | 𝕬     |
| `\symsfup`     | `\mathsfup`   | 𝖠𝖡𝖼𝖽  |
| `\symbfsfup`   | `\mathbfsfup` | 𝗔     |
| `\symsfit`     | `\mathsfit`   | 𝘈𝘉𝘤𝘥  |
| `\symbfsfit`   | `\mathbfsfit` | 𝘼     |
| Missed         |               |       |
| `\symbf`       | `\mathbf`     |       |
| `\symit`       | `\mathit`     |       |
| `\symup`       | `\mathup`     |       |
| `\symsf`       | `\mathsf`     |       |
| `\symtt`       | `\mathtt`     |       |

> I also don't think we currently support all of those \math… variants.

I cannot find unicode of all variants, either. :cry: For those variants I can only find unicode character `A`.

> But it is unclear how \symliteral should behave

![image](https://github.com/user-attachments/assets/b304049d-ab8c-4540-8d6b-a66aaa3c7d6c)

Given that LaTeX will convert some stylish variant of characters to other styles (seemingly so).

I don't know how it should be seen as some style… maybe we could leave it un-concealed?

**Comment by One-In-Dark** [comment]
> A more general way is to allow users to add this correspondence manually, as is mentioned in the previous issue.

Sorry for vagueness. For example if no exact `\symbbit` unicode concealing is applicable, maybe it's a good idea to allow users to define it to resemble `\mathbb`(`\symbb`)?

**Comment by One-In-Dark** [comment]
BTW I would appreciate it if some more commands provided by `unicode-math` can be added, as a syntax package:

| Command      | Conceal |
| ------------ | ------- |
| `\increment` | `∆`     |
| `\mbfnabla`  | `𝛁`     |

**Comment by lervag** [comment]
Sorry for the delay, busy days here.

Now, my understanding is that we want to add support for the `unicode-math` package such that the following commands will work similarly to their synonyms in the following table. I'm only including the commands whose synonyms are actually handled by VimTeX as of now:

Command 	Synonym 	Eg
`\symbb` 	`\mathbb` 	𝔸
`\symfrak` 	`\mathfrak` 	𝔄
`\symcal` 	`\mathcal` 	𝓐
`\symsecr` 	`\mathscr` 	𝓐
`\symbf` 	`\mathbf` 	bold font
`\symit` 	`\mathit` 	italic font

In addition, I'll add the conceals you mention for `\increment → ∆` and `\mbfnabla → 𝛁`.

We may want to extend things beyond this as well, but let's start here. Ok? If we extend, then we might want to also extend the support for the `\math…` variants first.

Is this OK, at least as a start?

> > A more general way is to allow users to add this correspondence manually, as is mentioned in the previous issue.
> 
> Sorry for vagueness. For example if no exact `\symbbit` unicode concealing is applicable, maybe it's a good idea to allow users to define it to resemble `\mathbb`(`\symbb`)?

Hmm, yes, but I think it is more work than I want to do right now. It is easier to instead add partial support that benefits all.

**Comment by lervag** [comment]
> > Is this OK, at least as a start?
> 
> Yes, thanks for the consideration! Maybe adding the support of `\symbfit` can be easily done as well, since `g:vimtex_syntax_custom_cmds` has the similar functionality?

Yes, ok - I'll add both variants then.

**Comment by lervag** [comment]
Can you update and test how things work for you now?

**Comment by One-In-Dark** [comment]
> Can you update and test how things work for you now?

Working perfectly. Greatly impressed for your remarkable efficiency!

**Comment by lervag** [comment]
Great, very glad to hear it! :)

**Comment by One-In-Dark** [comment]
As time went by, I've found myself willing more concealing! Providing only two concealing proves to be short-sighted, stupid me!

| Command              | Conceal  |
| -------------------- | -------- |
| `\mathhyphen`        | `‐`      |
| `\mathstraightquote` | `'`      |
| `\mathbacktick`      | backtick |
|                      |          |
| `\slash`             | `/`      |
| `\fracslash`         | `⁄`      |
| `\divslash`          | `∕`      |
| `\reversesolidus`    | `⧵`      |

| Command          |      |      | Command          |
| ---------------- | ---- | ---- | ---------------- |
| `\cdotp`         | `·`  |      |                  |
| `\vysmblkcircle` | `∙`  | `∘`  | `\vysmwhtcircle` |
| `\smblkcircle`   | `•`  | `◦`  | `\smwhtcircle`   |
| `\mdsmblkcircle` | `⦁`  | `⚬`  | `\mdsmwhtcircle` |
| `\mdblkcircle`   | `⚫` | `⚪` | `\mdwhtcircle`   |
| `\mdlgblkcircle` | `●`   | `○` | `\mdlgwhtcircle` |
| `\lgblkcircle`   | `⬤`  | `◯` | `\lgwhtcircle` |

**Comment by lervag** [comment]
I believe the latest update should provide this; please update and test.

**Comment by One-In-Dark** [comment]
> I believe the latest update should provide this; please update and test.

Thanks for the consideration!

There's one strange behaviour: concealing of `\symbfit` is lost, after being updated to commit ded1d89.

Initial commit fcbaf6 works fine.

**Environment**

`:VimtexInfo` just throw an error: `Assertion failed: ch_len == (size_t)(ch ? utf_ptr2len(p) : 1), file D:\a\neovim\neovim\src\nvim\eval\decode.c, line 380`.

I'm using Neovim nightly (v0.11.0-dev-783+g0ade8fed1) on MS-Windows11 23H2 22631.4317.
