### ISSUE TITLE
Custom syntax highlighting for spacing

### ISSUE THREAD

**Issue by Felipe-9** [lervag/vimtex#3020]
<details><summary>
Following #3010

</summary>

> Well, yes and no. \, is matched with the texSpecialChar group, and you can customize how this looks on your end. See :help vimtex-syntax-core if you want some relevant docs on these things. I've tried to provide good references for how to customize your colorschemes and I've tried to explain the base core groups.

> However, texSpecialChar includes a lot of things, and so I am not sure if it is precisely what you want here. A possibility would be to create a new group to match the spacing commands, e.g. texCmdSpacing - this would allow you to add a different highlight closer to the background for such commands. I'm not sure if it's worth the effort.

> Another way here would be to use the custom syntax mechanism and define your own custom groups and highlights.
</details>

Im having some trouble understanding how to make the changes and create the `texCmdSpacing` group...

After reading the some of the references provided:
- [`:h usr_44.txt`](https://vimhelp.org/usr_44.txt.html)
- [`:h syntax`](https://vimhelp.org/syntax.txt.html#syntax)
- [`:h vimtex-syntax-core`](https://github.com/lervag/vimtex/blob/fcbaf66887bd19f5d973406848cf2a5ac46bd65e/doc/vimtex.txt#L4924)
- also using [`master/syntax/tex.vim`](https://github.com/lervag/vimtex/blob/master/syntax/tex.vim) as reference

i created the file `.config/nvim/after/syntax/latex.vim`
```vim
function! MyHighlights() abort
  highlight def link texCmdSpacing texMathDelim
endfunction

augroup MyColors
  autocmd!
  autocmd ColorScheme * call MyHighlights()
augroup END

autocmd BufWritePost $MYVIMRC nested source $MYVIMRC
```

The idea was to create the `texCmdSpacing` to describe `/\\(?:[,:; !]|q{1,2}uad)/` and have the same highlighting and `texMathDelim`

Is everything so far right?
where should i go from here to describe the groups?

**Comment by lervag** [comment]
It seems like you are quite close. The only thing lacking is the syntax rules. I've added one rule which should be close to what you want:

```
function! MyHighlights() abort
  highlight def link texCmdSpacing texMathDelim
endfunction

augroup MyColors
  autocmd!
  autocmd ColorScheme * call MyHighlights()
augroup END

syntax match texCmdSpacing "\\[,;:!>]"

" Perhaps you also need this - in case your colorscheme was applied before the
" autocommand was defined.
call MyHighlights()
```

For testing and further developing, I recommend:

1. Creating a simple, short test file `test.tex`
2. Keep one neovim window for writing the syntax rules
3. Keep a terminal close by where you do `nvim test.tex` to test and `:q` to quit after testing

It's not perfect, but it should work well enough.
