### ISSUE TITLE
[Ques]: Keep the working dir clean?

### ISSUE THREAD

**Issue by niksingh710** [lervag/vimtex#3021]
![image](https://github.com/user-attachments/assets/4bbbb004-bc60-4bde-8e81-9debd1d6f163)
The compilation process generates multiple files but is there any way to keep the working dir clean?
like telling the compiler to store the temp file in `/tmp` or somewhere else?

and keeping the pdf file only?

**Comment by Felipe-9** [comment]
you can set `aux_dir = ".build"` for example, the compiler will create the dir and send all auxiliary tex files to it, keeping only the tex, pdf and synctex.gz file on the current directory.

add this to your `vimtex.lua` config inside `init = function() ... end`:
```lua
vim.g.vimtex_compiler_latexmk = {
  aux_dir = ".build" -- you can set here whatever name you desire
}
```

**Comment by lervag** [comment]
What @Felipe-9 said - and it's the only good solution in my opinion. 🤷🏻
