### ISSUE TITLE
nvim ~/.config/nvim/lua/user/vimtex.lua Shows an empty file

### ISSUE THREAD

**Issue by G0MITA** [lervag/vimtex#3022]
### Description

Hello I am new to vim and coding and I have followed your video to setup vim and all that stuff. I just wanted to finish up by adding Zotero and I have also already installed skim. But when I try to configure the file nvim ~/.config/nvim/lua/user/vimtex.lua I just see an empty file and nothing that I can rewrite. And once I tried just to copy paste what was standing in that file in the video, but an error message was returned. Now I am really just lost and don't know what to do.
\

### Steps to reproduce

1.nvim ~/.config/nvim/lua/user/vimtex.lua  2. See empty file

### Expected behavior

A full written file where I can just simply change one word.

### Actual behavior

An empty file and a depressing feeling of hopelessness

### Do you use a latexmkrc file?

i don't think so 

### VimtexInfo

```yaml
I don't think it has something to do with this.
```

**Comment by lervag** [comment]
> Hello I am new to vim and coding and I have followed your video to setup vim and all that stuff.

Cool! Welcome to this "world", I hope you find it fun!

Now, just to be clear, I think you must be talking about a video from someone else. I've not made any videos myself.

> But when I try to configure the file nvim ~/.config/nvim/lua/user/vimtex.lua I just see an empty file and nothing that I can rewrite.

Well, it seems you are basing things off some premade configuration or distribution. I don't know these, and I think you should ask the maintainer of that particular distribution/config.

> And once I tried just to copy paste what was standing in that file in the video, but an error message was returned. Now I am really just lost and don't know what to do. \

Again, I've not made any videos. But I _did_ document things, and I strongly recommend that you first read the README file of VimTeX, and also skim at least the introduction of the main documentation (`:help vimtex`) after installing it.
