### ISSUE TITLE
VimTeX: Viewer cannot find Zathura window ID!

### ISSUE THREAD

**Issue by cklin731** [lervag/vimtex#3028]
### Description

VimTeX: Viewer cannot find Zathura window ID!

I have seen many article.
No one said, how to fix this problem.

### Do you use a latexmkrc file?

NO

### VimtexInfo

```yaml
VimTeX: Viewer cannot find Zathura window ID!
```

**Comment by user202729** [comment]
Without steps to reproduce, it's impossible to help.

What's your environment? 

* If WSL2, see https://github.com/lervag/vimtex/issues/2980
* If Wayland, see https://github.com/lervag/vimtex/issues/2973 (include a possible workaround)
* Apparently some users report issues with gvfs https://github.com/lervag/vimtex/issues/2904

**Comment by cklin731** [comment]
> Without steps to reproduce, it's impossible to help.
> 
> What's your environment?
> 
> * If WSL2, see [WSL2: Viewer cannot find Zathura window ID! #2980](https://github.com/lervag/vimtex/issues/2980)
> * If Wayland, see [Vimtex: Viewer cannot find Zathura window ID #2973](https://github.com/lervag/vimtex/issues/2973) (include a possible workaround)
> * Apparently some users report issues with gvfs [Zathura issues with finding Window ID #2904](https://github.com/lervag/vimtex/issues/2904)

I use the brew tap zegervdv/zathura to install on the macbook.

**Comment by user202729** [comment]
Maybe try reading `:help vimtex-faq-zathura-macos`. there are a few other issues https://github.com/lervag/vimtex/issues/1735 https://github.com/lervag/vimtex/issues/2581 on GitHub concerning Mac users as well.

**Comment by lervag** [comment]
@cklin731

You're original post contains:

> VimTeX: Viewer cannot find Zathura window ID!
> 
> I have seen many article. No one said, how to fix this problem.

And where we asked for `:VimtexInfo` you did not provide the output of `:VimtexInfo`.

@user202729 asks for more info, to which you reply simply

> I use the brew tap zegervdv/zathura to install on the macbook.

He also provides a reference to the faq section in the docs. This is, as far as I know, the best possible answer right now. If you need further help, then _please_ provide a reproducible example and/or the details necessary to help you.

> @lervag It may be a good idea to detect user running on Mac (https://vi.stackexchange.com/a/2577/26108 --- looks like need to run uname) and on zathura synctex failure automatically point the user to the FAQ entry.

Well, yes, possibly. But that's more work than answering a post every once in a while 😅
