### ISSUE TITLE
Improve support for subequations environment

### ISSUE THREAD

**Issue by gssfaw** [lervag/vimtex#3036]
**Is your feature request related to a problem? Please describe it.**
I've found that vimtex does not parse labels from the subequations environment of the asmath package if they contain non-Latin characters in them for the omnifunc completions.

**Describe the solution you'd like**
It would be great if the subequations environment got a better support. This is probably due to the fact that Unicode characters need special handling. 

On this screenshot you can see that omnifunc (C-xC-o) does not show the number of the subequation if it contains a Cyrillic character, while the equation with Latin letters works as expected.
![20241026_15h28m01s_grim](https://github.com/user-attachments/assets/41551fb6-6f5c-4e2a-8169-380e7698f6cc)
Here is a minimal `.tex` file with examples. The first one has Cyrillic letters, the former has Latin characters.
<details>
  <summary>Minimal tex file</summary>

```tex
%! TeX program = lualatex
\documentclass[12pt]{article} 
\usepackage{polyglossia}
\setdefaultlanguage[babelshorthands=true, forceheadingpunctuation=false]{russian}
\setotherlanguages{english}
\usepackage{fontspec} 
\setmainfont{FreeSerif}
\setsansfont{FreeSans}
\setmonofont{FreeMono}
\usepackage{amsmath}   
\begin{document}
% subequations with cyrillic letters
\begin{subequations}
    \renewcommand{\theequation}{\theparentequation\asbuk{equation}}
    \begin{align}
        test 1 1\label{eq:test_1_1}\\ 
        test 1 2 \label{eq:test_1_2}
    \end{align}
\end{subequations}
% subequations with latin letters
\begin{subequations}
    \begin{align}
        test 2 1\label{eq:test_2_1}\\ 
        test 2 2 \label{eq:test_2_2}
    \end{align}
\end{subequations}

\eqref{eq:test_1_2} % Does not show the number 
\eqref{eq:test_2_2} % Does show the number

\end{document}
```
</details>
`main.aux` has all labels and they seem to look the same way. 
<details>
  <summary>main.aux</summary>

```tex
\relax 
\ProvideDocumentCommand \selectlanguage {sO{}m}{}
\catcode `"\active 
\@writefile{toc}{\selectlanguage *[babelshorthands=true, forceheadingpunctuation=false]{russian}}
\newlabel{eq:test_1_1}{{1а}{1}{}{}{}}
\newlabel{eq:test_1_2}{{1б}{1}{}{}{}}
\newlabel{eq:test_2_1}{{2a}{1}{}{}{}}
\newlabel{eq:test_2_2}{{2b}{1}{}{}{}}
\gdef \@abspage@last{1}
```
</details>

**Comment by lervag** [comment]
There was a regex that explicitly looked for simple lowercase latin characters. I've generalized it in a manner that looks safe and I believe this should resolve your issue.

**Comment by gssfaw** [comment]
It's working now, I really appreciate your help

**Comment by lervag** [comment]
Great; glad to hear it!
