### ISSUE TITLE
When doing :VimtexInverseSearch, temporarily highlight the relevant area in the editor for a short duration

### ISSUE THREAD

**Issue by ThSGM** [lervag/vimtex#3038]
Same as comment. It would be useful, like in some modification of the yank functionality, to highlight the relevant section of the document when doing an inverse search from the PDF. This not only provides some visual feedback that the inverse search is working, but it also draws the eye to the location. 

It might also be useful to code in, as a default behaviour, that the editor window centers on the content.

**Comment by ThSGM** [comment]
Amazing stuff as usual @lervag. 

It might be worth implementing this as a feature in vimtex, or perhaps something that can be turned off via configuration options? I'm not sure it's a super controversial snippet. Worth considering perhaps. 

Thanks for adding it to the docs.

**Comment by lervag** [comment]
> Amazing stuff as usual @lervag.

Thanks 🤩

> It might be worth implementing this as a feature in vimtex, or perhaps something that can be turned off via configuration options? I'm not sure it's a super controversial snippet. Worth considering perhaps.

It's an interesting proposal. I'm not sure how controversial it would be, to be honest.

> Oh, worth asking: how would you modify the highlight group to make it a bit more prominent?

The blinking uses the `cursorline` setting which has the `:help hl-CusrorLine` highlight group. But changing this would also change it if you use it in general, right.

Perhaps you could open a new issue where we discuss if this is something we should build into VimTeX directly. It would include a discussion of which highlight group to use (I could find a different way to do this, I think, perhaps).
