### ISSUE TITLE
We should say Merry Christmas to @lervag

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#304]
...and thanks for `vimtex`!!! 

(Sorry for the offtopic, but when it's needed, it's needed...)

**Comment by lervag** [comment]
Thanks, @Rmano! And merry christmas to you also! :)

**Comment by samvv** [comment]
Merry christmas and thanks for the plugin! :+1:

**Comment by lervag** [comment]
Thanks @samvv! Merry Christmas to you also! :-)

**Comment by nasenatmer** [comment]
Hehe, thanks for this great plugin and your ongoing commitment!

**Comment by Konfekt** [comment]
Yep, thanks for the most sensible and leanest TeX plugin.

**Comment by lervag** [comment]
Thanks, @nasenatmer and @Konfekt!

**Comment by lervag** [comment]
And a happy new year to everyone as well! :)
