### ISSUE TITLE
Zathura viewer with Wayland

### ISSUE THREAD

**Issue by GNUqb114514** [lervag/vimtex#3043]
**Is your feature request related to a problem? Please describe it.**
I'm using vimtex with zathura and Wayland, but vimtex always report 'Viewer cannot find Zathura window ID',
and it's annoying (even it's not matter for its main functionality).

I found some informations in old issues that says xdotool, the tool vimtex used to get the 'window ID',
cannot work with Wayland at all (well, getting 'window ID').

**Describe the solution you'd like**
Make the viewer 'zathura' able to detect the protocol the user is using, and use the correct tool.

**Describe alternatives you've considered**
Just provide a new viewer.

P.S. I'd like to help you implementing this, if anybody can tell me where should I put my codes in.

**Comment by lervag** [comment]
Zathura does work best on Xorg with `xdotool`. On Wayland, it is better to use `zathura_simple` as it does not include the xdotool integration. Please read `:help vimtex-view-zathura`, which says:

```vimhelp
Configuration: >vim
  " Main variant with xdotool
  let g:vimtex_view_method = 'zathura'

  " For simple variant without xdotool
  let g:vimtex_view_method = 'zathura_simple'

The main variant uses `xdotool` to help avoid duplicate Zathura instances.
However, in some environments, `xdotool` is not available. Here the simple
variant should work well.
```

I believe this should be a valid solution for you, please let me know if I'm wrong.

**Comment by lervag** [comment]
> Well, it seems like the simple variant losts some functionality like synctexs, and I think we can use some substitutional tool to have the same functionality in Xorg.

No, the simple variant will still work well with synctex. If it does not, then there is something wrong on your end.

The only thing you loose is that the "full" version that requires `xdotool` will attempt to reuse existing Zathura windows instead of creating new ones.

**Comment by GNUqb114514** [comment]
Oh, I mean, when I change my tex file, it doesn't do forward synchronization with the existing Zathura process; rather it just does nothing.

**Comment by lervag** [comment]
> Oh, I mean, when I change my tex file, it doesn't do forward synchronization with the existing Zathura process; rather it just does nothing.

I don't quite understand what you mean. The `zathura_simple` and `zathura` viewers are exactly the same, except that the simple version does not use xdotool to ensure there is only one window. But that is not relevant to what you are talking about.

With default configurtion, the viewers will _not_ automatically do a forward synchronization after a successful compilation. Thus you are clearly not using default config here.

Can you please provide the relevant configuration that you are using and explain in tiresome detail exactly what you are trying to do, what you expect to happen, and what you observe is happening?
