### ISSUE TITLE
Complete include glossary entries from .bib files

### ISSUE THREAD

**Issue by brunotvs** [lervag/vimtex#3046]
**Is your feature request related to a problem? Please describe it.**
Currently, vimtex provides autocomplete for glossary entries, but not when we use a `.bib` file for input, loaded via the `\GlsXtrLoadResources` command.

**Describe the solution you'd like**
Use the `.bib` file loaded via the `\GlsXtrLoadResources` command to suggest autocomplete for glossary entries.

**Comment by lervag** [comment]
I've never heard of `\GlsXtrLoadResources`. Can you provide a minimal working example that would compile on my end? I want to see how this looks before I consider adding it.

**Comment by brunotvs** [comment]
Sure. Here is a [git repo](https://github.com/brunotvs/vimtex_gls). Use latexmk to compile.

**Comment by lervag** [comment]
I think this is fixed now. The gls completion was already supported, but there was a bug in detecting the file.
