### ISSUE TITLE
Add syntax highlighting for LuaLaTeX-CAS

### ISSUE THREAD

**Issue by ArtemChandragupta** [lervag/vimtex#3050]
There is a really good thing for small calculations inside $\LaTeX$ documents, [LuaLaTeX-CAS](https://github.com/cochraef/LuaLaTeX-CAS). I would really like to see the environment that this computer algebra package adds supported by VimTeX.

![image](https://github.com/user-attachments/assets/e00bb7c5-1ecb-4b22-8745-9c3841c54a89)

**Comment by lervag** [comment]
> There is a really good thing for small calculations inside L A T E X documents, [LuaLaTeX-CAS](https://github.com/cochraef/LuaLaTeX-CAS). I would really like to see the environment that this computer algebra package adds supported by VimTeX.

Ok, I might add it. But I would like some help:

1. Can you provide a short example document for this (please provide it inline instead of a screenshot - use the triple backquotes, e.g. ```` ```tex ... ``` ````).

2. If you were to edit a LuaCAS file directly, which syntax does it use? Does Neovim support it out of the box? If not, then I can't add it.

**Comment by ArtemChandragupta** [comment]
[This](https://ctan.altspu.ru/macros/luatex/latex/luacas/doc/luacas.pdf) is the documentation with a lot of examples of Luacas code, that can be copied from pdf-file; My own example from screenshot is also from this file.

About syntax, seems that it is custom and do not have any highlights now. Also in the pdf it is not highlighted. So I think the good way is just make the code inside \begin{CAS}...\end{CAS} unhighlighted so that VimTeX doesn't complain about it.

**Comment by lervag** [comment]
> [This](https://ctan.altspu.ru/macros/luatex/latex/luacas/doc/luacas.pdf) is the documentation with a lot of examples of Luacas code, that can be copied from pdf-file; My own example from screenshot is also from this file.

Ok, thanks. I can use the docs, but notice that if you were to copy the relevant examples here it would save me some time looking up and reading the docs for this. 🤷

> About syntax, seems that it is custom and do not have any highlights now. Also in the pdf it is not highlighted. So I think the good way is just make the code inside \begin{CAS}...\end{CAS} unhighlighted so that VimTeX doesn't complain about it.

Ok, great; then I'll add it as a normal verbatim-like environment.

**Comment by lervag** [comment]
Please update and test; I didn't read the docs. I've added support for the `CAS` environment, but nothing else right now.

**Comment by ArtemChandragupta** [comment]
Update was delivered for me.

The environment works well. Thank you for brilliant plugin!

**Comment by lervag** [comment]
Glad to hear it works and thanks for the kind words!
