### ISSUE TITLE
Showing errors before warning in quickfix window

### ISSUE THREAD

**Issue by Djoop** [lervag/vimtex#3053]
Hi, is there an option or an easy way to get automatically errors appearing before warnings in the quickfix window when calling `(vimtex-errors)`? I've seen that there is an option to hide some warnings, but still it happens to me when working on large documents that it would be useful to display (at least some of) the warnings, however it is even more important to quickly see the error messages (which, for now, are often hidden because both warning and error messages are ordered by the line number of their occurence in the document, and the quickfix window is small).

Suggestion: a boolean option such that, if activated, all error messages appear before the warning messages (and then inside each group, sorting is still performed according to line numbers).

Note: I use the default log parser.

**Comment by lervag** [comment]
Good question. There is no such feature now - it is currently sorted by line numbers, I think. But I agree it may make sense to sort by severity, or at least to put the errors on top. I'll look into it!

**Comment by lervag** [comment]
Please update and test - does this work as you suggested?

**Comment by Djoop** [comment]
Yes, it seems to work perfectly, thank you !

**Comment by lervag** [comment]
Great, glad to hear it!
