### ISSUE TITLE
start file name completion for \includegraphics

### ISSUE THREAD

**Issue by huesersohn** [lervag/vimtex#308]
I use neocomplete for automatic completions. For `\cite` and `\ref` this brings up the respective menu after typing `{`. I'd like to have the same thing for `\includegraphics` (maybe `\input` and `\include` too?) so that after typing the opening brace file name completion starts. Is there already an option for this (didn't find one)?

**Comment by lervag** [comment]
This is not a vimtex issue, but a neocomplete issue. I suggest you open an issue [there](https://github.com/Shougo/neocomplete.vim). I was not able to find a way to achieve what you wanted, because it seems the file source for neocomplete decides whether to start file completion manually.

**Comment by Shougo** [comment]
@lervayg  Hm.

I think your omni source pattern should be updated.

```vim
  let g:neocomplete#sources#omni#input_patterns.tex =
        \ '\v\\\h\w*([^]]*\])?\{([^}]*,)*[^}]*'
```

**Comment by lervag** [comment]
@Shougo No, I don't think so. The omnicomplete function only completes citations and labels. I don't think it should be necessary to add file name completion as part of the omnifunc. My suggestion is either to allow to control when the file source is activated in neocomplete, or that @huesersohn learns to use the `<c-x><c-f>` mapping (to use standard vim filename completion).

**Comment by ff2000** [comment]
On Sat, 02 Jan 2016 23:49:27 -0800, Karl Yngve Lervåg <notifications@github.com> wrote:
> @Shougo No, I don't think so. The omnicomplete function only completes citations and labels. I don't think it should be necessary to add file name completion as part of the omnifunc. My suggestion is either to allow to control when the file source is activated in neocomplete, or that @huesersohn learns to use the `<c-x><c-f>` mapping (to use standard vim filename completion).

IMHO that won't work because latex expects image paths relative to the
master document. If you are in an included subfile, that sits in a
subdir relative to the master file, vim-internal file completion never
can do the right thing.

**Comment by lervag** [comment]
@ff2000 Hmm. Ok, so you're saying that you think it would be useful if the omni completion would complete *relevant* file names for `\includegraphics` based on the master document root path? I can agree that this requires something more specialized than common file completion.

Note, though, that there seems to be several things that might complicate things. E.g. if one adds a path to `\graphicspath` with the `graphicx` package, then one can use figure paths relative to this path.

I am questioning whether this feature is "good enough" and necessary enough to be implemented. Personally, I have never had any problems with using `<c-x><c-f>`, although I agree it would be convenient. I'll definately consider it if you guys believe it is useful. It should be relatively easy to add a first unfiltered version that does not take `\graphicspath` into account.

**Comment by huesersohn** [comment]
It really would be convenient. Right now, I do use the `<c-x><c-f>` mapping. But being used to the way the completion from neocomplete works, i.e. the popup opens and when you choose an entry, it automatically completes again, I was looking for something similar. Personally I have never used `\graphicspath`, so I'd find your suggestion useful.

**Comment by Shougo** [comment]
> @Shougo No, I don't think so. The omnicomplete function only completes citations and labels. I don't think it should be necessary to add file name completion as part of the omnifunc.

Hm...  I think vimtex supports the filename completion.

> My suggestion is either to allow to control when the file source is activated in neocomplete, or that @huesersohn learns to use the <c-x><c-f> mapping (to use standard vim filename completion).

To control the filename completion by the pattern, neoinclude is the better choice than neocomplete file source.

**Comment by lervag** [comment]
@Shougo No, vimtex does not support filename completion (although I am working on a simple version of this now). As I said, the omnifunction only completes bibliography entries and labels.

I do not understand how to use neoinclude in this setting. I would be very happy if you could give an example of how to use neoinclude to control the filename completion with vimtex!

**Comment by Shougo** [comment]
>No, vimtex does not support filename completion (although I am working on a simple version of this now). As I said, the omnifunction only completes bibliography entries and labels.

OK.

> I do not understand how to use neoinclude in this setting. I would be very happy if you could give an example of how to use neoinclude to control the filename completion with vimtex!

neoinclude has file/include source.
You can define the completion pattern like this.
This is the html file completion example.

```vim
  call neoinclude#util#set_default_dictionary(
        \ 'g:neoinclude#_patterns',
        \ 'html,xhtml,xml,markdown,mkd', '\%(src\|href\)="\ze[^"]*$')
```

It completes from the 'path' option and the current directory.

**Comment by lervag** [comment]
I've pushed a simple version of the completion. Please see docs for how to set neocomplete options.

**Comment by huesersohn** [comment]
Nice, it works just as I expected! Would you consider adding this for `tex` files for use with `\input` and `\include` too?

I tried neoinclude, but ran into an issue with a function call like the one @Shougo posted. I found that neoinclude already does support `\input` and `\include`, but the current directory it completes from seems to be the directory the file is in rather than the current working directory of vim.

**Comment by petobens** [comment]
Hi @lervag  thanks for adding this feature. I do use `\graphicspath` and I would like to complete only the tail of the filename. For instance if I have a graphic file `figures/foo.pdf` and a tex file containing:

```tex
\graphicspath{{figures/}{tables/}}
```

I want to complete `foo.pdf` instead of `figures/foo.pdf` (as the omnifunc currently does). Is it possible to implement this? If it is not (or if it complicates things too much) then just forget about. Thanks in advance.

**Comment by lervag** [comment]
@huesersohn I've added completion for input and include as well. I think I agree that this might be convenient.

@petobens I've added an option `g:vimtex_complete_img_use_tail`. This will complete only the tail part, and I think it might be sufficient. Let me know what you think.

**Comment by lervag** [comment]
Thanks for the input on neoinclude, @Shougo!

**Comment by huesersohn** [comment]
Thank you, @lervag! The patterns for neocomplete (and YCM) need to be adjusted in the docs, for the former I did it like so:
```vim
let g:neocomplete#sources#omni#input_patterns.tex =
      \ '\v\\%('
      \ . '\a*%(ref|cite)\a*%(\s*\[[^]]*\])?\s*\{[^{}]*'
      \ . '|%(input|include?(graphics))%(\s*\[[^]]*\])?\s*\{[^{}]*'
      \ . ')'
```
What would you use?

**Comment by petobens** [comment]
Thank you! It works just as expected. One minor thing: is it possible to show the "full relative path" i.e `figures/foo.pdf`  in the popup menu but only complete  the tail  `foo.pdf` when actually inserting/selecting the candidate?. Even if one wants to insert only the tail I believe that when selecting a candidate it is useful to have a longer path information. I understand however that this might be confusing and you prefer not to implement it. Thanks once again

**Comment by lervag** [comment]
@petobens No problem. I was thinking about this same thing myself, actually. Should work now.

**Comment by petobens** [comment]
Thank you @lervag.
