### ISSUE TITLE
Strange behaviour when using vimtex's formatexpr

### ISSUE THREAD

**Issue by huesersohn** [lervag/vimtex#309]
Using `let g:vimtex_change_set_formatexpr=1` I get some strange behaviour when typing long lines of text. I use `textwidth=100` to have vim automatically break the line, and with vimtex's `formatexpr` the last two characters disappear after breaking the line.

Consider the following:
```
In diesem Abschnitt werden die für die Implementierung relevanten Teile der Programmiersprache
```

Typing `vorgestellt,` after the last word, the line gets wrapped and I end up with
```
In diesem Abschnitt werden die für die Implementierung relevanten Teile der Programmiersprache
vorgestel,
```
Notice the two missing characters `lt` just before the comma. Another example I noticed with a shorter word (I don't remember the exact sentence, but this example will do; the whitespace before `Programmiersprache` is necessary to get the needed length of line):
```
In diesem Abschnitt werden die für die Implementierung relevanten Teile der   Programmiersprache sowie 
```
After typing the last `sowie` and then pressing space yields the following, again two characers are missing, but the line is not wrapped because the `w` is the 100th character:
```
In diesem Abschnitt werden die für die Implementierung relevanten Teile der   Programmiersprache sow 
```

**Comment by lervag** [comment]
Should be fixed now.

**Comment by huesersohn** [comment]
It is, thank you! :)

**Comment by lervag** [comment]
No problem :)
