### ISSUE TITLE
Vimtex command :VimtexCompile dose not work in  latest gvim in windows platform!

### ISSUE THREAD

**Issue by chenzhihuai1990** [lervag/vimtex#311]
I download the latest gvim from the official website[ftp://ftp.vim.org/pub/vim/pc/gvim74-1024.exe].
It does not work when I use <leader>ll to start compiling, and not any message is echoed!
However, it work in with an older version!

Partial version information of the latest:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Jan  2 2016 14:36:11)
MS-Windows 32-bit GUI version with OLE support
Included patches: 1-1023
Compiled by mool@tororo

Partial version information of the older:
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Aug 10 2013 14:36:26)
MS-Windows 32-bit GUI version
Compiled by mool@tororo

**Comment by chenzhihuai1990** [comment]
I have find alternative version (Yangwei's build) recommended in official site. It works successively.

**Comment by lervag** [comment]
Great. Good to hear it works with Yangwei's build.
