### ISSUE TITLE
Issuing the view command opens a new zathura window each time

### ISSUE THREAD

**Issue by svenstaro** [lervag/vimtex#313]
I'm using neovim on Arch Linux and set zathura as my viewer. Whenever I use the view command, vimtex opens a new instance of zathura. Now, I know that vimtex uses xdotool to find that stuff. ~~It was updated to 3.20150503.1-1 on my system on 2015-12-31 and probably is the root of the problem.~~

EDIT: Don't report bugs when tired. The xdotool package in Arch is actually from May so it's not the problem. Still, the problem is real.

I will run any tests for you to fix this.

**Comment by lervag** [comment]
Could you please create a minimal working example? See for instance [here](https://github.com/lervag/vimtex/tree/master/test/issue/272); I can do `vim -u minivimrc main.tex` to test. Or in this case I would probably do something like `neovim -u minivimrc ...`.

Note: Full neovim support is not yet provided out of the box. You might already be aware of this. See #262 for more info.

**Comment by svenstaro** [comment]
I can reproduce with that little example. Every time I time I type :VimtexView or <localleader>lv, I get a new zathura.

**Comment by nasenatmer** [comment]
I can't reproduce this with `VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Dec 29 2015 00:03:54)` so might be a `neovim` issue…

**Comment by lervag** [comment]
I can not reproduce this with Vim 7.4.944 on Arch Linux. I think as @nasenatmer that this might be a neovim issue.

Again, it would help if you could explain very concretely how to reproduce. Please provide a minimal example and a minimal vimrc (if it worked, you could just copy the files from example I provided) and a step-by-step description of how to reproduce.

In addition, it could help if you could provide the output of `<localleader>li` after you have started the first zathura instance.

**Comment by svenstaro** [comment]
Well, I took the minivimrc from the resource you linked, changed the paths to point at current vimtex on my system and then started neovim in the way you stated above.

I then typed <localleader>lv upon which zathura opened. I then pressed <localleader>lv again and a second zathura instance opened.

`<localleader>li:`
```
b:vimtex : main                                                                                                                                                                                                                                                                   
  pid : 29640                                                                                                                                                                                                                                                                     
  root : '/home/svenstaro/prj/uni/thesis/tex'                                                                                                                                                                                                                                     
  aux : '/home/svenstaro/prj/uni/thesis/tex/main.aux'                                                                                                                                                                                                                             
  log : '/home/svenstaro/prj/uni/thesis/tex/main.log'                                                                                                                                                                                                                             
  out : '/home/svenstaro/prj/uni/thesis/tex/main.pdf'                                                                                                                                                                                                                             
  tex : '/home/svenstaro/prj/uni/thesis/tex/main.tex'                                                                                                                                                                                                                             
  tmp : '/tmp/nvimDB1XqI/2'                                                                                                                                                                                                                                                       
  cmd_latexmk_compile : 'cd ''/home/svenstaro/prj/uni/thesis/tex'' && max_print_line=2000 latexmk -verbose -pdf  -e ''$pdflatex =~ s/ / -file-line-error /'' -pvc -e ''$success_cmd = "\"vim\" --servername /tmp/nvimDB1XqI/0 --remote-expr \"vimtex\#latexmk\#callback(1)\""'' -e
 ''$failure_cmd = "\"vim\" --servername /tmp/nvimDB1XqI/0 --remote-expr \"vimtex\#latexmk\#callback(0)\""'' -e ''$new_viewer_always = "0"'' -e ''$pdf_previewer = "zathura  -x \"vim --servername /tmp/nvimDB1XqI/0 --remote +\%{line} \%{input}\" \%S"'' ''main.tex'' >/tmp/nvimD
B1XqI/2 2>&1'                                                                                                                                                                                                                                                                     
  base : 'main.tex'                                                                                                                                                                                                                                                               
  viewer                                                                                                                                                                                                                                                                          
    xwin_id : 0                                                                                                                                                                                                                                                                   
    class : 'Zathura'                                                                                                                                                                                                                                                             
    init : function('389')                                                                                                                                                                                                                                                        
    view : function('390')                                                                                                                                                                                                                                                        
    start : function('391')                                                                                                                                                                                                                                                       
    forward_search : function('392')                                                                                                                                                                                                                                              
    latexmk_callback : function('393')                                                                                                                                                                                                                                            
    latexmk_append_argument : function('394')                                                                                                                                                                                                                                     
    xwin_exists : function('<SNR>126_xwin_exists')                                                                                                                                                                                                                                
    xwin_get_id : function('<SNR>126_xwin_get_id')                                                                                                                                                                                                                                
```

xwin_id seems wrong to me but I really have no idea.

**Comment by lervag** [comment]
Thanks. The output implies that there is a problem with `xdotools`. That is, the `xwin_id` is not captured. Can you please try to run the command

    xdotool search --class Zathura

in a terminal after you have opened the first viewer (from vimtex)? It should output a (list of) xwin ID(s).

**Comment by svenstaro** [comment]
It does:
```
xdotool search --class Zathura
39845891
39845889
```

**Comment by lervag** [comment]
Interesting. I'm trying to reproduce with `neovim`, but still can't. Can you please create a minimal working example based on the files I've linked to earlier and explain very clearly step by step how to reproduce?

You say the files for #272 reproduces the issue, but they obviously don't, since the minimal vimrc file doesn't set zathura as the viewer. Thus you have added options or use you still use your own vimrc file.

**Comment by svenstaro** [comment]
Interestingly enough, the reason it opens zathura is not because it is set in the config but because it's my system's default. I changed my system default to mupdf and then `\lv` opens mupdf instead! However, when I ask vim to output `g:vimtex_view_method` it gives me: 'zathura'

My config lines for vimtex look like this:

```
" vimtex
let g:vimtex_fold_enabled = 0
let g:vimtex_view_method = 'zathura'
```

However, the behavior I'm seeing would imply that vimtex uses the xdg-open method even though 'zathura' is set! Maybe this is the whole problem here in fact?

**Comment by lervag** [comment]
No. It does not use `xdg-open`, cf. the output from `\li` that you showed earlier.

I don't really understand what is so difficult with doing what I ask?! It is simple: Provide a clean and minimal vimrc file and a minimal tex file, and steps to reproduce the issue. I've already linked to test files that you can probably use almost as is.

Btw: Can you report whether things work with Vim instead of neovim?

**Comment by svenstaro** [comment]
Ok so this is weird. This vimrc works:

```
set nocompatible
let &rtp = '~/.config/nvim/plug/vimtex,' . &rtp
filetype plugin indent on
syntax enable
set iskeyword+=:
let g:tex_flavor = "latex"
let g:vimtex_view_method = 'zathura'
```

[Mine](https://github.com/svenstaro/dotfiles/blob/master/vim/.config/nvim/init.vim) does not. Mine is obviously not trivial but I wonder why zathura decides to use xdg-open instead of zathura.

**Comment by svenstaro** [comment]
Alright, I figured it out. I had: 

```
Plug 'lervag/vimtex'
Plug 'sheerun/vim-polyglot'
```

but I need to use:

```
Plug 'sheerun/vim-polyglot'
Plug 'lervag/vimtex'
```

Sorry for the noise! Might want to add this to the FAQ, though.

**Comment by lervag** [comment]
Ah. FYI: Polyglot loads LaTeX-Box, which is the problem here and which explains why it works when you change the order. I suggest that you disable LaTeX-Box with

```vim
let g:polyglot_disabled = ['latex']
```

In any case, I am glad to hear it is working now. Personally, I really don't like plugins like polyglot. I think it is much better to keep things verbose, instead of hiding so many things in a wrapper plugin such as this.

**Comment by svenstaro** [comment]
I would tend to agree but I had lot of language plugins. Thanks for the tip!

**Comment by Tyrn** [comment]
This is no noise, **svenstaro**. I've got exactly the same problem, no language plugins, `vimtex` moved to the bottom:

    Plug 'powerman/vim-plugin-ruscmd'
    Plug 'xolox/vim-misc'
    Plug 'xolox/vim-session'
    Plug 'lervag/vimtex'

Got this and two Zathura windows:

    $ xdotool search --class Zathura
    46137345
    48234497
    48234499
    46137347

Arch, up-to date.

**Comment by Tyrn** [comment]
Looks like a harmless `vim-session` is the culprit this time. Smells of alchemy.

**Comment by Tyrn** [comment]
I can't be sure, as it turned out. Today I've got a warning, right on start:

    vimtex warning: viewer can not find Zathura window ID!

before firing two Zathura windows on `VimtexView`

**Comment by lervag** [comment]
I've also experienced to get two Zathura windows, but I have not been able to reproduce it, and so I have not found how/why it happens.

If you by chance would be able to reproduce it and describe how, then (very) please open a new issue and describe it. I would be happy to solve this!

**Comment by weikang-q** [comment]
> Thanks. The output implies that there is a problem with `xdotools`. That is, the `xwin_id` is not captured. Can you please try to run the command
> 
> ```
> xdotool search --class Zathura
> ```
> 
> in a terminal after you have opened the first viewer (from vimtex)? It should output a (list of) xwin ID(s).

I have the same issue. but as I run 
`search --class Zathura`
it prints that
```
Error: Can't open display: (null)
Failed creating new xdo instance
```

**Comment by lervag** [comment]
I don't use MacOS and I don't know how well `xdotool` is expected to work there. I'm not the maintainer of xdotool, so feel free to submit issue reports upstream.

On MacOS, people tend to use Skim as the pdf viewer, I think.

**Comment by weikang-q** [comment]
Ok. But if I use skim, is it opened automatically by splitting my terminal window?
For me, it just open a new window on my desktop.

**Comment by lervag** [comment]
> Ok. But if I use skim, is it opened automatically by splitting my terminal window?
For me, it just open a new window on my desktop.

I have no idea. I don't use MacOS or Skim. Does Zathura open in a terminal split? For me, it does not. It opens in a new window in my desktop.

This issue is from 2017. Please open a new issue if you need more help, and if so, please describe according to the issue template.
