### ISSUE TITLE
Support for closing other delimitors

### ISSUE THREAD

**Issue by eolianoe** [lervag/vimtex#314]
Does vimtex support closing delimiters like `\bigl( \bigr)` or `\lvert \rvert` (and all their declensions) as it supports the closing of `\left( \right)` with `]]` ?

**Comment by lervag** [comment]
No, sorry, it does not at the moment. I personally never use `]]`, since I find this feature obsolete through snippets. However, since the feature already works with `\left(`, it should be possible to make it work with similar commands. I'll leave this open and try to implement it when I get the time.

**Comment by lervag** [comment]
I've looked at this a little bit now. It should not be too difficult to add the feature. However, I see that I have not really understood the point of `\bigl...\bigr` and similar until now. Or the math delimiters in general. That is, I think I should update vimtex to handle delimiters in a more general and consistent manner throughout.

In this regard, it would be helpful if you could assist a little bit, e.g. provide a list of the different declenations and delimiters that should be detected in math mode by vimtex. At the moment, I have the following list (regexps for `open ... close`):

{{{
    \\\[\s*$ ...  \\\]\s*$
    \\{ ...  \\}
    \\\Cleft\s*\%([^\\]\|\\.\|\\\a*\) ...  \\\Cright\s*\%([^\\]\|\\.\|\\\a*\)
    \\\c\(bigg\?\)\((\|\[\|\\{\) ...  \\\1\()\|\]\|\\}\)
    \\\c\(bigg\?\)l\((\|\[\|\\{\) ...  \\\1r\()\|\]\|\\}\)
    \\l\(vert\|angle\|ceil\|floor\) ...  \\r\1
}}}

**Comment by nilsbecker** [comment]
i'm not sure i understand the regexps fully. but i'm confused by `bigg`. as far as i know, `bigg` is just a specific size, just like `big, Big,Bigg`. nothing special.

for delimiters, i found a list here: https://en.wikibooks.org/wiki/LaTeX/Mathematics#List_of_Mathematical_Symbols under 'Delimiters' and this: http://tug.ctan.org/info/symbols/comprehensive/symbols-letter.pdf seems to be a reference.

**Comment by lervag** [comment]
@nilsbecker Sorry, the regexps are somewhat complex, I should instead just have listed all the possibilities. However, `\\\c\(bigg\?\)` matches all of e.g. `\big`, `\bigg`, `\Big`, etc.

Thanks for the list. It will probably be useful!

**Comment by nilsbecker** [comment]
ahh! that makes more sense. thanks.

**Comment by lervag** [comment]
This should be provided in the recent update.
