### ISSUE TITLE
inline math with \( \)

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#315]
this is a bit related to #115 . inline math can be done in a less fragile way by using `\( \)` (actually this seems to be the officially preferred way) but the text object `$` does not seem to recognize it.

**Comment by lervag** [comment]
This should work now. Please note that I might not be able to address all of your recent issues very fast. Life is quite busy at the moment.

**Comment by nilsbecker** [comment]
cool, thanks! no worries about response times, it's all entirely up to you of course. vimtex is already very useful!

**Comment by lervag** [comment]
:)
