### ISSUE TITLE
prevent line joining after commands

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#317]
this is an idea that came out of #238 .

the `gq` formatting operation is very useful. currently it works fine for text paragraph and also respects environment boundaries. however, sometimes it leads to undesired results.

two cases come to mind

1. line/page breaking commands at the end of a line become unreadable when the following line is joined. arguably, for some commands the following line should be empty anyway, but for linebreaks this is maybe not desired. so:
```
lalal alal a \\
blbl blbl 
```
should probably not be joined by `gq` (which it is presently). this would be even more desirable when `\\` is used to break rows in a tabular or a matrix, or lines of an `align` environment.

some more line breaking commands:
```
\\ start a new paragraph.
\\* start a new line but not a new paragraph.
\cleardoublepage flush all material and start a new page, start new odd numbered page.
\clearpage plush all material and start a new page.
\linebreak allow to break the line here.
\newline request a new line.
\newpage request a new page.
\pagebreak encourage page break. 
```

2.  commands on separate lines in the preamble or in a figure environment etc.

```
\begin{document}
\title{Laba daba}
\date{\today}
\author{B.\,Bunny}
```

or 

```
\begin{figure}[htpb]
    \includegraphics[width=\linewidth]{fig/mdsscc-erika.pdf}
    \centering
    \caption{\label{fig:mdsscc-erika}%
        Scatter plots of  bla bla bla}
\end{figure}
```

here is the proposal: both cases 1. and 2. would be handled by not joining lines whose last word is a latex command. then `gq` could potentially even be used on whole documents.

caveat: this global rule will prevent line breaking if e.g. `\emph{not}` is the last word on a line. this is not ideal. the question is if this is a price maybe worth paying?

**Comment by lervag** [comment]
I think the goal of applying `gq` to the whole document might be too optimistic, but who knows where we will end up?

I've added a test (but not implemented feature) for supporting the line breaks. I'm slightly more "worried" about the other feature. Perhaps a rule of thumb could be that we don't join lines that contain just a single latex command?

**Comment by Rmano** [comment]
I think that this is quite complex --- find a general rule is really difficult. What about _not_ joining any line, but simply splitting long ones (maintaining the indent of the first one, that is)? 

I would be happy with something doing just that (and as a bonus, adding a CR after a full stop, like in [this suggestion](http://dustycloud.org/blog/vcs-friendly-patchable-document-line-wrapping/) (without the horrible additional indents, obviously)...

**Comment by nilsbecker** [comment]
in my opinion not joining any lines would cripple the `gq` command -- it should be possible to nicely format some text-only paragraph to a common linewidth.  

let's try to collect joining rules. 

- lines with only latex commands will not be joined upwards or from below. 
one problem could be that `{}` are often optional. the line `\newcommand \llala \lambda` is legal for example. so what would the regex be? a line that does not contain a word beginning with something other than `\` except inside a pair `{}`? this sounds quite hard with a regex, since it would require some notion of a 'top level' of brace nesting (i may be wrong). if this could be solved i think it would go a long way to a solution.

- lines that start with `\item` should not join the one above.

- environment boundaries should block joining

- lines that end with one out of a set of break markers should not be joined from below. 
this requires listing the break markers. probably not too bad. in particular `%` should be part of that list as well.

ok, how about this: there is a set of 'start markers' which when at the (except-whitespace) beginning of a line, prevent that line from joining upward. those include `\begin`, `\item` and possibly some others. then there is the set of 'end markers', `\end`, all kinds of breaks, possibly others. this does not cover the preamble or some commands inside figure environments, tikz, etc. and indeed it's impossible to list all latex commands in on of the above lists. but that should be covered by the last rule for not joining command-only lines (don't know if that last one is feasible, see above)

**Comment by nilsbecker** [comment]
ok, an addendum: inside of math, line joining is probably always unwelcome. but how should `gq` know that? if i select 2 lines inside a long `align` environment, there is no information if this is math? hmm.

**Comment by Rmano** [comment]
I was unsure, but now you have convinced me... the better strategy is to never join. I really prefer to select a block, `J` them, and the `gq` it --- And let `gq` just split. 

That means tha you will not be able to `gq` all file, I know.

**Comment by nilsbecker** [comment]
just to be sure: i was not arguing for `gq` not being able to join. i still think `gq` ideally should join and split as necessary.

**Comment by Rmano** [comment]
@nilsbecker  I know :-) it was supposed to be a joke... sorry if it was not clear :-). But I really think that *joining* line in a LaTeX source file is a very human-decision kind of thing, so I'd prefer that `gq` refrained from this.

**Comment by lervag** [comment]
I agree with @nilsbecker that `gq` _should_ join lines, if necessary.
Personally, I think we should define a subset of possible cases that should be
supported. This set does not need to capture every case, I think it is _not_
possible to aim for auto-formatting an entire file.

My suggestion is to include these rules:

- Don't join from below on lines that end with comment or newline type commands
- Lines that start with `\item` should not join the line above
- Environment boundaries should block joining (perhaps excluding the case where
  the boundary is defined inline?)
- Don't join lines inside some environments, e.g. math and verbatim(?)

I think @nilsbecker might be right that this can mostly be solved by defining end and start markers. I think it is possible to detect the current environment through syntax information, so I think the last point on the list should be possible to solve.

I am thinking that perhaps one could solve both cases here: that is, @Rmano does not want `gq` to ever join any lines, perhaps this could be solved through an option. Still, for me, this is not a priority. If one prefers manual formatting, then `gq` should not be used anyways.

**Comment by lervag** [comment]
I think this task is so complex, it is better to open a new issue where the main requirements are specified before I start solving/implementing things. I suggest we continue the discussion there (#436).
