### ISSUE TITLE
sentence text object

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#320]
i noticed that invoking `das` at the position `*` below,
```
...
x = y.
\end{equation}
This is a * new sentence.
```
also deletes the closing `\end{equation}`. this is somewhat annoying and unintuitive, since for example, `dap` does not delete `\end{equation}` presently. so, it's not true that the object `s` is nested inside `p`.

this made me think that maybe the `s` text object should generally stop at environments? 

on second though this is not so clear-cut.  equation or other (text formatting) environments may be a legitimate part of a sentence, so one may actually want to delete them with `das`. but then, not even a paragraph deletion would delete the environment, it seems.

the behavior at the moment non-intuitive since paragraphs borders are not always also sentence borders. to solve this, it seems one would want to either make paragraphs span environments, or make sentences stop at environments. 

it seems that the first option would possibly break #226 again? could the formatting with `gq` in #226 be made to work just by modifying `gq` and keeping a more naive paragraph text object which only sees blank lines as borders? this may be nonsense, sorry if so.

the second option is possibly easier: make sentences stop at any environment. then the simple rule 'sentences go from . to . within a paragraph' would still apply. the `s` could possibly be defined to always be inside the current `p`..

**Comment by lervag** [comment]
Hmm... I think perhaps it makes sense to let paragraphs span environments. One way to solve this would be to utilize syntax information. I.e., if inside a math environment (possibly also other), then `gq` should not do anything.

I'll look at it when I get the time, and I'll consider implementing improved support for sentences when we agree that the paragraph motion and text object is defined correctly.

**Comment by Rmano** [comment]
@lervang, being on the topic, have you seen http://vi.stackexchange.com/questions/6004/text-formatting-cvs-friendly (shameless plug... ;-))?

**Comment by nilsbecker** [comment]
@lervag it is a tricky question, which i think deserves some calm thinking. it's really about defining very clearly what the various text objects should be. one could perhaps make a canonical example file and test the desired behavior on that. i would be happy to test. 

anyway, here is another thought: one could also potentially keep the vanilla definition of paragraph (between blank lines) and add an extra text object which would be a 'latex block' or some such. this would then stop at any environment boundary. sentences would always be within a vanilla paragraph, but may overlap more than one latex block... not sure if this is best but it's an idea.

@Rmano this sounds useful in specific contexts but seems to be rather a separate feature? in other words i would think what you propose should probably not be standard?

**Comment by Rmano** [comment]
@nilsbecker  yes, maybe you're right. It's basically how I format the paragraph in LaTeX, and it would be nice to have it as a possible `gqip` effect --- even across equations ans similar things. But yes, I agree it seems more a separate feature.

**Comment by lervag** [comment]
@nilsbecker I agree! I already have a test file for the formatting. We could use the same file also for motions and text objects. I very much like the idea of defining cases first, then defining how text objects, motions and the formatter function should do on the particular cases.

The existing test file is found [here](https://github.com/lervag/vimtex/blob/master/test/feature/formatter/format.tex). I propose that we continue the discussion here, and that I update the test file as we go.

So, we need to determine the behaviour of:

- [ ] Text objects: `ap`, `ip`, `as`, `is`
- [ ] Motions: `}/{` (and possibly others?)
- [ ] Formatter (`gq`)

@Rmano Thanks for the input. Feel free to join the discussion here.

**Comment by nilsbecker** [comment]
cool. here is a possibly harder nut for the formatting and alignment, in case you're looking for additional material (needs amsmath, multirow)
```
\begin{gather}
	\label{eq:model1proof}
	\begin{aligned}
	p(\tau_i,\tau_j,\tau_{jk}) &= p(\tau_i,\tau_j)p_{md}(t_{jk}|\tau_j) \\
														 &\propto \exp \Bigl[ - 1/2 \Bigl\{ 
	\bigl(\begin{smallmatrix}\tau_i\\ \tau_j\end{smallmatrix}\bigr)^T C_{i,j}^{-1}
	\bigl(\begin{smallmatrix}\tau_i\\ \tau_j\end{smallmatrix}\bigr)
		+ \frac{(\tau_{jk} - \rho_{md}\tau_j)^2}{1-\rho_{md}^2} 
	\Bigr\} \Bigr]
\end{aligned} \\ 
= \exp \left[ - \frac{1}{2\bar{\rho}} 
	\begin{pmatrix} \tau_i \\ \tau_j \\\tau_{jk}\end{pmatrix}^T
	\left(\begin{array}{ccc} 
			\multicolumn{2}{c}{\multirow{2}{*}{$\bar{\rho}C_{i,j}^{-1} + 
\begin{pmatrix}0 & 0 \\ 0 &  \rho_{md}^2\end{pmatrix}$}} & 0 \\
									& & -\rho_{md} \\
			0 & -\rho_{md} & 1
	\end{array}\right)
\begin{pmatrix} \tau_i \\ \tau_j \\\tau_{jk}\end{pmatrix}
\right]
\end{gather}
```

**Comment by Rmano** [comment]
I think that LaTeX paragraph could be defined just as block of text separated by blank lines; the only command that stop/start them apart from this should be the sectioning ones (and I think that anyway, everybody should add a blank line there too...). An equation does not automatically break a paragraph, for example. 

Now, I agree with @nilsbecker  that a *displayed* equation at least intuitively should break a sentence object --- even if linguistically (sp?) speaking this is not always the case. I think most people write the displayed equation on individual lines and when reformatting the paragraph the should stay put.  

I would be happy if `gq` command would simply skip equations or things like that --- I think that aligning math environment is so complex it's better done by hand --- minus a general indentation of the environment to the nesting level, that is.

**Comment by nilsbecker** [comment]
@Rmano  this could be a guiding principle: the `p` in vim should correspond to what latex makes into a paragraph in the output. that would give more or less the usual definition 'between blank lines'. i also that sentences can span displayed equations. so maybe the first example in this thread should just not be fixed, i.e. " `das` can screw up environment boundaries, deal with it."

but i think we still want `gqip` to leave nicely formatted equations within a paragraph alone. the logic for that should then be within `gq`, and not in the paragraph text object.

**Comment by nilsbecker** [comment]
another snippet:
```
Math can be inline, $x=y$, or it can be new-style inline \(z=w\), with punctuation expected outside of the
 environment. However, text inside math \(y=z,\text{, therefore }x=w\) can contain punctuation. Display 
math may occur inside a line in the source like this, \[d^2=r,\] where punctuation is expected inside the
 environment. Of course it is clearer to break the line for 
\[ r^2=u,\]
or even
\[
(u^3,v^3)=(y,g),
\]
still producing a single paragraph in the output which ends with
\begin{equation}
w=r^6.
\end{equation}

A new paragraph needs a blank line.
```

**Comment by nilsbecker** [comment]
here is a figure environment where currently `gqip` and `=ip` disagree how the caption should be indented, and both don't do a very convincing job at indentation.
```
\begin{figure}[htpb]
	%\includegraphics[width=1.0\linewidth]{fig/mod12rhoo.pdf} 
	\centering
	\caption{\label{fig:mod12rhoo}%
            kaslj fjalkskjd fk ($\rho^o_{md}$, lower curve sets) skdj lkajs kfjlasdkjf 
            ($\rho^o_{ss}$, upper curve sets) a lsdkdj alskdjf alskdj flaksdjf laskdjfk
            ladskfja lskdkjfj alskdjf sldkfjs alskdjf slaklsjdfj jksyj
            jfaksjf lkasjdfj alkdsfjf kdjf f slkdjfjalskdjfj alaskdjf kdj
            \(\rho_{md},\rho_{ss}\) alksdjf laksdj 
            lakdsjfl lasdkfj fjalskdfj alskdjkfj }
\end{figure}
```

**Comment by nilsbecker** [comment]
another one where i noticed imperfect behavior of `gq`:
```
\begin{enumerate}
	\item Asdfkl fjaskdf laskdfj skdjflksad fl. Aslkdjas lsskj fksdfj 
alsdj alsdkj alsdkjf sldf. Alkdj asldfj, \(y=z \).
	\item Lakdjfj jaskfj $x=y$ skjdf laks; asldfj asdf. Kjas sl sdkjfd .
\end{enumerate}
```

**Comment by lervag** [comment]
Ok, it's been a long time, but now I'm getting ready to consider this issue again.

To repeat and summarize, we need to decide the "proper" behaviour for:

- [ ] `as` and `is`
- [ ] `ap` and `ip`
- [ ] `}` and `{`
- [ ] `gq`

Let me know if there are other mappings/features that should be considered. I'll use this list as a working TODO list, and I'll update if necessary.

After having worked for quite some time with the current altered behaviour for `{` and `}`, I've decided that I don't really like it. I propose to revert to standard Vim behaviour for these motions. One could possibly add new motions similar to the current motions, but I am not certain that these are really necessary.

Regarding `is` and `as`, I propose to make a simple adjustment and compromise: Sentences are delimited by sectioning commands and environments, as well as the normal dots. I think this will make the text object more useful, even though it might not be semantically 100% accurate.

`ap` and `ip`: How about using a similar reasoning as for the paragraph motions? I.e., delimit by empty lines?

Finally, `gq`: I think we should add necessary corner cases to allow more intelligent formatting. I can easily see the value of this feature. I've started to use Vader for continuous testing, and I propose that we define tex examples upon which we apply `gq`, and that we provide the expected results. This will allow me to develop the `gq` command in a test-driven manner. I've already added one test, see [here](https://github.com/lervag/vimtex/blob/master/test/vader/format.vader).

**Comment by nilsbecker** [comment]
> After having worked for quite some time with the current altered behaviour for { and }, I've decided that I don't really like it. I propose to revert to standard Vim behaviour for these motions.

i too have been thinking that using standard vim behavior as much as possible is good. e.g. it's intuitive to look at a block of contiguous line and then select them with `vap`, irrespective of whether they contain also an `equation` block. and actually this also corresponds to latex semantics; equations without preceding empty lines are formatted in the same paragraph. 

so i would vote: `p` text object between empty lines as usual, and `{,}` moving between so-defined paragraphs, as usual.

for `s` i'm torn. how well would the proposed delimiting work? would it stop sentences just at `\begin` or `\end`? if yes then common formatting commands would not disrupt a sentence, which is good. is there a common environment that is often used within the flow of a sentence? i can't think of any right now, but i would argue that `$...$` and `\( .. \)` should not disrupt a sentence. hmm if it works well why not. otherwise standard full stop to full stop/?/! would also work for me.

this simplified logic puts more of the formatting burden on the definition of `gq`. test-driven development sounds good! see also my comment in #317 .

**Comment by lervag** [comment]
Ok, I decided to revert the motions `{`, `}` and the text objects `ap` and `ip` to the Vim defaults. I think this makes more sense. I've updated accordingly.

I also think it will make sense to implement a sentence text object that understands at least some LaTeX specific stuff. I've opened a new issue for this, see #437. It is good if we can continue the discussion about the sentence text object there.

**Comment by rafaeln** [comment]
That's a shame. I was liking the nonstandard behavior. The fact that you didn't decide to use a variable that the user could set in their vimrc to control whether one gets the standard or nonstandard behavior probably means you consider keeping the code for the nonstandard behavior unnecessary bloat.

![image](https://cloud.githubusercontent.com/assets/2940362/14690123/e8736fe8-0720-11e6-90c6-44be04940803.png)

**Comment by lervag** [comment]
Sorry about that. Which behaviour did you like? I could leave the functions there. This would make it possible for you to map them manually. The motions may be mapped already, since the motion function was not removed, i.e.:

```vim
  nnoremap <silent><buffer> } :call vimtex#motion#next_paragraph(0,0)<cr>
  nnoremap <silent><buffer> { :call vimtex#motion#next_paragraph(1,0)<cr>
  xnoremap <silent><buffer> } :<c-u>call vimtex#motion#next_paragraph(0,1)<cr>
  xnoremap <silent><buffer> { :<c-u>call vimtex#motion#next_paragraph(1,1)<cr>
  onoremap <silent><buffer> } :execute "normal v}"<cr>
  onoremap <silent><buffer> { :execute "normal v{"<cr>
```

**Comment by rafaeln** [comment]
Oh, I didn't realize I could do this. Thank you. Where should I put these lines, though? If I put them in `.vimrc`, it seems to run before the plugin or something, because then I open tex files and the mappings aren't changed. If I then `source ~/.vimrc`, I finally get the desired nonstandard settings.

**Comment by lervag** [comment]
No problem, I haven't documented this, so it's not surprising that people don't recognize it. Actually, I think it should work if you simply put it in your vimrc file. If not, then it definately should work if you put it in `.vim/after/ftplugin/tex.vim`.

**Comment by rafaeln** [comment]
Thanks for the tip. It does work when added to `~/.vim/after/ftplugin/tex.vim`
