### ISSUE TITLE
Enhancement Request: Template Support

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#321]
One feature that I liked about Vim-LaTeX-Suite was the ability to define and use LaTeX templates for common tasks (course notes, course assignment, journal article, etc.). I have seen Vim plugins that allow for easy use of templates based on file type (e.g. https://github.com/aperezdc/vim-template). But, these plugins do not (as far as I could see) allow for multiple templates for a given file type.

The template would define at least a custom preamble (packages, user-defined commands, \renewcommand statements, etc.) and potentially a bibliographic skeleton at the bottom of the document. I could just store the templates as text files on my filesystem that I copy and paste manually into my working directory... but, ughhh.

The "API" I would like to see available for vimtex is a vimtex variable that allows me to specify a directory on my system where my templates are stored (e.g. `g:vimtex_templates_dir`) and a vimtex command that allows me to load a specified template (e.g. `<plug>VimtexTemplateLoad`).

Additionally, it would also be nice to see a description of all of the templates. This could be managed by including a LaTeX comment at the top of each template file that describes the template. Vimtex could read that first comment for the description and print it alongside the file name when the user is selecting a template.

@lervag, If you do not plan/want to implement this in vimtex then could you/someone suggest an alternative? I've thought about using UltiSnips but this seems a little "heavy" (read: heavy-handed) for UltiSnips.

**Comment by Rmano** [comment]
Hmmm...  why do you think that UltiSnips is not a good tool for this? I have 

```
snippet templ-tikz "Tikz figure template" b
\documentclass{standalone}
\usepackage{tikz}
\usetikzlibrary{arrows,positioning,calc}
\begin{document}
\begin{tikzpicture}[
    thick]
        $0
\end{tikzpicture}
\end{document}
endsnippet
```

in my personal snippets file and it works like a charm, plus it would let you use substitution or default text or whatever...

**Comment by lervag** [comment]
I agree with @Rmano, it seems to me UltiSnips (or similar snippet engines) are perfect for this task. It should be a very easy task to use your existing templates to create a snippet file, and to keep things clean you could add those snippets into a separate snippet file that is included in the main file. That is what I do myself.

**Comment by fuzzybear3965** [comment]
The reason I didn't want to use UltiSnips was just because I didn't want to clutter my snippets file with entire templates. Also, I'm always eager to find out what other people are doing and if there is some better solution out there, either in terms of design or in terms of productive value. But, @lervag, you're right, I can include these snippets as separate files. I will do that.

Thanks, @Rmano, for the encouragement.

**Comment by Rmano** [comment]
It is probably possible to use a regexp, python-interpolated UltiSnip that "fetches" a template file in a specific directory.... I'll put it in the "things to explore" and when I'll find some time I will try a go at it.

**Comment by lervag** [comment]
@fuzzybear3965 I also very much like to understand how other people solve similar issues, so I am just happy you started the discussion. I think this particular topic is nicely handled by snippets, though, so I don't think it requires any further updates to vimtex.

@Rmano Feel free to share if you are able to create such a snippet with UltiSnips!
