### ISSUE TITLE
Correct way to input quotes?

### ISSUE THREAD

**Issue by anjiro** [lervag/vimtex#325]
Normally in LaTeX I write curly quotes with

    ``hello''

But using vimtex, `` ` `` is mapped to `g:vimtex_imaps_leader`, which means to type two literal backticks I have to type `` ` `` four times instead of two. Putting in quotes is a pretty common activity, so I assume I'm missing something obvious here...

**Comment by lervag** [comment]
You can change `g:vimtex_imaps_leader` to something else, e.g. with the following line in your `.vimrc` file:

```vim
let g:vimtex_imaps_leader = ';'
```

Personally, I like the idea of using an automatic snippet for these curly quotes, e.g. (example with both neosnippet and UltiSnips):

```vim
" With neosnippet
inoremap <silent><expr> " neosnippet#anonymous("``${1}''${0}")

" With UltiSnips
inoremap <silent> " "<c-r>=UltiSnips#Anon("``{$1}''$0", '"', '', 'i')<cr>
```

**Comment by Rmano** [comment]
I have a normal snippet --- like 
```
snippet " "Latex quote" i
\`\`$1''
endsnippet
```

which works quite well (it's `"` + `TAB`, still fast)
