### ISSUE TITLE
`%` goes backwards when out of pair

### ISSUE THREAD

**Issue by michamos** [lervag/vimtex#329]
`%` behaves differently with `vimtex` from standard Vim.

To reproduce, start Vim with the provided `minivimrc` as `vimrc` (using the `-u` option), and in an empty Vim buffer (that does **not** have `ft=tex`), add the line 
```
(aaa) bbb (ccc)
```
Place the cursor on the first `b` and execute the command `d%`.
**Result**: `(aaa) `.

Do the same thing in a buffer with `ft=tex` (for example, add that line to the `test/template/minmal.tex` file).
**Result**: `bb (ccc)`, meaning that the `%` motion goes backwards when using Vimtex instead of forwards.
This is a general feature, and occurs for many paired delimiters (`{...}`, `$...$`, etc.) and makes the `%` motion completely useless when being outside a pair.

**Comment by lervag** [comment]
Hmm, no, this does not reproduce with me. That is, I can confirm that the motion is unexpected outside of `$...$` pairs, but not for the other ones.

**Comment by lervag** [comment]
Should be fixed in the recent update.

**Comment by michamos** [comment]
:+1:  it works great now!

**Comment by lervag** [comment]
Great :)
