### ISSUE TITLE
Expanding label gives error with package siunitx

### ISSUE THREAD

**Issue by martinwk** [lervag/vimtex#331]
I started using sunitx to have consistent notation of the units in my thesis. This however breaks down the omnicompletion of `\ref{` when the `\si{}` command is used inside a figure. Is there any solution for this?

``` latex
\documentclass{memoir}
\usepackage{siunitx}
\usepackage{graphicx}
\begin{document}
\begin{figure}[tbp]
  \centering
  \includegraphics[height=\linewidth]{somefig}
  \caption{sdadasda \si{\m}}
  \label{fig:fig1}
\end{figure}
\ref{fig:}
\end{document}
```

**Comment by Rmano** [comment]
Hmmm... tried your example, but it worked perfectly for me (I'm using supertab). If I put the cursor after the `:` and press TAB y have the label expanded correctly to `fig:fig1`.

**Comment by lervag** [comment]
I've been able to reproduce. It seems that the documentclass is important. I'll look into it when I get the time.

**Comment by martinwk** [comment]
@lervag thanks for taking the time to look into it. Just let me know when you need more info (.vimrc or so). I forgot to mention that if you remove the `\si` command from the caption, `omnicompletion` of the fig:fig1 labels works fine.

BTW much of thanks for this great tool you developed and develop!

**Comment by lervag** [comment]
I found a problem with a substitute for tex to unicode conversion. It seems to fix this issue.

**Comment by lervag** [comment]
And no problem, I'm happy you like the plugin! :)

**Comment by martinwk** [comment]
Excellent! Works like a charm now. Many thanks once more.

**Comment by lervag** [comment]
Great!
