### ISSUE TITLE
Purpose of F7 not clear from documentation

### ISSUE THREAD

**Issue by yossigil** [lervag/vimtex#335]
I read the README file and could not figure out what F7 does and how should it be used.

**Comment by lervag** [comment]
First, reference to [related vi.stackexchange.com post](https://vi.stackexchange.com/questions/6242/whats-the-purpose-of-f7-in-vimtex-how-is-it-used).

Note, there are no explanations in the README file. The documentation is in the normal vim help file system. Have you read the docs? See in particular `:h <plug>(vimtex-create-cmd)`.

**Comment by lervag** [comment]
Further: It is very unclear to me what exactly that you do not understand. If you could explain better, then I might consider to update the docs.

**Comment by yossigil** [comment]
I opened the full documentation (in https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt) and searched for the two occurrences of F7. They did not make any sense to me. I could not understand how this command should be used and what it does.

**Comment by lervag** [comment]
The first occurence simply lists the different functionalities. The second shows what `<f7>` is mapped to, with a link to the `<plug>(vimtex-create-cmd)` mapping description. The mapping is explained there. I added some minor text to link these sections better. I hope that better explains things for you.

**Comment by paullamar3** [comment]
I found the documentation confusing as well. I had to experiment to understand what it was doing. You might want to change the documentation to something like:

**Comment by lervag** [comment]
It seems there is a problem with the normal mode version of the command/mapping. I've opened a new issue for this, see #336. It seems to work as expected when used in insert mode, though.

I've updated the docs, I hope that will prevent future confusion. Thanks for the suggestion!

**Comment by lervag** [comment]
Just want to mention that I've fixed #336, which means the `<f7>` mapping should work better now, in particular from the normal mode.
