### ISSUE TITLE
Ampersand (&) in superscript in caption breaks omnicompletion of labels

### ISSUE THREAD

**Issue by martinwk** [lervag/vimtex#337]
I have a problem similar to my previous issue (#331 )

I want to have a superscript in my caption, but in text mode. Furthermore, this text has an ampersand in it. To achieve this I use `\(^\text{K\&K}\)`. The type setting is correct, but when using this in a caption, it breaks down the omnicompletion (`<C-X><C-O>`) of the label in `\ref`. It seems to be caused by the combination of all these three things

1. use \text{} in math environment
2. Use ampersand \&
3. Inside a caption

I any of these three is not the case, it works fine; it has nothing to do with the superscript. Any solution or work around?

```
\documentclass{memoir}
\usepackage{graphicx}
\usepackage[fleqn]{amsmath}
\begin{document}
\begin{figure}[tbp]
  \centering
  \includegraphics[height=\linewidth]{/home/martin/Pictures/Images/Displace.png}
  \caption{Blabla \(\text{K\&K}\) }
  \label{fig:fig1}
\end{figure}
\ref{fig:fig}
\end{document}

**Comment by lervag** [comment]
Thanks, I've reproduced the problem and updated the previous test files (for #331).

**Comment by lervag** [comment]
Ok, I've fixed this by removing something that I'm not really sure what does (funnily enough). It seems the code still works on all the examples I have, and so I think it might be safe. Let me know if this breaks something for you somewhere else!

**Comment by martinwk** [comment]
Yes seems to work! It does not seem to break something else too, so that is even better :)

**Comment by lervag** [comment]
Great! Just let me know if you find any problems. I'll cross my fingers and hope it just works (tm). :)
