### ISSUE TITLE
zathura synctex support broken since version 0.3.4 (on Archlinux)

### ISSUE THREAD

**Issue by nasenatmer** [lervag/vimtex#338]
Hey, 

I just wanted to let you know that it seems that yesterday's update to the new version of zathura (`0.3.4`) on Archlinux made it stop working with the `-x` switch.

Neither `\ll` nor `\lv` will successfully open a zathura window.

My settings are unchanged from before, I only set `let g:vimtex_view_method = 'zathura'`, no other customisation of zathura settings.

When trying to open a file from command line with the new zathura, I get:
```sh
zathura -x "vim --servername VIM --remote +\%{line} \%{input}" /home/jakob/masterthesis/masterthesis.pdf
error: Error parsing command line arguments: Unknown Option -x
```

Downgrading to 0.3.3 immediately solves the issue. I'm trying to report the bug at upstream but it seems their gitlab doesn't work right now. Also, it could be that the Arch Linux build of zathura is without support for synctex so it need not necessarily be a problem of `0.3.4` but of Arch's version.

However, I'm unable to build a version from git myself, so I can't nail it any further down. Has anybody else got an idea?

**Comment by nasenatmer** [comment]
Ok, I figured it's [this patch](http://article.gmane.org/gmane.comp.editors.zathura/564/) that seems to disable synctex by default, at least the way it is included in the Arch Linux [PKGBUILD](https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/zathura). I'll let the people on zathura mailing list know.

Sorry for spamming this here. This issue basically describes my learning process here.

**Comment by sebastinas** [comment]
This patch does not disable synctex by default. This patch makes zathura not fail to build if libsynctex is not available. You need to build zathura against libsynctex to have synctex support.

**Comment by lervag** [comment]
I noticed the new version of Zathura, but I have not updated yet. Thanks for the info, @nasenatmer! I would be happy if you could let me know what you find.

@sebastinas: @nasenatmer is using version of zathura that comes from Arch Linux's Community repository, [see here](https://www.archlinux.org/packages/community/x86_64/zathura/). Version 0.3.3 of zathura has been working correctly. Perhaps the maintainer did not build the new version with libsynctex?

**Comment by lervag** [comment]
@nasenatmer Perhaps you should also notify the Arch Linux maintainer, Johannes Löthberg?

**Comment by nasenatmer** [comment]
Ah, now I understand why my own build worked: Because I have libsynctex installed (as a part of `texlive-bin`), and **not** because I removed the patch from the `PKGBUILD`. I was a careless there.

@lervag: [Caleb reported](https://lists.pwmt.org/archive/zathura/2016-February/001459.html) this to the Arch [bug tracker](https://bugs.archlinux.org/task/48010) already.

**Comment by lervag** [comment]
@nasenatmer Thanks for the information and effort! I hope the problem will be fixed soon!

**Comment by nasenatmer** [comment]
Apparently, this has been fixed by the Arch Linux maintainers now https://bugs.archlinux.org/task/48010

**Comment by lervag** [comment]
Great!
