### ISSUE TITLE
Zathura viewer stopped working

### ISSUE THREAD

**Issue by Eisfreak7** [lervag/vimtex#339]
Hi,
yesterday my zathura was updated to version 0.3.4.
Since then, `VimtexView` with
`let g:vimtex_view_method="zathura"`
doesn't work anymore (either nothing happens or sometimes it shows an error about not being able to detect the zathura window id).
With the view method set to "general" it works, however. So apparently there have been breaking changes in the zathura interface.

**Comment by lervag** [comment]
Please see #338.
