### ISSUE TITLE
g:vimtex_delim_toggle_mod_list default should not include the versions without l,r

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#347]
i think a reasonable default for that list would be `nothing, \left, \bigl, \Bigl, \biggl, \Biggl` or maybe only `nothing, \left`. the versions `\big` etc are more special-purpose, for non-matched delimiters and should not be default.

**Comment by lervag** [comment]
I'm tempted to agree. I'll leave this open for some days first, and see if there are more reactions and opinions. In the meantime, you can use the option.

**Comment by lervag** [comment]
Just for reference: This issue is closely related to #229.

**Comment by lervag** [comment]
I think this is a more sensible default. It should be easy to set a custom list.
