### ISSUE TITLE
feature wish: jump to label

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#348]
on `\ref{eq:xyz}` it would be cool if one could jump to (the first occurrence of) the corresponding label. i tried `c-]` but that did not work. would it make sense to population the tags list with all existing labels?

**Comment by lervag** [comment]
I think this is best solved using tags. See e.g. [here](https://stackoverflow.com/questions/8119405/create-tags-file-for-latex-for-labels-and-bib-items). I'm not sure this should be part of vimtex.

**Comment by lervag** [comment]
If we figure a good way to solve this, even without new vimtex code, perhaps we should add an entry to the docs.

**Comment by nilsbecker** [comment]
that sounds right, thanks for the pointers. for reference, there is also this: 
http://vim-taglist.sourceforge.net/extend.html which has a long latex-specific entry. possibly it's too much/would need to be adapted to the vimtex philosophy.

**Comment by lervag** [comment]
Personally I'm using [vim-gutentags](https://github.com/ludovicchabant/vim-gutentags) for generating tags files automatically. It seems to me that the solution in the stackoverflow question provides a relatively good behaviour for me.

Let me know what you end up doing. I might consider to add this to the docs, as I mentioned. In the meantime, I'm closing this since I don't think there will be any other updates to the code.

**Comment by nilsbecker** [comment]
i'm using this snippet from one of the linked pages in `~/.ctags` now:
```
--langdef=tex2
--langmap=tex2:.tex
--regex-tex2=/\\label[ \t]*\*?\{[ \t]*([^}]*)\}/\1/l,label/
```
i'm also trying gutentags now. so far it seems to be working for my purposes!

**Comment by lervag** [comment]
Thanks! I've added a short entry to the faq section.

**Comment by nachovizzo** [comment]
@lervag is there any intuition for the requirement on this particular configuration for ctags? I've been trying it so far, and it's working out of the box when using universal ctags. I also did not require modifying it ot make it work with .bib files (#853)

On the vimtex documentation, it suggests doing both modifications, but I'd love to know what is that I'm missing if I don't do it. Any idea?

**Comment by lervag** [comment]
You are bumping an issue that is 7 years old. Your question would be much better if you asked it in a new issue and provided all necessary context. Any context in this thread may be very outdated!

> @lervag is there any intuition for the requirement on this particular configuration for ctags?

Which requirement? What are you referring to? In the docs, I recommend Universal Ctags (see `:help vimtex-af-tag-nav`). The FAQ section you are referring to is quite old, so perhaps the configuration mentioned there is no longer necessary?

If you think it might be relevant to update the docs, then please, open a new issue and be somewhat more specific. I'll be happy to update if you are right.
