### ISSUE TITLE
NeoComplete does not work

### ISSUE THREAD

**Issue by ernestorenanche** [lervag/vimtex#350]
I cannot get the auto-completion to be triggered automatically by NeoComplete. It works fine with `<C-X><C-O>`.

**Comment by lervag** [comment]
> I cannot get the auto-completion to be triggered automatically by
> NeoComplete. It works fine with <C-X><C-O>.
>
Have you read the docs? You can find a recipe for neocomplete there, see
`:h vimtex-neocomplete`.

>

**Comment by lervag** [comment]
Sorry, the reference should be `:h vimtex-complete-neocomplete`. The following options should work:

```vimL
  if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
  endif
  let g:neocomplete#sources#omni#input_patterns.tex =
        \ '\v\\%('
        \ . '\a*%(ref|cite)\a*%(\s*\[[^]]*\])?\s*\{[^{}]*'
        \ . '|includegraphics%(\s*\[[^]]*\])?\s*\{[^{}]*'
        \ . '|%(include|input)\s*\{[^{}]*'
        \ . ')'
```

**Comment by ernestorenanche** [comment]
Yes I did read the doc and copied-pasted the previous code in my .vimrc. However it does not work. I checked that NeoComplete is correctly installed: I can enable it if needed.

**Comment by lervag** [comment]
Then there are problems with your configuration, and the problem is related to neocomplete, not with vimtex.

If you provide the relevant parts of your vimrc file, I can try to find the problem.

**Comment by ernestorenanche** [comment]
Here is [a link](https://gist.github.com/ernestorenanche/25899d6b400ed8fa3011) my .vimrc

The neocomplete config for vim-tex is line 130.

Thank

**Comment by lervag** [comment]
You have not enabled neocomplete, you should add: `let g:neocomplete#enable_at_startup = 1`.

**Comment by ernestorenanche** [comment]
If I do that neocomplete will popup as soon as I start typing commands (not what I want).
![neocomplete-vimtex](https://cloud.githubusercontent.com/assets/16289623/12974133/cb272916-d0b1-11e5-86d0-a0ad4d957788.png)

**Comment by lervag** [comment]
That is because of how neocomplete works. As I said, this is a neocomplete problem, not a vimtex problem! You should read the documentation for neocomplete!

However, to make things easy for you, you should read `:h g:neocomplete#sources`.

**Comment by ernestorenanche** [comment]
Ok I put it here if somenone looks for it : you have to add
`call neocomplete#custom#source('buffer', 'disabled', 1)`
in your .vimrc

**Comment by lervag** [comment]
Yes, that should do it. :)
