### ISSUE TITLE
`ci$` in `\[ ... \]` does not indent closing delimiter correctly

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#352]
Let * the cursor position
Then `ci$` on
```
  \[
      ...*
  \]
```
gives
```
   \[  
*\]
```
Expected:
```
  \[
     *
  \]
```

**Comment by lervag** [comment]
Thanks, I agree this should be changed.

**Comment by Konfekt** [comment]
One idea to solve this: Make `ie` generally exclude the inner white space padding (`\v(\s|\n)` as a vim regex)  around the delimiters.

**Comment by lervag** [comment]
I've pushed an update that should make this more consistent for all of `ie`, `i$` and `id`. I think it should fix the problem, but I might have missed something. Note that the inner matching now behaves differently for different cases, i.e.:

```tex
% i$ matches everything inside, including spaces, in all of these cases

\[ f(x) = 1 \] % di$ => \[\]

\[
 f(x) = 1 \] % di$ => \[\]
 
\[ f(x) = 1
  \] % di$ => \[\]

% i$ only matches the lines, not including the delimiters, preserving indent
\[
  f(x) = ...
    ...
\]
% di$ =>
\[
  % cursor
\]
```

**Comment by lervag** [comment]
Optimally, there should be a slight difference between `di$` and `ci$`, however, I don't know how to do that. Thus I think the current version is a good compromise that should be what one wants in most cases.

**Comment by Konfekt** [comment]
Thanks! Works perfectly. Not sure what slight difference there ought to be between `di$` and `ci$`.

**Comment by lervag** [comment]
I think the best behaviour would be:

```tex
% original
\[
  f(x) = ...
\]

% di$
\[
\]

% ci$test<esc>
\[
  test
\]
```

But as I said, it does not seem important.

**Comment by Konfekt** [comment]
Ok, that's debatable though. The current behavior seems as fine too me.

**Comment by lervag** [comment]
Nothing is better than that :)
