### ISSUE TITLE
Opening top level brace lag

### ISSUE THREAD

**Issue by avfonarev** [lervag/vimtex#354]
I'm sorry if it has been already discussed before and/or is a dumb question (I've spent some time looking for an answer).

My problem is whenever I'm inserting a top level opening brace, vim hangs for a couple of seconds.
Here is what profiling tells me (tested on a 700 line mathematical paper, the only thing I did was enter insert mode and press `{`):

```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
 1825              2.710943  vimtex#util#in_syntax()
   19              0.124893  <SNR>15_Highlight_Matching_Pair()
    1   2.750222   0.032972  <SNR>28_get_matching_delim()
 1824   2.724429   0.013670  vimtex#util#in_comment()
   13   0.005183   0.004875  <SNR>28_get_delim()
   14   2.763731   0.000712  <SNR>37_highlight_matching_pair()
    1   0.001013   0.000479  VimtexIndent()
    4              0.000279  <SNR>44_count()
   13   0.005429   0.000246  vimtex#delim#get_current()
   13   2.750411   0.000189  vimtex#delim#get_matching()
    1   0.000308   0.000119  <SNR>28_parser_delim()
    1              0.000116  <SNR>28_parser_delim_get_corr()
    2              0.000073  <SNR>28_parser_delim_get_regexp()
    1   0.000255   0.000049  vimtex#delim#get_valid_regexps()
    1   0.000206   0.000022  vimtex#util#in_mathzone()
```

Tested on an almost vanilla vim (here is my [.vimrc](https://github.com/avfonarev/dotvim/blob/master/vimrc)). Of course, whenever I turn syntax off, everything works pretty fast.

The lag happens whenever quite a lot of lines follow (I've used vim for a couple of days only, but do understand that it's looking for a matching brace scanning through the remaining 700 lines). Turning off vimtex does make the experience bearable.

Thank you in advance and sorry for inconvenience.

**Comment by lervag** [comment]
No inconvenience! I was hoping this wouldn't be a problem, but I see that it is. The problem is as you say the search for a matching brace. I'll fix it as soon as possible.

**Comment by lervag** [comment]
Btw: In the mean time, you can use `let g:vimtex_motion_matchparen = 0` to turn off the highlighting. This should speed things up until I fix the problem.

**Comment by lervag** [comment]
I think the last update should fix the problem.

Note: I've restricted a lot of the searching for matched delimiters/environments. This might not be the desired behaviour, as it might break e.g. the `%` motion command whenever the target delimiter is outside of the current window scope.

I'd love to get some feedback on if the latest version is fast enough, after which I might update to allow wider searches for manual commands (e.g. `%` and `cse` and similar).

**Comment by avfonarev** [comment]
First of all, thank you for such a quick update.

I've just done some profiling. In both cases an opening brace was inserted on an empty line following `\documentclass` in a medium sized maths paper. The results are really good.

4521f587bbf4abf8
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    2   3.949592   0.000140  <SNR>41_highlight_matching_pair()
    2   3.948191   0.000137  vimtex#delim#get_matching()
    2   3.948054   0.045835  <SNR>32_get_matching_delim()
 3646   3.902381   0.026345  vimtex#util#in_comment()
 3647   3.876240             vimtex#util#in_syntax()
    3   0.398259             <SNR>18_Highlight_Matching_Pair()
    2   0.001099   0.000017  vimtex#delim#get_current()
    2   0.001082   0.000389  <SNR>32_get_delim()
    1   0.001009   0.000421  VimtexIndent()
    2   0.000693   0.000217  <SNR>32_parser_delim()
    4   0.000317             <SNR>48_count()
    1   0.000271   0.000040  vimtex#delim#get_valid_regexps()
    4   0.000257             <SNR>32_parser_delim_get_regexp()
    1   0.000231   0.000027  vimtex#util#in_mathzone()
    2   0.000219             <SNR>32_parser_delim_get_corr()
```

4521f587bbf4abf8 with `g:vimtex_motion_matchparen = 0`

```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    4   0.385781             <SNR>18_Highlight_Matching_Pair()
    1   0.001065   0.000438  VimtexIndent()
    1   0.000328   0.000037  vimtex#delim#get_valid_regexps()
    4   0.000299             <SNR>48_count()
    1   0.000291   0.000025  vimtex#util#in_mathzone()
    1   0.000266             vimtex#util#in_syntax()
```

c6b0d6e994d0ee14
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
    3   0.396277             <SNR>18_Highlight_Matching_Pair()
    2   0.005641   0.000133  <SNR>41_highlight_matching_pair()
    2   0.004356   0.000125  vimtex#delim#get_matching()
    2   0.004231             <SNR>32_get_matching_delim()
    1   0.000984   0.000422  VimtexIndent()
    2   0.000983   0.000017  vimtex#delim#get_current()
    2   0.000966   0.000389  <SNR>32_get_delim()
    2   0.000577   0.000208  <SNR>32_parser_delim()
    3   0.000341             vimtex#util#in_syntax()
    4   0.000305             <SNR>48_count()
    1   0.000257   0.000040  vimtex#delim#get_valid_regexps()
    2   0.000221             <SNR>32_parser_delim_get_corr()
    1   0.000217   0.000025  vimtex#util#in_mathzone()
    2   0.000169   0.000020  vimtex#util#in_comment()
    4   0.000148             <SNR>32_parser_delim_get_regexp()
```

**Comment by lervag** [comment]
Great, good to know! I believe there will be future adjustments, let me know if you experience the lag again in the future.

The future adjustments will be made in order to allow matching between delimiters that are further apart than within the visible region. However, I will await the adjustments until I experience problems myself or until someone complains.
