### ISSUE TITLE
"undefined command" in nested definitions not shown in the quickfix window.

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#355]
I have a problem that I am not sure if it's possible to solve. Consider the following snippet: 

```
\documentclass{article}

\newcommand{\mycomm}{%
    One two three
    \nocomm
    four.
}

\begin{document}

Word word word \mycomm word. 

\end{document}

```

If you compile it with `<leader>ll` I have an error, clearly, because the command `\nocomm` is not defined. But the quickfix window is like this one: 

```
nested.tex|11 error| Undefined control sequence.
nested.tex|11 error| Emergency stop.
nested.tex|11 error| ==> Fatal error occurred, no output PDF file produced!
```

as you can see, there is no mention of *which* command is undefined. I have to go to a command-line and issue manually the compilation, which will output:

```
[...]
! Undefined control sequence.
\mycomm ->One two three \nocomm 
                                four. 
l.11 Word word word \mycomm
                            word.
? 
```

Is it possible to have the "unkwown" command shown in the error window?

**Comment by nasenatmer** [comment]
Not the answer to your question, but for the time being a faster solution to find the wrong command: `\lo` opens the `log` file so you can directly search for `undefined` or whatever. So there shouldn't be a need for a manual compilation just to get to the error.

**Comment by Rmano** [comment]
@nasenatmer --- thanks, really useful, I didn't know that trick. It really solves 90% of the issue...

**Comment by nasenatmer** [comment]
Glad to help :)

**Comment by lervag** [comment]
Actually, this is really hard. The errorformat system in Vim is not very easy to use, and in particular, I have no idea how to match this specific type of error message output from latex.

I think @nasenatmer's suggestion is the best option for now. If anyone should ever manage to write errorformat code that solves this, I would be happy to accept a pull request. Personally, I think the latexmk output will suffice, and I'll rather spend time solving other issues. I hope that's OK by you.

**Comment by Rmano** [comment]
Yes, it's ok for me. When I'll have time I will try to see if I can dig into the errorformat thing. 

One little thing only if it's on top of your mind, otherwise I'll do my research. It is possible to do some buffer-local definition to the `\lo` window so that it will never go in input mode and hitting "q" will close it?  

Thanks a lot!

**Comment by lervag** [comment]
Hmm. `q` will already close it. I'm not sure what you mean by "never go in input mode". Do you mean "insert mode"? And why do you want to prevent that? The buffer is already set to non modifiable, so insert mode should be prevented.

**Comment by Rmano** [comment]
Ok. Please forget my previous message. Sleepy. Thanks!

**Comment by lervag** [comment]
No problem :-)

lør. 13. feb. 2016, 12.05 skrev Romano Giannetti <notifications@github.com>:

**Comment by Rmano** [comment]
I really found that my problem there was another one, not vimtex-related at all. For reference... 
http://vi.stackexchange.com/questions/6463/have-different-tabs-windows-remembering-their-mode
