### ISSUE TITLE
Can vimtex_imaps_leader be changed/disabled in insert mode when not inside a math environment?

### ISSUE THREAD

**Issue by atorg** [lervag/vimtex#361]
The default setting of `g:vimtex_imaps_leader` is \`.

This works well in a math environment, where \` a completes to `\alpha` for example and there doesn't seem to be any reason to insert a literal \`.

However, outside of a math environment, \` is a commonly used character for quotations (\`\` and '' in Latex).

It seems like when ` is entered in insert mode, vimtex pauses (since this is the leader key) before moving the cursor. This is pretty annoying outside of a math enviroment.

Is there a way to change this behavior? I like \` as the leader, and all of the default insert mode mappings seem to be triggered only within math environments. So perhaps there is a way to turn off \` as the leader outside of math environments?

**Comment by lervag** [comment]
Yes, this is due to how Vim mappings work. You may be interested in knowing about the options `:h 'timeout'` and/or `:h 'timeoutlen'`.

I don't know a good way to fix this, except changing the leader key. Personally I use `;`, which I think works well.

**Comment by Rmano** [comment]
@atorg , I personally worked around this with this small UltiSnippet:

```
snippet " "Latex quote" i
\`\`${1:${VISUAL}}'' 
endsnippet
```
Now I press `"` and `TAB` and I can write the text into quotes; another TAB moves me after the closing pair of quotes (there is a space after the second closing quote in the second line). 

Or even I can visual select the text to be put into quote and with `TAB` `"` `TAB` it's done.

**Comment by atorg** [comment]
The snippet solution is a great workaround! Thanks!
