### ISSUE TITLE
Local problem in big file with label completion: E684 and E15

### ISSUE THREAD

**Issue by nasenatmer** [lervag/vimtex#363]
Hey, 

it seems that sometimes a problem can arise with label completion in big files. I noticed this yesterday in my current project: If I type `\ref{ <c-x>-<c-o>` I get the following error. 

```vim
Error detected while processing function vimtex#complete#omnifunc[21]..10[3]..11[1]..12:
line   28:
E684: list index out of range: 1
Press ENTER or type command to continue
Error detected while processing function vimtex#complete#omnifunc[21]..10[3]..11[1]..12:
line   28:
E15: Invalid expression: tree[0][1][0]
Press ENTER or type command to continue
```

After pressing `ENTER` twice, the completion dialog opens successfully and after selecting an entry I can continue working. After this, the error won't come up anymore.

I don't use any completion engine, just basic vim `<c-x>-<c-o>`.

The problem is that the error does **not happen with a minimum working example**, just with my current dissertation project. First I thought it is caused by the high number of `labels` in my file, but removing all text except `(sub)sections`, `figures` and `tables` didn't help either: The problem does not arise any more. `\lC` and `\ll` also didn't help.

However, it seems independent of the config, since I can reproduce it with a minimal vimrc file.

As I haven't submitted the dissertation yet, I can't post the file here and it seems to be a local problem rather than a real `vimtex` issue. I just felt I want to report it. In case you want to have a look at it, @lervag, I could send you the file via mail, but it is of rather low priority since completion still works after this error.

**Comment by nasenatmer** [comment]
Searching around old issues I found that the aux files sometimes could be of help: [This](https://gist.github.com/nasenatmer/4fd2b67b28e0bd82a23f) is the problematic aux file, and [here](https://gist.github.com/nasenatmer/2fc727bd84158e84be05) the one where the error doesn't come up any more…

**Comment by lervag** [comment]
The problem is related to the line

```tex
\newlabel{RF1}{30}
```

in the `aux` file. If you could explain how and why this line is there, then we could discuss finding someway of treating it.

**Comment by nasenatmer** [comment]
This label is created by the [rotating](ftp://ftp.tu-chemnitz.de/pub/tex/macros/latex/contrib/rotating/rotating.pdf) package's `sidewaysfigure` environment. Here's a MWE:

```tex
\documentclass{scrartcl}
\usepackage{rotating}
\begin{document}
\begin{sidewaysfigure}[phtb]
  \caption{Sidewaysfigure}
  \label{fig:sideways}
\end{sidewaysfigure}
\ref{
\end{document}
```

**Comment by lervag** [comment]
I see. Do you every actually use the `RF1` label for anything?

**Comment by nasenatmer** [comment]
Nope, didn't even know it exists and also I think this package is not a big thing either.

Okay, thanks for the fix! Hope it wasn't too much work!

**Comment by lervag** [comment]
No, it was simple. I ended up pushing before your reply because I couldn't see how the `RF` label was supposed to be used by the end user, and so I assumed (I think correctly) that it is for internal use. As you can see for yourself, the fix was simple. It is typically pretty simple to fix things when I know exactly what the problem is. When you provide minimal examples and enough information, as you typically do, it is often relatively straightforward to fix.

Thanks! :)
