### ISSUE TITLE
Make a/ie linewise

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#365]
The Environment Text object should be linewise as Operator map, That is, :normal Vae<Cr>. For example, When  yanking , yae, this allows for convenient pasting afterwards.

**Comment by lervag** [comment]
Actually, I would claim that it is not this easy. There are several scenarious in which I can see `begin/end` on the same line, for instance:

```tex
\[ a = \begin{bmatrix} 1 \\ 2 \end{bmatrix} \]
```

Here one would not want the operator to be linewise. Also, when we do `cie`, it is much better to preserver the indentation, which is impossible with linewise visual mode.

I agree that in very many cases we write the `begin/end` blocks very structured and on separate lines, and that in very many such cases, the linewise operator would be useful. I think an optimal solution is to have the text object be aware of its operator, but I don't know how.

**Comment by lervag** [comment]
FYI, I've opened a [question on vi.stackexchange.com](http://vi.stackexchange.com/q/6500/21).

**Comment by Konfekt** [comment]
Yeah true, I'd like to withdraw this issue, and in any case only let it apply to yanking. 

If people put `\begin{...} ... \end{...}` environments inline, then `vimtex` should check for this case leave when yanking the selection characterwise. Here, environments are always linewise, and then `yie` and pasting ideally should also be.

**Comment by Konfekt** [comment]
I answered your question by the way. There are a couple of maps using this construction in `.vimrc`. Others:
```vim
onoremap        <SID>(esc) <esc>
omap     <expr> C          '<SID>(esc)' . v:operator . v:count1 . (v:operator ==# 'd' ? '<Plug>(textobj-comment-big-a)' : '<Plug>(textobj-comment-i)')

omap     <expr> <CR>       '<SID>(esc)' . v:operator . v:count1 . (v:operator ==# 'y' ? '<Plug>(textobj-entire-i)' : '<Plug>(textobj-entire-a)')
```

**Comment by Konfekt** [comment]
Thinking about: it, by the operator mapping in http://vi.stackexchange.com/q/6500/21, check if the operator is `y` and then, if `\begin{...}` and `\end{...}` stand alone on separate lines, set the yank register to linewise by 
```vim
  call setreg(a:regname, getreg(a:regname), "l")
```

**Comment by lervag** [comment]
I've begun working on this. I've pushed a commit that actually breaks things now (in that it now uses linewise almost randomly), but it is the first step in fixing things. I'll try to get things sorted out in not too long.

**Comment by Konfekt** [comment]
Thanks! Surprising that for the operator maps the same command as for the visual ones works (https://github.com/lervag/vimtex/commit/ec5e0df3607de6bf6562e60d4fe2759519e9f9a7#diff-10ad055417d0d6c72beacdbc11fbeebaR30). No `execute "normal \<sid>(v)` any longer?

**Comment by lervag** [comment]
No, I found there was no need to go through the visual mode, which made it possible to simplify everything. Besides, the extra step through the `<sid>v` stuff made `v:operator` inaccessible (it was set to `:` before the function was called for the operator maps). That's essentially why I did this, because now I have `v:operator` accessible, and so I can (and will) make the target area for the operator maps depend slightly on which operators are used.

**Comment by Konfekt** [comment]
Ah, I didn't now about this drawback. Understood.

**Comment by lervag** [comment]
I think this should solve the issue. By default it will treat `d` and `y` linewise if possible (i.e. if the delimited region is not "inline"). If you want to treat other operators similarly, you can alter the option `g:vimtex_text_obj_linewise_operators`.

**Comment by Konfekt** [comment]
Thanks!
