### ISSUE TITLE
TiKZ indentation

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#371]
Similar to issue #66, I'm encountering some bad indentation when lines contain a pair of curly braces which are not terminated with semicolons. The following code is formatted as follows

```
% (i) center contact head
\draw [solid] let \p{I} = (centerContactHead) in (centerContactHead) -|
  (\x{I}-.75cm,-2.5) 
  node [yshift=-.25cm] {(i)};
 
% (ii) outer conductor of the contact head
  \coordinate (outerContactHead) at (.8,-1.7);
  \draw [solid] let \p{O} = (outerContactHead) 
    in (outerContactHead) -- (\x{O},-2.5)
      node [yshift=-.25cm] {(ii)};
```
The same code with the desired indentation would look like:
```
% (i) center contact head
\draw [solid] let \p{I} = (centerContactHead) in (centerContactHead) -|
  (\x{I}-.75cm,-2.5) 
  node [yshift=-.25cm] {(i)};

% (ii) outer conductor of the contact head
\coordinate (outerContactHead) at (.8,-1.7);
\draw [solid] let \p{O} = (outerContactHead) 
  in (outerContactHead) -- (\x{O},-2.5)
  node [yshift=-.25cm] {(ii)};
```
I can prevent indentation by adding semicolons immediately after {I} and {O} in the above code segments. Unfortunately, this breaks the TiKZ code. Additionally, if the logical line of code extends onto multiple physical lines (as with this case) the subsequent lines will keep the same indentation as the line which contains the semicolon-unterminated pair of curly braces. So, explicitly, the modified text would look like:
```
% (i) center contact head
\draw [solid] let \p{I}; = (centerContactHead) in (centerContactHead) -|
(\x{I}-.75cm,-2.5) 
node [yshift=-.25cm] {(i)};

% (ii) outer conductor of the contact head
\coordinate (outerContactHead) at (.8,-1.7);
\draw [solid] let \p{O}; = (outerContactHead) 
in (outerContactHead) -- (\x{O},-2.5)
node [yshift=-.25cm] {(ii)};
```
Although I'm not capable of offering a solution in the form of a pull request, it seems that the required solution follows:

1.  Check if the line comprises only whitespace. Ignore indentation if it's just whitespace.
1.  Check if the current physical line is a comment. If it is a comment, then the indentation will be that of the first physical line of the previous logical line. Logical lines are possibly many physical lines with the final physical line being identified with a semicolon termination.
1.  If the current physical line is not a comment/whitespace and is not the start of a logical line, then the current physical line will maintain the same indentation as the first physical line of the current logical line..
2. If it is the start of a logical line then it maintains the same indentation as the first physical line of the previous logical line.

Note that this logic does not at all depend on curly braces used to delimit text. This would at least fix my issue and I think would be an easy way to account for indentation in

**Comment by lervag** [comment]
I agree with how things should look. When I take the example into a clean buffer and do `gg=G`, then I reproduce the problem. However, if I repeat `=G`, then the indentation becomes correct. Can you verify this?

Note, though, that I think the indendation should be correct also on the first iteration, and so I'll investigate and try to understand what is wrong here.

**Comment by fuzzybear3965** [comment]
Yeah, when that text is on its own, I can reproduce the issue. However, in the context of a document it seems like it still isn't working (even with multiple applications of ``gg=G``). Consider the following "minimum working document:

```
\documentclass[10pt]{article}
\usepackage{tikz}
\usetikzlibrary{calc}
\begin{document}

\begin{tikzpicture}
   \draw [solid] let \p{I} = (0,0) in (1,1) -|
      (\x{I}-1cm,-1cm) node [yshift=-.25cm] {(i)};
   % Just some comment
   \end{tikzpicture}
   \end{document}
```
No matter how many times that I ``gg=G`` this document I can't get the ``\end{document}`` unindented. While this isn't the exact same issue as the one I reported first, it seems related.

**Comment by lervag** [comment]
I think this should be fixed now, please test.

**Comment by fuzzybear3965** [comment]
This looks beautiful! I'll let you know if I have any more issues. It worked an all my test cases.

**Comment by lervag** [comment]
Great! It worked on my tests as well, so it seems a good step in the right direction. I've added tikz commands to a list manually, so I would not be surprised if you might find some minor issues with tikz indentation. If so, please let me know!
