### ISSUE TITLE
vimtex is very slow

### ISSUE THREAD

**Issue by ptiede** [lervag/vimtex#372]
Hi, after a recent update my vimtex distribution has become very slow. It seems that it is due to using folding. Once I comment out thae last line on my config below it gets much quicker.

```vim
let g:tex_flavor = "latex"
let g:vimtex_latexmk_callback = 1
let g:vimtex_latexmk_continuous = 1 
let g:vimtex_quickfix_ignore_all_warnings=0 
let g:vimtex_quickfix_ignored_warnings = [ 'Underfull', 'Overfull', 'specifier changed to',] 
let g:vimtex_quickfix=2 
let g:vimtex_fold_automatic=0 
"qpdfviewer plugin for forward search 
let g:vimtex_view_general_viewer = 'qpdfview' 
let g:vimtex_view_general_options = '--unique @pdf\#src:@tex:@line:@col' 
let g:vimtex_view_general_options_latexmk = '--unique' 
let g:vimtex_fold_enabled=1
```

P.S. I am running Manjaro Linux (Arch derivative) if that helps with anything

**Comment by lervag** [comment]
It should not matter anything if you comment out the last line, since the folds are enabled by default. Could you please test with a minimal vimrc file (see [example here](https://github.com/lervag/vimtex/blob/master/test/template/minivimrc)).

**Comment by ptiede** [comment]
Thanks, I was able to fix it by setting it to use manual folding.

**Comment by lervag** [comment]
Yes, that's it: `g:vimtex_fold_automatic` is deprecated and one should rather use `g:vimtex_fold_manual`. Sorry for not noticing at once! :)

**Comment by ptiede** [comment]
No problem, just wanted to say how much I enjoy this distribution, it is by far the best tex package I have ever used for vim :)

**Comment by lervag** [comment]
Thanks! I'm very happy you feel that way :)

**Comment by Shougo** [comment]
@ptiede You can use FastFold.  It is better choice.

https://github.com/Konfekt/FastFold
