### ISSUE TITLE
`]]` doesn't close nested delimiters

### ISSUE THREAD

**Issue by slangangular** [lervag/vimtex#376]
In insert mode `]]` doesn't close nested delimiters. This is true both for parentheses aswell as for environments.

Consider the following sample document:
```latex
\documentclass{article}

\begin{document}

\begin{itemize}
    \item Foo
    \item Bar
\end{itemize}

\begin{itemize}
    \item Foo (bar)
\end{itemize}

\end{document}
```

In the first `itemize` the environment is closed properly. In the second one `]]` only inserts another `)`.

An even simpler case: `([ foo ])`. Here the square bracket is closed properly with `]]` but afterwards only additional square brackets are inserted.

**Comment by avfonarev** [comment]
Actually, this one quite annoys me as well. I skimmed through the source code after having discovered it and it looks like intended behaviour.

**Comment by lervag** [comment]
@avfonarev is right, it is intended. But it can be changed. I'll look at it when I get the time.

**Comment by slangangular** [comment]
Okay, thanks. I thought maybe it happened accidentally during the huge refactoring of the delimiter engine two weeks ago.
Thanks for the project btw, it's great!

**Comment by lervag** [comment]
It should work more as expected now. It is still not perfect, though! However, the next improvement is much more difficult to fix. That is, `]]` will close a preceding environment or delimiter, even if the env or delim is already closed AFTER the cursor. I still think the current version should be good enough for most cases. I hope you agree.

**Comment by avfonarev** [comment]
That is a great improvement, thank you!

**Comment by lervag** [comment]
No problem, happy you like it :-)

søn. 21. feb. 2016, 22.03 skrev Anton Fonarev <notifications@github.com>:

**Comment by slangangular** [comment]
Thanks, this is really awesome!
