### ISSUE TITLE
Strawberry Perl vs. Git for Windows Perl

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#378]
I just wanted to put this in the public forum that as of today with Git for Windows 2.7.2 that vimtex will not load the quickfix window or notify the user of compilation success/failure. I have tested this extensively on Windows 10 and Windows 8.1 with both 32- and 64-bit versions of Git for Windows and Strawberry Perl (using a 32-bit version of gvim and console vim).

EIther a 32-bit or 64-bit version of Strawberry Perl is compatible with 32-bit vim and gvim.

**Comment by lervag** [comment]
Hmm. What does Git for windows have to do with Vim and vimtex? It doesn't sound right to me that this should affect vimtex and Vim in any way.

I guess the version of Perl might be relevant, though, as `latexmk` is a perl script. Thus, if Perl is not installed correctly, or if a bad version is installed, then possibly some features of `latexmk` might not work.

**Comment by fuzzybear3965** [comment]
So, here is sample output from `VimtexInfo`. Note that you have defined a command to be run in Perl using `latexmk` in the event of successful/failed compilation. The version of Perl released with Git for Windows does not successfully callback to Vim. I can see that the `perl.exe` process is started but the vimtex status in the bottom of gvim never indicates successful/failed compilation and the quickfix window is not automatically opened (however, I can see the log results using `\le` so it does get populated).

```
b:vimtex : pts_pdfsizeopt2009_talk
  pid : 3116
  tmp : 'C:/Users/JOHNRI~1/AppData/Local/Temp/VIBA61F.tmp'
  root : 'C:/Users/John Rinehart/Downloads'
  aux : 'C:/Users/John Rinehart/Downloads/pts_pdfsizeopt2009_talk.aux'
  log : 'C:/Users/John Rinehart/Downloads/pts_pdfsizeopt2009_talk.log'
  out : 'C:/Users/John Rinehart/Downloads/pts_pdfsizeopt2009_talk.pdf'
  tex : 'C:/Users/John Rinehart/Downloads/pts_pdfsizeopt2009_talk.tex'
  cmd_latexmk_clean : 'cd /D "C:/Users/John Rinehart/Downloads" & latexmk -C "pts_pdfsizeopt2009_talk.tex"'
  cmd_latexmk_compile : 'cmd /s /c "cd /D "C:/Users/John Rinehart/Downloads" && set max_print_line=2000 & latexmk -verbose -pdf -recorder- -e "$pdflatex =~ s/ / -file-line-error /" -pvc -e "$success_cmd = ''\"gvim\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e "$failure_cmd = ''\"gvim\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previewer = ''SumatraPDF''" "pts_pdfsizeopt2009_talk.tex" >C:/Users/JOHNRI~1/AppData/Local/Temp/VIBA61F.tmp"'
  base : 'pts_pdfsizeopt2009_talk.tex'

  viewer
    init : function('279')
    view : function('280')
    latexmk_append_argument : function('281')
```

**Comment by lervag** [comment]
Sorry for taking so long to reply. If the problem persists; what is the output from latexmk? You can see it from `\lo` (or `VimtexLatexmkOutput`).

**Comment by fuzzybear3965** [comment]
@lervag, I'm sorry that I've waited to respond, too. "If the problem persists" was a really good thing to include. After I had posted that message, but before you had responded, I switched from using a version of gvim that I compiled on Windows to a version [that is compiled by someone else](https://tuxproject.de/projects/vim/). I haven't had this problem since and I don't have an old copy of the gvim version I was using. For now, I guess the issue is dead. If I encounter it again I will let you know.

**Comment by lervag** [comment]
Ok, thanks for letting me know. Feel free to reopen if you encounter it again in the future.

**Comment by fuzzybear3965** [comment]
Unfortunately, I don't have the privilege to reopen the issue, but I am experiencing this problem. I'm a little confused as to why it's happening because I have not updated my version of Vim and, while I have removed Strawberry Perl from my OS as of this morning, Strawberry Perl was not on my `PATH` and, so, was not providing the `perl` application required by `latexmk` and `vimtex`. The following is the compiler output (obtained by `\lo`):

```
Latexmk: applying rule 'pdflatex'...
This is LuaTeX, Version beta-0.80.0 (MiKTeX 2.9) (rev 5238) 

 \write18 enabled.

(./test.tex

LaTeX2e <2015/10/01> patch level 2

Babel <3.9n> and hyphenation patterns for 69 languages loaded.

("C:/MiKTeX 2.9/tex/latex/base/article.cls"

Document Class: article 2014/09/29 v1.4h Standard LaTeX document class

("C:/MiKTeX 2.9/tex/latex/base/size10.clo"))

("C:/MiKTeX 2.9/tex/latex/amsmath/amsmath.sty"

For additional information on amsmath, use the `?' option.

("C:/MiKTeX 2.9/tex/latex/amsmath/amstext.sty"

("C:/MiKTeX 2.9/tex/latex/amsmath/amsgen.sty"))

("C:/MiKTeX 2.9/tex/latex/amsmath/amsbsy.sty")

("C:/MiKTeX 2.9/tex/latex/amsmath/amsopn.sty")) (./test.aux) [1{C:/Users/John Ri

nehart/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}] (./test.aux))

 322 words of node memory still in use:

    nodes

   avail lists: 1:1,2:12,3:7,4:27,5:2,6:25,7:1,9:9

<<C:/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmmi10.pfb><<C:/MiKTeX 2.9/fonts/

type1/public/amsfonts/cm/cmr10.pfb><<C:/MiKTeX 2.9/fonts/type1/public/amsfonts/c

m/cmsy10.pfb>

Output written on test.pdf (1 page, 28532 bytes).

Transcript written on test.log.

Latexmk: applying rule 'pdflatex'...
This is LuaTeX, Version beta-0.80.0 (MiKTeX 2.9) (rev 5238) 

 \write18 enabled.

(./test.tex

LaTeX2e <2015/10/01> patch level 2

Babel <3.9n> and hyphenation patterns for 69 languages loaded.

("C:/MiKTeX 2.9/tex/latex/base/article.cls"

Document Class: article 2014/09/29 v1.4h Standard LaTeX document class

("C:/MiKTeX 2.9/tex/latex/base/size10.clo"))

("C:/MiKTeX 2.9/tex/latex/amsmath/amsmath.sty"

For additional information on amsmath, use the `?' option.

("C:/MiKTeX 2.9/tex/latex/amsmath/amstext.sty"

("C:/MiKTeX 2.9/tex/latex/amsmath/amsgen.sty"))

("C:/MiKTeX 2.9/tex/latex/amsmath/amsbsy.sty")

("C:/MiKTeX 2.9/tex/latex/amsmath/amsopn.sty")) (./test.aux) [1{C:/Users/John Ri

nehart/AppData/Local/MiKTeX/2.9/pdftex/config/pdftex.map}] (./test.aux))

 322 words of node memory still in use:

    nodes

   avail lists: 1:1,2:12,3:7,4:27,5:2,6:25,7:1,9:9

<<C:/MiKTeX 2.9/fonts/type1/public/amsfonts/cm/cmmi10.pfb><<C:/MiKTeX 2.9/fonts/

type1/public/amsfonts/cm/cmr10.pfb><<C:/MiKTeX 2.9/fonts/type1/public/amsfonts/c

m/cmsy10.pfb>

Output written on test.pdf (1 page, 28532 bytes).

Transcript written on test.log.

Latexmk: All targets (test.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
```

**Comment by lervag** [comment]
Thanks! Unfortunately, the output does not help.

Could you please provide a very specific and detailed description on how to reproduce? This must be pretty basic, because I will need to use a windows machine and install stuff. Since I am not very proficient with windows, it will be important that you provide details on how I should install gvim so that I get the same version (with same features) that you are using. Similar with MikTex and latexmk, as well as the pdf viewer. I know I'm asking a lot, but since this is a windows issue I need extra input.

So, something like this should suffice:

1. Install instructions for gvim
2. Install instructions MikTex (or whatever latex distribution)
    If relevant: Instructions for how to install latexmk
3. Install instructions for pdf viewer
4. Configuration instructions for all of the above, if applicable
5. Step-by-step guide for how to reproduce: Please include a minimal vimrc file and a minimal tex file

**Comment by fuzzybear3965** [comment]
No problem. It is not difficult to produce this error.  My setup is very basic.

gvim install instructions
==================

1. Download and install the x86 version of the installer from [here](https://tuxproject.de/projects/vim/).
Install to `C:\Program Files (x86)\vim`. Note that all executables, runtime folder, etc. are directly below `C:\Program Files (x86)\vim`. That is, I have a `C:\Program Files (x86)\vim\vim.exe` executable and `C:\Program Files (x86)\vim\gvim.exe` executable and a `C:\Program Files (x86)\vim\ftplugin` folder, among the other things.
2. Add `C:\Program Files (x86)\vim` [to your `PATH` environment variable](http://www.computerhope.com/issues/ch000549.htm).

MiKTeX
======

1. Download the basic MiKTeX installer from [here](http://miktex.org/download).
1. Install it to `C:\MiKTeX 2.9`.
1. Add `C:\MiKTeX 2.9\miktex\bin` to your `PATH` environment variable.

This will make `pdflatex` and `latexmk` available to you.

Sumatra PDF Viewer
================

1. Download the portable version of Sumatra PDF viewer from [here](http://www.sumatrapdfreader.org/download-free-pdf-viewer.html).
1. Extract the archive to wherever you'd like.
1. Add the location of `SumatraPDF.exe` (root of the extracted archive) to your `PATH` environment variable.

Git Bash / Git for Windows 
====================

1. Download the 64-bit version of Git for Windows from [here](https://git-scm.com/download/win).
1. Install it to `C:\Program Files\Git`.
1. Add `C:\Program Files\Git\usr\bin` to your `PATH` environment variable.

This makes `perl.exe` available to your `PATH`.

vimtex
=====

Clone the vimtex repository and place it in `%HOMEDRIVE%%HOMEPATH%\vimfiles` (see vimrc below).

Minimal vimrc
====
```
set shellslash nocompatible
set runtimepath^=$HOME/vimfiles/vimtex
filetype plugin indent on
let g:tex_flavor='latex'
let vimtex_viewer_general = 'sumatra'
```

Minimal LaTeX file
==============
```
\documentclass{article}
\begin{document}
a
\end{document
```

My Configuration
=============

* My gvim version is 7.4.1641. 
* My version of MiKTeX is up-to-date: latexmk version is 4.44.
* My version of perl included in Git for Windows is perl5, revision 22 subversion 0 (full configuration summary output below).
* The OS used for these tests is Windows 10 Pro 64-bit Insider Preview Build 14291.rs1_release.160314-2254. Although, I think you should be able to reproduce these results with any modern Windows OS.

I think that's everything. Let me know if something fails to work as described. I have tested this on my system by using gvim with the minimal vimrc file shown above. I have checked to make sure that no other `perl` executable is visible on my path: `where perl`. So, although I haven't tried this on a barebones set-up myself, we should agree.

Perl Configuration Summary
======================

```
Summary of my perl5 (revision 5 version 22 subversion 0) configuration:

  Platform:
    osname=msys, osvers=2.1.4(0.28753), archname=x86_64-msys-thread-multi
    uname='msys_nt-6.1 cab8 2.1.4(0.28753) 2015-06-08 22:11 x86_64 msys '
    config_args='-des -Dusethreads -Doptimize=-march=x86-64 -mtune=generic -O2 -pipe -Dprefix=/usr -Dvendorprefix=/usr -Dprivlib=/usr/share/perl5/core_perl -Darchlib=/usr/lib/perl5/core_perl -Dsitelib=/usr/share/perl5/site_perl -Dsitearch=/usr/lib/perl5/site_perl -Dvendorlib=/usr/share/perl5/vendor_perl -Dvendorarch=/usr/lib/perl5/vendor_perl -Dscriptdir=/usr/bin/core_perl -Dsitescript=/usr/bin/site_perl -Dvendorscript=/usr/bin/vendor_perl -Dinc_version_list=none -Dman1ext=1perl -Dman3ext=3perl -Darchname=-msys-threads -Dmyarchname=-msys -Dlibperl=msys-perl5_22.dll -Dlddlflags=-shared -pipe -Dldflags=-pipe -Dcc=gcc -Dld=g++'
    hint=recommended, useposix=true, d_sigaction=define
    useithreads=define, usemultiplicity=define
    use64bitint=define, use64bitall=define, uselongdouble=undef
    usemymalloc=n, bincompat5005=undef
  Compiler:
    cc='gcc', ccflags ='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_FORTIFY_SOURCE=2',
    optimize='-march=x86-64 -mtune=generic -O2 -pipe',
    cppflags='-DPERL_USE_SAFE_PUTENV -U__STRICT_ANSI__ -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong'
    ccversion='', gccversion='4.9.2', gccosandvers=''
    intsize=4, longsize=8, ptrsize=8, doublesize=8, byteorder=12345678, doublekind=3
    d_longlong=define, longlongsize=8, d_longdbl=define, longdblsize=16, longdblkind=3
    ivtype='long', ivsize=8, nvtype='double', nvsize=8, Off_t='off_t', lseeksize=8
    alignbytes=8, prototype=define
  Linker and Libraries:
    ld='g++', ldflags ='-pipe -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'
    libpth=/usr/lib/gcc/x86_64-pc-msys/4.9.2/include-fixed /usr/lib /usr/lib/gcc/x86_64-pc-msys/4.9.2/../../../../lib/../include/w32api
    libs=-lpthread -lgdbm -ldb -ldl -lcrypt -lgdbm_compat
    perllibs=-lpthread -ldl -lcrypt
    libc=/usr/lib/libc.a, so=dll, useshrplib=true, libperl=msys-perl5_22.dll
    gnulibc_version=''
  Dynamic Linking:
    dlsrc=dl_dlopen.xs, dlext=dll, d_dlsymun=undef, ccdlflags=' '
    cccdlflags=' ', lddlflags=' --shared -pipe -Wl,--enable-auto-import -Wl,--export-all-symbols -Wl,--enable-auto-image-base -fstack-protector-strong'


Characteristics of this binary (from libperl):
  Compile-time options: HAS_TIMES MULTIPLICITY PERLIO_LAYERS
                        PERL_DONT_CREATE_GVSV
                        PERL_HASH_FUNC_ONE_AT_A_TIME_HARD
                        PERL_IMPLICIT_CONTEXT PERL_NEW_COPY_ON_WRITE
                        PERL_PRESERVE_IVUV PERL_USE_SAFE_PUTENV
                        USE_64_BIT_ALL USE_64_BIT_INT USE_ITHREADS
                        USE_LARGE_FILES USE_LOCALE USE_LOCALE_COLLATE
                        USE_LOCALE_CTYPE USE_LOCALE_NUMERIC USE_LOCALE_TIME
                        USE_PERLIO USE_PERL_ATOF USE_REENTRANT_API
  Built under msys
  Compiled at Jun 18 2015 09:31:57
  @INC:
    /usr/lib/perl5/site_perl
    /usr/share/perl5/site_perl
    /usr/lib/perl5/vendor_perl
    /usr/share/perl5/vendor_perl
    /usr/lib/perl5/core_perl
    /usr/share/perl5/core_perl
.
```

**Comment by lervag** [comment]
Ok, so I've tried this now. I've downloaded the same version of Vim that you're using, and I have MikTeX installed and latexmk version 4.44. I've installed the github desktop app to clone the vimtex repo. I never installed anything perl.

When I try to run the minimal example, everything works as expected.

I am curious why you are so concerned about the perl configuration. latexmk is a perl script, but it is provided by MikTeX, and so I assume MikTeX already provides a perl environment or something like it to make latexmk work without any external dependencies.

So, I think we will have to investigate things on your end. Could you please make a trivial test of the clientserver functionality? Read `:h clientserver` for some info about it. Could you verify that it works as expected?

**Comment by fuzzybear3965** [comment]
Okay, so I recorded a screencast to make sure you are seeing something similar to me (bottom of post). [`perl.exe` is not included with MiKTeX](http://tex.stackexchange.com/questions/113707/perl-interpreter-could-not-be-found) for good reason: Perl is not necessarily used by `latexmk`. `vimtex` uses Perl for some callbacks, but, in general, not every user of MiKTeX will need a Perl interpereter.

I followed the [instructions on #243](https://github.com/lervag/vimtex/issues/243#issuecomment-150642634) and the `--remote-send` worked fine. I opened one instance of gvim without arguments. I used the command line to send the `echo` to the already-opened instance of gvim. The already-opened instance of gvim had `echo` printed in the status bar at the bottom. So, that works fine. `echo v:servername` reports `GVIM` for the gvim instance opened without arguments.

Note that the Google Drive player renders the video in 360p, by default. It's almost unwatchable. I would strongly recommend either downloading the screencast from Google Drive or watching it using the first link.

[Screencast.com Mirror](http://www.screencast.com/t/YNTwGFbXw)
[Google Drive Mirror](https://drive.google.com/open?id=0B9uIl02XJ-1OQ3V5am5nZ1loNXc)

**Comment by lervag** [comment]
So, first about perl: I still don't understand why you need to have perl installed. `latexmk` does not need it, and it is NOT needed for the callbacks. To make it clear: I'm using vim on Windows with only miktex intsalled and with the latexmk package installed through miktex. Everything works, including the callbacks. I have not installed perl separately.

Thanks for the screencast. I like the idea of showing me explicitly what happens. Also, thanks for verifying that the clientserver works.

Do you have a `.latexmkrc` file (or similar; I don't know what it is called on windows)? Perhaps you've added some settings there that are conflicting with the settings added by vimtex?

The next step of debugging is to copy the command used in vimtex directly to the command line. This is a little bit tedious, as the command is quite complex. But it should be possible, I think. First, you should issue `:VimtexInfo` after you've started compilation to see what the command is. It would be interesting for me to see as well. You've already provided this once long ago, but it would be interesting to see it again. In the previous comment, I notice that the `-recorder` option is added to latexmk. I'm curious why?

**Comment by fuzzybear3965** [comment]
I want to include some information that I think is important that I haven't mentioned, yet. When I start compiling a LaTeX document with vimtex, I can see in the Windows Task Manager (`top` for Windows) that a `perl` process is started and a `latexmk` process is started. I can see which executable on the filesystem is responsible for starting each process. In the case of the `perl` process, the following executable file is running: `C:\Program Files\Git\usr\bin\perl.exe`. When I stop compilation of the LaTeX document (`:VimtexCompileToggle`) both of these processes terminate.

Now, esponding to you in order: 

 1. I "need" Perl installed because I use Git for Windows which comes bundled with a few MSYS2 packages, like Perl, Bash, ls, cp, etc. 

 2. Regarding why I believe `vimtex` uses Perl with `latexmk` to execute callbacks, below is some output of `:VimtexInfo`. This was generated in my normal working environment (not my minimal working environment).
    ```
  cmd_latexmk_compile : 'cmd /s /c "cd /D "C:/Users/John Rinehart" && set max_print_line=2000 & latexmk -verbose -pdf -recorder- -pdflatex="lualatex --shell-escape --interaction=nonstopmode" -e "$pdflatex =~ s/ / -file-line-error /" -pvc -e "$success_cmd = ''\"gvim\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e "$failure_cmd = ''\"gvim\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previewer = ''SumatraPDF''" "test.tex" 
    ```
The `-e` flags passed, above, to `latexmk` are used to execute Perl code. From `latexmk --help`:
    ```
   -e <code> - Execute specified Perl code (as part of latexmk start-up
               code)
    ```
It seems clear from the `cmd_latexmk_compile` output of `:VimtexInfo` that Perl is used to execute callbacks upon successful/failed compilation.

 3. No problem for the screencast. I'm glad you found it helpful. No problem for verifying the clientserver functionality.

 4. I do have a `latexmkrc` file (I forgot that I had it). I have removed it and, then, repeated the same sequence that you saw in the screencast. The same behavior was observed (namely: the successful/failed completion of the compilation is never indicated and the quickfix window is never opened automatically).

 5. With regards to executing the command directly on the command line, I will do this later. I just wanted to post a "brief" response, now. I have already issued `:VimtexInfo` in the minimum working environment (using `mwe.vimrc`). Below is the output of `:VimtexInfo` in the minimum working environment, which is different than it is in my normal working environment with vimtex because I use an option in my normal `vimrc` file to control vimtex's compilation of my documents. The output of `:VimtexInfo` using the same `mwe.vimrc` and test LaTeX file that I used in the screencast is:
```
b:vimtex : test
  pid : 368
  tmp : 'C:/Users/JOHNRI~1/AppData/Local/Temp/VIA2DE3.tmp'
  root : 'C:/Users/John Rinehart'
  aux : 'C:/Users/John Rinehart/test.aux'
  log : 'C:/Users/John Rinehart/test.log'
  out : 'C:/Users/John Rinehart/test.pdf'
  tex : 'C:/Users/John Rinehart/test.tex'
  cmd_latexmk_compile : 'cmd /s /c "cd /D "C:/Users/John Rinehart" && set max_print_line=2000 & latexmk -verbose -pdf  -e "$pdflatex =~ s/ / -file-line-error /" -pvc -e "$success_cmd = ''\"gvim\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(1)\"''" -e "$failure_cmd = ''\"gvim\" --servername GVIM --remote-expr \"vimtex\#latexmk\#callback(0)\"''" -e "$pdf_previewer = ''sumatrapdf''" "test.tex" >C:/Users/JOHNRI~1/AppData/Local/Temp/VIA2DE3.tmp"'
  base : 'test.tex'

  viewer
    init : function('17')
    view : function('18')
    latexmk_append_argument : function('19')
```

**Comment by lervag** [comment]
Thanks for all the info! I think we'll get to the bottom of this, even if it might take some time...

When I get back to my windows PC I'll check the windows task manager. As I said, I don't have any perl executables. At least I don't think so, but I'll know for sure when I check the windows task manager.

One thing: I _know_ that the `-e` option means running a perl script. But `latexmk` itself is just a perl script, i.e.:

```
> head /usr/bin/latexmk 
#!/usr/bin/env perl

# !!!!!!!!!! Don't forget to document $silence_logfile_warnings.!!!

# N.B. !!!!!!!!!!!  See 17 July 2012 comments !!!!!!!!!!!!!!!!!!

# On a UNIX-like system, the above enables latexmk to run independently
#   of the location of the perl executable.  This line relies on the 
#   existence of the program /usr/bin/env
# If there is a problem for any reason, you can replace the first line of 
```

I assume this is also the case on windows, which should imply that I also, somehow, have a version of perl installed. I assume this must come with MikTeX, because I never installed perl myself.

**Comment by fuzzybear3965** [comment]
Ah, I didn't know this. It seems you are right: [Latexmk is a perl script](https://www.ctan.org/tex-archive/support/latexmk?lang=en). However, you are in a strange position. I have not been able to reproduce your results. When I run `where perl` on my machine, I discover that there are two available `perl` executables:
```
C:\>where perl
C:\Strawberry32\perl\bin\perl.exe
C:\Program Files\Git\usr\bin\perl.exe
```
So, I removed both of those from my `PATH`. Those are not tied to MiKTeX. So, if what you say is true and `latexmk` can run without using external `perl` binaries, then I should still be able to use `latexmk` after `perl` is no longer on my `PATH`. However, after removing both `perl` executables from my path  I ran the following two commands:
```
C:\>where perl
INFO: Could not find files for the given pattern(s).
```
```
C:\>latexmk test.tex
latexmk: The script interpreter could not be found.
latexmk: Data: scriptInterpreter="perl.exe"
```
Note that I will abstain from entering the `cmd_latexmk_compile` command into the command line until I receive word from you as to what `perl` executable `latexmk` is using on your system. Again. perl does not seem to be installed/packaged with MiKTeX. See [here](https://github.com/thomasjo/atom-latex/issues/92) and [here](http://tex.stackexchange.com/questions/158796/miktex-and-perl-scripts-and-one-python-script).

**Comment by lervag** [comment]
Interesting. I checked `where perl`, and I see I have `Strawberry Perl` installed (version 5.22.1). I never installed this myself, so it must have been done by MikTeX or something else. The folder is `C:\Strawberry\perl\bin\perl.exe` (that is, no 32).

Could you try to only have the Strawberry version in your path? Does it work then?

As you probably understand, I am really quite lost when it comes to Windows... :\

**Comment by lervag** [comment]
Hmm, ok. So, do I understand correctly that the entire issue here i that the Git version of perl does not work, but that the Strawberry version DOES work?

**Comment by fuzzybear3965** [comment]
Yes to the first question and yes to the second question. I realize, now, that my original post was written in error. I had meant to say, originally, that there exists some problem that makes the `perl` released with Git for Windows incompatible with `vimtex` in that it doesn't execute the callbacks. But, I never did say that, originally, and I'm really sorry for that. I'm going to edit my original post, now, to be more clear for future readers.

**Comment by lervag** [comment]
I think this has been a good lesson for me on understanding vimtex for windows. Thanks!

You may be right about my installing perl. I have no recollection of it, but I see from the Programs and features list that Strawberry perl was installed on a different time than MikTeX. The time corresponds to when I installed SumatraPDF, but I don't remember installing perl.

In any case, thanks a lot for being patient with my confusion. It is very useful for me to understand these things better, so that I can more easily understand future related issues.

I think the issue is now fully resolved, and can be left closed. Your original post makes much more sense to me now. In a perfect world, I would have created a wiki where such things could be written down. However, my time doesn't stretch that far. :\

**Comment by fuzzybear3965** [comment]
I understand not being able to make a wiki. I was hoping, though, that you might be able to add a note regarding this to the documentation, somewhere, for people using Windows. This might save someone the time and frustration that I spent dealing with this issue.

**Comment by lervag** [comment]
I could add an entry to the faq section. Or perhaps I should add a small section on common settings and troubleshooting for different OSes?

**Comment by fuzzybear3965** [comment]
I think that it would be good to start such a section. There are a couple things that are already worth mentioning in such a section: this problem, @hubanya's issues with paths. You probably know of more, right now, but those are a good start.

**Comment by lervag** [comment]
Ok, I've opened a new issue for this. I'd be happy for contributions to topics that should be added.
