### ISSUE TITLE
Get rid of warnings with relative file paths

### ISSUE THREAD

**Issue by wikimatze** [lervag/vimtex#379]
I'm resuing styles and put them in a relative folder to all of my tex projects. Here is what my document looks like:

```tex
%% config
\def\home{../../styles}

%% documentclass
\input{\home/documentclass_normal_oneside}

%% generell-styling
\input{\home/style_proggen}

%% meta-tags for pdf
\input{tex/metatags.tex}

%% fancy-header
\input{\home/style_header_oneside}

%% setting the infos for the pdf
\input{\home/info_hypersetup}

%% environments
\input{\home/environments_normal}
\input{\home/environments_mathe}

%% cover
\input{\home/style_cover}


\usepackage[strings]{underscore} % don't escape underscores

% label for programming-language
\input{\home/style_ruby}
\begin{document}
\input{\home/style_starting_document_without_cover}

\section{Hallo}

hallo hio

\end{document}
```

If I compile the document I get the correct output and the following warnings:

```sh
angular.tex|5 error| Could not open "\home/documentclass_normal_oneside"
angular.tex|8 error| Could not open "\home/style_proggen"
angular.tex|14 error| Could not open "\home/style_header_oneside"
angular.tex|17 error| Could not open "\home/info_hypersetup"
angular.tex|20 error| Could not open "\home/environments_normal"
angular.tex|21 error| Could not open "\home/environments_mathe"
angular.tex|24 error| Could not open "\home/style_cover"
angular.tex|30 error| Could not open "\home/style_ruby"
angular.tex|32 error| Could not open "\home/style_starting_document_without_cover"
```

How can I get rid of them?

**Comment by fuzzybear3965** [comment]
Do the errors go away if you substitute each instance of the variable ``\home`` with ``../../styles``?

**Comment by lervag** [comment]
@wikimatze I've pushed an issue template. I thought it should explain how to write good issues, but perhaps you did not see it? I am not sure if it works as intended...

In any case, as your example is not usable for me, since you have a lot of `\input`s that I can't use, then it is very difficult to test and investigate.

Please, and VERY PLEASE, provide a minimal working example. And please also explain what you are actually doing, and what you expect to happen.

**Comment by wikimatze** [comment]
Here are the steps you have to do:

```sh
cd /tmp && mkdir projects
git clone https://github.com/wikimatze/styles.git
git clone https://github.com/wikimatze/angular.git projects/angular
vim projects/angular/angular.tex
```

But somehow the errors now disappear. I've no clue what I've changed.

**Comment by lervag** [comment]
In other words, you can no longer reproduce the problem?

Let me know if the problem persists, and in that case, feel free to reopen.

**Comment by wikimatze** [comment]
I can not reproduce it. Maybe on another project. At least I posted the steps. I'll let you know, because your plugin has amazing feature (I still have to wait to a latest zathura version to have forward and reverse search running on my machine).

**Comment by lervag** [comment]
Thanks for the kind words! I don't mean to sound rude, btw. Feel free to reopen if you experience the problem again, or feel free to open a new issue. If you do, please try to provide minimal working examples, a minmal vimrc file (use with `vim -u minivimrc` or similar), as well as steps to reproduce.
