### ISSUE TITLE
Maths environment are not recognized as an environment

### ISSUE THREAD

**Issue by ernestorenanche** [lervag/vimtex#380]
Inside a `\[ ... \]` block the command `cse` and `dse` don't work any-more. The text object don't work either. For instance `dae` has also stopped working.

**Comment by lervag** [comment]
Yes, this is actually an intended change. `\[ ... \]`, together with `$ ... $`, `$$ ... $$` and `\( ... \)`, are now controlled through the `$,i$,a$` regions. You can use `cs$` to change, and it will allow a change to a common environment name.

I understand it might be somewhat upsetting, but the reasoning is really quite good. Please see #351.
