### ISSUE TITLE
`]]` not working on environments with optional settings

### ISSUE THREAD

**Issue by HarrisonB** [lervag/vimtex#381]
### Issue Explaination

`]]` for closing environments does not work if enviornment has optional settings

### Minimal working example

Given the following document,

```tex
\documentclass{minimal}
\usepackage{enumitem}
\begin{document}
\begin{enumerate}[label={(\arabic*)}]
_

\end{document}
```

if one's cursor is in the position of `_` and one is in Insert mode, pressing `]]` does not yield the proper result of 

```tex
\documentclass{minimal}
\usepackage{enumitem}
\begin{document}
\begin{enumerate}[label={(\arabic*)}]
\end{enumerate}_

\end{document}
```

but instead yields
```tex
\documentclass{minimal}
\usepackage{enumitem}
\begin{document}
\begin{enumerate}[label={(\arabic*)}]
    )_
\end{document}
```

.virmc:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
Thanks! I know what the problem is, and I think I have an idea for how to fix this in a good way. I'll get on it when I get the time.

**Comment by lervag** [comment]
I think this should fix it. Let me know if it works for you.
