### ISSUE TITLE
skim update on os x

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#383]
### Explain the issue

i'm trying to make Skim update the produced pdf. While Skim has an option 'check for file changes', this requires manually confirming it for each file and is not recommended on the Skim wiki.  instead they provide a bash script which tells skim to refresh the view via applescript. i have tested this script (i call it updateskim.sh) by invoking it from the command line, it works.

now i want to use $success_cmd to have latexmk invoke that script after successful compilation. i do not want to spread this config in a .latexmkrc file but prefer to keep it in my .vimrc.

to this end, i put the following line:

```
let g:vimtex_latexmk_options = '-pdf -e ''$success_cmd = "updateskim.sh %B";'''
```
which i kind of reverse-engineered from the vimtex and latexmk docs.

i expected this to refresh the skim view.

it does nothing; the behavior is unchanged from the default option value `'-pdf'`. the success-callback function in vim is called as before.

can this work? will vimtex combine the options? am i using the right quote syntax?

thanks!

the update script for reference...

```
#!/bin/bash

# from:
# https://sourceforge.net/p/skim-app/wiki/TeX_and_PDF_Synchronization/

# trimmed down to just do the view update

# the first argument should be the tex file, either with or without extension
file="$1"
[ "${file:0:1}" == "/" ] || file="${PWD}/${file}"
pdffile="${file%.tex}.pdf"
echo "something something"

# reload the pdf  in Skim
/usr/bin/osascript << EOF
  set theFile to POSIX file "${pdffile}" as alias
  tell application "Skim"
  activate
  set theDocs to get documents whose path is (get POSIX path of theFile)
  if (count of theDocs) > 0 then revert theDocs
  open theFile
  end tell
EOF

```

**Comment by lervag** [comment]
Actually, I think this should rather be solved by adding a hook to the callback function. Then you would not need to alter the vimtex options, instead you could add a custom function hook. The hook can use all of the vimtex variables, which makes it simple to achieve what you want.

I've added the functionality, and I think you should be able to get the desired behaviour with something like:

```vim
let g:vimtex_latexmk_callback_hook = 'MyHook'

function! MyHook(status)
  if a:status
    call system('updateskim.sh ' . b:vimtex.tex)
  endif
endfunction
```

**Comment by rionda** [comment]
Just tested this to do exactly what the OP wanted and works great. Thanks.

**Comment by lervag** [comment]
No problem :)

**Comment by nilsbecker** [comment]
this is great! thanks a lot! i tried it and it works. however, it does switch focus to the viewer window, which is not ideal when using the continuous latexmk mode. i guess this needs to be fixed in the applescript. will try to figure it out.

**Comment by lervag** [comment]
Yes, I think this needs to update in the applescript. Sorry... :p

**Comment by nilsbecker** [comment]
ok: removing the line 'activate' in the script does the trick: update but no focus switching. still when i use `:VimtexView` the focus switches properly. so everything's just fine for me now!

**Comment by lervag** [comment]
Great! :)

I'm curious: Since you're using OSX and you seem to have a good setup, perhaps you would be willing to write a short section in the docs that explain how to set things up for OSX users? I'm thinking it could be something to add in the beginning of the docs... what do you think?

**Comment by nilsbecker** [comment]
in principle no problem. but there is not really much to set up. basically all that is mac related in my `.vimrc` is this:

```

" settings for vimtex
let g:vimtex_view_general_viewer
			\ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '@line @pdf @tex'

" new hook
let g:vimtex_latexmk_callback_hook = 'CallUpdateSkim'

function! CallUpdateSkim(status)
  if a:status
    call system('updateskim.sh ' . b:vimtex.tex)
  endif
endfunction
```

**Comment by lervag** [comment]
Ah, that wasn't much. Then I'll just update the docs on the Skim viewer. However, it would be nice to have a more static link for the `updateskim.sh` script. Is it available for other users to download, for instance?

**Comment by nilsbecker** [comment]
hmm, i got it from the skim wiki, the address is listed in the script above as a comment. i just removed some parts of it that were unneccessary for updating from vim. so, the script as listed above is nowhere downloadable.

(also, on the wiki page they have some other script about how to do inverse search with vim, but that seems too complicated, as it is working just fine using the default preset for inverse search with MacVim in the Skim preferences. maybe it's old.)

so, i guess this whole little update script could be copied-and-pasted to the docs? maybe one should ask the skim wiki folks if that's ok -- i'm not experienced with this kind of thing.

**Comment by lervag** [comment]
Ok, I'll see what I can do.

**Comment by nhooyr** [comment]
Guess I should have explained why i added the callback when I made my PR.

```vim
let g:vimtex_view_general_callback = "VimtexForwardSearch"
function! VimtexForwardSearch()
  let out = b:vimtex.out()
  if empty(out)
    return
  endif
  call jobstart(["~/bin/updatePDF", line('.'), shellescape(out)])
endfunction
```

The script `updatePDF` looks like this

```zsh
#!/usr/bin/env zsh

if [[ $# == 2 ]]; then
	if pgrep Skim; then
		/opt/homebrew-cask/Caskroom/skim/1.4.17/Skim.app/Contents/SharedSupport/displayline -r -g "$@"
	else
		/opt/homebrew-cask/Caskroom/skim/1.4.17/Skim.app/Contents/SharedSupport/displayline -r "$@"
	fi
else
	/opt/homebrew-cask/Caskroom/skim/1.4.17/Skim.app/Contents/SharedSupport/displayline -r "$2" "$3"
fi
```

**Comment by lervag** [comment]
`jobstart` is only available in bleeding edge Vim's. I look forward to working more with those features, but for now I'll ignore them (I'm waiting until it is more "settled"; I want to support both neovim and Vim, and I hope they will settle on a similar API).

I'll keep the current documentation. I think interested readers should check out the links, and then they might see @nhooyr's version as well.

**Comment by nhooyr** [comment]
@lervag i just updated it a bit to use system. I forgot exactly what I did and why so I'm trying to figure it out again lol.

**Comment by lervag** [comment]
Although it looks like a good solution to me, the solution in the docs is more aligned with the official Skim wiki. In any case, thanks for contributing, I think your solution will be useful to others!

**Comment by nhooyr** [comment]
@lervag the skim wiki suggests using the `displayline` script as well for ForwardSearching. I think its a better idea to use it, since you can jump to lines or control whether or not bg/fg skim very easily. And its a standard script that comes with Skim.

**Comment by nhooyr** [comment]
Wait why do we have two custom callbacks? `g:vimtex_latexmk_callback_hook` and `g:vimtex_view_general_callback`? We don't really need the general_callback then do we?

**Comment by nhooyr** [comment]
The function in the docs is named  `CallUpdateSkim`. Shouldn't that be `UpdateSkim`?

**Comment by lervag** [comment]
@nhooyr I forgot about the general viewer callback, I realize that this is now sort of redundant, and I also realize that it could have been used to solve both this issue and your use case without adding the new hook.

However, I think I might consider to update this to instead remove the viewer specific callbacks, and instead improve the new callback hook and let the viewers attach to that hook if desired (zathura and mupdf uses the old hooks). This will have to be for future work (I've opened #388).

**Comment by nhooyr** [comment]
@lervag great.

But what about using `displayline` over the other script. You're gonna stick with the other one for now?

**Comment by lervag** [comment]
Does the suggested script work with bash? zsh is not available everywhere, and if I add a custom script, then I want it to work for most people without much ado...

**Comment by nilsbecker** [comment]
it seems that `displayline` is a standard way to control skim so maybe it's better to use that than some applescript from the wiki. can it also be used to update only and not jump to a line? if yes then the applescript above (which does no jumping, just update) is redundant.

**Comment by nilsbecker** [comment]
i think what @nhooyr means is to not use any extra script. so scrap the zsh part above and only directly call displayline, which is available with skim.

**Comment by lervag** [comment]
Yes, I think the zsh script works with bash and sh with no changes. But I'm not on OSX and can't test... in any case, I'm also curious which version of displayline/Skim is required for this to work. And is versioning an issue here at all?

**Comment by nhooyr** [comment]
alright this is my new version, works for neovim, bleeding edge vim, and a normal vim. And it requires no extra script, just point `g:vimtex_view_general_viewer` to wherever the displayline script is on your system. If you used brew cask to install, its in `/usr/local/bin` which should be in your path.

```vim
let g:vimtex_view_general_viewer = 'displayline'
let g:vimtex_view_general_options = '-r @line @pdf'
let g:vimtex_latexmk_callback_hook = 'UpdateSkim'
function! UpdateSkim(status)
  let out = b:vimtex.out()
  if empty(out)
    return
  endif
  let cmd = [g:vimtex_view_general_viewer, "-r"]
  if !empty(system("pgrep Skim"))
    call extend(cmd, "-g")
  endif
  if has('nvim')
    call jobstart(cmd + [line('.'), out])
  elseif has('job')
    call job_start(cmd + [line('.'), out])
  else
    call system(join(cmd + [line('.'), shellescape(out)], ' '))
  endif
endfunction
```

**Comment by lervag** [comment]
Great! I'll add this to the docs, then! Thanks, @nhooyr!

**Comment by lervag** [comment]
I took the liberty to make some minor syntactic changes. I'd appreciate if you could take a look, @nhooyr, and see if you think it looks correct.

**Comment by nhooyr** [comment]
LGTM but you should update the rest. e.g. it still mentions `updateskim.sh` and the other settings aren't in the docs. E.g. `g:vimtex_view_general_options` is different.

**Comment by lervag** [comment]
I think I fixed the remaining things in the docs now.

Just curious: If `displayline` is in `$PATH`, why is there so many examples of using the entire path?

**Comment by rionda** [comment]
@lervag : Because not everyone has it in $PATH. I don't, for example.

**Comment by lervag** [comment]
Hmm. OSX sort of annoys me. Is there a good reason NOT to specify the full path @nhooyr?

**Comment by nhooyr** [comment]
@lervag on OSX there is a special package manager home-brew . If you install Skim with homebrew, displayline will be in your path, otherwise it won't. I think most people still install it manually so its a good idea to specify the full path.

**Comment by lervag** [comment]
Thanks. I think it should be fine now. I think this should provide a very good setup for OSX users. Thanks alot, @nhooyr!

**Comment by lervag** [comment]
Hi! Just want to mention that the recent update now generalizes the hooks. Note the change of option: One should now add hooks to the list `g:vimtex_latexmk_callback_hooks` (allows more than one hook).

**Comment by nhooyr** [comment]
great thanks.

**Comment by lervag** [comment]
No, i did that already.

**Comment by albertfgu** [comment]
Hi, this issue was very helpful for me. However, you guys mention the "skim example" several times here, but I could not find the script provided here in the documentation. Additionally, the docs link to the Skim wiki which also did not seem to have anything relevant. In fact I could not configure anything for Skim without searching through these Github issues.

**Comment by nhooyr** [comment]
@albertfgu I believe you need https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L1584
