### ISSUE TITLE
since zathura update 0.33 -> 0.35 zathura viewer no longer opens

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#384]
### Explain the issue

Most issues are related to bugs or problems. In these cases, you should include
a minimal working example and a minimal vimrc file (see below), as well as:

1. Steps to reproduce
- Start vim with
```vim
  let g:vimtex_view_method = 'zathura'
```
in `.vimrc` and enter
```
:VimtexCompile
```
2. Expected behaviour
Zathura opens.
3. Observed behaviour
Nothing happens.

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
 let g:vimtex_view_method = 'zathura'

```

**Comment by Konfekt** [comment]
Ok, this relates to

https://github.com/lervag/vimtex/issues/338

**Comment by lervag** [comment]
Do you know if this is a vimtex specific problem, or if the problem instead is with zathura?

**Comment by Konfekt** [comment]
Added a comment at

https://build.opensuse.org/package/show?project=X11%3AUtilities&package=zathura

Yep, it's a problem with zathura that dropped libsynctex support by default. Now all distributions have to cope with it. ArchLinux reacted first. This concerns OpenSUSE.

**Comment by Konfekt** [comment]
Maybe warn people, this issue could become more and more frequent.

**Comment by lervag** [comment]
How very annoying!

I might add a warning, at least if more people complain.

Thanks for noticing and investigating!

**Comment by Konfekt** [comment]
Just to be correct, if I understood correctly, now zathura no longer ensures synctex support by allowing to compile without TeXlive and then dropping synctex support.  But practically the outcome is apparently the same.

**Comment by Konfekt** [comment]
Just for reference, since working around this has been costing me some time, [here's](https://bugzilla.opensuse.org/show_bug.cgi?id=1192602) the official response to adding synctex support for zathura in Opensuse.

In the meanwhile, I've been copying the `zathura` and `libpdf-poppler.so` binaries from, say, some deb package to a folder `~/bin/apps/zathura/` and adding the following `zathura` shell script in `~/bin` coming before `/usr/bin/` in `$PATH`:

```shi
#!/bin/sh

exec $HOME/bin/apps/zathura/zathura -p $HOME/bin/apps/zathura "$@"
```
