### ISSUE TITLE
Close quickfix window when closing corresponding buffer

### ISSUE THREAD

**Issue by yagebu** [lervag/vimtex#385]
I usually have the quickfix open to keep track of the latex warnings. But the quickfix window stays open and has to be closed separately if the corresponding buffer is closed. It would be nice if it closed automatically in this case.

**Comment by lervag** [comment]
I'm wondering: Do you mean "corresponding latex project"? I'm asking, because it is quite normal to work in multiple-file projects, and in these cases one may have multiple buffers open for a single project.

Also: When you say "closed", do you mean when the buffer (or project) is deleted, or simply if it is hidden?

**Comment by yagebu** [comment]
> I'm wondering: Do you mean "corresponding latex project"?

Good point that I didn't consider. I was only thinking of a single file, but in case a project consists of multiple files, I guess it should stay open as long as the one of the files is open.

> Also: When you say "closed", do you mean when the buffer (or project) is deleted, or simply if it is hidden?

Deleted. Actually the concrete scenario I had in mind is the following: 1. Open a single latex file and start compilation. 2. Close window with `:q`, in this case the only window that's left is the quickfix window. I guess it would also be nice for the quickfix window to be hidden if the corresponding buffer is hidden, but I'm not sure it that can possibly be implemented in viml...

Seems that this is not as simple and clear-cut as I thought. I guess it is also quite low-priority, I currently have as a workaround a `WinEnter` autocommand that closes the quickfix window if it's the last window left. If you feel that it's not worth the effort, feel free to close this issue.

Similar issue for syntastic: https://github.com/scrooloose/syntastic/issues/123

**Comment by lervag** [comment]
I think I can implement a simple solution that should close the quickfix window if the project itself is wiped out. This should work for the concrete scenario. It is not a priority, but I have an idea so I might try to solve it soon when I get the time.

**Comment by lervag** [comment]
This seems to work well. And I agree that this makes sense. Thanks for suggesting!
