### ISSUE TITLE
Faster Fold Expression

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#387]
Just for reference, there's a plugin

https://github.com/matze/vim-tex-fold

that promises a fast fold expression. Perhaps interesting to compare it to that of vimtex.

**Comment by lervag** [comment]
It is very simple, so I am not surprised if it is relatively fast. However, it is very simple. I think it is even buggy, in that it will start a fold on lines that contain both `\begin` and `\env` (which will thus never be closed).

In any case, thanks for letting me know about it.
