### ISSUE TITLE
Indenting of lstlistings

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#389]
Using a minimal .vimrc (just vimtex loaded), I have this behavior --- try with 

```
\begin{lstlisting}[language=Gnuplot, basicstyle=\small\ttfamily, frame=single, float=htb,
caption={Data fitting in gnuplot --- with the non-linear formula}, label={lst:nlfit}]
gnuplot> f(x)=R0 + B*x + C*sin(G*x)
gnuplot> fit f(x) "measR.dat" via R0, B, C, G
R0              = 134.247          +/- 6.717        (5.003%)
B               = 18.5092          +/- 1.307        (7.063%)
C               = 15.0483          +/- 5.097        (33.87%)
G               = 0.663579         +/- 0.05086      (7.665%)
\end{lstlisting}
```

then `vae` and indent it, and you have 

```
begin{lstlisting}[language=Gnuplot, basicstyle=\small\ttfamily, frame=single, float=htb,
caption={Data fitting in gnuplot --- with the non-linear formula}, label={lst:nlfit}]
gnuplot> f(x)=R0 + B*x + C*sin(G*x)
gnuplot> fit f(x) "measR.dat" via R0, B, C, G
R0              = 134.247          +/- 6.717        (5.003%)
    B               = 18.5092          +/- 1.307        (7.063%)
        C               = 15.0483          +/- 5.097        (33.87%)
            G               = 0.663579         +/- 0.05086      (7.665%)
                \end{lstlisting}
```

which is not the expected thing. `lstlistings` should be managed as `verbatim`, and left untouched. (Notice that this happens if the environment is flush left with the start of the column, different things happens when it's indented)

**Comment by Rmano** [comment]
(Notice that with autogobble you can indent `lstlistings` --- but you need to keep the "internal" spacing fixed). 

http://tex.stackexchange.com/questions/19953/how-to-automatically-skip-leading-white-spaces-in-listings

**Comment by lervag** [comment]
Ok, I think the solution here is to check for the verbatim environments through the syntax rules. I'll look into it.

**Comment by lervag** [comment]
I've look at this now, and I can't reproduce your problem. Could you please try the minimal example that I've just pushed?

**Comment by Rmano** [comment]
I am not able to reproduce it, both with my test and your test example. Puzzled. 
(sorry for the delay --- out skiing :-P )

**Comment by Rmano** [comment]
Close as no reproducible.

**Comment by lervag** [comment]
Great. Let me know if the problem reappears or if you have other problems! :)
