### ISSUE TITLE
Is it possible to make omnicomplete search through "\externaldocument"s ?

### ISSUE THREAD

**Issue by atorg** [lervag/vimtex#392]
Sometimes I use the xr package and the \externaldocument command to be able to cross-reference objects from other .tex files.

It does not appear that these labels from other .tex files get indexed into vimtex's omnicomplete function at current.

Is it possible to get this behavior? Perhaps as a feature in some future release?

**Comment by lervag** [comment]
Yes, this could be possible, but I am not entirely sure. However, I would be happy to try if you could provide a working example of how this is used so that I can use in testing.

**Comment by atorg** [comment]
I attach a minimal working example. It just requires file1.tex and file2.tex.
I have also included file2alt.tex which demonstrates the prefixing option of the externaldocument command.


[vimtex-externaldocument.zip](https://github.com/lervag/vimtex/files/167552/vimtex-externaldocument.zip)

**Comment by lervag** [comment]
Thanks! I think this should be possible to implement.

**Comment by lervag** [comment]
Might take some time, but I'll look at it.

**Comment by lervag** [comment]
Please try the latest version. I think it should work, but there might be some flaws I didn't notice.

**Comment by atorg** [comment]
Thanks!
It works for the file2.tex example.
However, it doesn't work for the file2alt.tex example.
The omnicomplete finds the reference in the other file but provides the wrong label, i.e. eq_1 instead of 1-eq_1.
For my purposes this is easy enough to work around.

**Comment by lervag** [comment]
Now it should work for the other example as well. I forgot that part. I had to rewrite a lot of stuff, here, but I think the code is better now. So I guess that's a win-win situation. :)

**Comment by atorg** [comment]
Works great! Thanks :)

**Comment by lervag** [comment]
No problem! Seems like a nice feature and a nice package.
