### ISSUE TITLE
Add support for `|` delimiters

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#398]
The `|x|` delimiters are not parsed correctly.

**Comment by lervag** [comment]
The big question is: How to decide which side a bar is on. That is, it is trivial to see that `(` is a left parenthesis. But it is not trivial to see if `|` is a left or a right bar. It can also be used as a separator, and so it will not always be used in a pair.

Perhaps one should utilize a context, e.g. 10 lines in each direction. Then one could count the number of bars and use this to decide the sideness of the current bar? This should work for most equation environments as long as the bar is always used in pairs...

**Comment by lervag** [comment]
I'd love some feedback: @nasenatmer @Konfekt @fuzzybear3965.

**Comment by fuzzybear3965** [comment]
Your example makes it trivially clear why `|` is difficult to parse. In light of this, I strongly recommend against using `vimtex` to determine which `|` is a left or right delimiter. It would not be a lot of overhead to require the user to "label" the bar as a left bar or right bar. This could also be done with other delimiters, like `%`. My idea is to promote, in `vimtex`, the requirement to prefix the bars, or other ambiguous delimiters, immediately with a `l` or `r` character, such as `l|` or `r|` which would make them parsable.

**Comment by lervag** [comment]
Thanks, @fuzzybear3965, I think this is a good proposal. That is, at least part of it. I sense two proposals here, actually:

1. Remove parsing of `|` and `\|` delimiters, since it is not possible (or rather, very difficult) to parse as pairs.
2. Allow users to write `l|` and `r|` so that `tsd` will expand this to `\left|` and `\right|`, respectively.

The first proposal I think is very good. There are two alternatives: Either don't parse `|`, or find some way to parse `|`s that have a high accuracy. Parsing will never be 100% accurate, and the LaTeX community seems to encourage that one uses `\lvert` and `\rvert` instead of `|` and `|` for delimiters, which will be parsed by vimtex today. For this reason, I think it seems very sensible to remove the currently broken support for the bars as delimiters.

Regarding the second proposal; I actually don't really like this. This is too similar to a snippet functionality, and in this case I would much rather encourage the user to define a snippet (e.g. with Ultisnips or neosnippet) that expands some trigger, e.g. `bars` to `\left| x \right|` where `x` is the cursor.

**Comment by nasenatmer** [comment]
I've never used `|` in LaTeX so I guess it must've sth todo with math mode :)

In order to KISS vimtex, I'd prefer proposal one to any complicated and error-prone solution like parsing 10 lines before and after cursor.

Sorry for the short feedback.

**Comment by fuzzybear3965** [comment]
"Thanks, @fuzzybear3965, I think this a good proposal" followed by, "Regarding the second proposal; I actually don't really like this" :). It seems that you have changed your mind.

To your points:
1. Parsing will never be 100% accurate, but support should still be added for parsing delimiters.
1. While I have found discussion suggesting the use of `\lvert` and `\rvert `, I have not found that advice in opposition to suggestions that `\|` should be used. But, note that I'm not proposing that `l|` and `r|` be expanded into `\|` but into `\left|` and `\right|`, respectively; this is different (see the last note).
1. While a snippet solution would work, it would work for all delimiters. The parser mitigates the requirement of snippets, allowing the user to refrain from jumping out of their snippets when they are using a bunch of nested and potentially overlapping delimiters.
1. The parser also allows the author to defer expansion until later when they have more time to type. Sometimes, (like in school courses) editing LaTeX documents is a time-varying stressor. It is preferable to type the delimiters, considering that one can expand them later, using the parser. Keeping track of jump points live, during a lecture, using snippets, is intellectual overhead.
1. From what [I have read](https://www.physicsforums.com/threads/big-vert-in-latex.207332/) it seems that `\lvert` and `\rvert` don't resize according to their context. `\left|` and `\right|` do, however. Of course, this can be manually accommodated for by adding `\big`, `\bigg`, etc., but that's more work and we already have enough work to do.

**Comment by lervag** [comment]
@nasenatmer Thanks for the feedback. I also think KISS applies here.

@fuzzybear3965 No, I did not change my mind, I just recognized to separate proposals in your text, where I agree with one and not the other. So:

1. Sure, and parsing delimiters ARE supported. Just not the bars, that is, the `|` and `\|`.

2. Yes, I understood your proposal about `l| x r|` to `\left| x \right|`. But let's say you toggled it again; should it return to `l| x r|`, which is not valid latex code? This would surprise many users who then toggled `\left| x \right|`.

3. Ok.

4. Still, snippets allow just this: speed of typing. In any case, one can also rather simply go back to finish up the bar delimiters afterwords.

5. What you've read is simply wrong. `\left\lvert ... \right\rvert` works as expected and resizes according to their context. Note the difference between a set of delimiters, e.g. `| x |` and `\lvert x \rvert`, and modifiers, e.g. `\left ... \right` and `\bigl ... \bigr`.

**Comment by fuzzybear3965** [comment]
I see. I think you interpreted "In light of this, I strongly recommend against using vimtex to determine which | is a left or right delimiter" as a separate proposal. I didn't mean it that way. 

1. I understand delimiters are supported (and that's great!). I just find that I use bars with `(` and `{` enough that it would be great to expand them all with a <kbd>Shift-v</kbd> a couple <kbd>j</kbd>s and a <kbd>t</kbd><kbd>s</kbd><kbd>d</kbd>.
1. Yeah, it should definitely return to `l|` and `r|` which, as far as I can tell, is not "invalid". I've just managed to compile a document using those two character sequences in both math and text mode with no compiler error generated.
1. :)
1. But, you have to admit that it's more awkward to navigate to some block of math text and individually expand all of the instances of `l|` and `r|` than selecting all off the `|`s with visual mode and using <kbd>t</kbd><kbd>s</kbd><kbd>d</kbd> once.
1. Okay. Thanks for clarifying the difference between the delimiters and the modifiers. I understand the difference. Technically what I'm asking for, then, is not a delimiter solution since I'm asking for `l|` to be expanded to `\left|`. But, I'll amend my request to have `l|` to be expanded to `\lvert` (and similarly for `r|`.

Come on, @lervag, you know you want to!

**Comment by lervag** [comment]
@fuzzybear3965 When I wrote "valid latex code", i did not mean code that compiles. I mean that `l| x r|` will print exactly "l|xr|" in the document, and that this is unexpected for users who are not aware of this "feature". I actually don't agree that it makes sense to allow `l| ... r|` to be expanded.

I think it might be important to note that the current implementation utilizes the difference between delimiters and modifiers. In order to support your proposal, I will have to add a new type of parser, and it is non-trivial and requires special code to handle. To me, that is a very high cost for a very low gain. And I am sorry if you don't agree with this.

You could try something like:

```vim
augroup SomeGroupName
  au!
  au FileType tex iabbr l\| \lvert
  au FileType tex iabbr r\| \rvert
augroup END
```

I think the only way to support the bars will be to add a mechinism that parses and detects which side the current bar is on. And since this is very non-trivial, I think I will pass on that for now. Unless anyone can come up with a very good strategy for solving it, that is.

**Comment by fuzzybear3965** [comment]
No problem. The abbreviation suggestion is a good one. Okay, well, we fleshed this out enough. I don't think will severely disadvantage any author.

**Comment by lervag** [comment]
@fuzzybear3965 Thanks. And just to be clear: I very much appreciate your input and thoughts. Being able to discuss things like this is very useful, even when the outcome, as in this case, is to choose not to implement a feature.

**Comment by fuzzybear3965** [comment]
Yo, that was never unclear. If I really want, I can fork the project and add whatever features I'd like. Going forward, I'm going to keep suggesting whatever I want. If @lervag doesn't want feature X implemented it's probably for good reason. vimtex continues to demonstrate itself as an example of good design.

I'm a huge vimtex fan. I just plugged it today on #vim on freenode. Keep up the great work!

**Comment by lervag** [comment]
Thanks!
