### ISSUE TITLE
Add reference autocompletion support for \hyperref

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#399]
This is a feature request.

It would be nice if autocompletion support for \hyperref from the [hyperref](https://www.ctan.org/pkg/hyperref) package could be added.

### Minimal working example

Consider this example:

```tex
\documentclass{amsart}
\usepackage{amsthm}
\usepackage{hyperref}
\newtheorem{thm}{Theorem}
\begin{document}

\begin{thm}
  \label{thm:main_theorem}
  This is the main theorem.
\end{thm}

Our \hyperref[]{main theorem} implies ...

\end{document}
```
If the cursor is placed between the [] in the second to last line, it would be nice if this would be completed to 

```tex
Our \hyperref[thm:main_theorem]{main theorem} implies ...
```

**Comment by lervag** [comment]
I think this should be working now, please try. If you use neocomplete, please note the updated neocomplete pattern in the docs.

**Comment by heiderich** [comment]
Yes, it is working. Thank your very much.

**Comment by lervag** [comment]
Great, and no problem! :)
