### ISSUE TITLE
Glossary completion

### ISSUE THREAD

**Issue by mbrunnen** [lervag/vimtex#403]
Hi
Thanks for this nice new feature #263 :)
I finally found my problem and can reproduce it:
Change in [`test/features/completions/main.tex`](https://github.com/lervag/vimtex/blob/master/test/features/completions/main.tex) on line 12:
    `\input{glossary.tex}`
to
    `\loadglsentries{glossary}`
and restart vim.
Then the completion breaks for me.
Best regards,
Manoel

**Comment by lervag** [comment]
Fixed through #404.
