### ISSUE TITLE
When setting new folding methods, information texts are not shown when folded

### ISSUE THREAD

**Issue by ranranking** [lervag/vimtex#407]
### Explain the issue

These are my settings:

```vim
  let g:vimtex_complete_close_braces = 1
  let g:vimtex_fold_enabled = 1
  let g:vimtex_fold_manual = 1
  let g:vimtex_fold_comments = 1
  let g:vimtex_complete_img_use_tail = 1
  let g:vimtex_quickfix_ignore_all_warnings = 1
  let g:vimtex_latexmk_build_dir='./output/'

  let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
  let g:vimtex_view_general_options = '-r @line @pdf'

  let g:vimtex_latexmk_callback_hooks = 'UpdateSkim'

  let g:vimtex_fold_sections = [
      \ "part",
      \ "chapter",
      \ "section",
      \ "subsection",
      \ "subsubsection",
      \ "paragraph",
      \ "subparagraph",
    \ ]

```
I added paragraph and subparagraph to fold sections. They are folded, but the name of paragraphs and subparagraphs are not shown on the folding line, it shows `Not defined`. How to fix this?

**Comment by lervag** [comment]
Please provide a minimal working example.

**Comment by ranranking** [comment]
Thank you very much!

**Comment by lervag** [comment]
No problem! Thanks for reporting!

**Comment by ranranking** [comment]
@lervag After updating, vimtex opens tex file really slow with `  let g:vimtex_fold_enabled = 1`. Even with `  let g:vimtex_fold_manual = 1` the startup is still about one minute. The start up time was fine before updating.

**Comment by lervag** [comment]
Thanks, there was an error in a regexp that is used for making things more efficient. It should work now.

**Comment by Konfekt** [comment]
Hmm.. Also setting regexpengine=1 speeds things up.

**Comment by lervag** [comment]
But you don't propose that I set this from vimtex, right? It is a global option, after all.

**Comment by Konfekt** [comment]
Oh, I didn't get that right. Thought it to be local.
