### ISSUE TITLE
Question about text objects

### ISSUE THREAD

**Issue by hubanya** [lervag/vimtex#408]
The text objects `ie`, `ae` and so on from vimtex are really handy . But I have a question about these test objects. It seems that these test objects always leave the last character in the texts unselected.

For example, for the following environment
```tex
\begin{equation}
  \alpha
\end{equation}
```
If the cursor is somewhere in one of these three lines, then `vie` only selects the characters `\alph`, leaving the last character `a` unselected. If instead `die` is used, then what I get is 
```\tex
\begin{equation}
  a
\end{equation}
```
This also happens to `ae`. For example, if `vae` is used, then the last `}` is not selected. If `dae` is used, then we get
```tex
}
```

The same thing happens to `i$`, `a$`, `ic`, `ac` as I tested. Is this intentionally designed or a potential bug? Thanks!!!

**Comment by lervag** [comment]
This works as expected for me. Thus it seems like a bug, but I don't know what's wrong. Could you create a minimal working example, including a minimal vimrc file?

**Comment by Rmano** [comment]
I am not able to reproduce it, either. The only case when `ie` and `ae` act strange is if I have optional arguments in the environment in multiple lines... for example:

```
\begin{tikzpicture}[red,
    thick]
    \node {a}
\end{tikzpicture}
```
...where `vie` selects the optional arguments too; it works correctly if all the optional arguments are on one line, like

```
\begin{tikzpicture}[red,thick]
    \node {a}
\end{tikzpicture}
```

But I can not see any "leaking" single chars.

**Comment by fuzzybear3965** [comment]
I can confirm @Rmano's test. I think `vimtex` should be able to handle newlines within the options. This seems to be a bug.

With regards to @hubanya's tests, I can not confirm them. @hubanya and I have a similar configuration so I would be in a better position to reproduce it than would @lervag or (possibly) @Rmano (We both use Windows 10 and gvim).

@hubanya, as @lervag requested, please clean your `vimrc` file of anything superfluous (you should be able to empty it out) and rerun this test.

**Comment by lervag** [comment]
@Rmano Could you (or someone) open a new issue for the optional arguments with newlines. I will fix it, but only when I get the time. I have an idea for how to do this, but it might have to wait until next weekend.

**Comment by lervag** [comment]
@fuzzybear3965 Thanks for letting me know that this is not directly reproducible on windows. My suspicion is that there are conflicts with plugins or something strange in the vimrc file.

**Comment by fuzzybear3965** [comment]
@Rmano, @lervag, I will open the newline issue, now.

**Comment by lervag** [comment]
Thanks!

**Comment by hubanya** [comment]
@lervag @fuzzybear3965 @Rmano  I'm really sorry to bother you for this issue. It is indeed my own problem. Then Windows gvim automatically add `behave mswin` in my `vimrc` and this is the source that causes my problem. I found it using just a minimal `vimrc`. Now all the text objects work as a charm!

Thank you again for your help!

**Comment by fuzzybear3965** [comment]
This seems to be related to the `selection` option. @hubanya, if you enable `:behave mswin` and run the command `:set selection=inclusive`, does it still work?

**Comment by lervag** [comment]
No problem, happy it works!

**Comment by lervag** [comment]
Note: I've opened an issue about writing a small troubleshoot section for windows (#412). I closed this, since it seems we've solved the problem now.
