### ISSUE TITLE
Environment text object not detected with option newlines

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#409]
Newlines in the options of an environment inhibit text objects `ae` and `ie` from working properly. This can be seen by considering the following minimal example:

```
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}[red,thick]
    \node {a};
\end{tikzpicture}
\end{document}
```
Trying to select everything within the tikzpicture environment results in the following being selected:
```
   thick]
    \node {a};
```
The following is what should be selected.
```
    \node {a};
```
Note that this is a special case because of how tikz (and possibly other packages) parse a comma-/delimiter-separated argument.

**Comment by lervag** [comment]
Did you close this because of #410?

**Comment by fuzzybear3965** [comment]
Yeah, I edited #410 relative to #409 because I considered both the case of multiple options and multiple arguments. I hate that issues can't be deleted.

**Comment by lervag** [comment]
Can't delete, but you could have edited/updated it. Thus, instead of creating #410, you could have changed #409. But really, it doesn't matter! I just wanted to be sure I didn't miss anything :)

**Comment by fuzzybear3965** [comment]
I could have, but GitHub doesn't allow for the changing of titles for issues and, unfortunately, I made the title too specific, originally.

**Comment by lervag** [comment]
Ok! I can edit the title (an edit button next to the title), I thought you could do it to. Perhaps there is a permission setting here. I'll look around.

**Comment by fuzzybear3965** [comment]
*palm face*. Don't look for any permission setting.

-- John Rinehart

**Comment by lervag** [comment]
Haha. Ok, no problem! :)
