### ISSUE TITLE
Environment text object doesn't work with newlines in "environment header"

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#410]
Newlines in the options or arguments of an environment inhibit text objects ae and ie from working properly. This can be seen by considering the following two minimal examples:

### Example 1
```
\documentclass{article}
\usepackage{tikz}
\begin{document}
\begin{tikzpicture}[red,
thick]
    \node {a};
\end{tikzpicture}
\end{document}
```
Trying to select everything within the tikzpicture environment (`vie`) results in the following being selected:
```
[red,
   thick]
   \node{a};
```
The following is what should be selected.
```
\node {a};
```
Note that this is a special case because of how tikz (and possibly other packages) parse a comma-/delimiter-separated argument.

### Example 2
```
\documentclass{article}
\newenvironment{lervag}[2]{This is an #1 and #2 package.}{}
\begin{document}
\begin{lervag}{amazing}
   {wonderful}
Hello there.
\end{lervag}
\end{document}
```
Trying to select everything in the lervag environment (`vie`) results in the following being selected:
```
{wonderful}
Hello there.
```
The following should be selected.
```
Hello there.
```

**Comment by lervag** [comment]
Thanks! I've made changes that should solve this issue. It seems to work well for me.
