### ISSUE TITLE
vimtex not loading when vim starts

### ISSUE THREAD

**Issue by Laranjadinho** [lervag/vimtex#411]
I have just installed vimtex with pathogen and it won't load. I have appended `let g:vimtex_enable = 1` to my `vimrc` but the problem persists. However, when I manually execute `:call vimtex#init()` the plugin runs normally. Am I missing some extra configuration?

**Comment by fuzzybear3965** [comment]
What is the output of `:set filetype?`?

**Comment by lervag** [comment]
You don't need `g:vimtex_enable`, since this is default on. The problem might be that the internal vim plugin sets your filetype to plaintex. Try to add `let g:tex_flavor = 'latex'` to your vimrc file.

Have you installed other plugins with pathogen? Do they work as expected?

Where did you install vimtex (path) and what is the output of `:echom &rtp`?

**Comment by Laranjadinho** [comment]
1. `set filetype` resolves to `filetype=tex`
2. Added `let g:tex_flavor = 'latex'` to my vimrc but nothing changed
3. Yes, I have some other plugins installed (See Item 5) and they are all working fine.
4. I cloned vimtex repo in `~/.vim/bundle`
5. Output of `:echom &rtp`:
```
~/.vim/bundle/vimtex,/home/laranjadinho/.vim,/home/laranjadinho/.vim/bundle/ctrlp.vim,/home/laranjadinho/.vim/bundle/nerdtree,/home/laranjadinho/.vim/
bundle/vim-airline,/home/laranjadinho/.vim/bundle/vim-airline-themes,/home/laranjadinho/.vim/bundle/vim-colors-solarized,/home/laranjadinho/.vim/bundl
e/vim-fugitive,/home/laranjadinho/.vim/bundle/vim-startify,/home/laranjadinho/.vim/bundle/vim-surround,/home/laranjadinho/.vim/bundle/vimtex,/usr/shar
e/vim/vimfiles,/usr/share/vim/vim74,/usr/share/vim/vimfiles/after,/home/laranjadinho/.vim/bundle/vimtex/after,/home/laranjadinho/.vim/after,~/.vim/bun
dle/vimtex/after
```

**Comment by lervag** [comment]
Strange. Can you open `ftplugin/tex.vim` in the vimtex repo and add `echom b:did_ftplugin` above the `if exists('b:did_ftplugin')` line? I suspect this is the main problem.

**Comment by Laranjadinho** [comment]
I added `echom b:did_ftplugin` and restarted vim but nothing was shown. Just to be sure I did everything correct I added `echom "Test Message"` to `~/.vim/bundle/vim-surround/plugin/surround.vim` (which is working fine) and the message was shown properly. Apparently `vimtex/ftplugin/tex.vim` is not being executed. This is indeed very strange!

**Comment by Laranjadinho** [comment]
I renamed the directory `ftplugin` to `plugin` and the vimtex loaded **sucessfully**. Any ideas why?

**Comment by lervag** [comment]
No, this is strange!

Could you try a minimal vimrc file similar to the ones I propose? I.e. something like:

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

" Vimtex options go here
```

Obviously, you must update the paths to vimtex.

**Comment by Laranjadinho** [comment]
Sorry for the late reply.
I reversed the directory name back to ``ftplugin`` and I used the exact same ``vimrc`` you suggested above, the plugin still didn't work.

**Comment by lervag** [comment]
This is very strange. If you move the `echom 'test'` to the absolute top of the `ftplugin/tex.vim`, it still does not echo anything?

Which OS are you on (or linux distribution). Which version of Vim. Are you using the latest version of vimtex? Does it happen with both gui version and terminal version (gvim and vim)?

**Comment by Laranjadinho** [comment]
Added `echom 'test'` to the very first line and still nothing happened.
I am running Arch Linux with Vim 7.4 Included Patches 1-1584. I don't have a GUI version installed.
Vimtex repo was cloned the same day I created this issue. I pulled the changes now and I have the commit `7497958 Fixed #410: Improve env text object matching`.
`

**Comment by lervag** [comment]
Ok, this is really strange! I have no idea why it doesn't work for you.

However, if you are on Arch, then you can try to update. The current Vim version on Arch is 7.4.1689. Could you also try to install the gui version and try again? You don't need to try the gui version, but perhaps the gui version includes other features that will make the terminal version work as expected.

Finally, you could try to temporarily create a totally new `.vim` folder. It should suffice to use a minimal vimrc file with a `.vim/bundle/vimtex`. Perhaps there are some strange things in your `.vim` folder..?

**Comment by lervag** [comment]
Any progress or update here?

**Comment by Laranjadinho** [comment]
Sorry. I made no progress.

I installed `gvim` package (Version 7.4 Patches 1-1689), created a new `~/.vim` directory and installed only `pathogen.vim` (most recent version from tpope's repository) under `~/.vim/autoload` and `vimtex` under `~/.vim/bundle`. Also I started with a clean `.vimrc` file you proposed earlier in this issue (See below). And `vimtex` still won't load normally.

```
execute pathogen#infect()

set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= '~/.vim/bundle/vimtexafter'
filetype plugin indent on
syntax enable
```

Added `echo "Vimtex Loaded"` to the very top of `~/.vim/bundle/vimtex/ftplugin/tex.vim` and the message won't get printed on the console unless I rename `ftplugin` to `plugin`.

**Comment by fuzzybear3965** [comment]
This seems to be an related to Pathogen. See [here](https://github.com/gregsexton/MatchTag/issues/34) and [here](http://stackoverflow.com/a/9178061/1477586). @Laranjadinho, there is an [open pull request](https://github.com/gregsexton/MatchTag/pull/35) that seeks to ameliorate this issue. But, if you don't want to wait, consider using a more popular plugin manager, like [Vundle](https://github.com/VundleVim/Vundle.vim) or [vim-plug](https://github.com/junegunn/vim-plug).

**Comment by lervag** [comment]
Ah, @Laranjadinho, I've several times tried to push you to use a _minimal_ vimrc file, i.e. NO pathogen. Use this:

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= '~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

The lines `let &rtp ...` will load vimtex, no need for pathogen. Can you try again, now without pathogen?

**Comment by Laranjadinho** [comment]
@lervag sorry I got you wrong, I'm new to vim.

I have repeated the earlier process with the *real* mininal vimrc file and cloned only vimtex repo and **it worked**.

@fuzzybear3965 was right. I am very sorry for the inconvenience and thanks for the attention!

**Comment by lervag** [comment]
@Laranjadinho No problem! I hope I didn't sound to mean/rude/harsh (written text can easily be misunderstood). In any case, I am very happy to hear things are working. Good luck vimming, and don't hesitate to open new issues if you experience other things that don't work as expected!

**Comment by Laranjadinho** [comment]
@lervag By no means, I appreciate your desire to help me. By the way, this plugin is extremely useful, keep up with the good work! :)

**Comment by lervag** [comment]
Thanks!

> @lervag <https://github.com/lervag> By no means, I appreciate your desire
> to help me. By the way, this plugin is extremely useful, keep up with the
> good work! :)
>

**Comment by alem0lars** [comment]
I also had the same problem but for me the fix was adding: `let g:tex_flavor = 'latex'`

Maybe we should add a FAQ entry for this kind of problem?

**Comment by lervag** [comment]
@alem0lars Notice that I suggested already in the first comment to add `let g:tex_flavor = 'latex'`. I've also suggested that one adds this option in the docs, see `:h vimtex-comment-internal`. I know the documentation is quite extensive, but I still think people should take their time to read it. Thus I think it is not needed as a FAQ entry.

**Comment by alem0lars** [comment]
I've read all of the docs but I didn't understand the importance of that setting. Basically by default the plugin doesn't work if you don't have that option turned on.

**Comment by lervag** [comment]
No. If you open a standard LaTeX document, everything works without that setting. However, if you open an empty tex-file, it won't work, beause it will be detected as a plaintex file. I do not remember exactly when a file is detected as a plaintex file, but I think most common latex documents are detected properly.

**Comment by yaojingguo** [comment]
I have a similar problem. `vim foo.tex` does not load vimtex. After I upgrade my pathogen to commit https://github.com/tpope/vim-pathogen/commit/7ba2e1b67a8f8bcbafedaf6763580390dfd93436, the problem is solved.

**Comment by krishpop** [comment]
I have had the same issues, and even that vim pathogen version does not work :(

**Comment by lervag** [comment]
Please open a new issue and describe according to the issue template.
