### ISSUE TITLE
Add troubleshoot section for windows

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#412]
- [x] `behave mswin` (#408)
- [x] Perl installation (#378)

**Comment by fuzzybear3965** [comment]
I have issued a pull request that should address those two naked checkboxes.

**Comment by lervag** [comment]
Thanks! This solves the current issue, but I'm wondering if there are more things that should be added to the docs..?

**Comment by fuzzybear3965** [comment]
I will (when I have time) spin up a Windows virtual machine (VM) and install vimtex from scratch, noting the difficulties I have along the way. I will post all of the difficulties I encounter here. I will try various PDF readers and I will try to obtain "maximum usability" (forward/reverse search, table of contents, etc.). This may take some time. I'll outline my test/set-up flow in a subsequent post to this issue. That post will serve to outline which steps I take to set up vimtex. You can provide feedback before/after I begin setting vimtex up on this VM. I will assume a Windows 10 VM, 64-bit. Unfortunately, I do not have time to test on various versions of the Microsoft Windows OS with varying "bitness-es".

**Comment by fuzzybear3965** [comment]
Let's leave this issue closed, since we have addressed all of the issues posted in the original issue. I will continue to work on this as I have time. Prompt me if you need anything tested explicitly.

**Comment by lervag** [comment]
Thanks! I really appreciate your effort and contributions, btw!
