### ISSUE TITLE
Commit 7bb6aa6... Improve/Fix tikz indentation (#390) breaks compatibility with neovim

### ISSUE THREAD

**Issue by stanislas-brossette** [lervag/vimtex#417]
From this commit, editing a tex file with vimtex in neovim is bugged.
Adding a new line tends to make the screen jump to a new location.
My nvimrc contains only the lines necessary to use vimtex:
```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```
Then in any tex file i get the following strange behavior:
We start in this situation, with the cursor on the one to last line:
![screenshot from 2016-04-04 13 23 16](https://cloud.githubusercontent.com/assets/3499090/14238208/fe29138e-fa68-11e5-90fa-6f08dfe10b28.png)
Then I just press "o" and get in that situation with the cursor in the middle of the screen, and the entire screen has schifted by 14 lines upward:
![screenshot from 2016-04-04 13 23 34](https://cloud.githubusercontent.com/assets/3499090/14238220/21fe9860-fa69-11e5-9c7e-97f8cc325b99.png)

Not sure if I should write that here as an issue or as a comment on the commit of interest?

**Comment by lervag** [comment]
Interesting. I think it is good to open this as an issue.

Since I don't really use neovim yet, could you please explain briefly how to setup neovim from scratch to test and reproduce the issue? It would be helpful with a full configuration example (I've understood that neovim has moved to a slightly different config file system than Vim).

**Comment by stanislas-brossette** [comment]
For the full setup, I installed neovim by following the guidelines here https://github.com/neovim/neovim/wiki/Installing-Neovim
The configuration file `~/.nvimrc` can be setup like this
```
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
ln -s ~/.vim $XDG_CONFIG_HOME/nvim
ln -s ~/.nvimrc $XDG_CONFIG_HOME/nvim/init.vim
```
Install vim plug:
```
curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
```
Fill your ~/.nvimrc with:
```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```
Install vimtex from within neovim with command `:PlugInstall`
Then everything is setup.
Open any tex file and you should be able to observe the bug by simply opening a new line with 'o' anywhere and notice that the screen scrolls without reasons.

**Comment by lervag** [comment]
Ok, I can reproduce the problem. I'll look into it.

**Comment by lervag** [comment]
Ok, I didn't find the reason why it broke, so I ended up fixing with a somewhat "hackish" solution. It seems to work well, though.

**Comment by stanislas-brossette** [comment]
Seems to work for me as well :+1: 
Thanks

**Comment by lervag** [comment]
No problem! It might affect/have affected regular Vim as well, cf. #420.
