### ISSUE TITLE
Buffer scroll when introducing unbalanced parens? 

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#420]
Hi -- this is just a head-on, because I was not be able to obtain a minimal example, and it's quite late in the evening now here... so I will try again tomorrow, otherwise I will close this issue. 

I have a quite big latex file (180 lines) and when I go in the middle of it and start adding text (with for example `o` and then typing) and I type a unbalanced delimiter (a `(`, for example), the buffer scrolls down in a strange way. Sometime the scroll happens just with pressing `o`... 

Can anyone reproduce it? Otherwise I'll try to dig the behavior in my configuration. I have 

```
set scrolloff=2 " see a couple of lines around top and bottom
set display+=lastline " show partial long lines 
````

in my `.vimrc`, but they don't seems to be the culprit.

**Comment by lervag** [comment]
Does it happen with the latest version?

Den tir. 5. apr. 2016, 23.13 skrev Romano Giannetti <
notifications@github.com>:

**Comment by lervag** [comment]
This sounds a lot like #417, which I fixed yesterday.

**Comment by Rmano** [comment]
Yes, it seems it was it. I update and I am not able to reproduce. 
Unfortunately, something in the last changes broke the two ways search with `okular`...  any idea before I open another issue? Thanks!

**Comment by lervag** [comment]
Hmm, strange. I did update some things that might cause it, but it seems to work well here (though, with zathura and mupdf, I haven't tested with Okular). I'll be happy to investigate if you open an issue, and I am sorry for breaking things!

**Comment by lervag** [comment]
I guess we can close this issue, then?

**Comment by Rmano** [comment]
Yes --- the update solved it (and I think that it was a duplicate of #417).

The okular problem was a false alarm --- the problem is that I use the `comment` package (see http://tex.stackexchange.com/a/301606/38080) which uses a temporary file --- and the backref goes to that temporary file. Unfixable, clearly. Sorry for the noise.

**Comment by lervag** [comment]
Ah, I see! And no problem!
