### ISSUE TITLE
Add -synctex and -interaction=nonstopmode as options to latexmk?

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#423]
I recently learned that one may pass some options directly to `latexmk`, see #422. This allows me to pass `-synctex=1` and `-interaction=nonstopmode` as options directly to `latexmk`, which should make a lot of things work without custom options and `.latexmkrc` files. I'm curious if there are reasons _not_ to add these options?

I am hoping for comments from people like @fuzzybear3965, @hubanya, @frankier.

**Comment by hubanya** [comment]
That sounds excellent! I personally don't see any reason of not having `-synctex=` and `-interaction=nonstopmode` as builtin options.

**Comment by lervag** [comment]
@nasenatmer @Konfekt @mbrunnen Perhaps you guys have some thoughts? Personally, I think this seems a good idea. It seems like a safe way to go. But perhaps I am missing something important?

**Comment by fuzzybear3965** [comment]
I'm not sure I understand what you mean by "[this] should make a lot of things work without custom options". 

1. Would you still keep the `g:vimtex_latexmk_options` option around? 
1. Would also only conditionally add `-synctex=1` and `-interaction=nonstopmode` based on some option like `g:vimtex_latexmk_synctex_enabled` and `g:vimtex_latexmk_interaction_nonstopmode`?

If both of the above are true, then yeah, I would totally agree that moving the most stuff out of `pdflatex=` is a great idea.

**Comment by Konfekt** [comment]
Sounds, good. Even better if there's a way ti override it. Because these parameters shadow thos of the latexmkrc, the vimtex latexmk options variable should be able to do so. Adding an extra variable for the synctex and nonstop mode looks inelegant, better explain tge latexmk paranetera in the vimtex option in the doc.

**Comment by lervag** [comment]
@fuzzybear3965 No, I don't want to have more options, but I would of course still keep the `g:vimtex_latexmk_options`. I could consider to have one option to "disable" the default options, i.e. `-pdf -verbose`, as well as the new proposed options. This would make it possible to override the default values for whomever would want to do that.

Note, the suggested change will move ALL of the stuff out of the `pdflatex=...`.

**Comment by fuzzybear3965** [comment]
I think that I understand, now (sorry for being slow on the uptake). If the user defines their own `g:vimtex_latexmk_options` option, then vimtex will default to using this. In the case where it is not included in the user's vimrc file, `vimtex` will take responsibility for providing some reasonable defaults.

That sounds great. So, right now, if I want `-interaction=nonstopmode` I have to do something like `let g:vimtex_latexmk_options='-pdflatex="--interaction=nonstopmode"'`. Your solution would allow me to write `g:vimtex_latexmk_options="-interaction=nonstopmode"`, but would not provide a separate option for changing the interaction mode to nonstopmode.

**Comment by mbrunnen** [comment]
I think, you could really put `-interaction=nonstopmode` as built-in default latexmk option. The `errorstopmode` is not necessary since errors are handled by vim's quickfix. About synctex I know to little.

**Comment by lervag** [comment]
I've updated according to what I've been thinking. I think this is a good change. Now the `g:vimtex_latexmk_options` variable will override the general options with user supplied options, which allow full customization. If one does not set this vimtex option, then a sensible set of defaults will be used, which now includes `-interaction=nonstopmode` and `synctex=1`.

**Comment by fuzzybear3965** [comment]
That's a great idea. A section should be added to the Troubleshooting (or possibly more related) section indicating that if the user does not include these two options in `g:vimtex_latexmk_options`, instead setting it to some other string, these options will not be enabled.

**Comment by lervag** [comment]
No, you misunderstood. `g:vimtex_latexmk_options` is _empty_ by default. Here is the updated description for the option:

```md
*g:vimtex_latexmk_options*
  By default, |vimtex| passes the following options to `latexmk`:

     -pdf                     -- Compile to pdf documents
     -verbose                 -- More verbose output
     -file-line-error         -- Enable file:line:error style messages
     -synctex=1               -- Generate synctex data
     -interaction=nonstopmode -- Disable interactive mode

  However, if `g:vimtex_latexmk_options` is defined and is nonzero, it will
  override the above with the user supplied options.

  Note: Options may also be specified indirectly to `latexmk` through
        both a global and a project specific `.latexmkrc` file. One should
        know, though, that options specified on the command line has priority,
        and so if one wants to override one of the above default options, then
        one has to set `g:vimtex_latexmk_options` to a string that contains
        the desired options.

  Default value: ''
```

Note: The default value is an empty string, and the option only becomes relevant if it is defined, and in this case, the mentioned default options will all be overridden.

**Comment by lervag** [comment]
(Or perhaps I mistunderstood you..?)

**Comment by fuzzybear3965** [comment]
Yes, I believe that you did misunderstand me. But, I could have been clearer. In the case where the user defines a `g:vimtex_latexmk_options` string that does not include `-interaction=nonstopmode` and/or `synctex=1` then they will be missing out on automatic error/warning skipping and/or forward/reverse search. I'm sure you will have users who choose to define their own `g:vimtex_latekmk_options` string but neglect to include these options. Their compilation will, then, run in batch mode and/or they won't have the inverse search that they crave so dearly. 

I'm suggesting that we include in the documentation that any user-provided `g:vimtex_latexmk_options` string should define at least `-interaction=nonstopmode` so as not to be limited when using vimtex.

**Comment by lervag** [comment]
Ah, yes. I agree. I've updated the docs to better describe how the default options are set. I think the docs should now complement the default options and explain the possible customization pretty well. I'll therefore close this issue.

Please feel free to comment, perhaps I did not think this through as well as I have thought..?

**Comment by lervag** [comment]
For reference, see 2f04e8f96263a71b56def5530ac5f38bb951e78a.
