### ISSUE TITLE
<plug>(vimtex-toggle-delim) throws error

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#427]
*<plug>(vimtex-toggle-delim)* on

```tex
$
\bigl (
\begin{smallmatrix}
  \Q^* & \\
         & 1\\
\end{smallmatrix}
\bigr )
$
```
yields
```vim
Error detected while processing function vimtex#delim#toggle_modifier:
line   18:
E684: list index out of range: 0
E15: Invalid expression: strpart(line, 0, l:open.cnum - 1) . newmods[0] . strpart(line, l:open.cnum + len(l:open.mod) - 1)
line   35:
E684: list index out of range: 1
E15: Invalid expression: strpart(line, 0, l:cnum - 1) . newmods[1] . strpart(line, l:cnum + len(l:close.mod) - 1)
```

**Comment by lervag** [comment]
I was slightly curious how to fix. I ended up choosing to let the toggle remove the modifiers. Note the option `g:vimtex_delim_toggle_mod_list`, which defines the list of modifiers to toggle between.

**Comment by Konfekt** [comment]
Alligator, thanks!

**Comment by lervag** [comment]
No problem. Alligator?

**Comment by Konfekt** [comment]
Haha, text recognition. Alright it was meant to be.

**Comment by Rmano** [comment]
Ah, I was thinking about ["see you later..."](https://en.wikipedia.org/wiki/See_You_Later,_Alligator) ;-)
