### ISSUE TITLE
sections no longer fold

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#430]
With
```vim
let g:vimtex_fold_enabled = 0
let g:vimtex_fold_sections = [
      \ "part", "chapter", "section",
      \ "subsection", "subsubsection",
      \ "paragraph", "subparagraph",
      \ ]
let g:vimtex_fold_comments = 1
autocmd FileType tex setlocal foldmethod=expr foldexpr=vimtex#fold#level(v:lnum)
```
and for example
```tex
\documentclass{beamer}
\begin{document}

\section{Intro}

\begin{frame}
\frametitle{Quais as partes de um autômato finito?}
\begin{block}{Programa ou Função de Transição}<3->
Função que controla a leitura da fita e as transições de estados.
\end{block}
\end{frame}

\end{document}
```
the `\section{Intro}` does not fold when hitting `zc`.

Everything works with `let g:vimtex_fold_enabled = 1` though.

**Comment by Konfekt** [comment]
Well, closing for now. This 'bug' persists, but found that
```vim
autocmd FileType tex setlocal foldtext<
```
is a much more elegant way to preserve my handcrafted foldtext.

**Comment by lervag** [comment]
I'm curious: What's the goal? Is it to use your own foldtext function?

In any case, I think the problem might be related to an "internal" variable `b:vimtex_fold`. It is not defined unless folding is enabled, and thus it might break folding if it is enabled manually.

I think my latest commit fixes this.

**Comment by Konfekt** [comment]
Exactly, it was just to leave the default foldtext function untouched. But the last autocmd is more stable as it leaves the default setup to enable vimtex's folding intact.
