### ISSUE TITLE
latexmk not quit when gvim finishes

### ISSUE THREAD

**Issue by nomeata** [lervag/vimtex#435]
Hi,

I just upgraded vimtex (from f9de44b to 270eb33), and now latexmk is no longer stopped when I exit vim, or use `\ll` to stop latexmk.

It does successfully quit the `vim --servername --remote-expr vimtex#latexmk#callback(1)` process.

It happens with a most minimal TeX file and an empty `~/.latexmkrc` and this `.vimrc`:

 ```vim
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

**Comment by fuzzybear3965** [comment]
@nomeata, are you saying that you can see in the Windows Task Manager that the `latexmk` process is still active, but that the `perl` process is killed?

**Comment by lervag** [comment]
@nomeata Strange. I don't have this problem. Can you provide some more background details: Which OS are you on, which version of Vim, which version of latexmk. What is the output of `\li` after you have started compilation with `\ll`?

**Comment by nomeata** [comment]
Yes, I see the `perl latexmk` process in `ps -A` (Linux here. Debian unstable to be precise, sorry for omitting that detail).

```
 $ gvim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 08 2016 02:37:20)
Inklusive der Korrekturen: 1-1689
$ latexmk --version
Latexmk, John Collins, 1 January 2015. Version 4.41
```

`\li` after compilation is started:
```
b:vimtex : foo
  pid : 11765
  root : '/tmp'
  aux : '/tmp/foo.aux'
  log : '/tmp/foo.log'
  out : '/tmp/foo.pdf'
  tex : '/tmp/foo.tex'
  tmp : '/tmp/vUEwBue/3'
  cmd_latexmk_compile : 'cd ''/tmp'' && max_print_line=2000 latexmk -verbose -pdf -file-
line-error -synctex=1 -interaction=nonstopmode -pvc -e ''$success_cmd = "''""''vim''""''
 --servername  --remote-expr \"vimtex\#latexmk\#callback(1)\""'' -e ''$failure_cmd = "''
""''vim''""'' --servername  --remote-expr \"vimtex\#latexmk\#callback(0)\""'' -e ''$pdf_
previewer = "evince"'' ''foo.tex'' >/tmp/vUEwBue/3 2>&1'
  base : 'foo.tex'
  viewer
    init : function('115')
    view : function('116')
    latexmk_append_argument : function('117')
```
and after stopping it again with `\ll`:
```
b:vimtex : foo
  pid : 0
  root : '/tmp'
  aux : '/tmp/foo.aux'
  log : '/tmp/foo.log'
  out : '/tmp/foo.pdf'
  tex : '/tmp/foo.tex'
  tmp : '/tmp/vUEwBue/3'
  cmd_latexmk_compile : 'cd ''/tmp'' && max_print_line=2000 latexmk -verbose -pdf -file-
line-error -synctex=1 -interaction=nonstopmode -pvc -e ''$success_cmd = "''""''vim''""''
 --servername  --remote-expr \"vimtex\#latexmk\#callback(1)\""'' -e ''$failure_cmd = "''
""''vim''""'' --servername  --remote-expr \"vimtex\#latexmk\#callback(0)\""'' -e ''$pdf_
previewer = "evince"'' ''foo.tex'' >/tmp/vUEwBue/3 2>&1'
  base : 'foo.tex'
  viewer
    init : function('115')
    view : function('116')
    latexmk_append_argument : function('117')
```

**Comment by fuzzybear3965** [comment]
It seems that compilation has terminated. [PID 0](http://unix.stackexchange.com/questions/83322/which-process-has-pid-0) is not a valid user space process id. There is no such thing as a `perl latexmk` process. Can you provide the output of `ps -A | grep latexmk` and `ps -A | grep perl` before and after `\ll`?

**Comment by nomeata** [comment]
Sure. 
Before:
```
$ ps -A ww|grep latexmk
12232 pts/4    S+     0:00 grep --color=auto latexmk
```
After enabling compilation with `\ll`:
```
$ ps -A ww|grep latexmk
12243 ?        S      0:00 /bin/bash -c cd '/tmp' && max_print_line=2000 latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e '$success_cmd = "'""'gvim'""' --servername GVIM2 --remote-expr \"vimtex#latexmk#callback(1)\""' -e '$failure_cmd = "'""'gvim'""' --servername GVIM2 --remote-expr \"vimtex#latexmk#callback(0)\""' -e '$pdf_previewer = "evince"' 'foo.tex' >/tmp/vGn0cL5/3 2>&1 &
12244 ?        S      0:00 perl /usr/bin/latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e $success_cmd = "gvim --servername GVIM2 --remote-expr \"vimtex#latexmk#callback(1)\"" -e $failure_cmd = "gvim --servername GVIM2 --remote-expr \"vimtex#latexmk#callback(0)\"" -e $pdf_previewer = "evince" foo.tex
12254 pts/4    S+     0:00 grep --color=auto latexmk
```
After stopping compilation with `\ll`:
```
$ ps -A ww|grep latexmk
12243 ?        S      0:00 /bin/bash -c cd '/tmp' && max_print_line=2000 latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e '$success_cmd = "'""'gvim'""' --servername GVIM2 --remote-expr \"vimtex#latexmk#callback(1)\""' -e '$failure_cmd = "'""'gvim'""' --servername GVIM2 --remote-expr \"vimtex#latexmk#callback(0)\""' -e '$pdf_previewer = "evince"' 'foo.tex' >/tmp/vGn0cL5/3 2>&1 &
12244 ?        S      0:00 perl /usr/bin/latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e $success_cmd = "gvim --servername GVIM2 --remote-expr \"vimtex#latexmk#callback(1)\"" -e $failure_cmd = "gvim --servername GVIM2 --remote-expr \"vimtex#latexmk#callback(0)\"" -e $pdf_previewer = "evince" foo.tex
12265 pts/4    S+     0:00 grep --color=auto latexmk
```

> There is no such thing as a perl latexmk process.

I’m not sure what you mean with that.

**Comment by fuzzybear3965** [comment]
I simply meant there is no program called `perl latexmk`, so such a process could not exist.

Hm, can you confirm that the statusbar changes state upon start and stopping compilation: `latemxk compile: started continuous mode` becomes `latexmk compile: stooped`?

Also, what did you mean when you said, "It does successfully quit the `vim --servername --remote-expr vimtex#latexmk#callback(1)` process"? How does the above output in either or both your two most recent posts confirm that such a command was successfully killed?

**Comment by lervag** [comment]
@nomeata Strange. Do you know how to perform a git bisect? If so, could you do one on the vimtex repo and identify which commit breaks things for you? If not: Can you verify that the old commit really does work as expected (i.e. f9de44b), and then again verify that the commit 270eb33 does not work?

When things don't work: Do the PID's correspond to the output of the manual `ps` commands?

**Comment by nomeata** [comment]
> Do you know how to perform a git bisect? I

Yes... sorry for not thinking about that before (and being lazy :-))

Here is the culprit:
```
5cda0b3410c80094ae573cde168d822737aee783 is the first bad commit
commit 5cda0b3410c80094ae573cde168d822737aee783
Author: Karl Yngve Lervåg <karl.yngve+git@gmail.com>
Date:   Fri Apr 1 10:21:43 2016 +0200

    Fixed #402: /usr/bin/perl instead of perl
```

Also, only now I notice that this message is left on the console after stopping compilation with `\ll` and quitting vim:

```
/bin/bash: line 0: kill: (13455) - No such process
```

Strangely, at least when compilation has started, `pgrep -nf "perl.*latexmk"` and `pgrep -nf "^perl.*latexmk"` yield the same pid (13454`, which is the pid of the `perl latexmk` process:
```
13454 pts/2    S+     0:00 perl /usr/bin/latexmk -verbose -pdf -file-line-error -synctex
=1 -interaction=nonstopmode -pvc -e $success_cmd = "vim --servername  --remote-expr \"vi
mtex#latexmk#callback(1)\"" -e $failure_cmd = "vim --servername  --remote-expr \"vimtex#
latexmk#callback(0)\"" -e $pdf_previewer = "evince" foo.tex
```
Aha, but **not** the pid that vimtext believes it is, according to `\li`
```
b:vimtex : foo
  pid : 13455
```
which is also the PID it tries to kill there.

I am not sure what other process that matches the less strict regex (without `^`) is there in the moment vimtex fires up latexmk.  Maybe latexmk is forking itself? Anyways, this seems all very fragile... what if I run multiple instances of vim with a TeX document?

**Comment by nomeata** [comment]
Anyways, here is a suggestion that works here, and likely works for the reporter of #402 as well:
```
pgrep -nf "^[^ ]*perl.*latexmk"
```

**Comment by lervag** [comment]
Thanks for your investigation! I'm a little bit confused: Which PID is detected by vimtex? That is, when you do `pgrep -nf ...`, you get two different PIDs with different commands. Which of these commands are related to the vimtex PID? Perhaps it is easier to find this through `ps aux|grep latexmk`. To be clear, what I want is to understand WHY the current version fails. Based on comments so far, I don't see anything that should lead to this problem.

I've applied your fix, but I would still like to understand why it is needed.

**Comment by nomeata** [comment]
> Which PID is detected by vimtex?

That’s the weird thing. I don’t know! By the time I get to run the command manually, it finds the `latexmk` process, so the process it finds must have quit by then.... but after some thought, it’s obvious: Without the anchor in the regex, the `pgrep` process likely finds itself!

**Comment by lervag** [comment]
No, I don't really think so.

Could you please try one thing, just because I'm curious: Could you change line 539 in `latexmk.vim` according to the following diff:

```diff
+    let b:vimtex.pid_line = system('pgrep -nfa "perl.*latexmk"')[:-2]
+    let b:vimtex.pid = str2nr(b:vimtex.pid_line)
-    let b:vimtex.pid = str2nr(system('pgrep -nf "^[^ ]*perl.*latexmk"')[:-2])
```

Now, when you perform the initial test with `\ll`, then `\li`, the info should include the `pid_line`, which should show the full command line of the pgrep result. This might help with discovering what is really happening.

**Comment by nomeata** [comment]
Good idea, and it confirms my suspicion, although it’s not the `pgrep` itself, but rather the `bash` that calls it.
```
pid_line : '8762 /bin/bash -c (pgrep -nfa "perl.*latexmk") >/tmp/vgubzCJ/4 2>&1'
```

**Comment by lervag** [comment]
Ah, there it is. Thanks! Although, this does not explain why this happens on your end, and not on mine. But it is good enough. With this I think we can consider the issue both understood and resolved. Again, thanks!
