### ISSUE TITLE
Auto-formatting with gq

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#436]
There currently exists a simple implementation of the `formatexpr`, however, as apparent through e.g. #317, it should be improved. In this thread, I will clearly define how it should work. The list of requirements will be updated based on the following discussion.

Requirements/Rules:

- [x] Don't join from below on lines that end with comment or newline type commands.
- [x] Lines that start with \item should not join the line above.
- [x] Environment boundaries should block joining (perhaps excluding the case where the boundary is defined inline?).
- [ ] Don't join lines inside some environments, e.g. math and verbatim(?).

Possible additions:

- [x] Option to support that `gq` never joins any lines (only splits)

**Comment by nilsbecker** [comment]
about environments: what about math? i would think `$` and `\(` can be joined but `\[` and `$$` should block joining to the previous while `\]` and `$$` block joining from below?

**Comment by nilsbecker** [comment]
another one: comment blocks like so:
```
% do not compile
% old \commands{} and stuff that are kept around for potential reuse
% TODOs 
% etc
```
should definitely not be garbled. the next question is: do nothing, or apply the same rules as otherwise, just to the block without the leading columns, and then re-decorate with `% ` to keep it as a comment?

**Comment by lervag** [comment]
Ok, sorry that this has taken so long! I've made an updaste that should, I think, significantly improve the formatting. Please test it and provide some feedback. I think the following can still be added/improved:

- [ ] Prevent formatting inside selected environments (i.e. math environments, including `$$` and `\[`)
- [ ] Consider formatting of comments

I've decided to not add an option to only split lines, never join them. At the moment, I am utilizing the built in `gw` formatter, which will both split and join lines in the provided ranges. If I were to add such an option, then I would have to write the formatter code myself, now I only parse the lines and selectively apply `gw` on "safe" lines.

**Comment by lervag** [comment]
Ok, as I've implemented most of what''s been asked, I will take the liberty of closing this. I think I will be able to refine and improve if there are specific requests, but it seems to work well for me right now. Please don't hesitate to open follow-up issues for improvement requests or if you find bugs/problems with the current version.

**Comment by nilsbecker** [comment]
i'll have a look at this tomorrow. thanks for working on it.

**Comment by nilsbecker** [comment]
i did a bit of testing. mostly it works beautifully. math environments are preserved as far as i can tell and so are end-of-line comment signs and `\item`s. 

one imperfection i noticed was some extra spaces introduced at the beginning of the last lines when formatting the example pasted below. this depends a lot on the exact length of the whole paragraph. i could not find an easy way to make a minimal example, so sorry for the blah-blah.

```
Therefore, in that case the observed dynamics cannot be truly
Markovian. We can still approximately capture the observed density dynamics
with eq.~\ref{eq:fpe}; however the local coefficients are then effectively
averages over the co-evolving unobserved distribution. For example, $\vec
v(\vec x,t)=\int p(\vec x^u|\vec x,t)v(\vec x,\vec x^u,t)dx^u$. This has some
important consequences. First, the effective Markovian coefficients $\vec v,
\lambda, D$, will generally depend on time, reflecting the time evolution of
the hidden $p(\vec x^u)$ over the time scale of the experiment. Second, the
effective coefficients may also depend on the initial condition: a cell
population started concentrated around label $\vec x_0$ implies a certain
distribution over $x^u$ when sampled at label $\vec x$ some time later; another
population started around $\vec x_1$ carries a different history when it, too,
visits $\vec x$ later. Therefore, for instance the effective drift $\vec v(\vec
x)$ will be different in the two cases. We conclude that, if unobserved degrees
of freedom have dynamics on the time scale of the experiment eq.~\ref{eq:fpe}
is an approximation whose coefficients become \emph{non-universal} (dependent
on intial conditions) and \emph{time-dependent}.
```

**Comment by lervag** [comment]
This is not due to the new `formatexpr`; you can see the same behaviour with `gw` (which uses the internal formatter). It seems to be due to some options. Looking into it now.

**Comment by lervag** [comment]
Actually, it is due to a bug in the `indentexpr`. It seems slightly nontrivial, but I will try to find a good way to fix it.

**Comment by lervag** [comment]
I can't find any good fix for this. It seems that the `indentexpr` is used after formatting, even with `gw`, and that for some reason, the buffer lines do not look the same after formatting. It is hard to explain, but I think there might be a Vim bug here. I don't have the time or energy to follow up and report a good bug report, but I think we can compromise by turning off reindentation when formatting lines.

I've pushed the change now, please test. If it has other strange side effects, then I'll reconsider.

**Comment by lervag** [comment]
By the way, as you yourself say, this problem only occured a few times, and it was very hard to construct a minimal example. The reason is just as I said. When the indentexpression is called from the formatting function, `getline(v:lnum)` returns something VERY different from what it does when the indentexpression is called in a normal manner. It also seems quite random, which means it is difficult to know how to solve this...

**Comment by lervag** [comment]
I now see that the hack I found makes formatting not work properly in some other examples. Thus I think perhaps we should just accept that this is a bug in Vim. I don't see a good way to fix this. :\

**Comment by nilsbecker** [comment]
i guess that's ok. it's only a minor inconvenience.

**Comment by lervag** [comment]
I've made some minor progress in creating a minimal example. I've opened a question on [vi.stachexchange.com](https://vi.stackexchange.com/questions/8964/can-someone-explain-the-strange-behaviour-with-indenting-during-reformatting). I will submit it as a bug report for Vim unless someone has a good explanation of the phenomenon.

**Comment by lervag** [comment]
I've now posted [an issue](https://github.com/vim/vim/issues/951) at the Vim github page.

**Comment by danielbmarques** [comment]
I don't know if I'm doing something stupid, but with Vimtex's `formatexpr` `gq` won't work for me if there's a single really long line. Also the lines won't break automatically when I'm typing and I go over `textwidth`. Is that on purpose?

**Comment by lervag** [comment]
Thanks, there was a minor bug in one of the conditionals. Should be fixed now.

**Comment by danielbmarques** [comment]
Ok, now it works with a single line, but instead of automatically breaking to the next line it just goes to the start of the same line, haha.

**Comment by lervag** [comment]
Hmm. Strange. It also broke a test which seems unrelated. I don't quite see the problem right now, but I'll look into it.

**Comment by danielbmarques** [comment]
Ok then, thanks. :)
I can open a new issue to keep track if you want me to. I just didn't do it at first because I wasn't sure if it was a bug.

**Comment by lervag** [comment]
Ok, I've now written the formatexpr fully by hand without depending on the internal `gw`. It still does not work for autoformatting while writing, but it now works as expected on the earlier example. I'm trying to find a way to make it work on a single line.

**Comment by danielbmarques** [comment]
Awesome, thanks for working on this. :)

**Comment by lervag** [comment]
Ok, with the latest commits, I think it should work as expected. Please try again now.

**Comment by lervag** [comment]
And, since this thread is so large, I think it will be good to open a new issue if you find problems. It should suffice with a small example of something that does not format as expected.

**Comment by danielbmarques** [comment]
It's working perfectly so far. Thanks! 🎉

**Comment by lervag** [comment]
Great! It was fun work :)
