### ISSUE TITLE
error related to highlight_matching_pair

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#440]
## Explain the issue

After upgrading to the latest commit 913d97de00c6c71a8838c7e48fa8196b1e4b21ed I get the following error when I search for "pmatrix" (the document contains pmatrix environments):

`
Error detected while processing function <SNR>62_highlight_matching_pair..vimtex#delim#get_current..<SNR>53_get_de
lim..<SNR>53_parser_env..vimtex#cmd#get_at..vimtex#cmd#get_current..<SNR>50_get_cmd:
line   16:
E716: Key not present in Dictionary: close.lnum
Press ENTER or type command to continue
Error detected while processing function <SNR>62_highlight_matching_pair..vimtex#delim#get_current..<SNR>53_get_de
lim..<SNR>53_parser_env..vimtex#cmd#get_at..vimtex#cmd#get_current..<SNR>50_get_cmd:
line   16:
E15: Invalid expression: arg.close.lnum
Press ENTER or type command to continue
Error detected while processing function <SNR>62_highlight_matching_pair..vimtex#delim#get_current..<SNR>53_get_de
lim..<SNR>53_parser_env..vimtex#cmd#get_at..vimtex#cmd#get_current..<SNR>50_get_cmd:
line   17:
E716: Key not present in Dictionary: close.cnum
Press ENTER or type command to continue
Error detected while processing function <SNR>62_highlight_matching_pair..vimtex#delim#get_current..<SNR>53_get_de
lim..<SNR>53_parser_env..vimtex#cmd#get_at..vimtex#cmd#get_current..<SNR>50_get_cmd:
line   17:
E15: Invalid expression: arg.close.cnum
`

### Steps to reproduce

Create a long enough document containg \begin{pmatrix} ... \end{pmatrix} somewhere close to the end. Put the cursor at an early enough place in the document.

Then search for "pmatrix".

### Expected behaviour

The first occurrence of pmatrix is found.

### Observed behaviour

The above error.

## Minimal working example

From my experience it seems that the document must be big enough. I have not found a minimal working example yet.

**Comment by lervag** [comment]
I created a tex file with 1500 lines, where I include various equation environments that has the pmatrix environment. I can not reproduce your issue.

Please use a minimal vimrc file and test again. Feel free to upload a less minimal tex example where the problem occurs. Without reproducability, there is nothing I can do...

**Comment by heiderich** [comment]
The following file works with a rather minimal vimrc: 
http://arxiv.org/e-print/0712.3748v4
I can reproduce the problem by placing the cursor at the beginning of this file followed by a search for "pmatrix".

**Comment by lervag** [comment]
Great, I reproduced and fixed the error.

**Comment by lervag** [comment]
Thanks for noticing and reporting!

**Comment by heiderich** [comment]
Thanks for the fix.
