### ISSUE TITLE
Table of content incomplete for \input from subdirs

### ISSUE THREAD

**Issue by wouterl** [lervag/vimtex#441]
When using \input from files \included in sub directories the table of content is not build correctly. In particular, the files \inputted from the subdirs are not included in the table of content for VimTex.

It might be that the somewhat annoying way in which you have to use \input in Latex -- all paths are relative to the root -- is to blame here.

### Minimal working example

The example uses three files.

`main.tex`:
```tex
\documentclass{article}

\begin{document}
\include{sectiond/section}
\end{document}
```

`sectiond/section.tex`:
```tex
\section{Section}
\input{sectiond/subsection}
```

`sectiond/subsection.tex`:
```tex
\subsection{subsection}
```

When opening the table of content (`:VimtexTocOpen`) only the section is shown, not the subsection.

### Minimal vimrc file

I confirmed that the problem persists with the following minimal vimrc file.

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
```

### Thanks

Thanks for your work on vimtex. It is very pleasant to use!

**Comment by lervag** [comment]
Thanks, I think this is a bug, and I think I see what the bug is. `\input` (and probably also `\include`) always use relative paths with respect to the main file. I think the current parser uses relative to the file where the include/input line is.

I'll look into it when I get the time!

**Comment by lervag** [comment]
I think this should be solved now.

**Comment by wouterl** [comment]
Works like a charm. Thx :).

**Comment by lervag** [comment]
No problem! :)
