### ISSUE TITLE
zathura reloads pages while pdf document is still in the process of being compiled

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#443]
Especially with larger latex documents, zathura happens to update before
the compilation (pdflatex in my case) is finished. This is expected,
since zathura automatically always updates automatically (at least up to the current stable version 0.3.6 this is the case). I consider this inconvenient, because one is no longer able to view the PDF while pdflatex is running. 

In the meantime there is an option for zathura to update when a SIGHUP is received (in the develop branch). This addresses the problem. However, the following problem remains: It seems that usually not the whole PDF document is cached by zathura. So if you want to view other parts of the  document while pdflatex is running, this might not be possible (I guess that this affects those parts that are not cached).

Other approaches (e.g. [atp-vim](https://github.com/coot/atp_vim/)) compile the PDF in a
temporary directory and only update the pdf that one is viewing after
successful compilation. This avoids this problem but adds more complexity to the vim-side of the implementation.

From a user perspective I consider the atp-vim approach to be very convenient. I wonder if this behavior could be realized using vimtex. I think it could be done either inside vimtex itself of at the side of latexmk.

**Comment by heiderich** [comment]
A first attempt is the following: The following options for latexmk will cause a copy of the generated pdf file to be generated when latexmk thinks that the pdf viewer should be updated:

$pdf_update_method = 4;
$pdf_update_command = 'cp %R %R_view.pdf';

Remark: Maybe %R is not the right placeholder here in general. I saw %S used elsewhere.

Looking at the file %R_view.pdf with zathura in auto-update mode is a first solution to my problem.

I am not familiar with the internals of vimtex. Adding these two options to the function s:zathura.latexmk_append_argument() defined in autoload/vimtex/view.vim as follows passes these arguments to latexmk:
`let cmd .= vimtex#latexmk#add_option('pdf_update_method', '4')
  let cmd .= vimtex#latexmk#add_option('pdf_update_command', 'cp \%R.pdf \%R_view.pdf')`

I am not sure how willing Karl is to implement something like this as a standard behavior in vimtex. Another option would be to implement another viewer in vimtex called "zathura_copy" (or something similar) that would differ by the above mentioned from the standard zathura.

However, as it stands, this breaks synctex support. I do not know how easy this is. Hopefully it would be enough to make vimtex aware of the different name (%R_view.pdf instead of %R.pdf in latexmk notation).

At the other side, I think all viewers could possibly profit from such a behavior. So one may consider a general implementation of this "copy" approach.

**Comment by lervag** [comment]
You could do this in your own `.latexmkrc` file, which could at least help you to test if this works. I actually think this looks very fragile for a feature for vimtex.

**Comment by lervag** [comment]
Sorry for the short reply; I just wanted to update the formatting of your comment before I continued. So.

First, I don't have time to test the SIGHUP method of updating yet, but assuming it works as expected, I think it should provide a very decent compromise between the current solution, where the zathura window may go black while compiling, and the "optimal" solution where the zathura window is perfectly accessible at all times, and where it updates only when a compilation cycle is fully completed.

I don't really aim for vimtex features to be perfect. Instead, I try to have useful features that are relatively easy to maintain and that provide enough convenience for me in particular and other users in general to be useful. In order to implement the optimal solutions, I have to use a lot of special/edge case treatment. This is hard to maintain and it is not always very much better than a merely good or acceptable solution.

I think this case is a good example of what I just talked about. I find the current solution satisfactory. It is relatively easy to maintain, at the same time as it is quite useful. Improving it in the ways you suggest require, as far as I can see, quite a lot of updates and changes. The changes will affect much of the vimtex code, I think, and it might need either several new options, or a lot of conditionals in the code to only use the feature for the relevant viewer(s).

I hope you can understand my reasoning about this. I understand that the feature you ask can be quite useful, but at the same time, both I and others are able to work well with large LaTeX document without this particular issue being a problem.

**Comment by lervag** [comment]
Note, though, that I see one approach for solving this that _could_ be tested:

- First, `latexmk` should not open any viewers (`-view=none`)
- Next, the vimtex function `b:vimtex.out()`, which is used by the viewers to get the path of the pdf file, should return the path to a "temporary" pdf file, not the compiled one
- Finally, the latexmk callback function should
  - copy the compiled file to the temporary file for viewing
  - send a signal to the viewer to update (if necessary)

These steps should suffice to implement the desired functionality. I will actually consider to implement it for testing, when I get the time.

**Comment by lervag** [comment]
Ok, I've added a new viewer: `zathura_alternative`. It should now use the callback functionality to copy the file to a temporary file, and then use this temporary file for viewing. There might be some remaining issues, but I decided to push it to see if you think this might be an acceptable solution.

**Comment by lervag** [comment]
It seems to work pretty well, except for forward searching. I haven't been able to get that working. If you have some idea for how to make that work, I'd be very happy. It seems that the forward search stops working when I change the name of the pdf...

**Comment by lervag** [comment]
Note to self: write docs.

**Comment by heiderich** [comment]
Thanks for adding this feature. It looks promising. Forward search seams to work for me, at least after the compilation is finished. 

When I edit foo.tex, then foo.pdf is generated. In my case execution of :VimtexView would copy foo.pdf to foo_vimtex.pdf and then the viewer would update.

It would be nice if foo.pdf would get copied automatically to foo_vimtex.pdf immediately after compilation is finished. Is this supposed to happen already? Am I missing something?

**Comment by lervag** [comment]
Please ensure that you are using the latest version. I made some updates today that fixed some bugs. I think it should work properly now.

**Comment by heiderich** [comment]
I am on commit 4e7fd6e04b89223baafecd11856ea23930ad2702.

**Comment by lervag** [comment]
`foo_vimtex.pdf` should be generated after compilation, as long as `foo.pdf` exists and is newer than `foo_vimtex.pdf`.

**Comment by lervag** [comment]
Hmm. In order for this to work, you need the callback features running. I.e., `g:vimtex_latexmk_callback = 1`.

**Comment by heiderich** [comment]
I have g:vimtex_latexmk_callback = 1, which seems to be the default.
I monitored foo_vimtex.pdf and foo.pdf. Again, after compilation foo.pdf is usually newer than foo_vimtex.pdf until I call :VimtexView, when they coincide again.

Is there anything special required in the latexmk configuration?

How can I debug this issue?

**Comment by lervag** [comment]
I've changed the implementation. Please use `g:vimtex_view_use_temp_files = 1` to enable it. It should now also work for `mupdf` and general viewers. Although, for general viewers, it won't automatically update or start the viewer unless you define a callback yourself.

I propose that you test it. If it doesn't work as you expect, please open a new issue where you explain what is wrong. Please also attach a minimal example, in particular a minimal vimrc file (see the issue template for an example).

**Comment by heiderich** [comment]
It turned out that I used vim without the clientserver feature. I used it in a terminal and was not aware of the fact that I have to activate this feature (sorry, I did not read that part of the manual).

Now it works. I really appreciate that feature. Thanks a lot!

**Comment by lervag** [comment]
No problem! I actually agree that this is a very nice feature, and I will probably use it myself. So I'm also grateful. :)
