### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#444]
There seems to be an issue with syntax highlighting in situations like the following:

```tex
\begin{lem}[{\cite[Theorem 90]{Hilbert:Zahlbericht}}]
	
\end{lem}
```

This renders as follows in gvim:

![screenshot from 2016-04-26 15-07-10](https://cloud.githubusercontent.com/assets/3432497/14819194/3dea353e-0bc1-11e6-81d0-eb5c12c7ac8e.png)

I would not expect the closing brace and bracket to be highlighted in red.

**Comment by lervag** [comment]
This is not an issue with vimtex, it is an issue with the internal syntax plugin. See `:h vimtex-comment-internal`. I think the problem may be solved with `let g:tex_no_error = 1` in your vimrc file, see `:h tex-error`.
