### ISSUE TITLE
Lag in large documents due to tikz indent

### ISSUE THREAD

**Issue by miseran** [lervag/vimtex#446]
I'm getting significant lag when working on larger documents (a few thousand lines). Opening a new line, a new brace etc. freezes neovim for half a second. It gets worse the farther down in the document I am, at the top there is practically no lag. I was able to track down the cause to indentation, in particular the part dealing with tikz. Commenting out the line

    let l:ind += s:indent_tikz(l:nprev, l:prev)

removes the lag.

**Comment by lervag** [comment]
I'm aware of this. Thanks for pushing me to fixing it, though. I think the latest commit should work well.
