### ISSUE TITLE
Quickfix window does not appear for warnings

### ISSUE THREAD

**Issue by stampho** [lervag/vimtex#447]
Quickfix window works for latex errors only. If there is an error in latex it also shows the warnings. If there are warnings only the Quickfix window doesn't appear. Opening the window explicitly by the :VimtexErrors command does not help. I can reproduce the problem with MacVim.

The problem occurs since the following commit: https://github.com/lervag/vimtex/commit/12a0f00603f1d34124fc73b74a16f9b81d55bc3b
Reverting the commit solves the problem.

**Comment by lervag** [comment]
Strange, I can't seem to reproduce this. Can you give me a simple/minimal tex file where this happens? Even better, include a minimal vimrc file (as suggested in the issue template).

**Comment by stampho** [comment]
Here is a small latex example that should produce overfull warning:
```
\documentclass[12pt]{report}

\usepackage{times}
\textwidth 150mm

\begin{document}

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

\end{document}
```
Here is my reduced .vimrc:
```
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'lervag/vimtex'

call vundle#end()
filetype plugin indent on

syntax on

" Latex
let g:tex_flavor = "latex"
set iskeyword+=:
set grepprg=grep\ -nH\ $*

let g:vimtex_latexmk_options ="-pdf -verbose -file-line-error -synctex=1 -interaction=nonstopmode"

let g:vimtex_view_enabled = 1
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
" This adds a callback hook that updates Skim after compilation
let g:vimtex_latexmk_callback_hooks = ['UpdateSkim']
function! UpdateSkim(status)
  " copied from documentation ...
endfunction

let g:vimtex_quickfix_ignore_all_warnings = 0
"let g:vimtex_quickfix_ignored_warnings = [
"    \ 'Underfull',
"    \ ]
```

With this configuration I can reproduce the problem. Here is an extra information that I've just found: when starting macvim from console (eg. `mvim example.tex`) quickfix window works. Starting macvim from spotlight it doesn't.

**Comment by lervag** [comment]
Strange. I've reduced your minimal vimrc file to this:

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
filetype plugin indent on
syntax on

let g:tex_flavor = "latex"
set iskeyword+=:
set grepprg=grep\ -nH\ $*
let g:vimtex_latexmk_options ="-pdf -verbose -file-line-error -synctex=1 -interaction=nonstopmode"
let g:vimtex_quickfix_ignore_all_warnings = 0
```

Then I do: `gvim -u minivimrc test.tex`, where `test.tex` is a file with the content you suggested. When I do `\ll`, I get the expected warnings in a quickfix window.

**Comment by lervag** [comment]
It also works with `vim`.

**Comment by lervag** [comment]
I don't know what the difference is between macvim from console and macvim from spotlight. Perhaps the environment? You could compare `:!env` from both versions. You could also compare `:version` and check if both versions include the same features.

**Comment by stampho** [comment]
The versions are the same. There are differences between envs. Console version uses the following variables, spotlight version doesn't:
```
TERM_PROGRAM=iTerm.app
COMMAND_MODE=unix2003
ITERM_PROFILE=Default
ITERM_SESSION_ID=w6t0p0
LC_CTYPE=UTF-8
SECURITYSESSIONID=186a6
```

Both version uses SHLVL variables but the value differs:
spotlight: SHLVL=1
console: SHLVL=2

Does any of them seem relevant?

**Comment by stampho** [comment]
I also tried your version of the minimal vimrc. I could reproduce the problem with it. Moreover, I can reproduce the problem with vim too. Its version is different than mvim:
```
:version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Apr 26 2016 22:13:34)
MacOS X (unix) version
Included patches: 1-1755
Compiled by Homebrew
```
However, I suppose the problem must be different because the same workaround (reverting the mentioned commit) doesn't work for vim.

**Comment by lervag** [comment]
Ok. Could you try to debug this problem on your own? I'll try to help, of course. I suggest doing the following:

With macvim, open the test file where the problem is reproducible. Then do `:debug VimtexErrors`. This will start vims debug mode, which allows you to step through code as it is executed.  See `:h debug` and `:h >cont` for info about how to work with the debug mode. I propose that you step through until you return to normal with `step`. This should allow you to see exactly which parts of the code that is executed, and if you use this to investigate, you might be able to get some understanding about what happens. I suggest that you also keep the relevant vimtex file open: `autoload/vimtex/latexmk.vim`, see `vimtex#latexmk#errors()`.

**Comment by stampho** [comment]
I did some debugging and found the exact problem. There must be a bug in s:fix_quickfix_paths() function. The following line produce wrong result:
```
let l:file = fnamemodify(simplify(s:root . '/' . bufname(l:qf.bufnr)),
```

I expect l:file variable hold "/Users/stampho/tmp/vimtex-bug/example.tex" or something similar that is relative from "/Users/stampho". The home directory is the working directory for macvim when I start it from spotlight. I verbosed how the l:file variable is built:
```
[l:file] tmp/vimtex-bug/tmp/vimtex-bug/example.tex
[s:root] /Users/stampho/tmp/vimtex-bug
[l:qf.bufnr] 0
[bufname] tmp/vimtex-bug/example.tex 
```
The path "tmp/vimtex-bug/tmp/vimtex-bug/example.tex" is definitely wrong.

This anomaly also explains why macvim works from console. I started the macvim from the directory of the tex file thus the relative path would have been correct. As a workaround I tried to cd to the working directory when I started macvim from spotlight. This way the quickfix window shows the warnings as expected.

**Comment by lervag** [comment]
Thanks! This is very helpful, and now I can also reproduce. I'll try to find a solution asap.

**Comment by lervag** [comment]
Just for future reference: This issue is somewhat related to #421.

**Comment by lervag** [comment]
Ok, I think the latest patch solves this. Please test. If not, please provide a new minimal example with steps to reproduce.

**Comment by stampho** [comment]
I've tested the fix. It works. Thanks.

**Comment by lervag** [comment]
Great, happy to hear it!

**Comment by lervag** [comment]
Oh, and thanks for noticing and reporting!
