### ISSUE TITLE
Skim not launching on compile

### ISSUE THREAD

**Issue by alecshaw** [lervag/vimtex#448]
I recently reinstalled Vim and MacVim with Homebrew and in the process seem to have broken something in vimtex's ability to launch Skim PDF, or to notice certain changes after a compilation. I've looked through past issues and can't resolve the problem myself.

I'm using this MWE:
```
\documentclass{article}
\usepackage{lipsum}
\begin{document}
\lipsum[1]
\end{document}
```

The compilation is said to be successful. I am wondering if there is some kind of issue with `$success_cmd` and `$failure_cmd` now.

```
:!cd '/Users/alecshaw/Desktop/mwe' && max_print_line=2000 latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -e '$success_cmd = "'""'/usr/local/Cellar/macvim/7.4-
101/MacVim.app/Contents/MacOS/Vim'""' --servername VIM --remote-expr \"vimtex#latexmk#callback(1)\""' -e '$failure_cmd = "'""'/usr/local/Cellar/macvim/7.4-101/MacVim.app/Contents/MacOS/Vim'""' --servername VIM --remote-expr \"vimtex#latexmk#callback(0)\""' -e '$pdf_previewer = "/Applications/Skim.app/Contents/SharedSupport/displayline"' 'mwe.tex'
Latexmk: This is Latexmk, John Collins, 24 February 2016, version: 4.44.
Latexmk: All targets (mwe.pdf) are up-to-date
latexmk compile: success
```

`:VimtexView` also does nothing.

Here are what I believe to be the relevant settings in my `.vimrc` file:
```
execute pathogen#infect()
filetype plugin indent on
syntax on
set encoding=utf-8
set noswapfile
set nocompatible

" Vimtex
" ------
let g:tex_flavor='latex'
let g:vimtex_latexmk_continuous=0
let g:vimtex_quickfix_ignored_warnings=[
  \ 'Underfull',
  \ 'Overfull',
  \ 'specifier changed to',
\]
let g:vimtex_view_general_viewer
  \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options='-r @line @pdf @tex'
" This adds a callback hook that updates Skim after compilation
let g:vimtex_latexmk_callback_hooks=['Update Skim']
function! UpdateSkim(status)
  if !a:status | return | endif
  let l:out=b:vimtex.out()
  let l:cmd=[g:vimtex_view_general_viewer, '-r']
  if !empty(system('pgrep Skim'))
    call extend(l:cmd, ['-g'])
  endif
  if has('nvim')
    call jobstart(l:cmd + [line('.'), l:out])
  elseif has ('job)
    call job_start(l:cmd + [line('.'), l:out])
  else
    call system(join(l:cmd + [line('.'), shellescape(l:out)], ' '))
  endif
endfunction
```

Please let me know if I've left something out that would help, and thanks for any help.

**Comment by lervag** [comment]
If I understand correctly, things worked earlier, but stopped working after you reinstalled Vim. Do you also imply that you have updated vimtex?

Can you open Skim through the command line with the viewer command?

Do you see any errors in the latexmk output (see `<localleader>lo` after you have started compilation).

I don't use OSX myself, and it is difficult to know what the problem is, but I'll try to help as best I can.

**Comment by lervag** [comment]
I'm closing this due to no response. Feel free to reopen if/when you have some more info.
