### ISSUE TITLE
imaps not working (wrap_math)

### ISSUE THREAD

**Issue by Miesco** [lervag/vimtex#449]
### Explain the issue

Most issues are related to bugs or problems. In these cases, you should include
a minimal working example and a minimal vimrc file (see below), as well as:

1. Steps to reproduce

      `:echo vimtex#imaps#wrap_math('p', '\pi')`

2. Expected behaviour

      `\pi`

3. Observed behaviour

      `p`

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
EMPTY
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

```

### Setup

I have vim 7.4 and it should be the latest version of vimtex.  I use debian
linux.

**Comment by lervag** [comment]
I don't really understand what the problem is. Why do you call the `wrap_math` function explicitly/manually? It is supposed to be used as a wrapper for the imaps.

Could you explain why this is an issue. What do you want to do, what do you expect, what happens?

**Comment by Miesco** [comment]
Oh I see, I was trying to use the bindings outside of math mode.  My bad.

**Comment by lervag** [comment]
Yes, I suspected as much. No problem!
