### ISSUE TITLE
Deoplete omni pattern

### ISSUE THREAD

**Issue by DelusionalLogic** [lervag/vimtex#453]
I just wanted to post the pattern compatible with [Shougo/deoplete.nvim](https://github.com/Shougo/deoplete.nvim) in case anyone else needs it. You might also consider adding it to the readme.

The pattern is practically the same as for neocomplete, except that deoplete wraps your pattern in ```\%(\)``` since you enter very magic mode the mast ```\)``` in seen as a literal ```)``` and wont close the opening ```\%(```. A simple fix is to return to magic mode before ending the pattern.

Other than that the variable name is different, but that's trivial:

    if !exists('g:deoplete#omni_patterns')
	    let g:deoplete#omni_patterns = {}
    endif
    let g:deoplete#omni_patterns.tex =
    			\ '\v\\%('
    			\ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
    			\ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
    			\ . '|hyperref\s*\[[^]]*'
    			\ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
    			\ . '|%(include%(only)?|input)\s*\{[^}]*'
    			\ . ')\m'

**Comment by lervag** [comment]
Thanks!

**Comment by kiryph** [comment]
I want to add a note from deoplete documentation (https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L506-508)

> ```
> omni							*deoplete-source-omni*
> 		This source collects keywords from 'omnifunc'.
> 		Note: It is not asynchronous.
> ```

Compare to [jedi-vim](https://github.com/davidhalter/jedi-vim) vs [deoplete-jedi](https://github.com/zchee/deoplete-jedi). The difference explained by Shougo

> jedi-vim is synchronous, but deoplete-jedi is asynchronous. deoplete-jedi does not block your neovim.

https://www.reddit.com/r/neovim/comments/4973ls/deoplete_does_not_autocomplete_classes/d0so7u7

To get a faster auto-completion with deoplete, a non-omni source must be provided.

**Comment by lervag** [comment]
Interesting. How do I know if `g:deoplete#omni#input_patterns` can be used with vimtex? @kiryph Have you tested, can you suggest an update to the vimtex docs?

**Comment by DelusionalLogic** [comment]
I just tested it by reducing the rule to only ```\cite{```. My omni rule looks like this: ```let g:deoplete#omni#input_patterns.tex = '\\cite\{[^}]*'``` It seems to work fine, and it no longer causes a hang for a large document. I suspect that adding more regex wouldn't create any additional issues. I'll try rewrite the last part into the regex and post it here.

**Comment by DelusionalLogic** [comment]
So, i went ahead an rewrote all the regexes into python3 syntax. It wasn't really as hard as i thought it was. It seems to work just like omni_patterns, so maybe you can include it, although you would have to maintain another regex language.

    if !exists('g:deoplete#omni#input_patterns')
        let g:deoplete#omni#input_patterns = {}
    endif
    let g:deoplete#omni#input_patterns.tex = 
            \   '\\(?:'
            \  .   '\w*cite\w*(?:\s*\[[^]]*\]){0,2}\s*{[^}]*'
            \  .  '|\w*ref(?:\s*\{[^}]*|range\s*\{[^,}]*(?:}{)?)'
            \  .  '|hyperref\s*\[[^]]*'
            \  .  '|includegraphics\*?(?:\s*\[[^]]*\]){0,2}\s*\{[^}]*'
            \  .  '|(?:include(?:only)?|input)\s*\{[^}]*'
            \  .'|)'

**Comment by lervag** [comment]
Ok, thanks. It lacks some of the patterns, though. I think my suggestion should work. Please see the updated docs.
