### ISSUE TITLE
Autocompletion of environments

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#457]
Following issue #174. There was an idea to have a list of environments to complete from. It isn't so usable for example in mathematical texts because there are many custom environments like `theorem`, `proof`, `proposition`, `definition`, `corollary` and etc.

It would be great to scan current `.tex` file and create list of environments based on that scan. And may be add items to that list when creating some new environment or in manual mode...

**Comment by lervag** [comment]
Just to be clear, you are talking about completion candidates for input completion for the `cse` command, right?

I think your suggestion to parse the current `.tex` file (or perhaps the entire project, not just the current file) could be viable. I'll look at it.

**Comment by petRUShka** [comment]
Yes, that is exactly what I mean. 26.05.2016, 10:00, "Karl Yngve Lervåg" <notifications@github.com>:Just to be clear, you are talking about completion candidates for input completion for the cse command, right?I think your suggestion to parse the current .tex file (or perhaps the entire project, not just the current file) could be viable. I'll look at it.—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by lervag** [comment]
I've pushed a first version of the feature. I am wondering what I should do with the old option, and I am also curious if the implementation is too slow for large files. Let me know what you think.

**Comment by petRUShka** [comment]
For not so big text (around 17 pages) it works perfectly! Thanks a lot! Should I close the issue?

**Comment by lervag** [comment]
We could close the issue, I guess. But I think it could be interesting to discuss whether we should adjust or remove the corresponding option, `g:vimtex_env_complete_list`. What do you think?

**Comment by petRUShka** [comment]
I've never used It actually (I always used default list and it wasn't good enough for me), so if you ask my opinion I propose to remove that option. I doubt that anyone has so many environments starts with one letter (or group of letters) that it force him to limit them by means of that list.

**Comment by lervag** [comment]
I'm thinking similarly. Thanks!
