### ISSUE TITLE
No compilation on write

### ISSUE THREAD

**Issue by imantdaunhawer** [lervag/vimtex#458]
Hey there,

trying to get vimtex up and running on OSX using Skim, I am stuck with the question why my files do not compile on `:w`. 
After opening a file I type `<leader>ll` which starts the continuous mode and opens Skim as expected. Yet, when I make some changes and save the file, Skim does not automatically display them, but only after `:w` and `<leader>lv`. 

I have searched through the documentation and earlier issues (#204 in particular), which made me expect vimtex to compile and refresh the pdf, but I could not find a solution.

Heres a minimal .vimrc:
```vim
set nocompatible
filetype plugin indent on
syntax enable

" Vimtex options
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
let g:vimtex_view_general_options_latexmk = '-r 1'
```
And the (complete) .latexmkrc setup:
`$pdflatex = 'pdflatex -synctex=1 %O %S';
`

Since I'm just starting out with vim I hope my question is not completely trivial. I'd greatly appreciate to receive your suggestions and to learn more about vim!

**Comment by lervag** [comment]
I don't have any firsthand experience with Skim. My first thought is that perhaps Skim does not autoupdate when the pdf changes. After you have saved changes, do you get a "status report" similar to "latexmk compile: success" or "latexmk comile: failed"? If you do, then this implies that `latexmk` is running appropriately. If not, then I think the error is with `latexmk`.

Could you do this:

1. Open a file and start compilation with `<leader>ll`
2. Wait for Skim to open and preferably a status message "latexmk compile: success" (if it shows at all)
3. Report the output from `<leader>lo`
4. Report the output from `<leader>li`

**Comment by imantdaunhawer** [comment]
Thank you for answering so quickly! 

You were right, the problem did not lie within vimtex, but in the synchronisation of the teX-file. I simply had to change the Skim setup as follows:
<img width="482" alt="screen shot 2016-05-26 at 14 56 20" src="https://cloud.githubusercontent.com/assets/13051028/15575237/0b91cafe-2352-11e6-9fea-745b2cdb8a58.png">
By default Skim's synchronisation was disabled. Simple as that. 

Thank you for leading me on the right track and helping me out. Keep up the great work!

**Comment by lervag** [comment]
No problem. I'm happy the problem was easily fixed.
