### ISSUE TITLE
lag when typing (presumable because of folding)

### ISSUE THREAD

**Issue by pvater** [lervag/vimtex#459]
(i have tested this with a minimal vimrc, only consisting of the code to include vimtex, and the vimtex option "let g:vimtex_fold_enabled = 1")

in certain areas of the text it lags when i type. a "minimal" example of where this happens:

	\documentclass{article}
	\begin{document}
	It is easy to see that $\mathbb R_{\scriptscriptstyle\leq 0}^d\subset O^\circ$, which is of course full dimensional (in the sense that it contains some full dimensional polyhedron, if you will), and therefore so is $D^\circ$.
	
	\end{document}

(i left the original text because it seems to have something to do with how it is layed out; if for example i split the line in multiple smaller lines, or remove the first math code part, the problem disappears).

if i type on the line after the long sentence, there is very notable lag. if i type anywhere else there isn't. also this only happens with the above fold option of vimtex enabled.

this happens in both gvim and terminal vim.

**Comment by lervag** [comment]
Have you read the documentation? I've clearly noted that `expr` folding is slow, see `:h vimtex-folding`. See the note towards the end of the help section. I propose two solutions:

1. Use @Konfekt's [FastFold plugin](https://github.com/Konfekt/FastFold), or
2. Enable `g:vimtex_fold_manual` (and read about it in the docs)

Let me know if I have misunderstood anything, and feel free to reopen if you think this is not an appropriate solution.
