### ISSUE TITLE
Hide preamble in TOC

### ISSUE THREAD

**Issue by petobens** [lervag/vimtex#46]
I understand that the TOC is just a means of navigation so it might be useful to have an entry for the "Preamble". Personally I like the TOC to reflect what eventually gets printed. So, is it possible to add a variable that controls whether the preamble is shown or hidden in the TOC? Something similar to `g:latex_toc_hide_preamble`?. 
Thank you!

**Comment by petobens** [comment]
Hi @lervag. I'm revisiting this after 9 years :) . I tried setting `vim.g.vimtex_toc_show_preamble = 0` as in the image below but the preamble is still shown. Any pointers? 

![Screenshot_2023-09-07_10:01:08](https://github.com/lervag/vimtex/assets/2583971/07d3087a-05a8-4d79-8d75-0b5176e0d9ff)

**Comment by lervag** [comment]
Interesting. That option should work. Can you open a new issue and describe your config in somewhat more detail?

**Comment by petobens** [comment]
Sure. See https://github.com/lervag/vimtex/issues/2787. Thanks!
