### ISSUE TITLE
indentition singularity in math environment

### ISSUE THREAD

**Issue by pvater** [lervag/vimtex#461]
it seems as soon as a line in some math environment like 'gather' or 'align' contains the string "\Righta" (e.g. in "\Rightarrow") it isn't indented (as all other lines are).

tested with minimal .vimrc (only including the vimtex plugin).

**Comment by lervag** [comment]
Here it seems it works as expected. Could you please provide a minimal example?

**Comment by pvater** [comment]
<minimal preamble>

    \begin{align}
      \Rightarrow
    \end{align}

if i do '==' on the "\Rightarrow" line, it indents to the same width as the code for the environment (align), e.g.:

    \begin{align}
    \Rightarrow
    \end{align}

doesn't happen if the line doesn't contain the string "\Righta"

**Comment by lervag** [comment]
Ok. I use the following LaTeX code:

```tex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{graphicx}

\begin{document}

\begin{align}
  \Rightarrow
\end{align}

\end{document}
```

I use a minimal vimrc file:

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
set sw=2
```

Then I do `vim -u minivimrc test.tex`, and `gg=G`, and the test file remains the same with correct indentation.

I believe the problem is not with vimtex, but rather with your configuration.

**Comment by pvater** [comment]
turns out i was using an older vimtex version, with the current it works fine. my bad. and thanks!

**Comment by lervag** [comment]
No problem. :)
