### ISSUE TITLE
TexCount: Count also characters (not only words)

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#464]
Some places for which you can apply paper do count characters instead of words. Please add related command in VimTex.

P.S. Citation from documentation of TexCount

> -char, -letter
>     Count letters instead of words. This count does not include spaces.

**Comment by lervag** [comment]
Please explain better what you mean. Currently we use `texcount -nosub -sub -merge FILE`. Are you saying that this is the wrong command?

**Comment by petRUShka** [comment]
It is perfect when you want to count words, but if you want to count letters (or characters) instead it is useless. I propose to add command for counting **letter**!

**Comment by lervag** [comment]
Implemented in 6e9dae11a46223271b1f3f30f1042ebd30582a7f, please test. Note that I changed the command name to `VimtexCountWords`. Seemed better to me.

**Comment by petRUShka** [comment]
It seems to work fine! Thanks again!

**Comment by lervag** [comment]
No problem. :)
