### ISSUE TITLE
Omni completion don't find proposition by number only theorem.

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#465]
I have preamble

```tex
\usepackage{amsmath, amsthm, amssymb} 
...
\newtheorem{theorem}{Theorem}
...
\newtheorem{proposition}{Proposition}
```

And I have several  labelled theorems and propositions (more than 3 in both cases) in my text. 

```tex
...
\begin{theorem}\label{th:third}
...
\end{theorem}
...
\begin{proposition}\label{prop:third}
...
\end{proposition}
...
```

When I try to use omni completion by using `ctrl-X-ctrl-O` in insert mode inside `\ref{3<CURSOR>}`, I see `Omni completion (^O^N^P) The only match`. And that match is theorem (not proposition, not corollary, not example). That is pretty annoying.

So one more time: I have more than 3 labelled theorem, more than 3 labelled proposition and more than 3 labelled corollary and examples. I can see all that labels in `Table of labels`. But when I try to complete number `3` in `ref` I see only one match: `theorem`.

```
~/.latexmkrc 
$pdflatex = 'pdflatex -synctex=1 %O %S';
```

```vim
...
let g:tex_flavor = "latex"
set iskeyword+=:

let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_ignored_warnings = [
    \ 'Package hyperref Warning: Token not allowed in a PDF string (Unicode)',
    \ 'Package babel Warning: No Cyrillic font encoding has been loaded so far',
  \ ]
let g:vimtex_quickfix_open_on_warning = 0

au Filetype tex
            \ set spell |
            \ set spelllang=ru,en
...
```

**Comment by lervag** [comment]
I think this is fixed now, please test.

**Comment by petRUShka** [comment]
That is working right now, thanks!

**Comment by lervag** [comment]
No problem, thanks for noticing and reporting!
