### ISSUE TITLE
Suggestion: auto install packages in file

### ISSUE THREAD

**Issue by danielbmarques** [lervag/vimtex#468]
I just updated to Tex Live 2016, and I don't like installing the whole MacTeX, so I use the basic version and install just the packages I need. Manually installing one by one is annoying, though, and I think it wouldn't be hard to have Vim do it for me.

First we'd need to find and capture the names of the packages used in the file with something like:

`/^\\usepackage\(\[.*\]\)\?{\(.*\)}$`

Then we'd just have to pass those packages to `tlmgr`:

`sudo tlmgr install package1 package2 package3`

So whenever I got an error like "File 'whatever.sty' not found" I'd just have to run something like `:VimtexInstallPackages` and all the packages in the current file would be installed.

It seems like it would be really easy to do this, but I'm new to vim and I still haven't figured out how to send the results captured in the regex pattern to `tlmgr`.

**Comment by lervag** [comment]
Nah, I don't want this as part of vimtex. It is probably not too hard. You could probably solve most of it with just doing `:g/\\usepackage`.

I strive to keep vimtex as simple as possible. This feature would not be used  by a lot of people, and if I were to implement it I should also implement it for Windows. That's not something I want to do. Also, it just doesn't feel like something that should be done by a Vim plugin.

**Comment by danielbmarques** [comment]
Alright then, thanks.
