### ISSUE TITLE
Can Vimtex complete the relative path?

### ISSUE THREAD

**Issue by chengs** [lervag/vimtex#469]
Hello

When I try to add a pdf in \includegraphics{}, it always completes only the file name instead of the relative path. Can Vimtex complete the relative path?

For example, if a file is under the path "./fig/aaa/bbb/ccc.pdf", when I type  \includegraphics{}, it always gives me back "ccc.pdf", while what I expect is "./fig/aaa/bbb/ccc.pdf".

I am using spf13-vim and Vimtex with the following ~/.vimrc.local file.
```
let g:vimtex_complete_img_use_tail = 0
if !exists('g:neocomplete#sources#omni#input_patterns')
  let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.tex =
      \ '\v\\%('
      \ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
      \ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
      \ . '|hyperref\s*\[[^]]*'
      \ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
      \ . '|%(include%(only)?|input)\s*\{[^}]*'
      \ . '|\a*(gls|Gls|GLS)(pl)?\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
      \ . '|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*'
      \ . '|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*'
      \ . ')'
```

**Comment by lervag** [comment]
Fixed now. Thanks for noticing and reporting.

**Comment by chengs** [comment]
Very efficient! 
Thanks for your response!

**Comment by chengs** [comment]
I think the fix is incomplete.
I am using neocomplete.

In my case, for example I have a file "./fig/aaa/bbb/ccc.pdf", 
(1) if I type "./fig", all candidates come up and I can select ccc.pdf;
(2) if I type "ccc", no candidates come up, while "./fig/aaa/bbb/ccc.pdf" came up on the previous version (of course only "ccc.pdf" is completed).

**Comment by chengs** [comment]
In the commit,
https://github.com/lervag/vimtex/commit/455fb3ff2c3dfe2c201e8a930bbbb8b6588ce923

'''
''word'' : v:val,
'''
Now the word var becomes the relative path instead of the filename, which probably makes regex matching unavailable.  

Maybe it is related to the mechanism of neocomplete.

**Comment by lervag** [comment]
No, @chengs. The fix is not wrong. If you want to complete full relative paths, then you _must_ start with the first letter, see `:h g:neocomplete#enable_fuzzy_completion`:

>		Note: The first letter must be matched.

Regexp matching is available. To use it, you must specify a regexp. E.g. if I type `\includegraphics{c*\.p<c-x><c-o>` then Vim completes `ccc.pdf` as expected (with the full relative path). However, this is independent of neocomplete!

**Comment by lervag** [comment]
The reason `ccc` would work in the previous version was _because_ it only (erroneously) completed the tail of the file name, not the entire relative path. Thus the old version would not match `./fig`, but it would match `ccc`.
