### ISSUE TITLE
Vimtex with YouCompleteMe makes backspacing terribly slow

### ISSUE THREAD

**Issue by danielbmarques** [lervag/vimtex#473]
I'm using Vimex with YouCompleteMe. When I'm at the end of a very large file, here's what happens when I hold down `<BS>`:

![slow](https://cloud.githubusercontent.com/assets/15813674/15987268/031f550e-2ff9-11e6-9c7f-9b389a586e88.gif)

If I comment out Vimtex from my vimrc, here's how it goes:

![fast](https://cloud.githubusercontent.com/assets/15813674/15987269/05f32936-2ff9-11e6-9ef2-1c59574330ee.gif)

Note that I start on line 478 in both cases. If I use the same file but try it at the top this problem doesn't happen.

I searched YCM's issues and found something similar: https://github.com/Valloric/YouCompleteMe/issues/1395

> It gets worse as the python files gets longer - at around line 250 it can take a second to type or backspace each character. If I type near the top of the file, the speed is slow but manageable. This only occurs in one of my python files, although I have had trouble locating the cause. 

It doesn't look like the problem is with YCM, though, since it works with other files and even with `tex` files without Vimtex (it shows my UltiSnips snippets and all).

I thought this could have something to do with the semantic triggers in 

    let g:ycm_semantic_triggers.tex = […]

But even if I remove all that, backspacing is still slow just for using Vimtex.

Any ideas?

**Comment by lervag** [comment]
I don't believe this happens with neocomplete, and I would think this does not happen with pure vimtex. Could you do a similar test where you comment out YouCompleteMe?

I think the reason this happens might be because YouCompleteMe asks for the completion candidates everytime you hit the backspace-key. However, I am not exactly sure, but I am pretty sure that the problem lies with YouCompleteMe...

**Comment by danielbmarques** [comment]
Right, it doesn't happen without YouCompleteMe, and I also think it must have something to do with it asking for completion candidates, that's why I tried removing the semantic triggers. But I think it's a problem with the specific interaction between YCM and Vimtex, since it doesn't happen with other filetypes. But I'll see about opening an issue in the YCM repository, then.

**Comment by danielbmarques** [comment]
Aha! The problem was with the folding methods.

I had set Vimtex to fold the preamble and some other stuff automatically. Now I tried neocomplete and it gave me a warning saying the `expr` folding method would make things slow. So I went back to YouCompleteMe and disabled Vimtex's folding, and now the problem's gone. 🎉 

I think it would be worth it to add a line in the folding documentation of Vimtex warning that it may cause problems with autocompleters.

**Comment by lervag** [comment]
Ah, there it is. I will consider to add such a line, but I've already clearly stated the the `expr` method of folding is slow, and I've suggested two alternative methods to fix this: use `g:vimtex_fold_manual`, or install `FastFold`. See `:h vimtex-folding` for details.
