### ISSUE TITLE
Fold Multiline Documentclass & Package Options

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#477]
Sometimes the number of options passed to the documentclass and packages become
quite long, so I write them in following style:
```
\documentclass[% Options of scrbook
  % draft,
  fontsize=12pt,
  %smallheadings,
  headings=big,
  english,
  paper=a4,
  twoside,
  open=right,
  DIV=14,
  BCOR=20mm,
  headinclude=false,
  footinclude=false,
  mpinclude=false,
  pagesize,
  titlepage,
  parskip=half,
  headsepline,
  chapterprefix=false,
  appendixprefix=Appendix,
  appendixwithprefixline=true,
  bibliography=totoc,
  toc=graduated,
  numbers=noenddot,
]{scrbook}

\usepackage[
  backend=biber,
  style=numeric-comp,
  maxcitenames=99,
  doi=false,
  url=false,
  giveninits=true,
]{biblatex}
```
I would like to fold them to the following:
```
\documentclass[...]{scrbook}

\usepackage[...]{biblatex}
```

Would it be possible to extend the folding method together with following vimtex-options `g:vimtex_fold_mulitline_documentclass_options` and `g:vimtex_fold_multiline_package_options`?

**Comment by lervag** [comment]
Yes, this should be possible. I agree this could be convenient. I'll look into it when I get the time.

**Comment by lervag** [comment]
Actually, folding documentclass opens some questions. How do we combine this with folding of the entire preamble? What should the fold text be? Preamble folding is started with the documentclass line, which thus conflicts with this new feature...

I've pushed an update that folds usepackages as you suggest. Please test if it works as expected. Should we make this optional? If so, what is the sensible default value?

**Comment by kiryph** [comment]
Thanks for your update.

1. Regarding folding of package options.

  I had to change the following to make it work
  ```diff
diff --git a/autoload/vimtex/fold.vim b/autoload/vimtex/fold.vim
index 097fe49..d2b78bc 100644
--- a/autoload/vimtex/fold.vim
+++ b/autoload/vimtex/fold.vim
@@ -143,7 +143,7 @@ function! vimtex#fold#level(lnum) " {{{1
   if line =~# '^\s*\\usepackage\s*\[\s*\%($\|%\)'
     let s:usepackage = 1
     return 'a1'
-  elseif get(s:, 'start', 0) && line =~# '^\s*\]{'
+  elseif line =~# '^\s*\]{'
     let s:usepackage = 0
     return 's1'
   endif
```
  I could not figure out the meaning of `s:start`. Can you tell me what the variable `s:start` is for?

  If everything which can be folded has an option for folding it, it would be consistent to add an option for folding options of packages as well.

  I would turn it on by default. There are not too many levels of folding anyhow.

2. Regarding folding of documentclass options.

  I am writing right now a thesis. I have put the preamble in a separate file. So folding for me the whole preamble is not what I want. I turn off folding of the preamble, but would turn on an option for folding documentclass options. Of course a user could not turn on both.
  
  What do you think? Is this a possible way to provide this feature?

**Comment by lervag** [comment]
Sorry, I pushed a minor bug. Should be fixed now. I've also added an option for usepackage folding.

I could add a similar option for documentclass, which would by default be 0. I can add a check and a warning if both preamble and documentclass folding is turned on, and then fallback to the default preamble folding in this case. How does that sound?

**Comment by kiryph** [comment]
Yes, this sounds good for me.

And the usepackage options folding  works now.

Remark about syntax highlighting of foldtext:
Afaik, vim cannot apply syntax highlighing to folded text.

See e.g. discussion on vim_dev mailing list https://groups.google.com/forum/#!topic/vim_dev/_T6K5B4Bm4s.
The suggestion by Ingo Karkat does sound good enough:

> it would already be helpful if highlighting of folded text could be transparent, so that the
> original syntax definitions would apply.

**Comment by lervag** [comment]
Great, I'll update for documentclass when I get the time.

I don't understand the point of the remark about highlighting. Do you suggest a change to vimtex? As far as I can understand, it is not possible to highlight folded text except through the Folded highlight group.

**Comment by kiryph** [comment]
No, I do not suggest a change to vimtex. I just wanted to remind people who read this discussion that the syntax highlighting of the foldtext is not in agreement with the rest of the document. And this is actually not an issue of vimtex but vim itself and the question of adjusting it to match the rest of the document has been raised at least since 2009

![demo-folding-highliting](https://cloud.githubusercontent.com/assets/371756/16762129/7d990cac-4823-11e6-90e9-71cc06bf2849.png)
Vim only applies the folded highlight group but no syntax highlighting to the foldtext. My current colorscheme makes them look like comments which I personally do not like

**Comment by lervag** [comment]
Remains to add documentation.

**Comment by kiryph** [comment]
thanks for your commit. It works nicely with following options in my vimrc:

```
let g:vimtex_fold_preamble = 0
let g:vimtex_fold_documentclass = 1
```

**Comment by lervag** [comment]
Great! I've added documentation now. Thanks for the suggestion and feedback!
