### ISSUE TITLE
vimtex hightlighting 

### ISSUE THREAD

**Issue by diegodiazd** [lervag/vimtex#478]
Hi all,

Just a quick question about vimtex usage.  When I type, lets say, \textbf{some bold example} in vim, the behavior is to show something like **some bold example**, instead the latex command. Is there a way to disable this feature by .vimrc?, it's a little inconvenient to me.

Thanks in advance.

**Comment by Rmano** [comment]
This is `conceal` in action.
Use `set concealable=0` in your .vimrc.
HTH,
   Romano
On Jun 16, 2016 23:41, Diego Díaz Domínguez <notifications@github.com> wrote:Hi all,

Just a quick question about vimtex usage.  When I type, lets say, \textbf{some bold example} in vim, the behavior is to show something like some bolde example, instead the latex command. Is there a way to disable this feature by .vimrc?, it's a little inconvenient to me.

Thanks in advance.

**Comment by lervag** [comment]
As @Rmano writes, this is controlled by the `conceal` feature. And it is not really a part of vimtex, instead, it comes with the internal syntax plugin with Vim (upon which vimtex simply adds some sugar).

If you don't like the conceal feature, which I very much understand, then you should add

```vim
set conceallevel = 0
```

to your `.vimrc` file. Note that this will disable conceal for everything, not just for LaTeX files. You might also be interested in looking at `:h g:tex_conceal`, which allows you to control which LaTeX constructs are concealed, or `let g:tex_conceal = ''` (again in your `.vimrc` file) to disable conceal for LaTeX files specifically, without adjusting the `conceallevel` option.

**Comment by diegodiazd** [comment]
Thank you so much. I ended up using ```let g:tex_conceal = '' ``` and it worked perfectly

**Comment by lervag** [comment]
No problem! :)
