### ISSUE TITLE
Opening TOC on the right side

### ISSUE THREAD

**Issue by manasthakur** [lervag/vimtex#484]
Is there a way to open the TOC on the right side instead of left? I would like to always keep the TOC open (like TagBar), but keeping it on the left side obstructs my editing on a smaller laptop screen.

**Comment by lervag** [comment]
Yes, see `:h vimtex_index_split_pos`. Try to set it to `vert belowright`.

**Comment by CBroz1** [comment]
Future visitors to this issue may wish to see an updated example config at #2060

**Comment by lervag** [comment]
Yes; or to read from the docs on `:help g:vimtex_toc_config`. ;)
