### ISSUE TITLE
<plug>(vimtex-delim-close) doesn't close the document environment

### ISSUE THREAD

**Issue by matthewjohnrussell** [lervag/vimtex#485]
`<plug>(vimtex-delim-close)` is meant to close the current environment or command. However, I haven't been able to make it close the document environment.

Minimal example:

```tex
\documentclass{article}
\begin{document}
\<press ]] or call vimtex-delim-close\>
```

**Comment by lervag** [comment]
This is because the `document` environment is ignored. the reason is because it is very rarely needed for anything, and if it is not ignored, then it will interfere with other things.

**Comment by matthewjohnrussell** [comment]
OK - not a bit deal. I'll just close it manually! Thanks

**Comment by lervag** [comment]
No problem! :)
