### ISSUE TITLE
Allow using make instead of latexmk

### ISSUE THREAD

**Issue by anandtrex** [lervag/vimtex#488]
Feature request: It would be nice if vimtex allowed using make for compilation rather than latexmk. I currently have a non-standard build process for which I need a make-based build. This option could be disabled by default, and when enabled, just runs `make` in the current directory.

**Comment by lervag** [comment]
I don't feel like this needs to be part of vimtex. It is already handled well by Vim by default, see `:h :make`. Further, there are several plugins that give you improved handling of make builds, such as [vim-dispatch](https://github.com/tpope/vim-dispatch). I think you can use vimtex with e.g. vim-dispatch set up use a makefile, and it should solve your use case with no need to update vimtex.

**Comment by lervag** [comment]
Btw: you can remap the vimtex mappings, e.g. `\ll`.
