### ISSUE TITLE
Feauture request: auto completion of references by counter

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#489]
It would be nice if vimtex would also allow tab completion for labels by specifying numbers of counters. This is a feature of atp-vim (see http://atp-vim.sourceforge.net/automatic-tex-plugin.html):

> Tab Completion for labels (|atp-completion|) allows to specify the number of the counter, e.g.
> \ref{3.1<Tab>
> will complete into the label of the counter with value '3.1'. As for now you can not specify which counter to complete. You can also write '\ref{3.1$' then '^3.1$' is used as a pattern!
> 
> For this two work the aux file must be present. As for now the aux file, if it is not present, is not made.

So if you have

```
\begin{equation}
   \label{eqn:fermat}
   x^n + y^n = z^n
\end{equation}
```

which will have the counter 1 assigned, then, if writing \ref{1 and pressing tab, it would be replaced by \ref{eqn:fermat}.

There might be several counters with the same number. If so, I guess it would be convenient to be able to chose from a list of all of them.

**Comment by lervag** [comment]
This is already a feature, see `:h vimtex-complete-labels`.

**Comment by heiderich** [comment]
Sorry, I did not notice that. Thank you.

**Comment by lervag** [comment]
No problem :)
