### ISSUE TITLE
'Press any key to continue ...' when starting vim with 'filetype plugin indent on'

### ISSUE THREAD

**Issue by camilstaps** [lervag/vimtex#494]
Since 39fe7b51701df3cbfb8212bbeb9881b8a4f2ea0f, every time I start vim I get `Press any key to continue ...`. My .vimrc:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
```

Could you please have a look?

**Comment by lervag** [comment]
Hmm, that's strange. In the mentioned commit and one after it, I've added a `wait` function to make people confirm that they've read a warning message. That is, before `Press any key to continue ...` there should be a warning. Is there none?

What system are you on?

**Comment by camilstaps** [comment]
Thanks for the quick reply.

I tested a bit more and it seems we can distinguish three different cases:

* Opening vim normally: no problem
* Opening a new `*.tex` file: `vim nonexistent.tex`: `Press any key to continue ...` without warning
* Opening an existing `*.tex` file: `vimtex warning: Can't use callbacks without +clientserver`

This is on Debian 8 with Vim 7.4.

**Comment by lervag** [comment]
Interesting. I've tried to make an update that should make things clearer. The point of this is to make sure that people notice the warnings. In the case where the file does not exist, I now instead use a `sleep 1` to make the message last some time before it is cleared by Vim.

If you want to ignore the error, you can `let g:vimtex_echo_ignore_wait = 1`.

**Comment by camilstaps** [comment]
Yes, now it shows the warning in all cases. Thanks a lot.

(I also disabled the callbacks; vim on debian isn't compiled with `clientserver` and I don't want to compile it from source unless absolutely necessary - so I don't get any warnings any more.)

**Comment by lervag** [comment]
Great. I assume you understand that without the callbacks, you won't get status updates inside Vim after compiles. This should be the only drawback, and I would easily agree that this feature is not essential, only conveniant.
