### ISSUE TITLE
Imaps should escape '

### ISSUE THREAD

**Issue by ernestorenanche** [lervag/vimtex#495]
When I try to use imaps to map `'` to `\prime` in maths mode I got the following error messages

`E116: Invalid arguments for function vimtex#imaps#wrap_math(''', '\prime')`
` E15: Invalid expression: vimtex#imaps#wrap_math(''', '\prime')`

The relevant part of my `.vimrc` reads

`call vimtex#imaps#add_map({
      \ 'lhs': "'",
      \ 'rhs': '\prime',
      \})`

**Comment by lervag** [comment]
Thanks, I think this is fixed now.

**Comment by ernestorenanche** [comment]
Not really the combination `<localleader>'` keep on producing
`E116: Invalid arguments for function vimtex#imaps#wrap_math(''''', '\prime')`
`E15: Invalid expression: vimtex#imaps#wrap_math(''''', '\prime')`
but also now `<localleader>.` produces
`E116: Invalid arguments for function vimtex#imaps#wrap_math(''.', '\cdot')`
`E15: Invalid expression: vimtex#imaps#wrap_math(''.', '\cdot')`.
In fact all the imaps seem to be broken right now (also tried with `<localleader>l` for instance).

**Comment by lervag** [comment]
That's strange. Things work fine here.

You say `<localleader>`, but I assume you mean the imaps leader, which is by default set to `` ` ``. Note, though, that this is a setting for vimtex, and that it does not have anything to do with `<localleader>`.

Could you please provide a new minimal example, preferably with a minimal vimrc file?

**Comment by ernestorenanche** [comment]
I think I understand the problem.

Here what the relevant part of my `.vimrc` was
```
let mapleader=";"
let maplocalleader="'"
let g:vimtex_imaps_leader = "<localleader>"
```

and here is how I changed it to make it works properly

```
let mapleader="'"
let maplocalleader=";"
let g:vimtex_imaps_leader = "<localleader>"
```

I think the problem came from the fact that I used the same character as the `<localleader>` and the one which is used to delimit strings.

**Comment by lervag** [comment]
Still, when I tried with `let g:vimtex_imaps_leader = "'"`, it worked as expected. Are you sure you updated to the most recent version?

**Comment by ernestorenanche** [comment]
What you suggested indeed works fine but
```
let maplocalleader="'"
let g:vimtex_imaps_leader = "<localleader>"
```
still produces an error.

**Comment by lervag** [comment]
Should work now. Thanks! I never considered that one could use `<localleader>` as the vimtex imaps leader, and in this case I needed a different way of "escaping" the argument for the wrapper function.
