### ISSUE TITLE
Handling includefrom

### ISSUE THREAD

**Issue by MathInside** [lervag/vimtex#500]
Hi everyone,

vimtex is able to build a table of contents when `\input` or `\include` commands are used but not when `\includefrom` is used. `\includefrom` differs from `\include` by giving the path where figure are stored.

Here is a WME:

```tex
\documentclass{report}
\begin{document}
\includefrom{fig/fig_file1/}{tex/file1}  % not seen by vimtex
\include{tex/file1}  % ok
\end{document}
```

Here's my proposal in `autoload/vimtex/parser.vim`: 

- add `includefrom`:  

    ```vim
    let s:input_line_tex = '\v^\s*\\%(input|include|includefrom|subimport|subfile)\s*\{'
    ```

- handle `includefrom` like `subimport` by deleting the figure folder path:

    ```vim
    if a:line =~# '\\includefrom'                                                 
	let l:file = substitute(l:file, '{\(\h\|\/\|\d\)*}', '', '')                
    endif 
    ```

Do you think the regex used is enough (and could be add to the master branch)? It has worked in my MWE.

Thanks for your help.

**Comment by lervag** [comment]
Hi. Thanks, this seems useful. I'll add it, but I'm a littly bit unsure about the substitute line. Why is it not just the same as the one I've used for the `subimport`? That is, why can I not just do this:

```vim
  " Hande subimport and includefrom commands
  if a:line =~# '\v\\%(subimport|includefrom)'
    let l:file = substitute(l:file, '}\s*{', '', 'g')
  endif
```

**Comment by MathInside** [comment]
First parameter inside braces of \subimport gives the folder which contains the tex file. The second parameter is the name of the file to be imported. So you need to 'concatenate' both to get the tex file's path.

First parameter inside braces of \includefrom gives the folder which contains the images. The path to the tex file is defined in the second paramter. So you need to delete the first argument.

ex : 
```tex
\subimport{folder/}{file.tex}  % vimtex needs folder/file.tex
\includefrom{fig_folder/}{tex_folder/file.tex}  % vimtex needs tex_folder/file.tex
```

Besides, I think
```vim
    let l:file = substitute(l:file, '{[^}]*}', '', '')
```
is more robust than my previous proposition.

**Comment by lervag** [comment]
I've looked up [the documentation] for the import package, where it seems the `includefrom` command comes from, and to me it seems that the behaviour of `\includefrom` should be the same as the behaviour of the `\import` command, which takes an absolute path as the first argument, then the relative path as the second argument.

Could you please provide a good source for the `\includefrom` command that explains how it works?

**Comment by MathInside** [comment]
Yes you're right. I was using `\includefrom` in a tricky way.
In fact, I looked at `import.sty` and it seems the import package check if the 2nd argument given in `\import` / `\subimport` / `\includefrom` .... is a file. And if it exists, the first argument is not used to import the tex file but would be used for other calls to `\input` / `\includegraphics` ... inside the included file. So in my example the first argument is not used to import the tex file.
I don't think `\includefrom` is supposed to be used like that.

So `\import, \includefrom, \subincludefrom, \inputfrom, \subinputfrom` should all be handled like `\subimport` (`\inputfrom` and `\subinputfrom` are alias command names for `\import` and `\subimport)` :

```vim
" Handle import.sty commands
if a:line =~# '\v\\%(import|subimport|includefrom|subincludefrom|inputfrom|subinputfrom)'
    let l:file = substitute(l:file, '}\s*{', '', 'g')
endif
```

**Comment by lervag** [comment]
I see. That seems like a good explanation. Note, though, that this implementation is then based on the documented form of the import commands, and not on the form that you were using. I hope that will not be a problem.

**Comment by MathInside** [comment]
Thanks for your commit.

Do you think it would be pertinent to check if the 2nd argument given in import commands is a file, and if it is the case to not use the 1st argument ? The behaviour of the import package would be reproduced.

Something like : 
```vim
if a:line =~# '\\includefrom'                                                 
    let l:arg2 = substitute(l:file, '{[^}]*}', '', '') 
    if filereadable(l:arg2)
       let l:file = l:arg2
    else                          
        let l:file = substitute(l:file, '}\s*{', '', 'g')
endif                     
```

**Comment by lervag** [comment]
Thanks, that's a good suggestion. I did it in a slightly different way in order to utilize the existing code, but it seems to work well.
