### ISSUE TITLE
Donation...

### ISSUE THREAD

**Issue by amca01** [lervag/vimtex#501]
I don't know how to do this privately, but anyway since you were so helpful in sorting out my issue of vimtex not producing pdf files, when I'm sure you had better things to do, I've donated $50 to the vimtex project.  It's not much, but it'll keep you in cups of coffee for a few days coding!

cheers,
Alasdair

**Comment by lervag** [comment]
Wow, thanks! Very much appreciated; surely it will keep my mugs of coffee filled even for a couple of weeks! :)
