### ISSUE TITLE
Vimtex and SuperTab keyword completion doesn't work well

### ISSUE THREAD

**Issue by mfedoten** [lervag/vimtex#502]
Hi,

The problem is when I am trying to complete words which are not citation keys or labels, etc. by pressing TAB, I get an error. I am using SuperTab with "chaining" (similar to #37), so I expect it to fallback to "previous" keyword completion, if vimtex can't complete it. Here's an example to illustrate it. I am using MWE from `~/.vim/bundle/vimtex/test/issues/324` with slightly different vimrc.

### Minimal vimrc file

```vim
set nocompatible
filetype plugin indent on
syntax enable

set completeopt=menu,preview

let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp = '~/.vim/bundle/vimtex/after,' . &rtp
let &rtp = '~/.vim/bundle/supertab,' . &rtp

" SuperTab settings
let g:SuperTabDefaultCompletionType = "context"
let g:SuperTabCompletionContexts = ['s:ContextText','s:ContextDiscover']
let g:SuperTabContextDiscoverDiscovery = ["&completefunc:<c-x><c-u>", "&omnifunc:<c-x><c-o>"]
let g:SuperTabContextTextOmniPrecedence = ['&completefunc', '&omnifunc']
let g:SuperTabMappingBackward = "<c-tab>"
let g:SuperTabMappingTabLiteral = "<s-tab>"
let g:SuperTabLongestEnhanced = 1
let g:SuperTabCrMapping = 0
autocmd FileType * if &omnifunc != '' | call SuperTabChain(&omnifunc, "<c-p>") | endif
```
### Minimal working example

I run the following file with `vim -u vimrc minimal.tex`

```tex
\documentclass{minimal}
\begin{document}

\begin{equation}
    \label{eq:eq}
    x = y
\end{equation}

Hello World, behold eq.~\ref{eq:

\end{document}
```

When typing `\beg<Tab>` on  the third line, I expect keyword completion ending in `\begin`, instead I get the following error:

```
Error detected while processing function SuperTabCodeComplete..vimtex#complete#omnifunc:
line   24:
E121: Undefined variable: s:completer
Press ENTER or type command to continue
Error detected while processing function SuperTabCodeComplete..vimtex#complete#omnifunc:
line   24:
E116: Invalid arguments for function s:close_braces(s:completer.complete(a:base))
Press ENTER or type command to continue
Error detected while processing function SuperTabCodeComplete..vimtex#complete#omnifunc:
line   24:
E15: Invalid expression: s:close_braces(s:completer.complete(a:base))
-- User defined completion (^U^N^P) Pattern not found
```
However typing `\ref{eq:<TAB>` on line 9 results in `\ref{eq:eq` as expected.

### Workaround

By commenting out the last line in vimrc (with chaining behaviour) I can achieve keyword completion, however I have to type <TAB> twice (which is a bit annoying) and also `:set completefunc` shows empty complete function.

Just a side note, I used the same SuperTab configuration with LaTeX-Box and it worked fine. However, I'd like to switch to vimtex because it's faster and more vim-friendly. Thank you for your work, it's a great plugin.

**Comment by lervag** [comment]
I've fixed it. But I would claim that the bug is not really with vimtex, but with supertab, which calls the completefunc again even when the first call says that it should not complete. In any case, it should work now.

**Comment by mfedoten** [comment]
Thanks a lot! It works perfectly now.

**Comment by lervag** [comment]
Great! :)
