### ISSUE TITLE
Even more smart autocompletion for eqrefs

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#503]
Suppose I have **lemma** 2 and **equation** which is labeled with 2 in my document. And suppose I've written down `\eqref{2`. After `ctrl-X-ctrl-O` I expect only equation to show up, but I also see lemma:

![2016-07-27-163521_428x71_scrot](https://cloud.githubusercontent.com/assets/146893/17177132/fef37644-5420-11e6-9465-8e8bba2303ec.png)

which is inconvinient and I doubt that anyone is ever needed in lemmas in `\eqref`.

**Comment by lervag** [comment]
I think the latest version should handle this in a good way. :)
