### ISSUE TITLE
Help message in table of labels is highlighted as VimtexLabelsLine

### ISSUE THREAD

**Issue by mfedoten** [lervag/vimtex#506]
This is very-very minor issue. Still thought I mention it.

If you ran any minimal example containing labels with `syntax enable` and open table of labels, you can notice that help message is highlighted as `VimtexLabelsLine` and not as `VimtexLabelsHelp` (see screenshots).

It can be fixed by placing line 126 in `vimtex/autoload/vimtex/labels.vim` after definitions of other highlight groups, as it was done in ToC.

![screen shot 2016-07-29 at 19 05 49](https://cloud.githubusercontent.com/assets/13535512/17257052/9215b8ba-55c0-11e6-91fd-7239409e6e58.png)

![screen shot 2016-07-29 at 19 06 24](https://cloud.githubusercontent.com/assets/13535512/17257051/9210eb6e-55c0-11e6-94ae-20f9dd33fe35.png)

**Comment by lervag** [comment]
Thanks!
