### ISSUE TITLE
Include Cygwin "support"

### ISSUE THREAD

**Issue by dutchgecko** [lervag/vimtex#509]
### Explain the issue

Similar to plain windows, cygwin doesn't offer any good ways of getting process IDs. Because it also doesn't offer a `pgrep` binary, I get the following in vim when opening a Tex  file:

```
vimtex warning: pgrep is not executable
- vimtex#latexmk was not initialized!
```

I would suggest disabling the latexmk server support  for cygwin as you currently do for windows.

Note: whether vim is running on cygwin or not can be detected with `has('win32unix')`

**Comment by lervag** [comment]
I am not quite sure I understand what you mean. Are you suggestion that for Cygwin (`has('win32unix')`), I disable the entire latexmk support? Or are you suggestion that I disable the warning?

And what do you mean by "latexmk server support"? Are you talking about the ability to start and stop continuous compilation, or the ability to get callbacks with status updates and automatic opening of errors?

**Comment by lervag** [comment]
I suggest instead that you turn off the callback feature and continuous compilation, i.e.

```vim
let g:vimtex_latexmk_callback = 0
let g:vimtex_latexmk_continuous = 0
```

This should remove the warning, as `pgrep` will not be necessary. Note, you need the latest version for this to work, as I needed to fix some minor issues.
