### ISSUE TITLE
Weird errors using gq

### ISSUE THREAD

**Issue by danielbmarques** [lervag/vimtex#512]
I have been trying to reproduce the errors I mentioned with the custom `formatexpr` and `neocomplete`.

I stripped my `.vimrc` down to this:

```vim
call plug#begin('~/.vim/bundle')

    Plug 'Shougo/neocomplete.vim'
    Plug 'lervag/vimtex'

call plug#end()

let g:vimtex_format_enabled = 1
let g:neocomplete#enable_at_startup = 1
let g:tex_flavor = "latex"
```

Then I just open a file I was already working on and do `gqip` on the first paragraph. I get the errors I mentioned before:

```
Error detected while processing function <SNR>89_complete_delay[3]..<SNR>89_do_auto_complete[12]..neocomplete#context_filetype#set:
line    2:
E117: Unknown function: context_filetype#get_filetype
E15: Invalid expression: s:exists_context_filetype ? context_filetype#get_filetype() : &filetype  
```

This only happens if `gqip` is the first thing I do. If I edit the text and add a single character and then do `<esc>gqip` it works fine.

Now that's on the file I was already working on. To isolate the problem I tried to create a different file so I could send it to you.

This was my first attempt:

[whatever.txt](https://github.com/lervag/vimtex/files/403096/whatever.txt)
(Rename the extension to `.tex`.)

Now using this file if I open it and do `gqip` right away I get those errors most of the time (there were a couple of times when it didn't happen, I don't know why.

But using this file if I do something like `whatever<esc>gqip`, I get this:

"vimtex warning: Formatting of selected text failed!"

And I can't use `gq` at all, all I get is that error.

I don't know why I get this error with this file and not with the one I had before.

So, anyway, it seems I have two problems again. The one with `neocomplete`, which I don't know if you'll be able to reproduce, but I don't know how to make an even more minimal exemple… and then this one with that "Vimtex warning", which happens regardless of `neocomplete`, but not with every file. I don't know what this file has in particular that causes this.

**Comment by lervag** [comment]
Ok, I've fixed this now. But I had to remove a pretty nice utility feature that saves the undo position. That is, with the last change, you will not return to the same position in the file when you do `gqip` then `u`. I couldn't find a different way of doing this, so I decided it was best to avoid the neocomplete error.

**Comment by danielbmarques** [comment]
Awesome, thank you!

**Comment by lervag** [comment]
No problem. I might try to solve the issue with undo position when I get the time, but I am not sure if I will be able. Perhaps I'll open an issue with Shougo for neocomplete, as I think the issue must be on his side, not mine...

**Comment by danielbmarques** [comment]
I think that feature was also causing those "vimtex warning: Formatting of selected text failed!" errors, though. At least they were happening here even without neocomplete, and now they're gone. 

Keeping the undo position would be nice, but it's not essential I think, even more considering that it's just Vim's regular behavior.

**Comment by lervag** [comment]
No. That warning was fixed with 665c895. The warning was not related to neocomplete, but was due to a bug. :)

**Comment by danielbmarques** [comment]
Ah! Alright then.

Now if that undo feature works I'll want to use your `formatexpr` for other filetypes too, it's really great. :)

If you're ever bored and want to make it even better, you could try to make the lines as close as possible in length, like `par` does.

For instance, here's the text I'm writing right now with `formatprg=par`:

![captura de tela 2016-08-05 as 04 45 08](https://cloud.githubusercontent.com/assets/15813674/17429938/d6a9d090-5ac7-11e6-95cb-563a89406324.png)

And here's the same paragraph with your `formatexpr`:

![captura de tela 2016-08-05 as 04 52 50](https://cloud.githubusercontent.com/assets/15813674/17430050/8405760e-5ac8-11e6-9143-c5d496de7b3d.png)


`par` makes the edges a lot less ragged. I have no idea how hard it would be to do this and it really doesn't make that much of a difference, I'm just being super picky, but I thought I'd put the idea out there.

**Comment by lervag** [comment]
I think it becomes a pretty hard problem, actually, because I would need to minimize an object function (e.g. standard deviation of line lengths). I agree that it would be nice, but I think I'll pass on that. I have too many other activities (i.e. _not bored). But thanks for the suggestions. :)

**Comment by lervag** [comment]
As you can see, the issue was fixed on the neocomplete side, so I can introduce the undo position hack again. I'm doing that as we speak. Please test.

**Comment by dbmrq** [comment]
It's looking good, thanks! 🎉 

I think I just noticed another problem, though. 😳
Run `gqip` in this paragraph:

```
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
voluptua.
% Whatever
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
voluptua.
\item Whatever
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
voluptua.
```

The lines above and below the comment are joined, and the lines below the `\item` are joined too. Is that the expected behavior? I can open a new issue, I just wasn't sure if this is intentional. But I thought the custom `formatexpr` shouldn't join the comments with the rest of the text, right?

Anyway, it's looking great, thanks for your hard work. I just thought I'd let you know in case this isn't how it should be.

**Comment by lervag** [comment]
Interesting. I think it is the expected behaviour for `\item`, but not so for the comment. I would be happy if you could open an issue for the comment part. I'll (try to) fix it when I get the time.
