### ISSUE TITLE
Nested syntax highlighting for Gnuplot (gnuplottex package)

### ISSUE THREAD

**Issue by matthewjohnrussell** [lervag/vimtex#514]
Would it be difficult to add syntax highlighting for nested Gnuplot commands that one puts inside a `gnuplottex` environment?

    \begin{gnuplottex}[terminal=..., terminaloptions=...]
        ...
    \end{gnuplottex}

It seems that in general, it is possible to enable such nested highlighting (many other vim plugins, e.g. for web frameworks with HTML+other language templates). I was able to modify [this](http://vim.wikia.com/wiki/Different_syntax_highlighting_within_regions_of_a_file) to enable Gnuplot highlighting in a plain text file, but didn't have time to make it work with LaTeX.

**Comment by lervag** [comment]
Done. It seems to work pretty well, but please test and let me know if there is something missing.
