### ISSUE TITLE
gq doesn't work with set fo+=a

### ISSUE THREAD

**Issue by danielbmarques** [lervag/vimtex#517]
It's me again, please don't hate me. 🙈 

The main reason I didn't use `formatoptions=a` with `tex` files is that it joins lines when it shouldn't, so I find it better to control the formatting myself. Now with your new `formatexpr` I don't have that problem anymore, so I thought "ok, let's turn on the automatic formatting". But if I do that (`set fo+=a`) the formatting goes haywire and I can't write anything anymore. The cursor jumps to the end of the paragraph at each character I type.

I don't know how hard it would be to fix this and the new `formatexpr` is already great, but I thought I'd mention this anyway, in case you have the time to take a look.

Thanks. :)

**Comment by lervag** [comment]
I'll look at it when I get the time. I think I know what is happening.

**Comment by danielbmarques** [comment]
Great, thanks. :)

While you're at it, I just noticed another problem (sorry, haha).

When using the automatic line breaks in insert mode (like I mentioned [here](https://github.com/lervag/vimtex/issues/436#issuecomment-236453873)), start with this text:

    Lorem ipsum dolor sit amet, consetetur sadipscing elitr, (sed diam nonumy eirmod
    tempor invidunt ut labore et dolore magna aliquyam erat, SED diam voluptua).

Place the cursor right after the uppercase "SED" and start typing whatever you want. When the line breaks the cursor ends up after the closing parenthesis (the same happens for brackets and braces).

**Comment by lervag** [comment]
Ok, this is strange. I can't find any way to get the cursor position in the `formatexpr` during autoformat (with the `a` option in formatoptions). Without that, it becomes impossible to set the correct position after formatting. That is, to be more specific: The cursor position returned from `getcurpos` (and similar) is never correct during autoformatting.

Thus, it seems I can't get this working with autoformat, sorry.

I'll look at the other issue now.

**Comment by lervag** [comment]
This is also difficult, it seems. I found I can turn to the internal formatter in these cases. How does that sound? I'll push that now, and you can test.

I am not sure if this will work or not. But it seems that it is difficult to implement a good behaviour for automatic formatting, also for this latter kind. The reason is that it won't allow me to format on spaces, which means it becomes very difficult to know if the word you're typing is finished or not.

**Comment by danielbmarques** [comment]
Uhm, how odd. Well, for the second problem is seems to work fine now. As for the first I guess I'll have to keep living without `fo=a`, then. Thanks again. :)

**Comment by lervag** [comment]
No problem. I'll try to keep this in mind, in case I should ever come over a Vim hack that could help with this issue. In the meantime, I'll take the liberty of closing.

The feeling of zero open issues... :)
