### ISSUE TITLE
Calling :VimtexView during compilation with g:vimtex_view_use_temp_files = 1

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#521]
### Explain the issue

When I call :VimtexView while pdflatex is running with g:vimtex_view_use_temp_files = 1 and g:vimtex_view_method='zathura', then the output file foo.pdf of pdflatex gets copied to foo_vimtex.pdf and the viewer is updated, which results in nothing shown in zathura (since the pdf file is corrupt). I would prefer foo_vimtex.pdf not to be updated in this case.

1. Steps to reproduce

Compile a sufficiently large .tex document and call :VimtexView with the settings above while pdflatex is running.

2. Expected behaviour

I expect foo_vimtex.pdf not to change.

3. Observed behaviour

foo.pdf gets copied to foo_vimtex.pdf

### Minimal working example

For small latex files this is difficult to reproduce since the compilation takes little time. So I do not provide a minimal working example.

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_latexmk_callback=1 " needed for zathura_alternative
let g:vimtex_view_use_temp_files = 1
let g:vimtex_view_method='zathura'
```

**Comment by lervag** [comment]
Interesting. I do not see an immediate solution. I _could_ use pgrep or ps to check for pdflatex processes, but that seems more complicated than necessary.

Perhaps the following can work: If `VimtexView` is called, then either:

1. If no viewer is already open, then copy files and open viewer (assume pdflatex is not running), or
2. Only do forward search, don't update files

In this case, `VimtexView` will only do the file copying if it has to start the viewer. Thus, you will still have a problem if you start compilation and then immediately do `\lv` to open the viewer. But I think it might be a good compromise. What do you think?

**Comment by heiderich** [comment]
If I remember it correctly, atp-vim does consult the process tables and I guess that it does partly for this purpose. I think it uses psutil. Not sure if this is easier than parsing ps or pgrep directly. I guess it might depend less on the OS.

Otherwise, I think your suggestion sounds like a good compromise.

**Comment by lervag** [comment]
Right. Consulting the process table is "easy" on linux (for me), but on MacOS and Windows I really don't know how to do things. That is, on MacOS, one might often use the same utilities as on linux. I would rather avoid to consult the process table, so since I agree that my suggestion is a good compromise, I will implement it and we can evaluate whether it works well enough.
