### ISSUE TITLE
[x] in citation autocomplete

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#522]
This may be the wrong forum for this question, depending on the source of the observed behavior. So, please direct me to someplace else if necessary.

I am using neocomplete with the settings recommended in the vimtex documentation (see below). When I use neocomplete to complete citations I have observed a set of rectangular brackets enclosing a single letter prefacing the match (see picture). Is this pattern generated by vimtex and, if so, is there a way to use this pattern to use a key sequence to select a match in the list?

![image](https://cloud.githubusercontent.com/assets/6321578/17556242/b816aa64-5ee0-11e6-8778-c1f326e8b5f0.png)

## Neocomplete Settings
```viml

" Neocomplete options
let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_smart_case = 1
let g:neocomplete#lock_buffer_name_pattern = '\*ku\*'

" Define keyword patterns
if !exists('g:neocomplete#keyword_patterns')
  let g:neocomplete#keyword_patterns = {}
endif
let g:neocomplete#keyword_patterns['default'] = '\h\w*'

" Plugin key-mappings.
inoremap <expr><C-g> neocomplete#undo_completion()
inoremap <expr><C-l> neocomplete#complete_common_string()

" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
endfunction

" <TAB>: completion.
inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"

" <C-h>, <BS>: close popup and delete backword char.
inoremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS>  neocomplete#smart_close_popup()."\<C-h>"

" vimtex settings below (taken from vimtex help as of August 10, 2016)
if !exists('g:neocomplete#sources#omni#input_patterns')
   let g:neocomplete#sources#omni#input_patterns = {}
endif
let g:neocomplete#sources#omni#input_patterns.tex =
         \ '\v\\%('
         \ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
         \ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
         \ . '|hyperref\s*\[[^]]*'
         \ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
         \ . '|%(include%(only)?|input)\s*\{[^}]*'
         \ . '|\a*(gls|Gls|GLS)(pl)?\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
         \ . '|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*'
         \ . '|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*'
         \ . ')'
```

**Comment by lervag** [comment]
What you see is an indicator of the type of bibliography entry. I don't remember the codes right now, but they are parsed from the output of running bibtex. They are not used for actually completing anything.

These are useful e.g. if you have two references with similar names, but of differing types (e.g. book and article with same author and similar title).

So, to answer your question(s): Yes, this "pattern" is generated by vimtex, and no, it is not possible to use it to select a completion.

PS! I updated your vimrc sample, removed irelevant stuff and comments.

**Comment by fuzzybear3965** [comment]
You're insanely helpful, @lervag. Sorry that my vimrc sample was in a poor state that had to be amended. I had cleaned it up a bit, already, in a prior edit.

Keep up the great work!

**Comment by lervag** [comment]
Thanks for the kind words!
