### ISSUE TITLE
How to change the default opener to skim?

### ISSUE THREAD

**Issue by JSDurand** [lervag/vimtex#523]
### Explain the issue

I am just beginning to use `vimtex` and trying to change the default pdf opener to `skim`, if this is possible.
I am using a mac el capitan, and set to execute :VimtexCompile every time I save the document. This works and after the compile, it opens Preview to view the pdf. But other key combinations `<leader>lv, <leader>lo, <leader>li` don't work: `<leader>lv` gives the following error:

```tex
"MWE.tex" [New] 6L, 71C written
Error detected while processing function Tex_ViewLaTeX:
line   34:
E121: Undefined variable: s:viewer
E116: Invalid arguments for function strlen(s:viewer)
E15: Invalid expression: strlen(s:viewer)
line   39:
E121: Undefined variable: appOpt
E15: Invalid expression: 'open '.appOpt.s:viewer.' $*.'.s:target
line   79:
E121: Undefined variable: execString
E116: Invalid arguments for function substitute(execString, '\V$*', mainfname, 'g')
E15: Invalid expression: substitute(execString, '\V$*', mainfname, 'g')
line   80:
E121: Undefined variable: execString  
E116: Invalid arguments for function Tex_Debug  
line   82:  
E121: Undefined variable: execString
E15: Invalid expression: 'silent! !'.execString
```
And `<leader>li` just places me in `insert mode`as if I pressed `li` and `<leader>lo` is equivalent with `lo` as well. I tried to use the `<localleader>` versions, but to no avail.
### Minimal working example

I am using this MWE:

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Minimal vimrc file

I think the relevant part in the vimrc file is
```vim
set nocompatible
filetype off                  " required

" Vundle plugin area {{{
"set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'Valloric/YouCompleteMe'
Bundle 'altercation/vim-colors-solarized'
Plugin 'lervag/vimtex'
call vundle#end()            " required
" }}}

" auxiliary settings {{{
syntax on
filetype plugin indent on
" }}}

let mapleader = "-"

" tex {{{
augroup tex
  autocmd!
  autocmd BufWritePre *.tex :VimtexCompile
augroup END

" tex settings {{{
filetype plugin on
set grepprg=grep\ -nH\ $*
filetype indent on
let g:tex_flavor='latex'
set sw=2
set iskeyword+=:
let g:tex_fold_enabled=1
let g:tex_nospell=1
let g:tex_no_error=1
"let g:vimtex_view_general_options = '-r @line @pdf @tex'
"let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
"let g:vimtex_view_general_options = '-r @line @pdf @tex'
"let g:vimtex_view_general_options_latexmk = '-r'
"let g:vimtex_fold_enabled = 0 "So large files can open more easily
" }}}


```
I have made some changes: those commented part in the end, but every time I get the same result: I didn't check the error output of `<leader>lv` each time, though.
This is a great plugin, and I am looking forward to the syncing functionalities such as forward/backward searches. 👍 
If needed, I can provide more details on demand, thanks in advance. :)

**Comment by lervag** [comment]
First, I'm happy to hear that you are interested in vimtex and Vim, and I hope it will be a pleasant experience. :)

So. I'm curious, are you aware of how `latexmk` works? Vimtex relies on `latexmk` for compilation, and in particular, the continuous compilation mode. This can be turned off with `g:vimtex_latexmk_continuous`, but in general I find this works very well and I think most people will like it.

The above paragraph means that, if you do not disable it, `:VimtexCompile` will already start a `latexmk` process that will compile the latex document whenever any relevant files change. Thus your autocommand is not necessary and should be removed.

Regarding the first things you mention, and the error messages: `Tex_ViewLaTeX` is __not__ a part of vimtex. Instead, it is part of the well known latex-suite (aka vim-latex), see [here](http://vim-latex.sourceforge.net/). I think you have installed this through a package manager or something similar, and I propose that you remove it. You should _not_ use latex-suite together with vimtex.

Regarding how to configure Vim and vimtex correctly, in particular for Skim, I think the following should work:

```vim
set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'lervag/vimtex'
call vundle#end()

syntax on
filetype plugin indent on

let mapleader = "-"

" Settings
set grepprg=grep\ -nH\ $*
set sw=2
set iskeyword+=:
let g:tex_flavor='latex'
let g:tex_fold_enabled=1
let g:tex_nospell=1
let g:tex_no_error=1

let g:vimtex_view_general_viewer
      \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
let g:vimtex_latexmk_callback_hooks = ['UpdateSkim']

function! UpdateSkim(status)
  if !a:status | return | endif

  let l:out = b:vimtex.out()
  let l:tex = expand('%:p')
  let l:cmd = [g:vimtex_view_general_viewer, '-r']
  if !empty(system('pgrep Skim'))
    call extend(l:cmd, ['-g'])
  endif
  if has('nvim')
    call jobstart(l:cmd + [line('.'), l:out, l:tex])
  elseif has('job')
    call job_start(l:cmd + [line('.'), l:out, l:tex])
  else
    call system(join(l:cmd + [line('.'),
          \ shellescape(l:out), shellescape(l:tex)], ' '))
  endif
endfunction
```

For more information about how to configure Skim, see `:h vimtex_viewer_skim`, and in particular, see the link in the note regarding how to get backward search working.

Finally, I understand that the documentation is very extensive and long, but I still very much recommend that you read it. At least read the introduction and skim the remaining part. I think that will help you understand how things work, and it will make it easier to explain issues you might have.

**Comment by JSDurand** [comment]
Thanks for the response. Now I am reading the introduction in the documentation. I find that the reason for this weird behavior might be that the vim I am using does not have client server support (I was quite confused by the warning received every time I open a tex file. :P).  

In fact, after the changes as described in your response, it works now in MacVim, but still fails in terminal vim. So I am trying to compile vim with client server support now.

Thanks again for the response. :D

**Comment by lervag** [comment]
No problem! Let me know if you have more problems. In the mean time, I'll close the issue. :)
