### ISSUE TITLE
Custom formatexpr joining comments

### ISSUE THREAD

**Issue by dbmrq** [lervag/vimtex#524]
Running `gqip` in the paragraph below causes the line with the comment to be joined with those above and below it.

```tex
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
voluptua.
% Whatever
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
voluptua.
```

**Comment by lervag** [comment]
An easy solution is to say that any lines that contains a comment string will not be formatted. However, this would also mean that e.g.

```
test
testing % tested
```

would not be formatted to

```
test testing % tested
```

Still, do you think this would work for you?

**Comment by dbmrq** [comment]
It's definitely an improvement I think.

But the line bellow a line with a comment shouldn't be formatted too, I think… like:

    testing % tested
    test

shouldn't become

    testing % tested test

Will that account for this scenario?

Ideally I think the rule should be: if a line *starts* with a comment, it shouldn't be joined to the line *above* it; if a line *contains* a comment, it shouldn't be joined with the line *below* it.

I think just disabling it the formatting for lines with comments already helps, though. And also it would account for a scenario like this:

```
% a
% b
% c
```

Which shouldn't become `% a % b % c` I think.

**Comment by lervag** [comment]
Yes, my idea will preserve all comment lines. I principle, it will disable formatting of any lines if it contains comments, which will not necessarily be what everyone expects. But to handle comments correctly is not trivial. If I were to allow lines that end with comments to join with lines above, as long as the comment is intact, it would mean that I also need to handle that in some cases, the content of the line must be joined but the comment must be left alone. That is, something like this:

```tex
testing
test % tested

becomes

testing test
% tested
```

I think that in general, using comments at the end of lines is bad style, and it should be avoided.

**Comment by lervag** [comment]
Sometimes I think I won't have time to do something... In any case, I think the latest commit should at least improve things. It might have some unintended side effects that I did not think of. Let me know what you think.

**Comment by dbmrq** [comment]
Great, it's definitely and improvement. :)

And I'm totally satisfied with how it is already, I'm just mentioning possible problems because I thought you'd want to know If you have other priorities or just don't think some things are worth the trouble it's absolutely fine.

**Comment by lervag** [comment]
I just pushed a minor bug fix.

At the moment, I think I'll leave this as it is. I'll of course reconsider if there are good reasons. In the meantime, I'll close this as fixed for now. I hope you approve :)

**Comment by dbmrq** [comment]
Sure, thank you!

**Comment by lervag** [comment]
No problem :)
