### ISSUE TITLE
Extend % Motion for \middle

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#525]
Consider following latex code line:

```
\left( \frac{a}{b} \middle| q \right)
```

I would expect that the % motion also cycles through `\middle` which currently does not happen.

What do you think about this?

**Comment by lervag** [comment]
I think you're sort of right to expect that behaviour, but I think it is to complex to implement. I'll look at it, though.

**Comment by lervag** [comment]
No, it is not possible. Based on `\middle|`, it is not possible to know what the start and end is. It would require guessing and/or assuming a given behaviour. I thus think it is better to keep the current behaviour, which works very well (I think) for all matching start/end delimiters.

**Comment by kiryph** [comment]
I am wondering whether you would reconsider this issue, maybe in the light of the recent discussion on 
https://www.reddit.com/r/vim/comments/7c1rjd/matchup_a_modern_enhanced_matchit_replacement/

I am not entirely sure why you said it is not possible. Consider following ruby file
```ruby
if var == 10
    print “Variable is 10”
elsif var == “20”
    print “Variable is 20”
elsif var == “30”
    print “Variable is 30”
else
    print “Variable is something different”
end
```
Apparently you can cycle through.

I know that you can invert `)` and `(` in latex as don in following example
```tex
\biggl)\times \frac{a}{b} \times\biggr(
```
But you would still use \biggl and \biggr.

I add a few more situations where `%`, `g%`, `]%`, `[%` could be useful:

```tex
\left \middle ... \middle \right
\bigl \bigm ... \bigm \bigr
\Bigl \Bigm ... \Bigm \Bigr
\biggl \biggm ... \biggm \biggr
\Biggl \Biggm ... \Biggm \Biggr
```

There is not only `\begin{} \end{}`
```tex
\makeatletter ... \makeatother
\begingroup ...\endgroup
```

Also for `itemize, enumerate, description` environments `\item` could become a target as well
```tex
\begin{itemize}
\item
...
\item
\end{itemize}
```

Plain tex `\if, \else, \fi`
```tex
\ifpdf
\DeclareGraphicsExtensions{.pdf,.jpg,.png}
\else
\DeclareGraphicsExtensions{.eps,.jpg,.png}
\fi
```

Package booktabs `\begin{tabular} \toprule, \midrule, \bottomrule, \end{tabular}`
```tex
    \begin{tabular}{@{} lr @{}}
      \toprule
      City & Population\\
      \midrule
      Mexico City & 20,116,842\\
      Shanghai & 19,210,000\\
      Peking & 15,796,450\\
      Istanbul & 14,160,467\\
      \bottomrule
    \end{tabular}
```

I am certain that there are more constructs.

So I just hope to convince you to either delegate this functionality to matchit or the new matchup plugin or extend vimtex itself.

**Comment by lervag** [comment]
When I said "not possible", I think I really meant "very difficult". The point is that the vimtex implementation of the `%` command assumes relatively common delimiters, but one has to match the delimiters with possible modifiers to the alternate form. There are a lot of combinations. If we also parse the middle part, it becomes very complex. I.e., if cursor is at `\midrule` and you type `%`, you would have to recognize that you are in a tabular environment. If you are in `\middle`, it means that we are in a math construct.

However, considering @andymass has opened a similar thread at #1009, I propose that we continue this discussion there.
