### ISSUE TITLE
Broken syntax highlighting when defining custom math column type

### ISSUE THREAD

**Issue by bartbkr** [lervag/vimtex#526]
### The issue

When defining a custom math column type, the syntax highlighting in the
rest of the document seems to break. It seems as though the syntax
highlighting assumes that the rest of the document is in math mode.

### Minimal working example

```tex

\documentclass{article}

\newcolumntype{R}{>{$}r<{$}}

\begin{document}

This is colored as if it is in a math section, rather than the default text
color.

\end{document}
```

(As you can see, it also seems to broken in the Markdown syntax for tex).

### Relevant parts of vimrc for vimtex (I load plugin using vim-plug):

```vim

"vimtex options
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options = '-forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
let g:vimtex_motion_matchparen = 0

```

**Comment by lervag** [comment]
This is not a vimtex issue. It is an issue with the internal syntax plugin. Consider: `vim -u NONE test.tex`, then `:syntax enable`. Now vimtex is not enabled, and you have the same issue.

You should consider reporting this to Charles E. Campbell, who maintaines the syntax plugin. You should also read `:h vimtex-syntax`.

**Comment by bartbkr** [comment]
Great thank you. I will reach out to Dr. Chip about this.

**Comment by lervag** [comment]
No problem. If Dr. Chip solves this, then he will solve it for everyone who writes (La)TeX with Vim, which is very nice. Vimtex is still only use by some (probably not a very large fraction of relevant Vim users).
