### ISSUE TITLE
Is it possible to automatically run :VimtexView after every successful compilation in continous mode?

### ISSUE THREAD

**Issue by steveeJ** [lervag/vimtex#527]
My vim skills are so little that my attempts are not worth sharing here, but my best guess is that something can be added to `g:vimtex_latexmk_callback_hooks`.

I'd appreciate help with this one!

**Comment by lervag** [comment]
Yes, this is possible. I assume you want `:VimtexView` in order to forward search, right? Which viewer are you using?

**Comment by steveeJ** [comment]
@lervag that's right! I'm using _zathula_.

**Comment by lervag** [comment]
Try this:

```vim
function! ViewerCallback() dict
  call self.forward_search(self.out)
endfunction

let g:vimtex_view_zathura_hook_callback = 'ViewerCallback'
```

**Comment by ih4cku** [comment]
How should I add for general viewer. BTW, I'm using `qpdfview`.

I tested with the following function:

```vim
function! ViewerCallback() dict
    echom '-->'
    call system('gedit')
    echom '<--'
endfunction
```

I tested two methods to call the function after build:
```vim
" let g:vimtex_view_general_callback = 'ViewerCallback'
```
and 
```vim
autocmd FileType tex :call add(g:vimtex_latexmk_callback_hooks, function('ViewerCallback'))
```

However, neither works.

**Comment by lervag** [comment]
There are two errors. The first was on my side, and has been fixed in the most recent commit. The second was on your side: The `ViewerCallback` takes one argument: the status, which is 1 if the compile was successfull or 0 if it failed.

**Comment by lervag** [comment]
Note: The `vimtex_view_general_callback` does not quite follow the same pattern as the `vimtex_view_zathura_hook_callback`. I realize this is somewhat confusing, and I might improve it at a later time. The code works if you do the change I suggested in the previous post. Note that for the general callback, you need an argument. For the zathura and mupdf callback hooks, you _don't_ use an argument.

**Comment by ih4cku** [comment]
Thanks, lervag. It  works. This is my solution for general forward call after success building.

```vim
let g:vimtex_view_general_callback = 'ViewerCallback'
function! ViewerCallback(status) dict
    if a:status
        VimtexView
    endif
endfunction
````

**Comment by lervag** [comment]
Thanks for sharing! :)

**Comment by lervag** [comment]
@steveeJ Have you had a chance to try my suggested configuration? I think it should work, so I'll take the liberty of closing the issue. Let me know if you have any more problems.

**Comment by steveeJ** [comment]
@lervag I've tried to add your first suggestion to my vimrc, adding the _status_ variable to the function arguments. It doesn't seem to have any effect though. Do I need the latest commit for this to work?

**Comment by lervag** [comment]
@steveeJ  This should work:

```vim
function! ViewerCallback() dict
  call self.forward_search(self.out)
endfunction

let g:vimtex_view_zathura_hook_callback = 'ViewerCallback'
```

Notice no status argument. I think you got things confused after @ih4cku talked about a related issue. I don't think you need the most recent commit, but there is really no reason at all not to update to the most recent version. I don't operate with stable versions and version numbers, thus I suggest that you try to update vimtex every once in a while, as I still push some bug fixes and updates at semi regular intervals.

**Comment by steveeJ** [comment]
@lervag thanks, unfortunately still no luck. I'll try to update to the latest commit later today and see if that helps. Currently I'm using 35fae13d17a08a7688a385644879f073a0fc8809.

**Comment by lervag** [comment]
Ok, then I think we need to take things one step back. Could you please create a minimal working example and a minimal vimrc file? See [the issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md) for how to do this and for what should be included.

Note, though, that 35fae13 is a month old, and so there are a lot of updates. I would not be surprised if there might be relevant updates. Thus I encourage you to update to the newest version.

**Comment by hejops** [comment]
How could this be done with the new VimtexEventCompileSuccess trigger?

```
function! ZathuraSearch() dict
  call self.forward_search(self.out)
endfunction

augroup vimtex_compilesearch
 au!
 au User VimtexEventCompileSuccess call ZathuraSearch()
augroup END
```

I'm getting the error `E725: Calling dict function without Dictionary: ZathuraSearch`.

**Comment by lervag** [comment]
Sorry, I made an error in my example. Try and remove the `dict` attribute of the function.

**Comment by hejops** [comment]
Doing that produces the following:

```
Error detected while processing function <SNR>77_callback_continuous_output[7]..vimtex#compiler#callback[28]..User Autocommands for "VimtexEventCompileSuccess"..function ZathuraSearch:
line    1:
E121: Undefined variable: self
```

Does the function need to be reworked?

**Comment by lervag** [comment]
Sorry, my mistake. The following should probably work better:

```vim
function! ZathuraSearch() abort
  if b:vimtex.viewer.xwin_exists()
    call b:vimtex.viewer.forward_search(b:vimtex.viewer.out())
  endif
endfunction
```

I'll update my previous post as well.

**Comment by hejops** [comment]
Works great, thanks!

**Comment by lervag** [comment]
Happy to hear it :)

**Comment by theRoboxx** [comment]
I tried your answer @lervag and `g:vimtex_view_zathura_hook_callback` seems to be deprecated by now.
Is it still possible to achieve this behavior today?

**Comment by lervag** [comment]
Yes, it's still possible, but now much simpler. Add this to your VimTeX
config:

```vim
augroup vimtex_auto_view
  autocmd!
  autocmd User VimtexEventCompileSuccess VimtexView
augroup END
```

Or, if you prefer Lua:

```lua
vim.api.nvim_create_autocmd("User", {
  pattern = "VimtexEventCompileSuccess",
  command = "VimtexView",
})
```

`VimtexEventCompileSuccess` fires after every successful compilation, including each successful rebuild while compiling in continuous mode. So `:VimtexView` will be invoked automatically each time. See `:help VimtexEventCompileSuccess` and the autocommand examples just below it for more info.

**Comment by theRoboxx** [comment]
> vim.api.nvim_create_autocmd("User", {
>   pattern = "VimtexEventCompileSuccess",
>   command = "VimtexView",
> })

Thank you very much for the fast reply, I didn't expect that :)
It works but there is still one little problem. 
It opens my pdf viewer zathura two times and one works with the new added behavior and the other one like the old one.

This is the config:
``` lua
  ft = function()
    -- PDF Viewer configuration - using zathura
    vim.g.vimtex_view_method = "zathura"

    vim.g.vimtex_compiler_method = "latexmk"
    vim.g.vimtex_compiler_latexmk = {
      build_dir = "",
      callback = 1,
      continuous = 1,
      executable = "latexmk",
      options = {
        "-pdf",
        -- "-pvc",
        "-verbose",
        "-file-line-error",
        "-synctex=1",
        "-interaction=nonstopmode",
      },
      hooks = {},
    }
    -- new 
    vim.api.nvim_create_autocmd("User", {
      pattern = "VimtexEventCompileSuccess",
      command = "VimtexView",
    })
    -- new 
  end,

```

**Comment by lervag** [comment]
> Thank you very much for the fast reply, I didn't expect that :)

No problem!

> It works but there is still one little problem. It opens my pdf viewer zathura two times and one works with the new added behavior and the other one like the old one.

Right, ok. So, first, your config is not good. Let's simplify it, please remove everything except this:


```lua
vim.g.vimtex_view_method = "zathura"

vim.api.nvim_create_autocmd("User", {
  pattern = "VimtexEventCompileSuccess",
  command = "VimtexView",
})
```

If you want to change the options for the latexmk compiler, then please read `:help g:vimtex_compiler_latexmk` first!

Now, I suggest you add this as well:

```lua
vim.g.vimtex_view_automatic = false
```

This prevents the viewer from opening automatically, and it may resolve the issue you have.

**Comment by theRoboxx** [comment]
Awesome! That solved it!

For clarification, I'm using [AstroNvim](https://github.com/AstroNvim/AstroNvim) and Included this [Community plugin](https://github.com/AstroNvim/astrocommunity/blob/main/lua/astrocommunity/markdown-and-latex/vimtex/init.lua) to my config,
