### ISSUE TITLE
[Feature Request] Add option to open vimtex-toc in horizontal split

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#528]
### Explain the issue

I have put my display in portrait mode, i.e. rotated by 90 degrees. For most work I do this makes more use of the screen real estate. For instance, in all my source code files the lines are basically hard wrapped at about 80 chars.

However, splits should by default be horizontally. So I'd like to have an option to open vimtex-toc and vimtex-labels in horizontal splits instead of vertical splits.

This is already the default behaviour for the following builtin splits: `:help`, `:copen` and the preview window. Also fugitive does it by default for `:Gstatus`.

**Comment by lervag** [comment]
This is already supported. You can make the vimtex TOC open in a horizontal split with `let g:vimtex_index_split_pos = 'below'` (or `above`).

**Comment by kiryph** [comment]
Sorry for not RTFM. Thanks for your great latex plugin and your active support of it.

**Comment by lervag** [comment]
No problem! I know that the manual/documentation is quite comprehensive, and so it is easy to miss stuff. :)
