### ISSUE TITLE
Go to first line with gg in vimtex-toc does not work

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#529]
### Explain the issue

1. **Steps to reproduce**  
    Open vimtex-toc with `<Leader>lt`, press `G` and then `gg` 
2. **Expected behaviour**  
    Cursor should be again at the top of the toc
3. **Observed behaviour**  
   Cursor stays on the last line but moves to the most right column which seems to be a bookkeeping column of numbers. BTW: What is the purpose of this column?

My vimtex settings in vimrc are:

```
" Vimtex: {{{2
let g:tex_flavor='latex'
let g:tex_no_error=1
let g:vimtex_fold_enabled = 1
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
let g:vimtex_view_general_options_latexmk = '-r 1'
let g:vimtex_fold_preamble = 0
let g:vimtex_fold_documentclass = 1
let g:vimtex_toc_secnumdepth = 1
let g:vimtex_index_show_help = 0
let g:vimtex_index_split_pos = 'above'
```

I have noticed that `gg` is remapped at https://github.com/lervag/vimtex/blob/9b158d763ec7f899baecb790a8e1f694057fbbcf/autoload/vimtex/index.vim#L90
which is most likely the reason for this behaviour together with the setting `let g:vimtex_index_show_help = 0`.

**Comment by lervag** [comment]
Sorry, `gg` should not be remapped if the help text is not displayed. Thanks for reporting!
