### ISSUE TITLE
[RFC] vimtex-index windows and D. Neil's opinion about project drawers

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#530]
Right now, I use [tpope/vim-vinegar](https://github.com/tpope/vim-vinegar) plugin which reconfigures the with vim distributed filebrowser `netrw` following the ideas of Drew Neil in his article [Oil and vinegar - split windows and the project drawer](http://vimcasts.org/blog/2013/01/oil-and-vinegar-split-windows-and-project-drawer/).

I think it would be a good option to vimtex to open the toc and table of labels windows in the currently active window when the user presses `<Leader>lt` instead of opening a split window.
This should of course only be an option the user has to add to vimrc because not everyone might want this behavior.

What do you think about this?

**Comment by lervag** [comment]
I agree, it should be possible. I'll see what I can do.

**Comment by lervag** [comment]
Should work now.

**Comment by kiryph** [comment]
Yes, it works. Thank you very much for this update as well.

**Comment by lervag** [comment]
No problem :)
