### ISSUE TITLE
Add support for tikzscale

### ISSUE THREAD

**Issue by benutzer193** [lervag/vimtex#532]
### Explain the issue

I don't know if this case is too special, but if you use the package *[tikzscale](http://www.ctan.org/pkg/tikzscale)* you have to include tikz-pictures using *\includegraphics*.
See [here](http://ftp.math.purdue.edu/mirrors/ctan.org/graphics/pgf/contrib/tikzscale/tikzscale.pdf) for the documentation.
The tikzimage files may only contain one tikzpicture environment and nothing else.

Features that could be added:

- autocomplete for *\includegraphics[...]{...}* (atm it only shows images)
- add it as ToC entries, so you can easily edit the images

The easiest possibility (I guess) would be to only allow the following file endings: .tikz, .TIKZ, .TikZ, .pgf or .PGF

**Comment by lervag** [comment]
I didn't know of this package. It seems convenient. If I were to add this feature, I would first have to implement a system that detects packages and sets options based on which packages are used. That is, `\includegraphics` should not autocomplete `.tikz` figures unless the `tikzscale` package is loaded.

The second feature is slightly more complicated, but I'll look at it. I think I would want to demand that one uses full file names, i.e., that the extension is included. In this case, I could parse the `\includegraphics` lines easily and add entries to the ToC.

**Comment by benutzer193** [comment]
Yeah, for the filename, I believe there is no case anybody would load a file named .tikz etc., if not using tikzscale, as this package adds the feature AND at the same time denies the use of tikzpicture environments outside a file loaded with includepicture.

And I think you should just add a paragraph in the documentation, that the feature is only available if the file is named accordingly. So it is a lot easier to determine when to use the feature, that means for you to implement.

I actually just discovered the package and love the scaling. It is a lot better than any other solution I found on stackexchange and can only recommend to use this package if you use a lot of tikzpictures. Aaaand you can easily reuse pictures.

**Comment by lervag** [comment]
Good point. I agree, if there are `.tikz` files (case ignored), it seems pretty safe to assume that these could be autocompleted directly. I'm pushing the update asap.

Regarding the TOC: I find it's less than trivial, because the paths used in the `\includegraphics` command may not be relative to the current file, since there are already other search paths defined in the `\graphicspath` command. At least for now, it becomes to bothersome to add. Also, I would have to add some sort of support for `tikz` and/or `pgf` files, e.g. to allow to open the TOC from such files. Could you please test if this feature really is necessary, that is, if your workflow may be good without it? I could reconsider, but it will have to be at a later time...

**Comment by benutzer193** [comment]
No it is not that necessary, but I just had an idea how sou could implement it and add support for other cases as well

you could add a include option specifically for vimtex, something like:

```tex
%vimtex-include: /path/to/file
```

So if you want to have a link to a file in the doc, but it is not supported otherwise, you can do it this way.
What do you think of this idea?

**Comment by lervag** [comment]
I like your idea, but there is one catch: the TOC won't be available unless the file you open is part of the current project. I.e., if you opened a tikz file through this means, then you would not be able to do `\lt` to open the TOC from the tikz file. You _can_ use the alternate file toggle, though: `<ctrl>-^`. It is a standard Vim feature that is very useful.

So: Do you still think this will be useful given the above restriction?

**Comment by benutzer193** [comment]
I think it is useful, because you always have the possibility to jump through your buffers. So if yu have open your tikz file or something else your tex file is always open as a buffer.

Another possibility (and I don't know if it would be hard to implement) would be if you open a document that is included with `%vimtex-include` (or how you name it) through the TOC, this buffer should know the current tex project and have the possibility to open the TOC.
I think it should work similar to the bib-file implementation, you just would have to trigger it differently (not with bib.vim).

**Comment by lervag** [comment]
I think the latest version should be satisfactory. It copies the current vimtex mappings into any file opened through the ToC. It might have side effects that I didn't think of, but we can resolve those later if desired.

**Comment by benutzer193** [comment]
Great, I'll report if I encounter any problems!
Thanks again.

**Comment by lervag** [comment]
No problem :)
