### ISSUE TITLE
Inconsistent syntax highlighting in toc with section/chapter name containing colon

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#534]
MWE:
 ```tex
\documentclass{article}

\begin{document}
\section{Hello World}

\section{Hello: World}

\end{document}
```
Open vimtex-toc:
![syntax-highlighting-vimtex-toc](https://cloud.githubusercontent.com/assets/371756/17972506/40066a36-6adf-11e6-8825-b8f6bdce7a60.png)

With the help of scriptease.vim I could identify the possible source: `zS` tells me that the second section name and number is highlighted as `VimtexTocHelp` whereas the first section is highlighted as `VimtexTocSec0` and the first section number as `VimtexTocNum VimtexTocSec0`.

`VimtexTocHelp` is here defined
https://github.com/lervag/vimtex/blob/master/autoload/vimtex/index.vim#L235

```
function! s:syntax() dict " {{{1
  syntax match IndexHelp /^.*: .*/
  syntax match IndexLine /^  .*$/ contains=@Tex
endfunction
```

This seems to be triggered because of the colon in section name and overriding the syntax definition in `autoload/vimtex/toc.vim`.

**Comment by lervag** [comment]
Should be fixed now.
