### ISSUE TITLE
Wrong project picked for compilation/visualization when files from multiple projects are opened

### ISSUE THREAD

**Issue by rionda** [lervag/vimtex#536]
I opened a file in one project, and started background compilation on this project. Then opened another file in another project (without starting background compilation on it). Then wiped the buffer (:bw) containing this second file. Now when calling \lv, the PDF of the second project shows, rather than the PDF of the first. Also, if at this point I do \ll twice, the background compilation is started on the second project, of which there is not even a file open. The two project are in separate directory structures, so it doesn't seem a mainfile problem, but it still seems related to the search.

I'll add a working example when I get around to it.

**Comment by rionda** [comment]
@lervag , here is a working example:

* Create the following two test files called `test1.tex` and `test2.tex`. You can save them in the same directory:
```tex
% test1.tex
\documentclass{article}
\title{Test1}
\author{Test1}
\begin{document}
\maketitle
Test1
\end{document}
```
```tex
% test2.tex
\documentclass{article}
\title{Test2}
\author{Test2}
\begin{document}
\maketitle
Test2
\end{document}
```
*  Open `test1.tex` in vim.
*  In command mode, `:sp test2.tex <Enter>`
*  Move the focus to the buffer of `test2.tex` (it may already be there)
*  In command mode, `:bw <Enter>`
*  You are now in the buffer of `test1.tex`. In command mode `:VimtexCompileToggle` (or `<localleader>ll`, i.e., enable the continuous compulation).

At this point, `test2.tex` gets compiled and `test2.pdf` is opened.

**Comment by lervag** [comment]
Sorry for taking so long. In any case, this was a minor, but subtle bug. I hadn't noticed it myself, but your example worked for me and it was quite easy to solve when I had it reproduced. Thanks!

**Comment by rionda** [comment]
Thank you, @lervag !

**Comment by lervag** [comment]
:)

**Comment by rionda** [comment]
@lervag the problem is almost gone, but not completely.

 If one does almost the same steps as before, but uses `<localleader>lv` in the last step (instead of `<localleader>ll`), `test2.pdf` is opened, instead of `test1.pdf`.

**Comment by lervag** [comment]
This issue is related to #551, I think even it is the same issue. The latest commit should fix things, I think. Please test.
