### ISSUE TITLE
Conflict with Vimgrep

### ISSUE THREAD

**Issue by dragonxlwang** [lervag/vimtex#538]
I can reproduce this problem by using vimgrep searching any keyword in the current directory. After the search, with the quickfix window closed, when using vimtex view, it throws error:

"vimtex warning: viewer cannot read PDF file"

my latexmk.rc file looks like this
```
 $pdf_previewer = "open -a /Applications/Skim.app";
  @default_files = ('main.tex');
  $pdflatex = 'pdflatex -pdf -verbose -file-line-error -synctex=1 -interaction=nonstopmode %O %S';
  $clean_ext = "paux lox pdfsync out synctex.gz";
```

I am using skim to view pdf on Mac OS X. Thanks,

**Comment by dragonxlwang** [comment]
maybe the problem is not resulted from vimgrep only. I will try to find its root.

**Comment by dragonxlwang** [comment]
It seems that whenever I am having a split of window and did the vimgrep, the problem occurs.

**Comment by lervag** [comment]
Can you please provide a specific step-by-step explanation for how to reproduce? Also provide a minimal vimrc file and a minimal example tex-file.

**Comment by lervag** [comment]
I'll consider this again if/when you provide the details I asked.

**Comment by dragonxlwang** [comment]
sorry that currently I don’t have a MWE to illustrate this.

seems it shows up pretty randomly …

**Comment by lervag** [comment]
No problem. But it is near impossible for me to help without a specific guide on how to repeat the problem. :\
