### ISSUE TITLE
Why so much redraw! (instead of redraw)

### ISSUE THREAD

**Issue by jrluw** [lervag/vimtex#539]
I'm surprised there is no configuration option for this.  Vimtex is awesome, except for the fact that it might cause seizures.  In continuous mode, every time latexmk runs it executes a "redraw!"  The problem is that redraw! clears the screen and then redraws it, resulting in a noticeable "flash."  For me, at least, this creates fatigue and headaches.  There is a simple fix (using redraw instead of redraw!).  Would be nice to add an option.

**Comment by lervag** [comment]
Hmm, good question. Perhaps I've been too aggressive on the redraws. I would prefer not to add more options, though, so I first want to investigate whether I can simply remove some of the `!`s. Note, there are almost no flickering at my end. I've tried to change into `redraw` where I think this is safe, and now I only use `redraw!` for the execution utility. I think it might be necessary there, and it does not seem to be relevant for this issue, so I kept that one.

Let me know how this works for you. If it does not add any problems, I'll keep it like this.

**Comment by nasenatmer** [comment]
Haha, I think some of the `redraw!`s have been caused due to issues on my end where the `redraw`s did not actually happen. Although there were quite a few issues where this seemed to be a problem we never really figured out whether it was due to `zsh` or `tmux` (which I both use) or other parts of my setup that caused this problem.

In any case, I can modify my local fork in the vundle directory to use `redraw!` instead of `redraw` if I encounter problems after applying a8c6d43.

Interestingly, though, I never encounter flickering due to `redraw!`s.

**Comment by lervag** [comment]
Neither have I, as I mentioned. I would not be against reverting this change, so if you do experience flickering due to the `redraw`s, then don't hesitate to let me know.

**Comment by jrluw** [comment]
I see.  The flickering could be a window manager issue, or a gvim issue.  I
don't get any flickering when I hit ctrl-L in a terminal, but if I run gvim
with black text on a white background, a screen clear is definitely
noticeable, whereas the screen redraw (without a clear) is undetectable.

I guess I have no particularly good reason to not just run vim in a
terminal.

Now I just have to figure out how to get a PDF viewer that doesn't "flash"
upon reloading a modified file.  (When writing 10+ hours/day, every
superfluous external stimulus gets magnified...)

Thanks,
-j

**Comment by lervag** [comment]
I think mupdf is one of the fastest pdf viewers there are. Perhaps I'm wrong, but I've been happy with it. I also like zathura, which has support for vim like key bindings.

I'll consider this closed then, unless someone complains about the removed `!`s.
