### ISSUE TITLE
Implement LatexLabels functionality

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#54]
LaTeX-Box has a nice feature implemented as the `:LatexLabels` command, which essentially gives a ToC window with a list of labels that match a provided regexp.

I think a nice way to implement this is to add the labels directly to the ToC, and to add a simple filter function in the ToC window mapped to `f`. Another idea might be to somehow interface the ToC to CtrlP to get a nice fuzzy filtering of ToC contents.

Unfortunately, I don't have time to do this now, so I open this issue in order to mention the ideas for future implementation.

**Comment by lervag** [comment]
I've now added a simple function that parses the tex files for the current project and returns a list of all labels. Each entry contains the label name, the file path, and the line number. This should make it easy to couple with external plugins.

**Comment by lervag** [comment]
@Konfekt @nasenatmer Since you have previously been active in several issue discussions, I was hoping you might want to test this new feature. The table of labels may be opened with `:VimtexOpenLabels` and `:VimtexToggleLabels`.

I am not 100% satisfied with the naming of the feature.

**Comment by Konfekt** [comment]
Cool. Works fine and is what TagBar should be for TeX with multifile projects. It's ```:VimtexLabelsToggle``` though.

**Comment by Konfekt** [comment]
In fact, there are errors in a beamer poster project file, that looks like
```tex
\begin{document}
\begin{frame}{}
\begin{columns}[t]

  \column{.32\columnwidth}
  \input{column1.tex}

  \column{.33\columnwidth}
  \input{column2.tex}

  \column{.32\columnwidth}
  \input{column3.tex}

  \begin{block}{Literature}
  \begin{footnotesize}
    \bibliographystyle{epnAmsmath}
    \bibliography{epnMath}
  \end{footnotesize}
  \end{block}

\end{columns}
\end{frame}
\end{document}
```
Error detected while processing function vimtex#labels#toggle..vimtex#labels#open..<SNR>263_gather_labels..<SNR>263_gather_labels:
line    3:
E484: Can't open file <empty>
E484: Can't open file <empty>
E484: Can't open file <empty>
```

**Comment by lervag** [comment]
First: You've added three files through `\input` but not included them here. It would help if you could refine the example and include the inputted file.

**Comment by Konfekt** [comment]
Ok, they all take the form

```tex
\section{Nombres}
\begin{block}{\Large{\thesection. \secname}}


\end{block}
```

**Comment by lervag** [comment]
That's strange. I am not able to reproduce this. I hope it is not too much to ask if you could provide a full minimal working example, including a minimal vimrc file?

**Comment by Konfekt** [comment]
Well, I played around a bit more, and the problem is that there are some `\imput{..}` in the preamble. There is
```tex
\NeedsTeXFormat{LaTeX2e}
% &preamble
  \documentclass[draft,xcolor=x11names,notheorems,compress]{beamer}
  \usepackage[french]{babel}
  \input{Preamble.tex}
  \input{PreambleBeamer.tex}
  \input{PreambleBeamerPoster.tex}
\csname endofdump\endcsname
\title{nombres p-adiques}
\author{Enno}
\date{}

\begin{document}
\begin{frame}{}
\begin{columns}[t]

  \column{.32\columnwidth}
  \input{column1.tex}

  \column{.33\columnwidth}
  \input{column2.tex}

  \column{.32\columnwidth}
  \input{column3.tex}

\end{columns}
\end{frame}
\end{document}

```

Commenting out the three `\input{..}` in the preamble resolves the bug. The problem is that these input files are actually in `~\texmf` and not in the project dir.

**Comment by Konfekt** [comment]
In conclusion: perhaps silently skip input files that are missing in the project dir, especially in the preamble as they could be in the texmf path.

**Comment by lervag** [comment]
Ah, I see. Then this is really a more general issue. I do not see a straightforward way to solve it, but feel free to open an issue. I think this issue also affects both completion and the table of contents (TOC).

**Comment by nasenatmer** [comment]
Cool! Tried it with my biggest project so far (BA thesis), which also includes a few `\input{}` files (in the document only, not preamble) and it works great! Is there a key mapped to it already?

**Comment by lervag** [comment]
Yes, it's mapped to `<localleader>ly` (`Y` for toggle). No particular reason, except that on QWERTY it is close to the TOC mappings.
