### ISSUE TITLE
If multi-file tex project set different vimtex options

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#541]
### Explain the issue

I have following settings in my vimrc:

```vim
let g:vimtex_fold_preamble = 0
let g:vimtex_fold_documentclass = 1
```

I am happy with them as long as I am working on a multi-file tex project.
However, I also edit single tex files where I would like to have the default behaviour.

Is there a possibility to define an autocommand in my vimrc to change the options only
if a multi-file project was detected?

**Comment by lervag** [comment]
Hmm. I don't quite get what you are doing here, or why. I might just be slow (I often am). That is, in multi file projects, you only want the documentclass to be folded, not entire preamble. I presume this is because in this case, you have a master file that basically is just a preamble and include statements? While for single files, you want the preamble to be folded. Is this a correct understanding of your initial problem?

**Comment by kiryph** [comment]
Yes, you got it right. Sorry that I omitted my motivation and made this issue kinda cloudy what it is about.

I was thinking about a function `vimtex#multi_file_project_detected()`  containing checks for `b:vimtex_main`, `TEX root specifier`, `s:get_main_latexmain` and `s:get_main_from_specifier`.

**Comment by lervag** [comment]
Ok, so: How do we properly detect a multi-file project? Should I parse the entire tex project and search for `\include`s, `\input`s and related commands? I think this should be done after initializing the current buffer, and as such, unrelated to actually searching for the main file. But I think the logical thing to do is to add a function that parses the tex project to set some local options based on it. This would allow me to add some hooks for certain packages and similar, if I wanted to add package specific features at a later stage. What do you think?

**Comment by kiryph** [comment]
That does sound good.

However, I am wondering when folds are initialized and if it is too late changing vimtex options after parsing which affect the foldexpr.

**Comment by lervag** [comment]
I've now added simple document parsing to the initialization that sets `b:vimtex.sources` to a list that contains all LaTeX source files detected for the current project. You can use this to get your desired effect with:

```vim
autocmd User VimtexEventInitPost
      \  if len(b:vimtex.sources) > 1
      \|   let g:vimtex_fold_preamble = 0
      \|   let g:vimtex_fold_documentclass = 1
      \| endif
```

Note, you should put this in an autocommand group. I personally use FastFold, and it seems to work as desired without any other changes. You might need to do `zx` (in normal mode) to update the folds if you use the manual mode of folding that comes with vimtex.
