### ISSUE TITLE
Vimscript error on opening ToC in file using subfiles

### ISSUE THREAD

**Issue by gvdeynde** [lervag/vimtex#543]
### Explain the issue

opening the ToC with a subfiles multiple file project gives an error in vimscript because there is no space between lcd and the path. For example it gives me: 

lcdc:\users\gvdeynde\foo\bar

The ToC opens, though.

**Comment by lervag** [comment]
I found one place where there was a lack of that space, but I am not sure if it actually caused this issue. If it persists, please provide a minimal working example which will help me to reproduce your issue.

**Comment by gvdeynde** [comment]
I updated to latest version and the problem is solved... Thanks.

**Comment by lervag** [comment]
Great! :)
