### ISSUE TITLE
Multi-line error messages are truncated

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#545]
Multi-line error messages or warnings printed by some packages are truncated in the quickfix list. Sometimes this requires a manual compilation to understand the actual warning due to the missing information.

### Minimal working example

Download https://www.ctan.org/pkg/classicthesis and compile the main document in the root of the archive. I receive the following  truncated warning:

    ClassicThesis.tex|| Class scrreprt Warning: Usage of package `titlesec' together

This happens for me with neovim (using nvr), Texlive from Ubuntu 14.04 with an upgradet latexmk 4.45.

**Comment by lervag** [comment]
Thanks, I've added support for more packages. To be clear: There is no general way of doing this, so every package must be added explicitly. Don't hesitate to open new issues for new packages.

**Comment by languitar** [comment]
Thanks!

**Comment by lervag** [comment]
No problem! By the way, in case you are curious: A lot of the warning messages are related to package files. The line numbers are also typically related to these package files. However, it is very difficult (too difficult for me) to parse the latex log so as to get the correct file paths for package files, and thus to get the correct file and line info for the package warnings. Thus, only the message is parsed.

**Comment by languitar** [comment]
Thanks for the info. I was also wondering who ever invented logging in LaTeX. The format is a nightmare...

**Comment by lervag** [comment]
Partly agreed. The syntax is not really that bad, but the errorformat mini language in Vim is not good enough to parse the LaTeX logs. The log files are quite logically structured as a list structure based on parantheses. Each entry begins with something like `(filename...` and ends with `)`. Still, it ends up being very difficult to parse correctly, thus the limitations to vimtex for parsing the warnings and errors.
