### ISSUE TITLE
VimCompletesMe has Error message

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#547]
My `Vimrc`:

```vim
call plug#begin('$Vim/vim/plugged')
Plug 'lervag/vimtex'
Plug 'ajh17/VimCompletesMe'
call plug#end()

source $VIMRUNTIME/vimrc_example.vim

let g:tex_flavor                          = "latex"
let g:vimtex_latexmk_background           = 1
let g:vimtex_latexmk_options              = '-pdf' 
let g:vimtex_view_general_viewer 	  = 'SumatraPDF'
let g:vimtex_view_general_options	  = '-reuse-instance -inverse-search "\"' . $VIMRUNTIME . '\gvim.exe\" -n --remote-silent +\%l \"\%f\"" -forward-search @tex @line @pdf' 
let g:vimtex_view_general_options_latexmk = '-reuse-instance'

set fdm=syntax

" VimCompletesMe
augroup VimCompletesMeTex
	autocmd!
	autocmd FileType tex let b:vcm_tab_complete = "omni"
	autocmd FileType tex let b:vcm_omni_pattern = '\\(?:'
				\ . '\w*cite\w*(?:\s*\[[^]]*\]){0,2}\s*{[^}]*'
				\ . '|\w*ref(?:\s*\{[^}]*|range\s*\{[^,}]*(?:}{)?)'
				\ . '|hyperref\s*\[[^]]*'
				\ . '|includegraphics\*?(?:\s*\[[^]]*\]){0,2}\s*\{[^}]*'
				\ . '|(?:include(?:only)?|input)\s*\{[^}]*'
				\ . '|\w*(gls|Gls|GLS)(pl)?\w*(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
				\ . '|includepdf(\s*\[[^]]*\])?\s*\{[^}]*'
				\ . '|includestandalone(\s*\[[^]]*\])?\s*\{[^}]*'
				\ .')'
augroup END
```

I think the `VimCompletesMe` Plugin shall behaves like map `Tab` key to `Ctrl+X CTRL+O`, but if I type `\cite{<Tab>` there is an error message:

```
Error detected which processing function <SNR> 16_vim_completes_me:
line 19:
E871: (NFA regexp) can't have a multi follow a mult !
Press Enter or type command to continue
Error detected which processing function <SNR> 16_vim_completes_me:
E62: Nested \{
E220: Missing}
```

while `\cite{<Ctrl+x><Ctrl+o>` works well.

**Comment by vanabel** [comment]
After a long time investigation, I find that the problem is the pattern is not correct. It seems there are magic patten in vim and I don't know what's the default, what's more, the `:` seems nonsense in regular expression? I try to replace the pattern with
`
\v\\(\w*cite\w*(\s*\[[^]]*\]){0,2}\s*\{[^}]*)
`
It is not work (but fixed the error message), so I think there are some more issue of the `VCM` plugin itself. Since `\cite{<tab>` not complete as `omni` (even I add the `b:vcm_tab_complete = "omni"`) but as `filename`, which apprently no as desired by the local option of `b:vcm_omni_pattern`.

**Comment by lervag** [comment]
Can you try the following:

```vim
augroup VimCompletesMeTex
    autocmd!
    autocmd FileType tex let b:vcm_tab_complete = "omni"
    autocmd FileType tex let b:vcm_omni_pattern = '\v\\(?:'
                \ . '\w*cite\w*(?:\s*\[[^]]*\]){0,2}\s*{[^}]*'
                \ . '|\w*ref(?:\s*\{[^}]*|range\s*\{[^,}]*(?:}{)?)'
                \ . '|hyperref\s*\[[^]]*'
                \ . '|includegraphics\*?(?:\s*\[[^]]*\]){0,2}\s*\{[^}]*'
                \ . '|(?:include(?:only)?|input)\s*\{[^}]*'
                \ . '|\w*(gls|Gls|GLS)(pl)?\w*(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
                \ . '|includepdf(\s*\[[^]]*\])?\s*\{[^}]*'
                \ . '|includestandalone(\s*\[[^]]*\])?\s*\{[^}]*'
                \ .')'
augroup END
```

That is, add `\v` to the front of the pattern.

**Comment by lervag** [comment]
By the way: I took the liberty of cleaning your posted vimrc file (no need to include lines that have been commented, no need to include options that are already the defaults, and adding the vim syntax highlighting). I also notice you set the `g:vimtex_latexmk_options` variable. I'm curious why you did that, and why you are not using the default options?

**Comment by lervag** [comment]
I also have to ask: Why are you including the `source $VIMRUNTIME/vimrc_example.vim`?

**Comment by vanabel** [comment]
1. The 'quick' fix of you code by adding `\v` (I copy and paste your code in fact) still not work, the error message says that _maybe misplaced ?_
2. Thanks for your help of cleaning my `vimrc` posted here, I am not quite familiar with github and vim, the setting of `vimrc` is quite complicated to me, for example, after I change the `vimrc` and `:so %`, it seems some option is still not refreshed (but after I close and reopen `gvim` it works). So I don't know what's the real problem of my configuration.

The configure option of `latexmk` is needed since without is (at first try of `vimtex`) it is not working when I type `\ll`, maybe I am just do something wrong?
3. I have a look at `vimrc_example.vim` and it has the setting I needed, so it seems save my work of writing it myself? Do you mean it is the default setting and I needn't to include it here? If So, then

**Comment by lervag** [comment]
Regarding the original question: The documention explicitly states that you should use the same pattern for VimCompletesMe as for neocomplete. I just tried this, and it works flawlessly. For some reason, the pattern you used is _not_ the same as the one for neocomplete in the docs. The following works for me:

```vim
    autocmd FileType tex let b:vcm_omni_pattern =
        \ '\v\\%('
        \ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
        \ . '|hyperref\s*\[[^]]*'
        \ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|%(include%(only)?|input)\s*\{[^}]*'
        \ . '|\a*(gls|Gls|GLS)(pl)?\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . '|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . ')'
```

When you resource the vimrc file, it will not reset previously defined options. When you do `:source vimrc-file` (or `%` or whatever), it will run the file as vimscript. This will overwrite current settings, but it will not reset anything.

I think the default options should work. If it does not, then I think you are using an old version of latexmk. However, this might not be very important, and if the current option that you use does work, then that should be fine.

The point is that for a minimal vimrc file as the one you posted, including that line means anything might be added. I propose that you remove the `vimrc_example.vim` and instead add the lines that you find relevant directly to your vimrc file. Explicit is better than implicit.
