### ISSUE TITLE
Vimtex-toc: multi-line section/chapter names

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#548]
### Explain the issue

Parsing names for toc only works if placed on a single line.

I use a fixed text width of 78 characters which means sometimes line breaks are introduced in chapter/section titles. For example:

```latex
\documentclass[a4paper,11pt]{article}

\begin{document}
\chapter[Parsing names for toc only works if one line --- toc version]{Parsing
  names for toc only works if placed on a single line --- full version}
\end{document}

% vim: ft=tex tw=78 sw=2
```
Now the vimtex-toc looks like this:
```
  Preamble
1 Parsing
```
It should look like this
```
  Preamble
1 Parsing names for toc only work if placed on a single line --- full version
```

---
Notes:

- I think adding an option to use the shortened toctitle for vimtex-toc if available would be a nice option because the toctitles tend to be more cleaned up and of course making vimtex-toc matching the latex toc makes somewhat sense.
- support for `\texorpdfstring` in titles could cleanup the vimtex-toc as well

**Comment by lervag** [comment]
Three steps:

- [ ] Support multiple line section titles (and chapter, subsection, ...)
- [ ] Support using short versions/toc versions
- [ ] Support `\texorpdfstring`

Could you please explain how the `\texorpdfstring` command works?

**Comment by kiryph** [comment]
The `\texorpdfstring` command is part of the package `hyperref`.
This command is used most commonly in section or chapter strings when using hyperref to generate a pdf toc. The toc of pdfs does not allow you to put math or color into its entries. You would simply read `\section{\textcolor{red}{very important title}}`. So you can write `\section{\texorpdfstring{\textcolor{red}{very important title}}{very important title}` and your pdf toc would only contain the text not the latex markup.

The documentation of hyperref

> 4.1.2 Replacement macros
> hyperref takes the text for bookmarks from the arguments of commands like \section, which can contain things like math, colors, or font changes, none of which will display in bookmarks as is.
> `\texorpdfstring{TEXstring}{PDFstring}`

see also for example http://tex.stackexchange.com/questions/249107/how-to-use-texorpdfstring-characters-disappear.

**Comment by lervag** [comment]
Ok, I've added support for the short versions (as long as they are on the same line). Line breaks are, unfortunately, not as easy to handle. I'm looking for an elegant solution, and I might find one for the main section parts (not the short parts).

**Comment by lervag** [comment]
Ok, this has been implemented now. I think it works well, but I didn' stress test it. Let me know if you find any problems.

**Comment by kiryph** [comment]
Looks great!

However, multi-line support works only for `\chapter{multiline title}` but not for `\chapter[multiline toc-title]{multi-line title}`. I expect that this shouldn't be difficult to fix.

**Comment by lervag** [comment]
Just for making sure I understand right, could you provide a full example?

**Comment by kiryph** [comment]
A full example would be

```tex
\documentclass{article}

\begin{document}

\chapter[Short title]{Long title}

\chapter{Parsing {toc entries works
  also for} multi-line \texorpdfstring{stuff}{entries}
--- Hurray!}

\chapter[Parsing toc specific entries works 
  also for multi-line --- A second Hurray!]{Parsing {toc entries works
  also for} multi-line \texorpdfstring{stuff}{entries}
--- Hurray!}

\section{\texorpdfstring{\textcolor{red}{Very important title}} {Very important title}}

\section{Test section 1}
\end{document}
```
Opening the toc menu gives me which completely misses the third chapter:
![vimtex-toc-multiline-toc-title](https://cloud.githubusercontent.com/assets/371756/19589200/2cbef8ae-976b-11e6-9682-d8fcc3ee6c71.png)

**Comment by lervag** [comment]
It should work now.

**Comment by kiryph** [comment]
Yes, it works now. Thanks for this apparently non-trivial fix.

**Comment by lervag** [comment]
No problem. I did the main work yesterday, so it was actually quite straightforward.

Thanks for raising the issue; I think this was a clear improvement to the TOC feature.
