### ISSUE TITLE
Implement 'Open Command'

### ISSUE THREAD

**Issue by xerron** [lervag/vimtex#552]
Keybinding:  <localleader> lk

This command can open or follow a couple of commands, for example it is possible to open a subfile, open a citation for fast editing, or follow a ref cross reference to the corresponding label. The supported commands are:

\documentclass

Provides a list of the local documentations for the selected class, especially during the learning process of using a new class is this feature very handy and can save time to find the individual class documentation. The commando line tool “texdoc”  is used.

\usepackage

Provides a list of the local documentations for the selected package, especially during the learning process of using a new package is this feature very handy and can save time to find the individual package documentation. The commando line tool “texdoc”  is used.

\include, \input, \subfile

Just opens the used included LaTeX or bibliography file, very useful for big projects.

\cite, \nocite

Follows the selected citation by locating the item and open the bibliography file if available. The supported commands are the same like for the fill command of \cite commands, so check the correlated section for more informations.

\ref, \cref

Follows the selected cross reference by location the item and open the LaTeX file if available. The supported commands are the same like for the fill command of \ref commands, so check the correlated section for more informations.

\ac

Follows the selected abbreviation by location the abbreviation and open the LaTeX file if available. The supported commands are the same like for the fill command of \ac commands, so check the correlated section for more informations.

\label

Follows the use of the current label throughout the whole project. You can select a item from the list of just check the used locations and return to the origin by pressing escape.

**Comment by xerron** [comment]
For search all class:

``` bash
grep "\.cls" `kpsewhich --var-value TEXMFDIST`/ls-R > $HOME/allcls.txt
```

**Comment by xerron** [comment]
For list usepackages:

``` bash
ls `kpsewhich --var-value=TEXMFDIST`/doc/latex   
```

**Comment by lervag** [comment]
Sorry for not responding sooner!

So, this is a very comprehensive feature request. I want to split this into smaller pieces, else I will never feel "ready" to handle it.

First: I think `\include`s and similar are already working with the internal `gf` mapping through the `include'  option. See `:h include`.

Next, regarding citations, see #564 and `:h vimtex-faq-tags` and `:h vimtex-faq-tags-bibtex`.

Tags can be used to follow references as well with the following in your `.ctags` file:

```
--langdef=tex2
--langmap=tex2:.tex
--regex-tex2=/\\label[ \t]*\*?\{[ \t]*([^}]*)\}/\1/l,label/
```

Thus we are down to four. I would propose that you open separate issues for each of the four remaining commands and be specific on what feature you want. I can see the point of having a single mapping/command that works on different commands, but I want to consider that after having implemented the specific features first. I hope that is OK.

For each of the new issues, please describe the desired feature and how it should/could work.

**Comment by lervag** [comment]
Just to be clear: I think you are proposing something that might become a useful feature, but I want to implement it in smaller steps. By proposing the different parts through separate issues, you will make it much easier for me to tackle the implementation in a proper way.
