### ISSUE TITLE
Syntax hightlighting for natbib and biblatex seems to clash

### ISSUE THREAD

**Issue by tobson** [lervag/vimtex#554]
Syntax highlighting of natbib's `\citet` command looks like this on my machine:
![screen shot 2016-09-14 at 8 38 22 pm](https://cloud.githubusercontent.com/assets/2904505/18525039/42c88b32-7abb-11e6-84c1-45862cf659a8.png)
`\citep` looks the same. I have tested this with the minimal vimrc below. It works correctly if I remove [this](https://github.com/lervag/vimtex/blob/master/after/syntax/tex.vim#L79) line, i.e.
```
       \   '[Cc]ite%(title|year|date)?\*?',
```
from `after/syntax/tex.vim`. I then get:
![screen shot 2016-09-14 at 9 22 58 pm](https://cloud.githubusercontent.com/assets/2904505/18526594/74a1a732-7ac1-11e6-935b-79c791c201a8.png)

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
```

**Comment by lervag** [comment]
Thanks, for some strange reason I haven't noticed that myself. Fixed now.
