### ISSUE TITLE
In multiple files project, continuous compilation is disabled when closing one window.

### ISSUE THREAD

**Issue by rionda** [lervag/vimtex#555]
Consider a multiple file project: `main.tex` includes `1.tex` and `2.tex`.

1. Open `1.tex` and activate continuous compilation. 
2. Now do `:sp 2.tex`, do something there. 
3. Now, with the focus on `2.tex`, do `:q` to close the window (the buffer of `2.tex` is still open, just not shown). You now only see one window for `1.tex`. 
4. Write something in `1.tex`, then `:w`. You'll notice that continuous compilation is not active anymore.

**Comment by lervag** [comment]
Should be fixed now.

**Comment by rionda** [comment]
Yep, can't reproduce anymore.
