### ISSUE TITLE
Deoplete auto parenthesis in bib completion

### ISSUE THREAD

**Issue by petobens** [lervag/vimtex#556]
Consider the following minimal `init.vim` file:

```vim
let $DOTVIM = expand('$HOME/.vim')

execute 'set runtimepath+=' . expand(
            \ '$DOTVIM/bundle/repos/github.com/Shougo/dein.vim')

call dein#begin(expand('$DOTVIM/bundle/'))
call dein#add('Shougo/deoplete.nvim')
call dein#add('lervag/vimtex')
call dein#end()
filetype plugin indent on

set completeopt=menuone,preview,noinsert

" Custom settings
if dein#check_install(['deoplete']) == 0
    call deoplete#custom#set('_', 'converters',
        \ ['converter_auto_delimiter', 'remove_overlap',
        \ 'converter_auto_paren'])
endif
let g:deoplete#enable_at_startup = 1
if !exists('g:deoplete#omni#input_patterns')
    let g:deoplete#omni#input_patterns = {}
endif
let g:deoplete#omni#input_patterns.tex = '\\(?:'
    \ .  '\w*cite\w*(?:\s*\[[^]]*\]){0,2}\s*{[^}]*'
    \ . '|includegraphics\*?(?:\s*\[[^]]*\]){0,2}\s*\{[^}]*'
    \ . '|(?:include(?:only)?|input)\s*\{[^}]*'
    \ .')'
```

Now open the following `foo.tex` file:
```tex
\documentclass{article}

\usepackage{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}

\end{document}
```
and (as in the screenshot) write `\cite{` and once the popup menu select one of the entries with a date (such as `Doody (1974)`). You will see that vimtex completes to `\cite{doody(` instead of `\cite{doody`. Not sure if this is a problem with deoplete or vimtex. Any help is appreciated. Thanks in advance!
![screen shot 2016-09-15 at 18 48 20](https://cloud.githubusercontent.com/assets/2583971/18568740/049875ec-7b75-11e6-8eae-19e24724ef80.png)

**Comment by Shougo** [comment]
This is deoplete feature.
`'converter_auto_paren'` affects it.
Because the candidate abbr contains `()`.
You should disable it in omni source.

**Comment by petobens** [comment]
@Shougo  thanks.

**Comment by lervag** [comment]
@Shougo Thanks!
