### ISSUE TITLE
Problem in indentation

### ISSUE THREAD

**Issue by nrontsis** [lervag/vimtex#559]
Hi,

I noticed the following abnormal behaviour:

Suppose the following table-in-a-table piece of code:

```tex
\begin{tabular}{cc}
	\begin{tabular}{c}
		Cell 1
	\end{tabular} &
	\begin{tabular}{c}
		Cell 2
	\end{tabular}
\end{tabular}
```

When performing automatic indentation I end up with

```tex
\begin{tabular}{cc}
	\begin{tabular}{c}
		1
	\end{tabular} &
		\begin{tabular}{c}
			2
		\end{tabular}
\end{tabular}
```

Thanks for your time!

Nikitas

**Comment by nrontsis** [comment]
A (visually) similar problem:

```
\begin{equation}
	\begin{aligned}
		& \left(
		\begin{bmatrix}
			123
		\end{bmatrix} \right)
	\end{aligned}
\end{equation}
```

is indented as:

```
\begin{equation}
	\begin{aligned}
		& \left(
		\begin{bmatrix}
			123
	\end{bmatrix} \right)
\end{aligned}
\end{equation}
```

**Comment by lervag** [comment]
For some reason, I ignored lines with ampersands when getting the previous indentation. I could find why I did this, and so I removed it. I added your case as a test. If this was a feature, then I am sure someone will complain, and I can return the feature while making sure it does not break this example.

**Comment by nrontsis** [comment]
Great! Thanks a lot 👍

**Comment by nrontsis** [comment]
Actually the fix breaks the following:

```
\begin{equation}
	\begin{aligned}
		1 &
		& 2 \\
		3 &
		& 4 \\
	\end{aligned}
\end{equation}
```
is indented as:

```
\begin{equation}
	\begin{aligned}
		1 &
		  & 2 \\
		  3 &
			& 4 \\
		\end{aligned}
	\end{equation}
```

**Comment by lervag** [comment]
Thanks! I think I have fixed it now. The original code almost worked properly, but needed a minor modification.
