### ISSUE TITLE
Vimtex-TOC include tags

### ISSUE THREAD

**Issue by benutzer193** [lervag/vimtex#560]
### Explain the issue
The prepended included tags (Included bib file:, Vimtex included:, ...) take a lot of space in the TOC. For example if I have included bib files it's impossible to see the filename without resizing the vsplit.
I would propose to remove them and instead add a marker in the numbering column, like **v** for vimtex-include, **i** for included, **b** for bibfile and perhaps add a caption explaining the tags below or above the TOC.

**Comment by lervag** [comment]
I think this is a great suggestion. I'll add it when I get the time.

**Comment by benutzer193** [comment]
great!

**Comment by lervag** [comment]
How does this work for you?

**Comment by benutzer193** [comment]
very good! Thanks!
