### ISSUE TITLE
Shortcut for inserting items in list-like environments

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#563]
I have converted from vim latex suite to this plugin. One thing I am missing is the quite handy `Alt + i` shortcut for inserting items in all list-like environments (`itemize`, `description`, `enumerate`). Is there some way to get a similar thing vim vimtex?

**Comment by lervag** [comment]
I do have something similar, but not this exact mapping. See `:h vimtex-imaps` for more info on the similar kind of insert-mode mappings/shortcuts. For the `Alt + i` mapping, I personally use this:

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : 'é',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_trivial'
      \})
```

I have that in a personal `ftplugin/tex.vim` file, but you can also put it in an `after/ftplugin/tex.vim`.

**Comment by languitar** [comment]
Thanks for the explanations. I didn't know of this feature. But how would I map a modifier like Alt? Would that become the leader?

**Comment by lervag** [comment]
Typing `Alt + i` in insert mode produces `é`. So that's what you should use to map the modifier.

**Comment by languitar** [comment]
For me it just produces an `i` in neovim and nothing in plain vim.

**Comment by Rmano** [comment]
This is probably keyboard-configuration dependent. On my (Spanish modified) keyboard `Alt-i` produces just "i" (and the modifier `Alt-left`, which is swallowed by the window manager, I think) while `AltGr-i` (the right Alt key) produces "í".

You can try to use `xev` to dig out what a key is doing.

**Comment by lervag** [comment]
Ah, yes, this is slightly more complicated: In gvim, it works as I said (although @Rmano is right that it might also depend on the keyboard configuration). However, vim in terminals can't handle the `Alt` modifier. Neovim does, though, so for neovim, this should be possible. However, I don't know, and I haven't tried...

In any case, you can map whatever you want in the manner I showed previously, but what keys are available for mapping depends on several factors, such as which terminal you are using, if you are using vim or neovim, and what your keyboard configuration is.

Question: Did the `Alt + i` mapping work with vim/neovim in the terminal with latex-suite?

**Comment by languitar** [comment]
Yes, it worked with latex suite.

**Comment by lervag** [comment]
Strange. latex suite and vim in terminal? Or neovim? Which terminal?

**Comment by languitar** [comment]
latex suite in neovim in terminal

**Comment by lervag** [comment]
Ok. Could you try:

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : 'i',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_trivial'
      \})
```

Note: In the `lhs`, you should type `<c-v><alt-i>`. In my vim, this displays as `^[i`.

**Comment by languitar** [comment]
I also only get an `i` after this.

**Comment by languitar** [comment]
I actually have working mappings using alt defined this way:
```
nnoremap <A-h> <C-w>h
nnoremap <A-j> <C-w>j
nnoremap <A-k> <C-w>k
nnoremap <A-l> <C-w>l
inoremap <A-h> <Esc><C-w>h
inoremap <A-j> <Esc><C-w>j
inoremap <A-k> <Esc><C-w>k
inoremap <A-l> <Esc><C-w>l
```

**Comment by lervag** [comment]
But does `inoremap <A-i> ...` work?

**Comment by languitar** [comment]
The following mappins work:
```
inoremap <m-i> test
inoremap <A-i> test
```

When in ex mode, `Ctrl+V Alt+I` actually yields `<M-I>`. Only in insert mode it doesn't.

**Comment by lervag** [comment]
No, in insert mode it shouldn't work. Well, then,  this should work:

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : '<m-i>',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_trivial'
      \})
```

As mentioned early, you should put this in a dedicated `ftplugin` file.

**Comment by languitar** [comment]
Great this works.

Would be nice if there was some wrapper that could be parameterized to provide these mappings only when in certain environments.

**Comment by lervag** [comment]
That's an interesting request. It should be possible to implement. Could you open a new feature for this?

**Comment by languitar** [comment]
Done: #566

**Comment by lervag** [comment]
Thanks! :)
