### ISSUE TITLE
[feature] binding to get to citation

### ISSUE THREAD

**Issue by teto** [lervag/vimtex#564]
I couldn't find any mapping if there is any to jump from "\cite{mycitation}" to the matching citation in the .bib file ?
I tried gf ("goto file") and K (help) over the . As my \cite{} entries are correctly autocompleted, I guess there must be some way to provide such a binding ?

**Comment by lervag** [comment]
That's an interesting request. I think this looks useful, and I'll look into if it might be possible to implement.

Note: It might not be. Creating the autocomplete candidates was not too difficult, but finding the correct bib file and location of a given entry is the reverse problem, and I am not quite sure how easy it is to solve.

**Comment by lervag** [comment]
One simple solution is to perform a grep search (e.g. through vimgrep) for any `.bib` or `.tex` files that contain the desired entry (in `bib` files, it would be something like `@\w\+{[ENTRY]`, and in `tex` files it would be something like `\bibkey{[ENTRY]}` (from thebibliography environments)). It might not work in all cases, but I think it should work in most.

**Comment by teto** [comment]
The most natural workflow for me I guess would be to use the
(YouCompleteMe) "GoTo" command. Same for \ref{} jumping to \label.
Hence such a solution wouldn't be in vimtex but in YCM. There doesn't seem
to have a "tex" semantic completer hence maybe I should open the ticket
there instead.

2016-09-20 21:50 GMT+02:00 Karl Yngve Lervåg <notifications@github.com>:

**Comment by Konfekt** [comment]
You can hit Ctrl-] to jump to the tag in the bib file. This needs ctags, gutentags and an appropriately set .ctags file.

**Comment by lervag** [comment]
That's a very good point, @Konfekt. You don't really need anything but `ctags` for this, but [gutentags](https://github.com/ludovicchabant/vim-gutentags) is a brilliant way to get a lot out of tags.

I actually don't think I can implement this in any better way than what is possible through tags, and so I don't want to add more code for this. Perhaps I should address this in the docs, though? As a FAQ entry, perhaps? What do you think, @teto?

**Comment by Konfekt** [comment]
Thr following .ctags file should work:

```

--langdef=bibtex
--langmap=bibtex:.bib
--regex-bibtex=/@string\{([^ "#%')(,=}{]+)/\1/s,BibTeX-Strings/i
--regex-bibtex=/@(article|book|booklet|inbook|incollection|inproceedings|manual|masterthesis|misc|phdthesis|proceedings|techreport|unpublished)\{([^,]+),/\2/e,BibTeX-Entries/i
--regex-bibtex=/[[:space:]]*author[[:space:]]*=[[:space:]]*("([^"]+)"|\{([^\}]+)\})[[:space:]]*,?[[:space:]]*$/\2\3/a,BibTeX-Authors/i

```

**Comment by lervag** [comment]
Thanks! I've updated the docs.

**Comment by teto** [comment]
Thanks for the solution @Konfekt ! 
Apparently there is a solution for vim + YCM here https://github.com/Cocophotos/vim-ycm-latex-semantic-completer/issues/2 but I could not make it work with neovim. I might fix it if I get time.

**Comment by lervag** [comment]
@Konfekt May I ask, how do you set up gutentags for LaTeX?

**Comment by Konfekt** [comment]
The only setting is
```vim
let g:gutentags_project_root = ['.git', '.hg', '.bzr']
```

In doubt, have a look at my .config files at bitbucket.

**Comment by lervag** [comment]
Ok, thanks.

**Comment by Konfekt** [comment]
Upon rereading the gutentags help file, the following settings are recommeded:
```vim
let g:gutentags_project_root = ['.git', '.hg']

let g:gutentags_file_list_command = {
                              \ 'markers': {
                                  \ '.git': 'git ls-files',
                                  \ '.hg': 'hg locate',
                                  \ },
                              \ }
```
See also http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html

**Comment by Konfekt** [comment]
Upon rereading the gutentags help file, the following settings are recommeded:
```vim
let g:gutentags_project_root = ['.git', '.hg']

let g:gutentags_file_list_command = {
                              \ 'markers': {
                                  \ '.git': 'git ls-files',
                                  \ '.hg': 'hg locate',
                                  \ },
                              \ }
```
See also http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html
