### ISSUE TITLE
VimtexClean questions

### ISSUE THREAD

**Issue by hubanya** [lervag/vimtex#565]
Thank you again for this great plugin!

I recently noticed that `VimtexClean` no longer displays success messages. If I remember correctly, it did show a success status a few months ago. I looked into the code and I am confused by the code in the definition of `vimtex#latexmk#clean` (L160-L164 in `latexmk.vim`)
```
if !a:0 == 0
    call vimtex#echo#status(['latexmk clean: ',
          \ ['VimtexSuccess', 'finished' . (a:full ? ' (full)' : '')]])
endif
```
It seems that `VimtexClean` command only passes `<bang>` to the `vimtex#latexmk#clean` function. Therefore, success status message is in some sense "disabled" by the above `if` statement. In fact, if I comment out the `if` and `endif` line, `VimtexClean` will display a success message. Is "cleaning silently" the intended behavior?

Moreover, is it possible to add an option to specify additional suffixes for `latexmk` to clean? This can be done by using `latexmk`'s `$clean_ext` option.

Thanks!

**Comment by lervag** [comment]
Sorry, that was just a silly bug introduced when I generalized the function. Should be fixed now.

I'd prefer not to add to the complexity. Instead, I propose that you use a personal `~/.latexmkrc` file with the desired option. Personally, I have such a file that contains (among other things) the following:

```perl
push @generated_exts, "cb";
push @generated_exts, "cb2";
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "brf";
push @generated_exts, "nlg";
push @generated_exts, "nlo";
push @generated_exts, "nls";
push @generated_exts, "synctex.gz";
push @generated_exts, "run.xml";
```

This makes the clean command also remove files with the above endings.
