### ISSUE TITLE
Provide a wrapper for insert mode mappings which enables a mapping only in certain environments

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#566]
Drawing from # 563, I'd like to define an insert mode mapping for `Alt+I` which adds items to `itemize`, `description` etc. Since description always requires square brackets after `\item`, the mapping should ideally be different in that case. So I'd like to be able to declare something like this:

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : '<m-i>',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment(["itemize", "enumerate"])'
      \})
call vimtex#imaps#add_map({
      \ 'lhs' : '<m-i>',
      \ 'rhs' : '\item[',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment(["description"])'
      \})
```

This would require a wrapper and I don't know whether it is currently possible to bind the same mapping multiple times.

**Comment by lervag** [comment]
I think it could be done. Although I think the syntax must be something like:

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : '<m-i>',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment'
      \ 'args' : [["itemize", "enumerate"]],
      \})
```

This is because the `wrapper` entry is only the name of the function, and can not in itself contain the arguments. However, this is just a detail. I'll look at it when I get the time. As you may have noticed, there are a few issues at the moment, and this will not have the top priority. I hope to get to it in not too long.

**Comment by languitar** [comment]
No problem. It would just be convenient.

**Comment by languitar** [comment]
Btw. maybe there would be a better name than `wrapper`?

**Comment by lervag** [comment]
Suggestions?

**Comment by languitar** [comment]
I am not sure whether I understand all details, but so far, to me it looks like the existing functions define the `context` in which a mapping should operate. I see that the code would also allow to do arbitrary modifications to the returned values, but maybe it could be better to separate these two aspects. One for defining the context and, if required, a function to provide rhs instead of a string in case complex things are required.

**Comment by lervag** [comment]
Interesting remarks. The name `wrapper` is used because the idea is to allow any wrapper function over the `rhs` value for a given mapping. Thus, the name comes from the developer perspective, not the user perspective.

I'll think about this as I work on the new wrapper.

**Comment by languitar** [comment]
I understand this. But maybe functions to define the context are much more reusable in case they do not include potential user-specific modifications to the returned value.

**Comment by lervag** [comment]
Ok, I've implemented the feature. It seems to work well. Consider the following example:

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : '<m-i>',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment'
      \ 'context' : ["itemize", "enumerate"],
      \})
```

The current idea is that the context key contains context for the wrapper, in this case a list of environments to check against.

It remains to add documentation, but I'll wait until you've tested and we've discussed naming.

**Comment by lervag** [comment]
Ah, and I see at once that your original use case won't work, because the `lhs` is used as a context key. I think I can solve this by appending the `rhs` to the context key, though. I've just done this and pushed.

**Comment by languitar** [comment]
Thanks, this seems to work now :-)

**Comment by lervag** [comment]
Happy it works :)

I'll add the documentation when I get the time.

**Comment by languitar** [comment]
Did anything change for this in the meantime? Somehow my imaps do not work anymore.

**Comment by lervag** [comment]
No, this should still work. I've added nightly tests that are passing.

**Comment by languitar** [comment]
Ok, strange, then I need to find the reason for this.

**Comment by lervag** [comment]
Yes. You could try to copy your settings into a minimal vimrc file and a minimal example LaTeX file. If it still fails, you can open a new issue with the minimal example and I could test if I have the same experience here.
