### ISSUE TITLE
How to change \[ environment to numbered equation?

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#567]
I know that `cse` will change the current environment, but how to change the equation surrounded by `\[`and `\]` to numbered equation, i.e. to the form 
```latex
\begin{equation}\label{eq:<placeholder>}
 <equation contents>
\end{equation}
```

**Comment by lervag** [comment]
You can do `ci$`. You must add the label manually afterwords.

**Comment by vanabel** [comment]
Thanks, I suppose that you mean `cs$` instead.

**Comment by lervag** [comment]
Yes, sorry! :)
