### ISSUE TITLE
g:vimtex_view_use_temp_files regression

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#568]
### Explain the issue

In recent versions of vimtex when setting g:vimtex_view_use_temp_files to 1 and editing foo.tex the file foo.pdf is not copied to foo_vimtex.pdf anymore.

1. Steps to reproduce
Edit file foo.tex and do :VimtexCompile.

2. Expected behaviour
foo.pdf is created and then copied to foo_vimtex.pdf

3. Observed behaviour
foo.pdf is created but not copied to foo_vimtex.pdf

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass[12pt]{article}

\begin{document}

Test

\end{document}
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_latexmk_callback=1 " needed for zathura_alternative
let g:vimtex_view_use_temp_files = 1
let g:vimtex_view_method='zathura'
```

**Comment by lervag** [comment]
Thanks! And sorry for introducing that bug. I think it should work as expected now.

**Comment by heiderich** [comment]
Thank you. It seems to work again.

**Comment by lervag** [comment]
:)
