### ISSUE TITLE
Latexmk requires pdflatex options to be passed with parameter -pdflatex.

### ISSUE THREAD

**Issue by francisreyes** [lervag/vimtex#569]
### Explain the issue
latexmk will not take pdflatex options directly from the command line. they must be passed with -pdflatex="pdflatex -file-line-error -synctex=1 -interaction=nonstopmode"

Compilation of the minimal working example gives the following error. 

:!cd '/Users/francisreyes/test' && max_print_line=2000 latexmk -verbose -pdf -file-line-error -syn
ctex=1 -interaction=nonstopmode -e '$success_cmd = "'""'/Applications/VimR.app/Contents/Frameworks
/MacVimFramework.framework/Versions/A/Vim'""' --servername VIM --remote-expr \"vimtex#latexmk#call
back(1)\""' -e '$failure_cmd = "'""'/Applications/VimR.app/Contents/Frameworks/MacVimFramework.fra
mework/Versions/A/Vim'""' --servername VIM --remote-expr \"vimtex#latexmk#callback(0)\""' -e '$pdf
_previewer = "open"' 'test.ltx'
Latexmk: -file-line-error bad option
Latexmk: -synctex=1 bad option
Latexmk: -interaction=nonstopmode bad option

Latexmk: Bad options specified
Use
   latexmk -help
to get usage information

shell returned 10
latexmk compile: success     
 
### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

**Comment by lervag** [comment]
What are your vimtex settings? Which version of Vim are you on? Which version of latexmk?

**Comment by francisreyes** [comment]
Vim is using 7.4
LatexMK : 4.45
The only vimtex setting I have is to override vimtex_view_general_viewer to open Skim.app .

**Comment by lervag** [comment]
Hmm. Can you please test with a minimal vimrc file, as specified in the issue template? Also, please specify the minor version of Vim, or patch level. It is given as output to `:version`.

Post the minimal vimrc file here, and post a full description of how to reproduce.

**Comment by francisreyes** [comment]
Ah, I will withdraw, as I must have changed something in my setup that I can't get this bug anymore. apologies!

**Comment by lervag** [comment]
Ok, no problem. :)
