### ISSUE TITLE
Indent error for \left  and \right pair

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#570]
It seems that the indent  (select and then `=`)  act correct on 
```tex
\[
    \left| \Bigg\{ formula \Bigg\} \right|
\]
```
but fails on
```tex
\[
    \left. \Bigg\{ formula \Bigg\} \right|
\]
I think this is an issue, am I right?

**Comment by vanabel** [comment]
I get it on [this issue](https://github.com/lervag/vimtex/issues/510).

**Comment by nasenatmer** [comment]
To me it seems that `=` re-indents a part of code by referring to the [equalprog](http://vimdoc.sourceforge.net/htmldoc/change.html#=) function. However, `equalprog` is not set in vimtex, so the erroneous behaviour is caused by vim's internal indentation routine.

**Comment by lervag** [comment]
@vanabel I don't understand. `gg=G` works the same on both of your examples.

@nasenatmer No, `=` uses `indentexpr`, which set to `VimtexIndent` by vimtex.

**Comment by lervag** [comment]
@vanabel You should not use `\left|` and `\right|`. Instead, you should use `\left\lvert` and `\right\rvert`.

**Comment by lervag** [comment]
Also see [here](http://tex.stackexchange.com/questions/498/mid-vertical-bar-vert-lvert-rvert-divides).

**Comment by lervag** [comment]
Finally: If you do as I suggest above, I think everything should work as expected.

**Comment by vanabel** [comment]
Sorry, maybe my example code did not reproduce the problem. Try the following in `test.vim`:

```tex
\begin{align*}
	f(x)&=g\\
		&\leq\left. a \right\rvert\\
		&h
\end{align*}
\begin{align*}
	f(x)&=g\\
		&\left. for \right|\\
		&h
\end{align*}
```
do the first time `gg=G` gives

```tex
\begin{align*}
	f(x)&=g\\
			 &\leq\left. a \right\rvert\\
			 &h
\end{align*}
\begin{align*}
	f(x)&=g\\
			 &\left. for \right|\\
			 &h
\end{align*}
```
and the second time gives

```tex
\begin{align*}
	f(x)&=g\\
				&\leq\left. a \right\rvert\\
				&h
\end{align*}
\begin{align*}
	f(x)&=g\\
				&\left. for \right|\\
				&h
\end{align*}
```
you can see the output is not the same (the & indent again), so I think it is an issue. I will expect

```tex
\begin{align*}
	f(x)&=g\\
		&\leq\left. a \right\rvert\\
		&h
\end{align*}
\begin{align*}
	f(x)&=g\\
		&\left. for \right|\\
		&h
\end{align*}
```

**Comment by lervag** [comment]
With your example, everything works as expected for me. Please provide a minimal vimrc file that reproduces the issue.

**Comment by nasenatmer** [comment]
@lervag thanks for your clarification. I wasn't able to correctly understand vim's documentation.

**Comment by lervag** [comment]
No problem. However, I should add that `=` uses `equalprg` if it is set, but `equalprg` is not defined by default. It then uses `indentexpr`, but falls back to the internal method if this is also not set.

**Comment by vanabel** [comment]
I find the problem: I need to change

```vim
set sw=2 ts=2 bs=2
```

to 

```vim
set sw=2 sts=2 bs=2 noet 
```

This is solved by first minify the `vimrc` and then read the doc of these options one by one. Then in `:h ts`, I find the solution. Thanks for your suggestion.

**Comment by lervag** [comment]
Yes, this seems to explain your problems. One should choose either to use tabs or spaces for indentation, and then set the options accordingly.
