### ISSUE TITLE
Fold multiline [re]new command/environment[*]

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#571]
I'd like to propose following extensions for folding of command definitions:

- \newcommand{\cmd}[nargs][optargdefault]{defn}
- \newcommand*{\cmd}[nargs][optargdefault]{defn}
- \renewcommand{\cmd}[nargs][optargdefault]{defn}
- \renewcommand*{\cmd}[nargs][optargdefault]{defn}

Fold here the second mandatory curly argument `{defn}` to `{...}` and `[optargdefault]` to `[...]` if present.

and definition of environments
- \newenvironment{env}[nargs][optargdefault]{begdefn}{enddefn}
- \newenvironment*{env}[nargs][optargdefault]{begdefn}{enddefn}
- \renewenvironment{env}[nargs][optargdefault]{begdefn}{enddefn}
- \renewenvironment*{env}[nargs][optargdefault]{begdefn}{enddefn}

Fold here the second and third mandatory curly argument `{begdefn}{enddefn}` to `{...}{...}` and `[optargdefault]` to `[...]` if present.

A few typical examples:
i)
```latex
\renewcommand{\marginpar}{%
  \marginnote%
}
```
fold to
```latex
\renewcommand{\marginpar}{...}
```
ii)
```latex
\newcommand*{\StoreCiteField}[3]{%
  \begingroup
    \global\let\StoreCiteField@Result\relax
    \citefield{#2}[StoreCiteField]{#3}%
  \endgroup
  \let#1\StoreCiteField@Result
}
```
fold to
```latex
\newcommand*{\StoreCiteField}[3]{...}
```
iii)
```latex
\newenvironment{theo}[1][]{%
  \stepcounter{theo}%
  \ifstrempty{#1}{%
    \mdfsetup{
      frametitle={%
      \tikz[baseline=(current bounding box.east),outer sep=0pt]%
        \node[anchor=east,rectangle,fill=blue!20] {\strut Theorem~\thetheo};%
      }
    }%
  }%
  {% else ifstrempty:
  \mdfsetup{
    frametitle={
    \tikz[baseline=(current bounding box.east),outer sep=0pt]%
      \node[anchor=east,rectangle,fill=blue!20]{\strut Theorem~\thetheo:~#1};}%
  }
  }%
  \mdfsetup{
    innertopmargin=10pt,
    linecolor=blue!20,
    linewidth=2pt,topline=true,
    frametitleaboveskip=\dimexpr-\ht\strutbox\relax,
  }
  \begin{mdframed}[]\relax%
}{%
  \end{mdframed}%
}
```
fold to
```latex
\newenvironment{theo}[1][...]{...}{...}
```

**Comment by lervag** [comment]
I've implemented a solution that should work quite well. It does not have as intricate fold text as you asked for, but I think it should work quite well. Let me know what you think.

**Comment by kiryph** [comment]
Thanks again. Works very well for me. The more intricated folding text is not so important for me. It would be nice to have but does not limit the usefulness of the folds for me; as long as I can see what is folded.

**Comment by lervag** [comment]
Great. Then I'll leave this as it is. I agree that this is useful: thanks for the suggestion!

**Comment by kiryph** [comment]
I was trying to copy and adapt your commit for declare commands of biblatex:

```diff
diff --git a/autoload/vimtex/fold.vim b/autoload/vimtex/fold.vim
index a7898f4..8328760 100644
--- a/autoload/vimtex/fold.vim
+++ b/autoload/vimtex/fold.vim
@@ -29,6 +29,7 @@ function! vimtex#fold#init_options() " {{{1
   call vimtex#util#set_default('g:vimtex_fold_documentclass', 0)
   call vimtex#util#set_default('g:vimtex_fold_usepackage', 1)
   call vimtex#util#set_default('g:vimtex_fold_newcommands', 1)
+  call vimtex#util#set_default('g:vimtex_fold_biblatex_declare', 0)

   " Disable manual mode in vimdiff
   let g:vimtex_fold_manual = &diff ? 0 : g:vimtex_fold_manual
@@ -57,6 +58,8 @@ function! vimtex#fold#init_script() " {{{1
         \   'part',
         \   'usepackage',
         \   '%(re)?new%(command|environment)',
+        \   'Declare%(Multi|Auto)?CiteCommand',
+        \   'Declare%(Index)?%(Field|List|Name)%(Format|Alias)',
         \ ], '|') . ')'
 endfunction

@@ -188,6 +191,21 @@ function! vimtex#fold#level(lnum) " {{{1
     endif
   endif

+  " Fold biblatex declare commands
+  if g:vimtex_fold_biblatex_declare
+    if ( line =~# '\v^\s*\\Declare%(Multi|Auto)?CiteCommand\*?' ||
+          \ line =~# '\v^\s*\\Declare%(Index)?%(Field|List|Name)%(Format|Alias)\*?' )
+          \ && indent(a:lnum+1) > indent(a:lnum)
+      let s:biblatex_declare_indent = indent(a:lnum)
+      return 'a1'
+    elseif exists('s:biblatex_declare_indent')
+          \ && indent(a:lnum) == s:biblatex_declare_indent
+          \ && line =~# '^\s*}\s*$'
+      unlet s:biblatex_declare_indent
+      return 's1'
+    endif
+  endif
+
   " Fold chapters and sections
   for [part, level] in b:vimtex_fold.parts
     if line =~# part
@@ -299,6 +317,16 @@ function! vimtex#fold#text() " {{{1
           \ '\v^\s*\\%(re)?new%(command|environment)\*?\{[^}]*\}') . ' ...'
   endif

+  " Text for biblatex declare commands
+  if g:vimtex_fold_biblatex_declare
+    if line =~# '\v^\s*\\Declare%(Multi|Auto)?CiteCommand'
+      return matchstr(line,
+            \ '\v^\s*\\Declare%(Multi|Auto)?CiteCommand\*?\{[^}]*\}') . ' ...'
+    if line =~# '\v^\s*\\Declare%(Index)?%(Field|List|Name)%(Format|Alias)'
+      return matchstr(line,
+            \ '\v^\s*\\Declare%(Index)?%(Field|List|Name)%(Format|Alias)\*?\{[^}]*\}') . ' ...'
+  endif
+
   " Text for documentclass
   if g:vimtex_fold_documentclass && line =~# '^\s*\\documentclass'
     return '\documentclass[...]{'
```
But for some reason this has side effects on other folds. Do you know what is wrong?

```tex
\documentclass{article}

\begin{document}
\frontmatter
\tableofcontents
\mainmatter
\chapter{introduction}
\section{section}
\backmatter
\chapter{Appendices}
\end{document}
```
is folded to 
```
\documentclass{article}

\begin{document}
0------------------
0------------------
0------------------
\end{document}
```
Instead of
```
\documentclass{article}

\begin{document}
    Frontmatter
    Mainmatter
    Backmatter
\end{document}
```

**Comment by kiryph** [comment]
A missing `endif` in the `vimtex#fold#text` function was the problem:
```diff
@@ -299,6 +316,17 @@ function! vimtex#fold#text() " {{{1
           \ '\v^\s*\\%(re)?new%(command|environment)\*?\{[^}]*\}') . ' ...'
   endif

+  " Text for biblatex declare commands
+  if g:vimtex_fold_biblatex_declare
+    if line =~# '\v^\s*\\Declare%(Multi|Auto)?CiteCommand'
+      return matchstr(line,
+            \ '\v^\s*\\Declare%(Multi|Auto)?CiteCommand\*?\{[^}]*\}') . ' ...'
+    elseif line =~# '\v^\s*\\Declare%(Index)?%(Field|List|Name)%(Format|Alias)'
+      return matchstr(line,
+            \ '\v^\s*\\Declare%(Index)?%(Field|List|Name)%(Format|Alias)\*?\{[^}]*\}') . ' ...'
+    endif
+  endif
+
   " Text for documentclass
   if g:vimtex_fold_documentclass && line =~# '^\s*\\documentclass'
     return '\documentclass[...]{'
```

**Comment by lervag** [comment]
Sorry, I haven't had time to look at this yet. If you got it working, please feel free to submit a pull request. I think this looks useful enough.

**Comment by kiryph** [comment]
Mmh, I am not sure about it. It can be useful but possibly only for a significant smaller fraction of vimtex-user. In contrast `newcommand/newenvironment` are very common. Another concern is that extending the folding expression of vimtex should be done in a more general way having in mind different needs of each individual user:

## **Folding According to Pre-Defined Patterns**
I would propose to create typical folding patterns consisting of a default list of commands which will be folded according to the same pattern:

Pattern 1: *Command with a long list of options on several lines and one short final mandatory argument*  
`\usepackage[...]{amsmath}`, `\includepdf[...]{mydoc.pdf}`

`let g:vimtex_folding_pattern1_cmd_list = [ 'usepackage', 'includepdf' ]`

Pattern 2: *Command with one single mandatory argument on several lines*  
`\hypersetup{...}`

`let g:vimtex_folding_pattern2_cmd_list = [ 'hypersetup']`

Pattern 3: *Command with two or more mandatory arguments with first short mandatory argument*  
`\presetkeys{todonotes} ...`, `\renewcommand{\emph} ...`, `\newenvironment{\theo} ...`

`let g:vimtex_folding_pattern3_cmd_list = [ 'presetkeys', 'newcommand', 'renewcommand', 'newenvironment', 'renewenvironment' ]`

Star versions could always be implicitly recognized.

And if possible, the list entries could be regexes: `%(re)?new%(command|environment)` or `Declare%(Multi|Auto)?CiteCommand`

## **Folding of Manual Markers**  
Another feature request regarding folding, which is not related to above, is support for manual markers. Have a look at https://github.com/matze/vim-tex-fold what I mean.

**Comment by lervag** [comment]
Could you open a new issue for the manual marker suggestion? I think we can continue the remaining discussion in your pull request #589, and with that consider this issue to be closed and finalized. Unless I missed something?
