### ISSUE TITLE
latexmk.vim refers to possibly undefined g:vimtex_view_automatic variable

### ISSUE THREAD

**Issue by Coacher** [lervag/vimtex#575]
Hello.

I have `g:vimtex_view_enabled` set to 0, so ` g:vimtex_view_automatic` is never defined: https://github.com/lervag/vimtex/blob/master/autoload/vimtex/view.vim#L11
Then I enable latexmk continuous mode via `VimtexCompileToggle` and get error due to undefined variable because of this: https://github.com/lervag/vimtex/blob/master/autoload/vimtex/latexmk.vim#L598

Please fix.

**Comment by lervag** [comment]
Sorry about that. Fixed now. Thanks for reporting!

**Comment by Coacher** [comment]
Nice. Thanks!

**Comment by Coacher** [comment]
I guess the change wasn't tested as now I have:
```
Error detected while processing function vimtex#latexmk#toggle[4]..vimtex#latexmk#compile[11]..<SNR>124_latexmk_build_cmd:
line   38:
E716: Key not present in Dictionary: viewer, 'xwin_id', 0) > 0 || get(s:, 'silence_next_callback', 0)
E116: Invalid arguments for function get(b:vimtex.viewer, 'xwin_id', 0) > 0 || get(s:, 'silence_next_callback', 0)
E15: Invalid expression: !get(g:, 'vimtex_view_automatic', 1) || get(b:vimtex.viewer, 'xwin_id', 0) > 0 || get(s:, 'silence_next_callback', 0)
```

**Comment by Coacher** [comment]
My vimtex config:
```
let g:vimtex_imaps_enabled = 0
let g:vimtex_labels_enabled = 0
let g:vimtex_toc_enabled = 0
let g:vimtex_view_enabled = 0
let g:vimtex_indent_enabled = 0
let g:vimtex_indent_bib_enabled = 0
```

**Comment by lervag** [comment]
It was actually another problem. It is fixed now.

**Comment by Coacher** [comment]
I can confirm this is fixed completely now. Thank you.

**Comment by lervag** [comment]
Great! Happy to hear it works! :)
