### ISSUE TITLE
[request] Add an ability to delete junk TeX files (.log, .aux, etc.) on exit

### ISSUE THREAD

**Issue by Coacher** [lervag/vimtex#576]
Hello.

I know about `-output-directory` option for `latexmk`. This isn't a suitable solution as I want pdf to stay and I don't want to be bothered with setting up symlinks or additional directories every time.
I also don't want to be bothered with any Makefiles like some people suggest to do.

`latexmk -c` already does almost a perfect job removing those junk files. The only thing it has problems with is `*.synctex.gz`, but it can be workarounded by manual handling of these files. latexmk upstream chose not to delete synctex stuff with `-c`, but it references `.aux`, which gets removed with `-c`, so it is kind of pointless to keep synctex.

Considering `latexmk` already supports this, a simple autocommand listening for buffer unloads should be enough.

Please add this feature.

**Comment by lervag** [comment]
There is already a mapping for cleaning files through `latexmk -c`, by default mapped to `\lc`. `\lC` deletes all generated files (as `latexmk -C`).

Instead of updating or adding to this feature, instead I suggest that you create/update your `.latexmkrc` file. Here you can specify which files should be cleaned up. E.g., I personally use the following content in my `~/.latexmkrc` file:

```perl
push @generated_exts, "cb";
push @generated_exts, "cb2";
push @generated_exts, "spl";
push @generated_exts, "nav";
push @generated_exts, "snm";
push @generated_exts, "tdo";
push @generated_exts, "nmo";
push @generated_exts, "brf";
push @generated_exts, "nlg";
push @generated_exts, "nlo";
push @generated_exts, "nls";
push @generated_exts, "synctex.gz";
push @generated_exts, "run.xml";
```

This will effectively remove all of the files with the above extensions when I do `latexmk -c` or `\lc`.

**Comment by Coacher** [comment]
I can run it manually, yes. The point is not having to run anything. Similarly like continuous mode compiles pdf for me, I would much appreciate if vimtex could clean up its own mess on exit.

**Comment by lervag** [comment]
Ah. I don't want to add that. But I have already added a mechanism that you can use to get the effect, see `:h VimtexEventQuit`. Specifically, you can add the following to your vimrc to achieve your desired feature:

```vim
augroup MyVimtex
  autocmd!
  autocmd User VimtexEventQuit call vimtex#latexmk#clean(0)
augroup END
```

However,  I noticed while testing this that it is not perfect. In particular, it does not seem to work unless you first stop compilation. I'll look into this and see if I can find a better implementation.

**Comment by Coacher** [comment]
> I don't want to add that.

May I ask why? At least having it as a configurable, optional behaviour would simplify things IMHO.

> Specifically, you can add the following to your vimrc [...]

This is pretty much what I did locally, except I wasn't aware of `VimtexEventQuit` event and used Vim default ones instead. Thanks.
>  I'll look into this and see if I can find a better implementation.

This would be nice.

**Comment by lervag** [comment]
Why: Because I already have a mechanism that (should) work. So, perhaps I should have rephrased it and said just that. But as I also said, I need to improve the mechanism. In the end, I want you to be able to write something like:

```vim
...
autocmd User VimtexEventQuit VimtexClean
```

But right now, the commands are not available when the event triggers.

In any case, I hope you agree that this mechism is more than strong enough for your needs. The point of it all is: I don't want to add more options. There are already way too many options.

**Comment by Coacher** [comment]
> In any case, I hope you agree that this mechism is more than strong enough for your needs.

I agree. I was able to solve this problem locally with the functionality already provided by vimtex.
The way described above is even mentioned in docs, but I failed to find it searching for 'remove', 'junk', and 'auxiliary'. Turns out `VimtexClean*` commands have a typo in the description, which prevented me to find them: 'auxilliary' (notice the double 'l').

> I don't want to add more options. There are already way too many options.

There are lots, yes ;)

**Comment by lervag** [comment]
Ok, I've looked into this, but I can't really find a better way to detect when a vimtex project is quit. There does not seem to exist an internal event that fires when a buffer is removed, but before it is unloaded. The closest is `BufWinLeave`, it seems, but this does not really imply that the buffer is being deleted.

Thus, I think we are restricted to a case where only the functions are available. Still, all functionality is still present, it only means that it becomes somewhat more complicated to add such configurations.

**Comment by postylem** [comment]
I have the following line in `~/.latexmkrc` which makes `latexmk -c` (and therefore `\lc`) clean up the files with the listed extensions. 

```
$clean_ext = 'synctex.gz synctex.gz(busy) run.xml tex.bak bbl bcf fdb_latexmk run tdo xdv %R-blx.bib'
```
Compared to what @lervag described using `@generated_exts` [above](https://github.com/lervag/vimtex/issues/576#issuecomment-250087161), I'm not sure if this is a worse approach, a better one, or equivalent, for the purpose, but I did notice that `push @generated_exts, "bbl";` will not remove a .bbl file, but including it in the list of `$clean_ext` does.

**Comment by lervag** [comment]
This is documented in [the latexmk manual](https://ctan.uib.no/support/latexmk/latexmk.pdf). `$clean_ext` is documented on page 27, and `@generated_exts` is documented on page 32 (as of today, 2021-03-29). Notice that `bbl` is in the list by default and for me, the `.bbl` file is already automatically deleted by default with `latexmk -c`. Both alternatives are valid ways to achieve this, but it is probably a good idea to read the manual :)
