### ISSUE TITLE
vimtexview for skim

### ISSUE THREAD

**Issue by dragonxlwang** [lervag/vimtex#578]
In
https://github.com/lervag/vimtex/blob/master/doc/vimtex.txt#L884

-r option was used. However, recently I find it causes problem in highlighting
when forward searching. It seems after remove this option, I can still highlight
the line. According to skim, it asks to turn off sync option in skim when using
-r option. However, I thought I need to turn it on in order to update pdf in skim
continuously.

There is still a minor problem --- Before, I can highlight the current line in Skim
in green together with the current position highlighted in a red dot. However,
now I couldn't have it no matter how I try...

Would greatly appreciate if someone can help!

**Comment by tdi** [comment]
@dragonxlwang I am curious because I also use skim. How do you use the forward search ? Did you have to do some additional steps to make it work ? Because for me `\lv` just focuses skim and that is it.

**Comment by lervag** [comment]
I'm really sorry that I can't help you with this. I don't use macOS/OSX, and thus I can't work with Skim and the Skim settings. The documentation is purely based on input from other users.

I will keep the issue open for the time being, perhaps someone else could be of assistance. If noone participates, then I'd suggest that you ask on reddit or something similar.

If you should happen to find better Skim settings for vimtex, please don't hesitate to let me know. I could update the docs.

**Comment by dragonxlwang** [comment]
Thanks Karl!

Do you have any specific reason that you want to use “-r” option?

The documentation of skim only says that to use “-r” when not syncing.

Thus I believe it would make more sense to remove the “-r” option for now.

Let me know what you think about this.

Thanks,

**Comment by lervag** [comment]
The reason I use `-r` is because someone else suggested it. Perhaps it was bad advice. In any case, I found the following pages:

https://atom.io/packages/skim-displayline

**Comment by dragonxlwang** [comment]
-b option changes how it was highlighted in Skim. I don't find it particular useful. 

My current setting is without any options (neither -r or -b)

I found that the skim's forward search highlight behavior changed after recent update. 

Before, when forward searching, it would highlight current line in green together with a red dot showing current location, which was great! At that time, I used the -r option.

Now, it would only highlight current line in green if I don't use -r option. Otherwise, it does not highlight anything at all.

However, I am not sure what exactly caused the change. I have used the old version of vim/vimtex/skim, and it still does not get back old behavior. I suspect that it might related to the mac os update  sierra recently.

**Comment by lervag** [comment]
I am sorry that I can't help you more with this. But I am definately sure that this is not due to vimtex. There is no special vimtex code for Skim, only the options you provide. Thus I think you are probably right it has to do with the macOS update. :\
