### ISSUE TITLE
precise forward search with zathura

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#580]
### Explain the issue

1. Steps to reproduce

Use forward search with zathura.

2. Expected behaviour

Zathura moves to the precise position corresponding to the cursor in the .tex document and highlights it.

3. Observed behaviour

Zathura moves to the top of the page of the position mentioned in 2.

Am I doing something wrong? Is this supposed to work as I wish?

**Comment by lervag** [comment]
Strange. This works as expected for me. Could you provide some more details, including the version of Zathura, which Linux distribution you are on and version, etc.

**Comment by heiderich** [comment]
I am using this on an Ubuntu 16.04 box. The versions of vim and zathura are:

$ dpkg -l vim zathura zathura-pdf-poppler
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                Version                        Architecture                   Description
+++-===================================================-==============================-==============================-============================================================================================================
ii  vim                                                 2:7.4.1689-3ubuntu1.1          amd64                          Vi IMproved - enhanced vi editor
ii  zathura                                             0.3.5-1                        amd64                          document viewer with a minimalistic interface
ii  zathura-pdf-poppler                                 0.2.6-1                        amd64                          PDF support for zathura

**Comment by lervag** [comment]
I'm using zathura with the mupdf backend, but I did not think that should have any impact. You could try that, though. I would guess you can install it with `sudo apt install zathura-pdf-mupdf`.

Except for that, I don't understand why you have this problem. As I said, everything works fine here.

Perhaps you could try to do the forward searches manually from the terminal and see if that helps? I.e., compile a LaTeX document (WITH synctex enabled), open the pdf with zathura, then do something like

```
zathura --synctex-forward LINE:COLUMN:TEXFILE PDFFILE
```

You could also do `zathura -h` and verify that it has the synctex features.

Note: Some time ago, zathura decoupled the synctex module, which means that the distribution managers have to have `libsynctex` installed in order for synctex support to be included when they make the zathura packages. If your zathura does not have synctex features, then I think you can fix this by installing it manually from the source. You can probably find a lot of information about this by searching for "zathura synctex".
