### ISSUE TITLE
Set quickfix title

### ISSUE THREAD

**Issue by teto** [lervag/vimtex#581]
Plugins I use tend to set the quickfix title to the command they ran (vim-grepper, fzf.vim for instance). It makes things easier to understand/replicate.
When using vimtex, I see "`Quickfix  :setqflist() `" on neovim but that should be the same on vim I guess.

**Comment by lervag** [comment]
I was not aware that we could do this. I did not find anything about this in the mentioned plugins, but I did find a clue that helped me solve it. In any case, thanks for the suggestion.

**Comment by teto** [comment]
Thanks for taking it into account !

2016-10-01 9:37 GMT+02:00 Karl Yngve Lervåg <notifications@github.com>:

**Comment by lervag** [comment]
My pleasure :)
