### ISSUE TITLE
Append to the default options in vimtex_latexmk_options

### ISSUE THREAD

**Issue by phcerdan** [lervag/vimtex#583]
I just want to add the option `-shell-scape` to latexmk.
The way to do it, as documented in `vimtex` is throug `g:vimtex_latexmk_options`
My issue is that I am happy with the vimtex defaults, I only want to append one extra option, not rewrite the default options (pdf, interaction=nonstop, etc)

If this is not easy, what are the default options for using luatex with the default options plus `shell-scape`

My try has been:
```
let g:vimtex_latexmk_options='-file-line-error -verbose -pdf -interaction="nonstopmode" -pdflatex="lualatex -synctex=1 -shell-escape \%O \%S"'
```
but still complaining about no `shell-scape`, even though it uses lualatex.

**Comment by lervag** [comment]
If you see the note in the docs for the option (`:h g:vimtex_latexmk_options`), I recommend that you configure for lualatex either in a global or project local `.latexmkrc` file. E.g., you can use:

```perl
$pdflatex = 'lualatex -synctex=1 --shell-escape %O %S';
```

This will keep the default options as specified by vimtex (on the `latexmk` command line), but it will use your `pdflatex` settings.

**Comment by phcerdan** [comment]
It works perfect. Thanks

**Comment by lervag** [comment]
No problem :)
