### ISSUE TITLE
dsc does not remove brackets

### ISSUE THREAD

**Issue by sbechtel** [lervag/vimtex#584]
dsc does not work as espected. The \command part gets removed but the brackets remain.

### Minimal working example

```tex
\begin{document}
	\emph{foo}
\end{document}
```
I do dsc when the cursor is on foo. Expected output is

```tex
\begin{document}
	foo
\end{document}
```

but I get

```tex
\begin{document}
	{foo}
\end{document}
```

### Minimal vimrc file

I just load vimtex via Vundle...

```vim
" I want vim, not vi
set nocompatible
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" My Bundles here:
Bundle 'lervag/vimtex'

filetype plugin indent on     " required!
```

**Comment by lervag** [comment]
This is actually a little bit tricky. It is (at least near) impossible to determine arguments for a command. For instance, let's say you write this: `\alpha {test}`. Is `{test}` and argument? No, not in this case. But obviously it is in `\emph {test}`.

That's why I chose to only delete the actual command specifier, but not the surrounding brackets.

**Comment by sbechtel** [comment]
I understand your point. [In a previous comment](https://github.com/lervag/vimtex/issues/245#issuecomment-147861067) you've putted the bracket removal on your todo list, therefore I thought that it is a bug. However I think that in most cases the user wants the brackets to be removed, only when writing about programming I can consider situations where I want the brackets to be part of the argument. Maybe it would be possible to add an option to let the user decide which behaviour he prefers?

**Comment by lervag** [comment]
Ok, I'm convinced. Can't argue with myself, either. I don't know why I had checked the box but not actually completed the implementation.

In any case, now `dsc` removes brackets as long as there is a single argument. I does not do anything when there are more arguments.

**Comment by lervag** [comment]
By the way, thanks for reporting the problem. Note that I also fixed a minor issue with the cursor position after the `dsc` command.
