### ISSUE TITLE
Add folding of manual markers

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#590]
Tex files can be quite messy. Folding can help to organize code and to get easily a "bird's eye" view of the code by folding major parts. A simple fold of the whole preamble can be too coarse. However, an automatic granular approach to fold parts of the preamble is not easily possible.

Adding support for manual fold markers allows the user to structure the code into additional folds. For example

```tex
%{{{ Packages
\usepackage{hyperref}
%}}}
```

There is another vim plugin only for folding of tex, called ['vim-tex-fold'](https://github.com/matze/vim-tex-fold), which supports this.

What do you think? I think this a manageable addition to vimtex folding (possibly in contrast to my pull request #589).

This feature request was already mentioned in #571.

**Comment by lervag** [comment]
I think that should do it. I didn't add any fold text parsing. Not quite sure how it should look. Perhaps something like `{{{ Title`, that is, strip any leading part of the string before the `{{{`?

**Comment by kiryph** [comment]
I think following the behavior of the builtin `fold-marker` would be one option for the fold text.

This would mean
```tex
% Packages {{{
\usepackage{hyperref}
% }}}
```
is folded to
```tex
% Packages -----------------
```

One could even add support for markers of different fold level. However, I think this is more complicated and IMHO it is unclear how this fit into the other folds.

**Comment by lervag** [comment]
I'm not saying unnamed folds, just that the fold text should not hide the `{{{` part. Because it makes it difficult to separate from other types of folds.

Btw: The current version will not fold `% Packages {{{`, beause it assumes the fold title comes after `{{{`. Should I fix that?

**Comment by kiryph** [comment]
I think it would be better to follow the built-in pattern: fixing this would make it more consistent.

Once again thanks for this commit. I really like this. Now my preamble folds nicely into
- documentclass with options
- Packages
- Commands & Environments
- Settings

Even more complex tex files fold into one screen length which helps me navigating faster with less distraction of lines I do not care right now about (and eventually forget what they mean :relieved:)

**Comment by lervag** [comment]
But what is the built-in pattern? Hmm... perhaps I can just use `foldtext()`?

**Comment by lervag** [comment]
Could you test the most recent version?

**Comment by kiryph** [comment]
Yes, now I can place the foldtext before or after the `{{{`. I think it is intuitive that the text between the `{{{` and `}}}` is folded. Therefore I would place the foldtext in front of the opening `{{{`.

As far as I understand vim's documentation, the [foldtext](http://vimhelp.appspot.com/fold.txt.html#fold-foldtext)  is determined by [`foldtext()`](http://vimhelp.appspot.com/eval.txt.html#foldtext%28%29) function for [`fold-markers`](http://vimhelp.appspot.com/fold.txt.html#fold-marker) which can be customized by the [user](http://dhruvasagar.com/2013/03/28/vim-better-foldtext) by `set foldtext=NeatFoldText()` .

Minor things:
- remove `%` and `{{{` as the default foldtext does and to match your style of other folds

```
FOLDTEXT                                                fold-foldtext

'foldtext' is a string option that specifies an expression.  This expression
is evaluated to obtain the text displayed for a closed fold.  Example: 

    :set foldtext=v:folddashes.substitute(getline(v:foldstart),'/\\*\\\|\\*/\\\|{{{\\d\\=','','g')

This shows the first line of the fold, with "/*", "*/" and "{{{" removed. 
```
- I would prefer a different style which follows my suggestions regarding folding documentclass and package options. I would try to make the foldtext to look like code and avoiding jumping text when opening or closing folds. I know that the default foldtext does this as well by prefixing `+-- <text>` (where the dashes represent the fold level). There is no right or wrong, only consistency within vimtex would be desirable. If you are happy with your existing foldtexts, I would actually change the foldtext of the documentclass and usepackage,  
`<indent>Documentclass: article --------` instead of `\documentclass[...]{scrreprt} ------` and  
 `<indent>Package: inputenc -------------` instead of `\usepackage[...]{inputenc} ---------`.

**Comment by lervag** [comment]
Ok, just to make sure I understand: Does this mean you are happy with the current fold feature? Or did you have further suggestions for improving?

**Comment by kiryph** [comment]
I am happy with the folding right now (except for my pull request #589 which however needs more work;  I simply use the proposal in my local vimtex version).

Thanks for checking back.

**Comment by lervag** [comment]
Great, thanks! I have the PR on my list; if I get the time I might propose a solution to that myself, but as you see, I don't have much time of late. I am just barely able to keep the issue count down...
