### ISSUE TITLE
ultisnips auto-trigger

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#591]
this is just a heads-up on a feature of ultisnips which i think is new (i discovered it only recently). 

it's called auto-expansion. one can define snippets which will get triggered automatically, without typing the trigger key (<c-j>). the advantage over the anonymous snippets is that one can now consistently jump out of nested snippets by hitting <c-j>. it really seems overall better than anonymous snippets -- maybe the vimtex docs could point to this instead?

an example (the A is for auto-expansion)
```
snippet {{ "double curly" iA
{$1}$0
endsnippet
```

**Comment by lervag** [comment]
Thanks! This makes me want to switch back to UltiSnips from neosnippet.
