### ISSUE TITLE
several main LaTeX files

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#599]
It seems that vimtex does not detect the main file correctly when \input{filename} is used instead of \input{filename.tex}. It would be nice if they could be detected.

Furthermore, in a situation where multiple latexmain files are found (say main1.tex.latexmain and main3.tex.latexmain exist in the example below), it would be nice to be able to switch easily between them, similarly to :VimtexToggleMain, but not only between a detected main file and the current one, but rather between all detected main files (probably one would have to restrict the "all detected main files" somehow).

### Steps to reproduce

Suppose you have files main1.tex, main2.tex and main3.tex, where main1.tex and main2.tex contain a line
```tex
    \input{inc.tex}. 
```
while main3.tex contains the line
```tex
    \input{inc}
```
Create an empty file main3.tex.latexmain. Suppose that main1.tex.latexmain and main2.tex.latexmain do not exist.
Open inc.tex in vim and call VimtexCompile.

### Expected behaviour

I expect that main3.tex will be compiled.

### Observed behaviour

main1.tex gets compiled.

When I create main2.tex.latexmain the file main2.tex will be compiled. The issue seems to be related to the missing extension ".tex" in \input.

### Minimal working example

The following file for main1.tex and main2.tex works:

```tex
\documentclass[12pt]{article}

\begin{document}

\input{inc.tex}

\end{document}
```

The following file for main3.tex causes the problem (it is not detected as main latex file):

```tex
\documentclass[12pt]{article}

\begin{document}

\input{inc}

\end{document}
```

**Comment by lervag** [comment]
The latest commit fixes the main issue.

Regarding the feature request of choosing the correct `latexmain` file: You can achieve the desired effect relatively easily by updating the latexmain file and then reloading vimtex with `\lx`.

For example, consider the following files:

```
> tree
.
├── input.tex
├── main1.tex
├── main1.tex.latexmain
├── main2.tex
└── main3.tex
```

Now open `input.tex` and the `main1.tex` will be used. Now change the latexmain file, e.g. with `mv main{1,2}.tex.latexmain` and then inside the `input.tex` vim buffer do `\lx`. Then do `\li` to show the vimtex info, it should now have reloaded and will use `main2.tex` as the main file.

Although I don't want to add the feature myself, you could use the above to get something close to what you want. You can write a function that uses `rename()`, `input()` (or one of the variants), and `VimtexReload` (i.e. the command that corresponds to the `\lx` mapping) to rename the `.latexmain` file and then reload vimtex.

**Comment by heiderich** [comment]
I noticed a related problem in the current version of vimtex (fa1adca64aea62d512bbc9e0b0f4b88ac8667ed4): If the file that is included contains a number in the filename (for instance "input2.tex") and it is included in two files, say foo.tex and bar.tex and there exists foo.tex.latexmain but not bar.tex.latexmain, then bar.tex gets compiled and not foo.tex.

**Comment by lervag** [comment]
Sorry, was a minor error in the file name matching regular expression.
