### ISSUE TITLE
Respect tex root specifier

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#6]
The current generic method (see #3) of locating the main tex file seems good, and would probably work in most cases. However, it is easy to give examples where it would not work (again, see #3). Therefore it has been proposed (#3) to also allow the main tex file to be specified with `%! Tex Root = <main-tex-file>`.

**Comment by notaduck** [comment]
@lervag have you added support for spellcheck as well ?

**Comment by lervag** [comment]
@notaduck I don't quite see the relevance of this question in this thread? Could you please open a new issue with your question and give some more context so it is more clear what you are asking? Thanks!

**Comment by notaduck** [comment]
no problem
