### ISSUE TITLE
After long lines of text, there are noticeable pauses after simple operations (newline, open paren)

### ISSUE THREAD

**Issue by process91** [lervag/vimtex#603]
### The issue

It seems like vimtex is adding almost every word into omnicomplete. I'm not sure if this is intended or not, but I think this is perhaps causing the problem I'm experiencing. After long lines of text, there is a noticeable (>= 2 seconds) pause after just hitting return, or typing an open parenthesis. Disabling vimtex fixes the problem.

I've noticed, for instance, in the example below that if I put my cursor on the line above \end{document} and hit O (in command mode) it takes a second or two before I can start typing. This delay increases with longer lines of text, and longer documents. This happens even with just the minimal .vimrc script below. If, in addition, I have the neocomplete plugin loaded and I type (for example) "Lo" the autocomplete suggests "Lorem", "lorem", and "libero". Is this expected?

Even with only the minimal .vimrc script below, when I copy and paste the long Lorem ipsum line, appending it onto itself, three or four times and then hit Enter I experience a much longer (>=8 seconds) delay.
### Minimal working example

Please provide a minimal working LaTeX example, e.g.

``` tex

\documentclass{article}

\begin{document}

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sodales nunc vitae lorem venenatis viverra. Donec eget elit aliquet, tristique erat at, convallis risus. Nulla volutpat, purus ac auctor faucibus, ligula velit posuere lectus, quis tristique dolor eros vitae lectus. In sapien augue, imperdiet non sodales quis, vulputate non orci. Ut ac turpis enim. Praesent eu libero elementum, tincidunt lectus ac, congue ex. Quisque ut fermentum tellus. Pellentesque id enim vehicula, rutrum massa eu, dignissim nibh. Proin pulvinar rutrum sem ac efficitur. Quisque tristique orci nec massa ornare cursus.

\end{document}

```
### Minimal vimrc file

I tried it with just this in my vimrc, same result.

``` vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
Do you think this might be the same as #598?

**Comment by process91** [comment]
Yes, I do. Your recent fix seems to have cleared up the problem for me. Thank you so much! Can I buy you a beer / coffee / tea?

**Comment by lervag** [comment]
Great, and no problem! I'm always grateful when people fund my beer or coffee. I've added a donate button on the front page README, so feel free to use it. :)

**Comment by lervag** [comment]
I assume we may close this issue?
