### ISSUE TITLE
indent: the closing bracket in \[ [a,b[ \] is indented too far right

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#605]
Using vimtex's indent function, indenting
```tex
\[ 
  [ab[ 
\]
```
gives
```tex
\[ 
  [ab[ 
  \]
```
Expected: The indentation stays unchanged.

**Comment by lervag** [comment]
The reason is that vimtex indents on the delimiters. In math mode, `[` and `]` are delimiters, and so they will add indentation. In your example, you use two opening brackets, and thus the next line gets two indentations.
