### ISSUE TITLE
'vimtex#imaps#wrap_math' does not recognze custom maths environment

### ISSUE THREAD

**Issue by ernestorenanche** [lervag/vimtex#611]
I use the [tex-syntax plugin](https://github.com/vim-scripts/tex-syntax) that allows me to define new math environment with for instance
`let g:tex_math_envs='tikzcd'`
in my `.vimrc`

The syntax is then correctly highlighted but the shortcuts such as `<localleader>+m` do not work inside the environment to insert math symbols.

**Comment by lervag** [comment]
First, you should use the [github](https://github.com/gi1242/vim-tex-syntax) version of that package, as it seems to be more up to date.

I can see the motivation behind that syntax project, however, I notice it has existed for quite some time and has not attracted much attention. I don't really see a good reason to add support for that project, as it will introduce more complexity to vimtex.

You could define the imaps snippets with the `vimtex#imaps#wrap_environment` wrapper, though. That would require some configuration, but then you would also be able to specify exactly which environments a mapping will be defined in. See `:h vimtex#imaps#add_map`.
