### ISSUE TITLE
Alignment with tabs

### ISSUE THREAD

**Issue by Eisfreak7** [lervag/vimtex#613]
### Issue

When using tabs (`noexpandtab`), vimtex adds additional alignment after an ampersand when inserting opening braces. For example:

```
\begin{align*}
    aaaaaaa &=
            &
\end{align*}
```

Aligns to this after Inserting `{`:

```
\begin{align*}
    aaaaaaa &=
               &{
\end{align*}
```

How often this happens depends on the number of characters until the ampersand in the first line. For example, here there are 7 `a`s, 1 whitespace and the `&`. That results in one additional indent when a `{` is typed (more `{`s won't do anything). Any aditional character will result in one more ident, for example using 8 `a`s:

```
\begin{align*}
    aaaaaaaa &=
                   &{{
\end{align*}
```
### Expected

I'd prefer to use tabs for indentation, spaces for alignment so ideally it should format to (TTTT = 1 Tab, _ = 1 Space)

```
\begin{align*}
TTTTaaaaaaaa &=
TTTT________&{{
\end{align*}
```

But that is probably hard to implement, so no alignment at all would also be good. I don't want to disable it using `vimtex-indent`, because I'd like to keep the normal indentation.
### Reproduce

Using this vimrc with vim-plug (technically `set list` isn't needed, but it helps):

``` vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
set list
```

And this tex file:

``` tex
\begin{align*}
    aaaaaaa &=
            &
\end{align*}
```

Type `{` after the second ampersand.

**Comment by lervag** [comment]
Ok, so you would be happy if I added an option to disable the alignment of ampersands? That is a trivial update. I could add `g:vimtex_indent_align_on_ampersand` with default value 1 that you could disable by setting to 0.

Mixing tabs and spaces is something I don't want to touch. It seems hard! But adding an option is something I can definately consider.

**Comment by Eisfreak7** [comment]
Yes. Often I don't want the alignment anyways because it takes away too much screen space.

You probably can't please everyone with tabs and spaces anyways, but this bit of configurability would help a lot.

**Comment by heiderich** [comment]
I would also welcome this.

**Comment by lervag** [comment]
Ok, I just read this once more. I think the problem here is that I personally use `set expandtab` (among other things). In this case, everything works pretty much as expected. However, for some reason, the indentation is screwed when tabs and spaces are mixed.

I'll add an option to disable alignment on ampersands in not too long.

**Comment by Eisfreak7** [comment]
Thanks, works for me!

**Comment by lervag** [comment]
Great :)
