### ISSUE TITLE
Support \jobname and \nobibliography & \bibentry of package bibentry

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#614]
The package bibentry (part of natbib) offers the possibility to get full references inside your text with the command `\bibentry{}`. For example:

``` tex
\documentclass{article}

% This is the sample bib file
\begin{filecontents}{\jobname.bib}
@book{Saussure1995,
    Author = {Ferdinand de Saussure},
    Origyear = {1916},
    Publisher = {Payot},
    Title = {Cours de Linguistique G{\'e}n{\'e}rale},
    Year = {1995}}

\end{filecontents}

\usepackage{natbib,bibentry}
\bibliographystyle{apalike}
\begin{document}
\nobibliography{\jobname}
This is a complete citation in the middle of the text: 

\bibentry{Saussure1995}
\end{document}

```

The omni-completion does not work here because
1. `\jobname` is not translated to the filename plus file extension bib (of course, this is not essential for this issue, but this would be nice to have)
2. `\nobibliography` is not recognized
3. `\bibentry` is not recognized

**Comment by lervag** [comment]
Sorry for taking so damn long to reply to this! I have a tendency to work on issues on a stack basis, and so this was too deep down the stack and ended up being neglected.
