### ISSUE TITLE
vimtex doesn't complete in file with UTF-16-LE encoding

### ISSUE THREAD

**Issue by Congee** [lervag/vimtex#615]
There's no need to support UTF-16LE encoding. But I suggest add this into documentation so that there won't be someone spending as much as three hours like me.

Details:
I accidently made a UTF-16LE encoded file with `pbpaste.exe` directing to a file in Windows `Powershell`

By the way, thanks for your minimal test. It significantly helped me pinpoint the issue.
And the hexdumps:

UTF-16LE file:

```
~/.../test $ hexdump -C gotcha.tex
00000000  ff fe 5c 00 64 00 6f 00  63 00 75 00 6d 00 65 00  |..\.d.o.c.u.m.e.|
00000010  6e 00 74 00 63 00 6c 00  61 00 73 00 73 00 7b 00  |n.t.c.l.a.s.s.{.|
00000020  61 00 70 00 61 00 36 00  7d 00 0d 00 0a 00 5c 00  |a.p.a.6.}.....\.|
00000030  61 00 64 00 64 00 62 00  69 00 62 00 72 00 65 00  |a.d.d.b.i.b.r.e.|
00000040  73 00 6f 00 75 00 72 00  63 00 65 00 7b 00 6c 00  |s.o.u.r.c.e.{.l.|
00000050  6f 00 63 00 61 00 6c 00  31 00 2e 00 62 00 69 00  |o.c.a.l.1...b.i.|
00000060  62 00 7d 00 0d 00 0a 00  0d 00 0a 00 5c 00 62 00  |b.}.........\.b.|
00000070  65 00 67 00 69 00 6e 00  7b 00 64 00 6f 00 63 00  |e.g.i.n.{.d.o.c.|
00000080  75 00 6d 00 65 00 6e 00  74 00 7d 00 0d 00 0a 00  |u.m.e.n.t.}.....|
00000090  5c 00 65 00 6e 00 64 00  7b 00 64 00 6f 00 63 00  |\.e.n.d.{.d.o.c.|
000000a0  75 00 6d 00 65 00 6e 00  74 00 7d 00 0d 00 0a 00  |u.m.e.n.t.}.....|
000000b0
```

Common ASCII file:

```
~/.../test $ hexdump -C test.tex
00000000  5c 64 6f 63 75 6d 65 6e  74 63 6c 61 73 73 7b 61  |\documentclass{a|
00000010  70 61 36 7d 0a 5c 61 64  64 62 69 62 72 65 73 6f  |pa6}.\addbibreso|
00000020  75 72 63 65 7b 6c 6f 63  61 6c 31 2e 62 69 62 7d  |urce{local1.bib}|
00000030  0a 0a 5c 62 65 67 69 6e  7b 64 6f 63 75 6d 65 6e  |..\begin{documen|
00000040  74 7d 0a 5c 65 6e 64 7b  64 6f 63 75 6d 65 6e 74  |t}.\end{document|
00000050  7d 0a                                             |}.|
00000052
```

**Comment by lervag** [comment]
I don't quite understand this: What was the issue here? How could I reproduce it?

Vimtex does not really do anything about encodings. That should be up to Vim itself..?

**Comment by lervag** [comment]
I also don't understand what you want me to write in the docs...

**Comment by Congee** [comment]
If your '.tex' file and '.bib' file are encoded in UTF-16-LE, you can't complete the citation after `\cite{`. Uh....I didn't debug into your code, so don't know if it's an upstream issue, but I believe it is.

**Comment by Congee** [comment]
What I would like to suggest is you write "Completion may doesn't work with some file encodings, e.g., UTF-16-LE".

**Comment by Congee** [comment]
Vimtex is fantastic! Thanks for your code. :-P

**Comment by lervag** [comment]
Thanks for the kind words!
