### ISSUE TITLE
Viewer opens old file

### ISSUE THREAD

**Issue by adhalanay** [lervag/vimtex#619]
Maybe this problem was already solved, but I can' find it. Assume I start with a file called file1.tex, then save it to file2.tex and further edit it. Compiling with \ll works perfecttly (does compile file2.tex) , but \lv opens file1.pdf.

If this is relevant I am using vim with okular on debian linux.

**Comment by lervag** [comment]
Can you explain more specifically what you do? Saving to `file2.tex` (with `:w file2.tex`) does not change the buffer, i.e. the current buffer will still be for `file1.tex`. Are you using `saveas`?

**Comment by adhalanay** [comment]
Indeed I am using saveas (in gvim FILE->Save As  menu item).

**Comment by lervag** [comment]
Ok. I'll look into it.

**Comment by lervag** [comment]
There, that should do it.

**Comment by lervag** [comment]
Btw: This is the 500th issue that I've closed. Calls for a celebration! :)

**Comment by adhalanay** [comment]
I can confirm that the bug is gone.
