### ISSUE TITLE
vim hangs when inline math is open before end of document

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#621]
i have now repeatedly seen vim freeze on me. it happens when the end of the file looks like this:
```
text, text, $a=

\bibliographystyle{unsrt}
\bibliography{filename}
\end{document}
```
and i hit `:w` to save and compile. the status line displays the error `-> unmatched "math begin $"`, vim is at 100% cpu and input is no longer possible so that i have to kill vim.

using macvim with vim 8.0.

**Comment by nilsbecker** [comment]
i tried to reproduce with a minimal tex file. the following was enough to reproduce:
```
\documentclass{article}
\begin{document}

Hello World!

aelt a \cite{acar05}

$d=adsf$ and and $basdf

\bibliographystyle{unsrt}
\bibliography{/Users/nbecker/Literature/bib/NilsRef}

\end{document}
```
i'm not sure if the bibliography is necessary. now the hang did not occur immediately upon saving, and it required several tries to reproduce it.

**Comment by nilsbecker** [comment]
ok, now i reproduced without bibliography. so basically, playing around with a file with open inline math should be enough to trigger this. it may require several attempts. latexmk should be running.

**Comment by nilsbecker** [comment]
d'oh. this was #616 . i should have updated before reporting. sorry about the noise.

**Comment by lervag** [comment]
No problem! I'm sorry about introducing that problem. It should stand as a reminder for me to use branches when developing more complex changes.
