### ISSUE TITLE
']]' mapping should ignore Vim fold markers

### ISSUE THREAD

**Issue by Coacher** [lervag/vimtex#622]
Hello.

Consider the following file:
```
\begin{env} % {{{
    Some text here.

```
1. Place the cursor at the beginning of the third line.
2. Enter Insert mode.
3. Hit `]]`

Actual results:
`}` is inserted.

Expected results:
`\end{env}` is inserted.

vimtex has problems ignoring vim fold markers.

vimtex config:
```
let g:vimtex_imaps_enabled = 0
let g:vimtex_view_enabled = 0
let g:vimtex_view_automatic = 0
let g:vimtex_quickfix_open_on_warning = 0
```

vimtex is fa1adca, vim is 8.0.0071.

Please fix.

**Comment by lervag** [comment]
Should work now.

**Comment by Coacher** [comment]
Yes, works perfectly now. Thank you very much!

**Comment by lervag** [comment]
No problem, happy it works :)
