### ISSUE TITLE
Command folding slows down folding

### ISSUE THREAD

**Issue by yagebu** [lervag/vimtex#623]
### Explain the issue

The time to run folding has gone up from basically instantly (<1s) to several seconds (~10 on some files) since 9d8b23e03a6e4cc56c43e16c0fd234fa431cf67a. I'm using vimtex in combination with FastFold to update the folds. I'm on a Mac and using neovim but with the below vimrc I can also reproduce the slowdown in Vim (opening a file, then typing `zuz` which blocks vim for several seconds). This doesn't happen for really small files, so I don't have a minimal example, but I also wouldn't call the files I'm working on huge (single tex files ~1k lines, ~50k chars) and there is a noticeable slowdown for all of them.

To narrow it down, I've slimmed down `g:vimtex_fold_commands_default` but that doesn't seem to make any difference - none of the files I opened even contain a `tikzset`. Setting `g:vimtex_fold_commands_default` to `{}` makes the folding run in an instant though.

### Minimal vimrc file

```vim
set nocompatible

let &rtp  = '~/.local/share/nvim/plugged/FastFold,' . &rtp
let &rtp  = '~/.local/share/nvim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.local/share/nvim/plugged/vimtex/after'

filetype plugin indent on
syntax enable
let g:vimtex_fold_enabled = 1
let g:vimtex_fold_commands_default = {
    \ 'tikzset' : 'single',
    \}
```

**Comment by lervag** [comment]
Thanks, I found a silly bug in the code that should fix this.

**Comment by yagebu** [comment]
Perfect, that seems to fix it. Thank you very much!

**Comment by lervag** [comment]
No problem! Thank you for noticing and reporting. I'd only worked on small files recently where this did not give noticable lags. I still think the folding is quite slow, in particular for large/complex files, but I don't see any clear ways to improve it at the moment.
