### ISSUE TITLE
subimport path resolution

### ISSUE THREAD

**Issue by DelusionalLogic** [lervag/vimtex#626]
According to the ```import``` package documentation, ```\subimport{<subdir>}{<file>}``` resolution has to follow a stack like structure. It also has to honor the ```TEXINPUTS``` env variable

The rules are as follows:

1. Look for the ```<file>``` in the directories in the ```TEXINPUTS``` env variable.
2. Look for the ```<file>``` in the ```<subdir>```
3. Look for the ```<file>``` in any previous ```<subdir>```

If the file is found at any point, skip the other steps and just use that file.

I might be wrong, since it's pretty difficult to decipher this part of the [documentation](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/import/import.pdf). As can be seen on page 2 it seems to suggest that failing to find ```three``` in ```abc/lmn/uvw/``` it tries to find it in ```abc/```, the ```subdir``` the ```file``` was included in. That suggests it might be following a stack structure.

**Comment by lervag** [comment]
I am curious: Is there a problem with the current version of vimtex where this is relevant? E.g., could you define some minimal working example(s) where issue description applies and vimtex is not handling it properly?

I think currently I only adhere to rule 2. It would be pretty easy to add rule 1, but is it necessary? Rule 3, however, would be more tricky. Again I question the necessity. It seems to me that rule 3 in particular adds a lot of implicitness that makes it hard to understand the tex code.

**Comment by DelusionalLogic** [comment]
I agree completely.

I could make a minimal example, but it wouldn't have any practical application for me personally, or anyone else I expect. I think both of our efforts are best used elsewhere

I made the issue for technical completeness. Seeing as how I touched the code and found the issue I figured I might as well document it for future reference.

**Comment by lervag** [comment]
Great! Thanks for that, I appreciate it. I am also happy to conclude that we'll leave this issue closed.
