### ISSUE TITLE
SumatraPDF can't auto open pdf-file.

### ISSUE THREAD

**Issue by xingezhang** [lervag/vimtex#627]
### Explain the issue
I use gvim 8.0 with vimtex on windows 10 x64, after command `\ll` compile is successful. but SumatraPDF can't auto open pdf file. After command `\lv`, SumatraPDF open tex file, and I notice "my path/example.tex is valid". But same file on Linux is fine. Please help me, thank you.

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

latexmkrc

```perl
$pdflatex = "xelatex --shell-escape -src-specials -synctex=1 -interaction=nonstopmode %O %S";
$preview_continuous_mode = 1;
$pdf_previewer = "start SumatraPDF -reuse-instance -inverse-search -a %O %S";
$pdf_mode = 1;
$clean_ext = 'synctex.gz synctex.gz(busy) acn acr alg aux bbl bcf blg brf dvi fdb_latexmk glg \
glo gls idx ilg ind ist lof log lot lox out paux pdfsync run.xml toc';
$recorder = 1;
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
let g:tex_flavor = "latex"
let g:vimtex_enabled                  = 1
let g:vimtex_latexmk_enabled          = 1
let g:vimtex_latexmk_continuous       = 1
let g:vimtex_latexmk_background       = 1
let g:vimtex_view_enabled             = 1
let g:vimtex_view_method = 'general'
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options 
	\ = '-reuse-instance -forward-search @line @pdf @tex'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'

```

**Comment by lervag** [comment]
Could you supply an actual minimal vimrc file? The content you've supplied makes me question if you are using a minimal vimrc file, or if those are just the relevant vimtex settings.

Based on the options you supply, I propose that you use the following minimal vimrc file:

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:tex_flavor = "latex"
let g:vimtex_latexmk_background       = 1

let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options 
	\ = '-reuse-instance -forward-search @line @pdf @tex'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
```

Note that several of the options that you suggested in your original post are already default and are therefore not necessary to include.  Also, the `g:vimtex_latexmk_background` option is not relevant if you have `g:latexmk_latexmk_continuous` enabled (which it is by default), thus I propose to remove that as well.

**Comment by lervag** [comment]
When we have sorted out the minimal vimrc file, I will test this on windows. Note, though, that I rarely use windows, and so it might be some time until the next time I have the chance to test this. If it is a bug, it might therefore take some time before I fix it.

**Comment by xingezhang** [comment]
Thank you very much,I use your minimal vimrc,compile success.but \lv open Tex file again,wait your fix it.

**Comment by lervag** [comment]
Which version of SumatraPDF are you using?

**Comment by lervag** [comment]
Ok, I've tested on windows, and everything works as expected here. Although, I had to fix one minor error from your description:

```diff
- \ = '-reuse-instance -forward-search @line @pdf @tex'
+ \ = '-reuse-instance -forward-search @tex @line @pdf'
```

That is, the order of the options matter. The correct version is the one that is described in the vimtex documentation.
