### ISSUE TITLE
subfiles detection is no longer working

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#629]
I've not updated for a some time. After the latest update the subfiles detection seems no longer working.

Steps to reproduce:
1. Create main.tex and test.tex as defined below.
2. Open main.tex.
3. Navigate to the subfile inclusion.
4. Press `gf`.
5. Call `VimtexInfo`

Adding `%! TEX root = main.tex` only works when `\documentclass[main.tex]{subfiles}` is removed.

```tex
%main.tex
\documentclass{article}
\usepackage{subfiles}
\begin{document}
aaa
\subfile{test.tex}
\end{document}

%test.tex
\documentclass[main.tex]{subfiles}
\begin{document}
\end{document}
```

**Comment by maxfl** [comment]
Perhaps it happens because function
```vim
  if s:file_is_main(expand('%:p'))
    return expand('%:p')
  endif
```
detects documentclass string and says that file is main.

**Comment by maxfl** [comment]
Yes, that is the reason. The logic should be reviewed somehow.

**Comment by lervag** [comment]
This was a regression bug that was introduced in a commit September 1st this year. I've fixed it and added a test that should prevent the bug from being introduced again in the future.

Thanks!
