### ISSUE TITLE
Omnicompletion and colons in \label

### ISSUE THREAD

**Issue by avfonarev** [lervag/vimtex#631]
I'm using the neocomplete omni patterns suggested in the vimtex help file. Whenever I use `\label{thm:one}`, the pattern that is suggested to me is `thm:` exclusively. Is it a bug or there is a deep reason for this behaviour?

Thank you for a great plugin,
Anton

**Comment by avfonarev** [comment]
It seems to me that the problem was in me not compiling the file first. So, neocomplete was providing some strange suggestions instead of what I expected. Works fine now. Sorry for inconvenience.

**Comment by lervag** [comment]
No problem! I understand it is nontrivial to understand all the features.
