### ISSUE TITLE
[request] Configurable list of environments with no indent

### ISSUE THREAD

**Issue by Coacher** [lervag/vimtex#634]
Hello.

vimtex doesn't do indent in environments considered verbatim:
https://github.com/lervag/vimtex/blob/master/indent/tex.vim#L78
As you can see the list of such environments is hard coded.

Vim stock tex indent also doesn't do indent in environments considered verbatim,
but the list of such environments is configurable via `g:tex_noindent_env` variable:
https://github.com/vim/vim/blob/master/runtime/indent/tex.vim#L117

Please make vimtex also support custom verbatim environments via a variable.

I prefer to have my proofs without extra indent and vimtex constantly gets in the way.
This feature would help me a lot.

**Comment by lervag** [comment]
I added an option for this. Let me know if you think it works as intended and if the help text is OK.

**Comment by Coacher** [comment]
Thank you for adding this, but I don't think it works.
Here's my vimtex config:
```
let g:vimtex_imaps_enabled = 0
let g:vimtex_view_enabled = 0
let g:vimtex_view_automatic = 0
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_indent_verbatim_envs = ['verbatim', 'lstlisting', 'minted', 'proof']
```

Have this file in Insert mode, where 'X' indicates the cursor position:
```
\begin{document}

\begin{proof}X

\end{document}
```

Press `<CR>`, then you have:
```
\begin{document}

\begin{proof}
    X

\end{document}
```

Expected results:
```
\begin{document}

\begin{proof}
X

\end{document}
```

**Comment by lervag** [comment]
I realize I did not think properly through this. What you want is not achieved by defining the verbatim environment names. Verbatim areas are matched through the syntax region. The regex that I updated only ensures that the begin/end commands _are_ indented properly.

I think what you want, instead, is an option for environments that should not add/reduce indents. This would, as far as I can see, solve your issue. Note, though, that "normal" indentation would still occur inside the environments. E.g. I think something like this:

```vim
let g:vimtex_indent_ignored_envs = ['proof']
```

```tex
\begin{proof}
Consider $f(x)$ such that
\begin{equation}
  f(x) = 1
\end{equation}
\end{proof}
```

That is, the equation environment is indented as expected, but the proof environment does not add/reduce indents. Does this sound right to you?

**Comment by Coacher** [comment]
> I think what you want, instead, is an option for environments that should not add/reduce indents.
> ...
> That is, the equation environment is indented as expected, but the proof environment does not add/reduce indents.

Yes, that's exactly what I meant. Sorry if my initial explanation was confusing.

**Comment by lervag** [comment]
I think this should solve it.

**Comment by Coacher** [comment]
I've tested this feature with `let g:vimtex_indent_ignored_envs = ['document', 'proof']` and it works as expected. Thank you very much! This saves me a lot of hassle!

**Comment by lervag** [comment]
No problem, happy it works :)

**Comment by aldanor** [comment]
I was wondering if it was possible to specify some kind of glob/regex to match these environments?

For instance, `\newminted{foo}{...}` always defines a minted environment named `foocode`, so it would be nice to have `*code` treated as verbatim.

**Comment by lervag** [comment]
Yes, that is possible. You can use regexes. Note that you must write the regexes in magic mode, see `:h \v`. E.g., you can do:

```vim
let g:vimtex_indent_ignored_envs = [
    \ 'document',
    \ '.*code',
    \]
```
