### ISSUE TITLE
Support for \subref{}-completion

### ISSUE THREAD

**Issue by aquadr** [lervag/vimtex#636]
The popular packages [subfig](http://www.ctan.org/pkg/subfig) [subfigure](http://www.ctan.org/pkg/subfigure) and [subcaption](http://www.ctan.org/pkg/subcaption) all provide the command \subref to make references to sub figures. It would be nice if vimtex could support \subref{} label completion!

ps. Thanks for the great plugin!

**Comment by lervag** [comment]
Sounds good. But it would help if you could provide a minimal example that I could work with while implementing it.

**Comment by aquadr** [comment]
Stolen from [tex.stackexchange](http://tex.stackexchange.com/a/130508)

```latex
\documentclass{article}
\usepackage{graphicx}
\usepackage{subcaption}

\begin{document}
\begin{figure}[ht]
  \centering
  \begin{subfigure}[b]{0.5\linewidth}
    \centering\includegraphics[width=100pt]{example-image-a}
    \caption{\label{fig:fig1}}
  \end{subfigure}%
  \begin{subfigure}[b]{0.5\linewidth}
    \centering\includegraphics[width=100pt]{example-image-b}
    \caption{\label{fig:fig2}}
  \end{subfigure}
\end{figure}
subref test: \subref{fig:fig1}
\end{document}
```

**Comment by lervag** [comment]
Thanks! I will look into it when I get the time.

**Comment by lervag** [comment]
I think it should work now.

**Comment by aquadr** [comment]
Works like a charm! Thanks!

**Comment by lervag** [comment]
No problem :)
