### ISSUE TITLE
Add vmap mappings

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#638]
Having recently made the switch from `LaTeX-Box` to `vimtex`, the only thing I really miss are the `vmap` mappings to quickly wrap a selection into a command or (more usefully) an environment. 

Specifically, the possibility to have

       vmap <buffer> <F7>   <Plug>LatexWrapSelection
       vmap <buffer> <S-F7> <Plug>LatexEnvWrapSelection

Does `vimtex` offer something similar, or would it be hard to port the functionality from `LaTeX-Box`?

**Comment by lervag** [comment]
I never used those mappings myself, and so I never cared to implement them. But I will look into it when I get the time. It should not be very difficult.

**Comment by Rmano** [comment]
What I do is using UltiSnips for that --- for example, with the snippet

```
snippet env "surround with environment" b
\begin{$1}
    ${0:${VISUAL}}
\end{$1}
endsnippet
```
you visual select what you need, and then press <TAB> (or the key you choose to trigger UltiSnips) and you have your selection surrounded. You can type the name of the environment and it will be echoed in the `\end{}` clause.

**Comment by lervag** [comment]
Thanks, @Rmano! That's actually the exact reason I never implemented this, I just forgot. That is: This particular `vmap` is a special case of a common snippet feature, and I made a design choice for vimtex not to implement a snippet engine.

@clason Could you consider to test Ultisnips to get the desired feature? Note: Ultisnips (or other snippet engines) and snippets are very useful for a lot of different cases and languages, and so I strongly recommend that you look into it if you have not already.

**Comment by kiryph** [comment]
Another possibility is to use one of the surround plugins:

1. [tpope/vim-surround](https://github.com/tpope/vim-surround)

   visually select and then press `Sl` or `S\` to be asked about the environment to use. To surround with a command with the mapping `Sc` add following line to `~/.vim/after/ftplugin/tex.vim`
   `let b:surround_{char2nr("c")} = "\\\1command: \1{\r}"`
   If you want to have a consistent mapping for the environment (`Se`), you can adding following
   `   let b:surround_{char2nr("e")}
      \ = "\\begin{\1environment: \1}\n\t\r\n\\end{\1\1}"`
   However,  you can't dot-repeat them. See next plugin for this and also support for [visualrepeat.vim](http://www.vim.org/scripts/script.php?script_id=3848).

2. [machakann/sandwich.vim](https://github.com/machakann/vim-sandwich)

   See in particular following suggested configuration
   - https://github.com/lervag/vimtex/issues/201#issuecomment-122611153

 Only sandwich.vim supports visualrepeat.vim which means you can do the following:

The text `italic non-italic italic` can be changed to `\textit{italic} non-italic \textit{italic}` via following code sequence (using surround mappings):
`viw`+`Sc`+`textit<Enter>`+`2W`+`.`

**Comment by lervag** [comment]
Thanks @kiryph. Yet another good reason not to add this to vimtex (IMHO).

**Comment by clason** [comment]
Thank you for the suggestions! Of course I'm also using UltiSnips and vim-surround. The UltiSnips workaround doesn't quite fit my workflow (muscle memory...), but the vim-surround command works nicely out of the box (I'm mainly concerned with environments anyway). Now I just have to retrain those muscles...

**Comment by lervag** [comment]
Great to hear that you find vim-surround to be an adequate solution (even with the necessary change of muscle memory).

Don't hesitate to open new issues if there are other things you are missing or that you think might be wrong.

**Comment by clason** [comment]
Well, I actually feel silly that I didn't know about the vim-surround command -- that is indeed the natural place to implement this. I even vaguely remember looking in the vim-surround documentation but not finding anything.

**Comment by kiryph** [comment]
Actually, Tim Pope removed it from the documentation in January, 2013 but kept the feature within the code:
https://github.com/tpope/vim-surround/commit/ac67c1a7387a9e1c082fa98e7526b7b633f4beec

Surprisingly, he accepted following pull request in February, 2015 https://github.com/tpope/vim-surround/pull/163

Anyhow, I was happy to help here.

**Comment by clason** [comment]
Let's hope it doesn't suddenly go away at some point, then :) (Not likely after so long, though.)
