### ISSUE TITLE
vimtex_complete_img_use_tail fails silently

### ISSUE THREAD

**Issue by napseis** [lervag/vimtex#640]
Hi,

I wanted to switch from latex-suite to vimtex, since i saw it was able to provide smart completion based on \graphicspath.

However, despite the instruction of the manual, the completion of includegraphics fails. It just doesn't do anything, or, at worse, propose a file in a subfolder.

I attached a minimal example, what do i do wrong ? I even tried with additional configuration with neocomplete and YCM, disable/enable omnicomplete...
I think this feature is a must have, and I like very much that vimtex is supposed to have it.

Thanks

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\graphicspath{{/some/absolute/path/}}

\begin{document}

Hello World!

\begin{figure}[h]
    \includegraphics[width=8cm]{here_it_fails}
\end{figure}

\end{document}
```

### Minimal vimrc file

```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex' , { 'for' : ['tex', 'latex']}
call plug#end()

set nocompatible
"set omnifunc=syntaxcomplete#Complete

let g:tex_flavor='latex'


filetype plugin indent on
syntax enable

let g:vimtex_complete_img_use_tail = 1

```

**Comment by lervag** [comment]
I use the following minimal example where it works exactly as expected:

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
let g:tex_flavor='latex'
let g:vimtex_complete_img_use_tail = 1
```

```tex
\documentclass{minimal}
\graphicspath{{/home/lervag/test/figures}}

\begin{document}

Hello World!

\begin{figure}[h]
  \includegraphics[width=8cm]{here_it_fails}
\end{figure}

\end{document}
```

And inside the `figures` directory I have touched `test1.png`, which is now correctly completed when I change "here_it_fails" and start omnicompletion with `CTRL-X CTRL-O`.

**Comment by napseis** [comment]
Thanks. This still doesn't work, despite i used exactly your vimrc . 
It displays all the graphic files in the current subfolders, but not in the given graphicspath.

Below my vim version:

gvim --version
VIM - Vi IMproved 7.4 (2013 Aug 10)
Included patches: 1-207, 209-326
Compiled by 'http://www.opensuse.org/'
Huge version with GTK2 GUI.  Features included (+) or not (-):
+acl             +farsi           +mouse_netterm   +syntax
+arabic          +file_in_path    +mouse_sgr       +tag_binary
+autocmd         +find_in_path    -mouse_sysmouse  +tag_old_static
+balloon_eval    +float           +mouse_urxvt     -tag_any_white
+browse          +folding         +mouse_xterm     -tcl
++builtin_terms  -footer          +multi_byte      +terminfo
+byte_offset     +fork()          +multi_lang      +termresponse
+cindent         +gettext         -mzscheme        +textobjects
+clientserver    -hangul_input    +netbeans_intg   +title
+clipboard       +iconv           +path_extra      +toolbar
+cmdline_compl   +insert_expand   +perl            +user_commands
+cmdline_hist    +jumplist        +persistent_undo +vertsplit
+cmdline_info    +keymap          +postscript      +virtualedit
+comments        +langmap         +printer         +visual
+conceal         +libcall         +profile         +visualextra
+cryptv          +linebreak       +python/dyn      +viminfo
+cscope          +lispindent      +python3/dyn     +vreplace
+cursorbind      +listcmds        +quickfix        +wildignore
+cursorshape     +localmap        +reltime         +wildmenu
+dialog_con_gui  +lua/dyn         +rightleft       +windows
+diff            +menu            +ruby/dyn        +writebackup
+digraphs        +mksession       +scrollbind      +X11
+dnd             +modify_fname    +signs           -xfontset
-ebcdic          +mouse           +smartindent     +xim
+emacs_tags      +mouseshape      +sniff           +xsmp_interact
+eval            +mouse_dec       +startuptime     +xterm_clipboard
+ex_extra        +mouse_gpm       +statusline      -xterm_save
+extra_search    -mouse_jsbterm   -sun_workshop    -xpm
 system vimrc file: "/etc/vimrc"
  user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
  user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/current"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-2.0 -I/usr/lib64/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/freetype2    -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=1 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -Wall -pipe -fno-strict-aliasing      
Linking: gcc   -L. -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.18.2/x86_64-linux-thread-multi/CORE   -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype  -lSM -lICE -lXt -lX11 -lSM -lICE  -lm -lnsl    -ltinfo -lacl -lattr -lgpm -ldl   -Wl,-E -Wl,-rpath,/usr/lib/perl5/5.18.2/x86_64-linux-thread-multi/CORE  -L/usr/local/lib64 -fstack-protector  -L/usr/lib/perl5/5.18.2/x86_64-linux-thread-multi/CORE -lperl -lm -ldl -lcrypt -lpthread

**Comment by lervag** [comment]
Ok. Could you please provide a full minimal example? That is, provide an absolute path and the exact steps you do that fails.

**Comment by napseis** [comment]
ok, so the .vim rc is exactly:

```
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
set nocompatible
let &rtp  = '~/.vim/plugged/vimtex,' . &rtp
let &rtp .= ',~/.vim/plugged/vimtex/after'
filetype plugin indent on
syntax enable
let g:tex_flavor='latex'
let g:vimtex_complete_img_use_tail = 1
```

Then I place myseld in $HOME, 
and try:
gvim tests.tex
with content:
```
\documentclass{minimal}
\graphicspath{{/home/napseis/Pictures/}}

\begin{document}

Hello World!

\begin{figure}[h]
\includegraphics[width=8cm]{}
\end{figure}

\end{document}
```

Then in  \includegraphics[width=8cm]{HERE}, i do CTRL-X CTRL-O, it thinks a while, then shows a list with all the images that it can find in the $HOME/ subdirectories.

When I first tried in my paper folder , it was displaying the only pdf file present in the only subfolder, so, same behavior.

**Comment by lervag** [comment]
Please remove the first three lines in the `.vimrc` file (`call plug...`).

But ok, I now see the problem. Currently, the completion does not care about the `\graphicspath` command. It only searches for image files from the root directory of the main LaTeX file.

I agree this should be implemented, and so we'll keep this issue open until I've managed to implement it. I hope that I get some time this Christmas to work on vimtex issues, but I can't promise anything. In the meantime, I think you could "solve" this by adding a symlink from your root folder, or by moving the pictures into the LaTeX folder.

**Comment by napseis** [comment]
Hi, 
Thanks for looking into it. But why should i remove the call plug lines ?
Indeed, i guess a symlink could do it, but then, what did I misunterstood in the documentation ? I thought the following was doing exactly this ?
```
By default, the paths are completed relative to the root path of the main
file. One can use the option |g:vimtex_complete_img_use_tail| to instead
complete only the tail part of file names. This is useful if one uses the
`graphicx` package and the `\graphicspath` command.
```
Have a nice Christmas celebration!

**Comment by lervag** [comment]
The `call plug` lines are not necessary when we adjust the `runtimepath` manually through the following `let &rtp ...` lines.

Actually, `g:vimtex_complete_img_use_tail` only specifies that we complete the tail part of the paths, and not the complete relative (or absolute) paths. That is, instead of `<c-x><c-o>` giving `figures/test.png`, it gives simply `test.png`. This is only possible when one uses the `\graphicspath` command or if the picture files are in the same folder as the tex file.

**Comment by napseis** [comment]
Ok, I see now. Thanks!

**Comment by napseis** [comment]
hi,
Thanks for the fix, I tested and it works, except for one thing (fr which i thought it wasn't working at first):
If i give, let's say, 

    \graphicspath{{/home/napseis/Travail/Saint_Etienne/Images/}}

which contains several subfolders, these folders are not completed.
I looked at the commit you made, but I'm not able to understand... Is this normal ?
As for me this is already good, I can add all the subfolders as a workaround at least.

thanks !

**Comment by Rmano** [comment]
Yes, it could be useful. I also have graphics organized like 
```
.../before/state.png
.../after/state.png
```
and like to use `\includegraphics{before/state}` with the opportune `\graphicspath`. 
I tried to change the `img.gather_candidates` function to make it recursive but for now I failed...

**Comment by napseis** [comment]
That's OK, I just wanted to be sure to understand what was the feature implemented.

**Comment by lervag** [comment]
Actually, @napseis, you've raised a relevant issue. Currently I don't search for pictures recursively through the directories. But I should, and I think it makes for a valid improvement.

It would be very helpful if you opened a new issue for this, since I can't start work immediately. Thanks!

**Comment by napseis** [comment]
hi,
I would like to point out that the completion fails if it is an upward relative path such as "../.../../Images"

thanks

**Comment by lervag** [comment]
Hmm. It doesn't for me, but perhaps I don't understand you correctly. Could you show me a minimal example?
