### ISSUE TITLE
Multiple filetypes

### ISSUE THREAD

**Issue by fab4100** [lervag/vimtex#642]
Hi

I have a small issue using vimtex with other filetype

### Issue
I use vimwiki and often write LaTeX code in my notes.  Hence, I want the tex filetype settings when I edit vimwiki filetypes.  I set this in my .vimrc

```autocmd BufRead,BufNewFile *.wiki setlocal ft=vimwiki.tex```

However, this triggers the error message in vimtex/after/syntax/tex.vim that a different filetype is already loaded.  Is it possible to silence this error and not load the syntax if another (primary) filetype is already loaded?

Thanks
Fab

**Comment by fab4100** [comment]
'''autocmd BufRead,BufNewFile *.wiki silent! setlocal ft=vimwiki.tex'''

**Comment by lervag** [comment]
Sorry for not responding faster!

I am wondering if I am perhaps a little bit too conservative in raising an error in this case. I'm pushing a change that should solve this for you without the need for `silent!`. Let me know what you think.

**Comment by fab4100** [comment]
No worries at all!

Thanks for the push.  I personally would probably not be that conservative in this case.  The syntax should not screw up things.  Also, my use case is probably rare too.  Nevertheless, thanks for the response.

**Comment by lervag** [comment]
No problem, and happy holidays!
