### ISSUE TITLE
[RFC] reduce complexity of vimtex-indent

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#643]
*(This is an offshoot and summary of the discussion in #598.)*

The `vimtex-indent` code is almost two orders of magnitude slower than the corresponding (much simpler) [indentation in LaTeX-Box](https://github.com/LaTeX-Box-Team/LaTeX-Box/blob/master/indent/tex.vim). (To give a rough idea, indenting ~1000 lines takes ~0.2 seconds with LaTeX-Box and ~9 seconds in vimtex as measured by `profile` -- long enough to be annoying if you have to do it repeatedly.)

The main difference is how vimtex matches delimiters (braces, parentheses etc.) for indentation: Where LaTeX-Box only looks for unmatched braces (but not brackets or parentheses) on the line, vimtex parses the whole line to distinguish text mode from inline math mode to also allow indentation of brackets and parentheses (only!) in math mode, e.g.,
```tex
Lorem ipsum dolor sit amet, (
consectetur adipiscing elit. $1+1=2,
2+2=4, (
    3+3=6
)$)
Ut porttitor blandit mi quis faucibus.
```
(Note that the second line is *not* indented.)

It is precisely this splitting of lines into math regions that takes such a long time (see details below).
Hence my proposal: **Remove the different treatment of text and inline math, i.e., in both cases indent only on braces (or on braces, brackets and parentheses).**  (I am not proposing changing the indentation inside environments -- in particular displayed math -- where currently braces, brackets and parentheses are indented.)

If yes, the main question would be: **Should brackets in normal mode be indented?** This could be useful in the preamble for `\documentclass`es or `\usepackage`s with lots of options, but (without the special treatment) would wreak havoc with lines containing, e.g., `$[0,\infty[$`. 

(If there's no consensus, the current behavior could be made optional, e.g., via `vimtex_indent_inlinemath`).

---

To put a face to things: Here are the bottlenecks, in descending order of severity, and the timing for the example above if they are skipped (these are cumulative):

* [`s:split`](https://github.com/lervag/vimtex/blob/master/indent/tex.vim#L173), specifically while calling `vimtex#delim#get_next('env_math', 'open')`: *~2 seconds*

(Here I just replaced by replacing [`s:indent_delims`](https://github.com/lervag/vimtex/blob/master/indent/tex.vim#L113) with</sup>
```vim
function! s:indent_delims(line, lnum, prev_line, prev_lnum) 
  if empty(s:re_delims) | return 0 | endif

  return &sw*(  max([  s:count(a:prev_line, s:re_delims[2])
        \            - s:count(a:prev_line, s:re_delims[3]), 0])
        \     - max([  s:count(a:line, s:re_delims[3])
        \            - s:count(a:line, s:re_delims[2]), 0]))
endfunction
```
That's not quite enough, since the current implementation does not match display the math environment `\[ ... \]` as an environment (i.e., via `indent_envs`) but as delimiters (i.e., via `indent_delims` as a special case of `[...]` in normal mode but not in math mode), which would have to be changed (and probably should be changed anyway for sanity).)

* `s:is_verbatim`, specifically the call to `synIDattr`: *~0.6 seconds*

(I don't quite understand what this function does precisely. Is the first line checking for -- in particular -- ``\begin{minted}``, and the second line whether we are inside a `minted` environment with, e.g., python code? In fact, going through a few of my files, I couldn't find *any* region where `synIDattr` returns `texZone`. (I found a nifty [vimL function](http://vim.wikia.com/wiki/Showing_syntax_highlight_group_in_statusline) to show the current syntax zone in the status line.))

* `s:indent_tikz`, specifically `is_inside('tikzpicture')`: *~0.2 seconds*

(See also #644.)

* `s:count`, specifically `match(line,pattern)`: *~0.1 seconds*

(Here I just replaced the complete function with the [single-line implementation from LaTeX-Box](https://github.com/LaTeX-Box-Team/LaTeX-Box/blob/master/indent/tex.vim#L26).)

**Comment by clason** [comment]
I've spent some more time comparing the two implementations and found a few cases where the matching of typographic delimiters (i.e., `(`, `[`, and in particularly `\{`) that vimtex does and LaTeX-Box doesn't can cause problems:

1. Admittedly a constructed example and easily corrected, but a more complicated version actually occurred in one of my files I used for testing and took me quite a while to figure out what was going on:
```tex
\begin{equation}
    f(x) = \begin{cases}{1}&x>0\\{0}&x\leq 0\end{cases}
\end{equation}
```

2. Also somewhat of an edge case, but actually a problem since there's no easy workaround:
```tex
\begin{bleq}
    \left\{\begin{aligned}
            f(x) &= x^2,\\
            g(x) &= x^3.
        \end{aligned}\right.
    \end{bleq}
```
(`bleq` is a self-defined environment that wraps an `equation` in a `beamercolorbox`; if I change this to `equation`, the indentation is correct.)

So I think I'm leaning towards changing my proposal to "don't indent on typographic delimiters at all, even in display math" (or at least make that optional).

**Comment by lervag** [comment]
Indentation is hard. I think the hardest part is deciding the actual rules, i.e., how things should look and behave. Personally, I think the current rules are OK, but I see the problem with e.g. manually defined math environments. The implementation uses the syntax groups to decide whether we are indenting math or normal text.

FYI: I don't indent on `\(` by design. This is inline math, similar to `$`s, and I don't think these should be indented.

I think your proposal might actually be quite good. If we chose to only add specific indents on `\left` and `\right` like pairs, then I think we could simplify the code quite a bit. In particular, we would have the following behaviour:

```tex
Some text with { \color{red} indented
  line here
} and inline math $here$ and \(here
f(x) = 1
\)
and displayed math here:
\[
  f(x) = 1
\]

More inline math with indented params here $\left(
  x = 1
\right)$

Equation here

\begin{equation}
  f(x) = (1.0
  - \left(
    2.0
  \right)
  )
\end{equation}
```

What do you think?

**Comment by clason** [comment]
The current rules are indeed reasonable (and indentation is partly a matter of personal preference, anyway); I am more concerned about the general performance than the behavior in edge cases.

Regarding `\(`: To me this feels more like an environment like `\[` than a toggle like `$`, but not indenting either is in fact more consistent.

Regarding `\left(`: By the same argument (consistency), I would *not* indent this, since `(` isn't indented either. (In my example, the indentation from `\begin{aligned}` would be sufficient for my taste; having additional alignment from `\left\{` might be too much.) But, like above, I can see the point of this being a "stronger" delimiter and hence to merit indentation. 

In any case, I don't have strong feelings; either is fine with me! (And it's your code after all :)) Actually, would it be feasible to make this configurable via something like `vimtex_indent_delims='\\[,\\(,\{,\\left'`?

**Comment by lervag** [comment]
Ok, I've started making some adjustments that should improve things. These first adjustments are not the most important ones, but I found they still have a noticable impact.

I'm going to look at the delimiter indentation next. I think my proposal might be a good starting point, since it would immediately give a very much simpler (and faster) method. Another proposal is to instead define environments where we should indent math delimiters (this could be configurable), and then only indent on e.g. `{ ... }` and perhaps `[ ... ]` outside of these environments.

**Comment by clason** [comment]
Sounds good! I've found another instance where special treatment of math mode leads to incorrect indentation: manual tags. Here's an example for the test files:

```tex
\begin{theorem}                                                                   
    \begin{equation}                                                              
        x^2 = 2                                                                   
    \tag{$P$}                                                                     
\end{equation}                                                                    
\end{theorem}   
```

(The surrounding environment is important here.) If the tag is `\tag{P}`, the lines are indented correctly.

**Comment by clason** [comment]
Regarding syntax highlighting/indenting inline code (listings, minted, lua etc.), https://github.com/Shougo/context_filetype.vim seems like it could be helpful?

**Comment by lervag** [comment]
@clason Thanks for noticing. I've pushed changes to the branch. I suggest you do

```sh
git checkout master
git fetch
git checkout issue-643/...
git reset --hard origin/issue-643
```

The reason is that I've forced pushed to the branch (something I allow myself to do in separate branches, but _never_ in master). In any case, I've now:

- Added some of the recent updates to the master branch that improves speed for verbatim and tikz environments.
- In the branch, I've added an option to set a "simple" delimiter indent method, which only indents on "modifier math delimiters", such as `\left( ... \right)` or `\left{ ... \right}`, but not on e.g. `( ... )` and `{ ... }`. This is, as expected, _much_ faster, but the question is if it is acceptable (or near acceptable) as rule for indenting.

**Comment by clason** [comment]
Yes, that's now impressively fast! Two regressions I noticed:
* `\[...\]` is not recognized as math mode and not indented; similarly, `\begin{align}...\end{align}` is not treated as math mode (but of course indented as a `\begin...\end` pair).
* Contrary to your original proposal, `{...}` is not indented anywhere (useful, e.g., for a long `\caption`) -- did you change your mind on this?

**Comment by lervag** [comment]
Could you try the latest version? It now works much more as expected, I think, e.g. it passes all existing Vader tests for indentation. It indents on `\[...\]` and `{...}` is still indented.

If we can agree that this is getting close to a working solution, then I think we can finalize it and merge in not too long. I want to clean up the code a little bit first, and we have to decide if the new delimiter indentation should be default or not. I think I might make it default, because it is somthing like 10 times faster.

**Comment by lervag** [comment]
Note, you will have to do a hard reset, because I have again rebased on top of master. I'm sorry for the inconvenicence...

**Comment by clason** [comment]
Very nice! I'm more than happy with that. I agree that merging now (or rather, soon) is a good idea (as is making this the default, but that's no surprise...)

Thank you for implementing this!

**Comment by lervag** [comment]
Sorry for the delay. I'm cleaning up, rebasing and merging now.

**Comment by lervag** [comment]
I'm curious: Is there any reason to keep the old style of delimiter indentation?

**Comment by clason** [comment]
No worries! It's not that something is broken currently.

I have to admit that I lost track a bit: What exactly do you mean by "old style" delimiter indentation?

**Comment by lervag** [comment]
I mean: The current PR implements a "simple" method that is faster, but that simply indents based on a (complicated) regex that matches any "modified" math delimiters, in addition to `\[ ... \]` and `{ ... }`. The old style that parses each line and only indents math delimiters in math environments is still there.

I actually think that I should remove the old version and remove the option. If anyone thinks something is missing I think I rather want to have the discussion and improve a singular method of indentation.

If there is something that really should be optional, then I want it to be apparent after a discussion.

What do you think?

**Comment by clason** [comment]
Ah, I see. Yes, I agree, having a single method is preferable. (I would definitely choose the new one over the old one! (No surprise...)) 

Merging this now even at the cost of possible regressions and fine-tuning afterwards if (when) they are  reported sounds like the best option.

**Comment by lervag** [comment]
Ok, I've simplified, rebased. Just waiting for tests to complete, then I'll merge.

**Comment by lervag** [comment]
Feel free to reopen or open a new issue if you see any regressions or have ideas for fine tuning.
