### ISSUE TITLE
MacVim – vimtex#latexmk was not initialized

### ISSUE THREAD

**Issue by imantdaunhawer** [lervag/vimtex#647]
Vimtex runs smoothly when I use it in the terminal. Yet, when I try to open a `.tex` file from within 
MacVim.app, I get the following warnings:
```
vimtex warning: latexmk is not executable
- vimtex#latexmk was not initialized!
vimtex warning: bibtex is not executable
- bibtex completion is not available!
Press any key to continue ...  
```

The file then opens, but I cannot run `:VimtexCompile` (not an editor command). Some other commands are available (e.g. VimtexView, VimtexReload, ...), yet I cannot work interactively as I've been used through running vim in the terminal.

I have no clue why vimtex won't work with the graphical application and have not experienced a problem with any other plugin so far. Thus, I'd greatly appreciate if you help me out.

### .vimrc 
```
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'
let g:vimtex_view_general_options_latexmk = '-r 1'
```

### .latexmkrc
```
$pdflatex = 'pdflatex -synctex=1 %O %S';
```

**Comment by manu-mannattil** [comment]
This is most likely an issue of MacVim not being able to find the
`latexmk` and `bibtex` executables.  Are you sure that your `PATH`
environment variable contains the parent directory of the `latexmk`
executable?  Try `:echo $PATH` from within MacVim and Vim in a terminal.

**Comment by imantdaunhawer** [comment]
Absolutely right, there is a bug in the OS X zsh setup, that results in the MacVim path not being set properly (see here: http://stackoverflow.com/questions/3344704/path-variable-not-properly-set-in-gvim-macvim-when-it-is-opened-from-the-finder).

`ln -s ~/.zshrc ~/.zprofile`
solved the problem for me.

Thank you very much for leading me in the right direction :)

**Comment by lervag** [comment]
Thank you, @manu-mannattil, for pitching in and helping out! Sorry, @imantdaunhawer, for not being more helpful. It's a little bit much going on right now, so I'm lagging behind on vimtex issues. I hope to catch up on the new year.
