### ISSUE TITLE
Feature request: syntax highlighting for all natbib citation commands

### ISSUE THREAD

**Issue by alefa** [lervag/vimtex#648]
The current version of vimtex has syntax highlighting for the two most commonly used natbib citation commands: \citep{} and \citet{}. It would be nice if the other natbib commands would be highlighted correctly as well. According to the [natbib reference sheet](http://mirrors.ctan.org/macros/latex/contrib/natbib/natnotes.pdf), the missing commands are:
\citet*{}
\citealt{}
\citealt*{}
\citealp{}
\citealp*{}
\citenum{}
\citetext{}
\citeauthor{}
\citeauthor*{}
\citeyear{}
\citeyearpar{}

**Comment by lervag** [comment]
I think it should work now. Please test.

**Comment by alefa** [comment]
Wow, thanks a lot for addressing this so quickly. It works, but I just noticed another small issue with the syntax highlighting of natbib commands. I've opened a separate issue (#649) for that one.

**Comment by lervag** [comment]
No problem. I'll look at the other issue when I get the time. :)
