### ISSUE TITLE
Inconsistent highlighting of natbib citation commands with/without square brackets

### ISSUE THREAD

**Issue by alefa** [lervag/vimtex#649]
Natbib citation commands can be given optional text in square brackets to be put before or after the citation. For example, to cite "Smith et al. 2000 and references therein", one can use the command \citep[][and references therein]{smith2000}. I noticed that vimtex's syntax highlighting differs between commands with these square brackets and commands without. Here is a minimal example tex file:

```latex
\documentclass{article}

\usepackage{natbib}

\begin{document}

This is a citation without square brackets \citep{bibtexkey1}, 
and this is one with square brackets \citep[e.g.][]{bibtexkey2}.

\end{document}

```
[Here's](https://imgur.com/a/MzCRJ) a screenshot of the difference on my system (using Neovim).
I assume that this difference is not by design. Would it be possible to use the same highlighting for both types of citations?

**Comment by lervag** [comment]
Seems to work now. It was a silly bug in a regex. I think the natbib/biblatex cite commands should now be fully covered and working as desired.

**Comment by alefa** [comment]
Excellent! Thanks a lot!

**Comment by lervag** [comment]
No problem. Thanks for noticing and reporting :)
