### ISSUE TITLE
Support for text color settings

### ISSUE THREAD

**Issue by ngphuoc** [lervag/vimtex#654]
I use [gruvbox](https://github.com/morhetz/gruvbox) colorscheme which require [modified colors](https://github.com/morhetz/gruvbox/blob/master/gruvbox_256palette.sh) in my terminal. As a result, the conceal text color of formulae appears in a darkgrey color on a dark background, rendered the formulae unreadable. My tex example is:
```tex
\documentclass[12pt]{article}
\begin{document}
$\int_0^\infty \cos (k t) e^{-s t} d t = \frac{s}{s^2 + k^2}$
\end{document}
```
Is there any option to change colors for the concealed text? Or is there any predefined option/group/syntax for use with the vim's highlight command?

**Comment by lervag** [comment]
This is basically off topic, as far as I can understand. However, I can try to help if I can understand what you are trying to do. Can you post a picture of how it looks, and then explain again what you are trying to achieve?

What happens if you turn off conceal with `set conceallevel=0` (you can do this manually after opening a TeX file). I don't think the colors have anything to do with the conceal option.

It is the syntax plugin that defines which colors to use. See `:h vimtex-syntax` for some information about this. In particular, note that vimtex does _not_ provide a full syntax plugin. Instead, it relies on the syntax plugin that ships with Vim, but adds some tweaks on top of it.

If the colors do not look good for LaTeX, then you could consider to change your colorscheme. If not, then I would rather raise this issue with the colorscheme author.

**Comment by ngphuoc** [comment]
Below is my screenshot
![screenshot from 2017-01-09 23-46-58](https://cloud.githubusercontent.com/assets/23738797/21767142/69594f36-d6c6-11e6-8855-1dd94e15a55d.png)

And the screenshot with ```set conceallevel=0```
![screenshot from 2017-01-09 23-52-02](https://cloud.githubusercontent.com/assets/23738797/21767187/a8696de6-d6c6-11e6-9fe0-683909777493.png)

And a screenshot with conceal text in markdown syntax (I use plasticboy/vim-markdown). 
![screenshot from 2017-01-09 23-57-44](https://cloud.githubusercontent.com/assets/23738797/21767320/8a641980-d6c7-11e6-9ca0-6ad320e69fef.png)
This conceal text has better contrast.

**Comment by lervag** [comment]
Did you read `:h vimtex-syntax`? As I said, vimtex only applies some minor improvements over the internal syntax plugin.

A quick search in the help gave me this:

```
'conceallevel' 'cole'   *'conceallevel'* *'cole'*
      number (default 0)
      local to window
      {not in Vi}
      {not available when compiled without the |+conceal|
      feature}
  Determine how text with the "conceal" syntax attribute |:syn-conceal|
  is shown:

  Value   Effect ~
  0   Text is shown normally
  1   Each block of concealed text is replaced with one
      character.  If the syntax item does not have a custom
      replacement character defined (see |:syn-cchar|) the
      character defined in 'listchars' is used (default is a
      space).
      It is highlighted with the "Conceal" highlight group.
  2   Concealed text is completely hidden unless it has a
      custom replacement character defined (see
      |:syn-cchar|).
  3   Concealed text is completely hidden.

  Note: in the cursor line concealed text is not hidden, so that you can
  edit and copy the text.  This can be changed with the 'concealcursor'
  option.
```

Notice that "It is highlighted with the Conceal highlight group". Reading further (`:h hl-Conceal`):

```
Conceal		placeholder characters substituted for concealed
		text (see 'conceallevel')
```

Thus, I think `Conceal` is what you're after.

**Comment by ngphuoc** [comment]
Yes I did read ```:h vimtex-syntax```. It has no information about conceal though:
```
==============================================================================         SYNTAX HIGHLIGHTING                                             vimtex-syntax

Vim ships with syntax highlighting for LaTeX documents out of the box, please
see ft-tex-syntax.  vimtex therefore does not provide its own syntax
highlighting.  However, vimtex does add some minor improvements:

- Support for biblatex and natbib package
- Support for cleveref package
- Improved highlighting of listings package
- Nested syntax highlighting for dot2tex
- Nested syntax highlighting for minted (see g:vimtex_syntax_minted)

Before enabling additional syntax highlighting, vimtex also checks the
g:tex_fast variable (defined by ft-tex-syntax) that allows one to
selectively enable or disable highlighting for specific groups.  If
g:tex_fast is set, additional syntax highlighting for bold, italic, and
reference groups are enabled only if they are explicitly allowed.

==============================================================================
```

Thank you! ```Conceal``` is exactly what I am looking for. I changed the highlight of ```Conceal``` to values of ```Normal``` and it looks fine now.

You are right. I need to report to the colorscheme's author.

Thanks again!

**Comment by lervag** [comment]
No, the point of reading `:h vimtex-syntax` was to make you notice `ft-tex-syntax` and then read that. But I guess I could have been more explicit.

In any case, I'm happy we found the problem, and good luck with suggesting an update to the colorscheem. :)

**Comment by maikol-solis** [comment]
Hi. Just a newbie question.

How do I could avoid that `set conceallevel=1` removes the dollar symbols ($) in an inline math expression?

The first two examples showed by @ngphuoc  (https://github.com/lervag/vimtex/issues/654#issuecomment-271279586) happens to me.   I like how the symbols looks like with `concealevel=1` but if I insert a dollar ($) to start an inline math expression, it completely disappears. 

If only the dollars symbols could show permanently while editing the file, this feature would be perfect.

**Comment by lervag** [comment]
Hi @maikol-solis! First, please note that it would be much better to make a new issue and refer to this issue, even though it is a quick question.

You can control the LaTeX symbol conceal with `g:tex_conceal`, see `:h g:tex_conceal`. This is not part of vimtex, though, it is part of the built in LaTeX syntax highlighting.

I think you would want something like `let g:tex_conceal = 'amgs'`.

**Comment by maikol-solis** [comment]
Thanks @lervag the next time I will open a new issue. And yes, your suggestion worked perfectly. 

Best.

**Comment by lervag** [comment]
Great, happy to hear it. :)

**Comment by Bthxtly** [comment]
I accidentally find that the plug indentline (https://github.com/Yggdroot/indentLine) changes the default conceal color, so I solve the problem by add `let g:indentLine_setColors = 0` to my vimrc :)
