### ISSUE TITLE
Zathura forward search isn't working

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#656]
### Explain the issue

Zathura forward search isn't working, but backward is working (sic!)!

Shortcut `\lv` only opens zathura but there is no jump to specific line and there is no highlight that line. Whereas `right click` together with `Ctrl` working great and move vim cursor to expected position.

I'm on Arch linux and have following packages:

```
community/zathura 0.3.6-3 [installed]
community/zathura-djvu 0.2.5-2 [installed]
community/zathura-pdf-poppler 0.2.6-2 [installed]
community/zathura-ps 0.2.3-2 [installed]
community/xdotool 3.20160805.1-1 [installed]
extra/texlive-core 2016.42515-2 (texlive-most) [installed]
extra/gvim 8.0.0149-1 [installed]
extra/vim-runtime 8.0.0149-1 [installed]
```

To test I run vim like this: `vim --servername VIM -u minivimrc test.tex`. Same issue with neovim.

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\pagebreak

Hello World again!

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

call plug#begin('~/.vim/plugged/')
Plug 'lervag/vimtex'
call plug#end()

let g:latex_view_general_viewer = 'zathura'
let g:vimtex_view_method = 'zathura'
```

### Latexmkrc configuration

```latexmkrc
$pdflatex = 'pdflatex -synctex=1 %O %S';
```

**Comment by lervag** [comment]
Strange. This works as expected for me on an up to date Arch Linux.

Note: The option `g:latex_view_general_viewer` does nothing. It is not a proper vimtex option, and the corresponding `g:vimtex_...` option is not needed when you set the view method to `zathura`.

**Comment by lervag** [comment]
I'm using the `mupdf` backend for zathura. I also don't have the djvu or ps packages.

**Comment by petRUShka** [comment]
That is really strange because after reboot it is working as expected.

I've upgraded system (`pacman -Suy`) but I don't think that is the case. Possible some strange Xorg bug or something else.

**Comment by lervag** [comment]
Or perhaps `libsynctex` or something like that was updated? In any case, good to hear that it works.

**Comment by petRUShka** [comment]
Possibly, but not libsynctex, last upgrade was before New Year:

```
[2016-12-30 23:36] [ALPM] upgraded libsynctex (2016.41290-9 -> 2016.41290-10)
```

**Comment by lervag** [comment]
Ok. Well, I guess we'll never know. The important thing is that it works :)

**Comment by petRUShka** [comment]
Exactly :) I've just added information mostly for people that find this issue by searching.

**Comment by rieser** [comment]
I had a similar problem on Ubuntu 19.04, vim 8.1. It seems that using the line:

let g:latex_view_general_viewer = 'zathura'

in your .vimrc will, indeed, set the viewer to zathura, but foward searching is broken and a new instance of zathura is opened every time one types <lead>lv. However, if you only use the line

let g:latex_view_method = 'zathura'

then everything works correctly.

**Comment by lervag** [comment]
@rieser Please do not "necrobump" old issues. If you have a question or problem, open a new issue. The information in your comment does not add to this thread. `g:vimtex_view_method` was already used in the original post, and I mentioned in my _first_ reply that `g:latex_view_general_viewer` is not a valid option and is simply ignored.
