### ISSUE TITLE
Syntax highlighting of nested luacode: directlua vs environment luacode

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#660]
I have copied a piece of lua code from the web which uses `\directlua` to insert it into the latex document:

![directlua-vs-env-luacode](https://cloud.githubusercontent.com/assets/371756/21931438/af3b5526-d99b-11e6-92f8-7951943b1d21.png)

The syntax highlighting, however, is not as intended (see screenshot and compare it to the version using `\begin{luacode}`)

The corresponding definition in `vimtex/after/syntax/tex.vim` looks quite the same
```viml
" {{{1 Nested syntax highlighting for lualatex
unlet b:current_syntax
syntax include @LUA syntax/lua.vim
syntax region texZone
      \ start='\\begin{luacode\*\?}'rs=s
      \ end='\\end{luacode\*\?}'re=e
      \ keepend
      \ transparent
      \ contains=texBeginEnd,@LUA
syntax region texZone
      \ start='\\\(directlua\|luadirect\){'rs=s
      \ end='}'re=e
      \ keepend
      \ transparent
      \ contains=texBeginEnd,@LUA
let b:current_syntax = 'tex'
```

Using vim-scriptease `zS` on `if`

1. `\directlua`: `luaTable texZone`
2. `\begin{luacode}`: `luaCond luaIfThen texZone`

**Comment by lervag** [comment]
Think latest commit should fix this.

**Comment by kiryph** [comment]
Thanks. no difference in syntax highlighting anymore.

vim-scriptease zS on `if` gives now

in `\directlua`: luaCond luaIfThen texZoneLua
in `\begin{luacode}`: luaCond luaIfThen texZone

**Comment by lervag** [comment]
Sounds about right. :)
