### ISSUE TITLE
Highlighting nested new/renew commands/environments

### ISSUE THREAD

**Issue by coachshea** [lervag/vimtex#662]
First, as always, thank you for this amazing plugging. I recently ran into an unusual situation.  I was nesting calls to renew command within a newenvironment. I discovered that, in order to keep track of the nested variables it is necessary to include a relative number of `#`s. For example (using two commands for simplicity): 

```tex
\newcommand{\mycommand}[1]{%
  \renewcommand{\myothercommand}[1]{%
      \dosomethingwithouterarg{#1}\dosomethingwithinnerarg{##1}}}
```

The `#1` displays correctly (in this case no highlighting), but the `##1`  incorrectly highlights the second `#` and the `1`. I was wondering if there was a way, without breaking something else, to adjust the syntax rules to allow this to display correctly. Thank you for your consideration.

**Comment by lervag** [comment]
I added support both for the nested (re)newcommands, for nested paramters (I use a different highlight color for nested parameters). I also added support for arguments to (re)newenvironments.

Let me know what you think!

**Comment by coachshea** [comment]
Thank you

**Comment by lervag** [comment]
No problem! I'm sorry for not responding sooner, btw. But as one say: Better late than never...
