### ISSUE TITLE
Found a (strange) corner case with new graphicspath processing 

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#664]
After a lot of searching around, I think I have restricted the problem I am seeing with graphicspath processing in omnicompletion. 

I am attaching a zip file with the case and a couple screenshots to explain the problem. Unzip the thing and then, from the directory `completion`, do a `gvim -u ../minivimrc test3.tex`. 

What happens is shown in screenshot 1: the `^X^O` command shows only the contents of the first directory, `../Pics-generic`. 

Now, if you delete the three lines of the `textblock*` environment, and then reload the file (`:w :e`) now the situation is correct, like in screenshot 2. You can alternatively open `test4.tex`, which is the same as `test3.tex` without that environment.   

This is so "Heisenbug" that I really feel strange submitting it --- it is just to see if it's possible to reproduce it or not. 

File: 
[test-completion-3.zip](https://github.com/lervag/vimtex/files/717460/test-completion-3.zip)

Screenshot1:
![selection_052](https://cloud.githubusercontent.com/assets/6414907/22120411/e14622ba-de7f-11e6-98d9-7ce6a91d7c39.png)

Screenshot2:
![selection_053](https://cloud.githubusercontent.com/assets/6414907/22120431/f1fb42ca-de7f-11e6-9e6d-5d47ef53e54f.png)

**Comment by clason** [comment]
I think the erroneous extra closing `}` in line 9 is throwing the code for a loop (probably because it assumes the `graphicpath` directive closes with `}}`).

**Comment by Rmano** [comment]
Frigg... I have trimmed too much . It's 

```
\addtobeamertemplate{frametitle}{}{%
\begin{textblock*}{100mm}(.98\textwidth,0.1cm)
    \includegraphics[height=0.9cm]{logo-eb}
\end{textblock*}}
```

which is now balanced, but the problem is still there.

**Comment by clason** [comment]
And it again goes away if you break up the `}}`. (N.B.: whitespace doesn't make a difference, so you need to add a dummy `\nop` (TeX's "no operation") between the two.)

**Comment by lervag** [comment]
The problem was that the `graphicspath` regex matched too much. What I am doing is that I am joing all the preamble lines into a single string, then doing a regex match for the `\graphicspath` command and grabbing everything between `{{` and `}}` (with possible spaces in between). Since I used `.*`, this ended up grabbing your textblock environment as well. It is fixed by changing to `.\{-}`, which matches as few as possible/necessary characters.

**Comment by Rmano** [comment]
Thanks! 
It works perfectly!

Yes, matching balanced pairs with regexs is from difficult to impossible, it seems... I have a couple of links that give me headache all the times. It seems that this is regex-engine dependent... 

I am pasting the links here --- I hope they can be useful somehow in the future.

http://www.regular-expressions.info/balancing.html
http://stackoverflow.com/questions/15301708/perl-regular-expression-match-nested-brackets
http://stackoverflow.com/questions/1099178/matching-nested-structures-with-regular-expressions-in-python

Cheers!

**Comment by lervag** [comment]
I know, regexes don't work for matching parantheses (or similar). But this case was easier, since it was safe to assume that the pattern `}\s*}` only appears at the end of the `\graphicspath` command.

In any case, thanks for the links! Perhaps they will be useful :)
