### ISSUE TITLE
-bibtex option to latexmk?

### ISSUE THREAD

**Issue by rionda** [lervag/vimtex#665]
Should "-bibtex" be passed to latexmk by default ? 
I was a bit surprised that it isn't.

**Comment by lervag** [comment]
No, there is no reason to. I have never had any problems with bibtex and `latexmk` without adding that option. If you think it should be passed by default, then please explain in more detail why you think that.

To me, it seems `latexmk` works well both with `natbib` and `biblatex`, and with `bibtex` and `biber`, without adding any extra options.

**Comment by rionda** [comment]
Well, I don't know why, but just recently I cleaned up all the latex auxiliary files, then open a tex file (not the main tex file of the "project"), started the continuous compilation and it gave warning for undefined citations. I then run bibtex manually in the directory and the continuous compilation worked without issues. If I set
```
let g:vimtex_latexmk_options = '-pdf -verbose -bibtex -file-line-error -synctex=1 --interaction=nonstopmode'
```
the issue goes away.

**Comment by lervag** [comment]
Strange. That is indeed interesting. Could you make a minimal example of this? I understand it might be bothersome, but it will be a great help for me.

**Comment by rionda** [comment]
Yes, I'll send you one later.

**Comment by rionda** [comment]
False alarm. I cannot reproduce it anymore.

**Comment by lervag** [comment]
Thanks. :)

**Comment by krishnakumarg1984** [comment]
I am encountering the same issue. 

I need to use

```let g:vimtex_latexmk_options = '-pdf -verbose -bibtex -file-line-error -synctex=1 --interaction=nonstopmode'```

to compile my document. Otherwise ```latexmk``` complains that ```no bbl file exists``` .

Please investigate

**Comment by lervag** [comment]
> Please investigate

Please open a new issue and describe it as suggested in the issue template.

As explained in this thread, things should work as expected without the `-bibtex` option. You need to provide a full minimal example with a clear description if you want to change my mind.

----

By the way:

```vim
" This is not a valid option for vimtex (it is deprecated)
let g:vimtex_latexmk_options = '-pdf -verbose -bibtex -file-line-error -synctex=1 --interaction=nonstopmode'

" Instead do this
let g:vimtex_compiler_latexmk = {
    \ 'options' : '-pdf -verbose -bibtex -file-line-error -synctex=1 --interaction=nonstopmode',
    \}
```
