### ISSUE TITLE
Problem with tab indentation when using gq in item list.

### ISSUE THREAD

**Issue by nrontsis** [lervag/vimtex#667]
### Issue
When using tabs for indentation, `gq` command changes tabs to spaces in long `\item` lines that are broken.
### Minimal working example
Executing `gqip` inside the following enumerate environment changes the first `\item` line from tab-indented to space-indented.
```tex
\documentclass{minimal}
\begin{document}

\begin{enumerate}
	\item This is some very very very big line that is going to break into two lines at some point.
	\item Test	
\end{enumerate}

\end{document}
```

### Minimal vimrc file

```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

au FileType tex setlocal nojoinspaces
let g:vimtex_format_enabled = 1

syntax on
filetype plugin indent on

set tw=80
set noet ci pi sts=0 sw=4 ts=4
```

**Comment by lervag** [comment]
I never considered tabs when implementing this feature. I think I could solve this if I understood how to properly choose whether or not to insert tabs or spaces. Is this correct: If `&noexpandtab`, then use tabs and convert the indentation into `indent()/&tabstop` number of tabs?

**Comment by nrontsis** [comment]
@lervag thanks very much for the quick reply and sorry for my delayed one :)

That sounds good to me. Could there be a case where indent()/&tabstop is not an integer?

**Comment by nrontsis** [comment]
On a similar note, `gq` counts tabs as single space hence underestimating the `textwidth` of lines.

**Comment by lervag** [comment]
I think this should work now. Sorry for taking so long.
