### ISSUE TITLE
Parse \graphicspath subdirectories for img completion

### ISSUE THREAD

**Issue by napseis** [lervag/vimtex#668]
hi,
Related to issue #640 and #657 , as requested by @lervag , I'm opening a new issue.

The completion of \includegraphics does work now, but it does not parse the subfolders inside \graphicspath and hence fails to propose the images files.

thanks!

**Comment by lervag** [comment]
I'm curious, do anyone know what the rules are for what paths are allowed in `\includegraphics`? That is, where are the figures searched? I am suspecting this:

1. Paths in `\graphicspath`
2. Relative to root LaTeX file
3. Relative to current included LaTeX file (?)

**Comment by Rmano** [comment]
The search is not recursive (at least, I think). What happens is that if you say 
```
\graphicspath{{mypath}}
```
then you can do `\includegraphics{alfa/beta.eps}` then `./alfa/beta.eps` and `mypath/alfa/beta.eps` are searched. I mean, when the files are in subdirectories, the relative paths have to be specified. 

So my idea is that the completion is done with `**/*.*` for every path `P` in `graphicspath`s, and then the substitution string is made by the matches with the initial `P` stripped. I mean, if I  have
```
mypath/pict.eps
mypath/before/state.png
mypath/after/state.png
```
in the expansion suggestions I should find `pict.eps`, `after/state.png` and `before/state.png` (well, these should be the string that finally are going into the `\includegraphics`).

**Comment by lervag** [comment]
Ok, I think it should work as expected now. Please test. I tested on some large projects I have, and it seems to run quite smoothly also for large amounts of files.

**Comment by Rmano** [comment]
I checked on a (admittedly small) example and it seems to work perfectly. Thanks again!

**Comment by napseis** [comment]
I agree, this is awesome !

**Comment by lervag** [comment]
Great, I'm happy it works :)
