### ISSUE TITLE
Advanced 'includeexpr' using kpsewhich

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#673]
I would like to use `gf` to open class and package files within the TDS/texmf tree from my current tex document. I was able to achieve this with following vim function assigned to `includeexpr` defined in `~/.vim/after/ftplugin/tex.vim`:
```viml
setlocal suffixesadd+=.sty,.cls
function! IncludeExpr()
  " copy from $VIMRUNTIME/ftplugin/tex.vim
  let ffile = findfile(substitute(v:fname, '^.\\{-}{\\|}.*', '', 'g'))
  if !filereadable(ffile)
      for suff in split(&suffixesadd,",")
          let kpsefile = systemlist('kpsewhich '.v:fname.suff)
          if len(kpsefile) != 0 && filereadable(kpsefile[0])
              return kpsefile[0]
          endif
      endfor
  endif
  return ffile
endfunction
setlocal includeexpr=IncludeExpr()
```

Now I can move the cursor on `silence`, `article`, `MinionPro` in this snippet
```tex
\RequirePackage{silence}
\documentclass{article}
\usepackage{MinionPro}
\begin{document}
\end{document}
```
to open within vim following files:

- `/usr/local/texlive/2016/texmf-dist/tex/latex/silence/silence.sty`
- `/usr/local/texlive/2016/texmf-dist/tex/latex/base/article.cls`
- `/usr/local/texlive/texmf-local/tex/latex/MinionPro/MinionPro.sty`

Would you consider adding such extended behavior for `gf` to `vimtex`?

**Update**  
Another approach is to get the directories in which `kpsewhich` looks by `kpsewhich --var TEXDOCS` and add them to the path variable.

Sometimes I have a local `~/project/texmf/` folder  which I have to add to the environment variable `$TEXINPUTS` in `~/project/latexmkrc` with

```perl
{
no warnings 'uninitialized';
$ENV{'TEXINPUTS'}='./texmf//:' . $ENV{'TEXINPUTS'};
}
```
(http://tex.stackexchange.com/a/50847/8917)
Now, `latexmk` compiles with the correct files.
`kpsewhich` does not know about this and would not open the files within this folder. So `vimtex` could be  sensible to the definition of the environment variable `$TEXINPUTS` set in `latexmkrc`.

**Comment by lervag** [comment]
I think this looks useful. I've begun work on this, pushing an update where I've extracted the `includeexpr` into a function. It needs more refinement still, in order to get valid candidates. At the moment, I only test with the suffixes and `filereadable`. I think we could abstract `filereadable` into a double test that first checks if a name is readable from the general path, then if `kpsewhich` can find it.

I also think you have a point about `$TEXINPUTS`, although I don't quite see how to use it. Can I use it with `kpsewhich`?

**Comment by kiryph** [comment]
Thanks as always for adding this.

A few notes which hopefully help to clarify things:

`kpsewhich` takes certain paths by default into account (see `$ kpsewhich --var TEXDOCS`). If you want to add an additional path you can use the environment variable `$TEXINPUTS` (and other) or make adjustments in one of the config files `texmf.cnf`.

However, if I want to add a certain subdirectory of one latex project, I personally would not edit one of the `texmf.cnf` files but only set an environment variable.

Environment variables as you might know can be set by the user temporarily in the command line, place them in their .bashrc/.zshrc, in Makefiles and also in latexmkrc files.

My motivation are following questions

- http://tex.stackexchange.com/questions/50697/how-can-i-keep-a-clean-document-folder-with-custom-cls-sty-bst-files-in-a-s/
- http://tex.stackexchange.com/questions/34203/where-to-put-sty-and-cls-file-for-project

If someone makes a change to $TEXINPUTS in `mylatex-project/latexmkrc`, latexmk would set the environment variable and pdflatex would work as expected. Of course, `kpsewhich` does not know about latexmk. So it would not know about TEXINPUTS in latexmkrc.

However, I use exclusively latexmk for building and vim for editing. So if these two tools know about the one location I add a project specific search tex stuff path, it would mostly serve my needs. Of course, if I run myself `kpsewhich` on the commandline it would not find files within the additional folder.

Background on  Kpathsea path searching can be found here https://www.tug.org/texlive/doc/texlive-en/texlive-en.html#x1-550007.1

**Comment by lervag** [comment]
Ok, I've now added the first variant of this based on your initial suggestion. This seems to work very well. But as you say, it won't work for the project specific cases you describe. Here we should find a way to pass `$TEXINPUTS` to kpsewhich, which would solve the problem, I think. Perhaps it would be possible to parse the latexmkrc file? Although, that does seem quite a lot of work for very borderline cases.

Would you be able to find a workflow that would not require much more advanced implementations on the vimtex side?

**Comment by lervag** [comment]
Btw, remaining tasks include:

- [ ] Add description in documentation (and perhaps README)
- [ ] Determine if there are any bad side effects from setting `suffixesadd=.tex,.sty,.cls` (previously I only had `.tex`) --- perhaps I should also include `.bib`?

**Comment by kiryph** [comment]
I've noticed that `gf` on `\usepackage{booktabs,array}` does not work. Apparently, the comma is not considered as filename separator. Vim searches for filename `'booktabs,array'` plus suffixesadd.

Do you (@lervag) know how to fix this?

**Comment by lervag** [comment]
The reason this happens is because the Vim option `isfname` contains `,`. See `:h 'isfname'`. However, I think this can be called "common", so I pushed a quickfix that I think should work without ruining anything.

**Comment by lervag** [comment]
There does not seem to be any bad side effects from setting `suffixesadd=.tex,.sty,.cls`.

**Comment by kiryph** [comment]
@lervag I think this issue is resolved. Do you leave it open until you have added a note to the documentation and README.md?

**Comment by lervag** [comment]
Yes, I'll try to add some documentation pretty soon.

**Comment by lervag** [comment]
I'd be happy to get some feedback on the updated docs/README.

**Comment by kiryph** [comment]
I close this issue since you've marked the last check box :smiley:.

Thanks for all your effort. I am really impressed by your passion and capability to extend this plugin :+1: . Sometimes I have just too many ideas for vimtex. Sorry for that. BTW vimtex is this week one of the trending vim projects on github: https://github.com/trending/vim?since=weekly.

**Comment by lervag** [comment]
Thanks, @kiryph. Kind words are always a pleasure to read and motivates me for further work. :)

Also, thanks for contributing ideas, suggestions and constructive criticisms. It is very nice to get some honest feedback and good ideas!
