### ISSUE TITLE
okular could not open file:///home/phuoc/test/build/main.pdf%23src:1/home/phuoc/test/main.ltx

### ISSUE THREAD

**Issue by ngphuoc** [lervag/vimtex#676]
vimtex seems to pass ```#``` as ```%23``` to okular and okular could not do forward search. I tried both ```let g:vimtex_view_general_options = '--unique @pdf\#src:@line@tex'``` and ```let g:vimtex_view_general_options = '--unique @pdf\\#src:@line@tex'``` but still got the error.

**Comment by lervag** [comment]
What happens if you use the extension `.tex` instead of `.ltx`?

**Comment by ngphuoc** [comment]
I have checked that I got the same error.

**Comment by lervag** [comment]
Ok, strange. Could you please specify a full minimal example as described in the issue template?

**Comment by ngphuoc** [comment]
```latex
\documentclass[12pt]{article}
\begin{document}
$\int_0^\infty \cos (k t) e^{-s t} d t = \frac{s}{s^2 + k^2}$
\end{document}
```
I use okular version 1.0.1

**Comment by lervag** [comment]
I don't use Okular, so I wouldn't know. But again, you are not specifying a full minimal example, in particular a minimal vimrc file.

I'll install Okular and test this myself in the meantime.

**Comment by lervag** [comment]
Ok, here it seems everything works. I used okular version 1.0.1, which seems to be the newest version.

**Comment by clason** [comment]
I've had exactly the same problem when I first set up `vimtex` with Okular; sometime later I tried again and it suddenly worked. Not looking a gift horse in the mouth, I did not investigate further, but it does point towards a(n intermittent) problem with Okular. (The same ` vimtex` installation worked with MacVim.)

**Comment by ngphuoc** [comment]
Thanks lervag and clason for checking and explaining the problem. I will switch to zathura for now.

**Comment by lervag** [comment]
No problem, @ngphuoc. I prefer `zathura` myself (it even has Vim-like keybindings).
