### ISSUE TITLE
Alignment problem with ampersands and set of parentheses

### ISSUE THREAD

**Issue by nrontsis** [lervag/vimtex#677]
### Issue
Strange alignment with ampersands and a set of parentheses that spans across multiple lines. Issue remains when `vimtex_indent_on_ampersands` is set to `0` (see #613).

### Minimal working example
The following alignment occurs in the example below

```tex
\documentclass{minimal}

% Problematic alignment
\begin{document}

\begin{align}
	&x(
y)
\end{align}

% Correct alignment (given vimtex_indent_on_ampersands=0)
\begin{equation}
	x(
	y)
\end{equation}

\end{document}
```

### Minimal vimrc file

```vim
call plug#begin('~/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()

let g:vimtex_format_enabled = 1
let g:vimtex_indent_on_ampersands = 0

syntax on
filetype plugin indent on
```

**Comment by lervag** [comment]
Thanks, this was actually quite simple, but it took me a while to understand the problem. In any case, it was a bug and I think it is squashed.
