### ISSUE TITLE
Windows, Inverse Search, SumatraPDF, 

### ISSUE THREAD

**Issue by haoyun** [lervag/vimtex#680]
### Explain the issue

It was explained in the documentation that 

```
          Note: It is possible to set up inverse search for SumatraPDF through
                the command line.  This can be utilized to set the correct
                |servername| for inverse search: >

            let g:vimtex_view_general_viewer = 'SumatraPDF -reuse-instance '
                \ . '-inverse-search "gvim --servername ' . v:servername
                \ . ' --remote-send \"^<C-\^>^<C-n^>'
                \ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
                \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
                \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
                \ . ':call remote_foreground('''.v:servername.''')^<CR^>\""'
<
```

But I've tried many times this does not work. A warning appears:
```
vimtex warning: viewer "SumatraPDF -reuse-instance -inverse-search "gvim --serve
rname GVIM --remote-send \"^<C-\^>^<C-n^>:drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv
^<CR^>:execute 'drop ' . fnameescape('\%f')^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>:
call remote_foreground('GVIM')^<CR^>\""" is not executable!
- Please see :h g:vimtex_view_general_viewer
Press any key to continue ...   
```
Finally I found that `g:vimtex_view_general_viewer` does not accept any arguments. Only
`g:vimtex_view_general_viewer = 'SumatraPDF'` works. The correct solution should be

```
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
    \ = ' -forward-search @tex @line @pdf'
    \ . ' -inverse-search "gvim --servername ' . v:servername
    \ . ' --remote-send \"^<C-\^>^<C-n^>'
    \ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
    \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
    \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
    \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
```

Differences are
1. all the options goes to `g:vimtex_view_general_options`.
2. `-forward-search @tex @line @pdf' is added as explained in the previous paragraph in the doc.
3. one more `^<CR^>`  is added to the end, otherwise, gvim (I use 8.0) asks `Press any key to continue ...   `

**Comment by haoyun** [comment]
There is another problem:

The above solution does work, but ``remote_foreground(......)` does not put gvim to the foreground as mentioned in [this post](https://github.com/LaTeX-Box-Team/LaTeX-Box/issues/251).

Actually I do not understand why the suggested solution is so difficult. I just copy and paste. It seems that every vim latex plugin uses this same solution.

But a simple solution
```
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
    \ = ' -forward-search @tex @line @pdf'
    \ . ' -inverse-search "gvim --remote +\%l \%f"'
```
works quite well, at least to me.

**Comment by lervag** [comment]
I don't know this stuff very well, since I don't use Vim on Windows. However, I will take your word for it and update the docs accordingly. I'm curious, is there a reason you removed the `-reuse-instance` option?

Regarding the `remote_foreground` call, I am sorry to say I can't give any explanation as to why it does not work. If you do find a better solution, let me know so that I can update the docs. Thanks!

**Comment by haoyun** [comment]
@lervag It was a mistake that I removed the `-reuse-instance`. Thank you!

**Comment by jdhao** [comment]
@lervag  I am using neovim-qt on Windows and use sumatraPDF for viewing PDF. I wonder how to change the above settings to make it work for backward search in sumatraPDF.

**Comment by lervag** [comment]
@jdhao Please open a new issue for new questions. I do not use Windows, and so I might not be able to answer. By opening a new issue, there might be someone else from the community that might be able to help.

**Comment by jdhao** [comment]
After nearly 2 years, I have finally been able to set up inverse search for Sumatra PDF viewer on windows correctly. See #1964.
