### ISSUE TITLE
setting build_dir at run-time

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#684]
### How to refresh vimtex viewer after setting build_dir?
Setting `g:vimtex_latexmk_build_dir` outside of the `vimrc` breaks the view commands.
Steps to reproduce:
1. `vim -u minvimrc test.tex`
2. `:let g:vimtex_latexmk_build_dir='build'`
3. Compile with `\ll`.   At this point, building succeeds in the build directory and a viewer opens up correctly if in continuous mode (but this is a larger issue for single-shot compilation).
4. Close any open viewer, and try to open a new one with `\lv`:
```vimtex warning: viewer can not read PDF file!```
5. Try to get vimtex to notice the change:
`:VimtexReload`  `\lv`: `vimtex warning: viewer can not read PDF file!`
`:call vimtex#reload()`  `\lv`: `vimtex warning: viewer can not read PDF file!`
`:call vimtex#init()`  `\lv`: `vimtex warning: viewer can not read PDF file!` 
Additionally, `\li` shows the wrong pdf location at this point.  Finally,
`:call b:vimtex.viewer.refresh_paths()`  `\lv`: opens viewer correctly

Is this the intended way to change the build_dir dynamically?  To me, this is unexpected behavior, since no reload is needed for the compiler to recognize the change in directory, and the viewer actually opens up in continuous mode with `\ll`, but not with `\lv`, so there is some difference in logic between the two methods.

### Setting build_dir locally?

This is perhaps more of a request, but why does vimtex store the build directory as a global variable?  vimtex stores much of its data locally for each buffer, but inconsistently.  Ideally, one could specify per-file or per-project build directories; compiling and viewing wouldn't need this global information.  Forgive me if this is covered by #651.

#### test.tex
```tex
\documentclass{minimal}
\begin{document}
Hello World!
\end{document}
```

#### minvimrc
```viml
set nocompatible                                                               
let &rtp = '~/.vim/bundle/vimtex,' . &rtp                                      
let &rtp .= ',~/.vim/bundle/vimtex/after'                                      
filetype plugin indent on                                                      
syntax enable                                                                  
                                                                               
let g:vimtex_view_method = 'zathura'
" let g:vimtex_latexmk_continuous = 0      " optional
```

**Comment by lervag** [comment]
I agree this was unexpected, and it should be fixed now. Also, just for reference, you might be interested in reading #700 and #701, about using the `$out_dir` option in a project specific `.latexmkrc` file to set this dynamically per project.

**Comment by andymass** [comment]
Excellent.  Thank you for this change!

**Comment by lervag** [comment]
No problem :)
