### ISSUE TITLE
Missing \usepackage{color} and \usepackage{hyperref} from examples/book-multifile/preamble.tex ?

### ISSUE THREAD

**Issue by jonascj** [lervag/vimtex#686]
### Explain the issue
I'm trying to compile the test/book-multifile example and If I'm not mistaken there should be a \usepackage{hyperref} and \usepackage{color} in the preamble, otherwise it will not compile correctly, e.g. no red test will appear in the pdf and warnings/errors will be given for \texorpdfstring{} which is from the hyperref package.

Can you confirm this?

### Minimal working example
The distributed examples/book-multifile folder or project.

**Comment by lervag** [comment]
I don't really care if the example compiles, as I use it mostly for testing other stuff. But there is no reason it shouldn't compile, so ...

**Comment by lervag** [comment]
thanks!

**Comment by jonascj** [comment]
I just thought test/ was the holy grail of what should work (like it was a unittest dir or something). So when I started looking into doing multifile projects with vimtex I looked at the example. Thank you for fixing it, I'll try not to fuss about examples again now that I know they are mostly for internal use.

**Comment by lervag** [comment]
No problem. And no, `test/` is simply for testing the vimtex features for debugging and improvements. I understand that it can be confusing, though. :)
