### ISSUE TITLE
Use spaces for aligning instead of tabs

### ISSUE THREAD

**Issue by dedmass** [lervag/vimtex#688]
Is there a way to disable the autoaligning of `&`s? For instance if I am typing in an `align` environment:
```
\begin{align}
    a + b &= b + c\\
    &= d + e
\end{align}
```
This will be automatically adjusted to
```
\begin{align}
    a + b &= b + c\\
          &= d + e
\end{align}
```
The issue is that I am trying to use an indent with tabs, align with spaces style. The vimtex aligning defaults to using tabs. 
```
\begin{align}
>---a + b &= b + c\\
>--->---␣␣&= d + e
\end{align}
```
Instead of what I want which is
```
\begin{align}
>---a + b &= b + c\\
>---␣␣␣␣␣␣&= d + e
\end{align}
```
Is there a way to disable this behavior (so that I can manually align these section) or even better have it use spaces for aligning these elements after the indentation level?

**Comment by dedmass** [comment]
It appears that `g:vimtex_indent_on_ampersands=0` disables the aligning on `&`, but it still would be nice to align with spaces instead of tabs.

**Comment by lervag** [comment]
I can understand that it would be convenient with a feature to allow tab indent and space align. However, I have to admit that I will probably never implement that myself. There are two reasons:

1. I think it will be quite messy. I might be wrong, and I will be very glad to consider a pull request!

2. I personally really dislike mixing tabs and spaces. I can see good reasons for using tabs, but I personally strongly prefer spaces over tabs.

I think `g:vimtex_indent_on_ampersands` should partly solve your issue, though. :)
