### ISSUE TITLE
Add mapping `tsc` for toggle starred command

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#689]
Since there are already `tse` and `tsd`, I think it would be a more consistent user experience to have `tsc` as well to toggle the star version of a command.

Together with surround.vim/sandwich.vim, there would be similar set of mappings for related things to do:

- `dsc` delete surrounding command
- `csc` change surrounding command
- `ysc` add surrouding command
- `tsc` toggle starred surrounding command

The same set of mappings exists for environments (`dse`, `cse`, `yse`, `tse`) and delimiters (`dsd`, `csd`, `ysd`, `tsd`) where for delimiters toggling has a different meaning (toggle between `()` and `\left(\right)`).

**Update**
I have created the pull request #690 which adds `tsc`.

**Comment by lervag** [comment]
Thanks! Both for noticing the missing feature and for implementing it!

I'm closing this, as it was fixed when I merged #690.
