### ISSUE TITLE
Add ranges support for VimtexCoutWords et al.

### ISSUE THREAD

**Issue by thriveth** [lervag/vimtex#692]
### Feature request: Add ranges support for `VimtexCountWords`

First of all, thank you for your great work on VimTeX! I am getting increasingly happy with it as I use it. 

During my current work, I stumbled upon a small feature which could be very useful: to call the word count/character count functions given a range, rather than the entire document. For instance, I might want to know if the abstract of my article is within the limits allowed by the journal, or whatnot. Currently, I have to copy the section into my clipboard and run `xclip -o | wc -w` to do this, and this is not directly difficult, of course. But I think it would be really convenient to be able to select a visual range and call `:VimtexCountWords` (or characters), or pass a range like `:42, 60 VimtexCountWords`

Even though I am no good at Vimscript, I guess it shouldn't be too complicated to implement, so figured it'd be low hanging fruit.

**Comment by clason** [comment]
+1 if that would also make it work with visual selections (which currently fail with  `E481: No range allowed`)!

**Comment by clason** [comment]
@thriveth I don't think it's that easy: `VimtexCountWords` calls an external perl script, [texcount](http://app.uio.no/ifi/texcount/) on the tex file (or the root file of the project, if that is defined). This allows it to do smart counting (ignoring inline math, for example), but this means that (quoting from the documentation)

> TEXcount handles complete LaTeX documents, i.e. that start with \documentclass and has the text between \begin{document} and \end{document}, as well as partial documents made to be included in another LaTeX document. However, in either case, it requires that all groups are closed: {. . . } and \begin. . . \end.

If all you want is a word count of simple text, you can do this with built-in vim commands: Select the text and press `g` followed by `<ctrl-g>`.

**Comment by thriveth** [comment]
@clason  Makes sense. However, I wonder if the wrapper could simply wrap the selection in a minimal preamble and begin/end document environments before passing it to TeXcount, possibly smart-check if they exist, and then return an error message and a hint to the documentation if texcount doesn't exit cleanly? It would limit the functionality of the call, of course, so it might break the law of minimal surprise.

So yeah, maybe it is better left to built in Vim functions after all. :thinking:

**Comment by lervag** [comment]
I've already implemented a similar feature to compile a selected part of the document. This feature will save the selection, add the necessary preamble and `\begin/end{document}` parts, then compile. I could probably reuse the code to implement the desired feature. I'll look into it when I get the time. In the meantime, I think @clason's answer and suggestion is good: `g<c-g>` gives valuable information and would probably be close to what you want anyway.

**Comment by thriveth** [comment]
I still think the feature, if possible, would be useful and add vale to the plugin. `g<c-g>` works fine for short pieces of pure text, like the abstract in my example above, but not past a `figure`, `itemize` or similar environment.

**Comment by lervag** [comment]
I was not able to add this for the `VimtexCountWords` command directly, but I added new commands `VimtexCountSelectedWords` and `...Letters` that work on selections and ranges. Please try and let me know how it works.
