### ISSUE TITLE
Please allow for modifying the bibliography engine

### ISSUE THREAD

**Issue by GijsTimmers** [lervag/vimtex#694]
I would like to use [`bibulous`](https://nzhagen.github.io/bibulous/index.html) for typesetting the bibliography. I looked through the documentation, it seems like this is not yet possible. Please allow for changing the bibliography engine.

**Comment by clason** [comment]
Since `vimtex` uses `latexmk` for compiling, it should be enough to set the latter's `$bibtex` option (either in a (local) `latexmkrc` or a `vimtex` variable).

**Comment by GijsTimmers** [comment]
Thank you!

**Comment by lervag** [comment]
Let me know if you need further explanations on this. If you always use bibulous, then I would suggest to put the option in your "global" `latexmkrc` file, i.e. `$HOME/.latexmkrc`. Else you should put it in your local file, i.e. `/project/path/.latexmkrc`.

**Comment by telemachus** [comment]
@lervag @GijsTimmers I really apologize for being clueless, but can one of you help me to understand what exactly I should add to a `latexmkrc` file in order for it to use Bibulous?

**Comment by lervag** [comment]
@telemachus I have not used Bibolous myself, but I found some links that might be of help:

- https://tex.stackexchange.com/questions/388009/how-can-i-use-bibulous-with-latexmk-from-the-command-line
- http://personal.psu.edu/jcc8//software/latexmk-jcc/latexmk-452c.txt

The latexmk manual _is_ pretty large, but I think you could come far by searching for bibtex.

I hope this helps!

**Comment by telemachus** [comment]
@lervag Thanks for googling around for me. Funny thing: that Stack Exchange link is **me**. I asked there as well. In any case, I appreciate the help.

**Comment by lervag** [comment]
Haha, sorry! I should of course have noticed that! My bad!

I would think this guy Torbjørn is right in his comment, though, that you can set the `$bibtex` variable in the `.latexmkrc` file.

**Comment by telemachus** [comment]
@lervag You and he were absolutely right! It took me a little bit to work out one more detail, but he was basically right. That link now has a pretty complete answer, so I'm glad it's here anyhow. More help for future Googlers. Thanks again.

**Comment by lervag** [comment]
No problem, I'm happy it works :)
