### ISSUE TITLE
Not an editor command: VimtexCompile

### ISSUE THREAD

**Issue by wf34** [lervag/vimtex#695]
The problem is that vimtex stopped working for me totally.  

I get a message:
`E492: Not an editor command: VimtexCompile`
other commands do not work either.  
 
`:scriptnames` tells me that only `85: ~/.vim/bundle/vimtex/after/syntax/tex.vim` loaded, which I anticipate is not the whole plugin at all.  

Please let me know if I can provide any other info to complement the description.
May be it is more of a vim question than vimtex question, but I am unsure about that and decided to start here.
Thank you for your help.

**Comment by lervag** [comment]
You should create a minimal example as specified in the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md). I suspect you won't be able to reproduce this, i.e., that everything works, if you use a minimal vimrc file.

**Comment by Konfekt** [comment]
Same problem over here. @wf34, you must be using a recent Vim version. The problem occured over here with 8.198 and is still there with 8.303. 

The filetype commands are no longer loaded. The command `set filetype=tex` restores the Vimtex commands, but that's tedious to do for every tex file.

**Comment by lervag** [comment]
I'm on 8.329 on Arch Linux, and I don't have this problem.

**Comment by Konfekt** [comment]
The problem is 
```vim
if exists('b:did_ftplugin')
  finish
endif
```
Somehow it is now already set over here, and vimtex bails out. Perhaps the tex file in $VIMRC already sets it?

**Comment by Konfekt** [comment]
The file `/usr/share/vim/vim80/ftplugin/initex.vim` already sets it.

**Comment by Konfekt** [comment]
Commenting it out makes `Vimtex` work again. Perhaps your distribution comes with other runtime files.  The file `initex.vim` in `$VIMRUNTIME/ftplugin`is called by `plaintex.vim, which is called by `tex.vim`.

**Comment by Konfekt** [comment]
Perhaps these lines should only be there if `Vim` didn't come with its own tex ftplugin files. There are plugins that set `did_ftplugin` and others that don't. To me, it seems to depend on how likely it is that `Vim` already ships with its own ftplugin files. For example, CheckAttach for mail files does not.

So how about a `did_vimtex_ftplugin`?

**Comment by lervag** [comment]
No, what happens is that you have loaded vimtex wrongly. It should be loaded before the internal plugins. With `:scriptnames`, you get a list of which scripts/files are loaded, in the order that they are loaded. For me, this gives (I've removed every line that is not a `ftplugin` and has `tex` in the name):

```
/home/lervag/.vim/personal/ftplugin/tex.vim
/home/lervag/.vim/bundle/vimtex/ftplugin/tex.vim
/usr/share/vim/vim80/ftplugin/initex.vim
/usr/share/vim/vim80/ftplugin/tex.vim
```
As you see, the internal plugin is loaded _after_ vimtex (and my personal settings).

This is all handled by how you add plugins. I use `vim-plug`, which handles this automatically.

**Comment by Konfekt** [comment]
Yes, the order is wrong. Albeit, there's nothing that changed other than the Vim version. Indeed
```vim
339: ~/.config/.vim/ftplugin/tex.vim
343: /usr/share/vim/vim80/ftplugin/initex.vim
345: ~/.config/.vim/plugged/vimtex/ftplugin/tex.vim
346: /usr/share/vim/vim80/ftplugin/tex.vim
347: ~/.config/.vim/after/ftplugin/tex.vim
```
Not sure why Vim now loads it between those two. I also load `vim-plug` at the very beginning of the `~/.vim/vimrc`

**Comment by Konfekt** [comment]
Ok, it seems that Vimtex has to be loaded first by `vim-plug`. See, I now see where it comes from: There's another plugin, `vim-sandwich`, that also added a `ftplugin/tex.vim` file that overrides that by `vimtex`. So those conflict.

**Comment by Konfekt** [comment]
Vimtex stops/starts working if and only if it is loaded after/before vim-sandwich.

**Comment by lervag** [comment]
Yes, you are right. If I load `vim-sandwich` before `vimtex`, things stop working. That is very strange. It is because if this code in `vim-sandwich/ftplugin/initex/sandwich.vim`:

```vim
if !exists('b:undo_ftplugin')
  " Make sure that 'b:undo_ftplugin' exists.
  runtime ftplugin/initex.vim
endif
```

@machakann I'm wondering if notifying you like this works..? Perhaps we/I should open an issue with vim-sandwich?

**Comment by machakann** [comment]
Hi, it seems my bad, sorry! I haven't expected that kind of problem but it could be solved soon.

I will move `vim-sandwich/ftplugin/initex/sandwich.vim` to `vim-sandwich/after/ftplugin/initex/sandwich.vim`. Just a minutes.

**Comment by machakann** [comment]
Please update vim-sandwich, and could you try if both of them work well?

**Comment by lervag** [comment]
Yes, now it seems to work as expected. Thanks for handling this so fast!

**Comment by lervag** [comment]
@wf34 and @Konfekt Please verify that updating vim-sandwich resolves your issues.

**Comment by wf34** [comment]
Colleagues, for me the issue is not resolved just yet. Workaround with commenting out the `did_ftplugin` variable of ftplugin did nothing for me. I also do not know what the `vim-sandwich` is and a search shows me that I do not have a copy of that plugin on my machine.

I also had incentive to switch to the `vim-plug` (now I use Vundle), as I got from this thread that the issue has to do with the order of script loading. But that just feels like brute-forcing problem blindly.

**Comment by lervag** [comment]
@wf34 See my first comment, please! You have not provided _anything_ that resembles details that help in solving this issue for you, even though I've specifically asked you for more details. I've also linked you to an issue template that describes _how_ to provide such details, that is: how to define a minimal example.

I suspect that the problem is still related to the loading order (which may, as explained earlier, be verified through `:scriptnames`). But you have not even said how you load plugins...

**Comment by wf34** [comment]
By the way of constructing a minimal example I have found a solution to my issue. An instruction `filetype plugin off` was at some point added to vimrc and then forgotten. Thank you.

**Comment by lervag** [comment]
No problem. This is exactly why I ask people to construct minimal examples. In any case, I'm glad we have sorted this out! Don't hesitate to open more issues if you should have other problems. :)

**Comment by Ploppz** [comment]
Using `Plug`, I got this problem. Thanks to this issue I could solve it by placing the `Plug 'lervag/vimtex'
` line at the very beginning after `call plug#begin(..)`. But I find it strange that it doesn't work when it is at the end of the Plug section , and works when it is at the beginning.

**Comment by lervag** [comment]
I suspect you are using polyglot. If so, please see the first entry in `:help vimtex-troubleshooting`.

**Comment by Ploppz** [comment]
I don't use polyglot (no such thing in my init.vim anyway)

**Comment by lervag** [comment]
I'll help you debug this if you want, but if so, please open a new issue.
