### ISSUE TITLE
Smart quotes support

### ISSUE THREAD

**Issue by maxigaz** [lervag/vimtex#697]
### Explain the issue

It would be great if there was an option to automatically turn the character `"` into the typographically correct opening and closing quotation marks. Also, the user should be able to set what he/she wants to be inserted—whether it be ` `` ` as opening quote and `’’` as closing quote, for instance, or `\enquote{` and `}`, respectively (the latter requires the `csquotes` package to work properly).

### Minimal working example

```tex
\documentclass{minimal}
\usepackage{csquotes}
\begin{document}

"Hello World!" % When this line is being typed, it should automatically turn
% into what can be seen in one of the following lines, depending on the user's
% setting.

``Hello World!''
\enquote{Hello World!}

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
I understand your desire for this feature, but I won't implement it. Instead, I will advice that you look into snippet plugins such as [neosnippet](https://github.com/Shougo/neosnippet.vim) or [UltiSnips](https://github.com/SirVer/ultisnips). These both will make it easy to create a snippet that gives you almost exactly what you want.

E.g., with UltiSnips, the following would be a convenient snippet:

```
snippet " "Quotes" A
\`\`${1}''${0}
endsnippet
```

The syntax is explained in the UltiSnips docs, but I'll remark that the `A` is an autotrigger option that makes this work like this:

1. You type `"`, then UltiSnips automatically expands to ``` ``|'' ```. You continue to type the quoted text, then use the trigger jump mapping that will move the cursor out of the quotes.

**Comment by maxigaz** [comment]
I've just tried your suggestion with UltiSnips. When I type `"`, it is expanded to ` ``|''" `, so the straight quotation mark remains there.

Similarly, using

```
snippet " "Quotes" A
\\enquote\{${1}\}${0}
endsnippet
```

will result in `\enquote{|}"`

**Comment by lervag** [comment]
Strange. This works as expected for me...

**Comment by Rmano** [comment]
I use 
```
snippet " "Latex quote" i
\`\`${1:${VISUAL}}''
endsnippet
```
...and it works quite well. There is a space after the two single quotes at the end of the command. To use it, type `"` then the UltiSnips key (TAB for me), write text, and then TAB. Alternatively, you can visually select a text, press TAB, pres `"`, press TAB again and the text will be surrounded by smart quote.

**Comment by maxigaz** [comment]
The cause of the problem with the redundant `"` I described above is most likely delimitMate, which I also have installed. However, I haven't been able to figure out how to disable it only for quotation marks and only for .tex files, and I don't want to disable the whole plugin completely.

**Comment by lervag** [comment]
@maxigaz I see. Still, my point is that I don't want to implement this feature because there are already plugins that do similar things, but better than I could do it. Also, such plugins (e.g. UltiSnips), will give you a more general feature that is very useful also for other filetypes and activities.

I won't be able to help you with configuring delimitMate and UltiSnips so they work together. If it is not straightforward, than I would suggest you open an issue where it seems most valid.

**Comment by lervag** [comment]
Thanks, @Rmano, I'll use that myself.

**Comment by maxigaz** [comment]
@lervag That's OK, it makes sense. Eventually, I could disable the automatic insertion of quotation marks *everywhere* in delimitMate. For now, it's better than nothing, and I appreciate your suggestion of using UltiSnips for this purpose.

@Rmano Thank you, I modified it as

```
snippet " "Quotes" A
\\enquote\{${1:${VISUAL}}\}${0}
endsnippet
```
and it works great.
