### ISSUE TITLE
Zathura view method cannot find PDF if `$out_dir` is given in .latexmkrc

### ISSUE THREAD

**Issue by j-jith** [lervag/vimtex#700]
When I don't want LaTeX polluting my source directory with its build files, I use a simple .latexmkrc which looks like this:
```
$out_dir = 'build';
```
If I use `g:vimtex_view_method='zathura'` now and try the command `:VimtexView`, I get this error - `vimtex warning: viewer can not read PDF file!`. It turns out that the `b:vimtex.out(1)` and `b:vimtex.viewer.synctex` do not match with the pdf and synctex files generated by latexmk due to vimtex being unaware  of `$out_dir`.

I have verified that if I specify `let g:vimtex_latexmk_build_dir=<build dir>` in my .vimrc, everything works as expected.

### Minimal working example

```tex
\documentclass{minimal}
\usepackage{lipsum}
\begin{document}
\lipsum
\end{document}
```

### vimrc

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_view_method = 'zathura'
```

### latexmkrc

```
$out_dir = 'build';
```

**Comment by j-jith** [comment]
I have just tried this with qpdfview. It shows the same error as zathura. The vimrc used was

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_view_general_viewer = 'qpdfview'
let g:vimtex_view_general_options = '--unique @pdf\#src:@tex:@line:@col'
let g:vimtex_view_general_options_latexmk = '--unique'
```

I have created a new pull request regarding this.

**Comment by lervag** [comment]
Interesting. First, I've never thought about parsing the `.latexmkrc` file for options. It seems like a good idea, at least for this particular case.

I'll continue the discussion in #701.
