### ISSUE TITLE
latexmk "zombie" process

### ISSUE THREAD

**Issue by edgarcosta** [lervag/vimtex#704]
On my desktop, I have noticed that sometimes after I close all my tex files, there is still a latexmk process running in the background.
Sometimes even happens that I have multiple latexmk processes running on the same project...
This doesn't happen all the time, and I have not yet managed to reproduce it on demand.

I have the exactly the same setup on my laptop,  .latexmkrc, .vimrc, plugins and etc, and I have not yet encountered the same behavior.

Is there a log (or some way to produce one) where I could look into to try to figure out what's happening?

Thanks for your help.

These are my vimtex options:

```vim
let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-g -r @line @pdf @tex'
```

and my .latexmkrc:

```perl
$pdflatex = q/xelatex -synctex=1 %O %S/
```

**Comment by lervag** [comment]
I think this could happen if Vim crashes, but if you close Vim in a normal way, it should not happen. However, obviously, there might be bugs...

Unfortunately, it is very difficult to debug or solve such issues without being able to reproduce them.

What is the difference between your desktop and laptop? Are both OSX?

Also, please provide more details. Which OS (version), which version of Vim?

There is no log file, no. :\

**Comment by pdf** [comment]
@edgarcosta please use code blocks to avoid paging users prefixed by `@`, and to preserve formatting:

```
This is a code block
```

**Comment by edgarcosta** [comment]
Thanks for the quick reply.

I will keep trying to recreate the bug.


Both computers are running OSX 10.11.6, same versions of latexmk and mvim.
```
$ latexmk --version
Latexmk, John Collins, 22 April 2016. Version 4.45
```
I use MacVim, so most of the times the app is running, but no windows are open
```
$ mvim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Feb 16 2017 04:51:36)
MacOS X (unix) version
Included patches: 1-329
```

**Comment by lervag** [comment]
Ok. I have to admit that I really can't help you unless you are able to give more clues into what might be wrong. Famous last words: "The code should be right". Obviously, something isn't right, but I don't know what.

Note that I have also experienced the same thing a couple of times (but very rarely). In my case, this has occured if Vim has crashed, in which case the clean up code is not executed. I don't think there is anything I can do about that, though.

If you are able to reproduce the issue, then we have something to work with. Else I think we must consider this issue unsolvable for now.

**Comment by edgarcosta** [comment]
Yup, let just mark it unsolvable.
Most likely has nothing to do with vimtex.

It has been driving me crazy for while, and today I decided that would be the day that I would ask for help.

**Comment by lervag** [comment]
I'm sorry that I can't be of more help. If you should get any more clues as to what is happening, don't hesitate to let me know. I would be happy if it turns out that it is a bug in vimtex that we may squash.
