### ISSUE TITLE
bibtex completion does not work for entries added to bibtex file

### ISSUE THREAD

**Issue by sdx23** [lervag/vimtex#705]
I work with a bib-file generated as export from Zotero, overwriting the the old one (inode is not changed).

In a ```\cite{}``` environment, no completion suggestions are shown for entries that were newly added to the bib-file.

Observations:
- After exiting and restarting vim, completion works as expected.
- Issueing ```:vimtexreload``` does not fix the issue.
- latexmk notices the change in the bib-file and recompiles

**Comment by lervag** [comment]
How can I reproduce? Please provide a full (minimal) example, as explained in the issue template.

**Comment by sdx23** [comment]
Contents of `main.tex`
```\documentclass[]{article}
\begin{document}

Foo.\cite{

\bibliography{bibfile}
\bibliographystyle{plainnat}
\end{document}
```

Contents of `bibfile.bib`
```@article{foo_2017,
	title = {Foo},
	journal = {Journal},
	author = {fooauthor},
	year = {2017},
}
```

Contents of `bibfile.bib2`
```@article{foo_2017,
	title = {Foo},
	journal = {Journal},
	author = {fooauthor},
	year = {2017},
}

@article{bar_2017,
	title = {Bar},
	journal = {Journal},
	author = {barauthor},
	year = {2017},
}
```

`vim main.tex`, get to `\cite{`, insert `f` shows completion, insert `b` nothing. Ok.

Now `cat bibfile.bib2 > bibfile.bib`, insert `f` shows completion, insert `b` nothing, but should show completion. Exit vim and enter it again. Insert `b` - shows completion.

**Comment by lervag** [comment]
Are you using neocomplete, youcompleteme or similar? I think that's the issue. Because omnicompletion works in your example exactly as expected:

0. Use a minimal vimrc file (see below)
1. `vim -Nu minivimrc main.tex`
2. Go to `\cite{`, insert `f` and then `<c-x><c-o>` (CTRL-X then CTRL-O)
3. Verify that no completion for `b`
4. Now do the `cat ...`
5. Now verify that completion works for both `f` and `b`

The minivimrc file I used is this:

```vim
" Be sure to use the correct path to vimtex here
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
```

**Comment by sdx23** [comment]
You're right, I'm using neocomplete. Calling the completion explicitly shows up the new entries. Thank you.

**Comment by lervag** [comment]
No problem. I think the problem is that neocomplete caches the completion candidates. I don't remember/know exactly how to deal with that, but you could try opening an issue on the neocomplete repo if you can't figure it out.
