### ISSUE TITLE
Enhancement discussion: per-directory setup.

### ISSUE THREAD

**Issue by Rmano** [lervag/vimtex#710]
Several program, for example `latexmkrc`, can have a directory-local init file that is read instead or (better) after a global one. 

It would be nice to be able to do a similar thing for editing LaTeX files, given that the type of a project that reside in a directory could be different from another one. I can think of things like default spell language, or indentation style (tab/space), or for example automatic search of main file or not (see #706). 

Although I think that such a thing could be useful in general for `vim` (and so not limited to `vimtex`), also a vimtex-only version could be quite useful. 

One possibility (flexible, but maybe risky) would be to execute a `vimtexrc` file is  there is one in the same directory of the file opened there; another possibility is to have a simple format of the kind 
```
variable = value
...
```
that will be limited to assign values to a series of configuration variables and that can be sanitized. 

In the general case, it seems that a plugin exists (http://www.vim.org/scripts/script.php?script_id=3393), but I think it's a bit different --- I am not sure it search the init file in the current directory, or in the directory where the file resides.

**Comment by lervag** [comment]
Perhaps [this](https://github.com/embear/vim-localvimrc) plugin is better?

**Comment by lervag** [comment]
Or, this option might be all that's needed:

```
					*'exrc'* *'ex'* *'noexrc'* *'noex'*
'exrc' 'ex'		boolean (default off)
			global
			{not in Vi}
	Enables the reading of .vimrc, .exrc and .gvimrc in the current
	directory.

	Setting this option is a potential security leak.  E.g., consider
	unpacking a package or fetching files from github, a .vimrc in there
	might be a trojan horse.  BETTER NOT SET THIS OPTION!
	Instead, define an autocommand in your .vimrc to set options for a
	matching directory.

	If you do switch this option on you should also consider setting the
	'secure' option (see |initialization|).
	Also see |.vimrc| and |gui-init|.
	This option cannot be set from a |modeline| or in the |sandbox|, for
	security reasons.
```

However, it is not recommended.

**Comment by lervag** [comment]
@Rmano What do you think about [vim-localvimrc](https://github.com/embear/vim-localvimrc)? To me it seems to do what you suggest, but in a general way that also benefits other filetypes. I'm therefore hesitant to implement a custom solution for vimtex.

**Comment by lervag** [comment]
To me it also seems like [localrc.vim](http://www.vim.org/scripts/script.php?script_id=3393) actually does what you want. I allows to load a local vimrc file. It will load the file in the current directory, if it exists, or the one in the directory above, and so on.

**Comment by Rmano** [comment]
Yes, it seems that it covers all the things I was proposing; so yes, I agree with you, no need to duplicate functions. 

I will close this issue now. Thanks!

**Comment by lervag** [comment]
No problem! I found it useful to investigate this, and I might even use this myself for future projects. :)
