### ISSUE TITLE
Add support for entering new \item

### ISSUE THREAD

**Issue by ngphuoc** [lervag/vimtex#712]
Could you please add support for automatically adding `\item` in the newline after pressing `Enter` at the end of the previous line? Below is an example:

```latex
\documentclass{minimal}
\begin{document}
\begin{itemize}
  \item Apple[Enter]
  \item [cursor here]
\end{itemize}
\end{document}
```

**Comment by lervag** [comment]
Hi! Actually, I don't want this. Instead, I propose that you add the following:

```vim
call vimtex#imaps#add_map({
  \ 'lhs' : '<m-i>',
  \ 'rhs' : '\item ',
  \ 'leader' : '',
  \ 'wrapper' : 'vimtex#imaps#wrap_environment',
  \ 'context' : ["itemize", "enumerate"],
  \})
```

This will map `ALT+i` to add `\item` in insert mode. You could add the above to your vimrc file, or to a personal `ftplugin` or `after/ftplugin`.

**Comment by lervag** [comment]
Just to clarify: I don't want to remap the `enter` key for several reasons. First, the feature you ask for is not something everyone, or probably even most people, want. In particular, it is not obvious that you do not want to just start a new line for the same `\item`. Second, remapping `enter` is very prone to conflict with other plugins that might also remap `enter`. Thus I think it is more appropriate to add a mapping for easily adding the `\item` such as what I proposed above.

**Comment by Rmano** [comment]
I was trying to add it to my `.vimrc` to try to modify it to remap "alt-enter" (to insert an enter and then an `\item` but I have a problem... 
```[romano:~/tmp] % gvim prova.tex   
Error detected while processing /home/romano/.vimrc:
line   44:
E117: Unknown function: vimtex#imaps#add_map
```

**Comment by lervag** [comment]
You have to add it _after_ the runtime paths have been updated. E.g., if you are using `vim-plug`, you have to add it after the `call plug#end()`.

**Comment by Rmano** [comment]
Ah, ok! 
It works really nicely like this: 
```call vimtex#imaps#add_map({
    \ 'lhs' : '<S-CR>',
    \ 'rhs' : '^M\item ',
    \ 'leader' : '',
    \ 'wrapper' : 'vimtex#imaps#wrap_environment',
    \ 'context' : ["itemize", "enumerate"],
    \})
```
...where the `^M` over there is really input with a `CTRL-V` `ENTER` sequence. Now with Shift-CR, at least in `gvim`, you have a return and a new `\item`. It will not work in terminals, though, where `shift-cr` is normally the same as `cr`.

**Comment by lervag** [comment]
Thanks for the suggestion! It seems closer to what @ngphuoc wanted than my own suggestion.

**Comment by ngphuoc** [comment]
Thanks a lot for the nice mapping. I tried it but it print out literally `^Mitem` at the cursor instead of `\item` in a new line. Am I missing something?

**Comment by ngphuoc** [comment]
I also tried @lervag's mapping. It works nice.

**Comment by Rmano** [comment]
You have to enter that string like: ` '` then press CTRL-V and the "Enter" key (or CR, whatever is called in you keyboard) and the the following chars; it should look like this (your color combination may vary): 

![selection_029](https://cloud.githubusercontent.com/assets/6414907/23836392/8f8ff204-0777-11e7-9a13-262c935882b4.png)

**Comment by ngphuoc** [comment]
It's clever, works great! Many thanks.
