### ISSUE TITLE
[Feature Request] Is there any plan for the ``magic comments''

### ISSUE THREAD

**Issue by haoyun** [lervag/vimtex#713]
There are some commonly used directives, like:
```
%!TeX encoding= UTF-8
%!TeX root=main.tex
%!TeX program=XeLaTeX
```
Of course this could be achieved using a separated `latexmkrc` file.
But I think it may be more convenient if directives could be used.

Some widely used editors understand these magic comments (http://tex.stackexchange.com/a/84687/9848):
```
            E P R S
TeXShop     x x x x
TeXStudio   x x x x
TextMate    ? x x ?
TeXworks    x x x x
SublimeText o x x x
Atom        o x x o
            | | | |
x = yes     | | | Spellcheck
o = no      | | Root
? = ?       | Program
            Encoding
```

**Comment by lervag** [comment]
There is no plan, no. That is, `TeX root` is already implemented. The rest are not supported at the moment. However, we could have the discussion and if I agree it is useful I might agree to implement. There are some questions, though:

1. We could also just use local vimrc configurations as discussed in #710. Why is this not as good of a solution as using the directives?

2. Why is it not better to instead use a (local) `.latexmkrc` file to specify the compilation program? If you use vimtex, then you already use `latexmk`. And then it makes more sense, at least to me, to set the compiler option in a local `.latexmkrc` file.

3. What would the `encoding` option do? I am not sure what I should do when reading it. To me, it seems Vim already reads the files correctly no matter which encoding we use. And if you use UTF-8, then it should suffice to use `\usepackage[utf8]{inputenc}`?

It seems to me, overall, as if the various directives might need separate discussions. I think the main argument for these directives is collaborative editing.

**Comment by Rmano** [comment]
For the spellcheck, you just use 
```
% vim: set spelllang=en :
```
near the top or bottom of the file. Be careful with the _three_ `l`s... ;-)

**Comment by andymass** [comment]
Personally,  I would have some use for the `program=` directive for testing one-off XeLaTeX documents.  The detection itself could easily be done in a personal .vimrc ([see this example gist](https://gist.github.com/andymass/ea7e381d51387e205f44c0c43aca7225)).  However, vimtex does not really have simple support for programs besides `g:vimtex_latexmk_options.='-pdflatex=xxx'`.  Each time the file is reloaded, my script naively appends an additional `-pdflatex=`.  I considered checking for the existence of one and replacing, but this approach seems very brittle.

**Comment by haoyun** [comment]
Actually to me, the most useful one is `%!TeX program=XeLaTeX`. A `latexmk.rc` in the working directory does the job. BUT:
I write lots of notes everyday, each on a different topic and most of them are short (not a big project). Some of these notes do require  `xelatex` rather than `pdflatex`. I don't think it's easier to manage all these notes in one file nor each in a different folder. So there are multiple `.tex` files in one folder. It will be much more convenient to put just one line in the particular tex file to declare the tex engine. rather than to manage lots of local `vimrc` or `latexrc` files..

**Comment by Rmano** [comment]
Hmmm... I don't see why in such a mixed environment you can't simply use `xelatex` for all of your files. At least for consistency in fonts treatment or whatever.... 
Anyway, a simple script like (notice: it has to be made smarter, but well, you gt the idea) should work...
```
#!/bin/bash 
#
program=pdflatex
head -5 "$1" | grep "XeLaTeX" && program=xelatex
$program "$1"
```
...and now stick a `% XeLaTeX` comment in the first five lines of the file you want to compile with `xelatex`. 

**Disclaimer**: the script is way too naïve to work; it should at list parse the argument to discard the options and apply the "grep" to the file name, but well... you got the idea.

**Comment by haoyun** [comment]
@Rmano , Thank you!
Yes, yes there are lots of workarounds.
But don't you think just one line `%!TeX program=XeLaTeX` is a very convenient way to control the engine?
The reason that I do not want to use xelatex for all files is that xelatex is much slower on Windows than it on OSX or Linux.

**Comment by lervag** [comment]
I'm sold. I'm adding support for the `TeX program` line. I hope you don't mind if you borrow your code, @andymass.

**Comment by andymass** [comment]
@lervag of course! (I must say I didn't test it much).  Thanks for this very speedy update.  Unfortunately, I made a [transposition](https://gist.github.com/andymass/ea7e381d51387e205f44c0c43aca7225/revisions#diff-3803676b3882b0e96a117a76b9d0526e) in the list.  `--xtx` should be on the xetex line, not the pdftex line:

        \ 'context (xetex)'   : '-pdflatex=''texexec --xtx''',
        \ 'context (luatex)'  : '-pdflatex=context',
        \ 'context (pdftex)'  : '-pdflatex=texexec',

**Comment by lervag** [comment]
Thanks, @andymass. I've updated accordingly. I also added some documentation. Please let me know what you think (see 2f1b86c).

**Comment by clason** [comment]
Sorry to bump an old issue. I just noticed that the `TeX program` command does not work if `g:vimtex_latexmk_progname` is set (specifically, to `nvr` as suggested in the documentation). This is not a big deal for me, so I thought I'd ask if I should open a new issue or if I'm missing something obvious here.

**Comment by lervag** [comment]
That's strange. I don't really see how those two should conflict. It would be good if you could provide a minimal example and open a new issue.

**Comment by clason** [comment]
Never mind, I found out what's happening. The `TeX program` directive is read when loading the file, not when starting compilation. So when I added the `TeX program = lualatex` line and started `<local-leader>ll`, and it was still using pdflatex, I closed gvim, checked my vimrcs, commented out the prime suspect, and restarted. And lo and behold, it worked, and I posted...

Is this (directive read on load, not compilation) intended behavior?

**Comment by lervag** [comment]
Hmm. Good question. It was the simplest thing to do. Would you really make use of changing this during a single editing session?

**Comment by clason** [comment]
Not twice, but putting in that line after having started writing is something I'd expect to do. 

(I'm using lualatex for letters where corporate identity dictates fonts not packaged for LaTeX, so those are frequent one-off files, not a big project like a book.)

In any case, it's no big deal, but it certainly something I didn't expect and might merit mention in the documentation.

**Comment by lervag** [comment]
I decided to update the docs with a hint to the `VimtexReload` command (mapped to `\lx` by default). This should work and provde the desired behaviour, I think.

**Comment by clason** [comment]
Yep, that's perfectly fine for me -- especially with `VimtexReload`, which I was not aware of, thanks for pointing it out!

**Comment by lervag** [comment]
No problem. `VimtexReload` is one of my "secret weapons" when developing. Very useful!

**Comment by jdhao** [comment]
I was also bitten by this issue. You have to use `VimtexReload` to make certain changes take effect.

**Comment by lervag** [comment]
Thanks, @krishnakumarg1984; I've updated the docs. `TEX TS-program` is (and was already) supported - this is more clear from the updated docs. Let me know what you think.

**Comment by krishnakumarg1984** [comment]
@lervag Thank you. The updated docs are very clear now. 

I note that you've updated the regexes, and was wondering if they need updated tests to go with it (just in case a regression is introduced which breaks stuff for existing docs)?

**Comment by lervag** [comment]
> @lervag Thank you. The updated docs are very clear now.

Good to hear, and thanks for motivating the changes.

> I note that you've updated the regexes, and was wondering if they need updated tests to go with it (just in case a regression is introduced which breaks stuff for existing docs)?

Yes, there were minor changes but they should not really change anything; only simplifying the regex.

Tests are usually preferred, and I try to add them as I go. It takes time, though, so sometimes I skip them (when I'm quite sure there are no problems).

**Comment by krishnakumarg1984** [comment]
Since this issue is mentioned in vimtex's documentation, just checking if those regex tests are still a relevant thing?
