### ISSUE TITLE
Special treatment of `\\[` for indentation (and autocomplete)

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#715]
First, thank you very much for the simplified indentation!

I noticed one regression: currently, `\\[` is treated as opening a display math environment (from the last two characters, leading to wrong indentation of multiline equations with custom spacing:

```
\begin{align}
    2+2 = 4\\[1ex]
        3+3 = 6
    \end{align}
```

(Similarly, calling `<plug>(vimtex-delim-close)` after the third line inserts `\]` instead of `\end{align}`.)

Maybe there should  also be a `\\\[` in `s:delims.delim_tex` `re:`?

**Comment by lervag** [comment]
Thanks! In general, I should probably add the `\\\@<!` construct to most of the regexes. I only added it to `\\\[` now, because it seems to be the one where it is most likely to fail. I'll reconsider if I see examples where it is likely that any of the other regexes might fail for the same reason.
