### ISSUE TITLE
Error detected while processing function vimtex#toggle_main:

### ISSUE THREAD

**Issue by AlekseiSmirnov** [lervag/vimtex#716]
Recently I updated all my Vim plugins through vundle using `PluginUpdate` command.
I'm not sure that it's an exact reason but since then, I get an error when try to toggle main (:VimtexToggleMain) file in multifile project:
```
Error detected while processing function vimtex#toggle_main:
line    8:
vimtex: Changed to `subfile.tex' [local]
```
It's reproduced on both: MacVim and command line vim.
Despite the error, it seems that function works as expected and indeed toggle the file.

The problem can be reproduced using simple multi-file project:
main.tex
```
\documentclass{minimal}
\usepackage{subfiles}

\begin{document}

Hello World!
\subfile{subfile}

\end{document}
```

subfile.tex
```
\documentclass[main.tex]{subfiles}

\begin{document}

This is subfile

\end{document}
```
Steps to reproduce:
1) Launch vim: `vim -u ~/.vimrc2 --servername a subfile.tex`
2) press `\ls`

### Minimal vimrc file
 .vimrc2 file:
```vim
set nocompatible

"Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable
"
" Vimtex options go here
```

**Comment by lervag** [comment]
Sorry about that, it was a minor regression bug. Fixed now. Thanks for reporting!

**Comment by AlekseiSmirnov** [comment]
Thanks for a quick response

**Comment by lervag** [comment]
No problem :)
