### ISSUE TITLE
Regression in `tse` and `tsd`

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#717]
I feel bad about this, but the new <strike>indentation</strike> delimiter API seems to have broken the `tse` and `tsd` implementation. Consider the following simple example:

```
\documentclass{article}
\begin{document}
\begin{equation}
    (x_{1})
\end{equation}
\end{document}
```

With the cursor inside the parenthesis, pressing `tse` results in the following wall of errors:

```
Error detected while processing function vimtex#env#toggle_star[1]..vimtex#delim
#get_surrounding[6]..vimtex#delim#get_prev[1]..<SNR>61_get_delim:
line   38:
E716: Key not present in Dictionary: env
E15: Invalid expression: g:vimtex#delim#re[a:opts.type][a:opts.side]
line   40:
E121: Undefined variable: l:re
E116: Invalid arguments for function searchpos(l:re, 'bcnW', max([line('.') - s:
stopline, 1]))   : searchpos(l:re, 'bcnW', line('.'))
E15: Invalid expression: a:opts.direction ==# 'next' ? searchpos(l:re, 'cnW', li
ne('.') + s:stopline) : a:opts.direction ==# 'prev'   ? searchpos(l:re, 'bcnW',
max([line('.') - s:stopline, 1]))   : searchpos(l:re, 'bcnW', line('.'))
line   45:
E121: Undefined variable: l:lnum
E15: Invalid expression: l:lnum == 0 | break | endif
line   54:
E171: Missing :endif:   endwhile
```
after which it repeats for as long as I cared to check. (Needless to say, the `equation` environment is not changed to `equation*`.)

Pressing `tsd` does nothing (but freezes on more complicated documents).

(Probably related to #718.)

**Comment by lervag** [comment]
Sorry, I think this has been fixed now. Probably a regression bug after some refactoring I recently did.

**Comment by clason** [comment]
Yep, that fixes it. Thanks for the quick fix!

**Comment by lervag** [comment]
No problem!
