### ISSUE TITLE
Lag introduced in f514528656e57f09a50390aefcb21beab4f41dgi87

### ISSUE THREAD

**Issue by rafaeln** [lervag/vimtex#718]
I get terrible lags using the minimal .vimrc file below, on neovim (compiled from head) or vim (compiled from head), and any commit of vimtex from f514528656e57f09a50390aefcb21beab4f41dgi87 onwards (2e4c93479a82fe0f26bd8c063d91c4ef09723ddd is the latest version that works for me without lags).

The file in which I found out about the lag is pretty big. [Here](https://www.dropbox.com/s/adowgckh181vrzr/mychapter.tex?dl=0) is a link to it. Go to the beginning of line 192 and move around with `w`. You'll notice the lag when you are close to the left parens.

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
I think this was fixed when I fixed #717.

**Comment by rafaeln** [comment]
Thanks! I tested the fix and it works for me now.

**Comment by lervag** [comment]
Great :)
