### ISSUE TITLE
documentation inconsistencies

### ISSUE THREAD

**Issue by nicodebo** [lervag/vimtex#719]
### Explain the issue

In order to remove conflicts between my particular keyboard layout and vimtex I have disable the plugin mappings (`g:vimtex_mappings_enabled=0`) and I am trying to remap all of them.
By comparing the `Default mapping` section of the documentation and the `vimtex.vim` autoload file It seems like:
* normal mode is mentioned for the text object mappings in the documentation (line 369-376 of /doc/vimtex.text) while they are not mapped in normal mode in the autoload file (line 412-429 of /autoload/vimtex.vim) (i.e `nxo` instead of `xo`)
* `<plug>(vimtex-env-change-math)` is missing from the documentation mapping list.
* `<plug>(vimtex-delim-toggle-modifier)` is `nx` in the documentation while it is `nv` in the autoload function.

I hope I am being clear, otherwise I can provide more details.

**Comment by lervag** [comment]
Thanks! I'll add the missing one later.

**Comment by lervag** [comment]
I think that should fix it. What do you think?

**Comment by nicodebo** [comment]
I double checked all the mappings and now it's correct. Thank you.

**Comment by lervag** [comment]
Great! And thank you for checking/noticing and reporting!
