### ISSUE TITLE
Undefined variable: g:vimtex#delim#re on opening markdown file

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#720]
Commit c0bfc yesterday introduced the following error message when opening a markdown document for the first time if the plugin https://github.com/vim-pandoc/vim-pandoc is installed:

```vim
E121: Undefined variable: g:vimtex#delim#re
E116: Invalid arguments for function join([ g:vimtex#delim#re.delim_mod_math.ope
n, '{', '\\\@<!\\\[',], '\|')
E15: Invalid expression: join([ g:vimtex#delim#re.delim_mod_math.open, '{', '\\\
@<!\\\[',], '\|')
line  130:
E121: Undefined variable: g:vimtex#delim#re
E116: Invalid arguments for function join([ g:vimtex#delim#re.delim_mod_math.clo
se, '}', '\\\]',], '\|')
E15: Invalid expression: join([ g:vimtex#delim#re.delim_mod_math.close, '}', '\\
\]',], '\|')
```

Perhaps someone has any idea why it only appears in markdown files?

**Comment by lervag** [comment]
I have an idea what is happening, but I can't reproduce it. Could you provide a minimal example?

**Comment by lervag** [comment]
Ok, I think it should work now. I refactored some initialization code and made it more in line with how autoloaded files should work (I think).

Crossing fingers that my refactoring has not introduced more bugs. :p

**Comment by Konfekt** [comment]
Thank you @lervag ! The error is gone.

**Comment by lervag** [comment]
Thank you! You triggered a pretty heavy refactoring of the code. I realized I was "doing it wrong" with regard to initialization of the plugin. I simplified most of the autoload modules as a response to this issue. In particular, I had defined functions that were called to initialize each script. Silly me: scripts should initialize when loaded. Anyhows.... thanks :)
