### ISSUE TITLE
dot-repeat does not work for ds$

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#722]
Consider this MWE:

```tex
$a+b$
$a+b$

\textbf{hello}
\textbf{hello}
```
`dsc` command can be repeated with `.` but `ds$` cannot.

It looks like https://github.com/lervag/vimtex/blob/master/autoload/vimtex/env.vim#L68-L73 misses something like `silent! call repeat#set("\<plug>(vimtex-env-delete-math)", v:count)`

**Comment by kiryph** [comment]
Thanks. It works now for both ds$ and dse.

**Comment by lervag** [comment]
Yes, I noticed this also didn't work for `dse`. Good catch, thanks for reporting.
