### ISSUE TITLE
Recent refactoring breaks vim-surround

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#723]
Here's another regression, unfortunately: After the last round of updates, the `vim-surround` plugin no longer works. 

1. Entering `dsb` (delete surrounding curved braces), the cursor jumps to the right of the first `\` to the left (and nothing gets deleted). Similarly for `dsB` etc.
2. Entering `csb` (change surrounding curved braces), the cursor jumps to the right of the first space to the left (and the command terminates before accepting the replacement, e.g., `B`). Similarly for `csB` etc.

(`dib` and `dab` still work.)

Possibly you immediately see the problem; otherwise I'll try to bisect and create an MWE.

**Comment by clason** [comment]
D'oh! I seem to have disabled `vim-surround` in myself at some point. If it is in fact enabled, it still works as expected. Sorry for the noise!

**Comment by lervag** [comment]
Nothing is better than to see a newly created and also closed issue :)

**Comment by clason** [comment]
Except seeing no issue at all :)

**Comment by lervag** [comment]
Haha, true dat.
