### ISSUE TITLE
mvim-issue

### ISSUE THREAD

**Issue by Kensuke-Hinata** [lervag/vimtex#725]
### Explain the issue

When I create a new tex file within MacVim, the plugin won't work unless I reopen this file, but everything will be OK when I use Vim in terminal.

**Comment by lervag** [comment]
I don't use `mvim`, and so I have no idea what is happening. Could you please follow the issue template? That is, specify a full minimal example consisting of a minimal vimrc file and the exact steps to reproduce your issue.
