### ISSUE TITLE
[feature] Add support for switching input language

### ISSUE THREAD

**Issue by lervag** [lervag/vimtex#726]
In #670 we implemented a custom function combined with some autocommands to change the input language when entering/exiting math mode. It was not implemented as part of vimtex, instead it was suggested that one add the code to ones vimrc file. However, the feature could be relevant to add as part of vimtex if we found a robust and good implementation.

@petRUShka proposes to use [vim-xkbswitch](/lyokha/vim-xkbswitch) with [custom switching rules](https://github.com/lyokha/vim-xkbswitch#custom-keyboard-layout-switching-rules) as a mechanism for adding the input language switch.

It is unlikely that I will prioritize this issue in near future unless someone either provides some concrete examples that help me understand how to add the feature, or better, submit a pull request.

**Comment by nvasilas** [comment]
Hello i did write a function which may help you. It is based on xkb-switch and vim-xkbswitch, so they must be installed and configured and then you need a custom function for the layout rules. The relevant section of my vimrc is the following.
```
autocmd BufNewFile,BufRead *.tex EnableXkbSwitch
let g:XkbSwitchPostIEnterAuto = [[{'ft': 'tex', 'cmd': 'call Set_lang()'}, 0]]

function! Set_lang()
	if exists('g:set_us')
		call libcall(g:XkbSwitchLib, 'Xkb_Switch_setXkbLayout', 'us')
		unlet g:set_us
	endif
	if exists('g:set_gr')
		call libcall(g:XkbSwitchLib, 'Xkb_Switch_setXkbLayout', 'gr')
		unlet g:set_gr
		return 0
	endif
	if !exists('s:was_in_math')
		let s:was_in_math = 0
	endif
	if s:was_in_math
		call libcall(g:XkbSwitchLib, 'Xkb_Switch_setXkbLayout', 'gr')
	endif
	if vimtex#util#in_mathzone()
		call libcall(g:XkbSwitchLib, 'Xkb_Switch_setXkbLayout', 'us')
		let s:was_in_math = 1
		return 1
	else
		let s:was_in_math = 0
		return 0
	endif
endfunction
```
Also i have these mappings which i found quite useful
```
inoremap <buffer><Leader>( <C-O>:let g:set_us=1<CR>\(<C-f>
inoremap <buffer><Leader>) <C-O>:let g:set_gr=1<CR>\)<C-f>
inoremap <buffer><Leader>[ <C-O>:let g:set_us=1<CR>\[<C-f>
inoremap <buffer><Leader>ε <C-O>:let g:set_us=1<CR>\e<C-f>
inoremap <buffer><Leader>ρ <C-O>:let g:set_us=1<CR>\r<C-f>
inoremap <buffer><Leader>β <C-O>:let g:set_us=1<CR>\b<C-f>
```
I hope this may help you.

**Comment by lervag** [comment]
Thanks, @nvasilas.

However, after more thought, I've decided I will close this issue as "won't fix". The reason is that I think this feature works better as a separate plugin. It does not seem like a feature that needs to be part of vimtex.

Of course, as before, if someone convinces me otherwise and/or suggests a good implementation that fits with vimtex, then I might reconsider.
