### ISSUE TITLE
Add `csd` and `dsd`

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#727]
One cannot change or delete a surrounding delimiter without an additional plugin.

Example `$ \left( E = (mc^2) \right) $`

Would you consider adding `csd` and `dsd` to your plugin as well since `ds$, dse, dsc, cse, csc` already exist?

Using sandwich.vim with following configuration
```viml
" enable surround.vim style mappings
runtime macros/sandwich/keymap/surround.vim
"nmap ds <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
"nmap dss <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
"nmap cs <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
"nmap css <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
" and modify a tex rule to use the letter `d`
let b:sandwich_recipes[26].input = ['ma', 'd']
```
gives you already the mappings `csd` and `dsd`. However, the rules might be different between both plugins.

**Comment by lervag** [comment]
Yes, you are right. I'll add these.

**Comment by lervag** [comment]
I've added first version of `csd`. Have to go to bed now, but I'll add `dsd` when I have the time. It requires some more work, because as of now, `csd` doesn't care about surrounding modifiers, only the actual delimiters. But `dsd` should also remove modifiers if they are present.

**Comment by lervag** [comment]
Was easier than expected. Now it remains to add documentation.

**Comment by lervag** [comment]
I guess that wasn't so hard.
