### ISSUE TITLE
Text after '--' is incorrectly highlighted as a comment

### ISSUE THREAD

**Issue by Coacher** [lervag/vimtex#728]
Hello.

### Explain the issue

Some change during the last couple of days broke syntax highlighting.
Now everything after '--' is highlighted as comment, which is bad.

Example file:
```
\begin{document}

\begin{center}
    \textbf{\Large{Wrong highlight after this--Oh no! I am no comment.}}
\end{center}

Regular text---Here's another false comment.

But-this whole string is highlighted as a regular text

\end{document}
```

Just open it, no extra steps required.

### Minimal vimrc file

No special vimrc required. Here's vimtex config:

```
" vimtex
let g:vimtex_imaps_enabled = 0
let g:vimtex_view_enabled = 0
let g:vimtex_view_automatic = 0
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_indent_ignored_envs = ['document', 'proof']
```

vim --version:
```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 20 2017 01:43:54)
Included patches: 1-494
Modified by Gentoo-9999
Compiled by coacher@Photon
Huge version without GUI.  Features included (+) or not (-):
+acl             +file_in_path    +mouse_sgr       +tag_old_static
+arabic          +find_in_path    -mouse_sysmouse  -tag_any_white
+autocmd         +float           +mouse_urxvt     -tcl
-balloon_eval    +folding         +mouse_xterm     +termguicolors
-browse          -footer          +multi_byte      +terminfo
++builtin_terms  +fork()          +multi_lang      +termresponse
+byte_offset     +gettext         -mzscheme        +textobjects
+channel         -hangul_input    -netbeans_intg   +timers
+cindent         +iconv           +num64           +title
+clientserver    +insert_expand   +packages        -toolbar
+clipboard       +job             +path_extra      +user_commands
+cmdline_compl   +jumplist        -perl            +vertsplit
+cmdline_hist    +keymap          +persistent_undo +virtualedit
+cmdline_info    +lambda          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       +python/dyn      +vreplace
-cscope          +lispindent      +python3/dyn     +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      +lua             +rightleft       +writebackup
+diff            +menu            -ruby            +X11
+digraphs        +mksession       +scrollbind      +xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xpm
+emacs_tags      -mouseshape      +startuptime     +xsmp_interact
+eval            +mouse_dec       +statusline      +xterm_clipboard
+ex_extra        -mouse_gpm       -sun_workshop    -xterm_save
+extra_search    -mouse_jsbterm   +syntax
+farsi           +mouse_netterm   +tag_binary
   system vimrc file: "/etc/vim/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: x86_64-pc-linux-gnu-gcc -c -I. -Iproto -DHAVE_CONFIG_H     -O2 -march=native -mfpmath=sse -fomit-frame-pointer -pipe -frecord-gcc-switches -Wimplicit-function-declaration -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: x86_64-pc-linux-gnu-gcc   -Wl,--hash-style=gnu -Wl,-O1 -L/usr/local/lib -Wl,--as-needed -o vim    -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -lncurses -lnsl    -lacl -lattr -ldl  -L/usr/lib -lluajit-5.1
```

vimtex is @ fa02403.

**Comment by Coacher** [comment]
Going back to vimtex @ 3ea152e7f7 fixes the problem.

**Comment by lervag** [comment]
I can't reproduce. Highlighting is fine for me...

**Comment by clason** [comment]
I can reproduce it, but for me it only happens inside braces:

```
I think en-dashes are cool -- but not everyone agrees.  
```

is fine, but

```
{I think en-dashes are cool -- but not everyone agrees.}
```

is not. (But if this is the argument of a comment -- say, `\emph`, it's correct again.)

**Comment by lervag** [comment]
Ah, I should have been more clear: I can't reproduce it, thus I can't really do anything. Please provide a full minimal vimrc file as a start. I suggest you start with the following files: `VIMTEX/test/feature/syntax`. In particular, that `minivimrc` file will print the current syntax items when moving around the file, which is very convenient in order to debug the syntax stuff.

**Comment by clason** [comment]
Here's a minimal `vimrc`:

```
call plug#begin('~/.vim/plugged')
    Plug 'lervag/vimtex'
call plug#end()
```

(`vimtex` really has to be loaded via `vim-plug`; if you load it with the `let &rtp=...` approach in your `minivimrc` this doesn't happen.)

Using my example, I get the following syntax zones:
```
{I think en-dashes are cool -- but not everyone agrees.} 
 texDocZone->texZoneLua     texDocZone->texZoneLua->luaComment
```
(where the comment zone starts at the first dash). After this, things go haywire since there's no comment close (`\end{document} is `luaError`, then `luaTableBlock`).

**Comment by migueldvb** [comment]
I can reproduce this with neovim using the runtimepath definition in `vimrc` as shown in the example in #733.

**Comment by clason** [comment]
And, of course, in this situation `%` (and everything after it) is *not* treated as a comment).

**Comment by lervag** [comment]
I still can't reproduce this. I now use the following minimal vimrc:

```vim
set nocompatible

call plug#begin('~/.vim/bundle')
Plug 'lervag/vimtex'
call plug#end()

function! SynNames()
  return join(map(synstack(line('.'), col('.')),
        \ 'synIDattr(v:val, ''name'')'), ' -> ')
endfunction

augroup Testing
  autocmd!
  autocmd CursorMoved * echo SynNames()
augroup END

let g:vimtex_imaps_enabled = 0
let g:vimtex_view_enabled = 0
let g:vimtex_view_automatic = 0
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_indent_ignored_envs = ['document', 'proof']
```

I tried both with `vim` and `nvim`.

**Comment by lervag** [comment]
I'm on Vim version 8.0.427. Thus the problem might be related to a more recent Vim patch. I should probably get it pretty soon (Arch Linux, and I update regularly).

**Comment by clason** [comment]
I can reproduce it with your `vimrc` (modifying the path to `~/.vim/plugged`) on vim 8.0.324 and neovim 0.1.7.

Can you try with a fresh install of vimtex using vim-plug?

**Comment by clason** [comment]
Oh, and your test example in https://github.com/lervag/vimtex/commit/5892e404a12f84d24fc4b741d32a5c8ad1f93a24 does not match mine: The braces *cannot* be preceded by a command, otherwise it doesn't fail. It really has to be
``` 
{ {Wrong highlight after this--Oh no! I am no comment.} }
```
without the `\textbf` or `\Large`.

**Comment by lervag** [comment]
Ok, I installed vimtex fresh with vim-plug. Still can't reproduce. I did the following:

1. Removed old vimtex directory.
2. Started Vim, did `:PlugInstall`.
3. In terminal, went to `VIMTEX/test/issues/728`.
4. Did `vim -u minivimrc`.

Everything looks fine here. :\

**Comment by lervag** [comment]
Ok, now I reproduce it. I'll try to fix it as soon as possible!

**Comment by lervag** [comment]
Thanks for being vigilant and helping me reproduce the issue. When I finally was able to reproduce, it was quite easy to find the problem. Should work now!

**Comment by clason** [comment]
Yes, looks good now! Thanks for the quick fix! (And a pleasure to help; knowing next to no vimL, it's the only way I have to contribute to what I sincerely believe is the best TeX plugin out there.)

**Comment by lervag** [comment]
No problem, and thanks for the kind words. :)
