### ISSUE TITLE
\textbf disappears while typing

### ISSUE THREAD

**Issue by rumpelsepp** [lervag/vimtex#729]
How can I disable this behaviour? Is this intended?
I have attached a video to show my issue.

[out.ogv.gz](https://github.com/lervag/vimtex/files/854014/out.ogv.gz)

**Comment by lervag** [comment]
See `:h g:tex_conceal` and `:h conceallevel`. The simplest way is to do `:set conceallevel=0` in your vimrc file.

Note: This is not a vimtex feature, it is a feature of the "intrinsic" tex syntax plugin, see `:h vimtex-syntax`.

**Comment by rumpelsepp** [comment]
Thank you! I have searched for a few days, but I did use the wrong
keywords... Thanks!

On Mon, Mar 20, 2017 at 7:59 AM, Karl Yngve Lervåg <notifications@github.com

**Comment by lervag** [comment]
No problem :)
