### ISSUE TITLE
Enable temporarily syntax highlighting of matching parenthesis

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#730]
I do not like how the syntax highlighting of matching parenthesis slows down my vim.

I have added to my vimrc following setting to disable it which helped.
```viml
let g:vimtex_motion_matchparen = 0
```

However, occasionally I want to enable it to track down mismatched parenthesis/delimiter.

I have extended my own version of unimpaired.vim for `$VIMRUNTIME/plugin/matchparen.vim`:
```viml
nnoremap [op :DoMatchParen<CR>
nnoremap ]op :NoMatchParen<CR>
nnoremap cop :<C-R>=exists("g:loaded_matchparen") ? 'NoMatchParen' : 'DoMatchParen'<CR><CR>
```
Pressing `cop` toggles matchparen.

The commands `DoMatchParen` and `NoMatchParen` are defined as following
```viml
command! NoMatchParen windo silent! call matchdelete(3) | unlet! g:loaded_matchparen |
	  \ au! matchparen
command! DoMatchParen runtime plugin/matchparen.vim | windo doau CursorMoved
```
I would like to adjust the behaviour of vimtex with this mapping as well.

So I would like to have another option for vimtex which says that vimtex acknowledges the value of `g:loaded_matchparen` and set `g:vimtex_motion_matchparen = 0` if `g:loaded_matchparen` does not exist and set it `g:vimtex_motion_matchparen = 1` if `g:loaded_matchparen==1`

I haven't found a useful name yet:
```viml
let g:vimtex_motion_matchparen_only_if_builtin_is_loaded = 1
" default 0, current behaviour
```

### Update

There is also following pull request regarding the plugin `matchparen.vim`:

https://github.com/vim/vim/pull/1338

After copying this version of `matchparen.vim` to `~/.vim/plugin`, there is now a slight delay until  the matching parenthesis is highlighted. This looks like it does what is advertised.

Would you consider adding the lazy display via timers also to vimtex?

**Comment by kiryph** [comment]
I have thought about this again and I think following way could be easier:

Add a variable like this to vimtex:
```viml
let g:vimtex_overload_DoNoMatchParen = 1
```
The name can still be improved.

If this variable is set to `1` (default `0`), `:DoMatchParen`and `:NoMatchParen` are overwritten and first toggle vimtex-matchparen and then call the original `:DoMatchParen` and `:NoMatchParen` respectively. I am not sure whether vimscript allows this. However, their definition is straightforward and could be copied. Of course, the variable of `g:loaded_matchparen` should be respected.

This means a user could disable `$VIMRUNTIME/plugin/matchparen.vim` with `let g:loaded_matchparen = 0` but use vimtex-matchparen with these commands.

In this scenario my unimpaired mapping would work just fine
```
nnoremap [op :DoMatchParen
nnoremap ]op :NoMatchParen
nnoremap cop :<C-R>=exists("g:loaded_matchparen") ? 'NoMatchParen' : 'DoMatchParen'<CR><CR>
```

The second feature idea regarding support for lazy display via timers (https://github.com/vim/vim/pull/1338) could be added addtionally.

**Comment by kiryph** [comment]
I close this issue because I am happy with my setup and I am not sure whether an addition to vimtex would be a considerable improvement. The addition would an optional overwrite of `:NoMatchParen` and `:DoMatchParen`.

**Comment by lervag** [comment]
Thanks! I've not come around to this yet (currently working on #651, which is a pretty big task). However, I might be interested in updating vimtex according to some of these ideas. It is not clear exactly how, but it seems that it would be good if vimtex played better together with matchparen.

**Comment by lervag** [comment]
Ok, I've done a first iteration:

1. Separated the matchparen feature into `vimtex#matchparen` module.
2. Changed name `g:vimtex_motion_matchparen` to `g:vimtex_matchparen_enabled`.
2. Added `vimtex#matchparen#enable` and `vimtex#matchparen#disable`.

This should make your personal customization much simpler. Currently there is no real change to the feature itself, only to the code/API. But this should make it simpler to improve the code even further wrgt further ideas.

So: Although you've created your own config now: How could we improve vimtex further along the lines you've pointed out without making it "bloaty"? E.g., how should we change things to better play ball with `g:loaded_matchparen`? I am not certain that it makes sense to overload or directly do anything with the general MatchParen plugin, since that could be unexpected...

**Comment by lervag** [comment]
I think your new config should look something like this:

```vim
" Overwrite NoMatchParen and DoMatchParen for tex files:
command! NoMatchParen
        \ call vimtex#matchparen#disable() |
        \ windo silent! call matchdelete(3) |
        \ let g:loaded_matchparen = 1 |
        \ au! matchparen
command! DoMatchParen
        \ call vimtex#matchparen#enable() |
        \ unlet! g:loaded_matchparen |
        \ runtime plugin/matchparen.vim |
        \ windo doau CursorMoved
```
