### ISSUE TITLE
Biblatex/biber warnings when unsing --validate-datamodel are truncated

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#731]
### Explain the issue

`biber` can validate the data model of the underlying bib file when setting the command line switch `--validate-datamodel`. Warnings found using this mechanism are currently truncated by vimtex. The original message:

```
(/usr/share/texmf-dist/tex/latex/caption/ltcaption.sty) (./thesis.bbl

Package biblatex Warning: Biber reported the following issues
(biblatex)                with 'Amir2004':
(biblatex)                - Datamodel: Entry 'Amir2004' (thesis.bib): Invalid f
ield 'number' for entrytype 'misc'.

```

becomes

```
thesis.tex|| Package biblatex Warning: Biber reported the following issues with 'Amir2004':
```

inside the quickfix list

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

An MWE can be found in [this stackexchange positng](https://tex.stackexchange.com/questions/359438)

**Comment by lervag** [comment]
Is there an actual line break in the log file? That is, for `...Invalid f` and `ield 'number'...`? If so, then that will be impossible to parse.

**Comment by languitar** [comment]
Hm, I copied the message from the console output. Maybe latexmk or pdflatex itself do line wrapping there? In the log file it is not wrapped.

**Comment by languitar** [comment]
But it works well now.

**Comment by lervag** [comment]
Good to hear. I suspected that the hard wrap happened during the copying, but I wasn't sure. In any case, I'm happy it works.
