### ISSUE TITLE
Conceal breaks on multiple subscripts, commas

### ISSUE THREAD

**Issue by OJFord** [lervag/vimtex#734]
Conceal seems to support a multiple character superscript such as `$a^{(i)}$` fine, but `$a_{ij}$` renders `j` as a *super*script, and `a_{i,j}$` renders `j` as a subscript to a superscript `,`. `$a_{(i)}$` works as expected, but `${(ij)}$` again puts `j` as a subscript to the (subscript) `i`.

I think this is better explained by a couple of images:

![source](https://cloud.githubusercontent.com/assets/3946014/24197598/28ab20ba-0efa-11e7-955b-d28ee82d0c2e.png)

![conceal rendering](https://cloud.githubusercontent.com/assets/3946014/24197597/289d6c36-0efa-11e7-8941-4d0b5c134002.png)

**Comment by lervag** [comment]
This is not a vimtex issue. See `:h vimtex-syntax` and `:h g:tex_conceal`. You should instead contact Charles Campbell, see [here](http://www.drchip.org/astronaut/vim/index.html#SYNTAX_TEX).
