### ISSUE TITLE
Missing biber support

### ISSUE THREAD

**Issue by feanor12** [lervag/vimtex#737]
At the moment i get a lot of errors when typing `\ref{`
Maybe the ref list can be empty instead of creating errors, which disturbs the workflow.
It would be great if biber was support though.

**Comment by lervag** [comment]
What do you mean? Biber is/should be supported. What do you expect that I can do based on your issue description? Did you even read the issue template?

Please provide a minimal example of your problem. Based on your post it is impossible for me to say if 1) you're problem is related to something that is not supported, or 2) there is a bug, or 3) you are doing something wrong.
