### ISSUE TITLE
Support standalone package in multifile project

### ISSUE THREAD

**Issue by nchisholm** [lervag/vimtex#738]
First off, thank you for VimTeX! I'm using it now to write my PhD thesis.

Currently, I have the following issue.  Say I have my main latex file `./thesis.tex` which does `\input{./tex/ch1.tex}`.  If `ch1.tex` has `\documentclass{standalone}`, vimtex will assume ch1.tex is the main file when editing it in a buffer, even if I use one of the possible methods to try override this and specify a different main file (e.g., setting the TEX main directive). Specifically, my issue is that, while doing synctex forward searches within ch1.tex, it will always try to look at `./tex/ch1.pdf` (failing if this file does not exist).  However, I am wondering if it is possible to look in `./thesis.pdf` instead.  Of course, the problem goes away if I don't give `ch1.tex` the standalone class, so the workaround is easy. Also, inverse search works fine (I'm using Zathura).

Now, I realize this is a bit ambiguous because ch1.tex _can_ be compiled to its own pdf, and thus the observed behavior might be as intended by the user. One solution here would be to have VimtexToggleMain switch between the two possible "main" files, similar to its functionality for the import and subfiles packages (I did try activating this function in `./tex/ch1.tex` to no effect).

### Minimal working example

`./thesis.tex`
```tex
\documentclass{minimal}
\usepackage{standalone}

\begin{document}

\input{tex/ch1.tex}

\end{document}
```
`./tex/ch1.tex`
```tex
%! TEX root = ../main.tex
\documentclass{standalone}

\begin{document}

Blah blah I'm so smart give me a PhD.
% Not going to pass.

\end{document}
```

**Comment by lervag** [comment]
I think this is fixed now. `VimtexToggleMain` should also work as expected now.

I'm happy you enjoy the plugin! :)
