### ISSUE TITLE
quickfix window no longer opens automatically

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#739]
I just noticed that the quickfix window no longer opens automatically on LaTeX errors, although calling `VimtexErrors` shows them correctly. (Tested with a "naked" vimrc that only loads the plugin.)

**Update**: Weird, it works as expected with MacVim (8.0.502), but not with vi (7.4.8056, 8.0.324 or 8.0.502(!)) or nvim (0.1.7), both on Linux and Mac OS. Obviously not a vimtex problem, then; but I'm leaving this up for a bit in case anyone has an idea what's going on.
Possibly the same issue as #243.

**Comment by clason** [comment]
Seems like for a variety of reasons (different for each version of (neo)vim listed above), `clientserver` functionality was not working. I'll have to find out how to fix it consistently for the versions I'm actually using, but this is my own problem. Sorry for the noise!

**Comment by lervag** [comment]
No problem! :)
