### ISSUE TITLE
Allow to opt out of Font warnings

### ISSUE THREAD

**Issue by clason** [lervag/vimtex#740]
Following up on #671, I found a new warning I'd like not to see in the quickfix list: ` LaTeX Font Warning: `. Examples are

```
LaTeX Font Warning: Command \small invalid in math mode on input line 724.
LaTeX Font Warning: Font shape `T1/cmss/m/n' in size <0.5> not available size <5> substituted on input line 724.
LaTeX Font Warning: Size substitutions with differences up to 4.5pt have occurred.
```

**Comment by lervag** [comment]
Try now. Set `font: 0` in the quickfix option.

**Comment by clason** [comment]
Perfect, thank you very much!

**Comment by lervag** [comment]
You're welcome!

Den tir. 28. mar. 2017, 22.45 skrev Christian Clason <
notifications@github.com>:
