### ISSUE TITLE
Default general viewer xdg-open does not accept default view general options

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#741]
The default values on linux for viewing `*g:vimtex_view_general_viewer*` (`xdg-open`)
and `*g:vimtex_view_general_options*` (`-r @line @pdf @tex`) are not compatible:

```
❯ xdg-open -r 12 demo-tabular.pdf
xdg-open: unexpected option '-r'
Try 'xdg-open --help' for more information.
```

**Comment by kiryph** [comment]
My fault: default is fine. I changed the value in my vimrc. Sorry.

**Comment by lervag** [comment]
No problem :)
