### ISSUE TITLE
`viewer` cannot find PDF file

### ISSUE THREAD

**Issue by aldur** [lervag/vimtex#745]
I use macOS 10.12.4, neovim, and Skim as a PDF viewer.
Additionally, I have `$out_dir = 'build';` in my `.latexmkrc`.

After commit 6f349ed8611d5946f6afa4dfdfb0334ae77b59aa, every time I use `:VimtexView` I get the following error message:

```
vimtex warning: viewer can not read PDF file!
/path/to/file/file.pdf
Press ENTER or type command to continue
```

The correct path to the produced pdf file should be `/path/to/file/build/file.pdf`, i.e. the `build` directory is missing.
I still haven't had time to dig into the commit, so in the meantime any help is appreciated.

**Comment by lervag** [comment]
Sorry. Pushing a fix pretty soon.

**Comment by aldur** [comment]
Thanks for the quick response! :)

**Comment by lervag** [comment]
No problem!

Den tir. 28. mar. 2017, 16.12 skrev Adriano Di Luzio <
notifications@github.com>:
