### ISSUE TITLE
insert environment

### ISSUE THREAD

**Issue by yuejuny** [lervag/vimtex#746]
This is not an issue at all. I am wondering how vimtex adds short cuts for insert tables/list/ etc. For example, I found this short cut from http://www.lukesmith.xyz/conf/.vimrc that when I type ;ul in INPUT mode, the itemize is there for me. So I don't have to do the typing the "\beigin{..}\end{..}".

**autocmd FileType tex inoremap ;ul \begin{itemize}<Enter><Enter>\end{itemize}<Enter><Enter>(<>)<Esc>3kA\item<Space>**

**Comment by lervag** [comment]
vimtex does not really provide such shortcuts. vimtex provides minimal insert mode maps that are similar to normal vim abbreviations (see `:h iabbrev`). See `:help vimtex-imaps`.

The reason vimtex does not provide these more advanced shortcuts is explained in `:help vimtex-neosnippet`. The bottom line is that you should use a snippet plugin such as [neosnippet](https://github.com/Shougo/neosnippet.vim) or [UltiSnips](https://github.com/SirVer/ultisnips). These are general plugins that, when you get familiar with them, are very powerful and useful. Therefore I suggest you use them both for LaTeX and other filetypes.
