### ISSUE TITLE
Regression: E127: Cannot redefine function <SNR>137_actions_activate: It is in use

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#747]
I have encountered following error a couple of days ago and sticked to ff8543e which does not show this error.
```
...
Error detected while processing /Users/kiryph/.vim-configs/mbp13-osx-7.4.769+lua/bundle/.cache/vimrc/.dein/autoload/vimtex/index.vim:
line  180:
E127: Cannot redefine function <SNR>137_actions_activate: It is in use
```

### Steps to reproduce

1. $ vim main.tex
2. open vimtex-toc with `<leader>lt`
3. select an entry and open it. Everything is still fine.
4. open vimtex-toc with `<leader>lt` a second time.
5. select an entry and pressing <Enter> triggers this error message.

**UPDATE**
using the vimtex-toc a second time is not necessarily the problem. I haven't figured out yet, what the crucial step is. I have removed the lightline warnings. These were due to misconfiguration in my vimrc.

My vimtex related settings are:
```
let g:vimtex_index_show_help = 0
let g:vimtex_index_split_pos = 'full'
```

If necessary, I can provide a minimal example. However, I do not have the time right now for this and will stay with the old commit and won't pull any updates.

Regarding #730: your recent commit containing `call vimtex#matchparen#disable()` and new settings for my configuration work. As I said, I will stick with my old config due to this error.

**Comment by lervag** [comment]
It seems the old index implementation was not optimal. I've simplified and improved it and at the same time fixed this bug. At least now it works for me. Thanks for noticing and reporting!

**Comment by kiryph** [comment]
Thanks for your update. No error anymore.
