### ISSUE TITLE
Cursor moves in wrong direction when opening TOC window on left

### ISSUE THREAD

**Issue by anandtrex** [lervag/vimtex#748]
### Explain the issue

1. Steps to reproduce
Install NERDTree with default settings and add the following lines to `.vimrc`:
```
let g:vimtex_index_split_pos = 'vert botright'  " Set vimtex's TOC buffer to load on the right
```
Open NERDTree buffer first (on the left), then toggle vimtex's TOC window (on the right) with `:VimtexTocToggle`

2. Expected behaviour
The TOC buffer is opened on the left and the cursor moves to it. Moreover, on selecting sections in the TOC buffer with `o`, the open tex buffer moves to the selected section.

3. Observed behaviour
The TOC window is opened, but the cursor moves to the buffer on the left (NERDTree's buffer).
Even so, after moving the cursor manually to vimtex's TOC buffer, if I select a section, this loaded in the wrong buffer -- not in the buffer that the tex file was open, but in the buffer on the right (in this case NERDTree's buffer)

Note that if I use `:VimtexTocOpen` instead of `:VimtexTocToggle`, the cursor initially moves to the correct buffer, but when opening sections, it still loads them in the wrong buffer.

**Comment by lervag** [comment]
I think I've solved this, at least partially. Could you test? I did not try with NERDTree directly, but I reproduced the part where activating a TOC entry did not go to the right window.

**Comment by anandtrex** [comment]
Trying with this commit, with vimtex TOC buffer opening in the 'vert botright' position, the cursor still move to the wrong buffer. 

But if I move to the vimtex TOC window and open a section, that does open in the right buffer.

**Comment by lervag** [comment]
Could you provide a full minimal example? I suspect that this is due to a configuration problem on your side.

Please see the issue template if you need help creating a minimal example.
