### ISSUE TITLE
Error detected while processing compile, Funcref required

### ISSUE THREAD

**Issue by edasaki** [lervag/vimtex#751]
### Explain the issue

![cbk8g3u](https://cloud.githubusercontent.com/assets/3021442/24583329/6b87f62a-16fb-11e7-84ed-211372a00375.png)

I'm running on Windows with gVim, and I believe this is the only relevant portion of my vimrc:

```let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_latexmk_continuous = 0
let g:vimtex_view_general_options
                \ = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'
```

Pressing \ll causes this to happen. `latexmk` works fine from command line, and I'm not sure if there's any other common causes (although I haven't been able to find any similar problems after a lot of Googling :( )

Would appreciate any insight into what's wrong here

**Comment by lervag** [comment]
Have you updated to newest version? If so, you must update your options:

```vim
let g:vimtex_compiler_latexmk = { 'continuous' : 0 }
```

However, I don't think this is the main problem here. Could you please provide a minimal example (as explained in the issue template)? This includes a minimal vimrc files (not just the vimtex options) and a simple tex example.

It would also be helpful if you could provide the output of `\li` after you have encountered the error.

**Comment by hbushz** [comment]
I have the same problem as that
![problem](https://cloud.githubusercontent.com/assets/12067245/24600946/8cddd51c-1889-11e7-9d77-6a831720aeb8.JPG)

I'm running on Windows with gVim and the _vimrc is
`
set nocompatible

" Load Vimtex
" Note: The path might need an update
let &rtp = 'D:/Applications/Vimedt/vimfiles/vimtex,' . &rtp
let &rtp .= 'D:/Applications/Vimedt/vimfiles/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
"---------------------
" set vimtex 
" --------------------
 let g:vimtex_compiler_latexmk = {
     \ 'background' : 0,
     \ 'build_dir' : '',
     \ 'callback' : 1,
     \ 'continuous' : 0,
     \ 'options' : [
     \   '-pdf',
     \   '-verbose',
     \   '-file-line-error',
     \   '-synctex=1',
     \   '-interaction=nonstopmode',
     \ ],
     \}
" let g:vimtex_view_automatic = 1
" Disable overfull/underfull \hbox and all package warnings
let g:vimtex_quickfix_latexlog = {
      \ 'overfull' : 0,
      \ 'underfull' : 0,
      \ 'packages' : {
      \   'default' : 0,
      \ },
      \}
" Set PDF Viewer
let g:vimtex_view_general_viewer = 'D:/Applications/TeX/SumatraPDF/SumatraPDF.exe'
`

**Comment by lervag** [comment]
What is the Vim version? I can't reproduce this on Linux. :\

**Comment by hbushz** [comment]
The following is the output of  `:version`
```     
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Sep 12 2016 22:02:20)
MS-Windows 64-bit GUI version 
```
![problem751-2](https://cloud.githubusercontent.com/assets/12067245/24635419/dd65e1ce-1905-11e7-8474-2a537f34f590.JPG)

**Comment by lervag** [comment]
Ok. I'm booting my windows computer to test.

**Comment by lervag** [comment]
I found an error. But I also noticed that the callback stuff does not work. Things should work as expected without the callback, though, i.e., set:

```vim
let g:vimtex_compiler_latexmk = {
     \ 'callback' : 0,
     \ 'continuous' : 0,
     \}
```

I really don't like working with and on Windows. I tried to find a way to fix the callback stuff, but I am not able to. Sorry.

**Comment by hbushz** [comment]
Thank you for your concern

**Comment by lervag** [comment]
No problem. I'm thinking about upgrading vimtex to use the new Vim 8 jobs api. Perhaps this will simplify things on windows.

In the meantime, I will have to depend on contributions from (expert) windows users who can help me to solve problems with the latexmk layer.

**Comment by lervag** [comment]
I've pushed some updates now that _should_ improve things on windows. First, the callback should work. Second, vimtex now uses the Vim jobs api if available, which is more robust (and perhaps somewhat faster). However, this is pretty new, and although I've tested on my machines, there might still be bugs. I'd be happy if you could provide some feedback whether or not it works as expected.
