### ISSUE TITLE
Resent commit broke something in VimtexView, and Compile with regard to build directories

### ISSUE THREAD

**Issue by yashamon** [lervag/vimtex#755]
I have build_dir = './build' which worked fine until a recent update. Now both the compile and view commands ignore this build directory. On commit 5d263e1af70456e806965229c7d3c08b04155939 
things work fine. I haven't checked all the newer commits.

Edit. Actually commit 5d263e1af70456e806965229c7d3c08b04155939 still has the problem (vimtexview now works with build but compile does not), however I was able to get around the issue on latest commit by using latexmkrc build dir option.

**Comment by lervag** [comment]
See `:h vimtex-changelog` and/or `:h g:vimtex_latexmk_build_dir`. The option have a new name. This should work:

```vim
let g:vimtex_compiler_latexmk = {'build_dir': './build'}
```
