### ISSUE TITLE
Automatically set the working directory

### ISSUE THREAD

**Issue by dbmrq** [lervag/vimtex#756]
I just thought that it would be nice if when opening a tex file Vim would automatically set the working directory to the directory of the main file in the project. So I was trying to figure out how to get that main directory when I realized vimtex already does that. I checked the state.vim file and added a line saying `  let b:mainTexFile = l:main` and got what I wanted, but I think it would be cool if vimtex had the option of setting the working directory automatically, or at least you could expose that variable, I think it could be useful for other things too, like adding the directory to Vim's `path` option (maybe vimtex could automatically do that too?).

**Comment by lervag** [comment]
I think this should be possible through the event `VimtexEventInitPost`, something like this (I don't have the time to check now):

```vim
autocmd User VimtexEventInitPost exe 'cd' b:vimtex.root
```

**Comment by dbmrq** [comment]
Ah, that's perfect, thank you! :)

**Comment by lervag** [comment]
No problem ☺️

Den man. 3. apr. 2017, 20.16 skrev Daniel Marques <notifications@github.com
