### ISSUE TITLE
Enter and Space behave the same in table of contents

### ISSUE THREAD

**Issue by rthrmt** [lervag/vimtex#760]
I have a tex project separated into multiple files, each section has it's own file.
When I open the table of contents (<localleader>lt) and want to jump to a section/subsection hitting space and enter do the same thing, they open a new window and show that file. In an earlier build it didn't open a new window and instead showed the file in the current one. Is there a way to get the old behavior back?

**Comment by lervag** [comment]
Yes, this is a bug. I'll work on it asap.

**Comment by lervag** [comment]
Ok, I think it works as expected now.

**Comment by rthrmt** [comment]
It does, thank you very much!

**Comment by lervag** [comment]
You're welcome!

Den tor. 6. apr. 2017, 12.00 skrev rthrmt <notifications@github.com>:
