### ISSUE TITLE
\ref and \cite completion in multi-file documents

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#763]
When switching to the `local` mode `vimtex` also switches pointers to the aux files. This has two sides:

1. Since in local mode the local file is compiled more often, `vimtex` provides access to local references almost immediately.
2. But as soon as the file is a part of the larger project with main.aux file and the bibliography defined in the main file as well, `vimtex` looses the access to the `\cite` completion and outer `\ref` completion.

It seems for me that this two sides may be merged, by trying to complete from both `local` and `main` auxilary files. Also it worth checking main files' bibliography.

**Comment by lervag** [comment]
Yes, I think you are right that we should be more aware of the current state while completing citations and references.

It would be very useful to have a minimal example that includes both citations and references while testing/developing. Could you provide this? I'm thinking it should consist of a simple, multi-file TeX project (probably enough with two files).

It would also be good to have a specific set of actions and expected consequences.

**Comment by maxfl** [comment]
Here it is: [local_ref_cite.zip](https://github.com/lervag/vimtex/files/909283/local_ref_cite.zip)

Actions in main file `test.tex` (after compilation):
- Type `\cite{}` and try omni-completion within `{}`. It opens the menu with two items: link 1 and link 2.
- Type `\ref{}`  and try omni-completion within `{}`. It opens the menu with four items: sections 1 to 4. Two section are defined in main file and two in the sub- file.

Actions in sub- file `sub.tex` in the `main` mode. Basically same as with `tex.tex`:
- Type `\cite{}` and try omni-completion within `{}`. It opens the menu with two items: link 1 and link 2.
- Type `\ref{}`  and try omni-completion within `{}`. It opens the menu with four items: sections 1 to 4. Two section are defined in main file and two in the sub- file.

Actions in sub- file `sub.tex` in the `local` mode (file is not compiled):
- Type `\cite{}` and try omni-completion within `{}`. No completions.
- Type `\ref{}`  and try omni-completion within `{}`. No completions.

Actions in sub- file `sub.tex` in the `local` mode (file is compiled):
- Type `\cite{}` and try omni-completion within `{}`. No completions.
- Type `\ref{}`  and try omni-completion within `{}`. It opens the menu with two items: sections 3 and 4. Both are defined in the sub- file.
- Define new `\label`. Compile. Try to complete `\ref`: see 3 items, two old and one new.

When working with the sub- file I expect.
- When completing `\cite{}` I expect to see both the citations defined in the .bib file referenced from the main file.
- When completing `\ref{}` I expect it to show all the 4 section from the main file, without duplications.
- When adding new label I expect the `\ref` completion to contain all the labels from the main file as well as new label from the sub- file.

**Comment by lervag** [comment]
Thanks! I'll look into this when I get the chance.

**Comment by lervag** [comment]
I think `\cite` completion now works as expected. Can you please test?

**Comment by lervag** [comment]
And now also `\ref` completion. Note: With `\ref` completion, we use the main file's references if the main file's aux file is available. Else we fall back to the subfile aux file.

> When adding new label I expect the \ref completion to contain all the labels from the main file as well as new label from the sub- file.

I understand you want this, but it increases the complexity quite alot. How important is it, you think? How does the current version work for you?

**Comment by lervag** [comment]
Nah, it wasn't that difficult. The page number and references are not perfect, though, but I think the completion should be satisfactory now.

**Comment by maxfl** [comment]
OK, I've got three message. Sounds awesome, but I'll be able to test it only next week. Thank you.

⁣Sent from Blue ​

**Comment by maxfl** [comment]
It works in both MWE and my documents. And it's awesome (:

Having the possibility to use new local labels is important, because the main file compilation may be very long.

Thank you!

**Comment by lervag** [comment]
Great, I'm happy to hear it! :)
