### ISSUE TITLE
local/main mark in statusline [airline]

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#765]
I think it is useful to have the information on whether the file is loca/main in the statusline.
Based on the example I've written an extension to the `airline` vim plugin to do it.

I do not know which is the best way to share it, so I attach it here for now.
[vimtex.vim.zip](https://github.com/lervag/vimtex/files/905549/vimtex.vim.zip)

The file should be put into airline/autoload/extensions folder. Also you need to add the following lines to airline/autoload/extensions.vim:
```vim
  if (get(g:, 'airline#extensions#vimtex#enabled', 1))
   call airline#extensions#vimtex#init(s:ext)
   call add(loaded_ext, 'vimtex')
  endif
```

Probably it would be good to add a trigger to `vimtex` in order to redraw the statusline after initialization. The style may be updated and the extension may be added to the `airline`.

**Comment by lervag** [comment]
I'm curious: would it not be easier to instead have a function available from vimtex that would print the status, and then use this in a simple vimrc customization of the airline statusline?

I use a custom, personalized statusline, but I used airline some years ago. If I remember correctly, it was pretty easy to add to the statusline through simple customizations in the vimrc file. E.g., I could add fugitive information through `fugitive#statusline()`.

**Comment by lervag** [comment]
Just to be clear: What I mean is, is it not better to allow an explicit interface that is easy to use, then to add an extension?

**Comment by maxfl** [comment]
@lervag, I agree with you and actually wanted to ask for it. I've decided to produce some example before asking. In the meantime I've checked the `vimtex` code in case such a function already exists and found that it's quite straightforward to do it and gave it a shot.

**Comment by maxfl** [comment]
The airline is what I'm using, that's why the example is for `airline`, but not for the vim's `set statusline`.

**Comment by lervag** [comment]
Ok, so you are not proposing that I add the airline extension to vimtex?

For the trigger, you could use the `VimtexEvenInitPost` event, something like this:

```vim
autocmd User VimtexEventInitPost call FunctionToRefreshAirlineStatus()
```

**Comment by maxfl** [comment]
right. After you make a function the extension may be actually added to the `airline` itself and work out of the box. I thought you may want to suggest how it should look like.

**Comment by maxfl** [comment]
thanks for the autocommand.

**Comment by lervag** [comment]
Hmm... I'm not quite sure I understand exactly what you are asking/proposing here. I think your airline extension looks pretty good. I would write the vimtex part slightly more concise:

```vim
function! airline#extensions#vimtex#get_scope()
  return get(get(b:, 'vimtex_local', {}), 'active')
        \ ? '[L]' : '[M]'
endfunction
```

The `get` function returns 0 if the key/item is not available. Thus this will return 1 only if the `b:vimtex_local` is available, and if it contains `b:vimtex_local.active = 1`.

**Comment by lervag** [comment]
As this is so straightforward, I don't really think it is necessary to add a new function for it. I don't plan to remove/change the `b:vimtex_local` dictionary, as I think it serves a purpose. I also think other plugins are allowed to read and use the state variables.

**Comment by maxfl** [comment]
I was actually asking for the '[M]/[L]' identifiers. As you OK with it I will submit a patch for the `airline`. Thanks for the code suggestions, looks good.

**Comment by lervag** [comment]
No problem! And no, I don't mind that you submit this for airline. I would even suggest that you add the compiler status. This should be pretty easy to add with `b:vimtex.compiler.is_running()` (obviuosly, you have to check that this is available before you run it). You could also use `b:vimtex.compiler.continuous` to check if the compiler is in continuous mode. If it is not, then it does not make sense to show the compiler status.

However, I want to make it clear that vimtex might change, and that I am not responsible for the airline extension. Thus, if I should push a breaking change (I don't plan to, at the moment), then you or someone else should make sure to update the airline extension.

**Comment by maxfl** [comment]
Sounds good. I will check which features worth including into statusline and will update the script. I will continue using `vimtex` and will be able to update the script in case compatibility is broken. 

I will post the function I'm using. I hope you will notify me if anything changes.

**Comment by maxfl** [comment]
is it possible to get the following status items?
- compilation error occured
- viewer is opened

**Comment by lervag** [comment]
You can do `vimtex#qf#inquire()` to check for compilation errors, but I wouldn't do it too often. There is no general way to check if a viewer is opened, but for `mupdf` and `zathura`, you can look for the `b:vimtex.viewer.xwin_id`.

**Comment by maxfl** [comment]
thanks. Ok, I will not use the compilation status.

**Comment by lervag** [comment]
Could we close this issue? Feel free to ask more questions, I'll answer even if it is closed.

**Comment by maxfl** [comment]
sure

**Comment by maxfl** [comment]
Is there any simple way or function to tell, whether the main file is the current file?

**Comment by lervag** [comment]
```vim
" This will work if you are editing normally, i.e. not within a subfile
expand('%:p') ==# b:vimtex.tex

" This should always work
expand('%:p') ==# get(vimtex#state#get(b:vimtex_local.main_id), 'tex')
```

**Comment by maxfl** [comment]
It looks like I simply can test the existence of `b:vimtex_local`. If it exists, the current file is included in some main file. Right?

**Comment by lervag** [comment]
Yes, you're right. If it does not exist, then the current file is a main file.

**Comment by maxfl** [comment]
Do you know, is it possible to check for `vimtex` existance before the ftplugin is loaded? I've tried `if exists('*vimtex#init')` but it works only within tex files.

**Comment by lervag** [comment]
Not quite sure what you mean by existence. Could you do `exists('b:vimtex')`? If I understand correctly, this should work because any `tex` filetype will have this buffer variable defined.

**Comment by maxfl** [comment]
this is needed for the configuration stage of the `vim-airline` and is executed once on the initialization stage.

**Comment by lervag** [comment]
Ah, you mean to check if vimtex is installed? Perhaps like this:

```vim
runtime autoload/vimtex.vim
return exists('*vimtex#init')
```

An important point is that autoloaded scripts are only loaded when they are needed. I.e., `exists(...)` won't work until you have loaded the script. Doing `runtime ...` will load the script, and thus the `exists(...)` should work afterwords. If there was no `autoload/vimtex.vim`, then it will return 0.

**Comment by maxfl** [comment]
It works, thank you!

**Comment by lervag** [comment]
Np!

Den ons. 19. apr. 2017, 16.09 skrev maxfl <notifications@github.com>:

**Comment by maxfl** [comment]
extension is merged
https://github.com/vim-airline/vim-airline/pull/1462

**Comment by lervag** [comment]
Great! Good work! :)
