### ISSUE TITLE
E40: can't open errorfile with build_dir

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#768]
### Explain the issue

After the switch to the new jobs backend, in non-continuous mode, the `build_dir` is not handled correctly when setting `errorfile` (`cfile`/`cgetfile`) to populate the quickfix.

Pressing `\ll` gives `E40: can't open errorfile test.log`, although the build works.
`\le` works correctly.

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}
Hello World!
\end{document}
```

### Minimal vimrc file

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable
let g:vimtex_compiler_latexmk = {
    \ 'continuous': 0,
    \ 'build_dir': 'build',
    \ }
```

**Comment by lervag** [comment]
Thanks, I've reproduced this. I'll try to fix it asap.

**Comment by lervag** [comment]
I think it should be fixed now. This should also fix the same problem for the Vim jobs backend.

**Comment by andymass** [comment]
Works great, thanks!  I'm really liking the change to the new jobs back-end so far.

**Comment by lervag** [comment]
Thanks! I don't think it should have that much of an impact as long as the processes are run in the background, but perhaps it feels slightly more robust and snappy? On the code side, I think it makes things simpler and better, which is important.

**Comment by andymass** [comment]
If I understand correctly, prior to using job_start there was no way to receive a callback in background+non-continuous compile mode.  So, for me the new way is an improvement.

**Comment by lervag** [comment]
True! :)
