### ISSUE TITLE
`-pdf' option causes '.latexmkrc' option '$pdf_mode' being ignored

### ISSUE THREAD

**Issue by zhouyan** [lervag/vimtex#777]
It seems the '-pdf' option is being hard coded in vimtex and it causes `pdflatex` being used regardless `latexmkrc` options such as `$pdf_mode`

**Comment by lervag** [comment]
No, it is not hardcoded, it is default. See `:h vimtex_compiler_latexmk`. To remove it, use this:

```vim
let g:vimtex_compiler_latexmk = {
      \ 'options' : [
      \   '-verbose',
      \   '-file-line-error',
      \   '-synctex=1',
      \   '-interaction=nonstopmode',
      \ ]}
```

**Comment by lervag** [comment]
Note: If you remove the flag from the default options, then you should specify the latex engine (e.g. `pdflatex`) either through a tex directive (see `:h vimtex-tex-directives`) or through a global/local `.latexmkrc` file.
