### ISSUE TITLE
Cursor position

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#781]
`vimtex` changes the behavior of the cursor when changing the lines of different length. Consider the following file:
```
line 1 very long long long line
short line 2
line 3 very long long long long long long line
```
1. In a plain file with such a contents, put the cursor on the end of the first line. Or use any position longer then the second line.
2. Press `down` `down`.
3. The cursor jumps to the end on the second line, and then to the position it had on the line 1.
4. `setf tex` (`vimtex` enabled)
5. Repeat the procedure. Now in the end the cursor happens to be on the position it had on the line 2.

Setting `g:vimtex_enabled=0` solves the issue.

I'm not sure which configuration options change the behavior. Is it possible to control it or to switch it back somehow? The default behavior is especially useful when editing latex tables with '\hline/\midrule' commands. They are usually shorter than data lines and keeping the position between data lines helps a lot.

**Comment by lervag** [comment]
Good question! I'll look into it, as I think this is a bug. At least it is not an intended behaviour.

**Comment by lervag** [comment]
This is due to the extended `matchparen` mode. As a temporary workaround, you can disable it with `g:vimtex_matchparen_enabled = 0`.

**Comment by lervag** [comment]
I think this should work. Note, though, that it only works when you have `getcurpos()`, which was introduced by patch 7.4.313.

**Comment by maxfl** [comment]
It works, thank you for the quick fix!

**Comment by lervag** [comment]
No problem :)
