### ISSUE TITLE
RFC: Cache vimtex-indices

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#782]
I have used vimtex-toc with the setting `g:vimtex_index_split_pos=full`. Right now I have also tried `nnoremap <localleader>lt :<c-u>Denite vimtex_toc<cr>`.

I do not like the delay until vimtex-toc is open.

I assume the toc is always recreated when I press `<localleader>lt` (either denite or the standard vimtex-toc window).

Would it be possible to cache the indices (toc or labels) and update the cache in certain situations in the background automatically (e.g. Bufwrite event for tex files) or manually with the mapping `<localleader>lx`. Initial setup of the indices by vimtex_init.

**Sidenote**  
Another observation regarding denite is that the mappings 
```vim
	" Change mappings.
	call denite#custom#map(
	      \ 'insert',
	      \ '<C-j>',
	      \ '<denite:move_to_next_line>',
	      \ 'noremap'
	      \)
	call denite#custom#map(
	      \ 'insert',
	      \ '<C-k>',
	      \ '<denite:move_to_previous_line>',
	      \ 'noremap'
	      \)
```
are very slow (vim8.0525) Most likely a denite issue.

**Comment by lervag** [comment]
I agree this could be cached. I'll look into it.

**Comment by lervag** [comment]
Btw: I think the denite related observation should be addressed to denite, not vimtex.

**Comment by lervag** [comment]
Ok, I've pushed a first version. This only introduces an option `g:vimtex_toc_refresh_always` which is enabled by default. If you disable it, the toc entries are only generated once. This is of course not quite what we're after, but it will be much faster on subsequent opening of toc windows, and you can refresh the toc entries through `\lx` (by reloading vimtex).

I'm curious: How big LaTeX project do you need before you feel this feature is required?

**Comment by kiryph** [comment]
Setting `g:vimtex_toc_refresh_always` to zero helped for `\lt`. Thanks.

### Errors triggered by `\lx`
However, if I want to update manually, `\lx`generates a long list of errors:
```
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/AdvancedSorters/Ranges.vim:
line  188:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
line  189:
E108: No such variable: "s:save_cpo"
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/comfortable_motion.vim:
line   90:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
line   91:
E108: No such variable: "s:save_cpo"
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/dein/command/check_clean.vim:
line   43:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
line   44:
E108: No such variable: "s:save_cpo"
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/dein/command/check_install.vim:
line   48:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
line   49:
E108: No such variable: "s:save_cpo"
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/dein/command/check_lazy_plugins.vim:
line   43:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
line   44:
E108: No such variable: "s:save_cpo"
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/dein/command/check_update.vim:
line   48:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
line   49:
E108: No such variable: "s:save_cpo"
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/dein/command/clean.vim:
line   60:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
line   61:
E108: No such variable: "s:save_cpo"
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/dein/command/clear_state.vim:
line   40:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
line   41:
E108: No such variable: "s:save_cpo"
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/dein/command/direct_install.vim:
line   48:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
line   49:
E108: No such variable: "s:save_cpo"
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/dein/command/each.vim:
line   56:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
line   57:
E108: No such variable: "s:save_cpo"
Error detected while processing /Users/kiryph/.cache/vim/dein/.cache/vimrc/.dein/autoload/dein/command/install.vim:
line   48:
E121: Undefined variable: s:save_cpo
E15: Invalid expression: s:save_cpo
Interrupted
```
Do you know what is going on here?

### BufWrite
If I want to update the toc on everywhere write, should I use following?

```
au BufWrite *.tex normal <Leader>lx
```

### Size of the LaTeX project
The LaTeX project is, I think, medium size: 1 main latex file and 20 small subfiles (1 file for each of the seven chapter and separate files for abstract, titlepage and so forth). I have separated many things in different files. The last line of the vimtex-toc has line number 55.

**Comment by lervag** [comment]
Sorry for taking so long. First, some answers:

1. The errors triggered with `\lx` are strange. I experienced similar errors, but I was not able to understand what caused them. At the moment, I am not able to reproduce them.

2. No, I would not recommend using `\lx` for this purpose. This binding reloads vimtex, and will implicitly stop compilation and similar things. Thus it has "side effects" that are not intended if you just want to update the toc. I've made some minor updates, so now this should work:

```vim
au BufWritePost *.tex call vimtex#toc#refresh()
```

When you think the updated ToC feature is OK, I'll make corresponding changes for the table of labels.

**Comment by lervag** [comment]
Note that you'll need to do a local hard reset on the feature branch due to a forced push.

**Comment by kiryph** [comment]
Thanks for the update. I had to delete the cloned repository and run git clone again. Anyway.

I have added to my ~/.vim/after/ftplugin/tex.vim
```
nnoremap <buffer> <Leader>lf :call vimtex#toc#refresh()<CR>
```
and to my vimrc:
```
let g:vimtex_toc_refresh_always = 0
augroup vimtex
    autocmd!
    autocmd BufWritePost *.tex call vimtex#toc#refresh()
augroup END
```

However, it does not update the toc, after I have changed for example a chapter name in a subfile.

**Comment by lervag** [comment]
Hmm. Could you provide a minimal tex example? I did not try with subfiles,
but it seemed to week with a normal multi file project.

**Comment by lervag** [comment]
Ok, I've pushed some updates, including a simple minimal test at `VIMTEX/test/issues/782`. Could you go there, then try:

1. `[n]vim -u minivimrc main.tex`
2. `\lt` to open toc
3. `<c-w>w` to go back to tex buffer
4. Add a section or something, then `:w`

With the above steps, I would expect the toc to update after `:w`. The same test should also work for the table of labels.

If you disable the autocmd and add mappings to refresh, they should also work as expected. But a mapping is not really necessary if you want the autocommands, since the feature relies on reading the file contents, not the buffer contents. Thus if you update when saving files already, then there is no need to update with a manual mapping.

Assuming things work also for you, it remains to add documentation. I think that the autocommand example should be included.

**Comment by kiryph** [comment]
Thanks for the update and writing the test!

Yes, it works as you describe.

However, using follow modified `minivimrc`:
```viml
set nocompatible
" let vimtex_basedir='~/.cache/vim/dein/repos/github.com/lervag/vimtex'
let vimtex_basedir='~/.vim/bundle/vimtex'
let &rtp  = vimtex_basedir.',' . &rtp
let &rtp .= ','.vimtex_basedir.'/after'
filetype plugin indent on
syntax enable

let g:tex_flavor = 'latex'

let g:vimtex_toc_refresh_always = 0
let g:vimtex_labels_refresh_always = 0

set hidden
let g:vimtex_index_split_pos = 'full'

augroup vimtex
  autocmd!
  autocmd BufWritePost *.tex call vimtex#toc#refresh()
  autocmd BufWritePost *.tex call vimtex#labels#refresh()
augroup END
```

I can reproduce my issue with following steps

1. `[n]vim -u minivimrc-modified main.tex`
2. open in full toc to see the original toc with `\lt`.
3. close it with `q`, `esc`
4. add/modify an entry
5. save the file with `:w`
5. open in full toc to see the updated toc with `\lt`. However, it is outdated and not updated.

**Comment by lervag** [comment]
Ah, I see. Reproduced. Will try to fix it asap.

**Comment by lervag** [comment]
Can you update and try now?

**Comment by lervag** [comment]
I've now added documentation and opened a PR, see #806. To keep things clear, let's continue the discussion there.
