### ISSUE TITLE
vimtex using sh on fish shell

### ISSUE THREAD

**Issue by GiusBen** [lervag/vimtex#783]
I haven't found a reason for this in any previously submitted issues and in the vimtex manual, so I thought it was the case reporting it here.
I'm trying to use vimtex on fish shell, but compiling produces no output.
From `:VimtexInfo` I see that value `cmd` is equal to `set max_print_line 2000; and latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e '$pdf_previewer = "open"' 'doc.tex'`, but after compiling via `<leader>ll` the output file (accessed via `<leader>lo`) only contains the string `sh: and: command not found`. 
Is there any option to set in order not to use `sh` but fish to invoke the command stored in `cmd`?

---

Just editing to add that I'm on MacOS X 10.12, fish 2.5.0, using vim-plug.

**Comment by lervag** [comment]
Ah. I realize I made a silly mistake here. I've hardcoded `sh` as the shell for the `nvim` and `jobs` backends. One possibility would be for you to change your shell to `sh` with `set shell=/bin/sh`, but I think it might be more appropriate that I fix this. However, I don't really know how, yet, so it might need some time.

**Comment by clason** [comment]
Weird, it's working fine for me with neovim inside fish on MacOS X 10.12 -- but I do have a sh in /bin, and I'd be very surprised if you didn't?

**Comment by lervag** [comment]
@clason Good question. A follow up question from me: Would it be OK for me to continue using `sh` even though people set `fish` as their main shells? In that case, I guess it is better to use an explicit path. Now I simply use `sh`, not `/bin/sh` or `/usr/bin/sh`.

**Comment by clason** [comment]
Yes, /bin/sh should be available on any Unix/BSD derivative (although it might not be the same shell; these days, though, it should be safe to assume bash (compatible)). I guess the problem here is then that for some reason /bin is not in the path. The alternative would be to use `/usr/bin/env sh` (or `/usr/bin/env bash`), see http://unix.stackexchange.com/questions/29608/why-is-it-better-to-use-usr-bin-env-name-instead-of-path-to-name-as-my. Not sure what that'd do on Windows, though...

**Comment by lervag** [comment]
@clason Is your `shell` option also `fish` inside Vim/neovim?

**Comment by clason** [comment]
No, I just started `fish` from my standard shell (bash) and ran neovim. I don't have `shell` set in either.

**Comment by lervag** [comment]
And I think that's why things work for you. The reason this does not work for @GiusBen is that his `shell` is set to `fish` (I think Vim inherits the standard shell in case it is not explicitly set). And I have mixed fish shell and sh, which is wrong. I'll need to fix this, but not right now.

**Comment by clason** [comment]
Yes, that's correct: `:! echo $0` returns `/bin/bash`. Running `env SHELL=/usr/local/bin/fish nvim` reproduces the problem.

**Comment by GiusBen** [comment]
Thanks for your fast replies. Using `set shell=/bin/sh` works good enough as a temporary fix.

**Comment by lervag** [comment]
Ok, I think it should work now. I allowed myself a "simple" fix which uses `sh` as the job shell even though you use `fish` as your personal shell. It seems to work well for me (I've reproduced the problem, see the related test files).
