### ISSUE TITLE
set nomagic breaks mappings

### ISSUE THREAD

**Issue by Bellaktris** [lervag/vimtex#784]
### Explain the issue

With nomagic text objects and insert-mode delimiter closing mapping doesn't work (may be some others too).

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}

\begin{enumerate}


\end{document}
```

1. Place cursor at the line just next to the \begin{enumerate}
2. Press ]]
* Nothing is inserted while I expect to see \end{enumerate}

### Minimal vimrc file

```vim
set nocompatible

let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

set nomagic 
```

**Comment by lervag** [comment]
Ah, yes. I've probably not managed to be explicit with the regex type throughout. I'll look into it.

**Comment by lervag** [comment]
There might still be errors like this, but at least this fixes the problem you mention.

Btw: Why do you set nomagic? Even the `:h 'magic'` text warns about this.

**Comment by Bellaktris** [comment]
I just found nomagic more convinient. I search for some code parts with special symbols more often then for regular expressions. Do you think you can fix the following mappings too?

```tex
\documentclass{minimal}
\begin{document}

\begin{enumerate}
  \item ...
\end{enumerate}

\end{document}
```

1. Place cursor at the item line and try to press tse or vie or place cursor at the \begin{enumerate} and press %
2. I am getting error "E62: recursive \?" in vimtex#delim$get_matching and nothing happens after while I expect mapping to work without errors

**Comment by lervag** [comment]
Strange, I can't reproduce this. I believe it might be a different issue. Could you open a new issue for this?

**Comment by Bellaktris** [comment]
Interesing. Okay, I will open a new one.
