### ISSUE TITLE
Denite source: Denite <tab> does not show vimtex_toc

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#785]
Disclaimer: I do not have any experience with writing Denite sources.

However, I have noticed following:

`:Denite <tab>` does not list `vimtex_toc` but `toc` which when invoked does not work.
I think the filename `toc.py` should match the source name (or the other way around).
Either rename the file to `vimtex_toc.py` or simply name the source in the file `toc`.

**Comment by lervag** [comment]
Ok, I tried to rename as you suggest. Let me know if it works.

**Comment by kiryph** [comment]
Yes, it works. Thanks.

**Comment by lervag** [comment]
Great :)
