### ISSUE TITLE
Textobjects iP and aP struggle with \partial

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#786]
Example tex file:
```tex
\documentclass[]{article}
\begin{document}
\paragraph{Paragraph 1}
This is an inline equation $\frac{\partial f(x)}{\partial x}$.
\begin{itemize}
  \item item
\end{itemize}
This is an inline equation $\frac{\partial f(x)}{\partial x}$.
\end{document}
```

Position the cursor on item. `vaP` and `viP` do no select the expected lines. (`vaP`: 3-8, `viP`: 4-8)

It looks like the subword `\part` of `\partial` is considered as a section boundary. I suspect the section search regex `s:section_search` must be improved. My first thought is: no alphabetic character should follow `\part` and other.

**Comment by kiryph** [comment]
My fix would be adding `\\>`:

```viml
" Pattern to match section/chapter/...
let s:section_search = '\v%(%(\\<!%(\\\\)*)@<=\%.*)@<!\s*\\\zs('
      \ . join([
      \   '%(sub)?paragraph\\>',
      \   '%(sub)*section\\>',
      \   'chapter\\>',
      \   'part\\>',
      \   'appendix\\>',
      \   '%(front|back|main)matter\\>',
      \   '%(begin|end)\{\zsdocument\ze\}'
      \  ], '|')
      \ .')'
```

**Comment by kiryph** [comment]
Sorry my fix was not good.

```
let s:section_search = '\v%(%(\\<!%(\\\\)*)@<=\%.*)@<!\s*\\\zs('
      \ . join([
      \   '%(sub)?paragraph\ze\W',
      \   '%(sub)*section\ze\W',
      \   'chapter\ze\W',
      \   'part\ze\W',
      \   'appendix\ze\W',
      \   '%(front|back|main)matter\ze\W',
      \   '%(begin|end)\{\zsdocument\ze\}'
      \  ], '|')
      \ .')'
```

**Comment by lervag** [comment]
Strange. Why didn't the last thing work?

**Comment by kiryph** [comment]
First of all I've misread your regex and I thought I have to escape the backslash.

I still do not understand the first part very well. The purpose seems to be excluding comments from the section_search.

The part of the regex I do not get is:
```
\v%(%(\\<!%(\\\\)*)@<=\%.*)@<!
```
Using vim help to decipher it:
- `\v` very magic (everything except [a-zA-Z0-9] has a special meaning)
- `%(%( ` groupings
- `\\` literal backslash
- `<` beginning of a word
- `!` **I haven't found a description of \! in the vim help**. Is this a literal `!`?
- `\\\\` two literal backslashes (why)
- `*` 0 or more matches
- `@<=` matches with zero width if the preceding atom matches just before what follows

The last items are clear to me:
- `\%` literal percentage sign
- `.*` arbitrary text
- `@<!`  matches with zero width if the preceding atom does **NOT** match just before what follows

Can you explain to me the reason for `!` and `\\\\`?

**Comment by lervag** [comment]
The first part ensures that the section names are not preceded by double slashes. E.g., we should _not_ match `\\section`.

**Comment by lervag** [comment]
But I think you've spotted a minor bug: It should be `\\@<!`, not `\\<!`.

**Comment by kiryph** [comment]
Thanks for the explanation. I don't feel too stupid since the `@` had missed.

And the second issue with my first proposal was that I had forgotten that the whole expression is very magic: instead of `\\>` it should have been a `>`.

**Comment by lervag** [comment]
No need to feel stupid regardless, complex regexes are not exactly human readable, even if you know the different atoms by heart. In any case, I've updated again, now with `>` instead of `\ze\W`, which seems more appropriate. :)

**Comment by kiryph** [comment]
Are you sure that `\\paragraph` is not considered as a section boundary?
```
\% \paragraph{Section Boundary}

no\\paragraph/section boundary

% no \paragraph/section boundary

no $\partial$ section boundary

CURSOR
```

`vaP` selects also `no\\paragraph/section boundary`.

**Comment by lervag** [comment]
Ah, sorry: I was wrong: the regex matches anything that is not a comment. I.e., it ensures that the line does not have `%` in front, and avoids `\%`.

I could update to also avoid the double `\\`, but I don't really think it is necessary. It should never really be a problem, I think.
