### ISSUE TITLE
E871 and E62 with "set nomagic"

### ISSUE THREAD

**Issue by Bellaktris** [lervag/vimtex#788]
With nomagic text objects and `%` motion produces errors and don't work.

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}

\begin{enumerate}
  \item ...
\end{enumerate}

\end{document}
```

1. Place cursor at the item line and try to press `tse` or `vie` or place cursor at the `\begin{enumerate}` and press `%`
2. I am getting error `"E62: recursive \?"` in `vimtex#delim#get_matching` and nothing happens after while I expect mapping to work without errors

### Minimal vimrc file

```vim
set nocompatible
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:tex_flavor = "latex"
set nomagic 
```

**Comment by lervag** [comment]
Ok, as in #784: I can't reproduce this. I'm using your minimal vimrc file: `vim -u minivimrc test.tex`.

Which version of Vim are you using? Are you using gui version? Which OS?

**Comment by Bellaktris** [comment]
I tried both latest neovim: NVIM v0.2.0-dev

and vim:

VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Nov 24 2016 16:44:48)
+acl             +farsi           +mouse_netterm   +tag_binary
+arabic          +file_in_path    +mouse_sgr       +tag_old_static
+autocmd         +find_in_path    -mouse_sysmouse  -tag_any_white
-balloon_eval    +float           +mouse_urxvt     -tcl
-browse          +folding         +mouse_xterm     +terminfo
++builtin_terms  -footer          +multi_byte      +termresponse
+byte_offset     +fork()          +multi_lang      +textobjects
+channel         +gettext         -mzscheme        +timers
+cindent         -hangul_input    +netbeans_intg   +title
-clientserver    +iconv           +packages        -toolbar
-clipboard       +insert_expand   +path_extra      +user_commands
+cmdline_compl   +job             -perl            +vertsplit
+cmdline_hist    +jumplist        +persistent_undo +virtualedit
+cmdline_info    +keymap          +postscript      +visual
+comments        +langmap         +printer         +visualextra
+conceal         +libcall         +profile         +viminfo
+cryptv          +linebreak       -python          +vreplace
+cscope          +lispindent      +python3         +wildignore
+cursorbind      +listcmds        +quickfix        +wildmenu
+cursorshape     +localmap        +reltime         +windows
+dialog_con      -lua             +rightleft       +writebackup
+diff            +menu            -ruby            -X11
+digraphs        +mksession       +scrollbind      -xfontset
-dnd             +modify_fname    +signs           -xim
-ebcdic          +mouse           +smartindent     -xsmp
+emacs_tags      -mouseshape      +startuptime     -xterm_clipboard
+eval            +mouse_dec       +statusline      -xterm_save
+ex_extra        +mouse_gpm       -sun_workshop    -xpm
+extra_search    -mouse_jsbterm   +syntax          


Both running in zsh in konsole on kubuntu 16.04.

**Comment by lervag** [comment]
Ok, I just tried with neovim, which reproduced the bug. I think it should be solved now. :)

**Comment by Bellaktris** [comment]
Yep, it works ). Thank you.

**Comment by lervag** [comment]
No problem! Let me know if you find more cases where the regexes might miss explicit "modes".
