### ISSUE TITLE
]] does not close \begin{document}

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#793]
Tex file:
```tex
\documentclass{article}
\begin{document}
]]
```
does not expand to
```tex
\documentclass{article}
\begin{document}
\end{document}
```
Within `\begin{document}` and `\end{document` `]]` works just fine.

```
:verbose imap ]]
i  ]]           @<Plug>(vimtex-delim-close)
        Last set from ~/.cache/vim/dein/.cache/vimrc/.dein/autoload/vimtex.vim    
```

**Comment by lervag** [comment]
Yes, it is by design. I found it inconvenient to include `\begin{document}|\end{document}` for closing delimiters, because I think it is easily closed by mistake. I might be convinced that I'm wrong, though...

**Comment by kiryph** [comment]
I see. Usually I use a snippet to setup the basic layout of a tex file which includes `\begin{document}|\end{document} `. I was testing all the completion possibilities of vimtex and entered documentclass and begin document manually. And then I encountered that `]]` does not work in this circumstance.

Since I have my `EDO` snippet based on latex-suite, I actually do not miss this. So I do not want to convince you. I was thinking that it is a minor issue. Anyhow, I close this issue. If someone else needs this he can reopen or raise a new issue.

**Comment by lervag** [comment]
Sounds good to me! :)
