### ISSUE TITLE
RFC: Vimtex completion source for neocomplete shouldn't hide others

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#795]
As far as I understand the configuration of neocomplete with
```viml
  if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
  endif
  let g:neocomplete#sources#omni#input_patterns.tex =
        \ '\v\\%('
        \ . '\a*cite\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|\a*ref%(\s*\{[^}]*|range\s*\{[^,}]*%(}\{)?)'
        \ . '|hyperref\s*\[[^]]*'
        \ . '|includegraphics\*?%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|%(include%(only)?|input)\s*\{[^}]*'
        \ . '|\a*(gls|Gls|GLS)(pl)?\a*%(\s*\[[^]]*\]){0,2}\s*\{[^}]*'
        \ . '|includepdf%(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . '|includestandalone%(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . '|usepackage%(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . '|documentclass%(\s*\[[^]]*\])?\s*\{[^}]*'
        \ . '|\a*'
\ . ')'
```
means that as soon as one of these trigger words match, I only see the omni completion source.
However, I would be interested to still see e.g. my ultisnips snippets.

I mean if I type out of habit `\frac` I won't see my `\frac` snippet which inserts the four curly braces and sets three jump locations for me. I know I can still use my mapping to expand the snippet, but the completion menu does not reflect this.

I guess there is no way except writing a dedicated neocomplete source instead of relying `g:neocomplete#sources#omni#input_patterns`.

Am I right?

**Comment by lervag** [comment]
As far as I know, yes, you are right. Perhaps it would be an idea to write a neocomplete source? I have not done that before, but I think it could be worth the effort. At least, I would be very glad to consider a PR.

If we did write a dedicated source, then it would simplify configuration for those who combine vimtex with neocomplete. That's a plus. It would also make neocomplete work better with vimtex, which is also a plus.

However, if we did implement a neocomplete source, then I think we should also implement a deoplete source. It seems this road may lead to some work with keeping "external" features up to date. I still think it is tempting, but I would be happy to get some help with this.

**Comment by kiryph** [comment]
I agree that having a dedicated source for the autocompletion plugins such as [neocomplete](https://github.com/Shougo/neocomplete.vim), [deoplete](https://github.com/Shougo/deoplete.nvim), [youcompleteme](https://github.com/Valloric/YouCompleteMe), [completor](https://github.com/maralla/completor.vim), [asyncomplete](https://github.com/prabirshrestha/asyncomplete.vim), [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager) and others would be great.

In my opinion one problem is that there are too many different plugins and each of them has its own user community.

I think the idea of the [language server protocol](http://langserver.org/) which somewhat tries to address this problem should also be taken into account. This has led to new autocompletion  plugins [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager), [nvim-langserver-shim](https://github.com/tjdevries/nvim-langserver-shim), and [vim-lsp](https://github.com/prabirshrestha/vim-lsp).

 Providing an omnifunc as it is right now is actually quite good with respect to support many different autocompletion plugins because most of them support this as a fallback.

I agree that this is a larger project and I am sorry that my time right now is too limited to make here a significant contribution. Actually, I submit too many issues for vimtex.

Possibly, a first step could be to get in contact with @poppyschmo the author of https://github.com/poppyschmo/deoplete-latex to see whether he would be interested in creating a PR which you could take as a starting point.

Besides my limited time there are two things why I am not too desparate for this feature

1. My snippets do typically not start with a backslash but are simply e.g. `frac` which means the omnicompletion is not triggered and I see the ultisnips item in the menu as long as I didn't type a backslash.
2. And as I said previously my keymapping to trigger the expansion of a snippet also still works. It just does not show up in the menu.

I close this issue since there is nothing I will do right now and the current state is not too bad for me.

**Comment by lervag** [comment]
Thanks for the thoughtful comment. I didn't know about the language server protocal, which seems interesting. I also find the nvim-completion-manager interesting.

I don't think it is a good idea to add custom sources for every single completer plugin, as it becomes too much work maintaining it. As such, I think instead that having a good omnicomplete function should be sufficient for now, and I agree with closing this.

However, if anyone, e.g. @poppyschmo, would want to submit a PR for a completion source that utilizes the vimtex completion API (in the sense we can call it an API), I would be happy to both consider it and help with making it work well, and merge it.
