### ISSUE TITLE
g:vimtex_latexmk_continuous is ignored?

### ISSUE THREAD

**Issue by dbmrq** [lervag/vimtex#796]
I have these two options in my .vimrc:

```vim
let g:vimtex_latexmk_continuous = 0
let g:vimtex_latexmk_background = 1
```

And they used to work fine. Now I updated vimtex to the latest commit and it seems like they're ignored. I tried checking out an older commit and they go back to working, so I think this is related to a recent change. Any ideas?

**Comment by lervag** [comment]
Yes, there's been a change of option names. Check the docs :)

Den tir. 18. apr. 2017, 06.30 skrev Daniel Marques <notifications@github.com

**Comment by dbmrq** [comment]
Ah, I missed that, thanks!

So now I'm setting

```vim
let g:vimtex_compiler_latexmk = {
    \ 'background' : 1,
    \ 'continuous' : 0,
\}
```

But now I get these errors when I try to compile:

```
Error detected while processing function <SNR>105_fix_paths:
line   15:
E121: Undefined variable: b:vimtex
E116: Invalid arguments for function simplify(b:vimtex.root . '/' . bufname(l:qf.bufnr)
), ':.')
E116: Invalid arguments for function fnamemodify( simplify(b:vimtex.root . '/' . bufnam
e(l:qf.bufnr)), ':.')
E15: Invalid expression: fnamemodify( simplify(b:vimtex.root . '/' . bufname(l:qf.bufnr
)), ':.')
```

**Comment by lervag** [comment]
Yes, it's a bug with neovim. There is a temporary workaround, you should
find it if you search the issues. If not, I can help you later when I'm at
the office.

Den tir. 18. apr. 2017, 07.22 skrev Daniel Marques <notifications@github.com

**Comment by dbmrq** [comment]
Weird, I'm using MacVim, not neovim. And I looked in the issues before asking and didn't find anything, but I'll keep looking then. Thanks again. :)

**Comment by dbmrq** [comment]
Ok, I found your comment about the neovim issue and added the `let g:vimtex_quickfix_latexlog = {'fix_paths':0}` option… but now I'm getting this:

```
Error detected while processing function <SNR>103_callback[1]..vimtex#compiler#callback
:
line    1:
E121: Undefined variable: b:vimtex
E116: Invalid arguments for function get(b:vimtex.compiler, 'silence_next_callback')
E15: Invalid expression: get(b:vimtex.compiler, 'silence_next_callback')   
```

Since it seems to be related to the callbacks I tried setting the `'callback' : 0` option, but it doesn't matter. Whenever you can help I'll be very grateful. And let me know if you want me to send any more information about my Vim version or something. Thanks. :)

**Comment by dbmrq** [comment]
(Weird… if I do `:call vimtex#compiler#callback(0)` I don't get those errors, but I always get them when trying to compile.)

**Comment by lervag** [comment]
Hmm, perhaps I was a little bit too quick. Which version of Vim are you using? Would it be ok to create a minimal example? You can use the template located in `VIMTEX/test/issues/template` as a starting point.

**Comment by dbmrq** [comment]
Ah! I had tried it with a minimal .vimrc when I got the first error, but I didn't try it again after the second one. I have these autocmds to open the quickfix window when running a quickfix command:

```vim
augroup autoquickfix
    autocmd!
    autocmd QuickFixCmdPost [^l]* cwindow
    autocmd QuickFixCmdPost    l* lwindow
augroup END
```

I still don't know why this causes the `Undefined variable: b:vimtex` error, but as soon as I removed the autocmds it was gone. I can live without them anyway, so it's fine. Thank you for your help. :)

**Comment by lervag** [comment]
That makes sense. The reason is that your autocommands are fired before the one from vimtex, and with `cwindow` you change the buffer. Thus the `b:vimtex` buffer variable becomes unavailable when the `fix_paths()` function is executed by the corresponding vimtex autocommand. To be clear: vimtex also uses the `QuickFixCmdPost` autocommand to fix some paths before opening the quickfix window.

**Comment by dbmrq** [comment]
Ah, of course, thanks for the explanation. Have a nice day! 🍻

**Comment by lervag** [comment]
Thanks, you too! :)
