### ISSUE TITLE
Parsing preamble for packages should consider input files

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#797]
I have moved a part of my preamble into a file `shared_preamble.tex` which I use for tikz pictures I compile separately. A MWE woud look like
`main.tex`:
```
\documentclass[]{article}
\input{shared_preamble}
% \usepackage{amssymb}

\begin{document}
vimtex should provide also completion for amssymb commands such as $\Rrightarrow$ 

\end{document}
```
`shared_preamble.tex`
```
\usepackage{amssymb}
```

I've noticed that `\li` does not list `amssymb` and also command completion does not work.

**Comment by lervag** [comment]
Thanks, this was due to a small but important bug in the tex file parser due to the new state initialization.
