### ISSUE TITLE
skim not being opened / updated anymore after successful compilation

### ISSUE THREAD

**Issue by rionda** [lervag/vimtex#800]
Skim doesn't get opened automatically after the first compilation triggered by \ll.  Opening it using \lv works, but then what is shown in Skip doesn't get updated after recompilation.

This used to work correctly until quite recently (maybe a week ago or so?)

```latex
\documentclass{article}
\author{}
\date{}
\title{}
\begin{document}
Test
\end{document}
```

.vimrc

```vim
" This is always first because we have pathogen in bundle/
runtime bundle/vim-pathogen/autoload/pathogen.vim

" This must be first, because it changes other options as side effect
set nocompatible

" Call pathogen to make it easy to install plugins under ~/.vim/bundle
call pathogen#infect()
call pathogen#helptags()

let g:vimtex_view_general_viewer = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'

" This adds a callback hook that updates Skim after compilation
let g:vimtex_latexmk_callback_hooks = ['UpdateSkim']
function! UpdateSkim(status)
        if !a:status | return | endif

        let l:out = b:vimtex.out()
        let l:tex = expand('%:p')
        let l:cmd = [g:vimtex_view_general_viewer, '-r']
        if !empty(system('pgrep Skim'))
                call extend(l:cmd, ['-g'])
        endif
        if has('nvim')
                call jobstart(l:cmd + [line('.'), l:out, l:tex])
        elseif has('job')
                call job_start(l:cmd + [line('.'), l:out, l:tex])
        else
                call system(join(l:cmd + [line('.'), shellescape(l:out), shellescape(l:tex)], ' '))
        endif
endfunction
```

**Comment by lervag** [comment]
There's been a few (major) updates. First, the `latexmk` options are moved to `g:vimtex_compiler_latexmk` (see the docs for more info). Next, I've added a viewer for `Skim` which _should_ work with no configuration: `let g:vimtex_view_method = 'skim'`.

**Comment by rionda** [comment]
@lervag as far as I can tell, the docs for vimtex_view_method do not list 'skim' as a possible value and still reports the old method.

**Comment by lervag** [comment]
Ah, sorry, that's not quite right. I've not updated the docs, it seems. I'll reopen this issue as a placeholder, but could you try to set the option regardless? I think it should work...

**Comment by rionda** [comment]
Yes, setting just `let g:vimtex_view_method = 'skim'` works. Thank you.

**Comment by lervag** [comment]
No problem! :)

I'll reopen and close this issue when I've updated the docs.

**Comment by lervag** [comment]
Just for reference: This issue is related to #769, which lead me to implement Skim as an internal viewer.
