### ISSUE TITLE
Outdated documentation for g:vimtex_compiler_method

### ISSUE THREAD

**Issue by leogama** [lervag/vimtex#802]
I think you missed these parts when you updated the documentation for `latexrun`: [here](https://github.com/lervag/vimtex/blob/4a0ee8e5da0226411f07da1938e28a68db3ccd2b/doc/vimtex.txt#L457) and [here](https://github.com/lervag/vimtex/blob/4a0ee8e5da0226411f07da1938e28a68db3ccd2b/doc/vimtex.txt#L557).

**Comment by lervag** [comment]
Thanks!
