### ISSUE TITLE
Error E194 when trying to use latexmk callbacks

### ISSUE THREAD

**Issue by haudren** [lervag/vimtex#804]
I recently updated vimtex, and saw that it now required the servername option to be set. I discovered the new "callbacks" options and thought that it would be nice to have a way to reload the error tab when recompiling with latexmk.

However, after launching vim with `vim --servername VIMTEX test.tex` and launching continuous compilation using `\ll`, I am greeted with this error:
> Error detected while processing function vimtex#compiler#compile..32..34..96..101:
line    4:
E194: No alternate file name to substitute for '#': !max_print_line=2000 latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e '$pdf_previewer = "okular --unique"' -e '$success_cmd = 
"'""'vim'""' --servername VIMTEX --remote-expr \"vimtex#compiler#callback(1)\""' -e '$failure_cmd = "'""'vim'""' --servername VIMTEX --remote-expr \"vimtex#compiler#callback(0)\""' 'test.tex' >'/tmp/v9gckWv/1' 2>
&1 &

I am trying to compile a simple Hello World,
```tex
\documentclass[a4paper]{article}

\begin{document}
Hello!
\end{document}
```

The relevant section of my vimrc (Note: VIM 7.4, default on Ubuntu 14.04, installed through gvim to get all the options enabled):
```vimscript
" Use okular for vimtex
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique @pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
let g:vimtex_complete_recursive_bib = 1
```

And my latexmkrc:
```
 # Custom dependency and function for nomencl package 
 add_cus_dep( 'nlo', 'nls', 0, 'makenlo2nls' );
 sub makenlo2nls {
 system( "makeindex -s nomencl.ist -o \"$_[0].nls\" \"$_[0].nlo\"" );
 }

 $pdflatex = 'pdflatex -shell-escape';
```

Do I need to define by myself the callback or something similar?

Sorry to bother you with those questions....

e/ After a quick investigation, it seems that you latest commit, c569d18, is to blame for this regression, as I don't have any problems with 7b7a5a5. Thanks for the great software!

**Comment by lervag** [comment]
The servername requirement is not really new, but I recently added a warning to notify users about it. The callback feature won't work without a proper servername.

And regarding the bug: I forgot to test with old Vim. The update should fix it. Thanks for noticing and reporting!

And thanks for the kind words :)
