### ISSUE TITLE
\cite and \ref completion not working

### ISSUE THREAD

**Issue by qazip** [lervag/vimtex#807]
First of, thanks for this valuable extension.

The \cite{} and \ref{} completion commands are not working. I'm using neovim. In insert mode, I get:

\cite{<F9>}

In normal mode nothing happens..

Any idea what might be causing this?

**Comment by lervag** [comment]
Did you read `:h vimtex-completion`? Why do you think anything should happen in normal mode? Did you read the issue template, which specifies how to write a good issue description with a reproducible example?

**Comment by qazip** [comment]
Hello,

Sorry, I did not see the template somehow. Sorry about that! Here it is:
```

\documentclass{beamer}

\usefonttheme{structuresmallcapsserif}
\setbeamertemplate{navigation symbols}{}
\setbeamertemplate{caption}[numbered]
\setbeamerfont{page number in head/foot}{size=\tiny}
\setbeamertemplate{footline}[frame number]

\setcounter{tocdepth}{1}
\usepackage[english]{babel}
\usepackage{indentfirst}
\usepackage{color}
\usepackage{graphicx}
\usepackage{caption}
\usepackage{textcomp}
\usepackage{gensymb}
\usepackage{amsmath}
\usepackage{bm}
\usepackage{multirow}
\usepackage{float}
\usepackage{verbatim}
\usepackage{gensymb}
\usepackage{cite}
\setbeamertemplate{bibliography item}{[\theenumiv]}
\captionsetup{font=scriptsize,labelfont=scriptsize}
\usepackage[font=scriptsize,labelfont=bf]{caption}


\title{testing}
\vspace*{+0.5cm}


\date{}


\begin{document}

\begin{frame}\frametitle{testing}

    \begin{figure}[h!]
        \centering
        \includegraphics[width=0.8\linewidth]{blabla.png}
        \caption{Blabla}
        \label{fig:blabla}
    \end{figure}

\end{frame}


\end{document}
```

blabla.png is an image. I tried CTRL+X+CTRL+O in insert mode and it doesn't work..

**Comment by lervag** [comment]
Did you use a minimal vimrc file?

Also, you have not been explicit about the steps to reproduce. Further, you are confusing me, because in the first post you talk about `\cite` and `\ref`, but now it seems you are talking about `\includegraphics`.

**Comment by lervag** [comment]
Also, I would think the following is a more minimal LaTeX example:

```tex
\documentclass{minimal}
\begin{document}

\begin{figure}[h!]
  \centering
  \includegraphics[width=0.8\linewidth]{blabla.png}
  \caption{Blabla}
  \label{fig:blabla}
\end{figure}

I want to \cite{blabla.png}, but the autocomplete doesn't seem to work.

\end{document}
```

However, I now notice you are using the `\cite` command, but you are using it wrong. In this particular case, you need `\ref`, since `\cite` is for citations. `\ref` is for referencing labelled parts (i.e. `\label`s). Also, `\ref` completion only works when the document has been compiled.

**Comment by qazip** [comment]
Hello,
Sorry! I was using cite when I should've been using ref.. I am such an idiot. Sorry for the trouble and thank you very much for your help.

**Comment by lervag** [comment]
No problem. :)

**Comment by mbsariyildiz** [comment]
Hello!

Thank you for maintaining this plugin.

I followed the steps to install the plugin. Auto-complete seems to be working for built-in macros and snippets, except `\cite`. Simply put, it does not auto-complete. I can verify this with a minimal .vimrc and a minimal example:
```latex
\documentclass{minimal}
\begin{document}

\begin{figure}[h!]
  \centering
  \includegraphics[width=0.8\linewidth]{blabla.png}
  \caption{Blabla}
  \label{fig:blabla}
\end{figure}

It does \ref{fig:blabla}, but the autocomplete doesn't seem to work for \cite{some_ref}.
\end{document}
```
Folder hierarchy is as follows:
```
my_folder:
---- minimal.tex
---- blabla.png
---- my_bib.bib
```

Could you please tell me what I can do to figure out the issue here?

Many thanks

**Comment by lervag** [comment]
Hi. Your minimal example does not work. This is easy to see if you just compile it. It will _not_ show the reference that you add with `\cite{some_ref}`. For this to work, you need to use either `natbib` or `biblatex` and include the reference file somehow. It should be straightforward and easy to figure out how to do this correctly. If you need more help, please open a new issue.
