### ISSUE TITLE
Restore cursor position if vimtex-toc set to 'full'

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#809]
I have set `let g:vimtex_index_split_pos = 'full'`.

When I open the first time the toc, the cursor is in the first line. When I move to a section, I would like to jump to, I reposition the cursor to the corresponding line and press `<CR>`.

### Current behavior
When I return to the toc, the cursor is again in line 1 of vimtex-toc

### Option 1
I would prefer if the cursor would be in the same line as I have left.

### Option 2
Another possibility would be: If you open the toc, the current cursor position in the tex file is checked and the current section or file determines the position in the vimtex toc. For example, if you move the cursor within the tex file to the second section and now open the vimtex toc, the cursor is placed in the line corresponding to the second section regardless where you left the toc. Maybe this requires something like ctags.

**Comment by kiryph** [comment]
Sorry, I think I was mistaken. With the newest version it actually does what I had in mind.

**Comment by lervag** [comment]
No problem. :)
