### ISSUE TITLE
ToC: +/- raise E716: Key not present in Dictionary: in-/decrease_depth

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#810]
### Explain the issue

1. Open vimtex-toc with `\lt`
2. Press `+` or `-`
3. Error appears: `E716: Key not present in Dictionary: in-/decrease_depth`

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}
\section{hello}
\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_index_show_help = 0
let g:vimtex_index_split_pos = 'full'
let g:vimtex_toc_refresh_always = 0
let g:vimtex_toc_secnumdepth = 1
let g:vimtex_labels_refresh_always = 0
```

vimtex version: c0ab7993d8f2403db6946570b5797e20180fb5e6 (Fri Apr 28 15:35:52 2017 +0200)

**Comment by kiryph** [comment]
The fix should be simple:
```diff
❯ git diff
diff --git a/autoload/vimtex/toc.vim b/autoload/vimtex/toc.vim
index 7a2ed25..ff61189 100644
--- a/autoload/vimtex/toc.vim
+++ b/autoload/vimtex/toc.vim
@@ -402,8 +402,8 @@ function! s:toc.hook_init_post() abort dict " {{{1

   nnoremap <buffer> <silent> s :call b:index.toggle_numbers()<cr>
   nnoremap <buffer> <silent> u :call b:index.update(1)<cr>
-  nnoremap <buffer> <silent> - :call b:index.decrease_depth()<cr>
-  nnoremap <buffer> <silent> + :call b:index.increase_depth()<cr>
+  nnoremap <buffer> <silent> - :call b:index.secnumdepth_decrease()<cr>
+  nnoremap <buffer> <silent> + :call b:index.secnumdepth_increase()<cr>
```
Just to make sure. This setting is only there to match the vimtex-toc counting to the latex setting `\setcounter{secnumdepth}{3}`

```
*g:vimtex_toc_secnumdepth*
  Define the number of section levels to display.  Set level corresponding to
  the desired latex variable `secnumdepth`.  For more info on `secnumdepth`,
  see http://en.wikibooks.org/w/index.php?title=LaTeX/Document_Structure.

  Note: The variable may be updated inside the ToC window with the mappings
        `+` and `-`.

  Default value: 3
```

I feel the wording could be a little bit more precise: `Define the number of section levels with section numbering.` This description sounds more like what `tocdepth` is for.

However, I am not sure about the expected behaviour of `-` and `+`. I think I would expect that they resemble the behavior of `tocdepth` which also adds/removes the lines from the toc. This feels more like someone would like to have mappings readily available such as `-` and `+`. So she or he can easily reveal temporarily also paragraphs and subparagraphs in the toc.

The variable `secnumdepth` feels more static and should be changed only if you change it in your latex document. This does not happen very often. I would even think about detecting this automatically when parsing the preamble to adjust the vimtex-toc to the latex toc automatically.

What do you think about this?

**Comment by lervag** [comment]
I've fixed the error.

Actually, the feature is more simple than what you've assumed. It only increases/decreases the area of the section numbers. You'll understand when you try it.

I think an important remark is that the vimtex ToC is there primarily as a means of navigation. I don't think it is crucial that it perfectly resembles the actual document ToC.

**Comment by lervag** [comment]
However, I might agree that the option should rather be called `_tocdepth`. Do you think it should also filter out everything "out of depth"?

**Comment by lervag** [comment]
I think your explanatin of tocdepth seems like it is more useful than the old version of this (that I called secnumdepth). As mentioned in the commit comment, I will add the filter.

**Comment by kiryph** [comment]
Since you already have added folding for toc, using `+`/`-` to adjust tocdepth to change the visibility of entries feels like re-implementing the folding functionality. 
`tocdepth` could be set to  the maximum (ie. include also subparagraph) and the user can set foldlevelstart for vimtex-toc to match the value of the latex document or another value to his liking. If he one wants to adjust the visibility of entries, the builtin mappings `zr`/`zm` can be used.

Therefore, I am not sure whether my question

> What do you think about changing - and + to in-/decrease vimtex_toc_tocdepth?

is actually a good idea. Of course, this would work independently of folding, however, sticking to the vim way feels better and the current behaviour, even though I am not using it, would be a separate functionality.

Additionaly, `-` shadows the vinegar mapping to enter the netrw file browser. If I have opened the vimtex-toc and do not see the entry I want to jump, I could be interested in opening the netrw-browser for the current working directory.

**Comment by lervag** [comment]
I agree, it seems better (and easier) to use folds. This already works well, I think. As such, I am not quite sure what needs to be implemented.

Based on your comment, I think I could add a new option (although I am not sure if anyone would actually use it?): `g:vimtex_toc_foldlevelstart` that sets the initial fold level. I don't think this needs any magic, since if you want to show everything you could simply set it to a large value.

**Comment by kiryph** [comment]
How much work do you think adding `g:vimtex_toc_foldlevelstart` without any magic would be?.

Before I started this issue, I didn't use folding in the toc. Now I am testing it if it is useful. Also I have modified some default fold mappings to my liking (https://github.com/arecarn/vim-fold-cycle/issues/6).

I would like to set g:vimtex_toc_foldlevelstart to the default of the latex variable of tocdepth, so I can set g:vimtex_toc_fold_levels to a high value, so I can also reveal paragraphs and subparagphs if I want to.

**Comment by lervag** [comment]
Let me know what you think about this.

**Comment by kiryph** [comment]
### `foldlevel` a local to window variable

I miss that the variable `foldlevel` changed by zm/zr of the vimtex-toc window is lost when I close the toc window e.g. when using `let g:vimtex_index_split_pos = 'full'`.

It looks like that this is not surprising: vim help says that `foldlevel` is a `local to window` variable. I guess when I close the toc the value is gone.

I would prefer if `foldlevel` would be a `local to buffer` variable since the vimtex-toc buffer is not removed from memory.

IMHO `foldlevelstart` or `g:vimtex_toc_foldlevelstart` should only apply when I open the vimtex-toc the first time of a certain tex document in my current vim session.

So, adding something like `b:vimtex_toc_foldlevel` could help me out here. This value should be updated when vimtex-toc window is exited.

### Notes about the doc

I would rename `g:vimtex_toc_fold_levels` to `g:vimtex_toc_fold_depth` to avoid confusion with the meaning of `foldlevel`.

I am wondering whether a user needs so much granularity w.r.t. folding: he can already decide how deep the toc goes (`g:vimtex_toc_tocdepth`); is it necessary to have a variable for folding depth?

I think vim folding commands offer many options: For example `zO` can already open current and nested folds which means: if he opens a chapter entry he can reveal immediately section, subsection of this chapter.

And finally, I mentioned this earlier but I am not happy with following text:

```
 *g:vimtex_toc_tocdepth*
   Define the number of section levels with section numbering. [...]
```
I think this describes `secnumdepth` and the description for tocdepth should be
```
 *g:vimtex_toc_tocdepth*
   Define the number of section levels to display.  [...]
```

**Comment by kiryph** [comment]
I just noticed that `+`/`-` adjust *g:vimtex_toc_number_width* instead of the toc depth. I guess the doc has to be updated for the meaning of `+`/`-`.

**Comment by kiryph** [comment]
I missed to add that I am happy with g:vimtex_toc_foldlevelstart and restoring the foldlevel when reopening is only a minor issue, i.e. adding `b:vimtex_toc_foldlevel`, updating and restoring is not so important for me.

I do not mind if you consider this issue as finished.

**Comment by lervag** [comment]
Actually, I think the `g:vimtex_toc_number_width` should be removed. It does not do anything necessary that is not handled as well/better by the tocdepth option.

-----

I've made the fold level persistent in the latest version. I agree that it makes sense, and it was not a very difficult thing to do.

----

I've also updated docs, removed uneccesary options and similar. I think all of these minor updates are nice refinements. Thanks for your input and suggestions!

**Comment by LindyBalboa** [comment]
Hi, I understood from this thread that +/- is now supposed to adjust the depth? However, my experience shows it to only be adjusting the depth numbers, not the actual depth. Additionally, my TOC is does not show paragraphs or subparagraphs. I figured this would be possible with setting the depth to 4 or 5 respectively. 

Would you mind clarifying these points? Thanks.

**Comment by lervag** [comment]
Please open a new issue with a full description. And I'd appreciate if you refer to the documentation instead of this thread for the documentation of how `+/-` is supposed to work. The relevant part is `:h g:vimtex_toc_tocdepth`.
