### ISSUE TITLE
ToC: Add option for custom section environments

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#812]
I have added to my document a so-called [`halftitlepage`](https://en.wikipedia.org/wiki/Half_title).

Originally, I had just used a second titlepage environment. However, the toc of vimtex lists then two titlepages and I cannot distinguish them there.

That's the reason I added a new environment `halftitlepage` which is a synonymous environment to `titlepage`:
```tex
\newenvironment{haltitlepage}{\begin{titlepage}}{%
    \end{titlepage}\ignorespacesafterend%
}
```
I have modified `autoload/vimtex/toc.vim` to recognize this:
```diff
git diff
diff --git a/autoload/vimtex/toc.vim b/autoload/vimtex/toc.vim
index 7a2ed25..f8ef147 100644
--- a/autoload/vimtex/toc.vim
+++ b/autoload/vimtex/toc.vim
@@ -581,6 +581,10 @@ let s:re_other = {
       \   'title' : 'Titlepage',
       \   're'    : '\v^\s*\\begin\{titlepage\}',
       \   },
+      \ 'halftitlepage' : {
+      \   'title' : 'Halftitlepage',
+      \   're'    : '\v^\s*\\begin\{halftitlepage\}',
+      \   },
       \ 'bib' : {
       \   'title' : 'Bibliography',
       \   're'    : '\v^\s*\\%('
```
Now the vimtex toc looks like:
```
      Preamble                                                                                                                                    0
      Halftitlepage                                                                                                                               0
      Titlepage                                                                                                                                   0
1     First part                                                                                                                                  0
1.1   Hello                                                                                                                                       1
1.2   World                                                                                                                                       1
2     Second part                                                                                                                                 0
2.1   Hello                                                                                                                                       1
2.2   Mars                                                                                                                                        1
```
Does this convince you to add a new option which allows to add custom environments which are recognized as section environments (or another way to achive this)?

**Comment by lervag** [comment]
Ok, I've done a pretty large refactoring to allow adding custom TOC matchers. I've added an option `g:vimtex_toc_custom_matchers`, which is a list of matchers (default empty). A matcher is a dictionary that can have several keys. The simplest version is the one you've already suggested for the `halftitleplage`, and so adding that to the option should give you the desired feature.

I'll add docs later. Also, I'm not surprised if there will be a couple of issues after this, but I think the restructuring was good.

**Comment by kiryph** [comment]
A big thanks to you again for this refactoring.

On my side, everything looks good except opening the toc from my bib file. I get following error:
```
E117: Unknown function: vimtex#toc#open
```

---

I have another application of this feature in mind: beamer frames
```tex
\documentclass{beamer}
\usetheme{Berlin}
\title{Example Presentation Created with the Beamer Package}
\date{\today}

\begin{document}

\begin{frame}
  \titlepage
\end{frame}

\section*{Outline}
\begin{frame}
  \tableofcontents
\end{frame}
\section{Introduction}
\begin{frame}
  \frametitle{What Are Prime Numbers?}
  A prime number is a number that has exactly two divisors.
\end{frame}

\begin{frame}{A title}
  Some content.
\end{frame}
\subsection{Overview of the Beamer Class}
\begin{frame}<beamer>{Outline}  % frame is only shown in beamer mode
      \tabelofcontent[current]
\end{frame}

\end{document}
```

The toc looks like
```
          Preamble                                                                                                                                    0
          Outline                                                                                                                                     0
          Table of contents                                                                                                                           0
2         Introduction                                                                                                                                0
2.1       Overview of the Beamer Class                                                                                                                1
```

But in my opinion could show also the frames

```
          Preamble                                                                                                                                    0
[f]       Titlepage
          Outline                                                                                                                                     0
[f]       Table of contents                                                                                                                        0
2         Introduction
[f]       What Are Prime Numbers?                                                                                                    0
[f]       A title
2.1       Overview of the Beamer Class                                                                                                                1
```

**Comment by lervag** [comment]
Ok, I've refactored some more and cleaned up the code, as well as provided some documentation. Confer the `autoload/vimtex/toc/matchers.vim` for examples if you want to add the frame matcher. I think it should be rather straightforward.

Don't hesitate to suggest improvements to the docs. Note, though, that I feel it is already slightly "too much", and so I hesitate to add more text.

**Comment by kiryph** [comment]
Ok, that looks very configurable. I guess this is actually necessary to support something like the beamer frame syntax. 

When I create my next beamer presentation, I will try to create a pull request to support beamer frames. I guess the builtin matcher `g:vimtex#toc#matchers#sections` can be used as a starting point. I think this is useful but also complicated enough that no one will do this but only use it if it is supported right away. Someone has asked the question how to include beamer frames to the latex toc. I add this link to indicate that this is nothing as obscure as my halftitlepage environment :-) https://tex.stackexchange.com/questions/17230/beamer-how-to-make-each-frame-appear-in-the-pdf-toc


### Docs
It looks like the doc could be further extended to describe the fields number, level, file, line and support functions `s:find_closing` and `s:clear_texorpdfstring`. I understand you when you say that you hesitate to add more text. Documenting the source code of the built-in toc matcher could be an alternative to avoid blowing up the documentation for a feature which almost no one will use.

IMHO the halftitlepage example in the doc is not the best example. I think this could be replaced with `abstract`. Many documentclasses have this environment (`article`, `scrartcl`, `elsarticle`, `revtex4-1`, ...). On the other hand you could support the abstract environment out of the box. I have to think about a non-standard environment which is not too obscure.

I have one question:
Can the script-local function `s:find_closing` be used in my vimrc?

**Comment by lervag** [comment]
Firstt, regarding beamer frames: Thanks! I will definately want to merge a PR for this when it is ready. Note, though, that it is not very straighforward if we want to make it "general" and support e.g. `\frametitle`. I think we need something like this for the part that searches the title:

1. First check if the title is provided as argument to `\begin{frame}...`.
2. If not, then we need to use the `continue` method to search for `\frametitle` until the next `\end{frame}`.
3. If we reach `\endframe`, then there was no title.

Note that the continued search will block any other entries in between from being parsed. Although, you could use readfile to read the current file from the current line number and some lines ahead to avoid the continue statement. I think it should be relatively safe to assume that the `\frametitle` appears in one of the first lines in the frame.

----

Thanks for the comments to the docs. I've updated somewhat to acommodate some of your points.

I'm sorry, but `s:find_closing` is not available outside the script. Perhaps this is useful enough to be upgraded to a `vimtex#util#find_closing` function, or similar? That way it would be available in your vimrc file.
