### ISSUE TITLE
Window not raised using '\lv' forward search using mupdf

### ISSUE THREAD

**Issue by sidzwans** [lervag/vimtex#814]
Hi,

I am using Arch Linux, using cinnamon desktop environment, and mupdf as viewer.

During forward search using forward search '\lv', the window is focused but not raised.
I believe this behaviour may depend on window manager, as for my case, I am using cinnamon.

Currently vimtex is using 'windowfocus' xdotool function. However, could we consider adding the implementation of  'windowactivate' function? The window is able to be raised when I use the 'windowactive' function instead. Anyway, this function is recommended in the xdotool doc as it works on more window managers.
 
My config are as below.

Thanks & Regards.

LaTeX file.

```tex
\documentclass{article}
\begin{document}
A new file.
\end{document}
```
Minimal vimrc

```vim
set nocompatible
filetype plugin indent on
syntax enable
set iskeyword+=:
set hidden

call plug#begin('~/.vim/bundle')
Plug 'https://github.com/lervag/vimtex.git', {'for': 'tex'}
call plug#end()

let g:vimtex_view_method ='mupdf'

```
latexmkrc

```latexmkrc
# Set pdf viewer as in 'start VIEWER'
$pdf_previewer = 'start mupdf';

# If zero, check for a previously running previewer on the same file and update it.  If nonzero, always start a new previewer.
$new_viewer_always = 0;

# How to make the PDF viewer update its display when the PDF file changes.  See the man page for a description of each method.
$pdf_update_method = 2;

# When PDF update method 2 is used, the number of the Unix signal to send
$pdf_update_signal = 'SIGHUP';
```

**Comment by lervag** [comment]
Do I understand correctly that you suggest changing the occurence of `windowfocus` to `windowactivate`? It seems from the xdotool manual that you are right in that this is sort of recommended. I'll make the change, as it seems safe. But if it breaks anything for anyone, we'll have to discuss if it should instead be optional.

**Comment by sidzwans** [comment]
Yes. That's what I would like like to suggest. By either substituting the function, or have it as an option.

Thanks & Regards.
