### ISSUE TITLE
Option to disable forward search

### ISSUE THREAD

**Issue by daturkel** [lervag/vimtex#815]
### Explain the issue

I quite like vimtex, and I'm using it with Skim as my viewer. However, I don't happen to like forward search and would like to disable it. I have looked extensively through the documentation but can't seem to find an option to disable this. Am I missing something, or is there no way to currently toggle this?

**Comment by lervag** [comment]
Interesting question. I think the easiest way would be to use the general view method for Skim to achieve that. I'm not using OSX myself, so it's always a bit difficult to answer such questions. However, I think a good starting point is the old way of customizing the general viewer for Skim:

```vim
let g:vimtex_view_general_viewer
      \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
let g:vimtex_view_general_options = '-r @line @pdf @tex'

" This adds a callback hook that updates Skim after compilation
let g:vimtex_compiler_callback_hooks = ['UpdateSkim']
function! UpdateSkim(status)
  if !a:status | return | endif

  let l:out = b:vimtex.out()
  let l:tex = expand('%:p')
  let l:cmd = [g:vimtex_view_general_viewer, '-r']
  if !empty(system('pgrep Skim'))
    call extend(l:cmd, ['-g'])
  endif
  if has('nvim')
    call jobstart(l:cmd + [line('.'), l:out, l:tex])
  elseif has('job')
    call job_start(l:cmd + [line('.'), l:out, l:tex])
  else
    call system(join(l:cmd + [line('.'), shellescape(l:out), shellescape(l:tex)], ' '))
  endif
endfunction
```

The new `skim` view method basically wraps the above customization for you, and it seems to me to be a good default setup. I don't like adding to many options, so I'd prefer to avoid that.

**Comment by lervag** [comment]
[This reference](https://atom.io/packages/skim-displayline) is probably also useful for understanding the options to the `displayline` tool. However, I think perhaps `displayline` is the tool you use exactly for forward searching. Thus you might want to find how to use Skim on the command line.

**Comment by daturkel** [comment]
I suppose the behavior I really want is for the compile command to **just** compile to a PDF, and not trigger a callback to the skim function (skim can automatically update when the file changes), and for the view command to simply open the file in Skim with a bash script, rather than using `displayline`.

**Comment by lervag** [comment]
In that case, you should try simply:

```vim
let g:vimtex_view_general_viewer
      \ = '/Applications/Skim.app/Contents/MacOS/Skim'
```

You could also use a personal bash script or whatever that takes the pdf file path as an argument. See `:h g:vimtex_view_general_viewer` and the surrounding parts.

**Comment by daturkel** [comment]
setting `vimtex_view_general_viewer` to `'[...]/MacOS/Skim'` has the odd effect of opening a new instance of Skim (as in there are multiple Skims in my dock, each with the file open) each time i use the command. Any clue how I can avoid this?

**Comment by lervag** [comment]
I'm happy you figured this out. As I don't work on OSX it would be difficult for me to find the right solution. In any case, don't hesitate to let me know if you have more questions/issues!
