### ISSUE TITLE
Command completion appends } if g:vimtex_complete_close_braces = 1

### ISSUE THREAD

**Issue by matthewjohnrussell** [lervag/vimtex#817]
If `g:vimtex_complete_close_braces` is set to 1 then command completion adds a spurious closing brace.

Example: typing `\lab<C-X><C-O>` yields `\label}`, whereas it should yield `\label`.

With the default value for `g:vimtex_complete_close_braces` (0) no brace is appended, as expected.

**Comment by lervag** [comment]
Should be fixed now.
