### ISSUE TITLE
Do we need `<= for \leq and most importantly it makes `< wait

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#818]
Vimtex-imaps should be fast. However, `` `<`` has to wait until timeout (`timeoutlen` 1000ms or `ttimeoutlen` which is set in `defaults.vim` to 100ms).

Therefore, I have added to my vimrc
```viml
let g:vimtex_imaps_disabled = ['<=', '>=']
```

Also note `` `<`` (expands to`\langle`) and `` `<=`` (expands to `\leq`) are semantically different.

My proposal would be to remove`'<=', '>='`.

For comparison

- latex-suite plugin and auctex.vim have no `` `<=`` and `` `>=`` only
```
    `<   expands to   \le
    `>   expands to   \ge
```

- emacs auctex (https://ftp.gnu.org/gnu/auctex/11.88-extra/tex-ref.pdf)
`<>` expands to `\leq` and `\geq` and `()` to `\langle` and `\rangle`. also no mappings with `<=` and `>=`

**Comment by lervag** [comment]
Sounds reasonable. I think I like auctexs mappings, because it makes sense to shorten the longest alternatives.

**Comment by lervag** [comment]
Fixed now, let me know what you think.

**Comment by kiryph** [comment]
Thanks, for your response.

First of all, my intention was not to suggest a change of the existing `` `<``. I just wanted to point out when the imap list contains single and double letter imaps with the same first letter, the single letter imap is slow to type. Perhaps this depends on the settings of timeoutlen and ttimeoutlen. What are your settings of timeoutlen and ttimeoutlen?

I have missed to point out that also `` `q`` is affected by this. So I would be interested to see there also a change.  Do you actually use `` `q` `` for `\theta` or only the two letter imaps starting with `q`?

In fact, I was not unhappy with `` `<`` expanding to `\langle` because this saves the most number of keystrokes. When touch typing `\leq` and `` `<`` on an Ansi US keyboard layout, I have to use the pinky finger for both, but also to hold shift for `<`. This means I have to press three keys to enter either of them. 
On the other hand touch typing `\langle` is not that bad: `l`,`a`,`g`,`l` are on the homerow and `n`,`e` are pressed by strong fingers. The only weak finger involved is the right pinky finger for `\`. In case of the imaps the left pinky finger has to be used instead, ie. no difference between them w.r.t. pinky finger action.

What is your rule of thumb how to choose the default imaps for vimtex?

For example
- having good mnemonics (e.g. `` `<`` is the extended version of `<`)
- being close to other plugins for people who switch to vimtex
- offering short mappings to speed up typing in particular for those which are more 'difficult' to type (either a lot of keystrokes or involve a lot of pinky finger action)

I would put emphasize on the last item.

**Comment by lervag** [comment]
I don't really use the imaps that much, so my rule of thumb is to satisfy users as best as possible. But I think your example list is pretty accurate on what i think are good rules.

Before I update again let's first agree on how things should be. Regarding `` `<  `> ``, do you propose to change these back to the prevous `\langle` and `\rangle`, or are you happy with the updated version?

Regarding `` `q ``, as I said, I don't really use these that much, so I won't mind changing this. Do you have a proposal for how to solve this? One possibility is to change the mappings that start with `q` to start with a different letter. I think `q` is used by other systems for theta, but I am not sure. Else we should find a different letter for theta?

**Comment by kiryph** [comment]
Satisfying the user is quite a challenging task 🔁  😃 . 

I am used to the old mapping, i.e. `` `<`` expands to `\langle` and therefore I would simply define them in my vimrc if they are now defined differently in vimtex.

In general, I would try to follow [Emacs Auctex](https://ftp.gnu.org/gnu/auctex/11.90-extra/tex-ref.pdf) and [vim-latex](https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/mathmacros-utf.vim) because these plugins exist for a longer period of time and should have established mappings which most user agree on. I agree that this is only an assumption. One could say people simply learned them the way they are given.

For comparison:

| latex command | [Emacs Auctex](https://ftp.gnu.org/gnu/auctex/11.90-extra/tex-ref.pdf) | [vim-latex](https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/mathmacros-utf.vim) | [auctex.vim](http://web.math.rochester.edu/people/faculty/cmlr/Latex/auctex-vim-keybindings) | [vimtex](https://github.com/lervag/vimtex/blob/master/autoload/vimtex.vim) |
|---------------|--------------|-----------|------------|--------|
|  `\langle`   | `( | none | none | none |
| `\leq` | `< | none | `< | `< |
| `\theta`              | `j             | `q          |  `q          | `q       |
| `\leftarrow` | `Ctrl-b | none | none | `qh

Obviously they are not consistent anyway.

Using `` `j`` for theta to free `` `q`` does not feel intuitive. Using ctrl+hjkl or HJKL for the arrows is probably not possible with vimtex, even though it would be quite easily to remember.

### Random Notes on this Issue

Most likely, no one has done a comprehensive analysis on zen-style coding for latex (similar to https://emmet.io/ for html/css). It also simply depends on the field you are working in. This affects  which ones you use quite often and also your keyboard layout could affect what you feel is convenient.

Nevertheless having a basic set people are familar with is certainly useful (in particular for greek letters and standard calculus).
The mentioned latex plugins already share quite a significant amount of mappings (with slight differences in the version of the greek letters)

| latex command | imap |
|---------------|--------------|
| `\alpha` `\beta` ... | `` `a`` `` `b`` ... |
| `\times`        | `*           |
| `\equiv` | `= |
| `\emptyset` | `0 |
| `\partial` | `6 |
| `\infty` | `8
| `\nabla` | `N
| `\cdot` | `. |
| `\forall` | `A |
| `\exists` | `E |


and more

Right now, I am also trying out the plugin https://github.com/brennier/quicktex for fast typing of latex math. My first experience is that it is quite good at this. It does not use any leader key it just replaces `alpha` with `\alpha` in math mode. Even though I am not really happy with the suggested remapping of double spaces for placeholder jumping.

**Comment by lervag** [comment]
Thanks for your comprehensive comment. There is only one thing, though: I still don't really know what is the most appropriate solution here. No one has reacted on the recent change of the default imaps, and since you say you would add new maps to revert the recent change, I think this argues that we revert `` `< `` and `` `> `` back to `\langle` and `\rangle`. This means there is no default for `\geq` and `\leq`, but these are already very short and so I think we can live with that.

Now, for the `` `q[jJkKlLhH] `` maps, I've decided to change them to `` `j[...] ``, because `j` is "free". `o` is also free, but I find `j` easier to type for these maps.

With that, I think there should be no more "collisions", and as far as I know all users are satisfied :)

**Comment by kiryph** [comment]
All users are satisfied :-). I also like j for the arrows. Thanks!

**Comment by lervag** [comment]
Your welcome. :)
