### ISSUE TITLE
ignore undefined references

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#819]
I am not sure whether this is already possible. Since I did not find anything about it, I would like to suggest a feature that allows to turn off warnings about undefined references such as the following:

> foo.tex|12 warning| LaTeX Warning: Hyper reference `reference' on page 7 undefined on input line 385.
>   2 foo.tex|| LaTeX Warning: There were undefined references.

Maybe this could also be controlled using `g:vimtex_quickfix_latexlog`.

**Comment by lervag** [comment]
I think my patch should work, please test. You should set

```vim
let g:vimtex_quickfix_latexlog = {
  \ ...
  \ 'references' : 0,
  \ ...
  \}
```
