### ISSUE TITLE
Support for ConTeXt 

### ISSUE THREAD

**Issue by IbnSaeed** [lervag/vimtex#821]
Can you support  [ConTeXt](http://wiki.contextgarden.net/What_is_ConTeXt)

ConTeXt document processing system which is a TeX macro package created and maintained by Pragma ADE. 

ConTeXt supports TeX engines such as pdfTeX, XeTeX, and LuaTeX without changing the user interface.

**Comment by lervag** [comment]
Can you be more precise? What would supporting ConTeXt mean? What is _not_ supported at the moment?

**Comment by IbnSaeed** [comment]
Does vimtex support autocompletion of ConTeXt commands ?

Can it compile a context document ?

**Comment by lervag** [comment]
Do you expect me to investigate and read up on all things ConTeXt? Please, if you could provide explicit details about what you find missing, it would be much eaiser for me to know if it is enough to customize options, or if we need a new feature.

What is the difference between compiling with ConTeXt compared to pdflatex?

Can you provide a minimal example of a ConTeXt document and what you think should be completed?

**Comment by lervag** [comment]
I've looked into this some more now, and my immediate thought is that ConTeXt support seems like a lot of work. A lot of the "main" macros are different (e.g. `\documentclass`), which means I need to update much of the initialization code. I would also need to add a context compiler layer, a context quickfix layer, and as you ask for, context command completion.

Considering that I don't use context myself, I will have to decline this. I don't have the time. If someone wants to implement this, though, I'll be happy to help. with reviewing pull requests.

Note, there already exists some Vim filetype plugin for context, see [here](http://wiki.contextgarden.net/Vim).
