### ISSUE TITLE
Delete does not work as expected in visual mode with IJKL navigation

### ISSUE THREAD

**Issue by kylebarbour** [lervag/vimtex#825]
Without `vimtex`, selecting text and then using the `d` command deletes the selected text. For example, with the document

```latex
\begin{document}
    \begin{itemize}
        \item One.
        \item Two.
        \item Three.
    \end{itemize}
\end{document}
```
selecting the text from `\begin{itemize}` to `\end{itemize}` and then pressing `d` will remove all of the items from the text.

If you have mapped your navigation keys to IJKL navigation (instead of vim's native HJKL, see [vim's guide](http://vim.wikia.com/wiki/Use_ijkl_to_move_the_cursor_and_h_to_insert)), and if you use plugin indentation, this no longer is the case. With `vimtex` enabled, selecting this region from the top (at `\begin{itemize}`) then pressing `d` produces the expected result. However, selecting this region from the _bottom_ (at `\end{itemize}`) does not delete the region, but leaves the region highlighted with the cursor now immediately before the closing bracket of `\end{itemize}`. The behavior expected is that the region would be deleted, just as if it had been selected from the top.

I've tried my best to understand why this might be the case, but it seems to be over my head.

A minimal .vimrc is as follows:

```vim
call pathogen#infect()
filetype plugin indent on
map h <insert>
map i <Up>
map j <Left>
map k <Down>
```

**Comment by lervag** [comment]
I don't quite understand. Can you be explicit about what you mean with _select_? Are you using the mouse? Are you using visual mode, or select mode? The point is, I can't reproduce this with Vim or neovim.

**Comment by kylebarbour** [comment]
Sure! I should have been more specific - I get this behavior on vim using the visual line (V) mode. I don't have any issues with mouse selection or with regular character-wise visual (v) mode.

**Comment by lervag** [comment]
Ok, but I still can't reproduce. Could you please be _very_ specific on how to force this error? E.g., I want the steps as verbose as this, which is what I just tried:

1. Open Vim with command: `vim -u minivimrc my_file.tex`
2. Navigate to `\end{itemize}`
3. Enter visual line mode with `V`
4. Do `iiii` (with your mappings) to select up until `\begin{itemize}`
5. Do `d` to delete text
6. Observed result: The text is deleted.

**Comment by kylebarbour** [comment]
Sure! Sorry for not being specific enough. Here are the steps I took:

1. Create .vimrc with the following content:
```vim
call pathogen#infect()
filetype plugin indent on
map h <insert>
map i <Up>
map j <Left>
map k <Down>
```
2. Create a file `mwe.tex` with the following content:
```latex
\begin{document}
    \begin{itemize}
        \item One.
        \item Two.
        \item Three.
    \end{itemize}
\end{document}
```
3. Open that file with vim: `$ vim mwe.tex`
4. Navigate to the first character (i.e. the first blank space on the line) of line 6 (with `\end{itemize}`): `5k`
5. Enter visual line mode: `V`
6. Navigate to the first character (i.e. the first black space on the line) of line 2 (with `\begin{itemize}`): `4i`
7. Attempt to delete those lines: `d`
8. Observed result: the lines are not deleted, and the cursor winds up on the last `e` in `\end{itemize}`, that is, here:
```
    \end{itemize}
               ^
```

In an attempt to figure out what's going on, I've tried a bunch of variations on this, and found that I can reliably reproduce those results only when entering the commands at my regular typing speed. If I instead wait a second between each command (in other words, open the file, press `5kV4i`, then pause for a second or two, then press `d`), the lines are reliably deleted. If I disable vimtex by removing the call to pathogen in my .vimrc, or if I remove `filetype plugin indent on`, no matter how fast I type those commands the lines are deleted.

**Comment by kylebarbour** [comment]
I'm thinking maybe this is an issue around timeout for conflicting commands? I'm not sure why that would cause the `d` to get misinterpreted though. Some supporting evidence for that is that setting `timeoutlen=0` eliminates this problem, although it then breaks all my other mappings.

Looking at `:xmap i` to see what might be conflicting, I see

```vim
x  iP           @<Plug>(vimtex-iP)
x  i$           @<Plug>(vimtex-i$)
x  ie           @<Plug>(vimtex-ie)
x  id           @<Plug>(vimtex-id)
x  ic           @<Plug>(vimtex-ic)
   i             <Up>
```

So I think what's happening is that during the timeout period, it's sending me to the end of the delimiter object (`id`) when I'm attempting to delete the section. It would also explain why it doesn't happen from the top: there's no other mapping after `k`.

Not super sure what the solution to this is while preserving IJKL navigation &mdash; any thoughts?

**Comment by lervag** [comment]
Yes, I see now. The reason is that your `i` mapping interfers with the standard text object mappings. My suggestion is that you ditch your IJKL navigation, because text objects are _much_ more important than moving the single letter movement keys (IMHO; or perhaps not even so humble)!

However, if you refuse this, you can remap the conflicting mappings. The best way to do that is to add a filetype plugin, e.g. in `.vim/ftplugin/tex.vim` with the following content:

```vim
xmap <silent><buffer> ic <plug>(vimtex-ic)
omap <silent><buffer> ic <plug>(vimtex-ic)
xmap <silent><buffer> id <plug>(vimtex-id)
omap <silent><buffer> id <plug>(vimtex-id)
xmap <silent><buffer> ie <plug>(vimtex-ie)
omap <silent><buffer> ie <plug>(vimtex-ie)
xmap <silent><buffer> i$ <plug>(vimtex-i$)
omap <silent><buffer> i$ <plug>(vimtex-i$)
xmap <silent><buffer> iP <plug>(vimtex-iP)
omap <silent><buffer> iP <plug>(vimtex-iP)
```

Obviously, you should change the mappings to your desired keys. As long as the file is loaded before vimtex, this will prevent vimtex from defining the mappings.

----

Note, again: I strongly recommend that you read about text objects, e.g. from `:h text-objects`, and learn to use them. They are _very_ powerful and I would say one of the crucial features of Vim that everyone should learn. And remapping `i` is therefore a bad idea, since text objects rely on mappings of the type `ix` and `ax`, where `x` is a type, e.g. `w` for word, `s` for sentence`, etc.

**Comment by kylebarbour** [comment]
OK, thank you very much!

**Comment by lervag** [comment]
No problem :)
