### ISSUE TITLE
Command folding 'multi' fold on first mandatory argument in curly braces

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#828]
The package `pgfplotstable` suggests following code snippet to have table sources within your latex file:
```tex
\pgfplotstableread[col sep=semicolon,trim cells]{
x    ; y    ; z   ; type  ; reference       ; comment
0.01 ; 1.00 ; nan ; type1 ; ref-unspecified ;
0.02 ; 2.00 ; nan ; type2 ; ref-unspecified ;
0.03 ; 3.00 ; nan ; type3 ; ref-unspecified ;
}{\datatable}
```
I'd like to fold this to
```tex
\pgfplotstableread[col sep=semicolon,trim cells]{...}{\datatable}
```

This can also be written as
```tex
\pgfplotstableread[col sep=semicolon,trim cells]{
x    ; y    ; z   ; type  ; reference       ; comment
0.01 ; 1.00 ; nan ; type1 ; ref-unspecified ;
0.02 ; 2.00 ; nan ; type2 ; ref-unspecified ;
0.03 ; 3.00 ; nan ; type3 ; ref-unspecified ;
}
\datatable
```
and then folds to
```tex
\pgfplotstableread[col sep=semicolon,trim cells]{...}---------------------------------------
\datatable
```
using existing folding capabilities but extended the regex for 'single' to allow options in square brackets.

### Allow square brackets between command and curly braces for command folding type  'single`
 This requires to change the following function:
```viml
function! s:cmd_single(cmds) " {{{1
  let l:re = '\v^\s*\\%(' . join(a:cmds, '|') . ')\*?\s*%(\[.*\])?'

  let l:fold = {}
  let l:fold.re = {
        \ 'start' : l:re . '\s*\{\s*%($|\%)',
        \ 'end' : '^\s*}',
        \ 'text' : l:re,
        \}

  function! l:fold.level(line, lnum) dict
    if a:line =~# self.re.start
      let self.opened = 1
      return 'a1'
    elseif has_key(self, 'opened')
          \ && a:line =~# self.re.end
      unlet self.opened
      return 's1'
    endif
    return ''
  endfunction

  function! l:fold.text(line) dict
    return matchstr(a:line, self.re.text) . '{...}'
  endfunction

  return l:fold
endfunction
```

### Fourth command folding type: fold first curly braces
However, I would prefer the first one. Since in the second one it is not obvious that `\datatable` belongs to `\pgfplotstableread`.

Would you consider adding a fourth type of command folding 'first'?

**Comment by kiryph** [comment]
Instead of forth command folding type 'first, I think adding a more general regex for the end of command folding 'single' should be sufficient:
Right now the value is: `'end' : '^\s*}'`
What about changing it to something like`^\s*}%(\{.*\})*;?`?
And the foldtext should also be extended.
However, this actually does not work. Do you know what the correct regex would be?

**Comment by lervag** [comment]
Just letting you know I've seen your recent issues, but I'm pressed for time. Will consider them when I have the time. I think you have some good suggestion for folding, but it will require some thinking since I want to avoid making things even more complex. :)

**Comment by kiryph** [comment]
@lervag No rush. All my issues are no bugs and everything works as expected. Extending folding is probably a never ending story. BTW vimtex provides already very good support for latex folding compared to other editors or plugins. 

And in this case I can already surround the inline data block with a manual fold. I usually do not like adding code for a feature of an editor, but I am right now the only one editing the file anyway.

I am much in favour of well-thought changes. Maybe I rush a little bit too fast with my feature requests and realize it can be done differently. Slowly advancing vimtex is a good idea.

**Comment by lervag** [comment]
Ok, I think this is solved. However, I'm curiuos: Should we update the default list of folded commands to include `pgfplotstableread`? If so, are there variants of the command that should be respected as well?

**Comment by kiryph** [comment]
Thanks for this update.

I think updating the documentation with an example (which could be part of the default list) should be helpful for others.

Afaik there are no variants for `pgfplotstableread`:
```tex
\pgfplotstableread[optional arguments]{file name}{\macro}
\pgfplotstableread[optional arguments]{inline table}{\macro}
```
