### ISSUE TITLE
How to fold preamble manually?

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#830]
### Explain the issue
I see that the manual has an method called `FakeSection` in fold. But it seems not work?? I try the following document:
```tex
\documentclass{amsart}
% Fakesection {Fold preamble always}
% Fold at level {{{5
\usepackage{amsmath}
\newcommand{\test}{}
%}}}
\begin{document}
\section{test}
this is section.
\subsection{test}
this is subsection.
\end{document}
```
If I `:set fdm=marker`, then the above code will be fold at the marker `{{{5` with level 5, while the other part is nto fold at all. So is there any solution to make vimtex fold the preamble?

I use the `FastFold` plugin and enabled the tex_fold option as
```vim
" Enable TeX fold {
au FileType tex let g:tex_fold_enabled =1
" we don't want fold too much
au FileType Tex setlocal foldlevel=3
" }
```

**Comment by lervag** [comment]
1. You can not mix fold methods. If you want to enable the vimtex folding feature, you need to have `let g:vimtex_fold_enabled = 1` in your vimrc file. This will use the `expr` fold method, but FastFold will apply some tricks with the `manual` fold method and only apply the expression at some chosen times.
2. The `g:tex_fold_enabled` is _not_ part of vimtex. If you want vimtex folding, don't enable this.

**Comment by vanabel** [comment]
Yes, it works now, if I set 
```vim
let g:vimtex_fold_enabled =1
```
but why it not work for
```vim
au FileType tex let g:vimtex_fold_enabled =1
```

**Comment by lervag** [comment]
The last form does not work because the option needs to be set _before_ loading the `.tex` file. This is because vimtex will initialize when a `.tex` file is loaded. The vimtex folding is turned off by default, and so it will only work if you set the option appropriately in your vimrc file.
