### ISSUE TITLE
Fold not work for comments?

### ISSUE THREAD

**Issue by vanabel** [lervag/vimtex#831]
I found that the comments (lines start with `%`) is not folded at any level. In fact it is better to fold at the deepest level, since we don't want to see it except rather special cases.

**Comment by lervag** [comment]
Could you please provide a minimal example? Comments should be included in folds, but comments are not folded themselves unless you set an option: `let g:vimtex_fold_comments = 1`.

**Comment by vanabel** [comment]
Ok, I think this problem is easy, but it is not. To make things clear, consider the following example:

### My minimal _vimrc

```vim
" vim: foldmethod=marker foldmarker={,}
" Plugin Admin {
call plug#begin('$Vim/myvim/plugged')
" for latex
Plug 'lervag/vimtex'
Plug 'Konfekt/FastFold'
call plug#end()
" }
"  Fold {
let g:vimtex_fold_enabled =1
let g:vimtex_fold_comments =1
let g:vimtex_fold_preamble =0
" }
" Viewer {
let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options
      \ = '-reuse-instance -forward-search @tex @line @pdf'
      \ . '-inverse-search "gvim --servername ' . v:servername
      \ . ' --remote-send \"^<C-\^>^<C-n^>'
      \ . ':drop \%f^<CR^>:\%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':execute ''drop '' . fnameescape(''\%f'')^<CR^>'
      \ . ':\%l^<CR^>:normal\! zzzv^<CR^>'
      \ . ':call remote_foreground('''.v:servername.''')^<CR^>^<CR^>\""'
" }
```

### The tested test.tex file

```tex
\documentclass{amsart}
% Fakesubsubsection Preamble
\usepackage{amsmath}
\newcommand{\test}{}
\begin{document}
\section{test}
this is section.
\subsection{test}
this is subsection.
\begin{equation}
	a+b=c
\end{equation}

% some comments
% some more

\section{new section}

\subsection{subsection}

\end{document}
```

With `zM` to fold all first and `zr` to unfold one by one, we see that the comments is not fold at all with above settings, since it at the same leve of `subsection`. In my opition, it should be at the lowest level, that is all things is open but the fold of comments should be keep closing.

By the way, I use the newest version of `vimtex`, is there any possibility that `` $`a$`` is not auto-complete to `$\alpha$` for a long document (>1500 lines)? which is quite strange it work at some position (before line 1000) but not work for other position (after 1100 lines), and after a while it work for any position. My OS is windows7 and the environment is the same as above but with long tex document.

**Comment by lervag** [comment]
Please don't raise more than one issue per thread. Open a new issue for the new topic.

Regarding the folding of comments, it seems there was a minor bug. Please test the most recent version.
