### ISSUE TITLE
Folding: add variable to let the user choose which environments should be folded

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#833]
I like folding of figures and math environments which provide a caption or label as foldtext.

However, other environments are not really useful for folding. For example:

```tex
\begin{tikzpicture}
\begin{axis}
\addplot+[error bars/.cd,x dir=both,x explicit] coordinates {
    (0,0)   +- (0.1,0)
    (0.5,1) +- (0.4,0.2)
    (1,2)
    (2,5)   +- (1,0.1)
};
\end{axis}
\end{tikzpicture}
```

The tikzpicture and axis environment folds are just annoying to re-open. I would prefer to disable it for them.

So adding a whitelist or blacklist to enable or disable folding for selected environments would add a possibility to limit the number of unused folds.

In latex-suite there is a whitelist
```
Tex_FoldedEnvironments
    verbatim,comment,eq,gather,
    align,figure,table,thebibliography,
    keywords,abstract,titlepage
```

Another approach would be: add an option to only fold those which have a special foldtext.
I mean by this: either a caption, label, comment or similar is used for the foldtext.

---

Afterwards I would be interested in folding of options of environments which are not folded (see https://github.com/lervag/vimtex/issues/829#issuecomment-300512331)

**Comment by lervag** [comment]
I've added whitelist and blacklist options now. With the current logic, the blacklist option will override the whitelist option. Also, if the whitelist is not empty, then only environments specified there will be folded.

**Comment by lervag** [comment]
Let me know what you think!
