### ISSUE TITLE
[solved]Synctex with neovim does not work anymore since deprecation of g:vimtex_latexmk_progname

### ISSUE THREAD

**Issue by stupidus89** [lervag/vimtex#835]
### Edit
Sorry, I am stupid sometimes.

`let g:vimtex_compiler_progname = "nvr"` does the trick. Should have read the documentation more carefully. However, there is a small mistake in the documentation:
```
*g:vimtex_latexmk_enabled* (use |g:vimtex_compiler_progname|)
*g:vimtex_latexmk_progname* (use |g:vimtex_compiler_enabled|)
```
These lines are switched, that's what got me confused.

### Explain the issue

I have a setup using neovim, vimtex, neovim-remote and zathura to get synctex working.
I had to use the following setting to get it to work (according to https://github.com/lervag/vimtex/issues/262#issuecomment-232037085):
`let g:vimtex_latexmk_progname = "nvr"`

Now, that this option is deprecated, zathura is called the following way
`zathura -x "/usr/bin/nvim --servername /tmp/nvim-MSWnprhayktp1fS6dbuzCZb3ZUuK11GY --remote +\%{line} \%{input}"`

However, it should be `zathura -x "/usr/bin/nvr ...`. Is there a new option to make the pdfviewer call nvr instead of nvim?

### Minimal vimrc file

```set runtimepath^=~/.config/nvim/bundle/vimtex
let g:vimtex_view_method = "zathura"
let g:vimtex_latexmk_progname = "nvr"
let g:tex_flavor = 'latex'
```
I am starting nvim the following way:
```
ID=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
socket=/tmp/nvim-$ID
nvr --servername $socket --remote $1 
```

**Comment by lervag** [comment]
As you say, `g:vimtex_latexmk_progname` is deprecated, but a better name is "renamed". A month ago or so I made some large updates that required some renaming. The new name is `g:vimtex_compiler_progname`.

**Comment by lervag** [comment]
Ah, thanks, I didn't notice the minor glitch in the docs. Should be fixed now.
