### ISSUE TITLE
Viewer duplication

### ISSUE THREAD

**Issue by Tyrn** [lervag/vimtex#836]
### Pdf viewer is duplicated on first forward search

This issue is opened as a sequel to issue #313. Before I can supply the MWE, replication steps, etc. I'd like to clear some uncertainties.

Zathura is certainly beautiful, but it doesn't honor hyperrefs, so I reverted to Okular. It also duplicates (once) on first forward search, every session. After some experimenting I learned that option `--unique` is essential, no matter how you start or restart Okular. Only *then* I discovered **vimtex.txt** recommendations on Okular. My point exactly! `.vimrc`:

    " vimtex group (view settings according to vimtex.txt; stands perfectly to reason)
    let g:vimtex_view_method = 'general'
    let g:vimtex_view_general_viewer = 'okular'
    let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
    let g:vimtex_view_general_options_latexmk = '--unique'
    let g:vimtex_compiler_method = 'latexmk'

The message is clear: unless you manage to put the burden of non-duplication on the viewer, it duplicates. The author of recommendations is perfectly aware of it, too. My `.latexmkrc`, the fruit of my independent experimentation:

    $pdf_mode = 1;
    $pdflatex = 'xelatex -interaction=nonstopmode -synctex=1';
    $pdf_previewer = 'okular --unique';

So I'd like to know why the author expects correct behavior in the first place. Maybe some brief under the hood introduction would be of service.

**Comment by lervag** [comment]
I do not quite grasp what you are raising here. When you say "the author", are you referring to me? It is also unclear if you are saying that the duplicated viewer is a problem also with okular, even with the settings (as described in the docs)?

All in all, I am aware that there is a duplication problem with Zathura. Unfortunately, it is difficult to replicate the problem, and so I haven't been able to fix it.

----

A minor comment to your vimrc settings: The `g:vimtex_view_general` and `g:vimtex_compiler_method` are not changed from default values and are therefore not needed.

**Comment by Tyrn** [comment]
Okular also duplicates, unless the docs settings are put into `.vimrc`. To my understanding, the settings make the first call of Okular to be with `--unique` option (as well as subsequent "forward search" calls), which blocks any possibility of duplication. From what I see in the #837 issue, it's a race condition which has always been there. It's just your computer being too fast for you to run into the problem yourself.

Yes, some of my `.vimrc` settings are redundant, but one of them must be essential.

**Comment by lervag** [comment]
But of course Okular duplicates if you do not use the suggested settings. That's _why_ they are suggested, after all. Thus there is no issue here.

And no, for Zathura, there is no race condition. I've actually just debugged this, and the problem is due to Zathura. I'll comment more detailed in #837.

**Comment by lervag** [comment]
These settings are essential if you want to use `okular`:

```vim
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
```
