### ISSUE TITLE
vimtex doesn't load with wildignorecase

### ISSUE THREAD

**Issue by mreppen** [lervag/vimtex#839]
Whenever I add `set wildignorecase` to init.vim (neovim), vimtex fails to load. The same problem occurs with regular vim/.vimrc.

It fails on every file, but here is a minimal `.tex` file:
```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

`init.vim`:

```vim
let &rtp  = '~/temp/vimtex,' . &rtp
let &rtp .= ',~/temp/vimtex/after'

let g:tex_flavor="latex"
set wildignorecase
```

I'm running fish, but neither `set shell=/bin/sh`, nor running under bash works.

**Comment by lervag** [comment]
Your minimal vimrc file is not complete. vimtex will not load if you do not also have `filetype plugin indent on` and `syntax enable` (of course, assuming that you want indentation and syntax highlighting; at a minimum you need `filetype plugin on`).

I've added test files, as you can see above. When I run the test with `nvim -u minivimrc` from the test folder, I can see no issue; i.e., I can't reproduce this with neovim or Vim.

**Comment by mreppen** [comment]
Thank you for your reply. You are right that `filetype plugin indent on` should have been in there, but the problem persists with your test files (only updated rtp paths).

Whenever I comment out `set wildignorecase`, vimtex is again available, both in neovim and Vim.

This computer is running fully updated Fedora 24, neovim version 0.1.7 and Vim 8.0. I will try to replicate it on another system tonight.

**Comment by lervag** [comment]
Strange. I'm on Arch Linux with Vim 8.0.586 and neovim v0.2.0.

Do you have any plugins installed on the system? Whats the output of `:scriptnames` when you run the test with the minimal vimrc file?

**Comment by mreppen** [comment]
On my Arch computer everything is fine.

This is the Fedora output of `:scriptnames`:
nvim:
```
  1: ~/temp/vimtex/test/issues/839/minivimrc
  2: /usr/share/nvim/runtime/filetype.vim
  3: /usr/share/nvim/runtime/ftplugin.vim
  4: /usr/share/nvim/runtime/indent.vim
  5: /usr/share/nvim/runtime/syntax/syntax.vim
  6: /usr/share/nvim/runtime/syntax/synload.vim
  7: /usr/share/nvim/runtime/syntax/syncolor.vim
  8: /usr/share/nvim/runtime/plugin/gzip.vim
  9: /usr/share/nvim/runtime/plugin/health.vim
 10: /usr/share/nvim/runtime/plugin/man.vim
 11: /usr/share/nvim/runtime/plugin/matchit.vim
 12: /usr/share/nvim/runtime/plugin/matchparen.vim
 13: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 14: /usr/share/nvim/runtime/plugin/rplugin.vim
 15: /usr/share/nvim/runtime/plugin/rrhelper.vim
 16: /usr/share/nvim/runtime/plugin/shada.vim
 17: /usr/share/nvim/runtime/plugin/spellfile.vim
 18: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 19: /usr/share/nvim/runtime/plugin/tohtml.vim
 20: /usr/share/nvim/runtime/plugin/tutor.vim
 21: /usr/share/nvim/runtime/plugin/zipPlugin.vim
 22: ~/temp/vimtex/ftplugin/tex.vim
 23: ~/temp/vimtex/autoload/vimtex.vim
 24: /usr/share/nvim/runtime/autoload/remote/host.vim
 25: ~/.local/share/nvim/rplugin.vim
 26: /usr/share/nvim/runtime/autoload/remote/define.vim
 27: ~/temp/vimtex/autoload/vimtex/util.vim
 28: ~/temp/vimtex/autoload/vimtex/state.vim
 29: ~/temp/vimtex/autoload/vimtex/parser.vim
 30: ~/temp/vimtex/autoload/vimtex/view.vim
 31: ~/temp/vimtex/autoload/vimtex/view/general.vim
 32: ~/temp/vimtex/autoload/vimtex/view/common.vim
 33: ~/temp/vimtex/autoload/vimtex/compiler.vim
 34: ~/temp/vimtex/autoload/vimtex/compiler/latexmk.vim
 35: ~/temp/vimtex/autoload/vimtex/qf.vim
 36: ~/temp/vimtex/autoload/vimtex/qf/latexlog.vim
 37: ~/temp/vimtex/autoload/vimtex/toc.vim
 38: ~/temp/vimtex/autoload/vimtex/index.vim
 39: ~/temp/vimtex/autoload/vimtex/labels.vim
 40: /usr/share/nvim/runtime/ftplugin/tex.vim
 41: ~/temp/vimtex/indent/tex.vim
 42: ~/temp/vimtex/autoload/vimtex/delim.vim
 43: /usr/share/nvim/runtime/indent/tex.vim
 44: /usr/share/nvim/runtime/syntax/tex.vim
 45: ~/temp/vimtex/after/syntax/tex.vim
 46: /usr/share/nvim/runtime/syntax/dot.vim
 47: /usr/share/nvim/runtime/syntax/lua.vim
 48: /usr/share/nvim/runtime/syntax/gnuplot.vim
 49: ~/temp/vimtex/autoload/vimtex/env.vim
 50: /usr/share/nvim/runtime/scripts.vim
 51: /usr/share/nvim/runtime/ftplugin/text.vim
 52: /usr/share/nvim/runtime/ftplugin/help.vim
 53: /usr/share/nvim/runtime/syntax/help.vim
```

vim:
```
 1: ~/temp/vimtex/test/issues/839/minivimrc
2: /usr/share/vim/vim80/filetype.vim
3: /usr/share/vim/vimfiles/ftdetect/stp.vim
4: /usr/share/vim/vim80/ftplugin.vim
5: /usr/share/vim/vim80/indent.vim
6: /usr/share/vim/vim80/syntax/syntax.vim
7: /usr/share/vim/vim80/syntax/synload.vim
8: /usr/share/vim/vim80/syntax/syncolor.vim
9: /usr/share/vim/vimfiles/plugin/cctree.vim
10: /usr/share/vim/vim80/plugin/getscriptPlugin.vim
11: /usr/share/vim/vim80/plugin/gzip.vim
12: /usr/share/vim/vim80/plugin/logiPat.vim
13: /usr/share/vim/vim80/plugin/manpager.vim
14: /usr/share/vim/vim80/plugin/matchparen.vim
15: /usr/share/vim/vim80/plugin/netrwPlugin.vim
16: /usr/share/vim/vim80/plugin/rrhelper.vim
17: /usr/share/vim/vim80/plugin/spellfile.vim
18: /usr/share/vim/vim80/plugin/tarPlugin.vim
19: /usr/share/vim/vim80/plugin/tohtml.vim
20: /usr/share/vim/vim80/plugin/vimballPlugin.vim
21: /usr/share/vim/vim80/plugin/zipPlugin.vim
22: ~/temp/vimtex/ftplugin/tex.vim
23: ~/temp/vimtex/autoload/vimtex.vim
24: ~/temp/vimtex/autoload/vimtex/util.vim
25: ~/temp/vimtex/autoload/vimtex/state.vim
26: ~/temp/vimtex/autoload/vimtex/parser.vim
27: ~/temp/vimtex/autoload/vimtex/view.vim
28: ~/temp/vimtex/autoload/vimtex/view/general.vim
29: ~/temp/vimtex/autoload/vimtex/view/common.vim
30: ~/temp/vimtex/autoload/vimtex/compiler.vim
31: ~/temp/vimtex/autoload/vimtex/compiler/latexmk.vim
32: ~/temp/vimtex/autoload/vimtex/echo.vim
33: ~/temp/vimtex/autoload/vimtex/qf.vim
34: ~/temp/vimtex/autoload/vimtex/qf/latexlog.vim
35: ~/temp/vimtex/autoload/vimtex/toc.vim
36: ~/temp/vimtex/autoload/vimtex/index.vim
37: ~/temp/vimtex/autoload/vimtex/labels.vim
38: /usr/share/vim/vim80/ftplugin/tex.vim
39: ~/temp/vimtex/indent/tex.vim
40: ~/temp/vimtex/autoload/vimtex/delim.vim
41: /usr/share/vim/vim80/indent/tex.vim
42: /usr/share/vim/vim80/syntax/tex.vim
43: ~/temp/vimtex/after/syntax/tex.vim
44: /usr/share/vim/vim80/syntax/dot.vim
45: /usr/share/vim/vim80/syntax/lua.vim
46: /usr/share/vim/vim80/syntax/gnuplot.vim
47: ~/temp/vimtex/autoload/vimtex/env.vim
```

**Comment by lervag** [comment]
Strange. I don't quite see what the problem is. As I can't reproduce it, I can't debug it myself.

Do you have both your Fedora and Arch Linux boxes at the same location? If so, could you try to run with more verbose output, i.e. `vim -V9 -u minivimrc minimal.tex` on both boxes and see if you can find some relevant differences?

**Comment by mreppen** [comment]
Unfortunately not at the same location, but I will try to arrange something and come back when

**Comment by mreppen** [comment]
Ooops. Accidental click.

They are not at the same location, but I will arrange so that I can compare and then come back with whatever I find.

**Comment by lervag** [comment]
I think this could be useful even without the comparison. On the Arch box, it will probably not reveal anything suspicious (it does not here). On Fedora, I hope it might reveal something. You can also try to increase the number (I think 20 is the maximum verbosity level, but this is specified more clealy in the docs (see `:h -V` and `:h 'verbose'). You could also use `-V9vimlog` to pass the log output to a file.

**Comment by mreppen** [comment]
Ok, here we go.

I tried running with and without the `wildignorecase` option and compared the logs. They are too long to post here, but the first line that differed in both `-V9` and `-V20` was
`Searching for "autoload/vimtex/cmd.vim" in ".......`
It turns out that the string `cmd.vim` doesn't even show up in the logs with `wildignorecase`. The log diffs are several hundred lines already with `-V9` (thousands with `-V20`), so I won't paste them here, but would gladly help look for clues (or send the log to the address I found in `-V20`).

Just to clarify:
The following two lines are found in both:
`continuing in function vimtex#init[5]..<SNR>23_init_state[1]..vimtex#state#init`
and
`finished sourcing /scratch/users/mreppen/temp/vimtex/ftplugin/tex.vim`
With `wildignorecase`, i.e., when vimtex doesn't load, there is nothing in-between the lines. When it successfully loads, it starts searching for `cmd.vim`.

**Comment by lervag** [comment]
If you compare the logs with `diff log1 log2`: Is the output still very long?

Note that you can attach files to an issue comment. Thus the size isn't that important...

Based on you comment it seems there might be something about `cmd.vim` that does not work.

Btw: Which version of Vim are you on? I.e. patch level, see output of `:version`.

One thing you could try: Add `finish` after the function `vimtex#cmd#init_buffer` in `cmd.vim`. This would prevent the remaining part from being sourced. If it works now, this will indicate that the problem is located there.

**Comment by mreppen** [comment]
I think I have found the issue. It happens in `glob` here:
https://github.com/lervag/vimtex/blob/master/autoload/vimtex.vim#L495

It turns out that `glob` fails with `wildignorecase` when a parent directory doesn't have read access. When running `glob` on a symlink bypassing the unreadable directory, it works again. What's also interesting is that with both `fileignorecase` and `wildignorecase` set, everything works.

This is clearly not a bug in vimtex, so I'll close this.

Thanks for an excellent plugin and your responsiveness here.

**Comment by lervag** [comment]
Interesting. I'm curious how you would end up with the scenario of the unreadable directory; I can not remember being on a system where I've had a parent directory be unreadable.

Good work in locating the problem! Nice catch finding that specific line with the `glob`.

In any case, I'm happy to hear this was not vimtex related, and I'm also happy to hear you like the plugin. Don't hesitate to open other issues if you find any.

**Comment by mreppen** [comment]
In this case, it's analogous to not having read access to `/home/`. It's also causing a lot of issues in GUI file save/open dialogs where it sometimes starts at `/` and I can't navigate...

It's not my setup, and I can't change it, so I just have to live with it.

**Comment by lervag** [comment]
Ok, I see. In any case, good to hear that you've figured it out and found ways to make things work.
