### ISSUE TITLE
Is it possible to improve syntax support for array package with {>$}{<$} spec?

### ISSUE THREAD

**Issue by CareF** [lervag/vimtex#840]
It's not a bug, and I checked that it's not supported by bare vim. It would be very much appreciated if this feather would be supported. 

I noticed that for the tabular with {>$} {<$} setting (meaning math mode in the table by default), there will be problems for syntax highlight as all the contents after this will be specified as in the math mode. For example the following codes: 

```
\documentclass{article}
\usepackage{array}
\begin{document}
\begin{tabular}{*{3}{>{$}c<{$}}}
	a & b & c \\\hline
	1 & 2 & 3
\end{tabular}

Here it should not be in the math mode. 
\end{document}
````

Probably it's not that important to support math mode inside the table, but it can be very annoying when all the contents afterwards are highlighted as math mode.

**Comment by lervag** [comment]
I think this should be added to the internal syntax plugin, and I have sent an email with a suggested fix for Dr. Chip. In the meantime, you can fix this yourself by adding the following lines to your own `after/syntax/tex.vim` file, e.g. in your `.vim` folder:

```vim
if exists('b:vimtex.packages.array') && get(g:, 'tex_fast', 'M') =~# 'M'
  syntax clear texMathZoneX
  if has('conceal') && &enc ==# 'utf-8' && get(g:, 'tex_conceal', 'd') =~# 'd'
    syntax region texMathZoneX matchgroup=Delimiter start="\([<>]{\)\@<!\$" skip="\%(\\\\\)*\\\$" matchgroup=Delimiter end="\$" end="%stopzone\>" concealends contains=@texMathZoneGroup
  else
    syntax region texMathZoneX matchgroup=Delimiter start="\([<>]{\)\@<!\$" skip="\%(\\\\\)*\\\$" matchgroup=Delimiter end="\$" end="%stopzone\>" contains=@texMathZoneGroup
  endif
endif
```

**Comment by CareF** [comment]
Thank you so much for this!

**Comment by lervag** [comment]
No problem! I actually got a reply from Dr. Chip already, and he argued quite well for not including this in the main syntax file. Thus I will add it to vimtex now. Note, though, that although I have tested and it seems to work well, I might choose to remove this if I were to find it breaks something unexpected.
