### ISSUE TITLE
Infinite compilation loop on macOs after commit d4c8d7e

### ISSUE THREAD

**Issue by luigipertoldi** [lervag/vimtex#842]
The `\ll` command starts an infinite compilation loop after commit d4c8d7e, I had to revert back to previous commit to make vimtex work again! My config is just as in #820.

**Comment by luigipertoldi** [comment]
Going back through commits I just realized that's not true, maybe there's something else I updated, I'll investigate, ignore this issue for now.

**Comment by luigipertoldi** [comment]
Apparently it was related to the X11 server, rebooted the OS and now works, sorry for the spam!

**Comment by lervag** [comment]
No problem! :)
