### ISSUE TITLE
Templetes for common types of documents

### ISSUE THREAD

**Issue by copyme** [lervag/vimtex#843]
I do not know about you but I would really appreciate an option to define templates for documents of different types.  

For instance, I found this very painful to setup a new  LaTeX document. I would love to have a function which would do this automatically. For instance, if I want to write a memo I would create a new file and then to set it up I would like to call some function which would add an appropriate  preamble, etc. This would allow us to quickly focus on the most important part of the job which is writing.

Not sure if adding this to vimtex is a good idea -- KISS rule. What do you think?

PS Sorry, if something like that is already in vimtex and I happened to overlook it.

**Comment by kiryph** [comment]
I use ultisnips for this. One of the snippets I commonly use to start a new latex document/MWE is this (inspired by latex-suite)
```
snippet EDO "Documentclass" b
\documentclass[${2:<+options+>}]{${1:article}}

\begin{document}
${0:${VISUAL}}
\end{document}
endsnippet
```

The templates offered by latex-suite can be found here:
https://github.com/vim-latex/vim-latex/tree/master/ftplugin/latex-suite/templates

They can easily be converted to a snippet. Any snippet engine (neosnippet, snipmate, ...) is good enough for this.

Secondly, snippets can be defined for typical environemnts such as figure which also consist of boilerplate code.
```
snippet fig "Figure environment" b
\begin{figure}[${2:htpb}]
	\centering
	\includegraphics[width=${3:0.8}\linewidth]{${4:name.ext}}
	\caption{${4/(\w+)\.\w+/\u$1/}$0}
	\label{fig:${4/(\w+)\.\w+/$1/}}
\end{figure}
endsnippet
```

**Comment by lervag** [comment]
Yes, as @kiryph says, this feature is already implemented by several plugins such as UltiSnips or neosnippet. In addition, these plugins provide a more general mechanism of snippets/templates that can be used for any kind of filetype. For this reason, I have chosen to not include such a template feature in vimtex.

**Comment by lervag** [comment]
By the way, I use UltiSnips and I have defined a couple of very _minor_ templates that I use often. See my [UltiSnips folder in my dotvim repo](https://github.com/lervag/dotvim/tree/master/UltiSnips) for how I define these.
