### ISSUE TITLE
vimtex does not recognize the star-variant of \subimport*

### ISSUE THREAD

**Issue by apskim** [lervag/vimtex#844]
## Issue

The `import` package includes star-variants of the commands: `\import*` and `\subimport*`, which direct the compiler to avoid searching for the included files in TEXINPUTS. However, vimtex does not recognize them when it collects its list of source files for the project. Thus, the included files are not visible in `<leader>li`, forward-searching with `<leader>lv` from them does not work, etc.

## Minimal working example

`main.tex.latexmain`:
Empty.

`main.tex`:

```tex
\documentclass{minimal}
\usepackage{import}
\begin{document}

\subimport*{chapter1/}{other}

\end{document}
```

`chapter1/other.tex`:

```tex
\section{Intro}
Hello
```

Open `main.tex` and press `<leader>li`.

**Expected behavior:**
```
source files:
  main.tex
  chapter1/other.tex
```

**Actual behavior:**
```
source files:
  main.tex
```

Changing `\subimport*` to `\subimport` fixes the issue.

**Comment by lervag** [comment]
Haha. Gold fish memory: I just pushed a fix to this, but I intended to test it some more before pushing. However, I now fixed something else in the meantime and forgot about that. I'll test it some more now, though, but I think it should work.

**Comment by lervag** [comment]
I think it should work now.
