### ISSUE TITLE
PDF viewer which automatically refresh the window

### ISSUE THREAD

**Issue by junhyeokahn** [lervag/vimtex#845]
Hi, I have a small question.
I am the newbie of vimtex. And I am using mac os preview for my pdfviewer.
However, I would like to ask which pdf viewer is looking like this video.(https://youtu.be/uWZiRKjeOdo)
In the video, when he makes some changes, it automatically refresh the pdf file.
For my case, if I change something, it automatically compiled again, but my preview doesn't reload changed pdf before I click that window. So I couldn't continue working on in terminal while seeing the changes.

**Comment by lervag** [comment]
I don't know which PDF viewer he is using. I think perhaps Evince on Linux, but not sure. However, on OSX, I think you could try to use Skim. It should work pretty well, I think, with `g:vimtex_view_method = 'skim'`. Obviously, you need to install it first (I guess).

Note: I don't use OSX myself, so I'm not really able to help on OSX specific questions.

**Comment by junhyeokahn** [comment]
I works really well!
I appreciate!

**Comment by lervag** [comment]
No problem, happy you like it! :)

**Comment by hugoweslien** [comment]
Had the same problem on Ubuntu 16.04 with mupdf changed to zathura and now it works.

**Comment by xarthurx** [comment]
Any recommendation for Windows user?

**Comment by xarthurx** [comment]
Or is it possible to integrate pdf.js as part of vimtex? (This is what `Latex Workshop` do for vscode)

**Comment by lervag** [comment]
@xarthurx Please open a new issue. Your comments are _not_ related to the original thread, and it is much better if you open separate new issues with clear wordings of your questions/issues/requests.
