### ISSUE TITLE
Environments do not fold any more

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#848]
Commit 8a8d8f835521f0799b2bb0fa623b708677cd84fb breaks folding of TeX environments (that is, `\begin{} ... \end{}`)

**Comment by lervag** [comment]
Sorry. Fixed now.

**Comment by Konfekt** [comment]
Thank you!

**Comment by lervag** [comment]
No problem! Thanks for noticing and reporting so fast. :)
