### ISSUE TITLE
vimtex warning: Can't use callbacks with empty v:servername

### ISSUE THREAD

**Issue by rionda** [lervag/vimtex#852]
### Explain the issue

With the minimal working example provided below (default from the issue template) and the minimal vimrc provided below (default from the issue template, comments removed), I get the following warning when activating the compilation with "\ll":

```
vimtex warning: Can't use callbacks with empty v:servername
Press ENTER to continue
```
I press ENTER, and then the compilation proceeds (although I don't see 'vimtex: success' message), and the pdf is opened.

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

```

**Comment by lervag** [comment]
After reading the warning, you could follow up with `:h v:servername`, then follow into the `x11-clientserver` tag in the help files. This would explain that the `v:servername` variable is empty if you do not provide the `--servername NAME` option for Vim. `gvim` uses a default nonempty value, `vim` in terminal does not.

I've also explained this in `:h vimtex-requirements` after the part about `latexmk`.

If you are not interested in the callback feature (which requires the clientserver feature), then you can disable it (and thus avoid the warning) with e.g.

```vim
let g:vimtex_compiler_latexmk = {'callback' : 0}
```

**Comment by rionda** [comment]
What I don't get is why the error started showing up when I didn't change any setting, as far as I can tell. Anyway, thank you, I'll see if I can trace it back to some change I may have done.

**Comment by lervag** [comment]
It is because I added the message in a relatively recent commit. I think it makes sense to warn people about this, because if you use Vim in terminal and want to and expect to have the callback feature, then you need to set the servername. Most people, at least those new to Vim, won't realize this, and with no warning it can be confusing.

**Comment by rionda** [comment]
I see, I didn't realize you added the warning. Yes, I agree it makes sense. Thank you again.

**Comment by lervag** [comment]
No problem. Just to be clear, if I came across a little bit offensive in my
first comment, that was not intended. :-)

**Comment by thomasahle** [comment]
Am I doing this right?
```
$ vim paper.tex --servername NAME
```
I still get
```
vimtex: Can't use callbacks with empty v:servername
vimtex: Compiler started in continuous mode
```

**Comment by lervag** [comment]
What is the output of `:VimtexInfo`? I suspect that your vim version does not have the clientserver feature.
