### ISSUE TITLE
Get rid of VimtexLacheck

### ISSUE THREAD

**Issue by petRUShka** [lervag/vimtex#855]
I've found that there is `VimtexLacheck` command.

> Run lacheck to check document for errors.

There are plenty of external plugins like [syntastic](https://github.com/vim-syntastic/syntastic) ([tex checkers](https://github.com/vim-syntastic/syntastic/tree/master/syntax_checkers/tex)), [neomake](https://github.com/neomake/neomake) ([tex checkers](https://github.com/neomake/neomake/blob/master/autoload/neomake/makers/ft/tex.vim)), [ALE](https://github.com/w0rp/ale) ([tex-checkers](https://github.com/w0rp/ale/tree/master/ale_linters/tex)) and others.

They are offered tex-file checkers with not only [lacheck](https://www.ctan.org/pkg/lacheck) support but also with support of tools like [chktex](http://www.nongnu.org/chktex/), [rubberinfo](https://www.systutorials.com/docs/linux/man/1-rubber-info/) and [proselint](http://proselint.com/) .

I believe that support lacheck itself contradicts with modular approach of vimtex. Therefore lacheck support should be replaced with documentation of how to achieve that functionality with more general syntax checkers.

**Comment by lervag** [comment]
Thanks. I agree. I've removed lacheck and added an entry in the changelog with references to syntax checkers.

**Comment by petRUShka** [comment]
Great! Why don't you want to add notice in documentation? For those who don't read Changelog but read documentation.

P.S. I'm asking because I found some interesting vim-tools from documentation of vimtex :)

**Comment by lervag** [comment]
Does this work better, you think?

**Comment by petRUShka** [comment]
I believe it does. Thanks!

**Comment by lervag** [comment]
No problem :)
