### ISSUE TITLE
Custom ToC matcher question/suggestion

### ISSUE THREAD

**Issue by dbmrq** [lervag/vimtex#856]
I added this simple custom matcher:

```vim
let g:vimtex_toc_custom_matchers = [
        \ { 'title' : 'To do',
        \   're' : '% TODO:' }
        \]
```

Instead of the title being "To do", however, I would like the whole line to show at the ToC. Something like:

```
1      A section
1.1    A subsection
TODO:  Whatever and ever amen
1.2    Another subsection
```

I couldn't figure out how to do that from the documentation though. Is that what the `get_entry` stuff is for? I didn't get how it works.

And I said this is a question/suggestion because I think it would be nice if vimtex had this matcher by default. Also it would be cool if there were an option to show the to-dos all together at the bottom of the ToC maybe.

As always, thanks for your great work on vimtex. :)

**Comment by lervag** [comment]
I think this is a good idea! I've added an initial version, please test and let me know what you think.

I could probably collect TODOs at the top or bottom of the TOC window (this could also be configurable or toggleable).

**Comment by lervag** [comment]
Now you can toggle between sorting the TODOs at the top or showing them inline. I've added some syntax highlighting as well. I think this should be pretty close to what you want.

**Comment by dbmrq** [comment]
Fantastic, it works perfectly. Thank you! 🍻

**Comment by dbmrq** [comment]
One small detail: typing `s` to hide the section numbers hides the "TODO:" text instead of the numbers. I don't mind it, though, just thought I should mention it.

**Comment by lervag** [comment]
Yes, I am aware that `s` will hide the TODO text. However, it feels unnecessary to change this at the moment. I might reconsider if someone thinks I'm wrong... :) (I like the saying "Don't let perfect be the enemy of good".)
