### ISSUE TITLE
Regression in recursive subimport handling

### ISSUE THREAD

**Issue by DelusionalLogic** [lervag/vimtex#857]
Commit b84e71 caused a regression of issue 841. The test case for issue 841 will already catch it if you open index.tex.

It seems to be related to this hunk: https://github.com/lervag/vimtex/commit/b84e710ab025c86c839bdaf458604aec98b7a535#diff-d9ca53ac9c170d83c2e834a75cb06008R208. When a subimport is used, the variable ```l:file``` holds something like ```{subdir/}{subfile.tex}```, which the old version would make into ```subdir/subfile.tex```, instead the new version discards the first part and just constructs ```subfile.tex```.

**Comment by lervag** [comment]
Thanks (and sorry!), I'll try to look at this later tonight. Note to self: I should write more tests! :\

**Comment by lervag** [comment]
Ok, I've studied the code, and I've added something that I don't quite see why is there. I've removed it, which fixes the issue. However, I might have missed something important. It would be nice to add some tests. I'll check the import package docs to see if I can write some commands and create some tests based on that.

**Comment by lervag** [comment]
I've updated my tests so that such regression bugs should not go undetected. My tests are based on the import documentation, and I think I should have covered the main cases. However, don't hesitate to let me know if you find edge cases that do not work.

**Comment by DelusionalLogic** [comment]
I will continue whining whenever something interferes with my workflow ;)

Seriously though, I'm just happy you are willing to support such a (apparently) unconventional use case.

**Comment by lervag** [comment]
To me it seems the import package is very convenient for some of its uses, and so I think it is good to support it. However, it is very valuable with users like you who report the issues and make me aware of the problems. :)
