### ISSUE TITLE
Reverse search doesn't work when there is another pdf file with similar name is open

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#858]
I'm almost sure that this issue can not be fixed, but will describe it anyway.

Steps to reproduce:
1. Compile you document with synctex support. Let's say the output is called talk.pdf
2. Open the viewer with `\lv`.
3. Go several pages through and use reverse search. `vimtex` will open the relevant file and line.
4. Close the viewer.
5. Somewhere else open another file named talk.pdf.
6. Open the view via `\lv` again.
7. Try reverse search. Doesn't work.

I'm thinking that the MWE is not required here. Tell me, if you need one.

It looks like the problem is in pdf viewer title check. I do not know the procedure, but may be checking the CWD (/proc/`pid`/cwd) of the viewer might help to distinguish the correct viewer.

**Comment by lervag** [comment]
I have one essential question:

- Which PDF viewer are you using? Do you think this is a problem with other viewers as well?

I also suspect this is a difficult one to solve. And I don't see that your steps to reproduce are something you would do often...

**Comment by maxfl** [comment]
I was using `zathura`.

If I use `mupdf` I can not reproduce the issue, but it is still a problem. Instead of opening the file, it jumps to the other open pdf viewer with the similar filename but the wrong pdf. When `mupdf` is used it may even jump to the similar filename opened in `zathura`. 

I hit this issue since I'm using some common file names: talk.tex, project.tex, etc.

Since the issue may not be solved I think it worth noting it in the vimtex. documentation.

**Comment by lervag** [comment]
I don't really see how to solve this issue. I've tried to find ways to do it before, but with no luck. And since it is not really a big problem (at least to me), I've not bothered to search for a very complicated solution that might work (if there is one).

Feel free to suggest an update to the docs that you think should suffice.

**Comment by maxfl** [comment]
I think something like this should be enough, feel free to improve English:
Note, that viewer handling uses window title matching. If there exists another pdf viewer with the same name as the current project pdf file viewing mechanism may misbehave. Known issues:
 - reverse search doesn't work for zathura.
 - mupdf can not be opened from vimtex.

**Comment by maxfl** [comment]
And a note that the issue will not be solved.

**Comment by lervag** [comment]
Thanks, I've added comments for MuPDF and Zathura.
