### ISSUE TITLE
Autocomplete the environment name in `\end{`

### ISSUE THREAD

**Issue by woky** [lervag/vimtex#860]
With LatexBox, I could use omni-completion (`C-x C-o`) to autocomplete the end of enviroment. For instance, in this case

```
\begin{quote}
foo bar baz
\end{
```

when cursor was placed after `\end{`, then `quote}` would be completed. This stopped working since I switched to vimtex. Is there something similar or different?

Thank you.

**Comment by lervag** [comment]
Yes, there is no such omni-complete feature in vimtex. Instead, you can use `]]` in insert mode to complete the current open delimiter/environment. This also works for closing e.g. `\left(` and similar.
