### ISSUE TITLE
marker folds not folding if marker followed by a comment 

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#862]
With 
```vim
set foldmarker=\ {{{,\ }}}
```
in `.vimrc`, in a TeX file  
```tex
% FOLD {{{
% Comment
\RequirePackage[shortlabels,inline]{enumitem}
% }}}
```
does not fold anymore. Removing `% Comment` it does so. This seems to be recent.

**Comment by lervag** [comment]
Vimtex folding does support foldmarkers, but it does not respect the foldmarker setting. Instead, it uses the following regexes:

```vim
  if line =~# '\v\%.*\{\{\{'
    return 'a1'
  elseif line =~# '\v\%\s*\}\}\}'
    return 's1'
  endif
```

With the following minimal vimrc file your example folds as expected.

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:tex_flavor = 'latex'
let g:vimtex_fold_enabled = 1
```

**Comment by Konfekt** [comment]
Okay. The regexes do not explain to me why the additional comment below the fold marker disables the fold though.

I forgot the setting
```vim
let g:vimtex_fold_comments = 1
```
to reproduce the issue with a minimal virmrc.

**Comment by lervag** [comment]
Ok, I think I've fixed it. However, note that fold markers don't mix well with comment folding. In particular, if you use fold markers inside several lines of comments, the two concepts will mix together and the actual fold levels can only be calculated in a coupled fashion. I don't really see why I should bother to implement that, and so at the moment, I won't. Thus: Please don't use fold markers inside comment blocks unless you turn off comment folding.

**Comment by Konfekt** [comment]
Thank you! Yes, from a pragmatic standpoint, there's little need to implement the nesting between marker and comment folds.
