### ISSUE TITLE
Warnings not ignored in GVim

### ISSUE THREAD

**Issue by qazip** [lervag/vimtex#864]
### Explain the issue

Warnings are not ignored in the error panel/window when using GVim. Nvim works as expected (warnings such as "Overfull hbox" are ignored).

I expected the same behaviour in Nvim and Gvim, that is, warnings such as "Overfull hbox" should be ignored by default.

Warnings are ignored when using neovim (expected) but not ignored when using gvim (unexpected, atleast to me).

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}

\vspace*{+2cm}
\textbf{Abstract}\\

Abstract here

Will this show any warning? Hopefully it will...

\end{document}
```

### Minimal vimrc file

The only thing in my vimrc that has to do with Latex/Vimtex is the following:

```vim
filetype plugin indent on
let g:tex_flavor='latex'
```

**Comment by lervag** [comment]
Nah, I think you have other settings for neovim than for (g)vim. In particular, the following setting will hide warnings such as the Overfull hbox:

```vim
let g:vimtex_quickfix_open_on_warning = 0
```

I suggest you also read the docs for related settings, e.g. `:h g:vimtex_quickfix_`.

**Comment by qazip** [comment]
Thank you, that fixed the issue. But no, I've exactly the same settings in nvim and gvim (I use the same vimrc).

**Comment by lervag** [comment]
I tried your example with a minimal vimrc file and was not able to reproduce. For me, gvim and neovim behaves exactly the same.
