### ISSUE TITLE
Quick-Question: How do I keep focus on vim?

### ISSUE THREAD

**Issue by qazip** [lervag/vimtex#865]
Hello, this is a quick question:

How do I keep focus on vim (gvim) after doing \lv? Default behaviour seems to be to focus the pdf window.

**Comment by lervag** [comment]
It might not be possible. Which pdf viewer are you using and on which system?

**Comment by qazip** [comment]
I'm using qpdfview and ubuntu 16.04.

**Comment by lervag** [comment]
You could use xdotool, but it becomes rather hackish. You can do something like this:

```vim
let g:vimtex_view_general_hook_view = 'MyHook'

function! MyHook()
  silent call system('xdotool windowactivate ' . v:windowid . ' --sync')
  silent call system('xdotool windowraise ' . v:windowid)
endfunction
```

Obv., you need `xdotool` installed. I recommend you play with the commands in your terminal. To see the actual window ID of your gvim session, do `:echo v:windowid`.

**Comment by aldanor** [comment]
I've tried the example above, but `MyHook()` never gets called (I'm using skim on osx, and tried using osascript to focus the terminal back, but the callback nevers seems to get triggered at all).

**Comment by aldanor** [comment]
Oh, apologies -- figured it out, it must be `g:vimtex_view_skim_hook_view` of course... wasn't obvious from the docs, had to read the source code :)

**Comment by lervag** [comment]
Yes, that's true. I haven't documented this, actually, because I found it so obscure that I thought it would just increase the noise to signal ratio of the docs. :)

**Comment by daveyproctor** [comment]
`let g:vimtex_view_automatic = 0` solved it for me.

**Comment by pochinha** [comment]
I'm having the same problem as @aldanor: the function MyHook never seems to get called. I tried both with `g:vimtex_view_general_hook_view` + `evince` and `g:vimtex_view_mupdf_hook_view` + `mupdf`.

**Comment by lervag** [comment]
Please open a new issue and follow the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md).

As you might have noticed, this issue is closed and the issue is resolved for @aldanor.
