### ISSUE TITLE
:VimtexCompile after :saveas starts compilation for old filename

### ISSUE THREAD

**Issue by camilstaps** [lervag/vimtex#866]
### Explain the issue

When you start editing a file (`vim first.tex`), save it under another name (`:saveas second.tex`) and start compilation (`:VimtexCompile`), vimtex will start latexmk on the first file(name).

1. Steps to reproduce:
  - Run `vim first.tex` (it does not need to exist)
  - Put some TeX code in it
  - `:saveas second.tex`
  - `:VimtexCompile`

2. Expected behaviour: compilation starts for `second.tex`.

3. Observed behaviour: compilation starts for `first.tex`. If `first.tex` did not exist, the `:VimtexCompileOutput` window says `Latexmk: Could not find file [first.tex].` Otherwise, you will see a PDF for `first.tex` (or errors corresponding to that file, if compilation failed).

Note: after this, even closing the file (but not vim) and opening it with `:e second.tex` does not help. The only way to recover is, as far as I know, to close vim and open the file with the new name from the start.

### Minimal working example

You can e.g. put this in `second.tex`:

```tex
\documentclass{minimal}
\begin{document}
Hello World!
\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
Thanks. Should be fixed now.
