### ISSUE TITLE
Main file detection broken in case \include is not the first word in a line

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#871]
### Explain the issue

The main file detection for multi-file projects systematically fails in case the `\include` line is not the first statement in the line of the including file. I could track this down to the function `file_reaches_current`, which is called even if a `latexmain` file exists, where I - as the uses - decided which file should always be used as the main. The regular expression used there doesn't cover all cases, as seen below in the MWE.

Is this checking really necessary, if there is a user-defined `latexmain` file?

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{article}

\begin{document}

This is the main file

\cleardoublepage\include{included}

\end{document}
```

When starting compilation in `included.tex`, this document is compiled instead of the main file, even if a `latexmain` file exists.

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
```

**Comment by lervag** [comment]
Yes, this is probably true. But I'm curious if it is not better to advice users to write the `\include` statements on separate lines. There is no reason not to, is there?

But I agree this seems unnecessary when the `.latexmain` method is used. I'll look into it.

**Comment by languitar** [comment]
Since the syntax allows this, vimtex shouldn't prevent this from working, I would say.

**Comment by lervag** [comment]
Thanks, I've fixed this now. Note, the same issue also prevented the recursive strategy from working.
