### ISSUE TITLE
Latexmain specification via buffer-local variable does not work

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#872]
### Explain the issue

The `autocmd` shown in the documentation in order to specify the main file in a multi-file document does not seem to work correctly (at least in neovim). When I manually check the existence of the variable with `let b:vimtex_main`, the variable is correctly set. However, for the contents of the function `get_main` it isn't set. I have added `echomsg`s to this function and in the scope of this function `b:vimtex_main` is not available. Hence, this step of the main file detection is ignored.

### Minimal working example

Doesn't matter. Any tex file.

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible
filetype off

call plug#begin('~/.local/share/nvim/bundle/')
Plug 'lervag/vimtex', {'for': 'tex'}
call plug#end()

filetype plugin indent on

autocmd FileType tex let b:vimtex_main = 'main.tex'
```

Neovim version:

```
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

**Comment by lervag** [comment]
Sorry, the `FileType` autocmd becomes wrong here, because vimtex will initialize before the variable gets defined. It should work if you use `BufReadPre` instead. I've updated the docs.
