### ISSUE TITLE
Infinite recursion in parser

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#875]
### Explain the issue

Create an empty file `one.tex`, and a file `file.tex` containing:

```tex
\documentclass{article}
\input{one}
\input{file}
\begin{document}
Hello
\end{document}
```

Upon opening `file.tex`, vimtex goes into an infinite loop (up to maxfuncdepth) in ` s:parser.parse`.

### Potential solution

Although vimtex's parser maintains `prev_parsed` to avoid self-loops, it only stores the most recent parsed file. So, vimtex parses one->file->one->file etc..  I believe this could be fixed simply by making `prev_parsed` a list or a dict.  I would be happy to create a PR, but wanted to check first to make sure there would be no bad side-effects.

**Comment by lervag** [comment]
Thanks, this is fixed now.
