### ISSUE TITLE
Neovim servername issue with Windows

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#877]
Forgive the lack of adherence to the issue template.

The neovim pipe servername used by `nvr` doesn't have enough backward slashes in the beginning. This is the command that vimtex generates for the compilation with my current settings.
```
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""""nvr"""""" --servername \\.\pipe\nvim-19300-0'" -e "$failure_cmd = '""""""nvr"""""" --servername \\.\pipe\nvim-19300-0'" "test.tex"
```
This generates the following output at the bottom of the log file
```
Running '"nvr" --servername \.\pipe\nvim-5116-0 --remote-expr vimtex#compiler#callback(1)'
------------

[!] Can't connect to: \.\pipe\nvim-5116-0

    The server (nvim) and client (nvr) have to use the same address.

    Server:

        Expose $NVIM_LISTEN_ADDRESS to the environment before
        starting nvim:

        $ NVIM_LISTEN_ADDRESS=\.\pipe\nvim-5116-0 nvim

        Use `:echo v:servername` to verify the address.

    Client:

        Expose $NVIM_LISTEN_ADDRESS to the environment before
        using nvr or use its --servername option. If neither
        is given, nvr assumes "/tmp/nvimsocket".

        $ NVIM_LISTEN_ADDRESS=\.\pipe\nvim-5116-0 nvr file1 file2
        $ nvr --servername \.\pipe\nvim-5116-0 file1 file2
        $ nvr --servername 127.0.0.1:6789 file1 file2

    Use any of the --remote*silent options to suppress this message.

[*] Starting new nvim instance with address: \.\pipe\nvim-5116-0
```
Now, to fix this, I have wrapped a `vimtex#util#shellescape` call around `v:servername` in the construction of `l:func` in `s:compiler.build_cmd()`. You probably want to handle this another way, though. Doing this, however, yields the following command which works just fine (callbacks execute gracefully).
```
    cmd: set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""""nvr"""""" --servername "\\\\.\\pipe\\nvim-16876-0" --remote-expr "vimtex#compiler#callback(1)"'" -e "$failure_cmd = '""""""nvr"""""" --servername "\\\\.\\pipe\\nvim-16876-0" --remote-expr "vimtex#compiler#callback(0)"'" "test.tex"
```

**Comment by lervag** [comment]
I'm not quite sure what is the correct solution here. It seems safe to use a simple shellescape on the `v:servername` part, but I'm not quite sure. I've tested on Linux with both neovim, vim and gvim, and it seems to work as expected.

However, since it will solve your problem, and since it seems to work well, I think we'll just try to add this as a solution. I would expect there to be new issues if this does breaks things on other systems...

**Comment by fuzzybear3965** [comment]
Yeah, I'm not sure what the best solution is, either. An `has('unix')` conditional may work but it's ugly and may be unnecessary.

I'm with you. We'll take a wait-and-see approach to this.

**Comment by lervag** [comment]
Sounds good.
