### ISSUE TITLE
Perl and latexmk not killed after :VimtexStop

### ISSUE THREAD

**Issue by fuzzybear3965** [lervag/vimtex#882]
Again, sorry for not adhering to the issue template. I'm posting this issue mostly as a reminder to myself so I remember to look at this issue later, when I have more time.

Currently, cycling a compilation (VimtexCompile -> VimtexCompile) spawns both a perl and a latexmk process when the compilation is toggled on. However, these processes don't terminate/get killed when the compilation is toggled off.

So, after `n` cycles of compilation and stopping compilation I have `n` perl.exe and `n` latexmk.exe processes running. This is ugly.

Note: This is being reported for nvim v0.2.1 (with nvr), the most recent version of vimtex and a Windows 10 machine.

**Comment by lervag** [comment]
> Again, sorry for not adhering to the issue template. I'm posting this issue mostly as a reminder to myself so I remember to look at this issue later, when I have more time.

Ok, thanks. I'll leave this be until you update with more information later. Note: If you want me to look at it, please give me simple instructions for installing neovim and nvr on windows. :)

**Comment by fuzzybear3965** [comment]
I'll document that, here, to help you and any other unfortunate soul who stumbles upon this cobwebbed thread. The following instructions assume a working version of Vim on Windows, a Python installation (with pip), and vimtex (so, latex(mk) and perl, too) configured to work within vim.

#### 1. Setup neovim (and its corresponding init.vim)
1. Install neovim (this isn't so hard).
1. Edit the $XDG_CONFIG_HOME/init.vim (usually C:\Users\\<Username\>\\AppData\Local\nvim\init.vim) to include:  
   - `source ~/vimfiles/vimrc` (or wherever your root vimrc file is located) and
   - `let g:python_host_prog= 'C:\Python27\Scripts\python.exe'` and `g:loaded_python_provider=0` or (inclusively)
   - `let g:python3_host_prog= 'C:\Python36\Scripts\python.exe'` and `g:loaded_python3_provider=0`

To be clear, my `init.vim` file currently is
```vim
source ~/vimfiles/vimrc
let g:python_host_prog= 'C:\Users\JohnRinehart\Envs\python2\Scripts\python.exe'
let g:python3_host_prog= 'C:\Users\JohnRinehart\Envs\python3\Scripts\python.exe'
g:loaded_python_provider=0
g:loaded_python3_provider=0
```

#### 2. Install neovim-remote
Then, use pip to install neovim-remote: `pip install neovim-remote`.

That should be all you need to get started with neovim on Windows with vimtex. @lervag, if you try this and it doesn't work for you then just let me know what's not working and I can try to help out. I'm going to try to look at this issue more on Saturday/Sunday.

**Comment by lervag** [comment]
Thanks for that I'll be needing this if (or when) you want me to look more closely into this issue.

**Comment by fuzzybear3965** [comment]
I'll be looking at this tomorrow. I'll report more then.

**Comment by fuzzybear3965** [comment]
Okay, I have no idea what's happening. But, I have observed some different behavior between `gvim` and `neovim`.

Starting continuous compilation with `neovim` spawns a master `cmd.exe` process ("master" means that the spawned process' PID is stored in `b:vimtex.compiler.get_pid()`). This `cmd.exe` process spawns *another* `cmd.exe` process which seems to spawn `latexmk` and `perl` processes. When the master process is killed using `b:vimtex.compile.stop()` it only kills the head `cmd.exe` process leaving the  children `cmd.exe` and grandchildren `latexmk` and `perl` processes still active.

However, starting continuous compilation with `gvim` spawns one master `cmd.exe`. This process is the master of the `latexmk` and `perl` processes. So, when it's killed the `latexmk` and `perl` processes are killed automatically.

I don't know how to go about fixing this.

**Comment by lervag** [comment]
Strange.

Which backend is used by neovim? (See output of `\li`.) You could try to set it to `process`. See `:h g:vimtex_compiler_latexmk` for more info on the backend stuff.

**Comment by lervag** [comment]
I guess this is probably it. You could look in `compiler/latexmk.vim` around line 477. Perhaps you can tweak the `l:cmd` variable for windows? E.g., you could try to remove the `cmd /s /c` part and the surrounding `"`s.

**Comment by fuzzybear3965** [comment]
I was using the `nvr` backend. My vimtex vimrc options are given below. I changed the first line from `{'backend': 'nvim',}` to `{'backend': 'process'}` and that didn't work... at all. neovim hangs at `:call vimtex#compiler#compile()`.

```vim
let g:vimtex_compiler_latexmk = {'backend' : 'nvim',}
nmap <F9> <plug>(vimtex-compile)
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_imaps_leader = '@'
if has("win32")
   let g:vimtex_view_general_viewer = 'SumatraPDF'
endif
```

I'll try to muck around in `compiler/latexmk.vim` now.

**Comment by fuzzybear3965** [comment]
Okay, yeah, it looks like vimtex and neovim has this problem, for now: https://github.com/neovim/neovim/issues/6530. Your use of [`jobstop()`](https://github.com/lervag/vimtex/blob/bfe4f4eafc78839fb60a10d7881c8a36c84885ce/autoload/vimtex/compiler/latexmk.vim#L505) [doesn't kill job IDs](https://github.com/neovim/neovim/issues/6530). Any edits to `latexmk.vim` won't fix this. `job_stop()` [seems to kill child processes](https://github.com/neovim/neovim/issues/6530#issuecomment-294321212).

**Comment by lervag** [comment]
Thanks for the research work. This does seem relevant.

Note, though, that the `process` backend should work also in neovim. Thus you could also investigate this part. (It does work for neovim on Linux, anyway).

**Comment by fuzzybear3965** [comment]
`process` doesn't work because `nvim.exe` doesn't accept the `--servername` switch. I think that's why you had us install `nvr` (according to the docs). To be clear (said another way) the `process` backend right now uses `nvim.exe` for the callbacks, which doesn't accept the `--servername` switch. Here's the output of `\li` for my system.

```
start /b "cmd /s /c "set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""""C:\Users\JohnRinehart\Programs\Neovim\bin\nvim.exe"""""" --servername "\\\\.\\pipe\\nvim-12608-0" --remote-expr "vimtex#compiler#callback(1)"'" -e "$failure_cmd = '""""""C:\Users\JohnRinehart\Programs\Neovim\bin\nvim.exe"""""" --servername "\\\\.\\pipe\\nvim-12608-0" --remote-expr "vimtex#compiler#callback(0)"'" "test.tex" >C:\Users\JOHNRI~1\AppData\Local\Temp\nvimNxX91x\0""
```

I'll try changing the backend process to use `nvr`, but I won't be able to get to this until tomorrow.

**Comment by lervag** [comment]
Ah, these are different settings. Try:

```vim
let g:vimtex_compiler_latexmk = {'backend' : 'process'}
let g:vimtex_compiler_progname = 'nvr'
```

Also, if this doesn't work, you could also try to disable callbacks (just to check if the backend works), i.e.

```vim
let g:vimtex_compiler_latexmk = {
    \ 'backend' : 'process',
    \ 'callback' : 0,
    \}
```

**Comment by fuzzybear3965** [comment]
Okay, I have done this, but the neovim hangs when running `vimtex-compile` (the message hangs at `:call vimtex#compiler#compile()`, focus is locked to the message). The only way to regain control of neovim is to open up the task manager and end the `cmd.exe` process spawned by `vimtex-compile`. The command listed by `li` is below. I've also included the contents of my `vimtex.vimrc` file.

##### \li cmd: output
```
start /b "cmd /s /c "set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" "test.tex" >C:\Users\JOHNRI~1\AppData\Local\Temp\nvimJ1nPLi\0""
```
##### vimtex.vimrc
```vim
nmap <F9> <plug>(vimtex-compile)
let g:vimtex_compiler_latexmk = {'backend' : 'process', 'callback': 0,}
let g:vimtex_compiler_progname = 'nvr'
if has("win32")
   let g:vimtex_view_general_viewer = 'SumatraPDF'
endif
```

Stripping the `start /b "` and terminating `"` from the command and running in the command line works just fine. However, copy and pasting the *entire* command results in the error shown in the screenshot below:

![image](https://user-images.githubusercontent.com/6321578/27888594-e7e1736e-61b4-11e7-9227-115fb5123411.png)

Now, clicking "ok" on this error dialog box results in a successful run of the command just as if I had stripped out the `start /b "` and terminating `"`.

So, I'm thinking what's happening is that an error is generated when `vimtex` spawns a `cmd.exe` to start the compilation. But, the process manager has no way of "clicking that box" (ignoring the error) like I can do when I run the command in the command line manually. So, if we fix the problem that's generating the `cannot find 'max_print_line=2000` error we will probably be okay.

**Comment by fuzzybear3965** [comment]
Okay, the issue of the hang seems to be fixed by changing [`let l:cmd = 'start /b "' . cmd . '"''`](https://github.com/lervag/vimtex/blob/2cef11aeb2396e498213976c140b5711f19a73df/autoload/vimtex/process.vim#L159) to `let l:cmd = 'start /b ' . cmd . ''`. So, I re-enabled callbacks. But, the callback fails with the output (`\lo`):
```
Latexmk: All targets (test.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
Evaluation failed: vimtextest.texcompilertest.texcallback(1)
```
I'm a bit confused about that line and where it comes from (what's `vimtextest`?).

The `cmd` shown with `\li` is shown below.

##### \li cmd output
```
start /b cmd /s /c "set max_print_line=2000 & latexmk -verbose -pdf -file-line-error -synctex=1 -interaction=nonstopmode -pvc -e "$pdf_previewer = 'SumatraPDF'" -e "$success_cmd = '""""""nvr"""""" --servername "\\\\.\\pipe\\nvim-6964-0" --remote-expr "vimtex#compiler#callback(1)"'" -e "$failure_cmd = '""""""nvr"""""" --servername "\\\\.\\pipe\\nvim-6964-0" --remote-expr "vimtex#compiler#callback(0)"'" "test.tex" >C:\Users\JOHNRI~1\AppData\Local\Temp\nvimjyuxGP\0"
```

**Comment by lervag** [comment]
I'm sorry for not replying sooner. I have to admit I really dislike issues related to Windows. I don't know enough about how the cmd.exe stuff works, and I don't regularly use Wndows, thus the test cycle and work on solving these issues really is not something I like.

The problems are generally due to escaping hell. Everything needs to be escaped properly. I have the impression that this works as expected on Windows with Vim, though...

I would be very happy if someone who had the knowhow could help with finding the correct command lines for running these things on Windows, both for Vim and neovim...

**Comment by fuzzybear3965** [comment]
Don't be sorry; we're both busy. I'm actually very busy this week and would have liked to inspect this issue a bit more. Yeah, well, the escaping issues seem to require access to different versions of Windows and spaced path names in order to verify.

I think the best approach is to fix something for each person as the issue comes (whatever that is), possibly undoing previous fixes to eliminate the most recent issue (possibly commenting out previous fixes, when applicable).

I will spend some time to figure out how best to form these command lines from vim. I'll do some experimenting at the end of this week (I've made a note in my personal calendar).

Please keep this issue open and ping me if it's been inactive for over 2 weeks.

**Comment by lervag** [comment]
Thanks! I really appreciate your help here!

**Comment by fuzzybear3965** [comment]
Agh, I hate this. I need an "extension" to address this issue. I'm absolutely swamped over this next week. I thought I'd be more free this weekend but I just got assigned some grading work and I still have to finish a huge assignment.

I haven't forgotten about this.

**Comment by lervag** [comment]
Thanks for the notice. For me there is no rush, so don't worry!

**Comment by fuzzybear3965** [comment]
Okay, minor update. It seems this issue has evaporated. But, I don't want to close it, yet, until we've figured out what made it go away.  We have about a month's worth of commits to check out. When I get a minute to breathe I'll check out a commit from the end of June and confirm the problem still exists with my current vimrc settings.

If I check out one of those commits and I can't replicate the problem then I'll have to throw my hands up in the error and declare incompetence.

If I check out one of those commits and I *can* replicate the problem then I'll work through the commit history to find the magic change.

**Comment by lervag** [comment]
I've improved the `:VimtexInfo` command, which should now also show some simple system information. I think it should work on windows as well, but I have not tested. Please let me know what you think. In particular, this should show the windows version, which is useful for future debugging of things similar to the current issue.

**Comment by lervag** [comment]
Since I have no idea how to procede on this issue, I'm deciding to close as `won't fix`. I _will_ continue to read new comments and updates, and I will be happy to assist in future developments. However, due to my lack of knowledge on Windows systems, as well as my limited access to a Windows system, I think it is better to acknowledge that vimtex support for windows is limited.

I really do hope you are able to figure some stuff out, @fuzzybear3965! If you have more updates, feel free to reopen. In any case, I do read updates to all issues, regardless of the state.

**Comment by fuzzybear3965** [comment]
No problem, @lervag. I'm running a couple of tests, now. I'll let you know if I find anything.

**Comment by lervag** [comment]
There is finally some related activity on neovim, see [here](https://github.com/neovim/neovim/issues/6530#issuecomment-370708832).

**Comment by fuzzybear3965** [comment]
I see. This is good. I'd like to wait until the next release (0.2.3) to test this fix (assuming it's included in the next release). I can't find their CI builds. I'll try to keep my eye on this issue, but no guarantees (life is hectic). Ping me if you want me to run some tests. I'm happy to help.

**Comment by justinmk** [comment]
For reference, https://github.com/neovim/neovim/issues/6530 should be fixed on Nvim HEAD.

> I can't find their CI builds.

here: https://github.com/neovim/neovim/releases/
