### ISSUE TITLE
Glossaries completion does not work when using loadglsentries

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#883]
### Explain the issue

Glossary entries from the `glossaries` package are not completed in case one uses the `loadglsentries` command from the package to reference a file that provides the entries.

Completion for the `\gls*` commands works, however, triggering omni completion after a `\gls{` results in `Pattern not found`.

### Minimal working example

`main.tex`:

```tex
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[xindy]{glossaries}

\loadglsentries{entries}
\makeglossaries{}

\begin{document}

This is not \gls{res}. But \gls{foobar}.

\printglossary{}

\end{document}
```

`entries.tex`:

```tex
\newglossaryentry{res}
{
    name={resource-awareness},
    description={Foo foo bar}
}
\newglossaryentry{foobar}
{
    name={foobar},
    description={Foo foo bar}
}
```

`latexmkrc`:

```perl
add_cus_dep('glo', 'gls', 0, 'makeglossaries');
add_cus_dep('acn', 'acr', 0, 'makeglossaries');
sub makeglossaries {
    system("makeglossaries \"$_[0]\"");
}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
```

**Comment by languitar** [comment]
I have found the issue. `input_re` given to the parser in `complete.vim` is replaced in `parser.new` with `input_re_tex`.

**Comment by lervag** [comment]
Thanks, you were right about the problem, but not quite right about the fix. The call from `complete.vim` to the parser was as intended, instead, the parser should use the supplied input regex. My fix addresses this.

**Comment by lervag** [comment]
Note, though, that I greatly appreciate your effort, and that it helped me solve the issue faster than I otherwise would have. So thanks!

**Comment by languitar** [comment]
I was already suspecting that the real fix was your solution, but I wasn't so sure how to implement this.
