### ISSUE TITLE
Minted environment not recognised within a chapter

### ISSUE THREAD

**Issue by gcollura** [lervag/vimtex#886]
Syntax highlighting in minted environment is not working if defined inside a `chapter` (from `report` document class).

![selection_417](https://user-images.githubusercontent.com/787586/27642641-b70bc540-5c1f-11e7-8317-aba53fb0f114.png)

Without `\chapter`:
![selection_416](https://user-images.githubusercontent.com/787586/27642629-ab41f43c-5c1f-11e7-8eec-3fc75c11d6b3.png)

I don't have any special configuration, if it is not reproducible, I'll upload more information if needed.

Thank you very much for this awesome plugin!

**Comment by lervag** [comment]
Thanks, this should work now. Let me know if you find similar issues, as I am not sure this will work in all cases.

**Comment by gcollura** [comment]
Thanks!
I noticed that it still breaks if you have:
```latex
\begin{document}
\chapter{...}
\section{...}
\begin{minted}{text}
Hello world
\end{minted}
\end{document}
```
but it works fine if the minted env is between `\chapter` and `\section`. It also work if you have `\chapter` with `\subsection` (and `\subsubsection`).

**Comment by lervag** [comment]
I found a slightly different way that seems to solve this for all kinds of part commands. Try now.

**Comment by gcollura** [comment]
Yes, it seems to be working in all cases now. Thanks!

**Comment by lervag** [comment]
No problem :)
