### ISSUE TITLE
Support for LaTeX/MathJax in Markdown files

### ISSUE THREAD

**Issue by cpassos** [lervag/vimtex#889]
I frequently use in Markdown and MathJax to write a pdf with math equations, because I find more convenient most of the times. Support for at least basic indentation in math mode (inside double $) would be neat.

**Comment by lervag** [comment]
There are several plugins for markdown and similar available, see e.g. [this VimAwesome search](http://vimawesome.com/?q=markdown).

However, vimtex is a LaTeX filetype plugin, not a markdown plugin, and so your feature request does not make sense here.
