### ISSUE TITLE
Quickfix window is closed after compilation if g:vimtex_quickfix_mode = 0

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#891]
### Explain the issue

When setting `let g:vimtex_quickfix_mode = 0` and manually opening the quickfix window, it is closed once compilation finishes. I would expect that vimtex doesn't change state in any case when the variable is set that way.

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}
narf{} % creates a warning to be put into quickfix list
\end{document}
```

1. `vim -u minimal.vim -e thatfile.tex`
1. `:VimtexCompileSS`
1. After compilation finished / failed, `:cwindow`
1. `:VimtexCompileSS` -> cwindow disappears

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

let g:vimtex_quickfix_mode = 0
```

**Comment by lervag** [comment]
Thanks, fixed now.

**Comment by languitar** [comment]
Thanks. works well now.

**Comment by languitar** [comment]
This started to reappear in case there are no issues in the current compilation run.

**Comment by lervag** [comment]
Do I understand correctly that you expect vimtex never to close the quickfix window, even in the case where there are no errors?

**Comment by lervag** [comment]
I don't think there has been any changes to this since 4cb32e8, and so I think think anything has reappeared. Instead, I think my previous fix did not work as you thought it did.

**Comment by lervag** [comment]
I also think that changing as you propose, if I understand correctly, should also lead to a better description in the docs, where it is only stated the vimtex does not open the qf window automatically, there is nothing about closing.

**Comment by languitar** [comment]
Weird, I thought I verified that behavior at that time. But yes, I don't want vimtex to mingle with the quickfix window at all. I don't like to see the window layout jumping around.

**Comment by lervag** [comment]
Ok, I think it works as expected now.
