### ISSUE TITLE
Minimum structure to activate plugin?

### ISSUE THREAD

**Issue by LindyBalboa** [lervag/vimtex#892]
So I'm confused about some behavior.

running `vim mynewfile.tex` does not trigger the plugin into activating. Saving the empty file and loading again does not trigger it. I can only seem to get it to trigger after having written, saved, and re-opened a compileable file. I don't really have to patience to play an elimination game, so I would like to ask: How exactly does the plugin detect that it should be activated? What are the minumum features we need so that all of the setup/init happens?

Thanks

**Comment by languitar** [comment]
What does `set ft` say in the cases in which it doesn't work? How do you notice that things do not work?

**Comment by lervag** [comment]
```vim
let g:tex_flavor = 'latex'
```

If you had bothered to read the introductory parts of the documentation this would not have been confusing.
