### ISSUE TITLE
Compilation errors/feedback not displayed in neovim

### ISSUE THREAD

**Issue by guiniol** [lervag/vimtex#893]
### Explain the issue

In neovim, vimtex doesn't show the compilation errors and doesn't show the "compilation finished" message. Forward/backward searches work, and the pdf is updated after a compilation.
I don't know if this is known issue and if there's a workaround. I couldn't find anything regarding it.

Steps to reproduce:
1. `nvim -u minimal.vimrc minimal.tex`
2. Start continuous compilation: `<leader>ll`
3. Wait for the pdf to open
4. See that there is no message about the compilation finishing.

Alternatively, make an error in `minimal.tex` and see that no error is displayed. Trying to manually open the quickfix window shows `No Errors` and doesn't open the quickfix window.

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_latexmk_progname = 'nvr'
```

**Comment by clason** [comment]
Works for me (neovim and vimtex master, neovim-remote 1.7.1).

**Comment by guiniol** [comment]
@clason it works with the minimal configuration I posted? I'm with neovim 0.2.0,neovim-remote 1.7.1 and vimtex on master.

**Comment by lervag** [comment]
@guiniol Did you update the option as @clason suggested?

**Comment by guiniol** [comment]
@lervag Not sure. Which option?
