### ISSUE TITLE
Completion for local commands ((re)?newcommand)

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#894]
It would be nice if vimtex could complete commands that are defined inside the document itself via `(re)?newcommand`.

**Comment by clason** [comment]
That would be nice, but probably not easy to implement...

**Comment by lervag** [comment]
I think I can manage that. I would have to parse the preamble for `\newcommand`s, which shouldn't be too difficult. The main difficulty is to decide how to manage file updates. I.e., should I parse the preamble every time there is a change to the file, or every time you perform a completion? Obviously, this question can't be answered until I have some benchmarking of the parsing speed. My guess is that we can update on file changes.

**Comment by lervag** [comment]
Just to make sure: Would it be enough to parse the preamble? I know one can define commands also inside the documents, but do anyone really do that?

**Comment by languitar** [comment]
I have some cases where I have defined commands inside the document because they are valid only for a local scope (for instance to prevent repetition when printing repetitive data in a specific paragraph format, where the format is then defined in the new command).

**Comment by lervag** [comment]
Ok, I see. The current implementation parses the preamble on every complete, which seemed to work well. If we were to parse the entire manuscript, I think we need to add some caching. The simplest would be to cache once only when loading vimtex (trivial). Else we could cache on every file change, either loading all candidates whenever any file has changed (simple), or loading only candidates from the file that was changed (slightly more complex).

**Comment by languitar** [comment]
If possible, the second option, of course, sounds best. But I don't know how much overhead that would be.

**Comment by lervag** [comment]
I'm looking at the most advanced option now. I don't think I'll complete right now, but it is an interesting challenge. :)

**Comment by lervag** [comment]
Ok, I added the simple version now. It seems to work well enough. Let me know what you think.

**Comment by languitar** [comment]
In a quick test this seems to be working. :)

**Comment by lervag** [comment]
Great! :)
