### ISSUE TITLE
Highlighting artefacts with g:vimtex_syntax_minted

### ISSUE THREAD

**Issue by aldanor** [lervag/vimtex#895]
Here's the minimal vimtex config:

```vim
let g:vimtex_syntax_minted = [
      \ { 'lang': 'cpp', 'environments': ['cppcode'] },
      \ { 'lang': 'python', 'environments': ['pythoncode'] },
      \]
```

For some reason, Python environments (all other languages are ok, far as I've noticed) have this highlighting problem:

<img width="156" alt="screen shot 2017-07-04 at 22 21 11" src="https://user-images.githubusercontent.com/2418513/27843017-5b15e6de-6107-11e7-83d0-6d18808d07c9.png">

Highlighting within the environment itself is fine; it's just the `\begin` part.

**Comment by lervag** [comment]
See `:h g:vimtex_syntax_minted`. In particular note the `ignore` key and how it is used for the python example:

```vim
let g:vimtex_syntax_minted = [
      \ {
      \   'lang' : 'python',
      \   'ignore' : [
      \     'pythonEscape',
      \     'pythonBEscape',
      \     ],
      \ }
      \]
```

----

To be more specific: The problem here is that the first `\b` is detected as a `pythonEscape` syntax element. By ignoring the syntax group we evade this problem.
