### ISSUE TITLE
Wrong file name in error log for multi-file scenario in case of internal log parser

### ISSUE THREAD

**Issue by nmder** [lervag/vimtex#896]
Vimtex internal error log parser is showing wrong filename in quickfix window for multifile scenario.

### Steps to Reproduce
1. Create a TeX file called **main.tex** having the content below.
```tex
\documentclass{book}

\begin{document}

\include{zebras}

\end{document}
```
2. Create another file called **zebras.tex**, having the content below, in the same directory as **main.tex**.
```tex
\chapter{zebras}
\section{Section Stripe}

I am a zebra. \cite{ios}
```
3. Compile **main.tex** using default compilation key-binding _&lt;localleader&gt;ll_.
4. Open quickfix window using :cw.

### Expected behaviour
The following output is expected:
```
zebras.tex|5 warning| LaTeX Warning: Citation `ios' on page 1 undefined on input line 5.
test.tex|| LaTeX Warning: There were undefined references.
```
### Observed behaviour
I got:
```
test.tex|5 warning| LaTeX Warning: Citation `ios' on page 1 undefined on input line 5.
test.tex|| LaTeX Warning: There were undefined references.
```

### Minimal vimrc file

```vim
call plug#begin('~/.vim/bundle')
Plug 'lervag/vimtex', { 'for': 'tex' }
call plug#end()

" vimtex options
let g:vimtex_fold_enabled = 1
let g:vimtex_fold_manual = 1
let g:vimtex_view_enabled = 1
let g:vimtex_view_method = 'zathura'
let g:vimtex_quickfix_mode = 0
let g:vimtex_quickfix_open_on_warning = 0
let g:vimtex_quickfix_method = 'pplatex'
let g:vimtex_compiler_latexmk = {
            \ 'backend' : 'jobs',
            \ 'background' : 1,
            \ 'build_dir' : '',
            \ 'callback' : 1,
            \ 'continuous' : 1,
            \ 'executable' : 'latexmk',
            \ 'options' : [
            \   '-pdf',
            \   '-bibtex',
            \   '-verbose',
            \   '-file-line-error',
            \   '-synctex=1',
            \   '-interaction=nonstopmode',
            \ ],
            \}

```
### Note
**pplatex** is generating expected output:
```
zebras.tex|5 warning|  Citation `ios' on page 1 undefined
test.tex|| There were undefined references.
```
It's not perfect for all cases, but this not the forum for that discussion.

**Comment by lervag** [comment]
Yes, this is a known issue. The problem is that the file path provided in the latex log is not consistently written on a single line, i.e., it may contain a line break/hard wrap. And the errorformat in Vim relies on a stack of paths that must be properly maintained. If, for some reason, one is not able to parse all the paths correctly, then this may screw up everything.

Thus, I've chosen to ignore this, because at least we get _consistent_ results, even though some entries will (unfortunately) be wrong.

This is actually the main reason that I relatively recently implemented support for using pplatex as a backend.

So, the conclusion is that I am aware of this problem, and that I will unfortunately leave it unsolved. :\

**Comment by nmder** [comment]
Thanks for the reply!! :)

**Comment by gauteh** [comment]
Is there a way to specify `pplatex` in a way that this works?

P.S. For other users: syntastic usually gives me the right file/line number for the same error.

**Comment by gauteh** [comment]
Actually, I was using my own makefile - when using Vimtex to compile it works fairly well.. disregard previous comment.

**Comment by lervag** [comment]
Disregarded. :)

Btw: If you should have other issues, please be more specific the next time. I would not have been able to help you for your first comment without more details. In particular, the [issue template](https://github.com/lervag/vimtex/blob/master/ISSUE_TEMPLATE.md) gives a good description of how to provide the details necessary for me to help.
