### ISSUE TITLE
Look for latexmkrc in $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by jfrankenau** [lervag/vimtex#897]
Newer versions of latexmk also allow the `latexmkrc` file to be in `$XDG_CONFIG_HOME/latexmk/latexmkrc`. It would be nice if vimtex would look there as well.

**Comment by lervag** [comment]
Vimtex does not really look up the latexmkrc files, thus this should already work. If it works in the terminal, then it should also work from Vim.

**Comment by jfrankenau** [comment]
Does it? What about https://github.com/lervag/vimtex/blob/bfe4f4eafc78839fb60a10d7881c8a36c84885ce/autoload/vimtex/compiler/latexmk.vim#L79.

**Comment by lervag** [comment]
Sorry, you're right. I'll look into this later. Gotta sleep now. :)

**Comment by jfrankenau** [comment]
Thank you. No problem.

**Comment by lervag** [comment]
Bah. I think this should do it... If not, I'll look into it this weekend.
