### ISSUE TITLE
VimtexDocPackage does not work when cursor is on the last character of a brace-less command

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#899]
### Explain the issue

Pressing K or calling VimtexDocPackage when the cursor on the last character of a latex command does not bring up documentation.  In the MWE below, I expect the amsmath documentation to be launched, but this does not occur when the cursor is on the `t` of `\lvert`.  Also, `vimtex#cmd#get_current()` there returns `{}`.

### Minimal working example

```tex
\documentclass{article}
\usepackage{amsmath}

\begin{document}
\lvert 10 \rvert
\end{document}
```

### Minimal vimrc file

```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

nnoremap q :qall<cr>
nnoremap <space> :echo vimtex#cmd#get_current()<cr>

augroup Testing
  autocmd!
  autocmd VimEnter *.tex normal 5ggeKy
augroup END
```

**Comment by lervag** [comment]
Ok, now I think this is solved in a more proper manner. Let me know if you should find a new case where it fails.
