### ISSUE TITLE
E65: Illegal back reference in .vimtex#paths#relative

### ISSUE THREAD

**Issue by etnoy** [lervag/vimtex#913]
I get this error when opening my tex file:

```
Error detected while processing function vimtex#init[5]..<SNR>145_init_state[1].
.vimtex#state#init[9]..432[29]..438[5]..vimtex#paths#relative:
line    7:
E65: Illegal back reference
E65: Illegal back reference
E65: Illegal back reference
E65: Illegal back reference
E65: Illegal back reference   
``` 
(last line repeated many times).

I traced the issue and found that line 25 in autoload/vimtex/paths.vim has the following:
`substitute(l:target, '^' . l:common, '', '')`

Why would this be an illegal back reference?

Well, I'm on windows, and the path to the tex file contains "Files\2016-2017\Tex". Note that windows implies backslashes, and the directory "2016-2017" begins with a number. Therefore, vim interprets the string "\2016" as a regex back reference, stops and throws the error. 

I'm not even sure that vimtex#paths#relative has the expected behavior on windows as all backslashes are interpreted as custom commands. This must be tested.

Workaround: moving the tex file to a folder where no folder begins with a number :)

**Comment by lervag** [comment]
Ah, another windows problem... :p

I think you have properly identified the issue here. Could you try to add `set noshellslash` at the beginning of the function and report back if it works?

**Comment by etnoy** [comment]
Unfortunately, that did not work. Same error still happens.

**Comment by etnoy** [comment]
The file names are given as string arguments to that function, I believe noshellslash must be set in the higher-level function.

**Comment by etnoy** [comment]
Good, it's working here. No errors on startup! :)

**Comment by lervag** [comment]
Great, good to hear!
