### ISSUE TITLE
Wishlist: Ignore spelling in more fields

### ISSUE THREAD

**Issue by etnoy** [lervag/vimtex#914]
A great feature about vimtex is that it (in contrast to competing packages) does recognize commands like \citeauthor and turns off spell check for the data contained within.

There are a few other places where I would find it useful to turn off spell checking:

- glossaries package, especially the commands \gls, \glspl etc.
- column alignment descriptors in table environments
- many fields in .bib files (basically all except abstract and title).

Thanks

**Comment by lervag** [comment]
I guess this should be possible, but I would appreciate if you could be specific about exactly which commands.

I have not written a syntax file for bib files, and I don't really want to do that. I propose that you send an email to Bernd Feige (see `:e $VIMRUNTIME/syntax/bib.vim` for his contact info) and ask him to fix this "upstream". If he would fix it, it would be fixed for all Vim users.

**Comment by etnoy** [comment]
Thanks, I'll get back with more details.

**Comment by lervag** [comment]
I also think, btw, that it could be best if you sent an email to Charles E. Campbell about spell checking. The same reason: If he would be willing to updatet the main syntax file, it would be fixed for all Vim users.

If he does not want to add this, then I will add it to vimtex.

**Comment by lervag** [comment]
(And again, see `:e $VIMRUNTIME/syntax/tex.vim` for contact info to Dr. Campbell.)

**Comment by lervag** [comment]
In the meantime, I'm closing this.
