### ISSUE TITLE
vimtex indent and highlighting confused by \big] in mathtools-style paired delimiter

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#916]
### Explain the issue

I frequently use manually-sized mathtools style paired delimiter like `\norm[\big]{x}` which typesets a norm with `\bigl` and `\bigr` double bars.  However, vimtex treats `\big]` as an unpaired delimiter no matter what, which causes problems with indenting and syntax highlighting.  The following animation illustrates the issue:

[![asciinema.org](https://asciinema.org/a/gI4f8TaD1kU7MMm0VtrQnvJqX.png)](https://asciinema.org/a/gI4f8TaD1kU7MMm0VtrQnvJqX?autoplay=1)

Indenting is the major problem, while highlighting is only a tiny inconvenience.  I realize there could be no easy fix.  Possible solutions may be to treat `\big]` as normal text if there is no corresponding `\big[`, or (with an option) never treat `\big]` as a delimiter (since I most always use `\bigr]` in the context of delimiters).

### Minimal working example

```tex
\documentclass{minimal}
\usepackage{mathtools}

\DeclarePairedDelimiter{\norm}{\lVert}{\rVert}%

\begin{document}

Hello World!
\[
\norm[\big]{10}
\norm[\Bigg]{10}
\]

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
The simple solution would be to remove support for matching delimiters with the `\big` family of modifiers. That would solve this issue, but I think a lot of people would not like it...

However, it seems like a lot of work to fix this in any other ways. :\

**Comment by lervag** [comment]
I'm tempted to implement the "easy" way here, because it sort of feels right as well...

**Comment by andymass** [comment]
I misunderstood what exactly the `extend(` was doing to the `g:vimtex_delim_list` option in the delimiter code.  It turns out if I manually set `g:vimtex_delim_list` to the default without `\big`,\bigg`, etc the indenting works as expected (at least like the "easy" way).  So, I should have read the docs more carefully to notice that I can override, not merely extend.

The syntax highlighting is still "wrong" for `\norm[\big]{}` since `[` is treated as `texMathZoneW` but `\big]` is `texMathDelim`.

**Comment by lervag** [comment]
Yes, I also noticed that the syntax highlighting is still wrong. However, this is not due to vimtex, but to the syntax plugin by Charles Campbell. You could send him an email (see `:e $VIMRUNTIME/syntax/tex.vim` for contact details).

I also forgot that the `g:vimtex_delim_list` option allows you to fix this on your end, and so I don't think there is a need for any changes. Agreed?

**Comment by andymass** [comment]
For sure.  Thank you!
