### ISSUE TITLE
Need autocomplete help about nvim-completion-manager

### ISSUE THREAD

**Issue by ashfinal** [lervag/vimtex#917]
vimtex is really wonderful plugin for tex. 👍 

I noticed in vimtex document you add `vimtex-complete-neocomplete`, `vimtex-complete-deoplete`, but without `nvim-completion-manager`. As far as I see, [nvim-completion-manager](https://github.com/roxma/nvim-completion-manager) is also a wonderful completion engine, which have better built-in completion sources, lots of third-party sources, and scoping sources feature.

I'm wondering how to make vimtex autocompletion work with nvim-completion-manager. Could you please kindly add some document for it?

**Comment by lervag** [comment]
Done. And thanks for the kind words :)

**Comment by lervag** [comment]
(Btw: If you should be able to find some better way of defining the ncm source, let me know!)

**Comment by ashfinal** [comment]
Wonderful, now it just works! 

I don't know much about vimscript, but I can help spreading the words. ❤️

**Comment by lervag** [comment]
:)
