### ISSUE TITLE
Package fixltx2e Warning: fixltx2e is not required with releases after 2015 

### ISSUE THREAD

**Issue by Chiel92** [lervag/vimtex#919]
The warning 

```
main.tex|| Package fixltx2e Warning: fixltx2e is not required with releases after 2015 All fixes are now in the LaTeX kernel. See the latexrelease package for details.
```

is always present in the quickfix window. Is this a known problem, and are there ways to mute this message?

**Comment by lervag** [comment]
I've never seen this warning before. You have obviously loaded the `fixltx2e` package, either explicitly or through one of the other packages or the documentclass. Are you able to make a minimal tex example where this happens?

**Comment by Chiel92** [comment]
Me being a latex noob thought it had something to do with the tex installation, instead of the packages loaded by my document. I've tracked down the dependencies of my document (I use a standard preamble) and it indeed appears the package fixltx2e is included. Thanks for the hint!
