### ISSUE TITLE
vim-airline status bar not updated/disappears when using vimtex

### ISSUE THREAD

**Issue by dnivra** [lervag/vimtex#926]
When I'm using both [vim-airline](https://github.com/vim-airline/vim-airline) and vimtex, the status bar of vim-airline does not get updated. I disable vimtex and everything works fine. I am using the latest vimtex and vim-airline with nvim 0.1.7 on Ubuntu 16.04.

1. Steps to reproduce

- Open minimal TeX file below in neovim using minimal vimrc below.
- Navigate around the file using cursor keys.
- Edit file.

2. Expected behaviour

- Status bar should be updated when navigating and editing files.
3. Observed behaviour

- Status bar doesn't get updated when navigating.
- Status bar disappears when file is edited. Never restored after that.

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load vim-airline
let &rtp .= ',~/.vim/bundle/vim-airline'

filetype plugin indent on
syntax enable

" vim-airline configuration
" unsure if necessary so included
set laststatus=2
set noshowmode
let g:airline#extensions#tabline#enabled=1
```

**Comment by dnivra** [comment]
Yes I am able to reproduce the issue with the files in `test/issues/926`. Here's my nvim version. Perhaps you're using a different version?

``` bash
$ nvim --version
NVIM 0.1.7
Build type: None
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1  -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-9avUof/neovim-0.1.7/build/config -I/build/neovim-9avUof/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-9avUof/neovim-0.1.7/build/src/nvim/auto -I/build/neovim-9avUof/neovim-0.1.7/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

If you require any other specific information, I can provide them.

**Comment by lervag** [comment]
Yes, I'm using version 0.2.0. Could you try to upgrade and see if it fixes things?

**Comment by lervag** [comment]
Also, could you check if things work as expected in regular Vim?

**Comment by dnivra** [comment]
Upgraded to neovim 0.2.0 and I can confirm this issue no longer occurs. Closing this issue.

**Comment by lervag** [comment]
Great, glad to hear it.

**Comment by rionda** [comment]
I'm experiencing the same issue on vim 8.2, but I'll investigate a bit and report back.

**Comment by rqy1458814497** [comment]
@rionda So how to solve the issue on vim8.2?

**Comment by rionda** [comment]
@rqy1458814497 Sadly, I never found a solution. I tried to get to the bottom of this issue, but got nowhere. I still experience it though :(

**Comment by jhossbach** [comment]
Can you open a new issue and provide some more details? I am using vim8.2 and i do not have this issue, but I'd be glad to help

**Comment by rionda** [comment]
@jhossbach what kind of information would you like, so I know what I should be collecting?
