### ISSUE TITLE
strange gaps when scrolling :VimtexInfo

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#929]
### Explain the issue

When scrolling in the `:VimtexInfo`/`\li` display, gaps appear in the list every other line making it difficult to follow.  The animation below demonstrates this.  It occurs in both vim/gvim.

[<img src='https://asciinema.org/a/EwETCuFt1ro7wtzRcwiT0QOcB.png'>](https://asciinema.org/a/EwETCuFt1ro7wtzRcwiT0QOcB)

### Minimal working example
```tex
\documentclass{scrbook}

\usepackage{amsmath, mathtools, geometry, hyperref}
\usepackage[basque]{babel}

\begin{document}
    Nothing
\end{document}
```

### Minimal vimrc file
```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
I've now added a minor scratch buffer feature that I use for the VimtexInfo. Please test. I've also improved/added a logging feature. This changes how messages are written as a side effect, but it allows one to easily see the history of log messages with `:VimtexLog` (or `\lq`). I find this convenient while debugging.

**Comment by andymass** [comment]
Seems to work well, thanks!   My only tiny criticism is when using splits, pressing q/<esc> closes the window which `:VimtexInfo` replaced.  Instead I have to remember to use `ctrl-6` to go back to what I was working on.

**Comment by lervag** [comment]
Thanks! I agree that's bad, so I've fixed it. It now also properly preserves the alternate file, which I think is the appropriate behaviour. And further, if you use the alternate file mapping, it will work similar to `q` and `<esc>`, also appropriate IMHO.
