### ISSUE TITLE
Citation completion for *cquote commands from csquotes

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#932]
[csquotes](https://www.ctan.org/pkg/csquotes) provides several commands that automatically generate a citation for quotes material. These are of the form `\textcquote[prenote][postnote]{key}[punct]{text}` (with the `c` inside. Would be nice if vimtext supported completion and proper highlighting of the references in these commands.

**Comment by lervag** [comment]
I am not quite sure I understand (perhaps I would if I read the csquotes manual, but no time right now). Could you elaborate a little? It would be very good if you could provide some clear examples of the kind of completion you want, as well as what would be proper highlighting.

It would also be very helpful with a minimal LaTeX example that I could use to experiment with.

**Comment by languitar** [comment]
```
\textcquote{Laprie1995}{This is quoted text}
```
In this case, the first argument `Laprie1995` is an entry from the bib file, for which I want completion (via deoplete). Right now, arguments to `\*cite` commands are also highlighted in green but such arguments to `csquotes` commands are not.

**Comment by lervag** [comment]
Are there more commands, or only `\textcquote`?

**Comment by languitar** [comment]
Yes (copied from the docs, the `h`s and `i`s are angle brackets incorrectly copied and pasted from the PDF):

Commands:
```
\textcquote[hprenotei][hpostnotei]{hkeyi}[hpuncti]{htexti}htpuncti
\textcquote*[hprenotei][hpostnotei]{hkeyi}[hpuncti]{htexti}htpuncti
\foreigntextcquote{hlangi}[hprenotei][hpostnotei]{hkeyi}[hpuncti]{htexti}htpuncti
\foreigntextcquote*{hlangi}[hprenotei][hpostnotei]{hkeyi}[hpuncti]{htexti}htpuncti
\hyphentextcquote{hlangi}[hprenotei][hpostnotei]{hkeyi}[hpuncti]{htexti}htpuncti
\hyphentextcquote*{hlangi}[hprenotei][hpostnotei]{hkeyi}[hpuncti]{htexti}htpuncti
\blockcquote[hprenotei][hpostnotei]{hkeyi}[hpuncti]{htexti}htpuncti
\foreignblockcquote{hlangi}[hprenotei][hpostnotei]{hkeyi}[hpuncti]{htexti}htpuncti
\hyphenblockcquote{hlangi}[hprenotei][hpostnotei]{hkeyi}[hpuncti]{htexti}htpuncti
\hybridblockcquote{hlangi}[hprenotei][hpostnotei]{hkeyi}[hpuncti]{htexti}htpuncti
```

Environments:
```
\begin{displaycquote}[hprenotei][hpostnotei]{hkeyi}[hpuncti]
\end{displaycquote}

\begin{foreigndisplaycquote}{hlangi}[hprenotei][hpostnotei]{hkeyi}[hpuncti]
\end{foreigndisplaycquote}

\begin{hyphendisplaycquote}{hlangi}[hprenotei][hpostnotei]{hkeyi}[hpuncti]
\end{hyphendisplaycquote}
```

**Comment by lervag** [comment]
Ok, I've started this. Could you let me know what you think? Note, so far, I've only added this for `textcquote`. If you think this looks good, I'll update the test files and add support for the other variants.

**Comment by languitar** [comment]
Nice, citation keys seem to be completed correctly. However, in combination with deoplete the completion doesn't list the citation details as for normal citation commands:
![2017-08-10t09 06 23 02 00](https://user-images.githubusercontent.com/1336287/29158480-7b7bc090-7dab-11e7-8140-848fc6f7f4b0.png)
![2017-08-10t09 06 55 02 00](https://user-images.githubusercontent.com/1336287/29158481-7b80d846-7dab-11e7-9056-858335b5154f.png)

**Comment by lervag** [comment]
Yes, I forgot to update the autocompleter patterns (including deoplete). I'll fix it later today.

**Comment by languitar** [comment]
Ok. The rest then seems to work fine :)

**Comment by lervag** [comment]
Ok, now I think it should work for all variants and with autocompletion for deoplete. Please test. :)

**Comment by languitar** [comment]
Seems to work well. But I didn't test all commands.
