### ISSUE TITLE
E716: Key not present in Dictionary: view

### ISSUE THREAD

**Issue by d4ff** [lervag/vimtex#937]
Hi,

I've been using vimtex with neovim without problems in the past, but after switching distros to Manjaro I get an E716 error when attempting to preview a .tex file with \lv.

\lo output:
```
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Viewing pdf
Rule 'pdflatex': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'test.tex'
------------
Run number 1 of rule 'pdflatex'
------------
------------
Running 'pdflatex  -file-line-error -synctex=1 -interaction=nonstopmode -recorder  "test.tex"'
------------
Latexmk: applying rule 'pdflatex'...
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017/Arch Linux) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./test.tex
LaTeX2e <2017-04-15>
Babel <3.10> and hyphenation patterns for 84 language(s) loaded.
(/usr/share/texmf-dist/tex/latex/base/article.cls
Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
(/usr/share/texmf-dist/tex/latex/base/size10.clo
)
)
 (./test.aux) [1
{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map
}
]
 (./test.aux) )</usr/share/texmf-dist/fonts/type1/public/amsfonts/cm/cmr10.pfb
>
Output written on test.pdf (1 page, 15303 bytes).
SyncTeX written on test.synctex.gz.
Transcript written on test.log.
Latexmk: Log file says output to 'test.pdf'
Latexmk: I have not found a previewer that is already running. 
   So I will start it for 'test.pdf'
------------
------------
Running 'start start acroread  "test.pdf"'
------------
=== TeX engine is 'pdfTeX'
Latexmk: All targets (test.pdf) are up-to-date
For rule 'view', running '&if_source(  )' ...
------------
Running '/usr/bin/nvim --servername /tmp/nvimewbteW/0 --remote-expr "vimtex#compiler#callback(1)"'
------------
sh: acroread: command not found
nvim: Unknown option argument: "--servername"
More info with "nvim -h"
```
I never had a problem with latexmk trying to start acroread in the past. I have been using mupdf through the following lines in my init.vim
```
" Vimtex settings
let g:tex_flavor = 'latex'
let g:Tex_DefaultTargetFormat='pdf'
let g:Tex_ViewRule_pdf='mupdf'
let g:vimtex_view_method = 'mupdf'
let g:Tex_CompileRule_pdf='pdflatex'
```
As part of my troubleshooting, I tried adding the followig line to `~/.latexmkrc`
`$pdf_previewer = 'start mupdf';`

This launched a preview in mupdf when I start compiling via \ll but, but I still get an E716 error when attempting to use \lv

I've never had to fiddle with resolving the --servername issue in nvim, in the past everything started working fine with those init.vim entries, and installing the texlive-latexextra packge.

Any help would be greatly appreciated.

**Comment by d4ff** [comment]
Problem resolved by installing xdotool. The error message was so brief that I didn't spot it.

**Comment by lervag** [comment]
You are mixing LaTeX-Suite options with vimtex. Are you trying to use both at the same time? If you are, then I hope you know what you are doing, else I would advice you not to do that. Also, _never_ install vim plugins through a package manager. That is just stupid. You should handle all plugins locally so that you know exactly which plugins you actually use. By installing globally, you are enabling plugins that are not clear from your vimrc file.

So, I suggest you do the following:

1. If you have LaTeX-Box or LaTeX-Suite (aka vim-latex) installed, please uninstall them.
2. Install [nvr](https://github.com/mhinz/neovim-remote).
3. Use the following options:

```vim
let g:tex_flavor = 'latex'
let g:vimtex_view_method = 'mupdf'
if has('nvim')
  let g:vimtex_compiler_progname = 'nvr'
endif
```
