### ISSUE TITLE
Is the main directory exposed somewhere?

### ISSUE THREAD

**Issue by dbmrq** [lervag/vimtex#938]
I often end up on a different directory and then I change to the current buffer's with `cd %:p:h`. On a multi file project I usually have to `cd ..` a couple of times to end up where I really want.

I just thought it would be handy to create a command (e.g. `CD`) to get me back to the main directory, but the `s:get_main()` function isn't exposed.

Is there already a way to do what I want? Is the main directory used by vimtex exposed somewhere so I can `cd` to it?

If it's not, would you be up to adding a command like the one I want, or maybe a `<Plug>`, or even just creating the `b:vimtex_main` variable if the user didn't already? I can (try to) do it and make a PR if you like the idea. It seems too much of a hassle to maintain my own fork for something so simple.

Thanks. :)

**Comment by andymass** [comment]
You can just grab the variable `b:vimtex.root`.  Is that the directory you're looking for?

**Comment by dbmrq** [comment]
Ah, awesome, that's what I was looking for. Thanks! 🍻
