### ISSUE TITLE
With g:vimtex_view_use_temp_files, copy file also if compilation failed

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#939]
In case of using `g:vimtex_view_use_temp_files = 1`, the compiled PDF is only copied to the name used by the PDF viewer if the compilation succeeded and not in case of errors. However, in the error case, the PDF might also provide hints where the actual problem is located. Therefore, it would be nice if the PDF was updated also in that case (at least optionally).

**Comment by lervag** [comment]
Ok, I've added a new mode to `g:vimtex_view_use_temp_files`. Set it to 2, and it will copy files also on failed compilations. However, it will not open/update the viewers unless the compilation was successful.

**Comment by languitar** [comment]
> However, it will not open/update the viewers unless the compilation was successful.

Why that? That would be exactly what I'd like to have.

**Comment by lervag** [comment]
Sorry, I misunderstood. How about now, does it work as expected?

**Comment by languitar** [comment]
First thing I notice, If I start compilation with a file that has an error, I get a viewer which doesn't show a file (black zathura).

**Comment by languitar** [comment]
When starting from a healthy document, this works as desired :)

**Comment by lervag** [comment]
Ah, yes. I guess the file is not always present. I think it is fixed now.

**Comment by languitar** [comment]
Works well now. Thanks!

**Comment by lervag** [comment]
No problem. :)
