### ISSUE TITLE
VimtexEventQuit doesn't really work

### ISSUE THREAD

**Issue by andymass** [lervag/vimtex#941]
### Explain the issue

This is really simple to reproduce.  1. Create an autocommand `au User VimtexEventQuit echo 'foo' | sleep 2` 2. Open a Tex file. 3. Open a not tex file in the same window.  4. Quit vim. 

It is clear the command is not being called.  

Another bug is if you open a Tex file multiple times the autocommand is added repeatedly, so if you close the tex file now, it is called multiple times.  

It is difficult to use this feature to do cleanup as the docs state.  

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
```

**Comment by lervag** [comment]
I think I've fixed this now. It is a little bit tricky, actually, to properly handle when Vim quits or deletes buffers. But I think the latest update should be correct in all cases (famous last words, or something). Let me know if you should find another edge case that is wrong.

**Comment by andymass** [comment]
Thanks, will test and get back.  You're a machine.  I'm trying really hard to not let the open issue count get too low :)

**Comment by lervag** [comment]
Yeah, I've noticed. Luckily, I've had some spare time lately to keep on top of the issue count. :)

**Comment by andymass** [comment]
Unfortunately, there are still a few problems.  I'm documenting them here, but I have not fully investigated the cause(s) yet.  I agree it's a tricky problem (with relatively minor impact), so feel free to ignore.

### 1. `VimtexEventQuit` is sometimes fired twice (sometimes even more).
MWE: directory structured as follows:
```
- minivimrc
- minimal.tex
- included.tex
- minimal.tex.latexmain
```

minivimrc:
```vim
set nocompatible
let &rtp = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'
filetype plugin indent on
syntax enable

let g:tex_flavor = 'latex'
augroup Testing
  autocmd!
  autocmd User VimtexEventQuit echo 'vimtex quitting '.bufname('%').'|'.b:vimtex_id | sleep 2
augroup END
```

included.tex:
```
% do nothing
```

minimal.tex
```tex
\documentclass{minimal}
\input{included}
\begin{document}
Hello World!
\end{document}
```

- Test: open as `vim -u minivimrc included.tex`, type `:q`
- Output:
```
vimtex quitting minimal.tex|0
vimtex quitting minimal.tex|0
```

I would expect it to be displayed only once.

### 2. `VimtexEventQuit` is fired before vim checks for changes

- Test: open as `vim -u minivimrc minimal.tex`, edit the file arbitrarily, then type `:q`.
- Output:
```
vimtex quitting minimal.tex|0
E37: No write since last change (add ! to override)
```

Seems strange.  I might expect no autocmd here since nothing is exiting.

### 3. Maybe `<nomodeline>` should be used?

Would you consider adding `<nomodeline>` to the `doautocmd`s, when supported?  E.g., `doautocmd <nomodeline> User VimtexEventQuit` and `doautocmd <nomodeline> User VimtexEventCompileStarted`, etc.  I believe this was introduced in `Vim 7.3.438`, Feb 2012.

**Comment by lervag** [comment]
You were right, there were some badly handled cases. However, it was not really correct that there should not be two messages. The reason this happens is because the included file is automatically creating a local `blob` which is used e.g. by the subfiles package for being able to compile only the subfile.

I'll try to explain what happens: When opening `included.tex`, we create two vimtex states. The first is for the main file, which becomes the current state. The second state is for the local file, i.e. for `included.tex`. When quitting, we are calling the cleanup function on both states, and each state issues the call to `VimtexEventQuit`. This should be expected, because it means it will e.g. stop compilation if one has started compilation in both states (which is possible in particular if one uses the subfiles package/system).

Regarding part 2: I agree this was strange. I think it is fixed now.

Finally, regarding 3: I'm not sure why this should be used. Please explain. Isn't the modeline only used when starting/creating a new buffer?

**Comment by andymass** [comment]
Thanks for your updates and the explanation.  I understand now why there are two in the case of `\input`.  I have switched to `b:vimtex.name` instead of `bufname` and everything seems to be working sensibly!

> Isn't the modeline only used when starting/creating a new buffer?

Actually, no :cry:.  `doautocmd User VimtexEventCompileStarted` triggers vim to re-parse the modeline regardless of when it's called (assuming the user has a matching receiving autocmd).  So, if the user has custom overrides (e.g., in `BufWinEnter`), compiling in vimtex resets them.  It is also a minor performance hit on each User autocmd and is pretty confusing.  I can't think of a good reason for needing to re-process modelines in these cases.

**Comment by lervag** [comment]
Thanks, I was not aware of this. I agree that it does not make sense to parse modelines while executing these autocmds. I've pushed the update. For now, I assume everyone has the patch; I'll update again if someone complains.

Again, thanks!

**Comment by andymass** [comment]
Thanks!  I have one last (possibly) related question.  When editing a multi-file project, each time I do `:e file.tex` to edit another file in the project, `s:vimtex.cleanup()` is called (twice, as we discussed).  Is this the expected behavior?

It would be fine except for one small detail- vimtex unconditionally closes the quickfix window [here](https://github.com/lervag/vimtex/blob/c64132d02d16c96cadac53e8cd054e1542761b53/autoload/vimtex/state.vim#L455), which makes navigating through a project (e.g. using grep) difficult.  I planned to make a PR which would first check to see if vimtex "owns" the quickfix, but I still don't completely understand the logic.  The quick-fix is per-project and should not be closed when switching between same-project files, whereas `s:vimtex.cleanup()` seems to operate on a per-file basis.

**Comment by lervag** [comment]
Yes, I can reproduce this if I do not have `set hidden`. I'm trying to be less rigid with cleaning up. How does the current version work for you?

**Comment by andymass** [comment]
Ah yes, I prefer `set nohidden`.  I did `vim -o test.tex ignore` and ran the following experiments separately, cursor starting in the `test.tex` window (buffer 1).  :skull_and_crossbones: denotes `VimtexEventQuit` being fired:

| action :arrow_right: | result :arrow_right: | action :arrow_right: | result :arrow_right: | action :arrow_right: | result | expected |
| --------- | --------- | --------- | --------- | --------- | --------- | ------ |
| `:q` | | `:q` | :skull_and_crossbones: | | | :+1: 
| `:bd` | | `:q` | :skull_and_crossbones: | | | :+1:
| `:bw` | :skull_and_crossbones: | `:q` | | | | :+1:
| `:bd` | | `:1bw` | | `:q` |  :skull_and_crossbones: | :-1:

The last case isn't a *problem* per se, since the event is still getting called, eventually, but it's a bit unexpected since after the `:bw` there is no trace of tex buffers in `:ls!`.

I also don't know how common it is for people to wipe their buffers.  Ordinarily, using `:q`, the user would basically never see the event (with vim defaults).  But, the `bd`/`bw` divide is at least logical and consistent with vim conventions.

Thanks again for iterating on this.  I am planning to improve the clarity of the documentation with respect to this feature and add another example (closing the viewer when appropriate.)  Will submit a PR when I get a chance.

**Comment by lervag** [comment]
Keeping track of these autocommands is not straightforward! But I think I've got it now. I think the last case should work as expected, please test.

**Comment by andymass** [comment]
One more.  If you switch away from a tex file before `:q`, `au User VimtexEventQuit VimtexClean` (out of the documentation) gives

     Error detected while processing User Auto commands for "VimtexEventQuit":
     E492: Not an editor command: VimtexClean

Using `au User VimtexEventQuit call vimtex#compiler#clean(0)` seems to work, so maybe this should be addressed in documentation instead of code.  Alternatively, you could force the command into existence at the right time.
```diff
diff --git a/autoload/vimtex/state.vim b/autoload/vimtex/state.vim
index cdd3302..c6df6c1 100644
--- a/autoload/vimtex/state.vim
+++ b/autoload/vimtex/state.vim
@@ -442,7 +442,17 @@ function! s:vimtex.cleanup() abort dict " {{{1
       let b:vimtex_tmp = b:vimtex
     endif
     let b:vimtex = self
+    if !exists(':VimtexClean')
+      echo 'doing' | sleep 1
+      command! -buffer -bang VimtexClean call vimtex#compiler#clean(<q-bang> == "!")
+      let l:undo_define_command = 0
+    endif
     doautocmd <nomodeline> User VimtexEventQuit
+    if exists('l:undo_define_command')
+      echo 'undoing' | sleep 1
+      delcommand VimtexClean
+      unlet l:undo_define_command
+    endif
     if exists('b:vimtex_tmp')
       let b:vimtex = b:vimtex_tmp
       unlet b:vimtex_tmp
```

**Comment by lervag** [comment]
Ah, yes. This is true, the commands are only available in the buffer and so will not necessarily be available when the VimtexEventQuit is fired.

I think perhaps that the best approach is to document this and ask users to rely on the function API. It should not be too difficult to use (at least not for experienced vimscript nerds).

Redefining VimtexClean is possible, of course, and sort of makes sense since it is one of those things a user might want to do on this event. However, I find it inconsistent. It also adds to the complexity of the code, which I think is already slightly "ugly". :\

What do you think? Would you mind if the autocommand would need the function API, if it were to be documented well? One could probably use the `vimtex#compiler#clean` as an example, since this is what most people probably wants.

**Comment by andymass** [comment]
Yes, I think addressing this in documentation is the cleaner way.  The functions are already well-named.  I've added my attempt in #951.

**Comment by lervag** [comment]
Great, thanks! I'll look into it when I get the time!
