### ISSUE TITLE
Multiple imaps for same binding depending on context do not work

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#945]
### Explain the issue

After the discussions in #563 and #566 I once came up with the following config in `ftplugin/tex.vim`:

```vim
call vimtex#imaps#add_map({
      \ 'lhs' : '<m-i>',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment',
      \ 'context' : ["itemize", "enumerate"],
      \})
call vimtex#imaps#add_map({
      \ 'lhs' : '<m-i>',
      \ 'rhs' : '\item[',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment',
      \ 'context' : ["description"],
      \})
```

This worked at least once and then stopped working at some point in time and I didn't track the reason. Today, by accident, I found out what is wrong. Only the second mapping works and so I only have completion in `description` environments. If I comment out the second mapping, `itemize` and `enumerate` work again.

With the context option and these clearly non-conflicting mappings, it would be nice, if I could use them in parallel again.

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\begin{itemize}
    %  no completion here for alt-i
\end{itemize}

\begin{description}
    %  completion works here
\end{description}

\end{document}
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable

" Vimtex options go here
```

`ftplugin/tex.vim`:
```vim
call vimtex#imaps#add_map({
      \ 'lhs' : '<m-i>',
      \ 'rhs' : '\item ',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment',
      \ 'context' : ["itemize", "enumerate"],
      \})
call vimtex#imaps#add_map({
      \ 'lhs' : '<m-i>',
      \ 'rhs' : '\item[',
      \ 'leader'  : '',
      \ 'wrapper' : 'vimtex#imaps#wrap_environment',
      \ 'context' : ["description"],
      \})
```

**Comment by lervag** [comment]
I've improved the wrapper. The old behaviour still works, but one can now also do this:

```vim
  call vimtex#imaps#add_map({
        \ 'lhs' : '<m-i>',
        \ 'rhs' : '',
        \ 'leader'  : '',
        \ 'wrapper' : 'vimtex#imaps#wrap_environment',
        \ 'context' : [
        \   {'envs' : ['itemize', 'enumerate'],
        \    'rhs' : '\item '},
        \   {'envs' : ['description'],
        \    'rhs' : '\item['},
        \ ],
        \})
```

That is, the `wrap_environment` function can take a context that has dict entries, if desired, which allows dedicated `rhs`s per environment.

**Comment by languitar** [comment]
Thanks, this works.
