### ISSUE TITLE
vimtex: Invalid viewer: qpdfview

### ISSUE THREAD

**Issue by chakravala** [lervag/vimtex#952]
Hello, I have had success with using zathura and vimtex together.

However, the qpdfview feature does not seem to work. If I set

```
let g:vimtex_view_method = 'qpdfview'
```
the error I get in vimtex is as follows

> vimtex: Invalid viewer: qpdfview
>         Please see :h g:vimtex_view_method
> Error detected while processing function vimtex#init[6]..<SNR>36_init_buffer[54]..vimtex#view#
> init_buffer:
> line    5:
> E716: Key not present in Dictionary: viewer, 'reverse_search')
> E116: Invalid arguments for function has_key(b:vimtex.viewer, 'reverse_search')
> E15: Invalid expression: has_key(b:vimtex.viewer, 'reverse_search')

It is possible to make it work if I set qpdfview as my system default viewer, but then the synctex forward search feature does not work (since it only uses default qpdfview command).

For zathura everything seems to work perfectly fine though.

Is this a bug or is this due to an issue on my end?

**Comment by andymass** [comment]
Sorry, but did you read `:help vimtex_viewer_qpdfview`?

**Comment by chakravala** [comment]
That command does not yield any results for me

> E149: Sorry, no help for vimtex_viewer_qpdfview

**Comment by chakravala** [comment]
Well, I found this snippet from issue #700 here:
```
let g:vimtex_view_general_viewer = 'qpdfview'
let g:vimtex_view_general_options = '--unique @pdf\#src:@tex:@line:@col'
let g:vimtex_view_general_options_latexmk = '--unique'
```
And that solves it for me now. Nevertheless, the `let g:vimtex_view_method = 'qpdfview'` command does not seem to be valid right now.

**Comment by andymass** [comment]
This is well documented in the help file `doc/vimtex.txt` (`:help vimtex`).  Perhaps you are using an old version of vim, an old version of vimtex, or you didn't update your help tags after installing.

**Comment by lervag** [comment]
As @andymass says, this is all well documented. Since the help file was not available, it is safe to assume that you were using an old version.
