### ISSUE TITLE
TeX compilation no longer working

### ISSUE THREAD

**Issue by Konfekt** [lervag/vimtex#954]
### Explain the issue

1. Type `:VimtexCompile<cr>`
2. Expected: Starts compiling
3. Instead: Gives Error message

```vim
Error detected while processing function vimtex#compiler#compile:
line    1:
E716: Key not present in Dictionary: compiler, 'continuous')
E116: Invalid arguments for function get(b:vimtex.compiler, 'continuous')
E15: Invalid expression: get(b:vimtex.compiler, 'continuous')
```

### Minimal TeX example

```tex
\documentclass{minimal}
\begin{document}

Hello World!

\end{document}
```

### Minimal vimrc file

Please provide a minimal vimrc file that reproduces the issue. The following
should often suffice:

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
```

**Comment by mircodezorzi** [comment]
I've installed vimtex on a fresh machine and I'm getting the same issue, how did you manage to solve it?

**Comment by mircodezorzi** [comment]
Looks like rebooting the machine fixed it.
