### ISSUE TITLE
can't open toc

### ISSUE THREAD

**Issue by theova** [lervag/vimtex#956]
Hello

If I type `:VimtexTocOpen`, I get the error:

> Fehler beim Ausführen von "function 83[7]..57":
> Zeile   38:
> E117: Unbekannte Funktion: strcharpart

in English:
> error while running "function 83[7]..57":
> line 38:
> E117: uknown function: strcharpart

and the Toc isn't opened at all....

A few days ago, I was able to open the toc, but I don't know, what has changed and causes the error.
Im relativly new to vim, so please let me know, if you need any additional informations.

Here is my setup:

### .vimrc:
```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable
```
### minimal working LaTeX example:

```tex
\documentclass{article}
\begin{document}
        \section{test}
        \section{another test}
\end{document}

Thank you for your help and the great vimtex-Plugin!

**Comment by kiryph** [comment]
Most likely your vim version is quite old and does not have the function `strcharpart()`.

This function has been added to vim in commit https://github.com/vim/vim/commit/58de0e2dcc1f2d251b74892a06d71a14973f3187 on April 14 Apr 2016 which is equivalent to the patch level 7.4.1730. 

Vimtex didn't use this function till recently: The commit https://github.com/lervag/vimtex/commit/a0a62d5faf9936f9e2cea683cfed5292e8f696f9 added the use of this function.

@lervag never specified the minimal vim version for vimtex.

You have to options just revert to the old vimtex version or get a newer vim version (many people like to have vim8 for various reasons).

**Comment by theova** [comment]
Thanks for your answer! Indeed, upgrading vim from 7.4 to 8.0 was the solution.

**Comment by lervag** [comment]
Thanks for pitching in, @kiryph! You are right, I've never specified a minimal version. I recognize that this is not quite "best practice", but it makes things easier for me. :)

@theova I'm happy to hear things work after updating Vim, and I hope it was not too inconvenient for you to update.

**Comment by theova** [comment]
@lervag No worries! Thanks for the great plugin!

**Comment by kiryph** [comment]
@theova and @lervag you are welcome.

It would be great to have a tool to identify automatically the required vim version for a plugin. I had encountered similar issues with other plugins when authors added vim functions without knowing that this changes the minimal required vim version.

I consider this a more important weakness of the vim plugin ecosystem than the often mentioned absence of plugin dependency tracking. Running the update function of vundle/neobundle/dein/minpack/plug can easily lead to the situation that things break and the authors are not aware of this. Adding a CI test to ensure compatibility with the minimal specified vim version would instantaneously report such a change. vim 7.4.1730 is just one year and a few months old and I guess many user could run into this issue.

**Comment by lervag** [comment]
Yes, I agree. I actually do just that, although my tests do not test all the code. I'm testing on Vim 7.4.50 (or something close to that). Thus, my intention really is to support approximately version 7.4. But this is the first issue related to Vim versions I've had in a while.

I could change the relevant code though, so as to support older Vim versions. But since it won't really help any users, as far as I know, I would rather spend my time on solving the other issues...

**Comment by kiryph** [comment]
So, theoretically speaking if vimtex would have 100% test coverage, CI tests would have complained.
100% coverage does not sound feasible, in particular, for one-man open source project.

When vim 7.4.50 is your inofficially intended version, do you plan to change it now to 7.4.1730?

IMHO, adding a vim required line, which emits a message to the user, would be informative and would not cost you much time. Most plugins start with a header like this
```viml
if exists("g:loaded_abolish") || &cp || v:version < 700
  finish
endif
```
You could adjust this for vimtex to check for vim version 7.4 and patches which have been known to be required (like this one).
```viml
" vimtex - LaTeX plugin for Vim
"
" Maintainer: Karl Yngve Lervåg
" Email:      karl.yngve@gmail.com
"

if !get(g:, 'vimtex_enabled', 1)
  finish
endif

if exists('b:did_ftplugin')
  finish
endif
let b:did_ftplugin = 1

if v:version < 704
  finish
endif

if !has("patch-7.4.1730") 
  echoerr "vimtex not loaded: vim patch 7.4.1730 required for strcharpart()"
  finish
endif

call vimtex#init()

" vim: fdm=marker sw=2
```

Does this sound manageable? If someone needs support for an older version, you could ask her/him to suggest implementations to avoid the need of the patches missing in their vim version.

**Comment by lervag** [comment]
Yes, this actually sounds reasonable. I'll implement something like this, but I'll add an option to ignore the version check (i.e. load vimtex and ignore problems with versions). I'll keep this open for now to remember to do it.

**Comment by lervag** [comment]
I've added a version check with a comment in the docs now. What do you think, @kiryph?

**Comment by kiryph** [comment]
Perfect.
IMHO this can help, in particular new user, figuring out why the plugin does not work in certain situations. For example, people using *Debian 8* (aka *Jessie*, released on 26th April 2015) are on vim version 7.4.488 (https://packages.debian.org/jessie/vim). *Debian 9* (*Stretch*, released on 17th June 2017) provides already vim version 8.0.0197.

**Comment by lervag** [comment]
I agree, I should probably have added this years ago. Better late than never, though. :)

**Comment by kiryph** [comment]
I just stumbled on following plugin showing in vim help version numbers: https://github.com/tweekmonster/helpful.vim

If somebody is really into this, he/she could feed the tag database of helpful.vim into a grep search to find all functions used within a vim plugin repo to identify the newest vim built-in function w.r.t. the date it was added to vim.

**Comment by lervag** [comment]
That would be cool. I won't do it, as I have too much else going on at the moment. But it looks like a fun task. If anyone were to do something like that, it seems it could make for a useful plugin/tool.
