### ISSUE TITLE
Error when the path name has the symbol `~`

### ISSUE THREAD

**Issue by aragonl** [lervag/vimtex#957]
### Explain the issue
I updated to vimtex latest version a few days ago and a new error started to appear when opening any .tex file located in a folder whose path has the symbol `~` . It gives the following error:

>     Error detected while processing function vimtex#init[5]..25_init_state[1]..vimtex#state#init[9]..3[29]..9[5]..vimtex#paths#relative:
>     E33: No previous substitute regular expression

with the E33 repeating several times. This is quite inconvenient for the projects I have in my iCloud folder since the system names the directory `com~apple~CloudDocs` and even if I change the name with a link the problem persists.

### Minimal working example

```tex
\documentclass{minimal}
\begin{document}
Hello World!
\end{document}
```

### Minimal vimrc file

```vim
set nocompatible              " required
filetype off                  " required
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'lervag/vimtex'
call vundle#end()            " required
filetype plugin indent on    " required
```

**Comment by lervag** [comment]
This should be fixed now, thanks for reporting!
