### ISSUE TITLE
dollar sign ($) breaks syntax highlighting in bib files

### ISSUE THREAD

**Issue by sga001** [lervag/vimtex#958]
When using the \$ inside a bib entry (e.g., in the title field) the rest of the document loses all highlighting.
For example, everything in my bib file after the "title" line in the following bib entry loses its highlighting.

```bib
@misc{helloworld,
  author = {nobody},
  title = {I wish I had \$1000},  % also breaks if you do "I wish I had \$1000" or {{I wish I had \$1000}}
  year = {2017},
}
```

I'm running neovim 0.2.0. I also have the latest vimtex version: (commit 65dbbcf331fc1e0b9690412c7b99c0777e9c2485).

Let me know if anyone can reproduce this. I hope it's not something in my setup.

**Comment by lervag** [comment]
Sorry for the slow response. You closed this with no comment. I'm curious why?

In any case, I would also have closed it. The reason: vimtex does not provide syntax highlighting of bibtex files. This is provided by the included vim plugins. The current version that ships with neovim and Vim is written by Bernd Feige, last changed September 12, 2016. I propose that you send him an email if you think you have found a problem with syntax highlighting of bib files.
