### ISSUE TITLE
problem determining latex main file

### ISSUE THREAD

**Issue by heiderich** [lervag/vimtex#960]
### Explain the issue

There seems to be a problem with the correct determination of the main latex file in the following situation

1. Steps to reproduce

Create files with the following contents:

```
$ cat test.tex
\documentclass[10pt]{article}
\usepackage{import}
\begin{document}
\input{test_main.tex}
\end{document}

$ cat test2.tex
\documentclass[10pt]{article}
\usepackage{import}
\begin{document}
\input{test2_main.tex}
\end{document}

$ cat test_main.tex
\subimport{dir/}{appendix_test}

$ cat test2_main.tex
\subimport{dir/}{appendix_test2}

$ cat dir/appendix_test.tex 
\input{ab.tex}

$ cat dir/appendix_test2.tex 
\input{abc}

$ cat dir/ab.tex 
ab
$ cat dir/abc.tex 
abc
```

Then open dir/ab.tex

```
vim dir/ab.tex
```

and compile it

```
:call vimtex#init()
:VimtexCompile
```

Note: With the minimal vimrc file as below I needed `:call vimtex#init()`. With my normal vimrc vimtex is loaded fine and the problem I describe here also occurs.

2. Expected behaviour

test.tex gets compiled and test.pdf is displayed.

3. Observed behaviour

test2.tex gets compiled and test.pdf is displayed.

### Minimal working example

See above

### Minimal vimrc file

```vim

set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

filetype plugin indent on
syntax enable
```

**Comment by andymass** [comment]
@lervag just skimming through, [this regex](https://github.com/lervag/vimtex/blob/770b5183d621eb5a0c8bbee7e05bbceff2d2c4f7/autoload/vimtex/state.vim#L318) should probably be anchored on the right somehow.

**Comment by lervag** [comment]
First: Use `let g:tex_flavor = 'latex'` in your vimrc file (and the minimal vimrc file) to recognize simple included latex files as latex and not plaintex. See `:h g:tex_flavor` for more info.

**Comment by lervag** [comment]
Thanks, with the thorough issue description and suggested solution I was able to fix this quickly. I think it works and I think it should not break anything else. :)

**Comment by lervag** [comment]
And thanks, @andymass, again, for taking the time to look into the issue! It was very helpful and probably saved me quite some time!
