### ISSUE TITLE
Clicking into table of contents (or labels) directly jumps to the entry under the cursor

### ISSUE THREAD

**Issue by edwardtulane** [lervag/vimtex#962]
I would expect that when I click into the table of contents window, it just gets activated and that double-click will jump to the selected entry. This is, for example, how tagbar and nerdtree behave, which I use everyday. Instead, single click jumps and double click jumps and closes (but only if the toc window is activated). 

Is this the intended behaviour or is it related to my particular setup? If it is intended, can I enforce my preferred behaviour somehow?

What I am using is vim 8.0.1159 in KDEs konsole on an arch linux machine with the latest vimtex version installed through vim-plug.
The minimal vimrc I just tried is
```
set nocompatible
filetype plugin indent on
syntax on
set mouse=a

call plug#begin()
Plug 'lervag/vimtex'
call plug#end()
```

Thank you!

**Comment by lervag** [comment]
I actually have no idea. I really never use the mouse with Vim, and I have no idea what is the expected behaviour for using the mouse in the table of contents window. I also don't know how to change the behaviour or control what the mouse does.

If anyone does know and is able to tell me what to do to make this work as should be "expected", then I won't mind implementing it. But I will never use this myself, and I have too much else to do, so I will not use my time to figure this one out by myself. Sorry.

**Comment by andymass** [comment]
This is all that is necessary to get OPs expected behavior:
```diff
diff --git a/autoload/vimtex/index.vim b/autoload/vimtex/index.vim
index 845ca5b..954a1b5 100644
--- a/autoload/vimtex/index.vim
+++ b/autoload/vimtex/index.vim
@@ -74,9 +74,8 @@ function! s:index.create() abort dict " {{{1
   nnoremap <silent><buffer> q             :call b:index.close()<cr>
   nnoremap <silent><buffer> <esc>         :call b:index.close()<cr>
   nnoremap <silent><buffer> <space>       :call b:index.activate(0)<cr>
-  nnoremap <silent><buffer> <leftrelease> :call b:index.activate(0)<cr>
+  nnoremap <silent><buffer> <2-leftmouse> :call b:index.activate(0)<cr>
   nnoremap <silent><buffer> <cr>          :call b:index.activate(1)<cr>
-  nnoremap <silent><buffer> <2-leftmouse> :call b:index.activate(1)<cr>

   call self.syntax()
   call self.refresh()
```

@edwardtulane do you think there should be a way to select and close with the mouse?  If so, what would it be?

**Comment by edwardtulane** [comment]
Oh, thank you! That works just fine! Honestly, I have no preference for jump+close because I keep the toc open all the time. Also, as I just checked, neither tagbar nor nerdtree seem to have a mouse mapping for this, so I guess it is ok if this remains unassigned?

**Comment by lervag** [comment]
Thanks, @andymass!
