### ISSUE TITLE
Links in quicksfix errors work only in current working directory

### ISSUE THREAD

**Issue by theova** [lervag/vimtex#963]
#### working set
If I start vim with  
`$ cd Documents/`
`$ vim something.tex`,
I can go to an error in the quickfix-window and hit enter to jump to the corresponding line. Nice feature!

#### Not working set 
If I start vim with `$ vim` and do `:e Documents/something.tex`, I have the following inappropriate behaviour: 
I can go to an error in the quickfix-window. But when I hit enter, a file in my home directory called "something.tex" will be created and opened. Instead, I expect, that the file "Documents/something.tex" will be opened.

I'm using vim 8.0 in Ubuntu 16.04 LTS.

**Comment by lervag** [comment]
Thanks. I will look into this. I am afraid that this is not easy to fix, though, and there have been several issues related to similar things. But I don't remember exactly the conclusions, and I think it might be OK to look into it again.

Note, though, that there is a severe limitation on reading the latex log for errors. In multi-file projects, things will not always work perfectly, and I can't fix that. That is unrelated to this issue, but I just wanted to mention it.

**Comment by lervag** [comment]
I think this should work now, at least for "most cases". Unfortunately, as said before, it is very difficult to parse the errors properly for complex/large (multi-file) projects.

**Comment by theova** [comment]
Wonderful, it works!

Thank you very much!

**Comment by lervag** [comment]
No problem, thank you for reporting the problem! :)
