### ISSUE TITLE
spaces in v:progpath prevents callback from working on Windows

### ISSUE THREAD

**Issue by JackeJR** [lervag/vimtex#966]
As the title suggests. The default installation path for vim Windows is `C:\Program Files\Vim\vim80`. The space in `Program Files` is tripping up the call back. The relevant `VimtexCompileOutput` is below.

Looking at the full path for `g:vimtex_compiler_progname` and from the compile output, I see 2 sets of double quotes. I assume some escaping either by `fnameescape` or `shellescape` is going on already so using something like  `let g:vimtex_compiler_progname = fnameescape(v:progpath)` or the `shellescape` variant doesn't work. Manually trying to escape the space with either `\` or `^` also doesn't work.

```
------------
Running '""C:\Program Files\Vim\vim80\gvim.exe"" --servername GVIM --remote-expr vimtex#compiler#callback(1)'
------------
'""C:\Program' is not recognized as an internal or external command, operable program or batch file.

```

Workaround:
Put the default installation path into your `PATH` and add `let g:vimtex_compiler_progname = v:progname` within your `vimrc`.

For reference:
```
*g:vimtex_compiler_progname*
  Path to vim executable.  This is used for the callback functionality, and it
  must be set correctly in order for the callback function to work.  The
  default value should work correctly in most cases, but in some cases, e.g.
  for MacVim, one might need to set it manually to get the callbacks to work
  as expected.

  Default value: |v:progpath| if it exists, else |v:progname|.
```

Setup:
- Windows 10 Pro x64
- gvim 8.1159
- vimtex (ae0b194), used with latexmk
- StrawebryPerl 5.26.1.1
- TexLive 2017, updated today

By the way, thanks for the great software and supporting Windows users despite not using Windows and I know the path handling issues are a pain for Windows.

**Comment by lervag** [comment]
Thanks for the thorough issue description and for the kind words at the end. As you might have understood, I've spent some time trying to get things to work reliably on windows. See e.g. #882.

I think one way to "solve" this is to write a new entry in the docs. As you can see from #882, it seems very difficult to find a reliable way to escape the progname variable. :\

**Comment by lervag** [comment]
#882 is probably relevant, but I meant to refer to #736.
