### ISSUE TITLE
Viewer cannot view PDF file

### ISSUE THREAD

**Issue by IWinarto** [lervag/vimtex#971]
Hi, I'm trying to make Vimtex use SumatraPDF. I'm using gVim 8.0.3 on Windows, and I've added SumatraPDF to my Path. However, `\lv` gives me the following error:

```
vimtex: Viewer can not read PDF file!
             C:\Users\someone\Desktop/test.pdf
```

I don't know what's wrong and I don't know why it tries to use forward slash on Windows.

My minimum _vimrc:

```
execute pathogen#infect()

let g:vimtex_view_general_viewer = 'SumatraPDF'
let g:vimtex_view_general_options = '-reuse-instance -forward-search @tex @line @pdf'
let g:vimtex_view_general_options_latexmk = '-reuse-instance'

syntax on
filetype plugin indent on
```

**Comment by lervag** [comment]
Can you try to add `set shellslash` or `set noshellslash`?

Also, can you confirm that the file `C:\Users\someone\Desktop\test.pdf` exists on your system (you have compiled the document)?

**Comment by IWinarto** [comment]
`set shellslash` and `set noshellslash` do not help. I still get the same error.

`\ll` and `:VimtexCompile` do not produce the expected pdf document, but they also do not produce any error message. Both commands give me this message: `vimtex: compiler started in continuous mode`.

I have installed latexmk using MikTex package manager.

My simple .tex file is just 
```
\documentclass{article}
\begin{document}
test test test
\end{document}
```

**Comment by IWinarto** [comment]
Nvm. Turns out I didn't have Perl installed on my Windows yet. So, vimtex is all good and working now. Thanks @lervag for your help.

**Comment by lervag** [comment]
No problem, happy to hear it works :)
