### ISSUE TITLE
Invalid expression: g:vimtex#toc#matchers#included.init(a:content[0][0])  

### ISSUE THREAD

**Issue by dbmrq** [lervag/vimtex#973]
I'm writing my masters thesis and it's a huge project split into many files. When I try to open Vimtex's TOC I get the following errors:

```
Error detected while processing function 138[7]..112[19]..114:
line   17:
E684: list index out of range: 0
E116: Invalid arguments for function 128
E15: Invalid expression: g:vimtex#toc#matchers#included.init(a:content[0][0])  
```

It doesn't happen with other projects and I couldn't figure out what exactly about this one triggers the problem, so I can't make a minimal example yet, but I thought maybe you could figure out what's up with that `content` argument anyway. If not I'll keep trying to come up with a reasonable example.

Thanks for the great work with Vimtex, as usual. :)

**Comment by lervag** [comment]
If you edit the file `autoload/vimtex/toc.vim` in or close to line 171 you shoud find where this comes from. You can add some echo debugging lines, e.g.:

```
unsilent echom string(a:content)
unsilent echom string(a:content[0])
```

This should help you to see what is happening. Note, though, that `a:content` is supposed to keep the content of your entire LaTeX document.

**Comment by lervag** [comment]
I suspect something wrong might be happening with `vimtex#parser#tex` in line 89 of the same file.

**Comment by dbmrq** [comment]
Ok, I did that and `a:content` seems to be completely empty:

```
[]
Error detected while processing function 138[7]..112[19]..114:
line   18:
E684: list index out of range: 0
E116: Invalid arguments for function string(a:content[0])
E15: Invalid expression: string(a:content[0])
```

And if I `echom string(l:content)` before line 97 it's also an empty array.

**Comment by lervag** [comment]
Interesting. Could you investigate this closer on your own in a similar fashion? I.e., `l:content` should be filled through `vimtex#parser#tec` after line 88. What is the value of `b:vimtex.tex`? What is the output of `\li`? In `parser.vim` around line 163, you could investigate what the values of `l:line` are. They should be the lines of your manuscript files.

**Comment by dbmrq** [comment]
Uhm, that's odd.

I checked `b:vimtex.tex` and it's `~/USP/Mestrado/Dissertação/base`, without the `.tex` extension, that apparently should be there. That causes `filereadable(a:file)` to return `false` on that `parser.vim` function and `l:content` isn't populated.

I thought the problem could be related to the diacritics in "Dissertação", so I moved the files to a different directory… and the problem was fixed. *But* then I renamed the directory and called it "Dissertação" – and the TOC still worked fine! So it appears that now everything's working properly, just because I moved the files to a different directory and back. They are now at the same exact place they were, on a directory with the same name, and everything's working fine. I don't know what caused the `.tex` extension to be omitted before, but apparently it wasn't the diacritics. 🤷‍♂️

**Comment by lervag** [comment]
That's odd, I agree. If you were to reproduce this, let me know. There might be a bug in the code that collects the main file name.

In the meantime, I'm closing this as fixed. :)

**Comment by dbmrq** [comment]
Since I have the same exact files at the same exact path I'm thinking it could have something to do with Vim auxiliary files that are save elsewhere, like `directory`, `backupdir`, or `~/.vim/view` for `mkview`. Some of these files may have been flushed when I copied and moved things around and maybe that's what fixed the problem.

Anyway, I'll let you know if it happens again.

Thank you for your help. ❤️

**Comment by lervag** [comment]
No problem! Good luck on your thesis :)
