### ISSUE TITLE
Syntax with `<>`, includegraphics and beamer

### ISSUE THREAD

**Issue by Gagbo** [lervag/vimtex#976]
I'm using beamer to prepare a presentation and when I use the command `\includegraphics` I have all the good syntax highlights and features (Omni completion to images) that I'd like... except when I use the superposition feature with [the angle brackets](https://en.wikibooks.org/wiki/LaTeX/Presentations#Text_animations).

Note that in the examples there,  `\only<num>{\include...}` syntax is used, but `\includegraphics<num>....` works perfectly also, and this more compact syntax is what I am using.

I suppose this minimal tex document will be enough to see the issue (even without trying to compile). If it's not I'll provide more info if I can.

```tex
\documentclass{beamer}
\begin{document}

\begin{frame}
    \includegraphics[height=0.5062\linewidth]{test.png} % Highlights and omnicomplete no problem
    \includegraphics<2>[height=0.5062\linewidth]{test.png} % Doesn't highlight at all past \includegraphics
\end{frame}

\end{document}
```

**Comment by lervag** [comment]
I've added some simple highlighting of `\only<...>`, `\item<...>` and `\includegraphics<...>`. Let me know what you think.

**Comment by Gagbo** [comment]
Sorry for being late, it looks good ! Thanks for the help

**Comment by lervag** [comment]
No problem! :)
