### ISSUE TITLE
Syntax highlighting of  \label[⟨type ⟩]{⟨label ⟩} provided by cleveref

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#977]
I've noticed that you have already added support for syntax highlighting of the LaTeX package [`cleveref`](https://ctan.org/pkg/cleveref). Therefore I think you would consider also adding support for following extended notation of `\label[⟨type ⟩]{⟨label ⟩}` also provided by `cleveref`. See chapter `6 Overriding the Cross-Reference Type` in its [documentation](http://mirrors.ctan.org/macros/latex/contrib/cleveref/cleveref.pdf).

```tex
\crefname{pluralequation}{eqs.}{eqs.}
...
\label[pluralequation]{eq1}
```

I guess I would expect syntax groups as follows:
`\label[<texCmdArgs/texOption>]{<texRefZone>}`

**Comment by lervag** [comment]
I think this should suffice.

**Comment by kiryph** [comment]
Thanks for the update. I only miss that the curly braces are not in the syntax highlighting group `Delimiter` but are in `texRefRangeStart`.

![screen shot 2017-10-16 at 11 18 20](https://user-images.githubusercontent.com/371756/31604489-c575eba2-b263-11e7-848a-cf34be634ff4.png)

That would mean the curly braces would be gray in the colorscheme used in the picture above.

**Comment by lervag** [comment]
I've modified accordingly. Note, though, that I think you really ask for the delimiters to be highlighted as `texStatement`. In any case, let me know what you think about the change.

**Comment by kiryph** [comment]
Looks good. Right now the characters are in following groups

- `\label` -> `texStatement`
- `[` and `]` -> `Delimiter texLabelOpts texStatement`
- text in square brackets -> `texLabelOpts texStatement`
- `{` -> `Delimiter texLabelRef`
- text in curly braces -> `texLabelRef`
- `}` -> `Delimiter`

which work as desired. I am not entirely sure what you mean with 
> to be highlighted as `texStatement`.

IMHO the color of the curly braces should be consistent, e.g. with the curly braces in `\begin{subequations}` which is now the case.

There is one thing I am wondering whether there should be a general approach to handle
`\texstatement[optional arguments]{mandatory arguments}...` instead of adjusting it for every command.

**Comment by lervag** [comment]
> to be highlighted as `texStatement`.

With this I mean when compared with `\label{test}`. The commands that are used for references and citations seem to include the delimiters in the `texStatement` group. Note that this is not from vimtex, but from the internal syntax plugin. However, I agree on the consistency, and so I've updated the highlighting again to make it more consistent.

> There is one thing I am wondering whether there should be a general approach to handle
`\texstatement[optional arguments]{mandatory arguments}...` instead of adjusting it for every command.

It is sort of handled generally, but not quite. For instance, all the reference specific statements are handled so as to highlight references differently. Similar for verbatim commands. But most commands are handled "correctly" with a general highlighting.

**Comment by kiryph** [comment]
> With this I mean when compared with \label{test}. The commands that are used for references and citations seem to include the delimiters in the texStatement group. Note that this is not from vimtex, but from the internal syntax plugin.

Sorry, I missed that the default syntax highlighting behaves this way. As far as I see at least following commands color the braces the same color as the command:

![screen shot 2017-10-17 at 09 54 01](https://user-images.githubusercontent.com/371756/31652928-1ffb7606-b321-11e7-9227-32282a9fa230.png)


I am not sure anymore what would be the best. I can see also a reason to use the same color as for the command. Sometimes fewer colors are less distracting.

### `texCmdArgs`

Another thing, which I noticed, is that often options in square brackets for commands are in the groups `texDocTypeArgs` and `texInputFileOpt` which both link to `texCmdArgs` which is again linked to the `Number`. See above picture for `a4paper` as an option for `\documentclass`, `fleqno` as an option for`\usepackage{amsmath}` and `width=...` for `\includegraphics`. Maybe `texCRefLabelOpts` could also be linked to `texCmdArgs`. What do you think?

**Comment by lervag** [comment]
To be honest, I find the main syntax plugin to be quite messy, and it would be an interesting and fun project to write a new and improved one. However, I don't quite feel up for the task right now (too much to do), but perhaps someday I will.

I agree with linking `texCRefLabelOpts` to `texCmdArgs`.
