### ISSUE TITLE
vim auto-suspends when opening LaTeX file

### ISSUE THREAD

**Issue by Champitoad** [lervag/vimtex#980]
After vimtex last update, each time I'm trying to open a .tex file, vim gets suspended automatically:
`"<filename>" 156L, 7498C[1]  + 8990 suspended (tty output)  vim -p <filename>`
Of course I can get back to vim with `fg`, but then some features won't work properly, like moving around with the arrow keys.

I shall add that this only happens when the file has some minimum LaTeX content, like the `\documentclass` line.

Also I don't have any vimtex specific config in my vimrc, I'm just loading it with vim-plug (btw the issue won't happen if I disable vimtex). I noticed though that the issue won't happen if I disable zsh's interactive mode:
`set shell=/bin/zsh " without -i option`

**Comment by lervag** [comment]
Could you please provide a minimal vimrc and LaTeX file that reproduces this?

**Comment by Champitoad** [comment]
vimrc (with vim-plug installed):
```
set shell=/bin/zsh\ -i

call plug#begin('/home/pablo/.vim/plugged')
Plug 'lervag/vimtex'
call plug#end()
```
mwe.tex:
```
\documentclass{article}
```

**Comment by lervag** [comment]
Ok, I've reproduced. The error occurs because vimtex uses `system()`, and for some reason, adding the `-i` flag suspends vim. I don't see why this happens. But I don't understand why you want to add the `-i` flag. As far as I see, there is no reason to add this...?

**Comment by lervag** [comment]
It seems you can solve this with `set shell=/bin/zsh\ -l`, see [here](https://github.com/zaiste/vimified/issues/89). See also here:

https://apple.stackexchange.com/questions/199520/suspended-tty-output-when-launching-editors-like-vim-vi-emacs-or-nano

http://zsh.sourceforge.net/Guide/zshguide02.html (section 2.1)

**Comment by Champitoad** [comment]
Ok I've read the resources you pointed out, and it seems I'll just have to give up on the `-i` flag. I wanted to keep it so I have access to all the aliases loaded by oh-my-zsh that I can't move to `~/.zshenv` from `:!` shell invocation, but I guess I'll go with `:sh` from now on :)

**Comment by lervag** [comment]
I see. I understand that this seems convenient, but IMHO, if you are doing a lot of shell commands from Vim, then you should consider running a terminal alongside your vim for the shell commands. In any case, if you were to find any other solutions to this, I would be willing to make changes for this to work. But based on my understanding, it seems like using `-i` is not quite recommended.
