### ISSUE TITLE
Fail to silent the warning

### ISSUE THREAD

**Issue by xu-cheng** [lervag/vimtex#981]
### Steps to reproduce the problem:

* Create file `test.tex` with following content:
```tex
\documentclass{article}
\usepackage[backend=bibtex]{biblatex}
\begin{document}
Hello World!
\end{document}
```
* Create file `test.vim` with following content:
```vim
set nocompatible

" Load Vimtex
let s:vimtex_path = '~/.config/nvim/plugged/vimtex'
let &rtp  = s:vimtex_path . ',' . &rtp . ',' . s:vimtex_path . '/after'

filetype plugin indent on
syntax enable

let g:maplocalleader = '-'
let g:vimtex_compiler_method = 'latexmk'
let g:vimtex_quickfix_latexlog = {'default' : 0}
```
* Open neovim using `nvim -u test.vim test.tex`. 
* Compile the latex file by `<maplocalleader>ll`.
* Open the quickfix window by `<maplocalleader>le`. There will be a warning shown in the quickfix window though all warnings are explicitly disabled by `let g:vimtex_quickfix_latexlog = {'default' : 0}`. The warning is:
```
test.tex|| Package biblatex Warning: Using fall-back BibTeX(8) backend: functionality may be reduced/unavailable.
```

**Comment by lervag** [comment]
Sorry, there was a minor bug in the initialization where the `default` key was not properly distributed to the package specific settings.
