### ISSUE TITLE
Several sandwich-* links in help pages are broken if vim-sandwich is not installed

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#984]
The help pages contain several links for `vim-sandwich` configuration that are currently pointing to nowhere if `vim-sandwich` is not installed. Is it common to link to potentially non-existing anchors?

These are the links:
* |sandwich-miscellaneous|
* |sandwich-filetype-recipes|

**Comment by lervag** [comment]
Yes, I actually think this is quite common. At least I've seen other people doing the same. The idea is to make it easy to jump to relevant documentation whenever possible. I can see that this may be confusing, but I find the benefit outweighs the cons.

Do you have any good reason _not_ to use links here?

**Comment by languitar** [comment]
I like the links, I was just confused that they pointed nowhere when I tried to find out whether sandwich is an option for me or not.

**Comment by lervag** [comment]
Ok. Well, I could add a note about that, but I would rather not. If it is OK by you, I'll close this as your question has been answered. If you do think that we should update the docs, then I would be happy if you could suggest how to update.

**Comment by languitar** [comment]
I actually have no real idea how to improve this. Maybe vim could at least color broken links differently, but that also doesn't tell the user that the package is required for this link to work.

**Comment by lervag** [comment]
Perhaps, but this discussion should be raised at the Vim repo, I think.
