### ISSUE TITLE
highlighting in starred math environments

### ISSUE THREAD

**Issue by nilsbecker** [lervag/vimtex#986]
when i change the environment between align* and align, the font highlighting changes. this is on macvim, with cseelus/vim-colors-lucid color scheme.

could it be that vimtex does not recognize the starred environments as math for highlighting?

**Comment by lervag** [comment]
That's strange. For me, both `align` and `align*` are highlighted the same. They are actually different groups: `align` gives `texMathZoneA`, whereas `align*` gives `texMathZoneAS`. But these are linked by default to `texMath`.

To see what highlightings are used, you can do

```vim
:[verbose] high texMathZoneA
:[verbose] high texMathZoneAS
```

With `verbose` prepended, you will also get information about where the highlighting was defined.

**Comment by lervag** [comment]
Btw, you might be interested in reading `:h vimtex-syntax` to understand how vimtex does not really provide a syntax plugin, instead it only improves on the syntax plugin that ships with Vim. Vimtex does not modify the highlighting of `align` or `align*` environments.

**Comment by lervag** [comment]
IMHO that is bad practice; why would they want to have a different highlighting of `texMathZone` and `texMath`? In any case, this is obviously subjective and they are free to do as they want. I'm glad the case is solved. :)
