### ISSUE TITLE
pplatex is not executable

### ISSUE THREAD

**Issue by coreyjherr** [lervag/vimtex#990]
I have pplatex installed and it properly executes in my shell, however I get the error

"pplatex is not executable!"

This happens for any .tex file.
A minimal  .vimrc that replicates this is

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

" Vimtex options go here
let g:vimtex_quickfix_method='pplatex'

**Comment by kiryph** [comment]
What does following command in the shell tell you?

```sh
❯ ls -l `which pplatex`
-rwxr-xr-x  1 kiryph  staff  81000 May 19 16:50 /Users/kiryph/.local/bin/pplatex
```

And can you execute `pplatex` in vim's commandline by yourself:

```
:!pplatex %
:!which pplatex
```

I would suspect that `pplatex` is not in vim's search path which can be different to the one of your shell.
You can compare both by
```
❯ echo $PATH | tr ':' '\n' | sort | uniq
:!echo $PATH | tr ':' '\n' | sort | uniq
```
There is a note about possible reasons for differences of the environment variable `$TEXMFHOME` in the documentation of vimtex `:help vimtex-faq-texmfhome`. This applies if you use `gvim`, `mvim`, `vimr` or another gui version of vim.

**Comment by lervag** [comment]
Thanks, @kiryph! It seems you were spot on.

@coreyjherr Since you closed the issue, I assume things are now working. If not, feel free to reopen.
