### ISSUE TITLE
Async doesn't work with arara

### ISSUE THREAD

**Issue by zoqaeski** [lervag/vimtex#992]
### Explain the issue

I'm in the process of switching to `arara` to compile my documents, and I've noticed that no matter the settings for `g:vimtex_compiler_arara`, it always runs with async off.

I'm using neovim, which should have asynchronous job control enabled by default.

### Minimal vimrc file

These are the settings for vimtex in my vimrc:

```vim
" VimTex
Plug 'lervag/vimtex', {'for' : ['tex', 'latex']}
    let g:tex_flavor = 'latex'
    let g:vimtex_format_enabled = 0
    let g:vimtex_fold_enabled = 1
    let g:vimtex_compiler_method = 'arara'
    let g:vimtex_compiler_arara = {
        \ 'backend' : 'nvim',
        \ 'background' : 1,
        \ 'options' : ['-v'],
        \}

    let g:vimtex_view_automatic = 1
    let g:vimtex_view_method = 'general'   
```

**Comment by lervag** [comment]
First, a minor note: vimtex is a filetype plugin, so there is no need to use the `{'for' : ['tex', 'latex']}` option to vim-plug. You won't get any noticable increase in start up time, and you loose the ability to open the vimtex documentation before you open a `tex` file.

Further, there is no need to specify the already default options. Your list of options may be reduced to:

```vim
let g:tex_flavor = 'latex'
let g:vimtex_fold_enabled = 1
let g:vimtex_compiler_method = 'arara'
```

Next, could you please provide the output of `\li` or `:VimtexInfo` after you have opened a (minimal) LaTeX file and started compilation with `\ll`?

**Comment by zoqaeski** [comment]
I've made the changes to my configuration, and then done a test with the very basic file below. When I start compilation the input waits until it's finished—the statusline reports "Compiling to pdf … (async off!)" every time.

```
\documentclass[11pt]{scrartcl}

\begin{document}

\section{Test Page}

This is a test of compiling with Arara.

\end{document}
```

The output of `:VimtexInfo` on that file is:
```
System info
  OS: nd not found: lsb_release
  Vim version: NVIM v0.2.1-1122-g54b79f19d
  Has clientserver: true
  Servername: /tmp/nvim8vgwxt/0
  Plugin conflicts: LaTeX-Box

vimtex project: arara
  base: arara.tex
  root: /home/zoqaeski/documents/latex/tests
  tex: /home/zoqaeski/documents/latex/tests/arara.tex
  out: /home/zoqaeski/documents/latex/tests/arara.pdf
  log: /home/zoqaeski/documents/latex/tests/arara.log
  aux: /home/zoqaeski/documents/latex/tests/arara.aux
  fls: /home/zoqaeski/documents/latex/tests/arara.fls
  document class: 
  compiler: arara
    backend: nvim
    output: /tmp/nvim8vgwxt/2
    configuration: 
      arara options:
        -v
  viewer: General
  qf: LaTeX logfile
    config: 
      fix_paths: 1
      packages: 
        default: 1
      default: 1
```

**Comment by lervag** [comment]
Could you show the output of `\lo`?

Also: If you see in the `System info`, there is a plugin conflict with LaTeX-Box. I strongly suggest that you solve this, as it might lead to unexpected behaviour. Actually, I think this is exactly what is happening now. Vimtex does not ever write that output.

For some reason, a lot of people find the [vim-polyglot](https://github.com/sheerun/vim-polyglot) plugin very desirable. My guess is that you are using this. I also strongly recommend against that, since it means you are adding things that you do not quite understand to your Vim setup. However, if you want to keep using it, then you can probably solve the problem by adding

```vim
let g:polyglot_disabled = ['tex']
```

to your vimrc file.

**Comment by lervag** [comment]
See also #930, #313, #454, #450.

**Comment by zoqaeski** [comment]
Ah, I totally missed that. I've been reworking my neovim configuration over the last couple of days as well, and I added the polyglot plugin at around the same time, though I had some misgivings that it might have been a potential conflict point. I think the main advantage of it is that it includes so many highly-rated language-specific additions it saves the effort of tracking them all down and trying various things until you find a set that you like.

This wasn't a bug, it was my own fault. Thanks for helping bisect it though, and I apologise for wasting some of your time. (I've added a comment to my configurations to double-check conflicts with polyglot before reporting bugs in the future.)

**Comment by lervag** [comment]
I can see why people want to use polyglot, but IMHO, it does not take that much time to add desired plugins manually (and thus knowingly) for the filetypes one cares about.

In any case, no problem. I'm happy to help. I hope you find most other things working as expected! :)

**Comment by fgheng** [comment]
> Could you show the output of `\lo`?
> 
> Also: If you see in the `System info`, there is a plugin conflict with LaTeX-Box. I strongly suggest that you solve this, as it might lead to unexpected behaviour. Actually, I think this is exactly what is happening now. Vimtex does not ever write that output.
> 
> For some reason, a lot of people find the [vim-polyglot](https://github.com/sheerun/vim-polyglot) plugin very desirable. My guess is that you are using this. I also strongly recommend against that, since it means you are adding things that you do not quite understand to your Vim setup. However, if you want to keep using it, then you can probably solve the problem by adding
> 
> ```viml
> let g:polyglot_disabled = ['latex']
> ```
> 
> to your vimrc file.

thank you very much
