### ISSUE TITLE
Support counts for [[, ]], [], and ][

### ISSUE THREAD

**Issue by kiryph** [lervag/vimtex#993]
Consider following tex file:
```tex
\documentclass{article}

\begin{document}

\chapter{section 1)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.

\chapter{section 2)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.

\chapter{section 3)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.

\chapter{section 4)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.

\chapter{section 5)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.

\end{document}
```

Jumping to the section beginnings with `]]` (forwards) / `[[` (backwards) and section ends `][`(forwards) / `[]` (backwards) do not accept counts. For example: `3]]` should move the cursor to the beginning of section 3 when the cursor is on line 1.

`<count>[[`, `<count>]]`, `<count>[]`, `<count>][`

I came across this feature when trying out the plugin https://github.com/Houl/repmo-vim. I raised an issue about supporting `]]`-family mappings. However, it turned out in order to repeat those ft-specific vertical motions, these ft-specific mappings must be defined properly with support for counts. Please read the comments by the author of repmo-vim https://github.com/Houl/repmo-vim/issues/1#issuecomment-342246547.

**Comment by lervag** [comment]
This sounds sensible, in that the default versions already support counts. I'll look into it.

**Comment by lervag** [comment]
There, I think this should work. There might be a "better way" (tm), but I don't expect updated code to fail. However, as always, let me know if you find edge cases I didn't think about! :)

**Comment by kiryph** [comment]
Thanks for adding support for counts. Right now, I could not find any corner case 😄 .

### Add note to the documentation
Maybe you want to add a hint about the support for counts to the documentation:
```diff
❯ git diff
diff --git a/doc/vimtex.txt b/doc/vimtex.txt
index dcb3a00..64d5810 100644
--- a/doc/vimtex.txt
+++ b/doc/vimtex.txt
@@ -2099,16 +2099,16 @@ Map definitions~
   Find matching pair.

 *<plug>(vimtex-]])*
-  Section forward (inclusive).
+  [count] sections forward (inclusive).

 *<plug>(vimtex-][)*
-  Section forward (exclusive).
+  [count] sections forward (exclusive).

 *<plug>(vimtex-[])*
-  Section backward (inclusive).
+  [count] sections backward (inclusive).

 *<plug>(vimtex-[[)*
-  Section backward (exclusive).
+  [count] sections backward (exclusive).
```
---
### `inclusive (]],][)` vs. `exclusive([[,[])`  and equivalent meaning of built-ins for LaTeX

I am actually struggling a little bit with the meaning of these motions in vimtex.

Does the note about *exclusive* and *inclusive* refer to the description under `:h exclusive`?

As far as I assume, *exclusive* and *inclusive* under `<plug>(vimtex-]])`,... refer to whether the section search term (e.g. `\section{}`) is included. However, I am confused for `[[` and `[]` which I would have denoted the other way around.
Could you explain it to me?

If the description under `:h exclusive` actually applies, this should be mentioned. In any case, I would be a little bit more specific what inclusive and exclusive mean.

BTW, the behavior of the built-in motions `[[,]],[],][` (see `:h [[`) are all `exclusive` with the meaning of *exclusive* described under `:h exclusive` with the note that often `exclusive-linewise` applies.

From my point of view one can describe the built-in motions `][` and `[]` as following:
> `[]` and `][`: go to end of previous scope/section and go to end of current/next scope/section

I think this is different to the motions of vimtex. I try to illustrate this with an example file.

### Current Situation
```tex
\begin{document}

\chapter{section 1) % [[[[ exclusive (cannot be repeated anymore)
%[][] inclusive (cannot be repeated anymore)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.

\chapter{section 2) % [[ exclusive
% [] inclusive
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
<CURSOR>
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.
%][ exclusive (cannot be repeated anymore)

\chapter{section 3) % ]] inclusive (cannot be repeated anymore)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.

\end{document}
```

### Variant inspired by builtin moitions: go to prev/next end of scope
```tex
\begin{document}

\chapter{section 1) % [[[[ (cannot be repeated anymore)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.
% [] (end of previous scope) (cannot be repeated anymore)

\chapter{section 2) % [[ (begin of current scope)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
<CURSOR>
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.
% ][ (end of current scope)

\chapter{section 3) % ]] (beginning of next scope) (cannot be repeated anymore)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.
% ][][ (cannot be repeated anymore)

\end{document}
```

Compare for example the equivalents for python in [`$VIMRUNTIME/ftplugin/python.vim`](https://github.com/vim/vim/blob/master/runtime/ftplugin/python.vim#L35-L38)

```python
class previous:             # [[[[

    def method_first:
        pass
    # ...

    def method_last:
        pass                # []

class current:              # [[ or [m...[m[m

    def method_first:       # [[]m or [m...[m
        pass                # [[]M or [M...[M
    # ...

    def method_previous:    # [m[m
        pass                # [M

    def method_current:     # [m
        # CURSOR <---------------------------
        pass                # ]M

    def method_next:        # ]m
        pass                # ]M]M
    # ...

    def method_last:        # ][[m or ]m...]m
        pass                # ][   or ]M...]M

class previous:             # ]]   or ]m...]m]m

    def method_first:
        pass
    # ...
```

I guess it might be quite difficult to identify section endings and therefore changing it to `go to next/previous end` might be more difficult than the current solution. I also see a purpose for the `inclusive` motions as defined by vimtex.

**Comment by kiryph** [comment]
From the vim user manual `29.3 Moving through a program` to illustrate the built-in behavior

### MOVING IN CODE BLOCKS
In C code blocks are enclosed in {}. These can get pretty long. To move to the start of the outer block use the "[[" command. **Use "][" to find the end.** This assumes that the "{" and "}" are in the first column. The "[{" command moves to the start of the current block. It skips over pairs of {} at the same level. "]}" jumps to the end. An overview:
```c
                    function(int a)
       +->          {
       |                if (a)
       |       +->      {
    [[ |       |            for (;;)               --+
       |       |      +->   {                        |
       |    [{ |      |         foo(32);             |     --+
       |       |   [{ |         if (bar(a))  --+     | ]}    |
       +--     |      +--           break;     | ]}  |       |
               |            }                <-+     |       | ][
               +--          foobar(a)                |       |
                        }                          <-+       |
                    }                                      <-+
```
When writing C++ or Java, the outer {} block is for the class. The next level of {} is for a method. When somewhere inside a class use "[m" to find the previous start of a method. "]m" finds the next start of a method.
**Additionally, "[]" moves backward to the end of a function** and "]]" moves forward to the start of the next function. The end of a function is defined by a "}" in the first column.
```c
                            int func1(void)
                            {
                                    return 1;
              +---------->  }
              |
          []  |             int func2(void)
              |        +->  {
              |    [[  |            if (flag)
    start     +--      +--                  return flag;
              |    ][  |            return 2;
              |        +->  }
          ]]  |
              |             int func3(void)
              +---------->  {
                                    return 3;
                            }
```

IMHO, this actually describes what the purpose of `[]` and `][` are:

> Use "][" to find the end.

and

> Additionally, "[]" moves backward to the end of a function

There are actually more ftplugins with definitions of `[[`, `]]`, `[]`, `][`:
- **vimscript** https://github.com/vim/vim/blob/master/runtime/ftplugin/vim.vim#L40-L47
- **ruby** https://github.com/vim/vim/blob/master/runtime/ftplugin/ruby.vim#L165-L181
- **markdown** https://github.com/plasticboy/vim-markdown/blob/master/ftplugin/markdown.vim#L624-L627

**Comment by kiryph** [comment]
### Plugin ninja-feet to operate till start/ end of text object

There is the nice plugin https://github.com/tommcdo/vim-ninja-feet which allows to use the existing vimtex text objects. Consider you are in the last chapter of your thesis:

```tex
\begin{document}

% ...

\chapter{Last Chapter) % [[
[] Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
<CURSOR>
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.

second paragraph

third paragraph

\end{document}
```

The motions `]]` and `][` will not work. But with `ninja-feet` you can delete till end of the current chapter with `d]iP`.

**Comment by lervag** [comment]
Wow, you've really done a depth study of this, I'm impressed.

So, I think the current behaviour is close to OK, but I agree that `[]` must be changed and that it seems I need to better handle the last section/chapter. Thus something like this should be good:

```tex
\begin{document}

\chapter{section 1) % [[[[ exclusive (cannot be repeated anymore)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.
%[] inclusive (cannot be repeated anymore)

\chapter{section 2) % [[ exclusive
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
<CURSOR>
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.
%][ exclusive

\chapter{section 3) % ]] inclusive (cannot be repeated anymore)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.
%][][ exclusive (cannot be repeated anymore)



\end{document}
```

(I now see this is what you called the Vim-variant.) I think this should be relatively easy to implement. A minor detail, though: Should the `][` and `[]` mappings include the empty lines or not? I.e.

```tex
\chapter{section 2)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
<CURSOR>
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.
%][ exclusive


\chapter{section 3)
```

or

```tex
\chapter{section 2)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
<CURSOR>
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.


%][ exclusive
\chapter{section 3)
```

Regarding the `exclusive` vs `inclusive`, I don't think I was thinking about the Vim concepts. Perhaps it is better to not use these terms here?

**Comment by kiryph** [comment]
> Wow, you've really done a depth study of this, I'm impressed.

Yeah, things got a little bit out of hand. I've actually done this for the plugin `vim-repmo`. I thought that you might want to know how other ftplugins handle this. The markdown reference could have been sufficient. However, markdown plugins handle this not really consistently and give me the impression plugin authors do only a limited check how their mappings fit into existing vim mappings. I have here in particular the popular https://github.com/plasticboy/vim-markdown in mind.

> So, I think the current behaviour is close to OK

I feel the same way.

> but I agree that [] must be changed and that it seems I need to better handle the last
> section/chapter.

Well, I am not sure how to do this without breaking existing behavior which, as just has been said, is useful.

> Thus something like this should be good:
> ```
> ...
> ```

Well, this would be the 'vim-way' and would change existing behavior.

If they are changed to resemble to jump to end of current or previous section, vim-ninja-feet could help to operate to just before the section line with `d[iP` (old behavior). However, no motion would exist.

If this your plan, I am happy with this either.

> I think this should be relatively easy to implement. A minor detail, though: Should the ][ and [] mappings include the empty lines or not? I.e.

I am not entirely sure. Empty lines have semantic meaning in latex. However, sections are ended with the start of a new section command and therefore blank lines are not necessary here and only serve the purpose of code readability.

Intuitively (without putting too much thought into it) I would expect followg

```tex
ending of last paragraph of previous chapter. % []

\chapter{Last Chapter} % [[
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
<CURSOR> % ]] does not do anything
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.

Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. %][

\end{document}
```
That means without blank lines.

> Regarding the exclusive vs inclusive, I don't think I was thinking about the Vim concepts. Perhaps it is better to not use these terms here?

IMHO the meaning of inclusive/exclusive in vimtex should be explained in the docs and other terms should be used to avoid that a user confuses them.

**Comment by lervag** [comment]
Well, I don't really have a plan, except trying to make things work the way it should. In this case, I sort of agree that the current behaviour actually works quite well, so perhaps it is better to keep this and update the docs.

I'm pushing a change now, let me know what you think.

**Comment by kiryph** [comment]
I have thought about this a little bit more and I am pretty sure I would start using the mappings `[]` and `][` if they would be changed to move to the end of the current/previous section (to be more precise to the line end of the last non-empty line of a section).

Actually, the text objects `iP` and `aP` should already know how to detect section boundaries which might help you to imlement this functionality more easily.

I hope I don't annoy you by changing my mind.

**Comment by lervag** [comment]
No problem. I don't really use these mappings myself, and I also think I might use them more if they are changed. Thus I will change it when I get the time.

**Comment by lervag** [comment]
I think this should be an improvement. Let me know what you think.

**Comment by kiryph** [comment]
I like it. `][` works now also in the last section. I have following thoughts about it:

1. I would prefer the first variant you asked previously

>  minor detail, though: Should the ][ and [] mappings include the empty lines or not? I.e.
```
\chapter{section 2)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
<CURSOR>
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.
%][ exclusive


\chapter{section 3)
```
or
```
\chapter{section 2)
Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
<CURSOR>
vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
no sea takimata sanctus est Lorem ipsum dolor sit amet.


%][ exclusive
\chapter{section 3)
```

2.  😇  I think the `exclusive` behavior of the builtin `}` could be resembled, i.e. the documented exceptions should be taken into account.   Just for clarification: `exclusive` and `inclusive` affect the behavior when using **operators**; see the help again:

> When **inclusive**, the start and end position of the motion are included in the operation.
> When **exclusive**, the last character towards the end of the buffer is not included [in the operation].
> Linewise motions always include the start and end position [when used after an operator].
> 
> There are however, two general exceptions:
> 1. If the motion is exclusive and the end of the motion is in column 1, **the
>    end of the motion is moved to the end of the previous line** and the motion
>    becomes inclusive.  Example: "}" moves to the first line after a paragraph,
>    but "d}" will not include that line.
> 						*exclusive-linewise*
> 2. If the motion is exclusive, the end of the motion is in column 1 and the
>    start of the motion was at or before the first non-blank in the line, the
>    motion becomes linewise.  Example: If a paragraph begins with some blanks
>    and you do "d}" while standing on the first non-blank, all the lines of
>    the paragraph are deleted, including the blanks.  If you do a put now, the
>    deleted lines will be inserted below the cursor position.

This would mean for `][`. Starting with following situation:
![screen shot 2017-11-27 at 11 16 59](https://user-images.githubusercontent.com/371756/33261848-87406bce-d364-11e7-9afb-1d18ebd572d2.png)

Yellow block is the cursor. `d][` should do the same as `d2}` (switch to linewise (exception 2) and should delete before the last blank line of the current section(exception 1)). However right now you get

![screen shot 2017-11-27 at 11 20 49](https://user-images.githubusercontent.com/371756/33261996-0aa82a10-d365-11e7-9790-71e8b985c37a.png)

but I would expect (`d2}`):

![screen shot 2017-11-27 at 11 24 33](https://user-images.githubusercontent.com/371756/33262137-8fcc9f64-d365-11e7-8a29-44d7be6e4437.png)

**Comment by lervag** [comment]
Ok. I've updated accordingly. I ended up writing the code slightly differently. Let me know if that broke anything unexpected.

**Comment by kiryph** [comment]
Looks good.

**Comment by lervag** [comment]
Great. It's fascinating how difficult it is to get this sort of thing "just right". I would not be surprised if there is a minor bug or two, but it seems to work well.
