### ISSUE TITLE
Reload current file's info

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#994]
Vimtex stores VimtexInfo even for buffers which were closed. When the buffers are reopened Vimtex reuses stored info. This behavior may be undesired in case, for example, when user wants Vimtex to determine the main file.

This happens under the following workflow:
1.  In the main latex file type `\subfile{dir/subfile.tex}`.
2. Open new file `dir/subfile.tex` in new tab.
3. Define it as a subfile:
```tex
\documentclass[main.tex]{subfiles}

\begin{document}
\end{document}
```
4. Write.
5. Use `\ls` to switch to local.
6. Since the file was opened without any contents, the main file is not determined, the working directory is set to `dir/` while in the case of `subfiles` it is desired to keep it to `.`.

I expect `vimtex` to determine the main file after the file is written. Unfortunately:
1. Closing the buffer and reopening it does not help.
2. There is no function to drop the saved information.

Of course, there is `VimtexReload` command, but I assume that it is the overkill for such a task.  

I think, that dropping (may be optional) VimtexInfo for closed buffer would solve the issue.

**Comment by lervag** [comment]
This raises the need for a state local reload function. The current reload function reloads everything. I'll look into it when I get the time.

**Comment by lervag** [comment]
I've added a new command that I think should fix this: `VimtexReloadState`.

**Comment by maxfl** [comment]
I'm getting the following error:
```
function vimtex#state#reload:                                                                                                                                                                                  
line    3:
E488: Trailing characters:     l:vimtex = remove(s:vimtex_states, l:id)
line    4:
E121: Undefined variable: l:vimtex
```
I've tried vim 8.0 (1271) and neovim 0.2.1.

**Comment by lervag** [comment]
Sorry about that! Fixed now.

**Comment by clason** [comment]
This also works for applying `TeX program = ` directives after the file is loaded (#713), right?

**Comment by lervag** [comment]
It should, yes.

**Comment by maxfl** [comment]
Works perfectly for subfiles. Thank you.

Unfortunately I'm unable to test it for the `%! TEX root =` directive. For a some reason it fails for files, located in sub folders. I've tried both relative and absolute paths with no luck.

I will try later again and will submit a new issue in case it's needed.

**Comment by lervag** [comment]
Hmm. In the first version, I only changed the state of the data for the current file, not for the entire project. But I think we should also reload the entire project. E.g., if I work on a standard project with 2 files, edit the included file `chapter.tex`, then I would expect the `VimtexReloadState` to reload the project state.

I'm fixing this now.
