### ISSUE TITLE
`vimtex` fails to open compilation output if the buffer was changed to non-tex file

### ISSUE THREAD

**Issue by maxfl** [lervag/vimtex#995]
The compilation output callback sticks to the currently active buffer and may fail to find `b:vimtex` variable.

1. Open any compilable `main.tex` file.
2. Open `readme.txt` in another tab.
3. Switch to `main.tex` and run background compilation with `\ll`.
4. While compilation is running switch to the `readme.txt` tab.
5. When compilation is done the error shows up that variable `b:vimtex` is not defined.

**Comment by lervag** [comment]
I was not able to reproduce this, but I think it is fixed in the latest commit. Please test.

**Comment by maxfl** [comment]
No more failures after the update. Thank you!
