### ISSUE TITLE
Support for list-like environments defined with enumitem

### ISSUE THREAD

**Issue by languitar** [lervag/vimtex#996]
### Explain the issue

With the `enumitem` package on can define derived list environments using the `\newlist` command.
It would be nice if those environments could be parsed so that for instance custom keybindings for these environments work correctly.

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\usepackage{enumitem}
\begin{document}

\newlist{mydesc}{description}{1}
\setlist[mydesc]{font=\normalfont\itshape,style=nextline}

\begin{mydesc}
    % alt-i as configured in #946 should work here, they don't right now
\end{mydesc}

\end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable
```

`ftplugin/tex.vim`

```vim
  call vimtex#imaps#add_map({
        \ 'lhs' : '<m-i>',
        \ 'rhs' : '',
        \ 'leader'  : '',
        \ 'wrapper' : 'vimtex#imaps#wrap_environment',
        \ 'context' : [
        \   {'envs' : ['itemize', 'enumerate'],
        \    'rhs' : '\item '},
        \   {'envs' : ['description'],
        \    'rhs' : '\item['},
        \ ],
        \})
```

**Comment by lervag** [comment]
I can see how this is convenient, but it is also very specialized. Also, I would think you typically use the same names for the custom lists. Thus, I would think you could simply solve this yourself by adding the custom lists to the current `<m-i>` mapping.

**Comment by languitar** [comment]
Hm, usually I defined those lists on a per-project basis with names matching their use case. So I would have to configure the mappings again for each project. I could live with that, but some automatic way would definitely be easier.

**Comment by lervag** [comment]
I still think this is not quite material for being part of vimtex. However, I've written a small code snippet that you could use in your `after/ftplugin/tex.vim` to get something like what you want. This also adds the custom lists to `g:vimtex_indent_lists` for proper indentation.

```vim
function! s:add_list_mappings() abort
  let l:lists = {
        \ 'desc' : ['description'],
        \ 'item' : ['itemize', 'enumerate'],
        \}

  for [l:new, l:type] in map(filter(
        \   vimtex#parser#tex(b:vimtex.tex, {'detailed': 0}),
        \   'v:val =~# ''\\newlist{'''),
        \ 'matchlist(v:val, ''{\([^}]*\)}{\([^}]*\)}'')[1:2]')
    if l:type ==# 'description'
      call add(l:lists.desc, l:new)
    else
      call add(l:lists.item, l:new)
    endif
  endfor

  call vimtex#imaps#add_map({
        \ 'lhs' : '<m-i>',
        \ 'rhs' : '',
        \ 'leader'  : '',
        \ 'wrapper' : 'vimtex#imaps#wrap_environment',
        \ 'context' : [
        \   {'envs' : l:lists.item, 'rhs' : '\item '},
        \   {'envs' : l:lists.desc, 'rhs' : '\item['},
        \ ],
        \})

  let g:vimtex_indent_lists = l:lists.item + l:lists.desc
endfunction

call s:add_list_mappings()
```

**Comment by lervag** [comment]
Note, if the `\newlist` commands are all in the preamble, then you could modify slightly to avoid parsing the entire LaTeX document:

```vim
        \   vimtex#parser#tex(b:vimtex.tex, {
        \      're_stop': '\\begin{document}',
        \      'detailed': 0,
        \     })
```

**Comment by languitar** [comment]
Thanks for the additional work! I'll test that in my document.

**Comment by lervag** [comment]
No problem, I hope it works :)
