### ISSUE TITLE
Single-line "\begin..\end" blocks break indenting

### ISSUE THREAD

**Issue by albertfgu** [lervag/vimtex#999]
### Explain the issue

Indentation is broken when a \begin{} \end{} environment is contained in a single line.

### Minimal working example

Please provide a minimal working LaTeX example, e.g.

```tex
\documentclass{minimal}
\begin{document}

\[
  1 2 3
I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix} # This line is not indented
\]

$I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$
  Rest of the document is indented


  Hello World!

  \end{document}
```

### Minimal vimrc file

```vim
set nocompatible

" Load Vimtex
let &rtp  = '~/.vim/bundle/vimtex,' . &rtp
let &rtp .= ',~/.vim/bundle/vimtex/after'

" Load other plugins, if necessary
" let &rtp = '~/path/to/other/plugin,' . &rtp

filetype plugin indent on
syntax enable

let g:tex_flavor='latex'
```

### Expected behavior
A \begin{} \end{} block that is contained in a single line should not affect any indenting.

### Observed behavior
There are several cases when the indent level is changed unexpectedly. See the minimal working example.

**Comment by lervag** [comment]
I think this should be fixed now.
